### ISSUE TITLE
Depend on more packages

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10012]
Should `dask[complete]` or the `dask` conda meta package depend on more stuff?  `lz4`?  `prometheus_client`?  `pyarrow`?

cc @jacobtomlinson @fjetter @jrbourbeau 

This came up in conversation internally at Coiled with people being sad that Promeetheus metrics weren't always present.  We can inject this dependency in separately (so it's not a huge driver here) but I suspect that no one has reviewed our "complete" dependencies in a while and this might be a good time to revisit there.

**Comment by fjetter** [comment]
+1 for extending `complete` but I'm not entirely sure what the extended subset should be

I think an argument could be made for `complete` shipping with everything that is necessary to make all dask features work (excluding all the various file formats)

Having pyarrow around will enable P2P, lz4 enables network compression, ...

However, strictly speaking this would also mean we should be adding `(python-)graphviz`, `crick`, one of a couple of choices for hashing libs (`cityhash`, `xxhash`, `mmh3`), `scipy` (for `array.fft`, `array.stats`), possibly `cytoolz`
This "rule" would even include `jupyter_server` and `ipython` which is not a good idea, I think.

---

Principles aside, adding `lz4` and `pyarrow` makes a lot of sense to me and I believe much more users will benefit from this than take harm.
`prometheus_client` is something probably only few will benefit from but the lib itself is very small and doesn't have any dependencies itself so I don't see any harm.

From an UX perspective, I would also love to see `graphviz` installed (or am I very biased as a developer here? I like dask.visualize)

**Comment by mrocklin** [comment]
I don't think that this should be a principled / rule-based decision.  I think that it should be made with some human thought.

**Comment by jacobtomlinson** [comment]
I'm +1 on expanding `complete`. I agree that in general installing everything to turn on most features makes sense. I rarely pip install Dask so I'm assuming this conversation also covers the conda feedstock?

I agree that `prometheus_client` would be nice to have around all the time. There have been discussions about switching to OTEL instrumentation though, I haven't looked at the package for that but it would be good to check that it is similarly lightweight.

I would also like `graphviz` to be around more but am I right in thinking you can't `pip` install that? Only `conda` or `apt + pip`?

**Comment by jrbourbeau** [comment]
I've pushed up https://github.com/dask/dask/pull/10023 which adds `pyarrow` and `lz4` to the `[complete]` extra. Folks should feel free to drop any comments they may have there. 

> I would also like graphviz to be around more but am I right in thinking you can't pip install that? Only conda or apt + pip?

That's correct. One needs to install both the python bindings from PyPI and the system graphviz package. We could add `ipycytoscape`, which can be install as a standalone package form PyPI, but I've not looked into what other dependencies that would bring in. Regardless, I think https://github.com/dask/dask/pull/10023 is useful as is
