### ISSUE TITLE
[pyarrow strings] consistently handle `string[pyarrow]` in `MultiIndex`

### ISSUE THREAD

**Issue by j-bennet** [dask/dask#10025]
**Describe the issue**:

Follow-up for https://github.com/dask/dask/pull/10000.

These tests failed with `pyarrow` strings and were xfailed, but we still need a fix:

```
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_multiprocessing[disk] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_multiprocessing[tasks] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_dropna_with_agg[disk-True] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_dropna_with_agg[disk-False] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_dropna_with_agg[tasks-True] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_dropna_with_agg[tasks-False] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_sort_argument[disk-True-count-by4] - AssertionError: MultiIndex level [1] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_sort_argument[disk-False-count-by4] - AssertionError: MultiIndex level [1] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_sort_argument[tasks-True-count-by4] - AssertionError: MultiIndex level [1] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_sort_argument[tasks-False-count-by4] - AssertionError: MultiIndex level [1] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_slice_getitem[disk-3-by0] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_slice_getitem[tasks-3-by0] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_rolling.py::test_groupby_rolling - AssertionError: MultiIndex level [0] are different
```

It looks like when we're grouping on multiple columns in Dask, the resulting `MultiIndex` inherits the `string[pyarrow]` dtype from its parent columns.

However, in `Frame` constructor, we don't use this dtype to convert the `MultiIndex` yet.

**Environment**:

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by j-bennet** [comment]
Already fixed:

```
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_multiprocessing[disk] - AssertionError: MultiIndex level [0] are different
FAILED dask/dataframe/tests/test_groupby.py::test_groupby_multiprocessing[tasks] - AssertionError: MultiIndex level [0] are different
```

**Comment by j-bennet** [comment]
There are two different ways we could fix this:

1. Not use`string[pyarrow]` dtype in `MultiIndex` yet.
2. Consistently use `string[pyarrow]` dtype in MultiIndex.

Right now there's an inconsistency: we don't convert `MultiIndex` in `Frame` constructor, so initially `MultiIndex` with have `object` in `dtypes`. But when we're grouping on `string[pyarrow]` columns, the resulting `MultiIndex` will have `string[pyarrow]` dtypes.

Question is, which way do we want to go? I'm leaning towards the 2nd.

**Comment by jrbourbeau** [comment]
Yeah, I think we will ultimately want option (2). I initially punted on `MultiIndex` support for `dataframe.convert_string`, but always intended to circle back and make sure we convert text dypes in `MultiIndex` appropriately.

**Comment by j-bennet** [comment]
Closed via https://github.com/dask/dask/pull/10040.
