### ISSUE TITLE
read_csv does not know keyword argument categorize

### ISSUE THREAD

**Issue by user32000** [dask/dask#1002]
Is the documentation at [http://dask.pydata.org/en/latest/dataframe-create.html](url) ahead on this?

**Comment by mrocklin** [comment]
It's almost certainly behind.  We removed this feature from read_csv a while ago and apparently forgot to remove it from documentation.

**Comment by user32000** [comment]
OK - can I fix this / how does that work?

**Comment by mrocklin** [comment]
If you want to categorize particular columns see the `dd.DataFrame.categorize` method.

If you're actually asking about fixing the documentation (a man can dream) then you would fork the project on github and then probably follow the [GitHub Flow](https://guides.github.com/introduction/flow/) guidelines and submit a pull request.  There are a few guides on the internet about how to do this.  Let me know if I should recommend something.

**Comment by mrocklin** [comment]
dataframe-create.html no longer contains the word categorize.  Closing
