### ISSUE TITLE
dask.imperative requires toolz, but it's not listed as one of the setuptools "extras"

### ISSUE THREAD

**Issue by tgs** [dask/dask#1005]
```
$ pip install dask[imperative]
Requirement already satisfied (use --upgrade to upgrade): dask[imperative] in ./env/lib/python3.4/site-packages
  dask 0.8.0 does not provide the extra 'imperative'
```

But base `dask` doesn't require `toolz`, and `dask.imperative` imports `toolz` on line 9.

Could you add a setuptools "extra" for "imperative"?

**Comment by mrocklin** [comment]
Sure, that sounds like a good idea.  Is this something you'd like to contribute?  I can do it if not.

**Comment by tgs** [comment]
Sure, I can do it. Thanks!

**Comment by tgs** [comment]
PR in #1006

**Comment by tgs** [comment]
:)
