### ISSUE TITLE
dask cli UserWarning when using entry points registered by pep660 editable installs from setuptools

### ISSUE THREAD

**Issue by graingert** [dask/dask#10068]
porting `distributed` to `pyproject.toml` based builds forces the use of https://peps.python.org/pep-0660/ Editable installs for pyproject.toml based builds which results in a `UserWarning: While registering the command with name 'scheduler', an existing command or group; the original has been overwritten."` https://github.com/dask/distributed/actions/runs/4373970047/jobs/7652816395#step:19:2248

this is due to https://github.com/python/cpython/issues/99130 fix released in 3.10.9 and 3.11.1

see: https://github.com/dask/distributed/pull/7629

**Comment by jrbourbeau** [comment]
Thanks @graingert! I see you've opened up https://github.com/dask/dask/pull/10070 to fix this -- I'll go take a look at that PR
