### ISSUE TITLE
Update `use_nullable_dtypes` and `dtype_backend` usage

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10062]
In https://github.com/pandas-dev/pandas/pull/51853 `pandas` deprecated `use_nullable_dtypes=` in I/O functions in favor of a new `dtype_backend=` keyword. Additionally, the global `dtype_backend` config option has been removed in favor of the corresponding keyword. We should make similar changes here

**Comment by jrbourbeau** [comment]
Filling in a few more details here, I think we should:

- [ ] Deprecate `use_nullable_dtypes=` in favor of the new `dtype_backend=` keyword (same as `pandas`)
    - Default and `"pyarrow"` have the same meaning, but `use_nullable_dtypes="pandas"` is now equivalent to `dtype_backend="numpy_nullable"`
- [ ] Deprecate `dataframe.dtype_backend` config option (since `pandas` decided to remove it) in favor of the `dtype_backend=` keyword 

cc @phofl for visibility on the `pandas` side

**Comment by phofl** [comment]
``use_nullable_dtypes`` was boolean before, so you don't have to change anything I think, just adding a deprecation warning. It is not possible anymore to get arrow backed DataFrames when only using ``use_nullable_dtypes``. The ``dtype_backend`` option was changed from ``pandas`` to ``numpy_nullable`` but it wasn't on a release version of pandas yet.

**Comment by jrbourbeau** [comment]
> use_nullable_dtypes was boolean before, so you don't have to change anything I think, just adding a deprecation warning.

Yeah, sorry this was more an internal dask implementation detail. The user-facing `use_nullable_dtypes=` keyword in dask was a boolean (matching pandas), but internally we then set it to `"pyarrow"` or `"pandas"` depending on the `dtype_backend` config option

**Comment by phofl** [comment]
dask-expr enforced this already
