### ISSUE TITLE
Incorrectness with lambda functions and scoping in .apply

### ISSUE THREAD

**Issue by mdering** [dask/dask#10092]
**Describe the issue**:
When using lambda functions with variables, the scope seems to resolve lazily, leading to incorrect behavior. The below code currently runs without warning or error and outputs incorrect values in the dataframe. I wanted to report this because I think this should at least warn you, if possible, though ideally it would work. I was able to get a workaround by using `lambda x, y: ` and passing in `y` to the apply function. 

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

kingdoms = {"Mammal": ["Dog", "Cat"],
            "Reptile": ["Lizard"],
            "Insect": ["Ant"]}

df = pd.DataFrame({"Species": ["Dog", "Cat", "Lizard", "Ant"]})
ddf = dd.from_pandas(df, npartitions=1)
for kingdom, species in kingdoms.items():
    ddf[kingdom] = ddf["Species"].apply(
        lambda x: 1 if x in species else 0,
        meta=(None, "int64")
    )
print(ddf.compute())

>>>  Species  Mammal  Reptile  Insect
0     Dog       0        0       0
1     Cat       0        0       0
2  Lizard       0        0       0
3     Ant       1        1       1
```

**Anything else we need to know?**:
I know there are workarounds for this, and this isn't a call for coding help. I wanted to see if there was something that could be done, or at least a warning could be issued to avoid this happening, since currently it deviates from the pandas behavior, as well as what is expected.
**Environment**:

- Dask version: 2023.3.1
- Python version: 3.10.10
- Operating System: linux
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
This is an issue with Python itself, not with Dask.  In these cases we
recommend using proper functions.  Their scoping rules line up more with
user expectations.

**Comment by mrocklin** [comment]
```python
for kingdom, species in kingdoms.items():
    def f(x):
        ...
    ddf[kingdom] = ddf["Species"].apply(
        f,
        meta=(None, "int64")
    )

**Comment by mdering** [comment]
right, i wanted to bring it to your attention because it deviates from the pandas behavior quietly. I know dask uses cloudpickle in the background, and a quick test shows that cloudpickle does work when this is done immediately. Perhaps theres something there?
```python
import dask.dataframe as dd
import pandas as pd
import cloudpickle

kingdoms = {"Mammal": ["Dog", "Cat"],
            "Reptile": ["Lizard"],
            "Insect": ["Ant"]}

df = pd.DataFrame({"Species": ["Dog", "Cat", "Lizard", "Ant"]})
ddf = dd.from_pandas(df, npartitions=1)

pickled_functions = {}
for kingdom, species in kingdoms.items():
    pickled_functions[kingdom] = cloudpickle.dumps(lambda x: 1 if x in species else 0,)
    ddf[kingdom] = ddf["Species"].apply(
        lambda x: 1 if x in species else 0,
        meta=(None, "int64")
    )
for k in pickled_functions:
    f = cloudpickle.loads(pickled_functions[k])
    print(k)
    print(f("Dog"))
print(ddf.compute())

>>>
Mammal
1
Reptile
0
Insect
0

  Species  Mammal  Reptile  Insect
0     Dog       0        0       0
1     Cat       0        0       0
2  Lizard       0        0       0
3     Ant       1        1       1
```

**Comment by mrocklin** [comment]
It isn't a cloudpickle thing, it's a lazy thing.  You're not using cloudpickle in that example.  Everything is running in the same process in threads.

The difference is when `.compute` is called.  

Anyway, there isn't anything we can do about lambdas doing lazy scope assignment.  This is a pure Python issue.  There is no bugfix we could apply except in CPython.

**Comment by mdering** [comment]
ok, that makes sense. thanks for taking a look!

**Comment by j-bennet** [comment]
@mdering I'm going to close the issue, but feel free to reopen if you need further help. Thank you!
