### ISSUE TITLE
Series object has no attribute 'columns'

### ISSUE THREAD

**Issue by terrytangyuan** [dask/dask#1010]
Is there anything changed in Series? I remember it has columns attribute before but correct me if I am wrong.

**Comment by terrytangyuan** [comment]
Alright, I think `Series` only has a `name`, instead of `columns`. My mistake. Not sure why my unit tests that used to pass do not pass anymore. I'll submit an issue if I find out why.

**Comment by mrocklin** [comment]
Yes.  Sorry.  I released last week and have yet to send out notes.
