### ISSUE TITLE
Add `xarray` back to Python 3.11 once there is `pandas` 2.0 support 

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10152]
`dask/array/tests/test_reductions.py::test_mean_func_does_not_warn` started failing on `main` recently with the following traceback (see [this CI build](https://github.com/dask/dask/actions/runs/4621048499/jobs/8171989949) for an example):

```
_________________________ test_mean_func_does_not_warn _________________________
[gw0] linux -- Python 3.11.2 /usr/share/miniconda3/envs/test-environment/bin/python3.11

    def test_mean_func_does_not_warn():
        # non-regression test for https://github.com/pydata/xarray/issues/5151
        xr = pytest.importorskip("xarray")
        a = xr.DataArray(da.from_array(np.full((10, 10), np.nan)))
    
        with warnings.catch_warnings(record=True) as rec:
            a.mean().compute()
>       assert not rec  # did not warn
E       assert not [<warnings.WarningMessage object at 0x7f4ab608c050>]

dask/array/tests/test_reductions.py:831: AssertionError
```

@phofl mentioned offline that we're pulling in an old version of `xarray` (0.19.0). My guess is this has to do with the recent conda-forge repodata patch made here https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/426, though that's just a guess, cc @keewis for visibility

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/pull/10153 was a temporary fix. Updating this issue to now cover adding `xarray` back to our Python 3.11 CI jobs once there's a release out that allows `pandas` 2.0

**Comment by jakirkham** [comment]
Thanks James! 🙏

Would track issue ( https://github.com/pydata/xarray/issues/7716 ) where `xarray` + `pandas` 2.0 discussion appears to be happening

**Comment by keewis** [comment]
FYI Deepak released a new version yesterday so you should be able to proceed here

**Comment by jrbourbeau** [comment]
Thanks for the heads up @keewis. I've pushed a PR that adds back `xarray` to our Python 3.11 builds. Will be able to merge that once the `xarray=2023.4.0` release is on conda-forge
