### ISSUE TITLE
Using `pandas >= 2.0` with `dask.dataframe` requires `dask >= 2023.2.0`

### ISSUE THREAD

**Issue by jameslamb** [dask/dask#10164]
**Describe the issue**:

We received a bug report this week over in LightGBM (https://github.com/microsoft/LightGBM/issues/5739#issuecomment-1500589135) whose root cause seems like it may have been the following set of changes:

* `pandas` 2.0 was released
* some versions of `dask.dataframe` prior to `2023.2.0` unconditionally used a `pandas` import path that was removed in `pandas` 2.0:
    - #9907
    - https://github.com/pandas-dev/pandas/pull/51207

**Minimal Complete Verifiable Example**:

Error with `2023.1.1`:

```python
docker run \
    --rm \
    -it python:3.11 \
    bash -c "
        pip install 'dask==2023.1.1' 'pandas>=2.0.0' && \
        python -c 'import dask.dataframe'
    "
```

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from dask.dataframe import backends, dispatch, rolling
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/backends.py", line 22, in <module>
    from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/core.py", line 35, in <module>
    from dask.dataframe import methods
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/methods.py", line 22, in <module>
    from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/utils.py", line 19, in <module>
    from dask.dataframe import (  # noqa: F401 register pandas extension types
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/_dtypes.py", line 4, in <module>
    from dask.dataframe.extensions import make_array_nonempty, make_scalar
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/extensions.py", line 6, in <module>
    from dask.dataframe.accessor import (
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/accessor.py", line 190, in <module>
    class StringAccessor(Accessor):
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/accessor.py", line 276, in StringAccessor
    pd.core.strings.StringMethods,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'
```

Success with `2023.2.0` (the first release to include #9907).

```shell
docker run \
    --rm \
    -it python:3.11 \
    bash -c "
        pip install 'dask==2023.2.0' 'pandas>=2.0.0' && \
        python -c 'import dask.dataframe'
    "

# no error
```

**Anything else we need to know?**:

I'll leave it to maintainers here to decide what, if anything, to do with those old `dask` versions and this report. For example, I'm not personally asking for a patch to be backported to older releases.

I'm just reporting it here because I couldn't find any other write-up on GitHub describing this issue, and I suspect that others will hit it as `pandas` 2.0 adoption increases. Hopefully when others search that `AttributeError`, this write-up will help them.

Thanks for your time and consideration.

**Comment by quasiben** [comment]
Thanks for bringing this up @jameslamb .  Though I can definitely sympathize with the pain of upgrading the stack, I think it's reasonable that newer dependencies get support in newer versions -- so I think asking users who want/need pandas 2.0 support to also upgrade their Dask version is the right call here.

**Comment by jrbourbeau** [comment]
Thanks for the issue @jameslamb! Yeah, I agree with @quasiben that upgrading `dask` is the recommendation for this case

**Comment by GenevieveBuckley** [comment]
> I'm just reporting it here because I couldn't find any other write-up on GitHub describing this issue, and I suspect that others will hit it as `pandas` 2.0 adoption increases. Hopefully when others search that `AttributeError`, this write-up will help them.

fyi @jameslamb you just helped me a lot by doing this. Thanks!

**Comment by jameslamb** [comment]
Hey great, glad it helped!

**Comment by achapkowski** [comment]
I'm seeing this version pop up on older versions of dask as well, what versions of dask are compatible with what versions of pandas?  Is there a matrix?
