### ISSUE TITLE
Windows builds on Python 3.8 and 3.9 are failing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10183]
We started seeing some interesting (unrelated) failures on PRs with errors like 

```python
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated
abruptly while the future was running or pending.
```

I ran a CI build against `main` and saw these failures (see [these](https://github.com/dask/dask/actions/runs/4682910082/jobs/8297351447) [build](https://github.com/dask/dask/actions/runs/4682910082/jobs/8297351582)) while the latest commit on `main` https://github.com/dask/dask/commit/fd31b9b67e105f4c63b391f5c24959e39e27a0cc doesn't have these failures. This makes me think that the source if these failures is outside of `dask/dask` itself. 

The next thing I would do here is `diff` the installed packages between the successful builds in https://github.com/dask/dask/commit/fd31b9b67e105f4c63b391f5c24959e39e27a0cc vs. the unsuccessful builds [here](https://github.com/dask/dask/actions/runs/4682910082/jobs/8297351447) and [here](https://github.com/dask/dask/actions/runs/4682910082/jobs/8297351582) to see what dependencies have changed. Hopefully that helps provide some insight. 

cc @rjzamora @charlesbluca @phofl @graingert is this something you have bandwidth to look into?

**Comment by phofl** [comment]
scikit-image pinned script to <1.9.2 on conda forge which resulted in some weird differences. Pinning scikit-image to <0.20 for now solves this, https://github.com/conda-forge/scikit-image-feedstock/pull/102 for context. The pin is already gone on main https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml, so will be fixed with the next release.

The package diff is anyone is interested:
```
          Name_base      Name_new Version_base Version_new
114    intel-openmp           NaN     2023.0.0         NaN
144         libblas       libblas        3.9.0       3.9.0
148        libcblas      libcblas        3.9.0       3.9.0
158        libhwloc           NaN        2.9.0         NaN
161       liblapack     liblapack        3.9.0       3.9.0
173         libxml2           NaN       2.10.4         NaN
188             mkl           NaN     2022.1.0         NaN
204         numexpr       numexpr        2.7.3       2.8.4
227           pooch           NaN        1.7.0         NaN
233  pthreads-win32           NaN        2.9.1         NaN
277    scikit-image  scikit-image       0.20.0      0.20.0
279           scipy         scipy       1.10.1       1.9.1
290             tbb           NaN     2021.8.0         NaN
343             NaN      libflang          NaN       5.0.0
344             NaN   libopenblas          NaN      0.3.21
345             NaN     llvm-meta          NaN       5.0.0
346             NaN         nomkl          NaN         1.0
347             NaN        openmp          NaN       5.0.0
```

**Comment by jakirkham** [comment]
It looks like the aforementioned issue was worked around in CI: https://github.com/dask/dask/pull/10186

Plus the `scipy` pin was dropped from the `scikit-image` package: https://github.com/conda-forge/scikit-image-feedstock/pull/103

Furthermore Dask has dropped Python 3.8 & 3.9: https://github.com/dask/dask/pull/10295 & https://github.com/dask/dask/pull/11245

Given all of this, think this issue can be closed
