### ISSUE TITLE
Implement mappers for groupby method

### ISSUE THREAD

**Issue by nirizr** [dask/dask#1018]
Pandas's DataFrame and Series implementation of groupby accepts a mapper function as it's "by" parameter (named "Index" in dask).
If this by parameter is a callable, the data will be grouped according to the function's returned value.
The function is called with the dataframe indices.

Although it's not as important to me personally, the by parameter can be a variety of value types. lists of functions and mapping dictionaries are also supported.

A somewhat funny example can be:
```
def odd_or_even(i):
  return "Even" if i % 2 == 0 else "Odd"
df.groupby(odd_or_even).get_group("Even")
```

**Comment by mrocklin** [comment]
Is this the same as the following?

    df.groupby(df.index.map(odd_or_even)).get_group("Even")

**Comment by TomAugspurger** [comment]
The other option (pandas has a big API :smile:) is a mapping (or Series, not sure if that's special cased separate from a dict). Pandas `Index.map` doesn't actually take a mapping, it's expecting a callable, so you may need to wrap the input in a `lambda x: by.get(x)` if it's not callable.

```python
In [29]: df = pd.DataFrame(np.random.randn(30, 3), columns=list('abc'))

In [30]: df['d'] = np.random.choice(['A', 'B', 'C'], size=30)

In [31]: df.groupby(lambda x: x % 2 == 0).mean()  # function applied to input
Out[31]:
             a         b         c
False  0.04764 -0.210169  0.029083
True   0.12660 -0.346553  0.300927

In [33]: df.groupby(dict(zip(df.index, df.index % 2))).mean()  # mapping of Index -> groupby keys
Out[33]:
         a         b         c
0  0.12660 -0.346553  0.300927
1  0.04764 -0.210169  0.029083
```

**Comment by nirizr** [comment]
@mrocklin Yes, that yields the same result. will it work with dask? would it be a proper way to implement that? Pandas uses `index.map` internally to convert a callable to an array-like.

@TomAugspurger Is right. Additionally, a list of functions and a tuple are also possible. Series and any array-like object is treated the same, and is expected to have the size of the index, and map every sample to group. that's how `df.index.map` works.

Personally, i'm interested in mapper functions like the example, but i'm willing to go the extra mile and provide something broader.
