### ISSUE TITLE
Odd behavior with .apply in version 2023.4.0 and Python 3.11 - "foo" values present

### ISSUE THREAD

**Issue by thehomebrewnerd** [dask/dask#10209]
**Describe the issue**:
I am seeing some odd "foo" values being passed to a function used in an `.apply` call. I have observed this with Dask version `2023.4.0` and `Python 3.11`. I have not tried to reproduce this on other Python versions, but this seems to be isolated to version `2023.4.0`.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'vals': [(0, 1), (0, 1), (100, 100)]})
dask_df = dd.from_pandas(df, npartitions=1)

def my_func(x):
    print(x)
    return x

dask_df["vals"].apply(my_func, meta=("vals", tuple([int, int]))).compute()
```

Output with Dask `2023.4.0`:
```
foo
foo
(0, 1)
(0, 1)
(100, 100)
0        (0, 1)
1        (0, 1)
2    (100, 100)
Name: vals, dtype: object
```

Output with Dask `2023.3.2`:
```
(0, 1)
(0, 1)
(100, 100)
0        (0, 1)
1        (0, 1)
2    (100, 100)
Name: vals, dtype: object
Name: vals, dtype: object
```
**Anything else we need to know?**:
I'm using the simple function `my_func` in the apply call here for illustrative purposes and printing the values to show the function gets called twice with `x=foo` before it gets called with the real series values. This issue was discovered when the real function I was using was expecting tuple inputs and failed when it received the string `foo` instead. Dask seems to happily ignore the `foo` values that are returned when constructing the output series since they aren't present there.

**Environment**:

- Dask version: 2023.4.0
- Python version: 3.11
- Operating System: macOS Monterey
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Hi, thanks for your report. This was caused while adapting to a pandas deprecation. See https://github.com/dask/dask/pull/10133
Should be straightforward to fix
