### ISSUE TITLE
Pandas copy-on-write

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10218]
Pandas 2.0 has improved performance with copy-on-write.  Apparently we've been doing lots and lots of unnecessary copies.  

@phofl I'm curious, what would we need to do to turn this on?  You've mentioned before that the test suite passes.  Are we good to go?

**Comment by jrbourbeau** [comment]
Should just need to turn on the config option in pandas like we did in https://github.com/dask/dask/pull/9942. I've opened / updated that PR to see if CI passes. Would probably want some minimum version checks, etc. Though @phofl would know better

**Comment by jrbourbeau** [comment]
For folks looking for more context there's this doc https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html

**Comment by mrocklin** [comment]
I'm looking forward to seeing this.  Thanks for rekindling the PR.

**Comment by phofl** [comment]
Yes turning on the option would functionally enable CoW. We should keep https://github.com/coiled/benchmarks/issues/808#issuecomment-1520491955 in mind. @crusaderky and I talked a bit about exposing some information whether an object is a view or a copy.

**Comment by mrocklin** [comment]
That sounds like a concern, but kind of like "oops, I didn't realize I had all of this money lying around and so my books are off" kind of concern.  It's a problem, granted, but a problem that I think we welcome with open arms?

**Comment by phofl** [comment]
Yes agree. 

We should only turn it on for 2.0 and up, the flag became available in 1.5.0, but we didn't implement any optimisations at that point.

**Comment by crusaderky** [comment]
We need to review all slicing operations in dask.dataframe.
For example, I understand that pandas' default CoW behaviour re horizontal slicing is to retain the full original input. In this case dask would need to force a deep-copy in case the input of the task is free'd.

**Comment by crusaderky** [comment]
XREF https://github.com/dask/distributed/issues/5868 for the over-estimation of managed memory

**Comment by phofl** [comment]
Horizontal slicing shouldn't change between CoW and non-CoW. Vertical slicing now retains views as much as possible. Potentially keeping more memory alive. Similar to the following without CoW:

```
df = pd.DataFrame({"a": [1, 2, 3], "b": 1})
df = df["a"]
```

This also keeps the whole array alive.

**Comment by phofl** [comment]
We decided against doing this at import time since this is a not great UX, so there isn't anything to do for now. We will just wait until pandas 3.0 drops and we get it by default
