### ISSUE TITLE
dask Array blocks not actually chunks

### ISSUE THREAD

**Issue by ahnsws** [dask/dask#10242]
**Describe the issue**:
Hello, I am probably doing something very wrong. I am trying to iterate over the chunks of a dask array as such:

```python
import dask.array as da
import numpy as np


def unexpected_behavior():
    chunk_size = (25, 25, 25)
    a: da.Array = da.ones(shape=(100, 100, 100), chunks=chunk_size)
    assert a.chunksize == chunk_size

    for block in a.blocks:
        assert block.shape != chunk_size  # unexpected! :(
        print(block.shape)  # (25, 100, 100)


def desired_behavior():
    chunk_size = (25, 25, 25)
    a: da.Array = da.ones(shape=(100, 100, 100), chunks=chunk_size)
    assert a.chunksize == chunk_size

    for i in np.ndindex(a.numblocks):
        block = a.blocks[i]
        assert block.shape == chunk_size


if __name__ == "__main__":
    unexpected_behavior()
    desired_behavior()
```

It looks like the blocking is only applied along the zeroth dimension.

**Environment**:

- Dask version: 2023.4.1
- Python version: 3.10.6
- Operating System: ubuntu 22.04.2 LTS
- Install method (conda, pip, source): poetry

**Comment by ahnsws** [comment]
Oh interesting, using ravel gives me the expected behavior:

```python
import dask.array as da


def expected_behavior():
    chunk_size = (25, 25, 25)
    a: da.Array = da.ones(shape=(100, 100, 100), chunks=chunk_size)
    assert a.chunksize == chunk_size

    for block in a.blocks.ravel():
        assert block.shape == chunk_size


if __name__ == "__main__":
    expected_behavior()

```

**Comment by jrbourbeau** [comment]
Thanks for the issue @ahnsws. `.blocks` returns an array-like object where the items in the array are the blocks that comprise the larger Dask array. Hopefully some of the docs here https://docs.dask.org/en/stable/generated/dask.array.Array.blocks.html#dask.array.Array.blocks make things a little more clear. 

It sounds like `ravel()` meets your needs. FWIW you can also index directly into `blocks` -- here's an example with the array in your original snippet:

```python
In [16]: chunk_size = (25, 25, 25)
    ...: a = da.ones(shape=(100, 100, 100), chunks=chunk_size)

In [17]: a
Out[17]: dask.array<ones_like, shape=(100, 100, 100), dtype=float64, chunksize=(25, 25, 25), chunktype=numpy.ndarray>

In [18]: a.blocks
Out[18]: <dask.array.core.BlockView at 0x1223b8220>

In [19]: a.blocks.shape
Out[19]: (4, 4, 4)

In [20]: a.blocks[0, 3, 1]
Out[20]: dask.array<blocks, shape=(25, 25, 25), dtype=float64, chunksize=(25, 25, 25), chunktype=numpy.ndarray>
```

I'm going to close this issue as it sounds like you have what you need with `.blocks.ravel()`
