### ISSUE TITLE
Dask.Array copy method isn't exactly no-op

### ISSUE THREAD

**Issue by syelman** [dask/dask#10240]
Hi,
I realized after the first call to copy dask array changes its hash value. I thought this might be expected but I realized this happens only for the first copy call so I decided to create this issue anyway.

**Code Snippet**:

```python
# Put your MCVE code hereimport dask.array as da
from joblib import hash

x1 = da.ones((10, 10), chunks=(5, 5))
init_hash = hash(x1)
x1.copy()
assert hash(x1) == init_hash
```

**Environment**:
Latest dask on python 3.9

**Comment by jrbourbeau** [comment]
Thanks for the issue @syelman. I'm not familiar with `joblib.hash`, so can't speak to if it is expected to work on Dask collections or not. Internally we use `dask.base.tokenize` for providing a unique hash

```python
In [1]: import dask.array as da

In [2]: x = da.ones((10, 10), chunks=(5, 5))

In [3]: y = x.copy()

In [4]: from dask.base import tokenize

In [5]: tokenize(x)
Out[5]: '779d8d4c29681b37a50d672bfdb62226'

In [6]: tokenize(x) == tokenize(y)
Out[6]: True
```
