### ISSUE TITLE
Dask does not pass arguments downstream when read parquet file

### ISSUE THREAD

**Issue by nkhabarov-exos** [dask/dask#10272]
Hello all,

I'm trying to write and then read parquet file with pyarrow schema.

code is something like:
```
pandas_df.to_parquet(<>, schema=MyPerfectSchema.to_pyarrow_schema())

dd.read_parquet(<>, schema=MyPerfectSchema.to_pyarrow_schema(), dtype_backend='pyarrow')
```
it raises an error:
```
Original Message: format number 1 of "dictionary<values=string, indices=int8, ordered=0>[pyarrow]" is not recognized
```

if i do:
```
df = pd.read_parquet(<>, schema=MyPerfectSchema.to_pyarrow_schema(), dtype_backend='pyarrow')
ddf = dd.from_pandas(data=df, npartitions=1)
```
it works fine.

Unfortunately I cannot disclosure my schema, very simplified it looks like this:
```
    field1: Field[pa.string()]
    field2: Field[pa.dictionary(pa.int32(), pa.string()
```

Looks like dd.read_parquet() doesn't pass arguments to downstream parquet reader.

**Comment by rjzamora** [comment]
I haven't had a chance to try myself yet, but you may have more luck passing schema as a dataset-level argument:

```python
dd.rad_parquet(..., dataset={"schema": <your-schema>})
```

Unfortunately, `dd.read_parquet` tries to do a lot of things and support an arbitrary IO engine, and so the user typically needs to specify whether a key-word argument should be passed to the underlying dataset API, or to the read function. 

Note that you can also use `dd.from_map` if you need more control over the behavior of the IO function being applied to each file or dataset fragment (see this [from_map overview](https://blog.dask.org/2023/04/12/from-map) if you're interested).

**Comment by nkhabarov-exos** [comment]
I did full example to better explain it:
```
async def main():
    import pyarrow as pa
    import pandas as pd
    import dask.dataframe as dd

    MyPerfectSchema = pa.schema([
        ("col1", pa.int8()),
        ("col2", pa.string()),
        ("col3", pa.dictionary(pa.int8(), pa.string())),
    ])

    df = pd.DataFrame.from_dict(
        {
            'col1': {0: 1, 1: 2},
            'col2': {0: 'name1', 1: 'name2'},
            'col3': {0: 'type1', 1: 'type2'},
        }
    )
    df.to_parquet('/tmp/test.parquet', schema=MyPerfectSchema)

    # this one works
    df = pd.read_parquet('/tmp/test.parquet', schema=MyPerfectSchema, dtype_backend='pyarrow')
    ddf = dd.from_pandas(df, npartitions=1)
    print('pandas', ddf.compute())

    # this one does not work
    ddf = dd.read_parquet('/tmp/test.parquet', schema=MyPerfectSchema, dtype_backend='pyarrow')
    print('dask', ddf.compute())

    return
```
but it seems @rjzamora already answered. Thank you! With `dataset={"schema": <your-schema>}` it works!

**Comment by rjzamora** [comment]
>With dataset={"schema": <your-schema>} it works!

Great! Closing the issue then, but feel free to reopen if necessary.
