### ISSUE TITLE
Dask 2023.5.0 python tests break 3.8+ test environment for Airflow

### ISSUE THREAD

**Issue by potiuk** [dask/dask#10279]
**Describe the issue**:

Dask 2023.5.0 breakes tests for Airflow for Python 3.8 - most likely because the "distribured tests" and related leave side effects after running tests (/tmp directory in following tests is pointing to dask scratch space)

**Minimal Complete Verifiable Example**:

After releasing dask our tests started to fail The only real chanve in our test suite is that we attempted to upgrade
to latest dask (previous suite of tests completed few hours ago, so the only upgraded dependency since was dask:

This is visible here:

https://github.com/apache/airflow/actions/runs/4960905632/jobs/8877036912#step:4:17652

```
147c147
< dask==2023.4.1
---
> dask==2023.5.0
156c156
< distributed==2023.4.1
---
> distributed==2023.5.0
```

Also you can see that Python 3.7 is still green - because the new dask is Python 3.8+ and the builds has not changed any dependencies:

```
Summary: Constraints constraints-source-providers:3.7:

Constraints generated in /files/constraints-3.7/constraints-source-providers-3.7.txt


No changes in constraints - exiting
```

With those dependencies upgraded, an unrelated test started to fail::

https://github.com/apache/airflow/actions/runs/4960905632/jobs/8877333352#step:6:8621

It shows:

```
        path = sys.path[0] + "/tests/kubernetes/pod.yaml"
>       with open(path) as stream:
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dask-scratch-space/scheduler-8895yk3s/tests/kubernetes/pod.yaml'
```

It looks like running tests from this sute leave `sys.path[0]` set to   `/tmp/dask-scratch-space/scheduler-8895yk3s` as side effect. This does not happen on Python 3.7, it only happens on Python 3.8+. (NOTE: Because new dask is Python 3.8+ only).

This test works fine in isolation, no problem, but our test suite executes dask tests before

```
  tests/executors/test_dask_executor.py ....ss....                         [ 11%]
  tests/executors/test_debug_executor.py .........                         [ 11%]
  tests/executors/test_executor_loader.py ................ss               [ 12%]
  tests/executors/test_kubernetes_executor.py .F.......................... [ 13%]
```

And tests from dask import the test suite friom dask:

https://github.com/apache/airflow/blob/main/tests/executors/test_dask_executor.py

```
try:
    # utility functions imported from the dask testing suite to instantiate a test
    # cluster for tls tests
    from distributed import tests  # noqa
    from distributed.utils_test import cluster as dask_testing_cluster, get_cert, tls_security

    skip_tls_tests = False
except ImportError:
    skip_tls_tests = True
    # In case the tests are skipped because of lacking test harness, get_cert should be
    # overridden to avoid get_cert failing during test discovery as get_cert is used
    # in conf_vars decorator
    get_cert = lambda x: x
```

**Anything else we need to know?**:

We are just limiting dask to < 2023.5.0 to handle it , but it would be nice to fix it asap.

**Environment**:

- Dask version: 2023.5.0
- Python version: 3.8+ 
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
I'm a little confused about what's going on here.  I think the failing tests are in [test_kubernetes_executor.py](https://github.com/apache/airflow/blob/d6051fd10a0949264098af23ce74c76129cfbcf4/tests/executors/test_kubernetes_executor.py#L59) not [test_dask_executor.py](https://github.com/apache/airflow/blob/main/tests/executors/test_dask_executor.py)

What _should_ `sys.path[0]`  be pointing to ?  Sys.path being monkey patched somewhere ? Perhaps using `dask.config.get("temporary-directory")` might work instead of hardcoded paths ?

**Comment by potiuk** [comment]
What is in sys.path[0] in our tests is the "airflow's" `/opt/airflow`  - where the sources of airflow are available when running the tests.

And as I explained above - this is a side effect of dask tests. Those tests should NEVER change global state. They do. 

The unit tests of dask executor in the new version modify `sys.path[0]` and do not clean up after themselves. They override system path with test directory of dask and forget to clean after themselves.  Usually this is done with patching which modify system path and clean up after the tests are done. Leaving behind modified global state is a very bad code-smell and it should not happen. The tests of dask executor are using the imported test suite from dask and apparently it's the suite that leaves things behind.

Unfortunately (for us) dask tests in Python have been implemented and managed by the dask team and we have no capacity or possibility to  manage it so every time such tests fail we have to freeze the version of dependency from dask and let the dask team fix it (happened 2 times in the past).  This is cumbersome and since we have no capacity to make any changes there, basically any time it happens we open an issue or discuss in the discort of dask to fix the problem and until they do we just freeze the version that caused the problem (which we already did in https://github.com/apache/airflow/pull/31259). We are not going to modify our tests to handle side-effects from the new dask provider.

The result of it is that users of dask executor will use old version of the dependency until it is fixed by dask team.

There is an easy way out though.

Better solution would be, that DASK team takes over back the maintenance of their dask executor and releases the executor on their own. We have just implemented https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-51+Removing+Executor+Coupling+from+Core+Airflow and 3rd-party companies that integrate with airflow can release their providers independently https://github.com/apache/airflow/blob/main/PROVIDERS.rst#rd-party-providers so that they can make sure whatever they release as dependency is up-to-date. I think this is the right direction for Dask.


Do you want to go that path? I think we would be super happy to pass the maintenance of dask executor and the related tests to your team back.

**Comment by jrbourbeau** [comment]
Thanks @potiuk. My guess is https://github.com/dask/distributed/pull/7802 is related to the change in behavior that's causing problems for the airflow test suite. I opened https://github.com/dask/distributed/pull/7838 as a possible fix.

**Comment by potiuk** [comment]
Thanks! Looks pretty much like it - once you have a release candidate up in PyPI - I will be able to test it - it will be enough to remove the limit in Airflow and make a "full tests needed" PR with it.

**Comment by potiuk** [comment]
Q: Is there a place (mailing list or smth) where I can subscribe to new releases? Right now we are upper-bound so we won't automatically upgrade. Or maybe this is all but guaranteed that it will be released in next release and I should put != for the broken versions in our deps?

**Comment by jrbourbeau** [comment]
Yeah, https://github.com/dask/distributed/pull/7838 will be included in the next release (we release every two weeks -- next one should be next Friday, May 26)

**Comment by potiuk** [comment]
Thanks for quick fix!

I will exclude just these versions and they should get upgradeded automatically when released then!
