### ISSUE TITLE
to_hdf lock kwarg is documented as taking an instance of Lock, but it is ignored

### ISSUE THREAD

**Issue by graingert** [dask/dask#10315]
the docs:

https://github.com/dask/dask/blob/0426326905c5e9773b05ae7e5f018facb135b779/dask/dataframe/io/hdf.py#L89-L94

however the implementation ignores the lock provided and uses it as a bool:

https://github.com/dask/dask/blob/0426326905c5e9773b05ae7e5f018facb135b779/dask/dataframe/io/hdf.py#L224-L225

either the docs need updating or we could do something like:

```python
@runtime_checkable
class SupportsLock(Protocol):
    def acquire(self) -> object: ...
    def release(self) -> object: ...

if isinstance(lock, bool) and lock:
    lock = get_scheduler_lock(df, scheduler=scheduler)
else:
    assert isinstance(lock, SupportsLock)
```

**Comment by j-bennet** [comment]
@graingert Kind of related to https://github.com/dask/dask/pull/10309; perhaps I could include the fix in the same PR. With a custom lock, this user could have solved their own problem.

**Comment by j-bennet** [comment]
@graingert I opened https://github.com/dask/dask/pull/10309.

**Comment by mrocklin** [comment]
As a heads-up, I don't think that HDF is in common usage.  I consider HDF
work to be low priority.

**Comment by j-bennet** [comment]
@mrocklin

> As a heads-up, I don't think that HDF is in common usage. I consider HDF work to be low priority.

The PR was pretty much done before I knew that, but I'l keep that in mind going forward.
