### ISSUE TITLE
p2p shuffled pandas data takes more memory

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10326]
I observe that after I call `set_index` on the uber-lyft data with `p2p` that my dataset takes up more memory than before.  When I use `tasks`, it doesn't.  cc @hendrikmakait 

Reproducible (but not minimal) example:

```python
import dask
from dask.distributed import wait
import dask.dataframe as dd

dask.config.set({"dataframe.convert-string": True})  # use PyArrow strings by default

df = dd.read_parquet(
    "s3://coiled-datasets/uber-lyft-tlc/",
)

print(df.memory_usage(deep=True).sum().compute() / 1e9)  # about 100

df = df.set_index("request_datetime", shuffle="p2p").persist()

print(df.memory_usage(deep=True).sum().compute() / 1e9)  # about 200
```

If you try wth `shuffle="tasks"` it doesn't expand that much.  I haven't tried this without Arrow.

**Comment by mrocklin** [comment]
Without arrow involved the memory does not expand (it's about 200 both before and after)

**Comment by hendrikmakait** [comment]
I haven't looked deeper into this, but from the description it sounds like this is caused by dask/distributed#7420

**Comment by mrocklin** [comment]
Ah yes, that would do it.

**Comment by jrbourbeau** [comment]
I think this has to do with when we convert `pa.Table` object to pandas objects with `pa.Table.to_pandas()`. `pa.Table` represents both `string[python]` and `string[pyarrow]` as `pa.string()` (which makes sense). By default when `pandas` creates a string column, it uses `string[python]`, not `string[pyarrow]` (there's a `mode.string_storage` `pandas` option to control that default). 

@hendrikmakait and I chatted offline about a possible fix. Right now we're just using a pyarrow schema to keep track of dtypes. I think we should also keep track of `meta` on the `pandas` side so we can handle the string case properly. My guess is we grab `._meta` at the beginning of a the shuffle process and pipe it down to where those `pa.Table.to_pandas()` calls happen. We can then do something like (psuedocode below):

```python
if <only-a-single-string-type-present>:
    df = table.to_pandas(type_mapper={pa.string(): <pandas-string-type>})
else:
    # Mixed string type case
    df = table.to_pandas().astype(meta.dtypes.to_dict())
```

**Comment by mrocklin** [comment]
Thanks for resolving this quickly.  It's nice seeing things happen in a day.
