### ISSUE TITLE
`dask/tests/test_distributed.py::test_map_partitions_df_input` failing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10335]
`dask/tests/test_distributed.py::test_map_partitions_df_input` is failing on `main` with 

```python
RuntimeError: shuffle_unpack failed during shuffle 53a3327765b9171a0d39308129460022
```

See the full traceback in [this CI build](https://github.com/dask/dask/actions/runs/5191717202/jobs/9359906097?pr=10334)

cc @hendrikmakait 

xref https://github.com/dask/dask/pull/10334

**Comment by jrbourbeau** [comment]
Looks like we're not properly handling how we pass `meta` around 

```python
>   return df.astype(meta.dtypes)
E   AttributeError: 'Serialize' object has no attribute 'dtypes'

../distributed/distributed/shuffle/_arrow.py:59: AttributeError
```

**Comment by rjzamora** [comment]
>But I've not thought deeply yet about why we're getting a Serialize instance here in the first place.

Pretty sure this all comes back to https://github.com/dask/dask/issues/8581  (I see `use_processes=False` in `test_map_partitions_df_input`)
