### ISSUE TITLE
Annotations and spans leak between threads and asyncio tasks

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#10340]
`dask.config.set` is a context manager that modifies the global singleton dict `dask.config.config`.
This means that if you have two threads or two asyncio tasks that perform temporary changes to the config in parallel, you'll get race conditions.

This is normally very much not a problem, as config parameters are something that is normally configured either in the yaml files before you even launch the python process or immediately after you load the script.

There is however a notable exception to this, which are annotations and the new [user-defined spans](distributed#7860) (which are a thin wrapper on top of annotations), which alter the config on the fly, typically for very short periods of times.

While it is somewhat uncommon for a user to define multiple graphs in different threads on the client, this problem becomes acute when the user submits tasks from other tasks:

```python
def f():
    with dask.annotate(resources={"GPU": 1}):
        dask_collection1 = ...
    client = get_client()
    secede()
    return dask_collection1.compute()

def g():
    with dask.annotate(resources={"HIMEM": 1}):
        dask_collection2 = ...
    client = get_client()
    secede()
    return dask_collection2.compute()

client.gather([client.submit(f), client.submit(g)])
```
In the above example, if f and g accidentally end up executing at the same time in two different threads of the same worker, you may randomly end up with `dask_collection1` to be erroneously limited to work on a HIMEM worker, and dask_collection2 to be limited to a GPU worker.

When it comes to [user-defined spans](distributed#7860), this issue makes it impossible to propagate the span information to the tasks, e.g. for logging purposes or because the tasks themselves submit more tasks:

```python
def process_df(uri):
    with span("load"):
        df = dd.read_parquet(uri)
    with span("reduce"):
        out = ...(df)
    client = get_client()
    secede()
    return out.compute()

client = Client()
with span("foo"):
    foo = client.submit(process_df, "s3://mybucket/foo.parquet")
with span("bar"):
    bar = client.submit(process_df, "s3://mybucket/bar.parquet")
client.gather([foo, bar])
```
In the above example, if the two calls to process_df end up running in parallel on two threads of the same worker, it will be mayhem. For example you may end up with tasks tagged with span=`(foo, load, reduce)` where they should be tagged instead with `(bar, reduce)`.

# Proposed design

This is a delicate problem. The canonical solution to global variables leaking this way is `contextvars`. However, contextvars are not inherited by children threads (hence why we wrote [run_in_executor_with_context](https://github.com/dask/distributed/blob/618f5ac5cc92457e67cc09badacaf5e32b3b9728/distributed/utils.py#L1451-L1472)).
If you call dask.config.set() at the top of your script and then break into threads, you definitely expect the changes to be inherited.

I suggest that:
- `dask.config.set` should accept an optional parameter `use_context=False`. If set to true, instead of modifying the global config dict it will modify a contextvar that overrides it.
If the contextvar is set, False is ignored and forced to True
- `dask.config.get` will read the contextvar first and, if it's not defined, the global dict.
- `dask.annotate` will call `dask.config.set(annotations=..., use_context=True)`
- `distributed.spans.span` doesn't need to change anything as it internally calls `dask.annotate`.

**Comment by crusaderky** [comment]
This issue blocks https://github.com/dask/distributed/pull/7898

**Comment by fjetter** [comment]
How about solving this problem exclusively for annotations? That dask.config is used for annotations is mostly an implementation detail. I would be surprised if we couldn't just use a contextvar for annotations. I even expect this to behave much better (maybe we need a combination of config + contextvar in case users *actually* set annotations in their config but I'd be willing to break this until somebody complains).

In which scenarios would we care about thread propagation? IIUC this would only be a problem if the user created a dask graph in Thread A but would call compute/submit in Thread B.

**Comment by crusaderky** [comment]
> How about solving this problem exclusively for annotations? [...]  I would be surprised if we couldn't just use a contextvar for annotations.

Yes, this is very reasonable and I doubt it will break anybody's code.

> maybe we need a combination of config + contextvar in case users actually set annotations in their config

I'm unconcerned.
Short of users bypassing the `annotate` function call and calling `dask.config.set` for whatever reason, which IMHO is bad practice, the use cases for annotations in the dask config feel... very narrow. For example one may statically set `{annotations.resources.GPU: 1}` and then have small section of the code that call `with annotate(resources={"GPU": 0})`. But I'd be surprised if anybody actually pulled this trick. Even then, such a user would just need to call `annotate(resources={"GPU": 1})` at the beginning of each thread that defines a graph.

> In which scenarios would we care about thread propagation? IIUC this would only be a problem if the user created a dask graph in Thread A but would call compute/submit in Thread B.

Your example is not problematic, because annotations are applied at graph creation.

**Comment by fjetter** [comment]
> Short of users bypassing the annotate function call and calling dask.config.set for whatever reason

I'm rather thinking a user specifying something in their _file_. I can't come up with a _good_ use case for this but I've seen stranger things happening :)

**Comment by fjetter** [comment]
> Your example is not problematic, because annotations are applied at graph creation.

That's only partially true.

https://github.com/dask/distributed/blob/19c8bf91e02a594f2cdaf7fb1fa9741569400355/distributed/client.py#L3111

There are basically "global" annotations that are present in the submit/compute context and there are "local" annotations that are only defined during graph creation.
The global ones take a different route to the scheduler and are not dropped by optimization while the local ones are attached to `Layer` objects
