### ISSUE TITLE
dask.array.reshape() fails on large chunks

### ISSUE THREAD

**Issue by ska-incom** [dask/dask#10368]
**Describe the issue**:
When using dask.array.reshape on chunks that are larger than the `array.chunk-size` limit it will fail if the number of dimensions change. 

**Minimal Complete Verifiable Example**:

```python
# %%
import dask.array as da
import dask

dask.config.set(
    **{"array.slicing.split_large_chunks": True, "array.chunk-size": "1KiB"}
)

da.random.random((100, 100, 48)).rechunk((5, 5, 6)).reshape((100, 100, 2, 24))
```

**Anything else we need to know?**:
Affects Xarray https://github.com/pydata/xarray/issues/7931

**Environment**:

- Dask version: 2023.6.0
- Python version: 3.10
- Operating System: Linux
- Install method (conda, pip, source): source

**Comment by phofl** [comment]
We've recently removed the split large chunk option (it never worked).. A more sensible behavior is now the default, so closing here
