### ISSUE TITLE
Document that `dask.array.rechunk` expects the output shape to match the input shape

### ISSUE THREAD

**Issue by hendrikmakait** [dask/dask#10361]
It is not documented anywhere that `dask.array.rechunk` expects the output to have the same shape as the input and does not allow reshaping. The validation step is also quite hidden. This has led to some confusion (https://github.com/dask/distributed/pull/7897#discussion_r1234169191), so I think it would be good to add a remark about this in the documentation.

**Comment by fjetter** [comment]
+1 I was initially confused by this as well

**Comment by Swish78** [comment]
Hello,
I am interested in working on this issue. I have gone through the problem description and would like to contribute by providing the necessary documentation improvements for the `dask.array.rechunk` function.
Could this issue be assigned to me? I am excited to work on it and believe I can provide a clear and concise update to the documentation.

Thank you!

**Comment by Swish78** [comment]
@fjetter Thank you. I've submitted the pull request and I'm looking forward to any feedback or suggestions you may have.
