### ISSUE TITLE
Collect docstring from functions in Dask workflow graph

### ISSUE THREAD

**Issue by mangecoeur** [dask/dask#1036]
A common problem when setting up data pipelines is actually documenting the things properly. Dask already makes it possible to inspect the workflow by visualizing a the graph of functions to apply. A nice extension would be if Dask could also collect the docstrings from the functions into a tree structure, which could then be fed e.g. into a Sphinx plugin to automatically create documentation of the data pipeline.

**Comment by mrocklin** [comment]
The functions themselves are present in the dask graph, so this is fairly straightforward to do.  Can you propose a good input/output format for such a function?  I suspect that the hard part here is in designing something that is generally useful.  What information would you need to create such a sphinx plugin?

**Comment by mangecoeur** [comment]
A very simple graph structure would do the trick, with each node containing the docstring and pointers to the previous/next node in the graph. This would look a lot like what is already in the dask-to-graphviz conversion, maybe a shared matadata tree could be developed. You would expect something json serializable like a list of items `{previous:<node id>, next:<node id>, function_name: <str>, function_docstring: <str>}`

The only tricky bit I can see is that you would want to 'reduce the graph when functions are run in parallel, because you only need to docstring once plus an indication that it is running in parallel in the workflow. But perhaps that can be left up to whatever tools want to display the info.

In a first instance it should be quite easy to add the function docstrings to the Graphviz output and allow existing tools to access it, including the existing Sphinx extension http://www.sphinx-doc.org/en/stable/ext/graphviz.html.

**Comment by mrocklin** [comment]
This issue seems to be lingering and I'm tempted to close it.  

@mangecoeur if you'd like to write up a spec for a graph format different from the existing dask graph spec I'd be quite happy to help you construct a conversion function.  My guess is that this wouldn't go directly within the dask repository but might instead live in whatever sphinx extension you're thinking of building.  I suspect that the conversion from our existing graph spec would be fairly straightforward.

**Comment by jcrist** [comment]
Closing as outside the scope of dask itself. As Matt said above, this would likely be a separate package that might make use of dask internally.
