### ISSUE TITLE
Docs build broken

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10381]
Looks like our docs are running into an error on `main`. See this build from a recent PR https://readthedocs.org/projects/dask/builds/21146384/

**Comment by douglasdavis** [comment]
Looks like `scipy.stats.chisquare` got a docstring update that uses a home-spun `doi` sphinx directive. I'm trying to see if we can use it

**Comment by jrbourbeau** [comment]
Thanks for looking into this one @douglasdavis 👍

**Comment by douglasdavis** [comment]
Welp we cant! I think this may be the best way to go

```
diff --git a/dask/array/stats.py b/dask/array/stats.py
index e5ec8c320..e2afc4f0c 100644
--- a/dask/array/stats.py
+++ b/dask/array/stats.py
@@ -144,8 +144,12 @@ def ttest_rel(a, b, axis=0, nan_policy="propagate"):
     return delayed(Ttest_relResult, nout=2)(t, prob)
 
 
-@derived_from(scipy.stats)
 def chisquare(f_obs, f_exp=None, ddof=0, axis=0):
+    """Calculate a one-way chi-square test.
+
+    Please see the docstring for :py:func:`scipy.stats.chisquare`.
+
+    """
     return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis, lambda_="pearson")
```
 I'll open a PR

**Comment by ncclementi** [comment]
Looks like they haven't been properly built since May see the changelog: https://docs.dask.org/en/stable/changelog.html
