### ISSUE TITLE
Warn or raise if ancient version of s3fs is installed

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10397]
There is a pinning issue around S3FS, see https://github.com/dask/dask/issues/10276, such that performance can be excruciatingly  slow in some cases since early versions of s3fs use slow APIs, do not cache, etc.

To my knowledge, there is no way to tell our package manages that we require a minimum version for an optional dependency. There is a recommendation in https://github.com/dask/dask/issues/10276#issuecomment-1549664991 to introduce an fsspec-all metapackage but I'm not entirely convinced this will help since reaching out to users is very difficult.

Instead, I propose to implement a check that sees if s3fs is installed and if so it verifies that a minimal version (TBD) is installed. If an ancient version is discovered, we either raise or issue a `UserWarning`.

I'm a bit on the fence regarding this. Sometimes users install s3fs as a transitive dependency in which case I wouldn't want to raise. However, for anybody who is actually using this, raising hard would be ideal.

cc @martindurant @jrbourbeau

**Comment by martindurant** [comment]
I'm not sure, but it may be reasonable for fsspec to do this check, since users do still end up with the newest fsspec in every case. So at the time of instantiating s3 (meaning they do plan to actually use it), we can warn. I'd say warn is better than raise, there could conceivably be some reason to want an old s3fs.

**Comment by fjetter** [comment]
> I'd say warn is better than raise, there could conceivably be some reason to want an old s3fs.

Well, I've seen libraries pin lower versions for much less than that. The version that is currently pulled in is four years old. I think if anybody wants to use an old version like this intentionally, they can also use an older version of fsspec.

I'm mostly concerned for users who only pull this in transitively.

**Comment by fjetter** [comment]
@martindurant do you want to take care of this warning?

**Comment by martindurant** [comment]
I will make a PR to issue the warning, yes. It's not a great solution, so I am also trying to change the upped python version bound allowed by those old version to < 3.9 (since s3fs 0.4.2 was released before then).
