### ISSUE TITLE
to_parquet partitioned by 'date'

### ISSUE THREAD

**Issue by marcdelabarrera** [dask/dask#10406]
I'm trying to save a dask dataframe `to_parquet` and partition it by date. The system won't allow the naming of the file `date=2022-01-01 00:00:00`. 
```
dates = pd.DataFrame({'date':pd.date_range(start='2022-01-01', end='2022-01-31', freq='D')})
ddata = dd.from_pandas(dates, npartitions=1)
ddata.to_parquet("dates.pq", partition_on="date")
```
```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '***/dask/dates.pq/date=2022-01-01 00:00:00'
```

Getting rid of the ` 00:00:00` would solve the issue. 

**Workaround**:
Save `date` as a string, but I would like it to be a date. 

I'm using dask '2023.5.1'

**Comment by rjzamora** [comment]
Thanks for the report @marcdelabarrera!  I cannot reproduce on my end, so I'm thinking this is probably specific to windows. Can you confirm if you are using the "pyarrow" engine (by specifying `engine="pyarrow"`)?

**Comment by marcdelabarrera** [comment]
Thank you for the reply. @rjzamora. 

I tried with `pyarrow` and I am getting the same error. I tried the same on Linxu and indeed worked. The problem is that on Windows, `:` is an invalid character to write in a directory name, while it does not seem to be the case with other OS.

I guess a partial fix is that the file was saved as `yyyy-mm-dd`, although this would drop information regarding hours, minutes, and seconds, or replacing `:` for some other allowed character.

**Comment by rjzamora** [comment]
>The problem is that on Windows, : is an invalid character to write in a directory name

Yes, you are definitely correct about this. I'll try to see if pyarrow's native `write_to_dataset` (or other systems) do something special to handle this problem.

**Comment by rjzamora** [comment]
>I guess a partial fix is that the file was saved as yyyy-mm-dd, although this would drop information regarding hours, minutes, and seconds, or replacing : for some other allowed character.

I'm not really finding any convenient ways to automatically handle the `":"` problem while partitioning by a `date_range` column. In practice, most hive partitioning tends to be on a specific "day", "month" or "year" (the second is not typically something you want to partition on). Therefore, if you need to track the time information somewhere, you may want to split your `"date"` column into distinct `"date"` and `"time"` columns, and only use the `"date"` column for partitioning.  If you don't need the time information, then doing the following before the write is probably your best bet:

```python
dates["date"] = dates["date"].astype("date64[pyarrow]")
```
