### ISSUE TITLE
test_division_or_partition fails on Python 3.12

### ISSUE THREAD

**Issue by QuLogic** [dask/dask#10418]
**Describe the issue**:

I believe 3.12 is the key factor, but all dependencies were rebuilt for it, so all dependencies are listed as possible causes. If you suspect that there's likely to be a different cause, [see here](https://koschei.fedoraproject.org/build/15856060) for all the dependencies.

```
__________________________ test_division_or_partition __________________________
[gw3] linux -- Python 3.12.0 /usr/bin/python3
db = 'sqlite:////tmp/tmpk8po4885'
    def test_division_or_partition(db):
        with pytest.raises(TypeError, match="either 'divisions' or 'npartitions'"):
            read_sql_table(
                "test",
                db,
                columns=["name"],
                index_col="number",
                divisions=[0, 2, 4],
                npartitions=3,
            )
    
        out = read_sql_table("test", db, index_col="number", bytes_per_chunk=100)
        m = out.memory_usage_per_partition(deep=True, index=True).compute()
>       assert (50 < m).all() and (m < 200).all()
E       assert (True and False)
E        +  where True = <bound method NDFrame._add_numeric_operations.<locals>.all of 0    True\n1    True\n2    True\n3    True\n4    True\ndtype: bool>()
E        +    where <bound method NDFrame._add_numeric_operations.<locals>.all of 0    True\n1    True\n2    True\n3    True\n4    True\ndtype: bool> = 50 < 0     78\n1     76\n2     78\n3     77\n4    238\ndtype: int64.all
E        +  and   False = <bound method NDFrame._add_numeric_operations.<locals>.all of 0     True\n1     True\n2     True\n3     True\n4    False\ndtype: bool>()
E        +    where <bound method NDFrame._add_numeric_operations.<locals>.all of 0     True\n1     True\n2     True\n3     True\n4    False\ndtype: bool> = 0     78\n1     76\n2     78\n3     77\n4    238\ndtype: int64 < 200.all
../../../BUILDROOT/python-dask-2023.4.1-1.fc39~bootstrap.x86_64/usr/lib/python3.12/site-packages/dask/dataframe/io/tests/test_sql.py:290: AssertionError
```

The main point here is that the last element has a size of 238, which is over the expected maximum of 200. I'm not sure how these numbers came about; maybe the maximum could just be increased?

**Minimal Complete Verifiable Example**:

```python
pytest
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.7.0
- Python version: 3.12.0b4
- Operating System: Fedora Rawhide
- Install method (conda, pip, source): source

**Comment by phofl** [comment]
Hi, thanks for your report. pandas 1.5.3 is not compatible with Python 3.12, same for NumPy 1.24, there is no guarantee that this works. We can't do much as long as there aren't any upstream wheels available for 3.12

**Comment by juliangilbey** [comment]
Quick update on this: the test still fails in exactly this way with Python 3.12 when using Pandas 2.1.4 and NumPy 1.24.2.  (I haven't yet been able to test it with NumPy 1.26.x.)

**Comment by hendrikmakait** [comment]
@juliangilbey: Thanks for the update. Support for Python 3.12 was only added in NumPy 1.26, so updating your NumPy version should fix the issue. Please let us know if this works!

**Comment by juliangilbey** [comment]
> @juliangilbey: Thanks for the update. Support for Python 3.12 was only added in NumPy 1.26, so updating your NumPy version should fix the issue. Please let us know if this works!

Indeed; when Debian updates it's NumPy (probably after the ongoing Python 3.12 transition has finished), I will be able to retest this.

**Comment by hendrikmakait** [comment]
Given that this test passes on CI for Python 3.12 (https://github.com/dask/dask/actions/runs/7281247936/job/19841385444#step:10:9553), I'll close this issue. Feel free to reopen if you experience an issue on Debian once you've updated.

**Comment by antonio-rojas** [comment]
This is still failing on Arch with numpy 1.26.4
