### ISSUE TITLE
GC error on mac with read_csv

### ISSUE THREAD

**Issue by PeterDSteinberg** [dask/dask#1042]
On Mac 10.10.5, in a Python 2.7 environment, and dask version 0.8.0 from conda install, this sequence of dask dataframe read_csv commands results in an uncaught GC error:
```
In [4]: filename = os.path.join('data', 'accounts.*.csv')

In [5]: import dask.dataframe as dd

In [6]: df = dd.read_csv(filename)

In [7]: len(df)
Fatal Python error: GC object already tracked
/Users/psteinberg/anaconda/envs/py27/bin/python.app: line 3: 82786 Abort trap: 6           /Users/psteinberg/anaconda/envs/py27/python.app/Contents/MacOS/python "$@"
```
(python exits)

**Comment by mrocklin** [comment]
This is a known Pandas bug.  I believe that if you try the 0.18.0 release candidate that this will disappear:

    conda install -c pandas pandas=v0.18.0rc2

**Comment by PeterDSteinberg** [comment]
Yes, you're right.  That fixes it.
