### ISSUE TITLE
Naming the Index Column

### ISSUE THREAD

**Issue by ax3l** [dask/dask#10440]
**Describe the issue**:

In Pandas, there is a quick way to assign a name to the index column. This is useful, e.g., when exporting to CSV or making clear what the index stands for when dealing with other "indices/ids" in other columns of the data frame.

There seems to be no way to do this in Dask yet?

**Minimal Complete Verifiable Example**:

```python
df.index.name = "row"
# or
df.index = df.index.rename("row")
```

then
```
print(df.columns)
print(df.index.name)
```
work in Pandas - but change nothing in Dask DFs.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.8.0
- Pandas version: 2.0.2
- Python version: 3.11.4
- Operating System: Ubuntu 22.04
- Install method (conda, pip, source): pip

**Comment by rjzamora** [comment]
Can you share an example where `df.index = df.index.rename("row")` doesn't work?

I know that you cannot currently set the name like `df.index.name = "new_name"`, but I *think* the following should work:

```python
>>> import dask.dataframe as dd
>>> df = dd.from_dict({"x": range(10)}, 1)
>>> df.index.name
>>> df.index = df.index.rename("new_name")
>>> df.index.name
'new_name'
```

**Comment by phofl** [comment]
I think we should add ``rename_axis`` to dask/dask as well (I already added it to dask-expr), it's convenient in method chains

**Comment by ax3l** [comment]
Thank you all for the hints!

@rjzamora the example is with `from_delayed`:
https://github.com/openPMD/openPMD-api/pull/1501/files

**Comment by phofl** [comment]
We added rename_axis and df.index = df.index.rename("foo") also works with dask-expr, making df.index.name = "something" work is not really doable since we don't have mutable objects, so closing here
