### ISSUE TITLE
Add da.Array.nanreductions?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1045]
NumPy ndarrays do not have nanreduction methods like `nanmean`

```python
In [1]: import numpy as np

In [2]: np.nanmean
Out[2]: <function numpy.lib.nanfunctions.nanmean>

In [3]: np.ndarray.nanmean
AttributeError: type object 'numpy.ndarray' has no attribute 'nanmean'
```

Dask.array follows this example and has `nanreduction` functions, but not methods.  

This is sometimes confusing.  Do we want to add `nanreduction` methods to the `Array` class?  Is there a reason that these aren't present in NumPy?

**Comment by jcrist** [comment]
My personal preference is just to copy numpy here. I also do a lot of tab-completion-driven-development™, and am mildly opposed to adding too many methods on a single class. Not a strong preference here though.

**Comment by shoyer** [comment]
I'm also -0 on this. I just don't see a lot to be gained by deviating from NumPy.

**Comment by mrocklin** [comment]
Alrighty.  Closing.
