### ISSUE TITLE
xarray test failure related to dask.array argmax on Python 2.6

### ISSUE THREAD

**Issue by shoyer** [dask/dask#1046]
This recently turned up as a failure on our master branch (xref https://github.com/pydata/xarray/pull/794):
https://travis-ci.org/pydata/xarray/jobs/115522509

We get the error `TypeError: type object argument after * must be a sequence, not generator` from this line in dask.array:
https://github.com/dask/dask/blob/0771dba0b7504847bf2143f4c9ebb67467ac983b/dask/array/reductions.py#L509

I'm not sure why the dask test suite didn't pick this up, since you do appear to run tests against Python 2.6. The source appears to be @jcrist's PR https://github.com/dask/dask/pull/1024.

**Comment by jcrist** [comment]
The toolz version provided by conda is too low (the error provided is
surpringly unhelpful). If you pip intall toolz on py26 this should go away.
I'm not sure what the best course of action is here, since anaconda support
for 2.6 is dropped.

**Comment by mrocklin** [comment]
Both requirements.txt and the conda.yaml file should reflect the toolz
version dependency.  I suspect that Anaconda will just stop providing new
dask packages for 26.

**Comment by jcrist** [comment]
To be clear, the issue is that the last version of toolz on the default conda channel is 0.7.2. Dask now depends on 0.7.4. In our travis test suite, toolz gets upgraded in the `pip install partd` line, so our tests pass fine on 2.6.

The code for arg reductions could be easily changed to make toolz 0.7.2 work fine. I'm not sure if that's the best course of action though.

**Comment by shoyer** [comment]
Thanks for your help debugging this!

I'm not entirely sure why, but we had already switched to pip for installing dask on Python 2.6 (probably because the conda package wasn't being updated). So it was easy enough to switch to pip for toolz, too. That should take care of things.
