### ISSUE TITLE
API: read_csv should default to ignore_index=True when no index_col

### ISSUE THREAD

**Issue by jreback** [dask/dask#1047]
xref https://github.com/pydata/pandas/issues/12618

```
In [13]: import dask

In [14]: dask.__version__
Out[14]: '0.8.0'

In [15]: pd.__version__
Out[15]: '0.18.0+7.g17a5982'
```

```
In [4]: import glob

In [5]: DataFrame(np.arange(10).reshape(-1,2)).to_csv('file1.csv')

In [6]: DataFrame(np.arange(10).reshape(-1,2)).to_csv('file2.csv')

In [7]: pd.concat([ pd.read_csv(f, index_col=0) for f in glob.glob('file*.csv') ], ignore_index=True)
Out[7]: 
   0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
5  0  1
6  2  3
7  4  5
8  6  7
9  8  9

In [11]: import dask.dataframe as dd

In [12]: dd.read_csv('file*.csv', header=0, usecols=[1,2]).compute()
Out[12]: 
   0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
```

- the concat should be ``ignore_index=True``, otherwise you are implicitly setting the index

Side issue (maybe an example in the docs would help), about how to ignore an index.

- I'd really like to do:

 ``dd.read_csv('file*.csv', header=0, index_col=0).compute()`` 

(see the above linked issue). This requires me to ``.set_index(...)`` after on a dummy column though

I know I have an index, but I 
```
In [17]: dd.read_csv('file*.csv', header=0, names=['col',0,1]).compute()
Out[17]: 
   col  0  1
0    0  0  1
1    1  2  3
2    2  4  5
3    3  6  7
4    4  8  9
0    0  0  1
1    1  2  3
2    2  4  5
3    3  6  7
4    4  8  9
```

Then drop it or ``.reset_index``

**Comment by jcrist** [comment]
This is tricky to do correctly, and in most cases doesn't matter:
- You really only see the default index if you're reading in many files and then concatenating into a large frame. If you're using dask to work with many files, it's likely that the concatenated result is a bit big.
- As soon as you start filtering rows, it becomes impossible to know what the concatenated row-number index really should be. We might be able to track this using a lot more metadata, but would be a large maintenance burden
- I can't think of many cases where knowing the row numbers (the default index) is important to the analysis.

I'm going to close this for now, feel free to reopen if needed.

**Comment by jcrist** [comment]
Looks like I said I'd close it, but never did :/. Closing now.
