### ISSUE TITLE
numexpr: missing dependency for dataframe

### ISSUE THREAD

**Issue by sciunto** [dask/dask#1048]
Hi,

I think numexpr must be added in setup.py for dataframe.

````
dask/dataframe/core.py:1451:            import numexpr
````

thanks.

**Comment by mrocklin** [comment]
Context

```python
    def query(self, expr, **kwargs):
        """ Blocked version of pd.DataFrame.query

        This is like the sequential version except that this will also happen
        in many threads.  This may conflict with ``numexpr`` which will use
        multiple threads itself.  We recommend that you set numexpr to use a
        single thread

            import numexpr
            numexpr.set_nthreads(1)

        The original docstring follows below:\n
        """ + pd.DataFrame.query.__doc__
```

**Comment by sciunto** [comment]
oops :) but still... :)

A user reported that numexpr is reported to be missing during the packaging: https://aur.archlinux.org/packages/python-dask/

I'm try to investigate more (weird, because I do not remember I had to install it in a venv.)

**Comment by mrocklin** [comment]
numexpr is a heavy dependency.  I would like to avoid it if possible.  It is an optional dependency to Pandas.  The error they're getting is from Pandas, not dask.

**Comment by sciunto** [comment]
Thanks for the hint!

**Comment by sciunto** [comment]
OK, I understand what's going on in pandas. I'll make a PR.
