### ISSUE TITLE
File objects fully read when embedded in `delayed` tasks

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10497]
While including file objects in `delayed` tasks (e.g. this is done when using `parallel=True` in `xr.open_mfdataset`) we end up fully reading in the file contents here 

https://github.com/dask/dask/blob/88dabae39f5c063474caa30fdc84cc433c98b994/dask/delayed.py#L101-L102

This results in unexpected IO, large graphs, and problems like https://github.com/pydata/xarray/issues/7574. Many (maybe all?) `fsspec` file objects like `S3File` are pickleable, so maybe we should just update this to `if isinstance(expr, Iterator) and <not-an-fsspec-file>:`. @martindurant do you have any thoughts here?

**Comment by martindurant** [comment]
I might suggest that `if isinstance(expr, Iterator): ` is only really meant to capture lists and sets. It would make no sense for a dict or string or many other other types.

**Comment by jrbourbeau** [comment]
Yeah, I agree using `Iterator` is probably reaching too broadly. It looks like the original motivation was for `slice` objects. I'll push up a PR to see if tests are happy.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/10498
