### ISSUE TITLE
Bug (?) concatenating arrays of strings

### ISSUE THREAD

**Issue by ToddSmall** [dask/dask#1050]
Hi,

I've run across what I think is a small bug with concatenating dask arrays of strings in which the dtypes of the arrays to be concatenated are different:

```
In [106]: a = np.array(['CA-0', 'CA-1'])

In [107]: b = np.array(['TX-0', 'TX-10', 'TX-101', 'TX-102'])

In [108]: a = da.from_array(a, chunks=2)

In [109]: b = da.from_array(b, chunks=4)

In [110]: da.concatenate([a, b]).compute()
Out[110]: 
array(['CA-0', 'CA-1', 'TX-0', 'TX-1', 'TX-1', 'TX-1'],
      dtype='|S4')

In [111]: da.concatenate([b, a]).compute()
Out[111]: 
array(['TX-0', 'TX-10', 'TX-101', 'TX-102', 'CA-0', 'CA-1'],
      dtype='|S6')
```

If the array with the "smaller" dtype (in this case, S4) is the first array in the sequence to be concatenated, then this "smaller" dtype is used for the end result, truncating the entries in the array with the "larger" dtype (in this case, S6). If the order of the arrays is swapped so that the array with the "larger" dtype comes first, then the concatenation works properly.

It looks to me like the error occurs in the [dask.array.core.concatenate3](https://github.com/dask/dask/blob/master/dask/array/core.py#L2952) function where the dtype of the result is inferred from the first array in the sequence, rather than using the dtype computed in the [concatenate](https://github.com/dask/dask/blob/master/dask/array/core.py#L1748) function itself.

Todd

**Comment by shoyer** [comment]
Hi @ToddSmall!

This is probably a good example of how it can be convenient to cast arrays of strings to `dtype=object` (like pandas) before doing operations.

**Comment by mrocklin** [comment]
Yeah, I think it will be challenging to lazily determine dtypes when the dtypes depend on runtime values.  Going with object dtype or explicitly casting to a large enough dtype manually seems to me to be the way to go.

**Comment by shoyer** [comment]
Well, dask is looking at argument dtypes to infer the dtype of the result,
so there's no reason why it couldn't follow the promotion rules of rules
here when combining arrays.

**Comment by mrocklin** [comment]
Oh indeed.  Actually, if I looked longer at @ToddSmall 's original comment I probably would have seen his astute description of where the problem lies.  My bad.

**Comment by ToddSmall** [comment]
Thanks @shoyer and @mrocklin. I'll use one or the other of those suggestions.

**Comment by mrocklin** [comment]
We should definitely fix this though.  I suggest that in `da.concatenate`, if the output dtype is not the same as the input dtypes, then we first call `astype` on all inputs with the new output dtype.

@shoyer can you anticipate any occasion in which this might fail?

**Comment by shoyer** [comment]
Thanks! This seems pretty safe to me.

**Comment by ToddSmall** [comment]
Thanks @mrocklin!
