### ISSUE TITLE
Dask reads list-type parquet columns as strings

### ISSUE THREAD

**Issue by lessthantrue** [dask/dask#10504]
**Describe the issue**: Dask reads list-type parquet columns as strings

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

data = {
    "one": [[1, 2], [3, 5]],
    "two": [[2, 4], [6, 10]]
}

pd.DataFrame(data).to_parquet("test.parquet", engine="pyarrow")

df = pd.read_parquet("test.parquet")

print("Pandas Read")
# prints:
# one    object
# two    object
# dtype: object
# 0     [3, 6]
# 1    [9, 15]
# dtype: object
print(df.dtypes)
print(df.one + df.two)

print("Dask Read")
# prints:
# one    string[pyarrow]
# two    string[pyarrow]
# dtype: object
# 0      [1 2][2 4]
# 1    [3 5][ 6 10]
# dtype: string
ddf = dd.read_parquet("test.parquet", engine="pyarrow")
print(ddf.dtypes)
df2 = ddf.compute()
print(df2.one + df2.two)

```

**Anything else we need to know?**: This problem does not exist in Dask version 2023.2.1

**Environment**:

- Dask version: 2023.9.1
- Python version: 3.11.4
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Hi, this is a bit of a problem since we infer all object dtypes as strings, you can turn this off globally if that's a problem for you though

```
dask.config.set({"dataframe.convert-string": False})
```

you can also set dtypes explicitly if that helps.

Additionally, pandas supports pyarrow list dtypes since 2.0, e.g. ``pd.ArrowDtype(pa.list())``. Does any of that help?

**Comment by lessthantrue** [comment]
This workaround gets the job done:

```
dask.config.set({"dataframe.convert-string": False}) 
```

Why was the default behavior changed?

**Comment by phofl** [comment]
PyArrow strings are significantly more efficient that NumPy object. It will drastically reduce memory usage and give a big speedup in operations. It also reduces gill contention which provides another speedup for multithreaded workers.
