### ISSUE TITLE
Incorrect behavior of override_with argument in dask.config.get

### ISSUE THREAD

**Issue by bnaul** [dask/dask#10519]
I think #10499 may have introduced an accidental change in the behavior of dask.config.get (I think https://github.com/dask/dask-kubernetes/issues/816 is referring to the same thing, albeit somewhat cryptically 🙂):
```
# Previous behavior, 2023.9.1 and earlier
HEAD is now at 3316c38f0 bump version to 2023.9.1
(.venv)  ➜  dask git:(2023.9.1) ✗ python -c 'import dask; print(dask.config.get("array.chunk-size", override_with=None))'
128MiB

# New version after this PR
HEAD is now at 216c7c939 Release 2023.9.2 (#10514)
(.venv)  ➜  dask git:(2023.9.2) ✗ python -c 'import dask; print(dask.config.get("array.chunk-size", override_with=None))'
None
```

I believe this also contradicts the docstring so I think it's a clear bug and not just a neutral change
>  If ``override_with`` is not None this value will be passed straight back

cc @crusaderky @jrbourbeau @fjetter

**Comment by jrbourbeau** [comment]
Thanks for surfacing @bnaul -- @crusaderky mentioned offline he'll look at this issue
