### ISSUE TITLE
Performance on laptop vs. virtual machine

### ISSUE THREAD

**Issue by thequackdaddy** [dask/dask#1052]
So I'm working with a dask dataframe. I have 2 computers at work... A laptop and virtual machine. 

Laptop specs: 
Windows 7 Professional
8 core i7 4710MQ @ 2.5 GHz
16 GB of RAM
500 GB HDD. 

Virtual Machine Specs 
Windows Server 2012R2
8 core Xeon E5-2609 v3 @1.9 GHz
32 GB of RAM
500 GB SSD

I'm noticing that the speeds of working with dask dataframe are much, much better on the i7 laptop than on the virtual machine. I have some code that runs in about 40 seconds on the laptop at 115 seconds on the virtual machine. 

I talked to my IT department and they offered to add more cores. (Who am I to say no?) But I'm wondering if there is something about the i7 processor vs. Xeon that would make it nearly 3 times faster? 

The operations I'm doing in dask are very math-heavy. Lots of `groupby().sum()` and elementwise stuff. 

Thoughts on this?

**Comment by jcrist** [comment]
Your laptop has both a faster processor (faster single core performance), and more cores (can do more things at once). I'd expect some combination of this plus the hit of running a VM in general to be the reason for the performance difference. The operations you're doing can be run fairly parallel, so the 8 vs 16 cores in particular are probably the largest difference.

**Comment by thequackdaddy** [comment]
I'm sorry where do you get 8 vs. 16 cores? Does i7 4710MQ have 16 cores? (When it comes to CPU's I get confused with all the buzzwords.) In both computers on the CPU tab in task manager, you can see 8 different windows. I was fairly sure that both had 8 cores. 

I'm wondering if I need to ask IT to turn my VM into a standalone box... Its just a 3 times performance hit is far more than I can probably deal with.

**Comment by jcrist** [comment]
Oop, looks like I misread the stats you posted. Indeed, they're both the same number of cores. 3x hit for a vm is a bit much, but could be due to that. I'd also check that you're running the same numpy and pandas versions on both boxes.

**Comment by branning** [comment]
Echoing what Jim said, the single-threaded performance of the i7-4710MQ is
almost double that of the Xeon E5-2609 v3, based on the PassMark tests (
http://www.cpubenchmark.net/compare.php?cmp%5B%5D=2427&cmp%5B%5D=2219).

One other thing that sticks out is that the Xeon is a 6-core processor, not
an 8-core. If it's a 2-socket machine, and they've allocated 2 cores from
one socket and 6 cores from its sibling socket, then you may have memory
contention over the interconnect between the two processors. If you have
multiple sockets and are using NUMA mode, then they'll be forced to contend
for the same memory. If you're "poring" over an amount of data that fits
into memory, then that's a good thing.  But if you're "streaming" over data
larger than memory, which I suspect is the case, then NUMA probably isn't
helping things.

Philip

**Comment by thequackdaddy** [comment]
Thanks for this. Very helpful. 

I guess I see myself as sort of screwed then. My thinking was that I could use dask and parallel mode to use all 8 cores of my server. It seems that what I've written, dask.dataframe is only really utilizing 1-2 cores. Unless I'm doing something wrong, I still have some work to get this fast enough to make me happy. 

With that said, the fact this works so well on out-of-core data is freaking amazing.

**Comment by mrocklin** [comment]
I would expect groupby-sum to be very parallelizable.  Perhaps your bottleneck is in loading in your data?

**Comment by thequackdaddy** [comment]
It could be. I've had a little difficulty with that. Perhaps starting from first principles is a good idea... Back to read_csv... let me play with that.

**Comment by mrocklin** [comment]
If your data is in CSV then that's almost certainly your bottleneck.  I
recommend something like HDF5 or castra.

On Wed, Mar 16, 2016 at 7:25 PM, Peter Quackenbush <notifications@github.com

**Comment by thequackdaddy** [comment]
I think I tried HDF5 but realized it wasn't thread-safe...

See here:

https://github.com/pydata/pandas/issues/12236

I like the idea behind HDF5... but I'm unable to get it to run parallel as well.

**Comment by shoyer** [comment]
Even if you need to use a lock around HDF5 for writing data (which should work with dask), it's still probably faster than multithreaded CSV.

**Comment by thequackdaddy** [comment]
Ahh... I see that now. Yes, it is much faster than CSV. 

I guess I was hoping that I could use all 8 cores on my computer with my data. Maybe I'm doing something wrong (very likely), but I seem to cap out around 25% with from_castra. 

Here's a very simple program I'm using. The dataset has around 120 columns and 1.2 million records.  using from_castra. castra has chunksizes of 50,000. I can get up to around 30% of the CPU on a multicore laptop. 

In any event, this is way to big to fit into the memory I have, so the out-of-core power here is a big win regardless. 

```
if __name__ == '__main__':
    import dask.dataframe as ddf

    data = ddf.from_castra('c:\\workspace\\mydata.castra')

    import dask

    from dask.diagnostics import CacheProfiler, Profiler, ResourceProfiler
    from cachey import nbytes

    a = data.groupby(data.CategoryA).sum()
    b = data.groupby(data.CategoryB).sum()
    c = data.groupby(data.CategoryC).sum()
    d = data.groupby(data.CategoryD).sum()
    e = data.groupby(data.CategoryE).sum()
    f = data.groupby(data.CategoryF).sum()
    g = data.groupby(data.CategoryG).sum()
    h = data.groupby(data.CategoryH).sum()

    with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, \
            CacheProfiler(metric=nbytes) as cprof:

                dask.compute(a, b, c, d, e, f, g, h)

    from dask.diagnostics import visualize
    visualize([prof, rprof, cprof])
```
![capture](https://cloud.githubusercontent.com/assets/8186432/13863499/4576c07e-ec68-11e5-9d02-4c7e93debed6.PNG)

**Comment by jcrist** [comment]
Overall this plot looks pretty good. A few things:

- Reading from castra will hold the GIL currently, as blosc doesn't release it. The reason you still see more than 100% cpu usage when the reads are occurring is that internally blosc uses threads as well.
- I suspect that you don't have 8 actual cores, but instead have 4, each with 2 *virtual* cores. Due to various things, you'll probably see similar performance if you use only 4 threads instead of 8. You can check this by adding this to the top of your file:

```python
from multiprocessing.pool import ThreadPool
from dask.context import set_options
pool = ThreadPool(4)
set_options(pool=pool)
```
hitting ~300% cpu usage with only 4 cores isn't bad. Due to the context switching and periodic GIL grabbing going on, I wouldn't expect you to ever reach full 400% usage.

**Comment by thequackdaddy** [comment]
Good to hear. 

This is where I'm going to admit that my lack of knowledge of hardware engineering is going to make me ask questions that are probably silly. 

Thanks for all your help.

**Comment by mrocklin** [comment]
It's really satisfying to see people use dask and generate plots like this.  Good stuff.
