### ISSUE TITLE
Dask SVD For Matrices > 3 GB

### ISSUE THREAD

**Issue by tommysisk** [dask/dask#10528]
I am finding that for large arrays (~3GB) dask's singular value decomposition is much slower than numpy's implementation. I find this confusing and am wondering if one would expect a speed up in this use case (the array is tall and skinny)? I am currently working on an academic project which involves very large singular value decompositions of both tall and skinny and square PSD arrays (covariance matrices). The aforementioned 3 GB array is substantially smaller than the target arrays I hope to work with. Is there anyway I can use dask to speed up decompositions of this sort? I have run several tests and find that dask is substantially slower than numpy for all things SVD which leads me to believe that I am making an error or misunderstanding the utility of dask. 

*Minimal Background*
I am creating arbitrarily large features sets (in the form of numpy/dask arrays) from all atom physics simulations of large molecules.  From these matrices, I compute a time-lagged correlation matrix that I want to take the SVD of ..

want the SVD of ---->  (x[:lag].T@x[:lag])^(-1/2) @ (x[:lag].T@x[lag:]) @ (x[lag:].T@x[lag:])^(-1/2)

where the matrices raised to the -1/2 power are computed via their SVD as follows

negative half inverse = U @ diag(1/sqrt(s)) @ V.T 

In this minimal backround snippet, all arrays are apparently square BUT these equations can be modified to compute SVDs of tall skinny arrays rather than their covariance matrix counterparts i.e x.T@x for x that is n,d where n>>d.

Any clarifications, suggestions, ect would be greatly appreciated! I am trying to maximize speed; I have access to a variety of computational resources, so memory is not so important.
<img width="776" alt="Screenshot 2023-09-24 at 5 24 44 PM" src="https://github.com/dask/dask/assets/85724985/543c12d0-4b3a-40e9-b56c-66b8f646d7b7">

"""
def dask_svd(x,
             compressed:bool=False,
             k:int=2,
             svals=False,
             transposed=False):
    getter = lambda x : x.compute()
    
    row, col = x.shape
    
    #this is only going to help if the svd is compressed
    

    if col>row:
        transposed=True
        x = x.T
            
    x = da.from_array(x,
                      chunks="auto")       
    
    if svals:
        x = da.linalg.svd_compressed(x,k=k)[1].compute()
        return x
    
    if compressed:
        x = list(map(getter, da.linalg.svd_compressed(x, k=k)))
    
    else:
        x = list(map(getter, da.linalg.svd(x)))
    
    if transposed:
        #to apply the transpose of the product of 3 matrices, need to flip the ordering
        return [x.T for i in x].reverse()
    else:
        return x
"""

**Comment by mrocklin** [comment]
For single machine execution nothing will beat a well-tuned BLAS/LAPACK
implementation (which Numpy can link to).  You should stick with Numpy on
data that fits in the memory of a single machine.  You might want to verify
that you have a modern BLAS/LAPACK implementation installed.

**Comment by hendrikmakait** [comment]
It looks like this issue has been resolved. Please reopen in case there are still open questions.
