### ISSUE TITLE
DataFrame sum produces incorrect results under specific conditions

### ISSUE THREAD

**Issue by fbunt** [dask/dask#10527]
**Describe the issue**:
Under specific conditions that are not hard to trigger, `DataFrame.sum` produces values that are incorrect.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import numpy as np
import pandas as pd


crit_value = 5794
nparts = 2
df = pd.DataFrame(
    {
        "A": np.ones(crit_value, dtype=int),
        "B": np.arange(crit_value).astype("float32"),
    }
)
dask_sum = dd.from_pandas(df, npartitions=nparts).sum().compute().B
pandas_sum = dd.from_pandas(df, npartitions=nparts).compute().sum().B
diff = dask_sum - pandas_sum
print(f"{(dask_sum, pandas_sum) = }, {diff = }")
(dask_sum, pandas_sum) = (16782321.0, 16782320.0), diff = 1.0
```

**Anything else we need to know?**:
I first encountered this with real world data with a very different distribution from the example above. I stumbled upon the critical value above while trying to simplify. Values below that number don't produce the error. The sign on the difference flips as you increase the crit_value.

It only happens for me when there is more than 1 column and the column being summed is `float32`. I ran into the issue originally when grouping.

It happens for `npartitions>=2`.

I think this is also affecting other aggregations that use sums such as mean and std.

**Environment**:

- Dask version: 2023.9.2
- Python version: Python 3.9.18
- Operating System: Kubuntu 22.04 Linux 5.15.0-83-generic
- Install method (conda, pip, source): conda (conda-forge)

**Comment by fbunt** [comment]
I just noticed that numpy has the same problem:

```python
print(np.arange(crit_value).sum())
print(np.arange(crit_value).astype("float32").sum())
16782321
16782320.0
```

There must be some floating point issue I'm running into and not seeing. I guess this isn't a problem in dask so I'll close the issue.

**Comment by hendrikmakait** [comment]
Thanks for making the extra effort of diving deeper into this. As suspected, you run into a floating-point issue here. The summed value is outside of the range of integer values that can be represented exactly (i.e., with a precision of `1`) using `float32`. I found that https://pythonspeed.com/articles/float64-float32-precision/ is a good read if you interested in more details.

**Comment by fbunt** [comment]
Yep that is the problem. Thank you!
