### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ballegri** [dask/dask#10565]
Hi,

I wanted to install the Dask package to use it in my notebook. I ran the following command:

conda install -c conda-forge dask

in the anaconda prompt which works fine.
However, when I run import dask.dataframe as dd I get the following:

TypeError: 'type' object is not subscriptable

Could you help me out?

Thanks a lot!

**Comment by jrbourbeau** [comment]
Thanks for the issue @ballegri. It's hard to say what's going on without more information. Can you paste the full traceback? Also what version of `dask` and `pandas` are installed?

**Comment by ballegri** [comment]
Thanks for your answer. I managed to work my way around the problem! Thanks
