### ISSUE TITLE
Better name for "Fused Operation"

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10563]
In the task stream today I'm seeing "Fused-operation" a lot.  If possible, it would be nice to get a better name here, even if it's only representative of a couple of operations that have been fused.

**Comment by mrocklin** [comment]
Also, if we keep the name "Fused" in the name (makes sense to me) I'd suggest that we lower-case it.  Most key names are lower-cased.

<img width="1115" alt="Screenshot 2023-10-16 at 7 18 39 PM" src="https://github.com/dask/dask/assets/306380/0f6492bb-6e8b-4eb6-8569-b463bdab0f4c">

**Comment by jrbourbeau** [comment]
This is maybe stemming from `dask-expr` and not `dask` (though I could definitely be missing something here). Grepping through `dask` for the term `Fused` I only see one reference in some `.rst` file but grepping through `dask-expr` I see this [`Fused` blockwise expression](https://github.com/dask-contrib/dask-expr/blob/308e0bcfc6fe4cc6ff1c9e3893a13ac972d6c46c/dask_expr/_expr.py#L2386) which seems like it might be related to this issue. Not saying this isn't an issue, just saying (after only a brief look) it's not clear to me that it's a `dask` issue 

cc @phofl for visibility

**Comment by phofl** [comment]
Yes, this is from dask-expr

**Comment by jrbourbeau** [comment]
Closing in favor of https://github.com/dask-contrib/dask-expr/pull/341. Happy to re-open if needed though

**Comment by rjzamora** [comment]
This issue is indeed related to dask-expr. However, it might be fair to argue that the dask/dask convention is even worse: We only see the name of the root task, and everything else gets "lost."

**Comment by jrbourbeau** [comment]
Agreed (xref https://github.com/dask/dask/issues/8635)

**Comment by mrocklin** [comment]
FWIW I don't plan to think much about task fusion in dask/dask, preferring
instead to focus on improving expressions.
