### ISSUE TITLE
Groupby "observed" being ignored

### ISSUE THREAD

**Issue by frbelotto** [dask/dask#10576]
Hello guys!
I am working on some dask code to replace some pandas code now the dataframe become too big for my memory capacity. I was working on a groupby code and I´ve faced this :

Sample dataframe 
```
import datetime as dt
import pandas as pd
import dask.dataframe as dd
import numpy as np

df = pd.DataFrame({'ProductID': ['Afiliates','End-to-End','Afiliates','Giftcards','Afiliates','Afiliates'],
'partner': ['Amazon','Awin','Amazon','Vivo','Amazon','Oi'],
'date': [dt.datetime(2022,11,1),dt.datetime(2022,11,5),dt.datetime(2022,11,1),dt.datetime(2022,11,10),dt.datetime(2022,11,15),dt.datetime(2022,11,1)],
'customerID' : ['01','01','01','01','02','01'],
'brand' : ['Amazon','Ponto','Amazon','Amazon','Amazon','Amazon'],
'sku':['firetv','alexa','alexa','firetv','firetv','firetv'],
'transactionID': ['51000','55000','51000','53000','54000','51000'],
'gmv' : [10,50,30,40,50,60] })

df = df.astype({'ProductID': 'category', 'partner':'category','brand':'category'})

ddf = dd.from_pandas(df,npartitions=1)
```

As I have some category types, I am using the "observed" feature to avoid rows multiplication.

```
test= ddf.groupby(['ProductID','partner', 'brand',ddf.date.dt.to_period("M"), 'customerID' ], observed=True).aggregate({'sku': 'count', 'transactionID': 'count', 'gmv': 'sum'})
test.compute()
```

![image](https://github.com/dask/dask/assets/24688087/2efd006f-41b5-44c6-a640-ae95dd6cb7e8)

Sadly, one of my columns I does not need only a "simple count", I need the number of unique values. So I need to code another query for the Nunique() data.

```
test= ddf.groupby(['ProductID','partner', 'brand',ddf.date.dt.to_period("M"), 'customerID' ], observed=True)['transactionID'].nunique()
test.compute()

```
![image](https://github.com/dask/dask/assets/24688087/a8a1ff0a-bbf4-4250-884e-e8bcb69bed5e)

As you can see, my code is not considering only the "observed" categories. I am not sure if its a bug or I got a misundersing as I could extract the nunique values of such column. I´ve tried the "aggregate({''transactionID': 'nunique'})" as I do on pandas, but dask does not support such agregation function. 

**Environment**:

- Dask version: 2023.9.3
- Python version: 3.11.6
- Operating System: Windows 11
- Install method (conda, pip, source): PIP

**Comment by phofl** [comment]
Hi, thanks for your report. This is the same cause as #10550. The fix should be straightforward if you are interested in looking into it
