### ISSUE TITLE
Reading and writing data from cloud storage or bigquery

### ISSUE THREAD

**Issue by orlandombaa** [dask/dask#10582]
Hello 

I would like to migrate some local ETL process from Apache Spark to Dask. In order to do this I have to be able to read and write  data from/to  Cloud Storage (in form of parquet) or BigQuery directly into a dask dataframe. 

Can Dask do this?, I have tried to do this without success. I  share one of the code that I have been triying: 

```import dask.dataframe as dd
from google.oauth2.credentials import Credentials
from google.oauth2 import service_account
import gcsfs
from google.cloud import storage

# Definir la ruta completa al archivo Parquet en GCS
path = 'gs://etl-dask/temporales/test_exportar.parquet'

# Configurar gcsfs con las credenciales de la cuenta de servicio
gcs = gcsfs.GCSFileSystem(token='google-oauth', project='ciencia-de-datos-398421',
                          keyfile_path='Credenciales.json', access="full_control")
gcs

# Leer el archivo Parquet a un Dask DataFrame
df_dask = dd.read_parquet(path=path)

# Visualizar las primeras filas (esto iniciará una computación, ya que Dask es de evaluación perezosa)
print(df_dask.head())
```

**Comment by orlandombaa** [comment]
I was available to make the connection to bigquery with sql alchemy, now I can read my tables directly into a dask dataframe. However, I still can not  write and read parquets from cloud storage directly to a dask df

**Comment by mrocklin** [comment]
Hi @orlandombaa , 

For Dask-BigQuery see https://github.com/coiled/dask-bigquery

For parquet `dd.read_parquet` is correct.  Permissions can be interesting.  It depends also on how you have deployed Dask.  Often the system deploying Dask will handle permissions.

**Comment by orlandombaa** [comment]
Hello @mrocklin  thank you so much for your answer. 

I just did the 2 process , I made the connection with sqlalchemy to BQ. However, now I have a different doubt.  When I read a table using the function of `read_sql_query` do I must to indicate the parameter `index_col` ? , because now I am reading a table from bigquery and this table doest not contain any column that can be use logically as a index column. 

I see 3 options: 
- create in the table a ID column which just have an incresing number 
- pick up any column even if this columns does not have so much sense as a index columns 
- somehow avoid the use of the parameter `index_col`

**Comment by mrocklin** [comment]
Instead of using sqlalchemy I recommend using the dask-bigquery package.  This problem will not exist there.

**Comment by orlandombaa** [comment]
Thank you again for your answer @mrocklin 

The thing in my case is that I am transfering  my ETL process from spark to Dask. So the conections to  GCP ( to cloud storage and bigquery) I want it mainly to write the data after processing. However, before to  this I need make conections to different data sources such as SAP, MySql and Sqlserver. 

So the connections using sqlalchemy looks like a general solution for me to make those previous connections.  Having said that, is possible to don´t indicate a `index_col` ?
