### ISSUE TITLE
`dask/array/tests/test_array_core.py::test_setitem_hardmask` failing on Windows with Python 3.12

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10604]
We're seeing this fail consistently over in https://github.com/dask/dask/pull/10544 with

```
FAILED dask/array/tests/test_array_core.py::test_setitem_hardmask - AssertionError: {('array-ca2bfc119ac07031ee36eb791623951f',): 2}
assert not {('array-ca2bfc119ac07031ee36eb791623951f',): 2}
```

This is niche enough that I don't want to block Python 3.12 support in general, so am instead `xfail`ing temporarily and opening this issue track.

**Comment by rjzamora** [comment]
Closed by https://github.com/dask/dask/pull/10701
