### ISSUE TITLE
Toggle to switch DataFrame API to use dask-expr (but not as default)

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10633]
There's been a lot of momentum around [`dask-expr`](https://github.com/dask-contrib/dask-expr) recently and we posted already a couple of blog posts ([introduction](https://blog.dask.org/2023/08/25/dask-expr-introduction) and [tpch benchmarks](https://blog.coiled.io/blog/dask-expr-tpch-dask.html)) that show how this new approach can be transformative to the performance and usability of the dataframe.

The project is not quite feature complete but the core API is implemented and functioning well enough for us to make the first step and add this to the main project via a feature toggle.

Implementing a feature toggle like this presents us with a certain challenge from an implementation POV since we have plenty of submodules in the `dask.dataframe` module that will be sensitive to such a switch. Many functions that can be imported from those modules will likely not work on a dask-expr DataFrame.

One proposal would be to drop all submodules in favor of allowing only imports from `dask.dataframe.__init__.py` and renaming all submodules s.t. they have an underscore signaling it to be private API.

The feature toggle could then easily be implemented at this central place and we could introduce proper deprecation warnings.

xref https://github.com/dask-contrib/dask-expr/issues/374

**Comment by phofl** [comment]
This is the default and only option now now
