### ISSUE TITLE
`X.T @ X` is almost 2 times slower if `X` has any dependencies in the task graph

### ISSUE THREAD

**Issue by timothymillar** [dask/dask#10645]
**Describe the issue**:

This is a possible performance issue with matrix multiplication in dask.array. There may be a good reason why it can't be improved and I apologize if I have missed any previous relevant discussions.

In numpy, `X.T @ X` is roughly 2x faster than `X.T @ Y` which I presume is due to optimization of the special case. This appears to be the same in dask.array so long as `X` has no dependencies in the task graph. If `X` has any dependencies then `X.T @ X` has similar performance to `X.T @ Y`. My best guess is that this is caused by duplication of the matrix during evaluation of the task graph.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da
import pandas as pd
from timeit import timeit

# setup
times = {
    "numpy XtX": [],
    "numpy XtY": [],
    "dask XtX": [],
    "dask XtY": [],
    "dask ZtZ": [],
}
reps = 7
n_col = 5_000
n_row_sizes = [10_000, 20_000, 40_000]
for n_row in n_row_sizes:
    X = np.random.rand(n_row * n_col).reshape(n_row, n_col)
    Y = np.random.rand(n_row * n_col).reshape(n_row, n_col)
    # numpy timings
    times["numpy XtX"].append(timeit(lambda : X.T @ X, number=reps) / reps)
    times["numpy XtY"].append(timeit(lambda : X.T @ Y, number=reps) / reps)
    # dask timings
    X = da.asarray(X, chunks=-1)  # ensure that we are using a single chunk
    Y = da.asarray(Y, chunks=-1)
    Z = X + da.zeros(1)  # Z is identical to X but with a dependency
    times["dask XtX"].append(timeit(lambda : (X.T @ X).compute(), number=reps) / reps)
    times["dask XtY"].append(timeit(lambda : (X.T @ Y).compute(), number=reps) / reps)
    times["dask ZtZ"].append(timeit(lambda : (Z.T @ Z).compute(), number=reps) / reps)
df = pd.DataFrame(times)
df.index = n_row_sizes
df.index.name = "n rows"
df.round(3)
```

After warming up the CPU this results in:

|   n rows |   numpy XtX |   numpy XtY |   dask XtX |   dask XtY |   dask ZtZ |
|---------:|------------:|------------:|-----------:|-----------:|-----------:|
|    10000 |       1.681 |       2.945 |      1.837 |      3.188 |      3.417 |
|    20000 |       3.428 |       6.5   |      3.683 |      7.032 |      7.229 |
|    40000 |       7.417 |      13.935 |      7.352 |     14.082 |     14.345 |

So `Z.T @ Z` performs similarly to `X.T @ Y` rather than `X.T @ X` even though `Z` should be identical to `X`. From what I can tell, the only difference is that `Z` has a dependency in the task graph. Obviously, evaluation of `Z.T @ Z` is also evaluating `X + 0` but that should account for a negligible portion of the execution time (~250 ms when `X` has 40,000 rows).

**Anything else we need to know?**:

**Environment**:

- WSL2 (Ubuntu)
- Conda environment:
  - Python 3.11.6 (conda-forge)
  - dask==2023.11.0 (pip)
  - numpy==1.26.2 (pip)

**Comment by fjetter** [comment]
Thanks for opening this issue. This is indeed an interesting case. FWIW I have no idea what numpy is doing to be faster when it's a same-matrix multiplication but I guess that doesn't really matter.

Interestingly, this is somehow connected to task fusion and I wonder if there are any bigger implications here or if this is just affected this specific case.

if you set

```python
```
