### ISSUE TITLE
"config" is not exported from module "dask" 

### ISSUE THREAD

**Issue by tekumara** [dask/dask#10657]
**Describe the issue**:

pyright/vscode errors with:
```
 error: "config" is not exported from module "dask" (reportPrivateImportUsage)
``` 

pyright (and therefore vscode) considers these symbols private based on [these rules](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface). 

**Minimal Complete Verifiable Example**:

```python
    dask.config.update(
        dask.config.global_config,
        {"kubernetes": {"scheduler-pdb-template": {"spec": {"minAvailable": 0}}}},
    )
```

**Anything else we need to know?**:

[PEP 008](https://peps.python.org/pep-0008/#public-and-internal-interfaces) states modules should explicitly declare the names in their public API using the `__all__` attribute .
[PEP 484](https://www.python.org/dev/peps/pep-0484/#stub-files) also mentions that imported modules are not considered exported unless they use the `import ... as ...` syntax or equivalent. 

**Environment**:

- Dask version: [2023.11.0](https://github.com/dask/dask/releases/tag/2023.11.0)
- Python version: 3.11
- Operating System:
- Install method (conda, pip, source):

**Comment by jrbourbeau** [comment]
Thanks @tekumara, sorry for the lack of response here. Closing in favor of https://github.com/dask/dask/issues/9710
