### ISSUE TITLE
map_blocks errors with numpy 1.26.0

### ISSUE THREAD

**Issue by Huite** [dask/dask#10658]
`map_blocks` raises an attribute error when used with numpy 1.26

**Minimal Complete Verifiable Example**:

```python
import dask.array as da

x = da.arange(6, chunks=3)
x.map_blocks(lambda x: x * 2).compute()
```

Which results in:

```
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

`np.object` isn't used though: `np.object_` is used twice in array.core: 

https://github.com/dask/dask/blob/5d75a04132d5ea1535287a649310c8529dbb3a79/dask/array/core.py#L901
https://github.com/dask/dask/blob/5d75a04132d5ea1535287a649310c8529dbb3a79/dask/array/core.py#L979

So I'm a little confused about why it's erroring here.

For what it's worth, writing `dtype=object` instead seems to work fine for me locally.

**Comment by phofl** [comment]
Hi, thanks for your report. 

Your reproducer works for me without raising

I am on NumPy 1.26

```
numpy                     1.26.0          py311hb8f3215_0    conda-forge
```

Which Dask version are you on? I am on main
