### ISSUE TITLE
Rewrite docs landing page

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10670]
The dask landing page uses fairly old language.  Probably it's time to revisit this.

My main concern looking through it is that it's largely developer focused, rather than user focused.  It talks about how Dask is organized internally ("Composed of two parts, a task scheduler and high level collections").  Also in general I think that we've just gotten better at writing in the last decade. 

I'd like to take a crack at rewriting the high level messaging.  Raising this issue here in case folks want to raise ideas early.

**Comment by jrbourbeau** [comment]
Marking this closed via https://github.com/dask/dask/pull/10674. Feel free to re-open is that's not the case.
