### ISSUE TITLE
'python setup.py install' omits dask.dataframe.tseries

### ISSUE THREAD

**Issue by keewis** [dask/dask#1067]
installing `dask.dataframe` using setuptools does not install dask.dataframe.tseries (the result is that resampling fails with an `ImportError`):
```bash
$ virtualenv test_dask_install
$ source test_dask_install/bin/activate
$ pip install dask[dataframe]
$ python -c 'import dask.dataframe.tseries.resample'  # ImportError
$ pip download dask
$ tar xfz dask-0.8.1.tar.gz
$ cp -r dask-0.8.1/dask/dataframe/tseries test_dask_install/lib/python3.4/site-packages/dask/dataframe
$ python -c 'import dask.dataframe.tseries.resample'  # no ImportError
```

The reason seems to be that `setuptools` does not automatically include subpackages.
As far as I know, there are two possible solutions for this:

1. to include the `tseries` package in `setup(packages=[...])`
2. as the `tseries` package only contains one module (`resample`), it could be moved into the `dataframe` package (and thus would be in a similar position as the `groupby` module, which gets imported at the first call of a groupby function to avoid circular imports)

**Comment by jcrist** [comment]
The `tseries` subpackage was created in a recent-ish reorganization (https://github.com/dask/dask/pull/964). Looks like we missed updating the setup.py file (note that this only affects install with setuptools - both the pip and conda packages still work fine). Easy fix, thanks for reporting.
