### ISSUE TITLE
Add a `.__wrapped__` (or similar) attribute for `@dask.delayed`-decorated functions

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dask/dask#10685]
It would be nice if the `@dask.delayed`-decorated function had an attribute that could be called to return the undecorated function. Drawing inspiration from the widely used [`functools.wraps()`](https://docs.python.org/3/library/functools.html) function, I would suggest calling it `.__wrapped__` for consistency. Having the ability to quickly strip off the decorator can be very useful for those building libraries around Dask-delayed functions. For instance, imagine a scenario where you have made a library of pre-decorated functions. If you want to use that function in another module but _not_ have it be delayed, there is currently no way to do so without copying/pasting. In practice, what you would like is something like so:

```python
from dask import delayed

@delayed
def add(a, b):
    return a+b

add.__wrapped__(1,2) # 3, not delayed
```

Note that because Delayed objects are immutable, it's not possible for someone like me to "manually" add the `.__wrapped__` attribute after the Delayed function is made.

**Comment by mrocklin** [comment]
I'm not opposed

**Comment by hendrikmakait** [comment]
@Andrew-S-Rosen: Thanks for raising this issue. This feels like a useful addition, also for introspection. Would you be interested in contributing a PR that adds the `.__wrapped__` attribute?
