### ISSUE TITLE
Nice visual for docs page

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#10718]
The docs homepage looks like this today:

<img width="1466" alt="Screenshot 2023-12-18 at 12 57 57 PM" src="https://github.com/dask/dask/assets/306380/63d1be23-a968-47d9-aca2-905d0440fa73">

There's a void above the fold in the upper right of the main contents.  I think it might be useful to have a small visual there, maybe something like the task stream.  @scharlottej13 do we have any good animation content that we can throw up there that you know of?

**Comment by scharlottej13** [comment]
Ooh yeah we have a couple of dashboard already (both _should_ be viewable publicly):

1. https://drive.google.com/file/d/14B7wXRGkrJClpZb40yZGBEKFvqAYqd6J/view?usp=sharing
2. https://drive.google.com/file/d/1BXYtd7w06x3N3EQVWht4AUErKsGOTIZ3/view?usp=sharing (my preference for the homepage b/c it's simpler and the task stream looks more fun)

Or we can make a new one

**Comment by mrocklin** [comment]
Hrm, those are both bigger and have more whitespace than I would be excited
about.  I'm thinking more something like what's at the top of
https://docs.coiled.io/user_guide/index.html , but without the Coiled bits.

**Comment by scharlottej13** [comment]
Oh nice! Just opened a draft PR w/ the wistia snippet embedded
