### ISSUE TITLE
dask.bag.to_textfiles does not store each element in a line

### ISSUE THREAD

**Issue by Jeffrey04** [dask/dask#1072]
Not sure if this is intended, but in the [documentation](http://dask.pydata.org/en/latest/bag.html) it is mentioned the behaviour of `bag.to_textfiles()` should be

```
Write bag to disk, one filename per partition, one line per element
```

However, as reproduced in the following example, it actually stores everything in a line

```
import dask.bag as db

db.from_sequence(range(10), 10) \
    .map(str) \
    .to_textfiles('foo.*.txt')
```

and the output file reads

```
0123456789
```

After some tinkering, replacing this loop in the `write()` function (in `dask/bag/core.py`) from

```
        for line in data:
            f.write(line.encode(encoding))
```

to

```
        for i, line in enumerate(data):
            f.write((line if i == 0 else '\n{}'.format(line)).encode(encoding))
```

seems to work as mentioned in the documentation

**Comment by mrocklin** [comment]
When I run this code:

```python
In [1]: import dask.bag as db
In [2]: db.from_sequence(range(10), npartitions=10).map(str).to_textfiles('foo.*.txt')
```

I get files like these:

```
mrocklin@notebook:~/tmp/foo$ ls
foo.0.txt  foo.2.txt  foo.4.txt  foo.6.txt  foo.8.txt
foo.1.txt  foo.3.txt  foo.5.txt  foo.7.txt  foo.9.txt
```

Where each file has just one line because each partition has just one element.

```
$ cat foo.0.txt
0
```

This seems correct to me.

However, if I do this same example with fewer partitions

```python
In [4]: db.from_sequence(range(10), npartitions=3).map(str).to_textfiles('foo.*.txt')
```

Then I find that my files lack endlines, as you suggest

```
$ cat foo.0.txt 
0123
```

So perhaps we should map a function that ensures text has endlines

```python
def ensure_endline(line):
    return line if line.endswith(os.linesep) else line + os.linesep
```

**Comment by Jeffrey04** [comment]
erm, actually this happens regardless the partition count

**Comment by mrocklin** [comment]
See #1074
