### ISSUE TITLE
Deprecate ``shuffle`` keyword in favour of ``shuffle_method`` for DataFrame methods

### ISSUE THREAD

**Issue by phofl** [dask/dask#10724]
dask-expr already changed the shuffle keyword to be a bit more explicit, we should deprecate this here to enforce when moving over

Get us consistent with the config option as well

**Comment by jrbourbeau** [comment]
Are there cases where `shuffle=` isn't specific enough? All other things being equal, I think a shorter name is better

**Comment by phofl** [comment]
shuffle for me is just very unspecific, could be a bool or something else. shuffle_method expresses the intent of the option very clearly. It's inconsistent with the config option as well

**Comment by hendrikmakait** [comment]
> shuffle for me is just very unspecific, could be a bool or something else. shuffle_method expresses the intent of the option very clearly. It's inconsistent with the config option as well

+1

**Comment by jrbourbeau** [comment]
Hmm, there's a tradeoff between making things very explicit and having overly long parameter names. In my mind `shuffle="p2p"` is clear enough (especially if it's clearly documented and used consistently as a keyword).

Though to be clear, I don't care a ton about this specific case -- my hope is most people are happy with the default shuffle algorithm and won't ever need to specify this option. I mostly just want to bring up the explicit vs. concise tradeoff to make sure we're considering it.

**Comment by hendrikmakait** [comment]
> shuffle for me is just very unspecific, could be a bool or something else. shuffle_method expresses the intent of the option very clearly. It's inconsistent with the config option as well

Note that the `shuffle` keyword can be a `bool` for groupby-aggregates: https://github.com/dask/dask/blob/2d8f6d54ce28a5b2311a96c2009431e09017eecb/dask/dataframe/groupby.py#L1332-L1341

In light of this, renaming `shuffle` to `shuffle_method` for all the cases where only a method is accepted is even more relevant to highlight the distinction.

We may also want to reconsider dumping all kinds of things into `shuffle` for groupby-aggregates.
