### ISSUE TITLE
Setup unit test overview and test report

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10732]
CI has been a little fragile the last couple of days. In distributed we put in some infrastructure that helps us identify failing tests.

- Unit Test Results aggregation

Every job aggregates the unit test results over the test matrix, e.g. (sorry, bad example ince there is only one failing test :) 

![image](https://github.com/dask/dask/assets/8629629/9f1ff9bc-12e7-4e1f-a0e2-2fb80c99efb5)

What's even more useful is the test report, see https://dask.github.io/distributed/test_short_report.html

For instance, this test is failing sporadically on py3.10 and below but it happens frequently so it is likely a problem (see https://github.com/dask/distributed/pull/8425)
![image](https://github.com/dask/dask/assets/8629629/f0b8bef1-6242-4d6d-b54e-346dd2055d4e)

while this one is something that is likely of no concern

![image](https://github.com/dask/dask/assets/8629629/d74e5210-1248-42d5-a87b-a1007dfe9a4b)

**Comment by jrbourbeau** [comment]
Seems reasonable to me
