### ISSUE TITLE
Deprecate compute keyword for set_index

### ISSUE THREAD

**Issue by phofl** [dask/dask#10737]
This is only relevant if you have a disk based shuffle and I don't really know what the advantage of the keyword would be.

It seems like something that we should clean up

**Comment by rjzamora** [comment]
Yeah, that code path does seem like an old optimization to me. When I first saw this issue, I thought the `compute` arg may have something to do with the new divisions calculation. However, as far as I can tell, [this block](https://github.com/dask/dask/blame/6dc86556950f65baf1b6fc934df932c9cad22cb2/dask/dataframe/shuffle.py#L632) is indeed persisting the shuffled collection to disk.

**Personal Thoughts**
I can actually imagine many cases where a disk-based persist mechanism like this can be useful. However, (1) I don't think many people are using "disk" for the cases that would benefit, and (2) I don't think this kind of mechanism makes much sense *within* the `shuffle` API like this. Instead, this kind of mechanism should be exposed to the user in such a way that it is clear that the query is being segmented. For example, the user should need to call something like `df.persist(storage=..., shuffle_method=...)`.

**Comment by phofl** [comment]
Yeah that might make more sense, the current keyword is just weird
