### ISSUE TITLE
Consider adding nonzero/flatnonzero to dask.array

### ISSUE THREAD

**Issue by shoyer** [dask/dask#1076]
This would need to eagerly evaluated, or perhaps return an imperative value, because the result shape is not known apriori.

This sort of thing could be useful for https://github.com/pydata/xarray/pull/815 if you want to mask out a small region of a very large array. For example, imagine you have a tiled digital elevation model dataset at high resolution covering the globe, and now you want to extract out the region corresponding to California. There are certainly more intelligent indexing strategies for geospatial data, but I could see something like `ds.sel_where(ds.region_enum == CALIFORNIA)` being convenient.

**Comment by jakirkham** [comment]
Indeed this definitely could come in handy for a few other cases I can think of. Just to provide an example of one, coming up with some seeds to use for performing a watershed.

**Comment by shoyer** [comment]
Note that the path forward here is now much more straightforward than it was when I originally filed this issue, because the dask.array data model now allow for unknown dimension sizes. So `nonzero()` could return an flat array of unknown size, with one block per block in the original array.

**Comment by jakirkham** [comment]
Oh that is really neat! Are there some docs explaining how this works? Definitely have some use cases for an unknown dimension size.

**Comment by shoyer** [comment]
I think it's as simple as using `np.nan` for unknown chunk sizes, e.g., `chunks=((np.nan,) * 10,)` for a 1d array with 10 chunks, each of unknown size. I don't know if @mrocklin has written up anything describing it in more detail.

**Comment by mrocklin** [comment]
Current docs are limited to http://dask.pydata.org/en/latest/array-creation.html#unknown-chunks

**Comment by jakirkham** [comment]
Is it only unknown chunks or are unknown dimension lengths for the overall array allowed too?

**Comment by mrocklin** [comment]
Unknown dimension lengths are fine

**Comment by jakirkham** [comment]
Would it be ok for `nonzero` to be a 2-D array?

Also with these unknown shapes why is slicing not allowed? It seems like this should be permissible as it is even possible to slice an empty list. Would it be possible to relax this constraint?

```python
>>> list()[0:1]
[]
```

**Comment by shoyer** [comment]
> Would it be ok for nonzero to be a 2-D array?

I guess it could, in principle, but I would prefer a tuple for consistency with NumPy.

> Also with these unknown shapes why is slicing not allowed? It seems like this should be permissible as it is even possible to slice an empty list.

I think it's just a matter of logic not having been needed or implemented yet.

**Comment by jakirkham** [comment]
What would the `tuple` be of? Dask Arrays? If so, I guess that could work.

> I think it's just a matter of logic not having been needed or implemented yet.

It would be good to know more details on what logic and the extent of the change required to support this.

**Comment by shoyer** [comment]
Yes, a tuple of dask arrays.

**Comment by jakirkham** [comment]
What do you mean by a few corner cases? Do you mean of slices? It's possible I don't understand what you are saying hence the questions. However, if I do understand you correctly, it's not accurate to say there are only a couple corner cases that make sense. Any slice is permitted on any object that permits slicing. This includes ones that are totally out of bounds even on non-empty sequences. For example...

```python
>>> [0, 1, 2][0:10]
[0, 1, 2]
>>> [0, 1, 2][3:10]
[]
```

The Python documentation backs this up by noting that "...out of range slice indexes are handled gracefully when used for slicing". In fact, this is why I'm raising this question about slicing in particular. Since we actually don't know what the length of the unknown dimension is, but we do know that it has *some* length, we should be allowed to slice it. As long as it is a well formed slice, we should be able to get some result and not an exception.

**Comment by mrocklin** [comment]
We don't know which chunks to inspect to get the first ten elements.  Is it only the first chunk?  The first few?  We can't answer this question without knowing the size of the chunks.

**Comment by jakirkham** [comment]
I see. Are there cases where we can know the chunk size and not some dimensions of the overall shape?

**Comment by mrocklin** [comment]
Unknown chunk sizes in any dimension imply unknown length of that dimension

It should be possibleto slice in other dimensions that have known shape.

**Comment by jakirkham** [comment]
Sorry, I guess that was unclear. What I was trying to say is could we have a chunk size say `(1, 101, 102)` and array with shape `(nan, 101, 102)`?

**Comment by mrocklin** [comment]
Dask arrays store the size of every chunk, not a single chunksize

```python
In [1]: import dask.array as da

In [2]: x = da.ones((10, 10), chunks=(3, 4))

In [3]: x.chunks
Out[3]: ((3, 3, 3, 1), (4, 4, 2))
```

See http://dask.pydata.org/en/latest/array-design.html#chunks

**Comment by jakirkham** [comment]
I guess what I'm trying to get at (to bring us back from this tangent I put us on, sorry) is `nonzero` will probably be something that scans through the elements looking for matches. So it seems if one just wants to find the first non-zero element or some similar subset, they shouldn't need to compute the full result. They should be able to somehow say, "give the me the first match if there is one". My naive thinking is this would be through slicing (e.g. `nz[:, 0:1]`), but maybe there is another way to approach this.

**Comment by mrocklin** [comment]
If you don't want to evaluate the entire result then you'll need to know which chunks to look for, in advance.  Generally this isn't doable.  Dask.array isn't good when the structure of the computation depends on the values of the array.

**Comment by jakirkham** [comment]
Have put together a working implementation using Dask Array's [`compress`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.compress ) function in PR ( https://github.com/dask/dask/pull/2539 ).

**Comment by jakirkham** [comment]
>> Would it be ok for nonzero to be a 2-D array?
>
> I guess it could, in principle, but I would prefer a tuple for consistency with NumPy.

FTR it appears that [`argwhere`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html ) satisfies this requirement. Have also included that in the aforementioned PR.
