### ISSUE TITLE
Deprecate use_nullable_dtypes from read_parquet

### ISSUE THREAD

**Issue by phofl** [dask/dask#10775]
pandas deprecated this as well, so lets rip it out before moving to dask-expr

**Comment by hendrikmakait** [comment]
It looks like this is already deprecated in `pyarrow`: https://github.com/dask/dask/blob/ca42dcf5fcd4fd7438c705820d0c0692ab99023b/dask/dataframe/io/tests/test_parquet.py#L663-L667

and not supported in `fastparquet`: https://github.com/dask/dask/blob/ca42dcf5fcd4fd7438c705820d0c0692ab99023b/dask/dataframe/io/tests/test_parquet.py#L651-L653

**Comment by phofl** [comment]
I think this comes from pandas, but we deprecated this In 2.0, so might be worth not doing anything, closing

**Comment by hendrikmakait** [comment]
The deprecation comes from `read_metadata` which we call from `read_parquet`: https://github.com/hendrikmakait/dask/blob/70f2f78c7373eeafc2990c5088fb7a2b43a6a232/dask/dataframe/io/parquet/arrow.py#L510-L528
