### ISSUE TITLE
toolz-0.12.0 doesn't have tlz.curry that is expected by dask-2023.12.1

### ISSUE THREAD

**Issue by yurivict** [dask/dask#10780]
**Describe the issue**:

```
[yuri@yv /usr/ports/science/py-thewalrus]$ python3.9
Python 3.9.18 (main, Dec 10 2023, 01:22:40) 
[Clang 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1 on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> from tlz import curry, groupby, identity, merge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tlz/_build_tlz.py", line 55, in exec_module
    toolz_mods = self._load_toolz(module.__name__)
  File "/usr/local/lib/python3.9/site-packages/tlz/_build_tlz.py", line 29, in _load_toolz
    raise ImportError(fullname)
ImportError: tlz.curry
>>>
```

**Environment**:

- Dask version: 2023.12.1
- Python version: 3.9
- Operating System: FreeBSD 14.0
- Install method (conda, pip, source): package

**Comment by hendrikmakait** [comment]
@yurivict: Thanks for reporting this issue. Unfortunately, I can't reproduce it locally. When creating a fresh environment with `python=3.9` and `toolz=0.12.0`, `from tlz import curry` works just fine on my Mac. 

Could you try creating a fresh environment and see if the issue persists?

**Comment by yurivict** [comment]
You are right, dask isn't a problem.

The issue appears to be in the toolz package.
