### ISSUE TITLE
GPU CI failing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10809]
gpuCI started failing with errors like

```
07:54:10 FAILED dask/dataframe/tests/test_shuffle.py::test_sort_values_tasks_backend[True-by2-cudf] - ValueError: Unsupported input arguments passed : ['shuffle']
```

After (I assume) the recent `shuffle` --> `shuffle_method` change

See [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/5321/CUDA_VER=11.8.0,LINUX_VER=ubuntu20.04,PYTHON_VER=3.10,RAPIDS_VER=24.02/console) for more details

cc @rjzamora as I think you mentioned this recently in an offline call

**Comment by phofl** [comment]
@rjzamora I assume we can close this now?

Thx for addressing this

**Comment by rjzamora** [comment]
Yep. Looks like we are good for now. Thanks!
Feel free to ping me if anything else pops up in GPU CI
