### ISSUE TITLE
pandas 2.2: dask-expr failure in test_groupby_reduction_split[median]

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#10847]
`test_groupby_reduction_split` has started failing, in the dask-expr CI only and only for median, when pandas upgraded from 2.1.4 to 2.2 this weekend:
https://github.com/dask/dask/actions/runs/7611579970/job/20727329263?pr=10845

CC @phofl

**Comment by phofl** [comment]
This was unrelated to pandas 2.2 and rather a side-effect of not merging a dask-expr PR. This is fixed now so closing
