### ISSUE TITLE
Tests for dummy data generation failing

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10858]
Looks like there are some tests failing for the dummy data generation

https://dask.github.io/dask/test_short_report.html

https://github.com/dask/dask/actions/runs/7650514559/job/20846717103

**Comment by jrbourbeau** [comment]
I haven't looked into this one deeply, but it looks like the latest release removes `age` in favor of a `randint` method https://mimesis.name/en/master/changelog.html#version-13-1-0

I'll see if adding a simple pin works as a temporary fix
