### ISSUE TITLE
pyright: "read_parquet" is not exported from module "dask.dataframe"

### ISSUE THREAD

**Issue by dluks** [dask/dask#10859]
**Describe the issue**:
For those who use `pyright` for type hinting, `dask.dataframe.read_parquet` throws the following `reportPrivateImportUsage` error: `"read_parquet" is not exported from module "dask.dataframe"`

This also occurs with `dask.dataframe.read_csv`. I haven't tested any other IO-related methods.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

ddf = dd.read_parquet("file.parquet")
```

**Environment**:

- Dask version: 2024.1.0
- Python version: 3.10.13
- Operating System: Ubuntu 22.04.3 LTS
- Install method (conda, pip, source): poetry

**Comment by jrbourbeau** [comment]
Thanks for the issue @dluks. This looks like the same as https://github.com/dask/dask/issues/9710. I'm going to close this issue in favor of consolidating conversation over in https://github.com/dask/dask/issues/9710
