### ISSUE TITLE
store and get_async bugs

### ISSUE THREAD

**Issue by alimanfoo** [dask/dask#1092]
I've run into a couple of bugs I think related to manually specifying the get function when using the da.store function. See this notebook: https://gist.github.com/alimanfoo/3cc169bd5108fb6bc8bb44a388390ec8

* When I use set_options I get the "get_async() missing 2 required positional arguments: 'dsk' and 'result'" error
* When I provide the get argument directly along with num_workers I get the "get_async() got multiple values for argument 'num_workers'" error

**Comment by jcrist** [comment]
`get_async` is a function used for building up schedulers, and not externally facing api directly. The existing schedulers are [described in the docs here](http://dask.pydata.org/en/latest/scheduler-overview.html).

**Comment by alimanfoo** [comment]
Thanks, I should rtfd properly.
