### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [dask/dask#10956]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by hendrikmakait** [comment]
cc @jrbourbeau, thoughts? Having automated release notifications would be nice, but I don't know the release process.

**Comment by mrocklin** [comment]
Maybe @jacobtomlinson would have thoughts here.  He's historically cared the most about automation.

**Comment by jacobtomlinson** [comment]
I think this is more of a small change to the [release procedure](https://github.com/dask/dask/blob/main/docs/release-procedure.md) than an automation.

Given that the `gh` CLI tool is already mentioned in the release procedure it would be easy to add a one line command to create the "GitHub release" which is effectively just a pointer to a tag with optional text and file attachments. 

At a minimum we could do the following after pushing the tags.

```bash
gh release create YYYY.M.X --notes-from-tag
```

We could also include the changelog as the release body, although this would include the whole changelog. We might want to be even more clever and just snip out the new section.

```bash
gh release create YYYY.M.X -F change.md
```

I assume we don't want to do things like attach the source distribution and wheel generated by `build`/`twine` to the release, but that would be easy to do as well. We just run another command after the `build`/`twine` step to upload the distributions.

```bash
gh release upload YYYY.M.X dist/*
```

Given that this generally done by @jrbourbeau I'll put it to him to set the appetite for doing this.

**Comment by kloczek** [comment]
Thank you 👍 😄
