### ISSUE TITLE
Inconsistent casting behaviour with dask-expr Dataframe

### ISSUE THREAD

**Issue by CaliPolys** [dask/dask#10960]
**Describe the issue**:

Not sure if this falls neatly into the bug category, but I'm experiencing what seems inconsistent behaviour for casting a dataframe column with the new dask-expr implementation in my existing code base. The code below shows a minimal example of how the dtypes never get updated. However, if one switches off the query planning by commenting or deleting dask.config.set({"dataframe.query-planning": True}), the old dask.Dataframe produces the desired casting to int.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask
dask.config.set({'dataframe.query-planning-warning': False})
dask.config.set({"dataframe.query-planning": True})
import dask.dataframe as dd

pd.options.mode.copy_on_write = True

pdf = pd.DataFrame({"col1:": ["foo", "foo", "foo"], "col2": ["MG4", "MZ5", "MY6"]})

print("\nPanda's types")
print(pdf.dtypes)

ddf = dask.dataframe.from_pandas(pdf, npartitions=1)

print("\nDask's types")
print(ddf.dtypes)

ddf["col2"] = ddf.col2.str.slice(start=2)
ddf.col2 = ddf.col2.astype(int)

print("\nDask's types after conversion")
print(ddf.dtypes)

computed_df = ddf.compute()

print("\nDask's types after conversion and compute()")
print(computed_df.dtypes)
```
Output:

```python
Panda's types
col1:    object
col2     object
dtype: object

Dask's types
col1:    object
col2     object
dtype: object

Dask's types after conversion
col1:    object
col2     object
dtype: object

Dask's types after conversion and compute()
col1:    object
col2     object
dtype: object
```

This is the output when switching off the dataframe.query-planning ( ie. ```python dask.config.set({"dataframe.query-planning": False}```), which seems consistent with previous behaviour:

```python
Panda's types
col1:    object
col2     object
dtype: object
Dask's types
col1:    string[pyarrow]
col2     string[pyarrow]
dtype: object
Dask's types after conversion
col1:    string[pyarrow]
col2               int32
dtype: object
Dask's types after conversion and compute()
col1:    string[pyarrow]
col2               int32
dtype: object
```

**Anything else we need to know?**:
I have managed to make the new dask-expr work by collapsing the casting into a single line: (ie ```python ddf["col2"] = ddf.col2.str.slice(start=2).astype(int)```). But it seems the semantics of the dataframe object have somewhat changed, which could affect deployed code (unless I may not be aware of some guiding/best practice for chaining accessors with casting operations... any advise appreciated). 

This post is related to my post in https://dask.discourse.group/t/dask-expr-casting-problem/2565, but I took the liberty to repost here since this was getting deeper into coding and the actual building/design of the library.

**Environment**:

- Dask version: 2024.2.1
- Python version: 3.11
- Operating System: Windows 11 Pro
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Thanks for your report. this is already on our todo list https://github.com/dask-contrib/dask-expr/issues/691
