### ISSUE TITLE
Drop pandas 1.X support?

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10962]
pandas 1.X has been released about 10 months ago and pandas 3.0 is on our doorstep. We're keeping a lot of compatibility code around, both in tests and in actual code. Additionally, we soon want to switch the default backend of `dask.dataframe` to `dask-expr` which **requires** `>=2.X`.

Therefore, I want to propose to drop support for 1.X with the next release.

Thoughts or concerns?

**Comment by crusaderky** [comment]
Now dask[dataframe] has a hard dependency on dask-expr, which in turn depends on pandas>=2.0.

CC @jrbourbeau a conscious choice on this point should be a blocker fo the next release.

**Comment by jrbourbeau** [comment]
Just wanted to ping this issue to point out there's a PR here https://github.com/dask/dask/pull/11199 that has the changes needed to drop support for `pandas < 2`
