### ISSUE TITLE
dask-expr: DataFrame.map_partitions no longer takes a `token` keyword

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/dask#10975]
**Describe the issue**:

The `map_partitions` method of the `dd.DataFrame` collection no longer accepts the `token` keyword in the dask-expr version.

It's certainly not a critical keyword (and with dask-expr you could also create a custom expr subclass instead of using `map_partitions` if you want to have more fine grained control, I suppose), but I think keep supporting this could be 1) nice for backward compatibility, and 2) useful inspectability of the eventual graph (just removing the keyword gives a generic "mappartitions" key in the task graph).

**Minimal Complete Verifiable Example**:

```python
import dask
dask.config.set({'dataframe.query-planning': True})

import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": np.arange(100), "b": np.random.randn(100)})
ddf = dd.from_pandas(df, npartitions=2)
ddf2 = ddf.map_partitions(lambda df: df, meta=ddf._meta, token="test")
ddf2.compute()
```

gives

```
...
File [~/scipy/repos/dask-expr/dask_expr/_expr.py:3513](http://localhost:8888/lab/tree/repos/dask-expr/dask_expr/_expr.py#line=3512), in Fused._execute_task(graph, name, *deps)
   3511 for i, dep in enumerate(deps):
   3512     graph["_" + str(i)] = dep
-> 3513 return dask.core.get(graph, name)

File [~/scipy/repos/dask/dask/dataframe/core.py:7387](http://localhost:8888/lab/tree/repos/dask/dask/dataframe/core.py#line=7386), in apply_and_enforce(*args, **kwargs)
   7385 func = kwargs.pop("_func")
   7386 meta = kwargs.pop("_meta")
-> 7387 df = func(*args, **kwargs)
   7388 if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   7389     if not len(df):

TypeError: <lambda>() got an unexpected keyword argument 'token'
```

**Environment**:

- Dask version: 2024.2.1+8.g5abd9daa (dask-expr 0.5.3+6.gdd3c54d)

**Comment by phofl** [comment]
We can add this back in, but we would still change the behaviour slightly if we do this:

currently tokenisation ignores the func if token is given, that's something we would want to change in dask-expr.
