### ISSUE TITLE
dask-expr is now a hard dependency

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#10979]
dask-expr is now a hard dependency of dask[dataframe].
We still need to update

- `distributed/continuous_integration/recipes` (see conda build workflow on distributed, currently failing)
- https://github.com/conda-forge/dask-feedstock
- distributed gpuci failing
- other?

CC @phofl @jrbourbeau 

XREFs
- dask/dask#10967
- dask/dask#10976 
- dask/distributed#8552

**Comment by crusaderky** [comment]
gpuci is failing, I think due to a method that has no docstring in dask-expr:

https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/8511/CUDA_VER=11.8.0,LINUX_VER=ubuntu20.04,PYTHON_VER=3.9,RAPIDS_VER=24.04/testReport/junit/distributed.shuffle.tests/test_shuffle/test_basic_cudf_support/

**Comment by phofl** [comment]
cc @rjzamora

**Comment by rjzamora** [comment]
Thanks for the ping

>I think due to a method that has no docstring in dask-expr

Yes, I should be merging a workaround for this (and many other things) today. It may take a few days for me to get gpuci passing.
