### ISSUE TITLE
importing dask.dataframe changes pandas behaviour in 2024.3.0

### ISSUE THREAD

**Issue by ivirshup** [dask/dask#10996]
**Describe the issue**:

Since the latest update, importing dask.dataframe changes pandas settings so arrays retrieved from a dataframe are no longer writable.

Ideally, importing dask.dataframe would not change the behaviour of `pandas`.

**Minimal Complete Verifiable Example**:

```python
In [1]: import pandas as pd

In [2]: pd.DataFrame({"a": [1,2,3, None]})["a"].to_numpy().flags
Out[2]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [3]: import dask.dataframe as ddf

In [4]: pd.DataFrame({"a": [1,2,3, None]})["a"].to_numpy().flags
Out[4]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

**Anything else we need to know?**:

It looks like this is caused by `dask-expr` doing:

* https://github.com/dask/dask-expr/blob/db20d4b88e1d736bdf099844e73e48c2c1127dbd/dask_expr/__init__.py#L22

Currently the cause of:

* https://github.com/scverse/scanpy/issues/2902

**Environment**:

- Dask version: 2024.3.0
- Python version: 3.12.2
- Operating System: Linux-5.15.0-100-generic-x86_64-with-glibc2.35
- Install method (conda, pip, source): pip

<details>
<summary> session-info </summary>

```python
-----
IPython             8.22.2
dask                2024.3.0
pandas              2.2.1
session_info        1.0.0
-----
asttokens           NA
cloudpickle         3.0.0
cython_runtime      NA
dask_expr           1.0
dateutil            2.9.0.post0
decorator           5.1.1
executing           2.0.1
fsspec              2024.2.0
jedi                0.19.1
numpy               1.26.4
packaging           24.0
parso               0.8.3
pickleshare         0.7.5
prompt_toolkit      3.0.42
pure_eval           0.2.2
pyarrow             15.0.1
pygments            2.17.2
pytz                2024.1
six                 1.16.0
stack_data          0.6.2
tlz                 0.12.1
toolz               0.12.1
traitlets           5.14.1
wcwidth             0.2.13
yaml                6.0.1
-----
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
Linux-5.15.0-100-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-03-12 12:45
```

</details>

**Comment by fjetter** [comment]
This is https://github.com/dask/dask-expr/pull/932

@phofl is this expected when enabling copy on write?

**Comment by fjetter** [comment]
FWIW The setting we're enabling here is something that will be enabled by default (if not enforced) in pandas 3.0 which is soon to be released. I suspect that this is desired behavior and you'll need to create a copy with `to_numpy(copy=True)`

**Comment by ivirshup** [comment]
I agree that we're going to eventually need to support pandas with copy on write.

But:

* I expect we're going to have to support pandas 2 for a while longer (we have optional dependencies and dependents pinning pandas pretty low)
* I think this is an unintuitive side effect of importing dask.dataframe.

**Comment by ivirshup** [comment]
Ran into a deeper issue where numcodecs doesn't like being passed a read-only buffer, so I think we'll end up needing to pin dask for a bit on our end.

* https://github.com/zarr-developers/numcodecs/issues/514

**Comment by fjetter** [comment]
I understand the problem. We'll likely want to continue using COW in dask but I can offer that we put in a toggle to control this, e.g.

```python

import dask
dask.config.set({"dataframe.copy-on-write": False})
import dask.dataframe
```

Would this be a feasible workaround for you?

**Comment by ivirshup** [comment]
> `dask.config.set({"dataframe.copy-on-write": False})`

Would that do something much different than me using `pd.set_option`?

-----

I do think it makes sense that you want to opt-in to this. I was just hoping to be able to address this during the pandas 3.0 release candidate period when our canary would pick it up.

I also don't think we'll need to do any configuration if we can figure out the numcodecs issue, but unfortunately I don't know enough cython to figure out what incantation it wants.

**Comment by fjetter** [comment]
> Would that do something much different than me using pd.set_option?

We want to enable this by default for dask users. The config option would be a way to opt-out of this opinionated choice.

**Comment by ivirshup** [comment]
@phofl, thank you for the pointer! https://github.com/zarr-developers/numcodecs/pull/515

**Comment by phofl** [comment]
No worries, pr looks good and should address those issues.

**Comment by flying-sheep** [comment]
> We want to enable this by default for dask users. The config option would be a way to opt-out of this opinionated choice.

Please reconsider that philosophy. Package-wide settings are intended for users and applications, not for libraries. `import` in Python should be free of side effects.
