### ISSUE TITLE
Dumb code error in the Example code in Dask-SQL Homepage

### ISSUE THREAD

**Issue by tiraldj** [dask/dask#10997]
Easy to fix.  On https://dask-sql.readthedocs.io/en/latest/ in the Example code the last line is 

```
# ...or use it for another computation
result.sum.mean().compute()
```

this throws an error because 'sum' was accidentally left in.

the code should be: 

```
# ...or use it for another computation
result.mean().compute()
```

**Comment by rjzamora** [comment]
Thanks @tiraldj - Would you mind moving this to https://github.com/dask-contrib/dask-sql?

**Comment by tiraldj** [comment]
oh ok will do. sorry for posting in the wrong place

**Comment by jrbourbeau** [comment]
Thanks @tiraldj @rjzamora. Closing in favor of https://github.com/dask-contrib/dask-sql/issues/1315
