### ISSUE TITLE
dask.dataframe.DataFrame.reduction fails on`split_every=False` if query planning is in effect

### ISSUE THREAD

**Issue by cbourjau** [dask/dask#11005]
**Describe the issue**:

This is a follow-up to #11000 - thanks again for the fix! It appears that the now present `dask.dataframe.DataFrame.reduction` changes its behavior if query planning is activated or not.

**Minimal Complete Verifiable Example**:

The following snippet fails:
```python
import dask
import pandas as pd
dask.config.set({'dataframe.query-planning': True})

import dask.dataframe as dd

dd.from_pandas(pd.DataFrame({"a": [1]}), npartitions=1).reduction(chunk=lambda x: x, split_every=False)
```
The error raised reads:

```
ValueError: split_every must be at least 2
```
If query planning is disabled the following snippet executes without raising an exception:
```python
import dask
import pandas as pd
dask.config.set({'dataframe.query-planning': False})

import dask.dataframe as dd

dd.from_pandas(pd.DataFrame({"a": [1]}), npartitions=1).reduction(chunk=lambda x: x, split_every=False)
```

**Anything else we need to know?**:

The [docstring](https://github.com/dask/dask-expr/blob/main/dask_expr/_collection.py#L2014-L2018) describing `split_every` states that this argument is in fact of type `int | None` but it does not make clear how to set it to "false".

**Environment**:

- Dask version: 2024.3.0
- dask-expr version: 1.0.2
- Python version: 3.12.2
- Operating System: MacOS 14.2.1
- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
Sorry about that, put up a pr
