### ISSUE TITLE
as of v2024.3.1, comparing a 1D dask.array.Array to a dask.dataframe.Series fails

### ISSUE THREAD

**Issue by jameslamb** [dask/dask#11006]
**Describe the issue**:

Prior to `dask < 2024.3.0`, it was possible to directly combined a 1-dimensional Dask Array and a Dask Series with operators like `==`, `-`, and `+`, like this:

```python
(d_ser == d_arr).compute()
```

As of `v2024.3.1`, with the switch to `dask-expr`, that instead raises an exception like this:

```text
ValueError: For a 1d array, columns must be a scalar or single element list
```

**Minimal Complete Verifiable Example**:

Consider the following Python code.

```python
import dask.array as da
import dask.dataframe as dd
import pandas as pd

d_series = dd.from_pandas(pd.Series([1.0, 2.0, 3.0, 4.0]), npartitions=1)
d_array = d_series.to_dask_array()

(d_series == d_array).compute()
(d_series - d_array).compute()
(d_series + d_array).compute()
```

In a Python 3.11 environment with `dask==2024.2.1`, `numpy==1.26.4`, and `pandas==2.2.1`, that succeeds.

```python
(d_series == d_array).compute()
# 0    True
# 1    True
# 2    True
# 3    True
# dtype: bool
```

In a Python 3.11 environment with `dask==2024.3.1`, that latest `dask-expr` (1.0.3), and the same `numpy` and `pandas` versions, it fails.

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/dask_expr/_collection.py", line 160, in _wrap_expr_op
    other = from_dask_array(
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dask_expr/_collection.py", line 4730, in from_dask_array
    df = from_dask_array(x, columns=columns, index=index, meta=meta)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/io/io.py", line 433, in from_dask_array
    meta = _meta_from_array(x, columns, index, meta=meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dask/dataframe/io/io.py", line 86, in _meta_from_array
    raise ValueError(
ValueError: For a 1d array, columns must be a scalar or single element list
```

**Anything else we need to know?**:

I've read #10995. I don't believe this issue is already captured elsewhere here or at https://github.com/dask/dask-expr/issues.

I discovered this behavior change because it broke LightGBM's CI: https://github.com/microsoft/LightGBM/issues/6365. It was convenient there to be able to compare two 1-dimensional arrays to each other and not need to care whether one was a dask Array and another was a Dask Series, but if that's a bad practice or no longer supported here, it won't be a huge problem to change it. I don't know if other projects rely on that behavior though.

Note that `pandas` and `numpy` objects can be compared in these ways (as of `pandas==2.2.1` and `numpy==1.26.4`):

```python
import pandas as pd
import numpy as np

ser = pd.Series([1.0, 2.0, 3.0, 4.0])
arr = ser.values

ser == arr
arr == ser
```

**Environment**:

I set these up using the official `python:3.11` container images.

```shell
docker run --rm -it python:3.11 bash
```

Latest `dask`, `numpy`, `pandas`, and `dask-expr`:

```shell
docker run --rm -it python:3.11 bash
pip install \
    'dask==2024.3.1' \
    'distributed==2024.3.1' \
    'dask-expr==1.0.3' \
    'numpy==1.26.4' \
    'pandas==2.2.1'
```

Slightly older `dask` and the newest `dask-expr` that supported it:

```shell
docker run --rm -it python:3.11 bash
pip install \
    'dask==2024.2.1' \
    'distributed==2024.2.1' \
    'dask-expr==0.5.3' \
    'numpy==1.26.4' \
    'pandas==2.2.1'
```

Thanks for your time and consideration.

**Comment by fjetter** [comment]
Thanks for the bug report. This is obviously expected to work. Will have a fix up shortly
