### ISSUE TITLE
dask.dataframe.Series.reduction is not available when using query planning

### ISSUE THREAD

**Issue by cbourjau** [dask/dask#11000]
**Describe the issue**:
The API of `dask.dataframe.Series` is missing the `reduction` method if query planning is enabled. Query planning should not change the public API, though.

**Minimal Complete Verifiable Example**:
Without query planning, the following snippet works as expected
```python
import dask
dask.config.set({"dataframe.query-planning": False})
import dask.dataframe as dd 
dd.Series.reduction
```

However, if query planning is enabled (the new default) the following snippet...
```python
import dask
import dask.dataframe as dd 
dd.Series.reduction
```
raises an `AttributeError`:
```
>>> dd.Series.reduction
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Series' has no attribute 'reduction'
```

Please note that query planning must be disabled before importing `dask.dataframe` for the mitigation to work.

**Environment**:

- Dask version: 2024.3.0
- Python version: 3.11.8
- Operating System: MacOS 14.2.1

- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
Hi, thanks for your report. We removed this intentionally since this was never really meant to be public, could you give a bit more context about what you are using the reduction method for?

**Comment by fjetter** [comment]
For reference, this is an implementation I added in https://github.com/data-engineering-collective/plateau/blob/de3363b6e0799eaf9be8b3feee658a51eac56428/plateau/io/dask/dataframe.py#L354

it's essentially a custom tree reduction to perform a dataset commit.

**Comment by cbourjau** [comment]
> For reference, this is an implementation I added in https://github.com/data-engineering-collective/plateau/blob/de3363b6e0799eaf9be8b3feee658a51eac56428/plateau/io/dask/dataframe.py#L354
> 
> it's essentially a custom tree reduction to perform a dataset commit.

The use of `.reduction` in Plateau is indeed exactly how I stumbled over this issue. Thanks for the context, @fjetter .

**Comment by xhochy** [comment]
Thanks!
