### ISSUE TITLE
Poor scheduling with `flox`, leading to high memory usage and eventual failure

### ISSUE THREAD

**Issue by ivirshup** [dask/dask#11026]
**Describe the issue**:

When performing aggregation with flox, I quickly run out of memory, regardless of the size of a chunk.

It appears that lower nodes (loading data) keep getting run while higher nodes (reduction) sit un-computed.

Opening here as requested in:

* https://github.com/xarray-contrib/flox/issues/346

cc: @dcherian 

**Minimal Complete Verifiable Example**:

```python
import dask.distributed as dd
import dask.array as da
import numpy as np
import flox

cluster = dd.LocalCluster(n_workers=3)
client = dd.Client(cluster)

M, N = 1_000_000, 20_000

# Note that it doesn't seem to matter where X comes from.
# In my real-world use case, it is either generated from `map_blocks` or 
# read directly from a zarr store
X = da.random.normal(size=(M, N), chunks=(5_000, N))
by = np.random.choice(2_000, size=M)

res, codes = flox.groupby_reduce(
    X.T,
    by,
    func="sum",
    fill_value=0,
    method="map-reduce",
    reindex=True,
)

res_comp = res.compute()
```

**Anything else we need to know?**:

<details>
<summary> As an example, here's how my task graph completes if I run `X.sum(axis=0).compute()` </summary>

<img width="500" alt="image" src="https://github.com/dask/dask/assets/8238804/e79e698e-ee21-4732-a856-19c3918492b6">

</details>

<details>
<summary> Whereas `res.compute()` ends up with something more like: </summary>

<img width="500" alt="image" src="https://github.com/dask/dask/assets/8238804/2ba8f855-52db-42d5-81a0-df294161ae1d">

<img width="500" alt="image" src="https://github.com/dask/dask/assets/8238804/cc2d6aec-f134-4c75-a752-e93f5480d576">

</details>

**Environment**:

- Dask version: '2024.3.1'
- Python version: Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
- Operating System: ubuntu (but can replicate on mac)
- Install method (conda, pip, source): pip (in conda env)

**Comment by dcherian** [comment]
I noticed that `random` wasn't detected as a "root task" in the dashboard. That said, @ivirshup this might just be "fixed" if you use a real data source

**Comment by dcherian** [comment]
The input chunk sizes are large here, so that's fixable in theory. I did notice that no root tasks were identified in the dashboard. @ivirshup's comment suggest that this is happening with Zarr inputs as well, not just `random`. Do you see this too?

**Comment by ivirshup** [comment]
@dcherian, adding an intermediate (computed) zarr store like this:

```python
M, N = 500_000, 20_000
N_CATEGORIES = 2_000
SCRATCH = Path("/scratch/tmp")
X_pth = SCRATCH / "X.zarr"

X_orig = da.random.normal(size=(M, N), chunks=(5_000, N))

X_orig.to_zarr(X_pth, overwrite=True, compute=True)
X = da.from_zarr(X_pth)
by = np.random.choice(N_CATEGORIES, size=M)
```

Has the same behaviour for me.

----

@fjetter, what is that task representation?

I'm not familiar enough with dask to know what my expectations should be of the high level graph representations, but some stuff there does seem a little off.

<img width="856" alt="image" src="https://github.com/dask/dask/assets/8238804/792bb341-508d-447b-8a5b-48c663b6db70">

My expectation would be that each groupby-sum chunk would be `(N, N_CATEGORIES)` with a total shape of `(N, N_CATEGORIES * len(X.chunks[1])`. Each partial aggregation layer after that reports chunk sizes to be `(20000, 1)` which also seems wrong. Not sure if this is related though.

**Comment by dcherian** [comment]
> Each partial aggregation layer after that reports chunk sizes to be (20000, 1) which also seems wrong.

Yes this is (intentionally) wrong. 

Number of outputs is more indicative of the reduction tree. You start with 200 chunks -> 50 -> 13 -> 4 -> 1 (The default "split-size" for the tree reduction is 4, so at each stage 4 outputs get combined to 1).

**Comment by ivirshup** [comment]
> Number of outputs is more indicative of the reduction tree. You start with 200 chunks -> 50 -> 13 -> 4 -> 1 (The default "split-size" for the tree reduction is 4, so at each stage 4 outputs get combined to 1).

That makes sense, but I guess I would have expected to have arrays that look like: 

* `shape=(N_FEATURES, N_CATEGORIES, N_REDUCTIONS), chunks=(FEATURE_CHUNKS, N_CATEGORIES, 1)`

Instead of:

* `shape=(N_FEATURES, N_REDUCTIONS), chunks=(FEATURE_CHUNKS, 1)`

Why does the `groupby_sum-chunk` task output an array the same size as the input?

----

FWIW, I tried this with the threading scheduler and it seemed to work great with no memory issues. So definitely speeks to high cost of transfer.

-----

I was under the impression that the scheduler would try to reduce the number of data transfers necessary. Is this explicitly done, or is this just expected to happen due to last-in-first-out task distribution? For instance, if one worker

**Comment by dcherian** [comment]
> Why does the groupby_sum-chunk task output an array the same size as the input?

This is interesting, I don't actually update the sizes. 

@fjetter would the scheduling algorithm work better if the size/shapes were more accurate at the blockwise step?

**Comment by mrocklin** [comment]
As a heads-up, Florian is travelling today and may not be very responsive.

**Comment by dcherian** [comment]
Is there a real dataset, preferably on public cloud, that we can use as an example?

**Comment by ivirshup** [comment]
It would require a little bit of manipulation. Most of the "real data" cases easily available I can think go off the top of my head are in a sparse format in either hdf5 or tiledb. I could share a link with some code to construct the Dask arrays?

**Comment by dcherian** [comment]
> I could share a link with some code to construct the Dask arrays?

I think that would help.

**Comment by ivirshup** [comment]
Here is a gist with examples using both hdf5 and tiledb: https://gist.github.com/ivirshup/eb4f5beb1bb33724b8c11bd0eacf03a6

I was able to get a little further today, and was able to get a few use-cases to actually run, but I am on a larger machine than I was using previously.

**Comment by dcherian** [comment]
This works on my laptop with 32GB RAM with some spilling

```
res, codes = flox.groupby_reduce(
    X_dense.T,
    by,
    func="sum",
    fill_value=0,
)
```

If you turn on logging with
```
import logging
logger = logging.getLogger("flox")
logger.setLevel("DEBUG")
console_handler = logging.StreamHandler()
logger.addHandler(console_handler)
```

you'll see it automatically chooses `method="cohorts"` and it *just* works albeit with spilling. There seems be a densification of each sparse block that could be improved. I'll have to look in to it.

**Comment by dcherian** [comment]
As an aside, why is your adata.X not actually sparse?
```
spblock = adata.X.blocks[0,0].compute()
spblock.nnz / spblock.size # 1.0
```

**Comment by phofl** [comment]
Is there anything that we can help with @dcherian ?

**Comment by dcherian** [comment]
Don't  think so! but see https://github.com/xarray-contrib/flox/issues/396 :)

**Comment by phofl** [comment]
Ah yikes, I missed that ping. This sounds like a shuffle - map_blocks problem now that we have a shuffle. I'll take a closer look though
