### ISSUE TITLE
Does not work with AWS - aiobotocore related error

### ISSUE THREAD

**Issue by openSourcerer9000** [dask/dask#11030]
Still getting [this error](https://github.com/dask/dask/issues/8335) when running cell 5 of this: https://nbviewer.org/github/NOAA-OWP/AORC-jupyter-notebooks/blob/master/jupyter_notebooks/AORC_Zarr_notebook.ipynb

`AttributeError: module 'aiobotocore' has no attribute 'AioSession'`

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

python                    3.9.13
dask '2022.9.2'
s3fs '0.6.0'
aiobotocore '2.5.2'
windows, conda,

**Comment by phofl** [comment]
Can you try upgrading your versions? Especially the dask version and s3fs are very old
