### ISSUE TITLE
Azure Functions using dask raise unexpected "AttributeError: 'function' object has no attribute 'fs'" for io operations

### ISSUE THREAD

**Issue by benrutter** [dask/dask#11037]
**Describe the issue**:

I'm not sure if this is really a "dask" problem, but thought it was worth raising. Dask appears to be incompatible with azure functions (note that from what I can determine the exact same code will not raise a bug in a normal running on linux environment)

**Minimal Complete Verifiable Example**:

Appologies, as since this bug is so context dependent - this example may not be particularly helpful.

Testing some azure functions that make use of dask, I found that IO operations seem to fail with an "AttributeError: 'function' object has no attrribute 'fs'" - this error *only* happens when I'm testing running things in an azure function, and *not* when running locally.

I haven't tracked down the exact line yet (multiple reads of csvs/json etc all seem to throw the same error) - it *seems* to be isolated around io operations, although interestingly doesn't include reading parquet (only reading csv, json etc) - I'm guessing because parquet uses a seperate process with the pyarrow engine.

I think this is the simplest code that would throw the error:

```python
(
    dd.read_csv(filepath, storage_options=storage_options)
    .to_parquet(another_filepath, storage_options=storage_options)
)
```

**Anything else we need to know?**:

This is *only* happening on azure functions from what I can observe, and not running locally.

**Environment**:

- Dask version: 2024.3.1
- Python version: 3.10
- Operating System: Linux / Azure Functions
- Install method (conda, pip, source): pip (I think, although I don't really know what azure functions do under the hood for installation)

**Comment by phofl** [comment]
Can you give us a traceback and the dependencies in your environment?

**Comment by benrutter** [comment]
Just seen this but will do! (I've since pinned back versions so will need to do a little digging to get a full traceback and example)

**Comment by benrutter** [comment]
Been looking into this just now, and can't reproduce the issue, even using the exact same environment (using a lockfile, so pretty sure the dependencies are exactly as they where when I saw the issues).

My best guess is that this didn't ever have anything to do with dask (especially since the same code worked locally with the exact same dependencies and versions) and either:
- something has since changed on azure functions
- the initial error I saw was with something odd that happened during the building of the functions and changing the dask version fixed the bug only because it retriggered the build and not because of any dask code.

Either way - everything seems to be working fine with the same version so I'll put this down to either me or azure functions doing something janky.

**Comment by benrutter** [comment]
Spoke to soon! Managed to hunt one down (although I think the issue is specific to dask 2024.3 and resolve in the latest 2024.4 so might be fine to close anyway. Here's a full traceback:

```
/home/site/wwwroot/yeti/azure_function_helpers.py\", line 20, in wrapped_function\n    return azure_function_to_wrap(*args, **kwargs)\n  File \"/home/site/wwwroot/function_app.py\", line 116, in inspect\n    success, message = data_pipeline.inspect_date_range(\n  File \"/home/site/wwwroot/yeti/pipeline.py\", line 217, in inspect_date_range\n    success, detail = self.inspect_date(\n  File \"/home/site/wwwroot/yeti/pipeline.py\", line 178, in inspect_date\n    success, expectations_df = self._inspect_date(query_date)\n  File \"/home/site/wwwroot/yeti/pipeline.py\", line 91, in _inspect_date\n    success, expectations_df = flexpectations.validate(\n  File \"/home/site/wwwroot/yeti/inspect/flexpectations.py\", line 92, in validate\n    df_to_check = datalake.clipped_ge_dataset(filename, storage_options)\n  File \"/home/site/wwwroot/yeti/datalake.py\", line 423, in clipped_ge_dataset\n    return_df_size = len(return_df)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_collection.py\", line 381, in __len__\n    return new_collection(Len(self)).compute()\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_collection.py\", line 452, in compute\n    out = out.optimize(fuse=fuse)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_collection.py\", line 488, in optimize\n    return new_collection(self.expr.optimize(fuse=fuse))\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_expr.py\", line 93, in optimize\n    return optimize(self, **kwargs)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_expr.py\", line 2877, in optimize\n    return optimize_until(expr, stage)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_expr.py\", line 2828, in optimize_until\n    expr = result.simplify()\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_core.py\", line 371, in simplify\n    new = expr.simplify_once(dependents=dependents, simplified={})\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/_core.py\", line 332, in simplify_once\n    out = child._simplify_up(expr, dependents)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/io/parquet.py\", line 622, in _simplify_up\n    _lengths = self._get_lengths()\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/io/parquet.py\", line 1311, in _get_lengths\n    self._update_length_statistics()\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/io/parquet.py\", line 1333, in _update_length_statistics\n    stat[\"num-rows\"] for stat in _collect_pq_statistics(self)\n  File \"/home/site/wwwroot/.python_packages/lib/site-packages/dask_expr/io/parquet.py\", line 1554, in _collect_pq_statistics\n    fs = expr._io_func.fs\nAttributeError: 'function' object has no attribute 'fs'\n"
```

**Comment by benrutter** [comment]
Ok, so I'm pretty confident that this issue isn't present in dask 2024.4 (probably because updating to that also bumps dask-expr from 1.0.5 to 1.0.11) so this can probably be closed

**Comment by benrutter** [comment]
I've just been digging around the codebase for dask-expr to try and figure the source of this out and this section is a little confusing to me and I think the source of the error? (still in the current codebase)

```
    @property
    def _io_func(self):
        if self._plan["empty"]:
            return identity
        dataset_info = self._dataset_info
        return ParquetFunctionWrapper(
            self.engine,
            dataset_info["fs"],
            dataset_info["base_meta"],
            self.columns,
            dataset_info["index"],
            dataset_info["kwargs"]["dtype_backend"],
            {},  # All kwargs should now be in `common_kwargs`
            self._plan["common_kwargs"],
        )
```

`ParquetFunctionWrapper` has a __call__ method so it can get used as if it's a function. But it also has an `fs` object variable, which gets inspected during `_collect_pq_statistics`.

That's all good, except that when the self._plan["empty"] is truthy, the _io_func is getting set instead just to functoolz identity function. That's an actualy function, so it doesn't have the `fs` method, which is what's causing the bug.

I *think* I was wrong to assume earlier that it was related to azure functions, and was probably because azure functions is somehow shortcutting the turning off of query planning I has.

Will dig some more.

**Comment by phofl** [comment]
Closing here for now, the other issue is most likely the cuplrit
