### ISSUE TITLE
Print functions are wrong inside of map_blocks

### ISSUE THREAD

**Issue by leo333000** [dask/dask#11031]
**Describe the issue**:
Print function does not seem to work inside map_blocks. Meanwhile the map_blocks function performs as expected. (in the example, it returns the same array, as intended)

**Minimal Complete Verifiable Example**:

```python
x = da.random.randint(0,100,size=(10,10,3))

def print_func(m):
    print(m)
    return m

da.map_blocks(print_func,x,chunks=(5,5,3)).compute()

# what the print functions prints out:
>>[]
>>[[[1]]]
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.11.0
- Python version: 3.11.8
- Operating System:
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
The print function also prints out the actual values for me, are they printed for you as well?

The first 2 can be explained with the calculation of the meta. From the docs:

> The meta of the output array, when specified is expected to be an array of the same type and dtype of that returned when calling .compute() on the array returned by this function. When not provided, meta will be inferred by applying the function to a small set of fake data, usually a 0-d array. It’s important to ensure that func can successfully complete computation without raising exceptions when 0-d is passed to it, providing meta will be required otherwise. If the output type is known beforehand (e.g., np.ndarray, cupy.ndarray), an empty array of such type dtype can be passed, for example: meta=np.array((), dtype=np.int32).


So you have to specify meta explicitly if you don't want that to happen
