### ISSUE TITLE
Binder environment is broken

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1104]
Execution of this notebook fails: http://mybinder.org/repo/dask/dask-examples/dask-array-basics.ipynb

**Comment by mrocklin** [comment]
ImportError: No module named dask.array

**Comment by jcrist** [comment]
Fixed by https://github.com/dask/dask-examples/commit/fd49f5b6fbcc202180144969d1db801792e95431 and rebuilding the environment. Closing.
