### ISSUE TITLE
Weird behavior of `rename` 

### ISSUE THREAD

**Issue by dualtob** [dask/dask#11041]
**Describe the issue**:

In our project, we rename columns in pandas DataFrames and dask DataFrames. However, dask DataFrames behave different, if a dict is passed to `rename`, in which a value corresponds to a column name in the DataFrame. Is this intended?

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as ddf
import pandas as pd

columns_ab = {"a": "b"}
columns_bb = {"b": "b"}
columns_ba = {"b": "a"}

df = pd.DataFrame({"a": [15.0]})

# Works as intended
df.rename(columns=columns_ab)["b"]
df.rename(columns=columns_bb)["a"]
df.rename(columns=columns_ba)["a"]

# KeyError in the last line
df_dff = ddf.from_pandas(df.copy())
df_dff.rename(columns=columns_ab)["b"].compute()
df_dff.rename(columns=columns_bb)["a"].compute()
df_dff.rename(columns=columns_ba)["a"].compute() # fails with KeyError: 'a'
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.4.0
- Python version: 3.9.19
- Operating System: MacOS
- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
Thx for the report. The new optimiser messes things up here. I've put up a PR and we will cut a release soon

**Comment by dualtob** [comment]
Perfect, works now, thanks a lot!
