### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#11066]
### Problem description

NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out 3 weeks back ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

### Feature description

To prepare for NumPy 2.0, it might be worthwhile to start testing Dask against NumPy 2 in CI

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share Dask's current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html ). As Dask doesn't have C/C++ usage of NumPy, only the Python changes would be relevant

### Additional information

Maybe Distributed needs similar considerations

Also Dask is both a consumer of NumPy and a producer of its own NumPy-like Array API. So there are two things to consider

1. Adding support for NumPy 2.0 itself with Dask
2. Updating Dask's Array API to more closely match NumPy 2

**Comment by jakirkham** [comment]
Looks like some work occurred in these PRs:

* https://github.com/dask/dask/pull/10549
* https://github.com/dask/dask/pull/10819
* https://github.com/dask/dask/pull/10821
* https://github.com/dask/dask/pull/10831
* https://github.com/dask/dask/pull/10837
* https://github.com/dask/dask/pull/10854

**Comment by jakirkham** [comment]
Running the `dask.array` test suite locally, am seeing a few test failures

```python
FAILED dask/array/tests/test_array_core.py::test_broadcast_arrays - assert () == []
...
FAILED dask/array/tests/test_routines.py::test_atleast_nd_no_args[atleast_3d] - assert () == []
...
FAILED dask/array/tests/test_routines.py::test_atleast_nd_two_args[shape10-shape20-atleast_3d] - AssertionError: assert <class 'tuple'> is <class 'list'>
```

These happen with variations of parameters for each test. So are likely not specific to those parameters

**Comment by jrbourbeau** [comment]
Thanks @jakirkham. We have a nightly upstream CI job that tests against the nightly dev version of `numpy` (and other packages). Unfortunately it's failing right now ([example job](https://github.com/dask/dask/actions/runs/8834599462/job/24256671375)) due to an `ImportError` being raised during the test suite setup.

> Likely need similar fixes as PR ( https://github.com/dask/dask/pull/10929 )

Thanks for tracking that down

**Comment by mrocklin** [comment]
@quasiben maybe this is something your team can help resolve?

**Comment by phofl** [comment]
There are a couple of things that break our upstream ci:

- numexpr 
- numba 
- sparse

None of these work with NumPy 2 and makes the build fail at import time, uninstalling them gets at least the tests running, even though we have some failures

context https://github.com/dask/dask/pull/11086

**Comment by jakirkham** [comment]
Regarding NumPy 2 support for these packages

> * numexpr

Done in [2.10.0]( https://github.com/pydata/numexpr/releases/tag/v2.10.0 ). Please PR: https://github.com/pydata/numexpr/pull/478

> * numba

Support to work with NumPy 2 is tentatively planned for Numba 0.60.0. Please see issue: https://github.com/numba/numba/issues/9544

Semantic support for NumPy 2 is tentatively planed for Numba 0.61.0. Please see issue: https://github.com/numba/numba/issues/9540

> * sparse

This depends on Numba. Looks like no major issues are expected here

**Comment by phofl** [comment]
We'd need numexpr 2.10 on conda forge (only 2.9 is available at the moment)

**Comment by jakirkham** [comment]
> We'd need numexpr 2.10 on conda forge (only 2.9 is available at the moment)

Please see PR: https://github.com/conda-forge/numexpr-feedstock/pull/62

Looks like there are build issues that may need addressing

<hr>

That said, conda-forge is still working on NumPy 2 bringup ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 ). So conda-forge packages built with NumPy 2 support are not yet available

Sounds like that is a requirement here as well?

**Comment by phofl** [comment]
No we are using nightlies for NumPy and a few other packages

**Comment by jakirkham** [comment]
How are those nightlies installed? Pip?

If so, may numexpr can be installed the same way?

**Comment by phofl** [comment]
I care mostly about getting the upstream build running again, we still need a volunteer to fix the tests. Feel free to push to my PR if interested or open a new one on top of it

**Comment by quasiben** [comment]
I started poking at this and it's a little challenging to assemble an environment given many dask dependencies are still at the release candidate stage.  Below is how i got things going:


```
mamba env create -f ./continuous_integration/environment-3.11.yaml
mamba uninstall --force numpy pandas scipy numexpr numba sparse
python -m pip install pandas==2.2.2
pip install --extra-index-url https://pypi.fury.io/arrow-nightlies/ \
    --prefer-binary --pre 'pyarrow==17.*'
conda install -c conda-forge -c conda-forge/label/numpy_rc 'numpy==2.*' --force
python -c 'import numpy;print(numpy.__version__);import pandas;print(pandas.__version__);import pyarrow;print(pyarrow.__version__)'

2.0.0rc1
2.2.2
17.0.0.dev59
```

I started off small with a single test [dask/array/tests/test_array_core.py](https://gist.github.com/quasiben/e0ab0d1088ff0a2ec1ba91144fe333bb) -- only 9 failures!  These seem mostly to do with h5py .  Need to look into h5py numpy 2 support...

```
FAILED dask/array/tests/test_array_core.py::test_asarray_h5py[True-asarray] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_asarray_h5py[True-asanyarray] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_asarray_h5py[False-asarray] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_asarray_h5py[False-asanyarray] - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_h5py_newaxis - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_h5py_tokenize - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
FAILED dask/array/tests/test_array_core.py::test_auto_chunks_h5py - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by jakirkham** [comment]
Thanks Ben! 🙏

What happens if you `pip install h5py`?

**Comment by quasiben** [comment]
h5py tess pass when installed from source

**Comment by jakirkham** [comment]
Looking at [this recent upstream CI log]( https://github.com/dask/dask/actions/runs/9098478113/job/25008760571 ) am not seeing any NumPy 2 failures

Do see a couple upstream Pandas failures

Assuming I'm looking at the right log. Do we think this is now fixed?

**Comment by jrbourbeau** [comment]
I've not taken a detailed look at the NumPy 2.0 changelog, but all our tests are passing when run against the latest nightly build of `numpy`. Grepping through the codebase with `git grep -5 NUMPY_GE_200` I also don't see us skipping / xfailing to temporarily get CI passing. Given that I'll close this issue -- folks should feel free to re-open if they're aware of something that's broken.
