### ISSUE TITLE
dd.concat returns empty tuple when axis=1

### ISSUE THREAD

**Issue by mscanlon-exos** [dask/dask#11074]
**Describe the issue**:

When calling dd.concat, if you pass `axis=1` the line  `dasks = [df for df in dfs if isinstance(df, _Frame)]` causes an empty dataframe to be produced because the dataframes passed are instances of `dask_expr._collection.DataFrame` and thus inherit from `dask_expr._collection.FrameBase`

**Minimal Complete Verifiable Example**:

```python
def test_mcve():
    import dask.dataframe as dd
    import pandas as pd


    ddf = dd.from_pandas(pd.DataFrame(data={'foo': [1]}))
    ddf_1 = dd.from_pandas(pd.DataFrame(data={'foo': [2]}))


    concat_ddf = dd.multi.concat([ddf, ddf_1], axis=1)
    assert(isinstance(concat_ddf.compute(), tuple))
    
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.4.2
- Python version: 3.10
- Operating System: Mac OSx
- Install method (conda, pip, source): Pip

**Comment by phofl** [comment]
Why are you using concat from multi? This won’t work with the query optimizer. You should use dd.concat instead

**Comment by mscanlon-exos** [comment]
I thought i did but i guess i didn't. Sorry about that. Thanks for the response

**Comment by phofl** [comment]
Closing this, it's currently not ideal if folks import from internal stuff, but this will fix itself when we remove the legacy implementation.

Please let me know if there is something that you need that you can't access with dd.foo
