### ISSUE TITLE
Rules for automatic reblocking

### ISSUE THREAD

**Issue by shoyer** [dask/dask#111]
xref #58, #60

Automatic reblocking in dask operations will be a super useful follow-on to manual `reblock` functionality. Here are my initial thoughts. For now, I'm going to simplify things by assuming that each array has a fixed blockshape (in practice, we could use the mean of the blockdims along each axis).
1. For operations where one argument has a strictly larger blockshape (e.g., `(100, 100)` and `(1000, 1000)`), we probably want to reblock to the _larger_ blockshape to minimize growth of the scheduling graph.
2. For operations with differently shaped blockshapes (e.g., `(100, 10000)` and `(10000, 100)`) but comparable chunk sizes let's consider using the _geometric mean_ of the blockshape along each dimension. This has the nice property of conserving the size of each chunk, and I suspect it would also minimize total amount of concat/slicing work necessary for the reblocking itself. For this example, this yields a blockshape of `(1000, 1000)`.
3. When given arrays with block shapes `(10000, 1)` and `(1, 10000)`, we probably don't want chunks of shape `(100, 100)` -- that's too small. So shapes calculated from the geometric mean should probably be scaled up to ensure some _minimum size_ (e.g., one million elements, or the largest chunk size currently in the dask).

"Uncut" dimensions deserve special consideration, because they are quite likely to arise in practice, both from array broadcasting (they'll have length 1) and from coercing fresh numpy arrays. But I think they are covered reasonably well by these rules.

For example, consider multiplying arrays with shapes/blockshapes `(100, 1, 1)` and `(1, 1000, 1000)`. With the geometric mean, we get about 10000 chunks of shape `(10, 32, 32)`, which after the scaling adjustment leaves us with about 100 chunks of size `(47, 147, 147)`.

**Comment by shoyer** [comment]
Hmm... I'm not so sure about my geometric mean rule anymore.

Consider an operation between the full array (blockshape `(4, 200, 200)`) and a vector along the time-axis (blockshape `(1464, 1, 1)`) from @mrocklin's [weather data example](http://matthewrocklin.com/blog/work/2015/02/13/Towards-OOC-Slicing-and-Stacking/). My algorithm (see below) would give a chunksize of `(167, 31, 31)`, which would result in making a huge number of rechunks of the big array -- roughly `((3 * 7) * 7 * 7) * (1464 / 4) = 376614` calls to getitem alone. In contrast, the right approach would simply be to rechunk from `(1464, 1, 1)` to (4, 1, 1)`, which is only 365 slice operations.

This seems like the sort of problem that might be favorably formulated as an optimization problem.

```python
from scipy.stats import gmean

def calc_chunksize(*shapes):
    gmean_shape = gmean(shapes, axis=0)
    sizes = np.prod(shapes, axis=1)
    scale_factor = ((np.max(sizes) / np.prod(mean_shape))
                    ** (1.0 / len(shapes[0])))
    return tuple(np.around(gmean_shape * scale_factor).astype(int))
```

**Comment by shoyer** [comment]
Per offline discussion with @mrocklin, we may get a pretty decent solution simply by using the existing blockshapes from the larger of the supplied arrays, or if all arrays have the same size, whichever array has the largest chunk size.

For dask + ndarray operations, in most cases we can simply use chunk dimensions from the dask array.

Cases that use broadcasting to create new dimensions (e.g., multiplying arrays of size `(100, 1, 1)` and `(1, 1000, 1000)`) will require different logic -- possibly something like my geometric mean solution.

**Comment by TomAugspurger** [comment]
How much is this is covered by https://github.com/dask/dask/pull/3507?

**Comment by mrocklin** [comment]
I think that rechunking will have to be done on a per-operation basis.  The rules for tensordot will be different from the rules for fft.  

This is discussed in https://github.com/dask/dask/issues/3587 .  Closing in favor of that issue.
