### ISSUE TITLE
New CI failure showing up in fsspec

### ISSUE THREAD

**Issue by martindurant** [dask/dask#11123]
I am seeing the following consistently in fsspec's downstream CI runs:
```
FAILED ../../../micromamba/envs/test_env/lib/python3.9/site-packages/dask/bytes/tests/test_s3.py::test_parquet_append[pyarrow] - AssertionError: DataFrame are different

DataFrame shape mismatch
[left]:  (2000, 4)
[right]: (1000, 4)
```

**Comment by phofl** [comment]
This should go away if you install dask-expr from main or with the release on Friday

**Comment by martindurant** [comment]
I can wait. When it goes away, I'll close this.

**Comment by jrbourbeau** [comment]
Following up here after the release -- @martindurant is this still an issue, or did things get fixed with the latest release?

**Comment by martindurant** [comment]
Yep; sorry, forgot :|

**Comment by jrbourbeau** [comment]
No worries, thanks for checking!
