### ISSUE TITLE
Release GH action needs to be run twice

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#11134]
We recently added some infrastructure to automatically create a release on GitHub when a release tag is pushed.

The 2024.5.0 release was the first time we were able to try this out. There was an issue where the release wasn't published properly (xref https://github.com/dask/community/issues/379#issuecomment-2097823417) but manually rerunning the workflow fixed things. We released again last Friday and the same thing happened again. I reran the workflow and the release was properly rendered https://github.com/dask/dask/releases/tag/2024.5.1.

Opening an issue to figure out why the release jobs aren't working the first time and need to be rerun. cc @jacobtomlinson 

Also, I noticed that in my GitHub feed there are two copies of the same content. Presumably related to rerunning the workflow (but that's just a guess). 

![Screenshot 2024-05-20 at 10 08 50 AM](https://github.com/dask/dask/assets/11656932/f54870ca-92dc-4f9c-b3a1-306bddb71dbd)

**Comment by jacobtomlinson** [comment]
My hypothesis is that in this project we push a release commit at the same time we push the tag, which I don't typically do in other places I've used this action setup. So the draft action and the publish action are triggered at the same time causing a race condition where the draft ends up winning. Then running the publish again manually corrects things.

If the release gets published, but then reverted to a draft again that might explain why you can see double in your feed as the original publish may be in a cache somewhere.

I'm going to take the naive approach and add a delay to the publish action to see if that fixes things up.
