### ISSUE TITLE
Concat with unknown divisions raises TypeError

### ISSUE THREAD

**Issue by manschoe** [dask/dask#11145]
**Describe the issue**:
When trying to concatenate multiple Dataframes without known divisions with Dask.Dataframe.multi.concat an error is raised as shown below.
![image](https://github.com/dask/dask/assets/80762836/610a213b-ea1f-4237-82fc-6594b7a264ee)

After some digging in the codebase I found some logic causing it:
https://github.com/dask/dask/blob/42ccab530ba01c00b51e89a48acd6bd178e94afb/dask/dataframe/multi.py#L1310
results in an empty list as the dataframes are not of type __Frame_ but of type _dask_expr._collection.DataFrame_

Which then causes
https://github.com/dask/dask/blob/42ccab530ba01c00b51e89a48acd6bd178e94afb/dask/dataframe/multi.py#L1337
to always be True -> Comparing Nones after that
**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
first = dd.from_dict(
    {
        "a": [1, 2, 3],
    },
    npartitions=1
).clear_divisions()
second = dd.from_dict(
    {
        "b": [3, 1, 3],
    },
    npartitions=1,
).clear_divisions()
dd.multi.concat([first,second])
```

**Anything else we need to know?**:
Strange thing is that when doing the following it actually works, so now we're confused why it isn't using the same concat function and what the difference is?
```python
dd.concat([first,second])
```
**Environment**:

- Dask version: 2024.5.1
- Python version: 3.10.11
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
We switched to an implementation that uses a logical query planning layer, which means that we re-implemented all the methods and functions. Anything that is not imported from dask.dataframe as dd won't work anymore, for example using

dd.multi.foo will use the legacy implementation and not the new one.

You can only use stuff that is accessible from dask.dataframe.__init__ directly

**Comment by phofl** [comment]
everything that is not from dd, i.e. dd.multi is legacy dask dataframe and won't work anymore if you aren't very lucky. Just import from top level
