### ISSUE TITLE
'SeriesGroupBy' object has no attribute 'nunique_approx'

### ISSUE THREAD

**Issue by LeilaGold** [dask/dask#11155]
Please add 'nunique_approx' feature for 'SeriesGroupBy' object

**Comment by phofl** [comment]
Groupby doesn't support nunique approx, you can call nunique directly. Can you elaborate a bit why that isn't sufficient?

**Comment by LeilaGold** [comment]
I have a massive dataset. My colleagues and I have tried different ways to elaborate, but we always face the memory error. So we decided to use 'nunique_approx' to reduce the burden on the memory and it turned out that it not supported by Group by.

**Comment by phofl** [comment]
What Dask version are you on? We need more information to give advice here.

**Comment by LeilaGold** [comment]
dask                      2024.5.1              
dask-core                 2023.9.2         
dask-expr                 1.1.1

**Comment by phofl** [comment]
And where is Dask blowing up memory? Normally, we trigger a shuffle for nunique that will make sure that the partition count doesn't change, i.e. we should not allocate to much memory on a single worker.

Can you provide a reproducer that doesn't do what you are trying to do?

**Comment by LeilaGold** [comment]
I will try to build a reproducible example, but it is not clear to me the usefulness of nunique_approx only for Series and not for SeriesGroupBy objects.

**Comment by phofl** [comment]
closing this for now, please ping to reopen when you have an example where this is an issue
