### ISSUE TITLE
from_s3 with a private bucket + take hangs

### ISSUE THREAD

**Issue by updiversity** [dask/dask#1115]
Hi,

not sure if this is an issue.

I am trying to use dask to read a big csv file (10Gb) which is located on a private S3 repo. Strangely, dask hangs when I use the following command:
```
import dask.bag as dbg
bag = dbg.from_s3(s3_path,aws_access_key=aws_access_key,aws_secret_key=aws_secret_key)
bag.take(0)
```
while by just using pandas read_csv, i can instantaneously have access to the row i want, using these lines:
```
import pandas as pd
df = pd.read_csv(s3_path,chunksize=chunksize)
df.get_chunk(1)
```

with 
```
s3_path = "s3://<bucket_name>/<key_name>"
```

any idea what am i doing wrong ?

**Comment by mrocklin** [comment]
Perhaps you need a colon in your path?  `s3://...`

**Comment by updiversity** [comment]
Just updated my issue. This was a typo.

**Comment by mrocklin** [comment]
OK.  It this able to wait for a couple of days?  I'm in the middle of rewriting how we handle S3.

**Comment by updiversity** [comment]
definitively ! there are plenty of workaround :) Looking forward to see the updates

**Comment by mrocklin** [comment]
This should hopefully be resolved if master

    db.read_text('s3://...', **authentication)

**Comment by mrocklin** [comment]
Closing this for now.  Please reopen if the problem continues.
