### ISSUE TITLE
Large memory use when loading file with np.memmap in recent dask versions

### ISSUE THREAD

**Issue by magnunor** [dask/dask#11152]
In the rosettasciio project, we use `dask.array` + `numpy.memmap` to load large files "lazily". In recent versions of `dask`, this does not work very well, as the memory use while doing this operation is very large. Essentially it looks like the full dataset is loaded into memory, and then removed. Previously this did not happen. Issue about this: https://github.com/hyperspy/rosettasciio/issues/266

**Minimal working example**

Link for a zipped version of a datafile (sorry about the size, this was the smallest one I could find): https://filesender.sikt.no/?s=download&token=74dea9bc-d2d8-4bd2-ad9a-66339cec6526

Code to test this:

```python
import numpy as np
import dask.array as da


data_dtype = np.dtype(np.dtype(">u2").name).newbyteorder(">")

merlin_frame_dtype = np.dtype(
    [
        ("header", np.bytes_, 384),
        ("data", data_dtype, (256, 256)),
    ]
)

full_data = np.memmap(
    "default.mib",
    dtype=merlin_frame_dtype,
    mode='r',
)

data = full_data['data']
dask_array = da.from_array(data, chunks=(10000, 256, 256))
```

In `dask` version `2024.1.1`, `2024.1.0` and `2023.10.0`, running this code is (almost) instant and uses (almost) no memory.

In more recent `dask` versions:

- 2024.5.1: About 13 GB memory use, and takes about 1 minute
- 2024.4.0: About 13 GB memory use, and takes about 1 minute
- 2024.3.0: About 13 GB memory use, and takes about 1 minute
- 2024.2.0: About 8 GB memory use, and takes about 10 seconds

Thus, something seems to have changed in `dask=2024.2.0`.

**Anything else we need to know?**:

To replicate the exact install procedure, I made a clean virtual enviroment in a `miniforge` install, then installed the most recent version of dask (`mamba install dask`).

**Environment**:

- Python version: 3.12
- Operating System: Ubuntu 22.04
- Install method (conda, pip, source): in miniforge (conda-forge) via mamba

**Comment by magnunor** [comment]
I also tested this on a Windows computer, with a similar python install: same issue.

- `2024.1.1` (almost) no memory use
- `2024.5.1`: About 13 GB memory use, and takes about 1 minute

**Comment by sivborg** [comment]
I tested this on my Windows computer and I get the same behaviour:
- 2024.5.1 and 2024.4.1: about 21 GB memory use, taking about 30 secs
- 2024.1.1: Instant and no memory use

**Comment by sivborg** [comment]
I ran `git bisect` to locate the bad commit, testing about 80 revisions. And here is the final output:
```
f51fa77f4cbba7a92a54a760da65a4b6e712e4ad is the first bad commit
commit f51fa77f4cbba7a92a54a760da65a4b6e712e4ad
Author: crusaderky <crusaderky@gmail.com>
Date:   Tue Feb 6 17:50:42 2024 +0000

    Make tokenization more deterministic (#10876)

 dask/array/ufunc.py          |   4 +-
 dask/base.py                 | 176 ++++++------
 dask/tests/test_base.py      |  12 +-
 dask/tests/test_delayed.py   |  12 +-
 dask/tests/test_highgraph.py |   6 +-
 dask/tests/test_tokenize.py  | 670 +++++++++++++++++++++++++++----------------
 dask/utils.py                |  18 +-
 7 files changed, 534 insertions(+), 364 deletions(-)
```
The commit is [this one here](https://github.com/dask/dask/commit/f51fa77f4cbba7a92a54a760da65a4b6e712e4ad). There seems to be a lot of changes to the `base.py` file, where the problem could have arisen.

**Comment by mrocklin** [comment]
Thanks for doing that work!

Looking more closely at the commit it looks like some code was removed that used to handle memmap files.  

https://github.com/dask/dask/commit/f51fa77f4cbba7a92a54a760da65a4b6e712e4ad#diff-10422b02c591d63ee295724faa14f7698b4a742c98ba20771c5f70d1a6926d06L1309-L1327

cc @fjetter when he gets back (on PTO currently) or maybe @jrbourbeau if he wants a quick fix

**Comment by magnunor** [comment]
Excellent! Would this be a regression? Or is there some other way of "lazily" loading binary data like with dask?

**Comment by mrocklin** [comment]
Thing used to work.  Thing no longer works.  Sounds like a regression to me 🙂 

I'd say most people doing lazy loading of array data tend to use more established formats like Zarr or HDF today.  memmapped numpy files are rare these days (probably why this issue went unreported for so long).  

If someone was starting a new project today I'd point them to https://zarr.dev/ which seems to be becoming the standard surprisingly quickly across a variety of fields.

**Comment by magnunor** [comment]
For most of our work with large array data, we do use Zarr. The reason for having to work with binary data here, is to load data generated by a type of very fast camera. Thus, the raw data itself comes out as binary files.

For all of my own data processing needs it is `zarr` all the way :)
