### ISSUE TITLE
AssertionError: DataFrame are different with dask 2024.5.1 and python 3.12

### ISSUE THREAD

**Issue by dschwoerer** [dask/dask#11169]
**Describe the issue**:
Some unit tests fails on dask 2024.5.1

```
FAILED ../dataframe/io/tests/test_parquet.py::test_append[pyarrow-True] - AssertionError: DataFrame are different
FAILED ../dataframe/io/tests/test_parquet.py::test_append_wo_index[pyarrow-True] - AssertionError: DataFrame are different
FAILED ../dataframe/io/tests/test_parquet.py::test_append_known_divisions_to_unknown_divisions_works[pyarrow] - AssertionError: DataFrame are different
FAILED ../dataframe/io/tests/test_parquet.py::test_custom_filename_works_with_pyarrow_when_append_is_true - AssertionError: DataFrame are different
= 4 failed, 10489 passed, 1628 skipped, 265 xfailed, 282 xpassed, 131 warnings in 545.24s (0:09:05) =
```

**Minimal Complete Verifiable Example**:

```bash
pytest dask
```

**Anything else we need to know?**:
Full log is [here](https://github.com/user-attachments/files/15801105/builder-live.log.gz)

**Environment**:

- Dask version: 2024.5.1
- Python version: 3.12
- Operating System: fedora
- Install method (conda, pip, source): dnf / source

**Comment by fjetter** [comment]
Can you provide a little more context to what you are doing? 

Our CI is passing fine on python 3.12 and your minimal example is referencing xarray.

**Comment by phofl** [comment]
You installed dask-expr in version 1.1.0, we fixed the bug that causes these tests to fail in version 1.1.1, so upgrading dask-expr will work
