### ISSUE TITLE
Improve documentation for `dd.from_map(...)`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/dask#11167]
There are two main ways to load dataframe partitions via custom functions:
* `dd.from_map`
* `dd.from_delayed`

For some reason, users seem to prefer `dd.from_delayed` over `dd.from_map` even though the latter is much simpler and most often suffices for their use cases. `dd.from_delayed` on the other hand, is more complex and has its implementation has some issues (e.g., https://github.com/dask/dask-expr/issues/1077).

We should improve the documentation for `dd.from_map(...)` and try to funnel most users toward it. `dd.from_delayed(...)` should be depicted as a last resort in case the user's case simply doesn't fit `dd.from_map(...)`.

**Comment by fjetter** [comment]
We should make sure that
- High level examples are not using `from_delayed`
- `from_delayed` documentation itself is pointing to `from_map`
