### ISSUE TITLE
[FEA] Add official mechanism to check if query-planning is enabled in ``dask.dataframe``

### ISSUE THREAD

**Issue by rjzamora** [dask/dask#11175]
The value of the `"dataframe.query-planning"` config currently dictates whether or not `dask.dataframe` will use dask-expr under the hood. However, after `dask.dataframe` is first imported, the value of the `"dataframe.query-planning"` config becomes somewhat useless.

For example, a down-stream library may wish to warn/raise if `dask.dataframe` is already imported with query-planning enabled, but the value of the `"dataframe.query-planning"` config will typically be `None` whether the module was already imported or not.

One way to mitigate this problem is for `dask.dataframe.__init__` to always convert `None` values into `True` (using the config system). This way, a down-stream library (or user) can interpret `None` as a confirmation that the query-planning config can still be modified. An alternative solution is to tell users to inspect `sys.modules` themselves to confirm that `dask.dataframe` is missing.

Whether or not we introduce a simple way for users to check if the query-planning config is already established (i.e. whether `dask.dataframe` was imported), it still seems problematic that the user **can** change the `"query-planning"` config after the fact. This problem is certainly tricky to resolve, but it would be nice if the user could be warned that their config will not be accommodated.

**Comment by fjetter** [comment]
This kind of problem occurs every now and then for various kinds of configs. Typically we are setting some global variable in this case.

**Comment by rjzamora** [comment]
>This kind of problem occurs every now and then for various kinds of configs. Typically we are setting some global variable in this case.

Thanks Florian! Just to clarify: This means you might be in support of having this issue addressed with a global variable that indicates whether or not query-planning is enabled?

**Comment by fjetter** [comment]
Yes, I'm fine with a constant

cc @phofl
