### ISSUE TITLE
cumsum/cumprod issue with empty partitions

### ISSUE THREAD

**Issue by faulaire** [dask/dask#11187]
**Describe the issue**:

cumprod and cumsum aggregations results differs from pandas results when the dataframe contains empty partitions.
All the lines after empty partitions are nan.

If it's an issue, I'm open to perform the PR to fix it.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
from dask.dataframe import from_pandas

df = pd.DataFrame({"x": [1., 2., 3., 4., 5., 6., 7., 8.]}, index=pd.date_range('1995-02-26', periods=8, freq='5min'), dtype=float)
df2 = df.drop(df.between_time("00:10", "00:20").index)

dd = from_pandas(df, npartitions=8)
dd2 = from_pandas(df2, npartitions=1).repartition(dd.divisions)

pd.testing.assert_frame_equal(dd2.cumprod().compute(), df2.cumprod()) # Raise
pd.testing.assert_frame_equal(dd2.cumsum().compute(), df2.cumsum()) # Raise
```

**Environment**:

- Dask version: 2024.6.0
- Dask expr version: 1.1.3
- Python version: 3.12.3
- Operating System: Windows & RHEL 8.4
- Install method (conda, pip, source): pip

**Comment by faulaire** [comment]
Thanks for the quick fix @phofl

Would it be possible to backport the fix in legacy API ?

Thanks

**Comment by phofl** [comment]
I personally don't plan on digging into the graph creation issues there. But happy for someone else to take a stab at it if you are interested?
