### ISSUE TITLE
from_pandas fails when given empty dataframe and chunksize

### ISSUE THREAD

**Issue by benrutter** [dask/dask#11232]
**Describe the issue**:

Attemping to initialise a dask dataframe from an empty pandas dataframe crashes if the dataframe is empty.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": []}).pipe(dd.from_pandas, chunksize=10_000)
# throws TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Edit: (you'll need to compute or try to print out the dataframe to actually see the error)

**Anything else we need to know?**:

It looks like this is being thrown in like 432 of dask_expr/io/io.py:

```python
if nrows == 0:
   locations = [0] * (npartitions + 1)
```
Since npartitions isn't set at this point (not sure why but seems related to the emptyy dataframe) npartitions is None, so adding to 1 throws an error.

**Environment**:

- Dask version: 2024.7.0 (dask_expr 1.1.7)
- Python version: 3.10.11
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by benrutter** [comment]
Yowza that was fast @phofl! I have a specific question but it probably makes more sense to ask on the PR 😁

**Comment by phofl** [comment]
No worries, happy to help
