### ISSUE TITLE
Array slicing is using low level materialized graphs

### ISSUE THREAD

**Issue by fjetter** [dask/dask#11234]
Slicing an array typically falls back to [array.slicing.take](https://github.com/dask/dask/blob/6a04b4ed70934b548d25a793eed90f033a690531/dask/array/slicing.py#L592-L708) which is implemented as a low level graph.

In some workloads (exacerbated by things like https://github.com/pydata/xarray/issues/9220) this can generate hundreds of thousands or even millions of tasks which is incredibly slow to serialize.

This functions was likely never migrated to HLG because part of the slicing operation has to be performed immediately (the plan) to determine the output chunks.

That the slicing is generating two output artifacts is also shown in the new dask-expr implementation https://github.com/dask/dask-expr/blob/25c8d542d301665de9b7878ba2c19dc152035bf5/dask_expr/array/slicing.py#L17-L32 where `slice_array` is called once and the output splits into `chunks` (which we need eagerly) and the materialized graph which should be only calculated once needed.

This also means that the problem of premature materialization and costly network transfer will not go away by moving to expressions.

Instead, the logic should be split up to handle the plan generation and the graph construction separately.

**Comment by phofl** [comment]
I've added a HLG layer for take here: https://github.com/dask/dask/pull/11256

The task graph that we upload to the scheduler is smaller now, but that's about the only improvement. the scheduler is still pretty busy on a random access take and performance stayed the same. so this is probably not worth the effort for now. We should rather fix random access take conceptually.

**Comment by phofl** [comment]
Closing this one, doesn't really make sense to do at this stage since Low level optimization will force materialisation
