### ISSUE TITLE
`read_sql_table` no longer sets index name in the resulting ddf meta

### ISSUE THREAD

**Issue by Timost** [dask/dask#11239]
**Describe the issue**:

First of all, thank you for dask ! ❤

I'm currently upgrading a code base from dask 2023.05.1 to dask 2024.7.0.

One operation that is performed is an extraction of a MariaDB database to parquet on an object storage.

This is done using `dask.dataframe.read_sql_table(...).to_parquet(...)`

The `read_sql_table` looks like:
```python
dask.dataframe.read_sql_table(
  "my_table",
  con=con,
  index_col="id",
  meta=make_meta(
    {
       "value": "string",
     },
  ),
   npartitions=100,
)
```

With dask 2023.05.1 this used to work but, after upgrading, the `to_parquet` call fails with:

```
KeyError: "None of ['__null_dask_index__'] are in the columns"
````

It took me some time to realize that this was a symptom the index name missing from the meta (used [here](https://github.com/dask/dask/blob/27ce2f8ff16f797aa41f64f2080d57bfbac9e677/dask/dataframe/io/parquet/core.py#L929))

My current fix is to pass the index to the `make_meta` call:

```python
make_meta(
    {
       "value": "string",
     },
     index=pd.Index([], dtype="UInt64", name="id"),
  ),
```

Ideally, I think a warning or an error should be thrown if a passed meta does not contain the `index_col` as the index.

**Minimal Complete Verifiable Example**:

I'm using SQLite for the purpose of the MCVE

```python
import pandas as pd
import dask.dataframe
from dask.dataframe.utils import make_meta
df = pd.DataFrame({'col1': [1,1,3,4, 10], 'col2': [10,11,12,13, 20]}, index = pd.Index([0,1,2,3,10], name='my_index'))
df.to_sql('mcve', 'sqlite:///mcve.sqlite')

ddf = dask.dataframe.read_sql_table(
  'mcve', 
  'sqlite:///mcve.sqlite',
  'my_index',
  meta=make_meta({'col1': 'int', 'col2': 'int'})
)
ddf._meta.index.names

# Out: FrozenList([None]) <<<<< Index name not set

ddf = dask.dataframe.read_sql_table(
  'mcve', 
  'sqlite:///mcve.sqlite', 
  'my_index', 
  meta=make_meta({'col1': 'int', 'col2': 'int'}, 
  index=pd.Index([], dtype='int', name="my_index"))
)

ddf._meta.index.names
# Out: FrozenList(['my_index']) <<<<< Index name properly set
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.7.0
- Python version: 3.11.9
- Operating System: Linux
- Install method (conda, pip, source): pip (poetry)

**Comment by phofl** [comment]
Hey, thanks for your report. I downgraded to the dask version and the index name in meta is not set there either. Can you double check that you indeed have an index name there? The index name not being set would be expected to me based on how you are passing meta to the call

**Comment by phofl** [comment]
Closing this for now, please ping to reopen when you can pinpoint where we still set the index name
