### ISSUE TITLE
'Lock is not yet acquired' using distributed lock

### ISSUE THREAD

**Issue by lhcorralo** [dask/dask#11246]
**Describe the issue:**

When using rioxarray for saving a dask array to geotiff using a distributed client, it fails. The error message says 'Lock is not yet acquired'. It seems to be caused by a bug in Dask's distributed locks.

The original code is based on [this example](https://corteva.github.io/rioxarray/html/examples/dask_read_write.html#Multiple-worker-example)

I have created a synthetic test (see below).

**Minimal Complete Verifiable Example**:

```python
import threading
from time import sleep
from distributed import Client, Lock
from concurrent.futures import ThreadPoolExecutor
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s.%(msecs)03d %(levelname)s: %(threadName)s -> %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
)

class MyLock(Lock):
    def __init__(self, name, client):
        self._name = name
        self._lock = Lock(name=name, client=client)

    def acquire(self):
        logging.info(f'Acquiring {self._name}. Currently locked? {self._lock.locked()}')
        try:
            acquired = self._lock.acquire()
            logging.info(f'Acquired? {acquired} Locked? {self._lock.locked()}')
        except Exception as e:
            logging.error(f'Error acquiring: {e}')
            raise e

    def release(self):
        logging.info(f'Releasing {self._name}. Currently locked? {self._lock.locked()}')
        try:
            released = self._lock.release()
            logging.info(f'Released? {released} Locked? {self._lock.locked()}')
        except Exception as e:
            logging.error(f'Error releasing: {e}')
            raise e

def loop_lock(lock: MyLock, event):
    while not event.is_set():
        lock.acquire()
        sleep(1)
        lock.release()

if __name__ == "__main__":
    n_threads = 8
    client = Client(processes=False, n_workers=1, threads_per_worker=n_threads)
    lock = MyLock("lock", client)
    pool = ThreadPoolExecutor(n_threads, thread_name_prefix='loop_lock')
    event = threading.Event()

    with pool:
        logging.info('Launching threads')
        futures = [pool.submit(loop_lock, lock, event) for _ in range(n_threads)]

        logging.info('sleeping in main thread')
        sleep(20)

        logging.info('Finish test')
        event.set()
        # The program never exits

```
The output messages are

> 2024-07-24 07:57:22.939 INFO: MainThread -> Launching threads
> 2024-07-24 07:57:22.941 INFO: loop_lock_0 -> Acquiring lock. Currently locked? False
> 2024-07-24 07:57:22.943 INFO: loop_lock_0 -> Acquired? True Locked? True
> 2024-07-24 07:57:22.945 INFO: loop_lock_1 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.948 INFO: loop_lock_2 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.954 INFO: loop_lock_3 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.958 INFO: loop_lock_4 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.962 INFO: loop_lock_5 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.968 INFO: loop_lock_6 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:22.971 INFO: MainThread -> sleeping in main thread
> 2024-07-24 07:57:22.972 INFO: loop_lock_7 -> Acquiring lock. Currently locked? True
> 2024-07-24 07:57:23.944 INFO: loop_lock_0 -> Releasing lock. Currently locked? True
> 2024-07-24 07:57:23.947 INFO: loop_lock_0 -> Released? None Locked? False
> 2024-07-24 07:57:23.947 INFO: loop_lock_0 -> Acquiring lock. Currently locked? False
> 2024-07-24 07:57:23.948 INFO: loop_lock_1 -> Acquired? True Locked? True
> 2024-07-24 07:57:24.948 INFO: loop_lock_1 -> Releasing lock. Currently locked? True
> 2024-07-24 07:57:24.949 INFO: loop_lock_2 -> Acquired? True Locked? True
> 2024-07-24 07:57:24.950 INFO: loop_lock_1 -> Released? None Locked? False
> 2024-07-24 07:57:24.950 INFO: loop_lock_1 -> Acquiring lock. Currently locked? False
> 2024-07-24 07:57:25.950 INFO: loop_lock_2 -> Releasing lock. Currently locked? False
> 2024-07-24 07:57:25.950 ERROR: loop_lock_2 -> Error releasing: Lock is not yet acquired
> 2024-07-24 07:57:42.972 INFO: MainThread -> Finish test

(I know messages are not extremely useful, I hope the provided code is better).

**Anything else we need to know?**:

Despite being observed using rioxarray, I tracked the issue until [here](https://github.com/corteva/rioxarray/blob/master/rioxarray/raster_writer.py#L301). Because of that, the minimum example is just a buch of acquire/release.

I have tested other Client (well, local cluster) parameters, like processes set to true, or 8 workers with a thread per worker. The results are similar. Changing the sleep time in 'loop_lock' does not help either (tried 0.01, 1 and 5 seconds)

Tests with local schedulers ('single-threaded' and 'threads') and with a lock based on threading.lock (like in [this example](https://corteva.github.io/rioxarray/html/examples/dask_read_write.html#Multithreaded-example)) are working. The problem seems limited to the distributed scheduler.

**Environment**:

- Dask version: 2024.7.0
- rioxarray version: 0.16.0
- Python version: 3.11.4
- Operating System: devcontainer based on mcr.microsoft.com/devcontainers/python:3.11-buster
- Install method (conda, pip, source): pdm (it uses a virtual environment)

**Comment by phofl** [comment]
Hi, thanks for your report. We released a fix for distributed Lock in the last Dask release, could you try on version 2024.07.1?

**Comment by lhcorralo** [comment]
Hi!

I updated to 2024.7.1, and the test is successful :)

Thanks!

**Comment by lhcorralo** [comment]
Hi!

I updated to 2024.7.1, and the test is successful :)

Thanks!
