### ISSUE TITLE
Docstring mismatch of chunksize parameter with actual implementation in multiprocessing `get` scheduler function

### ISSUE THREAD

**Issue by SwamyDev** [dask/dask#11253]
https://github.com/dask/dask/blob/534cd7b7d546657339b260f3274b2d1016bc181a/dask/multiprocessing.py#L180-L185

**Describe the issue**:
As can be seen the docstring indicates a default value of 5 at line 182, whereas in reality it is set to 6 at line 185.
I'd be happy to quickly fix this with a pull request, but I'd need to know which of those two values is the correct/intended one.

This is really a minor thing, however, for months one of my CI builds ran out of memory, and for the live of me I couldn't figure out what changed. Well until now, it seems at some point the `chunksize` has been changed from 5 to 6, and since I ran already on the limit of my RAM, that pushed it over the cliff. 

No big deal, I set it to 5 manually now, and everything is again as it should be.
Maybe this clears up some vexing memory issues for other people as well ;).

- Dask version: at least from 2024.2.0 onwards
- Python version: 3.10

**Comment by phofl** [comment]
Thanks for your report. I would recommend updating the docs to point to the correct value.
