### ISSUE TITLE
Incorrect conversion to/from datetime64 with numpy arrays

### ISSUE THREAD

**Issue by ThomWorm** [dask/dask#11279]
**Describe the issue**:
I'm getting some unexpected behavior when working with numpy arrays that should return as datetime64 objects. In the above example, when I set output_dtypes to ``` output_dtypes=[datetime64[ns]``` I'm getting a TypeError: Cannot cast NumPy timedelta64 scalar from metadata [ns] to  according to the rule 'same_kind'.

I have tried many variations of explicitly setting input and output dtypes with no change in the error. 

If I set  ``` output_dtypes=[ ]``` I am able to get a return of float64 values that I can convert after the fact to the expected datetime's. Although conversion after the fact isn't a huge problem, it seems to suggest to me that there is either an underlying issue or I have some misunderstanding with using Dask. 

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import xarray as xr
import dask.array as da

#############################################
#Function
#############################################
def day_cumsum_reaches_threshold_linear(
    degree_days, start_index, start_time_values, threshold
):
    cumsum = np.cumsum(degree_days[start_index:])
    threshold_reached = np.where(cumsum >= threshold)[0]
    if len(threshold_reached) == 0:
        print("error")
        return np.datetime64("NaT", "ns")
    first_reached_index = threshold_reached[0]
    result_date = start_time_values[start_index + first_reached_index]
    return result_date

#############################################
#Input data
#############################################

vday_cumsum_reaches_threshold_linear = np.vectorize(day_cumsum_reaches_threshold_linear)


time = pd.date_range("2000-01-01", periods=50, freq="D").to_numpy(
    dtype="datetime64[ns]"
)
lat = np.linspace(-90, 90, 10)
lon = np.linspace(-180, 180, 10)
degree_days = xr.DataArray(
    da.random.random((10, 10, 50), chunks=(10, 10, -1)),  # No chunking along time
    coords=[lat, lon, time],
    dims=["lat", "lon", "time"],
)
start_dates = xr.DataArray(
    np.random.choice(time[:5], size=(10, 10)), coords=[lat, lon], dims=["lat", "lon"]
)
start_indices = np.array(
    [np.where(degree_days.time.values == d)[0][0] for d in start_dates.values.flatten()]
).reshape(start_dates.shape)
threshold = 15

#############################################
#Apply function
#############################################


result_raw = xr.apply_ufunc(
    day_cumsum_reaches_threshold_linear,
    degree_days,
    start_indices,
    degree_days.time.values.astype("datetime64[ns]"),
    threshold,
    input_core_dims=[["time"], [], ["time"], []],
    output_core_dims=[[]],
    vectorize=True,
    dask="parallelized",
    output_dtypes=[],
)


result_raw.compute()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.7.1
- -Numpy version 1.26.4 -  used because 2.0 is currently incompatible with netCDF4
- Xarray version 2024.6.0
- Python version: 3.12.4
- Operating System: ubuntu 22.04
- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
Hi, thanks for your report.

I do get the same error when I replace 

degree_days

with a NumPy backed xarray, so this is not a Dask bug.
