### ISSUE TITLE
DataFrame object vs string datatype

### ISSUE THREAD

**Issue by FBruzzesi** [dask/dask#11299]
## Description

Dask seems to store objects as strings. I cannot find a way to assess if the underlying data is an actual string or not. 

Consider the following snippet:

```py
import dask.dataframe as dd

class Foo:
    pass
    
data = {
    "a": list("xyz"),
    "b": [[1], [2, 3], [3, 2, 1]],
    "c": [Foo(), Foo, Foo()]
}

df = dd.from_dict(data, npartitions=1)
df.dtypes
```
> a    string[pyarrow]
> b    string[pyarrow]
> c    string[pyarrow]
> dtype: object

and (maybe even worse), if I try running any `.str` namespace method, I get no issue/warning/raise:

```py
df["c"].str.split().compute()
```
Results in 

> 0    [<__main__.Foo, object, at, 0x7fd9a53b75e0>]
> 1                       [<class, '__main__.Foo'>]
> 2    [<__main__.Foo, object, at, 0x7fd9a53b75b0>]
> Name: c, dtype: object

## Pandas counterpart

In pandas land, some tricks can be applied, depending on how certain we want to be that a column is backed by actual strings.

Example:
```py
import pandas as pd

df = pd.DataFrame(data)
isinstance(df["c"].loc[df["c"].first_valid_index()], str)
```
> False

In general I can get a bunch of random indexes and check if they are strings or not.

## Additional info

**Dependencies**

dask==2024.6.2
pandas==2.2.2
pyarrow==17.0.0

**System**

python 3.10
machine: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

**Comment by phofl** [comment]
Dask automatically converts these to string and the mechanism isn't perfect, these issues will go away with pandas 3 though.

For now, you can disable this if needed, see #10139 for more information

**Comment by FBruzzesi** [comment]
Hey @phofl thanks for getting back to me. I understand that it is possible to disable the behavior at source by setting dataframe.convert-string to false.

However, to give you some more context, I am trying to expand the dask support in [narwhals](https://github.com/narwhals-dev/narwhals) and we can't control what the user passes in directly. My question was more in the direction of:

Is there a way to assess what's actually a string and what's not? The same question actually hold for non-arrow backed types, as the pandas "trick" uses a eager computation, I would not know how to perform that in dask. Hence if we get a _object_ dtype, what's the best way to assess if that's actually a string?

**Comment by phofl** [comment]
No, you can not check that unfortunately without looking at the data. We normally use _meta for this, but this will give you strings for object independently what's in the data
