### ISSUE TITLE
`2024.8.0` breaks `sparse` array indexing

### ISSUE THREAD

**Issue by ilan-gold** [dask/dask#11290]
**Describe the issue**:

Previously, one could at least use `dask` for sparse array indexing/getting, even if more complex operations didn't work.  But now, this too has broken, at least in one use-case.

**Minimal Complete Verifiable Example**:
The following works on `<2024.8.0` but breaks otherwise
```python
import dask.array as da
import scipy as sp

X = da.map_blocks(lambda: sp.sparse.random(10, 10, format="csr"), meta=sp.sparse.random(10, 10, format="csr"), chunks=((10, ) * 100, (10, )))

X[[5, 15], :].compute()
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 X[[5, 15],:].compute()

File ~/Projects/Theis/anndata/venv/lib/python3.11/site-packages/dask/base.py:376, in DaskMethodsMixin.compute(self, **kwargs)
    352 def compute(self, **kwargs):
    353     """Compute this dask collection
    354 
    355     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    374     dask.compute
    375     """
--> 376     (result,) = compute(self, traverse=False, **kwargs)
    377     return result

File ~/Projects/Theis/anndata/venv/lib/python3.11/site-packages/dask/base.py:662, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    659     postcomputes.append(x.__dask_postcompute__())
    661 with shorten_traceback():
--> 662     results = schedule(dsk, keys, **kwargs)
    664 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/Projects/Theis/anndata/venv/lib/python3.11/site-packages/dask/array/_shuffle.py:190, in concatenate_arrays(arrs, sorter, axis)
    189 def concatenate_arrays(arrs, sorter, axis):
--> 190     return np.take(np.concatenate(arrs, axis=axis), np.argsort(sorter), axis=axis)

ValueError: zero-dimensional arrays cannot be concatenated
```
**Anything else we need to know?**:
I've noticed that the problem only occurs when indexing across the chunk boundaries, for what it is worth.
**Environment**:

- Dask version: 2024.8.0
- Python version: 3.11
- Operating System: mac
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Thanks for the report. We rewrote indexing because the previous implementation was terrible in most cases. Is there a sparse equivalent to concat these arrays?

**Comment by ilan-gold** [comment]
> Is there a sparse equivalent to concat these arrays?

What do you mean by this?  Equivalent to what?

**Comment by phofl** [comment]
A sparse equivalent for np.concatenate that does not raise for sparse arrays with 0 elements

**Comment by Illviljan** [comment]
For what it's worth, pydata/sparse handles it:

```python
import numpy as np
import sparse as sp
X = sp.random((10, 10), format="csr")
np.concatenate([X, X])
Out[10]: <GCXS: shape=(20, 10), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(np.int64(0),)>
```

```python
import dask.array as da
import sparse as sp
X = da.map_blocks(lambda: sp.random((10, 10), format="csr"), meta=sp.random((10, 10), format="csr"), chunks=((10, ) * 100, (10, )))
X[[5, 15], :].compute()
<GCXS: shape=(2, 10), dtype=float64, nnz=1, fill_value=0.0, compressed_axes=(0,)>
```

**Comment by ilan-gold** [comment]
@Illviljan Thanks, but unfortunately, that's not an option for us.

**Comment by ivirshup** [comment]
@phofl, there isn't a direct equivalent but I think it wouldn't be so bad to wrap the existing concatenation functions into something that looks array-api compliant.

If we make that is there a good overload point here?

**Comment by phofl** [comment]
We could overload yes. I think (haven't looked deeply) that argsort could also be problematic. The main change is:

We are now concatenating and then calling argsort on it

**Comment by ilan-gold** [comment]
@phofl Is there a plan for this?  If you could give a quick outline of what needs to change, I could take it from there?

**Comment by phofl** [comment]
Happy to review a pr that addresses this, haven’t looked much into what needs to change though

**Comment by ilan-gold** [comment]
@phofl Perhaps you could point me to the refactoring PR that you mentioned earlier?  You seem to have some sense that this PR may have caused this issue.

**Comment by phofl** [comment]
I think it's in ``concatenate_arrays`` in ``array._shuffle.py``. Just special Casing would be fine for an initial version

**Comment by ivirshup** [comment]
So, `concatenate` is already overloaded here:

But there's no overload point in the shuffle module however. If we had an overloaded indexer function (instead of `np.take`) that would work here. For instance, it seems like I can get this to work if I define `concatenate_arrays` like:

```python
def concatenate_arrays(arrs, sorter, axis):
    from scipy import sparse
    typ = type(arrs[0])

    concatenate = concatenate_lookup.dispatch(typ)
    if issubclass(typ, sparse.spmatrix):
        idx = np.argsort(sorter[1])
        array = concatenate(arrs, axis=axis)
        if axis == 0:
            return array[idx, :]
        elif axis == 1:
            return array[:, idx]
        else:
            raise ValueError()
    else:
        return np.take(concatenate(arrs, axis=axis), np.argsort(sorter[1]), axis=axis)
```

But it's not very pretty
