### ISSUE TITLE
Import error: TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function

### ISSUE THREAD

**Issue by weiliu620** [dask/dask#1130]
Ubuntu 14.04 LTS 64 bit, python 2.7 with numpy 1.11.0. 

I got an import error 
========= begin  import error =============
`In [7]: import dask.dataframe
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8010029fbbe3> in <module>()
----> 1 import dask.dataframe

/home/weiliu/.local/lib/python2.7/site-packages/dask/dataframe/__init__.py in <module>()
----> 1 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      2                    repartition)
      3 from .io import (read_csv, from_array, from_bcolz, from_array, from_bcolz,
      4                  from_pandas, from_dask_array, from_castra, read_hdf,
      5                  from_imperative)

/home/weiliu/.local/lib/python2.7/site-packages/dask/dataframe/core.py in <module>()
   1232 
   1233 
-> 1234 class Index(Series):
   1235 
   1236     _partition_type = pd.Index

/home/weiliu/.local/lib/python2.7/site-packages/dask/dataframe/core.py in Index()
   1264         return self.drop_duplicates().count()
   1265 
-> 1266     @derived_from(pd.Index)
   1267     def max(self):
   1268         # it doesn't support axis and skipna kwds

/home/weiliu/.local/lib/python2.7/site-packages/dask/utils.pyc in wrapper(method)
    524 
    525             method_args = getargspec(method).args
--> 526             original_args = getargspec(original_method).args
    527 
    528             not_supported = [m for m in original_args if m not in method_args]

/home/weiliu/.local/lib/python2.7/site-packages/dask/compatibility.pyc in getargspec(func)
    188             return _getargspec(func.__init__)
    189         else:
--> 190             return _getargspec(func)
    191 
    192 def skip(func):

/home/weiliu/.local/lib/python2.7/site-packages/dask/compatibility.pyc in _getargspec(func)
     54 
     55     def _getargspec(func):
---> 56         return inspect.getargspec(func)
     57 
     58     if sys.version_info[1] <= 7:

/usr/lib/python2.7/inspect.pyc in getargspec(func)
    814         func = func.im_func
    815     if not isfunction(func):
--> 816         raise TypeError('{!r} is not a Python function'.format(func))
    817     args, varargs, varkw = getargs(func.func_code)
    818     return ArgSpec(args, varargs, varkw, func.func_defaults)

TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function`
=========== end of import error ================

I can provide more information if that helps. (found this error when importing tensorflow, which import dask.dataframe)

**Comment by mrocklin** [comment]
Your version of Pandas is very old.  You should install dask with one of the following ways if you want to use it with Tensorflow:

```
conda install dask
pip install dask[complete]
```

See https://github.com/tensorflow/tensorflow/issues/2045

**Comment by weiliu620** [comment]
Yes, after upgrading pandas, I fixed the error. Thanks!
