### ISSUE TITLE
Expose a blockwise - reshape operation that doesn't guarantee to keep the ordering consistent for downstream libraries

### ISSUE THREAD

**Issue by phofl** [dask/dask#11314]
@dcherian when we chatted you mentioned that Xarray would benefit if we could expose a blockwise reshaping operation that doesn't guarantee the same ordering as the NumPy equivalent. 

The requirement that Xarray would have is that

```
arr = da.random.random((100, 100, 100), chunks=(10, 10, 10))
result = arr.blockwise_reshape(100, 10_000).blockwise_reshape(100, 100, 100)
```

would result in the same array, correct?

This would keep the graph a lot simpler and allow actual blockwise operations if you would transform things back into the original shape anyway.

@dcherian is this what you are looking for?

A side-note: This is something that we should be able to detect automatically if / when we have array-expr 

(more context https://github.com/pydata/xarray/issues/5629#issuecomment-960133879)

**Comment by dcherian** [comment]
Yes, something like that!  TBH I stole the idea from https://github.com/dask/dask/issues/4855

Here's the code I wrote, I had trouble generalizing to `blockwise` for some reason I can't remember.

```python
def reshape_block(arr, output_chunks):
    """
    Blockwise reshape array to match output_chunks

    This method applies a reshape operation blockwise, so it only makes sense if
    you do not care about the order of elements (along reshaped axes) after reshaping.
    The order of elements will depend on the chunking of ``arr``.
    It is substantially more efficient than a usual reshape, which makes sure array elements
    appear in a numpy-like order regardless of chunking.

    Based on https://github.com/dask/dask/issues/4855#issuecomment-497062002
    """

    from itertools import product

    import numpy as np
    from dask.array import Array
    from dask.base import tokenize
    from dask.highlevelgraph import HighLevelGraph

    name = "reshape-block-" + tokenize(arr)
    ichunks = tuple(range(len(chunks_v)) for chunks_v in arr.chunks)
    ochunks = tuple(range(len(chunks_v)) for chunks_v in output_chunks)

    dsk = {
        (name, *ochunk): (np.reshape, (arr.name, *ichunk), oshape)
        for ichunk, ochunk, oshape in zip(
            product(*ichunks), product(*ochunks), product(*output_chunks)
        )
    }

    graph = HighLevelGraph.from_collections(name, dsk, dependencies=[arr])
    res = Array(graph, name, output_chunks, arr.dtype, meta=arr._meta)

    return res
```

**Comment by Illviljan** [comment]
There's been a related PR: #10016

**Comment by dcherian** [comment]
Yes this is right. To undo the transformation we need to pass in extra info; i just passed in the original chunks when I prototyped this.

**Comment by phofl** [comment]
Thx, added the keyword on the PR, so we should get this in for the next release this Friday
