### ISSUE TITLE
Bump mindeps for pyarrow and numpy

### ISSUE THREAD

**Issue by fjetter** [dask/dask#11323]
In https://github.com/dask/dask/pull/11320 I encountered problems with the old pyarrow versions. While there is no strict support window like [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) I think a year long support window is generous and shouldn't hurt much.

Therefore I propose to bump the minimal version from `7` to `13` (I'm also fine with moving more aggressively.

Similarly, we're behind NEP29 when in comes to numpy version support. According to [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) we can pin to 1.24+ which is also a requirement to increase the pyarrow dependency

**Comment by jrbourbeau** [comment]
That sounds reasonable to me, thanks for raising this issue 

> Therefore I propose to bump the minimal version from 7 to 13

Maybe bump to 14.0.1 instead? FWIW we've also had this on `dask.dataframe` import for a while now 

https://github.com/dask/dask/blob/058f1b69ee3115d63046acf60e537d358462a466/dask/dataframe/_pyarrow_compat.py#L12-L26

**Comment by fjetter** [comment]
Turns out that pyarrow is **not** to blame on the other issue. I think we should still move forward with this.

Happy to move to 14.0.X as well. that would get rid of some compat code in p2p

**Comment by phofl** [comment]
PRs were merged in all repositories
