### ISSUE TITLE
Bug: Can't perform a (meaningful) "outer" concatenation with dask-expr on `axis=1`

### ISSUE THREAD

**Issue by benrutter** [dask/dask#11343]
**Describe the issue**: I *think* this is a bug, because the behaviour is inconsistent between dask-expr and "original-dask". But it is for a bit of an edge case that I can't see coming up a whole lot.

Concatenating two dataframes of different length throws an "assertion error" rather than following the previous behaviour of discarding non-matching indexes or null-filling those indexes depending on the "join" keyword. (I don't feel like that's a very clear way of phrasing it, sorry! The example below should help)

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

one = dd.from_dict({"a": [1, 2, 3], "b": [1, 2, 3]}, npartitions=1)
two = dd.from_dict({"c": [1, 2]}, npartitions=1)

dd.concat([one, two], axis=1, join="outer")
# previous result from old versions of dask (i.e. 2024.2)
#    a  b  c
# 0  1  1  1.0
# 1  2  2  2.0
# 2  3  3  NaN

# Now throws an AssertionError

dd.concat([one, two], axis=1, join="inner")
# previous result from old versions of dask (i.e. 2024.2)
#    a  b  c
# 0  1  1  1.0
# 1  2  2  2.0

# now also throws an AssertionError
```

**Anything else we need to know?**:

The error stack makes it has a good hint on where/why this happens `dask_expr/_expr.py` has this line:

`assert arg.divisions == dependencies[0].divisions`

Which in the case of those above two concats, I guess *isn't* the case, either one needs to be null filled, or the other needs to be shortened, or else they won't match up.

**Environment**:

- Dask version: 2024.8.0
- Python version: 3.10.12
- Operating System: Ubuntu (Jammy Jellyfish)
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Sorry about that, that's a bug. Opened a PR to fix.

FYI: You'll only run into this if npartitions=1
