### ISSUE TITLE
Add option to automatically compute chunk sizes in dask

### ISSUE THREAD

**Issue by lithomas1** [dask/dask#11356]
When testing out dask using array API compat in scikit-learn and scipy, one annoyance are the unknown chunk sizes that come as a result from doing boolean indexing and calls to unique.

These cause problems later for scikit-learn and scipy, e.g. when you do boolean indexing with a lazy array or you get the length of a unique call.

(If one were to write code for dask only, we could call ``compute_chunk_sizes`` afterwards to get the shape, but this doesn't work for someone that wants to write array library agnostic code)

To work around this problem, we can add a mode to dask.array, e.g. ``compute_chunks_sizes_on_demand``, where if it is on, and we are in a method that needs chunks to be known, we will call ``compute_chunk_sizes`` for the user, instead of raising the error to tell the user to call ``compute_chunk_sizes``.

Then, in array-api-compat, I think we can set the flag to auto compute chunk sizes when a library requests the array API namespace from array-api-compat, and unset it when the array API namespace gets garbage collected.

This was briefly mentioned in the Python Array API standard (and I believe the PR implementing the Array API standard for dask does this).
https://github.com/dask/community/issues/109

cc @lucascolley

**Comment by phofl** [comment]
We are explicitly moving away from behaviour where Dask automatically calls compute (see https://github.com/dask/dask/issues/11298#issuecomment-2317544179 for more context). I would rather not add any option like this and then have users stumble into it.

Boolean indexing is generally not great for lazy arrays

**Comment by lithomas1** [comment]
Thanks for the context and for the quick reply!

> I would rather not add any option like this and then have users stumble into it.

Would raising a PerformanceWarning when the option is on be a reasonable alternative to this?

It is not so easy to avoid doing calls to ``unique`` or doing a ``getitem`` in user code - and the exact heuristics for determining whether a piece of code would need a ``compute_chunk_sizes`` call is non-trivial (there are some cases I think where dask is able to figure out chunk sizes sometimes)

**Comment by phofl** [comment]
> Would raising a PerformanceWarning when the option is on be a reasonable alternative to this?

We had this in a few pretty egregious cases until 2 releases ago but people didn't know what to do with it which caused very bad performance issues.

>  and the exact heuristics for determining whether a piece of code would need a compute_chunk_sizes call is non-trivial (there are some cases I think where dask is able to figure out chunk sizes sometimes).

Yep that's correct, not every function needs knowledge about the chunk sizes, see sum for example, it doesn't care. Slicing on the other hand does, since it needs the length of the chunks to figure out where a specific index is.

Xarray is dealing with this as well, they tend to avoid boolean masks whenever possible to avoid these issues. Unique is generally something that is not a great idea in a distributed context while it is very cheap in NumPy

**Comment by lithomas1** [comment]
Sorry for the slow reply, and thanks for the response.

I'm happy to close this then if there's nothing to be done here.
