### ISSUE TITLE
Slicing an array on the last chunk of an axis duplicates the number of chunks

### ISSUE THREAD

**Issue by josephnowak** [dask/dask#11376]
**Describe the issue**:
After updating to the version 2024.08.02 of Dask, I'm noticing that slicing a Dask Array on the last axis on the last positions duplicates the number of chunks with certain configurations like the one on the example, is this something expected? from my perspective it should keep the same chunk shape.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da

da.zeros(
    shape=(6, 7),
    chunks=(1, 2)
)[:, 5:]
# The chunks would have the following shape (1, 1)

da.zeros(
    shape=(6, 7),
    chunks=(1, 2)
)[:, [5, 6]]
# The chunks would have the following shape (1, 2)
```

![image](https://github.com/user-attachments/assets/faa06298-e581-4dcb-97ab-9469b3702bc2)

![image](https://github.com/user-attachments/assets/fc8c5dfb-aed7-4ef0-a652-63da06f50ad0)

**Anything else we need to know?**:

**Environment**:

- Dask version: 2024.08.02
- Python version: 3.11
- Operating System: Windows 11
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Hi, thanks for your report.

Are you referring to the ``[:, [5, 6]]`` case?

This behavior is intentional, Dask will now try to roughly keep the input chunk size along that axis, which is 2

**Comment by josephnowak** [comment]
Hi, no I'm referring to the slice case [:, 5:], it should keep the chunks in the same way than [5, 6] right?

**Comment by josephnowak** [comment]
It is just a misunderstood from my side, the slicing chunks has total sense. sorry.
