### ISSUE TITLE
dask.dataframe can't read_csv

### ISSUE THREAD

**Issue by FredaXYu** [dask/dask#11384]
When I try 

```python
import dask.dataframe as dd
ddf = dd.read_csv('random_people.csv')
```
It reports to me: 
`
AttributeError                            Traceback (most recent call last)
d:\Python\Python38\lib\site-packages\dask\backends.py in wrapper(*args, **kwargs)
    134                 try:
--> 135                     return func(*args, **kwargs)
    136                 except Exception as e:
...
    139                         f"method registered to the {self.backend} backend.\n"

**AttributeError: An error occurred while calling the read_csv method registered to the pandas backend.
Original Message: 'BlockManager' object has no attribute 'arrays'**

`

**Environment**:

- Dask version: 2023.5.0
- Python version: 3.8.8
- Operating System: Win10
- Install method (conda, pip, source): pip install dask

**Comment by phofl** [comment]
Thanks for your report. Please upgrade to the newest dask version and see if the error persists. We won’t fix bugs on version this old

**Comment by FredaXYu** [comment]
But I guess for python 3.8.8, the newest version I can download is my current one?

**Comment by hendrikmakait** [comment]
I suggest upgrading your Python version. Dask has stopped supporting Python 3.8 in May 2023 (see https://github.com/dask/community/issues/315) following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).

It's also worth noting that Python 3.8 will reach its end of life around October 2024 (https://devguide.python.org/versions/).

**Comment by phofl** [comment]
Closing this as it seems it's not a problem on newer dask versions. Please ping to reopen if you can reproduce this on a new dask version
