### ISSUE TITLE
pandas & dask metadata mismatch after .unique()

### ISSUE THREAD

**Issue by JoranDox** [dask/dask#11401]
**Describe the issue**:

I suspect I found a bug in .unique() (or something underlying that), where the index metadata from the df where unique is applied on bleeds through on dask level, while pandas (correctly) starts from a fresh index called "index".

**Minimal Complete Verifiable Example**:

```python
test_df = dd.from_pandas(
    pd.DataFrame(
        {
            "viewid": [901, 902, 903, 904],
            "userid": [101, 102, 103, 101],
            "itemid": [201, 202, 201, 203],
        }
    ).set_index("viewid"),
    npartitions=2,
)

# we want the unique users list
test_users = test_df.userid.unique()

# we want to have a mapping of 0..n to the users
test_users.reset_index().head()
# shoddy attempt at inlining the pandas output:
#      	index	userid
#   0	0      	101
#   1	1      	102
#   2	2      	103

# oh no, it's called "index", let's rename it
test_users.reset_index().rename(columns={"index": "userid_encoded"}).head()
# boom:
# ValueError: The columns in the computed data do not match the columns in the provided metadata
#   Extra:   ['index']
#   Missing: ['userid_encoded']

# indeed I can do reset_index 3 times on the test_users before it complains about not being able to add the same column name again, and the columns (with reset_index adding on the left each time) look like this:
test_users.to_frame().reset_index().reset_index().reset_index().columns
# Index(['level_0', 'index', 'viewid', 'userid'], dtype='object')

# note that it looks like pandas and dask disagree, because the error is a metadata mismatch, and this works fine (except I can't do it with my actual big data):
test_users.compute().reset_index().rename(columns={"index": "userid_encoded"}).head()

```
So clearly 'viewid' (the original index of the starting df) is somewhere hidden still in the metadata of the series that results from .unique(), and the metadata in dask does not agree with the metadata in the pandas df underlying it. 

**Anything else we need to know?**:

I tried to confirm this on the binderhub that's linked with the dask examples but the binderhub is not working (https://mybinder.org/v2/gh/dask/dask-examples/main?urlpath=lab) so I didn't really confirm it in other versions.

**Environment**:

- Dask version:  2024.2.1
- Python version:  Python 3.10.11
- Operating System: ubuntu on k8s
- Install method (conda, pip, source): I think pip? it's on a jupyterhub, not entirely sure

**Comment by phofl** [comment]
Can you please try this on a newer dask version? I don't get this error on main

**Comment by phofl** [comment]
Closing this, please ping to reopen if this is a problem on the newest dask version as well
