### ISSUE TITLE
Latest Dask 2024.9.1 and Pandas 2.2.1 not compatible

### ISSUE THREAD

**Issue by gangaTR** [dask/dask#11410]
It seems the latest version of Pandas is not supporting "Int64Index" anymore.

    import dask.dataframe as dd
../../../.venv/lib/python3.9/site-packages/dask/dataframe/__init__.py:2: in <module>
    from .core import (
../../../.venv/lib/python3.9/site-packages/dask/dataframe/core.py:54: in <module>
    from . import methods
../../../.venv/lib/python3.9/site-packages/dask/dataframe/methods.py:8: in <module>
    from .utils import (
../../../.venv/lib/python3.9/site-packages/dask/dataframe/utils.py:374: in <module>
    _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
E   AttributeError: module 'pandas' has no attribute 'Int64Index'

- Dask version: 2024.9.1
- Python version: 3.11.4
- Pandas version: 2.2.1
- Operating System: Mac
- Install method (conda, pip, source): poetry

**Comment by phofl** [comment]
Hi, thanks for your report. Could you double check for dask version? Your versions are saying that you are using python 3.11, but the traceback is from an environment that has python 3.9, which is not supported by dask 2024.09.1

The Int64Index class was removed a long time ago.
