### ISSUE TITLE
Ngrok Error

### ISSUE THREAD

**Issue by matt7salomon** [dask/dask#11413]
I am running dask on my databricks cluster and my organization blocks connections to Ngrok. When I do a merge using dask-cudf, I get an Ngrok_3200 connection error. How can I disable dask connection to Ngrok?

**Comment by phofl** [comment]
cc @dask/gpu

**Comment by pentschev** [comment]
To be clear, I don't think this has anything to do with dask-cudf, but rather [databricks being an ngrok customer itself](https://ngrok.com/customers/databricks). I have no experience with databricks so can't comment on that, perhaps @jacobtomlinson or @rjzamora can comment here too, but generally speaking I don't think this is at all related to GPUs directly and I don't know who from the Dask community could clarify databricks requirements further.

**Comment by matt7salomon** [comment]
I am not sure where it stems from because I dont think the native databricks compute is connecting to ngorks at all. This error only happens when I merge cudf or dask_cudf datasets.

**Comment by jacobtomlinson** [comment]
We don't use ngrok at all in Dask or cudf, so I'm not sure where to direct you other than Databricks.

Also the error you shared in https://github.com/rapidsai/cudf/issues/16992 points directly to a backend Databricks service.

```
com.databricks.rpc.UnexpectedHttpException: Got invalid response: 404 /ERR_NGROK_3200
```
