### ISSUE TITLE
using tweepy to extract data but getting error

### ISSUE THREAD

**Issue by tapl0w** [dask/dask#11417]
i am getting this coroutine error for my code.i need some tweet data for some sentiment analysis and I am unable to get it due to this error.

python
from twikit import Client, TooManyRequests
import time
from datetime import datetime
import csv
from configparser import ConfigParser
from random import randint

MINIMUM_TWEETS = 20
QUERY = 'stock'

config = ConfigParser()
config.read("config.ini")
username = config['X']["username"]
email = config['X']["email"]
password = config ['X']["password"]

# 1. use the login credentials
client =Client(language = "en-US")
# client.login(auth_info_1=username,auth_info_2=email,password=password)
# client.save_cookies("cookies.json")

client.load_cookies('cookies.json')

#get tweets
tweets = client.search_tweet(QUERY, product = 'Top')
for tweet in tweets:
    print(vars(tweets))
    break

 File "d:\VS CODE\Sentiment Analysis using Tweepy\main.py", line 26, in <module>
    for tweet in tweets:
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'Client.search_tweet' was never awaited

- Dask version:
- Python version:3.12
- Operating System: windows 10
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
This doesn't seem to be related to dask, please provide an example that includes Dask or ask on the tweety issue tracker
