### ISSUE TITLE
`array.broadcast_shapes` to return a tuple of `int`, not a tuple of NumPy scalars

### ISSUE THREAD

**Issue by trexfeathers** [dask/dask#11433]
Before NumPy v2, the `repr` of NumPy scalars returned a plain number. This changed in [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html), which changes how the result of `broadcast_shapes()` is printed:

- Before: `(240, 37, 49)`
- After: `(np.int64(240), np.int64(37), np.int64(49))`

There is no functional difference here, but it is much less intuitive to read - especially problematic for documentation/notebooks.

What does everyone think of adding a line into `broadcast_shapes` to ensure that only plain integers are returned? Would this have any unintended consequences? Many thanks.

**Comment by phofl** [comment]
I don't think that we want to deviate from numpy here

**Comment by trexfeathers** [comment]
> I don't think that we want to deviate from numpy here

Thanks!

I realise I should have compared the behaviour before posting, sorry. Anyway, I can now confirm that Dask is deviating from NumPy:

```python
from dask import array as da
import numpy as np

shapes = [(1, 2), (3, 1), (3, 2)]
from_numpy = np.broadcast_shapes(*shapes)
from_dask = da.core.broadcast_shapes(*shapes)

print(from_numpy)
print(from_dask)
```

```
(3, 2)
(np.int64(3), np.int64(2))
```

**Comment by phofl** [comment]
Thanks! The change you are proposing makes sense then

**Comment by trexfeathers** [comment]
I will have a go at a PR
