### ISSUE TITLE
Differences between client.compute and dask.compute

### ISSUE THREAD

**Issue by andonimichael** [dask/dask#11448]
**Describe the issue**:

Currently I am seeing discrepancies between blocking and sync compute calls (only in Jupyter environments). Specifically:

```
dask.compute(my_delayed_function, client=dask_client)
```

runs fine; however

```
dask_client.compute(my_delayed_function)
```

leads to serialization issues (`TypeError: cannot pickle '_asyncio.Task' object`). I realize that [client.compute runs async](https://distributed.dask.org/en/latest/memory.html#difference-with-dask-compute) but it is odd to see one able to serialize my graph and not the other. I see this consistently across different types of local clients all within Jupyter/ipython environments, but cannot replicate in normal python runtimes.

**Minimal Complete Verifiable Example**:

I am still working on an isolated MRE, but Martin Durant encouraged me to open the issue while I am working on one.
 
**Anything else we need to know?**:

I have a suspicion that my particular serialization issues are due to https://github.com/pydantic/pydantic/issues/8232 and not Dask; however, the different handling between compute calls is still odd. I am also a little outdated and will try to upgrade all of my relevant deps.

**Environment**: Jupyter

- Dask version: 2024.6.2
- Python version: 3.11.9
- Operating System: Ubuntu 22.04.5 LTS
- Install method (conda, pip, source): poetry

```
name = "dask"
version = "2024.6.2"

name = "jupyter-client"
version = "8.6.2"

name = "jupyter-core"
version = "5.7.2"

name = "ipython"
version = "8.28.0"

name = "cloudpickle"
version = "2.2.1"
```

**Comment by andonimichael** [comment]
For what it's worth, upgrading to:

```
cloudpickle = "^3.1.0"
dask = "2024.10.0"
pydantic = "^2.9.2"
```

Fixes the serialization issue

**Comment by rjzamora** [comment]
Hi @andonimichael -  Are you still working on a reproducer?

**Side note**: If this indeed a dask issue, the fix will probably need to be in https://github.com/dask/distributed

**Comment by phofl** [comment]
Closing tis for now, please ping to reopen if you have a reproducer
