### ISSUE TITLE
6x Performance regression from dask 2024.8.0 onwards 

### ISSUE THREAD

**Issue by saschahofmann** [dask/dask#11453]
**Describe the issue**:
I am seeing a huge performance regression for certain operations using `dask>=2024.8.0`.  The below example runs over 6 times faster in 2024.7.1 than in 2024.8.0. The only difference between the two environments are the dask and distributed version.
See the timeit output:
`2024.7.1: 151 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
`2024.8.0: 1.05 s ± 39.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

The example is relative complex and is using an [xclim](https://github.com/Ouranosinc/xclim) function that [generates hourly temperatures from daily min and max temperatures](https://github.com/Ouranosinc/xclim/blob/main/xclim/indices/helpers.py#L730). 

I didn't manage to narrow it down further but suspect it has something to do with the hourly resampling.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import numpy as np
import xarray as xr
from xclim.indices.helpers import make_hourly_temperature

times = pd.date_range("2000-01-01", "2010-12-31", name="time")
annual_cycle = np.sin(2 * np.pi * (times.dayofyear.values / 365.25 - 0.28))

base = 10 + 15 * annual_cycle.reshape(-1, 1)
tmin_values = base + 3 * np.random.randn(annual_cycle.size, 3)
tmax_values = base + 10 + 3 * np.random.randn(annual_cycle.size, 3)

ds = xr.Dataset(
    {
        "tasmin": (("time", "location"), tmin_values),
        "tasmax": (("time", "location"), tmax_values),
    },
    {"time": times, "location": ["IA", "IN", "IL"]},
)
ds = ds.assign_coords(lat=("location", [43.2, 40.1, 41.7]))
ds = ds.assign_coords(lat=ds.lat.assign_attrs(units="degrees_north"))
ds["tasmin"] = ds.tasmin.assign_attrs(units="degC")
ds["tasmax"] = ds.tasmax.assign_attrs(units="degC")
ds = ds.chunk(time=360, location=1)
```

```python
%%timeit

make_hourly_temperature(ds.tasmin, ds.tasmax).compute()
```

**Environment**:

- Dask version:2024.7.1/2024.8.0
- Python version: 3.11.6
- Operating System: MacOS
- Install method (conda, pip, source): PDM (pip)

**Comment by phofl** [comment]
Hi,

Is it intentional that you are using xarray backed by numpy until the Chunk command?

**Comment by saschahofmann** [comment]
I just took an example from the xarray tutorial. So the array creation is in numpy but then of course to trigger dask. I need to have a dask array so I chunk. I will try and create a larger array.

**Comment by phofl** [comment]
Closing this for now, please ping to reopen if you have an example with reasonably sized chunks

**Comment by saschahofmann** [comment]
Alright @phofl, I increased DataArray and  chunksize to 3650, 100 or 2.78 MiB and computation time is still ~2x slower in 2024.8 then 2024.7.

```python
times = pd.date_range("2000-01-01", "2050-12-31", name="time")
annual_cycle = np.sin(2 * np.pi * (times.dayofyear.values / 365.25 - 0.28))
locations = np.arange(1000)
base = 10 + 15 * annual_cycle.reshape(-1, 1)
tmin_values = base + 3 * np.random.randn(annual_cycle.size, locations.size)
tmax_values = base + 10 + 3 * np.random.randn(annual_cycle.size, locations.size)

ds = xr.Dataset(
    {
        "tasmin": (("time", "location"), tmin_values),
        "tasmax": (("time", "location"), tmax_values),
    },
    {"time": times, "location": locations},
)
ds = ds.assign_coords(lat=("location", [43.2]*locations.size))
ds = ds.assign_coords(lat=ds.lat.assign_attrs(units="degrees_north"))
ds["tasmin"] = ds.tasmin.assign_attrs(units="degC")
ds["tasmax"] = ds.tasmax.assign_attrs(units="degC")
ds = ds.chunk(time=10*365, location=100)
```

**Comment by phofl** [comment]
You should choose something around 100-200MiB, that’s a good chunksize, 2MiB is still way too small

**Comment by saschahofmann** [comment]
The operation that is taking long is still the same as in the original post so I didn't post it again
```python
%%timeit
make_hourly_temperature(ds.tasmin, ds.tasmax).compute()
```

**Comment by saschahofmann** [comment]
Xarray mentions chunks of a minimal chunksize of a 1M (1000x1000) so that's what I have been aiming so far.
In fact, if I change the chunks to something like 10*365 and 1000, I am getting a warning
```python
PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]
 ```
in 2024.7.1.


I am also quite surprised that, so much chunk optimisation is necessary to get good results on a minimal example? Would it make sense to raise a warning for small chunks. Since to me it came as quite a (hard to trace) surprise when my tests started taking much longer after I updated my environments.

**Comment by saschahofmann** [comment]
I assume its this change that leads to the regression for chunks that are "too small" ?
https://docs.dask.org/en/stable/changelog.html#improve-scheduling-efficiency-for-xarray-groupby-reduce-patterns

**Comment by phofl** [comment]
The change is this one: https://docs.dask.org/en/stable/changelog.html#improve-efficiency-and-performance-of-slicing-with-positional-indexers

previously, your example created large chunks with small inputs, which is pretty bad since it's not something you can predict. Now, you get input chunk size = output chunk size. Small input chunks will lead to small output chunks, hurting performance. 

The default chunk size behind auto is 128MiB, if you use that you should be good,

The warning is now gone since the algorithm behaves better naturally, so no warning needed anymore

**Comment by saschahofmann** [comment]
So if upsample like in this case where I go from daily to hourly, the chunk size stays the same?

**Comment by phofl** [comment]
Yes correct

saschahofmann ***@***.***> schrieb am Mi. 6. Nov. 2024 um
15:45:

**Comment by saschahofmann** [comment]
Ok cool. I will try and see whether I can fix the slowness in my "real world" example and report back

**Comment by phofl** [comment]
Great, I’d recommend aiming for 100MiB chunks or using auto and see how this performs
