### ISSUE TITLE
map_partitions get error using read_csv read a list of files. But normal when read one file each time.

### ISSUE THREAD

**Issue by lyzf** [dask/dask#11452]
**Describe the issue**:
in version 1, I read a list of csv about 4 files,  log shows map_partition get error.
in version 2, I read one csv each time, things go well.
I don't know why, It seems very weird.
**************************************************
logs:
2024-10-22 01:51:09,227 - distributed.worker - WARNING - Compute Failed
Key:       ('ddf_translatetomgrsid-890789823657ff087d3ebcc0c24eee4c', 24)
Function:  subgraph_callable-4d637d84-6d49-4471-ae2e-153f5c17
kwargs:    {}
Exception: 'MGRSError(\'Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error \')'

Traceback (most recent call last):
  File "/app/mydask10_9addchangsuo/finderrordatadask1022_2.py", line 218, in <module>
    ddf = ddf.set_index('GRID_ID_50')
  File "/usr/local/lib/python3.9/site-packages/dask/dataframe/core.py", line 5435, in set_index
    return set_index(
  File "/usr/local/lib/python3.9/site-packages/dask/dataframe/shuffle.py", line 242, in set_index
    divisions, mins, maxes, presorted = _calculate_divisions(
  File "/usr/local/lib/python3.9/site-packages/dask/dataframe/shuffle.py", line 54, in _calculate_divisions
    divisions, sizes, mins, maxes = compute(divisions, sizes, mins, maxes)
  File "/usr/local/lib/python3.9/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/app/mydask10_9addchangsuo/finderrordatadask1022_2.py", line 59, in ddf_translatetomgrsid
    return df.apply(lambda row: tomgrsid(row['LAT'], row['LON'], preci), axis=1)
  File "/app/mydask10_9addchangsuo/finderrordatadask1022_2.py", line 59, in <lambda>
    return df.apply(lambda row: tomgrsid(row['LAT'], row['LON'], preci), axis=1)
  File "/app/mydask10_9addchangsuo/finderrordatadask1022_2.py", line 39, in tomgrsid
    originmgrs = m.toMGRS(lat, lon)
  File "/usr/local/lib/python3.9/site-packages/mgrs/__init__.py", line 90, in toMGRS
    core.rt.Convert_Geodetic_To_MGRS(lat, lon, MGRSPrecision, p)
  File "/usr/local/lib/python3.9/site-packages/mgrs/core.py", line 209, in check_error
    raise MGRSError(msg)
mgrs.core.MGRSError: Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error
**************************************************
I use try except to enclose tomgrsid function, to see where data can't transform, the log seems data is normal, and I manually transform lat and lon to mgrs is ok.
**************************************************
28.124998 112.890724 200 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error
**************************************************

above all, I think there is no issue with tomgrsid function.  First I manually transform is ok, second when process file one by one ,it is ok too. But it gets error when processing a list of files.
I don't know why ? maybe dask partition data , transfer data having error?
It is very weird, seems magic.

**Minimal Complete Verifiable Example**:

```python
version 1:
ddf = dd.read_csv(files,usecols = list(DTYPES_MAPPING.keys()),dtype = DTYPES_MAPPING)
ddf['GRID_ID_50'] = ddf.map_partitions(ddf_translatetomgrsid, preci= 50, meta=('grid_id', 'string'))
ddf['GRID_ID_200'] = ddf.map_partitions(ddf_translatetomgrsid, preci = 200, meta=('grid_id', 'string'))
ddf = ddf.set_index('GRID_ID_50')
ddf.to_parquet(parquetdir, engine='pyarrow')

version 2:
for file in files:
    ddf = dd.read_csv(file,usecols = list(DTYPES_MAPPING.keys()),dtype = DTYPES_MAPPING)
    ddf['GRID_ID_50'] = ddf.map_partitions(ddf_translatetomgrsid, preci= 50, meta=('grid_id', 'string'))
    ddf['GRID_ID_200'] = ddf.map_partitions(ddf_translatetomgrsid, preci = 200, meta=('grid_id', 'string'))
    ddf = ddf.set_index('GRID_ID_50')
    ddf.to_parquet(parquetdir, engine='pyarrow')
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.11.0
- Python version: 3.9.18
- Operating System:linux
- Install method (conda, pip, source):pip

**Comment by lyzf** [comment]
try except, I using as follows, and the logs show lat and lon data is very normal. I manually pass them to tomgrsid is normal too.
seems very weird?  
```
def ddf_translatetomgrsid(df, preci):
    return df.apply(translatetomgrsid, args=(preci,), axis=1)

def translatetomgrsid(row, preci):
    try :
        mgrsid = tomgrsid(float(row['LAT']), float(row['LON']), preci)
    
    except Exception as e:  
        print("**********************")
        # print(row)
        print(row['LAT'], row['LON'], preci, type(row['LAT']) , type(row['LON']), type(preci))
        print(e)
        return 'error'
    return mgrsid
```

**********************
28.497234 109.193153 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
29.520668 106.515289 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
29.345648 105.939818 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
30271.000063 114.263474 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Latitude Error 
**********************
30271.000063 114.263474 200 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Latitude Error 
**********************
31.400867 109.623923 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
29.041032 106.655805 200 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
31.329905 109.60181 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
31.027157 109.459736 200 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error 
**********************
29.543842 106.582522 50 <class 'float'> <class 'float'> <class 'int'>
Error in "Convert_Geodetic_To_MGRS": MGRS Errors: Easting Error

**Comment by lyzf** [comment]
> This is something that you will probably have to debug yourself. You can check the dtype in map_partitions and the data to see if it looks like what you expect but the error is raised in your function, not inside of Dask

It's being one week, I still can't figure out why things get weird. So I looking for help here. 
I tesing  code using pandas to read one file each time and do the transformation to map latlon to mgrsid, it seems alright, no error.
and I   using dask to read one file each time and do the transformation to map latlon to mgrsid, it seems alright too.
The problem is arise when I using dask to read a list of files. I don't think there is problem with transfomation function.

**Comment by phofl** [comment]
You can set break points in map_partitions and look at the pandas df that you get there to see if things deviate

**Comment by lyzf** [comment]
> You can set break points in map_partitions and look at the pandas df that you get there to see if things deviate

I forgot to say I using LocalCluster.
```
from dask.distributed import LocalCluster
dask.config.set({"dataframe.convert-string": False})
cluster = LocalCluster(n_workers = 32, memory_limit = None)
client = cluster.get_client()
```
how to debug in localcluster, it is multiprocess. 
I add breakpoint() in code, and it can't succeed to debug.
how to debug in localcluster, is there any advice?

**Comment by phofl** [comment]
Don't use a LocalCluster here and then the debugger will hit the break point, that is the easiest way of getting there. Can you ask these usage questions on dask discourse https://dask.discourse.group? 

Please feel free to ping us if the error ie because of Dask
