### ISSUE TITLE
Add `split_out` parameter to `nunique()`

### ISSUE THREAD

**Issue by eonu** [dask/dask#11476]
The current function signature for `Series.nunique()` is:

https://github.com/dask/dask/blob/9b4bef654be34e51f14f95fbfc62454018986d8d/dask/dataframe/core.py#L4192-L4194

The default value for `split_out` in `drop_duplicates` is set to 1:

https://github.com/dask/dask/blob/9b4bef654be34e51f14f95fbfc62454018986d8d/dask/dataframe/core.py#L960

While for most datasets `drop_duplicates` will reduce the data enough that it can fit into one partition, this isn't always the case. If the deduplicated data doesn't fit into one partition, Dask will run out of memory and crash.

Setting `drop_duplicates(split_out=...)` to some large value, or to the number of partitions in the original series/data-frame can be used to get around this, but since `split_out` is not exposed to the `nunique()` function, `drop_duplicates()` is always being called with `split_out=1`, meaning that `nunique()` can result in Dask running out of memory.

Is it possible to add `split_out` to `nunique()`'s signature and forward it to the `drop_duplicates()` call to fix this?

```python
@derived_from(pd.Series) 
def nunique(self, split_every=None, split_out=1, dropna=True): 
    uniqs = self.drop_duplicates(split_every=split_every, split_out=split_out) 
```

`split_out` is similarly missing for `DataFrame.nunique()`:

https://github.com/dask/dask/blob/9b4bef654be34e51f14f95fbfc62454018986d8d/dask/dataframe/core.py#L6085-L6086

Happy to make these changes if this is sensible.

---

It's interesting to note that `SeriesGroupBy.nunique()` correctly has the `split_out` parameter in its signature. 

https://docs.dask.org/en/latest/generated/dask.dataframe.groupby.SeriesGroupBy.nunique.html

**Comment by phofl** [comment]
Hi,

thanks of your report.

The legacy implementation is already deprecated and will be removed soon. The new implementation is documented [here](https://docs.dask.org/en/stable/dataframe-api.html) (google just doesn't link to it automatically :() and developed [here](https://github.com/dask/dask-expr). It already has these keywords, so you should be good to go :)

**Comment by phofl** [comment]
The defaults are already set to True as well

**Comment by eonu** [comment]
Thanks for the quick response, looks good :)
