### ISSUE TITLE
perf: big slowdown in tpch queries between 2024.10.0 and 2024.11.0

### ISSUE THREAD

**Issue by MarcoGorelli** [dask/dask#11507]
**Describe the issue**:

Noticed in the Narwhals CI

Between https://github.com/narwhals-dev/narwhals/actions/runs/11745034758 and https://github.com/narwhals-dev/narwhals/actions/runs/11756885339, the only differences are:

- 2024.10.0 vs 2024.11.0 (dask)
- 1.1.16 vs 1.1.17 (dask-expr)

and the run went from 2 minutes 15 seconds to over 16 minutes

for now we've removed dask from that ci job

**Comment by phofl** [comment]
Yikes this is pretty bad, thanks for reporting.

What scale were you running on? 1?

**Comment by MarcoGorelli** [comment]
no worries 😄 

.5 https://github.com/narwhals-dev/narwhals/blob/80aad57a3b91b211047936fd75ba1cdd581baaa9/tpch/generate_data.py , we're just running it to check correctness of the outputs against expected results

**Comment by phofl** [comment]
Thanks

The culprit is https://github.com/dask/dask-expr/pull/1159

It looks like it broke column projections, which is kind of surprising (for one that no tests failed and second that this hasn't touched it at all...)

**Comment by phofl** [comment]
Scratch that, the PR is the culprit, but it's not related to column projection

**Comment by phofl** [comment]
Yikes this is bad...

More minimal reproducer:

```
# pdf = pd.DataFrame({"a": [1, 2, 3], "b": 1})
# pdf.to_parquet("fusion-repro.parquet")
import dask.dataframe as dd

df = dd.read_parquet("fusion-repro.parquet")
df = df[df.a > 1]
df.sum().compute()
```

Use the first 2 lines to create a sample parquet file.

What is happening?

Previously, blockwise fusion for DataFrames just generated a flat dictionary that was executed.

Now, each fused task is represented by the task spec, which is basically a tree. Each leaf node in this example is a task reading from parquet. We aren't doing anything to deduplicate these things, which means that we are reading from parquet as many times as we have leaf nodes. You will hit the ``__call__`` from ``ParquetFunctionWrapper`` twice in this example (or 12 times in q1 of the tpch queries...)

**Comment by phofl** [comment]
@MarcoGorelli this should solve your runtime issues in CI as well
