### ISSUE TITLE
dask.array.full produces read-only arrays when computed

### ISSUE THREAD

**Issue by fbunt** [dask/dask#11531]
**Describe the issue**:

`dask.array`'s functions for creating single-value arrays such as `full`, `zeros`, `ones`, `full_like`, `zeros_like`, and `ones_like` all produce read-only numpy arrays when computed. In order to get a result that can be written to, I have to copy the entire result or use `map_blocks` to map `np.copy` onto each chunk.

**Minimal Complete Verifiable Example**:

```python
>>> import dask.array as da
>>> import numpy as np

>>> a = da.full(9, 0)
>>> ac = a.compute()
>>> print(ac.flags)
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

>>> ac[0] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: assignment destination is read-only
```

My current workaround is to map a copy operation onto the chunks:

```python
>>> a = da.full(9, 0).map_blocks(np.copy)
>>> ac = a.compute()
>>> print(ac.flags)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

>>> ac[0] = 1
>>>
```

**Anything else we need to know?**:

This may be related to #6520.

**Environment**:

- Dask version: 2024.11.2
- Python version: 3.12.7
- Operating System: Fedora 40
- Install method (conda, pip, source): conda

**Comment by phofl** [comment]
This is interesting, probably because of the tricks we use to make the initial creation as easy as possible, but not sure. Will have to look into that a bit

You can just do a.compute().copy() if that's simpler for you

**Comment by phofl** [comment]
Ok this only happens because your dask array has a single chunk, that problem disappears if you have more than one, so I am inclined to close this because we definitely don't want to introduce complexity for cases where NumPy is better suited

```
import dask.array as da
a = da.full(9, 0, chunks=(3, ))
ac = a.compute()
print(ac.flags)
```

This will be writeable

**Comment by fbunt** [comment]
Oh interesting. Thanks for looking at this and figuring that out. I'm fine with closing.

**Comment by fbunt** [comment]
Hmm is there an easy way to handle this for both single and mulit-chunk arrays without having to check for npartitions==1? I'm running into this error while writing tests that use smaller arrays. It is annoying to have to check if the number of chunks is 1.

**Comment by fbunt** [comment]
Got it. Thanks. I'll go ahead and close this.
