### ISSUE TITLE
bug in dask.array.reshape_blockwise

### ISSUE THREAD

**Issue by dcherian** [dask/dask#11540]
**Minimal Complete Verifiable Example**:

```python
import dask.array

reshape_blockwise(dask.array.ones((3,)), shape=(3,), chunks=((3,),))
```
```
ValueError: Setting chunks is not allowed when reducing the number of dimensions.
```

cc @phofl

**Comment by dcherian** [comment]
Yes, https://github.com/pydata/xarray/pull/9800/files, but I worked around it by only using `reshape_blockwise` with >=2D arrays.

xref https://github.com/pydata/xarray/issues/9425

**Comment by phofl** [comment]
I am a bit confused (sorry for being slow here), but the reshape_blockwise would be a no-op in the case you posted, correct? You don't expect us to do anything here?

**Comment by dcherian** [comment]
Yes correct. it was a no-op.
