### ISSUE TITLE
Consider scattering data ahead of time and using futures.

### ISSUE THREAD

**Issue by robertzeibich** [dask/dask#11562]
I am using pyscenic and getting the following warning:

```
UserWarning: Sending large graph of size 11.52 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
```

Is that something that will massively slow down the runtime and is there a way to fix this?

I tried starting a scheduler and worker, however, that did not resolve the warning. Looks even worse than before. 
[slurm-41038663_9_pysenic_ALL.txt](https://github.com/user-attachments/files/17892796/slurm-41038663_9_pysenic_ALL.txt)

Any suggestions?

**Comment by loelj** [comment]
Has the issue been resolved? How was it resolved?
