### ISSUE TITLE
chained ufuncs seem not to call any graph optimization

### ISSUE THREAD

**Issue by louisletoumelin** [dask/dask#11583]
From my understanding of dask arrays, there are several ways to chain mathematical operations, including ufuncs and `map_blocks`.

Timing these operations yields the following results:

### 1. ufuncs:

**Without 'manual' graph optimization**

```python
import dask.array as da
array = da.random.random((10, 10), chunks=(5, 5))
# simulate a deep graph
for _ in range(200):
    array = da.abs(da.exp(da.sin(array)))

%timeit array.compute(optimize_graph=True)
```

> 433 ms ± 4.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**With 'manual' graph optimization**

```python
import dask
import dask.array as da
array = da.random.random((10, 10), chunks=(5, 5))
# simulate a deep graph
for _ in range(200):
    array = da.abs(da.exp(da.sin(array)))
array, = dask.optimize(array)

%timeit array.compute(optimize_graph=True)
```

> 4.73 ms ± 99.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### 2. `map_blocks`

**Without 'manual' graph optimization**

```python
import dask.array as da
import numpy as np
def f(array):
    return np.abs(np.exp(np.sin(array)))
array = da.random.random((10, 10), chunks=(5, 5))
# simulate a deep graph
for _ in range(200):
    array = da.map_blocks(f, array)

%timeit array.compute(optimize_graph=True)
```

> 55.2 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**With 'manual' graph optimization**

```python
import dask.array as da
import numpy as np
def f(array):
    return np.abs(np.exp(np.sin(array)))
array = da.random.random((10, 10), chunks=(5, 5))
# simulate a deep graph
for _ in range(200):
    array = da.map_blocks(f, array)
array, = dask.optimize(array)

%timeit array.compute(optimize_graph=True)
```

> 3.9 ms ± 610 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Summarize:**

1. Not calling manually `dask.optimize` results in slower computation time when chaining ufuncs and when using `map_blocks`. Based on my understanding of the [documentation](https://docs.dask.org/en/stable/optimize.html), I thought these optimizations for Dask arrays should be handled automatically.

> In most cases, users won’t need to interact with these functions directly, as specialized subsets of these transforms are done automatically in the Dask collections (dask.array, dask.bag, and dask.dataframe).

2. `map_blocks` appears to be faster than ufuncs, notably when the graph is not manually optimized.

From my understanding of the [documentation](https://docs.dask.org/en/stable/array-best-practices.html#build-your-own-operations), `map_blocks` should be called when dask ufuncs are not available, suggesting to use ufuncs otherwise. I’m a bit confused about the best approach for my real-world use case (large computation graph, >100 chained mathematical operations):

Should I prioritize `map_blocks`, or rely on Dask ufuncs? Are there situations where the recommendation for ufuncs might not apply?

This issue is [discussed](https://dask.discourse.group/t/map-blocks-vs-dask-ufuncs/3723) on the dask forum.

Thanks for your help,

**Environment**:

- Dask version: '2024.5.2'
- Python version: '3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]'
- Operating System: Ubuntu

**Comment by phofl** [comment]
Thanks for your report.

The numbers here give of the wrong impression a bit unfortunately. Your ufunc graph is larger since you add 3 operations per iteration. This results in a longer runtime for the graph optimization, not the actual execution. If you profile the optimise call, you should see that the difference is roughly your difference in computation time. The actual execution after the optimization will then be equivalent.

The good news here is, that the optimization time is constant here, so you get the same runtime for the optimization for a 1GB and a 10TB array, this is just a constant factor that you have to pay

I am closing this for now since there is not much we can do. I wouldn't worry too much about the optimization time in this case.
