### ISSUE TITLE
dask.dataframe not preserving index dtype

### ISSUE THREAD

**Issue by dcherian** [dask/dask#11584]
**Describe the issue**:
```python
df = pd.DataFrame({"a": x, "b": y}, index=pd.Index(t, name="t"))
expected = dd.from_pandas(df, chunksize=4)
pd.testing.assert_frame_equal(df, expected.compute())
```

```

*** AssertionError: DataFrame.index are different

Attribute "dtype" are different
[left]:  object
[right]: string[pyarrow]
```

**Environment**:

- Dask version: 2024.12.0
- Python version: ...
- Operating System: ...
- Install method (conda, pip, source): ...

**Comment by phofl** [comment]
That's expected, the convert string option converts object to strings, you can turn this off if needed.

pandas 3 will behave equivalently, until then the only method of ensuring equality is to turn the option off
see https://github.com/dask/dask/issues/10139
