### ISSUE TITLE
`NestedContainer.to_container` method gets tracked individually per NestedContainer object

### ISSUE THREAD

**Issue by hendrikmakait** [dask/dask#11599]
Looking into https://github.com/dask/distributed/issues/8958, I've noticed that for each `NestedContainer` object, its bound `to_container` method is tracked individually by the GC. This accounts for ~500k of 9MM objects in my workload. It would probably be better to stop tracking these individually.

**Comment by fjetter** [comment]
On top, that is very likely a self referencing cycle so breaking this will benefit GC in more than one way
