### ISSUE TITLE
consolidate testing utilities

### ISSUE THREAD

**Issue by cowlicks** [dask/dask#116]
The same `eq` is redifined and used for testing dask arrays in a bunch of separate modules. We should put it in its own module of testing utilities.
```bash
$ grep -ri "def eq" .
./array/tests/test_creation.py:def eq(a, b):
./array/tests/test_ghost.py:def eq(a, b):
./array/tests/test_array_core.py:def eq(a, b):
./array/tests/test_into_array.py:def eq(a, b):
./array/tests/test_percentiles.py:def eq(a, b):
./array/tests/test_chunk.py:def eq(a, b):
./array/tests/test_reductions.py:def eq(a, b):
./array/tests/test_blaze.py:def eq(a, b):
./frame/tests/test_frame.py:def eq(a, b):
```

**Comment by mrocklin** [comment]
Note that these eqs are, in some cases, slightly different.  The dataframe
eq is quite different.

**Comment by mrocklin** [comment]
We now generally have well defined `eq` functions for array and dataframe.  Closing.
