### ISSUE TITLE
Memory is not being cleared

### ISSUE THREAD

**Issue by simonkamronn** [dask/dask#1160]
When repeating a computation on a dask.DataFrame the memory builds up and the computation slows considerably. 

`for _ in range(10):
    %time mag_std = ddf.mag.resample('15Min').std().compute()`

> CPU times: user 3min 21s, sys: 10.6 s, total: 3min 32s
> Wall time: 1min
> CPU times: user 3min 17s, sys: 11.1 s, total: 3min 28s
> Wall time: 59.9 s
> CPU times: user 3min 14s, sys: 10.9 s, total: 3min 25s
> Wall time: 58.8 s
> CPU times: user 3min 6s, sys: 9.98 s, total: 3min 16s
> Wall time: 1min 8s
> CPU times: user 2min 57s, sys: 14.3 s, total: 3min 11s
> Wall time: 2min 2s
> CPU times: user 2min 51s, sys: 13.7 s, total: 3min 5s
> Wall time: 3min 41s
> CPU times: user 2min 44s, sys: 17.5 s, total: 3min 1s
> Wall time: 5min 20s
> CPU times: user 2min 44s, sys: 11.4 s, total: 2min 55s
> Wall time: 5min 37s
> CPU times: user 2min 42s, sys: 11.3 s, total: 2min 53s
> Wall time: 7min 6s
> CPU times: user 2min 50s, sys: 14.8 s, total: 3min 5s
> Wall time: 12min 3s

**Comment by mrocklin** [comment]
Hi @simonkamronn can you provide a reproducible example that we can use to test this?

**Comment by mrocklin** [comment]
Here is a small example on my local machine:

```python
In [1]: import numpy as np
In [2]: import pandas as pd
In [3]: import psutil
In [4]: import dask.dataframe as dd

In [5]: df = pd.DataFrame({'x': np.arange(2000000)}, index=np.arange(2000000).astype('M8[s]'))
In [6]: ddf = dd.from_pandas(df, npartitions=8)
In [7]: for i in range(20):
   ...:     _ = ddf.x.resample('15min').std().compute()
   ...:     print(psutil.Process().memory_percent())
   ...:     import gc; gc.collect()
   ...:     
/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/dask-0.9.0-py3.4.egg/dask/dataframe/tseries/resample.py:54: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).count()
  temp = divs.resample(rule, how='count', closed=closed, label='left')
7.097494976784888
9.655723916451082
10.41409133967979
9.986215363179515
10.204666811097377
10.526980930898402
10.126822906710506
9.77392346021996
10.198401067088064
9.828509772436673
9.718806152748218
10.697961403016903
10.423436856168253
10.201056043363197
9.873219572909896
10.09432599710289
9.608677736855743
9.820863440764294
10.041757466855277
10.906961135395294
```

**Comment by simonkamronn** [comment]
I'm unable to reproduce the issue with synthetic data and it seems to happen only occasionally when using data stored in BColz. If it happens again I will try to find out more.
