### ISSUE TITLE
Possible to use Generalized Ufuncs?

### ISSUE THREAD

**Issue by jakevdp** [dask/dask#1176]
I wonder if it might be possible to make use of NumPy's generalized linear algebra ufuncs in dask.

For example, here's numpy's syntax for solving `M*x=b` for 1000 different (M, b) pairs:

``` python
>>> M = np.random.rand(1000, 10, 10)
>>> b = np.random.rand(1000, 10)
>>> x = np.linalg.solve(M, b)
>>> x.shape
(1000, 10)
```

To confirm this is doing what we expect:

``` python
>>> np.allclose(b, [np.dot(Mi, xi)
                    for (Mi, xi) in zip(M, x)])
True
```

This seems like something that would naturally fit into dask for an appropriately-chunked array, in order to distribute such computations. Is there a way to accomplish this currently, or is it on the road-map?

Thanks!

**Comment by jcrist** [comment]
This is already doable, but doesn't have quite the same clean spelling:

```python
In [1]: import dask.array as da

In [2]: import numpy as np

In [3]: M = da.random.random((1000, 10, 10), chunks=(100, 10, 10))

In [4]: b = da.random.random((1000, 10), chunks=(100, 10))

In [5]: res = np.linalg.solve(M, b)

In [6]: x = da.map_blocks(np.linalg.solve, M, b[:, :, None], chunks=b[:, :, None].shape).squeeze()

In [7]: x.shape
Out[7]: (10000, 10)

In [8]: res.shape
Out[8]: (1000, 10)

In [9]: x
Out[9]: dask.array<squeeze..., shape=(10000, 10), dtype=float64, chunksize=(1000, 10)>

In [10]: np.allclose(x, res)
Out[10]: True
```

We do have `da.linalg.solve`, but it does a blocked solve for large dimension arrays. A code path could be added for the broadcasted solve done here, but I'm unsure if they could easily be mixed (broadcasted and blocked).

**Comment by mrocklin** [comment]
@jakevdp are you suggesting that dask.array functions follow the gufunc practice of parallelizing across extra dimensions?  Or are you suggesting that the numpy gufuncs themselves might be of practical value in dask.array development?  Or perhaps something else entirely?

Also, you might find the [atop](http://dask.readthedocs.io/en/latest/array-api.html#dask.array.core.atop) function of interest.

**Comment by jakevdp** [comment]
Thanks! I'll go ahead and use ``map_blocks`` in the meantime.

**Comment by jakevdp** [comment]
> are you suggesting that dask.array functions follow the gufunc practice of parallelizing across extra dimensions?

Yes – it would be useful to have wrappers for the linalg methods that do this automatically, accepting higher-dimensional inputs with the same syntax as NumPy's generalized ufuncs. I don't think it would introduce ambiguity, and it would be fine to raise appropriate errors if the block-size doesn't lend itself to efficient computation.

**Comment by mrocklin** [comment]
@pitrou this issue may interest you.

**Comment by pitrou** [comment]
Interesting. I thought the np.linalg would implement general broadcasting, but apparently they do not:
```
>>> A = np.random.rand(3,4,4)
>>> B = np.random.rand(3,4)
>>> np.linalg.solve(A, B)

array([[ 1.69554477, -2.38334658,  1.4370541 , -0.16470639],
       [ 1.04272646,  0.47806603,  1.21867436, -1.94218685],
       [-1.10373245, -0.84127117,  1.64479471,  0.78965016]])
>>> np.linalg.solve(A[0], B[0])
array([ 1.69554477, -2.38334658,  1.4370541 , -0.16470639])
>>> np.linalg.solve(A[0], B)
Traceback (most recent call last):
  File "<ipython-input-10-cfc037f1bd3b>", line 1, in <module>
    np.linalg.solve(A[0], B)
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 384, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 3 is different from 4)

>>> np.linalg.solve(A, B[0])
Traceback (most recent call last):
  File "<ipython-input-11-c54bd8085b43>", line 1, in <module>
    np.linalg.solve(A, B[0])
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 384, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve: Input operand 1 does not have enough dimensions (has 1, gufunc core with signature (m,m),(m,n)->(m,n) requires 2)

```

**Comment by shoyer** [comment]
@pitrou I think that is an issue with how `np.linalg.solve` handles dispatching, not broadcasting. It looks like it effectively has two gufunc signatures, `(m,m),(m)->(m)` and `(m,m),(m,k)->(m,k)`, and chooses between the two based on the dimensions of the input (similar to `np.matmul`).

**Comment by shoyer** [comment]
Note: this has strong overlap with https://github.com/dask/dask/issues/1176

**Comment by jakirkham** [comment]
Believe this was solved by PR ( https://github.com/dask/dask/pull/3109 ). Can someone please confirm or deny?

**Comment by jakirkham** [comment]
Going to go ahead and closed as this appears to be solved. If not, feel free to let us know and we can reopen. Thanks.
