### ISSUE TITLE
Unique() implementation for Dask

### ISSUE THREAD

**Issue by doctorf72** [dask/dask#1191]
Hello.
Is it possible to implement Pandas unique() for Dask platform? This will increase functionality.
Thank you
Felix

**Comment by mrocklin** [comment]
Does `drop_duplicates` work for you?

**Comment by mrocklin** [comment]
It looks like there is a `dd.Series.unique` method, but not a separate `unique` function.  Is this something you would be interested in contributing?  It should be fairly simple to add.

**Comment by doctorf72** [comment]
I am interesting as an end user. I am using unique to slice main data set into sub sets. With unique i am getting unique values and put them into list. After i am iterating through this list and subset from main data set rows meeting criteria df[df['A']==iterator]. Is it help?

**Comment by mrocklin** [comment]
Perhaps you can `groupby` the column you want to achieve the same result more efficiently?

**Comment by mrocklin** [comment]
@limx0 mentioned that `pandas.DataFrame` doesn't support `unique`.  Presumably `drop_duplicates` suffices.  Closing for now.

**Comment by TomAugspurger** [comment]
pandas.DataFrame.unique was added after this issue was closed.

Properly supporting it in dask sounds somewhat difficult, but I haven't put much thought into that.

**Comment by summerela** [comment]
The groupby/apply functions can be pretty spendy, but vital. Either way, Dask is awesome, thanks so much for all the hard work :smile:

**Comment by myidealab** [comment]
It may not seem obvious, but for the Dask DataFrame to use Pandas DataFrame methods, you add `.compute()` to the end of the method: `df_name.column_name.unique().compute()`

Sources:
[Dask Documentation - DataFrame](https://docs.dask.org/en/latest/dataframe.html)  
[Dask Documentation - Managing Computation](https://distributed.dask.org/en/latest/manage-computation.html)
