### ISSUE TITLE
Scheduler doesn't compute lists of tasks

### ISSUE THREAD

**Issue by jcrist** [dask/dask#1192]
Lists of tasks with no external dependencies aren't computed:

```python
In [1]: from dask import get

In [2]: def inc(x):
   ...:     return x + 1
   ...:

# This doesn't work
In [3]: dsk = {'a': [1, (inc, 1)]}

In [4]: get(dsk, 'a')
Out[4]: [1, (<function __main__.inc>, 1)]

# But this does
In [5]: dsk = {'a': ['b', (inc, 1)], 'b': 1}

In [6]: get(dsk, 'a')
Out[6]: [1, 2]

# And so does this
In [7]: dsk = {'a': [1, (inc, 'b')], 'b': 1}

In [8]: get(dsk, 'a')
Out[8]: [1, 2]
```

Discovered while investigating http://stackoverflow.com/questions/37535160/using-dask-multi-threaded-module.

**Comment by jcrist** [comment]
Related: https://github.com/dask/dask/issues/421. I still think this is inconsistent here, not sure what the best solution is. Past me thought it was don't compute things that aren't tasks (meaning no top-level lists should be computed).

Because of this thought, I've pushed a fix for the stackoverflow issue here https://github.com/dask/dask/pull/1194, which fixes it so that those graphs don't result.

This issue should stay open for discussion though (which is really a continuation of https://github.com/dask/dask/issues/421). My personal preference is that either all or none of the above work. None seems safer, as the list could be extremely large and nested.

**Comment by mrocklin** [comment]
My assumption was that `{'a': [1, (inc, 1)]}` *would* trigger a computation.  Performance issues aside this seems least surprising to me.  

Have we run into cases where long list traversal burdens pragmatic problems?

**Comment by jcrist** [comment]
Not that I know of, but I could probably construct some artificial case where it would cause problems. It's also a bit ambiguous what a list of strings represents:

```python
{'a': ['b', 'c', 'd', 'e'], ...}
```

Are the strings keys or data? You'd have to check each one to see if it's a key in the graph. This may not be bad, it's just something that may come up.

Having list literals be tasks regardless of whether they're a direct argument or not would definitely simplify things. If this is a but, it's been broken this way for a while (see #421).

**Comment by mrocklin** [comment]
Per the spec `'b'` is considered to be a key if its in the dict or a literal if it isn't.  Not the most explicit, but simple and fast-ish to check.
