### ISSUE TITLE
batched consumption of dask.bag

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#120]
Migrated from mrocklin fork. Originally posted by @phrrngtn

How do you suggest consuming a dask.bag in chunks of N?  My particular use-case is writing/merging cooked output to the database (which I want to be done by a single writer to avoid unnecessary contention at the database).  I want something that iterates over the bag (ideally gathering back whatever results are available for whatever partition) and returns a block/batch that in turn is iterable to get at the items themselves. E.g.
```python
for batch in bag.batch(N):
    e.execute(q, batch)
```
 
where e is a sqlalchemy engine, q is a sqlalchemy insert query.

I have hacked together something similar with itertools.islice on top of ipython parallel.
http://ipython.org/ipython-doc/dev/parallel/asyncresult.html#map-results-are-iterable

**Comment by mrocklin** [comment]
At the moment this isn't doable.  It should be though.  We'll need to teach the schedulers how to operate in an iterative way.  This is a bit tricky as we might want consumption of the iterator to throttle execution within the scheduler.

A hack would be to encode your database submission operations as tasks in the dask graph and link those tasks in a sequential way.  This is way more low-level into the guts of dask graphs than most people would like to get though.

**Comment by mrocklin** [comment]
This can be done with the [distributed scheduler](distributed.readthedocs.org) closing.

**Comment by amnezzia** [comment]
@mrocklin is there an example how this can be done? the link does not lead anywhere

**Comment by mrocklin** [comment]
I've fixed the link.  This link would probably be nicer today though: http://dask.pydata.org/en/latest/futures.html
