### ISSUE TITLE
`.notnull()` and `.isnull()` methods not defined on DataFrames

### ISSUE THREAD

**Issue by flacjacket** [dask/dask#1205]
Pandas DataFrames proved methods for computing [`isnull()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.isnull.html) and [`notnull()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.notnull.html), however Dask currently only provides these methods for Series objects.

**Comment by jcrist** [comment]
Thanks, fixed in #1206.

**Comment by flacjacket** [comment]
Thanks for the quick fix, Jim!
