### ISSUE TITLE
Adding a .iteritems() method to dask.dataframe.DataFrame

### ISSUE THREAD

**Issue by chrislaing** [dask/dask#1214]
Hello,

I have not contributed to this project before, and would like some guidance on the following issue:

While both the dask Series class and the pandas DataFrame class implement a .iteritems() method, dask DataFrame does not. Among other things, this makes conversion using xarray.Dataset.from_dataframe difficult.

The pandas .iteritems() method yields a (column_name, Series) for each column of the DataFrame. As an inherently column-wise operation, this cannot be naïvely implemented in a similar fashion to the .iterrows() method. Explicitly, a method implemented like so:

```
@derived_from(pd.DataFrame)
def iteritems(self):
    for i in range(self.npartitions):
        df = self.get_division(i).compute()
        for item in df.iteritems():
            yield item
```

yields each of the columns of the first partition, followed by each of the columns of the second partition, etc.

The (ugly and suboptimal) implementation below yields a (column_name, Series) for each iteration

```
@derived_from(pd.DataFrame)
def iteritems(self):
    for k in self.columns:
        yield (k, self.__getitem__(k).compute())
```

and passes the following (also ugly and suboptimal) test

```
def test_dataframe_iteritems():
    df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 30, 40]})
    ddf = dd.from_pandas(df, npartitions=2)

    for (a, b) in zip(df.iteritems(), ddf.iteritems()):
        assert a[0] == b[0]
        tm.assert_series_equal(a[1], b[1])
```

Disregarding the poor implementation, there remains the issue that yielding a pandas Series object seems to me to defeat the purpose of dask's out-of-core computation. In my view, yielding a dask Series object would be the more useful functionality.

The following implementation gives essentially this functionality, but I am not sure that it makes sense, and seems to me to break the API.

```
@derived_from(pd.DataFrame)
def iteritems(self):
    for k in self.columns:
        yield (k, self.__getitem__(k))
```

I would appreciate some guidance as to what the desired behaviour of .iteritems() should be.

Many thanks in advance.

**Comment by mrocklin** [comment]
Ah, when I encouraged this earlier I mistakenly assumed that `pandas.DataFrame.iteritems` iterated over rows.  I agree with your assessment that the actual behavior of iterating over columns does not align well with how `dask.DataFrame` separates data.

I don't see a simple way to achieve this operation efficiently in small memory

**Comment by jcrist** [comment]
Since this can't be implemented in a performant way, and doesn't mesh with how `dask.dataframe` separates data, I'm closing this for now.
