### ISSUE TITLE
Organize examples from various sources

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1217]
We have a lot of examples from different sources.  It would be good to include these in the examples sections of the various collections
### Sources
- http://matthewrocklin.com/blog
- https://gist.github.com/mrocklin
- https://www.youtube.com/playlist?list=PLRtz5iA93T4PQvWuoMnIyEIz1fXiJ5Pri
### Targets
- http://dask.readthedocs.io/en/latest/array-examples.html
- http://dask.readthedocs.io/en/latest/bag-examples.html
- http://dask.readthedocs.io/en/latest/dataframe-examples.html
- http://dask.readthedocs.io/en/latest/delayed-examples.html

@jnmclarty

**Comment by jnmclarty** [comment]
Maybe we should find a way to just index notebook renderings(?)

https://github.com/dask/dask-examples => http://mybinder.org/repo/dask/dask-examples/status (too cool, btw!)

**Comment by mrocklin** [comment]
Github/gist will render the notebooks.  We can also provide nbviewer links which look a bit nicer and sometimes render faster.  

Binder is cool when it works.  Historically we haven't had the discipline to keep things up to date so that they run smoothly there, although I am pleasantly surprised to find that many of the dask-examples are still in good working order.  

Perhaps we provide a variety of links to static and interactive notebooks?

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask-examples/ is probably the best place for developing further examples (good to keep this issue for visibility though).

**Comment by mrocklin** [comment]
https://examples.dask.org
