### ISSUE TITLE
Add tests to package

### ISSUE THREAD

**Issue by stefanv** [dask/dask#1223]
In `setup.py`, make sure `tests` subdirectories are included in the package (otherwise, it is not possible for a user with an installed version of dask to verify its integrity).

**Comment by jcrist** [comment]
How would you advise this is done? We rely on pytest as our testing framework, and I'd be hesitant to add that as a dependency to the package. Would just adding the tests the package be enough, or should we provide a `test` function as in numpy/pandas/etc...?

**Comment by stefanv** [comment]
Adding pytest won't be needed.  Just add ``__init__.py`` files in all test directories.
