### ISSUE TITLE
read_csv sampling logic is not a generalized solution

### ISSUE THREAD

**Issue by frol** [dask/dask#1230]
I have hit an issue with a dataset which has over 10k columns, so I obviously hit a bug with a misleading error message:

```
/opt/conda/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    486                 _execute_task(task, data)  # Re-execute locally
    487             else:
--> 488                 raise(remote_exception(res, tb))
    489         state['cache'][key] = res
    490         finish_task(dsk, key, state, results, keyorder.get)

ValueError: ('Columns do not match', Index(['Unnamed: 0', 'Var1', 'Var2', 'Var3', 'Var4', 'Var5', 'Var6', 'Var7',
       'Var8', 'Var9',...
```

Once I bumped the `sample` size to `1MB` I got through the above error but hit another one described in a related issue #1166, when sample size is not enough to guess dtypes (I have very sparse character columns with a number of missings (>95%), which is not a so rare use-case).

I do understand that from a performance point of view it is not a great idea to scan the whole dataset twice, but can be there implemented an option to force full scan (in fact, early stopping once `object` dtype is discovered can save some time and full scan won't take so long)?

**Comment by jcrist** [comment]
Regarding the first error, that can definitely be fixed, your csv was wide enough that it wasn't grabbing all of the columns in the sample.

If the dtypes are known, you can pass in the dtypes to `read_csv`, and that will avoid your issue. In general I'd prefer to avoid recommending a full read to users, so making that cheap is a bit undesirable. Passing in a very large number to `sample` should also work, although it's a bit of a hack.

**Comment by frol** [comment]
@jcrist Passing a larger `sample` makes it work for this specific case, just like it did for @koverholt in #1166. However, increasing the size of `sample` will only make it harder to catch the issue next time.

**Comment by mrocklin** [comment]
Perhaps this issue can be resolved with a separate function that does do a full pass and determines dtypes.  This would be separate from read_csv, isolating an uncommon case, but would be mentioned somewhere in a docstring or exception, removing the burden from the user to figure out how to perform the full scan.

Thoughts?

**Comment by frol** [comment]
@mrocklin This will be fine for me. However, I was thinking that there must be an option in the reader itself to ensure that a dataset will be read without weird issues... I would even assume this to be a default behavior with an option to switch to "hope we guessed correctly" mode.

**Comment by mrocklin** [comment]
In common cases this degrades performance sufficiently that it feels wrong to make it the default.  In general I'm completely for opting into performance and out of correctness.  But in the common case of reading data from disk `dd.read_csv` would start taking tens of minutes, pretty much destroying any chance of interactivity.  Personally I find the optimistic approach better, especially if we couple it with informative error messages.
