### ISSUE TITLE
dask.dataframe.read_csv cannot be used to read from non-localhost HDFS

### ISSUE THREAD

**Issue by frol** [dask/dask#1232]
Current implementation of `dask.dataframe.read_csv` don't pass either `**kwargs` or, at the very least, `hdfs` down to `read_bytes`. Thus, I cannot read CSV files from HDFS if it is not on the localhost.

It also seems not supporting URL parsing for HDFS name-node hostname and port extraction, e.g.:

```python
>>> dask.dataframe.read_csv('hdfs://my-namenode.hdfs/my-file.csv')
```

This will try to locate `my-namenode.hdfs/my-file.csv` file on `localhost:8020` instead of `my-file.csv` file on `my-namenode.hdfs:8020`.

P.S. Patching and passing `hdfs` argument to `read_csv` get things a little bit further, but another "unexpected keyword 'hdfs'" raised later, so be prepared to test this thing...

**Comment by mrocklin** [comment]
@frol did this PR improve the situation?  https://github.com/dask/dask/pull/1184

**Comment by frol** [comment]
@mrocklin Yes, it did the trick. Still, URL parsing would be a natural thing to go with, but `storage_options` argument at least fixes the introduced regression.

**Comment by frol** [comment]
BTW, `distributed.hdfs.read_csv` is broken because it passes `hdfs` argument to `dd.read_csv`.

**Comment by mrocklin** [comment]
We'll probably remove `distributed.hdfs.read_csv` in the next version anyway.  It's just there to hold a deprecation warning.

**Comment by frol** [comment]
The point of a deprecated code is to work just as before, but with a warning of future changes. Here we have a broken implementation, which is not good.

**Comment by mrocklin** [comment]
Eventually we need to remove the functionality.  This feature was not in wide circulation.  It was experimental and all documentation referring to it (mostly just blogposts) referred to it as experimental.  The deprecation warning has been around for a couple of versions now.  I think that it's reasonable to remove it at this point.  I definitely don't intend to keep it around forever.
