### ISSUE TITLE
read_json for dask.DataFrame

### ISSUE THREAD

**Issue by jebuss** [dask/dask#1236]
Hi, Could you implement a json reader for the dask.DataFrame, please?

**Comment by mrocklin** [comment]
Normal JSON?  
Line delimited JSON? (this is probably more useful for you but not yet implemented in Pandas)

You could probably also implement this yourself by following http://dask.readthedocs.io/en/latest/delayed-collections.html if you were interested.

Is this something you would feel like contributing?

**Comment by necaris** [comment]
I believe you can also get data into a `dask.dataframe` with [odo](http://odo.pydata.org/en/latest/json.html), if that's useful?

**Comment by mrocklin** [comment]
As of https://github.com/pydata/pandas/pull/13351 pandas now supports line-delimited json

**Comment by TomAugspurger** [comment]
Closed by #3494
