### ISSUE TITLE
`storage_options` argument to `dataframe.read_csv` is out of sync with `bag.read_text` and open_files methods

### ISSUE THREAD

**Issue by frol** [dask/dask#1237]
Since #1184 is not released yet, I think it is a good time to align interfaces of all `read_*` methods. Currently, you have to pass `protocol://path` string to the first (`path`) argument and, in case of `read_csv`, a dict with storage options as `storage_options` argument, while `bag.read_text` and `open_files` methods expect storage options in `**kwargs`.

I think `storage_options` should be just implemented everywhere instead of polluting `**kwargs`. Also, I suggest to parse `path` (first argument to `read_*` and `open_files` methods) with [`urllib.parse` (py3)](https://docs.python.org/3/library/urllib.parse.html) / [`urlparse` (py2)](https://docs.python.org/2/library/urlparse.html) instead of dummy splits.

This issue is related to #1232.

**Comment by mrocklin** [comment]
Both of these ideas sound fine to me.  Can I interest you in contributing a PR?  These both seem fairly straightforward to implement.
