### ISSUE TITLE
error 139 on mac

### ISSUE THREAD

**Issue by erwindassen** [dask/dask#1238]
I have a set of HDF5 files containing pandas `DataFrames` saved via `to_hdf` with `format='table'`. The layout of such a table is 

```
                                                  precipitation mm/h  temperature C  timestamp_start  trafficflow counts/h  trafficspeed km/h  windspeed m/s
site                         datetime_start                                                                                                                 
RWS01_MONIBAS_0131hrl0038ra  2016-01-12 09:35:00                 0.0            7.1       1452591300                1100.0          95.333333            9.0
RWS01_MONIBAS_0131hrl0056ra  2016-01-12 07:47:00                 0.0            7.0       1452584820                1240.0          63.666667            7.0
RWS01_MONIBAS_0131hrl0079ra  2016-01-12 10:52:00                 0.3            6.5       1452595920                1080.0         101.333333            6.0
```

For completeness the info of such a data frame:

```
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2199936 entries, (rws01_monibas_0010vwa0056ra, 2016-01-22 04:58:00) to (rws01_monica_10d04c00705bd007000b, 2016-01-22 12:00:00)
Data columns (total 6 columns):
precipitation mm/h      float64
temperature C           float64
timestamp_start         int64
trafficflow counts/h    float64
trafficspeed km/h       float64
windspeed m/s           float64
dtypes: float64(5), int64(1)
memory usage: 117.5+ MB
```

I'm trying to use `dask.dataframe` to load and aggregate the whole dataset. But even at the following simple example I get an error code 139 on my computer. I'm running on a mac with python 3.5 (anaconda 4.0) and dask 0.8.1. I got confirmation that the same code runs correctly on a linux box.

```
glob = str(DF_DIR) + '/*.hdf'  # DF_DIR points to the input folder (a pathlib Path)

df = dd.read_hdf(glob, key='dataset')

print(df.npartitions)  # I get 132 partitions

# Since I have 100s of thousands of records this should give a non-empty DataFrame
samples = df.sample(1e-6).compute()
print(samples.head())
```

I tried to look for similar issues in the net (stackoverflow included!) but since I couldn't find I'm posting it here.

Kind regards,

Erwin

**Comment by erwindassen** [comment]
Errata: I'm running on version 0.9.0 on both machines.

**Comment by jcrist** [comment]
Can you post the traceback? After which line of the above do you get the error? How did you install your python packages?

**Comment by erwindassen** [comment]
The error occurs after the `compute` call, that is, the `df.sample` call returns correctly.

This is the output if run from the terminal:
```
python src/predictor/models/tflearn_lstm.py 
0.9.0
132
Segmentation fault: 11
```

Ans this is from the pyCharm debugger:
```
pydev debugger: process 60591 is connecting

Connected to pydev debugger (build 145.971)
0.9.0
132
Backend MacOSX is interactive backend. Turning interactive mode on.
python(60591,0x70000272b000) malloc: *** error for object 0x125220b00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Process finished with exit code 139
```

I don't seem to get a full traceback (at least from python).

I installed all packages via `conda` or `pip` in case not available on `conda`.

**Comment by jcrist** [comment]
I suspect you're using an older version of pandas (which had known segfaults in threaded code). Can you update pandas to 0.18.1?

**Comment by erwindassen** [comment]
I think I'm in the right version:

```
(mlenv)mun:companion-predictor eltdassen$ python
Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> import pandas
>>> print(h5py.__version__)
2.6.0
>>> print(pandas.__version__)
0.18.1
>>> 
```

Thanks for your time,

Erwin

**Comment by jcrist** [comment]
Ahh, I missed that you're globbing multiple files, instead of using just one file. This was a bug in the last release of dask (see https://github.com/dask/dask/issues/1198). Can you try running on dask master?

`pip install --upgrade git+https://github.com/dask/dask.git`

**Comment by erwindassen** [comment]
Yep! Solved the problem. Funny how it runs on linux though. Out of curiosity, why?

**Comment by jcrist** [comment]
Not sure. Could be different versions of hdf5/h5py between the two machines. Could also be that it's not threadsafe on linux either, and you just got lucky when running it. Either way, glad it's fixed. Closing.

**Comment by dojeda** [comment]
Just a heads-up to whoever may be interested: we've encountered this issue, that is a malloc exception when using pandas and hdf5 within Dask on OSX. Our culprit was that we had an anaconda environment with pandas and pytables installed from pip, but when we re-created an environment with these two dependencies installed by conda and not pip, the problem was solved.
Cheers.
