### ISSUE TITLE
Reduce communication in rolling operations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1242]
Rolling operations currently take two partitions as inputs to produce one output partition.  This causes a lot of communication in a distributed memory case.  Instead we should explicitly split off a window-sized tail of the previous partition as a separate task.  This smaller piece can be moved around more easily.

Comes from https://github.com/dask/dask/pull/1221

**Comment by mikegraham** [comment]
Relatedly: currently, the rolling operations also only look at one chunk prior, so if the window is bigger than the size of the prior partition minus one, dask can't handle it. Is this a fair limitation, or is it important that dask should look back further?

**Comment by mrocklin** [comment]
It is difficult to determine how far back we should look at graph construction time.  I'm fine with punting in this case.  

Alternatively, I wonder if it is reasonable to return `nan` in cases where we were unable to determine correct results.  I don't know enough about how people interpret `nan` in these cases to know if this is correct or not.

**Comment by jcrist** [comment]
> Alternatively, I wonder if it is reasonable to return nan in cases where we were unable to determine correct results. I don't know enough about how people interpret nan in these cases to know if this is correct or not.

I think that'd be the wrong thing to do here (at least by default) - `nan` propagation in `rolling` has defined semantics, changing those for dask may be unexpected. In the past implementation we just punted and threw an informative error during computation.

**Comment by mrocklin** [comment]
Alright, sounds good

**Comment by mikegraham** [comment]
I pushed a PR for this, though I'm not positive it truly addresses the issue. I call a function that will just have to tail the full array, so it won't in general decrease communication. Does distributed have some sort of node affinity to allow direct access in some cases?

My PR should decrease the memory requirements for any single worker either way.
