### ISSUE TITLE
DataFrame loc on string timestamp fails

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1265]
When we index a timestamp indexed dataframe with a slice of times encoded as strings everything is great

    result = df.loc['2015-01': '2015-02']

However, when we use a single string things fail

    result = df.loc['2015-01']

Probably there is some custom logic in dask.dataframe that is doing actual value comparisons of the input string against the `divisions`.  It would be nice to use whatever logic Pandas uses in order to coerce this input to the proper timestamp.

cc @jreback any pointers?

**Comment by jreback** [comment]
https://github.com/pydata/pandas/blob/master/pandas/core/indexing.py#L1756 will give you an indexer (or ``None``) if its not applicable based on the key and index

**Comment by mrocklin** [comment]
Unfortunately we don't have a fully realized index with values to throw this against.

**Comment by jreback** [comment]
not sure I understand, how is this different that the slicing of two strings case? you don't need a fully materialized index, this can be in a chunk.

**Comment by mrocklin** [comment]
I first need to compare these values against the divisions that separate the partitions.  This allows me to select which partitions to send the loc query down to.
