### ISSUE TITLE
Support feather format in dask.dataframe

### ISSUE THREAD

**Issue by benitocm** [dask/dask#1277]
Feather format looks promising as a columnar data format. It would be nice if the dask.dataframe could  read/write feather files as in the case hdf5 format.

**Comment by sinhrks** [comment]
Should be after https://github.com/pydata/pandas/issues/13092

**Comment by mrocklin** [comment]
My understanding is that feather does not support random access, which makes it hard to read a single feather file in chunks.  If this is true then the only parallelism we can provide is on multiple files.   This might still be worth supporting, but is less exciting.  

Also, it's quite easy to handle custom file formats without putting them into dask.dataframe.  For an example see this rather old notebook using dask.dataframe with feather: https://gist.github.com/mrocklin/e7b7b3a65f2835cda813096332ec73ca

**Comment by benitocm** [comment]
I had already seen that notebook. The thing is that you could not manage a "big" dataframe right?
In Feather project, there are  some issues opened related to support some kind of chunking.

**Comment by mrocklin** [comment]
We could not manage a big Feather file.  Although we could manage a big dataframe composed of many Feather files.  It would be very easy to add a `dask.dataframe.from_feather` function after Feather supports random chunked reads.  Before then there isn't much we can do.

**Comment by benitocm** [comment]
Thanks very much for the explanation.

**Comment by my-R-help** [comment]
I think it would be nice to be able to export a dask dataframe to feather. My idea is this: Run first steps in dask and reduce the size of the data (by aggregating or subsampling), then save to feather and continue e.g. in R. I think this would be nice and people (especially coming from R) would love it, since right now there's no equivalent in R that is capable to deal with larger-than-memory data as easily as in dask.

**Comment by mrocklin** [comment]
Does feather support chunked writing?  If not then the way to do this is probably just to aggregate as you suggest, convert to a Pandas dataframe, and then convert to feather.

    my_dask_dataframe.compute().to_feather()

**Comment by martindurant** [comment]
As above, I'm assuming since we're dealing with out-of-core sizes, a single massive feather file may not be possible to make or be useful for R to read. Many-feather-files may well be useful, though, and easy to implement in dask.

**Comment by mrocklin** [comment]
Ah, sorry, should have looked more deeply at the history of this issue.

**Comment by harryprince** [comment]
@my-R-help maybe, reticulate can help you to call Dask directly in R

**Comment by dhirschfeld** [comment]
The feather format is likely to be replaced by direct arrow support in R:
https://github.com/apache/arrow/pull/1815

**Comment by mrocklin** [comment]
We have yet to come across a case of people actively wanting to use feather in a parallel way in the wild.  Most folks today seem to prefer parquet.  This issue seems to be of the form "it might be nice if", so I'm going to close it for now.  If someone actively has a need for this please ping here and I'll reopen.

**Comment by jangorecki** [comment]
@mrocklin is there any doc on how to read data from `feather` file into dask dataframe?

**Comment by jangorecki** [comment]
@TomAugspurger your code, precisely `dd.concat(dfs)` raises following exception
```
TypeError: Truth of Delayed objects is not supported
```
It seems that `father.read_dataframe` cannot be concatenated.
I actually need to load single feather file only, not as pandas but as dask to utilize multiple cores.

**Comment by mrocklin** [comment]
There is an old notebook example here:
https://gist.github.com/mrocklin/a6360fc7c91b6ec53101c91dd358e80b

**Comment by mrocklin** [comment]
That notebook is more about trying to communicate that dask.delayed can be used for complex problems than feather specifically, so it may be more complex then you need.  Hopefully it teaches you how to interact between dask.delayed and dask.dataframe though.

**Comment by TomAugspurger** [comment]
Sorry I was missing a dd.from_delayed


________________________________
