### ISSUE TITLE
Should _default_get be inherited on chained operations?

### ISSUE THREAD

**Issue by frol** [dask/dask#1283]
```python
>>> dd = distributed_executor.persist(local_dd)
>>> dd._default_get
<function dask.threaded.get>
>>> dd._default_get = distributed_executor.get
>>> dd.head(compute=False)._default_get
<function dask.threaded.get>
```

Due to the fact that currently `_default_get` is not inherited, I'm getting a weird traceback if I do `dd.head()`:

```python
>>> dd.head()
/opt/conda/lib/python3.5/site-packages/dask/dataframe/core.py in head(self, n, compute)
    369 
    370         if compute:
--> 371             result = result.compute()
    372         return result
    373 

/opt/conda/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     35 
     36     def compute(self, **kwargs):
---> 37         return compute(self, **kwargs)[0]
     38 
     39     @classmethod

/opt/conda/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    108                 for opt, val in groups.items()])
    109     keys = [var._keys() for var in variables]
--> 110     results = get(dsk, keys, **kwargs)
    111 
    112     results_iter = iter(results)

/opt/conda/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/opt/conda/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    486                 _execute_task(task, data)  # Re-execute locally
    487             else:
--> 488                 raise(remote_exception(res, tb))
    489         state['cache'][key] = res
    490         finish_task(dsk, key, state, results, keyorder.get)

AttributeError: 'Future' object has no attribute 'head'

Traceback
---------
  File "/opt/conda/lib/python3.5/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/opt/conda/lib/python3.5/site-packages/dask/dataframe/core.py", line 365, in <lambda>
    dsk = {(name, 0): (lambda x, n: x.head(n=n), (self._name, 0), n)}
```

It also seems that `_default_get` is not used much (I would expect `distributed_executor.persist()` set it automatically; am I doing something wrong?)

**Comment by mrocklin** [comment]
You should use the following:

```python
dask.set_options(get=distributed_executor.get)
```

**Comment by mrocklin** [comment]
_default_get is a class attribute and not something that users should feel comfortable changing.

**Comment by frol** [comment]
`dask.set_options` is a global setting, and I'm not a fan of global changes. Especially, when local setting is expected to work.

**Comment by mrocklin** [comment]
You can use set_options as a context manager.  You can supply `get=e.get` in any compute call.  Are these options sufficient for you?

You should treat `dd._default_get` as global as well, just a global option that is not supported or intended.

**Comment by frol** [comment]
I can live even with ugly API, but I would like to make it better. Wrapping data with `e.persist`, I expect that my next operations on this data are performed wherever my data is persistent on, and I certainly wouldn't expect to get `'Future' object does not have a method...`

**Comment by mrocklin** [comment]
Agreed.  I've run across that error as well and it took me (who presumably wrote the error message) a while to figure out what was going on.

One option is to have the Executor set itself as default upon construction (see https://github.com/dask/distributed/pull/319).  This is pretty robust but does affect global state.

Making `_default_get` a field and passing it through is possible, but would take a lot of work, both today and for all future changes to dask.dataframe.

We could also try to catch that error and redirect to the last constructed Executor.  

Any thoughts or suggestions on how best to handle this?

**Comment by mrocklin** [comment]
The intrinsic problem here is that dask graphs *are* separate from the scheduler.  This was an early decision that helped tremendously (for example all of the dask collections work today with the distributed scheduler, which was constructed after they were designed) but this freedom does cause ambiguity and opportunities for the user to shoot themselves in the foot.

**Comment by frol** [comment]
> Making `_default_get` a field and passing it through is possible, but would take a lot of work, both today and for all future changes to dask.dataframe.

Hmm, why are you talking like there is no `_default_get` implementation at all? (It is a part of `dask.base.Base` implementation.)

> One option is to have the Executor set itself as default upon construction (see dask/distributed#319). This is pretty robust but does affect global state.

Why don't just set `_default_get` on a persisted instance, and inherit `_default_get` on chained operations?

> You can use set_options as a context manager.

The implementation doesn't seem to be thread-safe, so I would avoid using it as much as possible.

**Comment by mrocklin** [comment]
`_default_get` is a static field on the class, not on the objects.  We would need to pass it around through all operations.  We would also need to figure out what to do when two different objects with different default-gets interact.  I'm not saying no to this I'm just saying that it's a lot of work.  If you're interested in implementing it then please I'd love to see a PR.  I think it'd be a great addition.

Regarding thread-safety of `set_options` I've found it to be very effective.  I tend not to run many dask programs in separate threads though.   Given your reaction here I assume that you presumably do.

**Comment by frol** [comment]
> `_default_get` is a static field on the class, not on the objects.

Silly me. Sorry, I missed this.

> We would also need to figure out what to do when two different objects with different default-gets interact.

I am fine with the current behaviour, which is to raise an exception: https://github.com/dask/dask/blob/master/dask/base.py#L166

I will see how far I can get with my ideas.

**Comment by jcrist** [comment]
As Matt said above, `_default_get` is an attribute of the class itself, and not meant for mucking with. If you'd like to discuss changes to how this works, #1068 was an attempt to codify this as a public spec for use by other packages. Closing for now, feel free to reopen if you're still interested in this.
