### ISSUE TITLE
performance issue with slicing and hdf5 

### ISSUE THREAD

**Issue by redst4r** [dask/dask#1289]
Hi,

when using dask.arrays on hdf5 files, I noticed a quite drastic drop in performance when doing different kinds of slices (continuous vs leaps):

```python
import dask.array as da
import numpy as np
import h5py

# create some big HDF5 files
with h5py.File('d1.h5') as f:
    f.create_dataset('data',data=np.random.rand(10000, 100,100), chunks=(200,100,100))

X = da.from_array(h5py.File('d1.h5')['/data'], chunks=(200,100,100))

ixFast = np.arange(100)   # contiguous indexing
ixSlow = np.arange(0,200,2)  # skipping every second one

% timeit X[ixFast].compute()
# Output: 
# 100 loops, best of 3: 16.6 ms per loop

% timeit X[ixSlow].compute()
# Output: 
# 10 loops, best of 3: 157 ms per loop
```

So, slicing out every second element is **10x slower** than just getting a contiguous part of the array.
Note that both slices stay within the first chunk of the data (which goes up to element 200), so its not that for the second slice dask has to work on more chunks.

Also, this only seems to happen in conjunction with hdf5. If the array resides in memory, no performance difference occurs :

```python
X = da.from_array(np.random.rand(10000, 100,100), chunks=(200,100,100))
% timeit X[ixFast].compute()
# Output:
# 100 loops, best of 3: 13.4 ms per loop

% timeit X[ixSlow].compute()
# 100 loops, best of 3: 13.3 ms per loop
```

Any ideas where this comes from? 
For me it's quite an issue, since I have huge hdf5-datafiles on disk, whose elements I want to feed into a machine learning algorithm, but not necessarily in the order that they are stored on disk (this skipping every second thing above is just the most simple example I could come up with).

**Comment by mrocklin** [comment]
Thanks for the reproducible example.  That is odd.  I'll take a look.

**Comment by mrocklin** [comment]
So, this might just be an HDF5 or H5Py thing.  Here is the same slowdown occuring without involving dask.array.

```python
In [1]: import dask.array as da

In [2]: import numpy as np

In [3]: import h5py

In [4]: f = h5py.File('d1.h5')

In [5]: ixFast = np.arange(100)   # contiguous indexing

In [6]: ixSlow = np.arange(0,200,2)  # skipping every second one

In [7]: %time _ = f['data'][ixFast, :, :]
CPU times: user 0 ns, sys: 4 ms, total: 4 ms
Wall time: 5.21 ms

In [8]: %time _ = f['data'][ixSlow, :, :]
CPU times: user 184 ms, sys: 4 ms, total: 188 ms
Wall time: 188 ms
```

**Comment by redst4r** [comment]
I can confirm that this is an HDF5 issue, maybe similar to [this H5Py issue](https://github.com/h5py/h5py/issues/413).
A simple workaround is to fetch the entire chunk (or multiple if the indices cover many chunks) from HDF5 and slice into them individually. 

```python
the_chunk = f['data'][:200]
the_chunk[ixSlow]
#100 loops, best of 3: 3.76 ms per loop
```
However, in general you pay the price of fetching much more elements than you need.

btw, thanks for this great project, dask made my life alot simpler :)

**Comment by mrocklin** [comment]
@redst4r is there anything dask should be doing differently here or should we close this issue?

**Comment by redst4r** [comment]
I don't think it's dask responsibility to handle this; that's really a problem of h5py or even hdf5 itself.
Maybe we can put a hint into the documentation that slicing into those hdf5 arrays might decrease performance.

**Comment by mrocklin** [comment]
Hrm, where in the documentation would you suggest?  Corner cases like these are tricky.  It's important to alert people to their presence but hard to introduce them without derailing the general common-case conversation.

**Comment by mrocklin** [comment]
Closing for now.  Please reopen if further discussion is warranted
