### ISSUE TITLE
resample doesn't support `.aggregate`

### ISSUE THREAD

**Issue by mikegraham** [dask/dask#1291]
```
In [308]: s # pandas series
Out[308]: 
2000-01-01 00:00:00    0
2000-01-01 00:01:00    1
2000-01-01 00:02:00    2
2000-01-01 00:03:00    3
2000-01-01 00:04:00    4
2000-01-01 00:05:00    5
2000-01-01 00:06:00    6
2000-01-01 00:07:00    7
2000-01-01 00:08:00    8
Freq: T, dtype: int64

In [309]: s.resample('2min').aggregate('asfreq')
Out[309]: 
2000-01-01 00:00:00    0
2000-01-01 00:02:00    2
2000-01-01 00:04:00    4
2000-01-01 00:06:00    6
2000-01-01 00:08:00    8
Freq: 2T, dtype: int64

In [310]: dd.from_pandas(s, 2).resample('2min').aggregate('asfreq')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-310-3b266d1c3122> in <module>()
----> 1 dd.from_pandas(s, 2).resample('2min').aggregate('asfreq')

AttributeError: 'Resampler' object has no attribute 'aggregate'
```

@jcrist I think you're the resampling guru?

**Comment by jcrist** [comment]
Sure, aggregate could be added. Will probably get to it later today. If all you're looking for is `.agg('asfreq')`, I'm pretty sure that's equivalent to `.first()` (which is currently implemented).

**Comment by mikegraham** [comment]
@jcrist Thanks for the kind reply.

I was still working on the new rolling API support and was going to add support for the `freq` argument and this was the exact phrasing of how to do the resample in the pandas deprecation warning. I wasn't sure at the time if there wasn't some subtle difference that could end up being material.

**Comment by mrocklin** [comment]
I believe that there are a few things that could be improved with resample.  @mikegraham if you're ever looking for a project after rolling this might suit you well.  

Generally speaking time-series handling in dask.dataframe has a decent foundation but hasn't really been put through its paces.  I suspect that this is because it has been difficult for users to properly set a datetime column as an index until very recently (distributed `set_index`/suffle was finished while we were at PyCon.)  This is a fun area.

**Comment by jcrist** [comment]
If you want to take this, I'd be more than happy to let you. I took a quick look, adding `aggregate` shouldn't be terribly difficult. The biggest issue would be inferring dtype and column names in the non-dictionary case. I'd probably add a keyword to optionally pass in that metadata, and fall back to the approach taken elsewhere where the function is evaluated on empty/fake data.

Adding `asfreq` specifically may be a bit more work though, it doesn't handle the boundaries the same as the other aggregations (unsure why).

**Comment by DigitalPig** [comment]
Looks like 0.13.0 does not have this feature included still? I am trying to apply a function on top of `resample` like:

```python
test_data['data'].groupby(pd.TimeGrouper(freq='M')).apply(func)
```

And I got the message that: 
```
AttributeError: 'Resampler' object has no attribute 'apply'
```
But it looks like the apply function is in the [doc](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.resample)?

**Comment by jsignell** [comment]
I am closing this since it is about `agg` on resample which is on latest dask.
