### ISSUE TITLE
dask.dataframe.to_csv should accept globstrings to write to many files

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1294]
We already do this in `dask.bag.to_textfiles` and `dask.dataframe.to_hdf`.  This would allow for better parallel writes to multiple CSV files at once.

**Comment by nirizr** [comment]
Taking a look at `dask.dataframe.to_csv`, it's structure is really similar to `dask.dataframe.to_hdf` and will have some of the issues we're currently experiencing with `to_hdf` (mode and append, link optimizations).

It feels like we can do better by somehow re-using the same code, although its not clear to me how.

Fulfilling this request is quite simple, especially after i've tampered with that code quite a bit, i'll be PRing this soon.

**Comment by nirizr** [comment]
See PR #1303

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/dask/pull/1303
