### ISSUE TITLE
Write_bytes, write_files

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1295]
We have a nice extensible system to read data from various sources (local, s3, hdfs).

It would be nice to have a similar (hopefully completely analogous) system to write data back to those sources.

cc @martindurant seems like the sort of issue that might interest you

**Comment by martindurant** [comment]
Writing the data to lots of files is very doable, with similar conventions about headers applied to each file or not, depending on the higher-level writer. I believe all map-reduce writers work like this.

For writing blocks to big files, the only way I can see it working is if each shard is written to a separate file, and when they are all complete, a separate task takes care of stitching them together. The second stage might involve re-reading all the data through a single node for some backends, so this will not be uniformly a useful option.

**Comment by mrocklin** [comment]
I suggest that we only concern ourselves parallel one-file-per-partition writing to start

**Comment by jcrist** [comment]
This was fixed in #1346. Closing.
