### ISSUE TITLE
Naming divisions vs partitions

### ISSUE THREAD

**Issue by jseabold** [dask/dask#1309]
Is there a reason to refer to these by different names going forward? They're conceptually the same thing right, or am I missing something? I know the API has been in-flight, so maybe this is already on the radar.

**Comment by mrocklin** [comment]
My intent here was to use the term "partitions" to mean the Pandas dataframes that constitute the dask dataframe and the term "divisions" to mean the values that separate the indices of the partitions.  People do tend to mix the two though.  Thoughts on how to improve the situation?

**Comment by jseabold** [comment]
That sounds reasonable. The method to return a 'partition' is `get_division`, which is a bit tricky. Makes sense both ways I think. Probably just documenting this as convention (if it's not) would clear things up, though I wonder if people would be confused if it was just one or the other. I was mainly just wondering if the current state reflected a transition from one to the other.

**Comment by mrocklin** [comment]
Ah, you're right that `get_division` should probably be renamed.  Improved documentation is probably also a very good idea.
