### ISSUE TITLE
Support idxmax/idxmin for DataFrame

### ISSUE THREAD

**Issue by jseabold** [dask/dask#1310]
Parking this here, since I don't have time right now to dig in. Not sure how difficult it would be with current implementations. Just need to keep up with the indices while doing regular max and min.

**Comment by mrocklin** [comment]
Yeah, you'd probably call `idxfoo` on each partition and `len` on each partition and then add up as necessary.

**Comment by postelrich** [comment]
working on this.

**Comment by postelrich** [comment]
@mrocklin @jcrist closed by #1446

**Comment by jcrist** [comment]
Thanks!
