### ISSUE TITLE
User defined aggregations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1313]
Dask.dataframe has efficient grouped aggregations for known reductions like sum, max, min.
To do this is uses the apply-concat-apply pattern.  We could expose this pattern out to users to help support their own custom aggregations.  This likely just means renaming the currently private `_aca_agg` method, adding a docstring, and adding some documentation.

**Comment by dukebody** [comment]
The signature of the function is:

> def _aca_agg(self, token, func, aggfunc=None, **kwargs)

Can we derive the `token` from the name of the given `func`? None of the rest of public `dask.dataframe` API methods expose the token attribute. We can use `dask.base.tokenize` for this.

So my proposal is to create a new public `aca_agg` function that in turn calls `_aca_agg`.

**Comment by dukebody** [comment]
I believe this is wrong https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2073 (edited):

```
def apply_concat_apply(args, chunk=None, aggregate=None,
                       columns=no_default, token=None, chunk_kwargs=None,
                       aggregate_kwargs=None, **kwargs):
    """ Apply a function to blocks, the concat, then apply again"""
    if chunk_kwargs is None:
        chunk_kwargs = dict()
    if aggregate_kwargs is None:
        aggregate_kwargs = dict()
    chunk_kwargs.update(kwargs)
    aggregate_kwargs.update(kwargs)

    if not isinstance(args, (tuple, list)):
        args = [args]

    ...

    a = '{0}--first-{1}'.format(token, token_key)
    if len(args) == 1 and isinstance(args[0], _Frame) and not chunk_kwargs:
        dsk = dict(((a, i), (chunk, key))
                   for i, key in enumerate(args[0]._keys()))
    else:
        dsk = dict(((a, i), (apply, chunk, [(x._name, i)
                                            if isinstance(x, _Frame)
                                            else x for x in args],
                                    kwargs))
```

Last `kwargs` should be `chunk_kwargs`. Otherwise the argument `chunk_kwargs` is ignored and only the extra `kwargs` are used.

**Comment by mrocklin** [comment]
> So my proposal is to create a new public aca_agg function that in turn calls _aca_agg

This generally sounds good to me.  I recommend rethinking the name `aca_agg` if we intend to expose this to users.  

I recommend looking at using both `dask.utils.funcname` and `dask.base.tokenize` when determining the name.

**Comment by mrocklin** [comment]
Your analysis of `chunk_kwargs` seems accurate to me.
