### ISSUE TITLE
NotImplementedError: Unknown protocol hdfs

### ISSUE THREAD

**Issue by jameskyle** [dask/dask#1324]
After running into issue #1232, I upgraded to the the source version.  hdfs3 is installed and working, but

    import hdfs3
    from dask import dataframe as dd

    namenode = 'mynode.com'
    port = 8020
    hdfs = hdfs3.HDFileSystem(namenode, port)
    hdfs.list('/path/to/file.csv')
    # returns file node information
    data = df.read_csv("hdfs://{0}/path/to/file.csv".format(namenode))

This produces the following error

    NotImplementedErrorTraceback (most recent call last)
    <ipython-input-30-2d58fa3887f0> in <module>()
    ----> 1 data = dd.read_csv('hdfs://{0}/path.to/file.csv'.format(namenode))

    /usr/local/share/virtualenvs/cartman/lib/python2.7/site-packages/dask/dataframe/csv.pyc in    read_csv(filename, blocksize, chunkbytes, collection, lineterminator, compression, sample, enforce,  storage_options, **kwargs)

    /usr/local/share/virtualenvs/cartman/lib/python2.7/site-packages/dask/bytes/core.pyc in read_bytes(path,   delimiter, not_zero, blocksize, sample, compression, **kwargs)

    NotImplementedError: Unknown protocol hdfs://mynode.com/path/to/file.csv

**Comment by mrocklin** [comment]
You'll have to `import dask.distributed`.  Usually people do this anyway to connect to a remote cluster but we should improve the error messaging regardless.

**Comment by mrocklin** [comment]
In particular you need to activate the code in `distributed.hdfs`

We should probably hardcode some of these external paths directly into the `dask.bytes` code.
