### ISSUE TITLE
Save and read dIvisions when using to_hdf and read_hdf

### ISSUE THREAD

**Issue by nirizr** [dask/dask#1336]
Divisions enable better performance and might be hard to compute correctly (see #1058), so preserving division when writing and reading dataframes is valuable. It will also reduce the significance of performance challenges of generating divisions.

They could easily be stored in a "metadata" node within an hdf file.

**Comment by mrocklin** [comment]
An alternative would be to efficiently support a `sorted=True` keyword argument to `read_hdf` which would then quickly run through the column of the HDF file and pick out good locations for dividing the dataset.  This was partially implemented in https://github.com/dask/dask/pull/1058

**Comment by nirizr** [comment]
if you're positive there's no need for this, please go ahead and close the issue.

**Comment by nirizr** [comment]
I think this was mostly implemented in #1407. At least, my goal for this issue is achieved there.
Closing.
