### ISSUE TITLE
Delayed in a loop statement (docs issue)

### ISSUE THREAD

**Issue by wikiped** [dask/dask#1337]
[Docs](https://dask.readthedocs.io/en/latest/delayed-overview.html) show this example for `delayed`:

    from dask import delayed

     output = []
     for x in data:
         a = delayed(inc)(x)
         b = delayed(double)(x)
         c = delayed(add)(a, b)
         output.append(c)

     total = delayed(sum)(output)

At the end of the same page it is said:

 > ...no <code class="docutils literal"><span class="pre">Delayed</span></code> can appear in a loop or if statement.

It does look like example contradicts the last point.
Perhaps that point is out-of-date? Or it means something else?

**Comment by mrocklin** [comment]
I think that the intent was that delayed objects shouldn't be used as part of the condition in an if statement or part of the looping iterator in a for loop but that both can quite comfortably be used within the body of either an if or for construct.

**Comment by jcrist** [comment]
The full statement is:

> The last two in particular mean that Delayed objects cannot be used for control flow, meaning that no Delayed can appear in a loop or if statement.

referring to the last two bullets:

> - Iteration. (for i in a: ...)
> - Use as a predicate (if a: ...)

What this means is that you can't iterate over a delayed object, or use it in an if statement. So the given example is fine, but wouldn't be if `data` was a delayed object.

If you have suggestions for how to clarify this language, please let us know. Docs can always be improved :).

**Comment by wikiped** [comment]
Thanks for clarifying this. I think the way you explain it makes quite easy to understand the meaning and adding this clarification might help to prevent this confusion (assuming I am not the only one to get confused :)

I would change the first sentence in the last paragraph to somethings like this:

 > The last two points in particular mean that <code class="docutils literal"><span class="pre">Delayed</span></code> objects cannot be used for
control flow, meaning that no <code class="docutils literal"><span class="pre">Delayed</span></code> can appear in a loop or if statement. In other words you can't iterate over a `Delayed` object, or use it as part of a condition in an if statement, but `Delayed` object can be used in a body of a loop or if statement (i.e. the example above is fine, but if <code>data</code> was a `Delayed` object it wouldn't be).

**Comment by mrocklin** [comment]
That sounds like a good suggestion.  Can I interest you in submitting a pull request with the change?

**Comment by mrocklin** [comment]
Thanks!
