### ISSUE TITLE
strange notebook import problem

### ISSUE THREAD

**Issue by brendancol** [dask/dask#1347]
Not sure if this is a anaconda-cluster issue or dask issue...

Scenario:

created conda environment and installed dask-distributed and s3fs from conda-forge
opened ipython and import `Executor` just fine
launched jupyter notebook with same environment activated
unable to import `Executor`

**Comment by jcrist** [comment]
That sounds like an environment issue, not a dask issue. Are you sure you're in the same environment? What does:

```
!conda list dask
!conda list distributed
!conda list s3fs
```

display in the notebook?

**Comment by jcrist** [comment]
Closing, as not a dask bug.
