### ISSUE TITLE
Add documentation and example for dask.array.histogram

### ISSUE THREAD

**Issue by dukebody** [dask/dask#1349]
After reading http://stackoverflow.com/questions/38086741/how-to-draw-a-histogram-in-dask I realized we are missing good documentation for `dask.array.histogram`.

http://dask.pydata.org/en/latest/array-api.html#dask.array.histogram:
> dask.array.histogram(a, bins=None, range=None, normed=False, weights=None, density=None)

If `bins` and `range` are required we should specify so.

The example can be taken from @mrocklin answer or pick a simpler/less random one.

**Comment by mrocklin** [comment]
+1
