### ISSUE TITLE
dask.array to dask.dataframe conversion

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1354]
We should be able to easily convert a dask.array of structs to a dask.dataframe.  This came up from someone who wanted to load tabular data from h5py.

**Comment by mrocklin** [comment]
Actually, there is already a dask.dataframe.from_dask_array function.  We should probably create a mate on the dask.array.Array object.

**Comment by postelrich** [comment]
ok I got this!

**Comment by jcrist** [comment]
Fixed by #1440.
