### ISSUE TITLE
Fix and improve map_partitions docs with real examples

### ISSUE THREAD

**Issue by dukebody** [dask/dask#1365]
Current docstring for [`dataframe.map_partitions`](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.Series.map_partitions) contains two examples that are not tested and not very informative.

Moreover the intro text for the second example is wrong:

> When tuple is passed as columns, the result will be Series.

It should be:
> When tuple is passed as columns, the result will be DataFrame.

Let's improve this with some real use case.

See http://stackoverflow.com/questions/31361721/python-dask-dataframe-support-for-trivially-parallelizable-row-apply

**Comment by nirizr** [comment]
+1
map_partitions is really useful doing anything not natively supported by dask, it's usage should be encouraged.

A more specific suggestion: using map_partitions with anything that does not release the GIL will perform poorly with the default thread scheduler. I think users will appreciate a warning :)
