### ISSUE TITLE
Make dd.head(n) and bag.take(n) explore all partitions necessary to get first n results

### ISSUE THREAD

**Issue by dukebody** [dask/dask#1367]
Based on http://stackoverflow.com/questions/38278157/does-npartitions-influence-the-result-of-dask-dataframe-head/38283697 and http://stackoverflow.com/q/38254247/356729, using only the first partition/block to fetch the head drives to unexpected results.

An easy way would be to fetch the first n elements from each partition, concatenate them all and return the first n. Another option would be to fetch n results from first partition and, if they are less than n, fetch from the second, and so on.

Which option sounds better? :)

**Comment by jcrist** [comment]
The second option wouldn't work with a static graph: you'd need multiple calls to compute to iterate through until you found the proper number of rows. As such, I'm not a fan of this option.

The first option would work, but would make `head`/`take` more expensive (imagine reading from many csvs - currently `head` only needs to read one file, changing it would need to read all files). If we were to make this change, I'd expect it to be a keyword argument, and default to the current behavior. Just my opinion though.

**Comment by dukebody** [comment]
I thought about this this morning. What about the following (elaborated first option):

- Add an optional parameter `n_partitions=1`  (defaults to 1, which is current behaviour) to look at when doing head/take.
- If head/take is expected to return n elements but less than n elements were found in the inspected partitions (and there are more partitions), issue a warning: "head/take: Less than {n} elements were found in the first {n_partitions} partitions. Try specifying a larger value for `n_partitions`.

**Comment by mrocklin** [comment]
I like the idea of specifying `npartitions` (it's a nice extension from one vs all).  I like the idea of warning the user.  I think that the user should recompute though, rather than dask.  Generally I think that, when it comes to expensive operations users should opt-in rather than have us do it automatically.

**Comment by nirizr** [comment]
I think an "all partitions" option would be nice. npartitions=-1 perhaps?

**Comment by jcrist** [comment]
I also like the `npartitions` keyword, defaulting to `1`, with `-1` meaning all partitions. This should be fairly straightforward to implement if anyone wants to take it on. Just a map of `head/take/etc...` across the first npartitions, then a concat, then the same `head/take/etc...` again (with a good warning if not enough elements).

**Comment by nirizr** [comment]
I think i'll give it a go if no-one else set his eyes on it

**Comment by jcrist** [comment]
Fixed by #1441.
