### ISSUE TITLE
Add to_bcolz method to dask.dataframe

### ISSUE THREAD

**Issue by jcrist** [dask/dask#1368]
Since we have a `from_bcolz` function, we should add a corresponding `to_bcolz` method.

From https://github.com/dask/dask/pull/1366.

**Comment by nirizr** [comment]
Should this support `ctable` (that's what `from_bcolz` handles currently) only or `carray` as well?

**Comment by mrocklin** [comment]
Perhaps `Series` would map to a `carray`?

**Comment by ankravch** [comment]
I tested in my forked dask environment to_bcolz  (based off to_hdf + https://github.com/visualfabriq/bquery/blob/master/bquery/benchmarks/taxi/load.py) and it seems to work

in dask/dataframe/core.py
def to_bcolz(self, outfile):
    from .io import to_bcolz
    return to_bcolz(self, outfile)

in dask/dataframe/io.py
import bcolz
def _pd_to_bcolz(pd_to_bcolz, lock, args, kwargs=None):
    if lock:
        lock.acquire()
    try:
        if kwargs['mode']=='w':
            pd_to_bcolz(args[0], rootdir=args[1], mode='w') # add expectedlen=outfile_Nrows
        else:
            import_ct = bcolz.ctable(rootdir=args[1], mode='a')
            temp_ct = bcolz.ctable.fromdataframe(args[0])
            import_ct.append(temp_ct)
    finally:
        if lock:
            lock.release()

    return None


def to_bcolz(df, outfile):
    name = 'to-bcolz-' + uuid.uuid1().hex
    pd_to_bcolz = bcolz.ctable.fromdataframe

    kwargs={'mode':'w'}
    dask_kwargs={}
    lock=False
    compute=True
    name_function=None

    fmt_obj = lambda outfile, _: outfile
    if name_function is None: name_function = build_name_function(df.npartitions - 1)
    i_name = name_function(0)


    dsk = dict()
    dsk[(name, 0)] = (_pd_to_bcolz, pd_to_bcolz,
                      lock,
                      [(df._name, 0), fmt_obj(outfile, i_name)],
                      kwargs)


    kwargs2 = kwargs.copy()
    kwargs2['mode'] = 'a'
    for i in range(1, df.npartitions):
        i_name = name_function(i)
        task = (_pd_to_bcolz, pd_to_bcolz, lock,
                [(df._name, i), fmt_obj(outfile, i_name)], kwargs2)

        link_dep = i - 1
        task = (_link, (name, link_dep), task)
        dsk[(name, i)] = task

    dsk = merge(df.dask, dsk)
    keys = [(name, df.npartitions - 1)]

    if compute:
        return DataFrame._get(dsk, keys, get=dask.get, **dask_kwargs)
    else:
        return delayed([Delayed(key, [dsk]) for key in keys])

**Comment by ankravch** [comment]
I tested in my forked dask environment to_bcolz (based off to_hdf +
https://github.com/visualfabriq/bquery/blob/master/bquery/benchmarks/taxi/load.py)
and it seems to work

##in dask/dataframe/core.py
def to_bcolz(self, outfile):
    from .io import to_bcolz
    return to_bcolz(self, outfile)

##in dask/dataframe/io.py
import bcolz
def _pd_to_bcolz(pd_to_bcolz, lock, args, kwargs=None):
    if lock:
        lock.acquire()
    try:
        if kwargs['mode']=='w':
            pd_to_bcolz(args[0], rootdir=args[1], mode='w') # add
expectedlen=outfile_Nrows
        else:
            import_ct = bcolz.ctable(rootdir=args[1], mode='a')
            temp_ct = bcolz.ctable.fromdataframe(args[0])
            import_ct.append(temp_ct)
    finally:
        if lock:
            lock.release()

    return None


def to_bcolz(df, outfile):
    name = 'to-bcolz-' + uuid.uuid1().hex
    pd_to_bcolz = bcolz.ctable.fromdataframe

    kwargs={'mode':'w'}
    dask_kwargs={}
    lock=False
    compute=True
    name_function=None

    fmt_obj = lambda outfile, _: outfile
    if name_function is None: name_function =
build_name_function(df.npartitions - 1)
    i_name = name_function(0)


    dsk = dict()
    dsk[(name, 0)] = (_pd_to_bcolz, pd_to_bcolz,
                      lock,
                      [(df._name, 0), fmt_obj(outfile, i_name)],
                      kwargs)


    kwargs2 = kwargs.copy()
    kwargs2['mode'] = 'a'
    for i in range(1, df.npartitions):
        i_name = name_function(i)
        task = (_pd_to_bcolz, pd_to_bcolz, lock,
                [(df._name, i), fmt_obj(outfile, i_name)], kwargs2)

        link_dep = i - 1
        task = (_link, (name, link_dep), task)
        dsk[(name, i)] = task

    dsk = merge(df.dask, dsk)
    keys = [(name, df.npartitions - 1)]

    if compute:
        return DataFrame._get(dsk, keys, get=dask.get, **dask_kwargs)
    else:
        return delayed([Delayed(key, [dsk]) for key in keys])

**Comment by ankravch** [comment]
ok, here is a test 

(dask_dev) [akravchenko@hnode1 ~]$ ipython
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.

In [1]: import dask.dataframe as dd

In [2]: import pandas as pd

In [3]: import numpy as np

In [4]: import random, bcolz

In [5]:

In [5]: t0=pd.DataFrame({'v0':np.random.randint(0,1000,(1000000,))})

In [6]: t0_d = dd.from_pandas(t0, npartitions=10)

In [7]: t0_d
Out[7]: dd.DataFrame<from_pa..., npartitions=10, divisions=(0, 100000, 200000, ..., 900000, 999999)>

In [8]: t0_d.to_bcolz(r'/mnt/outfile.bcolz')
Out[8]: (None,)

In [9]: t1 = dd.from_bcolz(r'/mnt/outfile.bcolz', blocksize=1000000, lock=False)

In [10]: t1
Out[10]: dd.DataFrame<from_bc..., npartitions=31, divisions=(0, 32768, 65536, ..., 983040, 999999)>

In [11]:

**Comment by ankravch** [comment]
ok, here is a test

(dask_dev) [akravchenko@hnode1 ~]$ ipython
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.
In [1]: import dask.dataframe as dd

In [2]: import pandas as pd

In [3]: import numpy as np

In [4]: import random, bcolz

In [5]:

In [5]: t0=pd.DataFrame({'v0':np.random.randint(0,1000,(1000000,))})

In [6]: t0_d = dd.from_pandas(t0, npartitions=10)

In [7]: t0_d
Out[7]: dd.DataFrame<from_pa..., npartitions=10, divisions=(0, 100000,
200000, ..., 900000, 999999)>

In [8]: t0_d.to_bcolz(r'/mnt/outfile.bcolz')
Out[8]: (None,)

In [9]: t1 = dd.from_bcolz(r'/mnt/outfile.bcolz', blocksize=1000000,
lock=False)

In [10]: t1
Out[10]: dd.DataFrame<from_bc..., npartitions=31, divisions=(0, 32768,
65536, ..., 983040, 999999)>

**Comment by ankravch** [comment]
ok, I think my current version of to_bcolz does not work correctly, here is
my test on a single machine:

import dask.dataframe as dd
import bcolz, dask
from dask.distributed import Executor, progress
from dask.diagnostics import ProgressBar

dgn_table = dd.from_bcolz(r'/mnt/nfs/test_dgn_pb_200M.bcolz',
blocksize=1000000, lock=False)
dgn_finder = dd.from_bcolz(r'/mnt/nfs/test_dgn9_finder_2.bcolz',
blocksize=1000000, lock=False)

[########################################] | 100% Completed | 31.2s
[########################################] | 100% Completed |  0.1s


#* ~200% (out of 400) CPU is used*
t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0.to_hdf(r'/mnt/nfs/test_tohdf_link_5.h5', 'test',
format='table', mode='w'))

[########################################] | 100% Completed |  2min 21.5s

*# only ~100% (out of 400) CPU is used*

t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0.to_bcolz(r'/mnt/nfs/test_tobcolz_link_5.bcolz'))

[########################################] | 100% Completed |  2min 14.1s

**Comment by ankravch** [comment]
when I run with get=dask.async.get_sync:

join+to_hdf, cpu ~200% (out of 400)
t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0.to_hdf(r'/mnt/nfs/test_tohdf_link_5.h5', 'test',
format='table', mode='w'), get=dask.async.get_sync)

[########################################] | 100% Completed |  2min 22.1s


only join, cpu usage ~100%  (out of 400)

res=dask.compute(t0.count(),get=dask.async.get_sync)

[########################################] | 100% Completed |  1min 53.2s
(CLAIMNO    71303395
dtype: int64,)


join+to_bcolz, cpu usage ~100% (out of 400)

t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0.to_bcolz(r'/mnt/nfs/test_tobcolz_link_5.bcolz'),
get=dask.async.get_sync)

[########################################] | 100% Completed |  2min 13.4s


I guess my question is how join+to_hdf (in dask.async.get_sync mode)
makes 200% CPU ?

**Comment by ankravch** [comment]
using dask.dataframe and dumping output dataframe in ram
t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0, get=dask.async.get_sync)
print (res[0])

[########################################] | 100% Completed |  1min 53.2s
(71303395, 1)


and than using pandas to save dask output dataframe (res[0]) as h5/bcolz:

res[0].to_hdf(r'/mnt/nfs/test_res.h5', 'test', format='table', mode='w')

0:01:10.806566


res[0].to_hdf(r'/mnt/nfs/test_res.h5', 'test', mode='w') # cons -
cannot load back to dask.dateframe

0:00:03.216095


bcolz.ctable.fromdataframe(res[0], rootdir=r'/mnt/nfs/test_res.bcolz')

0:00:01.696645


Ideally I would want to see dask to_bcolz function

that preserves ~same performance (as bcolz.ctable.fromdataframe using
pandas) and and uses available ram wisely. Do you think it's doable?

**Comment by ankravch** [comment]
ok, here is a follow up
t0=dd.merge(dgn_table[['DGN','CLAIMNO']], dgn_finder, on='DGN',
how='inner')[['CLAIMNO']]
res=dask.compute(t0, get=dask.async.get_sync)
print (res[0].shape)

back to dask.dateframe
dres = dd.from_pandas(res[0], npartitions=1)
dres.to_hdf(r'/mnt/nfs/test_res.h5', 'test', format='table', mode='w')

[########################################] | 100% Completed | 31.5s


dres.to_bcolz(r'/mnt/nfs/test_res.bcolz')

[########################################] | 100% Completed |  2.9s


dask to_bcolz performs acceptable, but it brings me back to the
original question:

dask join+to_hdf, cpu ~200% (out of 400), runtime=2min 22s

dask join+to_bcolz, cpu usage ~100% (out of 400), run time=2min 13s

how join+to_hdf (in dask.async.get_sync mode) makes 200% CPU

**Comment by sfragosorodrig** [comment]
any updates on the to_bcolz functionality?

**Comment by mrocklin** [comment]
To the best of my knowledge this issue is up to date.  Is this something that you would like to take on @sfragosorodrig ?

**Comment by mrocklin** [comment]
Are people still using bcolz?  Most people I interact with today use Parquet, which since the opening of this issue has grown a couple of good reader/writers in Python.  I'm going to close this now.  If this is still an active issue then please ping and I'll reopen.  However I suspect that bcolz my become out-of-scope for dask.dataframe in the future due to low usage.
