### ISSUE TITLE
Cannot import name visualize

### ISSUE THREAD

**Issue by JamesRamm** [dask/dask#1372]
I am getting the following error:

```
>>> from dask.diagnostics import visualize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name visualize

```

The documentation suggests the above should be possible: http://dask.pydata.org/en/latest/diagnostics.html#example

I have bokeh etc installed. 
Any idea?

This is dask 0.10.1

**Comment by mrocklin** [comment]
from dask import visualize

Make sure that you have `graphviz` installed.  Both the system library and the Python library.

**Comment by JamesRamm** [comment]
Fixed by installing `toolz`

Can those dependencies be documented? Potentially not easy for a newbie to track down as it passes on the ImportError when a dependency for visualise isnt installed

**Comment by mrocklin** [comment]
You probably want to install dask using either of the following:

    conda install dask -c conda-forge
    or
    pip install dask[complete]

Installation is complex because different people want to avoid certain dependencies (some downstream libraries don't want Pandas for example).  See http://dask.pydata.org/en/latest/install.html#pip

**Comment by nirizr** [comment]
Perhaps we can add dask[visualize] or dask[diagnostics]?

**Comment by mrocklin** [comment]
I'm slightly concerned about `dask[foo]` blowup.  I think that for more fringe libraries like `graphviz` we should just rely on informative exceptions.

**Comment by bryevdv** [comment]
perhaps these would be useful: 

https://github.com/bokeh/bokeh/blob/master/bokeh/util/dependencies.py
