### ISSUE TITLE
Implement DataFrame.coalesce 

### ISSUE THREAD

**Issue by frol** [dask/dask#1381]
I would love to use repartition of DataFrames without having to set index (#1380), yet even simple `coalesce` (merging some partitions together without a need to shuffle/rebalance partitions, like it is done in PySpark) would work in my use-case.

Can this be easily done in Dask? Please, advise where to look for the inspiration (I'm currently trying to get a sense of how `repartition` and `set_index` are done, though it is said that they are quite complex and still not complete for distributed use while `coalesce` should be much easier to implement).

**Comment by mrocklin** [comment]
Just to make sure I understand, you're looking to do this on dataframes for which divisions are not known, correct?  If you are interested in contributing a solution for dask.dataframe then you might take a look at `dask.bag.Bag.repartition` which solves a very similar problem.

**Comment by frol** [comment]
Correct. Thank you, I will take a look there.
