### ISSUE TITLE
MemoryError : Dask DataFrame .apply

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#1385]
I am running .apply on a dask dataframe with 8 partitions and observe the following.
Does this indicate I am out of disk space, the systems (Windows10) shows a python out of memory error and the systems is not functional with a reboot.

C:\p\x1\lib\dask\async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    482                 _execute_task(task, data)  # Re-execute locally
    483             else:
--> 484                 raise(remote_exception(res, tb))
    485         state['cache'][key] = res
    486         finish_task(dsk, key, state, results, keyorder.get)

MemoryError: 
## Traceback

  File "C:\p\x1\lib\dask\async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "C:\p\x1\lib\dask\async.py", line 248, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]

**Comment by mrocklin** [comment]
Yeah, probably you have too much data in RAM.  You could try using smaller/more partitions.

**Comment by apiszcz** [comment]
Thank you. Where does DASK store temporary and intermediate files?

**Comment by mrocklin** [comment]
Dask only stores intermediate data in memory.  It manages larger-than-memory computation by streaming through the input intelligently and removing intermediate data as quickly as possible.  For computations that require shuffles it does use a temporary file, but this is uncommon.

Perhaps if you include a minimal failing example that fails for you then we can help to identify what your bottleneck is.

**Comment by apiszcz** [comment]
The entire dataframe fits in memory, ~5GB, after adding the two additional
columns it becomes a 7.9GB pkl file. The system has 32GB memory, about 27GB
free

**Comment by mrocklin** [comment]
Without more information about what you're doing I'm not sure how I can help you

**Comment by apiszcz** [comment]
import dask.dataframe as dd
import numpy as np
import pandas as pd
from pyproj import Proj, transform
inProj = Proj(init='epsg:4326')
outProj = Proj(init='epsg:3857')

def wgs84_2_webmercator2(row):
    xwm,ywm = transform(inProj,outProj,row['lon'],row['lat'])
    return pd.Series([xwm,ywm])

%time df=pd.read_pickle(r'D:\nyc_taxi\trip_data_pickup_pd.pkl')

mask=((df['lat']>-90.0) & (df['lat']<90.0) & (df['lon']>-180.0) &
(df['lon']<180.0) )
df=df[mask]

df['xwm']=1.0
df['ywm']=1.0
df['idx']=df.index

ddf = dd.from_pandas(df, npartitions=8)
ddf[['xwm','ywm']]=ddf.apply(wgs84_2_webmercator2,columns=['lon','lat'],axis=1)
%time ddf.compute()

**Comment by mrocklin** [comment]
And does that work with just pandas if you don't use dask.dataframe?

**Comment by mrocklin** [comment]
Ping.

**Comment by apiszcz** [comment]
The call I used was:

%time df[['xwm','ywm']]=df.apply(wgs84_2_webmercator,axis=1)

**Comment by mrocklin** [comment]
And that works fine in pandas, yes?

**Comment by apiszcz** [comment]
yes, it is working, what I am using for now.

**Comment by jcrist** [comment]
Closing for now as stale. Feel free to reopen if the issue persists and you can provide a reproducible example.
