### ISSUE TITLE
Working with collections (docs clarification)

### ISSUE THREAD

**Issue by wikiped** [dask/dask#1389]
There is  an example in [Working with collections](https://dask.readthedocs.io/en/latest/delayed-collections.html#working-with-collections) section:

    import dask.dataframe as dd
    from dask.delayed import delayed

    from my_custom_library import load, save

    filenames = ...
    dfs = [delayed(load)(fn) for fn in filenames]

    df = dd.from_delayed(dfs)
    df = ... # do work with dask.dataframe

    dfs = df.to_delayed()
    writes = [delayed(save)(df, fn) for df, fn in zip(dfs, filenames)]

    dd.compute(*writes)

This might be a naive question, but does the fact that `dask` will perform the tasks asynchronously mean that operations in `writes` ___might___ result in having content from one file ending up in another file after all previous processing?

I am trying to use this scheme and need to carry along the process information about the files the data came from.

One way to ensure that is to attach this info to `pandas.DataFrame`'s metadata, but it is getting lost once `pandas.DataFrame` becomes part of `dask.dataframe`.

Using `zip(dfs, filenames)` approach (as in the example) seems to be the easiest, but there is this concern about the effect of asynchronous processing...

Thanks in advance for any clarification.

**Comment by nirizr** [comment]
Actually, I think you are correct.

That depends on what's done in `df = ... # do work with dask.dataframe`.

Things could notably messy with operations reducing the number of partitions. That will keep some of the files with their original data, creating duplication and other potential strange effects.

I think those examples are not intended as bullet-proof code snippets, but as a way to present a clear and simple higher view of functionality.

**Comment by nirizr** [comment]
Some sort of disclaimer might be in order, i suspect this might exist in various locations throughout the docs.

**Comment by wikiped** [comment]
@nirizr Thank you. Do I understand correctly that if nothing was done between

`dfs = [delayed(load)(fn) for fn in filenames]` 

and 

`writes = [delayed(save)(df, fn) for df, fn in zip(dfs, filenames)]` 

everything should be in order?

I.E. If `filename[0]` was process the last it will be still at index `[0]` of resulting `dfs` list?

**Comment by nirizr** [comment]
Yes, you are correct.

Some dask.dataframe operations change the internal layout of partitions. If this happens the example will break, but those operations are usually explicit (because they also tend to be performance heavy).

Without doing any reindexing/repartitioning/etc, the first partition will remain the pandas dataframe created by the first `load` call.

**Comment by wikiped** [comment]
Thanks, again for clarifying this.
