### ISSUE TITLE
dtype and shape don't match for empty arrays

### ISSUE THREAD

**Issue by jcrist** [dask/dask#1398]
Currently if an array is empty, we just return `np.empty(0)`, which has a dtype `f8`. This means that dtype of the output won't match for other dtypes. Further, you can have "empty" arrays with `shape != ()` as long as one of the dimensions is `0` (e.g. `shape=(0, 10, 10)`).

The `da.Array` objects have the necessary metadata to create empty arrays with the appropriate dtype/shape, but these aren't passed on to `_finalize`. One solution for this would be to make `_finalize` a property, and return a partial with the metadata if the output is known to be empty. This slightly complicates the implementation, but isn't too bad. I'll do it here:

``` python
def finalize_empty(shape, dtype, res):
    return np.empty(shape, dtype=dtype)

class Array(Base):
    ...
    @property
    def _finalize(self):
        if self.shape or 0 not in self._shape:
            return finalize
        return partial(finalize_empty, self.shape, self.dtype)
```

This would solve the issue and is (I think) pretty simple, but I'll open it here for discussion. This also might be a non-issue, as we might not care if the metadata matches for empty arrays.

**Comment by mrocklin** [comment]
It's worth pointing out that this kind of thing has come up before and that we might want finalize to take some (easily serializable) metadata by default.

**Comment by jcrist** [comment]
Indeed. Perhaps an (optional) property `_finalize_args` to be passed in after the results. So `finalize` would be `finalize(results, *finalize_args)`. This is related to #1068, and should probably be solved together.

**Comment by mrocklin** [comment]
```python
In [15]: x = da.ones(5, chunks=(5,), dtype='int8')

In [16]: x[:0]
Out[16]: dask.array<getitem, shape=(0,), dtype=int8, chunksize=(0,)>

In [17]: x[:0].compute()
Out[17]: array([], dtype=int8)

```
