### ISSUE TITLE
Benchmarking `read_csv`

### ISSUE THREAD

**Issue by stefanseefeld** [dask/dask#1401]
I've been running some experiments with dask's `read_csv()` function (`dask.dataframe.read_csv()`), using different file and block sizes.
Attached is a benchmark I'm using (which calls this function via `blaze`'s `data()` function. The timing varies quite a bit, so a more careful measurement may be needed. However, it shows that the current default blocksize may not be optimal.

The attached plot was generated on my quadcore laptop (8GB, 8 logical cores).
![read_csv](https://cloud.githubusercontent.com/assets/1243351/17066889/202d868c-5017-11e6-9942-d292122970f0.png)

**Comment by stefanseefeld** [comment]
Here is the benchmark code (sorry, github wouldn't let me attach a .py file :-( ):
--------------------
#! /usr/bin/env python

from __future__ import print_function, division, absolute_import
import time
import blaze as bz
import os

"""
CSV input files were created with this snippet:

---------------------------------------------------------
#!/usr/bin/env python

import sys

outfile = 'test8.csv'
size = 1024*1024*32

with open(outfile, 'w+') as out:
    print('idx,amount,two,three', file=out)
    for i in range(size):
        print('{},{},{},{}'.format(i, i, i, i), file=out)
---------------------------------------------------------

"""

def generate_input(size):
    
    return ('test{}.csv'.format(size),)

def dask_csv(filename, blocksize=None):

    if blocksize:
        blocksize = blocksize * 1024*1024 # MB
    comfortable_size = os.path.getsize(filename) - 1 # just too small...
    t = bz.data(filename)
    before = time.perf_counter()
    r = bz.compute(t['amount']*2, comfortable_memory=comfortable_size, blocksize=blocksize, return_type='core')
    after = time.perf_counter()
    del r
    return after - before


if __name__ == '__main__':

    format='%24s %24s %24s %24s %24s %24s'
    print("# Benchmark: bz.compute(t['amount']*2")
    print(format%('size', 'default', '8MB', '16MB', '32MB', '64MB'))
    for s in range(1,8):
        d0 = dask_csv(*generate_input(s))
        d1 = dask_csv(*generate_input(s), blocksize=8)
        d2 = dask_csv(*generate_input(s), blocksize=16)
        d3 = dask_csv(*generate_input(s), blocksize=32)
        d4 = dask_csv(*generate_input(s), blocksize=64)
        print(format%(s, d0, d1, d2, d3, d4))

**Comment by mrocklin** [comment]
This is great.  I highly encourage benchmarks like this.

How did file size vary in these tests?  I see that `test8.csv` was 32 million rows.  What about the others?  I'm also somewhat curious how this works on real data.  I may try this out on the NYCTaxi data in a while.

It's interesting that the performance difference diminishes for larger files.  

Still, at first glance this is fairly strong evidence that we should reduce our block sizes.

**Comment by stefanseefeld** [comment]
Sorry for the lack of clarity. Yes, I used exponential scaling (though I just notice that somehow my scale is slightly off. It's approximately "test<n>.csv" -> 2**(18+<n>) )

**Comment by mrocklin** [comment]
OK, so the flat scaling that we're seeing towards the beginning may just be because the blocksize is as large or larger than the filesize, so parallelism is able to kick in sooner for smaller chunksizes.

**Comment by stefanseefeld** [comment]
Indeed. (Notice that in this benchmark I'm forcing the dask backend, while in actual end-user code there is an additional dispatch that only picks dask as backend for larger files. But that's more relevant to blaze users than dask...)

**Comment by mrocklin** [comment]
This was a nice benchmark.  It looks like convesation is over.  Closing.
