### ISSUE TITLE
dd.sort method

### ISSUE THREAD

**Issue by ankravch** [dask/dask#1414]
I wonder how much work would it require to implement dask.dataframe.sort(...) method?  

P.S. At moment I am saving intermediate results to a large (~500M rows, ~200 columns) h5 table and using PyTables to sort it. Dumping to h5 on disk takes time...
I was thinking to use bcolz to dump on disk quickly, but bcolz.ctable does not have a sort method yet.

**Comment by mrocklin** [comment]
You can use `set_index` to achieve this if you like but it will also take time and it will also dump to disk.

There really isn't any way to sort a larger-than-memory dataset without dumping to disk.

**Comment by ankravch** [comment]
I would need to sort by more then one column with ascending/descending option for each column. 
Do you think all available CPU would be used if sort method was implemented in dask?

**Comment by mrocklin** [comment]
I think that sorting larger-than-memory data will likely be bound by disk I/O.  Dask.dataframe is probably not the best tool to do what you want to do here.

**Comment by ankravch** [comment]
Another way I could try to do it is to strip columns that has to be sorted + index (those should fit in memory). And after sorting is done - join sorted table with unsorted wide table on index variable. Though I am not sure how much stress it would be for dask to join 500M by 500M...

**Comment by ankravch** [comment]
Given data that fits in-memory, do you think dask could leverage all CPU cores if it had a sort method ?

**Comment by mrocklin** [comment]
If your data fits in memory then I would just use Pandas
