### ISSUE TITLE
create a new column on existing dataframe

### ISSUE THREAD

**Issue by ankravch** [dask/dask#1426]
I wonder if one could create a new column on existing dask dataframe
```python
In [1]: %paste
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: t0=pd.DataFrame({'v0':[i for i in range(1000000)]})

In [4]: t0['v1']=[i for i in range(1000000)]

In [5]: t0.head()

## -- End pasted text --
Out[1]:
   v0  v1
0   0   0
1   1   1
2   2   2
3   3   3
4   4   4

In [2]: t0_d = dd.from_pandas(t0, npartitions=10)

In [3]: t0_d['v2']=[i for i in range(1000000)]

In [4]: t0_d.head()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-4b106fba7c25> in <module>()
----> 1 t0_d.head()

/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in head(self, n, compute)
    380
    381         if compute:
--> 382             result = result.compute()
    383         return result
    384

/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     84             Extra keywords to forward to the scheduler ``get`` function.
     85         """
---> 86         return compute(self, **kwargs)[0]
     87
     88     @classmethod

/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180
    181     results_iter = iter(results)

/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58
     59     return results

/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    482                 _execute_task(task, data)  # Re-execute locally
    483             else:
--> 484                 raise(remote_exception(res, tb))
    485         state['cache'][key] = res
    486         finish_task(dsk, key, state, results, keyorder.get)

ValueError: Length of values does not match length of index

Traceback
---------
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/array/core.py", line 2087, in partial_by_order
    return function(*args2, **kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 2047, in _assign
    return df.assign(**kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2527, in assign
    data[k] = v
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2423, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2578, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/pandas/core/series.py", line 2770, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
```

**Comment by jcrist** [comment]
Dask only supports adding new columns as `dd.Series` objects. Adding data that already exists in memory shouldn't be a common use case, as dask is meant for out-of-core/distributed data. We should probably add a check so this errors on the assignment (with a good error message).

**Comment by ankravch** [comment]
The use case I am thinking about is shown below as a pseudocode
```python
## use wild star to read a stack of bcolz files
stack_of_files_dd = dd.from_bcolz('stack_of_files_*.bcolz', chunksize=1000000, lock=False) 

## add 'global_id' column to the existing dask dataframe
stack_of_files_dd['global_id'] = [i for i in range(stack_of_files_dd.divisions+1)] 

## select only few variables to query data  
slim_stack_to_query_dd =  stack_of_files_dd[['global_id', 'used_var1',  'used_var2',..., 'used_var20']] 

## run_query(various joins and cuts) on slim_stack_to_query_dd
skimmed_dd = run_query(slim_stack_to_query_dd) 

## in-memory sort by 'used_var1',  'used_var2' in pandas
skimmed_and_sorted = skimmed_dd[['global_id', 'used_var1',  'used_var2']].to_pandas().sort(...) 

## once all done, join selected rows with the former stack_of_files_dd on 'global_id'
dd.merge(stack_of_files_dd, skimmed_and_sorted[['global_id']], on='global_id', how='inner')[keep_columns_list].to_hdf('skimmed_data.h5','/skim')
```
P.S. If a single new column does not fit in-memory, could we append it (to existing dask dataframe) chunk by chunk from disk or just throw a good error message?

**Comment by jcrist** [comment]
> `stack_of_files_dd['global_id'] = [i for i in range(stack_of_files_dd.divisions+1)] `

`divisions` is a tuple, so that won't actually work. If you mean `npartitions`, then the added column won't have the proper length (it'd be as long as the number of partitions, not the length of the data). Since there's no way to know the total length of a dataframe (and dask.dataframe is intended for data that you wouldn't want to all have in memory on a single computer anyway) I don't think we should support assignment of an in-memory column.

 I assume what you want is a different id for data in each file in the glob. One way to do this would be to assign an id by broadcasting a scalar (as done in pandas):

```
df['global_id'] = 12345
```

So your code would then be:

```python
frames = []
for i, file in enumerate(glob('stack_of_files_*.bcolz')):
    df = dd.from_bcolz(file, chunksize=1000000, lock=False)
    df['global_id'] = i
    frames.append(df)

df = dd.concat(frames)
```

This is currently supported, and should work fine.

> P.S. If a single new column does not fit in-memory, could we append it (to existing dask dataframe) chunk by chunk from disk or just throw a good error message?

If you have a single new column that doesn't fit in memory, create it as a `dask.Series`, and assign it the normal way (`df['col'] = some_dask_series`).

**Comment by ankravch** [comment]
There was a typo (fixed now). Though I am not sure I understand 'Since there's no way to know the total length of a dataframe':

```python
In [1]: import dask.dataframe as dd

In [2]: import bcolz

In [3]: N=int(1e7)

In [4]: ct=bcolz.fromiter(((i,i) for i in range(N)), dtype="i8,i8",count=N, rootdir='foo.bcolz')

In [5]: ct_table = dd.from_bcolz('foo.bcolz', chunksize=1000000, lock=False)

In [6]: ct_table.divisions[-1]+1
Out[6]: 10000000
```

**Comment by jcrist** [comment]
Dask dataframes keep their index divisions as metadata (the `divisions` attribute). The last element in `divisions` (if they are known) *may* be length, but it doesn't have to be. Example:

```python
In [22]: df = pd.DataFrame({'a': range(5)}, index=[1, 1, 1, 2, 3])

In [23]: ddf = dd.from_pandas(df, npartitions=2)

In [24]: ddf.divisions
Out[24]: (1, 2, 3)
```

If the divisions are both *known* and known to be *monotonically increasing*, then you could create an index out-of-core using `da.arange` (to create an index), and `dd.from_dask_array` to convert to a series.

```python
In [27]: df = pd.DataFrame({'a': map(float, range(100)), 'b': range(100, 200)})

In [28]: ddf = dd.from_pandas(df, npartitions=5)

In [29]: import dask.array as da

In [30]: a = da.arange(ddf.divisions[-1] + 1, chunks=ddf.divisions[1:])

In [31]: ddf['id'] = dd.from_dask_array(a)

In [32]: ddf.head()
Out[32]:
     a    b  id
0  0.0  100   0
1  1.0  101   1
2  2.0  102   2
3  3.0  103   3
4  4.0  104   4
```
Reiterating, this is only valid if you know the divisions are representative of the length.

**Comment by ankravch** [comment]
>Reiterating, this is only valid if you know the divisions are representative of the length.

right, that's my use case

P.S. For other cases I would do something like ddf.count().compute()[0] to get a total length of dask dataframe.

**Comment by jcrist** [comment]
> P.S. For other cases I would do something like ddf.count().compute()[0] to get a total length of dask dataframe.

Yes, that also works, but it can't be done without computing the graph up to that point, which is best to avoid if possible.

Does this solve your issue?

**Comment by ankravch** [comment]
>Yes, that also works, but it can't be done without computing the graph up to that point, which is best to avoid if possible.
right, I could run it as a subprocess and wait until it's finished, and then start a real computing with dask.

>Does this solve your issue?
yep, thanks alot for discussion, it was helpful!

**Comment by AlexS12** [comment]
I think this issue is related to the problem I am experiencing. I have the following python code using pandas:
```
import pandas as pd
import numpy  as np

time = np.linspace(0, 10, 101)
x = np.sin(time)
df = pd.DataFrame(x, index=time)

window_ = 5
df['__group__'] = np.arange(len(df)) // window_
df.groupby('__group__')
```

Basically I create a column group in order to make the groupby on consecutive elements.
Using a dask data frame instead directly does not work: `TypeError: Column assignment doesn't support type ndarray` which I can understand. I have tried to create a dask array instead but as my `divisions` are not representative of the length I don't know how to determine the chunks.

Is there any way to create a new column like the one I want? Is that even possible?

**Comment by TomAugspurger** [comment]
It probably isn't the fastest, but

```python
df['group'] = df['group'].assign(__group__ = laaambd x: np.arange(len(x)) // window_)
```

may work for you.

**Comment by AlexS12** [comment]
Finally this one worked for me:
`df = df.assign(__group__=lambda x: np.arange(len(x)) // window_)`
thanks a lot!

**Comment by sheetalanns-blume** [comment]
Convert list to pd.Series, and then assign the series. The below code should work:

t0_d['v2'] = pd.Series([i for i in range(1000000)])
