### ISSUE TITLE
slice by list loses chunking

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#1430]
If you slice an array by list of indices on a chunked axis, you end up with a single, big chunk.
This is problematic because you may not have enough memory to store that single chunk, and it may not be feasible/efficient to chunk on a different axis.

``` python
>> import dask.array as da
>> a = da.ones(20, chunks=5)
>> b = a[[2,3,1,15,15,15,15,15,15]]
>> b.chunks
((9,),)
```

A more sensible, conservative algorithm could be:
1. every output chunk takes in input exactly one input chunk. This will typically produce output chunks that are smaller than the input chunks
2. every output chunk can be at most as large as the largest of the input chunks (it may happen in case of repetitions in the index).

In the above example, this algorithm would have produced chunks `((3, 5, 1), )`

**Comment by crusaderky** [comment]
This PR does the right think when the index is a da.Array: https://github.com/dask/dask/pull/3407
Similar logic could be applied to a np.array / list index.

**Comment by mrocklin** [comment]
```python
In [1]: import dask.array as da
   ...: a = da.ones(20, chunks=5)
   ...: b = a[[2,3,1,15,15,15,15,15,15]]
   ...: b.chunks
   ...: 
Out[1]: ((3, 6),)
```
