### ISSUE TITLE
dd.from_bcolz() read performance

### ISSUE THREAD

**Issue by ankravch** [dask/dask#1432]
It looks like dd.from_bcolz(...)[['single_column']] object is reading all columns first (every time when dask.dataframe is used) and then selects a single column

``` python
ct_wide_read = dd.from_bcolz('wide_table_10M.bcolz', chunksize=1000000, lock=False, categorize=False)
%time ct_wide_read[['f1']].head() 
Wall time: 21.5 s

ct_thin_read = dd.from_bcolz('thin_table_10M.bcolz', chunksize=1000000, lock=False, categorize=False)
%time ct_thin_read[['f1']].head() 
Wall time: 2.6 s
```

From a pure bcolz

``` python
%time ct_wide_ = bcolz.ctable(rootdir='wide_table_10M.bcolz')
Wall time: 4.23 s

%time ct_wide_['f1'][:10]
Wall time: 1ms

%time ct_thin_ = bcolz.ctable(rootdir='thin_table_10M.bcolz')
Wall time: 431 ms

%time ct_thin_['f1'][:10]
Wall time: 1ms
```

**Comment by mrocklin** [comment]
You can pass a bcolz ctable directly into the from_bcolz function

```python
ct_wide_ = bcolz.ctable(rootdir='wide_table_10M.bcolz')
ct = ct_wide_[['list', 'of', 'columns', 'I', 'want']]

df = dd.from_bcolz(ct)
```

**Comment by mrocklin** [comment]
Can this be closed?  Are you interested in creating a PR to provide a `columns=` keyword argument to `from_bcolz`?

**Comment by ankravch** [comment]
Your solution is fairly good, it reduces a run time by 50x - from reading 999 columns of garbage, to 19 columns of garbage.  

Sure, I will create a PR to add columns= keyword to from_bcolz. It should improve the run time further by ~5x if we read exactly those columns that we asked for.
