### ISSUE TITLE
Applying array functions to a Series loses chunk information

### ISSUE THREAD

**Issue by ibab** [dask/dask#1435]
Does dask support calling `dask.array` functions on a `Series`?
Although evaluating the resulting array seems to work, there's no chunk information on it, so calling `len` on the array fails.
Here's a minimal example that demonstrates the problem:

``` python
import pandas as pd
import dask.array as da
from dask.dataframe import from_pandas

df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
df = from_pandas(df, chunksize=2)

out = da.cos(df['x'])
print(out.chunks) # ==> ()
print(len(out))
```

```
Traceback (most recent call last):
  File "run1.py", line 12, in <module>
    print(len(out))
  File "/usr/lib/python3.4/site-packages/dask/array/core.py", line 831, in __len__
    return sum(self.chunks[0])
IndexError: tuple index out of range
```

**Comment by mrocklin** [comment]
Calling dask.array functions on dask.dataframe objects is not supported.

**Comment by ibab** [comment]
Are there difficulties with supporting `dask.array` and `dask.dataframe` interop, or is this something that might be added in the future?
Being able to call array functions on `Series` objects and assigning them back into a `DataFrame` would be quite useful, as this is something I often do with pandas DataFrames.
I can have a look at writing a PR if there's interest in adding this functionality to `dask`.

**Comment by mrocklin** [comment]
I think that the most straightforward way of doing this is to recreate the elementwise functions like `sin, cos, exp` as dask.dataframe functions using elemwise.  

This involves a bit of code duplication but should be fairly straightforward.

I recommend looking at `dask.dataframe.core.DataFrame.isin` for an example on how to use `dask.dataframe.core.elemwise` and at how `dask.array.core.wrap_elemwise` gets used to implement `dask.array.{sin,cos,exp, ...}`.

**Comment by shoyer** [comment]
`dask.dataframe` and `dask.array` use different internal models for partitioning (index based vs position based), so it's not so straightforward to convert back and forth.

**Comment by jcrist** [comment]
`dask.dataframe` now supports calling `dask.array` ufuncs on series/dataframe objects. These return a `dask.dataframe` object mirroring the numpy/pandas behavior:

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: import dask.array as da

In [4]: import dask.dataframe as dd

In [5]: df = pd.DataFrame({'x': [1, 2, 3, 4]})

In [6]: ddf = dd.from_pandas(df, npartitions=2)

In [7]: res = da.cos(ddf.x)

In [8]: res
Out[8]:
Dask Series Structure:
npartitions=2
0    float64
2        ...
3        ...
Name: x, dtype: float64
Dask Name: cos, 6 tasks

In [9]: res.compute()
Out[9]:
0    0.540302
1   -0.416147
2   -0.989992
3   -0.653644
Name: x, dtype: float64

In [10]: np.cos(df.x)
Out[10]:
0    0.540302
1   -0.416147
2   -0.989992
3   -0.653644
Name: x, dtype: float64

In [11]: res = da.cos(ddf)

In [12]: res
Out[12]:
Dask DataFrame Structure:
                     x
npartitions=2
0              float64
2                  ...
3                  ...
Dask Name: cos, 4 tasks

In [13]: res.compute()
Out[13]:
          x
0  0.540302
1 -0.416147
2 -0.989992
3 -0.653644

In [14]: np.cos(df)
Out[14]:
          x
0  0.540302
1 -0.416147
2 -0.989992
3 -0.653644
```

Closing.
