### ISSUE TITLE
DataFrame from bag of sequence of dicts can only infer columns from first dict

### ISSUE THREAD

**Issue by dwyatte** [dask/dask#1448]
When creating a dask DataFrame from a bag pointing to a sequence of dicts, columns are only computed based on the first dict in the sequence. It would be great if the DataFrame constructor could normalize the keys across the sequence, which is consistent with the way the pandas DataFrame constructor works.

Here is some simple test code:

``` python
import pandas as pd
import dask.bag as db

N_seq = 8

seq = [{str(i): i} for i in range(N_seq)]
b = db.from_sequence(seq)

print '-'*80
print 'Sequence'
print seq
print

print 'Dask dataframe with column inference'
print b.to_dataframe().compute()
print

print 'Dask dataframe with column specification'
print b.to_dataframe(columns=[str(i) for i in range(N_seq)]).compute()
print

print 'Pandas dataframe with column inference'
print pd.DataFrame(seq)
print

seq = [{str(i): i} for i in range(N_seq)]
seq[0]['1'] = 1
b = db.from_sequence(seq)

print '-'*80
print 'Sequence'
print seq
print

print 'Dask dataframe with column inference'
print b.to_dataframe().compute()
print

print 'Dask dataframe with column specification'
print b.to_dataframe(columns=[str(i) for i in range(N_seq)]).compute()
print

print 'Pandas dataframe with column inference'
print pd.DataFrame(seq)
print

seq = [{str(i): i} for i in range(N_seq)]
seq[1]['0'] = 0
b = db.from_sequence(seq)

print '-'*80
print 'Sequence'
print seq
print

print 'Dask dataframe with column inference'
print b.to_dataframe().compute()
print

print 'Dask dataframe with column specification'
print b.to_dataframe(columns=[str(i) for i in range(N_seq)]).compute()
print

print 'Pandas dataframe with column inference'
print pd.DataFrame(seq)
print
```

**Comment by mrocklin** [comment]
dask.bag.to_dataframe assumes that all elements in the sequence are of the same form.  We do this to maintain laziness, which seems to be a well loved feature by users that have large on-disk datasets.  It's for this reason that I hesitate to force a full dataset read on dataframe conversion.

Perhaps you could expand out your dictionaries of your bag yourself by performing bag computations.  Something like the following:

```python
keys = b.map(lambda d: tuple(d)).distinct().compute()  # forces computation
empty = dict.fromkeys(keys)
b = b.map(lambda d: merge(empty, d)).to_dataframe()
```

Something like this should give you what you want without forcing other `to_dataframe` cases to lose laziness.

**Comment by nirizr** [comment]
I see this being useful for dataframe originated data. Reading multiple different dataframes and merging their columns.
Matt, Will you appreciate a PR implementing something similar to the snippet you suggested for both dd and db, or do you prefer leaving that to the user?

**Comment by mrocklin** [comment]
@nirizr for dataframe originated data would `concat` work?

Before we put something like what is in my example into dask.bag I would want to make sure that this is a common problem.  I'm always a little hesitant to add features (and maintenance burden) for things that can easily be handled in user code.  @dwyatte do you have a more concrete example of where this is coming up for you?  The provided toy example is great for demonstrating the problem (thank you for providing a minimal example), but it'd be good to know also why this is coming up in practice.

**Comment by dwyatte** [comment]
@mrocklin The common use case for us (and others, I suspect) is reading a large collection of line-delimited JSON files scattered across disk, potentially with different schema, that we then want to work with using DataFrame methods. Basically, the same circumstances that would warrant Spark.

I agree that we want to maintain laziness when converting to a DataFrame, including when calling dask.DataFrame.columns. However, it seems that it would be possible for DataFrame.compute() to normalize over keys like pandas does, but this would break equality between dask.DataFrame.columns and dask.DataFrame.compute().columns.

If a user knows their schema beforehand, they can specify it with dask.Bag.to_dataframe(columns=schema). I think this is okay, but we should clarify the documentation to note that if columns=None, the columns are computed from the first element only.

It would be interesting to see how Spark handles this. They acknowledge the same problem at the end of this blog post (https://databricks.com/blog/2015/02/02/an-introduction-to-json-support-in-spark-sql.html), but I haven't checked to see what the current behavior is.

**Comment by mrocklin** [comment]
> but this would break equality between dask.DataFrame.columns and dask.DataFrame.compute().columns

Yeah, this is what concerns me.  This is likely to introduce a lot of subtle bugs and incorrect results if we allow it.  Generally the algorithms in dask.dataframe are unable to always guarantee correctness if they learn about columns on-the-fly.  If you want consistent dependable behavior and if you don't know the columns ahead of time then my guess is that you'll have to do something like what what is proposed above.

> However, it seems that it would be possible for DataFrame.compute() to normalize over keys like pandas does.

The difference here is that Pandas looks at all of the data before it does anything, so it's able to set things up correctly before starting any computations.  I agree that this is super convenient for the user when possible, however when we switch to a distributed or larger-than-memory workloads I don't currently see how this same approach is possible.

> If a user knows their schema beforehand, they can specify it with dask.Bag.to_dataframe(columns=schema). I think this is okay, but we should clarify the documentation to note that if columns=None, the columns are computed from the first element only.

I entirely agree with this

**Comment by mrocklin** [comment]
@nirizr perhaps a keyword argument to `Bag.to_dataframe`?  What are your thoughts?

**Comment by nirizr** [comment]
You're right. I now have a single dd with multiple partitions, each with slightly differing columns. Building those a several dds and calling `concat` will do what I want. I can think of a use case where a dd method would be easier but `concat` is good enough for me.

Did you mean adding a keyword to trigger an additional computation? that sounds good.
IMHO the current method could use some better documentation in that regard. Right now `Bag.to_dataframe` just says columns will be computed if not provided, neglecting to state according to first partition and that a `compute` will be triggered by calling `take(1)` (which could be quite heavy itself, see #1438)

**Comment by nirizr** [comment]
I PRed a doc clarification in #1450.

> If a user knows their schema beforehand, they can specify it with dask.Bag.to_dataframe(columns=schema). I think this is okay, but we should clarify the documentation to note that if columns=None, the columns are computed from the first element only.

providing a list of colums will still trigger an expensive compute. a user doing that should better provide a `pd.DataFrame' to get better performance. I wasn't aware of that before actually modifying the docs.

**Comment by nirizr** [comment]
@mrocklin I can't think of a simple way to get a single row from each partition, which is needed to add the keyword parameter you suggested. Ideas?

`db.take(1, npartitions=-1)` is nearly there, except it then calls an additional `take` and returns a single row. It might be a valid use-case ("get 5 rows from each partition") but could also be too much. What do you think? Is it worth it?

btw, similar issues might exist [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L1154), [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L1435), [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L1645) and [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2006), although I didn't take an in-depth look.

**Comment by mrocklin** [comment]
Actually I think that for this to work as @dwyatte we would need to process through all rows of the dataset, not just one from each partition.  I would do something like the snippet proposed above: 

```python
keys = b.map(lambda d: tuple(d)).distinct().compute()  # forces computation
empty = dict.fromkeys(keys)
b = b.map(lambda d: merge(empty, d)).to_dataframe()
```

**Comment by dwyatte** [comment]
@mrocklin After digging further, making a pass through the entire dataset is what Spark does unless the schema (with type information) is specified. So it seems that is probably the way that this problem has to be solved. http://spark.apache.org/docs/2.0.0/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.json

I think the schema inference would be a welcome addition if @nirizr or someone else has time to implement it, but manually specifying it with columns= works for my use case. 

I did not know that columns= in Bag.to_dataframe() should be a pandas DataFrame to avoid computation, so I agree with updating the docs per 1450.

**Comment by mrocklin** [comment]
Instead of having a separate schema interface a la Spark, Dask generally asks the user to provide an example Pandas DataFrame or a dtypes dict as would be used by a Pandas DataFrame.  I agree that this could be better documented.  

The work of @jcrist  over at #1422 is relevant here, where all of dask.dataframe is being unified around this model.

**Comment by jcrist** [comment]
Can this be closed? I'm not sure if having the expensive full-scan in dask is a good idea, especially if it can be written in only a few lines of code anyway. Encouraging users to provide the metadata themselves instead of doing the expensive scan seems like a better plan to me. The docs have been updated to reflect this.

**Comment by mrocklin** [comment]
is `Bag.to_dataframe` aligned with other dataframe functions around `meta=` enough so that https://github.com/dask/dask/pull/1514 is sufficient documentation (perhaps with a link in the to_dataframe docstring?)

**Comment by jcrist** [comment]
I'd say the description [in the docstring](http://dask.pydata.org/en/latest/bag-api.html#dask.bag.Bag.to_dataframe) is adequate, but it does use the name `columns`, not `meta`. I'm not sure if this should be changed to `meta`, as it also does allow for column subselection.

**Comment by MarkDunne** [comment]
I've just run into this problem trying to load in many JSON files of an unknown schema. I have a function which maps a given JSON file to a list of columns. I determine which columns the output dataframe should have by taking the union of these lists. Without writing my own custom graph, is there any way to do this without loading all JSON files into memory?

**Comment by mrocklin** [comment]
@MarkDunne perhaps one of the mechanisms above?  Perhaps you can identify the full set of columns by doing a single pass of the data and using something like `distinct` and then you can map a function across your json data that normalizes it to a uniform schema and then call to_dataframe?

**Comment by MarkDunne** [comment]
@mrocklin Thanks for the quick response!

Unfortunately, doing two full passes of the dataset would be impractical in my use case. It already takes a couple of hours for a single pass and I would like to avoid doubling that if possible.

Let me explain a little more about my case. Ideally, I want to do something like this
```    
data = dask.bag.read_text('*.json').map(transform_json)
columns = data.map(get_json_keys).fold(set.union)
data.to_dataframe(columns=columns).to_csv('output.csv')
```

The above clearly doesn't work, as I can't feed to_dataframe a bag object. Instead, I could call `columns.compute()`. Except this means reading and transforming the json files twice. As I said earlier, this is impractical as a single pass takes hours and I don't want to double this.

My current solution is this
```
data = dask.bag.read_text('*.json').map(transform_json).compute()
columns = dask.bag.from_sequence(data).map(get_json_keys).fold(set.union)
dask.bag.from_sequence(data).to_dataframe(columns=columns).to_csv('output.csv')
```

This means I only need to make one pass of the data, but its not without its drawbacks. The most important is that this necessitates storing all data in RAM for a period of time, and the second is that I think this is a bit slower it should be just because there is some overhead in going into and out of Dask.

I think the crux of the matter is that there is a fork in my code. I need to branch off, compute my columns, then merge this information back to the main process. It seems that the Dask bag API is strictly sequential. I could do this in a custom graph, but this would take quite a bit of work I think.

**Comment by mrocklin** [comment]
(sorry for the long delay)

Dask.bag should be able to handle non-linear dependencies.  However converting to a dataframe will require explicit knowledge of the columns of your data.  If you don't know this ahead of time then I don't see any way to accomplish what you want in a single non-memory-intensive pass.

**Comment by jcrist** [comment]
I believe the original issue has been resolved through documentation. Feel free to reopen if there's still more to do.
