### ISSUE TITLE
Reading a bag from s3, with nested directories

### ISSUE THREAD

**Issue by martindurant** [dask/dask#1471]
Following http://stackoverflow.com/questions/38946110/dask-bag-read-text-s3

Failing test case:

```
def test_read_nested_bag(s3):
    db = pytest.importorskip('dask.bag')
    with s3.open(test_bucket_name+'/not_a_directory', 'wb') as f:
        f.write(b'data1')
    with s3.open(test_bucket_name+'/not_a_directory/file1', 'wb') as f:
        f.write(b'data2')
    out = db.read_text('s3://'+test_bucket_name+'/not_a_directory',
                       blocksize=900000)
    assert out.compute() == ['data1']
    out = db.read_text('s3://'+test_bucket_name+'/not_a_directory')
    assert out.compute() == ['data1']
    out = db.read_text('s3://'+test_bucket_name+'/not_a_directory/*')
    assert out.compute() == ['data2']
```

**Comment by martindurant** [comment]
Use of blocksize causes data to come from read_bytes, otherwise comes from open_text_files.

**Comment by martindurant** [comment]
The culprit is s3.glob : is there is no "*", it assumes the path is a directory and adds "/*". Read_bytes does not call glob if there is no "*". This is probably reasonable behaviour for s3.glob (because of the ambiguity between files and directories on s3), so open_text_files should have the same logic as read_bytes.

**Comment by mrocklin** [comment]
Was this resolved?

**Comment by martindurant** [comment]
It seems not - the test case above didn't make it into the code base, presumably because the workaround was good enough. I still want to comprehensively rewrite the read_ functionality to make it simple like the write_ ones, but I don't know when I'll get to it.
