### ISSUE TITLE
groupby count throws an encoding error: can't decode byte at position 0

### ISSUE THREAD

**Issue by gbrian** [dask/dask#1476]
Hi,

Have this happened to any of you before?
![image](https://cloud.githubusercontent.com/assets/767180/17726280/4d762596-6452-11e6-87b5-d43c698ed14d.png)

Thanks in advance

**Comment by nirizr** [comment]
Thanks for reporting the issue!

Can you provide more details about what you're trying to do?
Perhaps provide a reproduction?

**Comment by mrocklin** [comment]
Possibly related to https://github.com/dask/dask/issues/1452

Try updating partd:

    pip install git+https://github.com/dask/partd.git --upgrade

**Comment by gbrian** [comment]
Thanks @nirizr , @mrocklin .
Finally seems that the problem is related with the CSV data used, that is in UTF8-BOM. So BOM is causing this issue creating a wrong index column name.

![image](https://cloud.githubusercontent.com/assets/767180/17736889/639188b0-648a-11e6-9e90-3c2034afdd64.png)

Thanks again, closing!

**Comment by TomAugspurger** [comment]
FYI, I think the UTF-8 was fixed in pandas a couple weeks ago: https://github.com/pydata/pandas/pull/13885. A Pandas 0.19 release candidate should be out in a couple weeks.

**Comment by gbrian** [comment]
Thanks, 
I'm newbie to this world so I'm a bit (totally) lost ;)
I've done some changes to adapt my code to use Dask, one is related with "size" new in pandas 0.18
Do you know if Dask is a layer on top pandas or rewrites it?
Thanks in advance.

**Comment by mrocklin** [comment]
Dask.dataframe wraps around Pandas.  Dask.dataframe functions cause many Pandas functions to occur.

**Comment by mrocklin** [comment]
http://dask.readthedocs.io/en/latest/dataframe-partitions.html

**Comment by gbrian** [comment]
Ok, thanks that explains. So Dask needs to add new functions as pandas publish to be 100% compliant, right?

Really I don't care to much about parity right now, as I'm new to panda and I don't have to much code done, so for me is ok to start learning Dask instead ;)

Right now I'm having some strange performance issues during debugging but I guess it is because my machine getting exhaust.

**Comment by mrocklin** [comment]
I recommend learning Pandas first and only using Dask.dataframe if it becomes necessary.  Pandas is usually entirely sufficient.

Dask.dataframe has no ambitions to be 100% compliant to Pandas.  Pandas is much more fully featured than dask.dataframe.

**Comment by gbrian** [comment]
Yeah, that makes sense, what I've done is replace pandas by Dask.
You mean for that parts I want to run in parallel I can jump into Dask, right?
I'll take a look on how to build Dask dataframe from pandas series or columns.

Great support, great project! I wish you all the best, let's keep in touch.
