### ISSUE TITLE
dask.dataframe.read_csv: ValueError: Integer column has NA values

### ISSUE THREAD

**Issue by vykhand** [dask/dask#1480]
I am trying to use dask to load csv file that can be found [here ](https://www.kaggle.com/c/grupo-bimbo-inventory-demand/download/test.csv.zip) on Kaggle.

Here is the code:

```
import dask.dataframe as dd
datadir = '../input'
types = {'id': 'int64', 'Semana': 'uint16', 'Agencia_ID': 'uint16', 'Canal_ID': 'uint16',
         'Ruta_SAK': 'uint16' ,'Cliente_ID': 'float32', 'Producto_ID': 'float32'}
name_map = {'Semana': 'week', 'Agencia_ID': 'agency', 'Canal_ID': 'channel',
            'Ruta_SAK': 'route', 'Cliente_ID': 'client', 'Producto_ID': 'prod'}

test =  dd.read_csv(os.path.join(datadir, 'test.csv'), usecols=types.keys(), dtype=types, )
test = test.rename(columns=name_map)
```

It gives an error:

gives :

> ValueError: Integer column has NA values in column 1

However, the same pandas read_csv operation completes fine and does not yield any NA:

```
types = {'id': 'int64', 'Semana': 'uint8', 'Agencia_ID': 'uint16', 'Canal_ID': 'uint',
         'Ruta_SAK': 'uint16' ,'Cliente_ID': 'float32', 'Producto_ID': 'float32'}
name_map = {'Semana': 'week', 'Agencia_ID': 'agency', 'Canal_ID': 'channel',
            'Ruta_SAK': 'route', 'Cliente_ID': 'client', 'Producto_ID': 'prod'}

test =  pd.read_csv(os.path.join(datadir, 'test.csv'), usecols=types.keys(), dtype=types)
test = test.rename(columns=name_map)
```

`test.isnull().any()`

> id         False
> week       False
> agency     False
> channel    False
> route      False
> client     False
> prod       False
> dtype: bool
> 

`test.info()`

> <class 'pandas.core.frame.DataFrame'>
> RangeIndex: 6999251 entries, 0 to 6999250
> Data columns (total 7 columns):
> id         int64
> week       uint8
> agency     uint16
> channel    uint32
> route      uint16
> client     float32
> prod       float32
> dtypes: float32(2), int64(1), uint16(2), uint32(1), uint8(1)
> memory usage: 166.9 MB

Full traceback:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-10-04e199a8237b> in <module>()
>       4             'Ruta_SAK': 'route', 'Cliente_ID': 'client', 'Producto_ID': 'prod'}
>       5 
> ----> 6 test =  dd.read_csv(os.path.join(datadir, 'test.csv'), usecols=types.keys(), dtype=types, )
>       7 test = test.rename(columns=name_map)
> 
> D:\PROGLANG\Anaconda2\lib\site-packages\dask\dataframe\csv.pyc in read_csv(filename, blocksize, chunkbytes, collection, lineterminator, compression, sample, enforce, storage_options, **kwargs)
>     195     else:
>     196         header = sample.split(b_lineterminator)[0] + b_lineterminator
> --> 197     head = pd.read_csv(BytesIO(sample), **kwargs)
>     198 
>     199     df = read_csv_from_bytes(values, header, head, kwargs,
> 
> D:\PROGLANG\Anaconda2\lib\site-packages\pandas\io\parsers.pyc in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
>     560                     skip_blank_lines=skip_blank_lines)
>     561 
> --> 562         return _read(filepath_or_buffer, kwds)
>     563 
>     564     parser_f.__name__ = name
> 
> D:\PROGLANG\Anaconda2\lib\site-packages\pandas\io\parsers.pyc in _read(filepath_or_buffer, kwds)
>     323         return parser
>     324 
> --> 325     return parser.read()
>     326 
>     327 _parser_defaults = {
> 
> D:\PROGLANG\Anaconda2\lib\site-packages\pandas\io\parsers.pyc in read(self, nrows)
>     813                 raise ValueError('skip_footer not supported for iteration')
>     814 
> --> 815         ret = self._engine.read(nrows)
>     816 
>     817         if self.options.get('as_recarray'):
> 
> D:\PROGLANG\Anaconda2\lib\site-packages\pandas\io\parsers.pyc in read(self, nrows)
>    1312     def read(self, nrows=None):
>    1313         try:
> -> 1314             data = self._reader.read(nrows)
>    1315         except StopIteration:
>    1316             if self._first_chunk:
> 
> pandas\parser.pyx in pandas.parser.TextReader.read (pandas\parser.c:8748)()
> 
> pandas\parser.pyx in pandas.parser.TextReader._read_low_memory (pandas\parser.c:9003)()
> 
> pandas\parser.pyx in pandas.parser.TextReader._read_rows (pandas\parser.c:10022)()
> 
> pandas\parser.pyx in pandas.parser.TextReader._convert_column_data (pandas\parser.c:11397)()
> 
> pandas\parser.pyx in pandas.parser.TextReader._convert_tokens (pandas\parser.c:12093)()
> 
> pandas\parser.pyx in pandas.parser.TextReader._convert_with_dtype (pandas\parser.c:13057)()
> 
> ValueError: Integer column has NA values in column 1

**Comment by jcrist** [comment]
I'm fairly certain this is the same issue that was fixed in https://github.com/dask/dask/pull/1495. Can you try again using master?

`pip install -U git+https://github.com/dask/dask.git`

**Comment by vykhand** [comment]
Hi @jcrist ,

I confirm that the issue is gone.

**Comment by jcrist** [comment]
Glad to hear it. Closing.
