### ISSUE TITLE
dask.array does not evaluate indexing by column names

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#1485]
Consider the case

```
x['c1'][:10]
```

Currently, dask.array does not evaluate indexing by column names from the storage backend.
It does slicing first. Effectively dask evaluate this as `x[:10]['c1']`.

I propose dask.array follows the instruction of the caller, evaluating the column selection before the slicing.
1. The current behaviour (evaluate slicing into a numpy array, then select the column) is inefficient when the storage backend supports efficient column selection. (e.g. chunked HDF5 files, FITS files or our bigfile format), because all columns must be read into memory first.
2. The proposed behaviour is not less efficient when the storage backend does not support efficient column selection. (e.g. unchunked FITS files). Because the file backend still has to read in all columns.

It is not a major breakage on API, since we already demand the storage object passed to dask.from_array to support numpy slicing indexing, it doesn't make a huge difference to assume it supports indexing by column names. Most we can imagine probably already support indexing by (at least) a single column name when the underlying data has structure.

Here is an example.

```
import numpy
import dask.array as da
class BinaryFile(object):
    def __init__(self, size, dtype):
        self.size = size
        self.shape = (size, )
        self.dtype = numpy.dtype(dtype)

    def __getitem__(self, s):
        s = s[0]
        if isinstance(s, str):
            print("requesting column %s" % str)
            return BinaryFile(self.size, self.dtype[s])

        start, end, stop = s.indices(self.size)
        print("requesting %d %d %d" % (start, end, stop))
        return numpy.zeros(end - start, self.dtype)

t = da.from_array(BinaryFile(10, [('c1', 'f8'), ('c2', 'f8')]), chunks=100)
t['c1'].compute() 

```

The current behaivor:

```
requesting 0 10 1

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

Proposed behavior

```
requesting column c1
requesting 0 10 1
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

If dask doesn't support this, we'll have to invent some quite ugly hacks - a situation we'd like to avoid that situation.

Please consider. Thanks!

**Comment by rainwoodman** [comment]
cc: @nickhand

**Comment by mrocklin** [comment]
Hrm, perhaps we can provide more options to turn particular optimizations on and off.  For example you might be satisfied if you were able to selectively run the following line: 

https://github.com/dask/dask/blob/master/dask/array/optimization.py#L24

**Comment by jcrist** [comment]
It's not our optimization passes that are causing this, rather it's the original indexing. This becomes more clear if you make the array size larger than your chunk size (currently you only get one chunk):

```python
# Include all your stuff from before

>>> t = da.from_array(BinaryFile(100, [('c1', 'f8'), ('c2', 'f8')]), chunks=10)
>>> res = t['c1'][:10]
>>> res.shape
(10,)
>>> len(res.dask)   # Before optimization
22
>>> len(res._optimize(res.dask, res._keys()))
1
>>> res._optimize(res.dask, res._keys())
{('getitem-0b649c39a50ee0c5145829f914851ef1', 0): (<function apply>,
  <function dask.array.core.partial_by_order>,
  [(<function dask.array.core.getarray>,
    <__main__.BinaryFile at 0x103356690>,
    (slice(0, 10, None),))],
  {'function': <function operator.getitem>, 'other': [(1, 'c1')]})}
```

What's happening here is:
- The original `from_array` call is chunking your on disk array (without loading it). This results in initial `getarray` slices being added to the graph.
- The index of `'c1'` pulls out a column afterwards, which is applied after the chunk is read from disk
- The slice of `[:10]` subselects the chunks in the array, resulting in only one chunk actually being loaded (which is why the length is sharply reduced after optimization).

If your chunk sizes are small, this shouldn't be a big deal. I assume you're trying to pull out fields from a structured array, which force `h5py` to actually load the data. I'm unsure what the overhead is between loading all of it and subselecting, vs just selecting a single column. If it's large enough, it may make sense to add an optimization pass to do the following rewrite:

```python
(getitem, (getarray, x, slice), some_string) -> (getarray, x, (some_string, slice))
```

which would load the chunk from the column. I'm not sure if this applies to any backend besides h5py though.
```

**Comment by rainwoodman** [comment]
@jcrist Thanks for the explanation.

We are also concerned with many other types of data storage backends (not only hdf5).
In most of the containers we use, [selecting, slicing] is more efficient than [slicing, selecting] because we store the columns separately on disk. We definitely want to avoid loading in the unused columns from disk. For example, in hydro-dynamic simulations we may save 10s of attributes per particle, but most types of analysis we only need one or two columns in one run. It is a factor of 10 reduction in total IO from filesystem.

Arguarable if the container stores data as rows (e.g. csv), there is little difference if you resolve the request to [selecting, slicing] or [slicing, selecting], because either way the disk has to spin through the entire records in order to pick up the columns that are selected.

There are hybrid containers (e.g. 'chunked' HDF5 -- be aware it is a different use of the name 'chunking' than dask) Several columns are bundled together, thus the disk only spins through the bundles that are involved in the requested columns.

So perhaps dask shall extend the from_array protocol a bit. The object goes in shall declare if it is efficient in column selection. If so (almost everything other than CSV), the rewrite is applied. If not (CSV, and numpy structured arrays), the rewrite is not applied. Does this sound good?

**Comment by rainwoodman** [comment]
The rewrite I meant is something like 

```(getitem, (getarray, x, slice), some_string) -> (getarray, (getitem, x, some_string), slice)```

 Does the sequence after rewrite make sense in dask?

The one Jim has mentioned seems to request `x['col', 1:10]`, which doesn't work on numpy arrays.

```
x= numpy.empty((10,), [('a','f8')])

x['a', :3]

/anaconda3/lib/python3.5/site-packages/IPython/kernel/__main__.py:2: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


IndexErrorTraceback (most recent call last)
<ipython-input-29-3f6a5c2da8fe> in <module>()
      1 x= numpy.empty((10,), [('a','f8')])
----> 2 x['a', :3]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

**Comment by shoyer** [comment]
@rainwoodman I'm curious about your use case for structured dtypes. If the data is saved on disk in a columnar format, then it might make more sense to simply load them into separate dask arrays. If you need to operate on collections of these arrays, you could either write your own container or use xarray.

By using structured dtypes, dask.array will store intermediate chunks with the columns put together, which means you're really sunk if dask's rewrite rules don't work. And my experience with dask's rewrite rules for optimizing away indexing is that they are (sadly) somewhat lacking. There are things we could do to improve them (e.g., https://github.com/dask/dask/issues/746), but we really could benefit from a separate abstraction on top of dask.array that handles optimization at the level of full arrays.

**Comment by rainwoodman** [comment]
Our case is pruning data before feeding them to the massively parallel section of the application (parallel FFTs). Because we have thousands of cores for the FFTs, IO and pruning is a large fraction of total run time (and they usually are). We are hoping dask can help us to optimize the IO and reduce the amount of code we have to maintain. The DAG in dask shall be smart enough to tell a column that is referenced several times only needs to be read in once, right?

@jcrist 
Can we add a new rule in
https://github.com/dask/dask/blob/master/dask/array/optimization.py#L30

e.g. v[0] is getitem with a column name and a[0] is getarray with a slice, then we shall make it into one operation getarrayitem(arr, column, slice)?

**Comment by mrocklin** [comment]
I'll admit that I haven't yet dug into the nuances of this problem yet, so please excuse any ignorance on my part.

>  (getitem, (getarray, x, slice), some_string) -> (getarray, (getitem, x, some_string), slice)

Is this optimization likely to negatively impact any other commonly used formats?  What does this do to h5py Datasets of record dtype?

> e.g. v[0] is getitem with a column name and a[0] is getarray with a slice, then we shall make it into one operation getarrayitem(arr, column, slice)?

If there is a way to perform a column-store friendly optimization that doesn't negatively impact other use cases and is fast to identify then I'm all for it.  I think that most of the work here involves surveying what use cases are out there and verifying that this doesn't have a negative effect.

If it does have a negative effect then I think that we should think about how to allow users to register (or unregister) custom optimization passes.  I suspect that optimizations will arise that are critically important for some communities and flawed for others.

**Comment by rainwoodman** [comment]
I'd like to get the use cases part started. We will focus on the faction of bytes that are fetched from disk but not actually used. I call it 'waste ratio'. Since IO is involved, we neglect the cost of slicing / repacking an in memory numpy array / buffer of the same complexity.

Let's consider X,  a storage object. It can be two types,

- Column store: X['col'][:10] reads in exactly 10 items for column 'col' from disk.  The waste ratio is 0.
   X[:10]['col'] reads in 10 items of all columns, then drops the extra unused columns. There is a waste ratio of 1 - sizeof(col) / sizeof(X[0])

- Record store:  X[:10]['col'] reads the 10 full records, then drops the extra unused columns. There is a waste ratio of 1 - sizeof(col) / sizeof(X[0])
X['col'][:10] can be implemented two ways. First possibility is read in all records, then drop columns that are not 'col'. It has a waste ratio of 1 - sizeof(col) / sizeof(X[0]) * 10 / len(X). Unrealisticly inefficient. A more practical way is to resolve this to X[:10]['col'] internally in the implementation of X. We can assume any mature storage backend does this -- because the alternative is just insanely inefficient and must have triggered a bug report from downstream users. I believe quite a fraction of code in h5py/fitsio/pyfits are making sure the swap happens by somehow representing X['col'] as an intermediate representation that allows slicing.

Thus, basically for a storage object, slicing and column selection commute, s.t. X[:10]['col'] and X['col'][:10] give identical results. Column Store for X['col'][:10] has 0 waste. All other three cases has the same amount of waste 1 - sizeof(col) / sizeof(X[0]).

Note that I have left aside the hybrid store where both ordering are equally inefficient.

Next, use cases. Let's consider D, a dask array accessing X.

Applying da.compute on D['col'][:10] or D[:10]['col'] shall give identical results because the commutivity. 

Either can resolve to two sequences, (getcolumn, (getslice, A)) and (getslice, (getcolumn, A))
I have redefined operation names to simplify the discussion. We may want the implementation to have similar names too to simplify the pattern matching in optimize() -- but that's implementation detail beyond my knowledge.

Let's go through two scenarios,
1) Single Access: da.compute(D['col'][:10]), 
2) Multiple Access: da.compute(D['col1'][:10], D['col2'][:10])

Case 2, Multiple Access allows opportunities for additional optimizations in dask and negatively impacts the waste ratio if we implement them. I do not know if current dask implements such optimization. (It seems to do so accidentally)

1. Let's develop the Single access case.

- If X is a Column Store.
 - (getcolumn, (getslice, A)): D['col'][:10] -> X[:10]['col'] -> waste of 1 - sizeof(col) / sizeof(X[0])
 - (getslice, (getcolumn, A)): D['col'][:10] -> X['col'][:10] -> waste of 0

- If X is a Record Store
 - (getcolumn, (getslice, A)): D['col'][:10] -> X[:10]['col'] -> waste of 1 - sizeof(col / sizeof(X[0])
 - (getslice, (getcolumn, A)): D['col'][:10] -> X['col'][:10] -> waste of 1 - sizeof(col / sizeof(X[0]) on a reasonably backend. Blows up if the backend is buggy.

2. Let's develop the Multiple access case.

- If X is a Column Store.
 - (getcolumn, (getslice, A)): D['col1'][:10], D['col2'][:10]  -> X[:10]['col1'], X[:10]['col2'] -> (optimization) -> t = X[:10], t['col1'], t['col2'] -> waste of 1 - sizeof(col1, col2) / sizeof(X[0])
 - (getslice, (getcolumn, A)): D['col1'][:10], D['col2'][:10]  -> X['col1'][:10], X['col2'][:10]->  waste of 0
- If X is a Record Store.
 - (getcolumn, (getslice, A)): D['col1'][:10], D['col2'][:10]  -> X[:10]['col1'], X[:10]['col2'] -> (optimization?) -> t = X[:10], t['col1'], t['col2'] -> waste of 1 - sizeof(col1, ol2) / sizeof(x[0])
 - (getslice, (getcolumn, A)): D['col1'][:10], D['col2'][:10]  -> X['col1'][:10], X['col2'][:10]  -> waste of 1 - sizeof(col1, ol2) / sizeof(x[0]), or blows up on bad backends.

So here are all of the cases. In any of the cases, the sequence (getslice, (getcolumn, A)) is never worse than (getcolumn, (getslice, A)) on a behaved backend, yet gives a huge boost in the column store case (waste drops to 0). At least on paper we have the proof that the optimization shall be always applied. 

We may still want to have a blacklist of bad backends, thought the list may not be very long. 

Does anyone want to go through this argument and check for errors?

**Comment by shoyer** [comment]
I understand that astropy's FITS reader uses structured dtypes for columnar data, but H5py certainly does not. In fact, h5py exhibits exactly the behavior you call "unrealistically inefficient", because the return value from indexing an h5py dataset is always a numpy array. This is exactly what I expect with structured dtypes, because structured dtypes are not storage agnostic -- they imply a row oriented format.

This doesn't negative the importance of solving your use case, but I want to emphasize that this optimization is usually not appropriate. I also think there are probably better approaches than using dask's optimization system to solve your problem. Generally speaking, using the optimization system only makes sense as a last resort, when you need to apply some operations before you know everything that will be done. Anything that can be done directly in dask is going to be far more robust.

What you need is a way to chunk across the fields of a structured dtype. Given that this isn't possible with dask currently (and would be a tricky addition to the dask array data model, which currently simply reuses numpy dtypes), I suggest creating a collection of dask arrays, one for each column.

You could either build task dictionaries directly for this or simply use dask.delayed (since, as @jcrist points out, dask's from_array won't work for you). For example, you could write something like the following: `da.from_delayed(da.delayed(X)['col'], X.shape, X.dtype.fields['col'][0])`. Now you can chunk this column as desired using `.chunk`. If there's a way to do combined field and slice based indexing (as [there is with h5py](http://docs.h5py.org/en/latest/high/dataset.html#reading-writing-data)), then we could also make that work with a custom constructor.

**Comment by rainwoodman** [comment]
Ah. Indeed h5py is glossly inefficient. [:] and ['col'] both triggers disk IO on h5py. I updated the analysis.

I agree with you structured types are not storage agnostic. 

There are two disagreements that are probably OK to disagree:

- I do not agree that structured dtype necessarily imply a row oriented format. dask.array.dtype implies that compute(da.Array) gives a row oriented format, but does not imply the origin of the data has to be row formatted; it can in fact come from a function evaluation from dask.delayed. Furthermore, dtype can describe a column format on disk. The column names and subdtypes is the data schema. The full dtype, including the offsets represents the in-memory format of the data, which can be altered by modifying the offsets.

- I also disagree with you about the use of 'optimization' as a last resort. I believe the optimizer in dask has the potential to be a mechanisms to solve complex problems posed in a simple way. For example, the row vs. column issue. The caller wants the data. then dask goes out and find the best way of loading that data. That's where the value of dask lies. If the caller has to do everything manually, what is the point of using dask?

Next, I strongly support your suggestion about combined indexing. 

(name, slice) is the normal way of obtaining subset from structured datasets. Any storage objects knows how to most efficiently load the data when both (name, slice) are given, regardless how data is stored on disk. The [:] protocol from numpy does not support this, creating all sorts of anomalies with row-major and column-major datasets. 

So I think the right approach is probably @shoyer suggested adding a dask.from_storage method that creates dask.array from storage objects that support a combined ```__getitem__(self, (name, slice))```?
We still need to modify optimize_slice to be able to fuse together name and slice accesses, (which probably means getitem cannot be implemented as ```map_block```)

**Comment by shoyer** [comment]
@rainwoodman If your data store always pulls out columns lazily like your `BinaryFile` example, would it work to simply write `arrays = {k: da.from_array(X[k], ...) for k in X.dtype.fields}`? Or are you also concerned about stores that don't support this shortcut? If so, a wrapper (like the one I proposed above using dask.delayed) might work.

We could certainly write something like `from_storage` but fusing the fields back into a single dask array with a structured dtype is not going to work very well, unless we add lots of optimizations to move field access before literally every dask.array operation. It *can* be done, but I'm not sure it makes sense for `dask.array`.

**Comment by rainwoodman** [comment]
It could be as simple as that for our BinaryFile example -- however we miss the full dtype(or dict of dtypes from your perspective) and the length / number of items in these arrays. So basically we'll need to reinvent some sort of dataframe.

The worse is we will need two code paths, one for record storage and one for row storage. Do you see a way to avoid two different paths if dask doesn't provide a uniform interface, I don't think I see how this might work with delayed. If I instruct the column name in delayed, the columnar storage is going to beas inefficient. 

Could you elaborate why we need lots of optimizations to move field access before every dask.array operation if the dtype is fused? I thought the optimize function is called on the final dask graph at beginning of compute(). That's where the optimization happens, but I must have been missing something here?

**Comment by shoyer** [comment]
> Could you elaborate why we need lots of optimizations to move field access before every dask.array operation if the dtype is fused? I thought the optimize function is called on the final dask graph at beginning of compute(). That's where the optimization happens, but I must have been missing something here?

You're right that optimization only happens when `compute()` is called, but we're going to need a separate optimization (or family of optimizations) for each operation, plus a few to just get things started.

As soon as you call `from_storage`, the dask graph is going to be filled with lots of tasks (among others) that look like `(fuse_arrays, columns)`, where `fuse_arrays` is a function that converts a dictionary of column arrays into a single array with a structured dtype. Now if you do indexing by field, the optimizer would need to replace `(getitem, (fuse_arrays, columns), key)` with `(fuse_arrays, columns_matching_key)`, where `columns_matching_key` has explicitly removed the dependence on tasks corresponding to unused `columns`. Otherwise you'll load in the entire array when you evaluate `fuse_arrays`.

For every other operation you want to be efficient after indexing (e.g., `transpose`), you need to insert a special case optimization `(getitem, (transpose, array), key)` -> `(transpose, (getitem, array, key))`. The default behavior of dask.array is going to be abysmal, which calls into question using directly dask.array at all, rather than an object that only has the white-listed methods.

> So basically we'll need to reinvent some sort of dataframe.

Well, there are at least two ways to do this that I would consider sane:

- Write a wrapper module on top of `dask.array` with a `ColumnarStructuredArray` class represented internally by a dict of dask arrays, one for each column. This could be pretty straightforward, and probably would be useful to others.
- Put your data in an `xarray.Dataset`, which is already a DataFrame with multi-dimensional columns that can be stored internally with dask.array. The consideration here is that xarray is more than just a multi-dimensional DataFrame -- it also adds required dimension names and coordinate labels to the data model, which you may or may not find useful.

**Comment by rainwoodman** [comment]
About transpose. Isn't it true the getitem commutes with about every meaningful operator? Are there any anomalies?

If not, then it is a simple rule to say that if I see getarray and a getitem along the same path, then move getitem next to getarray, and replace these two with getarray2(arr, columnname, slice), which can always be computed efficiently. Is this feasible?

The least intrusive way is to write a diskarray that is a subclass of dask.array, where __getitem__ and optimize are overridden to make use of the [(column, slice)] interface of h5py.

Does xarray have the heuristics to deal with column and record storage both efficiently? 

BTW, our current solution is to assume column datasets are small and fits into a single computing node. Then we just read the entire thing in memory and rely on numpy API to achieve the same uniform API for both types of storage. We may be able to survive by keep doing that; but then we are not really getting all of the potential usefulness from dask.

**Comment by shoyer** [comment]
> About transpose. Isn't it true the getitem commutes with about every meaningful operator? Are there any anomalies?

For operations that don't handle recarrays explicitly, this does appear to be mostly true, but it also puts us in a weird position of supporting operations that NumPy itself does not handle, e.g.,
```
In [2]: x = np.array([(1, 2.0)], dtype='i8,f8')

In [3]: x
Out[3]:
array([(1, 2.0)],
      dtype=[('f0', '<i8'), ('f1', '<f8')])

In [4]: x + x
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype([('f0', '<i8'), ('f1', '<f8')]) dtype([('f0', '<i8'), ('f1', '<f8')]) dtype([('f0', '<i8'), ('f1', '<f8')])

In [5]: x.mean()
TypeError: cannot perform reduce with flexible type
```

So it might indeed be possible to write `ColumnarStructuredArray` as a subclass of dask.array with overridden optimize methods. I'm not 100% sure though.

> Does xarray have the heuristics to deal with column and record storage both efficiently?

xarray itself supports a struct of arrays as its data model. But if you have record storage, you could read it in with dask and then pass a dict of unstructured arrays into xarray (e.g., as I describe above) and that would support computation that as efficient as you could hope for.

**Comment by rainwoodman** [comment]
Well I would say it is debatable why numpy does not define these operators on same typed objects.  
ColumnStructuredArray is not even a subclass of numpy array, so I guess it is fine to support more operations. 

I think there is some fundamental correctness in insisting triggering IO only when column and slice are both known. I'll play around with the idea.

**Comment by shoyer** [comment]
> Well I would say it is debatable why numpy does not define these operators on same typed objects.

I agree. This is quite likely simply because nobody ever got around to implementing it (which in turn is quite likely because NumPy's internals may make this difficult to add), not an intentional omission.

**Comment by jakirkham** [comment]
@rainwoodman, does xarray work for your use case? If not, do you see a way of improving Dask to handle this case (given what you have learned since)?

**Comment by rainwoodman** [comment]
We end up using the first prescription by shoyer one array per column.

Feel free to close this old ticket!

Yu

**Comment by jakirkham** [comment]
Thanks for the update. Closing it out.
