### ISSUE TITLE
bag.from_delayed seems subfunctional

### ISSUE THREAD

**Issue by jacksonloper** [dask/dask#1488]
Using dask 0.11.0, this fails:

```
def foo(x):
    return x+1

dask.bag.from_delayed([dask.delayed(foo)(2),dask.delayed(foo)(3)]).map(lambda x:x+2).compute()
```

Am I missing something obvious?  Is there a reason that from_delayed doesn't support `npartitions=` or `partition_size=`?  It seems like `from_delayed` is doing something quite different from `from_sequence`, which confuses me.  I would have expected it be identical to `from_sequence` except replacing the objects with their keys...

**Comment by mrocklin** [comment]
@jacksonloper thanks for the note.  See explanation in the revised docstring in #1490

**Comment by jacksonloper** [comment]
Ahhah!  That's why `from_delayed` doesn't have `npartitions=`.   This way we can partition it however we want.  Perfect.
