### ISSUE TITLE
bag.from_sequence doesn't work with callables

### ISSUE THREAD

**Issue by jacksonloper** [dask/dask#1489]
If the objects in your sequence happen to be callable, then dask gets mixed up and thinks that it is looking at a task.  Using dask 0.11, this fails:

```
class Foo:
    def __init__(self,k):
        self.k=k
    def __call__(self):
        pass

dask.bag.from_sequence([Foo(10),Foo(11)]).map(lambda x:x.k).compute()
```

The trouble seems to come from the convention of associating the partitions of bags with tuples in the dask dictionary.  I believe a quickfix would be to wrap such tuples inside a 1-tuple?

**Comment by mrocklin** [comment]
We could also change the internal representation from a tuple to a list
