### ISSUE TITLE
User Gallery and Related Projects

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1496]
Lets crowd-source a list of uses of Dask to feature in the documentation.

I suspect that it will be easier and more fun to explain the breadth of this project if we have a collection of active use cases. Additionally funding sources are happier seeing lots of use and  potential users like knowing that they are in good company.  This also is a nice way to link to downstream projects and hopefully drive interest towards them.

This is inspired by XArray's version of this over here: https://github.com/pydata/xarray/issues/946

So, if you know of Dask being used in a project/research group/company/paper/other then please add a comment with the following:
- Title
- A one-line description of the project 
- A a web link
- A few sentences describing the project in more depth, and how it uses dask

The [pandas ecosystem](http://pandas.pydata.org/pandas-docs/stable/ecosystem.html) doc may be a good model for this.

If you know someone who fits this description then perhaps forward this issue to them.  If your work fits this description but are unable to comment publicly for work reasons then please send me an e-mail and I'll include a suitably anonymized description.

**Comment by mrocklin** [comment]
* XArray
* One line: Brings the labeled data power of pandas to the physical sciences, by providing N-dimensional variants of the core pandas data structures.
* Link: http://xarray.pydata.org/en/stable/
* Paragraph: XArray manages collections of labeled and indexed n-dimensional arrays, such as are commonly found in geo and atmospheric science.  It uses either NumPy or Dask.array to perform calculations.  Dask.array is useful when these datasets grow beyond the size of available memory but still fit comfortably on disk.

**Comment by mrocklin** [comment]
* Dask.mesos
* Apache Mesos backend for Dask scheduling library
* https://github.com/lensacom/dask.mesos
* A backend that extends the single-machine scheduler found in the dask repository to run task graphs on a cluster running Mesos

**Comment by mrocklin** [comment]
* Daisy
* https://github.com/llllllllll/daisy
* Syntax tricks to automatically compile Python functions into dask graphs.  An alternative to dask.delayed.

**Comment by mrocklin** [comment]
*  daskfitsio
* https://github.com/mindriot101/daskfitsio
* Wrapper around `fitsio.ImageHDU` creating a `dask.Array`

**Comment by mrocklin** [comment]
* Cesium ML
* http://cesium.ml/
* Open-Source Machine Learning for Time Series Analysis
* Cesium is a time-series machine learning platform with a web-based frontend out of BIDS.  It uses Dask to farm out tasks with low latency to a set of worker nodes, replacing celery.

cc @stefanv @bnaul for verification

**Comment by mrocklin** [comment]
* COMPRESSED NONNEGATIVE MATRIX FACTORIZATION IS FAST AND ACCURATE
* http://arxiv.org/pdf/1505.04650.pdf
* Paper on parallel non-negative matrix factorization
* This paper proposes and benchmarkes novel blocked algorithms to perform approximate non-negative matrix factorization.  The algorithms were prototyped using Dask and executed with dask.array.

**Comment by martindurant** [comment]
- zarr storage
- http://zarr.readthedocs.io/en/latest/
- storage of ND array data in many compressed files, allows easy access of parts of the arrays using [..] syntax and loading only the pieces needed. Works on any backend with appropriate interface (e.g., hdfs3, s3fs)
- could conceivably couple with xarray to store physically meaningful coordinates on massive ND datasets

**Comment by martindurant** [comment]
- fastparquet
- http://fastparquet.readthedocs.io/en/latest/
- interface to commonly used data format from the hadoop/big-data world. Dask can read and write with parallelism at the "row group" level.

**Comment by jbednar** [comment]
* datashader
* bin-base rendering of large datasets
* https://github.com/bokeh/datashader
* Accepts columnar data as either a pandas dataframe or a dask dataframe, and supports out-of-core and distributed operation only for dask dataframes.

**Comment by mrocklin** [comment]
@jrbourbeau and I were chatting about this.  I think that my thinking here has shifted a bit, so I wanted to write down my current thoughts:

This is one of the more common requests I get from *potential institutional users*.  Folks from companies or other institutions e-mail me fairly frequently and ask me "who uses dask?".  One part of an answer to that question is software projects, like what is collected here.  Another, possibly more motivating part, are other companies that use the project.  I'm inclined to include both on the same page.  

Also, given the intended audience (or at least my intended audience) I'm inclined to style this with more care than would be provided by Sphinx.  I think that a page like this might live on dask.org (hosted from https://github.com/dask/dask.github.io) rather than docs.dask.org and that we might write it in HTML and CSS.

I think that there are three things to do here:

1.   Figure out groups that use the project
2.  Design a nice way to present the information 
3.  For those that aren't broadcasting their use, get their permission

1 and 2 are more straightforward, they're probably also useful in accomplishing 3 (many groups will have a default "no, don't publicize" reaction that we will need to overcome)

**Comment by mrocklin** [comment]
A couple days ago I searched through twitter and came up with the following list:

-  Xarray
-  Iris / UK Met
-  Pangeo: NASA, NCAR, UK Met, USGS (probably several more)
-  Datashader, Anaconda, US Army Corps of Engineers
-  Scikit-Learn through Joblib
-  Karthotek - Blue Yonder
-  TSFresh - Blue Yonder
-  Satpy
-  MDAnalysis
-  Scikit-Allel Oxford Big Data Institute / Center for Genomics and Global Health
-  Daskperiment
-  Prefect / Prefect I
-  Feature tools / Feature Labs
-  Barclays (https://twitter.com/jiminy_crist/status/1052592632021639169?s=19) (need to get slides)
-  Capital one https://medium.com/capital-one-tech/dask-numba-for-efficient-in-memory-model-scoring-dfc9b68ba6ce
-  Full Spectrum Credit + Banking - http://stories.dask.org/en/latest/fullspectrum.html
-  Ice Cube http://stories.dask.org/en/latest/icecube-cosmic-rays.html
-  Aladdin by BlackRock - https://www.ftfnews.com/blackrock-builds-aladdin-web-app-for-investor-research/19423

There are several other industry groups that use the project, but I would want to check with them before adding them to a public list.  When I go to a conference there are always a decent number of folks who come up from various companies and mention that they use it internally.  Presumably once a page is up it'll be easier to grow.

**Comment by jbednar** [comment]
People using datashader are presumably at least installing dask, including these from Twitter:

- Instacart: https://tech.instacart.com/space-time-and-groceries-a315925acf3a 
- SafeGraph: https://twitter.com/jbrichman/status/1006195205899505665

**Comment by jrbourbeau** [comment]
Thanks @mrocklin for assembling this list

> Another, possibly more motivating part, are other companies that use the project

Totally agree. I'd be in favor of a "Who uses Dask?" (or some other title) page on dask.org that highlights companies using Dask, software projects that use Dask, Institutional partners, etc.

One other approach I've seen is to include a "Project X is used by" section on the project landing page with company logos. For example, Jupyter has a "Currently in use at" section on https://jupyter.org/ (shown in screenshot below) which highlights some organizations that use Jupyter. We could consider having something similar on the Dask landing page in addition to a separate "Who uses Dask?" page.

![Screen Shot 2019-05-14 at 2 50 53 PM](https://user-images.githubusercontent.com/11656932/57727652-ac82db00-7657-11e9-86ac-a8bebbc2c32c.png)

**Comment by mrocklin** [comment]
Definitely agreed.  A page like that (or footer on the main page) that showed the logos of all companies that currently use the project would, I think, make many others much more comfortable with depending on the software.

It's sometimes tricky getting permission to use those logos.  I'm not sure how careful we have to be here though, especially when a company has made public mention of their use of the project.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask.github.io/pull/8
