### ISSUE TITLE
dd.merge indicator support/alternative

### ISSUE THREAD

**Issue by ankravch** [dask/dask#1500]
Hi there,

I want to do outer join of two dataframes (each has only one column).
In pandas I would do it like this:
```python
df1 = pd.DataFrame({'v0':[1,2,3,4,5]})
df2 = pd.DataFrame({'v0':[2,3,4,6,7]})
out=pd.merge(df1,df2, how='outer', indicator=True)
out[out['_merge']!='both'].drop('_merge', axis=1)
	v0
0	1.0
4	5.0
5	6.0
6	7.0
```

From dask.pdf docs it looks like indicator keyword is not supported. Is there an alternative to 'indicator' in my use case?
```python
import dask.dataframe as dd
import dask
df1 = pd.DataFrame({'v0':[1,2,3,4,5]})
df2 = pd.DataFrame({'v0':[2,3,4,6,7]})
ddf1 = dd.from_pandas(df1, npartitions=1)
ddf2 = dd.from_pandas(df2, npartitions=1)
dask.compute(dd.merge(df1,df2, on='v0', how='outer'))

(    v0
 0  1.0
 1  2.0
 2  3.0
 3  4.0
 4  5.0
 5  6.0
 6  7.0,)
```

Thank you,
Anton

**Comment by mrocklin** [comment]
Seems like we should be able to pass this down through the pd.merge calls.  Any interest in trying this out and submitting a pull request?
