### ISSUE TITLE
error in csv sampling

### ISSUE THREAD

**Issue by ikilledthecat** [dask/dask#1501]
While trying to read a large csv file using dask. I found the following error

CParserError: Error tokenizing data. C error: EOF inside string starting at line 1698

No such error was observed in reading the file through pandas. The error it seems lies on line 68 of dask/bytes/local.py. The call to function read_block_from_file has delimiter set to None. reseting it to the variable delimiter in function  read_bytes, from where it is called did the trick for me.

Please let me know if this approach is ok and if you want me to raise a pull request

**Comment by mrocklin** [comment]
Can you provide a failing test?

Does the recently merged https://github.com/dask/dask/pull/1495 help in your case?

**Comment by ikilledthecat** [comment]
I believe #1495 solves the issue. Thanks

**Comment by mrocklin** [comment]
Great!  Closing.
