### ISSUE TITLE
Update DataFrame.to_csv documentation to indicate using glob based naming over single file

### ISSUE THREAD

**Issue by mobcdi** [dask/dask#1506]
As mentioned in the forum https://groups.google.com/a/continuum.io/forum/#!searchin/blaze-dev/to_csv/blaze-dev/NCQfCoOWEcI/S7fwuCfeCgAJ the dask dataframe.to_csv will write to multiple csv files to overcome the issue of parallel execution on a single file. 

From the documentation in the API, the cheatsheet or the introduction its not clear that a user should not provide a single filename but instead use the glob format to create multiple files using a common structure like `file-*.csv`

**Comment by mrocklin** [comment]
I agree.  Currently we just copy the `pandas` docstring.  It would be good to create our own.  Can I interest you in submitting a pull request?

**Comment by mobcdi** [comment]
Fairly new to this word but happy to do my bit if I can. Where do you recommend I target the change?

**Comment by mrocklin** [comment]
This might be helpful: http://dask.readthedocs.io/en/latest/develop.html , in particular http://dask.readthedocs.io/en/latest/develop.html#docstrings

If you search for `def to_csv` in dask/dataframe/core.py` you'll find the right place to add the docstring.  Other docstrings within that file might be good models.

**Comment by mobcdi** [comment]
#1508 and #1507 created

**Comment by dukebody** [comment]
I created another PR for the docstring part, copying the pandas docstring and adding info about the multiple files features.

The downside of this is that we have to keep track of pandas to_csv docstring updates manually. However this method should be already rock-solid stable, so I believe that won't be a serious issue.

**Comment by mrocklin** [comment]
Closed by #1525
