### ISSUE TITLE
test_read_csv_of_modified_file_has_different_name failure

### ISSUE THREAD

**Issue by jmwoloso** [dask/dask#1509]
Hello!

Wondering if anyone might be able to help me decode what went wrong with the test suite. The test that failed is mentioned in the title.

My setup:
Linux Mint Rosa
Pandas: 0.18.1
NumPy: 1.11.1

Test output is attached. Thank you in advance for any insight!
[dask_tests.txt](https://github.com/dask/dask/files/440466/dask_tests.txt)

**Comment by mrocklin** [comment]
Fixed in #1510 

What's more concerning is that travis-ci didn't pick this up

**Comment by jmwoloso** [comment]
@mrocklin Great point, lol. Thank you for the update! I'll pull down that commit and try it out. Closing.
