### ISSUE TITLE
API to apply multiple functions while grouping

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#1517]
Hi,
I've found that a pandas syntax for that process isn't available in dask. Is there any other recommended way to achieve the the following?
- take dataset `x`
- group by column `id3`
- calculate sum over `v1` and mean over `v3`

in pandas:
```py
x.groupby(['id3']).agg({'v1':'sum', 'v3':'mean'})
```
Thanks

**Comment by mrocklin** [comment]
At the moment the `.agg` interface isn't implemented.  It would be a great contribution if you have an interest though.  At the moment you would use `sum` and `mean` separately but compute them together

a = x.groupby('id3').v1.sum()
b = x.groupby('id3').v3.mean()

a, b = dask.compute(a, b)

**Comment by jangorecki** [comment]
Thanks for very fast response!

**Comment by mrocklin** [comment]
I think so?  I'm not sure.  I recommend exploring the API to make sure.
