### ISSUE TITLE
Split/Chunk Workflow support

### ISSUE THREAD

**Issue by mbande** [dask/dask#1536]
is there any way to implement [parallel split](http://www.workflowpatterns.com/patterns/control/basic/wcp2.php) with [custom graph](http://dask.pydata.org/en/latest/custom-graphs.html)?

**Comment by mrocklin** [comment]
Like this?

```python
@dask.delayed
def f(*args):
    return ...

@dask.delayed
def g(*args):
    return ...

x = f(1)
y = g(x, 1)
z = g(x, 2)
```

**Comment by khafan246** [comment]
@mrocklin I'm looking for the same feature
assume the ```f``` returns a list of arbitrary size ```n```, i want to trigger a ```g``` to any of that items.
a more generalized use case is to apply ```g```s to each chunk of size ```m``` of ```f``` outputs

**Comment by mrocklin** [comment]
The example in https://gist.github.com/mrocklin/ef9ccd29a6ec5f4de84d6192be95042a starting with "Example with data streams" might be of interest

**Comment by mrocklin** [comment]
Any additional questions here?

**Comment by mbande** [comment]
@mrocklin thank you. i will look at gist and reopen the issue if neede
