### ISSUE TITLE
celery comparision

### ISSUE THREAD

**Issue by khafan246** [dask/dask#1537]
looking at Dynamic task scheduling side of dask, is there any feature comparison to celery?
handling (multiple) queues, canvas (celery's workflow), rate limiting, retrying, etc.

**Comment by mrocklin** [comment]
I don't know of any such comparison.  I'd be happy to help if someone wanted to perform such a test. Looking at the documentation for the distributed scheduler might be a good start: http://distributed.readthedocs.io/en/latest/

**Comment by mrocklin** [comment]
Closed by http://matthewrocklin.com/blog/work/2016/09/13/dask-and-celery
