### ISSUE TITLE
Beware of Pandas.concat bug upcasting column types performing repartition when empty partitions exist

### ISSUE THREAD

**Issue by frol** [dask/dask#1547]
There is already a PR in Pandas, but nobody takes care of it: https://github.com/pydata/pandas/pull/13337

When at least one of your partitions is empty or some columns contain only `NaN` values (e.g. after filtering), `.repartition`, which uses `pandas.concat`, upcasts the `dtype`:

``` python
 In [7]: pn1 = pd.DataFrame(np.array([1.0], dtype=np.float32, ndmin=2)) # df of 1.0

 In [8]: pn2 = pd.DataFrame(np.array([np.nan], dtype=np.float32, ndmin=2)) # df of nan

 In [9]: print(pd.concat([pn2, pn2]).values.dtype)
 float64

 In [10]: print(pd.concat([pn1, pn1]).values.dtype)
 float32
```

**Comment by jcrist** [comment]
Thanks for filing this issue. Since there have been 3 major release versions since the fix was merged to pandas, I'm going to close this.
