### ISSUE TITLE
Misleading documentation on Bag.join

### ISSUE THREAD

**Issue by kszucs** [dask/dask#1551]
I've found http://dask.pydata.org/en/latest/bag-overview.html#shuffle a bit misleading. 
I'd expect a slow, but working bag-to-bag join, but I can't find any working [implementation](https://github.com/dask/dask/blob/master/dask/bag/core.py#L808)

**Comment by mrocklin** [comment]
Confirmed. The reference to join for bag should be removed.

**Comment by lsorber** [comment]
What is the current recommended way to achieve a bag-to-bag join, if at all possible?

**Comment by mrocklin** [comment]
I don't think it is implemented.  I suspect that the best implementation today would be to switch to dataframes and use their joins.  It would be nice to implement a proper join in bag though.  If you have time and interest in this, effort here would be quite welcome.

**Comment by lsorber** [comment]
@mrocklin Thanks for the suggestion. We came up with the same solution (see below), which is always nice to see. Thinking about it more, it's probably best to just move away from Bags altogether if you need a bag-to-bag join since the absence of order makes an efficient join almost impossible.

For reference, this was our version of a bag-to-bag join:
```python
def record_to_keydata(x, key):
    return {'key': x[key], 'data': {k: v for k, v in x.items() if k != key}}

def keydata_to_record(x, key):
    return {
        key: x[0],
        **(x[1] if isinstance(x[1], dict) else {}),
        **(x[2] if isinstance(x[2], dict) else {})
    }

def join_bags(left, right, key, how='left'):
    left = left.map(record_to_keydata, key)
    right = right.map(record_to_keydata, key)
    left = left.to_dataframe(columns=['key', 'data']).set_index('key')
    right = right.to_dataframe(columns=['key', 'data']).set_index('key')
    merged = left.join(right, how=how, lsuffix='_left', rsuffix='_right')
    return merged.to_bag(index=True).map(keydata_to_record, key)

a = [
    {'id': 123, 'colA': 1, 'colB': 2},
    {'id': 456, 'colA': 3, 'colB': 4},
    {'id': 789, 'colA': 5, 'colB': 6},
]
b = [
    {'id': 123, 'colC': 1, 'colD': 2},
    {'id': 789, 'colC': 5, 'colD': 6},
]
ba = dask.bag.from_sequence(a)
bb = dask.bag.from_sequence(b)
join_bags(ba, bb, 'id').compute()
```
Output:
```python
[{'colA': 1, 'colB': 2, 'colC': 1, 'colD': 2, 'id': 123},
 {'colA': 3, 'colB': 4, 'id': 456},
 {'colA': 5, 'colB': 6, 'colC': 5, 'colD': 6, 'id': 789}]
```
