### ISSUE TITLE
Task-based shuffle performance and stability

### ISSUE THREAD

**Issue by dkourilov** [dask/dask#1552]
Hello,

I'm evaluating Dask, and trying to sort an averagely sized (2^26 .. 2^30) dask.DataFrame of random int64, generated in N partitions.

I'm using most up-to-date distribution, provisioned by dask-ec2 (from master branch):

```
dask-ec2 up --name dask --count 3 --type r3.4xlarge --region-name eu-central-1 --ami ami-b1cf39de
```

EC2 AMI used in this evaluation is Ubuntu Trusty with HVM enabled. The instances type is r3.4xlarge.

The workers are run in multi-process mode, with a memory limit per worker process:

```
--nprocs 16 --nthreads 1 --memory-limit 7e9
```

I run following code in IPython notebook on the head node:

```
from dask.distributed import Executor, progress
from dask.array import from_delayed
from dask import delayed, dataframe

import numpy as np
import pandas as pd

TOTAL_RECORDS = (2**30)
NUM_PARTITIONS = (2**8)
PARTITION_SIZE = TOTAL_RECORDS / NUM_PARTITIONS
MAX_VALUE = 1 << 62

def generate_partition():
    points = np.random.randint(low=0, high=MAX_VALUE, size=PARTITION_SIZE)
    return pd.DataFrame({'point': points})

def generate():
    delayed_list = [delayed(generate_partition)() for x in xrange(0, NUM_PARTITIONS)]  
    return dataframe.from_delayed(delayed_list)

e = Executor('localhost:8786')
df = generate()
sorted_df = e.persist(df.set_index('point'))
progress(sorted_df)
```

At the same time, I started Spark 2.0 (Scala 2.10) cluster, provisioned by Databricks. The cluster is running on the same number of nodes, in the same AWS DC, and on the same node type (3x r3.4xlarge).

In Spark, we run exactly the same code snippet but implemented in Scala (generate N random partitions on workers, trigger shuffle with Dataset.sort operation, and persist results in cluster memory).

The observations we have raise a question about efficiency and stability of the Dask shuffle implementation:

```
problem size/    2^30/   2^29/   2^28/   2^28/   
partition size   2^8     2^8     2^10    2^8     

Spark            150.0s  55.3s   46.50s  26.50s  
Dask             *       152.8s  *       74.6s   

                 2^28/   2^27/   2^26/   2^24/
                 2^6     2^6     2^6     2^6

Spark            27.6s   13.7s   7.0s    1.9s
Dask             *       32.1s   15.0s   4.2s

*
Dask could not complete the stage, hangs in the middle with progress not being updated.
This behaviour is stable to reproduce, and looks like a deadlock or task key collision.
Also there are errors in the scheduler log:

$ tail /var/log/dscheduler.log
distributed.scheduler - INFO - Expected data missing from worker: xxx.xxx.xxx.xxx:38424, set(["('shuffle-group-53318b487054e217e6762c23378ff2fb', 2, (19, 6))"])
distributed.scheduler - INFO - Excess keys found on workers: {'xxx.xxx.xxx.xxx
:57457': {'missing': ["('shuffle-group-53318b487054e217e6762c23378ff2fb', 2, (11, 18))"], 'extra': []}, '172.31.24.23:53017': {'missing': ["('shuffle-split-53318b487054e217e6762c23378ff2fb', 2, 6, (24, 18))"], 'extra': []}}
distributed.scheduler - INFO - Expected data missing from worker: xxx.xxx.xxx.xxx
:39060, set(["('shuffle-split-53318b487054e217e6762c23378ff2fb', 2, 18, (11, 14))"])
distributed.scheduler - INFO - Excess keys found on workers: {'xxx.xxx.xxx.xxx
:38424': {'missing': ["('shuffle-group-53318b487054e217e6762c23378ff2fb', 2, (19, 6))"], 'extra': []}}
distributed.core - INFO - Connection from xxx.xxx.xxx.xxx
:35332 to Scheduler
distributed.scheduler - INFO - Excess keys found on workers: {'xxx.xxx.xxx.xxx
:39060': {'missing': ["('shuffle-split-53318b487054e217e6762c23378ff2fb', 2, 18, (11, 14))"], 'extra': []}}
```

Are there any plans to improve the performance and stability of task-based shuffle? 
Can we offer to sponsor this development?

**Comment by mrocklin** [comment]
Hi @dkourilov ,  

First, thank you for the great benchmark and for sharing the results.  This is great. 

If the sorting isn't completing then something is definitely incorrect.  In regards to performance there is definitely some room for improvement; I'm not sure exactly how much.   We would have to do some benchmarking.

In regards to sponsoring development I recommend that we take that conversation offline.  Can I ask you to send me an e-mail at mrocklin at continuum.io.

**Comment by jcrist** [comment]
There have been some performance improvements in shuffle performance in the last few months. Further opportunities for performance gains are being tracked at: https://github.com/dask/distributed/issues/932. Closing for now, feel free to reopen if needed.
