### ISSUE TITLE
dataframe dropna "meta"/kwargs issues in v0.11

### ISSUE THREAD

**Issue by acrosby** [dask/dask#1553]
I am having some trouble trying to `dropna` on a particular dataset I am using. If I issue the command using the arguments that I would for a typical Pandas DataFrame (`stats.dropna(subset=("Count"), how="any")`) I get the following immediately:

```
ValueError: Metadata inference failed, please provide `meta` keyword
```

Which I have seen before,  but it complains that meta isn't an available kwarg if I do incorporate it. It may be a corner case for my specific data file, but unfortunately I can't provide it. Is there an obvious work around that I am missing?

**Comment by jcrist** [comment]
This is a corner case in the inference procedure. These should be fully definable, so failures here should be regarded as a bug. You're right that that error isn't very informative though - it's thrown by a method it calls that does have the `meta` keyword. Will fix.

Can you create a fake file that causes the same failure? I'd start by creating only a few rows with the same dtypes as your data, and see if you can get the error again. Having a reproducible test case will be useful when fixing.

**Comment by acrosby** [comment]
Great, I'll see if I can create a fake file that throws the error.

**Comment by jcrist** [comment]
Ping @acrosby, any luck in creating a reproducible example? Even just knowing the dtype that it fails on might help.

**Comment by acrosby** [comment]
Actually, I can't seem to reproduce the original problem with the original files. The *only* thing I can think of is that perhaps the file was still being held on to by a process that was writing to it, which lead to the inference problem? I have started a test, but it takes a while to get to that step so I don't know for sure yet.

**Comment by acrosby** [comment]
Even with something writing to the file, it is not having a problem anymore...

Please let me know if you learn anything from the code that could point me in the right direction as to what to avoid in the future.

**Comment by jcrist** [comment]
I've pushed a PR to improve the error message on inference failure. The new message will also include the original error and traceback, which should make these inference failures easier to diagnose. https://github.com/dask/dask/pull/1598

Glad everything is working ok (even if we don't know why it was failing before). I'm going to close this for now, feel free to reopen if the error happens again.
