### ISSUE TITLE
Does ddf.pipe() make sense?

### ISSUE THREAD

**Issue by hussainsultan** [dask/dask#1555]
Often times, i end up writing a function that takes in a `dask.dataframe`. pandas implements [`pd.pipe(func)`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pipe.html) that i find pretty convenient.

This is a pretty easy to implement but i think pipe may be pretty confusing in `dask.dataframe` world especially if someone tries to do columnar reductions. Thoughts on if it makes sense to implement?

**Comment by mrocklin** [comment]
cc @tomaugspurger

**Comment by shoyer** [comment]
`pipe` is just sugar that lets you apply a function like a method. So, it seems pretty obvious and sensible to me.

> This is a pretty easy to implement but i think pipe may be pretty confusing in dask.dataframe world especially if someone tries to do columnar reductions.

I'm not sure I understand the concern here. How would this be more confusing for dask.dataframe than for pandas?

**Comment by TomAugspurger** [comment]
I think this makes sense too.

> pipe is just sugar that lets you apply a function like a method

Would dask expect the function to be a delayed function? Or would `pipe` accept any function that takes a`dask.dataframe`?

**Comment by mrocklin** [comment]
I think that dask.dataframe should almost always follow pandas semantics

**Comment by shoyer** [comment]
I would literally copy the implementation of `pipe` from pandas, e.g.,
```
    def pipe(self, func, *args, **kwargs):
        if isinstance(func, tuple):
            func, target = func
            if target in kwargs:
                raise ValueError('%s is both the pipe target and a keyword '
                                 'argument' % target)
            kwargs[target] = self
            return func(*args, **kwargs)
        else:
            return func(self, *args, **kwargs)
```

`df.pipe(func)` should not separately map `func` over partitions no more than calling a `func(df)` does.
