### ISSUE TITLE
dask.bag.map(): "TypeError: apply() got an unexpected keyword argument"

### ISSUE THREAD

**Issue by Grk0** [dask/dask#1572]
Passing keyword arguments to dask.bag.map() doesn't seem to work for me:

```
def f(x, y):
    return {x: y}
testbag = db.from_sequence(['x']).map(f, y='y')
testbag.to_dataframe()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-7387e49cb28a> in <module>()
      2     return {x: y}
      3 testbag = db.from_sequence(['x']).map(f, y='y')
----> 4 testbag.to_dataframe()

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/bag/core.py in to_dataframe(self, columns)
   1118             meta = columns
   1119         else:
-> 1120             head = self.take(1)[0]
   1121             meta = pd.DataFrame([head], columns=columns)
   1122         columns = list(meta.columns)

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/bag/core.py in take(self, k, npartitions, compute)
   1002 
   1003         if compute:
-> 1004             return tuple(b.compute())
   1005         else:
   1006             return b

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     84             Extra keywords to forward to the scheduler ``get`` function.
     85         """
---> 86         return compute(self, **kwargs)[0]
     87 
     88     @classmethod

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180 
    181     results_iter = iter(results)

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, **kwargs)
     81         # Run
     82         result = get_async(apply_async, len(pool._pool), dsk3, keys,
---> 83                            queue=queue, get_id=_process_get_id, **kwargs)
     84     finally:
     85         if cleanup:

/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                     _execute_task(task, data)  # Re-execute locally
    480                 else:
--> 481                     raise(remote_exception(res, tb))
    482             state['cache'][key] = res
    483             finish_task(dsk, key, state, results, keyorder.get)

TypeError: apply() got an unexpected keyword argument 'y'

Traceback
---------
  File "/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/home_local/caichinger/miniconda3/lib/python3.5/site-packages/dask/bag/core.py", line 1667, in safe_take
    r = list(take(n, b))
```

Happens with dask 0.11.0 and conda 4.1.11, Python 3.5.2 on Ubuntu 16.04.

**Comment by jcrist** [comment]
This has to do with some magical behavior in `dask.bag.Bag.map`, where functions with multiple arguments are implicitly applied using `*args`. In pseudocode:

```python
def map(f, bag):
    if takes_multiple_arguments(f):
        return [f(*item) for item in bag]
    else:
        return [f(item) for item in bag]
```

If you make `y` a keyword argument instead of an argument, then your code works:

```python
In [1]: import dask.bag as db

In [2]: def f(x, y=None):
   ...:     return {x: y}
   ...:

In [3]: db.from_sequence(['x']).map(f, y='y').to_dataframe().compute()
Out[3]:
   x
0  y
```

**Comment by jcrist** [comment]
@mrocklin: perhaps it's time to reconsider my argument against this magic behavior (https://github.com/dask/dask/issues/472#issuecomment-125249022). This seems to have enough edge cases that it's hard to understand what's going on. We also don't implicitly do this for other methods either (`filter`, etc...). This has caused a few user issues:

- https://github.com/dask/dask/issues/472
- https://github.com/dask/dask/issues/1062

Alternatively, we could just informatively error when passing in kwargs to functions that take multiple arguments, since it's hard to tell whether we should splat or if the remaining arguments are filled by keywords.

**Comment by mrocklin** [comment]
I'll admit that I remain fond of the magic, but am happy to see it go if it's causing more issues than it has value.  We'll have to be careful about raising informative errors when it goes away.

**Comment by Grk0** [comment]
The source of my problems with Bag.map():
* The actual behavior undocumented and actually contradicts the documentation "Keyword arguments are passed through to func"
* The error message (`apply() got an unexpected keyword argument 'y'`) gave no hint what I was doing wrong

The inconsistency where **kwargs are forwarded to is confusing. Also, what is the difference between the magic map behavior and map_partitions()?

**Comment by MauricioRoman** [comment]
I am also getting a similar error when working through the example Notebooks:

df.B[(df.A > 0) & (df.A < 3)].sum().compute()

--------------------------------------------------------------
TypeError                    Traceback (most recent call last)
<ipython-input-29-2eaa588b03d9> in <module>()
----> 1 df.B[(df.A > 0) & (df.A < 3)].sum().compute()

/home/ec2-user/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.pyc in sum(self, axis, skipna)
   1369     @derived_from(pd.Series)
   1370     def sum(self, axis=None, skipna=True):
-> 1371         return super(Series, self).sum(axis=axis, skipna=skipna)
   1372 
   1373     @derived_from(pd.Series)

/home/ec2-user/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.pyc in sum(self, axis, skipna)
    866     def sum(self, axis=None, skipna=True):
    867         axis = self._validate_axis(axis)
--> 868         meta = self._meta_nonempty.sum(axis=axis, skipna=skipna)
    869         if axis == 1:
    870             return map_partitions(_sum, self, meta=meta,

TypeError: _sum() got an unexpected keyword argument 'skipna'

**Comment by mrocklin** [comment]
What is your version of Pandas and Dask?

**Comment by jcrist** [comment]
@MauricioRoman : I can't seem to replicate on dask 0.11.0, or on the latest release (0.11.1). I suggest reinstalling dask and seeing if it clears up. If not, please open a new issue, this is unrelated to the issue being discussed here (which is about `dask.bag`).
