### ISSUE TITLE
Enable get_dummies for dask

### ISSUE THREAD

**Issue by nsharkey** [dask/dask#1581]
Allow the user to use the Pandas get_dummies function with minimal to no changes for Pandas user experience

**Comment by TomAugspurger** [comment]
I just want to reiterate that users should be *strongly* encouraged to only use `get_dummies` on Categorical dtype. Illustrating the difference, with objects:

```python

In [12]: s = pd.Series(['a', 'b', 'c', 'b', 'b', 'b'])

In [13]: a = dd.from_pandas(s, npartitions=2)

In [14]: pd.get_dummies(a.get_partition(0).compute())
Out[14]:
   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1

In [15]: pd.get_dummies(a.get_partition(1).compute())
Out[15]:
   b
3  1
4  1
5  1
```

With Categoricals

```python
In [16]: s = pd.Series(pd.Categorical(['a', 'b', 'c', 'b', 'b', 'b']))

In [17]: a = dd.from_pandas(s, npartitions=2)

In [18]: pd.get_dummies(a.get_partition(0).compute())
Out[18]:
   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1

In [19]: pd.get_dummies(a.get_partition(1).compute())
Out[19]:
   a  b  c
3  0  1  0
4  0  1  0
5  0  1  0
```

Storing the set of all possible values on the type is necessary to get consistent transformations across partitions.

**Comment by mrocklin** [comment]
@TomAugspurger this related question came up on StackOverflow.  Do you have time to take a quick look?

http://stackoverflow.com/questions/41854492/dask-get-dummies-does-not-transform-variables
