### ISSUE TITLE
groupby.apply + multiprocessing causes error

### ISSUE THREAD

**Issue by abast** [dask/dask#1587]
Running the following code causes an RemoteError for me:

import dask
import pandas as pd
import dask.dataframe as dd
pdf = pd.DataFrame({'A':[1,2,3,4,5], 'B':['1','1','a','a','a']})
ddf = dd.from_pandas(pdf, npartitions = 3)
groups = ddf.groupby('B').apply(lambda x: x).compute(get = dask.multiprocessing.get)

Using the threaded scheduler, this problem does not occur.

I get the following error stack:
  File "<stdin>", line 1, in <module>
  File "/[path_to_anaconda]/lib/python2.7/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/[path_to_anaconda]/lib/python2.7/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "[path_to_anaconda]a/lib/python2.7/site-packages/dask/multiprocessing.py", line 83, in get
    queue=queue, get_id=_process_get_id, **kwargs)
  File "/[path_to_anaconda]/lib/python2.7/site-packages/dask/async.py", line 470, in get_async
    key, res, tb, worker_id = queue.get()
  File "<string>", line 2, in get
  File "/[path_to_anaconda]/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
 ---------------------------------------------------------------------------
Unserializable message: ('#RETURN', (('zpartd-7ec42c1484d311e6b85f782bcb709c3f',), <partd.encode.Encode object at 0x7fe80bd8a250>, None, 1007))
 ---------------------------------------------------------------------------

**Comment by jcrist** [comment]
Thanks for the bug report - I'm able to reproduce on master, although I get an empty dataframe instead of an error.

The issue is due to a bug in partd (a composable key-value store that we use for shuffle operations). We're writing to a buffered file, but not flushing the buffer (a python dictionary) afterwards. For larger datasets the buffer is usually empty, so it just happened to work before. Since the test set is small, the buffer has all the data and the result is an empty dataframe.

**Comment by abast** [comment]
So does this mean, that this error should not occur on larger datasets? Because for me, as far as i can tell, the size of the dataframe doesn't matter: using the multiprocessing scheduler, I always get an error.

**Comment by jcrist** [comment]
It appears you're using an old version of dask (from a comment in a different issue) - try upgrading to the latest version (0.11), or master (`pip install -U git+https://github.com/dask/dask.git`) and running again. You'll also need to upgrade `partd`. I get a wrong answer, but not an error, so there's still a bug here.

Note that if you're loading all the data into memory already, then the task-based shuffle in the distributed scheduler might be more performant here. You can specify this by passing in `shuffle=task` to the groupby call. I recommend using this with the distributed scheduler.

**Comment by jcrist** [comment]
This was fixed in #1625. We plan to cut a release in the next day or so, but if you want to use it now you can install from master:

```
pip install -U git+https://github.com/dask/dask.git
```
