### ISSUE TITLE
warning directly after dask import

### ISSUE THREAD

**Issue by abast** [dask/dask#1588]
After importing dask, I sometimes get the following warning:

[path_to_anaconda]/python2.7/site-packages/psutil/_pslinux.py:338: RuntimeWarning: shared memory stats couldn't be determined and was set to 0
warnings.warn(msg, RuntimeWarning)

Details about the used system:
Dask: 0.10.2
Python version: 2.7.12 |Anaconda custom (64-bit)| (default, Jul 2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform: Linux-2.6.27.19-5-default-x86_64-with-SuSE-11-x86_64
Byte-ordering: little
Detected cores: 40
Default encoding: ascii
Default FS encoding: UTF-8

**Comment by jcrist** [comment]
The warning itself is no big deal - it just means that your psutil didn't find all fields when collecting virtual memory information. I've silenced it here: https://github.com/dask/dask/pull/1589.
