### ISSUE TITLE
dask delayed closure problems

### ISSUE THREAD

**Issue by 0xymor0n** [dask/dask#1600]
here is the code that illustrates the problem i have
```
from dask import delayed, compute

def it():
    for i in range(10):
        yield lambda: i

print ([f() for f in it()]) #this is how i want it to work (expected behaviour)

delFs = [delayed(f)() for f in it()]

print (compute(*delFs)) #this is how it works

print ([f() for f in list(it())])   #it works like this
```

Output:
```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(9, 9, 9, 9, 9, 9, 9, 9, 9, 9)
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
```
Do not know if it is supposed to be an issue.
Is there some way to achieve expected behaviour? Thanks.

**Comment by TomAugspurger** [comment]
This has to do with when python binds names for function. You could use `partial` to ensure your inner function gets the correct `i`.

```python
In [48]: from functools import partial

In [49]: def it():
    ...:     for i in range(10):
    ...:         def f(i):
    ...:             return i
    ...:         yield partial(f, i)
    ...:
    ...:

In [50]: print ([f() for f in list(it())])
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by jcrist** [comment]
Tom is right - the reason your code runs differently is that in the delayed version `i` has iterated to 9 in its scope before any of the `f`'s are actually called. It's an issue with how you're creating the functions, not how dask is using them.

The fix above is the one I would suggest, but can also be done using an extra scope (to illustrate the issue):

```python
In [1]: def it():
   ...:     def make_f(i):
   ...:         return lambda: i
   ...:     for i in range(10):
   ...:         yield make_f(i)
   ...:

In [2]: print([f() for f in list(it())])
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

Given the choice between a partial or a closure, I'd suggest a partial as it will serialize better if you ever need to move to multiprocessing/distributed.

**Comment by jcrist** [comment]
Closing for now, as this isn't an issue with dask - rather it's an issue with how you create your functions.
