### ISSUE TITLE
Bag "pluck" method "default" argument does not return correct value

### ISSUE THREAD

**Issue by WHITSNAK** [dask/dask#1603]
dask version = "0.11.0"

I was trying the below example:

``` python
from dask import bag

d = [{'a':1, 'b':2, 'c':[1,2,3]}] * 3
e = [{'a':1, 'e':2, 'c':[1,2,3]}] * 3

db = bag.from_sequence([d, e, d, d, e])
db = db.concat().pluck('e', default=0)

result = db.compute()
>>> Actual output: [2, 2, 2, None, None, None, 2, 2, 2, 2, 2, 2, None, None, None]
>>> Expected output: [2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0]
```

Not sure if this is expected behavior or not.
But in the mean time I am happy to use below for replacement:
``` python
f = lambda x: x['e'] if 'e' in x else 0
db = db.concat().map(f)
```

**Comment by jcrist** [comment]
Thanks for the bug report, this appears to be a bug in cytoolz.

```python
In [13]: import toolz

In [14]: import cytoolz

In [15]: e
Out[15]:
[{'a': 1, 'c': [1, 2, 3], 'e': 2},
 {'a': 1, 'c': [1, 2, 3], 'e': 2},
 {'a': 1, 'c': [1, 2, 3], 'e': 2}]

In [16]: toolz.pluck('b', e, default=0)
Out[16]: <generator object <genexpr> at 0x111e95050>

In [17]: list(toolz.pluck('b', e, default=0))
Out[17]: [0, 0, 0]

In [18]: list(cytoolz.pluck('b', e, default=0))
Out[18]: [None, None, None]
```

For now, this should work if you uninstall cytoolz (we use toolz as a fallback). Will have a fix there shortly.

**Comment by jcrist** [comment]
Fixed in https://github.com/pytoolz/cytoolz/issues/82.

**Comment by jcrist** [comment]
The fix has been merged into master of cytoolz. You can install it from git with `pip install -U git+https://github.com/pytoolz/cytoolz.git` if you need it now (requires cython and a c compiler to build). Otherwise, we plan to push a release in the next day or two, which will include the fix.
