### ISSUE TITLE
DataFrame tabular repr

### ISSUE THREAD

**Issue by sinhrks** [dask/dask#1604]
Like normal `pd.DataFrame`, it's nice to check `DataFrame` overview via tabular format. 

My idea is adding a table with `divisions`, `columns` and `dtype` to existing string repr as below (without calling `.compute()`). It should also work on console accordingly.

![2016-10-02 10 50 43](https://cloud.githubusercontent.com/assets/1696302/19018044/275b5f60-888e-11e6-861a-97e23f0f6e04.png)

Any ideas?

**Comment by mrocklin** [comment]
I think that something like this would be more engaging, and would match the visual expectations set by Pandas.  I think we'll want to experiment with a few questions like the following:

1.  Do we display dtypes?
2.  How many divisions should we show before we switch to `...`?

**Comment by sinhrks** [comment]
1. I think it is helpful for users to distinguish columns when there are lots. Alternative is all dots ``...``?
2. Truncation should be the same as pandas options (``display.max_rows``).

**Comment by sinhrks** [comment]
@shoyer @TomAugspurger Do you have any suggestion?

**Comment by mrocklin** [comment]
Follow on topic, should we improve the dask.array repr and html repr as well?  It would be interesting to try to convey chunk shape visually in some way.
