### ISSUE TITLE
Deprecate .cache methods

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1607]
The .cache methods put a dask.array or dask.dataframe into a MutableMapping or (in the case of dask.array) an HDF5 file, returning another dask.array or dask.dataframe.  

I believe that these methods are not commonly used and I would like to remove them from the API.  They also overlap a bit with the distributed scheduler's use of `Client.persist`.

**Comment by jcrist** [comment]
I'm fine with that - the functionality doesn't play well with multiprocessing anyway. Probably should add a deprecation warning on next release, and nix it after that.
