### ISSUE TITLE
DataFrame.map_partitions documentation is misleading / incomplete

### ISSUE THREAD

**Issue by stefanseefeld** [dask/dask#1631]
The `DataFrame.map_partitions` documentation doesn't make it clear whether the `columns` argument is needed or not. The main description suggest a value is required (tuple or string), while the argument description then says "Defaults to names of data itself".

Also, no indication is given for what signature the function that's to be applied to the partitions needs to have.

**Comment by jcrist** [comment]
> The DataFrame.map_partitions documentation doesn't make it clear whether the columns argument is needed or not.

Are you using an old version of dask? The columns argument for `map_partitions` was removed a while ago. The description of the `meta` param

> Also, no indication is given for what signature the function that's to be applied to the partitions needs to have.

The first bit of the docstring reads:

```python
"""
Parameters:	
-----------
func : function
    Function applied to each partition.
args, kwargs :
    Arguments and keywords to pass to the function. The partition
    will be the first argument, and these will be passed after.
"""
```

Does this not answer your question? If not, any suggestions for how this can be made clearer?

**Comment by stefanseefeld** [comment]
Indeed, I was looking at the docstrings of a slightly outdated version (0.10.1). Sorry for the noise.
