### ISSUE TITLE
Common chunks in dask.array atop

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1641]
Forking from https://github.com/dask/dask/issues/417

For operations backed by `atop` we currently require that chunks either match exactly, or that some are singletons.

```python
>>> common_blockdim([(3,), (2, 1)])
set([(2, 1)])

>>> common_blockdim([(2, 1), (1, 2)])
ValueError: Chunks do not align {(1, 2), (2, 1)}

>>> common_blockdim([(3, 3), (2, 1, 3)])  # We should probably support this regardless
ValueError: Chunks do not align {(2, 1, 3), (3, 3)}
```

*  Should we relax this?  
*  If so, what is the right way to do this?
*  Should we warn in bad situations?  This opens up opportunities for people to shoot themselves in the foot.

cc @shoyer @jcrist

**Comment by shoyer** [comment]
I am reluctant to relax these requirements by much short of a major overhaul of dask.array. There is no avoiding the need to understand chunking when using the current version of dask.array. Without knowledge of the complete computation graph, it is very difficult to pick appropriate chunk sizes.

**Comment by mrocklin** [comment]
I put together a draft at #1644 as an experiment

The policy it implements is that it automatically expands chunks to fit each axis.  The `common_blockdim` test in that PR is illustrative:

```python
def test_common_blockdim():
    assert common_blockdim([(5,), (5,)]) == (5,)
    assert common_blockdim([(5,), (2, 3,)]) == (2, 3)
    assert common_blockdim([(5, 5), (2, 3, 5)]) == (2, 3, 5)
    assert common_blockdim([(5, 2, 3), (2, 3, 5)]) == (2, 3, 2, 3)

    assert common_blockdim([(1, 2), (2, 1)]) == (1, 1, 1)
    assert common_blockdim([(1, 2, 2), (2, 1, 2), (2, 2, 1)]) == (1, 1, 1, 1, 1)
```

So this is safe in terms of per-task memory use, but is dangerous in that it can significantly expand the number of chunks, especially in the nd-array case.

This is only done in `atop`, which covers a subset of dask.array where we can be more-confident-than-usual that we can rechunk as we like.

**Comment by mrocklin** [comment]
At first glance some of these changes seem pretty tame to me.  For example:

    assert common_blockdim([(5, 5), (2, 3, 5)]) == (2, 3, 5)

Others are somewhat more concerning.  It would be useful to consider fail case applications if anyone has any.

    assert common_blockdim([(1, 2, 2), (2, 1, 2), (2, 2, 1)]) == (1, 1, 1, 1, 1)

**Comment by mrocklin** [comment]
> I am reluctant to relax these requirements by much short of a major overhaul of dask.array. 

@shoyer do your concerns persist if we restrict the relaxation to just `atop`?  Do you have thoughts on problems that might serve as good benchmarks with which we could test the performance of the change proposed in #1644

**Comment by shoyer** [comment]
Maybe it's not so bad to make lots of chunks. Failures are graph construction time are certainly better than failures at compute time.

On the other hand, runtime errors due to running out of memory in graph construction are not very pleasant, either (see the issues with `da.reshape`). Requiring explicit rechunking avoids this. I don't know whether this will actually improve the user experience.

**Comment by mrocklin** [comment]
We could consider warning if the number of chunks increases considerably, such as by a factor of 10.  This wouldn't catch chunk explosions resulting from chained computations, but might allay some of the concern.
