### ISSUE TITLE
slices of memmaps don't concatenate correctly

### ISSUE THREAD

**Issue by rabernat** [dask/dask#1645]
I have several slices of the same underlying numpy.memmap object. I want to concatenate them using dask. As shown in the example below, it doesn't work.

```python
import dask.array as da
import numpy as np

# test data
dtype = 'f8'
data = np.arange(10, dtype=dtype)
# save as memmap
data.tofile('data.bin')
# load as memmap
mm = np.memmap('data.bin', dtype)
# slices of the memmap
mm_slices = [mm[:5], mm[5:]]
# make dask arrays of those slices
da_slices = [da.from_array(mm_sl, chunks=(5,)) for mm_sl in mm_slices]
# concatenate with dask
mm_da = da.concatenate(da_slices)
np.testing.assert_allclose(data, mm_da.compute())
```

This fails with
```
(mismatch 50.0%)
 x: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 y: array([5, 6, 7, 8, 9, 5, 6, 7, 8, 9])
```

The first chunk has been replaced by the second chunk's data. Note this does not happen if I look at the slices individually (e.g. ``da_slices[0].compute()`` gives the correct values). 

I strongly suspect this is related to #1562 and the way that memmaps are tokenized. In fact, these two slices get the same token:
```python
from dask.base import tokenize
print([tokenize(mm_sl) for mm_sl in mm_slices])
>>> ['0053a0dda7a12ecf8ad86dbf62ba1c7c', '0053a0dda7a12ecf8ad86dbf62ba1c7c']
```

This is because the `normalize_array` function checks objects for the `.filename` attribute and uses this to determine the token.
```python
        if hasattr(x, 'mode') and hasattr(x, 'filename'):
            return x.filename, os.path.getmtime(x.filename), x.dtype, x.shape
```
Both these memmaps have the same filename, despite representing different slices, so they get the same token.

Note that the whole point of this is to *avoid reading the data into memory*. In my real application, `data.bin` would be an enormous binary file which I can't fit into memory. So any fix which has to read the whole array in order to tokenize is useless to me. At that point, I might as well use `numpy.concatenate`.

I'm not sure what the solution is here... Maybe I need to bypass `concatenate` and implement a custom function to wrap my data using the lower level constructor for `dask.array.Array`. But regardless, the tokenizing of memmap is still buggy and could cause problems for other users.

**Comment by jcrist** [comment]
Hmmm, that is a problem. I'm not sure if we can fix this with deterministic tokenization, as `mmap` doesn't seem expose any information about the underlying buffer.

For now, why don't you let `dask` handle the slicing for you? This works, and has the hashes work out properly:

```python
In [1]: %load temp.py

In [2]: # %load temp.py
   ...: import dask.array as da
   ...: import numpy as np
   ...:
   ...: # test data
   ...: dtype = 'f8'
   ...: data = np.arange(10, dtype=dtype)
   ...: # save as memmap
   ...: data.tofile('data.bin')
   ...: # load as memmap
   ...: mm = np.memmap('data.bin', dtype)
   ...: dmm = da.from_array(mm, chunks=5)
   ...: # make dask arrays of those slices
   ...: da_slices = [dmm[:5], dmm[5:]]
   ...: # concatenate with dask
   ...: mm_da = da.concatenate(da_slices)
   ...: np.testing.assert_allclose(data, mm_da.compute())
```

**Comment by jcrist** [comment]
Fixed by #1646. I added the strides, shape, and pointer offset to the hash. This should fully define each array, fixing the issue.

```python
In [2]: # %load temp.py
   ...: import dask.array as da
   ...: import numpy as np
   ...:
   ...: # test data
   ...: dtype = 'f8'
   ...: data = np.arange(10, dtype=dtype)
   ...: # save as memmap
   ...: data.tofile('data.bin')
   ...: # load as memmap
   ...: mm = np.memmap('data.bin', dtype)
   ...: # slices of the memmap
   ...: mm_slices = [mm[:5], mm[5:]]
   ...: # make dask arrays of those slices
   ...: da_slices = [da.from_array(mm_sl, chunks=(5,)) for mm_sl in mm_slices]
   ...: # concatenate with dask
   ...: mm_da = da.concatenate(da_slices)
   ...: mm_da.compute()
   ...:
Out[2]: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [3]: np.testing.assert_allclose(data, mm_da.compute())
```

**Comment by rabernat** [comment]
Wow that was fast! Thanks @jcrist!

**Comment by rabernat** [comment]
Wow so fast! Thanks @jcrist!
