### ISSUE TITLE
array.concatenate changes dtype endianness

### ISSUE THREAD

**Issue by rabernat** [dask/dask#1647]
I often have to work with binary data with non-native endianness. I found that when I concatenate dask with big-endian datatypes, the resulting array is native (little) endian.

```python
import dask.array as da
import numpy as np

arrays = 2*[np.arange(4, dtype='>f4')]
darrays = [da.from_array(a, (4,)) for a in arrays]
concat = da.concatenate(darrays)
print(darrays[0].dtype, concat.dtype)
>>> (dtype('>f4'), dtype('float32'))
```

The numerical values of `concat` are correct, indicating it has been recast. But I don't necessarily want this to happen.

I know this is very obscure. Would you consider it a bug?

**Comment by mrocklin** [comment]
If this deviates from NumPy behavior then it doesn't seem particularly
obscure

**Comment by rabernat** [comment]
In fact I just realized it does *not* deviate from numpy behavior. So probably best to close this and for me to find another solution.

**Comment by jcrist** [comment]
I'd say so - `dask.array` tries to match numpy behavior wherever possible. Perhaps take a look at `byteswap` http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.byteswap.html? This could be easily added to `dask.array` if needed.
