### ISSUE TITLE
dask / pandas categorical transformation differences

### ISSUE THREAD

**Issue by littlegreenbean33** [dask/dask#1650]
Bear in mind my nickname. First post here. Apologies if  I do not completely follow the nettiquete.

This is in relation to [(https://stackoverflow.com/questions/39958065/dask-pandas-categorical-transformation-differences)]

I am reading a ( larger than memory) csv file that then I categorize in dask. The cat.categories result is different if I had follow the same process using pandas. Specifically in the nan values, which pandas does not include and dask does include.

The whole objective of the exercise was to convert very large csv files with categorical data, into something that actually fits in memory.

I notice this while saving into HDF5, where dask uses pandas libraries and I get a future warning message.

If I understand dask is trying to mimic pandas behavior I believe this is a place where things could be improved.

**Comment by jcrist** [comment]
I believe this was fixed recently in https://github.com/dask/dask/pull/1578. Can you try re-running with master? You can install it easily with `pip install -U git+https://github.com/dask/dask.git`.

**Comment by littlegreenbean33** [comment]
@jcrist   Yes, this works as expected now.
Cheers.
