### ISSUE TITLE
Result of `.compute()` operation exceeds memory limits

### ISSUE THREAD

**Issue by gbrener** [dask/dask#1662]
Hey `dask` contributors, sometimes it's difficult to anticipate whether the result of a `.compute()` operation will end up exceeding memory limits.

I'm creating an issue because there's potential for `dask` to be able to help out here, for example by issuing a warning when a user tries to create a very large result.

Or, it might be useful to provide a way to inspect a partially-computed `dask` array for the purpose of determining whether the results are desirable; perhaps this would be easier.

**Comment by mrocklin** [comment]
I see two things here:

Dask.array.compute could warn when `.nbytes` would return a value greater than total memory (as determined by an optional call to `psutil.virtual_memory().total`.  NumPy does this sometimes.

@gbrener you can partially compute a dask.array by computing a slice:

    x[:10].compute()

**Comment by jcrist** [comment]
That's an interesting idea. A few caveats:

- We'd only be able to do that in `array.compute` (and maybe if we hacked it into `dask.compute`, but I'd be slightly against that).
- It would only be able to catch cases where the output was large, not the intermediates.

If these are acceptable, then adding that check seems fine to me.

**Comment by jcrist** [comment]
Since this is hard to do generally (can't tell if intermediates will overflow), and a partial solution may be confusing to users (dask didn't error, but more memory was still used), I'm closing for now. Feel free to reopen if desired.
