### ISSUE TITLE
Add tree-reductions for `dd.quantile`

### ISSUE THREAD

**Issue by jcrist** [dask/dask#1672]
In #1663 we added tree-reductions to most `dask.dataframe` reductions. However, a few remain:

~~- `df.corr` and `df.cov`. These are done using the same function, which is based on the formulas in this paper: http://prod.sandia.gov/techlib/access-control.cgi/2008/086212.pdf. Adding a `combine` function for these reductions just requires a bit of math.~~ (edit, fixed in #1758).
- `dd.quantile`. This requires porting the `quantile` functionality to use `aca` or `_Frame.reduction` instead of its own custom graph creation.

**Comment by mrocklin** [comment]
I believe that this was done

**Comment by jcrist** [comment]
No, quantile is still missing tree reductions.

**Comment by jakirkham** [comment]
Is this still relevant @jcrist?

**Comment by jcrist** [comment]
Quantile doesn't implement tree reductions, but I'm not sure if that has any noticeable performance impact. Tree reductions are turned off for most dataframe computations anyway by default. I'd be fine closing this for now and reopening if it ever becomes useful for someone.
