### ISSUE TITLE
Dask has no 'read_table()` function? 

### ISSUE THREAD

**Issue by evanbiederstedt** [dask/dask#1673]
I am trying to import the following file with dask:

    import dask.dataframe as dd
    file = dd.read_table("filename...")

Here's the error I receive

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'dask.dataframe' has no attribute 'read_table'

**Comment by mrocklin** [comment]
Does dd.read_csv work for you?

**Comment by evanbiederstedt** [comment]
@mrocklin Yes, `dd.read_csv()` works, but not for this dataset. It is possible for files this size to convert to csv via pandas first, but that may not be the case in the future.

**Comment by jcrist** [comment]
This should be fairly easy support with a refactor of dask's `read_csv`. Under the hood, `read_table` and `read_csv` are implemented by much of the same functionality in pandas. Working on it now.

**Comment by evanbiederstedt** [comment]
@jcrist Thanks! That would be awesome. 

I just converted several TB of files into csv format in order to use `dd.read_csv`. That feels silly.

**Comment by jcrist** [comment]
I still need to add tests, but hand-testing, this is done in #1682. Feel free to try it out:

```python
In [1]: import pandas as pd

In [2]: df = pd.util.testing.makeTimeDataFrame(nper=10000, freq='d')

In [3]: df.to_csv('test.table', sep='\t')

In [4]: import dask.dataframe as dd

In [5]: ddf = dd.read_table('test.table')

In [6]: ddf.head()
Out[6]:
   Unnamed: 0         A         B         C         D
0  2000-01-01 -0.536249  0.164949 -0.177234 -0.012274
1  2000-01-02  1.008533 -0.339272 -0.559791 -1.468960
2  2000-01-03 -0.097426  0.412881  0.047888 -0.177689
3  2000-01-04 -0.827059 -1.672267  0.102813 -0.745098
4  2000-01-05 -1.336592  1.169739 -0.239363 -1.347392

In [7]: pd.read_table('test.table').head()
Out[7]:
   Unnamed: 0         A         B         C         D
0  2000-01-01 -0.536249  0.164949 -0.177234 -0.012274
1  2000-01-02  1.008533 -0.339272 -0.559791 -1.468960
2  2000-01-03 -0.097426  0.412881  0.047888 -0.177689
3  2000-01-04 -0.827059 -1.672267  0.102813 -0.745098
4  2000-01-05 -1.336592  1.169739 -0.239363 -1.347392
```

**Comment by evanbiederstedt** [comment]
@jcrist Thanks for this! I'll give it a swing
