### ISSUE TITLE
Join dask.DataFrame with dask.Series

### ISSUE THREAD

**Issue by michaldul** [dask/dask#1677]
Dask docs says it's possible to join dataframe with "DataFrame, Series with name field set, or list of DataFrame":
http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.join

while according to code it clearly not possible:
https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2267

Is documentation outdated?

**Comment by mrocklin** [comment]
Yeah, we should probably expand that check to include series and verify that it works (I suspect that it does).  Do you have any interest in trying this out and contributing a solution?

Regarding docstrings we often end up stealing the Pandas docstring.  It would be great to have people go through and actually write the docstrings properly, making note of the variations of behavior.

**Comment by michaldul** [comment]
Yes, I will try out expanding that check.

**Comment by mrocklin** [comment]
Thanks!

**Comment by michaldul** [comment]
Expanding that check is not enough and more work is required in dask/dataframe/multi.py. Eventually Series is passed to pd.merge which accepts only DataFrame. If something useful come out of my tests I'll create PR.


________________________________

**Comment by mrocklin** [comment]
I suspect (but have not verified) that this works today.  Please feel free to ping and I'll reopen if this is not the case.

**Comment by racinmat** [comment]
Still, in version 1.1.1 I need to convert the Series to DataFrame by calling the `to_frame` method. If the direct  series joining will not be supported, it would nice to mention it in the documentation, which still states that you can join Series, which is confusing.

**Comment by TomAugspurger** [comment]
Are you interested in making a pull request to do the `to_frame()` on the
Series inside of `dd.join`?
