### ISSUE TITLE
Custom graph to read dataframes fails while pd.read_csv succeeds

### ISSUE THREAD

**Issue by bmaisonn** [dask/dask#1680]
Hi,

If i try to read a csv file with pandas i have no error

```
pd.read_csv('~/myfile.txt, ';', None, 'infer', None, None, ColumnsToKeep, False, None, True, None, None, 
                    None, None, None, False, None, None, None, True, True, False, True, 
                    False, False, False, None, False, False, None, 'infer', None, '.', None, 
                    '"', 0, None, None, 'utf-8', None, False, True, True, 0, 0, 
                    True, False, False, False, False, True, None, False, None)
```

If i try to read several files with the same format using dask custom graphs, it fails:

```
dsk[('mydf', 0)] = (pd.read_csv, '~/myfile1.txt, , ';', None, 'infer', None, None, ColumnsToKeep, False, None, True, None, None, 
                    None, None, None, False, None, None, None, True, True, False, True, 
                    False, False, False, None, False, False, None, 'infer', None, '.', None, 
                    '"', 0, None, None, 'utf-8', None, False, True, True, 0, 0, 
                    True, False, False, False, False, True, None, False, None) 

dsk[('mydf', 1)] = (pd.read_csv, '~/myfile2.txt', , ';', None, 'infer', None, None, ColumnsToKeep, False, None, True, None, None, 
                    None, None, None, False, None, None, None, True, True, False, True, 
                    False, False, False, None, False, False, None, 'infer', None, '.', None, 
                    '"', 0, None, None, 'utf-8', None, False, True, True, 0, 0, 
                    True, False, False, False, False, True, None, False, None)

name = 'mydf' 
columns = ['col1', 'col2']
empty_df = pd.DataFrame(columns=columns)
df = dd.DataFrame(dsk, name, empty_df, divisions) 

#Connect to Scheduler 
client = Client(SchedulerAddress) 
#Load Files 
df = client.persist(df) 
distributed.wait(df, timeout=None, return_when='ALL_COMPLETED') 
 
res = client.compute(df.map_partitions(atomic_jw)).result()
```

When i execute that last line, the following error occurs:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/distributed/client.py", line 109, in result
>     six.reraise(*result)
>   File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 645, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 388, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 702, in __init__
>     kwds['delimiter'] = dialect.delimiter
> AttributeError: 'str' object has no attribute 'delimiter'
> 

On the worker console the below error is displayed:

> distributed.worker - WARNING -  Compute Failed
> Function: read_csv
> args:     ('~/myfile2.txt', ';', None, 0, None, False, [1, 2], False, None, True, None, None, None, None, None, False, None, None, None, None, True, True, False, True, False, False, False, None, False, False, None, 'infer', None, '.', None, '"', 0, None, None, 'utf-8', None, False, True, True, 0, True, False, False, False, False, True, None, False, None)
> kwargs:   {}
> NoneType
> 

Note that this error happens since with migrated our code to the latest version of dask

Regards,

Bertrand

**Comment by jcrist** [comment]
I suspect this is due to your upgrade of dask upgrading pandas, and the keyword order of pandas read_csv switching around. When passing in keywords, I recommend using either `apply`, or a custom function that takes keywords as a dictionary. This lets you pass them as keywords, rather than relying on the order staying consistent:

```python
# Using apply
dsk[('mydf', 0)] = (apply, pd.read_csv, ['~/myfile1.txt], {'usecols': ColumnsToKeep, ...})

# Using a custom function
def my_readcsv(path, kwargs):
    return pd.read_csv(path, **kwargs)

dsk[('mydf', 0)] = (my_readcsv, '~/myfile1.txt', {'usecols': ColumnsToKeep, ...})
```

However, I recommend avoiding building custom graphs yourself, and using [dask.delayed](http://dask.pydata.org/en/latest/delayed.html) instead. This lets you write code that looks like normal python code, and builds up a dask-graph for you:

```python
from dask import delayed

@delayed(pure=True)
def my_readcsv(path, **kwargs):
    return pd.read_csv(path, **kwargs)

parts = [my_readcsv(path, usecols=ColumnsToKeep, ...) for path in file_paths]

# If you're then converting these parts into a dask-dataframe, you can use `dd.from_delayed`:
import dask.dataframe as dd
df = dd.from_delayed(parts, meta=an_empty_dataframe_that_matches_your_schema)
# Note: if you the index of your partitions is meaningful, and you know the start/end
# of each partition, you can also pass in `divisions` to from_delayed as a list of
# [start_of_part_1, start_of_part_2, ...,  start_of_last_part, end_of_last_part].
# This allows certain operations in dask.dataframe to be much more efficient.
```

**Comment by bmaisonn** [comment]
Hi,
The solution that you suggested worked perfectly.
Thx!
Bertrand

**Comment by jcrist** [comment]
Glad to hear you got it working. Closing.
