### ISSUE TITLE
Store Categorical Series with Codes Partitions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1686]
Currently we represent a dd.Series of categorical dtype as several pd.Series of categorical dtype, each storing all of the categories.  This is a simple and straightforward solution.

An alternative solution would be to keep the categories on the dd.Series only and represent each partition as just a Series of codes.  In the case of many categories this would help to reduce costs.

I'm not sure this is worth the code complexity, but thought I'd bring up the idea for discussion.

**Comment by jcrist** [comment]
I'd be worried about doing this robustly, and think this might be hard to get right, especially with user-defined functions (`map_partitions`, `reduction`, etc...). With the recent addition of non-uniform categoricals, having each partition only contain the mappings that they use might help reduce memory/serialization costs enough, without requiring us to manage the mappings ourselves.
