### ISSUE TITLE
Optimization-specific keyword arguments

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1688]
Optimizations are both essential for efficient computations and frequently get in the way.

We've allowed a little bit of customization by allowing users to turn them off with the `optimize_graph=True` keyword to `compute()`.  However users also want to turn on or off or send keyword arguments down to specific optimizations.  For example "don't fuse in dask.array" or "send the `keys=['x', 'y']` keyword to the `fuse` function".  The problem is that these optimizations are hard coded and hidden within the collection's `._optimize` method and so are difficult to reach.

There are a few options here:

1.  We could arrange the optimizations in some sort of data structure rather than a method (Theano does this)
2.  We could develop a convention to send keyword arguments to specific optimizations.  For example like sklearn we could prepend the name of the optimization to the keyword argument:

    ```python
    x.compute(fuse_keys=['x', 'y'], inline_functions_fast_functions={inc, dec})
    ```
3.  ??

**Comment by mrocklin** [comment]
(I accidentally hit submit early, the title comment is now populated with actual content)

Currently I'm in favor of option 2.  Would love to hear other options:

cc @jcrist @shoyer

**Comment by jcrist** [comment]
Hmmm, I'm not sure. Perhaps just enforce that optimizations accept `**kwargs``, and can ignore any keywords that don't apply to them?

Pro:
- simple to implement, just splat all kwargs to all optimizations
- no need to duplicate keywords to optimizations if they're the same `fuse_keys=['x', 'y'], other_opt_keys=['x', 'y'], ...`

Con:
- Things that may be different must have different keyword names.

The best option might be to mix these. If prefixed by an optimization name, then forward to only that optimization, otherwise forward to all optimizations?

**Comment by mrocklin** [comment]
Yeah, as it turns out `fuse_keys` and `cull_keys` are quite different.

The `fuse_keys=` option is also simple to implement if we do it naively:

### Before

```python
def optimize(dsk, keys, **kwargs):
    """ Optimize dask for array computation

    1.  Cull tasks not necessary to evaluate keys
    2.  Remove full slicing, e.g. x[:]
    3.  Inline fast functions like getitem and np.transpose
    """
    keys = list(flatten(keys))
    fast_functions = kwargs.get('fast_functions',
                                set([getarray, getarray_nofancy, np.transpose]))
    dsk2, dependencies = cull(dsk, keys)
    dsk4, dependencies = fuse(dsk2, keys, dependencies)
    dsk5 = optimize_slices(dsk4)
    dsk6 = inline_functions(dsk5, keys, fast_functions=fast_functions,
                            dependencies=dependencies)
    return dsk6
```

### After

```python
def optimize(dsk, keys, fuse_keys=None, inline_functions_fast_functions={getarray, getarray_nofancy, np.transpose}, cull_dependencies=None):
    """ Optimize dask for array computation

    1.  Cull tasks not necessary to evaluate keys
    2.  Remove full slicing, e.g. x[:]
    3.  Inline fast functions like getitem and np.transpose
    """
    keys = list(flatten(keys))
    dsk2, dependencies = cull(dsk, keys, dependencies=cull_dependencies)
    dsk4, dependencies = fuse(dsk2, keys + (fuse_keys or []), dependencies)
    dsk5 = optimize_slices(dsk4)
    dsk6 = inline_functions(dsk5, keys, fast_functions=inline_functions_fast_functions,
                            dependencies=dependencies)
    return dsk6
```
