### ISSUE TITLE
Support for swig

### ISSUE THREAD

**Issue by akcheung** [dask/dask#1691]
I am using dask to delay calling to some swig functions and I got `TypeError: can't pickle SwigPyObject objects` when trying to call `Executor.submit`. Does dask support swig?

**Comment by mrocklin** [comment]
Dask uses pickle or cloudpickle to serialize functions.  I would have thought that Swig supported standard serialization techniques.  Is this not true?

Can you provide a failing example, perhaps with a common library that uses swig?

**Comment by mrocklin** [comment]
Any further information on this?

**Comment by akcheung** [comment]
@parmitam and I just uploaded a VM [here](https://homes.cs.washington.edu/~akcheung/lsst_ubuntu.tar.gz) (username/pw: ubuntu/ubuntu). `~ubuntu/dask/run.py` contains a short pipeline implemented on top of the [LSST framework](http://dm.lsst.org/). When run it gets stuck on line 468 when executing `e.submit`. The non-dask version runs fine, and we currently don't have an idea whether that is a swig problem, a LSST bug, a dask bug, or simply us misunderstanding how dask works.

Sorry that we weren't able to create a shorter pipeline. Feel free to poke around, but we also understand that this might be too involved and if so feel free to pass as well.

**Comment by mrocklin** [comment]
Yeah, I'm personally unlikely to dive through a VM to help diagnose this.

A quick googling of the problem also leads to this stackoverflow question, which may be of use:

http://stackoverflow.com/questions/9310053/how-to-make-my-swig-extension-module-work-with-pickle

**Comment by jcrist** [comment]
This appears to not be an issue with dask, just a lack of pickle support in your swig code. Closing for now, feel free to reopen if needed.
