### ISSUE TITLE
DataFrame.__getitem__ on multilevel columns fails

### ISSUE THREAD

**Issue by chmp** [dask/dask#1695]
Test case:

```python
def test_getitem_multilevel():
    pdf = pd.DataFrame({('A', '0') : [1,2,2]})
    ddf = dd.from_pandas(pdf, npartitions=3)

    assert_eq(pdf['A', '0'], ddf['A', '0'])

# result:
# E       NotImplementedError: ('A', '0')
```

**Comment by chmp** [comment]
Strange, I have been using that syntax for quite some time now.

```
In [1]: import pandas as pd

In [2]: pdf = pd.DataFrame({('A', '0') : [1,2,2]})
   ...: 

In [3]: pdf['A', '0']
Out[3]: 
0    1
1    2
2    2
Name: (A, 0), dtype: int64

In [4]: pdf.loc[('A', '0')]
---------------------------------------------------------------------------
<Traceback removed>

KeyError: 'the label [A] is not in the [index]'
```

However, I have to admit pandas is overwhelming at times.

**Comment by jreback** [comment]
@chmp you are referring to the *index* in that case, ``pdf.loc[:, ('A', '0')]`` is the column accessor

**Comment by chmp** [comment]
@jreback you can leave out the parens. Any multi argument list in `obj[ ]` is implicitly passed a tuple:

```python
In [5]: class klass(object):
   ...:     def __getitem__(self, key):
   ...:         return key
   ...:     

In [6]: obj = klass()

In [7]: repr(obj['a', 'b'])
Out[7]: "('a', 'b')"

In [8]: type(obj['a', 'b'])
Out[8]: tuple
```

**Comment by jreback** [comment]
of course, but this is a convenience feature in pandas that is not completely unambiguous, so you should *never* do that (even though there are times you can)

**Comment by chmp** [comment]
Sorry, I seem to have misunderstood you. To be honest, I am somewhat confused by now. Your recommendation is to only use `df.loc[:, ('A', '0')]`? 

Regarding the issue: since pandas does support using tuples for getting the column, should dask support it too?
