### ISSUE TITLE
Use repartition to increase the number of partitions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1699]
This works fine when the user supplies divisions but doesn't work otherwise.

**Comment by kayibal** [comment]
Would be very useful! Is there any workaround for this limitation atm?
Tried this but doesn't work because the delayed returns a dask dataframe.
Maybe I could construct a dask.DataFrame from the delayed object manually?
```
fut = dd.from_delayed(delayed(dd.from_pandas)(big_intermediate, chunksize=2))
```

**Comment by abast** [comment]
Would be super useful. I think, it worked some versions ago.

**Comment by abast** [comment]
Was this issue specifically about `dask.bag`? What about `dask.dataframe`?
