### ISSUE TITLE
Dataframe API: to_hdf not mentioned in table of contents

### ISSUE THREAD

**Issue by abast** [dask/dask#1700]
The documentation about `to_hdf` is in the API:
http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.read_hdf

However, it is not listed in the table of contents:
http://dask.pydata.org/en/latest/dataframe-api.html#create-dataframes

**Comment by jcrist** [comment]
I assume you mean `read_hdf` (as you linked to), instead of `to_hdf`. `to_hdf` was already in the docs, but I added the missing `read_*` functions in eb6aac7. Closing.

**Comment by abast** [comment]
You are right of course, I was talking about read_hdf...
