### ISSUE TITLE
saving dataframe generated via from_delayed in parallel to hdf5 fails

### ISSUE THREAD

**Issue by abast** [dask/dask#1704]
I tried saving a dataframe generated via `from_delayed` to hdf. I tried all schedulers. Additionally, I tried saving to several files (asterisk in path) or to several nodes (asterisk in node). In none of the cases, the result was as expected. I tested this on the master branch. To make it short:
- I was unable to save in parallel using the multiprocessing scheduler.
- The distributed scheduler throws rather uninformative errors. However, if `lock`is set to `False`and the asterix is provided in the path, everything works apparently fine. Is it safe to disable the lock?

Now the details.
## create example dataframe

```
import tempfile
import shutil
import os
import random
import string
import numpy as np
import pandas as pd
import dask
import dask.dataframe as dd
import distributed 
from multiprocessing import Lock

#generate test dataframe, containing a variety of data
rowsPerPartition = 5000
npartitions = 500

def pdfGenerator(nrows):
    '''generates pandas dataframe containing dtypes float64, int64 and object (random text)'''
    randomTextGenerator = lambda length: "".join( [random.choice(string.letters + string.digits) for i in xrange(length)] )
    textColumn1 = map(randomTextGenerator, [50]*nrows)
    floatColumn1 = np.random.uniform(-100, 100, nrows)
    intColumn1 = np.random.randint(-100, 100, nrows)
    return pd.DataFrame({'t': textColumn1, 'f': floatColumn1, 'i': intColumn1})

d = dask.delayed(pdfGenerator(rowsPerPartition))
ddf = dd.from_delayed([d]*npartitions)
```
## threaded and multiprocessing scheduler use only one core

```
#save to hdf5, many files
print('multiprocessing scheduler, save to many hdf5 files:')
path = tempfile.mkdtemp()
%time ddf.to_hdf(os.path.join(path, 'a*.h5'), '/test', get = dask.multiprocessing.get, complib = 'blosc')
shutil.rmtree(path)
print('')

print('multithreading scheduler, save to many hdf5 files:')
path = tempfile.mkdtemp()
%time ddf.to_hdf(os.path.join(path, 'a*.h5'), '/test', get = dask.threaded.get, complib = 'blosc')
shutil.rmtree(path)
print('')

#save to hdf5, many nodes
print('multiprocessing, from delayed, many hdf5 nodes:')
path = tempfile.mkdtemp()
%time ddf.to_hdf(os.path.join(path, 'a.h5'), '/test*', get = dask.multiprocessing.get, complib = 'blosc')
shutil.rmtree(path)
print('')

print('threaded, from delayed, many hdf5 nodes:')
path = tempfile.mkdtemp()
%time ddf.to_hdf(os.path.join(path, 'a.h5'), '/test*', get = dask.threaded.get, complib = 'blosc')
shutil.rmtree(path)
print('')
```

> multiprocessing scheduler, save to many hdf5 files:
> CPU times: user 22.3 s, sys: 5.52 s, total: 27.8 s
> Wall time: 25.2 s
> 
> multithreading scheduler, save to many hdf5 files:
> CPU times: user 16.3 s, sys: 2.32 s, total: 18.6 s
> Wall time: 17.3 s
> 
> multiprocessing, from delayed, many hdf5 nodes:
> CPU times: user 44.6 s, sys: 10.3 s, total: 55 s
> Wall time: 51.5 s
> 
> threaded, from delayed, many hdf5 nodes:
> CPU times: user 17.9 s, sys: 2.99 s, total: 20.9 s
> Wall time: 19.5 s

At least, I would expected the multiprocessing scheduler to work in parallel.
## The distributed scheduler requires a lot of trail and error

Using the distributed scheduler, it is possible to save in parallel, but only if:
- lock = False (is this risky?)
- asterix in path and not in node

```
print('distributed, from delayed, save to many hdf5 files:')
path = tempfile.mkdtemp()
#needs lock = False, otherwise: can't pickle thread.lock objects. 
#lock = True or lock = multiprocessing.Lock() does not work.
%time ddf.to_hdf(os.path.join(path, 'a*.h5'), '/test', get = c.get, complib = 'blosc', lock = False) 
shutil.rmtree(path)
print('')
```

> distributed, from delayed, save to many hdf5 files:
> CPU times: user 1.62 s, sys: 152 ms, total: 1.77 s
> Wall time: 2.33 s

In the case that the asterix is provided in the node, I got unlcear / confusing error messages: 

```
#Causes error, no matter what:
#lock = False --> HDF5-Error
#lock = True --> TypeError: can't pickle thread.lock objects
#lock = None --> TypeError: can't pickle thread.lock objects
#lock = multiprocessing.Lock() --> EOFError
print('distributed, from delayed, many hdf5 nodes:')
path = tempfile.mkdtemp()
%time ddf.to_hdf(os.path.join(path, 'a.h5'), '/test*', get = c.get, complib = 'blosc', lock = None)
shutil.rmtree(path)
print('')
```
## Misc
- Writing in parallel to csv works out of the box, if the distributed scheduler is set as default. 
- Writing in parallel to hdf using the multiprocessing scheduler works, if the dataframe is generated via from_csv.
- If `repartition` is used on a dataframe generated via from_csv, it cannot be saved in parallel any more using the multiprocessing scheduler (this was my original problem).

**Comment by jakirkham** [comment]
As far as locking is concerned, probably worth trekking over to issue ( https://github.com/dask/distributed/issues/780 ).

**Comment by abast** [comment]
Coming back to this after one year, the problems I mentioned here are tracked in other issues in a more concise way.
