### ISSUE TITLE
Bag.read_text much slower than DataFrame.read_csv

### ISSUE THREAD

**Issue by michaldul** [dask/dask#1707]
Playing with DataFrame and Bag I found out that the same ~500 MB file was loading into memory way longer with Bag.read_text compared to DataFrame.read_csv:
```
import dask.dataframe as dd

if __name__ == '__main__':
    _ = dd.read_csv("./data.csv").compute()
```
execution time: 0min 4s
```
import dask.bag as db

if __name__ == '__main__':
    _ = db.read_text("./data.csv").compute()
```
execution time: 2min 37s

using much more memory as well (hundreds of MB vs ~8 GB).

I found out that program spends most of time on serialization of decode() result from dask\bag\text.py. Replacing cloudpickle with pickle results with execution time of 29s, with memory usage about 3 GB.

Is it known issue?

My environment is Python 3.5.1 :: Anaconda 4.1.0 (64-bit) on Windows 10. I use dask from master branch. data.csv is clicks_tests.csv from https://www.kaggle.com/c/outbrain-click-prediction/data

**Comment by mrocklin** [comment]
I suspect that this is all just interprocess communication.  

How about the following:

    db.read_text('.data.csv').count().compute()

**Comment by michaldul** [comment]
You are right, 5s. Can you explain why does this help?

**Comment by mrocklin** [comment]
The cost isn't in `read_text`, it's in pulling the data back from the worker python process to the main process when calling `.compute()`.  This incurs a pickle and IPC roundtrip, both of which are slower than reading from disk.  It's much better to leave the data on the worker and do processing there, such as by using `Bag.map` methods or other dask functionality.

**Comment by mrocklin** [comment]
Ideally, you want `.compute()` to return a small result.

**Comment by michaldul** [comment]
Thank you. I guess this issue should be closed.

**Comment by mrocklin** [comment]
You might find the following document of use: http://dask.pydata.org/en/latest/scheduler-choice.html
