### ISSUE TITLE
Avoid using x.dtype in dask.array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1718]
We sometimes use the `.dtype` property within dask.array which can sometimes trigger computation.  We should use `._dtype` instead.

**Comment by jcrist** [comment]
I'm took a brief look through this, and am wondering if there's a reason why we don't make known dtype strict here, as we did in `dask.dataframe`. The only places I can see where unknown dtype may appear is in user provided functions (e.g. `map_blocks`). `dtype` inference similar to what we did for `dask.dataframe` could also work here. This seems easier to me than trying to find all the places where we accidentally trigger computation.

**Comment by mrocklin** [comment]
I would be open to trying the function.  I would also be open to requiring explicit dtypes.

FWIW I think that this is fairly low priority

**Comment by shoyer** [comment]
Yes, I like requiring explicit dtypes. Trigger computation with `.dtype` can be problematic if it's expensive -- users have encountered this when using when using dask.array in xarray.

**Comment by mrocklin** [comment]
@shoyer you'd prefer that dask.array err early?

**Comment by shoyer** [comment]
I think so. It's not hard to require a dtype in map_blocks.
