### ISSUE TITLE
da.ufunc DataFrame support follow-up

### ISSUE THREAD

**Issue by sinhrks** [dask/dask#1723]
Follow up of #1669. May needs to improve `Array` dtype inference to clean up the logic (#1718).
- [ ]  `frexp`, `modf`
- [ ] `Index` with `bool` dtype

**Comment by mrocklin** [comment]
I'm not sure how to interpret this issue.  Closing for now.  If it remains an issue please feel free to reopen.

**Comment by mrocklin** [comment]
Ah, sorry, I just noticed the checklist, which has more information.

**Comment by jakirkham** [comment]
@mrocklin, do you know if is this still relevant? If so, would you be able to expound upon the original request. Unfortunately I'm also having a hard time following it.

**Comment by mrocklin** [comment]
I'm not interested in engaging on this issue

**Comment by jakirkham** [comment]
Alright I'm going to close for now. No objection though to it being reopened. Would be good if there was some clarification on the ask if that happens.
