### ISSUE TITLE
CI/PERF: Add performance benchmarks

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#1733]
There seem to be a decent number of issues around performance and graph optimization. Having a suite of benchmarks can help with tracking performance across revisions.

[asv](http://asv.readthedocs.io/en/latest/) is popular among scientific python projects. Pandas recently switched to it and things are working well.

If people are interested, then I'll volunteer to do the setup work.

**Comment by mrocklin** [comment]
Definitely interested.  If you set up a scaffold I'll also be happy to pitch in and contribute benchmarks.

**Comment by TomAugspurger** [comment]
See https://github.com/dask/dask-benchmarks
