### ISSUE TITLE
Investigate sparse matrices

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#174]
Some questions for anyone who happens along:

1.  For what applications do people use large sparse matrices?
2.  How do they store these matrices?
3.  What operations do they need?
4.  What do blocked algorithms tend to look like in this case?

I can imagine a few solutions but I'm likely to build the wrong thing without hearing from people first.  This might require a little research.

**Comment by tkelman** [comment]
1. Anything where the interactions are not all-to-all, and the problem size is large enough that taking that structure into account matters for performance. Linear and nonlinear optimization, finite element and CFD calculations, many others.

2. Most commonly in CSR or CSC. Sometimes COO, or diagonal or banded or skyline or block and/or distributed versions of these. Ref http://netlib.org/linalg/html_templates/node90.html, scipy.sparse has a pretty good selection of these implemented, as do frameworks like PETSc and Trilinos.

3. Virtually anything you would do on a dense array, but taking into account the more subtle performance implications. Getting or setting a row,column index is potentially much more expensive for a sparse matrix than a dense one, especially if a set operation results in changing the nonzero structure by either inserting an element that was previously an implicit zero, or removing an element that was previously a stored nonzero. Linear algebra operations like (sparse or dense) matrix times (sparse or dense) (vector or matrix), transpose, factorizations like Cholesky, LU, Bunch-Kaufman, QR. Rowwise or columnwise or elementwise reductions and aggregations, data structure traversal and modification, assembly and conversions between different formats.

4. Irregular, messy, and hard. Generally they involve (hyper)graph partitioning schemes like nested dissection, approximate minimum degree, various reordering and permutation and dense sub-block aggregation methods. Do a literature search on multifrontal methods, supernode aggregation, and communication-avoiding algorithms. Some established implementations for this are METIS, Scotch, and subroutines included in larger libraries like SuiteSparse, MUMPS, Pardiso, WSMP, and Harwell HSL.

**Comment by mrocklin** [comment]
Parallel sparse matrices are hard to do generally.  There are too many approaches to fully encompass within a single project.  I think it's probably wiser to use dask.delayed and roll custom things for the time being.  Closing for now.

**Comment by mrcabbage972** [comment]
An important use case of sparse matrices in machine learning is [one-hot encoding](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html). This is the standard way of using categorical variables in ML models and it produces matrices that can be very sparse. Implementations of one-hot encoding that outputs sparse matrices exist in Pandas and Spark ML/MLLib. I would be glad to see this feature supported in Dask as well - then the ML crowd could use Dask for problems that are too large to fit in memory but are not large enough to justify the overhead of managing a Spark cluster.

**Comment by sinhrks** [comment]
pandas and scipy sparse have different internal repr. I _think_ implementing pandas sparse to dask is straightforward. Though pandas sparse is not enough matured.

**Comment by mrocklin** [comment]
Sparse matrices are certainly valuable.  There are also about ten ways to do them.  I definitely don't have time to do these and I'm not certain that they should be maintained with the core library.  It would be great to see external contributors take on this valuable idea.

**Comment by fabboe** [comment]
Agree with @mrcabbage972. Using dask with sklearn estimators that accept sparse matrices (i.e. many) would remove one of the last reasons to move to Spark for ML training.
