### ISSUE TITLE
Testing Dask scalability

### ISSUE THREAD

**Issue by gmocornejos** [dask/dask#1754]
Hi! 

I'm testing dask scalabitly, in order to do so, I wrote a simple matrix multiplication program. It takes two parameters: matrix size and  number of workers. 

    import dask.array as da
    import dask
    from multiprocessing.pool import ThreadPool
    import time 
    import sys
    import math
    
    def main():
        try :
           size  = int(sys.argv[1])
           cores = int(sys.argv[2])
        except IndexError:
            print("Usage: python3 matmul_dask.py size cores")
            raise SystemExit 
    
        dask.set_options(get=dask.threaded.get)
        dask.set_options(pool=ThreadPool(cores))
    
        chunk_size = int(math.sqrt(size * size / cores))
        mat1 = da.random.random((size,size), chunks=chunk_size)
        mat2 = da.random.random((size,size), chunks=chunk_size)
    
        start_time = time.time()
        mat3 = mat1.dot(mat2)
        mat3.compute()
        end_time = time.time()
        print("Elapse time with " + str(cores) + " cores: %.3f seconds" % (end_time - start_time))
    
    if __name__ == '__main__':
        main()

I tested the program with python 3.5.2, over an Intex Xeon Phi KNL (100 GB, 66 cores) using Threaded and Multiprocessing scheduler, and time required to execute grows with number of workers, as the following chart shows: 

![matix_multiplication_scalability](https://cloud.githubusercontent.com/assets/4778547/19976162/4186f64e-a1b4-11e6-841f-9042690d7159.jpg)

Other two tests (stencil and N-body problem) shows the same pattern. I really appreciate if you can help me to understand this behavior. 

Thanks,

Guillermo.

**Comment by mrocklin** [comment]
Some things to watch out for:

1.  Is your BLAS also multi-threaded?  You'll get contention if so.  See https://goparallel.sourceforge.net/using-dask-library-intel-python/
2.  Multiprocessing will have a lot of data movement, and so probably isn't ideal.  Threads should perform better

There are some notes from a similar benchmark here: http://matthewrocklin.com/blog/work/2015/01/14/Towards-OOC-MatMul

Generally speaking dask.array isn't an optimized BLAS implementation.  If you goal is matmul then you'll probably be better off with OpenBLAS or MKL.

Stencil and N-Body would depend very heavily on how you write down those algorithms.  Naive use of dask.array is unlikely to yield very good results.  Linking to your related stackoverflow question here: http://stackoverflow.com/questions/40249717/efficient-n-body-simulation-with-dask/40250354#40250354
