### ISSUE TITLE
ElemWise DataFrame operations by Series

### ISSUE THREAD

**Issue by simonkamronn** [dask/dask#1759]
It is not possible to perform trivial operations like standardization of data e.g. 
```
ddf = (ddf - ddf.mean(axis=0))  /  ddf.std(axis=0)
```
It throws an error saying
```
ValueError: Not all divisions are known, can't align partitions. 
Please use `set_index` or `set_partition` to set the index.
```
The output of the reduction operations are `Series` with one row and same number of columns so it shouldn't need to know the divisions. However, would it make sense to set the divisions of the `Series` to be the start and end divisions of the `DataFrame` that was reduced?

**Comment by GrierPhillips** [comment]
+1

**Comment by mrocklin** [comment]
Interesting case, I suspect that you're right that it's seeing DataFrame + Series and assuming that the intended operation is row-wise.  A good check here would be that the number of partitions of the series is one.  I'm in favor of this change.  Does anyone have the time to try to implement it?

**Comment by GrierPhillips** [comment]
Here is a minimal example I constructed from the same example in the documentation for [map_partitions](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions). What is interesting that this works with a dask dataframe constructed using `from_pandas`, but fails when constructed with `from_csv`.

```python
import pandas as pd
import dask.dataframe as dd
from dask.multiprocessing import get

df = pd.DataFrame({'x': [1, 2, 3, 4, 5],
                   'y': [1., 2., 3., 4., 5.]})
ddf = dd.from_pandas(df, npartitions=2)
def myadd(df, a, b=1):
    return df.x + df.y + a + b
ddf['res'] = ddf.map_partitions(myadd, 1, b=1).compute(get=get)
# Success!
df.to_csv('test.csv', index=False)
ddf2 = dd.read_csv('test.csv')
ddf2['res'] = ddf2.map_partitions(myadd, 1, b=1).compute(get=get)
# Fail
```
The above code returns 

> ValueError: Not all divisions are known, can't align partitions. Please use `set_index` or `set_partition` to set the index.

**Comment by GrierPhillips** [comment]
This still isn't fixed for the minimal example I included. Am I understanding the expected behavior incorrectly? I would assume that whether `dask.dataframe` is created using `from_pandas` or `read_csv` they both should behave the same, but that is clearly not the case.

**Comment by mrocklin** [comment]
You probably don't want to call compute here

    ddf2['res'] = ddf2.map_partitions(myadd, 1, b=1).compute(get=get)

Instead just leave things as a dask dataframe/series

    ddf2['res'] = ddf2.map_partitions(myadd, 1, b=1)

**Comment by mrocklin** [comment]
The error here is saying that "OK, you've given me a dask.dataframe with two partitions without any information about how those partitions are aligned.  For example I don't know how many rows are in each partition.  You've also given me a pandas series with 10 rows (or whatever).  I have no idea how to split the pandas series to align with the partitions of the dask dataframe."

**Comment by GrierPhillips** [comment]
Oh. Interesting. So the values still end up being computed even without calling `compute`. Is this a lazy execution for example if I tried:
```python
ddf2['res'] = ddf2.map_partitions(myadd, 1, b=1)
ddf2.head()
```
I would see the 'res' column included. Is the computation executed when `head` is called? If this is the case is it generally a best practice then to avoid calling `compute` if possible?

**Comment by mrocklin** [comment]
Yes, dask.dataframe computations build on each other.  You want to avoid calling compute for as long as possible.

**Comment by goyal-neeraj** [comment]
pandas version 0.22
dask version 0.17

The map_partitions is not recognized, am I doing something wrong?
```python
import pandas as pd
import dask.dataframe as dd
df = dd.read_csv('../201712/file*.GZ', compression='gzip', sep='|',  dtype = {'COL1': 'float64', 'COL2' : 'float64', 'COL3': 'str'}, blocksize=None)
df.repartition(npartitions=df.npartitions*10)
df['COL3'] = df.map_partitions(lambda x: str(x['COL3']).zfill(11))
```
OR 
```python
def func(df, col, z):
     return str(df[col]).zfill(z)
df['COL3'] = df.map_partitions(func('COL3', 11))
# Fail
# File "/usr/local/lib/python3.5/site-packages/pandas/core/generic.py", line 3614, in __getattr__
#    return object.__getattribute__(self, name)
# AttributeError: 'DataFrame' object has no attribute 'map_partitions'
```

**Comment by mrocklin** [comment]
I recommend raising a new issue with a minimal reproducible example.  

https://stackoverflow.com/help/mcve
