### ISSUE TITLE
dask.array.store needs to be able to accept a list of Lock objects

### ISSUE THREAD

**Issue by shoyer** [dask/dask#1762]
Otherwise, it's impossible for xarray to exercise fine-grained control of locking for writes (e.g., to use one lock per netcdf file consisting of multiple arrays).

xref https://github.com/pydata/xarray/pull/1087

**Comment by mrocklin** [comment]
Still an issue @shoyer ?

**Comment by shoyer** [comment]
We worked around this in xarray -- we manage our own locks inside `__setitem__` on custom arrays objects.

This is probably the more maintainable way to handle to handle complex locking, so I'm not sure this really makes sense in dask. (But the single `lock` argument is a good shortcut for the easy cases.)

**Comment by jakirkham** [comment]
This seems like a reasonable request. Though it also seems there is no more need for it. Happy to leave open or close as others see fit.

**Comment by shoyer** [comment]
I think we can close this -- this logic is better handled in a more modular way inside custom array objects.

**Comment by jakirkham** [comment]
Sounds good. Thanks @shoyer for the follow-up.
