### ISSUE TITLE
ImportError: cannot import name _deps

### ISSUE THREAD

**Issue by TMsangohan** [dask/dask#1767]
Using Python 2.7 (anaconda)

from distributed import Scheduler returns

----> 1 from distributed import Scheduler

/afs/cern.ch/user/t/tomerten/anaconda2/lib/python2.7/site-packages/distributed/__init__.py in <module>()
      3 from .config import config
      4 from .core import connect, read, write, rpc
----> 5 from .deploy import LocalCluster
      6 from .diagnostics import progress
      7 from .client import (Client, Executor, CompatibleExecutor, wait, as_completed,

/afs/cern.ch/user/t/tomerten/anaconda2/lib/python2.7/site-packages/distributed/deploy/__init__.py in <module>()
      1 from ..utils import ignoring
      2 
----> 3 from .local import LocalCluster
      4 from .adaptive import Adaptive
      5 with ignoring(ImportError):

/afs/cern.ch/user/t/tomerten/anaconda2/lib/python2.7/site-packages/distributed/deploy/local.py in <module>()
     11 from ..http.scheduler import HTTPScheduler
     12 from ..utils import sync, ignoring, All
---> 13 from ..client import Client
     14 from ..nanny import Nanny
     15 from ..scheduler import Scheduler

/afs/cern.ch/user/t/tomerten/anaconda2/lib/python2.7/site-packages/distributed/client.py in <module>()
     20 import dask
     21 from dask.base import tokenize, normalize_token, Base
---> 22 from dask.core import flatten, _deps
     23 from dask.compatibility import apply
     24 from dask.context import _globals

ImportError: cannot import name _deps

**Comment by mrocklin** [comment]
Update both dask and distributed from PyPI or conda-forge

    conda install -c conda-forge dask distributed

or

    pip install dask distributed --upgrade

**Comment by TMsangohan** [comment]
That worked, thanks.
