### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#1780]
dask creates more processes than necessary during initialization in
https://github.com/dask/dask/blob/master/dask/threaded.py#L22 .

```
default_pool = ThreadPool()
```

On a system with 64 os cores, if we start 64 processes that imports dask, a total of 64*64=4096 process will be created during start up. 

Note that we only intend to use dask in single process mode to optimize IO requests and (hopefully) the preprocessing computation network ; our application (hybrid with MPI) takes care of the data parallelism on top of many 64-core computing nodes.

This has been causing us (@nickhand) a load of trouble running our tools on Cray XC30 and XC40 systems at NERSC. The systems have a ulimit -u of 2048. We are asking the admin to raise this limit, but in the meanwhile from the dask side, starting so many processes without explicit user request seems to be a strange behavior. 

We do not see a clear way to work around this though. There is no way to override the mulptiprocessing default, which defers to the os module. Note that the solution OpenMP has is via environment variable `OMP_NUM_THREADS`. I would suggest dask add compatibility to this behaviour, as a workaround. Or if people hated OMP, `DASK_NUM_THREADS` will work equally well. 

Alternatively, `import dask` shall not create a default pool. The default pool can be created on demand. Then we add the ability to modify a parameter that sets the number of threads of the default pool.

The environment variable approach is more deterministic than the after import configuration approach.

Here is an error message we see (FYI):

```
Traceback (most recent call last):
  File "/dev/shm/local/bin/nbkit.py", line 8, in <module>
    from nbodykit import plugin_manager
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/__init__.py", line 15, in <module>
    plugin_manager = PluginManager.create(core_paths, qualprefix='nbodykit')
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/plugins/manager.py", line 50, in create
    PluginManager._instance = cls(paths, qualprefix=qualprefix)
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/plugins/manager.py", line 81, in __init__
    self._load(p, qualprefix=qualprefix)
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/plugins/manager.py", line 168, in _load
    mod = self._load(fullfn, qualname)
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/plugins/manager.py", line 189, in _load
    exec(code, module.__dict__)
  File "/dev/shm/local/lib/python3.5/site-packages/nbodykit/io/csv.py", line 3, in <module>
    import dask.dataframe as dd
  File "/dev/shm/local/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/dev/shm/local/lib/python3.5/site-packages/dask/delayed.py", line 14, in <module>
    from . import threaded
  File "/dev/shm/local/lib/python3.5/site-packages/dask/threaded.py", line 15, in <module>
    default_pool = ThreadPool()
  File "/dev/shm/local/lib/python3.5/multiprocessing/pool.py", line 749, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/dev/shm/local/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/dev/shm/local/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/dev/shm/local/lib/python3.5/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/dev/shm/local/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Rank 945 [Fri Oct 28 14:56:58 2016] [c0-1c1s2n3] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 945
```

**Comment by mrocklin** [comment]
I agree that this should be fixed.  Your use case of a 64 core machine wanting to use dask in single-threaded mode is a great example.

I suggest two changes:

1.  As you suggest we don't create the threadpool by default but instead on demand.  This is done here: https://github.com/dask/dask/pull/1781
2.  As you suggest, use some sort of environment variable.  I'm somewhat against using OMP_NUM_THREADS because I use that to control OpenMP libraries to use a single thread while I use them with Dask.  A DASK_FOO environment variable makes sense.

**Comment by rainwoodman** [comment]
Thanks. I see 1781. `DASK_NUM_THREADS` or `DASK_NUM_PROCESSES`?

I do feel the use of Thread and Process in dask is a bit blurry and using threads or processes in the name of the env adds more confusion to it.

What about `DASK_DEFAULT_POOL_SIZE` or `DASK_NUM_WORKERS`?

**Comment by mrocklin** [comment]
Can you explain your concern about the use of thread and process in dask being blurry?

**Comment by rainwoodman** [comment]
Sorry, I read the code sufficiently superficially.

I saw multiprocessing and ThreadPool together and got confused. Now that I look at that again after goolging ThreadPool, it is clear dask (at least for the default pool) uses only threads, no processes.

It could help if you add a comment near ThreadPool import to clarify although, it is imported from multiprocessing, ThreadPool uses threads, not processes. 

I don't know if dask can ever run on processes. If so an env name doesn't have 'thread' or 'process' could be more suitable -- so that's my suggestion.
