### ISSUE TITLE
reset_index resets the index to the default per partition

### ISSUE THREAD

**Issue by birbbit** [dask/dask#1784]
Reading the documentation, I was under the impression that `reset_index` will reset the index of the dataframe, but the following example shows that's not the case. I believe that the index gets reset per partition.

```python
import dask.dataframe as dd
import pandas as pd

pdf = pd.DataFrame({'name': ['a', 'a', 'a', 'b', 'b', 'b', 'c'], 'value': [1, 3, 2, 6, 8, 7, 9]})
ddf = dd.from_pandas(pdf, npartitions=3)

ddf[ddf['value'] <= 7].reset_index(drop=True).index.compute()
```

Outputs:
``` Int64Index([0, 1, 2, 0, 1], dtype='int64')```

Also, why is the number of partitions 2 in the above example? 
```
In [2]: ddf
Out[2]: dd.DataFrame<from_pa..., npartitions=2, divisions=(0, 3, 6)>
```

**Comment by mrocklin** [comment]
That's correct.  We don't know how many rows are in the dask.dataframe without reading through all of your data, so it is difficult to construct an accurate range index.

The logic in `from_pandas(npartitions=...)` doesn't guarantee an exact number of partitions.  However in your case I don't see why it shouldn't perform as expected.  If you felt like looking into the source code here and submitting a PR that would be most welcome.  The logic in `dask/dataframe/io/io.py::from_pandas` should be accessible.

**Comment by birbbit** [comment]
Thank you for the fast reply! That makes sense.

As for the number of partitions, it looks like the number of partitions is one less in cases when the divisions would include the same value twice. Adding it again works, but it looks weird. 
`dd.DataFrame<from_pa..., npartitions=3, divisions=(0, 3, 6, 6)>`
Going by the documentation:

> Divisions includes the minimum value of every partition’s index and the maximum value of the last partition’s index.

it looks like that would would be expected. However, if there is no guarantee on the exact number of partitions, it might be better to just leave it as is since it's less confusing.

**Comment by jcrist** [comment]
I added some clarifications to the docstrings here: https://github.com/dask/dask/pull/1830. Please let me know if these aren't clear enough, or you have suggestions for improvement.

The `npartitions` bit is tricky to do in a general case, as we care more about the divisions than we do about the number of output partitions matching exactly. As such, I just made a note in the docstring and left things the way they are.

**Comment by birbbit** [comment]
Looks clear to me. Thanks!
