### ISSUE TITLE
Question: drain a node

### ISSUE THREAD

**Issue by ptulpen** [dask/dask#1793]
Hello,
I have a question about the scheduling where I could not find an answer yet:
Is it possible to drain in dask nodes like in other Cluster systems?
Like: I want to remove this node, so start no new jobs but finish the old one
(I am aware that the jobs would be rescheduled if I just remove the node, I a planned way would also be nice, ecspecially for long running jobs)

Best regards,
Peter

**Comment by mrocklin** [comment]
There is internal code to do this, but nothing user facing. Relevant code
is retire_workers in
https://github.com/dask/distributed/blob/master/distributed/scheduler.py

**Comment by ptulpen** [comment]
Hello,
thanks a lot, we should be able to use this.

Is there any particular reason, that this is not user facing? I think it would be useful for others as well

**Comment by mrocklin** [comment]
Much of this is still in flux as we learn more about how Dask gets deployed on various kinds of clusters.  Also, with the approach I've personally taken so far this is often handled on the scheduler side, where this is as public as it gets.

You might also enjoy http://matthewrocklin.com/blog/work/2016/09/22/cluster-deployments

**Comment by mrocklin** [comment]
Closing for now.
