### ISSUE TITLE
ProgressBar using FloatProgress in Notebooks

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#1797]
One thing that would be really neat would be to use the `FloatProgress` widget from `ipywidgets` as the `ProgressBar` particularly when running in Jupyter Notebooks. If there is interest in such a contribution, I'd be willing to give it a try.

**Comment by mrocklin** [comment]
Sure.  You might want to look at the dask/distributed progress and
multi-progress bars in distributed/diagnostics/progressbar.py

**Comment by jakirkham** [comment]
So it looks like there is something like this in `distributed` called [`ProgressWidget`]( https://github.com/dask/distributed/blob/e534e26e50cd8956942d5821193cac633a15af51/distributed/diagnostics/progressbar.py#L114 ). However, it is unclear to me how I use it. I see that it takes `keys` from the graph, but I don't know the names of the keys I want. All I know is that they should come from the last computation. How do I query the `Array` object to get the right keys?

**Comment by mrocklin** [comment]
it's not for use with the single machine scheduler.  Use the `distributed.progress` function if you are using the distributed scheduler.  For more information see http://distributed.readthedocs.io/en/latest/plugins.html and the source code.
