### ISSUE TITLE
evaluating impure delayed object always delivers the same result

### ISSUE THREAD

**Issue by abast** [dask/dask#1802]
According to the [API](http://dask.pydata.org/en/latest/delayed-api.html?highlight=pure), I would expect that evaluating the same impure delayed object twice would result in two distinct computations of the result. I would therefore expect, that the following code picks different random numbers:

```
d = dask.delayed(lambda: random.randint(0,100), pure = False)()
dl = 10*[d]
dask.compute(*dl, get = dask.threaded.get)
dask.compute(*dl, get = dask.async.get_sync) #to see if same seeds might be the problem
```

However, this always gives 10 times the same result. Maybe I just don't get how to use `delayed` and the result is already computed in the first line?

**Comment by mrocklin** [comment]
You're only calling the function once.  The following are similar

```python
x = random.randint(0, 100)
l = 10 * [x]

d = delayed(random.randint, pure=False)(0, 100)
dl = 10 * [d]
```

`d` is a single value.  If you reuse that value it will remain consistent.  

I think that you want the following:

```python
f = delayed(random.randint, pure=False)
dl = [f(0, 100) for i in range(10)]
```

**Comment by abast** [comment]
You are right. Thanks. I close the issue.
