### ISSUE TITLE
Issues using `dask.merge()` on pandas dataframes, KeyError: 'column1'

### ISSUE THREAD

**Issue by evanbiederstedt** [dask/dask#1804]
So I have two pandas dataframes created via 

    df1 = pd.read_cvs("first1.csv")
    df2 = pd.read_csv("second2.csv")

These both have the column `column1`. To double check, 

    print(df1.columns)
    print(df2.columns)

both return a column `'column1'`. 

So, I would like to merge these two dataframes with dask, using 60 threads locally (using an outer merge):

    dd1 = dd.merge(df1, df2, on="column1", how="outer", suffixes=("","_repeat")).compute(num_workers=60)

That fails with a KeyError, `KeyError: 'column1'`

    Traceback (most recent call last):
      File "INSTALLATIONPATH/python3.5/site-packages/pandas/indexes/base.py", line 2134, in get_loc
        return self._engine.get_loc(key)
      File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
      File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
      File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
      File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
    KeyError: 'column1'

I would think this is a parallelizable task, i.e. `dd.merge(df1, df2, on='id')`

http://dask.pydata.org/en/latest/dataframe-overview.html

Why doesn't this work? Is there a "dask-equivalent" operation for this? I also tried reindexing the pandas dataframes on `chr` (i.e. `df1 = df1.reset_index('chr')` ) and then tried joining on the index

     dd.merge(df1, df2, left_index=True, right_index=True)

That didn't work either, same error. 

Am I doing something wrong?

**Comment by mrocklin** [comment]
Hi @evanbiederstedt it will be easier to provide an answer if you can provide a simple reproducible example that fails.  Ideally this would start with a tiny pandas dataframe

```python
df1 = pd.DataFrame(...)
ddf1 = dd.from_pandas(df1, npartitions=2)

...

dd.merge(...)
```

**Comment by evanbiederstedt** [comment]
@mrocklin Of course, you're right:

    print(df1.shape) # outputs (4757076, 4)
    df1.head 

        column1  begin    end    category
    0  class1  10001  10468    third
    1  class1  10469  11447     third
    2  class1  11505  11675     fourth
    3  class2  15265  15355   seventh
    4  class2  15798  15849   second

And the second dataframe

    print(df2.shape) # (428764, 45)
       column1  begin    .... 
    0  class1  10524   .... 
    1  class1  10541   ....
    2  class1  10549  ....
    3  class1  10565  ...
    4  class1  10596  ...

My previous mistake was to this that dask merged pandas dataframes. Following your template:

    ddf1 = dd.from_pandas(df1, npartitions=2)
    ddf2 = dd.from_pandas(df2, npartitions=2)

and then 

    merged = dd.merge(ddf1, ddf2, on="column1", how="outer", suffixes=("","_repeat")).compute(num_workers=60)

leads to a memory error: `dask.async.MemoryError`

The full error is pasted below. I'm working with 2TB RAM. Could this operation really be that intensive? Are there any optimization steps to try?

Here is the error:

```
Traceback (most recent call last):
  File "repeat_finder.py", line 15, in <module>
    merged = dd.merge(ddf1, ddf2,on="column1", how="outer", suffixes=("","_repeat")).compute(num_workers=60)
  File "/path/python3.5/site-packages/dask/base.py", line 78, in compute
    return compute(self, **kwargs)[0]
  File "/path/python3.5/site-packages/dask/base.py", line 178, in compute
    results = get(dsk, keys, **kwargs)
  File "/path/python3.5/site-packages/dask/threaded.py", line 69, in get
    **kwargs)
  File "/path/python3.5/site-packages/dask/async.py", line 502, in get_async
    raise(remote_exception(res, tb))
dask.async.MemoryError: 

Traceback
---------
  File "/path/python3.5/site-packages/dask/async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File "/path/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/path/python3.5/site-packages/dask/dataframe/methods.py", line 221, in merge
    suffixes=suffixes, indicator=indicator)
  File "/path/python3.5/site-packages/pandas/tools/merge.py", line 59, in merge
    return op.get_result()
  File "/path/python3.5/site-packages/pandas/tools/merge.py", line 503, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/path/python3.5/site-packages/pandas/tools/merge.py", line 667, in _get_join_info
    right_indexer) = self._get_join_indexers()
  File "/path/python3.5/site-packages/pandas/tools/merge.py", line 647, in _get_join_indexers
    how=self.how)
  File "/path/python3.5/site-packages/pandas/tools/merge.py", line 876, in _get_join_indexers
    return join_func(lkey, rkey, count, **kwargs)
  File "pandas/src/join.pyx", line 226, in pandas._join.full_outer_join (pandas/src/join.c:11286)
  File "pandas/src/join.pyx", line 231, in pandas._join._get_result_indexer (pandas/src/join.c:11474)
  File "/gpfs/commons/groups/imielinski_lab/lib/pythonVE-3.5.2/lib/python3.5/site-packages/pandas/core/algorithms.py", line 1072, in take_nd
    out = np.empty(out_shape, dtype=dtype, order='F')
```

**Comment by evanbiederstedt** [comment]
@mrocklin Considering that this is arguably a new issue (i.e. different than the title), I'm happy to close the current issue and open a new open. Apologies for the confusion. 

It appears the KeyError is thrown because I was using pandas DataFrames and merging with `dd.merge(df1, df2, on="index")` (This is correct? It's not possible to merge pandas dataframes on an index as above with `dask.dataframe.merge()`?)

When I convert these pandas dataframes to dask dataframes with `ddf1 = dd.from_pandas(df1, npartitions=2)`, then there's a memory issue.

**Comment by jcrist** [comment]
Closing, as related to #1814. Feel free to reopen if needed.

**Comment by brainrichtech** [comment]
Hi
i got this error please any one solve this

reviews_users_df = pd.merge(reviews_df, users_df, on='user_id') # merging 2 dataset on user_id
users_df = []
reviews_df = []

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2392             try:
-> 2393                 return self._engine.get_loc(key)
   2394             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5239)()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5085)()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20405)()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20359)()

KeyError: 'user_id'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-35-dbb894882137> in <module>()
      1 
----> 2 reviews_users_df = pd.merge(reviews_df, users_df, on='user_id') # merging 2 dataset on user_id
      3 
      4 users_df = []
      5 

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\reshape\merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator)
     51                          right_on=right_on, left_index=left_index,
     52                          right_index=right_index, sort=sort, suffixes=suffixes,
---> 53                          copy=copy, indicator=indicator)
     54     return op.get_result()
     55 

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\reshape\merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator)
    556         (self.left_join_keys,
    557          self.right_join_keys,
--> 558          self.join_names) = self._get_merge_keys()
    559 
    560         # validate the merge keys dtypes. We may need to coerce

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\reshape\merge.py in _get_merge_keys(self)
    808                     if not is_rkey(rk):
    809                         if rk is not None:
--> 810                             right_keys.append(right[rk]._values)
    811                         else:
    812                             # work-around for merge_asof(right_index=True)

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2060             return self._getitem_multilevel(key)
   2061         else:
-> 2062             return self._getitem_column(key)
   2063 
   2064     def _getitem_column(self, key):

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2067         # get column
   2068         if self.columns.is_unique:
-> 2069             return self._get_item_cache(key)
   2070 
   2071         # duplicate columns & possible reduce dimensionality

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   1532         res = cache.get(item)
   1533         if res is None:
-> 1534             values = self._data.get(item)
   1535             res = self._box_item_values(item, values)
   1536             cache[item] = res

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   3588 
   3589             if not isnull(item):
-> 3590                 loc = self.items.get_loc(item)
   3591             else:
   3592                 indexer = np.arange(len(self.items))[isnull(self.items)]

C:\Users\brain\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2393                 return self._engine.get_loc(key)
   2394             except KeyError:
-> 2395                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2396 
   2397         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5239)()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5085)()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20405)()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20359)()

KeyError: 'user_id'

**Comment by mrocklin** [comment]
Hi @brainrichtech I recommend producing a minimal example and using it to open a new issue. 

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
