### ISSUE TITLE
ImportError: cannot import name local

### ISSUE THREAD

**Issue by MortezaMoghadd** [dask/dask#1805]
I installed dask via: **`conda install dask -c conda-forge`** 
**python version: 2.7.12 :: Anaconda 4.0.0 (64-bit)**
I could import dask and **dask version is 0.12.0**
I am getting this issue:

`import dask.dataframe as dd`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-e012ff17e82a> in <module>()
----> 1 import dask.dataframe as dd

C:\Users\i709837\AppData\Local\Continuum\Anaconda2\lib\site-packages\dask\dataframe\__init__.py in <module>()
      3 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      4                    repartition)
----> 5 from .io import (from_array, from_pandas, from_bcolz,
      6                  from_dask_array, from_castra, read_hdf,
      7                  from_delayed, read_csv, to_csv, read_table,

C:\Users\i709837\AppData\Local\Continuum\Anaconda2\lib\site-packages\dask\dataframe\io\__init__.py in <module>()
      4                  from_pandas, from_dask_array, from_castra, to_castra,
      5                  from_delayed, dataframe_from_ctable, to_bag)
----> 6 from .csv import read_csv, to_csv, read_table
      7 from .hdf import read_hdf, to_hdf
      8 from . import demo

C:\Users\i709837\AppData\Local\Continuum\Anaconda2\lib\site-packages\dask\dataframe\io\csv.py in <module>()
     17 from .io import from_delayed
     18 
---> 19 from ...bytes import read_bytes
     20 from ...bytes.core import write_bytes
     21 from ...bytes.compression import seekable_files, files as cfiles

C:\Users\i709837\AppData\Local\Continuum\Anaconda2\lib\site-packages\dask\bytes\__init__.py in <module>()
      4 from .core import read_bytes, open_files, open_text_files
      5 
----> 6 from . import local
      7 
      8 with ignoring(ImportError, SyntaxError):

**ImportError: cannot import name local**

I also tried:
`from dask.compatibility import local`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-38dfb90b1d71> in <module>()
----> 1 from dask.compatibility import local

ImportError: cannot import name local

**Comment by jcrist** [comment]
That's odd. The import that's failing is `dask/bytes/local.py` failing from `dask/bytes/__init__.py`. Since this is python 2, my first thought was that we were missing a `from __future__ import absolute_import`, but that's not the case.

I'm unable to recreate the issue by doing a clean install. The following works fine for me:

```bash
$ conda create -y -n test-bed python=2.7
$ source activate test-bed
$ conda install -y -c conda-forge dask
$ python -c "import dask.dataframe"
```

Can you try reinstalling? It may have been an issue with your install.

**Comment by MortezaMoghadd** [comment]
Tried reinstalling and also, did the same steps as yours. Neither is working and I got the same error. :(

**Comment by jcrist** [comment]
Hmmm, I'm sorry, I'm not sure what else to try here. If you can create a reproducible example (a list of commands that I can run, similar to what I did above, that will reproduce your issue) then we might be able to help more. It really sounds like this is an issue with your python install, and not an issue with dask.

**Comment by jcrist** [comment]
Closing for now due to lack of activity. Feel free to reopen if you can provide a reproducible example.
