### ISSUE TITLE
get_dummies not executing

### ISSUE THREAD

**Issue by nsharkey** [dask/dask#1809]
Dask `get_dummies` "runs" but it doesn't actually execute the get_dummies task. 

```
import pandas as pd
import dask.dataframe as dd

pandasData = pd.DataFrame({'var1': ['a', 'b', 'a'], 'var2': ['b', 'a', 'c'], 'var3': ['c', 'a', 'b']})
pd.get_dummies(pandasData)

daskData = dd.from_pandas(pandasData, npartitions=1)
daskData.head()

daskDataDummies = dd.get_dummies(daskData).compute()
daskDataDummies.head()

daskDataDummies.to_csv('daskDataDummies_out.csv', header=True, index=False)
```

There's no error message it simply doesn't transform the dataframe.

**Comment by mrocklin** [comment]
Looking at the docstring it looks like these need to be categorical:

```
Convert categorical variable into dummy/indicator variables. Data must
have category dtype to infer result's ``columns``
```

Arguably we should err here, but I suspect that this is your problem.

**Comment by nsharkey** [comment]
Understood, but if this is trying to be 100% analogous to Pandas' get_dummies shouldn't this be baked into the functionality?

**Comment by mrocklin** [comment]
I'm not sure that what you're proposing is possible without a full scan.
If you'd like to do some experimentation and submit a PR though that would
be great.

**Comment by nsharkey** [comment]
I don't have the technical capabilities to do that. If it isn't something you or the community can do then close out the request.

**Comment by mrocklin** [comment]
Adding to that parametrized test has been helpful so far.  Next time I take a look at this I'll probably dump in a bunch more dtypes and such.

**Comment by nsharkey** [comment]
Perhaps someone smarter than I can figure out a sampling technique to approximate the full file's dtypes.

**Comment by mrocklin** [comment]
Sampling probably isn't sufficient.  We need to know *all* of the values throughout the file to determine the columns.
