### ISSUE TITLE
Overcoming `dask.async.MemoryError` with merge

### ISSUE THREAD

**Issue by evanbiederstedt** [dask/dask#1814]
I begin with two dataframes, working with Python 3.5 on a system with 2 TB RAM and approx. 300 threads:

df1 = pd.read_cvs("first1.csv")
df2 = pd.read_csv("second2.csv")

The size of `first1.csv` is 139 MB, and the size of `second2.csv` is 118 MB. As for the contents of these dataframes:

```
print(df1.shape) # outputs (4757076, 4)
df1.head 

    column1  begin    end    category
0  class1  10001  10468    third
1  class1  10469  11447     third
2  class1  11505  11675     fourth
3  class2  15265  15355   seventh
4  class2  15798  15849   second
```

and 

```
print(df2.shape) # (428764, 45)
   column1  begin    end     category
0  class1  11524   11556    fourteenth
1  class1  11541   ....
2  class1  11549  ....
3  class1  11565  ...
4  class1  11596  ...
```

I try to run the following code

```
import pandas as pd
import os
import dask.dataframe as dd
from numpy import nan

ddf1 = dd.from_pandas(repeats, npartitions=1000)  # I was hoping more parititions would make this managable
ddf2 = dd.from_pandas(anno, npartitions=1000)

merged = dd.merge(ddf1, ddf2, on="column1", how="outer", suffixes=("","_repeat"))
merged.to_csv("out.*.test1.csv") 
 # without a globstring with an asterisk `*`, I get this error: `dask.async.FileNotFoundError: [Errno 2] No such file or directory: 'out.test1.csv/865.part'`
```

This last line fails:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/lib/python3.5/site-packages/dask/dataframe/core.py", line 985, in to_csv
    return to_csv(self, filename, **kwargs)
  File "/path/lib/python3.5/site-packages/dask/dataframe/io/csv.py", line 305, in to_csv
    compute(*values, get=get)
  File "/path/lib/python3.5/site-packages/dask/base.py", line 178, in compute
    results = get(dsk, keys, **kwargs)
  File "/path/lib/python3.5/site-packages/dask/threaded.py", line 69, in get
    **kwargs)
  File "/path/lib/python3.5/site-packages/dask/async.py", line 502, in get_async
    raise(remote_exception(res, tb))
dask.async.MemoryError: 

Traceback
---------
  File "/path/lib/python3.5/site-packages/dask/async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File "/path/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/path/python3.5/site-packages/dask/dataframe/methods.py", line 221, in merge
    suffixes=suffixes, indicator=indicator)
  File "/path/lib/python3.5/site-packages/pandas/tools/merge.py", line 59, in merge
    return op.get_result()
  File "/path/lib/python3.5/site-packages/pandas/tools/merge.py", line 517, in get_result
    concat_axis=0, copy=self.copy)
  File "/path/lib/python3.5/site-packages/pandas/core/internals.py", line 4818, in concatenate_block_managers
    placement=placement) for placement, join_units in concat_plan]
  File "/path/lib/python3.5/site-packages/pandas/core/internals.py", line 4818, in <listcomp>
    placement=placement) for placement, join_units in concat_plan]
  File "/path/lib/python3.5/site-packages/pandas/core/internals.py", line 4915, in concatenate_join_units
    for ju in join_units]
  File "/path/lib/python3.5/site-packages/pandas/core/internals.py", line 4915, in <listcomp>
    for ju in join_units]
  File "/path/lib/python3.5/site-packages/pandas/core/internals.py", line 5215, in get_reindexed_values
    fill_value=fill_value)
  File "/path/lib/python3.5/site-packages/pandas/core/algorithms.py", line 1074, in take_nd
    out = np.empty(out_shape, dtype=dtype)
```
So, how could I accomplish this with dask? Again, I'm using 2 TB of RAM. I tried doing this with more threads, but it's the same problem: 

    merged.to_csv("out.*.test1.csv").compute(num_workers=60)

I get the exact same error, `dask.async.MemoryError:`. So, how would I overcome this? My understanding as that there should be a way via dask to partition this merged dataframe such that one saves to disk without holding the entire structure in memory.

**Comment by jreback** [comment]
show what you expect as output 
you are merging duplicates with dupllicates

you will get something like 5M x 500K rows
which is a really large number

**Comment by evanbiederstedt** [comment]
Thanks for the response/help. 

"show what you expect as output
you are merging duplicates with dupllicates"

My goal is to match multiple columns for an "interval", i.e.  take the `df2` dataframe and check whether the intervals `begin:end` match any of the rows in the original dataframe `df1`. If it does, this row in `df1` should be labeled with the `df2` dataframe's value.

So, given my examples above, `merged` would look like this:

```
column1    begin     end     value        value_repeat
class1      11505  11675     fourth       fourteenth
class2      15265  15355   seventh    fourteenth
.... 
````

Because if you look at `df2`, the row

`0  class1  10524   10556    fourteenth`
with interval `10524:10556` falls in the interval `11505:11675` in `df1`.

I'm doing this with the following short script: 

```
merged = dd.merge(ddf1, ddf2, on="column1", how="outer", suffixes=("","_repeat")).compute(num_workers=60)
merged = merged[(ddf1.column1 == row.column1) & (ddf2.begin >= ddf1.begin) & (ddf2.begin <= ddf1.end)]
merged = dd.merge(ddf2, merged, on = ["column1"]).compute(num_workers=60)
merged.to_csv("test.*.output.csv", index=False)
```

Is this clear? Is there any scalable way to do this? In principle, this should be simple: find where "intervals" in one dataframe overlap with the intervals in another dataframe. (In my example, I noticed my numbers are off----each `value_repeat` with be unique.)

**Comment by jcrist** [comment]
@evanbiederstedt, I'm sorry, I'm having a hard time reproducing this issue. Is there any way you can provide a reproducible example? Ideally this would involve either sharing the input data, or finding a way to generate data that also causes failure. Something like:

```python
df = make_first_dataframe()
df2 = make_second_dataframe()
...  # The rest of your code that causes the failure
```

Ideally I should be able to run `python your_test_case.py` and get the error.

**Comment by mrocklin** [comment]
dd.demo.make_timeseries can be useful when making reproducible examples

**Comment by evanbiederstedt** [comment]
Hi @jcrist 
I agree. I've just sent you an e-mail---this should allow you to download the data and recreate the issue with scripts.

**Comment by jcrist** [comment]
Hi Evan, I sent you a more thorough response via email. For your use case, you're creating a huge intermediate table with ~2e12 rows (which is the error happens). Instead of using `merge`, I'd solve this by writing a function to do the label applying (using one of the dataframes as a lookup-table), and just using pandas to load the data and apply function. This won't result in the huge intermediate result, and should be sufficient for the size of inputs you have.

Closing for now, feel free to reopen if needed.
