### ISSUE TITLE
Rewrite docstrings

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1815]
Currently we blindly copy dask.array and dask.dataframe docstrings from NumPy and Pandas.  This allows us to avoid rewriting hundreds of docstrings.

However, this fails when the dask operation and the numpy/pandas operation differ slightly, as often occurs when we support only a subset of functionality.  This appears to be confusing users who inspect our documentation, try something out, and then receive an error when it doesn't work (see [this example](http://stackoverflow.com/questions/40845169/aggregation-fails-when-using-lambdas)).

There are some efforts to mitigate this, for example `derived_from` takes a list of unavailable arguments to add to the docstring.  However this keyword argument is virtually unused.

### Some solutions

1.  Crowd-sourced effort to rewrite docstrings manually
2.  Add disclaimer to all wrapped functions that it is merely a copy
3.  ?

**Comment by mrocklin** [comment]
I'm somewhat more inclined towards option 2 to start because it is simple and comprehensive, if perhaps a bit blunt.  We might be able to combine the two in some way, perhaps taking a small docstring from the dask.dataframe/array function and prepending it onto the pandas docstring in some clever way.

**Comment by mrocklin** [comment]
Perhaps something like this, but better:

```
""" Docstring for FUNCTION NAME

This Dask function implements most of the functionality of WRAPPED FUNCTION NAME, whose complete docstring is included below.  However, this Dask version contains the following alterations:

DOCSTRING FROM DASK FUNCTION

The original docstring follows below:

ORIGINAL DOCSTRING
"""
```

**Comment by soloz** [comment]
Hi,

I've been using dask - thanks for the work. So its time to start giving back. For start, I'm happy to work on this, #1592 and #1606 and see how I get on with. Also happy to sync with anyone already doing so. 

Should put in a pr over the coming days.

**Comment by mrocklin** [comment]
Thank you for the enthusiasm and effort Solomon.

**Comment by jaypeedevlin** [comment]
I think some sort of re-ordering of the notes + explicit disclaimer would help a lot.  There are some extreme cases, like this where all 5 of the listed parameters that are copied from the pandas docstring are not supported.

![image](https://user-images.githubusercontent.com/17235807/36216089-69b16386-1173-11e8-81d0-de3b62e27154.png)

Does anyone know if the format of the pandas docstrings are consistent enough that we might be able to strip these params out in the [`derived_from()` decorator](https://github.com/dask/dask/blob/de6c2a49d76066abb51085570816322f063fc5c5/dask/utils.py#L463)

**Comment by mariusvniekerk** [comment]
So theoretically the pandas docstrings should be adhering to numpydoc which you might be useful for parsing these.

**Comment by jakirkham** [comment]
I've added this to our core work list for triage.

**Comment by jsignell** [comment]
I was thinking of trying to implement a generic disclaimer as described in this comment https://github.com/dask/dask/issues/1815#issuecomment-263272272. Do people still think that is a good idea?

**Comment by TomAugspurger** [comment]
Talking with @jsignell, we may want to just strip out parameters that aren't supported by dask.

Rather than 

```
Parameters
----------
rule : DateOffset, Timedelta or str
    The offset string or object representing target conversion.
axis : {0 or 'index', 1 or 'columns'}, default 0  (Not supported in Dask)
    Which axis to use for up- or down-sampling. For `Series` this
    will default to 0, i.e. along the rows. Must be
    `DatetimeIndex`, `TimedeltaIndex` or `PeriodIndex`.
closed : {'right', 'left'}, default None
...
```

We'd have

```
Parameters
----------
rule : DateOffset, Timedelta or str
    The offset string or object representing target conversion.
closed : {'right', 'left'}, default None
...

Notes
------
The following paramerts are not supported by dask

* axis
* ...

```

or put that next to the dask disclaimer.

**Comment by TomAugspurger** [comment]
It would also be nice if the disclaimer included a link to the original docstring.

<img width="671" alt="Screen Shot 2020-02-27 at 5 40 19 PM" src="https://user-images.githubusercontent.com/1312546/75493588-40742800-5988-11ea-8d8c-41becb5fd015.png">

That could be :meth:\`pandas.DataFrame.resample`, rather than `pandas.core.frame.DataFrame.resample`.

It's a bit tricky because the API doc location isn't always the same as where the object is defined (pandas.core.frame vs.pandas)


The disclaimer should maybe be in an info box too.

**Comment by xmnlab** [comment]
I want to start contributing to dask and am interested in helping on this issue.

I saw that @jsignell worked on some PRs related to this issue.

is there missing anything to finish this issue? if yes I would be happy to help on that :)

**Comment by xmnlab** [comment]
thanks @jsignell for all the information! that sounds good. I will start it this weekend :)

**Comment by jsignell** [comment]
I think we can close this at this point. There haven't been any issues in a while where people complained about docstrings that were missing the disclaimer, so maybe we hit them all with the brute force approach? Anyone should feel free to reopen if they disagree.
