### ISSUE TITLE
Distributed append-only data structure

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#183]
For complex operations like groupby and joins we often need to shuffle data.  This can be tricky.  Some data from each of the old partitions may contribute to each of the new ones.  The resulting quadratic overhead (or more!) crushes performance if we don't take care.

Historically we took care with the `pbag` and `pframe` data structures for out-of-core shuffling in `dask.bag` and `dask.dataframe` respectively.  These have taken time but for the most part worked well.  As we move to distributed shuffling we need to make a new distributed data structure.  The ideal data structure is constrained by/supports the following:

1.  It supports breaking apart a block of data into new local groups and appending those groups onto their new blocks ([see example image for pframe](http://dask.readthedocs.org/en/latest/pframe.html)).  This happens many times and so needs to be fast.

        groups = groupby(func, old_block_1034)
        datastructure.append(groups)

2.  Any worker can request one of the new blocks and all of the data for that block from all of the nodes should assemble on that worker.

        datastructure.get('new-block-5329')

I suggest that when breaking-apart/writing we write to local files without communication and then only communicate when reading the finished blocks.  Other considerations:

3.  To keep the number of OS files low per compute-node (overhead here is odd when you get into the thousands of files) we may want multiple *processes* to write to the same files.  This will require something like a file-based lock.
4.  To keep the disk usage optimal, file writes should be relatively large, this may require some in-memory buffering.
5.  We may want to plug in compression prior to communication (like snappy for text or blosc and friends for binary)

We can make this easier by allowing out-of-order appends.  I don't see a use case where order matters within a block other than to ensure consistency (which can be done with locking.)

I expect writing to be hard and reading/communication to be relatively easy.  The many-small case tends to be trickier than the few-large, even with communication.

Historically I've coupled serialization into this process.  I think that we should make a general low level data structure that just appends bytes.  We can hopefully build around this for numpy arrays, dataframes, lists, etc..  

*  For binary if we use memmapped arrays then we can just append to the file
*  For pickled lists it would be nice to find a way to concatenate two pickled lists together without deserializing them.  At first glance this looks doable.

Finalized store
---------------

We may want a few features on top of append/shuffle.  This may be a second distributed data structure.

1.  We commonly want to add a new partition that we have fully formed.  This is the case when we add a new day onto a running time series.  That partition is local and does not require shuffling.
2.  We may want to pre-compute a full shuffle so that future operations can pull from only one machine.  This should be a persistent store.

**Comment by jcrist** [comment]
Since distributed is now its own project, should this issue be closed (and potentially moved to the other repo)?
