### ISSUE TITLE
Extend dask.array no-chunk solution

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1839]
Recently in https://github.com/dask/dask/pull/1838 we allowed dask.arrays to exist with unknown chunk sizes.  There is still some work to do here:

1.  Support more operations like the following:
    * reshape
    * slicing dask.arrays with other dask.arrays (an often requested feature)
    * ...
2.  Document the feature and its limitations

**Comment by moody-marlin** [comment]
It appears that `.values` with dask DataFrames doesn't work as I would expect with addition / subtraction of numpy arrays.  Example:

```
A = dd.from_array(np.array([[0,0], [1,1]]))
B = da.from_array(np.array([[0,0], [1,1]]), chunks=2)
A.columns = ['x', 'y']

B[:,0] - np.zeros(2) ## works fine, and as expected
A.y.values.compute() - np.zeros(2) ## works fine, as expected
A[['y']].values - np.zeros(2) ## works, broadcasts to create (2,2) array
A.y.values - np.zeros(2) ## throws a ValueError

ValueError: operands could not be broadcast together with shapes (nan,) (2,)
```

**Comment by mrocklin** [comment]
In the `A[['y']].values` case we know the shape to be `(nan, 2)` (we know the number of columns, but not rows) so subtracting a `(2,)` array works because of broadcasting.  In the `A.y.values` case we don't know the number of rows, so I think it's proper to err here.

In this *particular* case we do know the number of rows, and so could set chunks explicitly

```python
v = A.y.values
v._chunks = ((2,),)
```

But this is a special case and not something that we can guarantee generally.  Going from dask.arrays to dask.dataframes and back will lose information.  Dask.array reserves the right to err rather than hope that things are correct in some cases.

**Comment by mrocklin** [comment]
I've implemented slicing.  It would be nice to also implement reshape (this comes up decently often.)

**Comment by jakirkham** [comment]
Not sure if this should be a new issue or if this is an ok place to add this idea, but it would be nice to have `stack` and `concatenate` work when dimensions are unknown. Admittedly this is not easy to solve in the general case as one doesn't know the length of the unknown dimensions. So one can't verify that they are the same. However if there was some way to mark the unknown length dimensions as the belong to the same group of unknown lengths, then it might be possible to validate `stack` and `concatenate` in the general case. Though there may be even simpler solutions for specific cases.

**Comment by mrocklin** [comment]
It would not be unreasonable to just assume that they matched and err at
runtime if they don't.  We do similar things in dask.bag

**Comment by jakirkham** [comment]
Sure that could be reasonable too and probably easier to implement. If we go that way, it's probably worth raising some kind of warning when concatenating or stacking any arrays with unknown dimensions.

**Comment by mrocklin** [comment]
Historically we have handled this by raising an exception if, while
computing the graph, we notice that the chunks don't line up.  This could
be changed to something else though.

**Comment by mrocklin** [comment]
Much of this has been implemented.  It's a bit open ended.  Closing.
