### ISSUE TITLE
Check matching versions of dask and distributed

### ISSUE THREAD

**Issue by abast** [dask/dask#1845]
Apparently, conda does not ensure a version compatibility of dask and distributed in some cases, e.g. I tried to first upgrade and than downgrade dask. Conda only upgraded distributed, but did not downgrade it, resulting in a too new version of distributed at the end. ([Here I asked on stackoverflow about that](http://stackoverflow.com/questions/40845751/how-to-find-matching-versions-of-dask-and-distributed)). 

I therefore wanted to ask if it makes sense to check for matching versions at runtime?

**Comment by jreback** [comment]
https://github.com/dask/distributed/pull/705

**Comment by abast** [comment]
Thanks for implementing this sort of check. I am sorry that I was not aware that this feature is already in development.
