### ISSUE TITLE
How to set index and devisions lazily using DataFrame.read_csv?

### ISSUE THREAD

**Issue by abast** [dask/dask#1848]
The DataFrame.read_csv method currently does not accept an `index_col` argument. Instead, the error message suggests to use` dd.read_csv(...).set_index('my-index')` instead. However, this is an expensive calculation, which should not be necessary if the index is already sorted and the divisions are known.

Is there a way to explicitly set index and divisions using the read_csv method, that does not require to load in data?

**Comment by abast** [comment]
Is this full pass through the data something, that is necessary in principle, even if I know the divisions or does it simply come with the current implementation of read_csv?

**Comment by mrocklin** [comment]
If you already know the divisions of each of your partitions exactly then you should be able to assign them directly.

    df.divisions = (...)

**Comment by abast** [comment]
Perfect! However, I do not only want to set the divisions, but the index as well. Overall, I am struggling for quite a while now with the very basic task to save a dask dataframe to disk in parallel and reload it lazily:
- setting an index using read_csv is expensive (even with sorted = True)
- hdf apparently [does not support very wide dataframes](https://stackoverflow.com/questions/40249660/how-to-store-very-wide-dask-dataframe-in-a-better-suited-format-than-csv)
- the to_hdf method requires some special attention to be able [to save in parallel](https://github.com/dask/dask/issues/1704)
- fastparquet will be a supreme solution but currently has the big disclaimer of beeing not battle tested.

I therefore figured, others might be in the same situation that they would like to provide as much metadata as possible to the read_csv function and wanted to suggest to extend the API of this method in a way, that known divisions along a specified index column can be provided.

**Comment by mrocklin** [comment]
Great.  If you can implement it in a clean maintainable way it would be
great to have help with read_csv.

**Comment by abast** [comment]
Okay, i will try that

**Comment by abast** [comment]
https://github.com/dask/dask/pull/1852

**Comment by abast** [comment]
as discussed in https://github.com/dask/dask/pull/1852, `df.set_index(column, sorted=True, divisions=...) ` works. This was also added to the docs. Closing.

**Comment by mrocklin** [comment]
Thanks for bringing this up and following it through.
