### ISSUE TITLE
DataFrame.set_index does not allow to specify the scheduler

### ISSUE THREAD

**Issue by abast** [dask/dask#1856]
Could DataFrame.set_index be changed in a way, that it accepts the `get=` keyword? Currently it fails with this error message:

> TypeError: set_partition() got an unexpected keyword argument 'get'

**Comment by mrocklin** [comment]
You should be able to use the `dask.set_options` context manager.  I think we generally stopped trying to add `get=` on all operations that do some computation, instead relying on the globals.  I'm open to having this change though.  In the mean time the following should work:

```python
with dask.set_options(get=...):
    df = df.set_index(...)
```

**Comment by abast** [comment]
That is what I ended up doing. So if I find more cases where a support for `get=` is missing according to my understanding, should I continue to raise issues? Should I collect all these cases in this issue and change its title accordingly?

**Comment by mrocklin** [comment]
Collecting issues here sounds good

**Comment by TomAugspurger** [comment]
I think we're OK with using context managers now.
