### ISSUE TITLE
Dask.distributed deployment

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#186]
We have a distributed scheduler.  All you need to do is have a bunch of machines and run a set of particular Python processes on those machines in a certain order.  Piece of cake eh?  Just a bit of ssh and bash scripting for all of our users.

This step is likely to stop most people.  We need simple mechanisms to bootstrap the scheduler and worker processes onto a cluster of machines.  Some options

1.  We could use systems like `yarn/mesos`
2.  We could bootstrap on top of IPython parallel and hope that users have that set up (is this true?)
3.  We could use something like `salt`?

I don't have much experience on this topic and hope that someone else comes by with a solution.

**Comment by venabled** [comment]
I saw some action in the IPython parallel examples, is that where you think you're headed?

**Comment by mrocklin** [comment]
Deployment is a hard problem and many users will probably want a many different things. 

However yes, as of https://github.com/ContinuumIO/dask/pull/208 you can now deploy dask.distributed given an IPython Parallel setup.  @cowlicks interested in adding a section to http://dask.pydata.org/en/latest/distributed.html on how to use this?

**Comment by cowlicks** [comment]
@mrocklin sure.

@venabled [here?](http://ipython.org/ipython-doc/dev/parallel/parallel_process.html) We can now use a `IPython.parallel.Client` connected to an `ipcluster` to set up dask distributed cluster.

**Comment by venabled** [comment]
@cowlicks I was reading thru #208 yesterday. I think this is probably a great example use case for what I want to do (smaller cluster of a few workstations vs large scale yarn/mesos deployment).

**Comment by mrocklin** [comment]
@venabled we would love to work with you on that.  Dask.distributed is new, seems to work fine, but has yet to be used in the wild.  If you're willing to kick some tires then we're willing to respond quickly to any problems or usability suggestions that you might have.  If you'd like to share a bit about what you're trying to do we can try to help get things started.  That conversation could happen here, on blaze-dev@continuum.io or on another github issue.

**Comment by mrocklin** [comment]
Oh, or this chat room, https://gitter.im/ContinuumIO/dask

**Comment by danielfrg** [comment]
I would say that the easiest solution would be to have some deploy scripts like spark has some scripts for deploying on EC2. I don't know how adopted IPython Parallel is but the deployment is basically the same problem than deploying a dask cluster.

The scripts don't have to be bash they could be a salt formula and it should be possible to use salt-ssh to run that so you don't need a salt master/minion cluster running. Also it should be relatively easy to add supervisord to the processes so they are restarted when they crash.

yarn/mesos would be the dream but the docs are not nice (if they even exists). My favorite is mesos and basically you have to go to the tests to see how to create a framework: https://github.com/apache/mesos/blob/d3847398d346b64112ae06a3fc60e53c2cec5212/src/examples/python/test_framework.py

**Comment by cowlicks** [comment]
Anaconda-cluster now uses salt to deploy and manage the processes.

**Comment by venabled** [comment]
Is there any open version of anaconda-cluster, or is it pay only?

**Comment by koverholt** [comment]
@venabled, currently, Anaconda Cluster is a premium/paid feature of the Anaconda platform. In the next few weeks, we are working on making Anaconda Cluster more generally available with a free usage tier. Stay tuned to the [Anaconda Cluster] (http://continuum.io/anaconda-cluster) page for updates, or contact Continuum for more information.

**Comment by mrocklin** [comment]
Just to be totally clear, dask in no way depends on anaconda-cluster or on any other proprietary project.  One can set up dask.distributed [easily](http://dask.pydata.org/en/latest/distributed.html#setup) by hand, particularly for system administrators.

Anaconda-cluster is one mechanism to handle this for you.  We'd love to see others arise as well.

**Comment by jcrist** [comment]
The distributed scheduler has been moved to its own project: https://github.com/dask/distributed. Closing.
