### ISSUE TITLE
client.restart() hangs

### ISSUE THREAD

**Issue by DFuller134** [dask/dask#1861]
client.restart() hangs at e.wait(1000000) in utils.py in sync(loop, func, *args, **kwargs).

client.restart() executes fine on a freshly booted cluster but this call hangs in this way even after scattering two small datasets (< 2% memory occupied) through the cluster.  Cluster is still functioning and responsive otherwise.

**Comment by mrocklin** [comment]
I've run into this myself.  Can you check if this problem persists in master as well (you would need to update both dask/dask and dask/distributed)?  

Are you able to reduce the failure to a relatively small case?  For example does it fail if you scatter even small results?

**Comment by DFuller-DAEN-Society** [comment]
Ok.  I'll be able to look deeper into this early next week.  I'll get back to you on my results.

**Comment by jcrist** [comment]
I'm unable to reproduce this locally on current master. Closing for now as stale, feel free to reopen if you can reproduce the issue.

**Comment by mrocklin** [comment]
Bugs were found and fixed in client.restart within the last month.
