### ISSUE TITLE
module 'dask.dataframe' has no attribute 'to_parquet'

### ISSUE THREAD

**Issue by markqiu** [dask/dask#1868]
import dask.dataframe as dd
df = dd.read_csv(...)  
to_parquet('/path/to/output/', df, compression='SNAPPY')  

AttributeError: module 'dask.dataframe' has no attribute 'to_parquet'

**Comment by mrocklin** [comment]
This is in the git version only.   Should have a release within a week or so.  See docs at http://dask.readthedocs.io/en/stable/ until then.

**Comment by markqiu** [comment]
OK, Thanks
