### ISSUE TITLE
Reading from HDFS does not work anymore. NotImplementedError: Unknown protocol hdfs

### ISSUE THREAD

**Issue by dojeda** [dask/dask#1870]
I've recently tried the latest development version of dask since there is support for parquet files (excellent!).
However, reading files from HDFS is no longer working. In version 0.12, the following minimum working example code to read a CSV file in a HDFS functions correctly:
```
from distributed import Client; client = Client()
import hdfs3
import dask.dataframe as dd
dd.read_csv('hdfs://hadoop-master/some_file.csv')
```

However, this same code does not work anymore, and the following exception is raised:
```
Traceback (most recent call last):
  File "/home/dojeda/apps/dask/dask/bytes/core.py", line 260, in __init__
    self.fs = _filesystems[self.protocol](**self.storage_options)
KeyError: 'hdfs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    dd.read_csv('hdfs://hadoop-master/some_file.csv')
  File "/home/dojeda/apps/dask/dask/dataframe/io/csv.py", line 271, in read
    **kwargs)
  File "/home/dojeda/apps/dask/dask/dataframe/io/csv.py", line 196, in read_pandas
    **(storage_options or {}))
  File "/home/dojeda/apps/dask/dask/bytes/core.py", line 145, in read_bytes
    None, **kwargs)
  File "/home/dojeda/apps/dask/dask/bytes/core.py", line 389, in get_fs_paths_myopen
    encoding=encoding, **kwargs)
  File "/home/dojeda/apps/dask/dask/bytes/core.py", line 263, in __init__
    (self.protocol, urlpath))
NotImplementedError: Unknown protocol hdfs (hdfs://hadoop-master/some_file.csv)
```

Apparently, the way files are read has been refactored in dask/dask#1774 but it does not seem to take into account the hdfs protocol. In fact, the global dict `_filesystems` in `dask/bytes/core.py` does not have a 'hdfs' entry, whereas 'file' and 's3' entries do exist because they are set by `dask/bytes/local.py` and `dask/bytes/s3.py` respectively.

Version information:
```
$ pip freeze | egrep "dask|distributed|hdfs"
-e git+https://github.com/dask/dask.git@aff7284671c9e3d443cec3a07855cafabeba8fc5#egg=dask
distributed==1.14.3
hdfs3==0.1.2

$ python --version
Python 3.5.2
```

**Comment by mrocklin** [comment]
The code in `distributed` was changed at the same time that the code in `dask` was changed.  You'll have to have both on the master version or both on the latest released version to make things consistent.

    pip install git+https://github.com/dask/distributed.git --upgrade
