### ISSUE TITLE
Possible direction for new Dask Interface

### ISSUE THREAD

**Issue by robdmc** [dask/dask#1873]
I'm a big fan of dask, and am grateful for all the work you guys are putting into it.  I tweeted to @mrocklin yesterday about an idea for a new dask interface and he suggested I open an issue on here.

I just released a pipeline tool for Python. https://github.com/robdmc/consecution

If the truth be told, I would much rather have used dask for the problem that inspired me to write consecution.  Unfortunately, I couldn't quite figure out how to get it to meet the requirements I had.  Consecution is a single-threaded synchronous approach to pipelining, which needless to say does not scale well.  I do, however, really like the user-facing interface it provides.

Not being at all familiar with the dask code-base, I'd be curious to know how hard it would be to implement an interface inspired by consecution.  Or, more importantly, I'd be curious to know if something like this would be within the scope envisioned for dask.

I would love to see the following features in dask.  I think doing this right could actually evolve the product to be more inline with the needs of database-driven production systems.

* Give nodes on your task graph the ability to maintain local state
* Give nodes access to some global_state object which they can read (and possibly mutate)
* Give nodes the ability to route output to specific downstream branches
* Give task graphs the ability to consume iterables

As a matter of context, I am currently using a slightly modified version of consecution in production to create pipelines for processing items consumed from database cursors.  I have found that this really helps write easily testable and maintainable code. 

Thanks again for all your work on dask.

**Comment by mrocklin** [comment]
Thanks for taking the time to write up an issue @robdmc .  If you don't mind I'd like to direct your attention to a few things in the distributed scheduler that might be relevant here.

1.  The dask.distributed scheduler implements the [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html) interface.  If you were to implement things on top of a concurrent.futures `Executor` then Dask might be able to drop in (assuming that functions didn't rely on global state.
2.  Queues: http://distributed.readthedocs.io/en/latest/queues.html
3. Launching tasks from tasks: http://distributed.readthedocs.io/en/latest/task-launch.html
4. Channels (https://github.com/dask/distributed/pull/729, https://github.com/dask/distributed/pull/749) and in particular a way to extend the scheduler and client

**Comment by robdmc** [comment]
@mrocklin Thanks for the pointers.  I'll put some thought into how one might build a dask-compatible version of this interface.  There is definitely some trickiness here.

**Comment by mrocklin** [comment]
Any update here?  I'm closing this for now (it appears to have gone stale) but feel free to reopen if you're still interested.
