### ISSUE TITLE
Drop support for pandas < 0.19?

### ISSUE THREAD

**Issue by jcrist** [dask/dask#1878]
Recent versions of pandas add some categorical niceties that would be nice to use in dask. These can be patched around with checks on version, but it may be nice to update to only supporting >= 0.19.0. This is related to #1877.

New niceties:
- unioning of categoricals (0.19.0)
- read_csv directly to categorical (0.19.0)

Ping @sinhrks, @shoyer, @TomAugspurger, @mrocklin, and @jreback for thoughts. I'm fine either way.

**Comment by jcrist** [comment]
I'm moving forward with this in #1877, unless anyone is against it.

**Comment by mrocklin** [comment]
I asked on twitter and within the for-profit side of continuum.  No one had any objections.

**Comment by jcrist** [comment]
Closed by #1877.
