### ISSUE TITLE
Implement Arrow HDFS data connector

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1880]
Arrow has an HDFS Client that implements the Python file interface

1.  http://pyarrow.readthedocs.io/en/latest/pyarrow.io.html
2.  http://wesmckinney.com/blog/python-hdfs-interfaces/

We should consider implementing a [dask.bytes backend](http://dask.pydata.org/en/latest/bytes.html) as an alternative to [hdfs3](http://hdfs3.readthedocs.io/en/latest/) which is backed by libhdfs3, which appears to be having community / maintenance issues.  This would also lessen the maintenance burden on Dask developers.

### Questions

1.  What needs to be implemented in Arrow?
2.  Is anyone interested in putting up a simple implementation?  This reference implementation for local files should serve as a sufficient reference: https://github.com/dask/dask/blob/master/dask/bytes/local.py

At first glance I suspect we could do a simple connector that didn't reason about data locality more-or-less immediately.  If we wanted data-local performance I suspect that arrow would need to improve to support getting block locations (I'm not seeing this in docs).

@wesm @martindurant @koverholt @quasiben

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-473.
