### ISSUE TITLE
calling delayed functions with lists is slow

### ISSUE THREAD

**Issue by abast** [dask/dask#1884]
The following is relatively slow:

```
myfun = lambda *args, **kwargs: None
%time d = [dask.delayed(myfun)(list(range(10000))) for i in range(100)]
```

> CPU times: user 11.2 s, sys: 88 ms, total: 11.3 s
> Wall time: 11.3 s

Since generating 100 lists of length 10k only takes about 50ms, the majority of the CPU time seems to be due to dask.delayed. What is dask.delayed doing behind the scenes?

Edit:
```
dask.__version__
> u'0.12.0'
```

**Comment by mrocklin** [comment]
It's checking if any element of the list is another delayed object, or a list/dict/set/tuple that might contain a delayed object.

**Comment by abast** [comment]
Okay, so I probably should avoid passing these types to `delayed` in general. 

Can I bypass the search that `dask.delayed` performs? Currently I try to hide all lists from dask delayed, e.g. using function enclosures, which feels a bit like a work around.

**Comment by mrocklin** [comment]
Relevant code is here: https://github.com/dask/dask/blob/bef55f24cba8687d93a0d08b1ac76cd409d70283/dask/delayed.py#L31-L88

```python
def to_task_dasks(expr):
    """Normalize a python object and extract all sub-dasks.
    - Replace ``Delayed`` with their keys
    - Convert literals to things the schedulers can handle
    - Extract dasks from all enclosed values
    Parameters
    ----------
    expr : object
        The object to be normalized. This function knows how to handle
        ``Delayed``s, as well as most builtin python types.
    Returns
    -------
    task : normalized task to be run
    dasks : list of dasks that form the dag for this task
    Examples
    --------
    >>> a = delayed(1, 'a')
    >>> b = delayed(2, 'b')
    >>> task, dasks = to_task_dasks([a, b, 3])
    >>> task # doctest: +SKIP
    ['a', 'b', 3]
    >>> dasks # doctest: +SKIP
    [{'a': 1}, {'b': 2}]
    >>> task, dasks = to_task_dasks({a: 1, b: 2})
    >>> task # doctest: +SKIP
    (dict, [['a', 1], ['b', 2]])
    >>> dasks # doctest: +SKIP
    [{'a': 1}, {'b': 2}]
    """
    if isinstance(expr, Delayed):
        return expr.key, expr._dasks
    if isinstance(expr, base.Base):
        name = 'finalize-' + tokenize(expr, pure=True)
        keys = expr._keys()
        dsk = expr._optimize(expr.dask, keys)
        dsk[name] = (expr._finalize, (concrete, keys))
        return name, [dsk]
    if isinstance(expr, tuple) and type(expr) != tuple:
        return expr, []
    if isinstance(expr, (Iterator, list, tuple, set)):
        args, dasks = unzip((to_task_dasks(e) for e in expr), 2)
        args = list(args)
        dasks = flat_unique(dasks)
        # Ensure output type matches input type
        if isinstance(expr, (tuple, set)):
            return (type(expr), args), dasks
        else:
            return args, dasks
    if isinstance(expr, dict):
        args, dasks = to_task_dasks([[k, v] for k, v in expr.items()])
        return (dict, args), dasks
    return expr, []
```

Delayed dives within standard Python collections (tuple, list, dict, etc.)  Making it possible to avoid searching seems reasonable but isn't currently implemented (to my knowledge).  Alternatively you could also use a container that is opaque to delayed like a NumPy array.  

*Ideally* you don't call `delayed` on data, but rather on the function that would produce the data.  This isn't always posible though.

**Comment by abast** [comment]
Thanks for pointing me to that function. 

If I pass a list of integers to that function, it appears to me that we get a list of empty dasks of the same length. Probably, they have to be merged later which also takes some more time. Would it make sense to add a test before the recursive call of `to_task_dasks`, so that we only enter the recursion, if there is at least one "interesting" object (another list, base.Base) in the list?

**Comment by mrocklin** [comment]
Yeah, I can imagine that some common case filtering might help out considerably. 

Here is a profile of your example:

```python
In [4]: %prun d = [dask.delayed(myfun)(list(range(10000))) for i in range(100)]
         10006976 function calls (9006874 primitive calls) in 4.728 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1000200    1.464    0.000    1.977    0.000 abc.py:178(__instancecheck__)
1000200/200    1.012    0.000    4.700    0.023 delayed.py:31(to_task_dasks)
  5001500    0.943    0.000    2.920    0.000 {built-in method builtins.isinstance}
  2000408    0.513    0.000    0.513    0.000 _weakrefset.py:70(__contains__)
  200/100    0.496    0.002    4.699    0.047 delayed.py:23(unzip)
  1000100    0.229    0.000    4.142    0.000 delayed.py:77(<genexpr>)
      200    0.043    0.000    0.043    0.000 itertoolz.py:193(unique)
        1    0.016    0.016    4.728    4.728 <string>:1(<listcomp>)
      100    0.002    0.000    4.705    0.047 delayed.py:391(call_function)
      200    0.001    0.000    0.001    0.000 {built-in method posix.urandom}
      200    0.001    0.000    0.002    0.000 uuid.py:106(__init__)
      200    0.001    0.000    0.044    0.000 delayed.py:18(flat_unique)
      200    0.001    0.000    0.001    0.000 uuid.py:226(__str__)
      700    0.001    0.000    0.001    0.000 delayed.py:348(__setattr__)
      200    0.001    0.000    0.006    0.000 delayed.py:91(tokenize)
```

**Comment by abast** [comment]
To figure out to what extend filtering might help, I did the following experiment:
```
args, dasks = unzip((to_task_dasks(e) for e in expr \
                             if isinstance(e, (Delayed, base.Base, Iterator, list, tuple, set, dict))), 2)
```
This gives ~50% speed increase, but not more. The remaining time seems to be on account of the 100*1000 calls of isinstance, which are probably inevitable if delayed is supposed to check every element in the list. So to get a significant speedup, I think the user needs to provide additional information.

Here an idea how the user interface could be extended:
We introduce the class `opaque`, which serves  as a simple wrapper around an arbitrary object. Delayed guarantees not to look into opaque objects. When compute is called, the underlying function is called with the object stored within `opaque`. So the original example would become:

```
from dask.delayed import opaque as o
myfun = lambda *args, **kwargs: None
%time d = [dask.delayed(myfun)(o(mylist) for i in range(100)]
```
What do you think? Do you see an opportunity for a significant speed up that does not require to change the user interface?

**Comment by jcrist** [comment]
Instead of adding another object/function, I suggest adding a new keyword to `delayed`, and using that to pre-wrap large objects. Perhaps call it `deep` or `traverse`. The default would be `True`, which is the current behavior, but you could set it to `False` to tell dask not to do a deep crawl of objects that are being wrapped. Then your application would be:

```python
d = delayed(myfun)(delayed(mylist, deep=False))
```

**Comment by mrocklin** [comment]
I lightly prefer traverse over deep.

We might want to try using type checks in some cases:

```python
typ = type(x)

# if isinstance(x, Foo):
if typ is Foo:  # this is faster 
```

I think that this might make sense for `Delayed`, `list`, `tuple`, and `set`.   @jcrist, any thoughts or warnings here?

Even if we implement deep/traverse it would still be good to do performance optimizations in the True case.  The naive users won't find the deep/traverse option.

**Comment by jcrist** [comment]
Adding `type(x) is foo` checks sound fine to me. We do that in several places elsewhere as well.

**Comment by abast** [comment]
The advantage of an additional opaque object might be, that the user can easily mix lists of delayed objects with data lists, something like: 

`delayed(myfun)(o(my_data_list), my_delayed_list)`

How could something similar be expressed with the API that provides a `deep` / `traverse` keyword?

**Comment by jcrist** [comment]
Once a python object is wrapped in a `delayed`, it's no longer traversed (and is effectively opaque). So the options are equivalent.

```python
my_list = [1, 2, 3]
# Looks at each element in the list to see if it's a dask object,
# before returning an instance of `Delayed`
delayed_list = delayed(my_list)
# Doesn't do the traversal, and just returns an instance of `Delayed`
delayed_list_2 = delayed(my_list, traverse=False)
# In the call here `my_list` is traversed (since it's a python object).
# Neither `delayed_list` or `delayed_list_2` are traversed, since
# they're already wrapped in `delayed`
delayed(myfun)(my_list, delayed_list, delayed_list_2)
```

Does that make sense?

**Comment by abast** [comment]
Okay, I see.

**Comment by abast** [comment]
So, whats the plan ... is someone already implementing the traverse keyword? Should I give it a try?

**Comment by abast** [comment]
Besides adding a traverse keyword, we discussed replacing `isinstance `with `type` for optimization purposes in this issue. From what I can tell, such optimizations are not included in #1899. Or am I wrong? So maybe we should leave this issue open?

**Comment by jcrist** [comment]
I profiled and found no change in performance when adding those optimizations. The small speedup of `typ is type` is negligible compared to other costs.

**Comment by abast** [comment]
Okay, thanks for explaining it.
