### ISSUE TITLE
Proposing `dask.array.map_blocks` function with multiple outputs

### ISSUE THREAD

**Issue by magonser** [dask/dask#1887]
Hi again,

as follow up from a [previous question on stackoverflow](http://stackoverflow.com/questions/41444462), I am trying to refactor my work from using my own dask-DAG assembly to `dask.array.Array` and `dask.delayed` syntax.

Because my application has functions with more than one return argument, e.g.

```python
def foo(x, y):
   return x*y, x+y
```

I get in trouble, when I try to map this across `dask.array.Array` blocks. E.g.

```python
import numpy as np
import dask.array as da
x = da.from_array(np.random.randn(3), chunks=2)
y = da.from_array(np.random.randn(3), chunks=2)

a, b = da.map_blocks(foo, x, y)  # Not working, just for demonstration
```

I have seen the [paused PR76](https://github.com/dask/dask/pull/76), however the proposed `map_blocks_multiple_outputs` seems not to be compatible any more with the current code base.

Another solution I could think of is to move the blocks to a delayed collection, iterate there, separate outputs and then reassemble the dask.array.Array. I could imagine it to be something like this:

```python
x_collection = x.to_delayed()
y_collection = y.to_delayed()
results = [delayed(foo, nout=2)(x, y) for x, y in zip(x_collection, y_collection)]
a_collection, b_collection = zip(*results)
a = da.from_delayed(a_collection)  # Actually this is wrong and does not work, but I try to convey the idea
b = da.from_delayed(b_collection)  # Actually this is wrong and does not work, but I try to convey the idea
```

A (sketchy) solution I came up with, looks like this:

```python
import dask.array as da
from dask import delayed
from itertools import product

def map_blocks(func, *arrs, nout=None, pure=False):
    arr0 = arrs[0]
    nr_common_dims = min([len(arr.shape) for arr in arrs])
    common_chunks = arr0.chunks[:nr_common_dims]
    arr_collections = [a.to_delayed() for a in arrs]
    common_blockshape = arr_collections[0].shape
    flat_arr_collections = [np.ravel(a, order='C') for a in arr_collections]
    blockshapes_common_dims = list(product(*common_chunks))  # Ordering needs to fit to np.ravel
    dfunc = delayed(func, nout=nout, pure=pure)
    flat_res_collections = [dfunc(*args) for args in zip(*flat_arr_collections)]
    if nout is not None:
        flat_res_collections = list(zip(*flat_res_collections))
    else:
        flat_res_collections = [flat_res_collections]
    # Unsolved problem: if `func` creates or destroys dimensions,
    # we can't know it automatically before evaluation. Refer also to `dask.array.Array.map_blocks`
    res_blockss = [[da.from_delayed(c, shape=s) for c, s in zip(fc, blockshapes_common_dims)]
                    for fc in flat_res_collections]  
    for iteridx, blocklen in enumerate(common_blockshape):
        res_blockss = [[da.concatenate(y[idx*blocklen:(idx+1)*blocklen], axis=(-1-iteridx)) for idx in range(len(y)//blocklen)] for y in res_blockss]
    res_blockss = tuple([r[0] for r in res_blockss])
    if nout is None:
        return res_blockss[0]
    return res_blockss

x = da.from_array(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]), chunks=(2, 3))
def foo(x):
    return x
x = map_blocks(foo, x, pure=True)

>>> x.compute()
array([[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10],
[11, 12, 13, 14, 15]])

x = da.from_array(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]), chunks=(2, 3))
def foo(x):
    return x, 2*x
x, y = map_blocks(foo, x, nout=2, pure=True)
>>>y.compute()
array([[ 2,  4,  6,  8, 10],
[12, 14, 16, 18, 20],
[22, 24, 26, 28, 30]])

x = da.from_array(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]), chunks=(2, 3))
def foo(x, y):
    return x*y
x = map_blocks(foo, x, x, pure=True)
>>>x.compute()
array([[  1,   4,   9,  16,  25],
[ 36,  49,  64,  81, 100],
[121, 144, 169, 196, 225]])
```

My intention is to start discussions about
    a) if this suits `dask` and should be considered implementing, and
    b) how to go about new and destroyed dimensions (tldr, need to better understand the existing approach in `dask.array.Array.map_blocks`)

Markus

**Comment by mrocklin** [comment]
General comment (I haven't yet looked at your implementation, but will soon):

There is only so much logic we can put into map_blocks.  Every time we add something (removing dimensions, multiple outputs, changing chunk size, etc.) we make it harder to add any future thing and maintain a consistent experience.  At some point we need to give up and recommend that users use dask.delayed.

So the hard part of doing this for map_blocks is really two things (which you've already alluded to).

1.  How do we add multiple outputs while still consistently supporting all other existing features
2.  How do we add multiple outputs with minimal complexity, so that it is still feasible to support other requests like this in the future.

This is getting harder and harder to do over time.

**Comment by shoyer** [comment]
Handling multiple outputs is one of the few remaining pieces of functionality that would allow dask to (naively) parallelize arbitrary [generalized ufuncs](https://docs.scipy.org/doc/numpy/reference/c-api.generalized-ufuncs.html). So I would welcome this functionality. But possibly it would be a better fit in `atop` than `map_blocks` (see https://github.com/dask/dask/issues/702) rather than `map_blocks`.

**Comment by magonser** [comment]
After reading documentation about `atop` and tried some simple examples on it, I also could imagine to have the functionality there instead. I get @mrocklin point about coming up with a sensible internal software architecture at that part of the code to be able to handle the broad scope of functionality. Unfortunately I haven't gained enough understanding of `dask.array` internals yet in order to come up with some ideas.

**Comment by magonser** [comment]
Refer to #3109
