### ISSUE TITLE
dtype kwarg for dask.array.random

### ISSUE THREAD

**Issue by jwittenbach** [dask/dask#1890]
It would be useful to have a `dtype` optional keyword argument on the array constructors in `random` (e.g. `randn`, `randint`, etc). This would mimic the NumPy API and avoid needing to call `astype` post creation.

**Comment by mrocklin** [comment]
I agree that this would be nice to have.  However it looks like very few of the numpy.random functions support this: https://docs.scipy.org/doc/numpy/reference/routines.random.html

**Comment by jwittenbach** [comment]
Huh, fair enough! I was playing with `randint` and assumed that was standard, but I guess it's actually exception.

**Comment by mrocklin** [comment]
You *could* raise an issue on NumPy.   I would love for this to become standard so that dask.array could add it as well.

**Comment by jwittenbach** [comment]
I think I shall 👍 

https://github.com/numpy/numpy/issues/8451

**Comment by mrocklin** [comment]
Happy to reopen if upstream changes
