### ISSUE TITLE
Looser meta enforcement option (aka allowing apply to not enforce a rename in `dd.apply_and_enforce`)

### ISSUE THREAD

**Issue by nirizr** [dask/dask#1895]
I would like to make a case for allowing a more flexible `dd.apply_and_enforce` specifically, and more generally permitting a more flexible dask operation. I would like to be able to avoid the `_rename` call in `dd.apply_and_enforce`, and instead validate `meta.columns` is a subset of `df.columns`.

I'll briefly describe my use case:
We have multiple sensors deployed at multiple client facilities. The process of updating a sensor is rarely smooth and clients usually update at their convenience (some with hard limitations on # of updates a year). Sensor updates carry new, removed and modified datasets, which translates to new columns in a `dask.dataframe`. Collecting data from multiple sensor versions makes it difficult for us to know which columns are to be expected in advance (sensor versions are created weekly and often add and remove dozens of columns). The data itself is pretty structured.

In the past, we created pandas dataframes with the right labels for each sensor separately and directly instantiated a `dd.DataFrame` and everything worked pretty good. Several sensor metadata column names were the only input to to `columns`. We couldn't use dask's interface to access columns except those initially declared (`df['Sensor_feature_1']` didn't work obviously), but that wasn't really needed.

I'm aware of the benefits of being strict and declarative about columns, but to me dask's previous flexibility had tremendous power and I would like to try bringing it back as a default-off flag with some restrictions and perhaps stricter sanity and dedicated tests, making it a feature and not a side-effect.

For now, I see this as:
* Adding `strict=True` parameter to `dd.DataFrame`, to avoid users doing it without explicit knowledge for now.
* Using that parameter in `dd.apply_and_enforce` (and perhaps other appropriate locations in the future).
* Adding sufficient tests for that specific use cases.
* Adding documentation with some kind of a disclaimer.

Thoughts?

**Comment by mrocklin** [comment]
In principle I'm for opting-in to looser restrictions as you suggest.  

I'm against adding another parameter to the actual dataframe object itself.  Tracking parameters through all DataFrame calls is expensive.  Currently there are only four (graph, name, meta, divisions)  However we can probably still accomplish this either through keyword arguments to the relevant methods or through globals.  I think that we would add strict as a parameter only after this became a more significant use case from more users. 

Alternatively, we could consider being loose by default, if we can demonstrate that we can do it in a way that never results in incorrect behavior for the known columns.  I'm not sure if this is possible, but might be worth thinking about.

cc @jcrist

**Comment by nirizr** [comment]
> I'm against adding another parameter to the actual dataframe object itself.

Valid point. Adding another parameter to the DataFrame constructor was just an interface suggestion, any approach is ok by me.

> we can probably still accomplish this either through keyword arguments to the relevant methods or through globals.

I tend to favor keyword arguments, but that adds some boilerplate kwargs passing from function to function, which dask already has a bit too much of IMHO. Sounds good nevertheless.

> we could consider being loose by default, if we can demonstrate that we can do it in a way that never results in incorrect behavior for the known columns.

Perhaps later on, if you ask me.

**Comment by jcrist** [comment]
Sorry for jumping in late here after you've already submitted a PR. I'm slightly against this, as every use case I can see can be solved in what I think is a cleaner way.

- If you want to treat all the frames as only having the intersection of their columns, then you can cull the extra columns on load using either the `usecols` keyword to `readcsv` (either in dask or pandas), or just subsetting the columns directly as `my_df[list_of_columns]`. This leads to each partition having matching metadata.

- If you want to treat all the frames as having the union of their columns, then `dd.concat` *will* do this for you. Pandas does this already, but dask doesn't in some cases (fixed in #1877). Here you'd use `dd.concat(dask_dataframes_for_each_file)`. If a partition is missing a column, it's filled with `NaN`s.

I'd really like to continue being strict about metadata - in the past being more lax has led to hard to diagnose bugs and harder to maintain code.

**Comment by nirizr** [comment]
_Just to be clear, my use-case is your second bullet, so I don't think the first is relevant to this issue._

I totally understand your concern about being less strict. I expected that (and was hoping for your involvement here) and for that reason I suggested this as somewhat of an experimental/"use at your own risk" type of thing.

Regarding the `concat` suggestion:
It took me a while to reply because I was benchmarking the two approaches:

- performing the same task: parsing files, minor cleanups, saving result to hdf files.
- on the same dataset: roughly 50g of data.
- in the same environment: 12cores xeon, 128g ram.

Had wildly different results. With my PR it took 4 and a half hours (and didn't peek above 30g of used ram). Without my PR and with calling `concat` it died for lack of memory after 10 hours. This might be handled as a `concat` performance issue (and if you wish I'll open a dedicated issue with more thorough benchmark and a reproduction), but I can understand why `concat` won't be as efficient as my suggestion in certain cases (mine included).

WDYT?

**Comment by mrocklin** [comment]
It looks like this proposal was rejected.  Closing.  My apologies for the lack of response.
