### ISSUE TITLE
Crash with pivot_table and bcolz compressed hdf

### ISSUE THREAD

**Issue by arita37** [dask/dask#1898]
The following code execution is fine (size is 1.7go HDF text+float), No Crash

```
############## 1.7 Go NO COMPRESS ####################################
df = dd.read_hdf( 'file_hdf_table_NOcompress.h5', key='df')
df.head()
df['company']= df['company'].astype('category')  ###Put in category some columns
df_pivot= df.pivot_table(index='brand', columns='company', values='purchaseamount', aggfunc='sum')
df_pivotr= df_pivot.compute()
```

But, I use the compressed file (bcolz compressed), pivot_table is crashing (Python.exe is crashing, so no error message). Total Memory usage is 2.2Go RAM on a 12GO RAM machine.

```
############## 1.7 Go NO COMPRESS ####################################
df = dd.read_hdf( 'file_hdf_table_bcolz_compress.h5', key='df')
df.head()
df['company']= df['company'].astype('category')  ###Put in category some columns
df_pivot= df.pivot_table(index='brand', columns='company', values='purchaseamount', aggfunc='sum')
df_pivotr= df_pivot.compute()
```

```
dask 0.13
pandas 0.19.2
```

**Comment by abast** [comment]
Not sure about the relevance, but: 
(1) I remember when I had a C library that caused a segfault, there was no error message in IPython, but if I simply started python in the terminal and executed my code there, I got an error message. Did you check if there might be an error message in the terminal? 
(2) Also did you try to run the test suite of the pytables package to figure out, if everything is ok with your pytables setup?

```
import tables
tables.test()
```

**Comment by arita37** [comment]
Forget to add that:
`    df = pandas.read_hdf( 'file_hdf_table_bcolz_compress.h5', key='df')`
works well and I generate pivot table on it (after load it in memory).

Running this code takes (over 15mins...) .
```
import tables
tables.test()
```

**Comment by arita37** [comment]
Additionnal point (beyond this issue reporting).
To make it more efficient bug/issue report --> Check --> debugging/improvement as well as
to be better 'Bullet proof' tested on real user cases, propose the following:

Create a large "open directory" where  user put  : 
      1) Create sub-folder
      2) In that folder create :  
              1) test_script.py
              2) data folder when all the data are put (txt, hdf, ....)
              3) .txt file when the problem is described.

To validate the folder, 'user 'or 'batch' has to run it and print output.

So,  you will get :       
        Community working for you to create real user case.
        Reduce the number of regression testing you have to setup.
       Bug/Issue reporting can be automatized.... 
           You can even analyze the issues by Machine Learning models....

       You can focus on 'solving the engineering problem' rather 're-testing'.....

Your tought are welcome !

**Comment by jcrist** [comment]
I believe this is an issue with thread safety in hdf5. This should be handled by setting `lock=True` in `dd.read_hdf`. Without a reproducible test case I'm not sure how we can help debug here.

I'm closing this for now as stale (sorry for just getting to it now). If you're still having this issue and have a reproducible test case you can share, please feel free to reopen.
