### ISSUE TITLE
GSOC 2017: NumFOCUS will be an umbrella organization

### ISSUE THREAD

**Issue by kain88-de** [dask/dask#1917]
Hi

Organizations can start submitting applications for Google Summer of Code
2017 on January 19 (and the deadline is February 9)

https://developers.google.com/open-source/gsoc/timeline?hl=en

NumFOCUS will be applying again this year. If you want to work with us
please let me know and if you apply as an organization yourself or under a
different umbrella organization please tell me as well. If you participate
with us it would be great if you start to add possible projects to the
ideas page on github soon. We some general information for mentors on
github.

https://github.com/numfocus/gsoc/blob/master/CONTRIBUTING-mentors.md

We also have a template for ideas that might help. It lists the things
Google likes to see.

https://github.com/numfocus/gsoc/blob/master/2017/ideas-list-skeleton.md

In case you participated in earlier years with NumFOCUS there are some
small changes this year. Raniere won't be the admin this year. Instead I'm
going to be the admin. We are also planning to include two explicit rules
when a student should be failed, they have to communicate regularly and
commit code into your development branch at the end of the summer.

best, Max

**Comment by mrocklin** [comment]
I used to mentor for the SymPy project and found it generally to be good for the community and a nice way to attract a new developer or two each season.  I think that there are two challenges:

1.  Finding a self contained project that a student can reliably complete within a summer that is important enough to matter but not a priority enough that some senior developer won't swoop in and finish it.
2.  Finding a senior developer with time to mentor the student, or a student that has already demonstrated sufficient maturity to not need much mentoring

Some thoughts on projects:

1.  R or Julia client/workers.  We might be able to jointly mentor with someone from those communities, although they're quite busy as well.  cc @shashi
2.  Some particular class of machine learning algorithm.  Someone from sklearn might be able to jointly mentor here.  @amueller @ogrisel if you have any thoughts here for good topics or mentors please speak up.
3.  ?? (other suggestions anyone?

Thanks for bringing this up @kain88-de

**Comment by kain88-de** [comment]
As a note I'm also writing all other NumFOCUS projects. You should see soon which organizations will also apply for GSoC and where on the repository I liked above.

A tip about estimating project size. It shouldn't take an experienced developer more then a week to implement. It gives students an appropriate amount of time to get to know the code base and understand the problem.

**Comment by mrocklin** [comment]
I suspect that the deadline for this has passed.  Closing.
