### ISSUE TITLE
Launch tasks from tasks, similar to Dask.distributed's local_client()

### ISSUE THREAD

**Issue by bschreck** [dask/dask#1918]
Is it currently possible to send additional tasks to the scheduler from within a dask task? In particular, I'd like to be able to compute a Delayed object, which does some stuff, then launches a big parallel map job, and then does some stuff with the results and returns.

In the distributed case, I can use local_client() to launch additional tasks, however on a single machine using the multiprocessing backend, if I just try to compute dask tasks like bag.map() I get an error that Daemon threads can't spawn additional processes (which seems like it would be the case just running a parallel joblib map() as well). So maybe it's more fundamental of a design decision to allow this.

The reason I don't want to just expand the Delayed call into several tasks up front is that I essentially have several layers of scheduling to do, and the user only sees the top level. So each user-submitted function should ideally be able to do some lower level scheduling of smaller tasks from inside of it.

**Comment by mrocklin** [comment]
`local_client` only works with the distributed scheduler.  The distributed scheduler however works very well on a single machine as a replacement for the multiprocessing scheduler.  If you do the following then you might be fine.

```python
from dask.distributed import Client
c = Client()  # creates local processes, registers itself as the global scheduler
```

**Comment by bschreck** [comment]
hmm yeah I could definitely do that- how much overhead is it compared to the multiprocessing scheduler? I'm expecting this calls on a single laptop to take 30 seconds to a minute if parallelized well (as in that's what we were getting using joblib or multiprocessing before trying out dask/distributed)

**Comment by mrocklin** [comment]
The distributed scheduler generally has better performance characteristics
than the multiprocessing scheduler.
