### ISSUE TITLE
Add arguments to Delayed node after initializing

### ISSUE THREAD

**Issue by bschreck** [dask/dask#1922]
Right now I let users create a bunch of delayed nodes, and then when they run a special compute() function, I need to add in another argument (which is itself a delayed node - containing some data) to each node's kwargs. I do this right now by manually creating new nodes with a new dask dict containing the additional argument, however this seems buggy.

I can't just call the nodes again with the new argument because then I end up with another node that apply's the first with the new argument. This will end up trying to run the delayed object's function without the argument first and so will fail.

Any suggestions? Is there anything dask provides for adding arguments after the fact?

**Comment by mrocklin** [comment]
There is nothing that facilitates this built in, no.  Dask generally tries to determine keynames based on all inputs in order to avoid collisions.  Changing an argument after creating the graph goes against some assumptions.

That being said, it's still entirely possible.  If I were to do this I would probably do it the way you're doing it, by updating the dict manually, perhaps something like the following:

```python
In [1]: from dask import delayed

In [2]: parameter = delayed('parameter-to-be')

In [3]: def f(*args):
   ...:     pass
   ...: 

In [4]: value = delayed(f)(1, 2, 3, parameter)

In [5]: dsk = value.dask

In [6]: dsk
Out[6]: 
{'f-a148efd4-e196-4347-8121-142c71434cbe': (<function __main__.f>,
  1,
  2,
  3,
  'str-48fa645d-3366-4366-b4f1-244168f6b05c'),
 'str-48fa645d-3366-4366-b4f1-244168f6b05c': 'parameter-to-be'}

In [7]: params = {parameter.key: 'actual-parameter'}

In [8]: dsk.update(params)

In [9]: dsk
Out[9]: 
{'f-a148efd4-e196-4347-8121-142c71434cbe': (<function __main__.f>,
  1,
  2,
  3,
  'str-48fa645d-3366-4366-b4f1-244168f6b05c'),
 'str-48fa645d-3366-4366-b4f1-244168f6b05c': 'actual-parameter'}

In [10]: from dask.threaded import get

In [11]: get(dsk, value.key)
```

**Comment by bschreck** [comment]
Thanks, that's much easier than what I was doing (walking through the dask dicts, finding my function names, and appending the new kwarg to the list of lists representation of it).

**Comment by mrocklin** [comment]
Cool.  I'm going to close this now.  I think that this is not the sort of thing I want to encourage with actual API :)  However hopefully future individuals with this issue will come across this issue and it will help them.  Thanks for raising.
