### ISSUE TITLE
Suggestion: provide a padding function for Dask arrays

### ISSUE THREAD

**Issue by mratsim** [dask/dask#1926]
Hi team,

I'm currently working on a dataset of 3D images that will be fed to a neural network.
The input arrays have varying sizes along all 3 axis for example:
[390, 355, 355]
[390, 414, 414]
[398, 474, 474]
[403, 474, 474]
[412, 490, 490]
[530, 490, 490]

All images would fit in a 530 x 490 x 490 array
I would like to pad smaller images with 0, or even better the 'edge' value as in numy.pad, so they all have the same 530x490x490 shape.

I don't see how to do that within dask without reverting to Numpy and using either:

1. assignment
(from https://stackoverflow.com/questions/35751306/python-how-to-pad-numpy-array-with-zeros)

```python
def pad(array, reference_shape, offsets):
    """
    array: Array to be padded
    reference_shape: tuple of size of narray to create
    offsets: list of offsets (number of elements must be equal to the dimension of the array)
    will throw a ValueError if offsets is too big and the reference_shape cannot handle the offsets
    """

    # Create an array of zeros with the reference shape
    result = np.zeros(reference_shape)
    # Create a list of slices from offset to offset + shape in each dimension
    insertHere = [slice(offsets[dim], offsets[dim] + array.shape[dim]) for dim in range(array.ndim)]
    # Insert the array in the result at the specified offsets
    result[insertHere] = array
    return result
```

2. or np.pad (see https://stackoverflow.com/questions/29218785/numpy-scale-3d-array)

I believe this is a very common scenario while preprocessing images for machine learning.

**Comment by shoyer** [comment]
Yes, this would be a useful addition to dask.array.

Any interest in putting together a PR? See http://dask.pydata.org/en/latest/array-design.html for details on how dask array works internally -- this should be pretty straightforward.

**Comment by mrocklin** [comment]
This is particularly straightforward if the images that you want to pad are each in a single chunk.  If that was the case then you could probably do this now with `da.map_blocks` and `np.pad`.

**Comment by mratsim** [comment]
@mrocklin ah I missed the map_blocks function.

@shoyer Thanks for the link I will try that.

**Comment by jakirkham** [comment]
Also interested in this. It would be great to even have some reasonable subset of the functionality that [`numpy.pad`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html ) provides in `dask.array`. In particular, the padding with zeros you have described. Are you working on something in this direction, @mratsim, or is anyone else?

**Comment by jakirkham** [comment]
Guess I forgot to mention this. :)

Have worked up an implementation of `pad` for Dask Arrays in PR ( https://github.com/dask/dask/pull/3578 ). This matches NumPy's `pad` API reasonably well. Could be used very easily to pad with `0`s or a variety of other useful things.

Would appreciate hearing feedback on it.
