### ISSUE TITLE
DataFrame.to_parquet add support for append

### ISSUE THREAD

**Issue by kayibal** [dask/dask#1936]
Would very much appreciate to get some guidance on how to implement this.

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
Append is already implemented in fastparquet, so won't be hard to implement for dataframes. What does the intended workflow look like?

**Comment by kayibal** [comment]
Just implemented this seems to work. We have daily clickstream data dumps that we would like to save into a continous parquet archive.
