### ISSUE TITLE
Update read_csv, read_hdf, and read_table to take a list of files

### ISSUE THREAD

**Issue by jtf621** [dask/dask#1948]
I have found that 

    dd.read_csv('myfiles.*.csv')
    dd.read_hdf('myfiles.*.csv', key='whatever')

could be improved by allowing an iterable of filenames to be passed in as the `urlpath` argument.  This allows more fine tuned filtering than the glob patterns and allows you to sample the `urlpath` during development.

    # example usage
    files = glob('myfiles.*.csv')
    files = random.sample(files, 5)  # work on a subset of the files for initial development
    df = dd.read_csv(files)

I also want `read_hdf` and `read_table` to have the same feature.  

My current workaround is to

    # example usage
    files = glob('myfiles.*.csv')
    files = random.sample(files, 5)  # work on a subset of the files for initial development
    dfs = [dd.read_csv(f) for f in files]
    df = dd.concat(dfs)

**Comment by apiszcz** [comment]
Related issue.
Is there a method to get the list of files discovered from the glob pattern?
While we are wishing, I'd like to see REGEX support for the urlpath.
Thanks.

**Comment by martindurant** [comment]
Sorry for not having noticed this before, @jtf621 - it is certainly something we can implement.

@apiszcz : there is currently no way to extract the list of files that were used, but you can look at the file-system classes dask.bytes.core._filesystems, e.g., dask.bytes.local.LocalFileSystem, and call it's glob method (which in this case called the builtin glob function).

For regex support, would you imagine passing `regex=True` to evaluate the path as a matching pattern?

**Comment by apiszcz** [comment]
Thank you, That would be great, another capability I'm in search of is to
obtain a list/dictionary of the input filenames to chunks or partitions.
regex=True is fine, glob is limited compared to regex.

**Comment by martindurant** [comment]
"obtain a list/dictionary of the input filenames to chunks or partitions" - I could see how this information might look, but I don't see how it could be returned. The purpose of the functions is to create dataframes, so it would not be appropriate to return anything else.  It would be possible to add a column to each partition with the data's origin, or put the file/offset in the partition's `name` field, but this would take a bit of untangling the current code path.

**Comment by martindurant** [comment]
Note that read_csv already does support passing a list of files.

**Comment by apiszcz** [comment]
and a name filter, thanks.

**Comment by martindurant** [comment]
"name filter" - sorry, what do you mean here? I thought you wanted to pass your own list of filenames or a regex to match against.

**Comment by jtf621** [comment]
Thank you @martindurant, @jcrist
