### ISSUE TITLE
Plan to support external data ingestion functions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1959]
People will want to ingest data into Dask from a variety of other databases.  For example, here is a small gist someone posted on twitter for a function to ingest from ElasticSearch:

https://gist.github.com/rolando/f4e912aadc8447463209d4fe672c260c

How do we collect these?  I have no desire to hold every possible combination within the dask repository itself, but at the same time there should be some way to curate solutions like this.

What are some options?

1.  Put everything in dask/dask
2.  Manage small repositories like dask/dask-elasticsearch
3.  Create a list of pointers to other projects and put them in documentation
4.  Just let people google for "how to query elasticsearch with dask"

**Comment by mrocklin** [comment]
Looks like the author put it on pypi, which is another fine way to handle this.  

https://pypi.python.org/pypi/dask-elasticsearch/

**Comment by mrocklin** [comment]
https://pypi.python.org/pypi/dask-avro

**Comment by mrocklin** [comment]
cc @rolando

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by rolando** [comment]
@mrocklin thanks for keeping me in the loop.

I've been using those little snippets for a while but now required to package it to have it available for another project. Fun fact: I was using a small Elasticsearch instance and was faster to load the search results into Dask and do aggregations than doing it on ES.

The option 1. can definitely be a maintenance burden for core developers. Option 2. brings more visibility to third-party projects.

I'm OK with transferring the projects under Dask organization. I think those small projects could be considered in incubating stage and if they become popular, feature complete and stable, then they can be considered for merging into Dask codebase.

**Comment by martindurant** [comment]
I like the idea of "incubating" related packages and scripts, although a "contrib" area in the main repo, or a contrib repo by itself would have a similar effect. Getting more people to contribute and collaborate must be a good thing.
The important point is for the team not to become responsible for the correctness of contributed code, and to let users know that these might be written to work only for some specific use case, etc.

**Comment by mrocklin** [comment]
CCing @kszucs who had similar thoughts about a third-party Marathon deployment package

**Comment by kszucs** [comment]
I like odo's approach: https://github.com/blaze/odo/blob/master/odo/__init__.py#L26, but the plugins needs to be highly related like cluster backends (SGE, Mesos) or databases/file systems (like s3 of hdfs already) and stable enough. BTW I hate importing dask_marathon/dask_mesos/<anything underscored> :) 

Importing from dask or distributed would guarantee the consistent API across plugins, and hopefully decrease the learning curve. It also needs a clear style guide though. 
I'd keep these integrations/plugins in separated repos (learning the whole dask/distributed codebase can be frightening), but under dask org (helps discovering).

**Comment by mrocklin** [comment]
Are there good ways to maintain a contrib namespace in Python?

**Comment by kszucs** [comment]
There are [ways](https://www.python.org/dev/peps/pep-0420/) but I wouldn't call them `good`

**Comment by jcrist** [comment]
I wrote up a quick demo of how we could do this with namespace packages: https://github.com/jcrist/namespace_modules.

Pros:
- Slightly prettier import syntax:

 ```python
from daskit import elastic_search, other_stuff
# vs
import dask_elastic_search
import dask_other_stuff
```

- Namespaces are kind of nice for organizing similar things

- Matplotlib does this with the `mpl` namespace, so there's some precedence here.

Cons:
- Slight potential for getting issues in main dask repo about sub-packages that we don't maintain (since the top-level namespace would point to this repo). This probably isn't a big deal though.

- May be more effort than it's worth


Either way, I think we should have a docs page with a list of packages, similar to what [scikit-learn does](http://scikit-learn.org/stable/related_projects.html).

**Comment by rolando** [comment]
I think a guideline should be to use the dask namespace for somewhat well-maintained packages. Otherwise there is the risk of polluting dask namespace with half-baked unmaintained modules. It won't be nice to have two or more contrib packages for the same task (i.e. `daskit.elasticsearch`, `daskit.esreader`, `daskit.fastelasticsearch`, `daskit.espy4`, etc).

**Comment by jakirkham** [comment]
If this is already a really big space of subprojects, maybe it is worth looking at how Jupyter manages/solves this problem.

cc @minrk

**Comment by minrk** [comment]
I think separate repos/packages is a good idea. Being liberal about including such projects on the dask GitHub org is one path to visibility, as is maintaining a good list in your docs. Presence on the org doesn't need to mean that every package is maintained by the same people (examples orgs: zeromq, jupyterhub), but you may take care to indicate this for contributed packages.

Assuming they are separate packages:

I like the idea of namespace packages a lot, but they have been an occasional source of frustration in practice. We considered using namespace packages for Jupyter when we were planning the big split, but ultimately decided against it, going with discrete packages. That doesn't mean it was the right decision, though.

Cons of namespace packages:

- People can be confused by import errors of what appear to be subpackages ("I have dask, why don't I have dask.ec2?"). ImportErrors of a top-level package are more searchable.
- It seems to be possible to corrupt namespace packages during installation. We still get some bug reports about one or two of our dependencies that use the `backports` namespace appearing to be unavailable and requiring reinstall. I still don't know how this is happening.

Another possible option (depending on API requirements) is to use  [entrypoints](http://entrypoints.readthedocs.io/en/latest/). We've started using this in a few places in Jupyter to provide things like custom nbconvert exporters and it's been a nice way for additional packages to make themselves known, but it assumes plugins provide a consistent API.

One option:

- use `dask.whatever` namespace package for 'official' packages
- incubating/community packages are standalone packages
- community packages can be 'promoted' to `dask.thing` if that's deemed desirable.

**Comment by jakirkham** [comment]
As to a doc listing, PR ( https://github.com/dask/dask/pull/2395 ) seems relevant.

**Comment by mrocklin** [comment]
I'm going to close this.  Folks can use normal mechanisms, include in docs, or use aggregation libraries like intake where appropriate.
