### ISSUE TITLE
Trouble connecting to S3

### ISSUE THREAD

**Issue by brendancol** [dask/dask#1960]
I was recently trying to read content with acl-private from S3 and had trouble with `dask.bag.read_text`.  Here are some of the step I took.  In the end, I was still unable to connect.  Note I'm using an IAM account, but I did verify separately that my account has S3 full access:

**Example:**
The code below would raised a `NoCredentials` error.
<img width="1156" alt="screen shot 2017-02-03 at 12 36 20 pm" src="https://cloud.githubusercontent.com/assets/433221/22601863/e44aaed2-ea0e-11e6-9430-cdd4d7820a00.png">
```
import dask.bag as db
b = db.read_text('s3://xdata-breach-data/dumps/*.txt',
                 errors='ignore', 
                 blocksize=10000000)
```

In the case of the workers, I have a `.aws/credentials` file on each node.  I was also able to verify that both `boto` and `boto3` were able to find credentials:
```
import boto
print(boto.connect_s3()) # ----> no problem

import boto3
print(boto3.client('s3')) # ----> no problem
```

I configure via the following methods config file methods: 
- `.boto`
- `.aws/config`
- `.aws/credentials`
- `/etc/boto.cfg`
- environment variables in `/etc/profile` and `.bashrc`

I also attempted passing the credentials via `read_text->storage_options`.  In this case I got ```TypeError: __init__() got multiple values for argument 'aws_secret_access_key'```

**Comment by rolando** [comment]
Try passing `key` and `secret` as storage options.

**Comment by brendancol** [comment]
@rolando passing key/secret kwargs seems to solve the `TypeError`.  Now I get a `FileNotFoundError: s3://my-bucket/dumps/myfile.txt`.  I tried making it public and still no luck. I'm going to keep digging though

**Comment by jcrist** [comment]
@brendancol did you ever resolve this?

**Comment by brendancol** [comment]
@jcrist No it was never resolved on my side.  This issue was really strange, cause I figure others would also be experiencing this same issue if it was truly an issue.  Have you guys tested with `acl-private` content?

I would think if nobody else has reported a problem, then it was something with me and not dask

**Comment by martindurant** [comment]
I can see your data now that it's public, using the same read_text line above.
I would guess you are not being authenticated as you think, or perhaps not at all for some reason. Have you tried with s3fs directly? The storage_options are the same kwargs as passed to the S3FileSystem constructor (except username and key both become key and password and secret both become secret).

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if you can provide a [reproducible example](https://stackoverflow.com/help/mcve)

**Comment by mromanello** [comment]
hello !

I've been running into this very same issue for a while now, i.e. not being able to read/write via `dask` from/to a non-AWS S3 endpoint. 

I've tried various ways of passing my s3 endpoint to `dask` via the `storage_options` parameter, but with no luck.

I've provided a minimum reproducible example here below using a toy public bucket so that this issue can be re-opened.

Many thanks in advance for your help!

## Example

- s3 host: `os.zhdk.cloud.switch.ch`
- bucket (`acl-public`): `impresso-public` 
- bucket contents: two JSON lines files (`'impresso-public/GDL-1799.jsonl', 'impresso-public/NZZ-1780.jsonl'`)

```python
import dask.bag as db
b = db.read_text(
    's3://impresso-public/*jsonl', 
    storage_options={'host': 'os.zhdk.cloud.switch.ch', 'anon':True}
)
```

This raises the following exception: 

```python
ValueError: ('No files found', 's3://impresso-public/*')
```

Funnily enough, if I try to connect instead via `s3fs` I can list the bucket's contents

```python
import s3fs

fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url':'https://os.zhdk.cloud.switch.ch'},
    anon=True
)
fs.ls('impresso-public')
>>> ['impresso-public/GDL-1799.jsonl', 'impresso-public/NZZ-1780.jsonl']
```

**Comment by martindurant** [comment]
The arguments provided in `storage_options` should match the ones that successfully list the files:
```
storage_options={'client_kwargs': {'endpoint_url':'https://os.zhdk.cloud.switch.ch'}, 'anon':True}
```

**Comment by martindurant** [comment]
Were you looking here: http://docs.dask.org/en/latest/remote-data-services.html#amazon-s3 ?

The trouble is, that there are many such loading functions where this can apply, and a whole lot of backends with various parameters that might be appropriate. Perhaps every mention of `storage_options` should be accompanied by a link to the remote-data-services page.

**Comment by mromanello** [comment]
I don't know if the documentation has changed recently, but the current one seems much more detailed than the last time I checked. I think it's pretty clear now where the parameters should go! Many thanks again for your help.

**Comment by martindurant** [comment]
Glad to hear!
