### ISSUE TITLE
dask set_index gives different index type compared to that from_pandas?

### ISSUE THREAD

**Issue by DigitalPig** [dask/dask#1965]
I am trying to read a csv using `dask` and then resample it based on its timestamp index.

The csv file has content like:
```
Time,data
2015-01-01,0
2015-01-02,1
2015-01-03,2
2015-01-04,3
...
```
## Method 1: Using `dask` load the data directly and then setup the index:
```python
import pandas as pd
import dask.dataframe as dd
data_sample = dd.read_csv('test_data.csv')
meta=pd.Series([], name='time',dtype=pd.Timestamp)
data_sample['Time'] = data_sample['Time'].map_partitions(pd.to_datetime, meta=meta)
data_sample2 = data_sample.set_index(data_sample['Time'])
data_sample2.index.head()
```
And I got:
```python
DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
           '2015-01-05'],
          dtype='datetime64[ns]', name='Time', freq=None)
```
However, when I am trying to do: `data_sample2.resample('1M').mean()`

I have the following error: 
```
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```
## Method 2:

If I use `pandas` load the data and then convert it to dask.dataframe, it seems to be OK:
```python
pd_data = pd.read_csv('test_data.csv')
pd_data['Time'] = pd.to_datetime(pd_data['Time'])
pd_data.set_index(pd_data['Time'],inplace=True)
pd_data.index
data_sample_from_pd = dd.from_pandas(pd_data, npartitions=1)
data_sample_from_pd.index.head()
```
And the dtype seems to be the same:
```python
DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
           '2015-01-05'],
          dtype='datetime64[ns]', name='Time', freq=None)
```
And the `resample` works fine:
```python
data_sample_from_pd.resample('1M').mean().head()

data
2015-01-31  15.0
2015-02-28  44.5
2015-03-31  74.0
2015-04-30  94.5
```

Any idea why it is like this?

**Comment by mrocklin** [comment]
I apologize for the very long delay here.  I suspect that the reason for this reduces down to the following:

```python
In [1]: import pandas as pd

In [2]: s = pd.Series([1, 2, 3], dtype=pd.Timestamp)

In [3]: s
Out[3]: 
0    1
1    2
2    3
dtype: object
```

Instead I recommend relying on the `pd.to_datetime` function directly to make your metadata

```python
In [6]: s = pd.to_datetime(pd.Series([], name='time'))

In [7]: s
Out[7]: Series([], Name: time, dtype: datetime64[ns])
```

This would probably also work if you don't include `meta=`, in which I case I think dask.dataframe would do `s = pd.to_datetime(pd.Series([], name='time'))` for you.

**Comment by jreback** [comment]
as a follow up to @mrocklin comments,

[1] is not valid at all (this should prob raise as its a completely invalid dtype).
[2] gives you a Series with the proper empty dtype.
```
In [1]: pd.Series([], name='time',dtype=pd.Timestamp)
Out[1]: Series([], Name: time, dtype: object)

In [2]: pd.Series([], name='time',dtype='M8[ns]')
Out[2]: Series([], Name: time, dtype: datetime64[ns])
```

**Comment by mrocklin** [comment]
Closing.  Please reopen if problem persists.
