### ISSUE TITLE
Using threaded scheduler from forked process 

### ISSUE THREAD

**Issue by rmancy-smg** [dask/dask#1967]
I was getting some decent performance from using `delayed()` with the threaded scheduler, but it still only runs on a single core.

I thought I would fork (either via `multiprocessing.Pool` or `dask.multiprocessing.get`) the code that called the `compute()` so I could get a `ThreadPool` running on all cores.

The problem is that `ThreadPool` is created at import time, and in the main thread. We're then calling functions (i.e `apply_async()`) to the `ThreadPool` from a child process. This doesn't work.

I tried a very naive approach of just moving the `ThreadPool`  instantiation to inside the `get()` call. This *seems* to work, but I haven't thoroughly tested it and it could very well break things elsewhere (or may in fact be the wrong approach all together).

AFAICT this https://github.com/dask/dask/pull/1487 is the PR that introduced this `ThreadPool` instantiation.

Cheers.

**Comment by mrocklin** [comment]
What version are you using?  Dask currently creates a ThreadPool on the first call to `threaded.get` to avoid this sort of problem.

You may also want to consider running the [distributed scheduler](http://distributed.readthedocs.org) on a single machine.  It provides many processes, each of which have a thread pool by default.  See http://dask.pydata.org/en/latest/scheduler-choice.html

**Comment by rmancy-smg** [comment]
Ahh, yeah. I should've checked on master. I'm using dask-0.11.1. If there's no dep changes on pandas or numpy I will likely upgrade.

I'll take another look at the local scheduler (I have tested it before with a different kind of job, and it didn't really help in that particular instance). If it will fork multiple ThreadPools than that would likely suit me for this application.
