### ISSUE TITLE
`dask.compute` on nested Python objects

### ISSUE THREAD

**Issue by eriknw** [dask/dask#1968]
I really like using `dask.compute` to calculate many things in a single pass over the data.  I sometimes even do so programmatically--e.g., from using results from a previous pass over the data.  The single list format via `*args` in `compute` is somewhat limiting.  I want a `compute` that also computes elements from nested dicts and lists.  I hacked/whipped up the following to do this that uses `dask.compute`:
```python
# Extend `dask.compute` to work on nested data structures.
from toolz import concat
from dask import compute

def _flatten_compute(vals):
    if isinstance(vals, list):
        inner = list(concat(map(_flatten_compute, vals)))
        return ['list', len(inner)] +  inner
    elif isinstance(vals, dict):
        inner = []
        for k, v in vals.items():
            inner.append(k)
            inner.extend(_flatten_compute(v))
        return ['dict', len(inner)] +  inner
    else:
        return ['item', vals]


def _rebuild_compute(results, start=0):
    if results[start] == 'list':
        rv = []
        stop = start + 2 + results[start + 1]
        i = start + 2
        while i < stop:
            val = results[i]
            if val == 'item':
                rv.append(results[i + 1])
                i += 2
            else:  # list or dict
                rv.append(_rebuild_compute(results, start=i))
                i += 2 + results[i + 1]
        return rv
    elif results[start] == 'dict':
        rv = {}
        stop = start + 2 + results[start + 1]
        i = start + 2
        while i < stop:
            key = results[i]
            val = results[i + 1]
            if val == 'item':
                rv[key] = results[i + 2]
                i += 3
            else:  # list or dict
                rv[key] = _rebuild_compute(results, start=i + 1)
                i += 3 + results[i + 2]
        return rv
    else:
        raise ValueError('Does not compute: %s %s' % (start, results))


def compute_nested(*args, **kwargs):
    """Extended ``dask.compute`` to work on nested data structures.
    
    This will compute (potentially nested) elements in lists and
    values in dicts.  For example:
    
    >>> compute_nested({'total': bag.count(), 'truthy': bag.filter(None).count()})
    ({'total': 100, 'truthy': 75},)
    """    
    flattened_args = _flatten_compute(list(args))
    results = compute(*flattened_args, **kwargs)
    return _rebuild_compute(results)
```
Thoughts?  Should I take the effort to make a PR to add this to `dask`?

**Comment by jcrist** [comment]
This already exists as `dask.delayed.compute`. I'm not sure if I think this should replace `dask.compute` though - there's some benefit to cheaply passing through non-dask objects (which is no longer cheap in `dask.delayed.compute`).

**Comment by eriknw** [comment]
Oh, I had no idea that existed!  Thanks.  It's also a much cleaner implementation.  `dask.delayed` ftw!

**Comment by jcrist** [comment]
It appears that it's only referenced in the `dask.delayed` api docs (http://dask.pydata.org/en/latest/delayed-api.html#dask.delayed.compute), so it may be non-obvious. Thoughts (or PR:) ). on how to improve the docs (if needed)?

**Comment by eriknw** [comment]
Personally, I wouldn't mind of `dask.compute` was replaced by `dask.delayed.compute`.

**Comment by jcrist** [comment]
I'm not 100% against it. My one issues is that currently `compute` passes through non-dask objects very cheaply (just an `isinstance` check). Switching to `dask.delayed.compute` results in a more expensive crawl of the objects beforehand if the object is one of the builtin collections (tuple, dict, set, list). This may not be a big deal though - in practice I only know of `dask-glm` that might call `compute` on non-dask objects.

I also see that `dask.delayed.compute` converts all arguments to `delayed` - really it should only do that for things that are not subclasses of `Base`. This should be fixed regardless of the decision above.

**Comment by eriknw** [comment]
Rather than having two similar functions (and one very hidden to the average user), I think it's preferable to have a keyword argument control behavior, such as `recurse=True`.
