### ISSUE TITLE
multiple keys to bag.pluck

### ISSUE THREAD

**Issue by mattilyra** [dask/dask#1971]
At the moment `bag.pluck` takes only a single key and (optionally) its default value. Would it possible to extend the API so that it takes a list of keys and (optionally) a dict of default values for each. At the moment I'm doing `bag.map(lambda d: {k: d[k] for k in d.keys & {'key1','key2'}})` to select a subset of fields, this is however quite cumbersome as I need to maintain the `dict` structure etc. It would however be much cleaner syntax wise to be able to do `bag.pluck('key1', 'key2')`. I've been using `spark` data frames and the desire to do so comes from there.

**Comment by jcrist** [comment]
This is currently supported, but not with different defaults per key. It also will return tuples instead of dictionaries. To do that you'd need to map a custom function:

```python
In [1]: import dask.bag as db

In [2]: data = [{'a': 1, 'b': 2, 'c': 3},
   ...:         {'a': 4, 'b': 5},
   ...:         {'a': 6, 'c': 7}]

In [3]: b = db.from_sequence(data)

In [4]: b.pluck(['b', 'c'], default=None).compute()  # Extract 'b' and 'c', using default of None
Out[4]: [(2, 3), (5, None), (None, 7)]

In [5]: def get(x, elements=None):
   ...:     """Extract keys in ``elements``, subbing in defaults if missing"""
   ...:     return {k: x.get(k, v) for k, v in elements.items()}
   ...:

In [6]: b.map(get, elements={'b': 200, 'c': 300}).compute()
Out[6]: [{'b': 2, 'c': 3}, {'b': 5, 'c': 300}, {'b': 200, 'c': 7}]
```

**Comment by mattilyra** [comment]
That's weird, I could've sworn I had tried that. I also just noticed that `pluck` with a  single key doesn't maintain the `dict`.

sorry for the non issue issue.
