### ISSUE TITLE
Slow access to s3 files with bag with read_text

### ISSUE THREAD

**Issue by rothnic** [dask/dask#1974]
I am working with a lot of small (300kB) bz2 compressed csv files on s3. Due to our bucket organization, the globbing is super slow, so I decided to pull the list of files manually, then try reading them via dask bag.

When just choosing a single file in my list, which was retrieved with s3fs, to start simple:

``` python
b = db.read_text('s3://' + all_files[0], blocksize=None)
b.take(5)
```

I wait a few minutes before killing the cell I'm running in ipython notebook. See [gist](https://gist.github.com/rothnic/2bea681d8413b2728123f90f5331e9d6) of output when I kill the task.

I then decided to take a look at it manually with s3fs with:

``` python
with fs.open(all_files[0], 'rb') as f:
    fd = bz2.BZ2File(f)
    print(fd.readlines()[0:5])
```

This statement returns in ~1.2s with the text output I'm expecting.

I then read in the documentation that you can pass in the s3 files directly to the dask dataframe read_csv. I wasn't sure that the files were csv beforehand, so didn't begin there. I ran the following:

``` python
ddf = dd.read_csv('s3://' + all_files[0], compression='bz2', blocksize=None)
ddf.head()
```

This statement returned in ~1.3s, and worked perfectly.

See [gist](https://gist.github.com/rothnic/2bea681d8413b2728123f90f5331e9d6) for the conda environment configuration.

**Comment by mrocklin** [comment]
@martindurant if you have a moment can you look at this?

**Comment by martindurant** [comment]
I notice that this is happening within multiprocessing - which is typical for `bag`, and typically includes some extra fuse internally. The stack trace suggests waiting on a lock, which is not too informative (there are no explicit locks in s3fs, and any internal locks within botocore should always be free in each process). 
For the record, I just tried the same and found no problem with three small files or just one of them.

**Comment by jcrist** [comment]
@martindurant was this ever resolved? Looks like this is an issue with s3fs and multiprocessing, rather than dask itself?

**Comment by martindurant** [comment]
The issue was not reproduced. More recent stuff on being careful about connections might have solved whatever the original problem was.

**Comment by jcrist** [comment]
Ok. @rothnic have you experienced this issue recently/do you have a reproducible example for it? Otherwise I plan to close soon.

**Comment by rothnic** [comment]
@jcrist: I'll take a look in the next couple of days. One thing that might be causing the issue is the structure of the bucket I was working with. I can't remember which exact files I was using because 300MB would be more in line with what I've used in the past, but not sure if that would affect listing the files.

**Comment by rothnic** [comment]
@jcrist I updated both dask (14.3) and s3fs (0.9) to their latest versions on conda and I no longer experience this issue with the same data I was using before. Closing

**Comment by jcrist** [comment]
Glad to here your issue was fixed! Thanks for letting us know.

**Comment by colinhiggins** [comment]
@martindurant, @jcrist I'm experiencing this issue currently, though in my case I'm using .gz compressed nested JSON instead of bz2 compressed CSV.

dask 1.4.3, s3fs 0.1.0

Worth re-opening? Let me know what other information you'd like me to gather to help track it down.

**Comment by martindurant** [comment]
It would be interesting to see if this is still specifically a multiprocessing problem, can you try with the distributed scheduler?

Note that .gz and .bz2 files are not splittable, so you will never get parallel processing - a good option, if you have the space, is to download and decompress, and then process the result in parallel.
