### ISSUE TITLE
Initializing special code on worker

### ISSUE THREAD

**Issue by varunmittal91** [dask/dask#1977]
My application requires complex initialization process.

But using dask-worker, I can hardly do that. Is there a way to work around this?

**Comment by mrocklin** [comment]
You may find [Client.run](http://distributed.readthedocs.io/en/latest/api.html#distributed.client.Client.run) useful.  Also the `distributed.worker_client.get_worker` function if you need access to the worker object itself.

```python
def setup():
    worker = get_worker()
    # do arbitrary setup code

client.run(setup)
```

**Comment by mrocklin** [comment]
Also related to https://github.com/dask/distributed/pull/505

**Comment by varunmittal91** [comment]
Thank you so much for the references.

I just have one more quick question that how does the scheduler respond if say I have 4 threads running and one of the thread is waiting for 10 dependent jobs waiting on Future.result.

Does it result in a deadlock, if not how is it resolved, with some getting failed and getting retried again. 

My application in is graph traversal.

**Comment by mrocklin** [comment]
Hi Varun,

I'm not sure I fully understand your situation.  The scheduler wait to
assign a task to a worker until all tasks on which that task depends are
finished and in-memory.  At that point it selects a worker (depending on
data movement, occupancy, etc.) and sends the task to that worker.  That
worker then runs that task in a first-in-first-out manner.

-matt

**Comment by mrocklin** [comment]
Closing.  Please reopen if problem persists.
