### ISSUE TITLE
Create docpage about reading bytes from remote data services

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1981]
Due to work by @martindurant Dask currently supports local file systems, HDFS, S3, Azure, and eventually GCS with a uniform interface.  http://martindurant.github.io/blog/python-and-big-data-storage/

It would be useful to have a companion docpage to http://dask.pydata.org/en/latest/bytes.html that describes how users can use data in these various systems.  What libraries do they need to install, what prefixes should they use, how to specify credentials, what special cases arise in each system, etc..

**Comment by mrocklin** [comment]
It would be particularly useful to mention things like using `storage_options=` to specify credentials, and where one can go to to find the right options for these.  This has come up a couple times today.

cc @martindurant if you have time, this would be good to prioritize.

**Comment by martindurant** [comment]
Going to the top of my list.

**Comment by mrocklin** [comment]
Thanks @martindurant !

**Comment by martindurant** [comment]
Writing this raises the question of whether there should be a DaskADLFileSystem and ALDMap somewhere, and whether there is a reasonable way to avoid copying code between the projects. Perhaps this is not the place to talk about that...

**Comment by mrocklin** [comment]
I seem to recall that this was done.  @martindurant can you verify?

**Comment by martindurant** [comment]
You mean this? http://dask.pydata.org/en/latest/remote-data-services.html?highlight=bytes

**Comment by jcrist** [comment]
Fixed in #1997. Closing.
