### ISSUE TITLE
Question: Can DaskDataFrame be passed to a delayed function? 

### ISSUE THREAD

**Issue by kaloramik** [dask/dask#1984]
Hi,

I ran into an issue a few versions back where I tried to pass a dask dataframe into a delayed function as follows 

```python

client = Client('127.0.0.1:8786')
@delayed
def process_df(df):
    return ...

ddf = dd.from_pandas(...)

future = process_df(ddf)

res = client.compute(future)
```

It seems to be working now with simple cases, but I was wondering if this is allowed in general? Or is it required to use the .to_delayed function in dask dataframe? It doesn't seem clear from the docs.

**Comment by mrocklin** [comment]
If you pass a dask dataframe to a delayed function it will arrive as a pandas dataframe.  If you are trying to parallelize one function across a dask.dataframe then you might try map_blocks.

**Comment by kaloramik** [comment]
got it, thanks!
