### ISSUE TITLE
Numpy 'all' operator realises dask arrays

### ISSUE THREAD

**Issue by pp-mo** [dask/dask#1988]
While passing dask objects in place of numpy arrays, I stumbled on some behaviour that surprised me greatly ...

If you say something like ```np.all(a1 == a2)``` when some array is a dask array, then it appears to silently and automatically  ***compute*** the array + delivers the "correct" result :--
```
>>> da_zeros = da.from_array(np.zeros(2), chunks=100)
>>> da_ones = da.from_array(np.ones(2), chunks=100)
>>> da_mixed = da.from_array(np.arange(2), chunks=100)
>>> np.all(da_zeros == 0)
True
>>> np.all(da_zeros == 1)
False
>>> np.all(da_ones == 1)
True
>>> np.all(da_ones == 0)
False
>>> np.all(da_mixed == 0)
False
>>> np.any(da_mixed == 0)
True
>>> 
```
In this, I'd *expect* it to simply produce another dask object (which will then always test 'True').
In fact, that's what the superficially similar ```(a1 == a2).all()``` ***does*** do.

After some digging, it seems that maybe anything that uses ```bool``` leads to a 'hidden compute', which could be the root of this :
```
>>> bool(da_mixed[0])
False
>>> bool(da_mixed[1])
True
>>> 
```

What's truly unexpected, for me, is that *anything* effects a 'compute', other than your explicitly asking for it.

**Key questions:**
  * is this intended behaviour 
  * is it a good idea
  * does it need documenting somewhere

**Comment by pitrou** [comment]
I'm not sure how Dask could do otherwise. `np.all` is a Numpy function, not a Dask function, and Dask cannot ask it to return a delayed result instead.

As for `bool`, it is a common expectation that `bool` really returns a boolean, on any kind of object. If not possible, it should raise an error (such as Numpy does when an array has more than 1 element). Returning a delayed result on `bool` would probably be actively harmful.

**Comment by mrocklin** [comment]
Regardless of whether or not it's harmful, it's not allowed:

```python
In [1]: class MyObj(object):
   ...:     def __bool__(self):
   ...:         return 'hello'
   ...:     

In [2]: bool(MyObj())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4b6be1b8a79b> in <module>()
----> 1 bool(MyObj())

TypeError: __bool__ should return bool, returned str
```

**Comment by pitrou** [comment]
Ah, yes, it seems Python took active steps to enforce the right behaviour :-)

**Comment by mrocklin** [comment]
Yeah, so @pp-mo in regards to np.any/all I think that generally we agree with your assessment, that it would be nice to return a delayed thing.  Unfortunately NumPy is in control here; there isn't much we an do other than to tell people that they should use `da` functions like `da.any` and `da.all` over `np` functions.  This is true generally, any numpy function like `np.sum` or `np.tensordot` will also produce a numpy array.  There are loose plans within NumPy to let the object make these decisions in the future.

**Comment by pp-mo** [comment]
Thanks for great responses @mrocklin @pitrou 

I think the key point here is, I simply didn't think that using numpy operators on dask objects was generally so unwise.  
Apologies for illogical thinking there :  I never really thought about how it works, and I suppose I vaguely thought that these operations would be type aware "somehow".  
I think it is a bit like that with masked array operations in numpy, where some methods are automatically mask/nonmask selective (and others are not).

I think the key problem of understanding is :  when you can write the "same" code for dask as normal arrays, and when not.  I have simply been a bit confused about this !

**Comment by mrocklin** [comment]
Some libraries use tricks like this:
https://github.com/dask/dask-glm/blob/master/dask_glm/utils.py

**Comment by jcrist** [comment]
Closing this for now as I believe the issue (a question) has been resolved. Feel free to reopen if there is still something left to do here.
