### ISSUE TITLE
Better explain how to perform partition-sensitive operations

### ISSUE THREAD

**Issue by Juanlu001** [dask/dask#1995]
In #1458 better error messages were added for attempts to resample a dataframe with unknown divisions. Reading the tests, it appears that I have to use `compute_divisions` first, but this function is not documented so I'm probably not meant to use it:

http://dask.pydata.org/en/latest/search.html?q=compute_divisions&check_keywords=yes&area=default

In fact, I get an error:

```
>>> df3 = compute_divisions(df)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-97-fb7d1d81cc4c> in <module>()
----> 1 df3 = compute_divisions(df)
      2 df3

/home/jlcano/.miniconda3/envs/b2c36/lib/python3.6/site-packages/dask/dataframe/core.py in compute_divisions(df, **kwargs)
   3572             any(a > b for a, b in zip(mins, maxes))):
   3573         raise ValueError("Partitions must be sorted ascending with the index",
-> 3574                          mins, maxes)
   3575 
   3576     divisions = tuple(mins) + (list(maxes)[-1],)

ValueError: ('Partitions must be sorted ascending with the index', 0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
dtype: int64, 0     410909
1     410850
2     410879
3     410897
4     410796
5     410727
6     410812
7     410842
8     410811
9     410915
10    410778
11    410876
12    410735
13    410934
14    410789
15    410805
16    410827
17    410855
18    410962
19    410831
20    410916
21    410887
22    410843
23    410852
24    410824
25    410876
26    410896
27    410860
28    410842
29    410810
30    410899
31     12619
dtype: int64)
```

The section on DataFrame partitions http://dask.pydata.org/en/latest/dataframe-design.html#partitions mentions that we can cleanly partition a dataset using `df.set_index(...)`, but for me it's not clear how that affects the partitions. I'm sure I'm missing something obvious here but would it be possible to have more detailed documentation in this respect?

**Comment by Juanlu001** [comment]
After re-reading the blog post I was following, I notice I had skipped the very precise part were this is explained:

http://matthewrocklin.com/blog/work/2017/01/12/dask-dataframes#shuffles-and-time-series

Shame on me :) I leave this issue open in case the maintainers consider it useful to expand the official docs.

**Comment by mrocklin** [comment]
Sorry for the delay in response.  I'd be happy to improve docs but I'm not sure how.

> The section on DataFrame partitions http://dask.pydata.org/en/latest/dataframe-design.html#partitions mentions that we can cleanly partition a dataset using df.set_index(...), but for me it's not clear how that affects the partitions. I'm sure I'm missing something obvious here but would it be possible to have more detailed documentation in this respect?

I'm not sure how to make this more clear.  Suggestions welcome.

**Comment by jcrist** [comment]
I believe that our docs for `partitions` and `set_index` are improved (http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.set_index). Closing for now, feel free to reopen if there's still improvements to make.

**Comment by Juanlu001** [comment]
I agree, it's much clearer now :) Thanks all! :raised_hands:
