### ISSUE TITLE
array references

### ISSUE THREAD

**Issue by marqh** [dask/dask#1996]
Hello Dask Folks

this isn't really a blocking issue, so feel free to close once there's a thought or two shared; i'll try to make sure to close it once i've got my head into the detail.

I have an example programme which I'd like to understand, i;ve tried to see how the referencing is working and i can't quite see what is going on.
I have also tried to extend the pattern into more complicated scenarios and i can't reproduce the simplified behaviour (a sure sign i'm missing the point)

The question I have is how does the reference sharing in this programme work?  All the 'id' returns are different, but changing one name changes them all, so sharing is occurring

much obliged
mark

```
import numpy as np
import numpy.ma as ma
import dask.array as da

print('#'*44)

anarray = np.arange(11)

darray = da.from_array(anarray, 11)

marray = ma.masked_array(darray.compute())

print('checking dask.array references:')

print(darray.compute()[5])
print(id(anarray))
print(id(darray.compute()))
print(id(darray.compute()))
print(id(darray.compute()))


darray.compute()[5] = 11
print(darray.compute()[5])
print(id(darray.compute()))
print(anarray[5])

anarray[5] = 13
print(darray.compute()[5])
print(id(darray.compute()))

marray[5] = 17
print(darray.compute()[5])

```

returns

```
############################################
checking dask.array references:
5
140433456945632
140433421350512
140433421350592
140433421350672
11
140433421350432
11
13
140433421350592
17

```

**Comment by mrocklin** [comment]
Generally dask.array is not shy about making copies.  In your case you're probably getting different id numbers because of this behavior in numpy

```python
In [1]: import numpy as np

In [2]: x = np.arange(5)

In [3]: id(x)
Out[3]: 140188405371808

In [4]: id(x[:])
Out[4]: 140188405372368

In [5]: id(x[:])
Out[5]: 140188405373008
```

Also, I recommend not changing the underlying data of a dask.array.  We generally assume that underlying data is unchanging.

**Comment by mrocklin** [comment]
Closing.  Feel free to reopen if your question was not answered.

**Comment by marqh** [comment]
thanks @mrocklin that covered all that i needed for now
