### ISSUE TITLE
dask.dataframe.from_delayed() memory issue

### ISSUE THREAD

**Issue by TMsangohan** [dask/dask#1998]
When I try to construct a dask dataframe from a list of delayed objects, my memory usage blows up eventually crashing my kernel in jupyter:
```python
import dask.dataframe as dd
import pandas as pd
from dask import delayed

# loading data from a set of hdf files
ddall = dd.read_hdf('aintdatab1*.hdf','int')
# loading summary data from hdf file
filldf = pd.read_hdf('hi2016fillsummary.hdf','/fills')

# creating list of start and end times to filter data
filllist= sorted(list(set(filldf[(filldf['mode']=='INJPHYS')]['fill'])))
startlist = [filldf[filldf['mode']==str(fill)]['startTime'].values[0] for fill in filllist]
endlist = [filldf[filldf['mode']==str(fill)]['endTime'].values[0] for fill in filllist]
combinedlist = zip(startlist,endlist)

# function to filter
def select(ddf,start, stop):
    ddfout  = ddf[(ddf['t']>=start) & (ddf['t']<=stop)]
    return ddfout

dfs = [delayed(select)(ddall,c[0],c[1]) for c in combinedlist]
df = dd.from_delayed(dfs)
```
Memory issue occurs at last command. Am I missing something here.

**Comment by mrocklin** [comment]
dd.from_delayed expects a list of Delayed objects that point to pandas dataframes, not dask dataframes.  If you have dask dataframes then you can probably just use normal dask.dataframe operations.  There is no reason to use delayed here.  Perhaps you're looking to just use your select function normally and then use `dd.concat` at the end?

**Comment by TMsangohan** [comment]
Ah I see. I missed that only pandas dataframes are accepted.  You are right, `dd.concat` is a better approach here.
