### ISSUE TITLE
Bad performance with DataFrame.categorize() and multiprocessing scheduler

### ISSUE THREAD

**Issue by abast** [dask/dask#2008]
```
pdf = pd.DataFrame(dict(A = ['A', 'B'] * 1000000, B = ['A', 'B'] * 1000000, C = ['A', 'B'] * 1000000))
ddf = dd.from_pandas(pdf, npartitions = 1000)
%time ddf.categorize(get = c.get) # c = distributed.Client()
%time ddf.categorize(get = dask.multiprocessing.get)

>CPU times: user 12.9 s, sys: 1.39 s, total: 14.2 s
>Wall time: 13.7 s

>CPU times: user 1min 12s, sys: 30.3 s, total: 1min 43s
>Wall time: 1min 30s
```

The multiprocessing scheduler is extremely inefficient if used together with `categorize`. The more columns in `ddf`, the bigger is the speed difference between the distributed and the multiprocessing scheduler. The main origin of the inefficency seems to be a lot of (de)serialization, as can be seen in the following profiling results.

<details>

```
`%prun ddf.categorize(get = dask.multiprocessing.get)`

         166389141 function calls (146670102 primitive calls) in 147.347 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
19249399/3436   51.293    0.000  127.712    0.037 pickle.py:269(save)
66006/50577   20.850    0.000  121.844    0.002 pickle.py:614(_batch_appends)
 18304083   14.725    0.000   20.397    0.000 pickle.py:260(get)
 20217882   10.829    0.000   10.829    0.000 {method 'write' of 'cStringIO.StringO' objects}
 19135962    5.963    0.000    5.963    0.000 {chr}
 20350667    5.179    0.000    5.179    0.000 {method 'get' of 'dict' objects}
    68860    5.159    0.000    5.159    0.000 {method 'acquire' of 'thread.lock' objects}
 19249399    3.447    0.000    3.447    0.000 pickle.py:333(persistent_id)
       24    3.128    0.130    3.128    0.130 {posix.fork}
 20705890    2.854    0.000    2.854    0.000 {id}
 18769284    2.439    0.000    2.439    0.000 {method 'append' of 'list' objects}
   619156    1.949    0.000    3.465    0.000 pickle.py:227(memoize)
    48024    1.579    0.000    1.742    0.000 core.py:159(get_dependencies)
    27575    1.519    0.000    2.594    0.000 ioloop.py:932(add_callback)
237030/3435    1.225    0.000  127.691    0.037 pickle.py:538(save_tuple)
    97725    0.936    0.000    1.910    0.000 {method '__reduce_ex__' of 'object' objects}
```
</details>

I wrote a custom categorize method that 

 1. converts the dataframe to delayed objects 
 2. calculates the categories using pandas for each delayed object
 3. concatenates the result.

This is much more efficient with the multiprocessing scheduler but a bit slower on the distributed scheduler. This type of fallback strategy generally seems to be a good option if the multiprocessing scheduler is slow. So what kind of optimizations does dask use internally that are well suited for the distributed scheduler but too challenging for the multiprocessing scheduler?

**Comment by jcrist** [comment]
Thanks for the bug report, this should be fixed in #2010. In general, the distributed scheduler can be a lot smarter than the multiprocessing scheduler in terms of making use of data locality (avoiding serialization) and fully utilizing all cores. Since you can start up a local cluster in process (just call `Client()`), I recommend using the distributed scheduler over the multiprocessing most cases.

**Comment by abast** [comment]
Thanks for the fast reply. Do you have any insights what might have been the cause for this inefficiency with the multiprocessing scheduler? I am not asking for technical details but rather for some advice how (not) to construct a workload for the multiprocessing scheduler. 

You say, distributed can be a lot smarter than  multiprocessing, e.g. when it comes to data locality. I thought data locality means that the data is on the same machine where it is processed. If we compare a distributed cluster with e.g. 10 processes and 1 thread for each process that is set up on the one machine to 10 workers of the multiprocessing schedulers - shouldn't be this the same in terms of communication overhead between the workers? How can the distributed scheduler avoid serialization in this scenario? How can it be smarter?

Personally I'd expected communication over tcp to introduce much more overhead than e.g. pipes between processes. Is this not the case? Or is distributed using smarter serialization methods than pickle which compensates for the additional offset that comes with using a high level network protocol?

Are there cases where you would explicitly recommend to use multiprocessing over distributed? The reason why I've been using multiprocessing was mainly, because it does not require to "set anything up". E.g. when I call `Client()` in a jupyter notebook but interrupt the kernel, I was sometimes required to call `Client()` again while I could immediately start the computation if I used the multiprocessing scheduler.

Sorry for all these questions, but I've been confused about this topic for quite a while now.

**Comment by mrocklin** [comment]
See http://dask.pydata.org/en/latest/scheduler-choice.html

**Comment by abast** [comment]
Thanks, I've visited that page several times but did not expect to find the in-depth comparison between distributed and multiprocessing in the paragraph "Distributed Scheduler on a Single Machine --> Data Locality". What about putting a small link to this section in the bullet points at the top of the page? Or maybe changing the title of this section to something like "multiprocessing vs distributed scheduler"?

**Comment by mrocklin** [comment]
I think that changing the title would ignore the information here about threaded and synchronous schedulers, which I actually view as *more* important here (threads vs processes is a more common question/concern among single machine users).  I agree that a tasteful link somewhere up in the distributed prose could be useful.
