### ISSUE TITLE
Default to fuse_linear if ave_width=1?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2012]
If `fuse_ave_width==1`, is it advantageous to use the `fuse_linear` algorithm instead?

cc @eriknw

**Comment by mrocklin** [comment]
I guess this is a question of two parts:

1.  What is the performance difference between the two functions if ave_width == 1
2.  Does fuse operate differently than fuse_linear if ave_width == 1

**Comment by eriknw** [comment]
1) In my limited benchmarks, `fuse` with ave_width == 1 can be up to 20%-ish slower than `fuse_linear` for large graphs.  More testing and benchmarks welcome.

2) Yes, `fuse` behaves differently.  It can fuse linear tasks that may reference the dependents of the first fused task.  For example,
![graph3](https://cloud.githubusercontent.com/assets/2058401/23332628/83c0bac6-fb42-11e6-9123-747061c47c9d.png)

is fused into this:
![graph4](https://cloud.githubusercontent.com/assets/2058401/23332629/8b107de8-fb42-11e6-804f-c34f8ad01c6d.png)

The only other difference is default key renaming.  `fuse` puts the prefixes in a set and sorts them, whereas `fuse_linear` creates a linear chain of the all prefixes in the order they were fused.  We could change the default renamer for `fuse` if ave_width == 1 if desired.
