### ISSUE TITLE
Buffer error while saving and loading Parquet Data

### ISSUE THREAD

**Issue by r-shekhar** [dask/dask#2024]
I've encountered an error while saving and loading some NYC taxi data in parquet format using to_parquet and read_parquet in dask. 

Here is a minimal example. It fails at the call to read_parquet. 

```python
#!/usr/bin/env python

import dask.dataframe as dd
from distributed import Client

def main(client):

    # This is a cleaned up version of the NYC green taxi dataset. 
    # I don't think it's relevant, but if you think it might be, you 
    # can see my script to clean the data here: https://git.io/vymsL
    # I encounter these same problems with the yellow taxi dataset

    # Load hdf files produced by the dask to_hdf function 
    df = dd.read_hdf('/data1/hdf/green/green-*.hdf', '/data')


    df.to_parquet('/data1/green.parquet', compression="SNAPPY", 
        has_nulls=True,
        object_encoding='json' #have tried multiple options here
        )

    df2 = dd.read_parquet('/data1/green.parquet')
    print(df2.head())
    print(df2.tail())


if __name__ == '__main__':
    client = Client()
    main(client)
```

I'm currently uploading the input hdf files [to my dropbox storage](https://www.dropbox.com/sh/vxjprcc5nqgky1v/AADSOXWKxsmiFMTs1TtKbKhUa?dl=0), it should be done in a couple of hours. There are 25 files total, and the error does not occur when only the first file is loaded using pandas, saved using fastparquet, and loaded again using fastparquet. 

This is the stacktrace when the above code is run
```
shekhar@rs:%> python dask_error.py
Traceback (most recent call last):
  File "dask_error.py", line 31, in <module>
    main(client)
  File "dask_error.py", line 22, in main
    df2 = dd.read_parquet('/data1/green.parquet')
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 85, in read_parquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 508, in sorted_partitioned_columns
    s = statistics(pf)
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 470, in statistics
    L = list(map(statistics, obj.row_groups))
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 467, in statistics
    for c in obj.columns}
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 467, in <dictcomp>
    for c in obj.columns}
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 456, in statistics
    rv['max'] = encoding.read_plain(ensure_bytes(s.max), md.type, 1)[0]
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/encoding.py", line 38, in read_plain
    return np.frombuffer(byte_buffer(raw_bytes), dtype=dtype, count=count)
ValueError: buffer is smaller than requested size
Received signal 15, shutting down
```

These are the versions of packages I'm using. I'm not sure if it's relevant.

```
dask                      0.14.0                   py35_0    conda-forge
distributed               1.16.0                   py35_0    conda-forge
fastparquet               0.0.5                    py35_0    conda-forge
numba                     0.31.0              np111py35_0
numpy                     1.11.1                   py35_0
pytables                  3.3.0               np111py35_0    conda-forge
python                    3.5.2                         0
python-snappy             0.5                      py35_0    conda-forge
snappy                    1.1.4                         1    conda-forge
```

**Comment by mrocklin** [comment]
cc @martindurant, who might be able to shed light on the parquet issues.

@r-shekhar FWIW I personally tend not to download data to reproduce errors.  Typically we ask users to try to reduce down the problem to a small example that is easily reproducible.  See [StackOverflow guidelines on MCVEs](http://stackoverflow.com/help/mcve)

**Comment by martindurant** [comment]
It appears to be happening in the stats calculation, with you don't access using to_pandas() - you could look at the `fastparquet.ParquetFile().statistics` to see where it breaks, and run debug to find out the column that is being accessed when that happens.

**Comment by r-shekhar** [comment]
@martindurant Thanks, I'll take a look as soon as I get a chance

**Comment by mrocklin** [comment]
You could also try running with the dask single-threaded scheduler and use
a normal debugger like pdb

with dask.set_options(get=dask.async.get):
    ... call to_parquet in here ...

**Comment by r-shekhar** [comment]
So I spent a bit of time tracking it down. I can point you to a general location, but I'm afraid I don't have the time to determine exactly where the issue is coming from.

The problem arises when the data in the green-10.hdf file, only if fastparquet.write(append=True) is used to append that dataframe to another dataframe already written out to disk.

```python

import pandas as pd
from glob import glob
import fastparquet

fileslist_green = ['/data1/hdf/green/green-09.hdf', 
                   '/data1/hdf/green/green-10.hdf']

output_filename = '/data1/hdf/green/allgreen.parquet'

for i, f in enumerate(fileslist_green):
    print( (i, f))
    df = pd.read_hdf(f)
    if i==0:
        fastparquet.write(output_filename, df, file_scheme='hive',
            compression="SNAPPY")
    else:
        fastparquet.write(output_filename, df, file_scheme='hive',
            compression="SNAPPY", append=True)


    df2 = fastparquet.ParquetFile(output_filename).statistics
    # print(df2.head())
    print(df2)
```

I dug into fastparquet/api.py, and edited these lines to add print statements. 
```python
    if isinstance(obj, parquet_thrift.ColumnChunk):
        md = obj.meta_data
        print(md)
        s = obj.meta_data.statistics
        print(s)
        rv = {}
        if not s:
            return rv
        if s.max is not None:
            print(s.max)
            rv['max'] = encoding.read_plain(ensure_bytes(s.max), md.type, 1)[0]
```

My output when running the program looks like this. I'm not sure how a three byte value is stored in a four byte float spot for 'max'. I also didn't really see anything anomalous when inspecting the data manually. 

```
@E
<class 'parquet_thrift.ColumnMetaData'>
codec: 1
data_page_offset: 48368642
dictionary_page_offset: None
encoding_stats: [<class 'parquet_thrift.PageEncodingStats'>
count: 1
encoding: 0
page_type: 0
]
encodings: [3, 4, 0]
index_page_offset: None
key_value_metadata: []
num_values: 2366377
path_in_schema: ['improvement_surcharge']
statistics: <class 'parquet_thrift.Statistics'>
  distinct_count: None
  max: b'\x9a\x99\x99>'
  min:
  null_count: 0

total_compressed_size: 657243
total_uncompressed_size: 9465533
type: 5

<class 'parquet_thrift.Statistics'>
distinct_count: None
max: b'\x9a\x99\x99>'
min:
null_count: 0

b'\x9a\x99\x99>'
Traceback (most recent call last):
  File "simple.py", line 24, in <module>
    df2 = fastparquet.ParquetFile(output_filename).statistics
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 105, in statistics
    return statistics(self)
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 473, in statistics
    L = list(map(statistics, obj.row_groups))
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 470, in statistics
    for c in obj.columns}
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 470, in <dictcomp>
    for c in obj.columns}
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/api.py", line 459, in statistics
    rv['max'] = encoding.read_plain(ensure_bytes(s.max), md.type, 1)[0]
  File "/home/shekhar/anaconda3/lib/python3.5/site-packages/fastparquet/encoding.py", line 38, in read_plain
    return np.frombuffer(byte_buffer(raw_bytes), dtype=dtype, count=count)
ValueError: buffer is smaller than requested size
```

So this seems like a fastparquet problem, not a dask problem. I'm afraid I don't have time to spend debugging this farther. Cheers.

**Comment by mrocklin** [comment]
> I'm afraid I don't have time to spend debugging this farther. Cheers.

That's unfortunate.  To be clear, the *most helpful thing* here is to produce a simple example that can reproduce the problem.  Devs can usually track things down pretty quickly once they have this.

**Comment by martindurant** [comment]
I have the source of your problem: in green-09, column improvement_surcharge is float32, but in green-10 it is float64. The docstring for append=True says that the schema must match. Inserting `df['improvement_surcharge'] = df.improvement_surcharge.astype('float64')` into your code above fixes this. 
Reading with dask gives dtype float64 for that column, so I'm not quite sure how the error propagates from that side.

**Comment by mrocklin** [comment]
What do errors look like in fastparquet if someone has inconsistent schemas like this?  Can we improve these?

**Comment by r-shekhar** [comment]
Ah I see. That's very helpful. I used `dd.from_csv` to produce the dataframes saved as hdf files. Pandas or dask must have chosen different types within different csv files it parsed. I'll make sure to specify dtypes manually in the future.  Thank you.
