### ISSUE TITLE
Extending concatenate to nested sequences

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2028]
It would be nice if `concatenate` were extended to nested lists. For instance, given a structure like the one below it would be nice to concatenate the inner lists on their last dimension and then concatenating those partial results on their first dimension to get one bigger dask array.

```python
s = [[a00, a01],
     [a10, a11]]
```

**Comment by mrocklin** [comment]
Does NumPy do this?  If not then is there an operation in NumPy that *does *do
this?

**Comment by jakirkham** [comment]
For `concatenate`, no. I suppose a different name could be chosen. What would you suggest?

From a cursor glance, not quite. They do allow nested `list`s as arguments to `array`, `stack`, and `concatenate`. Though all of them seem to do something slightly different.

That said, one might be able to leverage `array` or `stack` to work towards something with this behavior. Though it will need some transposing and reshaping to get it right.

**Comment by jakirkham** [comment]
Here's an example of how one might accomplish this with `stack` for one case.

```python
In [1]: import numpy

In [2]: a = numpy.array([[0, 1, 2],
   ...:                  [3, 4, 5]])

In [3]: numpy.stack([[a, a], [a, a]]).transpose(0,2,1,3).reshape(4,6)
Out[3]:
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])
```

**Comment by mrocklin** [comment]
I think in Dask.array (and possibly numpy) you'd be better off using a
bunch of stack and concatenate calls.

We had to implement the numpy version of this internally.  I think it'd be
great for NumPy to implement such a thing.  I think that that conversation
should happen first at NumPy and then Dask.array would follow.

**Comment by jakirkham** [comment]
Perhaps. Though I doubt I'll have time that can be volunteered towards that effort.

That said, I think we could at least get `stack`, `array` and possibly `concatenate` to at least behave like NumPy does in Dask. That should at least make it easier for people (myself included) to approach problems like this one.

**Comment by mrocklin** [comment]
In what way to stack and concatenate not yet behave like NumPy?  What is
missing?

**Comment by jakirkham** [comment]
Looked at this again and it really doesn't feel like `concatenate` or `stack` get the job done. They start doing strange things when arrays with different shapes are considered. Though maybe `block` whenever it gets added will. ( https://github.com/numpy/numpy/pull/7768 )

**Comment by jakirkham** [comment]
> We had to implement the numpy version of this internally. I think it'd be great for NumPy to implement such a thing. I think that that conversation should happen first at NumPy and then Dask.array would follow.

To be clear, this is what is happening at PR ( https://github.com/numpy/numpy/pull/8886 ) FWICT. So if you have particular feelings about how this should work, would encourage you to weigh in.

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/dask/dask/issues/2350 ) about adding `block` (a new NumPy function) to Dask, which should solve the problem laid out here.
