### ISSUE TITLE
`dask.array.Array.to_delayed()` inconsistent behavior for arrays with scalars?

### ISSUE THREAD

**Issue by magonser** [dask/dask#2029]
```python
import numpy as np
import dask.array as da
v = da.from_array(np.array([1, 2, 3]), chunks=2)
v.to_delayed()[0].compute()
>>> array([1, 2])
```

```python
v = da.from_array(np.array(0), chunks=2)
v.to_delayed()[tuple()].compute()
>>> (array(0),)
```

Shouldn't the second outcome be `array(0)` ?

**Comment by mrocklin** [comment]
What is your intent behind chunks=2 ?

**Comment by magonser** [comment]
Oh ... it is arbitrary. I am assuming it won't change anything about this behavior. Haven't tried it yet though.

**Comment by magonser** [comment]
I have tried it, changing `chunks` doesn't affect the behavior. Could you comment, what your expected/planned behavior on this issue was?

**Comment by magonser** [comment]
After some code digging I understand, that the problem comes from the implementation of `dask.utils.ndeepmap`: 

    def ndeepmap(n, func, seq):
        """ Call a function on every element within a nested container

        >>> def inc(x):
        ...     return x + 1
        >>> L = [[1, 2], [3, 4, 5]]
        >>> ndeepmap(2, inc, L)
        [[2, 3], [4, 5, 6]]
        """
        if n == 1:
            return [func(item) for item in seq]
        elif n > 1:
            return [ndeepmap(n - 1, func, item) for item in seq]
        else:
            return func(seq)


For the scalar example

    x = da.from_array(np.array(0), name='x', chunks=2).to_delayed()

the call of ndeepmap inside `to_delayed` is 

    ndeepmap(x.ndim, lambda k: Delayed(k, x.dask), x._keys())

For the scalar array `x._keys()`` will be a list of keys, hence the call on 
`ndeepmap` is with the arguments `n=0`, `func=lambda k: Delayed(k, x.dask)` and 
`seq=[('x', )]`. Clearly the `else` statemement gets executed and the whole `seq` 
passed to `func`. Changing last line of implementation to `return func(seq[0])` 
solves the issue for the scalar example, but introduces problems (i.e. many tests in 
`dask/array/tests/test_array_core.py` fail).

Having a look at `dask/tests/test_utils.py`

    def test_ndeepmap():
        L = [1, 2, 3]
        assert ndeepmap(1, inc, L) == [2, 3, 4]

        L = [[1, 2], [3, 4]]
        assert ndeepmap(2, inc, L) == [[2, 3], [4, 5]]

        L = [[[1, 2], [3, 4, 5]], [[6], []]]
        assert ndeepmap(3, inc, L) == [[[2, 3], [4, 5, 6]], [[7], []]]

does not reveal the corner cases. 

I would appreciate some comments on how the corner cases of `ndeepmap` are to be 
understood. Or any suggestions on how to make it consistent.

**Comment by mrocklin** [comment]
What is a corner case that fails?

**Comment by mrocklin** [comment]
I suspect that sometimes when n==0, seq isn't a list, but is in fact an element

**Comment by magonser** [comment]
Yes, currently only `n==0` with `L` not being a seq works (and is required in other parts of dask). For the scalar case (as for which this Issue is for) it should also work for `n==0` with `L` being a list.

**Comment by mrocklin** [comment]
Perhaps this could be fixed by a quick check:

```python
if isinstance(L, list):
    L = L[0]
```
