### ISSUE TITLE
Using multiprocessing scheduler with a repartitioned dataframe is slow

### ISSUE THREAD

**Issue by abast** [dask/dask#2033]
```
import distributed
c = distributed.Client()

pdf = pd.DataFrame(dict(A = ['A', 'B'] * 1000000, B = ['A', 'B'] * 1000000, C = ['A', 'B'] * 1000000))
ddf = dd.from_pandas(pdf, npartitions = 1000)
%ddf.repartition(npartitions = 10).compute(get = dask.multiprocessing.get)
%ddf.compute(get = dask.multiprocessing.get)
%ddf.repartition(npartitions = 10).compute(get = c.get)
%ddf.compute(get = c.get)
```

```
CPU times: user 30.6 s, sys: 32.7 s, total: 1min 3s
Wall time: 44.4 s
CPU times: user 648 ms, sys: 3.25 s, total: 3.9 s
Wall time: 3.92 s
CPU times: user 2.76 s, sys: 604 ms, total: 3.36 s
Wall time: 4.23 s
CPU times: user 4.2 s, sys: 692 ms, total: 4.89 s
Wall time: 4.61 s
```

The multiprocessing scheduler seems to be an order of a magnitude slower than the distributed scheduler in case the dataframe is repartitioned. Could this be optimized?

**Comment by mrocklin** [comment]
Yeah, you should definitely avoid moving data down to processes and back up.  Given that this is an anti-pattern I'm not particularly motivated to improve it.  

I also don't think there is much we can do with the multiprocessing scheduler here.  Any improvement to the multiprocessing scheduler would just be recreating work in the distributed scheduler.

**Comment by abast** [comment]
If we move data only in one direction, the phenomenon of multiprocessing being an order of a magnitude slower still persists.

```
with dask.set_options(get = dask.multiprocessing.get):
    %time ddf.repartition(npartitions = 10).to_csv('/some/path/1')
with dask.set_options(get = c.get):
    %time ddf.repartition(npartitions = 10).to_csv('/some/path/2')
```

```
CPU times: user 21 s, sys: 21.2 s, total: 42.1 s
Wall time: 32.2 s
CPU times: user 2.06 s, sys: 320 ms, total: 2.38 s
Wall time: 3.41 s
```

**Comment by mrocklin** [comment]
You move the pandas dataframe to each process for every part of the repartition call (which happens ten times).  You should probably use `from_pandas(df, npartitions=10)`.  Or better yet, just use the distributed scheduler which will handle this more intelligently.

I guess my question is really "why isn't the solution to this issue just to use the distributed scheduler?"

**Comment by abast** [comment]
This was my attempt to provide a minimal example. In reality, I have many files, which should be concatenated to a smaller amount of files. This is one step of many. The distributed scheduler apparently does not provide an easy way to reliably determine the time point when all IO operations are finished as long as work stealing is activated (https://github.com/dask/distributed/issues/847).  So the idea was  to do the basic file processing stuff with multiprocessing, the actual analysis which benefits from work stealing with the distributed scheduler. 

Currently, I am using the distributed scheduler with deactivated work stealing, but this again creates a corner case with its own disadvantages. 

Since my example was probably to simplistic, here the more real case which should not involve any pandas dataframe in memory:
```
ddf = dd.read_csv('/path1/bla*.csv')  #1000 partitions from above
with dask.set_options(get = dask.multiprocessing.get):
    %time ddf.repartition(npartitions = 10).to_csv('/path2/bla*.csv')
```
```
CPU times: user 28.7 s, sys: 2.8 s, total: 31.5 s
Wall time: 32 s
```
The data flow looks linear to me - am I wrong? If not, why should multiprocessing not be adequate for the job?

**Comment by mrocklin** [comment]
Each task takes in the full dataframe as an input.  So you pay the
serialization cost 10 times.

**Comment by abast** [comment]
Okay, I guess my wrong assumption was that after re-partitioning it is possible to only send the respective "subdataframe" to each worker. Thanks for all your explanations. Closing.

**Comment by mrocklin** [comment]
For full generality choosing that subdataframe is itself a task.

**Comment by mrocklin** [comment]
More generally on this problem, I perceive the single-machine
multiprocessing scheduler as pretty stable.  I don't have any plans to
improve it nor do I see any ways in which it can be cheaply improved.  I
would focus efforts on the distributed scheduler.  I suspect that it is
less work to make that do what you want than to make the multiprocessing
scheduler do what you want.

**Comment by abast** [comment]
Yes, it all makes sense now. I basically had this misconception about what `repartition` does and could therefore not understand the performance problems. I've definitely learned something :)
