### ISSUE TITLE
ImportError: No module named distributed

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2036]
Hi,
I have installed the latest version of dask inside a docker image that I am maintaining. However, the import command for **dask.distributed**  fails while it works for **dask.dataframe.**

`
! pip install --upgrade dask
from dask import *
import dask.dataframe as dd 

from dask.distributed import Client, progress`

Has the package been moved? 

Many thanks, 

![dask-parquet-df](https://cloud.githubusercontent.com/assets/18743986/23579656/206304bc-00fa-11e7-85b7-8974f92596c3.jpg)

**Comment by martindurant** [comment]
`distributed` is a separate package from dask, and should also be [installed](http://distributed.readthedocs.io/en/latest/install.html) in addition. This is historical, and previously users would have done `import distributed` to the same effect.

**Comment by QuantScientist** [comment]
Great thanks, script updated here:
https://hub.docker.com/r/quantscientist/deep-ml-meetups/~/dockerfile/

**Comment by CarolinaPardoFuquen** [comment]
The only code that works for me is this:

`python -m pip install "dask[complete]"    # Install everything`

i found in this page:  https://docs.dask.org/en/latest/install.html
