### ISSUE TITLE
A Linux based dokcer image with all the required libraries

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2037]
Dear All,
I am building a docker image which includes python 2.7 , jupyter, dask, fastparquet, llvm and all the relevant dependencies. It is available here:
https://github.com/QuantScientist/deep-ml-meetups/blob/master/nice-docker/README.md
https://hub.docker.com/r/quantscientist/deep-ml-meetups/builds/

It is my hope that it would be useful to others, 
Let me know if you have any requests, parquet-cpp is on my next to do list :) 

![dask-parquet-df](https://cloud.githubusercontent.com/assets/18743986/23580071/309be58e-0103-11e7-8f97-c394aa1f519b.jpg)

**Comment by martindurant** [comment]
Note that I do not know how complicated building parquet-cpp is, but you might be interested in [fastparquet](https://fastparquet.readthedocs.io/), which does have python requirements (cython, numba, thrift), but conda-installs without issues.

**Comment by QuantScientist** [comment]
fastparquet is already installed on the docker image.

**Comment by martindurant** [comment]
ok ;)

**Comment by mrocklin** [comment]
Thanks for informing us @QuantScientist .  I'm going to close this down for now.  Please feel free to reopen if further conversation is warranted.
