### ISSUE TITLE
Progress keeps running forever

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2039]
Hi,
Must be doing something wrong.
I started the scheduler as follows: 
`dask-scheduler --host localhost &
dask-worker loaclhost:8786 $* &`

An then from python:

![dask-parquet-df_and_nice-docker_ _root_bdeedf7a5b18____ _docker_run_-it_-p_8888_8888_-p_6006_6006_-p_8786_8786_-p_8787_8787_-p_8788_8788_-v___volumes_1tb-ext_2019_db_stan_dropbox_dev2_books_2019_bml___root_sharedfolder_quantscientist_deep-m](https://cloud.githubusercontent.com/assets/18743986/23582535/0075eb48-0135-11e7-8aa4-a3d38ebeaffe.jpg)

Is this a problem with the ports? 
I tried this with the 'Client' instead of executor but its the same result.

**Comment by martindurant** [comment]
You seem to have a typo in your call to `dask-worker`.  "loaclhost" -> "localhost".

**Comment by QuantScientist** [comment]
Thanks.
