### ISSUE TITLE
distributed.scheduler - ERROR - error from worker Python int too large to convert to C long

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2041]
Hi,
I am reading CSV files in order to convert them into parquet, the numbers are around 10*E^22.

The error is:
```
Exception: OverflowError('Python int too large to convert to C long',)
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:46891: Python int too large to convert to C long

``` 

Does that mean I will not be able to use Dask for that? 
I tried Apache drill and it did not report any errors during the conversion process.

**Comment by mrocklin** [comment]
Hi Solomon, it would be really helpful here if you can provide a minimal
failing example that we can use to easily reproduce the issue.  Please see
http://stackoverflow.com/help/mcve for guidelines.
