### ISSUE TITLE
Add dask.dataframe.read_json

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2043]
I'm actually a little surprised that no one has asked for this yet...

We probably can't read proper non-line-delimited JSON (unless we read in entire files) but line delimited should be pretty easy.  The current `dask.bytes.read_bytes` and `pd.read_json` functions should get us  most of the way there.

**Comment by jcrist** [comment]
> I'm actually a little surprised that no one has asked for this yet...

#1236 :)

**Comment by mrocklin** [comment]
Ah ha, closing in favor
