### ISSUE TITLE
The equivalent of Pandas df.sort_index(by='TS')  and df.set_index('TS',inplace=True)

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2044]
# df = df.sort_index(by='TS')  
# df.set_index('TS',inplace=True)                
Is there such a notion in Dask? I need the data-frame to be indexed by Timestamp
Thanks,

**Comment by QuantScientist** [comment]
Answering myself:
`df=df.set_index('TS')                `

**Comment by mrocklin** [comment]
Great.  Thanks for self-answering.  Closing.
