### ISSUE TITLE
Exception: OverflowError('Overflow',)

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2045]
Hi,
Issues when reading CSV's. I know I have very large numbers inside the CSV' so this may be the issue.
**How to reproduce:** 

``
from dask.distributed import Client
from distributed import Executor, progress, wait
from dask.diagnostics import ProgressBar, Profiler, ResourceProfiler, visualize

d_client = Client('localhost:8786')
d_client

col_names=['ID', 'NE', 'Object', 'Granularity', 
           'Report Time', 'Monitor Seconds', 'Suspect Flag', 
           'Rx_Pkts_64', 'Rx_Pkts_65_127', 'Rx_Pkts_128_255', 
           'Rx_Pkts_256_511', 'Rx_Pkts_512_1023', 
           'Rx_Pkts_1024_1518', 'Rx_Pkts_1519_MTU', 
           'Rx_Undersize_Pkts', 'Rx_Oversize_Pkts', 
           'Rx_Fragments', 'Rx_Jabber_Pkts', 'Rx_Broadcast_Pkts', 
           'Rx_Multicast_Pkts', 'Rx_CRC_Align_Error_Pkts', 
           'Collision_Errors', 'Rx_Error_Pkts', 'Rx_Octets', 
           'Rx_Pkts', 'Tx_Octets', 'Tx_Pkts', 'PCS_LCV', 'PCS_ES', 
           'PCS_SES', 'PCS_UAS']
col_types={
'ID'                           :int,
'NE'                          :object,
'Object'                      :object,
'Granularity'                 :object,
'Report Time'                 :object,
'Monitor Seconds'              :int,
'Suspect Flag'                  :bool,
'Rx_Pkts_64'                   :int,
'Rx_Pkts_65_127'               :int,
'Rx_Pkts_128_255'              :int,
'Rx_Pkts_256_511'              :int,
'Rx_Pkts_512_1023'             :int,
'Rx_Pkts_1024_1518'            :int,
'Rx_Pkts_1519_MTU'             :int,
'Rx_Undersize_Pkts'            :int,
'Rx_Oversize_Pkts'             :int,
'Rx_Fragments'               :float,
'Rx_Jabber_Pkts'             :float,
'Rx_Broadcast_Pkts'            :int,
'Rx_Multicast_Pkts'            :int,
'Rx_CRC_Align_Error_Pkts'      :int,
'Collision_Errors'             :int,
'Rx_Error_Pkts'                :int,
'Rx_Octets'                    :int,
'Rx_Pkts'                      :int,
'Tx_Octets'                    :int,
'Tx_Pkts'                      :int,
'PCS_LCV'                    :float,
'PCS_ES'                     :float,
'PCS_SES'                    :float,
'PCS_UAS'                    :float
}

import dask.dataframe as dd
import numpy as np

CSV_FILES='DATA/'
df_orig = dd.read_csv(CSV_FILES+ '/zip_LARGE/11/1/*.csv', header=1, 
                 parse_dates=['Report Time'], names=col_names,dtype=col_types)
df_df_orig = d_client.persist(df_orig)
the background.
progress(df_orig)

[PortHisPerformanceInfo_10.zip](https://github.com/dask/dask/files/820393/PortHisPerformanceInfo_10.zip)

``

I attached a sample CSV file. 

[I 07:22:33.630 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:38924'
distributed.scheduler - INFO -   Scheduler at:      tcp://127.0.0.1:8786
distributed.scheduler - INFO -       bokeh at:            127.0.0.1:8788
distributed.scheduler - INFO -        http at:            127.0.0.1:9786
distributed.bokeh.application - INFO - Web UI: http://127.0.0.1:8787/status/
distributed.scheduler - INFO - -----------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:55012
distributed.worker - INFO -              bokeh at:            127.0.0.1:8789
distributed.worker - INFO -               http at:            127.0.0.1:49740
distributed.worker - INFO -              nanny at:            127.0.0.1:38924
distributed.worker - INFO - Waiting to connect to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         16
distributed.worker - INFO -                Memory:                   81.12 GB
distributed.worker - INFO -       Local Directory:          /tmp/nanny-SGXv9I
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register tcp://127.0.0.1:55012
distributed.worker - INFO -         Registered to:             tcp://localhost:8786
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55012
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Nanny 'tcp://127.0.0.1:38924' starts worker process 'tcp://127.0.0.1:55012'
[I 07:22:40.352 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 07:22:40.354 NotebookApp] Notebook sharedfolder/jupyter/ems/analyticsDataCSVToParquetUsingDask.ipynb is not trusted
[I 07:22:41.625 NotebookApp] Kernel started: 8afd5007-6f2b-47b8-bfa3-c2884ed0418d
[W 07:22:46.217 NotebookApp] 404 GET /api/kernels/703b2bfa-44a5-4867-8794-e5857585846f/channels?session_id=0CC649707E2242889A83EFB4044912EE (172.31.205.123): Kernel does not exist: 703b2bfa-44a5-4867-8794-e5857585846f
[W 07:22:46.224 NotebookApp] 404 GET /api/kernels/703b2bfa-44a5-4867-8794-e5857585846f/channels?session_id=0CC649707E2242889A83EFB4044912EE (172.31.205.123) 10.92ms referer=None
distributed.scheduler - INFO - Receive client connection: c0a637d4-023d-11e7-bee5-0242ac110002
distributed.core - WARNING - Lost connection to 'tcp://[::1]:58385' while sending result for op 'feed': error: [Errno 32] Broken pipe
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<built-in function apply>, <function pandas_read_text at 0x7fbdd455fcf8>, [<function read_csv at 0x7fbdb3b30f50>, 'ID,NE,Object,Granularity,Report Time,Monitor Seconds,Suspect Flag,Rx_Pkts_64,Rx_Pkts_65_127,Rx_Pkts_128_255,Rx_Pkts_256_511,Rx_Pkts_512_1023,Rx_Pkts_1024_1518,Rx_Pkts_1519_MTU,Rx_Undersize_Pkts,Rx_Oversize_Pkts,Rx_Fragments,Rx_Jabber_Pkts,Rx_Broadcast_Pkts,Rx_Multicast_Pkts,Rx_CRC_Align_Error_Pkts,Collision_Errors,Rx_Error_Pkts,Rx_Octets,Rx_Pkts,Tx_Octets,Tx_Pkts,PCS_LCV,PCS_ES,PCS_SES,PCS_UAS\n60001,MUR_BCLKL_SCH_P_E50831,XS A:AMXE_2 10GE-MoE Port 1,15min,2016-01-12 11:34:09,900,false,6181514,745,32,5,15,112,0,0,0,0,0,0,1750,0,0,0,395865158,6182423,38646121868,33820939,0,0,0,0\n60002,BGL_TNGKA_WFD_P_E50881_GNE,TS3:DHXE_2 10GE-MoE Port 1,15min,2016-01-12 11:34:08,899,false,6176604,41832667,24284819,4767589,4678894,89462610,0,0,0,0,0,0,1232,0,0,0,147459247592,171203181,42979716544,177984939,0,0,0,0\n60003,TLP_TNGAP_KKM_P_E50637,XS A:AMXE_2 10GE-MoE Port 1,15min,2016-01-12
kwargs:    {}
Exception: OverflowError('Overflow',)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:55012: Overflow
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<built-in function apply>, <function pandas_read_text at 0x7fbdd455fcf8>, [<function read_csv at 0x7fbdb3b30f50>, 'ID,NE,Object,Granularity,Report Time,Monitor Seconds,Suspect Flag,Rx_Pkts_64,Rx_Pkts_65_127,Rx_Pkts_128_255,Rx_Pkts_256_511,Rx_Pkts_512_1023,Rx_Pkts_1024_1518,Rx_Pkts_1519_MTU,Rx_Undersize_Pkts,Rx_Oversize_Pkts,Rx_Fragments,Rx_Jabber_Pkts,Rx_Broadcast_Pkts,Rx_Multicast_Pkts,Rx_CRC_Align_Error_Pkts,Collision_Errors,Rx_Error_Pkts,Rx_Octets,Rx_Pkts,Tx_Octets,Tx_Pkts,PCS_LCV,PCS_ES,PCS_SES,PCS_UAS\n140001,CLT_BCLKL_NEC_P_E50867_GNE,TS6:DHGE_8 GE-ETY Port 1,15min,2016-01-12 23:48:12,899,false,10583,221313,50292,24090,22360,913787,0,0,0,0,0,98,5394,0,0,0,1432573969,1242423,196314551,779750,NA,NA,NA,NA\n140002,CLT_BCLKL_NEC_P_E50867_GNE,TS6:DHGE_8 GE-ETY Port 2,15min,2016-01-12 23:48:12,899,false,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NA,NA,NA,NA\n140003,CLT_BCLKL_NEC_P_E50867_GNE,TS6:DHGE_8 GE-ETY Port 3,15min,2016-01-12 23:48:12,899,false,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
kwargs:    {}
Exception: OverflowError('Overflow',)

**Comment by QuantScientist** [comment]
This seems to resolve the issue _**dtype=object:**_
``
df_orig = dd.read_csv(CSV_FILES+ '/zip_LARGE/11/*/*.csv', header=1, 
parse_dates=['Report Time'], names=col_names,dtype=object)
``
But that defies teh whole purpose of selecting the correct type for each column.

**Comment by mrocklin** [comment]
Can you verify that this works with Pandas?

**Comment by mrocklin** [comment]
Perhaps you can supply dtype=object just on the column that has the
difficult-to-handle data?

**Comment by mrocklin** [comment]
> Can you verify that this works with Pandas?

Any update on this?  It would be nice to verify that the Overflow error is coming from Dask and not Pandas before diving into this.

**Comment by jcrist** [comment]
Closing for now as stale. Feel free to reopen if you can provide a reproducible test case.
