### ISSUE TITLE
Ordering is broken when using map_partitions returning a MultiIndex DataFrame

### ISSUE THREAD

**Issue by rach** [dask/dask#2046]
I understand that Dask doesn't yet support MultiIndex DataFrame. I noticed that if a function return a MultiIndex df when you use map_partitions and use MultiIndex DF as meta then the order is broken. Eg: value of some columns are in different columns.

This was a behavior that I observer with 0.13 and I'm not of the support for MultiIndex DF for some of this operations and the behavior may have changed since 0.13. 
If this operation is not supported then It may be better to fail if the user pass a MultiIndex DF as meta. It's possible to make it works if you sort the columns on the meta DF and the output.

**Comment by mrocklin** [comment]
Thanks for the bug report.  Are you able to provide a minimum failing
example?  http://stackoverflow.com/help/mcve

**Comment by rach** [comment]
Of course. Let me put an example together.

**Comment by rach** [comment]
My past code had a similar logic to this but I'm not able to reproduce the ordering problem with this small example. I will close this ticket for now but I will try to check if my previous commit work with dask 0.14 and come up with a better example

```
from dask import dataframe as ddf
import pandas as pd
from dask.dataframe.utils import make_meta

sub_df_1_type = {
    'b': 'float64',
    'a': 'float64',
    'date': 'datetime64[ns]',
}

sub_df_2_type = {
    'a': 'object',
    'b': 'float64',
    'x': 'float64',
    'token': 'object',
    
}

make_meta(sub_df_1_type), make_meta(sub_df_2_type)
meta_df = pd.concat({'group1': make_meta(sub_df_1_type), 'group2': make_meta(sub_df_2_type)}, axis=1)
meta_df
df = pd.DataFrame([{'a': 1}]*1000)
returning_df = pd.concat({'group1': pd.DataFrame([{'a': 1, 'b': 2, 'date': '2011-01-01'}]*1000), 'group2': pd.DataFrame([{'a': 'woow', 'x': 4, 'token': 'something'}]*1000)}, axis=1)
dask_df = ddf.from_pandas(df, chunksize=10)
ddf.map_partitions(lambda *args, **kwargs: returning_df, meta=meta_df).compute()
```
