### ISSUE TITLE
df.to_parquet throws TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2047]
HI,
I have a dask data-frame which I am trying to convert to parquet. 

```
import os, datetime
def createNewDir(basePath=PARQUET_FILES):
    parquet_dir = os.path.join(basePath, datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
    os.makedirs(parquet_dir)
    return parquet_dir


```
`X_df.to_parquet(parquet_dir, compression='SNAPPY') `

I am using python 2.7 and this is the stack trace: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-a25af0083707> in <module>()
      4 # fastparquet.write(parquet_dir, X_df, file_scheme='hive',compression="SNAPPY")
      5 
----> 6 X_df.to_parquet('.', compression='SNAPPY')

/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.pyc in to_parquet(self, path, *args, **kwargs)
    944         """ See dd.to_parquet docstring for more information """
    945         from .io import to_parquet
--> 946         return to_parquet(path, self, *args, **kwargs)
    947 
    948     def to_csv(self, filename, **kwargs):

/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/parquet.pyc in to_parquet(path, df, compression, write_index, has_nulls, fixed_text, object_encoding, storage_options, append, ignore_divisions)
    223     myopen = OpenFileCreator(path, compression=None, text=False,
    224                              **(storage_options or {}))
--> 225     myopen.fs.mkdirs(path)
    226     sep = myopen.fs.sep
    227     metadata_fn = sep.join([path, '_metadata'])
/usr/local/lib/python2.7/dist-packages/dask/bytes/local.pyc in mkdirs(self, path)
     42         if path.startswith('file://'):
     43             path = path[len('file://'):]
---> 44         return os.makedirs(path, exist_ok=True)
     45 
     46     def open(self, path, mode='rb', **kwargs):

TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
I see this is not py2 compatible. Fix coming.

**Comment by martindurant** [comment]
Question: do we not test parquet on py2? It should work from now.

**Comment by mrocklin** [comment]
See
https://github.com/dask/dask/blob/master/continuous_integration/travis/install.sh

**Comment by martindurant** [comment]
So we could add it, but I'm not sure how much effort we want to put into py2 maintenance across the libraries.

**Comment by mrocklin** [comment]
It shouldn't be hard to add.  I would move fastparquet from the py35 only
section and into the base conda install section.

**Comment by martindurant** [comment]
OK, trying it in #2050, we see if this throws up any additional issue.

**Comment by QuantScientist** [comment]
Hi :)
How can I get the fixed version? tried pulling from master but the same error is thrown.

**Comment by martindurant** [comment]
You can pull from the branch or wait until it is merged into master (probably today).

**Comment by QuantScientist** [comment]
I tried ! pip install --upgrade git+https://github.com/dask/dask.git
Still the same issue.

**Comment by tega23** [comment]
This helped
sudo apt install python python-dev python3 python3-dev
Check this page : https://cloud.google.com/python/setup#installing_python
