### ISSUE TITLE
Invoking set_index while or after reading CSV's takes a vert long time to complete

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2048]
Hi,
If I set index as follows, it seems that on the computation graph many  tasks are added: 
```
df_orig = dd.read_csv(CSV_FILES+ '/zip_LARGE/12/*/*.csv', header=1, 
    parse_dates=['Report Time'], names=col_names,dtype=col_types).set_index('Report Time')
```
And the computation time increased exponentially. 

This:
`df_orig.set_index(...) `
Also seems to be running forever. 

What is the best option here?
Using a pure pandas data-frame )after coercion) takes a very short time to complete.  

![image](https://cloud.githubusercontent.com/assets/18743986/23608133/958efbb6-0270-11e7-8d47-d07394d6296e.png)

**Comment by mrocklin** [comment]
Yes, shuffling in a distributed system is much more expensive than in a shared memory system.  If your data actually fits in memory then I would just use Pandas.  If your data fits on a single machine then I would just use the single-machine threaded scheduler (the default if you don't create a client.)

**Comment by jcrist** [comment]
Closing for now as stale. Feel free to reopen if there's still an issue/question here.
