### ISSUE TITLE
dd.read_parquet : RuntimeError: invalid input size (corrupted?)

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2051]
Hi,
Still struggling to have a basic work-flow.  
Parquet files which were generated by Apache Drill, a single file can be read correctly  using fastparquet, the exact same file results in the folowing stack trace when using dd.read_parquet: 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-45-2a671e4e009b> in <module>()
      3 import dask.dataframe as dd
      4 
----> 5 df_from_parquet = dd.read_parquet(PARQUET_FILES)
      6 # df_from_parquet = d_client.persist(df_from_parquet)
      7 # Dask runs entirely asynchronously, leaving operators free to explore while computations happen in the background.

/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/parquet.pyc in read_parquet(path, columns, filters, categories, index, storage_options)
     83 
     84     # Find an index among the partially sorted columns
---> 85     minmax = fastparquet.api.sorted_partitioned_columns(pf)
     86 
     87     if index is False:

/usr/local/lib/python2.7/dist-packages/fastparquet/api.pyc in sorted_partitioned_columns(pf)
    506     statistics
    507     """
--> 508     s = statistics(pf)
    509     columns = pf.columns
    510     out = dict()

/usr/local/lib/python2.7/dist-packages/fastparquet/api.pyc in statistics(obj)
    468 
    469     if isinstance(obj, ParquetFile):
--> 470         L = list(map(statistics, obj.row_groups))
    471         names = obj.columns
    472         d = {n: {col: [item[col].get(n, None) for item in L]

/usr/local/lib/python2.7/dist-packages/fastparquet/api.pyc in statistics(obj)
    465     if isinstance(obj, parquet_thrift.RowGroup):
    466         return {'.'.join(c.meta_data.path_in_schema): statistics(c)
--> 467                 for c in obj.columns}
    468 
    469     if isinstance(obj, ParquetFile):

/usr/local/lib/python2.7/dist-packages/fastparquet/api.pyc in <dictcomp>((c,))
    465     if isinstance(obj, parquet_thrift.RowGroup):
    466         return {'.'.join(c.meta_data.path_in_schema): statistics(c)
--> 467                 for c in obj.columns}
    468 
    469     if isinstance(obj, ParquetFile):

/usr/local/lib/python2.7/dist-packages/fastparquet/api.pyc in statistics(obj)
    454             return rv
    455         if s.max is not None:
--> 456             rv['max'] = encoding.read_plain(ensure_bytes(s.max), md.type, 1)[0]
    457         if s.min is not None:
    458             rv['min'] = encoding.read_plain(ensure_bytes(s.min), md.type, 1)[0]

/usr/local/lib/python2.7/dist-packages/fastparquet/encoding.pyc in read_plain(raw_bytes, type_, count, width)
     45         return read_plain_boolean(raw_bytes, count)
     46     # variable byte arrays (rare)
---> 47     return np.array(unpack_byte_array(raw_bytes, count), dtype='O')
     48 
     49 

/usr/local/lib/python2.7/dist-packages/fastparquet/speedups.pyx in fastparquet.speedups.unpack_byte_array (fastparquet/speedups.c:3276)()
    164 
    165     if remaining != 0:
--> 166         raise RuntimeError("invalid input size (corrupted?)")
    167     return out

RuntimeError: invalid input size (corrupted?)
```

Is this too a python 2 issue? 
I really want something working before I give up :)

**Comment by martindurant** [comment]
@QuantScientist , it is hard to diagnose from the stack-trace alone. As usual, is there any chance you can provide a self-contained example? Failing that, perhaps an extract from the data itself that shows the problem. It appears to happen while analysing the partition max/min values.

@mrocklin , if occurs to me that it's wasted effort to load statistics if index=False, and should only load statistics for the given index column, if an index is specified.

**Comment by QuantScientist** [comment]
How to reproduce: 

```
import dask
PARQUET_FILES_FROM_DASK= '/root/parquet/parquet_small_3/0_0_0.parquet'# docker mapping
import dask.dataframe as dd
df_from_parquet = dd.read_parquet(PARQUET_FILES_FROM_DASK)

```

Open the attached ZIP file which contains the parquet file. 
[parquet_small_3.zip](https://github.com/dask/dask/files/824779/parquet_small_3.zip)

**Comment by QuantScientist** [comment]
Also note that the same file, can be read by fastparquet easily:

![image](https://cloud.githubusercontent.com/assets/18743986/23662971/e0102fc2-0359-11e7-8ffe-22a833536b15.png)

**Comment by QuantScientist** [comment]
I am still getting the same error even after updating to the latest versions. 

![2017-03-09 08_39_11-analyticsdatacsvtoparquetusingdask](https://cloud.githubusercontent.com/assets/18743986/23738844/fe62bc7e-04a3-11e7-81f7-8412fe2b0abc.png)

**Comment by martindurant** [comment]
Did you also update fastparquet `pip install --upgrade git+https://github.com/dask/fastparquet` ?

**Comment by DigitalPig** [comment]
I experience the same issue using latest `dask` and `fastparquet` trying to read a parquet file generated by Spark 2.1. Here is the sample tar file:

[dask-data.tar.gz](https://github.com/dask/dask/files/917738/dask-data.tar.gz)

**Comment by martindurant** [comment]
I'm afraid that the data reads fine with dask or raw fastparquet, sorry :|

You probably know, but all of those data files are empty (contain only metadata, no rows) except for part-00000.

**Comment by DigitalPig** [comment]
Hmm... that is interesting. Are you saying that you can `read.parquet` the whole dir without any issue? Do you use `dd.read_parquet('./dask_data')`?

This dataset is quite small, only three rows and three columns. So I am not surprised that some of them are empty.

**Comment by martindurant** [comment]
Yes, `dd.read_parquet('dask_data')` worked.

**Comment by DigitalPig** [comment]
Cool. This time is my bad. I can confirm if I am using the latest master `fastparquet`. everything is good now. :)
