### ISSUE TITLE
Read multiple parquet segments into a single partition

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2060]
Dask.dataframe computations tend to do well when partitions are of a certain size.  If partitions are too small then overheads can take over.  For datasets like CSV the user can tune this using blocksize parameters.

For `read_parquet` we currrently associate one partition per row group.  This may be suboptimal depending on how the data is stored.  We might choose to have a single dask task read multiple parquet row groups as a single fused task.  

Any thoughts on this @martindurant ?

**Comment by martindurant** [comment]
The row group is the "natural size" for a parquet file, originally being limited by the HDFS block size for map-reduce systems. There are smaller units (column chunks) and conceivably larger units (files) which could for a data-set. When writing, we make one file, containing one row-group, containing one column-chunk per original partition, and this appears to be fairly typical of other parquet systems. 
There is no theoretical reason we couldn't partition the dataframe more coarsely when reading, but how would you decide? Total number of rows, total number of bytes? This latter will depend on the rows selected and, potentially, the encoding/compression.

**Comment by mrocklin** [comment]
Do we have statistics for how many rows are in each group?  If so we might do a small calculation based on dtype size.  So we might get a bunch of groups, get their approximate sizes, then bundle them up so that each group had roughly, say 128MB of data, and then create a task to read those.

**Comment by martindurant** [comment]
Yes, we know the number of rows, the encoding, number of nulls (sometimes), number of bytes compressed/uncompressed for each chunk of each row-group beforehand. 

```
pf = fastparquet.ParquetFile(...)
list_of_rows = [rg.num_rows for rg in pf.fmd.row_groups]
list_of_bytes = [rg.total_byte_size for rg in pf.fmd.row_groups] # size on disc for all columns
```

(Note that the number of chunks within a given row-group is not necessarily the same for every column, but that's going more fine-grained rather than coarse-grained)

**Comment by ian-r-rose** [comment]
This is now possible today using a combination of the `chunksize` and `aggregate_files` options. Closing as done
