### ISSUE TITLE
Consistent behavior with NumPy arrays

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2064]
When someone  puts a numpy array into a dask.array function what is expected behavior?  Here is a non-exhaustive list of options:

1.  Operate as a numpy function
2.  Err informatively
3.  Convert the numpy array to a single-chunk dask.array and operate lazily
4.  ...

Given that expected behavior what is the best way to implement this consistently across all dask.array functions?

cc @shoyer

**Comment by martindurant** [comment]
Are we talking about `da.func(nparray)`, `mydarray.func(nparray)`, or both?

**Comment by mrocklin** [comment]
`da.func(nparray)`

**Comment by mrocklin** [comment]
although I suppose we should have a good answer to the other as well.

**Comment by shoyer** [comment]
> Convert the numpy array to a single-chunk dask.array and operate lazily

This would be my preferred option. I think `dask.array.core.asarray` already does the right thing already, though see the concerns I raised about a potential bug with the current implementation in https://github.com/dask/dask/pull/1152/files

**Comment by mrocklin** [comment]
We could put this behavior easily into `atop`, which would cover many (but not all) cases.  Should we support this partially?
