### ISSUE TITLE
skiprows makes Dask skip rows in each partition

### ISSUE THREAD

**Issue by p-himik** [dask/dask#2065]
```python
import dask.dataframe as dd
import dask

print(dask.__version__)
# 0.14.0

d = dd.read_csv('data.txt', skiprows=1000, dtype=str)
print(d.npartitions)
# 6
print(d.compute().shape[0])
# 2644307
```
```sh
$ wc -l data.txt
2650308 data.txt
```

Apparently, Dask passes `skiprows` to each call of `pandas.read_csv`, whereas when reading a single file it should pass it only to the call that reads the first partition.

**Comment by mrocklin** [comment]
Clearly an issue.  Do you think we should pass it once to each file though
or only the first?

**Comment by p-himik** [comment]
I'd say to each file. Having only a single file with both data and some not column related header info doesn't sound right.
Of course, someone still may have such situation, but if that someone wants such behavior to be implemented in Dask, I would treat it as a feature.

**Comment by mrocklin** [comment]
Do you have any interest in submitting a PR with a proposed fix?  I'd love to get some more hands in this project.  

The relevant function is probably [text_blocks_to_pandas](https://github.com/dask/dask/blob/master/dask/dataframe/io/csv.py#L88-L136) .  That function receives a list of delayed values that point to blocks of bytes from a single file.  You can see how the first block is already singled out.  We would have to do some logic there to manipulate the keyword arguments passed down to different blocks.

**Comment by p-himik** [comment]
Thanks for the starting point. I think I'll be able to spend some time on this during the next week.

**Comment by mrocklin** [comment]
Thank you for the effort.

**Comment by mrocklin** [comment]
And thank you for the bug report regardless.

**Comment by p-himik** [comment]
Wow, time sure flies.

The fix that involves just manipulation of the kwargs is trivial, but is, strictly speaking, not correct.
What if the number of lines I want to skip is larger than the number of lines in the first block? I know that a block's size is supposed to be in the order of 10-100MB which makes such situation unlikely, but it's still a possibility.

**Comment by mrocklin** [comment]
It's good to be aware of such issues, but generally we ignore them.  If we wanted to be very careful we could put in a runtime check that verified the data as we actually read it.  In practice I suspect that adding checks for all corner cases like this would as likely introduce bugs and identify them.
