### ISSUE TITLE
Dask unable to start more than one bokeh instance (diagonstic server) when using Client

### ISSUE THREAD

**Issue by triskadecaepyon** [dask/dask#2067]
When using two "local" Clients, Dask is unable to start a second instance of the diagnostic server on port 8787 (i.e. the bokeh server), or autoselect a new port for it like it does for the scheduler.  Change https://github.com/dask/distributed/pull/850 has it native to LocalCluster, but not for Client.

**Instance 1:** 
client_a = client.Client()
client_a.scheduler_info
<bound method Client.scheduler_info of <Client: scheduler='tcp://127.0.0.1:8786' processes=4 cores=4>>

**Instance 2:**
client_b = client.Client()
client_b.scheduler_info
<bound method Client.scheduler_info of <Client: scheduler='tcp://127.0.0.1:55550' processes=4 cores=4>>

_with error message:_ 
[I 11:14:49.303 NotebookApp] Saving file at /Demo of calculation-Copy1.ipynb
bokeh.command.util - CRITICAL - Cannot start Bokeh server, port 8787 is already in use

**However, when done manually with Local Clusters, it is possible:**

local1 = LocalCluster()
local1.diagnostics_port
8787
local2 = LocalCluster(scheduler_port=50000,diagnostics_port=9000)
local1.diagnostics_port
9000
client_n = client.Client(local2)
client_n.scheduler_info
<bound method Client.scheduler_info of <Client: scheduler='tcp://127.0.0.1:50000' processes=4 cores=4>>

**Comment by mrocklin** [comment]
Yes, this is true.  This would probably be resolvable by https://github.com/dask/distributed/pull/815 if you wanted to take that on.

**Comment by triskadecaepyon** [comment]
@mrocklin , I'm assuming the auto-selection of the port as default behavior when starting Client() is preferred vs passing kwargs (like in https://github.com/dask/distributed/pull/815)?

**Comment by mrocklin** [comment]
I think it's reasonable to fall back to random ports for the scheduler because the user never really needs to know this address.  However for the web addresses the user arguably needs to know the port numbers so that they can enter them into a web browser.  One way to make sure they know this address is to have them enter it.  

Another solution might be to have some method on the client that opens a web browser for them pointed to the correct location.  I've actually never looked into if there is a standard way to do this from within Python.

**Comment by martindurant** [comment]
In the webbrowser module, there is - but only if the client is actually running locally, as opposed to within a remote jupyter session or such.

**Comment by triskadecaepyon** [comment]
Would it suffice to have the diagnostic server info published in scheduler_info as a start?

**Comment by mrocklin** [comment]
It probably already is?  I'm not sure how much I trust the average novice user to understand the output of `scheduler_info`.

**Comment by triskadecaepyon** [comment]
It looks to be absent in the source for scheduler_info:

https://distributed.readthedocs.io/en/latest/_modules/distributed/scheduler.html#Scheduler.identity

Which is most likely why it doesn't show up when called this way:

local2 = LocalCluster(scheduler_port=50000,diagnostics_port=9000)
client_n = client.Client(local2)
client_n.scheduler_info()
```
Out[7]:
{'address': 'tcp://127.0.0.1:50000',
 'id': 'dfc5e03e-0685-11e7-a3a1-7831c1c7a85c',
 'services': {'http': 50538},
 'type': 'Scheduler',
 'workers': {'tcp://127.0.0.1:50525': {'host': '127.0.0.1',
   'last-seen': 1489255781.358873,
   'local_directory': '/var/folders/2r/kcn7byqs73376y6yrd73p8680000gn/T/nanny-6gh8fwf_',
   'memory_limit': 17179869184.0,
   'name': 'tcp://127.0.0.1:50525',
   'ncores': 1,
   'services': {'nanny': 50521},
   'time-delay': 0.0013239383697509766},
  'tcp://127.0.0.1:50527': {'host': '127.0.0.1',
   'last-seen': 1489255781.366046,
......
```

I'd agree with the novice user not knowing about it in scheduler_info.  Thoughts?

**Comment by mrocklin** [comment]
No, no strong thoughts from me other than what I wrote above.  It would be nice to find a solution.

**Comment by triskadecaepyon** [comment]
I'll try a few ideas and report back via this thread.

**Comment by mrocklin** [comment]
Thank you for exploring this

**Comment by triskadecaepyon** [comment]
Sorry about the delay.  

After closer inspection, it looks like the majority of the changes required would start in client.py code in distributed/client.  In the code for _start(), LocalCluster is called without a fallback for the diagnostic server port (i.e. trying to bind to port 0, then listening in to verify the selected port).  

So my guess is that I'll need the code similar to distributed/scheduler.py in client.py to verify the selected port for the diagnostic server (code example from scheduler.py) and bind to port 0 if none is provided, as well as reporting back the actual port if the binding fails.
```
self.listen(addr_or_port)
self.ip = get_address_host(self.listen_address)
```
Does that sound like a sound plan? I think the changes should only touch client.py if done correctly.

**Comment by mrocklin** [comment]
I think that you would want to resolve this in deploy/cluster.py, not client.py.  I think that it will be harder in this case because the bokeh scheduler is in a separate process, so it's difficult to tell if it succeeded or not.  This will become easier when/if we merge https://github.com/dask/distributed/pull/963

**Comment by triskadecaepyon** [comment]
@mrocklin , do you mean deploy/local.py? I don't think I can find deploy/cluster.py in dask/distributed.

**Comment by mrocklin** [comment]
Sorry yes. That is what I meant.

**Comment by mrocklin** [comment]
Client now passes down keyword arguments to LocalCluster

```python
In [1]: from dask.distributed import Client

In [2]: client = Client()
client2 = 
In [3]: client2 = Client(diagnostics_port=0)

In [4]: client2.scheduler_info()['services']['bokeh']
Out[4]: 38146
```
