### ISSUE TITLE
Problem with dask.dataframe.io.tests.test_parquet

### ISSUE THREAD

**Issue by katsou55** [dask/dask#2072]
Hi,

I installed your package, and I tried to run the following specific test which is:

<img width="1017" alt="screen shot 2017-03-13 at 15 56 25" src="https://cloud.githubusercontent.com/assets/12156222/23863106/c5f50c64-0806-11e7-91d7-da1b53920e67.png">

What I really want to do is: 

<img width="981" alt="screen shot 2017-03-13 at 16 08 14" src="https://cloud.githubusercontent.com/assets/12156222/23868413/35a07b6a-0817-11e7-80f8-7051b3cdccf5.png">

But I since I got that error I tried your test (first print) in order to understand the root of the problem!
Looks like the os.makedirs() just accept an argument (path). Any idea how to solve this problem ?

I am using conda with python 2.7 and the last version of Dask.

**Comment by martindurant** [comment]
This py2 problem should have been fixed since #2050 which was merged on Mach 9, but not yet released as a conda package.

**Comment by katsou55** [comment]
I pulled the code from master, works. Thanks!
