### ISSUE TITLE
Add ``get`` parameter to dask.bag.to_textfiles() method

### ISSUE THREAD

**Issue by MattPitlyk** [dask/dask#2086]
I recommend adding the ``get`` parameter to ``bag.to_textfiles()`` (and probably any output method) to make it easier to use multiple processes for writing to files. I just spent a long time trying to figure out why my entire Dask pipeline was running multi-core until I added the ``.to_textfiles()`` step to the end of it, at which point everything ran in a single process. I just happened to stumble on [this answer](http://stackoverflow.com/a/35516679/6661502), which wasn't addressing my question, but told me what I need to know, nonetheless.

I can provide a complete example if you need one (omitting for now, since this isn't a bug issue). In the end I had to set ``compute=False`` for ``to_textfiles()`` and then use ``db.compute(write_bag, get=dask.multiprocessing.get)`` in order to get multiple processes. I think having the get parameter exposed to the user within the method and others like it makes a lot of sense. At the very least, the docs should mention that the default get is threading.

Thanks,
Matt

**Comment by mrocklin** [comment]
Yeah, this looks like it's happening because we're using dask.delayed, for which the default scheduler is the threaded scheduler.
