### ISSUE TITLE
Optionally allow pyFFTW in place of numpy.fft

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2092]
The pyFFTW provides a nice lightweight Python library that wraps FFTW. Given how well optimized FFTW is, this ends up being significantly faster. Thanks to its [interfaces]( http://pyfftw.github.io/pyFFTW/pyfftw/interfaces/interfaces.html ) it is pretty easy to drop in a pyFFTW in place of NumPy's FFTPACK. Would be nice if there was an option (maybe a function?) to change up the FFT backend used in Dask.

**Comment by mrocklin** [comment]
Looking at https://github.com/dask/dask/blob/master/dask/array/fft.py can
you think of a good way to do this?  Might also want to expand to scipy?

**Comment by jakirkham** [comment]
This is not very clever, but I had thought about just reassigning what [`npfft`]( https://github.com/dask/dask/blob/a36f36d1a1f79f39ce94e157befc1406547ae024/dask/array/fft.py#L6 ) points to after the fact.

**Comment by mrocklin** [comment]
Yeah, Dask probably can't do that responsibly.  You could in your own code thought.  

Probably there is some way to change `_fft_wrap` to take a function name, like `'fft'` and produce a function that takes an fft module as a keyword argument.  This keyword would default to `np.fft` but could be replaced by others.

**Comment by jakirkham** [comment]
A different idea might be to let people wrap their own FFTs. So we provide functions like `*fft_wrap`, which take an FFT function of that type and return a function that can perform an FFT of that form. So as an example `fft_wrap(numpy.fft.fft)` would return the same thing as `dask.array.fft.fft`.

**Comment by mrocklin** [comment]
Sure, that sounds like a great idea.  Presumably this works well now.  We might want to make the `_fft_wrap` function slightly more user-facing with a nice docstring with examples and such.

**Comment by jakirkham** [comment]
Ok, I'll give it a look.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/dask/dask/pull/2093 ).

**Comment by jakirkham** [comment]
Probably worth noting that as of pyFFTW 0.11.0+, they provide a Dask-like interface, which can be used as a drop-in substitute for the one we provide.

ref: https://pyfftw.readthedocs.io/en/latest/source/pyfftw/interfaces/interfaces.html#dask-fft

**Comment by mrocklin** [comment]
Awesome.  I'm glad to hear it.
