### ISSUE TITLE
Issues (wrong result) when computing the mean on a NetCDF file 

### ISSUE THREAD

**Issue by matteodefelice** [dask/dask#2095]
Hi,
I was exploring the use of dask for climate data analysis. 
This is a minimal example in iPyhon: 
```
import dask.array as da
from netCDF4 import Dataset
f = Dataset('/opt/data/EOBS/pp_0.50deg_reg_v10.0.mon.nc')
f.variables['pp'][:].mean()
Out[3]: 1014.3992960196152
daskarray = da.from_array(f.variables['pp'], chunks = (1000))
daskarray.mean().compute()
Out[8]: -8371.5934749772732
```
The final result varies slightly when changing the chunks. 
I have tried with several NetCDF files, on two different machines (MacOS with Python 2.7.13 and dask 0.14 and Ubuntu with Python 2.7.12 and the same version of dask)
**UPDATE**: When I wrote this post I still wasn't aware of the lack of support from `dask` for the `numpy` masked arrays. However, the next comment of mine is still a valid and open issue.

**Comment by matteodefelice** [comment]
Ok, an update. 
The problem disappears when I use a dataset without NaN but now I have another issue: if I "split" the computation on the time dimension (chunksize < length time dimension) I get the wrong numbers.
Here the code with the new dataset:
```
f = Dataset('/opt/data/ERAIN/ERAIN-t2m-1983-2012.seasmean.nc')
f.variables['var167'][:].mean()
Out[4]: 278.62466
daskarray = da.from_array(f.variables['var167'], chunks = (1000))
daskarray.mean().compute() 
Out[6]: 278.62466
f.variables['var167'][:].shape
Out[9]: (121, 256, 512)
daskarray = da.from_array(f.variables['var167'], chunks = (121,120,512))
daskarray.mean().compute()
Out[13]: 278.26028
daskarray = da.from_array(f.variables['var167'], chunks = (60,256,512))
daskarray.mean().compute()
Out[15]: 1.3058767e+26
```

**Comment by jcrist** [comment]
Hmmm, that's concerning. Does it fail if you load your dataset into memory beforehand (if it fits?):

```python
da.from_array(f.variables['var167'][:], chunks=(60, 256, 512)).mean()
```

 Can you provide a reproducible example?

**Comment by matteodefelice** [comment]
The dataset is ~65 MB, here the file https://www.dropbox.com/s/xtj3fm7ihtbwd5r/ERAIN-t2m-1983-2012.seasmean.nc?dl=0 

Honestly, I've just tried but I didn't get the error. However, is it normal to have different results when changing the chunk size?

**Comment by jcrist** [comment]
No. That should only matter for poorly conditioned datasets, and reading from disk or in memory shouldn't change things. Thanks, I'll take a look. Are you using the 0.14 dask release or dask from github master?

**Comment by matteodefelice** [comment]
It's the 0.14.0 installed from macports.

**Comment by rabernat** [comment]
@matteodefelice, you might want to consider trying out [xarray](xarray.pydata.org/en/stable/), which is designed for working with netcdf-style data and integrates tightly with dask. I would be curious to see what answer you get if you load your data via xarray and do the same mean operation.

**Comment by mrocklin** [comment]
> It's the 0.14.0 installed from macports.

Dask is distributed through macports?

**Comment by matteodefelice** [comment]
@mrocklin Yes, look at here: https://www.macports.org/ports.php?by=name&substr=py-dask
@rabernat I have tried (using the last xarray from Github) and the situation looks weirder and weirder:
```
# With dask
In [13]: f = netCDF4.Dataset('/opt/data/ERAIN/ERAIN-t2m-1983-2012.seasmean.nc')
    ...: f.variables['var167'][:].mean()
    ...: 
Out[13]: 278.62466
# With xarray
In [14]: ds = xarray.open_dataset('/opt/data/ERAIN/ERAIN-t2m-1983-2012.seasmean.nc')
In [14]: ds.var167[:].mean()
Out[14]: 
<xarray.DataArray 'var167' ()>
array(261.6441345214844)
```
Same file, different averages...

**Comment by martindurant** [comment]
xarray does not use dask unless you provide the `chunks` keyword, so this looks like a clue to something inherently odd about the data, perhaps to do with auto-scaling and nan labelling at load time. The variable `ds` should give you lots of metadata about itself with a simple print.

**Comment by matteodefelice** [comment]
Well, you are probably right, I have tried with another file and the two averages are almost identical.
Nevertheless, this behaviour worries me because the former dataset hasn't been processed in any particular way, FYI here the output of `ds`:
```
Out[22]: 
<xarray.Dataset>
Dimensions:    (bnds: 2, lat: 256, lon: 512, time: 121)
Coordinates:
  * lon        (lon) float64 0.0 0.7031 1.406 2.109 2.812 3.516 4.219 4.922 ...
  * lat        (lat) float64 89.46 88.77 88.07 87.37 86.66 85.96 85.26 84.56 ...
  * time       (time) datetime64[ns] 1983-01-31T03:00:00 1983-04-15T21:00:00 ...
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) float64 0.0 1.41e+03 1.416e+03 3.618e+03 ...
    var167     (time, lat, lon) float32 243.053 243.057 243.06 243.064 ...
Attributes:
    CDI: Climate Data Interface version 1.7.2 (http://mpimet.mpg.de/cdi)
    Conventions: CF-1.4
    history: Sun Sep 04 15:15:29 2016: cdo seasmean temp.nc ERAIN-t2m-1983-2012.seasmean.nc
Sun Sep 04 15:15:28 2016: cdo mergetime ERAIN-t2m-1983.grib.mon.nc ERAIN-t2m-1984.grib.mon.nc ERAIN-t2m-1985.grib.mon.nc ERAIN-t2m-1986.grib.mon.nc ERAIN-t2m-1987.grib.mon.nc ERAIN-t2m-1988.grib.mon.nc ERAIN-t2m-1989.grib.mon.nc ERAIN-t2m-1990.grib.mon.nc ERAIN-t2m-1991.grib.mon.nc ERAIN-t2m-1992.grib.mon.nc ERAIN-t2m-1993.grib.mon.nc ERAIN-t2m-1994.grib.mon.nc ERAIN-t2m-1995.grib.mon.nc ERAIN-t2m-1996.grib.mon.nc ...
    institution: European Centre for Medium-Range Weather Forecasts
    frequency: mon
    CDO: Climate Data Operators version 1.7.2 (http://mpimet.mpg.de/cdo)
```

**Comment by martindurant** [comment]
I suspect `ds.var167` has more information too.

**Comment by matteodefelice** [comment]
Here:
```
In [28]: ds.var167
Out[28]: 
<xarray.DataArray 'var167' (time: 121, lat: 256, lon: 512)>
[15859712 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 0.0 0.7031 1.406 2.109 2.812 3.516 4.219 4.922 ...
  * lat      (lat) float64 89.46 88.77 88.07 87.37 86.66 85.96 85.26 84.56 ...
  * time     (time) datetime64[ns] 1983-01-31T03:00:00 1983-04-15T21:00:00 ...
Attributes:
    code: 167
    table: 128
    grid_type: gaussian
```

**Comment by martindurant** [comment]
Hm, maybe not... I was expecting something about valid data ranges or missing values like [here](http://cfconventions.org/Data/cf-documents/overview/viewgraphs.pdf) (page 6). There seem to be a lot of conventions that can apply, CF-1.4 is listed above, that map the numbers in raw binary to usable data.

**Comment by matteodefelice** [comment]
Whatever is the cause, it is definitely a big concern for me: that dataset has been produced using a common workflow based on CDO and the average obtained with `dask` is consistent with the one obtained with other tools (e.g. R with ncdf4 library).

**Comment by jcrist** [comment]
Apologies for the long delay here. I'm unable to reproduce using the provided file and the specified packages:

```python
In [1]: import dask.array as da

In [2]: from netCDF4 import Dataset

In [3]: f = Dataset('ERAIN-t2m-1983-2012.seasmean.nc')

In [4]: nx = f.variables['var167']

In [5]: dx = da.from_array(nx, chunks=(121,120,512), lock=True)

In [6]: dx.mean().compute()
Out[6]: 278.62488

In [7]: dx = da.from_array(nx, chunks=(60,256,512), lock=True)

In [8]: dx.mean().compute()
Out[8]: 278.62497

In [9]: dx = da.from_array(nx, chunks=1000, lock=True)

In [10]: dx.mean().compute()
Out[10]: 278.62466
```

I do get slightly different numbers for different chunk sizes, but that has to do with numeric precision and the fact that you're using `float32` (as pointed out in https://github.com/pydata/xarray/issues/1346#issuecomment-290760342).

What version of numpy are you using (`python -c "import numpy;print(numpy.__version__)"`)?

**Comment by matteodefelice** [comment]
I'm using `numpy` 1.12.1
I can reproduce your results but...
```
daskarray = da.from_array(f.variables['var167'], chunks = (121,120,512)
    ...: )
daskarray.mean().compute()
Out[26]: 279.21347
```
Every time I get random result:
```
In [27]: daskarray.mean().compute()
    ...: 
Out[27]: 278.6846
In [28]: daskarray.mean().compute()
    ...: 
Out[28]: 278.255
In [29]: daskarray.mean().compute()
    ...: 
Out[29]: 3.1980865e+22
In [30]: daskarray.mean().compute()
    ...: 
Out[30]: 279.53751
```
Instead:
```
daskarray = da.from_array(f.variables['var167'], chunks = (121,120,512), lock = True)  
daskarray.mean().compute()
Out[81]: 278.62488
```

**Comment by jcrist** [comment]
The lock prevents concurrent reads from the same file. Netcdf4 files can't be safely read concurrently, as the underlying library uses global state. Depending on your build of hdf5 (which underlies netcdf4) you may have a lock at the c level, otherwise you need to use `lock=True` for things to work properly. I'm surprised your call to compute produces results, my non-threadsafe build fails at a c level assert in the underlying library and kills the process.

**Comment by jcrist** [comment]
Closing for now as stale. It sounds like your issue was solved by specifying `lock=True`. Feel free to reopen if you're still experiencing problems.
