### ISSUE TITLE
Enable repartitioning to more partitions

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask#2099]
If you have a single large dataframe it would be useful to be able to repartition it to have *more* partitions so that work can be parallelised.

At present this isn't allowed for - https://github.com/dask/dask/blob/175ae5a91ac09940c1065ea007a6a93a95d39207/dask/dataframe/core.py#L858

**Comment by mrocklin** [comment]
I'm generally in favor.

When there are known_divisions we should probably use `np.interp` to interpolate between the current values.  

```python
new_divisions = tuple(np.interp(..., self.divisions, ...))
return self.repartition(divisions=new_divisions)
```

When divisions are unknown then we should probably split partitions with `iloc`.

@dhirschfeld do you have any interest in taking this on?

**Comment by dhirschfeld** [comment]
It doesn't sound too difficult so I'll try to find some time to give it a shot...
