### ISSUE TITLE
tput warning in AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2102]
Seeing the following message cropping up in AppVeyor builds.

```
tput: terminal attributes: No such device or address
```

ref: https://ci.appveyor.com/project/daskdev/dask/build/1.0.774#L457

Edit: FWIW it doesn't appear in this [build]( https://ci.appveyor.com/project/daskdev/dask/build/1.0.762 ). So if it is a change in dask that caused this, that should hopefully help put a range on where it was introduced.

**Comment by jakirkham** [comment]
If I had to guess there is something like a text-based progress bar or other cursor moving thing, that is causing this warning.

**Comment by jakirkham** [comment]
This seems to be the [first build]( https://ci.appveyor.com/project/daskdev/dask/build/1.0.774#L457 ) on `master` where it shows up. The [previous build]( https://ci.appveyor.com/project/daskdev/dask/build/1.0.762 ) on `master appears to be free of this issue. Maybe that helps narrow it down.

**Comment by TomAugspurger** [comment]
This seems to have resolved itself https://ci.appveyor.com/project/daskdev/dask/build/1.0.4055
