### ISSUE TITLE
Zero reference for Bokeh plots

### ISSUE THREAD

**Issue by jbednar** [dask/dask#2106]
The Bokeh plotting support is extremely useful, but I've found it confusing that the plots show calendar time rather than the start of a computation:

![image](https://cloud.githubusercontent.com/assets/1695496/24167807/1c2c3ca2-0e46-11e7-8527-4cbcc5dafeb2.png)

Here it's not clear when the first task was started, but judging by the blocks shown it appears to have been at about 46.2 seconds past the last minute boundary, with a task duration of about 3 seconds.  I think elapsed duration is usually what one cares about, not time of day, and so I think it would be much nicer if (a) there were no whitespace at the left, with the plot starting always at the first task's start), and (b) if the x axis would read out the elapsed time from this zero point, so that viewers don't have to do any tricky mental arithmetic to see how long tasks take.

One complication is that dask-scheduler has no concept of a "job" beginning, so it's not very well defined where to place this zero.  But there is already code to reset the plot after a period of inactivity (https://github.com/dask/distributed/blob/master/distributed/bokeh/components.py#L129-L138), and so presumably the plot could start from the first task's start, after a reset (if any).  The various times would all need to be subtracted from this reference, when plotting.

**Comment by bryevdv** [comment]
c.f. http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#functickformatter

**Comment by jbednar** [comment]
The functickformatter seems like it will solve the problem fairly easily, thanks!

**Comment by mrocklin** [comment]
Does the functickformatter require that node be present on the user's machine?

**Comment by mrocklin** [comment]
Or rather on the machine with the bokeh server

**Comment by bryevdv** [comment]
I'm not actually sure offhand, the quickest thing is probably just to try the linked example without node installed.

**Comment by jbednar** [comment]
Thanks!
