### ISSUE TITLE
Should delayed objects modify instances of classes?

### ISSUE THREAD

**Issue by ordirules** [dask/dask#2107]
```python
from dask import delayed
from nose.tools import assert_true

class MyClass(dict):
    pass

@delayed(pure=True)
def foo_dict(arg):
    assert_true(isinstance(arg, dict))

@delayed(pure=True)
def foo_myclass(arg):
    assert_true(isinstance(arg, MyClass))


# works fine
res = foo_dict(MyClass())
res.compute()
# raises an error
res = foo_myclass(MyClass())
res.compute()
```

This returns an error because when passing through `delayed`, the instance goes from a `MyClass` instance to `dict`.

Is this intended? For my use cases, it doesn't bother me much, but I want to better understand the inner workings of the `delayed` object, and what assumptions I can make.
If I replaced `delayed` with a `curry` instance, this works (of course, now don't do the last `compute` step). I'm not sure if this helps narrow things down.

Thanks for the great library!

**Comment by mrocklin** [comment]
I suspect that this is due to an `isinstance(obj, dict)` check somewhere that should *maybe* be an `type(obj) is dict` check.

**Comment by ordirules** [comment]
Do you mean in code above? I just tried replacing with `type` as you suggested, and still get the same result:
```python
def test_delayed_passthrough1():
    class MyClass(dict):
        pass

    @delayed(pure=True)
    def foo(arg):
        assert_true(isinstance(arg, MyClass))

    res = foo(MyClass())
    res.compute()
def test_delayed_passthrough2():
    class MyClass(dict):
        pass

    @delayed(pure=True)
    def foo(arg):
        assert_true(type(arg) is MyClass)

    res = foo(MyClass())
    res.compute()
```

both functions raise `AssertionErrors`

**Comment by mrocklin** [comment]
No, I mean somewhere within Dask.  Dask uses dicts in some special ways.
Your class subclasses dict, which is somewhat atypical.  I suspect that
inheriting from dict is what is causing this problem.

**Comment by ordirules** [comment]
Ah now I understand, `isinstance(MyClass, dict) = True`, thanks.

Found it. This does the trick (from latest master branch), but I think you already knew...
```
diff --git a/dask/delayed.py b/dask/delayed.py
index a9cbf63..b9a402d 100644
--- a/dask/delayed.py
+++ b/dask/delayed.py
@@ -86,7 +86,7 @@ def to_task_dask(expr):
             return (type(expr), args), dsk
         else:
             return args, dsk
-    if isinstance(expr, dict):
+    if type(expr) is dict:
         args, dsk = to_task_dask([[k, v] for k, v in expr.items()])
         return (dict, args), dsk
     return expr, {}
```

Should that be merged in along with the test I wrote above?

**Comment by mrocklin** [comment]
Yes, such a PR with a test would be great.  You might want to ping @jcrist who might be able to spot a corner case if one exists.

**Comment by jcrist** [comment]
Looks fine to me. Can you submit a PR with a test? Something similar to https://github.com/dask/dask/blob/master/dask/tests/test_delayed.py#L28 (same thing, but for tuples) would be good.

**Comment by ordirules** [comment]
sounds good, submitted, thanks!

**Comment by jcrist** [comment]
Fixed by #2108. Closing.

**Comment by ordirules** [comment]
The same issue seems to occur with distributed library (I fetched the latest version from master branch just in case). I am not sure where in the library is responsible.

```python
from dask import delayed
from dask.delayed import Delayed 
from distributed import Client
_pipeline_client = Client("10.11.128.3:8786")

def test_delayed_passthrough():
    ''' Test that a class that inherits dict isn't improperly interpreted and
        modified.
        This is from Issue https://github.com/dask/dask/issues/2107
    '''
    class MyClass(dict):
        pass

    @delayed(pure=True)
    def foo(arg):
        assert_true(isinstance(arg, MyClass))

    res = foo(MyClass())
    res.compute()
```

**Comment by martindurant** [comment]
I have checked, and within the function foo, when running in a worker process, `arg` does have the type MyClass, but id(type(arg)) and id(MyClass) do not match: i.e., presumably deserialization has created two identical class definitions. If you pass the class, it works fine:
```
@delayed(pure=True)
    def foo(arg, cls):
        assert_true(isinstance(arg, cls))

res = foo(MyClass(), MyClass)
```

**Comment by ordirules** [comment]
ah yes thanks, I should have seen that. I have noticed that issue in the past. A class defined in the same file code is run is not the same as a class imported (I don't understand the internals why, but it makes intuitive sense for a namespace safe system).

thanks again
