### ISSUE TITLE
Return type of computed scalar da changes after math operation

### ISSUE THREAD

**Issue by dkillick** [dask/dask#2111]
It seems that if you run a mathematical operation on a scalar dask array and compute the result, you get a different type returned than if you directly compute the result:

```python
x = da.from_array(np.array(5), chunks=1)
x
dask.array<array-c..., shape=(), dtype=int64, chunksize=()>
y = x + 5
y
dask.array<add-5e6..., shape=(), dtype=int64, chunksize=()>
type(x.compute())
<type 'numpy.ndarray'>
type(y.compute())
<type 'numpy.int64'>
```

We tripped over this behaviour in something we were doing recently. We can easily work with it, but we're interested in whether this behaviour is intentional or not.

Versions...

* Python 2.7.12
* Dask v0.13.0
* NumPy v1.11.1

**Comment by mrocklin** [comment]
No intent, but it looks like NumPy does this as well.

```python
In [9]: type(np.array(5))
Out[9]: numpy.ndarray

In [10]: type(np.array(5) + 5)
Out[10]: numpy.int64
```

NumPy scalars are weird.

**Comment by dkillick** [comment]
> NumPy scalars are weird.

Too right! As dask behaviour in this case is the same as NumPy behaviour, I'm happy to drop this as an issue, and we'll work with the behaviour.

Thanks @mrocklin!
