### ISSUE TITLE
Test with NumPy 1.12 (and drop NumPy 1.10)

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2117]
Raising this issue to discuss testing NumPy 1.12 in CIs (Travis CI notably). Also possibly contemporaneously dropping NumPy 1.10 from CI testing.

The primary motivator is testing with the new NumPy. The secondary motivator is dropping the Python 2.7, NumPy 1.10 CI test as it is the longest running one in the matrix FWICT.

**Comment by mrocklin** [comment]
I'm in favor of testing new NumPy.  Less excited about dropping old NumPy.

**Comment by jakirkham** [comment]
What about just dropping Python 2.7, NumPy 1.10? Seems that is the slowest one clocking in at 13+ mins. There would still be a test for it with Python 3.4.

**Comment by mrocklin** [comment]
That entry also tests docstrings and doesn't run in parallel, both of which may account for the added time.

**Comment by mrocklin** [comment]
Closing for now.  While I agree with the original intent of the issue of making tests run faster I think that the proposed solution is probably not the core problem.  Feel free to reopen.

**Comment by jakirkham** [comment]
We still need to add NumPy 1.12 though. The dropping of other builds was more of a suggestion.

In any event, I can't actually reopen an issue a member closes as GitHub does not give that permission to me.

**Comment by mrocklin** [comment]
Ah, I thought that people were able to reopen their own issues.

**Comment by jakirkham** [comment]
Only if I close it, but if others close it, I can't.

**Comment by jakirkham** [comment]
A potential proposal in PR ( https://github.com/dask/dask/pull/2145 ).
