### ISSUE TITLE
Dill fails to serialize globals in windows

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#212]
This error pops up in Windows

```python
>>> import dask.bag as db
>>> b = db.from_sequence([1, 2, 3])
>>> q = 5
>>> list(b.map(lambda x: x + q))
NameError: global name 'q' is not defined
```

This is because `dill` doesn't serialize globals well.  Somewhat related to https://github.com/uqfoundation/dill/issues/98

**Comment by mmckerns** [comment]
I believe the better link is: https://github.com/uqfoundation/dill/pull/86 -- which is essentially resolved through my edits to the referenced PR, but not applied (due to lack of time on my part as of late).

**Comment by jcrist** [comment]
@mrocklin : do you have access to a windows box? Both the referenced issues are closed, may be fixed.

**Comment by mrocklin** [comment]
This works for me if I set the recurse flag in dill

    dill.settings['recurse'] = True

but continues to fail otherwise.  Either we should set this flag in `dask`, which might be a bit invasive, or we should wait until this is set by default in `dill`.  My understanding from @mmckerns was that there were still some concerns about setting this flag by default.

**Comment by mmckerns** [comment]
I've tested, and can confirm the behavior that @mrocklin sees on windows.

Please see the discussion thread here:
https://github.com/uqfoundation/dill/issues/115
and the linked issues:
https://github.com/uqfoundation/dill/issues/105
https://github.com/uqfoundation/multiprocess/issues/6

**Comment by jcrist** [comment]
Dask now uses cloudpickle instead of dill for multiprocessing. Closing.
