### ISSUE TITLE
Cannot run diagnostics on compute method

### ISSUE THREAD

**Issue by toonday** [dask/dask#2121]
I get an error when I attempt to get diagnostics on the compute method.

    with Profiler() as prof, ResourceProfiler(dt=0.5) as rprof, CacheProfiler() as cprof:
        z = dask.delayed()(values)
        z.compute()

Dask version: 0.14
[error_call_stack.txt](https://github.com/dask/dask/files/871244/error_call_stack.txt)

**Comment by mrocklin** [comment]
Hi @toonday are you able to provide a minimal easy-to-run example that reproduces this error?

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if you can provide a reproducible test case.
