### ISSUE TITLE
Add abstraction layer for Parquet files to support multiple reader/writer libraries

### ISSUE THREAD

**Issue by wesm** [dask/dask#2127]
The IO implementation in `dask.dataframe.io.parquet` is coupled to fastparquet. I would like to enable users to elect to use `pyarrow.parquet` if it is available. This would work by writing:

`read_parquet(..., driver='pyarrow')`

or

`read_parquet(..., driver='fastparquet')`

This should also help encourage semantic conformity per discussion in #2113 

cc @cpcloud @jreback

**Comment by mrocklin** [comment]
I'm generally in favor.  Two questions:

1.  Dask usually delivers either bytes or objects that behave like Python files to data reading libraries.  I know that PyArrow works with proper CPython file objects.  Will it work with things that *look* like file objects but aren't?  Alternatively is there a cheap way to us Arrow's data ingestion layer here.  I suspect that this would be closer to bare-metal speed but also require more development work to start up.
2.  Dask.dataframe currently checks metadata to find a sorted column.  If it finds exactly one then it calls it the index.  Is parquet metadata exposed through PyArrow?

**Comment by wesm** [comment]
1. Yes, anything with a `read` method will suffice, but we have zero-copy reads from memoryview/buffer protocol now, which is faster: https://github.com/apache/arrow/commit/685ebf49001ef02134e404dddae2bfd032dc4a65

2. Some of the metadata is exposed but not what you're describing, but I don't think it will be difficult to add. Can you point me to this? 

Also, if you can point me to any representative workloads or sample code that I can use for testing while I'm developing a patch, that would be very helpful! Thanks

**Comment by mrocklin** [comment]
@martindurant is probably the person to ask regarding parquet in particular, but for Dask dataframe generally I tend to benchmark with the functions in `dd.demo`

### Purely numeric 

```python
import dask.dataframe as dd
df = dd.demo.daily_stock('GOOG', '2010', '2011', freq='100ms', 
                         random_state=1234)

>>> df
Dask DataFrame Structure:
                       close     high      low     open
npartitions=252                                        
2010-01-04 09:00:00  float64  float64  float64  float64
2010-01-05 09:00:00      ...      ...      ...      ...
...                      ...      ...      ...      ...
2010-12-31 09:00:00      ...      ...      ...      ...
2010-12-31 16:00:00      ...      ...      ...      ...
Dask Name: from-delayed, 504 tasks

df.to_parquet('goog.parquet')
```

### Mixed types

```python
df = dd.demo.make_timeseries('2010', '2011',
                             {'value': float, 'name': str, 'id': int},
                             freq='100ms', partition_freq='1D', seed=1)
>>> df
Dask DataFrame Structure:
                    id    name    value
npartitions=365                        
2010-01-01       int64  object  float64
2010-01-02         ...     ...      ...
...                ...     ...      ...
2010-12-31         ...     ...      ...
2011-01-01         ...     ...      ...
Dask Name: make-timeseries, 365 tasks
```

You should be able to play with partition size by repartitioning beforehand.

```python
df = df.repartition(freq='7d')
```

You'll probably want to persist in memory before writing and call `len` when reading.

```python
df = df.persist()  # this blocks until done (what you want) if using the single machine scheduler
df.to_parquet(...)
```

```python
%%time
df = dd.read_parquet(..., engine='pyarrow')
len(df)  # dask.dataframe is dumb, and so will go ahead and read all of the data for this
```

**Comment by mrocklin** [comment]
When constructing a dataframe ingestion function it's probably wise to look at the following functions:

- http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.from_delayed 
- http://dask.pydata.org/en/latest/bytes.html#dask.bytes.open_files

**Comment by wesm** [comment]
Very good. I'll start putting together a patch and keep you posted.

**Comment by jreback** [comment]
+1 on this, from pandas perspective we use ``engine`` rather than ``driver`` for spelling the back-end/impl. Not sure if this is common though.

**Comment by jcrist** [comment]
This is now completed, both `fastparquet` and `pyarrow` are supported for reading and writing operations as of #2868. Closing.
