### ISSUE TITLE
Adding FFT changes to docs

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2128]
There have been a few significant changes to use of FFTs in Dask. Figure this should enter the documentation somewhere. Opening this issue to figure out where this should live, how to include the API/docstrings in the docs, what examples to include, etc.

**Comment by mrocklin** [comment]
This would probably be a good start:
https://github.com/dask/dask/blob/master/docs/source/array-api.rst

**Comment by jakirkham** [comment]
Adding them to the API docs in PR ( https://github.com/dask/dask/pull/2136 ).
