### ISSUE TITLE
Automatic chunking depending upon platform

### ISSUE THREAD

**Issue by pwolfram** [dask/dask#2138]
Is there a plan to provide automatic chunking in dask, e.g., https://github.com/pydata/xarray/issues/1338?  This would be particularly helpful to make operation on different platforms more intuitive.

**Comment by mrocklin** [comment]
I agree that this would be useful.  I don't know how to do it.  What logic would we need to figure out to reliably automatically chunk dask arrays?

**Comment by pwolfram** [comment]
The error typically occurs on a compute step.  Is it possible to know the extent of the graph produced at that point and then rechunk prior to the computation?  I would expect at this point it is probably too late, is that correct?  

```python
# code block produces error if ds = ds.chunks(1e5) not used here
mean = ds.mean('Time')
mean.compute()
```

**Comment by pwolfram** [comment]
cc @shoyer

**Comment by mrocklin** [comment]
That is correct.  We do not know the history of computations that produced our graph.

**Comment by pwolfram** [comment]
Once we are at the mean step, which is a simple case, the limiting factor is the total chunk size for a particular variable in `ds`, which must be smaller than the total memory available at that time.

**Comment by pwolfram** [comment]
Ok, so this would imply that we would need to keep track of the symbolic computational stack in xarray then, would it not?  For instance, if we had the computational stack at the `mean.compute()` point and not just the dask graph we could sort this out prior to building the dask graph, correct?

**Comment by shoyer** [comment]
As has come up before, doing this as the compute step really requires a graph based representation for whole-array operations before dividing into chunks. This would be another level of abstraction between xarray and dask.

This would certainly be highly useful, but would also require significant effort.

@mrocklin has noted that his Blaze project contained such an array object, but it's probably still pretty far from feature complete.

**Comment by mrocklin** [comment]
It depends what you think of as feature complete.  If you only care about the expression building parts of Blaze and not the "compile to anything" parts it's a not-terrible project.

```python
In [1]: import blaze as bz

In [2]: x = bz.Symbol('x', '1000 * 2000 * real')

In [3]: y = (x.dot(x.T) - 1)[::2].mean(axis=1)

In [4]: y
Out[4]: mean((tensordot(x, transpose(x))) - 1[::2], axis=(1,))

In [5]: y.dshape
Out[5]: dshape("500 * float64")

In [6]: y = (x.dot(x.T) - 1)[5::3].mean(axis=1)

In [7]: y.dshape
Out[7]: dshape("332 * float64")
```

**Comment by shoyer** [comment]
Agreed, adding wrappers for the majority of `dask.array` operations to construct the graph (at least those used by xarray) would probably not be terribly difficult.

**Comment by mrocklin** [comment]
I find that the challenge here is more that you'd have to add another layer into the mix.  I don't think that XArray is likely to add in blaze arrays that then go down to dask arrays that then use numpy arrays.  Indirection has costs.

So far the solution to this problem has been to tell people to think about their chunk sizes.  So far this has worked ok.  I think that it might fail if we try to reach out to a broader population.

**Comment by pwolfram** [comment]
@mrocklin is correct.  Our group had an issue related to that this week and I mistook an error in our analysis for something greater than a chunking error.  It wasn't immediately obvious, and I've seen these problems before, that the dask memory error was strictly caused by a chunking failure.  

The fundamental problem is that computations change as the problem size is bigger and naive code developed on a small problem size just doesn't immediately scale without handling this chunking issue.  Even something as simple as changing the error message to indicate chunking may be to blame would go a long way.  

But, my apologies to you both because this definitely has the flavor of a newbie question.

**Comment by mrocklin** [comment]
I think it's more of a fundamental core question of the libraries personally.  It's just not one that we're able to solve except that great cost.  

I like the idea of partially-solving this through feedback.  Thoughts on what would help?  Are you on the single-machine or distributed scheduler?

**Comment by pwolfram** [comment]
We are on the single-machine scheduler right now although I wouldn't be surprised if we end up on the distributed scheduler before the year is out to complete our analysis.  We are already in the task-parallelism weeds (https://github.com/MPAS-Dev/MPAS-Analysis/pull/112).

The challenge we are having fundamentally is trying to keep the learning curve down for scientist involvement in the analysis package.  Issues like https://github.com/MPAS-Dev/MPAS-Analysis/issues/161 that crop up make this cost too high for many.  But, this is at least partially due to our pace of development on this repository so this problem may dissolve over time.

**Comment by mrocklin** [comment]
I can imagine putting some sort of global plugin mechanism into the `da.Array` constructor so that people could run checks automatically.  This would allow you to err or warn loudly if very large chunks ended up occurring.

**Comment by shoyer** [comment]
> I can imagine putting some sort of global plugin mechanism into the da.Array constructor so that people could run checks automatically.

This would also be useful for a "Debug" mode for dask array, where every array is evaluated eagerly before creating a new array with the same shape (effectively automatically calling `.persist()` after every array operation)

**Comment by jcrist** [comment]
With the addition of array constructor plugins to provide checks and warnings in #2142, is this issue resolved?

**Comment by shoyer** [comment]
Array constructor plugins are nice, but I don't think they solve the automatic chunking problem. At best they are a partial solution.

**Comment by mrocklin** [comment]
Are we likely to solve the larger problem?

**Comment by shoyer** [comment]
Probably not in dask :)

**Comment by mrocklin** [comment]
Then should we close?

**Comment by pwolfram** [comment]
In https://github.com/pydata/xarray/issues/1338 we decided to move this issue to dask.  

Is the overall decision here that right now the problem is simply too hard to come up with some type of reasonable solution?  This seems to be the general consensus and it jives with my intuition but I just wanted to double-check.  I'm happy to close if we agree.

**Comment by shoyer** [comment]
Well, this is a real usability problem for both xarray and dask, even if the solution will require a separate project. So I suspect this is likely to come up again.

I'd be happy to leave this open for discussion (makes thing slightly easier to find) but it's up to you (@mrocklin) on how you want to manage this project.

**Comment by mrocklin** [comment]
I'm happy to leave it open if it's useful.  If it's still open and
untouched a year from now then we might consider closing then?

**Comment by TomAugspurger** [comment]
It's been a year, and we now accept `'auto'` in `rechunk` :)

How well is the original use case from https://github.com/pydata/xarray/issues/1338 solved? It's not automatic, but perhaps the user has enough tools now?

**Comment by mrocklin** [comment]
The original request was, I think, to rechunk retrospectively based on computations.  This is out of scope for dask array.  Some other project could take it on though.  Closing.

**Comment by shoyer** [comment]
Yes, agreed
