### ISSUE TITLE
partd directories are not always cleaned up

### ISSUE THREAD

**Issue by moody-marlin** [dask/dask#2139]
Whenever `dask.DataFrame` performs certain operations, temporary `.partd` directories are created; however, in the presence of certain errors, these temporary directories are never cleaned up.  This can be a big problem on shared servers with limited `/tmp/` space, or if you aren't aware that it's happening.  

For example, `dd.merge()` eventually [creates a `.partd` directory](https://github.com/dask/dask/blob/master/dask/dataframe/shuffle.py#L224) but during the actual merge / shuffle, a `MemoryError` might get thrown and the (usually large) `.partd` directory is never cleaned.  

Here's a reproducible example that mocks up the situation by mocking [this line](https://github.com/dask/dask/blob/master/dask/dataframe/shuffle.py#L228):

```
In [1]: import dask.dataframe as dd; import os

In [2]: [folder for folder in os.listdir(os.environ['TMPDIR']) if 'partd' in folder]
Out[2]: []

In [3]: A = dd.demo.daily_stock('GOOG', '2010', '2011', freq='1d')

In [4]: dd.shuffle.shuffle_group_3 = lambda x: x

In [5]: dd.merge(A, A, on='close').head()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-97a9ff784554> in <module>()
----> 1 dd.merge(A, A, on='close').head()

//anaconda/lib/python3.5/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    795 
    796         if compute:
--> 797             result = result.compute()
    798         return result
    799 

//anaconda/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     93             Extra keywords to forward to the scheduler ``get`` function.
     94         """
---> 95         (result,) = compute(self, traverse=False, **kwargs)
     96         return result
     97 

//anaconda/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    200     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    201     keys = [var._keys() for var in variables]
--> 202     results = get(dsk, keys, **kwargs)
    203 
    204     results_iter = iter(results)

//anaconda/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

//anaconda/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    498                     _execute_task(task, data)  # Re-execute locally
    499                 else:
--> 500                     raise(remote_exception(res, tb))
    501             state['cache'][key] = res
    502             finish_task(dsk, key, state, results, keyorder.get)

TypeError: <lambda>() takes 1 positional argument but 4 were given

Traceback
---------
  File "//anaconda/lib/python3.5/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "//anaconda/lib/python3.5/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)


In [6]: [folder for folder in os.listdir(os.environ['TMPDIR']) if 'partd' in folder]
Out[6]: ['tmpqk5joscj.partd']
```

Related to this, it might be nice to elevate / expose the `path` keyword argument in `partd.File.__init__()` in some way so that users don't have to know to set `TMPDIR` and `TMP` environment variables.

**Comment by mrocklin** [comment]
@pitrou is there a mechanism that you would recommend to reliably clean up this temporary directory after all references to it are removed?  I tend to use the `atexit` module for this but I recall you using something recently that was more associated to an object than to a session.

**Comment by pitrou** [comment]
The simple solution is a `try .. finally` block. Otherwise, `tempfile.TemporaryDirectory` is an option. It only exists on Python 3 but the source code is simple enough that it shouldn't be a problem backporting it on Python 2 (it uses `weakref.finalize` which is already backported in Distributed):
https://github.com/python/cpython/blob/master/Lib/tempfile.py#L777

Do note that if `MemoryError` was raised, perhaps the Python process will not be able to allocate enough memory to actually run the directory deletion routine...

**Comment by mrocklin** [comment]
I don't think that we can use a context manager here.  We create an object in one task that then gets used by other tasks in other threads.  I think it's better to tie the lifetime of the directory to an object or to a process.
