### ISSUE TITLE
Add convolve

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2147]
Would be nice to have an N-D convolution function like SciPy Signal's [`convolve`]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html ).

**Comment by mrocklin** [comment]
This would only make sense, I think, for the direct method where the second input is a small numpy array.

**Comment by jakirkham** [comment]
It's a good point. Also in some cases FFTs are more performant. So we may want to have `fftconvolve` as well. Though this note in the `fftconvolve` documentation is of interest.

> As of v0.19, convolve automatically chooses this method or the direct method based on an estimation of which is faster.

ref: https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.signal.fftconvolve.html

**Comment by jakirkham** [comment]
Am adding PR ( https://github.com/jakirkham/dask-ndfilters/pull/18 ) to `dask-ndfilters` for N-D convolutions. Not exactly the same thing as this, but it is related.

**Comment by jakirkham** [comment]
Going to close as similar behavior is already handled by [`dask-ndfilters`]( https://github.com/dask-image/dask-ndfilters ). A 0.1.0 release for `dask-ndfilters` is already on PyPI and work on a conda-forge package is in progress. Contributions welcome. 😄
