### ISSUE TITLE
Add tile

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2151]
Would be great to have the `tile` function (like NumPy's [`tile`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html ))  added to Dask Array. This is a nice complement to `repeat`, which is already present.

**Comment by mrocklin** [comment]
I'm generally in favor

**Comment by jakirkham** [comment]
Have a WIP proposal for this in PR ( https://github.com/dask/dask/pull/2153 ).
