### ISSUE TITLE
Appending categoricals fails with to_parquet

### ISSUE THREAD

**Issue by wikiped** [dask/dask#2174]
Trying to append data to an existing parquet hive where some columns are stored as dictionaries (originating from categoricals):

    import pandas as pd
    import fastparquet as fp
    from dask import dataframe as dd

    DATA_SIZE = 100
    alphas = ['q'] * DATA_SIZE
    cats = ['w'] * DATA_SIZE
    ints = [3] * DATA_SIZE
    flts = [3.] * DATA_SIZE
    df = pd.DataFrame({'a': alphas, 'c': cats, 'i': ints, 'f': flts})
    df['c'] = df['c'].astype('category')

    ddf = dd.from_pandas(df, npartitions=1)

    ddf.to_parquet('parquet_hive', compression='snappy', write_index=False)
    
This succeeds:

    fp.write('parquet_hive', data=df, compression='snappy', write_index=False, append=True, file_scheme='hive')
    
This fails:

    ddf.to_parquet('parquet_hive', compression='snappy', write_index=False, append=True)

With:

    ValueError: Appended dtypes differ.
    {('c', category), ('c', dtype('O'))}

As parquet does not store dtype `'category'` this creates obvious problem.
Currently dtype check is done [via](https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L263):

    ...
    elif set(pf.dtypes.items()) != set(df.dtypes.iteritems()):
        raise ...
        

Since `fastparquet` does check for schema compatibility is there really a need for a dtype check here?

If there is a need it seems to require a separate algo/function for checking dtypes to ensure that `'category'` == `'O'`...

**Comment by martindurant** [comment]
Seems to be working in latest master versions of dask and fastparquet. fastparquet now automatically infers whether a column was created from categoricals (if it was written with dask and/or fastparquet in the first place), and they show up with dtype=category.

**Comment by wikiped** [comment]
Thank you. I can confirm that after upgrading `fastparquet` to master on github (reported `__version__` is `0.0.5`) the issue is gone.
