### ISSUE TITLE
Investigate MPI compatability.

### ISSUE THREAD

**Issue by cowlicks** [dask/dask#218]
It might be useful to have mpi4py be swapable with pyzmq. We'd be able to use dask on clusters with infiniband. And we'd deployment with mpiexec (ref #186). Currently our performance is probably not limited by our message passing library, so we do not expect a significant speed increase.

If anyone has interest in this please let us know.

**Comment by gabrielelanaro** [comment]
That feature would be pretty useful as all supercomputers in worked on had great support for mpi but not much else. Right now I'm using hdf5 format for data communication and mpi4py for my analysis, you can imagine the pain.

**Comment by cowlicks** [comment]
@gabrielelanaro Thanks for the feedback. Can you use zmq on your cluster? Have you tried using dask.distributed on it? :)

Off the top of my dask needs to:

* Wrap everything we use from zmq a module, this won't be too hard.
* wrap mpi4py with a to provide a similar interface
* wrapping mpi4py for things like sends and receives should be easy
* I'm not sure what is analogous to zmq sockets in mpi4py.

**Comment by gabrielelanaro** [comment]
I didn't manage to setup zmq or anything else on the cluster (PBS scheduling system).

The main problem is that (as far as my understanding goes) you are allowed to run a script that launches mpiexec, and mpiexec is configured such as it gets run on the proper cores in the proper nodes. So you can't control multiple nodes (except through mpi) .

**Comment by gabrielelanaro** [comment]
Basically you mean implementing the Scheduler/Client architecture with mpi4py?

**Comment by mrocklin** [comment]
One could use mpiexec to deploy the scheduler and workers

```python
if rank == 0:
    from dask.distributed import Scheduler
    s = Scheduler(...)
else:
    from dask.distributed import Worker
    w = Worker(...)
```

and then let them communicate with each other over zeromq.  ZeroMQ isn't that heavyweight and is fairly low-level.  It feels like the kind of library super-computer sysadmins might appreciate.

Just to be clear though, the communication patterns in `dask.distributed` aren't designed for high performance computing.  Just getting MPI into dask.distributed is unlikely to change performance.

**Comment by cowlicks** [comment]
@gabrielelanaro Yes, basically making dask.distributed agnostic to the message passing library you use.

Also @mrocklin, is correct. The bottlenecks in `dask.distributed` are not our message passing library. I edited the issue to reflect this.

**Comment by mrocklin** [comment]
We're unlikely to devote serious resources towards MPI compatibility.  If so it would probably be as a Tornado IOStream and separate from this project.  Closing.
