### ISSUE TITLE
daily_stock doctest failing

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2188]
Seeing this failure even in builds with relatively benign changes like this [build]( https://travis-ci.org/dask/dask/jobs/219864165#L3338-L3362 ).

```python
_________________ [doctest] dask.dataframe.io.demo.daily_stock _________________
156         The frequency of sampling
157     data_source: str, optional
158         defaults to 'yahoo'.  See pandas_datareader.data.DataReader for options
159     random_state: int, np.random.RandomState object
160         random seed, defaults to randomly chosen
161 
162     Examples
163     --------
164     >>> import dask.dataframe as dd
165     >>> df = dd.demo.daily_stock('GOOG', '2010', '2011', freq='1s')
UNEXPECTED EXCEPTION: ImportError('No module named pandas_datareader',)
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs
  File "<doctest dask.dataframe.io.demo.daily_stock[1]>", line 1, in <module>
  File "/home/travis/build/dask/dask/dask/dataframe/io/demo.py", line 186, in daily_stock
    from pandas_datareader import data
ImportError: No module named pandas_datareader
/home/travis/build/dask/dask/dask/dataframe/io/demo.py:165: UnexpectedException
```

**Comment by mrocklin** [comment]
We should either pip install pandas_datareader or skip that doctest.  Why
did this just start happening now?

**Comment by jakirkham** [comment]
Unclear. Also not seeing it any more. Should we close this or would you like to keep it open for adding the dependency?

**Comment by jakirkham** [comment]
Actually this was already [being installed]( https://github.com/dask/dask/blob/33d7a791d9d4a103ff46c237844cf16fcc2b8a68/continuous_integration/travis/install.sh#L74 ). So maybe this was similar to what we saw with `pytest` ( https://github.com/dask/dask/issues/2189 ). In any event, there is nothing actionable here FWICT and the problem is no longer appearing. So closing it out.
