### ISSUE TITLE
Graphviz tests failing

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2191]
Appears something [bad]( https://travis-ci.org/dask/dask/jobs/220110435#L3477-L3919 ) is happening to the `graphviz` tests. Seeing some [strange downgrading]( https://travis-ci.org/dask/dask/jobs/220110435#L317-L328 ) that is going along with it, which is more than likely the problem.

**Comment by jakirkham** [comment]
Opened an issue at the graphviz feedstock to see if anyone else has ideas as to what is going wrong.

xref: https://github.com/conda-forge/graphviz-feedstock/issues/14

**Comment by jakirkham** [comment]
It's actually very strange that we are having this issue because `python-graphviz` just ran and tested out fine at conda-forge several hours ago as shown in PR ( https://github.com/conda-forge/python-graphviz-feedstock/pull/6 ). 😕

**Comment by jakirkham** [comment]
This is showing up in `master` now too as demonstrated by this [build]( https://travis-ci.org/dask/dask/builds/220248227 ). Note that the previous [build]( https://travis-ci.org/dask/dask/builds/220012355 ) passed and both are cron jobs running on the same commit.

**Comment by jakirkham** [comment]
Alright, this [looks suspicious]( https://travis-ci.org/dask/dask/jobs/220248228#L290 ) to me. It seems that `matplotlib` is being pulled in from `defaults` instead of `conda-forge`. Maybe having something to do with the NumPy 1.10 requirement. It's also an older copy of `matplotlib`. Also the fact that [`qt`]( https://travis-ci.org/dask/dask/jobs/220248228#L296 ) is coming from `defaults` is a bit suspicious.

**Comment by mrocklin** [comment]
OK, this would be a good reason to drop testing for 1.10 I think

**Comment by jakirkham** [comment]
At a bare minimum, we could move the Graphviz tests to a different build like the Python 2.7 NumPy 1.12 one.

**Comment by mrocklin** [comment]
Eh, you were keen on dropping the older version anyway.  If it's going to
start interfering with the build process then that seems like reason
enough.  I'd like to avoid maintenance confusion if possible.  I wouldn't
be surprised if requiring numpy 1.10 causes other version issues as well
down the line.

**Comment by jakirkham** [comment]
So this is interesting. If I move `bokeh`, which is pulling in `matplotlib` as it is a dependency, then it seems we actually get the right set of things installed. ( https://github.com/dask/dask/pull/2193 ) Now I would have expected the set of dependencies I see pulled in now to have occurred before. Interestingly I'm [not the first]( https://github.com/dask/dask/commit/5513f3b1fdfc3147e5ae2e97988901505b4b86d7#diff-88105215154efaee464e9bb1002f9579R11 ) to see this strange behavior.

I expect this is happening because `conda` is not respecting the channel used for already installed dependencies. Hence why it is so willing to replace so many things with packages from `defaults` We could probably fix this by setting the `.condarc` with a specific channel order. Though it would also be nice if `conda` was a little more aware and respectful of the install history.

cc @jcrist

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/conda/conda/issues/5027 ) to discuss minimizing the number of package changes that occur as part of the solve. Expect this would help avoid problems like the one seen here.

**Comment by electronwill** [comment]
You may have seen this already but this page talks some about channel order on .condarc: https://conda.io/docs/channels.html
