### ISSUE TITLE
Control optimizations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2206]
Optimizations can be either critical or dead weight, depending on the application.  As people depend more strongly on Dask collections they increasingly ask for ways to modify the optimization process.  This results in us adding various hidden options like `fuse_ave_width=...` or globals.  

How do we sensibly enable power users to tweak the optimization process?

cc @eriknw @jcrist @shoyer

**Comment by mrocklin** [comment]
## Optimizations as data structures 

I think that in early versions users could pass a list of optimization passes like `[cull, fuse, optimize_slices]` and the graph and keys would be passed through each successively.  This was easy to understand and cheap to maintain.  However as optimizations have become more complex and have started to share intermediate state a simple list data structure no longer makes sense.  
 
However we could still go this route of using a data structure, it would just have to be more complex.  Two thoughts come to mind:

1.  Allow the user to register optimization functions per collection

        dask.optimization.register(da.Array, my_optimization_function)

    I suspect that this may be equivalent to just doing the following today:

        da.Array._optimize = my_optimization_function

2.  We could define the optimization pass as a dask graph.  This seems fun and would allow for composition.  I'm not sure if it's actually pragmatic though.

**Comment by mrocklin** [comment]
Perhaps when calling compute we specify an optimization suite, something like the following:

```python
optimizations = {
  da.Array: my_optimize_function,
  dd.DataFrame: False
}
compute(a, b, optimize_graph=optimizations)
```

**Comment by jcrist** [comment]
Just to clarify, would that replace the optimizations for those collections? Since the ordering of optimization passes is critical and they don't *exactly* chain together in a uniform way, I think the most pragmatic thing would be to only allow replacement, and worry later about composition.

The syntax you suggest above sounds good. If we wanted a global/fixed option as well, perhaps registering on the class would make more sense than in `context._globals`? Not sure.

**Comment by mrocklin** [comment]
Yes, these would replace.

I slightly prefer using context._globals over modifying the class.  They both have the problems of global state but `context._globals` at least has a context manager.  I suspect that users could monkey-patch things now on the class if they wanted to.
