### ISSUE TITLE
Rename Bag

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#222]
Should we rename dask.bag?  Technically the name is quite accurate as, mathematically, a bag is an unordered collection with repeats.  This is exactly the abstraction that dask.bag implements.

However this name is not particularly attractive, especially for those unfamiliar with the mathematical meaning.  Should we rename it?

Some options

*  collection
*  list
*  multiset
*  ...

There are decent reasons for and against all of those, and presumably many other excellent options.  Suggestions welcome.

**Comment by bryevdv** [comment]
`list` is inaccurate, `collection` is vague. +1 for `multiset` which AFAIK is an actual synonym,  Also +100 for renaming.

**Comment by cowlicks** [comment]
My initials are BAG and I don't particularly like them either.

**Comment by mrocklin** [comment]
I think that we're probably cemented on bag for now.  Closing.
