### ISSUE TITLE
Alternatives to handling Dask DataFrame metadata

### ISSUE THREAD

**Issue by wesm** [dask/dask#2221]
Currently, we have

```
    meta: pandas.DataFrame, pandas.Series, or pandas.Index
        An empty pandas object with names, dtypes, and indices matching the
        expected output.
```

There's a few possible issues with this approach -- I am curious how they're currently being dealt with.

1) This is a somewhat complicated way to transport a schema. What would you think about defining a "real" schema data structure `dask.dataframe.Schema`? This would allow for more extensible type validation and conforming (e.g. we could represent the "maybe int64" type, see the next point)

2) The Series or DataFrame dtypes are often impossible to know until you load the data. For example, if you're loading a Parquet file, the file metadata may say INT64, but the pandas dtype may be float64 due to nulls. Same for booleans

I originally started looking into this because of the `ParquetFile._dtypes` function used in `dask.dataframe.io.parquet`: https://github.com/dask/fastparquet/blob/master/fastparquet/api.py#L374

For example:

```python
        for col, dt in dtype.copy().items():
            if dt.kind in ['i', 'b']:
                # int/bool columns that may have nulls become float columns
                num_nulls = 0
                for rg in self.row_groups:
                    chunks = [c for c in rg.columns
                              if c.meta_data.path_in_schema[-1] == col]
                    for chunk in chunks:
                        if chunk.meta_data.statistics is None:
                            num_nulls = True
                            break
                        if chunk.meta_data.statistics.null_count is None:
                            num_nulls = True
                            break
                        num_nulls += chunk.meta_data.statistics.null_count
                if num_nulls:
                    dtype[col] = np.dtype('f%i' % max(dt.itemsize, 2))
```

In the event that someone has written file statistics (which are optional) and there are nulls, setting float dtype is correct, but the data may all be non-null integers, but we won't know until reading the file. Here, if there are no file statistics, then the dtype is set defensively to float just in case.

Thoughts on ways to improve the API for thirdparty "ingesters"  of dask.dataframe data? 

cc @jreback @cpcloud @mrocklin @martindurant 

xref #2177 #2127

**Comment by martindurant** [comment]
Quick comment:
"In the event that someone has written file statistics (which are optional) and there are nulls, setting float dtype is correct, but the data may all be non-null integers, but we won't know until reading the file." - you wouldn't know whether there were any nulls until you had read *all* of the chunks you are interested in, which of course may be in several files.

**Comment by wesm** [comment]
Right, the idea is to have a schema that can accommodate pandas's "lossy" dtypes -- so a column might be int64 in some partitions, but float64 in others. And these would be considered to be the conforming to the schema

**Comment by jreback** [comment]
This is exactly the same problem we have (now) in reading csv's via chunking, or really anytype of inference engine, you don't know until you have fully read it if you can coerce to a better dtype.

Its actually not that expensive to check even now (and of course this would actually raise in the astype if its *not* convertible.

```
In [1]: arr = np.arange(1000000.)

In [3]: %timeit (arr == arr.astype('int64', copy=False)).all()
100 loops, best of 3: 3.48 ms per loop
```

**Comment by mrocklin** [comment]
For questions like these my inclination is almost always to divert the problem to the in-memory library.  In this case I would recommend that Pandas itself maintain a Schema attribute so that it can faithfully roundtrip metadata like maybe-int64.  I agree with the motivations raised above, but suspect that they would apply equally well to Pandas as to Dask.dataframe.

Dask.dataframe generally just follows Pandas, both for good and for bad.  This practice has greatly simplified maintenance on our end.  The Pandas community is, I think, generally better equipped to maintain this sort of thing, both in developer-power and in experience.

**Comment by mrocklin** [comment]
Is there any further discussion to be had here?

**Comment by wesm** [comment]
Using an empty object as a proxy for a true schema-like data structure is a little bit janky. I'm not sure what are actionable steps to build something better. Perhaps pandas 0.x can define type metadata to model the current semantics (with mappings on-demand to a list of NumPy dtype objects for the physical storage), a sort of `pandas_schema` add-on library (so Dask doesn't need to block on a release of the pandas monolith to get this new functionality)

**Comment by mrocklin** [comment]
>  Using an empty object as a proxy for a true schema-like data structure is a little bit janky.

In general I agree.  However in practice this practice has been tremendously helpful in this case.  For example this helps us track subtle changes in Pandas very nicely across versions as operations exhibit behavior differences.

**Comment by mrocklin** [comment]
Discussion seems to have stopped.  Closing.  I think we're going to leave this decision with upstream.
