### ISSUE TITLE
Index column inference issues in read_parquet

### ISSUE THREAD

**Issue by wesm** [dask/dask#2222]
I'm working on #2127. The default behavior when not passing the `index` argument is to infer the index based on the presence of any sorted columns. This can lead to some unpredictable behavior. Let me give some examples:

```python
import dask.dataframe.io.parquet as ddp
import dask.dataframe as dd
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'a': range(5), 'b': range(5)})
df2 = pd.DataFrame({'index': range(5), 'a': range(5), 'b': range(5)})

df1 = dd.from_pandas(df1, npartitions=5)
df2 = dd.from_pandas(df2, npartitions=5)

ddp.to_parquet('test1', df1)
ddp.to_parquet('test2', df1, write_index=False)
ddp.to_parquet('test3', df2, write_index=False)
ddp.to_parquet('test4', df2)
```

Now, `test1` returns what we put in automatically:

```python
>>> ddp.read_parquet('test1').compute()
       a  b
index      
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
```

`test2` errors:

```python
>>> ddp.read_parquet('test2').compute()
ValueError: Multiple possible indexes exist: ['a', 'b'].  Please select one with index='index-name'
```

To get `test3` back, you have to pass `index=False`

```
>>> ddp.read_parquet('test3', index=False).compute()
   a  b  index
0  0  0      0
0  1  1      1
0  2  2      2
0  3  3      3
1  4  4      4
```

`test4` has artifacts of a MultiIndex regardless of what you pass:

```python
>>> ddp.read_parquet('test4').compute()
       level_0  a  b
index               
0            0  0  0
1            1  1  1
2            2  2  2
3            3  3  3
4            4  4  4

>>> ddp.read_parquet('test4', index=False).compute()
   level_0  a  b  index
0        0  0  0      0
0        1  1  1      1
0        2  2  2      2
0        3  3  3      3
1        4  4  4      4
```

Having this index inference behavior turned on by default seems like a recipe for problems like these. Having more explicit code like:

```
ddp.read_parquet('test1', index='index')
ddp.read_parquet('test1', infer_index=True)
ddp.read_parquet('test2')
ddp.read_parquet('test3')
```

would likely lead to an overall better user experience.

There's a separate issue we should discuss, which is how the index column is written to Parquet. It would be _much_ better to use a unique identifier for the column name (to avoid conflicts like above) and store key value metadata so we can recover the index from the Parquet file precisely 100% of the time.

**Comment by wesm** [comment]
As an aside, I don't think using column statistics to infer the index is a good idea at all: I would rather we decide on a convention for storing pandas metadata in the Parquet file metadata and use that -- less brittleness, and more predictable behavior.

**Comment by mrocklin** [comment]
If we can store pandas-specific metadata in Parquet then I'm entirely in favor of that.  I think that that's best when we're roundtripping data from Pandas-like systems to Pandas-like systems.

In practice I haven't yet run into a problem with index inference have so far found it pretty convenient.  However we haven't gotten very much exposure to Parquet yet, so my confidence level is low.  I'm open to turning off magic, but I think that we should probably make this decision after we have more understanding of use.  To me it's not yet clear where the convenience to predictability tradeoff line is.  

Something to be aware of is that setting the index ahead-of-time is *very* important to Dask.dataframe.  Much more so than it was to Pandas (where it is still pretty important.)  The index provides order-of-magnitude speed improvements in some cases (timeseries operations, groupby-applys, joins) and can take a long while to change if not set initially.

**Comment by wesm** [comment]
That's totally fine, and won't impact the construction of the dask.dataframe. I think we should use the custom metadata support we have at our disposal in Parquet rather than making a guess; if that were not an option then the best efforts inference (similar to pandas.read_csv) would be the thing to do. 

Part of why I'm raising the issue is that I'd like the metadata to be the same regardless of who wrote the file, to files written by fastparquet will be readable in pyarrow and vice versa. This is related to #2113 also

**Comment by mrocklin** [comment]
> I think we should use the custom metadata support we have at our disposal in Parquet rather than making a guess; if that were not an option then the best efforts inference (similar to pandas.read_csv) would be the thing to do.

Sounds good to me.  

Is there a good place for conversation about Pandas-specific Parquet metadata?  This might interest @martindurant for fastparquet if so.

**Comment by xhochy** [comment]
Personally I would chose the file format (mailing list) as the base for the discussion for storing the metadata if we also would like to ensure that e.g. also R users would in future benefit. Then this must be addressed and standardised inside the format itself.

Otherwise as we only focus on constructing Pandas-specific metadata, I would think that this issue should actually be discussed as part of the Pandas community/mailing list/tracker. As far as I know, for Parquet files that were built from AVRO records, inside these files the actual AVRO schema is stored in the metadata thus ensuring optimal reconstruction of the data if they are back into AVRO records again.

For Pandas it would be nice if we could also have a textual representation of the schema of the DataFrame. Thus we could simply persist it (with maybe some additions to overcome shortcomings of various formats) and use it for inferring indices, categoricals and so on if we load the file again into Pandas. This solution would not also solve the problem discussed here but also help with e.g. Apache Arrow or other serialization formats.

**Comment by wesm** [comment]
Since this is pandas specific, I'll open an issue there to discuss and we can start a general document about embedding pandas metadata in file formats.

**Comment by wesm** [comment]
see https://github.com/pandas-dev/pandas/issues/16010

**Comment by wesm** [comment]
We just merged (https://github.com/apache/arrow/commit/bed01974321d9d1edeae9e474bd9df020b42ea10) support for reading and writing the index using the metadata as being described in https://github.com/pandas-dev/pandas/issues/16010 and PR https://github.com/pandas-dev/pandas/pull/16315. As soon as fastparquet can write and read this metadata, we should be able to do some scrubbing in `dask.dataframe.io.parquet` and get cross-compatibility tests between fastparquet and pyarrow. Anything we can do in the meantime? Hopefully we'll close out the pandas PR today

**Comment by martindurant** [comment]
I will start work on the fastparquet side of this today, but I don't know how long it will take. 

On an related note, I am wondering about categoricals. From dask's point of view, for a given categorical column, the partitions may have the same category labels or not: for instance, if created from a pandas dataframe, the labels are guaranteed to be the same in each partition, but if reading from csv, each partition will generally have different labels.
Writing this to parquet is all fine: when loading back in, the labels can vary partition to partition and dask copes with this. What should happen if this same parquet dataset is loaded directly into pandas? Presumably we don't want to do a category merge and recode.

**Comment by wesm** [comment]
Global dictionaries are difficult -- Apache CarbonData recently implemented one approach, but it is dependent on using Spark to pre-compute a global dictionary. With Parquet, encoders may also fall back to plain encoding for large dictionaries I think the software needs to be robust to having different categories in different partitions.

For the metadata wrangling, you can possible crib https://github.com/apache/arrow/blob/master/python/pyarrow/pandas_compat.py to help go faster. We need to make another patch on this now that the spec has been finalized

**Comment by martindurant** [comment]
See https://github.com/dask/fastparquet/pull/151 for a start on this. I have not yet decided how to fold this through to the dask side.

**Comment by wesm** [comment]
Arrow 0.4.0 is about to release including these changes. The sooner we can get this integrated into Dask the better in case there are implementation discrepancies that need to be fixed. Let me know how I can help -- @cpcloud or @jreback may be able to help also

**Comment by martindurant** [comment]
Please have a look through https://github.com/dask/fastparquet/pull/151 to see if I am doing things in a reasonable manner, that would be the biggest help.
