### ISSUE TITLE
Problem with working with large numpy arrays using Dask

### ISSUE THREAD

**Issue by mkhoshle** [dask/dask#2227]
I am trying to load bunch of Numpy arrays from .npy, .npz files (512 MB total) and I create larger arrays from them by stacking them and the size of my final array would be (2GB). I am trying to perform some calculations on this arrays using dask distributed on a cluster. When I use smaller file sizes than 512 MB my code works fine. But for larger ones I get the following error: 

```tornado.application - ERROR - Exception in callback None
Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
  handler_func(fd_obj, events)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
  return fn(*args, **kwargs)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 511, in _handle_events
  self._handle_read()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 655, in _handle_read
  self._read_from_buffer(pos)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 770, in _read_from_buffer
  self._run_read_callback(pos, False)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 679, in _run_read_callback
  future.set_result(self._consume(size))
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 879, in _consume
  _merge_prefix(self._read_buffer, loc)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/iostream.py", line 1543, in _merge_prefix
  deque.appendleft(type(prefix[0])().join(prefix))
MemoryError```

```
and also 
```

```distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/protocol/core.py", line 112, in loads
  fs = merge_frames(head, fs)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/protocol/utils.py", line 74, in merge_frames
  out.append(b''.join(map(ensure_bytes, L)))
MemoryError
distributed.worker - ERROR -
Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/worker.py", line 1051, in compute_stream
  msgs = yield comm.read()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
  value = future.result()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
  raise_exc_info(self._exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
  yielded = self.gen.send(value)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/tcp.py", line 161, in read
  msg = from_frames(frames, deserialize=self.deserialize)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/utils.py", line 27, in from_frames
  return protocol.loads(frames, deserialize=deserialize)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/protocol/core.py", line 112, in loads
  fs = merge_frames(head, fs)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/protocol/utils.py", line 74, in merge_frames
  out.append(b''.join(map(ensure_bytes, L)))
MemoryError```


```
When I looked at issue tracker with similar issues, I thought this maybe the problem with python 2. So I created a conda environment with python 3.5.3. But then I got the following error:

```


```tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x2aad51aa55c0> exception was never retrieved: Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
  yielded = self.gen.send(value)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/core.py", line 235, in handle_comm
  op = msg.pop('op')
KeyError: 'op'```


```
I am checking the version of python on client, scheduler, Workers using client.get_versions(check=True), and here is what I get:

```

```{'client': {'packages': {'optional': [('numpy', '1.12.1'), ('pandas', '0.19.2')], 'required': [('dask', '0.14.1'), ('distributed', '1.16.1'), ('msgpack', '0.4.8'), ('cloudpickle', '0.2.2'), ('toolz', '0.8.2')]}, 'host': [('python', '3.5.3.final.0'), ('python-bits', 64), ('OS', 'Linux'), ('OS-release', '2.6.32-642.13.1.el6.x86_64'), ('machine', 'x86_64'), ('processor', 'x86_64'), ('byteorder', 'little'), ('LC_ALL', 'None'), ('LANG', 'en_US.UTF-8'), ('LOCALE', 'en_US.UTF-8')]}, 'scheduler': {'packages': {'optional': [['numpy', '1.12.1'], ['pandas', '0.19.2']], 'required': [['dask', '0.14.1'], ['distributed', '1.16.1'], ['msgpack', '0.4.8'], ['cloudpickle', '0.2.2'], ['toolz', '0.8.2']]}, 'host': [['python', '3.5.3.final.0'], ['python-bits', 64], ['OS', 'Linux'], ['OS-release', '2.6.32-642.13.1.el6.x86_64'], ['machine', 'x86_64'], ['processor', 'x86_64'], ['byteorder', 'little'], ['LC_ALL', 'None'], ['LANG', 'en_US.UTF-8'], ['LOCALE', 'en_US.UTF-8']]}, 'workers': {}}```

```
I can see that the workers are started on each node but I do not understand why nothing is being shown for workers? Any idea of why this is happening?
```

**Comment by jcrist** [comment]
Apologies for letting this sit for so long.

> When I use smaller file sizes than 512 MB my code works fine. But for larger ones I get the following error:

Dask should work fine here, even for large chunk sizes. Indeed, we can compute on arrays with chunks this large, and submit tasks to the scheduler with arguments this large:

```python
In [1]: from dask.distributed import Client

In [2]: c = Client('tcp://10.10.20.45:8786')

In [3]: c  # I've setup a cluster with 2 workers, each with 4 threads
Out[3]: <Client: scheduler='tcp://10.10.20.45:8786' processes=2 cores=8>

In [4]: import numpy as np

In [5]: import dask.array as da

In [6]: x = np.random.randint(0, 500, (10000, 10000))  # 800 MB

In [7]: dx = da.from_array(x, chunks=x.shape)

In [8]: dx.chunks
Out[8]: ((10000,), (10000,))

In [9]: big = da.stack([dx, dx, dx])

In [10]: big  # array with 3 800MB chunks
Out[10]: dask.array<stack, shape=(3, 10000, 10000), dtype=int64, chunksize=(1, 10000, 10000)>

In [11]: res = big.mean(axis=2).sum(axis=1)

In [12]: res.compute()
Out[12]: array([ 2494976.0879,  2494976.0879,  2494976.0879])

In [13]: f = c.submit(np.sum, x)  # submit a task with an argument > 512 MB

In [14]: f.result()   # works fine
Out[14]: 24949760879

In [15]: np.sum(x)  # matches numpy result
Out[15]: 24949760879
```

However, ideally you should keep chunk sizes smaller. More information on choosing chunk sizes can be found [here](http://dask.pydata.org/en/latest/array-creation.html#chunks), but the main goal is:
- Small enough that you can fit several chunks in memory at once (many computations will need to keep intermediates around for a bit)
- Large enough that each task takes *much* longer than the scheduler overhead (roughly .2ms-1ms).

I suspect the issue you're running into here is that the computations you're trying to do end up creating large intermediates and keeping them around long enough that they saturate the memory on the workers. Using a smaller chunk size/thinking more about how to align chunks with the operations you're trying to do may help alleviate this. To verify this, you could look at the memory usage plot on the [web interface](https://distributed.readthedocs.io/en/latest/web.html).

**Comment by mkhoshle** [comment]
Thanks, actually I am using Dask-delayed not Dask-arrays. In order to solve the memory problem, I tried to use smaller chunk sizes as you also suggested and I am doing this in two ways:
Method-1: One worker reads the whole array and sends a copy of the slices of the large Numpy array to other workers
Method-2: Each worker loads a small Numpy array and there is no sending and receiving of the Numpy arrays across workers.

I have attached the timing plots for each method.
Using Method 2 I was able to get good speed-up; however, with method1 I have problem getting results when I increase the number of processes and dask fails when the number of processes is large. Here is the error:

```
tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x2b1c67509668> exception was never retrieved: Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/comm/tcp.py", line 145, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/core.py", line 423, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/core.py", line 312, in send_recv
    response = yield comm.read()
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/comm/tcp.py", line 159, in read
    convert_stream_closed_error(e)
  File "/home/mkhoshle/miniconda2/envs/py35/lib/python3.5/site-packages/distributed/comm/tcp.py", line 105, in convert_stream_closed_error
    raise CommClosedError(str(exc))
distributed.comm.core.CommClosedError: Stream is closed
```
The results from Method-1 are obtained with Python 3.5.3, and I was not able to get that with Python 2.7.13 because it fails. You can see them here:
`https://github.com/mkhoshle/PSA-with-Dask/blob/master/PSA_Parallel-Method1.pdf` 
As you can see as I increase the number of my workers my code fails as trajectory size increases which is weird for me. I do not think if this is going to be a memory issue, because if it was memory issue, with smaller trajectory sizes it should had been failed as well. 

You can see the results with Method-2 here:
`https://github.com/mkhoshle/PSA-with-Dask/blob/master/PSA_Parallel-Method2.pdf`

**Comment by jcrist** [comment]
> As you can see as I increase the number of my workers my code fails as trajectory size increases which is weird for me. I do not think if this is going to be a memory issue, because if it was memory issue, with smaller trajectory sizes it should had been failed as well.

I'm afraid I won't be able to help you here unless I can see a reproducible example of what you're doing. Ideally this would be a script that I could run on my computer without downloading any data (you can use numpy to create fake data) that demonstrates the issues you're having. If this is not possible, just seeing the code that leads to the errors above should be of some help (but a reproducible test case would be better).

**Comment by mkhoshle** [comment]
@jcrist  I am using MDAnalysis library and I am parallelizing a function in this package and also it includes loading 2G of our input files. I first try to reproduce an example that creates the same problem with Numpy arrays and outside MDAnalysis. If it worked I would put it here if I was not able to reproduce it I will send you my code.

**Comment by mrocklin** [comment]
What is the status on this?

**Comment by mkhoshle** [comment]
@mrocklin @jcrist  I am faing this error a lot in my calculations. This is not the only case that I get this error, in one other example I am using dask arrays with another function inside MDAnalysis and again when I submit my job with large number of processes (256, 1024), it fails with the same error. I tried to start the scheduler with the flag --no-bokeh; however, it did not help.
It works very well with small number of processes, but when I increase the number of processes it fails for larger trajectory size. 
I do not think if it is a memory error, because when `N_procs=256` it works with small (128 trajectories with a total size of 500MB), and medium  (128 trajectories with a total size of 1 GB)  trajectories, but it fails for larger ones (128 trajectories with a total size of 2 GB).
Here is the plot `https://github.com/mkhoshle/PSA-with-Dask/blob/master/PSA_Parallel-Method1.pdf`.
Here is the link to my code:
`https://github.com/Becksteinlab/MDAnalysis-with-Dask/blob/master/PSA/PSA_Parallel-method2.py`

**Comment by mrocklin** [comment]
Hi @mkhoshle are you able to produce a simple reproducible example that we can run ourselves? Ideally this would be as small as possible (so that we don't have to spend a long time trying to understand your intent) and wouldn't require us to download any data.  Generally issues that take on this effort get higher quality responses much more quickly.  https://stackoverflow.com/help/mcve

**Comment by mkhoshle** [comment]
Hi @mrocklin, I hope I can reproduce this error. I am getting this error on another example as well. But the problem is that they are all inside MDAnalysis and with MD trajectories. Let me have a look and I will let you know. Thank you. I appreciate your help.

**Comment by mrocklin** [comment]
Yeah, I appreciate that this is hard.  At the end of the day picking out the MDAnalysis parts from the Dask parts is probably the hardest part of this process.  Identifying the cause of the error is probably harder than fixing it.  You may be the best qualified person to do the identification part here.

**Comment by mkhoshle** [comment]
@mrocklin @jcrist  I was able to reproduce the error outside MDAnalysis. I ran the code with 1024 cores. 

```
import dask
from dask.delayed import delayed
from dask import multiprocessing
from dask.multiprocessing import get
from dask.distributed import Client, progress
import numpy as np
import math
import time, glob, os, sys
import random

Scheduler_IP = sys.argv[1]
c = Client(Scheduler_IP)

def dH(P, Q):
    def vsqnorm(v, axis=None):
        return np.sum(v*v, axis=axis)
    Ni = 3./P.shape[1]
    d = np.array([vsqnorm(pt - Q, axis=1) for pt in P])
    return ( max(d.min(axis=0).max(), d.min(axis=1).max())*Ni )**0.5

def PSA(block, Block_size):
      subD = np.zeros([Block_size, Block_size])

      for i in range(Block_size):
           for j in range(Block_size):
               P = block[i]
               Q = block[j+Block_size]
               subD[i,j] = dH(P,Q)
      return subD

def main(arr_list, N_blocks, N_procs):
    Block_size = int(128/N_blocks)

    D_list = []
    for ii, i in enumerate(range(0, 128, Block_size)):
        for jj, j in enumerate(range(0, 128, Block_size)):
             block = arr_list[i:i+Block_size] + arr_list[j:j+Block_size]
             D_list.append(delayed(PSA)(block, Block_size))

    return D_list

N_procs = 1024
N_blocks = int(np.sqrt(N_procs))
arr_list = [np.random.random((102, 40092)) for i in range(128)]

output = main(arr_list, N_blocks, N_procs)
output = delayed(output)
result = output.compute(get=c.get)
```

And here is the error:
```
/var/spool/slurmd/job9168327/slurm_script: line 46: 18762 Killed   python $my_file.py $SCHEDULER:8786
slurmstepd: Exceeded step memory limit at some point.

Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object handle_worker at 0x2ba5a82db910> ignored
tornado.application - ERROR - Future exception was never retrieved: Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/tcp.py", line 159, in read
    convert_stream_closed_error(e)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/tcp.py", line 105, in convert_stream_closed_error
    raise CommClosedError(str(exc))
CommClosedError: Stream is closed
```

**Comment by mrocklin** [comment]
Thanks @mkhoshle .  Quick question: do I need to have a 1000 core cluster to test this or will this run on my laptop?

**Comment by mrocklin** [comment]
From your error it looks like maybe SLURM is just imposing a hard memory limit and dask is going beyond it and so getting killed?

> slurmstepd: Exceeded step memory limit at some point.

That error is coming from SLURM, not from Dask.  You might want to monitor your workers and see if they're going over.  If so then you might want to increase your limit on SLURM or decrease your limit on Dask.  You would also want to make sure that each your partitions are well below the limit that SLURM expects.  Dask may bring in several of these at once.

**Comment by mkhoshle** [comment]
@mrocklin  My code only fails when I have large number of cores. For example 1024, 256, etc. 
I did not test this example with 256 cores. But I tested it with 1024 (43 nodes) on Comet.

**Comment by mkhoshle** [comment]
@mrocklin  Thank you. I do not know what is this memory limit for? How can I specify it on Slurm or Dask? Do I need to ask the system administrator to do that for me?

**Comment by mrocklin** [comment]
My guess is that SLURM kills any process that takes a certain amount of memory.  You can suggest to dask that it keep below a certain threshold with the `--memory-limit` keyword.  See http://distributed.readthedocs.io/en/latest/worker.html?highlight=memory-limit#spill-excess-data-to-disk

You can probably ask SLURM to give you a bit more leeway.  Yes, this would be a good question for your system administrator.

**Comment by mkhoshle** [comment]
But the problem is that the same case runs successfully with the small number of processes. When I increase the number of my processes, it means that I have smaller number of blocks and as a result, smaller memory needed per worker. If this is a memory problem, it should fail for smaller number of processes not larger. Should not it?
You can also take a look at the following plot (https://github.com/mkhoshle/PSA-with-Dask/blob/master/PSA_Parallel-Method1.pdf) the ones that are blank are the ones that failed.

**Comment by mkhoshle** [comment]
When I talked to the system administrator they suggested to use larger number of nodes and use less cores per node (for example 64 nodes with 16 cores per node instead of 43 nodes with 24 cores per node). So I did try this, but it did not help. Also, although I used --memory-limit=2e9 when starting dask workers, when I monitor memory usage I am able to see workers that go over that limit. How can this happen?

**Comment by mkhoshle** [comment]
I had a line in my code where I was doing insertion into a Sparse matrix. I noticed that the memory usage of the node increased by more than 2GB when running that line. Thus, I should say that the error I reported is not  a Dask issue. So, I close this issue!
