### ISSUE TITLE
Multiplication by imaginary unit generates unstable name

### ISSUE THREAD

**Issue by estebanag** [dask/dask#2228]
I'm using dask to work with complex-valued arrays and noticed that the dask name is unstable. This example replicates the issue:
```python
import numpy as np
import dask.array as da

A = np.ones((10, 10))*5
B = np.ones((10, 10))*6
A = da.from_array(A, chunks=A.shape)
B = da.from_array(B, chunks=B.shape)
C = A + 1j * B
D = A + 1j * B
print(C.name)
print(D.name)  # this should print the same as the previous line but doesn't.
```
This originates from the multiplication by `1j`. My current workaround is to use `np.array([1j])` instead of `1j`.

**Comment by mrocklin** [comment]
Thank you for tracking this down @estebanag .  Fixed (I think) in https://github.com/dask/dask/pull/2229
