### ISSUE TITLE
Quickstart for non-scientific users 

### ISSUE THREAD

**Issue by kszucs** [dask/dask#2230]
I'm a bit frustrated how under-starred dask and distributed repos are.

IMHO here are a couple areas where the project needs to improve.

### README

Nowadays projects are all about README, README, README. Dask and distributed have a jumper link for excellent and overwhelming sphinx pages. I have a bunch of coworkers who would instantly leave and forget repos in the absence of a (5-min read) README containing QUICKSTART informations.

### Users without scientific background

I've found dask when it was just about distributed array computations. Nowadays (along with distributed) dask provides a more robust solution. 
I starting with dask for a non-scientific user is kinda frightening now. 

People not faimiliar with numpy or pandas could still benefit (and be amazed) from bag and delayed computations (without a steep learning curve). A large portion of python developers live in the flask/django/rq world (like the majority of my coworkers). On the other hand increasing the popularity of dask in such communities would bring a couple of great contributors for integrating in widely used systems. 

### Integration examples

I've seen the following usage pattern on my colleagues: dask is, straightforward, great, and awesome until we stay in ipython (say experimental environment).
BUT dask is risky, experimental, barely have stars on github (especially true for distributed) they wouldn't use in production (rather start with a JVM based animal - like we did with sparkit-learn :))

I like the examples approach of [sanic](https://github.com/channelcat/sanic/tree/master/examples).

**Comment by mrocklin** [comment]
I'm in favor of a small readme for both projects.  I'm somewhat wary about replicating a large amount of content from the docs. 

Historically it has been difficult to create a readme which is both general/fully scoped and also concise.  The people who have tried this before have focused on what was important to them.  For example they will say "Dask is a parallel pandas" or "Dask is a parallel numpy" which as you suggest doesn't capture the full scope.  Trying to capture the full scope results in a much larger document which ends up competing with the proper docs.

Anyway, I'd love to see a solution here.  It's a non-trivial problem though.

**Comment by kszucs** [comment]
How about the usage/integration examples?

I think this would be a good start as a README: https://dask.readthedocs.io/en/latest/index.html with the usual chapters installation, testing, contribution etc.

**Comment by mrocklin** [comment]
> How about the usage/integration examples?

I'm entirely in favor of adding more examples.  Historically the challenge here has been convincing people like yourself with domain knowledge to contribute to providing examples that are both representative of a domain and also simple enough to include in core documentation.  Perhaps this is something you're willing to work on though?

> I think this would be a good start as a README: https://dask.readthedocs.io/en/latest/index.html with the usual chapters installation, testing, contribution etc.

How would you recommend keeping those two pages synchronized in the future?  When people change the documentation or the README they are unlikely to change the other.

**Comment by kszucs** [comment]
These features or core concepts won't change often. Dask have a lot of code documentation, sphinx documentation, probably already misaligned. Maintaining a short README won't take too much effort.

**Comment by mrocklin** [comment]
Does this mean that you are volunteering to keep these synchronized for the foreseeable future?

**Comment by kszucs** [comment]
Oooh, my English isn't that feasible :) - but sure, I can take a try.

**Comment by kszucs** [comment]
Where did the name dask (dag + task?) came from?

**Comment by mrocklin** [comment]
> Oooh, my English isn't that feasible :) - but sure, I can take a try.

Presumably you would just need to check in from time to time and make sure that things remain synchronized.  It shouldn't require much content creation.

> Where did the name dask (dag + task?) came from?

Sure, something like that. It's just a name though.

It might be useful to look at other projects like scikit-learn, pandas, jupyter, etc. to see how they handle their README files.

**Comment by TomAugspurger** [comment]
Pandas used to have an extensive README, but has been moving towards having pretty much everything in the main docs. The README and main docs were too often out of sync.

The current readme is mostly a summary of main features, links to various places, and a bit of information for developers.

**Comment by jakirkham** [comment]
Wonder if the landing page being worked on will solve this issue. ( https://github.com/dask/dask/pull/3315 )

**Comment by mrocklin** [comment]
Docs have moved around a lot since this issue. There is still plenty that can improve.  Hopefully we can continue further discussion in more focused issues.  Closing.
