### ISSUE TITLE
Dask.distributed demo repository

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#224]
Setting up a cluster and then setting up dask.distributed is probably a big enough speedbump to derail most potential users.  It would be good to have a simple-yet-motivating example.  This would demonstrate

1.  How to set up a cluster on EC2 (perhaps using conda-cluster)
2.  How to set up dask.distributed on that cluster (perhaps using IPython parallel)
3.  How to compute on some public dataset (perhaps hosted on S3 (I should build S3 hooks into dask.bag))
4.  How to connect a collection like dask.bag up to dask.distributed using the Client.get method

The artifact here is probably a public repository on github.  This could serve as a public reference example both for dask.distributed and for conda-cluster.  It would be a nice example use case to use in presentations and would probably serve well when communicating with new users on mailing lists.

**Comment by mrocklin** [comment]
cc @quasiben @danielfrg @cowlicks

**Comment by quasiben** [comment]
We could push to make this fairly easy.  Could dask.distributed be setup in a `local mode` on a single machine?  IPython Parallel has no issues here I don't think

**Comment by mrocklin** [comment]
Dask has other schedulers that support that case well.  The goal here is to demonstrate capability on a distributed machine.

**Comment by cowlicks** [comment]
There is a prototype here https://github.com/ContinuumIO/dask-distributed-demo (private repo)

@chdoig could you move this to the blaze org? Or maybe we should wait for @mrocklin's planned distributed changes.

**Comment by mrocklin** [comment]
My current plan is to avoid committing resources to the current `dask.distributed` system.  I'm open to other suggestions.  My work at github.com/mrocklin/distributed is slowgoing but also somewhat steady.

**Comment by jcrist** [comment]
The distributed scheduler has been moved to its own project: https://github.com/dask/distributed. Closing.
