### ISSUE TITLE
ENH: Adding median filtering

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2241]
Would be great to have an N-D median filter function akin to [`median_filter`]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.median_filter.html ). This is a common go to in image processing or the 1-D analog in signal processing to address speckle noise.

As it tends to be used over small regions, this should work well with `map_blocks`. It would in fact be reasonable to require the window to be smaller than the chunk size. So this should simplify the implementation quite a bit.

**Comment by mrocklin** [comment]
Would da.map_overlap help here?

**Comment by jakirkham** [comment]
That does look interesting. Though we should probably hash out a docstring for it so we are clear on what this is suppose to be doing.

**Comment by jcrist** [comment]
I think Matt was suggesting that the desired function could be easily written using `map_overlap`. Since there is some cost to adding functionality to dask array, I'm unsure if adding `median_filter` directly to dask is worth it, since it can be written quickly using public api.

Here's a version that doesn't handle all args/kwargs, but should give the general idea:

```python
In [43]: from scipy.ndimage import median_filter

In [44]: import dask.array as da

In [45]: import numpy as np

In [46]: x = np.random.randint(0, 255, (1000, 1000))

In [47]: dx = da.from_array(x, chunks=(500, 500))

In [48]: def dask_median_filter(x, size):
    ...:     return x.map_overlap(median_filter, size, size=size)
    ...:

In [49]: (dask_median_filter(dx, (1, 2)).compute() == median_filter(x, (1, 2))).all()
Out[49]: True
```

**Comment by jakirkham** [comment]
If it's that simple to write and test, then I would argue that makes it is completely reasonable to add it to the API. As noted in the OP, this is a commonly used function and people are more likely to look for a way to do this directly than a way to roll it themselves. Not to mention that having it tested gives people some confidence that it does indeed work. These tests are as much about making sure the wrapped versions work for people as demonstrating the wrapping function is widely applicable. Whereas by rolling it ourselves, we are left to also test it ourselves and potentially find out it doesn't work for our use case, which sounds like a lot of unnecessary code duplication and potentially wasted effort.

In fact there is precedent for us providing wrapped functions out of the box with FFT functions. Even though we provide a way for people to roll their own, we still provide wrapped versions of NumPy's FFTPACK. Not to mention we provide very good test coverage of these wrapped functions. While people are certainly free to wrap up other functions to use with this FFT wrapper (as we do in pyFFTW or one can do with SciPy), we guarantee a base case to satisfy people's needs. Doing something similar for a handful of stencil operations like median filtering would be quite handy.

Would also highlight, I'm still unclear on some things about `map_overlap` as the API is [not documented]( http://dask.pydata.org/en/latest/array-api.html#dask.array.ghost.map_overlap ). For instance, how are boundary conditions handled? What ability do we have to override this? Also what are these `kwargs`?

**Comment by jcrist** [comment]
> Would also highlight, I'm still unclear on some things about map_overlap as the API is not documented.

The docstring lives on the equivalent method: `da.Array.map_overlap`. See doc: http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.map_overlap. You're right though, we should either remove the function from the docs, or add a docstring to it.

> In fact there is precedent for us providing wrapped functions out of the box with FFT functions.

I'm not arguing that it shouldn't be in dask, I'm just saying that at some point we have to draw a line. The FFT functionality has a counterpart in numpy whereas the filters only exist in scipy (which is not a required dependency). We can certainly add them and make scipy an optional dependency. Would you be interested in submitting a PR?

**Comment by jakirkham** [comment]
Ok, thanks for the pointer.

Thanks for clarifying. I understand the point and would definitely like to talk more about how the Dask ecosystem should look. The closest issue I see to this is issue ( https://github.com/dask/dask/issues/1959 ), but that seems pretty specific to data ingestion. For instance, I make use of a lot of image and signal processing functions as well as some machine learning things. It would be good to chat about where these live in the long run.

FWIW I'm ok going with scipy as an optional dependency. Wondering if it would be worthwhile to hash out a general stencil wrapper first. ( https://github.com/dask/dask/issues/2244 ) Or instead just going forward with this simple operator and then refactoring once we have a bit more of an idea of what is needed. Happy to submit a PR for this.

**Comment by jcrist** [comment]
For now I'd add a `da.ndimage` module (or add onto/rename the `da.image` module) and implement any of the operations you want there. Not all of the filters in `scipy.ndimage` have the same interface, so a "generic" wrapper might be tricky. Certain ones like `median/maximum/minimum/percentile_filter` all do though, and could be wrapped the same. We do have `da.learn` for wrapping simple scikit-learn functionality, so I have no problem doing the same here for commonly used scipy stufff. I just don't want to go down the rabbit whole of wrapping all of scipy (which is huge).

There is also a benefit to splitting off subprojects into smaller components. Could also see a small project `dask_ndimage` (or a different name) containing these. Up to you.

**Comment by mrocklin** [comment]
> There is also a benefit to splitting off subprojects into smaller components. Could also see a small project dask_ndimage (or a different name) containing these. Up to you.

+1 on this.  I would love to see more work split off from the main repository.  It is already difficult to maintain all of the dask collections code together.  This is a general comment; I haven't sufficiently looked into this particular issue to yet have an opinion.

**Comment by jakirkham** [comment]
Have much more to say on this topic, but will try to be brief for now.

Am working on a Dask extension library for N-D filters and morphological operations. Basically wrappers around a reasonable subset `scipy.ndimage` for use with Dask. In particular `scipy.ndimage.filters` and  `scipy.ndimage.morphology` are of particular interest. May look at the Fourier filters as well. Though Fourier filters can't be straight wrappings of the SciPy versions FWICT. The rest will be saved for other libraries, which I may or may not write. The separation is partly do to their similarity and partly due to current needs for scientific work.

Thinking the filters, morphological operators, and Fourier filers will be in the same library called [`dask-ndfilters`]( https://github.com/jakirkham/dask-ndfilters ). Am working on adding a median filter currently in PR ( https://github.com/jakirkham/dask-ndfilters/pull/3 ). Though this will be extended to include other ordering filters as well.

Would certainly appreciate feedback on that PR and this project as a whole. Right now I want to do the bulk of the work just so I know what is going on, but can open it up more after the initial work is done. That said suggestions and feedback are always welcome.

At some point down the road, we can discuss migrating this under the Dask org if there is interest. For now am simply eager to get something off the ground.

**Comment by jakirkham** [comment]
This is now handled by the [`dask-ndfilters`]( https://github.com/dask-image/dask-ndfilters ) library. A 0.1.0 release of `dask-ndfilters` is on PyPI and a conda-forge package coming soon. Contributions welcome. 😄
