### ISSUE TITLE
Decomposition discussion

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2242]
I'm opening this issue to discuss leveraging Dask/Distributed to approach decomposition problems probably using or borrowing from scikit-learn. Have noticed the work on Dask-GLM, which may have some applicability. Initially am trying to figure out if there is interest in this topic. Once we figure that out, it would be good to hammer out a vision of where this lives and how this looks.

**Comment by mrocklin** [comment]
@jakirkham can you explain more about what information you're looking for?  What do you mean by "decomposition problems"?  This phrase may mean a different things to different communities.

**Comment by mrocklin** [comment]
I would also find it interesting to hear what your objectives are and what you would be interested in working on.

**Comment by mrocklin** [comment]
Is there an active question or comment here?  Can this be closed?

**Comment by jakirkham** [comment]
By decomposition, I'm thinking of matrix factorization problems.

ref: http://scikit-learn.org/stable/modules/decomposition.html

**Comment by mrocklin** [comment]
Have you seen the work currently in `dask.array.linalg`?  Did you want to propose something specific?

More generally I think I get confused by issues of the form "this issue is for the discussion of topic X" without any further discussion of that topic by the person who raised the issue.  If you would like to propose something specific then I encourage you to do so.  I would not be surprised to find that people come by and respond.  However if you're waiting for someone else to research your topic and propose things then you might be in for a long wait.

**Comment by mrocklin** [comment]
Maybe this is the sort of thing for which a mailing list would be useful if we had one.

**Comment by jakirkham** [comment]
> Have you seen the work currently in `dask.array.linalg`?

So that may be useful in implementing things I want to solve. Though the types of matrix factorization problems I'm referring to are not classical matrix factorization. Instead they are approximate matrix factorization problems where an exact factorization won't work. However something that is in some sense optimal can be approached.

> Did you want to propose something specific?

For me personally, I'm interested in the possibility of doing [dictionary learning]( http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.DictionaryLearning.html ) with Dask as a near term goal. Though some other techniques like K-SVD and NMF have merits as well. Some of the other things that fall under decomposition may be of interest for other applications (e.g. PCA and ICA).

It would be nice if we could reuse scikit-learn to accomplish this task. However I don't know how feasible this would be.

**Comment by mrocklin** [comment]
Yeah, if I were you I would start by doing some research on parallel algorithms for dictionary learning.  Perhaps a google scholar search?  Or if you find a sequential algorithm that can be written only with bulk numpy operations then you might try naively implementing it with dask.array and see how it performs.

**Comment by jakirkham** [comment]
Yeah, implementing these is mainly a matter of having some way of doing linear algebra (i.e. BLAS, LAPACK). FWICT this should be possible with current Dask implementations of these operations. Though it is always possible there is some linear algebra operation we are missing.

That said, it will just be a bit of work to implement and could benefit from additional eyes for review. Was hoping by opening this issue, I could connect with some like-minded individuals to collaborate with on this problem.

Plus if there are some pieces of this work that already exist (e.g. LASSO, LARS), which can be reused, that would be helpful to know before embarking on this.

**Comment by mrocklin** [comment]
If there are lower level components then maybe start with those?  They might be able to attract more broad interest.  cc @moody-marlin and @marianotepper in case this interests them.

**Comment by jakirkham** [comment]
I wonder if this should be moved to dask-ml maybe? Seems like it would be more in scope there, but I don't want to overstep. Thoughts @TomAugspurger?

**Comment by jakirkham** [comment]
Have raised related issues over at [`dask-ml`]( https://github.com/dask/dask-ml ) for `DictionaryLearning` ( https://github.com/dask/dask-ml/issues/95 ), `NMF` ( https://github.com/dask/dask-ml/issues/96 ), `ICA` ( https://github.com/dask/dask-ml/issues/97 ), and `FA` ( https://github.com/dask/dask-ml/issues/98 ). It looks like `PCA` and `TruncatedSVD` were already addressed in issue ( https://github.com/dask/dask-ml/issues/22 ). Closing this as relevant discussions can now occur under those issues (and any others deemed relevant by others).
