### ISSUE TITLE
COMPAT: pandas privacy changes in >= 0.20.0

### ISSUE THREAD

**Issue by jreback** [dask/dask#2245]
https://github.com/pandas-dev/pandas/pull/16086

As we change what is public/private in 0.20.0. 

``pandas.tools.hashing`` -> ``pandas.util.hashing``, so need to change have a try/except on the import

This needs to change.
```
./dask/dataframe/hashing.py:# - For versions > 0.19.2, we use the provided `hash_pandas_object` function.
./dask/dataframe/hashing.py:# - For 0.19.0 through 0.19.2, we copy the definition of `hash_pandas_object`
./dask/dataframe/hashing.py:    from pandas.tools.hashing import hash_pandas_object
```

**Comment by wikiped** [comment]
This as well:

    D:\Anaconda\lib\site-packages\dask\dataframe\methods.py in <module>()
          4 import pandas as pd
          5 from pandas.api.types import is_categorical_dtype
    ----> 6 from pandas.types.concat import union_categoricals
          7 from toolz import partition
          8 

    ImportError: No module named 'pandas.types'

According to [pandas docs](https://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#modules-privacy-has-changed):

 > `pandas.types` moved to `pandas.core.dtypes`

**Comment by jreback** [comment]
these are both private, ``pandas.api.types`` is the exposed are. this is the same as in 0.19.2 as well.
