### ISSUE TITLE
Web interface does not respond with tornado 4.5.1 and bokeh 0.12.5

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2252]
Upgrading from bokeh 0.12.4 to 0.12.5 pulled down version 4.5.1 of tornado. This caused the web ui to never respond. Rolling back to 0.12.4 and 4.4.3. has resolved it for me for now.

I replicated this on centos and OS X.

**Comment by shughes-uk** [comment]
Apparently this is a known issue with tornado 4.5.1 and not related to dask! Apologies.

**Comment by mrocklin** [comment]
Thanks for reporting it on Github regardless.  You're certainly not the
only person that this will affect.  Hopefully others who come by will see
this issue and learn what's going on.

Thanks!

**Comment by pitrou** [comment]
Reference of upstream Bokeh issue: https://github.com/bokeh/bokeh/issues/6152
The issue is fixed on Bokeh master and should therefore be solved once a new Bokeh version is released.

**Comment by bryevdv** [comment]
FYI conda installing `0.12.6` should now no longer allow tornado 4.5, the dependencies for the package in the defaults channel were updated to exclude it.
