### ISSUE TITLE
Use absolute paths in read_* functions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2256]
In a distributed context the workers may have different working directories than the client.  In this case relative paths may be confusing.  Should we consider converting all paths on the posix file systems to absolute paths?

**Comment by martindurant** [comment]
No strong opinion: is this a problem now? It would be easy to implement in LocalFileSystem._trim_filename.

**Comment by mrocklin** [comment]
I run into it from time to time.  Users do as well.  It's a common problem
in tutorials.

However it's also very easy to avoid if you understand what's going on, so
not a very high priority, mostly just a question at this point.
