### ISSUE TITLE
Zero npartitions in dd.read_sql_table

### ISSUE THREAD

**Issue by kszucs** [dask/dask#2260]
if `(count * bytes_per_row / bytes_per_chunk) < 0.5` than npartitions will be 0.0 resulting a one length `divisions` array.

`np.linspace(100, 101, 0 + 1) -> array([ 100.]) -> zero partitions`

https://github.com/dask/dask/blob/328884c82d9fb9ff0ffbae630c7dbcc05681e198/dask/dataframe/io/sql.py#L113

@martindurant Using `ceil` instead of `round` solves the problem.

**Comment by martindurant** [comment]
Gahhh, thanks for spotting this.

**Comment by martindurant** [comment]
How about 
`npartitions = round(count * bytes_per_row / bytes_per_chunk) or 1`
because I'm not sure we always want to push the number or partitions higher?
