### ISSUE TITLE
map_partitions creates a `foo` column on a phantom partition

### ISSUE THREAD

**Issue by moody-marlin** [dask/dask#2265]
It appears that `map_partitions` operates on a phantom partition, which converts all string columns to a constant value of `foo`:

```
In [1]: import dask.dataframe as dd; import pandas as pd

In [2]: base_data = pd.DataFrame({'id': ['a', 'b', 'c'], 'val': [0, 1, 2]})

In [3]: test = dd.from_pandas(base_data, npartitions=1)

In [4]: def look_inside(df):
   ...:     from IPython import embed; embed()
   ...:     return df
   ...: 

In [5]: test.map_partitions(look_inside).compute()
```

In the first `IPython` session that is triggered, we find:

```
In [1]: df
Out[1]: 
    id  val
0  foo    1
1  foo    1
```

and in the second:

```
In [1]: df
Out[1]: 
  id  val
0  a    0
1  b    1
2  c    2
```

and the final result is correct.

In general if the final result is correct this would be harmless, but sometimes processing happens that might trigger an error whenever the constant `foo` column is present:

```
In [6]: def throws_error(df):
   ...:     out = df.groupby('id').count()
   ...:     if out.max()[0] > 1:
   ...:         raise ValueError('Too many ids!')
   ...:     return out
In [7]: test.map_partitions(throws_error).compute() # <-- raises ValueError
```

when in fact we know the data should be immune to this error:

```
In [8]: throws_error(base_data)
Out[8]: 
    val
id     
a     1
b     1
c     1
```

I suspect the [`_meta_nonempty` function](https://github.com/dask/dask/blob/bab4942b4b9eab6862226c0da868389629ee074f/dask/dataframe/core.py#L34) is somehow responsible via this [`_simple_fake_mapping`](https://github.com/dask/dask/blob/9136fdaf23ade5991ef91d20369d2dd5b9d22a37/dask/dataframe/utils.py#L347-L356) but am not familiar enough with the code path to understand why.

FWIW, I also get this error whenever I exit the above `IPython` session:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/IPython/core/history.py", line 785, in writeout_cache
    self._writeout_input_cache(conn)
  File "//anaconda/lib/python3.5/site-packages/IPython/core/history.py", line 769, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145322360832 and this is thread id 140735106551808
```

**Comment by mrocklin** [comment]
Does this stackoverflow answer help?  http://stackoverflow.com/questions/43416809/on-dask-dataframe-apply-receiving-n-rows-of-value-1-before-actual-rows-proces/43417070#43417070

**Comment by jcrist** [comment]
The first call is for metadata inference, as is documented here: http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions. We call the function on some fake metadata to infer the output dtype. When it works, this is great, but for complicated functions this can fail. As you noted, `"foo"` is the fake string that we use for object dtype.

**Comment by moody-marlin** [comment]
Oh wow, you guys are fast; yea that definitely explains it.  Sorry my google-fu didn't turn that up.  I guess this isn't really a bug then?  Knowing this, I suppose I can write an error check to catch the error I expect to see on the fake block, and just have it `pass` there.

**Comment by mrocklin** [comment]
The cleanest thing to do is to pass in `meta=` explicitly if you're able to provide the column names and dtypes

**Comment by jcrist** [comment]
> Knowing this, I suppose I can write an error check to catch the error I expect to see on the fake block, and just have it pass there.

It'd be much better to pass in the metadata you expect `map_partitions` to return here.

**Comment by moody-marlin** [comment]
Ok, verified that actually avoids the fake data call, thanks!

**Comment by gancvp** [comment]
Is this is still not resolved ? I had following code and after looking @ this page I added the meta to map_partitions funciton. But still getting  value error ( converting string to float). When I forced string type , I was able to see two rows with foo content.  PLease let me know what to do.
 

`def ProcessPQ(aDfChunk, output_pqfolder):
    fPQfile = os.path.join(output_pqfolder,"{}.parquet".format(str(uuid.uuid1())))    
    aDfChunk.to_parquet(fPQfile, compression="snappy")
def ConvertTxttoPQ(aLocation,aFilePattern,aColumns,aDTypes):
    files=os.path.join(aLocation, aFilePattern)    
    df = dd.read_csv(files, dtype=aDTypes, header=None,sep='|', names=aColumns)
    df2 = df.repartition(npartitions=2)
    df2.map_partitions(ProcessPQ, aObjFileInfo.outputfilelocation).compute(num_workers=3)
`

**Comment by gancvp** [comment]
@mrocklin  - Boss I'm counting on you for this. please provide your thoughts

**Comment by mrocklin** [comment]
> @mrocklin - Boss I'm counting on you for this. please provide your thoughts

This kind of comment is disruptive and makes me personally sad.  I suspect that you meant well here, but please don't place expectations on the time of open source maintainers who are working for you for free.

**Comment by gancvp** [comment]
@mrocklin  my apologies.
