### ISSUE TITLE
Keyerror when slicing dating

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2288]
This looks similar to #2211 but I'm not sure. I've attached a zip with sample data and code that reproduces it. If you uncomment line 25 it works for some reason.
```
import dask.bag
import pandas as pd
import re
from datetime import datetime
schema_dict = {
    'timestamp': 'datetime64[ns]',
}


time_regex = r'\[(?P<time>[^]]+)\]'
time_regex = re.compile(time_regex)


def get_log_dict(line):
    match = time_regex.match(line)
    dt = pd.datetime.strptime(match.groupdict()['time'], '%d/%b/%Y:%H:%M:%S +0000')
    return {'timestamp': dt}


files = ['2012-09-25.log', '2012-09-26.log', '2012-09-27.log']
b = dask.bag.read_text(files, blocksize=5000000).map(get_log_dict).to_dataframe(schema_dict)
b = b[~b.timestamp.isnull()]
b = b.set_index('timestamp')
b = b[sorted(b.columns)]
# b = b.repartition(freq='15m')
start = datetime(2012, 9, 26)
end = datetime(2012, 9, 27)
b = b.loc[start:end]
b.compute()
```

[Archive.zip](https://github.com/dask/dask/files/971843/Archive.zip)

**Comment by TomAugspurger** [comment]
Yeah, this looks very similar.

I think dask's `.loc` will have to protect against the index not being monotonic / sorted, and fall back to  `boundary_slice` if it isn't. I can take a closer look tonight or tomorrow morning.

**Comment by TomAugspurger** [comment]
So, when you call `b.set_index('timestamp')`, it sets an index that isn't monotonic. (This is another situation where https://github.com/dask/dask/pull/2150 comes into play).

@mrocklin do you have thoughts on the desired behavior here? The two options I see:

1. Follow pandas and raise a KeyError when you do a slice into a non-monotonic index with a missing key
2. Do some special handling for this case

Normally I would go with 1 without reservation. My only hesitation is that `dask.dataframe.set_index` has that sorting behavior that differs from pandas. I think I have a slight preference for 1, but we should clarify the docs on this. The docstring for set_index mentions 

> It then passes over the data a second time, splitting up each input partition into several
pieces and sharing those pieces to all of the output partitions now in
sorted order.

when it should say mostly sorted order.

@shughes-uk you have the one work around with a repartition; the other option is to explicitly sort each partition's block before slicing:

```python
b.map_partitions(pd.DataFrame.sort_index).loc[start:end].compute()
```

**Comment by mrocklin** [comment]
Does set_index not also sort the index per-partition?  If not then should it?

**Comment by TomAugspurger** [comment]
> Does set_index not also sort the index per-partition? If not then should it?

Not in all cases. IIRC, we do the `partition_quantiles`, and if that is "sorted enough" (I forget the exact heuristics used), then we just set that column directly. Let me see if there's a performance cost to always mapping sort_index. Pandas does short-circut if the index is monotonic, so it may not be too expensive.

**Comment by mrocklin** [comment]
Always sorting seems reasonable to me, especially if this is the semantics expected by pandas.

**Comment by shughes-uk** [comment]
If you're going to raise an error the docs should probably be changed to reflect the 'mostly sorted' status and perhaps include the workaround for it. It doesn't sound like you're going to go that route though.
