### ISSUE TITLE
Import dask dataframe error: "No module named decorators"

### ISSUE THREAD

**Issue by edesz** [dask/dask#2306]
I had installed Dask 0.10.0 on Win 7 (64-bit) with `pip install dask[complete]` and then I installed a new version with:

    pip install dask[complete]

Now, I get this error message:

    import dask.dataframe as dd

    Traceback (most recent call last):
	  File "C:\Python27\test.py", line 2, in <module>
	    import dask.dataframe as dd
	  File "C:\Python27\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
	    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
	  File "C:\Python27\lib\site-packages\dask\dataframe\core.py", line 13, in <module>
	    from pandas.util.decorators import cache_readonly
	ImportError: No module named decorators

For `0.10.0` I did not get this error when I ran `import dask.dataframe as dd`.

I have the latest version of Pandas, NumPy, etc. - all were installed with `pip` - see below for version numbers.

Dask 0.10.0 ran just fine on my PC. I had to upgrade it since I could not get `ddf.values` to execute. I suspected this was due to an older version and so installed the new version.

Versions:
numpy 1.11.1+mkl
pandas 0.20.0
dask 0.14.2
distributed 1.16.1
Python version - `print(platform.python_version())` gives me `Python 2.7.8`.

**Comment by jcrist** [comment]
This is due to the new release of pandas (0.20.0). We just release dask 0.14.3 on pypi and conda-forge with fixes for the new pandas release. Try upgrading dask to 0.14.3 and the problem should go away.

**Comment by edesz** [comment]
Ok, so I upgraded with [pip](https://packaging.python.org/installing/#upgrading-packages): `pip install --upgrade dask[complete]`. I noticed this installed `NumPy`. When I tried to load pandas with `import pandas as pd`, it threw an error: something like "could not find NumPy-MKL". So, I had to [download](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) and install NumPy-MKL with `pip install numpy-1.11.3+mkl-cp27-cp27m-win_amd64.whl`.

`import dask.dataframe as dd` works just fine now.

**Comment by edesz** [comment]
Sorry for missing the new release before. A GOOGLE search returns a search result for Dask documentation with 0.14.2 so I never thought to think of a new version. Thanks for pointing this out to me.

**Comment by jcrist** [comment]
They happened within a day of each other (due to the recent pandas release). You're not the only one who had this problem. As far as the mkl issue, that sounds like an issue with how you installed numpy/pandas, not a dask specific issue. Glad you figured it out though.
