### ISSUE TITLE
What is dask.quote?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2307]
I get that this has an SO flavor to it, but instead what I'm getting at is this doesn't appear to be documented. 😕 In fact, the first time I heard of it was in issue ( https://github.com/dask/dask/issues/2299 ).

**Comment by mrocklin** [comment]
Does the docstring suffice?

```python
def quote(x):
    """ Ensure that this value remains this value in a dask graph

    Some values in dask graph take on special meaning. Sometimes we want to
    ensure that our data is not interpreted but remains literal.

    >>> quote((add, 1, 2))  # doctest: +SKIP
    (literal<type=tuple>,)
    """
    if istask(x) or type(x) is list:
        return (literal(x),)
    return x
```

Given that this is an internal function (not exposed through the public API) this meets my personal criteria for documentation.  Is confusion about this function restricting productivity somehow?

**Comment by jakirkham** [comment]
Ah by not documented I meant not in RTD (API or otherwise). If it is meant to be internal, then that seems unnecessary. So feel free to close.
