### ISSUE TITLE
Support Py3 `pathlib.Path` objects

### ISSUE THREAD

**Issue by mattilyra** [dask/dask#2309]
At the moment `dask.bag.read_text` accepts `glob` patterns or `iterable`s of file paths. For better support of Python 3 the methods should also support `pathlib.Path` objects.

This doesn't seem to be that much work, as far as I can tell `get_fs_paths_myopen` in `dask.bytes.core` is the only thing that needs to be changed. I'm new to the codebase though, so might well be missing something.

https://github.com/dask/dask/blob/master/dask/bytes/core.py#L386

**Comment by martindurant** [comment]
This is solved by simply calling str() on the passed path?

**Comment by mattilyra** [comment]
That should solve it
