### ISSUE TITLE
dask.dataframe.describe fails with all object columns

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2326]
From [SO](http://stackoverflow.com/questions/43895873/dask-eror-min-arg-is-an-empty-sequence)

```python
In [14]: df = pd.DataFrame({"A": ['a', 'b', 'c', 'd', 'e']})

In [15]: import pandas as pd; import dask.dataframe as dd

In [16]: df = pd.DataFrame({"A": ['a', 'b', 'c', 'd', 'e']})

In [17]: dd.from_pandas(df, 2).describe().compute()
```

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-48df04528427> in <module>()
----> 1 dd.from_pandas(df, 2).describe().compute()

/Users/taugspurger/.virtualenvs/pandas-dev/lib/python3.6/site-packages/dask/dataframe/core.py in describe(self, split_every)
   1305         num = self._get_numeric_data()
   1306
-> 1307         stats = [num.count(split_every=split_every),
   1308                  num.mean(split_every=split_every),
   1309                  num.std(split_every=split_every),

/Users/taugspurger/.virtualenvs/pandas-dev/lib/python3.6/site-packages/dask/dataframe/core.py in count(self, axis, split_every)
   1190                                     token=token, split_every=split_every)
   1191             if isinstance(self, DataFrame):
-> 1192                 result.divisions = (min(self.columns), max(self.columns))
   1193             return result
   1194

ValueError: min() arg is an empty sequence

```

I can take a look later.

**Comment by TomAugspurger** [comment]
Ah interesting, `.describe` only computes on numeric data. We can probably have a better error message here anyway.

**Comment by GermanCM** [comment]
Hi @TomAugspurger if I look at the official documentation: http://docs.dask.org/en/latest/dataframe-api.html, it seems to be that 'object' dtypes should be accepted with the 'describe()' option by means of this sentence: "For object data (e.g. strings or timestamps), the result’s index will include count, unique, top, and freq", but as I can see in one of my examples, it does not work yet, giving the following error message: "ValueError: DataFrame contains only non-numeric data."
Any news about it so far? Thanks in advance.

**Comment by TomAugspurger** [comment]
The documentation may be pulled from pandas.DataFrame.describe. I don't
recall the specifics.

Let us know if you're interested in updating the documentation, or updating
describe to handle non-numeric data.
