### ISSUE TITLE
Expose chunksize in Dask Array API

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2328]
Frequently am finding myself in situations where I need to create another array say to multiply to some Dask Array provided as input. In these situations, the new array needs some chunk size provided. As there is really no reason to pick the new array's chunksize to be anything other than that of the input array, I'd really like a simple way to do that. However, FWICT there isn't one. The best one can do is roll their own version of [this]( https://github.com/dask/dask/blob/28848055b4f50017feae95acf27b9c00d604a7f9/dask/array/core.py#L1029 ), which merely gets the first chunk for each dimension. At a bare minimum, it would be nice if that was a readonly attribute (property) of Dask Array's for these use cases.

**Comment by jcrist** [comment]
> Frequently am finding myself in situations where I need to create another array say to multiply to some Dask Array provided as input. In these situations, the new array needs some chunk size provided.

Do you mean you want to create an array with the same chunks as the input to do some operation on where the chunks should align? In this case `chunksize` wouldn't be sufficient, as dask arrays don't need to have all chunks be identically shaped. Is there a reason you can't just use the `chunks` attribute as is? Any method that takes `chunks` as a parameter should work fine with an existing `chunks` tuple. E.g.

```python
a = some_dask_array
ones = da.ones(a.shape, chunks=a.chunks)   # same chunks as `a`
```

**Comment by jakirkham** [comment]
Yeah I end up needing to feed it into `linspace` or `arange` or similar, which acts on a single dimension. Seem to be running into issues when I do that.

**Comment by jcrist** [comment]
Seems to work fine for me? Note that your input chunks must match the expected shape:

```python
In [1]: import dask.array as da

In [2]: da.arange(10, chunks=(4, 4, 2)).compute().shape
Out[2]: (10,)

In [3]: da.linspace(0, 1, 10, chunks=(4, 4, 2)).compute().shape
Out[3]: (10,)

In [4]: da.arange(10, chunks=(4, 4, 1)) # bad chunks
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-b896e65e4ac3> in <module>()
----> 1 da.arange(10, chunks=(4, 4, 1)) # bad chunks

/Users/jcrist/Code/dask/dask/array/creation.py in arange(*args, **kwargs)
    124
    125     num = max(np.ceil((stop - start) / step), 0)
--> 126     chunks = normalize_chunks(chunks, (num,))
    127
    128     name = 'arange-' + tokenize((start, stop, step, chunks, num))

/Users/jcrist/Code/dask/dask/array/core.py in normalize_chunks(chunks, shape)
   1803             raise ValueError(
   1804                 "Chunks and shape must be of the same length/dimension. "
-> 1805                 "Got chunks=%s, shape=%s" % (chunks, shape))
   1806
   1807     if shape is not None:

ValueError: Chunks and shape must be of the same length/dimension. Got chunks=(4, 4, 1), shape=(10.0,)
```

**Comment by jcrist** [comment]
Note that the `.chunks` attribute is a tuple of tuples. Since `linspace` and `arange` only return 1d arrays, you need to subselect along a dimension to align. Something like:

```python
a = some_dask_array
aligned_on_zeroth_axis = da.linspace(a.shape[0], chunks=a.chunks[0])
```

**Comment by jakirkham** [comment]
It's a little more subtle than my last comment suggests it is. When using `fftfreq`, we create an array with `linspace`. However, that always contains one more value than we care about (namely the last value). So if the chunks are anything other than a number, they will likely not add to the full length. I think this could be fixed if we normalize the given chunks first and add a singleton chunk for the end (as it will be removed anyways). Thoughts?

**Comment by jcrist** [comment]
That would work. The relevant function is `dask.array.core.normalize_chunks`.

Looking at that function more it's not clear what a fully specified `chunks` (e.g. a tuple) argument means for `rfftfreq`, since it doesn't return the full size. You could separate the call to linspace between real and imaginary and be smart about creating the output exactly with the specified chunks, but I'm not sure if it's worth it.

**Comment by jakirkham** [comment]
Cool, I think PR ( https://github.com/dask/dask/pull/2330 ) will fix it then.

**Comment by jcrist** [comment]
Thoughts on what `chunks` means for `rfftfreq`?

**Comment by jakirkham** [comment]
Updated the aforementioned PR to handle that case as well.

**Comment by jcrist** [comment]
Fixed by #2330. Closing.

**Comment by jakirkham** [comment]
FWIW I still think this is an interesting idea, but yes the motivating use case has been resolved in a better way.

**Comment by jcrist** [comment]
My issue with that is `chunksize` isn't a good measure of `chunks` unless all chunks have the same shape. Since we expose `chunks` as an attribute already (which is a good measure), I'm hesitant to expose `chunksize` as I think it'll be confusing and misunderstood by users more often than it'll be useful.

**Comment by jakirkham** [comment]
Maybe having upper and lower bounds on it would be good?
