### ISSUE TITLE
Lazy test of false-iness

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2329]
*Got this request from a user.  Decided to put it up on Github for discussion.*

Given a lazy dask object:

    x = dask.delayed([])

Is there a convenient API to lazily determine if this object is falsey.  Currently the best I can come up with is the following:

    y = dask.delayed(lambda x: not x)(x)

Is there any interest in extending any of the APIs like bag.Item, dataframe.Scalar, or delayed to have a more convenient method?

**Comment by jcrist** [comment]
I'd be against that for `delayed` objects - I don't think these should have any methods beyond the standard dask ones like `compute` and `visualize`. For the others, maybe.

**Comment by shoyer** [comment]
`dask.delayed(operator.not_)(x)` is probably the idiomatic choice.

I can see a case for a dask submodule with delayed versions of everything in the standard library's [`operator`](https://docs.python.org/3.6/library/operator.html) module.

**Comment by jakirkham** [comment]
Why not `dask.delayed(bool)(...)`? That's what Python does under the hood anyways, right?

**Comment by shindavid** [comment]
@jakirkham That evaluates truthiness, not falsiness.

**Comment by jakirkham** [comment]
Sure add a `not` if you want it the other way.

**Comment by shindavid** [comment]
@jakirkham I think then you end up needing a lambda, and it'll look like mrocklin's code.

**Comment by mrocklin** [comment]
FWIW I also think that in the general case using a lambda is fine.  There is a maintenance cost to convenience functions and creating novel API.

**Comment by jcrist** [comment]
I'm going to say using `delayed(operator.not_)` is the most idiomatic and best choice. Since it's just a simple one-liner, I'm going to opt to close this for now. As Matt said above, there is a maintenance cost to expanded api.
