### ISSUE TITLE
Implement outer ufuncs

### ISSUE THREAD

**Issue by Joshuaalbert** [dask/dask#2342]
The ufuncs in numpy all have useful `outer` methods which are useful and easily parallelizable.
For instance, `np.subtract.outer(x,y)` can be done in chunks of rows of length `y.size`.
`delayed(np.subtract.outer)` does not work because numpy casts the inputs to ndarrays.

Is this enhancement possible?

**Comment by jcrist** [comment]
Thanks for the issue report. I have a PR for this almost ready, should be up later today.

**Comment by jcrist** [comment]
Fixed in #2345.
