### ISSUE TITLE
tolist method for Dask Arrays

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2347]
NumPy Arrays have a [`tolist`]( https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ndarray.tolist.html ) method. It might be nice if Dask Arrays did too. This would amount to creating a potentially nested list of Dask 0-D Arrays. Not sure if this would be of interest for Dask Arrays or not.

**Comment by jcrist** [comment]
Do you need this for something? Since `dask.array` is designed to work with larger datasets, converting to python objects is less-than-efficient. I'd be hesitant to make this easy to do without a good reason.

**Comment by jakirkham** [comment]
Not really and I found other ways to get around the problem where I had needed it. That said, did find it interesting that it was missing. Maybe it is worth adding a note in the docs about why this doesn't exist.

**Comment by jcrist** [comment]
> Maybe it is worth adding a note in the docs about why this doesn't exist.

See #2351.
