### ISSUE TITLE
Add block function 

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2350]
Basically am interested in having a `block` function for Dask Arrays that acts like NumPy's new [`block`]( https://github.com/numpy/numpy/blob/v1.13.0rc1/doc/release/1.13.0-notes.rst#npblock-function-for-creating-blocked-arrays ) function. This is scheduled to be released with NumPy 1.13.0. As similar functionality has been discussed before ( https://github.com/dask/dask/issues/2028 ) and seems to be of general interest, am opening this issue to discuss getting this implemented in Dask.

**Comment by mrocklin** [comment]
This sounds like a good idea to me.  I'm glad to see that NumPy added this
to their API.

**Comment by jakirkham** [comment]
Attempting to add this in PR ( https://github.com/dask/dask/pull/2650 ).
