### ISSUE TITLE
Support writing and reading parquet partitions

### ISSUE THREAD

**Issue by rothnic** [dask/dask#2362]
I'm saving partitioned data out by month to parquet with fastparquet 0.0.6, then reading in with dask 0.14.3 and pandas 0.20.1. I'm updating only the partitions as needed each time I need to update the data, then I'm trying to read it all with dask, to further operate on the entire thing and eventually store it in a location for tableau to pick it up.

It looks like the only option at the moment is to manually manage the different parquet partitions, but it would be nice if I could do something like spark supports, where you can do something like:

### Ideal End Goal

``` python
data_path = '/path/to/full/data/'

new_data = get_new_chunk_of_data()

new_data.write_parquet(data_path, mode='append', partition_on=['year', 'month', 'day'])
# or
new_data.write_parquet(data_path, mode='replace', partition_on=['year', 'month', 'day'])
```

For now, I'm trying to just handle the appending/replacing of each partition manually, then reading the entire thing with dask afterwards. So I often have a structure like:

```
/path/to/full/data/
/path/to/full/data/year=2017/
/path/to/full/data/year=2017/month=1/
/path/to/full/data/year=2017/month=1/day=1/
```

And I want to do: `dd.read_parquet('/path/to/full/data/')`, where dask generates a dataframe with columns of all those that exist within the parquet file, plus year, month, day. Right now it appears to error out like `[<paritition_name>] not in index` on this function call `meta = _meta_from_dtypes(all_columns, pf.columns, dtypes)`, line 102 of `dask/dataframe/io/parquet.py`.

### Simple Example

Here is a simple example of what I'm trying to do:

``` python
import dask.dataframe as dd
import pandas as pd
from fastparquet import write

# create dataframe for a single partition
dates = pd.date_range('2017-01-01', '2017-01-31')
col1 = range(0, len(dates))
col2 = list(reversed(col1))
df = pd.DataFrame({'event_date': dates, 'metric_1': col1, 'metric_2': col2})

# add column I will partition on
df['year_month'] = '2017-01'

# write with fastparquet using partitioning
write('./tmp/', df, partition_on=['year_month'], file_scheme='hive', write_index=False)
```

#### Resulting in

``` python
> glob.glob('./tmp/*')
['./tmp/_common_metadata', './tmp/_metadata', './tmp/year_month=2017-01']
```

#### Write a second partition

``` python
# pretending we actually have new data here
df['year_month'] = '2017-02'
write('./tmp/', df, partition_on=['year_month'], file_scheme='hive', write_index=False)

> glob.glob('./tmp/*')
['./tmp/_common_metadata',
 './tmp/_metadata',
 './tmp/year_month=2017-01',
 './tmp/year_month=2017-02']
```

#### Exceptions on Reading with Dask

```python
df2 = dd.read_parquet('./tmp/')
```

Errors with `ValueError: Multiple possible indexes exist: [u'event_date', u'metric_1', u'metric_2'].  Please select one with index='index-name'`

```python
df2 = dd.read_parquet('./tmp/', index='event_date')
```

Errors with `KeyError: "[u'year_month'] not in index"`

**Note:** reading with fastparquet does work, but then I can only convert it to a pandas dataframe.

**Comment by martindurant** [comment]
Would you mind checking if https://github.com/dask/dask/pull/2354 fixes this for you? You might try `index=False` to make things simple.
I don't think there's explicit consideration yet that the index might be a partitioned value, but we certainly should. I expect to work on categorical and partitioned reading/writing shortly.

**Comment by mrocklin** [comment]
What is the status here?  Was this resolved?

**Comment by martindurant** [comment]
There appear to be no more comments coming on #2365 , so it should be merged, and then this can be closed.

**Comment by jdanbrown** [comment]
Just ran into a bug that might be a blocker for this issue: https://github.com/dask/dask/issues/2398
