### ISSUE TITLE
allow objects to define their own tokenize

### ISSUE THREAD

**Issue by ordirules** [dask/dask#2366]
Recently, I found it convenient for objects to define their own tokenization. Basically, by checking if it has the attribute `tokenize`. Would this be something that could be supported by dask?
If this has already been discussed, I apologize in advance. I searched very quickly.

Thanks!

example:

```python
    def tokenize(*args, **kwargs):

        # now check if each argument/kwarg handle their own tokenization
        argslist = list()
        for arg in args:
            if hasattr(arg, 'tokenize'):
                argslist.append(arg.tokenize())
            else:
                argslist.append(arg)

        kwargsdict = dict()
        for key, val in kwargs.items():
            if hasattr(val, 'tokenize'):
                kwargsdict[key] = val.tokenize()
            else:
                kwargsdict[key] = val

        hsh = tokenize(*argslist, **kwargsdict, pure=True)
       
        return hsh
```

**Comment by ordirules** [comment]
I should mention a usage case. We have objects that generate large arrays of coordinate values based on a few simple parameters. It is simpler for us to pass these objects around as opposed to explicitly passing the arrays. We could like the hash not to depend on the object itself (i.e. if the class is redefined or the library re-loaded). The best way to ensure this is to check for a `tokenize` method in the arguments.
If there is a better way, happy to hear.

Maybe @jcrist may have a quick tip on this. thanks!

**Comment by jcrist** [comment]
You can do this right now by registering your own implementation of `normalize_token` for a certain type. This should return an object made of only python builtins that represent your object (e.g. tuple, str, etc...). For example:


```python
In [1]: from dask.base import normalize_token, tokenize

In [2]: class Foo(object):
   ...:     def __init__(self, x, y):
   ...:         self.x = x
   ...:         self.y = y
   ...:

In [3]: import numpy as np

In [4]: x = np.arange(10)

In [5]: y = np.arange(5)

In [6]: f = Foo(x, y)

In [7]: tokenize(f)  # no implementation, different key each time
Out[7]: '224d3d61159f2cac5222da3fe99d4182'

In [8]: tokenize(f)  # no implementation, different key each time
Out[8]: '8b9b1c346a2aac0ec7f314a6d59c2265'

In [9]: @normalize_token.register(Foo)
   ...: def normalize_foo(x):
   ...:     # call normalize_token on each of the arrays and return the result
   ...:     return (normalize_token(x.x), normalize_token(x.y))
   ...:

In [10]: tokenize(f)  # same key every time now
Out[10]: 'c33c3c5d181ac1bb7018b3e57184d2ee'

In [11]: tokenize(f)  # same key every time now
Out[11]: 'c33c3c5d181ac1bb7018b3e57184d2ee'
```

I recommend looking in `dask.base` at how these are defined for other classes.

**Comment by ordirules** [comment]
thanks and thanks for quick response, this is so clean. great library. :-)

(maybe this should be added to the documentation? I don't see it. Maybe Delayed->Overview add a section called 'hashing tasks' or something?)

**Comment by jcrist** [comment]
> maybe this should be added to the documentation?

I'm not 100% set on this being public api yet, but I wouldn't expect it to change anytime soon so you should be fine relying on it.

**Comment by ordirules** [comment]
sounds good, thanks!

**Comment by ordirules** [comment]
@jcrist would it be fine to add a `dispatch` method for `utils.Dispatch`?
I'm thinking of an object that inherits from another object. I'd like to call `normalize_token` for the parent object (nested object) first, like:

```python
def normalize_token_myobj(obj):
    args = myfunc.dispatch(ParentObject)(obj)
    newargs = list()
    newargs.append(obj.newelementinobj)
    newargs.append(obj.newelementinobj2)
    args.extend(normalize_token(newargs))
    return args
```
If there is a better way, i'm also interested to hear. Thanks for all the discussions

**Comment by jcrist** [comment]
That could be done. An existing solution would be to just call the implementation for `ParentObject` directly:

```python
@normalize_token.register(ParentObject)
def normalize_parent(obj):
    return obj.attr1, obj.attr2, obj.attr3

@normalize_token.register(NewObject)
def normalize_token_myobj(obj):
    return normalize_parent(obj) + (obj.attr4, obj.attr5)
```

**Comment by ordirules** [comment]
Yeah, I noticed after doing that. This would still be cleaner (in my case, I'm importing the class from another location. I'd have to import each classes normalizing function. Keeping logic in the dispatch would be simpler).
Would it be worth adding? I could also submit PR if saves you time

**Comment by jcrist** [comment]
Sounds fine to me. If you could submit a PR that'd be great.

**Comment by ordirules** [comment]
sounds good, thanks, i posted  a suggested PR, works on test_utils.py but haven't tested elsewhere, let me know if this is good, thanks!

**Comment by IPetrik** [comment]
For those like me coming here after Oct 2017, the method `__dask_tokenize__` was added. (http://docs.dask.org/en/latest/custom-collections.html#deterministic-hashing)
