### ISSUE TITLE
Add nan-aware reductions to DataFrame

### ISSUE THREAD

**Issue by astyonax** [dask/dask#2376]
I would like to do this:

`
merged = dd.read_hdf('a_file.h5','/merged')
merged.groupby(['hour','month']).aggregate([np.nanmean,np.nanmin,np.nanmax,np.nanstd])
`

But I get: `ValueError: unknown aggregate nanstd`

Is it problematic to add nan-aware reductions to dask.DataFrame?

**Comment by martindurant** [comment]
You do not need to do this - pandas, and therefore dask-dataframe, does not normally include NaN values in aggregations. In this it behaves unlike numpy.

    merged.groupby(['hour','month']).aggregate(['mean', 'min', 'max', 'std'])

**Comment by astyonax** [comment]
ok, thank you!
Indeed, I just realized that you can still get NaN from the aggregate functions when a group is "empty". 
E.g.:
```python
>>> import pandas as pd
>>> import numpy as np
>>> df = pd.DataFrame([{'A':1,'B':np.nan},{'A':1,'B':np.nan},{'A':2,'B':1}])
>>> df
   A    B
0  1  NaN
1  1  NaN
2  2  1.0
>>> df.groupby('A').aggregate(['mean','max'])
     B     
  mean  max
A          
1  NaN  NaN
2  1.0  1.0
```

**Comment by jcrist** [comment]
Sounds like this issue is resolved then. Closing.
