### ISSUE TITLE
Dask dataframe set_index documentation and sorting

### ISSUE THREAD

**Issue by joshring** [dask/dask#2388]
**Existing documentation docstring:** 
https://pastebin.com/0HMWQQcy

**Default behaviour with Dask 14.3 is that sorted=True, docs say False, setting True gives an error.**
Default=True is matching pandas and is good, but docstring states default=False

If we enable `sorted=True` we get an error when we call set_index:

`set_index( 'timestamp_dte_object', sorted=True )`

**The error:**
https://pastebin.com/nbzfanfG

### **It is important to note that `set_index('timestamp')` works, and returns a sorted array, without the `sorted=True` option, which is fantastic**

**Summary**

* Dask dataframe Doc string fix for `sorted=True` by default in `set_index()`
* Fix crash where `set_index()` is called with `sorted=True`

Related to this issue:
https://github.com/dask/dask/issues/1995

**Comment by TomAugspurger** [comment]
Can you give a runnable example of what you mean?

I think you might be misunderstanding the parameter (or I misunderstand you). `sorted` indicates whether the column is *already* sorted. The output of `.set_index` will always have a sorted index, regardless of `sorted`.

```python
In [4]: ddf.set_index("A", sorted=True)  # OK
Out[4]:
Dask DataFrame Structure:
                   B
npartitions=2
1              int64
3                ...
4                ...
Dask Name: set_index, 4 tasks

In [5]: ddf.set_index("B", sorted=True)  # Not OK
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-bfe81e9dce95> in <module>()
----> 1 ddf.set_index("B", sorted=True)  # Not

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/core.py in set_index(***failed resolving arguments***)
   2259             from .shuffle import set_sorted_index
   2260             return set_sorted_index(self, other, drop=drop, divisions=divisions,
-> 2261                                     **kwargs)
   2262         else:
   2263             from .shuffle import set_index

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/shuffle.py in set_sorted_index(df, index, drop, divisions, **kwargs)
    462
    463     if not divisions:
--> 464         divisions = compute_divisions(result, **kwargs)
    465     elif len(divisions) != len(df.divisions):
    466         msg = ("When doing `df.set_index(col, sorted=True, divisions=...)`, "

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/shuffle.py in compute_divisions(df, **kwargs)
    486             any(a > b for a, b in zip(mins, maxes))):
    487         raise ValueError("Partitions must be sorted ascending with the index",
--> 488                          mins, maxes)
    489
    490     divisions = tuple(mins) + (list(maxes)[-1],)

ValueError: ('Partitions must be sorted ascending with the index', 0    1
1    2
dtype: int64, 0    4
1    3
dtype: int64)
```

**Comment by joshring** [comment]
Oh right, thanks you're right I did misunderstand it.
