### ISSUE TITLE
Add `apply_along_axis` and `apply_over_axis` to `dask.array`

### ISSUE THREAD

**Issue by eriknw** [dask/dask#2390]
[`numpy.apply_along_axis`](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.apply_along_axis.html) and [`numpy.apply_over_axis`](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.apply_over_axes.html) should be good candidates to parallelize in `dask`.  I recently reached for `apply_along_axis`.

**Comment by jakirkham** [comment]
Mapping over axes is pretty easy.

Concatenating the results is not as trivial as it should be currently. Probably adding `block` will make that simpler. ( https://github.com/dask/dask/issues/2350 )

**Comment by jakirkham** [comment]
Attempted to add `apply_along_axis` in PR ( https://github.com/dask/dask/pull/2698 ). Still a little rough around the edges, but it does work.

**Comment by jakirkham** [comment]
Also have some work locally for `apply_over_axis` that I'm happy to share once `apply_along_axis` lands (as it depends on the latter).

**Comment by jakirkham** [comment]
Added `apply_over_axis` in PR ( https://github.com/dask/dask/pull/2702 ).
