### ISSUE TITLE
future has status 'finished' even while still executing

### ISSUE THREAD

**Issue by ijstokes** [dask/dask#2392]
Using dask 0.14.3

I'm looking at the 01-custom-futures.ipynb notebook where there is this sequence of operations:

```python
zs = []
for i in range(256):
    x = c.submit(inc, i)     # x = inc(i)
    y = c.submit(double, x)  # y = inc(x)
    z = c.submit(add, x, y)  # z = inc(y)
    zs.append(z)
    
total = c.submit(sum, zs)

print(total)

print(total.result())

print(total)

del total

zs = []
for i in range(256):
    x = c.submit(inc, i)     # x = inc(i)
    y = c.submit(double, x)  # y = inc(x)
    z = c.submit(add, x, y)  # z = inc(y)
    zs.append(z)
    
total = c.submit(sum, zs)

print(total)

print(total.result())

print(total)
```
What is odd is that if I do `del total` and then execute the same sequence of operations I can see in the profiler that Dask is executing tasks, but the future `total` is instantly tagged as the state `Finished`.

<img width="729" alt="screenshot 2017-05-26 15 47 31" src="https://cloud.githubusercontent.com/assets/293525/26510411/35ac8e84-422b-11e7-86fd-ce61e00e3ed6.png">

then I do a `del total` and then execute again, starting with a bare `total` to make sure it isn't still, somehow, defined:

<img width="737" alt="screenshot 2017-05-26 15 48 11" src="https://cloud.githubusercontent.com/assets/293525/26510412/35aca266-422b-11e7-8987-eec6e33104ec.png">

**Comment by mrocklin** [comment]
I would expect total to finish quickly because zs are already in memory.  I
would expect some futures to run because intermediate values (like the x's)
are briefly created where previously they had been released.

**Comment by ijstokes** [comment]
OK, let me try to come up with a self contained example and explain better the part that surprises me.
