### ISSUE TITLE
Optimize da.where for bool case

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2407]
In the case of [`da.where`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.where ), a strictly known Boolean value should be an optimized case. IOW one of the two Dask Arrays provided should be returned outright instead of handling this element-wise and adding an operation to the graph.

**Comment by jakirkham** [comment]
Does this seem like a reasonable suggestion? If so, should be pretty easy to get a PR together.

**Comment by mrocklin** [comment]
In principle it seems fine to me.  I'm curious when it comes up in practice.

**Comment by jakirkham** [comment]
Some of the morphological functions from SciPy (e.g. [`binary_dilation`]( https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.binary_dilation.html )) provide a `mask` argument to restrict where the morphological operation is computed. The easiest way I could see to handle this behavior in Dask currently was to initially apply the morphological operation on the whole array and then use `da.where` to restrict where the result was kept after the fact. Part of the motivation for this implementation is that `map_overlap` doesn't support multiple arrays yet. ( https://github.com/dask/dask/issues/2403 )

As the default case for `mask` is equivalent to making it `True`, `da.where` could be inserted into the final Dask graph (potentially multiple times due to the `iterations` parameter) needlessly. Since we know that `mask` was `True` on the outset, it makes sense to optimize out these calls to `da.where` during graph construction. While we can certainly do that optimization ourselves, it seemed like an appropriate addition to Dask proper.

**Comment by mrocklin** [comment]
OK.  If you feel like submitting a PR I'd be much obliged.

**Comment by jakirkham** [comment]
Took a few other PRs to get things cleaned up and do a few other optimizations along the way, but PR ( https://github.com/dask/dask/pull/2432 ) should do the trick.
