### ISSUE TITLE
dd.get_partition(n) displays wrong index in error message

### ISSUE THREAD

**Issue by nico-ha** [dask/dask#2411]
Hi guys,

this is a really minor issue but I just noticed that when you pass an invalid index to `dd.get_partition(n)`, the resulting `ValueError` shows an incorrect upper bound in the error message. Example:

```
$ pip freeze | grep dask
dask==0.14.3
$ python
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> import numpy as np
>>> pdf = pd.DataFrame(np.zeros(9))
>>> ddf = dd.from_pandas(pdf, npartitions = 3)
>>> ddf.get_partition(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<python-path>\lib\site-packages\dask\dataframe\core.py", line 370, in get_partition
	raise ValueError(msg)
ValueError: n must be 0 <= n < 3
```

It should be `0 <= n < 2`.

**Comment by mrocklin** [comment]
Thanks for the report @nico-ha .  Can I interest you in submitting a small pull request with a fix?

**Comment by nico-ha** [comment]
Hi @mrocklin ,

thanks for your quick reply, but I just noticed it's actually alright because there is a `<`, not a `<=`. Sorry about that, I should go to sleep :)
