### ISSUE TITLE
Exception when loading parquet

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2414]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 286, in read_parquet
    categories=categories, index=index)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 68, in _read_fastparquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/fastparquet/api.py", line 607, in sorted_partitioned_columns
    sorted(max) == max and
TypeError: unorderable types: dict() < dict()
```

I've attached the parquet files that generate this error. They were created with dask also.
[test.zip](https://github.com/dask/dask/files/1052698/test.zip)

It looks like it causes an issue when a column value is a dictionary

**Comment by martindurant** [comment]
Unfortunately it loads OK for me.
I notice a couple of things:
- column zonePlan is encoded as JSON, although everything is strings (actually just one value of a string): would recommend categorical, bytes or UTF8 encoding. This is the column that might look like a dict somehow.
- no index was defined for the data (specifically, the pandas metadata exists, and says that none of the given columns should treated as the index)
- timestamp looks very index-like, so even though no index is defined, `index='timestamp'` is probably a useful thing to do. Alternatively, `index=False` will prevent the attempt to guess an index, and so calling the stats functions; this happens automatically in your case of metadata specifying no index as of https://github.com/dask/dask/commit/81e1dea6c2f86238044f2b716cd9c601cb11b08b

**Comment by martindurant** [comment]
Yes, it seems you are right, and calculating the order of column values fails for dictionaries. This should be silently ignored, since dictionaries should never be used as an index, and comparison operations ought always to fail.
