### ISSUE TITLE
set_index datetime in dataframe composed of multiple HDF file keys fails

### ISSUE THREAD

**Issue by littlegreenbean33** [dask/dask#2429]
Hi,

I am unable to set a datetime  index in a dask dataframe, that I have read out of multiple pandas dataframes,  originally saved in a single HDF file, under different keys.

The pandas dataframes contain same fields, are mostly categoricals but a couple of fields, including a date field.

`df = dd.read_hdf(store_file,"/ISE_week_22")
pddf=pd.read_hdf(store_file,"/ISE_week_22")

df2=dd.from_pandas(pddf,npartitions=10)
pddf.date.head()

0   2017-06-01 12:52:54.329
1   2017-06-01 12:52:56.280
2   2017-06-01 12:52:56.306
3   2017-06-01 12:52:57.317
4   2017-06-01 12:52:58.320
Name: date, dtype: datetime64[ns]

df2.date.head()

0   2017-06-01 12:52:54.329
0   2017-06-02 17:02:54.352
0   2017-05-28 00:00:08.493
0   2017-05-28 00:00:08.494
0   2017-05-28 00:00:00.131
Name: date, dtype: datetime64[ns]

df2.set_index(df2.date)
df2.known_divisions
True

df = dd.read_hdf(store_file,"/ISE_week_2*")  <---- see the asterisk
df.known_divisions
False

df.set_index(df.date)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-149-d89141576615> in <module>()
----> 1 df.set_index(df.date)

C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\dataframe\core.py in set_index(***failed resolving arguments***)
   2297             from .shuffle import set_index
   2298             return set_index(self, other, drop=drop, npartitions=npartitions,
-> 2299                              divisions=divisions, **kwargs)
   2300 
   2301     @derived_from(pd.DataFrame)

C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\dataframe\shuffle.py in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, **kwargs)
     61         mins = [ipart.min() for ipart in iparts]
     62         maxes = [ipart.max() for ipart in iparts]
---> 63         divisions, sizes, mins, maxes = base.compute(divisions, sizes, mins, maxes)
     64         divisions = divisions.tolist()
     65 

C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    201     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    202     keys = [var._keys() for var in variables]
--> 203     results = get(dsk, keys, **kwargs)
    204 
    205     results_iter = iter(results)

C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, **kwargs)
     85         result = get_async(pool.apply_async, len(pool._pool), dsk3, keys,
     86                            get_id=_process_get_id,
---> 87                            dumps=dumps, loads=loads, **kwargs)
     88     finally:
     89         if cleanup:

C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    523                     _execute_task(task, data)  # Re-execute locally
    524                 else:
--> 525                     raise(remote_exception(res, tb))
    526             state['cache'][key] = res
    527             finish_task(dsk, key, state, results, keyorder.get)

KeyError: 'date'

Traceback
---------
  File "C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\dask\async.py", line 272, in _execute_task
    return func(*args2)
  File "C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\pandas\core\series.py", line 601, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\U91437\Documents\xx\Program Files\Anaconda\lib\site-packages\pandas\indexes\base.py", line 2169, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\index.pyx", line 105, in pandas.index.IndexEngine.get_value (pandas\index.c:3567)
  File "pandas\index.pyx", line 113, in pandas.index.IndexEngine.get_value (pandas\index.c:3250)
  File "pandas\index.pyx", line 163, in pandas.index.IndexEngine.get_loc (pandas\index.c:4373)

`

**Comment by littlegreenbean33** [comment]
apologies, ... python 3.5.2, pandas 0.19 dask 0.14

using multiprocessing scheduler

**Comment by TomAugspurger** [comment]
Sorry about missing this. Is it still an issue?

If so, are you able to make a reproducible example? (http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

You could create a representative DataFrame in memory with and write to HDF5 with pandas, and then read it in with dask.dataframe.

**Comment by littlegreenbean33** [comment]
Thanks Tom for getting back into this.

Unfortunately this is already "overtaken by events".

You can close this if you wish so. I do not have the materials or can reproduce this anymore

JC
