### ISSUE TITLE
ENH: Expand integration / unit tests between Apache Parquet implementations and fix any bugs that come up

### ISSUE THREAD

**Issue by wesm** [dask/dask#2439]
I started looking to add the `engine` argument to more unit tests and have started running into some issues. I will create subissues and link to them here, and I will open a PR with expansions in the test suite

**Comment by jcrist** [comment]
I'm going to close this. #2868 added a cartesian-product of reader/writer engines to relevant tests, and fixed a number of bugs that showed up. If specific bugs are found in either engine, please open a new issue for them.
