### ISSUE TITLE
cached delayed functions?

### ISSUE THREAD

**Issue by xinluh** [dask/dask#2441]
For similar use cases like `functools.lru_cache`, it can be very handy to "cache" delayed function calls, e.g. persist the computation and return the persisted object if function signature is the same as a previous computation. 

I haven't found a straightforward way to accomplish it right now, except for doing staged computation and saving the intermediate persisted objects to variables. So I hacked together this decorator that abuses `dask_client.get_datasets()` as a cache:

```python
from functools import wraps
from dask.delayed import tokenize

def cached_delayed(dask_client):
    def decorator(f):
        @wraps(f)
        def cached(*args, **kwargs):
            hash_key = '__cached-' + f.__name__ + '-' + tokenize(args + tuple(sorted(kwargs.items())), pure=True)
            if hash_key in dask_client.list_datasets():
                return dask_client.get_dataset(hash_key)
            else:
                computation = delayed(f)(*args, **kwargs).persist()
                dask_client.publish_dataset(**{hash_key: computation})
                return computation
        def get_all_cached():
            return [k for k in dask_client.list_datasets() if k.startswith('__cached-' + f.__name__ + '-')]
        cached.get_all_cached = get_all_cached 
        return cached
    return decorator
```

with usage like
```python
>>> @cached_delayed(dask_client)
>>> def test_compute(i):
>>>     return (i, random.random())
 
>>> test_compute(1).compute()
(1, 0.8021161328037106)
>>> test_compute(1).compute()
(1, 0.8021161328037106)  # cached, same as before
>>> test_compute(2).compute()
(2, 0.9588660960895805)  # newly computed 

>>> test_compute1.get_all_cached()  # 2 cached computations
['__cached-test_compute-468ea027d13e5c00b2039cb4cc8c94ca',
 '__cached-test_compute-d28a26e72c5cf6667e66de5a5e92bd62']
```

Does this kind of usage make sense, or is there a better way to do it?

**Comment by mrocklin** [comment]
Yes, something like this makes sense.  Some options:

### dask.delayed(pure=True)

Delayed itself can catch repeated computations if you add the pure=True keyword

```python
In [1]: import dask

In [2]: def inc(x):
   ...:     return x + 1
   ...: 

In [3]: dask.delayed(inc)(1)
Out[3]: Delayed('inc-ed7c5147-f8b7-4c4f-a110-3021decc6d6f')

In [4]: dask.delayed(inc)(1)
Out[4]: Delayed('inc-c46b28ae-7019-4c98-82ee-576c0ea6feee')

In [5]: dask.delayed(inc, pure=True)(1)
Out[5]: Delayed('inc-0475926aa94072e7d0dc3bdc2f65ea48')

In [6]: dask.delayed(inc, pure=True)(1)
Out[6]: Delayed('inc-0475926aa94072e7d0dc3bdc2f65ea48')

In [7]: dask.delayed(inc, pure=True)(2)
Out[7]: Delayed('inc-dbbb93af27a63d27db10252f00af9926')
```

This works well if you are doing only a single compute call.  It will not help you between compute calls.

### Similar work for the single-threaded scheduler

This was added as an experimental feature to the single-threaded scheduler.  See http://dask.pydata.org/en/latest/caching.html and http://matthewrocklin.com/blog/work/2015/08/03/Caching

### Scheduler plugin

We could do the same trick as a scheduler plugin.  See discussion in https://github.com/dask/distributed/issues/681

**Comment by mrocklin** [comment]
The latter option seems most similar to what you've done here and, I think, might be cleaner long-term (though I'm not sure).  If you were interested in the work I think it would be a good contribution.

**Comment by xinluh** [comment]
@mrocklin Definitely be interested in working on this. I'm not terribly familiar with internal workings with distributed though - do you think maintaining the references on scheduler (probably something like published datasets but under a separate dict) makes sense?

**Comment by mrocklin** [comment]
Yes.  You would probably make this as a SchedulerPlugin.  You might want to look at the plugin for progress bars here: https://github.com/dask/distributed/blob/master/distributed/diagnostics/progress.py

**Comment by mrocklin** [comment]
This seems to have gone stale.  Closing.  Feel free to respond and I'll reopen.
