### ISSUE TITLE
Messed up index on a dask dataframe prevents accessing data by label

### ISSUE THREAD

**Issue by olivier-lacroix** [dask/dask#2442]
Hi,

I am using dask (0.14.3) (Python 3.6.1 :: Anaconda 4.4.0 (64-bit)) to load a significant amount of data (250Go) in a dask dataframe on a local distributed client.

I do the following:
 - Load data through dask read_csv
 - Set the index on a string column

Trying to extract data through the loc operator sometimes bring empty data while it does return something when done from a partition.

Looking into it a bit more, it seems like the dataframe partitions are not aligned with the divisions. For instance, trying to "loc" the last value of the divisions in the last partition fails

I cannot share the data, but the code used is similar to:

import dask.dataframe as dd
X = dd.read_csv('file*', header=None,names=names, dtype=dtypes)
X = X.set_index('x', compute = False)
X = X.persist()

X.get_partition(X.npartitions-1).compute().loc[X.divisions[-1]]
>> gives "not in index"

Any idea what can go wrong and what other details would be needed? 

Olivier

**Comment by mrocklin** [comment]
Thank you for the code example.  Are you able perhaps to create a small reproducible example that creates the bug that you've seen, perhaps using random data?

**Comment by olivier-lacroix** [comment]
Hi Matt, I'll try to find the time to do that.

I can confirm that the bug is reproductible on the dataset I am using. It is likely linked to distributed rather than dask, as switching back to the default scheduler gives a sane dataframe.

**Comment by samuelroberth** [comment]
Is there an update on this? I'm having issues as well. Specifically I call applymap on a subset of the columns and then it does not recognize the other columns.

**Comment by TomAugspurger** [comment]
@samuelroberth do you have a reproducible example demonstrating the problem that you can share?

**Comment by samuelroberth** [comment]
Hmm I seem to have fixed it. Is there a good way to applymap to a subset of columns?

For instance data[['A', 'B']] = data[['A','B']].applymap(func).compute()

**Comment by TomAugspurger** [comment]
@samuelroberth you probably want to avoid calling the `.compute` before setting ``A, B``. e.g. this works:

```python
In [18]: a = dd.from_pandas(pd.DataFrame({"A": range(10), "B": range(10), "C": range(10)}), npartitions=2)

In [19]: a[['D', 'E']] = a[['A', 'B']].applymap(lambda x: x ** 2)

In [21]: a
Out[21]:
Dask DataFrame Structure:
                   A      B      C      D      E
npartitions=2
0              int64  int64  int64  int64  int64
5                ...    ...    ...    ...    ...
9                ...    ...    ...    ...    ...
Dask Name: assign, 12 tasks

In [22]: a.compute()
Out[22]:
   A  B  C   D   E
0  0  0  0   0   0
1  1  1  1   1   1
2  2  2  2   4   4
3  3  3  3   9   9
4  4  4  4  16  16
5  5  5  5  25  25
6  6  6  6  36  36
7  7  7  7  49  49
8  8  8  8  64  64
9  9  9  9  81  81

```

**Comment by samuelroberth** [comment]
Is there a way to do that 'in place' ie. instead of [['D', 'E']] use [['A', 'B']]. It is saying that column assignment does not support type dataframe.

**Comment by TomAugspurger** [comment]
That should work (maybe try with dask master), but again, you probably
don't want to be assigning *pandas* dataframes into a dask dataframe. It's
best to leave off that `.compute` and defer computation until later, so
you'll assign the *dask* dataframe that the applymap returns.

**Comment by samuelroberth** [comment]
doesn't seem to be working with the above logic...

**Comment by TomAugspurger** [comment]
```python
In [28]: a = dd.from_pandas(pd.DataFrame({"A": range(10), "B": range(10), "C": range(10)}), npartitions=2)

In [29]: a[['A', 'B']] = a[['A', 'B']].applymap(lambda x: x ** 2)

In [30]: a.compute()
Out[30]:
    A   B  C
0   0   0  0
1   1   1  1
2   4   4  2
3   9   9  3
4  16  16  4
5  25  25  5
6  36  36  6
7  49  49  7
8  64  64  8
9  81  81  9
```

Maybe show your example?

**Comment by samuelroberth** [comment]
Interesting. I'm doing the same thing you are doing but it is not working. 

I have some proprietary code so I can't share but it's basically 

```
data[['A', 'B', 'C', 'D']] = data[['A', 'B', 'C', 'D']].applymap(customfloatconversion)

data.compute()

data[['E', 'F', 'G', 'H']] = data[['E', 'F', 'G', H']].applymap(customstringconversion)

data.compute()
```

Giving me TypeError: Column assignment doesn't support type DataFrame

**Comment by mrocklin** [comment]
@samuelroberth perhaps you can create a simple example that fails that uses non-proprietary code, much like how @TomAugspurger has done above.

https://stackoverflow.com/help/mcve

**Comment by samuelroberth** [comment]
Here's my mcve which actually works fine:

```
import pandas as pd
import dask.dataframe as dd
import time
import numpy as np
import csv

def float_apply(x):
    try:
        return float(x)
    except ValueError:
        return float('nan')

def string_apply(x):
    try:
        return str(x)
    except ValueError:
        return str('nan')

df = pd.DataFrame(np.random.randint(0,100,size=(20, 4)), columns=list('ABCD'))

data = dd.from_pandas(df, npartitions=2)

data = data.applymap(float_apply)

data = dd.from_pandas(df, npartitions=2)

data[['A','B']] = data[['A','B']].applymap(float_apply)

data.compute()
```

However it does not work in my actual code. But if I read in the requested columns it works fine....

**Comment by mrocklin** [comment]
Perhaps you can find a simple example that fails to function well but that we can still reproduce.  It's very hard to help you otherwise.

**Comment by samuelroberth** [comment]
I apologize there was a coding error on my end.

Thank you for the help.

Issue can be closed I believe.
