### ISSUE TITLE
diagnostics partially empty for serial get

### ISSUE THREAD

**Issue by Joshuaalbert** [dask/dask#2448]
**Undesired behaviour**
I am invoking a local cluster to start realtime gathering of diagnostic information with something like:
```
client = Client()
dsk = .... # A custom graph of tasks that use nested dask computations
dask.get(dsk,['pull_m20'])
```
What I find is that the /tasks diagnostic is empty. The system pages show current system resources.

**Alternative approaches**
I understand  #2397 has fixed the nested callbacks issue so I can use:
```
with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
    dask.get(dsk,'pull_m20')
visualize([prof,rprof,cprof])
```

**Desireable Feature**
As far as I understand, it is **not** possible to do:
```
client = Client()
dsk = .... # A custom graph of tasks that uses nested dask computations
client.get(dsk,['pull_m20']) # daemon having children ERROR
```
Is there a way of using the distributed scheduler actually, and not just the data collection abilities with sub-dasks (possibly also using multiprocessing or distributed) with minimal overhear?

**Verison**
Master 1c0113d

**Comment by mrocklin** [comment]
> What I find is that the /tasks diagnostic is empty. The system pages show current system resources.

I suspect that you are just hosting pages on a couple different ports.  Tasks should show all of the information here.

> As far as I understand, it is not possible to do:

Your second example looks like your first.  I'm not sure what the difference is.

I apologize that no one responded to your issue when you raised it originally.  I'm going to go ahead and close it now.  If you still have issues and can add some new information please respond and we'll reopen.
