### ISSUE TITLE
[ENH] Support splitting compressed files with dataframe.read_csv()

### ISSUE THREAD

**Issue by ijstokes** [dask/dask#2449]
I'm using Dask 0.14.3.  I am performing this operation:

```python
df = dd.read_csv('pkgs/{y}-{m:02d}-*.gz'.format(y=ym[0], m=ym[1]), compression='gzip', error_bad_lines=False)
```

I get the warning message:

```bash
/Users/ijstokes/anaconda/envs/test/lib/python3.6/site-packages/dask/dataframe/io/csv.py:209: UserWarning: Warning gzip compression does not support breaking apart files
Please ensure that each individual file can fit in memory and
use the keyword ``blocksize=None to remove this message``
Setting ``blocksize=None``
```

But it seems to me that while it is not possible to split a compressed file in parallel there could be very good reasons to stream-uncompress the content and then create partitions that are smaller than the entire file.  Maybe there are reasons why that is impossible, but my sense is that it should be possible and would be beneficial in cases where the task-graphs don't require all partitions to remain in memory at the same time.

**Comment by mrocklin** [comment]
I agree that this would be beneficial.  However under the current design it
is not easy to do lazy stream processing with dask.dataframe.  This would
require a significant rewrite that I do not thing is likely to occur in the
near future.
