### ISSUE TITLE
Failing to specify numeric columns fails with "could not convert foofoo to numeric"

### ISSUE THREAD

**Issue by bluenote10** [dask/dask#2452]
A minor suggestion to improve error messages: The following code fails, because the meta data does not specify that column `A` is numeric. However, the error message is somewhat non-intuitive:

```python
import pandas as pd
import dask.dataframe as dd
from dask import delayed

df = pd.DataFrame({"A": [1, 2, 3]})
ddf = dd.from_delayed(delayed(lambda: df), meta=pd.DataFrame(columns=["A"]))
ddf["A"].mean()
# TypeError: Could not convert foofoo to numeric
```

This is probably a consequence of the data in `_simple_fake_mapping` in `dataframe/utils.py`. It would be good to turn the error into something more explicit mentioning the column name + dtype, so that users don't start to search for foofoo.

**Comment by mrocklin** [comment]
I agree that this would be a good change.  Can I interest you in submitting a small PR?  ("no" is a fine answer)

**Comment by bluenote10** [comment]
In general yes, but I don't know when I will get to it.

On first glance: Solving it for `df.mean()` only is trivial, but identifying + solving the issue for all affected operations requires a bit more thought I guess.

**Comment by mrocklin** [comment]
I suspect that you could catch an error somewhere in `map_partitions` or `_get_numeric_data` and have it applied more widely.

**Comment by jcrist** [comment]
For reference, this is what you in pandas get when you call `mean` on a non-numeric series.

```python
In [52]: x = pd.Series(['a', 'b', 'c'])

In [53]: x.mean()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/jcrist/anaconda/envs/dask/lib/python3.5/site-packages/pandas/core/nanops.py in _ensure_numeric(x)
    767         try:
--> 768             x = float(x)
    769         except Exception:

ValueError: could not convert string to float: 'abc'
```

For this case, we could provide a better error than pandas (check relevant series reductions for object dtype and fail early), but we can't catch the error for all operations. In general if you provide the wrong metadata, you're going to have a bad time.

> I suspect that you could catch an error somewhere in map_partitions

We already do this when we infer metadata for user provided functions, and prefix the error message with a brief note (see https://github.com/dask/dask/blob/master/dask/dataframe/utils.py#L126-L149).

I think the error behavior should be:

- For methods that take user functions (e.g. `map_partitions` or `reduction`), metadata inference should fail nicely (already done, but maybe message prefix could be nicer).
- For builtin methods, we should provide same/similar errors to pandas assuming the metadata is correct (already done by calling method on fake data generated from the metadata).

If the metadata is incorrect (as happened here) I'm not sure what we should do.

**Comment by bluenote10** [comment]
My idea would be to wrap all lines like [this](https://github.com/dask/dask/blob/ecdae84aa3b8ee5408876b0b7d7eade3d127e177/dask/dataframe/core.py#L1174) into: 

```python
with safe_meta_numerics():
    meta = self._meta_nonempty.mean(axis=axis, skipna=skipna)
```

with an appropriate context manager that catches only `TypeError` containing "Could not convert" and re-raises with an explicit hint that the meta data must be wrong. 

It took me quite some time to make sense of this error, probably because:
* I did explicitly specify `meta` including dtypes, just with a tiny mistake. 
* From a user perspective the `.mean()` is a lazy operation, so it was surprising to see hints of a numeric operation in the first place.
* The "foofoo" pointed me in the wrong direction, checking my code & data for "foofoo".

**Comment by jcrist** [comment]
>  explicit hint that the meta data must be wrong.

If the column is actually an object column, then the metadata doesn't have to be wrong, the operation is just invalid. I'd rather fix series reductions to check for object dtype, and error explicitly with `ValueError("mean reduction not supported for object dtype")`. If the metadata was correct, this is a better error message than what pandas throws. If the metadata is wrong, the user will see "object dtype" and should be able to track down their prior mistake.
