### ISSUE TITLE
dask.dataframe.from_dask_array doc wrong

### ISSUE THREAD

**Issue by paulochf** [dask/dask#2455]
I'm aware that documentation may be wrong (from https://github.com/dask/dask/issues/2450), but I've just found what can be another typo. As I didn't find anywhere talking about it, I'm opening this issue for reference.

I was looking for a way to get a Dask Array from a Dask DataFrame, then I came across this.

Doc about [dask.dataframe.from_dask_array](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.from_dask_array) is weird.

```
Create Dask Array from a Dask DataFrame

Converts a 2d array into a DataFrame and a 1d array into a Series.

    Parameters:
        x: da.Array
        columns: list or string
            list of column names if DataFrame, single string if Series

Examples

>>> import dask.array as da
>>> import dask.dataframe as dd
>>> x = da.ones((4, 2), chunks=(2, 2))
>>> df = dd.io.from_dask_array(x, columns=['a', 'b'])
>>> df.compute()
     a    b
0  1.0  1.0
1  1.0  1.0
2  1.0  1.0
3  1.0  1.0
```

Actually, this should be about "Create **Dask DataFrame** from a **Dask Array**", right?

**Comment by mrocklin** [comment]
Yes, I think that you are correct

**Comment by paulochf** [comment]
Just went through what I was looking for (and proof by contradiction)

http://dask.pydata.org/en/latest/array-creation.html#from-dask-dataframe

```
You can create dask arrays from dask dataframes using the .values attribute or the .to_records() method.

>>> x = df.values
>>> x = df.to_records()
```
