### ISSUE TITLE
Warning message in dask.array.compress

### ISSUE THREAD

**Issue by estebanag** [dask/dask#2458]
I've updated dask to the [latest version](https://github.com/dask/dask/releases/tag/0.15.0) and I'm getting the following ~~error~~ warning message when calling [compress](http://dask.pydata.org/en/latest/array-api.html#dask.array.compress):

```python
import dask.array as da
import numpy as np


data = np.arange(5)
dask_data = da.from_array(data, chunks=data.shape)
dask_mask = dask_data >= 2
mask = dask_mask.compute()
masked_dask_array = da.compress(mask, dask_data, axis=0)
result = masked_dask_array.compute()
```
```bash
/home/ubuntu/.virtualenvs/psi/lib/python3.5/site-packages/dask/core.py:307: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif type_arg is type(key) and arg == key:
```
The `result` is correct, but I wonder if there's anything else failing silently that I should keep in mind.

**Comment by TomAugspurger** [comment]
@estebanag this is just a warning, not an exception, correct?

I think https://github.com/dask/dask/pull/2457 silence the array (and fix the behavior when numpy changes in the future). Basically, dask is doing something like `if (a, b) == (c, d): ...`, where `a` may or may not be a NumPy array.

**Comment by estebanag** [comment]
You're right: it's just a warning. I think your solution (in your pull request) fixes the problem.
