### ISSUE TITLE
TST/CI: Unskip hanging tests test_learn.py::test_fit and test_bag.py::test_from_url

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2471]
In https://github.com/dask/dask/pull/2459 I unconditionally skip two tests

- `dask/array/tests/test_learn.py::test_fit`
- `dask/bag/tests/test_bag.py::test_from_url`

because they hang under certain conditions I don't fully understand. Running them by themselves doesn't cause any issues. The key components seem to be that you use `pytest-xdist` and run at least two of the main suites `{dask.array, dask.dataframe, dask.bag}`, for me it didn't hang when running just one of those.

**Comment by mrocklin** [comment]
test_learn.py is out.  URL testing is odd from time to time.  Closing.
