### ISSUE TITLE
Computing read_parquet with filters can return empty list

### ISSUE THREAD

**Issue by p-himik** [dask/dask#2477]
If you provide a filter that selects no partitions, `compute()` will return an empty list instead of an empty DataFrame with correct columns and dtypes.

Maybe not relevant, but plain and easy to fix in the same context problem - poor documentation for `filters` argument. It never says that the filters are applied only to partitions. It may be easily mistaken with `where` in `pandas.HDFStore.select`.

**Comment by martindurant** [comment]
The first issue is already fixed in master.
