### ISSUE TITLE
ResourceProfiler must be enclosed in `if __name__ == '__main__'` block on windows

### ISSUE THREAD

**Issue by HenkHcks** [dask/dask#2484]
Under some circumstances the ResourceProfiler does not function (the other profilers and the progressbar do). The `result` attribute of the profile is empty.  It does not occur under all circumstances, but occurs in both IPython shell and normal Python interpreter. 
The following code does not result in a recorded resource profile, and shows an error (but the program continues)  when using the Python terminal.  (`dask 0.15.0`, `python 3.6.0`)

```
import dask
from dask import delayed
from time import sleep
from dask.diagnostics import ResourceProfiler
from dask.diagnostics import visualize

with ResourceProfiler(dt=0.25) as rprof:
  dask.compute(delayed(sleep)(20))
visualize([ rprof, ])
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\anaconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\anaconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Projecten\MovSum\BUG_LineAnalysis.py", line 11, in <module>
    with ResourceProfiler(dt=0.25) as rprof:
  File "c:\anaconda\lib\site-packages\dask\diagnostics\profile.py", line 140, in __init__
    self._tracker.start()
  File "c:\anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "c:\anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <bound method ResourceProfiler.close of <dask.diagnostics.profile.ResourceProfiler object at 0x0000000002A65390>>
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\dask\diagnostics\profile.py", line 173, in close
    self._tracker.shutdown()
  File "c:\anaconda\lib\site-packages\dask\diagnostics\profile.py", line 210, in shutdown
    self.join()
  File "c:\anaconda\lib\multiprocessing\process.py", line 120, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
```

**Comment by jcrist** [comment]
I'm unable to reproduce.

```
(py36) jcrist dask $ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
(py36) jcrist dask $ cat test.py
import dask
from dask import delayed
from time import sleep
from dask.diagnostics import ResourceProfiler
from dask.diagnostics import visualize

with ResourceProfiler(dt=0.25) as rprof:
    dask.compute(delayed(sleep)(20))
visualize([ rprof, ])
(py36) jcrist dask $ python test.py
(py36) jcrist dask $
```

<img width="829" alt="screen shot 2017-06-23 at 10 47 39 am" src="https://user-images.githubusercontent.com/2783717/27489775-70135a8a-5801-11e7-8dc7-a1aa66c46d38.png">

I get same results in `ipython`. Does this happen for you every time? How are you running this script? What OS?

**Comment by HenkHcks** [comment]
I ran both of them from `Spyder 3.1.4`, and it happens every time. To be sure I just ran it in a bare interpreter, and gave the same error (python.exe bug.py). 

Reducing a working peace of code, lead to exactly the same  piece of code! The difference, the working piece is run as 'run selection', i.e. interactive mode, while the non-working piece is run using runfile('bug.py', 'workingdir') (F5 in Spyder). Strange problem and it does not seem to be Spyder related since it also occures in a bare interpreter.

**Comment by mrocklin** [comment]
It looks like this is caused by calling `multiprocessing.Process` from the module level of a Windows script.  This could be resolved on the Dask side by not using a background `Process` object or on the user side by putting this code within an `if __name__ == '__main__':` block

```python
if __name__ == '__main__':
    with ResourceProfiler(dt=0.25) as rprof:
        dask.compute(delayed(sleep)(20))
    visualize([ rprof, ])
```

**Comment by jcrist** [comment]
> This could be resolved on the Dask side by not using a background Process object

It was originally split out into a separate process for two reasons:
- `psutil` requests have some overhead, didn't want to slow down the main process. They're not terribly expensive though, takes ~`100 us` per tick for a pool of 8 workers on my computer.
- Any blocking call in the main process would prevent the profiler from collecting resource usage.

The first I don't think is terribly important, those calls are cheap enough. The second may be an issue in certain cases. I could go either way here. The lack of a separate process would simplify some things, which would be nice.

**Comment by mrocklin** [comment]
I think it's also reasonable to expect users to call code within `if __name__ == '__main__'` blocks.  For example we already expect this if they use the multiprocessing scheduler.

**Comment by HenkHcks** [comment]
Sounds reasonable, but could there be a clear warning, in case someone like me forgets? The error raised is rather cryptic to me, and wasn't shown at all in the IPython session.

**Comment by apiszcz** [comment]
I am noticing a blank plot for the resource profiler in windows and the if __name__ == '__main__' is used to start the main function. The job run time is less than 5 seconds, dt=0.2

**Comment by davidh-ssec** [comment]
I am noticing a blank plot (no results) on OSX due to what seems like the `_Tracker` not being stopped until after the `with` exits.

```
import dask.array as da
from dask.diagnostics import Profiler, ResourceProfiler, CacheProfiler, visualize
a = da.random.random(size=(1000, 100), chunks=(100, 100))
q, r = da.linalg.qr(a)
a2 = q.dot(r)

with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
    out = a2.compute()
    visualize([prof, rprof, cprof])
```

If I move the `visualize` outside the with statement then I only get a single point/result. If I add the following code to `ResourceProfiler._plot` then I get multiple results back.

```
        if self._is_running():
            self._stop_collect()
            self.close()
```

Obviously this is not ideal. Just putting out another case to help find the best solution.

**Comment by jakirkham** [comment]
Are you using NoScript or a similar JavaScript blocker? Have you ensured it allows all local processes and relevant CDNs?

**Comment by davidh-ssec** [comment]
@jakirkham This is not a notebook, just running the above script with `python my_script.py` on OSX Python 3.6 conda environment. I wasn't clear in my first comment but adding the code at the bottom produces a plot with some data on it. It is two straight lines and the cursor probe doesn't show anything so it could just be two points, but adding a print statement to dask in the `ResourceProfiler` shows that it is getting multiple results. Regardless I opened the chrome developer tools and there are no failed resource downloads and I don't have NoScript on.

I did another test after realizing what the problem was and everything is working as expected for me now. My example problem set was too small and was completing faster than the `ResourceProfiler` interval. Decreasing the interval to `0.03` or increasing the problem size (everything * 10) gets me multiple points. This was all with the visualize call after the with block. I'm guessing that's the intended use.

**Comment by jcrist** [comment]
> This was all with the visualize call after the with block. I'm guessing that's the intended use.

That is correct. `visualize` is for plotting completed diagnostics, not currently running ones. For completeness, your example above: 

```python
import dask.array as da
from dask.diagnostics import Profiler, ResourceProfiler, CacheProfiler, visualize
a = da.random.random(size=(1000, 100), chunks=(100, 100))
q, r = da.linalg.qr(a)
a2 = q.dot(r)

with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
    out = a2.compute()

# not in the with block
visualize([prof, rprof, cprof])
```
