### ISSUE TITLE
"ValueError: Sample is not large enough" but the byte size should be enough

### ISSUE THREAD

**Issue by jolespin** [dask/dask#2487]
I'm trying to read in a dataframe in parallel to speed up the i/o for large dataframes.  I'm confused on the "sample" parameter because it wants a byte size to estimate the dtype.  I thought this should be efficient for a row...I even did 2* that but it still didn't work. If this isn't the right way to read a large dataframe in parallel to speed up the process, please direct me to the correct method if possible. 

```
path = './Data/counts/gt2500.counts.tsv.gz'

num_lines = count_lines(path)
num_bytes = os.path.getsize(path)
n_jobs=16
num_lines, num_bytes
(14919, 4129059)
ddf = dd.read_table(path, blocksize=num_bytes//n_jobs, compression="gzip", sample=(num_bytes//num_lines))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-f842422ff0ff> in <module>()
----> 1 ddf = dd.read_table(path, blocksize=num_bytes//n_jobs, compression="gzip", sample=(num_bytes//num_lines)*2)

/Users/jespinoz/anaconda/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    338                            enforce=enforce, assume_missing=assume_missing,
    339                            storage_options=storage_options,
--> 340                            **kwargs)
    341     read.__doc__ = READ_DOC_TEMPLATE.format(reader=reader_name,
    342                                             file_type=file_type)

/Users/jespinoz/anaconda/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    234 
    235     if nparts < skiprows + need and len(b_sample) >= sample:
--> 236         raise ValueError("Sample is not large enough to include at least one "
    237                          "row of data. Please increase the number of bytes "
    238                          "in `sample` in the call to `read_csv`/`read_table`")

ValueError: Sample is not large enough to include at least one row of data. Please increase the number of bytes in `sample` in the call to `read_csv`/`read_table`


import dask, sys
sys.version, dask.__version__
('3.6.1 |Anaconda custom (x86_64)| (default, Mar 22 2017, 19:25:17) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]',
 '0.15.0')
```

**Comment by jcrist** [comment]
This error means that the `sample` isn't large enough to include at least one row of *data*, meaning if you have a header it needs at least 2 rows. In most cases  the default value is large enough to get a good sample, but small enough to still be efficient for inference. Why are you specifying sample directly? Does it also error if you use the default?

A few other points:

- I don't think you can assume the first line is `n_compressed_bytes/n_lines` bytes of the file. The gzip format has a header, and the compression per line isn't consistent. Again, the default sample size is probably fine here.
- If you know the dtypes, you can also specify them directly using the `dtype` kwarg and skip the sample & inference bit.
- In most cases it's more efficient to decompress a gzipped file to disk and then read it in. Gzip doesn't support random access, so each gzipped file is only one partition (no file-level parallelism). If you have multiple small gzipped files this can be fine, but dask won't really help you in the case of one large gzipped file unless you decompress to disk beforehand.

**Comment by jolespin** [comment]
I did `dtype = float` but still got this error `ValueError: Sample is not large enough to include at least one row of data. Please increase the number of bytes in `sample` in the call to `read_csv`/`read_table``.  I tried sample=None and sample as default.

**Comment by jcrist** [comment]
Ah, my mistake. We still use the sample for other stuff, there's no way around that.

What happens if you ungzip the file and then try again? As mentioned above, reading from a single gzipped file won't be performant even if it *works*.

Can you provide a minimal reproducible example that we can run to get the same error? This is the easiest way for us to debug.

**Comment by taylorreiter** [comment]
Was any headway made on diagnosing this error? I'm receiving the same error when reading a 26 GB csv into python:
On ubuntu 16.04
from command line
```
sudo apt-get -y update && \
sudo apt-get install -y python3.5-dev python3.5-venv make \
    libc6-dev g++ zlib1g-dev

python3.5 -m venv ~/py3
. ~/py3/bin/activate
pip install -U pip    
pip install dask[complete] toolz cloudpickle
```

in python
```
import dask.dataframe as dd

filename = 'scaffolds_comp.csv'
df = dd.read_csv(filename)
```

I also tried explicitly declaring the `dtype = 'float'` and `header = 0`.

**Comment by TomAugspurger** [comment]
@taylorreiter are you able to provide a reproducible example?  Some way to generate a dataset similar enough to your CSV that it produces the same error?

**Comment by taylorreiter** [comment]
@TomAugspurger I ended up using `df = dd.read_csv(filename, sample = 2000000)`; I had approximately 44k columns, so I think I needed to be more explicit. Thank you!!
