### ISSUE TITLE
Improved persistence support

### ISSUE THREAD

**Issue by bluenote10** [dask/dask#2492]
Following up on the question about [incremental caching on SO](https://stackoverflow.com/q/44797668/1804173), I'm wondering if it would be possible to offer better persistence support in Dask. I like the idea of the proposed `release` function:

```python
def release(collection):
    for future in futures_of(collection):
        future.release()
```
However the simple implementation is difficult to scale, because it causes trouble on the call-site: For the caller, the futures will be cancelled and the source data becomes unusable. Is it possible to implement `release` in a way that it replaces the cancelled futures by the original DAG representation, so that the caller can still use the original data, just at the cost of re-computation?

This would come very close to how `unpersist` works in Spark. A remaining difference would be that in Spark `persist` / `unpersist` mutate the RDD/DF instance. This makes sense, because both operations don't mutate actual data, but rather transition from a lazy DAG to the cached equivalent. Consider passing a `df` to a sub-function and this functions decides that it is beneficial to persist the input `df`. If the persist is mutable, the call-site can directly benefit from the caching and doesn't have to recompute the DAG up to that point eventually. I'm not sure if it is due to this difference, but it feels a lot easier in Spark to minimize recomputations while avoiding data duplication. Might as well be my lack of Dask experience :-) and solvable on documentation level.

**Comment by mrocklin** [comment]
There are two ways to address this

### Client side

You could store the original (unpersisted) graph somewhere on the client side.  If the user was willing to do some bookkeeping they could do this themselves today:

```python
x2 = x.persist()
```

Then they could delete or release x2 at any time and use the original x afterwards.

If the client held on to the entire graph (see https://github.com/dask/distributed/issues/594) then it could handle this bookkeeping for the user instead.

### Scheduler side

Currently the scheduler eagerly computes anything that it knows about.  We could change this, but it would take some development.

**Comment by mrocklin** [comment]
Of these two solutions client-side solution seems better to me.  I haven't yet seen enough need of this to prioritize the work personally, but would welcome a clean solution that didn't significantly impact performance or maintenance costs.  

I would be inclined to just use the `x2 = x.persist()` solution in the meantime.  You could even make a tiny function around this:

```python
unpersisted = weakref.WeakKeyDictionary()
def persist(x):
    x2 = x.persist()
    unpersisted[x2] = x
    return x2

def unpersist(x2):
    return unpersisted[x2]
```

**Comment by mrocklin** [comment]
This seems to have gone stale.  Closing.
