### ISSUE TITLE
Ability to drop duplicates on Bag based on subset of data

### ISSUE THREAD

**Issue by munro** [dask/dask#2493]
It would be nice if it was possible to drop duplicates on a bag based on a subset of the data, similar to `DataFrame.drop_duplicates(subset=[...])`.  Perhaps the API could be `Bag.distinct(key=lambda x: x['name'])`.

I can help implement this feature, just let me know what the ideal API would be & any ideas on making it performant are greatly appreciated. :D

**Comment by mrocklin** [comment]
Hi @munro this seems useful to me.  The current thing to look at is (as you seem to have found) [Bag.distinct](http://dask.pydata.org/en/latest/bag-api.html#dask.bag.Bag.distinct).  This operates as a reduction, and assumes that the output set will fit nicely into memory in a single partition.  Adding a `key=` keyword seems sensible if it is likely to be used in practice.  Have you taken a look at the current implementation?  Do you have any particular questions?

In case you haven't seen it [this page](http://dask.pydata.org/en/latest/develop.html) has notes about style and testing and such.

**Comment by jcrist** [comment]
I think following the behavior of `toolz.unique` would be good.

It also might be nice to use the same function name here (see https://github.com/pytoolz/toolz/issues/276). Could either deprecate `Bag.distinct` to `Bag.unique`, or `toolz.unique` to `toolz.distinct`.

**Comment by daniel-severo** [comment]
I'll give this a try!
