### ISSUE TITLE
Bcolz backed dataframe to_parquet fails

### ISSUE THREAD

**Issue by BruceChurch** [dask/dask#2496]
When a Dask data frame is backed by bcolz rather than CSV or a Pandas data frame the conversion to parquet fails with TypeError: expected list of bytes

```
import pandas as pd
import dask.dataframe as dd
from blaze import *

#create a dataframe in pandas 
df = pd.DataFrame(data={'A':range(1,1000),'B':range(1001,2000)})
#convert it to bcolz 
dfz = odo(df,'df.bcolz')
# wrap it with dask 
ddf = dd.from_bcolz(dfz,chunksize=100)
# attempt to covert to parquet 
ddf.to_parquet('df.parquet')
```
[How to create a Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)

**Comment by mrocklin** [comment]
Thanks for the concise example @BruceChurch .  I personally am somewhat busy this week or next, but hopefully someone else has some time.

**Comment by mrocklin** [comment]
Unfortunately this passes fine for me.

```python
In [1]: import pandas as pd
   ...: import dask.dataframe as dd
   ...: from blaze import *
   ...: 
   ...: #create a dataframe in pandas 
   ...: df = pd.DataFrame(data={'A':range(1,1000),'B':range(1001,2000)})
   ...: #convert it to bcolz 
   ...: dfz = odo(df,'df.bcolz')
   ...: # wrap it with dask 
   ...: ddf = dd.from_bcolz(dfz,chunksize=100)
   ...: # attempt to covert to parquet 
   ...: ddf.to_parquet('df.parquet')
   ...: 
/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/blaze/server/server.py:17: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  from flask.ext.cors import cross_origin
```

except for some warnings from blaze

**Comment by martindurant** [comment]
@BruceChurch , do you have any suggestion on under what circumstance this happens for you, given that we don't see the same problem? Otherwise, the issue will probably be closed.

**Comment by BruceChurch** [comment]
Thanks everyone, 

I should have included the versions of the relevant packages.    I'm using Anaconda python 2.7 and the problem shows up on both linux and OSX.   I just ran the test code and recovered the same issue on OSX with the following versions of the packages: 

1. Bcolz at 1.1.2 
2. Dask at 0.15.0 
3. FastParquet at 0.1.0
4. Blaze at 0.10.1

These are the versions that are installed by Conda.

**Comment by martindurant** [comment]
I have reproduced the problem with your package versions. For `ddf`, before attempting to write to parquet, the index column metadata appears to be wrong:

    In [14]: ddf.index.dtype
    Out[14]: dtype('O')

    In [16]: ddf.compute().index.dtype
    Out[16]: dtype('int64')

When trying to write this, integers are being encoded using utf8, hence the error.

**Comment by BruceChurch** [comment]
Should I be using different versions?

**Comment by martindurant** [comment]
The successful run above was with bcolz 1.0.0.

**Comment by martindurant** [comment]
Note that if you don't actually want the index in the parquet file, you can do `ddf.to_parquet('df.parquet', write_index=False)`

**Comment by BruceChurch** [comment]
Thanks!  Using the write_index=False allows me to go forward.   

But is the wrong type on the index of ddf a bug?

**Comment by martindurant** [comment]
Yes, I believe this is a bug with the bcloz interaction - I cannot tell whether it is on writing of reading. Using write_index simply ignores those values, so that you avoid the issue.

**Comment by mrocklin** [comment]
Closing.  BColz today is probably going out of scope.
