### ISSUE TITLE
Ability to read Array of JSON in BAG

### ISSUE THREAD

**Issue by vikramsinghchandel** [dask/dask#2499]
I have an array of JSON of the following format
[{"name":"XCV","val":0.767631603323895,"time_hour":"2016-07-01T00:00:00.000Z"},{"name":"SSD","val":0.7640998636682829,"time_hour":"2016-07-01T00:00:00.000Z"}]

**in pandas i can read this by following way**
filePath = "C:/../../a.json"
dframe = pd.read_json(filePath,orient='records')

but i am unable to do so in DASK via json.loads
This following json comes as a HTTP POST response from a time series database

**Comment by mrocklin** [comment]
If you are using dask.bag then you might want to try the following:

```python
import json
import dask.bag as db

b = db.read_text(filePath).map(json.loads)
```

**Comment by vikramsinghchandel** [comment]
Already tried this i treats the whole JSON as a single object but my JSON is an Array of objects.
I need to iterate through each individual JSON and perform some operation on it

**Comment by mrocklin** [comment]
Dask has no trivial way to split apart a single JSON blob.  This is actually somewhat difficult to accomplish.  You could parallelize among many files using dask.delayed if that's an option.

**Comment by vikramsinghchandel** [comment]
I achieved this but in a very bad way i suppose kind of a hack i also think its of no use as it might not give me any performance boost.
Please let me know if this is a good approach and if i get any benefit doing this

import pandas as pd

filePath = "pathToJson"
dframe = pd.read_json(filePath,orient='records')
dask_df_frmPD = df.from_pandas(dframe, npartitions=5)
dask_df_frmPD.visualize() // this shows 5 chunks

Then i iterate over dask_df_frmPD in a for loop

is this a good approach?

**Comment by mrocklin** [comment]
You are not getting parallel reads.  Does this matter to you?  But further operations on the dask dataframe will be in parallel.

You should not use a for loop with dask dataframes.

**Comment by vikramsinghchandel** [comment]
The original issue was when we had a huge file to work upon (2-3 Gb) we were getting out of memory exceptions(Originally the data comes as a HTTP response) we wanted to utilize DASK for this purpose but recently i also read that DASK is not better than pandas and one should stick to pandas for doing stuff.

In the computation logic after we get the response, we pivot the data on timestamp column and then run a for loop for each the data points (Index column) to do the computation. each data point has around 300 column and if the index is at second level than we would have 2592000 data points for a month of data

**Comment by mrocklin** [comment]
Large single-glob json files are hard to parallelize or stream.  Most people have switched to JSON-lines for this reason.  Dask dataframes don't provide efficient random access, so you should not iterate over them with a for loop.

Given that the request here seems to be "support reading a single json array in parallel" and that we aren't able to do this I'm going to close this issue.
