### ISSUE TITLE
dask.array.array is broken/mis-documented

### ISSUE THREAD

**Issue by QuLogic** [dask/dask#2500]
Someone coming from NumPy might think to use `dask.array.array` just as one would do in NumPy. [The documentation](http://dask.pydata.org/en/latest/array-api.html#dask.array.array) shows exactly the same API as NumPy (because it's in fact copied from NumPy's version).

However, if you look at [the code for `array`](https://github.com/dask/dask/blob/master/dask/array/core.py#L3771), it does not accept `copy`, `order`, or `subok`. 

The `object` parameter takes:
>    An array, any object exposing the array interface, an object whose `__array__` method returns an array, or any (nested) sequence.

but you _cannot_ pass a sequence, as the code appears to expect an array subclass:
```python
da.array([1, 2, 3])
```
```pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-115-b769122294bb> in <module>()
----> 1 da.array([1, 2, 3])

/usr/lib/python3.5/site-packages/dask/array/core.py in array(x, dtype, ndmin)
   3633 @wraps(np.array)
   3634 def array(x, dtype=None, ndmin=None):
-> 3635     while x.ndim < ndmin:
   3636         x = x[None, :]
   3637     if dtype is not None and x.dtype != dtype:

AttributeError: 'list' object has no attribute 'ndim'
```
and even ignoring the `ndim` thing, the code doesn't really do any conversion.

Additionally, the default value for `ndmin` causes an error #1847:
```python
a = np.array([1, 2, 3])
da.array(a, ndmin=0)
```
```pytb
TypeError                                 Traceback (most recent call last)
<ipython-input-112-66eebf33e458> in <module>()
      1 a = np.array([1, 2, 3])
----> 2 da.array(a)

/usr/lib/python3.5/site-packages/dask/array/core.py in array(x, dtype, ndmin)
   3633 @wraps(np.array)
   3634 def array(x, dtype=None, ndmin=None):
-> 3635     while x.ndim < ndmin:
   3636         x = x[None, :]
   3637     if dtype is not None and x.dtype != dtype:

TypeError: unorderable types: int() < NoneType()
```

**Comment by mrocklin** [comment]
Hi @QuLogic see this issue: https://github.com/dask/dask/issues/1815

If you have time to help out with this that would be greatly appreciated.

**Comment by mrocklin** [comment]
This issue is still live, but in a different way:

```python
In [1]: import dask.array as da

In [2]: da.array([1, 2, 3])
Out[2]: [1, 2, 3]
```

This should probably return a single-chunked dask array

**Comment by Madhu94** [comment]
I think this issue seems fixed in the latest dask? It would be good to close.
