### ISSUE TITLE
Dask major release (v1) plan?

### ISSUE THREAD

**Issue by lbdreyer** [dask/dask#2515]
Dask is getting quite mature now. Is there a plan for a major release (i.e. Dask v1.0.0)?

**Comment by mrocklin** [comment]
There are no short terms plans for this.  Does the current 0.x.x version number affect you in some way?

**Comment by lbdreyer** [comment]
I am familiar with SemVer which states that version 1.0.0 defines the public API and until then the public API should not be considered stable.

Now that Dask is a dependency of Iris I am interested in any breaking changes to the API that may impact us, for example the change in dask v0.15 of moving dask.async to dask.local.

It would be nice to see a stable API so I just wanted to check if that was on your radar.

**Comment by mrocklin** [comment]
It is hard to define stability for a library with many differently evolving components.  Parts like dask.array are very stable while other parts, like the concurrent.futures task interface still change.  As a result using the SemVer definition is somewhat problematic for us.

Regarding dask.async to dask.local this was forced by changes within the Python language (`async` became a keyword and will be invalid in 3.7).  This is a good example of how a certain amount of stability is just out of our hands.

**Comment by lbdreyer** [comment]
We mostly use dask.array so that should be okay.

Thanks for clarifying @mrocklin !

**Comment by mrocklin** [comment]
Informally dask.array is fairly stable and under enough use that any
significant API change would probably go under a standard deprecation
cycle.  We also tend to consult with notable downstream projects before
making these changes.
