### ISSUE TITLE
to_parquet fails while to_csv works (distributed backend)

### ISSUE THREAD

**Issue by redst4r** [dask/dask#2516]
Hi,

I have some trouble saving results with `to_parquet` in the distributed backend (on the filesystem of the worker nodes. Note that the filesystem is shared across workers). 
Here's an example:

```python
import numpy as np
from dask.distributed import Client
import dask.dataframe as dd
import dask
import random
import pandas as pd

client = Client('xx.xx.xx.xx:8786')  # connect to remote scheduler
remote_folder = '/users/myaccount/dask_testfolder/'

@dask.delayed
def create_content(r,c):
    return pd.DataFrame(np.random.rand(r,c))

X = create_content(10000,100)
df = dd.from_delayed(X)

# this works fine; creates a single file /users/myaccount/dask_testfolder/0.part
df.to_csv(remote_folder)

#this fails
df.to_parquet(remote_folder)
```
Here's the error thrown by `to_parquet`:
```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
/anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/local.py in mkdirs(self, path)
     43         try:
---> 44             os.makedirs(path)
     45         except OSError:

/anaconda3/envs/py36/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    209         try:
--> 210             makedirs(head, mode, exist_ok)
    211         except FileExistsError:

/anaconda3/envs/py36/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    209         try:
--> 210             makedirs(head, mode, exist_ok)
    211         except FileExistsError:

/anaconda3/envs/py36/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    209         try:
--> 210             makedirs(head, mode, exist_ok)
    211         except FileExistsError:

/anaconda3/envs/py36/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    219     try:
--> 220         mkdir(name, mode)
    221     except OSError:

PermissionError: [Errno 13] Permission denied: '/users'

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-5-b0722763efbb> in <module>()
     20 
     21 #this fails
---> 22 df.to_parquet(remote_folder+'/subdoldwe')

/anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
    953         """ See dd.to_parquet docstring for more information """
    954         from .io import to_parquet
--> 955         return to_parquet(path, self, *args, **kwargs)
    956 
    957     def to_csv(self, filename, **kwargs):

/anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in to_parquet(path, df, compression, write_index, has_nulls, fixed_text, object_encoding, storage_options, append, ignore_divisions, partition_on, compute)
    361     fs, paths, myopen = get_fs_paths_myopen(path, None, 'wb',
    362                                             **(storage_options or {}))
--> 363     fs.mkdirs(path)
    364     sep = fs.sep
    365     metadata_fn = sep.join([path, '_metadata'])

/anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/local.py in mkdirs(self, path)
     44             os.makedirs(path)
     45         except OSError:
---> 46             assert os.path.isdir(path)
     47 
     48     def open(self, path, mode='rb', **kwargs):
```

I'm not sure what's going on, but I have the feeling that dask somehow tries to write the parquet files on my local machine (where I execute the above code) instead of on the remote workers.
On my machine the `remote_folder` doesnt exist (e.g. /users/) and that's why it fails with permission errors.

What puzzles me is that `to_csv` works flawless and creates the .csv on the workers!

As a sidenote: There's similar issues when I try loading data located on the worker file-system via read_csv:
```
dd.read_csv(remote_folder+'/*')
```

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-8-331a662ae29b> in <module>()
----> 1 dd.read_csv(remote_folder+'/*')

anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    338                            enforce=enforce, assume_missing=assume_missing,
    339                            storage_options=storage_options,
--> 340                            **kwargs)
    341     read.__doc__ = READ_DOC_TEMPLATE.format(reader=reader_name,
    342                                             file_type=file_type)

anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    218                                   sample=sample,
    219                                   compression=compression,
--> 220                                   **(storage_options or {}))
    221 
    222     if not isinstance(values[0], (tuple, list)):

anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, **kwargs)
    137     client = None
    138     if len(paths) == 0:
--> 139         raise IOError("%s resolved to no files" % urlpath)
    140 
    141     if blocksize is not None:

OSError: /users/myaccount/dask_testfolder//* resolved to no files
```

I all seems to boil down to: How do I tell dask to look at the remote workers' filesystem instead of my local one??

**Comment by martindurant** [comment]
This is not unexpected: when you do `to_parquet`, each worker writes files from the chunks of data, but the metadata file is written from your local process. One workaround would be to use `to_parquet(..., compute=False)`, which will give you back a delayed object, and then call `compute()` on this object - then the final write should happen in a worker too.

Similarly for the read_csv case, the file-list is generated in the local process. You could maybe execute the file listing on a worker like

    files = client.gather(client.submit(glob.blog, filepath))

and pass the list of files instead of the glob string to read_csv.

**Comment by redst4r** [comment]
Thx for your help!

```python
delayed_write= df.to_parquet(remote_folder, compute=False)
```
gives me the same error as before (even without calling `compute()` afterwards).

```python
files = client.gather(client.submit(glob.glob, remote_folder+'/*.csv'))
dd.read_csv(files)
```
fails with 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-156-793138575d1c> in <module>()
----> 1 df_read_csv= dd.read_csv(files)

anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    338                            enforce=enforce, assume_missing=assume_missing,
    339                            storage_options=storage_options,
--> 340                            **kwargs)
    341     read.__doc__ = READ_DOC_TEMPLATE.format(reader=reader_name,
    342                                             file_type=file_type)

anaconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, **kwargs)
    218                                   sample=sample,
    219                                   compression=compression,
--> 220                                   **(storage_options or {}))
    221 
    222     if not isinstance(values[0], (tuple, list)):

anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, **kwargs)
    156         for path in paths:
    157             try:
--> 158                 size = fs.logical_size(path, compression)
    159             except KeyError:
    160                 raise ValueError('Cannot read compressed files (%s) in byte chunks,'

anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/core.py in logical_size(self, path, compression)
    506             compression = infer_compression(path)
    507         if compression is None:
--> 508             return self.size(path)
    509         else:
    510             with self.open(path, 'rb') as f:

anaconda3/envs/py36/lib/python3.6/site-packages/dask/bytes/local.py in size(self, path)
     69         """Size in bytes of the file at path"""
     70         path = self._trim_filename(path)
---> 71         return os.stat(path).st_size
     72 
     73 

FileNotFoundError: [Errno 2] No such file or directory: '/users/myaccount/dask_testfolder/3.csv'
```
the `files`-list has the expected content however (first entry being `/users/myaccount/dask_testfolder/3.csv`)

The cheap way out of this would be to start the "client" session also on the worker/scheduler node, but I guess that's not really the point...

I wonder how it works for "truely remote" content, e.g. data on S3. Here dask also seem to know that it shouldn't look for the data on the local machine.

**Comment by martindurant** [comment]
Oh I see - it's trying to make the directory to write into. You could monkey-patch dask.bytes.local.LocalFileSystem.mkdirs to a no-op, and make sure that the directory does exist for your workers... inelegant, but it may work.
Even S3, GCS et al., only work if both the client and the workers can access the remote source, which often means moving credentials around. I was not aware that this was a pain for anyone - it would be possible to do all of the current client logic in a worker, but it would take effort to implement.

**Comment by redst4r** [comment]
Hi,

Ok that means even for S3, the client would pull down some info (such as a directory listing) from S3 to build the dask-graph which is subsequently submitted to the scheduler/workers. I didn't realize til now the the dask graph is assembled on the client...

> I was not aware that this was a pain for anyone

There's actually a good chance that I'm using the whole thing the wrong way... Basically what I want to do is create/simulate some data on the workers (expensive operation), save it to disk (as csv, parquet...) and then later on do some analysis on the workers again (i.e. reloading from the csvs and running some functions on them).

**Comment by mrocklin** [comment]
@martindurant what is the status here?  Can this be closed?

**Comment by martindurant** [comment]
This falls into "untypical use", I think - it ought to work without resorting to the tricky workarounds I tried to describe above, but most people won't experience this situation. The better fix would maybe be to change to_parquet to delay the final write also. Maybe.

**Comment by mrocklin** [comment]
I encourage you to make a judgement call here and either outline what should change within the codebase (if changes should indeed be made) or close this stating that we're unlikely to make these changes because the situation is too rare, or because it would have other negative effects.

**Comment by martindurant** [comment]
It would require going through all the IO functions, and making sure that any access to a path or listing directories, etc., remote or otherwise, is done via delayed/compute. I suspect tat would be quite involved.

Side issue: would be interesting and easy to make a WorkerFileSystem implementation, where every operation is passed to a worker for evaluation; effectively a DelayedLocalFileSystem.

**Comment by jsignell** [comment]
It seems like you have now written that filesystem @martindurant :) - good to close?

**Comment by martindurant** [comment]
True! I don't think it gets used, but it could be...

**Comment by CarterFendley** [comment]
@martindurant Still seeing issues with the `read_csv` and others accessing the local file system. Especially for instances with dask kubernetes where the data is on PersistantVolumes, and the client is accessing the cluster remotely it is causing a lot of headache.

```
Traceback (most recent call last):
  File "/miniconda3/envs/my-env/lib/python3.10/site-packages/dask/backends.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/miniconda3/envs/my-env/lib/python3.10/site-packages/dask/dataframe/io/csv.py", line 731, in read
    return read_pandas(
  File "/miniconda3/envs/my-env/lib/python3.10/site-packages/dask/dataframe/io/csv.py", line 524, in read_pandas
    b_out = read_bytes(
  File "/miniconda3/envs/my-env/lib/python3.10/site-packages/dask/bytes/core.py", line 111, in read_bytes
    size = fs.info(path)["size"]
  File "/miniconda3/envs/my-env/lib/python3.10/site-packages/fsspec/implementations/local.py", line 99, in info
    out = os.stat(path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/pvc-vol/G1_1e7_1e2_0_0.csv'
```

@jsignell Suggested there might have been some progress on this?

**Comment by CarterFendley** [comment]
Okay I did some digging and found [DaskWorkerFileSystem](https://github.com/fsspec/filesystem_spec/blob/6b85a471733124de6e30edf4e16425ee8d30291d/fsspec/implementations/dask.py#L24) implementation which has been [registered here](https://github.com/fsspec/filesystem_spec/blob/6b85a471733124de6e30edf4e16425ee8d30291d/fsspec/registry.py#L92-L95).

I have tested with `read_csv` and `read_bytes` and it is working!
```python
# read_csv
dask.dataframe.read_csv(
    "dask://" + filepath,
    storage_options={
        "target_protocol": "file"
    }
)

# read_bytes
dask.bytes.read_bytes(
    "dask://" + filepath,
    target_protocol="file"
)
```

I was not previously a big user of `fsspec` so my understand of the `target_protocol` is the protocol which you want the worker to access the file from, presumably would work with `s3` or similar although I have not tested this. You can also [pass an existing fs instance](https://github.com/fsspec/filesystem_spec/blob/6b85a471733124de6e30edf4e16425ee8d30291d/fsspec/implementations/dask.py#L37-L41), although I am not familiar with that and assumed I didn't have one.

[This document](https://docs.dask.org/en/stable/how-to/connect-to-remote-data.html#connect-to-remote-data) was helpful for general understanding.
