### ISSUE TITLE
Problems with tutorial

### ISSUE THREAD

**Issue by loisks317** [dask/dask#2517]
Hi Dask Team, 

You're doing a great job, and I realize this is a pain, but I wanted to let you know that I've spent 2+ hours trying to get this tutorial to run and I can't. I'm running into install problems between pytables and graphviz packages to the point where I'm (A) not able to run the tutorial and (B) going to try to find or develop a simpler tutorial. I know you all have spent a lot of time making the tutorial as is, but I think for non-conda users like me, it's too much effort and tracing back errors in package installs (i.e. different versions) to even get the first line of code executed. A simpler tutorial that focuses more on dask and less on other packages would be much appreciated.

**Comment by martindurant** [comment]
Do you mean https://github.com/dask/dask-tutorial ? If you could specify your problems in issues there, we will endeavour to fix things as quickly as we can get to them.
It is in general true that dask is such a useful package in great deal thanks to the numerical python ecosystem in general, and that a great majority of users  will install via conda (which also makes life easier for us). We do hope to keep pip and source installation options available, so if you are having problems installing dask itself, then please describe your experience here.

**Comment by loisks317** [comment]
I know, I'm being vague, haha, and it's because I worked through a lot of the problems. The current error is in executable 1 of overview-01 of the dask-tutorial where you do %run prep.py: 
`---------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/loiskeller/Downloads/dask-tutorial-master/prep.py in <module>()
     87 if __name__ == '__main__':
     88     random_array()
---> 89     create_weather()
     90     accounts_csvs(3, 1000000, 500)
     91     accounts_json(50, 100000, 500)

/Users/loiskeller/Downloads/dask-tutorial-master/prep.py in create_weather(growth)
     74             x = f['/t2m'][:]
     75 
---> 76         y = imresize(x, growth)
     77 
     78         out_fn = os.path.join('data', 'weather-big', os.path.split(fn)[-1])

/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/misc/pilutil.pyc in imresize(arr, size, interp, mode)
    418         size = (size[1],size[0])
    419     func = {'nearest':0,'bilinear':2,'bicubic':3,'cubic':3}
--> 420     imnew = im.resize(size, resample=func[interp])
    421     return fromimage(imnew)
    422 

/Library/Python/2.7/site-packages/PIL/Image.pyc in resize(self, size, resample)
   1697         self.load()
   1698 
-> 1699         size = tuple(size)
   1700         if self.size == size:
   1701             return self.copy()

TypeError: 'float' object is not iterable`

This is an error within how pillow, scipy, and pytables are talking to each other. My issue isn't something that you can necessary 'fix' with a debug, it's that to get this tutorial working, I had to do so many installs and configurations and work through so many error messages that it became not worth it for me to continue. I'm a data scientist whose been using Python for 7 years... I'm not new to Python. A tutorial with fewer required packages just to get the essence of dask would be great. It's a huge loss for the community to turn people off dask because the tutorial requires conda or a day's worth of time to get working.

**Comment by martindurant** [comment]
You are right on a couple of points: 
- the tutorial is not tested and not particularly built with non-conda in mind; this should be at the very least clearly stated. The environment.yaml specifies py35.
- given that pure dask doesn't have anywhere near the same amount of dependencies, and can be pip-installed alone, it could be reasonable to have some section dedicated to raw dask usage.

Have you tried using the Dockerfile? That builds a full conda-based stack in a container for you. Actually, it uses a set of packages described in the docker-file, not the same environment file, above, which is undesirable.

**Comment by loisks317** [comment]
Thanks :) 

It's worth having a non-conda tutorial. I know conda is becoming standard, but it's actually tough sometimes to install non-conda modules. In graduate school I had to use a lot of non-standard modules like spacepy, etc. and conda made installing those a nightmare. Blagh. 

I'm working on building a dask tutorial for myself and my group, so I will share it with you all when I'm done. I would **love** any feedback. 

I haven't tried the docker file yet. I'm not a big docker user, but it's worth a try too.

**Comment by martindurant** [comment]
Certainly happy to look through any tutorial work you produce, or if you wish to contribute any of it back here. 
Interestingly, there was an attempt to build [spacepy for conda](https://github.com/conda-forge/staged-recipes/pull/1781), but they did not manage to iron out compile problems. I wouldn't know how to fix that - do you? :)

**Comment by jcrist** [comment]
Closing as stale. If you have specific issues with the dask tutorial please open them at https://github.com/dask/dask-tutorial. You might also be interested in https://github.com/jcrist/dask-tutorial-pydata-seattle-2017 which is a smaller tutorial with a more minimal set of dependencies.
