### ISSUE TITLE
ResourceProfiler blank graph output on Windows question

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#2521]
Dask 0.15.1, Python 3.5.3, psutil 5.2.2, Windows 10/64
The standard dask profiler works correctly. The ResourceProfiler is producing a blank graph, reviewing the returned results shows and empty [] list. I would be interested in any suggestions to debug/resolve what may be causing the empty result. The _Tracker method in profile.py might be the issue, I noticed a passive exception. To debug I opened a file in _Tracker and tried writing mem2 and cpu2 to it, and the file is empty upon complete with one input file. So it seems the loop may not be connecting to the child?

```
                        except Exception: # could be a few different exceptions
                            pass

```

Adding the the lines shown below with ## at the end produced the following output.
```
3052, msg: collect
3052, ps: [<psutil.Process(pid=10164, name='python.exe') at 1943868503600>, <psutil.Process(pid=3052, name='python.exe') at 1943868368152>]
3052, msg: collect
3052, ps: [<psutil.Process(pid=10164, name='python.exe') at 1943868503600>, <psutil.Process(pid=3052, name='python.exe') at 1943868503264>]
3052, msg: send_data
3052, msg: shutdown
```

```
    def run(self):
        import os ##
        dfile=open('log.txt','w') ##
        mypid=os.getpid() ##
        pid = current_process()
        ps = self._update_pids(pid)
        data = []
        while True:
            try:
                msg = self.child_conn.recv()
                dfile.write('%d, msg: %s\n'%(mypid,msg)) ##
            except KeyboardInterrupt:
                continue
            if msg == 'shutdown':
                break
            elif msg == 'collect':
                ps = self._update_pids(pid)
                dfile.write('%d, ps: %s\n'%(mypid,ps)) ##
                while not self.child_conn.poll():
                    tic = default_timer()
                    mem = cpu = 0
                    for p in ps:
                        dfile.write('%d, p: %s\n' %(mypid,p))
                        try:
                            mem2 = p.memory_info().rss
                            cpu2 = p.cpu_percent()
                            dfile.write('%d, mem2:%f, cpu2:%f, p: %s\n' % (mem2,cpu2,mypid, p)) ##
                        except Exception: # could be a few different exceptions
                            pass
                        else:
                            # Only increment if both were successful
                            mem += mem2
                            cpu += cpu2
                    data.append((tic, mem / 1e6, cpu))
                    sleep(self.dt)
            elif msg == 'send_data':
                self.child_conn.send(data)
                data = []
        dfile.close()
        self.child_conn.close()

```

**Comment by jcrist** [comment]
Does psutil work fine for you normally?

```python
import psutil
p = psutil.Process(os.getpid())
p.memory_info().rss
p.cpu_percent()
```

Can you provide a [minimum reproducible example](https://stackoverflow.com/help/mcve)?

**Comment by apiszcz** [comment]
Yes

> py test.py
15695872
0.0


import os,psutil
p = psutil.Process(os.getpid())
print(p.memory_info().rss)
print(p.cpu_percent())

**Comment by bmerry** [comment]
I notice that the unit test for `ResourceProfiler` doesn't check that any results come back, only that the results that do come back have the right shape.

**Comment by apiszcz** [comment]
This is issue has been resolve. it can be closed.

**Comment by bmerry** [comment]
@apiszcz What was the solution?

**Comment by apiszcz** [comment]
User error. I had the visualize call indented incorrectly, (it was inside
the inner loop, instead of outside the loop).
NOTE: I have created some VERY large rprof html files > 500MB, they don't
seem to load in Chrome/IE/FFOX, so I'm guessing I'll need to reduce the
sampling time.
