### ISSUE TITLE
Problems building docs with sphinx 1.5.6

### ISSUE THREAD

**Issue by detrout** [dask/dask#2530]
I'm attempting to build the documentation for dask 1.15.1 for the Debian package, using sphinx 1.5.6, pandas 0.20.3, python 3.5.3 and numpydoc 0.7.0, and it's currently failing to build from source.

With the error:

Exception occurred:
  File "/usr/lib/python3/dist-packages/numpydoc/docscrape.py", line 343, in _pae
    raise ValueError(msg)
ValueError: The section Notes appears twice in the docstring of None in None.
The full traceback has been saved in /tmp/sphinx-err-_mt1fzrj.log, if you want .

If I disable this code in dask/utils.py:derived_from
`python
            if len(not_supported) > 0:
                note = ("\n        Notes\n        -----\n"
                        "        Dask doesn't support the following argument(s).\n\n")
                args = ''.join(['        * {0}\n'.format(a) for a in not_supported])
                doc = doc + note + args
`
It'll build, I also found changing Notes to Extra Notes, and adding extra ------ in the restructured text heading markup worked.

**Comment by mrocklin** [comment]
Hi @detrout !  First, thank you for the well worded issue.  

I ran into this as well.  My solution was here: https://github.com/dask/dask/pull/2512 .  However that as merged before the last release, so I would expect you to get that solution regardless.

**Comment by detrout** [comment]
Sadly pinning numpydoc to an earlier version is one of those things Debian packaging isn't good at.

I wonder why it's still getting the duplicate Notes error even though extra_titles() is being called and does appear to be changing the doc string to "Extra Notes"

**Comment by mrocklin** [comment]
Yeah, the fix in that PR resolved the issue for us.  I'm not entirely sure
what's happening here.

**Comment by detrout** [comment]
The fix in #2512 that resolved the exception was pinning numpydoc to 0.6.0. At least for me, the doc build fails with numpydoc 0.7.0 and with numpydoc 0.8.0.dev.0 (commit 057ef572dd5ea547af2832e1b68d934cf953eafe)

**Comment by detrout** [comment]
I stuck a pdb.set_trace in docscrape.py just before the raise ValueError, and tried to figure out what the duplicate Notes sections were... It seems almost like they're documentation for two different functions? (I'll try to attach the body of the two sections to the issue.)

Would you mind if I renamed the section about unsupported arguments to 'Caution'? for the Debian packaging?

```
--- a/dask/utils.py
+++ b/dask/utils.py
@@ -496,7 +496,7 @@
                 not_supported.extend(ua_args)
 
             if len(not_supported) > 0:
-                note = ("\n        Notes\n        -----\n"
+                note = ("\n        Caution\n        -------\n"
                         "        Dask doesn't support the following argument(s).\n\n")
                 args = ''.join(['        * {0}\n'.format(a) for a in not_supported])
                 doc = doc + note + args
```

It does trigger unknown section errors, but the build finishes at least.

**Comment by detrout** [comment]
The blocks were pretty long. I put them in gists.

https://gist.github.com/detrout/26459718e933bcc3feab0151fc66bbee
https://gist.github.com/detrout/32f19ebcddfacee9e6bd4d1cf33ffa37

**Comment by jakirkham** [comment]
Has this been raised as a numpydoc issue or does this overlap with an existing numpydoc issue?

**Comment by mrocklin** [comment]
Renaming Notes to Caution seems sensible to me.  Sorry for the delay @detrout .  We could do this in the mainline codebase as well.

@jakirkham I haven't personally reported upstream.  If you feel like doing this I would be obliged.

**Comment by detrout** [comment]
I haven't reported it to numpydoc and I haven't found a similar case either.

Do you know of any other projects trying to inherit docstrings like you are?

As far as I can tell your extra_docs function always works, If there's two notes sections, one of them is renamed to Extra Notes. I just can't figure out why numpydoc cares.

I added some code to write out all of the docstrings, and discovered the indentation wasn't always consistent. DataFrame functions mask and where, and SeriesGroupBy functions agg and aggregate have a different indentation from the Notes block being added, but suppressing adding the "doesn't support" note didn't stop the sphinx traceback

**Comment by mrocklin** [comment]
I believe that this has been resolved.  The doc building on RTD seems to work well.  Regardless, this issue has gone stale.  Closing.
