### ISSUE TITLE
Client() and rpy2

### ISSUE THREAD

**Issue by rpanai** [dask/dask#2532]
I have a dask dataframe and I'm calling some R function with apply. It's everything working fine and I'm having the same results as in R as long as I avoid to call

    from dask.distributed import Client
    client = Client()

If I use `Client` I experience the following error:

    NotImplementedError: Conversion 'py2ri' not defined for objects of type '<class 'pandas.core.series.Series'>'

**Comment by mrocklin** [comment]
Interesting.  My first impression is that that looks like an `rpy2` error.  Do things work with the single-machine task schedulers?  What happens if you use dask.dataframe without invoking a `Client` object (this uses threads by default?

How about if you use the multiprocessing scheduler?

```python
import dask.multiprocessing
dask.set_options(get=dask.multiprocessing.get)
```

**Comment by rpanai** [comment]
Without invoking  a `Client` it works flawlessy. I'm going to try the method you are suggesting.

**Comment by martindurant** [comment]
rpy2 instantiates an embedded R interpreter, with it's own set of objects separate from python globals - I assume that thing cannot be serialized.

**Comment by rpanai** [comment]
@mrocklin If I use the `multiprocessing scheduler` (which I still have to understand what it does) it slow as hell but it produce the dataframe without any error.

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if it's still an issue and you can provide a [minimal reproducible example](https://stackoverflow.com/help/mcve).
