### ISSUE TITLE
Feature Request: Dask Dataframe to Support Transform Method

### ISSUE THREAD

**Issue by mmcky** [dask/dask#2536]
It would be great if dask dataframe supported the ``transform`` method that is similar to [pandas transform](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.transform.html). 

It is very convenient to ``split-apply`` and then ``transform`` which can be used, for example, to append the group means (or other transformations) and return a single dataframe. 

Here is a good example of its use case: http://pbpython.com/pandas_transform.html

**Comment by rpanai** [comment]
I second this one.

**Comment by mrocklin** [comment]
Assuming you mean groupby-transform this would be fairly similar to `groupby.apply`.  Are either of you interested in submitting a PR that modifies the current implementation?  If you're lucky it may be that you only need to change the last line that is annotated with the following comment

    # Perform embarrassingly parallel groupby-apply

with a function that instead does a groupby-transform.  Ideally this change would be refactored into a general method with two shorter methods for `apply` and `transform` that used the general one.

**Comment by mmcky** [comment]
@mrocklin I will try and take a closer look at [groupby.py](https://github.com/dask/dask/blob/master/dask/dataframe/groupby.py) on the weekend to see if I can get this up and running. Thanks for the pointer to ``groupby.apply``

**Comment by EDUARDO78** [comment]
Any luck on this?  I have a click log consisting of 200 million rows.  I'm attempting to create features by frequency.  So for instance if I have IP and channel as a feature I'm attempting to add an ip_channel_frequency feature to the same dataframe.

ip    channel
123 12
123 12
145 49

Should look like
ip    channel frequency
123 12          2    
123 12          2
145 49          1

df['ip_channel_frequency'] = df.groupby(['ip','channel'],ip.transform('size')

Doesn't work due to the transform method not being implemented

**Comment by faizanahemad** [comment]
Is there an API for this now?

**Comment by mrocklin** [comment]
To my knowledge no one has volunteered the time to do this.  If any of the people discussing this issue are interested it sounds like others would find it valuable.

**Comment by ddebernardy** [comment]
@carlosdanielcsantos I'm not familiar with Dask's internals either but intuitively Approach 2 might be failing without setting the groupby column as the explicit index because Dask needs to re-arrange the data so that identical index values don't end up in multiple partitions.

**Comment by OliverHofkens** [comment]
I decided to try my hand at this one, and on first sight it seems like @mrocklin was right in https://github.com/dask/dask/issues/2536#issuecomment-317518635: This isn't very different from `groupby().apply()`.
I drafted up a small PR to prove that it works fine: https://github.com/dask/dask/pull/5327

I still need to refactor out the code it shares with `apply()`, and I'll need to check how this interacts with `Aggregation` and other Dask specifics.

**Comment by OliverHofkens** [comment]
Implemented in https://github.com/dask/dask/pull/5327 ✅

**Comment by TomAugspurger** [comment]
Thanks @OliverHofkens!
