### ISSUE TITLE
ResourceProfile has different behaviour using context manager vs `register`

### ISSUE THREAD

**Issue by bmerry** [dask/dask#2551]
I'm using the dask profilers with the pattern
```
for profiler in profilers: profiler.register()
foo() # Do work, some of it dask, some of it other
for profiler in profilers: profiler.unregister()
```
(although with some try/finally stuff to make it more robust). I had assumed that this would be equivalent to running `foo` under a context manager per profiler, except that the `with` statement doesn't allow for unpacking so can't take a variable number of context managers (and `contextlib.nested` is deprecated and I'm on Python 2 so can't use `ExitStack`). However, the `ResourceProfiler` code has specific checks for whether it is currently being used as a context manager (`_enter` member) and if not, it stops tracking resources as soon as a computation is complete (in `_finish`), which leads to gaps in the graph whenever no dask computation is running.

Example code:
```python
#!/usr/bin/env python
import dask.array as da
from dask.diagnostics import ResourceProfiler
import time

def foo():
    x = da.ones(1000000000, chunks=1000000)
    da.dot(x, x).compute()  # Keep things busy for a while
    time.sleep(3)
    da.dot(x, x).compute()  # Keep things busy again

profiler = ResourceProfiler(dt=0.2)
profiler.register()
foo()
profiler.unregister()
profiler.visualize()
```

**Comment by jcrist** [comment]
> except that the with statement doesn't allow for unpacking so can't take a variable number of context managers

For non variable numbers, you can do:

```
with ResourceProfiler() as rprof, Profiler( )as prof:
    ...
```

which is my common pattern.

> it stops tracking resources as soon as a computation is complete (in _finish)

This mirrors the other profilers, which also only track during dask computation. As a context manager the `ResourceProfiler` is actually an exception, as it can be used to profile non-dask code (always tracks around a context). I'm slightly against changing this behavior. What would you want this to be instead?

**Comment by bmerry** [comment]
I'd got the impression from the documentation that they were [intended to be] exactly equivalent, with the context manager just being a convenient way to ensure cleanup, but it sounds like that wasn't the intention. Maybe it just needs a bit of clarification in the documentation.
