### ISSUE TITLE
dask.dataframe.read_csv() error with compression

### ISSUE THREAD

**Issue by andybrnr** [dask/dask#2554]
Hi,

I have a collection of csv files encoded with .zip format, but when trying to read into a dask dataframe, I get a NotImplementedError: Compression format zip not installed. In my current pandas version (0.20.1), it successfully infers and decompresses the file on my system. Is this a minor tweak? Would like to avoid converting the compression type on all my files.

Thanks,
Andy

Trace:
  File "/home/andy/anaconda3/envs/my_env/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 323, in read
    **kwargs)

  File "/home/andy/anaconda3/envs/my_env/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 213, in read_pandas
    compression)

NotImplementedError: Compression format zip not installed

python 3.6
dask 0.14.3

**Comment by jcrist** [comment]
What happens if you specify `compression='zlib'` in the call to `read_csv`?

**Comment by mrocklin** [comment]
Dask.dataframe does not currently support zip compression.  We could, but this would only work with `blocksize=None`.  In the meantime you might consider loading up your data using dask.delayed

https://gist.github.com/mrocklin/e7b7b3a65f2835cda813096332ec73ca
http://dask.pydata.org/en/latest/delayed-collections.html

**Comment by andybrnr** [comment]
Hi Jim,

Thanks so much for the quick response!

Still no joy, trace below:

df_csv = dd.read_csv(file, compression='zlib')

/home/andy/anaconda3/envs/my_env/lib/python3.6/site-packages/dask/dataframe/io/csv.py:209:
UserWarning: Warning zlib compression does not support breaking apart files
Please ensure that each individual file can fit in memory and
use the keyword ``blocksize=None to remove this message``
Setting ``blocksize=None``
  "Setting ``blocksize=None``" % compression)
Traceback (most recent call last):

  File "<ipython-input-7-d5e701c222cf>", line 1, in <module>
    df_csv = dd.read_csv(file, compression='zlib')

  File
"/home/andy/anaconda3/envs/my_env/lib/python3.6/site-packages/dask/dataframe/io/csv.py",
line 323, in read
    **kwargs)

  File
"/home/andy/anaconda3/envs/my_env/lib/python3.6/site-packages/dask/dataframe/io/csv.py",
line 213, in read_pandas
    compression)

NotImplementedError: Compression format zlib not installed



Thanks,
Andy

**Comment by andybrnr** [comment]
@mrocklin got it, thanks. Turns out I've got to do some preprocessing/cleaning anyway, I'll just transcode them at the same time. Thanks again for the quick answer!

Best,
Andy

**Comment by jcrist** [comment]
Looks like this was resolved. Closing. Feel free to reopen if there are still issues.

**Comment by tpanza** [comment]
@jcrist can support for zip compression not be added to Dask? (perhaps with caveat of `blocksize=0` that @mrocklin mentioned)

If `dd.read_csv` uses `pandas.read_csv` and `pandas.read_csv` now supports zip compression, then shouldn't Dask as well?

(Sorry if this is a dumb question... just discovered and learning Dask today. My first use case is with very large and zipped CSV files. Will look at dask.delayed in the meantime. But it seems that ultimately Dask should provide support for zip compression...)

**Comment by mrocklin** [comment]
@tpanza note that with blocksize=0 large and zipped CSV files would be read in as a single pandas dataframe.  There would be no intra-file parallelism. 

In general I agree that this should be possible.  Perhaps you'd like to take a crack at implementing it and submit a PR?

**Comment by Hoeze** [comment]
Wouldn't it be possible to have some index on the gzipped file, like e.g. Tabix or this:
https://github.com/mattgodbolt/zindex

**Comment by mrocklin** [comment]
Perhaps, but that's probably out of scope for the core Dask project.  You could definitely build something like that fairly easily using dask delayed and dask dataframe together.  See https://docs.dask.org/en/latest/dataframe-create.html#dask-delayed

However in general if people are going to get creative and if their context allows it, we recommend using a more modern format like Parquet or ORC, where all of these problems are already solved.
