### ISSUE TITLE
Adding ravel_multi_index and unravel_index

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2557]
Would be nice to have Dask implementations of [ravel_multi_index]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel_multi_index.html ) and [unravel_index]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.unravel_index.html ). These are particularly nice to have as we are starting to look at Dask index arrays ( e.g. https://github.com/dask/dask/pull/2539 ).

**Comment by jakirkham** [comment]
Adding `unravel_index` in PR ( https://github.com/dask/dask/pull/3958 )

**Comment by rabernat** [comment]
👍 to `ravel_multi_index`
