### ISSUE TITLE
Add rollaxis and moveaxis

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2559]
Would be nice to have Dask Array implementations of [`rollaxis`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html ) and [`moveaxis`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.moveaxis.html ). This can probably be done relatively easily by building off of [`transpose`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.transpose ).

**Comment by shoyer** [comment]
These functions already work on dask arrays, since they are defined in terms of the transpose method:
```
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: x = da.ones((10, 11, 12), chunks=7)

In [4]: np.rollaxis(x, 0, -1)
Out[4]: dask.array<transpose, shape=(11, 10, 12), dtype=float64, chunksize=(7, 7, 7)>

In [5]: np.moveaxis(x, 0, -1)
Out[5]: dask.array<transpose, shape=(11, 12, 10), dtype=float64, chunksize=(7, 7, 7)>
```

So we could probably just add appropriate aliases here.

**Comment by jakirkham** [comment]
I see. Should we be relying on an implementation detail of these functions though? Not that I'd expect them to change much (if at all). Just being cautious. FWIW it should be equally trivial to write them using Dask alone.

**Comment by shoyer** [comment]
I'm not 100% sure about rollaxis (you should check the numpy test suite),
but certainly this is absolutely intended for moveaxis -- I wrote that test
case myself. If you prefer, you can also copy there implementations
verbatim -- this is why we use compatible licenses.

**Comment by jakirkham** [comment]
Certainly having test cases for it is good. I'm just wondering do the docs spell this out somewhere? Ideally the API description would say this, but I'm not seeing it. Am thinking about this from the perspective of a C/C++ programmer where the docs really are the gold standard about what the library does.

No strong preference as long as these behaviors are documented and tested this way. Sounds like we know `moveaxis` is tested this way. The doc change should be easy if it is agreeable. `rollaxis` will take some research and at least a doc addition (if not a test addition as well).

**Comment by jakirkham** [comment]
Also this [comment]( https://github.com/numpy/numpy/issues/9473#issuecomment-318371050 ) is interesting.

**Comment by shoyer** [comment]
> I'm just wondering do the docs spell this out somewhere? Ideally the API description would say this, but I'm not seeing it. Am thinking about this from the perspective of a C/C++ programmer where the docs really are the gold standard about what the library does.

Agreed, see https://github.com/numpy/numpy/issues/9476.

**Comment by mrocklin** [comment]
I'm labeling this as good first issue.  It sounds like providing an alias like

```
rollaxis = np.rollaxis
```

providing some tests and adding this to the api docs in `docs/source/array-api.rst` would be enough

**Comment by TAdeJong** [comment]
I could spend some time on this to make a PR in the style @mrocklin proposes, but am somewhat confused by @jakirkham 's work on this. Can I just start a new PR trying the aliassing?
Also, I saw this: https://github.com/numpy/numpy/issues/11658, should I take this into account in any way?
