### ISSUE TITLE
RTD config file in the repo

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2568]
As follow-up from this [comment]( https://github.com/dask/dask/pull/2539#issuecomment-318659736 ), have transposed this here.

Would be nice to have the RTD settings moved into a [`.readthedocs.yml`]( http://docs.readthedocs.io/en/latest/yaml-config.html ) file in the repo. This would make it easier to see what is going on with RTD. Also if there is a doc building issue, it would be easier for people to tweak it in their own RTD project and submit a fix.

**Comment by mrocklin** [comment]
This would be welcome.  If any core contributor wants rights to RTD that doesn't have them and wants to fix this let me know and I'll be happy to add others to the RTD account.
