### ISSUE TITLE
Choose method for Dask Arrays

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2569]
NumPy supports a [`choose`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.choose.html ) method for `ndarray`s. Given there is already a `choose` function implementation for Dask Arrays, it should be pretty easy to add `choose` as a method of Dask Arrays as well.

This can be handy in cases where someone wants to use `choose`, but due to duck typing may not know whether they have a NumPy array or a Dask Array (or maybe something else?). So doesn't want to pick the (wrong) `choose` function. Having a `choose` method easily resolves this issue.

**Comment by mrocklin** [comment]
Sounds good to me

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/dask/dask/pull/2584 ).
