### ISSUE TITLE
Support inplace API like -=, *=, ...

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2588]
When parallelizing existing numpy codes it would be convenient to support operations like `-=`, `+=`, etc..  This won't have any performance benefits, but would be somewhat convenient.  

Typically we do this by doing the normal operation and then overwriting `.dask`, `.name`, etc..

**Comment by shoyer** [comment]
Python implements `+=` via `__add__` even if `__iadd__` isn't defined, so I think this already works:
```
In [1]: import dask.array as da

In [2]: x = da.ones((5, 5), chunks=(2, 2))

In [3]: x += 1

In [4]: x.compute()
Out[4]:
array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])
```
Possibly it could use some testing and/or documentation, though.

**Comment by mrocklin** [comment]
Oh hey, neat

**Comment by jakirkham** [comment]
Yeah, I have already been using this functionality without issues. Though it couldn't hurt to have a few tests to make sure these continue to work should methods be added for these.
