### ISSUE TITLE
Investigate using plasma

### ISSUE THREAD

**Issue by shoyer** [dask/dask#2594]
http://arrow.apache.org/blog/2017/08/08/plasma-in-memory-object-store/

This looks like a great way to share data across processes for dask.array (and dask.dataframe, possibly). `Array.persist()` should possibly use this by default if the scheduler is using multiple processes (either via the multi-processing scheduler or distributed).

**Comment by mrocklin** [comment]
How generic does Plasma go?  If the answer isn't "entirely generic" then this might have to be attached to a collection rather than the scheduler itself.  Something like `array = array.cache_in_plasma()`.  Was this what you were thinking @shoyer ?

**Comment by dhirschfeld** [comment]
It seems like plasma may just be designed for single-node parallelism? In that case a `distributed` `cache_in_plasma` function may have to take care to push to a plasma cache on each node.

**Comment by shoyer** [comment]
> How generic does Plasma go? If the answer isn't "entirely generic" then this might have to be attached to a collection rather than the scheduler itself. Something like array = array.cache_in_plasma(). Was this what you were thinking @shoyer ?

It looks like plasma provides a way to share data in the form of Python `memoryview` objects. It can't work for arbitrary Python objects, for which there is no equivalent to memoryview.

So by necessity it does appear it would be limited to particular collections. It would work well for dask array, but perhaps not for dask dataframe (string columns are stored with `dtype=object`, and custom dtypes would require special work).

**Comment by mrocklin** [comment]
I can imagine a modification of the dask.multiprocessing scheduler that put numpy intermediates into Plasma, or some other posix-shared memory store and sent everything else back as normal.  Joblib may also provide enough infrastructure here for using posix shared memory if we want to rely on something slightly more stable.

**Comment by mrocklin** [comment]
This seems to have gone stale.  Closing.  If folks want to discuss this further then please reopen.

**Comment by Hoeze** [comment]
Maybe this would be a good time point to re-open the discussion here?
Plasma and the Arrow ecosystem has grown a lot in its possibilities, e.g. sparse tensors and data frames:
https://arrow.apache.org/docs/python/plasma.html

**Comment by jakirkham** [comment]
There's already a discussion about using UNIX domain sockets, which would add shared memory ( https://github.com/dask/distributed/issues/3630 ). Seems better to do that before worrying about adding more dependencies.

That said, do you actually have a use case for this? If so, do you mind sharing that in a new issue?

**Comment by Hoeze** [comment]
Thanks for your answer @jakirkham.
I opened an issue at https://github.com/dask/distributed/issues/3630

**Comment by jakirkham** [comment]
xref: https://github.com/dask/dask/issues/6267
