### ISSUE TITLE
Next steps with vnorm

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2606]
In PR ( https://github.com/dask/dask/pull/2597 ), `norm` was added to Dask Array's `linalg` module with functionality equivalent to [NumPy's `norm`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html ). This handles the case that [`vnorm`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.vnorm ) was created to do and some more cases for 2-D arrays. Thus it is possible to rewrite `vnorm` to use `norm`, deprecated it, or something else. Opening this issue to discuss what to do with `vnorm` in light of the addition of `norm`.

cc @mrocklin @jcrist @shoyer

**Comment by jakirkham** [comment]
Should add that `vnorm` currently does the wrong thing with complex vectors if `ord` is a multiple of 2. The lack of `abs` means that we do not get the magnitude for complex values, but instead square them, which is not really the same thing.

-------------------------------------------------------------------------------------------------

https://github.com/dask/dask/blob/72a5f5104b22bd50de37329a99f0f5c623983171/dask/array/reductions.py#L436-L438

**Comment by jakirkham** [comment]
Any thoughts from others on how we should approach this?

**Comment by jcrist** [comment]
I would prefer to deprecate in favor of just using `norm`, as `vnorm` isn't a method provided by numpy, and all `vnorm` code can be rewritten to use `norm` instead. Not a huge priority for me at the moment though.

**Comment by jakirkham** [comment]
Should be resolved with PR ( https://github.com/dask/dask/pull/2773 ).
