### ISSUE TITLE
Add `timestamp96` argument to `read_parquet` methods

### ISSUE THREAD

**Issue by sotte** [dask/dask#2616]
Hey there!

When exporting data from spark into a parquet file, timestamps are represented as int96, see https://github.com/dask/fastparquet/issues/93.

When converting such a parquet file into a pandas dataframe I can specify the columns which are then converted to datetime:
```    
import fastparquet
pfile = fastparquet.ParquetFile('some_file.parquet')
df = pfile.to_pandas(timestamp96=['CREATE_TS'])
```

However, when I'm using dask I can't specify this argument:
```
from dask import dataframe as dd
ddf = dd.read_parquet('some_file.parquet')
```

It would be great if dask also offered the timestamp96 feature.
```
Versions
dask        0.15.1
fastparquet 0.1.0
```

**Comment by martindurant** [comment]
This is easy for me to add this to the fastparquet path.
@wesm, how is this handled in arrow?

**Comment by wesm** [comment]
These are read automatically since the only supported data for INT96 is timestamps

**Comment by martindurant** [comment]
Actually, it looks like I did this too, since https://github.com/dask/fastparquet/commit/3d1450fd3728fc4c95a586a9c48821bfa07c0c58 - @sotte , are you should upgrade to fastparquet 0.1.1, and then you won't need to supply the timestamp96 argument at all.

**Comment by sotte** [comment]
@martindurant the update to fastparquet 0.1.1 did the trick, thanks!
