### ISSUE TITLE
Update pyarrow dependency to 0.6.0

### ISSUE THREAD

**Issue by wesm** [dask/dask#2617]
conda-forge is in the process of being updated, so we can update the dependency in Dask and make sure the tests pass

@jreback @cpcloud we need to go through the Dask test suite and enable more of the tests for `engine='arrow'`, some of them are still disabled I believe. This would be helpful for validating that the metadata is being handled properly on all sides.

**Comment by jcrist** [comment]
Dask now supports arrow 0.8.0, and most tests check a cartesian product of arrow and fastparquet for reading/writing. For specific issues, please open another issue. Closing.

**Comment by wesm** [comment]
thanks @jcrist @cpcloud @TomAugspurger!
