### ISSUE TITLE
Exception Handling in ApplyMap

### ISSUE THREAD

**Issue by samuelroberth** [dask/dask#2623]
Hi,

It seems like it is impossible to catch exceptions using ApplyMap. I am trying to convert elements to floats and return None if it is not possible. I have:

```
def float_apply(x):
    try:
        val = float(x)
    except ValueError:
        val = None

    return val
```

I then try:

`datall = datall.applymap(float_apply)`

However the exception is not caught.

**Comment by jcrist** [comment]
Can you provide a reproducible example? I suspect that the error raised on the call to `float` isn't a `ValueError` in that case (perhaps a `TypeError`?). There's nothing special about `applymap` here, normal python exception handling applies.

**Comment by mrocklin** [comment]
Remember that dask.dataframe is lazy, so your function will not be run until you call `compute`.

**Comment by martindurant** [comment]
https://stackoverflow.com/questions/45866644/exception-handling-in-dask-float-conversion

**Comment by mrocklin** [comment]
Ah, I see, this is repeated.  Closing.
