### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2626]
I would like to consider dropping official support for Python 3.4 after the next release.  It is easy to update from 3.4 to 3.5 and we haven't seen any recent users using 3.4 (which seems generally unpopular).

**Comment by jcrist** [comment]
In general I'm for it. Note that both scikit-image and x-array still support 3.4, and are downstream projects. I'd be fine dropping testing for 3.4 though, as I think it's unlikely that we'll have any major version issues, and I don't think it gets much use (as you said).

**Comment by mrocklin** [comment]
cc @shoyer @stefanv

**Comment by stefanv** [comment]
I would do a query for dask and Python 3.4 a la:

http://www.randalolson.com/2016/09/03/python-2-7-still-reigns-supreme-in-pip-installs/

**Comment by mrocklin** [comment]
https://gist.github.com/mrocklin/341c9b93c46dbc147f755ddf22394ac7

I'm also trying to get access to conda downloads.  I suspect that these are
more 3.x focused

**Comment by mrocklin** [comment]
![screen shot 2017-08-27 at 10 52 49 am](https://user-images.githubusercontent.com/306380/29750903-f891cb2a-8b15-11e7-84cc-e26ce5b1e095.png)

**Comment by jamesstidard** [comment]
I'm currently looking at using Dask in a 3.4 project due to a PySide dependency. Just as a reason for why upgrading might not be a option for some.

**Comment by alvarouc** [comment]
The cluster of computers I am working on are mainly python 3.4.2 (old Debians) but we are implementing docker containers to avoid multiple versions in different machines. So, dropping support 3.4 won't affect us much.

**Comment by jcrist** [comment]
In #2697 I've turned off testing for 3.4 on PRs (still run when pushing/merging to master). For now I think this will ensure 3.4 still works without slowing down our tests too much.

**Comment by jcrist** [comment]
Looks like xarray is planning on dropping 3.4 support in the next release: https://github.com/pydata/xarray/issues/1829.
