### ISSUE TITLE
map_blocks with function that reduces a dimension

### ISSUE THREAD

**Issue by alimanfoo** [dask/dask#263]
I have an input dataset of shape (n_variants, n_samples, ploidy) and a function to map blocks of this array to an output array of shape (n_variants, n_alleles). Using da.map_blocks() with this function raises an exception. Details are in [this notebook](http://nbviewer.ipython.org/gist/alimanfoo/0c45c1d2d8c09c02bd2f/dask.ipynb).

**Comment by mrocklin** [comment]
So after trying to implement this cleanly I'm not sure that correct behavior is always unambiguous.  I don't have a very clean example yet; something like the following might give an idea though.

```python
x = da.ones((4, 1, 1), chunks=(2, 1, 1))

def f(block):
    return block[:, 0, :]

def g(block):
    return block[:, :, 0]

y = x.map_blocks(f, chunks=(2, 1))
z = x.map_blocks(g, chunks=(2, 1))
```

This is a bit contrived (and in this case there is no difference) but hopefully it's clear that we're not sure which dimension we've killed.  I'm not convinced that this is actually an issue, but it has led me to a more sane solution.

Use the full chunks, then call `squeeze`.

```python
ac = dg.map_blocks(f, chunks=(2, 2))  # Before
ac = dg.map_blocks(f, chunks=(2, 2, 1)).squeeze()  # after
```

However, this is also insufficient for this problem.  You need to provide the entire tuple-of-tuples `chunks`.  We're not clever enough to take a single per-block chunksize and ensure that it works over all blocks.  Perhaps we can do this if the blocks are uniformly shaped.

Verbose solution  (requires a bugfix in `squeeze`)

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: genotypes = np.array([[[0, 0], [0, 0], [0, 0]],
   ...:                       [[0, 0], [0, 0], [0, 1]],
   ...:                       [[0, 1], [0, 1], [1, 1]],
   ...:                       [[1, 1], [1, 1], [1, 1]]], dtype='i1')

In [4]: dg = da.from_array(genotypes, chunks=(2, 3, 2))

In [5]: def f(block):
   ...:     return block.sum(axis=2)
   ...: 

In [6]: dg.map_blocks(f, chunks=((2, 2), (3,), (1,)), dtype=dg.dtype).squeeze().compute()
Out[6]: 
array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 2],
       [2, 2, 2]])
```

**Comment by mrocklin** [comment]
Probably we can get the desired behavior in the common case.  I'm not sure how best to handle uneven block sizes though.  This might require passing explicit chunk sizes.

**Comment by shoyer** [comment]
This sort of thing is a bit easier to infer with labeled dimensions like in xray. Hence why I probably need to write my own version of `map_blocks`.

**Comment by alimanfoo** [comment]
Apologies if this is all obvious to you already, just trying to work this through for myself.

Consider a 2D int array x of shape (n, m) where n >> m.

Consider the operation to sum x over the second dimension, i.e., we want to compute x.sum(axis=1). We want to implement this operation block-wise over x.

If x is only chunked along the first dimension (i.e., all chunks are of width m) then implementing this block-wise is simple, as it involves calling block.sum(axis=1) for each input block, then concatenating all output blocks along the first dimension.

If x is chunked along both the first and second dimensions then implementing this block-wise involves computing block.sum(axis=1) for each input block, then reducing all blocks along the second dimension by summing them, then concatenating the results. I.e., there is a step to map blocks, and a step to reduce blocks, which in this case both happen to involve a sum.

Now generalise to consider any operation f that we want to apply block-wise over x, where the operation involves some reduction over the second dimension.

Again, if x is only chunked along the first dimension then implementing this block-wise is simple, as it involves calling f(block) for each input block then concatenating along the first dimension.

However, if x is chunked along both the first and second dimensions then we also need to know a second function g which will reduce the blocks over the second dimension. When f is sum() then g is also sum(), however in general f and g may be different functions.

So it occurs to me that there multiple cases to consider for a general map_blocks() function, each of which may need different information depending on the operation to be applied and the way the input array has been chunked. Maybe map_blocks() should be divided into several functions which deal with these different cases separately, to ease both implementation and usage?

FWIW, the simplest case (which deals with most of my current use cases) is where x is only chunked along the first dimension, and you can apply f to each block then assume the right thing to do is concatenate output blocks along the first dimension, whatever shape the output blocks happen to be. That's what I implemented for [carray_block_map](http://scikit-allel.readthedocs.org/en/v0.14.0/_modules/allel/bcolz.html#carray_block_map) in scikit-allel.

**Comment by mrocklin** [comment]
Labeled dimensions would definitely help in this case.  Here is a cleaner example

>>> x = da.random.random(size=(10, 10, 10, 10, 10), chunks=(5, 10, 10, 10, 5))
>>> x.numblocks
(2, 1, 1, 1, 2)
>>> x.map_blocks(f, chunks=(5, 2, 3, 5))

It's clear from the `numblocks` property that the missing dimension is somewhere in the middle 3 (otherwise this wouldn't be a `map_blocks` operation, but rather a reduction).  If I know which of the three this is then I can manually add a `x[:, :, None, :, :]` after calling your function, then call `da.squeeze` on the whole thing, producing the desired result.  We could accept this information from the user but I suspect that this leads down a rabbit hole.  

I think that it's probably simpler to require that the user defined function doesn't collapse dimensions and instead recommend the use of `squeeze` after the fact.  

It could also be that a richer interface, like `atop`, could solve this problem.  I'll improve user documentation on that and see if it's appropriate.

I've resolved the issue with requiring the full tuple-of-tuple `chunks` in https://github.com/ContinuumIO/dask/pull/274

**Comment by mrocklin** [comment]
@alimanfoo indeed the patterns behind reductions (or other operations) can become quite odd.  Functions like da.sum, da.mean, etc.. depend on an internal function [`reduction`](https://github.com/ContinuumIO/dask/blob/master/dask/array/reductions.py#L14) which does something like what you suggest along any `axis=` direction (including several simultaneously.)

This function is in turn based on a function [`atop`](https://github.com/ContinuumIO/dask/blob/master/dask/array/core.py#L1025) a thin wrapper around [`top`](https://github.com/ContinuumIO/dask/blob/master/dask/array/core.py#L231)) which handles any computation that looks like a combination of tensor inner/outer products like the following

    z_jk = f(a_ij, b_ik, c_i)

This code drives things like `map_blocks`, all of the reductions, as well as operations like `transpose` and `tensordot`.  I haven't done much to expose this functionality to the user but perhaps I should.  It could use a better docstring with examples.  `top` has this but it's a pure dict function and so not very interpretable.

**Comment by mrocklin** [comment]
Atop could probably solve your problem and it's probably a more consistent solution than trying to push the boundaries of map_blocks.

Your operation would look something like the following

```python
y = atop(func, 'y', 'i', x, 'ij')  # apply func along first dimension, collapse second
```

**Comment by mrocklin** [comment]
I've improved the atop docstring here https://github.com/ContinuumIO/dask/pull/275

**Comment by mrocklin** [comment]
Map blocks now includes a drop_axis keyword

http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.map_blocks

Closing.
