### ISSUE TITLE
Make dask collections hashable?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2630]
Should we be able to put dask arrays and dataframes within sets and dictionaries?  This can be convenient at times (I'm trying to put collections in dictionaries in order to specify resource constraints) but breaks with the immutability guarantee.

cc @jcrist @shoyer

**Comment by shoyer** [comment]
We already made dask collections mutable when we defined `__setitem__` on `Array`. So I don't see how we could possibly make them hashable.

One plausible alternative is to make dask *dictionaries* hashable, e.g., by wrapping them in some sort of light-weight [`Frozen` class](https://github.com/pydata/xarray/blob/bcd608101133c0cb84c74d341d22edef71ef4818/xarray/core/utils.py#L279).

**Comment by jcrist** [comment]
I also don't think we should make them hashable. Since constraints are kept by task key, perhaps keep a mapping of keys to constraints instead of collections to constraints?

**Comment by mrocklin** [comment]
OK, closing
