### ISSUE TITLE
String Accessors in Converted DataFrame Columns

### ISSUE THREAD

**Issue by samuelroberth** [dask/dask#2633]
Whenever I try to access strings in a dataframe which are previously converted to strings (ie. datall[['A']] = datall[['A']].applymap(str) and then datall['A']=datall['A'].str[:5]) I get a TypeError: 'StringAccessor' object has no attribute '__getitem__'.

This is reproducible as follows:

```
import pandas as pd
import dask.dataframe as dd
import numpy as np

def float_apply(x):
    try:
        return float(x)
    except ValueError:
        return float('nan')

def string_apply(x):
    try:
        return str(x)
    except ValueError:
        return str('nan')

df = pd.DataFrame(np.random.random_integers(0,6,size=(20, 6)), columns=list('ABCDEF'))

data = dd.from_pandas(df, npartitions = 2)

data=data.applymap(float_apply)

data[['A']] = data[['A']].applymap(string_apply)
data['A'] = data['A'].str[:1]

print data.compute()

```

This will work with pandas dataframes. If .compute() is run prior to this then it works fine but that is probably suboptimal for large datasets.

**Comment by mrocklin** [comment]
Thank you for the great reproducible example @samuelroberth !

Fixed in https://github.com/dask/dask/pull/2634

**Comment by samuelroberth** [comment]
Great, I implemented your fixes in my build. Thanks!
