### ISSUE TITLE
ENH: Allow the groupby by param to handle columns and index levels

### ISSUE THREAD

**Issue by jmmease** [dask/dask#2635]
In version 0.20 Pandas added the ability to group DataFrames by a combination of columns and index levels (See pandas-dev/pandas#14432). This was accomplished by allowing the strings passed as the `by` parameter to the `df.groupby` method to refer to either columns or index levels (where columns take precedence for backward compatibility). I propose supporting this feature in dask DataFrames as well.

In dask we need to consider how this feature will interact with partitioning when the DataFrame has known partitions and the partitioning index is specified as a grouping parameter.

Currently, all `ddf.groupby(...).apply(...)` operations require a full shuffle.  With this change in place, we can avoid shuffling when the DataFrame has known partitions and the partitioning index is included in the grouping parameters.  In this case, we can simply evaluate the `df.groupby(...).apply(...)` operation on the pandas DataFrame in each partition individually and produce a dask object (Series or DataFrame) that maintains the known partitions of the input.

We could do something similar for the known aggregate functions (e.g. `ddf.groupby(...).mean()`). However, I would lean against making changes here as these operations are already efficient regardless of the input DataFrame's partitioning status.

PR implementing this proposal to follow. Thanks for the consideration.

**Comment by mrocklin** [comment]
> Currently, all ddf.groupby(...).apply(...) operations require a full shuffle. With this change in place, we can avoid shuffling when the DataFrame has known partitions and the partitioning index is included in the grouping parameters. In this case, we can simply evaluate the df.groupby(...).apply(...) operation on the pandas DataFrame in each partition individually and produce a dask object (Series or DataFrame) that maintains the known partitions of the input.

We actually *do* avoid shuffling when the user explicitly groups by the *index*.  To the best of my knowledge we're not clever in any other situation.  A fix here would indeed be both very valuable and very welcome (so too would additional contributors like yourself :))

Look forward to seeing you around @jmmease !

**Comment by jmmease** [comment]
Just created PR.  I hadn't noticed the logic when grouping by the index explicitly. I'll take a look and see if that should have any influence on my changes.

Thanks for the warm welcome @mrocklin!

**Comment by TomAugspurger** [comment]
Closed by #2636
