### ISSUE TITLE
Array creation *_like functions

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2637]
Would be nice to have some Dask Array equivalents of common NumPy `*_like` functions. These would be [`empty_like`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html ), [`ones_like`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html ), [`zeros_like`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html ), and [`full_like`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html ). Should be relatively straightforward to create these by reusing existing `empty`, `ones`, `zeros`, and `full` functions.

Could optionally take the `chunks` parameter from the provided array if there is one. If not, could require `chunks` be provided and error out.

**Comment by mrocklin** [comment]
This sounds like a good idea to me

**Comment by jakirkham** [comment]
Ok, adding these in PR ( https://github.com/dask/dask/pull/2640 ).
