### ISSUE TITLE
Can't pickle an object created in a worker process

### ISSUE THREAD

**Issue by PeterMinin** [dask/dask#2643]
I am trying to pickle objects created by dask workers. I am using [dill](https://github.com/uqfoundation/dill) for pickling, as it does the trick in simple cases, but now I've encountered a case where it fails too. This happens with `dask.distributed` and `dask.multiprocessing` alike. Here is the code, with some comments below.
```python
import dask
import dask.multiprocessing
import dill


class A(object):
    def foo(self):
        print('A.foo')


class B(A):
    def foo(self):
        super().foo()


def makeB():
    return B()


b = dask.delayed(makeB)().compute(get=dask.multiprocessing.get)
dill.dumps(b)
b.foo()
```
This produces an error:
`_pickle.PicklingError: Can't pickle <class '__main__.B'>: it's not the same object as __main__.B`
Full stack trace: [gist](https://gist.github.com/PeterMinin/f962da57b771f18d25eded9d30588764).

The error does not happen in either of the following cases:
- the classes are imported from a module;
- class `B` doesn't use `super()`, i.e. if it's defined like this:
```python
class B(A):
    def foo(self):
        A.foo(self)
```
That is, it happens with classes defined in `__main__`, if they reference their base class with `super()`.

I'm not really sure whether this is a dask or dill issue, but I wouldn't be able to explain how such objects are special for dill. An explanation for a report to their tracker would be very welcome too.

Versions:
python - 3.5.2
dask - 0.15.2
dill - 0.2.7.1

**Comment by mrocklin** [comment]
What happens if you don't `import dill`.  Is cloudpickle unable to serialize these objects?

**Comment by PeterMinin** [comment]
I tried `cloudpickle`, and it works. Thank you for the suggestion.
Could you suggest how this case can be described in more abstract terms?
Anyway, this does not seem to be a dask issue, so I will close it.

**Comment by mrocklin** [comment]
When you import dill it modifies the pickle library.  If you don't also
import dill on the receiving side then the pickle library won't know what
to do.  Generally Dask uses cloudpickle and we've found it to be a
sufficient solution in almost all cases.

**Comment by PeterMinin** [comment]
As far as I understand, the modification of `pickle` could be a problem in the dask intercommunications, but that's not the case. The problem still arises if I move the import like this, which shouldn't interfere with the creation of the object:
```python
b = dask.delayed(makeB)().compute(get=dask.multiprocessing.get)
import dill
dill.dumps(b)
```
So I think it's the way dask modifies the class that's not supported by dill.

**Comment by mrocklin** [comment]
Dask doesn't modify the class.  It serializes the class with cloudpickle.
We don't do any modification or think about serialization at all except to
use cloudpickle.

**Comment by PeterMinin** [comment]
I see, this helps reduce the example:
```python
import cloudpickle


class A(object):
    def foo(self):
        print('A.foo')


class B(A):
    def foo(self):
        super().foo()


NewB = cloudpickle.loads(cloudpickle.dumps(B))
b = NewB()

import dill
dill.dumps(b)
b.foo()
```
Thank you again.
