### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory when writing to_csv

### ISSUE THREAD

**Issue by kingblah** [dask/dask#2656]
I'm getting the following error when trying to write using to_csv. It works fine using pandas. 

```
import dask.dataframe as dd

Filename = '\FreshPlanet_SongPop_0317.txt'
Filepath = r'O:\Song Pop\01 Originals\2017'
OutputFilepath = r'O:\Song Pop\01 Originals\2017\FreshPlanet_SongPop_0317_FORMATTED.txt'
df = dd.read_csv(Filepath + Filename, sep='\t', encoding='ansi', keep_default_na=False)

dd.to_csv(df=df, filename=OutputFilepath, index=False, header=False, float_format='%.7f', sep='\t')

```

Error:
```
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/Freshplanet/TestDask.py", line 12, in <module>
    dd.to_csv(df=df, filename=OutputFilepath, index=False, header=False, float_format='%.7f', sep='\t')
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 505, in to_csv
    delayed(values).compute(get=get)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\compatibility.py", line 60, in reraise
    raise exc
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\local.py", line 271, in _execute_task
    return func(*args2)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\bytes\core.py", line 29, in write_block_to_file
    with lazy_file as f:
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\bytes\core.py", line 311, in __enter__
    f = f2 = self.myopen(self.path, mode=mode)
  File "C:\ProgramData\Miniconda3\lib\site-packages\dask\bytes\local.py", line 61, in open
    return open(path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'O:\\Song Pop\\01 Originals\\2017\\FreshPlanet_SongPop_0317_FORMATTED.txt\\6.part'

```

**Comment by mrocklin** [comment]
The `to_csv` method is going to create a directory and write many files to that directory.  I suspect that the filename that you have provided is already a file and so Windows is unable to create a directory of the same name.

**Comment by kingblah** [comment]
Hi there - i've checked the file path and the file doesn't exist at the point of running the script (and nothing is output after it errors) - which is why the error confused me.

Is there a way to just get one .csv created rather than many?

**Comment by mrocklin** [comment]
> Is there a way to just get one .csv created rather than many?

No, but you can concatenate them afterwards

**Comment by TomAugspurger** [comment]
@kingblah you need to provide a globstring (including a `*`) or a list of filenames: http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_csv

**Comment by kingblah** [comment]
@TomAugspurger thanks - that fixed the error! I'll guess I need to formulate a looping function afterwards to concatenate the .csvs afterwards. Apologies, my python isn't great.

**Comment by TomAugspurger** [comment]
We could potentially interpret `foo.csv` as `[foo.csv]`, but I like the current behavior of raising if a globstring is not provided.

We could improve this by:

- checks the output filename for a globstring and raises with a nice error message if one isn't found
- Update the documentation to recommend using a length-one list if you want a single file.

@kingblah would you be able to submit a pull request doing that?

**Comment by kingblah** [comment]
@TomAugspurger Using a length one list worked great (`blocksize=None` on the `read_csv`). Will dask still enforce a globstring (-*.csv)? 

Sure, what do you need in the pull request?

**Comment by TomAugspurger** [comment]
> Using a length one block worked great (blocksize=None on the read_csv). Will dask still enforce a globstring (-*.csv)?

Yes, I think so.

> Sure, what do you need in the pull request?

In https://github.com/dask/dask/blob/b1ff82604af5360b7972cd613e57d47688824316/dask/dataframe/io/csv.py#L388 I would add a check like

```python
if isinstance(filename, six.string_types):
    if '*' not in filename:
        raise ValueError(nice message)
```

> Update the documentation to recommend using a length-one list if you want a single file.

It looks like I was wrong about this. This only contained the the first partition. @martindurant do you think we should check that `len(filename)` equals `df.npartitions` when filenames is a list?

**Comment by mrocklin** [comment]
A list of length one is not generally a good solution to this problem.
There is no easy way to have many threads/processes write in parallel to a
single linear file of unknown length.

**Comment by kingblah** [comment]
Ah, OK. Would it therefore be more efficient to write to multiple files, and then concatenate them afterwards (outside of `dask`?), as you suggested?

**Comment by mrocklin** [comment]
Yes

**Comment by mrocklin** [comment]
The check that Tom points out sounds like a good one to me to avoid wrong
results.  @martindurant would probably have a more informed perspective
here though.

**Comment by martindurant** [comment]
Yes, I agree with @TomAugspurger on both things: we should accept only lists or strings, the former to have the right number of partitions, the latter to be an expandable pattern - otherwise error early.

**Comment by kingblah** [comment]
@mrocklin I've just done some testing and, at least with my file, writing to 7 csv's (that's how many partitions dask gave the csv when read) and then subsequently concatenating each of the 7 output csv's into one single csv takes significantly longer (presumably due to two large writing operations) than just setting `blocksize = None` and dask writing out one single csv all in one operation.  I'm probably missing something here!

**Comment by samuelroberth** [comment]
You can run .compute() and write to CSV using Pandas if your aggregated data will fit into memory. Might be easier depending on your application.

**Comment by vascoosx** [comment]
@TomAugspurger I provided a glob including a `*` but still had the same problem

**Comment by TomAugspurger** [comment]
> By the way I am running in distributed mode

Do all your workers have access to the same filesystem? If you're running on AWS EC2, e.g. they won't, so you would need to use something like S3.

**Comment by vascoosx** [comment]
Thanks, I was beginning to suspect that was the issue. I was trying to store locally.

**Comment by javabrett** [comment]
>> Is there a way to just get one .csv created rather than many?
> No, but you can concatenate them afterwards

I think you can always re-partition to `npartitions=1`, at the cost of doing that, and the potential consequences on performance of the export and re-import.  But you'll get a single CSV file.

**Comment by javabrett** [comment]
I visited this issue when triaging some bugs.  One thing I observed is that Dask wasn't creating any parent-paths for me, so errored-out when attempting to `to_csv()` or `to_json()` into a non-existent path.  This wasn't completely unexpected, but might cause some confusion when the last directory-path-segment is viewed or treated like a pseudo-filename, because it is actually a container for the exported file-partitions.

**Comment by martindurant** [comment]
I agree that we could have these call `mkdirs` on the filesystem in each case, and this could even like in the `open_files` machinery, rather than being specific to the CSV or JSON writers. `mkdirs` is indeed one of the required methods on a dask file-system, even if it has no effect on object stores like s3. However, there are always errors of this sort that can happen, particularly lack of permissions, which will not surface until the lazy operations are being executed later.

**Comment by kunkub** [comment]
I changed file name from multiData(copy).csv to multiData.csv. It works

**Comment by flutterq** [comment]
All Possible working solution added [[Solved] FileNotFoundError: [Errno 2] No such file or directory](https://flutterq.com/filenotfounderror-errno-2-no-such-file-or-directory/)

**Comment by linehammer** [comment]
If the user does not pass the full path to the file (on Unix type systems this means a path that starts with a slash), the [python file](http://net-informations.com/python/file/open.htm) path is interpreted relatively to the current working directory. The current working directory usually is the directory in which you started the program. In order to make this work, the directory containing the python executable must be in the PATH, a so-called environment variable that contains directories that are automatically used for searching executables when you enter a command. 

In any case, if your Python script file and your data input file are not in the same directory, you always have to specify either a relative path between them or you have to use an absolute path for one of them.
