### ISSUE TITLE
Add unquote

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2663]
Would be nice to have an `unquote` operation to reverse `quote`. This [comment]( https://github.com/dask/dask/issues/741#issuecomment-142347806 ) may be helpful for implementing this.

**Comment by jakirkham** [comment]
Then again this may trivially fallout from [`__call__`]( https://github.com/dask/dask/blob/adf37b934e9a59d4163a1e109a18f278fe3b4bfa/dask/core.py#L441-L442 ) provided by `literal`.

**Comment by jcrist** [comment]
Why do you need this?

> This comment may be helpful for implementing this.

That's for a separate operation, making tasks look like function calls/literals. `dask.core.quote` is for taking an object and ensuring that it doesn't get treated like a task.

**Comment by jakirkham** [comment]
This is pretty speculative, but was thinking of doing some metaprogramming in Dask. So quoting operations, detecting and replacing certain patterns, and then unquoting to get an actual Dask for computation.

**Comment by GenevieveBuckley** [comment]
Is this still needed?

**Comment by jakirkham** [comment]
There's not been much activity here in 4yrs. Am happy to close. Can always revisit if it becomes important. Though my guess is there are different ways people want to manipulate graphs today where this functionality is less relevant.
