### ISSUE TITLE
Foldby not combining in parallel.

### ISSUE THREAD

**Issue by daniel-severo** [dask/dask#2668]
Hey guys.

Been using dask for ad-hoc big data analysis creating custom reports while processing a few terabytes of json data.

I've noticed that the `foldby` operation has a huge sequential task that is computed after it has applied the `binop` to each partition. In theory, if a `combine` function is supplied couldn't this be done in parallel by taking the output of each partition and combining them in a pairwise fashion?

Does this make sense or did I miss something?

Sample code:

```python
(
    bag
    .filter(predicate)
    .map(js.loads)
    .map(transform)
    .foldby(key, binop, initial, combine, initial)
    .compute()
)
```
![image](https://user-images.githubusercontent.com/17755465/30222040-15de90de-949c-11e7-9cc3-0a4eed0568a3.png)

Cheers!

**Comment by mrocklin** [comment]
It looks that while many reduction operations in dask support tree
reductions, this one does not, I suspect because it requires cleverness on
the part of the user to combine intermediate results.

One quick solution would be to try switching over to dask.dataframe at an
appropriate part in your computational pipeline using the Bag.to_dataframe
method.  This would only be appropriate if, at that time, your JSON data is
nicely tabular.

In the mean time it probably makes sense to extend foldby to support tree
reductions.

**Comment by daniel-severo** [comment]
After the `.map(transform)` operation the data is perfectly tabular (all bag elements are `dict`s).

I'll try converting it to a dataframe and using `groupby`. I was reluctant to do so due to performance concerns.

dask already has the option of specifying the `combine` function which is the operation that combines the output of the partitions. I think tree reductions would be a huge improvement in speed :dancer:

**Comment by mrocklin** [comment]
Is this something that you would be willing to help contribute?  The
dask.bag code is a good entry point to the rest of the project.

**Comment by daniel-severo** [comment]
Funny enough I was looking at the code and it does look fairly simple. I'll
take a hack at it once I return to the office (sometime next week).

I'll keep you updated.

**Comment by daniel-severo** [comment]
How do you think the interface should be done? Should I put tree reductions as the default for `foldby`, create a new method or an optional flag?

**Comment by mrocklin** [comment]
I would do this within one function with a flag if necessary.  I'm not sure
what the default of that flag should be.

Does the user need to provide any additional combination function when
doing a tree-reduction foldby?  If so then this might be a good signal.

**Comment by daniel-severo** [comment]
The user doesn't need to specify any more function. A `binop` and `combine` suffice.

All that needs to happen is that both arguments and the output of the `combine` function to be of the same schema. At first I was thinking of a try, except kind of implementation, where the method itself would decide if the tree reduction should be executed or not. But I think this might be unfeasible and not very pythonic (way to implicit).

I'll make a boolean flag `tree_reduction` for now.

**Comment by mrocklin** [comment]
You should consider the `split_every=` keyword used by other functions like `fold` and `reduction`

**Comment by mrocklin** [comment]
> The user doesn't need to specify any more functions. A binop and combine suffice. As long as the inputs and output of the combine method have the same schema it should work fine.

Is this ever not the case?

**Comment by mrocklin** [comment]
In [gitter chat](https://gitter.im/dask/dask?at=59b72a12319100804e22fbb3) @daniel-severo said the following

> Hey @mrocklin, any reason why dictitems was applied on the top expression and not the bottom one here: https://github.com/daniel-severo/dask/blob/master/dask/bag/core.py#L983-L989

I'm not sure I understand.  It looks like both lines include the call to `dictitems`.

(also, I prefer to keep conversation on github if possible so that others can participate and search in the future)

**Comment by daniel-severo** [comment]
> Is this ever not the case?

I guess not (for `npartitions` > 2). But if this is the general case, wouldn't make sense for the tree reduction to be the default behavior?

**Comment by daniel-severo** [comment]
> I'm not sure I understand. It looks like both lines include the call to dictitems.

Sorry, I was actually talking about the second application of `dictitems` in the top expression (the one that comes after the `map` and before the `list(dsk.keys())`.

> (also, I prefer to keep conversation on github if possible so that others can participate and search in the future)

my bad, I've been using open-source software for about a little over a year and this is my first time contributing. Still a n00b.

**Comment by mrocklin** [comment]
I'm not sure why dictitems is not applied in the second case.  Do any of the tests fail with its addition?  That might be a useful way to see an unintended change.

> My bad, I've been using open-source software for about a little over a year and this is my first time contributing. Still a n00b.

Different groups operate differently, but most dask devs congregate on github rather than gitter.

**Comment by daniel-severo** [comment]
> I'm not sure why dictitems is not applied in the second case. Do any of the tests fail with its addition? That might be a useful way to see an unintended change.

Not sure. I'll check that out today.

--

I finished a rudimentary (but working) version yesterday. Although I'm not quite happy with [the way I built the tree reduction](https://github.com/daniel-severo/dask/blob/master/dask/bag/core.py#L984-L998).

I start off with a queue that has the elements of `dsk.keys()`, which are the keys of the `binop` reduction (`"foldby-a-{token}"`).  I then group these keys in a pairwise fashion (so I can apply the `combine`) and insert the corresponding new key (`"foldby-b-{token}"`) at the end of the queue.

I index the partitions of the second part by first calculating how many total partitions I would need and I then count backwards. To calculate the number of partitions

Opinions?

**Comment by mrocklin** [comment]
There are a few other tree reduction implementations around in the codebase.  You might want to search for `split_every` in the codebase.

**Comment by daniel-severo** [comment]
Great. [I got it down](https://github.com/daniel-severo/dask/blob/master/dask/bag/core.py#L994-L1002) :)

Just need to replicate it for the second case.

So I don't see any unit tests for this function. Can I go ahead and write one?

**Comment by mrocklin** [comment]
> So I don't see any unit tests for this function. Can I go ahead and write
one?

Please do.  That would be great :)

**Comment by daniel-severo** [comment]
https://github.com/dask/dask/pull/2710

:)

**Comment by TomAugspurger** [comment]
Closed by https://github.com/dask/dask/pull/2710

Thanks @daniel-severo
