### ISSUE TITLE
Nested namespace accessor

### ISSUE THREAD

**Issue by chdoig** [dask/dask#267]
I'm trying to remove stopwords from a list of strings with dask.bag.

This returns a list of the stopwords for each line:

``` python
b.pluck('abstract').map(lambda line: line.split()).map(lambda l: filter(STOPWORDS.__contains__, l)).take(1)
```

What's the best way to do the opposite (return if the word is not contained) with dask.bag?

I think I'm looking for something like:
https://docs.python.org/2/library/itertools.html#itertools.ifilterfalse
http://toolz.readthedocs.org/en/latest/api.html#toolz.itertoolz.remove

If an equivalent function is not implemented, what's the recommended alternative?

Thanks!

**Comment by chdoig** [comment]
I solved it by using itertoolz the following way:

```python
from toolz.itertoolz import remove
b.pluck('abstract').map(lambda line: line.split()).map(lambda l: list(remove(STOPWORDS.__contains__, l))).take(1)
```

**Comment by eriknw** [comment]
Great.  By the way, you can replace `map(lambda line: line.split())` with `map(str.split)`.

**Comment by chdoig** [comment]
Thanks @eriknw . I actually got this error when replacing (using ``0.5.0``) :

```
TypeError:  Exception in remote process

descriptor 'split' requires a 'str' object but received a 'unicode'

Traceback:
  File "/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.py", line 258, in execute_task
    result = _execute_task(task, data)
  File "/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.py", line 241, in _execute_task
    return func(*args2)
```

but I belive Matt fixed it here: https://github.com/mrocklin/dask/commit/0707698ffd26cc8b6656626f538a295d4fe0f21e

**Comment by eriknw** [comment]
Good point, your way is more compatible.  Another way to be compatible is to `import string ; ... ; map(string.split)`, but your way is good (and explicit) too.

**Comment by mrocklin** [comment]
There is a `str` namespace in bag so one can also do

    b.str.split()

This works both on unicode and on strings.

I'll add remove in the morning (some 8 hours from now)

**Comment by eriknw** [comment]
Yeah, @chdoig pointed to the commit that added str/unicode compatibility to the `b.str` accessor.  Her example above would be even nicer if there were also a list or generic sequence accessor, such as `b.pluck('abstract').str.split().list.remove(STOPWORDS.__contains__).take(1)`.

**Comment by mrocklin** [comment]
I'm fairly comfortable dumping sequence functions into the dask.bag.Bag namespace.  Several other functions are already there, notably `filter`.

**Comment by eriknw** [comment]
To clarify, I was thinking about an accessor, `Bag.list`, that behaves like `Bag.str`.  For example,
```python
In [1]: import dask.bag as db

In [2]: iseven = lambda x: x % 2 == 0

In [3]: seq = [0, 1, 2, 3]

In [4]: list(db.from_sequence(seq).filter(iseven))
Out[4]: [0, 2]

In [5]: seq_of_seqs = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [6]: list(db.from_sequence(seq_of_seqs).list.filter(iseven))
Out[6]: [[0, 2], [4], [6, 8]]
```

**Comment by mrocklin** [comment]
Oh!  Interesting.  One might presumably want to nest these.  That might be fun.

Looking again at the original error report I see that I misunderstood the problem.  Yes, this looks like a good idea.

**Comment by mrocklin** [comment]
Also short term, your question was how do we do this but with remove

    b.pluck('abstract').map(lambda line: line.split()).map(lambda l: filter(STOPWORDS.__contains__, l)).take(1)

A trivial way would be to use remove

    b.pluck('abstract').map(lambda line: line.split()).map(lambda l: remove(STOPWORDS.__contains__, l)).take(1)

Alternatively if you don't care about the list structure at this point then you could also concatenate your lists into one large bag

    b.pluck('abstract').str.split().concat().remove(STOPWORDS.__contains__).take(1)

**Comment by chdoig** [comment]
Matt,

Your suggestion:

```python
b.pluck('abstract').map(lambda line: line.split()).map(lambda l: remove(STOPWORDS.__contains__, l)).take(1)
```

Gets me this error:

```python
---------------------------------------------------------------------------
RemoteError                               Traceback (most recent call last)
<ipython-input-12-2025568b18c2> in <module>()
----> 1 b.pluck('abstract').str.split().map(lambda l: remove(STOPWORDS.__contains__, l)).take(1)

/Users/cdoig/dask/dask/bag/core.pyc in take(self, k, compute)
    565         b = Bag(merge(self.dask, dsk), name, 1)
    566         if compute:
--> 567             return tuple(b.compute())
    568         else:
    569             return b

/Users/cdoig/dask/dask/bag/core.pyc in compute(self, **kwargs)
    574     def compute(self, **kwargs):
    575         """ Force evaluation of bag """
--> 576         results = get(self.dask, self._keys(), **kwargs)
    577         if isinstance(results[0], Iterable):
    578             results = toolz.concat(results)

/Users/cdoig/dask/dask/bag/core.pyc in get(dsk, keys, get, **kwargs)
     86     dsk2 = optimize(dsk, keys)
     87 
---> 88     return get(dsk2, keys, **kwargs)
     89 _get = get
     90 

/Users/cdoig/dask/dask/multiprocessing.pyc in get(dsk, keys, optimizations, num_workers, func_loads, func_dumps)
     49         # Run
     50         result = get_async(apply_async, len(pool._pool), dsk2, keys,
---> 51                            queue=queue)
     52     finally:
     53         if cleanup:

/Users/cdoig/dask/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, debug_counts, queue, raise_on_exception, **kwargs)
    448         if isinstance(res, Exception):
    449             raise type(res)(" Exception in remote process\n\n"
--> 450                 + str(res) + "\n\nTraceback:\n" + tb)
    451         state['cache'][key] = res
    452         finish_task(dsk, key, state, results)

RemoteError: 
---------------------------------------------------------------------------
 Exception in remote process


---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cdoig/anaconda/envs/dask-text/lib/python2.7/multiprocessing/managers.py", line 240, in serve_client
    request = recv()
TypeError: ifilterfalse expected 2 arguments, got 0
---------------------------------------------------------------------------

Traceback:
  File "/Users/cdoig/dask/dask/async.py", line 270, in execute_task
    queue.put(result)
  File "<string>", line 2, in put
  File "/Users/cdoig/anaconda/envs/dask-text/lib/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
---------------------------------------------------------------------------
```

It works if I add list() to remove, as the solution my second comment:

```python
b.pluck('abstract').map(lambda line: line.split()).map(lambda l: list(remove(STOPWORDS.__contains__, l))).take(1)
```

**Comment by mrocklin** [comment]
@eriknw any further interest in this?

I'm now mildly in favor of just recommending that people continue to use lambdas.  This reduces maintenance burden and API on our end.

**Comment by eriknw** [comment]
I don't plan to get to this in the near term.  Feel free to close the issue.  It is neat, though, and offers modest (but not amazing) performance boosts, so I may revisit or post a WIP branch if others are interested.

**Comment by jcrist** [comment]
Closing for now as stale. Feel free to reopen if needed.
