### ISSUE TITLE
Memory issues causing sporadic CI failures

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2671]
This seems to happen with some regularity, but does not always happen and restarting sometimes fixes it. However there are a few tests that seem to fail due to memory issues some times on CI. A link to a log showing some of these failures is included below.

ref: https://travis-ci.org/dask/dask/jobs/273380620

**Comment by mrocklin** [comment]
Interesting.  I ran into a very similar issue with dask.distributed a month ago.  We were leaking memory in tests for a few reasons.  To resolve this I added checks before and after every test to identify which tests were leaking the most.  See the 50 or so lines following this entry: https://github.com/dask/distributed/pull/1317/files#diff-5e2c0e4a5c31298584de13564b98fe49R491

Unfortunately dask/dask doesn't have any obvious context managers or test decorators into which we can insert checks like this.  Is there a plugin for py.test that we could use to measure memory use after every test?
