### ISSUE TITLE
npy_stack not working

### ISSUE THREAD

**Issue by mayl** [dask/dask#2672]
When I tried to use the dask.array.to_npy_stack() function, it failed on os.path.mkdir.  This is because mkdir lives in the os namespace, not os.path.  Changing the call to os.mkdir allowed to_npy_stack to work as expected.  

Not at my main machine, but can provide an example later if the above explanation is not enough.

**Comment by mrocklin** [comment]
Thanks for the bug report @mayl.  Can I interest you in submitting a small PR to fix?

**Comment by mayl** [comment]
Sure, happy to.  I'm actually currently traveling and will be away from my main machine, so expect that it may take a week or two before I'm able to get to it.

**Comment by mrocklin** [comment]
We appreciate any help we can get, even delayed help :)

**Comment by mayl** [comment]
I just submitted #2709 with the change.  I ran the tests and flake which passed (unsurprisingly).  Since there is no API change, I assumed no documentation would really be necessary. My first time going through this process, so please let me know if the PR doesn't fit the project standards in any way.

**Comment by jakirkham** [comment]
Given PR ( https://github.com/dask/dask/pull/2709 ) has been accepted, can this be closed or is there more work to be done?

**Comment by jakirkham** [comment]
Going to assume this is resolved since a patch has already landed and shown up in release. If this is not fixed, feel free to let us know.
