### ISSUE TITLE
Array assert_eq doesn't check for equality on scalars

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2680]
Not sure if this is intentional, but I thought I would check:

```python
In [41]: import dask.array as da; import dask.array.utils

In [42]: import numpy as np

In [43]: a = da.from_array(np.array([0]), chunks=1)

In [44]: x = np.array([1])

In [45]: da.utils.assert_eq(a[0], x[0])
# None
```

**Comment by TomAugspurger** [comment]
This check seems fragile: https://github.com/dask/dask/blob/a1a75a766243f1f84ac1df502de3faf8ce4ebc81/dask/array/utils.py#L99-L103

I think that will short-circuit when `a` is empty.

```python
(Pdb++) _not_empty(a) and _not_empty(True)  # the second condition isn't checked
()
(Pdb++) _not_empty(True)  # it is hit now, raises an error
*** AttributeError: 'bool' object has no attribute 'shape'
```

**Comment by TomAugspurger** [comment]
Huh

```python
In [40]: np.isscalar(np.array(1))
Out[40]: False
```

I'm not quite sure how to distinguish between empty arrays and a scalar.

**Comment by bmerry** [comment]
> I think that will short-circuit when a is empty.

I imagine it should probably have been `or` rather than `and`.

**Comment by shoyer** [comment]
> I'm not quite sure how to distinguish between empty arrays and a scalar.

`getattr(x, 'size', 1)` will be 1 for scalars and 0 for empty arrays.

`np.isscalar()` has a pretty strange design. It checks for instances of `np.generic` types *or* their built-in Python equivalents (`int`, `float`, `str`, etc).
