### ISSUE TITLE
Add ptp

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2687]
Would be nice to have [`ptp`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.ptp.html ) for Dask Arrays. Should be relatively straightforward as it can be composed from the difference between the `min` and `max` of the array.

**Comment by mrocklin** [comment]
Seems reasonable

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/dask/dask/pull/2691 ).
