### ISSUE TITLE
Short-cut for rechunking an array into a single chunk along an axis?

### ISSUE THREAD

**Issue by shoyer** [dask/dask#2689]
Currently this requires writing something like `x.rechunk((x.shape[0], ...))` or `x.rechunk((1000000,))`, which is a little clunky.

Possible alternatives:
1. Use `-1` as an alias for "full dimension size", e.g., `x.rechunk((-1,))`.
2. Add a keyword argument, e.g., `rechunk(divisions=(1,))` for rechunking into equally sized divisions instead of chunks.

**Comment by mrocklin** [comment]
Using an alias makes sense.  Doesn't reshape have similar aliases already?
