### ISSUE TITLE
"ValueError: Not all divisions are known, can't align partitions" when performing math on dataframe column

### ISSUE THREAD

**Issue by konrad-roze** [dask/dask#2690]
I am trying to perform following on a dask dataframe:
```
newcolumn = np.log(df[column_name])
return df.assign(newcolumn_name=newcolumn)
```
I expected it to work according to example given in [documentation](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.assign). However I'm getting following error:

```
File ".../dask/dataframe/core.py", line 2321, in assign
    return elemwise(methods.assign, self, *pairs, meta=df2)
  File ".../dask/dataframe/core.py", line 2796, in elemwise
    args = _maybe_align_partitions(args)
  File ".../dask/dataframe/multi.py", line 147, in _maybe_align_partitions
    dfs2 = iter(align_partitions(*dfs)[0])
  File ".../dask/dataframe/multi.py", line 103, in align_partitions
    raise ValueError("Not all divisions are known, can't align "
ValueError: Not all divisions are known, can't align partitions. Please use `set_index` to set the index.
```
I'm using dask 0.15.2. 

I do have a workaround for this by using `df.assign(newcolumn_name=lambda...)` but the lambda function in this case needs to operate on whole record, not a specific set of columns

PS. In fact I'd like to do `df[newcolumn_name] = np.log(df[column_name])` directly - is it supposed to work?

**Comment by jcrist** [comment]
You want to use `da.log` here instead of `np.log`. More generally, you want to replace calls to numpy and pandas functions with their `dask.array` and `dask.dataframe` counterparts:

```python
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: import dask.array as da

In [4]: import dask.dataframe as dd

In [5]: df = pd.DataFrame(np.random.normal(size=(1000, 4)), columns=['a', 'b', 'c', 'd'])  # Create a pandas df

In [6]: ddf = dd.from_pandas(df, npartitions=4, sort=False)  # Create a dask.dataframe with unknown divisions

In [7]: ddf.known_divisions
Out[7]: False

In [8]: ddf2 = ddf.assign(e=da.log(ddf.d))  # Using assign and `da.log`

In [9]: ddf2.head(2)
Out[9]:
          a         b         c         d         e
0  0.326580  2.922833 -0.470117 -1.520436       NaN
1 -2.189221  0.284689  0.736333  1.507069  0.410167

In [10]: ddf['e'] = da.log(ddf.d)  # Using setitem notation

In [11]: ddf.head(2)
Out[11]:
          a         b         c         d         e
0  0.326580  2.922833 -0.470117 -1.520436       NaN
1 -2.189221  0.284689  0.736333  1.507069  0.410167
```

> PS. In fact I'd like to do df[newcolumn_name] = np.log(df[column_name]) directly - is it supposed to work?

Yes, demonstrated in cell 10 above.

**Comment by asifali22** [comment]
@jcrist 
I'm facing the same issue.
Trying the above snippets, `In [8]: ddf2 = ddf.assign(e=da.log(ddf.d))`  with a numpy array i.e. `y_pred = np.random.permutation(1000)`

```
...
>>> y_pred = np.random.permutation(1000)
>>> ddf2 = ddf.assign(e=y_pred)
...
```

Gives following error:
```
  File "<stdin>", line 1, in <module>
  File "/Users/asifali/workspace/pythonProjects/ML-engine-DataX/pre-processing/diya_libs/venv/lib/python3.6/site-packages/dask/dataframe/core.py", line 2683, in assign
    "{0}".format(type(v).__name__))
TypeError: Column assignment doesn't support type ndarray
```
Trying with series:
```
ddf2 = ddf.assign(e=dd.from_array(y_pred))
```
Error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-20-e26ffd6ae1d1> in <module>()
----> 1 ddf2 = ddf.assign(e=dd.from_array(y_pred))

/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py in assign(self, **kwargs)
   2502         # Figure out columns of the output
   2503         df2 = self._meta.assign(**_extract_meta(kwargs))
-> 2504         return elemwise(methods.assign, self, *pairs, meta=df2)
   2505 
   2506     @derived_from(pd.DataFrame)

/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   3048 
   3049     from .multi import _maybe_align_partitions
-> 3050     args = _maybe_align_partitions(args)
   3051     dasks = [arg for arg in args if isinstance(arg, (_Frame, Scalar, Array))]
   3052     dfs = [df for df in dasks if isinstance(df, _Frame)]

/anaconda3/lib/python3.6/site-packages/dask/dataframe/multi.py in _maybe_align_partitions(args)
    145     divisions = dfs[0].divisions
    146     if not all(df.divisions == divisions for df in dfs):
--> 147         dfs2 = iter(align_partitions(*dfs)[0])
    148         return [a if not isinstance(a, _Frame) else next(dfs2) for a in args]
    149     return args

/anaconda3/lib/python3.6/site-packages/dask/dataframe/multi.py in align_partitions(*dfs)
    101         raise ValueError("dfs contains no DataFrame and Series")
    102     if not all(df.known_divisions for df in dfs1):
--> 103         raise ValueError("Not all divisions are known, can't align "
    104                          "partitions. Please use `set_index` "
    105                          "to set the index.")

ValueError: Not all divisions are known, can't align partitions. Please use `set_index` to set the index.
```

**How can I assign values of a new column from np.array?**

**Comment by jcrist** [comment]
You can't (or at least you can't without some work), and you probably shouldn't.

`dask.dataframe` partitions data along the index. Information about the partition boundaries are kept, but not how many elements are in each partition. This is useful for many operations, but makes it hard to assign a column from a non-indexed type, as we don't know where to split your array `y_pred`. You *can* do the assignment if you determine the indices in both `df` and `y_pred` (following the error message advice to use `set_index`), but this comes with some performance cost.

 I recommend trying to rethink your problem to avoid this entirely. If you can't, you can call `set_index`, but it has a cost:

```
In [51]: df = dd.from_pandas(pd.DataFrame({'a': range(100)}), npartitions=6, sort=False)

In [52]: df.known_divisions
Out[52]: False

In [53]: df2 = df.reset_index().set_index('index')  # Determine divisions. Here we re-index the existing indices

In [54]: df2.known_divisions
Out[54]: True

In [55]: y_pred = np.arange(100)

In [56]: df3 = df2.assign(e=dd.from_array(y_pred))

In [57]: df3.head()
Out[57]:
       a  e
index
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
```

**Comment by asifali22** [comment]
@jcrist
@mrocklin 
@TomAugspurger 
Thanks for the workaround, I really appreciate that. Perhaps, my problem is simple.
I'm trying to write down a `pipeline` with some transformers and a predictor but might have to predict on the major dataset, causing a memory problem. Workaround for that will be [ParallelPostFit](https://dask-ml.readthedocs.io/en/latest/meta-estimators.html#parallel-prediction-and-transformation). But then since It's a pipeline:
```
...
pipe = Pipeline([
    ('t1', transformer1()),
    ('t2', transformer2()),
    ('clf', ParallelPostFit(estimator=estimator())),
])
```
When I'm passing out the grid parameters to the pipeline it says, the parameters passed for estimator are not valid and which makes sense, since the pipeline is expecting the parameters of `ParallelPostFit`, not the `estimator`.

> Is there a way to pass parameters to the estimator enclosed in `ParallelPostFit` inside a pipeline?

Since, as of now I can't do anything else rather just predict which returns a `np.array` causing the above issue.

**Comment by TomAugspurger** [comment]
Prefex the parameters with `estimator__` like in the last example at http://ml.dask.org/hyper-parameter-search.html#incremental-hyperparameter-optimization

**Comment by asifali22** [comment]
Do you think, it's worth specifying this in the main documentation page of [ParallelPostFit](https://dask-ml.readthedocs.io/en/latest/meta-estimators.html#parallel-prediction-and-transformation) or in the example link within the main documentation page [here](https://dask-ml-benchmarks.readthedocs.io/en/latest/auto_examples/plot_parallel_post_fit_scaling.html) ?

**Comment by TomAugspurger** [comment]
Sure, if you want to make a PR that'd be a good update to the docs. This is
standard for scikit-learn though:
http://scikit-learn.org/stable/modules/compose.html#usage

**Comment by BParesh89** [comment]
I am also facing the similar error while assigning the label encoded values to a column in dask dataframe. I have posted the same with code and error on [stackoverflow](https://stackoverflow.com/questions/53318032/error-while-assigning-label-encoded-values-to-column-in-dask-dataframe).  How can I resolve this issue ?

**Comment by PGryllos** [comment]
@TomAugspurger I understand how having to invoke reset index should make you think that you are doing something unconventional, but how is someone supposed to created a random permutation of a dataframe without going through the process that @asifali22 was describing above?

**Comment by PGryllos** [comment]
the close I found to an answer is this one https://stackoverflow.com/questions/46842155/shuffling-data-in-dask/46848375; (adding a column with random data to your dataframe) - the best way I can think to do that is add a column with guuids or something similar and use that for sorting; 1) is this always guaranteed to provide a good shuffle? and second procuding uuids for every row of your dataframe is also costly :/
