### ISSUE TITLE
Document and expose assert_eq in public API

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2694]
Would be great to have `assert_eq` documented and exposed as part of the public API. Should help answer questions about what it does internally as well as providing a preferred way to test results from Dask.

**Comment by sinhrks** [comment]
Maybe we can define common `assert_eq` which dispatches to array/dataframe `assert_eq` each.

**Comment by jakirkham** [comment]
That's not a bad idea. I realize I left this issue kind of vague as there are lots of `assert_eq` implementations and wasn't sure how we might want to deal with this variety. Having a dispatching function makes a lot of sense.

**Comment by jakirkham** [comment]
Another way to address this for Dask Array at least would be to create an equivalent `dask.array.testing` to [`numpy.testing`]( https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.testing.html ) and add those function here via refactoring the existing code.

**Comment by pitrou** [comment]
I'd be wary of exposing such a function in the public API. We want to be able to change its behaviour over time without having people complain that we broke their code.

We can still document it, though, as long as it's made clear that it's for internal use. Also +1 for a dedicated place for testing-related utilities.

**Comment by TomAugspurger** [comment]
FWIW, xarray may make use of `dask.array.utils.assert_eq`: https://github.com/pydata/xarray/issues/1759#issuecomment-349765925

**Comment by jakirkham** [comment]
Sure. Have used it myself as well (hence the issue 😉). Though it certainly isn't documented as part of the public API FWICT. So in theory we can't really expect it to always work or stay the same. In practice, we might have to be more careful about changing it given there is external use (guessing this is your point).

That said, maybe it will be better to add some [new assertion functions that mimic NumPy's own]( https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.testing.html#asserts ) and state they are part of the public API to begin with. Then external libraries can switch to them and we can even consider doing the same internally.

**Comment by mrocklin** [comment]
FWIW I find the numpy assert functions to be somewhat cumbersome.  I think that for testing I tend to prefer the all-in-one magical function approach.  

I also think that because this is primarily used in testing that we have some more flexibility about changing assert_eq without much notice (though downstream libraries may differ).  We also haven't changed it much recenty in ways that downstream libraries are likely to notice.

**Comment by jakirkham** [comment]
Not attached to the NumPy approach. Just trying to sell the idea of making these functions public. ;)

FWIW I already use `assert_eq` downstream. Wonder if there are others. :)

The main thing is the `assert_eq` functions actually do a lot of checks that are really smart that external users might not thing to check (e.g. `nan` in shape or comparing results before and after computation). As a result, if downstream users do this all correctly, they have duplicated a lot of work we already did. Would be better to just share the answer. :)

Given we haven't changed too much lately, seems like the perfect time to make them public, right? ;)

**Comment by mrocklin** [comment]
I'm fine with making assert_eq public

**Comment by jakirkham** [comment]
Addressed in PR ( https://github.com/dask/dask/pull/3726 ).
