### ISSUE TITLE
Fix test_svd_compressed comparison

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2695]
`test_svd_compressed` has a rather [odd comparison]( https://github.com/dask/dask/blob/4d6a121a430c6f408d0155598f5672f2fa5a275a/dask/array/tests/test_linalg.py#L116-L118 ). It would be great to fix up this comparison with something more reasonable like an array to array comparison with a tolerance.

**Comment by jakirkham** [comment]
This [thread]( https://github.com/dask/dask/pull/2681#pullrequestreview-64111456 ) is relevant for fixing the issue.

**Comment by jakirkham** [comment]
Looks like this traces back to commit ( https://github.com/dask/dask/commit/2853e1b52d3695a02d46ed4adff66cdf522d151b#diff-d7290b4980b8cd1764d1e9eabf402115R104 ). Any ideas on this test, @marianotepper?

**Comment by mrocklin** [comment]
Looks good to me today
