### ISSUE TITLE
[Documentation] Meta Keyword for dask.dataframe.apply requires meta of output of .apply, not meta of output of func

### ISSUE THREAD

**Issue by tobsecret** [dask/dask#2717]
From dask.dataframe.apply [documentation](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.apply)
 >   meta : pd.DataFrame, pd.Series, dict, iterable, tuple, optional

>    An empty pd.DataFrame or pd.Series that matches the dtypes and column names of the output. This 
>    metadata is necessary for many algorithms in dask dataframe to work. For ease of use, some 
>    alternative inputs are also available. Instead of a DataFrame, a dict of {name: dtype} or iterable of 
>    (name, dtype) can be provided. Instead of a series, a tuple of (name, dtype) can be used. If not 
>    provided, dask will try to infer the metadata. This may lead to unexpected results, so providing meta is 
>    recommended. For more information, see dask.dataframe.utils.make_meta.

For apply I found this a bit confusing because I was thinking of the output of the func that is passed to apply, so I passed a Series and then got a Pandas Error because a Series object has no attribute Columns.

Would a PR be helpful where I just found the place in the code and added a line of explanation, like:

>  2. The user should provide output metadata via the meta keyword. Note that the output of apply is meant, not the output of the func that you passed. So if your func returns a Series, meta needs to be a DataFrame.

**Comment by TomAugspurger** [comment]
This is discussed in https://docs.dask.org/en/latest/dataframe-design.html#metadata. From that, I hope it's clear that `meta` should be the metadata of the resulting operation applied to the DataFrame. But clarifications are always welcome.
