### ISSUE TITLE
BUG: dask.array no longer supports indexing with np.int64

### ISSUE THREAD

**Issue by shoyer** [dask/dask#2718]
To reproduce:
```
In [20]: x = da.ones((2,), chunks=1)

In [21]: x[0]
Out[21]: dask.array<getitem, shape=(), dtype=float64, chunksize=()>

In [22]: x[np.int64(0)]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-8268a5ebce06> in <module>()
----> 1 x[np.int64(0)]

~/dev/dask/dask/array/core.py in __getitem__(self, index)
   1220
   1221         from .slicing import normalize_index, slice_with_dask_array
-> 1222         index2 = normalize_index(index, self.shape)
   1223
   1224         if any(isinstance(i, Array) for i in index2):

~/dev/dask/dask/array/slicing.py in normalize_index(idx, shape)
    760     idx = idx + (slice(None),) * (len(shape) - n_sliced_dims)
    761     if len([i for i in idx if i is not None]) > len(shape):
--> 762         raise IndexError("Too many indices for array")
    763
    764     none_shape = []

IndexError: Too many indices for array
```

This is a recent regression affecting xarray users, see https://github.com/pydata/xarray/issues/1591. (Apparently we normalize all integer indexing to `np.int64`.)

**Comment by fujiisoup** [comment]
This seems to be caused by that `np.int64` (and also `np.int`) has `ndim` attribute.

Will send a PR.

**Comment by jhamman** [comment]
@mrocklin - what are your plans for the next dask release? I'm wondering when this fix is going to make it out.

**Comment by mrocklin** [comment]
I have no particular plans.  We could do a micro-release if important.  Alternatively people might be able to get by with pip installing from git master?

    pip install git+https://github.com/dask/dask.git --upgrade --no-deps

**Comment by shoyer** [comment]
We have been getting a steady stream of bug reports in this issue from
xarray users -- three so far. I think a micro release would be warranted if
it's not too difficult.

**Comment by mrocklin** [comment]
Sure, I'll try to start this tomorrow.
