### ISSUE TITLE
Allow non-square arrays for tril and triu

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2722]
It seems that the Dask Array implementations of `tril` and `triu` require a square array as input. However there is no similar constraint for NumPy's implementations of these functions. Would be nice if this constraint could be relaxed for Dask Arrays.

**Comment by jakirkham** [comment]
Similarly the square chunking constraint seems a little restrictive. Though I may simply be unaware of the issues being worked around with these constraints.

**Comment by mrocklin** [comment]
I believe that this is now resolved.
