### ISSUE TITLE
Docs - array-api issue

### ISSUE THREAD

**Issue by maxgamurar** [dask/dask#2724]
Hello!
Please check docs:

array-api.rst:223: WARNING: failed to import random.different_seeds

Looks like different_seeds is missing in array-api and should be removed from docs.

**Comment by TomAugspurger** [comment]
Yep, your diagnosis looks correct. Could you submit a PR removing it from `docs/source/array-api.rst`?

**Comment by jakirkham** [comment]
Should be fixed with PR ( https://github.com/dask/dask/pull/2772 ).
