### ISSUE TITLE
Strange behaviour of `ifftshift`: data is rechunked

### ISSUE THREAD

**Issue by woozey** [dask/dask#2725]
Running Python 3.5 (conda) on Mac with dask 0.15.1...
Using shifted IFFT seem not to work out-of-the-box. In particular method `fft.ifftshift`seem to rechunk complex data which is than passed to `fft.ifft` causes chunking issue:

```python
In[1]: import dask.array as da
In [2]: im = da.random.random((2, 3, 4, 5), chunks=(2, 3, 4, 5))
In [3]: im.chunks
Out[3]: ((2,), (3,), (4,), (5,))
In [4]: axes = (2, 3)
In [5]: im_fft = da.fft.fftshift(da.fft.fftn(im, axes=axes), axes=axes)
In [6]: im_fft
Out[6]: dask.array<concatenate, shape=(2, 3, 4, 5), dtype=complex128, chunksize=(2, 3, 2, 2)>
In [7]: im_ifft = da.fft.ifftn(da.fft.ifftshift(im_fft, axes=axes), axes=axes)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-4e78bbcb62c9> in <module>()
----> 1 im_ifft = da.fft.ifftn(da.fft.ifftshift(im_fft, axes=axes), axes=axes)

~/anaconda/lib/python3.5/site-packages/dask/array/fft.py in func(a, s, axes)
    166         for each_axis in axes:
    167             if len(a.chunks[each_axis]) != 1:
--> 168                 raise ValueError(chunk_error % (each_axis, a.chunks[each_axis]))
    169 
    170         chunks = out_chunk_fn(a, s, axes)

ValueError: Dask array only supports taking an FFT along an axis that 
has a single chunk. An FFT operation was tried on axis 2 
which has chunks (2, 2). To change the array's chunks use dask.Array.rechunk.

In [8]: da.fft.ifftshift(im_fft, axes=axes).chunks
Out[8]: ((2,), (3,), (2, 2), (3, 2))
```

Is it an expected behaviour and one has to rechunk the data in between or is it a bug?

**Comment by jakirkham** [comment]
This is expected behavior.

Both `fftshift` and `ifftshift` have to split the data into two pieces and use `concatenate` to combine those two pieces in a different order. If that split goes through an existing chunk, then the data will be split into smaller chunks.

That said, we could `rechunk` inside of `fftshift` and `ifftshift` after the fact to ensure that the original chunking is recreated after this `concatenate` operation. Thoughts?

**Comment by jakirkham** [comment]
Have put together PR ( https://github.com/dask/dask/pull/2733 ) based on what I proposed above. Please let me know if this seems reasonable to you.

**Comment by mrocklin** [comment]
I'm inclined to have fft functions chunk the data as necessary to ensure that their function works.  I do not think that they should then reverse that chunking.  Downstream operations may or may want to the new chunking.  I would prefer to rechunk only when we know it is necessary.

**Comment by jakirkham** [comment]
Would also mention that this problem would go away if we support chunked FFTs ( https://github.com/dask/dask/issues/2620 ), but that may be more challenging than just picking some rules about when and how we rechunk with FFTs.

**Comment by jakirkham** [comment]
Have just put in PR ( https://github.com/dask/dask/pull/2733 ). Running your example with this change results in the following. Hopefully this makes FFTs a little easier to work with in Dask.

```python
In [1]: import dask.array as da

In [2]: im = da.random.random((2, 3, 4, 5), chunks=(2, 3, 4, 5))

In [3]: im.chunks
Out[3]: ((2,), (3,), (4,), (5,))

In [4]: axes = (2, 3)

In [5]: im_fft = da.fft.fftshift(da.fft.fftn(im, axes=axes), axes=axes)

In [6]: im_fft
Out[6]: dask.array<rechunk-merge, shape=(2, 3, 4, 5), dtype=complex128, chunksize=(2, 3, 4, 5)>

In [7]: im_ifft = da.fft.ifftn(da.fft.ifftshift(im_fft, axes=axes), axes=axes)

In [8]: da.fft.ifftshift(im_fft, axes=axes).chunks
Out[8]: ((2,), (3,), (4,), (5,))
```

**Details:** The rechunking only occurs on chunks that are singleton initially. If one runs `fftshift`/`ifftshift` on axes that have more than one chunk, rechunking won't occur as this may result in suboptimal performance. So the same recommendations about rechunking data before it goes into the first FFT function applies. However this should help keep that chunking throughout multiple FFT functions, which appears to be the concern here.
