### ISSUE TITLE
Dask Array's diag supporting diagonal selection

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2726]
Would be nice if Dask Array's [`diag`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.diag ) supported the `k` value to allow selection of the diagonal as NumPy's implementation [does]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html ). It seems like Dask Array's API docs suggest `diag` does support `k`, but the code does not allow for this option.

https://github.com/dask/dask/blob/f015b5f0808420bdd23f8408f5822d2f5aff8ff1/dask/array/creation.py#L413

**Comment by jakirkham** [comment]
It might make sense to rewrite `diag` to use `diagonal` after PR ( https://github.com/dask/dask/pull/4431 ) is accepted. This would be a way to solve this problem and cutdown on code as well.

**Comment by lightsighter** [comment]
It's worth pointing out this feature is broken in both directions. You also can't make a dask 2-D array from a vector on k!=0 diagonal. Support for da.diagonal doesn't help at all in this case as da.diagonal only extracts diagonals from 2-D arrays. Here's a use case to reproduce the problem:

`import dask.array as da

v = da.random.uniform(size=100,chunks=50)
A = da.diag(v,k=1)`

which yields the following error:

`TypeError: diag() got an unexpected keyword argument 'k'`

At a minimum the documentation should be updated to reflect that you don't support the 'k' keyword argument. Currently the documentation says that it is supported.
http://docs.dask.org/en/latest/array-api.html#dask.array.diag

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/issues/3265 or docstrings

**Comment by TAdeJong** [comment]
I am working on a pull request on this using #4431 for the diagonal extraction case. WIP though, as I was surprised by the $(n+k)*(n+k)$ output of `np.diag(np.ones(n), k)`.
I also want to have a look into cleaning up the shared but different code in `da.triu`, `da.tril` and `da.diag`.

**Comment by jakirkham** [comment]
Cool, thanks for working on this. Please let us know if you need pointers or would like someone to take a look.
