### ISSUE TITLE
Casting dataframes to arrays has meta information loss. 

### ISSUE THREAD

**Issue by daniel-severo** [dask/dask#2727]
I've noticed that when casting a DataFrame to an Array the first dimension (a.k.a. the number of lines) becomes `nan`.

```python
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> df = dd.from_pandas(pd.DataFrame(3*[range(5)]), npartitions=2)
>>> df.values
dask.array<values, shape=(nan, 5), dtype=int64, chunksize=(nan, 5)>
```
I get that in more complex DAGs the dimension might not be computable beforehand, but this isn't the case.

**Comment by jcrist** [comment]
Dask Dataframes don't keep their length as metadata, so we can't know the zeroth dimension in the converted dask array. Changes to allow this would result in a fairly major redesign of dask dataframe.
