### ISSUE TITLE
COMPAT: pandas 0.21.0

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2736]
In https://github.com/pandas-dev/pandas/pull/17710 pandas delays the import of various libraries. An upshot of this is that `pandas.core.computation/__init__.py` doesn't import `pandas.core.computation.expression`, so the code in https://github.com/dask/dask/blob/0f29e7b8570dcd72d0dfbcaf276fce0189ab099f/dask/dataframe/core.py#L38-L43 fails.

The recommended way to set that value is `pd.set_option("compute.use_numexpr", True)`.

Does anyone know what that's being set in the first place? I'll look around the history.

**Comment by mrocklin** [comment]
My guess is that we wanted to avoid oversubscribing threads.

**Comment by TomAugspurger** [comment]
Seems to go back to https://github.com/dask/dask/pull/502 (cachey)
