### ISSUE TITLE
da.concatenate raises an error on contatenation of custom arrays

### ISSUE THREAD

**Issue by mraspaud** [dask/dask#2742]
When I create dask Arrays from dictionaries, I get problems when concatenating them later on. I can't see what I'm doing wrong, so I would believe this is a bug...

Here comes a minimal test script and the corresponding traceback. I'm running on python 2.7 and dask 0.15.3.

```python
import dask.array as da
import numpy as np


def chunks_from_blocksize(shape, chunks):
    shape = tuple(map(int, shape))
    chunks = tuple(map(int, chunks))
    return tuple(((bd,) * (d // bd) + ((d % bd,) if d % bd else ())
                 if d else (0,))
                 for d, bd in zip(shape, chunks))

def onez(shape, blocksize):
    name = 'onez1563'  # unique identifier
    vchunks, hchunks = chunks_from_blocksize((shape, (blocksize, blocksize))

    dsk = {(name, i, j): (np.ones, (vcs, hcs))
             for i, vcs in enumerate(vchunks)
             for j, hcs in enumerate(hchunks)}

    dtype = np.ones(0).dtype  # take dtype default from numpy

    return da.Array(dsk, name, shape=shape, chunks=(blocksize, blocksize), dtype=dtype)


arr1 = onez((60, 70), 50)
arr2 = onez((60, 80), 50)

da.concatenate((arr1, arr2), axis=1)
```

traceback:
```text
Traceback (most recent call last):
  File "test_dask.py", line 28, in <module>
    da.concatenate((arr1, arr2), axis=1)
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 2346, in concatenate
    _, seq = unify_chunks(*uc_args, warn=False)
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 2115, in unify_chunks
    arrays.append(a.rechunk(chunks))
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 1695, in rechunk
    return rechunk(self, chunks, threshold, block_size_limit)
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/rechunk.py", line 261, in rechunk
    raise ValueError("Provided chunks are not consistent with shape")
ValueError: Provided chunks are not consistent with shape
```

Thanks for any help in that matter !

**Comment by mrocklin** [comment]
The error that you've gotten implies that there might be something wrong with how you're specifying chunks.  Have you inspected the chunks and shape of your arrays and verified that they are as expected?

**Comment by mraspaud** [comment]
```text
arr1 shape (60, 70)
arr1 chunks ((50, 10), (50, 20))
arr2 shape (60, 80)
arr2 chunks ((50, 10), (50, 30))
```
I can't see anything wrong here, am I missing something ?

**Comment by mraspaud** [comment]
For reference, using the builtin `da.ones` instead of my own `onez` yields the same values for shape and chunks, but concatenate works!

```python
arr1 = da.ones((60, 70), chunks=50)
print 'arr1 shape', arr1.shape
print 'arr1 chunks', arr1.chunks
arr2 = da.ones((60, 80), chunks=50)
print 'arr2 shape', arr2.shape
print 'arr2 chunks', arr2.chunks

da.concatenate((arr1, arr2), axis=1)
```
output
```
arr1 shape (60, 70)
arr1 chunks ((50, 10), (50, 20))
arr2 shape (60, 80)
arr2 chunks ((50, 10), (50, 30))
```

**Comment by mrocklin** [comment]
Your unique identifier is not unique between the two arrays.  If you change it then things work out fine.

**Comment by mrocklin** [comment]
I recommend using something like

    from dask.base import tokenize
    name - 'onez-' + tokenize(shape, blocksize)

**Comment by mraspaud** [comment]
wow, thanks ! sorry about that. Might I ask under which condition two arrays must have different names ?

**Comment by mrocklin** [comment]
If they are in any way different in value, shape, chunks, or dtype.

**Comment by mrocklin** [comment]
In dask.array/dataframe/bag name is almost always just 

    'some-descriptive-name-' + tokenize(*args, **kwargs)

**Comment by mraspaud** [comment]
Thanks. It makes sense. I my real life case, I'm using the differing attributes of the class it belongs to, and it seems to work now. Sorry again for the noise, I hadn't fully understood the importance of the name.
