### ISSUE TITLE
Unpin conda/pytables from conda-forge on travis

### ISSUE THREAD

**Issue by jcrist** [dask/dask#2744]
In #2738 a few changes were made to fix recent failures. Most of these are due (I think) to binary incompatibility issues on conda-forge right now. When these are fixed, we should be able to revert these changes.

- [ ] Unpin conda (currently pinned, somehow fixing issues with graphviz)
- [x] Switch back to pytables from conda-forge (waiting on https://github.com/conda-forge/pytables-feedstock/issues/19)

The changes to be reverted are in d9a5e1945dd2 (all but the switch to `conda list`).

**Comment by jakirkham** [comment]
So I noticed that `graphviz`'s pinnings were out of date. Not sure if that caused problems, but have refreshed them in PR ( https://github.com/conda-forge/graphviz-feedstock/pull/17 ).

**Comment by jakirkham** [comment]
Experimenting with `conda-forge`'s `pytables` in PR ( https://github.com/dask/dask/pull/3088 ).
