### ISSUE TITLE
ValueError: Length mismatch with added/missing columns

### ISSUE THREAD

**Issue by citynorman** [dask/dask#2752]
Hi folks,

I'm having trouble using dask if the CSV files contain an equal amount of columns (either added or missing). Couldn't find any solutions in the API docs, the issues or on SO.

**code**

	import pandas as pd
	import numpy as np
	import dask.dataframe as dd

	nobs=3
	df5=pd.DataFrame({'t':['2016-12-05']*nobs,'a':np.arange(nobs)*1}) # starting format
	df6=pd.DataFrame({'t':['2016-12-06']*nobs,'a':np.arange(nobs)*1,'b':np.arange(nobs)*2}) # column added

	# save data
	df5.to_csv('data-2-5.csv',index=False)
	df6.to_csv('data-2-6.csv',index=False) # new columns

	print(pd.concat([df5,df6]))

	# dask fails to show missing columns as NANs
	ddf = dd.read_csv('data-2-*.csv',assume_missing=True)
	print(ddf.compute()) # error
	print(ddf.loc[:,['a','b','t']].compute()) # error

** stack trace**

  File "<ipython-input-88-3ec4c9fac830>", line 17, in <module>
    print(ddf.compute()) # error

  File "C:\Anaconda3\lib\site-packages\dask\base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "C:\Anaconda3\lib\site-packages\dask\base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 562, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 529, in get_async
    fire_task()

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 504, in fire_task
    callback=queue.put)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 551, in apply_sync
    res = func(*args, **kwds)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 295, in execute_task
    result = pack_exception(e, dumps)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 290, in execute_task
    result = _execute_task(task, data)

  File "C:\Anaconda3\lib\site-packages\dask\local.py", line 271, in _execute_task
    return func(*args2)

  File "C:\Anaconda3\lib\site-packages\dask\compatibility.py", line 47, in apply
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\dask\dataframe\io\csv.py", line 67, in pandas_read_text
    df.columns = columns

  File "C:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2983, in __setattr__
    return object.__setattr__(self, name, value)

  File "pandas\_libs\src\properties.pyx", line 65, in pandas._libs.lib.AxisProperty.__set__ (pandas\_libs\lib.c:45103)

  File "C:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 471, in _set_axis
    self._data.set_axis(axis, labels)

  File "C:\Anaconda3\lib\site-packages\pandas\core\internals.py", line 2836, in set_axis
    (old_len, new_len))

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

** setup **

dask.__version__
Out[87]: '0.15.3'

Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by mrocklin** [comment]
Dask.dataframe expects all CSV files to have the same structure.  In more custom situations you might consider using dask.delayed instead.  Here are some pointers to documentation:

- http://dask.pydata.org/en/latest/delayed.html
- http://dask.pydata.org/en/latest/delayed-collections.html
- https://gist.github.com/mrocklin/e7b7b3a65f2835cda813096332ec73ca

**Comment by citynorman** [comment]
Ok thanks @mrocklin, I'll check those out. Btw it also fails if the number of columns are the same but the order is swapped... Delayed potentially the solution again I guess?

	import pandas as pd
	import numpy as np
	import dask.dataframe as dd

	nobs=3
	df5=pd.DataFrame({'t':['2016-12-05']*nobs,'a':np.arange(nobs)*1,'b':np.arange(nobs)*2}) # starting format
	df6=pd.DataFrame({'t':['2016-12-06']*nobs,'a':np.arange(nobs)*1,'b':np.arange(nobs)*2}) # column added

	# save data
	df5.to_csv('data-3-5.csv',index=False)
	df6[['b','a','t']].to_csv('data-3-6.csv',index=False) # new columns

	print('*pandas*')
	print(pd.concat([df5,df6]))

	# dask fails to show missing columns as NANs
	ddf = dd.read_csv('data-3-*.csv')
	print('*dask*')
	print(ddf.compute()) # wrong column content for t=='2016-12-06'

**Comment by apiszcz** [comment]
I may have a similar issue where the CSV (read_csv) works correctly, however when I use parquet files (read_parquet) I get a stack trace.

```
(Pdb) df=df.compute()
*** ValueError: Length mismatch: Expected axis has 8 elements, new values have 3 elements.
```

The input data only has 3 columns, with CSV that is what is read, with read_parquet I am picking 'dir0' to 'dir4'

```
(Pdb) df.columns
Index(['a', 'b', 'c', 'dir4', 'dir2', 'dir1', 'dir3', 'dir0'], dtype='object')
```

**Comment by citynorman** [comment]
You can use `d6stack` library to deal with this problem. See https://github.com/d6t/d6tstack/blob/master/examples-dask.ipynb

**Comment by mrocklin** [comment]
I think I'm going to close this.  Dask dataframe read_csv today expects data to be uniform.  If this is not the case then you should handle things with external processing (like the library mentioned above) or perhaps by converting to an easier to manage format, like Parquet.
