### ISSUE TITLE
Add atleast_*d functions

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2753]
Would be nice to have [`atleast_1d`]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.atleast_1d.html ), [`atleast_2d`]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.atleast_2d.html ), and, [`atleast_3d`]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.atleast_3d.html ) for Dask Arrays. Should be pretty trivial to create with Dask Array operations alone.

**Comment by mrocklin** [comment]
No objection from me.  I would hope that these implementations would be
very easy to implement.

**Comment by jakirkham** [comment]
Cool. Yep, these should be trivial. More of a note to self and check to make sure they are still reasonable for inclusion.

**Comment by jakirkham** [comment]
Hmm...seems `atleast_2d` and `atleast_3d` were added in PR ( https://github.com/dask/dask/pull/854 ), but not added to the public API or documented. Though it seems they can't handle 0-D data. Also it seems that `atleast_1d` is missing. Not sure if there was any reason for these omissions.

**Comment by jakirkham** [comment]
Do you know why these were excluded from the API or don't handle the 0-D case? Admittedly they were added a long time ago?

**Comment by mrocklin** [comment]
Probably just sloppiness

**Comment by jakirkham** [comment]
Ok, thanks for clarifying. Wanted to make sure I wasn't missing something.

Have addressed this in PR ( https://github.com/dask/dask/pull/2760 ).
