### ISSUE TITLE
dask 0.15.3 read_parquet engine auto detect error

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#2754]
The CSV (read_csv) works correctly, however when I use parquet files (read_parquet) I get a stack trace.
Operating environment is Windows 10, local file system.
```
(Pdb) df=df.compute()
*** ValueError: Length mismatch: Expected axis has 8 elements, new values have 3 elements.
```

The input data only has 3 columns, with CSV that is what is read, with read_parquet I am picking 'dir0' to 'dir4'. I am using arrow with fastparquet to create the files. I have noticed a much slower first file write performance with thrift, arrow seems consistent with write speeds for all output.

```
FAIL: ddf.read_parquet(ipath, columns=['a','b','c'])
(Pdb) df.columns
Index(['a', 'b', 'c', 'dir4', 'dir2', 'dir1', 'dir3', 'dir0'], dtype='object')
```

If I set the engine='arrow', three columns are read and all is well.

```
`PASS: FAIL: ddf.read_parquet(ipath, columns=['a','b','c'],engine='arrow')
(Pdb) df.columns
Index(['a', 'b', 'c'], dtype='object')
`
```

With engine='arrow' I can read thrift or arrow files, with engine='fastparquet' failure occurs with fastparquet files.

**Comment by jcrist** [comment]
There has been considerable work on parquet support lately, and improvements and bugfixes made to both the fastparquet and arrow readers/writers. Without a reproducible example I can't check if your issue still persists. Closing for now as stale, feel free to reopen if the issue persists and you can provide a [minimal reproducible example](https://stackoverflow.com/help/mcve)
