### ISSUE TITLE
read_hd5 gives TypeError

### ISSUE THREAD

**Issue by larsr** [dask/dask#2755]
I want to read a hd5 file, but get an error, even though I created the hd5 file with `format='table'`.

As an example, running this code

```
import pandas as pd
import numpy as np
import dask.dataframe as dd

filename = 'test.hd5'

with pd.HDFStore(filename, mode='w', format='table') as h:
    for i in range(10):
        key = "i{i}".format(**locals())
        h[key] = pd.DataFrame(np.random.random((100,100)))

dd.read_hdf(filename,'*')
```

gives the error

```
TypeError: 
This HDFStore is not partitionable and can only be use monolithically with
pandas.  In the future when creating HDFStores use the ``format='table'``
option to ensure that your dataset can be parallelized
```

**Comment by mrocklin** [comment]
Can you verify that tables stored in this way are genuinely being written in tabular format?  Given the error my guess is that this isn't happening as you might expect.  You could try using the pd.DataFrame.to_hdf method instead, I suspect that it handles these keyword arguments better than the `pd.HDFStore` object.  If so then you might want to raise an issue on the pandas issue tracker.

**Comment by larsr** [comment]
Apparently [`format` is not a defined parameter to `HDFStore`][1], (see [src][2]) and one should use [`put`] instead, like this for the example above:

```
with pd.HDFStore(filename, mode='w') as h:                                     # CHANGED
    for i in range(10):
        key = "i{i}".format(**locals())
        h.put(key, pd.DataFrame(np.random.random((100,100))), format='table')  # CHANGED

dd.read_hdf(filename,'*')
```

[1]: https://github.com/pandas-dev/pandas/issues/13291#issuecomment-221842282
[2]: https://github.com/pandas-dev/pandas/blob/v0.20.3/pandas/io/pytables.py#L444
[3]: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.HDFStore.put.html
