### ISSUE TITLE
Pass hostname to read_parquet

### ISSUE THREAD

**Issue by quartox** [dask/dask#2757]
When I let the dask dataframe infer the hostname it comes up with `'user'`. There has been problems parsing values from my cluster before (e.g. `hdfs-site.xml` uses high availability mode see https://github.com/dask/dask-yarn/issues/17#issuecomment-312935212).

If I do not pass the host through `storage_options` this yields the following error:

```
ConnectionError: Connection Failed: InvalidParameter: Cannot parse URI: hdfs://user, missing port or invalid HA configuration	Caused by: HdfsConfigNotFound: Config key: dfs.ha.namenodes.user not found
```

If I pass the host through `storage_options` I get a different error:

```
KeyError: "storage options ({'host': 'hostname.allstate.com', 'port': 8020}) and path url options ({'protocol': 'hdfs', 'path': '/hive/warehouse/dra_aa_sandbox.db/test_policy', 'host': 'user'}) collision is detected"
```

The offending line that tries to parse the host is here: https://github.com/dask/dask/blob/master/dask/utils.py#L881

With the collision here: https://github.com/dask/dask/blob/master/dask/utils.py#L894

I am open to submitting a fix, but I wonder if the user passed hostname should take precedence or if the parsing can be improved for my cluster.

**Comment by martindurant** [comment]
huh, I guess the code wants your url to be like `'hdfs://hostname.allstate.com:8020/user/...'` and none of this is to do with reading from hdfs-site.xml. Does it work with `'hdfs:///user/...'` (note three slashes - should imply no host given) ?
Clearly that's not quite right, and the error message is not helpful. Certainly, not including host/port in the URL should work fine, as the same url works for hdfs3, and passed parameters should override. If both URL and storage_parameters give a host, probably it's better to decide precedence than to error.

**Comment by quartox** [comment]
Yes it works with 3 slashes and gives a warning about port. Alternatively I can pass it directly like you suggested.

**Comment by martindurant** [comment]
OK, cool. Then this can be closed, with a note that the docs could be a bit more specific.
