### ISSUE TITLE
Wrapper always pass None to random.choice

### ISSUE THREAD

**Issue by rzu512** [dask/dask#2767]
From dask/array/random.py:

>     with ignoring(AttributeError):
>         @doc_wraps(np.random.RandomState.choice)
>         def choice(self, a, size=None, replace=True, p=None, chunks=None):
>             return self._wrap(np.random.RandomState.choice, a,
>                               size=size, replace=True, p=None, chunks=chunks)

Wrapper gets non-None p argument -> Wrapper passes None to p kwarg of np.random.RandomState.choice anyway.

Test:

> import dask
> import dask.array as da
> import numpy as np
> import dask.array.random as dar
> import matplotlib.pyplot as plt
> 
> p = np.arange(12)
> p = p*1.0 / np.sum(p)
> 
> p = da.from_array(p, chunks=6)
> s = dar.RandomState()
> 
> c = s.choice(len(p), p=p,size=10000,chunks=8)
> cc = c.compute()
> b = np.bincount(cc)
> print(b)
> 
> c = np.random.choice(len(p), p=np.array(p), size=10000)
> b = np.bincount(c)
> print(b)
> 

Result from numpy and dask are different.

> [806 815 833 873 877 809 850 818 837 792 892 798]
> [   0  117  332  467  637  731  901 1079 1251 1316 1483 1686]

**Comment by jcrist** [comment]
Thanks for the bug report. This is now fixed in #2781:

```python
In [1]: import numpy as np, dask.array as da

In [2]: p = np.arange(12)

In [3]: p = p / p.sum()

In [4]: c = da.random.choice(len(p), p=p, size=10000, chunks=8)

In [5]: cc = c.compute()

In [6]: np.bincount(cc)
Out[6]:
array([   0,  134,  295,  492,  591,  802,  842, 1097, 1212, 1361, 1541,
       1633])

In [7]: np_c = np.random.choice(len(p), p=p, size=10000)

In [8]: np.bincount(np_c)
Out[8]:
array([   0,  146,  300,  413,  656,  762,  901, 1053, 1216, 1317, 1565,
       1671])
```
