### ISSUE TITLE
Support relabelling of individual chunks for global consistency

### ISSUE THREAD

**Issue by imaluengo** [dask/dask#2768]
I think dask was missing a feature that I very much needed and I came up with a method to do so (find it below). It might be that there are dask tools to achieve the same, in which case I would be very glad to hear about them, but I couldn't find anything.

A bit about the problem: imagine that we want to perform a connected [components algorithm](https://en.wikipedia.org/wiki/Connected-component_labeling) over an ND-array. But the array is too big to fit in memory. One could apply local connected components locally using `map_blocks` of `da.Array`, but that would return components with the same labelling (0, 1) for every block. In order to get a unique results for the components, each of the local components of the map operation has to be relabelled to a global unique index.

Here is what I came with:

```python
def dask_relabel_chunks(A):
    """
    Relabel all the the chunks of an input array. It is assumed
    that a `map_blocks` or `map_overlap`, has been previously applied
    over `A`, and each of the chunks of `A` contains a local labelling.

    The function labels all the chunks so that all the labels all
    globally independent.

    E.g. for an input dataset with 3 different chunks of local labels:

    Chunk1: [1, 0, 0] # Maxlabel = 1
    Chunk2: [0, 2, 1] # Maxlabel = 2
    Chunk3: [2, 0, 1] # Maxlabel = 2

    The relabelling of the chunks would look like:

    newChunk1: [1, 0, 0]
    newChunk2: [2, 4, 3] # Chunk2 + Maxlabel(newChunk1) + 1
    newChunk3: [7, 5, 6] # Chunk3 + Maxlabel(newChunk2) + 1

    Parameters:
    -----------
    A: dask.Array
        An input array to be relabeled

    Returns
    -------
    B: dask.Array
        Dask array of the same shape, with chunks relabelled.
    """
    inds = tuple(range(A.ndim))
    max_per_block = da.atop(np.max, inds, A, inds, axis=inds,
                            keepdims=True, dtype=A.dtype,
                            adjust_chunks={i:1 for i in inds})
    block_index_global = da.cumsum(max_per_block.ravel() + 1)

    def relabel(a, block_id=None):
        bid = int(np.ravel_multi_index(block_id, A.numblocks))
        if bid == 0:
            return a
        return a + block_index_global[bid-1]

    return A.map_blocks(relabel)
```

Another problem is that components might fall in boundaries between chunks, but that is problem specific (in the case of connected components) and could be solved as a postprocessing step later.

I thought it was worth sharing it.

**Comment by mrocklin** [comment]
Cool algorithm.  Thanks for sharing!
