### ISSUE TITLE
Harden toolz requirement?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2769]
Wondering if it makes sense to harden the `toolz` requirement of `dask`. It looks like every extra requirement install of `dask` adds `toolz`. Considering as it is pure Python, adds no additional requirements, and has friendly licensing, this seems like a very painless thing to require. Does this seem reasonable or are there constraints/issues that I am missing?

**Comment by mrocklin** [comment]
No strong thoughts on this.  I agree that adding toolz is probably ok.

**Comment by jcrist** [comment]
I'd be -0.5 to making toolz a hard dependency. I know of a few projects that are using dask just for the threaded/synchronous scheduler, and currently that part of dask has no dependencies outside the standard library. That said, I think this use case is in the minority.

Is there something in core dask that you'd like to use toolz for?

**Comment by jakirkham** [comment]
Sorry not following. How does making `toolz` a hard dependency complicate things for those users? Also is there some way we can reach out to them to get feedback?

Was more interested in this question from a dependency management perspective. Namely it should simplify specifying dependencies internally (e.g. extras) and for cases where the `conda` package `dask-core` is used.

**Comment by mrocklin** [comment]
There hasn't been much follow up here.  I'm inclined to agree with @jcrist that we have core functionality that doesn't require toolz.  Some folks like the stdlib-only option.  

Happy to reopen if people want to continue the conversation, but for now I'm going to close it out.
