### ISSUE TITLE
Dependency issue after "conda install Dask"

### ISSUE THREAD

**Issue by Schlump** [dask/dask#2788]
I've set up a new conda env for some developing, as i only need a few packages i only installed Dask and Scipy.

Ive got the follwing code:
`allArrays = np.concatenate([imread(dataDir+subdir+'/*.tif').compute() for subdir in os.listdir(dataDir)]) `

Which runs fine in my other environments, but fails  because of  line 49 in /array/image.py

` imread = imread or sk_imread`

with a name error:

> NameError: global name 'sk_imread' is not defined

In the requires.txt scikit-image is not listed as dependency. 
After installing it manually it works.

**Comment by mrocklin** [comment]
Yes, dask works optionally with some libraries like scikit-image, scikit-learn, etc..  We don't include these as hard dependencies.

**Comment by jcrist** [comment]
We could add a nicer error here, using `dask.utils.import_required`. For an example, see [here](https://github.com/dask/dask/blob/master/dask/diagnostics/profile.py#L202-L203).

**Comment by Schlump** [comment]
Well if it's intentional i guess there's no issue at all ;)

**Comment by mrocklin** [comment]
It would be nice to be able to list optional dependencies.  Maybe some day
this will be easier :)

**Comment by jakirkham** [comment]
> It would be nice to be able to list optional dependencies. Maybe some day this will be easier :)

Funny that I stumble across this looking for something else. ;)

For those following along, PR ( https://github.com/dask/dask/pull/3456 ) is an attempt to list all optional dependencies. :)
