### ISSUE TITLE
Unexpected behavior when map_partition column order does not match meta column order

### ISSUE THREAD

**Issue by mauricef** [dask/dask#2789]
## Problem
Dask will modify the `columns` for DataFrames returned by `map_partitions` if it detects that the DataFrame does not match both the meta content and ordering. This may result in misaligned data, that is data where the column values do not match the column labels.

```
import dask.dataframe as dd
import numpy as np
import pandas as pd

df = pd.DataFrame(data={'a': ['a'], 'b': ['b']})
ddf = dd.from_pandas(df, npartitions=1)

def _calculate(part):
    return part[['b', 'a']]

meta = [('a', np.object), ('b', np.object)]
ddf.map_partitions(_calculate, meta=meta).compute()
```

## Current behavior

The resulting dataframe will contain misaligned data:
```
 b | a
-------
 a | b
```

I believe this is because `apply_and_enforce` sets the columns on the dataframe when it detects that the returned dataframe does not match the meta. 

## Expected behavior
I would have expected Dask to either 

1. Raise an error that the the data returned from map_partitions does not match the meta 
2. Detect that the ordering is different but the contents and dtype are the same and leave the dataframe unmodified
3. Reorder the column labels and the data so that they maintain proper alignment.

Maybe I am misunderstanding something about the intended use of map_partitions or of the meta parameter?

**Comment by TomAugspurger** [comment]
I think that we typically assume that the `meta` provided by the user is correct, which in this case it's not.

That said, I think erroring loudly would be nice for this particular example. I'm curious which tests would break if you changed `apply_and_enforce` to error when the columns don't match. Do you have time to check @mauricef?

**Comment by mauricef** [comment]
In the above case maybe we could say that the meta is incorrect, but what if I passed a dict as meta?

```
meta = {'a': np.object, 'b': np.object}
```

What order does the _calculate need to return columns in to pass the `apply_and_enforce` step? I would expect that as long as the columns and dtypes match, Dask should consider the dataframe to be matching the meta regardless of the ordering of the columns.

**Comment by mauricef** [comment]
Hey! Just checking in, I would consider making a fix for this but its not clear to me what the fix should be or if I'm just misunderstanding something about the intended usage of map_partitions.

My understanding is 

- I can pass a `meta` to `map_partitions` in a variety of formats including an itterable of `(column_name, column_dtype)` tuples or a dict of `{column_name:column_dtype}` mappings.
- If `map_partitions` detects that the pandas DataFrame returned from the mapping `func` does not match the column ordering of the meta it will set the `DataFrame.columns` in `_apply_and_enforce`
- Setting the columns will cause a misalignment between the column data and the column labels.

Are those statements correct? If I pass a `dict` for the `map_partitions(meta=)` then how would I even know what the correct column order to return is, since the dict does not specify an order?

**Comment by TomAugspurger** [comment]
Good point on meta being a dictionary, I hadn't considered that. We could only check the order when an ordered collection is passed, but that seems unwise.

@jcrist do you have thoughts here?

**Comment by sschuldenzucker** [comment]
Hi! I just produced another data point on this. I hit this issue in my own work, firmly believing that the order of columns in `meta` didn't matter. This was because I can pass a dict as `meta` and because almost all other functions take care of column order for me, for example `concat()`. I'd like to see this issue fixed, especially because it could lead to silent data corruption.

Does anyone have an insight regarding why a (destructive/overwriting) `_rename()` is used in `apply_and_enforce`? It seems that the implicit assumption is that the result of `func` always has the correct order of columns, but not necessarily the correct names for columns. It seems that more commonly, the opposite is assumed: that `func` returns the correct *names* for columns, but perhaps in a different order. If this is true, how about going to the latter? AFAIU, this could by done by changing the line
https://github.com/dask/dask/blob/8dadb1b0f1b680a084d39083b32a89d8f09b6830/dask/dataframe/core.py#L3569
to:
```
        return df[c]
```

Am I overlooking anything?

**Comment by TomAugspurger** [comment]
I vaguely recall @jcrist saying he doesn't thing `_rename` should overwrite the column names, but I may be mis-remembering.

> Am I overlooking anything?

No, I don't think so. I agree with your assessment. Do you have time to try out that change and see how many of the `dask.dataframe` tests fail?

**Comment by TomAugspurger** [comment]
We should probably bump the priority on this. I won't have time this week, but hopefully next.

**Comment by mrocklin** [comment]
@jcrist it looks like your opinion has been asked for a couple times here.  Can you take a look at this and respond?

**Comment by Lemina** [comment]
Hi, I also encountered this issue. Any updates please?

**Comment by TomAugspurger** [comment]
I applied the following

```diff
diff --git a/dask/dataframe/core.py b/dask/dataframe/core.py
index 2b2be7dd..3a436b55 100644
--- a/dask/dataframe/core.py
+++ b/dask/dataframe/core.py
@@ -2627,7 +2627,7 @@ class DataFrame(_Frame):
 
     @columns.setter
     def columns(self, columns):
-        renamed = _rename_dask(self, columns)
+        renamed = _rename_dask(self, columns, overwrite=True)
         self._meta = renamed._meta
         self._name = renamed._name
         self.dask = renamed.dask
@@ -3992,7 +3992,7 @@ def apply_and_enforce(*args, **kwargs):
     return df
 
 
-def _rename(columns, df):
+def _rename(columns, df, overwrite=False):
     """
     Rename columns of pd.DataFrame or name of pd.Series.
     Not for dd.DataFrame or dd.Series.
@@ -4025,7 +4025,10 @@ def _rename(columns, df):
             return df
         # deep=False doesn't doesn't copy any data/indices, so this is cheap
         df = df.copy(deep=False)
-        df.columns = columns
+        if overwrite:
+            df.columns = columns
+        else:
+            df = df[columns]
         return df
     elif is_series_like(df) or is_index_like(df):
         if is_series_like(columns) or is_index_like(columns):
@@ -4037,7 +4040,7 @@ def _rename(columns, df):
     return df
 
 
-def _rename_dask(df, names):
+def _rename_dask(df, names, overwrite=False):
     """
     Destructively rename columns of dd.DataFrame or name of dd.Series.
     Not for pd.DataFrame or pd.Series.
@@ -4054,10 +4057,10 @@ def _rename_dask(df, names):
     """
 
     assert isinstance(df, _Frame)
-    metadata = _rename(names, df._meta)
-    name = 'rename-{0}'.format(tokenize(df, metadata))
+    metadata = _rename(names, df._meta, overwrite=overwrite)
+    name = 'rename-{0}'.format(tokenize(df, metadata, overwrite))
 
-    dsk = partitionwise_graph(_rename, name, metadata, df)
+    dsk = partitionwise_graph(_rename, name, metadata, df, overwrite)
     graph = HighLevelGraph.from_collections(name, dsk, dependencies=[df])
     return new_dd_object(graph, name, metadata, df.divisions)
```

and only one test seems to fail (we get an `Index([1, 2, 3])` instead of an `Int64Index([1, 2, 3])`. @Lemina are you interested in making a PR with a change like that and tracking down why that last test is failing? Otherwise I should be able to get to this next week.

**Comment by TomAugspurger** [comment]
I plan to work on this this week.

**Comment by TomAugspurger** [comment]
Thinking more on this, I do think that dask now does the right thing for the original example

```python
import dask.dataframe as dd
import numpy as np
import pandas as pd

df = pd.DataFrame(data={'a': ['a'], 'b': ['b']})
ddf = dd.from_pandas(df, npartitions=1)

def _calculate(part):
    return part[['b', 'a']]

meta = [('a', np.object), ('b', np.object)]
ddf.map_partitions(_calculate, meta=meta).compute()
...
ValueError: The columns in the computed data do not match the columns in the provided metadata
```

I'm updating the documentation about this. 


> almost all other functions take care of column order for me, for example concat()

IIUC, your concat example is that you're allowed to `concat([df1, df2])` whose columns are different orders? If so, I think that's a bit different from what we're talking about here. pandas will typically align during operations (doing a union on the keys). Dask can't do that in this case, since we really should be able to distinguish between a function that returns ``[('a', int), ('b', 'float')]`` and one that returns ``[('b', 'float'), ('a', 'int')]``.

> especially because it could lead to silent data corruption

Do you have an example where we this currently occurs? It's changed since the issue was originally opened.
