### ISSUE TITLE
Job pending forever when '/' in task key

### ISSUE THREAD

**Issue by quertenmont** [dask/dask#2790]
Thank you for reporting an issue.

Please read the following guidelines to ensure that your issue is handled
properly.

1.  If you have a general usage question like
    *"How do I filter a dask.dataframe?"* then please consider asking the
    question on StackOverflow instead using the #Dask tag
2.  If you have found a bug, then please include a self-contained copy-pastable
    example that generates the issue if possible.
3.  Please also include an exception and full traceback of the error if
    available.
4.  If you have an issue with fastparquet, the distributed system, s3fs, etc.
    then please consider submitting a report to their issue trackers instead.
    A full list of repositories can be found here:
    [https://github.com/dask](https://github.com/dask)
5.  Please include the versions of Python, dask, and other relevant libraries
    if they are applicable, (pandas, dask.distributed, etc..)

Thank you again for your efforts.

[How to create a Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)

**Comment by quertenmont** [comment]
kwargs["key"]="MyName/MySubName"
future = dask_client.submit(myFunc, **kwargs) 
Results in a task that is in "pending" state forever...

kwargs["key"]="MyName/MySubName".replace("/","_")
future = dask_client.submit(myFunc, **kwargs) 
Results in a task that is entering in "running" state almost imediately...

Tooks me a while to figure this out... might be good to stress the limitation of the task "name" in the doc.  Or fix this behaviour

**Comment by mrocklin** [comment]
Are you able to provide a minimal reproducible example?  Here was my attempt:

```python
In [1]: from dask.distributed import Client

In [2]: client = Client()

In [3]: future = client.submit(lambda x: x + 1, 100, key='foo/bar')

In [4]: future.result()
Out[4]: 101
```

**Comment by quertenmont** [comment]
hum... no actually I can't reproduce the issue...
Although I fight with it for 2 hours this morning...  weird...
Let's say I wasn't fully aware.

Sorry for the noise!
