### ISSUE TITLE
dataframe tail incorrectly reporting index value?

### ISSUE THREAD

**Issue by littlegreenbean33** [dask/dask#2795]
Hi, receive an unexpected value of index when performing a tail over a 400M CSV file read with dd.read_csv. As I have not provided an index at reading, the index is created as a sequential list of number that should end in 400M..ish.

As per reading the manual I do not get to the conclusion that my assumption is wrong.

These are the steps and results I get. Installation is a fresh conda with python 3.5.4, using distributed, running across a cluster of 4 linux machines same OS/ubuntu version and configuration.

File is split across 393 csv.gz files with unix command split  .

`
    us=dd.read_csv("/home/julian/kaggle/wsdm/original_data/user_logs_dir/*",
    ...:                     compression="gzip",               
    ...:                     infer_datetime_format=True,
    ...:                     parse_dates=[1],
    ...:                     dtype={"msno":str,"date":str,"num_25":np.float32,"num_50":np.float32,"num_75":np.float32,
    ...:                            "num_985":np.float32,"num_100":np.float32,"num_unq":np.float32,"total_secs":np.float32},
    ...:                     names=["msno","date","num_25","num_50","num_75","num_985","num_100","num_unq","total_secs"],
    ...:                     header=0,blocksize=None)

In [20]: us.head()
Out[20]: 
                                           msno       date  num_25  num_50  \
0  0009K5+x2nW6DPHo+VWSWncFCMO2qfa5vjAOmYT7jbc= 2015-08-27    12.0     1.0   
1  000A3Z7XXQoJI58Y6J46y2vfChRKWYVkJMXw4o4QMMM= 2015-01-01     1.0     0.0   
2  000A3Z7XXQoJI58Y6J46y2vfChRKWYVkJMXw4o4QMMM= 2015-01-02     4.0     4.0   
3  000A3Z7XXQoJI58Y6J46y2vfChRKWYVkJMXw4o4QMMM= 2015-01-04     3.0     2.0   
4  000A3Z7XXQoJI58Y6J46y2vfChRKWYVkJMXw4o4QMMM= 2015-01-06     2.0     0.0   
 num_75  num_985  num_100  num_unq    total_secs  
0     3.0      2.0      3.0     12.0   2087.626953  
1     1.0      2.0      5.0      9.0   1594.683960  
2     2.0      2.0     82.0     56.0  19498.697266  
3     0.0      0.0     25.0     28.0   6437.534180  
4     1.0      0.0     20.0     13.0   5194.895020  

`

Up to here, everything normal. Index start a 0 sequentially

`
In [21]: us.tail()
Out[21]: 
                                                msno       date  num_25  \
106537  ZzzzuoedGDQPTRJJvxmx8blCGTjHY+f8/hoWTHzdKPQ= 2017-02-22     0.0   
106538  ZzzzuoedGDQPTRJJvxmx8blCGTjHY+f8/hoWTHzdKPQ= 2017-02-25     0.0   
106539  ZzzzuoedGDQPTRJJvxmx8blCGTjHY+f8/hoWTHzdKPQ= 2017-02-26     0.0   
106540  zzZzw3AmtiWq7Rz85RgOD4CYv43+uXQ88VXmeeJ+wLU= 2015-02-23     0.0   
106541  ZZzZyNwX6/uBV8p+ZSLcRWapC6UA1xSob6mXjsSEsj0= 2017-02-20     0.0   

 num_50  num_75  num_985  num_100  num_unq   total_secs  
106537     0.0     0.0      0.0      8.0      8.0  1998.000000  
106538     0.0     0.0      0.0      7.0      7.0  1785.119995  
106539     0.0     0.0      0.0      4.0      4.0  1076.640015  
106540     0.0     0.0      0.0      1.0      1.0   257.384003  
106541     0.0     0.0      0.0      1.0      1.0   252.000000 
`

The last file partition has exactly 106541 number of lines, however as a total in file

`
In [23]: us.index.count().compute()
Out[23]: 392106150
`
Which is the kind of number I was expecting.

did I got something wrong ?

Thanks.

JC

**Comment by mrocklin** [comment]
Index values will not correspond to row numbers when reading csv files.  It is actually quite difficult to get the number of rows without reading through the entire file ahead of time.

**Comment by littlegreenbean33** [comment]
I am ok with your explanation. I understand the rational. I indeed expected that  the dataframe had gone through a  full pass in order to give it an index. It works contrary to what most people (coming from pandas) would expect....  it may be eventually a source of confusion for newcomers.

It is a source of con
