### ISSUE TITLE
flake8 now checks for bare except blocks

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#2815]
Flake8 was recently updated to check for bare except blocks http://flake8.pycqa.org/en/latest/release-notes/3.5.0.html. Currently in dask/.travis.yml

https://github.com/dask/dask/blob/de2afdb76e34e0675a4ed429f28a49a314d33400/.travis.yml#L71-L72

there is an additional check (after `flake8 dask`) for bare except blocks that I think can be removed now.

**Comment by jcrist** [comment]
Thanks, fixed in #2816.
