### ISSUE TITLE
Add DataFrame.squeeze

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2830]
```python
In [3]: pd.DataFrame({"A": [1, 2]}).squeeze()
Out[3]:
0    1
1    2
Name: A, dtype: int64
```

**Comment by freddiev4** [comment]
Hi @TomAugspurger I'd like to work on this. Couple of questions for you:
- Where do you think this should belong?
- Do you have any initial thoughts in regards to implementation?

**Comment by TomAugspurger** [comment]
Thanks!

It'll apply to both `dd.Series` and `dd.DataFrame`.

For Series, it can be as simple as `return self`

For DataFrame, you'll want to use `map_partitions`, it should be pretty similar to something like `dropna`: https://github.com/dask/dask/blob/643ae878d7cc5204aa096b9f9946e5ccac0aea25/dask/dataframe/core.py#L2415

Tests can go in `tests/test_dataframe.py` probably. Let me know if you run into any difficulties.

**Comment by freddiev4** [comment]
FWIW, going to try and get a PR open for this in the next few days

**Comment by cr458** [comment]
@TomAugspurger @freddiev4 could have a look at this if it has gone quiet? Don't mean to intrude.

**Comment by freddiev4** [comment]
@cr458 feel free to give it a go 🙂sadly I just don't have time for it.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/dask/dask/pull/3366
