### ISSUE TITLE
dask.bag.read_text does not read binary when encoding=None

### ISSUE THREAD

**Issue by charmoniumQ** [dask/dask#2841]
Python 3.6.3 (default, Oct  4 2017, 08:37:57)
    [GCC 6.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import dask, dask.bag
    >>> print(dask.__version__)
    0.15.4
    >>> urls = dask.bag.from_sequence([b'this is a test']).to_textfiles('/tmp/*.json', encoding=None)
    >>> dask.bag.read_text(urls, encoding=None).compute(get=dask.get)
    None 3
    ['this is a test']

Note that the byte-string, `b'this is a test'`, was written and the string,`'this is a test'` was read. If the byte-string has unencodable data, then an exception is thrown:

    >>> urls = dask.bag.from_sequence([b'this is a test \x80']).to_textfiles('/tmp/*.json', encoding=None)
    >>> dask.bag.read_text(urls, encoding=None).compute(get=dask.get)
    None 3
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.6/site-packages/dask/base.py", line 99, in compute
        (result,) = compute(self, traverse=False, **kwargs)
      File "/usr/lib/python3.6/site-packages/dask/base.py", line 206, in compute
        results = get(dsk, keys, **kwargs)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 562, in get_sync
        return get_async(apply_sync, 1, dsk, keys, **kwargs)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 508, in get_async
        fire_task()
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 504, in fire_task
        callback=queue.put)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 551, in apply_sync
        res = func(*args, **kwds)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 295, in execute_task
        result = pack_exception(e, dumps)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
        result = _execute_task(task, data)
      File "/usr/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
        return func(*args2)
      File "/usr/lib/python3.6/site-packages/dask/bag/core.py", line 1438, in reify
        seq = list(seq)
      File "/usr/lib/python3.6/site-packages/dask/bag/text.py", line 97, in file_to_blocks
        for line in f:
      File "/usr/lib/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 15: invalid start byte

This is especially troublesome if the user wants to save pickled datatypes, as in:

    urls = bag.map(pickle.dumps).to_textfiles('/tmp/*.json', encoding=None)
    bag.read_text(urls, encoding=None).map(pickle.loads)

as `pickle.loads` takes byte-strings not strings.

**Comment by TomAugspurger** [comment]
I'm not sure that those functions are intended to bytes. The docs could clarify this, but they are named `read_text` and `to_textfiles`. I suspect this is because it can be difficult to sniff line delimiters on undecoded blobs of bytes.

I'd recommend writing your own reader and using `dask.delayed`:

```python
In [15]: import dask.delayed

In [16]: import pickle

In [17]: def reader(path):
    ...:     with open(path, 'rb') as f:
    ...:         b = f.read()
    ...:

In [18]: def reader(path):
    ...:     with open(path, 'rb') as f:
    ...:         b = f.read()
    ...:     return pickle.loads(b)
    ...:

In [19]: import glob

In [20]: paths = glob.glob('/tmp/*.json')

In [21]: readers = [dask.delayed(reader)(f) for f in paths]

In [22]: dask.bag.from_delayed?
```

**Comment by martindurant** [comment]
You may also want to look at `dask.bytes.read_bytes`

**Comment by charmoniumQ** [comment]
@TomAugspurger That makes sense. I was a little confused by the discrepency between the behavior of `to_textfiles` (which does accept bytes if you pass `encoding=None`) and `read_text` which does not.

Perhaps the easiest way to store the binary data is to base85 encode it first. The output would be completely utf-8 compatible and not have newlines.

**Comment by TomAugspurger** [comment]
Yes, if you look at `to_textfiles`, you'll see that `encoding` is passed to `dask.bytes.core.write_bytes`, which requires that the data be bytes already.

The docstring also says

```
**Bag Contents**: The bag calling ``to_textfiles`` must be a bag of
text strings. For example, a bag of dictionaries could be written to
JSON text files by mapping ``json.dumps`` on to the bag first, and
then calling ``to_textfiles`` :
```

So I think that's already pretty clear. I think the question whether `to_textfiles` should validate that the contents are indeed text before writing.
