### ISSUE TITLE
Incorrect parsing/coercing of invalid timestamps

### ISSUE THREAD

**Issue by kadrach** [dask/dask#2845]
Dask does not appear to handle out of bounds dates very well:

```
# minimal-0.csv
id,date
1,2017-10-31 00:00:00

# minimal-1.csv - out of bounds date/timestamp
id,date
2,4998-01-01 00:00:00
```

```python
    import dask.dataframe as ddf

    df = ddf.read_csv('minimal-*.csv', dtype={'id': 'int',
                                              'date': 'str'},
                      parse_dates=['date']).compute()
```

For some reason, this doesn't fail, but produces incorrect timestamps
```
df
Out[1]: 
   id                          date
0   1 2017-10-31 00:00:00.000000000
0   2 2075-03-26 02:07:11.452241920
df.dtypes
Out[2]: 
id               int64
date    datetime64[ns]
dtype: object
```

Pandas will ignore the failing `parse_dates` directive and return an `object` dtype. `pd.to_datetime` will throw a `pandas._libs.tslib.OutOfBoundsDatetime` error as expected. 

Is it possible to use `pd.to_datetime(.., error='coerce')` with Dask (which would return `NaT` in this case?).

```
pandas (0.21.0rc1)
distributed (1.19.3)
numpy (1.13.3)
dask (0.15.4) 
```

**Comment by kadrach** [comment]
`ddf.read_csv('minimal-*.csv', parse_dates=['date']).head(n=2)` seems to just drop the row. How is this impacted by the distributed scheduler? The source CSV (not the minimal example) has ~300M rows with ~100 dodgy dates.

**Comment by TomAugspurger** [comment]
Unfortunately, I don't think there's much dask can. It'd be nice if pandas had an option to throw an error when the CSV parser encounters an out of bounds value.

**Comment by jcrist** [comment]
This should be fixed by #2863.

The issue here was that the first partition worked, so the dtype of the column was found to be a `datetime64`. In the other partitions dask tries to convert mismatched dtypes, and succeeds in this case as numpy `astype` is much more lax with conversion (leading to the overflow you saw above):

```python
In [1]: import numpy as np

In [2]: np.array(['4998-01-01 00:00:00'], dtype='M8[ns]')
Out[2]: array(['2075-03-26T02:07:11.452241920'], dtype='datetime64[ns]')
```

To fix this, we now error nicely when a `parse_dates` column fails to properly convert. Your example:

```
>>> df = dd.read_csv('minimal-*.csv', parse_dates=['date']).compute()
<traceback...>
ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

The following columns failed to properly parse as dates:

- date

This is usually due to an invalid value in that column. To
diagnose and fix it's recommended to drop these columns from the
`parse_dates` keyword, and manually convert them to dates later
using `dd.to_datetime`.
```

As you and @TomAugspurger both mentioned, you can use `dd.to_datetime` (note that we implement this method, no need to use `map_partitions`) to convert datetimes, failing or coercing as needed. The error message also suggests that you use this.

**Comment by jcrist** [comment]
Also filed a bug for this in numpy: https://github.com/numpy/numpy/issues/9956.

**Comment by kadrach** [comment]
Thank you @jcrist for looking into this, that sounds like good news!

I've been using a workaround similar to what @TomAugspurger suggested. 

I somehow had convinced myself that `dd.to_datetime` did not support `errors='coerce'`, but I might have been playing with too many things at the same time when trying to figure out what was happening :)
