### ISSUE TITLE
ResourceProfiler keeps running after `__exit__`

### ISSUE THREAD

**Issue by pitrou** [dask/dask#2869]
If you write something like:
```
    with ResourceProfiler(dt=0.01) as rprof:
        # ...
```

then the profiler process keeps running at the end of the `with` block. You have to call `rprof.close()` as well, which is unexpected.
(noticed in the distributed test suite)

**Comment by pitrou** [comment]
@jcrist

**Comment by jcrist** [comment]
If I remember correctly, that was to allow using the same profiler multiple times without paying the cost of restarting the tracker process:

```python
rprof = ResourceProfiler()

with rprof:
   ...

with rprof:
   ...
```

This should be cleaned up as soon as the object exits scope though (`__del__` just calls `close`). Are you seeing this process live on outside the test?

**Comment by pitrou** [comment]
> Are you seeing this process live on outside the test?

Yes. It stays alive until the test session end.

**Comment by pitrou** [comment]
As a general rule of thumb, objects with a `close()` method implicit call `close()` in their `__exit__`. The fact that a test written by @mrocklin made that assumption reinforces my point, IMHO :-)

**Comment by pitrou** [comment]
(note that unless you're Windows, that child process is being forked, so it's reasonably cheap to start... not costless, but not a full spawn either)

**Comment by pitrou** [comment]
So, perhaps a suggestion is to change the idiom and:
* have `with` blocks handle the process lifetime
* have separate `pause()` and `resume()` methods to control when the actual profiling is done?
