### ISSUE TITLE
dask apply in a loop, running over all the previews columns created each iteration

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#2872]
I am using python 2.7 with dask dataframe.

I wish to create 4 new columns, 
each of them should contain 1 if the value of two columns in the row are equal and 0 if not.

When I run a loop to create the 4 columns, the values are created properly, but when I check the values after the loop finishes, they are all the same as the last calculation in the loop. 

I tried to use compute and then assign the column but this does not help,

The only way I made it work is using apply, then compute the column, and convert it into pandas dataframe, then using merge to put the values to the original dataframe. 

Please refer to my [stackoverflow question](https://stackoverflow.com/questions/47201116/python-dask-data-frame-apply-over-a-column-in-a-loop-runs-over-the-results-o) for more detail.

**Comment by TomAugspurger** [comment]
This doesn't look like a bug, so stackoverflow is the correct place to go. I'll answer over there later if I have a chance.
