### ISSUE TITLE
get_dummies web docummentation is missing

### ISSUE THREAD

**Issue by mrkowalski** [dask/dask#2874]
The function is documented in sources. I mean this one:
dask/dask/dataframe/reshape.py

But not visible under https://dask.pydata.org/en/latest/search.html?q=get_dummies&check_keywords=yes&area=default#

This effectively makes one think there is no such functionality, even though it is there.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @mrkowalski, apologies for the lack of reply. `get_dummies` was added to the API documentation in #4896.
