### ISSUE TITLE
dask.distributed.progress does not work in jupyter notebook

### ISSUE THREAD

**Issue by tobsecret** [dask/dask#2876]
dask.distributed.progress does not work for me in the jupyter notebook anymore and throws the following error when I try to use it:
> Widget Javascript not detected.  It may not be installed or enabled properly.
> Error rendering Jupyter widget. Widget not found {"model_id":"c11c2bd9c91b490ca0cbacda849a2dde"}

So I made a new environment, using the following commands:
>conda create -n daskTest python=3.5 --yes
>activate daskTest
>conda install -c conda-forge dask --yes
>conda install jupyter --yes

A minimal code example, as well as my env.yml and a conda list dump can be found at this gist:
https://gist.github.com/tobsecret/70148de951817269f4851aef70faff4e

For convenience, here is the minimal example:

```python
#IN[1]:
from time import sleep
from random import randint
from dask.distributed import Client, progress

#IN[2]:
c = Client()
#A list of futures does not work
tasks = [c.submit(sleep, randint(10, 40)) for i in range(300)]
progress(tasks)
#Widget Javascript not detected.  It may not be installed or enabled properly.
#Error rendering Jupyter widget. Widget not found: {"model_id":"c11c2bd9c91b490ca0cbacda849a2dde"}

#IN[3]:
#A single future also does not work
fut = c.submit(sleep, 200)
progress(fut)
#Widget Javascript not detected.  It may not be installed or enabled properly.
#Error rendering Jupyter widget. Widget not found: {"model_id":"c11c2bd9c91b490ca0cbacda849a2dde"}
```

**Comment by mrocklin** [comment]
Do other jupyter widgets work?

**Comment by TomAugspurger** [comment]
Conda is supposed to run `jupyter nbextension enable --py widgetsnbextension` for you when you install ipywidgets. Perhaps try that and see if the problem persists.

**Comment by tobsecret** [comment]
Hmm, oddly enough they do not. Bokeh gallery examples and holoviews work just fine however.
Will try getting the jupyter widgets to work and report back.

**Comment by tobsecret** [comment]
Update, the widgets do not work in the new toy environment created just for this github issue. Nothing changes when I use `jupyter nbextension enable --py widgetsnbextension`, it tells me that the validation went ok but then still nothing works:

```
>jupyter nbextension enable --py widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok
```

In an older dask tutorial the widgets still work fine and so does `dask.distributed.progress`. I added the .yml file for that working environment to the gist.

**Comment by mrocklin** [comment]
If IPython widgets don't work generally then this issue is probably unrelated to Dask.  I recommend asking for help from the Jupyter team.  Is it ok to close this issue?

**Comment by tobsecret** [comment]
I will make a new issue in jupyter then.

**Comment by martindurant** [comment]
I can confirm that I've seen the same behaviour for a widget completely unrelated to dask. @tobsecret , was this with jupyter, jupyterhub or jupyter-lab?

**Comment by tobsecret** [comment]
Just regular jupyter, fresh environment, everything installed from scratch. I found a thread on jupyter that says maybe ipywidgets 6.0 was rolled out prematurely. https://github.com/jupyter/notebook/issues/2764#issuecomment-339316326

When I get the time, I will check if that solves the problem.
