### ISSUE TITLE
Streaming tasks with from_sequence not working

### ISSUE THREAD

**Issue by knkski** [dask/dask#2879]
According to [these docs](http://dask.pydata.org/en/latest/bag-creation.html#db-from-sequence), the correct usage for streaming tasks with `from_sequence` should look like this:

```python
from dask import bag as db

def generator(num):
    yield from range(num)

db.from_sequence([100]).map(generator).map(lambda x: x + 1).map(lambda x: x * 2).compute()
```

However, that raises this exception:

```python
Traceback (most recent call last):
  File "scripts/test.py", line 8, in <module>
    db.from_sequence([100]).map(generator).map(lambda x: x + 1).map(lambda x: x * 2).compute()
  File "/virtualenv/lib/python3.6/site-packages/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/virtualenv/lib/python3.6/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/virtualenv/lib/python3.6/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/virtualenv/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/virtualenv/lib/python3.6/site-packages/dask/compatibility.py", line 59, in reraise
    raise exc.with_traceback(tb)
  File "/virtualenv/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/virtualenv/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/virtualenv/lib/python3.6/site-packages/dask/bag/core.py", line 1438, in reify
    seq = list(seq)
  File "/virtualenv/lib/python3.6/site-packages/dask/bag/core.py", line 1597, in map_chunk
    for a in zip(*args):
  File "/virtualenv/lib/python3.6/site-packages/dask/bag/core.py", line 1598, in map_chunk
    yield f(*a)
  File "scripts/test.py", line 8, in <lambda>
    db.from_sequence([100]).map(generator).map(lambda x: x + 1).map(lambda x: x * 2).compute()
TypeError: unsupported operand type(s) for +: 'generator' and 'int'
```

This method works, but attempts to load the entire iterator into memory:

```python
from dask import bag as db

db.from_sequence(range(100)).map(lambda x: x + 1).map(lambda x: x * 2).compute()

```

This is with Python 3.6.3 and Dask 0.15.4.

The context of this is that I would like to extract a list of items from a large (100GB) XML file, do a few transforms on each item, then persist each item to a database.

I also found this issue, which makes it look like this should work, but no luck: https://github.com/dask/dask/issues/2423

**Comment by mrocklin** [comment]
You should not use a generator function within map.  Functions to map should expect a single element and return a single element.  If you want to operate on iterators then you might be looking for `map_partitions`.

If your actual goal is to split a large file into many pieces then ideally you can just split the file along some sort of delimiter and just process those separate blocks of bytes separately.

**Comment by knkski** [comment]
@mrocklin: When you say split the file along a delimiter, do you mean splitting the file up somehow prior to using `dask`, and then doing something like this?

```python
from dask import bag as db

db.from_sequence(['split-1.xml', 'split-2.xml', ...]).map(transform_record).map(persist_record).compute()
```

That would work, although I was hoping to just iterate through the single large file and process it without having to create a bunch of split files. As it stands, I've got a more verbose option that accomplishes that with `distributed`:

```python
from distributed import Client
from queue import Queue

client = Client(...)
input_queue = Queue()
remote_queue = client.scatter(input_queue)
transform_queue = client.map(transform_record, remote_queue)
persist_queue = client.map(persist_record, transform_queue)

result_queue = client.gather(persist_queue)

for item in yield_xml_items():
    input_queue.put(item)

input_queue.put(None)

while True:
    item = result_queue.get()

    if item is None:
        break
```

Closing the issue, since this isn't a bug

**Comment by mrocklin** [comment]
I meant using the `linedelimiter=` keyword in `read_text`.  If you have a string that you know separates records you can pass that string to split the file reasonably.  If you want to go lower level you could also look at http://dask.pydata.org/en/latest/bytes.html
