### ISSUE TITLE
Standardize filesystem interface between dask and arrow

### ISSUE THREAD

**Issue by jcrist** [dask/dask#2880]
In #2801 a discussion started around how to handle the differences between arrow and dask filesystem classes in a more robust way.

**Current Behavior**

Dask and arrow have differing interfaces for filesystem objects. To handle this, `pyarrow` contains a few wrappers for dask filesystems, and applies them if the string of the class name matches a couple known ones (https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L786-L792). This seems hacky and not-robust. It also doesn't support all of the dask filesystems, only a few special cased ones.

**A few ideas**

- Dask is responsible for creating wrappers for each of its filesystems that subclass from `pyarrow.filesystem.FileSystem`. This is much more robust (we fulfill the required interface, no inference hacks), but may require us to maintain wrappers for each fileystem.

- Arrow and dask standardize on the same interface, and the check moves to one checking for an abstract base class. This means that dask doesn't need to depend on arrow (nor arrow on dask), as long as we fill the same interface.

  From inspection, it looks like the differences amount to:
  - Lack of a walk method on a few of our classes
  - Lack of `isfile`/`isdir` in s3fs
  - Difference in walk method between s3fs and the arrow wrapper
  - `delete` vs `rm` for method name

Of these two solutions, the second is definitely more desirable, as it would simplify the interaction between these two projects.

**Comment by jcrist** [comment]
Ping @martindurant, @mrocklin, @wesm (and probably others on the arrow team?) for comment.

**Comment by mrocklin** [comment]
I suspect that a good step forward would be for someone (I nominate @jcirst) to write an abstract base class for the full interface, to have some discussion over that interface, and then to include it (and necessary changes to subclasses) within each project.  

If we wanted to be more serious we could also publish it as a proper Python module with a tiny doc page to which we could refer others who come into this space in the future.

**Comment by jcrist** [comment]
Sure, I can handle that. I'll most likely need hdfs arrow parquet support before then though, so I may patch #2801 separately.

**Comment by mrocklin** [comment]
Moving conversation from https://github.com/dask/dask/issues/2801 over here (cc @wesm @xhochy )

@wesm suggested the following:

> We could create a pure Python library to define a abstract public API for these sorts of things. Then we aren't relying on duck typing

I agree.  Some decisions that need to be made

1.  Name of this library and class (I'll throw out `filesystem_interface.FileSystem` as a strawman)
2.  Home of this library (I'll suggest the `pydata` org)
3.  Mechanisms for subclassing, do we want to use the `abc` module to enforce things?
4.  The precise methods that are required and their names.  Do we have any current conflicts?  Which projects are missing which methods?

**Comment by martindurant** [comment]
Fixing walk is, of course, fairly straight-forward, as we could always provide a walk_list with the old behaviour. However, we (from dask) should be careful not to be biased in defining the standard. 

The first of the libraries I made (hdfs3) has methods mostly matching posix, which in turn match most of the nomenclature in HDFS, but I know some would have preferred closer consistency with the python standard library. Other FSs are less posix-like in nature.

I would say that the posix conventions are indeed a useful model to go from (it really is a standard) and would mean the least changes for the existing FS back-ends used by Dask; some FSs (azure) may be resistant to change - that's one vote.

**Comment by xhochy** [comment]
Is there already a (design) document that describes what `dask` expects from a filesystem implementation? That would be a good starter for a common definition.

**Comment by martindurant** [comment]
There is https://github.com/dask/dask/blob/master/dask/bytes/local.py

**Comment by mrocklin** [comment]
We might consider publishing this as a prose design document somewhere that is more human readable and less likely to change as Dask changes.  This would, presumably, be part of the documentation of any interface library.

**Comment by xhochy** [comment]
There is also https://www.pyfilesystem.org/ with a slightly different API then dask/arrow. Would that be also a candidate project that may use the same APIs or does someone see a clear differentiator why we would need a different base API?

**Comment by wesm** [comment]
I think it's worth assessing if that one meets our requirements.

**Comment by xhochy** [comment]
Another thing to add that I encounter during implementing a FileSystem for AzureStorageBlob is there is a lot of Python code that can be shared between the object store based implementations. The code of S3FS and GCSFS is very similar in many situations and I can easily use a copy&paste approach to quickly get started with Azure. But copying the code (even if the License allows it) is not feeling right. This in addition to a set of a abstract base classes, we would also benefit from an object store filesystem base class.

**Comment by mrocklin** [comment]
I'm entirely in favor of code sharing and a super-class where appropriate.

I have to admit that I haven't yet investigated pyfilesystem sufficiently well to have an opinion on it.

**Comment by martindurant** [comment]
+ hdfs3 and azure-data-late.

Yes, it's very true, that each library has a very similar structure, but also there are many differences in the specific implementations. The base class wouldn't make building any of the libraries any easier, there isn't much to be shared, I don't think, but it would make their usage easier - it would require guarantees of the same set of methods, behaving in the same prescribed way. This is largely true already.

**Comment by martindurant** [comment]
I have begun a repo which can be used to define a spec for filesystems: https://github.com/martindurant/filesystem_spec
(note that it has many personal comments from me, but that is just to get conversation going, everything is up for discussion)

Everyone here is welcome to read and comment on it in issues and PRs, if you agree that it is a location we can work on together to build consensus. If useful, it should be moved from my personal account to somewhere shared.

cc @xhochy @fjetter @wesm @mrocklin @jcrist

**Comment by mrocklin** [comment]
@xhochy @fjetter if you get a chance it would be useful to get your thoughts on that repository, and what might need to change for Arrow to use it, either formally or informally

@martindurant it's nice to see that there is some common code that might cut down on replication between the various filesystem libraries :)

**Comment by wesm** [comment]
I'm pretty backlogged until later this month -- it may be useful in the meantime to make the Arrow dev mailing list aware of this effort, though

**Comment by martindurant** [comment]
How would I do that - or would you mind doing it for me?

**Comment by mrocklin** [comment]
It looks like there is a green "Join Mailing List" button on
https://arrow.apache.org/

**Comment by ian-r-rose** [comment]
This is done now that `fsspec` exists and is pyarrow-compatible
