### ISSUE TITLE
Bag.to_dataframe fails if bag is empty and meta not specified.

### ISSUE THREAD

**Issue by asford** [dask/dask#2884]
This is an *bit* of an edge case and I'm not entirely *entirely* sure the current behavior is incorrect, but I found the result surprising enough that it may be a bug. I'd be happy to contribute a fix if you agree that the behavior should be changed.

This scenario may occur when the bag pipeline contains some configurable components that either (a) filter values from the bag or (b) add data to elements of the bag. In the event that the "filtering" reduces the bag size to zero the call to Bag.to_dataframe will fail when attempting to infer column names. This is different than the expected result, which would be an "empty" dask DataFrame.

Evaluating the bag with `.compute()` and passing the results to `pandas.DataFrame` produces and empty dataframe. Similarly, calling `to_dataframe(meta=pandas.DataFrame())` yields and empty frame.

Repro:

````
import dask
import dask.bag
import pandas

def add_val(e):
    e["b"] = e["a"] + 10
    return e
    
def filter_val(e):
    return e["b"] > 100

source_bag = dask.bag.from_sequence([{"a" : i} for i in range(2)])

print("SOURCE VIA COMPUTE: ",
      pandas.DataFrame(source_bag.compute()))
print("MAPPED VIA COMPUTE: ",
      pandas.DataFrame(source_bag.map(add_val).compute()))
print("FILTERED VIA COMPUTE:",
      pandas.DataFrame(source_bag.map(add_val).filter(filter_val).compute()))

print("SOURCE VIA TO_DATAFRAME: ",
      source_bag.to_dataframe())
print("MAPPED VIA TO_DATAFRAME: ",
      source_bag.map(add_val).to_dataframe())
print("FILTERED VIA TO_DATAFRAME WITH META: ",
      source_bag.map(add_val).filter(filter_val).to_dataframe(meta=pandas.DataFrame()))
print("FILTERED VIA TO_DATAFRAME NO META: ",
      source_bag.map(add_val).filter(filter_val).to_dataframe())
````

Yields:
````
SOURCE VIA COMPUTE:     a
0  0
1  1
MAPPED VIA COMPUTE:     a   b
0  0  10
1  1  11
FILTERED VIA COMPUTE: Empty DataFrame
Columns: []
Index: []
SOURCE VIA TO_DATAFRAME:  Dask DataFrame Structure:
                   a
npartitions=2       
               int64
                 ...
                 ...
Dask Name: to_dataframe, 4 tasks
MAPPED VIA TO_DATAFRAME:  Dask DataFrame Structure:
                   a      b
npartitions=2              
               int64  int64
                 ...    ...
                 ...    ...
Dask Name: to_dataframe, 6 tasks
FILTERED VIA TO_DATAFRAME WITH META:  Dask DataFrame Structure:
Empty DataFrame
Columns: []
Index: []
Dask Name: to_dataframe, 6 tasks
/usr/local/miniconda3/envs/dev_base/lib/python3.6/site-packages/dask/bag/core.py:1973: UserWarning: Insufficient elements for `take`. 1 elements requested, only 0 elements available. Try passing larger `npartitions` to `take`.
  "to `take`.".format(n, len(r)))
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-44-7f461515d6f8> in <module>()
     26       source_bag.map(add_val).filter(filter_val).to_dataframe(meta=pandas.DataFrame()))
     27 print("FILTERED VIA TO_DATAFRAME NO META: ",
---> 28       source_bag.map(add_val).filter(filter_val).to_dataframe())

/usr/local/miniconda3/envs/dev_base/lib/python3.6/site-packages/dask/bag/core.py in to_dataframe(self, meta, columns)
   1195                 meta = columns
   1196             else:
-> 1197                 head = self.take(1)[0]
   1198                 meta = pd.DataFrame([head], columns=columns)
   1199         elif columns is not None:

IndexError: tuple index out of range
````

**Comment by mrocklin** [comment]
What would be the dtypes and columns of such a dataframe?  Empty as well?  If so then a fix for this should be somewhat simple by setting `meta = pd.DataFrame()`.  Would you be interested in submiting a PR for this?

**Comment by asford** [comment]
Yes, I believe the output of `pandas.DataFrame(my_bag.compute())` should be the same as `my_bag.to_dataframe().compute()` in this case and `dask.DataFrame` should have empty columns. I believe the fix will be in [`Bag.to_dataframe`](https://github.com/dask/dask/blob/0.15.4/dask/bag/core.py#L1196) but I've already noticed that the classes of exceptions raised vary depending on how the bag has been generated and I'll need to investigate this a bit more.

I'm happy to file a PR for this change and will start on this shortly.

**Comment by mrocklin** [comment]
Currently the answer is "no, dask.dataframe does not guarantee correct operation in this case".  However I can appreciate that it would be useful in a variety of practical settings.

**Comment by asford** [comment]
I completely understand that this isn't supported now, but what's your gut instinct on whether this could be added to the current implementation? Is a strict definition a `dask.DataFrame`'s column layout baked into the implementation? Would this be a feature someone without a deep understanding of `dask` internals could work on as a learning project?

**Comment by mrocklin** [comment]
If we were to accept this we would need to have confidence that most (all?) dask.dataframe algorithms worked well even with extra columns.  I would not be very surprised to learn that this was or was not the case.

This *could* be a learning project, with the caveat that, because of the possibility above, it is somewhat likely that it will not be merged regardless.  

If you were curious and wanted to pursue this I would first create a dask.dataframe that had incomplete metadata, and then run through a bunch of operations with it, seeing where it performed well and where it broke.  This sort of exploration would probably help us to make a more informed decision.

```python
df = pd.DataFrame({'x': ..., 'y': ...})
value = dask.delayed(df)
ddf = dd.from_pandas([value], meta=df.iloc[:0][['x']])
# do stuff with ddf, see what works and what doesn't
```

**Comment by jcrist** [comment]
As someone who wrote the current metadata handling for `dask.dataframe`, I'm going to be a fairly hard -1 on anything that makes knowing the complete metadata for each partition in a dask dataframe possible. Many operations rely on knowing what the columns, dtypes, and indices are in order to function properly. Being strict about the metadata helps ensure correctness and eases the already large maintenance burden of dask dataframe.

If your goal as a user is just to not have to specify the metadata beforehand, you can either let dask compute it for you in `to_dataframe`, or somehow infer it yourself based on your query.

Alternatively, if your only goal is to turn a `bag` into an in-memory pandas dataframe (never using `dask.dataframe` operations), then you can probably write your own conversion function using `bag.to_delayed` and `dask.delayed` (applying `pd.DataFrame`, and `pd.concat` appropriately).

**Comment by asford** [comment]
@jcrist I'm assuming to mean "knowing the complete metadata for each partition in a dask dataframe ***impossible***?"

Completely understand if you're the maintainer for section of the code and *don't* want to see. My instinct is that having incomplete metadata could make a number of dependent components quite tricky. Thank you for the clear 👎.

**Comment by jcrist** [comment]
Apologies for the delayed response here. I've pushed #3025 which should help with this problem.

> What would be the dtypes and columns of such a dataframe? Empty as well? If so then a fix for this should be somewhat simple by setting meta = pd.DataFrame()

The issue with automatically inferring no columns is that you might have no data in the first partition, but data in subsequent partitions. As such, we shouldn't assume no data in the bag, but rather error nicely:

```python
In [1]: %load test.py

In [2]: # %load test.py
   ...: import dask.bag as db
   ...:
   ...: data = [(i, i * 2) for i in range(100)]
   ...:
   ...: b = db.from_sequence(data, npartitions=5)
   ...: b2 = b.filter(lambda x: x[0] > 100)  # no data in first partition
   ...:
   ...: df = b2.to_dataframe()
   ...:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-ebbfd82a117b> in <module>()
      7 b2 = b.filter(lambda x: x[0] > 100)  # no data in first partition
      8
----> 9 df = b2.to_dataframe()

~/Code/dask/dask/bag/core.py in to_dataframe(self, meta, columns)
   1224                 head = self.take(1, warn=False)
   1225                 if len(head) == 0:
-> 1226                     raise ValueError("`dask.bag.Bag.to_dataframe` failed to "
   1227                                      "properly infer metadata, please pass in "
   1228                                      "metadata via the `meta` keyword")

ValueError: `dask.bag.Bag.to_dataframe` failed to properly infer metadata, please pass in metadata via the `meta` keyword
```
