### ISSUE TITLE
DataFrame.groupby level param

### ISSUE THREAD

**Issue by lsorber** [dask/dask#2887]
I checked the docs and the `dask.dataframe.groupby` source, but I don't at first sight see a way of grouping DataFrames by (a subset of) their index similar to pandas' `df.groupby(level=0)`.

Right now a workaround is `df.groupby(df.index)`, but it's unclear to me if that would benefit from having a sorted index on the DataFrame. Is there a more idiomatic way of grouping by index?

**Comment by TomAugspurger** [comment]
Like pandas, the first argument to `groupby` can refer to index levels by name. Does that work for you?

http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#groupby-enhancements

**Comment by lsorber** [comment]
I did try that, but unfortunately it didn't work for the dask DataFrame I was testing on. In fact, I didn't expect it to work because grouping by index name is undocumented. I searched through the issues and found that #957 concluded that grouping by index name wasn't desirable because (at the time) pandas didn't support it either.

I'll see if I can reproduce the circumstances under which grouping by index name didn't work for me.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/pull/2636 added support for this in dask. What version of dask are you using?

IIRC there was an issue with names needing to be list-like, though that may have been in pandas. Does `df.groupby(['index_name'])` work?
