### ISSUE TITLE
Eager evaluation in dask.array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#292]
Dask.collections remove the execution of code from where it was written.  This can make debugging frustrating and difficult to track down.  It may be useful to have an auto-evaluate mode that calls `.compute` and then `.from_array` on every dask.array operation.  

This would be bad for performance obviously but good to track down bugs in complex programs on small test datasets.

**Comment by shoyer** [comment]
+1 this is a great idea. Might be a good idea to disable concurrent executor at the same time (e.g., with `dask.set_options(debug=True)`)

**Comment by cowlicks** [comment]
I like @shoyer's idea. But maybe it should be `dask.set_options(eager_eval=True)`. But what would something like `my_bag.filter(foo)` return? Another bag, or the result of `my_bag.filter(foo).compute()`? 

It seems like it should be the former, so we would discard the result of the computation?

**Comment by shoyer** [comment]
@cowlicks yes, it would be another bag, created from the eagerly evaluated contents.

**Comment by jcrist** [comment]
This can now be done with the constructor plugins added in #2142:

```python
In [27]: x = np.arange(10)

In [28]: dx = da.from_array(x, chunks=5)

In [29]: def eager(x):
    ...:     with dask.set_options(array_plugins=()):
    ...:         return x.persist()
    ...:
    ...:

In [30]: with dask.set_options(array_plugins=[eager]):
    ...:     y = dx + 1
    ...:

In [31]: y.dask  # Computed eagerly, tasks are the results
Out[31]:
{('add-cc8c601b444ed2b5f209a913a9d126dc', 0): array([1, 2, 3, 4, 5]),
 ('add-cc8c601b444ed2b5f209a913a9d126dc', 1): array([ 6,  7,  8,  9, 10])}
```

Can this be closed?

**Comment by shoyer** [comment]
Yes, I think plugins handle this nicely
