### ISSUE TITLE
to_parquet documentation typo?

### ISSUE THREAD

**Issue by benepo** [dask/dask#2920]
http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_parquet lists the parameter order as

`dask.dataframe.to_parquet(df, path, engine='auto', compression='default', write_index=None, append=False, ignore_divisions=False, partition_on=None, storage_options=None, compute=True, **kwargs)`

but the example at the end of that section (and other guides I've found online) puts `df` as the second parameter:

```
df = dd.read_csv(...)  
to_parquet('/path/to/output/', df, compression='snappy')
```

Is the `dask.dataframe.DataFrame` parameter order important or do both work?

**Comment by mrocklin** [comment]
The API documentation is auto-generated from current code and so much more likely to be accurate.  I suspect that these switched places somewhat recently for consistency with other functions. 

Do you have any interest in submitting a small PR to resolve the error in the example?

**Comment by benepo** [comment]
I found the reference: https://github.com/dask/dask/blob/1f99105b429dbb0954de73b29db6f96281c28649/docs/source/changelog.rst#L56

```
Deprecate old argument ordering in dd.to_parquet to better match convention of putting the dataframe first
```

I'll work on a PR to clean up the example to reflect the new preferred ordering.

**Comment by jcrist** [comment]
I'd actually recommend not using the function directly, and just using the method `df.to_parquet(path, ...)` (which has always been the same). The docstring in that section would then be updated to:

```python
>>> df = dd.read_csv(...)  
>>> df.to_parquet('/path/to/output/', compression='snappy')  
```

**Comment by benepo** [comment]
Ah, just found that: http://dask.pydata.org/en/latest/dataframe-performance.html?highlight=to_parquet#store-data-in-apache-parquet-format

**Comment by jcrist** [comment]
If you still want to submit a pull request to fix that docstring, I'd be glad to merge it :).
