### ISSUE TITLE
Very slow construction of dask.delayed DAG involving metaclass usage

### ISSUE THREAD

**Issue by bluenote10** [dask/dask#2925]
This is probably an exotic/low priority issue, but maybe still worth documenting. The following example creates a DAG of chained `dask.delayed` expressions. What is surprising is that building the DAG becomes extremely slow when passing instances of the `Stringlike` class to a delayed function (< 0.1 sec with plain `str` instances versus ~7 minutes with `Stringlike` instances):

```python
from __future__ import print_function
from dask import delayed
import time

class StringlikeMeta(type):
    def __eq__(cls, other):
        return issubclass(other, str)

class Stringlike(unicode):
    __metaclass__ = StringlikeMeta
    def __new__(cls, name):
        ob = super(Stringlike, cls).__new__(cls, name)
        return ob

def f(partition, args):
    return None

def iterative_dag(partitions, iterations, use_stringlike=True):
    if use_stringlike:
        args = [Stringlike(str(i)) for i in range(500)]
    else:
        args = [str(i) for i in range(500)]

    for i in range(iterations):
        print("adding iteration: {}".format(i))
        partitions = [
            delayed(f)(partition, args=args)
            for partition in partitions
        ]
    return partitions

def run_test():
    n_partitions = 20
    partitions = [delayed(None) for _ in range(n_partitions)]
    for use_stringlike in [False, True]:
        t1 = time.time()
        partitions = iterative_dag(partitions, 3, use_stringlike)
        t2 = time.time()
        print("Using stringlike: {}   Time: {} ".format(use_stringlike, t2 - t1))

run_test()
```

I haven't had time to look into why it is happening exactly, but it looks like it is related to the meta-class.

**Comment by mrocklin** [comment]
This problem seems to disappear in Python 3.  Have you all considered switching over?  Many problems like this disappear.

My recommendation here would be to run your script under the cProfile module

    python -m cProfile -o prof.out myfile.py

and then look at the profile, perhaps with snakeviz

    pip install snakeviz
    snakeviz prof.out

**Comment by bluenote10** [comment]
Yes, switching to Python 3 is the goal -- still ;). I already did the profiling, and but with limited time I could only conclude that the `Delayed.__call__` call is doing something completely different. I have another work-around, so we may close the issue, I just wasn't sure if this is known/expected.

**Comment by mrocklin** [comment]
If you're able to reproduce this under Python 3 then I would care more.  If
it's only an issue in Python 2 then I'm less inclined to spend dev time on
it.
