### ISSUE TITLE
Dataframe.read_sql_table() fails when reading empty table

### ISSUE THREAD

**Issue by avlahop** [dask/dask#2928]
There is a problem when trying to use `read_sql_table` to get data from an empty sql table. 

The problem is in that when trying to get the max and min values of the index col (if no divisions were provided) sql query returns `None` values for both of them (see [here](https://github.com/dask/dask/blob/master/dask/dataframe/io/sql.py#L105) ) thus the following code [here](https://github.com/dask/dask/blob/master/dask/dataframe/io/sql.py#L123) that tries to create the divisions fails.

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-83-d14f44b5a2c5> in <module>()
----> 1 alerts = df.read_sql_table('alerts', db_url, index_col='id', npartitions=16)

/home/avlach/virtualenvs/dask/local/lib/python2.7/site-packages/dask/dataframe/io/sql.pyc in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, **kwargs)
    121             divisions[-1] = maxi
    122         else:
--> 123             divisions = np.linspace(mini, maxi, npartitions + 1).tolist()
    124 
    125     parts = []

/home/avlach/virtualenvs/dask/local/lib/python2.7/site-packages/numpy/core/function_base.pyc in linspace(start, stop, num, endpoint, retstep, dtype)
    106     # Convert float/complex array scalars to float, gh-3504
    107     # and make sure one can use variables that have an __array_interface__, gh-6634
--> 108     start = asanyarray(start) * 1.0
    109     stop  = asanyarray(stop)  * 1.0
    110 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```
Shouldn't read_sql_table() provide with a failsafe mechanism like returning empty dataframes when there is no data on the table?

**Comment by TomAugspurger** [comment]
Yep, that seams reasonable. It looks like we grab a concrete sample at https://github.com/dask/dask/blob/32ebaa5497b8b17b0189276f8bbcab0805859535/dask/dataframe/io/sql.py#L98, so if the length of that is 0, you can wrap it up with a `dd.from_pandas`.

The only thing to handle is the divisions / npartitions arguments from the user. I think if `npartitions` is given, just use that. If neither are given, just use `npartitions=1`. If divisions is given, maybe we error?

Mind seeing if that works and submitting a pull request?
