### ISSUE TITLE
dask dataframe groupby apply returns unexpected column order

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#2931]
Hi 

First - dask is awesome! ! ! 

I am using dask with python 2.7 and using groupby apply with meta for the columns 

Sometimes I get in return the columns in another order than the one I defined and i can't find a reason for it 

Here is an example 

```
import pandas
import dask.dataframe as dd

def makeStuff(x):
    import itertools
    import pandas
    vals = [x[col].values.tolist() for col in x.columns.values.tolist()]
    d = list(itertools.product(*vals))
    return pandas.DataFrame.from_records(d)


a = [(1,2,3,4,5,6,6),(5,6,7,8,3,3,3), (1,2,3,6,5,4,6)]
b = pandas.DataFrame.from_records(a,columns=[1,2,3,4,5,6,7])


ddf = dd.from_pandas(b, npartitions=1)
g = ddf.groupby(1).apply(lambda x: makeStuff(x), meta={"what":int, "yo":int, "are":int, "stuff":int, "this":int, "is":int, "cool":int})

print g.compute()
```

you would expect the columns to return in the same order as they are defined in the meta, or at least with the correct data inside with regard to that order but the order is shuffled and so does the data in the columns (one column's data is assigned to another column) 

The output of this code is 

 

>       are  cool  is  stuff  this  what  yo
> 1                                          
> 1 0      1     2   3      4     5     6   6
>   1      1     2   3      4     5     6   6
>   2      1     2   3      4     5     4   6
>   3      1     2   3      4     5     4   6
>   4      1     2   3      4     5     6   6
>   5      1     2   3      4     5     6   6
>   6      1     2   3      4     5     4   6
>   7      1     2   3      4     5     4   6
>   8      1     2   3      6     5     6   6
>   9      1     2   3      6     5     6   6
>   10     1     2   3      6     5     4   6
>   11     1     2   3      6     5     4   6
>   12     1     2   3      6     5     6   6
>   13     1     2   3      6     5     6   6
>   14     1     2   3      6     5     4   6
>   15     1     2   3      6     5     4   6
>   16     1     2   3      4     5     6   6
>   17     1     2   3      4     5     6   6
>   18     1     2   3      4     5     4   6
>   19     1     2   3      4     5     4   6
>   20     1     2   3      4     5     6   6
>   21     1     2   3      4     5     6   6
>   22     1     2   3      4     5     4   6
>   23     1     2   3      4     5     4   6
>   24     1     2   3      6     5     6   6
>   25     1     2   3      6     5     6   6
>   26     1     2   3      6     5     4   6
>   27     1     2   3      6     5     4   6
>   28     1     2   3      6     5     6   6
>   29     1     2   3      6     5     6   6
> ...    ...   ...  ..    ...   ...   ...  ..
>   99     1     2   3      4     5     4   6
>   100    1     2   3      4     5     6   6
>   101    1     2   3      4     5     6   6
>   102    1     2   3      4     5     4   6
>   103    1     2   3      4     5     4   6
>   104    1     2   3      6     5     6   6
>   105    1     2   3      6     5     6   6
>   106    1     2   3      6     5     4   6
>   107    1     2   3      6     5     4   6
>   108    1     2   3      6     5     6   6
>   109    1     2   3      6     5     6   6
>   110    1     2   3      6     5     4   6
>   111    1     2   3      6     5     4   6
>   112    1     2   3      4     5     6   6
>   113    1     2   3      4     5     6   6
>   114    1     2   3      4     5     4   6
>   115    1     2   3      4     5     4   6
>   116    1     2   3      4     5     6   6
>   117    1     2   3      4     5     6   6
>   118    1     2   3      4     5     4   6
>   119    1     2   3      4     5     4   6
>   120    1     2   3      6     5     6   6
>   121    1     2   3      6     5     6   6
>   122    1     2   3      6     5     4   6
>   123    1     2   3      6     5     4   6
>   124    1     2   3      6     5     6   6
>   125    1     2   3      6     5     6   6
>   126    1     2   3      6     5     4   6
>   127    1     2   3      6     5     4   6
> 5 0      5     6   7      8     3     3   3

**Comment by jcrist** [comment]
There are two issues with your code that are compounding to give this result:

- Your metadata has column names, but the result from your `makeStuff` function doesn't. Dask expects the given metadata to match for the applied function, and does some renaming if it doesn't (note, this shouldn't be relied on, it might go away soon). In your case the output of `makeStuff` has no column names, so dask applies the column names that were passed in via meta:

```python
In [15]: b
Out[15]:
   1  2  3  4  5  6  7
0  1  2  3  4  5  6  6
1  5  6  7  8  3  3  3
2  1  2  3  6  5  4  6

In [16]: makeStuff(b).head()  # no column names
Out[16]:
   0  1  2  3  4  5  6
0  1  2  3  4  5  6  6
1  1  2  3  4  5  6  3
2  1  2  3  4  5  6  6
3  1  2  3  4  5  3  6
4  1  2  3  4  5  3  3
```

- You're passing in a dictionary for metadata. In python, dictionaries have particular order when iterated over - the order is determined by the hashseed on startup. This is why your columns are getting assigned in a random order.

---

Passing in a list of tuples to `meta` fixes this problem. I also recommend naming your columns in `makeStuff`, but that's optional (for now):

```python
In [1]: %load test.py

In [2]: # %load test.py
   ...: import pandas as pd
   ...: import dask.dataframe as dd
   ...: from itertools import product
   ...:
   ...:
   ...: def makeStuff(x):
   ...:     vals = [x[col].values.tolist() for col in x.columns.values.tolist()]
   ...:     d = list(product(*vals))
   ...:     # Pass in columns
   ...:     return pd.DataFrame.from_records(d, columns=['what', 'yo', 'are', 'stuff', 'this', 'is', 'cool'])
   ...:
   ...:
   ...: a = [(1,2,3,4,5,6,6),(5,6,7,8,3,3,3), (1,2,3,6,5,4,6)]
   ...: b = pd.DataFrame.from_records(a,columns=[1,2,3,4,5,6,7])
   ...:
   ...:
   ...: # Ordered object for metadata
   ...: meta = [("what", int),
   ...:         ("yo", int),
   ...:         ("are", int),
   ...:         ("stuff", int),
   ...:         ("this", int),
   ...:         ("is", int),
   ...:         ("cool", int)]
   ...:
   ...:
   ...: ddf = dd.from_pandas(b, npartitions=1)
   ...:
   ...: g = ddf.groupby(1).apply(makeStuff, meta=meta)
   ...:

In [3]: g.compute().head()
Out[3]:
     what  yo  are  stuff  this  is  cool
1
1 0     1   2    3      4     5   6     6
  1     1   2    3      4     5   6     6
  2     1   2    3      4     5   4     6
  3     1   2    3      4     5   4     6
  4     1   2    3      4     5   6     6
```

**Comment by thebeancounter** [comment]
@jcrist  thanks for the help!
