### ISSUE TITLE
Merge b/w two dask data-frame giving MemoryError

### ISSUE THREAD

**Issue by SahilDahiya** [dask/dask#2934]
Data can be downloaded from here
https://www.kaggle.com/c/avito-context-ad-clicks/data

Reading the data using read_table

    import dask.dataframe as dd

    df_ss = dd.read_table("trainSearchStream.tsv",delimiter="\t").rename(columns=str.lower)
    df_ai = dd.read_table("AdsInfo.tsv",delimiter="\t",dtype=
    {'CategoryID':'category'}).rename(columns=str.lower)

merging the dataset

    df_train = (df_ss.merge(df_ai,on="adid",how="left")
           ).compute()

Available ram on my local machine: 15 GB

Datasets are 10 and 5 GB

My system crashes every time due to low on memory.

![image](https://user-images.githubusercontent.com/10377794/33393125-1bed1f6c-d50c-11e7-9a1f-105cf5219304.png)

I have tried stuff below but nothing works:
1. Converting the files to parquet and then doing the merge
2. Increasing the npartition manually
3. Creating index on "adid" on both datasets

Is it me doing something wrong or there is a bug in dask? Please let me know

Thanks in advance

**Comment by mrocklin** [comment]
Calling .compute creates a pandas dataframe, which in your case may be
larger than memory.

**Comment by SahilDahiya** [comment]
So is there a work around it or this is the limitation of dask

**Comment by mrocklin** [comment]
When you call .compute you are asking to convert your dask.dataframe into a pandas dataframe.  Your resulting pandas dataframe is probably larger than memory.  You're outside of Dask at this point.  I suspect that you didn't mean to actually call  `.compute()`.

**Comment by SahilDahiya** [comment]
You are right, now I am saving it as parquet file instead of using .compute. It works now. Thanks

**Comment by mrocklin** [comment]
Glad everything is working well for you.  Enjoy!
