### ISSUE TITLE
Writing and reading known categorical to parquet results in forgetting categories

### ISSUE THREAD

**Issue by michcio1234** [dask/dask#2944]
To reproduce:
- create dask dataframe with categorical column with known categories
- save it to parquet
- read it from parquet
- categories are unknown.

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame(data=list('abcaabbcc'), columns=['col'])
df.col = df.col.astype('category')
ddf = dd.from_pandas(df, npartitions=1)

ddf.to_parquet('tmp')
ddf2 = dd.read_parquet('tmp')
```

```
>>> ddf.col
Dask Series Structure:
npartitions=1
0    category[known]
8                ...
Name: col, dtype: category
Dask Name: getitem, 2 tasks

>>> ddf2.col
Dask Series Structure:
npartitions=1
0    category[unknown]
8                  ...
Name: col, dtype: category
Dask Name: getitem, 2 tasks
```

dask: 0.16.0
fastparquet: 0.1.3
pandas: 0.21.0

**Comment by TomAugspurger** [comment]
I believe that pandas has currently decided not to store the unique categories in the parquet metadata: http://pandas-docs.github.io/pandas-docs-travis/developer.html#storing-pandas-dataframe-objects-in-apache-parquet-format IIRC the fear was that that array could still be very large.

**Comment by martindurant** [comment]
Correct, the categories information should only be available upon accessing the actual data. The metadata is not particularly fast to decode by comparison, and in dask's case, gets replicated to every task, which would be slow. At least we can be sure that, if the data was written by dask/pandas, each chunk has the *same* categories, so you could get them from any one of the partitions.

**Comment by michcio1234** [comment]
Thank you guys for your responses. @martindurant, I am not sure what you mean in your last sentence. How can I get categories from a partition? What if one or more of categories don't appear in a certain partition (eg. `part0-> A A A B B B part1-> C C C` where category `C` doesn't appear in partition 0)?

**Comment by TomAugspurger** [comment]
Something like

```python
In [10]: dtype = ddf2.get_partition(0).categorize().col.dtype

In [11]: dtype
Out[11]: CategoricalDtype(categories=['a', 'b', 'c'], ordered=False)
```

Should work. Then you should be able to `ddf2.col.astype(dtype)`, though I think there may be a bug there. Looking now.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/issues/2947 for that last issue with `astype`.

I think something like

```python
In [13]: ddf.col.cat.set_categories(dtype.categories)
Out[13]:
Dask Series Structure:
npartitions=1
0    category[known]
8                ...
Name: col, dtype: category
Dask Name: cat, 3 tasks
```

will work in the meantime.

**Comment by michcio1234** [comment]
Thank you very much for your help!
The issue may be closed.

**Comment by martindurant** [comment]
Doesn't `.categorize()` **re**categorize? I think this is probably simpler

```
cats = ddf.col.head(1).cat.categories
```

and that should already be the same set as all partitions, so only need to update in `_meta`.

**Comment by michcio1234** [comment]
Both ways work well for the example I presented (didn't check category codes though).

**Comment by McToel** [comment]
Shouldn't this be mentioned in [documentation](https://docs.dask.org/en/latest/dataframe-categoricals.html) about categoricals? I had this issue come up while working with categoricals, and it took me some time to figure out how to fix it.

**Comment by jsignell** [comment]
If you have ideas about how to make this documentation clearer, @McToel we are always very happy to review documentation pull requests!
