### ISSUE TITLE
ENH: Support merging Dask DataFrames on a combination of columns and index levels

### ISSUE THREAD

**Issue by jmmease** [dask/dask#2950]
## Background
Pandas version 0.22.0 will have support for merging DataFrames on a combination of columns and index levels. This was accomplished by allowing the `on`, `left_on`, and `right_on` parameters to `df.merge` to accept index levels as well as column labels. 

- Feature discussion: pandas-dev/pandas#14355
- PR: pandas-dev/pandas#17484

## Proposal
I would like to update Dask DataFrame to support this feature as well (when used with pandas >= 0.22.0)

This will allow us to avoid shuffling when merging DataFrames (with known divisions) if the shared index level name is included in the `on` parameter list (by itself or with additional columns).

I'll have a PR up for discussion in a few days, but please share any comments or concerns in the meantime. @mrocklin @TomAugspurger 

Thanks!

**Comment by mrocklin** [comment]
This sounds great to me.  I'm also happy whenever anyone starts to get engaged in the deeper parts of dask.dataframe.  Please let me know if anything is unclear.
