### ISSUE TITLE
can't drop duplicated on dask dataframe index

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#2952]
please note my stackoverflow [question](https://stackoverflow.com/questions/47534099/dask-dataframe-drop-duplicate-index-values) 

I am using dask dataframe with python 2.7 and want to drop duplicated index values from my df. 

When using pandas i would use 

    df = df[~df.index.duplicated(keep = "first")]

And it works 

When trying to do the same with dask dataframe i get 

> AttributeError: 'Index' object has no attribute 'duplicated'

I could reset the index and than use the column that was the index to drop duplicated but I would like to avoid it if possible 

I could use df.compute() and than drop the duplicated index values but this df is too big for memory. 

I tried using the following code as suggested by jezrael in stackoverflow 
`rxTable[~rxTable.index.to_Series().duplicated()]`
and got 

> AttributeError: 'Index' object has no attribute 'to_Series'

It worked a few days ago and just stopped, i can't find any difference in the code and data. 

How can i drop the duplicated index values from my dataframe using dask dataframe?

Thanks

**Comment by TomAugspurger** [comment]
Reminder, it's helpful to have reproducible examples :)

This may be your best shot right now:

```python
import pandas as pd
import dask.dataframe as dd

a = pd.DataFrame({"A": [1, 2, 3, 4]},
                 index=[0, 0, 1, 1])
b = dd.from_pandas(a, 2)

a.groupby(a.index).first()

def chunk(x):
    return x.first()


def agg(x):
    return x.first()
```

A PR implementing `first` and `last` on groupby objects would be helpful if you have time.

**Comment by thebeancounter** [comment]
@TomAugspurger  Thanks!

**Comment by thebeancounter** [comment]
@TomAugspurger  BTW - by pr your mean pull request? please clarify what is the need and I will try to do it

**Comment by TomAugspurger** [comment]
Yes, PR = pull request, sorry.

We have some development guidelines at
http://dask.pydata.org/en/latest/develop.html#development-environment

Post here if you have any difficulties.

**Comment by thebeancounter** [comment]
@TomAugspurger  will try my best!

**Comment by 3ggaurav** [comment]
Hey Tom, We are familiar with attributes - subset, keep, and inplace, which are used in pandas.dataframe.drop_duplicates function. Please tell us about the attributes given in dask.dataframe.drop_duplicates function i.e. **split_every, split_out**. 

There is no explanation of these attributes in dask documentation also. What are these?
<img width="720" alt="Screen Shot 2019-06-20 at 6 34 53 PM" src="https://user-images.githubusercontent.com/19906193/59851431-3fffa800-938a-11e9-82fb-157ee7225821.png">

Kindly help us. Thanks.

**Comment by TomAugspurger** [comment]
I'm not sure, perhaps the number of output partitions. If you investigate
it and can clarify the documentation, we would happily take a pull request.

**Comment by Demirrr** [comment]
> Reminder, it's helpful to have reproducible examples :)
> 
> This may be your best shot right now:
> 
> ```python
> import pandas as pd
> import dask.dataframe as dd
> 
> a = pd.DataFrame({"A": [1, 2, 3, 4]},
>                  index=[0, 0, 1, 1])
> b = dd.from_pandas(a, 2)
> 
> a.groupby(a.index).first()
> 
> def chunk(x):
>     return x.first()
> 
> 
> def agg(x):
>     return x.first()
> ```
> 
> A PR implementing `first` and `last` on groupby objects would be helpful if you have time.

I am also interested in dropping the duplicate indexes. However, I fail to understand how this chunk of code aims to solve the aforementioned problem ?

**Comment by jsignell** [comment]
@3ggaurav you can read about `split_every` and `split_out` [here](https://github.com/dask/dask/blob/ab99d961b4e2bdc67d947400aa21be02314feeb6/dask/dataframe/core.py#L4885:L4891):

```
    split_every : int, optional
        Group partitions into groups of this size while performing a
        tree-reduction. If set to False, no tree-reduction will be used,
        and all intermediates will be concatenated and passed to ``aggregate``.
        Default is 8.
    split_out : int, optional
        Number of output partitions. Split occurs after first chunk reduction.
```

@Demirrr this is a very old issue. I think you'd be better off setting your index as a column and sing `drop_duplicates`:

```python
import pandas as pd
import dask.dataframe as dd

a = pd.DataFrame({"A": [1, 2, 2, 3, 2, 2]},
                 index=[0, 0, 1, 1, 2, 2])
b = dd.from_pandas(a, 2)
out = b.reset_index().drop_duplicates(["index"]).set_index("index")
out.compute()
```

I am closing this. But if you are still having issues, please reopen.
