### ISSUE TITLE
Better Dask Array support of `frompyfunc`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2956]
NumPy's [`frompyfunc`]( https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.frompyfunc.html ) is quite useful for wrapping up a basic Python function as a `ufunc`. It also works pretty much out of the box with Dask Arrays thanks to [`__array_ufunc__`]( https://docs.scipy.org/doc/numpy-1.13.0/user/basics.subclassing.html#array-ufunc-for-ufuncs ).

However there are two caveats. First one must have NumPy 1.13 at least for `__array_ufunc__` to work (we support 1.10+ currently). Second it appears that `frompyfunc` objects cannot be pickled. ( https://github.com/numpy/numpy/issues/8099 ) The latter hurts any distributed computing use cases where the `frompyfunc` object must be shipped between processes.

One way to fix both of these would be to create some sort of wrapper object derived from [Dask Array's `ufunc`]( https://github.com/dask/dask/blob/9e9fa10ef11bfe86a52214d8a2cda19508a4ee37/dask/array/ufunc.py#L45 ) that delays creating of the `frompyfunc` object until the computation is performed. This should allow the `frompyfunc` object to interact more reliably with Dask Arrays on older NumPy versions. Further it would allow the object to pickled more easily (assuming the Python function used can be pickled).

**Comment by mrocklin** [comment]
In general I'm not opposed to continuing to wrap numpy ufuncs.  Presumably
as long as the function itself was serializable this would work fine in a
distributed context.

**Comment by jakirkham** [comment]
It seems like a lot of user questions end up going along the lines of "I can do this special thing with NumPy how do I take it to larger data with Dask?" Hence there is a lot of value in having operations in Dask that generally wrap up things of this sort (e.g. `map_blocks`, `atop`, `apply_along_axis`, etc.). My thinking with raising `frompyfunc` in particular is it handles another class of operations like this. Namely wrapping up user provided Python functions that are intended to act in an element-wise fashion.

**Comment by jcrist** [comment]
Fixed by #3030.
