### ISSUE TITLE
Understanding read_csv ?

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#2957]
I am using a globstring *.csv, however when I check df.npartition the count includes all files in folder, including non .csv files. I must be doing something wrong?

**Comment by martindurant** [comment]
This is not our experience:

```
> %cat temp.csv
,a,b
0,1,2
2,3,4
> df = dd.read_csv('temp*.csv')  # two identical files match
> df.compute()
Out[5]:
   Unnamed: 0  a  b
0           0  1  2
1           2  3  4
0           0  1  2
1           2  3  4
> df.npartitions
2
```

There are indeed other files in the directory.

**Comment by mrocklin** [comment]
Note that the number of partitions may be larger than the number of CSV
files if those CSV files are large.  Dask may cut up a single CSV file into
many partitions.

**Comment by apiszcz** [comment]
Thank you, that 'must' be it.  Simple test with small .csv files yield 1 to 1 match for npartitions.
