### ISSUE TITLE
dask.from_blaze('blaze://...')

### ISSUE THREAD

**Issue by cowlicks** [dask/dask#296]
I think we will need a way to create a dask collection from a blaze server URI.

I'm not sure how exactly this will work but it seems to be the direction continuum wants to go.

**Comment by mrocklin** [comment]
I'm also not sure how this would work.

**Comment by cowlicks** [comment]
Maybe @chdoig, @teoliphant, or @pzwang  can comment.

My probably wrong summary: 
Blaze server will become an important source for data in the future. The same way we have `dask.bag.from_s3`, `dask.bag.from_url`, etc. We should have a way to make a bag from a blaze server.

**Comment by pzwang** [comment]
@mrocklin What things are unclear about this?  How dask would partition the dataset, or...?

**Comment by mrocklin** [comment]
Yes, that would be a good question.  

Generally I've gotten the general impression that  "it would be nice for dask to drive blaze server or perhaps many blaze servers" but I don't have a good lower-level example on how this would work or be useful.  Do we have a practical problem that someone cares about that can motivate this work?

**Comment by mrocklin** [comment]
Or perhaps a code example on how this would work and how it would differ from using Blaze to interact with a Blaze server or using dask to interact with dask.distributed.

**Comment by chdoig** [comment]
I'm not sure how this would work either. If we want Blaze to be the common user-facing API, then maybe what we need is not a Blaze connection in dask, but a dask connection in Blaze.

https://github.com/ContinuumIO/blaze/issues/1142

**Comment by mrocklin** [comment]
Agreed with @chdoig , this is a blaze, not a dask issue.  Closing.
