### ISSUE TITLE
Corner cases for topk of array

### ISSUE THREAD

**Issue by rzu512** [dask/dask#2965]
Kind of silly, but I run into this when I try to define topk(k, x, axis=None).
Test:
```python
import numpy as np
import dask.array as da
x = da.from_array(np.array([0]), chunks=1)
da.topk(x, 0)
```
Result:
```python
Traceback (most recent call last):
  File "test_topk2.py", line 4, in <module>
    da.topk(x, 0)
  File "<python dir>/site-packages/dask/array/routines.py", line 790, in topk
    if x.ndim != 1:
```

Tests:
```python
import numpy as np
import dask.array as da
cases = [(0, 0, 0), (0, 1, 0), (0, 1, 1), ([0], 1, 0), ([0], 1, 1)]

for a, b, c in cases:
    x = da.from_array(np.array(a), chunks=b)
    try:
        da.topk(x, c)
    except Exception as err:
        print("[ case: (%s, %s, %s) ]" % (a, b, c))
        print('fail', err)
```
Result:
```
[ case: (0, 0, 0) ]
fail 'int' object has no attribute 'ndim'
[ case: (0, 1, 0) ]
fail 'int' object has no attribute 'ndim'
[ case: (0, 1, 1) ]
fail 'int' object has no attribute 'ndim'
[ case: ([0], 1, 0) ]
fail 'int' object has no attribute 'ndim'
[ case: ([0], 1, 1) ]
fail 'int' object has no attribute 'ndim'
```

**Comment by mrocklin** [comment]
It looks like your argument order is reversed.

**Comment by rzu512** [comment]
My bad. sorry about that.

**Comment by mrocklin** [comment]
The function signature is confusing and against convention.  We might
consider deprecating this function and point people instead towards the
topk method.  Thoughts or alternatives @jakirkham ?

**Comment by rzu512** [comment]
Wait. Do you mean deprecating topk for array? or something else?

**Comment by jakirkham** [comment]
No strong thoughts.

That said, sounds like you have made a reasonable argument for deprecation. Would be ok with that. Appears the docstring for the function already encourages using the method. :)

Just for the purpose of discussion, one alternative might be adding a `FutureWarning` and then flipping the argument order down the road. However that seems more painful than deprecating, removing, and reintroducing with corrected argument order later. Mainly as the `FutureWarning` route would likely compound the existing argument confusion.
