### ISSUE TITLE
Dask.distributed setup documentation

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2966]
I'm considering a rewrite of the dask.distributed cluster setup documentation.  I'm also considering moving that documentation to the main Dask page for visibility (I'd like to slowly move the less detail-oriented documentation over to the main site).  

Any concerns or thoughts?

**Comment by jcrist** [comment]
I believe this was fixed in #3014. Ok to close?

**Comment by mrocklin** [comment]
Thanks for the reminder
