### ISSUE TITLE
Tags for Docker images and Helm charts

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2972]
I'm starting to make Docker images and Helm charts (actually I'm extending @danielfrg's work) and I'll soon have to make tags for those other than `latest`.  

How should we tag these?  

Also are there any standards or conventions that we should apply to the images or helm charts? 

cc @jakirkham

**Comment by mrocklin** [comment]
Also, we're currently hosting a Helm repository at https://dask.github.io/helm-chart .  I chose the helm-chart name by copying JupyterHub.  This might not be the appropriate name though.  `helm-charts` ?  `charts`?

**Comment by mrocklin** [comment]
The `dask` name is taken on DockerHub.  Do we know any ways to obtain names that are already taken but inactive?  https://github.com/docker/hub-feedback/issues/1124

**Comment by ogrisel** [comment]
I think the version number of the main project, that is dask. Possibly with an additional docker image / helm chart release number appended at the end.

I am not familiar with the best practices of the kubernetes community.

**Comment by jcrist** [comment]
> The dask name is taken on DockerHub.

FYI, I created a `daskdev` account on dockerhub a while ago (for @danielfrg's work). Happy to give others permission: (https://hub.docker.com/u/daskdev/).

**Comment by jakirkham** [comment]
We versioned them by git commit in docker-stacks. Its a bit granular, but this way you know what you are getting.

ref: https://github.com/jupyter/docker-stacks/wiki/Docker-build-history

**Comment by mrocklin** [comment]
Going with @ogrisel 's suggestion: I think the version number of the main project, that is dask.
