### ISSUE TITLE
read_sql_table gives AttributeError when reading a database

### ISSUE THREAD

**Issue by gsavaia** [dask/dask#2975]
When I try to read from a sql database:
`df_database = create_engine('sqlite:///' + database_path)`
`df = dd.read_sql_table('table', df_database, 'id_driver')`

I get this error: `AttributeError: 'Engine' object has no attribute '_instantiate_plugins'`

If I use the pandas `read_sql_query` function on the same db, it works just fine.

Here's a full trace:
> AttributeError Traceback (most recent call last)
> ipython-input-10-2da58b7e1773 in <module>()
>       3 t0 = time.time()
> ----> 4 df = dd.read_sql_table('table', df_database, 'id_driver')
>       5 t1 = time.time()
>       6 
> 
> ~/lib/python3.6/site-packages/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, **kwargs)
>      66     if index_col is None:
>      67         raise ValueError("Must specify index column to partition on")
> ---> 68     engine = sa.create_engine(uri)
>      69     meta = sa.MetaData()
>      70     if isinstance(table, six.string_types):
> 
> ~/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py in create_engine(*args, **kwargs)
>     389     strategy = kwargs.pop('strategy', default_strategy)
>     390     strategy = strategies.strategies[strategy]
> --> 391     return strategy.create(*args, **kwargs)
>     392 
>     393 
> 
> ~/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py in create(self, name_or_url, **kwargs)
>      50         u = url.make_url(name_or_url)
>      51 
> ---> 52         plugins = u._instantiate_plugins(kwargs)
>      53 
>      54         u.query.pop('plugin', None)
> 
> AttributeError: 'Engine' object has no attribute '_instantiate_plugins'

**Comment by TomAugspurger** [comment]
reprex: 

```python
In [3]: import dask.dataframe as dd
imp
In [4]: import pandas as pd

In [5]: from sqlalchemy import create_engine

In [6]: engine = create_engine("sqlite:///tmp.db")

In [7]: df = pd.DataFrame({"A": [1] * 100})

In [8]: df.index.name = 'idx'

In [9]: df.to_sql("table", engine, index=True)

In [10]: r = dd.read_sql_table("table", engine, "idx")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-63977ffca8c7> in <module>()
----> 1 r = dd.read_sql_table("table", engine, "idx")

~/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, **kwargs)
     66     if index_col is None:
     67         raise ValueError("Must specify index column to partition on")
---> 68     engine = sa.create_engine(uri)
     69     meta = sa.MetaData()
     70     if isinstance(table, six.string_types):

~/Envs/dask-dev/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py in create_engine(*args, **kwargs)
    389     strategy = kwargs.pop('strategy', default_strategy)
    390     strategy = strategies.strategies[strategy]
--> 391     return strategy.create(*args, **kwargs)
    392
    393

~/Envs/dask-dev/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py in create(self, name_or_url, **kwargs)
     50         u = url.make_url(name_or_url)
     51
---> 52         plugins = u._instantiate_plugins(kwargs)
     53
     54         u.query.pop('plugin', None)

AttributeError: 'Engine' object has no attribute '_instantiate_plugins'

```

**Comment by martindurant** [comment]
The second argument to `read_sql_table` should not be an engine, but a URI from which an engine can be made.

**Comment by TomAugspurger** [comment]
Ah, thanks @martindurant. I suppose it would be nice to allow `uri` to be an engine, in case the user has some special configuration on it. Though perhaps I'm missing a good reason to require a string.

@gsavaia could you submit a PR allowing `uri` to be an existing `Engine`, along with some tests and docs?

**Comment by mrocklin** [comment]
I would not be surprised if it was difficult to serialize an engine with
active database connections.

**Comment by TomAugspurger** [comment]
That's an excellent reason :) We could perhaps extract `engine.url` then.

**Comment by ChrisMcPherson** [comment]
Running into the same issue and was hoping for some guidance.
Understanding that read_sql_table expects a URI, how could one supply a configuration such as:
connect_args={'sslmode': 'prefer'})

I am unfortunately unable to connect to Redshift without supplying this configuration.

Thanks!

**Comment by TomAugspurger** [comment]
@ChrisMcPherson your suggestion to use `connect_args` seems good. They could be passed through to https://github.com/dask/dask/blob/d80957501680522291de0653f3d9e2eda010295e/dask/dataframe/io/sql.py#L68.

**Comment by ChrisMcPherson** [comment]
@TomAugspurger Thanks for pointing me in the right place, Tom! I'll take a stab at adding the connect_args pass-through feature.

**Comment by mrocklin** [comment]
@TomAugspurger was this resolved?

**Comment by TomAugspurger** [comment]
I don't believe so.

IIUC, this would be fixed by adding a `conncect_args=None` parameter to `DataFrame.to_sql` and `read_sql` that's a dict of args passed through to `create_engine`'s `conncect_args`.

I notice that `create_enginge` takes a lot of keyword arguments, not just `connect_args`. We may want to have a more general `engine_kwargs` that is passed through to `create_engine` as `**kwargs`. Then it would be something like

```python
dd.read_sql_table(..., engine_kwargs={'connect_kwargs': {'sslmode': 'prefer'}, ...})
```

**Comment by garaud** [comment]
In the pandas API for `read/to_sql`, you pass an instance of SQLAlchemy engine. What do you think if you do:

```python
dd.read_sql_table(query, eng, ...)
```

instead of `uri` or a dict?

**Comment by TomAugspurger** [comment]
IIRC, sqlalchemy engines tend to not pickle well.

**Comment by garaud** [comment]
OK. I didn't know. Thanks. I'll try to push something soon about this "good first" issue.
