### ISSUE TITLE
Modify `dask.array.meshgrid` to not producing rechunking operations

### ISSUE THREAD

**Issue by magonser** [dask/dask#2981]
Once PR #2943 is implemented, `dask.array.meshgrid` should be modified to omit rechunking operations in the DAG. 

My use-cases suggest, that the current implementation of `meshgrid` (yielding rechunking operations in the DAG) has inferior performance when using `distributed` or when having problem sizes larger than memory. 
Thank you again for your efforts.

**Comment by jakirkham** [comment]
As noted in the aforementioned PR, a new PR for this behavior would be welcome.

**Comment by jakirkham** [comment]
Closing now that PR ( https://github.com/dask/dask/pull/3001 ) has been merged.
