### ISSUE TITLE
DataFrame.set_index(..., compute=False) triggers computation

### ISSUE THREAD

**Issue by Juanlu001** [dask/dask#2982]
According to the documentation of `DataFrame.set_index`, `compute` controls "Whether or not to trigger an immediate computation" and "Defaults to False". However, `if divisions is None`, `dask.compute` is called:

https://github.com/dask/dask/blob/0.16.0/dask/dataframe/shuffle.py#L64

As expected, if sorted divisions are provided no computation is triggered.

Depending on the complexity of the derived dataframe at hand, this sole computation of the divisions can be quite expensive and block the interpreter for a while. I acknowledge that avoiding this might be difficult, so perhaps this bit should be clarified in the documentation?

**Comment by mrocklin** [comment]
Sorry for the lack of response.  Yes, a documentation fix might be appropriate here.  Any interest?

**Comment by natalya-patrikeeva** [comment]
I'm going to fix the documentation for this.

**Comment by jrbourbeau** [comment]
Great, thanks @natalya-patrikeeva!
