### ISSUE TITLE
memory blowing up when using set_index, groupby

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#2983]
I am using python 2.7 with dask dataframe 
this is a big dataframe on a local machine (200M rows) 

I use 
```
df = dd.read_hdf(file, "/key*").set_index("k") 
groups = df.groupby("k") 
indecies = df["k"].unique().compute().values.tolist() 
groupList = [groups.get_group(index) for index in indecies] 
for group in groupList:
    print group.head()
```

And the memory blows up (32 ram & 16 swap) 

I think this shouldn't use too much memory given that all the shuffles are on disk, what am i missing here?

**Comment by thebeancounter** [comment]
Does using 

`df.map_partitions(lambda x:x.set_index("k")).persist()`

Make any sense?

**Comment by thebeancounter** [comment]
When I used repartition to around 3000 partitions for 200m*3 shape df the memory does not blow up

**Comment by thebeancounter** [comment]
@TomAugspurger  Ideas?

**Comment by TomAugspurger** [comment]
Not immediatly. If you're able to make a reproducible example using random
data I may be able to look more closely (though not till later in the week).

**Comment by thebeancounter** [comment]
OK thanks! will wait,
I guess the main question here is does set index need to get all the values
into memory at some stage, this is my assumption here, can't find it in the
source code.

**Comment by thebeancounter** [comment]
@TomAugspurger when i try to create random data this does not happen. 

When i read data from hdf ~ 200m rows -> 1m/chunk 
and setting index 
I get a high memory consumption of ~20G

**Comment by thebeancounter** [comment]
udpate 

when using 
`dask.set_options(get = dask.get)`
This does not happen 

I assume that the issue is dask duplicating information when using multiprocessing 

I tried to limit the process count with 
```

from multiprocessing.pool import ThreadPool
dask.set_options(pool = ThreadPool(1))
```

But this had no affect 

What is the proper way of limiting the number of process on a local machine?

**Comment by thebeancounter** [comment]
possible work around 

```
import dask.dataframe as dd
import os

        if os.path.exists(outputFile):
            os.remove(outputFile)

        ddf = dd.read_hdf(file, key, chunksize=10000000)
        partitions = [ddf.get_partition(i) for i in range(ddf.npartitions)]
        for i,par in enumerate(partitions):
            p = dd.from_pandas(par.compute().set_index(index),1)
            p.to_hdf(outputFile, outputKey, append = True, format = "table")
            

        ddf = dd.read_hdf(outputFile, outputKey)
        return ddf
```

**Comment by mrocklin** [comment]
I recommend providing a minimal example so that others can easily replicate the situation.  I recommend using `dask.datasets.timeseries()`

@thebeancounter if you have time to do this that would probably help to accelerate finding a solution to this problem.

**Comment by TomAugspurger** [comment]
@thebeancounter were you able to create a minimal example?

**Comment by jrbourbeau** [comment]
I'm going to close this issue for the time being. @thebeancounter please feel free to re-open if you're able to provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by klieret** [comment]
Let me link https://github.com/dask/dask/issues/7259 for anyone getting here from google. TL;DR: Use `dask > 2021.03.0`
