### ISSUE TITLE
Number of blocks mismatch for 1st dimension

### ISSUE THREAD

**Issue by estebanag** [dask/dask#2984]
I'm trying to pass three arguments, each of which is equally chunked in the first dimension:
```python
import dask.array as da

dx = da.ones((5, 23), chunks=(2, 23))
dy = da.ones((5, 23), chunks=(2, 23))
dz = da.ones(5, chunks=(2,))
dr = da.map_blocks(lambda x, y, z: x + y, dx, dy, dz, dtype='f8', chunks=((2, 2, 1), (23,)))
```
This fails with `ValueError: Dimension 1 has 3 blocks, chunks specified with 1 blocks`.

However, if dimensions are swapped, no errors arise:
```python
dx = da.ones((23, 5), chunks=(23, 2))
dy = da.ones((23, 5), chunks=(23, 2))
dz = da.ones(5, chunks=(2,))
dr = da.map_blocks(lambda x, y, z: x + y, dx, dy, dz, dtype='f8', chunks=((32,), (2, 2, 1)))
```
Is this expected/desired behavior?

My workaround (to avoid swapping dimensions) is to add a dummy dimension:
```python
dx = da.ones((5, 23), chunks=(2, 23))
dy = da.ones((5, 23), chunks=(2, 23))
dz = da.ones((5, 1), chunks=(2, 1))
dr = da.map_blocks(lambda x, y, z: x + y, dx, dy, dz, dtype='f8', chunks=((2, 2, 1), (23,)))
```

**Comment by mrocklin** [comment]
I believe that this follows normal NumPy broadcasting rules.  Your solution of adding a singleton dimension seems to make sense to me.  You could also use `dz[:, None]` to do this with NumPy syntax.  If you want to get fancy you might also consider using the slightly more advanced [atop](http://dask.pydata.org/en/latest/array-api.html#dask.array.core.atop) function.

**Comment by estebanag** [comment]
Thanks for the clarification and tip Matthew.
