### ISSUE TITLE
Visualization of more than 100% CPU usage

### ISSUE THREAD

**Issue by drorata** [dask/dask#2990]
When running a length processing on 4 nodes I get the following visualization (http://my.ip.comes.here:8787/workers):

![screen shot 2017-12-12 at 11 29 32](https://user-images.githubusercontent.com/2905978/33879928-3e1fa13a-df30-11e7-809e-f81a40f8a57f.png)

You can see that only one worker appears on the CPU usage scale. The others are experiencing more than 100% usage (maybe due to the multiple cores?) Here are the versions of the modules I use:

```
dask==0.16.0
distributed==1.20.2
dask-searchcv==0.2.0
pandas==0.21.0
scikit-learn==0.19.1
numpy==1.13.3
bokeh==0.12.13
```

**Comment by mrocklin** [comment]
Thanks for the bug report.  See https://github.com/dask/distributed/pull/1624

**Comment by drorata** [comment]
@mrocklin If I understand correctly, in the screenshot I posted each worker uses ~1 core out of 8? In other words, 100% means that one core is at 100%. If the whole VM is working with 8 cores that should be 800%?

**Comment by mrocklin** [comment]
Right, we use `psutil.Process.cpu_percent` to measure CPU activity

```python
Signature: proc.cpu_percent(interval=None)
Docstring:
Return a float representing the current process CPU
utilization as a percentage.

When interval is 0.0 or None (default) compares process times
to system CPU times elapsed since last call, returning
immediately (non-blocking). That means that the first time
this is called it will return a meaningful 0.0 value.

When interval is > 0.0 compares process times to system CPU
times elapsed before and after the interval (blocking).

In this case is recommended for accuracy that this function
be called with at least 0.1 seconds between calls.

A value > 100.0 can be returned in case of processes running
multiple threads on different CPU cores.

The returned value is explicitly *not* split evenly between
all available logical CPUs. This means that a busy loop process
running on a system with 2 logical CPUs will be reported as
having 100% CPU utilization instead of 50%.

Examples:

  >>> import psutil
  >>> p = psutil.Process(os.getpid())
  >>> # blocking
  >>> p.cpu_percent(interval=1)
  2.0
  >>> # non-blocking (percentage since last call)
  >>> p.cpu_percent(interval=None)
  2.9
  >>>
```

In the PR linked to above we now divide that number by the number of cores/threads in the worker before plotting on the 1-d scatter plot.

**Comment by drorata** [comment]
I am still not sure. The screenshot was taken during a `dask-searchcv`. I was expecting that all cores will take part in the process, but given what you say, it seems like it is not the case. Am I missing something?

**Comment by mrocklin** [comment]
It could be that the computations you're running don't perfectly release the GIL?  You might want to experiment by changing the mixture of threads/processes by increasing the number of dask-worker proceses and decreasing the number of threads per process.

**Comment by drorata** [comment]
Do @mrocklin mean experimenting with `nthreads ` and/or `nprocs ` of [`dask-worker`](http://distributed.readthedocs.io/en/latest/worker.html#command-line-tool) CLI?

**Comment by mrocklin** [comment]
Yes, that would work

**Comment by sandesh04** [comment]
How can i define nthreads and nprocs with dask-gateway on kubernetes? can anyone link me to documentation related to this?
