### ISSUE TITLE
Option for progress bar to show key of the task being computed?

### ISSUE THREAD

**Issue by neuronist** [dask/dask#2992]
I have a big number of different tasks to be computed on sequence and the progress bar is something I find very useful to understand which computations are taking longer. I ended up with something like this with the default ProgressBar.

[########################################] | 100% Completed | 11.6s
[########################################] | 100% Completed |  1min 12.3s
[########################################] | 100% Completed |  1min 14.0s
[########################################] | 100% Completed | 12min  3.9s

I went ahead and did a little investigation and changing this to show what function is being computed is very easy. Would this be something worth the change? Or at least a verbose mode for the progress bar that when active it prints the key of the task being computed like this.

[########################################] | 100% Completed | 11.3s | value-counts-agg-3ecd9a335d595837f6bb653ef005f2d72d7
[########################################] | 100% Completed |  1min 12.2s | value-counts-agg-c2cfebe3d3ba4776eb9c8910c90f086e
[########################################] | 100% Completed |  0.2s | series-mean-a2a6ae68d6e3d693d3132bc6de064b6b-8213d5823a468a54ff91f8feb3d299c2

To achieve this I simply added to this [script](https://github.com/dask/dask/blob/master/dask/diagnostics/progress.py) the following:

- `self._key = None` on `_start` function
- `self._key = key[0]` on `_pretask` function (might drop the [0] here)
-  changed line 130 to ` msg = '\r[{0:<{1}}] | {2}% Completed | {3} | {4}'.format(bar, self._width, percent, elapsed, self._key)` on `_draw_bar` function

**Comment by mrocklin** [comment]
The dask.distributed dashboard is also handy for cases like this: http://distributed.readthedocs.io/en/latest/web.html

**Comment by neuronist** [comment]
Yes, I normally use the dashboard when working with dask.distributed but I wanted to compare the speeds of the other schedulers. Well, it is solved now. Thanks for the help

**Comment by jcrist** [comment]
> Would this be something worth the change? Or at least a verbose mode for the progress bar that when active it prints the key of the task being computed like this.

Since the local progress bar only includes a single bar (can only rewrite one line of terminal output easily using standard output characters) we can only display a single task name. This is a bit misleading, as multiple different tasks may be computing in parallel at the same time. The web progressbar shown above don't have this limitation and can thus make use of task name information.

Since the web progressbar already solves this problem, and adding it to the terminal progressbar is non-trivial, I'm going to close this.
