### ISSUE TITLE
Indexing a dask array with a decreasing slice results in negative dimension size

### ISSUE THREAD

**Issue by shoyer** [dask/dask#2994]
On dask 0.16:
```
In [39]: import dask.array as da

In [40]: x = da.ones(10, chunks=-1)

# notice the negative shape!
In [41]: x[6:3]
Out[41]: dask.array<getitem, shape=(-3,), dtype=float64, chunksize=(-3,)>

# at least it gets computed correctly.
In [42]: x[6:3].compute()
Out[42: array([], dtype=float64)
```

This manifested itself in an issue for xarray: https://github.com/pydata/xarray/issues/1778

**Comment by jakirkham** [comment]
That's clearly wrong. Do you know if this has always been the case or if it was this some kind of regression?

**Comment by shoyer** [comment]
Not sure. It could have been here for a while -- decreasing slices are pretty rare, they aren't actually useful for anything.

**Comment by DirkEilander** [comment]
I ran into the same error as pydata/xarray#1778 but using slice(None, None, -1) to revert an axis. There is no error when i run it in dask version 0.15.0,
