### ISSUE TITLE
ddf.index.name is set to None after assign

### ISSUE THREAD

**Issue by kayibal** [dask/dask#3003]
If meta's index name is not explicitly set dask sets the index name to None. Wouldn't it be preferable to use the available index name of `ddf`?

```
In [1]: import pandas as pd
   ...: import dask.dataframe as dd
   ...: import numpy as np
   ...:

In [2]: df = pd.DataFrame({
   ...:     'a': np.arange(20)**2,
   ...:     'ts': pd.date_range('01-01-2000', periods=20).map(str)
   ...: }, index=pd.Index(np.arange(20), name='id')
   ...:     )
   ...:

In [3]: ddf = dd.from_pandas(df, npartitions=4)

In [4]: ddf.index.name
Out[4]: 'id'

In [5]: ddf2 = ddf.assign(ts_parsed=ddf.ts.map_partitions(pd.to_datetime, meta='datetime64[ns]'))

In [6]: print(ddf2.index.name)
Out[6]:  None

.....

In [8]: meta = pd.Series([], dtype='datetime64[ns]')
   ...: meta.index.name = 'id'

In [9]: ddf2 = ddf.assign(ts_parsed=ddf.ts.map_partitions(pd.to_datetime, meta=meta))

In [10]: print(ddf2.index.name)
id
```

**Comment by TomAugspurger** [comment]
> Wouldn't it be preferable to use the available index name of ddf?

Yes, that'd be good to do I think. We could maybe make `dask.dataframe.util.make_meta` accept an `index_name` argument (default is None). Then anywhere we call it we would pass `self.index.name`, where `self` is the original...

@kayibal do you have any interest in working on this?

**Comment by jcrist** [comment]
> Then anywhere we call it we would pass self.index.name, where self is the original...

Hmmmm, I'm not sure that's the best idea. We generally assume if the user passes in `meta` that it's 100% correct. This includes index type and name. We can't automatically set the index name to the current index name, because sometimes user defined functions change the index/index name.

**Comment by TomAugspurger** [comment]
I should say we’d only pass through the current index name when the user defined meta doesn’t include the index (a tuple of series name, dtype or a dict of columns to dtypes)

**Comment by jcrist** [comment]
Would you also copy the index type in that case? Something like `"If a non-pandas object is passed in, the output index is assumed to have the same type and name as the original frame"`. If so, just passing in `index=self.index` to `make_meta` should already work.

**Comment by kayibal** [comment]
@TomAugspurger Sure, I would gladly work on this once a consensus on the desired behaviour is reached.

**Comment by alexrudy** [comment]
I want to poke at this issue. It causes dd.to_datetime and friends to behave oddly as well, since they use (dask) supplied meta. I'd happily take a crack at a PR, which would pass along index info when a non-pandas object is passed in, as suggested by @jcrist.

**Comment by mrocklin** [comment]
Please do!

**Comment by jorloplaz** [comment]
This doesn't seem to be an issue anymore:

```python
>>> df
      a                   ts
id                          
0     0  2000-01-01 00:00:00
1     1  2000-01-02 00:00:00
2     4  2000-01-03 00:00:00
3     9  2000-01-04 00:00:00
4    16  2000-01-05 00:00:00
5    25  2000-01-06 00:00:00
6    36  2000-01-07 00:00:00
7    49  2000-01-08 00:00:00
8    64  2000-01-09 00:00:00
9    81  2000-01-10 00:00:00
10  100  2000-01-11 00:00:00
11  121  2000-01-12 00:00:00
12  144  2000-01-13 00:00:00
13  169  2000-01-14 00:00:00
14  196  2000-01-15 00:00:00
15  225  2000-01-16 00:00:00
16  256  2000-01-17 00:00:00
17  289  2000-01-18 00:00:00
18  324  2000-01-19 00:00:00
19  361  2000-01-20 00:00:00
>>> ddf = dd.from_pandas(df, npartitions=4)
>>> ddf.index.name
'id'
>>> ddf2 = ddf.assign(ts_parsed=ddf.ts.map_partitions(pd.to_datetime, meta='datetime64[ns]'))
>>> print(ddf2.index.name)
id
>>> meta = pd.Series([], dtype='datetime64[ns]')
>>> ddf2 = ddf.assign(ts_parsed=ddf.ts.map_partitions(pd.to_datetime, meta=meta))
>>> print(ddf2.index.name)
id
>>> ddf2 = ddf.assign(ts_parsed=ddf.a.map_partitions(lambda x: x+1))
>>> print(ddf2.index.name)
id
>>> ddf2 = ddf.assign(ts_parsed=ddf.a.map_partitions(lambda x: x+1, meta=int))
>>> print(ddf2.index.name)
id
```

Can we close it?

**Comment by jcrist** [comment]
Thanks @jorloplaz!
