### ISSUE TITLE
Experiment with CuPy GPU arrays

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3007]
Dask contains parallel algorithms for parallel arrays based on the numpy syntax.  While commonly used with numpy arrays they also work with other libraries that mimic subsets of the numpy ndarray API.  

The [CuPy](https://cupy.chainer.org/) library implements a NumPy API compatible GPU ndarray.  It would be interesting to see how these two libraries interact, where performance bottlenecks are, and under what conditions they may be effectively used together.  

To experiment with this one would want to do a few things:

1.  Register cupy operations for `concatenate` and `tensordot`.  Examples doing this for the `sparse` library are [at the top of dask/array/core.py](https://github.com/dask/dask/blob/2e99f7d9af3ae82e9f96d2b9c0c271769f66de87/dask/array/core.py#L49-L60)
2.  Create a GPU array using `da.from_array`, or `da.from_delayed` and `da.concatenate/stack`.  See http://dask.pydata.org/en/latest/array-creation.html
3.  If you want to use distributed computing then ensure that cupy ndarrays can be efficiently serialized, probably by implementing `__setstate__` and `__getstate__` methods for them if they don't already exist.

This should be sufficient to get something up and running.

**Comment by jakirkham** [comment]
May be worth looking at `libgpuarray`/`pygpu` as well.

**Comment by mrocklin** [comment]
Sure, assuming that it matches a decent subset of the the np.ndarray API. I suspect that there are other options out there as well.

**Comment by sjperkins** [comment]
This would be a great addition!

I would guess that scheduling of asynchronous:

1. array transfers both on and off the GPU.
2. GPU kernels.

in the presence of limited GPU memory is going to the challenge.

**Comment by rzu512** [comment]
How about [theano](http://deeplearning.net/software/theano/)?

**Comment by jakirkham** [comment]
`theano` at least in the latest version uses `libgpuarray`/`pygpu`.

**Comment by jakirkham** [comment]
Should have mentioned [Bohrium]( http://bohrium.readthedocs.io ) before. There are some similarities between it and Dask in that it lazy evaluates things and provides a NumPy-like interface.

That said, Bohrium is focused on computations on a single CPU or GPU and makes use of OpenCL to do so. Also it compiles things as it is run much like Theano.

I think there is a really interesting possibility of using Dask Distributed to construct graphs that contain functions with Bohrium. Then fuse many of these operations down to tasks. Finally submitting them to workers where they are built and run. Thus allowing one to create high performance operations distributed on nodes with ease on larger than memory data.

**Comment by jakirkham** [comment]
Probably should add `numba` here too.

**Comment by jakirkham** [comment]
Has anyone been actively exploring this space? Would be interested to know what sort of things have been tried/learned. :)

**Comment by hmaarrfk** [comment]
How badly does cupy perform if you use the delayed interface?

**Comment by mrocklin** [comment]
Why would it run badly?

**Comment by hmaarrfk** [comment]
I don't think it would ;). I guess the only thing to worry about it resource contention for the GPU(s), though, I guess that is always something to worry about.

**Comment by mrocklin** [comment]
Sure, I can see how that would be a problem.

**Comment by pmoulik** [comment]
As a new user of dask, I have a naive question on how to manage GPU's on a multi-node multi-GPU cluster from inside a python script (not from command prompt like in https://youtu.be/jLQ2wAwapRg?t=894) with or without using cupy/numba. A simple application could be a matrix-matrix multiplication. A solution is to use mpi4py with cupy GPU arrays to allocate chunks of the matrices to a particular GPU; is there a simpler or similar solution while using dask arrays?

**Comment by mrocklin** [comment]
I'm going to go ahead and close this.  This topic is being handled piece by piece in other issues.
