### ISSUE TITLE
ddf.to_parquet(append=True) error when file not existing

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#3008]
When I try to save to parquet with append = True, in the first time (the file is absent), I get an error, I fixed it using this code 

```
append = False 
if os.path.exsists(file):
    append = True 
ddf.to_parquet(append = append) 
```

Is it a good idea to create a pool request with this code inside the to_parquet method?

Thanks.

**Comment by shughes-uk** [comment]
Just want to chime in to say I do the same thing and would appreciate this change.
