### ISSUE TITLE
Dask objects inspection failing, issues with graph

### ISSUE THREAD

**Issue by apatlpo** [dask/dask#3015]
Hi,

- I cannot reproduce the example given [here](http://dask.pydata.org/en/latest/inspect.html) on the dask website in order to inspect dask objects.
Please see the following notebook:
[inspect dask object](https://github.com/apatlpo/lops-array/blob/master/sandbox/test_graph.ipynb)

(sorry if github is not rendering notebooks as it the case for me right now)

- Also when I try to print graphs, complicated numbers show up which complicate the interpretation. For example:
[graph](https://github.com/apatlpo/lops-array/blob/master/sandbox/natl60_tseries_debug.ipynb)

Any thoughts?
Are these relates issues?

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/3016

**Comment by apatlpo** [comment]
Ok, thanks, my output still looks substantially different from that in the doc though:
[inspect dask object](https://github.com/apatlpo/lops-array/blob/master/sandbox/test_graph.ipynb)

**Comment by mrocklin** [comment]
Yes, as mentioned in the note of that PR we've taken some license in
cleaning up the output for the sake of documentation clarity

**Comment by apatlpo** [comment]
sorry,  my bad, I misunderstood the meaning of the note

**Comment by mrocklin** [comment]
How could it be clearer?

**Comment by apatlpo** [comment]
(answering your question will just emphasize that some weaknesses in my knowledge of python ...)

I guess it wasn't clear to me where were keynames in the output.

Something like that may help:

Here we've kept the names (e.g. ``x_1``, ``ones``, ``add``) simple for demonstration purposes.

or maybe having the true output somewhere.

but again I feel this is probably coming more from me than anything else

**Comment by mrocklin** [comment]
Pushed.  Thanks for the excellent suggestions.  Please let me know if there are ways to improve it further.

**Comment by apatlpo** [comment]
Actually, I've got another question: why do the graph png look different [here](https://github.com/apatlpo/lops-array/blob/master/sandbox/test_graph.ipynb) and [here](https://github.com/mrocklin/dask/blob/4aa5dae14c3593144efc13fa6a6cb9a8fa69fe56/docs/source/inspect.rst) ?
