### ISSUE TITLE
FUSE for Dask filesystem wrappers

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3018]
I would like a FUSE file system over S3 and GCS.  This is to experiment with reading NetCDF data on cloud providers.  Existing FUSE libraries exist, but sometimes don't work particularly well.  

We have a mostly-uniform interface in the s3fs/gcsfs/adlfs/hdfs3/pyarrow.hdfs projects that we might leverage here.  There are also Python FUSE libraries:

-  https://medium.com/the-python-corner/writing-a-fuse-filesystem-in-python-5e0f2de3a813
- https://www.stavros.io/posts/python-fuse-filesystem/

It might be interesting to create a FUSE wrapper around our standard interface at some point.  

I believe that @martindurant and @quasiben played with this several years ago.  

cc @jhamman @rabernat from XArray, @jacobtomlinson @niallrobinson from UK Met

**Comment by martindurant** [comment]
A branch tried something similar for hdfs3 - performance and other behaviour was not characterised https://github.com/martindurant/hdfs3/tree/feature/fuse

**Comment by jacobtomlinson** [comment]
We created https://github.com/met-office-lab/pysssix for simple fuse access
to S3.

**Comment by mrocklin** [comment]
@jacobtomlinson did you do any profiling of your FUSE system and get a sense of where bottlenecks might be?  Did you find any optimizations (connection pooling, read-ahead) useful?

**Comment by mrocklin** [comment]
@martindurant has been working with gcsfs and Fuse recently

- https://gitter.im/dask/dev?at=5a4c1e32ba39a53f1acc116b
- https://github.com/dask/gcsfs/pull/53

**Comment by jacobtomlinson** [comment]
Not yet. This is something we are going to start looking at now.

**Comment by martindurant** [comment]
Recommend closing this since https://github.com/dask/gcsfs/pull/53 . Something similar could be fairly simply done for s3fs, but other fuse implementations do already exist for s3, so maybe that is not necessary.
