### ISSUE TITLE
Pull request policy

### ISSUE THREAD

**Issue by rzu512** [dask/dask#3023]
What is the policy of pull request?
1. Complete, tested, and working code that enhance/maintain dask's functionality, or
2. Skeleton code with documentation for signature and return of functions.

**Comment by mrocklin** [comment]
Work-in-progress pull requests are welcome.  Github's PR format tends to be a convenient way to communicate about ideas.  I usually mark experimental PRs with `[WIP]` to discourage people from providing particularly detailed feedback.

**Comment by rzu512** [comment]
Thank you. I did a search on google ("pull request site:dask.pydata.org") and didn't find that on the wiki.
I don't want to do option 1 and then find out the api/architecture don't work in the end.

**Comment by mrocklin** [comment]
Another option is to ask questions and have discussion on an issue

**Comment by mrocklin** [comment]
Closing as resolved
