### ISSUE TITLE
QUESTION: read_sql_table() - how to specify table name in specific database?

### ISSUE THREAD

**Issue by pybokeh** [dask/dask#3029]
Hello, I want to apologize in advance, but I keep getting NoSuchTableError and have been searching all over StackOverflow.  I am using SqlAlchemy with PyODBC and I can connect to my data source fine with pure SqlAlchemy.  But when I tried to use dd.read_sql_table('database.schema.table_name', uri), I get the NoSuchTableError.  My uri is pretty much along the lines of: uri = 'mssql+pyodbc//user:pw@DSN', so I am using a DSN-based connection, not hostname-based connection.  Within my server, there are multiple databases.  So I think part of my problem is how to specify the specific database name.  I assumed I just use the dot notation: database.schema.table_name.  But I get that NoSuchTableError.  Is there another notation format I should be using to specify a specific database to obtain the table data from?  

Thanks!

**Comment by martindurant** [comment]
`read_sql_table` takes a `schema=` keyword, you should probably be using that to define where within the database system your table is located.

**Comment by pybokeh** [comment]
@martindurant Thank you!  FYI, I was using jupyter notebook's code completion and it did not show "schema" as a valid or available parameter.  So I'm assuming it is missing in the [docstring](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.read_sql_table).  Should I close this issue and open a new issue for documentation to include "schema" parameter for read_sql_table method?

**Comment by martindurant** [comment]
Indeed, `schema=` appears not in the docstring. An issue would be fine, but a PR would be better :)
Sorry for taking so long to get back to you on this.

**Comment by pybokeh** [comment]
@martindurant No problem!  Sorry I am not a developer type and wish I knew how to contribute by doing something seemingly as easy as updating documentation.  Otherwise, I would have done it myself!  I only know how to use Git for local repository version control and don't really use Github, other than to report errors.

**Comment by mrocklin** [comment]
Fixed by @martindurant in #3100
