### ISSUE TITLE
Installing dask-tensorflow failed on windows machine with python 3.6

### ISSUE THREAD

**Issue by AbdalaDiasse** [dask/dask#3031]
I am trying to install dask-tensorflow by running the following commands:

1. Install dask : pip install dask[complete]
2. install dask-ml : pip install dask-ml[complete]

dask was successfully installed as well as dask-ml with xgboost dependency but failed by installing tensorflow dependency.
I have got the following exception :
`
      File "C:\Users\XQing\AppData\Local\Temp\pip-build-3e2oi6r0\dask-tensorflow
\setup.py", line 7, in <module>
        requires = open('requirements.txt').read().strip().split('\n')
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XQing\Ap
pData\Local\Temp\pip-build-3e2oi6r0\dask-tensorflow\
(C:\ProgramData\Anaconda3) C:\Users\XQing>
`

**Comment by mrocklin** [comment]
It looks like the repository lacks a MANIFEST.in file

**Comment by AbdalaDiasse** [comment]
@mrocklin  can you help me to solve this issues... how can i get this manifest.in file

**Comment by mrocklin** [comment]
There isn't one.  This looks like a packaging problem on our end in the
dask-tensorflow package.  Short term you might try not pip installing with
the dask-ml rather than dask-ml[complete].  cc @TomAugspurger

**Comment by AbdalaDiasse** [comment]
@mrocklin I have installed now from your github repo.
Thanks ....

**Comment by jcrist** [comment]
Should be fixed by https://github.com/dask/dask-tensorflow/pull/4.
