### ISSUE TITLE
How can i implement the parallel version of kmeans?

### ISSUE THREAD

**Issue by aleeee** [dask/dask#3033]
Hello, i was to create a parallel clustering program using k-means and xMeans but when i use the n_jobs parameter of kmeans it doesn't have any effect.

```python
seeds = random_state.randint(np.iinfo(np.int32).max, size=n_init)
results = Parallel(n_jobs=n_jobs, verbose=0)(
    delayed(_kmeans_single)(X, n_clusters,
                            max_iter=max_iter,
                            init=init,
                            verbose=verbose,
                            tol=tol,
                            precompute_distances=precompute_distances,
                            x_squared_norms=x_squared_norms,
                            random_state=seed, # Change seed to ensure variety
                            distance_function=distance_function)
    for seed in seeds)
```

how can i implement the parallel version of kmeans?

**Comment by jcrist** [comment]
Hello,

Thank you for filing an issue. In the future when filing an issue, please create a simple title, and put the text of the issue in the text box below (I've fixed this one for you).

It also helps if you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve). This would be something that we could copy-paste to reproduce your issue. In this case you've provided code, but it's not clear where each of these functions come from (missing relevant imports).

It's also not clear to me how/if dask is being used here - this issue may be more fitting in scikit-learn. Alternatively, if this is a usage question, you might try asking on https://stackoverflow.com/.

**Comment by mrocklin** [comment]
See also http://dask-ml.readthedocs.io/en/latest/clustering.html

**Comment by jakirkham** [comment]
Should we close since `dask-ml` already implements `KMeans`?
