### ISSUE TITLE
CI failures with pandas master

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3039]
Seeing some [CI build failures with `pandas` dev]( https://travis-ci.org/dask/dask/jobs/323051544#L9277 ). Errors seem to be of the form `'MultiIndex' object has no attribute 'sortorder'`. More details in the log linked above.

**Comment by jakirkham** [comment]
These failures can also be seen on [`master`]( https://travis-ci.org/dask/dask/jobs/323489079#L9269 ).

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/18882 Probably. I can take a closer look tomorrow or Tuesday.

**Comment by TomAugspurger** [comment]
Should be fixed now @jakirkham.

**Comment by jakirkham** [comment]
Thanks @TomAugspurger.
