### ISSUE TITLE
Allow failures in development tests

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3043]
Currently one of the travis-ci configurations tests against master versions of NumPy, Pandas, and other libraries.  This has caused Dask testing builds to fail a couple of times recently.  Do we want to consider changing our travis-ci settings to allow this testing configuration to fail short term?

**Comment by TomAugspurger** [comment]
I would prefer leaving it as for now (now that https://github.com/dask/dask/issues/3039is fixed)

When something upstream does break dask, a maintainer could quickly make an issue calling attention to it and a PR [allowing failures](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail) on that build until its fixed.

**Comment by jakirkham** [comment]
IMHO this is a reasonable thing to do.

Development versions of libraries will inevitably introduce breaks that will cause failures. These are things that we certainly need to address, but not typically on the same time scale as issues with current stable releases. Not to mention it seems (to me at least) that problems in development libraries have been on the rise. In my rough estimation, it seems there has been an issue like this once a week. The consequence is reasonable PRs that have relatively little (or in some case nothing to do) with these development libraries end up being blocked rather frequently. Some of these include bug fixes for Dask or with stable library versions. Marking the development library build as a known failure IMHO more appropriately prioritizes these issues and allows development to continue at a more reasonable pace.

I suppose the counter to that would be that marking the development library build as an allowed failure could allow more issues to creep in. Maybe there is a way for those interested or closely associated with these development libraries to subscribe to these failures. Perhaps that would alleviate some of the concern about issues creeping in. Other thoughts on how to make this less burdensome?

**Comment by TomAugspurger** [comment]
Yep, I'd favor moving the development versions to a nightly cron job.

**Comment by jakirkham** [comment]
Put in PR ( https://github.com/dask/dask/pull/3088 ) to allow the dev build to fail for now. It certainly can be used to fix this issue if we agree with the change. Though it could also be used to discuss exactly how we would like to test development versions of dependencies going forward.
