### ISSUE TITLE
Implement the __array_ufunc__ protocol on Series and DataFrame objects

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3044]
Currently numpy ufuncs do not work as expected on dask Series and DataFrame objects.  We point people to dask.array ufuncs instead.

With the new `__array_ufunc__` protocol we make make this work as expected for all numpy ufuncs.  https://docs.scipy.org/doc/numpy-1.13.0/user/basics.subclassing.html#array-ufunc-for-ufuncs

This isn't necessarily high priority, but might be fun for someone who understands the protocol well and wants to affect a large part of the project.  The `__array_ufunc__` implementation in `dask/array/core.py` might be a good model.

**Comment by almaleksia** [comment]
@mrocklin hi, may I take this one? :)

**Comment by mrocklin** [comment]
Of course!

**Comment by almaleksia** [comment]
@mrocklin thank you :)

**Comment by mrocklin** [comment]
I believe that this has been resolved.  Thanks again @almaleksia !
