### ISSUE TITLE
Support hdfs filesystem(s) from pyarrow

### ISSUE THREAD

**Issue by jcrist** [dask/dask#3046]
Currently `hdfs` support requires using [hdfs3](https://github.com/dask/hdfs3). It would be nice to add additional support for using hdfs from pyarrow. `pyarrow.hdfs.HadoopFileSystem` supports using either `libhdfs` or `libhdfs3`. In our case, we need support for `libhdfs` to get around lack of support for reading encrypted data in `libhdfs3`.

A few complications:

- Currently the testing integration for hdfs in dask is in the [hdfs3](https://github.com/dask/hdfs3) repo. We could add tests for using pyarrow in there as well, but that seems odd. An alternative would be to move the hdfs integration tests to another repo. Could either move them back into distributed, into dask, or into some external repo set to run once daily.

  To be clear, the code we need to test is:
  - hdfs3 core (non-dask) functionality. This should stay in the hdfs3 repo
  - Integration tests with distributed (block locations stuff). This used to be in distributed. Could make sense to move back to here, these tests run fairly quickly, but would add another matrix build to the tests.
  - Integration tests with dask. This is reading/writing various formats to/from hdfs.

  An extra repo might make more sense in terms of test time (this code is slow to change, no need to slow down builds), but also runs the risk of failing without us noticing (see https://github.com/dask/hdfs3/pull/147#issuecomment-351893875)

- How do we specify a different backend? The options are:
  - libhdfs3 from hdfs3
  - libhdfs from pyarrow
  - libhdfs3 from pyarrow (not sure if there is a benefit to this, but including it for consistency)

  Ideas:
  - Unite all hdfs backends under a single dask file system class, the options above are specified as storage_options. More work, but more consistent. In this case I'd probably move the dask wrapper out of hdfs3 and into dask (similar to s3).
  - Specify backend using `set_options(hdfs_backend='hdfs3')` or `hdfs_backend='hdfs3'` in `storage_options`, with possible values `'hdfs3', 'pyarrow'`. The remaining `storage_options` are then forwarded to the appropriate backend class. This is similar to the idea above, but the switch option is external to the class (rather than internal). In this case, the pyarrow wrapper would live in dask, and the hdfs3 wrapper would live in hdfs3.

 I have a slight preference towards option 1, as it seems cleaner.

**Comment by jcrist** [comment]
cc @mrocklin, @martindurant for comment.

**Comment by jcrist** [comment]
> How do we specify a different backend? The options are:

Another idea would be to add a `filesystem` (or `fs`) kwarg where appropriate, and allow users to specifiy an instantiated fileystem object themselves. We may want to do this anyway in addition to ideas described above.

**Comment by mrocklin** [comment]
Thanks for the writeup.  Some thoughts:

-  I'm somewhat against having the HDFS testing machinery within core dask repositories.  I'm somewhat more in favor of a `dask-hdfs` package.  This is just a feeling though, I'm happy to be overruled, especially since I'm not likely to be the one that has to build/maintain this.
-  I'm entirely willing to drop the block locations stuff.  This is a performance hit, but it probably simplifies this quite a bit
-  If we do drop block locations stuff then we can just centralize on the abstract FileSystem interface, which might simplify things.  
-  Instead of adding a filesystem keyword to relevant functions it seems like we could make utility functions to manipulate `dask.bytes.core._filesystems` ?

**Comment by jcrist** [comment]
> I'm entirely willing to drop the block locations stuff. This is a performance hit, but it probably simplifies this quite a bit

This is a special case just for hdfs (currently), but besides complicated code doesn't really hit maintenance on the testing issues as specified above. Since it's already written I'm fine keeping it.

> I'm somewhat more in favor of a dask-hdfs package.

If we do this, this repo will be 100% for testing imo - the code should live elsewhere (probably in dask).

> Instead of adding a filesystem keyword to relevant functions it seems like we could make utility functions to manipulate dask.bytes.core._filesystems ?

In this case we have a few different possible backends for the same "protocol". Since the filesystem registry is just a lookup on protocol, this complicates things. Providing a way to specify an already instantiated filesystem is nice because:

- Allows specifying custom filesystems without needing to register them with dask, avoiding the need to override this lookup table.
- The connection/initialization cost can be shared between dask/external code (minor)

In this specific case I think we should make using pyarrow/hdfs3 configurable with a kwarg, so specifying fileystems manually isn't needed, but still may be a good idea in the future.

**Comment by mrocklin** [comment]
> This is a special case just for hdfs (currently), but besides complicated code doesn't really hit maintenance on the testing issues as specified above. Since it's already written I'm fine keeping it.

I think that this is the only dask-hdfs cross code that needs to exist.  If we drop it then maybe we can just rely on the abstract FileSystem contract and not have any code at all?

**Comment by jcrist** [comment]
That's true. I'm not sure how important this optimization is. It only comes into effect when short circuit reads are enabled and the data is evenly distributed across the same nodes the workers are (otherwise the scheduler will ignore the loose restriction in favor of increased parallelism). Dropping this functionality would drop the special case here, which may be nice.

We still may want some integration tests though. These things have a habit of breaking.

**Comment by mrocklin** [comment]
I agree with the value of integration tests.

Your assessment of the situation where locality is valuable is correct.  I believe that in modern practice this is more rarely the case and that  it's rare to have full access to all of the nodes in the cluster.
