### ISSUE TITLE
dask.dataframe.groupby with tuple keys fails

### ISSUE THREAD

**Issue by gsakkis** [dask/dask#3047]
To reproduce:
```
In [1]: import numpy as np; np.__version__
Out[1]: '1.13.3'

In [2]: import pandas as pd; pd.__version__
Out[2]: '0.21.1'

In [3]: import dask.dataframe; dask.__version__
Out[3]: '0.16.0'

In [4]: df = pd.DataFrame(np.random.choice((0,1), (10, 3)), columns=list('abc'))

In [5]: df.groupby('b').apply(len)
Out[5]: 
b
0    3
1    7
dtype: int64

In [6]: df.groupby(('b', 'c')).apply(len)
Out[6]: 
b  c
0  1    3
1  0    4
   1    3
dtype: int64

In [7]: ddf = dask.dataframe.from_pandas(df, npartitions=2)

In [8]: ddf.groupby('b').apply(len, meta=int).compute()
Out[8]: 
b
1    7
0    3
dtype: int64

In [9]: ddf.groupby(('b', 'c')).apply(len, meta=int).compute()
...
ValueError: Wrong number of items passed 0, placement implies 5
```

**Comment by jcrist** [comment]
Looks like we enforce that this is a list, not a tuple. The following works for me:

```python
In [15]: ddf.groupby(['b', 'c']).apply(len, meta=int).compute()
Out[15]:
b  c
0  1    2
1  0    4
0  0    3
1  1    1
dtype: int64
```

This is probably a simple thing to fix, if you'd like to submit a PR :).

**Comment by gsakkis** [comment]
D'oh, I could swear I tried a list first but apparently not! Thanks for the quick reply!

**Comment by TomAugspurger** [comment]
Pandas is changing it's handling of tuple keys in the next release. Here's the behavior on pandas master:

```python
In [8]: df.groupby(('b', 'c')).apply(len)
   ...:
/Users/taugspurger/Envs/dask-dev/bin/ipython:1: FutureWarning: Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
  #!/Users/taugspurger/Envs/dask-dev/bin/python3.6
Out[8]:
b  c
0  0    2
   1    3
1  0    3
   1    2
dtype: int64
```

Dask does seem to have some issues when the keys are actually tuples though:

```python
In [26]: df.columns = ['a', 'b', ('c', 'd')]

In [27]: df
Out[27]:
   a  b  (c, d)
0  1  0       0
1  1  1       1
2  1  1       0
3  0  0       1
4  1  1       0
5  1  0       1
6  0  0       0
7  1  1       1
8  0  0       1
9  0  1       0

In [28]: ddf = dask.dataframe.from_pandas(df, 2)

In [29]: ddf.groupby(('c', 'd')).apply(len, meta=int).compute()
```
...

~/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/methods.py in drop_columns(df, columns, dtype)
    168
    169 def drop_columns(df, columns, dtype):
--> 170     df = df.drop(columns, axis=1)
    171     df.columns = df.columns.astype(dtype)
    172     return df

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/core/generic.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   2847         for axis, labels in axes.items():
   2848             if labels is not None:
-> 2849                 obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   2850
   2851         if inplace:

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/core/generic.py in _drop_axis(self, labels, axis, level, errors)
   2873         axis, axis_ = self._get_axis(axis), axis
   2874
-> 2875         if axis.is_unique:
   2876             if level is not None:
   2877                 if not isinstance(axis, MultiIndex):

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/properties.pyx in pandas._libs.properties.cache_readonly.__get__()

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/core/indexes/base.py in is_unique(self)
   1306     def is_unique(self):
   1307         """ return if the index has unique values """
-> 1308         return self._engine.is_unique
   1309
   1310     @property

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.is_unique.__get__()

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._do_unique_check()

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._ensure_mapping_populated()

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine._call_map_locations()

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.map_locations()

TypeError: unhashable type: 'list'
```

**Comment by makmanalp** [comment]
We just hit this - just a heads up that figuring out that tuple vs list was the issue was not straightforward! The error messages we got were `ValueError: Multiple levels only valid with MultiIndex` and `IndexError: Index ... is out of bounds for size x`.

**Comment by TomAugspurger** [comment]
The issue in https://github.com/dask/dask/issues/3047#issuecomment-355595521 is still present (I actually get a SystemError now, fun). But I think given pandas' difficulties with handling keys as tuples I'm comfortable ignoring it now.

The original issue of specifying a list of keys as tuples currently (correctly) raises in both pandas and Dask.
