### ISSUE TITLE
dask.dataframe.DataFrame.apply: meta dtypes are not applied

### ISSUE THREAD

**Issue by gsakkis** [dask/dask#3048]
I'm trying to wrap my head around the `meta` parameter of [DataFrame.apply](https://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.apply). It _seems_ it works (printing the `dtypes` of the dask dataframe shows as expected) but when finally calling `compute()`, the resulting pandas dataframe has different dtypes:
```
In [1]: import numpy as np; np.__version__
Out[1]: '1.13.3'

In [2]: import pandas as pd; pd.__version__
Out[2]: '0.21.1'

In [3]: import dask.dataframe; dask.__version__
Out[3]: '0.16.0'

In [4]: df = pd.DataFrame(np.random.choice((0,1), (10, 3)), columns=list('abc'))

In [5]: ddf = dask.dataframe.from_pandas(df, npartitions=2)

In [6]: ddf2 = ddf.groupby('b').apply(lambda x: pd.Series((2, 13.19)), meta=[('x', np.dtype('int8')), ('y', np.dtype('float32'))])

In [7]: ddf2.dtypes
Out[7]: 
x       int8
y    float32
dtype: object

In [8]: ddf2.compute().dtypes
Out[8]: 
x    float64
y    float64
dtype: object
```

**Comment by jcrist** [comment]
This is because you're creating a single series in the lambda (which must have a consistent dtype representation), and that series has a float in it. The result of the compute call is consistent with pandas (both columns are floats):

```python
In [4]: df.groupby('b').apply(lambda x: pd.Series((1, 13.19)))
Out[4]:
     0      1
b
0  1.0  13.19
1  1.0  13.19
```

The reason why the computed and non-computed results differ above is that when you provide `meta` to dask, dask assumes that metadata is correct. In this case the metadata you provided was incorrect (column `x`'s dtype should have been `float64`).

**Comment by gsakkis** [comment]
Ok I see, I expected the meta enforces the types instead of assuming they are correct. In this case:
1. Why does `meta` need the types? It looks like it just needs the column names; `meta=pd.DataFrame(columns=['x', 'y'])` works and gives the same result.
2. Given that all elements of a pandas Series have the same type, how can I change the example above to actually return something consistent with the desired meta (int8 for x, float32 for y)?

**Comment by jcrist** [comment]
> Why does meta need the types? It looks like it just needs the column names; meta=pd.DataFrame(columns=['x', 'y']) works and gives the same result.

The default dtype when unspecified in pandas is `float64`, which just happens to be correct here. If your function returned integers you'd also need to specify the dtypes.

> Given that all elements of a pandas Series have the same type, how can I change the example above to actually return something consistent with the desired meta (int8 for x, float32 for y)?

We implement the same interface as Pandas, so you'd need to consult the pandas documentation for that: https://pandas.pydata.org/pandas-docs/stable/groupby.html. Returning a DataFrame works, but then you get an extra index column (cc @TomAugspurger for a potentially cleaner solution):

```python
In [39]: df = pd.DataFrame(np.random.choice((0, 1), (10, 3)), columns=list('abc'))

In [40]: ddf = dd.from_pandas(df, npartitions=2)

In [41]: df.groupby('b').apply(lambda x: pd.DataFrame({'x': [1], 'y': [13.19]}))  # pandas
Out[41]:
     x      y
b
0 0  1  13.19
1 0  1  13.19

In [42]: ddf.groupby('b').apply(lambda x: pd.DataFrame({'x': [1], 'y': [13.19]}), meta=[('x', 'i8'), ('y', 'f8')])  # dask
Out[42]:
Dask DataFrame Structure:
                   x        y
npartitions=2
               int64  float64
                 ...      ...
                 ...      ...
Dask Name: _groupby_slice_apply, 18 tasks

In [43]: ddf.groupby('b').apply(lambda x: pd.DataFrame({'x': [1], 'y': [13.19]}), meta=[('x', 'i8'), ('y', 'f8')]).compute()
Out[43]:
     x      y
b
1 0  1  13.19
0 0  1  13.19
```

**Comment by gsakkis** [comment]
> The default dtype when unspecified in pandas is float64, which just happens to be correct here. If your function returned integers you'd also need to specify the dtypes.

Not sure what you mean? if the function returned integers, the resulting dtype would be int64, regardless of what the declared `meta` dtypes were.

> We implement the same interface as Pandas, so you'd need to consult the pandas documentation for that: https://pandas.pydata.org/pandas-docs/stable/groupby.html. Returning a DataFrame works, but then you get an extra index column (cc @TomAugspurger for a potentially cleaner solution):

Great, thanks for the example; it's kinda cumbersome but does the job. My original question regarding `meta` remains though: I'm not sure what dask does with the dtypes passed in `meta`, it seems that the resulting dtypes are determined exclusively by the function passed to apply. If that's not always the case, can you give an example where passing different `meta` for the same applied function gives a different result?

**Comment by mrocklin** [comment]
Meta doesn't affect the computation.  It is just a hint from you to
Dask.dataframe about what your function does.  This helps Dask.dataframe
reason about your computation before actually executing anything.

**Comment by gsakkis** [comment]
Got it, good to know. Last question: is there a downside in passing `pd.DataFrame(columns=['x', 'y', 'z'])` as meta, e.g. if only the names but not the actual dtypes are known in advance?

**Comment by mrocklin** [comment]
Yes, there is some downside because dtypes may be wrong.

Closing
