### ISSUE TITLE
Release new (minor) version

### ISSUE THREAD

**Issue by topper-123** [dask/dask#3052]
The current version of dask relies on ``pandas.rolling_*``, which is deprecated and should be removed in the next version of pandas. The issue has been solve in #2995. However, the is currently only solved in master, so this blocks removing ``pandas.rolling_*`` etc. in pandas currently.

I propose releasing a new version of dask, eventually a minor version, that includes #2995 and other small PRs that make sense to include. I mentioned this wish in 4b09c3e58a8668daafac0caf4fcd60e139c388a0 as well.

**Comment by mrocklin** [comment]
Yes, I agree that we should do this.  Checking in with @jcrist , I think that everything he wanted in has been merged.  

@topper-123 , I apologize for the delay.

**Comment by jcrist** [comment]
Yep, should be good to release now.

**Comment by topper-123** [comment]
Great, thanks:-)

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/3053
