### ISSUE TITLE
Tokenize produces inconsistent results with sparse scipy arrays

### ISSUE THREAD

**Issue by rth** [dask/dask#3054]
Currently tokenizing sparse scipy arrays with `dask.base.tokenize` silently produces incorrect results,
```py
import numpy as np
import scipy.sparse
from dask.base import tokenize

rng = np.random.RandomState(42)
X1 = scipy.sparse.rand(1000, 10000, random_state=rng).asformat('csr')
X2 = X1.copy()

print("Hash the same array:", tokenize(X1), tokenize(X1))
print("Hash of a copy:", tokenize(X1), tokenize(X2))
X2.indices[:] = rng.randint(100, size=X2.indices.shape)
print('Same array:', (X1.data == X2.data).all() and (X1.indices == X2.indices).all())
print("Hash of a copy:", tokenize(X1), tokenize(X2))
```
which produces,
```
Hash the same array: 474b316b6cb32bf8259ba162f781ba5b 6e1b5064592383540cf14b1036aa021f
Hash of a copy: 890b397a996aa6334f4d5e35cdde5d96 a2f64849df27e4606ef14a7a2bc63dbb
Same array: False
Hash of a modified copy: 328441953a2ead3f92c1e6c58a316e9a 98dcc72f929b8036bdccc907981cb102
```
in particular, tokenizing the same sparse CSR array twice produces a different hash value. As does hashing a copy of an array.

While I understand that the tokenize function is not part of the public API (https://github.com/dask/dask/issues/593) and that scipy sparse arrays are not directly supported in dask,  it might still be not ideal to have a function occasionally [used in the docs](http://dask.pydata.org/en/latest/examples/array-extend.html?highlight=tokenize)  that silently produces incorrect results. To give more context, I run into this while building custom computational graphs (see this [SO question](https://stackoverflow.com/questions/48183849/opportunistic-caching-with-reusable-custom-graphs-in-dask) for more details)

**Versions**

Linux-4.4.0-105-generic-x86_64-with-debian-stretch-sid
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0]
NumPy 1.13.3
SciPy 1.0.0
dask 0.16.0

**Comment by jcrist** [comment]
>While I understand that the tokenize function is not part of the public API (#593) and that scipy sparse arrays are not directly supported in dask, it might still be not ideal to have a function occasionally used in the docs that silently produces incorrect results.

`dask.base.tokenize` is used for generating graph keys based on arguments from arbitrary python functions. We'd like functions with identical inputs to have the same key (and thus same hash), but we also never want it to fail. As such, if no implementation is registered for a type it defaults to a `uuid`. This is not incorrect for the intended purpose, it's just not optimal.

`tokenize` is implemented using a dispatch, so you can register your own implementation external to dask (http://dask.pydata.org/en/latest/custom-collections.html#implementing-deterministic-hashing). I'd also be willing to accept a PR adding deterministic hashing of sparse arrays to dask. In this case you'd want to use the lazy registration method to not enforce dependence on scipy (see https://github.com/dask/dask/blob/master/dask/base.py#L605-L629 for example)

**Comment by rth** [comment]
> As such, if no implementation is registered for a type it defaults to a uuid

OK, the results make more sense now.

Thanks for the detailed explanations, I'll try to make a PR.
