### ISSUE TITLE
to_delayed always optimizes

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3061]
The `da.Array.to_delayed` call optimizes the underlying dask array's task graph before creating the dask.delayed objects.  In some cases this is not desired.  One option here would be to have an `optimize_graph=True` keyword argument.  There might also be broader solutions?

**Comment by jcrist** [comment]
Adding a flag seems like a good option to me, with the default of `True`.

> In some cases this is not desired.

For documentation, can you give an example?

**Comment by mrocklin** [comment]
When you have multiple arrays that share a common history.  Per-array optimization would remove this common history, generating redundant work.

```pyhon
x = da.from_array(...)
y = x + 1 + 2
z = 2 * x
ys = y.to_delayed() 
zs = z.to_delayed()
...
```

**Comment by jcrist** [comment]
Perhaps we should have a toplevel `to_delayed` function?

```
yz, zs = dask.to_delayed(ys, zs)
```
