### ISSUE TITLE
Define Dask array with known numblocks but unknown chunks.

### ISSUE THREAD

**Issue by rzu512** [dask/dask#3065]
I want to define a Dask array with known numblocks but unknown chunks. This is because da.unique can create blocks with unpredictable shape. In this case, knowing the numblocks without knowing the chunks is enough to perform a step of tree reduction. 

Is it ok to use `chunks=((np.nan, np.nan), (np.nan, np.nan))` to represent a Dask array that have 2 blocks x 2 blocks and each block has unpredictable shape? 

If it is ok, maybe a small change to rechunk can perform block concatenation for blocks with unpredictable shapes.

**Comment by rzu512** [comment]
Example at http://dask.pydata.org/en/latest/array-creation.html states:

Some arrays have unknown chunk sizes. These are designated using np.nan rather than an integer....

```python
>>> import numpy as np
>>> import dask.array as da
>>> x = da.from_array(np.arange(4).reshape(2,2), chunks=1)
>>> g=da.Array(x.dask, x.name, ((np.nan, np.nan),(np.nan, np.nan),), dtype=x.dtype)
>>> g
dask.array<array, shape=(nan, nan), dtype=int64, chunksize=(nan, nan)>
>>> g.numblocks
(2, 2)
>>> g.shape
(nan, nan)
```
The `g.shape` is same as `(np.nan, np.nan)` in the example. So I guess this is fine.

**Comment by mrocklin** [comment]
Yes, you can use chunks and np.nan as you suggest.  If you want to perform
concatenation I would use da.concatenate.  I would expect this to work.
It's not clear to me how rechunk would work with unknown chunk shapes.

**Comment by rzu512** [comment]
Thanks.

Is it a good idea to change the example in the documentation to something like this?
```python
>>> x = da.ones((2,2), chunks=1)
>>> y = da.Array(x.dask, x.name, ((np.nan, np.nan), (np.nan, np.nan),), dtype=x.dtype)
>>> y.shape
(np.nan, np.nan)
>>> y[0]
ValueError: Array chunk sizes unknown
```

**Comment by mrocklin** [comment]
I would prefer that we avoid encouraging users to use the Array constructor
directly.

**Comment by rzu512** [comment]
Make sense. `y = da.unique(x)` would create a Dask array with unknown chunks, but it can't take the axis keyword. This means `y` is 1D and can't really illustrate the case of specifying a 2-dimensional array with `chunks=((np.nan, np.nan), (np.nan, np.nan))`
```python
>>> x = da.from_array(np.arange(16).reshape(4,4), chunks=1)
>>> y = da.unique(x)  # can't use axis keyword.
>>> y.shape
(nan,)
>>> y[0]
ValueError: Array chunk sizes unknown
```
