### ISSUE TITLE
fastparquet tests failing

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3084]
Seems many `fastparquet` tests are failing on CI with the message below. This happens in the development tests. ~~Given some `fastparquet` tests pass, it is probably not as simple as `fastparquet` not being installed.~~

```python
RuntimeError: `fastparquet` not installed
```

ref: https://travis-ci.org/dask/dask/jobs/331204699
ref: https://travis-ci.org/dask/dask/jobs/330840002

**Comment by jcrist** [comment]
> Given some fastparquet tests pass

I don't see any fastparquet tests passing in those. The other parquet tests (using pyarrow) are all skipped - looks like every fastparquet test fails due to failure to import (unless I missed one). But if `import fastparquet` fails then all the parquet tests should have been skipped, so I'm not sure what's going on here.

I know @martindurant made some recent changes to fastparquet, perhaps one of those is the culprit.

**Comment by jakirkham** [comment]
Hmm...maybe I was misreading some of the results due to the interleaved nature of the output from the parallel test runner.

**Comment by jakirkham** [comment]
That said, it's a bit odd that `fastparquet` is not found as [it does appear to be installed]( https://travis-ci.org/dask/dask/jobs/331204699#L724 ).

**Comment by jakirkham** [comment]
Given `fastparquet` hasn't been updated for a couple of days and the failures started within the last day, I think something else is at play.

**Comment by jakirkham** [comment]
From playing around locally, I think the issue is the `fastparquet` install is getting messed up somehow when we try to overwrite it with `pip`. Adding PR ( https://github.com/dask/dask/pull/3085 ) to remove the `conda` package before installing the development version with `pip` to see if that helps. Suspect it will.

**Comment by jakirkham** [comment]
As a side note, when exploring the `fastparquet` install on CI, discovered that the `pandas` version used had an effect on `fastparquet` failures. Given this, it might be worth testing `fastparquet` against different `pandas` versions. Opened issue ( https://github.com/dask/fastparquet/issues/283 ) to discuss adding different `pandas` versions to `fastparquet`'s CI.

**Comment by mrocklin** [comment]
Does anyone know what the current status of this is and possible fixes?  This appears to have been discussed in a few places.

**Comment by jcrist** [comment]
The only failing branch is the numpy/pandas most recent release branch, which doesn't actually install fastparquet. For some reason the tests run anyway *sometimes*, which results in failure. This may be a bug in pytest, I haven't investigated yet.

**Comment by mrocklin** [comment]
This no longer appears to be true.  I just reran a [docs-only-PR](https://github.com/dask/dask/pull/3102) and came up with some other failures:

https://travis-ci.org/dask/dask/builds/333765500?utm_source=github_status&utm_medium=notification

**Comment by martindurant** [comment]
^ that looks like a genuine bug, I'll try to get around to it.

**Comment by martindurant** [comment]
The following fixes the failures that remain. Sorry, this was poorly-vetted code
```
--- a/dask/dataframe/io/parquet.py
+++ b/dask/dataframe/io/parquet.py
@@ -366,7 +366,7 @@ def _write_partition_fastparquet(df, fs, path, filename, fmd, compression,
         rgs = None
     elif partition_on:
         rgs = partition_on_columns(df, partition_on, path, filename, fmd,
-                                   fs.sep, compression, fs.open, fs.mkdirs)
+                                   compression, fs.open, fs.mkdirs)
     else:
         # Fastparquet current doesn't properly set `num_rows` in the output
         # metadata. Set it here to fix that.
```
(the sep parameter is longer required since all paths are converted to posix-like - but the parameter should not have disappeared like that).

This is in the currently-released fastparquet. A mini-release could add back the sep parameter and ignore it.

**Comment by mrocklin** [comment]
Will this then fail on previous versions of fastparquet?

**Comment by martindurant** [comment]
Yes, removing it like the diff above will fail backwards. 
I can make it work for both by writing out the parameters as kwarguments here and also releasing the small fix on the fastparquet side; or explicitly testing for the version.

**Comment by jcrist** [comment]
I'd prefer a version check, no sense in adding a parameter back that's meaningless.

**Comment by martindurant** [comment]
Fixed by https://github.com/dask/dask/pull/3114

**Comment by jcrist** [comment]
The fastparquet tests are now passing on all branches (dev and master). This was a combination of issues fixed in fastparquet, and a small bugfix in our test code dealing with skipping tests if the dependencies weren't installed. Closing.
