### ISSUE TITLE
Caching conda packages on CI

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3086]
Given how many packages we are installing on CI, am thinking we may be able to speed up the CI builds significantly by caching `conda` packages that we install. Is this a reasonable suggestion? Has anyone tried this before with Dask? Any other thoughts?

**Comment by mrocklin** [comment]
I wasn't aware that this is possible.  This sounds great to me, assuming
that there is some mechanism for them to find new packages as they are
pushed.

**Comment by jakirkham** [comment]
Right. So `conda` itself has a package cache that it checks anyways after the solve is complete. IOW caching packages doesn't affect the solve. It only affects whether they are downloaded or reused.

**Comment by jcrist** [comment]
I'm not entirely sure if this would be a benefit. Setup time can be split into the following categories:
- Installation of conda
- Conda solving
- Downloading packages
- Installing packages

The actual installation of packages is pretty quick, it's just the solve and the download that take time. Since we'd just be skipping the download I'm not sure this would be worth it (besides marginally decreasing the load on `anaconda.org`. From [the travis docs](https://docs.travis-ci.com/user/caching/#Things-not-to-cache):

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source

**Comment by jakirkham** [comment]
For some context on how this can be done, here's some docs on [Travis CI's caching]( https://docs.travis-ci.com/user/caching/#Arbitrary-directories ) and [AppVeyor's caching]( https://www.appveyor.com/docs/build-cache/#cache-dependencies ). Typically CIs store the cache on S3.

In order to get this to work with Miniconda, one needs to know the layout a little bit. Basically there is a directory in the top level of the `conda` installation called `pkgs`, we would want to ensure `urls.txt` (where the packages come from) and all files matching `*.tar.bz2`s (the packages themselves) are kept. IOW all directories are purged. At conda-forge, we do this for the webpage repo by doing [a bit of cleanup and caching the directory]( https://github.com/conda-forge/conda-forge.github.io/blob/d4333bcb5b4864a914b74f7ac773cc0b38ca8a8f/.travis.yml#L41-L47 ). There's [a little bit of cleverness to use the cache directory with `conda`]( https://github.com/conda-forge/conda-forge.github.io/blob/d4333bcb5b4864a914b74f7ac773cc0b38ca8a8f/.travis.yml#L19-L20 ).

We also [cache Miniconda]( https://github.com/conda-forge/conda-forge.github.io/blob/d4333bcb5b4864a914b74f7ac773cc0b38ca8a8f/.travis.yml#L16-L17 ) at conda-forge. Though I doubt that part is really necessary.

**Comment by jcrist** [comment]
Have you noticed measurable speedups because of that?

If you'd want to try that with Dask, any speedups provided on our test runs would be nice. I'd just want to see measurable benefits before the build process gets more complicated.

**Comment by jakirkham** [comment]
Sorry I think your previous comment showed up only after that got posted.

It's been a while since anyone investigated caching and associated speedups. Also we mainly use Travis CI for macOS, which is where most of the effort was spent. Most of those findings are largely irrelevant here.

When it comes to Linux builds in conda-forge, we use CircleCI with a Docker image. So the Docker image solves the caching problem already. I suppose we could consider a Docker image here as well, but it could only be used for the Linux tests and would introduce divergence from the macOS build.

We certainly can explore. I agree that we should only make the change if it helps.

**Comment by mrocklin** [comment]
Any update here?

**Comment by TomAugspurger** [comment]
I think we'd welcome people working on this, but the recent conda speedups have lessened the need for it. Closing if that's OK (though feel free to reopen if you think it's worthwhile @jakirkham)
