### ISSUE TITLE
Reduction over arrays with broadcastable numblocks

### ISSUE THREAD

**Issue by rzu512** [dask/dask#3092]
Hi.

I wrote a reduction module based on extensions of `da.map_blocks` and `da.rechunk`, a set of functions for defining chunks over steps of tree reduction, and shifting and broadcasting of indices along axes. The current work in progress is at https://github.com/rzu512/dask-array-reductions2

The implementation includes:
- `sum` and `min` over zero, one, or multiple axes.
- `topk`, `argtopk` and `argmin` over zero or one axis.
- `argtopk_lookup`, `argmin_lookup` over zero or one axis.

`argtopk(k, x, axis)` returns the indices to the k largest elements along an axis. 

`argtopk_lookup(k, x, y, axis)` returns the indices to and the values of the k largest elements of x along an axis, and also lookup the values in y according to these indices.

It seems to work now, but the API can be simplified, and some places need more error messages / documentation.

**Comment by rzu512** [comment]
This implementation of tree reduction requires all arrays to have broadcastable numblocks.
But that doesn't work for all cases.

For example, suppose I want to calculate argmin on array A and use the result to index array B and to index array C. The numblocks of A and B are broadcastable. The numblocks of B and C are broadcastable. But the numblocks of B and C do not have to be broadcastable. I don't think it is possible to do a single reduction by a single function on A, B, and C together because the numblocks of A, B, and C are not broadcastable together. For now, I use `argmin_lookup` between A and B, and another `argmin_lookup` between B and C. But that performs `argmin` on A for twice. 

Maybe it is better to calculate argmin on array A, and somehow save the intermediate Dask arrays A0, A<sub>1</sub>, A<sub>2</sub>, ... A<sub>N</sub> for all steps of tree reduction. Then, create another tree reduction on B that uses A<sub>1</sub>...A<sub>N</sub> and another tree reduction on C that uses A<sub>1</sub>...A<sub>N</sub>. Probably I can get away from saving the rule for calculating chunks of A<sub>N + 1</sub> from chunks of A<sub>N</sub> if there are only a few possible rules.

Another possible solution is to define a tree reduction that can use multiple functions at each step. Function 1 performs reduction by argmin, 2 performs indexing over B, and 3 performs indexing over C. That would require additional code to define connectivity between the arrays and functions, and the ordering of the operations. In this case, there is no need to further modify map_blocks and rechunk. This seems more simple than last idea.

By the way, does ufunc in Dask already broadcast over both blocks and elements?

**Comment by TomAugspurger** [comment]
Sorry for missing this originally @rzu512. It seems like that linked repository is no longer available.
