### ISSUE TITLE
Tutorial: cant load file

### ISSUE THREAD

**Issue by effath** [dask/dask#3095]
i am using conda and installed all package from conda per the instructions.   I am using windows 10 and when I run 'prep.py' 
I get this error.   from other bugs on Stack, I saw that it might be an issue with skil-learn or pillow. 
IS there any way to fix this?

Traceback (most recent call last):
  File "prep.py", line 89, in <module>
    create_weather()
  File "prep.py", line 69, in create_weather
    from scipy.misc import imresize
ImportError: cannot import name 'imresize'

**Comment by martindurant** [comment]
This function is marked [depricated](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imresize.html), but still appears to import fine in scipy 1.0. 
Are you using a development version of scipy, @effath ?

In any case, we should heed the deprecation and change the import/dependency. Would you be interested in submitting a PR?

**Comment by effath** [comment]
I dint think i was using a development version...

`conda list --revision` 
```
+scikit-learn-0.19.1
+scipy-1.0.0 
```

I can submit one.

**Comment by effath** [comment]
I dint think i was using a development version...

`conda list --revision` 
```
+scikit-learn-0.19.1
+scipy-1.0.0 
```

I can submit.

**Comment by martindurant** [comment]
To submit a PR:
- for the repository by going to https://github.com/dask/dask-tutorial/ and clicking "fork" in the top-right
- clone the new repository (presumably at https://github.com/effath/dask-tutorial/ )
- make the changes in a new local branch, commit with useful message
- push the changes
- on the web interface of your fork, find the branch you pushed and click "new pull request"

**Comment by NHameleers** [comment]
Hi, also a newbie here.

I ran into the same error and found this page. I have fixed it in my local copy of the code. Is it ok if I make the pull request, or is that considered bad etiquette since effath offered to make it?

**Comment by mrocklin** [comment]
Alls fair in love, war, and contributing to the common good
