### ISSUE TITLE
graphviz and python-graphviz missing during conda install dask

### ISSUE THREAD

**Issue by franktoffel** [dask/dask#3101]
When installing dask with miniconda, graphviz dependencies are missing.

As result, you get an error when trying `.visualize()`:

```
*** RuntimeError: Drawing dask graphs requires the `graphviz` python library and the `graphviz` syst
em library to be installed.
```

Installation is not straightforward since when you:
`conda install graphviz`

You get the same error or the following if you are trying to import the library.
```
ipdb> import graphviz
*** ModuleNotFoundError: No module named 'graphviz'
```

After that, if you are lucky, you find that you should also:
`conda install python-graphviz`

Can these dependencies be added as default?

**Comment by mrocklin** [comment]
They are not required dependencies.  Generally we don't force users to
install optional dependencies and instead let them do it based on their own
judgment.

**Comment by franktoffel** [comment]
I see. Closing this issue then.

Thanks for the clarification.
