### ISSUE TITLE
dd.read_parquet no longer include index columns

### ISSUE THREAD

**Issue by xwang777** [dask/dask#3104]
When calling dask.dataframe.read_parquet(pq_file, index=False), dask 0.16.0 and earlier will include the MultiIndex columns as regular columns in the returned DataFrame, but dask 0.16.1 does not include them. The difference is due to dask, not fastparquet.

Here's an example:

```
from dask import dataframe as dd
import fastparquet as fpq
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10, 2), columns = ['a','b'], index=pd.MultiIndex.from_arrays([np.arange(10), np.arange(10) + 1], names=['x0','x1']))
df

fpq.write('/tmp/test.pq', df, write_index=True)

ddf = dd.read_parquet('/tmp/test.pq', index=False)
ddf
```

The df is like:

>               a         b
> x0 x1                    
> 0  1   1.088650  0.458507
> 1  2   1.271835 -0.840432
> 2  3  -0.979103 -0.240490
> 3  4   0.636582 -0.325154
> 4  5  -1.227770  0.602984
> 5  6  -0.707955  0.804685
> 6  7  -1.512000 -0.494987
> 7  8  -1.074822 -0.126040
> 8  9  -0.445532  0.682687
> 9  10  1.777594  1.127077
> 

For 0.16.0, the final ddf print as:

> Dask DataFrame Structure:
>                   x0     x1        a        b
> npartitions=1                                
>                int64  int64  float64  float64
>                  ...    ...      ...      ...
> Dask Name: read-parquet, 1 tasks
> 

For 0.16.1, the final ddf print as (index columns x0 and x1 are not included):

> Dask DataFrame Structure:
>                      a        b
> npartitions=1                  
>                float64  float64
>                    ...      ...
> Dask Name: read-parquet, 1 tasks
> 

Versions of pkgs:

> In [5]: dask.__version__, fpq.__version__, pd.__version__, np.__version__
> Out[5]: (u'0.16.0', u'0.1.3', u'0.21.0', '1.13.3')
> 

I'd think the older version's behavior is more convenient and intuitive, isn't it?

Thanks

**Comment by xwang777** [comment]
This is a break of API behavior. Is it planned, or is it an accident?

**Comment by martindurant** [comment]
Does this happen for both fastparquet and pyarrow engines?

**Comment by TomAugspurger** [comment]
Sorry for the slow replay.

I suspect this was in https://github.com/dask/dask/pull/2973, and was an unintentional change.

Personally, I don't find reading the indexes into regular columns intuitive, but perhaps better than dropping entirely :)

**Comment by martindurant** [comment]
I disagree, @TomAugspurger : the data is stored as column(s), and I would take the metadata as just a hint that they should be made the index of the newly-read data-frame. If the user wishes to prevent setting the index, the data should be read as ordinary columns.

**Comment by xwang777** [comment]
Thanks for the reply.

I only used fastparquet. The features of pyarrow seem to be more limited so I didn't try.

I think the problem here is API consistency. If I do `fpq.write(..., write_index=True)`, then I would expect to have some way to get the index columns back in `dd.read_parquet`. I understand that MultiIndex is not supported in parquet for now, so I have to do `dd.read_parquet(..., index=False)`. If the 'index=False' here means that I don't want index columns, then what's the API in read_parquet that let me get the index column data?

**Comment by martindurant** [comment]
Yes, I agree @xwang777  - I'll look into reverting this change for `index=False`.

**Comment by martindurant** [comment]
Interestingly, if you explicitly include the list of columns and include the index name(s) there, you do get them back:

```
[ ] ddf = dd.read_parquet('/tmp/test.pq', index=False, columns=['x0', 'x1', 'a', 'b'])
   x0  x1         a         b
0   0   1  1.231914 -1.044352
1   1   2 -0.499282  0.436183
2   2   3  0.552027 -0.265289
3   3   4  0.345140  0.485580
4   4   5  0.937267 -0.604615
5   5   6 -1.707770  1.143857
6   6   7  1.103741  0.411966
7   7   8  0.648006 -2.070996
8   8   9  0.900816 -1.107321
9   9  10 -0.619174  0.095268
```

**Comment by martindurant** [comment]
The following fixes it. @jcrist @TomAugspurger - does this seem like the right thing to do?
```
--- a/dask/dataframe/io/parquet.py
+++ b/dask/dataframe/io/parquet.py
@@ -234,6 +234,7 @@ def _read_fastparquet(fs, fs_token, paths, columns=None, filters=None,
         index_names, column_names, storage_name_mapping, column_index_names = (
             _parse_pandas_metadata(json.loads(pandas_md[0]))
         )
+        column_names.extend([n for n in index_names if n not in (index or [])])
     else:
         raise ValueError("File has multiple entries for 'pandas' metadata")
```
i.e., if `index=False` or `index='a'` (one of the columns or putative indexes), the data from what were previously indexes get loaded as normal columns.

**Comment by martindurant** [comment]
Note that if you specify an `index=` with any name that is not a column/index at all, you get the standard range index (0, 1, ..) but with that name applied. I don't know if that is intentional.

**Comment by TomAugspurger** [comment]
I would push it into `_normalize_index` / `_normalize_columns`, which are for reconciling user-input with the data. Putting it there will also fix things for Pyarrow, which I assume suffers from the same bug? I guess that `_normalize_columns` will need to take `index, index_names` too now, and if `index=False`, then `index_names` will all be included in the output.

**Comment by martindurant** [comment]
```
In [9]: dd.read_parquet('out.parq', index='a', engine='pyarrow').compute()
Out[9]:
                  b
a
 1.231914 -1.044352
-0.499282  0.436183
 0.552027 -0.265289
 0.345140  0.485580
 0.937267 -0.604615
-1.707770  1.143857
 1.103741  0.411966
 0.648006 -2.070996
 0.900816 -1.107321
-0.619174  0.095268

In [10]: dd.read_parquet('out.parq', index='blah', engine='pyarrow').compute()
Out[10]:
              a         b
x0 x1
0  1   1.231914 -1.044352
1  2  -0.499282  0.436183
2  3   0.552027 -0.265289
3  4   0.345140  0.485580
4  5   0.937267 -0.604615
5  6  -1.707770  1.143857
6  7   1.103741  0.411966
7  8   0.648006 -2.070996
8  9   0.900816 -1.107321
9  10 -0.619174  0.095268
```
You get the same latter result whether index=None, 'blah', 'x0', ['x0'], []...
I'm not sure that the behaviour should be.
In fact, for the case that works, I thought that dask dataframes could not handle multi-indexes anyway.
