### ISSUE TITLE
da.argmin of unique's result

### ISSUE THREAD

**Issue by rzu512** [dask/dask#3108]
Test:
```python
import dask.array as da
import numpy as np
x = da.arange(40, chunks=10)
y = da.unique(x)
z = da.argmin(y)
z.compute()
```
Result:
```
...
  File "<site-packages>/dask/array/reductions.py", line 496, in arg_chunk
    arg[:] = np.ravel_multi_index(total_ind, total_shape)
TypeError: 'float' object cannot be interpreted as an integer
```
Versions
```
Python 3.6.3
Dask 0.16.1 installed by pip3 install dask[complete] --user
Numpy 1.14.0
```
Don't know if this is caused by `np.nan` in `chunks`. That `ravel_multi_index` is probably for calculating offset of each block.

**Comment by rzu512** [comment]
arg-reduction can't calculate offset of blocks if the blocks or the array have unknown shape.
That case would need to communicate the shape of blocks between blocks or the main process.

**Comment by jakirkham** [comment]
Correct. I don't see an obvious way to fix this. Maybe a better error message? Do you have any suggestions?
