### ISSUE TITLE
Dask image subpackage

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3111]
There have been a few efforts to handle image data with Dask in the past. 

-  scikit-image [apply_parallel](http://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.apply_parallel) function, mostly designed to accelerate in-memory processing
-  Several small packages by @jakirkham under the dask-image github org: https://dask-image.github.io/ .  These tend to be aimed towards handling larger image stacks rather than accelerating the processing on smaller data.
    - https://github.com/dask-image/dask-imread
    - https://github.com/dask-image/dask-ndfilters
    - https://github.com/dask-image/dask-ndfourier
    - https://github.com/dask-image/dask-ndinterp
    - https://github.com/dask-image/dask-ndmeasure
    - https://github.com/dask-image/dask-ndmorph
-  The XArray geosciences community has done some work with stacks of GeoTIFF for satellite imagery

I thought I'd start an issue to centralize conversation.  I'm curious if there is a group of people that have enough time and interest in this topic to discuss possible scope and applications, as well as thinking about what groups might have resources to put effort into construction and maintenance in the future.

cc @jakirkham @stefanv @jni @jhamman to start.  Please include others from your communities if you know people that are likely to be interested.

**Comment by jni** [comment]
👋 

I don't have anything to add at this moment other than I am following these developments with interest. My *top* wish list item would be something like [BigDataViewer](https://imagej.net/BigDataViewer) but in Python. Currently I have neither the expertise nor the time to develop this, but I'd be willing to join forces with someone more experienced to make it happen.

**Comment by martindurant** [comment]
@jni , a good portion of that functionality could be achieved with datashader and holoviews (with dask as the computational engine). It would be nice for someone to put those pieces together into an imaging app like this.

**Comment by jakirkham** [comment]
Thanks for putting this together @mrocklin.

Yeah I know where you are coming from on the image viewer point, @jni. Sorry in advance for the rather long comment.

Personally have been using some primitive Matplotlib code I wrote combined with `%matplotlib notebook` in a Jupyter Notebook. It's called [`mplview`]( https://github.com/jakirkham/mplview ) (for lack of a better name 😄). It works ok, but lacks many of the features that an ImageJ/Fiji user would come to expect (maybe these can be overcome by manipulating the data viewed beforehand 😉). However it's saving grace has been that it can work on a NumPy array-like object. So it has been pretty easy to add a Dask Array to display.

Ultimately agree with @martindurant that holoview (+ datashader) (dependent on data size) does look promising and may be a good fit for Dask image work. Some relevant discussion on this point can be found in issue ( https://github.com/bokeh/datashader/issues/478 ). Have done a bit of preliminary work on this, but not in a form that is easy to show at this point. Though the examples in that issue should be fairly helpful for playing with this.

@hanslovsky has been doing some pretty interesting things with NumPy and ImgLib2. I'm not sure on what the current status of this work is; so, hopefully Philipp can chime in. That said, I *think* the main piece of this code lives in [imglib2-imglyb]( https://github.com/hanslovsky/imglib2-imglyb ) and there are [some examples in this repo]( https://github.com/hanslovsky/imglyb-examples ), which includes a couple BigDataViewer examples. Not sure if he has played with Dask in this context, but we can ask. :)

Regardless of what strategy is picked, would expect that dynamically adjusting task prioritization after submission will be very important ( https://github.com/dask/dask/issues/2860 ). Won't belabor the point as that issue already lays out this problem well.

**Comment by mrocklin** [comment]
It would be useful to get feedback from other imaging communities to flesh out scoping conversations.  

I wonder if @jakevdp can give an astronomy-focused perspective, or forward this to others who might be more engaged (astropy devs?).

**Comment by hanslovsky** [comment]
Pinging @ctrueden
Using bdv (or [BigCAT](https://github.com/saalfeldlab/bigcat)) could be a practical choice once [scijava/scyjava](https://github.com/scijava/scyjava) resolves the issue of importing java dependencies at runtime.

**Comment by stefanv** [comment]
From the skimage perspective, we are interest in all of the use cases listed above:

- Batch processing large stacks of images
- Processing a single image that is too large to fit into memory, via tiled access
- Processing single or multiple images in a way that utilizes all image cores

We would be happy to include code in skimage where applicable (a-la `apply_parallel`), and will write pages for our user guide that illustrate how to use external packages, should that be the preferred venue.

It is hard for your average skimage user to tune parallel approaches for optimal performance (how do you optimize storage access vs memory vs computation, parallel vs multi-node vs combinations of the above, tiling vs direct load, etc.), so if we could come up with "best practices" for these applications, that would be very useful.

**Comment by jakirkham** [comment]
Regarding chunk size, @stefanv, generally have found [FAQ 3]( http://dask.pydata.org/en/latest/faq.html ) helpful. Normally end up using something closer to the suggested upper bound in that answer. There may be cases where that doesn't make sense, but expect those are highly dependent on what operations are performed.

Would be curious to know if you have looked at any of the `dask-image` packages that @mrocklin has mentioned. One of thing he and I discussed was possibly merging these into a single `dask-image` package. Though if these sorts of things are of interest to the `scikit-image`, would be open to discussing other options.

**Comment by stefanv** [comment]
Admittedly, I haven't.  In order to make this more usable, would it make sense to package `dask-image/*` under a single `dask-ndimage` package?  It looks like it's only Python code, so the package shouldn't be very large.

**Comment by jakirkham** [comment]
Right, was thinking `dask-image` as the name (don't want to be constrained to N-D only operations in the future). That said, yes this sounds like a good idea (Matt also suggested this). As these are now a bit more feature complete than when we had started on this project, agree that moving towards one package is a good idea.

Though if there is interest in inclusion in `scikit-image`, would be happy discussing that as well. IMHO these libraries tend to cover your first two bullet points. Though suppose they could be used to handle the third bullet point, it is not something we have done with them in practice. The operations are equivalent to those one would find in `scipy.ndimage` and have relatively good coverage.

**Comment by stefanv** [comment]
@jni Any thoughts on how well this would fit inside skimage?

**Comment by jakirkham** [comment]
If it doesn't fit in skimage, that's fine too. Would also be happy to roll the current work together into a `dask-image` package. Either way would be very interested in collaborating with skimage devs on this project. So please let me know if there is anything I can do to make that easier.

**Comment by jni** [comment]
Sorry for the lag, I missed the notifications...

My intuition is that we don't want duplicate parallel/out-of-core and standard functions inside skimage. Long term, it would be awesome to have some global skimage parameter, "maxmem" (defaulting to e.g. machine RAM), and then it would choose between in-core and out-of-core functions automatically depending on the size of the input. But I think this kind of transparency is very hard to do right.

So, for now, I would say a unified `dask-image` library is the right approach. (Or `da-skimage`? =P)

For the long-term vision, an "@out_of_core" decorator could possibly apply quite generally to many of our functions. But, again, I think it would not be trivial, since each function has different border requirements.

I definitely want to work on this with you @jakirkham, and can do so starting mid-April.

@martindurant yes, a great suggestion. Were you volunteering to help me implement it? =P

**Comment by jakirkham** [comment]
No worries. Thanks for getting back to us. Guess it's my turn to be sorry for lag. ;)

Put together a basic repo for this collaboration with @mrocklin's help called [dask-image]( https://github.com/dask/dask-image ). Just has the boilerplate for a typical Python package ATM. Happy to share permissions with those interested. To help start things off, happy to migrate the content from the `dask-*` packages listed in the OP.

Generally agree that we should strive to avoid duplicating algorithm code if at all possible. There's already been a lot of work and thought in getting this stuff right in scikit-image. So would prefer to leverage that work with Dask whenever possible. We can discuss more the ins and outs of how parallel vs. distributed computations are handled. Though maybe we can move this over to an issue at dask-image. ;)

Sure. There is some tooling useful for this sort of problem in Dask. In particular [`map_overlap`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.map_overlap ) is pretty useful. We certainly could create a decorator based off of it. After playing with this problem a bit, have some ideas as to how we could write a reasonable decorator, but we should discuss more perhaps in a different dask-image issue.

Should add that there is no pressure for us to start working on these problem immediately. Just thought it would be good for us to have a place were we can collaborate on these issues.

**Comment by ebo** [comment]
I am *very* interested.  I literally have petabytes of data we regularly analyze, and so far the images can be as large as 3 gigapixels each (with as many as 8 bands).  Then there are stacks of processed data that would be nice to handle with dask's stacking functionality.  Right now I am working on implementing a modified Hoshen-Kopelman algorithm which gives not only segmentation, but keeping the neighborhood information as well provides m-coloring for an extra 10 or 20 lines of code.  The implementation I currently have is mutable (so that I can collapse and pack the ID's, and also make it easier to run out of core.  Much of our work data is stored as geotiff's so I would love to get some help polishing up examples (to be given back to one of the tutorials) that works with off the shelf data, as well as large giga-pixel datasets.  I will look into open-sourcing the dask work beyond tutorials, but that is a LONG line of paperwok, and would likely take 6 months once submitted.  All that said, I use image processing all the time and will give back what I can.

**Comment by ebo** [comment]
I also forgot to mention that when dealing with projected data, it would be nice to have an array save method which copies all the projection, and maybe metadata from some parent that is considered a template.  Hmmm... not sure that is clear...  Imaging calculating a Normalized Vegetation Difference Index (NDVI) from a multispectral image, and you want to save the array.  At the moment it seems like you have to go in and add all the pieces parts of the geospatial information.  Optimizing that would also be of great help.  I can probably help flesh out some ideas there, and test them ;-)

**Comment by jakirkham** [comment]
Have opened a topic for the sprint next week as issue ( https://github.com/scisprints/2018_05_sklearn_skimage_dask/issues/11 ). If people are interested in working on this during the sprint and have ideas, please feel free to chime in. Also if people that aren't at the sprint, but would be interested in joining remotely, it would be great to hear from you too so we can setup a way to connect next week.

**Comment by jakirkham** [comment]
Also added a Jupyter Notebook interactive image viewer topic as issue ( https://github.com/scisprints/2018_05_sklearn_skimage_dask/issues/12 ).

**Comment by magnunor** [comment]
Coming from the electron microscopy community, doing out-of-core data analysis of images has become necessary with improvements in detector technologies. My smaller datasets now contain 65000+ images, giving about 8.6 GB of raw data. One of the bigger problems now is simply being able to process the data. The HyperSpy community has been using `dask.array` to work with large datasets, and recently I've been implementing image processing routines for processing my specific type of data: https://gitlab.com/pixstem/pixstem/blob/master/pixstem/dask_tools.py

Having a package like dask image containing common functions for processing images out-of-core would be very nice!

As an aside, HyperSpy has had interactive visualization of dask arrays in Jupyter Notebooks through `LazySignal2D` for a while now: http://hyperspy.org/hyperspy-doc/current/user_guide/big_data.html

**Comment by jakirkham** [comment]
Of course, so there are some resources that might already be helpful for you. Also areas that might be fun to contribute to if they are interesting to you.

One is the [dask-image org]( https://github.com/dask-image/ ), which contains a bunch of image processing functions for Dask that generally follow the API of [`scipy.ndimage`]( https://docs.scipy.org/doc/scipy/reference/ndimage.html ), but take/provide Dask Arrays as input/output. These exist as various subpackages on PyPI and conda-forge. So should be easy to get and use. Would like to migrate this functionality over to [dask-image in the dask org]( https://github.com/dask/dask-image ). Help on this or other Dask image processing tools would certainly be welcome. 😄

Another is [scikit-image's `apply_parallel`]( http://scikit-image.org/docs/dev/api/skimage.util.html#apply-parallel ), which can parallelize computation over cores using Dask. Currently it takes/provides NumPy Arrays as input/output. Though there is a feature in `master`, which would allow Dask Arrays to be provided as input and computation delayed (so pieces could be viewed and/or spilled to disk). So can get this by installing scikit-image from source. Also should be available in the next scikit-image release.

There are of course general Dask functions, which can be useful in this space (though you may already be aware). In particular, [`map_overlap`]( http://dask.pydata.org/en/latest/array-ghost.html#dask.array.map_overlap ) is very useful for any filters needing some overlap to avoid boundary issues. Some work is happening in scikit-image PR ( https://github.com/scikit-image/scikit-image/pull/3133 ) to aid in estimating the overlap needed for arbitrary filters. Other useful Dask functions include [`atop`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.core.atop ) for general tensor operations and [`map_blocks`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.core.map_blocks ) when overlapping blocks are not needed.

Somewhat off topic, but if you have interest in signal processing, collecting use cases in issue ( https://github.com/dask/dask/issues/3339 ).

**Comment by mrocklin** [comment]
The dask-image package exists.  http://image.dask.org/en/latest/

There is probably still more work to do among people interested in this topic.  Lets defer the conversation to that issue tracker though.

**Comment by ctrueden** [comment]
@mrocklin Sorry if I am missing something obvious, but which issue tracker do you mean? It doesn't look like there is an https://github.com/dask/dask-image repository...

**Comment by mrocklin** [comment]
There is in fact a https://github.com/dask/dask-image repository

**Comment by ebo** [comment]
On Oct 24 2018 11:53 AM, Matthew Rocklin wrote:
> There is in fact a https://github.com/dask/dask-image repository

I will try to make some time to look into this.  I was not tracking the 
dask_image as I thought that functionality would migrate over to xarray 
and friends.
