### ISSUE TITLE
Didn't know which `TimeoutError` to catch - maybe the docs could be updated?

### ISSUE THREAD

**Issue by ianozsvald** [dask/dask#3113]
For reference I'm using 0.16.1 with Python 3.6.

I've just spent a happy couple of hours trialling dask on arbitrary functions (on large filesets with time-consuming regular expressions). Sometimes the re package seems to hang (I think 60k character lines on complex expressions are rather CPU-hungry - note this isn't dask, this is confirmed as a complex re) so I tried to use Dask's TimeoutError.

I didn't know what to catch and given that I had liberal `print` statements scattered around my code which continued to dump to screen _after_ the `TimeoutError` had been thrown, it took me a while to track back.

At first I assumed it was this exception I was seeing:
https://docs.python.org/3/library/exceptions.html#TimeoutError

Later using an ack-grep for "TimeoutError" inside `site-packages/distributed` I could see:
```
nanny.py
12:from tornado.ioloop import IOLoop, TimeoutError

utils.py
249:            raise gen.TimeoutError("timed out after %s s." % (timeout,))
...
```

At first I tried `tornado.iolook.TimeoutError`. After that did nothing I realised that the original error report was referring to `utils` and that `tornado.gen.TimeoutError` was the right one to catch.

Can I suggest that the Dask docs add a reference to this? For me it would have been useful in http://dask.pydata.org/en/latest/futures.html#distributed.Future.result as I saw this via the IPython help.

I can see on that doc page that `TimeoutError` is referred to a few times, then `gen.TimeoutError` is referred to under `distributed.wait`.

If you don't catch the right variant of the `TimeoutError` then you're debugging hint is a traceback like:
```

~/anaconda3/.../python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    247     if timeout is not None:
    248         if not e.wait(timeout):
--> 249             raise gen.TimeoutError("timed out after %s s." % (timeout,))
    250     else:
    251         while not e.is_set():

TimeoutError: timed out after 0.1 s.
```
where `gen` is the clue...but if you don't know Tornado then it takes you a while to think it backwards :-)

After the fact I realise that a quicker debug route would have been:
```
In [2]: import sys
In [3]: sys.last_value
Out[3]: tornado.gen.TimeoutError('timed out after 0.1 s.')
```

Aside from this - within a couple of hours I'd converted a serial-only complex bit of hacky code into something that runs on 4 cores & 4 hyperthreads - cheers!

**Comment by mrocklin** [comment]
Yeah, that seems like a valid concern.  You're correct that we use Tornado's `gen.TimeoutError`.   I agree that we should put this into docs in various places.  We could also expose it as `dask.distributed.TimeoutError` for future-proofing.  

Are there other documentation locations that you would recommend?  Do you have any interest in doing this work and submitting a pull request?

**Comment by mrocklin** [comment]
I'm glad to hear that you were able to parallelize some of your work with Dask.  Thank you for taking the time to file an excellent usability bug report.

**Comment by ianozsvald** [comment]
Hi Matt, you're most welcome. I'm not interested in doing the PR but I'd guess that this makes for a good documentation issue as a beginner task? Having a Dask `TimeoutError` also sounds very sensible, that sounds like a nice refactoring task for a new supporter too.

I spoke too soon on processing my large collection of files (the for-loop serial version completed overnight, the Dask variant didn't), I'll go back and clean up my shocking code. I'm certainly curious to try to get Dask working on this sort of task, I tend to promote Dask in my public machine learning talks now and I want to get a bit more comfy with it. Cheers!

**Comment by mrocklin** [comment]
See fix in https://github.com/dask/distributed/pull/1722

**Comment by ianozsvald** [comment]
The fix looks brilliant, thanks!
