### ISSUE TITLE
dask.dataframe.read_parquet nanosecond index divisions are None

### ISSUE THREAD

**Issue by postelrich** [dask/dask#3125]
I am working with time series data with nanosecond granularity. I was trying to convert from csv to parquet and ran into an issue when I read in the parquet files, the divisions are None. I was able to contrive the following example. The issue only exists when the parquet file is in multiple files.

**Example**
```
import pandas as pd
times = ['20180102000000000000' + '%03d' % n for n in range(1, 201)]
df = pd.DataFrame({'timefield': times, 'foo': range(200)})
df.to_csv('foo.csv', index=None)

import dask.dataframe as dd
ddf = dd.read_csv('foo.csv', blocksize=1280)
ddf['timefield'] = dd.to_datetime(ddf.timefield, format='%Y%m%d%H%M%S%f')
ddf = ddf.set_index('timefield')
ddf.to_parquet('fooparq', compression='snappy', write_index=True, times='int96')

ddf2 = dd.read_parquet('fooparq', index='timefield')
ddf2.divisions
```

**Expect**
```
ddf.divisions == ddf2.divisions
```

**Actual**
```
ddf.divisions
>>>(Timestamp('2018-01-02 00:00:00'),
>>> Timestamp('2018-01-02 00:00:00'),
>>> Timestamp('2018-01-02 00:00:00'),
>>> Timestamp('2018-01-02 00:00:00'),
>>> Timestamp('2018-01-02 00:00:00'),
>>> Timestamp('2018-01-02 00:00:00'))

ddf2.divisions
>>> (None, None, None, None, None)
```

Part of the issue was fastparquet not getting the right numpy type when loading int96 https://github.com/dask/fastparquet/pull/298. After @martindurant fixed that, the issue persisted and we saw that it failed in `compute_divisions` at [this line](https://github.com/dask/dask/blob/master/dask/dataframe/shuffle.py#L519).

@mrocklin @martindurant

**Comment by postelrich** [comment]
Noticed that the `to_csv` didn't write the nanos, working on update.

**Comment by postelrich** [comment]
Fixed example

**Comment by postelrich** [comment]
Example no longer reproduces problem, closing for now.

**Comment by aussetg** [comment]
Problem still exists.
