### ISSUE TITLE
Writing partitioned parquet fails with fastparquet 0.1.4

### ISSUE THREAD

**Issue by gorlins** [dask/dask#3130]
```dask.dataframe.io.parquet._write_partition_fastparquet``` relies on positional arguments to ```fastparquet.writer.partition_on_columns``` which had a breaking change in 0.1.4

dask/fastparquet#300

**Comment by jcrist** [comment]
This was fixed in #3114. You can install from master, or wait for the next release (should be sometime this week). Closing.
