### ISSUE TITLE
Question: Rolling calculation and sharing adjacent rows

### ISSUE THREAD

**Issue by postelrich** [dask/dask#3131]
If you repartition time series data to have a freq of 1H lets say, why does a 1min rolling calculation need to overlap-prepend, specifically why do adjacent partitions need to share rows?

https://github.com/dask/dask/blob/4b09c3e58a8668daafac0caf4fcd60e139c388a0/dask/dataframe/rolling.py#L45

**Comment by mrocklin** [comment]
I wouldn't expect any data sharing for an operation like resample, but for
rolling I think we'll always need to move data from previous partitions.
The value for a rolling aggregation for 1h00m will depend on data from
0h59m30s.

**Comment by postelrich** [comment]
do you mean because the divisions may not necessarily be exactly on the hour?

**Comment by mrocklin** [comment]
Even if they are exact, you still need information from the previous hour
to compute a rolling average

**Comment by postelrich** [comment]
yup yup, I was mixing up rolling with aggregating

**Comment by martindurant** [comment]
^ imagine the case where you have divisions (10h, 14h, 18h), for partition #2 14<=t<18hr, the very first entry will consider times 1359-1400, for which there *might* be values in the previous partition. Dask doesn't know that your values are spaced 1hr apart.
