### ISSUE TITLE
`sum` requires dtype argument for object array.

### ISSUE THREAD

**Issue by fujiisoup** [dask/dask#3133]
xref: pydata/xarray#1866
`sum` requires `dtype` arguments, which is different behavior from `numpy`.
Is it intended?

```python
In [1]: import numpy as np
In [2]: import dask.array as da
In [3]: x = np.array([True, True, False, np.nan], dtype=object)
In [4]: dx = da.from_array(x, chunks=[2])
In [5]: np.sum(x)
Out[5]: nan
In [6]: dx.sum()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-f94d34a739b8> in <module>()
----> 1 dx.sum()

/home/keisukefujii/Dropbox/projects/dask/dask/array/core.py in sum(self, axis, dtype, keepdims, split_every, out)
   1537         from .reductions import sum
   1538         return sum(self, axis=axis, dtype=dtype, keepdims=keepdims,
-> 1539                    split_every=split_every, out=out)
   1540 
   1541     @derived_from(np.ndarray)

/home/keisukefujii/Dropbox/projects/dask/dask/array/reductions.py in sum(a, axis, dtype, keepdims, split_every, out)
    142         dt = dtype
    143     else:
--> 144         dt = np.empty((1,), dtype=a.dtype).sum().dtype
    145     return reduction(a, chunk.sum, chunk.sum, axis=axis, keepdims=keepdims,
    146                      dtype=dt, split_every=split_every, out=out)

AttributeError: 'NoneType' object has no attribute 'dtype'
```

Python: 3.6
dask: current master

**Comment by jcrist** [comment]
Thanks for the bug report, no this is not intended. Looks like the issue is due to object dtype returning a python object instead of a numpy scalar (like all other dtypes). Adding `keepdims=True` to the `sum().dtype` call fixes this. Care to open a PR?

**Comment by fujiisoup** [comment]
Thanks, @jcrist 
I will take a look inside and try to send a PR.

**Comment by fujiisoup** [comment]
I started working but it looks that `nansum` does not work for object arrays either.

https://github.com/dask/dask/blob/8570bb2bb063838b6faa43068cd7c446f5805998/dask/array/reductions.py#L189-L191

I think `nansum` of the empty object array does not work well, 
```python
x = np.empty((1,), dtype=object)
np.nansum(x).dtype  -> AttributeError: 'NoneType' object has no attribute 'dtype'
```
Is there any workaround for this?

**Comment by jcrist** [comment]
You'll have to apply a similar to fix to all reductions. I recommend using `getattr(result_of_original_computation, 'dtype', object)`. In this case it'd be:

```
getattr(np.nansum(x), 'dtype', object)
```

**Comment by fujiisoup** [comment]
Thanks.
I will send a PR later today (japan time)
