### ISSUE TITLE
Memory-inefficient ordering related to rechunk

### ISSUE THREAD

**Issue by bmerry** [dask/dask#3139]
I've run into a case where graph traversal seems to be proceeding more-or-less breadth-first instead of depth-first, causing excessive memory usage. I've cut it down to a minimum example below. It creates a dask array (backed by a numpy array), multiplies it by some lower-dimensional arrays (with broadcasting along some dimension), and sums it along an axis. The original array takes 1,677,721,600 bytes, and is split into 25 chunks along axis 0. Thus, I expect total memory to be a small fraction larger than the original, rather than double the original.

It may be only indirectly related, but I've noticed that the behaviour occurs when I wrap a big numpy array into a single-chunk dask array and then partition it with `rechunk`, but that chunking it in the same way at `from_array` time makes the problem go away (change `PRECHUNK` in the example to True to get the latter behaviour). I've noticed that the graph optimiser doesn't seem to elide nodes related to trivial rechunk merges, so maybe it's just that this happens to affect the depth calculations in some way.

Results below are for Dask 0.16.1, Python 2.7. I also tried with master (8570bb2) in case the recent graph ordering changes improved things, but the same excessive memory use occurs (I didn't check to see if the ordering is identical).

![tasks](https://user-images.githubusercontent.com/1963944/35843141-3113daf0-0b0f-11e8-88e0-533e83906f61.png)
![resources](https://user-images.githubusercontent.com/1963944/35843150-37503a26-0b0f-11e8-8930-a00498e03eec.png)
![cache-count](https://user-images.githubusercontent.com/1963944/35843155-3be85988-0b0f-11e8-87ba-cd5d7b8bb834.png)

The breadth-first walk can be seen in the first image: the dark blue tasks on the left are mul tasks for the first multiplication of `vis`, while the green ones are combined mul-sum tasks. The resource usage also shows total memory coming to about double the size of the input array.

While a fix isn't hugely urgent (I'm going to work around it by doing some hand-coding to avoid using `rechunk` to produce the original array), I would be interested to know what triggers this behaviour so that I can be sure to avoid it.

```python
#!/usr/bin/env python

from __future__ import division, print_function
import dask.array as da
import numpy as np
import cachey

import dask.diagnostics
from dask.diagnostics import Profiler, CacheProfiler, ResourceProfiler


PRECHUNK = False
N_TIMES = 100
N_CHANS = 256
N_BLS = 8192
SHAPE = (N_TIMES, N_CHANS, N_BLS)


dask.set_options(get=dask.get)
profilers = [Profiler(), ResourceProfiler(dt=0.05), CacheProfiler(),
             CacheProfiler(metric=cachey.nbytes)]
with profilers[0], profilers[1], profilers[2], profilers[3]:
    vis_raw = np.full(SHAPE, 1.0, np.complex64)
    if PRECHUNK:
        vis = da.from_array(vis_raw, chunks=(4, N_CHANS, N_BLS), name=False)
    else:
        vis = da.from_array(vis_raw, chunks=SHAPE, name=False)
    vis = vis.rechunk({0: 4})

    Bf = da.asarray(np.ones((1, N_CHANS, N_BLS), np.complex64))
    Gf = da.asarray(np.ones((N_TIMES, 1, N_BLS), np.complex64))
    vis *= Bf * Bf.conj()
    vis *= Gf
    vis = da.sum(vis, axis=0)
    vis.compute()
dask.diagnostics.visualize(profilers, file_path='diagnostics.html')
```

**Comment by bmerry** [comment]
It doesn't seem to be purely related to rechunking: I tried an alternate approach of taking pieces and putting them back together with `da.concatenate`, and it had the same issues.

On the other hand, more aggressive optimization seems to help. Adding the following after the call to `vis.rechunk` makes it behave well again:
```
    dsk = vis.__dask_optimize__(vis.__dask_graph__(), vis.__dask_keys__(),
                                fast_functions=(da.core.getter, operator.getitem),
                                rename_fused_keys=False)
    vis.dask = dsk
```

**Comment by mrocklin** [comment]
Thank you for the excellent fail case.  I'm able to reproduce this locally.  

![dask](https://user-images.githubusercontent.com/306380/35861577-47fc932c-0b16-11e8-911d-6e345af9b623.png)

I'm not yet sure what's going on, but look forward to diving into this more in the future, probably in a few days.

**Comment by mrocklin** [comment]
Out of curiosity have you tried the dask.distributed scheduler?  

```python
from dask.distributed import Client
client = Client(processes=False)

# dask.set_options(get=dask.get)  # remove this line
```

Your current diagnostics won't work, but I suspect that it may perform slightly differently.

**Comment by mrocklin** [comment]
(especially on git-master)

**Comment by bmerry** [comment]
> Out of curiosity have you tried the dask.distributed scheduler?

I haven't yet tried dask.distributed (for anything). I see it now supports single-process threaded operation (which is a requirement for the way I'm using dask), so maybe it's time I tried it.

> Your current diagnostics won't work, but I suspect that it may perform slightly differently.

How would you recommend I tell whether dask.distributed is doing the right thing?

**Comment by mrocklin** [comment]
Look at http://localhost:8787/status .  That should give you plenty of
information

**Comment by bmerry** [comment]
Thanks, I see. Is there some way to force a single worker with distributed so that I can do an apples-to-apples comparison? I'm trying
```python
cluster = LocalCluster(n_workers=1, threads_per_worker=1, processes=False)
client = Client(cluster)
```
but it just seems to hang, with the process using about 20% CPU.

**Comment by bmerry** [comment]
> (especially on git-master)

Should I try git-master of dask, of distributed, or both?

**Comment by mrocklin** [comment]
> Should I try git-master of dask, of distributed, or both?

Both

> I'm trying

```python
cluster = LocalCluster(n_workers=1, threads_per_worker=1, processes=False)
client = Client(cluster)
```

This actually seems fine to me

**Comment by bmerry** [comment]
It turns out the problem was that creating a single thread on an N-core machine sets a memory limit of TOTAL_MEMORY/N, and there was spilling happening. Once I set the memory limit to 0, the distributed client seems to use breadth-first ordering and memory usage is good.

**Comment by mrocklin** [comment]
graph ordering of this problem seems to have improved.  Closing.
