### ISSUE TITLE
Add page for base API to docs

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3140]
Currently all our API docs are associated to a particular collection, like arrays or dataframes.  However there are a few functions like compute/persist/optimize/visualize that are generic and should maybe have a home of their own in a top-level API page.  Thoughts?

**Comment by martindurant** [comment]
Agreed, I think it's a good idea - it should also have links to the other specific API pages too, as well as public functions not documented elsewhere.

**Comment by jcrist** [comment]
These are mildly documented [here](http://dask.pydata.org/en/latest/custom-collections.html), but there should be an api docs page. Perhaps a "Common" or "Common Api" section under the Collections header in the sidebar?
