### ISSUE TITLE
Custom exceptions in custom graphs can't be reconstructed in main process when multiprocessing

### ISSUE THREAD

**Issue by OliverHofkens** [dask/dask#3145]
I'm using Dask as a general scheduler for custom functions, building the graphs manually.
When using the `dask.multiprocessing` scheduler, I stumbled upon the following issue:
When the function running in a subprocess throws an exception which needs arguments for its constructor, the exception cannot be instantiated in the main process: 

Example:
```
class ValidationError(Exception):
    def __init__(self, validator, message):
        pass
```

Raising this exception in a scheduled function gives the following exception:
```
.tox/py36/lib/python3.6/site-packages/dask/local.py:514: TypeError
--------------------------------------------------------------------
 while state['waiting'] or state['ready'] or state['running']:
                    key, res_info, failed = queue_get(queue)
                     if failed:
                     exc, tb = loads(res_info)
                     > TypeError: __init__() missing 2 required positional arguments: 'validator' and 'message'

```

If I understand correctly, whenever an exception occurs in a subprocess, the type and the tb are sent back to the main process to be reconstructed there. (ref: https://github.com/dask/dask/blob/3f6fd6a12dc0162a03d74d550058457824d0585c/dask/multiprocessing.py#L83). 
This fails in this scenario because the exception has required args to be instantiated.

I've tried both with and without `tblib` installed, but this doesn't change anything.

Is there a better approach for my custom exceptions, or is this something that could be fixed?

I'm on Python 3.6 running Dask 0.16.1.

Thanks!
Oliver

**Comment by mrocklin** [comment]
It looks like your exception is not serializable.  You might resolve this by implementing either the `__reduce__` or `__getstate__/__setstate__` protocols (see Python docs).

We might consider being robust to this sort of error though.  This wouldn't help users see the exception, but would present a slighly more clear error about the situation like `Exception("An error occured, but could not be serialized to be presented here")`.

**Comment by OliverHofkens** [comment]
Thanks for your fast response!
You were right, the exception wasn't serializable.

For future reference, implementing `__getstate__/__setstate__` didn't help because the base `Exception` has a `__reduce__` implementation calling `__init__`. The fix was to make sure every custom exception calls `super().__init__(*args)` where `args` are all arguments needed to construct the custom exception. Ref: https://stackoverflow.com/questions/16244923/how-to-make-a-custom-exception-class-with-multiple-init-args-pickleable

Thanks!
