### ISSUE TITLE
LZ4_compress and LZ4_uncompress removed

### ISSUE THREAD

**Issue by thrasibule** [dask/dask#3156]
Since commit python-lz4/python-lz4@d62fdc50c0e183d7260961f09d4e0701fbdf0c5c LZ4_compress and LZ4_decompress have been removed (they've been deprecated for a while). With the version of python-lz4 released on pypi, it means we can't use lz4 compression with dask, and worse importing dask.bytes.compression errors out.

**Comment by mrocklin** [comment]
That does indeed seem like an issue.  Would you be interested in submitting a PR to resolve this?  
How far back does the current solution go in the `python-lz4` library?  Should we consider being backwards compatible?

**Comment by mrocklin** [comment]
The relevant code to change lives here: https://github.com/dask/dask/blob/master/dask/bytes/compression.py#L36-L39

**Comment by thrasibule** [comment]
I can submit a PR, the fix is easy enough. Regarding backwards compatibility or not, the new api was introduced on version 0.9.0 which was released March 12th last year. I can try to be backwards compatible if that's important.

**Comment by martindurant** [comment]
Note that the version of lz4 in the anaconda channel of conda appears to be rather old.

**Comment by mrocklin** [comment]
Any interest in mentioning this in the company's *Anaconda Distribution* flow?
