### ISSUE TITLE
request: HTTP file system

### ISSUE THREAD

**Issue by martindurant** [dask/dask#3158]
It would be convenient to be able to do `open_files` on a list of HTTP URLs. This cannot be a complete file-system like the other backends, because there is no possibility of `glob()`, but I still think it would be useful for accessing remote data. 

In general, the size of a given URL's data can be found through a HEAD command, and chunks read using the `Range` header keyword; some servers do not support that, however, and then downloads could only be parallelised across multiple files.

**Comment by mrocklin** [comment]
I agree that this would be a useful thing to have

**Comment by mrocklin** [comment]
I'm curious, is there a particular use case that you had in mind?

**Comment by martindurant** [comment]
Yes, I am looking at archival astro data in FITS format, where the extensions can be addressed independently, and, for uncompressed data, you can slice the binary data directly.

Also, in the case of Intake, many data resources (and possibly their schemas) are available via a URI that may be HTTP or something else, and we'd like to use just one function to generate file-like objects for them.

It is worth noting that some loading functions like `pd.read_csv` already support HTTP (I don't know if that is done chunk-wise, though).
