### ISSUE TITLE
“Column Assignment Doesn't Support Timestamp”

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [dask/dask#3159]
Issue filed here based on MRocklin's suggestion at https://stackoverflow.com/q/48738936/1870832...

Reproduceable Example Below:
```
# library imports
import pandas as pd
from sklearn import datasets
from dask import dataframe as dd 

# Load toy data
iris = datasets.load_iris()
DF = pd.DataFrame(iris.data, columns = iris.feature_names)

# Convert Pands DataFrame to Dask DataFrame
ddf = dd.from_pandas(DF, npartitions = 2)

# Add a date column                                                                     
months_ago = 50
some_date = pd.datetime.today() - pd.DateOffset(months=train_months_back)

# Add state column to DataFrame
DF['date_vintage']= some_date # works fine
ddf['date_vintage']= some_date # TypeError: Column assignment doesn't support type Timestamp
```

Versions
`dask.__version__`
'0.17.0'
`pandas.__version__`
'0.22.0'

**Comment by mrocklin** [comment]
The relevant code is in dask/dataframe/core.py

```python
    @derived_from(pd.DataFrame)
    def assign(self, **kwargs):
        for k, v in kwargs.items():
            if not (isinstance(v, (Series, Scalar, pd.Series)) or
                    callable(v) or np.isscalar(v)):
                raise TypeError("Column assignment doesn't support type "
                                "{0}".format(type(v).__name__))
        pairs = list(sum(kwargs.items(), ()))
```

Which was added in 8b4be199a783a65811781275157bf826f0562cc3

It looks like some sort of check is necessary here, but that the check should be expanded somewhat.  Exactly what the check should be is a bit beyond me.  That commit has a good example of where this came about.  It looks like people were trying to assign lists of data hoping that things would partition out magically.  I think that we want the check to be "is either already a dask series or else is something that pandas considers a scalar".  I don't know of a good way to check for pandas-scalar values.

**Comment by TomAugspurger** [comment]
> I don't know of a good way to check for pandas-scalar values.

`pd.api.types.is_scalar` should do it for recent enough (0.18ish?) pandas.

**Comment by mrocklin** [comment]
Grand.  @MaxPowerWasTaken any interest in submitting a PR?  Presumably we just need to replace `np.isscalar` with the Pandas variant above.  We should probably also add a test.

**Comment by MaxPowerWasTaken** [comment]
Hi MRocklin, yes I can submit a PR for this, thanks to you and Tom for finding the issue and likely fix so fast. I probably won't have a chance to turn to this before tonight though.

**Comment by MaxPowerWasTaken** [comment]
Hey Matt and Tom,

So I tried cloning the dask repo, which seems to be the first step towards contributing per the 'Development Guidelines' site, but got an error related to permissions...
 
`(daskcontrib) MacBook-Pro:~ maxepstein$ git clone git@github.com:dask/dask.git`

```
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How should I proceed? Sorry if I'm missing something that should be obvious.

**Comment by martindurant** [comment]
I don't know about your specific error, but typically people use HTTP:
```
git clone https://github.com/dask/dask
 ```

**Comment by MaxPowerWasTaken** [comment]
that did it. Thanks! 

Maybe that should be the default suggestion at http://dask.pydata.org/en/latest/develop.html 
instead of:

```
Development Environment
Download code
Clone the main dask git repository (or whatever repository you’re working on.):

git clone git@github.com:dask/dask.git
```?

...or maybe not. Anyway thanks again Martin. I'll move forward on this tonight.

**Comment by martindurant** [comment]
Yeah, I think to make `git@` to work, you have to have set up appropriate SSH keys. I know I did this at some point, but I can't remember how.

**Comment by mrocklin** [comment]
I believe that this has been resolved.  Merging.
