### ISSUE TITLE
read_parquet unable to load list of hdfs files

### ISSUE THREAD

**Issue by dennis-ec** [dask/dask#3163]
Hello,
first of all thank you for your great work.
I updated my dask version to version 0.17.0 with the long awaited feature of passing list of files into read_parquet. However when passing a list of parquet files on a hdfs file system like
['hdfs://0.0.0.0:800/data/2018-01-01.parquet', 
 'hdfs://0.0.0.0:800/data/2018-01-01.parquet',  . . .]
I get the following error using pyarrow:
```
OSError                                   Traceback (most recent call last)
<timed exec> in <module>()
/home/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    794 
    795     return read(fs, fs_token, paths, columns=columns, filters=filters,
--> 796                 categories=categories, index=index)
    797 
    798 

/home/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_pyarrow(fs, fs_token, paths, columns, filters, categories, index)
    522         columns = list(columns)
    523 
--> 524     dataset = pq.ParquetDataset(paths, filesystem=get_pyarrow_filesystem(fs))
    525     schema = dataset.schema.to_arrow_schema()
    526     has_pandas_metadata = schema.metadata is not None and b'pandas' in schema.metadata

/home/miniconda3/lib/python3.6/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema)
    686 
    687         (self.pieces, self.partitions,
--> 688          self.metadata_path) = _make_manifest(path_or_paths, self.fs)
    689 
    690         if self.metadata_path is not None:

/home/miniconda3/lib/python3.6/site-packages/pyarrow/parquet.py in _make_manifest(path_or_paths, fs, pathsep)
    846             if not fs.isfile(path):
    847                 raise IOError('Passed non-file path: {0}'
--> 848                               .format(path))
    849             piece = ParquetDatasetPiece(path)
    850             pieces.append(piece)

OSError: Passed non-file path: /data/2018-01-01.parquet
```
I also tried setting the engine to fastparquet and got this:
```
ValueError                                Traceback (most recent call last)
<timed exec> in <module>()

/home/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    794 
    795     return read(fs, fs_token, paths, columns=columns, filters=filters,
--> 796                 categories=categories, index=index)
    797 
    798 

/home/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_fastparquet(fs, fs_token, paths, columns, filters, categories, index)
    221 
    222     if len(paths) > 1:
--> 223         pf = fastparquet.ParquetFile(paths, open_with=fs.open, sep=fs.sep)
    224     else:
    225         try:

/home/miniconda3/lib/python3.6/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
     81         if isinstance(fn, (tuple, list)):
     82             basepath, fmd = metadata_from_many(fn, verify_schema=verify,
---> 83                                                open_with=open_with, root=root)
     84             if basepath:
     85                 self.fn = join_path(basepath, '_metadata')  # effective file

/home/miniconda3/lib/python3.6/site-packages/fastparquet/util.py in metadata_from_many(file_list, verify_schema, open_with, root)
    134             # should remove 'empty' datasets up front? Get ignored on load
    135             # anyway.
--> 136             raise ValueError('Cannot merge multi-file input', fn)
    137         for rg in pf.row_groups:
    138             rg = copy.copy(rg)

ValueError: ('Cannot merge multi-file input', '2018-01-01.parquet')
```

The files have multiple partitions and are written with fastparquet as engine and snappy as compression. My previous solution of passing each string in the list to read_parquet and then concat the dataframes is still working.

**Comment by martindurant** [comment]
So far as the fastparquet error goes, the exception should have been more expressive. I'd be interested if you can find out more information about `'2018-01-01.parquet'`. If it has multiple partitions in the one file and no reference to any other files, it should have `file_scheme='simple'` and not hit that ValueError. Loading multiple data-sets, which are themselves each multi-file, is not supported, which is this error. That support could in theory be added with some effort.

**Comment by dennis-ec** [comment]
Thank you for your answer.
I wrote the files by calling:
```
dd.to_parquet(dd.from_pandas(df, chunksize=10000),
                      'hdfs://0.0.0.0:800/datat/{}.parquet'.format(date_name),
                      compression='snappy', engine='fastparquet')
```
For me I solved this issue by using a one partition per file policy and now save the file directly in pandas:
```
df.to_parquet(
        '/data/{}.parquet'.format(date_name),
        compression='snappy', engine='fastparquet', open_with=hdfs.open)
```
For me this solution actually gives me a speed boost because my partitions were too small and now each file/partition has an appropriate size.

However, I believe there is a strong use case to conveniently read file arrays containing multi-file files.
Writing multi partitioned parquet files seems quite natural with dask and the ability to read multiple of such files without reading each one of them and then concat them should be a common use case.

**Comment by martindurant** [comment]
Yeah, you will find that `dd.to_parquet` created multiple files for each data-frame, to enable each partition to be independently written by different workers. This remains true even if the data-frame only contains one partition (you get one `_metadata` file and one data file).

Another workaround would have been to pass a list of data-files only to `read_parquet`, perhaps by globbing. 

In principle, there is no reason that fastparquet should not be able to cope with this situation, infer the full path of each part file from its metadata file plus relative path, and then compute a joint root to the whole lot; but I expect that this would break spectacularly if there were any directory-based partitioning going on.
