### ISSUE TITLE
Example point to an old notebook

### ISSUE THREAD

**Issue by glemaitre** [dask/dask#3165]
The following [example](https://github.com/dask/dask/blob/master/docs/source/examples/delayed-custom.rst) is linked to an [old notebook](http://nbviewer.jupyter.org/github/dask/dask-examples/blob/master/do-and-profiler.ipynb) which break with the current dask API.

At first, I made a PR to the original repo:
https://github.com/dask/dask-examples/pull/19

but it does seem to be a good idea if it is not going to be maintained in the future.

So I was wondering what would be the best such that I can provide an appropriate PR.

**Comment by mrocklin** [comment]
I agree that the old repository with stale notebooks is an issue.  I don't
know what the best solution is.  Do you have any suggestions?

**Comment by glemaitre** [comment]
If you are running the examples with the CI, the notebook could be an example by itself in rst.

Did you have any plan/disucssion to have an example gallery with sphinx-gallery for instance.
At least building the gallery ensure that the examples are up to date at the cost of maintenance.

**Comment by mrocklin** [comment]
The dask-examples repository is now tested regularly by CI. We point to that repository for examples.  Closing.
