### ISSUE TITLE
FAQ is out of date

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3172]
https://stackoverflow.com/questions/48825884/caching-ignores-available-memory-argument/48826768#48826768

Also, the choice of questions on there seems silly, and there are only four.  I'm in favor of greatly expanding it, or removing it entirely.  Based on time availability my guess is that expanding it is not a sensible option short term.

**Comment by mrocklin** [comment]
In the docs?  I don't disagree that that question and answer is useful, but
I don't think that this page should exist as it is if there are only a few
questions here.  If you're into this topic I propose that we (you?) make an
array-specific FAQ and move this there, along with hopefully many other
questions and answers that we've seen come up frequently.  That might
reduce the promise that we're making here.

**Comment by jakirkham** [comment]
So I don't have strong feelings as to whether that content lives in something like a FAQ or gets integrated into the other docs pages somehow. Just stating that it would be good to keep it in the docs in some form.

**Comment by mrocklin** [comment]
I would again like to bring this up.  I haven't had time to build content to replace the exact questions FAQ nor do I expect to in the near future, but would still like to delete it.  It is out of date and I believe that it does active harm.  I believe that all relevant questions (serialization, chunks) are handled elsewhere in the documentation.

@jakirkham thoughts?

**Comment by mrocklin** [comment]
This has been removed.
