### ISSUE TITLE
Batcher sort comparison

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3173]
I learned today that @sklam has a batcher sort algorithm for the dask gpudataframe.  I would be curious to see how this compares to Dask.dataframe's current shuffle algorithms.

Any time/interest in collaborating on this @sklam?

**Comment by sklam** [comment]
All you need to do is adapt `sort_delayed_frame ` and `_compare_frame` in https://github.com/gpuopenanalytics/dask_gdf/blob/22bb4c39715121612a8df0b3b9fa792ee01fdaad/dask_gdf/batcher_sortnet.py
