### ISSUE TITLE
Unable to read from HDFS in Dask

### ISSUE THREAD

**Issue by lijose** [dask/dask#3181]
I am trying to read data from HDFS using dask data frame. While trying to execute, I am getting below error:

`dd.read_csv('hdfs://username:password@host_name:port/path_to_hdfs')`
`NotImplementedError: Unknown protocol hdfs://username:password@host_name:port/path_to_hdfs`

My dask version:
`dask.__version__`
`0.10.0`

Is there any work around to access the hdfs using current dask version ??

**Comment by martindurant** [comment]
Do you have `hdfs3`installed?

**Comment by lijose** [comment]
yes

**Comment by martindurant** [comment]
I assume your hdfs3 import failed - try using it directly, to see why that might be.

**Comment by mrocklin** [comment]
Note that the current dask version is 0.17.0

**Comment by jcrist** [comment]
Dask version 0.10.0 is *very* old (released 6/13/16, almost 2 years ago). Please try upgrading to the current dask release.

**Comment by martindurant** [comment]
(as of the latest dask release, you also have the option of using pyarrow's implementation of hdfs, so you should be covered)

**Comment by lijose** [comment]
I can't change the version as I am using office environment. 
@martindurant 
   I am using dask alone and not hdfs3. Kindly find the whole code 

```
import dask.dataframe as dd
dd.read_csv('hdfs://username:password@host_name:port/path_to_hdfs')
```

**Comment by mrocklin** [comment]
We recommend that you install a new version.  You might consider downloading and installing [Anaconda](https://www.anaconda.com/), which can often be done with only user permissions on a standard computer.

Unfortunately due to limited maintainer time it is rare to find people willing to support very old versions.
