### ISSUE TITLE
Indexing with conditional array gives incorrect ordering

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3184]
Appears that indexing with a conditional array in Dask gives an ordering of the results that does not match what one would get from NumPy. This appears to be a consequence of applying each chunk in the conditional against each chunk in the array being indexed and combining the results over chunks. To better mimic how NumPy is scanning through the array, we could flatten both arrays before pulling out the results in the expected order.

<details>
<summary>Example:</summary>

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: a1 = np.arange(24).reshape(4, 6)

In [4]: a2 = da.from_array(a1, chunks=(2, 3))

In [5]: a1[a1 % 2 == 1]
Out[5]: array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [6]: a2[a2 % 2 == 1].compute()
Out[6]: array([ 1,  7,  3,  5,  9, 11, 13, 19, 15, 17, 21, 23])
```

</details>

<details>
<summary>Environment:</summary>

```yaml
name: test
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- bokeh=0.12.13=py36_0
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- click=6.7=py_1
- cloudpickle=0.5.2=py_0
- dask=0.17.0=py_0
- dask-core=0.17.0=py_0
- decorator=4.1.2=py36_0
- distributed=1.21.0=py36_0
- heapdict=1.0.0=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36_0
- libgfortran=3.0.0=0
- locket=0.2.0=py36_1
- markupsafe=1.0=py36_0
- msgpack-python=0.5.1=py36_0
- ncurses=5.9=10
- numpy=1.14.0=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- parso=0.1.1=py_0
- partd=0.3.8=py36_0
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- psutil=5.4.0=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pytz=2018.3=py_0
- pyyaml=3.12=py36_1
- readline=7.0=0
- setuptools=38.5.1=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- sortedcontainers=1.5.7=py36_0
- sqlite=3.20.1=2
- tblib=1.3.2=py36_0
- tk=8.6.7=0
- toolz=0.8.2=py_2
- tornado=4.5.3=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- yaml=0.1.7=0
- zict=0.1.3=py_0
- zlib=1.2.11=0
```

</details>

**Comment by jakirkham** [comment]
To be clear the workaround would be `a2.ravel()[(a2 % 2 == 1).ravel()]`. Not sure if there is an obvious place to use that exact strategy. Thoughts @mrocklin?

**Comment by mrocklin** [comment]
Yeah, this seems like a case where correctness and performance are at odds.  We should probably choose correctness.  It looks like the relevant function is `dask/array/slicing.py::slice_with_dask_array`, which currently just uses `atop`.

**Comment by jakirkham** [comment]
Thanks. Trying to address with PR ( https://github.com/dask/dask/pull/3193 ). Not sure if we like that approach. Also failed a test for me locally.

**Comment by jrbourbeau** [comment]
Had an offline conversation with @jakirkham a few days ago about this issue. He proposed trying an alternative approach to the `ravel`-based technique taken in #3193. I had hoped to summarize the alternative approach here (which would use `np.indices` and dask array sorting to get the same ordering as NumPy when indexing with a conditional array), but didn't quite wrap my head around exactly how all the steps fit together : /

@jakirkham whenever you get a moment, if you're able to outline the other approach I think that would help a lot in moving this issue forward

**Comment by jakirkham** [comment]
Fixed with PR ( https://github.com/dask/dask/pull/5151 ).

Note: This doesn't handle unknown chunk sizes. However it looks like we will soon start erroring out in that case (unless we do come up with a viable fix there).
