### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by kamalmkce-2016** [dask/dask#3189]
import sys

def find_min_num(num_div):
    
    if num_div < 80:
        for i in xrange(1,2**num_div,1):
            if check_divisor(long(i)) == num_div:
                print(i)
                break
def check_divisor(n):
    n=long(n)
    count=0
    for j in range(1,n+1,1):
        if n%j==0:
            count+=1
    return count

find_min_num(44)
 ERROR:
Traceback (most recent call last):
  File "C:/Python27/prg.py", line 22, in <module>
    find_min_num(44)
  File "C:/Python27/prg.py", line 6, in find_min_num
    for i in xrange(1,2**num_div,1):
OverflowError: Python int too large to convert to C long

**Comment by TomAugspurger** [comment]
Is this a dask bug report? I don't see you using it anywhere. Did you mean to open this issue somewhere else?
