### ISSUE TITLE
Release 0.17.1

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3192]
I would like to issue a micro-release soon.  Any objections or concerns?

**Comment by jakirkham** [comment]
SGTM

**Comment by jakirkham** [comment]
Do you have a timeline in mind?

**Comment by mrocklin** [comment]
Today or tomorrow sometime if that's alright with everyone

**Comment by mrocklin** [comment]
Pushed both `dask` and `distributed` packages to PyPI
