### ISSUE TITLE
dask/dataframe/core.py imports toolz, which isn't installed

### ISSUE THREAD

**Issue by girving** [dask/dask#3195]
I installed dask `0.17.0` with `pip install dask`.  If I try to import `dask.dataframe`, I get

    Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import dask.dataframe
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/irving/anaconda/envs/openai/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 3, in <module>
        from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      File "/Users/irving/anaconda/envs/openai/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
        from toolz import merge, first, unique, partition_all, remove
    ModuleNotFoundError: No module named 'toolz'

toolz also came up in https://github.com/dask/dask/issues/1849, but that was in `async.py`.  This is `dataframe/core.py`.

**Comment by jcrist** [comment]
`pip install dask` doesn't install dask dataframe, you probably want `pip install dask[complete]` or `pip install dask[dataframe]`. See http://dask.pydata.org/en/latest/install.html for more information.

**Comment by girving** [comment]
Thanks for clarifying.  I'll close, but it could be reopened if it's worth it to produce a better error message explaining what's happening.
