### ISSUE TITLE
Groupby-Apply runs function twice for each group

### ISSUE THREAD

**Issue by JR-Mayday** [dask/dask#3197]
Example:
```python

import time
import pandas as pd
import dask.dataframe as dd


def func(df):
    print("Processing ...")
    total = sum(df['D'])
    time.sleep(5)
    print("Processed: {}".format(total))
    return total


def create_pandas_df():
    return pd.DataFrame({'A': "test", 'B': "foo", 'C': "bar", 'D': [1, 2, 3, 4, 5]})


def main():
    df = create_pandas_df()
    print(df)
    ddf = dd.from_pandas(df, npartitions=1)

    keys = ['A', 'B', 'C']
    # Data only has one group if groupby A,B,C
    result = ddf.groupby(keys).apply(func, meta=('total', 'int')).compute()

    print(result)


if __name__ == '__main__':
    main()

```

Output:
```
      A    B    C  D
0  test  foo  bar  1
1  test  foo  bar  2
2  test  foo  bar  3
3  test  foo  bar  4
4  test  foo  bar  5
Processing ...
Processed: 15
Processing ...
Processed: 15
A     B    C  
test  foo  bar    15
Name: total, dtype: int64
```

Sample data only has one group but user function with sleep(5) is executed twice for same group. I don't believe it's a bug which we didn't find out earlier. I'm confused here. I want to understand what happened in the back for handling this one group calculation.

Dask version: 0.17.0

**Comment by mrocklin** [comment]
Dask dataframe runs the function once immediately to determine types.  You can avoid this extra call by providing metadata with the `meta=` keyword.

**Comment by mrocklin** [comment]
The

**Comment by mrocklin** [comment]
The initial call is on a tiny fake dataset, and so usually doesn't take much time.

**Comment by JR-Mayday** [comment]
Thanks for super fast response! How can I pass meta when creating dask dataframe by read_csv()?

In this example, it sleeps twice instead of once which caused extra cost.

**Comment by jcrist** [comment]
In this case this is pandas calling your function twice, not dask:

```python
In [7]: type(df)
Out[7]: pandas.core.frame.DataFrame

In [8]: df.groupby(['A', 'B', 'C']).apply(func)
Processing ...
Processed: 15
Processing ...
Processed: 15
Out[8]:
A     B    C
test  foo  bar    15
dtype: int64
```

From the pandas docstring:

```
Notes
-----
In the current implementation ``apply`` calls func twice on the
first group to decide whether it can take a fast or slow code
path. This can lead to unexpected behavior if func has
side-effects, as they will take effect twice for the first
group.
```

**Comment by JR-Mayday** [comment]
For dask, this twice-on-first-group thing will happen for each partition. So the duplication could be more than once - depend on partition number.

**Comment by jcrist** [comment]
> For dask, this twice-on-first-group thing will happen for  each partition. So the duplication could be more than once - depend on  partition number.

Correct. Dask just calls groupby-apply on each partition. The only thing you can do as a user is make sure you pass in `meta` to `groupby(...).apply(func, meta=...)`, which will make sure `func` isn't called until `compute` time where it can happen in parallel or across a cluster.

**Comment by JR-Mayday** [comment]
Got it. Thank you!

**Comment by CMCDragonkai** [comment]
> > For dask, this twice-on-first-group thing will happen for  each partition. So the duplication could be more than once - depend on  partition number.
> 
> Correct. Dask just calls groupby-apply on each partition. The only thing you can do as a user is pass in `meta` to `groupby(...).apply(func, meta=...)`, which will ensure `func` isn't called until `compute` time where it can happen in parallel or across a cluster.

Is this true? Even when I use `meta` in my usage, I've found that each partition/group is still being executed twice. Is there a particular version of dask that has the `meta` keyword preventing the double execution? This is quite problematic for me as my group by apply has side effects.

**Comment by TomAugspurger** [comment]
Do you have an example of it applying twice?

```python
In [8]: df = pd.DataFrame({"A": [1, 2, 3, 4], "B": ['a','a', 'b', 'b']})

In [9]: ddf = dd.from_pandas(df, 2)

In [10]: def f(x):
    ...:     print(x)
    ...:     return x
    ...:

In [11]: ddf.groupby("B").apply(f, meta=ddf._meta).compute()
   A  B
2  3  b
3  4  b
   A  B
0  1  a
1  2  a
Out[11]:
   A  B
2  3  b
3  4  b
0  1  a
1  2  a
```
