### ISSUE TITLE
'dask.array.image' not found

### ISSUE THREAD

**Issue by doublex** [dask/dask#3203]
This line:
````dask.array.image.imread('/tmp/test.jpg').to_hdf5(target, name)````

Error:
```` AttributeError: 'module' object has no attribute 'image' ````

How can I setup `dask.array` with `dask.array.image`?

Thanks a lot!

**Comment by jcrist** [comment]
The image namespace isn't imported by default, you need to do:

```python
import dask.array.image
dask.array.image.imread('/tmp/test.jpg').to_hdf5(target, name)
```

**Comment by doublex** [comment]
@jcrist 
You are right! Thanks a lot!!
