### ISSUE TITLE
I read a 9G csv with 2 workers using 30min

### ISSUE THREAD

**Issue by edolele** [dask/dask#3204]
I read a 9G csv with 2 workers (40 cpu cores and 256G RAM)
In top, I found that the computation of dask-workers finished in about 1 min. But the dask-scheduler started a python process after dask-workers' work finished, this python process work had been running for about 30 min.

This is my code:
`class DATATABLE_CLASS():
    """
    读取数据存储类
    """

    def __init__(self,client):
        self.client=client

    def load_trans_data(self, path, npartitions=1, header='infer', encoding='gb18030', dtype='str',error_bad_lines=False, delimiter=',',
                        **kwargs):
        trans_data = self.client.persist(dd.read_csv(path, header=header, encoding=encoding, delimiter=delimiter, dtype=dtype,
                                                     error_bad_lines=False, **kwargs))
        trans_data.columns = ['trx_dt', 'trx_tm', 'cust_id', 'cust_nm', 'cust_type', 'trx_amt', 'onl_bal',
                              'opp_cust_id', 'opp_cust_nm', 'memo', 'ip']
        trans_data = trans_data[~trans_data['trx_amt'].str.contains(u'[\u4e00-\u9fa5]')]
        trans_data = trans_data[~trans_data['onl_bal'].str.contains(u'[\u4e00-\u9fa5]')]

        # trans_data['trx_dt'] = pd.to_datetime(trans_data['trx_dt'])
        trans_data['trx_amt'] = trans_data['trx_amt'].astype('float')
        trans_data['onl_bal'] = trans_data['onl_bal'].astype('float')

        trans_data = trans_data.set_index('cust_id', drop=False)`

**Comment by mrocklin** [comment]
To my knowledge dask-scheduler doesn't start any extra processes.  I don't know how to help you without additional information.  Maybe you can create a minimal example that reproduces the problem?

**Comment by edolele** [comment]
I found these two filters waste too much time. 
    trans_data = trans_data[~trans_data['trx_amt'].str.contains(u'[\u4e00-\u9fa5]')]
    trans_data = trans_data[~trans_data['onl_bal'].str.contains(u'[\u4e00-\u9fa5]')]
