### ISSUE TITLE
`isnull` takes a long time

### ISSUE THREAD

**Issue by davidh-ssec** [dask/dask#3205]
This is related to https://github.com/pydata/xarray/issues/1937.

I'm using xarray DataArrays with dask arrays underneath. I noticed that running `xarr.isnull()` was actually computing the array leading to the issue above. So my workaround was to use `dask.array.isnull(xarr)`, except this seems to take an extremely long time and shows up in the profiler that way. The code and profile graphs are below. The code is doing similar calculations to what my actual code is doing along with some extra calculations to throw in more tasks in the profiler:

```
import numpy as np
import dask.array as da
import xarray as xr
import pandas as pd

from dask.diagnostics import ResourceProfiler, Profiler, CacheProfiler, visualize
from dask.dot import dot_graph
from datetime import datetime

def isnull(x):
    return x.data.map_blocks(pd.isnull, dtype=np.bool)
    
with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
    rows, cols = (6000, 10000)
    a = xr.DataArray(da.arange(rows * cols, chunks=4096 * 4096).reshape((rows, cols)))
    b = xr.DataArray(da.arange(rows * cols, chunks=4096 * 4096).reshape((rows, cols)))
    c = xr.DataArray(da.arange(rows * cols, chunks=4096 * 4096).reshape((rows, cols)))
    a = a * 2.35 + 2.35
    b = b * 2.35 + 2.35
    c = c * 2.35 + 2.35
    d = a * b + c
    e = ~(da.isnull(a) | da.isnull(b) | da.isnull(c) | da.isnull(d))
    #e = ~(isnull(a) | isnull(b) | isnull(c) | isnull(d))
    b = b.where(e)
    c = c.where(e)
    d = d.where(e)
    f = xr.concat([b, c, d], 'bands')
    np.save('isnull_1.npy', f.compute().data)
    #np.save('isnull_2.npy', f.compute().data)
    
visualize([prof, rprof, cprof])
```

Running the above code produces a profiler plot like the following:

![image](https://user-images.githubusercontent.com/1828519/36631288-e6568b86-193a-11e8-8089-7b6f958f25bb.png)

If you switch to the commented out lines and run it again you should get a profile like the following:

![image](https://user-images.githubusercontent.com/1828519/36631298-0229302a-193b-11e8-8acf-d99eda185711.png)

You can then do `diff isnull_1.npy isnull_2.npy` and the results should be the same. As you can see from the plots above the dask `isnull` takes ~2.75 seconds per chunk and most of the execution time on those workers. The second plot shows mapping blocks to pandas `isnull` takes ~0.05 seconds per chunk. Am I doing something wrong here or is this a bug?

**Comment by mrocklin** [comment]
Thank you for the minimal example

> dask.array.isnull(xarr)

This line isn't quite valid.  Dask.array functions don't necessarily know how to operate on xarray objects directly.  It looks like they're computing the entire upstream array.  This is suboptimal.

The second approach seems fine.  Your custom isnull function properly unwraps the dask array from the xarray dataarray.

FWIW I debugged this by using the dashboard for the distributed scheduler.  In particular I looked at the call stacks for the individual workers during the long execution task.  This also would have been evident when looking at the profile plot.  I recommend [this video](https://www.youtube.com/watch?v=N_GqzcuGLCY) if you're interested in using the dashboard to diagnose problems like this.

**Comment by davidh-ssec** [comment]
Thanks @mrocklin I'll take a look. Since I'm not using the result of the `isnull` like an xarray and I don't need it to be I've switched to `da.isnull(a.data)` which performs the same as the second approach.

So I guess this can be closed as "don't ask dask to work on things that it doesn't know how to work on".
