### ISSUE TITLE
Implementing broadcast_arrays

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3209]
Would be great to have a Dask Array implementation of [`broadcast_arrays`]( https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.broadcast_arrays.html ). It may be possible to pull [code from the Dask Array `meshgrid`]( https://github.com/dask/dask/blob/0.17.1/dask/array/creation.py#L334 ) to get this to work.

**Comment by jakirkham** [comment]
Do you know of a good way to determine the expected shape, @shoyer? We probably could guess, but if there is a better way, would like to use it here if possible.

**Comment by shoyer** [comment]
NumPy has an internal helper function `broadcast_shape()`:
https://github.com/numpy/numpy/blob/v1.14.0/numpy/lib/stride_tricks.py#L176

So one option would be to construct dummy arrays with `as_strided()` and then use `np.broadcast` along the lines of `broadcast_shape()` to get the result shape.

Or we could rewrite the logic in Python -- it isn't that complicated, and you can find it in old versions of the numpy source code:
https://github.com/numpy/numpy/blob/e8590311a7b312711c7a4f40c1a15496e34d0ee6/numpy/lib/stride_tricks.py#L47

**Comment by jcrist** [comment]
There's also `dask.array.core.broadcast_shapes` (https://github.com/dask/dask/blob/master/dask/array/core.py#L2866-L2893), which may be useful here.

**Comment by jakirkham** [comment]
Thanks all. Added PR ( https://github.com/dask/dask/pull/3217 ) with an implementation of `broadcast_arrays`. Feedback welcome.
