### ISSUE TITLE
CI timeouts

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3220]
Have noticed an uptick in CI timeouts during the test suite. Here's an [example]( https://travis-ci.org/dask/dask/jobs/345659992 ). Unfortunately not much info to go on. Restarting normally corrects the issue. Not sure if it is just a memory limit issue and thus cleaning up (e.g. `conda` and `pip` packages to start) will help or something else is required.

**Comment by TomAugspurger** [comment]
FWIW pandas has been seeing these over the past couple weeks so it's (probably) not anything specific to dask's CI. I haven't done any investigation into why some builds take 2-3x longer than normal.

**Comment by xhochy** [comment]
We also see 2-3x slowdowns in Travis in the recent weeks in the Arrow builds. This is probably due to Travis just giving out less resources than before.
