### ISSUE TITLE
Membership policies

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3223]
I've been going through a few Dask systems recently and cleaning things up.  

This evening I'm looking at the members of the GitHub organization, and the various privileges that everyone has.  There are a few things we might want to change here.  I would appreciate feedback from current active core devs on this topic before taking any action.  

### Permissions

The current permissions are relatively permissive.  All members have full ability to create, destroy, and modify any repository within the organization.  

We might want to reduce these default permissions.  That would allow us to invite more people within the organization with a lower barrier to entry.

### Current members

Historically there have been a few ways in which people have become members:

1.  I arbitrarily gave them commit rights, typically this happened early in the project (like @shoyer, @jcrist, @cowlicks, @eriknw)
2.  They were involved early on in the project within Continuum (like @koverholt, @danielfrg, @quasiben, @chdoig, @martindurant, and @teoliphant)
3.  More recently (last couple of years) they were added only after consensus from other core and active devs (like @ogrisel,  @sinhrks, @TomAugspurger, @pitrou, @jakirkham) 

All of these people have played significant roles in Dask's development at some point or another.  Some people are still around while others seem to have moved on.

Additionally several people have been given commit rights to particular repositories a la carte.

### Current Owners

1.  @mrocklin
2.  @jcrist 
3.  @koverholt 
4.  @teoliphant 

### New Member Policy

The current process to add new members has been that a current member proposes a candidate to the active core contributors (arbitrarily determined) and if a consensus agrees then they are given full rights everywhere.  I came up with this process arbitrarily.

Individuals have been given commit rights to some of the peripheral repositories (like daskernetes, gcsfs, dask-glm) in an ad-hoc way by members who manage those repositories.  This has historically been done without consultation with the larger group.  To my knowledge this has never been done on the larger repositories like dask/dask and dask/distributed.

### Old Member Policy

We've never removed any rights from anyone in organization.  This hasn't been a problem.  

However we might want to consider it.  There are people who were added early on who have significantly more permission that others today who are more engaged with the project.  I personally have great trust and respect for everyone listed above, and don't think that this is a problem, but it might be good to establish a policy here early.

### Some options
 
1.  We could continue as-is.  Everything seems to be fine.
2.  We could create a policy around conditions for global rights (active in the last year, good behavior, voted on) and apply those conditions to the current set of members.
3.  We could downgrade global rights somewhat (currently everyone listed above has the power to delete the dask/dask repo)
4.  We could downgrade global rights entirely, and manage permissions at the repository level (this would be a bit of a pain, but would let us invite many more people to the organization safely)

We also need to figure out how to rearrange the Owners list.  A similar set of options exists for them as well.

I would love to know how other communities handle this.  I wonder if @TomAugspurger @ogrisel @shoyer @jakirkham @pitrou can share about the policies used in their respective communities.

**Comment by mrocklin** [comment]
Also cc @yuvipanda for a perspective from the Jupyter project in case there are things for us to learn from them.

**Comment by yuvipanda** [comment]
IIRC Project Jupyter doesn't have any formal rules, but I know @Carreau has been thinking about this from the Project jupyter side recently.

**Comment by Carreau** [comment]
Permission always become an issue especially on large orgs, one thing that we recently discovered is that issue closed by maintainer cannot be reopened by external member. In general the more people are owner(s)/admin the more detached the team will be from how occasional contributors will hit roadblocks.

In the Jupyter Org we tend to also have a couple of repositories that are private, and do not want everybody to see, so "owners" are restricted. We have a rule that commit right should get reviewed on a yearly basis, and remove commit bit if people get inactive, with the option for the inactive member to ask one the removal to be delayed for 1 year – in practice no-one really reviews.

I believe that's a bit long and 6-month may be better suited, and I think there is often a feat of vexing people to remove their right. So I would be pretty liberal with removing rights and differentiating "honorific member" from "Active member". From a security perspective the less permission is given the less risk you have – which is always good. This also allows to recognize non-GitHub contributors, and is one of the things I want for the Jupyter.

One thing I've played with (but need more time) is to have a bot with finer grained permissions, so you could for example only give tagging permissions to someone (at-mention bot + tags).

Sorry if this answer was potentially useless by raising more questions than giving answers.

**Comment by TomAugspurger** [comment]
Pandas' policy is at https://github.com/pandas-dev/pandas-governance/blob/master/governance.md#core-team-membership I think we modeled it off Jupyter's. We don't regularly review the list of members to see if anyone has become inactive.

I've been happy with the process of adding new members.

No thoughts on the old & inactive members / owners.

As I general rule, I prefer to have the least amount of privileges necessary. This is a minor annoyance, as I think some CI services require elevated permissions for certain tasks, but it seems like a worthwhile tradeoff.

**Comment by pitrou** [comment]
CPython's policy is at https://devguide.python.org/coredev/ . Basically once someone has been promoted core developer, they remain so eternally, unless they specifically ask to lose their rights. There is no formal voting procedure, it's more of an approval- and consensus-based mechanism. I wouldn't say it's necessarily a good example to follow, though.

**Comment by jcrist** [comment]
Just to add another data point, SymPy's policy is to review people with commit rights ~once a year, and remove everyone that hasn't been active. There's a single group with commit rights to everything, and a few smaller groups that have subsets of privileges.

My personal thoughts are that we should be liberal about giving commit rights to good active contributors, especially if we subset those rights per repo. I also think it's good to periodically cull the membership list to only active contributors, but think a more lax policy of "ask them if they still want commit rights if they haven't been active in a year or so" makes more sense, rather than just removing them. How to codify that in governance documents I'm not sure :).

**Comment by martindurant** [comment]
Transcribing discussion comments:

I notice the number of bigger repo/groups that seem to allow commit rights to persist indefinitely, even if they have thoughts around how to remove those rights.

Having to approach people to requests if they want to maintain membership, or having a yearly review of "active" members (these are suggestions around) comes with a bureaucratic overhead. Someone needs to be in charge of it.

Similarly, if we want to have a process around deciding repository "owners" (as opposed to committers), because we don't want anyone to accidentally delete everything, then this is a process that we actually have to implement.

**Comment by pitrou** [comment]
> My personal thoughts are that we should be liberal about giving commit rights to good active contributors, especially if we subset those rights per repo.

I would qualify that by saying that reviewing is at least as important as contributing code. Commit right holders definitely should IMHO be skilled reviewers, such that they ensure that overall quality doesn't regress.

> think a more lax policy of "ask them if they still want commit rights if they haven't been active in a year or so" makes more sense, rather than just removing them.

Agreed, especially when people contribute as volunteers.

**Comment by jakirkham** [comment]
Probably will save any longer thoughts for the next meeting. That said, the comments above have done a pretty good job covering the subject.

Would add that from a management perspective, it helps to make permissions a bit more uniform by making teams and giving the teams specific permissions as opposed to giving people commit permissions on specific repos. It also helps with coordinating cross repo fixes especially as the org grows. Not to mention is more flexible as different people come and go on different teams.

Also would agree that asking inactive people annually about whether they still want to be active is reasonable. Wouldn't want us to be doing this without asking. :) More generally feel that asking about removals (or even additions) normally are best through more private forms of communication (e.g email). Though that might be obvious.

conda-forge has a bit of a graduating structure for teams. Namely one spends some time reviewing new recipes and then can be promoted to a larger role. Each step of this is discussed with core. Though there are thematic teams that don't fit this model (docker, webservices, etc.), which don't get the same level of discussion typically. Not that we should take on this model, but there could be things to learn from.

Whatever we decide, it would be to document it somewhere. :)

**Comment by cowlicks** [comment]
:+1: Feel free to remove my access. But can I remain a member in the organization? I'd like to be a member so can keep the little profile badge, I think it is a cute token. Others might feel the same way.

**Comment by mrocklin** [comment]
OK, to push things along I'll make the following proposal.  

### Removing permissions

People's permissions can be removed in a two-step process:

1.  After a year of inactivity they are sent a private message noting that they have been inactive and asking if they'd still like to maintain their permissions.  No response will default in removal of permissions
2.  After two years of inactivity their permissions are removed regardless

We intentionally call out that "activity" can mean a great many things including but not limited to writing code, documenting, being active on issues, supporting users, etc..  Activity should be more than token events to maintain permissions

Any owner may temporarily remove permissions of any non-owner if there is some reason to do so.  A consensus of owners can remove permissions of anyone long-term

### Owners

I'll arbitrarily suggest the following set of people with ownership privileges 

- Antoine Pitrou @pitrou (Two Sigma)
- Jim Crist @jcrist (Anaconda)
- John Kirkham @jakirkham (HHMI/Janelia)
- Martin Durant @martindurant (Anaconda)
- Matthew Rocklin @mrocklin (Anaconda)
- Olivier Grisel @ogrisel (Inria)
- Stephan Hoyer @shoyer (Google)
- Tom Augspurger @TomAugspurger (Anaconda)

New owners are made by consensus of previous owners.

### Members

We remove default write and destroy privileges from members.  We hope that by making permissions more granular that they will be granted more frequently.

New members can be made by any owner if the following criteria are met: 

1.  The owner thinks it's a good idea
2.  Some other owner employed by a different company thinks it's a good idea
3.  The new member has supported the project several times, either through PRs, handling other people's issues, diagnosing important problems, etc..
4.  The new member demonstrates some degree of familiarity of open source practices and online courtesy 

Members can be given write privileges to any repository by an owner by the above conditions and the following:

1.  The lead maintainer of that repository think's it's a good idea
2.  The member has demonstrated technical familiarity with git and github (and so, for example, is unlikely to accidentally mess with history or merge PRs in an unclean state)

In the case of the more critical repositories (dask/dask, dask/distributed) then at least three owners should agree to give privileges.

### Teams

We acknowledge that write permissions to individual projects may be better handled by teams.  Team membership will be handled similar to write permissions.

### Exception Handling

If for some reason something above breaks or a conflict arises then @mrocklin 's decision will break deadlocks.

### Final comments

Feedback on this is welcome.  It would be nice to eventually formalize this and other information into some sort of governance document.  If people want to have a proper meeting about these sorts of things then please speak up.

**Comment by martindurant** [comment]
One missing piece: whose responsibility is it to police/enforce the reasonable rules we may agree on.

**Comment by koverholt** [comment]
I am okay with being converted to an ordinary member of the Dask org.

Thanks to everyone for their ongoing work in this community and for organizing this clean-up effort and policy.

**Comment by mrocklin** [comment]
> One missing piece: whose responsibility is it to police/enforce the reasonable rules we may agree on.

It seems like anyone *can* police by raising an issue, pointing to this document, waiting a suitable time for objections to clear and then acting.  This can become a problem if no one wants to do this.  I'm happy to take on the role of enforcer for the time being.  I'm also happy to find a replacement when necessary.

**Comment by teoliphant** [comment]
Great job on organizing governance.  I am happy to have helped in some small way Dask get off the ground.  At this point, I can be removed from the "owner" role.  I would like to stay a member as I talk about Dask quite a bit and want the affiliation.

**Comment by mrocklin** [comment]
Thanks @teoliphant and @koverholt for checking in here.  I really appreciate it.

**Comment by mrocklin** [comment]
Does anyone have further concerns on the propsal in https://github.com/dask/dask/issues/3223#issuecomment-371475223 ?

If possible I would like to get some acknowledgment from those listed as new Owners with either a thumbs up or thumbs down on this comment.  Suggestions and alterations would be quite welcome as well.

**Comment by jakirkham** [comment]
I think it would be helpful to see this info moved into some appropriate repo. Naively thinking a `governance` repo, but maybe another repo/name would be better suited.

**Comment by TomAugspurger** [comment]
+1 to the list in #3223

**Comment by mrocklin** [comment]
@pitrou and @ogrisel any feedback?

**Comment by pitrou** [comment]
Sorry for the delay. I am fine with the proposed organization.

**Comment by mrocklin** [comment]
OK.  We've gotten positive feedback from all previous and future owners.  I've gone ahead and changed the following in GitHub settings.

1.  Moved @teoliphant and @koverholt from owner to member role
2.  Moved @jcrist @TomAugspurger @martindurant @pitrou @ogrisel @jakirkham @shoyer to the owner role
3.  Removed automatic write-everywhere, delete repositories, and change visibility permissions from members

I think that the next steps are the following:

1.  Add new members and teams, now that we can do more granular permissioning
2.  Write up the general policy above and push it into a new dask-governance repository (which should hopefully grow as time goes on)

**Comment by mrocklin** [comment]
A couple meetings ago I brought up the idea of starting to send out membership invitations to people who have been active in the project.  It became clear that we didn't have a good threshold on when this should happen.  What does membership mean for us?  When should we extend it?  We have a technical process for doing to above but no guidelines.  

What are good guidelines for when someone should be recommended for membership in the Dask organization?

**Comment by TomAugspurger** [comment]
Agreed with all of those member traits.

**Comment by jakirkham** [comment]
Same as my GitHub name :)

**Comment by jakirkham** [comment]
Should we do the same with Distributed?

**Comment by jakirkham** [comment]
> One more thing on permissions: who has the ability to upload to PyPI and merge PRs on conda-forge. I think those should be the same as the owners.

Opened PRs at `dask-core`, `distributed`, and `dask` feedstocks to provide permissions to everyone who has owner permissions in the Dask org. Many people were already on these lists. So each of these adds a few people not on those lists. Have pinged anyone added in those PRs. If you were pinged, please let us know whether those are ok, in the relevant PR(s), and we can proceed from there.

xref: https://github.com/conda-forge/dask-core-feedstock/pull/16
xref: https://github.com/conda-forge/distributed-feedstock/pull/56
xref: https://github.com/conda-forge/dask-feedstock/pull/41
