### ISSUE TITLE
Requirements for 1.0.0 release

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3226]
We're currently bumping along in the 0.X series.  What requirements would we have before releasing Dask 1.0?

**Comment by shoyer** [comment]
@jakirkham I agree, the duplication between dask and dask-distributed for threaded computation is unfortunate. Distributed is likely strictly more functional and some of those functions would be welcome for core Dask collections (e.g., https://github.com/dask/dask/issues/3235), but it comes at the price of more required dependencies (Dask itself works with little more than the standard library).

**Comment by lijose** [comment]
I have a suggestion :
If you can introduce temporary variables in dask dataframe it will be more useful when used as an ETL.

Sample Scenario:
1) Select a list of columns from source data frame  
	natural_keys = [col1, col2, ...]
2) Apply MD5 function after merging all columns as string and add to temp column the source dataframe  ie  source_df.cdc
3) Select same set of columns from target data frame 
4) Apply MD5 function after merging all columns as string  and add to the target dataframe 
 ie.target_df.cdc 
5) Compare the cdc column between source and target data frame and set a temp column to specify flag
	like  value not matching : 'U'  (update)
		  value matching    :   'NA' (Ignore)
		  target.cdc is null : 'I'  (Insert)
6)Delete target df where source df.flag = 'U'
7)Load source df with flag = 'I' and 'U' to target df

In above scenario step 2,4 and 5 needs to have a temp variable and no need to save its value in hard disk . 
As you can see the variables saves memory too since data is compared using hashed string rather than complete data set

**Comment by mrocklin** [comment]
Thanks for the thought @lijose .  Can I ask that we move that particular feature request to a separate issue?  I would like to avoid getting too detailed in this issue if possible.

Thanks!

**Comment by jakirkham** [comment]
> I agree, the duplication between dask and dask-distributed for threaded computation is unfortunate. Distributed is likely strictly more functional and some of those functions would be welcome for core Dask collections (e.g., #3235), but it comes at the price of more required dependencies (Dask itself works with little more than the standard library).

It's true, @shoyer. Though I think there is some value gained by getting to the bottom of this. Even if the conclusion is we only copy a few things around in the end. Have moved this to issue (  https://github.com/dask/dask/issues/3237 ) so we can discuss further.

**Comment by lijose** [comment]
@mrocklin Kindly do the necessary.  
Thank you for considering my suggestion

**Comment by mrocklin** [comment]
@jcrist @TomAugspurger @jakirkham and I met in person and discussed this issue.  Two issues arose that would be good to fix before a major release

1.  A configuration system that did a better job of centralizing configuration to be accessible in a single place while also allowing better extensibility #3367 
2.  Replacing the `get=` keyword with names like threads, processes, synchronous, and distributed

**Comment by mrocklin** [comment]
Also cc @mahmoud who had thoughs on moving away from [zero based versioning](http://0ver.org/)

**Comment by mahmoud** [comment]
Haha yeah, @mrocklin and I had a fun chat about alternatives to 0ver at AnacondaCON. I guess I like offering up [CalVer](https://calver.org/) as an option to take under consideration, especially for larger applications with a bigger API surface area that is better taken holistically. 

[The site](https://calver.org) kind of speaks for itself, so I'll summarize *very* briefly: there's definitely [precedent at all levels of project](https://calver.org/users.html) (Ubuntu 16.04, C++ 11, Fortran 77, [manylinux](https://www.python.org/dev/peps/pep-0571/)) and it works really well for software with multiple concurrently-supported versions, as a lot of larger/business applications end up having.

Happy to answer questions or help with version scheme design. Keep up the good work toward a major release!

**Comment by mrocklin** [comment]
Note that the two previously mentioned blocking issues, configuration and replacing get= are implemented in pending pull requests.  I plan to issue a bugfix release soon, then merge those PRs so that they're in master for a while, and then probably issue another 0.X.0 release with deprecations before releasing 1.0.0.  If there are any other hard constraints to this process I encourage people to speak up.

**Comment by jakirkham** [comment]
Should we include dropping [`dask.array.learn`]( https://github.com/dask/dask/blob/0.17.5/dask/array/learn.py )? We could make a separate patch release, 0.17.6, that adds a big warning to that file encouraging users to move to `dask-ml`.

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
IMO, that doesn't need to wait for anything special. I suspect it isn't
getting any use.

**Comment by jakirkham** [comment]
Ok, added PR ( https://github.com/dask/dask/pull/3580 ) to just drop it.

**Comment by jakirkham** [comment]
Would add that we should flip `token` and `name` in [`map_blocks`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.core.map_blocks ). These do the opposite thing from what a user would expect (though there are historical reasons for it). 1.0.0 would be a good opportunity to fix this sort of issue since it is a breaking change.

**Comment by mrocklin** [comment]
I'd like to revisit this.  Some larger issues were mentioned

1.  Stabilize around a new config API
2.  Replace get= with scheduler=

and some collection-specific issues

1.  Replace name and token in `da.map_blocks`

These have all been resolved.  Is there currently any objection to cutting a 1.0 release?

**Comment by TomAugspurger** [comment]
No objections from me.

Has there been any discussion about what our version policy or release
schedule will be going forward? Will Dask adopt semver, or keep a rolling
deprecation cycle like NumPy?

**Comment by mrocklin** [comment]
I don't think any conversation like that has occurred.

**Comment by TomAugspurger** [comment]
This seems like a decent place for it, so what are people's thoughts?

On versioning, I don't really have a preference. Given the tight ties between the Dask & NumPy communities, the familiar rolling deprecation cycles may be most appropriate.

There was a short discussion on calver in https://github.com/dask/dask/issues/3226#issuecomment-381291602, which I missed in my quick skim earlier. Other projects (pip, manylinux) are adopting it.

(Side-note, this is a good topic for a meeting like https://github.com/dask/dask/issues/3854, if anyone subscribed to this thread has feedback on that)

**Comment by jcrist** [comment]
> I'd like to revisit this. Some larger issues were mentioned
>
>  1.   Stabilize around a new config API
>  2.    Replace get= with scheduler=

Both of those were included in release 0.17.5. We're now at release 0.18.2. When I removed deprecation warnings in #3841 I left these warnings because they were major changes that were likely to affect a large portion of users, and we hadn't had at least one full major release cycle (wouldn't want to remove them until a 0.19.0 came out). The question is - do we want to remove these deprecation warnings before releasing 1.0? And if so, should we release 0.19.0 beforehand to give a full release cycle for the deprecations?

Personally I feel fine releasing 1.0 now and moving on, I think too much stress is put on a 1.0 release, but could also see the argument to finish up removing old apis before the release.

**Comment by jcrist** [comment]
> On versioning, I don't really have a preference. Given the tight ties between the Dask & NumPy communities, the familiar rolling deprecation cycles may be most appropriate.

I also have no strong preference, but am more familiar with the rolling deprecation cycle model (and usually assume that in projects).

**Comment by mrocklin** [comment]
OK, I think that our current state is fine to release as 1.0.  Some questions on logistics:

1.  Do we cut a 1.0 from current state, or do we do a 0.20 release, wait a bit, and then release as 1.0?
2.  In writing an announcement there are a few different approaches we can take.  I'm inclined to go with a message like "To us 1.0 means usable in production.  That's clearly been the case for Dask for a long time.  This release is nothing special except for us recognizing that.  We plan to behave just like before."   

    Any objections to this messaging?
3.  For future versions it seems like most people expressing opinions currently prefer the rolling version semantics that we do today (and is done by numpy, pandas, sklearn, ...).  I'm happy with that.  

Given no further feedback I'll cut a 1.0 from current state, and issue a short blogpost talking about versions generally.

**Comment by martindurant** [comment]
Given 14 days since 0.19.4, I'm OK with going straight to 1.0.

I agree with the sentiment of the message, but think its a bit terse as given.

Yes, would stay with the current release process and cadence. This should be stated in the docs.

**Comment by mrocklin** [comment]
Here is a draft blogpost.  There is plenty more we could talk about, but I thought I'd put this up here now: https://github.com/dask/dask-blog/pull/4

**Comment by mrocklin** [comment]
Another alternative would be to move the decimal place one point to the right.  Currently our version number is `0.20.0` .  Our next version might be `2.1.0`.  This sort of skips the 1.0.0 hurrah and makes it easier to bump the version from 2->3 rather than 1->2.

**Comment by shoyer** [comment]
No strong opinions from me, though if you forced me to pick I'd make a 1.0
release.

**Comment by mrocklin** [comment]
I'd be curious to hear more about your thinking on that @shoyer .

**Comment by shoyer** [comment]
Despite your well intentioned blog-post, I like 1.0 as a marketing
opportunity.

**Comment by mrocklin** [comment]
Heh, fair enough :)

I would also be very happy to defer to someone else if they wanted to write
up the 1.0 blogpost.  Honestly I think that having other people than me
write that would also be a pretty positive signal in line with that message.

**Comment by jrbourbeau** [comment]
I'm also in favor of a 1.0 release. I agree with @shoyer that it would be a good marketing opportunity for Dask. Also, it's subjective, but it seems a little unnatural to me to skip ahead to 2.X

**Comment by TomAugspurger** [comment]
I haven't really been able to improve on the draft blogpost at https://github.com/dask/dask-blog/pull/4. We can still celebrate the release as marking a major milestone and all that, but I think that the tone of the post accurately reflects the state of the project.

**Comment by mrocklin** [comment]
I plan to push a 1.0 pre-release to PyPI on Friday, let it simmer until Monday or Tuesday, and then push.

**Comment by mrocklin** [comment]
Also, just verifying, but I can just tag something as 1.0.0.rc1 and push that to PyPI right?  There aren't any special flags when creating an rc/dev/beta build?

**Comment by shoyer** [comment]
That's right, pypi parses version numbers for determining pre-releases.
(and our version number is generated by versioneer)

**Comment by jakirkham** [comment]
Would it be possible to hold off until next week after the holiday?

**Comment by mrocklin** [comment]
I guess my thought was that an release candidate wasn't a big deal.
Certainly I wouldn't release 1.0 over the holiday.

**Comment by mrocklin** [comment]
But if there are concerns, then yes I can wait.

**Comment by mrocklin** [comment]
OK, I'm inclined to just push a 1.0.0 release directly at this point.  If there are no objections then i'd like to do this Tuesday or Wednesday.

**Comment by mrocklin** [comment]
The latest micro-release seems to be good, and there hasn't been much churn since then.

**Comment by mrocklin** [comment]
Releasing 1.0.0 to PyPI in one hour if there are no objections

**Comment by mrocklin** [comment]
Pushed dask/dask 1.0.0 and dask/distributed 1.25.0 to PyPI
