### ISSUE TITLE
Add custom pytest flag to run tests with the synchronous scheduler where it makes sense

### ISSUE THREAD

**Issue by cpcloud** [dask/dask#323]
I often find myself writing these two lines whenever i want to debug something:

```python
import dask
<dask thing>.compute(get=dask.async.get_sync)
```

Fortunately pytest has a way to add custom command line options. We could add something like this:

```sh
$ py.test --scheduler=get_sync
```

or maybe

```sh
$ py.test --get=get_sync
```

pytest docs: https://pytest.org/latest/example/markers.html#custom-marker-and-command-line-option-to-control-test-runs

Other suggestions for syntax welcomed

**Comment by cpcloud** [comment]
There also might be a better way to debug things so that we wouldn't need this

**Comment by mrocklin** [comment]
In many cases I think that we should be using the synchronous scheduler in tests anyway.

**Comment by mrocklin** [comment]
In practice we're pretty good about using get_sync where appropriate.  Closing.
