### ISSUE TITLE
Return file names on `to_parquet`

### ISSUE THREAD

**Issue by xhochy** [dask/dask#3231]
For dealing with the dataset generated with `to_parquet`, I want to know the names of the generated files afterwards. For now, I have the practical solution of just making an `ls` on the resulting directory. Instead of doing this (as this may be costly in environments like S3 or Azure Blob Storage), I would like the jobs to return a list (dask.bag would also be ok) of the resulting file names.

Implementation-wise I know what I have to do but API-wise I'm unsure what the best fitting solution for dask would be. Of the top of my head I would add a parameter `to_parquet(return_storage_names=True)`.

cc @fjetter

**Comment by martindurant** [comment]
An interesting idea. In general, I am in favour - although the number of parameters you can pass to to parquet methods (as with csv) is now rather large.

**Comment by jcrist** [comment]
We could probably make this work without an api change, as currently:
- If `compute=True`, this returns None
- If `compute=False`, this returns a list of delayed objects that evaluate to None.

If we change the `None` to the resulting filename this should be fine and I wouldn't consider it a breaking change (no one should be relying on a method returning `None`). `to_csv` already does this.

That said, there's a few complications:
- By default, there's a 1:1 mapping between partition and filename, so each partition would return a single filename
- If `partition_on`, there can be multiple files per partition, which complicates things. I'm not sure what would be expected here.
- If `append=True`, the just written filenames aren't the only files in the dataset. What would you return then?
- Parquet datasets also include metadata files that are useful for efficient reads without scanning every file in the dataset. The metadata file wouldn't be present in this list (or would it?), which feels a bit off.

**Comment by xhochy** [comment]
> If partition_on, there can be multiple files per partition, which complicates things. I'm not sure what would be expected here.

I would make `to_parquet` always return a list of filenames, thus the `partition_on` and standard case don't vary. This makes it behave differently in comparison to `read_csv` but consistent independent of the flags set on `to_parquet`.

> If append=True, the just written filenames aren't the only files in the dataset. What would you return then?

Only the newly created files, i.e. we could have the definition that each task that writes Parquet files should return the path to its files. In the append mode, if you are interested in the list of files, you probably already have this list in memory, thus we don't want the append call to make extra calls to retrieve them.

> Parquet datasets also include metadata files that are useful for efficient reads without scanning every file in the dataset. The metadata file wouldn't be present in this list (or would it?), which feels a bit off.

These metadata files are always written (depending on the chosen engine) and they are a fixed set of files. Checking for their existence is acceptable (at least in my situation).

**Comment by mrocklin** [comment]
Sorry for the long delay.  Having `to_parquet` return filenames sounds good to me.  @xhochy if you're still interested in this (which after this long of a delay would be surprising) a PR would be welcome.

**Comment by xhochy** [comment]
Currently I'm not interested anymore on this as we don't use `to/from_parquet`. I can reopen if this pops up again.

**Comment by manugarri** [comment]
Maybe we can implement this following the [read_csv PR](https://github.com/dask/dask/pull/3908/files) ?

**Comment by martindurant** [comment]
This should be possible following https://github.com/dask/dask/pull/4995 . We need that PR, because in the case of value-partitioning, there has been no way for the calling code to know what files were created by the pyarrow engine.
