### ISSUE TITLE
BUG: inline fails with user supplied keys

### ISSUE THREAD

**Issue by dancollins34** [dask/dask#3232]
```python
from dask.optimization import inline

class MyKey:
    def __init__(self):
        self.name = "a"
    def __hash__(self):
        return hash(self.name)
    def __eq__(self, other):
        return isinstance(other, MyKey)

dsk1 = {
    MyKey(): 3,
    "x": (lambda y: y, MyKey())
}

dsk2 = inline(dsk1) # This line fails
```

This throws:

  File ".....\dask\optimization.py", line 278, in inline
    val = subs(val, item, keysubs[item])
  File ".....\dask\core.py", line 310, in subs
    if len(arg) == len(key) and all(type(aa) == type(bb) and aa == bb
TypeError: object of type 'MyKey' has no len()

**Comment by dancollins34** [comment]
potential patch:

on line 306-312, replace

```python
elif type_arg is type(key):
    # ndarray relevant block
```

with 

```python
elif type_arg is np.ndarray:
    # ndarray relevant block
elif type_arg is type(key):
    if arg == key:
        arg = val
```

and the requisite "import numpy as np" at the top of the file.

**Comment by mrocklin** [comment]
We might also consider reducing the spec to only allow keys that are json-serializable.

**Comment by mrocklin** [comment]
I think that the distributed scheduler already makes this assumption

**Comment by dancollins34** [comment]
I don't think so? If so it doesn't enforce it.  I've been able to use user-class keys when submitting the task graph just fine, its just inline/subs that is causing issues.  Regardless, the code as written makes a bad assumption: that if an argument is not a task and it is not a list, and its not a constant, and its type is equivalent to that of the substituted key, it must  then it must be an ndarray.  This is not a good assumption to make.  In fact, this change would only be a reversion of this incorrect assumption made in #2457.

**Comment by mrocklin** [comment]
If you're willing I recommend submitting the proposed patch and the fail case as a PR.  I suspect that it will be easier to discuss seeing the changes in context.

> I've been able to use user-class keys when submitting the task graph just fine, its just inline/subs that is causing issues. 

Hrm, that's interesting.  I'm glad to hear it.

> and the requisite "import numpy as np" at the top of the file.

Dask core doesn't explicitly depend on NumPy, so we'll have to be somewhat clever about this.

**Comment by dancollins34** [comment]
> If you're willing I recommend submitting the proposed patch and the fail case as a PR. I suspect that it will be easier to discuss seeing the changes in context.
I'll do this tonight.
> Dask core doesn't explicitly depend on NumPy, so we'll have to be somewhat clever about this.
if typearg.__name__ == "ndarray": perhaps?

**Comment by mrocklin** [comment]
This seems to have gone stale.  Closing.

If there are update please feel free to respond here and we'll reopen.
