### ISSUE TITLE
Launching tasks within tasks without using the distributed scheduler

### ISSUE THREAD

**Issue by shoyer** [dask/dask#3235]
The pattern described here with `dask.delayed` doesn't actually seem to use/require the distributed scheduler in any way:
https://distributed.readthedocs.io/en/latest/task-launch.html#dask-delayed

Is there any reason not to encourage using this pattern within core dask collections? I can think of some examples where this would be useful, e.g., for indexing dask arrays with dask arrays in https://github.com/dask/dask/pull/3210.

**Comment by mrocklin** [comment]
One issue would be oversubscription of hardware because of using too many threads.  The distributed scheduler has cleverness that avoids this sort of thing.  

Note that *if* you can install a modern version Tornado (which I understand is a big *if* in some places :) ) the dask.distributed scheduler is very lightweight when created with 

    client = Client(processes=False)

**Comment by jakirkham** [comment]
If one doesn't start a `Client` instance, what happens to this example? Does it just block in the middle of the task? Is it able to start the next task? Other things to consider for this case?

**Comment by mrocklin** [comment]
My guess is that it would create a new `ThreadPool` and run the sub-computation as a blocking computation within this task.

**Comment by shoyer** [comment]
> My guess is that it would create a new ThreadPool and run the sub-computation as a blocking computation within this task.

Yeah, this is a non-starter. Now that I think about it, I recall running into these issues before.

It might be worth noting somewhere in that example why this isn't a good idea with non-distributed dask.

**Comment by mrocklin** [comment]
Hrm, you probably *could* make this work with the modified `ThreadPoolExecutor` in dask.distributed rather than a vanilla ThreadPool.  It has enough of the `secede`/`rejoin` logic to make this work.  

This would take modest effort though.

**Comment by mrocklin** [comment]
I'm going to go ahead and close this.  It doesn't look like anyone cares enough about this to do this work near-term.  The distributed scheduler also offers this functionality.

**Comment by jakirkham** [comment]
In a Python 3.5+ code base, would this be more achievable using async?

**Comment by mrocklin** [comment]
No.  There's nothing we can do with async/await tahat we couldn't do with tornado.

Why do you ask @jakirkham .  Is this blocking you somewhere?
