### ISSUE TITLE
Can we do "daskification" of a pointwise array function operating on numpy arrays?

### ISSUE THREAD

**Issue by pp-mo** [dask/dask#3244]
See here : 
https://stackoverflow.com/questions/49096771/dask-array-conversion-of-a-pointwise-array-operation

And note especially the motivating example / stopgap solution here : 
https://github.com/SciTools/iris/pull/2964

If there isn't a neat way to do this, can we provide one ?

**Comment by pp-mo** [comment]
Solution is da.map_blocks

**Comment by mrocklin** [comment]
A bit more high-tech, but dask.array also supports numpy ufuncs natively.
You can always create a ufunc and it will operate well on both numpy arrays
or dask arrays without any special consideration on your end.

**Comment by pp-mo** [comment]
> You can always create a ufunc

Given a function on arrays, I think the only automatic way of constructing a ufunc would be by applying `frompyfunc` ?
That does work, but of course is hopelessly inefficient because is calls the original, array-oriented function once per point.

Given the freedom to rewrite the original operation, I think it would probably be easier to rewrite it in a dask-compliant form than to recast it as a ufunc.
