### ISSUE TITLE
`df.values` has unspecified length

### ISSUE THREAD

**Issue by stefanv** [dask/dask#3251]
After constructing an array of values from a dask DataFrame, the length is unspecified.

```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame.from_dict({'A': [1, 2, 3], 'B': [4, 5, 6]})
df = dd.from_pandas(df, npartitions=2)

print(df.values.shape)
```

Produces:

```
(nan, 2)
```

**Comment by mrocklin** [comment]
That's correct.  Dataframes don't maintain their lengths.  Even in your case where we could maybe guess by looking at the maximum index value (which we *do* keep track of) it's hard to guarantee that that index value matches the length.

If we wanted to support this would would need to track more metadata than we currently do.  This is possible, but expensive to build and maintain.

**Comment by stefanv** [comment]
Just to give a bit of background: I was helping someone apply `scipy.stats.zscore` to rows of data, so was trying to inspect some of the values, but because the length is unknown, you cannot slice `df.values`:

```
ValueError: ('Arrays chunk sizes are unknown: %s', (nan, 2))
```

This was a bit of a surprise, and doesn't suggest an easy avenue for recovering.

I'l close this specific issue for now, thanks for clarifying.

**Comment by stsievert** [comment]
I also ran into this issue. I'm trying to get the first dimension of an array, and these arrays can possibly be passed in as `dataframe.values`. That is, I had to code similar to

``` python
def foo(X: da.array):
    n, d = X.shape
    assert not np.isnan(n), "n cannot be nan"

ddf = dd.read_csv(...)
print(ddf.values.shape)  # prints "(nan, 19)"
f(ddf.values)
```

My solution involved moving to the below because `X` could be a dask array:

``` python
def foo(X: da.array, n=None):
    _n, d = X.shape
    if not np.isnan(_n):
        n = _n
    if n is None:
        raise ValueError
    return function_where_n_not_nan(n, d, X)

print(ddf.size.compute())  # prints "64"
f(ddf.values, n=ddf.index.size.compute())
```

**Comment by mrocklin** [comment]
Yeah, generally speaking when dealing with dataframes we won't know how many elements are there without first computing the dataframe.  This can be expensive (imagine trying to count all of the `"\n"` characters in a large pile of CSVs quickly).  If possible I would first verify that you actually *need* the exact length.    In my experience using `len(df)` is something we're used to reaching for, but not something that we strictly need.  Your case may differ though.

**Comment by stsievert** [comment]
> using `len(df)`.

Thanks for the tip. I think that should be sufficient – I only need a random row from the dataframe values.

But, I suppose `DataFrame.values.sample` and `Array.sample` would resolve this problem. I can put in a PR for this.

**Comment by mrocklin** [comment]
Why do you need a single random row?  Note that any operation on dask.dataframes will have non-trivial overhead (milliseconds to 100s of millseconds depending on scale).  If this were the basis for any kind of computational algorithm then I would recommend taking a step back and reconsidering your objective.

**Comment by stsievert** [comment]
I need access to random rows for a mini-batch SGD implementation. Typical implementations sample 64–1024 random rows, but it'd be fair to increase that if the overhead is significant. I'll expand more upon my objective when I put in the PR (which is related to https://github.com/dask/dask-ml/issues/146).

**Comment by mrocklin** [comment]
Given the number of iterations that I suspect are needed for mini-batch SGD my guess is that we don't want to touch the entire dataframe every cycle for 1k rows.  I can think of a few alternatives:

1.  Grab a *much* larger sample from dask and then iterate through it locally updating your parameters
2.  Shuffle your data a bit beforehand (for various definitions of "a bit") and then walk through your data sequentially
3.  Make sure that you're getting futures samples asynchronously to overlap communication and computation using APIs like [futures](http://dask.pydata.org/en/latest/futures.html)

But, given these alternatives my guess is that other alternatives exist.  I'm now curious what kinds of parallel SGD algorithms exist.

**Comment by mrocklin** [comment]
Ah, I see that you may already have thoughts on parallel SGD.  My apologize if I'm saying dumb things above: https://stsievert.com/research/2017/parallel-sgd.pdf

**Comment by stsievert** [comment]
> Shuffle your data a bit beforehand (for various definitions of "a bit") and then walk through your data sequentially

Perfect. That indexing method would resolve this issue. Plus, it's mentioned in section 4.1 of "[SGD tricks]", which I neglected to look at it for this issue. It looks like shuffling would have to be done every epoch (or after every data point has been seen).

Let's move this discussion to https://github.com/dask/dask-glm/pull/69

[SGD tricks]:https://www.microsoft.com/en-us/research/wp-content/uploads/2012/01/tricks-2012.pdf
