### ISSUE TITLE
Array's `vindex` shuffles dimensions

### ISSUE THREAD

**Issue by mraspaud** [dask/dask#3266]
Running this code:

```python
import dask.array as da
import numpy as np

data = da.arange(3 * 5 * 5, chunks=5).reshape(3, 5, 5)
cols, lines = np.meshgrid(np.arange(5), np.arange(5))

print(data.vindex[:, lines, cols])
```

produces the following `dask.array<reshape, shape=(5, 5, 3), dtype=int64, chunksize=(5, 5, 1)>`

meaning the dimensions go from (3, 5, 5) to (5, 5, 3) even if I asked the first dimension to remain unchanged.

Sorry if I made a trivial mistake, but this looks buggy to me...

Thanks for a great lib !

Dask 0.17.1, pythons 2.7.5 and 3.6.3

**Comment by mraspaud** [comment]
For completeness, the same behaviour shows in 2D arrays with 1D indices:
```python
data = da.arange(3 * 5, chunks=5).reshape(3, 5)
data.vindex[:, [1, 2, 3, 4]]
# -> dask.array<vindex-merge, shape=(4, 3), dtype=int64, chunksize=(4, 1)>
```

**Comment by davidh-ssec** [comment]
If the result is in the right order but just the wrong shape then I vote for this line being the problem: https://github.com/dask/dask/blob/master/dask/array/core.py#L3500

**Comment by shoyer** [comment]
This is the right behavior, which intentionally deviates from numpy's advanced indexing when you use slice objects. 

Please read the `vindex` proposal in https://github.com/numpy/numpy/pull/6256/files for an explanation. NumPy's advanced indexing orders output dimensions in an "intuitive" way when it can, but it fails in edge cases which makes it much harder to program with.

**Comment by davidh-ssec** [comment]
@shoyer If I'm reading this correctly (and I'm not even close to understanding most of it), in our specific case here we would want `oindex`? But also in our specific case we can get the same result if we tranpose (`.T`) the result of `vindex`?

...or am I completely wrong?

**Comment by shoyer** [comment]
I'm not sure. What result do you actually want?

But yes, the result of `vindex` differs from indexing numpy arrays only by transposes.

**Comment by davidh-ssec** [comment]
In the simpler example:

```
data = da.arange(3 * 5, chunks=5).reshape(3, 5)
data.vindex[:, [1, 2, 3, 4]]
# -> dask.array<vindex-merge, shape=(4, 3), dtype=int64, chunksize=(4, 1)>
array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# we expect:
# shape = (3, 4)
array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

```

**Comment by shoyer** [comment]
yes, you can transpose

**Comment by davidh-ssec** [comment]
Ok so `data.oindex[:, [1, 2, 3, 4]]` for the above case should produce our expected result?

**Comment by shoyer** [comment]
oindex does not exist yet, in either numpy or dask.

**Comment by davidh-ssec** [comment]
I know. I'm wondering if when it does exist and if I'm understanding the PR you linked to it should produce our expected result. Just curious, I know we can't use it yet.

**Comment by mraspaud** [comment]
Yes, my bad, the vindex doc states it explicitely http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.vindex

Sorry for the noise
