### ISSUE TITLE
read_parquet needs to finish first, if it's the second time it's been called

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#3268]
Sorry I can't share my data, but here's my code and what I see.

Here's a chunk of code

```python
import dask.dataframe as dd
df = dd.read_parquet(FILES, columns=['location', 'script_url'], engine='pyarrow')
df['https_location'] = df.location.str.startswith('https:')
df['https_script_url'] = df.script_url.str.startswith('https:')
df['mixed'] = df.https_location != df.https_script_url
https_mixed = df[(df.https_location == True) & (df.mixed == True)].persist()
progress(https_mixed)
```

If it's the first thing I run in a notebook, then the `read_parquet` operation gets interleaved with all the others.

If I run another chunk of code first that does similar things, then when I run this snippet all the `read_parquet` operations run first and it is no longer interleaved leading to a dramatic slowdown.

@mrocklin, you've seen this in action.

**Comment by mrocklin** [comment]
Yup, working on this at this instant.  For other dask folks that may be
curious about this, I think that we need to update our per-task
prioritization if old priorities from older computations exist.

**Comment by mrocklin** [comment]
This is fixed by https://github.com/dask/distributed/pull/1828
