### ISSUE TITLE
Dask Dataframe Delayed section docs

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3273]
Appears the last sentence of the first paragraph trails off (incomplete sentence). Not sure what was intended.

ref: http://dask.pydata.org/en/latest/dataframe-create.html

**Comment by mrocklin** [comment]
This no longer seems to be the case.  Closing.

In the future @jakirkham I also invite you to fix these things directly.  I suspect that it would be about as time-expensive for you as raising an issue.
