### ISSUE TITLE
Cannot use multiprocessing with cythonized code

### ISSUE THREAD

**Issue by hdhoa** [dask/dask#3276]
Hi

I have a problem with multiprocessing and cythonized code:  methods cannot be pickled and so it fails. The problem comes from the cloudpickle library, that cannot pickle a cython function.

I have made a small demo, just unzip the attached file in a directory and run the commands:
[test.tar.gz](https://github.com/dask/dask/files/1803842/test.tar.gz)

1. Python
python test_dummy.py
2. Cythonized code 
- python setup.py build_ext --inplace 
- python test_dummy.py

There is a pickling error
_pickle.PicklingError: Can't pickle <cyfunction DummyClass.test at 0x10cfa9c80>

For now, my very dirty fix is to overload dask multiprocessing package _dumps method before using it:
    dask.multiprocessing._dumps = pickle.dumps

**Comment by jakirkham** [comment]
Do you have `cloudpickle` installed? If not, can you please install it and retry? Thanks.

**Comment by hdhoa** [comment]
I have cloudpickle (0.4.0) installed

**Comment by jakirkham** [comment]
So I think this is a Cython bug. Issue ( https://github.com/cython/cython/issues/1606 ) in particular seems relevant. That said, it looks like it got fixed at some point.

Would try recompiling with the latest Cython (if you are in a position to do that).

If you are unable to compile the Cython code, might try adding a Python function, which can be pickled, on top of this method call. This second case is a little kludgy, but should help get things working at least.

**Comment by jakirkham** [comment]
Any updates on this @hdhoa?

**Comment by mrocklin** [comment]
Closing as non-responsive.

**Comment by jakirkham** [comment]
Could reasonably be argued to be out of scope as well. Seems it was a pickling issue with Cython functions, which while it may affect Dask use cases, is not itself an issue with Dask.
