### ISSUE TITLE
dask.distributed Client freezes after recent software upgrade.

### ISSUE THREAD

**Issue by ebo** [dask/dask#3279]
After a recent forced upgrade, nothing that uses dask.distributed now freezes and refuses to work.  I am able to replicate this with the following code from pangeo/notebooks/newmann_ensemble_meteorology.ipynb

----------------------------------
from dask.distributed import Client
client = Client(scheduler_file='/glade/scratch/jhamman/scheduler.json')
client
----------------------------------

I notice that I get messages:

    Adapting to protocol v5.1 for kernel 48f87baf-4f25-418a-9eb1-cd7ed4d7fc91

and following the net I have tried installing ipykernel  jupyter_client ipyparallel, and changing my port from 8888 to 8889 and 9012.  I have also tried re-initializing jupyer_notebook_config.py, rebooting the machine, and I cannot remember what all.  Has there been a recent change (since 4.4, or maybe I had 5.0 installed, still trying to figure that out).  Anyway, this morning everything worked fine until I installed pangeo and xarray.  Now dask.distributed is broken.

Any suggestions?

I should also note that after everything went sideways I moved my old install to the side and did a full clean install from the most recent anaconda version.  So I am currently working from a clean pangeo environment.yml install.

**Comment by jakirkham** [comment]
Issue moved to [dask/distributed #1867](https://github.com/dask/distributed/issues/1867) via [**ZenHub**](https://www.zenhub.com/)
