### ISSUE TITLE
Note optional scipy requirement

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3287]
Currently `scipy` doesn't show up as an optional requirement in `setup.py`. Mainly `scipy` is used for testing (e.g. our compatibility with things in `scipy`). So generally this is not needed outside of development.

However there are a few cases in the code like [`lu` decomposition]( https://github.com/dask/dask/blob/0.17.1/dask/array/linalg.py#L361-L362 ) or [sanity checks in `fft_wrap`]( https://github.com/dask/dask/blob/0.17.1/dask/array/fft.py#L133-L137 ) where `scipy` is a hard or at least soft requirement. Other things like support `scipy.sparse.linalg.LinearOperator` support implicitly depend on `scipy`'s behavior; so, could be impacted by changes in `scipy`.

Given this, it would be good to provide some guidelines to users as to what versions of `scipy` work in the form of an extra requirement. Naively would suggest basing this off what `scipy` version we are testing against in CI. Though would be curious to know if there are other considerations.

**Comment by jakirkham** [comment]
Any ideas on what minimum version of `scipy` we need in these cases?

**Comment by jakirkham** [comment]
Should be addressed by PR ( https://github.com/dask/dask/pull/3309 ).

**Comment by mrocklin** [comment]
*If* the features of scipy that we're using have been around for a while and we expect them to be in most installations of scipy then maybe we can just rely on standard `ImportError`s?

**Comment by mrocklin** [comment]
Has this come up in practice?  Has it affected users?  Did it cause some confusion for you in particular when trying to use Dask?

**Comment by jakirkham** [comment]
Am reacting in part to issues experienced downstream due to the lack of a version constraint for `numpy`. I don't know of any similar issues with `scipy`. However am eager to have us avoid them before others point them out to us. Hope that provides some more context.

Does the list of `scipy` features used above sound accurate? Are there others that we may be missing? Look at the docs it seems like 0.9.0+ (based on `solve_triangular`). Though we haven't tested there.

Ultimately what caused issues with `numpy` was not the dependency being listed, but the version being expected has shifted over time. Likely based on what the CIs would allow. Expect the same issue to occur with `scipy` given the 1.0 release late last year. An example use case which could run into such problems would be the discrete sine/cosine FFTs requested in issue ( https://github.com/dask/dask/issues/3250 ). The N-D discrete sine/cosine FFTs were added as part of 1.0. A full solution to this problem likely involves pinning `scipy` in CI to the oldest version we wish to support for this reason.

**Comment by mrocklin** [comment]
> Does the list of scipy features used above sound accurate? Are there others that we may be missing?

I don't know.

@jakirkham what would resolve this problem for you?  Are you asking just for a pinning in the CI or are you asking for it to be listed as a requirement for `pip install dask[array]`, or something else?  I'm not sure how best to resolve this issue.

**Comment by jakirkham** [comment]
At a bare minimum, I'd like us to document this requirement with a version constraint somehow. Other things would help verify that constraint is accurate (e.g. CI, simplifying user install, etc.).

**Comment by mrocklin** [comment]
Can you suggest where / how to document that version constraint?

**Comment by mrocklin** [comment]
Also, given the scope of Dask and its tendancy to touch many projects in different ways it seems like this goal might be somewhat larger scoped than just SciPy.

**Comment by jcrist** [comment]
For conda, we might be able to make use of the new [optional dependency requirements](https://github.com/conda/conda-build/pull/2001). It's not clear to me how to specify these though, and I can't find anything in the docs. cc @msarahan.

**Comment by jcrist** [comment]
That sounds perfect for our use case (at least for conda installations). Would this resolve your issue @jakirkham?

**Comment by jakirkham** [comment]
Would like to see it documented in the Dask source code so if this constraint changes one can see that from version to version. To be clear this is a feature that I and others use when packaging many different types of software.

**Comment by kalefranz** [comment]
The description on constrained dependencies @msarahan gave is exactly correct.  The quote is usually how I describe the concept.  The concept can also be thought of as a *reverse* dependency, allowing an upstream package to constrain a downstream package.

As a future improvement to conda, there's been discussion of using this metadata to somehow indicate "suggested" additional packages for an environment. At the moment such feature really hasn't been prioritized yet. The most complex part is probably getting the messaging right so we don't confuse users with it.

**Comment by mrocklin** [comment]
Conversation here seems to have stalled.  Closing.  Happy to reopen if folks plan to do more planning or work here.
