### ISSUE TITLE
to_parquet default compression is `None` not `snappy`

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#3288]
The pandas to_parquet method defaults to using `snappy` for compression.
However, when you don't specify compression in dask, the data is saved uncompressed.

**Comment by martindurant** [comment]
`None` was the original in fastparquet, since snappy is a dependency we didn't want to force onto people; I believe if you give None with the arrow backend, you get snappy. arrow persuaded pandas otherwise, since snappy is the default in, for example, spark (but not everywhere!). I am fine with having different defaults in different places.

**Comment by birdsarah** [comment]
I guess I was caught unawares. I wrote some pandas code, it all worked as expected, I switched it to dask and now my parquet files are huge. 

I wonder if in cases where dask intentionally, for good reasons, doesn't match the pandas API it could be highlighted in some way. 

I do see that the docstrings are different and that pandas uses snappy by default, but it's easy, as a newcomer to not fully understand the implications of the slightly different docstrings - or to not have checked them at all because the method just works....

This is pretty vague so I'm more than fine with closing this issue if there's not clear next step.

**Comment by mrocklin** [comment]
We usually conform to Pandas standards when there is no strong reason not
to do so.  Deviations from this seem to cause surprise in users.

@martindurant what are your thoughts on defaulting to snappy if snappy is
present?  Were there reasons to not do this or is this just historical?

**Comment by martindurant** [comment]
Indeed historical. The "if snappy is present" will obviously require a little logic similar to that which exists elsewhere.
