### ISSUE TITLE
FutureWarning handling fill value for masked array of datetime64

### ISSUE THREAD

**Issue by hdkire** [dask/dask#3289]
The warning occurs because dask.array.ma._concatenate calls np.unique(fill_values).
The fill value for datetime64 is NaT and cannot be compared to itself without warning.

Dask version: 0.17.1
Numpy version: 0.13.3
Python version: 2.7.14

Repro:
```
import numpy as np
import dask.array as da
import datetime

a = np.ma.masked_array([datetime.datetime.now()], [True], dtype='datetime64[us]')
d = da.from_array(a, chunks=(10,), asarray=False)
da.hstack([d, d]).compute()
```
=>
```
.../site-packages/numpy/lib/arraysetops.py:279: FutureWarning: In the future, NAT != NAT will be True rather than False.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))
```

**Comment by mrocklin** [comment]
Thanks for the excellent reproducible example.  My apologies that no one has responded to this.  My guess is that masked arrays just aren't a common topic among many of the maintainers.  I wonder if @pelson or @bjlittle care about this perhaps?

**Comment by TomAugspurger** [comment]
I can't reproduce this warning anymore with dask master and NumPy 1.17.
