### ISSUE TITLE
Mixed multi-processing and multi-threading at the same time

### ISSUE THREAD

**Issue by shoyer** [dask/dask#329]
As I spoke about with @mrocklin last night, it would be great to have the ability to simultaneously execute GIL limited tasks in a multi-processing pool and non-GIL limited tasks in a thread pool, all on the same dask graph.

**Comment by mrocklin** [comment]
This is interesting but also hard.  I suspect that it would be a separate scheduler.  One would have to invent a convention with dask graphs to annotate tasks as "to be run with threads" or "to be run with processes."  One could achieve this annotation by hijacking the key of a task with some special convention or by wrapping the task in something else.  Both of these could possibly be controlled with a context manager.

**Comment by mrocklin** [comment]
Hrm, one solution here would be to use the threaded scheduler but use the threads to launch processes.  E.g. if we have a task

    (f, a, b)

We write a function

```python
from multiprocessing import Pool
pool = Pool()

def run_in_process(func, *args):
    return my_process_pool.apply(func, args=args)
```

and then instead we might create the following task if we know we want to run it in a process instead of a thread.

    (run_in_process, f, a, b)

And so, annotating tasks to run in processes rather than in threads ends up being just adding a term.

**Comment by mrocklin** [comment]
Thoughts on this approach @shoyer ?

**Comment by shoyer** [comment]
This actually looks quite reasonable to me, and is certainly worth a try. Gzipped data files are quite common, either in hdf5 chunks or just entire files compressed.

**Comment by mrocklin** [comment]
Hrm, this is also relevant with `dask.bag.to_dataframe`.  Where we might want to wrap every task with `run_in_process`.

**Comment by mrocklin** [comment]
I'm going to ahead and say that this isn't likely to happen.  I think that we're more likely to walk around issues in other ways.  Closing for now.  Please reopen if there is further interest and will.
