### ISSUE TITLE
dask.dataframe.DataFrame.at alternative

### ISSUE THREAD

**Issue by jamesstidard** [dask/dask#3292]
Hi all,

I know `dask.dataframe` is only a subset of the pandas DataFrame API but I am wondering if it is possible to emulate the `DataFrame.at` and `DataFrame.update` methods through `dask`.

I have a `DataFrame` which has some interdependent rows; it's a tree where a rows value is determined by the sum of its children. So when updating the values I want to start at the lowest level of the tree and work up to the root so the children are all evaluated before their respective parents.

At the moment I have something like:

```python
def sum_children(node):
    children = node['children']
    is_child = df.index.isin(children)
    return df[is_child]['value'].sum()

for level_index in levels:
    this_level = df[df['level'] == level_index]
    df.at[this_level, 'value'] = df[this_level].apply(sum_children, axis=1)
```
I'm also kinda weary that my solution to summing these interdependent nodes may not be the best, so also open to any kind of restructuring ideas that may even get rid of the `apply` and/or `at`.

Thanks.

**Comment by mrocklin** [comment]
For at I would use `loc`.  We don't support mutating individual rows, so update is out.

**Comment by mrocklin** [comment]
Sorry for the late reply.
