### ISSUE TITLE
ModuleNotFoundError: No module named 'dask.bag'

### ISSUE THREAD

**Issue by BrendanMartin** [dask/dask#3295]
I'm using a Jupyter notebook, and I've uninstalled/reinstalled fresh versions of pandas and dask, but I still keep getting this error when trying to import a .py file (that imports dask) into my notebook :
```
     10 import numpy as np
     11 import pandas as pd
---> 12 import dask.bag as bag
     13 from dask import dataframe as dd
     14 from dask.dataframe.core import DataFrame as Dask_DataFrame

ModuleNotFoundError: No module named 'dask.bag'
```

It started happening right after I installed dask-searchcv. After that, dask wouldn't import, and that's when I removed dask-searchcv and reinstalled pandas and dask but now I have this error.

**Comment by jakirkham** [comment]
Could you please include some more information about how you installed and what is installed? Thanks.

**Comment by mrocklin** [comment]
Any further information here?  Closing soon otherwise.

**Comment by BrendanMartin** [comment]
I fixed it somehow. I just had to reinstall everything.
