### ISSUE TITLE
dask.dataframe map_partitions func return type?

### ISSUE THREAD

**Issue by ailurus1991** [dask/dask#3306]
Hi there,

So glad to see you guys nice work, and I'm using dask to speed up my old pandas apply by replace it with dask.dataframe's map_partitions.

Here's the example from Dask documents:

``` python
df = pd.DataFrame({'x': [1, 2, 3, 4, 5], 'y': [1.1, 2.2, 3.3, 4.4, 5.5]})
ddf = dd.from_pandas(df, npartitions=2)
def myadd(row):
    return row + 1
df["y+1"] = ddf["y"].map_partitions(myadd).compute(get=get)
```

then I got:

x | y | y+1
-- | -- | --
1 | 1.1 | 2.1
2 | 2.2 | 3.2
3 | 3.3 | 4.3
4 | 4.4 | 5.4
5 | 5.5 | 6.5

the results is good as we expected.

but if I changed the func's return datatype to string, like this:

``` python
df = pd.DataFrame({'x': [1, 2, 3, 4, 5], 'y': [1.1, 2.2, 3.3, 4.4, 5.5]})
ddf = dd.from_pandas(df, npartitions=2)
def myadd(row):
    return str(row)+"-"
df["y+1"] = ddf["y"].map_partitions(myadd).compute(get=get)
```

I got:

x | y | y+1
-- | -- | --
1 | 1.1 | 0 1.1\n1 2.2\n2 3.3\nName: y, dtype: ...
2 | 2.2 | 3 4.4\n4 5.5\nName: y, dtype: float64-
3 | 3.3 | NaN
4 | 4.4 | NaN
5 | 5.5 | NaN

So... in my previous pandas experience, the result should be:

x | y | y+1
-- | -- | --
1 | 1.1 | 1.1-
2 | 2.2 | 2.2-
3 | 3.3 | 3.3-
4 | 4.4 | 4.4-
5 | 5.5 | 5.5-

I checked Dask's document but got no thing...

**Comment by mrocklin** [comment]
The function you give to map_partitions should take a dataframe/series of many rows and return a dataframe/series of many rows.  It looks like your function was designed to take a single row and return a single result value.  You probably want the `apply` method instead.

    df["y+1"] = ddf["y"].apply(myadd).compute()
