### ISSUE TITLE
custom node names in graphs

### ISSUE THREAD

**Issue by eddienko** [dask/dask#3318]
Custom node names in graphs using `delayed` do not wok. In the following code:

```python
@dask.delayed(name='some-random-name')
def fn(a):
    return a

res = fn(4)
res.visualize()
```

The node is still called `fn`. 

Using dask 0.17.1 on Python 3.6.4

**Comment by mrocklin** [comment]
You probably want the following:

```python
@dask.delayed
def fn(a):
   return a

res = fn(4, dask_key_name='some-random-name-4')
```

See https://github.com/dask/dask/pull/3346 for more information

**Comment by eddienko** [comment]
Thanks. That certainly fixes the issue.

However there is an interesting side effect of naming the node graphs that is better explained with an example. The following just takes two images, subtracts another one and sums the result:

```python
@delayed
def load_image(filename, extension):
    return np.ones([1000,1000])

@delayed
def load_bias(filename, extension):
    return np.ones([1000,1000])

@delayed
def subtract_bias(img, bias):
    return img - bias

img1 = load_image('image1', 1)
bias1 = load_bias('image1', 1, dask_key_name='bias1')
res1 = subtract_bias(img1, bias1)

img2 = load_image('image2', 1)
bias2 = load_bias('image2', 1, dask_key_name='bias2')
res2 = subtract_bias(img2, bias2)

res = res1 + res2
visualize(res)
```

![bias1](https://user-images.githubusercontent.com/3780274/38125625-215707ae-33eb-11e8-9a35-2ed878375052.png)

That's good. However **if** I use ```dask_key_name='bias'``` for the two ```load_bias``` functions above I get the following:

![bias2](https://user-images.githubusercontent.com/3780274/38125734-db1b762a-33eb-11e8-8f24-6a3cf9984cc6.png)

i.e. the ```bias``` image (in this case the array in ```bias2```)  is shared between both computations. I can think of some situations where this would be useful, if indeed this is the intended behaviour.

**Comment by eddienko** [comment]
The above is documented in the delayed docstring so all good.

> Note that objects with the same key name are assumed to have the same
> result. If you set the names explicitly you should make sure your key names
> are different for different results.
