### ISSUE TITLE
Salting terminal keys

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3322]
Would be nice to have a function that can salt an arbitrary Dask graph's terminal (or result relevant) keys and return either the Dask graph or a new Dask object with the terminal keys salted.

**Comment by mrocklin** [comment]
Can you explain more about why this would be useful?  It's not obvious to
me.

**Comment by jakirkham** [comment]
In retrospect salt may not be the best term, but using a nonce would be a bit more accurate and representative of the problem being considered.

**Comment by jakirkham** [comment]
Sure. There are basically two cases that could benefit from this. Both have internal and user facing components.

The first case is when Dask interacts with the world. In these cases we need some way to track "the state of the world" (kind of like [State Monads in Haskell]( https://mvanier.livejournal.com/1765.html ) though we don't have an ordering problem within a Dask graph) in the Dask graph to avoid Dask from regarding it as an operation that has already been performed. A nice example of this would be profiling the runtime of a Dask graph. If I want to run the same Dask graph a few times to see how long it takes to run, the same keys reappear, which can confound one's ability to profile it. This is explored briefly with a rather contrived example in issue ( https://github.com/dask/distributed/issues/1860 ). Other use cases include storage operations where the state of the world (e.g. what is on disk) could change in-between operations. ( https://github.com/dask/dask/pull/3325 ) In these cases, we need some way to simulate the state of the world somehow.

The second case is for debugging. Profiling again fits here. Though also cases where the user may suspect the key is somehow playing a part in the problem. So being able to eliminate repeating keys as part of the problem quickly helps identify a potential issue right away. This is just as useful debugging one's own issues as others.

Being able to inject a nonce into the tokenization operation used for each key would effectively address both of these use cases. The randomization should allow operations that impact the state of the world to be viewed as extinct and thus not having already occurred before. Also it should aid in distinguishing cases that are intentionally replayed (e.g. profiling). Further it should help identify cases of accidental repetition when not enough information was used to determine keys.

**Comment by mrocklin** [comment]
In cases like storage where side effects (from dask's perspective) are the main result or any time where we're depending on external state I think we just shouldn't tokenize, and should instead use uuids.  This is common in many places in the codebase, but I would not be surprised if it was missing in others.  

In cases like profiling and benchmarking yes, I can see how this could be useful.  Having some global value/seed in _globals may be an option.  This is the sort of topic where I suspect @jcrist might have thoughts.

**Comment by dhirschfeld** [comment]
One thing I would like is to be able to label a particular dask graph so I can understand what tasks belong to what job.

I submit multiple jobs (dask graphs) to my distributed cluster where each job represents a pipeline of work. It would be useful for me to be able to see what tasks running on the cluster belong to what jobs.

***xref:*** mrocklin/streamz#100

**Comment by mrocklin** [comment]
I agree that that would be useful.  It is not currently supported.  I
believe that that is a different issue to what is being discussed here.
Would you might verifying that no existing issue discussing it exists and,
if not, raise one?

**Comment by jakirkham** [comment]
Agree that UUIDs should be used when there are stateful actions occurring. Closing.
