### ISSUE TITLE
DataFrame.describe : got an unexpected keyword argument 'include'

### ISSUE THREAD

**Issue by ZerothB** [dask/dask#3324]
The documentation ( http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.describe ) says that describe supports the "include" parameter exactly like pandas, but it does not seem to be that way. I tried both with the dask version 0.16.x and with the most recent 0.17.1 but I always get the same error: describe() got an unexpected keyword argument 'include'.

**Comment by mrocklin** [comment]
https://github.com/dask/dask/issues/1815
