### ISSUE TITLE
Add examples and infrastructure to the dask-examples repository

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3336]
The [dask-examples](https://github.com/dask/dask-examples) repository is set up to [run on binder](https://mybinder.org/v2/gh/dask/dask-examples/master).  This provides a nice entry point for new users who want to try things out.  It might be improved in several ways:

1.  Build it into Dask's documentation as a static notebook gallery for those who want to look at examples without necessarily running them.  Other projects do this with some sphinx plugin, so there is a fair amount of infrastructure already built up
2.  Extend it with more examples, possibly gleaning from (and cleaning up) our current [examples documentation](http://dask.pydata.org/en/latest/examples-tutorials.html), but being mindful of the [constraints](https://github.com/dask/dask-examples#contributing) laid out in the dask-examples README
3.  Adding CI to that repository so that it stays up to date without manual intervention

These topics are also listed on the dask-examples repository as separate issues but I wanted to raise an issue here as well for higher visibility.

This would be a good set of tasks for new developers to have very high impact on the project while also building Dask knowledge.

**Comment by kvn219** [comment]
@mrocklin, I would like to handle this issue. Could I have a go at this?
