### ISSUE TITLE
Creating a dask signal processing package

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3339]
Will be doing a fair bit of playing with signal processing functions and Dask in the near term. Was thinking it would be nice to have a package (e.g. `dask-signal` or similar) with some common routines (mainly from SciPy) wrapped up for use with Dask (including determining appropriate halos). Am trying to figure out the best home for it. A few options I can think of.

1. Here at the Dask org.
2. dask-signal org (which I own currently).
3. Other orgs (PyData, somewhere else).

Thoughts welcome. :)

**Comment by mrocklin** [comment]
Can you say more about the intended scope?  What are the classes of
operations that you imagine being within this package?  Are you planning to
use dask.array, dask.dataframe, or other collections?

**Comment by jakirkham** [comment]
Sure, happy to. Hope this helps. Please feel free to ask more questions. :)

Probably would mimic [`scipy.signal`]( https://docs.scipy.org/doc/scipy-1.0.0/reference/signal.html ) to start. In particular, [the filtering section]( https://docs.scipy.org/doc/scipy-0.19.1/reference/signal.html#filtering ) is of interest. [Splines]( https://docs.scipy.org/doc/scipy-0.19.1/reference/signal.html#b-splines ) can prove handy as well. Most of the other functions are about filter design, which can be done outside of Dask easily. Though they could be imported from SciPy for convenience. Some of the other ones (e.g. convolutions) are implemented for Dask Arrays elsewhere.

Personally am thinking about Dask Arrays. Though expect Dask Dataframes (given some conversion) could work as well since these filters work on 1-D arrays.

Open to other thoughts on this. Really just a rough idea on how to organize this as this stage.

**Comment by mrocklin** [comment]
Are there other domains where you think this would be useful?  Perhaps we
know some people in those domains who would want to collaborate

**Comment by jakirkham** [comment]
My guess is people already making use of the FFT functionality in Dask would be interested in this.

Can think of other fields these techniques might be useful in, but that would be mostly speculation on my part. Would say image processing, video processing, audio processing, finance, seisomology, etc. Generally if there is a temporal component or the data has some sort of noise that needs to be removed/features highlighted, these techniques will be generally useful.

**Comment by mrocklin** [comment]
I recommend that folks working independently generally create packages under their own name, and then wait until other folks come and start contributing before moving to the dask org.  Closing this for now.
