### ISSUE TITLE
DataFrame: Splitting a list to multiple columns is throwing error 

### ISSUE THREAD

**Issue by lijose** [dask/dask#3342]
I was trying to split a string and saved value in a temp column and use that column to populate additional columns.  I am able to split string and convert to a list. But while fetching elements from list and assigning to new column is throwing error. 

I have tried to recreate the error with below code:

```
df = pd.DataFrame({ 'a' : [1, 2, 3] ,
      'b' : ['a|b|c|d|e|f|g', 'a|b|c|d|e|f|g', 'a|b|c|d|e|f|g']
            })
ddf = dd.from_pandas(df,1)
ddf['c'] = ddf.b.str.split('|')
ddf = ddf.assign(col1= ddf.c.map(lambda x: x[0]))
ddf = ddf.assign(col2= ddf.c.map(lambda x: x[1]))
ddf = ddf.assign(col3= ddf.c.map(lambda x: x[2]))
ddf = ddf.assign(col4= ddf.c.map(lambda x: x[3]))
```
Getting error while executing last line >> ddf = ddf.assign(col4= ddf.c.map(lambda x: x[3]))
   IndexError('string index out of range',)

**Comment by mrocklin** [comment]
Thank you for the example failure.  Dask wasn't able to determine the dtype
of the output of your function.  I've improved the error message here in
https://github.com/dask/dask/pull/3343 .  I hope that it is sufficiently
informative to help you (and others like you) here.
