### ISSUE TITLE
Named Graphs/Pipelines

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask#3344]
Moved from https://github.com/dask/dask/issues/3322#issuecomment-375944629

> *One thing I would like is to be able to label a particular dask graph so I can understand what tasks belong to what job.*
>
> *I submit multiple jobs (dask graphs) to my distributed cluster where each job represents a pipeline of work. It would be useful for me to be able to see what tasks running on the cluster belong to what jobs.*

**Comment by dhirschfeld** [comment]
Possibly also related to #3318?

**Comment by mrocklin** [comment]
I agree that this would be valuable.  Unfortunately Dask doesn't currently
have any notion of a job, so I don't know how this would be implemented
currently

**Comment by sjperkins** [comment]
Related to https://github.com/dask/distributed/pull/1559

**Comment by mrocklin** [comment]
Currently out of scope.
