### ISSUE TITLE
ImportError: cannot import name methods

### ISSUE THREAD

**Issue by ptiagi** [dask/dask#3348]
I am importing dask in my jupyter notebook by running the following command:
import dask.dataframe as dd
And I get the following error:
ImportErrorTraceback (most recent call last)
in ()
----> 1 import dask.dataframe as dd

/home/ptyagi/myenv/lib/python2.7/site-packages/dask/dataframe/init.py in ()
9 demo, to_hdf, to_records, to_bag)
10 from .optimize import optimize
---> 11 from .multi import merge, concat
12 from . import rolling
13 from ..base import compute

/home/ptyagi/myenv/lib/python2.7/site-packages/dask/dataframe/multi.py in ()
68 _maybe_from_pandas, new_dd_object, is_broadcastable)
69 from .io import from_pandas
---> 70 from . import methods
71 from .shuffle import shuffle, rearrange_by_divisions
72 from .utils import strip_unknown_categories

ImportError: cannot import name methods

I had first installed dask by running pip install dask
but later on I installed dask again by running pip install "dask[complete]" as I was getting import error for toolz.
My python version is 2.7.10
dask version is 0.17.2

following is my pip freeze result:
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.3
click==6.7
cloudpickle==0.5.2
configparser==3.5.0
cycler==0.10.0
dask==0.17.2
decorator==4.2.1
Distance==0.1.3
distributed==1.21.4
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
futures==3.2.0
HeapDict==1.0.0
html5lib==1.0.1
ipykernel==4.8.2
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.2
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
locket==0.2.0
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
msgpack-python==0.5.6
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.1
numpy==1.14.2
pandas==0.22.0
pandocfilters==1.4.2
partd==0.3.8
pathlib2==2.3.0
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psutil==5.4.3
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.2
python-Levenshtein==0.12.0
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
scandir==1.7
scikit-learn==0.19.1
scipy==1.0.1
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
subprocess32==3.2.7
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.0.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.4
zict==0.1.3

**Comment by ptiagi** [comment]
I am importing dask in my jupyter notebook by running the following command:
`import dask.dataframe as dd`
And I get the following error:
ImportErrorTraceback (most recent call last)
<ipython-input-5-420aeb5f905d> in <module>()
----> 1 import dask.dataframe as dd

/home/ptyagi/myenv/lib/python2.7/site-packages/dask/dataframe/__init__.py in <module>()
      9                  demo, to_hdf, to_records, to_bag)
     10 from .optimize import optimize
---> 11 from .multi import merge, concat
     12 from . import rolling
     13 from ..base import compute

/home/ptyagi/myenv/lib/python2.7/site-packages/dask/dataframe/multi.py in <module>()
     68                    _maybe_from_pandas, new_dd_object, is_broadcastable)
     69 from .io import from_pandas
---> 70 from . import methods
     71 from .shuffle import shuffle, rearrange_by_divisions
     72 from .utils import strip_unknown_categories

ImportError: cannot import name methods

I had first installed dask by running `pip install dask`
but later on I installed dask again by running `pip install "dask[complete]"` as I was getting import error for toolz.
My python version is 2.7.10
dask version is 0.17.2

following is my `pip freeze` result:
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.3
click==6.7
cloudpickle==0.5.2
configparser==3.5.0
cycler==0.10.0
dask==0.17.2
decorator==4.2.1
Distance==0.1.3
distributed==1.21.4
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
futures==3.2.0
HeapDict==1.0.0
html5lib==1.0.1
ipykernel==4.8.2
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.2
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
locket==0.2.0
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
msgpack-python==0.5.6
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.1
numpy==1.14.2
pandas==0.22.0
pandocfilters==1.4.2
partd==0.3.8
pathlib2==2.3.0
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psutil==5.4.3
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.2
python-Levenshtein==0.12.0
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
scandir==1.7
scikit-learn==0.19.1
scipy==1.0.1
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
subprocess32==3.2.7
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
tornado==5.0.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.4
zict==0.1.3

**Comment by mrocklin** [comment]
Did you resolve your issue?  If so can you share what it was for future
readers?

**Comment by ptiagi** [comment]
I just restarted my kernel and it worked fine.

**Comment by nrj101** [comment]
Restarting the kernel works

**Comment by Vanderser** [comment]
I confirm it works (2)

**Comment by elizaguseva** [comment]
restarting fails for me repeatedly

**Comment by SamDean332** [comment]
Restart works - must restart after installs

**Comment by meabhi07** [comment]
I confirm it works when kernel restarts

**Comment by funsooje** [comment]
Restarting kernel confirmed
