### ISSUE TITLE
Can't save array using distributed scheduler

### ISSUE THREAD

**Issue by joshua-gould** [dask/dask#3351]
```
import dask.array as da
from distributed import Client
import h5py
from dask.utils import SerializableLock


def create_and_store_dask_array():
    data = da.random.normal(10, 0.1, size=(1000, 1000), chunks=(100, 100))

    data.to_hdf5('test.h5', '/test')
    # this fails too
    # f = h5py.File('test.h5', 'w')
    # dset = f.create_dataset('/matrix', shape=data.shape)
    # da.store(data, dset) #
    # f.close()


if __name__ == '__main__':
    client = Client()
    create_and_store_dask_array()
```

Gives: TypeError: can't pickle _thread._local objects

**Comment by mrocklin** [comment]
Thank you for the minimal example.

Yeah, the distributed scheduler and HDF5 don't seem to get along very
well.  It would be nice to fix this.  Alternatively you have a few
workarounds

   1. Use the local scheduler by just not instantiating the Client
   2. Use XArray, which I think has done a fair amount of work to resolve
   this problem downstream

Alternatively, effort to fix this problem would be welcome.

**Comment by joshua-gould** [comment]
Is there a recommended output format for the distributed scheduler? Thanks.

**Comment by mrocklin** [comment]
Many people are switching to Zarr, which seems to be easier for distributed
systems to work with: http://zarr.readthedocs.io/en/stable/

**Comment by jakirkham** [comment]
Zarr is definitely a good option (am somewhat biased).

It's possible to improve writing to HDF5 with at least either a locking strategy or a network bound strategy. The locking strategy for HDF5 is in PR ( https://github.com/dask/dask/pull/3179 ). The network bound strategy would involve a single process receiving data from other processes and writing to disk. Both of these will fundamentally be limited to one process writing at a time.

**Comment by joshua-gould** [comment]
Another option is to use HDF5 virtual datasets (
https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesVirtualDatasetDocs.html)
and write each output chunk independently and combine them into a virtual
dataset when finished.

**Comment by jakirkham** [comment]
Yep, that came up in issue ( https://github.com/dask/dask/issues/3074 ) as well.

**Comment by joshua-gould** [comment]
My current solution is to have one process that does writing and and receives chunks from other workers. It's very slow, but it works.

**Comment by jakirkham** [comment]
Yeah, that seems reasonable as well. It also [came up in that thread]( https://github.com/dask/dask/issues/3074#issuecomment-358521913 ). If you have time, would encourage you to drop a line in that thread, share your experiences, and ask questions. Many of the people in that thread have run into this issue and have dealt with it in different ways.

**Comment by mrocklin** [comment]
There are other issues about HDF5 and the distributed scheduler.  Closing this one.
