### ISSUE TITLE
Branding dataframe reprs

### ISSUE THREAD

**Issue by tonyfast** [dask/dask#3352]
This may be a weird design comment. 

It seems that everyone is using dataframes to visualize there data.  At quick glance, all dataframe reprs look similar.  It would be nice to provide some differentiation between different classes that provide dataframes.  Dask already considers with the markdown header.

The image below shows the current dask repr and a modified version.  In general, I rarely see the table header populated in a dataframe repr.  The modified repr replaces this cell with the dask logo and a link to the dataframe documentation.

<img width="500" alt="screen shot 2018-03-29 at 12 14 04 am" src="https://user-images.githubusercontent.com/4236275/38069877-c5e87128-32e6-11e8-9213-2de6b0b47aca.png">

Please feel free to dismiss this suggestion. But, I thought it looked snazzy.

**Comment by mrocklin** [comment]
Seems like a sensible approach.  No strong thoughts from me either way.
