### ISSUE TITLE
Dataframes: divisions vs partition (min, max) and other partfile stats?

### ISSUE THREAD

**Issue by gorlins** [dask/dask#3384]
This is less of an issue and more a structural question that has bothered me for a while and I'm wondering if it make sense at all for a future version of dask, or if this is better solved by other approaches.

Dataframe divisions are lossy by design:

```python
from dask.dataframe import from_pandas, concat
ddfs = [
    from_pandas(pd.DataFrame({'a':range(5)}), npartitions=1),
    from_pandas(pd.DataFrame({'a':range(5)}, index=range(10, 15)), npartitions=1)]
"""
In [6]: ddfs
Out[6]:
[Dask DataFrame Structure:
                    a
 npartitions=1
 0              int64
 4                ...
 Dask Name: from_pandas, 1 tasks, Dask DataFrame Structure:
                    a
 npartitions=1
 10             int64
 14               ...
 Dask Name: from_pandas, 1 tasks]
"""

concat(ddfs).get_partition(0)
"""
Dask DataFrame Structure:
                   a
npartitions=1
0              int64
10               ...
Dask Name: get-partition, 5 tasks
"""
```

In the above example, we lose the fact that the initial partition has a max value of 4 - there are no rows between 4 and 10.  We also lose the symmetry given that the last division is an inclusive end (`index <= divisions[i+1]`) where others are exclusive (`index < divisions[i+1]`)

When dealing with indices that are relatively dense within ranges, this is fine.  However, there are plenty of cases where an index is relatively sparse - I deal with geospatial indices a lot, for instance, where a partition might contain data from a certain region of a map, which is nicely indexed by something like a https://en.wikipedia.org/wiki/Geohash - but there may be a lot of space between the bounds of their hashes depending on how close the regions are.  Datetime ranges also make sense here, if you have big data sets with lots of time gaps in between.  Many algorithms could benefit by knowing the precise span of data within a partition, ie to know that *no* partitions/rows are impacted by a filter/query etc or to do some math on duration/span of a partition via the metadata alone.  I can leverage this to some extent by operating on lists of single partition dask dataframes, but it would be nice to let dask handle that kind of complexity for me.

This information exists in parquet partfiles and row group statistics for instance (don't know off the top of my head about other data stores) and to my knowledge is better leveraged by spark in its dataframes.  It is thrown out after reading the metadata, as opposed to if I read one part file at a time into separate dask dataframes.  Some of the functionality is also exposed via parquet filters on read, but it seems like dask *could* incorporate this better at the dataframe level if it kept the stats around.

Similarly, other column min/max stats can be useful for accelerated filtering etc, though obviously are more distant from what dask already exposes via the divisions.

Do you think switching from divisions to index ranges, for instance, would be an appropriate thing for dask? Is it even achievable with a realistic amount of work?

**Comment by gorlins** [comment]
Another small case where this is an annoying, albeit fixable, error:

```python
together = concat(ddfs)

concat([together.get_partition(i) for i in range(together.npartitions)])

ValueError: All inputs have known divisions which cannot be concatenated in order. Specify interleave_partitions=True to ignore order
```

**Comment by mrocklin** [comment]
It looks like the difference here isn't with get_partitions losing data, its with the first two partitions of the two dataframes being merged.  

```python
In [5]: concat(ddfs)
Out[5]: 
Dask DataFrame Structure:
                   a
npartitions=2       
0              int64
10               ...
14               ...
Dask Name: concat, 4 tasks
```

The question then becomes, when we have two dataframes with overlapping divisions, how should we merge them?

**Comment by gorlins** [comment]
I get the concern about adding more metadata in general, but I don't understand your prior comment about merging.  Knowing the max value of an index in a partition can only help a merge, since it's possible that there are more non-overlapping partitions that can be interleaved.  When the values of indices overlap for two partitions in different dataframes, you are no worse off than you currently are - the partitions either have to be split or merged:

```python
ddfs = [ # A dataframe from the concatenation of these
    from_pandas(pd.DataFrame({'a':range(5)}), npartitions=1),
    from_pandas(pd.DataFrame({'a':range(5)}, index=range(10, 15)), npartitions=1)]

# Should be mergeable with :
from_pandas(pd.DataFrame({'a':range(5)}, index=range(5, 10)), npartitions=1)]
# So long as interleave_partitions=True and dask knows the max of each partition index values
```

On your first comment, yes it is the merge which is lossy (and only lossy for the `ddf.divisions`, not the computed frame itself).

I can imagine something like:

```python
class DataFrame():
    ...
    index_bounds = [(0, 4), (10, 14)]
    @property
    def divisions(self):  # Backwards compat, but should be unnecessary
        return tuple([b[0] for b in self.index_bounds] + [self.index_bounds[-1][1]])
```

There may even be sane default values for index max values, such as div[i+1]-1 for integers, etc for various dtypes, if we don't know them but do know the divisions.  I've seen that approach in hbase/happybase as well with byte decrements for max value of a row key in a chunk.

Do you think its worth even attempting just for the index/divisions case, or would all of this just be way too hard given the current design?

**Comment by mrocklin** [comment]
It's doable, but would be a non-trivial amount of work.  I think that, in the common case, it also won't be informative.  In my experience data is usually pretty continuous, and so the minimum value of the next partition is usually a very good estimate for the minimum value of the previous partition.  I'm actually somewhat surprised that you have a real-world situation where this is not the case. 

You're more than welcome to try to implement this.  I think that seeing the difficulty or ease with which this can be implemented would help to determine if it should go in or not.  

Alternatively, if you're interested in partitioning data along geospatial lines, you might consider taking up a project like [dask-geopandas](https://github.com/mrocklin/dask-geopandas) (also see the second half of [this blogpost](http://matthewrocklin.com/blog/work/2017/09/21/accelerating-geopandas-1)).  This seems like a cleaner solution to me than relying on geo-hashing tricks.

**Comment by gorlins** [comment]
Thank you, yes, I've been following the dask-geopandas bit and would probably already be using it if it were released and production ready.  Right now my team is doing a poor approximation of that with normal parquet-backed dask dataframes w/ a WKT column and going to/from geopandas w/in a function, say:

```python
def as_geopandas(func):
    def wrapped(df):
        gdf = func(deser_pandas_to_geopandas(df))
        return ser_geopandas_to_pandas(gdf)
    return wrapped

some_dask_df.map_partitions(as_geopandas(lambda gdf: gdf.buffer(10))
```

This is obviously not as fast but works very well otherwise - and maintains clean compatibility with spark and tools like geospark and magellan (i haven't seen any geopandas work w/ parquet, just shapefiles!).  The main advantage of using a geospatial index is to enable predicate pushdowns for spatial joins or queries either via the dask/pandas index or even to filters in `read_parquet`.  I can imagine dask-geopandas could do something similar by writing `total_bounds` for a partition into the parquet metadata (?) and having something like `dask_gdf.partition_bounds=[bbox0, bbox1, ...]` but then that would be geopandas specific and not work elsewhere.  With my approach I can also use normal dask stuff too w/o caring about the GEOS interface or extra ser/deser steps w/ shapely or whatever, and just treat the geometry as a text column (or not load it at all!).  This is a very interesting topic but beyond the scope of this issue :).

I'll keep thinking about this and poke through the code to see if it makes sense to continue or not.

**Comment by martindurant** [comment]
@gorlins , what you are asking sounds like a great idea. But as you say, the data is stored as binary strings, and so the chunk statistics' min/max are meaningless as there is no geo type in parquet. 

You can store arbitrary extra metadata in both a global key/value store or a column-chunk specific one (which is also saved in the same file footer), and we use this for some pandas-specific type information. In theory the per-chunk divisions could go here, or the whole set in the global store. In order to make use of this, any loader must know that the column type is geo, and know to look for the extra metadata. Any filtering must then know to use logical operations like `in` and `not in` (and something for 'overlap'?). It's no obvious how dask or geopandas would push that down except in the initial set-up of the dataset object (`filters=`-style).

I could imagine coding that up in fastparquet, but there ought to be agreement on exactly what should be stored, where, the operations to support, etc.

In addition, there are other types with complex filtering that could be considered (e.g., filtering IP addresses by a mask), it doesn't really feel like any of this belongs in the data ingest layer when the number of logical types explicitly supported is limited.

**Comment by hafez-ahmad** [comment]
I tried in both way , gettting error,
dateRange=list(range(1989,2020))
years=[]

for year in dateRange:
    str_year=str(year)
    years.append(str_year)
    
# repartition the data - takes 0.001 seconds
permits_repartitioned=permits_indexed.repartition(divisions=years)
ValueError: right side of old and new divisions are different


divisions = pd.date_range('2009-01-23', ' 2012-04-02', freq='YS').tolist()
divisions[0] = permits_indexed.divisions[0]
divisions[-1] = permits_indexed.divisions[-1]
permits_repartitioned =permits_indexed.repartition(divisions=divisions)
TypeError: '<' not supported between instances of 'Timestamp' and 'str'

**Comment by TomAugspurger** [comment]
@hafez-ahmad your comment seems unrelated.
