### ISSUE TITLE
Temporary directory options

### ISSUE THREAD

**Issue by ckaz02** [dask/dask#3386]
I have some dask code that runs on small files successfully but when I try to process large files I get the "No space left on device" error and I find the leftover partd folder in the /tmp folder. 

I have tried using dask.set_options globally and as a context manager for the temporary_directory but I'm still getting the error and it's still going to the /tmp folder.

Is there another way in dask to make sure it uses the temp directory that I want it to? Am I able to view the dask options to see what is set if I step through using pdb?

**Comment by mrocklin** [comment]
Unfortunately it looks like the best documentation we have for this is code.  These lines might help:

https://github.com/dask/dask/blob/7cd5143820f58cc600bbaf553b542ccc5e760d9e/dask/dataframe/shuffle.py#L244-L263

https://github.com/dask/partd/blob/4cf8ac65fcf12d4d5a18b7f0dfe35d329ffb91de/partd/file.py#L14-L27

If you're able to determine what is going wrong and feel like providing a fix that would be well appreciated.

**Comment by jakirkham** [comment]
IDK if you know about this, @ckaz02. Linux (if you are using Linux) has something called [tmpfs]( https://wiki.archlinux.org/index.php/tmpfs ), which appears like disk storage, but is really in-memory storage. It is commonly used on the `/tmp` directory (amongst some other locations). Assuming this applies to your system, then the error indicates that the job filled up all available in-memory storage and crashed. Would recommend choosing a location that does not use `tmpfs`.

**Comment by fwrite** [comment]
For those searching for a solution to this problem, the alternative location can be set using:
```python
import dask
dask.config.set({'temporary_directory': '/alternative_location_here'})
```
