### ISSUE TITLE
read_sql_table is not working correctly

### ISSUE THREAD

**Issue by krinkere** [dask/dask#3393]
I tried to read table from a remote Oracle database, and I am able to do it via dataframe and sqlalchemy.
When i call read_sql_table provided by dask in sql.py, I am getting KeyError message

It breaks on index = (table.columns[index_col] if isinstance(....

checked and my index_col matches available table.columns, however, my index_col is of str per documentation, and table.columns are sqlalchemy.sql.schema.Column. Hence the error

Also in example section where it shows basic use, the example is outdated, still uses dd.read_sql

I installed dask via pip, so I am using

0.17.2-py36_0

**Comment by krinkere** [comment]
Both table and column are strings.
Here is my code snippet. Let me know what else you need to reproduce the issue.

conn = 'oracle+cx_oracle://'+username+':'+password+'@'+ip+':'+str(port)+'/?service_name='+SID
df_dusk = ddf.read_sql_table(table="employee", uri=conn, index_col='employee.id',  schema="hr")

Error:
Traceback (most recent call last):
  File "/temp.py", line 56, in <module>
      df_dusk = ddf.read_sql_table(table="employee", uri=conn, index_col='employee.id',  schema="hr")
  File "/lib/python3.6/site-packages/dask/dataframe/io/sql.py", line 91, in read_sql_table
    index = (table.columns[index_col] if isinstance(index_col, six.string_types)
  File "/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'employee.id'

**Comment by martindurant** [comment]
Can you please find the possible entries in `table.columns`, i.e., `list(table.columns)` ?

**Comment by krinkere** [comment]
Well. I have no idea what happened there, but simply restarting pycharm (which I had to do due to system reboot) "fixed" it. I am now getting what I want.

**Comment by martindurant** [comment]
Great news! I might suspect that there was a version conflict somewhere in the system, in that case.

**Comment by martindurant** [comment]
We like those numbers :)
We do have a policy of keeping pypi and conda releases in step (at least on the conda-forge channel), so you may have dropped unlucky in timing your installation last time. Unless you are installing directly from github, of course.
