### ISSUE TITLE
Dask datasets submodule

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3397]
It might be useful to have a `datasets` module similar to scikit-learn that provides a few canned dask collections.  This would be useful in examples, tutorials, testing, and other situations where we want a dask collection, but don't want to go through the process of collecting data and using the normal API

These might be random / artificial datasets or downloaded data.

Questions:

1.  What are existing conventions around doing this that we can borrow from other projects?
2.  What are some good example datasets (either real or random) that we can provide?

cc @AlbertDeFusco

**Comment by jakirkham** [comment]
From a packaging standpoint, we generally try to package the datasets separately. Though it is better still if the datasets are not required by the library at runtime, but are strictly optional.

A couple examples are `basemap` and `nltk` (@danielfrg was involved with nltk and might have some thoughts to share on this approach).

We could look at providing this like optional dependencies for ensuring the right version of the datasets are installed with a version of Dask should users opt to install them.

Are there particular use cases/data that you are hoping to package?

**Comment by mrocklin** [comment]
There are not particular use cases or data, other than what we often find ourselves wanting in tutorials, or what novice developers might find educational.

**Comment by mrocklin** [comment]
These are the sorts of things that I would hope to use within the dask-examples repository, or in scalability studies.

**Comment by jakirkham** [comment]
When I think of things that scikit-image or scikit-learn include as datasets, they are usually well-understood, toy pieces of data that are useful for showing examples and allowing users to test out/improve their intuition. Typically when I think of Dask, it is in applications with either of the two libraries above (though I'm obviously biased ;). So some Dask examples could possibly reuse other libraries data as is. Perhaps there are other libraries with toy data that could be coupled in the same way.

**Comment by mrocklin** [comment]
Yes, that's a good point.  One difference is that we would like to have
"datasets" that can scale.  For example I think that @TomAugspurger has
code that use's scikit-learn's make_classifier function (I think that's
what it's called?) in parallel to make a much larger version with the same
semantics.

**Comment by danielfrg** [comment]
I think sklearn convention is pretty good for stuff like that. I also like the `keras.datasets` ( https://keras.io/datasets) API, this downloads to specific directory when used.

For R I think there is some standard datasets like [nyc flights 2013](https://github.com/hadley/nycflights13), diamonds and more that are more toy examples but work very well for demos. nyc taxi is always nice.

For nltk in conda-forge we also ship [nltk-data](https://github.com/conda-forge/nltk_data-feedstock) but this might be an special case since the library actually needs the data (pickles and other stuff) to work and not just for examples.

**Comment by jakirkham** [comment]
> One difference is that we would like to have "datasets" that can scale.

This was the other point that we need to think about. What sizes are we considering because our approach will be very different depending on this?

**Comment by mrocklin** [comment]
In my mind the ideal "dataset" has a tunable size.
dask.dataframe.demo.make_timeseries() is a good example of this.

**Comment by mrocklin** [comment]
The NYC Taxi is another example because you can also choose to look a a
small fraction of the data (a day, week or month of a year) and it remains
meaningful.

**Comment by jakirkham** [comment]
So synthetic vs. actual is a big difference. One just relies on us having some code to make it. The other has to be provided somehow. How it is provided varies greatly based on it's size. Hence the question. 😉

**Comment by AlbertDeFusco** [comment]
For large datasets I like the approachs taken by Keras andr PyViz where datasets are downloaded as needed from a common S3 bucket or original source.

Keras has a separate module and load function for each dataset.

https://github.com/keras-team/keras/blob/master/keras/datasets/boston_housing.py


PyViz provides a command line tool and importable function to download files specified in the datasets.yml file.

https://github.com/pyviz/pyviz/tree/master/pyviz

**Comment by jakirkham** [comment]
A similar data packaging topic came up at ImageXD. Think @stefanv was working on it. Apparently there is a data packaging project IIRC, which would be useful here.

**Comment by martindurant** [comment]
What Intake does not provide (yet?) is a) downloading data on demand, as opposed to installing data packages or referencing remote data b) a way to generate procedural/random data.
