### ISSUE TITLE
Improving the docs of advanced features

### ISSUE THREAD

**Issue by bheklilr** [dask/dask#3398]
(Prompted by https://twitter.com/dask_dev/status/984505594567708672)

I have recently been using distributed to build a somewhat more customized cluster to suit my particular needs.  In building this I've found myself having to dig down into the source code for `distributed` fairly frequently as the information I wanted was not easily found in the documentation.  Some of the things that I think could have improved documentation are:

### Scheduler services

Services like `distributed.bokeh.scheduler.BokehScheduler` are not enabled by default, could not find this stated in the documentation anywhere, and to figure out how to enable it required me to read `distributed/cli/dask_scheduler.py`.  I could also not find any documentation on how to write my own services, since there is not a single `BaseService` class or ABC to tell me what is required.

### Worker services

See above about scheduler services.

This one I actually needed to write my own wrapper for.  Essentially, I needed to be able to pass in configuration values that are worker machine specific (path to another program installed on the computer, could be in multiple locations).  Ended up writing
```python
class ConfigValueProvider(tornado.httpserver.HTTPServer):
    def initialize(self, *args, **kwargs):
        self.config_value = kwargs.pop('config_value', None)
    def listen(self, addr):
        pass

worker = distributed.Nanny(..., 
    services={('config_value', 0): (ConfigValueProvider, {'config_value': variable})}
)
```
Then in the code I need to run on each computer
```python
from distributed.worker import get_worker

def thing_to_run():
    worker = get_worker()
    # But with more error handling
    config_value_provider = worker.services['config_value'].config_value
```
There may be a better way, but this is a way that I found that works, soo....

### `asyncio`/`async-await` Integration

(This may be a non-existent feature) While there is [existing documentation](https://distributed.readthedocs.io/en/latest/asynchronous.html) for using the Client object with coroutines, I also ran into the problem that I really wanted to be able to run a coroutine on the worker itself.  Because I am shelling out to an external tool on the workers, it would be awesome if the worker code could be a coroutine that integrates into the dask-worker's event loop, or gets run in its own event loop depending on how the implementation details go.  I couldn't find anything on doing this or not doing this.

**Comment by TomAugspurger** [comment]
@bheklilr is there anything here you're interested in turning into docs?

**Comment by bheklilr** [comment]
@TomAugspurger As of right now, no.  Unfortunately since I made this issue I've moved on to a different employer and no longer get to use Python much, let alone dask.  I would still like to see dask be improved, but I just don't have the use for it anymore, and don't have the free time to work on it independently.

**Comment by TomAugspurger** [comment]
Alrighty, thanks. We'll always accept improvements to the docs, but I'm not sure this issue is specific / up to date enough to warrant leaving open.
