### ISSUE TITLE
CommClosedError when using own Jupyter on Kubernetes

### ISSUE THREAD

**Issue by tracek** [dask/dask#3399]
Hi,

I have installed Dask via helm as described in the manual. The deployment consist of three workers and a Jupyter. In the same namespace I have JupyterHub running.

When I run Dask on Jupyter supplied with the deployment, all is good. Problems start when I try to use Dask with my own Jupyter.

```
import dask.dataframe as dd
from dask.distributed import Client, config

client = Client(address='invinvible-snake-dask-scheduler:8786')

df = dd.read_csv('*.csv')
print(len(df))
```

which produces:

```
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://10.44.14.13:8786' processes=3 cores=12>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/toClient
Scheduler: tcp://invinvible-snake-dask-scheduler:8786
Dashboard: http://invinvible-snake-dask-scheduler:8787/status
Cluster
Workers: 3
Cores: 12
Memory: 47.33 GB
rnado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 846, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat'})
  File "/opt/conda/lib/python3.6/site-packages/distributed/batched.py", line 106, in send
    raise CommClosedError
distributed.comm.core.CommClosedError
```

When I print `client`, it looks reasonable:

```
Scheduler: tcp://invinvible-snake-dask-scheduler:8786
Dashboard: http://invinvible-snake-dask-scheduler:8787/status
Cluster
Workers: 3
Cores: 12
Memory: 47.33 GB
```

Perhaps I am missing something about connecting to k8s Dask cluster? I am on 0.17.2.

**Comment by mrocklin** [comment]
Interesting.  Do normal operations work?  Things to check:

1.  `client.get_versions(check=True)`
2.   `client.submit(lambda x: x + 1, 10).result()`

**Comment by tracek** [comment]
@mrocklin You nailed it. Turned out the error was caused by discrepancy between client and scheduler / workers. Before I close it: do you think it's worth adding to FAQ? There might be more people making such a rookie mistake.

**Comment by mrocklin** [comment]
I'm in favor of removing the FAQ as-is.  I do agree that we should improve
the usabiliy here though.  This is a common mistake.  I'm more inclined to
do this automatically in the near future.

On Fri, Apr 13, 2018 at 12:05 PM, Lukasz Tracewski <notifications@github.com

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/issues/1678

**Comment by mrocklin** [comment]
That would be welcome.  Shall we continue conversation on #1678 ?  Perhaps
look through the proposal there and the code in Client._start

https://github.com/dask/distributed/blob/419b373ea7326d24a48192d77c67550c9d641130/distributed/client.py#L717



... and then ask questions that arise about how best to proceed?  (I'm sure
that there will be some.)  I'd be happy to help point you in the right
direction and field questions that may arise.

On Fri, Apr 13, 2018 at 12:24 PM, Lukasz Tracewski <notifications@github.com

**Comment by tracek** [comment]
Excellent, will do - thanks! Closing this one and refer to the potential fix later.
