### ISSUE TITLE
DataFrame read_hdf sorted_index=True forces npartitions to 1

### ISSUE THREAD

**Issue by Pierre-Bartet** [dask/dask#3401]
When reading a dataframe from a hdf file, using `sorted_index=True` forces the number of partitions to 1 whatever the value of `chunksize`:

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame(range(20))
df.to_hdf('df.h5', 'data', format='table')

ddf = dd.read_hdf('df.h5', 'data', chunksize=5)
print 'npartitions:', ddf.npartitions # -> 4

ddf = dd.read_hdf('df.h5', 'data', chunksize=5, sorted_index=True)
print 'npartitions:', ddf.npartitions # -> 1
```

**Comment by jrbourbeau** [comment]
It looks like this is why only a single partitions is being used in the `sorted_index=True` case:

https://github.com/dask/dask/blob/519932079fc08e084d469951f668bb211ba9176c/dask/dataframe/io/hdf.py#L268-L272

The `chunksize` parameter isn't being used, and instead the dataframe is being loaded in a single chunk. 

Perhaps something like 
 
```python
if sorted_index:
    index_series = storer.read_column('index', start=0, stop=storer.nrows)
    division = [index_series[idx] for idx in range(0, storer.nrows, chunksize)]
    division.append(index_series.iloc[-1])
    # For index_series of length 1
    if len(division) == 1:
        division = 2 * division
    divisions.append(division)
```

could be used to incorporate the `chunksize` when `sorted_index=True`.

**Comment by jrbourbeau** [comment]
@Pierre-Bartet are you interested in submitting a PR?

**Comment by Pierre-Bartet** [comment]
When I saw this line of code where chunksize is not used I wondered whether
there were some subtleties that prevented dask from combining both
sorted_index and chunksize. If it is not the case I can give a try !

2018-04-20 21:28 GMT+02:00 James Bourbeau <notifications@github.com>:

**Comment by jrbourbeau** [comment]
That's a good point. I'm not sure why `sorted_index` and `chunksize` aren't both currently being used. But adding the code snippet I posted fixes your example where the `npartitions` was being set to 1 when `sorted_index=True` and doesn't break any of the existing tests.

**Comment by jrbourbeau** [comment]
Hey @Pierre-Bartet, just wanted to check in to see how things are going with this issue. If you run into any problems, feel free to ask me about them.

**Comment by Pierre-Bartet** [comment]
Hi @jrbourbeau, I was quite busy but now I'm on it, currently I'm trying to find a solution to the fact that doing:
`index_series = storer.read_column('index', start=0, stop=storer.nrows)`
Will read the entire dataframe index into RAM, which in some sense negates the usefulness of chunksize.

**Comment by jrbourbeau** [comment]
> Will read the entire dataframe index into RAM, which in some sense negates the usefulness of chunksize.

Great point 

Since we're only interested in items in the index that are in `chunksize` intervals. We can do

```python
division = [storer.read_column('index', start=start, stop=start + 1)[0]
            for start in range(0, storer.nrows, chunksize)]
division_end = storer.read_column('index',
                                  start=storer.nrows - 1,
                                  stop=storer.nrows)[0]
division.append(division_end)
```

This should avoid any unnecessary loading of the dataframe index.

**Comment by jrbourbeau** [comment]
Closed by #3463

**Comment by jrbourbeau** [comment]
This issue can be closed cc @mrocklin

**Comment by mrocklin** [comment]
Thanks for following up @jrbourbeau !
