### ISSUE TITLE
Un-reproducible results when executing 2 graphs consecutively 

### ISSUE THREAD

**Issue by idanpai** [dask/dask#3417]
Hi,

In my application, I am executing 2 custom-graphs one after the other, with the second graph depending on the results of the first graph (the topology of the graphs is identical, yet I fetch different nodes from the graph).

I am trying to run an integration test, which reproduces the execution of the 2 graphs.

My code depends heavily on the python and numpy random modules, so I lock the random seed in several places in the code, knowing that if I use dask multi-threading, setting the seed in a single place will not reproduce the same result.

Here is the issue:
When using dask multi-threading scheduler, the random seed setting IN THE SECOND GRAPH is ignored and I get different random numbers generated when trying to reproduce the results.

Any Ideas why this may happen?
Is there some why to re-initiate dask? As it seems it kinds of remembers the execution of the first custom-graph, even though I re-built the graph-dict from scratch.

Thanks dask contributors,
You rock!

Notes:
1) This issue is not happening when I use dask single thread.
2) This issue is happening both when I use python's random module, and when I use numpy's random module.
3) My versions: python 3.6.3, numpy 1.14.2., dask 0.15.2

**Comment by idanpai** [comment]
Could It be that I need to use thread-locking in each random-depending code segment?

**Comment by mrocklin** [comment]
Thanks for the bug report @idanpai .  If you're able to produce a minimal reproducible example that would probably help people to understand what you are doing and more easily reproduce your curious results.
