### ISSUE TITLE
spectral clustering on dask.array dies on large image

### ISSUE THREAD

**Issue by ebo** [dask/dask#3418]
I recently extended Tom's spectral clustering to work on GeoTIFF images:

    https://github.com/ebo/pangeo-tutorials/blob/master/geo-spectral-geotiff-da.ipynb

and got it to work on the small image provided in the example (size: 1,343 x 1,227 x 3).  The processing is done remotely `client = Client('10.100.162.152:8786')` on a node that provides 1 worker, 4 cores, and 256GB/RAM.

When I give it a huge image (size: 35,249 x 36,855 x 5) it crashed  at the line `%time clf.fit(X)` with the following error that goes on for pages (follows is a smaller excerpt to follow).  I will  reproduce with some large synthetic images, but I wanted to capture the error message before it got lost:

> /att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/dask/array/core.py:2187: UserWarning: Increasing number of chunks by factor of 100
>   (nparts / max_parts))
> distributed.protocol.pickle - INFO - Failed to serialize (<toolz.functoolz.Compose object at 0x7ef3b59344d0>, (<built-in function apply>, <function any at 0x7eff6063ea28>, [(<ufunc 'isinf'>, (<built-in function getitem>, (<built-in function concatenate>, [(<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 0, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 1, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 2, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 3, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 4, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 5, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 6, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 7, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>,
> 
> ...
> 
> , (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 12989, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 12990, 0)", (array([    0,     1,     2, ..., 99997, 99998, 99999]), slice(None, None, None))), (<built-in function getitem>, "('div-transpose-abe58b36df7e1c0916245b151fadc7ba', 12991, 0)", (array([   0,    1,    2, ..., 1892, 1893, 1894]), slice(None, None, None)))], 0), (array([       100,        101,        102, ..., 1299101892, 1299101893,
>        1299101894]), slice(None, None, None))))], {'keepdims': True, 'axis': (0, 1)})). Exception: 'i' format requires -2147483648 <= number <= 2147483647
> 
> distributed.protocol.core - CRITICAL - Failed to Serialize
> Traceback (most recent call last):
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 41, in dumps
>     for key, value in data.items()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 42, in <dictcomp>
>     if type(value) is Serialize}
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 135, in serialize
>     header, frames = {}, [pickle.dumps(x)]
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
>     return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 881, in dumps
>     cp.dump(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 268, in dump
>     return Pickler.dump(self, obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 224, in dump
>     self.save(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 606, in save_list
>     self._batch_appends(iter(obj))
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 642, in _batch_appends
>     save(tmp[0])
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
>     save(state)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 492, in save_string
>     self.write(BINSTRING + pack("<i", n) + obj)
> error: 'i' format requires -2147483648 <= number <= 2147483647
> tornado.application - ERROR - Exception in callback (<zmq.sugar.socket.Socket object at 0x7eff64f4c590>, <function null_wrapper at 0x7eff64f18de8>)
> Traceback (most recent call last):
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 1065, in start
>     handler_func(fd_obj, events)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
>     self._handle_recv()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
>     self._run_callback(callback, msg)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
>     callback(*args, **kwargs)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/ipykernel/iostream.py", line 120, in _handle_event
>     event_f()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/ipykernel/iostream.py", line 376, in <lambda>
>     self.pub_thread.schedule(lambda : self._buffer.write(string))
> MemoryError
> distributed.comm.utils - ERROR - 'i' format requires -2147483648 <= number <= 2147483647
> Traceback (most recent call last):
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/comm/utils.py", line 38, in _to_frames
>     return list(protocol.dumps(msg))
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 41, in dumps
>     for key, value in data.items()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 42, in <dictcomp>
>     if type(value) is Serialize}
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 135, in serialize
>     header, frames = {}, [pickle.dumps(x)]
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
>     return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 881, in dumps
>     cp.dump(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 268, in dump
>     return Pickler.dump(self, obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 224, in dump
>     self.save(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 606, in save_list
>     self._batch_appends(iter(obj))
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 642, in _batch_appends
>     save(tmp[0])
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
>     save(state)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 492, in save_string
>     self.write(BINSTRING + pack("<i", n) + obj)
> error: 'i' format requires -2147483648 <= number <= 2147483647
> 
> distributed.batched - ERROR - Error in batched write
> Traceback (most recent call last):
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/batched.py", line 83, in _background_send
>     nbytes = yield self.comm.write(payload)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
>     value = future.result()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
>     raise_exc_info(self._exc_info)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/comm/tcp.py", line 217, in write
>     frames = yield to_frames(msg)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
>     value = future.result()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
>     raise_exc_info(self._exc_info)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
>     yielded = next(result)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/comm/utils.py", line 47, in to_frames
>     res = _to_frames()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/comm/utils.py", line 38, in _to_frames
>     return list(protocol.dumps(msg))
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 41, in dumps
>     for key, value in data.items()
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/core.py", line 42, in <dictcomp>
>     if type(value) is Serialize}
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 135, in serialize
>     header, frames = {}, [pickle.dumps(x)]
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
>     return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 881, in dumps
>     cp.dump(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 268, in dump
>     return Pickler.dump(self, obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 224, in dump
>     self.save(obj)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 606, in save_list
>     self._batch_appends(iter(obj))
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 642, in _batch_appends
>     save(tmp[0])
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
>     save(state)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
>     save(element)
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/att/nobackup/jldavid3/anaconda/lib/python2.7/pickle.py", line 492, in save_string
>     self.write(BINSTRING + pack("<i", n) + obj)
> error: 'i' format requires -2147483648 <= number <= 2147483647
>

**Comment by mrocklin** [comment]
The immediate error seems to be that you are pickling a single very large
array.  Python 2's pickle library breaks after 2GB.  However the
fundamental issue here is that you are loading a large tif file into memory
as a numpy array and then cutting it up with dask array.  It would be much
nicer if you would point dask to the tif file directly, so that it could
load chunks lazily rather than keep the entire array in memory.   I
recommend using the xarray.open_rasterio function instead, which seems to
handle this chunking automatically (assuming that your tif file is properly
tiled.)

**Comment by ebo** [comment]
That is what I have been working to do with:

https://github.com/ebo/pangeo-tutorials/blob/master/geo-spectral-geotiff-xa.ipynb

It is good to know that Python 2's pickle library breaks after 2GB.  I 
had not seen that documented, and have added it to the example.

Now that my current run has crashed I will look into why I am running 
on python2 and not 3 on the cluster, as well as continue working on the 
xarray version of the code.

   EBo --

**Comment by mrocklin** [comment]
Yes, the xarray version looks nicer.  I don't know what's up with the error
that you're getting there.

X = arr.reduce(np.ndarray.flatten)

I don't even know if this is valid xarray code.  I recommend raising XArray
issues with XArray.

On Wed, Apr 18, 2018 at 11:32 AM, John (EBo) David <notifications@github.com

**Comment by mrocklin** [comment]
Hi @ebo , just checking in, any update on your status here?  Have you been able to resolve your issue?

**Comment by ebo** [comment]
On Apr 21 2018 3:52 PM, Matthew Rocklin wrote:
> Hi @ebo , just checking in, any update on your status here?  Have you
> been able to resolve your issue?

I got a little farther ahead, but not much.  I forgot to push the 
current revision before I left work on Friday.  One thing that I did 
find is that the install on the local cluster depends on Python2.  I've 
worked around that but, but we will have to sort that out with the sys 
admins.  Also, I realized that all the I/O of that original notebook was 
going through the schedule node and not the worker.  I tweaked it, just 
to see how far it would get, and it died with a different error.  But as 
we both agree, using the dask array and reading in the image at one go 
is *not* the way to do it, but I wanted to stress test the stupid case.

Also, Jean-Luc has also set up a private repository to share this so I 
have less issues with sharing code and data.  I'll will get that posted 
ASAP.  Should I add you to those repositories?

   EBo --

**Comment by mrocklin** [comment]
OK, it sounds like you're handling this through other channels.  Closing.  

To be clear, the Python 2/3 issue here is not what I would focus on.  You should use functionality in XArray to load data lazily rather than immediately.  This is probably easier to resolve than screwing around with Python 2/3 easier and will result in much better performance.

Closing.

**Comment by ebo** [comment]
Understood.  The reason I did anything with the python 2/3 issue was I 
needed to figure out why it was set up that way on the cluster and to 
alert them of the issues.
