### ISSUE TITLE
Scaling of memory for svd_compressed

### ISSUE THREAD

**Issue by jmarkow** [dask/dask#3419]
I'm curious about the memory usage of `linalg.svd`.  In the following example I find that memory scales with the size of the array, not the blocksize,

```
import dask.array as da
import dask.array.linalg
ar =  da.random.random((600000,6400), chunks=(1000,6400))
u, s, v= da.linalg.svd_compressed(ar[:500], 100, 0)
%memit s, v = dask.compute(s, v)
u, s, v= da.linalg.svd_compressed(ar[:500000], 100, 0)
%memit s, v = dask.compute(s, v)
```
I see the following memory usage,

```
peak memory: 357.35 MiB, increment: 53.86 MiB
peak memory: 25273.55 MiB, increment: 24951.71 MiB
```

But the documentation for the underlying tsqr algorithm [states](https://github.com/dask/dask/blob/master/dask/array/linalg.py#L45),

```
If blocks are of size ``(n, k)`` then this algorithm has memory use that
scales as ``n**2 * k * nthreads``.
```

I see similar usage patterns running tsqr alone on the data.

**Comment by mrocklin** [comment]
I'm able to reproduce this.  Looking at the graph view with the distributed scheduler we see that many of the getitem tasks are accumulating in memory.  

![image](https://user-images.githubusercontent.com/306380/38980767-b35a28ca-438b-11e8-98a6-74d6229c24ff.png)

cc @marianotepper , the original author of that algorithm, to see if he has any thoughts.

**Comment by jmarkow** [comment]
Interesting, thanks for looking into it!  Until this is resolved we can use a cache with `Chest`.

**Comment by mrocklin** [comment]
That will, I suspect, be somewhat expensive (depending on your disk speed)

On Thu, Apr 19, 2018 at 9:15 AM, Jeffrey Markowitz <notifications@github.com

**Comment by jmarkow** [comment]
So right now the performance with cache is acceptable for us, but we'd obviously like to keep the computation in memory if we can.  

I'm going to try some naive alternatives like calculating the covariance matrix through a running mean and running sum of squares, then performing svd on the covariance matrix.  I'll keep you posted.

**Comment by jmarkow** [comment]
I'm finding that naive methods for computing covariance also seem to scale with dataset size and not chunk size (leaving out centering the data for now), e.g., 

```
ar =  da.random.random((100,6400), chunks=(100,6400))
cov = ar.T.dot(ar)
%memit tmp = cov.compute()
ar =  da.random.random((1000,6400), chunks=(100,6400))
cov = ar.T.dot(ar)
%memit tmp = cov.compute()
ar =  da.random.random((10000,6400), chunks=(100,6400))
cov = ar.T.dot(ar)
%memit tmp = cov.compute()
```

```
peak memory: 3067.55 MiB, increment: 625.16 MiB
peak memory: 9268.63 MiB, increment: 6825.98 MiB
peak memory: 20699.54 MiB, increment: 18254.89 MiB
```

**Comment by jmarkow** [comment]
Fair enough. 

What if we used a `naive` covariance estimate?  It's quite straightforward and chunks can be passed in instead of `datums` per the Wikipedia parlance.  What would be the best way to implement with Dask?

https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance

See the pseudocode at the top.

**Comment by mrocklin** [comment]
Ah, I'm sorry, is it possible that you're just looking for the [da.cov](http://dask.pydata.org/en/latest/array-api.html#dask.array.cov) function?

**Comment by jmarkow** [comment]
I'm finding similar memory usage patterns with `da.cov`,

```
ar =  da.random.random((6400,100), chunks=(6400,100))
# tmp = ar.T.dot(ar)
cov = da.cov(ar)
%memit tmp = cov.compute()
ar =  da.random.random((6400,1000), chunks=(6400,100))
# tmp = ar.T.dot(ar)
cov = da.cov(ar)
%memit tmp = cov.compute()
ar =  da.random.random((6400,10000), chunks=(6400,100))
# tmp = ar.T.dot(ar)
cov = da.cov(ar)
%memit tmp = cov.compute()
```

```
peak memory: 12556.28 MiB, increment: 624.97 MiB
peak memory: 18247.62 MiB, increment: 6316.31 MiB
peak memory: 33132.55 MiB, increment: 21196.34 MiB
```

**Comment by jmarkow** [comment]
Hopefully I'm not adding noise (forgive me if the implementation is wrong), but memory usage also scales here with dataset size not chunk size,

```
ar =  da.random.random((10000,6400), chunks=(1000,6400))
ar -= ar.mean(axis=0)
parts = ar.to_delayed()

cov = []
for x in parts:
    sumsq=dask.delayed(lambda x: da.dot(x.T,x))(x[0])
    cov.append(sumsq)
    
%memit tmp = dask.delayed(sum)(cov).compute()

ar =  da.random.random((1000000,6400), chunks=(1000,6400))
ar -= ar.mean(axis=0)
parts = ar.to_delayed()

cov = []
for x in parts:
    sumsq=dask.delayed(lambda x: da.dot(x.T,x))(x[0])
    cov.append(sumsq)
    
%memit tmp = dask.delayed(sum)(cov).compute()
```

**Comment by jmarkow** [comment]
That makes sense to me.  In the meantime we've just been using `svd_compressed` with the distributed scheduler on large clusters with more than enough memory.  Seems to be working well for us at the moment.  

Has your recursion implementation been merged into master?  If so I might give it a try just to see if things work a little more efficiently.

Thanks!

**Comment by mrocklin** [comment]
Yes, it was merged.

**Comment by jmarkow** [comment]
Running code similar to above and finding the same results,

```python
import dask.array as da
import dask.array.linalg
ar =  da.random.random((600000,6400), chunks=(1000,6400))
u, s, v= da.linalg.svd_compressed(ar[:5000], 100, 0)
%memit s, v = dask.compute(s, v)
u, s, v= da.linalg.svd_compressed(ar[:500000], 100, 0)
%memit s, v = dask.compute(s, v)
```

```
peak memory: 381.04 MiB, increment: 272.86 MiB
peak memory: 25063.33 MiB, increment: 24947.29 MiB
```

We've switched over to using the distributed scheduler and more than enough workers to store things in distributed RAM.  Right now our matrices being fed to the SVD are on the order of 1e7 x 6400.

Let me know if there's anything else I can do to diagnose this, but not a pressing issue for us anymore.

**Comment by jmarkow** [comment]
Ah I see.  

Since we have everything working well on our end this isn't really an issue for us anymore.
