### ISSUE TITLE
Dropping NumPy 1.10

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3427]
Increasingly we discover issues with PRs after merging them on NumPy 1.10, which we then either need to fix ourselves or hope the submitter of the PR will kindly fix the issue. While these issues can normally be solved by skipping, adding compat functions, etc., it starts to raise the question: how long do we want to support NumPy 1.10. As of January NumPy 1.14 was relased and has since had 2 patch releases. The list of NumPy 1.15 issue is not too long either (roughly two thirds have already been resolved). To me this is a pretty good case for dropping, but am interested to hear other thoughts.

If we do feel strongly about keeping NumPy 1.10, could we discuss adding it as part of the PR builds to cutdown on strain caused by the issues mentioned above?

**Comment by jcrist** [comment]
We need to keep numpy 1.10 for downstream dependencies. I suggest moving the 3.5 build to 1.10, and bumping the 3.4 to the latest numpy that has a 3.4 build.

**Comment by jakirkham** [comment]
Works for me. Thanks @jcrist. :)

**Comment by jcrist** [comment]
> We need to keep numpy 1.10 for downstream dependencies.

Actually, that's no longer the case. Looks like xarray and scikit-image have both dropped 1.10. In that case, I'd also be fine dropping support. Ping @mrocklin in case I missed any other dependents.

**Comment by mrocklin** [comment]
Fine by me

**Comment by jcrist** [comment]
See #3429. Always nice to delete code.

**Comment by shoyer** [comment]
Indeed, very nice!
