### ISSUE TITLE
The use of db.read_text('file.json').map(json.loads) returns a list and thus is not equivalent to the loaded json structure

### ISSUE THREAD

**Issue by arjay55** [dask/dask#3435]
Creating a bag using the code `db.read_text('file.json').map(json.loads)` returns a list and thus is not equivalent to the loaded json structure:

Original JSON:
"[{'larry':red},{'harry':blue}]"

produces a bag of:
[[{'larry':red},{'harry':blue}]]

This may need to be fixed. A workaround then is to execute `dask.bag.flatten` to the bag object to remove the encapsulating list but it may not work on other JSON orient, when the internal levels are lists and should not be flattened.

**Comment by martindurant** [comment]
The basic thing here, is that `read_text` produces a list of lines in a file, even if there is only one line. When you map that to `loads`, you naturally get a list - but the problem you suppose, of accidentally unpacking something that really is a list in JSON will not happen. It is natural in the bag abstraction to consider a "list of things" whether those things are bytestrings, dictionaries, or more lists.

**Comment by arjay55** [comment]
So I expect that lists from JSON will not be unpacked. If that's the case, then we can close the issue.

**Comment by martindurant** [comment]
Perhaps you want `db.read_text('file.json').map(json.loads).flatten()` ?
