### ISSUE TITLE
Add scheduler= keyword to compute and persist

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3442]
As discussed in https://github.com/dask/dask/issues/3226#issuecomment-379937925 we should allow a more intuitive replacement for the current `get=` keyword, perhaps something like `compute(..., scheduler='threads')`

Some questions:

1.  What are the appropriate names to use?  threads, processes, synchronous ? 
2.  How do we handle distributed?  Perhaps a client registers a name 'distributed' in some global registry of schedulers?
3.  Do we keep the `get=` keyword around to be explicit?  Do we deprecate it?

I'm happy to do this work, though I suspect that @jcrist or @jakirkham might have strong thoughts and or want to do it directly.

**Comment by jakirkham** [comment]
Whatever we decide here, we should include that syntax in the [single threaded scheduler debugging page]( http://dask.pydata.org/en/latest/debugging.html#use-the-single-threaded-scheduler ) as we don't currently.

**Comment by mrocklin** [comment]
This was implemented in #3448
