### ISSUE TITLE
Improving the release process

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3447]
One of the current pain points in our release process that everyone has run into at least once is merge conflicts due to changelog entries. Namely if two PRs have a changelog entry in the same place and one got merged, there will be a merge conflict for the other one. This results in a fair bit of churn merging/rebasing and CI usage from these changes. So how do we fix this?

Well there are a few options. One is [`rever`]( https://github.com/regro/rever ), which is a release automating tool. It provides a [news directory]( https://regro.github.io/rever-docs/devguide.html#changelog ), which allows users to drop separate files into (so no merge conflicts) and aggregates them into the changelog when a release is cut. We started using it with `conda-smithy` and it is amazing 😍. Though this is an end to end release tool, which we may or may not be comfortable playing with. There are a plethora of different tools that are changelog focused, but I don't have lots of experience with any of them. Suggestions welcome.

**Comment by mrocklin** [comment]
We could also drop the requirement to add a changelog entry and instead
handle this at release time.  I used to do this.  It was not terribly
onerous.

**Comment by jcrist** [comment]
I'm also for moving the changelog creation to release time. There's been a lot of changelog only PRs (fixing of typos, formatting, etc...) that could potentially be avoided by just writing it once every release.

Alternatively, I've found just inserting a new changelog entry between old entries (instead of at the end of a list) reduces conflicts, as git sees these as unrelated edits. The changelog is no longer sorted by PR number, but I don't see that as an issue.

**Comment by martindurant** [comment]
The spyder project uses [loghub](https://github.com/spyder-ide/loghub), which generates entries based on PRs and closed issues (the intent being to clean this up before release).

**Comment by martindurant** [comment]
Anything auto-generated would still need proofing. I am surprised that you can do this by hand in five minutes, though.

**Comment by mrocklin** [comment]
I just go through git log and copy things down.  I also don't mind this
process that much,  it's good to be reminded of what has happened since
last release.

To be honest, its pretty much the only time I look at release notes.

**Comment by xhochy** [comment]
For Arrow, we have a fully auto-generated commit log that is pushed on release. For the release manager this is quite nice as he does not have to go over the merged PRs but I also do not consider it really user-friendly and thus we always also have a blog post per release.

If it only takes you 5min to manually assemble it, than this is probably the best option. As a library consumer I regularly read these changelogs and the dask ones are very readable and helpful.

**Comment by jakirkham** [comment]
My only complaint was merge conflicts and the churn caused over adding these items. If the feeling is these are easy to add at the end, great. That said, figured there was a reason we asked users to contribute to the changelog in the first place. So was trying to be considerate of that point of view as well.

Would be fine with closing as we have dropped the requirement. We can revisit alternatives if we feel the need to handle user submissions to the changelog. Independently if some of the other problems raised (e.g. automating publishing releases) are of interest we could keep this open and discuss those.

> As a library consumer I regularly read these changelogs and the dask ones are very readable and helpful.

👍
