### ISSUE TITLE
how do we specify which conda environemnt to use from within a notebook or program?

### ISSUE THREAD

**Issue by ebo** [dask/dask#3455]
As per the user docs, I have a number of environments set up in Anaconda, and switch between them (using  "source activate pangeo" for example).  When setting up jobs on a cluster, is there some way to specify that it should use a specific environment from the notebook, or do I have to do that by hand?

In specific I have an issue where the systems administrators on or experimental cluster use the system supplied python (Python-2.7) and use pip to install the packages.  Since it is my understanding that development is focused on using Python-3.6+, I have a local Anaconda install to work around the issue.  There is a question on how to set this up to work for general users, and by extension how to set it up to run through different Anaconda environments so that I/we can test different configurations.

**Comment by mrocklin** [comment]
This seems to be a question about how to use conda environments rather than how to use Dask.  Closing as off-topic.
