### ISSUE TITLE
Adding from_zarr and to_zarr methods

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3457]
Would be nice to have convenience methods for `from_zarr` and `to_zarr`, on Dask Arrays and possibly other Dask objects (thoughts from others?) that enables simple storage to Zarr. This has come up in a few different places and has been mentioned by a few different people generally along the same lines.

cc @alimanfoo @martindurant @mrocklin @rabernat @jhamman @shoyer

ref: https://github.com/dask/dask/issues/3302#issuecomment-385674820
xref: https://github.com/zarr-developers/zarr/issues/251
xref: https://github.com/zarr-developers/zarr/issues/198
xref: https://github.com/dask/dask/issues/1983
xref: https://github.com/pydata/xarray/pull/1528

**Comment by mrocklin** [comment]
No objection from me

**Comment by jakirkham** [comment]
Some work on this front in PR ( https://github.com/dask/dask/pull/3460 ). Would be helpful if others took a look. :)

**Comment by jakirkham** [comment]
Addressed by PR ( https://github.com/dask/dask/pull/3460 ).
