### ISSUE TITLE
Dask 0.17.3 <ImportError: cannot import name 'natural_sort_key'

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#3467]

**Comment by martindurant** [comment]
The function appears to be there: https://github.com/dask/dask/blob/master/dask/utils.py#L902

**Comment by mrocklin** [comment]
Thank you for reporting @apiszcz 

Can I ask how you installed dask?

**Comment by apiszcz** [comment]
unzip wheel into lib, I located the issue, sorry for the noise.

**Comment by mrocklin** [comment]
No worries.  Thanks for reporting anyway.  It's nice to know that people will report when issues arise.
