### ISSUE TITLE
Version 0.17.4 mismatch between git tag and pypi

### ISSUE THREAD

**Issue by cyrilpic** [dask/dask#3473]
While trying to use distributed 1.21.8 along with dask 0.17.4 (both latest version on pypi), I ran into the following issue: `AttributeError: module 'dask' has no attribute 'config'`.

It took me a while to find the origin: it seems like version [0.17.4 uploaded to pypi](https://pypi.org/project/dask/#files) is not the same as the [tagged version](https://github.com/dask/dask/releases/tag/0.17.4) on Github. If you download the files from pypi, you will notice that `config.py` is not yet present.

Would it be possible to release an updated minor version? Thanks!

**Comment by mrocklin** [comment]
I've just double-checked and I don't see config.py in either version.  

I pip installed from a clean environment.  I also downloaded the source tarball from github.  I also checked out git history in the main repo.

**Comment by mrocklin** [comment]
Note that we did add a config.py just after the release.  Is it possible that you are accidentally operating from master?

**Comment by cyrilpic** [comment]
Yes you are right. I was accidentally working with distributed from master and got confused browsing through history.
Thanks for the quick reply and sorry for the false alarm.

**Comment by mrocklin** [comment]
No worries.  It's reassuring knowing that people are out there that *will*
raise an alarm if we screw up during the release process.  Thank you for
raising the issue.
