### ISSUE TITLE
Python 3.4 CI failure

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3475]
Seeing failures on Travis CI for Python 3.4. Have added the suspicious lines from the log below with a link to the log as well.

```python
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy==1.12.1
  - pandas==0.19.1 -> numpy=1.11
  - pyarrow
Use "conda info <package>" to see the dependencies for each package.
```

ref: https://travis-ci.org/dask/dask/jobs/375566458#L779-L783

**Comment by mrocklin** [comment]
I'm seeing an inability to import toolz.  My first guess would be that
conda failed on this build (which happens occasionally).

**Comment by jakirkham** [comment]
Agreed. The snippet above is where I think this install failure occurred.

**Comment by jakirkham** [comment]
Attempting to fix this in PR ( https://github.com/dask/dask/pull/3482 ).
