### ISSUE TITLE
Large data and multiprocessing fails

### ISSUE THREAD

**Issue by david-hoffman** [dask/dask#3489]
I'm trying to use `dask.array` and multiprocessing to build an array, but the final move back to main memory fails. This same example will work with the threaded back end.

```python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: import dask

In [3]: import dask.multiprocessing

In [4]: import dask.array as da

In [5]: shape = (4986, 800, 10000)

In [6]: datalarge = np.zeros(shape, dtype="uint8")

In [7]: @dask.delayed
   ...: def nothing(d):
   ...:     return d
   ...:
   ...:

In [8]: flat = da.from_delayed(dask.delayed([nothing(d) for d in datalarge]), datalarge.shape, datalarge.dtype)

In [9]: flat
Out[9]: dask.array<from-value, shape=(4986, 800, 10000), dtype=uint8, chunksize=(4986, 800, 10000)>

In [10]: from dask.diagnostics import ProgressBar

In [11]: with ProgressBar():
    ...:     flat = flat.compute(get=dask.multiprocessing.get)

```

The last line will just hang.

**Comment by shoyer** [comment]
This is a 40 GB array. How much memory does your machine have?

Python's multiprocessing uses pickle, so my guess is that computing this array would entail 3-4x memory overhead.

**Comment by mrocklin** [comment]
Note that when you call `.compute()` you are bringing the entire result
into memory as a numpy array.  This may not be what you want.  Often people
only call compute on finished results that tend to be a bit smaller.

**Comment by mrocklin** [comment]
In your situation I would investigate things further, perhaps by seeing at what size things fail.  

This seems to have gone stale, so I'm going to close for now.  If you come up with more information or have questions let us know here and we'll reopen.
