### ISSUE TITLE
reading parquet file from azure data lake store

### ISSUE THREAD

**Issue by jsolack** [dask/dask#3490]
i'm getting an known protocol when trying to connect to data lake store

dd.read_parquet('adl://xxxx.azuredatalakestore.net/yyyy')

is this something that is supported

**Comment by martindurant** [comment]
You would need to install and import the following https://github.com/dask/dask-adlfs/ The import is required to register `adl://` with dask. 
That repo has not been touched in some time, and was never officially released, so I am not sure of its status and would certainly say that is is not "supported". Please let us know if it works for you.

**Comment by martindurant** [comment]
Closing as stale
