### ISSUE TITLE
Can't pickle nancumsum

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#3492]
```
>>> import pickle
>>> import dask.array as da
>>> a = da.ones(2, chunks=1)
>>> b = da.nancumsum(a, 0)
>>> pickle.dumps(b)

PicklingError: Can't pickle <function nancumsum at 0x7ff9380f7488>: it's not the same object as numpy.lib.nanfunctions.nancumsum
```
Oddly, cumsum has no such problem:
```
>>> c = da.cumsum(a, 0)
>>> pickle.dumps(c)
b'\x80\x03cdask.array.core\nArray\nq\x00(cdask.sharedict\nShareDict\nq\x01)\x81q\x02}q\x03X\x05\x00\x00\x00dictsq\x04}q\x05(X\'\x00\x00\x00cumsum-f6390a2e35917cc6da2b155edf4088ddq\x06}q\x07(h\x06K\x00\x86q\x08(cdask.compatibility\napply\nq\tcnumpy.core.fromnumeric\ncumsum\nq\n]q\x0bX(\x00\x00\x00wrapped-feb776511226dafe0d6a6b9b53b2ece2q\x0cK\x00\x86q\ra}q\x0eX\x04\x00\x00\x00axisq\x0fK\x00stq\x10h\x06K\x01\x86q\x11(h\th\n]q\x12h\x0cK\x01\x86q\x13ah\x0etq\x14uh\x0c}q\x15(h\x0cK\x00\x86q\x16cfunctools\npartial\nq\x17cnumpy.core.numeric\nones\nq\x18\x85q\x19Rq\x1a(h\x18)}q\x1bX\x05\x00\x00\x00dtypeq\x1cX\x02\x00\x00\x00f8q\x1dsNtq\x1ebK\x01\x85q\x1f\x86q h\x0cK\x01\x86q!h\x1aK\x01\x85q"\x86q#uX.\x00\x00\x00cumsum-axis=0-4c19182a7c285d0b2246a35ad98be024q$}q%(h$X\x05\x00\x00\x00extraq&K\x00\x87q\'(cnumpy.core.numeric\nfull\nq(K\x01\x85q)K\x00cnumpy\ndtype\nq*X\x02\x00\x00\x00f8q+K\x00K\x01\x87q,Rq-(K\x03X\x01\x00\x00\x00<q.NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq/btq0h$K\x00\x86q1h\x06K\x00\x86q2h$h&K\x01\x87q3cdask.array.reductions\n_cumsum_merge\nq4h$h&K\x00\x87q5c_operator\ngetitem\nq6h\x06K\x00\x86q7cbuiltins\nslice\nq8J\xff\xff\xff\xffNN\x87q9Rq:\x85q;\x87q<\x87q=h$K\x01\x86q>h4h3h\x06K\x01\x86q?\x87q@uusbh$K\x01K\x01\x86qA\x85qBh-tqCRqD.'
```

**Comment by jakirkham** [comment]
What NumPy and Dask versions are you using?

**Comment by jrbourbeau** [comment]
I got a similar error as @crusaderky with Dask 0.17.4+33.g4a2c72c4, NumPy 1.14.2, and Python 3.6.4. The example 

```python 
import pickle
import dask.array as da

a = da.ones(2, chunks=1)
b = da.nancumsum(a, 0)
pickle.dumps(b)
```

yields 

```
Traceback (most recent call last):
  File "test_scripts/pickle_nancumsum.py", line 5, in <module>
    pickle.dumps(b)
_pickle.PicklingError: Can't pickle <function nancumsum at 0x10b6c66a8>: it's not the same object as numpy.lib.nanfunctions.nancumsum
```

For what it's worth, using `cloudpickle` instead of `pickle` doesn't raise any errors.

**Comment by crusaderky** [comment]
numpy                     1.14.3           py36hcd700cb_1  
dask                      0.17.5                   py36_0

**Comment by jakirkham** [comment]
Thanks for checking @jrbourbeau. :)

It could be that we are using closures here, which won't work with `pickle`. Though they normally work fine with `cloudpickle` and `dill`.

What's the use case for pickling this operation?

**Comment by jakirkham** [comment]
Should add that PR ( https://github.com/dask/dask/pull/3385 ) likely fixes this issue.

cc @mrocklin

**Comment by jakirkham** [comment]
Also would be interesting to know more about the motivation of pickling Dask Array functions.

**Comment by crusaderky** [comment]
@jakirkham I'm not trying to pickle a da function; I'm trying to pickle the graph it produces.
For two reasons:
1. ``distributed`` first tries serializing the graph with pickle, and when it fails it silently falls back to cloudpickle - see https://github.com/dask/distributed/issues/1371. The reason for not going for cloudpickle directly is that pickle is faster and produces smaller binary output. Being able to send to the grid a kernel you just wrote in your jupyter notebook is great for prototyping, but it should be avoided in production for this reason. Note that if ANY node of the dask graph fails to pickle, the WHOLE dask graph will be cloudpickled and any work you already spent pickling will be wasted.
2. My production problem is _big_. It takes north of 10 minutes to define the dask graph. So it's very convenient, at the end of it, to pickle both the final output and all the intermediate steps (10 seconds) to offer them to the user for forensics and fiddling purposes.

**Comment by crusaderky** [comment]
Can't reproduce anymore with dask 1.2
