### ISSUE TITLE
WARNING:botocore.vendored.requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by ghost** [dask/dask#3493]
When using read_parquet with s3 I get hundreds of:

```WARNING:botocore.vendored.requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: ...
```
There are > 1000 parquet segments on s3. I haven't found a way to fix it yet other than sync.

**Comment by martindurant** [comment]
There are a number of mentions of this kind of situation with botocore/boto3. The parameter in [this PR](https://github.com/boto/botocore/pull/1026) was introduced to try to eliminate it, can you try to add it to the s3 client config?

**Comment by brianmingus** [comment]
I needed a huge connection pool to get rid of the message.

```python
ddf.read_parquet('s3://my-bucket', 
                           storage_options={'config_kwargs': {'max_pool_connections': 2500}})
```

**Comment by martindurant** [comment]
How many threads are you running? If you don't know, it's commonly equal to the number of CPU cores, as seen by python.

**Comment by brianmingus** [comment]
36 cores. I only ever see Dask use 18 of them.

**Comment by martindurant** [comment]
Hm. Are there very many partitions? I wonder if boto3 is not reaping connections until the Session is done (when compute finishes). The docs say that you should never have to care about reaping connections from the pool.

**Comment by brianmingus** [comment]
There are about 1500 partitions in this case.

**Comment by mrocklin** [comment]
@martindurant is there something concrete we can do here to resolve this problem?  If so can you help to explain what that might be?  If not then can you close?

**Comment by martindurant** [comment]
I don't think we need to do anything, this is a boto problem specifically, although we are using it in a way they perhaps haven't anticipated.

**Comment by mrocklin** [comment]
Are Dask users today OK?  To be clear I'm not asking "is it our fault or
theirs" I'm asking if there are things that dask users will run into today
that we should resolve

**Comment by martindurant** [comment]
It seems like a rare possibility, but I would not advocate trying to automatically set the boto session parameters for our users. This will happen only in the case where many threads (not processes) are doing simultaneous s3 work.
