### ISSUE TITLE
RLS: 0.17.5

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3503]
The 0.23 pandas release caused a few issues, so I'd like to release 0.17.5 today. Master has some changes that may need to wait a while, so I'd like to branch 0.17.5 off the 0.17.4 tag and include the changes from https://github.com/dask/dask/pull/3499.

Is there anything else we want to backport?

**Comment by jakirkham** [comment]
Sounds good.

Would suggest grabbing commit ( https://github.com/dask/dask/commit/4756b59050ab3478b5dd197093d0d28e7b8a33fd ) and ( https://github.com/dask/dask/commit/5826ae0a108deedfca24e4d31db5f28a9e196026 ).

Might also grab commit ( https://github.com/dask/dask/commit/7c419580037f552befc2650cb13967dd6bdef86a ), but leave that up to you.

**Comment by jakirkham** [comment]
Good to close?

**Comment by TomAugspurger** [comment]
Yep, thanks!
