### ISSUE TITLE
Automatic rechunking along particular axes

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3506]
In support of #2225 and #3109 we would like to collapse some dimensions in a dask array while making others more granular if necessary in order to compensate.  We might do this today explicitly with rechunk:

```python
x = x.rechunk({0: 1000, 1: -1, 2: 500, 3: -1})  # collapse dimensions 1 and 3, make 0 and 2 more granular
```

Where presumably dimensions 0 and 2 had chunks larger than 1000 and 500 previously.  In #2225 we learn that doing this well is both tricky and critical for performance when doing operations like `x.dot(x.T)`, which is common.  It would be ideal if we could add some automation so that functions like `atop` could optionally call rechunk as follows:

```python
x = x.rechunk({0: 'auto', 1: -1, 2: 'auto', 3: -1}, block_size_limit=1e8)
```

Ideally setting some dimensions to `"auto"` would ensure that we would cut up blocks as needed to ensure that blocks get close to the size limit, but that no blocks exceed it.  

I'm currently planning to work this into `normalize_chunks`, but thought I'd advertise the intent before I do much work.

**Comment by martindurant** [comment]
How does this interact with #3488 ?

**Comment by mrocklin** [comment]
I'm not planning any interaction

**Comment by shoyer** [comment]
This makes sense to me
