### ISSUE TITLE
Unclear precedence between scheduler and get with dask.config.set()

### ISSUE THREAD

**Issue by shoyer** [dask/dask#3512]
This came up in the xarray test suite when I was in the midst of refactoring to it to use `scheduler=` instead of `get=`:
```python
import dask

count = [0]

def counting_get(*args, **kwargs):
    count[0] += 1
    return dask.get(*args, **kwargs)

dask.config.set(scheduler='sync')

dask.delayed(1).compute(get=counting_get)
assert count[0] == 1  # passes

with dask.config.set(get=counting_get):
    dask.delayed(1).compute()
assert count[0] == 2  # fails, because get was silently ignored
```

More generally, the problem is that it's possible to set *both* `get` and `scheduler` in `dask.config.set` (e.g., `dask.config.set(get=counting_get, scheduler='sync')`), but it isn't clear which setting takes precedence.

My suggestions:
- If setting `get` is explicitly in an inner context, it should take precedence over `scheduler`.
- It should be an error to try to set both `get` and `scheduler` at the same time.

**Comment by mrocklin** [comment]
I agree that this is an issue.

> If setting get is explicitly in an inner context, it should take precedence over scheduler.

It's not easy for us to determine the scope of configuration changes.  

We could however generally prefer `get=` over `scheduler=` , which might make sense.

> It should be an error to try to set both get and scheduler at the same time.

This also makes sense

Any preferences?

**Comment by shoyer** [comment]
If can't easily determine the scope, then erroring would certainly be better than silent failure.

**Comment by mrocklin** [comment]
The alternative would be to prefer get= over scheduler=.  The argument
would be that get= is lower level, and so arguably more explicit.

**Comment by shoyer** [comment]
Okay then. No strong preference from me :)

**Comment by ed-alertedh** [comment]
Sorry if this is a little off-topic, but was there an old way to set the default scheduler everywhere before `dask.config` was introduced? I'm on the latest stable release and trying to work out the easiest way to run everything on the single-threaded scheduler for debugging.

**Comment by jakirkham** [comment]
+1 for preferring `get` over `scheduler` when set.

Long term we should figure out how we want to have the same level of control for whatever new interface evolves. ( https://github.com/dask/dask/issues/3708 )

**Comment by mrocklin** [comment]
We've removed the `get=` option.
