### ISSUE TITLE
`astype` broken for partitioned parquet files

### ISSUE THREAD

**Issue by gsakkis** [dask/dask#3518]
Computing `dask.dataframe.astype` on partitioned parquet files either fails with `ValueError` or (worse) messes up the column order. Self-contained example below:

```python
import numpy as np
import pandas as pd
import dask, dask.dataframe as dd

print('dask:', dask.__version__)

data = {
    'p': np.repeat(np.arange(3), 2).astype(np.int8),
    'b': np.repeat(-1, 6).astype(np.int16),
    'c': np.repeat(-2, 6).astype(np.float32),
    'd': np.repeat(-3, 6).astype(np.float64),
}
pdf = pd.DataFrame(data)
print('Original df:\n{}\n'.format(pdf))

path = 'test_df.pq'
ddf = dd.from_pandas(pdf, npartitions=2)
ddf.to_parquet(path, engine='pyarrow', partition_on='p')

ddfs = [
    dd.read_parquet(path),
    dd.read_parquet(path, columns=['p', 'b']),
    dd.read_parquet(path, columns=['p', 'b', 'd']),
]

for i, df in enumerate(ddfs):
    try:
        converted = df.astype({'b': np.float32}).compute()
    except ValueError:
        print('ddfs[{}]: Failed to convert\n'.format(i))
    else:
        print('ddfs[{}] head:\n{}\n'.format(i, converted.head()))
```
Output:
```
dask: 0.17.5
Original df:
   b    c    d  p
0 -1 -2.0 -3.0  0
1 -1 -2.0 -3.0  0
2 -1 -2.0 -3.0  1
3 -1 -2.0 -3.0  1
4 -1 -2.0 -3.0  2
5 -1 -2.0 -3.0  2

ddfs[0]: Failed to convert

ddfs[1] head:
     p  b
0 -1.0  0
1 -1.0  0
0 -1.0  0
1 -1.0  0
0 -1.0  0

ddfs[2] head:
     p    b  d
0 -1.0 -3.0  0
1 -1.0 -3.0  0
0 -1.0 -3.0  0
1 -1.0 -3.0  0
0 -1.0 -3.0  0
```

Possibly related to #3361.

**Comment by mrocklin** [comment]
Thank you for the excellent bug report @gsakkis . My apologies for the delay.

@martindurant, this seems to be in your realm.  If you have time can you take a look at this and give your impression about what might be amiss?

**Comment by martindurant** [comment]
I'll take a look.

**Comment by martindurant** [comment]
I would probably fix it on the dask side by, within `_read_pyarrow`, passing `meta` to `_read_pyarrow_parquet_piece` and enforcing columns/types on the output of that function; although it may well be that the fault is in the detail of `_read_pyarrow_parquet_piece`.

**Comment by martindurant** [comment]
@gsakkis , any progress here?

**Comment by gsakkis** [comment]
@martindurant my current workaround is to call `dd.read_parquet()` with a `columns` list parameter that includes the partition column as the last column (along with a XXX comment of why this is needed) but I'm not familiar enough with dask/pyarrow internals to fix it myself.
