### ISSUE TITLE
da.map_blocks chunk alignment

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3519]
I'm not sure if this is a bug, but wanted to confirm.

I want to slice a 2D dask array with another 1D dask array of integers. The 1D array as a special structure, which allows me to implement things more efficiently than in https://github.com/dask/dask/pull/3407. Each chunk in the 1D array represents slices for that particular block, so the elements are between `[0, len(block))`. No communication is required between blocks.

```python
x = da.random.uniform(size=(10, 4), chunks=4)
y = da.random.randint(0, 4, size=(6,), chunks=(2,))

chunks = (y.chunks[0], x.chunks[1])
da.map_blocks(lambda u, v: u[v], x, y, chunks=chunks, dtype=X.dtype)
```

The last line raises with

```pytb
ValueError                                Traceback (most recent call last)
<ipython-input-40-59f78381f835> in <module>()
----> 1 da.map_blocks(lambda u, v: u[v], x, y, chunks=chunks, dtype=X.dtype)

~/sandbox/dask/dask/array/core.py in map_blocks(func, *args, **kwargs)
    750                     raise ValueError("Dimension {0} has {1} blocks, "
    751                                      "chunks specified with "
--> 752                                      "{2} blocks".format(i, nb, len(c)))
    753                 chunks2.append(c)
    754             else:

ValueError: Dimension 1 has 3 blocks, chunks specified with 1 blocks
```

The docs say

```
Map_blocks aligns blocks by block positions without regard to shape. In the
following example we have two arrays with the same number of blocks but
with different shape and chunk sizes.
```

Should this work, or am I misreading something?

**Comment by mrocklin** [comment]
This works (note the `[:, None]`)

```python
da.map_blocks(lambda u, v: u[v], x, y[:, None], chunks=chunks, dtype=x.dtype)
```

Broadcasting rules perhaps suggest that the chunking of the last axis should be the same.  Here x has 1 chunk while y has 3.

Also, I'm not sure if this is the application or not, but if you're trying to slice one array by another in order to achieve per-block shuffling then I would recommend applying a function that generated and then sliced the data all in one go.  The distributed scheduler doesn't currently schedule two leaf tasks that will eventually have to interact on the same node, so some communication is likely to occur here.

**Comment by TomAugspurger** [comment]
> Broadcasting rules perhaps suggest that the chunking of the last axis should be the same. Here x has 1 chunk while y has 3.

Ah, yes, I flipped that rule in my head (first instead of last).

> achieve per-block shuffling then I would recommend applying a function that generated and then sliced the data all in one go.

that is the use-case. I'll do some performance profiling later today.

**Comment by mrocklin** [comment]
You may want to look at _Frame.random_split

https://github.com/dask/dask/blob/83107230c0bad0cd901ea4f86667c42250aff649/dask/dataframe/core.py#L826-L867
