### ISSUE TITLE
Dataframes from read_sql_table create too many DB connections. This makes Dask unusable with Multi-Factor Auth

### ISSUE THREAD

**Issue by Myles1** [dask/dask#3533]
```
from dask import dataframe as dd
df = dd.read_sql_table(table='my_table_name', uri=my_sqlalchemy_con_url, index_col='id')
print(len(df))
```
This results in 11 multi-factor authentication messages (depends on the size of the table)
One connection to read into the df
One connection per method call
One connection per partition per method call for distributed df's.

This issue results in Dask being completely unusable at my company.
We want to switch from Spark, but are not able to because of the MFA issue.

Solution:
Reuse one single connection for each method call.

**Comment by mrocklin** [comment]
It might be worth investigating how SQLAlchemy, the underlying library that dask.dataframe/pandas uses for SQL connectivity, handles these issues.  It's quite mature.  Presumably there is something within SQLAlchemy that can assist here.

**Comment by Myles1** [comment]
@mrocklin you're right. The issue isn't 11 connections or the MFA. It's the scaling of the connections.
`n_connections = n_operations * n_partitions`
Dataset with 50 partitions and a script with 20 operations? That's 1,000 connections to the db.

**Comment by martindurant** [comment]
What is an "operation" here? Depending on what you mean, you maybe could reduce this number by combining queries in a single call to `compute()`, by calling `persist()` on some common intermediate precursor to your calculations.

**Comment by Myles1** [comment]
Literally anything that touches the data. Once per method call. It doesn't matter where you put the compute call, and calling persist isn't an option because of the size of the data.

**Comment by martindurant** [comment]
OK, so the principle problem is the following line in `read_sql_table`:
```
engine = sa.create_engine(uri)
```
This exists, because the engine object contains a cache and connections pools, etc., and so cannot be serialised to workers. I don't believe sqlalchemy has any mechanism to fetch active engines from a process-wide cache upon recognising a URL, but that is what you are after here. Since you are presumably always connecting to the same DB, it would not be hard for you to swap out that line with a "connect_if_no_engine_yet" function, or create engines upfront in each worker (because of racing).

**Comment by martindurant** [comment]
@Myles1 , did you have a chance to implement my suggestions above?

**Comment by martindurant** [comment]
I am happy to help create the right behaviour for you, but this issue is getting old now, so I suspect either it was solved, or @Myles1 , you have moved onto something else.

**Comment by Myles1** [comment]
I did move on, but I might be able to take a look at changing the behavior this or next week if you don't have time. Thanks for your comments :)
