### ISSUE TITLE
Discrepancy between dask.array and numpy random streams

### ISSUE THREAD

**Issue by valentina-s** [dask/dask#3537]
When generating random numbers with a fixed state, I expected dask and numpy to produce the same stream, but they do not:

```
import dask.array as da
state = da.random.RandomState(1234)  # a seed
x = state.normal(10, 0.1, size=3, chunks=(2,))
x.compute()

array([10.01867852, 10.04812289,  9.89649746])
```

```
import numpy as np
state = np.random.RandomState(1234)
x = state.normal(10,0.1, size=3)

array([ 10.04714352,   9.88090243,  10.1432707 ])
```
My understanding is that dask wraps the numpy function, so I wonder why they are different.

dask version: '0.17.4'
numpy version: '1.12.1'

**Comment by mrocklin** [comment]
That's correct.  Numpy random number generation and Dask array random
number generation will not produce exactly the same stream of numbers.  The
constraints of parallel implementations forces these to behave differently.
