### ISSUE TITLE
QR Decomposition: Short and Fat?

### ISSUE THREAD

**Issue by convexset** [dask/dask#3548]
Hi, it seems that Western beauty standards have crept into `dask.array.linalg.qr`. Only "tall and skinny" (single column of blocks).

There doesn't seem to be room for the "short and fat". It seems that a quick fix.
```
QR = A = [ A_1 | A_2 | ... | A_n ]
```
Doing a decomposition for the first square matrix...
```
Q R_1 = A_1
```
... and then...
```
R_i = Q'A_i
```
which should be a quick supplementation to the existing QR method.

**Comment by convexset** [comment]
Quickly...
```
A = da.random.random((4, 10), chunks=4)

# short and fat QR
A_sq = A[:, :A.shape[0]]
A_rest = A[:, A.shape[0]:]
q, r_sq = da.linalg.qr(A_sq)
r_rest = q.T.dot(A_rest)
r = da.concatenate([r_sq, r_rest], axis=1)

((q.dot(r) - A < 1e-14).all()).compute()  # they match up
```

**Comment by mrocklin** [comment]
> Hi, it seems that Western beauty standards have crept into dask.array.linalg.qr

Heh, guilty as charged.  :)

Any interest in submitting a PR?

**Comment by convexset** [comment]
I don't mind... but any pointers to how to get started contributing and guidelines?

**Comment by convexset** [comment]
The quick and dirty version is something that might be done fast, but I'd like to learn the internals a little more so as to handle arrays with multiple blocks on the row dimension, that would probably entail some "joins" where there is waiting for other operations to complete. Any pointers to well written code that fits that bill for arrays?

**Comment by mrocklin** [comment]
The linear algebra code is likely to be a somewhat complex introduction to
dask.array.  I recommend starting with a pull request that implements the
simple solution, and then following up later with a more complex solution.

In practice I expect that tall-and-skinny or short-and-fat arrays are
likely to be the common case, and that rechunking the array to have a
single chunk in one dimension is likely to be the most efficient solution
in these cases.

**Comment by convexset** [comment]
I have written something (with an accompanying modification to `qr` which does the normal thing when the number of chunks width-wise is 1. That is at the bottom.

But I'm not too satisfied because I find myself not exactly sure how to construct an `Array` from a `delayed(np.linalg.qr)(A)` after doing the required `delayed(operator.getitem)` without using a `ShareDict`. This doesn't work...
```
M = np.array([[3,4,4,3],
              [4,3,4,4]])
A = da.from_array(M, chunks=2).persist()

Q_R = dask.delayed(np.linalg.qr)(A)
Q = dask.delayed(operator.getitem)(qr, 0)
R = dask.delayed(operator.getitem)(qr, 1)
print (Q.compute().dot( R.compute() ))  # this is fine
RR = Array(r.dask, r.name,
           shape=data.shape,
           chunks=(len(data.chunks[0]), len(data.chunks[1])),
           dtype=A.dtype)
print(RR.compute())
# rr.visualize()
```
I'm alright submitting the below where (a `ShareDict` is used so) output has proper dimensions.

```
def sfqr(data, name=None):
    """ Direct Short-and-Fat QR

    Currently, this is a quick hack for non-tall-and-skinny matrices which
    are one chunk tall and (unless they are one chunk wide) have chunks
    that are wider than they are tall
    
    Q [R_1 R_2 ...] = [A_1 A_2 ...]
    
    it computes the factorization Q R_1 = A_1, then computes the other
    R_k's in parallel.

    Parameters
    ----------

    data: Array

    See Also
    --------

    dask.array.linalg.qr - Supported by this
    """

    nr, nc = len(data.chunks[0]), len(data.chunks[1])
    cr, cc = data.chunks[0][0], data.chunks[1][0]

    if not ((data.ndim == 2) and  # Is a matrix
            (nr == 1) and         # Has exactly one block row
            ((cr <= cc) or        # Chunking dimension on rows is at least that on cols or...
             (nc == 1))           # ... only one block col
           ):
        raise ValueError(
            "Input must have the following properties:\n"
            "  1. Have two dimensions\n"
            "  2. Have only one row of blocks\n"
            "  3. Either one column of blocks or chunking dimension on rows is at most that on cols"
        )

    prefix = name or 'sfqr-' + tokenize(data)
    prefix += '_'

    m, n = data.shape
    numblocks = (1, nc)

    qq, rr = np.linalg.qr(np.ones(shape=(1, 1), dtype=data.dtype))

    dsk = sharedict.ShareDict()
    dsk.update(data.dask)

    # data = A = [A_1 A_rest]
    name_A_1 = prefix + 'A_1'
    name_A_rest = prefix + 'A_rest'
    dsk.update_with_key({
        (name_A_1, 0, 0): (data.name, 0, 0)
    }, key=name_A_1)
    dsk.update_with_key({
        (name_A_rest, 0, idx): (data.name, 0, 1 + idx)
        for idx in range(nc - 1)
    }, key=name_A_rest)

    A_1 = Array(dsk, name_A_1,
                shape=(cr, cc), chunks=(cr, cc), dtype=qq.dtype)

    # Q R_1 = A_1
    name_Q_R1 = prefix + 'Q_R_1'
    name_Q = prefix + 'Q'
    name_R_1 = prefix + 'R_1'
    dsk.update_with_key({
        (name_Q_R1, 0, 0): (np.linalg.qr, (name_A_1, 0, 0))
    }, key=name_Q_R1)
    dsk.update_with_key({
        (name_Q, 0, 0): (operator.getitem, (name_Q_R1, 0, 0), 0)
    }, key=name_Q)
    dsk.update_with_key({
        (name_R_1, 0, 0): (operator.getitem, (name_Q_R1, 0, 0), 1),
    }, key=name_R_1)

    Q = Array(dsk, name_Q,
              shape=(m, min(m, n)), chunks=(m, min(m, n)), dtype=qq.dtype)
    R_1 = Array(dsk, name_R_1,
                shape=(min(m, n), min(m, n)), chunks=(cr, cc), dtype=rr.dtype)

    # R = [R_1 Q'A_rest]
    Rs = [R_1]

    if nc > 1:
        A_rest = Array(dsk, name_A_rest,
                       shape=(min(m, n), n - min(m, n)), chunks=(cr, cc), dtype=rr.dtype)
        Rs.append(Q.T.dot(A_rest))

    R = da.concatenate(Rs, axis=1)
    
    return Q, R
```

**Comment by convexset** [comment]
Stuff I'd like to learn to be able to better contribute would be:
 - how to convert `o.dask` items that are arrays of known dimensions and chunking into arrays via `Array` or something
 - how to pass keyword arguments into methods (in a `ShareDict`)
 - what the proper structure for items are in the `ShareDict`

I had to figure out that arrays would take the form:
```
{
  # ...
  "arr-hashhash-etc": {
    ("arr-hashhash-etc", 0, 0): (op, (src, 0, 0), arg1, arg2, ...),
    ("arr-hashhash-etc", 0, 1): (op, (src, 0, 1), arg1, arg2, ...),
    ("arr-hashhash-etc", 1, 0): (op, (src, 1, 0), arg1, arg2, ...),
    ("arr-hashhash-etc", 1, 1): (op, (src, 1, 1), arg1, arg2, ...),
  },
  # ...
}
```
So a good reference would be nice.

I guess structure of the core distributed objects are defined by:
 - bags with `npartitions`
 - dataframes with `npartitions`, `columns` and `dtypes`
 - arrays have `shape` and `chunks`

So it would be good to know how to represent these in the "list of computations" which is the `ShareDict`, and how to extract items (so those 3 plus generic objects).

**Comment by mrocklin** [comment]
Thanks for the notes @convexset .  Dask array is probably the most advanced of the Dask collections (it tends to have the most advanced algorithms, and so has the most performance pressure on it) and so I can appreciate that it's a bit of a challenge to dive in.  

If you haven't already you should read http://dask.pydata.org/en/latest/array-design.html and the docstring of ShareDict (apparently we don't have any online docs for this?).  

Regarding your questions about delayed and Dask arrays I suggest that you don't go down this path.  Calling delayed functions on dask array objects doesn't parallelize those functions, instead it converts the dask arrays to numpy arrays when the function is called.  So in the following case:

> But I'm not too satisfied because I find myself not exactly sure how to construct an Array from a delayed(np.linalg.qr)(A) 

You're not constructing a Dask array, you're lazily converting `A` to a numpy array, then calling the `np.linalg.qr` call on it, and returning it as a lazy numpy arrays.

Instead, for short-and-fat QR decomposition, I wonder if we can reuse the existing solution to this problem by transposing the array, calling the tall-and-skinny QR decomposition, and then transposing the results.

**Comment by convexset** [comment]
Ok, so I guess my code snippet works fine because the approach using delayed would just not distribute. I'll send a PR.

Also... we can't just transpose the solution... (QR)' = R' Q'.

**Comment by convexset** [comment]
... I'll add tests first.

**Comment by convexset** [comment]
See: PR https://github.com/dask/dask/pull/3575

**Comment by jakirkham** [comment]
> Also... we can't just transpose the solution... (QR)' = R' Q'.

When reading this, this was my initial thought. Should be possible. We are able to transpose arrays.

**Comment by convexset** [comment]
Matrix multiplication is mostly not commutative. So what we get is the orthogonal matrix on the right. It's a common idea people have when going through numerical linear algebra though.
