### ISSUE TITLE
"New"/"Previous" swapped in Parquet writing error message?

### ISSUE THREAD

**Issue by seibert** [dask/dask#3553]
I think the meaning of "New" and "Previous" are swapped in this error message:

https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L412-L414

I would have expected the columns already on disk (`pf.columns`) to be labelled as "Previous", and the data about to be appended (`list(df.columns)`) to the Parquet file as "New".

Just wanted to sanity check my understanding before opening a PR to change the message.

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
I don't recall anything being done, but it's been a while. The relevant code does not seem to have changed since this issue.

**Comment by mrocklin** [comment]
If you get a chance can I ask you to make a small PR to solve this?  My hope is that this would take less than five minutes.

**Comment by martindurant** [comment]
If I trust my statement above, I can just replace New and Previous, indeed quick. Should probably spend a few minutes making sure its true!
