### ISSUE TITLE
Simplify graph produced by da.from_array

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#3556]
```
>>> dict(da.from_array(np.array([1, 2]), chunks=2).__dask_graph__())
{
    ('array-de932becc43e72c010bc91ffefe42af1', 0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'array-original-de932becc43e72c010bc91ffefe42af1', (slice(0, 2, None),)),
    'array-original-de932becc43e72c010bc91ffefe42af1': array([1, 2])
}

>>> dict(da.from_array(np.array([[1, 2], [3, 4]]), chunks=(1, 2)).__dask_graph__())
{
    ('array-7cb83fc33e4505ed4b89aa67e13272f7', 0, 0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'array-original-7cb83fc33e4505ed4b89aa67e13272f7', (slice(0, 1, None), slice(0, 2, None))),
    ('array-7cb83fc33e4505ed4b89aa67e13272f7', 1, 0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'array-original-7cb83fc33e4505ed4b89aa67e13272f7', (slice(1, 2, None), slice(0, 2, None))),
    'array-original-7cb83fc33e4505ed4b89aa67e13272f7': array([[1, 2], [3, 4]])
}
```
The above two should really just produce:
```
>>> dict(da.from_array(np.array([1, 2]), chunks=2).__dask_graph__())
{('array-de932becc43e72c010bc91ffefe42af1', 0): array([1, 2])}

>>> dict(da.from_array(np.array([[1, 2], [3, 4]]), chunks=(1, 2)).__dask_graph__())
{
    ('array-7cb83fc33e4505ed4b89aa67e13272f7', 0, 0): (<function _operator.getitem>, 'array-original-7cb83fc33e4505ed4b89aa67e13272f7', (slice(0, 1, None))),
    ('array-7cb83fc33e4505ed4b89aa67e13272f7', 1, 0): (<function _operator.getitem>, 'array-original-7cb83fc33e4505ed4b89aa67e13272f7', (slice(1, 2, None))),
    'array-original-7cb83fc33e4505ed4b89aa67e13272f7': array([[1, 2], [3, 4]])
}
```

**Comment by mrocklin** [comment]
In particular, the slicing optimizations can be pretty involved.  There are a number of important use cases that depend on slicing in particular ways.

**Comment by crusaderky** [comment]
@mrocklin sorry I don't see it. If I slice an Array with ``[:1]``, it does use operator.getitem.
I'm sure there are sophisticated use cases that warrant ``dask.array.core.getter`` - but this clearly isn't one of them?
Also I fail to understand why the trivial case of a single chunk should produce two nodes.

**Comment by mrocklin** [comment]
For getter I recommend making the change, running the test suite, and then
seeing the names of the tests that fail.

Hrm, I suspect that the two node case would fail if you were slicing from
an h5py dataset.  If objects are top-level then I think that they get
custom serialization treatment in a way that they don't if they're buried
within tasks.

All this is to say that some things that look strange are strange for a
reason, and that I generally recommend asking questions before embarking on
work.

**Comment by mrocklin** [comment]
To be clear, I mean using an h5py dataset with the distributed scheduler
with multiple processes
