### ISSUE TITLE
[Bug?] Index changes when calling 'to_frame()' method 

### ISSUE THREAD

**Issue by henriqueribeiro** [dask/dask#3564]
When calling `to_frame()` method on a dataframe index it gave me different outputs whenever I give it a name or not. I cannot really understand if this is a bug or not but I will leave an example here.

### Generate Dataframe

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

d = {'index': range(10),
     'data': np.random.normal(size=10)
    }
df = pd.DataFrame(d).set_index('index')
ddf = dd.from_pandas(df, npartitions=2)
ddf.compute()
```
<table border="0" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>data</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.454431</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-0.210278</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.710888</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-2.292036</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-0.036463</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-0.413318</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.169958</td>
    </tr>
    <tr>
      <th>7</th>
      <td>-2.755862</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.416129</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2.203884</td>
    </tr>
  </tbody>
</table>

### The problem

If I run the following command without the 'name' parameter, I get this:
```python
ddf.index.to_frame().compute()
```
<table border="0" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>index</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
    </tr>
    <tr>
      <th>0</th>
      <td>5</td>
    </tr>
    <tr>
      <th>1</th>
      <td>6</td>
    </tr>
    <tr>
      <th>2</th>
      <td>7</td>
    </tr>
    <tr>
      <th>3</th>
      <td>8</td>
    </tr>
    <tr>
      <th>4</th>
      <td>9</td>
    </tr>
  </tbody>
</table>

However, if I run it with a random name, I get this:
```python
ddf.index.to_frame('a').compute()
```
<table border="0" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>index</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>5</td>
    </tr>
    <tr>
      <th>6</th>
      <td>6</td>
    </tr>
    <tr>
      <th>7</th>
      <td>7</td>
    </tr>
    <tr>
      <th>8</th>
      <td>8</td>
    </tr>
    <tr>
      <th>9</th>
      <td>9</td>
    </tr>
  </tbody>
</table>

As can be seen, the index of the 'index Dataframe' is different on both cases. Also,  the name that I insert seems 'useless'. 

Do you have any thought about this? Is it a bug?

Thanks in advance

**Comment by alvis** [comment]
I just bumped into a similar problem. Mine is a time series. When I convert it to a DataFrame, the DatetimeIndex is gone.

**Comment by TomAugspurger** [comment]
@henriqueribeiro it looks like pandas Index.to_frame doesn't take a `name` parameter. I'd recommend search on pandas issue tracker to see if this is a known issue. I'm not sure about losing the name of the `.index`, but we probably want to see what the expected pandas behavior is first.

@alvis do you have an example?

```python
In [51]: ts
Out[51]:
Dask DataFrame Structure:
                   id    name        x        y
npartitions=11
2000-01-31      int64  object  float64  float64
2000-02-29        ...     ...      ...      ...
...               ...     ...      ...      ...
2000-11-30        ...     ...      ...      ...
2000-12-31        ...     ...      ...      ...
Dask Name: make-timeseries, 11 tasks

In [52]: ts.index.to_frame()
Out[52]:
Dask DataFrame Structure:
                     timestamp
npartitions=11
2000-01-31      datetime64[ns]
2000-02-29                 ...
...                        ...
2000-11-30                 ...
2000-12-31                 ...
Dask Name: to_frame, 33 tasks

In [53]: ts.index.to_frame().head()
Out[53]:
            timestamp
0 2000-01-31 00:00:00
1 2000-01-31 00:00:10
2 2000-01-31 00:00:20
3 2000-01-31 00:00:30
4 2000-01-31 00:00:40

```

Out[52] is buggy, since the index metadata is incorrect.

**Comment by alvis** [comment]
Here is an example I have.

```python
import dask.dataframe as dd
import pandas as pd
import random

num = 5
timestamps = pd.date_range("2018-08-01", periods=num).to_series()
values = [random.random() for i in range(num)]

pdf = pd.DataFrame({"timestamp": timestamps, "values": values})
ddf = dd.from_pandas(pdf, npartitions=1)
series = ddf.groupby("timestamp").apply(lambda x: x["values"].mean(), meta="float64")
```

Here, the type of the original `timestamp` column in `ddf` is a `datatime64[ns]`.
```
In [27]: ddf["timestamp"]
Out[27]:
Dask Series Structure:
npartitions=1
2018-08-01    datetime64[ns]
2018-08-05               ...
Name: timestamp, dtype: datetime64[ns]
Dask Name: getitem, 2 tasks
```

Then after the grouping and conversion back to a dataframe, the type of the index, which is `timestamp` becomes `int64`.
```
In [28]: series.to_frame().index
Out[28]:
Dask Index Structure:
npartitions=1
    int64
      ...
dtype: int64
Dask Name: to_frame, 12 tasks
```

**Comment by TomAugspurger** [comment]
Hmm, your `meta` is "incorrect". If you fix it to be

```
    ...: series = ddf.groupby("timestamp").apply(lambda x: x["values"].mean(), meta=pd.Series(dtype="float64", index=pd.DatetimeIndex([], name='timestamp'))
    ...: )

In [17]: series.to_frame().index
Out[17]:
Dask Index Structure:
npartitions=1
    datetime64[ns]
               ...
Name: timestamp, dtype: datetime64[ns]
Dask Name: to_frame, 12 tasks

In [18]: series.to_frame().index.compute()
Out[18]:
DatetimeIndex(['2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04',
               '2018-08-05'],
              dtype='datetime64[ns]', name='timestamp', freq=None)

```

then things come out correctly I think.

I'm not sure whether we explicitly document how the index is treated in this case.

**Comment by alvis** [comment]
🤔  Actually, I'm not quite sure how to interpret the [doc on meta](http://dask.pydata.org/en/latest/dataframe-api.html?highlight=apply#dask.dataframe.DataFrame.apply). It says "Instead of a series, a tuple of (name, dtype) can be used." I tried `meta=("values", "float64")`, but it doesn't make a difference.

For `meta=pd.Series(dtype="float64", index=pd.DatetimeIndex([], name='timestamp')`, while it seems fixed the problem, it's actually not.

If you further try
```python
series.to_frame().to_parquet('./test')
```
then you would get `TypeError: Column name must be a string. Got column 0 of type int`.

I think there's a small hidden bug...

**Comment by TomAugspurger** [comment]
Specify `name='name'` for either your Series meta, or in `to_frame`.

Either way, I think your issue is distinct from the original issue, which
is about Index.to_frame.

**Comment by henriqueribeiro** [comment]
@TomAugspurger you are right. Pandas index.to_frame doesn't have `name` as an argument. I just did a pull request to pandas to add it. Let's wait and then we check it on dask also.

**Comment by mrocklin** [comment]
Any update on this @henriqueribeiro ?

**Comment by henriqueribeiro** [comment]
@mrocklin The PR on pandas was accepted and I will work on this soon.

**Comment by jrbourbeau** [comment]
@henriqueribeiro is it safe to close this issue as the `name` parameter was added to the index `to_frame` method in #4498?

**Comment by henriqueribeiro** [comment]
@jrbourbeau Sure, I close it! Thanks
