### ISSUE TITLE
regression tests failures: TypeError: can't pickle _thread.lock

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#3567]
I'm getting a plethora of failures in the regression tests - test_distributed, test_multiprocessing, test_threaded. They all fail with the message ``TypeError: can't pickle _thread.lock``.

This exclusively happens in the Master git branch (e1c48e0c970aeb81ffeb58791db2ca3ce76fa846). The 0.17.x branch (b2bed5eb145b39641181140b8f64a9b4427b53ba) is unaffected.

Running on Anaconda 5 Linux x86-64. Relevant entries from conda list:
```
cloudpickle               0.5.3                    py36_0  
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
distributed               1.21.8                   py36_0  
numpy                     1.14.3           py36h28100ab_2  
pandas                    0.23.0           py36h637b7d7_0  
python                    3.6.5                hc3d631a_2  
```

Related: #1683, #780, #1556

**Comment by crusaderky** [comment]
This problem only happens with dependencies from the anaconda repo. If I switch to conda-forge, the issue disappears.

**Comment by crusaderky** [comment]
Related: #3408

**Comment by mrocklin** [comment]
That sounds frustrating.  It would be good to fix this.  Are these failures
intermittent or consistent?  Which tests fail (or is this with your
personal code)?  My guess is that the right way to track this down is to
find a minimal reproducible example.

**Comment by mrocklin** [comment]
Closing due to lack of response
