### ISSUE TITLE
reblock?

### ISSUE THREAD

**Issue by convexset** [dask/dask#3569]
I was just exploring the code and noticed the occurrence of `reblock` in

https://github.com/dask/dask/blob/master/dask/array/learn.py#L71
https://github.com/dask/dask/blob/master/dask/array/learn.py#L101

... I looked for the implementation and couldn't find any, and later found out that it was replaced with `rechunk`.

**Comment by convexset** [comment]
PR #3570

**Comment by jakirkham** [comment]
This is still an issue in `dask-ml`. So reopening.

Will be addressed when PR ( https://github.com/dask/dask-ml/pull/208 ) is merged.

**Comment by mrocklin** [comment]
This appears to be merged. Closing
