### ISSUE TITLE
Suggestion: Implement dataframe.read_sql

### ISSUE THREAD

**Issue by martindurant** [dask/dask#3572]
We have dataframe.read_sql_table, which can work for a given table or sqlalchemy expression. In practice, we have people asking for a method which can take arbitrary SQL instead. (There is no way to parse arbitrary SQL into aqlalchemy expressions).

I am thinking that this could be a rather simple function of the form
```
dataframe.read_sql_query(connection_uri, query, where_clauses, divisions=None, index_col=None, meta=None)
```
i.e., the user must specify the set of `WHERE` text clauses to append to the query, appropriate for the target SQL dialect, which define the final query for each partitions. Providing the divisions (which presumably have the same values as encoded in where_clauses) and the index is optional, and not providing meta would result in having to load the first partition up front.

**Comment by MosheVai** [comment]
why add the 'where_clauses' argument when you can simply add it in the query string ?
pandas doesn't has it.

**Comment by martindurant** [comment]
I think you misunderstand. The `where_clauses` are to select partitions from the global query - pandas only ever gets the whole query, so doesn't need this.

**Comment by martindurant** [comment]
cf: https://github.com/ContinuumIO/intake-sql/blob/master/intake_sql/intake_sql.py#L226

**Comment by martindurant** [comment]
I will close this now, and issues should be posted on intake-sql (which is not released or documented yet, but probably usable).
