### ISSUE TITLE
DataFrame.sample function signature differs from pandas

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3574]
- `pandas.DataFrame.sample(n, frac, ...)`
- `dask.dataframe.DataFrame.sample(frac, ...)`

We can't reliably do `n`, so we should raise if it's anything but `None`. But it'd still be nice to match the signature.

**Comment by jrbourbeau** [comment]
I can work on adding `n` to the dask DataFrame `sample` signature. My only concern is this will break existing code like `ddf.sample(0.5)`. Is there some sort of `FutureWarning` or depreciation message that should be raised?

**Comment by TomAugspurger** [comment]
You could probably

- update the signature to `sample(self, n=None, frac=None...)`
- detect if `n`is between 0 and 1, emit a FutureWarning about the change, and set `frac=n`

Would that work?

**Comment by jrbourbeau** [comment]
That seems like it will work! Thanks for the feedback @TomAugspurger!
