### ISSUE TITLE
dask.array.linalg.tsqr incorrectly reported shapes

### ISSUE THREAD

**Issue by convexset** [dask/dask#3583]
```
a = np.random.random((3, 5))
data = da.from_array(a, chunks=5)
q, r = da.linalg.tsqr(data)
q.shape, r.shape
```
we get...
```
((3, 5), (5, 5))
```
wherein the shape of `q` is wrong. It should be a `(3, 3)`.

But `q.compute()` correctly yields a 3x3 matrix but of course `q.T.dot(q).shape` will yield `(5,5)` which will cause tests to fail (if such tests were there).

I'm presently mucking around tsqr. So perhaps I might tidy up the tests there.

**Comment by convexset** [comment]
Fix in: https://github.com/dask/dask/pull/3575

**Comment by mrocklin** [comment]
cc @jakirkham
