### ISSUE TITLE
read_json doesn't infer compressed files

### ISSUE THREAD

**Issue by mathewlee11** [dask/dask#3593]
Hello,

Right now dask's ```dataframe.read_json``` doesn't properly infer if a json file is compressed, which differs from pandas behavior. Small example:

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
df.to_json('test.json.gz', orient='records', lines=True, compression='gzip')
pd.read_json('test.json.gz', orient='records', lines=True) # works
dd.read_json('test.json.gz', orient='records', lines=True) # fails
dd.read_json('test.json.gz', storage_options={'compression': 'gzip'}) # works
```
It fails with ```UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte``` which means that it didn't pick up on the fact that the file is gzipped. A fix is straightforward, add ```compression='infer'``` as a keyword argument to ```read_json``` and pass it through to ```open_files``` . I can make a PR if that sounds like the right thing to do. Thanks!

**Comment by martindurant** [comment]
Thanks for noticing this, and would be happy to see the PR.
