### ISSUE TITLE
I can't save to parquet after change divisions

### ISSUE THREAD

**Issue by rpanai** [dask/dask#3598]
I'm basically trying to replicate [this](https://stackoverflow.com/questions/50824943/how-to-efficiently-split-a-large-dataframe-into-many-parquet-files) with dask. To change division by day i use [this](https://github.com/dask/dask/issues/1848#issuecomment-267138530)
advice

    import pandas as pd
    import numpy as np
    import dask.dataframe as dd
    idx = pd.date_range('2017-01-01 12:00:00.000', '2017-03-01 12:00:00.000', freq = 'T')

    df = pd.DataFrame({'numeric_col' : np.random.rand(len(idx)),
                              'string_col' : pd.util.testing.rands_array(8,len(idx))},
                               index = idx)

    ddf = dd.from_pandas(df, npartitions=2)
    # This work fine
    ddf.to_parquet("data/")

But if I try to set

    ddf.divisions = pd.date_range('2017-01-01 12:00:00.000', '2017-03-01 12:00:00.000', freq = 'D')

I can see that the divisions now are by day but I can't save it to parquet anymore.

    KeyError: ('from_pandas-20a60e8702ba1f7df2afddfc6f78acb0', 41)

**Comment by randomgambit** [comment]
interested in knowing more as well

**Comment by martindurant** [comment]
The divisions you are trying to set have many more entries than the original ones. The idea is setting `ddf.divisions` is to label the boundaries of the partitions you already have, not change their number. As it happens, in this case the original `ddf` already has labeled divisions
```
(Timestamp('2017-01-01 12:00:00', freq='T'),
 Timestamp('2017-01-31 00:01:00', freq='T'),
 Timestamp('2017-03-01 12:00:00', freq='T'))
```

In short, could it be that you were after `.resample()` perhaps?

**Comment by rpanai** [comment]
Hi @martindurant,
thank you the enlightenment. I don't think that `.resample()` could solve this problem.  But the following does it

    import pandas as pd
    import numpy as np
    import dask.dataframe as dd
    idx = pd.date_range('2008-01-01 12:00:00.000', '2017-03-01 12:00:00.000', freq='T')

    df = pd.DataFrame({'numeric_col': np.random.rand(len(idx)),
                       'string_col': pd.util.testing.rands_array(8, len(idx))},
                      index=idx)

    parts = pd.date_range('2008-01-01', '2017-03-01', freq='D')
    ddf = dd.from_pandas(df, npartitions=(len(parts)-1))
    ddf.to_parquet("data/")

**Comment by martindurant** [comment]
Glad you have a solution. OK to close?
