### ISSUE TITLE
Add feature to iterate over multiple dask arrays while computing

### ISSUE THREAD

**Issue by djhoese** [dask/dask#3600]
Related stackoverflow question (@mrocklin @jakirkham): https://stackoverflow.com/questions/50774663/iterate-and-compute-over-multiple-dask-arrays/50824610

I have a use case that I'm looking for the most performant solution to and if it doesn't already exist then I'm hoping for some guidance on where I can add it in dask (if it makes sense to do so). The use case can be described in the most basic sense with:

```
import dask.array as da
writer = Writer(...)
for dask_arr in da.compute([dask_arr1, dask_arr2, dask_arr3]):
    writer.write_frame(dask_arr)
```

Where `writer` is writing data to disk in a specific order and due to the size of data it could take a while to write and we wouldn't want to load all of the frames at once. I'm looking for a solution that would allow the equivalent of the above `compute` function that would start computing the next dask array in the iterable while I'm using/writing the current item and preserve the order of the input dask arrays. I could also see a nice feature of this functionality being that it should cache/optimize the dask graph between all the items (a generator would mean no optimization probably).

I'm sure this is hackable with the distributed scheduler, but what about the threaded scheduler?

**Comment by mrocklin** [comment]
For what it's worth I don't totally understand what is meant here.  You
want to compute dask_arr1, convert it to a numpy array, and then write the
result while you also compute dask_arr2 concurrently?  If so then I would
call dask.delayed(write)(dask_arr1) and add that to the graph before you
call compute.  If you don't want to do any parallelism within the dask
array itself then things are pretty easy.

**Comment by shoyer** [comment]
Probably your best bet if making a bunch of dependent tasks with dask.delayed, e.g.,
```python
def write_frame(numpy_arr, last_write=None):
    writer.write_frame(numpy_arr)

current_write = None
for dask_arr in [dask_arr1, dask_arr2, dask_arr3]:
    current_write = dask.delayed(write_frame)(dask_arr, current_write)
current_write.compute()
```

**Comment by djhoese** [comment]
@mrocklin The converting to a numpy array is not the important part, but yes that's essentially what is happening. With dask distributed you could probably use map/submit to kind of submit dask arrays to be computed then continue on working with the current frame.

@shoyer That'll do it! I was trying to think of how I could do that and for some reason was too focused on having to pass dask arrays to delayed that I missed the idea of passing delayed functions. I'll test this out tonight or tomorrow and respond back with my actual solution.

**Comment by jakirkham** [comment]
It's worth adding that you will likely want to optimize the Dask Array graphs before storing them (this is something `store` does for you under the hood).

```python
arrays = [dask_arr1, dask_arr2, dask_arr3]

# optimize Dask graph over all objects
dsk = da.Array.__dask_optimize__(
    dask.sharedict.merge(*[e.__dask_graph__() for e in arrays]),  # combine all Dask Array graphs
    list(dask.core.flatten([e.__dask_keys__() for e in arrays]))  # get Dask Array keys in result
)
arrays = [da.Array(dsk, e.name, e.chunks, e.dtype) for e in arrays]  # rebuild Dask Arrays
```

**Comment by djhoese** [comment]
Thanks @jakirkham. Here's my final working (mildly tested) solution:

```
def cascaded_compute(callback, arrays, optimize=True):
    """Dask helper function for iterating over computed dask arrays.

    Args:
        callback (callable): Called with a single dask array. The function
                             must accept an extra keyword argument named
                             'previous_call' which will be the result of the
                             previous call to 'callback'.
        arrays (list, tuple): Dask arrays to pass to callback.
        optimize (bool): Whether to try to optimize the dask graphs of the
                         provided arrays.

    Returns: `dask.Delayed` object to be computed

    """
    if optimize:
        # optimize Dask graph over all objects
        dsk = da.Array.__dask_optimize__(
            # combine all Dask Array graphs
            dask.sharedict.merge(*[e.__dask_graph__() for e in arrays]),
            # get Dask Array keys in result
            list(dask.core.flatten([e.__dask_keys__() for e in arrays]))
        )
        # rebuild Dask Arrays
        arrays = [da.Array(dsk, e.name, e.chunks, e.dtype) for e in arrays]

    current_write = None
    for dask_arr in arrays:
        current_write = dask.delayed(callback)(dask_arr, previous_call=current_write)
    return current_write
```

Unexpected bonus of doing it this way: I only get one ProgressBar now because all of the arrays are being computed "at the same time".

**Comment by djhoese** [comment]
Even better, now the callback doesn't have to have the extra keyword argument:

```
def cascaded_compute(callback, arrays, optimize=True):
    """Dask helper function for iterating over computed dask arrays.

    Args:
        callback (callable): Called with a single numpy array computed from
                             the provided dask arrays.
        arrays (list, tuple): Dask arrays to pass to callback.
        optimize (bool): Whether to try to optimize the dask graphs of the
                         provided arrays.

    Returns: `dask.Delayed` object to be computed

    """
    if optimize:
        # optimize Dask graph over all objects
        dsk = da.Array.__dask_optimize__(
            # combine all Dask Array graphs
            dask.sharedict.merge(*[e.__dask_graph__() for e in arrays]),
            # get Dask Array keys in result
            list(dask.core.flatten([e.__dask_keys__() for e in arrays]))
        )
        # rebuild Dask Arrays
        arrays = [da.Array(dsk, e.name, e.chunks, e.dtype) for e in arrays]

    def _callback_wrapper(arr, cb=callback, previous_call=None):
        del previous_call  # used only for task ordering
        return cb(arr)

    current_write = None
    for dask_arr in arrays:
        current_write = dask.delayed(_callback_wrapper)(
            dask_arr, previous_call=current_write)
    return current_write
```

**Comment by djhoese** [comment]
@jakirkham Quick question about the need to optimize: Does this mean that if I do:

```
a = da.arange(...)
b = a + 1
c = dask.delayed(my_func)(a, b).compute()
```

That `a` is actually computed/generated twice?

**Comment by jakirkham** [comment]
There are some optimizations that can be applied on any Dask graph. In addition to these there are some collection specific optimizations that could also be applied. For example, Dask Arrays fuse slices as part of their optimization. Expect for the simple case shown this won't matter much. In practice these matter quite a bit. Playing with [`.visualize()`]( http://dask.pydata.org/en/latest/api.html#dask.visualize ) is pretty instructive as to what is actually happening before and after optimization passes.

ref: http://dask.pydata.org/en/latest/optimize.html
ref: http://dask.pydata.org/en/latest/custom-collections.html#optimize

**Comment by djhoese** [comment]
@jakirkham @shoyer I've started working with this test code more in the last weekend and noticed that dask is actually computing *all* of the inputs for all of the delayed functions (the entire cascaded graph) before it ever calls the first delayed function. This results in all of the arrays being held in memory at once and quickly crashes from running out of memory.

Any ideas at how I can fix this?
