### ISSUE TITLE
Save parquets flavor='spark' and join

### ISSUE THREAD

**Issue by rpanai** [dask/dask#3605]
This is related to this [issue](https://github.com/dask/dask/issues/3598#issuecomment-396970081). The `pyarrow` version is [here](https://stackoverflow.com/a/50841152/4819376).
I'd like to know if there is a way to save parquet files with dask using a similar flavor (i.e. create a folder for every day called `dt=YYYY-MM-DD` ). What I'm wondering if this can help in case of join dataframes on columns different than index.

**Comment by martindurant** [comment]
Yes, you can partition your data upon save using directory names. *Each* resultant directory will contain files from each of the original partitions. You can load these and set the index to either the original index or the partitioning one. Whether that improves performance on join, you will have to measure for yourself.

**Comment by rpanai** [comment]
Do you mind to share the commands that can do so?

**Comment by martindurant** [comment]
The [API](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_parquet) shows you that there is a keyword argument `partition_on=`

> Construct directory-based partitioning by splitting on these fields’ values. Each dask partition will result in one or more datafiles, there will be no global groupby.
