### ISSUE TITLE
Dask.read_parquet not scanning partition cols with glob path

### ISSUE THREAD

**Issue by pranav-kohli** [dask/dask#3611]
I am saving a dask dataframe to parquet with two partition columns using the pyarrow engine. The problem arises in scanning the partition columns. When I scan using the directory path, I get the partition columns in the output dataframe, whereas if I scan using the glob path, I dont get these columns

pyarrow : 0.9.0.post1

dask : 0.17.1

    import dask.dataframe as dd

    size = 20
    tmpdir = '/tmp/test/outputParquet1'
    engine = 'pyarrow'

    d = {'signal1': np.random.normal(0, 0.3, size=size).cumsum() + 50,
         'fake_categorical1': np.random.choice(['A', 'B', 'C'], size=size),
         'fake_categorical2': np.random.choice(['D', 'E', 'F'], size=size)}

    df = dd.from_pandas(pd.DataFrame(d), 2)
    df.to_parquet(tmpdir, compression='snappy', write_index=True, engine=engine,
                  partition_on=['fake_categorical1', 'fake_categorical2'])

    #This doesnt scans the partitioned columns
    df_partitioned = dd.read_parquet(tmpdir + '/*/*/*.parquet', engine=engine)

    #this fails
    #df_partitioned[df_partitioned.fake_categorical1 == 'A'].compute()

    #This scans the partitioned columns
    df_partitioned = dd.read_parquet(tmpdir, engine=engine)

    df_partitioned[df_partitioned.fake_categorical1 == 'A'].compute()

Fastparquet supports the glob path, but somehow pyarrow doesn't

**Comment by martindurant** [comment]
This appears to be a bug with pyarrow: `pq.ParquetDataset(paths)` does not find partitions when given the set of parquet files or glob, but does when given the root directory. I recommend raising an issue upstream and closing this one.

**Comment by martindurant** [comment]
Note that the equivalent code in fastparquet to extract the root directory is at `fastparquet.util.analyse_paths`, but this is not particularly complex.

**Comment by pranav-kohli** [comment]
Raised the issue in the arrow page
https://github.com/apache/arrow/issues/2147

Closing this one
