### ISSUE TITLE
SciPy Sprint

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3614]
It looks like a few Dask developers will be at the SciPy sprints (including at least @jcrist @martindurant @stsievert) and they seem to be happy to organize something.  We discussed this briefly during the weekly meeting.  

Some tasks:

- [ ] Officially register as a sprint: https://scipy2018.scipy.org/ehome/299527/648141/
- [ ] Formulate plans about what we'll sprint about (see below)
- [ ] Tweet about that sprint and mention it in the gitter chat
- [ ] Do prep work so that sprinters have activities when they arrive, including people with a range of skill levels

### Content

Two suggestions were made:

1.  Construct examples for https://github.com/dask/dask-examples

    To make this easier it would be nice to have some material to steal from

2.  Solve easy bugs within the dask codebase.

    To make this easier we should probably spend some time identifying some easy to fix bugs and protecting them from the more active maintainers.

**Comment by martindurant** [comment]
Registering. Currently I have chosen "beginner" and "needs familiarity with the package".

**Comment by shoyer** [comment]
I will be at the SciPy sprints, likely focused mostly on finishing NumPy Enhancement Proposals, though.

(@mrocklin, will you be there?)

**Comment by mrocklin** [comment]
I'll be there on Saturday.  Flying out Sunday in the early afternoon.
