### ISSUE TITLE
Official Dask Blog

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3616]
A Dask blog might serve as a location for the following kinds of posts:

1.  Announcements, like releases
2.  Fun developer facing blogposts
3.  User contributed posts

There are some open questions and challenges:

1.  How do we host content?
2.  How do we collect content from users?

**Comment by jcrist** [comment]
We currently have a dask blog hosted at https://blog.dask.org/, with content at https://github.com/dask/dask-blog. Closing.
