### ISSUE TITLE
Slicing of big dask arrays

### ISSUE THREAD

**Issue by m-rossi** [dask/dask#3619]
I'm using dask (currently version 0.17.5) for performing computations on big arrays. Recently I discovered a bug if I perform a slicing operation, see my example below:

```python
import dask.array as da

d1 = da.zeros(1_000_000_000_000, chunks=1_000_000)
d2 = d1[1000:]

assert d1.shape[0] - 1000 == d2.shape[0],\
    f'Size not match, expected {d1.shape[0] - 1000}, got {d2.shape[0]}'
```

which results in

```python
AssertionError: Size not match, expected 999999999000, got 892625816600
```

After some debugging the issue seems to be in `_slice_1d`:

https://github.com/dask/dask/blob/207afc664d21cdcfda7575f887b4014d31c17575/dask/array/slicing.py#L375

which calculates incorrectly the `chunk_boundaries`, which seems to be related to an integer overflow. I can fix this use by passing `dtype=np.int64` to `np.cumsum` but I am not sure if it is the best way to fix it and there are maybe more parts of the code in dask where a similiar approach is necessary for big arrays.

Therefore I want to open a discussion here instead of directly opening a PR (which I would be glad to do later).

**Comment by mrocklin** [comment]
Thanks for the excellent bug report and analysis @m-rossi .  Yes, I suspect that your understanding is correct.  The one change I would recommend would be to use unsigned integers to get the extra bit `np.uint64` :)

A PR would be welcome!

**Comment by m-rossi** [comment]
Great idea, thanks.

**Comment by jakirkham** [comment]
Is this addressed with PR ( https://github.com/dask/dask/pull/3620 ) or is there more to do here?

**Comment by m-rossi** [comment]
Merged.
