### ISSUE TITLE
dask.utils.effective_get removal in dask 0.18 breaks xarray

### ISSUE THREAD

**Issue by shoyer** [dask/dask#3638]
#3448 removed the utility function `dask.utils.effective_get`, which xarray was relying upon to detect the current dask scheduler (see https://github.com/pydata/xarray/issues/2238 for details). This will break netCDF/HDF5 IO using dask distributed, because we fall back to using a thread lock (which can't be pickled). I suspect we will get bug reports soon, likely from Pangeo users.

It would be good to restore this utility, at least temporarily, to avoid breaking xarray. In the long term, if there's another supported way to detect the current dask scheduler we can certainly switch how we do it in xarray.

CC @jhamman

**Comment by mrocklin** [comment]
Thanks for reporting.  I thought that XArray was testing against Dask master.  Is this not true, or did we sneak in somehow?

Adding a deprecated version back into dask makes sense to me.

**Comment by shoyer** [comment]
We do have a test against dask master, but it doesn't break our build when it fails. We should probably switch that.

(In the past, tests against master for various projects have been trickier to maintain, mostly because we can't rely on conda/pip and have build from source. But dask and distributed are pure Python, so that shouldn't be a problem.)
