### ISSUE TITLE
Rename ghost module to overlap or some other term

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3639]
This term is probably not the clearest.  We should continue replacing it with something else, like overlap.

cc @jakirkham

**Comment by jakirkham** [comment]
...or halo. ;) Though maybe overlap is clearer.

@ogrisel used another term that was good, but have since forgotten. Maybe he remembers?

**Comment by jakirkham** [comment]
Also @jni may have thoughts here ;)

**Comment by mrocklin** [comment]
This would require the following:

1.  Changing the function names within the ghost module
2.  Renaming the ghost module to overlap
3.  Changing the documentation and API documentation
4.  Including a deprecated ghost module with deprecated functions that warn and then point to the new ones
