### ISSUE TITLE
dask read_parquet returns partition columns even when specifying not to.

### ISSUE THREAD

**Issue by MosheVai** [dask/dask#3646]
I am saving a dask dataframe to parquet using pyarrow and partitioning it on a 'certain' column.
when reading the parquets from the dir i explicitly specify the columns to read however it reads the 'certain'
column even though it wasn't specified.   

example: 
```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'names':['foo','bar'],'id':[1,2],'year': [2013,2014]})
dff = dd.from_pandas(df,npartitions=1)
# will write the parquet files and create a folder named res
dff.to_parquet('res',write_index=False, engine='pyarrow', compression='snappy', partition_on=['year'])  
```
when reading and not computing it shows:

```python
read_res = dd.read_parquet('res/', engine='pyarrow', columns=['names', 'id'])
read_res
```
**Dask DataFrame Structure:**

|names | id 
|-- | -- 
| object| int64
| ...| ...

however when you actually compute you  can see the undesired column 'year'
```python
read_res.compute()
```
names | id | year
-- | -- | --
foo | 1 | 2013
bar | 2 | 2014

**Comment by martindurant** [comment]
A similar but different issue was just fixed in #3636 - can you check whether you still have this problem after that merge?

**Comment by MosheVai** [comment]
yes that seems to have fixed it :) @martindurant 
is the code on pypi and conda already ?

**Comment by martindurant** [comment]
No, this is not released, but releases of dask come fairly regularly every few weeks.

> it doesn't work with s3

What do you mean?

**Comment by MosheVai** [comment]
I have updated my dask and tried it again while reading and writing from s3 and it didn't work.
And  this  
>   this is not released

is why.
thank you for the quick response.
