### ISSUE TITLE
Collect user stories with online form

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3651]
People often ask "who uses Dask?"

I would like to set up a form to collect this information in a more formal way.  I would like to make a Google form with the following content (suggestions welcome), post it on our website, and e-mail it out to a number of our friends.

### Header

Hi!

This form invites you to share about the problems that you solve with Dask.

We want to highlight real-world applications of Dask to show to larger user communities and to possible funding agencies so that they can better understand when Dask might or might not be appropriate for their work.  When deciding on a technology it's helpful to hear from people within your own community, so as an experienced Dask user you are probably the best suited to explain the costs and benefits of using Dask to your peers.

We may want to share some of these responses, either with individual groups or with the broader public.  Please do not share anything that you would mind being passed on.  Feel free to answer as much or as little of this form as makes sense for you.

We appreciate your time on this.  This is valuable to the Dask project.

### Questions

-  Who are you, and for what group, project, or effort do you use Dask? Links are welcome.  Leave this blank if you wish to remain anonymous.
- What problem are you trying to solve, and why was it challenging?  Ideally you would focus on your problem domain, and not mention Dask here.
- How does Dask help you to solve your problem in general?
- What are some of the reasons you chose to use Dask in the first place and how have these reasons changed over time?
- What are some of the pain points of using Dask on your problem?    What are some of the costs of using the project?
- Would you be interested in expanding your description above into a blogpost in the future?

### Preview form

https://docs.google.com/forms/d/e/1FAIpQLSexQY6Y_RZcpkiUOOfyyXns5uoi56E7cL2NDf7HLYoLtjMZWQ/viewform

**Comment by mrocklin** [comment]
Updated form here: https://docs.google.com/forms/d/e/1FAIpQLSexQY6Y_RZcpkiUOOfyyXns5uoi56E7cL2NDf7HLYoLtjMZWQ/viewform

**Comment by martindurant** [comment]
Agree that boxes rather than reply lines would be nice.

> and not mention Dask here

sounds odd to me. 

Do we want to ask about other big data tools that they use in conjunction or instead of dask?

> expanding your description into a blogpost

Can leave a box for including links to existing blogs here? Seems like "anything else" (next) should really be else.

**Comment by mrocklin** [comment]
Thanks for the feedback

> Agree that boxes rather than reply lines would be nice.

I agree.  Unfortunately it's not clear to me how to do this with google forms.  If anyone has experience here and/or wants access to the form let me know.

> "and not mention Dask here" sounds odd to me

I've changed this to the following:

*Ideally you would focus on your problem domain here first, and discuss your technical solution with Dask in the next question.*

> Can leave a box for including links to existing blogs here? Seems like "anything else" (next) should really be else.

Unfortunately I don't see a way to do this with google forms.  I've added a section following that says:

*Is there anything else we should know?*
*Links to existing blogposts? Groups we should reach out to? Your favorite issue that you'd like to see resolved?*

**Comment by mrocklin** [comment]
I'm somewhat inclined to leave this as a suggestion in a final "anything else you'd like to tell us?" question.

**Comment by hussainsultan** [comment]
I have the following suggestions on the survey:
1. For the question "How does Dask help you to solve your problem?" I thought the subtitle with "scale pandas workflow"  or "dask.delayed" may add a bias to the answer. I'd rather let the question stay as is without the subtitle. 
2. I like the pain-points question. It might be more potent if we add another question for how do people operationalize dask and any unexpected costs during that phase. 

Thank you for putting this together. I appreciate the focus on getting more organized around customers.

**Comment by mrocklin** [comment]
Thanks @hussainsultan !  Updated version from your feedback is here: https://docs.google.com/forms/d/e/1FAIpQLSexQY6Y_RZcpkiUOOfyyXns5uoi56E7cL2NDf7HLYoLtjMZWQ/viewform

**Comment by mrocklin** [comment]
Update: I iterated on the form a couple of times and included it in a blogpost as a short test.  I didn't get a ton of responses, and the responses I got varied widely.  I think I'm going to go for a more targetted approach for the near term to build up some solid examples.  Currently these lives in https://github.com/mrocklin/dask-stories and there is an excellent example there from Allistair that's worth a read.  

My current plan is to try to pressure a few other people to expand their answers to match that form.

**Comment by mrocklin** [comment]
http://dask-stories.readthedocs.io/en/latest/ is live.  I'll close this when we include this in the main docs.  I'm currently waiting on getting a few more responses before I do that.

**Comment by jrbourbeau** [comment]
@mrocklin as https://stories.dask.org is linked to in the main docs, is it okay to close this issue?

**Comment by mrocklin** [comment]
Sure
