### ISSUE TITLE
Add DataCamp to documentation

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3661]
[Datacamp](https://www.datacamp.com/) is a for-profit company offering online courses.  They have a [Dask course](https://www.datacamp.com/courses/parallel-computing-with-dask).  Should we include a link to this in our documentation?

Full disclosure: Anaconda, my employer, was active in creating that course.  I think I'm on the intro video but am otherwise not seriously involved.

**Comment by GenevieveBuckley** [comment]
I know this issue was opened a long time ago. Given [Datacamp's recent behaviour](https://dnlmc.medium.com/dont-use-datacamp-ef04adcf1b7f), that is a hell no from me.

**Comment by GenevieveBuckley** [comment]
Also, I know there are two newer courses on Dask at TalkPython. It's mostly the same content as the official Dask tutorial, plus a whole bunch of about Coiled in there too. I don't think there's any real benefit in linking to these things from the Dask docs.
