### ISSUE TITLE
Explain logic behind recursive tsqr 

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3667]
So I'm trying the following computation:

```python
x = da.random.random((1000000000, 10), chunks=(1000000, 10))
u, s, v = da.linalg.svd(x)
```

And I find that we don't recurse in the tsqr computation.  Looking at the logic it seems like `prospective_blocks == 1`.  I'm not sure I understand why this is the case though.  

@convexset are you around to help explain this?  Thoughts on how the docstring or comments might be improved here?

**Comment by convexset** [comment]
Hmmm... so....

(1000000000, 10) in 1000 x (1000000, 10) chunks would lead to the need to factorize a (10000, 10) sized block.

That’s smaller than the largest input chunk, so recursion will not happen. Hence, prospective blocks will be 1.

The logic is that if something larger than the largest block has to be factorized, then recursion will be used to avoid burdening a single core.

**Comment by convexset** [comment]
Probably some examples to improve on...

```
The implementation here is the recursive variant due to the ultimate
    need for one "single core" QR decomposition. Given m blocks, the
    "single core" QR decomposition will have to work with a ``(k * n, n)``
    matrix, and ``k * n`` may be substantially larger than ``m``.
    As such, (if ``m / n >= 2``) recursion will be applied as necessary
    to ensure that single core computations do not have to work on blocks
    larger than ``(m, n)``.
```

**Comment by convexset** [comment]
Interestingly... I see a documentation error...

https://github.com/dask/dask/blob/36e235d7074f01830dd79a24fd656f4cda9e2c81/dask/array/linalg.py#L51

It should be given k blocks. Not given m blocks.

**Comment by convexset** [comment]
Just pushed an additional little commit to fix that documentation error.

**Comment by hristog** [comment]
Seems to me that https://github.com/dask/dask/commit/fc71015ecf82e8416f6598377ab5d00e83a04dfb (#3698) closes this issue.

**Comment by mrocklin** [comment]
Thank you for following up @hristog
