### ISSUE TITLE
'Series' object has no attribute 'columns'

### ISSUE THREAD

**Issue by R1994** [dask/dask#3681]
i run below code,it reported me:`'Series' object has no attribute 'columns'`
```
df = dd.read_parquet('/data/dask/af.pq',columns=['timestamp','gid','uid'])
df.set_index('timestamp',inpalce=True)
df.groupby('gid').apply(lambda x:x.resample('1D').uid.unique(),meta=('uid','object'))
```
if output is dataframe,it worked,but it happened error when output is series.i know series don't have column but how i make code work properly?
setting output's dtype particularly will let computation faster?such as let `meta=('uid','str') `better than `meta = ('uid','object')`?
how many kinds of dtype?

**Comment by TomAugspurger** [comment]
Could you make a small reproducible example that demonstrates the problem? Ideally, you shouldn't need to read in data from disk.

Could you also post the full traceback?

**Comment by R1994** [comment]
code is:
```
def activate_record(start):
    data = []
    for i in range(5000):
        timestamp = start + datetime.timedelta(hours=random.randint(0, 920))
        group = 'g' + str(random.randint(500, 505))
        account = 'qq' + str(random.randint(1000, 1100))
        data.append([timestamp, group, account])
    return data


log_df = dd.from_pandas(pd.DataFrame(activate_record(pd.to_datetime('2010-1-2')),columns=['timestamp','gid','uid']),npartitions=1)
daily_login_users = log_df.set_index('timestamp').groupby('gid').apply(lambda x: x.resample('1D').uid.unique(), meta=('uid','object'))
daily_login_users.compute()
```
traceback is:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-11-249fb6a9c71f> in <module>()
>      19 log_df = dd.from_pandas(pd.DataFrame(activate_record(pd.to_datetime('2010-1-2')),columns=['timestamp','gid','uid']),npartitions=1)
>      20 daily_login_users = log_df.set_index('timestamp').groupby('gid').apply(lambda x: x.resample('1D').uid.unique(), meta=('uid','object'))
> ---> 21 daily_login_users.compute()
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
>     154         dask.base.compute
>     155         """
> --> 156         (result,) = compute(self, traverse=False, **kwargs)
>     157         return result
>     158 
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
>     400     keys = [x.__dask_keys__() for x in collections]
>     401     postcomputes = [x.__dask_postcompute__() for x in collections]
> --> 402     results = schedule(dsk, keys, **kwargs)
>     403     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
>     404 
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
>      73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
>      74                         cache=cache, get_id=_thread_get_id,
> ---> 75                         pack_exception=pack_exception, **kwargs)
>      76 
>      77     # Cleanup pools associated to dead threads
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
>     519                         _execute_task(task, data)  # Re-execute locally
>     520                     else:
> --> 521                         raise_exception(exc, tb)
>     522                 res, worker_id = loads(res_info)
>     523                 state['cache'][key] = res
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/compatibility.py in reraise(exc, tb)
>      67         if exc.__traceback__ is not tb:
>      68             raise exc.with_traceback(tb)
> ---> 69         raise exc
>      70 
>      71 else:
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
>     288     try:
>     289         task, data = loads(task_info)
> --> 290         result = _execute_task(task, data)
>     291         id = get_id()
>     292         result = dumps((result, id))
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/local.py in _execute_task(arg, cache, dsk)
>     269         func, args = arg[0], arg[1:]
>     270         args2 = [_execute_task(a, cache) for a in args]
> --> 271         return func(*args2)
>     272     elif not ishashable(arg):
>     273         return arg
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/dask/dataframe/core.py in apply_and_enforce(func, args, kwargs, meta)
>    3559         if isinstance(df, pd.DataFrame):
>    3560             # Need nan_to_num otherwise nan comparison gives False
> -> 3561             if not np.array_equal(np.nan_to_num(meta.columns),
>    3562                                   np.nan_to_num(df.columns)):
>    3563                 raise ValueError("The columns in the computed data do not match"
> 
> ~/miniconda2/envs/py35/lib/python3.5/site-packages/pandas/core/generic.py in __getattr__(self, name)
>    4366         if (name in self._internal_names_set or name in self._metadata or
>    4367                 name in self._accessors):
> -> 4368             return object.__getattribute__(self, name)
>    4369         else:
>    4370             if self._info_axis._can_hold_identifiers_and_holds_name(name):
> 
> AttributeError: 'Series' object has no attribute 'columns'

**Comment by R1994** [comment]
and i plan to change another method,using dask-scheduler allocate task,computing in pandas,i think it will help ease my workload(it tortured me 10 days!),but every machine just 200mb memory avaliable, how to limit  every worker's memory usage?log files save in every worker, some files read in memory may be oversize.i try to write Pseudocode to demonstrate my ideal.
```

client=Client('ip address')
ddf = dd.read_parquet('local disk path',columns=[])    # 'every worker reads files from local disk'
convert to pd.dataframe,don't know how to write
filter by group_id_list,get  new small df
def f(df):
    do some dataframe computation
finally,get  rentation rate dataframe,how to gather them all?
```

**Comment by R1994** [comment]
thank your help!but i want a series with mutliindex for follow up operation conveniently,because my another table is a series.in fact , this code also make a dataframe:
```
def per_group(blk):
        return blk.resample('1D').uid.unique()
    periods = pd.date_range(pd.to_datetime('2010-1-2'),pd.to_datetime('2010-1-2')+datetime.timedelta(days=38))
    meta_2 = {'{}'.format(i):'object' for i in periods}
    daily_login_users = log_df.groupby('gid').apply(
        per_group, meta=meta_2 )
```

**Comment by TomAugspurger** [comment]
Sorry, I'm not sure I understand the question.

At this point, it *looks* like there's no bug in dask.dataframe. We recommend StackOverflow for usage questions since it tends to get better answers and search results. I'd recommend putting together a [minimal example](http://stackoverflow.com/help/mcve).
