### ISSUE TITLE
API for selecting arrays by block

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3684]
It might be useful to provide an API to select Dask arrays by block.  This would be useful for operations like selecting all internal blocks, selecting every other block, etc..  Presumably this would use numpy-like slicing on an attribute and return a dask array back:

```python
>>> x = da.arange(20, chunks=(5,))
>>> x.blocks[:2] 
dask.array<getitem, shape=(10,), dtype=int64, chunksize=(5,)>

>>> x.blocks[:2] 
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> x.blocks[::2].compute()
array([0, 1, 2, 3, 4, 10, 11, 12, 13, 14])
```

I think that this was previously mentioned by @shoyer, but I can't find the issue.  cc also @jakirkham and @stuartarchibald

**Comment by jakirkham** [comment]
Have you seen issue ( https://github.com/dask/dask/issues/3274 )?

**Comment by mrocklin** [comment]
So presumably these are similar in that `x.blocks[i, j,k]` is semantically equivalent to `x.to_chunks()[i, j, k]`?

**Comment by stuartarchibald** [comment]
This would be very useful, especially if you have some function being mapped that operates using globally aware indexing (potentially from https://github.com/dask/dask/pull/3686) but will only be applicable on the e.g. first column of blocks. Also when streaming it allows the dropping of undersized blocks from a domain with view of waiting for more data to combine with them.

**Comment by jakirkham** [comment]
> So presumably these are similar in that `x.blocks[i, j,k]` is semantically equivalent to `x.to_chunks()[i, j, k]`?

Basically. Was thinking of a nested list initially. Though we have had some success with NumPy object arrays that contain Dask Array chunks.

> This would be very useful, especially if you have some function being mapped that operates using globally aware indexing (potentially from https://github.com/dask/dask/pull/3686)...

It could be useful there. We have often used `da.index` combined with the original array to get at this need. Though this gives you actual index and not block index. Here's a [simple example]( https://github.com/dask/dask/blob/0.18.1/dask/array/routines.py#L1093-L1096 ). Though there are more complex ones as well.

<br>

Generally this functionality would be a nice alternative for use cases that are simply outside of the typical `map_blocks` API. For instance, performing operations that reduce each chunk to a scalar, storing individual chunks to different files, operations where the shape might not fit into what `map_blocks` expects, and more general operations that act differently depending on which chunk is considered.

**Comment by shoyer** [comment]
Yes, I agree that this would be useful.

**Comment by mrocklin** [comment]
This is implemented in #3689

**Comment by jakirkham** [comment]
If any thoughts come to mind, @d-v-b, would be great to hear them. ;)

**Comment by d-v-b** [comment]
This looks like it would be quite handy insofar as it obviates the need for kludgy uses of`map_blocks`.  (Especially if iterator support is added)

**Comment by jakirkham** [comment]
IDK if we will do iterator support initially, but [this is pretty close and works]( https://github.com/dask/dask/pull/3689#issuecomment-401446030 ).
