### ISSUE TITLE
SciPy Birds of a Feather session for Dask users

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3685]
It might be useful to have a "Birds of a Feather" (BOF) session for Dask users.  This would be about an hour long session and would allow many users to briefly speak about their application of using Dask (maybe five minutes each) followed by discussion on each topic.  

To do this, we need a few users who can definitely present, and then we'll probably be able to pull a few others from the general attendees.

**Comment by djhoese** [comment]
Is there a list of current BOF proposed sessions? I would attend the dask one if there weren't any more relevant to my exact field.

**Comment by mrocklin** [comment]
Not yet I don't think.  I recommend looking at the scipy conference website
here: https://scipy2018.scipy.org

**Comment by lesteve** [comment]
I am definitely interested to attend!

**Comment by jrbourbeau** [comment]
I would definitely attend a Dask BOF session!

**Comment by seanlaw** [comment]
I would be interested in attending. Have we settled on a slot yet?

**Comment by martindurant** [comment]
1:00-200 pm Friday, Room 204
