### ISSUE TITLE
Specifying a Client to use with dask.config

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3708]
Follow-up to [this SO question]( https://stackoverflow.com/q/51094070 ), it would be nice to have a standard way to specify the computational strategy to use within a specified context. This is useful when working with multiple clients (e.g. living in different environments), when using Dask in different contexts (e.g. using out-of-core features on a worker instead of Distributed features across workers), etc..

Current strategies include...

1. `dask.config.set(get=...)`
2. `with distributed.client.temp_default_client(...):`
3. `distributed.client.ensure_default_get(...)`

However the first one is deprecated and the other two are not part of the public API (nor is there any guarantee that they will be). Would be good to settle on a strategy for users to address this sort of situation especially before removing existing ones. Thoughts on appropriate strategies for context specific client selection welcome.

cc @mrocklin

**Comment by jakirkham** [comment]
Also relevant is PR ( https://github.com/dask/distributed/pull/1849 ), which attempts to make option 2 part of the public API.

**Comment by mrocklin** [comment]
Sorry I missed this.  Yes, I agree that using `dask.config.set` to set the default client would be a good idea.  This would require a change to `distributed/client.py::_get_global_client` in the [distributed repository](https://github.com/dask/distributed) to first check `dask.config.get('client')` or something similar.  

To test this it would be good to create a couple of clients and play around with making them default and getting the default in various nested patterns to ensure good behavior and cleanup.

Marking as good first issue

**Comment by jakirkham** [comment]
To update this a bit, one can now do `dask.config.set(scheduler=client)` where `client` is a specific `Client` instance (pointed out to me by Matt recently). ( https://github.com/dask/dask/pull/4062 ) I think this solves the issue of having a standard way to specify a `Client`. Perhaps now we can tidy up the other old ways of doing this to just use the `config` and/or deprecate them. Think that is all that remains for this issue unless there are other thoughts.

**Comment by TomAugspurger** [comment]
> Perhaps now we can tidy up the other old ways of doing this to just use the config and/or deprecate them. Think that is all that remains for this issue unless there are other thoughts.

By "old ways" do you mean the other two alternatives in the original post? As you say, those aren't part of the public API, so there shouldn't be need for a deprecation.

**Comment by mrocklin** [comment]
Closing then.  Happy to have this reopened if folks disagree.
