### ISSUE TITLE
Cannot specify dask array shape with a numpy array

### ISSUE THREAD

**Issue by hmaarrfk** [dask/dask#3710]
```python
import numpy as np
import dask.array as da


chunks = (10, 10)
shape = np.asarray((100, 100))

n = np.zeros(shape)
d = da.zeros(shape, chunks=chunks)
```

output
```python
Traceback (most recent call last):

  File "<ipython-input-31-0eb572d2c4ad>", line 1, in <module>
    d = da.zeros(shape, chunks=chunks)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/wrap.py", line 36, in wrap_func_shape_as_first_arg
    chunks = normalize_chunks(chunks, shape, dtype=dtype)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/core.py", line 1990, in normalize_chunks
    if not (len(shape) == 1 and sum(chunks) == shape[0]):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

You can specify the numpy array shape with a numpy array.

Dask version: 0.18.1
Python: 3.6
Linux 64 bit
Using miniconda

**Comment by mrocklin** [comment]
I agree that that is a bug and should be fixed.  Thanks for the excellent issue.  My guess is that there are probably a few places to normalize the shape to a tuple of ints.  Trying this on a few functions should be helpful in identifying most of them.

**Comment by hmaarrfk** [comment]
Incidentally, I realized that I'm not even supposed to create my array this way.
So I don't know if I'm going to care to fix this myself.

For whoever else has this issue: my workaround was to use as I wanted to have flexibility in how 'shape' was defined.

```python
d = da.zeros(list(shape), chunks=chunks)
```

`tuple` might work too.

**Comment by jakirkham** [comment]
Also NumPy has the `tolist` method, which is a bit more performant. Though it is unlikely this is ever the bottleneck.

```python
In [1]: import numpy as np

In [2]: shape = np.asarray((100, 100))

In [3]: %timeit list(shape)
952 ns ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: %timeit shape.tolist()
152 ns ± 5.13 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Comment by jakirkham** [comment]
Should we close then or would you still like to see this fixed?

**Comment by hmaarrfk** [comment]
@jakirkham I think it became an issue since I wrote some code with the following spirit:

```python
import numpy as np
arr_1 = np.zeros((3, 2))
shape_2 = np.asarray(arr_1.shape)*2
arr_2 = np.zeros(shape=shape_2, dtype=arr_1.dtype)
```
and when I wanted to convert it to dask, I ran into the issue. 

Operating on the shape, as a numpy array is often advantageous.
