### ISSUE TITLE
Add Yarn documentation 

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3713]
The setup documentation currently includes options like Kubernetes and HPC.  Given the introduction of [dask-yarn](http://dask-yarn.readthedocs.io/en/latest/) it seems reasonable to put a link up for that as well.  This might help to drive traffic to the new project.

One thing to consider is that most people who have a Yarn cluster probably think of it as a Hadoop or Spark cluster and may not recognize the name.  We might consider naming this section "Yarn / Hadoop" for their benefit.  

We should probably also include a small section explaining that many clusters that were originally designed to run Hadoop/Spark/Hive/... use the Yarn resource manager, and that Dask can also use this resource manager natively.

I'm happy to write something up, but also happy to defer to @jcrist , who likely has more experience here.  It might be useful also to provide wisdom in this documentation section that is commonly useful when using Yarn clusters.  I don't have anything in particular in mind, but suspect that something exists.

**Comment by mrocklin** [comment]
I also don't know where to draw the line between documentation in dask-yarn and documentation in the core docs.

**Comment by jcrist** [comment]
My preference is to minimize documentation in the dask docs, and instead redirect users to the dask-yarn docs. Splitting code from documentation feels wrong for me, but I understand the value of having some reproduction in the dask docs.

> but also happy to defer to @jcrist

If you can hold off, I'll write something up on Thursday.

**Comment by mrocklin** [comment]
Happy to hold off.  Happy to have most documentation be in dask-yarn.  The
right thing here might even be to just have a redirect.

**Comment by mrocklin** [comment]
Mostly I care that there is a link from the main dask page that points
people to information about dask-yarn.  Beyond that I have no strong
preferences.

**Comment by mrocklin** [comment]
Ping @jcrist

**Comment by mrocklin** [comment]
This could just be a redirect to the dask-yarn page with no content.  Marking as good first issue

https://dask-yarn.readthedocs.io

**Comment by martindurant** [comment]
@jcrist , happy to provide this, about a paragraph's worth with the link, unless you are likely to get to it soon.

**Comment by jcrist** [comment]
Oop, apologies, I'll take care of this later today.

**Comment by martindurant** [comment]
All yours!

**Comment by mrocklin** [comment]
Thanks @jcrist
