### ISSUE TITLE
Set index and save to parquet dask 0.17.5 vs 0.18.1

### ISSUE THREAD

**Issue by rpanai** [dask/dask#3716]
I have several parquets file saved on `tmp_folder` I want to read, sort by a key and save the sorted file to parquets inside `folder`. My df has 59M rows and I'm running the following code on a machine with 16 cores 24GB of RAM on GCP. I would like to run this with the minimum amount as possible as then I'm going to process the single files one-by-one.
The following code runs in about 24 with `dask.__version__=='0.17.5'`
```python
folder = "test_dataset"
tmp_folder = "_".join([folder,"tmp"])
df = dd.read_parquet(tmp_folder)
with dask.set_options(get=dask.get):
    nrows = len(df)
npartitions = int(nrows//2e6) # check
df = df.repartition(npartitions=npartitions)
with dask.set_options(get=dask.get):
    df = df.set_index("key")
with dask.set_options(get=dask.get):
    df.to_parquet(folder, compression="snappy") 
```

But if I try to run the same code in `dask.__version__=='0.18.1'` and changing `with dask.set_options(get=dask.get)` with `with dask.config.set(scheduler='single-threaded')` the process ends but I don't have any files in `folder`.
I'm not sure if I'm getting confused with the right `scheduler` to use in this case or it's a bug.

**Comment by mrocklin** [comment]
Dask.get is the sequential scheduler.  The equivalent would be
dask.config.set('single-threaded')

**Comment by martindurant** [comment]
May I ask why you want to run this single-threaded? If the data fits entirely into memory, you could also use fastparquet directly, which contains an option for the partition resizing on write. Which parquet engine are you using here?
Neither engine returns the set of files written, but perhaps they should.

**Comment by rpanai** [comment]
@mrocklin the code I was using with `dask.__version__=='0.18.1'` is

```python
folder="test_dataset"
tmp_folder = "_".join([folder,"tmp"])
df = dd.read_parquet(tmp_folder)
with dask.config.set(scheduler='single-threaded'):
    nrows = len(df)
npartitions = int(nrows//2e6) # check
df = df.repartition(npartitions=npartitions)
with dask.config.set(scheduler='single-threaded'):
    df = df.set_index("key")
with dask.config.set(scheduler='single-threaded'):
    df.to_parquet(folder, compression="snappy")  
```
if I try to use `dask.config.set('single-threaded')` I receive this error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>()

~/.conda/envs/promoPRODv2/lib/python3.6/site-packages/dask/config.py in __init__(self, arg, config, lock, **kwargs)
    247             self.old = {}
    248 
--> 249             for key, value in kwargs.items():
    250                 self._assign(key.split('.'), value, config, old=self.old)
    251 

AttributeError: 'str' object has no attribute 'items'
```

**Comment by martindurant** [comment]
`dask.config.set('single-threaded')`  --> `dask.config.set(scheduler='single-threaded')`

**Comment by mrocklin** [comment]
Sorry, I meant dask.config.set(scheduler='single-threaded')  Probably
better to look at the docs for this than listen to me :)
http://dask.pydata.org/en/latest/scheduling.html

**Comment by rpanai** [comment]
@martindurant I'm running sequentially on single schedule because the data doesn't fit in memory. I basically want to split the data in disjoint parquet files and then process one by one fitting in memory with pandas. I know it might be not the ideal solutions but the function I'm using works better in pandas than dask.

**Comment by rpanai** [comment]
@martindurant and @mrocklin i posted the [code](https://github.com/dask/dask/issues/3716#issuecomment-402488664) I'm running with the latest dask version and I'm using `dask.config.set(scheduler='single-threaded')`.

**Comment by TomAugspurger** [comment]
Closing this, since I think the suggestion in https://github.com/dask/dask/issues/3716#issuecomment-402489727 is correct.

@rpanai if not, could you provide a minimal example demonstrating the problem http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports?
