### ISSUE TITLE
h5py + from_array() performance with thousands of files

### ISSUE THREAD

**Issue by d-v-b** [dask/dask#3718]
I use dask to work with thousands of `.h5` files. This means I must call `from_array(h5py.File())` thousands of times before combining all these arrays into one using `dask.array.stack()`. In my testing, this can take multiple seconds to complete, with some execution time variability / hysteresis  depending on stuff under the hood of `h5py` (I think).

I wanted to speed this process up. I found that replacing `from_array(h5py.File())` with `from_array(from_delayed(delayed(h5py.File)()))` before calling `stack` gave me a modest (1.5 - 2x) speed up on test data that approximates the scale of my real data. An example is below:

```python
import h5py as h5
import dask
import dask.array as da
import time
from h5py import File
from dask.delayed import delayed
import sys

print(f'Python : {sys.version}')
print(f'Dask : {dask.__version__}')
print(f'h5py : {h5.__version__}')

dims = [1000, 10, 100, 100]
fnames = ['t_{0:03d}.h5' for ind in range(dims[0])]
data_base = da.random.randint(0, 1, size=dims, chunks=(1,*dims[1:]))

# generate a hdf5 dataset in multiple files on disk
for ind, d in enumerate(data_base):
    try:
        da.to_hdf5(fnames[ind], 'default', d)
    except OSError:
        from os import remove
        remove(fnames[ind])
        da.to_hdf5(fnames[ind], 'default', d)

        
# wrap our h5py.File creation in a function
def from_h5(fn):
    return File(fn, 'r')['default']

sample = from_h5(fnames[0])

st = time.time()
arrs1 = [da.from_array(from_h5(fnames[ind]), chunks=sample.shape) for ind in range(dims[0])]
test1 = da.stack(arrs1)
en = time.time()
print(f'Using from_array(h5py.File): stack finished in {en-st:.2f}s')

st = time.time()
arrs2 = [da.from_array(da.from_delayed(delayed(from_h5)(fnames[ind]), shape=sample.shape, dtype=sample.dtype),chunks=sample.shape) for ind in range(dims[0])]
test2 = da.stack(arrs2) 
en = time.time()
print(f'Using from_array(from_delayed(h5py.File)): stack finished in {en-st:.2f}s')
```
output:
```
Python : 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]
Dask : 0.18.1
h5py : 2.8.0
Using from_array(h5py.File): stack finished in 0.53s
Using from_array(from_delayed(h5py.File)): stack finished in 0.34s
```

I suspect this time difference arises because calling `h5py.File()` serially can be slow, and wrapping it in `delayed()` mitigates the serial execution. 

Calling `from_array(from_delayed(delayed(h5py.File())))` is kind of ugly but I understand why it's necessary, since there's an ambiguity between the `h5py` dataset (which`from_delayed` will return) and the underlying array (which `from_array` will properly represent based on the `h5py` dataset). 

Unfortunately I can't see any obvious way to change `from_array` or `from_delayed` in light of this, but I thought I would at least post the (hopefully) reproducible example and expose the issue to the dask devs.

**Comment by jakirkham** [comment]
Would suspect this is because multiple files are being opened. If one `h5py.File` instance was opened and then selected from for all cases, this is probably a bit faster. Would be good to test if this is true or not though.

**Comment by mrocklin** [comment]
It might be worth asking on the XArray issue tracker.  That community deals
with this problem frequently.

**Comment by TomAugspurger** [comment]
Does anyone have concrete suggestions on how to close this? I could imagine an API for reading in a directory of h5py files, but that feels like it's on the edge of dask array's scope.

**Comment by d-v-b** [comment]
I did some more research on this and I found that the the fundamental slowness / hysteresis has to do some with h5py internal state, so essentially it's not a dask issue; the `delayed` solution is perfect adequate for my purposes, so from my point of view the issue can be closed.

**Comment by martindurant** [comment]
Let's close, in that case.

**Comment by jakirkham** [comment]
Glad to hear `delayed` is working well for you 🙂
