### ISSUE TITLE
Dask array setitem with differently chunked data provides wrong shape

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3730]
```python
>>> import dask.array as da
>>> x = da.zeros(5, chunks=2)
>>> m = da.zeros(5, chunks=3)
>>> x[m>0] = 1
>>> print x.shape, x.compute().shape
(5,) (4,)
```

This should probably unifiy chunks before slicing

**Comment by mrocklin** [comment]
Marking this as "good first issue".  I suspect that it might be a bit challenging, but it does take new developers through thinking about chunks.

**Comment by itamarst** [comment]
Looks educational, going to try to do this.

**Comment by mrocklin** [comment]
I appreciate you going through this
