### ISSUE TITLE
Dask API for larger-than-memory matrix dot

### ISSUE THREAD

**Issue by tzhang298** [dask/dask#3732]
I am using Dask for large-than-memory matrix multiplication. If I limit the memory to be 128MB, the program is killed when do 1000x1000 matrix dot. Whereas in-memory 1000x1000 matrix dot works perfectly. Could anyone give me some directions about where I did wrong? Thank you very much! 

    import dask as dk
    import tables
    import numpy as np
    import sys
    from time import time
    import math
    import h5py

    outpath = "/data/dottest/"
    lenx = int(sys.argv[1])
    leny = int(sys.argv[2])
    numpart =int( math.sqrt(int(sys.argv[3])))

    fname = "t{0:03d}_{1:03d}.h5".format(int(lenx),int(leny))

    def writefile():
        h5f = h5py.File(fname, 'w')
        
        pres = np.random.random((lenx,leny))
        h5f.create_dataset('pressure',shape=pres.shape,chunks=(leny/numpart,lenx/numpart),dtype='f8',data=pres)
        
        lines = np.random.random((leny,lenx))
        h5f.create_dataset('lines',shape=lines.shape,chunks=(lenx/numpart,leny/numpart),dtype='f8',data=lines)
    
        h5f.close()

    def dottest():
        import h5py
        import dask.array as da
        h5open2 = h5py.File(outpath+fname)
    
        print('numpart = ',numpart)
        
        d1=da.from_array(h5open2["/pressure"],chunks=(leny/numpart,lenx/numpart))
        d2=da.from_array(h5open2["/lines"],chunks=(leny/numpart,lenx/numpart))
        print d1 
        print d2

        t = d1.dot(d2)
        s = t.compute()
        
        print("dot finished")
        h5open2.close()

    writefile()
    dottest()

$echo 134217728 > /sys/fs/cgroup/memory/mygroup/memory.limit_in_bytes

$cgexec -g cpu,memory:mygroup python inmemory.py 1000 1000 

0.0245869159698

$cgexec -g cpu,memory:mygroup python newdasktest.py 1000 1000 4

dask.array 'array, shape=(1000, 1000), dtype=float64, chunksize=(500, 500)'

dask.array 'array, shape=(1000, 1000), dtype=float64, chunksize=(500, 500)'

killed

**Comment by mrocklin** [comment]
Matrix multiply is not easily streamable.  Dask is not a good library for
out-of-memory matrix multiplications.

**Comment by sherlockwu** [comment]
@mrocklin according to your old blog here: 
http://matthewrocklin.com/blog/work/2015/01/14/Towards-OOC-MatMul

Is Dask + Blaze still a good solution for out-of-core matrix multiplications? or you would recommend some other libraries? Thanks.

PS. seems the API of Dask and Blaze are quite different now, compared to what you used in the blog.

**Comment by mrocklin** [comment]
That blogpost is several years old.  I recommend reading documentation to understand the current state of things. 

It depends on the shape of the matrix.  Not all shapes can be done efficiently in low memory.  

Closing.
