### ISSUE TITLE
repartition dask dataframe gives faulty partitions.

### ISSUE THREAD

**Issue by MosheVai** [dask/dask#3736]
when repartitioning a dask dataframe according to a certain frequency the last partition contains values that should not be in this partition.

example: 
```python 
import pandas as pd
nums = [f'{i:02},' for i in range(0,3)]
dates = pd.date_range('2018-07-01', periods=3, freq='1d')
df = pd.DataFrame({'dates':dates, 'nums': nums}).set_index('dates')
df
```

<details>

|            | nums |
|------------|------|
| dates      |      |
| 2018-07-01 | 00,  |
| 2018-07-02 | 01,  |
| 2018-07-03 | 02,  |

</details>

when loading to a dask dataframe, repartitioning with a daily frequency and printing the partitions
you can see that last partition contains two days.

```python
from dask import dataframe as dd
ddf = dd.from_pandas(df, npartitions=1).repartition(freq='1d')
for i in range(ddf.npartitions):
    print(ddf.get_partition(i).compute())
``` 
<details>

|            | nums |
|------------|------|
| dates      |      |
| 2018-07-01 | 00,  |

|            | nums |
|------------|------|
| dates      |      |
| 2018-07-02 | 01,  |
| 2018-07-03 | 02,  |
</details>

**Note**: this also happens with other frequencies.

Python 3.6.5 :: Anaconda, Inc. 
dask Version: 0.18.1 
pandas Version: 0.23.0

**Comment by quasiben** [comment]
possible related to #3714 .  I think this has to do with the initial setting of `npartitions=1` ?  If the divisions/index don't have an initial frequency then I don't think dask can guarantee perfect partitions

cc @mrocklin

**Comment by TomAugspurger** [comment]
I think this is unavoidable when your repartition freq matches the resolution of the timestamps.

The divisions will always have the minimum of each partition and the max of the last. That means you have to have the following divisions.

```
(Timestamp('2018-07-01 00:00:00', freq='D'),
 Timestamp('2018-07-02 00:00:00', freq='D'),
 Timestamp('2018-07-03 00:00:00', freq='D'))
```

I don't think there's anything dask could do here, other than perhaps document that. Would welcome a PR to clarify this in the docs. I couldn't quite find a nice way to word it.
