### ISSUE TITLE
Gzip.open and dask.dataframe.read_csv not functioning.

### ISSUE THREAD

**Issue by Eriz11** [dask/dask#3739]
Hi,
After having memory issues with `pandas`, I switched to `dask` but I have execution problems in the below code:

```
import os, gzip, pandas as pd, time, dask.dataframe as dd 

rootdir = "/home/eriz/Desktop/2012_peter"

dataframe_total_list = []

counter = 0 

start = time.time()

for subdir, dirs, files in os.walk(rootdir):
    dirs.sort()
    
    for files_gz in files:
        
        with gzip.open(os.path.join(subdir, files_gz)) as f:
             
             df = dd.read_csv(f)
             dataframe_total_list.append(df)
             counter += 1
             print(counter)

    total_result = dd.concat(dataframe_total_list)
    total_result.to_csv("/home/eriz/Desktop/2012_dd.csv")
    print(total_result.shape)
           
    end = time.time()
    print(end - start)
```

Giving this error: 

````
Traceback (most recent call last):
  File "/home/eriz/ZMproject/GitHub/QuantPro/1_preprocess_data/1_unzip.py", line 36, in <module>
    df = dd.read_csv(f)
  File "/home/eriz/miniconda3/envs/quant/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 426, in read
    **kwargs)
  File "/home/eriz/miniconda3/envs/quant/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 302, in read_pandas
    **(storage_options or {}))
  File "/home/eriz/miniconda3/envs/quant/lib/python3.6/site-packages/dask/bytes/core.py", line 89, in read_bytes
    size = logical_size(fs, path, compression)
  File "/home/eriz/miniconda3/envs/quant/lib/python3.6/site-packages/dask/bytes/core.py", line 505, in logical_size
    return fs.size(path)
  File "/home/eriz/miniconda3/envs/quant/lib/python3.6/site-packages/dask/bytes/local.py", line 67, in size
    return os.stat(self._normalize_path(path)).st_size
FileNotFoundError: [Errno 2] No such file or directory: "/home/eriz/hello/<gzip _io.BufferedReader name='/home/eriz/Desktop/2012_peter/20120101/ESH2.csv.gz' 0x7f09a3ae7f98>"
````

I have confirmed that the file exists - this code works well with `pandas` but fails to work now and I don't find any reference in the web to solve it. As you can see, I'm using absolute paths. Also, issue has nothing to do with `compression` or `chunksize` parameters; so I'm a bit confused.

Please, if you could help I would appreciate it very much.

Details: Linux (Ubuntu 18.04), Dask 0.18.1

**Comment by martindurant** [comment]
Do not pass open gzip file objects to dask. It should be enough to do the following:
```df = dd.read_csv(files)```

**Comment by Eriz11** [comment]
Hi Martin, 

Thanks for the quick reply. I will check it and see if it works and quote on the same; I’m new on working with big files, compressions... so struggling a bit until I understand it.

Moreover, could you please put some clarity for me on the concept dask uses so that scripts dont run out of memory? 

I mean, in which step puts information in RAM and when/how releases it and uses the available disk space? 


Thanks again,

**Comment by martindurant** [comment]
I'm sorry, your questions are very vague - is there something specific you are having trouble with? Dask *can* run out of memory. I advise you to read through the documentation or perhaps run through one of the tutorials.

> on the concept dask uses so that scripts dont run out of memory

Working on data chunk-by-chunk

> which step puts information in RAM...

Perhaps you want this? http://distributed.readthedocs.io/en/latest/memory.html

**Comment by Eriz11** [comment]
My bad; I'm also new in asking detailed questions. Always learning.

I'm finding issues in processing huge datasets (this is the [question](https://stackoverflow.com/questions/51243386/memory-problems-with-pandas-understanding-memory-issues?noredirect=1#comment89465507_51243386) I asked in SO, in which they pointed me to look at `dask`, which may resolve my issues).

Maybe you could give some more insights in if I will also run into troubles with `dask` or it may help me.

Thank you so much for the guidance again.

**Comment by martindurant** [comment]
Replied on SO.
