### ISSUE TITLE
Feature request: Option to add a final newline in Bag.to_textfiles

### ISSUE THREAD

**Issue by gsakkis** [dask/dask#3743]
I was kinda caught by surprise with `Bag.to_textfiles()` not ending each partition file with a newline; using a simple `cat *.part > full` bash line to concatenate them doesn't work as expected. It would be useful to add an optional parameter, say `final_newline=False`, to end each partition file with a newline.

**Comment by martindurant** [comment]
Sounds reasonable and not hard to implement.
Would you be interested in writing a PR?

**Comment by gsakkis** [comment]
Yeah i'll give it a try, thanks!
