### ISSUE TITLE
dask.visualize doesn't visualize non-dict mappings

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3749]
Currently `dask.visualize` will only visualize a dask graph that's an actual dictionary. Notably, `sharedict`s are not visualized.

```python
import dask
import dask.array as da

dask.visualize(da.random.uniform(size=(10, 10), chunks=5).dask)
# no graph is visualized
```

(of course, you would just pass the collection, not the `.dask`).

@jcrist do you recall, is there a reason for hardcoding `dict` here? https://github.com/dask/dask/blame/d8f7ad314f37729167902f5129ee0287d35a5ac7/dask/base.py#L457

**Comment by mrocklin** [comment]
Presumably this should use `collections.MutableMapping` instead.  Marking as good first issue.

Not sure how best to test this.

**Comment by mrocklin** [comment]
We probably have to test against one of the lower functions that `visualize` calls that produces a networkx graph or similar.

**Comment by jcrist** [comment]
> Presumably this should use `collections.MutableMapping` instead.

I know of one project that has a `MutableMapping` subclass that is also dask collection. We should probably check each item first if it's a dask collection, then check the remainder if they're mutable mappings.

---

Also, side note, I find the fact that `visualize` handles raw dask graphs odd compared to the other top-level functions. It breaks the parity between `compute`/`persist`/`optimize`, and prevents things like the following:

```python
a = dask.delayed(lambda x: x + 1)(1)
o = {'a': a, 'b': a + 1}
dask.compute(o)  # computes all the delayed object in the dict
dask.visualize(o)  # doesn't work on nested objects
```

**Comment by asmith26** [comment]
Hi there,

This seems to be working now:
![image](https://user-images.githubusercontent.com/6988036/60468786-a9b56700-9c52-11e9-87cd-c9d7357c61f1.png)

**Comment by jrbourbeau** [comment]
I can confirm that in the current `master` branch, `visualize` works with both dask collections and `Mapping` instances. Thanks for following up on this @asmith26! Closing
