### ISSUE TITLE
Support configuring the `multiprocessing` context

### ISSUE THREAD

**Issue by itamarst** [dask/dask#3758]
`multiprocessing` supports different context, with different tradeoffs. Currently Dask only allows setting a custom *global* pool. This causes some problems:

1. It's not possible to use a different context with multiple pools: users are forced to use a single global pool if they want to use a different context.
2. It impedes changing the default context (see followup issue #3759).

Solution: support setting a multiprocessing context in the configuration, instead of just defaulting to the default `fork` context.

**Comment by itamarst** [comment]
Going to start on this during the sprint.

**Comment by mrocklin** [comment]
+1!

**Comment by mrocklin** [comment]
Also cc @jcrist

**Comment by itamarst** [comment]
Bit tricky in that one needs to create compatible Lock/Queue/etc. from the same context object, so need to figure out how to ensure that happens.

**Comment by jakirkham** [comment]
Would you be able to comment more on your motivating use case?

**Comment by mrocklin** [comment]
@itamarst would like to move our default from `fork` to `spawn`.  This is a lightweight step in that direction.

**Comment by itamarst** [comment]
@jakirkham in particular see #3759.

**Comment by jakirkham** [comment]
Hmm...thought our default was `forkserver` or is that just in Distributed?

**Comment by itamarst** [comment]
In non-Distributed default is the Python default, which on POSIX is the broken `fork`.
