### ISSUE TITLE
ValueError exception when using da.stack() is too verbose.

### ISSUE THREAD

**Issue by nmiles2718** [dask/dask#3762]
I was attempting to stack 1-d arrays that were read in from a list of `hdf5` files and I blindly followed some boiler-plate [here (array-hdf5)](http://dask.pydata.org/en/latest/examples/array-hdf5.html#). I had ~10,000 arrays that I attempted to stack and the traceback was too verbose as it lists the size of each individual array that I was attempting to stack. 

It think the `Traceback` should  skip displaying the sizes of the individual arrays or handle them in a smarter way by return. Note that after _actually_ reading the [stack, concatenate, and block documentation](http://dask.pydata.org/en/latest/array-stack.html#) it was clear that I should be using `concatenate` and so it was really a user error on my part lol. 

Anyways, the problem still remains that the traceback is essentially unbounded. Plus, it's a simple fix as you only need to remove the  `"..Got %s", [x.shape for x in seq]"` portion of the `ValueError()` or maybe return only a list of the unique shapes tuples by doing `set([x.shape for x in seq])` or something along those lines.
 
MWE
``` python
import numpy as np
import dask.array as da

N=100
rand_size = np.random.randint(1e3,1e4,size=N) # N random array sizes
rand_arr = [np.random.rand(size) for size in rand_size] # N randomly sized arrays
da_rand_arr = [da.from_array(arr, chunks=1e2) for arr in rand_arr] # Convert them to dask arrays
x = da.stack(da_rand_arr, axis=0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-1bc07fcfdcc1> in <module>()
      6 rand_arr = [np.random.rand(size) for size in rand_size] # N randomly sized arrays
      7 da_rand_arr = [da.from_array(arr, chunks=1e2) for arr in rand_arr] # Convert them to dask arrays
----> 8 x = da.stack(da_rand_arr, axis=0)

~/miniconda3/envs/astroconda3/lib/python3.6/site-packages/dask/array/core.py in stack(seq, axis)
   3637     if not all(x.shape == seq[0].shape for x in seq):
   3638         raise ValueError("Stacked arrays must have the same shape. Got %s",
-> 3639                          [x.shape for x in seq])
   3640 
   3641     ind = list(range(ndim))

ValueError: ('Stacked arrays must have the same shape. Got %s', [(3556,), (4444,), (3314,), (7310,), (9619,), (2346,), (3513,), (4840,), (7844,), (4226,), (5426,), (6735,), (9695,), (6998,), (9099,), (7529,), (3825,), (3720,), (8882,), (8107,), (2361,), (5933,), (7392,), (2839,), (8659,), (9984,), (5285,), (5445,), (8320,), (7674,), (8962,), (3500,), (7632,), (5624,), (3374,), (5849,), (1425,), (8344,), (1487,), (5457,), (6076,), (1608,), (1611,), (4152,), (3408,), (8743,), (5775,), (8244,), (1069,), (2922,), (9263,), (2802,), (6441,), (4198,), (3101,), (5776,), (2487,), (9003,), (2015,), (7582,), (5734,), (8715,), (8161,), (7697,), (7131,), (2417,), (4067,), (1188,), (1151,), (7045,), (5605,), (8532,), (5192,), (3520,), (2684,), (8015,), (2839,), (6987,), (5875,), (2619,), (5820,), (7123,), (9466,), (7467,), (6434,), (8581,), (6593,), (7352,), (5708,), (1217,), (8538,), (1286,), (8735,), (1031,), (8512,), (2643,), (3304,), (2847,), (2390,), (9384,)])

```

**Comment by martindurant** [comment]
Rather than removing the information at all, maybe it's worthwhile printing the first size that failed?

**Comment by nmiles2718** [comment]
Yeah, I like the idea of returning the first size that fails. Returning a list of only the unique sizes still has the same problem in the event that all arrays have different sizes.

**Comment by martindurant** [comment]
Something like: "all shapes so far were {}, but at chunk {} found shape {}"

**Comment by nmiles2718** [comment]
Ok, so here's what I came up with:
```python
if not all(x.shape == seq[0].shape for x in seq):
    idx = np.where(np.asanyarray([x.shape for x in seq]) != seq[0].shape)[0]
    raise ValueError("Stacked arrays must have the same shape.\n"
                     "The first {0} had shape {1}, while array "
                     "{2} has shape {3}".format(idx[0],
                                                seq[0].shape,
                                                idx[0] + 1,
                                                seq[idx[0]].shape))
```
Example:
```python
N=20
rand_size = np.random.randint(1e2,1e3,size=N)
rand_size = np.insert(rand_size,[1]*20,rand_size[0])
rand_arr_2d = [np.random.rand(size, size) for size in rand_size]
da_rand_arr_2d = [da.from_array(arr, chunks=(50,50)) for arr in rand_arr_2d]
da.stack(da_rand_arr_2d)
```
```console
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-b0cddef797aa> in <module>()
----> 1 da.stack(da_rand_arr_2d)

~/dask/dask/array/core.py in stack(seq, axis)
   3790                          "The first {0} had shape {1}, while array "
   3791                          "{2} has shape {3}".format(idx[0], seq[0].shape,
-> 3792                                                     idx[0]+1, seq[idx[0]].shape)
   3793                          )
   3794 

ValueError: Stacked arrays must have the same shape.
The first 21 had shape (354, 354), while array 22 has shape (995, 995)
```

I ran `flake8 dask`, which caught a lack of whitespace around the `idx[0] + 1` line, so I fixed that. Then I ran `py.test dask/array --verbose` on my local copy and the `test_stack_err()` failed on the [second assertion](https://github.com/dask/dask/blob/5a4064d6c95435d132c8b7f0f2ee9aef63f3a73f/dask/array/tests/test_array_core.py#L3333). I went and printed out `str(e)` and for some reason it only displays the _first_ line in the error message supplied to `ValueError()`. Anyways, I removed the `'\n'` at the end of the first sentence and it passed. A second solution is to update the test function to explicitly access the `value` attribute of the raised exception (e.g. `str(e.value)` vs. `str(e)`). Any preference? I don't think there is much gained by including the `'\n'`, so I'm fine with just removing it and only changing one file.
