### ISSUE TITLE
Rolling aggregate

### ISSUE THREAD

**Issue by GPistre** [dask/dask#3769]
Is there any plan to implement aggregate (agg) for rolling objects, like in pandas ?

Is the reason it's not implemented yet because of structural difficulties with the way dask handles rolling windows ? (And so I should perhaps find a different way to approach this)

**Comment by mrocklin** [comment]
Looking briefly at the code it looks like it should be pretty easy to
implement.  You might want to look at the current source and see how
_call_method is used in functions like sum/mean/std.  This might be a good
first PR if you're interested.

https://github.com/dask/dask/blob/16957a92d9c5f2a7fce2a494b0c9c9ec11a13652/dask/dataframe/rolling.py#L225

**Comment by GPistre** [comment]
Basic functionality seems indeed quite easy

```
@derived_from(pd_Rolling)
def agg(self, func, args=(), kwargs={}, **kwds):
    return self._call_method('agg', func, args=args,
                             kwargs=kwargs, **kwds)
```

Seems to do the job for basic cases such as: 

```

import pandas as pd
import numpy as np
import dask.dataframe as dd
import datetime
from pandas.tseries.offsets import Day

time_range = pd.date_range(datetime.datetime(2016, 1, 1), datetime.datetime(2017, 1, 1), freq='D')

data = pd.DataFrame({'time': time_range,
                     'value': np.random.random(len(time_range))})
data = data.set_index('time')
data_dd = dd.from_pandas(data, npartitions=1)

result = data_dd.rolling(Day(10)).agg({'value': ['min', 'max', 'mean']}).compute()

```
However it would be interesting to implement it for groupby objects as well, but it seems slightly more involved and I'm not really familiar enough yet with the pandas / dask codebases to implement it comfortably.

**Comment by mrocklin** [comment]
Would you be interested in submitting a small PR with your implementation
and a small test?  This would probably be quite helpful for others.

Groupby might already have an aggregate method.  I suspect that for user
defined functions you'll have to use the apply_concat_apply or aca mehod.

**Comment by GPistre** [comment]
I can do that, I'll take a look.

**Comment by mrocklin** [comment]
I believe that this has been resolved.  Thank you @GPistre !
