### ISSUE TITLE
Organize Dask.delayed best practices doc to use tables

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3773]
This page: http://dask.pydata.org/en/latest/delayed-best-practices.html

Would look nicer if the code snippets were in tables.  

I believe that something like the following works:

```
+--------------------------------+-----------------------------+
| **Bad**                        | **Good**                    |
+--------------------------------+-----------------------------+
| .. code-block:: python         | .. code-block:: python      |
|                                |                             |
|                                |    @dask.delayed            |
|    def foo(...):               |    def foo(...):            |
|        ...                     |        ...                  |
|                                |                             |
+--------------------------------+-----------------------------+
```

I suspect that this will look quite a bit nicer and be easier for new users to understand.  This is also a good opportunity to go through the best practices documentation :)

Presumably this applies to other places within the codebase as well.

**Comment by quasiben** [comment]
@mrocklin @martindurant this issue has lingered for a bit .  Do you have more recent thoughts what you'd like to see done here and the associated PR ?
