### ISSUE TITLE
np.clip(dask array) does not return a dask array

### ISSUE THREAD

**Issue by rzu512** [dask/dask#3774]
Test:
```python
import dask.array as da
import numpy as np
x = da.arange(12, chunks=2)
y = np.clip(x, -1, 13)
z = da.clip(x, -1, 13)
print(type(x))
print(type(y))
print(type(z))
```
expected result:
```
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
```
actual result:
```
<class 'dask.array.core.Array'>
<class 'numpy.ndarray'>
<class 'dask.array.core.Array'>
```
Versions:
```
Python 3.6.5
Dask 0.18.1 installed with pip3 --upgrade
Numpy 1.14.2
Linux
```

**Comment by mrocklin** [comment]
It probably isn't a ufunc.  This would need to be resolved upstream in
Numpy.  There are active conversations about this topic generally more
generally (beyond just clip).  I recommend that you raise an issue there so
that they understand that the mismatch affects users.

**Comment by martindurant** [comment]
On my dask/numpy, I get an error 

```
In [8]: y = np.clip(x, -1, 13)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-b75e3d19207c> in <module>()
----> 1 y = np.clip(x, -1, 13)

~/anaconda/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py in clip(a, a_min, a_max, out)
   1738     except AttributeError:
   1739         return _wrapit(a, 'clip', a_min, a_max, out)
-> 1740     return clip(a_min, a_max, out)
   1741
   1742

TypeError: clip() takes from 1 to 3 positional arguments but 4 were given
```

because `np.clip(x)` explicitly calls `x.clip()` *and* passes the `out` parameter, `None` in this case.

np: 1.11.3, dask: 0.18.1+ (master)

**Comment by rzu512** [comment]
i have numpy 1.14.2

**Comment by martindurant** [comment]
Yep, their implementation changed to look for the attribute immediately; but the problem is still the same, it is trying to pass `out=` to the `x.clip()`, which causes an exception, so it falls back to using `np.asarray`.

**Comment by mrocklin** [comment]
I recommend pushing this upstream.  It's more important that the Numpy
folks see issues like this.

**Comment by martindurant** [comment]
Agreed, just clarifying.

**Comment by rzu512** [comment]
If I understand this issue correctly, I worry the following might happen.
If I rely on this and this is not as expected, my program might silently compute an intermediate dask array to a numpy array.
After that, the program transforms the numpy array is to a final dask array.
When the intermediate array is too large, the program will get out of memory error.
It probably will take a while to find out exactly what goes wrong.
I will always use the function provided by dask array instead of numpy, even when I port a numpy program to a dask program.

**Comment by mrocklin** [comment]
Yes, that is exactly the problem.  I recommend that you report that
upstream to Numpy so that they understand the problem as you have just
stated it.

Unfortunately there is nothing that can be done within Dask itself to solve
this problem.  The solution must come from within Numpy.  Please raise this
upstream in the Numpy issue tracker.
