### ISSUE TITLE
docs figures not loading

### ISSUE THREAD

**Issue by crashMOGWAI** [dask/dask#3775]
visualize() figures for diagnostics/profilers are not loading in docs

https://dask.pydata.org/en/latest/diagnostics-local.html

**Comment by mrocklin** [comment]
They seem to show for me.  I suspect that this is a browser issue.   I recommend providing information about your system and browser.

**Comment by crashMOGWAI** [comment]
Yep, it's a browser issue. Works fine on alternatives. 

Issue seen on Edge: 
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if it's still an issue.
