### ISSUE TITLE
categorical.as_known returns incorrect type for already known categorical

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3784]
In https://github.com/dask/dask/blob/003962f61dc2c19e363ad723e9bb0ca406afd621/dask/dataframe/categorical.py#L186-L187 we return `self`, which is a `CategoricalAccessor`.

I think that should return `self._series`, the dask series.

**Comment by Sriharsha-hatwar** [comment]
hey @TomAugspurger will take up this.

**Comment by quasiben** [comment]
resolved by https://github.com/dask/dask/pull/3888
