### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3789]
It's been about a month since our last release. We seem to have accumulated a bunch of nice features and fixes in that time. How do we feel about making a new release?

**Comment by jakirkham** [comment]
Thoughts?

cc @mrocklin @TomAugspurger @martindurant @shoyer

**Comment by shoyer** [comment]
I support making non-breaking releases as often as practical

**Comment by mrocklin** [comment]
It seems reasonable to me.

I'm slightly concerned by the state of tests in dask/distributed (we have
more intermittent failures than normal) but I don't think that would stop a
release of dask/dask.  We'd want to verify that dask/dask can operate
cleanly with the latest release of dask/distributed.

**Comment by jakirkham** [comment]
I'm ok waiting for test failures to be resolved. FWIW along those lines found a Python 3.4 bug that we need to fix before releasing Dask. ( https://github.com/dask/dask/pull/3791 )

**Comment by mrocklin** [comment]
I don't necessarily plan to spend the time necessary to track down the
intermittent failures in dask/distributed in the next week or so.  This is
a large endeavor.  To be clear, *most *of the test suite *usually *passes.
Reliably testing distributed systems is hard.

**Comment by mrocklin** [comment]
Anyway, it would probably be ok to release distributed, but I'd prefer to
wait.  If you can release dask/dask and have it operate cleanly with the
existing dask/distributed version then I'm all in favor.  I suspect that
this is the case, but it would be good to verify.

**Comment by jakirkham** [comment]
FWIW nothing in the diff since the last release made me think a new Distributed release was necessary. Also didn't seen any breaking changes. However wouldn't mind another set of eyes to verify.

**Comment by jakirkham** [comment]
Ideally I'd like to do the release today once any test failures are addressed. Am fine with having another release soon after if it is helpful to people. Please let me know if you have a different timeline in mind.

**Comment by mrocklin** [comment]
I'm not planning to touch any kind of testing work in dask or distributed
today or this weekend.

I'm going to ask that before we release either package that we verify that
things work well with the latest release.

**Comment by shoyer** [comment]
> I'm going to ask that before we release either package that we verify that
things work well with the latest release.

Is this an automated process? Or something that you do in a more ad-hoc way?

**Comment by mrocklin** [comment]
Typically I do this in an ad-hoc way on a couple machines I have lying
around.  Our CI is also designed to test master against master, but not
master against latest release.

Don't get me wrong though, I'd love to see an easier solution.  In practice
it's not that much of a burden on me personally though.

**Comment by jakirkham** [comment]
> I'm going to ask that before we release either package that we verify that things work well with the latest release.

Happy to do that. What is the best way to test the Distributed reliant components of Dask?

**Comment by mrocklin** [comment]
I would create a new conda environment, install distributed, then check out
the master version of dask and run both test suites

**Comment by jakirkham** [comment]
Alright, it may have been a bit ambitious to try to get it out today. That said, it was a useful exercise to attempt as it caught a few issues.

Here's the current list of blockers I found.

* https://github.com/dask/dask/issues/3793 (fix proposed)
* https://github.com/dask/dask/issues/3794 (fix proposed)
* https://github.com/dask/dask/issues/3795 (no current fix)

Also here are some fixes for the blockers above.

* https://github.com/dask/dask/pull/3791
* https://github.com/dask/dask/pull/3796

**Comment by mrocklin** [comment]
Thank you for going through this @jakirkham .  I suspect that some of these have been hanging around for a while (in my ad-hoc process I don't tend to test 3.4).  I'm probably fine not solving all of these (the current release probably doesn't solve them either) but I agree that in principle we should.

**Comment by mrocklin** [comment]
My apologies also for generally being somewhat inactive at the moment on this topic.  I can sense that you'd like to get things out quickly.  I've been focused on some other work recently.

**Comment by mrocklin** [comment]
Regardless, it's good to get others engaged in this process.

**Comment by jakirkham** [comment]
Sure, happy to help. Yeah, it's possible.

Ok. Guess I'd lean towards getting any small fixes that we already have PRs for in. Anything more complicated I'm happy to either punt on or simply mark the test as a known fail with some reference back to an issue for discussion. Generally looks like things aren't too bad actually, which is encouraging.

No worries. It's my fault for bring this up rather last minute. Again am ok giving it a couple days (just to be clear excluding the weekend) if that would help.

**Comment by jakirkham** [comment]
Have merged the fixes that have been checked and passed. Also Stephan identified one of issues as a likely upstream bug, which has now been confirmed. Only issue ( https://github.com/dask/dask/issues/3794 ) remains.

**Comment by mrocklin** [comment]
To be clear, my original request was also to verify that the `distributed`
test suite works with any proposed release of dask.

**Comment by jakirkham** [comment]
Was thinking at a bare minimum we can mark that test as a known failure. There is an issue already open to track it. Though could just skip that altogether if you prefer.

Just now saw there were a few other PRs that you were interested in getting in. Should we hold off until early next week to save some time for reviewing these? FWIW am ok with that plan just wanted to get your thoughts.

**Comment by mrocklin** [comment]
The only thing I see particular value in getting in sooner is
https://github.com/dask/dask/pull/3780 , but even that can wait if it needs
more discussion.  I have no blockers on release on than to verify that
things work well with a couple of the more common downstream packages, like
dask/distributed.

**Comment by jakirkham** [comment]
Added the changelog for 0.18.2 to PR ( https://github.com/dask/dask/pull/3804 ). Please take a look.

**Comment by jakirkham** [comment]
How do you typically upload Dask to PyPI? Would like to make sure I'm doing this in a consistent way.

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/blob/master/docs/release-procedure.md

**Comment by jakirkham** [comment]
Thanks. Release is tagged. Have upload packages to PyPI.

conda-forge release is under way.

xref: https://github.com/conda-forge/dask-core-feedstock/pull/20
xref: https://github.com/conda-forge/dask-feedstock/pull/45
