### ISSUE TITLE
test_json_compressed[xz] fails on Python 2.7

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3793]
Seems `test_json_compressed[xz] ` requires `backports.lzma` on Python 2.7 and it didn't get installed by installing `dask` from `conda-forge`. Should we be adding this as a dependency? Should we skip this test if `backports.lzma` is not present? Other thoughts?

**Comment by jakirkham** [comment]
Should add installing `backports.lzma` did fix the issue.

**Comment by mrocklin** [comment]
Definitely not a dependency.  I think that lzma is infrequently used

**Comment by jakirkham** [comment]
Ok, how about skipping the test like so ( https://github.com/dask/dask/pull/3796 )?
