### ISSUE TITLE
Python 3.4 support timeline

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3797]
Raising this to figure out when we want to drop Python 3.4. FWIW [xarray recently dropped Python 3.4]( https://github.com/pydata/xarray/commit/74625d463ec71ac6f4a3642d3385bd9cbf8381ce ). scikit-image still supports Python 3.4. hyperspy doesn't appears to be Python 3.5+. Not sure what other packages our downstream that are using it. Anyways just raising this for discussion at this point.

**Comment by mrocklin** [comment]
cc @stefanv do you all have plans here?  We'd like to drop this soon if
possible.

**Comment by stefanv** [comment]
We're done with 3.4 in scikit-image, as of our last release.

**Comment by mrocklin** [comment]
I recommend that we drop 3.4

**Comment by hugovk** [comment]
Here's the pip installs for dask from PyPI for June 2018, showing low numbers for 3.4:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  46.24% |         54,143 |
| 2.7            |  40.93% |         47,916 |
| 3.5            |  11.72% |         13,720 |
| 3.4            |   1.02% |          1,198 |
| 3.7            |   0.08% |             98 |
| 3.3            |   0.00% |              3 |
| 2.6            |   0.00% |              1 |
| Total          |         |        117,079 |

Source: `pypinfo --start-date 2018-06-01 --end-date 2018-06-30 --percent --markdown dask pyversion`

**Comment by mrocklin** [comment]
Cool.  That's very helpful.  Thank you Hugo!
