### ISSUE TITLE
Fuse dataframe collections by default

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3801]
Currently we don't fuse dask.dataframe computations by default

```python
In [1]: import dask

In [2]: df = dask.datasets.timeseries()

In [3]: len(df.dask)
Out[3]: 30

In [4]: len((df.x + 1 + 2 + 3).dask)
Out[4]: 150

In [5]: len(dask.optimize((df.x + 1 + 2 + 3))[0].dask)
Out[5]: 150

In [6]: dask.config.set(fuse_ave_width=1)
Out[6]: <dask.config.set at 0x7f42e84f0b00>

In [7]: len(dask.optimize((df.x + 1 + 2 + 3))[0].dask)
Out[7]: 60
```

Should we?  If I recall correctly this was done for two reasons:

1.  Fusing can be about as expensive as the overhead of running
2.  By fusing you sometimes lose out on shared structure between subsequent computations

However, as I've seen more ways in which dask.dataframe gets used in the wild I've found that *very* long linear-ish chains are pretty common.  The overhead of the distributed scheduler is a bit higher, and having very long linear chains affects other things, like diagnostics, the memory on the distributed scheduler process, etc..

**Comment by jcrist** [comment]
Yes, thanks. Closing.
