### ISSUE TITLE
Some tests assume endianness

### ISSUE THREAD

**Issue by QuLogic** [dask/dask#3811]
On [ppc64](https://koji.fedoraproject.org/koji/taskinfo?taskID=28589824) and [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=28589826), two big-endian arches, two tests seem to fail due to some assumptions in tests and/or implementation:

```
_______________________ test_concatenate_types[dtypes1] ________________________
dtypes = (('<f4', '<f8'), '<f8')
    @pytest.mark.parametrize('dtypes', [(('>f8', '>f8'), '>f8'),
                                        (('<f4', '<f8'), '<f8')])
    def test_concatenate_types(dtypes):
        dts_in, dt_out = dtypes
        arrs = [np.zeros(4, dtype=dt) for dt in dts_in]
        darrs = [from_array(arr, chunks=(2,)) for arr in arrs]
    
        x = concatenate(darrs, axis=0)
>       assert x.dtype == dt_out
E       AssertionError: assert dtype('float64') == '<f8'
E        +  where dtype('float64') = dask.array<concatenate, shape=(8,), dtype=float64, chunksize=(2,)>.dtype
dask/array/tests/test_array_core.py:372: AssertionError

__________________________ test_concat_datetimeindex ___________________________
    def test_concat_datetimeindex():
        # https://github.com/dask/dask/issues/2932
        b2 = pd.DataFrame({'x': ['a']},
                          index=pd.DatetimeIndex(['2015-03-24 00:00:16'],
                                                 dtype='datetime64[ns]'))
        b3 = pd.DataFrame({'x': ['c']},
                          index=pd.DatetimeIndex(['2015-03-29 00:00:44'],
                                                 dtype='datetime64[ns]'))
    
        b2['x'] = b2.x.astype('category').cat.set_categories(['a', 'c'])
        b3['x'] = b3.x.astype('category').cat.set_categories(['a', 'c'])
    
        db2 = dd.from_pandas(b2, 1)
        db3 = dd.from_pandas(b3, 1)
    
        result = concat([b2.iloc[:0], b3.iloc[:0]])
>       assert result.index.dtype == '<M8[ns]'
E       AssertionError: assert dtype('>M8[ns]') == '<M8[ns]'
E        +  where dtype('>M8[ns]') = DatetimeIndex([], dtype='datetime64[ns]', freq=None).dtype
E        +    where DatetimeIndex([], dtype='datetime64[ns]', freq=None) = Empty DataFrame\nColumns: [x]\nIndex: [].index
dask/dataframe/tests/test_multi.py:1090: AssertionError
```
At least the latter looks like a test issue, but the former might be a problem in the implementation.

**Comment by martindurant** [comment]
Agree with your assessment, for the second, it would be enough to test `== 'M8[ns]'`.
For the first, the output endianness should match the input one, so the implementation is wrong somewhere. It would be worth checking whether the values came out right anyway.

**Comment by mrocklin** [comment]
The right thing to do here is probably to go through the dask/array/core.py::concatenate function and look at how it handles the dtypes of the inputs and output, and see if we can recreate this behavior with just numpy code, and then figure out why numpy makes the choices that it does.

https://github.com/dask/dask/blob/3fdc757ea58cdc13457f5a66acacca26871e1759/dask/array/core.py#L3036-L3134

**Comment by QuLogic** [comment]
> For the first, the output endianness should match the input one, so the implementation is wrong somewhere. It would be worth checking whether the values came out right anyway.

This does not match NumPy behaviour:
```python
In [13]: for i, dtype in enumerate([(('>f8', '>f8'), '>f8'), (('<f4', '<f8'), '<f8')]):
    ...:     dts_in, dt_out = dtype
    ...:     arrs = [np.zeros(4, dtype=dt) for dt in dts_in]
    ...:     print(i, np.concatenate(arrs).dtype.byteorder)
    ...:     
0 = >f8
1 = <f8
```
The result is in native byte order no matter the input.

**Comment by QuLogic** [comment]
Ping?

**Comment by mrocklin** [comment]
Thank you for resolving this in #4113 @QuLogic 

OK to close?

**Comment by QuLogic** [comment]
That only handles the second failure; I did not get any response about the first one.

**Comment by QuLogic** [comment]
No, what I mean is that if you're trying to emulate NumPy, then the endianness _should_ [switch to native](https://github.com/dask/dask/issues/3811#issuecomment-408361665).

**Comment by mrocklin** [comment]
@QuLogic sorry for the delay here.  If you have a recommendation on what should be done then I invite you to submit the solution.  I think you'll find that you're probably the most expert person here on this topic and that folks here trust your opinion.
