### ISSUE TITLE
Add DataFrame.nunique

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3817]
http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.nunique.html

essentially a `pd.concat([self[col].n_unique() for col self.columns], axis=1)`

Could do a `DataFrame.nunique_approx` as well.

**Comment by HassankSalim** [comment]
Can I pick this up ?

**Comment by mrocklin** [comment]
Yes!  In the future there is no need to ask.  We will take all the help we can get :)

**Comment by Avhirup** [comment]
@HassankSalim  Is the issue closed ? If not, i could help.

**Comment by HassankSalim** [comment]
I'm sorry, I was busy with work i couldn't pick it up

**Comment by quasiben** [comment]
This was resolved by:
- https://github.com/dask/dask/pull/1358 (nunique_approx)
- https://github.com/dask/dask/pull/1663 (nunique)

**Comment by datafuz** [comment]
@TomAugspurger Was your original issue addressed by the pull request? I don't believe that `DataFrame.nunique()` works like pandas (I'm guessing your original intension).  Also, `DataFrame.nunique_approx()` is a surprising result in that it returns a single value, not a value for each column, which would also be more analogous to the pandas result.

**Comment by TomAugspurger** [comment]
I'm not sure. If there's a behavior difference I'd recommend opening a new issue.
