### ISSUE TITLE
DataFrame.__setitem__ fails for index

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3818]
```python
In [10]: import pandas as pd

In [11]: import dask.dataframe as dd

In [12]: df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})

In [13]: ddf = dd.from_pandas(df, 2)

In [14]: df[df.columns] = 1

In [15]: ddf[ddf.columns] = 1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-736f0f46dec1> in <module>()
----> 1 ddf[ddf.columns] = 1

~/sandbox/dask/dask/dataframe/core.py in __setitem__(self, key, value)
   2430                                 for k, c in zip(key, value.columns)})
   2431         else:
-> 2432             df = self.assign(**{key: value})
   2433
   2434         self.dask = df.dask

~/Envs/dask-dev/lib/python3.6/site-packages/pandas/core/indexes/base.py in __hash__(self)
   2060
   2061     def __hash__(self):
-> 2062         raise TypeError("unhashable type: %r" % type(self).__name__)
   2063
   2064     def __setitem__(self, key, value):

TypeError: unhashable type: 'Index'
```

pandas index objects aren't hashable, putting them in a dictionary fails. We should probably special Index objects in `DataFrame.__setitem__` and convert them to lists.

**Comment by Sriharsha-hatwar** [comment]
Can I take up the task? is anyone looking into this? is there any guide for contributors?

**Comment by Sriharsha-hatwar** [comment]
Hey @TomAugspurger, could you please elaborate this statement ?

<<<
pandas index objects aren't hashable, putting them in a dictionary fails. We should probably special Index objects in DataFrame.__setitem__ and convert them to lists.
<<<

And also let me know if there are already existing test cases to validate the fix or we need to write a new one.

**Comment by TomAugspurger** [comment]
The problem is in https://github.com/dask/dask/blob/b88b805633051df046009650c400a865b5a638af/dask/dataframe/core.py#L2435-L2440

In that `else` block, I think should add a 

```
if isinstance(key, pd.Index)
    key = list(key)
```


Tests can go in dask/dataframe/tests/test_dataframe.py. A good test would be taking my example and ensure the dask and pandas operations give the same output

```python
df = ...
ddf = ...

df[df.columns] = 1
ddf[ddf.columns] = 1
assert_eq(df, ddf)
```

**Comment by TomAugspurger** [comment]
Hmm yes... I'm a bit confused by the current implementation. I suppose we
want to go down the `if` block, but that seems to expect `value` to be a
dataframe, which it might not be.

**Comment by Sriharsha-hatwar** [comment]
So do you have any implementation in mind for this?

**Comment by TomAugspurger** [comment]
Not off the top of my head, no.

________________________________

**Comment by Sriharsha-hatwar** [comment]
hey @TomAugspurger  and @mrocklin, do you think this is still a good first issue kind of fix? do you think I need to dive deeper into the way dask creates the partition for the objects?

**Comment by TomAugspurger** [comment]
Not sure. I haven't had time to look more closely.

**Comment by Sriharsha-hatwar** [comment]
I will have a look at this over the weekend and will submit a PR.
