### ISSUE TITLE
Applying da.arg* with axis argument uses non-tuple nd indexing

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#3835]
Applying a `da.array` function such as `da.argmax` along an axis yields the following warning:

```
C:\ProgramData\Anaconda3\lib\site-packages\dask\array\reductions.py:564:` FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. 
In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  vals = vals[inds]
```
This is not triggered for a function such as `da.max` and not triggered if either no axis argument is given or the array is 1D.
Minimal working example:
```
import dask array as da

Y =  da.random.random((10,10), chunks='auto')
da.argmax(Y, axis=0).compute()
```

Shows up on Python3.6 since I updated from dask 0.18.1 to 0.18.2.

I would like to spend some time on fixing this to get into this as my first issue, but frankly, I have no idea where to start.

**Comment by TomAugspurger** [comment]
Thanks for the report.

> Shows up on Python3.6 since I updated from dask 0.18.1 to 0.18.2.

I suspect that that upgrade also triggered an update to NumPy 1.15, which IIRC introduced this warning.

When debugging these warnings, I find elevating them to errors helpful

```python
import warnings
warnings.simplefilter("error", FutureWarning)
```

This points to https://github.com/dask/dask/blob/master/dask/array/reductions.py#L562-L565 as the source of the problem. We may be able to make `inds` a tuple, but I haven't looked closely. Let us know if you have any issues debugging further!
