### ISSUE TITLE
Unified filters/predicates interface for Parquet

### ISSUE THREAD

**Issue by xhochy** [dask/dask#3847]
Currently we support filters on row-group level based on an _AND_ of predicates. I would like to implement this in the next 4-6 weeks also for `pyarrow`. I have a pure Python implementation working but for my use case I required more than simply  _AND_. Therefore I would propose to change the current interface to accept predicates in disjunctive normal form. With this representation, we are able to represent all possible predicates.

This change would mean that we would also support `list of list of tuples` in 
https://github.com/dask/dask/blob/e823ecf51032ea7e4d57687a91d788cfb28e36ac/dask/dataframe/io/parquet.py#L915-L919

@martindurant @wesm @mrocklin Would that sound like an acceptable extension of the interface?

**Comment by mrocklin** [comment]
No objection from me, though I'm probably not the most up-to-date on the state of parquet reading/writing in dask.dataframe.  @martindurant would probably have more detailed thoughts.

**Comment by martindurant** [comment]
I am not opposed.
Changes in the fastparquet side would have to go into `fastparquet.api.filter_*`, I think.

**Comment by mrocklin** [comment]
Does this need to be implemented in fastparquet in order for it to be
implemented in dask.dataframe?  Or can we provide an informative error if
the feature only exists in some engines, but not all.

**Comment by martindurant** [comment]
No, it could be implemented for arrow alone, with an error message, or (since the logic isn't too complicated), be implemented for both in dask. At the moment, there are two functions in `fastparquet` for the filter functionality, and it would be nice if any implementation became available to users of the direct fastparquet API.

**Comment by wesm** [comment]
@xhochy can you create a tracking JIRA for this so we can tackle in the 0.11.0 release cycle?

**Comment by xhochy** [comment]
@wesm there is https://issues.apache.org/jira/plugins/servlet/mobile#issue/ARROW-1796 for this.
