### ISSUE TITLE
Move configuration to separate package

### ISSUE THREAD

**Issue by djhoese** [dask/dask#3853]
I have packages that could benefit from some/all of the configuration functionality provided by dask (thread-safe, environment variable overrides, yaml loading, etc). I had considered copying what I needed, but when I looked at it again `dask` had changed the preferred way of interfacing with the configuration settings. It also looked like a lot of the internals had changed. It has been a month or so since I've looked at the current implementation and it looks like it supports even more now.

Would the dask project/community be open to migrating the dask configuration functionality to a separate package that is agnostic of the package using it?

**Comment by mrocklin** [comment]
cc @jhamman @jcrist

**Comment by jcrist** [comment]
A few assorted thoughts:

- If this was to be pulled out of dask and into a separate project, this would be the first dependency of `dask-core` (currently you can install and use the dask local scheduler with no dependencies). Work could be done to make it so dask doesn't require the configuration library as a dependency, but that seems tricky and could lead to bugs. Perhaps adding a dependency is fine, both pip and conda make this easy.

- I personally don't care for the design of our config system's *python* api. A few reasons:
    - Does stuff at import time
    - Hard coded paths
    - Common api usage (e.g. `dask.config.get(...)`) *looks* like methods on an object, but is really functions on a module.

  If we were to pull the config out and make it a generic module, I'd prefer to also clean these things up. I'm less worried about these issues when used inside dask as we're the only users of this api, but for a generic package it might be nice to be cleaner. Of course these are just my opinions, and may differ from others.

One suggestion would be to copy the stuff out you want to use and start your own config library, making the api as you see fit. If it looks good and worth changing to, at some point in the future dask may decide to depend on your library.

**Comment by jcrist** [comment]
> For your first point, is there a use case that doesn't use pip or conda and can't be considered a "hack" or someone being lazy or solved with a --user flag on pip?

I'm not sure I follow this, but previously one of the touting points of dask was that the core library had no dependencies. This was important for some users, but maybe a bit irrational now. I'm honestly not sure.

> do you see any solutions that don't require a dask 2.0 release?

I think the user-facing api is fine - I'd really like to remove two behaviors from a configuration-specific library:

- required to do stuff on import (dask is free to load the config on import, but a config library shouldn't mandate this)
- Using a module as an object instead of having a class specific.

I think both of these might fall out of making what was very dask-specific into a reusable library.

**Comment by mrocklin** [comment]
The do stuff on import is already a choice of dask's, not of the config module.  See `dask/config.py::ensure_file()`. 

Presumably `dask.config` would become some sort of `Configuration` object with `get` and `set` methods

**Comment by djhoese** [comment]
```
  --user                      Install to the Python user install directory for your platform. Typically ~/.local/, or %APPDATA%\Python on Windows. (See the Python documentation for
                              site.USER_BASE for full details.)
```

In my experience a package having no dependencies is good for two things:

1. "cool" factor of saying it is pure python and self contained. Dask is cool enough 😉 
2. A user having some limitation on their environment (no write permissions to their python environment) or not knowing best practice for installing/using python libraries so they want to untar an sdist, add it to PYTHONPATH, and run their code.

**Comment by djhoese** [comment]
So if `dask/config.py` was replaced by `dask/__init__.py: config = magic_config_library.Config()` everything should work the same interface-wise by the sounds of it.

**Comment by jcrist** [comment]
That was my thought, unless users are importing `dask.config` directly (although we can hack around that as well, since Python is flexible with what a "module" really is). I wouldn't worry about our api here too much, as long as the configuration object has the same methods.

**Comment by djhoese** [comment]
Any good name ideas for a package like this? Any idea if something like this already exists?

**Comment by djhoese** [comment]
@jhamman @jcrist I'm finally getting back to this in my free time and I think I have a local version that is all bundled up in to a class instead of a module. New question (besides name ideas), if I put this in to its own package would you prefer to have it in the `dask` github organization or do you not feel strongly about that? If not, I might put it in my `pytroll` organization since I'll end up using it in our `satpy` package.

FYI I think the replacement for dask would be to do:

```python
# dask/__init__.py
from conf_lib import Config
config = Config('dask')
```

Which would set up all of the prefixes and environment variable checks to look for `DASK_*`, etc.

**Comment by mrocklin** [comment]
@djhoese ok to close?

**Comment by djhoese** [comment]
It depends. The `donfig` package does exist now and I could update the related PR (or start a new one) for dask to use that package. If this isn't anything dask is interested in then feel free to close, but try to keep me updated on changes to the dask config logic so I can update donfig with similar features.

**Comment by jrbourbeau** [comment]
@djhoese is it safe to close this issue? Seems as though discussion around potentially adopting `donfig` is happening over in #4328

**Comment by mrocklin** [comment]
Closing this for now.  Lets reopen if an active plan develops.

@djhoese , I'll endeavor to keep you updated when config changes occur.

**Comment by djhoese** [comment]
I was just about to reply and say this can be closed given that `donfig` exists and @mrocklin has been keeping me updated on any changes to `config.py`. I'm hoping with the recent `_/-` normalization change and merge that it will be easier for me to make a PR that can be considered for dask to fully switch to an object-based config interface.

After that we can consider `donfig` more. Is dask open to the idea of a "vendor" package being bundled in its source if the devs prefer not to add another dependency?

**Comment by mrocklin** [comment]
FWIW I've gotten a couple of requests from other projects about using Dask's config system.  At the same time we haven't been changing Dask's config system much recently.  It may start to make more sense to pull donfig into a "blessed" dask-config repository and start depending on it.

Thoughts anyone?

**Comment by djhoese** [comment]
Good with me: https://github.com/pytroll/donfig

While I have plans to use donfig for a couple other projects I'm really only using it in one other project so far.
