### ISSUE TITLE
Periodic project meetings

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3854]
Should we have a monthly or quarterly Dask meeting?

Currently there is a weekly thirty-minute meeting on Thursday, which tends to cover current work and pressing issues like "is there anything blocking the next release?" and "what else do we need to handle for the tutorial at the upcoming conference?".  This tends to have an attendance of around 4-6 people who actively work on the project day-to-day.

We might consider having a longer but less frequent meeting monthly or quarterly.  My hope is that this meeting would draw a larger group of stakeholders in the project and discuss larger issues like "should we drop Python 2.7?" and "how can we best support external project X?"

Some open questions:

1.  Would stakeholders who don't come to the weekly meeting come to the monthly/quarterly meeting?
2.  What is the most productive way to structure such a meeting?  What has worked well for other projects?

**Comment by martindurant** [comment]
I believe this is generally a good idea, if we can widen the group of attendees. Would it be worthwhile publishing the minutes of each meeting somewhere a bit more prominent than the current ongoing google-doc? Perhaps the meeting scheduler should be right in the main documentation.

**Comment by mrocklin** [comment]
Also brought up during last week's weekly meeting was that frequent meetings on more focused topics, like dask.array or dask-ml might be more interesting to a more focused group.

**Comment by jcrist** [comment]
For the last few months we've been meeting on the first thursday of every month at 16:00 UTC at http://appear.in/dask-dev. Closing.
