### ISSUE TITLE
Testspace Management for Travis CI

### ISSUE THREAD

**Issue by munderseth** [dask/dask#3859]
As suggestion by @mrocklin I am opening up an Issue to discuss how the [Testspace.com](https://testspace.com) technology could be used by the DASK team. We originally open an [Pull Request](https://github.com/dask/dask/pull/3839) that has been closed. Note that Testspace is completely **free** and does **not** affect the workflow. 

Testspace is designed for managing test results -- consumes content generated from Travis jobs. 

* **Failure Triage**: When there are a lot of failures, or the log is very large, or the failures happen across a number of jobs, etc. it can be tedious to track them down. Testspace provides a flat list very quickly containing the stderr output, etc.

    **Example Travis Build Jobs with failures:**
    
![travis build jobs](https://user-images.githubusercontent.com/1229367/43743216-c78a5866-9989-11e8-8b57-9c26cde4a06d.PNG)
 
   **Same Build using Testspace failure filtering:**

![travis build failure filtering](https://user-images.githubusercontent.com/1229367/43743228-d45e32ba-9989-11e8-84ff-4a938382a59e.png)

* **Metrics:** All of the results generated from the CI are collected and persisted for `history tracking`. This includes test results, code coverage, static analysis, and any custom content. Along with this information, statistical analysis is used to calculate `how effective the testing is` and measures the `workflow efficiency` (rates for resolving Pull Requests and test failures). 

* For more details check out this **LIVE DEMO**: https://demo.testspace.com. 

* Test results, metrics, insights, provides more visibility to others -- new contributors, unfamiliar with Travis, non-dev types, managers -- and enables easier navigation on content.

**Comment by jcrist** [comment]
My personal take is that I don't see a significant value over travis ci and coveralls that this service provides. Perhaps my opinion would change over time after using it, but on first glance I'm more happy with what I currently use. And while it's free and does not affect the workflow, it is One-More-Service™ to maintain and link to.

This is just my take though, other dask maintainers may have different opinions. I'll leave this open for other dask maintainers to give a quick vote, in particular @mrocklin, @TomAugspurger, @jakirkham, and @martindurant.

**Comment by TomAugspurger** [comment]
No preference.

________________________________

**Comment by mrocklin** [comment]
I share @jcrist's opinion here

**Comment by munderseth** [comment]
I thought I would add a few quick comments.

First I appreciate you guys taking the time to provide feedback -- thank you! I certainly understand the `One-More-Service` issue. 

Besides a _Dashboard for failure triage_ we see the main purpose of Testspace is for collecting all of the data generated from the CI process and analyzing the content for patterns related to the efficiency of the workflow.  For example, we track all of the New PRs, Closed PRs, Rejected PRs, PR Comments, etc. We also track unique regressions generated as a result of Code Changes.  All of these measurements and there are many more, are being used to statistically assess the workflow.

We are still working on our analytics, and having feedback from the Dask team actually using the product, in our humble opinion, could benefit both teams.

**Comment by jcrist** [comment]
Thanks for the explanation @munderseth. Based on the team's conversations here and offline, I think we're going to pass on this service for now. Best of luck with testspace, perhaps we'll decide to use it later on.
