### ISSUE TITLE
distributed.comm.core.CommClosedError error on Windows

### ISSUE THREAD

**Issue by icfly2** [dask/dask#3862]
Thank you for reporting an issue.

I'm trying to setup a `dask` distributed cluster, I've installed `dask` on  three machines to get started:

- laptop (where searchCV gets called)
- scheduler (small box where the dask scheduler process lives)
- HPC (Large box expected to do the work)

I have `dask[complete]` installed on the laptop and `dask` on the other machines. 
The worker and scheduler start fine and I can see the dashboards, but I can't send them anything. Running `GridSearchCV` on the laptop get's a result but it comes from  the laptop alone, the worker sits idle. 

All machines are windows 7 (HPC is 10) I've checked the ports with `netstat` and it appears that it is really listening where it is supposed to. 

When running a small example I get the following error:

    from dask.distributed import Client
    scheduler_address = 'tcp://10.X.XX.XX:8786'
    client = Client(scheduler_address)
    
    def square(x):
            return x ** 2
    
    def neg(x):
        return -x
    
    A = client.map(square, range(10))
    B = client.map(neg, A)
    total = client.submit(sum, B)
    
    print(total.result())

```
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://10.X.XX.XX:8786' processes=1 cores=10>>
Traceback (most recent call last):
  File "C:\Users\rmenk\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 1208, in _run
    return self.callback()
  File "C:\Users\rmenk\AppData\Local\Continuum\anaconda3\lib\site-packages\distributed\client.py", line 907, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "C:\Users\rmenk\AppData\Local\Continuum\anaconda3\lib\site-packages\distributed\batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError
```
the process does not stop and prints this error continuously for a while till it is killed. Making me suspect tornado or some other local async  aspect.

The client object is:
```

Client   
Scheduler: tcp://10.X.XX.XX:8786   
Dashboard: http://10.X.XX.XX:8787/status

Cluster    Workers: 1   Cores: 10   Memory: 68.72 GB
```

**Comment by mrocklin** [comment]
I recommend running client.get_versions(check=True) and see if that passes
without error

**Comment by icfly2** [comment]
@mrocklin I found that suggestion in another thread and am goign through that as it claims version missmatch. However it is a clean install on all three machines and when asking to upgrade with `pip install -U ` all report the same version. I'm guess ing `cloudpickle, dask and msgpack` need to be the exact same version? Or do all need to match?

**Comment by icfly2** [comment]
Yeah in an ideal world. We have some production code that relies on different versions of pandas :S I'm setting up everything in environments for dask, but this someone limits it's usefulness. Is it just the scheduler and workers that need to match or also the machine dispatching?

**Comment by icfly2** [comment]
Ok, so scheduler and worker having their own environments with the versions fixed through `pip freeze` works fine. From he laptop it works even with different versions, but from the `Jupyter notebook` it still fails. I'm guessing that is a separate issue. Thanks for your help and this awesome project.
