### ISSUE TITLE
NotImplementedError; struct<...> while reading from parquet using pyarrow engine (works with pandas)

### ISSUE THREAD

**Issue by RafaelIL** [dask/dask#3865]
File "/home/rafael.moraes/.virtualenvs/normalization_backend/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 995, in read_parquet
    categories=categories, index=index, infer_divisions=infer_divisions)
  File "/home/rafael.moraes/.virtualenvs/normalization_backend/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 579, in _read_pyarrow
    dtypes = _get_pyarrow_dtypes(schema, categories)
  File "/home/rafael.moraes/.virtualenvs/normalization_backend/lib/python3.6/site-packages/dask/dataframe/io/utils.py", line 26, in _get_pyarrow_dtypes
    numpy_dtype = field.type.to_pandas_dtype()
  File "pyarrow/types.pxi", line 176, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: struct<country: string, admin_area: string, sub_admin_area: string...>

I got this error while reading a parquet file using dd.read_parquet  with engine pyarrow, even if i remove the specific column with this struct type using (columns=) it still throw this error, if i switch to pandas it works fine, seems a dask related issue only.

**Comment by TomAugspurger** [comment]
Could you create a small example where you generate the data (with pyarrow / pandas), write it to a file, and read it in again?

What version of pyarrow?

**Comment by TomAugspurger** [comment]
Could you also post the pandas output?

**Comment by RafaelIL** [comment]
i have tested with pyarrow 0.10.0 and 0.9.0.
My work around now is reading with pandas then using dd.from_pandas().

The files was generated using Spark, the column type that is throwing this erro is a dict. That is why i cannot write it back then read it again with pandas/dask, i think pyarrow cannot handle this type.

**Comment by mrocklin** [comment]
It sounds like this should maybe be handled upstream?

**Comment by RafaelIL** [comment]
I mean i can read with pandas and pyarrow, but pyarrow cannot write back to parquet.

This is the actual structure of the parquet file.

pyarrow.Table
id: string
address: struct<country: string, area: string, sub_area: string, locality: string, sub_locality: string, thoroughfare: string, sub_thoroughfare: string, postal_code: string>
  child 0, country: string
  child 1, area: string
  child 2, sub_area: string
  child 3, locality: string
  child 4, sub_locality: string
  child 5, thoroughfare: string
  child 6, sub_thoroughfare: string
  child 7, postal_code: string
timestamp: int64
geoarea: list<element: string>
  child 0, element: string
location: struct<lat: double, lng: double>
  child 0, lat: double
  child 1, lng: double

**Comment by mrocklin** [comment]
This is an issue for upstream at PyArrow.  Closing

**Comment by RafaelIL** [comment]
@martindurant, as it works with pandas, im not sure if that is the problem, it seems Dask is using a different approach on the method read_parquet that is causing this issue cause i am not even using this column

**Comment by martindurant** [comment]
@RafaelIL , this was not clear (to me) from your initial report.
So, to be sure: `pd.read_parquet()` with pyarrow works, but `dd.read_parquet()` with pyarrow does not, for the same dataset? In that case it is a dask bug.

**Comment by RafaelIL** [comment]
@martindurant Sorry if i didnt make it clear, thats right.

**Comment by RafaelIL** [comment]
My work around now is to read with pd.read_parquet() then use dd.from_pandas.
