### ISSUE TITLE
converting dask array to numpy array taking long time

### ISSUE THREAD

**Issue by pullanagari** [dask/dask#3870]
Hi,

I tried to convert dask array into numpy array using the following command 

> x1=np.asarray(x)
but it is taking long time ..
Appreciate your help in advance.

**Comment by martindurant** [comment]
have you tried `x1 = x.compute()`? But first, are you sure that your array fits into memory?

**Comment by pullanagari** [comment]
it is also taking long time as well, I am sure array is small (20,000 row vector)

**Comment by mrocklin** [comment]
I recommend providing a minimal reproducible example

**Comment by pullanagari** [comment]
it working well with small dataset

**Comment by pullanagari** [comment]
When i try on big vector it showing the following message
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?

**Comment by jcrist** [comment]
@pullanagari without a minimal reproducible example, we have no way to help you. I recommend reading https://stackoverflow.com/help/mcve.

**Comment by mrocklin** [comment]
Unfortunately this example is too large to investigate easily.  See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If you're able to isolate your problem a bit more precisely please post here and we'll reopen.
