### ISSUE TITLE
DataFrame groupby apply gives incorrect result for cumulative functions. 

### ISSUE THREAD

**Issue by groceryheist** [dask/dask#3872]
I tried reproducing this using mock data but failed for some reason.  The data I am using is here: https://teblunthuis.cc/outgoing/dask_cumcount_bug.tsv

    import dask.dataframe as dd

    # reading the data, not initially in order
    d = dd.read_table(input_file, dtype={"anon":np.bool,
                                         "articleid":np.int32,
                                        "deleted":np.bool,
                                         "editor":np.str,
                                         "minor":np.bool,
                                         "namespace":np.int32,
                                         "revert":np.bool,
                                         "reverteds":np.str,
                                         "revid":np.int64,
                                         "sha1":np.str,
                                         "title":np.str},
                      true_values=["TRUE"],
                      false_values=["FALSE"],
                      parse_dates=["date_time"], 
                      infer_datetime_format=True
    )

    d.set_index("date_time")
    editor_groups = d.groupby(d['editor'])
    d['editor_nth_edit'] = editor_groups.cumcount()
    d.loc[d.editor=="%22Legobot%22",['editor','date_time','editor_nth_edit']].compute()

What happens: cumcount is applied to the data in the order of the data, but not in the order of the index. 
Expected: Setting the index works, probably by sorting my data. 

dask: 0.18.2
python: 3.6.6
numpy: 1.15.0
OS: debian

More generally, I'm having a pretty frustrating time finding a way to get dask dataframe to actually sort my data according to a column. An on disk sort is one of the main things I was looking for when trying dask. Is there another part of the API i should be using?

**Comment by TomAugspurger** [comment]
> What happens: cumcount is applied to the data in the order of the data, but not in the order of the index.

What's the output with dask, and how does it differ from pandas?

Note that I don't think `d.set_index('date_time")` isn't 100% equivalent to a `.set_index('date_time').sort_index()`, since dask's set_index only ensures that data are sorted between partitions, not within (https://github.com/dask/dask/issues/3376).

**Comment by TomAugspurger** [comment]
> More generally, I'm having a pretty frustrating time finding a way to get dask dataframe to actually sort my data according to a column.

See #3376 for that, but a `.map_partitions(lambda x: x.sort_index())` should result in dataframe fully sorted by the index.

**Comment by groceryheist** [comment]
I see. This issue is a case of #3376.
