### ISSUE TITLE
LocalCluster only works with processes=True

### ISSUE THREAD

**Issue by sirpy** [dask/dask#3877]
According to the manual dask distributed should start and run a localcluster by simply issuing 
c=Client()
or c = Client(LocalCluster())

This results in a crash with the following error  below for each process. when adding the argument processes=False it runs fine, but then it seems to only be using 1 cpu core even when setting n_workers, because of python no thread support maybe.
```
xception in thread AsyncProcess ForkServerProcess-8 watch message queue:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/distributed/process.py", line 36, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/distributed/process.py", line 185, in _start
    process.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 36, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 43, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by jcrist** [comment]
Thanks for the issue. I am unable to reproduce:

```
In [1]: from dask.distributed import Client

In [2]: Client()
Out[2]: <Client: scheduler='tcp://127.0.0.1:53413' processes=8 cores=8>
```

 It would be helpful to know:

- What version of dask?
- What version of distributed?
- What operating system?
- Are you creating a `Client` in a script? In IPython?

**Comment by jcrist** [comment]
The issue title says

>  LocalCluster only works with processes=True

did you mean `processes=False`?

> when adding the argument processes=False it runs fine, but then it seems to only be using 1 cpu core even when setting n_workers, because of python no thread support maybe.

With `processes=False` workers are threads instead of processes. This is fine for some workloads which release the interpreter lock (much of numpy, some of pandas), but not everything.

**Comment by neverfox** [comment]
I'm seeing the same thing. If I run python console and enter:
```
>>> from dask.distributed import Client
>>> Client()
```
It works fine and I can proceed to use Dask. However if I put those lines and the start of a py file and run it with `python myprogram.py`, I get the OP's errors.

**Comment by neverfox** [comment]
Ah you need this:
```
if __name__ == '__main__':
    from dask.distributed import Client
    Client()
```

**Comment by mrocklin** [comment]
Thanks for posting the issue and the solution @sirpy and @neverfox   .  Hopefully this helps others who come here in the future.

**Comment by seanlaw** [comment]
@neverfox This solved my problem and I never would've thought to do this. So, thank you! Can you provide an explanation as to why this is needed as it isn't obvious?

> Ah you need this:
> 
> ```
> if __name__ == '__main__':
>     from dask.distributed import Client
>     Client()
> ```

**Comment by jcrist** [comment]
See https://stackoverflow.com/a/20222706/1667287, same thing applies here. When processes are started in the absence of fork, they'll try to import the script that launched them, which will cause failures if the creation of `Client` isn't shielded in the `if` block.

**Comment by drorata** [comment]
Is it also documented somewhere on dask's side or is the snippet by @neverfox is considered a common knowledge?

**Comment by TomAugspurger** [comment]
We still get questions / reports about it, so it's not common *enough* knowledge. @jcrist looked into giving a better error message a while back, but IIRC there isn't really a good place for us to actually handle it.

**Comment by jcrist** [comment]
If you're creating a `LocalCluster` (or just calling `Client`) in a script, then yes.

**Comment by mrocklin** [comment]
Or any time you create a process in Python from a script.

**Comment by drorata** [comment]
@mrocklin so when is it *not* needed? Isn't it that every processing start (at some point) with creation?

**Comment by mrocklin** [comment]
If your Python script creates no additional processes then you don't need
it.

**Comment by drorata** [comment]
@mrocklin I'm sorry, but I don't understand. Can you give an example where "no additional processes" are used?

**Comment by TomAugspurger** [comment]
I think Matt was noting that this is a general Python problem, not just Dask. Any python program that creates processes at the top-level will have this issue.

Specifically for Dask, the processes are probably created with a  `LocalCluster` (which is implicitly created by `Client()` when `processes=True` (the default).

**Comment by drorata** [comment]
Since `dask` is such a heavy abstraction on top of so many things, I guess it is expectable that a `dask` user won't be familiar with this aspect. I'd vote for mentioning this in the docs. In the meanwhile, can you point to some related documentations?

**Comment by drorata** [comment]
Please forgive me for the somehow off-topic. If I understand it correctly, trying to use

```python
#job.py
from multiprocessing import Process

def foo():
    print('hello')

p = Process(target=foo)
p.start()
```

would yield an error because the same code will be executed independently by all "instances" on the different processes. This will lead to a conflict (whose details I don't fully understand). However, by *protecting* the process creation step:

```python
# job_protected.py
from multiprocessing import Process, freeze_support, set_start_method

def foo():
    print('hello')

if __name__ == '__main__':
    freeze_support()
    set_start_method('spawn')
    p = Process(target=foo)
    p.start()
```

Only the initial invocation of the job creates the process and the copies are not doing that anymore because they are not ran as `__main__` anymore. Is it the right understanding/intuition?

**Comment by haje01** [comment]
> I'm seeing the same thing. If I run python console and enter:
> 
> ```
> >>> from dask.distributed import Client
> >>> Client()
> ```
> 
> it works fine and I can proceed to use Dask. However if I put those lines at the start of a .py file and run it with `python myprogram.py`, I get the OP's errors.
> 
> dask complete 0.19.2, Python 3.6.6, OS X 10.13.6

I have the same issue. When I first installed Dask, It worked just fine. But few days after, it started showing the issue. Strangely, it works fine with Python console as mentioned.

My environment: macOS 10.15.1, Dask 2.9.0, Python 3.7.2

**Comment by TomAugspurger** [comment]
@haje01 have you read through https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming? I don't think there's much Dask (or any other Python program) can do about this, beyond perhaps giving a better warning.

**Comment by haje01** [comment]
@TomAugspurger I'm sorry. I did not understand what `Client()` actually doing. Without `processes=False`, it instantly spawns new process. That makes sense.

Thank you.
