### ISSUE TITLE
Feature request: DataFrame.to_csv header option to only output headers in the first chunk

### ISSUE THREAD

**Issue by rvaidya** [dask/dask#3883]
Python 3.6

I am dumping a large database table, processing it, and writing it to csv.  Since it's large, I'm using dask to handle chunking and scheduling workers.

After getting all the csv chunks, I'm concatenating them together.  However, if I specify that I want headers, every chunk will contain the header line, so I'll get a bunch of duplicates in the middle of data.

I'd like to be able to concatenate the files with only the first chunk having headers, without having to open files in text mode or loop over lines in each file.

This looks doable looking at the source, as there's a list comprehension that can instead be a for loop with special handling of kwargs.

**Comment by rvaidya** [comment]
I could take a stab at this next week - what would be your preferred way of introducing this as an option?  A new separate param, or as a fixed string value to "headers" ?

**Comment by mrocklin** [comment]
I believe that ths was implemented in #3909  Closing
