### ISSUE TITLE
da.asarray broken for Dask Series / DataFrame

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3885]
I suspect as a result of adding `.shape` / `.size` in https://github.com/dask/dask/pull/3212

Looking into a fix now. IIUC, we used to create an intermediate NumPy array here https://github.com/dask/dask/blob/master/dask/array/core.py#L3321-L3322

I don't think we want to return to that behavior.

I've just opened https://github.com/dask/dask/pull/3884. If we call that, then `asarray(dask_frame)` will work, but we need to decide what the default behavior should be: perform an intermediate computation to discover the chunk lengths, or allow the chunk lengths to be unknown?

Eagerly computing the lengths is backwards compatible (and more efficient than the old version), but somewhat at odds with the rest of dask. I'm not sure what's best here.

**Comment by mrocklin** [comment]
I think that it is best to avoid computation if possible.  I think that we should produce a dask array with unknown chunk lengths.

**Comment by TomAugspurger** [comment]
Agreed. Fixing this in #3884

**Comment by jakirkham** [comment]
Closing as it appears this was fixed. Please feel free to reopen if I've misinterpreted this.
