### ISSUE TITLE
DataFrame groupby doesn't accept method argument

### ISSUE THREAD

**Issue by groceryheist** [dask/dask#3886]
According to the [documentation](http://dask.pydata.org/en/latest/dataframe-groupby.html?highlight=set_index%20disk) I should be able to specify a method argument to `df.set_index` or `df.groupby` to indicate whether to use tasks or on-disk for the shuffle. This doesn't work for groupby. 

MWE: 

`   import dask.dataframe as dd
    import pandas as pd

    df = pd.DataFrame(dict(a=list("".join(['aabbccdd' for i in range(int(200/8))])),
                       date=pd.date_range(start='20100101', periods=200)))

    d = dd.from_pandas(df, npartitions=4)

    d.set_index(d['date'], method='disk') ## ok
    d['i'] = d.groupby('a', method='disk').cumcount() ## error
    d.loc[d['a'] == 'a', :].compute()

Error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-06d5f574e0b2> in <module>()
----> 1 d['i'] = d.groupby('a', method='disk').cumcount() ## error

~/.local/lib/python3.6/site-packages/dask/dataframe/core.py in groupby(self, by, **kwargs)
   2565     def groupby(self, by=None, **kwargs):
   2566         from dask.dataframe.groupby import DataFrameGroupBy
-> 2567         return DataFrameGroupBy(self, by=by, **kwargs)
   2568 
   2569     @wraps(categorize)

TypeError: __init__() got an unexpected keyword argument 'method'

This is with dask 18.2 and python 3.6.6 on linux. 

Thanks!

**Comment by jrbourbeau** [comment]
Thanks for the MWE @groceryheist! 

A couple of points related to your issue:

1. After a little digging, it looks like the `method=` keyword was replaced in favor of the `shuffle=` keyword in #1404. For example, see the `DataFrame.set_index` API documentation http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.set_index. 

2. From what I can tell `DataFrame.groupby` doesn't accept a `shuffle` keyword argument. Although `'disk'`- vs. `'tasks'`-based shuffling can be configured using `dask.config.set`. E.g. 

```python
with dask.config.set(shuffle='tasks'):
    ddf.groupby(columns_no_index).apply(user_fn)
```

I'm not super familiar with this portion of the codebase, perhaps @mrocklin can comment
