### ISSUE TITLE
dd.read_parquet with pyarrow engine fails on GCS

### ISSUE THREAD

**Issue by lihan** [dask/dask#3887]
I hit error when trying to `read_parquet` files from Google Cloud Storage, specifically this NotImplemented error https://github.com/dask/dask/blob/master/dask/bytes/core.py#L516

While it is able to save file to GCS as parquet format using pyarrow, anything I am missing here?

Also see https://github.com/dask/dask-kubernetes/issues/80, others seem be able to do this.

**Comment by martindurant** [comment]
Can you debug to find out the original error? It may be the same as https://github.com/dask/dask/issues/3882 , in which case updating gcsfs to master would solve it. I can also do a release of gcsfs .

**Comment by mrocklin** [comment]
Also reported in https://github.com/dask/dask/issues/4009 which has gone a bit further.  Closing in favor of that issue.
