### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3891]
There were a few important fixes in dask/distributed recently.  I'm inclined to do a release there.  I was thinking I would also release dask/dask.  Any objections or known blockers?

**Comment by mrocklin** [comment]
I would aim for later this week

**Comment by TomAugspurger** [comment]
+1

**Comment by jakirkham** [comment]
Releasing sounds good.

**Comment by jakirkham** [comment]
This can be closed, right?
