### ISSUE TITLE
Parallelism of dataframe.read_parquet() across multiple files?

### ISSUE THREAD

**Issue by CharlesHe16** [dask/dask#3892]
_It's unclear if this belongs in Stackoverflow. However, this is an explicit suggestion related to dask features. Please advise if it I should go to SO in the future._

It seems that `dask.dataframe.read_parquet(path)` doesn't take advantage of parallelism when `path` is a list of files. Instead, it uses one thread to read the files one at a time, the read speed is O(N) in files, etc. Note that there does not appear to be sorting of the final dataframe. 

My CPU and disk is underutilized. 

- Is my understanding above correct?
- If so, as part of a bigger project, I believe I can write a trivial joblib script to parallelize this, assuming the final dataframe fits in memory.

**EDIT for clarity:** To help clarify: The parquet files involved in the issue exist quite distinctly, in arbitrarily different directories. They were produced by seperate `dask.dataframe.to_parquet` or `fastparquet.write()` commands. Dask has no awareness that the files are connected, because in a sense, they aren't. 

Seperately, I understand that dask takes advantage of parquet's partitions/row groups. I'm additionally taking advantage of this other partitioning and preserving it as a distinct arm of multiple indexing strategy.

**Comment by martindurant** [comment]
You are correct that the scanning of metadata across the files happens in the client, and is not parallelised. Ideally, the metadata reading and parsing should be much faster than the actual data access - you may want to try with a larger number of rows per file/row-group.

**Comment by mrocklin** [comment]
I feel like we've run into this situation before, where scanning metadata
on many many files is expensive.  While the suggestion to increase the
number of rows per metadata entry is a nice one, I suspect that many users
won't be able to rewrite all of their data to suit reading performance.

Is this something that we can improve in the future somehow?  Are there any
options that we can implement easily that might help users in this
situation?  For example are there ways to consolidate or ignore most
metadata?

**Comment by martindurant** [comment]
From fastparquet's point of view, it is certainly possible to load each parquet file separately, and do the metadata scan in tasks instead of the client. That is not how it is designed now, however, because of max/min/divisions, or directory-based partitioning, which need to be known globally. The latter does not need a scan as such, but the former does.

For arrow, I would have to read to see how things are implemented.

**Comment by CharlesHe16** [comment]
> You are correct that the scanning of metadata across the files happens in the client, and is not parallelised. Ideally, the metadata reading and parsing should be much faster than the actual data access - you may want to try with a larger number of rows per file/row-group.

This is interesting! 

However, I've personally lost the thread of this discussion. I think this might be because my original post wasn't clear.

To help clarify: The parquet files involved in the issue exist quite distinctly, in arbitrarily different directories. They were produced by seperate `to_parquet` or `write` (from past_parquet) . Dask has no awareness that the files are connected, because in a sense, they aren't. Despite this, the dataframes' format are homogenous and can be readily concatenated. 

While this seems contrived, you can imagine this to exist in the wild (log files for example).

Now, @martindurant and @mrocklin, your responses seem to be assuming some existing feature of dask, when in fact I'm describing completely different functionality. I'm describing a 'super' or higher layer of joining the dataframes. In some sense, this is far less sophisticated and easier than the metadata and abstraction you are discussing.

Is there any reason I shouldn't trivially parallelize of read_parquet, using multiple processes to ingest/decompress/parse independent dataframes and concatenate them?

**Comment by martindurant** [comment]
@CharlesHe16 ,
the reading of parquet data is parallel. As with most things, you will not get a speed-up equal to the number of CPU cores because of bottlenecks such as the your disc bus (or network), overhead, memory pressure, etc.. If you think you are not seeing this, then we would appreciate seeing more details of what you are doing.

**Comment by CharlesHe16** [comment]
Given who I'm talking to in this thread, I'm quite sure I was wrong. So I was surprised by these results! 

Using dask to load multiple parquet files in `path`: 
```
1 loop, best of 3: 38.6 s per loop
```
Trivial joblib implementation: 
```
1 loop, best of 3: 10.5 s per loop
```

So what I think is driving these results, and what I failed to mention, is that I'm using `.query()` to cut the dataframes. See code below. 

A reasonable guess is that dask is pulling all the data into memory and then concatenating, instead of merely taking the smaller data specified by `query`. This really hurts because concatenation is serial and eats up most wall time.

As described in the notes below, because dask appeared to run as one CPU process, I may have conflated this with a lack of parallelization.

@martindurant: Can you confirm the above is what going on? 

Is there something I've missed, and I'm using dask incorrectly, so that this is all driven by some pathological use case?

<details><summary> Code to produce above times:</summary>
<p>

```python
import pandas as pd
import dask.dataframe as dd

from joblib import Parallel, delayed
from pathlib import Path

files = list(Path('PATH TO FILES').glob('*'))
query = "column== 'group_of_interest'"

def _get_df_file(file, query):
    df = dd.read_parquet(file).query(query).compute()
return df

# 1 loop, best of 3: 38.6 s per loop
%timeit joblib_df = pd.concat(Parallel(n_jobs=6)(delayed(_get_df_file)(file, query) for file in files))

# 1 loop, best of 3: 10.5 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute()
```
</p>
</details>
<br>

<details><summary> Notes and misc:</summary>
<p>

- Just in case, I've done these tests with a cold booted system, and without `timeit`. This was to avoid caching and to try to confirm nothing weird is happening under the hood. The results appear robust.
- Note that the joblib code is crude and probably can run faster. For example, you can imagine using callbacks to get intermediate results and begining concatenation in mid computation. 
- As mentioned before, I'm not using `filter`, because these use the row-group/partitions in dask. 
- Interestingly, when using dask, CPU and IO use was about the level of one process, far below maximum utiliization. Yet, despite not appearing to parallelize, _dask is still performing better than my joblib_ when not using `query`, as shown below. I don't understand this.

As you would expect, without `query()`, dask is no longer slower at all:


```python
import pandas as pd
import dask.dataframe as dd

from joblib import Parallel, delayed
from pathlib import Path

files = list(Path('PATH TO FILES').glob('*'))

def _get_df_file(file, query):
    df = dd.read_parquet(file).compute()
return df

# 1 loop, best of 3: 43.7 s per loop
%timeit joblib_df = pd.concat(Parallel(n_jobs=6)(delayed(_get_df_file)(file) for file in files))

# 1 loop, best of 3: 47.2 s per loop
%timeit dask_df = dd.read_parquet(files).compute()
```
</p>
</details>
<br>

**Comment by martindurant** [comment]
```
# 1 loop, best of 3: 38.6 s per loop
%timeit joblib_df = pd.concat(Parallel(n_jobs=6)(delayed(_get_df_file)(file, query) for file in files))

# 1 loop, best of 3: 10.5 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute()
```

Were these times the wrong way around?

**Comment by CharlesHe16** [comment]
@martindurant Yes. Fixed now. 

The times in the "notes" example were transposed as well (dask is slightly faster than my joblib without `query()`).

**Comment by martindurant** [comment]
Can you try with the different [schedulers](http://dask.pydata.org/en/latest/scheduler-overview.html) ? The distributed one, in particular, gives ready diagnostic information on the dashboard. 

You didn't say which engine you were using to read the data, but I am assuming fastparquet. The library does make some effort to release the GIL, but many expensive operations are pure-python (e.g., text decoding), so you may find that processes work better than threads.

**Comment by CharlesHe16** [comment]
Yes, I am using `fastparquet`.

As you have suggested, I've rerun the tests with distributed and processes. 

Using processes and workers, the script overcomes the GIL. Now, (with the usual overhead) IO and CPU is fully utilized. However, while performance increases, it remains well below the simple `joblib` implementation described above. 

<details><summary>More Benchmarks:</summary>
<p>

```python
import pandas as pd
import dask.dataframe as dd

from joblib import Parallel, delayed
from pathlib import Path

files = list(Path(PATH_TO_FILES).glob('*'))
query = "group == 'group_of_interest'"

def _get_df_file(file, query):
    df = dd.read_parquet(file).query(query).compute()
    return df

# 1 loop, best of 3: 9.09 s per loop
%timeit joblib_df = pd.concat(Parallel(n_jobs=6)(delayed(_get_df_file)(file, query) for file in files))

# 1 loop, best of 3: 34.9 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute()

# 1 loop, best of 3: 22.9 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute(scheduler='processes')

# 1 loop, best of 3: 22.1 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute(scheduler='processes',  num_workers=6)
```
(Possibly unneccessarily) in a completely separate Python instance, to avoid issues of multiple schedulers:
```python
from dask.distributed import Client, LocalCluster
import dask.dataframe as dd
from pathlib import Path

files = list(Path(PATH_TO_FILES).glob('*'))
query = "group == 'group_of_interest'"

cluster = LocalCluster(n_workers = 6)
client = Client(cluster)

# 1 loop, best of 3: 17.6 s per loop
%timeit dask_df = dd.read_parquet(files).query(query).compute()
```
</p>
</details>
<br>

Now, let's take a step back now for perspective. Personally, my questions motivating this issue are resolved and a simple joblib implementation meets my needs.

Separate to this, there are two distinct topics:
- Low level performance issues involving multiple layers of packages/GIL/processing/threading and Amdahl's law, as suggested by a close reading of the benchmarks.
- My theory that dask is not taking advantage of the `query()` optimization, as described above.

These are fairly interesting to me, but whether it would be interesting and productive to you is beyond my expertise. If you are interested, please let me know how I can be helpful with either or both. 

In particular, if you have an exemplar issue or tutorial of others getting the relevant logs from your dashboard (which is fantastic BTW), I would be happy to follow it and obtain this information for you.

**Comment by martindurant** [comment]
Yeah, I suppose the strictly fair comparison would be with a `dask.delayed()` function that does both loading and query in a single task, rather than chaining tasks as you now do.

**Comment by tropicalpb** [comment]
I am also facing this problem.  I have a few hundred parquet files of the same schema in a Hadoop HDFS directory that I am using dask read_parquet('.../*.parquet'..) to load into a data frame.  The system has 64 cpus but at any given time cpu/disks/network are mostly idle.  It seems like the loading is quite serial.  Is there anyway to speed this up?

**Comment by martindurant** [comment]
@tropicalpb , loading parquet locally with workers in processes or threads, I see good parallelism. Again, you would be best looking at your scheduler dashboard to figure out what time is being spent on.
