### ISSUE TITLE
da.linalg.norm errors for ndims>2 & axis=something

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#3895]
Using `numpy.linalg.norm`, if I have a nD array of vectors X, I can calculate the nD array of norms of these vectors using the `axis` kwarg in the following way:

```
import numpy as np

X = np.random.random(5,5,2)
Xnorms = np.linalg.norm(X, axis=-1)
```

One would expect this to work with `da.linalg.norm` as well, but this throws an error:
```
import dask.array as da

X = da.random.random(5,5,2, chunks=(1,1,2))
Xnorms = da.linalg.norm(X, axis=-1)
```

However:

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\array\linalg.py", line 1085, in norm
    #    raise ValueError("Improper number of dimensions to norm.")
ValueError: Improper number of dimensions to norm.
```

I disagree with this error message for this case. In fact, when removing the raising of this error, everything computes fine.
I think the solution is editing the requirements in the following lines:

https://github.com/dask/dask/blob/6a9fc9a342d62c102d8cfc9607ebab2c25f45781/dask/array/linalg.py#L1082-L1092
Where we should check `x.ndims <= 2` only if `axis=None` and for completeness if axis is a tuple check if it is not more than a 2-tuple (see also the relevant [numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html) ).

Or are there any hurdles I am not aware of? Otherwise I will just implement this.

**Comment by mrocklin** [comment]
My first guess is that that code was copied verbatim from Numpy at a time
when Numpy didn't support norm of greater than 2.  I'm not sure though.  I
suspect that @jakirkham would know more.

**Comment by TAdeJong** [comment]
The axis argument was introduced in version 1.8.0. of numpy, from 2013 or so, so that would be a bit surprising. Equivalent code is (here)[https://github.com/numpy/numpy/blob/18f2385b29bdd62701a1a82d7bf33fd87430a05e/numpy/linalg/linalg.py#L2357-L2382] btw.

**Comment by mrocklin** [comment]
In that case I suggest that we wait to see if @jakirkham has thoughts.  I
suspect that he has a good answer here.

**Comment by jakirkham** [comment]
Hmm...it's pretty hard to remember why I wrote some code a particular way a year ago. Sorry to not be more insightful.

My guess is that I didn't have a good use case to drive adding such functionality or test it. So left it out figuring if it was important someone (like yourself) would show up looking for it and we could discuss such improvements.

Expect that if we generalize the function to N-D a few checks within the function will need to be updated as they seem to assume the array is either 1-D or 2-D, but don't consider catching cases that are higher dimensionality. Would expect this is straightforward to do, but there is a bit of bookkeeping. Testing some N-D arrays with all norms should help flush these issues out.

**Comment by TAdeJong** [comment]
To be precise and avoid confusion @jakirkham: I am not talking about extending the norm to more than 2D ( I am not even sure if this is a thing mathematically), but to be able to use the axis argument to take the norm of 1D or 2D slices of an nD array, as is implemented by numpy.

**Comment by jakirkham** [comment]
Right, that's what I meant as well. Sorry to be imprecise.

**Comment by TAdeJong** [comment]
I am working on a pull request for this. Most of it is straight forward, except for the SVD-based norms on slices of ND arrays. I see that `np.linalg` itself only supports operating on the last two dimensions of ND-arrays for the svd here: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html#linear-algebra-on-several-matrices-at-once, although `np.linalg.norm` handles this somehow.
This means we can either create some application of map_blocks/apply_along_axes on the existing `da.linalg.svr` (or the underlying `da.linalg.tsqr`) in this case for norm, or extend one of these to operate on the last 2 dimensions of an N-D array, or to take an axis argument, respectively replicating or superseding the stacked linalg computation functionality of numpy.
I guess matching `numpy` functionality and operate on the last two dimensions would be the best, as introducing a full axis argument for svd/tsqr would just hide away an underlying transpose.

Any thoughts on this?

P.S. Working on both thus and some applications I notice there is only an `da.apply_along_axis`, and no `da.apply_along_axes` for mapping operations on general subdimensions, requiring instead to write some wrapper function to put in a `map_blocks` in order to handle extra non-one dimensions of blocks. Maybe this would be a nice extension/generalization of the API, or am I missing a function for this?

**Comment by TAdeJong** [comment]
Closing this as it is resolved for most cases, the left over `NotImplementedError` cases for SVD-based norms are discussed in the new issue #3962 .
