### ISSUE TITLE
problem with dask concat using dataframes of unequal size

### ISSUE THREAD

**Issue by kostasmarkakis** [dask/dask#3898]
Hi,
I am experiencing a strange behavior when performing a concatenation of two dask dataframes (lazy objects) that have different number of columns/rows. The dataframes are read from hdf5 files using:

df1 = dd.read_hdf( f1, 'hf', mode='r' )

the final concat is: 

concat_df = dask.concat( list_of_data_frames_list, axis=0 )

The operation completes but a subsequent persist or compute of the concatenated dataframe causes Python to exit with:

Process finished with exit code -1073741819 (0xC0000005)

if i do the same thing using two identical dataframes, concat works fine. it also works fine if the dataframes are read from csv files and not hdf5!.

i am using Python 3.6.6, Pandas 0.23.3 and dask 0.18.2

any thoughts?

**Comment by TomAugspurger** [comment]
Are you able to reproduce the issue using just pandas? (probably not if HDF5 is involved)

Do you have a reproducible example to share?

**Comment by kostasmarkakis** [comment]
I need to create a sample of the files to share because the ones that i am working on are quite large.

In the meantime i did as you suggest (read and concat with pandas) and it works just fine. hdf5 or no.

I also did something else: i read the files with pandas, did the concat with pandas and then transformed the concat dataframe from pandas to dask dataframe. it does not work either!

i will get back to you soon with some sample files and test script

**Comment by mrocklin** [comment]
Any update on this?  Closing soon otherwise.

**Comment by jrbourbeau** [comment]
Closing. @kostasmarkakis feel free to re-open this issue if you're able to construct a reproducible example https://blog.dask.org/2018/02/28/minimal-bug-reports
