### ISSUE TITLE
Problem when working with loc using Dask

### ISSUE THREAD

**Issue by GHSADAF** [dask/dask#3904]
I have a large csv file. I wanted to load this csv file via Dask. I could load it successfully and confirmed some row of the dataset to make sure the dataset has been loaded correctly. I was supposed to select one column of dataset (last column ) with "loc" but I couldn't do so because of the error below. '131094' is the name of last column. How is it possible to do label based indexing for a data-frame with Dask?

import dask.dataframe as dd
df = dd.read_csv('filename.csv', header=None)
y = df.loc[:, [131094]] 

File "/usr/local/dask-2018-08-22/lib/python2.7/site-packages/dask-0.5.0-py2.7.egg/dask/dataframe/core.py", line 180, in _loc "Can not use loc on DataFrame without known divisions") ValueError: Can not use loc on DataFrame without known divisions

**Comment by martindurant** [comment]
Duplicate: https://stackoverflow.com/questions/52022211/how-to-use-loc-for-column-selection-of-a-dataframe-in-dask
Recommend close.
