### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'Timestamp' and 'datetime.date'

### ISSUE THREAD

**Issue by eromoe** [dask/dask#3905]
Hello,

I want to switch my code from pandas to dask. 
After replacing `import pandas as pd` of  `import dask.dataframe as pd`  , I got error 
```
Traceback (most recent call last):
  File "read_hdfs_train_predict.py", line 234, in train_predict_sale_count
    if (daily_orderitems.index[-1] - df_userstat.index[0]).days < 30:
TypeError: unsupported operand type(s) for -: 'Timestamp' and 'datetime.date'

```

pandas support this , so I think `dask.dataframe` sync with it.

**Comment by martindurant** [comment]
Please be more specific and provide some code which produces the problem you are describing.

**Comment by eromoe** [comment]
daily_orderitems.index[-1]  is `Timestamp` and  `df_userstat.index[0]` is `datetime.date`. 
`dask.dataframe` doesn't support compare these.

**Comment by mrocklin** [comment]
Closed due to lack of response.
