### ISSUE TITLE
Inversing a Dask Array (matrix) is complex

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3910]
Taking an inverse of Dask Array (matrix) generates a quite complex Dask graph even for small Dask Arrays. Wondering if it is possible to make this simpler by using a different algorithm. 

<details>
<summary>Example:</summary>

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: a = 2 * np.random.random((9, 9)) - 1

In [4]: d_a = da.from_array(a, chunks=3)

In [5]: d_a_inv = da.linalg.inv(d_a)

In [6]: d_a_inv.visualize()
Out[6]: <IPython.core.display.Image object>
```

</details>

<br>

<details>
<summary>Graph:</summary>

![mydask](https://user-images.githubusercontent.com/3019665/44686927-c4f58b80-aa1d-11e8-9266-dba566608399.png)

</details>

**Comment by mrocklin** [comment]
Note that inverting an array is almost never a good idea.  Are you
confident that this is an operation that you want?  Usually one uses the
solve operation.

**Comment by jakirkham** [comment]
Was looking at some algorithms that might be interesting to use that would involve inversing a rather larger matrix. Certainly after looking at this graph am a bit skeptical that pursuing them would be worthwhile without a better story here.

**Comment by mrocklin** [comment]
It's very rare for people to explicitly invert a matrix.  It's usually far
more efficient and stable to do a matrix solve.  This almost always
suffices.  You might want to see if calling solve would resolve your
problem as well.

**Comment by jakirkham** [comment]
Unfortunately the inverse was needed in the cases I was looking at. So I think alternatives in this case would be using a different algorithm.

**Comment by mrocklin** [comment]
I'm *very *surprised to learn that it was needed.  In every case where I've
heard someone say "I really need the inverse" it was actually possible (and
far more efficient) to use solve in some clever way.  You probably know
this stuff pretty well though, so I'll leave it to you.

That being said, if you can find a better algorithm for inv for dask array
that would be great.

**Comment by jakirkham** [comment]
To be clear, by different algorithm in the last comment, was meaning selecting a different machine learning algorithm that doesn't require an inverse. This will require more research.

**Comment by rainwoodman** [comment]
Perhaps the algorithm needs running inversion of the same matrix many many times, making an iterative solver unfavorable. I agree it feels rare. @jakirkham Is there a public reference to the algorithm?

**Comment by mrocklin** [comment]
I'm going to go ahead and close.  If someone can propose a simpler method to compute the inverse and has an interest in implementing that method then they can comment here and we'll reopen or they can raise a new issue.
