### ISSUE TITLE
Merging frames results in empty frame (due to empty partitions)

### ISSUE THREAD

**Issue by sadams** [dask/dask#3911]
I have an issue with merging two dataframes where there are multiple partitions:
```python
import dask.dataframe as dd

import pandas as pd

idx = 'thekey'

def generate_data(n_rows):
    return {
        'thekey': ['001'] * n_rows,
        'somedata': ['2018-01-01'] * n_rows,
    }

def ddf_from_dict(table):
    return dd.from_pandas(pd.DataFrame(table), npartitions=2)

def do_merge(fr1, fr2):
    fr1 = fr1.set_index(idx)
    fr2 = fr2.set_index(idx)
    return fr1.merge(fr2, how='left', left_index=True, right_index=True)

def compare(rows):
    frame1 = ddf_from_dict(generate_data(rows))
    frame2 = ddf_from_dict(generate_data(1))

    merge_using_dask = do_merge(frame1.copy(), frame2.copy()).compute()
    merge_using_pandas = do_merge(frame1.copy().compute(), frame2.copy().compute())
    print(f'''
Row counts (expecting {rows}):
dask: {len(merge_using_dask)} vs pandas: {len(merge_using_pandas)}
____________''')

compare(2)
compare(3)
compare(4)
compare(5)
```
output of above: 
```
Row counts (expecting 2):
dask: 2 vs pandas: 2
____________
Row counts (expecting 3):
dask: 3 vs pandas: 3
____________
Row counts (expecting 4):
dask: 0 vs pandas: 4
____________
Row counts (expecting 5):
dask: 0 vs pandas: 5
____________
```

By changing the number of partitions or adding more data (so that it spans all the partitions) the results change, so it looks like it's down to having empty partitions. E.g. when we change `npartitions` in the above example to `3` then `compare(3)` also results in an empty result.

Versions: 
```
dask = 0.18.2
pandas = 0.23.4
python = 3.6.5
```
Although the above is a contrived example, the concern is that (in a production environment) if we filter a large dataset it will result in empty partitions which will then not merge correctly. I.e. at scale this sort of problem could be happening without us knowing.

**Comment by mrocklin** [comment]
Thank you for the excellent bug report @sadams .  This definitely seems like a genuine issue.  

For other maintainers, I've reduced it to the following:

```python
import dask.dataframe as dd

import pandas as pd


df1 = pd.DataFrame({'x': [0, 0, 0, 0]})
df2 = pd.DataFrame({'x': [0]})

ddf1 = dd.from_pandas(df1, npartitions=2)
ddf2 = dd.from_pandas(df2, npartitions=1)
ddf1.set_index('x').merge(ddf2.set_index('x'), how='left', left_index=True, right_index=True).compute()
df1.set_index('x').merge(df2.set_index('x'), how='left', left_index=True, right_index=True)
```

I was unable to remote the `set_index` operations, and get the same erroneous result.  I was unable to get the same erroneous result by going under four elements.

**Comment by mrocklin** [comment]
The next thing to do here is probably to walk through the task graph and figure out where things are going wrong.  @sadams if you have the apetite for this your help would be welcome.

**Comment by KiranVaranas** [comment]
@mrocklin 
We too are facing similar issue where post join incorrect results are displayed. Please do let us know your findings.

**Comment by mrocklin** [comment]
@KiranVaranas you are also able to investigate this issue directly.  Any help would be welcome.
