### ISSUE TITLE
Worker exceeded 95% memory budget

### ISSUE THREAD

**Issue by tropicalpb** [dask/dask#3914]
I am trying to read a few hundred compressed parquet files into dask dataframe.  The system has 64 CPU and 256 GB memory.  I am allocating only 12 workers so there should be plenty of memory.  I can use dask non-distributed read_parquet('*.parquet'), it takes a while, use upwards about 30G of memory, but can execute fine.

However, when I use the dask distributed

cluster = LocalCluster(n_workers=12, threads_per_worker=1)
client = Client(cluster)
...
df = dd.read_parquet('*.parquet')
df = client.persist(df)
...(compute)

it constantly fail with 'Worker exceeded 95% memory budget'.  Any ideas?

**Comment by TomAugspurger** [comment]
Have you looked at the distributed diagnostics page while the computation is occurring? https://distributed.readthedocs.io/en/latest/web.html What's that show?

**Comment by kumarspark** [comment]
@tropicalpb How did you fix this? I am having a similar issue trying to read a 65 mb parquet file on a 16 gb ram ubuntu with 4 workers (4 gb ram each)

**Comment by pavithraes** [comment]
@kumarspark Perhaps something in https://docs.dask.org/en/stable/dataframe-parquet.html might be helpful for you? I'd also encourage you to post this question on [Discourse](https://dask.discourse.group/) with the complete error traceback. :)
