### ISSUE TITLE
Link to dask-examples repository

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3921]
See https://github.com/dask/dask-ml/blob/56714b4a8749d0b0d1948de443bcce43dc60354e/docs/source/conf.py#L203-L226

**Comment by TomAugspurger** [comment]
For reference, https://dask.github.io/dask-ml/examples.html, each of those links to a rendered version of the notebook (built with nbsphinx when the docs are built)

I'd like to make it so the TOC includes a "try on binder" link next to the notebook title.

**Comment by TomAugspurger** [comment]
I briefly played with writing a sphinx extension to take a toctree like

```
.. toctree:

   examples/foo :binder:
```

and  turn it into something like

```
..toctree:

   xgboost .. image:: https://mybinder.org/badge.svg :target: https://mybinder.org/v2/gh/dask/dask-examples/master?filepath=%2Fmachine-learning%2Fxgboost.ipynb
```

to render like

- xgboost [![](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/dask/dask-examples/master?filepath=%2Fmachine-learning%2Fxgboost.ipynb)

I didn't get very far though. It seems like sphinx doesn't recursively parse markup in the toctree.

**Comment by mrocklin** [comment]
It seems like we're also heading to a point where we get better at
integrating many different doc pages into one cohesive system.  Maybe we
wait on that and manage examples separately within the dask-examples repo
itself.

**Comment by jrbourbeau** [comment]
FWIW an alternative approach to including a binder badge in the toctree would be to specify a `nbsphinx_prolog` in `conf.py` (ref https://nbsphinx.readthedocs.io/en/0.3.5/prolog-and-epilog.html) that adds a binder badge to the top of each rendered notebook 

Example usage: https://jrbourbeau.github.io/pyunfold/notebooks/tutorial.html

**Comment by mrocklin** [comment]
Ooh, nice.

**Comment by jakirkham** [comment]
My understand was Sphinx-Gallery was trying to solve this too.

**Comment by mrocklin** [comment]
examples.dask.org is now integrated into docs.  Closing.  Thanks all
