### ISSUE TITLE
Stacking list of arg reduction's produces duplicates of last list element

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#3940]
This is weird. As I do often, I create a list of _n_ dask.arrays in a for-loop for a number of cases, and stack this together to one big dask array. However, if I stack together `da.argmin` operations, the array contains _n_ copies of the last argmin in the list. This does not happen for regular `da.min` or `da.sum`, but is does happen for `da.argmax`, so I suspect a issue in the general arg_reduction.

A reproduction example:

```python
import dask.array as da
import numpy as np
import matplotlib.pyplot as plt

Data = da.random.random((3,3,20,3), chunks=(3,1,-1,1))
minima = []
argminima = []
for index in range(Data.shape[-1]):
    minima.append(da.min(Data[...,index], axis=2))
    argminima.append(da.argmin(Data[...,index], axis=2))
    
fig,ax = plt.subplots(Data.shape[-1], 4, figsize=[9,6])
for index in range(Data.shape[-1]):
    ax[index,0].imshow(minima[index].compute())
    ax[index,1].imshow(argminima[index].compute())
minimb = da.stack(minima)
argminimb = da.stack(argminima)
for index in range(Data.shape[-1]):
    ax[index,2].imshow(minimb[index,:,:].compute())
    ax[index,3].imshow(argminimb[index,:,:].compute())
for i, text in enumerate(["min_before", "argmin_before", "min_after", "argmin_after"]):
    ax[0,i].set_title(text)
plt.show()
```
![image](https://user-images.githubusercontent.com/6816964/45033289-5c796080-b054-11e8-8362-53b6fa583cda.png)

Note how for `da.min` the data before and after stacking is the same, but different for each iteration, while for `da.argmin` after stacking all slices are the same.

**Comment by TAdeJong** [comment]
Okay, one step further in debugging this: all the argminima elements have exactly the same `name` attribute.

**Comment by mrocklin** [comment]
> Okay, one step further in debugging this: all the argminima elements have exactly the same name attribute, while the minima have different tokens.

That's definitely an issue.  It looks like the problem is here:

https://github.com/dask/dask/blob/09100d02ad8f2b23da70234707888b1374dd46bd/dask/array/reductions.py#L590-L617

Note that when we form the name we only include `chunk` and `axis`, but we should really be including all of the input parameters to make sure that if we change any of them (like the input array) that the output array's names will differ.

Are you comfortable making this change @TAdeJong ?
