### ISSUE TITLE
from_array performance when no name is provided

### ISSUE THREAD

**Issue by hmaarrfk** [dask/dask#3946]
The performance of `from_array` seems to be seriously affected when no `name` is provided.

I understand that in the documentation you mention that setting `name` to false is `(fast)`, ~~but I think the default should be changed to `False`.~~ Edit: I think perhaps a more stark warning should be provided and the information that @martindurant can be linked in the comment.

For example, the `asarray` function doesn't even provide a `name` argument. this means that using asarray is guaranteed to be slow. `da.asarray` is used in at least a few places like `empty_like` which make that function take for ever....

I have a feeling the whole array module will feel different with that default changed

```
from dask import array as da
import numpy as np
import dask
print(dask.__version__)
print(np.__version__)
# For python to load up dask array for fair benchmarks
_ = da.asarray(np.zeros(2))
shape = (50, 1024, 1024)

# This takes Wall time 170 ms
%time a = np.ones(shape=shape)
# This takes wall time 500 ms!!
%time _ = da.asarray(a) 
# This takes wall time 400 us, that is more like it!
%time _ = da.from_array(a, chunks=-1, name=False)
# This takes 500 ms !!!
%time b = da.from_array(a, chunks=-1)

# This takes 500ms!!
%time da.empty_like(a)
# This takes 100 us! much more like it
%time da.empty_like(b)
```

**Comment by hmaarrfk** [comment]
I get it.

This was definitely done intentionally.

Maybe a separate bug for the use of asarray in the *like functions is
appropriate. Really only the metadata needs to be extracted.

Finally, maybe the introduction of a name parameter to asarray would help
overcome the immediate issues for those transitioning from numpy arrays.

**Comment by martindurant** [comment]
It is worth pointing out that for arrays, the default hash uses python's standard sha1, but if you happen to have cityhash, xxhash or murmurhash installed (all available with pip), then you can get a large-factor speedup in the tokenisation step. You may consider that a separate point, but perhaps it is useful.

**Comment by mrocklin** [comment]
Adding a name parameter makes sense.

**Comment by hmaarrfk** [comment]
I guess that will start to depart from the numpy API.

Seem like you could:
1. Add a `name` parameter to asarray
2. Make `asarray` call `from_array` with `name=False`

I'm not sure if that will invoke the same loss in hashing for the algorithms you mentioned.

**Comment by hmaarrfk** [comment]
@mrocklin I could add a PR to add a `name` parameter to `asarray`.

How would this affect the performance of `*_like` when calling `asarray` with the parameter `name=False` for the use cases you mentioned?

**Comment by hmaarrfk** [comment]
So the added parameter should have to be added to the functions `*_like` as well?

**Comment by mrocklin** [comment]
I have no objection to that

**Comment by jakirkham** [comment]
FYI the `*_like` functions don't actually generate any arrays until computation occurs. So hashing for them proceeds through a different path. Doubt that adding a `name` parameter is needed in that case.

**Comment by mrocklin** [comment]
Ah, good point

**Comment by mrocklin** [comment]
It looks like using name=False there would be safe

**Comment by hmaarrfk** [comment]
the only thing I can think of is:

```
import dask.array as da
a = [[1, 2], [3, 4]]
da.empty_like(a)
```

doesn't have the array interface. 

we would need a function that is like:

```
def get_size_and_dtype(a):
    check if it has the array protocol,
    da.from_array(a, name=False)
```

**Comment by mrocklin** [comment]
Thanks for noticing the performance hit here.  It's really nice to have
someone invested in single-machine single-process performance for dask
array.
