### ISSUE TITLE
Computing one key of a dask graph result in computing all keys

### ISSUE THREAD

**Issue by fspot** [dask/dask#3952]
This example : 

```python
import dask

def a():
    print("=> func a called")
    return 1

def b():
    print("=> func b called")
    return 2

dsk = {
    "a": (a,),
    "b": (b,),
}

res = dask.get(dsk, "a")
print("Result:", res)
```

used to give this output with dask 0.18.2 : 

```
=> func a called
Result: 1
```

but now it gives this output with dask 0.19 : 
```
=> func a called
=> func b called
Result: 1
```

where the call of func `b` is unexpected.

This example has been tested on : 
- ubuntu 16.04 with python 3.6.2
- mac os x 10.13.1 with python 3.6.5 and python 3.7.0

**Comment by mrocklin** [comment]
You probably want to use dask.optimization.cull

**Comment by jcrist** [comment]
We used to cull automatically in the local schedulers, but not in the distributed scheduler. Since all dask collections apply cull automatically, we settled on never culling in the schedulers in #3856. Apologies for the backwards incompatible change here, your code should be fixed with culling manually:

```
>>> from dask.optimization import cull
>>> dask.get(cull(dsk, 'a')[0], 'a')
=> func a called
```

**Comment by jakirkham** [comment]
Anything else to discuss here or is this good to close?

**Comment by fspot** [comment]
I'm a bit worried that this behaviour is quite counterintuitive, in my very simple scenario it seems strange to have to "optimise" something in order to avoid to call all the functions :/. Anyway, I will call cull manually, thanks for the tip !
