### ISSUE TITLE
Loading data from Oracle

### ISSUE THREAD

**Issue by ansin218** [dask/dask#3953]
I have been trying load data from Oracle like this:

```
import dask.dataframe as ddf

host = 'host_name'
port = 1521
service_name = 'service'
username = 'username'
password = 'password'

conn = 'oracle+cx_oracle://'+username+':'+password+'@'+host+':'+str(port)+'/?service_name='+service_name
df_dusk = ddf.read_sql_table(table = 'TABLE_NAME', uri = conn, index_col = 'INDEX_COL')
```
However, I always get a key error on the relevant index column. Here is the traceback: 

> Traceback (most recent call last):
> 
>   File "<ipython-input-17-b121367edcaa>", line 1, in <module>
>     runfile('C:/Users/ankurs/Documents/playground/dask-test.py', wdir='C:/Users/ankurs/Documents/playground')
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/ankurs/Documents/playground/dask-test.py", line 17, in <module>
>     df_dusk = ddf.read_sql_table(table = 'TABLE_NAME', uri = conn, index_col = 'INDEX_COL')
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\io\sql.py", line 90, in read_sql_table
>     index = (table.columns[index_col] if isinstance(index_col, string_types)
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\sqlalchemy\util\_collections.py", line 194, in __getitem__
>     return self._data[key]
> 
> KeyError: 'INDEX_COL'
> 

I have been struggling to get the data from quite some time now. Can anyone tell me what I am doing wrong?

**Comment by mrocklin** [comment]
Can you verify that this works with `pandas.read_sql_table`?

**Comment by ansin218** [comment]
Strangely enough, when I try to do the same using Pandas, it says that the table itself does not exist. The table clearly exists in the database. 

> Traceback (most recent call last):
> 
>   File "<ipython-input-20-b121367edcaa>", line 1, in <module>
>     runfile('C:/Users/ankurs/Documents/playground/dask-test.py', wdir='C:/Users/ankurs/Documents/playground')
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/ankurs/Documents/playground/dask-test.py", line 21, in <module>
>     df2 = pd.read_sql_table(table_name  = 'TABLE_NAME', con = conn, index_col = 'INDEX_COL')
> 
>   File "C:\Users\ankurs\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py", line 242, in read_sql_table
>     raise ValueError("Table %s not found" % table_name)
> 
> ValueError: Table TABLE_NAME not found

**Comment by mrocklin** [comment]
I recommend first ensuring that your workflow works smoothly in Pandas and then try Dask afterwards.  

I'm going to close this for now.  If you get things working with Pandas but Dask.dataframe doesn't work then please speak up.

**Comment by ansin218** [comment]
To anyone else facing a similar problem, this is how you can go about debugging it: 

https://github.com/pandas-dev/pandas/issues/11258

This is not a Dask issue, not even Pandas, but rather SQL Alchemy!

**Comment by mrocklin** [comment]
Thanks for updating Ankur.  I'm sure that others will appreciate it.

**Comment by martindurant** [comment]
If you wish to use read_query instead of read_table, then you could try with intake-sql, or follow the pattern [here](https://github.com/ContinuumIO/intake-sql/blob/master/intake_sql/intake_sql.py#L144), so long as you explicitly know beforehand how you would like to partition your data.
