### ISSUE TITLE
how can i use a dask array to slice a dask array

### ISSUE THREAD

**Issue by Rhettydl** [dask/dask#3959]
while i have a dask array such as
data = da.randon.normal(0,2,1000,chunks=1000)
and a index such as 
index = da.linspace(1,1000,100,chunks=100)
how can i use index to slice data
i see the way of a[b.argtopk(num)]
but i can not use it success, thank you very much

**Comment by TomAugspurger** [comment]
Your code has a typo, `randon` -> `random`.

I also assume your `index` variable is incorrect, since that's an array of floats. NumPy can't index with that either.

Docs are at http://dask.pydata.org/en/latest/array-slicing.html. Let us know if there's anything that's unclear.
