### ISSUE TITLE
Postmortem debugging with dill.dump_session

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#396]
Debugging in a parallel context is a common source of frustration.

One solution is #386, where we rerun the failing task in the local process.  Running the task twice can be bad if the task has side effects.

Alternatively we could package up the entire runtime state of the failed worker with `dill.dump_session`, send that over to the local process, and then restart the failed state locally with a debug step.  The IPython `%debug` magic manages this somehow.

@mmckerns have you done this before?  Is there a prior implementation of this that I should consider?

**Comment by mmckerns** [comment]
I've sent session images to other computers and then restarted, but not with the intent of trapping an exception and debugging on a local host… so no, I have no experience doing that.

**Comment by mrocklin** [comment]
Closing as stale.

**Comment by mmckerns** [comment]
I should have sent this earlier: http://rpyc.readthedocs.org/en/latest/docs/howto.html  maybe you knew of it.
