### ISSUE TITLE
read_sql_table fails on large tables

### ISSUE THREAD

**Issue by spleiner** [dask/dask#3961]
I am trying to read a table on a SQL Server containing  approximately 3 billion rows with the following code:

import dask.dataframe as dd
df = dd.read_sql_table("TABLE",connectionstring,"INDEX")

After a while I get the following error:
DataError: (pyodbc.DataError) ('22003', '[22003] [Microsoft][ODBC SQL Server Driver][SQL Server]Arithmetic overflow error converting expression to data type int. (8115) (SQLExecDirectW)') [SQL: 'SELECT count([TABLE].[TAB_KEY]) AS count_1 \nFROM [TABLE]'] (Background on this error at: http://sqlalche.me/e/9h9h)

When using another client to query the database with:
SELECT COUNT(*) FROM TABLE

I get the same Arithmetic overflow error converting expression to data type int. (8115)-error but when using:

SELECT COUNT_BIG(*) FROM TABLE

it works.

Is there a way to make Dask use COUNT_BIG or some other workaround?

Python: 3.6.6
Dask: 0.19.1

**Comment by martindurant** [comment]
The code could certainly change COUNT -> COUNT_BIG; however, this expression is meant to be cross-sql-dialect, and I don't think COUNT_BIG is standard. Do you know of a way to do this that would be sure to work on all backends?

As an aside, you can avoid the count query if you supply the `divisions=` manually.

**Comment by martindurant** [comment]
Does `CAST(COUNT(*) AS BIGINT)` work?

**Comment by martindurant** [comment]
I'm not sure this is legal syntax, but `COUNT(1 as BIGINT)` may do the trick.

**Comment by mrocklin** [comment]
What is the status here?  Is there a proposed change to Dask or can this be closed?

**Comment by martindurant** [comment]
I have no way to check this. If @spleiner can confirm that some syntax like my suggestion solves the problem, that would be a beneficial change. Otherwise, we would probably need a SQL expert on this problem.

**Comment by spleiner** [comment]
Sorry for my absence but here are the results of various SQL queries:
SELECT COUNT(*) FROM table -> **Fails** (SQL Error 8115, arithmetic overflow)
SELECT COUNT_BIG(*) FROM table -> **Works** fine
SELECT CAST(COUNT(*) AS BIGINT) FROM table -> **Fails** (SQL Error 8115, arithmetic overflow)
SELECT COUNT(1 as BIGINT) FROM table -> **Fails** (SQL Error 195, COUNT is not a recognized built-in function)

**Comment by martindurant** [comment]
Ah, but I think COUNT_BIG only exists for MS SQL server, and, apparently, is not the function returned by the SQLalchemy `count()` function. So maybe this should be posted as an issue to sqlalchemy? I do not immediately find any reference to the problem by searching.

**Comment by martindurant** [comment]
I don't know if you tried, but in the first comment, above, I mentioned that you can avoid the COUNT branch in the code completely. It only gets used in the case that divisions=None and npartitions=None. Assuming we cannot solve how to get sqlalchemy to cooperate here, that would be the easier way to go.

**Comment by jrbourbeau** [comment]
@spleiner any update here? Does @martindurant's comment about avoiding the COUNT branch help your situation?

Is there a proposed change to Dask for this issue, or is it safe to close?

**Comment by mrocklin** [comment]
Given the age of this issue.  Lets just close.  @spleiner if you'd like to continue the conversation let us know and we'll reopen.
