### ISSUE TITLE
How can I get a np.array from dask array quickly

### ISSUE THREAD

**Issue by Rhettydl** [dask/dask#3967]
while I have a dask array such as :
data_dask = da.random.normal(2,2,(10000,10000),chunks=(1000,1000))
at fist, I use data = np.array(data_dask) or data = data_dask.complete(), it is quickly,
but,while I do some operate with it,such as data_dask_two = data_dask * 3 + 2 and so on,
then  data = np.array(data_dask_two) or data = data_dask_two.complete() will be very slow, how can i saolve this?

**Comment by TomAugspurger** [comment]
You question is quite broad. Could you specify what "quickly" and "quite slow" is? How long to they take relative to eachother? Relative to NumPy? Do you suspect there's a performance issue somewhere in dask? Have you read through http://dask.pydata.org/en/latest/understanding-performance.html?

**Comment by mrocklin** [comment]
No response from original asker.  Closing.
