### ISSUE TITLE
Memory usage increases substentially since 0.19.0

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#3970]
There appears to be changes in dask optimizing the slicing, such that since 0.19.0 the memory usage of our application suddenly increased by a huge factor, causing OOM errors. The problem persists in 0.19.1. The application worked fine with dask 0.18.2 and before.

The basic usage pattern is to use dask to access an object representing disk files that provides slicing support for reading data.

It seems like rather than only reading the requested chunks, dask is either reading more or trying to internally cache the read data instead of freeing up the memory. Where shall I look for a potential workaround?

**Comment by mrocklin** [comment]
In your situation, assuming that you can easily test behavior, I would
probably use git bisect to identify the commit where the behavior changes.

**Comment by rainwoodman** [comment]
Indeed. I found the commit that introduced the problem here:

https://github.com/dask/dask/commit/55d243b68b3d33648c77e1d3801371be4ad15a41

**Comment by mrocklin** [comment]
Does the commit message help explain why things may have changed for you?

**Comment by rainwoodman** [comment]
I think this is because we use dask.array, and by-pass the optimization routines of dask (due to  a performance issue related to commuting column / slicing on column-wise storage formats):

https://github.com/bccp/nbodykit/blob/master/nbodykit/base/catalog.py#L554

What do you recommend us to do here?

**Comment by mrocklin** [comment]
Yes, that would explain things.  You should probably call the cull function
manually.  Unfortunately there aren't great mechanisms to pick out just
certain optimization functions.  You'll probably have to dig a bit to get
at the graphs, merge them appropriately and then call cull and get manually.

Alternatively you could consider turning optimizations back on and see if
you can improve why they were slow in the first place.

**Comment by rainwoodman** [comment]
What are the chances the culling being added back to the main compute function of dask?

**Comment by mrocklin** [comment]
Low near-term.

**Comment by rainwoodman** [comment]
I am adding a `__dask_optimize__` method to our subclass of `dask.array.Array` that does the culling. I do wonder if it is OK that I drop the dependency return value of cull (seems to be fine).

https://github.com/bccp/nbodykit/pull/521

**Comment by mrocklin** [comment]
Yes, that should be fine

**Comment by rainwoodman** [comment]
Thanks. Closing this ticket then.
