### ISSUE TITLE
Client.submit function results in inconsistent results for dask dataframe groupby operation

### ISSUE THREAD

**Issue by KiranVaranas** [dask/dask#3988]
The below test case produce inconsistent results under multi node cluster. The test was ran on 2 node cluster using client.submit vs dask dataframe operation. The same test works correctly on single node where all workers exists on the same machine.
The below are dask versions used
**dask==0.19.1**
**distributed==1.22.1**

```
import pandas as pd
from dask.distributed import Client
from dask import dataframe as ddf
client=Client("localhost:8786")

def generate_data():
    dataframe_data = {
        'incremental_key':list(range(1537188888,1537188888+100)),
        'column1':range(0,100)
    }
    input_dataframe = ddf.from_pandas(pd.DataFrame(dataframe_data), npartitions=10)
    return input_dataframe

def agg_sum(data):
    data["column1_max"]=data["column1"].sum()
    return data

def group_by_agg(input_data,ts_col):
    out_df=input_data.groupby(ts_col).apply(agg_sum)
    return out_df

input_data=generate_data()
ts_col="incremental_key"
output_df= client.submit(group_by_agg,input_data,ts_col).result()
print("Post client.submit function....",output_df.count().compute())

output_df=group_by_agg(input_data,ts_col)
print("Post dataframe operation with out client.submit function....",output_df.count().compute())
```
****

**Comment by mrocklin** [comment]
Thanks for the bug report @KiranVaranas .  Are you able to reduce it any further?  I'm curious if the particular values and column names and data that you use are required to reproduce the failure.  My guess is that only some of these are important and that you are probably the most qualified person to try things out to figure out what is necessary.

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by KiranVaranas** [comment]
I have simplified it further.The apply function after groupby aggregation is giving incorrect results.
I need to 2 columns atleast to reproduce the same using groupby function.

**Comment by mrocklin** [comment]
When I run the following I get the following results:

```python
In [1]: import pandas as pd
   ...: from dask.distributed import Client
   ...: from dask import dataframe as ddf
   ...: client=Client()
   ...: 
   ...: def generate_data():
   ...:     dataframe_data = {
   ...:         'incremental_key':list(range(1537188888,1537188888+1)) + [1537188888] * 99,
   ...:         'column1':range(0,100)
   ...:     }
   ...:     input_dataframe = ddf.from_pandas(pd.DataFrame(dataframe_data), npartitions=10)
   ...:     return input_dataframe
   ...: 
   ...: def agg_sum(data):
   ...:     data["column1_max"]=data["column1"].sum()
   ...:     return data
   ...: 
   ...: def group_by_agg(input_data,ts_col):
   ...:     out_df=input_data.groupby(ts_col).apply(agg_sum)
   ...:     return out_df
   ...: 
   ...: input_data=generate_data()
   ...: ts_col="incremental_key"
   ...: output_df= client.submit(group_by_agg,input_data,ts_col).result()
   ...: print("Post client.submit function....",output_df.count().compute())
   ...: 
   ...: output_df=group_by_agg(input_data,ts_col)
   ...: print("Post dataframe operation with out client.submit function....",output_df.count().compute())
   ...: 
/home/mrocklin/Software/anaconda/bin/ipython:19: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
Post client.submit function.... column1            100
incremental_key    100
column1_max        100
dtype: int64
/home/mrocklin/Software/anaconda/bin/ipython:19: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
Post dataframe operation with out client.submit function.... column1            100
incremental_key    100
column1_max        100
dtype: int64
```

I'm not sure what the error is supposed to be here.  

Note that you're calling submit on a function that takes dask dataframes.  This is odd; is there a reason why you are doing this?  This shouldn't affect correctness, but will force everything into a pandas dataframe when you're using the futures interface.  Most people just stick to using dask.dataframes.

**Comment by san21886** [comment]
@mrocklin : I was also able to verify the problem reported by @KiranVaranas . If there are multiple worker nodes then the result  of submit is not consistent.

Here is the result from my run(2 worker nodes):

**Post client.submit function.... column1            47**
incremental_key    47
column1_max        47
dtype: int64
test.py:19: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  out_df=input_data.groupby(ts_col).apply(agg_sum)
**Post dataframe operation with out client.submit function.... column1            100**
incremental_key    100
column1_max        100
dtype: int64

I do agree that if an usecase can be achieved using available dask dataframe apis then we should avoid using submit but in some situations where you have to use pandas apis then submit provides a way to execute on nodes which have sufficient resources.

**Comment by mrocklin** [comment]
> but in some situations where you have to use pandas apis then submit provides a way to execute on nodes which have sufficient resources

Do you understand that by calling submit on a dask dataframe that you force it to become a pandas dataframe?

Unfortunately I'm not able to reproduce the problem that you're running into.  I'm not sure how best to help.

**Comment by san21886** [comment]
@mrocklin - I totally get your point about submit on dask dataframe.

About the inconsistent result, let me check again and comeback.

**Comment by mrocklin** [comment]
> I totally get your point about submit on dask dataframe.

OK, my apologies for assuming that you didn't know what was going on here.

**Comment by san21886** [comment]
No problem @mrocklin . Thanks for pointing in right direction about the dataframe. It will certainly help other as well.

About the inconsistent result: I did fresh installation of dask 0.17.1, distributed - 1.21.6, tornado - 4.5.3 and thrift - 0.10.0 on 3 VMs. I still see the same problem. 

I also wanted to add that, this is in the recent installations that I have seen this problem. Old installations with same version gives the right result.

If possible can you try with new installation. Or can provide me versions that you tried on.

**Comment by mrocklin** [comment]
You might try with newer versions.  The latest dask release is 0.19.2.

**Comment by mrocklin** [comment]
Any update on this?

**Comment by san21886** [comment]
0.19.2 also had similar behavior. We are now thinking of changing out approach.
Thanks for your help @mrocklin .
