### ISSUE TITLE
Supporting alternative RandomState objects

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask#3993]
Alternative random number generator libraries can be significantly more performant than numpy so, if it's easy to support there may be value in allowing alternative `RandomState` implementations:

![image](https://user-images.githubusercontent.com/881019/45734679-b9fed700-bc28-11e8-9ac0-28b8c1238194.png)

**Comment by dhirschfeld** [comment]
[IIUC](https://github.com/numpy/numpy/blob/6105281cf245c5713660245a0c87ae00e85aec23/doc/neps/roadmap.rst#random-number-generation-policy--rewrite) `randomgen` will eventually become numpy's new random generator implementation but that might not be for quite a while. Also, the MKL implementations are 2x faster than even `randomgen`.

**Comment by mrocklin** [comment]
Interesting.  Would it be enough to generalize this line by providing a keyword input for an explicit randomstate object?

https://github.com/dask/dask/blob/a25c47b3a003ba2aff2cd803f49812ae69ff43bc/dask/array/random.py#L46-L47

**Comment by dhirschfeld** [comment]
^^^ I was kind of hoping that might be the case in which case it would totally be worth it IMHO.

What got me was all the individually defined methods:
```python
    @doc_wraps(np.random.RandomState.exponential)
    def exponential(self, scale=1.0, size=None, chunks=None):
        return self._wrap(
            np.random.RandomState.exponential, scale,
            size=size, chunks=chunks
        )
```
...which made it seem not so straightforward? There may be a smart way around it,  not sure, but if not I'd probably rate it as very low priority because with the ability to scale out horizontally it's likely not a performance issue.

**Comment by mrocklin** [comment]
Perhaps the user would provide a RandomState class and we would use the methods of that class instead of np.random.RandomState?

```python
rs = da.random.RandomState(RandomState=mymodule.RandomState, seed=123)
```

**Comment by dhirschfeld** [comment]
^^^ That sounds like a great api! That would also easily allow passing custom params (such as `method='ICDF'` /  `brng`)

**Comment by mrocklin** [comment]
Is this something that you'd like to take on @dhirschfeld ?

**Comment by dhirschfeld** [comment]
Ha ha! I think I could probably do that, however my enthusiasm for good ideas is currently far outstripping my ability to deliver (except perhaps on a critical path for work).

My near-term goal is to close out #2085.

I'll keep this on the back-burner though - a 5x performance improvement is nothing to sniff at though dask is a bit of a victim of its own success here - it's probably easier to add more workers than implement a generic rng interface 🤔

**Comment by mrocklin** [comment]
It shouldn't be hard to do.  I encourage you to make an attempt.
