### ISSUE TITLE
Docs: Issue about naming conventions of dask modules in the text

### ISSUE THREAD

**Issue by farrajota** [dask/dask#3999]
I've started taking a deeper look at Dask recently by reading its documentation and I've encounter a few typos here and there (which is expected to have in any sizable project). So I submitted a few corrections and I would like to contribute a little more to the docs since I'm reading them anyway (I like to fix these kinds of errors whenever I see them).

Having said this, there are some incongruities in the naming conventions of Dask modules throughout the docs. For example, the Dask's Array module is written in several different ways in the **Array** section of the documentation:
- [in the first sentence](https://dask.pydata.org/en/latest/array.html#array) it is written Dask Array
- [here](https://dask.pydata.org/en/latest/array.html#common-uses) it is written Dask array (here I'm not saying this way is wrong, I'm just using it to point out to this issue)
- [also here](https://dask.pydata.org/en/latest/array-sparse.html#sparse-arrays) it is written both Dask.array and dask.array
- [and in other places](https://dask.pydata.org/en/latest/diagnostics-local.html#example) it is highlighted as `dask.array`

This issue is visible across several sections of the documentation for other modules besides Dask Array like Dask's Bag module, where it is written in several different ways like Dask.Bag, Dask.bag, `dask.bag`, etc.

I think it would be better to keep the same naming convention throughout the docs  by using a couple of ways of naming a module in order to have some consistency while helping to avoid miss-interpretations by the reader (and to look nice of course). 

Personally, I'd use the highlighted convention (`dask.array`, `dask.bag`, `dask.graph`, etc) when referring to a module and the capitalized Dask instead of dask when referring to the library.

What do you think?

**Comment by mrocklin** [comment]
> So I submitted a few corrections and I would like to contribute a little more to the docs since I'm reading them anyway (I like to fix these kinds of errors whenever I see them).

First, let me just say that I'm very happy to hear this.  Thank you for taking the time to help out here. I really appreciate it and I suspect that many others do as well.

The variation you're seeing is historical.  I think that we tended to use `dask.array` early on, and have slowly moved towards "Dask Array" when describing the object generally.

> Personally, I'd use the highlighted convention (`dask.array`, `dask.bag`, `dask.graph`, etc) when referring to a module and the capitalized Dask instead of dask when referring to the library.

This fits my personal preference as well.  I find that I refer to the library or collection abstractly ("Dask Arrays are great for parallelizing Numpy") far more often than I refer to the specific module ("The `atop` function is available within the `dask.array` submodule`).

**Comment by farrajota** [comment]
> This fits my personal preference as well. I find that I refer to the library or collection abstractly ("Dask Arrays are great for parallelizing Numpy") far more often than I refer to the specific module ("The atop function is available within the dask.array submodule`).

If no one disagrees with this, then I could attempt to refactor this issue in the docs whenever I see it

**Comment by farrajota** [comment]
I'm closing this issue for now since there hasn't been any discussion on this issue. Please, feel free to re-open this issue in case anyone has something to say about this.
