### ISSUE TITLE
Do apply after filter?

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#4004]
My code looks something like this

```python
df = pd.DataFrame({
 'a': ['a', 'b', 'c', 'd'],
 'b': [1, 2, 1, 2],
})
ddf = dd.fromPandas(df)
# A series of applies that generate new columns and use column a
ddf['c'] = ddf.a.apply(lambda x: f'{x}_c')
ddf['d'] = ddf.a.apply(lambda x: f'{x}_d')
ddf['e'] = ddf.a.apply(lambda x: f'{x}_e')
# Wanted to take a subset and take a look
curious = ddf[ddf.b == 1].compute()
```
If I'm understanding correctly, dask runs the applies on all my data and not just the filtered subset to make "curious." This seems inefficient. 

I'm aware that I could write my code the other way round, but when exploring in a notebook, that's not always how it goes.

**Comment by mrocklin** [comment]
Correct.  Dask dataframe doesn't do any high-level optimization to rewrite
your logic.  This would be a nice optimization of course, but isn't
currently part of the project.  It would be a sizable new chunk of
functionality.
