### ISSUE TITLE
Optionally batch reading large number of small files

### ISSUE THREAD

**Issue by epall** [dask/dask#4012]
Dask's `bag.read_text()` function performs poorly when given a large number of small files (>1000 * ~100kb), because it constructs a massive graph of operations that takes significant time (10-50s) to serialize. Reading chunks of files in batches would dramatically reduce the size of the graph, cutting overhead both in time and memory. This could be an optional parameter to `read_text()`.

**Comment by mrocklin** [comment]
Makes sense to me.  Something like a `files_per_partition=None` parameter?
If you are interested in implementing this that would be welcome.

**Comment by epall** [comment]
Yep. Got a prototype working now. PR incoming.
