### ISSUE TITLE
Better name for atop?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4035]
The class of operations encompassed by `atop` includes elemwise, transpose, tensordot, reductions (in theory if not in practice) and others.  It is characterized by a chunksize operation, and an Einstein-summation style indexing pattern.  Can we think of a better name for this class of operations than `atop`?

cc @shoyer @jcrist

**Comment by shoyer** [comment]
I tend to think of "tensor" as more of an explicitly indexed quantity than an array.

What about "block indexed op"?

**Comment by mrocklin** [comment]
> explicitly indexed quantity than an array

What do you mean by indexed quantity here?

-  An object with the ability to refer to elements in some sort of grid, like a numpy array?
-  An object with a pandas style index, like an xarray.DataArray?
-  An object along with some statement that uses something that looks aesthetically like einstein summation notation, like `$X_{ijk}^{ij}$`?

"block indexed op" sounds like an improvement to me (not to say that we couldn't come up with something better).

**Comment by shoyer** [comment]
Or "chunk indexed"?

**Comment by jcrist** [comment]
I also like `tensor_op` for the public facing function, but have no strong argument as to why. Agree that whatever it is, `atop` is too abbreviated to be publicly meaningful.

**Comment by mrocklin** [comment]
Any response to this concern about the name `tensor_op`?

> The name "tensor op" seems too generic to me. Aren't operations that don't fall into the atop system also "tensor op"s? Is solve, or slicing, or the generation of random data somehow different?

**Comment by jcrist** [comment]
Not really. When I thin tensor I think indexed operations along multiple dimensions, einstein-sum notation, etc... That all seems to fit within `atop`'s realm (note that I don't do actual tensor work, and this word certainly means something different to others). There may be a better name though.

Free associating `atop` related words:

- `indexed`
- `apply`
- `blocks`
- `tensor`
- `op`
- `map`
- `contraction`
- `reduction`

And some combinations of these:

- `indexed_op`
- `apply_indexed_op`
- `apply_indexed`
- `indexed_tensor_op`
- `blockwise_op`
- `apply_blocked_op`

**Comment by jakirkham** [comment]
FWIW we use `atop` any time an operation gets too fancy for `map_blocks`. We also use it for all sorts of things that have nothing to do with traditional tensor operations (in addition to the more usual cases). As one example, we need to translate some frames in a video and truncate them. This is done using `atop`.

**Comment by mrocklin** [comment]
How about `broadcast` or `blockwise`

Also, I'm thinking of reusing the high-level atop code for dask dataframe blockwise operations.

**Comment by mrocklin** [comment]
`Blockwise` then?

**Comment by shoyer** [comment]
Sounds good to me.

**Comment by mrocklin** [comment]
This has been partially implemented in #4348

**Comment by jakirkham** [comment]
Sorry to be late on voicing an opinion here. @jcrist’s suggestion of `contraction` is more descriptive IMHO.

**Comment by shoyer** [comment]
@jakirkham the confusing bit about the name `contraction` is that `atop` often does not remove any indices, e.g., like how it's used for arithmetic.

**Comment by jakirkham** [comment]
Naming is hard :)

That's fair. Maybe `tensor_op` is still appealing?

Am mainly thinking it would be useful to communicate that indexing for this function is tensor-based. Otherwise I worry that new users won't understand why this function has the API it does.

**Comment by mrocklin** [comment]
I'm somewhat against the use of the word tensor to mean a multi-dimensional array in programming.  In general I prefer the name array in this case, which has been used for longer and is somewhat less hyped today.  I'm probably more strongly biased here than most people though, perhaps irrationally so.

Regardless, I think that the words tensor/array are both too specific (we're also using this now for dask dataframe) as well as too generic (lots of tensor/array operations don't fall into the old top/atop functionality).  I think that `blockwise` is arguably also too generic, but maybe less so.

**Comment by mrocklin** [comment]
> Naming is hard :)

Indeed!  I'm growing increasingly confident that there is no good and concise name for this operation :/
