### ISSUE TITLE
Fusing purely linear chains not working

### ISSUE THREAD

**Issue by SimonHeybrock** [dask/dask#4036]
On branch `master`, in particular after https://github.com/dask/dask/pull/3979 was merged: I am trying to make use of the new feature of merging linear chains in (sub)graphs. To do so, I enable it via the config:

In `config.yaml`:
```
fuse_subgraphs: True
```

The following works as expected, with the new `fuse_subgraphs` option the long chains are now fused:

```python
import dask
import dask.array as da
import numpy as np

if __name__ == '__main__':
    x = da.from_array(np.zeros((3,)), chunks=(1,))
    x = x + x
    branch = x + x
    x = x + branch
    x = x + x
    x = x + x
    x = x + x
    x = x + x
    dask.visualize(x, filename='fused.svg', optimize_graph=True)
```

However, graphs without any branches will not fuse:

```python
import dask
import dask.array as da
import numpy as np

if __name__ == '__main__':
    x = da.from_array(np.zeros((3,)), chunks=(1,))
    x = x + x
    x = x + x
    x = x + x
    x = x + x
    x = x + x
    x = x + x
    x = x + x
    dask.visualize(x, filename='not-fused.svg', optimize_graph=True)
```

I have tracked the issue back to https://github.com/dask/dask/blob/master/dask/optimization.py#L570 --- for a linear graph this returns early, skipping fusion of linear chains. I do not understand what exactly is done in this part of the code, so I cannot propose a precise fix.

**Comment by mrocklin** [comment]
cc @jcrist
