### ISSUE TITLE
Dictionary type for map_partitions meta argument is not supported

### ISSUE THREAD

**Issue by LucMioulet** [dask/dask#4037]
Python 3.6, dask 0.19.2.

```
import pandas as pd
import dask.dataframe as dd

a = pd.DataFrame([[1,2]],columns=['a','b'])
ddf = dd.from_pandas(a, npartitions=1)
def foo(x):
    return x
result = ddf.map_partitions(foo, meta={'a':int,'b':int})
result.compute() # works fine
result = ddf.map_partitions(foo, meta={'b':int,'a':int}) #not sorted in the same order as the columns
result.compute() # produces the following error:
```

```
raise ValueError("The columns in the computed data do not match"
ValueError: The columns in the computed data do not match the columns in the provided metadata
```

We can pass a dictionary with the [API](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions), but internally the map_partitions only uses unsorted arrays (dictionaries are transformed into them)... Either the API should support dictionary as an input for the meta, or remove its support.

**Comment by TomAugspurger** [comment]
Same issue as https://github.com/dask/dask/issues/2789
