### ISSUE TITLE
Accessing Wrapped Delayed Function

### ISSUE THREAD

**Issue by jamesstidard** [dask/dask#4045]
Hi,

I'd like to be able to get back to the function which has been wrapped in a delayed for later use in my application. One use-case would be inspecting the return type annotation to avoid needless computation.

For example I might have a something like this:

```python
@delayed
def heavy_work() -> int
    return 5

delayed_work = heavy_work()

# application loses context of how delayed_work was made.

if isinstance(delayed_work.fn.__annotations__['return'], int):
    # know the return type looks like what I'm after so do computation
    value = compute(work)
    print(value)
else:
    # early error without computation
    raise TypeError('wrong type, expected int')
```

Is it possible to get to the wrapped function in dask, or am I able to subclass a `dask.delayed.Delayed` to achieve this?

Thanks.

**Comment by mrocklin** [comment]
For a wrapped function object you can do the following:

```python
In [1]: import dask

In [2]: f = lambda: None

In [3]: d = dask.delayed(f)

In [4]: d.__dask_graph__()[d.key]
Out[4]: <function __main__.<lambda>>

In [5]: _4 is f
Out[5]: True
```

However once you've called that function on an object you'll have to do some digging within the graph.  I recommend investigating `dict(obj.__dask_graph__())`.

**Comment by jamesstidard** [comment]
Ah that looks spot-on, thank you @mrocklin, I'll take a look at the graph
