### ISSUE TITLE
Somewhat of a gotcha: performance with dask.distributed.Client() not representative for actual performance?

### ISSUE THREAD

**Issue by Huite** [dask/dask#4054]
The Dask dashboard has been a great tool in helping me reason about scheduling before. However, I ran into a case just now where I got rather confused.

### Background
I have some model output for three fluxes (`primary, secondary, tertiary`). Originally, this is 2D data, with one file per timestep. I concatenated this using xarray, and dumped it into a netcdf. This netcdf is moderately big, so I define `chunks` in `open_dataset()`. The dimensions, and shape are as follows:
```
(time, y, x) float32 dask.array<shape=(4018, 284, 429)>
```

I add these fluxes, then write to another netcdf for later processing:
```Python
ds = xr.open_dataset("flux.nc", chunks={"time":1})
ds["total"] = ds["primary"] + ds["secondary"] + ds["tertiary"]
ds.to_netcdf("flux_with_total.nc")
```

A priori, I expect chunking over the `time` dimension to be best (because of row major order). I figured I'd test a little, using the Dash dashboard to monitor.

This resulted in some very slow performance, and in the above case, chunking of `x` and `y` turned out to be faster:
```Python
ds = xr.open_dataset("flux.nc", chunks={"y":50, "x":50})
```

However, repeating the computations _without_ the dashboard gives results as expected: chunking over time dimension is faster.

## MWE

I did a little more testing, and I don't think it's because of `xarray`, I can reproduce the general pattern using just `dask.array`.
(I ran the following in a Jupyter Notebook):

### With Client()
```Python
import dask.array as da
from dask.distributed import Client

client = Client()
client

# "Sensible" chunking
da1 = da.random.random(size=(400, 300, 200), chunks=(1, 300, 200))
da2 = da.random.random(size=(400, 300, 200), chunks=(1, 300, 200))
da3 = da.random.random(size=(400, 300, 200), chunks=(1, 300, 200))
da4 = da1 + da2 + da3

%timeit da4.compute()
```

Results in:
```Python
8.33 s ± 568 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
```Python
# "Suboptimal" chunking
da1 = da.random.random(size=(400, 300, 200), chunks=(400, 50, 50))
da2 = da.random.random(size=(400, 300, 200), chunks=(400, 50, 50))
da3 = da.random.random(size=(400, 300, 200), chunks=(400, 50, 50))
da4 = da1 + da2 + da3

%timeit da4.compute()
```

Results in:
```Python
5.74 s ± 451 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### Without Client()
Running this without `Client()` gives me, for `chunks=(1, 300, 200)`:
```Python
776 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

And for `chunks=(400, 50, 50)`:
```Python
1.2 s ± 57.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

## Remarks
Two observations:
1. With Client() is five to ten times slower (>20 times slower in one of my xarray `to_netcdf()` examples).
2. Chunking "wrongly" is significantly faster with Client(). Probably because of the overhead of monitoring every chunk, which matters more in this case than memory access?

The computation is minimal, so it makes sense. My impression is that it does get worse when IO is involved,  there's two jupyter notebooks using `xarray` [here](https://github.com/Huite/Notebooks).

## Concluding
The more I think about it, the less surprising I find it that a different chunking scheme (with more chunks) results in worse performance. 

The slowdown with I/O does seem rather dramatic, from 3.7 seconds to over a minute for me.

So (if my understanding is correct) it may be worthwhile to add a line in the documentation stating that dashboard overhead may well be dominant when dealing with very simple computations, or I/O bound operations?

**Comment by mrocklin** [comment]
It looks like you're setting up a client with multiple processes, so yes, I
would expect operations that were previously fast but moved around a lot of
data to be slower.  See http://docs.dask.org/en/latest/scheduling.html

I don't think that the overhead you're seeing has anything to do with the
dashboard.

**Comment by Huite** [comment]
Ah, I see!

 I think I'm a little less confused:
* I should have been looking at `dask.diagnostics` in this case; I didn't realize creating a `Client` overrides the scheduler ([it's right there in the documentation, of course](http://docs.dask.org/en/latest/setup/single-distributed.html)).
* It's also clear to me now I need to study the differences between the schedulers more.

Thanks.
