### ISSUE TITLE
Consistency Facilities / Defensive Programming

### ISSUE THREAD

**Issue by Tallic** [dask/dask#4057]
Hello,
in non-distributed imperative but also functional programming it is relatively easy to program defensively by adding assertions and other checking mechanisms into the computational stages.
This is also possible in Dask if you use defined functions.
However, this excludes lambdas as assertions are not possible in lambdas and the conditions are hidden under function names that do something else.

Developers would greatly benefit if they could add separate assert stages to their pipelines to check data consistency such as shape, relationships.
Ultimately, they would only be scheduled similar to ordinary assertions.

Example:
```
result = (bag.from_sequence(data, npartitions=10)
                    .starAssert(lambda a, b: 0 < a < b)
                    ... # several stages later
                    .starAssert(lambda a, b: 0 < b < a)
                    .compute())
```
```
result = (bag.from_sequence(data, npartitions=10)
                    .toDataframe()
                    .assertHomogeneity("some_repeated_value", columns="Common", axis=0)
                    ... # merges etc
                    .assert(lambda df: "category" not in df["Common"])
                    .compute())
```

There is a large design space for specialized assertions that would make the life easier.
However, the general assertion (assert true or assert equals) would already alleviate lots pragmatic development problems and make conditions on data explicit.

**Comment by TomAugspurger** [comment]
I would write these quality checks as a separate library and pass them to e.g. bag.map_partitions or dataframe.pipe.

**Comment by Tallic** [comment]
How would this look like?

**Comment by Tallic** [comment]
Ah ok :+1: yeah I have seen **engarde** and partially the idea came from it.

> Data are messy. But, our analysis often depends on certain assumptions about our data that should be invariant across updates to your dataset.

I completly agree with this statement and think consistency checks should be first-class citizens in a data heavy framework as unit testing is often quite hard. Probably wouldn't go so far to bloat the API with all sorts of checking methods, however, a simple assert function would help quite a lot.

Sadly the concept of engarde isn't quite as readable in contrast to the natrive framework support.
The extra methods have to be navigated, named, and clutter the namespace etc. 

A pipeline-style has several advantages:

- Naturally readable e.g., "bag becomes a dataframe that has homogenious data along column x and is merged with ...."
- Adds additional error handling and messaging during dev with precise messages and locations
- May be deactivated during production
- Allows for lambdas-style pipeline stages (no naming of simple method steps that change structure)

**Comment by TomAugspurger** [comment]
> Probably wouldn't go so far to bloat the API with all sorts of checking methods, however, a simple assert function would help quite a lot.

To me, the functions doing the actual checks are far more valuable than a "native" way to do the asserts. I wrote engarde because I was tired of re-writing the same quality checks over and over again in each project.


> isn't quite as readable in contrast to the native framework support

To be sure I understand, you're defining "native" as the difference between

```python
df = (
   load_data()
   .pipe(check_one)
   .apply(op)
   .pipe(check_two)
)
```


vs

```python
df = (
   load_data()
   .assert(check_one)
   .apply(op)
   .assert(check_two)
)
```

If pandas added something like this, dask dataframe would follow. But I don't think dask dataframe will get ahead of pandas here. I'm less sure about `dask.bag`, but this feels like something that can take advantage of the natural extension points like `.map_partitions` and `.pipe`, and be built on top of dask, rather than within it.

**Comment by mrocklin** [comment]
> If pandas added something like this, dask dataframe would follow. But I
don't think dask dataframe will get ahead of pandas here

+1 .  Perhaps this conversation should happen on the Pandas github issue
tracker first?

**Comment by Tallic** [comment]
> To me, the functions doing the actual checks are far more valuable than a "native" way to do the asserts. I wrote engarde because I was tired of re-writing the same quality checks over and over again in each project.

Currently writing a service and did not encounter many reusable assertions (mostly different datasources); however, in your case function-style is the way to go.

> don't think dask dataframe will get ahead of pandas here

fair enough, thanks for the time
