### ISSUE TITLE
incorrect result after calling set_index

### ISSUE THREAD

**Issue by cpcloud** [dask/dask#406]
```
In [24]: d = Castra('trip.castra/')

In [25]: df = d.to_dask()

In [26]: dd = df.set_index('dropoff_datetime')

In [27]: df.tolls_amount.sum().compute()
Out[27]: 43299963.519970238

In [28]: dd.tolls_amount.sum().compute()
Out[28]: 60320529.88000387
```

**Comment by mrocklin** [comment]
This is concerning.  It's also odd that it's higher.  It seems like we somehow duplicated data.

Can you report the `len` of both dataframes?

**Comment by cpcloud** [comment]
Yep. In the works

**Comment by cpcloud** [comment]
```
In [24]: len(dd)
Out[24]: 241210121

In [25]: len(df)
Out[25]: 173179759
```

**Comment by mrocklin** [comment]
Downloading the data now.  Looks like it should finish by tomorrow.  I'll go through and take a look at things.

**Comment by cowlicks** [comment]
@mrocklin ping

**Comment by mrocklin** [comment]
@cpcloud did this problem magically go away?

**Comment by cpcloud** [comment]
i can take a look today

**Comment by mrocklin** [comment]
Ping.  I'd like to close this if it's no longer an issue.

**Comment by mrocklin** [comment]
Closing in 24 hours if no comment
