### ISSUE TITLE
Dask Array Remote Storage Support

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#4060]
I'm currently using dask `0.17.1`. I'm curious as to why remote storage is supported for dask dataframe reading operations, but not dask array operations? I tried various `s3://` protocols on the dask array operations, but they couldn't understand the protocol, whereas `dd.read_csv` did understand the `s3://` protocol.

Also the dask documentation doesn't seem to mention whether you can write to the remote storage endpoints as well.

**Comment by mrocklin** [comment]
As mentioned in http://docs.dask.org/en/latest/array-creation.html you can create dask arrays from any object that supports numpy-style slicing.  If that object can read from a cloud object store then you can read and write to cloud object stores.  The only ndimensional array storage technology that I know of that can do this is Zarr.

The mechanism used to deliver bytes in dask bag and dask dataframe really only works well with linear storage formates.  nd storage formats are much more complex.

If you want to try to use the same mechanism on some custom array format you should take a look at http://docs.dask.org/en/latest/bytes.html .

**Comment by martindurant** [comment]
An example of how you might read array data from remote: https://github.com/ContinuumIO/intake/blob/master/intake/source/npy.py - it isn't so simple. This is in the context of the [Intake](https://intake.readthedocs.io/en/latest/) project, which is capable of *streaming* dask array data (and xarrays), i.e., a remote server reads data local to it, and passes the data for each chunk to the Intake client, such that it appears as a Dask array to the user.
