### ISSUE TITLE
Add meta attribute to Dask Array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4070]
Sometimes we want to ask questions about the kind of constituent arrays we have within our dask arrays.  For example we might want to know if it is sparse or on the GPU.

Currently we are unable to answer these questions, except by doing a small computation.

To resolve this we might consider storing a small empty array rather than the dtype.  This is similar to what we do with the `_meta` attribute to Dask Dataframes.

This would help us to understand more about our arrays, but would also introduce some potential challenges when computing metadata of subsequent arrays.

**Comment by shoyer** [comment]
This sounds pretty similar to what we discussed in https://github.com/dask/dask/issues/2977.

`meta` sounds like a fine name for this, though it might be enough to store the type of the arrays in each chunk.

**Comment by mrocklin** [comment]
Closing in favor of #2977  (thanks @shoyer )
