### ISSUE TITLE
Pandas Categorical Index causes groupby apply problems

### ISSUE THREAD

**Issue by parnell** [dask/dask#4072]
Using categories as an index and grouping by them produces unexpected output. The unexpected output is always a multiple of the number of categories. In the example given it seems to be 2, but I've seen upwards of 28.

It's hard to think this would be the expected output unless I'm missing something.

```python
df = pd.DataFrame({'Id': ['a','b','b','c','c']})
df['Id'] = df['Id'].astype('category')
df.set_index('Id', inplace=True)

gb = df.groupby(df.index)
r = gb.apply(len)
print(r)

df = dd.from_pandas(df, npartitions=4)
gb = df.groupby(df.index)
r = gb.apply(len, meta=pd.Series(name='len', dtype='int')).compute()
print(r)
```

The output of the above code is the following.
```
Id
a    1
b    2
c    2
dtype: int64
Id
a    1
b    0
c    2
a    0
b    2
c    0
Name: len, dtype: int64
```

**Comment by mrocklin** [comment]
Interesting.  Thanks for the excellent reproducible example.  I can reproduce on my machine.  My guess is that when we aggregate results the categoricals aren't fusing for some reason.  If you have any interest in pursuing this further that would be welcome @parnell ! (though of course, no obligation)

**Comment by parnell** [comment]
Thanks @mrocklin, but I don't think I have the understanding to work on it right now, and I don't think I have the time to delve further. Today is literally the first day I've used Dask. I just happened to have an exceptionally slow pandas groupby that I was trying to speed up and the bug happened.

But I'm sure it's useful know about at the very least.

**Comment by mrocklin** [comment]
It's a great bug report.  Thank you for taking the time to submit it.

**Comment by jakirkham** [comment]
FWIW this is still reproducible with Dask 1.2.1.

**Comment by TomAugspurger** [comment]
There's a warning about this in the docs at https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.groupby.DataFrameGroupBy.apply. GroupBy.apply(func) is applied to each partition, and there's no logic to combine the outputs for functions that reduce.

You want `.agg`

```python
In [18]: gb.size().compute()
Out[18]:
Id
a    1
b    2
c    2
dtype: int64
```
