### ISSUE TITLE
[DOCS] Code on Futures documentation page might be incorrect?

### ISSUE THREAD

**Issue by ericmjl** [dask/dask#4075]
Hi Dask team!

I am not quite sure if I've spotted this correctly or not. On the [Futures documentation page](http://docs.dask.org/en/latest/futures.html#distributed.Future.traceback), I see the following block of code:

<img width="674" alt="screen shot 2018-10-10 at 8 12 58 am" src="https://user-images.githubusercontent.com/2631566/46735569-8d0c7580-cc64-11e8-9704-d13ff76057c4.png">

The arrow in the PNG file points to:

```python
traceback.export_tb(tb)
```

However, when I looked inside the traceback module (Python 3.6), it doesn't have an `export_tb` function; rather, it has an `extract_tb` function. Might the docs need to be changed?

Cheers,
Eric

**Comment by mrocklin** [comment]
Indeed.  That does look like a typo.  I might suggest format_tb instead.
Would you be willing to make the change Eric?

**Comment by ericmjl** [comment]
Yes, no problem, @mrocklin :smile:
