### ISSUE TITLE
ValueError on .to_csv()

### ISSUE THREAD

**Issue by adriangrepo** [dask/dask#4084]
I have a very large csv file saved in pandas (58GB) which has the following types, plus two string (object) columns that merged from a pandas dataframe then dropped (not shown in dtypes)

`Unnamed: 0                      int64
Unnamed: 0.1                  float64
Unnamed: 0.1.1                float64
LCLid                          object
day_x                          object
energy_median                 float64
energy_mean                   float64
energy_max                    float64
energy_count                  float64
energy_std                    float64
energy_sum                    float64
energy_min                    float64
LCL_day_uid                    object
Bank_holiday                   object
time_x                         object
energy(kWh/hh)                float64
dayYear                       float64
dayMonth                      float64
dayWeek                       float64
dayDay                        float64
dayDayofweek                  float64
dayDayofyear                  float64
dayIs_month_end                  bool
dayIs_month_start                bool
dayIs_quarter_end                bool
dayIs_quarter_start              bool
dayIs_year_end                   bool
dayIs_year_start                 bool
dayElapsed                    float64
temp_day                       object
str_time                       object
day_time               datetime64[ns]
delta_minutes                 float64
day_time_str                   object
dtype: object`

When I run the following command:

`hh_dd.to_csv(f'{PATH}hh_dd-*.csv')`

I get the following error

/home/me/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/local.py:290: DtypeWarning: Columns (4,14,22,23,24,25,26,27,29,30,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  result = _execute_task(task, data)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-46-c028e832e29e> in <module>()
      1 #note dask needs a globstring to save files
----> 2 hh_dd.to_csv(f'{PATH}hh_dd-*.csv')

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/dataframe/core.py in to_csv(self, filename, **kwargs)
   1075         """ See dd.to_csv docstring for more information """
   1076         from .io import to_csv
-> 1077         return to_csv(self, filename, **kwargs)
   1078 
   1079     def to_delayed(self, optimize_graph=True):

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/dataframe/io/csv.py in to_csv(df, filename, name_function, compression, compute, get, storage_options, **kwargs)
    575 
    576     if compute:
--> 577         delayed(values).compute(get=get)
    578         return [f.path for f in files]
    579     else:

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    152         dask.base.compute
    153         """
--> 154         (result,) = compute(self, traverse=False, **kwargs)
    155         return result
    156 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    405     keys = [x.__dask_keys__() for x in collections]
    406     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 407     results = get(dsk, keys, **kwargs)
    408     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    409 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     74                         cache=cache, get_id=_thread_get_id,
---> 75                         pack_exception=pack_exception, **kwargs)
     76 
     77     # Cleanup pools associated to dead threads

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    519                         _execute_task(task, data)  # Re-execute locally
    520                     else:
--> 521                         raise_exception(exc, tb)
    522                 res, worker_id = loads(res_info)
    523                 state['cache'][key] = res

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
     65         if exc.__traceback__ is not tb:
     66             raise exc.with_traceback(tb)
---> 67         raise exc
     68 
     69 else:

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    288     try:
    289         task, data = loads(task_info)
--> 290         result = _execute_task(task, data)
    291         id = get_id()
    292         result = dumps((result, id))

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/local.py in _execute_task(arg, cache, dsk)
    269         func, args = arg[0], arg[1:]
    270         args2 = [_execute_task(a, cache) for a in args]
--> 271         return func(*args2)
    272     elif not ishashable(arg):
    273         return arg

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     46     def apply(func, args, kwargs=None):
     47         if kwargs:
---> 48             return func(*args, **kwargs)
     49         else:
     50             return func(*args)

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/dataframe/io/csv.py in pandas_read_text(reader, b, header, kwargs, dtypes, columns, write_header, enforce)
     64     df = reader(bio, **kwargs)
     65     if dtypes:
---> 66         coerce_dtypes(df, dtypes)
     67 
     68     if enforce and columns and (list(df.columns) != list(columns)):

~/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/dataframe/io/csv.py in coerce_dtypes(df, dtypes)
    154         msg = ("Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.\n\n"
    155                "%s" % (rule.join(filter(None, [dtype_msg, date_msg]))))
--> 156         raise ValueError(msg)
    157 
    158 

ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

+------------+--------+----------+
| Column     | Found  | Expected |
+------------+--------+----------+
| precipType | object | float64  |
| summary    | object | float64  |
+------------+--------+----------+

The following columns also raised exceptions on conversion:

- precipType
  ValueError("could not convert string to float: 'rain'",)
- summary
  ValueError("could not convert string to float: 'Clear'",)

Usually this is due to dask's dtype inference failing, and
*may* be fixed by specifying dtypes manually by adding:

dtype={'precipType': 'object',
       'summary': 'object'}

to the call to `read_csv`/`read_table`.

The columns raiseing the ValueError were clearly dropped

**Comment by mrocklin** [comment]
Thank you for the issue @adriangrepo .  Was the error message that Dask gave to you not clear?  Is there something else we can help with?

**Comment by adriangrepo** [comment]
Thanks for the response. I was wondering why I was getting this error - after the columns (precipType,  summary) were dropped from the DataFrame. I assumed that these would not exist anymore after they were dropped. NB when I ran df.head() the columns were not present.

**Comment by mrocklin** [comment]
Consider supplying the dtypes argument as recommended, or use the usecols=
keyword to not read them in the first place.

**Comment by mrocklin** [comment]
Answered.  Closing.
