### ISSUE TITLE
Add nchunks argument to Array constructor

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask#4085]
To me it seems that asking the user to specify the chunk *sizes* is somewhat cumbersome in practice. In my usage at least I'm always calculating what the appropriate chunk-size is given my desired `nchunks` and the size of the array.

As a user I often have a good idea of how many chunks I want as it relates to the amount of parallelism my desktop can handle - either a 1:1 mapping `nchunks:ncores` or some amount of over-subscription to allow for dynamic scheduling.

Just wondering if anyone else is of the same opinion or if I'm the only one?!

**Comment by dhirschfeld** [comment]
To work well (automatically) it might also need a `minsize` argument to specify the minimum chunk size in each dimension... in which case maybe it's adding too much complexity for too little gain? :thinking:

Anyway, I just thought I'd put the idea out there. Feel free to close if it's not deemed worthwhile...

**Comment by mrocklin** [comment]
I agree that this could be useful, but agree that the complexity could add
more maintenance burden.  I could go either way on this.

For now I think that the right thing to do is to consider how the API would
behave in a number of different situations.

**Comment by mrocklin** [comment]
@dhirschfeld did you have any follow up here?  It seems like things here have stalled.  Shall we close?

**Comment by dhirschfeld** [comment]
I still think (done well) it could be a nice improvement but there are some design issues which make it not entirely trivial to implement so I'm unlikely to have time to get stuck in here.

Given that I'll go ahead and close to reduce noise in the issues. It doesn't prevent anyone picking it up in future...
