### ISSUE TITLE
Inconsistent results between apply and agg methods

### ISSUE THREAD

**Issue by dimitar-petrov** [dask/dask#4088]
Hello Guys,

The dataset is a timeseries data with duplicated index read from hdf5 file with full index and CSI=True. 

I cannot present minimal complete example since the issue is tightly linked to the dataset and I don't have deep enought knowledge of dask to pin point and isolate it. So I will try to explain it.

Data Structure:
```
timestamp                               price	
2018-01-01 00:23:03.594	13061.0
2018-01-01 00:23:03.594	13059.5
2018-01-01 00:23:03.594	13064.0
2018-01-01 00:23:03.594	12495.0
2018-01-01 00:23:03.594	13074.5
```

If I decide to groupby index, I got different results with apply and agg:
```
part.groupby('timestamp').apply(lambda x: x.price.min(), meta=pd.Series()).compute()

timestamp
2018-01-01 00:23:03.594    12315.5
2018-01-01 00:23:03.594    12495.0
dtype: float64
```

```
part.groupby('timestamp').agg({'price': 'min'}).compute()
timestamp                               price	
2018-01-01 00:23:03.594	12315.5
```

`part` is a slice from the entire dataframe:

```part = df.loc['2018-01-01 00:23:00':'2018-01-01 00:24:00']```

Upon investigation I notced that this timestamp is one of the division points of the dataframe:

```
pd.Timestamp('2018-01-01 00:23:03.594') in df.divisions
True
```
And also the data in the part slice is divided in two partitions even though all records are with the same timestamp:

```
part.npartitions
2

part.get_partition(0).compute().price.min()
12315.5

part.get_partition(1).compute().price.min()
12495.0
```

So I guess the main question is why data with identical timestamp ended up in different partitions.

Here is the hdf5 structure.
```
/ (RootGroup) ''                                                                                                                                                                                                   
/foo (Group) ''
/foo/bar (Group) ''
/foo/bar/table (Table(1813408503,)) ''
  description := {
  "index": Int64Col(shape=(), dflt=0, pos=0),
  "values_block_0": StringCol(itemsize=4, shape=(1,), dflt=b'', pos=1),
  "values_block_1": Float64Col(shape=(1,), dflt=0.0, pos=2),
  "values_block_2": Int64Col(shape=(1,), dflt=0, pos=3)}
  byteorder := 'little'
  chunkshape := (9362,)
  autoindex := True
  colindexes := {
    "index": Index(9, full, shuffle, zlib(1)).is_csi=True}
/foo/bar/_i_table/index (Index for column /foo/bar/table.cols.index)
  optlevel := 9
  kind := full
  filters := Filters(complevel=1, complib='zlib', shuffle=True, bitshuffle=False, fletcher32=False, least_significant_digit=None)
  is_csi := True
  nelements := 1813408503
  chunksize := 16384
  slicesize := 4980736
  blocksize := 1817968640
  superblocksize := 3635937280
  dirty := 0
  byteorder := 'little'
  sorted := IndexArray(path=/foo/bar/_i_table/index/sorted)
  indices := IndexArray(path=/foo/bar/_i_table/index/indices)
  ranges := /foo/bar/_i_table/index/ranges (CacheArray(364, 2), shuffle, zlib(1)) 'Range Values'
  bounds := /foo/bar/_i_table/index/bounds (CacheArray(364, 303), shuffle, zlib(1)) 'Boundary Values'
  sortedLR := /foo/bar/_i_table/index/sortedLR (LastRowArray(4981041,), shuffle, zlib(1)) 'Last Row sorted values + bounds'
  indicesLR := /foo/bar/_i_table/index/indicesLR (LastRowArray(4980736,), shuffle, zlib(1)) 'Last Row indices'

```

Thanks,
Dimitar

**Comment by mrocklin** [comment]
Thanks for raising this issue @dimitar-petrov .  The first thing to do in this case is probably to come up with a minimal example that reproduces the problem.  As you say though, this is often difficult.  Often when in this situation I take a situation that I know fails and I remove as much of my application away from it as I can, piece by piece, until only a very small failing example remains.  If you're able to go through this process with your dataset and computation then that would be helpful.

**Comment by mrocklin** [comment]
No response.  Closing.
