### ISSUE TITLE
Solve Dask input file problems

### ISSUE THREAD

**Issue by rpanai** [dask/dask#4105]
Hi all, 
I recently saw this library [d6tstack](https://github.com/d6t/d6tstack) I was wondering if we can implement something similar on dask.

**Comment by TomAugspurger** [comment]
What exactly are you proposing? I'm not familiar with d6tstack.

Did you see https://github.com/d6t/d6tstack/blob/master/examples-dask.ipynb?

**Comment by rpanai** [comment]
Hi Tom,
yes I did see exactly that example. I was wondering if it is viable to implement it as a option for `dask.dataframe`

**Comment by TomAugspurger** [comment]
I still don't really follow what it's doing (because I haven't bothered to
look).

Typically, dask.dataframe follows pandas. Would something like this make
sense for pandas?

**Comment by TomAugspurger** [comment]
Thanks.

It sounds like that's pretty easy to do with d6tstack from outside of dask
/ pandas. Right now my preference would be to just do that rather than
incorporating it.

**Comment by mrocklin** [comment]
Maybe there is some way that d6stack could make optional use of dask?
Perhaps using something like dask.delayed?

**Comment by TomAugspurger** [comment]
https://github.com/d6t/d6tstack/blob/master/examples-dask.ipynb implies that it does that, but I haven't confirmed that.

**Comment by rpanai** [comment]
@mrocklin I'm not the author of that library but I guess it's possible.
@TomAugspurger I see your point. But I still think it could be an useful feature for people who's approaching to dask.

**Comment by mrocklin** [comment]
OK, it looks like the discussion here is less about the specific library `d6stack` and instead a request to cleanly read files with mismatched column names, dtypes, etc. and  unify them.  Is that the case?  

If so there are some performance issues.  In the general case it can be pretty expensive to read the metadata for every file upfront.  Historically we've asked that people handle this ahead of time before using Dask.  

Still, if there are options for easy wins that don't incur too much performance or maintenance cost they would probably be fine.  Is there anything specific being proposed here?  If not then I may close this issue in a few days and people can follow up with more specific issues if they have some sort of plan on a particular change to make.

**Comment by jakirkham** [comment]
@rpanai, has Matt accurately captured your question above? If so, are you able to clarify further what is being asked of Dask? Sounds like there were some performance implications of the previous proposal that we would like to avoid. If I've mischaracterized anything here, please (anyone) feel free to hop in 🙂

**Comment by rpanai** [comment]
> @rpanai, has Matt accurately captured your question above? If so, are you able to clarify further what is being asked of Dask? Sounds like there were some performance implications of the previous proposal that we would like to avoid. If I've mischaracterized anything here, please (anyone) feel free to hop in

Yes he has. We can close it.
