### ISSUE TITLE
Dataframe correlation function uses too much memory

### ISSUE THREAD

**Issue by jhb9** [dask/dask#4106]
Whenever I am calculating corr on a dask data frame with a larger but not enormous number of columns (200-2000) my worker memory is blowing up and getting  a MemoryError at one of two lines:

```
from /dask/dataframe/core.py

3885     x = np.where(keep, mat[:, None, :], np.nan)
3886     sums = np.nansum(x, 0)
```

This is reliably reproduced  with the code below, exact breaking point will obviously vary with worker,  I'm currently using 4 thread, 24GB workers.

```
arr = da.random.randint(100, size=(10_000, 500), chunks=1_000)
df  = dd.from_array(arr, columns=[f'col_{i}' for i in range(arr.shape[1])])
df.to_parquet(path)
df = dd.read_parquet(path)
corr = df.corr().compute()
```

Workers are reporting " distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 22.55 GB -- Worker memory limit: 24.00 GB"

Dask will break with memory errors at sizes small enough to process the entire calculation in memory with Pandas. I will need to scale to 10's of millions of rows and 1-3 thousand columns so staying in memory doesn't look to a be a good option.

**Comment by mrocklin** [comment]
> it looks like there are NumPy arrays created that are of shape (n_rows, n_cols, n_cols) for each DataFrame partition. Perhaps this could be the memory bottleneck herecd

That makes sense to me.  My guess is that there is a way to implement this function in smaller memory.

**Comment by mrocklin** [comment]
I'm going to mark this as good first issue, not necessarily because it's easy (it's actually quite an interesting problem) but rather because it requires little knowledge of dask itself.  The goal is to reimplement the `cov_corr_chunk` function in `dask/dataframe/core.py` in a way that produces the same result, but uses less memory.  This probably requires some good skill with numpy or pandas.
