### ISSUE TITLE
Memory usage limit

### ISSUE THREAD

**Issue by RealPolitiX** [dask/dask#4118]
Is there a way to explicitly limit the memory usage on a dask-based project (w/ thread scheduler)?

**Comment by mrocklin** [comment]
You probably want the following:

client = Client(memory_limit='8GB', processes=False)

**Comment by jcrist** [comment]
Closing, as it appears this has been answered. Feel free to reopen/open a new issue if you have further questions.

**Comment by H4dr1en** [comment]
The `memory_limit` parameter is not described in the [doc](http://distributed.dask.org/en/latest/api.html#distributed.Client). Was it removed in newer versions? If not, it should be appearing in the doc.

**Comment by mrocklin** [comment]
It's a keyword on LocalCluster.  See https://github.com/dask/distributed/pull/2647
