### ISSUE TITLE
Make Debian package

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#412]
We should consider making a dask debian package.  This provides two things

1.  It allays concerns about depending on dask by projects with conservative views on packaging
2.  It assists distributed system administrators who want to install dask, either in a parallel computing or institutional/university environment.  Apparently in these contexts even `pip install` is non-trivial.

**Comment by chdoig** [comment]
Some options to create debian packages from python applications:

- debinate: https://github.com/rholder/debinate
- dh-virtualenv: https://github.com/spotify/dh-virtualenv 

@rholder had some thoughts on those different alternatives.

**Comment by rholder** [comment]
I've done a bit of work over the years packaging up Python applications to ease installations and generally trying to make installing things as painless as possible. Both `debinate` and `dh-virtualenv` use `virtualenv` to isolate the `pip` installed module and its associated dependencies. These would work if installing via a .deb in an isolated environment is acceptable, but would limit the ability to mix it with other libraries.

If the intention is to build a package that is suitable as a system dependency (for import via the system Python), say for inclusion in upstream Debian/Ubuntu (or at a minimum just getting it to run in either of the latest releases of those distributions) then any dependent packages would need to be added from what's available via `aptitude` and be limited by whatever version that might be.

In looking at `dask`'s `setup.py` and what's available in the existing `aptitude` repos, you might also have a good chance at being able to package up the entire module directory and drop it into the Python system dist-packages directory (for 2.7, it's `/usr/lib/python2.7/dist-packages`).

Creating such a .deb archive to do this can be built reasonably quickly to test via [fpm](https://github.com/jordansissel/fpm)'s directory option with a target of where you'd like the dask module to land. Something like:
```bash
fpm -s dir -t deb -n dask -v 0.6.0 --prefix / --package dask-0.6.0.deb --deb-user root --deb-group root --architecture all -C some/directory .
```
This would change into the `some/directory` and treat it as if it's the root directory (or `/`). From here, anything you drop in it, once installed would be extracted into `/`. Creating `some/directory/usr/lib/python2.7/dist-packages/dask` and putting all of the module's goodies in it might work. For calling out additional dependencies that should be available when trying to install the .deb, they can be added to the package with `--depends`, as in: `--depends python-numpy --depends pyzmq`. It can be installed with:
```bash
dpkg -i dask-0.6.0.deb
```
And then cleanly removed with:
```bash
dpkg -i dask-0.6.0.deb
```

Finally, here are a few good links on what is even in a .deb file in case building one from scratch sounds like fun:
* https://github.com/jordansissel/fpm/wiki/DEB-Internals
* https://github.com/jordansissel/fpm/wiki/Debuild-to-fpm
* https://github.com/rholder/debinate/blob/master/debinate (:

**Comment by cowlicks** [comment]
Thanks @rholder this is great feedback.

**Comment by cowlicks** [comment]
The only dependencies not already packaged by debian are toolz, partd, and by extension locket. For now these can be bundled with dask. This is fairly cheap since they are pure python packages.

There is currently a [PR](https://github.com/pytoolz/toolz/pull/260) in toolz for creating a debian package. It could possibly be included in the debian repositories in the future.

**Comment by mrocklin** [comment]
SKImage people are on this.  Closing.
