### ISSUE TITLE
Appending categoricals fails with to_parquet

### ISSUE THREAD

**Issue by galvanist** [dask/dask#4120]
With dask[complete] `0.19.4`, fastparquet `0.1.6` and Python `3.6.6`:

```python
#!/usr/bin/env python3
# coding: utf-8

import pandas as pd
import dask.dataframe as dd
import fastparquet as fp

PARQUET_PATH = "test_parquet"
FPARQUET_PATH = "test_fparquet"

df = pd.DataFrame({"x": ["a", "a", "b", "a", "b"]})
# the following has the same behaviour as a ddf.categorize(['x'])
df["x"] = df["x"].astype("category")
ddf = dd.from_pandas(df, npartitions=1)

fp.write(FPARQUET_PATH, df)
dd.to_parquet(ddf, PARQUET_PATH)

# this succeeds:
fp.write(FPARQUET_PATH, df, append=True)

# this fails:
dd.to_parquet(ddf, PARQUET_PATH, append=True)
```

The above fails with the following error:
```
Traceback (most recent call last):
  File "categoricals_to_parquet.py", line 23, in <module>
    dd.to_parquet(ddf, PARQUET_PATH, append=True)
  File "/Users/gavin/.local/share/virtualenvs/dask_playground-wLgMaRNp/src/dask/dask/dataframe/io/parquet.py", line 1229, in to_parquet
    **kwargs)
  File "/Users/gavin/.local/share/virtualenvs/dask_playground-wLgMaRNp/src/dask/dask/dataframe/io/parquet.py", line 589, in _write_fastparquet
    set(df.dtypes.iteritems())))
ValueError: Appended dtypes differ.
{('x', CategoricalDtype(categories=['a', 'b'], ordered=False)), ('x', 'category')}
```

It appears this is a regression/recurrence of #2174

I've also tried installing from master of dask and fastparquet (as per following `pip freeze`), and was able to reproduce as above.
```
-e git+https://github.com/dask/dask@b1f06aa605dcdd801bec012bf025be12d91d5bc1#egg=dask
-e git+https://github.com/dask/fastparquet@c8457d1726bdc81fd8973a11bcb3166e8413a001#egg=fastparquet
```

**Comment by martindurant** [comment]
Yeah, on the face of it, those two dtypes do appear compatible, although should assure that the category values are the same, not just that both are categorical.

**Comment by jhb9** [comment]
I am encountering the same thing and I explicitly know the category values are the same as it's synthetically generated data.

**Comment by TomAugspurger** [comment]
Ugh this is ugly. The docs at http://pandas-docs.github.io/pandas-docs-travis/categorical.html#equality-semantics explain this a bit, but all CategoricalDtypes are equal to the string `'category'` for backwards compat.

```python
In [10]: x = pd.api.types.CategoricalDtype(['a', 'b'])

In [11]: x == 'category'
Out[11]: True
```

fastparquet is essentially comparing a set of those

```python
In [12]: {x} == {'category'}
Out[12]: False
```

which is false, I assume because of hashing differently? I'm not sure how set equality works.

Anyway, I think that fastparquet may need to read the actual CategoricalDtype from the file before comparing. I don't think this is a dask issue.

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
@TomAugspurger , do you think the following super-ugly condition captures it?
```diff
--- a/dask/dataframe/io/parquet.py
+++ b/dask/dataframe/io/parquet.py
@@ -583,7 +583,10 @@ def _write_fastparquet(df, fs, fs_token, path, write_index=None, append=False,
             raise ValueError('Appended columns not the same.\n'
                              'Previous: {} | New: {}'
                              .format(pf.columns, list(df.columns)))
-        elif set(pf.dtypes[c] for c in pf.columns) != set(df[pf.columns].dtypes):
+        elif (set(pf.dtypes[c] for c in pf.columns if pf.dtypes[c] != 'category') !=
+              set(d for d in df[pf.columns].dtypes if d != 'category') or
+              any(pf.dtypes[c] != 'category' for c in pf.columns if pf.dtypes[c] == 'category')
+              ):
```

I guess @galvanist 's case should be turned into a test.

**Comment by jakirkham** [comment]
@martindurant, any thoughts on Tom's suggestion above?

**Comment by martindurant** [comment]
Yes, I think it should be tried: we know the line to put it in, and there's a decent test at the top of the thread.

**Comment by martindurant** [comment]
This no longer fails (although you must ignore divisions int he given example)
