### ISSUE TITLE
Strange behavior when calling .index() on list containing Delayed objects

### ISSUE THREAD

**Issue by spitz-dan-l** [dask/dask#4123]
Today I encountered some surprising behavior dealing with a list containing `Delayed` objects.

Python version: 3.6.4
Dask version: 0.19.4

The minimal repro:

```
from dask import delayed

[delayed(None), None].index(None)
```

The above raises the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dspitz/miniconda3/lib/python3.6/site-packages/dask/delayed.py", line 442, in __bool__
    raise TypeError("Truth of Delayed objects is not supported")
TypeError: Truth of Delayed objects is not supported
```

I tried to investigate why this was happening and came up empty. I think it's something to do with an interaction between `list.index()` and `dask.utils.OperatorMethodMixin`. The lack of traceback frames between the error and the calling code suggests something particularly magical going on. Attempts to reproduce the issue with a minimal Delayed-like class failed.

I ran into the problem while using `toolz.partition_all()` to work through a list of `Delayed` objects. The fix was to reimplement `partition_all()` in a way that doesn't call `.index()` on a tuple containing contents of the input sequence.

Very esoteric/surprising bug! Thought it would be worth sharing.

Thank you for all you do! Huge fan!

**Comment by mrocklin** [comment]
I suspect that the `.index` method looks something like the following:

```python
def index(seq, match):
    for i, x in enumerate(seq):
        if x == match:
            return i
```

In this case `x` is a `Delayed` object, so `x == match` is a delayed object, which you shouldn't put in an if statement (we don't know yet if it is truthy or not).

I don't think that there is much we can do to fix this.  I recommend working around it, probably using something like the `is` operator instead of `==`.
