### ISSUE TITLE
Add tests for code style 

### ISSUE THREAD

**Issue by andersy005** [dask/dask#4129]
I noticed that in the [pull request template](https://github.com/dask/dask/blob/master/.github/PULL_REQUEST_TEMPLATE.md),  **Passes `flake8 dask`** is one of the points on the checklist. I am wondering whether it would add value to the project by adding a test for this using `flake8` public Python API (http://flake8.pycqa.org/en/latest/user/python-api.html). 

I'd be happy to submit a PR  if this turns out to be valuable.

**Comment by mrocklin** [comment]
We already do such a test

**Comment by andersy005** [comment]
Good! Where's it located at? I couldn't find one

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/blob/f644e7f34f23386f034a19d2b743ad0c69b79441/.travis.yml#L89

**Comment by andersy005** [comment]
Thank you @jrbourbeau, @mrocklin! I see. I was looking in the wrong location then ( I thought it was part of the unit tests).

**Comment by jrbourbeau** [comment]
You're welcome, thanks for the inquiry @andersy005!
