### ISSUE TITLE
Config parameter 'num_workers' can't be set with environment variables

### ISSUE THREAD

**Issue by djhoese** [dask/dask#4141]
In a recent commit the `num_workers` configuration setting was adding to multiprocessing/threaded schedulers. However, it uses an underscore when getting the value from the configuration object (`num_workers`). This means that the environment variable `DASK_NUM_WORKERS` can't be used to set it as environment variables have underscores converted to hyphens (`num-workers`).

The commit in question (@jrbourbeau @mrocklin ): https://github.com/dask/dask/commit/abfae43c808ad15714df8033c8be3176b1595644

Simple example proving that what it is doing won't work:

```bash
DASK_NUM_WORKERS=4 python -c "import dask; print(dask.config.get('num_workers', None)); print(dask.config.get('num-workers', None))"
None
4
```

Is num workers not supposed to be configurable from an environment variable? Otherwise, should it be changed to `num-workers` in the threaded and multiprocess schedulers?

**Comment by jrbourbeau** [comment]
Thinking about this more, we may want to have both `get` and `set` normalize underscores and hyphens to the same value. If only `get` normalizes, then you have the situation 

```python
import dask

# Assume DASK_NUM_WORKERS has been set to 2

with dask.config.set(num_worker=5):
    # Will use 2 workers
```

If only `set` normalizes then existing code like `dask.config.get('rerun_exceptions_locally')` or `dask.config.get('delayed_pure')` will break. 

When `get` and `set` both have the same normalization, both the above problems are avoided.
