### ISSUE TITLE
Use key names rather than function names in dask.visualize

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4146]
When creating task graph images we currently inspect the task graph to find functions and use those function names in the graph.  Now that atop produces `subgraph_callables` all the time, this is less informative than it used to be.  We could either dig deeper here, or we could use the keynames instead.  This is what is done in most of the other diagnostics.  It might be a good time to switch over?

cc @jcrist

**Comment by jcrist** [comment]
A few ideas:
- Use the simplified keyname (the `"foo"` in `("foo", 0)`, I think this is what you're suggesting above). This is probably fine, as most keys are generated from function names, and single function names in the graph can be misleading.
- Set the `name` field in `SubgraphCallable` in `atop`. It may be easy to generate nice names, not sure.
- Leave the circles empty - the keys are already in the rectangle, this may provide adequate information, with the circles/edges just showing dependency information.

**Comment by aberres** [comment]
I am wondering one thing: The "dask_key_name" is moved now from the data rectangles to the processing circles.
Is this really the correct representation? At least in my understanding, `dask_key_name` is the name of the outcome of the circle.

Just asking as I was confused after updating why my visualization is now "broken" (aka different on purpose).
