### ISSUE TITLE
dask.array.ma.masked_array average error

### ISSUE THREAD

**Issue by dnadeau4** [dask/dask#4163]
Workers freeze when using this code.  
 * works with other `get` functions such **as dask.threaded.get**

**Environment**
dask                      0.20.0                     py_0    conda-forge
dask-core                 0.20.0                     py_0    conda-forge
dask-glm                  0.1.0                         0    conda-forge
dask-ml                   0.11.0                     py_0    conda-forge
numpy                     1.15.3          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1  

**Code**
``` python
import numpy.ma
import numpy
import dask
import dask.array.ma
from dask.distributed import Client
from distributed.deploy.local import LocalCluster
cluster = LocalCluster()
display(cluster)
c=Client(cluster)
rand_data= numpy.random.random((20,18,365))
ma_rand_data= numpy.ma.MaskedArray(rand_data)
da_rand_data = dask.array.ma.masked_array(ma_rand_data)
dask.array.average(da_rand_data).compute()
```
**Error**
```
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/distributed-1.24.0-py2.7.egg/distributed/batched.py", line 94, in _background_send
    on_error='raise')
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/distributed-1.24.0-py2.7.egg/distributed/comm/tcp.py", line 239, in write
    future = stream.write(frame)
  File "/software/anaconda52/envs/dask-scipy/lib/python2.7/site-packages/tornado/iostream.py", line 571, in write
    if data:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by mrocklin** [comment]
Thank you for the excellent error report @dnadeau4 .  I'm able to reproduce this.  

@bjlittle @pelson any interest in investigating this error related to masked dask arrays and dask.distributed?  I'd be happy to help walk you through diagnosing things tomorrow.

**Comment by dnadeau4** [comment]
Theses three scheduler options work but not when `scheduler` is set to `None`.
The cluster is only invoke when `scheduler` is set to `None`.
**Works**
```python
print(dask.array.average(ma_rand_data).compute(scheduler='single-threaded'))
print(dask.array.average(ma_rand_data).compute(scheduler='threads'))
print(dask.array.average(ma_rand_data).compute(scheduler='processes'))
```

**Failed**
```python
print(dask.array.average(ma_rand_data).compute(scheduler=None))
```

**Comment by dkillick** [comment]
@dnadeau4 thanks indeed for raising this and explaining the issue so clearly. As it happens the origin of the issue is in `distributed`, which is why it was only the distributed scheduler (and not the dask schedulers) that was demonstrating the issue. Specifically it's the way that distributed prepares NumPy arrays for communication across a network that was particularly affecting masked arrays, due to an inconsistency in the API between NumPy ndarrays and masked arrays.

**Comment by dnadeau4** [comment]
@dkillick  Thanks for the explanation.  
I saw that `NumPy` use `pickle` calling `__getstate__`, `__setstate__` in `MaskedArray`.    

in climate we use `MaskedArray` a lot where there is no data.  An example of that is sea level pressure where they are mountains.  :smile:   For statistics it is very important.  

I will look carefully at your code,  it will certainly help me serialize my own data.

**Comment by dnadeau4** [comment]
Thanks that was great help! 
Looking at the PR changes, I was able to add my own `serializer/deserializer` by registering my `class` to dask.    :smile:

**Comment by dkillick** [comment]
@dnadeau4 nice! Now that the PR to distributed has been merged you will be able to take advantage of the new masked array serializer in distributed itself once the next release is made. 

> in climate we use `MaskedArray` a lot

As it happens, I am very aware of this! I would normally be found developing [SciTools-Iris](https://github.com/SciTools/iris), which provides a strongly CF-compliant Python data model for analysing and visualising weather and climate datasets. Iris uses dask for out-of-core data processing, and masked arrays to represent areas where there shouldn't be data, such as in your example. In fact it was integrating dask into Iris that somewhat led to dask masked arrays support, which also leads to me getting involved here!
