### ISSUE TITLE
Dask array rechunk should do intermediate sized rechunking when appropriate

### ISSUE THREAD

**Issue by shoyer** [dask/dask#417]
Consider rechunking from chunks=(1, 100) to chunks=(100, 1) on an array of shape (100, 100).

A direct rechunk operation creates ~10,000 tasks corresponding to intermediate arrays of shape (1,1).

However, if we rechunk first to shape (10,10) (the same array size as all of our chunks) and then to our final chunk shape, there would be only ~2000 tasks, because the smallest intermediate arrays have 10 elements.

I don't know what the general rules are for how to optimize rechunkings but this makes a big difference in computational efficiency -- O(n^2) vs O(n^1.5) for square arrays with a side of length n. For n=10,000, this is a ~50x speed up (assuming that the task overhead dominates for small tasks).

Credit to @freeman-lab for this idea, which apparently works really nicely in Thunder. Jeremy, if you could share how you calculate intermediate chunks sizes that would be helpful!

**Comment by mrocklin** [comment]
I've run into this with other ndarray-on-spark systems and have heard that it performs decently.

**Comment by cowlicks** [comment]
@shoyer from your description I would propose:
 given final chunk size  `n = final_chunk.size`, and the array has `ndim` number of dimensions. Then the intermediate chunks can be square, where each dimension's length is the *ndim*th root of *n*. Like `intermediate_chunk = (floor(n**(1./ndim)),) * ndim`

But I'm not familiar enough with the rechunking internals to know if this is too naive.

**Comment by shoyer** [comment]
If you do the rechunking repeatedly, each time scaling the longer chunk axis by a factor of two, you can get the number of intermediate chunks created down to O(n log(n)). OTOH, I have no idea how this scales in practice.

**Comment by cowlicks** [comment]
@shoyer I'm not sure I understand. Could you give an example?

**Comment by shoyer** [comment]
Again, suppose you have an n x n array completely chunked along one axis with chunks of size (n, 1). In the first chunking operation, create chunks of size (n/2, 2). This involves 2n intermediate arrays. Then repeat the process log(n) times, and you have your final desired chunk size of (1, n).

.

On the plus side, this involves only O(n log(n)) tasks. But you also created O(log(n)) temporary copies of the full dataset.

**Comment by shoyer** [comment]
I did a few benchmarks my machine:
http://nbviewer.ipython.org/gist/shoyer/425cb3dc9101c235fe86

For 1024 x 1024 arrays, I get a 15x speedup using one intermediate rechunking, and a 30x speedup using 3 intermediates -- bringing the calculation down from 4 minutes to 7 seconds. So it looks like a pretty clear win.

**Comment by freeman-lab** [comment]
This is very cool @shoyer ! The size estimation we've done for this kind of chunking has been more about optimizing for axis swaps in large shuffles, and in that case chunks of approximately 100-150mb have empirically proven optimal, in that smaller chunks are slower (due to increased shuffle complexity) and larger chunks run into memory issues.

The optimal sizes here clearly have different constraints, but cool that the concept proves useful!

**Comment by shoyer** [comment]
@freeman-lab Do you guys use multiple intermediates in axis swaps or just one?

**Comment by freeman-lab** [comment]
@shoyer just one... at least in Spark I'm fairly certain the time incurred just from processing the additional shuffles would outweigh any other gains, but I don't have hard numbers.

Btw, we've just about finished moving all the custom chunking logic into Bolt (https://github.com/bolt-project/bolt/pull/67), if you want to check out more of the details there.

**Comment by mrocklin** [comment]
@shoyer how do these speeds compare to just throwing the array into an empty 1024x1024 numpy array and then pulling an array with different chunks back out?  How would your benchmarks change with an array that didn't fit in memory?  Are the current scheduling routines smart enough to manage a reshuffle like this without filling up the cache and writing back to disk?

**Comment by shoyer** [comment]
> how do these speeds compare to just throwing the array into an empty 1024x1024 numpy array and then pulling an array with different chunks back out?

I'm not quite sure what you're getting at here -- I think we can safely presume that creating the 1024x1024 numpy array directly would be far, far faster.

> How would your benchmarks change with an array that didn't fit in memory?

It takes 53 seconds merely to compute the *graph* to do the naive rechunking, before any of the values are computed. Naive rechunking will be entirely unworkable for arrays that don't fit in memory.

> Are the current scheduling routines smart enough to manage a reshuffle like this without filling up the cache and writing back to disk?

My sense is that doing a full rechunking will pretty much require spilling to disk, regardless -- or distributing an array in memory across many machines.

**Comment by mrocklin** [comment]
> I'm not quite sure what you're getting at here -- I think we can safely presume that creating the 1024x1024 numpy array directly would be far, far faster.

> My sense is that doing a full rechunking will pretty much require spilling to disk, regardless -- or distributing an array in memory across many machines.

In the single machine case if this requires spilling to disk and if creating the temporary explicitly is faster then maybe the optimal approach is to explicitly store the result into a shared array and then pull out from it again.

**Comment by mrocklin** [comment]
This issue has become a bit more interesting now with distributed scheduling.  I plan to run a benchmark on a few approaches soon.

**Comment by mrocklin** [comment]
Verified that in practice with the distributed scheduler the log-based rechunking seems nicer.  I also found that an explicit `rebalance` operation after rechunking was cheap and useful.  Things tend to get a bit unbalanced during computation.  I have yet to try this on a large cluster.  

It's possible that we'll be scheduler bound.

**Comment by mrocklin** [comment]
@freeman-lab roughly what kind of performance does Thunder get on Spark for tranposing the direction of partitioning?  Do you have ballpark numbers for a common dataset shape that you often use?

**Comment by freeman-lab** [comment]
@mrocklin we're putting some numbers together now with recent versions of everything, will post here in just a bit

**Comment by mrocklin** [comment]
@freeman-lab even order-of-magnitude numbers would be really valuable here.  Something along the lines of the following would be really helpful.

*  Our data is usually shaped like 10000 by 10000000
*  A transpose of chunk shape from (10000, 1) to (1, 10000000) usually takes around 1-10 minutes on 20 m3.2xlarges

At the moment I'm currently curious if I'm anywhere in the same ballpark or not.  I'm trying to figure out how far I can get without building an explicit shuffle operation and just using task scheduling throughout.  My hope is to get a quick "nope, definitely not close" so that I know if I should continue to pursue my current path.

**Comment by mrocklin** [comment]
cc @broxtronix in case he has ballpark numbers

**Comment by freeman-lab** [comment]
@mrocklin cool gotcha so a typical medium-sized dataset for us might be (10000, 512, 512, 4), that's around ~20 GB as `uint16` and we'll often go from 10000 chunks of size (1, 1000000) to 1000000 chunks of size (10000, 1). The complete operation of loading from disk and doing the rechunking on 10 nodes might take ~2 minutes. Those numbers are from an internal cluster, which based on other benchmarking we've done might be 2-4x faster than the generic `m3`, but the exact factor there depends a lot on whether it's compute / network / io bound.

**Comment by mrocklin** [comment]
Is there a sequence of commands I can run in Thunder to do this on random data?

**Comment by mrocklin** [comment]
Do you have multiple chunks per spark partition?

**Comment by freeman-lab** [comment]
yup yup, with v1.0.0 it's as easy as

**Comment by freeman-lab** [comment]
We typically do have multiple chunks per spark partition, assuming we set the partitioning to be roughly 2-3x the number of cores, which generally gives the best performance.

**Comment by freeman-lab** [comment]
We just confirmed the 2 minutes is correct for that size on 10 nodes, also confirmed that doing the same thing for `(2000, 1000, 2000, 30)`, going from (1,60000000) chunks to (2000,1) chunks is about 10 minutes on 20 nodes.

**Comment by freeman-lab** [comment]
cc @jwittenbach who's been running these tests

**Comment by mrocklin** [comment]
Thank you.  These numbers are great.  Will crunch away on dask stuff and see how close I can get.

**Comment by freeman-lab** [comment]
cool, very curious to hear how it goes!

**Comment by mrocklin** [comment]
OK, using a cascading transpose as suggested by @shoyer we can flip around the 20GB array in roughly two minutes.  

https://gist.github.com/mrocklin/01f39076b86fe73c71c353be830e4d0f

Looking at the Dask web UI this *does* seem to take a fair amount of RAM.  It doesn't appear to be particularly sensitive to how many steps we use in the transpose-cascade.  Using only every second or third step or using significantly more partitions results in only a marginal increase (around 50%).  The scheduler is nowhere near peak when doing these operations, so we should be able to scale quite a bit larger.

The interesting thing we've learned here is that, as long as we keep the scheduler fast and pay attention to batching, it seems to be reasonable to avoid building a separate shuffle operation, at least for now.

**Comment by mrocklin** [comment]
@shoyer this might interest you: https://www.youtube.com/watch?v=W_VBpv27soU&feature=youtu.be

**Comment by shoyer** [comment]
@mrocklin Yes, interesting to see this working! I would definitely try to benchmark against Bolt on the same cluster. I would not be surprised at all if EC2 has significantly worse networking than @freeman-lab's cluster, even with enhanced networking.

**Comment by mrocklin** [comment]
I can get this down to three minutes by splitting with a finer resolution, 2**5 rather than 2**2.  This shifts burden from the network to the scheduler (fewer copies, more tasks) but the scheduler seems to be able to handle it just fine.  

I tested network bandwidth by trying `(x + x.T)` on a large square matrix and got up to around 300 MB/s steady output averaged across the network.

**Comment by shoyer** [comment]
@mrocklin Something is wrong with the formatting on your last comment.

**Comment by mrocklin** [comment]
Fixed

**Comment by shoyer** [comment]
By resolution you mean the step size for each rechunk? That makes sense.

**Comment by mrocklin** [comment]
Yeah, this chunks more finely and so accomplishes the movement in fewer stages with more tasks per stage.  We're nowhere near saturating the scheduler though (which is now quite speedy) so all is well.

**Comment by mrocklin** [comment]
Changed a couple things in the scheduler gets us down to around 2 minutes.  

Also, I realized that my test cluster didn't have any compression libraries installed.  After conda installing lz4 doing the transpose in more steps wasn't as bad, and came down to about 2.5 minutes.

In the two-step transpose I'm nowhere near saturating the bandwidth of my network.  The scheduler also doesn't appear to be particularly burdened.  Not sure where the current bottleneck is.

**Comment by mrocklin** [comment]
Actually, I just measured bandwidth by doing `x + x.T` on a large square matrix and came up with the same bandwidth measurement.  It could be that EC2 is a bit bogged down at the moment.  It would be interesting to run the above computation on a dedicated cluster.

**Comment by pitrou** [comment]
WIP heuristic implementation at https://github.com/dask/dask/pull/1737

**Comment by mrocklin** [comment]
I tried out this computation again.  Without any serious attempts to optimize we're down to slightly under a minute.  This is using 19 `n1-standard-8` machines on GCE.  The benefits here are probably a mix of nicer network handling on Dask's part and nicer infrastructure on Google's.
