### ISSUE TITLE
Series.map() passes "foo" to the function to map

### ISSUE THREAD

**Issue by semio** [dask/dask#4172]
When we map a function to a Series object, the value "foo" will be passed to the function multiple times. For example:

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: data = pd.Series(['a', 'b', 'c'])

In [4]: dictionary = {'a': 1, 'b': 2}

In [6]: data_dask = dd.from_pandas(data, npartitions=1)

In [7]: data_dask
Out[7]:
Dask Series Structure:
npartitions=1
0    object
2       ...
dtype: object
Dask Name: from_pandas, 1 tasks

In [10]: def func(v):
    ...:     if v == 'foo':
    ...:         print("foo?")
    ...:     return dictionary.get(v)
    ...:

In [13]: data_dask.map(func)
foo?
foo?
Out[13]:
Dask Series Structure:
npartitions=1
0    object
2       ...
dtype: object
Dask Name: map, 2 tasks

In [20]: data_dask.map(func).compute()
foo?
foo?
Out[20]:
0    1.0
1    2.0
2    NaN
dtype: float64
```

It shouldn't output `foo?` in the last 2 blocks because the series doesn't contain "foo"

**Comment by TomAugspurger** [comment]
See the `meta` section of the Series.map docstring:

```
If not provided, dask will try to infer the metadata.
    This may lead to unexpected results, so providing ``meta`` is
    recommended. For more information, see
    ``dask.dataframe.utils.make_meta``.
```

And http://docs.dask.org/en/latest/dataframe-design.html#metadata. So the computation is happening to create the metadata. If you specify `meta` then nothing is printed.

Are those docs sufficient to answer what's happening? Had you read http://docs.dask.org/en/latest/dataframe-design.html#metadata already?

**Comment by semio** [comment]
Ah, I see! I must have missed this part of documents. Thanks, that answers what's happening and we can close this issue :)

**Comment by mrocklin** [comment]
If you don't provide metadata about the output type of your function then
dask dataframe tries your function on a small dataframe with the same
type.  You can avoid this behavior by passing meta= .  I recommend looking
at the docstring of the map method.
