### ISSUE TITLE
pocketfft being added to NumPy/SciPy

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4188]
NumPy (and likely to follow SciPy) are looking at replacing FFTPACK with pocketfft as the library backing FFT operations. @rgommers, brought this to our attention over at pyFFTW. Am pretty sure this is a non-issue for us (especially if the NumPy API remains the same). Perhaps there may be slight differences in how precision is handled or in test results (accuracy improved). So am noting this here so that others are aware and if issues do emerge this can be a single point of discussion should any changes be needed.

xref: https://github.com/numpy/numpy/pull/11888

**Comment by jcrist** [comment]
This can be reopened if any issues actually occur, but I'd rather not have "potential future issues" in the issue tracker. Thanks for the heads up @jakirkham, closing.
