### ISSUE TITLE
Inconsistent Schema with partitioned pyarrow files

### ISSUE THREAD

**Issue by c-thiel** [dask/dask#4194]
When writing partitoned Datasets to parquet files, and it so happens that there are is a partition where one column has no values, inconsistent schemas are written to the parquet file so that reading is prevented later:

```python
import dask as da
import dask.dataframe as dd
import pandas as pd
import numpy as np
import os
import shutil

PATH_DASK = '/tmp/dask.pa'

if os.path.exists(PATH_DASK):
    shutil.rmtree(PATH_DASK)

arrays = np.array([np.array([0, 1, 2]), np.array([3, 4]), np.nan, np.nan])
strings = np.array(['a', 'b', np.nan, np.nan])

df = pd.DataFrame([0, 0, 1, 1], columns=['partition_column'])
df['arrays'] = pd.Series(arrays)
df['strings'] = pd.Series(strings)

da_df = dd.from_pandas(df, npartitions=2)
da_df.to_parquet(PATH_DASK, partition_on=['partition_column'])
dd.read_parquet(PATH_DASK)
```

Fails with:
```
ValueError: Schema in partition[partition_column=1] /tmp/dask.pa/partition_column=1/4cd3552267d84d66a5ec8764f869a13b.parquet was different. 
arrays: null
strings: string
__index_level_0__: int64
metadata
--------
...

vs

arrays: list<item: int64>
  child 0, item: int64
strings: string
__index_level_0__: int64
metadata
--------
```

I found #3454 relating to https://issues.apache.org/jira/browse/ARROW-2860. However the Pyarrow Issue only relates to reading files with different schemas. However Pyarrow in it self doesn't even suffer this Bug, as Pyarrow itself would't even write those different schemas in the first place:

```python
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
import os
import shutil

PATH_PYARROW = '/tmp/pyarrow.pa'

if os.path.exists(PATH_PYARROW):
    shutil.rmtree(PATH_PYARROW)

arrays = np.array([np.array([0, 1, 2]), np.array([3, 4]), np.nan, np.nan])
strings = np.array([np.nan, np.nan, 'a', 'b'])

df = pd.DataFrame([0, 0, 1, 1], columns=['partition_column'])
df['arrays'] = pd.Series(arrays)
df['strings'] = pd.Series(strings)

table = pa.Table.from_pandas(df)

pq.write_to_dataset(table, root_path=PATH_PYARROW, partition_cols=['partition_column'])

dataset = pq.ParquetDataset(PATH_PYARROW)
df_read = dataset.read().to_pandas()
df_read
```
Works perfectly fine. Even reading the Pyarrow Files with Dask now works perfectly fine:
`dd.read_parquet(PATH_PYARROW).compute()`

This is simply due to the reason that Pyarrow still uses the same schema accross partitions even if ther is missing data:
```python
import os
files = [val for sublist in [[os.path.join(i[0], j) for j in i[2]] for i in os.walk(PATH_PYARROW)] for val in sublist]
for file in files:
    dataset_part = pq.ParquetDataset(file)    
    print(file)
    print(dataset_part.schema)
    print(dataset_part.read().to_pandas())
```
Outputs:
```python
/tmp/pyarrow.pa/partition_column=0/f32bf0bfedcc4312829e7c4371e544e6.parquet
<pyarrow._parquet.ParquetSchema object at 0x7fdd1c103eb8>
arrays.list.item: INT64
strings: BYTE_ARRAY UTF8
__index_level_0__: INT64
 
      arrays strings
0  [0, 1, 2]     nan
1     [3, 4]     nan
/tmp/pyarrow.pa/partition_column=1/044dd125e0b5472db23bff9a954a1bff.parquet
<pyarrow._parquet.ParquetSchema object at 0x7fdd1c1034e0>
arrays.list.item: INT64
strings: BYTE_ARRAY UTF8
__index_level_0__: INT64
 
  arrays strings
2   None       a
3   None       b
```

So summing it up: In Pyarrow the `pyarrow.parquet.write_to_dataset` wrapper around `pyarrow.parquet.write_table` takes care that the schema in individual files doesn't get screwed up. Dask blindly uses `pyarrow.parquet.write_table` on each partition and hence ends up with a wrong schema.

This means that even if https://issues.apache.org/jira/browse/ARROW-2860 is fixed, loading of these wrong schemas might work, but they are still written wrongly to the file in the first place.

I believe that fixing this in dask is probably going to be hard but might still be worth a try. Maybe one simple but not ideal solution would be to to stick to the schema the first written partition produces and raise an error otherwise. At least we should make sure, that after all partitions are written to file, the schemas match. Otherwise people will save their files without an error raised and notice later on that opening is no longer possible.

**Comment by pitrou** [comment]
I'm not a Parquet expert so it's hard to say for sure. Intuitively, I'd say all files in a Parquet partition had better have the same schema, but perhaps there's a specification somewhere that spells it out?

**Comment by martindurant** [comment]
It is certainly much much better to have the same schema throughout. In some circumstances and some parquet frameworks, schema evolution is allowed, but that is not in the official spec.

**Comment by pitrou** [comment]
That said, we could add such a facility in PyArrow. Homogenizing arrays may be needed for other purposes at some point.

**Comment by wesm** [comment]
We've already had several bug reports about this, here is one:

https://issues.apache.org/jira/browse/ARROW-2860

Here is my comment from 15th September

> There's other issues reported about this. We should handle schema normalization across components of a dataset. I don't have time to work on this for 0.11 but I hope that someone else can take a look soon

In general, we need more help on Parquet support in Apache Arrow.  I think this issue can be completely solved in Python code without touching any C++

**Comment by wesm** [comment]
That being said, we should probably implement concatenation with schema normalization in C++ so it doesn't have to be redone for R and Ruby. Ruby already has Parquet support and R is not far behind

**Comment by rafonseca** [comment]
I've just run into the same problem. I understand that I can use pyarrow.parquet.write_to_dataset as a workaround, right?
But I would like to do it properly using dask API. Is someone working in this issue? Can I help?

**Comment by mmccarty** [comment]
@mrocklin @wesm Any movement on this issue?  We are running into it as well.  Please let me know if you need help.

**Comment by wesm** [comment]
Not yet. It would be great if someone could write a patch for this or contact me about paying for development work on the project. Absent these things I don't know when it will get fixed

**Comment by birdsarah** [comment]
I was having this problem too and the following, not very elegant, patch fixes it for my data:

```patch
From 396492823960544fbf7632450562908d516df069 Mon Sep 17 00:00:00 2001
From: Sarah Bird <birdsarah@mozilla.com>
Date: Sat, 20 Apr 2019 03:12:51 -0500
Subject: [PATCH 1/1] First hack to pass in schema

---
 dask/dataframe/io/parquet.py | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)

diff --git a/dask/dataframe/io/parquet.py b/dask/dataframe/io/parquet.py
index 81e2a846..8015dba9 100644
--- a/dask/dataframe/io/parquet.py
+++ b/dask/dataframe/io/parquet.py
@@ -958,7 +958,7 @@ def _read_pyarrow_parquet_piece(fs, piece, columns, index_cols, is_series,
 
 _pyarrow_write_table_kwargs = {'row_group_size', 'version', 'use_dictionary',
                                'compression', 'use_deprecated_int96_timestamps',
-                               'coerce_timestamps', 'flavor', 'chunk_size'}
+                               'coerce_timestamps', 'flavor', 'chunk_size', 'pyarrow_schema'}
 
 _pyarrow_write_metadata_kwargs = {'version', 'use_deprecated_int96_timestamps',
                                   'coerce_timestamps'}
@@ -1000,7 +1000,12 @@ def _write_partition_pyarrow(df, path, fs, filename, write_index,
                              partition_on, metadata_path=None, **kwargs):
     import pyarrow as pa
     from pyarrow import parquet
-    t = pa.Table.from_pandas(df, preserve_index=write_index)
+
+    if 'pyarrow_schema' in kwargs:
+        pyarrow_schema = kwargs.pop('pyarrow_schema')
+        t = pa.Table.from_pandas(df, preserve_index=write_index, schema=pyarrow_schema)
+    else:
+        t = pa.Table.from_pandas(df, preserve_index=write_index)
 
     if partition_on:
         parquet.write_to_dataset(t, path, partition_cols=partition_on,
-- 
2.20.1
```

I then manually create a pyarrow schema and pass it in:

```python
df.to_parquet(
    path='out.parquet',
    engine='pyarrow',
    pyarrow_schema=pa.schema([
        ('field_1', pa.string()),
        ('field_2', pa.int64()),
    ])
```

**Comment by mmccarty** [comment]
Thanks @birdsarah !  This isn't too terrible.  Do others think it would be reasonable fix this in Dask until we can get a solution at the lower level?  

Wes, I'm working on making open source contributions possible for my team.  Unfortunately, it is an uphill battle, however I am making progress.  Stay tuned!  I have folks, including myself, that would love to help out!

**Comment by martindurant** [comment]
Probably the thing to do is produce the pyarrow schema from the meta? Or does that not produce a useful schema for an empty dataframe, is that the problem? 
Being allowed to explicitly specify the schema does seem like a useful option in any case.

**Comment by birdsarah** [comment]
> Probably the thing to do is produce the pyarrow schema from the meta

@martindurant I think that sounds right. 

I'm not having an empty dataframe problem so I can't speak to that. The problem I'm having is that the schema is inferrred each time from each partition of data and attempts to specify the meta have been ignored. I have a string field that's sometimes all null for a given partition, then my individual partitions are written with different schemas and I can't read back.

I was surprised to see the meta not being used, but I also didn't know how to make a pyarrow schema from the meta data, which is why i'm hard coding the pyarrow schema. I'm already making the meta data schema and I'd prefer to not make the schema twice. 

That said, I had specified the meta data. Are there were cases where you'd get to line ~1000 above and the df would not have _meta on it.

**Comment by martindurant** [comment]
> I'm not having an empty dataframe problem

So although a dataframe should always have one, the meta is usually empty, so calling pyarrow on it directly to make a schema would produce exactly the wrong thing :|  I suppose you could always make the schema from a partition of the data that you know to be sound.
fastparquet has this problem too, and you need to, in the general case, specify how you want to interpret object columns.

**Comment by birdsarah** [comment]
>  in the general case, specify how you want to interpret object columns.

Good point. Maybe it's possible to can in the other direction then. I'm working with my initial data processing pipeline. Here's the code:

```python
dfs = [delayed(process_file)(file_name) for file_name in file_names]
df = dd.from_delayed(dfs, meta=meta)
out = df.to_parquet(
    path='out.parquet',
    engine='pyarrow',
    compression='snappy',
    pyarrow_schema=pyarrow_schema
)
```

Seems like there's potential to give a pyarrow schema to meta, as it's actually more specific, and then anything that needs to be cast as an object could be.

**Comment by birdsarah** [comment]
Obviously there's no need to optimize to my use case, just sharing.

**Comment by martindurant** [comment]
That way around is certainly possible
```
schema=pa.schema([
         ('field_1', pa.string()),
         ('field_2', pa.int64()),
     ])
pa.Table.from_pandas(pd.DataFrame(columns=schema.fields, schema=schema).to_pandas()
```
Generally, an arrow schema versus a pandas dtypes object do not map perfectly to one-another, I'm not sure you can do better; but still it may be useful to pass the arrow schema down functions like to_parquet which need direct use of them.

**Comment by birdsarah** [comment]
Thanks. Do you know how to handle categoricals?

**Comment by martindurant** [comment]
No, I really don't, sorry :| Surely someone from arrow can help with that one.

**Comment by jorisvandenbossche** [comment]
>  Do you know how to handle categoricals?

@birdsarah do you mean in light of manually creating the schema (as this is the workaround you are doing above)?

In arrow, Categoricals map to DictionaryType:

```
In [23]: cat = pd.Series(pd.Categorical(['a', 'b', 'a']))

In [24]: a = pyarrow.array(cat)

In [25]: a
Out[25]: 
<pyarrow.lib.DictionaryArray object at 0x7f0c56993ca8>

-- dictionary:
  [
    "a",
    "b"
  ]
-- indices:
  [
    0,
    1,
    0
  ]

In [26]: a.type
Out[26]: DictionaryType(dictionary<values=string, indices=int8, ordered=0>)
```

So you can create the type manually to add this to the schema (from the datatype of the indices, and the unique categories):

```
In [30]: pa.dictionary(pa.int8(), pa.array(['a', 'b']))
Out[30]: DictionaryType(dictionary<values=string, indices=int8, ordered=0>)
```

I think you should be able to get the categories from the dtype of the empty `_meta` ?

> the meta is usually empty, so calling pyarrow on it directly to make a schema would produce exactly the wrong thing :|

Indeed, when passing an empty DataFrame to arrow, it will infer all object columns as 'null' type.

**Comment by birdsarah** [comment]
@martindurant 

> `pa.Table.from_pandas(pd.DataFrame(columns=schema.fields, schema=schema)).to_pandas()`

pandas doesn't accept schema keyword

**Comment by martindurant** [comment]
I think it was meant to be 
```
pa.Table.from_pandas(pd.DataFrame(columns=schema.fields), schema=schema).to_pandas()
```

**Comment by birdsarah** [comment]
thank you!!!

**Comment by birdsarah** [comment]
Interestingly (maybe) that didn't work with timestamps because

```
~/miniconda/envs/daskyarn/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1496                             six.reraise(type(exception),
   1497                                         exception,
-> 1498                                         traceback)
   1499                     if errors == 'skip':
   1500                         bad_keys.add(key)

~/miniconda/envs/daskyarn/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/mnt/yarn/usercache/hadoop/appcache/application_1556407391758_0007/container_1556407391758_0007_01_000026/environment/lib/python3.6/site-packages/dask/dataframe/utils.py in check_meta()

ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `DataFrame`
+------------+---------------------+----------------+
| Column     | Found               | Expected       |
+------------+---------------------+----------------+
| time_stamp | datetime64[ns, UTC] | datetime64[ns] |
```
Pandas made `datetime64[ns, UTC] ` but the meta from `pa.Table.from_pandas(pd.DataFrame(columns=schema.fields), schema=schema).to_pandas()` was just `datetime64[ns] `.

**Comment by martindurant** [comment]
The implicit timezone in parquet is UTC, I don't know if arrow follows this. The implicit timezone in pandas where none is given is also UTC, so the two above could be considered equivalent.

**Comment by jreback** [comment]
> The implicit timezone in pandas where none is given is also UTC, so the two above could be considered equivalent.

this is incorrect; no time zone means it’s a naive time; this is distinct from UTC

**Comment by wesm** [comment]
> The implicit timezone in parquet is UTC, I don't know if arrow follows this. 

Timestamps in Arrow are UTC-normalized if time-zone aware. If time-zone naive, they have the same kind of interpretation that pandas gives them (https://github.com/apache/arrow/blob/master/format/Schema.fbs#L171)

**Comment by jorisvandenbossche** [comment]
> Pandas made datetime64[ns, UTC] but the meta from pa.Table.from_pandas(pd.DataFrame(columns=schema.fields), schema=schema).to_pandas() was just datetime64[ns] .

@birdsarah can you give a bit more details how you ran into this? Has your original dask dataframe a tz-aware column, but the way to create an empty `meta` as above does not match that?

**Comment by birdsarah** [comment]
@jorisvandenbossche yes, it's a bit lost in this thread. I am currently manually making a meta dataframe and a *separate* pyarrow schema. I was lamenting this and @martindurant suggested making the meta dataframe from the pyarrow schema by running `pa.Table.from_pandas(pd.DataFrame(columns=fields), schema=schema).to_pandas()` on my pyarrow schema. But it failed at the timezone step.

My pyarrow schema looks like this:

```python
pyarrow_schema = pa.schema([
    ('argument_0', pa.string()),
    ('argument_1', pa.string()),
    ('argument_2', pa.string()),
    ('argument_3', pa.string()),
    ('argument_4', pa.string()),
    ('argument_5', pa.string()),
    ('argument_6', pa.string()),
    ('argument_7', pa.string()),
    ('arguments', pa.string()),
    ('arguments_len', pa.int64()),
    ('call_stack', pa.string()),
    ('crawl_id', pa.int64()),
    ('document_url', pa.string()),
    ('event_ordinal', pa.int64()),
    ('extension_session_uuid', pa.string()),
    ('frame_id', pa.int64()),
    ('func_name', pa.string()),
    ('in_iframe', pa.bool_()),
    ('incognito', pa.int32()),
    ('operation', pa.string()),
    ('page_scopedevent_ordinal', pa.float64()),
    ('script_col', pa.int64()),
    ('script_line', pa.int64()),
    ('script_loc_eval', pa.string()),
    ('script_url', pa.string()),
    ('symbol', pa.string()),
    ('tab_id', pa.int64()),
    ('time_stamp', pa.timestamp('ns')),
    ('top_level_url', pa.string()),
    ('value', pa.string()),
    ('value_1000', pa.string()),
    ('value_len', pa.int64()),
    ('visit_id', pa.int64()),
    ('window_id', pa.int64()), 
])
```

**Comment by jorisvandenbossche** [comment]
@birdsarah you create the time stamp field with `pa.timestamp('ns')`, but if you have tz-aware data, this would need to be `pa.timestamp('ns', 'UTC')`.

That fails when creating the empty pandas DataFrame:

```
In [58]: schema = pa.schema([('timestamps', pa.timestamp('us', 'UTC'))])

In [59]: pa.Table.from_pandas(pd.DataFrame(columns=schema.names),
    ...:                      schema=schema, preserve_index=False).to_pandas()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-59-3e6fd251c01b> in <module>
----> 1 pa.Table.from_pandas(pd.DataFrame(columns=schema.names), schema=schema, preserve_index=False).to_pandas()

~/miniconda3/envs/dev37/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._PandasConvertible.to_pandas()

~/miniconda3/envs/dev37/lib/python3.7/site-packages/pyarrow/table.pxi in pyarrow.lib.Table._to_pandas()

~/miniconda3/envs/dev37/lib/python3.7/site-packages/pyarrow/pandas_compat.py in table_to_blockmanager(options, table, categories, ignore_metadata)
    600         column_indexes = pandas_metadata.get('column_indexes', [])
    601         index_descriptors = pandas_metadata['index_columns']
--> 602         table = _add_any_metadata(table, pandas_metadata)
    603         table, index = _reconstruct_index(table, index_descriptors,
    604                                           all_columns)

~/miniconda3/envs/dev37/lib/python3.7/site-packages/pyarrow/pandas_compat.py in _add_any_metadata(table, pandas_metadata)
    927                 col = table[idx]
    928                 converted = col.to_pandas()
--> 929                 tz = col_meta['metadata']['timezone']
    930                 tz_aware_type = pa.timestamp('ns', tz=tz)
    931                 with_metadata = pa.Array.from_pandas(converted.values,

TypeError: 'NoneType' object is not subscriptable
```

But that can be solved by specifying `ignore_metadata=True`
```
In [60]: pa.Table.from_pandas(pd.DataFrame(columns=schema.names),
    ...:                      schema=schema, preserve_index=False).to_pandas(ignore_metadata=True)
Out[60]: 
Empty DataFrame
Columns: [timestamps]
Index: []

In [61]: _.dtypes
Out[61]: 
timestamps    datetime64[ns, UTC]
dtype: object
```

The reason that it originally fails is because the pandas metadata that are created when converting the empty DataFrame to an arrow Table does not match the actual schema (and in case of timezone aware data, those metadata are used, but the expected timezone is not found)

**Comment by birdsarah** [comment]
Thanks. To get this issue back on track, I believe we still need a solution where dask lets you specify the schema or uses the provided metadata. I am currently running patched dask and it's not ideal.

**Comment by martindurant** [comment]
> dask lets you specify the schema

Short term, this seems to be the only solution, given the ambiguity going back and forth from pandas. I think it may be reasonable to provide a `schema=` keyword to `to_parquet` for the pyarrow branch as one of the arbitrary kwargs that gets passed to the partition-writing tasks.

**Comment by birdsarah** [comment]
I can work up a PR. I'm not sure how I would write a test for the error described here though. Perhaps we can collaborate.

**Comment by martindurant** [comment]
I guess make a dask dataframe with a zoned datetime column and no rows (or only NaT) in one partition.

**Comment by birdsarah** [comment]
The original issue here has nothing to do with datetime. That whole discussion only arised out of trying to build a shortcut and i would say it's separate if we're not going to try and infer the pyarrow schema from the already provided data to meta.

**Comment by martindurant** [comment]
OK, just thought datetime was the most complex case; the simplest case (int?) would do.

>  if we're not going to try and infer the pyarrow schema 

Right, so it seems this isn't as simple to do as I had originally hoped. It it were straight-forward, no extra options would be needed.

**Comment by birdsarah** [comment]
There's also array cases and other datatypes which i feel like i don't know enough about pyarrow to make sure are properly covered. Providing your own pyarrow schema bypasses any attempts to be clever that could fail.

**Comment by jorisvandenbossche** [comment]
So trying to summarize the different threads from the discussion above:

-  Provide a `schema=` keyword to `to_parquet` for the pyarrow branch as one of the arbitrary kwargs that gets passed to the partition-writing tasks (and we might want to do something similar in pandas' `to_parquet`). 
   This can be used as a work-around to ensure consistent schema's across partitions / multiple writes.
- On the Arrow side, schema evolution / normalization can help with dealing with such situations *when reading* parquet files with inconsistent schema's (https://issues.apache.org/jira/browse/ARROW-2659 and related issues).
-  To prevent that dask writes parquet datasets with inconsistent schema's, it should somehow infer the schema for the whole dask.dataframe, so it can enforce that when writing each partition. This, however, is not that simple to solve (the empty `meta` dataframe alone is not enough to reliably create a schema):
   - In fastparquet, this is somewhat tackled with the `object_encoding` keyword, to specify how to interpret object dtype columns (as all other column dtypes can faithfully be mapped to arrow / parquet types)

**Comment by martindurant** [comment]
That sounds like a fair summary to me. The first point should not be required if we can tackle the third (or ameliorated by the second), although maybe it's possible to get such inconsistent schemas from elsewhere.

**Comment by mmccarty** [comment]
I can take a stab at the Dask related parts summarized above, but I wanted to check first. Is anyone else working on this?

**Comment by birdsarah** [comment]
I'm not. I don't currently have time, but would LOVE to see this happen. Thanks!

**Comment by latusaki** [comment]
I have this issue with dask==2.5.2, pyarrow==0.15.0. Fastparquet does not have this problem, although I am guessing its down to the way it handles partitions.

Is there anything more clever to do than manually mapping numpy.dtypes to pa data types like the following ?: 

```
104     type_dict = {
105         "object": pa.string()
106     }
107
108     def type_map(t):
109         return type_dict[t.name] if t.name in type_dict else getattr(pa, t.name)()
110     pyarrow_types = pa.schema([(k, type_map(v)) for k, v in df.dtypes.items()])
```

**Comment by TomAugspurger** [comment]
@latusaki you could likely construct / extract a DataFrame with the correct schema and make a pyarrow.Table from that.

**Comment by latusaki** [comment]
@TomAugspurger  sadly enough, table.head() and table.tail() have different schema on my example dataframe that reproduces this issue

**Comment by ldacey** [comment]
I have something similar @latusaki. I needed to also fix my category columns and I wanted dates to be saved as pa.date32()

```
def create_pyarrow_schema(df, date_columns):
    dtypes = {
        'object': pa.string(),
        'category': pa.dictionary(index_type=pa.int16(), value_type=pa.string(), ordered=False),
        'datetime64[ns]': pa.timestamp('ns'),
        'Int64': pa.int64(),
    }

    fields = []
    for col, dtype in psd.dtypes.items():
        if col in date_columns:
            fields.append(pa.field(col, pa.date32()))

        if df[col].isnull().all():
            fields.append(pa.field(col, pa.string()))

        else:
            fields.append(pa.field(col, type_map(dtype)))

    return pa.schema(fields)
```


How can I save this to a file or something though? I want to reuse it when I read in a new file every day without reading a 'correct' version of the file first (ideally).

Can I save this to a file or print it out in a format like this which I can save in my script and edit if needed?

pyarrow_schema = pa.schema([
    ('argument_0', pa.string()),
    ('argument_1', pa.string()),
    ('argument_2', pa.string()),])

**Comment by jrbourbeau** [comment]
@ldacey I would suggest looking through the pyarrow documentation to see if there's a supported API for saving `schema` objects

**Comment by ldacey** [comment]
FYI, thanks @jorisvandenbossche  for pointing out that we can use .set() to change the data type of a field. Here is a working example:

```
pyarrow_schema = pa.Schema.from_pandas(df, preserve_index=False)

def modify_pyarrow_schema(df, schema, column, new_type):
    """
    :param df: pandas Dataframe
    :param schema: The original pyarrow schema
    :param column: The column name which needs to be assigned a different data type.
                   The column is found using .loc
    :param column: The new pyarrow data type (ex. pa.string())              

    """
    loc = df.columns.get_loc(column)
    schema = schema.set(loc, pa.field(column, new_type))

    return schema


pyarrow_schema = modify_schema(df, 
                               schema=pyarrow_schema, 
                               column='date', 
                               new_type=pa.date32())

pyarrow_schema = modify_schema(df, 
                               schema=pyarrow_schema, 
                               column='action', 
                               new_type=pa.string())
```

I'll probably just tweak that to work based off of a dictionary of columns which might need to be changed instead of changing them one by one.

I think this suffices for now but it would be nice to be able to generate a dict or list of `column: pyarrow_type` that could be saved externally:

```
# Output of pa.Schema.from_pandas() which could be saved to a file and edited:

schema = {
    'date': pa.date32(),
    'name': pa.string(),
    'is_current': pa.bool_(),
    'status': pa.dictionary(index_type=pa.int16(), value_type=pa.string(), ordered=False)),
    'effective_timestamp': pa.timestamp('ns')
}

# Turn the dict of pyarrow types into a schema to be used when writing data

fields = [pa.field(x, y) for x, y in schema.items()]
schema = pa.schema(fields)
```
