### ISSUE TITLE
Unknown data types passed to dask.delayed() are no more visualized

### ISSUE THREAD

**Issue by aberres** [dask/dask#4203]
After #4160 I think we see a regression in the visualization.

If a non-trivial object is passed to delayed it is just visualized as empty box even if a name has specified.

The example code makes not sense on its own but shows the problem:

```python
import dask

class UnknownToDask():
    pass

a = dask.delayed(UnknownToDask(), name='my class')
b = dask.delayed({}, name='my dict')

dask.delayed((a,b)).visualize()
```

The class instance passed as delayed object lost its text.

I was explicitly using `dask.delayed` here to get this description. Maybe this was the problem in the first place as things are not expected to be used this way?

Before
![image](https://user-images.githubusercontent.com/20811121/48422773-a458ea00-e75f-11e8-85b9-317ecca29624.png)

After
![image](https://user-images.githubusercontent.com/20811121/48422827-be92c800-e75f-11e8-8946-193b4279c41c.png)

**Comment by aberres** [comment]
Why am I caring at all?
In my case, I am creating a custom graph and all nodes have a well-defined name.

Some data is already known when the dask is constructed

**Comment by mrocklin** [comment]
Yes, that's correct.  See https://github.com/dask/dask/pull/4160 and #4146 for reasoning.  If you have a counterproposal that resolves those issues that would be welcome.

**Comment by jcrist** [comment]
Closing, feel free to reopen if you have a better suggestion for how we should display graphs.

**Comment by jakirkham** [comment]
cc @jni (as we were talking about this behavior a few weeks back)
