### ISSUE TITLE
Different behaviour when specifying scheduler == 'threads'

### ISSUE THREAD

**Issue by PGryllos** [dask/dask#4205]
Hi, I am using dask to parallelise a feature extraction pipeline - part of the feature extraction pipeline uses the output of a keras model. For everything so far I am using bag and df; so (based on the docs) the default scheduler is `threads`.  Weird enough if I explicitly specify the scheduler to be threads I run into an exception; specifically an exception irrelevant to dask but one that is frequently discussed as an issue when invoking  keras models in a multithread environment. Does that make sense? Is `threads` not the default scheduler and how could the behaviour change when explicitly asking for this scheduler.

Unfortunately I cannot share the feature extraction code or the model that when loaded with threads causes the exception :/

**Comment by mrocklin** [comment]
Threads is the default scheduler for dask dataframe, but multiprocessing is
the default scheduler for dask bag

**Comment by PGryllos** [comment]
@mrocklin sorry misread the doc. I noticed that specifying the 'processes' scheduler gives a measurable improvement in execution time; Is this expected or could happen as a side-effect of something?

**Comment by mrocklin** [comment]
https://docs.dask.org/en/latest/scheduling.html

> For different computations you may find better performance with
particular scheduler settings

**Comment by PGryllos** [comment]
I thought that specifying the same scheduler as the default should result in the same settings

**Comment by mrocklin** [comment]
Yes, it should

**Comment by mrocklin** [comment]
I recommend providing a minimal example.  It's quite difficult to provide meaningful assistance otherwise.

**Comment by PGryllos** [comment]
okay makes sense; I think it's clear now, I don't have anything more concrete than the following question. When your computation graph includes both dataframes and bags, can I know which scheduler is used by default?

**Comment by mrocklin** [comment]
it is defined by the final object from which you call compute.

**Comment by PGryllos** [comment]
okay, that's clear. thx a lot
