### ISSUE TITLE
Creating dask array from dask dataframe results in array without store npy option

### ISSUE THREAD

**Issue by PGryllos** [dask/dask#4213]
I am converting a dask dataframe to array using both the `to_records` and `to_dask_array` (specifying `length=True`). The resulting array doesn't seem to have the `to_npy_stack` method. Is this expected somehow? 

I am running the latest version of dask `0.20.0`

**Comment by TomAugspurger** [comment]
`to_npy_stack` is a top-level method in `dask.array`, not a method of `Array`.

http://docs.dask.org/en/latest/array-api.html#dask.array.to_npy_stack

**Comment by PGryllos** [comment]
oops sorry; thx for the quick response

**Comment by TomAugspurger** [comment]
👍
