### ISSUE TITLE
array to hdf5 fails

### ISSUE THREAD

**Issue by PGryllos** [dask/dask#4216]
I have a dataframe which columns I want to convert to arrays and store them using hdf5; the following fails

```python
s = ds.some_col.to_dask_array(lengths=True)
s.to_hdf5('myfile.hdf5', '/x')
```

with 

> TypeError: Object dtype dtype('O') has no native HDF5 equivalent

I think this error relates to storing arrays with different sizes but I assumed that using `lengths=True` will make sure to compute appropriate chunks

note: the column that I try to serialise may be a boolean column although the dataframe contains one column with variable size per row

**Comment by PGryllos** [comment]
Going a bit further into the problem I converted one the columns to instead of containing a numpy ndarray per row now contains list (which contains ndarrays). Now the error I when trying to hdf5 convertion is

> ValueError: All chunk dimensions must be positive (All chunk dimensions must be positive)

**Comment by mrocklin** [comment]
The first error says that you have python objects in your dataframe that
pandas/hdf5 doesn't know how to store into an HDF5 file.  I recommend
verifying that you can do what you want to with Pandas first, before
switching to dask dataframe.

**Comment by mrocklin** [comment]
(or dask array)

**Comment by jakirkham** [comment]
As noted above, there is not a way to serialize generic Python objects into an HDF5 file. The data will need to be transformed to something that HDF5 can handle. If you have further questions about what HDF5 supports, would suggest reaching out to [h5py]( https://github.com/h5py/h5py ) developers for help.
