### ISSUE TITLE
Dask documentation for the Dataframe.append function is wrong

### ISSUE THREAD

**Issue by lfdversluis** [dask/dask#4217]
First of all, thanks for developing this library.

I am parsing some files one by one, each returning a Dask Dataframe. At the end I would like to combine them into one dataframe before writing, thus I am using the append function. According to the [doc](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.append) it has a keyword `ignore_index` which I need to set to avoid conflicts on the indices. However, when setting this keyword you get `TypeError: append() got an unexpected keyword argument 'ignore_index'`

When I didn't set `ignore_index`, the error I got already made no sense, saying `ValueError: All inputs have known divisions which cannot be concatenated in order. Specify interleave_partitions=True to ignore order`. There is no `interleave_partitions` in the doc specified.

The code I use is 
```
final_dask_task_df = dask_data_frames[0]
for i in range(1, len(dask_data_frames)):
   final_dask_task_df.append(dask_data_frames[i])
```

Issue 2 (also wrong in the doc, but maybe better to create a separate issue? not sure). if I supply a list like `final_dask_task_df = dask_data_frames[0].append(dask_data_frames[1:])` I get `NotImplementedError: append doesn't support list or dict input`. while the doc says I can use a list for other.

**Comment by rvaidya** [comment]
Is there a recommended way to concatenate two dask dataframes?  In what situations would the .append function actually work? It seems like you'd run into this for any use case.

**Comment by mrocklin** [comment]
To concatenate two dataframes I would use the `dask.dataframe.concat` function.

**Comment by jakirkham** [comment]
Maybe I'm missing something, but is there something actionable here? Could someone please clarify? If not, should we close this issue?

**Comment by mrocklin** [comment]
With the recent update to derived_from I think that we can close docstring issues like this.

**Comment by Sharma24Rahul** [comment]
I want to append my dataframe to empty Dask DataFrame , not able to do by dd.append ? Is there anyway to do append operation . I dont want to use pandas for this

**Comment by jrbourbeau** [comment]
You can try using the `dask.dataframe.concat` function

**Comment by mrocklin** [comment]
You may also want to read through
https://docs.dask.org/en/latest/best-practices.html#load-data-with-dask
