### ISSUE TITLE
Multiple Schedulers in a cluster.

### ISSUE THREAD

**Issue by xweichu** [dask/dask#4218]
Feature Request:
We're using Dask to distribute the computation tasks to multiple servers. There is 1 dask-scheduler and 5 dask-worker servers. My question is: is there a way so that multiple dask-schedulers can be used? I'm asking this because single dask-scheduler can't avoid single point of failure, and sometimes, if the requests are in a very high volume, the single-scheduler could be a bottleneck of the performance. Do you have any plans to make this feature available in future? Or what do you think is the best practice?

**Comment by jcrist** [comment]
With the current design of dask, only a single scheduler is used. In practice this doesn't seem to be a problem for most uses, and changing it would require a large amount of work (and increased overhead). We have no current plans to make this available. Are you finding real workloads that you can *profile* and show the scheduler is the bottleneck?

**Comment by jcrist** [comment]
Closing, feel free to open new issues if you can provide reproducible examples showing performance issues.

**Comment by supadhyaya** [comment]
@jcrist sorry for commenting on the closed issue but is there a plan to allow multiple scheduler inside a dask-cluster in future ? My use case is that I want to run DAGS in dask-workers with its own virtual environment. For example, owner ABC will have a DAG file XZY which needs to run in dask-worker with its own virtual environment. And then the owner MNO will have its own DAG file PQR which needs to run in a dask-worker with a different virtual environment.  Is there a workaround for this ? Thanks.

**Comment by jcrist** [comment]
There is no plan to support this. Generally dask clusters are transient and short-lived - for your use case I suggest starting a new temporary dask cluster for each job you're running. See https://docs.dask.org/en/latest/setup.html for more on deployment options.

**Comment by supadhyaya** [comment]
thanks @jcrist for your kind reply. I was able to spin up multiple dask-yarn clusters in a single node. But what I found out is whenever I use Client(scheduler:port) to direct the DAG to the scheduler, the DAG gets passed from one scheduler to another basically creating dependency between different dask-yarn clusters. I would kindly like to ask you if there is a way to direct those DAG directly to a specific scheduler without having to relay from one scheduler to another ?

**Comment by supadhyaya** [comment]
@jcrist also, when you say to start new temporary dask clusters for each job, how exactly do you recommend to start those clusters temporarily ? currently I am spinning up clusters in the very beginning and using them without shutting them off. In this scenario I am seeing dependency between the clusters as the DAGs are passed from one main cluster to other clusters. Solution I am looking for is to direct the DAGs directly to a specific cluster without entering any intermediate cluster.
