### ISSUE TITLE
Dask Series std function returns NaN for valid array

### ISSUE THREAD

**Issue by lfdversluis** [dask/dask#4233]
When executing `memory_usage_series.std().compute()` where `memory_usage_series = task_dataframe["memory_consumption"]` I got a Warning.

```
/home/lfdversluis/miniconda3/envs/format2/lib/python3.6/site-packages/dask/compatibility.py:95: RuntimeWarning: invalid value encountered in sqrt
  return func(*args)
```

and the output is NaN.

I checked the Series and all the values are fine. They are np.int64 integers and there are no `NaN`, or `None` values in the array. If I now parse the same array directly using numpy from a pandas dataframe (on the same data, working on a subset right now), `print(task_df["memory_consumption"].values.std(dtype=np.float64))` I do get the correct output. I cannot find any reasons in the document that could case this bug. I also tried passing `dtype=np.float64` in the Dask std call, but I get the same warning and output.

**Comment by mrocklin** [comment]
Thanks for the bug report @lfdversluis .  If you're able to provide a minimal reproducible example that would help maintainers be able to identify what is wrong more quickly.

**Comment by mrocklin** [comment]
Also possibly a repeat of https://github.com/dask/dask/issues/3906

**Comment by lfdversluis** [comment]
Sure thing. I don't think it is related to #3906, there are no gaps AFAIK.
Here is a simple example:

```
import pandas as pd
import numpy as np
import dask.dataframe as dd

pandas_df = pd.read_csv("test.csv", low_memory=False, memory_map=True, engine='c', dtype={"memory_consumption": np.int64}, header=0,
                delimiter=",")

print(pandas_df['memory_consumption'].std())

dask_df = dd.from_pandas(pandas_df, npartitions=1)
print(dask_df['memory_consumption'].std().compute())
```

`test.csv`:  [test.zip](https://github.com/dask/dask/files/2607515/test.zip)

**Comment by almaleksia** [comment]
I could repro it as well.

This code returns NaN:
```python 
ddf = dd.from_pandas(pd.DataFrame({'a': [13094304034, 3489385935, 100006774]}), npartitions=2)
ddf['a'].std().compute()
```

Warning:
`compatibility.py:95: RuntimeWarning: invalid value encountered in sqrt 
return func(*args)`

When I debugged there was a negative variance passed to np.sqrt function.

Looks like it overflows in var function:
```python 
x2 = 1.0 * (num ** 2).sum(skipna=skipna, split_every=split_every)
```
Maybe smth like this can be used: https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm

**Comment by mrocklin** [comment]
@jcrist did something similar for Dask Array a while ago in
https://github.com/dask/dask/pull/297 and it seems to have worked out
well.  Doing the same for Dask DataFrame would be a nice (and possibly fun)
contribution.

**Comment by almaleksia** [comment]
@mrocklin for dask array it works, indeed :) thank you, looks interesting.
