### ISSUE TITLE
Feature Request: Support Hyperopt

### ISSUE THREAD

**Issue by superaja** [dask/dask#4238]
Hello - 

Can I request hyperopt (an SMBO based python library) be supported by dask? Currently, hyperopt authors support parallelization via Mongo that adds a layer of additional dependency.
Below is some additional information - 

hyperopt: https://github.com/hyperopt/hyperopt
documentation: http://hyperopt.github.io/hyperopt/
Current Parallelization Methods: https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB

Thanks so much for all the wonderful work! 

AD

**Comment by mrocklin** [comment]
Hi @superaja , thanks for the suggestion.  I suspect that this work would probably need to be done in the hyperopt library rather than in the dask library.  Perhaps it would be better to raise an issue there and link to that issue here?

**Comment by superaja** [comment]
Makes sense, Matt. 

Let me do it and update this thread. 

AD

**Comment by superaja** [comment]
@mrocklin - you had a comment in a hyperopt issue thread (#282) in 2017. I have updated that issue with my comment. hopefully, they can address. 

https://github.com/hyperopt/hyperopt/issues/282

AD

**Comment by jcrist** [comment]
Thanks @superaja. Closing, as this should be handled elsewhere and not in the core dask library.
