### ISSUE TITLE
Dask Groupby on Multiple Columns takes more times than plain Pandas

### ISSUE THREAD

**Issue by harshnisar** [dask/dask#4239]
code:
```
def custom(df):
    return df.smth()
ddf = dd.from_pandas(df)
ddf.groupby(['A', 'B'])['C'].apply(custom)
ddf.compute()
```

This is taking more time than just using pandas to do the ```groupby()```.

I read somewhere that this is because dask tries to index in each partition the multiple columns first and that adds to the overhead. It suggested to index the multiple columns, but dask dataframes don't support multiple index.

What I want is that groups are computed in a parallel manner using all cores.

If I just want to use the parallization of dask - I can encapsulate the function in ```delayed``` like:
```
t = df.groupby(['A','B'])['C'].apply(delayed(custom))
t = compute(t)
```

But `compute` isn't giving me the results unless I call compute on all the reducers iterating over them. That doesn't seem natural. 

What am I missing here fundamentally?

**Comment by mrocklin** [comment]
Groupby-apply can be more complex to do in parallel when the data isn't
guaranteed to fit in memory.  The algorithms that dask dataframe uses for
this operation can't be as efficient as those algorithms used by Pandas,
which can assume that the data fits in memory.

**Comment by harshnisar** [comment]
Makes sense.

What if I am done with the groupings in memory and just want each of the applies on respective groups to be parallelized. What's the right way to do that using Dask?

**Comment by TomAugspurger** [comment]
You should be able to apply a delayed func to each group: http://docs.dask.org/en/latest/delayed.html

```python
[delayed(f)(v) for for k, v in df.groupby(...)]
```
