### ISSUE TITLE
Can't make rollings with a partition size smaller than the requested window

### ISSUE THREAD

**Issue by RodrigoNeves95** [dask/dask#4248]
Right now, it's impossible to make any rolling operations (and probably other operations that I do not remember now) with a partition size smaller than the window requested.

Example:
```python
import numpy as np
import pandas as pd
import dask.dataframe as dd
import random
import fastparquet


#generate dummy df
def generate_dask_df(size):
    d = {
        'dates':
        pd.date_range('1980-01-01 00:00:00', periods=size, freq='1h'),
        'signal1':
        np.random.normal(0, 0.3, size=size).cumsum() + 50,
    }

    df = pd.DataFrame(d)

    return dd.from_pandas(df.set_index('dates'), npartitions=5)

small_df = generate_dask_df(20).repartition(freq='3h')
small_df.divisions
```
```
(Timestamp('1980-01-01 00:00:00', freq='3H'),
 Timestamp('1980-01-01 03:00:00', freq='3H'),
 Timestamp('1980-01-01 06:00:00', freq='3H'),
 Timestamp('1980-01-01 09:00:00', freq='3H'),
 Timestamp('1980-01-01 12:00:00', freq='3H'),
 Timestamp('1980-01-01 15:00:00', freq='3H'),
 Timestamp('1980-01-01 18:00:00', freq='3H'),
 Timestamp('1980-01-01 19:00:00'))
```
This works nicely
```python
small_df['signal1'].rolling('3h').mean().head()
```

this doesn't
```python
small_df['signal1'].rolling('4h').mean().head()
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-73-995569d34a2d> in <module>
----> 1 small_df['signal1'].rolling('4h').mean().head()

/usr/local/lib/python3.7/site-packages/dask/dataframe/rolling.py in mean(self)
    259     @derived_from(pd_Rolling)
    260     def mean(self):
--> 261         return self._call_method('mean')
    262 
    263     @derived_from(pd_Rolling)

/usr/local/lib/python3.7/site-packages/dask/dataframe/rolling.py in _call_method(self, method_name, *args, **kwargs)
    247         return map_overlap(pandas_rolling_method, self.obj, before, after,
    248                            rolling_kwargs, method_name, *args,
--> 249                            token=method_name, meta=meta, **kwargs)
    250 
    251     @derived_from(pd_Rolling)

/usr/local/lib/python3.7/site-packages/dask/dataframe/rolling.py in map_overlap(func, df, before, after, *args, **kwargs)
    112         deltas = pd.Series(df.divisions).diff().iloc[1:-1]
    113         if (before > deltas).any():
--> 114             raise ValueError(timedelta_partition_message)
    115         dsk.update({(name_a, i): (_tail_timedelta, (df_name, i), (df_name, i + 1), before)
    116                     for i in range(df.npartitions - 1)})

ValueError: Partition size is less than specified window. Try using ``df.repartition`` to increase the partition size
```

This is something that would be doable and that would make sense to look into it and try to change it, or it will change the internals of dask?

**Comment by mrocklin** [comment]
The challenge here is that Dask dataframe won't know how large your
partitions are likely to be when constructing the task graph for this
operation, so it will be difficult to do this automatically.

One option would be to allow the user to define the number of partitions
they want to participate in every rolling output chunk, but in practice I
think that asking them to repartition ahead of time with an informative
error message might be a good compromise.  I'm curious, are there
improvements that you think could be made to the error message that would
have helped you further?

**Comment by RodrigoNeves95** [comment]
In my opinion, the error message is very informative to the user.

Regarding only TimeDealta operations, having the knowledge of divisions we can know a priori the number of partitions necessary for the operation that we want to do. Regarding Integer operations where divisions are unknown that a whole different story because there we don't know the size of each partition. But probably it's possible to have different behaviours depending on the operation(Integer/TimeDelta)?

That is another thing that dask could maybe leverage from FastParquet metadata, that is, store the size/min/max and other statistics for each partition directly from metadata. This is probably impossible because then we would have to update this after each operation over the initial dask graph right?

**Comment by RodrigoNeves95** [comment]
#4796

**Comment by SGStino** [comment]
Seems to me like you can't make rolling windows with a partition size smaller than the requested window either?


> Partition size is less than overlapping window size. Try using ``df.repartition`` to increase the partition size.

```python
ddf.repartition(partition_size=10000).rolling(1000).apply(wma, raw=False).compute()
```

**Comment by RodrigoNeves95** [comment]
Actually, I don't think that this issue is still relevant. There was a PR https://github.com/dask/dask/commit/d53b5608781da50fffff11179f9f6e466e6315d9 that implemented the desired logic for TimeDelta operations (that it does not seem to be what you are trying to do). Since implementing this logic for other operations types seems impossible I will close this for now
