### ISSUE TITLE
TypeError: Column assignment doesn't support type DataFrame when trying to assign new column

### ISSUE THREAD

**Issue by PGryllos** [dask/dask#4264]
Hi, from looking into the available resources irt to adding a new column to dask dataframe from an array I figured sth like this should work

     import dask.dataframe as dd
     import dask.array as da

     w = dd.from_dask_array(da.from_npy_stack('/home/ubuntu/export/npy/', mmap_mode=None))

     ds = dd.read_csv('/home/ubuntu/export/export-*.csv')
     ds.assign(sensors=w)

where in `'/home/ubuntu/export/export-*.csv'` contains the csv export of a dataframe with 3 str columns and `home/ubuntu/export/npy` contains a stack of npy files that describe sensor measurements

but I get 

> TypeError: Column assignment doesn't support type DataFrame

**Comment by TomAugspurger** [comment]
I suspect that wouldn't work for pandas either. It looks like you're trying to assign a DataFrame into a DataFrame: http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.assign.html

**Comment by PGryllos** [comment]
that's quite obvious indeed :D but how does it differ from your example here https://github.com/dask/dask/issues/3866? There again a dask dataframe is created from an array and then assigned to a specific column if I am not mistaken

**Comment by GenevieveBuckley** [comment]
Closing this thread due to inactivity.
