### ISSUE TITLE
Dask community meeting, December 6th 2018

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4269]
As a reminder, this Thursday is the first Thursday of the month, and so is the Dask community developer meeting.  This generally takes place at 4pm UTC at https://appear.in/dask-dev .  I look forward to seeing people there!

**Comment by mrocklin** [comment]
Agenda document.  Currently entirely open access.  If anyone has anything that they would like to bring up then feel free to list it here (or fill it in day-of). 

https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit?usp=sharing

**Comment by jcrist** [comment]
Closing, since this has already happened.
