### ISSUE TITLE
test_s3.py failing on Travis

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#4273]
`dask/bytes/tests/test_s3.py` is failing on the Python 3.6 Travis build. Here's the traceback:

```python
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.10.0, py-1.7.0, pluggy-0.8.0 -- /home/travis/miniconda/envs/test-environment/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/dask/dask, inifile: setup.cfg
plugins: xdist-1.24.1, forked-0.2
collected 6561 items / 1 errors / 5 skipped                                    
==================================== ERRORS ====================================
_________________ ERROR collecting dask/bytes/tests/test_s3.py _________________
dask/bytes/tests/test_s3.py:10: in <module>
    moto = pytest.importorskip('moto')
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/__init__.py:8: in <module>
    from .acm import mock_acm  # flake8: noqa
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/acm/__init__.py:2: in <module>
    from .models import acm_backends
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/acm/models.py:7: in <module>
    from moto.ec2 import ec2_backends
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/ec2/__init__.py:2: in <module>
    from .models import ec2_backends
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/ec2/models.py:13: in <module>
    import boto.ec2
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/boto/__init__.py:1216: in <module>
    boto.plugin.load_plugins(config)
E   AttributeError: module 'boto' has no attribute 'plugin'
```

See https://travis-ci.org/dask/dask/jobs/463980937

**Comment by martindurant** [comment]
Boto3 appears to have been updated such that moto doesn't work with latest. Suggest pinning to previous version.

On December 5, 2018 11:13:46 PM EST, James Bourbeau <notifications@github.com> wrote:
>`dask/bytes/tests/test_s3.py` is failing on the Python 3.6 Travis
>build. Here's the traceback:
>
>```python
>============================= test session starts
>==============================
>platform linux -- Python 3.6.6, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
>-- /home/travis/miniconda/envs/test-environment/bin/python
>cachedir: .pytest_cache
>rootdir: /home/travis/build/dask/dask, inifile: setup.cfg
>plugins: xdist-1.24.1, forked-0.2
>collected 6561 items / 1 errors / 5 skipped                            
>       
>==================================== ERRORS
>====================================
>_________________ ERROR collecting dask/bytes/tests/test_s3.py
>_________________
>dask/bytes/tests/test_s3.py:10: in <module>
>    moto = pytest.importorskip('moto')
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/__init__.py:8:
>in <module>
>    from .acm import mock_acm  # flake8: noqa
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/acm/__init__.py:2:
>in <module>
>    from .models import acm_backends
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/acm/models.py:7:
>in <module>
>    from moto.ec2 import ec2_backends
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/ec2/__init__.py:2:
>in <module>
>    from .models import ec2_backends
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/moto/ec2/models.py:13:
>in <module>
>    import boto.ec2
>../../../miniconda/envs/test-environment/lib/python3.6/site-packages/boto/__init__.py:1216:
>in <module>
>    boto.plugin.load_plugins(config)
>E   AttributeError: module 'boto' has no attribute 'plugin'
>```
>
>See https://travis-ci.org/dask/dask/jobs/463980937
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/dask/issues/4273

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
There does appear to be a genuine bug also, affecting test_s3::test_open_files_write - `open_files` with `mode='wb'` and a list of paths returns only one `OpenFile`. Looking into it now.
