### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4274]
During monthly meeting today we spoke about a variety of communication mechanisms.  One was to have open office hours once a week, with some core developer attending.  

There seemed to be enough willingness among core devs to volunteer that this seems reasonable to try, at least for a month.  I propose that people who would be willing to do this during the month of January pick a week and propose a time that is convenient for them in their timezone (I think that having scattered rather than regular times here is probably ideal to match different timezones and work schedules).  We'll construct a Google Calendar and publish it on the webpage and announce it through Twitter.

The first step is to find times that work for volunteering devs.  I'll start by arbitrarily volunteering for the third week of January, and specifically January 22nd at 12:00pm US Pacific time (8pm UTC).

**Comment by martindurant** [comment]
Happy to take any of the slots, but will first wait to see if people from other time-zones than NAmerica-east will volunteer.

**Comment by jcrist** [comment]
Sure, I'll take January 10th at 10:00am US Central time.

**Comment by TomAugspurger** [comment]
@mrocklin I don't think we've promoted this yet. How about we push it back aa week?

**Comment by mrocklin** [comment]
Sure.  I've almost entirely forgotten about this :/

**Comment by mrocklin** [comment]
This didn't happen.  Closing.
