### ISSUE TITLE
Regression: map_blocks converts large np arrays to strings

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#4284]
I work on stacks of images and noticed a somewhat awkward regression from dask version 0.19.2 to 1.0.0.
Consider the following code creating a stack of shifted copies of the same image:

```python
import numpy as np
import dask.array as da
import dask

dE = 10

def shift_blocks(xshifts, image):
    result = np.stack([image] * dE)
    print("DEBUG:", image, type(image))
    # Normally go on to apply shifts by assigning to indexed np arrays
    return result

da_xshifts = da.arange(100, chunks=(dE,))

image = np.ones((354,354))
imagestack = da.map_blocks(shift_blocks, da_xshifts, image,
                          dtype=image.dtype,
                          new_axis=(1,2),
                          chunks=(dE,image.shape[0],image.shape[1]),
                         )
print(image.shape, image.dtype)
imagestack[0,...].compute()
```

This worked as expected for any size of `image` I checked under dask 0.19.2. 

However, for dask 1.0.0 the image array gets converted to a string like "ndarray-46e175ad-8db4-412f-9e55-73ee0662adc2" for _any_ size where the product of dimensions is larger than 125000, i.e. :
`np.ones((353,353))` works, `np.ones((354,354))` doesn't, 
`np.ones((1,125000))` does, `np.ones((1,125001))` doesn't.

This is probably related to #3263 , but holds here for args as well as kwargs, and there is a regression since that bug was posted as this worked before. It is suggested there that the following code is probably to blame:
https://github.com/dask/dask/blob/69ea16e388c215b6c1a849d543a690334406d2e2/dask/delayed.py#L32-L37

But git blame shows this code has not been changed in quite some time.

For this particular case I can work around it by converting `image` to a dask array as well and using broadcasting to get the sizes I want and convert to numpy array in `shift_blocks`, but as I don't find this expected behaviour I thought let's make a bug report anyways.

**Comment by TAdeJong** [comment]
I verified: it also works fine for me on #4229 . 
For completeness: this triggers if the size of the array is larger than 1e6 bytes.

**Comment by mrocklin** [comment]
This has been resolved.  Closing.
