### ISSUE TITLE
[Documentation Request] Configuration  Reference

### ISSUE THREAD

**Issue by vinayan3** [dask/dask#4286]
It would be really great if we had a page describing all of the possible configuration options. I am new to Dask. I am still figuring out the configuration options. I usually google around. It'd be great if that knowledge about the configuration settings, possible values, and explanations were centralized.  A great example of this is [Django's Settings Reference](https://docs.djangoproject.com/en/2.1/ref/settings/).

Thank you for listening.

**Comment by mrocklin** [comment]
Thanks for raising the issue @vinayan3 .

Are there options not listed in http://docs.dask.org/en/latest/configuration.html that you think should be?

Or are you asking for the config file itself, something like https://github.com/dask/distributed/blob/master/distributed/distributed.yaml for the dask.distributed library

**Comment by vinayan3** [comment]
One small one I had to dig around for and found on a git issue was:
* `temporary_directory`

The configuration page is great at describing how configuration works, where to put the values. and the precedence. However, it'd be really awesome to have all the possible options listed out on a page with explanations.

For the distributed case that would be awesome to have it as part of the docs.dask.org.

Thanks for getting back to me @mrocklin

**Comment by mrocklin** [comment]
Yes, I agree.  Given that config options can change and docs can get out of
date, I suggest that a first simple solution to this problem would be to
add links to common config files from the configuration doc page to the
various config files in the common projects (dask, distributed, jobqueue,
kubernetes, yarn, ml, ...) and then make sure that the config files
themselves are well documented with single-line explanations.

**Comment by quasiben** [comment]
cc @jcrist
