### ISSUE TITLE
Read_sql_table ufunc error

### ISSUE THREAD

**Issue by JuanPabloMF** [dask/dask#4289]
Whilst trying read_sql_table I get a somewhat obscure numpy error:

    
    import dask.dataframe as dd
    from dask.distributed import Client
    client = Client()
    connection_string = "mysql+pymysql://{user}:{password}@{host}:{port}/{database}".format(user=user, password=password, host=host, database=database, port=port)
    dd.read_sql_table(given_table_name, connection_string, index_col = 'idTx')

The error I am getting is the following:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a060bf974152> in <module>()
----> 1 dd.read_sql_table('Logger_init', connection_string, index_col = 'idTx')

~/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, head_rows, schema, meta, engine_kwargs, **kwargs)
    153             divisions[-1] = maxi
    154         else:
--> 155             divisions = np.linspace(mini, maxi, npartitions + 1).tolist()
    156 
    157     parts = []

~/miniconda3/lib/python3.6/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype)
    106     # Convert float/complex array scalars to float, gh-3504
    107     # and make sure one can use variables that have an __array_interface__, gh-6634
--> 108     start = asanyarray(start) * 1.0
    109     stop  = asanyarray(stop)  * 1.0
    110 

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```
I tried several index cols and got the same error. If I select a date column as index I get this different error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1a4e483e85a4> in <module>()
----> 1 dd.read_sql_table('Logger_init', connection_string, index_col = 'date')

```
~/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/sql.py in read_sql_table(table, uri, index_col, divisions, npartitions, limits, columns, bytes_per_chunk, head_rows, schema, meta, engine_kwargs, **kwargs)
    149             divisions = pd.date_range(
    150                 start=mini, end=maxi, freq='%iS' % (
--> 151                     (maxi - mini) / npartitions).total_seconds()).tolist()
    152             divisions[0] = mini
    153             divisions[-1] = maxi

AttributeError: 'numpy.timedelta64' object has no attribute 'total_seconds'
```

**Comment by mrocklin** [comment]
@martindurant any thoughts on this?

**Comment by martindurant** [comment]
It is datetime objects which have the `total_seconds` method, but single-item numpy datetime results like this should wrap the python object. Some sources suggest using `.item().total_seconds()`, would appreciate if you were to try it, @Juanlu001 .

**Comment by Juanlu001** [comment]
@martindurant I think you mentioned the wrong person :)

**Comment by jcorb** [comment]
I've come across this error as well, I managed to get it working by switching the order of `.total_seconds()` and `\npartitions`, i.e.
```
 divisions = pd.date_range(
                start=mini, end=maxi, freq='%iS' % (
                    (maxi - mini) / npartitions).total_seconds()).tolist()

```
becomes
```
divisions = pd.date_range(
                start=mini, end=maxi, freq='%iS' % (
                    (maxi - mini).total_seconds() / npartitions)).tolist()
```
Is that now doing what it should be?  My test case works and seems to give me what I expect.

**Comment by martindurant** [comment]
@JuanPabloMF , if you are still on this, can you try the fix above?

**Comment by AlexisMignon** [comment]
Hello,

How about other columns than the date. I run into the same problem when trying to index using a VARCHAR column.

For instance, this code fails:
```python
import pandas as pd
df = pd.DataFrame([("1", "2"), ("2", "3")], columns=['A', 'B'])
conn_string = "sqlite:///./test.db"
connect = sqlalchemy.create_engine(conn_string)
df.to_sql("test_table", connect, index=False, if_exists="replace")
dd.read_sql_table("test_table", conn_string, index_col="A")
```
Alexis

**Comment by martindurant** [comment]
This is a documentation problem rather than a bug. Unless the user specifies otherwise, Dask will try to get the min/max of the given index column, so that it can be partitioned into separate sub-queries for each chunk of the overall dataframe. If your data-type is text, there is no reasonable way to make a set of linear divisions, and that is the reason for the error you see. In this case, you will need to explicitly provide the `divisions=` keyword, with a-priori knowledge of how the index column can be split.

**Comment by martindurant** [comment]
From the docstring:

> index_col: ... If the type is number or time, then partition boundaries can be inferred from npartitions or bytes_per_chunk; otherwide must supply explicit ``divisions=``.

**Comment by jcorb** [comment]
@martindurant is the patch I'm using above the correct way to fix the bug?  I can provide a PR if required.  I also have a version that raises a `TypeError` if `divisions is None` and the type is not `M` or in `['i', 'u', 'f']` if that would be useful (I don't have access to a numeric indexed sql table to fully test that on though)

**Comment by martindurant** [comment]
@jcorb , yes I believe so; and the TypeError sounds like a good idea.
The types may be a little more subtle, because Pandas has changed the dtype API and names a few times. I think `dtype.kind` should always be a single character as you imagine.

**Comment by jcorb** [comment]
Yes, I should have been clearer -  it does check `dtype.kind`.  I have created a PR.
