### ISSUE TITLE
feature request: expose dashboard stats URL and/or variables

### ISSUE THREAD

**Issue by ebo** [dask/dask#4290]
When using dask.distributed.client on Jupyter, it creates and prints out the dashboard URL using the _repr_html_ method in client.py.  There is no easy way to get the UR, the host or hemp (bokeh) port to reconstruct the URL.  

Could we either add a dask.distributed.url containing that info, or possibly better yet add the necessary host and port info to dask.config.get('distributed.dashboard')?

Future Use Case:

I use dask.distributed both in Jupyter and in backend scripts.  I would like to 

    from dask.distributed import Client
    import logging
    ...
    if logger.level == logging.DEBUG:
       import bokeh
    client = Client()
    logger.debug(" Attach to Bokeh Dashboard via: %s"%config.dashboard.url)

or something similar, so that the dashboard of a sever side script can be attached to during debug operations.

Workaround / Initial Implementation:

I was able to implement the functionality with the following lines.  I thought I would offer it up as a use case feature request because it required reading through several bits of code to come up with the necessary information:

    info = sync(client.loop, client.scheduler.identity)
    port = info['services']['bokeh']
    host = client.scheduler.address.split('://')[1].split(':')[0]
    template = dask.config.get('distributed.dashboard.link')

    url = template.format(host=host, port=port, **os.environ)

Please note that the 'host' ID is buried in the clients 'address' and cannot be reused without parsing.  Normally I would not post a feature request in something that can be worked around with 4 lines of code.  That said, what information that is kept and exposed is not intuitive given different workflows, so it took me maybe a half hour hunting around until I found all the pieces parts,.  I am not sure how many people could easily find that info if they needed it for something.

**Comment by mrocklin** [comment]
Yes, I think it makes sense to break out the logic to a `Client.dashboard_url` method or something similar.

**Comment by mrocklin** [comment]
> thanks.

Just to be clear, I'm not promising to do this work, just agreeing with you that it would be good to have. If folks are around that would like to contribute this their work would be quite welcome.

**Comment by ebo** [comment]
On Dec 11 2018 9:01 AM, Matthew Rocklin wrote:
>> thanks.
>
> Just to be clear, I'm not promising to do this work, just agreeing
> with you that it would be good to have. If folks are around that 
> would
> like to contribute this their work would be quite welcome.

I had not interpreted it in that way, so understood.

This is small enough that I can probably submit a diff if someone does 
not beat me to it -- since I have a small workaround it is now a low 
priority, but I think useful.

**Comment by ebo** [comment]
BTW, do you prefer "Client.dashboard_url", "dask.config.get('distributed.dashboard.url')", both or something completely different?  For myself I think "Client.dashboard_url" is very clear, but looking at the naming conventions of string representation and other bits, should it be exposed with with the name 'dashboard'?  Is there any other dask context in which the name dashboard means something other than the bokeh status interface?

ex:

   str(client)
   []  "<Client: scheduler='tcp://127.0.0.1:38528' processes=8 cores=8>"

could then look like:

   [] "<Client: scheduler='tcp://127.0.0.1:38528' dashboard="http://127.0.0.1:38529/status" processes=8 cores=8>"

**Comment by ebo** [comment]
dashboard_url it is then.

**Comment by mrocklin** [comment]
To do this we need to get the port from the scheduler, this will require us to communicate a bit.  

Probably the right place to do this is in `Client._ensure_connected`

https://github.com/dask/distributed/blob/d0df3d563929061bedad1326c458fc44f6aaa57d/distributed/client.py#L896-L900

Currently that message is just `{'op': 'stream-start'}`, but we could pretty easily also add in a call to Scheduler.identity in that message.

https://github.com/dask/distributed/blob/d0df3d563929061bedad1326c458fc44f6aaa57d/distributed/scheduler.py#L250-L263

That should give us enough information to construct the dashboard url at that time.

**Comment by ebo** [comment]
Understand.  I was not sure of the best place to move the URL generation outside of the __rep_html__, but I figured that once the client is initialized it was probably OK.  I was worried that there might be other use cases where we needed to accommodate, and I am glad that you point me to them.  As a note, I am leaving tomorrow for the holidays and may be able to work on this a bit next week.

Also since I messed up not creating a branch after forking, how about we reject this PR and I'll clean that up as we move forward.

**Comment by mrocklin** [comment]
Done

**Comment by ebo** [comment]
I like the idea of adding dashboard_url to identity (assuming I 
understood you correctly).

Would it be appropriate to move the meat of the logic into the 
Scheduler.start 
<https://github.com/dask/distributed/blob/d0df3d563929061bedad1326c458fc44f6aaa57d/distributed/scheduler.py#L1102> 
to set it?

Hmmm... digging more into the code it looks like 
get_worker_service_addr could almost do it in and of itself.  I will 
have to dig into the code to see where the 'bokeh' service is 
instantiated, but it appears that the service is accessed via the worker 
and not higher.

I have to go pack and get on the road.  I will take a look at this 
again ASAP.

**Comment by mrocklin** [comment]
No, I didn't mean to suggest that we add dashboard_url to identity.  The information about the port is what you need.  It's already present in the services key.

**Comment by hristog** [comment]
Hi @mrocklin, I was about to pick this issue and have a stab at it, but it seems to me it's already been addressed in https://github.com/dask/distributed/pull/3429 (which introduces `dashboard_link`).

Could you, please, confirm if this issue can be closed as done?

**Comment by jrbourbeau** [comment]
Thanks for following up @hristog! I think you're correct that `Client.dashboard_link` takes care of this feature request -- @ebo feel free to reopen if needed
