### ISSUE TITLE
msgpack upgrade breaks dask.compute because of reduced max_array_len

### ISSUE THREAD

**Issue by teamatbotticelli** [dask/dask#4297]
Hello,

I briefly described the issue here.

https://github.com/msgpack/msgpack-python/issues/338

I can't imagine I'm the only one in this situation, I would expect this to break any dask workflow large enough.
Is there any remediation possible on the dask's side?

Thanks

**Comment by mrocklin** [comment]
Yes, I believe that this is fixed in dask/distributed master .  You might
try installing from there, or waiting for the next release.

**Comment by teamatbotticelli** [comment]
Thanks!

**Comment by jurajmichalak1** [comment]
Hello,

I'm adding part of my error output so this issue will be found easier by others:

> distributed.protocol.core - CRITICAL - Failed to deserialize ValueError: 202928 exceeds max_array_len(131072)
