### ISSUE TITLE
tensordot cannot handle >26 dimensions

### ISSUE THREAD

**Issue by jcmgray** [dask/dask#4303]
Currently ``tensordot`` is limited to tensors with 26 or fewer dimensions. Reproducing example:

```python
>>> import dask.array as da

>>> x = da.random.random([2]*26, chunks=-1)
>>> da.tensordot(x, x, 26)  # works fine
dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=()>

>>> x = da.random.random([2]*27, chunks=-1)
>>> da.tensordot(x, x, 27)  # errors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johnnie/conda/lib/python3.6/site-packages/dask/array/routines.py", line 235, in tensordot
    right_index[r] = left_index[l]
IndexError: list index out of range
```

The culprit is these lines in ``dask/array/routines.py::tensordot``
```python
    ...
    left_index = list(alphabet[:lhs.ndim])
    right_index = list(ALPHABET[:rhs.ndim])
    ...
```
Which silently slices too few characters, which are then supplied to ``atop``.

I know this sounds like quite an niche use-case! But it would actually be super useful to support this (e.g. in quantum physics where such arrays appear often) as this is the exact kind of size where memory limitations make dask's array chunking attractive/necessary.

**Comment by mrocklin** [comment]
Seems like a reasonable request to me.  Any interest in submitting a PR to help resolve this @jcmgray ?

**Comment by jcmgray** [comment]
Sure thing, I'll have a deeper look at a fix momentarily.
