### ISSUE TITLE
Feature Request for read_fwf

### ISSUE THREAD

**Issue by binaryc0de** [dask/dask#4305]
I typically work with fixed width files and read_table looks to only handle delimited files.  There doesn't appear to be a way to read fixed width files.

**Comment by TomAugspurger** [comment]
This should be doable with a bit of effort. Are you interested in working on it?

**Comment by binaryc0de** [comment]
If I thought I was qualified I would love to take a stab at it.  Unfortunately, I'm a rather new Python coder and don't feel that I could adequately handle such a task (not understanding/knowing what's under the hood of Dask).  However, another few months under my belt at development in this language I may try if it's not already being developed.  I haven't used Dask all that much yet as I couldn't figure out how to shove a fixed width file into it without going through pandas first and instead have been bench-marking my solutions using multiprocessing.  I just didn't find anyone suggesting this feature and wanted to put it out there for others to consider.

**Comment by slnguyen** [comment]
I'll try working on this issue.
