### ISSUE TITLE
Export profile data to be viewed after the cluster is closed

### ISSUE THREAD

**Issue by stuarteberg** [dask/dask#4315]
**Feature Request:** Export profile data to be viewed after the cluster is closed.

The dask dashbord's profile graph (which shows which functions took the most time) is very useful.  Yet, as far as I can tell, it cannot be viewed any more after the cluster has been shut down.  Is there any way to save that profile data for historical and/or forensic analysis?

**Comment by mrocklin** [comment]
Functions do exist to collect and transform the lower level data.  Here is a small example:

```python
from dask.distributed import Client
client = Client()
import dask
dask.datasets.timeseries().x.sum().compute()  # do some work
x = client.profile()  # the nested data structure described in the distributed/profile.py module docstring
from distributed.profile import plot_data
y = plot_data(x)  # everything necessary to turn that data into a plot
```

Ideally there would be a nice way to display this data to a user separate from a dask.distributed dashboard session.  Perhaps some of the logic in the `distributed.bokeh.components.ProfileTimePlot` class could be broken out into a standalone system?  Help with this would be welcome.

**Comment by mrocklin** [comment]
This is probably a general theme.  It would be nice to standardize saving and viewing diagnostic plots for later offline use

**Comment by andersy005** [comment]
> Perhaps some of the logic in the `distributed.bokeh.components.ProfileTimePlot` class could be broken out into a standalone system?

@mrocklin, I am interested in working on this. Let me know If I can help in any way. 
What would be the plan here? Have these components into a standalone package?

**Comment by mrocklin** [comment]
Sorry for not responding earlier @andersy005 

This has been done and is available in the [Client.profile](http://docs.dask.org/en/latest/futures.html#distributed.Client.profile) method.

It would be nice to also have a context manager solution, similar to `get_task_stream` that tracked start and end times, but I'm going to close this for now.

**Comment by andersy005** [comment]
No worries, @mrocklin! I am glad to see that this has been implemented! Thank you for mentioning `get_task_stream`, I wasn't aware this method existed.
