### ISSUE TITLE
Use Black for automatic styling

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4319]
Do we want to use an automatic style tool like [black](https://black.readthedocs.io/en/stable/)?  This tool would standardize all Python code with the repository.  This would remove conversations around style (which I think is good) but also remove flexibility that we might want at times (which might be bad).

I was pretty happy when we added `flake8` to CI.  I'm curious if adding `black` to pre-commit hooks would be a further step along this direction.

Any thoughts?

**Comment by xhochy** [comment]
I'm doing this in other projects and people are happy with it. There are sometimes things one could argue about but the automation and standardization with other projects clearly outweigh. In all these projects, we have `black` in the pre-commit hook and that helped a lot for those that actually can deal with pre-commit hooks.

**Comment by TomAugspurger** [comment]
I'd support this (and probably isort at the same time). Not having to worry about formatting at all is nice.

Though, in some cases black's formatting for manually created dask graphs is a bit ugly, e.g. most of https://github.com/dask/dask-ml/blob/master/dask_ml/model_selection/_search.py. But I think the convenience of black wins here.

**Comment by jakirkham** [comment]
This is pretty close to the style I write code in anyways. So seems fine. Agree with others that spending less bandwidth of both contributors and reviewers on style is a good thing.

The only part that gives me pause is the pre-commit hook. These are admittedly not that hard to setup. However for new contributors, it is pretty easy to miss that this is something the user needs to do beforehand. This can get more mess if say `black` isn't easily accessible when `git` runs. So having some good clear documentation on this point seems pretty important.

**Comment by mrocklin** [comment]
We've tried this out on a number of sub-projects including dask-labextension, dask-ml, dask-kubernetes, and generally it has been nice.  I plan to apply this to dask-distributed soon if there are no objections and we can see if anything comes up when having it on a larger codebase that gets more drive-by contributions.

**Comment by jrbourbeau** [comment]
@mrocklin how have things been since switching to using `black` on `dask.distributed` (ref https://github.com/dask/distributed/pull/2614)? Have any issues come up using it on a larger codebase?

**Comment by mrocklin** [comment]
Good question.  Here are some of the things I've learned:

1.  Any pending PRs will have many merge conflicts.  It would be good to make this switch only after merging/closing most pending work
2.  Git pre-commit hooks are great, but new developers probably won't use them.  We should tell them how to use black manually
3.  So far, the break in git blame history hasn't been an issue
4.  There hasn't yet been a time when I wish I could override black's decision

**Comment by jrbourbeau** [comment]
Thanks for the great feedback! 

>  It would be good to make this switch only after merging/closing most pending work

Perhaps we should have another sprint that focuses on merging/closing PRs : )

> Git pre-commit hooks are great, but new developers probably won't use them. We should tell them how to use black manually

Agreed, we should add the both `black dask` and how to set up pre-commit hooks to the "Development Guidelines"

> There hasn't yet been a time when I wish I could override black's decision

Good to know!

**Comment by mrocklin** [comment]
I think that we're at a good point to do this.  Would anyone like to do the honors?  @jrbourbeau ?

**Comment by mrocklin** [comment]
(I'm also more than happy to do this, but it can be quite satisfying, so I thought I'd offer it around :) )

**Comment by jrbourbeau** [comment]
Yeah, I can take care of `black`-ifying things

**Comment by mrocklin** [comment]
Grand.  I think it should be a matter of ...

1. Ccalling `black dask` and then committing the result
2.  Adding black to CI
3.  Adding a pre-commit config file, similar to what we have in dask-ml and distributed

**Comment by TomAugspurger** [comment]
Do people care about import sort order? If so, it’d be good to do that at the same time with isort. I don’t have a strong preference.
