### ISSUE TITLE
Who controls https://dask-doc-demo.readthedocs.io ?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4323]
Someone just pointed me to https://dask-doc-demo.readthedocs.io/en/apidocs/ .  

This appears to be an old version of our docs.  I suspect that someone set this up to test documentation but then didn't take it down.  Does anyone control this?  If so can we remove it?

**Comment by TomAugspurger** [comment]
"Edit on Github" links to https://github.com/arve0/dask/blob/apidocs/docs/source/index.rst (cc @ arve0)

**Comment by TomAugspurger** [comment]
"Edit on Github" links to https://github.com/arve0/dask/blob/apidocs/docs/source/index.rst

cc @arve0.

**Comment by mrocklin** [comment]
I've e-mailed @arve0.  He got back and said that he'll take care of it soonish.

**Comment by mrocklin** [comment]
@arve0 just confirmed that he closed it down.  Thanks!

Closing.

**Comment by arve0** [comment]
dask-doc-demo was setup to demonstrate that automatic builds of documentation is possible, some years ago: https://github.com/dask/dask/pull/231

I've closed the demo today.
