### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by x2584179909** [dask/dask#4334]
How does dask read the data in mongo?
Millions of data,
Pd. DataFrame(list(col.find({},{'_id':0}))). Look for pandas
What should I do

**Comment by TomAugspurger** [comment]
Neither dask nor pandas support reading directly from Mongo. You could try using dask.delayed and your normal pandas methods to load data in parallel (assuming mongo supports that): http://docs.dask.org/en/latest/delayed.html

**Comment by martindurant** [comment]
[`pymongo`](http://api.mongodb.com/python/current/api/pymongo/) in general will return to you a list of objects for a given query. As an example, you can see how it is used by  [intake-mongo](https://github.com/ContinuumIO/intake-mongo). However, this is not partitioned, and so a query is assumed to consist of just one piece; and the results are not necessarily homogenous, table-like. You will need to do some additional work yourself.

**Comment by TomAugspurger** [comment]
Closing. Let us know if you find any issues with the proposed solutions.
