### ISSUE TITLE
Debian Free Source Guidelines

### ISSUE THREAD

**Issue by hmaarrfk** [dask/dask#4340]
Debian seems to require the removal of 
docs/source/_static/profile.html and docs/source/_static/stacked_profile.html

XREF: https://github.com/scikit-image/scikit-image/issues/3630#issuecomment-450571993

@olebole, can you please elaborate on why? If the change isn't too obtrusive, maybe we can get those two files in line with your guidelines.

**Comment by olebole** [comment]
Reason seems that these static files download some files from bokeh, which is not in Debian:

 https://github.com/dask/dask/blob/8a97ebde4fe0c23a9f1226524567f18740485662/docs/source/_static/profile.html#L7

I have no idea, why bokeh is not packaged (maybe not freee according to our guidelines, or just no volunteer to do it); however it is doscouraged when documentation downloads third party stuff (i.e. privacy reasons). For a specific discussion, you should contact the Debian maintainer of the dask package, @detrout.

**Comment by mrocklin** [comment]
Those files are useful for our docs.  We depend pretty strongly on bokeh
for our diagnostic visualizations.  This isn't critical for packaging
though.  I think that the solution where Debian patches them out seems
great from my end.

**Comment by hmaarrfk** [comment]
Ok, thanks guys. closing as it seems status quo is fine.
