### ISSUE TITLE
It isn't obvious that the 'processes' scheduler requires 'cloudpickle'

### ISSUE THREAD

**Issue by hmaarrfk** [dask/dask#4341]
It would be nice if we told people that they could install more dependencies instead of 
```
ValueError: Expected one of [distributed, single-threaded, sync, synchronous, threading, threads]
```
which doesn't make any mention of the `'processes'` scheduler.

maybe we can add `dask[multiprocessing]` or a better warning
https://github.com/dask/dask/blob/8a97ebde4fe0c23a9f1226524567f18740485662/dask/base.py#L867

**Comment by mrocklin** [comment]
Agreed that that could be better.  I'm in favor of a better error message at runtime rather than a `dask[multiprocessing]` install option (which I think that most users aren't aware of).

Is this something that you would be willing to do @hmaarrfk ?
