### ISSUE TITLE
Dask monthly meeting 

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4347]
As a reminder, this Thursday is the first Thursday of the month, and so is the Dask community developer meeting. This generally takes place at 4pm UTC at https://appear.in/dask-dev . I look forward to seeing people there!

Agenda document. Currently entirely open access. If anyone has anything that they would like to bring up then feel free to list it here (or fill it in day-of).

https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit?usp=sharing

**Comment by TomAugspurger** [comment]
I made a public calendar event for this:

* URL: https://calendar.google.com/calendar/b/2?cid=NGwwdnRzMGMxY2dkYnE1amhjb2dqNTVzZnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

* iCal: https://calendar.google.com/calendar/ical/4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com/public/basic.ics

**Comment by jrbourbeau** [comment]
👍 thanks @TomAugspurger
