### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4355]
Do we want to participate in Google Summer of Code?  

This can be a good way to bring new developers into the project, increase diversity, and do some public service.  However it may require significant mentoring effort from individuals.  This leads us to two questions:

1.  What are good self-contained projects that a novice summer student could accomplish?
2.  Do we have people who are willing to mentor a summer student?

If we can find positive answers for 1 and 2 then we can either submit an application on our own to be a GSoC organization, or we can try to be under an umbrella organization like the PSF or PyData.

**Comment by jcrist** [comment]
> Do we have people who are willing to mentor a summer student?

Yes. I think I mentioned this in an earlier meeting, but I'd be willing to mentor a student. I've been both a participant and a mentor with SymPy in the past, and felt it was a good way to get new contributors interested in the project.

> or we can try to be under an umbrella organization like the PSF or PyData.

I think we should aim to be under an umbrella organization this first time around. For us the PSF or NumFocus would make sense.

**Comment by mrocklin** [comment]
I'm glad to hear it.  Are there topics that you would like to mentor in particular?

**Comment by franciscbalint** [comment]
> What are good self-contained projects that a novice summer student could accomplish?

If can be applied, maybe we find some synergies between the 350 issues and create the most relevant group to make a project.

> Do we have people who are willing to mentor a summer student?

If more people are needed even if they don't have relevant experience to dask, I'm interested.

**Comment by mrocklin** [comment]
One well-scoped topic would be to cythonize some internal parts of the local scheduler and see how well that improves things.  This has a chance of not being accepted, but has a pretty clear objective, an existing test suite, and would inform future work.  I think that @jcrist might also find the topic interesting.  It could expand to rewriting the local scheduler in some other language like C/C++/Rust.

**Comment by jcrist** [comment]
I've created an ideas list here: https://github.com/dask/dask/wiki/GSOC-2019-Project-Ideas. Please feel free to add ideas as you have them.

**Comment by jcrist** [comment]
Also cc @TomAugspurger in case there are Dask-ML related projects that would be good for a GSoC student.

**Comment by jcrist** [comment]
Full student instructions link: https://github.com/dask/dask/wiki/Google-Summer-of-Code-Student-Instructions

**Comment by jcrist** [comment]
The application period is now over, closing.
