### ISSUE TITLE
docs from merge wrong

### ISSUE THREAD

**Issue by jendrikjoe** [dask/dask#4358]
The dask documentation simply copies the pandas merge documentation to the dask merge function. This omits a lot of very relevant information on the dask API (especially how the repartitioning is handled in the different cases).
I am willing to update the docs. 
Just want to make sure that I can do this in the code as a "normal" docstring without breaking too much of the @derived_from(pd.DataFrame).

Cheers,

Jendrik

**Comment by mrocklin** [comment]
Yes, just drop the derived_from decorator and write a docstring as normal.

Thank you for your help with this.  It is appreciated.

**Comment by ncclementi** [comment]
Closing this issue since, this was fixed in https://github.com/dask/dask/pull/4382, and updated here https://github.com/dask/dask/pull/5685 and here https://github.com/dask/dask/pull/5531 but the issue was never close.
