### ISSUE TITLE
python dask, use disk and memory

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask#4364]
Hi All,

I ran the following code using python dask-dataframe however, I have only 4GB RAM. Hence it gives an error saying memory error. I would like to know whether dask is able to use disk rather than memory since my computer memory is less. Furthermore, when training a machine learning model we have to load the whole data at once to train the model. It cannot be parallelized (unless its an ensemble model) . So I would like to know whether it is possible to run it on disk, if not enough memory on computer (I am running the code on a single computer) All the data is from kaggle elo-merchant competition.

Here is the code:

```
merchant_headers = historical_transactions.columns.values.tolist()

for c in range(len(merchant_headers)): 
    print(merchant_headers[c])
    print('--------------------')
    print("{}".format(historical_transactions[merchant_headers[c]].value_counts().compute()) + '\n')
    print("Number of NaN values {}".format(historical_transactions[merchant_headers[c]].isnull().sum().compute()) + '\n')
```

Below is the final sections of the output:

```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.89 GB -- Worker memory limit: 4.00 GB
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f570ed9a510>, <Future finished exception=TypeError('Could not serialize object of type Series.', '2017-11-24 00:00:00    26184\n2017-11-25 00:00:00    26182\n2017-11-18 00:00:00    24498\n2017-11-30 00:00:00    24430\n2017-11-17 00:00:00    23260\n2017-11-14 00:00:00    21979\n2017-11-23 00:00:00    21830\n2017-11-29 00:00:00    21137\n2017-11-16 00:00:00    20678\n2017-11-22 00:00:00    20404\n2017-11-28 00:00:00    20122\n2017-11-21 00:00:00    19618\n2017-11-03 00:00:00    19244\n2017-11-27 00:00:00    19052\n2017-10-28 00:00:00    18712\n2017-11-04 00:00:00    18455\n2017-11-01 00:00:00    18278\n2017-11-09 00:00:00    18255\n2017-11-13 00:00:00    18177\n2017-11-08 00:00:00    17740\n2017-11-20 00:00:00    17529\n2017-11-07 00:00:00    17496\n2017-10-27 00:00:00    17295\n2017-11-15 00:00:00    16460\n2017-10-31 00:00:00    16246\n2017-11-26 00:00:00    15677\n2017-10-21 00:00:00    15536\n2017-11-19 00:00:00    15118\n2017-10-26 00:00:00    14967\n2017-11-06 00:00:00    14921\n                       ...  \n2017-09-16 00:06:58        1\n2017-09-16 00:06:57        1\n2017-09-16 00:06:53        1\n2017-09-16 00:06:50        1\n2017-09-16 00:06:48        1\n2017-09-16 00:06:44        1\n2017-09-16 00:06:43        1\n2017-09-16 00:06:38        1\n2017-09-16 00:06:36        1\n2017-09-16 00:07:19        1\n2017-09-16 00:07:25        1\n2017-09-16 00:07:26        1\n2017-09-16 00:07:53        1\n2017-09-16 00:08:17        1\n2017-09-16 00:08:16        1\n2017-09-16 00:08:15        1\n2017-09-16 00:08:12        1\n2017-09-16 00:08:09        1\n2017-09-16 00:07:59        1\n2017-09-16 00:07:56        1\n2017-09-16 00:07:50        1\n2017-09-16 00:07:32        1\n2017-09-16 00:07:49        1\n2017-09-16 00:07:48        1\n2017-09-16 00:07:39        1\n2017-09-16 00:07:38        1\n2017-09-16 00:07:37        1\n2017-09-16 00:07:36        1\n2017-09-16 00:07:33        1\n2017-01-01 00:00:08        1\nName: purchase_date, Length: 16395300, dtype: int64')>)
Traceback (most recent call last):
  File "/home/michael/env/lib/python3.5/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/home/michael/env/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/michael/env/lib/python3.5/site-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/michael/env/lib/python3.5/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/worker.py", line 2186, in memory_monitor
    k, v, weight = self.data.fast.evict()
  File "/home/michael/env/lib/python3.5/site-packages/zict/lru.py", line 90, in evict
    cb(k, v)
  File "/home/michael/env/lib/python3.5/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/home/michael/env/lib/python3.5/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/serialize.py", line 346, in serialize_bytelist
    header, frames = serialize(x, **kwargs)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/serialize.py", line 163, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type Series.', '2017-11-24 00:00:00    26184\n2017-11-25 00:00:00    26182\n2017-11-18 00:00:00    24498\n2017-11-30 00:00:00    24430\n2017-11-17 00:00:00    23260\n2017-11-14 00:00:00    21979\n2017-11-23 00:00:00    21830\n2017-11-29 00:00:00    21137\n2017-11-16 00:00:00    20678\n2017-11-22 00:00:00    20404\n2017-11-28 00:00:00    20122\n2017-11-21 00:00:00    19618\n2017-11-03 00:00:00    19244\n2017-11-27 00:00:00    19052\n2017-10-28 00:00:00    18712\n2017-11-04 00:00:00    18455\n2017-11-01 00:00:00    18278\n2017-11-09 00:00:00    18255\n2017-11-13 00:00:00    18177\n2017-11-08 00:00:00    17740\n2017-11-20 00:00:00    17529\n2017-11-07 00:00:00    17496\n2017-10-27 00:00:00    17295\n2017-11-15 00:00:00    16460\n2017-10-31 00:00:00    16246\n2017-11-26 00:00:00    15677\n2017-10-21 00:00:00    15536\n2017-11-19 00:00:00    15118\n2017-10-26 00:00:00    14967\n2017-11-06 00:00:00    14921\n                       ...  \n2017-09-16 00:06:58        1\n2017-09-16 00:06:57        1\n2017-09-16 00:06:53        1\n2017-09-16 00:06:50        1\n2017-09-16 00:06:48        1\n2017-09-16 00:06:44        1\n2017-09-16 00:06:43        1\n2017-09-16 00:06:38        1\n2017-09-16 00:06:36        1\n2017-09-16 00:07:19        1\n2017-09-16 00:07:25        1\n2017-09-16 00:07:26        1\n2017-09-16 00:07:53        1\n2017-09-16 00:08:17        1\n2017-09-16 00:08:16        1\n2017-09-16 00:08:15        1\n2017-09-16 00:08:12        1\n2017-09-16 00:08:09        1\n2017-09-16 00:07:59        1\n2017-09-16 00:07:56        1\n2017-09-16 00:07:50        1\n2017-09-16 00:07:32        1\n2017-09-16 00:07:49        1\n2017-09-16 00:07:48        1\n2017-09-16 00:07:39        1\n2017-09-16 00:07:38        1\n2017-09-16 00:07:37        1\n2017-09-16 00:07:36        1\n2017-09-16 00:07:33        1\n2017-01-01 00:00:08        1\nName: purchase_date, Length: 16395300, dtype: int64')
```

Could anyone please help me overcome this issue?

Thanks

Michael

**Comment by TomAugspurger** [comment]
> I would like to know whether dask is able to use disk rather than memory since my computer memory is less.

Dask array / dask dataframe coordinates many NumPy arrays / dask dataframes. These chunks need to fit in memory.

> Furthermore, when training a machine learning model we have to load the whole data at once to train the model.

http://ml.dask.org/incremental.html

Closing, since I don't think there's a bug to fix here. But if you read through the docs and found any of them confusing, please do send along a PR improving them.

**Comment by MichaelSchroter** [comment]
Hi Tom,

Thanks for the reply. Could you please tell me whether dask is able to utilize the hard disk of a computer (in my case a SSD) to do computation when the data is larger than memory. (I understand that Hadoop and spark are able to do it) Since some machine learning models need to use whole data set once in order to do the training. 

In a single computer case, we would be sacrificing time for practicality. I saw in the dask documentation that dask would use disk when memory is not enough. However, I do not know whether this would be automatically done or we need set some options for this such as in spark and Hadoop. It would be great if the documentation addresses this

Thanks 

Michael

**Comment by TomAugspurger** [comment]
Dask will attempt to do operations in a low memory footprint, reading data from disk as necessary. See the schedulers docs.


________________________________

**Comment by MichaelSchroter** [comment]
Hi Tom,

Would you be say what is the reason that I get the error?

My point is if dask is able to use disk like memory to use it for computation  as mentioned in the documentation of used cases, then it would be utilising more resources of the computer even though sacrificing speed.

**Comment by guillaumeeb** [comment]
Hi,

> Would you be able to say what is the reason that I get the error?

You example is two opaque to really understand what may be going wrong, you would need to make it clearer to have more feedback.

> then it would be utilizing more resources of the computer even though sacrificing speed.

Yes it can, as long as your input dataset can be accessed by chunks that fits in memory, as mentioned by @TomAugspurger.

> Also would you be able to let me know if dask is able to use GPU along with the CPU cores.

See ongoing work in https://github.com/rapidsai/dask-cudf and some blog posts http://blog.dask.org/.

**Comment by MichaelSchroter** [comment]
Hi @guillaumeeb,

As per my understanding dask creates graphs on its objects (and processes) such as dataframes and arrays according to size of memory. Hence it automatically creates chunks. How does this fit into machine learning algorithms. We know the SGDClassifier could be iteratively trained (online training). Should we think on this lines or just use the code to train any preferred algorithm that daskml has.

Thanks

Michael

**Comment by TomAugspurger** [comment]
See http://ml.dask.org/incremental.html for using dask arrays with online
learners like SGDClassifier.
