### ISSUE TITLE
Python Dask .visualize() does not show the full graph

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask#4365]
My Dask `.visualize()` does not show the graph properly. The code was taken from http://github.com/dask/dask-tutorial/ 01_dask.delayed.ipynb notebook.

I installed graphviz using pip and apt. Even though the graph is displayed, it is not fully shown. I am running the code on jupyter Lab

the code is below:

```
def inc(x):
    return x + 1

def double(x):
    return x + 2

def add(x, y):
    return x + y

data = [1, 2, 3, 4, 5]

output = []
for x in data:
    a = inc(x)
    b = double(x)
    c = add(a, b)
    output.append(c)

total = sum(output)

import dask

output = []
for x in data:
    a = dask.delayed(inc)(x)
    b = dask.delayed(double)(x)
    c = dask.delayed(add)(a, b)
    output.append(c)

total = dask.delayed(sum)(output)

total.visualize()  # see image to the right
```

I expected the boxes in the image to be also filled with data. Below is the output of the graph.

It would be great if someone could help me in this matter

![index](https://user-images.githubusercontent.com/31654102/50957411-456ee180-1512-11e9-9a45-38b6d51d5311.png)

**Comment by jcrist** [comment]
See my answer in https://github.com/dask/dask/issues/4288, this was changed intentionally in a recent release. If you have a better idea of how graphs should be visualized, feel free to suggest one in an issue.

**Comment by MichaelSchroter** [comment]
OK thank you. I thought there was something that I did not do right to get the graph from the author
