### ISSUE TITLE
Key normalization when reading config breaks logging configuration of Distributed

### ISSUE THREAD

**Issue by theMarix** [dask/dask#4366]
I wanted to configure logging using [configuration dictionary schema](
https://docs.python.org/2/library/logging.config.html#logging-config-dictschema) as it is documented in [the Dask documentation](http://distributed.dask.org/en/latest/configuration.html#logging). However, I ran into a road block. The configuration dictionary schema uses mappings to specify keyword arguments for the constructors of filters, log handlers, etc. As such, the keys of these must be valid Python identifiers and in many cases the expected arguments have underscores in their names. But, Dask replaces all underscores by hyphens when reading the configuration files. In result, logging configuration is broken the keys no longer map the expected values of the objects to be instantiated and, actually, aren't even valid Python identifiers anymore.

A somewhat minimal Dask configuration file to reproduce the issue is as follows:
```
logging:
    version: 1
    disable_existing_loggers: False
    root:
        level: INFO
        handlers:
            - gelf
    handlers:
        gelf:
            level: INFO
            class: pygelf.GelfUdpHandler
            host: localhost
            port: 31337
            include_extra_fields: True
            debug: True
            static_fields:
                _something: 11
```
In case you are wondering, host and port are obviously just dummy values. But, as we won't get as far as to send any packages this won't matter.

The example requires the following packages:
```
dask[distributed]
pygelf
```

Assuming the config is in `dask.config`, the scheduler will fail as follows:
```
$ DASK_CONFIG=dask.config dask-scheduler
Traceback (most recent call last):
  File "<redacted>/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "<redacted>/lib/python3.6/logging/config.py", line 729, in configure_handler
    kwargs = dict([(k, config[k]) for k in config if valid_ident(k)])
  File "<redacted>/lib/python3.6/logging/config.py", line 729, in <listcomp>
    kwargs = dict([(k, config[k]) for k in config if valid_ident(k)])
  File "<redacted>/lib/python3.6/logging/config.py", line 277, in valid_ident
    raise ValueError('Not a valid Python identifier: %r' % s)
ValueError: Not a valid Python identifier: 'include-extra-fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted>/bin/dask-scheduler", line 7, in <module>
    from distributed.cli.dask_scheduler import go
  File "<redacted>/lib/python3.6/site-packages/distributed/__init__.py", line 3, in <module>
    from . import config
  File "<redacted>/lib/python3.6/site-packages/distributed/config.py", line 136, in <module>
    initialize_logging(dask.config.config)
  File "<redacted>/lib/python3.6/site-packages/distributed/config.py", line 131, in initialize_logging
    _initialize_logging_new_style(config)
  File "<redacted>/lib/python3.6/site-packages/distributed/config.py", line 110, in _initialize_logging_new_style
    logging.config.dictConfig(config.get('logging'))
  File "<redacted>/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "<redacted>/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'gelf': Not a valid Python identifier: 'include-extra-fields'
```

When using legacy Python the same issue occurs, so the traceback looks somewhat different.

Sorry if this issue would have better been filed with Distributed. But I as it is an both are involved I assumed this was the proper place.

**Comment by mrocklin** [comment]
cc @jrbourbeau @djhoese

**Comment by jcrist** [comment]
I implemented your suggestion to reverse the normalized form in #4422. I still think we should only normalize declared keys (we could infer these from the default config files shipped with each library), but that's a more expansive change that could be done later.

**Comment by xiaofanyang002** [comment]
I've had a similar issue. The key normalization is causing a bug that disables existing loggers if calling `logging.config.dictConfig(dask.config.config.get('logging'))` , e.g. https://github.com/dask/distributed/blob/master/distributed/config.py#L110

Basically, setting `disable_existing_loggers: False` in dask config also does not work because the normalization will change it to `disable-existing-loggers`, which cannot be recognized by `logging.config.dictConfig` and results in existing logger being disabled.

Not sure if I followed the resolution of this issue, but it seems to me the '_' => '-' normalization still exists. Does anyone know if it can be removed for logging config? If not, what's the best approach to make disable_existing_loggers works?

More details related to "disable_existing_loggers" attribute see: https://python.readthedocs.io/en/stable/library/logging.config.html#dictionary-schema-details
