### ISSUE TITLE
dask grouping vs pandas grouping - different results?

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#4372]
(minimal example)

```python
import string
import pandas as pd
import dask.dataframe as dd
import numpy as np


N = int(100)
K = 10
choices = list(string.ascii_letters[:K])

df = pd.DataFrame({
  'a': pd.Categorical(np.random.choice(choices, N)),
  'b': np.random.choice(K, N),
  'c':  np.random.choice(5, N),
})
ddf = dd.from_pandas(df, 2)


def func(x):
   return pd.Series({'result': x['c'].max() - x['c'].min()})


a = df.groupby(['a','b']).apply(func)
meta = a.iloc[:0]
b = ddf.groupby(['a','b']).apply(func, meta=meta)

dd.utils.assert_eq(a, b)
```

```pytb
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-47-ecf5af493a9b> in <module>
     24 b = ddf.groupby(['a','b']).apply(func, meta=meta)
     25
---> 26 dd.utils.assert_eq(a, b)

~/sandbox/dask/dask/dataframe/utils.py in assert_eq(a, b, check_names, check_dtypes, check_divisions, check_index, **kwargs)
    706         a = _maybe_sort(a)
    707         b = _maybe_sort(b)
--> 708         tm.assert_frame_equal(a, b, **kwargs)
    709     elif isinstance(a, pd.Series):
    710         a = _maybe_sort(a)

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/testing.py in assert_frame_equal(left, right, check_dtype, check_index_type, check_column_type, check_frame_type, check_less_precise, check_names, by_blocks, check_exact, check_datetimelike_compat, check_categorical, check_like, obj)
   1456                             'DataFrame shape mismatch',
   1457                             '{shape!r}'.format(shape=left.shape),
-> 1458                             '{shape!r}'.format(shape=right.shape))
   1459
   1460     if check_like:

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/testing.py in raise_assert_detail(obj, message, left, right, diff)
   1092         msg += "\n[diff]: {diff}".format(diff=diff)
   1093
-> 1094     raise AssertionError(msg)
   1095
   1096

AssertionError: DataFrame are different

DataFrame shape mismatch
[left]:  (100, 1)
[right]: (200, 1)
```

---

I have same source data loaded to dask and pandas but I am getting different results in those tools. Could you please review if syntax I am using for dask is correct to corresponding pandas syntax?

# dask 1.0.0

```py
x.dtypes
#id1    category
#id2    category
#id3    category
#id4       int64
#id5       int64
#id6       int64
#v1        int64
#v2        int64
#v3      float64
#dtype: object
ans = x.groupby(['id2','id4']).apply(lambda x: pd.Series({'range_v1_v2': x['v1'].max()-x['v2'].min()}), meta={'range_v1_v2': 'int64'}).compute()
print(ans.shape)
#(80000, 1)
ans = x[['id2','id4','v1','v2']].groupby(['id2','id4']).apply(lambda x: pd.Series({'r2': x.corr()['v1']['v2']**2}), meta={'r2': 'float64'}).compute()
print(ans.shape)
#(80000, 1)
```

# pandas 0.23.4

```py
x.dtypes
#id1    category
#id2    category
#id3    category
#id4       int64
#id5       int64
#id6       int64
#v1        int64
#v2        int64
#v3      float64
#dtype: object
ans = x.groupby(['id2','id4']).apply(lambda x: pd.Series({'range_v1_v2': x['v1'].max()-x['v2'].min()}))
print(ans.shape)
#(10000, 1)
ans = x[['id2','id4','v1','v2']].groupby(['id2','id4']).apply(lambda x: pd.Series({'r2': x.corr()['v1']['v2']**2}))
print(ans.shape)
#(10000, 1)
```

To re-create data use following script
```sh
wget https://raw.githubusercontent.com/h2oai/db-benchmark/master/groupby-datagen.R
Rscript groupby-datagen.R 1e7 1e2 0 0
```

**Comment by mrocklin** [comment]
cc  @jcrist @TomAugspurger do either of you have time to look into this?

**Comment by TomAugspurger** [comment]
@jangorecki can you simplify the example at all? Is generating and reading from a CSV necessary, or can it be reproduced when creating a dask dataframe from an in-memory pandas dataframe? If you're able to simplifying things I'll hopefully be able to debug things more quickly.

**Comment by jangorecki** [comment]
@TomAugspurger following code from 2014 should work
```py
import pandas as pd
import numpy as np
import timeit

# randChar is workaround for MemoryError in mtrand.RandomState.choice
# http://stackoverflow.com/questions/25627161/how-to-solve-memory-error-in-mtrand-randomstate-choice
def randChar(f, numGrp, N) :
   things = [f%x for x in range(numGrp)]
   return [things[x] for x in np.random.choice(numGrp, N)]

def randFloat(numGrp, N) :
   things = [round(100*np.random.random(),4) for x in range(numGrp)]
   return [things[x] for x in np.random.choice(numGrp, N)]

N=int(1e9)
K=100
DF = pd.DataFrame({
  'id1' : randChar("id%03d", K, N),       # large groups (char)
  'id2' : randChar("id%03d", K, N),       # large groups (char)
  'id3' : randChar("id%010d", N//K, N),   # small groups (char)
  'id4' : np.random.choice(K, N),         # large groups (int)
  'id5' : np.random.choice(K, N),         # large groups (int)
  'id6' : np.random.choice(N//K, N),      # small groups (int)
  'v1' :  np.random.choice(5, N),         # int in range [1,5]
  'v2' :  np.random.choice(5, N),         # int in range [1,5]
  'v3' :  randFloat(100,N)                # numeric e.g. 23.5749
})
```
convert id1:id3 to categorical, then only difference should be random seed.

**Comment by TomAugspurger** [comment]
Thanks. I'll take a closer look today.

**Comment by jangorecki** [comment]
Any update on this? 1.2.0 is still returning incorrect results. Shouldn't this be labelled as high priority?

**Comment by TomAugspurger** [comment]
I haven’t had time to investigate further. Please let us know if you intend to.

**Comment by mrocklin** [comment]
cc @jcrist @jrbourbeau

**Comment by mrocklin** [comment]
@jangorecki as always, anything you can do to reduce the example to a minimal form would help enocurage others to get involved.  You can probably help most here by producing a minimal reproducible example.  Currently in order to reproduce this someone needs to download your script, install R, figure out which of the columsn are necessary, and so on, which makes it less likely that a volunteer maintainer will spend their weekend time on it.  

-  https://stackoverflow.com/help/mcve
-  https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

This is obviously asking a lot of work from you, but if you have time I'm sure it would help a lot.

**Comment by jangorecki** [comment]
@TomAugspurger (un)fortunately I am not a python developer.
@mrocklin in comments in this issue I provided python code that can be used to produce data so there is no need to download script or install R AFAIK. I understand it can take time for volunteer maintainers to address report, but I think the cases where query returns incorrect result should have reasonably higher priority over most of other issues. If there is no plans/resources to address that in near future then probably adding a warning in such case would be best. Otherwise users might take bad decisions based on incorrect answers, and that costs money.

**Comment by mrocklin** [comment]
Ah, this code:

```python
import pandas as pd
import numpy as np
import timeit

# randChar is workaround for MemoryError in mtrand.RandomState.choice
# http://stackoverflow.com/questions/25627161/how-to-solve-memory-error-in-mtrand-randomstate-choice
def randChar(f, numGrp, N) :
   things = [f%x for x in range(numGrp)]
   return [things[x] for x in np.random.choice(numGrp, N)]

def randFloat(numGrp, N) :
   things = [round(100*np.random.random(),4) for x in range(numGrp)]
   return [things[x] for x in np.random.choice(numGrp, N)]

N=int(1e7)
K=100
DF = pd.DataFrame({
  'id1' : randChar("id%03d", K, N),       # large groups (char)
  'id2' : randChar("id%03d", K, N),       # large groups (char)
  'id3' : randChar("id%010d", N//K, N),   # small groups (char)
  'id4' : np.random.choice(K, N),         # large groups (int)
  'id5' : np.random.choice(K, N),         # large groups (int)
  'id6' : np.random.choice(N//K, N),      # small groups (int)
  'v1' :  np.random.choice(5, N),         # int in range [1,5]
  'v2' :  np.random.choice(5, N),         # int in range [1,5]
  'v3' :  randFloat(100,N)                # numeric e.g. 23.5749
})

```

Are all of these columns necessary in order to reproduce the error?  Do we need 1e7 rows to reproduce the error or does the problem present itself with a smaller amount of data?

> but I think the cases where query returns incorrect result should have reasonably higher priority over most of other issues

I totally agree, and I encourage your efforts to get people to help solve the problem.  The way it was phrased before it sounded like you were saying "this is your responsibility to solve this problem".  I apologize if I misinterpretted this.

Anyway, again, if you're able to reduce your example to the minimum necessary that would be very helpful.  This is often most of the work involved in solving issues like this, and you are probably the person that is most qualified to do it.

**Comment by TomAugspurger** [comment]
> The way it was phrased before it sounded like you were saying "this is your responsibility to solve this problem". I apologize if I misinterpretted this.

Same.

I spent the last 10 minutes simplifying the example.

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np


N = int(100)
K = 10
choices = list(string.ascii_letters[:K])

df = pd.DataFrame({
  'a': pd.Categorical(np.random.choice(choices, N)),
  'b': np.random.choice(K, N),
  'c':  np.random.choice(5, N),
})
ddf = dd.from_pandas(df, 2)


def func(x):
   return pd.Series({'result': x['c'].max() - x['c'].min()})


a = df.groupby(['a','b']).apply(func)
meta = a.iloc[:0]
b = ddf.groupby(['a','b']).apply(func, meta=meta)

dd.utils.assert_eq(a, b)
```

```pytb
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-47-ecf5af493a9b> in <module>
     24 b = ddf.groupby(['a','b']).apply(func, meta=meta)
     25
---> 26 dd.utils.assert_eq(a, b)

~/sandbox/dask/dask/dataframe/utils.py in assert_eq(a, b, check_names, check_dtypes, check_divisions, check_index, **kwargs)
    706         a = _maybe_sort(a)
    707         b = _maybe_sort(b)
--> 708         tm.assert_frame_equal(a, b, **kwargs)
    709     elif isinstance(a, pd.Series):
    710         a = _maybe_sort(a)

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/testing.py in assert_frame_equal(left, right, check_dtype, check_index_type, check_column_type, check_frame_type, check_less_precise, check_names, by_blocks, check_exact, check_datetimelike_compat, check_categorical, check_like, obj)
   1456                             'DataFrame shape mismatch',
   1457                             '{shape!r}'.format(shape=left.shape),
-> 1458                             '{shape!r}'.format(shape=right.shape))
   1459
   1460     if check_like:

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/testing.py in raise_assert_detail(obj, message, left, right, diff)
   1092         msg += "\n[diff]: {diff}".format(diff=diff)
   1093
-> 1094     raise AssertionError(msg)
   1095
   1096

AssertionError: DataFrame are different

DataFrame shape mismatch
[left]:  (100, 1)
[right]: (200, 1)
```

**Comment by mrocklin** [comment]
Thanks @TomAugspurger !  You're the best.

Looks like the difference is in the handling of null values

```python
ipdb> pp len(a.result[a.result.notna()])
57
ipdb> pp len(b.result[b.result.notna()])
57
ipdb> pp len(a)
100
ipdb> pp len(b)
200
```

**Comment by jangorecki** [comment]
@mrocklin Sorry for lack of minimal example. It definitely could be smaller. I work with multiple different technologies, in result it happens that I have to report multiple issues in multiple projects. It also happened that due to lack of time (and idle machines at hand) I stopped reporting non-critical bugs/segfaults/etc (one might be even related to dask+arrow, not sure now). Example provided by @TomAugspurger looks perfect.

**Comment by mrocklin** [comment]
Yeah, it's also not your responsibility to craft a minimal example (none of us have any control over the others).  It's just the easiest way to get maintainers to do things.  If you have a chance I do recommend that you glance through [the craft minimal bug reports post](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I appreciate the work you do on comparative benchmarks.

**Comment by TomAugspurger** [comment]
I realize now that we can simplify further. The root cause is the output shape ambiguity in pandas' DataFrameGroupby.apply. `.apply` can do anything (aggregate, transform, or an entirely different shape), so it's not clear in this case whether we should do a final cross-partition aggregation.

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np


df = pd.DataFrame({
  'a': pd.Categorical(['a', 'b', 'a', 'b', 'a', 'c']),
  'b':  [1, 2, 3, 4, 5, 6],
})
ddf = dd.from_pandas(df, 2)


def func(x):
   return pd.Series({'result': x['c'].max() - x['c'].min()})

a = df.groupby('a').apply(lambda x: 1)
b = ddf.groupby('b').apply(lambda x: 1, meta='int')

dd.utils.assert_eq(a, b)
```

The outputs are

```python
In [21]: a
Out[21]:
a
a    1
b    1
c    1
dtype: int64

In [22]: b.compute()
Out[22]:
b
1    1
2    1
3    1
4    1
5    1
6    1
dtype: int64
```

So returning to the original example, we would implement that as a `dd.Aggregation`:

```python
import string
import pandas as pd
import dask.dataframe as dd
import numpy as np


N = int(100)
K = 10
choices = list(string.ascii_letters[:K])

df = pd.DataFrame({
  'a': pd.Categorical(np.random.choice(choices, N)),
  'b': pd.Categorical(np.random.choice(K, N)),
  'c':  np.random.choice(5, N),
})
ddf = dd.from_pandas(df, 2)


def func(x):
    return pd.Series({'result': x['c'].max() - x['c'].min()})


a = df.groupby(['a','b']).apply(func)


def chunk(col):
    return col.max(), col.min()


def agg(max_, min_):
    return max_.max(), min_.min()


def finalize(max_max, min_min):
    idx = pd.MultiIndex.from_product([a.index.levels[0], a.index.levels[1]],
                                     names=a.index.names)
    result = (max_max - min_min).reindex(idx)
    return result
    

agg = dd.Aggregation("extent", chunk, agg, finalize=finalize)
b = ddf.groupby(['a', 'b']).agg(agg).rename(columns={"c": "result"})

dd.utils.assert_eq(a, b)
```

A few notes:

1. Computing the extent / span is a decent example for dd.Aggregate. I'll try to turn this into a doc PR (though I may remove the Categorical aspect, as that unnecessarily complicates things I think).
2. The name of the output from `finalize` isn't respected when a Series is returned. So I needed to follow the aggregation with a `.rename`. This may be a bug.

At this point, I'm not really sure what all Dask can do here. I'm personally not a fan of pandas' groupby apply's inference on whether the user wanted to do an aggregation, transformation, or something else. We could detect whether the `.apply` aggregates, and switch modes, but that seems dicey.

**Comment by jangorecki** [comment]
Thanks for approaching this issue.
It happened that my initial report was simplified to much.
Query from my report was:
```
ans = x.groupby(['id2','id4']).apply(lambda x: pd.Series({'range_v1_v2': x['v1'].max()-x['v2'].min()}), meta={'range_v1_v2': 'int64'})
```
so `max` was taken on `v1` column, while `min` was taken on `v2` column. While simplified example uses same column. I would appreciate a comment how to address original report. Below simplified.
```py
df = pd.DataFrame({
    'id1': ['a', 'b', 'a', 'a', 'b'],
    'v1': [0, 1, 0, 2, 5],
    'v2': [2, 1, 1, 3, 5]
})
```
expected answer
```
    range2
id1
a        1
b        4
```

**Comment by TomAugspurger** [comment]
I would write this as a `.agg().assign` with both dask and pandas

```python
In [20]: df.groupby('id1').agg({'v1': 'max', 'v2': 'min'}).assign(range2=lambda x: x['v1'] - x['v2'])['range2']
Out[20]:
id1
a    1
b    4
Name: range2, dtype: int64

In [21]: ddf.groupby('id1').agg({'v1': 'max', 'v2': 'min'}).assign(range2=lambda x: x['v1'] - x['v2'])['range2'].compute()
Out[21]:
id1
a    1
b    4
Name: range2, dtype: int64
```

**Comment by jangorecki** [comment]
@TomAugspurger Thank you for your comment. It gives nice speed improvement for pandas over comparing to previous `lamba` method. It of course well cover the initially reported problem.
It happened that I have another similar query to ask against the data - calculate regression by group - where AFAIU I am not able to decompose it for atomic aggregation functions, followed by `assign`, as you did above.
I am aware of two ways to get the answer in pandas. Could you please suggest how it could be coded in dask?
`apply` is not applicable due to same reason as reported in this issue.
I cannot find any `dd.Aggregation` documentation examples ([1](https://docs.dask.org/en/latest/dataframe-groupby.html#dataframe-groupby-aggregate), [2](https://docs.dask.org/en/latest/dataframe-api.html#custom-aggregation)) where reduction function takes multiple columns on input.
```py
df = pd.DataFrame({
    'id1': ['a', 'b', 'a', 'a', 'b', 'b'],
    'v1': [0, 2, 0, 2, 5, 4],
    'v2': [2, 1, 1, 3, 6, 8]
})
df
ans1 = df.groupby('id1').corr().iloc[0::2][['v2']]**2
ans2 = df.groupby('id1').apply(lambda x: pd.Series({'v2': x.corr()['v1']['v2']**2}))
```

**Comment by TomAugspurger** [comment]
@jangorecki this would be most useful if it were implemented directly in Dask: https://github.com/dask/dask/issues/4828
