### ISSUE TITLE
Diamond fusion for blockwise operations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4373]
It would be nice to un-xfail the following test in `dask/dataframe/tests/test_optimize_dataframe.py`

```python
@pytest.mark.xfail(reason="need better high level fusion")
def test_optimize_blockwise():
    from dask.array.optimization import optimize_blockwise
    df = pd.DataFrame({'x': range(10), 'y': range(10)})
    ddf = dd.from_pandas(df, npartitions=2)

    for i in range(10):
        ddf['x'] = ddf.x + 1 + ddf.y

    graph = optimize_blockwise(ddf.dask)

    assert len(graph) <= 4
```

Usually blockwise operations (previously called atop) are fused early on at the expression level.  Unfortunately that doesn't happen with some diamond situations.  This probably requires a similar style of solution to task-based diamond fusion, but now with atop operators.

cc @jcrist @eriknw

**Comment by mrocklin** [comment]
This topic is coming up with increasing frequency in user-submitted error reports and so is probably decently high priority.

**Comment by mrocklin** [comment]
The logic to do this currently lives here

https://github.com/dask/dask/blob/72915b313e44a908931869b549b4fd3d8ac3cd88/dask/blockwise.py#L393-L477

It could probably be rewritten or improved

**Comment by eriknw** [comment]
Ping received!  I should be able to take a look at this this weekend.

**Comment by mrocklin** [comment]
Any luck @eriknw ?

**Comment by jcrist** [comment]
If not, I plan to take a look at this tomorrow.

**Comment by eriknw** [comment]
Sorry, nope, the weather was too nice and the weekend went by too quickly.

**Comment by mrocklin** [comment]
;)

**Comment by mrocklin** [comment]
Interestingly, calling `optimize_blockwise` twice may solve this particular problem.
