### ISSUE TITLE
Error while loading data from Dask Data Frame

### ISSUE THREAD

**Issue by dileep3004** [dask/dask#4377]
I am trying to Connect using Dask dataframe.read_sql_table. i am connecting to data base.But while retrieving the data from Data frame I am getting this Attribute Error.

```
**params = urllib.parse.quote_plus("Driver={ODBC Driver 17 for SQL 
Server};Server;Database;uid;pwd\")
engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)
uri=engine.url

data=dd.read_sql_table("Table", uri, index_col="index")
target=data['columns name']
target.mean().compute()**
```
error message

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-97-c293fe452774> in <module>
> ----> 1 target.mean().compute()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
>     154         dask.base.compute
>     155         """
> --> 156         (result,) = compute(self, traverse=False, **kwargs)
>     157         return result
>     158 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
>     395     keys = [x.__dask_keys__() for x in collections]
>     396     postcomputes = [x.__dask_postcompute__() for x in collections]
> --> 397     results = schedule(dsk, keys, **kwargs)
>     398     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
>     399 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\threaded.py in get(dsk, result, cache, num_workers, **kwargs)
>      74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
>      75                         cache=cache, get_id=_thread_get_id,
> ---> 76                         pack_exception=pack_exception, **kwargs)
>      77 
>      78     # Cleanup pools associated to dead threads
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
>     499                         _execute_task(task, data)  # Re-execute locally
>     500                     else:
> --> 501                         raise_exception(exc, tb)
>     502                 res, worker_id = loads(res_info)
>     503                 state['cache'][key] = res
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\compatibility.py in reraise(exc, tb)
>     110         if exc.__traceback__ is not tb:
>     111             raise exc.with_traceback(tb)
> --> 112         raise exc
>     113 
>     114 else:
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
>     270     try:
>     271         task, data = loads(task_info)
> --> 272         result = _execute_task(task, data)
>     273         id = get_id()
>     274         result = dumps((result, id))
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in _execute_task(arg, cache, dsk)
>     250     elif istask(arg):
>     251         func, args = arg[0], arg[1:]
> --> 252         args2 = [_execute_task(a, cache) for a in args]
>     253         return func(*args2)
>     254     elif not ishashable(arg):
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in <listcomp>(.0)
>     250     elif istask(arg):
>     251         func, args = arg[0], arg[1:]
> --> 252         args2 = [_execute_task(a, cache) for a in args]
>     253         return func(*args2)
>     254     elif not ishashable(arg):
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in _execute_task(arg, cache, dsk)
>     250     elif istask(arg):
>     251         func, args = arg[0], arg[1:]
> --> 252         args2 = [_execute_task(a, cache) for a in args]
>     253         return func(*args2)
>     254     elif not ishashable(arg):
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in <listcomp>(.0)
>     250     elif istask(arg):
>     251         func, args = arg[0], arg[1:]
> --> 252         args2 = [_execute_task(a, cache) for a in args]
>     253         return func(*args2)
>     254     elif not ishashable(arg):
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\local.py in _execute_task(arg, cache, dsk)
>     251         func, args = arg[0], arg[1:]
>     252         args2 = [_execute_task(a, cache) for a in args]
> --> 253         return func(*args2)
>     254     elif not ishashable(arg):
>     255         return arg
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\compatibility.py in apply(func, args, kwargs)
>      91     def apply(func, args, kwargs=None):
>      92         if kwargs:
> ---> 93             return func(*args, **kwargs)
>      94         else:
>      95             return func(*args)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\io\sql.py in _read_sql_chunk(q, uri, meta, **kwargs)
>     167 
>     168 def _read_sql_chunk(q, uri, meta, **kwargs):
> --> 169     df = pd.read_sql(q, uri, **kwargs)
>     170     if df.empty:
>     171         return meta
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
>     379             sql, index_col=index_col, params=params,
>     380             coerce_float=coerce_float, parse_dates=parse_dates,
> --> 381             chunksize=chunksize)
>     382 
>     383     try:
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
>    1411 
>    1412         args = _convert_params(sql, params)
> -> 1413         cursor = self.execute(*args)
>    1414         columns = [col_desc[0] for col_desc in cursor.description]
>    1415 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
>    1371             cur = self.con
>    1372         else:
> -> 1373             cur = self.con.cursor()
>    1374         try:
>    1375             if kwargs:
> 
> AttributeError: 'URL' object has no attribute 'cursor'

**Comment by martindurant** [comment]
> engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)

This doesn't look right; you should not be creating your own engine, but passing in the URI (the thing you use as the argument here), rather than some internal attribute.

**Comment by TomAugspurger** [comment]
Does passing `str(engine.url)` rather than `engine.url` work?

**Comment by dileep3004** [comment]
> Does passing `str(engine.url)` rather than `engine.url` work?

No it's not working

**Comment by dileep3004** [comment]
> > engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)
> 
> This doesn't look right; you should not be creating your own engine, but passing in the URI (the thing you use as the argument here), rather than some internal attribute.

Can you tell me how to create that Uri String

**Comment by dileep3004** [comment]
i am done with it
i had used this connection string
connection_string = "mssql+pymssql://{user}:{password}@{host}:{port}/{database}".format(user=user, password=password, host=host, database=database, port=port)


Thank you for your support

**Comment by knitinsingh** [comment]
Hi, i am unable to figure out the dask connection.
Can you please elaborate, what is uri string. It would be great if you can give an example.

**Comment by mrocklin** [comment]
I think that @dileep3004 means something like this

```
connection_string = "mssql+pymssql://{user}:{password}@{host}:{port}/{database}".format(user=user, password=password, host=host, database=database, port=port)
```

Please see the SQLAlchemy documentation for more information.
