### ISSUE TITLE
Dataframe . to_parquet  with compute=False writes wrong data when apply operation is present

### ISSUE THREAD

**Issue by bgoodman44** [dask/dask#4390]
Hello all,

I believe I've uncovered a bug in df.to_parquet(path,compute=False) when df has had an apply operation administered upon it, and the computation occurs within a loop.  If the apply operation is removed, or compute is set to True, everything works fine.  If i persist the df after the apply operation, it works...but my real-life use case has a dataset of a couple hundred gbs, so I don't have enough ram to persist the df.

Any ideas or workarounds?

```
import pandas as pd
import dask.dataframe as dd
from dask import distributed
from time import sleep
client = distributed.Client()

df = dd.from_pandas(  pd.DataFrame({'A':[1,2]}) ,npartitions=1 )
```
```
def SplitAndWrite(df):
    #If this line is removed..it works
    df['B'] = df.apply(lambda row: row.A*2,axis=1,meta=(None,int))
   #df =  client.persist(df); # This makes things work, but I don't want to run out of memory!
    
    un = df.A.unique().compute();
    newDf = dict();
    writeTask = dict();
    for aa in un.values:
        print(aa)
        newDf[aa] = df[df.A == aa]
         
         #Direct computation works, I.E compute=True
#         writeTask[aa]  = newDf[aa].to_parquet('./OUT/' + str(aa) +'/') 
        
        writeTask[aa]  = client.persist(
            newDf[aa].to_parquet('./OUT/' + str(aa) +'/',compute=False),
        )
    return newDf,writeTask
```

```
newDf,writeTask = SplitAndWrite(df)
sleep(5) # sleeping to let client finish...
 #One or more of the out files will be wrong. One MAY be right
df2 = dd.read_parquet('./OUT/2') 

df2.compute()
```

```
#This works on small data...but not on large.
newDf[2].compute()
```
[ToParquetIssue.pdf](https://github.com/dask/dask/files/2764180/ToParquetIssue.pdf)

**Comment by martindurant** [comment]
Would you mind simplifying this as much as possible, and posting the expected/actual results inline?

**Comment by bgoodman44** [comment]
Checkout the attached pdf.  It has the results inline.

**Comment by martindurant** [comment]
> Checkout the attached pdf. It has the results inline.

Sorry for being picky, but the point is that they shouldn't be in an attachment; plus I hope you can make a simpler example. It would be best in the form of "did this, expected this, got this" without all the intermediate variables.

**Comment by bgoodman44** [comment]
Did this:

```
un = [1,2]
df = dd.from_pandas(  pd.DataFrame({'A':un}) ,npartitions=1 )
df['B'] = 2.5*df['A']
savedTasks = dict()
for aa in un:
    adf = df[df.A == aa]
    savedTasks[aa] = client.compute(
            adf.to_parquet('./OUT/' + str(aa) +'/',compute=False)
    )
    
sleep(5)
for ii in un:
    print( dd.read_parquet( './OUT/' + str(ii) ).compute()     )
```
Got this:

```
       A    B
index        
0      1  2.5
       A    B
index        
0      1  2.5
```

Expected this:

```
       A    B
index        
0      1  2.5
       A    B
index        
1      2  5.0
```

Adding client.persist (below) yields the expected result, but I'm fearful of persisting the data, since the real data is larger than what can fit in memory.

```
un = [1,2]
df = dd.from_pandas(  pd.DataFrame({'A':un}) ,npartitions=1 )
df['B'] = 2.5*df['A']
df = client.persist(df)
savedTasks = dict()
for aa in un:
    adf = df[df.A == aa]
    savedTasks[aa] = client.compute(
            adf.to_parquet('./OUT/' + str(aa) +'/',compute=False)
    )
    
sleep(5)
for ii in un:
    print( dd.read_parquet( './OUT/' + str(ii) ).compute()     )
```

**Comment by bgoodman44** [comment]
Thats as simple as I can get it without being "tricky"

**Comment by martindurant** [comment]
Running your shortened code, I find on my system I am getting your "expected" values. Please ensure you are running with the latest versions of dask, distributed and fastparquet.

**Comment by bgoodman44** [comment]
Hmm, interesting.
Upgraded distributed from 1.25.1 to 1.25.2, and still have the same issues:

I'm using Ubuntu 16.04 and python 3.5.2

dask == 1.0.0
distributed = 1.25.2
fastparquet==0.2.1
tornado = 5.1.1
bokeh = 1.0.2

Any other relevant version numbers?

**Comment by martindurant** [comment]
Versions look OK, although I am on python 3.6. I'm afraid I don't have an answer for you. The only thing I can think of, is that somehow you are getting duplicate keys in the graphs.

**Comment by bgoodman44** [comment]
Confirmed that I'm having the same problem on my laptop (also Ubuntu Gnome 16.04, python 3.5)

**Comment by bgoodman44** [comment]
Ran in a barebones pipenv with python 3.6, and have the same issue.  What OS are you using?

**Comment by bgoodman44** [comment]
i tried using pyarrow as well...same result.

**Comment by martindurant** [comment]
I cannot explain it, except to suppose that somehow your paths were set to pick up some versions or configurations from your default system python. I suggest closing.
