### ISSUE TITLE
dataframe.repartition(npartitions=n) not behaving properly.  distributed.nanny exceeded memory

### ISSUE THREAD

**Issue by bgoodman44** [dask/dask#4391]
Hello,

I'm running into an issue with workers exceeding their memory budget on relatively small problems.  It appears to be related to the number of partitions in the dataframe.   If the initial dataframe is poorly partitioned (i.e there aren't enough partitions)... I get distributed.nanny memory errors.   This isn't unexpected, but even if I re-partition, I still get the errors.    

This works:
```
draws = int(100e6)
np.random.seed(0)
df = dd.from_pandas(  pd.DataFrame({'A':np.random.randint(0,10,(draws,))}) ,npartitions=1 )
df['B'] = 2.5*df['A']
un = client.persist(df.B.unique());
un.compute()
```

This yields distributed nanny errors, as expected:
```
draws = int(100e6)
np.random.seed(0)
df = dd.from_pandas(  pd.DataFrame({'A':np.random.randint(0,10,(draws,))}) ,npartitions=1 )
df['B'] = 2.5*df['A']
un = client.persist(df.B.unique());
un.compute()
```

This should work, but also yields distributed nanny errors:
```
draws = int(100e6)
np.random.seed(0)
df = dd.from_pandas(  pd.DataFrame({'A':np.random.randint(0,10,(draws,))}) ,npartitions=1 )

mem = df.memory_usage(deep=True).sum().compute()
n = 1 + mem//100e6;
print('----repartitioning to:',n,mem)
df = df.repartition(npartitions = n);

df['B'] = 2.5*df['A']
un = client.persist(df.B.unique());
un.compute()
```

I should not that my machine has 6 cores (12 workers), and 32gb of memory.  You MAY need to increase the number of "draws" in the above code blocks if your system has more/less workers/memory.

More info about my REAL use-case:

Ideally, the datframe would just be appropriately partitioned from the beginning, as in the first code block.  Unfortunately, I don't think this is an option for me because of the way my input data is structured.  I have a zipped folder that has multiple csv files within it.    To load the File1.csv data into single dataframe, I pass the zipfiles to a custom loader function through dask.delayed.  The loader function uses zipfile and pd.read_csv.  Unfortunately, each *.csv file is loaded into a single partition.  Using dd.read_csv isn't an option due to the structure of the zipfile (as far as i can tell).

```
Folder_0.zip
       File1.csv
       File2.csv

Folder_N.zip
       File1.csv
       File2.csv
```

```
import zipfile
def Loader(zfilename,csvName):
    zFile = zipfile.ZipFile(zfilename)
    df = pd.read_csv(zFile.open(csvName))
    return df
dfs = [delayed(Loader)(f,'File1.csv') for f in myZipFileList]
df  = dd.from_delayed(dfs)
```

**Comment by mrocklin** [comment]
> Ideally, the datframe would just be appropriately partitioned from the beginning, as in the first code block.

Yeah, dask doesn't work this way unfortunately.  It can't go back and rewrite expressions today.

> I have a zipped folder that has multiple csv files within it. To load the File1.csv data into single dataframe,

It sounds like you need to find a way to break up reading these larger chunks into smaller chunks.  If you're writing this as your own custom function then you may be on your own here.

**Comment by bgoodman44** [comment]
Hi Matt,
Thanks for the reply.

What I've done as a work around is read the larger files, re-partition, write to_parquet, read_parquet, and 
then carry on with the computations without issue.   I just don't understand WHY  simply re-partitioning, without the write/load in between, doesn't have the same effect?

**Comment by mrocklin** [comment]
When you write and read you're probably balancing out load a bit more
evenly, or loading things in smaller chunks-at-a-time and so able to
pipeline more efficiently.

You might consider playing around with persist/wait/rebalance to see if
that has an effect, but that's also a tricky workflow that expects all of
your data to be in RAM at once.

**Comment by bgoodman44** [comment]
Thank you, Matt.  Do you recommend keeping this open or closing it?

**Comment by mrocklin** [comment]
I don't see a path forward that isn't covered by other larger issues (like
large scale expression optimization).  I'm in favor of closing.
