### ISSUE TITLE
da.store is confused when regions is a tuple of tuple of slices.

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#4393]
This works as expected:
```
regions = [(slice1, slice2)]
future = da.store(sources, targets, regions=regions, lock=False, compute=False)
```

While this creates write operations with wrong slices:
```
regions = [(slice1, slice2)]
future = da.store(sources, targets, regions=tuple(regions), lock=False, compute=False)
```
The documentation claims regions can be iterable of tuple of slices, but apparently due to the check in `da.store` for the type of region it only allows non-tuple iterable of tuple of slices as the input.

Either the documentation or the code needs to be changed. I suspect there are other occasions where tuples are treated in special like this.

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
AFAICT this has always been true of regions. Please see PR ( https://github.com/dask/dask/pull/1756 ) for details. Specifically it seems to assume that a `tuple` means a single region was specified and that region should be reused for all source/target pairs.

Adding a doc PR that clarifies the existing behavior seems good. If possible improving the error message and checking for this, could also be good. It might be possible to support nesting `tuple`s, but we'd want to think about this a little bit.

**Comment by martindurant** [comment]
Should be a quick fix.

**Comment by mrocklin** [comment]
@martindurant does this mean that you plan to execute this fix?
