### ISSUE TITLE
Provide byte size in chunks keyword?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4397]
How do people feel about the following:

```python
x = da.ones(1000000000, chunks="256 MiB")
```

This would use the `"auto"` chunking mechanism, and use the provided value as the desired chunk size.

**Comment by mrocklin** [comment]
Planning to interpret silence here as assent :)

**Comment by gsakkis** [comment]
I was about to suggest a similar parameter for `dataframe.repartition` to basically implement the approach you suggested in [this SO question](https://stackoverflow.com/questions/44657631/strategy-for-partitioning-dask-dataframes-efficiently). Should I open a new issue for it?

**Comment by mrocklin** [comment]
Yes, a different issue would be good here.

**Comment by jakirkham** [comment]
In the case of a 1-D array the meaning of this is somewhat clear. However it's less clear what this means for arbitrary dimensionality. Could you please elaborate?

**Comment by mrocklin** [comment]
We would use the same logic as is currently implemented for the "auto"
chunking value

**Comment by mrocklin** [comment]
Some relevant pieces of code for this

https://github.com/dask/dask/blob/9241a2ae16c0eb54073b16bc3ae01bf40f43c90c/dask/utils.py#L950-L997

https://github.com/dask/dask/blob/9241a2ae16c0eb54073b16bc3ae01bf40f43c90c/dask/array/core.py#L1776-L1897

note in particular the `chunks` keyword (which will be something like "10 MiB") and the `limit=` keyword, which we use within the function to determine the ideal chunksize

**Comment by mrocklin** [comment]
I spoke to @beberg offline and he seemed interested in doing this

**Comment by mrocklin** [comment]
It might be that the user provides conflicting or overlapping values for `limit=` or byte chunk values like 

```python
x = da.ones((100000, 100000), chunks=('1MiB', '10 MiB'))
```

In these cases I suggest that we raise a ValueError encouraging them to specify at most one byte size value.

**Comment by beberg** [comment]
I throw an error if the user specifies different values of the byte limit in chunks= or limit=. Consistent values are OK.
