### ISSUE TITLE
SciPy 2019 tutorial?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4400]
https://www.scipy2019.scipy.org/tutorials

Should we submit something?  cc'ing @martindurant @jcrist @TomAugspurger who I think handled the tutorial last year.

**Comment by martindurant** [comment]
Yes, I believe we should - indeed, last year's seems to have been fairly well received. I personally ought to also think about something for Intake, and a tutorial might make the most sense this time.

**Comment by mrocklin** [comment]
Did this happen?

**Comment by martindurant** [comment]
Not by me, I did an Intake one (this was also in the gitter chat). I'm not aware of any dask tutorial going in.

**Comment by mrocklin** [comment]
@jcrist ?

**Comment by jcrist** [comment]
Nope, apologies, I realized I missed the deadline on Saturday.

**Comment by martindurant** [comment]
@jcrist , given that they had been in direct contact requesting a submission, they may well consider a late one, if you are interested.

**Comment by jcrist** [comment]
Sure, I'll shoot them an email now and see if that's true.

**Comment by stsievert** [comment]
@jcrist did the tutorial get submitted?

**Comment by jcrist** [comment]
No, we will not be having a tutorial this year at Scipy. Sorry, this was communicated via email, but I forgot to update the issue here.
