### ISSUE TITLE
sereies.str.get_dummies not supported

### ISSUE THREAD

**Issue by ilango100** [dask/dask#4403]
Pandas supports the function `series.str.get_dummies()` [[pandas doc]](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.get_dummies.html) which is very much useful to convert a string column directly into word based "vectors" for ML algorithms. The matrix can be later converted to much useful tf-idf matrix and more.
```
df = pd.DataFrame({"a":["hello world", "hola mi amigo"]})
df.a.str.get_dummies(" ")
```
|amigo | hello | hola | mi | world
|-- | -- | -- | -- | --
|0 | 1 | 0 | 0 | 1
|1 | 0 | 1 | 1 | 0

Currently, dask doesn't seem to support it.

```
ddf = dd.from_pandas(df, npartitions=1)
ddf.a.str.get_dummies(" ")
```
```
AttributeError                            Traceback (most recent call last)
<ipython-input-18-9fdcf14ccce2> in <module>
      1 ddf = dd.from_pandas(df, npartitions=1)
----> 2 ddf.a.str.get_dummies(" ")

c:\python\3.6\lib\site-packages\dask\dataframe\accessor.py in __getattr__(self, key)
     83                 return partial(self._function_map, key)
     84         else:
---> 85             raise AttributeError(key)
     86 
     87 

AttributeError: get_dummies
```

Is it possible to implement the feature?

**Comment by mrocklin** [comment]
> Is there a way to do it lazily, i.e, by creating the meta dict lazily etc. ?

No.  The columns depend on the values of your data, so you need to pass through your data to get them.

Closing as "wont fix"
