### ISSUE TITLE
ModuleNotFoundError: No module named 'dask.highlevelgraph'

### ISSUE THREAD

**Issue by melvinev** [dask/dask#4408]
Running Dask version 1.1.0.

Getting no module named "dask.highlevelgraph" found when I run this:

df = db.from_sequence(dat).to_dataframe(meta=meta)
futures = client.submit(backtest, df.to_records)
futures.result()

I'm trying to map the rows of the dataframe to a new function.

**Comment by mrocklin** [comment]
Try

    client.get_versions(check=True)

**Comment by melvinev** [comment]
Thank you for the prompt (and right!) reply-.  Docker cluster was on 1.0.0 and I was on 1.1.0 locally.  Upgrade dockerfile and all set.  Thanks @mrocklin
