### ISSUE TITLE
countvectorizer returns incorrect dimensions

### ISSUE THREAD

**Issue by dileep3004** [dask/dask#4412]
`count_vec = CountVectorizer()
final_tr=train.map_partitions(count_vec.fit_transform).compute()
final_te=test.map_partitions(count_vec.transform).compute()`

when i m trying to print shape
it s getting 
(46, 1)

i am passing around 
846065 data points

train and test are dask dataframes

**Comment by dileep3004** [comment]
this is my ipynb file
drive link: https://drive.google.com/open?id=1OnZjL1C0JjPSiax0gmmKLviVH0GraDJg

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports :)

Do you think there's a bug in map_partitions?

**Comment by mrocklin** [comment]
Closing due to lack of response.
