### ISSUE TITLE
Migration from sharedict to HighLevelGraph

### ISSUE THREAD

**Issue by djhoese** [dask/dask#4417]
I understand that sharedict is being deprecated, but it is currently not importable as it was before. This is probably by accident or a misunderstanding on my part. Previously doing `import dask` and then using `dask.sharedict` was possible. This import issue has an easy fix (`import dask.sharedict`), but I'm looking for help on modifying some old code with the new interface. Additionally, I don't see anything in the release notes about HighLevelGraph being added or sharedict being deprecated.

My use case was provided by @jakirkham as mentioned here: https://github.com/dask/dask/issues/3600#issuecomment-396802704.

```python
arrays = [dask_arr1, dask_arr2, dask_arr3]

# optimize Dask graph over all objects
dsk = da.Array.__dask_optimize__(
    dask.sharedict.merge(*[e.__dask_graph__() for e in arrays]),  # combine all Dask Array graphs
    list(dask.core.flatten([e.__dask_keys__() for e in arrays]))  # get Dask Array keys in result
)
arrays = [da.Array(dsk, e.name, e.chunks, e.dtype) for e in arrays]  # rebuild Dask Arrays
```

What is the suggested way of accomplishing this in newer/future versions of dask?

Side note: the deprecation warning is a `UserWarning`:

```python
In [2]: import dask.sharedict                                                                                                                                        
/Users/davidh/anaconda/envs/polar2grid_py36/bin/ipython:1: UserWarning: ShareDict has been deprecated in favor of HighLevelGraph and will be removed in future versions
  #!/Users/davidh/anaconda/envs/polar2grid_py36/bin/python
```

Shouldn't this be a `PendingDeprecationWarning` or `DeprecationWarning`?

**Comment by djhoese** [comment]
Wow so unless I'm missing something it should be a drop in replacement. Thanks I'll test this out later today hopefully.

**Comment by jcrist** [comment]
> Shouldn't this be a PendingDeprecationWarning or DeprecationWarning?

`DeprecationWarning` isn't shown by default, we use `UserWarning` instead since we really want users to see this and fix their code.
