### ISSUE TITLE
Updating the collections/schedulers graphic

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4419]
As much as I think the [graphic shown for collections and schedulers]( https://docs.dask.org/en/latest/#dask ) is great, it could use some updating. Here are some thoughts in no particular order.

1. Would be great to make it an SVG.
2. The "distributed" scheduler mode actually has a lot of variety that is not portrayed.
3. Collections can be extended and in some cases are already (would be great to include these).
4. Delayed appears not to be included.

These are just my thoughts. The general gist of the graphic still seems very good to me, but I think these changes would help paint a clearer picture of what is possible.

Would be curious to hear thoughts from others on these (or other) suggested changes.

**Comment by mrocklin** [comment]
I definitely agree that that graphic could be improved.  I'm also curious
to hear people's suggestions.

**Comment by mrocklin** [comment]
Closing in favor.
