### ISSUE TITLE
Inconsistent behavior when computing Delayed objects with more than one output

### ISSUE THREAD

**Issue by zo7** [dask/dask#4420]
I ran into some inconsistent behavior using `dask.delayed` with multiple outputs (via the `nout` arg) and was wondering if this was intentional behavior or not:

Consider these two functions:
```python
import dask

@dask.delayed()
def return_one():
    return 1

@dask.delayed(nout=2)
def return_two():
    return 1, 2
```

Depending on how you compute the `Delayed` objects these return, you get different results:
```python
>>> x = return_one()
>>> dask.compute(x)
(1,)
>>> x, y = return_two()
>>> dask.compute(x, y)
(1, 2)
```
```python
>>> return_one().compute()
1
>>> return_two().compute()
(1, 2)
```
```python
>>> dask.compute(return_one())
(1,)
>>> dask.compute(return_two())
((1, 2),)
```
```python
>>> client = dask.distributed.Client()
>>> client.gather(client.compute(return_one()))
1
>>> client.gather(client.compute(return_two()))
(1, 2)
```

This produces some inconsistent behavior, for example if you were trying to unpack all of the tuples: (notice the commas on the LHS)
```python
x_ = return_one()
x, = dask.compute(x_)  # => (1,)

x_, y_ = return_two()
x, y = dask.compute(x_, y_)  # => (1, 2)

x = return_one().compute()  # => 1

x, y = return_two().compute()  # => (1, 2)

x, = dask.compute(return_one())  # => (1,)

(x, y), = dask.compute(return_two())  # => ((1, 2),)

x = client.gather(client.compute(return_one()))  # => 1

x, y = client.gather(client.compute(return_two()))  # => (1, 2)
```
Is this intentional? If not, how should this behave?

**Comment by mrocklin** [comment]
Sorry for the lack of response here.  I agree that this inconsistency is unfortunate.  It's an artifact of history.  If there was a clean way to deprecate and change the behavior I would be in favor of it.  I'm not sure how feasible this is though.
