### ISSUE TITLE
Feature request: Report scheduler details in dashboard

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#4424]
On the worker and info tabs, we get the details of the workers, in particular their ip address.

Would it be possible to also display the scheduler address somewhere too, maybe at the top of the system page?

I just went looking for it today and didn't want to trundle back through traceback in my console to find my cluster address but I had the dashboard up and running. 

It's a marginally useful idea that would only be worth it if it was very easy to implement.

**Comment by mrocklin** [comment]
One two-line solution is here: https://github.com/dask/distributed/pull/2483

There is probably other information that would be good to collect there.  Adding this stuff is pretty easy if you want to jump in :)  It would be great to have you active in the dashboard again ;)
