### ISSUE TITLE
Feature request: improve error reporting when misusing da.histogram

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#4428]
When porting code like this:

```python
hist, edges = np.histogram(data, bins=40)
```

to dask, it's easy to do:

```python
hist, edges = da.histogram(data, bins=40)
```

and forget to specify a range.

The error that you get in this case is:

```python-traceback
~/miniconda3/envs/ovscrptd/lib/python3.6/site-packages/dask/array/routines.py in histogram(a, bins, range, normed, weights, density)
    612     if not np.iterable(bins):
    613         bin_token = bins
--> 614         mn, mx = range
    615         if mn == mx:
    616             mn -= 0.5

TypeError: 'NoneType' object is not iterable
```

An extra check here and a nudge to add a range or specify bins would be helpful, specially for noobs like me.

**Comment by jrbourbeau** [comment]
Thanks for reporting this @birdsarah! I totally agree that the `'NoneType' object is not iterable` message being raised could be improved upon. In #4430 I proposed an updated error message:

```python
ValueError: dask.array.histogram requires either an iterable 
specifying the bins or the number of bins and a range to be defined.
```

Hopefully that's more informative, any feedback is appreciated.
