### ISSUE TITLE
Join dask.DataFrame with dask.Series

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask#4429]
Hi,

Could someone please let me know how to join a dask dataframe with a dask series object. I tried converting the dask series into a dask dataframe but it did not work. #1677 does not give a clear answer for it. In pandas, a pandas series could be converted into a pandas dataframe by using `pandas.dataframe(series)` it gives me an error when doing the same for dask dataframe.

code:
```
card_id_pur_freq = dd.DataFrame(card_id_pur_freq)
```
output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-c5d7a167a963> in <module>
----> 1 card_id_pur_freq = dd.DataFrame(dsk = card_id_pur_freq)

TypeError: __init__() missing 3 required positional arguments: 'name', 'meta', and 'divisions'

```
I only know what give the `divisions` parameter
could someone please help me with the code.

Thanks

Michael

**Comment by mrocklin** [comment]
Try the to_frame method

**Comment by MichaelSchroter** [comment]
ok thanks for the help
