### ISSUE TITLE
Dask on Mesos - Running Jobs with a Role

### ISSUE THREAD

**Issue by mangeshkaslikar** [dask/dask#4439]
Hi,  

I am looking to leverage Mesos to run my Dask Jobs. Mesos comes with a feature that a certain 'Role' has a 'Quota' of resources and if you can associate your jobs with that Role, your jobs can consume those resources set in the 'Quota'. This feature is present in spark (https://spark.apache.org/docs/latest/running-on-mesos.html ). Is the same feature available in Distributed Dask. 

Thanks. 

Mangesh Kaslikar

**Comment by martindurant** [comment]
I don't know the status of [dask-mesos](https://github.com/mrocklin/dask-mesos), btu maybe you can try it (atyour own risk). The solution for [yarn](https://github.com/dask/dask-yarn/) is much more mature and feature-complete.

**Comment by mangeshkaslikar** [comment]
@mrocklin I am looking to run task presented by a Mesos Offer coming from a Role which has an assigned quota. More details on Quota here : http://mesos.apache.org/documentation/latest/quota/ 

Thanks. 

Mangesh

**Comment by mrocklin** [comment]
@mangeshkaslikar is there anything else we can do to help you here?

If the question is "Does Dask natively support Mesos?" then the answer is "No, but there are a variety of third-party packages out there that attempt to do so".  

Closing.  Feel free to ping again if you have further questions.
