### ISSUE TITLE
Is Masked-array arithmetic getting masks wrong ?

### ISSUE THREAD

**Issue by pp-mo** [dask/dask#4441]
Arithmetic operations between a dask array and a numpy array have the effect of ignoring any mask on the latter.

Like this :
```
>>> lazy = da.asarray([5, 6])
>>> mask = np.ma.masked_array([2, 3], mask=[0, 1])
>>> (lazy + mask).compute()
array([7, 9])
>>> 
>>> # But expected ...
... lazy.compute() + mask
masked_array(data=[7, --],
             mask=[False,  True],
       fill_value=999999)
>>> 
```

However, if we *explicitly* wrap the masked array as a dask array, all is well ...
```
>>> (lazy + da.asanyarray(mask)).compute()
masked_array(data=[1, --],
             mask=[False,  True],
       fill_value=999999)
>>> 
```

(BUT: only using `da.asanyarray` : `da.asarray` does not work)

**Comment by pp-mo** [comment]
NOTE:
I think it may be that, when promoting 'mask' to a dask array, 
the code is wrapping it with 'da.asarray()', where 'da.asanyarray()' would make more sense ?

Or possibly, the fact that `ds.asarray` applies `np.asarray` is also a subtle mistake, and it should be employing `np.asanyarray` instead.
At least, for this precise example, I found that the key call is this one : https://github.com/dask/dask/blob/master/dask/array/core.py#L82
 -- changing that from `np.asarray` to `np.asanyarray` "fixes" the above problem.

However, I'm unclear on the exact intentions of these routines : 
*what is appropriate here ?*

**Comment by pp-mo** [comment]
NOTE#2 :

Another thing I found, which may influence our view of this, is that whereas calculating (dask-array + numpy-array) behaves as expected, the opposite order (numpy-array + dask-array) results in realising the dask array and converting it to numpy.

Presumably, this asymmetry is governed by the fact that numpy "accepts" a dask-array as an array-like to be converted, and there is nothing we can do about that in this project.

However, this might influence whether we think this kind of cross-domain arithmetic is desirable in the first place.

**Comment by mrocklin** [comment]
@pp-mo thank you for investigating these issues.  

> what is appropriate here ?

The right person to engage here is probably @jcrist , though he may also be busy with other work at the moment.  It may be that you (and the folks around you) are the people best suited to analyze the situation.

**Comment by jcrist** [comment]
It looks like `elemwise` is calling `da.asarray` on non-dask arrays when it should *possibly* be calling `da.asanyarray`.

> Presumably, this asymmetry is governed by the fact that numpy "accepts" a dask-array as an array-like to be converted, and there is nothing we can do about that in this project.

This is correct, and one reason why I'd advise explicitly converting numpy arrays into dask arrays before mixing them. Things can work if you're careful, but you have greater assurances and control if you handle things manually.

**Comment by pp-mo** [comment]
Just reviewing this again...

> I'd advise explicitly converting numpy arrays into dask arrays before mixing them

I get the point, but shouldn't at least `da.asarray` then do the right thing with a masked array ?
The same applies to `da.from_array` : in both cases, you **_must_**  explicitly specify `asarray=False` to avoid it stripping the mask, and again I think this is due to an `np.asarray` which really ought to be a `np.asanyarray`.

If there's any appetite, I'll create a PR suggesting a fix.

**Comment by mrocklin** [comment]
@jcrist do you have a recommendation here?  It looks like @pp-mo is willing to do some work here, but needs the go-ahead from you.

**Comment by jcrist** [comment]
Apologies @pp-mo, in the process of trying to recommend a fix, I ended up fixing and submitting a PR (#4506). We now call `da.asanyarray` on args of array types instead of `da.asarray`.

> I get the point, but shouldn't at least `da.asarray` then do the right thing with a masked array ?
> The same applies to `da.from_array`

`da.asarray` does the right thing in that it mirrors numpy. Calling `np.asarray` on a masked array also results in a numpy array. `da.asanyarray` is what we wanted here.

`da.from_array` is our own interface, and has its casting conventions due to legacy reasons. I'm reluctant to change this, but it could happen with a long deprecation period.
