### ISSUE TITLE
Backwards incompatible change to map_partitions in v1.1.0

### ISSUE THREAD

**Issue by joegoldbeck** [dask/dask#4446]
Easy fix on the user's end, but I didn't see it in the changelog and so I thought worth pointing out :)

In `v1.0.0`, the following code works:

```
import dask.bag as db

def append_str(partition, s):
    return [x + s for x in partition]

mybag = db.from_sequence(["a", "b", "c"])

tupled_map_partitions_result = mybag.map_partitions(append_str, "foo").compute()
print(f"map_partitions result: {tupled_map_partitions_result}")
```

which prints: `map_partitions result: ['afoo', 'bfoo', 'cfoo']`

However in `v1.1.0`, this raises:`TypeError: can only concatenate str (not "itertools.repeat") to str`

The following code works in `v1.1.0` to achieve the same result (1.0.0 would have different behavior)

```
import dask.bag as db

def append_str(partition, strs):
    return [x + s for x, s in zip(partition, strs)]

mybag = db.from_sequence(["a", "b", "c"])

tupled_map_partitions_result = mybag.map_partitions(append_str, "foo").compute()
print(f"map_partitions result: {tupled_map_partitions_result}")
```

I believe this comes from PR #4092, in particular, this line: https://github.com/dask/dask/blame/d63ad2a4a74ff88e6f7b670e9fb5e4bb4c0d667b/dask/bag/core.py#L1954

**Comment by mrocklin** [comment]
Thanks for the excellent issue @joegoldbeck (and sorry for the delay in response).

I agree that this seems to be a regression.  Ideally we would be able to pass simple values like "foo" down through `map_partitions` easily.  Do you have any interest in helping to fix this?  I would probably remove the line you mention, replacing with the simpler `args2.append(a)`, and then see if anything breaks.  Presumably I made that change for some reason (no clue at the moment what it was).  The example you provide here would also make for an excellent test to make sure that we don't regress again in the future.

**Comment by joegoldbeck** [comment]
Sure, I'll take a look!
