### ISSUE TITLE
KeyError when using da.map_blocks to reduce a dimension

### ISSUE THREAD

**Issue by venabled** [dask/dask#445]
When using a mapping function that reduces a dimension of the array, dask throws a key error indicating that one of the nodes in the graph is not available. 
 
I ran into this when trying to convert an (m,n,3) RGB nd-array to a (m,n) grayscale array using skimage. @shoyer suggested a simple example to rule out skimage doing anything, so I used the following code example: 

```
import skimage.data as dgen
img = dgen.astronaut()
chunkshape = (256, 256, 3)
dimg = da.from_array(img, chunks=chunkshape)
gray = dimg.map_blocks(lambda arr: arr.mean(axis=2), chunks=(256, 256))
grayimg = gray.compute()
```

And dask throws a key-error: ``` KeyError: ('x_76', 0, 1)```

The full gist of the traceback is here: https://gist.github.com/venabled/fb102bb7cd7dd4ed2d22

Not sure if this is intended behavior (e.g. should I manually do my reduction using coarsen?), or if this is a bug.

**Comment by venabled** [comment]
FYI, I was able to accomplish conversion to grayscale using this workflow: 

```
img = dgen.astronaut()
chunkshape = (256, 256)
r = 0.2125 * da.from_array(img[..., 0].astype(np.float), chunks=chunkshape)
g = 0.7154 * da.from_array(img[..., 1].astype(np.float), chunks=chunkshape)
b = 0.0721 * da.from_array(img[..., 2].astype(np.float), chunks=chunkshape)
gray = da.stack([r, g, b], axis=2).sum(axis=2)
grayimg = gray.compute()
```

**Comment by mrocklin** [comment]
This also came back in https://github.com/ContinuumIO/dask/issues/263

This can be tricky to get right but is generally doable given enough time.

Alternatively we could establish a policy around `map_blocks` that the mapped function must maintain the same dimensionality as the input and improve error messaging suggesting the use of introducing empty dimensions in the mapped function, e.g.

    return result[..., None]

followed by a call to `da.squeeze`

**Comment by venabled** [comment]
@mrocklin I'm fine with a policy right now. I agree with @shoyer and your assessment that labeled axes probably makes this easier.

**Comment by mrocklin** [comment]
There is now a `drop_axis=` keyword argument in [da.map_blocks](http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.map_blocks).  Closing.
