### ISSUE TITLE
Dataframe groupby/apply fails when DF contains a tz-aware column

### ISSUE THREAD

**Issue by arredond** [dask/dask#4451]
#### Description

For some reason, when applying a function on a grouped DF, the function fails if the DF contains a tz-aware timestamp column. Even though the error comes from Pandas, the issue only occurs in Dask and not in Pandas itself.

#### Extra info

This issue popped up when migrating to Dask 1.1. I was using Dask 0.17 before and didn't encounter it.

#### Reproducible example

```python
import pandas as pd

from dask import dataframe as dd

def return_self(x):
    return x

# These work fine
df = pd.DataFrame({
    'id': [0, 1],
    'ts': [pd.Timestamp.now(), pd.Timestamp.now() - pd.Timedelta(minutes=5)]
})
ddf = dd.from_pandas(df, npartitions=2)

df.apply(return_self, axis=1, meta=[('id', 'datetime64[ns]')])
df.groupby('id').apply(return_self, meta=[('id', str), ('ts', 'datetime64[ns]')]).compute()

# Here the groupby/apply fails
df = pd.DataFrame({
    'id': [0, 1],
    'ts': [pd.Timestamp.now(tz='UTC'), pd.Timestamp.now(tz='UTC') - pd.Timedelta(minutes=5)]
})
ddf = dd.from_pandas(df, npartitions=2)

df.apply(return_self, axis=1, meta=[('id', 'datetime64[ns]')]) # OK
df.groupby('id').apply(return_self, meta=[('id', str), ('ts', 'datetime64[ns]')]).compute() # Fails

# Changing the meta does not help
df.apply(return_self, axis=1, meta=[('id', 'datetime64[ns, UTC]')]) # Still OK
df.groupby('id').apply(return_self, meta=[('id', str), ('ts', 'datetime64[ns, UTC]')]).compute() # Still fails

# It doesn't matter what you return
def return_nothing(x):
    return None

df.groupby('id').apply(return_nothing, meta=df._meta).compute() # Still fails
```

<details>

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-42-b4619c312770> in <module>
----> 1 df.groupby('id').apply(return_self, meta=[('id', str), ('ts', 'datetime64[ns, UTC]')]).compute()

/usr/local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/usr/local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

/usr/local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/usr/local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    457                         _execute_task(task, data)  # Re-execute locally
    458                     else:
--> 459                         raise_exception(exc, tb)
    460                 res, worker_id = loads(res_info)
    461                 state['cache'][key] = res

/usr/local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

/usr/local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

/usr/local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/usr/local/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/usr/local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/usr/local/lib/python3.6/site-packages/dask/dataframe/shuffle.py in collect(p, part, meta, barrier_token)
    424 def collect(p, part, meta, barrier_token):
    425     """ Collect partitions from partd, yield dataframes """
--> 426     res = p.get(part)
    427     return res if len(res) > 0 else meta
    428 

/usr/local/lib/python3.6/site-packages/partd/core.py in get(self, keys, **kwargs)
     71     def get(self, keys, **kwargs):
     72         if not isinstance(keys, list):
---> 73             return self.get([keys], **kwargs)[0]
     74         elif any(isinstance(key, list) for key in keys):  # nested case
     75             flatkeys = list(flatten(keys))

/usr/local/lib/python3.6/site-packages/partd/core.py in get(self, keys, **kwargs)
     77             return nested_get(keys, dict(zip(flatkeys, result)))
     78         else:
---> 79             return self._get(keys, **kwargs)
     80 
     81     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in _get(self, keys, **kwargs)
     28         raw = self.partd._get(keys, **kwargs)
     29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
---> 30                 for chunk in raw]
     31 
     32     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in <listcomp>(.0)
     28         raw = self.partd._get(keys, **kwargs)
     29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
---> 30                 for chunk in raw]
     31 
     32     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in <listcomp>(.0)
     27     def _get(self, keys, **kwargs):
     28         raw = self.partd._get(keys, **kwargs)
---> 29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
     30                 for chunk in raw]
     31 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in deserialize(bytes)
    173             index_from_header_bytes(headers[1], bytes[1])]
    174     blocks = [block_from_header_bytes(h, b)
--> 175               for (h, b) in zip(headers[2:], bytes[2:])]
    176     return pd.DataFrame(create_block_manager_from_blocks(blocks, axes))
    177 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in <listcomp>(.0)
    173             index_from_header_bytes(headers[1], bytes[1])]
    174     blocks = [block_from_header_bytes(h, b)
--> 175               for (h, b) in zip(headers[2:], bytes[2:])]
    176     return pd.DataFrame(create_block_manager_from_blocks(blocks, axes))
    177 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in block_from_header_bytes(header, bytes)
    141     elif extension_type == 'datetime64_tz_type':
    142         tz_info = extension_values[0]
--> 143         values = pd.DatetimeIndex(values).tz_localize('utc').tz_convert(
    144             tz_info)
    145     return make_block(values, placement=placement)

/usr/local/lib/python3.6/site-packages/pandas/core/accessor.py in f(self, *args, **kwargs)
     89 
     90             def f(self, *args, **kwargs):
---> 91                 return self._delegate_method(name, *args, **kwargs)
     92 
     93             f.__name__ = name

/usr/local/lib/python3.6/site-packages/pandas/core/indexes/datetimelike.py in _delegate_method(self, name, *args, **kwargs)
    719 
    720     def _delegate_method(self, name, *args, **kwargs):
--> 721         result = operator.methodcaller(name, *args, **kwargs)(self._data)
    722         if name not in self._raw_methods:
    723             result = Index(result, name=self.name)

/usr/local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py in tz_localize(self, tz, ambiguous, nonexistent, errors)
   1047                                                   self.tz)
   1048             else:
-> 1049                 raise TypeError("Already tz-aware, use tz_convert to convert.")
   1050         else:
   1051             tz = timezones.maybe_get_tz(tz)

TypeError: Already tz-aware, use tz_convert to convert.
```

**Comment by arredond** [comment]
In case this helps anybody, I've been able to get around this issue by casting to a naive datetime:

```python
df['ts'] = df['ts'].apply(lambda x: x.tz_localize(None), meta=[('ts', 'datetime64[ns]')])
```

**Comment by arredond** [comment]
I absolutely did. Seems I mixed Pandas DFs (`df`) with Dask DFs (`ddf`). Not the best naming choices there...

Thanks for spotting that!

**Comment by arredond** [comment]
Hey there @TomAugspurger 

I've been struggling with this again and figured out the issue was real. It seems that `dask/partd` is always trying to `tz_localize` timestamp columns, whether they're already tz-aware or not.

Here's an example:

```python
import pandas as pd
from dask import dataframe as dd

pd_df = pd.DataFrame({'id': [0, 1, 2], 'ts': [pd.Timestamp.now(tz='UTC')]*3})
ddf = dd.from_pandas(pd_df, npartitions=3)

def return_self(df):
    return df

ddf.groupby('id').apply(return_self, meta=ddf._meta).compute() # Raises TypeError
ddf.groupby('id').apply(return_self).compute() # Same result w/o meta
```

The error is `TypeError: Already tz-aware, use tz_convert to convert.` Here's the full trace:
<Details>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-b26ded46447f> in <module>
      8     return df
      9 
---> 10 ddf.groupby('id').apply(return_self, meta=ddf._meta).compute() # Adding meta doesn't help

/usr/local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/usr/local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

/usr/local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/usr/local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    457                         _execute_task(task, data)  # Re-execute locally
    458                     else:
--> 459                         raise_exception(exc, tb)
    460                 res, worker_id = loads(res_info)
    461                 state['cache'][key] = res

/usr/local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

/usr/local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

/usr/local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/usr/local/lib/python3.6/site-packages/dask/core.py in <listcomp>(.0)
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]
--> 118         args2 = [_execute_task(a, cache) for a in args]
    119         return func(*args2)
    120     elif not ishashable(arg):

/usr/local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/usr/local/lib/python3.6/site-packages/dask/dataframe/shuffle.py in collect(p, part, meta, barrier_token)
    424 def collect(p, part, meta, barrier_token):
    425     """ Collect partitions from partd, yield dataframes """
--> 426     res = p.get(part)
    427     return res if len(res) > 0 else meta
    428 

/usr/local/lib/python3.6/site-packages/partd/core.py in get(self, keys, **kwargs)
     71     def get(self, keys, **kwargs):
     72         if not isinstance(keys, list):
---> 73             return self.get([keys], **kwargs)[0]
     74         elif any(isinstance(key, list) for key in keys):  # nested case
     75             flatkeys = list(flatten(keys))

/usr/local/lib/python3.6/site-packages/partd/core.py in get(self, keys, **kwargs)
     77             return nested_get(keys, dict(zip(flatkeys, result)))
     78         else:
---> 79             return self._get(keys, **kwargs)
     80 
     81     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in _get(self, keys, **kwargs)
     28         raw = self.partd._get(keys, **kwargs)
     29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
---> 30                 for chunk in raw]
     31 
     32     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in <listcomp>(.0)
     28         raw = self.partd._get(keys, **kwargs)
     29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
---> 30                 for chunk in raw]
     31 
     32     def delete(self, keys, **kwargs):

/usr/local/lib/python3.6/site-packages/partd/encode.py in <listcomp>(.0)
     27     def _get(self, keys, **kwargs):
     28         raw = self.partd._get(keys, **kwargs)
---> 29         return [self.join([self.decode(frame) for frame in framesplit(chunk)])
     30                 for chunk in raw]
     31 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in deserialize(bytes)
    173             index_from_header_bytes(headers[1], bytes[1])]
    174     blocks = [block_from_header_bytes(h, b)
--> 175               for (h, b) in zip(headers[2:], bytes[2:])]
    176     return pd.DataFrame(create_block_manager_from_blocks(blocks, axes))
    177 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in <listcomp>(.0)
    173             index_from_header_bytes(headers[1], bytes[1])]
    174     blocks = [block_from_header_bytes(h, b)
--> 175               for (h, b) in zip(headers[2:], bytes[2:])]
    176     return pd.DataFrame(create_block_manager_from_blocks(blocks, axes))
    177 

/usr/local/lib/python3.6/site-packages/partd/pandas.py in block_from_header_bytes(header, bytes)
    141     elif extension_type == 'datetime64_tz_type':
    142         tz_info = extension_values[0]
--> 143         values = pd.DatetimeIndex(values).tz_localize('utc').tz_convert(
    144             tz_info)
    145     return make_block(values, placement=placement)

/usr/local/lib/python3.6/site-packages/pandas/core/accessor.py in f(self, *args, **kwargs)
     89 
     90             def f(self, *args, **kwargs):
---> 91                 return self._delegate_method(name, *args, **kwargs)
     92 
     93             f.__name__ = name

/usr/local/lib/python3.6/site-packages/pandas/core/indexes/datetimelike.py in _delegate_method(self, name, *args, **kwargs)
    719 
    720     def _delegate_method(self, name, *args, **kwargs):
--> 721         result = operator.methodcaller(name, *args, **kwargs)(self._data)
    722         if name not in self._raw_methods:
    723             result = Index(result, name=self.name)

/usr/local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py in tz_localize(self, tz, ambiguous, nonexistent, errors)
   1047                                                   self.tz)
   1048             else:
-> 1049                 raise TypeError("Already tz-aware, use tz_convert to convert.")
   1050         else:
   1051             tz = timezones.maybe_get_tz(tz)

TypeError: Already tz-aware, use tz_convert to convert.

**Comment by mrocklin** [comment]
@TomAugspurger any feedback here?  is there anything to be done for this issue?

**Comment by KrishanBhasin** [comment]
Can I add a +1 to this issue? It has affected me too

**Comment by TomAugspurger** [comment]
I think we fixed this in partd: https://github.com/dask/partd/pull/32.

```python
import pandas as pd
from dask import dataframe as dd

pd_df = pd.DataFrame({'id': [0, 1, 2], 'ts': [pd.Timestamp.now(tz='UTC')]*3})
ddf = dd.from_pandas(pd_df, npartitions=3)

def return_self(df):
    return df

ddf.groupby('id').apply(return_self, meta=ddf._meta).compute() # Raises TypeError
ddf.groupby('id').apply(return_self).compute() # Same result w/o meta
## -- End pasted text --
/Users/taugspurger/.virtualenvs/dask-dev/bin/ipython:11: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
Out[1]:
   id                               ts
1   1 2019-06-06 14:25:21.418004+00:00
0   0 2019-06-06 14:25:21.418004+00:00
2   2 2019-06-06 14:25:21.418004+00:00

```

@KrishanBhasin what version of partd do you have?

**Comment by TomAugspurger** [comment]
I see that our setup.py only requires partd >= 0.3.8. This bug was fixed in partd 0.3.10. I think this is large enough to warrant bumping the minimum partd version, so that partd is updated when users update their env with dask.

@KrishanBhasin if you're on an older version of partd can you try manually updating it to the latest version?

**Comment by quasiben** [comment]
I just tried and it ran without issue:

For reference:
> partd                     0.3.10                   py37_1

**Comment by KrishanBhasin** [comment]
I just checked, I have `partd==0.3.8`. I will manually set my package up to ask for a newer version and rerun.

**Comment by KrishanBhasin** [comment]
I can confirm that updating partd to 0.3.10 fixes this issue for me.

Thank you!

**Comment by quasiben** [comment]
https://github.com/dask/dask/pull/4890 will close this issue
