### ISSUE TITLE
backing a dask array with disk as swap

### ISSUE THREAD

**Issue by ttung** [dask/dask#4465]
We are considering adopting dask in [starfish](https://github.com/spacetx/starfish) to manage computation for datasets that are larger than a machine’s memory.  One challenge is that our chunking has to be relatively generic, but we have to support a variety of algorithms with different data access patterns.  As such, we might have data arrays where the access patterns that stride a large number of chunks.  Have you given any thought to the ability to specify a backing for a dask array, where data that has been computed gets flushed to disk under memory pressure?  This would be somewhat similar to the [ability to spill data to disk](http://distributed.dask.org/en/latest/worker.html#spill-data-to-disk) in [dask-distributed](https://github.com/dask/distributed), except in dask.

**Comment by mrocklin** [comment]
Great question @ttung .  

When you're using the local scheduler you can pass in a `cache=` parameter that serves as a data storage MutableMapping.  If unspecified this is a normal Python dictionary.  It receives key-value pairs where the keys identify the task/result and the values are the Python objects that are your intermediate results.

So if you can construct a `MutableMapping` that keeps things in memory until it runs out of memory and then serializes things and puts them to disk, then you should be able to just provide that to a compute call, or to a config call

```python
cache = MySpillToDiskDictionary()
x.compute(cache=cache)
# or
dask.config.set(cache=cache)
x.compute()
```

I worked on one of these once, but offer no expectation of maintenance today: https://github.com/mrocklin/chest

Additionally you could probably cook one up using [Zict](https://zict.readthedocs.io/en/latest/), which is more maintained today (hopefully the docs help explain how to build something like this).

**Comment by mrocklin** [comment]
Any follow up @ttung ?  Otherwise I'll close this.

**Comment by ttung** [comment]
I haven't had time to try these things out, but if I have new questions, I'll reopen.  Thanks!

**Comment by ttung** [comment]
Is this cache parameter documented anywhere?  Can this cache be lossy, and force recomputation if necessary?  My experiments with this seems to suggest that this is not possible, at least the cache needs to be large enough to hold each computation to completion, and subsequent drops are tolerable.

**Comment by mrocklin** [comment]
> Is this cache parameter documented anywhere? Can this cache be lossy, and force recomputation if necessary? My experiments with this seems to suggest that this is not possible

Congratulations, you may now be the person with the most expertise in this topic :) It sounds like you may have answered your own question.
