### ISSUE TITLE
Update make_timeseries for pandas deprecation

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#4467]
```python
In [3]: dd.demo.make_timeseries()
/Users/taugspurger/sandbox/dask/dask/dataframe/io/demo.py:91: FutureWarning: Creating a DatetimeIndex by passing range endpoints is deprecated.  Use `pandas.date_range` instead.
  freq=partition_freq))
/Users/taugspurger/sandbox/dask/dask/dataframe/io/demo.py:45: FutureWarning: Creating a DatetimeIndex by passing range endpoints is deprecated.  Use `pandas.date_range` instead.
  index = pd.DatetimeIndex(start=start, end=end, freq=freq, name='timestamp')
Out[3]:
Dask DataFrame Structure:
                   id    name        x        y
npartitions=11
2000-01-31      int64  object  float64  float64
2000-02-29        ...     ...      ...      ...
...               ...     ...      ...      ...
2000-11-30        ...     ...      ...      ...
2000-12-31        ...     ...      ...      ...
Dask Name: make-timeseries, 11 tasks
```

Switching to `pd.date_range` should be fine.

**Comment by mrocklin** [comment]
The demo module should also be deprecated.  The main API entry point for this function is now `dask.datasets.timeseries`.

**Comment by liabifano** [comment]
Can I work on it?

**Comment by HSR05** [comment]
@mrocklin i resolved the warning part. Can you guide me what you mean by deprecating the demo module. Does it need to be shifted somewhere else?

**Comment by HSR05** [comment]
@mrocklin i resolved the warning part. Can you guide me what you mean by deprecating the demo module. Does it need to be shifted somewhere else or do i only change the main entry point of the API in setup.py. But as i see it should be dataframes as it is named that.
Can you guide me more on this? I would be more than thankful.

**Comment by TomAugspurger** [comment]
> Can you guide me what you mean by deprecating the demo module

Ideally, a warning would be emitted when any of the functions in `dask.dataframe.demo` is called. For some, like `make_timeseries`, the message would instruct people to use `dask.datasets.timeseries`. Others, like `make_string`, may just be removed (or perhaps moved to datasets.py, not sure).

**Comment by TomAugspurger** [comment]
And we can leave the deprecation to a separate module.

**Comment by TomAugspurger** [comment]
Apologies for missing your post @liabifano, it looks like @HSR05 has started on this.

Let me know if you want help finding / starting on another issue!
