### ISSUE TITLE
Proposed issue labeling to support project management tools

### ISSUE THREAD

**Issue by beberg** [dask/dask#4477]
**Goals**

Keep issue management simple and lightweight, while enabling project management tools.

Dask is used by other companies (the contributors among others) that want to contribute to Dask but need a greater level of coordination across internal and dask projects.

With GitHub Projects (or other tools) milestones, progress, and priority are expressed and tracked, but to do this effectively issues need to have a meaningful set of labels applied to them to express type, size, and component. In GitHub projects, it displays the issue title, tasks, "#xxx opened by user in repo", and the labels.

**Labels**

Each issue should have a type, size, and component whenever appropriate.

**Type label**

By default, an issue with no type is an enhancement. For simplicity issues that are dup/WillNotFix/invalid should get a comment and be closed, not kept open.

- (default no-label type means enhancement)
- bug
- question
- good first issue
- community

**Size label**

A rough estimation of how long someone familiar with the system would take to complete the issue. This helps in planning and enables new contributors to find smaller tasks.

- size minutes
- size hours
- size days
- size weeks

"size weeks" is for community issues discussing roadmap/architecture planning, which are broken into smaller issues for implementation. No single merge should ever be that vast.

**Component label**

Each project has a minimal but complete set of component labels. The list should be short but correspond to areas of expertise.

Common Components

- core (core to functionality of the repo)
- documentation
- cicd
- ... + project components. e.g. networking, scheduling, arrays, cicd, ...

**Flow**

A component and size label means the issue has been triaged (blank type means enhancement).

An issue actively being worked on should have the "assigned" field set when possible.

Default GitHub labels: bug, ~~duplicate~~, ~~enhancement~~, ~~help wanted~~ (help is always wanted), ~~invalid~~, question, ~~wontfix~~.

**Comment by mrocklin** [comment]
cc @TomAugspurger @jcrist @shoyer @jakirkham @ogrisel 

Companies like NVIDIA would like to use labels when doing internal project management.  They'd like to avoid having their own issues for work, and centralize on the dask issue tracker.  I think that there is some balance to be struck between adding structure and making sure that that structure is not company specific.  Your input on this topic would be very welcome.

**Comment by martindurant** [comment]
Labels (all of subproject, type of issue and workflow) and assignees are an excellent idea, even if only the companies/people that want to make use of them actually use them. Getting good labels may not be entirely straight-forward, and I think it may be a mistake to force OSS contributors from having to label everything.

**Comment by TomAugspurger** [comment]
No objection to using labels / projects more.

I don't see much in the initial post about milestones. Do we want to use those? Pandas has one milestone per release. Issues are tagged with the milestone we'd like to have it done by (with a bucket "someday" release for things none of the maintainers plan to work on). PRs are added to the milestone they're merged for, making it easy to see what version a PR is available in.

Is a given issue expected to have exactly one of each component? For example, I could see an issue being laeled as "good first issue" and "bug" (though I don't really see the value in a "bug" label).

I'm also somewhat against a "community" label, since that reinforces the distinct between paid and volunteer developers.

Size sounds hard to estimate, some issues more than others. Not to say we shouldn't try.

**Comment by mrocklin** [comment]
> and I think it may be a mistake to force OSS contributors from having to label everything.

One challenge here is that only people with write access can assign labels.  We're in an odd position where there may be some benefit to giving someone with a corporate project management role write access.  (To be clear, I'm not necessarily in favor of this, just stating a tension).

**Comment by jrbourbeau** [comment]
> No objection to using labels / projects more

Same here, I think this would be helpful 

> I'm also somewhat against a "community" label, since that reinforces the distinct between paid and volunteer developers

I think the community label is more for general project discussions like roadmaps, planning, upcoming sprints, etc. that anyone can be involved in (see https://github.com/dask/dask/issues?utf8=%E2%9C%93&q=label%3ACommunity+ for the issues that have the community label in the Dask issue tracker).

**Comment by mrocklin** [comment]
> PRs are added to the milestone they're merged for, making it easy to see what version a PR is available in.

As in @martindurant 's comment above, I'm somewhat hesitant to add any maintenance burden to people who are reviewing and merging PRs.  Currently this is usually me, and I'm often a bottleneck.  I'd be much more comfortable with this if we're able to diffuse review and merging burden.

**Comment by martindurant** [comment]
> only people with write access can assign labels

I didn't realise that. I suppose that brings in the "supporting entity" concept (or whatever we called it), that any organisation that wants to be able to assign labels should be an official supporter and thereby have at least one proven person with commit access.

**Comment by shoyer** [comment]
I have no objections to giving commit access to anyone who wants to do
project organization tasks. We can generally trust people to do the right
thing and not step beyond their bounds of expertise. The caveat would be
for genuine security risks, but I don't think that's a concern here.

**Comment by jakirkham** [comment]
One common strategy that other OSS projects have is to add a descriptor to the issue title (e.g. ENH, BUG, etc.). We could at a minimum adopt an existing standard along these lines and add this information to our contributing guide and GitHub contributing templates. This would let us empower more users to include this information without needing to worry about a level of trust or having someone necessarily burdened with cleanup.

**Comment by beberg** [comment]
Continuing the discussion

- Seems to be general consensus that labels would be good.
- @TomAugspurger is right about the multiple meanings of "community"...  "discussion" may be clearer and more universal to people that are new or coming from other languages.
- "bug" to me is useful as a red flag (and it should be the red label) on things that are broken, not matching the API, wrong, or blocking a user from adopting Dask. A bug means at least one person is blocked, and worst case the rest haven't noticed their results may be wrong. Bugs lead to retractions, retractions are very very bad.
- Milestones are orthogonal but related to labels, I'd like to keep that as a separate discussion.
- I believe @jakirkham is referring to Conventional Commits https://www.conventionalcommits.org/ which I have used before and love because of all the tooling it enables, and the component labels can match the commit scopes, but it requires some discipline by those who are doing the merges. Either way it's a very good idea to adopt. Component names should be single word and lowercase (and mostly are).

The good news is that existing labeling there is appears to be mostly consistent with the above.

Proposed Action Items:
- Type "community" -> "discussion"
- Create project component lists. (I plan to start with dask/distributed and related)
- Use Conventional Commits as preferred commit/merge format, but not required.
- Raise separate discussion about releases/milestones/project/etc.

**Comment by mrocklin** [comment]
* Type "community" -> "discussion"

+1 from me

* Create project component lists. (I plan to start with dask/distributed and related)

I'm curious what these would look like.  I interpret this as things like "bag", "array", "dataframe", "scheduling" and in the main repository.  Is this what you had in mind?

* Use Conventional Commits as preferred commit/merge format, but not required.

I'm not sure that concensus has been reached on this.  I personally don't find the prefixes like BUG and ENH super helpful and tend to avoid process by default.  I would be curious to hear from people here about when having prefixes like these on all commits would have helped them with Dask maintenance work before moving forward on this.

* Raise separate discussion about releases/milestones/project/etc.

Sounds good to me

**Comment by jakirkham** [comment]
To clarify my original suggestion, the use of prefixes like BUG and ENH are suggested to be used with issue/PR titles. The point being a random user doesn't necessarily have the option to label an issue/PR, but they can prefix the title with ENH for example. Am not opposed to using them in commits, but as we squash commits this should mostly follow from the PR title. The acronyms are taken from [NumPy's dev docs]( https://docs.scipy.org/doc/numpy-1.13.0/dev/gitwash/development_workflow.html#writing-the-commit-message ) as these are frequently used by projects in the ecosystem.

**Comment by TomAugspurger** [comment]
I've found the "Need Info" label helpful. It's applied when a user submits a bug report that isn't (easily) reproducible or a vague feature request. I'll periodically go through issues labeled with "Needs Info" and either ping the reporter or close them.

**Comment by TomAugspurger** [comment]
This topic was discussed in the meeting today: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit?usp=sharing

A brief summary:

We're pretty happy with the proposed labels.
- Size estimates are difficult. Trialing for the next month, and it's up to the maintainer to assign them (or not) as they see fit.
- Assigning issues is difficult: We don't want to discourage someone else from picking up an issue because it's been "assigned" and dropped. Trialing for the next month; maintainers can assign as they see fit and we'll check in.

---

What are the next steps? Do we need to ensure that all the repositories of interest (need to specify exactly what these are) have the same "label type" and "label size" labels, and "component" labels specific to that repository?

**Comment by quasiben** [comment]
From last week's meeting and summarizing the above discussion, I was going to start labeling issues \(to the best of my abilities).  We are going to keep the labels at least through SciPy sprints and evaluate if the labels were helpful/harmful/indifferent in the lead up to and during the sprints. 

Before proceeding I would like to get consensus on the the labels:

## Type Label
bug
question
good first issue
discussion
need info

## Component label

documentation
cicd
bag
array
dataframe

**Comment by jrbourbeau** [comment]
I generally like this proposed list of labels @quasiben, thanks for continuing this discussion. I'd put forward that we also keep the current ["io" label](https://github.com/dask/dask/issues?utf8=%E2%9C%93&q=label%3Aio+) as it's used relatively frequently.

**Comment by jrbourbeau** [comment]
Also, I'm happy to help with labeling existing (and new) issues. We should probably make that "discussion" label so we can label this issue : )

**Comment by jakirkham** [comment]
@quasiben, your proposal seems reasonable. Do you know if there is a way to ask users to select a type and then some components?

**Comment by quasiben** [comment]
I think we can ask uses to optionally select labels when creating an issue.  The issue template will need to be amended:
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Additionally, for me to start applying labels I think I need write access to the repository.  Perhaps this should wait until https://github.com/dask/governance/pull/12 is merged

**Comment by martindurant** [comment]
@quasiben , you now have rights.

This issue could be closed (we agreed in principle), although setting of the issue template has not yet happened.

**Comment by quasiben** [comment]
closing
