### ISSUE TITLE
DASK 1.1.1 breaks read_parquet with fastparquet

### ISSUE THREAD

**Issue by jimfulton** [dask/dask#4478]
This breaks for me with 1.1.1:

```
import dask.dataframe as dd

ddf = dd.read_parquet(
    "hdfs://foo.com/user/opensaedev/external_table/bar/*",
    engine='fastparquet',
)
```

with:

```
~/.conda/envs/python3/lib/python3.6/site-packages/dask/bytes/pyarrow.py in __init__(self, **kwargs)
     33 
     34     def __init__(self, **kwargs):
---> 35         self.fs = pa.hdfs.HadoopFileSystem(update_hdfs_options(**kwargs))
     36 
     37     @classmethod

TypeError: update_hdfs_options() got an unexpected keyword argument 'host'
```

OTOH, it works (assuming environment variables set properly and proper hdfs URL) with DASK 1.1.0.

It looks like the handling of hdfs URL parsing changed in a way that isn't compatible with fastparquet.

**Comment by martindurant** [comment]
This is already fixed in master, sorry for the trouble: https://github.com/dask/dask/blob/master/dask/bytes/pyarrow.py#L35

**Comment by jimfulton** [comment]
Doh, I should have searched closed issues before posting.

Thanks!

**Comment by rishi1111** [comment]
Is there any temporary solution to this. Or should i downgrade to 1.1.0 in the interim

**Comment by martindurant** [comment]
You can install from master, if you like to live on the edge.
