### ISSUE TITLE
NEP-18: mean_chunk() object __array__ method not producing an array

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4481]
Several Dask operations that utilize `mean_chunk()` from `dask/array/reductions.py` fail for Dask arrays created from non-NumPy (e.g., CuPy, sparse) arrays.

Some of the operations confirmed to fail are (including other non-core Dask projects):
* `dask.mean()`
* `dask.glm.algorithms.*`

A sample to reproduce the issue is given below, followed by its traceback.

```python
import cupy
import dask.array as da

x = cupy.random.random((5000, 1000))

d = da.from_array(x, chunks=(1000, 1000), asarray=False)

d.mean().compute()
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/local.py", line 459, in get_async
    raise_exception(exc, tb)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/compatibility.py", line 93, in apply
    return func(*args, **kwargs)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/dask/array/reductions.py", line 336, in mean_chunk
    result['n'] = n
ValueError: object __array__ method not producing an array
```

**Comment by mrocklin** [comment]
Hrm, @jcrist do you have any suggestions here?  The challenge is that we're creating an `empty` numpy array and then assigning into it.  This makes things hard for non-Numpy implementations like sparse or cupy.

Two thoughts:

1.  We could see if dask array is returning a tuple rather than a record array.  My guess is that it will get upset
2.  We could use `empty_like` for our dispatch rather than `empty`.  This would allow the `__array_function__` protocol to work as desired.

**Comment by jcrist** [comment]
We already have a dispatch for `empty`, found in `dask.array.reductions`, could cupy just register an implementation for that?

`empty_like` won't work, since you can't override the shape (unfortunately).

**Comment by mrocklin** [comment]
Right, following @jcrist 's suggestion this should be easy.  

@pentschev you probably want something like the following in `dask/array/backends.py`

```python
from .reductions import empty_lookup
empty_lookup.register(cupy.ndarray, np.cupy)
```

**Comment by pentschev** [comment]
> ```python
> from .reductions import empty_lookup
> empty_lookup.register(cupy.ndarray, np.cupy)
> ```

Yes, that probably would solve the problem, but `cupy.empty()` doesn't support a list of tuples as `dtype`. Just as means of reproduction consider the following:

```python
In [25]: n = cupy.array([[1000000.]])

In [26]: n
Out[26]: array([[1000000.]])

In [27]: n.shape
Out[27]: (1, 1)

In [28]: cupy.empty(n.shape, dtype=[('total', total.dtype), ('n', total.dtype)])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-ea9bfab84d63> in <module>
----> 1 cupy.empty(n.shape, dtype=[('total', total.dtype), ('n', total.dtype)])

~/.local/lib/python3.5/site-packages/cupy/creation/basic.py in empty(shape,
dtype, order)
     20 
     21     """
---> 22     return cupy.ndarray(shape, dtype, order=order)
     23 
     24 

~/src/cupy/cupy/core/core.pyx in cupy.core.core.ndarray.__init__()

~/src/cupy/cupy/core/_dtype.pyx in cupy.core._dtype.get_dtype_with_itemsize()

TypeError: unhashable type: 'list'
```

I'm not sure whether this is a bug or a missing feature in CuPy. But as far as I can tell, this empty array is only used for internal Dask computing, so an alternative would be to replace it by something else, since it's only used to hold two values by their names, just like a hash table.

**Comment by mrocklin** [comment]
Lets raise the list-of-tuple dtype issue on the cupy issue tracker to see
if they can add it.

In the meantime we might look to see if we can avoid using record arrays
(these are what list-of-tuple dtype arrays are called).  I can take a quick
look at this today.

**Comment by pentschev** [comment]
@mrocklin I'm opening the issue on CuPy's tracker. If you find an appropriate way of avoiding the use of record arrays, I could also work on the implementation if you'd like, just let me know.

**Comment by mrocklin** [comment]
Raised here: https://github.com/cupy/cupy/issues/2031

It looks like we can resolve this on our end just by adding a `np.dtype(...)` call around the list.

**Comment by mrocklin** [comment]
So the following change is probably needed and welcome on the dask side

```diff
-   result = empty(n.shape, dtype=[('total', total.dtype), ('n', n.dtype)])
+   result = empty(n.shape, dtype=np.dtype([('total', total.dtype), ('n', n.dtype)]))
```

**Comment by pentschev** [comment]
Yes, that should work. I can try it out now and submit a PR, or are you working on this already @mrocklin ?

**Comment by mrocklin** [comment]
All yours

**Comment by pentschev** [comment]
Well, there's yet another CuPy problem when assigning a value to result, I guess it can only handle indices with the bracket operator:

```python
Traceback (most recent call last):
  File "empty.py", line 9, in <module>
    result['n'] = n
  File "cupy/core/core.pyx", line 1183, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/_routines_indexing.pyx", line 49, in cupy.core._routines_indexing._ndarray_setitem
  File "cupy/core/_routines_indexing.pyx", line 726, in cupy.core._routines_indexing._scatter_op
  File "cupy/core/_routines_indexing.pyx", line 309, in cupy.core._routines_indexing._simple_getitem
ValueError: invalid literal for int() with base 10: 'n'
```

Looking at `cupy.core._routines_indexing._simple_getitem()`, this is where it fails:

```python
308         elif numpy.isscalar(s):
309             ind = int(s)
```

According to [NumPy's documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isscalar.html) a string is a scalar, and CuPy immediately tries to convert to an int, as it seems to be the case that only indices are expected there.

**Comment by mrocklin** [comment]
We should probably ask the cupy devs for help here.  Maybe raise a github
issue on cupy/cupy that asks how to combine two arrays into an array with a
structured dtype?

**Comment by pentschev** [comment]
Agreed. Perhaps this could be part of your recently opened issue https://github.com/cupy/cupy/issues/2031, since this is more of a follow-up case? If some fix like the one you suggested, this will definitely be next issue, so I see no reason to fix one without the other.

**Comment by mrocklin** [comment]
I've made an attempt at this in #4513 it's not complete though.  If anyone has time to investigate it further that would be welcome.

**Comment by pentschev** [comment]
I had a quick look here, but it really seems that it's a more complicated issue than it seemed at first. I will try to investigate a little further.

By the way, I would say this is probably the highest priority bug on the Dask side regarding the CuPy integration. I've seen many functions breaking due to `mean_chunk()`, and this is also the breaking point for Dask GLM algorithms as well. Most likely we'll uncover other bugs after fixing this as well, but we should really fix this soon.

**Comment by system123** [comment]
Should this be working with v2.1.0?

I've tried to recreate the SVD examples in the [Blog post](https://blog.dask.org/2019/03/18/dask-nep18) but get the `ValueError: object __array__ method not producing an array` issue when running np.svd on the dask-cupy array.

I tried using the latest master too and get the same error.
