### ISSUE TITLE
Dataframe set_index(inplace=True) doesn't work

### ISSUE THREAD

**Issue by smangham** [dask/dask#4484]
Fairly straightforward one, but I may have done something stupid:
```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({
        'a': [9, 8, 7],
        'b': [6, 5, 4],
        'c': [3, 2, 1]
})
ddf = dd.from_pandas(df, npartitions=1)
print('Rows: {}'.format(df.index.values))

df.set_index('a', inplace=True)
print('Pandas: {}'.format(df.index.values))

ddf.set_index('a', inplace=True)
print('Dask - inplace=True: {}'.format(ddf.index.values.compute()))

ddf = ddf.set_index('a')
print('Dask: {}'.format(ddf.index.values.compute()))
```
The output for this is:
```
Rows: [0 1 2]
Pandas: [9 8 7]
Dask - inplace=True: [0 1 2]
Dask: [7 8 9]
```
So `set_index(col, inplace=True)` doesn't work. Expected behaviour would be a warning or an error that this is an unsupported argument. The sort on index also differs but is documented and makes sense anyway.

**Comment by mrocklin** [comment]
I agree that an error here would be best.  Is it just this keyword, or do
we silently ignore all unknown keywords in that function?
