### ISSUE TITLE
NEP-18: fix() with CuPy array depends on __array_wrap__

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4496]
Calling `dask.array.fix()` on a Dask array created from a CuPy array fails as it depends on unimplemented `__array_wrap__` from CuPy. There's an issue open to add that feature to CuPy https://github.com/cupy/cupy/issues/589.

@mrocklin

**Comment by jakirkham** [comment]
FWIW raised issue ( https://github.com/numpy/numpy/issues/13100 ) to see if `fix` and a few other functions could be converted to ufuncs, which would be one way to solve this. Please feel free to join the discussion over there if it is of interest.

**Comment by pentschev** [comment]
Thanks @jakirkham, I've subscribed for notifications, I'll join if I can help with something. :)

**Comment by jakirkham** [comment]
Just in case it is needed, here's a workaround.

```python
np.where(a < 0, np.ceil(a), np.floor(a))
```

CuPy does implement [`where`]( https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.where.html ), which could be dispatched to via NEP 18. Also `ceil` and `floor` are both `ufunc`s, which already dispatch through the `__array_ufunc__` protocol.

**Comment by pentschev** [comment]
Closing this, since #4708 was merged already.
