### ISSUE TITLE
Improve visibility of openmp suggestions with dask.array

### ISSUE THREAD

**Issue by djhoese** [dask/dask#4514]
I mentioned this on gitter and thought it may help if this was more public on the dask documentation as well. A lot of users of the SatPy library (which uses xarray and dask) end up running their operational processing on one or two high performance servers with 30-40 cores. Limiting the number of dask workers on a threaded scheduler has become something that many users understand to avoid memory errors from too many chunks being processed at once. However, I learned yesterday that using numpy with openmp can also be a huge problem. Having openmp create a lot of threads on these servers is not a huge issue in a single thread/process, but combined with dask it is (see details below).

I'm wondering if OpenMP and `OMP_NUM_THREADS` should be mentioned more in the documentation when either introducing dask arrays or talking about performance. Right now I think it is only mentioned [here](http://distributed.dask.org/en/latest/faq.html#error-when-running-dask-worker-about-omp-num-threads) and that is specifically about errors when working with OpenMP. Am I missing anything? I'm guessing you would be against automatically setting `OMP_NUM_THREADS` in dask and I can agree with that. If I was to add more to the docs about this, where would you prefer I do it?

<details>
My processing was configured for 8 workers on a 48 core machine and without limiting openmp it was creating 384 threads. The processing I was doing took about 12m30s. After being surprised by the number of threads, I forced openmp to 2 threads and the processing now created an understandable 20-30 threads and completed in 10m30s.

</details>

**Comment by mrocklin** [comment]
I'm in favor of documentation that helps people past common issues. The challenge is how to list common issues while not flooding documentation with them.  There are probably 10 issues of similar-or-greater importance to `OMP_NUM_THREADS` for dask array workloads (use good storage, chunk your storage appropriately, don't use very small chunks, don't use bad compression, ...) and so the approach of putting these things front-and-center generally means that nothing is front-and-center.

What has worked decently well is the [Delayed best practices](http://docs.dask.org/en/latest/delayed-best-practices.html) documentation page.  I think that it would be good to establish such a page for each of the collections that could hold information like this.  I think that a start on such a document would be a good idea if you're interested in starting it up.

**Comment by djhoese** [comment]
Yes, I'll see if I can find the time. I've definitely read the Delayed best practices multiple times. Do you think this should be `dask.array` specific best practices? I guess we'll deal with overlap with other things later (link or duplicate). So the list:

1. limit workers
2. limit openmp threads
3. good storage
4. chunk your storage appropriately (what does this mean?)
5. no very small chunks
6. choose good compression (are you thinking input data or output data? zarr only or all formats?)

**Comment by mrocklin** [comment]
Yes, I think that a new page that was array specific but that had the same structure of the Delayed best practices page would be good.

I recommend that you only write down the things that you're pretty comfortable with.  If you're not sure about some of those then leave them for others.

**Comment by jrbourbeau** [comment]
Closing as `OMP_NUM_THREADS` was included in #4705
