### ISSUE TITLE
`da.bincount` fails on numpy arrays

### ISSUE THREAD

**Issue by zklaus** [dask/dask#4517]
The functions `apply_along_axis` and `bincount` don't play nicely together.
The snippet

```
import dask.array as da
o = da.ones((1000, 1000), dtype=int)
da.apply_along_axis(da.bincount, 0, o, minlength=10).compute()
```
leads to the exception
```
Traceback (most recent call last):
  File "./testdask.py", line 7, in <module>
    da.apply_along_axis(da.bincount, 0, o, minlength=10).compute()
  File ".../lib/python3.7/site-packages/dask/array/routines.py", line 324, in apply_along_axis
    test_result = np.array(func1d(test_data, *args, **kwargs))
  File ".../lib/python3.7/site-packages/dask/array/routines.py", line 543, in bincount
    for i, _ in enumerate(x.__dask_keys__())}
AttributeError: 'numpy.ndarray' object has no attribute '__dask_keys__'
```

Essentially, `bincount` relies on the passed array being a dask array and fails on np/np.ma arrays.
This can be fixed by including a `x = asarray(x)` at the top of bincount, but I am not sure if that is the way to go.

This might be related to #3727.

**Comment by mrocklin** [comment]
Apply_along_axis should take a function that consumes and produces numpy arrays.  I recommend replacing da.bincount with np.bincount

```python
In [1]: import numpy as np

In [2]: import dask.array as da
   ...: o = da.ones((1000, 1000), dtype=int)
   ...: da.apply_along_axis(np.bincount, 0, o, minlength=10).compute()
Out[2]:
array([[   0,    0,    0, ...,    0,    0,    0],
       [1000, 1000, 1000, ..., 1000, 1000, 1000],
       [   0,    0,    0, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]])
```

**Comment by zklaus** [comment]
Thanks for the comment, that works. Would it be worthwhile to make this clearer in the documentation? It seems that most methods in the array api work on dask objects, this being one of the exceptions.

If the obstruction to this is the use of `@wraps`, maybe we could have a custom wrapper decorator that allows for the addition of a dask note?

**Comment by jrbourbeau** [comment]
> Would it be worthwhile to make this clearer in the documentation?

This would be a nice addition!

Improving our docstring wrapping is an ongoing effort (see #3265) and any interest you have in helping improving the situation would be very welcome.

**Comment by jakirkham** [comment]
The docstring wrapping has since been improved. Am going to go ahead and close this, but please feel free to raise a new issue if there are other things off with this change. Thanks!
