### ISSUE TITLE
Merge dispatch

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4521]
I would like to use parts of the dask.dataframe merge codebase for dask-cudf merge.  To do this, I need to replace instances of `pd.merge` with some generic dispatchable `merge` function.  

We do this today in many places throughout the codebase for systems like cudf, sparse, and cupy.  For those we use our custom singledispatch implementation.  The `merge` function is different in that we probably want to dispatch against two inputs.

The natural thing to do here from my perspective is to use the `multipledispatch` library.  How do people feel about this?  We would have dask[dataframe] depend on multipledispatch, and add a dispatch definition in the dask codebase that included just the pandas case.  Other libraries would then import and extend this dispatched implementation.

cc @jcrist @martindurant

**Comment by jcrist** [comment]
What kind of dispatch do you think needs to be done here?

For a function `merge(df, df) -> df` with 2 types (`pandas`, `cudf`), the following might take place:

```
merge(pandas, pandas) -> pandas
merge(pandas, cudf) -> cudf
merge(cudf, pandas) -> cudf
merge(cudf, cudf) -> cudf
```

This pattern could be implemented easily in code by adding a priority dispatch. I'd argue that this would be simpler to understand, and wouldn't require an additional dependency. A simple version might look like (works with existing dask code):

```python
from dask.utils import Dispatch
import pandas as pd
import cudf

priority_to_type = {}
type_to_priority = {}

def register_priority(type, value):
    priority_to_type[value] = type
    type_to_priority[type] = value

def type_to_use(*values):
    priority = max(type_to_priority.get(type(v), -1) for v in values)
    return priority_to_type[priority]

register_priority(pd.DataFrame, 0)
register_priority(cudf.DataFrame, 1)

merge_dispatch = Dispatch('merge')

@merge_dispatch.register(pd.DataFrame)
def merge_pandas(df1, df2):
    ...

@merge_dispatch.register(cudf.DataFrame)
def merge_cudf(df1, df2):
    ...

def merge(df1, df2):
    df_type = type_to_use(df1, df2)
    func = merge_dispatch.dispatch(df_type)
    return func(df1, df2)
```

I'd argue that in most cases:
- The number of types we'd be dispatching on would be low
- Functions taking disparate types would likely upcast to some common type before continuing
- The number of arguments we care about would be low (in merge's case it's just 2)

As such I think my preference would be to roll a simple custom dispatch like the above (which works with the existing `dask.utils.Dispatch` and is only a few lines of code), and only move to `multipledispatch` if necessary.

**Comment by mrocklin** [comment]
I've pushed up https://github.com/dask/dask/pull/4522 with an initial implementation with multipledispatch (started this before @jcrist 's recent comment) just to get a sense of how invasive this is.

**Comment by mrocklin** [comment]
Happy to do something like what is proposed.  The main argument I could see for something like multipledispatch is that we've spent some non-trivial amount of time tweaking our custom `Dispatch` object over the last few years.  At some point we might want to punt and use something used and maintained by others as well (though admitedly, not by that many).

**Comment by mrocklin** [comment]
I'm happy either way though.  They're both easy to do.

**Comment by jcrist** [comment]
I think for now I'd prefer not to add a new dependency, and see how doing this with a priority feels. If more complicated behavior is needed at some point then I'd be open to using multipledispatch.

**Comment by mrocklin** [comment]
OK, so I'm curious about how best to implement your suggestion above.  Do people who want to register a new type register both to `merge_dispatch` and to the `register_priority` function?  Or is there some extension to `Dispatch` that you're proposing?

**Comment by jcrist** [comment]
Right now I'm suggesting a hack like the above to make what you need now work. So yes, new `register_priority` function. My guess is the prioritization will be the same for all functions that take disparate types, so the priority lookup could be shared between merge, etc...

**Comment by mrocklin** [comment]
OK, in my PR I've now switch to using Python's standard method dispatch, which should work in all cases except for `merge(pandas, cudf)`.  

I'm inclined not to add in something like register priority for just this case, just because I would like to avoid making a new system.

I find myself preferring `multipledispatch` long term, which I view as a stable and lightweight dependency.  That's probably just because I'm more familiar with it though.
