### ISSUE TITLE
Design Question : an alternative implementation of Dataframes using Dask Arrays ?

### ISSUE THREAD

**Issue by jjerphan** [dask/dask#4524]
Hello,

I went through the [internal design page for DataFrame](http://docs.dask.org/en/latest/dataframe-design.html) to know more about the way they are constructed.

I just got a random and naïve question when reading this:
> Dask DataFrames coordinate many Pandas DataFrames/Series arranged along an index.

Maybe this has already been studied, but : _could it be possible to design DataFrames with Dask Arrays similarly to what Pandas is doing with Numpy array internally?_

Maybe the actual design of Dask Dataframe is convenient and also implementable compared to this one that may be out of scope.

Thank you for your time and effort put in this project!

**Comment by mrocklin** [comment]
Thanks for the question Julien, is there a particular objective that you're
trying to accomplish here?  Are there use cases where Dask DataFrame
doesn't currently solve your needs where you think this different design
might be more effective?

**Comment by martindurant** [comment]
There have been some questions around chunking on columns as well as rows, which maybe such an implementation would allow for - but only if the index were applied to every column-chunk, and at the cost of a lot more complexity when, for example, grouping on a column in one chunk and aggregating on a column in another. 

To @jjerphan , I think it's fair to say that the current design is the simplest way to scale pandas functionality to big data, applying pandas methods to real pandas dataframe pieces. The internal numpy stuff in pandas is complex and probably wouldn't work straight-forwardly on dask-arrays (and may be changing substantially). An implementation of an extension-type wrapping a dask-array could be done now and might be interesting, but there's no obvious pressure to try to do this.

**Comment by jjerphan** [comment]
> Thanks for the question Julien, is there a particular objective that you're trying to accomplish here? Are there use cases where Dask DataFrame doesn't currently solve your needs where you think this different design might be more effective?

Not specifically, it is just for curiosity: I just saw those two routes to build Dataframes and was wondering why the first one has been chosen. I think @martindurant answered it:

> [...] it's fair to say that the current design is the simplest way to scale pandas functionality to big data, applying pandas methods to real pandas dataframe pieces. The internal numpy stuff in pandas is complex and probably wouldn't work straight-forwardly on dask-arrays (and may be changing substantially).

I agree, especially when it come to methods that can be implemented simply by mapping their pandas counterpart on Dask Dataframe partitions.

The second roads could be taken, but it would require much more to do and to know if this would be a good fit is quite uncertain.

Thanks for your answers.
