### ISSUE TITLE
Bugfix release of dask/dask

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4536]
I'm inclined to push out a small bugfix release of dask/dask.  Updating our examples to the recent release exposed some non-trivial bugs.  See https://github.com/dask/dask-examples/issues/62

I plan to do this later this evening if there are no objections.

**Comment by jakirkham** [comment]
SGTM

**Comment by mrocklin** [comment]
Pushed 1.1.3 to PyPI

**Comment by jrbourbeau** [comment]
Thanks @mrocklin
