### ISSUE TITLE
Test builds with CuPy

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4538]
I've been thinking that on the scope of NEP-18 it will become very important for us to have tests running on PRs with CuPy as well. I know this may be problematic due to the need for CUDA-capable GPU(s).

Is there any discussion towards that end already? Given the resources (mostly hardware, I assume), I'd be happy to help set it up and get at least some testing in place so that we can start getting more confident. If I recollect correctly, I think I've seen some of the existing CuPy tests are failing in upstream.

**Comment by mrocklin** [comment]
I think that testing Dask Array + CuPy sounds like a great idea.

For as long as there isn't a nice public GPU-enabled CI system my guess is
that we don't want to attach it to this repository specifically, but
perhaps we can set up a nightly testing suite to run on the NVIDIA
hardware?  cc @mike-wendt (no pressure/rush)

**Comment by pentschev** [comment]
Nightly builds are a start, but I think it would be better to have CuPy tested for PRs as well. If we want to save time on NVIDIA hardware, it would probably suffice to test only CuPy-related tests there and the rest on the existing CI.

**Comment by quasiben** [comment]
I think we can close this as we now have GPU dask tests running in UCX-Py https://github.com/rapidsai/ucx-py/blob/c923a304e426be90177368781adbbe5fcf943bf7/ci/gpu/build.sh#L107-L116
