### ISSUE TITLE
Remote operations on dask dataframe

### ISSUE THREAD

**Issue by RealPolitiX** [dask/dask#4540]
When operating on remote data using dask dataframe, is dask automatically using all the network transfer bandwidth or there is a way to set the transfer rate limit?

**Comment by mrocklin** [comment]
Dask is just calling functions like requests.get (for gcs) or boto (for s3)
or arrow (for hdfs) under the hood.  You might want to consult those
projects to see if there is a way to limit bandwidths.

**Comment by RealPolitiX** [comment]
Thanks, Matthew!
