### ISSUE TITLE
Documentation does not match behaviour

### ISSUE THREAD

**Issue by suvayu** [dask/dask#4545]
I have now encountered this several times, the docstring, or the API docs don't always match actual behaviour of dask classes.  Here's the latest example, below I'm trying to concatenate several dask dataframes:

    dfs = [
        pd.DataFrame(np.random.randint(10, size=(3, 2)), columns=('a', 'b'))
        for i in range(3)
    ]
    ddfs = [dd.from_pandas(df, npartitions=1) for df in dfs]

These fail:

    [ ]: ddfs[0].append(ddfs[1:])

    NotImplementedError                       Traceback (most recent call last)
    <ipython-input-16-fde3c66e1f54> in <module>
    ----> 1 ddfs[0].append(ddfs[1:])

    ~/.local/lib/python3.6/site-packages/dask/dataframe/core.py in append(self, other)
       2956         elif is_series_like(other):
       2957             other = other.to_frame().T
    -> 2958         return super(DataFrame, self).append(other)
       2959
       2960     @derived_from(pd.DataFrame)

    ~/.local/lib/python3.6/site-packages/dask/dataframe/core.py in append(self, other)
       1687         if isinstance(other, (list, dict)):
       1688             msg = "append doesn't support list or dict input"
    -> 1689             raise NotImplementedError(msg)
       1690
       1691         return concat([self, other], join='outer', interleave_partitions=False)

    NotImplementedError: append doesn't support list or dict input

    [ ]: ddfs[0].append(ddfs[1], ignore_index=True)
    TypeError                                 Traceback (most recent call last)
    <ipython-input-17-bc64a590a6d8> in <module>
    ----> 1 ddfs[0].append(ddfs[1], ignore_index=True)

    TypeError: append() got an unexpected keyword argument 'ignore_index'

However the [doc](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.append) says both of the above are correct!

Am I missing something obvious?

**Comment by TomAugspurger** [comment]
We have a general issue about dask dataframe docstrings. Many are taken from pandas. The decorator borrowing from pandas is supposed to note when a parameter isn't supported (note that the signature in http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.append only includes `other`).

FYI, for pandas and dask.dataframe you'll typically want `concat` rather than `.append`

**Comment by suvayu** [comment]
Okay thanks, I'll go by only the signature from now on.

About `concat`, I knew that about `pandas`, but I couldn't find it in the "contents" at the beginning of the dask dataframe API page, but now I see there is an "Other functions" section that does not show up in the contents!

Thanks again :)
