### ISSUE TITLE
read_parquet + getitem optimization no longer working

### ISSUE THREAD

**Issue by jmunar** [dask/dask#4546]
The optimization introduced in #1785 doesn't work in master.

```python
import dask
import dask.dataframe as dd
import pandas as pd

# Create test dataset
df = pd.DataFrame({'a': [1] * 10000, 'b': [2] * 10000})
df.to_parquet('test.parquet', engine='fastparquet')

# Open it, get a subset of items and try to optimize the graph
ddi = dd.read_parquet('test.parquet', engine='fastparquet')[['a']]
dsk = ddi.dask
dsk2 = dd.optimize(dsk, ddi.__dask_keys__())

dsk2[('read-parquet-getitem-e42c1003708b81c7d6bfcbf6eaa5ac3d', 0)]
```
returns

```python
(subgraph_callable, (<function _read_parquet_row_group>,..., ['a', 'b'], ...), ['a'])
```
whereas in the past we were seeing:

```python
(<function _read_parquet_row_group>,..., ['a'], ...)
```
The problem seems to be in dask.optimization.fuse_selections not handling subgraph_callable. I see 2 possible solutions:

* Convert read_parquet into a HighLevelGraph, so that the optimization can be performed between 2 layers, instead of among tasks
* Modify fuse_selections to handle subgraph_callable

What would you suggest? I could find some time to work on it. Thank you for your help!

**Comment by mrocklin** [comment]
Yes, that's correct.  It conflicted with another larger optimization that was considered more important. 

I started down the path of a full parquet refactor here: https://github.com/dask/dask/pull/4336

My hope is that after things get cleaned up a bit there that we'll be able to add this optimization back in, but now for all backends.  If you have time to push forward on that refactor, or on the upstream Arrow issues around metadata writing, then that would be welcome.  If you have time to add the optimization into that refactor that would also be welcome.

**Comment by martindurant** [comment]
As a less-than-great workaround, you can include the columns you want the backend to load, and therefore skip the graph optimisation step altogether.

**Comment by jmunar** [comment]
Thank you for your comments! @martindurant, I am using your proposed workaround for the moment, it works but I really like the approach of creating my dataframe with hundreds of columns and only read the 4-5 that I need for my typical operations.

I like what I have learnt so far about high level graphs, and I believe that the thrift object with row groups information can be encoded as one layer using dask.delayed, and then create the dataframe object as a second layer. If this is the case, the optimization should be straightforward to implement. I will keep on playing with it, and if it works I will start a pull request.

**Comment by timothydmorton** [comment]
Commenting to follow this issue.  I am interested in contributing to help move this forward, but will need some guidance as to where to begin.

**Comment by timothydmorton** [comment]
@jmunar do you have any more recent thoughts on this issue?

**Comment by mrocklin** [comment]
If we solve this problem at the high level graph layer (which seems best) then probably we would want to construct a Mapping type for `read_parquet`.  An example high level mapping type is the Blockwise type here: 

https://github.com/dask/dask/blob/0922a872e34445970c65d2275ed56a920f7d826d/dask/blockwise.py#L128-L136

That Mapping type is paired with an optimization function, `optimize_blockwise` here: 

https://github.com/dask/dask/blob/0922a872e34445970c65d2275ed56a920f7d826d/dask/blockwise.py#L441-L464

Which is then used in the dataframe optimization code explicitly here: 

https://github.com/dask/dask/blob/0922a872e34445970c65d2275ed56a920f7d826d/dask/dataframe/optimize.py#L9-L12

All of this is pretty unstructured today.  Dask doesn't do enough optimizations to have a firm structure about how we optimize graphs, particularly at the high level.  So, whoever does this work can probably proceed in a variety of ways, many of which will be fine.  Maybe, after we have a few of these optimizations (I can imagine doing the same thing with `read_csv` or `join` for example) then it will make sense to structure them a bit more strictly.  Until then, exploration is probably encouraged.

**Comment by mrocklin** [comment]
So, I would make a Mapping class that had enough information to generate the task graph created in a read_parquet call.  I would have the read_parquet call return that as a layer rather than a concrete `dict` object.  

I would then write a function that took a `HighLevelGraph`, and looked through all of the layers to find cases where a ReadParquet mapping was followed by a layer that picked out columns, and then returned a new `HighLevelGraph` with those two layers changed appropriately.  I would then call that function within dask.dataframe.optimize.  

There are some corner cases to be aware of here, like what if we have two dependents on the read_parquet call :

```python
df = dd.read_parquet(...)
z = df.x + df.y
```

But those sorts of problems will probably be easier to think about after the initial work is up in a PR

**Comment by martindurant** [comment]
Note that you can always do better by hand: change the inputs in the loading functions to include columns=, or even select which partitions to load only after setting up the computation. For example, geo/datashader has an interesting mode for selecting from parquet depending on an axes viewpoint. We would, of course, try to do as much as possible automatically.

```
z = df.x + df.y
```
This kind of thing is interesting, certainly don't want to end up loading each partition twice, even if each time we only pick some pieces.

**Comment by timothydmorton** [comment]
Thanks guys; I'll start to take a look at this, and see where I can get.

**Comment by jmunar** [comment]
@timothydmorton nice that you pick up on this. I tried embedding read_parquet into a blockwise, embedding the row groups as a delayed layer. But I didn't succeed, so ended up doing an extremely ugly using "low level" graphs

**Comment by timothydmorton** [comment]
@mrocklin any suggestions on how I might identify a "layer that picks out columns"?  I'm using the example setup in https://github.com/dask/dask/blob/8001ee2e258f3f27d40e78990c5b98d44edc138e/dask/dataframe/io/tests/test_parquet.py#L517 and the only way I can come up with to identify that a layer is a "column-picking-out" layer is the fact that its name has `'getitem'` in it, which seems somewhat flimsy at best...  Any other suggestions?

**Comment by timothydmorton** [comment]
i.e., can I test for a specific method(s) being the callable?

**Comment by timothydmorton** [comment]
And to further clarify the first part of your suggestion, were you suggesting the new `ReadParquet` mapping to replace the `subgraph` in this call?
https://github.com/dask/dask/blob/f6c2449a000a72f05e41d0208d80696bc257d2ab/dask/dataframe/io/parquet/core.py#L291

**Comment by mrocklin** [comment]
There really isn't any standard way to do this today.  You're in very new territory for all of us.  Really, the only constraint is that you make sure that whatever you do works well with how `DataFrame.__getitem__` operates.  I could imagine making a subclass of Blockwise that was specific for getitem and testing for that, or, as you suggest just testing the value of the callable within the Blockwise call.  

We don't have any best practices around optimizations yet, so as long as what you do is decently simple it will be interesting to see.  If you complete this work then it would also be good to get your thoughts on the experience, and what we might do to design things to make optimizations like this more effective in the future.

**Comment by mrocklin** [comment]
> And to further clarify the first part of your suggestion, were you suggesting the new ReadParquet mapping to replace the subgraph in this call?

Yes.
