### ISSUE TITLE
Monthly Meeting: March 7th at 16:00 UTC

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4552]
As a reminder, the monthly meeting is tomorrow (March 7th) at 16:00 UTC.

- Minutes: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit
- Video: https://appear.in/dask-dev
- Calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=MXRmc2sxNDVocm1ycTI5YjEyazFhN2Vsa2FfMjAxOTAyMDdUMTYwMDAwWiA0bDB2dHMwYzFjZ2RicTVqaGNvZ2o1NXNmc0Bn&tmsrc=4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com&scp=ALL

I encourage people to think about issues that may need discussion and add them to the agenda (first link)

**Comment by jakirkham** [comment]
Updated the title to reflect the OP. Hope that is ok :)

**Comment by stsievert** [comment]
It'd be helpful to add the "community" tag.
