### ISSUE TITLE
Fix Pandas warnings from Dask Dataframe test suite

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4568]
There are a variety of warnings that show up when we run the dask.dataframe test suite with a new version of Pandas. 

conda install pandas
py.test dask/dataframe --verbose

Some examples

```
  /Users/mrocklin/workspace/dask/dask/dataframe/utils.py:391: FutureWarning: Creating a DatetimeIndex by passing range endpoints is deprecated.  Use `pandas.date_range` instead.
  /Users/mrocklin/workspace/dask/dask/dataframe/utils.py:411: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  /Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/fastparquet/util.py:221: FutureWarning: A future version of pandas will default to `skipna=True`. To silence this warning, pass `skipna=True|False` explicitly.
```

If anyone wants to help out, fixing these appropriately would be very welcome.

I'm marking this as a good first issue not because it's very easy, but because it doesn't require that much understanding of the Dask codebase.  My guess is that someone with moderate experience with Pandas will probably find it doable.

**Comment by HSR05** [comment]
@mrocklin do we just need to correctly fix the deprecated keywords or did i get it wrong? Can you guide me a little so that i can start working on it? Thanks 👍

**Comment by TomAugspurger** [comment]
It'll depend a bit on the warning. For something like `.codes` ->
`.labels`, we'll need to change it (while maintaining backwards compat for
older pandas).

The pandas release notes of the version it was added should give some
guidance too.

**Comment by abhinavralhan** [comment]
@TomAugspurger  @mrocklin this https://github.com/dask/dask/commit/c358a0b2ab28942a31a85b76f6019cc54ea2fd06 suppresses all warnings produced. verified it via the command `py.test dask/dataframe --verbose`.

**Comment by mrocklin** [comment]
We would like to actually change our behavior that Pandas is warning us
about, otherwise user code will break in the future.

A start on this is here: https://github.com/dask/dask/pull/4576/files

**Comment by HSR05** [comment]
@mrocklin I was able to test the suite using py.test but could not find more warnings. I resolved the ones that are shown as example in your comment. I'll figure out and run the test suite again. Once i resolve all the pandas warnings, I'll make a PR. Cheers 👍  

> 
> 
> There are a variety of warnings that show up when we run the dask.dataframe test suite with a new version of Pandas.
> 
> conda install pandas
> py.test dask/dataframe --verbose
> 
> Some examples
> 
> ```
>   /Users/mrocklin/workspace/dask/dask/dataframe/utils.py:391: FutureWarning: Creating a DatetimeIndex by passing range endpoints is deprecated.  Use `pandas.date_range` instead.
>   /Users/mrocklin/workspace/dask/dask/dataframe/utils.py:411: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
>   /Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/fastparquet/util.py:221: FutureWarning: A future version of pandas will default to `skipna=True`. To silence this warning, pass `skipna=True|False` explicitly.
> ```
> 
> If anyone wants to help out, fixing these appropriately would be very welcome.
> 
> I'm marking this as a good first issue not because it's very easy, but because it doesn't require that much understanding of the Dask codebase. My guess is that someone with moderate experience with Pandas will probably find it doable.

**Comment by HSR05** [comment]
@mrocklin #4576 does not resolve this too?

**Comment by mrocklin** [comment]
A lot of these were resolved in https://github.com/dask/dask/pull/4576 

Closing
