### ISSUE TITLE
Need to create some non-serializable objects on Workers before task execution and reference them in from tasks...

### ISSUE THREAD

**Issue by Felix-neko** [dask/dask#4570]
Hi folks! And thank your for such a great project.

I want to execute MATLAB scripts from Python dask tasks (implemented as @delayed-functions) via MATLAB API for Python. To do that, I must at first create the MATLAB engine instance to run MATLAB on the machine). MATLAB engine initialization is slow (about 5-10 seconds), much slower than the tasks, and I know that I don't need more than one engine per worker (it eats too much memory and utilizes all CPU).

I want to to the following:

- run some initialization code for my Workers to create all the objects I need to call from my task functions
- save the objects in the memory of each worker
- run the tasks that will use the objects from its worker.

Can you please tell me, how can it be done?

**Comment by mrocklin** [comment]
The simplest way is perhaps to create the object in your own library in some global state

```python
# mylibrary.py

my_obj = []

def get_my_obj():
    if not my_obj:
        my_obj.append(create_my_complex_object())
    return my_obj[0]
```
