### ISSUE TITLE
Readthedocs builds not triggering

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4575]
I'm not sure why, but readthedocs builds are no longer being triggered when we merge commits into master.

**Comment by TomAugspurger** [comment]
I notice that our readthedocs webhook is broken at https://github.com/dask/dask/settings/hooks. Looking into it now. May need to create a new one.

**Comment by TomAugspurger** [comment]
I created a new Github Integration on readthedocs and added a new webhook on Github. following the directions at https://docs.readthedocs.io/en/stable/webhooks.html

I removed the old web hooks. Didn't do any investigation into why they started failing (a couple weeks ago I think).

The ping on the new webhook succeeded. Will keep an eye on future builds, but hopefully this is fixed now.
