### ISSUE TITLE
Accept `dtype` in RandomState.randint

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#4579]
NumPy 1.11 added an optional `dtype` argument to RandomState.randint

```
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int', etc, so byteorder is not available
    and a specific precision may have different C types depending
    on the platform. The default value is 'np.int'.

    .. versionadded:: 1.11.0
```

dask-ml would like to make use of that.

In https://github.com/dask/dask/blob/master/dask/array/random.py#L334, we may be able to add a `dtype='l'` argument, and pass that through to `self._wrap` A PR doing that and adding tests would be most welcome.

**Comment by mrocklin** [comment]
Sounds good to me

**Comment by HSR05** [comment]
I added the argument` dtype='1'` in  https://github.com/dask/dask/blob/master/dask/array/random.py#L334 and passed it through `self._wrap`. Can you review it and guide me for adding tests? Thankyou.

**Comment by HSR05** [comment]
@mrocklin @jrbourbeau  i created a PR (#4607) for this. I am sorry for the previous mess. Can you review it please? Thankyou.
