### ISSUE TITLE
Increase minimum supported NumPy/Pandas versions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4580]
Currently we claim to require the following versions:

```python
extras_require = {
  'array': ['numpy >= 1.11.0', 'toolz >= 0.7.3'],
  'bag': ['cloudpickle >= 0.2.1', 'toolz >= 0.7.3', 'partd >= 0.3.8'],
  'dataframe': ['numpy >= 1.11.0', 'pandas >= 0.19.0', 'toolz >= 0.7.3',
                'partd >= 0.3.8', 'cloudpickle >= 0.2.1'],
  'distributed': ['distributed >= 1.22'],
  'delayed': ['toolz >= 0.7.3'],
}
```

Do we want to increase some of these versions?  I think that this question is motivated by two parts:

1.  How much of a pain for maintainers is it to support older versions?
2.  How much of a pain for users is it to upgrade?

We don't currently receive any complaints of the form "Dask's version requirements are too modern for me to use", so we can probably push things a bit.  

cc @TomAugspurger @jcrist @jakirkham

**Comment by TomAugspurger** [comment]
I'd recommend bumping pandas to 0.21.x. That gives us pandas' new CategoricalDtype, which seems pretty important for distributed workloads.

0.21.0 was released Oct. 28, 2017.

**Comment by mrocklin** [comment]
Would we want to bump even further?

**Comment by TomAugspurger** [comment]
I didn't see any single thing that jumped out. There are a decent number of
checks for 0.23.0, but those are split among new keywords
and features added to pandas. If we bump further, I would recommend that.

**Comment by jakirkham** [comment]
If we were to bump NumPy, I'm not sure there is much value in just going to 1.12 (maybe I'm forgetting something). So would encourage going to 1.13 at a minimum as that introduced `__array_ufunc__`, which will allow us to clean up a significant amount of boilerplate in Dask.

**Comment by mrocklin** [comment]
Any further thoughts on this?  @jcrist @shoyer any thoughts on becoming more aggressive in NumPy/Pandas version requirements?

**Comment by jakirkham** [comment]
To summarize it sounds like the recommendation is as follows.

* NumPy 1.13
* Pandas 0.21.0

Does that sound right? Is this agreeable?

**Comment by shoyer** [comment]
+1 for updating to NumPy 1.13 and pandas 0.21.0.

**Comment by jcrist** [comment]
Fine by me. This is currently blocking a PR, shall we go for it?

**Comment by mrocklin** [comment]
There are a couple +1s, no one seems opposed.  I think it's fine to go ahead.

**Comment by jcrist** [comment]
On it.
