### ISSUE TITLE
Update `dask.optimization` docs to remove automatic culling in examples

### ISSUE THREAD

**Issue by lsouiki** [dask/dask#4585]
Hi guys,

I'm puzzled about the disappearance of culling when we want to get parts of the graph.

Previously, calling dask.get would trigger the culling (since #2 actually!). And that's what's explained [in the doc](http://docs.dask.org/en/latest/optimize.html).
  
But the behaviour has changed. I'm not sure if it was a side consequence of PR #3856 or just #4219. 
  
I would guess it's a bit of both, though #4219 removed that test checking the culling:     
    https://github.com/dask/dask/commit/e6af2e42f08b0d9d3f29c00a0bd6c9c33dad2404#diff-7e0fa7dbafa23ca8c9a94bff278b4f3f

  
As a consequence, the [documentation and samples](http://docs.dask.org/en/latest/optimize.html) are now wrong: dask.get or dask.threaded.get do not optimize. 

In oldish versions, we were able to call dask.get and have some culling done. Up until 1.0.0, we had the same behaviour through dask.core.get. But since 1.1.0, even that optimization is gone.

Is this the expected behaviour ? Or are we supposed to wrap everything in delayed ? 

Code to reproduce the issue:

```
import dask
from operator import add
import traceback


def crash(x):
    print("undesired",x)
    traceback.print_stack()


d = {'x': 1,
     'y':   (add, 'x', 10),
     'out': (add, 'y', 10),
     'crash': (crash, 'x'),
}

# OK up until 1.0.0. NOK since 1.1.0
dask.core.get(d, 'out')

# NOK, even in 1.0.0
dask.get(d, 'out')

# NOK, even in 1.0.0
dask.threaded.get(d, 'out')
```

**Comment by mrocklin** [comment]
It looks like the discussion for this was here:
https://github.com/dask/dask/issues/3735

I think that the current recommendation would be to cull on your own if
you're writing raw graphs yourself.

Thanks for the pointer to the incorrect documentation.  Do you have any
interest in removing these lines in a PR?

**Comment by caseyclements** [comment]
Hmmm.  8 hours after this was opened, I came here to open the same issue. The example of cull in the documentation specifically works with a custom graph. Does the 'local scheduler' include all but distributed, or is just the synchronous one?

**Comment by mrocklin** [comment]
There are two schedulers, the local one which uses threads, processes, or
single-threaded, and the distributed scheduler.

**Comment by lsouiki** [comment]
> Do you have any interest in removing these lines in a PR?

Hi Matthew. Sure, I can give it a try. Give me a bit of time to set-up a dev env and make sure I understand the context of culling and inlining, and I'll see what I can do.
