### ISSUE TITLE
Performance considerations of bag.flatten()

### ISSUE THREAD

**Issue by joel-odlund** [dask/dask#4589]
Loading items from json lists into dask bags is typically done using `bag.flatten()`, such as

```
items  = db.read_text(list_of_jsons_with_lists).map(json.loads).flatten()
```
Reading the doc, it is not clear what the flatten operation is doing,  and in particular how costly it is in terms of shuffling data beteween nodes on a cluster.   If performance is an issue, is `bag.flatten()` something to avoid?

Some note about this in the documentation would be helpful,  similar to what is given for other bag operarations.

**Comment by mrocklin** [comment]
Have you run into a performance issue?  My guess is that bag.flatten is embarrassingly parallel. 

We don't currently list performance for every operation in docstrings.  If this is something you'd like to take on it could be a useful project.

**Comment by mrocklin** [comment]
Closing due to lack of response.
