### ISSUE TITLE
DataFrame.set_index(..., sorted=True) causes data to be in the wrong partition

### ISSUE THREAD

**Issue by bchu** [dask/dask#4591]
```
import pandas as pd
import dask.dataframe as dd
df = pd.DataFrame([[1,2],[1,4],[1,6],[2,3]], columns=['a', 'b'])
df = dd.from_pandas(df, npartitions=2).set_index('a', sorted=True)
print(df.get_partition(0).head())
print()
print(df.get_partition(1).head())
print('\nBut divisions are:', df.divisions)
```

returns

```
   b
a   
1  2
1  4

   b
a   
1  6
2  3

But divisions are: (1, 1, 2)
```

This could just be my misunderstanding of the `sorted` kwarg. The documentation for the `divisions` kwarg vaguely suggests this could be a problem: "Note that if sorted=True, specified divisions are assumed to match the existing partitions in the data." If so, this could be more clearly documented for the `sorted` kwarg.

**Comment by mrocklin** [comment]
Yup, sorted is a promise from you to Dask, not a promise from Dask to you.

Improving the docstring would be welcome.

**Comment by TomAugspurger** [comment]
If your question is "why does `df.get_partition(1)` have the index [1, 2]?", that's more likely because there are duplicate 1s in the index, which span the partition boundary.

**Comment by bchu** [comment]
Would there be any value if I added an error check in `dask.dataframe.shuffle.compute_divisions` (e.g. if the mins/maxes of adjacent partitions overlap, raise an error).

Or is this a legitimate usecase (in which case maybe a warning would be appropriate).

**Comment by TomAugspurger** [comment]
I could be wrong, but I believe that we allow multiple divisions having the
same value. I think the only requirement is that
they be weakly increasing (though I haven't looked at this in a while, so I
may be wrong).

**Comment by mrocklin** [comment]
Divisions are assumed to strictly increase, except for the last two (where
it doesn't matter anyway).  There is now also a
dask.dataframe.utils.valid_divisions which defines things in code, if
helpful.
