### ISSUE TITLE
DataFrame groupby apply returns unexpected duplicated MultiIndex

### ISSUE THREAD

**Issue by bchu** [dask/dask#4592]
```
import pandas as pd
import dask.dataframe as dd
df = pd.DataFrame([[1, 2], [2, 3], [3, 4]], columns=['a', 'b'])
# df = df.astype({'b': 'category'})
df = dd.from_pandas(df, npartitions=1).set_index('a')
df = df.groupby('a').apply(lambda d: d.copy())
df.compute()
```

returns a dataframe with a MultiIndex where both levels are just copies of the original index:

```
     b
a a   
1 1  2
2 2  3
3 3  4
```

Providing the right meta object does not change the result. Interestingly, if I convert column 'b' to 'category' dtype (uncomment the line `# df = df.astype({'b': 'category'})`), I get the right result:

```
   b
a   
1  2
2  3
3  4
```

**Comment by TomAugspurger** [comment]
Pandas has some inconsistencies here when the input  is (maybe) mutate in side an apply.

```python
In [17]: df.groupby('a').apply(lambda d: d)
Out[17]:
   a  b
0  1  2
1  2  3
2  3  4

In [18]: df.groupby('a').apply(lambda d: d.copy())
Out[18]:
     a  b
a
1 0  1  2
2 1  2  3
3 2  3  4
```

I'd recommend searching on the pandas issue tracker to see if this is the expected behavior, and maybe make a PR fixing it if not.

**Comment by bchu** [comment]
Ah okay. It appears to be expected behavior in Pandas, a result of Pandas `.groupby(group_keys=True)` being the default. If `group_keys=False` the result is what we would want:

```
>>> df.groupby('a', group_keys=False).apply(lambda d: d.copy())
   a  b
0  1  2
1  2  3
2  3  4
```

So the fix here would be to expose `group_keys` in dask.

**Comment by TomAugspurger** [comment]
It's not clear to me that the difference between the two pandas outputs
(mutate vs. not) is intentional.

**Comment by bchu** [comment]
It does appear to be a pandas bug (https://github.com/pandas-dev/pandas/issues/22546). But the "correct" Pandas behavior is the behavior exhibited by `df.groupby('a').apply(lambda d: d.copy())` (the grouping index gets added).

So I suppose this is more of a feature request for supporting `.groupby(group_keys)`

**Comment by mrocklin** [comment]
It looks like it might not be terribly difficult to add support for the `group_keys=` keyword.  I *think* that this needs to be passed in here:

https://github.com/dask/dask/blob/d8a4f3be9a6ec685261ed043a45ecc019055ec0d/dask/dataframe/groupby.py#L144-L150

You would have to follow how the keyword arguments get passed into that function, which might go back a few levels.  But I suspect that there is a 50+% chance of that working.  

I know it's been a little while @bchu, but do you have any interest in trying this out?

**Comment by bchu** [comment]
Yep, I'll take a look.
