### ISSUE TITLE
dask.dataframe.drop doesn't accept inplace argument

### ISSUE THREAD

**Issue by danodonovan** [dask/dask#4595]
The [documentation](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.drop) suggests that `dask.dataframe.drop` accepts the `inplace` argument - but it's missing from the dask function [signature](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2869).

I'll happily submit a PR to update the docs, but first - should `dask.dataframe.drop` accept `inplace`? The implementation of the desired behaviour doesn't appear trivial to me (at first glance). 

Example failing code
```
    df = pd.DataFrame({'x': [1, 2, 3, 4],
                       'y': [5, 6, 7, 8],
                       'z': [9, 10, 11, 12]})
    ddf = dd.from_pandas(df, npartitions=2)

    ddf.drop('y', axis=1, inplace=True)
    df.drop('y', axis=1, inplace=True)

    assert_eq(ddf, df)
```

**Comment by TomAugspurger** [comment]
The notes section indicate that `inplace` is not supported.

Your example raises for me on master. What version of dask do you haev?

**Comment by danodonovan** [comment]
Yes - my mistake, I'd not read that far. Apolgoies for the noise
