### ISSUE TITLE
yaml.load() deprecation warning after updating to pyyaml v5.1 (released 13/03/19)

### ISSUE THREAD

**Issue by kindjacket** [dask/dask#4597]
Very small issue. Wanted to flag early. Just updated to the lastest version of pyyaml (a dependency of dask) v5.1. After updating I get the following deprecation warning. 

```
/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
```

**Comment by TomAugspurger** [comment]
Yep, there's a distributed issue as well. A PR updating to the safe method
loader would be welcome.

**Comment by jakirkham** [comment]
For context, this changed in PR ( https://github.com/yaml/pyyaml/pull/257 ).

Note: While that PR appears closed, it was merged into specific commits noted at the bottom of the PR.
