### ISSUE TITLE
read_csv: EOF inside string @ head = reader(BytesIO(b_sample), **kwargs)

### ISSUE THREAD

**Issue by verasativa** [dask/dask#4598]
I was having this "EOF inside string" error when trying to load some csv containing line breaks inside string (go dask for nlp!), and noticed:

Even when I passed dtypes to ```dask.dataframe.read_csv``` it still take a sample at [dataframe/io/csv.py:377](https://github.com/dask/dask/blob/87f3a482918076f885fe419329dfb5552d24cbaa/dask/dataframe/io/csv.py#L377), and in my case (chance) it was cutting inside a text, then crashing with a "EOF inside string" error.
I'm not familiar enough to implement a good solution and do PR, but I'm asking to provide a way of avoiding that sample, to make dask more text friendly.

ps: my current solution is to set ```sample``` size a number way bigger than csv files, but it's not optimal as the csv are been loaded twice, one as "sample" and on "for real".

**Comment by TomAugspurger** [comment]
Do you have a small example of the text that caused the issue? I assume it's only a problem with Dask, and not pandas, if it's specific to Dask's sampling.

Alternatively, do you know the dtypes of your file ahead of time? If so, you could try passing those as the `dtype` parameter. We would need to make sure you can turn of `sample` entirely though... Not sure if that's possible right now.

**Comment by verasativa** [comment]
I could build you a small sample file, but in order to work I'll have to set sample size to less than file size. And yes, is specific issue to dask (works on pandas).

I do have the dtypes, and I do pass those, but it's not possible to turn off ```sample``` entirely (that it's issue I'm reporting). I'll try to make the file/code sample on the weekend.

**Comment by jcrist** [comment]
@verasativa any update here? Without a reproducible example we'll have a difficult time debugging this. See also https://blog.dask.org/2018/02/28/minimal-bug-reports.

**Comment by martindurant** [comment]
Since https://github.com/dask/dask/pull/4634 , it is now possible to do without the sample.

**Comment by verasativa** [comment]
Ok, sorry for the delay, hope my test code its clear:
```python
import dask.dataframe as dd
import pandas as pd

# Create fail csv and add headers
file = open("fail.csv","w+")
file.write('"id","text"\n')

# Set a string lenght targer over the default (256000) "sample" parameter of dd.read_csv
# https://docs.dask.org/en/latest/dataframe-api.html#storage-and-conversion explains 
target = 256000 + 1


# Build a long string
#
# Please note:
# if you remove the \n dask will not fail
long_string = 'This a long string\n'
while len(long_string) <  target:
    long_string = long_string + long_string

# use long string in 5 rows (just for more realism), and save the file
for line in range(5):
    file.write('{},"{}"\n'.format(line, long_string))
file.close()

# set dtypes (to make case stronger)
types = {
    'id': int,
    'text': str,
}


# pandas will not fail
pdf = pd.read_csv('fail.csv', dtype=types)
# then dask will fail
ddf = dd.read_csv('fail.csv', dtype=types)
```
Perhaps @martindurant can try it on #4634 width ```blocksize=None, sample=False```

**Comment by martindurant** [comment]
Yes, I can confirm that `dd.read_csv('fail.csv', dtype=types, blocksize=None, sample=False)` does work on master. I think this should have been included in v1.2.0.

**Comment by jrbourbeau** [comment]
@verasativa I was able to successfully run you excellent code example when specifying `sample=False` in `dd.read_csv` with the latest release of Dask (release version `1.2.0`). Is it safe to close this issue?

**Comment by verasativa** [comment]
> @verasativa I was able to successfully run you excellent code example when specifying `sample=False` in `dd.read_csv` with the latest release of Dask (release version `1.2.0`). Is it safe to close this issue?

Sure, thanks!

**Comment by jrbourbeau** [comment]
Thank you!
