### ISSUE TITLE
toolz should be a non-optional requirement?

### ISSUE THREAD

**Issue by QuLogic** [dask/dask#4601]
Currently, `toolz` is listed in all extras except `distributed`. However, `toolz` is imported by `dask.base`:
https://github.com/dask/dask/blob/87f3a482918076f885fe419329dfb5552d24cbaa/dask/base.py#L13-L14

So should it not be a hard requirement (in `install_requires`)?

**Comment by mrocklin** [comment]
There are parts of dask, notably dask.core and dask.local which are useful
in their own right and don't require toolz.

I'm not sure how many people use these in isolation today, or how many
people want to avoid toolz, but that was the original reasoning at least.

Is the lack of toolz in the hard requirements causing an issue for you?

**Comment by QuLogic** [comment]
No, actually, it turns out that while xarray imports `dask.base`, it actually requires `dask[array]` and `dask[dataframe]` (which I had missed initially), so it gets `toolz` anyway.
