### ISSUE TITLE
Add configuration for temporary directory

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4609]
There are a few places where we want to write scratch data to local disk.  This includes both the `partd` solution for out-of-core shuffling, as well as dask.distributed's local directory for excess data and user-uploaded files.

Dask-jobqueue currently has a config entry for this, (this is often an issue on HPC systems with NFS systems) but nothing else does.

We should consider adding a top-level entry for temporary root directory that people might set to something like `/tmp` or `/scratch` and that would probably default to `.`.

**Comment by jcrist** [comment]
Agree that making this configurable would be good. I'm not sure if the default should be `.` or [`tempfile.gettempdir()`](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) (which also is configurable using different mechanisms).

**Comment by mrocklin** [comment]
I'll try to take care of this later this afternoon

**Comment by jcrist** [comment]
I just stumbled upon this:

https://github.com/dask/dask/blob/c6aa46e076e611b6e5522ddea2e070eb5239995b/dask/bag/core.py#L2106

**Comment by jcrist** [comment]
Fixed by #4774
