### ISSUE TITLE
Cannot connect to ipykernel with tornado > 6

### ISSUE THREAD

**Issue by jmcarpenter2** [dask/dask#4612]
Hello,

Dask is amazing - I use it in projects consistently and it is highly effective.

It appears that the most recent versions of dask[complete] introduced a dependency on tornado>=6.0.0, which currently is unfortunately incompatible with ipykernel and therefore the use of jupyter notebooks. See [here](https://github.com/jupyter/notebook/issues/4439) for further discussion of the issue. As of today, most solutions involve downgrading to an earlier version of tornado i.e. < 6.

Here is an error that I got while attempting to connect to an ipykernel using jupyter notebook (`tornado 6.0.1`, auto-installed as dependency by `dask[complete] 1.1.4`)

`[W 21:59:05.903 NotebookApp](B Replacing stale connection: 68d5651d-4737-429f-8065-3bb7115c6e6b:5760f9cb8eaa43099cf0588d0b72f2b6`

Instead of connecting and being able to run cells in the jupyter notebook, my kernel simply hangs and I am unable to run anything. 

I realize that the underlying library, `tornado` is the root issue here, but I would advise temporarily downgrading dask's dependent version of tornado to < 6, unless >= 6 is critical to dask's latest releases.

Thank you for all your hard work,
Jason

**Comment by mrocklin** [comment]
Dask.distributed depends on torando >=5 not >6.  You should be ok if you
specify tornado==5

**Comment by jmcarpenter2** [comment]
Hi @mrocklin ,

Thanks so much for your immediate response! I completely agree that I can manually install tornado==5 (which is what I did), but by default when I run `pip install -U dask[complete]`, it will install the latest version of tornado, which is 6.0.1. Please see the attached screenshot, where it automatically uninstalled tornado 5.1.1 and installed v6.0.1 even though the dask[complete] tornado>=5 dependency was satisfied.
![Screen Shot 2019-03-18 at 3 52 56 PM](https://user-images.githubusercontent.com/29585347/54568831-f8860c00-4995-11e9-8b1d-fb3d456738c0.png)

I think it might be wise to avoid user issues by specifying dask's dependency on tornado to tornado<6 in the distribution of the package, at least until tornado resolves this issue.

**Comment by mrocklin** [comment]
If there is a conflict is between ipykernel and tornado then the version
constraint should probably be there, not in Dask.  You might consider
raising there?

There is also a flag in pip to only upgrade those dependencies that need to
be upgraded.

**Comment by jmcarpenter2** [comment]
Fair enough - it's not Dask's fault that the issue is occurring, and this is likely to be a temporary issue. 

Thank you for your timely responses to this issue, I will close it now.
