### ISSUE TITLE
Multiple merge steps results in incorrect result

### ISSUE THREAD

**Issue by bluecoconut** [dask/dask#4617]
This seems to be related to a closed issue: https://github.com/dask/dask/issues/3911

I'm getting different result from pandas and dask on the same merge pipeline. Set up a small example:

```
import dask.dataframe as dd
import pandas as pd

def do_merge_work(base, mapto):
    mapto_series = mapto.set_index('i')['a']
    base_ind_by_a = base.set_index("a")
    base_b = base_ind_by_a['b']
    base_c = base_ind_by_a['c']
    mapped_b = mapto_series.to_frame().merge(base_b.to_frame(), left_on='a', right_index=True, how='left')['b']
    mapped_c = mapto_series.to_frame().merge(base_c.to_frame(), left_on='a', right_index=True, how='left')['c']
    final_output = mapped_b.to_frame().merge(mapped_c.to_frame(), left_index=True, right_index=True, how='outer')
    return final_output
```

```
base = pd.DataFrame({'a': [1,2,3], 'b': ['a','b','c'], 'c': [123,44,12]})
mapto = pd.DataFrame({'i': range(10), 'a': [0,1,2,1,2,0,1,2,3,4]})
print("Pandas result: ")
print(do_merge_work(base, mapto))
print()

base = dd.from_pandas(base, npartitions=1)
mapto = dd.from_pandas(mapto, npartitions=1)

output = do_merge_work(base, mapto)
print("Dask result: ")
print(output.compute())
```

Output: 
```
Pandas result: 
     b      c
i            
0  NaN    NaN
1    a  123.0
2    b   44.0
3    a  123.0
4    b   44.0
5  NaN    NaN
6    a  123.0
7    b   44.0
8    c   12.0
9  NaN    NaN

Dask result: 
   b      c
i          
1  a  123.0
2  b   44.0
3  a  123.0
```

I would have expected the two results to be the same. 

By changing to `npartitions=2` the join works correctly (though comes out unsorted?)
```
Dask result: 
     b      c
i            
0  NaN    NaN
2    b   44.0
3    a  123.0
4    b   44.0
5  NaN    NaN
6    a  123.0
7    b   44.0
8    c   12.0
1    a  123.0
9  NaN    NaN
```

**Comment by bluecoconut** [comment]
Small update in looking at this deeper. 

I realized that in the example i wasn't explicit about the `on` parameter, which highlights another difference/potential bug between pandas and dask, but is unrelated to the main problem.

Eg.
```
def merge_on(base, mapto):
    mapto_series = mapto.set_index('i')['a']
    base_ind_by_a = base.set_index("a")
    base_b = base_ind_by_a['b']
    mapped_b = mapto_series.to_frame().merge(base_b.to_frame(), on='a', right_index=True, how='left')['b']
    return mapped_b
base = pd.DataFrame({'a': [1,2,3,5], 'b': ['a','b','c', 'a'], 'c': [123,44,12,17]})
mapto = pd.DataFrame({'i': range(10), 'a': [0,1,2,1,2,0,1,2,3,4]})
print(merge_on(base, mapto))
print(merge_on(dd.from_pandas(base, npartitions=1), dd.from_pandas(mapto, npartitions=1)).compute())
```

### Updated code for bug:

```

import dask.dataframe as dd
import pandas as pd

def do_merge_work(base, mapto):
    mapto_series = mapto.set_index('i')['a']
    base_ind_by_a = base.set_index("a")
    base_b = base_ind_by_a['b']
    base_c = base_ind_by_a['c']
    mapped_b = mapto_series.to_frame().merge(base_b.to_frame(), left_on='a', right_index=True, how='left')['b']
    mapped_c = mapto_series.to_frame().merge(base_c.to_frame(), left_on='a', right_index=True, how='left')['c']
    b_frame = mapped_b.to_frame()
    c_frame = mapped_c.to_frame()
    final_output = b_frame.merge(c_frame, left_index=True, right_index=True, how='outer')
    return final_output, b_frame, c_frame
```
```
base = pd.DataFrame({'a': [1,2,3], 'b': ['a','b','c'], 'c': [123,44,12]})
mapto = pd.DataFrame({'i': range(10), 'a': [0,1,2,1,2,0,1,2,3,4]})
print("Pandas result: ")
pandas_out, pandas_b, pandas_c = do_merge_work(base, mapto)
print(pandas_out)
print()

base = dd.from_pandas(base, npartitions=1)
mapto = dd.from_pandas(mapto, npartitions=1)

output, b_frame, c_frame = do_merge_work(base, mapto)
print("Dask result: ")
print(output.compute())
```
The result is now:
```
Pandas result: 
     b      c
i            
0  NaN    NaN
1    a  123.0
2    b   44.0
3    a  123.0
4    b   44.0
5  NaN    NaN
6    a  123.0
7    b   44.0
8    c   12.0
9  NaN    NaN

Dask result: 
   b      c
i          
1  a  123.0
2  b   44.0
3  a  123.0
```

Still highlighting the difference/problem.

**Comment by bluecoconut** [comment]
Digging deeper into tests now (how this is happening, that divisions and index get out of sync):

In `dask/dataframe/tests/test_multi.py::test_merge` I see a bunch of `list_eq` rather than `assert_eq` (not sure the purpose of `list_eq` vs. the more common `assert_eq` throughout the tests).

Changing these to `assert_eq` raises errors based on the index being incorrect, which seems to be a sign of this problem (?). 

I also tried updating `list_eq` to check indices, and came across many errors:
```
    if isinstance(aa, dd.DataFrame):
        a = aa.compute(scheduler='sync')
        a_index = aa.index.compute(scheduler='sync')
    else:
        a = aa
        a_index = aa.index

    if isinstance(bb, dd.DataFrame):
        b = bb.compute(scheduler='sync')
        b_index = bb.index.compute(scheduler='sync')
    else:
        b = bb
        b_index = bb.index

    tm.assert_numpy_array_equal(a_index.values, b_index.values)
```

I'd also like to do something to validate that the `divisions` are correct, but I'm not sure the best way to do this. I tried checking that `dask_frame.divisions[0] == pandas_frame.index.min()` and `dask_frame.divisions[-1] == pandas_frame.index.max()`, but found that there were `None` involved with `divisions` that I don't quite understand.


@mrocklin the last changes in these tests were from you 3 years ago, so I'm a bit worried I'm heading down the wrong path and misunderstanding indices / divisions in dask. 

Any suggestion about where to focus to fix this bug?

**Comment by mrocklin** [comment]
@jcrist do you have a moment to check this out?

**Comment by bluecoconut** [comment]
I think I was able to chase down this bug (was reproducible as a test, and then fixable) see: https://github.com/dask/dask/pull/4636

A semi-separate (but clarification question about intention in dask that came up in chasing this):
Is it the case that the result of merge of dataframes that are _not_ indexed do not guarantee any indexing uniqueness?

Eg. 
```
df1 = pd.DataFrame({'x': [1,2,3,4], 'z': list("qcce")})
df2 = pd.DataFrame({'x': [3,4,5,6], 'y': list("haaa")})
df1_dd = dd.from_pandas(df1, npartitions=2)
df2_dd = dd.from_pandas(df2, npartitions=3)
print(df1_dd.merge(df2_dd, left_on='x', right_on='x', how='outer').compute())
print(df1.merge(df2, left_on='x', right_on='x', how='outer'))
```

Here, pandas re-indexes the resulting frame to have 1->6, while dask has an index in the resulting table `0,0,1,2,3,4`. 

Or is this another bug / something to be considered? This does not affect my use-case, so I am less concerned, but wanted to ask to be thorough while looking at this part of the code.

**Comment by mrocklin** [comment]
In general any time a range index would be applied to a Pandas dataframe Dask dataframe won't be able to follow.  We don't know how many elements are in each partition up front, so it's hard/expensive to coordinate index values across partitions.

**Comment by mrocklin** [comment]
(hopefully that answered your question, I have to admit I'm rushing through things a bit at the moment)

**Comment by bluecoconut** [comment]
I guess I understand that it can't keep up in the interim (would be expensive), but what surprises me is that after a `.compute()` and gather to a local in memory pandas frame, there are 2 differences from the pandas result: 

1) Index isn't necessarily sorted (even for indexed inputs), and 
2) Index isn't necessarily unique (for non-indexed input dfs)

I think for (1) it's a non issue, since any operation that will happen later has the index values to rely on still, it's more for presentation, and it's always an option to call `sort_index()` if that is result is required. and (2) is just a bit surprising, but ultimately a non issue, if not explicitly using indexed frames, maybe it's not so bad that the resulting index isn't unique, and can always call `reindex`. I think I just have a mental "requirement" that indexes (even auto-generated ones) are always unique. 

Ultimately, both of these are nearly cosmetic and unrelated to the issue here / PR. Just wanted to validate understanding~ Thanks for your help!

**Comment by mrocklin** [comment]
Thanks for finding, diagnosing, and fixing this issue @bluecoconut !
