### ISSUE TITLE
Any reason for an experienced Dask user on a single machine _not to_ use Dask Distibuted?

### ISSUE THREAD

**Issue by JamesCropcho** [dask/dask#4618]
Hello! I have a question.

Is there any reason for an experienced Dask user on a single machine _not to_ use Dask Distributed?

The documentation is rather clear that single-machine Dask Distributed outperforms the `dask.multiproccessing` scheduler (https://docs.dask.org/en/latest/scheduling.html#local-processes).

But what about compared to the threaded scheduler? It seems that the Dask Distributed analog is to instantiate like `Client(processes=False)`. Is this too considered nearly always superior to the default local threaded scheduler?

And finally to zoom out maximally and bring us back to the top: you're clear on the `dask.multiprocessing` scheduler, but should an experienced Dasker _ever_ use the default threaded scheduler?

With Gratitude for Dask,
James

**Comment by martindurant** [comment]
The per-task overhead of the old, simple threaded scheduler is still much smaller than the distributed one, even when running threads in-process; also it has a smaller CPU and memory footprint by itself, as well as fewer package dependencies. Also, there are more decisions to make with the distributed scheduler, which is good added flexibility, but requires more knowledge and thought.
None of that may not be important for your workload, and there are some clear benefits of the distributed one (some better logic around graph optimisation, additional features like futures, and of course diagnostics).

Probably it's the old multiprocessing scheduler that loses out the most to distributed. If you have a lot of GIL-holding computations, I don't think that it should be recommended any more.

**Comment by jcrist** [comment]
Closing, as the question was answered.
