### ISSUE TITLE
How to run the development version (local version)

### ISSUE THREAD

**Issue by Shekharrajak** [dask/dask#4620]
I have forked the repository and have changed the code as per my requirement. I was looking for a development workflow wiki page/article to understand how new contributor will setup and can debug the changes, but I didn't find it.

Please let me know how can I run my changes in python shell without installing my local version of dask repository.

**Comment by mrocklin** [comment]
http://docs.dask.org/en/latest/develop.html
http://docs.dask.org/en/latest/install.html#install-from-source

**Comment by Shekharrajak** [comment]
Thanks @mrocklin , Yes I went through the link and I understood that if I want to test it I need to write testcase and run the test command and check the expected output. Is there any way to directly check in python-shell ?

**Comment by jrbourbeau** [comment]
> Please let me know how can I run my changes in python shell without installing my local version of dask repository.

@Shekharrajak I'm not sure what you mean by this. If you want to use a local version of Dask that has changes you've made, then you'll need to [install your local version of Dask](http://docs.dask.org/en/latest/install.html#install-from-source). Feel free to elaborate a little more, I could be misunderstanding your particular use case.

**Comment by Shekharrajak** [comment]
Thanks! Now I am able to run python code inside the cloned repo. Previously it was not using my changes when I run it inside the folder.
