### ISSUE TITLE
Bug in auto_chunks

### ISSUE THREAD

**Issue by abergou** [dask/dask#4627]
I believe that there is a bug in `auto_chunks`. On line [1980](https://github.com/dask/dask/blob/eef368ffe40026f49930b061a1fe6fc59a9ee575/dask/array/core.py#L1980) limit is redefined from byte units to num-items units:
```python
limit = max(1, limit // dtype.itemsize)
```

However, later on in the file on line [2032](https://github.com/dask/dask/blob/eef368ffe40026f49930b061a1fe6fc59a9ee575/dask/array/core.py#L2032) auto_chunks is called recursively passing the redefined limit in:
```python
return auto_chunks(chunks, shape, limit, dtype)
```

I think that either limit shouldn't be redefined in-place  or this line should read something like:
```python
return auto_chunks(chunks, shape, limit * dtype.itemsize, dtype)
```
Thanks!

**Comment by abergou** [comment]
Adding a bit more detail. The issue comes up when the array has a highly non-uniform chunksize. That is the following condition is triggered:
```python
        size = (limit / largest_block) ** (1 / len(autos))
        small = [i for i in autos if shape[i] < size]
        if small:
            for i in small:
                chunks[i] = (shape[i],)
            return auto_chunks(chunks, shape, limit, dtype)
```

Consider first, a case where auto-chunking works as desired:
```python
In [1]: limit = 2. ** 20

In [2]: auto_chunks(('auto', 'auto', 'auto'), (1000, 1000, 1000), limit, numpy.dtype('f8'))
Out[2]: (50, 50, 50)

In [3]: 50 ** 3 * numpy.dtype('f8').itemsize / limit
Out[3]: 0.95367431640625
```
Now one where it doesn't:
```python
In [1]: limit = 2. ** 20

In [2]: auto_chunks(('auto', 'auto', 'auto'), (50, 20000, 1000), limit, numpy.dtype('f8'))
Out[3]: ((50,), 16, 10)

In [3]: 50 * 16 * 10 * numpy.dtype('f8').itemsize / limit
Out[3]: 0.06103515625
```
The array is chunked too finely along axes 1 and 2.  Interestingly enough (and consistent with the bug) when the "limit" is reduced the chunk size increases:
```python
In [4]: dask.array.core.auto_chunks(('auto', 'auto', 'auto'), (50, 20000, 1000), 0.95 * 2 ** 20., numpy.dtype('f8'))
Out[116]: (25, 40, 40)
```

**Comment by mrocklin** [comment]
@jakirkham if you have a moment can I ask you to take a quick look at this?

**Comment by mrocklin** [comment]
Thanks for the excellent issue @abergou .  I have a proposed fix in https://github.com/dask/dask/pull/4645

Can you suggest a simple test that would use user-facing API, perhaps slightly higher level than the auto_chunks function, maybe something with `da.ones(..., chunks=(...))`?

**Comment by abergou** [comment]
Unfortunately, when auto_chunks is called through normalize_chunks then it is only triggered if `previous_chunks` is `None` (auto_chunks is only recursively called in this case). At the moment this is only exposed when `auto_chunks` or `normalize_chunks` is directly called (I was doing the latter). Thus, the lowest level test I can propose is:

```python
In [1]: import numpy; from dask.array.core import normalize_chunks
In [2]: shape = (50, 20000, 1000)
    ...: chunks0=da.core.normalize_chunks(('auto', 'auto', 'auto'), (50, 20000, 1000), dtype='f8', limit=2 ** 20)
    ...: chunks1=da.core.normalize_chunks(('auto', 'auto', 'auto'), (50, 20000, 1000), dtype='f8', limit=0.95 * 2 ** 20)
    ...: size0 = numpy.prod([max(c) for c in chunks0])
    ...: size1 = numpy.prod([max(c) for c in chunks1])
    ...: size0 >= size1
    ...:
Out[2]: False
```

I believe we would expect `Out[2]: True`

**Comment by mrocklin** [comment]
Hrm, without thinking hard, it's not immediately clear to me why that would be

**Comment by mrocklin** [comment]
To be clear, I don't understand the intent of the test.

**Comment by abergou** [comment]
Thanks Matt!
Indeed I wasn't very clear about what the test does - sorry about that. The test calls normalize chunks twice changing only the limit parameter. It then computes the maximum chunk-size (in items) generated by the two calls and shows that in the buggy version of auto-chunks decreasing the limit-size actually increases the chunk size.

This is good to close though since your change fixes the issue. Thanks!
