### ISSUE TITLE
Try __array_interface__["typestr"] when calling np.dtype(obj).

### ISSUE THREAD

**Issue by skrah** [dask/dask#4632]
Would it be possible to try `x.__array_interface__["typestr"]` in situations like the following?

I would prefer `xnd.array.dtype` to return `ndt()`, so it needs to be translated for NumPy:

```
>>> from xnd import array
>>> import dask.array as da
>>> 
>>> x = array([1,2,3])
>>> x.dtype
ndt("int64")
>>> x.__array_interface__["typestr"]
'=q'
>>> 
>>> d = da.from_array(x, chunks=(5,), asarray=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/dbg/lib/python3.8/site-packages/dask/array/core.py", line 2096, in from_array
    chunks = normalize_chunks(chunks, x.shape, dtype=x.dtype)
  File "/home/stefan/dbg/lib/python3.8/site-packages/dask/array/core.py", line 1846, in normalize_chunks
    dtype = np.dtype(dtype)
TypeError: data type not understood
```

**Comment by mrocklin** [comment]
Interesting.  I guess we would to ask a few questions:

-  Do all Numpy-like array objects support `__arrray_interface__`?  (cupy, sparse, ...)
-  Is there some way to make `np.dtype` support non-numpy types?  We (and I think other projects) use `np.dtype` as a general normalization function for dtypes.  I wonder if we might be able to move this conversation there.

**Comment by skrah** [comment]
Unfortunately support does not look that good: For some reason `cupy` only has `__cuda_array_interface__["typestr"] `, and I could not find it in `sparse`.

Making another protocol for `np.dtype` (`__numpy_dtype__`,  `__pep3118_format__`?) would perhaps work. But that is yet another protocol. :)

What would also work of course is `np.dtype(memoryview(array).format)`.

I'm not sure how well that would integrate in `dask`'s codebase, the object would need to be available any time `np.dtype` is called.

Also possible would be to have `np.dtype` accept objects directly that support buffer exports, but that would just be a slightly more convenient form of `np.dtype(memoryview(array).format)`.

I guess if the `memoryview` hack isn't suitable for `dask`, we can try moving this to `numpy`.

**Comment by mrocklin** [comment]
I suspect that calling `memoryview` on a cupy or sparse array might have negative effects.

> I guess if the memoryview hack isn't suitable for dask, we can try moving this to numpy.

Yes, given how common using `np.dtype` is to normalize dtypes, it seems like a useful conversation to have anyway.

**Comment by mrocklin** [comment]
It's worth noting that the NumPy community is actively thinking about how to engage with user defined types, so this is a relevant topic for them to consider today.

**Comment by mrocklin** [comment]
@skrah ok to close?

**Comment by skrah** [comment]
Yes, sure, let's move it to numpy!
