### ISSUE TITLE
SciPy 2019 Sprint

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#4639]
From discussion during previous monthly developer meetings, it sounds like there are several Dask developers who will be attending SciPy this year. I'd like to organize a Dask sprint at the conference https://www.scipy2019.scipy.org/sprints

Some related tasks:

- [x] Officially register as a sprint
- [ ] Do prep work so that sprinters have activities when they arrive, including people with a range of skill levels
- [ ] Tweet about the sprint and mention it in the gitter chat

I'm opening up this issue to track related discussion

**Comment by mrocklin** [comment]
Thanks for starting this issue @jrbourbeau !

**Comment by jrbourbeau** [comment]
I've added a [sprint discussion item](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit) to the next monthly developers meeting agenda. 

At this point, has anyone already officially registered us? If not, I'm happy to do so.

**Comment by jrbourbeau** [comment]
We're registered!

**Comment by mrocklin** [comment]
Thanks James!

**Comment by jrbourbeau** [comment]
A list of sprint issues can be found at 

https://docs.google.com/document/d/14FnBWFhQC2vxrEo98QHlKiFpwFneyKknJdEQUNqdCms/edit?usp=sharing

**Comment by jcrist** [comment]
For new contributors, here's a link to our development guidelines: https://docs.dask.org/en/latest/develop.html

**Comment by jcrist** [comment]
Closing, as SciPy (unfortunately) is over.
