### ISSUE TITLE
read_parquet does not handle timezones

### ISSUE THREAD

**Issue by bchu** [dask/dask#4640]
Dask DataFrame method `read_parquet` does not read parquet timezone metadata (despite fastparquet handling this metadata), except if the file was written with fastparquet _and_ is being read with pyarrow.

This works:
```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame([[0]], columns=['a'], dtype='datetime64[ns, UTC]')
df.to_parquet('tmp1.parquet', engine='fastparquet')
df = dd.read_parquet('tmp1.parquet', engine='pyarrow')
df.dtypes
# a    datetime64[ns, UTC]
# dtype: object

# But any other permutation of engines results in:
# a    datetime64[ns]
# dtype: object
```

`to_parquet` does correctly write timezones, for any permutation of read/write engines:
```
df.astype('datetime64[ns, UTC]').to_parquet('tmp2.parquet', engine='fastparquet')
pd.read_parquet('tmp2.parquet/part.0.parquet', engine='fastparquet').dtypes
# a    datetime64[ns, UTC]
# dtype: object
```

**Comment by mrocklin** [comment]
@martindurant any thoughts here?

@bchu does this also happen when using `engine='pyarrow'`?

**Comment by bchu** [comment]
I've updated the comment. `dd.to_parquet` actually does work. `dd.read_parquet` only works with pyarrow, and only when the original Pandas dataframe is written with fastparquet.

**Comment by martindurant** [comment]
Hah, that is a surprise! Metadata handling for parquet is something we've been talking about elsewhere also and could probably do with an overhaul. In the meantime, could you please check that the timezone information does roundtrip successfully when using fastparquet directly? I seem to think there is such a test.

**Comment by bchu** [comment]
Do you mean without using Dask? Using fastparquet directly does correctly roundtrip (both as an engine in pandas, and if I do `fastparquet.write` / `fastparquet.ParquetFile().to_pandas()`.

**Comment by martindurant** [comment]
OK, thanks for testing that - then the bug is in Dask alone. I'll try to look into it.

**Comment by martindurant** [comment]
For the fastparquet arm, I can fix this in fastparquet alone. That PR: https://github.com/dask/fastparquet/pull/411
(and fastparquet is due for a release anyway)
