### ISSUE TITLE
Monthly Meeting: April 4th at 16:00 UTC

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#4658]
As a reminder, the monthly meeting is this Thursday (April 4th) at 16:00 UTC.

- Minutes: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit
- Video: https://appear.in/dask-dev
- Calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=MXRmc2sxNDVocm1ycTI5YjEyazFhN2Vsa2FfMjAxOTAyMDdUMTYwMDAwWiA0bDB2dHMwYzFjZ2RicTVqaGNvZ2o1NXNmc0Bn&tmsrc=4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com&scp=ALL

I encourage people to think about issues that may need discussion and add them to the agenda (first link)

**Comment by martindurant** [comment]
Note: some of us will be at AnacondaCon, may be tricky to attend.

**Comment by jrbourbeau** [comment]
Good to know, thanks for the info @martindurant. I saw a post from the RAPIDS twitter account about @mrocklin being at AnacondaCon too. Perhaps it makes sense to reschedule the meeting. Does pushing back a week work for others? Same time on April 11?

**Comment by mrocklin** [comment]
Alternatively, having many of us in the same place for AnacondaCon may be
beneficial

**Comment by jrbourbeau** [comment]
Also a fair point. That seemed to work well a couple of meetings ago when there was a large contingent in Austin.

**Comment by pentschev** [comment]
@jrbourbeau can you confirm the calendar invite is correct? For some reason it says Jan 3rd, 2019, for me.

**Comment by jrbourbeau** [comment]
I think that's an artifact of when the invite was created. It should add an event to your calendar for every first Thursday of the month.

**Comment by pentschev** [comment]
Ah yes, you're right, thanks for clarifying. I'm not very used to Google Calendar.

**Comment by jrbourbeau** [comment]
To follow up, will those (or some) attending AnacondaCon be able to join the call on Thursday?

**Comment by mrocklin** [comment]
I will be there

**Comment by jrbourbeau** [comment]
Great 👍 Then to clarify, we will have the meeting this Thursday. Also, note that daylight savings has happened since the last meeting

**Comment by stsievert** [comment]
> note that daylight savings has happened since the last meeting

i.e., the Dask meeting has moved an hour later for all time zones that observe daylight savings time.

**Comment by mrocklin** [comment]
For folks at AnacondaCon lets meet at 10:50am at the NumFOCUS booth and then walk up from there to the seventh floor at 10:55am, which has some relatively quiet space.

**Comment by mrocklin** [comment]
cc @jcrist @martindurant @jakirkham @quasiben @pzwang
