### ISSUE TITLE
Document special handling of dataframe positional arguments to map_partitions.

### ISSUE THREAD

**Issue by jimfulton** [dask/dask#4661]
See #3637.

map_partitions treats dataframes specially when passed as positional arguments.  As far as I can tell, this isn't mentioned in the map_partitions documentation.  I think it should be.

**Comment by jcrist** [comment]
Right, dataframes passed as args first have their partitions aligned, then the function is mapped across all partitions. Agree this would be good to document, can I interest you in submitting a PR?

**Comment by jcrist** [comment]
Fixed by #4757.
