### ISSUE TITLE
da.sum() not working for sparse csr_matrix  

### ISSUE THREAD

**Issue by iambatman07** [dask/dask#4664]
da.sum()  throws a 
`TypeError: sum() got an unexpected keyword argument 'keepdims'` , 
when trying to add a sparse csr_matrix along one axis . 

Here is the code 
`adj_matrix_dask.compute()`
<79x79 sparse matrix of type '<type 'numpy.float64'>'
	with 812 stored elements in Compressed Sparse Row format>
`da.sum(adj_matrix_dask, axis = 1).compute()`.

If you want I can add the full stacktrace.

@mrocklin

**Comment by mrocklin** [comment]
Right, scipy.sparse matrices don't implement the numpy.ndarray interface, so they don't work with all (or even most) dask array operations.  You might want to consider looking at the pydata/sparse project instead, which does support the numpy.ndarray interface.   

See https://docs.dask.org/en/latest/array-sparse.html
