### ISSUE TITLE
Parquet tests fail in PRs

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4666]
For a couple of days, parquet tests have been failing in PRs, for Python 3.6 and 3.7 builds only. Some examples are: https://travis-ci.org/dask/dask/builds/514818005?utm_source=github_status&utm_medium=notification (#4663) and https://travis-ci.org/dask/dask/builds/514571777?utm_source=github_status&utm_medium=notification (#4525).

I'm not sure who to tag here that has some knowledge about that specific part of the code. Could you take a look and maybe ask people who could look at this @mrocklin, @jakirkham ?

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
Pyarrow 0.13.0 was released - I had the impression they were maintaining backward compatibility in the metadata, but it seems not. I'll try to look into this, it should be possible to work around fairly easily.

**Comment by martindurant** [comment]
I have an environment up which demonstrates the problem. It is not so straight-forward, because the new metadata not only has a new structure for the index column info (dict), but now allows an index column with name==None, and actually we can infer the divisions from the row counts of the pieces. In fact, the latter is true for the case that there is no index or pandas metadata at all, and should have been done before. I'll investigate how much of a pain it is to make happen.

**Comment by pentschev** [comment]
If this is too time-consuming, can we mark the failing tests to xfail until we have a permanent fix?

**Comment by martindurant** [comment]
That would be OK by me, but getting this parquet thing right might be more pressing than the other PRs that could be waiting for it.

**Comment by martindurant** [comment]
and to be sure, after a little while of trying to tweak some minimal changes, I think it may take a decent amount of work to get right :(

**Comment by pentschev** [comment]
I understand, the best is really to get the tests right, but in these circumstances it may take quite some effort. I don't have a strong opinion on this, the xfail was only a suggestion, if this may need a week or more until somebody can get them fixed, it may be a good idea to have them xfailing, otherwise, there's a risk of people merging bad PRs thinking that possible failures are only coming from the parquet test.

**Comment by pentschev** [comment]
Another (subpar) idea, that probably nobody will like, is to perhaps constrain testing against an older PyArrow version for the time being.

**Comment by martindurant** [comment]
Certainly; I don't feel like this is my decision to make, regarding what happens to non-parquet PRs, since I'm conflicted. If you were to submit a PR with either of those temporary solutions, then it will get discussed there.

**Comment by pentschev** [comment]
I will submit a PR with the xfail idea then, probably more likely to not be completely hated. Would you say the issue is something that may take 1+ week to be fixed? If it only takes you or somebody else a day or two, I think we can survive with that.

**Comment by martindurant** [comment]
In theory it should have been simple, but arrow is doing some magic things I don't understand yet. There is also @mrocklin 's parquet rewrite that may or may not make this simpler, but probably I'm stuck with the somewhat convoluted codebase in the current implementation. I am at conference right now, so it may well take me a week, especially if maintaining compatibility for old pyarrow. If anybody else wanted to have a go, I'd be more than happy to see it!

That reminds me, there are various special cases for pyarrow versions in the code already, I wonder how old they have to be before they can be dropped.

**Comment by pentschev** [comment]
I won't commit to trying to fix this because I'm clueless about the whole parquet/pyarrow integration, it's likely that anything I do will be wrong in one way or another.

> That reminds me, there are various special cases for pyarrow versions in the code already, I wonder how old they have to be before they can be dropped.

This is an interesting question. @mrocklin is this something that we would generally like to discuss, or maybe even better, does this answer maybe already exists?
