### ISSUE TITLE
Set codecov commit status threshold

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#4670]
Codecov is marking the commit status as failed (with a red 'X') for PRs where there is any decrease in coverage (ref #4669). Since we're not currently enforcing any minimum required coverage, it would be nice to avoid the red 'X' on PRs where the coverage slightly decreases. We should be able to configure this using the [`target`](https://docs.codecov.io/docs/commit-status#section-target) and/or [`threshold`](https://docs.codecov.io/docs/commit-status#section-threshold) parameters in `.codecov.yml`.

**Comment by mrocklin** [comment]
cc @pentschev

**Comment by jrbourbeau** [comment]
Open to other options here if others have different thoughts on this topic

**Comment by pentschev** [comment]
Agreed, thanks for the report. I'll send a PR for that.

**Comment by pentschev** [comment]
If #4669 passes after merging latest master, this can probably be closed.

**Comment by jrbourbeau** [comment]
It's passing, thanks for working on this @pentschev!
