### ISSUE TITLE
Inconsistent memory usage results with ResourceProfiler

### ISSUE THREAD

**Issue by mansenfranzen** [dask/dask#4676]
## Motivation
Let's say I'm trying to profile different dask computation graphs which solve the exact same problem and yield identical results. What I'm interested in is their memory consumption. I want to know which computation graph requires less memory during execution.

## Expectation
Using the `ResourceProfiler` I expect multiple profile runs to yield identical results for the same computational graph. However, results differ between runs. It seems as if there is some memory still allocated and not released properly. This might relate to #3247.

## Minimal complete verifiable example

```python
from dask import dataframe as dd
from dask.diagnostics import ResourceProfiler

import numpy as np
import pandas as pd
import gc
import time


df = pd.DataFrame(np.random.rand(3000000, 10))

def compute():
    # Dummy dask computation
    return dd.from_pandas(df, npartitions=10).pow(2).compute()

def min_max(iterable):
    return np.min(iterable), np.max(iterable)

def profile():
    with ResourceProfiler(0.001) as rprof:
        compute()
    return min_max([x.mem for x in rprof.results])

for run in range(5):
    # clean up
    gc.collect()
    time.sleep(1)

    # profile
    mmin, mmax = profile()
    print("Run: {:02d} Min: {:>7.2f} Max: {:>7.2f}".format(run, mmin, mmax))
```
**Output**:

```
Run: 00 Min:  591.49 Max: 1196.48
Run: 01 Min:  842.49 Max: 1327.24
Run: 02 Min: 1043.90 Max: 1428.04
Run: 03 Min: 1043.89 Max: 1425.35
Run: 04 Min: 1044.12 Max: 1425.45
```
After some iterations, the minimal and maximal memory usages start to stabilize. However, the number of iterations required differs with graph complexity and input size (I observed examples in which it took more than 5 runs for the results to stabilize).

I wonder if I can use the `ResourceProfiler` to safely estimate the memory usage. Interestingly, I also get different results when using the `memory_profiler` which usually reports only half of the memory in use. 

Do you have any advice? Thanks in advance.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-47-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8
pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jcrist** [comment]
Dask runs aren't deterministic (as can be expected with most threaded programming), so there is bound to be some variation here. However, fresh runs (e.g. multiple runs of `python yourscript.py`) should go about the same.

The scheduler releases all references to objects upon completion, so this isn't a memory leak on our side - what you're running into is likely a result of memory fragmentation due to poor performance when mixing threads with Python's allocator. See https://github.com/dask/dask/issues/3530 and https://bugs.python.org/issue33444#msg316289 for more information. There are a few environment variables you can set to tune the allocator (you might try `MALLOC_MMAP_THRESHOLD_=16384`), but a long term solution is still undecided.

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if you're still having issues.
