### ISSUE TITLE
Dask array best practices

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4681]
I'd like for us to make a doc page about best practices for Dask Array.  What are some topics?

Starting off..

1.  Chunk sizes
    -  Right size
    -  Right shape
    -  Aligned with storage
2.  Avoid oversubscribing threads with environment variables
3.  Use efficient storage
4.  Consider Xarray
5.   ...

What else?  cc @jakirkham @jhamman @rabernat @shoyer

**Comment by rabernat** [comment]
Excellent timing. A discussion from today (https://github.com/pangeo-data/pangeo-datastore/pull/24#issuecomment-481357649) made me realize how much un-documented best practice knowledge is locked up in our heads. A new dask user commented

> I was just blindly assuming that everything should magically work perfectly

I will be glad to contribute to such a best practices effort.

**Comment by jrbourbeau** [comment]
cc @djhoese who may be interested in this based on https://github.com/dask/dask/issues/4514

**Comment by djhoese** [comment]
Thanks @jrbourbeau. I'm guessing that number 2 above includes `OMP_NUM_THREADS`. Another one I realized after working with a threaded scheduler for a majority of the time: not using nested functions as arguments to map_blocks and the like:

```python
def do_processing(arr):
    def _do_block_stuff(chunk_arr):
        pass
    new_arr = arr.map_blocks(_do_block_stuff, ...)
```

Which will fail to serialize in non-threaded schedulers.

**Comment by mrocklin** [comment]
Starting work here: https://github.com/dask/dask/pull/4705

Direct edits there would be quite welcome.

**Comment by mrocklin** [comment]
Fixes https://github.com/dask/dask/issues/4514

**Comment by mrocklin** [comment]
Closed for now
