### ISSUE TITLE
Dask Dataframe best practices

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4682]
I'd like for us to make a doc page about best practices for Dask DataFrame. What are some topics?

As a reminder, here is the best practices doc for dask delayed: http://docs.dask.org/en/latest/delayed-best-practices.html

Here is a current page that we might update: https://docs.dask.org/en/latest/dataframe-performance.html and bring in line with common styling

What else should we mention that isn't in that page?  cc @jrbourbeau @TomAugspurger @jcrist

**Comment by jcrist** [comment]
There's some content in a few other pages that may full under best practices as well:

- https://docs.dask.org/en/latest/dataframe-design.html (partitions, passing metadata)
- https://docs.dask.org/en/latest/dataframe-categoricals.html (how to use known/unknown categoricals)
- https://docs.dask.org/en/latest/dataframe.html#common-uses-and-anti-uses

**Comment by mrocklin** [comment]
I've started on this in https://github.com/dask/dask/pull/4703 .  Mostly I just moved over the original dataframe-performance file, and added a couple things.

**Comment by mrocklin** [comment]
Help there would be welcome
