### ISSUE TITLE
Bag.compute ignores num_workers

### ISSUE THREAD

**Issue by EdwardJB** [dask/dask#4688]
Hi.

I'm using `dask==1.1.5` and trying to run the following workflow:

```python
...
    @classmethod
    def pipeline(cls):
        bag = db.read_text(PATH_SENTENCES, blocksize=10000)
        bag = bag.map(cls.get_annotations)
        bag = bag.remove(lambda v: v is None)
        bag = bag.map(json.dumps)
        bag = bag.remove(lambda v: not v)
        bag = bag.to_textfiles('*.jsonl')
        with ProgressBar():
            result = bag.compute(scheduler='processes', num_workers=2)
        return result
```

The `num_workers` is getting ignored. It just uses the core count (meaning I can't do any other work as the computer is unresponsive). 

Side note: the `ProgressBar` doesn't display anything either. It used to but after changing some of the pipeline steps (I didn't notice which) it stopped.

**Comment by mrocklin** [comment]
My guess is that you're using the distributed scheduler, which doesn't
respect either of those elements.  I'm not sure though given your code
example.

https://docs.dask.org/en/latest/understanding-performance.html
<http://docs.dask.org/en/latest/understanding-performance.html>

> The single-machine and distributed schedulers
<http://docs.dask.org/en/latest/scheduling.html> come with *different*
diagnostic
tools. These tools are deeply integrated into each scheduler, so a tool
designed for one will not transfer over to the other.


>

**Comment by EdwardJB** [comment]
Thanks for the reply. I've actually fixed both issues now:

```python
    @classmethod
    def build(cls):
        with ProgressBar(), dask.config.set(scheduler='processes', num_workers=2):
            cls.pipeline()

    @classmethod
    def pipeline(cls):
        bag = db.read_text(PATH_SENTENCES, blocksize=1000)
        bag = bag.map(cls.get_annotations)
        bag = bag.remove(lambda v: v is None)
        bag = bag.map(json.dumps)
        bag = bag.remove(lambda v: not v)
        bag = bag.to_textfiles('*.jsonl')
        result = bag.compute()
        return result
```

Looks like it respects the settings if applied to `dask.config`, but not if passed directly to the `compute` method.

**Comment by mrocklin** [comment]
If my previous guess that you had created a Client was correct, then the
difference here is that you're explicitly setting the scheduler='processes'
keyword, which tells Dask that you want to use the local scheduler instead
of the distributed one.

Glad to see that you've resolved your issue.

**Comment by EdwardJB** [comment]
I did make a `Client` _at one point_ but it's no longer in the code. Does it still have an effect?

**Comment by mrocklin** [comment]
If you made a client in that Python process yes.  You can look at
dask.config.get('scheduler')

**Comment by jrbourbeau** [comment]
@EdwardJB any update here? Is it safe to close this issue?

**Comment by jrbourbeau** [comment]
> I've actually fixed both issues now

Closing as the originally posted issue seems to have been resolved. Feel free to re-open if this is not the case
