### ISSUE TITLE
dask.array.ones() and dask.array.zeros() do not accept dask arrays as input

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#4691]
It was unclear to me from [the documentation on dask.array.ones()](http://docs.dask.org/en/latest/array-api.html) whether this was expected or unexpected behaviour. If this is expected behaviour, I'd like to clarify it in the docs.

`dask.array.ones()` and `dask.array.zeros()` do not accept dask arrays as input, but will accept input numpy arrays. 

In contrast, `dask.array.ones_like()` and `dask.array.zeros_like()` will both happily accept input dask arrays.

```python
import dask.array as da
import numpy as np

x = np.array([3, 3])
d = da.from_array(x, chunks=2)

da.ones(x, chunks=2)
# output is as expected
# dask.array<ones, shape=(3, 3), dtype=float64, chunksize=(2, 2)>

da.ones(d, chunks=2)
# an error occurs, even before attempting .compute()
# ValueError: The truth value of a Array is ambiguous
# see full traceback below
```

Traceback:
```python-traceback
ValueError                               Traceback (most recent call last)
<ipython-input-99-3200d4255dc8> in <module>
----> 1 da.ones(d, chunks=2)

c:\users\genevieb\documents\github\dask-hacking\dask\dask\array\wrap.py in wrap_func_shape_as_first_arg(func, *args, **kwargs)
     38     dtype = np.dtype(dtype)
     39
---> 40     chunks = normalize_chunks(chunks, shape, dtype=dtype)
     41     name = kwargs.pop('name', None)
     42

c:\users\genevieb\documents\github\dask-hacking\dask\dask\array\core.py in normalize_chunks(chunks, shape, limit, dtype, previous_chunks)
   1913         chunks = sum((blockdims_from_blockshape((s,), (c,))
   1914                       if not isinstance(c, (tuple, list)) else (c,)
-> 1915                       for s, c in zip(shape, chunks)), ())
   1916     for c in chunks:
   1917         if not c:

c:\users\genevieb\documents\github\dask-hacking\dask\dask\array\core.py in <genexpr>(.0)
   1913         chunks = sum((blockdims_from_blockshape((s,), (c,))
   1914                       if not isinstance(c, (tuple, list)) else (c,)
-> 1915                       for s, c in zip(shape, chunks)), ())
   1916     for c in chunks:
   1917         if not c:

c:\users\genevieb\documents\github\dask-hacking\dask\dask\array\core.py in blockdims_from_blockshape(shape, chunks)
    757     if shape is None:
    758         raise TypeError("Must supply shape= keyword argument")
--> 759     if np.isnan(sum(shape)) or np.isnan(sum(chunks)):
    760         raise ValueError("Array chunk sizes are unknown. shape: %s, chunks: %s"
    761                          % (shape, chunks))

c:\users\genevieb\documents\github\dask-hacking\dask\dask\array\core.py in __bool__(self)
   1076             raise ValueError("The truth value of a {0} is ambiguous. "
   1077                              "Use a.any() or a.all()."
-> 1078                              .format(self.__class__.__name__))
   1079         else:
   1080             return bool(self.compute())

ValueError: The truth value of a Array is ambiguous. Use a.any() or a.all().
```

**Comment by jcrist** [comment]
Those functions do different things:

- `da.ones` and `np.ones` accept a sequence of integers describing the output shape. A 1D numpy array happens to be a valid sequence, but tuples/lists are certainly more common here.
- `da.ones_like` and `np.ones_like` accept an existing array-like and return a new array-like with the same shape and dtype filled with ones. Array-likes are the expected input here.

Where in the docstring for `da.ones` (which is just a copy of `np.ones`) does it indicate that a dask array should be a viable input? How could the language be improved?

We could certainly have a better error here, probably checking for `da.Array` inputs around here, and erroring appropriately: https://github.com/dask/dask/blob/91ce8c87ffc992b5b96e1ef2f1971ebefe6d4d73/dask/array/wrap.py#L27-L31

Would you be interested in submitting a fix?

**Comment by GenevieveBuckley** [comment]
I realise they do different things, so I think my question was more along the lines of "if a 1D numpy array is acceptable input, should a 1D dask array also be considered acceptable as input"? Since the docstring is a copy of the numpy docstring, it doesn't mention dask arrays one way or the other.

is your suggestion that we add something like this to the function? I could do that.
```python
if isinstance(x, dask.array.Array):
    raise ValueError('Dask array input not supported, please use tuple, list, or a 1D numpy array as input instead.')
```

**Comment by jcrist** [comment]
> is your suggestion that we add something like this to the function? I could do that.

If that's a sufficient fix from your perspective, then yeah that'd be good. I'd use a `TypeError` instead though.
