### ISSUE TITLE
Weekly maintainer standup

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4694]
Three people have mentioned a desire to have a weekly standup recently.  Let's start this back up again.  I'll arbitrarily suggest Thursdays at 3pm UTC (8am US Pacific, 11am US Eastern, 5pm Paris) at https://appear.in/dask-dev, though counter proposals are welcome.

**Comment by mrocklin** [comment]
Actually, to help plan things, it's probably better to have this earlier in the week.  Maybe Tuesday?

**Comment by jcrist** [comment]
End of week is also fine, can discuss what everyone did that week and set tentative plans for the following week. I don't think it really matters what day it is as long as most people can make it. I'm free every day but Thursdays at the suggested time.

**Comment by jrbourbeau** [comment]
I'm free anytime other than Tuesdays 2-3 PM and Fridays 12-1 PM central time

**Comment by jakirkham** [comment]
Could I suggest we aim to keep the meeting to 30mins?

Also would suggest we do a poll for times, which might help us pick a time a bit quicker. Given we each know our own schedules well, but not other people's. Happy to make this poll if the idea is agreeable.

**Comment by jcrist** [comment]
I second keeping it less than 30 min (I was hoping for 15-20 tops). I don't think we should try to discuss anything to technical (this is just a standup), I'd mostly be interested in discussing:

- What everyone did for the last week (or 2)
- What everyone is planning on doing for the next week
- Any additional *brief* discussion around planning future work

Technical discussions should be held on github, or scheduled separately IMHO.

**Comment by mrocklin** [comment]
>  I'd mostly be interested in discussing:

-  What everyone did for the last week (or 2)
- What everyone is planning on doing for the next week
- Any additional brief discussion around planning future work

Personally I'm more interested in planning than in reporting.  So I might want to add on questions like ...

-  What are some current fires going on in the project?
-  What common themes do we see coming up recently?
-  Who has time to address these over the coming week?

I think that raising these up is probably important to help determine what people work on, especially if it's not the case that everyone is tracking the issue tracker.

**Comment by mrocklin** [comment]
> Also would suggest we do a poll for times, which might help us pick a time a bit quicker. Given we each know our own schedules well, but not other people's. Happy to make this poll if the idea is agreeable.

Yes, please do (also, in the future I encourage people to just do things rather than wait for the group to assent)

**Comment by jcrist** [comment]
I've created a doodle poll here: https://doodle.com/poll/e6r4kzhiwavzpwr9

If everyone could respond asap that would be appreciated. Thanks.

**Comment by mrocklin** [comment]
Thanks @jcrist !  Responded.

**Comment by jakirkham** [comment]
Submitted. Thanks Jim!

**Comment by jcrist** [comment]
From looking at the times when everyone was available on the poll, I'll arbitrarily pick Tuesdays at 10:30 am Central as the standup time. Lets meet at http://appear.in/dask-dev. I'll be there tomorrow morning, but given the short notice don't expect everyone to make the first one.

**Comment by jakirkham** [comment]
Thanks Jim. Have sent out a calendar invite to everyone who responded to the poll. Please let me know if you got it (or not). Also please check that I have configured it correctly. Happy to fix if not.

**Comment by jrbourbeau** [comment]
@jakirkham thank you for setting up the calendar invite, I received it and it seems to be configured correctly

**Comment by mrocklin** [comment]
In the call today we mentioned organizing a issue/PR closeout sprint sometime next week.  I've put up a doodle poll here: https://doodle.com/poll/t38be8upiy8z6d72

@jcrist you mentioned that you might be out next week.  Is this the entire week, or is there some possibility that you'll be free later on?

**Comment by jcrist** [comment]
No, looks like it's not til next month.

**Comment by mrocklin** [comment]
Based on the Doodle poll, it looks like tomorrow, Tuesday April 30th works best for everyone.  I recommend that we meet up at 10am US Central time at https://appear.in/dask-dev .  

OK @jcrist @martindurant @jrbourbeau @jakirkham @quasiben ? (also @TomAugspurger if you feel like making a brief appearance it'd be fun to see you)  Also, if anyone else wants to join this is entirely open to anyone (anyone who wants to spend a day closing out old issues and PRs that is :) )

**Comment by TomAugspurger** [comment]
Tomorrow probably won't work for me. I'll be back full time on the 13th.

**Comment by mrocklin** [comment]
Yeah, no expectations.  Mostly this was an FYI in case nap times align and
you want to pop in to say hi for a few minutes.

**Comment by jcrist** [comment]
Fine by me. To be clear, were we wanting to continue with the standups at 10:30 am Central on Tuesdays like we did last week? I was under the impression that would be a weekly thing.

**Comment by mrocklin** [comment]
Agreed.  I figure that we just roll it into the day.  Open to other
thoughts though.

**Comment by jcrist** [comment]
No, that makes sense, just wanted to clarify that on normal tuesdays standups will still occur.

**Comment by jrbourbeau** [comment]
That time works for me. Unfortunately I won't be able to stay all day, but looking forward to a few hours of cleaning up the issue tracker and old PRs : )

**Comment by TomAugspurger** [comment]
Looks like I’ll end up being free at 10:00, so I’ll pop in then!

**Comment by jcrist** [comment]
I'm going to close this issue, as we've resolved to have standups at http://appear.in/dask-dev every Tuesday at 10:30 am Central.

**Comment by TomAugspurger** [comment]
@jakirkham can you publish the calendar invite, so new maintainers can subscribe to it?

**Comment by jakirkham** [comment]
Sorry Tom, I created this event in my work calendar and invited people to it. Can see how this might be a problem though. For now have simply added you to the event. Please let me know if you got the invite. Open to a different solution for how we track this event long term if needed.

**Comment by TomAugspurger** [comment]
Got it, thanks.
