### ISSUE TITLE
Getting access to the delayed.Delayed class

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#4702]
I'd like to get access to the `delayed.Delayed` class, since I'm writing some wrappers around delayed objects to experiment with distributed incremental computation.

However I've found that I cannot even import it.

```
import dask
import dask.delayed

dask.delayed.Delayed
```

I get this error:

```
AttributeError: 'curry' object has no attribute 'Delayed'
```

I'm guessing this is problematic as the smart constructor `delayed` is conflicting with the module name of `delayed.py`.

**Comment by jrbourbeau** [comment]
You could use

```python
from dask.delayed import Delayed
```

**Comment by jcrist** [comment]
Closing as answered. Feel free to reopen if needed.
