### ISSUE TITLE
Tests skipped with optional dependencies installed

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#4706]
There are a few tests being skipped with `pytest.importorskip` in the CI even though it appears the corresponding dependency is installed in the CI environment. See https://travis-ci.org/dask/dask/jobs/520461060#L2631 for a `snappy` example and https://ci.appveyor.com/project/daskdev/dask/builds/23870810#L1112 for a `moto` example. It's not immediately clear to me why this is happening, so I'm opening up this issue to document and track the problem.

**Comment by jcrist** [comment]
Perhaps imports are failing due to incompatible/missing deps of those packages?

**Comment by jrbourbeau** [comment]
Looks like unpinning the `conda` version in #4720 fixed this issue for `zarr`-related tests on Appveyor.

I plan to look into this more sometime next week

**Comment by jcrist** [comment]
@jrbourbeau does the issue persist?

**Comment by mrocklin** [comment]
This appears to be stale.  Closing.  (Though please reopen if the problem persists)
