### ISSUE TITLE
map_blocks: block_info doesn't work with broadcasting

### ISSUE THREAD

**Issue by bmerry** [dask/dask#4712]
While working on an alternative approach to #4476, I noticed that the code in `da.map_blocks` for computing `block_info` doesn't take broadcasting into account. That causes the following code to crash (on dask 1.2.0-10-g967e30c3):
```python
import numpy as np
import dask.array as da

def op(a, b, block_info):
    return a + b

a = da.from_array([[10, 20]], chunks=1)
b = da.from_array([[1], [2]], chunks=1)
c = da.map_blocks(op, a, b, chunks=((1, 1), (1, 1)))
print(c.compute())
```

```
IndexError: index 2 is out of bounds for axis 0 with size 2
```

If the `block_info` argument is removed, then it runs and produces sensible output.

**Comment by jcrist** [comment]
Thanks for the excellent issue example @bmerry. This should be fixable, any issue in tackling this?

**Comment by bmerry** [comment]
It wasn't immediately obvious to me where the broadcasting happens and hence how to unwind it for constructing the block info - I think it's several layers further down. I guess one option is just to handle any dimension with only one block specially, since in that case the block spans the whole array regardless of whether that dimension was broadcast or not.

**Comment by bmerry** [comment]
I can take a look at fixing this, but after #4713 is merged since that touches some of the same code.
