### ISSUE TITLE
failed to write index in to_parquet() when using read_sql_table()

### ISSUE THREAD

**Issue by dungthuapps** [dask/dask#4723]
hi, I have tried using read_sql_table to read data from sqlite.
but failed when trying to write to parquet file while seting write_index=True
My code:

``` python
import logging
import os
import sqlite3
import datetime
import numpy as np
import pandas as pd
import sqlalchemy as sa
import multiprocessing
import dask
from dask.distributed import Client
from dask import dataframe as ddf

client = Client()
meta = {"MEASURE_DATE": [pd.to_datetime("2000-01-01")],  "STATIONS_ID": [1], 'FX': [0.1]}
meta = pd.DataFrame(meta)[0:0]
```
```python
x = ddf.read_sql_table(table_name, 
                           sqlite:///{}".format(DB_FILE),
                           index_col="STATIONS_ID",
                           meta=meta,
                           columns=list(meta.columns),
                           npartitions=500)
x["MEASURE_DATE"] = x["MEASURE_DATE"].map_partitions(pd.to_datetime)
x["YEAR_MONTH"] = x["MEASURE_DATE"].apply(lambda x: x.strftime("%Y-%m"),
        meta=("YEAR_MONTH", np.str))
x["YEAR"] = x["MEASURE_DATE"].apply(lambda x: x.strftime("%Y"),
        meta=("YEAR", np.str))
logging.debug(x._meta.dtypes)
```
```python
x.to_parquet(os.path.join(DATA_FOLDER, "parquet/climate"),
                 engine='pyarrow',
                 write_index=False,
                 partition_on=["YEAR", "YEAR_MONTH", "MEASURE_DATE"])
```
### Case 1: leave index_col in meta
meta = {"MEASURE_DATE": [pd.to_datetime("2000-01-01")],  "STATIONS_ID": [1], 'FX': [0.1]}
index_col = "STATIONS_ID"
**> KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'**

### Case 2: remove index_col in meta
meta = {"MEASURE_DATE": [pd.to_datetime("2000-01-01")],  'FX': [0.1]}
index_col = "STATIONS_ID"
x.to_parquet(..., write_index=True, ...)
**>KeyError: 'STATIONS_ID'**

### Case 3: a tricky way to write column STATIONS_ID -> rename index_col 
meta = {"MEASURE_DATE": [pd.to_datetime("2000-01-01")],  "STATIONS_ID": [1], 'FX': [0.1]}
index_col = sa.sql.columns("STATIONS_ID").label("ID")
x.to_parquet(..., write_index=False, ...)
-> this will write all columns to parquet

So I believe a problem comes when I set write_index=True in to_parquet(). If I would like to write all columns including index, I must create a new column and rename it as index and set write_index=False.

**Comment by jcrist** [comment]
Thanks for filing a bug report. A few general notes when reporting bug reports to projects:

- Please include the full traceback when you get error messages. You've provided the text of the error, but the full traceback is useful for seeing where the error comes from.
- It appears that your issue is happening when writing the output parquet files, not when reading from the sql table (to confirm, try to do `.head()` on `x` right after `read_sql_table`). If so, this means that operation is irrelevant to the cause of the error, the dataframe could have come from anywhere (including by creating one in the script). In general we prefer issue reports to be runnable as is (a "minimal, complete, verifiable issue": https://blog.dask.org/2018/02/28/minimal-bug-reports). See if you can create a dataframe that looks like your dataframe above but experiences the same issue when calling `to_parquet` above. This might look like:

```python
import pandas as pd
# Create a dataframe with the same schema as above, but do it in the script
df = pd.DataFrame(...)
# Convert to a dask dataframe
ddf = dd.from_pandas(df, npartitions=3)
# Output to parquet
ddf.to_parquet(os.path.join(DATA_FOLDER, "parquet/climate"),
               engine='pyarrow',
               write_index=False,
               partition_on=["YEAR", "YEAR_MONTH", "MEASURE_DATE"])
```

Also cc @martindurant for parquet knowledge.

**Comment by martindurant** [comment]
The `meta` you provide must match the dataframe you expect - in this case, it will have an index, but you have not specified one. You probably need

```
meta = {"MEASURE_DATE": [pd.to_datetime("2000-01-01")],  "STATIONS_ID": [1], 'FX': [0.1]}
meta = pd.DataFrame(meta).set_index('STATIONS_ID')[0:0]
```
(or provide `index=` in the call to `DataFrame`).

Or you could always map_partitions with `reset_index`, or something... I agree with @jcrist , it's too hard to know what you're really doing to try to guess further.

**Comment by dungthuapps** [comment]
@martindurant sorry, this actually 2 problems.
First is with read_sql_table
assume. my index col is **"STATIONS_ID"**
in case 1: I cannot define both in read_sql_table for the index in meta and index_col . 
if I use read_sql_table(, **index_col="STATIONS_ID"**) and also defined it in meta -> error
Then I need to rename "STATIONS_ID" -> "ID" by: sql.columns("STATIONS_ID").label("ID") to avoid this error

second is with to_parquet() after creating dataframe from read_sql_table (not sure with other methods)
every time I use write_index=True it failed
every time I set append=True -> if the file or folder of parquet available -> it failed

I will reproduce and send you traceback

**Comment by jcrist** [comment]
@dungthuapps any update here? A reproducible example (https://blog.dask.org/2018/02/28/minimal-bug-reports) would be very useful in resolving your issue.

**Comment by dungthuapps** [comment]
@jcrist Sorry, I forgot: here I reproduce my code more simpler as example
```
from dask.distributed import Client
from dask import dataframe as ddf
import pandas as pd
import numpy as np
import sqlite3
# Generate test data
db_file = "testdb.db"
conn_str = "sqlite:///{}".format(db_file)
table_name = "test"

id = list(range(0, 100))
v1 = np.random.randint(1, size=100)
v2 = np.random.randint(1, size=100)

pd.DataFrame({"id": id, "v1": v1, "v2": v2}).to_sql(table_name,
                                                    sqlite3.connect(db_file),
                                                    if_exists="replace")

# Reproduce problem
client = Client()
meta = {"id": [1], 'v1': [0], 'v2': [1]}
meta = pd.DataFrame(meta)[0:0]

x = ddf.read_sql_table(table_name, conn_str,
                       index_col="id",
                       meta=meta,
                       columns=list(meta.columns),
                       npartitions=10)

```
and the error trace
``` 
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function check_meta at 0x0000028D099E3950>, (<function apply at 0x0000028D058618C8>, <function _read_sql_chunk at 0x0000028D09A58B70>, [<sqlalchemy.sql.selectable.Select at 0x28d060e4e48; Select object>, 'sqlite:///testdb.db', Empty DataFrame
Columns: [id, v1, v2]
Index: []], (<class 'dict'>, [['index_col', 'id']])), Empty DataFrame
Columns: [id, v1, v2]
Index: [], 'from_delayed'))
kwargs:    {}
Exception: KeyError('Only a column name can be used for the key in a dtype mappings argument.',)
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function check_meta at 0x000001BF015D3C80>, (<function apply at 0x000001BF7D5C18C8>, <function _read_sql_chunk at 0x000001BF0167C840>, [<sqlalchemy.sql.selectable.Select at 0x1bf7e6ff048; Select object>, 'sqlite:///testdb.db', Empty DataFrame
Columns: [id, v1, v2]
Index: []], (<class 'dict'>, [['index_col', 'id']])), Empty DataFrame
Columns: [id, v1, v2]
Index: [], 'from_delayed'))
kwargs:    {}
Exception: KeyError('Only a column name can be used for the key in a dtype mappings argument.',)
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function check_meta at 0x0000028D099E3950>, (<function apply at 0x0000028D058618C8>, <function _read_sql_chunk at 0x0000028D09A58B70>, [<sqlalchemy.sql.selectable.Select at 0x28d09a8f198; Select object>, 'sqlite:///testdb.db', Empty DataFrame
Columns: [id, v1, v2]
Index: []], (<class 'dict'>, [['index_col', 'id']])), Empty DataFrame
Columns: [id, v1, v2]
Index: [], 'from_delayed'))
kwargs:    {}
Exception: KeyError('Only a column name can be used for the key in a dtype mappings argument.',)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\dask\base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\dask\base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\client.py", line 2332, in get
    direct=direct)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\client.py", line 1656, in gather
    asynchronous=asynchronous)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\client.py", line 676, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\utils.py", line 282, in sync
    six.reraise(*error[0])
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\utils.py", line 267, in f
    result[0] = yield future
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\tornado\gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\distributed\client.py", line 1497, in _gather
    traceback)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\dask\compatibility.py", line 93, in apply
    return func(*args, **kwargs)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\dask\dataframe\io\sql.py", line 178, in _read_sql_chunk
    return df.astype(meta.dtypes.to_dict(), copy=False)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\pandas\core\generic.py", line 5673, in astype
    raise KeyError('Only a column name can be used for the '
KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'

```

**Comment by dungthuapps** [comment]
This block as suggested by @martindurant solved the above error but when writing to parquet, then error again.
``` python
meta = {"id": [1], 'v1': [0], 'v2': [1]}
meta = pd.DataFrame(meta)**.set_index('id')[0:0]**
```
Traceback (most recent call last):
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\pandas\core\frame.py", line 4178, in set_index
    level = frame[col]._values
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\DevTools\miniconda3\envs\data-etl-3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

**Comment by martindurant** [comment]
But you can't partition on the index...

Following successfully loading the dataframe, as I think you have, you need to
```
x.reset_index().to_parquet("test.parquet", engine='pyarrow',
             write_index=True, partition_on=["id", "v1"])
```
and I think it's unlikely that you really want `write_index=True`.

**Comment by dungthuapps** [comment]
Thanks, @martindurant. 
You are right, I just want to do partition on "v1", not on index "id", my mistake. Your code solved the problem.

However, correct me if I wrong, I think  reset_index or set_index will lead to expensive computation, doesn't it?

**Comment by dungthuapps** [comment]
I close issue here, because the script provided by @martindurant  solved the issue

**Comment by martindurant** [comment]
> reset_index or set_index will lead to expensive computation

No, reset_index should be simple, and you are calling set_index on the small meta piece, not the total dataframe, so that's ok too.

**Comment by dungthuapps** [comment]
Thanks @martindurant 
Could you also add the your above hints of dealing with index_col and parquet to the documents to help other users like me?

**Comment by martindurant** [comment]
I don't know where such documentation might go, this is rather a specific case. I imagine anyone doing a search might happen to find this very issue.
