### ISSUE TITLE
http seek name nloc is not defined with whence=1

### ISSUE THREAD

**Issue by youngsaj** [dask/dask#4724]
**Bug Report***
I've run a trace on an issue with seek into https file.
I get to a point where I have a whence=1, and get *** NameError: name 'nloc' is not defined
self.loc is definitely set
for whence = 1 it's doing
nloc += 

which off hand doesn't make sense, but I could be overlooking something simple.
I also have a self.size so that's good.
attempting it on:
https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE16I_IM16I.nitf

**Comment by martindurant** [comment]
Agree, should be `nloc = self.loc + where`.
Would you like to submit the fix as a PR?

Surprised that you are calling this directly, what is your use case.

**Comment by youngsaj** [comment]
I'm trying to write an Intake driver.
I was closely trying to reuse code that used local file system.

With local file system I could do:
set_of_open_files = dask.bytes.open_files(urlpath, mode='rb')

Reading basic metadata from the file, then later pulling out a subset of file.
Perhaps not the way to do that, I'm open for suggestions.

I'll give a PR a try (very limited use on my part of github per se)

**Comment by martindurant** [comment]
You are quite right, so you are going beyond typical Dask use here. 
Note that the version of HTTPFile in [fsspec](https://github.com/martindurant/filesystem_spec) doesn't have this problem, and eventually Intake will be moving to use fsspec instead of the functions in Dask (and eventually eventually, Dask should use fsspec).

**Comment by jrbourbeau** [comment]
> I'll give a PR a try (very limited use on my part of github per se)

Thanks @youngsaj! There is documentation about contributing to Dask at http://docs.dask.org/en/latest/develop.html.

**Comment by quasiben** [comment]
@youngsaj are you still interested in submitting a PR ?  Happy to help/review

**Comment by martindurant** [comment]
(if no reply, I can handle this tomorrow)
