### ISSUE TITLE
Conditional gather?

### ISSUE THREAD

**Issue by ericmjl** [dask/dask#4729]
If I would like to gather the result of parallel computations that have finished (not those that have thrown an error, or are still in computation), I would write cod that does this:

```python
scores = dict()
for assay, score_future in scores_futures.items():
    if score_future.status == 'finished':
        scores[assay] = client.gather(score_future)
```

Would it be of interest, and would it also make sense or not (I'm open to this not being a sensible thing), to have this wrapped in a `client.gather_finished(futures)` class method? Some of my parallel computations take a long time, while others finish up pretty quickly, so being able to gather just the finished jobs and continue prototyping, while allowing myself to come back later and gather everything later, might be of use, I think.

**Comment by martindurant** [comment]
Is `as_completed` useful for you? https://distributed.readthedocs.io/en/latest/api.html#distributed.as_completed

**Comment by ericmjl** [comment]
Thanks for pinging back, @martindurant!

I took a careful look at the docs, but I think I need to clarify one point:

> Calling next on the iterator will block until the next future completes, irrespective of order.

If I understand the above statement correctly, I think this might be a blocker to using `as_completed` in the way I'm hoping to, but I might be wrong here. I'm basically looking for non-blocking behaviour - that is, if the future is still running, skip over it, and let me just continue using the results of the futures that already have finished. From that line in the doc, it looks like using `as_completed` may still block if I'm iterating over the futures. 

Can I check, is my mental model wrong here?

**Comment by martindurant** [comment]
Yes, I suppose you are right. Your loop is simple enough, and seems it works well - I don't suppose it's designed to be run too often. 

There may be interest in supplying this convenience method. I would recommend proposing a PR with clear docstring and tests (some futures don't finish for a long time, some error).

**Comment by eriknw** [comment]
The `as_completed` object is able to be used in a non-blocking fashion.  For example:
```python
my_tasks = as_completed([x, y, z])

# option 1, the batch will be empty if none are ready.  Doesn't block
batch = my_tasks.next_batch(block=False)

# option 2, check if any are ready
if not my_tasks.queue.empty():
    batch = my_tasks.next_batch()
    # or you could just grab one result if that fits better in your loop
```
Hope this helps.  The docs could maybe be improved.  Check out the source code:

http://distributed.dask.org/en/latest/_modules/distributed/client.html#as_completed

**Comment by quasiben** [comment]
@ericmjl what are your thoughts here ?  The block described by @eriknw seems to satisfy what you are after but the docs should probably be amended.

**Comment by jcrist** [comment]
I added the `as_completed` method docstrings to the docs in https://github.com/dask/distributed/pull/2642, and also added a public method `has_ready` for checking if there are any ready futures. Erik's example using more public interfaces would then look like:

```python
my_tasks = as_completed([x, y, z])

# option 1, the batch will be empty if none are ready.  Doesn't block
batch = my_tasks.next_batch(block=False)

# option 2, check if any are ready
if my_tasks.has_ready():
    batch = my_tasks.next_batch()
```

**Comment by ericmjl** [comment]
Thanks @quasiben and @eriknw for getting back. 

I briefly tried `as_completed`, but it didn't work out for what I was thinking of doing. That's not an issue though, as the code block I had was small enough that I could just make it a function and leave the patch as just that - "a patch". 

I'll have another opportunity to try out `as_completed` later in the week, when I get back to the project I was working on, after I finish tutorials @ PyCon.
