### ISSUE TITLE
Repartition min/max behavior

### ISSUE THREAD

**Issue by codercody** [dask/dask#4740]
I’m working in the dataframe/multi.py file and had the following issue. When I call the merge method, the use of align_partitions often causes the desired behavior of divisions to no longer be adhered. That is, it might cause a DataFrame to have divisions d_0, d_1, …, d_n where the ith part doesn’t necessarily have minimum index d_i. Indeed, the merge function sometimes causes parts to be completely empty.

My question is: in general, how strictly does Dask obey the divisions rule? What I’m implementing requires that the minimum of the ith division is d_i. Is there any way for me to enforce this rule? I tried making a list containing the minimum value of each division and then repartitioning on that list.

On another similar note, is there any good way to enforce that the upper bound of each division is strictly non-inclusive? That is, I want the ith partition to not contain any indices of maximum value equal to d_{i+1}. Would df.repartition(divisions=df.divisions) do that or am I thinking about it wrong?

**Comment by quasiben** [comment]
Thanks for asking the question.  I recommend reading the following related issue: https://github.com/dask/dask/issues/3384 

cc @mrocklin

**Comment by mrocklin** [comment]
> align_partitions often causes the desired behavior of divisions to no longer be adhered

That sounds concerning.

> where the ith part doesn’t necessarily have minimum index d_i

Ah, in this case divisions are a bound, not a guarantee that an element exists.

> My question is: in general, how strictly does Dask obey the divisions rule? What I’m implementing requires that the minimum of the ith division is d_i. Is there any way for me to enforce this rule? 

Nope.  We can't enforce that a value exists over all operations.  For example we might call something like `df.sample(frac=0.0001)` and it would be very unlikely that the minimum value continued to exist.  The only way to achieve this would be to compute every operation as we go, which would destroy laziness.

**Comment by mrocklin** [comment]
I think that this question has been answered.  Closing.
