### ISSUE TITLE
[FEA] Remove pandas dependency of cummin_aggregate and cummax_aggregate

### ISSUE THREAD

**Issue by beckernick** [dask/dask#4747]
Removing the pandas dependency in the Series/DataFrame vs scalar check within [cummin_aggregate](https://github.com/dask/dask/blob/master/dask/dataframe/methods.py#L147) and [cummax_aggregate](https://github.com/dask/dask/blob/master/dask/dataframe/methods.py#L154) will help allow us to use other backend dataframe libraries such as cuDF for cummin and cummax. When these functions are run in the cummin/cummax operations, the type of argument `x` is determined by the dataframe backend.

**Comment by quasiben** [comment]
@beckernick good idea!  Any interest in submitting a PR ?  You could probably use `is_dataframe_like`

https://github.com/dask/dask/blob/8d13240841fcefb6c2410f94c4d7dbd7f7ea9a66/dask/dataframe/utils.py#L502-L518

**Comment by beckernick** [comment]
@quasiben Yes absolutely. I intended to take this and do exactly that (used that in an update to `_take_last` last week), but I need to prioritize other work until mid-week. Happy to pick this up if nobody else jumps in before that timeline.
