### ISSUE TITLE
Add a `HighLevelGraph.__setitem__`

### ISSUE THREAD

**Issue by lsorber** [dask/dask#4750]
We're adding support for `HighLevelGraph`s in [graphchain](https://github.com/radix-ai/graphchain) (cf. https://github.com/radix-ai/graphchain/issues/35), and in doing so we had a need for a `HighLevelGraph.__setitem__`. Right now we're monkey patching that class, but it would be great if dask could add a simple implementation itself so we don't have to do that.

For reference, here's our implementation:
```python
def hlg_setitem(self: HighLevelGraph, key: Hashable, value: Any) -> None:
    """Set a HighLevelGraph computation."""
    for d in self.layers.values():
        if key in d:
            d[key] = value
            break

# Monkey patch HighLevelGraph to add a missing `__setitem__` method.
if not hasattr(HighLevelGraph, '__setitem__'):
    HighLevelGraph.__setitem__ = hlg_setitem
```

**Comment by quasiben** [comment]
Hey @lsorber thanks for raising an issue 

cc @mrocklin

**Comment by mrocklin** [comment]
First, my apologies that changes in Dask broke your code 

One challenge here is that the layers of a high level graph can be shared among many graphs.  One of the reasons why they were created was to avoid repeatedly copying large dictionaries every time we made a change.   For this reason I'm somewhat wary of adding mutation onto these classes. 

I wonder if, instead, something like graphchain might be better suited as an optimization, that was activated during computation, when we *do* create explicit copies of the graph, and where we're quite comfortable subbing in subgraphs.

**Comment by jcrist** [comment]
I agree with @mrocklin that directly touching the graphs outside of the standard plugin spots (optimizations, etc..., see https://docs.dask.org/en/latest/optimize.html#customizing-optimization and https://docs.dask.org/en/latest/custom-collections.html) is potentially fragile. It could also be a scheduler plugin, which is how caching currently works (see https://github.com/dask/dask/blob/master/dask/cache.py and https://docs.dask.org/en/latest/diagnostics-local.html#custom-callbacks). The downside is this would need to be implemented differently for the local and distributed schedulers, but may also be useful.

**Comment by lsorber** [comment]
Graphchain is in fact already intended to be used as a dask graph optimizer (which at the time of creation looked like the best way to hook into dask). This is an example usage from the README:

```python
with dask.config.set(scheduler='sync', delayed_optimize=graphchain.optimize):
    result.compute(location='s3://mybucket/__graphchain_cache__')
```

When dask calls the optimizer, graphchain replaces computations with `CachedComputation`s, which is a light wrapper around the original computation. It's at that time that we have the need to set computations in a regular graph or `HighLevelGraph`.

@jcrist I think the callback API looks like a great fit, but as you say it would need a different approach for other schedulers. If other schedulers are supported in the future, we could consider plugging into this instead.

If there are any other best practices we should be following, I'd be happy to apply those to graphchain.

**Comment by jcrist** [comment]
>  If other schedulers are supported in the future, we could consider plugging into this instead.

The local and distributed schedulers are sufficiently different that I doubt they'll ever have the same plugin api. That said, both do expose hooks for their internals:

- Distributed: http://distributed.dask.org/en/latest/plugins.html
- Local: https://docs.dask.org/en/latest/diagnostics-local.html#custom-callbacks

> When dask calls the optimizer, graphchain replaces computations with CachedComputations, which is a light wrapper around the original computation. It's at that time that we have the need to set computations in a regular graph or HighLevelGraph.

I recommend not mutating the original graph, but creating a new graph. The exposed api is intended to encourage immutability. Things like optimizations generally take in a graph and return a *new* graph with the required optimizations applied. I agree with @mrocklin above - we're unlikely to add methods that enable mutation of `HighLevelGraph` here as it goes against our internal design.

**Comment by lsorber** [comment]
I believe that's what we're doing:

1. We create a deepcopy of the graph
2. We mutate the copy's computations

Is there another way we should be creating the cached version of the graph? We'd need to support both classical dask graphs and HighLevelGraphs.

**Comment by mrocklin** [comment]
Often in optimization we end up converting the HighLevelGraph
MutableMapping objects into normal dicts.  This tends to be necessary
before we do any mutation operations.

**Comment by lsorber** [comment]
All right, we can do that. I was hesitant to take that approach because it would destroy the additional information that a `HighLevelGraph` carries. Should we be using `dask.utils.ensure_dict` to normalise the graph to a dict before optimizing it?

Also, what would be the best way to benefit from dask's default optimizer(s) in addition to third-party optimizers like graphchain? As far as I can tell, if a user selects the graphchain optimizer they would miss out on the default optimizations.

**Comment by mrocklin** [comment]
Yes to ensure_dict.

Yeah, we don't currently have a nice way to add something into an existing
optimization pipeline.  There is no structure here to take advantage of.
It would be nice to see this improved.

**Comment by jcrist** [comment]
Currently you can add things to a list of optimizations to run *before* the defaults. This isn't super flexible, but may work for what you need.

```python
In [1]: def myfunc(dsk, keys):
   ...:     print("Custom called")
   ...:     return dsk
   ...:

In [2]: import dask.array as da
/Users/jcrist/Code/dask/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

In [3]: x = da.arange(100, chunks=10)

In [4]: import dask

In [5]: with dask.config.set({'optimizations': [myfunc]}):
   ...:     x.sum().compute()
   ...:
Custom called
```

**Comment by mrocklin** [comment]
The defaults will want to receieve HighLevelGraphs ideally though, and
they'd like a state of things after the high level graph optimizations are
complete, and they can modify a normal dictionary.

**Comment by jcrist** [comment]
Perhaps we should add a configuration option for methods to run after the default optimizations? These would receive a dict graph and keys, and should return a dict.

**Comment by mrocklin** [comment]
Long term I would prefer that we try to structure optimizations somewhat.
Perhaps a named list or something that people can query and inject at more
precise locations.  That's a larger conversation though.

**Comment by jakirkham** [comment]
Totally unrelated, but graphchain looks really cool, @lsorber! You might enjoy engaging in the discussion in issue ( https://github.com/dask/dask/issues/2119 ) where users are looking for functionality like this. 🙂

**Comment by lsorber** [comment]
Thanks @jakirkham! Will check out that issue and see if we can contribute there.

In the short term, we'll be updating graphchain to use `ensure_dict` before optimising the graph. Long term it would indeed be nice if the dask graph optimization API is extended to support a series of optimizers.

**Comment by mrocklin** [comment]
> Long term it would indeed be nice if the dask graph optimization API is
extended to support a series of optimizers.

Agreed.  If this is something that you or people around you might be able
to help with, that would be great (though of course, no expectation).  If
so then we should probably design something in an issue somewhere.

**Comment by jakirkham** [comment]
What is the next step here? @lsorber would you be interested in opening a new issue as @mrocklin suggests? Is there anything else we should try to do in this issue?

**Comment by lsorber** [comment]
From my perspective, this issue can be closed since the current best practice is to use `ensure_dict` before modifying the graph.

In terms of next steps, I think it'd be great to work towards upgrading the graph optimiser API to allow multiple optimiser passes over the graph.

I don't have a concrete proposal for this though, and think the topic might be much deeper than it seems at first sight. For example, TensorFlow's approach to declarative graph optimisation is quite complex (they have `GraphOptimizationPass`, `GraphOptimizer`, `Grappler`, and `XLA`) [1].

[1] https://www.slideshare.net/ssuser5f01c2/tensorflow-134544864

**Comment by jcrist** [comment]
Cool, I'll close this for now. Agreed that we should generalize how we expose graph optimizations - I think we only need a few plugin points for users to insert their own functions in different places, we won't need anything as complicated as what tensorflow has.
