### ISSUE TITLE
Use derived_from logic in dask array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4758]
Dask Dataframe methods copy Pandas docstrings, but with some logic to add disclaimers around unsupported arguments (and other niceties).  It would be useful to reuse this logic in dask array, which often uses functools.wraps.  I ran into this in dask.array.routines, but I suspect that it is in lots of places.

The `derived_from` code is currently baked around class methods, which isn't always appropriate for dask array (many of which are top level functions), but probably a lot of the lower level bits would work fine.  We should...

1.  Rearrange the logic in derived_from to also support top level functions, making a wraps-like decorator function
2.  Replace functools.wraps with that decorator

**Comment by martindurant** [comment]
Just to note: dask.array.Array does have a number of methods using `derived_from` to fill in their docstrings. I'll look into applying to functions, as opposed to methods, as suggested.
