### ISSUE TITLE
Bug: visualize() not showing any text in rectangles

### ISSUE THREAD

**Issue by H4dr1en** [dask/dask#4767]
Regarding the example of the [doc](http://docs.dask.org/en/latest/delayed.html) for delayed, the result of the call to `visualize()` gives me:

![image](https://user-images.githubusercontent.com/16240134/57063641-37f98500-6cc4-11e9-874d-44789ceaade5.png)

No text in rectangles...

**Comment by martindurant** [comment]
It is the doc which is outdated, this change was purposeful, because the text was not adding any extra information.
