### ISSUE TITLE
TypeError: read_json() got an unexpected keyword argument 'meta'

### ISSUE THREAD

**Issue by YashSinha1996** [dask/dask#4773]
Code:
```
import dask.dataframe as dd
df = dd.read_json('dir_name/*.json', meta={"column": dict})
```
Environment:
- OS: Ubuntu 16.04
- Version: 1.2.1
- Installation: Using pip

On inspecting the read_json function:
```
import inspect
inspect.signature(dd.read_json)
```
Output: 
```
<Signature (url_path, orient='records', lines=None, storage_options=None, blocksize=None, sample=1048576, encoding='utf-8', errors='strict', compression='infer', **kwargs)>
```

In the docs at https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_json , it does mention `meta` as a keyword argument. However, on inspecting the traceback, the argument is directly being passed onto pandas' `read_json`. 

I really want to use meta as my line delimited json files are not fully homogeneous, and I need just one column, which is guaranteed to be there in all lines. How do I achieve this?

Thanks a lot.

**Comment by mrocklin** [comment]
Added in https://github.com/dask/dask/pull/4588 , not yet released.  You
may want to read docs.dask.org/en/stable instead

**Comment by YashSinha1996** [comment]
Okay, thanks makes a lot of sense.
