### ISSUE TITLE
Issue in setting partition size in Dask dataframe while reading from DB

### ISSUE THREAD

**Issue by lijose** [dask/dask#4775]
I am trying to read from table and set the size of each chunk to 256MB without specifying divisions and partition. But when I checking the size of each partition it is less than 60 MB

Minimal complete code for stimulating issue:
Generate Data:
```

import string
import sqlite3

from itertools import permutations
def create_table(cur):    
    query = '''create table sample(id int, name text)'''
    cur.execute(query)
c = 1
def get_chunk(n, chunk_size):
    chunk = []
    global c
    for d in permutations(string.ascii_uppercase, n):
        t = c , ''.join(d)
        chunk.append(t)
        c += 1
        if len(chunk) >= chunk_size:
            yield chunk
            chunk = []
    return chunk

def insert_data(cursor, n, chunk_size): 
    for chunk in get_chunk(n, chunk_size):
        cur.executemany('insert into sample values (?, ?)', chunk)
conn = sqlite3.connect('test.db')
cur = conn.cursor()
create_table(cur)
conn.commit()
insert_data(cur, 6, 1000)
conn.commit()
```

For Data processing 
```

import dask.dataframe as dd
df = dd.read_sql_table('sample', 'sqlite:////path/to/test.db', 'id', bytes_per_chunk=268435456)
def fun(df):
    print(df.name.count())
    print(df.info())
df.map_partitions(fun).compute()
```

**Comment by jcrist** [comment]
Thanks @lijose for the excellent reproducible issue. ccing @martindurant who may be able to provide some insight here.

**Comment by martindurant** [comment]
Repeat of https://stackoverflow.com/questions/55983095/issue-in-setting-partition-size-in-dask-dataframe-while-reading-from-db

**Comment by lijose** [comment]
Above minimal code is not returning correct size of dataframe (apologies) . Needs to use below one

```
def fun(df):
    print(f'Size: {round(df.memory_usage(deep=True, index=True).sum() / 2 ** 20, 2) }') 
```

**But** code is working fine when the head_rows is not passed as parameter while creating dataframe. If the value of head_rows != 5 then the bytes_per_row is not correct 
**File : dask/dask/dataframe/io/sql.py
Line:  127**
Current code : ` bytes_per_row = (head.memory_usage(deep=True, index=True)).sum() / 5`

I think it should be : `bytes_per_row = (head.memory_usage(deep=True, index=True)).sum() / head_rows`

**Comment by martindurant** [comment]
I suspect you are correct. Would you like to submit a PR with this fix? Ideally, there would be a test which shows that changing the head_rows does not change the number of rows per partition (much).

**Comment by lijose** [comment]
ok. will submit PR
