### ISSUE TITLE
Task stealing

### ISSUE THREAD

**Issue by avnovikov** [dask/dask#4776]
I'm runing into task-stealing and workers killings on Linux machines withing dask.
The code is the following:

```
future_pe = []
future_pe.extend(ddf.groupby('imo_grouper').apply(lambda x: client.submit(generate_port_events_map, x,
                                                                                      retries=250000)))
pe = client.gather(future_pe)
```

The errors (with faulthandler) are the following:

```
distributed.scheduler - INFO - Unexpected worker completed task, likely due to work stealing.  Expected: tcp://127.0.0.1:45441, Got: tcp://127.0.0.1:40243, Key: generate_port_events_map-90420e750dd136a35edc3e0faf840394
distributed.scheduler - INFO - Register tcp://127.0.0.1:40243
distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:40243
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/utils.py", line 654, in log_errors
    yield
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/scheduler.py", line 1281, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:40243
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:40243
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py", line 361, in handle_comm
    result = yield result
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/ec2-user/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/scheduler.py", line 1281, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:40243
```

Setup is Linux (ubuntu and amazon) machines with 

```
# Name                    Version                   Build  Channel
distributed               1.26.1                   py36_0    conda-forge
dask                      1.1.5                      py_0    conda-forge
dask-core                 1.1.5                      py_0    conda-forge
```

Tasks run from 30 to 180 seconds, **retries** option in the client.submit seems not to work (as the process dies earlier than 250 thousand errors.

Is there any way to further diagnose and change this behaviour?

**Comment by jcrist** [comment]
cc @mrocklin - do you have any insights in this? I haven't seen the `ValueError: Worker already exists ...` error before, but it also showed up in #4769.

**Comment by mrocklin** [comment]
I don't have a strong understanding of what's going on here.  It's a bit
odd to see dask dataframe and futures combined in that way.  I think it
would be useful to get a minimal reproducible example here.

**Comment by avnovikov** [comment]
Matthew @mrocklin  - the dataframe is a regular pandas dataframe, this approach is caused by the #4700 (or how to waste 500Gb of memory). The question is how to trace this problem further?

I **constantly** run in the problems with dask including KilledWorkers when moving code from development (macos) to the test - production (linux) environments.

**Comment by TomAugspurger** [comment]
@avnovikov I think we're a bit blocked by a minimal example here. Have you been able to construct one? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be helpful.

You say that `ddf` is a regular pandas Dataframe? (A bit confusing since we usual use `ddf` for a Dask Dataframe). Shot in the dark, but pandas DataFrame.apply will call the function multiple times for the first group, to infer the output shape. Could that be causing issues?

**Comment by avnovikov** [comment]
> @avnovikov I think we're a bit blocked by a minimal example here. Have you been able to construct one? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be helpful.
I'll try to construct a minimal example, however, it may be quite difficult as the function is rather complex. 
> You say that `ddf` is a regular pandas Dataframe? (A bit confusing since we usual use `ddf` for a Dask Dataframe). 

Yes, dask dataframe is not working, due to inability to construct the computational graph.

**Comment by TomAugspurger** [comment]
> however, it may be quite difficult as the function is rather complex.

It's hare to say for sure, but it seems like the function being applied in the groupby shouldn't matter much.

**Comment by mrocklin** [comment]
Closing due to lack of response.  @avlahop if you're able to come up with a minimal reproducible example please response here and we'll reopen.

**Comment by avlahop** [comment]
@mrocklin I think you ment @avnovikov. :smile:
