### ISSUE TITLE
DOC: Impossible sequence of commands

### ISSUE THREAD

**Issue by michaelaye** [dask/dask#4779]
On here:

http://docs.dask.org/en/latest/setup/single-distributed.html

in the examples section, there's the following set of commands:

<img width="688" alt="Screenshot 2019-05-06 14 58 51" src="https://user-images.githubusercontent.com/69774/57254896-b2513e80-700f-11e9-96e5-953aa391a107.png">

The last command is not possible, because the `Client()` object does not have a method called `start_worker`.
The `LocalCluster()` object `c` which was overwritten by doing `c = Client()` does have this method, but the `Client()` object has `start_ipython_workers`?

As I'm just beginning with `dask`, I don't know which one was meant to be used. Or do both work?

Using version 1.2 on macOS 10.12.3

**Comment by martindurant** [comment]
Agreed that it would make sense to be more explicit, and call the variables `client` and `cluster`, to remove the ambiguity. Elsewhere, `c` is normally the client, so it could be only the cluster variable that gets changed.

If you would like to fix this yourself, the file of concern is this: https://github.com/dask/dask/blob/master/docs/source/setup/single-distributed.rst

**Comment by martindurant** [comment]
Sorry, here is the right location: https://github.com/dask/distributed/blob/master/distributed/deploy/local.py#L85

**Comment by michaelaye** [comment]
So, the example meant to use cluster then, correct? So only a minimal change like this would do:

`cluster = LocalCluster()`

?

**Comment by martindurant** [comment]
yes, but you would need to refer to `cluster` again on the next line (where we just get the repr) and start/stop worker lines.

**Comment by michaelaye** [comment]
Added dask/distributed#2664
