### ISSUE TITLE
trivial improvement of dask's local.py documentation

### ISSUE THREAD

**Issue by GTimothee** [dask/dask#4785]
Hi everyone, 
I just wanted to be sure that there is no documentation error in the "local.py" file. 
It is written line 333 that : "We hope that this first-in-first-out policy reduces memory footprint"
However, everywhere else it is written that Dask is using a LIFO policy. Is it just a mistake or is it FIFO in this file ? 
Excuse me in advance if it is a misunderstanding from me. 
Regards,
Tim

**Comment by martindurant** [comment]
> everywhere else it is written that Dask is using a LIFO policy

such as where?

**Comment by GTimothee** [comment]
"After several other policies we find that the policy of last in, first out is surprisingly effective." in the paper of Dask Array for example

**Comment by martindurant** [comment]
Would appreciate a link to this.

One thing to keep in mind when considering scheduling policies, is that the graph describe dependencies: later tasks often depend on former ones and simply cannot be scheduled before them.

**Comment by GTimothee** [comment]
Sure,

"To keep the memory footprint small, we choose to keep ready-to-run tasks in a last-in-first-out stack such that the most recently made available tasks get priority." https://docs.dask.org/en/latest/shared.html?highlight=last%20in%20first%20out

At this stage we choose the policy of “last in, first out.” That is we choose the task that was most recently made available, quite possibly by the worker that just returned to us.  https://docs.dask.org/en/latest/scheduling-policy.html?highlight=last%20in%20first%20out

"After several other policies we find that the policy of last in, first out is surprisingly effective." https://conference.scipy.org/proceedings/scipy2015/pdfs/matthew_rocklin.pdf

Yes sure, I just found it confusing to speak about a FIFO policy because of the above links stating that Dask policy is LIFO.

**Comment by martindurant** [comment]
I think the right reference is https://distributed.dask.org/en/latest/scheduling-policies.html#first-come-first-served-coarsely - there is a difference between what is done at the fine grained level within the workers and threaded scheduler (LIFO) and what happens to tasks as they come in from clients (FIFO). 

I see that in fact I have been confused too - there is more than one local.py! The one you are referring to is `dask.local` as opposed to `distributed.deploy.local`. I think in the former location you are right, the working is the wrong way around.

**Comment by GTimothee** [comment]
So in dask.local it is not a mistake, it is using FIFO, right ?

**Comment by martindurant** [comment]
Excuse me if I'm not being clear :)

I believe the text is wrong and should be LIFO ( cc @mrocklin , to be certain)

**Comment by mrocklin** [comment]
Dask task scheduling is a bit more complex than LIFO vs FIFO, but yes, LIFO
is more correct and a good first approximation.

**Comment by GTimothee** [comment]
OK thank you very much for your help :) !
