### ISSUE TITLE
IndexError when doing compute() on a filtered Dask Array

### ISSUE THREAD

**Issue by markojurkovic** [dask/dask#4790]
I have a Dask `Array` (one-dimensional) called `feat_arr` which holds values of some feature (`float64` values). It gets created by filtering out a column of a Dask `DataFrame` called `feature_dataframe`. I also have a (one-dimensonal) NumPy `ndarray` called `scores_` which is the same size as `feat_arr`. I use that array to filter out values from `feat_arr`, like so:

    feat_arr = feature_dataframe[feat].values
    (...)
    outs = feat_arr[scores_ > OUTLIER_THRESHOLD_LOCAL],

where `OUTLIER_THRESHOLD_LOCAL` is a constant `float` value.

Now if I call `outs.compute()`, I get the following error, as indicated in the title:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-37-7c64832810f5> in <module>
----> 1 outs.compute()

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\dask\base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2566                     should_rejoin = False
   2567             try:
-> 2568                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2569             finally:
   2570                 for f in futures.values():

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1820                 direct=direct,
   1821                 local_worker=local_worker,
-> 1822                 asynchronous=asynchronous,
   1823             )
   1824 

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\client.py in sync(self, func, *args, **kwargs)
    751             return future
    752         else:
--> 753             return sync(self.loop, func, *args, **kwargs)
    754 
    755     def __repr__(self):

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\utils.py in sync(loop, func, *args, **kwargs)
    329             e.wait(10)
    330     if error[0]:
--> 331         six.reraise(*error[0])
    332     else:
    333         return result[0]

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\utils.py in f()
    314             if timeout is not None:
    315                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 316             result[0] = yield future
    317         except Exception as exc:
    318             error[0] = sys.exc_info()

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py in run(self)
    734                     if exc_info is not None:
    735                         try:
--> 736                             yielded = self.gen.throw(*exc_info)  # type: ignore
    737                         finally:
    738                             # Break up a reference to itself

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\distributed\client.py in _gather(self, futures, errors, direct, local_worker)
   1651                             six.reraise(CancelledError, CancelledError(key), None)
   1652                         else:
-> 1653                             six.reraise(type(exception), exception, traceback)
   1654                     if errors == "skip":
   1655                         bad_keys.add(key)

c:\users\ejrmaru\appdata\local\programs\python\python36\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

IndexError: index 1661 is out of bounds for axis 0 with size 1655
```

Why is this exception getting raised? I'm using the latest version of Dask, 1.2.2, and my code is running in a Jupyter Notebook using Python 3.6.

If the error cannot be avoided in this case for some reason, is there a workaround that could be used?

**Comment by martindurant** [comment]
Can you please provide more details or otherwise try to narrow down your problem, in a way that we can replicate and thus help solve? The following, seemingly similar situation works fine:
```
x = np.random.randn(100)
d = da.from_array(x, chunks=10)
d[x > 0].compute()
```
(produces the expected array of about 50 elements, with only positive values)

**Comment by markojurkovic** [comment]
> Can you please provide more details or otherwise try to narrow down your problem, in a way that we can replicate and thus help solve? The following, seemingly similar situation works fine:
> 
> ```
> x = np.random.randn(100)
> d = da.from_array(x, chunks=10)
> d[x > 0].compute()
> ```
> 
> (produces the expected array of about 50 elements, with only positive values)

I really don't know what additional details to provide, since the two lines of code and the description in the original post are really all there is to the lifecycles of those variables. Is there anything specific that you would like me to provide? Could it be that your examples works because you use the `from_array` method and specify the number of chunks explicitly?

**Comment by jrbourbeau** [comment]
@markojurkovic you could try using the Dask DataFrame [`to_dask_array()` method](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.to_dask_array) to convert your Dask Series to a Dask array with known chunk sizes. For example, something like:

```python
import dask.dataframe as dd
import numpy as np

# Create Dask DataFrame of random data
data = np.random.randn(100, 2)
ddf = dd.from_array(data, chunksize=30, columns=['col1', 'col2'])

# Generate an array to filter on
x = np.random.randn(100)

# Convert Dask Series to a Dask Array
# Specifying lengths=True to compute array chunk sizes
d = ddf['col1'].to_dask_array(lengths=True)

# Perform filtering
result = d[x > 0].compute()
print(f'result = {result}')
```

Note that specifying `lengths=True` in `to_dask_array()` will trigger an immediate computation of the Dask array chunk sizes.

**Comment by jrbourbeau** [comment]
Just checking in here, @markojurkovic does using `.to_dask_array(lengths=True)` instead of `.values` avoid the raised `IndexError`? Is it safe to close this issue?

**Comment by markojurkovic** [comment]
@jrbourbeau OK, now the IndexError doesn't get raised, but why the piece of code @martindurant wrote in the first reply works, and mine doesn't stil isn't clear.

**Comment by TomAugspurger** [comment]
@markojurkovic are you able to provide a [minimal example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) reproducing the first issue? That may help us (or you) understand the difference between your code & @martindurant's.

**Comment by jrbourbeau** [comment]
> now the IndexError doesn't get raised

Glad to hear it!

> why the piece of code @martindurant wrote in the first reply works, and mine doesn't still isn't clear

Not all operations (e.g. slicing) are supported for dask arrays with unknown chunk sizes (see http://docs.dask.org/en/latest/array-creation.html#from-dask-dataframe). The `.values` attribute on a dask series returns a dask array with unknown chunk sizes, while in @martindurant's example the dask array has known chunk sizes. My guess is that's what's causing your original issue. Echoing @TomAugspurger's comment, a minimal example could help us better understand the situation.

**Comment by jrbourbeau** [comment]
Closing this issue as I think the originally posted issue has been resolved. @markojurkovic feel free to re-open if this is not the case
