### ISSUE TITLE
Add registration accessors for 3rd-party libraries

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#4801]
Pandas provides an API 3rd parties to register accessors: http://pandas.pydata.org/pandas-docs/stable/development/extending.html#registering-custom-accessors.

For example, cyberpandas provides the [`.ip` series accessor](https://cyberpandas.readthedocs.io/en/latest/usage.html#ip-accessor). For cyberpandas to work well with dask.dataframe, it should also register an accessor with Dask.

We should provide

1. Similar APIs for registering accessors with dask's Series, Index, and DataFrame
2. Documentation on how to write accessors (optional dependency on dask, basics like map_partitions for elementwise operations)

**Comment by achapkowski** [comment]
@TomAugspurger is there a demo/example of creating dask accessors?

**Comment by TomAugspurger** [comment]
Probably in cyberpandas, if you want it'd be good to have a PR with docs.

**Comment by achapkowski** [comment]
@TomAugspurger  cyberpandas is a great project covering Pandas' accessor.  I am trying to figure out best practices for working/accessing the Array data behind the DataFrame?  Should I use `map_partition`, etc...   My accessor is taking data from `Pandas`, which has a custom accessor/array.  

I registered the Dtype with Dask, and I need to access the underlying functions defined on the custom array class.

**Comment by TomAugspurger** [comment]
Dask doesn't have the equivalent of `.array` on its Series. So you could
only access that through map_partitions right now. We have an open issue
about it.

**Comment by achapkowski** [comment]
@TomAugspurger thank you for the clarification.  I was using the `map_partition` but I wanted to ensure I was doing it the best way possible.  Appreciate the help!
