### ISSUE TITLE
Error Python/Dask worker/scheduler

### ISSUE THREAD

**Issue by josivalmarques** [dask/dask#4812]
Hello everyone, I am using in my local network the 3 computers, being 2 for 'worker' and 1 computer the 'schedule', configuring the 'client' in python when executing the command:

###################
from dask.distributed import Client

client = Client ('My ip address: 8786')
###################

And the result is:

TypeError: descriptor 'tls_worker_cert' for 'Security' objects does not apply to 'Security' object

Has anyone ever experienced this?

I am using a python 3.7.3 and dask 1.2.2

Thank you for your help!

**Comment by TomAugspurger** [comment]
Can you give a full traceback? What version of distributed, and are there any logs on the scheduler / worker?

What protocol are you passing to Client? `tcp`? (no protocol defaults to tcp) or tls?

**Comment by josivalmarques** [comment]
Hi Tom, tks for ur help, 

*Can you give a full traceback
How i can see full traceback?

*What version of distributed
1.27.0, latest

*any logs on the scheduler / worker?
I just have 2 files in a dask folder, purge.lock and global.lock, both empty

What protocol are you passing to Client?
TCP
![image_dask](https://user-images.githubusercontent.com/7399450/57942232-4f7d6400-78a7-11e9-985e-4a4ef957b491.png)

Tks

**Comment by TomAugspurger** [comment]
The console with the client should have a longer traceback.

How'd you start the scheduler & workers?

**Comment by josivalmarques** [comment]
*The console with the client should have a longer traceback.


*How'd you start the scheduler & workers?
Using Anaconda Prompt Console.
http://distributed.dask.org/en/latest/setup.html, page "Setup Network"

Print of Anaconda command worker:
![anaconda prompt](https://user-images.githubusercontent.com/7399450/57951973-24543e00-78c2-11e9-878c-9adfba6ba99b.png)

Print of Dask directory:
![dask-rodcelo](https://user-images.githubusercontent.com/7399450/57952013-451c9380-78c2-11e9-990f-56fa6c511630.png)

Print of Anaconda command scheduler:
![dask - scheduler](https://user-images.githubusercontent.com/7399450/57952175-c1af7200-78c2-11e9-9e52-e713b9756fc5.png)

Tks

**Comment by TomAugspurger** [comment]
> *The console with the client should have a longer traceback.

Were you able to get this traceback?

Can you also try setting the log level to debug in case that has more information? https://distributed.dask.org/en/latest/configuration.html#user-wide-configuration (change the logging.distributed value from `info` to `debug`

**Comment by TomAugspurger** [comment]
Let us know if you can provide that info. This doesn't *seem* to be an issue with dask / distributed though.
