### ISSUE TITLE
Retire duplicate documentation in distributed.dask.org

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4813]
We have a lot of information about setup and installation at distributed.dask.org that is now pretty well covered at dask.org.  We should probably go through and remove pages for which we have analogs.  We should probably also add redirects (there is some code for this in `docs/source/conf.py`

**Comment by TomAugspurger** [comment]
Setup is now pointing at the dask docs.

Install (https://distributed.dask.org/en/latest/install.html) can probably be updated to point to the Dask as well.

**Comment by ncclementi** [comment]
@TomAugspurger would you say this has been resolved, it looks like it to me but I might be missing something. If so, should we close the issue?

**Comment by TomAugspurger** [comment]
Yep I think so too.
