### ISSUE TITLE
[FEA] Remove pandas dependencies from rolling functionality

### ISSUE THREAD

**Issue by beckernick** [dask/dask#4817]
Removing the pandas dependencies in the [rolling windows](https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py) implementation will help allow us to use other backend dataframe libraries such as cuDF for distributed rolling windows (cuDF rolling functionality is currently a work in progress).

As of May 17, 2019, the following lines of code have explicit pandas dependencies on what appear to be meaningful chunks of data based on the code:

- [concatenation](https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py#L32) of the partitions (in `overlap_chunks`)
- [getting the deltas](https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py#L108) of the dataframe divisions when the rolling window is operating on datetimes (in `map_overlap`) (two places due to branching logic). This may not be that meaningful of a bottleneck, as the number of divisions is `npartitions + 1`. It looks to me on a first pass through that there isn't concatenation of the results to any other objects so this might not block cuDF.
- [concatenation](https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py#L197) again for rolling windows with timedeltas (in `tail_timedelta`).
- [converting the timedelta window string ('5S', for example) into an actual timedelta object](https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py#L265) in the actual Rolling class implementation (in `_call_method`). This would not matter much if the cuDF implementation can accept pandas timedeltas as arguments, but will matter if it cannot.

**Comment by mrocklin** [comment]
Nice analysis @beckernick !  My thoughts (which in many cases agree with yours)

https://github.com/dask/dask/blob/081a911148d472bb1a82a88a19f18e5c19d5f137/dask/dataframe/rolling.py#L108

This might be ok to keep we're only manipulating the divisions here, not the actual data.  It's probably fine to keep this in Pandas regardless of how we store the data

https://github.com/dask/dask/blob/081a911148d472bb1a82a88a19f18e5c19d5f137/dask/dataframe/rolling.py#L197
https://github.com/dask/dask/blob/081a911148d472bb1a82a88a19f18e5c19d5f137/dask/dataframe/rolling.py#L32

We should use the general concat function that we use elsewhere throughout the dask dataframe codebase 

https://github.com/dask/dask/blob/081a911148d472bb1a82a88a19f18e5c19d5f137/dask/dataframe/rolling.py#L265

This is probably ok to keep as well.  This is just a scalar value

**Comment by beckernick** [comment]
@mrocklin I generally agree with what you've suggested. The unknown for me on your last one is that `before` is ultimately used for some operations as a timedelta, which might pose some interoperability concerns if cuDF can't handle that conversion.

**Comment by mrocklin** [comment]
I think that ideally cudf would be able to reason about Pandas and Python timedelta objects.  They're likely to come up in normal workflows.  If this isn't the case today then I think it's a reasonable request and that we should raise an issue on the cudf issue tracker.

**Comment by beckernick** [comment]
Will verify.

**Comment by jsignell** [comment]
Seems like the concats mentioned above have been changed to not depend on pandas, so this issue might be resolved. I am closing, but please reopen if there is still work to be done.
