### ISSUE TITLE
Add documentation for dataframe reshape methods

### ISSUE THREAD

**Issue by tpanza** [dask/dask#4825]
The methods implemented in [dataframe/reshape.py](https://github.com/dask/dask/blob/master/dask/dataframe/reshape.py) are not documented on the https://docs.dask.org site. Please add documentation, ideally with some examples and best practices for the 3 currently existing reshape methods:

* [get_dummies](https://github.com/dask/dask/blob/master/dask/dataframe/reshape.py#L19)
* [pivot_table](https://github.com/dask/dask/blob/master/dask/dataframe/reshape.py#L165)
* [melt](https://github.com/dask/dask/blob/master/dask/dataframe/reshape.py#L239)

**Comment by TomAugspurger** [comment]
Thanks @tpanza, are you interested in working on this? I think adding to the "Other functions" section in https://github.com/dask/dask/blob/master/docs/source/dataframe-api.rst is appropriate.

**Comment by tpanza** [comment]
Yeah I'll try to get something together, using the pointers above

**Comment by mrocklin** [comment]
Checking in here.  Any progress @tpanza ?  No pressure of course (none of us can set expectations for the others) but I thought I'd ask.

**Comment by tpanza** [comment]
Hi @mrocklin , please see PR #4896
