### ISSUE TITLE
Broadcasting Issues at Edge of Array

### ISSUE THREAD

**Issue by jlevy44** [dask/dask#4826]
Awesome stuff. I'll running an analysis where I have a large dask array, dimensions (133000, 55000, 3) , chunk size 1000. When I try to load the end of the array: arr[131000:133000,54000:54800].compute() , the command breaks: ValueError: could not broadcast input array from shape (729,720,3) into shape (729,800,3)

And this seems to only happen across the axis 1. Can you please help me debug this issue?

The only other thing I can think of is that the array, without using dask, should be (133000, 54750, 3), the 54750, being less than the size of the axis 1 is concerning to me. What are your thoughts?

**Comment by jlevy44** [comment]
It works if I trim this array down.

**Comment by jlevy44** [comment]
Is there any option I can specify to read off the ending chunks values as zeros if the true array doesn’t quite reach that far?

**Comment by TomAugspurger** [comment]
@jlevy44 if you can provide a [minimal example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) it'd be easier to see where things are going wrong.

**Comment by mrocklin** [comment]
Closing this due to lack of response.  @jlevy44 if you're able to provide a small minimal reproducible example then please respond here and we'll reopen this.
