### ISSUE TITLE
divmod doesn't work on Dask Arrays

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4832]
Currently [`divmod`]( https://docs.python.org/3/library/functions.html#divmod ) doesn't work on Dask Arrays. This should just be a matter of defining [`__divmod__`]( https://docs.python.org/3/reference/datamodel.html#object.__divmod__ ) and [`__rdivmod__`]( https://docs.python.org/3/reference/datamodel.html#object.__rdivmod__ ) for Dask Array objects, which can be defined in terms of the integer division and modulus as shown in the Python docs.

```python
In [1]: import dask.array as da                                                 

In [2]: a = da.random.randint(0, 10, (4, 6), chunks=(2, 3))                     

In [3]: divmod(a, 2)                                                            
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-2db1b3c1558a> in <module>
----> 1 divmod(a, 2)

TypeError: unsupported operand type(s) for divmod(): 'Array' and 'int'
```

**Comment by Sriharsha-hatwar** [comment]
Hi so basically it should return two elements which are themselves an array, one is with the quotients and one is with the remainders right? 

I will take this up if that's the case :)

**Comment by jakirkham** [comment]
Yep, that is the idea. Please feel free to. Would be happy to review a PR.

**Comment by jakirkham** [comment]
Solved with PR ( https://github.com/dask/dask/pull/4884 ).
