### ISSUE TITLE
dask.bag unexpected KilledWorker when module cannot be imported

### ISSUE THREAD

**Issue by apatlpo** [dask/dask#4839]
I run into misleading error messages and thought it might be worth putting the information into an issue.

In a notebook, I import methods found in a local library (`from mylib import *`) and distribute calls to these methods.

If the distribution is performed with `client.submit, I get an informative message error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-4109487e10e2> in <module>
----> 1 client.submit(mylib.add_one, 2).result()
...
ModuleNotFoundError: No module named 'mylib'
```

If however I use a dask bag the worker is killed:
```
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
...
KilledWorker: ("('from_sequence-add_one-22f1b59fbc6f70c09085e9d83741f3d1', 9)", <Worker 'tcp://128.93.84.85:60693', memory: 0, processing: 10>)
```
calls was: `db.from_sequence(range(10)).map(mylib.add_one).compute()`

I would have expected an import error as in the `client.submit` distribution.

It seems pretty critical that workers and scheduler are not created in the work directory where the library file lives.
This happened to me on an HPC cluster.

cc @lesteve, @jacobtomlinson

**Comment by martindurant** [comment]
Would appreciate any logging output from the workers before going down, if possible.

**Comment by mrocklin** [comment]
You're correct that missing modules shouldn't cause killed workers.  I'm
surprised to see that occur.  If you have time to generate a reproducible
example that would be helpful.

**Comment by lesteve** [comment]
Something like this should reproduce:
```py
import os
import subprocess

from dask.distributed import Client, LocalCluster
import dask.bag as db

cluster = LocalCluster(n_workers=0)
client = Client(cluster)

open('local_module.py', 'w').write('def add_one(x): return x + 1')
import local_module

os.chdir('/tmp')
subprocess.Popen(['dask-worker', client.scheduler.address])

try:
    client.submit(local_module.add_one, 1).result()
except ImportError:
    print('ImportError as expected when using client.submit')

# KilledWorker when using dask.bag.map
db.from_sequence(range(5)).map(local_module.add_one).compute()
```

**Comment by mrocklin** [comment]
Hrm, indeed, reproduced.  Thanks @lesteve !

**Comment by jakirkham** [comment]
Any thoughts on next steps here, @mrocklin?

**Comment by mrocklin** [comment]
Not a ton, no.  The thing to do here is to figure out where we're deserializing this bit of data, and figure out how to make the system robust to that bit of code failing.  Clearly we've done this clearly for other cases.  I don't have any particular thoughts on why this might differ.  Someone would have to investigate further.  As a disclaimer, that person is unlikely to be me any time in the next month or two.

**Comment by jsignell** [comment]
I no longer am able to reproduce the issue. Perhaps it has been solved! I am going to close, but please reopen if you are still experiencing this.

**Comment by lesteve** [comment]
Thanks a lot for looking into this.

This is slightly weird I can still reproduce the problem with the latest `dask` and `distributed` release (I get a `KilledWorker` exception rather than a nice print statement saying that the `ImportError` has been caught) with my snippet from https://github.com/dask/dask/issues/4839#issuecomment-495644136.

```
$ conda list | grep -P 'distributed|dask'
dask                      2.15.0                     py_0    conda-forge
dask-core                 2.15.0                     py_0    conda-forge
distributed               2.15.1           py38h32f6830_0    conda-forge
```

I tried with `dask` and `distributed` from master and I don't get an error but I don't get the expected behaviour either in particular I don't get this `print` (I have no idea why ...):
```py
try:
    client.submit(local_module.add_one, 1).result()
except ImportError:
    print('ImportError as expected when using client.submit')
```

So I suspect the underlying problem is still there but the snippet does not reproduce the problem for some weird reason ...

I think this problem is very edge-casy though so leaving it closed is completely fine.

**Comment by jsignell** [comment]
Ok, I didn't get the expected `ImportError` either. I'm wondering if perhaps the imports are being handled differently now.
