### ISSUE TITLE
Dask Array's constant pad coerces array to NumPy ndarray

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4842]
Currently Dask Array's pad (when using the `constant` mode) may end up coercing array data of a different array type to a NumPy `ndarray`. For example, the following code will result in a NumPy `ndarray`.

```python
a_gpu_pad = da.pad(a_gpu, 1, "constant")
a_gpu_pad.compute() 
```

This still happens if we try to set the `constant_values` differently. If we provide a 0-D array, we run into issue ( https://github.com/dask/dask/issues/4841 ).

**Comment by jakirkham** [comment]
@pentschev, do you have any thoughts on how best to handle this or issue ( https://github.com/dask/dask/issues/4841 )?

**Comment by pentschev** [comment]
Seems like they should be treated as part of #4543, I'll check this and #4841 next.

**Comment by jakirkham** [comment]
Thanks Peter!

**Comment by mrocklin** [comment]
Is this resolved by the _meta PR?

**Comment by pentschev** [comment]
No, unfortunately `da.pad` relies on `da.asarray`, which in turn relies on `np.asarray`. We've started a discussion on how to deal with those cases in #4883.

If this particular case (constant padding) is needed immediately, I think we could use `*_like` functions instead, but to solve `pad` more generally we will require to deal with the cases I mentioned above.

**Comment by jakirkham** [comment]
The one downside of using `_like` is it creates a dependency on the data in the array. That said, if this is as close as we can get to the right behavior here, this seems like the best way to resolve this issue.

**Comment by brendancol** [comment]
@mrocklin @jakirkham just wanted to ping this issue to get help promote.  Any tips on solving the coercion issue for cupy arrays in the `cupy_backed_array.map_overlap(..., boundary=0.)` case?

**Comment by pentschev** [comment]
> @mrocklin @jakirkham just wanted to ping this issue to get help promote it.
> 
> Any tips on solving the coercion issue for cupy arrays in the `cupy_backed_array.map_overlap(..., boundary=0.)` case?

The original issue here with `da.pad` is going to be resolved by https://github.com/dask/dask/pull/6738. However, your issue with `map_overlap` (that internally relies on `map_blocks`) is probably solved by passing `meta=`, please see https://github.com/dask/dask/blob/8d622ad81162245d5e7663522b9721df5b23e9f4/dask/array/core.py#L486-L495
