### ISSUE TITLE
Dask client not running on Colab

### ISSUE THREAD

**Issue by cornhundred** [dask/dask#4843]
Dask client is not running on Colab. My code is: 

```
from dask.distributed import Client, progress
client = Client()
client
```

and the error is:

```
/usr/local/lib/python3.6/dist-packages/distributed/bokeh/core.py:57: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/usr/local/lib/python3.6/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/dist-packages/distributed/deploy/local.py", line 229, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.gen.TimeoutError: Worker failed to start
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tornado/gen.py in callback(f)
    827                 try:
--> 828                     result_list.append(f.result())
    829                 except Exception as e:

33 frames
TimeoutError: Worker failed to start

During handling of the above exception, another exception occurred:

TimeoutError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/distributed/deploy/local.py in _start_worker(self, death_timeout, **kwargs)
    227         if w.status == 'closed' and self.scheduler.status == 'running':
    228             self.workers.remove(w)
--> 229             raise gen.TimeoutError("Worker failed to start")
    230 
    231         raise gen.Return(w)

TimeoutError: Worker failed to start
```

To reproduce the error please see the following Colab gist:

https://colab.research.google.com/gist/cornhundred/70524e9425db14f3adec9e86660aa313/trying_dask_on_colab.ipynb

**Comment by TomAugspurger** [comment]
Are you in contact with anyone from colab about this?

**Comment by cornhundred** [comment]
Not yet, but I'll raise the issue with Colab.

**Comment by mrocklin** [comment]
My guess is that they don't allow users to start processes.  You might try the following for now:

```python
client = Client(processes=False)
```

Though there are performance implications of this, particularly when using GIL-bound computations.

**Comment by jakirkham** [comment]
@cornhundred, have you had a chance to try Matt's suggestion above?

**Comment by cornhundred** [comment]
Hi @jakirkham, yes adding the argument `processes=False` worked - see gist https://colab.research.google.com/gist/cornhundred/1fa599c4cb09cded2a598cc02ca3947b/trying_dask_on_colab_no_processes.ipynb

However, I have to read the documentation more to understand the consequences of not using proceses. Also, the Dashboard link is not working.

**Comment by jakirkham** [comment]
Glad to hear that worked.

Could you please raise another Colab issue about the Dashboard being inaccessible?

**Comment by jakirkham** [comment]
After talking with a colleague about the dashboard issue, they recommended using `ngrok`. This [SO answer]( https://stackoverflow.com/a/48468512/3877089 ) may also be useful for setting it up.

Would also be curious if `jupyter-server-proxy` works here. If not, it might be worth [raising an issue on `jupyter-server-proxy`'s tracker]( https://github.com/jupyterhub/jupyter-server-proxy ) with whatever outcome is seen.

**Comment by randerzander** [comment]
@cornhundred I suspect the dashboard being inaccessible is because printing the client info in Colab gives you a localhost address: 
```
Dashboard: http://localhost:8787/status |  
```

I've dug around for ways to expose it, and the simplest I've seen is using ngrok like so:
```
# expose Dask's status dashboard to a public URL
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

get_ipython().system_raw('./ngrok http 8787 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"
```

That should print a link which you can click and get the Dask Status Dashboard for your Colab instance.

**Comment by jakirkham** [comment]
@cornhundred, does this info help?

**Comment by cornhundred** [comment]
Hi @jakirkham, I made a gist with the changes suggested by @randerzander (https://colab.research.google.com/gist/cornhundred/7b6f535d279cc2005a13f6a6e21e00bd/trying_dask_on_colab_no_processes.ipynb#scrollTo=rQuhrN9ZxXLj), but I'm getting a "Web Page Blocked" error. 

`Access to the web page you were trying to visit has been blocked in accordance with company policy. Please contact the helpdesk x4HELP if you believe this is in error.`

It sounds like this might be an issue with my work internet connection. I haven't tried this from my home computer yet.

**Comment by jakirkham** [comment]
Did you have a chance to try on your home computer? Am curious to know if it worked there.

**Comment by cornhundred** [comment]
Hi @jakirkham, yes the link worked when I ran the notebook off my cellphone's WiFi hotspot.

**Comment by mrocklin** [comment]
Is there anything left to do here, or can this be closed?

**Comment by cornhundred** [comment]
@mrocklin, I think it's resolved. 

However, Colab does not appear to support processes (but this is a Colab issue).

**Comment by Nithanaroy** [comment]
> Hi @jakirkham and @mrocklin, yes adding the argument `processes=False` worked - see gist https://colab.research.google.com/gist/cornhundred/1fa599c4cb09cded2a598cc02ca3947b/trying_dask_on_colab_no_processes.ipynb
> 
> However, I have to read the documentation more to understand the consequences of not using proceses. Also, the Dashboard link is not working.

I get 
```
/usr/local/lib/python3.6/dist-packages/distributed/bokeh/core.py:57: UserWarning: 
Failed to start diagnostics server on port 8787. [Errno 99] Cannot assign requested address
  warnings.warn('\n' + msg)
/usr/local/lib/python3.6/dist-packages/distributed/deploy/local.py:197: UserWarning: 
Could not launch service 'bokeh' on port 8787. Got the following message:

[Errno 99] Cannot assign requested address
  self.scheduler.start(scheduler_address)
```
error in Colab now

**Comment by Nithanaroy** [comment]
```
from IPython.display import IFrame
IFrame(src='http://localhost:8787', width=900, height=600)
```
shows the UI though the `client` doesn't start

**Comment by TomAugspurger** [comment]
@Nithanaroy does colab restrict which ports procesess talk over?

**Comment by Nithanaroy** [comment]
That could be reason but I'm not sure. Is it possible to change the default 8787?

**Comment by jakirkham** [comment]
AIUI (reaffirmed by talking to a colleague offline) Colab doesn't support opening any ports. Maybe worth proding issue ( https://github.com/googlecolab/colabtools/issues/569 ) to let people know this is still an issue people are interested in?

So is running `client = Client(processes=False)` not working for you? If not, we might need to check that the dashboard is not setup here or figure out a way for you to disable it.

**Comment by jakirkham** [comment]
Ah sorry have you tried `Client(processes=False, diagnostic_port=None)`?

https://github.com/googlecolab/colabtools/issues/569#issuecomment-578392622

**Comment by randerzander** [comment]
```
from dask.distributed import Client
client = Client(processes=False, diagnostic_port=None)
```

results in:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-78f089029570> in <module>()
      1 from dask.distributed import Client, progress
----> 2 client = Client(processes=False, diagnostic_port=None)
      3 client

14 frames
/usr/lib/python3.6/asyncio/events.py in get_event_loop(self)
    600         if self._local._loop is None:
    601             raise RuntimeError('There is no current event loop in thread %r.'
--> 602                                % threading.current_thread().name)
    603         return self._local._loop
    604 

RuntimeError: There is no current event loop in thread 'IO loop'.
```

**Comment by jakirkham** [comment]
What versions of Dask + Distributed are you using?

**Comment by randerzander** [comment]
Edited my above comment to include versions and try seting both `dashboard_address` and `diagnostic_port`.

**Comment by jakirkham** [comment]
Interesting was not able to reproduce locally. Were you testing on Colab?

**Comment by Nithanaroy** [comment]
> Ah sorry have you tried `Client(processes=False, diagnostic_port=None)`?
> 
> [googlecolab/colabtools#569 (comment)](https://github.com/googlecolab/colabtools/issues/569#issuecomment-578392622)

Thanks @jakirkham for the suggestion. Looks like it is not working on Google Colab with dask 2.15 as well. Created one with public access at https://colab.research.google.com/drive/1-gH4MYXDhj9CVBqjYdwWq12F9NSrTqLr

**Comment by riversdark** [comment]
Any update on this? I'm getting the same error messages on Colab.
