### ISSUE TITLE
Dask dashboard not working on Kaggle

### ISSUE THREAD

**Issue by cornhundred** [dask/dask#4844]
The Dask dashboard is not working on Kaggle. My code is:

```
from dask.distributed import Client, progress
client = Client()
client
```

Clicking the Dashboard link says "This site can’t be reached"

I'm guessing that page (e.g.  http://127.0.0.1:8787/status) is not being served by Kaggle. Is there any way to get any of the dashboard components to be visible in the notebook? Or would we IFrame something into the notebook?

To reproduce the error please see the Kaggle kernel https://www.kaggle.com/cornhundred/trying-dask-on-kaggle?scriptVersionId=14702415

**Comment by TomAugspurger** [comment]
@quasiben is something like https://github.com/dask/distributed/pull/2715 likely to solve this?

**Comment by mrocklin** [comment]
Nope.  That's different. This likely needs to be solved on the Kaggle
side.  They either need to open up another port, or else use something like
nbserverproxy to allow the Jupyter notebook server to proxy through the
dask dashboard.

I recommend raising a feature request with Kaggle.  There isn't much we can
do other than implement tools that can solve this problem.  Kaggle needs to
choose to actively use them.

**Comment by TomAugspurger** [comment]
That’s my suspicion too. I’d recommend reaching out to them and pointing them here if they have questions.

Closing for now since there isn’t any immediate step to take here.

**Comment by cornhundred** [comment]
Thanks I'll raise the issue with Kaggle
