### ISSUE TITLE
AttributeError: module 'dask.array.numpy_compat' has no attribute 'nancumprod'

### ISSUE THREAD

**Issue by letmaik** [dask/dask#4846]
These lines are incorrect:
https://github.com/dask/dask/blob/125e0d7872ffb5374f5b2ccb20cdb79ca4834682/dask/array/chunk.py#L70-L74

The [numpy_compat](https://github.com/dask/dask/blob/master/dask/array/numpy_compat.py) module doesn't define these functions, hence it will fail badly with older numpy versions, like 1.11.

The numpy_compat moduled contained the functions up until dask 1.2.0, with 1.2.1 they vanished.

**Comment by TomAugspurger** [comment]
We recently bumped the minimum numpy version to 1.13. How’d you install dask?

**Comment by letmaik** [comment]
```sh
conda create --name pyenv python=3.6
...
conda install numpy=1.11 dask
```

https://ci.appveyor.com/project/letmaik/rawpy/builds/24820422/job/mcp7o1ajeo9cv3d5#L741

**Comment by TomAugspurger** [comment]
Did dask come from conda forge or defaults?

**Comment by TomAugspurger** [comment]
I see that our dependencies on Conda-forge weren't updated. I'll make a PR updating them.

**Comment by TomAugspurger** [comment]
@letmaik conda-forge should be building corrected packages now.

@jakirkham do you know if the bad packages need to be manually removed? i.e. will `conda install -c conda-forge numpy=1.11 dask=1.2.2` correctly error in the future, or will the solver fall back to the lower build number with the incorrect metadata?

**Comment by letmaik** [comment]
This came from defaults. Just run these commands and you can reproduce it:
```sh
conda create --name dask-test python=3.6 numpy=1.11 dask
conda activate dask-test
python -c "import dask.array"
```

**Comment by TomAugspurger** [comment]
I think the defaults recipe mirrors conda forge. I’ll ping the distro team after the holiday to make sure they pick up build number bumps.

**Comment by jakirkham** [comment]
Thanks @TomAugspurger. I've pulled what I believe to be the broken packages from conda-forge (as noted in your PR), but if you can recheck that would be very helpful.

**Comment by jakirkham** [comment]
Independently it's probably worth dropping these fallbacks as they are not needed. Have submitted PR ( https://github.com/dask/dask/pull/4850 ) to address that.

**Comment by TomAugspurger** [comment]
@jakirkham confirmed for conda-forge

```
$ conda create --name dask-test -c conda-forge python=3.6 numpy=1.11 dask=1.2.2                                                                                                                                                                                                                             643ms  Tue May 28 13:15:54 2019
Collecting package metadata:
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - dask=1.2.2
  - numpy=1.11
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by jakirkham** [comment]
Thanks Tom!

**Comment by grlee77** [comment]
@jakirkham:
I think there are still some builds that may need to be marked as broken. On the following CI run from PyFFTW, I get an install of `dask 1.2.2` with incompatible `numpy 1.11.3`:

https://ci.appveyor.com/project/hgomersall/pyfftw/builds/26051197/job/l5765hlr9342dv25#L152

**Comment by jakirkham** [comment]
@grlee77, if there are conda package issues, let's move those to the conda-forge feedstock.

Also would you be able to identify the ones with incorrect version constraints? That way we can hopefully get these in one pass. 🙂
