### ISSUE TITLE
deprecation warnings messages in Read-from-Parquet documentation

### ISSUE THREAD

**Issue by JoranDox** [dask/dask#4848]
https://examples.dask.org/dataframes/01-data-access.html#Read-from-Parquet

![image](https://user-images.githubusercontent.com/7152733/58401506-59992280-805e-11e9-8fd9-ea2ca1aaaca9.png)

**Comment by martindurant** [comment]
The environment in the repo lists [pyarrow 0.10.0](https://github.com/dask/dask-examples/blob/master/binder/environment.yml#L14), but pandas is not pinned, hence this error. I'll check, but I expect it's completely safe to use pyarrow 0.12 at least.

**Comment by martindurant** [comment]
I can confirm that pyarrow 0.12 works without any warnings. I'll go through the environment and see which of the packages are safe to update across all of the examples.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/dask/dask-examples/pull/73
