### ISSUE TITLE
Use tree reduction in `da.bincount`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4852]
Currently `da.bincount` does a [reduction over `np.bincount`s from each chunk]( https://github.com/dask/dask/blob/2f308e72a46de818055819108429e8f7ce7ba03b/dask/array/routines.py#L549 ). It would be nice to change this to use [a tree reduction]( https://github.com/dask/dask/blob/master/dask/array/reductions.py ) instead.

**Comment by jakirkham** [comment]
This could be a fun task if it is interesting to you, @madsbk. Would provide an opportunity to learn about how reductions work in Dask and how to construct task graphs.

**Comment by mrocklin** [comment]
How important is it to do a tree reduction here?  I understand the value of tree reductions generally, I'm mostly just curious about when this becomes awkward.

**Comment by mrocklin** [comment]
How important is it to do a tree reduction here?  I understand the value of tree reductions generally, I'm mostly just curious about when this becomes awkward.

**Comment by jakirkham** [comment]
Running `bincount` on the AOLLSM m4 dataset now is pretty slow. My hope is this would help speed it up, but I could be wrong about this.

**Comment by jakirkham** [comment]
I’m no longer looking at this. That doesn’t mean it’s not useful to people using `bincount`. Just have different work today.
