### ISSUE TITLE
dropna for columns

### ISSUE THREAD

**Issue by raymondyao** [dask/dask#4858]
Missing dropna(axis='columns) like pandas

**Comment by quasiben** [comment]
Thanks @raymondyao for the suggestion.  Any interest in contributing a PR ?

**Comment by mrocklin** [comment]
Unfortunately we can't do this operation lazily.  This would require us to read through all the data in order to determine the columns of the output.  I think that given this constraint we probably won't implement this any time in the near future.  Closing.
