### ISSUE TITLE
Repartition randomly dropping some rows

### ISSUE THREAD

**Issue by codercody** [dask/dask#4860]
**Bug report**

When I called `set_index(..., sorted=True)`, I got a warning saying partition indices have overlap, which is fine. From here, after calling `repartition`, I lost a row. This must be a bug in the `repartition` code since I don't see why `repartition` would make me lose rows.

```python3
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> A = pd.DataFrame({'key': [1,2,3,4,4,5,6,7], 'value': list('abcd'*2)})
>>> a = dd.from_pandas(A, npartitions=2)
>>> a = a.set_index('key', sorted=True)
/Users/ctj/Documents/dask/dask/dataframe/shuffle.py:600: UserWarning: Partition indices have overlap.
  warnings.warn("Partition indices have overlap.")
>>> a.compute()
    value
key      
1       a
2       b
3       c
4       d
4       a
5       b
6       c
7       d
>>> a = a.repartition(divisions=a.divisions)
>>> a.compute()
    value
key      
1       a
2       b
3       c
4       a
5       b
6       c
7       d
```

**Comment by codercody** [comment]
I found a workaround to this phenomenon. Instead of using `repartition`, I just manually constructed the graph using `methods.boundary_slice`, though it seems like overkill to me.

**Comment by TomAugspurger** [comment]
It's possible that `sorted=True` is assuming that the provided index is
strictly increasing. Are you interested in investigating?

**Comment by codercody** [comment]
I’m currently working on implementing `merge_asof` but am certainly interested after I finish up! Shouldn’t be too much longer…

**Comment by codercody** [comment]
Does the Dask spec say that all the indices of partition i lie in the interval [ddf.divisions[i], ddf.divisions[i+1]) or is the upper bound allowed to be inclusive? (Except for the last partition)

**Comment by mrocklin** [comment]
> all the indices of partition i lie in the interval [ddf.divisions[i], ddf.divisions[i+1])

Yes

> is the upper bound allowed to be inclusive? (Except for the last partition)

No

This seems like a likely culprit in this case to me.

It looks like dask dataframe identified this and raised a not very informative warning

```python-traceback
/Users/ctj/Documents/dask/dask/dataframe/shuffle.py:600: UserWarning: Partition indices have overlap.
```

**Comment by codercody** [comment]
In that case, how would Dask handle when a ton of the rows have the same index? Is ddf.divisions necessarily a _strictly_ increasing sequence? (Except the last one)

**Comment by mrocklin** [comment]
> Is ddf.divisions necessarily a *strictly* increasing sequence

Yes

> how would Dask handle when a ton of the rows have the same index?

Poorly

**Comment by codercody** [comment]
Alright, this is very helpful. Thanks Matthew!

**Comment by TomAugspurger** [comment]
What's the next step here? Should that warning be elevated to an error (disclaimer: I haven't really dived into the context to understand the issue).

**Comment by codercody** [comment]
I’m currently using what Matthew said to fix it. Should be easy.

**Comment by codercody** [comment]
On second thought, it does cause the strictness of the upper bound to be violated. If you deem that error-worthy then sure.
