### ISSUE TITLE
Adding bokeh to the complete install scope 

### ISSUE THREAD

**Issue by philippegr** [dask/dask#4862]
This is a feature request 

From the [doc](http://distributed.dask.org/en/latest/web.html) Bokeh has to be installed separately. This is a somewhat unexpected behavior, as one would think that a `pip install dask[complete]` would bring everything.

I think that it would be worth: either including bokeh in the scope of complete or stating in dask-tutorials (like the one at Scipy) that the web interface requires an extra install that does not come bundled with complete. (The conda env for the dask tutorial contains a bit more lib that one may want to use in its own project)

**Comment by jakirkham** [comment]
Interesting question. Maybe it is worth adding a `diagnostics` extra, which includes `bokeh`. That way it will be folded into `complete`. Thoughts from others?

cc @mrocklin @TomAugspurger @quasiben @jrbourbeau @martindurant

**Comment by jakirkham** [comment]
As no one else has responded, I'll assume my suggestion above is ok (though please speak up if not). Would you be interested in submitting such a PR, @philippegr?

**Comment by philippegr** [comment]
I will give it a try :-)

**Comment by jakirkham** [comment]
Great! Thanks for the help. Please let us know if you run into any issues. Happy to help review once you have put something together. 🙂

**Comment by jakirkham** [comment]
In an effort to move things forward, have submitted PR ( https://github.com/dask/dask/pull/4924 ). Please share your thoughts over there.

**Comment by philippegr** [comment]
Sorry I did not move faster on that one

**Comment by jakirkham** [comment]
Not need to be sorry. It's part of my job to make sure things don't get dropped. So just wanted to make sure we were handling your concern.
