### ISSUE TITLE
Index not continuous for read_csv with chunksize specified

### ISSUE THREAD

**Issue by njanakiev** [dask/dask#4866]
First of all, wonderful project, thanks for the efforts! 
I noticed that the index of the resulting dataframe from `.read_csv()` with `blocksize` argument is not continuous for the whole dataframe (it repeats for each block from `0` to `blocksize - 1`):

```python
ddf = dd.read_csv(filepath, blocksize=10000)
```

Pandas also offers the functionality to read chunks of a CSV with [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) with the `chunksize` argument but the index there is continuous. It is a problem when doing joins and merges with the dataframe and e.g. there is no column with unique values.

**Comment by TomAugspurger** [comment]
Given just the blocksize, do we know the number of rows per partition without reading the actual file?

**Comment by njanakiev** [comment]
@TomAugspurger Isn't the number of rows per partition the same as the blocksize, or did I misunderstood something?

**Comment by mrocklin** [comment]
Right, it's not possible to do this and be nicely efficient.  I'm afraid this isn't likely to occur.  Closing for now.
