### ISSUE TITLE
divmod doesn't work on Dask Series

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#4874]
Currently [`divmod`]( https://docs.python.org/3/library/functions.html#divmod ) doesn't work on Dask Series. This should just be a matter of defining [`__divmod__`]( https://docs.python.org/3/reference/datamodel.html#object.__divmod__ ) and [`__rdivmod__`]( https://docs.python.org/3/reference/datamodel.html#object.__rdivmod__ ) for Dask Series objects, which can be defined in terms of the integer division and modulus as shown in the Python docs.

```python
In [1]: import pandas as pd                                                     

In [2]: import dask.dataframe as dd                                             

In [3]: s = pd.Series([-1.10, 2, -3.33, 4])                                     

In [4]: ds = dd.from_pandas(s, chunksize=1)                                     

In [5]: divmod(s, 2)                                                            
Out[5]: 
(0   -1.0
 1    1.0
 2   -2.0
 3    2.0
 dtype: float64, 0    0.90
 1    0.00
 2    0.67
 3    0.00
 dtype: float64)

In [6]: divmod(ds, 2)                                                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-4bf6ad8b37d6> in <module>
----> 1 divmod(ds, 2)

TypeError: unsupported operand type(s) for divmod(): 'Series' and 'int'
```

**Comment by Sriharsha-hatwar** [comment]
Will be working on this as well, will issue a separate PR in couple of days.

**Comment by jakirkham** [comment]
Thanks @Sriharsha-hatwar. It looks like @henriqueribeiro just recently submitted PR ( https://github.com/dask/dask/pull/4884 ). Maybe you'd be interested in helping review/test that?

**Comment by jakirkham** [comment]
Solved with PR ( https://github.com/dask/dask/pull/4884 ).
