### ISSUE TITLE
Add chunking dict to blockwise e.g.  da.blockwise(...,chunks=...)

### ISSUE THREAD

**Issue by mpeaton** [dask/dask#4879]
Feature Request
Currently da.blockwise does not have an interface for explicitly specifying chunk sizes.
Adding a "chunks" kwarg that accepts a dictionary may improve the syntax of blockwise expressions when rechunking is required.  For example:
```
da.blockwise(f, 'abc', x, 'bc', y, 'ab', chunks={'b': (2,3,4)}, dtype='f8')
```
Could be used instead of:
```
da.blockwise(f, 'abc', x.rechunk({0:(2,3,4)}), 'bc',
             y.rechunk({1:(2,3,4)}), 'ab', dtype='f8')
```

**Comment by jakirkham** [comment]
@shoyer, any thoughts on this?

**Comment by mrocklin** [comment]
@jakirkham heh I would actually have pinged you on this :)

**Comment by jakirkham** [comment]
I will also try to look later in the week when I'm off triage duty 😄

**Comment by mrocklin** [comment]
@mpeaton I'm curious, what is the motivating use case here?

My first instinct is that if this is just to avoid a rechunk call then I'm somewhat against this just to keep things orthogonal.  Otherwise we get too many keyword arguments in complex functions like blockwise and they become difficult to manage going forward (see for example, the current state of map_blocks).  

I also wouldn't want to add a `chunks=` keyword argument to every dask array function.  Is there some reason why blockwise is different here?

**Comment by mpeaton** [comment]
I understand.   Is it possible that specifying chunks explicitly in this manner, as opposed to via rechunk calls, would make the chunking computational requirement more easily utilized by dependent tasks?

**Comment by mrocklin** [comment]
> would make the chunking computational requirement more easily utilized by dependent tasks? 

I'm sorry but I'm not sure I understand what you mean here.  Can I ask you to rephrase?

Are you asking if there is some advantage to blockwise knowing a target chunk structure, rather than doing this in a previous step?  If so, then my answer is "I don't know".  Has this come up for you?

**Comment by mpeaton** [comment]
IIUC da.blockwise() is the only dask.array "building block" that allows multiple array inputs with arbitrarily-labeled/permuted axes, so chunks=… (or maybe rechunk=…?) makes particular sense there.  I don't think there would be much use for bubbling up beyond there.

As for my comment regarding dependent tasks, I was speculating about autochunking and related optimizations.  I have noted there is other work,  dask/dask#4763 , dask/dask#3587  that is not unrelated, so I'm sure you are giving plenty of thought to how chunks are being specified and managed in supported use cases.  I don't wish to pull you away from a more timely and appropriate improvement.   I think for now this Issue could be handled with a simple wrapper, unless you disagree.

**Comment by mrocklin** [comment]
> I think for now this Issue could be handled with a simple wrapper, unless you disagree.

If by a simple wrapper you mean "just add a chunks= keyword to blockwise, and call rechunk internally if so" then I disagree.  While I agree that the implementation is likely quite simple, adding new keyword arguments to a function like blockwise has long term consequences.  We have to continue maintaining it for a long time and consider how it interacts with all other keyword arguments, now and in the future.  There needs to be a good reason why it's important to do here.  I think that this conversation would benefit from a few such use cases, where adding a chunks= keyword argument to blockwise significantly benefits users.
