### ISSUE TITLE
Array creation and __array_function__

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4883]
One of the issues that arise when introducing `__array_function__` in a NumPy-like library, such as Dask, is array creation. Many functions require some sort of array to be created, either for temporary usage or to hold results. Specifically within Dask, most resulting arrays are simply NumPy-arrays, most of the times wrapped in a Dask array. However, when we deal with another NumPy-like library, be it either CuPy, xarray, Sparse, etc., we need to ensure that the arrays created within Dask match those types.

A very common case is the use of `empty` (and counterparts, `full`, `ones`, `zeros`), which we can now overcome with the introduction of `shape` argument in `empty_like` (and counterparts) in https://github.com/numpy/numpy/pull/13046. This is a great starting point, but doesn't solve all array creation issues. Most notably, we have `array` and `asarray`, which are _not_ included in the `__array_function__` scope, so we have no simple way to deal with certain situations involving those functions.

With Dask, we could of course introduce mechanisms such as looking up the type of the array and dispatching a call to that library, but this would limit the scope of use to a few libraries that we support and would be an effort, to my understanding, counter-productive towards `__array_function__`.

So my question here is: are there ideas out there already or discussions already initiated on how to solve such problems? Maybe @shoyer, @mrocklin or @jakirkham know something about this already?

**Comment by mrocklin** [comment]
I'm not sure I fully understand, what are situations where this goes poorly? 

For example, if I can `da.asarray(my_cupy_array)` do I not get a dask array of cupy arrays?

**Comment by pentschev** [comment]
> For example, if I can `da.asarray(my_cupy_array)` do I not get a dask array of cupy arrays?

That's correct, and if I'm not mistaken, this is the primary reason we have to use `asarray=False` when creating a Dask array from a CuPy array.

**Comment by pentschev** [comment]
And beyond that, we have cases where we create an array from a list, for example, currently there's no mechanism to ensure that this array will be of same type of some other array which will be operated on. One example is `percentile`, in which we have an array `a` that can be a CuPy array for example, and `q` which is array-like but we need to make a CuPy array from it. See https://github.com/dask/dask/commits/master/dask/array/percentile.py

**Comment by mrocklin** [comment]
If possible I would like to focus first on the `da.asarray(my_cupy_array)` case.  I think that it is likely easier to manage.

Some relevant code is here:

https://github.com/dask/dask/blob/165f71e70983874a9f63eda544199d526041f69f/dask/array/core.py#L2316-L2334

There is some clear special-casing of NumPy here.  I wonder if there is some check we can do instead of an explicit type check here that would be valid.  cc @shoyer in case he has suggestions.  For example I wonder what would happen if we added the check

```python
asarray = not hasattr(x, '__array_function__')
```

This would change behavior on matrix objects (although maybe that's ok now with `_meta`).  

Also, I noticed that there is an `asanyarray` function, which isn't as nice as using `asarray` directly, but might be a short-term standin.

https://github.com/dask/dask/blob/165f71e70983874a9f63eda544199d526041f69f/dask/array/core.py#L3163-L3201

**Comment by mrocklin** [comment]
For the `da.asarray(my_list)` case that seems a bit harder to resolve.  Maybe a `like=` keyword?  This seems a bit odd though.

**Comment by pentschev** [comment]
I don't have a particular order in which I would like to keep, I'm just raising this question in case we already have something ongoing, and to get ideas from other people.

The idea I had was similar to your `like=` argument suggestion, but with a new function, similar to `empty_like`. In any case, I don't know long-term what would be a better solution, ideally -- and supposing the idea is to have `__array_function__` more widely used -- we would have a way for libraries to specify what a resulting array should look like, e.g., you have an array as input, so your output should be the same type of array, which often requires that other arrays created internally be of that type as well.

Maybe I have incorrect expectations and this is not intended with NEP-18 for a reason, but for now I think it's missing that capability, which is essential in some situations, such as I mentioned before with `percentile`.

**Comment by pentschev** [comment]
And by the way, something that maybe wasn't clear before, the issue is not with Dask alone, but we can't use `numpy.asarray(cupy_array)` as well:

```python
>>> import numpy as np
>>> import cupy
>>> a = cupy.empty((2, 2))
>>> b = np.asarray(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/pentschev/.local/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: object __array__ method not producing an array
```

**Comment by jakirkham** [comment]
For fixing `da.asarray`, maybe we can go through a deprecation cycle and then default to `asarray=False`.

That said, IIUC the `da.asarray` is a finer point. The larger issue is, how do we handle array creation in algorithmic code? Currently we have hard-coded NumPy array creation in some places. How can we relax this to create an array matching the input type when needed?

**Comment by pentschev** [comment]
> For fixing `da.asarray`, maybe we can go through a deprecation cycle and then default to `asarray=False`.

I think the main problem isn't `da.asarray`, but `np.asarray` itself, since we can't dispatch that with a CuPy array, for example. Maybe if that was possible, we wouldn't need to use `asarray=False` in Dask array creation at all.

> That said, IIUC the `da.asarray` is a finer point. The larger issue is, how do we handle array creation in algorithmic code? Currently we have hard-coded NumPy array creation in some places. How can we relax this to create an array matching the input type when needed?

Correct, and I'm raising this here to see what ideas we have on the Dask side, but this may be a question that we need to raise in NumPy itself.

**Comment by mrocklin** [comment]
Cupy intentionally doesn't want np.asarray(my_cupy_array) to work.  Their
reasoning here is that this often happens and reduces performance.  They
would rather that users intentionally call a to_numpy method, or something
similar.

**Comment by jakirkham** [comment]
IIUC Peter is suggesting that `np.asarray` should mean `cp.asarray` in some cases. Perhaps similar to [the backend selection idea]( https://github.com/scipy/scipy/issues/10204#issuecomment-495225397 ). Though please correct me if I'm getting this wrong, Peter.

Anyways I don't think we should get too bogged down in `asarray` in particular. It's only one example of the kinds of issues we still encounter.

**Comment by mrocklin** [comment]
My guess is that that's not possible today.  Too much of the ecosystem probably depends on `np.asarray` to produce exactly a numpy array.

**Comment by pentschev** [comment]
> IIUC Peter is suggesting that `np.asarray` should mean `cp.asarray` in some cases. Perhaps similar to [the backend selection idea](https://github.com/scipy/scipy/issues/10204#issuecomment-495225397). Though please correct me if I'm getting this wrong, Peter.
> 
> Anyways I don't think we should get too bogged down in `asarray` in particular. It's only one example of the kinds of issues we still encounter.

You're correct in your entire statement. :)

**Comment by pentschev** [comment]
> My guess is that that's not possible today. Too much of the ecosystem probably depends on `np.asarray` to produce exactly a numpy array.

That's right, it isn't possible today, and that's exactly what I want to discuss: how do we make it possible?

It is too often the case that we need to create new arrays, and for `__array_function__` to work properly in all (or almost all) cases, we need to deal with that. This is why I used the example of `shape` in `empty_like`, we depend on it in several instances, and we need something similar for `np.array` and `np.asarray`, and perhaps others as well, but I don't know how many of NumPy's array creation functions are of much relevance for other libraries, such as Dask and CuPy.

**Comment by shoyer** [comment]
> > My guess is that that's not possible today. Too much of the ecosystem probably depends on `np.asarray` to produce exactly a numpy array.
> 
> That's right, it isn't possible today, and that's exactly what I want to discuss: how do we make it possible?

My view is that we need a new coercion function/protocol inside NumPy, something like `np.duckarray()`. We can't change `np.asarray()` because that is used in some cases where the user expects real NumPy arrays (e.g., with `strides`).

Nathaniel Smith and I discussed this in [NEP-22](http://www.numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html#principle-3-focus-on-protocols), but didn't come to a concrete proposal, mostly because we struggled to come up with a good [name](http://www.numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html#terminology).

**Comment by jakirkham** [comment]
Is there an issue on the NumPy repo that we should use to discuss this proposal, @shoyer?

**Comment by pentschev** [comment]
TBH, I've been trying to wrap my head around the NEP-22 proposal, but I still don't understand how we would use that in practice. I'm very sure I don't understand the proposal well, but my little understanding is that duck arrays would automatically convert itself, we will face some rejection, and here I'm thinking particularly of CuPy, where no implicit conversion is allowed. Happy to continue the discussion either here or some more appropriate place.

**Comment by shoyer** [comment]
It wouldn't be a bad idea to discuss this in the NumPy tracker somewhere.

My thinking something like the following implementation for the protocol:
```python
import numpy as np

# hypothetical np.duckarray() function
def duckarray(array_like):
  if hasattr(array_like, '__duckarray__'):
    # return an object that can be substituted for np.ndarray
    return array_like.__duckarray__()
  return np.asarray(array_like)
```

Example usage:
```python
class SparseArray:
  def __duckarray__(self):
    return self
  def __array__(self):
    raise TypeError

duckarray(SparseArray())  # returns a SparseArray object
np.array(SparseArray())  # raises TypeError
```

**Comment by jakirkham** [comment]
What you are proposing sounds reasonable, Stephan. Is there a particular NumPy issue we should move too?

**Comment by jakirkham** [comment]
@shoyer, I went ahead and opened issue ( https://github.com/numpy/numpy/issues/13831 ) (copying everyone here) to get the ball rolling on this. Hope that is ok. 🙂

**Comment by pentschev** [comment]
We have now a more appropriate place to discuss this in https://github.com/numpy/numpy/issues/13831, so I'm closing this.
