### ISSUE TITLE
Implementing sizeof() for third-party libraries

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4891]
For the task of memory spilling in https://github.com/rapidsai/dask-cuda, we need to add `sizeof()` support for https://github.com/rapidsai/cudf types (and maybe others in the future), the easiest would be to add that to `dask/sizeof.py`, is that something acceptable to have in Dask? Otherwise, I would implement that in dask-cuda itself and have a fallback to `dask.sizeof` for the types that already exist in Dask. Note that we do this already for CuPy, which is also a third-party library.

**Comment by mrocklin** [comment]
Benefits of pushing into downstream libraries, like dask-cuda 

-  Reduce scope of the core library (we wouldn't want every downstream Python library to add their own serialization to our codebase.
-  Easier for cudf dev community to change things without having to check in with the dask/dask group

Benefits of dask/dask

-  It will be reliably imported.  It's entirely possible that people won't import the dask-cuda library in their workers when deploying Dask.  If this happens then they might not see this code

Another option would be to use the Python `__sizeof__` protocol on cudf objects.  In general, if we can keep this code in the `cudf` project somehow that seems best.  A protocol like `__sizeof__` might be the best of both worlds.  Any thoughts @kkraus14 ?

**Comment by pentschev** [comment]
Instead of implementing `sizeof()` for third-party libraries, I propose a different solution now. We add a parameter `sizeof_func` to `distributed.sizeof.safe_sizeof` which defaults to `dask.sizeof.sizeof`. We can then reimplement that function in libraries such as dask-cuda to handle specialized types or simply return `dask.sizeof.sizeof` in case the type isn't explicitly handled by this new function. Does that approach seem reasonable to you @mrocklin ?

**Comment by mrocklin** [comment]
The current sizeof functions are dispatchable, meaning that you can extend them to custom types today in other libraries.  I think that this is similar to your suggestion to take in a `sizeof_func` function.  In other libraries you can do the following:

```python
from dask.sizeof import sizeof

@sizeof.register(MyCustomType)
def sizeof(obj):
    return ...
```

However, we need to make sure that those libraries are imported on the workers.  For this reason it's slightly more safe to have the implementation in cudf rather than dask-cuda, because dask-cuda might not be imported in all cases.

Regardless, I think that safeest and most general solution is just to implement the `__sizeof__` method in cudf. 

```python
class DataFrame:
    def __sizeof__(self):
        return ...
```

The various sizeof functions will pick this up automatically.

**Comment by pentschev** [comment]
There is a `__sizeof__` implementation in cudf, but now that you mention it, I think that it didn't work well maybe because of the issue in https://github.com/rapidsai/cudf/issues/1957. The size didn't match and I assumed it was using a wrong implementation (like Pandas), but maybe it's just that bug. Let's hold on with the issue here and see if we can fix the cudf issue first, that may solve all our problems.

**Comment by jakirkham** [comment]
Is this still relevant or is it safe to close?

**Comment by pentschev** [comment]
This has been solved in cuDF, so no longer relevant, closing. Thanks for pinging @jakirkham .
