### ISSUE TITLE
Dask monthly meeting calendar

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4892]
It seems that lately we're having issues interpreting timezones. The meeting on my calendar was supposed to start one hour after it actually happened, and I think @mrocklin had a similar issue.

I don't know if this is something that can be fixed easily with google calendar, so I suggest we keep that invite (as a suggestion only, and additionally encourage people to confirm if the time is indeed correct!) but we have an entry somewhere stating when it's happening, completely disconnected to any calendars and with a single timezone. The issue with having multiple timezones stated is very easily demonstrated, take the [meeting info doc](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit#heading=h.j9d68y361gb2) where it's stated the meeting happens 16:00 UTC and 08:00 Pacific, which 8h difference, but due to daylight savings, the difference today is only 7h.

cc @jrbourbeau @mrocklin

**Comment by TomAugspurger** [comment]
I updated the google calendar invite:
https://calendar.google.com/event?action=TEMPLATE&tmeid=NmxnamVvcGtjY3E2NGI5bTZzcW1hYjlrYzhybTZiYjFjY29qOGI5ZzY0cWoyYzFrNjFpMzhwaGlja18yMDE5MDYwNlQxNjAwMDBaIDRsMHZ0czBjMWNnZGJxNWpoY29najU1c2ZzQGc&tmsrc=4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com&scp=ALL

The meeting now has a timezone of (GMT+00:00) Coordinated Universal Time.

So today's would have occurred at 11:00 Central. The next meeting after the
US DST transition should be December, and that shows up on my calendar as
10:00 Central.

Hopefully we're all sorted out now.

**Comment by mrocklin** [comment]
I suspect that this does not always align with the text in
http://docs.dask.org/en/latest/support.html#discussion .  We might want to
remove the text that gives rough times in different parts of the world and
instead just use the UTC or GMT time

**Comment by TomAugspurger** [comment]
Yes, if we're OK with the local time of the meeting shifting around DST
transitions, then I think removing that text and replacing it with UTC (and
a link to the calendar invite) is best.

**Comment by jakirkham** [comment]
So last monthly meeting (before today's) we agreed to reset the time to remain the same after daylight savings time in the US. IOW we made it 11a EDT. It sounds like we are changing it again. Could we please not change the time again, but instead keep it at 11a EDT?

**Comment by pentschev** [comment]
FWIW, I don't care which timezone is used, as long as there's a single one used as reference that we can always check the day before and be sure of the right time.

**Comment by jakirkham** [comment]
Sure, to be clear I'm not so concerned with timezone. Am just trying to avoid changing the time again given we are already having issues with people showing up at the wrong time. If we can change the timezone so that the time doesn't not change for the next meeting, that would be preferred. Does this sound reasonable to people? If so, @TomAugspurger would it be possible to reflect this in the event?

**Comment by jakirkham** [comment]
IIRC we decided in our core meeting last week to reset this to follow US DST. Does that sound correct? If so, what are the next steps here?

**Comment by TomAugspurger** [comment]
Sorry, dropped the ball. @pentschev does fixing the calendar in, say, US Eastern time sound OK to you? It'll mean the time of the meeting will shift in your local time around DST transitions, assuming your local time isn't synced up with US DST.

**Comment by pentschev** [comment]
Yep, which timezone is used is less important to me, as long as we can always confirm the time without margin for being off by one [hour].

**Comment by jakirkham** [comment]
@martindurant [mentioned on Gitter]( https://gitter.im/dask/dev?at=5d0a66fc4e8f972d37593025 ) that the next monthly meeting lands on July 4th (a US holiday). How would we like to handle that?

**Comment by martindurant** [comment]
I would suggest either postponing a week or going ahead, and accepting a possible low turnout. It is not a holiday in Canada, and probably almost all other countries, but the dev group is certainly US dominated. In the user survey we might have also asked which country people were from...

**Comment by mrocklin** [comment]
I suggest postponing a week.  Some of us will be in SciPy that week, and it
might be nice to force a physical get-together.

**Comment by TomAugspurger** [comment]
Agreed with postponing.

I've updated the google meeting invite to

1. Be fixed at 11:00 US Central Time
2. Postponed the July 4th meeting to July 11th (11:00 US Central Time).

leaving this issue open to update the docs.

**Comment by jrbourbeau** [comment]
Wanted to re-ping this issue again. Copying over from gitter:

> lets move the monthly dev meeting to 12pm central tomorrow, Friday 2019-07-12 . There are a number of us who have conflicts today at the SciPy conference
