### ISSUE TITLE
Feature Request:  Timestamp in logs

### ISSUE THREAD

**Issue by simaster123** [dask/dask#4893]
I think it would help debugging and performance optimization.  I find it hard to line up output from my own logs with the logs from the dask-scheduler/ dask-workers.

**Comment by mrocklin** [comment]
Dask uses the standard Python logging module.  This means that you can control logging today by modifying the settings there.

If you want to use Dask configuration, then this is customizable with the `distributed.admin.log-format` configuration value.  See https://docs.dask.org/en/latest/configuration.html 

See 

https://docs.python.org/3/library/logging.html#logrecord-attributes

https://github.com/dask/distributed/blob/0696a1f6456b8010b19ac47b14cd2dca0d859246/distributed/distributed.yaml#L99

cc also @TomAugspurger , who was asking about this

**Comment by simaster123** [comment]
Perfect - thank you!  

For what it's worth, I edited the distributed/distributed.yaml file as follows:

From:
`log-format: '%(name)s - %(levelname)s - %(message)s'`

To:
`log-format: 'Dask Log -- %(asctime)s - %(name)s - %(levelname)s - %(message)s'`
