### ISSUE TITLE
`DataFrame.to_parquet(engine='fastparquet')` not amenable to out-of-core workflows

### ISSUE THREAD

**Issue by bnaul** [dask/dask#4894]
**Summary**: the fact that `df.to_parquet` returns a single delayed object which depends on all of the chunks being written prevents memory from being freed and makes it difficult (impossible?) to use it for out-of-core analyses.

**Example**: let's say we want to perform some dataframe operation and save the results. With `to_csv` it's easy to write a chunk at a time and garbage collect the inputs as we go:
```
import distributed, dask.dataframe as dd
client = distributed.Client()
ddf = dd.from_pandas(pd.util.testing.makeCustomDataframe(100, 3), chunksize=5)
def f(_df):
    import numpy as np
    import time
    time.sleep(np.random.randint(1, 20))
    return _df
output = ddf.map_partitions(f).to_csv('/tmp/output_*.csv', compute=False)
#output = ddf.map_partitions(f).to_parquet('/tmp/output', compute=False)
ac = distributed.as_completed(distributed.futures_of(client.persist(output)))
for _ in ac:
    # as each chunk is written, the future is deleted and the scheduler can forget about it
    # this is obvious on the scheduler bokeh diagnostic but I'm not sure how else to show it
    pass
```

`to_parquet` on the other hand returns a single `Delayed()` object which depends on all of the intermediate partitions, so everything has to remain in memory until the entire write is completed.

The offending `_write_fastparquet` code is:
```
    write = delayed(_write_partition_fastparquet, pure=False)
    writes = [write(part, fs, path, filename, fmd, compression, partition_on)
              for filename, part in zip(filenames, df.to_delayed())]

    return delayed(_write_metadata)(writes, filenames, fmd, path, fs, sep)
```
Would extracting the necessary metadata from each partition as an intermediate task be enough to allow the inputs to be cleared from memory? I'm interested in taking a stab at this if it seems like a reasonable solution. cc @martindurant since I believe this is `fastparquet`-specific.

**Comment by martindurant** [comment]
Have you observer the behaviour (holding on to memory) in practice? The `writes` above evaluate to pieces of parquet metadata, not the original data that was written to disc. Although these also take up some memory, there is no reason it should be a bottleneck or constraint in the typical scenario of many rows/few columns per partition.

Worth mentioning that pyarrow is in the process of being able to pass parquet metadata around for writing to a common metadata file in this manner, so will have very much the same execution pattern.

**Comment by bnaul** [comment]
I have* observed this behavior; in particular the reason I'm interested in changing this is that my workers are running out of memory and being evicted (this is on Kubernetes). The problem actually sort of compounds itself because tasks for files that were already written are still being held by the scheduler, so when the worker responsible for that task gets killed the scheduler thinks that the task needs to be retried even though the desired side effect already occurred. Maybe this is related to read/writing tasks getting fused together by the graph optimizer?

* I've also seen pretty substantial memory leaks from pandas in the same kinds of situations, so maybe I'm conflating the two here?

**Comment by martindurant** [comment]
> I've also seen pretty substantial memory leaks from pandas

we have come across such things where many allocations and releases are happening, but I thought this was much better in pandas 24 and whatever numpy did.

> even though the desired side effect already occurred

Can you tell what a worker is doing at the time of death? If is any worker, or specifically the one expecting to do the finalisation task? You can use the `client.nbytes` method to find out how much memory the partition-writing results are actually taking up.

I should mention that the version of fastparquet that will eventually be released for python-3 only will include an option not to collect statistical data about columns, which will help the parquet metadata results pieces' size a bit.

What is your typical number of rows per partition, number of columns and number of partitions?

**Comment by martindurant** [comment]
(I should mention, in reference to my comment about pyarrow, that the same refactor will allow skipping of the finalisation step, in cases where the global metadata file is not useful, for both pyarrow and fastparquet)

**Comment by birdsarah** [comment]
I think https://github.com/dask/dask/issues/4410 is related.

**Comment by jcrist** [comment]
`to_parquet` no longer produces a `_metadata` file by default, so the memory taken by metadata aggregation is no longer required by default. If the user sets `write_metadata_file=True`, only the metadata is collected and merged in a single aggregation task, the original data is not held in memory and can be released. Closing.
