### ISSUE TITLE
Var calculation fails with non-pandas Dataframe

### ISSUE THREAD

**Issue by quasiben** [dask/dask#4910]
When using `dask-cudf`, the new parallel variance calculation will fail (PR https://github.com/dask/dask/pull/4865/) . This is probably due to two main causes

- `__array_interface__`   isn't fully implemented: `np.X` (var/nansum) may not be supported but can be added see https://github.com/rapidsai/cudf/issues/1728
- Tightly using pandas signatures: `pd.Series -> Series()`, `pd.concat -> Concat`

**Comment by quasiben** [comment]
I'm not sure what the best action here is but I think there are two solutions:

1) fix cudf to work with the various numpy calls and update dask with generalized dataframe things
2) detect non-pandas dataframes and dispatch to old variance calculation

**Comment by TomAugspurger** [comment]
My preference is for option 1. Does the cudf side of things sound difficult?

**Comment by quasiben** [comment]
I don't think it should be too bad -- i'll look at it shortly and come back with an update

**Comment by quasiben** [comment]
I added `__array_function__` to cuDF for numpy dispatch but ran into some trouble with dask core bits.  I didn't fully appreciate this at the outset, but using dask-array means the object being passed around needs to support much/all of the dask-array.  Parallel variance will eventually call `to_dask_array` -- a `dask_cudf.Series` currently does not support enough of the array like things to make it all the way through the array reduction machinery.  

Another thing we could do is vendor in the old variance work into dask-cudf -- this would be a short term solution

cc @mrocklin

**Comment by jakirkham** [comment]
cc @pentschev (in case you have thoughts here 😉)

**Comment by pentschev** [comment]
It looks like the most relevant changes in #4865 were in the dataframe context, which I don't know much about.

@quasiben if you need any help with `__array_function__` I can try to take a look at it tomorrow.

**Comment by jakirkham** [comment]
That's correct. It was the `__array_function__` bit that I thought you might find interesting. 😉

**Comment by kkraus14** [comment]
We'll work on fixing cuDF upstream and as a stopgap we can vendor over the old variance code so as to not slow down Dask. Thanks all!

**Comment by quasiben** [comment]
In a chat with @mrocklin we briefly experimented with use `cupy.array` on the `dask_cudf.Series` obj.  This gets you quite far but trouble arises with the `nansum`.  Nansum has not been implemented but there is a TODO in the cupy src:

https://github.com/cupy/cupy/blob/0e4141428d4dace8d13e10ac58c844d3bb0d23c5/cupy/math/sumprod.py#L66

@pentschev would this be difficult to add ?

**Comment by pentschev** [comment]
Not sure yet, I will take a look at it soon. Possibly, a specialized reproduction of `sum` will do.

**Comment by jakirkham** [comment]
Might be worth taking a look at PR ( https://github.com/cupy/cupy/pull/2222 ), which implements some other `nan` functions. The same strategy could be leveraged by `nansum` without too much difficulty.

**Comment by pentschev** [comment]
Thanks @jakirkham for mentioning that PR, I would not have seen that otherwise! :)

**Comment by mrocklin** [comment]
More generally, it looks like we're now computing dataframe variance computations using numpy-like functions.  This causes problems with gpu dataframes/arrays due to null-handling, but I could imagine that it would also cause problems with other non-numpy compatible dtypes in the future (though perhaps those don't exist).

**Comment by pentschev** [comment]
@quasiben could you try out https://github.com/cupy/cupy/pull/2252 and see if it works for you?

**Comment by pentschev** [comment]
https://github.com/cupy/cupy/pull/2252 has just been merged, let me know if you encounter any issues with that @quasiben .

**Comment by quasiben** [comment]
I will try this out tomorrow.  Thanks!

**Comment by quasiben** [comment]
I believe we can close this now as a lot of work has gone into cudf to support `__array_function__` calls:


```python
In [1]: import cudf

In [2]: import dask.datasets

In [3]: ddf = dask.datasets.timeseries()

In [4]: cdf = ddf.map_partitions(cudf.from_pandas)

In [5]: cdf.head()
Out[5]:
                       id     name         x         y
timestamp
2000-01-01 00:00:00   983   George  0.355031 -0.200610
2000-01-01 00:00:01  1011    Kevin -0.784447 -0.212326
2000-01-01 00:00:02   991   George -0.295418  0.403791
2000-01-01 00:00:03   989  Norbert  0.474926 -0.494320
2000-01-01 00:00:04   963   Ingrid -0.845560 -0.586977

In [6]: cdf.x.var().compute()
Out[6]: 0.33295403416731695

In [7]: ddf.x.var().compute()
Out[7]: 0.33295403416731695
