### ISSUE TITLE
Dataframe.to_parquet does not work with Path

### ISSUE THREAD

**Issue by philippegr** [dask/dask#4936]
```
from dask import dataframe as ddf
from pathlib import Path

# Empty DaskDF for the sake of it 
import pandas as pd
pd_df = pd.DataFrame()
my_df = ddf.from_pandas(pd_df, npartitions=2)

my_df.to_parquet(Path('/mnt/tmp/test'))
```
Last line fails with

```pytb
> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-d291d9cdd052> in <module>
----> 1 df.to_parquet(Path('/mnt/tmp/test'))

~/.cache/pypoetry/virtualenvs/hello-py3.7/lib/python3.7/site-packages/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
   2904         """ See dd.to_parquet docstring for more information """
   2905         from .io import to_parquet
-> 2906         return to_parquet(self, path, *args, **kwargs)
   2907 
   2908     @derived_from(pd.DataFrame)

~/.cache/pypoetry/virtualenvs/hello-py3.7/lib/python3.7/site-packages/dask/dataframe/io/parquet.py in to_parquet(df, path, engine, compression, write_index, append, ignore_divisions, partition_on, storage_options, compute, **kwargs)
   1252                                          storage_options=storage_options)
   1253     # Trim any protocol information from the path before forwarding
-> 1254     path = infer_storage_options(path)['path']
   1255 
   1256     out = write(df, fs, fs_token, path, write_index=write_index, append=append,

~/.cache/pypoetry/virtualenvs/hello-py3.7/lib/python3.7/site-packages/dask/bytes/utils.py in infer_storage_options(urlpath, inherit_storage_options)
     38     """
     39     # Handle Windows paths including disk name in this special case
---> 40     if re.match(r'^[a-zA-Z]:[\\/]', urlpath):
     41         return {'protocol': 'file',
     42                 'path': urlpath}

/usr/local/lib/python3.7/re.py in match(pattern, string, flags)
    171     """Try to apply the pattern at the start of the string, returning
    172     a Match object, or None if no match was found."""
--> 173     return _compile(pattern, flags).match(string)
    174 
    175 def fullmatch(pattern, string, flags=0):

TypeError: expected string or bytes-like object
```

Is it a problem of implementing a PathLike interface? (On a *non-empty* df using `str(Path(...))` would work)

**Comment by TomAugspurger** [comment]
Can you post a full example (simple definition of df) and a traceaback?

**Comment by philippegr** [comment]
Edited my initial post

**Comment by TomAugspurger** [comment]
Thanks. I think that we should add something like

```
path = path.__fspath__() if hasattr(path, "__fspath__") else path
```

somewhere before calling `infer_storage_options`. Are you interested in exploring that @philippegr?

**Comment by mrocklin** [comment]
Would `path = str(path)` work?

**Comment by TomAugspurger** [comment]
For pathlib, probably. What I posted is for anyone implementing the fspath protocol.

**Comment by philippegr** [comment]
> Thanks. I think that we should add something like
> 
> ```
> path = path.__fspath__() if hasattr(path, "__fspath__") else path
> ```
> 
> somewhere before calling `infer_storage_options`. Are you interested in exploring that @philippegr?

That would fix it locally, and yes I could do that. 

Looking at the pandas codebase, there is a generic function to handle this cases
https://github.com/pandas-dev/pandas/blob/d2beaf3c821236e8e2f6fb0bdaf90ff3d404cc11/pandas/io/common.py#L97

That would be a more robust across the API solution, but I must also say that it's probably touching too many files for me to be comfortable doing this

**Comment by TomAugspurger** [comment]
The pandas function you linked to is private. It wouldn't be appropriate for Dask to use.

**Comment by philippegr** [comment]
@TomAugspurger of course not. 
I was just suggesting that a similar function in Dask could solve the problem in many different places.

**Comment by martindurant** [comment]
I wonder why we want to support this? Since we'd immediately convert the Path to a string, why not require the caller to do this beforehand?

**Comment by TomAugspurger** [comment]
working with Paths is much nicer than strings. And pandas supports it, so we should too.

**Comment by jrbourbeau** [comment]
@philippegr a new `stringify_path` function was just added to `dask/bytes/utils.py` which you may find useful

https://github.com/dask/dask/blob/1701064f4c4d566ba0ae65d00486ef12a5e77898/dask/bytes/utils.py#L271-L297

**Comment by TomAugspurger** [comment]
So we'll want to call `stringify_path` somewhere before https://github.com/dask/dask/blob/6e5043ac7670e4d1de772dbe2aeea7359821b5f6/dask/dataframe/io/parquet.py.

**Comment by jrbourbeau** [comment]
Closing as this appears to be supported with `fsspec==0.6.2` and `dask==2.11.0`
