### ISSUE TITLE
Mask selection vs compress() - inconsistent shape

### ISSUE THREAD

**Issue by alimanfoo** [dask/dask#4940]
Using dask 1.2.2. In the following example:

```
In [16]: x = da.from_array(np.arange(5), chunks=2)                                                                                                                           

In [17]: x                                                                                                                                                                   
Out[17]: dask.array<array, shape=(5,), dtype=int64, chunksize=(2,)>

In [18]: t = np.array([1, 0, 0, 1, 0], dtype=bool)                                                                                                                           

In [19]: da.compress(t, x, axis=0)                                                                                                                                           
Out[19]: dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,)>

In [20]: x[t]                                                                                                                                                                
Out[20]: dask.array<getitem, shape=(2,), dtype=int64, chunksize=(1,)>
```

...I would expect ``da.compress(t, x, axis=0)`` to give the same result as ``x[t]``, however the shape is ``(nan,)`` in the first case and ``(2,)`` in the second. 

Is this expected behaviour?

**Comment by alimanfoo** [comment]
Maybe the difference is because ``compress()`` calls ``asarray(condition)`` [here](https://github.com/dask/dask/blob/d8ff4c4d155d51cf275776c1ec8ef27c16d43f17/dask/array/routines.py#L1005). I.e., the ``condition`` array is coerced to a dask array, although it doesn't really need to be if it is a numpy array.

Perhaps we could add a check to allow ``condition`` to be a numpy array, and if so don't coerce to dask array? Happy to make a PR if that sounds reasonable.

cc @jakirkham as I know you rewrote ``compress()`` recently in #4548.

**Comment by mrocklin** [comment]
That sounds reasonable to me
