### ISSUE TITLE
Problem with merging on a named index

### ISSUE THREAD

**Issue by AdrienHEH** [dask/dask#4941]
Dask version: 1.2.2, python 3.7.2

```
import dask.dataframe as dd
data = dd.read_csv(***, usecols=['THD_ID_N'], dtype=str)
portfolio = dd.read_parquet(***)
```
`portfolio` contains a `str` index named `eh_id`, and another column which will not be used.
Merging them directly results in an empty dataframe, when it shouldn't:
```
data.merge(portfolio, left_on='THD_ID_N', right_index=True).compute()
```
Going back to pandas before the merge solves the issue (non empty dataframe):
```
data.compute().merge(portfolio.compute(), left_on='THD_ID_N', right_index=True)
```
Using the name of the index in dask also solves the issue (non empty dataframe):
```
data.merge(portfolio, left_on='THD_ID_N', right_on='eh_id').compute()
```
Somehow computing the dask.dataframe to pandas and then recasting it to a dask dataframe solves the issue too (non empty dataframe):
```
data.merge(dd.from_pandas(portfolio.compute(), npartitions=20), left_on='THD_ID_N', right_index=True).compute()
```
If that matters, the `portfolio` parquet was created using dask.

**Comment by TomAugspurger** [comment]
Are you able to provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@AdrienHEH let us know if you can get a minimal example together and we'll reopen.
