### ISSUE TITLE
Event loop was unresponsive in Worker for 5.02s, whilst using scatter

### ISSUE THREAD

**Issue by anfractuosity** [dask/dask#4965]
I get this warning or similar, with dask 1.2.2

```
[ worker 192.168.10.1 ] : distributed.core - INFO - Event loop was unresponsive in Worker for 3.90s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```

When running 1 or 2 workers, via:

dask-ssh 192.168.10.1 
or
dask-ssh 192.168.10.1 192.168.10.11

Code:
```
#!/usr/bin/python3 

from dask import delayed
import time
import socket
from dask.distributed import Client, LocalCluster

client = Client('127.0.0.1:8786', processes=True)

def inc(x):
    return x + 1

L = client.scatter(range(10000))
future = client.submit(sum,L)
print(future.result())
```

I've tried processes=False also.  Is it ok to ignore this, as I'm using scatter to distribute data, so there would be a certain degree of I/O waiting anyway?

**Comment by martindurant** [comment]
You have created 10000 very small futures here, and then one tasks for each. Creating all of that and communicating it all to the scheduler takes time. You might want to read about how you can batch computations of this sort, perhaps using Dasks "bag" interface.

**Comment by mrocklin** [comment]
See
https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-too-many-tasks

Also, the warning is fine.  It's just a warning.  Things should work ok.

**Comment by anfractuosity** [comment]
Cheers both of you, I just switched to use scatter with bagged data, and it's now a lot faster too! Thanks a lot :)

**Comment by impravin22** [comment]
> Cheers both of you, I just switched to use scatter with bagged data, and it's now a lot faster too! Thanks a lot :)

Sorry, Can you explain how did you switch to scatter with bagged data?
