### ISSUE TITLE
Program stuck many times for undefined time in case of a large CSV file.

### ISSUE THREAD

**Issue by 3ggaurav** [dask/dask#4971]
I import a large CSV file (size - 2.2GB) having 14,972,640 rows and 19 columns. After importing the file, I just run the block to find the length of the dataframe. It stuck for a long time, after some time, It runs for a second then again stuck. This process goes several times, then finally in 4-5 steps, it calculates the length of dataframe to 14,972,640 in 12min 23sec.
My code is in Screen Shot 2019-06-20 at 4 45 44 PM.  I don't know why the code stopping many times in between the run.
Note:- All the Task graph screenshots are telling the stuck point of code for 3-4 minutes.

![Screen Shot 2019-06-20 at 4 45 44 PM](https://user-images.githubusercontent.com/19906193/59846990-f9f11700-937e-11e9-93ae-a0db3bad1149.png)
![Screen Shot 2019-06-20 at 5 16 23 PM](https://user-images.githubusercontent.com/19906193/59847071-2b69e280-937f-11e9-9963-812fd34f9a2e.png)
<img width="486" alt="Screen Shot 2019-06-20 at 4 45 10 PM" src="https://user-images.githubusercontent.com/19906193/59847091-37ee3b00-937f-11e9-811a-f518df4f5666.png">
![Screen Shot 2019-06-20 at 4 44 41 PM](https://user-images.githubusercontent.com/19906193/59847101-3faddf80-937f-11e9-874a-10b83e506ae8.png)
![Screen Shot 2019-06-20 at 4 48 26 PM](https://user-images.githubusercontent.com/19906193/59847112-48061a80-937f-11e9-93d9-a4215e66c2df.png)

**Comment by TomAugspurger** [comment]
Is it stuck, or is it loading data?

**Comment by 3ggaurav** [comment]
As I said, it was stuck at many points on execution. I also check the Task stream graph shows in the status window. Let me clear by screenshots. I took some more screenshots for analyzing, so You can see the attachment. It takes 10 min 37s for this run, in the previous run It takes 12 min 23 sec. Let me Explain - 
![Screen Shot 2019-06-21 at 11 33 46 AM](https://user-images.githubusercontent.com/19906193/59901322-7ab02180-9418-11e9-9e13-750799d42c9d.png)

Stage 1: It stuck at the starting of the run for 4 to 5 min. 
![Screen Shot 2019-06-21 at 11 16 20 AM](https://user-images.githubusercontent.com/19906193/59901391-b519be80-9418-11e9-8531-9350aa38641e.png)

Stage2: After stage 1, suddenly in 2-3 sec It executes till stage 2 and stuck for 3 to 4 min again.
![Screen Shot 2019-06-21 at 11 19 55 AM](https://user-images.githubusercontent.com/19906193/59901480-fc07b400-9418-11e9-8ae5-9420fd28c16c.png)

Stage3: After it, within 1-2 sec It executes till stage 3 and stuck for 3 to 4 min again at this point-

**Comment by mrocklin** [comment]
If you look at the "info" tab on the dashboard you can navigate to one of
the workers and look at the current activity of the threads.  This should
tell you which line of your Pandas code they're stuck on.  That might help
you to discover what is going on.

**Comment by 3ggaurav** [comment]
I did this also, want to navigate workers but not know, what's the problem. In the info window, It is paused at many places Let me show one -
![Screen Shot 2019-06-21 at 11 16 20 AM](https://user-images.githubusercontent.com/19906193/59910518-b86c7480-942f-11e9-878a-0400682d3c74.png)
It paused at this point for 4 min.
![Screen Shot 2019-06-21 at 1 37 02 PM](https://user-images.githubusercontent.com/19906193/59910526-c02c1900-942f-11e9-8c6d-360793448273.png)
![Screen Shot 2019-06-21 at 1 36 45 PM](https://user-images.githubusercontent.com/19906193/59910543-ca4e1780-942f-11e9-99a1-b157c6418292.png)

**Comment by mrocklin** [comment]
You would click on one  of the worker addresses on the left.  Then there is
a button to access stacks or threads or something towards the right of the
page.

**Comment by 3ggaurav** [comment]
See this - 
I run the code 
**len(dataframe)** 
in start It shows as below - 
<img width="540" alt="Screen Shot 2019-06-21 at 2 26 42 PM" src="https://user-images.githubusercontent.com/19906193/59911038-b656e580-9430-11e9-9aea-9ce77d21a65d.png">

as you said I clicked on one worker and then click on stack button - 
It does not show anything.
<img width="715" alt="Screen Shot 2019-06-21 at 2 29 08 PM" src="https://user-images.githubusercontent.com/19906193/59911377-5f054500-9431-11e9-9fa7-946265a285c3.png">
and when I clicked on **call stack** button It shows a web page written this- 
<img width="495" alt="Screen Shot 2019-06-21 at 2 29 25 PM" src="https://user-images.githubusercontent.com/19906193/59911402-6d536100-9431-11e9-81ee-680e2ba041f0.png">

**Comment by mrocklin** [comment]
Yup.  I don't know then.

**Comment by 3ggaurav** [comment]
It's running by taking 2-3 sec processing, 3-3 4-4 minute pauses repeatedly, and complete it in 10-12 min. It's a 2.2GB data with 15 million rows and 19 columns.

**Comment by TomAugspurger** [comment]
FWIW, I don't think https://github.com/dask/dask/issues/4971#issuecomment-504019074 has been definitively answered. If your task takes 2-3 minutes to run, may appear to be "stuck" in the task stream, as those are plotted upon completion. The "Tasks processing" pane show active tasks.

**Comment by jakirkham** [comment]
Any update here, @3ggaurav?

**Comment by TomAugspurger** [comment]
@3ggaurav I'm pretty sure that https://github.com/dask/dask/issues/4971#issuecomment-504433760 is the correct explanation. Let us know if you think otherwise.
