### ISSUE TITLE
Release Version 2.0

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4973]
I think that it would be nice to do a release of both dask and distributed.

This is a larger than normal release for a few reasons:

1.  We've dropped Python 2 in both projects
2.  The meta changes in dask.array are substantial
3.  We've broken quite a few small APIs in distributed

For that reason, I'd like to cut a new major version number, 2, in both projects.  This will also put both projects on the version, which is somewhat convenient (we might keep them in lock-step up to 0.X.0 versions at least in the future).

Before we release I think that there are a few things we should do:

1.  Make sure that important downstream projects are OK.  
    - I think that Xarray will be fine after https://github.com/dask/dask/pull/4954 (cc @shoyer )
    - dask-jobqueue after https://github.com/dask/dask-jobqueue/pull/278
    - @TomAugspurger fixed dask-kubernetes, but it should be co-released 
2.  Consider blackifying dask beforehand
    - If we want to do this we should make an effort to merge in active large PRs.  I think that everything is on track, except perhaps for https://github.com/dask/dask/pull/4877 (@TomAugspurger , if you have time can you take a look?)
3.  Write up a blogpost with the major changes, highlighting breaks
4.  Anything else?

**Comment by mrocklin** [comment]
I've pushed a PR to have Dask sign the Python 3 statement here: https://github.com/python3statement/python3statement.github.io/pull/239

It would be good to get a few other maintainers to +1 that PR

**Comment by shoyer** [comment]
This sounds like a nice plan to me.

**Comment by TomAugspurger** [comment]
+1.

I think https://github.com/dask/dask/pull/4877 can be resolved today.

**Comment by jakirkham** [comment]
If we are going to do a 2.0 release, would this be a good opportunity to change some APIs?

In particular am interested in solving issue ( https://github.com/dask/dask/issues/3641 ). It should be pretty quick to fix if we are ok breaking the API a little bit. This would also allow us to easily generalize the work in PR ( https://github.com/dask/dask/pull/4863 ) to all kinds of paddings, which it doesn't handle currently.

**Comment by jakirkham** [comment]
> If we are going to do a 2.0 release, would this be a good opportunity to change some APIs?

Also if we are comfortable making some API changes in 2.0, would it make sense to push out a minor release with relevant deprecation warnings?

**Comment by jakirkham** [comment]
It might also be a good opportunity to bump our requirements in again.

For instance bumping NumPy aggressively could allow us to clean out a lot of code working around the lack of NEP 18 or `empty_like`. OTOH trying to get rid of all of those workarounds will be a pretty aggressive version bump and may have us waiting for a new NumPy release depending on how many workarounds we want to eliminate. There may be a balance to strike here depending on the community's needs.

Would be curious to hear others thoughts on this. 🙂

**Comment by mrocklin** [comment]
> Also if we are comfortable making some API changes in 2.0, would it make sense to push out a minor release with relevant deprecation warnings?

Personally I'm in favor of "just releasing 2.0".  At this point we would have to walk back to a previous commit before we dropped Python 2 and possibly the meta work, publish a new version with the deprecation warnings, wait a while, then publish 2.0.

I think that this would have been good to do ahead of time but at this stage I think it would take too much developer time.

**Comment by mrocklin** [comment]
> If we are going to do a 2.0 release, would this be a good opportunity to change some APIs?

Yes, I think that now would be a good time to change APIs.

**Comment by mrocklin** [comment]
> For instance bumping NumPy aggressively could allow us to clean out a lot of code working around the lack of NEP 18 or empty_like. OTOH trying to get rid of all of those workarounds will be a pretty aggressive version bump and may have us waiting for a new NumPy release depending on how many workarounds we want to eliminate. There may be a balance to strike here depending on the community's needs.

If you're talking about going all the way to 1.16 or 1.17 then I think that that is probably too aggressive.

**Comment by jakirkham** [comment]
Thanks for the responses. Sounds like there's nothing to do on these then.

**Comment by mrocklin** [comment]
I've pushed up a draft release blogpost here: https://github.com/dask/dask-blog/pull/34

I've also pushed a PR to dask-examples that cleans up some issues there: https://github.com/dask/dask-examples/pull/84

Other than these and black I think we're good?  Anything else I've missed?

**Comment by jakirkham** [comment]
I went ahead and merged PR ( https://github.com/dask/dask/pull/4979 ) as it seemed like we were done there.

**Comment by jakirkham** [comment]
Are we wanting to fix upstream dev failures ( https://github.com/dask/dask/issues/4961 ) before releasing?

**Comment by mrocklin** [comment]
What do you suggest @jakirkham ?

**Comment by TomAugspurger** [comment]
I haven't had time to start that yet, so I'd recommend not worrying about
them. A 2.0.x is easy to do if needed.

**Comment by pentschev** [comment]
On the Dask Array side, there's only one issue, I've commented in #4961, and opened an issue for us to track that in #4994.

**Comment by mrocklin** [comment]
@pentschev should it block the release?  I anticipate that we'll probably have a bugfix 2.0.1 release within a week.

**Comment by mrocklin** [comment]
I've pushed 1.0 versions of `partd` and `zict` to PyPI.

**Comment by pentschev** [comment]
I don't think it will block the release, since, AFAIK, NumPy 1.17 will not be released yet.

**Comment by mrocklin** [comment]
I think we're ready to go.  I'll plan to pull the trigger on this later today.

**Comment by mrocklin** [comment]
Pushed dask/dask and dask/distributed to PyPI

**Comment by mrocklin** [comment]
and dask/dask-kubernetes

**Comment by mrocklin** [comment]
Announced.  Closing.  Thanks all.
