### ISSUE TITLE
Clean up git commits before squash-and-merge

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4985]
Currently we use the Squash and Merge feature of Github to merge PRs into master.  This takes the title of the PR and makes it the title of a new commit, and adds the commit message of every following commit into a list.  When contributors are careful about commits, this results in nicely informative commit messages.  However sometimes contributors aren't that careful, and we end up committing less-than-helpful commit messages.  Here is such an example

```
commit 773f775034f37ce2c5097c51bf05b0a0370f6612
Author: XXXX
Date:   Fri Jun 14 14:34:34 2019 +0000

    4809 fix extra cr (#4935)

    * added test that fails to demonstrate the issue in 4809

    * modfied open_files/OpenFile to accept a newline parameter, similar to io.TextIOWrapper or the builtin open on py3. Pass newline='' to open_files when preparing to write csv files.

    Fixed #4809

    * modified newline documentation to follow convention

    * added blank line to make test_csv.py flake8-compliant
```

I propose that the people who merge the PR take a moment and clean up the commit message.  I suggest the following guidelines:

1.  The title should be informative and concise
2.  The title should be a verb phrase like "Adds the DataFrame.foo method" rather than "adding DataFrame.foo" or "DataFrame.foo method".  I *think* that the verb phrase approach is a standard convention in git
3.  Try to include `Fixes` comments if applicable
4.  Remove unuseful commit lines like "fixup" or "add blank line to make flake8 compliant" .  (Often I find myself nuking all of the commit messages, and writing down a bit of prose myself, or copying the comment in the original post)

cc'ing folks who often merge: @jcrist @jakirkham @TomAugspurger @jrbourbeau @martindurant @quasiben 

I'm open to other conventions, but this is what I've been doing historically and I think it strikes a good balance between being low-effort and making git log inforamative.  I spend on average 10-30s per PR on the commit message.

**Comment by jakirkham** [comment]
Personally I'm not a big fan of merge and squash in the first place as it loses the commit history. That said, this is what devs here have agreed upon and it is a low amount of effort. I think what you are proposing is we spend more time on actively cleaning the history, which I'm even less of a fan of. This mainly because I don't think we should be cleaning up the commit history in the first place.

The only exception in my mind would be updating the PR title and adding fixes notes in the PR OP, which could be reasonable. Though if we do this, I think we should make those changes to the actual PR (not the merge commit GitHub generates) before merging otherwise there is a bit of a disconnect. Namely xrefs between the PR and issues are not added. Also it becomes a little harder to find the related PR.

**Comment by mrocklin** [comment]
> Personally I'm not a big fan of merge and squash in the first place as it loses the commit history

In order to be efficient with time, I think that we should revisit the squash-and-merge conversation in a high bandwidth conversation, perhaps at the next Dask developers meeting at SciPy.  Otherwise I'm afraid that this is likely to be somewhat contentious and a time sink for lots of people, which I'd like to avoid.

> I think what you are proposing is we spend more time on actively cleaning the history, which I'm even less of a fan of.

I think that this takes around 10-30s per PR, which I think is not onerous.

> This mainly because I don't think we should be cleaning up the commit history in the first place.

I think that we need to clean up commits like the following, which I find uninformative:

```
commit 773f775034f37ce2c5097c51bf05b0a0370f6612
Author: XXXX
Date:   Fri Jun 14 14:34:34 2019 +0000

    4809 fix extra cr (#4935)

    * added test that fails to demonstrate the issue in 4809

    * modfied open_files/OpenFile to accept a newline parameter, similar to io.TextIOWrapper or the builtin open on py3. Pass newline='' to open_files when preparing to write csv files.

    Fixed #4809

    * modified newline documentation to follow convention

    * added blank line to make test_csv.py flake8-compliant
```

Either we teach novice contributors to do this or the maintainers do it themselves.  Given the number of novice contributors to this project  I think that it is more efficient with everyone's time if the maintainers do this in a low effort way, like writing in a simple one-line explanation of the PR, and nuking non-informative commit messages.

> The only exception in my mind would be updating the PR title and adding fixes notes in the PR OP, which could be reasonable. Though if we do this, I think we should make those changes to the actual PR (not the merge commit GitHub generates) before merging otherwise there is a bit of a disconnect. 

I'm ok with this.  

> Namely xrefs between the PR and issues are not added. 

I think that it's good to keep references to other PRs and issues in the commit message regardless.

> Also it becomes a little harder to find the related PR.

Squash and merge always includes the PR number in the commit title.  I've never had difficulty finding the PR afterwards, even if the name is changed.

**Comment by jcrist** [comment]
Seems reasonable to me. I personally mostly care about the commit titles - I usually end up looking at the related PR anyway when diving through git history.

**Comment by mrocklin** [comment]
As an example, I just changed this

```
Added melt as a method of Dask DataFrame (#4984)

* - Moved list_eq from test_multi to dataframe/utils testing area
- Moved melt test from test_multi to test_reshape and imported list_eq
- Added additional test for melt as DataFrame method

* Revert "- Moved list_eq from test_multi to dataframe/utils testing area"

This reverts commit 41f8fc97c68ca3b6ed2a3a2ef40782d65f5339cb.

* add test

* apply black

* fixup
```

To this

```
Add melt as a method of Dask DataFrame (#4984)
```

**Comment by TomAugspurger** [comment]
I think our logs are looking nicer now. Closing.
