### ISSUE TITLE
add_worker ERROR

### ISSUE THREAD

**Issue by myairforce1** [dask/dask#4998]
Hi,

I'm trying to use dask distributed across two linux machines but got error. Below is the steps:

1. On 192.168.1.75, run 
dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://192.168.1.75:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-uaj9dxgb
distributed.scheduler - INFO - -----------------------------------------------

2. on 192.168.1.17， run
dask-worker tcp://192.168.1.75:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.1.17:42073'
distributed.diskutils - INFO - Found stale lock file and directory '/home/ubuntu/worker-vndr3mg5', purging
distributed.worker - INFO -       Start worker at:   tcp://192.168.1.17:38075
distributed.worker - INFO -          Listening to:   tcp://192.168.1.17:38075
distributed.worker - INFO -              nanny at:         192.168.1.17:42073
distributed.worker - INFO - Waiting to connect to:    tcp://192.168.1.75:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         12
distributed.worker - INFO -                Memory:                   67.47 GB
distributed.worker - INFO -       Local Directory: /home/ubuntu/worker-e_9hk1mc
distributed.worker - INFO - -------------------------------------------------

3. then on the scheduler machine, an error occurred:
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'types'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tfenv/lib/python3.6/site-packages/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/home/ubuntu/anaconda3/envs/tfenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/ubuntu/anaconda3/envs/tfenv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'types'

The dask version I'm using is '1.2.2'. Thanks for your advice.

Regards
Eric

**Comment by mrocklin** [comment]
It's quite likely that your versions of the `distributed` library differ
between the two machines.

**Comment by myairforce1** [comment]
That's true. One is 1.25, the other is 1.28. Issue solved. Thanks a lot. @mrocklin
