### ISSUE TITLE
to_parquet rainsed RuntimeError: Max number of S3 retries exceeded

### ISSUE THREAD

**Issue by michelleowen** [dask/dask#4999]
When I try to save a dask dataframe to parquet, I got RuntimeError, see details below:
my code: 
`data.to_parquet("hdfs:///user/path_to_data")`

Error:

> ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-43dc1794203c> in <module>
----> 1 data.to_parquet("hdfs:///user/path_to_data")

~/.local/lib/python3.6/site-packages/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
   2904         """ See dd.to_parquet docstring for more information """
   2905         from .io import to_parquet
-> 2906         return to_parquet(self, path, *args, **kwargs)
   2907 
   2908     @derived_from(pd.DataFrame)

~/.local/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in to_parquet(df, path, engine, compression, write_index, append, ignore_divisions, partition_on, storage_options, compute, **kwargs)
   1259 
   1260     if compute:
-> 1261         out.compute()
   1262         return None
   1263     return out

~/.local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/.local/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2566                     should_rejoin = False
   2567             try:
-> 2568                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2569             finally:
   2570                 for f in futures.values():

~/.local/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1820                 direct=direct,
   1821                 local_worker=local_worker,
-> 1822                 asynchronous=asynchronous,
   1823             )
   1824 

~/.local/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    751             return future
    752         else:
--> 753             return sync(self.loop, func, *args, **kwargs)
    754 
    755     def __repr__(self):

~/.local/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    329             e.wait(10)
    330     if error[0]:
--> 331         six.reraise(*error[0])
    332     else:
    333         return result[0]

/usr/lib/python3/dist-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/.local/lib/python3.6/site-packages/distributed/utils.py in f()
    314             if timeout is not None:
    315                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 316             result[0] = yield future
    317         except Exception as exc:
    318             error[0] = sys.exc_info()

/usr/local/lib/python3.6/dist-packages/tornado/gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

/usr/local/lib/python3.6/dist-packages/tornado/gen.py in run(self)
    734                     if exc_info is not None:
    735                         try:
--> 736                             yielded = self.gen.throw(*exc_info)  # type: ignore
    737                         finally:
    738                             # Break up a reference to itself

~/.local/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1651                             six.reraise(CancelledError, CancelledError(key), None)
   1652                         else:
-> 1653                             six.reraise(type(exception), exception, traceback)
   1654                     if errors == "skip":
   1655                         bad_keys.add(key)

/usr/lib/python3/dist-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

~/.local/lib/python3.6/site-packages/dask/bytes/core.py in read_block_from_file()
    138 def read_block_from_file(lazy_file, off, bs, delimiter):
    139     with copy.copy(lazy_file) as f:
--> 140         return read_block(f, off, bs, delimiter)
    141 
    142 

~/.local/lib/python3.6/site-packages/dask/bytes/utils.py in read_block()
    217 
    218     if not offset and length is None and f.tell() == 0:
--> 219         return f.read()
    220 
    221     if delimiter:

/usr/lib/python3.6/gzip.py in read()
    274             import errno
    275             raise OSError(errno.EBADF, "read() on write-only GzipFile object")
--> 276         return self._buffer.read(size)
    277 
    278     def read1(self, size=-1):

/usr/lib/python3.6/gzip.py in read()
    461                 # jump to the next member, if there is one.
    462                 self._init_read()
--> 463                 if not self._read_gzip_header():
    464                     self._size = self._pos
    465                     return b""

/usr/lib/python3.6/gzip.py in _read_gzip_header()
    404 
    405     def _read_gzip_header(self):
--> 406         magic = self._fp.read(2)
    407         if magic == b'':
    408             return False

/usr/lib/python3.6/gzip.py in read()
     89             self._read = None
     90             return self._buffer[read:] + \
---> 91                    self.file.read(size-self._length+read)
     92 
     93     def prepend(self, prepend=b''):

~/.local/lib/python3.6/site-packages/s3fs/core.py in read()
   1331         if self.closed:
   1332             raise ValueError('I/O operation on closed file.')
-> 1333         self._fetch(self.loc, self.loc + length)
   1334         out = self.cache[self.loc - self.start:
   1335                          self.loc - self.start + length]

~/.local/lib/python3.6/site-packages/s3fs/core.py in _fetch()
   1295             self.cache = _fetch_range(self.s3.s3, self.bucket, self.key,
   1296                                       version_id, start, self.end,
-> 1297                                       req_kw=self.s3.req_kw)
   1298         if start < self.start:
   1299             if not self.fill_cache and end + self.blocksize < self.start:

~/.local/lib/python3.6/site-packages/s3fs/core.py in _fetch_range()
   1542             else:
   1543                 raise
-> 1544     raise RuntimeError("Max number of S3 retries exceeded")

RuntimeError: Max number of S3 retries exceeded

**Comment by martindurant** [comment]
It appears from your traceback that the error is in fact happening during reading. It would be for the best if you could a version of the code which causes this problem (minimal, complete, verifiable example)

I gather you are using read_csv on something which is gzipped
- are you sure your S3 files are accessible to you? You could test this using s3fs directly
- since the files are gzipped, random access within a file is not possible, and you need to use a blocksize of None (one partition per file)

**Comment by michelleowen** [comment]
@martindurant, I did data.count().compute() and it works fine though. 

Below is complete code:
`!pip3 install distributed --user
import boto3
from boto3 import Session
from functools import partialmethod
import re
import pandas as pd
Session.client = partialmethod(Session.client, endpoint_url=os.environ["BCS_HOST"])

from distributed import Client
client = Client()
from dask import dataframe as dd

transaction = dd.read_csv(
    "s3://path_to_file/*.transactionHistory_part_*.csv.gz", 
    sep="\t",
    compression="gzip",
    storage_options={"client_kwargs": {"endpoint_url": os.environ["BCS_HOST"]}}
)

vendor = dd.read_csv(
    "s3://path_to_file/*.vendorHistory_part_*.csv.gz", 
    sep="\t",
    compression="gzip",
    storage_options={"client_kwargs": {"endpoint_url": os.environ["BCS_HOST"]}}
)

vendor = vendor[vendor.name.notnull()]
vendor_sec = vendor[vendor.name.str.match('^\D')]

data = transaction.merge(vendor_sec, on="vendor_key")
data = data[data.contract_end_date>="2007-01-01"]

data.to_parquet("hdfs:///user/path_to_data")
`

**Comment by michelleowen** [comment]
I tried the same command again and it works somehow. It was a transient error...
