### ISSUE TITLE
Dask User Survey

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#5004]
The 2019 Dask User Survey is currently live at https://t.co/OGrIjTLC2G

This takes 5-10 minutes and impacts our future direction.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/pull/5147 and https://github.com/dask/dask.github.io/pull/15 update the docs and website to remove links to the survey.

I've stopped accepting responses on the Google form.

I'll write up a summary of the results.

**Comment by jrbourbeau** [comment]
Closing this issue as #5147 and dask/dask.github.io#15 have been merged
