### ISSUE TITLE
where is the docs of dask 2.0

### ISSUE THREAD

**Issue by jmsking** [dask/dask#5005]
Hello~
today i find the merge of the dask with version 2.0, but i can not find the docs in
websit: https://docs.dask.org/en/latest
therefore, I want to know where can i find the docs of dask 2.0 ?
Thanks so much!

**Comment by TomAugspurger** [comment]
They're at `/latest`. See, e.g.
https://docs.dask.org/en/latest/changelog.html

**Comment by jmsking** [comment]
Oohh~
Thanks so much~
