### ISSUE TITLE
Concatenate Array[sparse] raises ValueError

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#5008]
This happens during metadata validation.

```python
In [56]: import scipy.sparse

In [57]: import dask.array as da

In [58]: a = scipy.sparse.random(4, 3, format='csr')

In [59]: meta = scipy.sparse.eye(0).asformat('csr')

In [60]: b = da.from_array(a, meta=meta)

In [61]: b
Out[61]: dask.array<array, shape=(4, 3), dtype=float64, chunksize=(4, 3)>

In [62]: da.concatenate([b], axis=1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-4bf3ad9a8a86> in <module>
----> 1 da.concatenate([b], axis=1).compute()

~/Envs/dask-dev/lib/python3.7/site-packages/dask/array/core.py in concatenate(seq, axis, allow_unknown_chunksizes)
   3232         raise ValueError("Need array(s) to concatenate")
   3233
-> 3234     meta = np.concatenate([meta_from_array(s) for s in seq], axis=axis)
   3235
   3236     # Promote types to match meta

ValueError: zero-dimensional arrays cannot be concatenated
```

Is this something we want to support? Came up in https://github.com/dask/dask-ml/pull/529

**Comment by TomAugspurger** [comment]
cc @pentschev (and @jakirkham, I don't think https://github.com/dask/dask/pull/4978 fixes this, right?)

**Comment by TomAugspurger** [comment]
So I suppose the thing to do is use `pydata/sparse` in dask_ml instead.

**Comment by pentschev** [comment]
IMO, this is a SciPy Sparse bug, and the best would be to fix it there. That works on both NumPy and PyData Sparse.

However, we could add a workaround on Dask to allow it to pass on `ValueError` and adjust `_meta` to the best of its capability (e.g., ensure dimensions are correct) instead. I think the best is to do this anyway, but we should perhaps add a warning (at least for developers) to make it easier to track in the future.

@TomAugspurger I have one additional question though, did you pass `meta=meta` for a particular reason? If you don't, `_meta` is inferred automatically from the array, and it worked as expected in the sample you posted.

**Comment by TomAugspurger** [comment]
>  I have one additional question though, did you pass meta=meta for a particular reason?

I did that to match the `meta` from the original dask-ml issue. I haven't looked into whether that's correct or not.

I think the best path forward is for dask-ml to shift to using pydata/sparse: https://github.com/dask/dask-ml/issues/123

**Comment by jakirkham** [comment]
> @jakirkham, I don't think #4978 fixes this, right?

That's unrelated.

**Comment by pentschev** [comment]
If the set of implemented functions suffice, I don't see why not switching to pydata/sparse. :)

If we would like to support scipy sparse anyway, I can also push a fix to this concatenation issue, should be fairly straightforward.

**Comment by jakirkham** [comment]
FWIW I raised issue ( https://github.com/scipy/scipy/issues/10362 ) to discuss extending NEP 18 to SciPy sparse matrices.

**Comment by jakirkham** [comment]
@TomAugspurger, do you know what other Dask Array operations you are using with SciPy sparse matrices?

**Comment by jakirkham** [comment]
It sounds like SciPy is advocating the move to Sparse as well. As we also seem to agree on that here, maybe we can just figure out what it takes to get dask-ml using Sparse?

**Comment by pentschev** [comment]
Sounds good to me.

For completeness, quoting the SciPy plan here from https://github.com/scipy/scipy/issues/10362: http://scipy.github.io/devdocs/roadmap.html#implement-sparse-arrays-in-addition-to-sparse-matrices

Thanks @jakirkham for raising the conversation with SciPy!

**Comment by TomAugspurger** [comment]
Let me dig into exactly why I ended up with that `_meta` in the first place.

**Comment by TomAugspurger** [comment]
Here's a somewhat more minimal example


```python
import numpy as np
import dask.array as da
import scipy.sparse

def _construct(x, categories):
    # type: (np.ndarray, np.ndarray) -> scipy.sparse.csr_matrix
    data = np.ones(len(x))
    rows = np.arange(len(x))
    columns = x.ravel()
    return scipy.sparse.csr_matrix(
        (data, (rows, columns)), shape=(len(x), len(categories))
    )


x = da.from_array(np.array([0, 0, 1, 2, 3]), chunks=2)
xs = x.map_blocks(_construct, ['a', 'b', 'c', 'd'], new_axis=1, chunks=(x.chunks[0], (4,)))

da.concatenate([xs])
```

**Comment by jakirkham** [comment]
Could you please point us to where this is being used in dask-ml?

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask-ml/blob/0f26eb47f14e747a4dc55c81b2c440688cde2d64/dask_ml/preprocessing/label.py#L241
via
https://github.com/dask/dask-ml/blob/0f26eb47f14e747a4dc55c81b2c440688cde2d64/dask_ml/preprocessing/label.py#L14

**Comment by jakirkham** [comment]
Actually as we are [defining our own `concatenate` SciPy sparse matrices]( https://github.com/dask/dask/blob/4d7e674189ed2473ea2dcc2ddf3536e519bd1da5/dask/array/backends.py#L61-L71 ), it makes sense that we fix this here in Dask. Maybe we can use our own lookup method for the metas here? Trying that in PR ( https://github.com/dask/dask/pull/6339 ).
