### ISSUE TITLE
Wiki page is empty!

### ISSUE THREAD

**Issue by Pranay144** [dask/dask#5019]
Should i work on wiki page of Dask on gitbub.
Its pretty empty!

**Comment by TomAugspurger** [comment]
Is there something specific you had in mind? We prefer that most things go in the documentation on dask.org.

**Comment by Pranay144** [comment]
we can put use cases and tutorials of Dask on wiki page.

**Comment by TomAugspurger** [comment]
See https://github.com/dask/dask/issues/5017 for educational materials.

Personally, I prefer having everything in one place, which would have to be the main sphinx documentation.

**Comment by jakirkham** [comment]
We could hide the wiki (given we don't use it). Would that address this issue?

**Comment by mrocklin** [comment]
+1

**Comment by TomAugspurger** [comment]
@Pranay144 I'll close this then. If you're interested in contributing to how the educational materials are presented, we'd welcome input on https://github.com/dask/dask/issues/5017

**Comment by Pranay144** [comment]
@TomAugspurger sure, I'm looking forward contributing to Dask.
