### ISSUE TITLE
Support zstandard compression for file formats

### ISSUE THREAD

**Issue by jcrist** [dask/dask#5039]
It would be useful to support reading files compressed with zstandard in our file IO routines. The appropriate code would be added [here](https://github.com/dask/dask/blob/master/dask/bytes/compression.py), and should only add support if the required library dependency is available (similar to `snappy`).

**Comment by Pranay144** [comment]
i can take this issue.
@jcrist please tell me how to proceed?

**Comment by jcrist** [comment]
Sure! You'll want to mirror the implementation for `snappy`here , but for `zstandard`.

https://github.com/dask/dask/blob/140a27b57dfe0c3a5a694e04c3c0cd07412d56eb/dask/bytes/compression.py#L32-L38

The key should be `zstd` (the name of the compression algorithm), and the values should be the compression/decompression functions. It looks like [this](https://github.com/indygreg/python-zstandard) is the most popular zstandard library for python. It doesn't provide methods with the signature we want, so you'll have to implement them yourself. For compression this might look like:

```python
import zstandard

def zstd_compress(data):
    c = zstandard.ZstdCompressor()
    return c.compress(data)
```

The decompression function would look similar.

For instructions on getting started with development of dask, see https://docs.dask.org/en/latest/develop.html#development-environment.

**Comment by quasiben** [comment]
@Pranay144 any updates on adding a PR for this issue ?

**Comment by jcrist** [comment]
See the discussion at https://github.com/dask/dask/pull/5095, looks like @martindurant disagrees about this feature.

@martindurant - if we're moving to `fsspec` as a dependency for handling these things, would you see this as in-scope for `fsspec`? People do store data as compressed `zstd` files, and this would be something we should handle.

**Comment by martindurant** [comment]
Yes, it would be in https://github.com/intake/filesystem_spec/blob/master/fsspec/compression.py
Dask does explicitly test all the compressions in the context of bag text and dataframe csvs.

**Comment by quasiben** [comment]
Ah, didn't see the PR.  Apologies.

**Comment by brl0** [comment]
Perhaps this should be closed?
See https://github.com/intake/filesystem_spec/issues/69

**Comment by jcrist** [comment]
Yep, this can be closed. Thanks for the ping.
