### ISSUE TITLE
Dask doesn't work with pyarrow > 0.12.1

### ISSUE THREAD

**Issue by dclong** [dask/dask#5040]
## Code Example

I have dask 2.0.0 and pyarrow 0.13.0 installed. I got an error message saying that "Please install either fastparquet or pyarrow when reading a parquet file using dask. Downgrading pyarrow to 0.12.1 works. 
```
import dask.dataframe as dd
dd.read_parquet('/path/to/parquet/file')
```

**Comment by TomAugspurger** [comment]
Working on this in https://github.com/dask/dask/pull/4995 I believe. I don't see a specific issue for this, so we'll leave this one open.

**Comment by rjzamora** [comment]
I don't believe there is any plan to support pyarrow 0.13.0, but 0.13.1 should work both now and after the refactor.  With that said, 0.13.1 will probably require you to build pyarrow from source until a pip/conda package becomes available.

**Comment by dclong** [comment]
@rjzamora Thank you! I won't bother to compile from the source code by myself. I will use 0.12.1 until 0.13.1 is available on PyPi.
