### ISSUE TITLE
On large data, len() gets much slower or fails entirely after dask 1.2.0/distributed 1.27.0

### ISSUE THREAD

**Issue by athornton** [dask/dask#5054]
2.  **Bug report:** 

    -  I don't have a great minimal example yet.  The symptom is that, in my dask setup in a JupyterHub+Jupyterlab+Kubernetes deployment, the dask dashboard loses connection with its workers.  This did not happen with dask 1.2.0  and distributed 1.27.0.  It appears to happen at dask 1.2.1 and distributed 1.27.1 and all later versions (including 2.0).  Although dask-kubernetes has evolved since then, it didn't change when the connection loss started appearing (it was at 0.7.0 then).  This is particularly strange since it looks like the changes in dask and distributed were purely cleaning up quote mark types and spacing.

    -  This can be demonstrated if you use the notebook:
https://github.com/lsst-sqre/notebook-demo/blob/master/experiments/DASK-notebooks/gaia_all_sky.ipynb ; however, this example uses the PyPi repo "jupyterlabutils" in order to proxy the worker and status dashboards through jupyter-server-proxy.  If you're not running under Kubernetes (and I don't *think* k8s is implicated here), you can probably use the standard client and cluster classes.  Anyway, to replicate, use gcsfs and the GCS bucket gcs://jupyterlabdemo-gaia-dr2/gaia_source.parquet.  There's a persist() step, and then after that a cell where we use the %%time magic to time calculating the dataframe length.  That len(df) call will hang within the first five times you invoke it if it's going to (just keep re-executing the cell).  The symptom is that the len() doesn't return, and the dask progress graph and memory consumption (which are the two I usually have open) just stop updating.

    -  I'll try to get a more minimal example, but I am pretty sure this is only going to show up on large datasets.

**Comment by athornton** [comment]
The slowness is real.  The hanging seems to be related to the `%%time` magic?  This is very weird.

**Comment by martindurant** [comment]
Does the dashboard reveal what workers are busy doing on the profile tab?
Or are you suspecting that the cluster is doing nothing? I have tried, and even from my laptop, I can create the dataframe from the GCS data, and load the first partition's worth.

**Comment by athornton** [comment]
I just managed to trigger it without a `%%time`.  It happened, in this case, on the fourth run of the `len(df)` cell in fairly rapid succession.

The dashboard makes it look like everything completed, but the cell never returns.

<img width="1003" alt="Screen Shot 2019-07-02 at 2 14 52 PM" src="https://user-images.githubusercontent.com/2453165/60547155-dcec0a80-9cd3-11e9-9838-c6f40eb83a57.png">

**Comment by dhirschfeld** [comment]
Do you have the Variable Inspector extension? That was previously implicated in performance issues:
https://github.com/lckr/jupyterlab-variableInspector/issues/59#issuecomment-433009643

...though that was supposed to have been fixed. Anyway, since it sounds pretty strange it might be worthwhile trying without any other extensions active.

**Comment by dhirschfeld** [comment]
*Probably* not related, but just in case:
https://github.com/ipython/ipython/pull/11812

**Comment by martindurant** [comment]
Indeed, it hadn't occurred to me, but @dhirschfeld has a point, it would be well worthwhile trying the code in a console with no jupyter stuff in the way at all. 
As usual, it would be a good idea to check the scheduler and worker logs for any output.

**Comment by SimonKrughoff** [comment]
Just dropping a note here that I have been doing a little more looking into this.  I have not been able to trigger the behavior directly from a python interpreter running in a terminal.  I'll post back when I have more info.

**Comment by athornton** [comment]
Now we're pursuing a hypothesis that it's actually related to the proxying we're doing to be able to get the dashboards to the end-user (via jupyter-server-proxy).

**Comment by athornton** [comment]
Still not a lot closer, but I have found, if you interrupt the hanging `len()` call, you get:

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-18-9e112543b788> in <module>
----> 1 len(df)

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
    510     def __len__(self):
    511         return self.reduction(
--> 512             len, np.sum, token="len", meta=int, split_every=False
    513         ).compute()
    514 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2525                     should_rejoin = False
   2526             try:
-> 2527                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2528             finally:
   2529                 for f in futures.values():

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1821                 direct=direct,
   1822                 local_worker=local_worker,
-> 1823                 asynchronous=asynchronous,
   1824             )
   1825 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    761         else:
    762             return sync(
--> 763                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    764             )
    765 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    328     else:
    329         while not e.is_set():
--> 330             e.wait(10)
    331     if error[0]:
    332         six.reraise(*error[0])

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554 

/opt/lsst/software/stack/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/threading.py in wait(self, timeout)
    298             else:
    299                 if timeout > 0:
--> 300                     gotit = waiter.acquire(True, timeout)
    301                 else:
    302                     gotit = waiter.acquire(False)

KeyboardInterrupt: 
```

So I think what's happening is that we get stuck in that wait loop forever called from `sync()` because it's defaulting callback_timeout to `None` ?

**Comment by athornton** [comment]
I suspect this is a subtle bug in either jupyter-server-proxy or in maproxy, or in my use of those classes.

It doesn't seem to exist when I'm not using my wrapper classes.

I've worked around it by adding a timeout with exponential backoff up to a maximum to sync(): see https://github.com/lsst-sqre/jupyterlabutils/blob/2d3757695fe3d731192c176d52c92ce9afab3640/jupyterlabutils/notebook/lsstdaskclient.py#L33

Probably close this?  I have an efficacious-if-gross workaround.

**Comment by athornton** [comment]
I'm going to close this particular one, but there is still an underlying issue.  See dask/distributed #2880 (https://github.com/dask/distributed/issues/2880)
