### ISSUE TITLE
Implement np.median along an axis

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5062]
Should we implement `np.median` in dask array, provided that it is along an axis that is unchunked?  This would be similar to how we handle `da.linalg.fft`

**Comment by nmiles2718** [comment]
Yes! This would be very useful in the field of astronomy. A typical use case is median combining a stack images which can be very memory and CPU intensive depending on the imager. 

I have a MWE for the implementation thanks to some debugging help from @jrbourbeau:
```python
import dask.array as da
import numpy as np 

example = da.linspace(1,81,81)
example_reshaped = example.reshape((9,3,3))
example_chunked = example_reshaped.rechunk((9,1,1))

dask_example_median = da.map_blocks(np.median,  
                                example_chunked,
                                axis=0,
                                chunks=(1,1),
                                drop_axis=0)

dask_med = dask_example_median.compute()
np_med = np.median(example_reshaped, axis=0)
assert (dask_med - np_med).sum() == 0
```

I will follow your suggestion from yesterday @mrocklin to document this behavior in a manner similar to `da.linalg.fft`.

**Comment by mrocklin** [comment]
Given the complexity around handling `axis=` and `keepdims=` I wonder if using `da.reduction` would be more robust to various combinations of keyword arguments.  It might be worth trying out as well.

**Comment by jrbourbeau** [comment]
@nmiles2718 glad to hear this will be of use! Any interest in submitting a PR? I'm happy to review / help out

**Comment by nmiles2718** [comment]
Yeah, definitely! I'm going to try and implement it using `da.reduction` first, but after that I'll submit a PR from my fork. I'm sure I'll have some questions, so stay tuned. lol

**Comment by jrbourbeau** [comment]
Will do, thanks :+1:

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/5575
