### ISSUE TITLE
Dataframe.loc is slow when there's a lot of columns

### ISSUE THREAD

**Issue by tshatrov** [dask/dask#5069]
Suppose I have a dask dataframe with lots of columns, all of them of float dtype. `_meta_nonempty` creates each column separately and then makes a dataframe out of it. This makes some operations surprisingly slow, such as `loc`. I see some issues with this:

1) `_meta_nonempty` can be optimized for some dataframes.
2) `loc` shouldn't require `_meta_nonempty` in the first place. It only needs `self.obj._meta_nonempty.index` which doesn't require recreating all these columns.

```
import pandas as pd
import dask.dataframe as dd

data = {}
for i in range(10000):
   data["col"+str(i)] = [1.0] * 10
df = pd.DataFrame(data)
ddf = dd.from_pandas(df, npartitions=1)

# any loc on ddf takes several seconds because of slow _meta_nonempty construction
%time dloc = ddf.loc[0]   # 2.82s
%time dmeta = ddf._meta_nonempty    # 2.87s

# loc works near-instantly on the original dataframe
%time loc = df.loc[0]   #  1.69ms
```

**Comment by mrocklin** [comment]
> This makes some operations surprisingly slow, such as loc.

Indeed.  That's surprising.  Thanks for bringing this up.

> _meta_nonempty can be optimized for some dataframes.

I agree that that would be great.

> loc shouldn't require _meta_nonempty in the first place. It only needs self.obj._meta_nonempty.index which doesn't require recreating all these columns.

That seems reasonable to me.  I wonder if there are other cases like this as well.

**Comment by quasiben** [comment]
@tshatrov thanks for identifying an optimization!  Any interest in submitting a PR ?  This would be a great first issue to get involved with dask dataframe!

**Comment by iamrajhans** [comment]
@quasiben I would like to take this

**Comment by petioptrv** [comment]
Hi @iamrajhans, are you still working on this? If not, do you mind if I take a crack at it?

**Comment by iamrajhans** [comment]
@petioptrv yeah, go ahead.
