### ISSUE TITLE
ValueError exception when appending dataframes in Dask 2.0.0

### ISSUE THREAD

**Issue by gilacop** [dask/dask#5077]
2.  **Bug report:** 
I have dask 2.0.0, dask-core 2.0.0, dask_yarn 0.6.1 installed. 
When I try to append a df to another df like this:
       df_all = df_all.clear_devisions().append(df_partial)
or 
       df_all = df_all.append(df_partial)
I get the following error message:

       "ValueError: The truth value of a series is ambigious. Use a.empty(), a.bool() or a.all()"

df_all and df_partial have the exact same structure (columns), and no mask is applied to them. 
I tried to reset_index on both dataframes and then append and I get the same error.

Regards

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by gilacop** [comment]
It seems to be working when I sent the parameter interleave_partitions=True as follows:
    df_all = df_all.append(df_partial, interleave_partitions=True)

However, if using the default index (1..n), the result contains duplicate indexes, and you might need to handle it as well (simple reset_index(drop=True) worked for me).
