### ISSUE TITLE
[QST] Is Dask an acronym?

### ISSUE THREAD

**Issue by ksangeek** [dask/dask#5081]
**General Question**

I tried searching around the Internet to find if DASK is an acronym or some random name, and didn't find a satisfactory answer. I thought this would be a better place for asking than in SO! Can someone help me with this?

P.S.
This closest I inferred based on the understanding of this library is "Dynamic tAsk SKheduling"!

**Comment by mrocklin** [comment]
Nope.  Dask is just a name.

> This closest I inferred based on the understanding of this library is "Dynamic tAsk SKheduling"!

Yes, there are many such interpretations that seem reasonable.  Feel free to pick one :)
