### ISSUE TITLE
NumFocus affiliation

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5082]
We are now officially a NumFOCUS sponsored project.  We should advertise this accordingly.

**Comment by jakirkham** [comment]
Where should we advertise? Near the "Supported By" section of the home page? Other places?

**Comment by quasiben** [comment]
I think we should do two things:
- add to the supported by section as @jakirkham noted
- ping numfocus about moving dask from the affiliated page to the [sponsored page](https://numfocus.org/sponsored-projects?_sft_project_category=python-interface)
- tweet about it after the changes go through and why this is impactful

**Comment by jrbourbeau** [comment]
Closing as all the items on @quasiben's list have been done
