### ISSUE TITLE
map_blocks with change of dimensions returns IndexError: tuple index out of range

### ISSUE THREAD

**Issue by nocrosstalk** [dask/dask#5083]
Not sure if this is a bug or incorrect use. The following code returns an error, I don't get why:

```
import dask
import dask.array as da
from numpy import median,array

def func(a):
    m = median(a)
    print(m)
    return array(m)

x = da.random.random((10000, 10000), chunks=(5000, 5000))

x.map_blocks(func,chunks=(1,1)).compute()
```

The output:

```
nan
0.5001597269075302
0.49996143572562185
0.49994227403711916
0.5001512434686584
Traceback (most recent call last):
  ...
    result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
IndexError: tuple index out of range
```

**Comment by pentschev** [comment]
I believe this is incorrect use, `map_blocks` needs to keep the number of dimensions, which `np.median` only does if you pass `keepdims=True`, and if you do that on your example, there will be no exceptions being thrown, but the result is still not what you are probably expecting. You will then have an array of shape `(2,2)` composed of 4 chunks of shape `(1,1)`. Of course, you could now rechunk that array to a single-chunk array and apply the same procedure, but this will likely be inefficient.

For efficient reductions in Dask, each operation has its own specialization, but I don't know why there's not one for median, perhaps it's not used that commonly in Dask.

**Comment by quakberto** [comment]
This was answered on stackoverflow: https://stackoverflow.com/questions/8885663/how-to-format-a-floating-number-to-fixed-width-in-python

**Comment by pentschev** [comment]
Thanks @m-albert.

If your question has been answered, feel free to close this @nocrosstalk.

**Comment by nocrosstalk** [comment]
Thank's all, yes, teh answer on stackoverlof worked.
