### ISSUE TITLE
When Using dask locally I get "ERROR - Workers don't have promised key”

### ISSUE THREAD

**Issue by nbmorgan** [dask/dask#5085]
This is half bug & half feature request.

When using dask locally and starting with just
```
import dask
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster

client = Client(
    n_workers=6, 
    threads_per_worker=4,
    memory_limit='8GB',
    processes=True, 
)
```

Then when I start using daskdataframe I get error output that contains: "ERROR - Workers don't have promised key"

After much, much, digging and trying to use ipyparallel with become dask, I figured out that my hostname was not resolving via DNS.  This was related to a VPN issue.

Request: Can we get an error message on the local cluster creation if the hostname does not resolve or switch to using localhost with a warning.

Thanks.

**Comment by quasiben** [comment]
@nbmorgan thanks for the note -- can you should the output of what happens when you start the cluster ?

Also, note that you can use `LocalCluster` to start things up:

```
In [1]: import dask
   ...: import dask.dataframe as dd
   ...: from dask.distributed import Client, LocalCluster

In [2]: cluster = LocalCluster()

In [3]: client = Client(cluster)

In [4]: client
Out[4]: <Client: scheduler='tcp://127.0.0.1:64550' processes=4 cores=12>
```

**Comment by nbmorgan** [comment]
I will when the error reproduces on the VPN

**Comment by nbmorgan** [comment]
Here is the error: 
<code bgcolor="pink"><pre>
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://43.148.8.41:53342'], ('head-1-2-from-delayed-fdbb442fbc7d89fd936004b0ecbb2d6b', 0)
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('head-1-2-from-delayed-fdbb442fbc7d89fd936004b0ecbb2d6b', 0)": ('tcp://43.148.8.41:53342',)}
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://43.148.8.41:53344'], ('head-1-2-from-delayed-fdbb442fbc7d89fd936004b0ecbb2d6b', 0)
...
</pre></code>
The block with the warning repeats

I tried setting host to localhost to no avail

```python
#Start Dask
#{'inc-1', 'inc-2'}
#client = Client(address='localhost:3110')
client = Client(
    n_workers=6, 
    threads_per_worker=4,
    memory_limit='8GB',
    host='localhost',
    processes=True, 
#    scheduler_port=3110, 
#    dashboard_address=':3787',
#    asynchronous=True,
)

client
```

**Comment by nbmorgan** [comment]
Just tried the following to no avail

```python
#Start Dask
#{'inc-1', 'inc-2'}
#client = Client(address='localhost:3110')
client = Client(
    address=LocalCluster(
        n_workers=6, 
        threads_per_worker=4,
        memory_limit='8GB',
        host='localhost',
        processes=True, 
#       scheduler_port=3110, 
#       dashboard_address=':3787',
#       asynchronous=True,
    )
)

client
```

**Comment by nbmorgan** [comment]
Got working again I think the default interface of 'lo' does not work on BSD flavored unixen. For these system (Like MacOS) you need to use 'lo0' as the default. 

My fix is:
```python
cluster = LocalCluster(
        n_workers=6, 
        threads_per_worker=4,
        memory_limit='8GB',
        interface='lo0' # This is the magic line
    )

client = Client(
    address=cluster.scheduler_address,
)

client

```

**Comment by pseudotensor** [comment]
```
distributed.scheduler - ERROR - Couldn't gather keys {"('from_array-d453264eae73c184f6f797cdd9b55592', 0)": ['ucx://127.0.0.1:40691']} state: ['memory'] workers: [] 
NoneType: None 
distributed.scheduler - ERROR - Workers don't have promised key: ['ucx://127.0.0.1:40691'], ('from_array-d453264eae73c184f6f797cdd9b55592', 0) 
NoneType: None 
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('from_array-d453264eae73c184f6f797cdd9b55592', 0)": ('ucx://127.0.0.1:40691',)} 
```

Hitting this as well.  How to diagnose?

I'm running xgboost with local dask_cuda cluster and see this every so often.  It only started, I think, once I stopped using dask_cuda.read_csv and started passing a dask dataframe using from_array() for a numpy array.  Maybe related to fact that now has to go from CPU -> GPU indirectly?

**Comment by jsignell** [comment]
Did the fix suggested in https://github.com/dask/dask/issues/5085#issuecomment-513043034 help at all @pseudotensor?

**Comment by pseudotensor** [comment]
I had to stick with tcp protocol for now for general stability reasons with ucx, so I haven't tried again.    I'll try upgrading to rapids 0.16/py38/cuda10.2 and see how that does with ucx.

**Comment by AaEll** [comment]
I found that this issue came up when completing a shuffle operation with many keys. In my case, over 10 million. I remedied this by defining a key-group column and then doing the shuffle on that key-group.

**Comment by uchennailodigwe** [comment]
> I had to stick with tcp protocol for now for general stability reasons with ucx, so I haven't tried again. I'll try upgrading to rapids 0.16/py38/cuda10.2 and see how that does with ucx.

Hi, were you finally able to implement this?

**Comment by jsignell** [comment]
I am going to close this issue for now, but if anyone runs into it again, please reopen1

**Comment by achangani** [comment]
> Got working again I think the default interface of 'lo' does not work on BSD flavored unixen. For these system (Like MacOS) you need to use 'lo0' as the default.
> 
> My fix is:
> 
> ```python
> cluster = LocalCluster(
>         n_workers=6, 
>         threads_per_worker=4,
>         memory_limit='8GB',
>         interface='lo0' # This is the magic line
>     )
> 
> client = Client(
>     address=cluster.scheduler_address,
> )
> 
> client
> ```

Tried that but getting this error on dask version 2022.02.1
ValueError: 'lo0' is not a valid network interface. Valid network interfaces are: ['lo', 'ens5']

**Comment by ncclementi** [comment]
@achangani That version of Dask is a year old, I would recommend upgrading the version to it's latest release. If you still have the problem, I would suggest you open a separate issue with a Minimal reproducible example.
