### ISSUE TITLE
In-memory cache for data on workers that won’t be moved / persisted

### ISSUE THREAD

**Issue by cjnolet** [dask/dask#5091]
For cuML’s new communicator abstraction, we are using Dask to bootstrap NCCL and UCX communicators so that we can pass their pointers down through Cython. 

We have implemented this by submitting tasks to the workers and holding onto the resulting futures on the client for submitting subsequent tasks that use the comms. 

I believe this design has the drawback that the ‘data’ cache on the workers could be serialized at any point and moved to disk or to another worker. 

As far as I know, there is no way to store this data on the workers that guarantee’s it will never be moved or serialized to disk. 

It would be nice if the workers provided some small local cache, maybe another dict along side the ‘data’ dict, for lightweight objects with the guarantee that its contents will not get serialized, persisted, or moved around.

If there’s a different / better way to accomplish this, I’m interested in discussing them.

**Comment by mrocklin** [comment]
One common approach is to attach data to the worker.

```python
from dask.distributed import get_worker

```python
def get_comm_state():
    worker = get_worker()  # get a handle to the worker in whiich this task is running
    if not hasattr(worker, "_cuml_comm_state"):
        worker._cuml_comm_state = ...
    return worker._cuml_comm_state
```

Then you call this function whenever you need this state.

Would an approach like this work for you?  Or, more generally, you don't need to handle *all* of your state through Dask.  You can use general Python tricks as well.

**Comment by cjnolet** [comment]
I have implemented this approach and it works well. This option never occurred to me, I think because I'm naturally hesitant to modify objects I don't own. I will use this solution, since it does allow us to maintain our state directly on the worker.

Thanks again, Matt!
