### ISSUE TITLE
Dask install documentation in `Development Guides' is incomplete

### ISSUE THREAD

**Issue by jekwatt** [dask/dask#5100]
Following the instruction to `Install Dask and dependencies` and `additional additional dependencies` caused lots of failing tests.  I ended up removing the dask_env directory and creating a new dask_env by using `continuous_integration/travis/travis-37.yaml`.

Here are the steps I used

Set up your fork for local development:
- conda env create --name dask_env --file continuous_integration/travis/travis-37.yam
- conda activate dask_env

Install Dask and dependencies:
- conda install -y numpy pandas scipy bokeh
- conda install pytest moto mock
- conda install toolz
- pip install -e .

Run Tests:
-  py.test dask --verbose --doctest-modules

**Comment by TomAugspurger** [comment]
> Following the instruction to Install Dask and dependencies and additional additional dependencies caused lots of failing tests.

Are you referring to the docs at https://docs.dask.org/en/latest/develop.html#install?

> caused lots of failing tests.

I notice you're passing `--doctest-modules` to run the doctests. For the unit tests, we should be skipping on failed import of an optional dependency. I don't know of a way to do that for doctests (do you know?). If not, we should note in the docs that one of the CI files can be used to install an environment with all the dependencies, as you've donee

**Comment by jcrist** [comment]
>  I don't know of a way to do that for doctests (do you know?)

This is not possible, as doctests just rely on python's builtin doctest module.

If you'd like to submit a PR updating our developer docs, we'd be happy for a fix.

**Comment by jekwatt** [comment]
Yes, I am referring to the docs at https://docs.dask.org/en/latest/develop.html#install.

To run the pytest, I followed what docs suggested in `Run Tests`.

I am on board with updating the docs that the CI file can be used to create an environment with all dependencies.

**Comment by TomAugspurger** [comment]
> To run the pytest, I followed what docs suggested in Run Tests.

Thanks for clarifying. In that case, I would recommend removing the `--doctest-modules` from that section. In the [Docstrings section](https://docs.dask.org/en/latest/develop.html#docstrings) we do note that you should use `--doctest-modules` to run the doctests.

**Comment by ncclementi** [comment]
Checking in here, it seems that installation instructions have changed a bit since this issue was open. I believe we are not having this problem anymore, as a matter of fact, I believe this PR https://github.com/dask/dask/pull/6399 adds the instructions to create the environment from the CI file. 

Closing the issue, since it is resolved.
