### ISSUE TITLE
An 'array-like' should not need an 'ndim' property

### ISSUE THREAD

**Issue by pp-mo** [dask/dask#5106]
When upgrading Iris to work with Dask 2.1.0, we observe that an "array-like", as described in the docs to `dask.array.from_array`, now seems to also need an `ndim` property.
Previously (version 1, at least), I believe this only required a `shape` and `__getitem__`, as described in docs.

As it's trivial to calculate from shape, this seems like a mistake.
Should this be rectified ?

Link showing changes we needed :
https://github.com/SciTools/iris/pull/3355/files#r302502604

## Example to Reproduce
code
```
import sys
import numpy as np
import dask
import dask.array as da

class Wrapped(object):
    def __init__(self, shape, dtype=np.float32):
        self.shape = shape
        self.dtype = dtype
    def __getitem__(self, keys):
        return np.zeros(self.shape, dtype=self.dtype).__getitem__(keys)

print('versions:')
print('  python version = {}'.format(sys.version_info))
print('  numpy version = {}'.format(np.__version__))
print('  dask version = {}'.format(dask.__version__))
wrapped = Wrapped((3,4))
lazy = da.from_array(wrapped, chunks=-1)
result = lazy[1:,1:].compute()
print('result = {}'.format(result))
```

results ...
```
versions:
  python version = sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
  numpy version = 1.16.4
  dask version = 1.2.2
result = [[0. 0. 0.]
 [0. 0. 0.]]
```

```
versions:
  python version = sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
  numpy version = 1.16.4
  dask version = 2.1.0
Traceback (most recent call last):
  File "dask_wrap_example.py", line 18, in <module>
    lazy = da.from_array(wrapped, chunks=-1)
  File "/tmp/persistent/miniconda3/envs/dask2/lib/python3.7/site-packages/dask/array/core.py", line 2683, in from_array
    return Array(dsk, name, chunks, meta=meta, dtype=getattr(x, "dtype", None))
  File "/tmp/persistent/miniconda3/envs/dask2/lib/python3.7/site-packages/dask/array/core.py", line 1000, in __new__
    meta = meta_from_array(meta, dtype=dtype)
  File "/tmp/persistent/miniconda3/envs/dask2/lib/python3.7/site-packages/dask/array/utils.py", line 86, in meta_from_array
    ndim = x.ndim
AttributeError: 'Wrapped' object has no attribute 'ndim'
```

**Comment by pentschev** [comment]
Maybe I misunderstood your question, but are you sure this is a consequence from `from_array`? We have now added a new `meta` keyword argument, but there's no `ndim` nor a `kwargs` there, as can be seen in [Dask docs](https://docs.dask.org/en/latest/array-api.html?highlight=from_array#dask.array.from_array).

Dask Array has also an `ndim` attribute that is inferred from the `shape`, which is in turn inferred from the array's `chunks`, but no `ndim` is needed by the constructor either.

**Comment by pp-mo** [comment]
> @pentschev  are you sure this is a consequence from from_array

Ok, that's my own fault for not providing a clear example !!
I have now added one to the main description

**Comment by pentschev** [comment]
Thanks @pp-mo the example is indeed very helpful. I see now, this is indeed due to `_meta` computation (added in Dask 2.0), we rely on arrays having `ndim` (mostly because we did not expect arrays not to have that), but we could also calculate `ndim` from `shape`. Just for my understanding, is there a reason why you don't want to provide an `ndim` attribute? I think providing one makes things simpler for NumPy-like array libraries in general, it's particularly helpful for interoperability.

cc @mrocklin

**Comment by pp-mo** [comment]
> an "array-like", as described in the docs t

P.S. the `from_array` docs actually say "Input must have a .shape and support numpy-style slicing."
But in fact, it must provide a `.dtype` as well.
I guess that is a separate issue, though...

**Comment by pentschev** [comment]
> P.S. the `from_array` docs actually say "Input must have a .shape and support numpy-style slicing."
> But in fact, it must provide a `.dtype` as well.
> I guess that is a separate issue, though...

Indeed, that is something that we missed.

As I said in my previous comment, `ndim` just makes things easier, but we can fix that here as well. In fact, maybe we should, maybe other libraries will fall under the same assumption. The fix is super simple, I wonder only if we should encourage other libraries to be more "NumPy-complete" to help with interoperability. Thoughts @mrocklin?

**Comment by pp-mo** [comment]
Sorry @pentschev messages crosse again.
Impressively quick responses !

I can't really add much in terms of what Dask needs, I can only explain my expectations.
I may be missing some more advanced context here about what an array "is".  But in my head, 'shape' is the fundamental thing and 'ndim' is just a shorthand for len(shape).
It would be a killer point for me if 'ndim' can carry information that isn't in 'shape'.

I do know that in *numpy* we do effectively have more than 1 type of "scalar" with different shapes :
```
>>> a = np.array([1])   
>>> a[1:1].shape
(0,)
>>> a[1:1].ndim 
1
>>> a[0].shape
()
>>> a[0].ndim 
0
```
Is that in any way relevant ??
In any case, those examples still obey "ndim == len(shape)".

**Comment by pentschev** [comment]
@pp-mo you're absolutely right, `ndim == len(shape)`. I am talking more about convenience functions/attributes, NumPy itself does provide an `ndim` attribute which is just there for convenience, even though (I believe) it's implemented as `len(shape)`. My point is only that by providing a more "complete" API can help in situations where libraries may make assumptions on what other libraries implement, in the case here, when adding `meta_from_array`, it didn't occur to me that libraries may not implement `ndim`, for example.

**Comment by mrocklin** [comment]
@pp-mo you're correct that `ndim` isn't strictly necessary to be array-like in principle.  In writing those functions we just took a look at lots of common array-like libraries and found a few common attributes that were good indicators that something was array-like.  There isn't any deep principled meaning behind them.

That being said, is there anything to do here?  Is this a problem for you in some way?  If so, what is that problem specifically?

**Comment by pentschev** [comment]
> That being said, is there anything to do here? Is this a problem for you in some way? If so, what is that problem specifically?

We need to compute `ndim` as `len(shape)` in `meta_from_array`, if `ndim` isn't implemented. My question is more on whether we should advocate for libraries to have a more complete NumPy API, or if we should try and handle all such cases within Dask, in case libraries do not implement NumPy API in full.

**Comment by mrocklin** [comment]
We could compute it if we wanted to.  It's not a big deal.  My question is more towards @pp-mo about why he is filing this issue.  I understand there is a philosophical question here about "what is an array" but I honestly don't care too much about that question :) 

I'm more curious if this is blocking progress somewhere, and if so exactly what is that progress and how hard would it be to just implement `ndim` whereever it currently isn't implemented.

**Comment by pentschev** [comment]
FWIW:

* I would like to see more complete APIs (this will make libraries interoperate more easily in the long run);
* We can also add that particular case on the Dask side without too much work;
* We need to update documentation on `from_array` (if we choose not to compute `ndim` from `shape`).

**Comment by pp-mo** [comment]
> is there anything to do here? Is this a problem for you in some way?

Not really, as we've already accommodated the change.

>  towards @pp-mo about why he is filing this issue. I understand there is a philosophical question here about "what is an array" but I honestly don't care too much about that question :)

It is more "philosophy" 😉 
I think there is just a difference in attitude :  We aren't wrapping some alternative array implementation, it is more like a fake object containing a deferred-access, _imitating_ an array.  So naturally, it presents the minimum array-like interface.  The benefit is, as an array (rather than a delayed, e.g.) the object can be indexed to access a part of the content (which it can support efficiently).

**Comment by mrocklin** [comment]
> Not really, as we've already accommodated the change.

Great

> It is more "philosophy" 😉

OK, in that case in the interests of everyone getting back to work I'm inclined to close this issue.  Would that be ok with everyone?

**Comment by pentschev** [comment]
> OK, in that case in the interests of everyone getting back to work I'm inclined to close this issue. Would that be ok with everyone?

Fine by me. I will fix the docs only.

**Comment by pp-mo** [comment]
> OK, in that case in the interests of everyone getting back to work I'm inclined to close this issue. Would that be ok with everyone?

OK, been there, will happily leave it at that.

**Comment by jrbourbeau** [comment]
Closing as the additional necessary attributes for `from_array` (`.ndim` and `.dtype`) were documented in #5108. Thanks for bringing this up @pp-mo!
