### ISSUE TITLE
Stop using the presence of `value_counts` to determine that an object is not a pandas.DataFrame

### ISSUE THREAD

**Issue by Strilanc** [dask/dask#5109]
There is an open PR to add a value_counts method to pandas.DataFrame:

https://github.com/pandas-dev/pandas/pull/27350

The duck type detection used at https://github.com/dask/dask/blob/4b2dbd4469423cf313ec4e9fc6967b606493a3b1/dask/utils.py#L1073 will stop working after this PR is merged.

**Comment by TomAugspurger** [comment]
We might replace `"value_counts"` with `"name"`.
