### ISSUE TITLE
Adding `copyto` function to Dask Array

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#5114]
It would be useful to add the [`copyto`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.copyto.html ) function to Dask Array. This would help when smoothing over the differences between various array-like libraries where copying contents from one array to another would be needed.

Not entirely sure what the implementation would look like, but at a first pass it might be replacing the graph inside the `dst` object with the one from the `src` object. Though there may be other needs to consider here. The implementation may need to evolve over time as well.

Some relevant discussion in issue ( https://github.com/numpy/numpy/issues/13831 ).

cc @pentschev

**Comment by jsignell** [comment]
This functionality now exists with `asarrray` right?

**Comment by jakirkham** [comment]
@pentschev do we still have a need for this? My guess is no, but please correct me if it is needed 🙂

**Comment by pentschev** [comment]
At this time, I can't really think of a need for `copyto`, _probably_ the `like=` argument has resolved our need. For now I'd say it's safe to close this and we can reopen should we find a use for that in the future.
