### ISSUE TITLE
Iterating over `.blocks`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#5117]
A typical use case for `.blocks` today would be something like the following.

```python
def map_blocks(func, a):
    for i in np.ndindex(a.numblocks):
        yield func(a.blocks[i])
```

To make this a bit more user friendly and readable, we might eschew the use of an index altogether by also making `.blocks` iterable like so.

```python
def map_blocks(func, a):
    for b in a.blocks:
        yield func(b)
```

Though perhaps users will want something like `enumerate` where we also provide the chunk index and/or slice as [shown here]( https://github.com/pydata/xarray/issues/3147#issuecomment-513044413 ).

**Comment by jsignell** [comment]
Blocks is iterable now.
