### ISSUE TITLE
read_csv() option to disable/prevent s3fs cache usage

### ISSUE THREAD

**Issue by pmlk** [dask/dask#5134]
The following code snippet leads to a `FileNotFoundError` due to `S3FileSystem` caching.

```python
import dask.dataframe as dd
import s3fs

file_1 = f"s3://my-bucket/foo.csv"
file_2 = f"s3://my-bucket/bar.csv"
fs = s3fs.S3FileSystem()
if fs.exists(file_2):
    fs.rm(file_2)

# read file_1 which will be committed to the s3fs cache
ddf = dd.read_csv(file_1).compute()
# copy existing file, path for file_2 is not in s3fs cache
fs.copy(file_1, file_2)
# s3fs.S3FileSystem.cachable = False    # <----------------- FIX/WORKAROUND
ddf_ = dd.read_csv(file_2).compute()
```

I looked at the `storage_options` parameter, but couldn't find an option with which to disable caching. The quickest fix/workaround I could come up with is to set `s3fs.S3FileSystem.cachable = False`. 

Is this the desired behaviour? Is there another parameter/option for `read_csv()` that I missed?

**Comment by jrbourbeau** [comment]
cc @martindurant

**Comment by martindurant** [comment]
The problem is not the caching of the filesystem instance, but rather than the directory listings cache of that instance is not being correctly cleared. You could do this using
```
fs.invalidate_cache('my-bucket')
```
before the second read_csv.

The following diff in s3fs fixes this; a PR to s3fs should be made, including a test showing that this works (which does not require dask).

**Comment by martindurant** [comment]
```diff
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -839,7 +839,9 @@ class S3FileSystem(AbstractFileSystem):
         if path is None:
             self.dircache.clear()
         else:
+            path = self._strip_protocol(path)
             self.dircache.pop(path, None)
+            self.dircache.pop(self._parent(path), None)

     def walk(self, path, maxdepth=None):
         if path in ['', '*', 's3://']:
```

**Comment by pmlk** [comment]
Awesome! Thanks for the super quick fix!
