### ISSUE TITLE
Generalizing rolling window functionality to dataframe backends

### ISSUE THREAD

**Issue by beckernick** [dask/dask#5135]
Similar to #5133 , we should generalize the rolling window functionality. Currently, there is explicit concatenation inside `overlap_chunks` that ties rolling windows to pandas, though there may be other areas as well (I'm investigating). That there is a reference to `pd.foo` does not inherently cause a generalization issue.

https://github.com/dask/dask/blob/d0ee3203ea0c65eeb5effb2efe1c4544b9317e4b/dask/dataframe/rolling.py#L34-L36

This issue can serve as a tracker for rolling window related generalization.

- [x] dask.dataframe.rolling.overlap_chunk
- [x] dask.dataframe.rolling._tail_timedelta

**Comment by mrocklin** [comment]
We already have a generalized concat function used in various other parts
of the code.  My guess is that we can swap that in relatively painlessly.

**Comment by beckernick** [comment]
:thumbsup: Matt. cc @galipremsagar

**Comment by mrocklin** [comment]
Yes, looks like we use `methods.concat` for the dispatchable
(cudf-friendly) version.  My guess is that you could swap out `pd.concat`
with `methods.concat` and things would be fine.
