### ISSUE TITLE
[FEA] Remove pandas specific code in quantile api

### ISSUE THREAD

**Issue by galipremsagar** [dask/dask#5138]
**Feature Request:**

In the quantile api code flow on the dask side we have pandas specific code like:
https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L4977

Due to which `describe` fails straight away when used with cudf. 

We will have to generalize this more to remove pandas hard dependency.

**Comment by GenevieveBuckley** [comment]
Closed by https://github.com/dask/dask/pull/5137
