### ISSUE TITLE
read_bytes 403 error on http requests

### ISSUE THREAD

**Issue by jmsking** [dask/dask#5166]
1. **Question Describe:** when i use read_bytes method, the codes as follows:
headers = {
&emsp; "Host": host,
&emsp; "Authorization": auth
}
kwargs['headers'] = headers
_, blocks = read_bytes(url, delimiter=b'\n',**kwargs)
print(len(blocks[0]))
And it will occur 403 *requests.exceptions.HTTPError: 403 Client Error: Forbidden for url*
2. **Test:** when i use requests get method, it run OK, the code as follows:
headers = {
&emsp; "Host": host,
&emsp; "Authorization": auth
}
kwargs['headers'] = headers
import requests
request = requests.get(url, params={}, **kwargs)
print(request.headers)

I don't know the reason, can anyone help me...
Thx

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by bw4sz** [comment]
@jmsking any insight here on your closed issue, I have a similar (impossible to reproduce error). Halfway through an embarrassingly parallel HPC run I suddenly get 403 forbidden. Feels like a network failure. Hard to debug.
