### ISSUE TITLE
S3 with MFA/profile authentication

### ISSUE THREAD

**Issue by ooverandout** [dask/dask#5167]
Hello!

I want to load multiple csv files into dask Dataframe from S3. 
i can log in/list the files using s3fs.core (I have a specific profile set up):
```
from s3fs.core import S3FileSystem

s3 = S3FileSystem(anon=False, profile_name="your-profile-name")

print(s3.ls("s3://your-bucket/some-folder"))
```
At this point I write my MFA auth code and it is ok.
Next step for me would be to load all of these files using dask.dataframe (like here, though probably it should be done differently...):
```
import dask.dataframe as dd
dd.read_csv(s3.ls("s3://your-bucket/some-folder"), sep='\t')

```
However, Python searches for this one in my local home path, resulting in a FileNotFoundError:

` No such file or directory: '/My_home_path/your-bucket/some-folder'`

Do you know how can I combine these two functionalities so that I can read all the files together? I would rather avoid opening each one seperately with s3fs and concatenating them all to one dask dataframe.

Thank you for any kind of assistance!

**Comment by jcrist** [comment]
The issue here is that `s3.ls` returns paths without the full uri (no `s3://` prefix), so their interpreted as local paths.

What you're likely looking for is a globstring, which you can pass directly to `dd.read_csv`:

```python
ddf = dd.read_csv("s3://your-bucket/some-folder/*.csv", sep='\t')
```

**Comment by jcrist** [comment]
Also, you can pass keyword arguments to the backing filesystem with `storage_options={...}`:

```python
ddf = dd.read_csv("s3://your-bucket/some-folder/*.csv", sep='\t',
                  storage_options=dict(anon=False, profile_name="your-profile-name"))

**Comment by ooverandout** [comment]
Thanks! Without this suggestion I probably would not be able to find the solution on my own. :) Now it works though!
