### ISSUE TITLE
moment() in dask.array.stats may give different results from scipy.stats

### ISSUE THREAD

**Issue by andrethrill** [dask/dask#5169]
Depending on the contents of the array, `dask.array.stats` may give, approximate, but different results from `scipy.stats`:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask.array as da
from dask.array import stats as dstats
from scipy import stats as sstats

np.random.seed(seed=1333)

x = np.random.random(size=(30,))
y = da.from_array(x, 3)

print(f'Pandas moment: {sstats.moment(x, 2)}')

print(f'Dask moment: {dstats.moment(y, 2).compute()}')

# Pandas moment: 0.0892461294322445
# Dask moment: 0.08924612943224451
```

```python
np.random.seed(seed=765)

x = np.random.random(size=(30,))
y = da.from_array(x, 3)

print(f'Pandas moment: {sstats.moment(x, 2)}')

print(f'Dask moment: {dstats.moment(y, 2).compute()}')

# Pandas moment: 0.07392703542612034
# Dask moment: 0.07392703542612034
```

Is this expected?

**Comment by jcrist** [comment]
Moments in dask are exact (not approximate), but as with all computations are subject to numerical precision issues. In this case the algorithm used for computing moments in dask is numerically stable, but having a different implementation than scipy may differ by a small amount. Here the difference between your two results is on the order of 1e-17, which is ~ the machine epsilon.

**Comment by andrethrill** [comment]
Thanks for the clarification @jcrist . This helped me writing the unit tests for #5177
