### ISSUE TITLE
Dask monthly meeting

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5181]
As an announcement, we'll be having our Dask monthly meeting this Thursday at 11am US Central time.  More information about where and when are [here](https://docs.dask.org/en/latest/support.html).  All all welcome to participate.

Notes available [here](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit?usp=sharing)

**Comment by TomAugspurger** [comment]
Moving to https://nvmeet.webex.com/join/mrocklin

**Comment by jrbourbeau** [comment]
Really glad to have such a large turnout for the meeting this month. Thanks @mrocklin for the quick fix when we filled the appear.in room

Looking forward to seeing you all next month!
