### ISSUE TITLE
mode argument of dask.dataframe.DataFrame.to_csv does not work

### ISSUE THREAD

**Issue by enneamer** [dask/dask#5187]
The documentation of dask.dataframe.DataFrame.to_csv provide `mode` as an argument, but its value is always overwritten at dask/dataframe/io/csv.py:728-733.

(Please keep the argument. There are some cases where append mode makes sense, such as using get_partition to combine all partitions to a same csv file.)

**Comment by martindurant** [comment]
Would you be interested in providing a PR with this change? You should note that not all file system backends necessarily allow append.

**Comment by enneamer** [comment]
I have added a pull request. I am not sure whether you want to add a test or how you want it tested.

**Comment by enneamer** [comment]
As explained in the pull request, this proposal has quite some flaws. I am closing it for now.
