### ISSUE TITLE
Dask.bag with partition_size>1 has potential memory issues

### ISSUE THREAD

**Issue by crepererum** [dask/dask#5189]
## Abstract
Linear fused parts in dask.bag clean intermediate results too late, leading to potential memory issues.

### Code

```python
import weakref

import dask.bag as db
import dask.config

import objgraph

# to simplify debugging
dask.config.set(scheduler="synchronous")

# global weakref so we can feed objects into objgraph for analysis
memory = weakref.WeakValueDictionary()


class C:
    def __init__(self, i):
        print(f"init: {i}")
        self.i = i

    def __del__(self):
        print(f"del: {self.i}")


def f1(i):
    print(f"f1: {i}")
    obj = C(i)
    memory[i] = obj
    return obj


def f2(obj):
    print(f"f2: {obj.i}")
    return obj.i


def f3(i):
    print(f"f3: {i}")
    if i in memory:
        objgraph.show_backrefs(memory[i], filename=f'refs{i}.png', shortnames=False, max_depth=20)
    return i


bag = db.from_sequence(range(4), partition_size=2).map(f1).map(f2).map(f3).sum()
bag.visualize(optimize_graph=False, filename="graph.png")
bag.visualize(optimize_graph=True, filename="graph_opt.png")
bag.compute()
```

### Compute Graph
The compute graph *without fusing* looks like this:
![graph](https://user-images.githubusercontent.com/1529400/62218909-a62a1280-b3ad-11e9-81e7-eb70614a9c93.png)

The optimized graph (with linear fusing) looks like this:
![graph_opt](https://user-images.githubusercontent.com/1529400/62218937-b215d480-b3ad-11e9-9102-473fc693e0a8.png)

Notice that the chain `f1->f2->f3` is fused into a single task (along with the per-partition aggregation).

### Actual Output
```
f1: 0
init: 0
f2: 0
f3: 0
f1: 1
init: 1
f2: 1
f3: 1
del: 0
del: 1
f1: 2
init: 2
f2: 2
f3: 2
f1: 3
init: 3
f2: 3
f3: 3
del: 2
del: 3
```

Notice that the payload objects that are created in `f1` and destroyed in `f2` are kept until the whole partition is finished.

### Expected Output
```
f1: 0
init: 0
f2: 0
del: 0
f3: 0
f1: 1
init: 1
f2: 1
del: 1
f3: 1
f1: 2
init: 2
f2: 2
del: 2
f3: 2
f1: 3
init: 3
f2: 3
del: 3
f3: 3
```

## Reference Graphs
`i=0`:
![refs0](https://user-images.githubusercontent.com/1529400/62219468-ad9deb80-b3ae-11e9-9bde-20a86d6b7ecb.png)

`i=1`:
![refs1](https://user-images.githubusercontent.com/1529400/62219478-b2fb3600-b3ae-11e9-87d0-923ff0949efc.png)

**Comment by crepererum** [comment]
FYI: I have a WIP solution that for sure needs some discussion. Will publish a WIP-PR later.

**Comment by mrocklin** [comment]
Thank you for the detailed analysis here @crepererum .  I'm glad to know that someone is thinking about this.  I also hadn't seen the `objgraph.show_backrefs` operation before.  That's handy.  I've just used endless `gc.get_referrers` calls before, which is far less helpful ... 

After glancing through the proposed solution I have two initial reactions:

1.  "I can see how this could work" 
2.  "This scares the heck out of me"

It scares me mostly because it's complex enough that I expect that it will eventually interact with something in a bad way, and that our average maintainer won't be able to understand it well enough to quickly figure out what's going on.

> leading to potential memory issues.

Has this issue affected you in a significant way before?  (I assume so, otherwise you probably wouldn't be investigating this).  I wouldn't mind zooming out a bit first to see if there is some other way to resolve the underlying problem that might involve a less technically sophisticated solution.

**Comment by mrocklin** [comment]
Also, is this specific to how Dask handles things, or is this possibly a lower level Python problem?

**Comment by crepererum** [comment]
> "This scares the heck out of me"

I can very much understand this. I think I could tackle this with proper documentation. Honestly, I had quite a hard time to understand the iterator chaining in bags and I think documenting both (the iterator concept and the `_Ref` class) could help maintainers as well as developers. So the WIP PR currently only contains very basic documentation.

> Has this issue affected you in a significant way before?

Yes. This is an issue in one of our ETL pipelines. Part of data that we pass through the bags are dataframes as well as models. We have loads of items and expected that using the partition-size, we could reduce the scheduler overhead and the fusing even suggested that this would work properly. Turns out that keeping the intermediate results for too long just blows up our distributed workers.

> Also, is this specific to how Dask handles things, or is this possibly a lower level Python problem?

So the very conservative refcounting of Python is not a Dask problem, but the iterator chains definitely make this very prominent. The issue is basically that all abstraction and their interactions in Python (iterators, function calls, yields) increase the refcount. Stepping back a little bit, here is a more basic example that does not require fancy iterators:

```python
class C:
    def __init__(self, i):
        print(f"init: {i}")
        self.i = i

    def __del__(self):
        print(f"init: {self.i}")


def f1(o):
    print("f1: start")
    o = C(o.i + 1)
    o = C(o.i + 1)
    print("f1: end")
    return o


def main():
    print("main: start")
    f1(C(1))
    print("main: end")


if __name__ == "__main__":
    main()
```

```
main: start
init: 1
f1: start
init: 2
init: 3
init: 2
f1: end
init: 1
init: 3
main: end
```

As you can see, `C(1)` is created in `main` but passing things via an argument increases the refcount and the count is only decreased again if the object is passed back to the parent scope. This late refcount decreasing is also the underlying issue with the yield statements.

In general, libs can workaround these issue using multiple measurements. One is the ref-wrapper in the proposed PR. Another involves sneaky cython tricks. There might be more that I am not aware of.

**Comment by mrocklin** [comment]
We might also consider fusing multiple maps into a single map that runs one compound function.

To do this we would reuse the HighLevelGraph and Blockwise functionality that we've adopted for dask array and dataframe.  This is also some scary machinery, but at least it's machinery that we already have to deal with.

**Comment by crepererum** [comment]
> We might also consider fusing multiple maps into a single map that runs one compound function.

I'm not too much concerned about the trivial case where we have linear chains like in the above example. I think the fusing gets really tricky if one of the parameters to the map functions is also a bag or when the user zips to bags.

Thinking about the python refcounting, I think one of the issues here is the edge case around `yield`, where the refcount is only decremened when the control flow returns to the generator (so `yield` seems to behave more like a function call and is therefore kinda reversed to `return`). I would like to try to rewrite `map_chunk` into an iterator where `__iter__` can just return the mapped result, which (to my understanding) would not increase the refcount. That's for sure is slightly more code than the master implementation, but might be really elegant and could also work for zipped bags.
