### ISSUE TITLE
Resample rule greater than a day raises NotImplementedError

### ISSUE THREAD

**Issue by andrethrill** [dask/dask#5191]
If I try to do `df.resample("5H")` I'll get the error:

> NotImplementedError: Resampling frequency <5 * Hours> that does not evenly divide a day is not implemented

Which I understand.

But, if I try `df.resample("2D")` I also get the same error.

Although I did not understand the internals completely, I would expect that if `df.resample("1D")` is possible, then `df.resample("2D")`should also be (easily?) possible. But maybe it's not that simple!

Is this really that case that  resampling frequencies greater than a day are not supported and difficult to implement?
Or were they simply not considered at implementation time?

I could attempt a PR but some guidance would be required...

**Comment by jsignell** [comment]
I am closing this in favor of #6271, but `df.resample("2D") should definitely work, so if you are still experiencing this issue, please reopen.
