### ISSUE TITLE
Add pyarrow to conda install in https://docs.dask.org/en/latest/develop.html

### ISSUE THREAD

**Issue by joy-rosie** [dask/dask#5193]
I tried following https://docs.dask.org/en/latest/develop.html and ran the tests but get failures as I need `pyarrow` which I conda installed but this should be added in this page?

**Comment by jrbourbeau** [comment]
@joy-rosie thanks for raising this issue! All tests that require `pyarrow` should be skipped if `pyarrow` is not installed. I've opened up #5217 to fix this issue

**Comment by jrbourbeau** [comment]
@joy-rosie with the updates in #5217, you should now no longer need `pyarrow` to be installed to run the tests suite. Is it safe to close this issue?

**Comment by joy-rosie** [comment]
Yes thank you!

**Comment by jrbourbeau** [comment]
Great, thanks again for raising this issue
