### ISSUE TITLE
pd.Grouper seems only partially supported

### ISSUE THREAD

**Issue by bluecoconut** [dask/dask#5195]
## Problem

I've tried to use the `pd.Grouper(...)` as a method of groupby in dask and it works for some cases, but not all, and it has some oddities in behavior (based on partitioning), so it leads me to believing it is not actually functioning properly or there's an underlying bug.

### Setup for all examples
```python
>>> from dask.datasets import timeseries
>>> import pandas as pd
>>> df = timeseries().reset_index()
```

### Example 1 (Not respecting freq (when set as days) longer than 1 day.)
```python
>>> two_day_df = df.groupby(pd.Grouper(key='timestamp', freq='2d'))['x'].max().compute()
>>> two_day_df.index[1]-two_day_df.index[0]
Timedelta('1 days 00:00:00')
```

### Example 2 (Does respect week, but not multiple week)
```python
>>> one_week_df = df.groupby(pd.Grouper(key='timestamp', freq='W'))['x'].max().compute()
>>> one_week_df.index[1]-one_week_df.index[0]
Timedelta('7 days 00:00:00')
```

```python
>>> two_week_df = df.groupby(pd.Grouper(key='timestamp', freq='2W'))['x'].max().compute()
>>> two_week_df.index[1]-two_week_df.index[0]
Timedelta('7 days 00:00:00')
```

### Example 3 (Does work when re-partitioned)
```python
>>> chunky_df = df.repartition(npartitions=4)
>>> two_day_cdf = chunky_df.groupby(pd.Grouper(key='timestamp', freq='2d'))['x'].max().compute()
>>> two_day_cdf.index[1]-two_day_cdf.index[0]
Timedelta('2 days 00:00:00')
```

### Example 4 (Does not work when time is not sorted...)
```python
>>> sorted_by_x = df.set_index('x').reset_index()
>>> one_day_unsorted = sorted_by_x.groupby(pd.Grouper(key='timestamp', freq='1d'))['x'].max().compute()
>>> one_day_unsorted.index[1]-one_day_unsorted.index[0]
ValueError: all keys need to be the same shape
```

## Also note

Pandas works on all of the above examples correctly. Simply changing the `.compute()` to happen before the groupby, and the output is consistently what one would expect, so this definitely seems to be related to partioning and how dask resolves Groupers.

**Comment by TomAugspurger** [comment]
I suspect it's not tested. I wouldn't expect pandas' `Grouper` to necessarily work on Dask objects out of the box.

**Comment by bluecoconut** [comment]
I originally raised this because of this other github issue implying it is supported:
https://github.com/dask/dask/issues/1749

This seems especially dangerous because it can actually run without error (eg. `NotImplementedError`), but the results are invalid / not what would be expected.

**Comment by TomAugspurger** [comment]
Are you interested in finding out what does work correctly, and raising /
implementing correctly in other cases?

**Comment by rubenvdg** [comment]
@TomAugspurger @jsignell would you welcome a fix for this if it only works for pandas >= 1.1.0? `pd.Grouper` has had some changes over time which makes it difficult to make a fix that accommodates for all versions.

**Comment by TomAugspurger** [comment]
Yeah I think that's just fine.

**Comment by jsignell** [comment]
Yep! Sounds good to me as well @rubenvdg :)

**Comment by jsignell** [comment]
closed by https://github.com/dask/dask/pull/7857
