### ISSUE TITLE
Processing with multiple csv files explodes memory and then got kill

### ISSUE THREAD

**Issue by ductri** [dask/dask#5196]
My code reads ~200 csv files, do some basic text pre-processing, but after a while running, it consumes over 80% RAM memory, and then gets kill. My RAM memory size is 32Gb

This is my code:
```python

start = time.time()
root_dir = 'path_to_my_dir/'
num_rows = 0
df = dd.read_csv(root_dir + '/*.csv', usecols=['id', 'topic_id', 'search_text']) # I also tried with blocksize='64MB'
logging.info('Dask is processing with %s partitions', df.npartitions)

logging.info('Drop NA and duplicates ... ')
df = df.dropna(subset=['search_text'])
df = df.drop_duplicates(subset=['search_text'])

logging.info('Fining search_text ...')
df = df[df['search_text'].map(lambda x: len(x.split()) > 1)]
df['mention'] = df['search_text'].map(lambda x: my_preprocess_func(x), meta=pd.Series([], dtype=str, name='mention'))
df = df[df['mention'].map(lambda x: len(x.split()) > 1)]
df.drop_duplicates(subset=['mention'])
logging.info('Saving ...')
df[['id', 'topic_id', 'mention']].to_csv('path_to_output/*.csv')
logging.info('Duration: %.2f s', time.time() - start)
```

**Comment by TomAugspurger** [comment]
@ductri sorry for the delay. I suspect you'd get a faster response if you can provide a minimal example: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports that reproduces the problem. Can you provide that?

**Comment by ductri** [comment]
I am not sure what kind of info do you want. In addition, `path_to_my_dir` in the code above contains ~200 csv files.
```
root_dir = path_to_my_dir/
```

**Comment by TomAugspurger** [comment]
Did you read http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports? That explains the kind of information that is useful for diagnosing whether there's a bug.

**Comment by jrbourbeau** [comment]
I'm going to close this issue for the time being. @ductri please feel free to re-open if you're able to produce a [minimal example](https://blog.dask.org/2018/02/28/minimal-bug-reports)
