### ISSUE TITLE
dask using a lot of memory reading csv and writing to parquet

### ISSUE THREAD

**Issue by thebeancounter** [dask/dask#5197]
Hi 
I am trying to collect multiple large csv files into one parquet file with this code 
```

data = b.map(lambda x: dd.read_csv(x, dtype='object', include_path_column="path", assume_missing=True)).\
        map(lambda y: dd.to_parquet(y, path=output_parquet_file, compute=True, partition_on=["path"])).\
        compute(nworkers=8, scheduler='processes')
```

Dask uses too much memory as if it tries to load the entire dataset to memory before writing it into parquet, How can I do this process in a iterative way, without blowing up the memory? 

Also, I How can i infer the dtypes of the data? I tried using 
`dd.read_csv().dtypes.to_dict() `
In order to get the dtypes for each csv and use them as parameter to` to_parquet()` but this resulted in errors with strings that it tried to treat as integets...

Thanks

**Comment by TomAugspurger** [comment]
Can you make a minimal, reproducible example?

**Comment by thebeancounter** [comment]
Well, I have no example to upload given those are large files, that will take ages to upload. The code is all here. Maybe let's produce csv files of random numbers?

**Comment by TomAugspurger** [comment]
The issue, if there is one, isn’t likely to depend on the specifics of your file. Ideally you’d recreate it with random data that’s representative of the problem.

And I don’t think the code is all there. I don’t know what “b” is.

**Comment by TomAugspurger** [comment]
@thebeancounter any updates here?

**Comment by thebeancounter** [comment]
Sorry, tried to reproduce with random data with no success

**Comment by TomAugspurger** [comment]
OK, let us know if you can provide a minimal example and we'll reopen. Otherwise, there's not a whole lot we can do.

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be worth reading through.
