### ISSUE TITLE
Crash with TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object on slurm-managed cluster

### ISSUE THREAD

**Issue by JohnZed** [dask/dask#5204]
Running with LocalCluster on a slurm-managed HPC cluster, I find that nanny processes are unable to launch. This happens whether I run a `dask-worker` CLI manually or use `dask.distributed.LocalCluster` - either way is an immediate crash with a back trace ending in:

```    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
distributed.nanny - WARNING - Worker process 74202 exited with status 1
```

If I run a worker with --no-nanny, it appears to connect and work.

**Comment by JohnZed** [comment]
Note that we ended up resolving this by updating the `~/.config/dask/<hostname>.yml` config file to be:

```
distributed:
  worker:
    multiprocessing-method: spawn
```

The crash was happening in forkserver, but the spawn method of worker creation was unable to proceed. It appears that the HPC cluster has some obscure limitation on how processes are able to use fork due to resource allocation controls. The spawn method appears to work smoothly

**Comment by mrocklin** [comment]
Thanks for the report!  Hopefully this helps other people that come here
via web search

**Comment by mrocklin** [comment]
Note that `<hostname>` above can actually be anything.  That yaml just needs to be in that directory under any filename.
