### ISSUE TITLE
Is the documentation missing on the site?

### ISSUE THREAD

**Issue by carkar7** [dask/dask#5206]
I'm going to the website and im seeing nothing but blanks within the api documentation. 
https://docs.dask.org/en/latest/dataframe-api.html

Is this a mistake?
![Xnip2019-08-01_17-39-58](https://user-images.githubusercontent.com/22269536/62336069-6fbec700-b483-11e9-8f5f-901342b6e46b.jpg)

**Comment by mrocklin** [comment]
Thanks for bringing this to our attention @carkar7 .  It is now fixed.
