### ISSUE TITLE
Crash importing fastparquet/pyarrow in dask==2.2

### ISSUE THREAD

**Issue by bnaul** [dask/dask#5215]
Edit: I thought this was caused by upgrading dask but I think it's a coincidence bc that pulled in new fastparquet+pyarrow. Can re-post elsewhere if needed.

In a clean virtualenv:
```
(segfault) ➜  model git:(dask_2_2) ✗ pip install -U numpy
Successfully installed numpy-1.17.0
(segfault) ➜  model git:(dask_2_2) ✗ pip install -U fastparquet dask[dataframe]
Successfully installed cloudpickle-1.2.1 dask-2.2.0 fastparquet-0.3.2 fsspec-0.4.0 llvmlite-0.29.0 locket-0.2.0 numba-0.45.1 pandas-0.25.0 partd-1.0.0 python-dateutil-2.8.0 pytz-2019.2 six-1.12.0 thrift-0.11.0 toolz-0.10.0
```

With these packages, everything is 💯
```
(segfault) ➜  model git:(dask_2_2) ✗ python -c 'import dask.dataframe, fastparquet'
```
Installing `pyarrow` causes a crash:
```
(segfault) ➜  model git:(dask_2_2) ✗ pip install pyarrow
Successfully installed pyarrow-0.14.1
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(segfault) ➜  model git:(dask_2_2) ✗ python -c 'import dask.dataframe, fastparquet'
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
[1]    64427 abort      python -c 'import dask.dataframe, fastparquet'
```
Any idea what's going on here? cc @martindurant

**Comment by martindurant** [comment]
Sorry, didn't follow: installing pyarrow makes importing fastparquet crash?

Noting that numpy 1.17 is brand new, maybe try with older. Also, may want to try installing cython before fastparquet, to see if a recompile helps.

**Comment by bnaul** [comment]
I'm not sure how pyarrow is related; I started seeing this in another environment and this is my incomplete attempt at piecing together what might be going on.

Downgrading to numpy 1.16.4 didn't fix the issue so I'm a bit stumped, nor did installing Cython.
```
pip install numpy==1.16.4 cython
pip install dask[dataframe] fastparquet  # still ok
pip install pyarrow  # import fails after this
```

**Comment by martindurant** [comment]
What else gets installed along with pyarrow?

**Comment by bnaul** [comment]
nothing, the whole output is
```
(segfault) ➜  model git:(short_trips) ✗ pip install pyarrow
Collecting pyarrow
  Using cached https://files.pythonhosted.org/packages/0c/fa/baea2c0713b4edf5abfcbd676c3d54e43edde0e62af273352660ef3368ae/pyarrow-0.14.1-cp37-cp37m-macosx_10_6_intel.whl
Requirement already satisfied: six>=1.0.0 in /Users/brett/venvs/segfault/lib/python3.7/site-packages (from pyarrow) (1.12.0)
Requirement already satisfied: numpy>=1.14 in /Users/brett/venvs/segfault/lib/python3.7/site-packages (from pyarrow) (1.16.4)
Installing collected packages: pyarrow
Successfully installed pyarrow-0.14.1
```

**Comment by martindurant** [comment]
I don't know, is there a way for force pip to ignore wheels and try local compilation instead? In general, I am not surprised that these very binary things don't play nicely.

**Comment by ihnorton** [comment]
This is the same issue as:
- https://github.com/ray-project/ray/issues/5250
- https://github.com/JuliaPy/PyCall.jl/issues/476
... and a number of others among projects that use LLVM (e.g. I've seen issues with Gallium, Arrow, and many others). The core issue is that different versions of LLVM often cannot be loaded in the same address space because static initializers from one version don't play nicely with the expectations of other versions.

**Comment by ihnorton** [comment]
In this case presumably the conflict is between pyarrow and numba, which both use LLVM.

Note that the Arrow project has [decided to stop producing wheels](https://lists.apache.org/thread.html/128a2bec285ad45aa4189ebb39a15b39dcf6d91c4ab0278ff4f7cdea@<dev.arrow.apache.org>), because the maintenance effort was prohibitive, so conda is currently the recommended source.

**Comment by martindurant** [comment]
Ah, so numba are still updating wheels, but arrow is not. Well, if arrow no longer supports it, I don't suppose there's anything we can do (except recompile locally every time).

**Comment by ihnorton** [comment]
Unfortunately that is probably not sufficient: unless you recompile *both* projects against the same libLLVM. Just recompiling llvmlite for Numba will still conflict with the LLVM from pyarrow.

**Comment by martindurant** [comment]
@bnaul , agreed to close this here?

**Comment by ivirshup** [comment]
@bnaul, you might want to consider swapping the order of your imports:

```sh
isaac@Mimir ~$ python -c "import fastparquet; import dask.dataframe"
isaac@Mimir ~$ python -c "import dask.dataframe; import fastparquet"
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
[1]    34868 abort      python3 -c "import dask.dataframe; import fastparquet"
```

Similar for numba:

```sh
isaac@Mimir ~$ python -c "import dask.dataframe; import numba"                                                                                                                                                                           
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
[1]    35259 abort      python3 -c "import dask.dataframe; import numba"
isaac@Mimir ~$ python -c "import dask.bag; import numba"                                                                                                                                                                          134 ↵  
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
[1]    35320 abort      python3 -c "import dask.bag; import numba"
isaac@Mimir ~$ python -c "import numba; import dask.bag"                                                                                                                                                                          134 ↵  
isaac@Mimir ~$ python -c "import numba; import dask.dataframe" 
```

https://github.com/JuliaPy/pyjulia/issues/307

**Comment by bnaul** [comment]
Thanks @ivirshup! I ended up just ditching pyarrow altogether for fastparquet since the impending lack of wheels won't work for my use case anyway.

**Comment by martindurant** [comment]
(might want help with wheels, actually, since there are issue with which numpy to cythonize against)
