### ISSUE TITLE
read_csv only read part of a large files on 2.2

### ISSUE THREAD

**Issue by philippegr** [dask/dask#5233]
I think I have found an issue with read_csv on a very large file (~50GB) with multiples types (str, float, ...), where dask 2.2 does not read the whole file but just a part of it but 2.1 was working fine.
Unfortunately this file is private and I was not able to build a reproducible example on a randomly generated frame. However here are some symptoms:

(In both cases pandas version is 0.25.0, code run in a docker built on an Ubuntu 18.04 image)
In dask 2.1:
`len(df)` and `bag.read_text(['my_csv.csv']).count().compute()` and bash `wc -l` agree.
For the record `df.npartitions` is 807
In dask 2.2
`len(df)` is much smaller than the output of `bag.count()` or `wc -l` 
On top of that `df.npartitions` is 1

(The suggestion of using `bag` as a way to compare via a totally different path is from @chrish42 )

Let me know what I can do to help track this bug down.

**Comment by TomAugspurger** [comment]
cc @martindurant.

The file is on your local filesystem, correct?

**Comment by philippegr** [comment]
Correct (mounted from the docker host, no S3 or things like that)

**Comment by martindurant** [comment]
I am not seeing this problem
```
In [14]: f = open('output', 'w')

In [15]: for x in range(1000000):
    ...:     f.write('a' * 10000 + '\n')
    ...:

In [16]: f.close()

In [17]: import dask.bag as db

In [18]: b = db.read_text('output', blocksize=1000000)

In [19]: b.npartitions
Out[19]: 10001

In [20]: b.count().compute()
Out[20]: 1000000
```
(fsspec 0.4.1+7.gdbf6d1e, dask 2.2.0+2.g7d517e8)

**Comment by philippegr** [comment]
`bag` is fine in both 2.2 and 2.1, it is dataframe that  incorrect in 2.2 in my case @martindurant

**Comment by martindurant** [comment]
I am still not seeing it. This file is smaller than yours, but far bigger than any normal blocksizes
```
In [1]: f = open('output.csv', 'w')

In [2]: for x in range(1000000):
   ...:     f.write('0,"hi"' * 100 + '\n')
   ...:

In [3]: f.close()

In [4]: ls -l output.csv
-rw-r--r--  1 mdurant  staff  601000000  6 Aug 19:23 output.csv

In [5]: import dask.dataframe as dd

In [6]: df = dd.read_csv('output.csv', header=None)

In [7]: len(df)
Out[7]: 1000000

In [8]: df = dd.read_csv('output.csv', header=None, blocksize=1000000)

In [9]: df.npartitions
Out[9]: 601

In [10]: len(df)
Out[10]: 1000000
```

**Comment by TomAugspurger** [comment]
@philippegr what version of fsspec?

**Comment by philippegr** [comment]
for dask 2.2, fsspec '0.4.1'

I cannot import it on dask 2.1, and I see it in the changelog, so I am assuming this is a new dependency, correct @TomAugspurger ?

**Comment by TomAugspurger** [comment]
Yes, it's a new dependency.

**Comment by philippegr** [comment]
The csv file I was loading is in fact a symlink.
In dask 2.2 if I open the symlink, I have the above mentioned problem, OTH if I open the underlying file directly all is good. So it seems to be a symlink issue.

Below is a reproducible example (**beware** it creates a 1.7GB csv file to prove its point, I could not reproduce it with small df) 
```
from dask import dataframe as ddf
import pandas as pd
test_df = pd.DataFrame.from_records([[0] + ["hello"]*30]*int(1e7), columns=list(range(31)))
test_df.to_csv('tmp.csv', sep='|', index=False)
```

Create a symlink (in jupyter)
```
!ln -s 'tmp.csv' 'tmp_sym.csv'
```

Now compare the `len` with and without the symlink 
```
with_symlimk = ddf.read_csv('tmp_sym.csv', sep='|')
len(with_symlink)
```
I have 351648 and 1 for `.npartitions` but 
```
no_symlink = ddf.read_csv('tmp.csv', sep='|')
len(no_symlink)
```
is fine at 10000000 and `.npartitions` being 29

This seems to be an issue somewhere between dask and fsspec. Let me know if you want me to reopen a ticket there @martindurant

**Comment by martindurant** [comment]
Interesting! That certainly gives me something to work on. With look, I can try this evening; this certainly feels like an fsspec issue, don't really mind if it is lodged there or not.

**Comment by philippegr** [comment]
FYI, looking for the root cause we tried forcing pandas to 0.24.2, the bug persists. 
(I guess if it's file handling related, this should not come as a surprise to you)

**Comment by philippegr** [comment]
Thanks a lot for the resolution @martindurant !
@TomAugspurger your hint at fsspec pointed us in the right direction, at a time when I was about to go crazy at trying to reproduce the bug
