### ISSUE TITLE
Trying to use Dask with TPOT

### ISSUE THREAD

**Issue by windowshopr** [dask/dask#5250]
Ok, first time trying to use Dask and I'm not sure what I'm doing wrong.

I've tried `TPOTRegressor(use_dask=True)` and:

```
    from dask.distributed import Client
    client = Client()
    from sklearn.externals import joblib
    with joblib.parallel_backend('dask'):
        # your scikit-learn code
    estimator.fit(X, y)
```

The first option just restarts my program from the the first line of code for some reason, and when I hit CTRL + C to stop it, it gives me a bunch of `distributed.nanny - WARNING - Restarting worker` errors so once I've battled through that, I try the second way and it does the same thing.

I also ran into some yaml.load error that I saw was an issue with other people but I'm still seeing it on my end. I reverted back to pyyaml 3.2 for now.

Any ideas? Thanks.

**Comment by TomAugspurger** [comment]
Can you give a few more details? Does the example from https://examples.dask.org/machine-learning/tpot.html run? What errors do you see? What versions of dask, distributed, and TPOT?

**Comment by windowshopr** [comment]
Running Python 3.6 on Windows 10. Trying to just run it on my local machine. 
Dask==2.2.0
Distributed==2.20
TPOT==0.10.2

All other dependencies are up to date. So when you first start my program, it asks you to input a stock ticker so that it will download historical data with pandas datareader. So what happens is:

```
Which ticker would you like to download? : AAPL
Getting historical data for : AAPL
```
...then it runs some stuff, then I get to the TPOTRegressor(use_dask=True...) part, and it gives me this:

```
C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\bokeh\themes\theme.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  json = yaml.load(f)
C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\bokeh\themes\theme.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  json = yaml.load(f)
Which stock ticker would you like to predict?Which stock ticker would you like to predict?Which stock ticker would you like to predict?Which stock ticker would you like to predict?
```
So then I hit CTRL + C once, then several times to quit and it tells me:

```
KeyboardInterrupt
distributed.nanny - WARNING - Restarting worker
Which stock ticker would you like to predict?Traceback (most recent call last):
  File "<string>", line 1, in <module>

distributed.nanny - WARNING - Restarting worker
Which stock ticker would you like to predict?Traceback (most recent call last):
  File "<string>", line 1, in <module>

Traceback (most recent call last):
  File "<string>", line 1, in <module>

distributed.nanny - WARNING - Restarting worker
Which stock ticker would you like to predict?Traceback (most recent call last):
  File "<string>", line 1, in <module>

Traceback (most recent call last):
  File "<string>", line 1, in <module>

distributed.nanny - WARNING - Restarting worker
Which stock ticker would you like to predict?Traceback (most recent call last):
  File "<string>", line 1, in <module>

Traceback (most recent call last):
  File "<string>", line 1, in <module>

distributed.nanny - WARNING - Restarting worker
```

NOW of course that I'm typing this, it seems I have found a working solution by inputting:

`best_model = TPOTRegressor(use_dask=True,n_jobs=-1,...)`

...where I didn't have n_jobs before. So it is working now, although it's not exactly fast, but I'll play with the number of n_jobs from here. Thanks for helping me work through this.
