### ISSUE TITLE
How to control memory usage in Dask actively ?

### ISSUE THREAD

**Issue by mohseniaref** [dask/dask#5251]
I can access to a workstation with 500 GB RAM and 28 CPUs which different job from different user could be submitted so the available memory and CPUs change time to time.I want to use all memory and number of physical CPUs that are available.Each thread take about 40 GB RAM and I have many jobs to submit in parallel while I am worried about the available memory and the number of physical CPUs. My code can make workstation easily overflow.
In order to limit memory usage of each thread ,I think we can use something like that
client = Client(memory_limit='8GB', processes=False) according https://github.com/dask/dask/issues/4118
https://github.com/willirath/dask_jobqueue_workshop_materials/blob/master/notebooks/01_local_cluster_monte_carlo_estimate_of_pi.ipynb 
How could I actively manage to send many threads in queue by considering available memory and number of available ?
I have recently seen similar question in stack-overflow 
https://stackoverflow.com/questions/44966704/how-to-control-memory-usage-in-multithreading

I really appreciate if you could inform me a trick to do multithreadingwith considering available shared memory automatically in local cluster?

PS: The job manager like PBS,Slurm or LSF cluster is not installed in the machine!

**Comment by TomAugspurger** [comment]
I don't really follow issue. You're asking how to control how many threads and how much memory each worker in the cluster gets?

**Comment by mohseniaref-InSAR** [comment]
@TomAugspurger No, very simple. imagine the next loop as following 
two problems might happen

1- each time that you run function, It takes huge space in RAM and within few iterations, you will reach the maximum available memory and Dask should stop the loop(how?) and wait to run next iteration but it does not just depend on your jobs which submitted to the server but it also depends on other users RAM usage
2-There are just n CPU cores and there are a lot of jobs submitted from not you and another user, how dask actively could stop sending threads to prevent deadlock and keep the jobs in queue


results =[ ]
 for x in L:
     y = dask.delayed(f)(x)  
   results.append(y)
  results = dask.compute(*results)
--

**Comment by TomAugspurger** [comment]
I may be misunderstanding, but it sounds like you're asking for things that are outside of Dask's scope. Something like

> there are a lot of jobs submitted from not you and another user, how dask actively could stop sending threads to prevent deadlock and keep the jobs in queue

is handled by a cluster resource manager, which Dask isn't.

**Comment by mohseniaref-InSAR** [comment]
Thanks so much, @TomAugspurger, I think I got my answer
I will try to manage the memory usage using import psutil

**Comment by TomAugspurger** [comment]
OK, good to hear.

**Comment by luisvivasg** [comment]
Hello.
In my case, I am using the Kaggle kernel so I have 16gb RAM. I am using
client = Client()
client.restart()

And then train XGBoos with Dask And I get this waring.

distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker

It is running but the system is using 6GB RAM and 16% of the CPU. I suppose it has reached the maximum memory allocated. Is there a way I can set a higher memory to run it faster?

**Comment by jrbourbeau** [comment]
You can explicitly set the [memory limit for workers](https://github.com/dask/distributed/blob/e7ba316d496a23d073188466571ce1580336aba4/distributed/worker.py#L240-L244). Additionally, there are [several configuration options](https://github.com/dask/distributed/blob/d8f46d502a561bd86cc5c08eec0fd906a4ba700d/distributed/distributed.yaml#L80-L86) that control how workers behave in high-memory situations

**Comment by luisvivasg** [comment]
> You can explicitly set the [memory limit for workers](https://github.com/dask/distributed/blob/e7ba316d496a23d073188466571ce1580336aba4/distributed/worker.py#L240-L244). Additionally, there are [several configuration options](https://github.com/dask/distributed/blob/d8f46d502a561bd86cc5c08eec0fd906a4ba700d/distributed/distributed.yaml#L80-L86) that control how workers behave in high-memory situations

Thanks. I will look at that.
