### ISSUE TITLE
dask.config caveat with mutable values

### ISSUE THREAD

**Issue by lesteve** [dask/dask#5254]
Here is a snippet:
```py
import dask.config
dask.config.set({'key': []})

value = dask.config.get('key')
print('config value:', dask.config.get('key'))  # config value: []
value.append(4)

print('config value:', dask.config.get('key'))  # config value: [4]
```

In a sense, this is the well known Python caveat (`a = []; b = a; b.append(4)`. `a` is updated too, see [this](https://nedbatchelder.com/text/names.html) for more details in case I am not making myself clear enough) with a `dask.config` spin on top of it. I would be fine if I was told this is a "won't fix" and code using `dask.config.get` should use `.copy` where appropriate.

I would argue that it would feel more natural if the only way to change the config was through `dask.config.set` and not through a (probably unintended) side-effect like the one above.

I am not sure what an acceptable solution would be, maybe `dask.config.get` would return a copy if the value is mutable.

Context: I was debugging a problem `dask_jobqueue` and even if I am very familiar with this Python caveat, it took me a while before figuring out the source of the problem.  The behaviour I was seeing was something like this:
```py
cluster = SGECluster(interface='gibberish', ...)  # error that makes complete sense
cluster = SGECluster(interface='eth0', ...)  # no error
print(cluster.job_script())  # this has --interface gibberish --interface --interface 'eth0'
```

The problematic dask-jobqueue code looks like this:

```py
if extra is None:
    # extra is [] by default (from the jobqueue.yaml config)
    extra = dask.config.get("jobqueue.%s.extra" % config_name)

# many lines later
if interface:
    extra += ["--interface", interface]
```

See the full [code](https://github.com/dask/dask-jobqueue/blob/a27d769d9619e2d769279eddc0ee5ae3dab338aa/dask_jobqueue/core.py#L221) for more details.

**Comment by TomAugspurger** [comment]
Hmm, I can see how that would be difficult to debug. However, I suspect that it copying could also cause confusion for users who expect to be able to mutate a mutable object and have that change persist.

**Comment by jcrist** [comment]
> I would be fine if I was told this is a "won't fix" and code using `dask.config.get` should use `.copy` where appropriate.

That's my take on things. We shouldn't implicitly copy, as that's potentially expensive (and not all objects are copyable anyway). Unfortunate, but I don't think there's anything we can do on dask's end to make this easier.

**Comment by TomAugspurger** [comment]
> I don't think there's anything we can do on dask's end to make this easier.

Though a note in the docs *might* help shorten a future debugging session, if anyone is inclined to write one.

**Comment by lesteve** [comment]
> Though a note in the docs might help shorten a future debugging session

I agree with the *might* this is the kind of thing that you tend to find in the docs when it is already too late.

Closing this one, thanks for your feed-back!
