### ISSUE TITLE
Improve warning for multiple sorted columns in parquet

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5260]
See https://stackoverflow.com/questions/57345240/problem-with-opening-parquet-files-with-fastparquet-after-updating-to-latest-ver  and the conversation there by @martindurant 

I suggest a few things:

1.  Include the column names in the warning
2.  Point the user towards the `index=` keyword
3.  Tell the user that things will keep working, that this is only a warning, and that to silence the warning they should explicitly pass an index, or pass `index=None`.

**Comment by martindurant** [comment]
Happy to do this, can't promise when I'll get to it.
