### ISSUE TITLE
`from_array` no longer detects dask arrays

### ISSUE THREAD

**Issue by djhoese** [dask/dask#5262]
## Problem

Not sure if this needs to be supported, but I had some old code that accidentally did a `da.from_array(existing_dask_arr)`. This is obviously unnecessary, but the code ran fine. Starting with dask 2.2 this no longer seems to work and will result in `map_blocks` passing a dask array to the underlying function instead of a numpy array.

## Example Code

```
import numpy as np; import dask.array as da

a = np.zeros((5, 5), dtype=np.float)
a = da.from_array(a, chunks=2)
b = da.from_array(a, chunks=2)

def test(arr): 
    print(type(arr)) 
    return arr 

print("Running a")
a.map_blocks(test, dtype=a.dtype).compute() 
print("Running b")
b.map_blocks(test, dtype=b.dtype).compute() 
```

## Output

```
Running a
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Running b
<class 'numpy.ndarray'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
<class 'dask.array.core.Array'>
```

## Expected

```
Running a
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Running b
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
```

**Comment by TomAugspurger** [comment]
This looks a bit strange. 

I think that passing `b = da.from_array(a, chunks=2, asarray=True)` fixes things, but maybe that shouldn't be necessary for dask arrays?

cc @jakirkham, @pentschev if you have thoughts.

**Comment by shoyer** [comment]
I think there is a good chance that this only worked before by nesting a (disconnected) dask array wrapping the inner dask array. This tends to be pretty problematic, because dask's scheduler doesn't understand how the arrays are connected.

The possible solutions are to either:
1. automagically convert `from_array` into `rechunk` on dask array (xarray actually exposes a single `chunk` API for both)
2. raise an error and require the user to be explicit

**Comment by jakirkham** [comment]
In general one should use `da.asarray` to ensure a Dask Array is given/used.

I don't have strong thoughts about fixing this as this doesn't seem like a use case that needs to be supported here (there are better recommended strategies). Though maybe we could error more clearly.

Feel free to push back though if there is some need I've overlooked in this thought process.

**Comment by djhoese** [comment]
I agree that `asarray` would be better in most cases. This accidental code was in a unit test for a function that expects a DataArray with dask underneath. I had created a numpy array with certain values and converted it to a dask array. This was not in a function/method that would be part of any normal use case. That's why I'm not sure this is something that needs to be fixed. Developers using dask should be using `asarray` if they really need a dask array as input.

**Comment by shoyer** [comment]
I think we should definitely error more clearly here.

**Comment by jakirkham** [comment]
@djhoese, any interest in submitting a PR?

**Comment by djhoese** [comment]
Sure. I was just talking to people about how I needed more merged dask PRs.

You ok with a simple `isinstance` with a `raise ValueError`? Message could be something like:

> Array is already a dask array. Use 'asarray' or 'rechunk' instead.

**Comment by jakirkham** [comment]
Yeah that seems reasonable to me. 👍
