### ISSUE TITLE
DataFrame.to_parquet() with PyArrow does now properly honor compression flag 

### ISSUE THREAD

**Issue by jmcotelo** [dask/dask#5266]
dask version 2.2.0

When using  `to_parquet(..., engine='pyarrow')`, no matter which compression scheme you (eg: `compression='brotli'`, or even `compression='none'`) it always uses snappy. Given some dataframe `df` (done with real and fake data), the following three statements produce the same results:

```
df.to_parquet("foo", engine='pyarrow', compression='snappy')
df.to_parquet("foo", engine='pyarrow',compression='brotli')
df.to_parquet("foo", engine='pyarrow', compression='none')
df.to_parquet("foo", engine='pyarrow')
```
After some fiddling, i think there is a missing ` compression=compression` in here:
https://github.com/dask/dask/blob/ab6acc5e224986dec8e21455b812ad61a9e65648/dask/dataframe/io/parquet/core.py#L455-L465

I'm not 100% sure but I think it could be an easy fix. Just passing the kwargs to the delayed write function like this:
```
        dwrite(
            d,
            path,
            fs,
            filename,
            partition_on,
            write_metadata_file,
            fmd=meta,
            index_cols=index_cols,
            compression=compression,
            **kwargs_pass
      )
```
If no one else wants to deal with this, I could make a PR for it.

**Comment by TomAugspurger** [comment]
Your diagnosis looks correct. Would welcome a PR to fix (especially if you can think of a way to easily test this).

**Comment by jmcotelo** [comment]
The only way i can think of is by creating some dataframe with dummy data and checking if written parquet files differ in size. I don't know how to put that into the test suite; I'm not familiar enough with dask testing suite (or even testing in general). 

I'd definitely try to put together a PR, tough. I'd appreciate any help :)

**Comment by TomAugspurger** [comment]
@martindurant my know.

**Comment by martindurant** [comment]
I don't know how to do it with pyarrow, but fastparquet gives full information about the encoding of every chunk of every pice of the data. I assume the pyarrow "pieces" do the same, should be easily found by tab-completing
```
dataset = pq.ParquetDataset(path)
dataset.pieces
```

**Comment by jakirkham** [comment]
@jmcotelo, does Martin's comment help?

**Comment by jmcotelo** [comment]
Sorry, I've been pretty damn busy lately and had no time to keep it up. I guess so but couldn't check it out. BTW, if someone else wants to do it, it's yours, because it is pretty hard to me finding spare time to do it right in the next days.
