### ISSUE TITLE
Dask parquet metadata w/ ~2k files very slow

### ISSUE THREAD

**Issue by talebzeghmi** [dask/dask#5272]
## To reproduce:

* Given an S3 directory of ~2k parquet files (~20mb) without a metadata summary file. In our case written by Spark.
* Read it 
```python
dask_df = dataframe.read_parquet("s3://path/*parquet")
```

## Result
It takes several minutes to `read_metadata`.

## Suggested fix
`read_parquet()` documentation for gather_statistics:
>     gather_statistics : bool or None (default).
>         Gather the statistics for each dataset partition. By default,
>         this will only be done if the _metadata file is available. Otherwise,
>         statistics will only be gathered if True, because the footer of
>         every file will be parsed (which is very slow on some systems).

Arrow and FastParquet engines read each file even when `gather_statistics is None` and the metadata file doesn't exist.  

Proposed fix is to change occurrences of `gather_statistics is not False` to `gather_statistics  is True` to follow the intent: [search of occurrences](https://github.com/dask/dask/search?q=%22gather_statistics+is+not+False%22&unscoped_q=%22gather_statistics+is+not+False%22)

**Comment by jakirkham** [comment]
Looks like this is being handled with PR ( https://github.com/intake/intake-parquet/pull/14 ), correct?

**Comment by talebzeghmi** [comment]
> Looks like this is being handled with PR ( [intake/intake-parquet#14](https://github.com/intake/intake-parquet/pull/14) ), correct?

That is a workaround for Intake only to pass in `gather_statistics` parameter.  The problem would still exist for those that use Dask to read from S3 parquet written by Spark.

**Comment by ian-r-rose** [comment]
Since #8072 and #8092 we can now read metadata in parallel, which should resolve this issue. If that's not the case @talebzeghmi let us know, and we can reopen.

There are still scalability problems when the metadata gets large, but those are tracked in other issues (cf. #4410)
