### ISSUE TITLE
Feature request: Add a total number of workers count to the web UI

### ISSUE THREAD

**Issue by simaster123** [dask/dask#5275]
Perhaps in the workers tab.  

This would be helpful to verify if all workers are connected / staying connected to the scheduler during tests.

**Comment by bnaul** [comment]
I forget if there's another issue for this but I had also thought it could be a Total row in the Workers tab, which would include both this and total cores, total RAM, ...

**Comment by mrocklin** [comment]
I'm in favor

**Comment by jakirkham** [comment]
Any interest in submitting this PR, @simaster123?

**Comment by arpit1997** [comment]
@simaster123 https://github.com/dask/distributed/tree/master/distributed/dashboard This is where the code for web ui resides

**Comment by jsignell** [comment]
I took a pass at it @simaster123 in https://github.com/dask/distributed/pull/3464. Let me know if that fits your needs.
