### ISSUE TITLE
compute() function attempting to connect to Oracle instead of dask dataframe

### ISSUE THREAD

**Issue by typicalanalytical** [dask/dask#5276]
This [SO question](https://stackoverflow.com/questions/57469457/how-to-load-subset-of-large-oracle-table-into-dask-dataframe) lead to discovery of and documents the bug.

**Comment by jakirkham** [comment]
Sorry @typicalanalytical I'm afraid I don't follow. Would you be able to include an [MCVE in the OP of this issue]( http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports ) for us to reproduce?

**Comment by jrbourbeau** [comment]
@typicalanalytical are you still encountering this behavior? Are you able to provide a minimal example?

**Comment by jrbourbeau** [comment]
Closing this issue for now. @typicalanalytical  please feel free to re-open if you're able to update with a minimal reproducible example.

**Comment by typicalanalytical** [comment]
Sorry I will try to create MCVE and re-open.  Thanks.

**Comment by jrbourbeau** [comment]
Sounds good, thanks @typicalanalytical
