### ISSUE TITLE
Profilers give 'AttributeError: __enter__' 

### ISSUE THREAD

**Issue by simaster123** [dask/dask#5279]
I'm trying to experiment with the profilers as described here: https://docs.dask.org/en/latest/diagnostics-local.html

But, I'm getting an error 'AttributeError: __enter__'

Using a Windows 10 machine.
dask: 2.2.0

My code:
```

from dask.diagnostics import Profiler as Dask_Profiler
from dask.diagnostics import ResourceProfiler as Dask_ResourceProfiler
from dask.diagnostics import CacheProfiler as Dask_CacheProfiler
from dask.diagnostics import visualize as Dask_Visualize

print('open is assigned to %r' % open)

with Dask_Profiler as prof, Dask_ResourceProfiler(dt=0.25) as rprof, Dask_CacheProfiler as cprof:
         self.parquet_metadata_delayed_arry = dask.compute(*self.parquet_metadata_delayed_arry)
self.logger.info(prof.results[0])
self.logger.info(rprof.results[0])
self.logger.info(cprof.results[0])
Dask_Visualize([prof, rprof, cprof])

```

Snippet of output:

```
open is assigned to <built-in function open>

2019-08-15 01:00:57,471 - CRITICAL - Traceback (most recent call last):
File "C:/Users/Dan/PycharmProjects/ML_Training_v2/ML_training.py", line 1241, in determine_batches
    with Dask_Profiler as prof, Dask_ResourceProfiler(dt=0.25) as rprof, Dask_CacheProfiler as cprof:
AttributeError: __enter__

```

**Comment by jakirkham** [comment]
I think you will want to replace `Dask_Profiler` with `Dask_Profiler()` and `Dask_CacheProfiler` with `Dask_CacheProfiler()` as you will want instances of these. Additionally you will need `import dask` as you are using `dask.compute` later.

Wasn't able to go further than that as `self` is being used here and this code does not appear to be in a method of some object. Also we are missing what `logger` would be.

Anyways try those things and see how it goes. 🙂

**Comment by jrbourbeau** [comment]
@simaster123 did the suggestions from @jakirkham fix this issue?

**Comment by jrbourbeau** [comment]
@simaster123 is it safe to close this issue?

**Comment by simaster123** [comment]
Yes, thank you all.
