### ISSUE TITLE
Dask config value setting question

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#5282]
Is `dask.config.set(**dict_mapping)` a supported way to set configuration values? 

Previously, using `with dask.config.set(**mapping):` would set the config options in `mapping` inside the `with` context. For example (on commit `d92f4015a1da3da10c04c682ed2acae8469e9576`):

```python
In [1]: import dask

In [2]: dask.config.get('array.svg')
Out[2]: {'size': 120}

In [3]: with dask.config.set(**{'array.svg': 2}):
   ...:     print(dask.config.get('array.svg'))
   ...:
2

In [4]: dask.config.get('array.svg')
Out[4]: {'size': 120}
```

with the changes in #5226, this is no longer the case. On the current `master`, we have:

```python
In [1]: import dask

In [2]: dask.config.get('array.svg')
Out[2]: {'size': 120}

In [3]: with dask.config.set(**{'array.svg': 2}):
   ...:     print(dask.config.get('array.svg'))
   ...:
{'size': 120}

In [4]: dask.config.get('array.svg')
Out[4]: {'size': 120}
```

However, removing the `**` (i.e. `with dask.config.set({'array.svg': 2}):`) does work on `master`. 

The [config docs](https://docs.dask.org/en/latest/configuration.html#directly-within-python) only make reference to `dask.config.set(mapping)` for setting config values, not passing as keyword argument like `dask.config.set(**mapping)`. Is the descrepency here a backwards compatibility issue, or was `dask.config.set(**mapping)` previously not a supported way to set config values?

**Comment by jrbourbeau** [comment]
cc @jcrist @djhoese

**Comment by jcrist** [comment]
```python
In [3]: with dask.config.set(**{'array.svg': 2}):
   ...:     print(dask.config.get('array.svg'))
   ...:
```

Using kwargs in `config.set` (as you're doing above), is valid, but splits on `__` instead of `.` for nested parameters (since `array__svg` is a valid parameter name, but `array.svg` isn't). However, due to how `**kwargs` works in python, this just happened to work before. If you already have a mapping, you shouldn't splat it into the function call, you should just pass it directly.

Unless you think otherwise, I don't think this is a bug, just a misuse.

**Comment by jcrist** [comment]
To be more clear, both of these work as intended:

```python
In [3]: with dask.config.set(array__svg__size=140):
   ...:     print(dask.config.get("array.svg"))
   ...:
{'size': 140}

In [4]: with dask.config.set({"array.svg.size": 140}):
   ...:     print(dask.config.get("array.svg"))
   ...:
   ...:
{'size': 140}
```

**Comment by mrocklin** [comment]
Is it easy to support anyway?  Are there problems with supporting it?

**Comment by jcrist** [comment]
It's possible, but imo a weird thing to do. Functions shouldn't expect keyword arguments that aren't valid python parameters. I'd rather not, and declare any (unlikely) past uses of this user error.

**Comment by jcrist** [comment]
This also was completely undocumented behavior before (docstring from before this change):

https://github.com/dask/dask/blob/d92f4015a1da3da10c04c682ed2acae8469e9576/dask/config.py#L263-L273

**Comment by mrocklin** [comment]
OK, no objection from my end

**Comment by jrbourbeau** [comment]
> Functions shouldn't expect keyword arguments that aren't valid python parameters

This seems reasonable to me

Thanks for the responses all! Closing.
