### ISSUE TITLE
 sklearn.model_selection.StratifiedKFold using Dask arrays produces confusing number of dimensions

### ISSUE THREAD

**Issue by javierfs** [dask/dask#5286]
I would like to use a stratified cross-validation approach to evaluate the performance of a Dask XGBoost Classifier I am trying with a large dataset and a very high imbalanced dataset (20 different classes):

    <class 'pandas.core.frame.DataFrame'>
    Int64Index: 194881 entries, 0 to 194880
    Columns: 76664 entries, actual_label to previous_word_€TZS09
    dtypes: float32(7), int64(1), uint8(76656)
    memory usage: 13.9 GB

    class #instances
    5     52477
    14    26087
    8     17000
    12    15632
    15    12908
    4     11637
    11    10650
    18     9644
    17     8149
    1      5849
    9      5811
    13     5330
    2      4551
    7      2680
    19     2578
    0      1118
    10      921
    16      897
    6       586
    3       376

For that reason, I am using Dask structures:

    dfp = pd.read_parquet(filename)
    
    X = dfp[dfp.columns[1:]].values
    y = dfp['actual_label'].values
    
    print('Starting chunking')
    dX = da.from_array(X, chunks=(4000, 4000))
    dy = da.from_array(y, chunks=(4000))

Then

    splits = 3
    cv = StratifiedKFold(n_splits=splits)
    for i, (train_index, test_index) in enumerate(cv.split(dX, dy)):
    
        print('[Fold %d/%d]' % (i + 1, splits))
        print('type:{} , shape {}'.format(str(type(train_index)),str(train_index.shape)))
        print('type:{} , shape: {}'.format(str(type(test_index)),str(test_index.shape)))

However if I print the shapes and types of ```dX, dy, train_index, and test_index```, it outputs different dimensions:  

    print('type:{} , shape: {}'.format(str(type(dX)),str(dX.shape)))

 > type: class 'dask.array.core.Array'  , shape: (194881, 76663)

    print('type:{} , shape: {}'.format(str(type(dy)),str(dy.shape)))

 > type: class 'dask.array.core.Array'  , shape: (194881,)
 

    print('type:{} , shape: {}'.format(str(type(train_index)),str(train_index.shape)))

> type: class 'numpy.ndarray' , shape: (129914,)

    print('type:{} , shape: {}'.format(str(type(test_index)),str(test_index.shape)))

> type: class 'numpy.ndarray' , shape: (64967,)

Therefore I cannot run the following as it is different dimensions. 

    train_X = dX[train_index,:]
    train_y = dy[train_index]
    test_X = dX[test_index,:]
    test_y = dy[test_index]

Anyone knows how to use StratifiedKFold from sklearn and Dask arrays?

**Comment by TomAugspurger** [comment]
Just to clarify, you're using `sklearn.model_selection.StratifiedKFold`?

Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Is dask.dataframe relevant? Is the parquet IO relevant?

**Comment by javierfs** [comment]
@TomAugspurger yes, exactly it is _sklearn.model_selection.StratifiedKFold_ 
Is relevant in the way that I want to show where dX and dy comes from. Perhaps, the problem is the dimensions of the input (dX, dy) of _sklearn.model_selection.StratifiedKFold_  as I formed Dask arrays in chunks=(4000, 4000)

**Comment by TomAugspurger** [comment]
> It is relevant in the way that I want to show where dX and dy come from.

So you don't see any issue when you just use dask arrays with those dimensions?

**Comment by javierfs** [comment]
@TomAugspurge There is no errors. But dimensions does not make sense to me when I  do this:

`train_X = dX[train_index,:]`

where:

`dX -> shape: (194881, 76663)`
```
train_index -> type:<class 'numpy.ndarray'> , shape: (129914,)
train_X -> type:<class 'dask.array.core.Array'> , shape: (129914, 76663)
```

**Comment by TomAugspurger** [comment]
A minimal example would be helpful: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jakirkham** [comment]
@javierfs, would you be able to supply and MRE as requested? 🙂

**Comment by jrbourbeau** [comment]
I'm going to close this issue for the time being. @javierfs please feel free to re-open if you're able to produce an reproducible example
