### ISSUE TITLE
dask 2.2.0 breaks gcsfs

### ISSUE THREAD

**Issue by schnekke** [dask/dask#5287]
$ python3 -m pip freeze | egrep 'dask|gcsfs'
dask==2.2.0
gcsfs==0.2.3
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
>>> import gcsfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gcsfs/__init__.py", line 4, in <module>
    from .dask_link import register as register_dask
  File "/usr/local/lib/python3.5/dist-packages/gcsfs/dask_link.py", line 126, in <module>
    register()
  File "/usr/local/lib/python3.5/dist-packages/gcsfs/dask_link.py", line 121, in register
    dask.bytes.core._filesystems['gcs'] = DaskGCSFileSystem
AttributeError: module 'dask.bytes.core' has no attribute '_filesystems'
>>> 

$ python3 -m pip install dask==2.1.0
   Successfully installed dask-2.1.0
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
>>> import gcsfs
>>>

**Comment by jrbourbeau** [comment]
Thanks for opening up this issue @schnekke. Could you try with the latest release of `gcsfs` (version `0.3.0`)?

**Comment by jrbourbeau** [comment]
@schnekke any luck with the latest `gcsfs` release? I'm not able to reproduce the error locally:

```python
In [1]: import dask

In [2]: dask.__version__
Out[2]: '2.3.0+2.gfbc37374'

In [3]: import gcsfs

In [4]: gcsfs.__version__
Out[4]: '0.3.0'
```

**Comment by schnekke** [comment]
@jrbourbeau 
Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1037-gcp x86_64)
python3 -m pip install --upgrade gcsfs==0.3.0
Collecting gcsfs==0.3.0
ERROR: Could not find a version that satisfies the requirement gcsfs==0.3.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3)
ERROR: No matching distribution found for gcsfs==0.3.0

**Comment by jrbourbeau** [comment]
What version of Python are you using?

**Comment by jrbourbeau** [comment]
The latest release of `gcsfs` (`0.3.0`) requires Python `>=3.6`. Although the minimum version seems to have been updated recently as the current `master` for `gcsfs` supports Python `>=3.5`.
