### ISSUE TITLE
Add meta to the repr for dask arrays?

### ISSUE THREAD

**Issue by shoyer** [dask/dask#5288]
It seems like `meta` would be nice to know for debugging. It's already in the HTML repr -- what about putting it in the text repr, too?

For example, instead of:
```
dask.array<array, shape=(3, 3), dtype=float64, chunksize=(3, 3)>
```
we could have:
```
dask.array<array, shape=(3, 3), dtype=float64, chunksize=(3, 3), meta=sparse.COO>
```

Or maybe drop the existing `name` field in favor of meta, since that isn't especially informative.

This came up in https://github.com/pydata/xarray/pull/3211, cc @crusaderky

**Comment by mrocklin** [comment]
Seems fine to me.

**Comment by jrbourbeau** [comment]
+1 adding `meta` to the text repr seems like a good idea to me

**Comment by jakirkham** [comment]
cc @pentschev
