### ISSUE TITLE
Feature request: support pandas NamedAgg

### ISSUE THREAD

**Issue by karldw** [dask/dask#5294]
pandas 0.25.0 [introduced](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#groupby-aggregation-with-relabeling) a new "named aggregation" feature. It would be lovely if dask.dataframe supported `NamedAgg` as well. 

Here's an example, copied from the pandas docs, that works in pandas but not dask.
```python
import numpy as np
import dask.dataframe as dd
import pandas as pd
animals = pd.DataFrame({'kind': ['cat', 'dog', 'cat', 'dog'],
                            'height': [9.1, 6.0, 9.5, 34.0],
                            'weight': [7.9, 7.5, 9.9, 198.0]})
animals = dd.from_pandas(animals, npartitions=1)
animals.groupby("kind").agg(
        min_height=pd.NamedAgg(column='height', aggfunc='min'),
        max_height=pd.NamedAgg(column='height', aggfunc='max'),
        average_weight=pd.NamedAgg(column='weight', aggfunc=np.mean),
   )
#> Traceback (most recent call last):
#> TypeError: agg() got an unexpected keyword argument 'min_height'
```

(This `NamedAgg` feature is absolutely not essential; pandas worked well for years without it.)

**Comment by TomAugspurger** [comment]
Dask should be able to support this without any problems.

---

On the implementation: pandas does this by converting the NamedAgg to the older list of aggregations, followed by a renaming. Something similar may work for dask

```python
In [1]: import pandas as pd

In [2]: import numpy as np
   ...: import dask.dataframe as dd
   ...: import pandas as pd
   ...: animals = pd.DataFrame({'kind': ['cat', 'dog', 'cat', 'dog'],
   ...:                             'height': [9.1, 6.0, 9.5, 34.0],
   ...:                             'weight': [7.9, 7.5, 9.9, 198.0]})
   ...: animals = dd.from_pandas(animals, npartitions=1)
   ...:

In [3]: kwargs = dict(min_height=pd.NamedAgg(column='height', aggfunc='min'),
   ...:         max_height=pd.NamedAgg(column='height', aggfunc='max'),
   ...:         average_weight=pd.NamedAgg(column='weight', aggfunc=np.mean),)

In [4]: pd.core.groupby.generic._normalize_keyword_aggregation(kwargs)
Out[4]:
(OrderedDict([('height', ['min', 'max']),
              ('weight',
               [<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>])]),
 ('min_height', 'max_height', 'average_weight'),
 [('height', 'min'), ('height', 'max'), ('weight', 'mean')])

In [5]: kwargs2, columns, order = pd.core.groupby.generic._normalize_keyword_aggregation(kwargs)

In [9]: animals.groupby('kind').agg(kwargs2)
Out[9]:
Dask DataFrame Structure:
                height            weight
                   min      max     mean
npartitions=1
               float64  float64  float64
                   ...      ...      ...
Dask Name: aggregate-agg, 3 tasks

In [10]: res = animals.groupby('kind').agg(kwargs2)

In [11]: res.columns = columns

In [12]: res
Out[12]:
Dask DataFrame Structure:
              min_height max_height average_weight
npartitions=1
                 float64    float64        float64
                     ...        ...            ...
Dask Name: rename, 4 tasks

In [13]: res.compute()
Out[13]:
      min_height  max_height  average_weight
kind
cat          9.1         9.5            8.90
dog          6.0        34.0          102.75

```

There are a couple issues with that, but that's the basic idea. Are you interested in working on it @karldw?

**Comment by karldw** [comment]
I can take a look! (probably next week)

**Comment by arpit1997** [comment]
@karldw Are you working on this? I can take this up if you are busy. cc: @TomAugspurger

**Comment by karldw** [comment]
I've been slow, but yes. I wanted to ask a couple of questions.
- How do you feel about importing the non-public `_normalize_keyword_aggregation` from pandas?
- Do you want to support named aggregations that aren't passed as `pd.NamedAgg`?
  - For example, pandas supports aggregations like this for Series:
`grouped_series.agg(a="sum", b="min")`

**Comment by karldw** [comment]
@arpit1997, this ended up being a little fiddly. If you want to work on this, feel free to move ahead and take anything you find useful from the [code](https://github.com/karldw/dask/tree/e7807924af318a74613d0fce2e76d2ae4525c859) I just pushed.

There are some design decisions to make too, raised in the questions above.

**Comment by arpit1997** [comment]
@karldw Thank you for your reply and the current work you posted. I can pick from here.

**Comment by TomAugspurger** [comment]
I’d recommend open an issue on pandas tracker about making normalize_keyword_aggregation public before using it, if it’s necessary.

**Comment by arpit1997** [comment]
@TomAugspurger I am looking into it right now. Will update if `normalize_keyword_aggregation` needs to be used.

**Comment by arpit1997** [comment]
@TomAugspurger Both `_normalize_keyword_aggregation` and `_is_multi_agg_with_relabel`needs to be used for Named Aggregation to be supported. Former is to construct the dict like parameter for agg and latter is to check is provided kwargs are named agg parameters. Opening an issue on `pandas-dev/pandas`

**Comment by lorenh516** [comment]
Bumping this issue

**Comment by TomAugspurger** [comment]
I think https://github.com/pandas-dev/pandas/issues/28472 is the latest issue on the pandas side. Dask could use private APIs (we do in other places), but I'd prefer to see that paired with an acknowledgement that it won't change in pandas.

**Comment by ChrisJar** [comment]
Is anyone currently working on this? Would be happy to pick this up
