### ISSUE TITLE
Please add a discussion of dask security to the docs

### ISSUE THREAD

**Issue by csbrown** [dask/dask#5301]
**Feature Request:**

I am considering creating a dask cluster that will be sending tasks over an insecure public network.  Since a dask task essentially tells my worker to execute arbitrary code, there is a naive opportunity for, e.g. MITM attacks.  I presume that there has been a lot of effort on the part of dask developers to ensure the security of communications between dask nodes.  However, I cannot seem to find any documentation of any security stuff.  Where can I find a discussion of how dask communications are secured, and can such a thing be added to the docs?

**Comment by quasiben** [comment]
@csbrown just in case you haven't the page.  Dask has security docs here: https://distributed.dask.org/en/latest/tls.html
