### ISSUE TITLE
un-numpy-like behavior of `da.pad` with stats 

### ISSUE THREAD

**Issue by d-v-b** [dask/dask#5303]
`da.pad` with `mode` set to a statistic (e.g., `minimum`) a) doesn't match numpy and b) gives a confusing error message when it fails. The source of this problem is how `da.pad` tries to calculate the `stat_length` parameter when that kwarg is not specified.  

If I have the time, I can put together a PR to fix this. It should not be too hard. The problem is this line: https://github.com/dask/dask/blob/master/dask/array/creation.py#L1007, which blindly uses `args[0]` as `stat_length` without an earlier check for whether `stat_length` has been supplied as a `kwarg`. 

MRE: 
```
import dask.array as da
# this works:
arr_2d = da.zeros((1,1))
da.pad(arr_2d, pad_width=1, mode='minimum')

# error: `TypeError: `pad_value` must be composed of integral typed values.`
arr_3d  = da.zeros((1,1,1))
da.pad(arr_3d, pad_width=1, mode='minimum')

# In numpy, pad with mode=$statistic uses an extra kwarg called `stat_length, which defaults to None. 
# In `da.pad`, passing stat_length=None doesn't work. This produces the same confusing error about the non-integral type of the pad_value.
da.pad(arr_3d, pad_width=1, mode='minimum', stat_length=None)

# this gives equivalent behavior to np.pad with stat_length=None:
da.pad(arr_3d, pad_width=1, mode='minimum', stat_length=arr_3d.shape)
```

**Comment by jrbourbeau** [comment]
@d-v-b thanks for raising this issue and investigating the `da.pad` internals! I'm able to reproduce the same `TypeError`. 

> If I have the time, I can put together a PR to fix this

That would be much appreciated, thanks! 

cc @jakirkham

**Comment by mark-boer** [comment]
Let me just start by saying that I think Dask is a really cool project :-)

@d-v-b Cool you are working on this. I'm currently working on implementing a pad method for [xarray](https://github.com/pydata/xarray/issues/2605), I saw some of the unittest fail and wrote a little script to compare numpy as dask's implementation. I saw a couple of ways that numpy and xarray seem to differ:

1. The issue you mention above where the default stat_length kwarg fails.
2. When using `pad_widths= ((2, 3),)` all modes fail with the same error message as above. 
3. When using `mode="mean"`, Dask converts the array to floats, while numpy keeps the array as integers.
4. Modes `symmetric`, `reflect` and `wrap`  can result in output arrays that have a different shape than the numpy equivalent. 

Do you think I should create several seperate issues in the Dask issue tracker?

This is the script I used to test this:
```
import dask.array as da
import numpy as np

np_arr = np.arange(2*3*4).reshape(2,3,4)
da_arr = da.from_array(np_arr, chunks="auto")

for pad_widths in [2, (2,), ((2, 3),), ((3, 1), (0,0), (2, 0))]:
    for mode in ["constant", "edge", "linear_ramp", "maximum", "mean", "minimum", "reflect", "symmetric", "wrap"]: #[median, empty]

        np_result = np.pad(np_arr, pad_widths, mode=mode)
        try:
            da_result = da.pad(da_arr, pad_widths, mode=mode).compute()
        except Exception as e:
            print("ERROR", mode, str(pad_widths))
            print(e)
            continue

        try:
            assert np_result.dtype == da_result.dtype, "dtype does not match"
            assert np_result.shape == da_result.shape, "shapes do not match"
            np.testing.assert_equal(np_result, da_result), "values do not match"
            print("successfull:", mode, str(pad_widths))
        except AssertionError as e:
            print("mismatch:", mode, str(pad_widths))
            print(e)
```

**Comment by d-v-b** [comment]
@mark-boer I haven't touched my code for fixing this in a while -- my progress is stalled while waiting for answers to the questions I asked in my last comment on the issue. 

That being said, I think there should be tests that catch these problems, so I assume additions to the test suite would be appreciated (and maybe we can catch @jakirkham's attention :)

**Comment by TomAugspurger** [comment]
In general, I think we should assume that undocumented differences between the two are unintentional bugs. PRs fixing these (small, independent ones each focused on a specific issue, if possible) would be welcome.

**Comment by jakirkham** [comment]
When I wrote this, I think we matched NumPy pretty closely. Since then NumPy revamped how they pad arrays to be more performant ( https://github.com/numpy/numpy/pull/11358 ) with some follow-up PRs. It's possible something changed through that churn. I don't have any objection to either raising an issue with NumPy if they changed behavior or aligning to it on our end.

**Comment by d-v-b** [comment]
Ah, thanks for the historical context @jakirkham, that explains a lot. If I have time soon I'll look into bringing dask into alignment with numpy in this area.

**Comment by jakirkham** [comment]
Thanks @d-v-b! 😄
