### ISSUE TITLE
RuntimeWarning: Multiple sorted columns found, cannot autodetect index

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#5305]
Dask 2.3.0
I am using daskdataframe.read_parquet(columns=[],index=False,...)

A RuntimeWarning appears with 80K lines of error output, concerning a pickle file protocol after this appears.
C:\g\test\lib\dask\dataframe\io\parquet\core.py:223: RuntimeWarning: Multiple sorted columns found, cannot autodetect index

**Comment by jrbourbeau** [comment]
@apiszcz thanks for raising an issue! Are you able to provide a minimal reproducible example https://blog.dask.org/2018/02/28/minimal-bug-reports? Are you able to explicitly specify which column to use as the DataFrame index?

**Comment by jrbourbeau** [comment]
Just checking in here, @apiszcz are you able to provide a minimal example?

**Comment by apiszcz** [comment]
We can close, assume this was my problem, user error, reviewing the code, I changed my access methods and do not have that issue. Thank you.

**Comment by jrbourbeau** [comment]
Glad to hear it's no longer an issue for you. Thanks for closing!
