### ISSUE TITLE
Small Typo in `delayed` Documentation

### ISSUE THREAD

**Issue by eugeneh101** [dask/dask#5308]
In the documentation for the `delayed` best practices (https://github.com/dask/dask/blob/master/docs/source/delayed-best-practices.rst), there appears to be small typo with the parentheses.

Under the section titled `Avoid too many tasks`, I think the line of code 
````result_batch = dask.delayed(batch, range(i, i + 10000))````
should be replaced by 
```result_batch = dask.delayed(batch)(range(i, i + 10000))```

Currently, as I run the exact code as specified in the documentation, it appears the `delayed()` decorator call with a second argument  (which is `name`) sets the `Delayed` object's key name. Hence, the `key` name is `range(0, 10000)`.

Hope that helps,
Eugene

**Comment by jrbourbeau** [comment]
Good catch @eugeneh101! Do you have any interest in submitting a PR with this fix? No obligation though 

Information on dask development can be found at https://docs.dask.org/en/latest/develop.html

**Comment by eugeneh101** [comment]
Hello jrbourbeau!

Thank for the quick reply! I just submitted a PR, which is my first open source contribution! I came from the Apache Spark and Beam world and I really like Dask. I hope the Dask community keeps growing!

-Eugene

**Comment by mrocklin** [comment]
> which is my first open source contribution!

Welcome!

**Comment by jrbourbeau** [comment]
Closed by #5311

**Comment by eugeneh101** [comment]
Thanks for the welcoming and quick-responding community! 
I really like Dask and it's extremely expressive--not only the collections but also `Delayed` and `Future` types. I hope to get Dask working in the distributed mode soon over containers.
