### ISSUE TITLE
Feature: Implement explode for Series

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#5309]
Very excited to see Pandas finally got explode https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#series-explode-to-split-list-like-values-to-rows

I use this function a good amount in spark. It's extremely useful.

Can we implement in dask? Are there any additional considerations due to the fact that this changes the size of a dataframe or is it just a matter of exposing the API.

**Comment by mrocklin** [comment]
No special consideration needs to be taken from changing the size of the
dataframe.  It looks like this might be a trivial application of
map_partitions.

If you're interested I would try using map_partitions, and if that seems to
do the right thing, maybe it's a one-line PR (plus a test and api-docs
addition)

**Comment by arpit1997** [comment]
@mrocklin @jrbourbeau I can take this for the weekend if no-one else is working on it.

**Comment by quasiben** [comment]
@arpit1997 Thanks!  let us know if you need any help

**Comment by birdsarah** [comment]
I can confirm that explode inside a map_partitions call works well.

**Comment by arpit1997** [comment]
@birdsarah Can you close this issue?

**Comment by mrocklin** [comment]
In the future @arpit1997 if you add text like `Fixes #5309` in your PR then it will automatically close that issue.  

Closing.  Thanks @birdsarah for raising this and @arpit1997 for resolving it!

**Comment by arpit1997** [comment]
@mrocklin sorry about that, forgot to add. Will do it next time.

**Comment by mrocklin** [comment]
Either way is fine.  It's just a nice GitHub trick that I thought you would
enjoy.
