### ISSUE TITLE
Inconsistent nbytes values returned for dask arrays composed of sparse arrays 

### ISSUE THREAD

**Issue by benbovy** [dask/dask#5313]
The value returned by ``dask.array.core.Array.nbytes`` property (i.e., array size * sizeof(dtype)) doesn't really make sense when a dask array is composed of sparse arrays:

```python
In [1]: import dask.array as da

In [2]: import sparse

In [3]: s = sparse.COO({(0, 0): 1}, shape=(10000, 10000))

In [4]: s.nbytes
Out[4]: 24

In [5]: a = da.from_array(s, chunks=(1000, 1000))

In [6]: a.nbytes
Out[6]: 800000000

In [7]: dask.__version__
Out[7]: '2.3.0'
```

I'm happy to submit a PR to improve this, although I'm not sure if this is trivial or not to implement (I'm not familiar with dask internals). I guess that lazy dask arrays don't make this straightforward.

**Comment by benbovy** [comment]
That said, I noticed that ``a.persist()`` seems to coerce sparse arrays into numpy arrays:

```python
In [11]: type(a._meta)
Out[11]: sparse.coo.core.COO

In [12]: p = a.persist()

In [13]: type(p._meta)
Out[13]: numpy.ndarray
```

So the behavior in my previous comment might be consistent after all (i.e., ``nbytes`` returns the size of data if it is written in memory, or ``.persist()`` should really preserve the original array type and that's another issue.

**Comment by TomAugspurger** [comment]
Persist changing to dense looks like a bug.

On the original issue, I'm really not sure how to get a correct nbytes...
You would need to know the density,
which Dask can't know lazily (AFAIK).

**Comment by benbovy** [comment]
I think the ``persist ._meta`` is related to #4888 

I'm happy to submit a PR for this specific case (in fact, I have already a fix here: https://github.com/benbovy/dask/tree/fix-persist-array-meta), but I don't know if individual PRs are the best way to deal with #4888 (see https://github.com/dask/dask/issues/4888#issuecomment-502075439). Please let me know.

cc @pentschev

**Comment by benbovy** [comment]
> On the original issue, I'm really not sure how to get a correct nbytes... You would need to know the density, which Dask can't know lazily (AFAIK).

Yes I'm afraid this is not possible. I'm leaving this issue open in case anyone has a good idea on how to improve this (e.g., docstrings, value returned, etc.), but feel free to close the issue if you think this is not worth it.

**Comment by mrocklin** [comment]
I don't expect us to find a good answer here.  I think that it was good to have the discussion (thanks to all involved) but yeah, I think it's probably best to close this.

**Comment by mrocklin** [comment]
> but I don't know if individual PRs are the best way to deal with

@benbovy please free free to open up an issue or PR whenever.  I think that @pentschev just didn't want to open up a new issue himself for every function in order to track them.  If you're running into something then yes, you should please raise an issue.

**Comment by benbovy** [comment]
@mrocklin that makes sense, done!
