### ISSUE TITLE
Executing dask delayed restarts Flask application on Windows local server

### ISSUE THREAD

**Issue by Harshitg** [dask/dask#5315]
I have implemented Dask delayed and compute to parallelize certain compute heavy code in a flask application running on windows localserver. There is a peculiar problem of application self restarting after executing the compute(*delayed_results) function. Here is the sample of the code for your perusal:
**app.py**

```
if __name__ == '__main__':
    from dask.distributed import Client
    client = Client(processes=True)  
    print(client)
    app.run(host='0.0.0.0', port=8080, debug=True)
```

views.py

```
delayed_results = [delayed(emi_cf_gen)(chunk) for chunk in proc_chunks]
MSE = compute(*delayed_results, scheduler="processes")
```

Any feedback or guidance would be much appreciated.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @Harshitg. Are you able to provide a minimal example? https://blog.dask.org/2018/02/28/minimal-bug-reports

**Comment by Harshitg** [comment]
@jrbourbeau - allow me a couple of days, i will update with an example.

**Comment by jrbourbeau** [comment]
Just checking in here, @Harshitg were you able to get a minimal example?

**Comment by jrbourbeau** [comment]
Closing this issue for now. @Harshitg please feel free to re-open if you're able to update with a minimal reproducible example.
