### ISSUE TITLE
Start dask worker with local directory

### ISSUE THREAD

**Issue by Selva163** [dask/dask#5316]
I'm having 6 python files which need to be transferred to the workers. I want to add workers dynamically. That is after I submit the task to the workers if I add a worker, will the tasks be assigned to the new worker? If so, the new worker should have the python files in its local directory. Though I start the worker with --local-directory option, it still creates a new directory within the mentioned dir. Is there a way to mention the dir as local directory where we have the python files?

**Comment by quasiben** [comment]
This is has since been resolved with the [upload_file](https://github.com/dask/distributed/pull/4238) plugin
