### ISSUE TITLE
read_sql_table creates delayed objects without provided sqlalchemy connection arguments

### ISSUE THREAD

**Issue by arpit1997** [dask/dask#5318]
I am trying to load a table from presto using Dask `read_sql_table`. The presto server runs on `https`. As per the [pyhive docs](https://github.com/dropbox/PyHive#passing-session-configuration) if server is on SSL you have to pass `{'engine_kwargs': {'connect_args': {'protocol': 'https'}}}`. 

Code:
```python
import dask.dataframe as dd
df = read_sql_table('test_extension', 'presto://server_url/hive',
                      index_col='col_name', divisions=[0, 30000, 60000], head_rows=100,
                       engine_kwargs={'connect_args': {'protocol': 'https'}})
# till here everything is fine it extracts metadata , creates correct number of partitions.
df.head()
```

`df.head` fails saying an http request was made to an https endpoint. I checked this using a debugger as well and the request is made with http protocol. 

I suspect the problem is at https://github.com/dask/dask/blob/6fd2eb57158dbf260e29311e84f6a389904f0ef2/dask/dataframe/io/sql.py#L191, this does not pass engine kwargs to https://github.com/dask/dask/blob/6fd2eb57158dbf260e29311e84f6a389904f0ef2/dask/dataframe/io/sql.py#L196

If the server is on http and I change protocol param to http then everything works.

**Comment by TomAugspurger** [comment]
How would you write the equivalent pandas call using `pandas.read_sql`? We need to get the connect_args passed through.

**Comment by arpit1997** [comment]
For `pandas.read_sql` I pass the connection object instead of Connection string. But as far as I have read in similar discussions it's quite complicated to pass the connection objects. @TomAugspurger

**Comment by TomAugspurger** [comment]
Right, they're generally not serializable. So it seems like we may need to pass some arguments through to `_read_sql_chunk` to create the engine which will be passed to `pd.read_sql`?

**Comment by arpit1997** [comment]
I can investigate things further and try to find a workaround or a solution which is not complicated like serialisation of sqlalchemy objects. @TomAugspurger

**Comment by arpit1997** [comment]
@TomAugspurger I will try sending a PR for this by tomorrow.
