### ISSUE TITLE
Problem with Fannie Mae data

### ISSUE THREAD

**Issue by xiaodaigh** [dask/dask#5326]
My system is Windows 10 and dask v2.3.0. 

I downloaded the [Fannie Mae data](https://loanperformancedata.fanniemae.com/lppub/index.html) 2016Q1 Performance data ( you need to register to download it).

```python
import dask.dataframe as dd

a = dd.read_csv("c:/data/Performance_All/Performance_2016Q1.txt", sep="|",
                dtype={7: 'double', 14: 'str', 15: 'str', 16:'str'})
a.columns = ["var" + str(i) for i in range(31)]
a.head()
a.to_parquet("c:/data/p03.parquet")

# the above runs fine, the below is not
a = dd.read_parquet("c:/data/p03.parquet", columns="var0")
```

I get

> Traceback (most recent call last):
>   File "C:\data\dask\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-5-677b8a531dd7>", line 1, in <module>
>     a = dd.read_parquet("c:/data/p03.parquet", columns="var0")
>   File "C:\data\dask\venv\lib\site-packages\dask\dataframe\io\parquet\core.py", line 114, in read_parquet
>     gather_statistics,
>   File "C:\data\dask\venv\lib\site-packages\dask\dataframe\io\parquet\core.py", line 155, in read_parquet
>     **kwargs
>   File "C:\data\dask\venv\lib\site-packages\dask\dataframe\io\parquet\arrow.py", line 115, in read_metadata
>     fs, paths, gather_statistics, **kwargs
>   File "C:\data\dask\venv\lib\site-packages\dask\dataframe\io\parquet\arrow.py", line 75, in _determine_dataset_parts
>     paths, filesystem=fs, **kwargs.get("dataset", {})
>   File "C:\data\dask\venv\lib\site-packages\pyarrow\parquet.py", line 1008, in __init__
>     self.validate_schemas()
>   File "C:\data\dask\venv\lib\site-packages\pyarrow\parquet.py", line 1061, in validate_schemas
>     dataset_schema))
> ValueError: Schema in c:/data/p03.parquet/part.1.parquet was different. 
> var0: int64
> var1: string
> var2: string
> var3: double
> var4: double
> var5: int64
> var6: int64
> var7: double
> var8: string
> var9: int64
> var10: string
> var11: string
> var12: double
> var13: string
> var14: string
> var15: null
> var16: null
> var17: double
> var18: double
> var19: double
> var20: double
> var21: double
> var22: double
> var23: double
> var24: double
> var25: double
> var26: double
> var27: double
> var28: string
> var29: double
> var30: string
> index: int64
> metadata
> --------
> {b'pandas': b'{"index_columns": ["index"], "column_indexes": [{"name": null, "'
>             b'field_name": null, "pandas_type": "unicode", "numpy_type": "obje'
>             b'ct", "metadata": {"encoding": "UTF-8"}}], "columns": [{"name": "'
>             b'var0", "field_name": "var0", "pandas_type": "int64", "numpy_type'
>             b'": "int64", "metadata": null}, {"name": "var1", "field_name": "v'
>             b'ar1", "pandas_type": "unicode", "numpy_type": "object", "metadat'
>             b'a": null}, {"name": "var2", "field_name": "var2", "pandas_type":'
>             b' "unicode", "numpy_type": "object", "metadata": null}, {"name": '
>             b'"var3", "field_name": "var3", "pandas_type": "float64", "numpy_t'
>             b'ype": "float64", "metadata": null}, {"name": "var4", "field_name'
>             b'": "var4", "pandas_type": "float64", "numpy_type": "float64", "m'
>             b'etadata": null}, {"name": "var5", "field_name": "var5", "pandas_'
>             b'type": "int64", "numpy_type": "int64", "metadata": null}, {"name'
>             b'": "var6", "field_name": "var6", "pandas_type": "int64", "numpy_'
>             b'type": "int64", "metadata": null}, {"name": "var7", "field_name"'
>             b': "var7", "pandas_type": "float64", "numpy_type": "float64", "me'
>             b'tadata": null}, {"name": "var8", "field_name": "var8", "pandas_t'
>             b'ype": "unicode", "numpy_type": "object", "metadata": null}, {"na'
>             b'me": "var9", "field_name": "var9", "pandas_type": "int64", "nump'
>             b'y_type": "int64", "metadata": null}, {"name": "var10", "field_na'
>             b'me": "var10", "pandas_type": "unicode", "numpy_type": "object", '
>             b'"metadata": null}, {"name": "var11", "field_name": "var11", "pan'
>             b'das_type": "unicode", "numpy_type": "object", "metadata": null},'
>             b' {"name": "var12", "field_name": "var12", "pandas_type": "float6'
>             b'4", "numpy_type": "float64", "metadata": null}, {"name": "var13"'
>             b', "field_name": "var13", "pandas_type": "unicode", "numpy_type":'
>             b' "object", "metadata": null}, {"name": "var14", "field_name": "v'
>             b'ar14", "pandas_type": "unicode", "numpy_type": "object", "metada'
>             b'ta": null}, {"name": "var15", "field_name": "var15", "pandas_typ'
>             b'e": "empty", "numpy_type": "object", "metadata": null}, {"name":'
>             b' "var16", "field_name": "var16", "pandas_type": "empty", "numpy_'
>             b'type": "object", "metadata": null}, {"name": "var17", "field_nam'
>             b'e": "var17", "pandas_type": "float64", "numpy_type": "float64", '
>             b'"metadata": null}, {"name": "var18", "field_name": "var18", "pan'
>             b'das_type": "float64", "numpy_type": "float64", "metadata": null}'
>             b', {"name": "var19", "field_name": "var19", "pandas_type": "float'
>             b'64", "numpy_type": "float64", "metadata": null}, {"name": "var20'
>             b'", "field_name": "var20", "pandas_type": "float64", "numpy_type"'
>             b': "float64", "metadata": null}, {"name": "var21", "field_name": '
>             b'"var21", "pandas_type": "float64", "numpy_type": "float64", "met'
>             b'adata": null}, {"name": "var22", "field_name": "var22", "pandas_'
>             b'type": "float64", "numpy_type": "float64", "metadata": null}, {"'
>             b'name": "var23", "field_name": "var23", "pandas_type": "float64",'
>             b' "numpy_type": "float64", "metadata": null}, {"name": "var24", "'
>             b'field_name": "var24", "pandas_type": "float64", "numpy_type": "f'
>             b'loat64", "metadata": null}, {"name": "var25", "field_name": "var'
>             b'25", "pandas_type": "float64", "numpy_type": "float64", "metadat'
>             b'a": null}, {"name": "var26", "field_name": "var26", "pandas_type'
>             b'": "float64", "numpy_type": "float64", "metadata": null}, {"name'
>             b'": "var27", "field_name": "var27", "pandas_type": "float64", "nu'
>             b'mpy_type": "float64", "metadata": null}, {"name": "var28", "fiel'
>             b'd_name": "var28", "pandas_type": "unicode", "numpy_type": "objec'
>             b't", "metadata": null}, {"name": "var29", "field_name": "var29", '
>             b'"pandas_type": "float64", "numpy_type": "float64", "metadata": n'
>             b'ull}, {"name": "var30", "field_name": "var30", "pandas_type": "u'
>             b'nicode", "numpy_type": "object", "metadata": null}, {"name": "in'
>             b'dex", "field_name": "index", "pandas_type": "int64", "numpy_type'
>             b'": "int64", "metadata": null}], "creator": {"library": "pyarrow"'
>             b', "version": "0.14.0"}, "pandas_version": "0.25.1"}'}
> vs
> var0: int64
> var1: string
> var2: string
> var3: double
> var4: double
> var5: int64
> var6: int64
> var7: double
> var8: string
> var9: int64
> var10: string
> var11: string
> var12: double
> var13: string
> var14: string
> var15: string
> var16: null
> var17: double
> var18: double
> var19: double
> var20: double
> var21: double
> var22: double
> var23: double
> var24: double
> var25: double
> var26: double
> var27: double
> var28: string
> var29: double
> var30: string
> index: int64
> metadata
> --------
> {b'pandas': b'{"index_columns": ["index"], "column_indexes": [{"name": null, "'
>             b'field_name": null, "pandas_type": "unicode", "numpy_type": "obje'
>             b'ct", "metadata": {"encoding": "UTF-8"}}], "columns": [{"name": "'
>             b'var0", "field_name": "var0", "pandas_type": "int64", "numpy_type'
>             b'": "int64", "metadata": null}, {"name": "var1", "field_name": "v'
>             b'ar1", "pandas_type": "unicode", "numpy_type": "object", "metadat'
>             b'a": null}, {"name": "var2", "field_name": "var2", "pandas_type":'
>             b' "unicode", "numpy_type": "object", "metadata": null}, {"name": '
>             b'"var3", "field_name": "var3", "pandas_type": "float64", "numpy_t'
>             b'ype": "float64", "metadata": null}, {"name": "var4", "field_name'
>             b'": "var4", "pandas_type": "float64", "numpy_type": "float64", "m'
>             b'etadata": null}, {"name": "var5", "field_name": "var5", "pandas_'
>             b'type": "int64", "numpy_type": "int64", "metadata": null}, {"name'
>             b'": "var6", "field_name": "var6", "pandas_type": "int64", "numpy_'
>             b'type": "int64", "metadata": null}, {"name": "var7", "field_name"'
>             b': "var7", "pandas_type": "float64", "numpy_type": "float64", "me'
>             b'tadata": null}, {"name": "var8", "field_name": "var8", "pandas_t'
>             b'ype": "unicode", "numpy_type": "object", "metadata": null}, {"na'
>             b'me": "var9", "field_name": "var9", "pandas_type": "int64", "nump'
>             b'y_type": "int64", "metadata": null}, {"name": "var10", "field_na'
>             b'me": "var10", "pandas_type": "unicode", "numpy_type": "object", '
>             b'"metadata": null}, {"name": "var11", "field_name": "var11", "pan'
>             b'das_type": "unicode", "numpy_type": "object", "metadata": null},'
>             b' {"name": "var12", "field_name": "var12", "pandas_type": "float6'
>             b'4", "numpy_type": "float64", "metadata": null}, {"name": "var13"'
>             b', "field_name": "var13", "pandas_type": "unicode", "numpy_type":'
>             b' "object", "metadata": null}, {"name": "var14", "field_name": "v'
>             b'ar14", "pandas_type": "unicode", "numpy_type": "object", "metada'
>             b'ta": null}, {"name": "var15", "field_name": "var15", "pandas_typ'
>             b'e": "unicode", "numpy_type": "object", "metadata": null}, {"name'
>             b'": "var16", "field_name": "var16", "pandas_type": "empty", "nump'
>             b'y_type": "object", "metadata": null}, {"name": "var17", "field_n'
>             b'ame": "var17", "pandas_type": "float64", "numpy_type": "float64"'
>             b', "metadata": null}, {"name": "var18", "field_name": "var18", "p'
>             b'andas_type": "float64", "numpy_type": "float64", "metadata": nul'
>             b'l}, {"name": "var19", "field_name": "var19", "pandas_type": "flo'
>             b'at64", "numpy_type": "float64", "metadata": null}, {"name": "var'
>             b'20", "field_name": "var20", "pandas_type": "float64", "numpy_typ'
>             b'e": "float64", "metadata": null}, {"name": "var21", "field_name"'
>             b': "var21", "pandas_type": "float64", "numpy_type": "float64", "m'
>             b'etadata": null}, {"name": "var22", "field_name": "var22", "panda'
>             b's_type": "float64", "numpy_type": "float64", "metadata": null}, '
>             b'{"name": "var23", "field_name": "var23", "pandas_type": "float64'
>             b'", "numpy_type": "float64", "metadata": null}, {"name": "var24",'
>             b' "field_name": "var24", "pandas_type": "float64", "numpy_type": '
>             b'"float64", "metadata": null}, {"name": "var25", "field_name": "v'
>             b'ar25", "pandas_type": "float64", "numpy_type": "float64", "metad'
>             b'ata": null}, {"name": "var26", "field_name": "var26", "pandas_ty'
>             b'pe": "float64", "numpy_type": "float64", "metadata": null}, {"na'
>             b'me": "var27", "field_name": "var27", "pandas_type": "float64", "'
>             b'numpy_type": "float64", "metadata": null}, {"name": "var28", "fi'
>             b'eld_name": "var28", "pandas_type": "unicode", "numpy_type": "obj'
>             b'ect", "metadata": null}, {"name": "var29", "field_name": "var29"'
>             b', "pandas_type": "float64", "numpy_type": "float64", "metadata":'
>             b' null}, {"name": "var30", "field_name": "var30", "pandas_type": '
>             b'"unicode", "numpy_type": "object", "metadata": null}, {"name": "'
>             b'index", "field_name": "index", "pandas_type": "int64", "numpy_ty'
>             b'pe": "int64", "metadata": null}], "creator": {"library": "pyarro'
>             b'w", "version": "0.14.0"}, "pandas_version": "0.25.1"}'}

**Comment by xiaodaigh** [comment]
The problem is that the data is quite and teating it on large data is the point. I tried to produce a MWE but if I reduce the data size then it works. So errro must be somewhere in the data. I think I might have identified a data source that daks has issue with. I will try to see if I cna reduce the dataset size but Fannieae is a great data source

**Comment by jrbourbeau** [comment]
Thanks for your efforts in trying to provide a MWE @xiaodaigh. Based on `ValueError: Schema in c:/data/p03.parquet/part.1.parquet was different.` in your traceback, it looks like there's a schema mismatch between partitions which can arise when there is missing data in DataFrame paritions (for example, see issue #4194). You can specify the schema manually using the `schema=` parameter in `to_parquet`.

**Comment by xiaodaigh** [comment]
Posting an example of using a schema as it's not document and not obvious how to use

```python
schema = pa.schema(
    [
        ("x", pa.float64()),
        ("timestamp", pa.timestamp("ns")),
        ("id", pa.int64()),
        ("name", pa.string()),
        ("y", pa.float64()),
    ]
)
df.to_parquet("wow.pq", schema=schema, engine="pyarrow")
```

**Comment by jrbourbeau** [comment]
Thanks for posting an example. Did using `schema=` help resolve your issue? 

Also, if you'd like to add more documentation surrounding the `schema` parameter or anything else, PRs are always appreciated. (no obligation though)

**Comment by xiaodaigh** [comment]
Hopefully will get it this weekend. I am benchmarking dask vs disk.frame

**Comment by arpit1997** [comment]
@jrbourbeau @xiaodaigh Anyone working on this? Can I take this one?

**Comment by TomAugspurger** [comment]
I'm not sure there's a clear issue here. We could document `schema` with an
example, or perhaps link to the pyarrow docs on the subject.

**Comment by jrbourbeau** [comment]
@xiaodaigh did specifying a value for `schema=` resolve your issue? 

> We could document `schema` with an example, or perhaps link to the pyarrow docs on the subject.

I think either of these options would be welcome contributions

**Comment by xiaodaigh** [comment]
Will try to have time this weekend. I only contribute to OSs on weekends

**Comment by jrbourbeau** [comment]
Just checking in here. @xiaodaigh has this issue been resolved for you? Is it okay to close this issue?

**Comment by xiaodaigh** [comment]
It's pretty annoying to do. It is still failing. But I only set the schema for first 4 columns. Do I need to set schema for all columns?

Is there a way to extract the schema that Dask is going to use? So I only need to modify the parts that break? Would be nice to have a function that extracts the schema for all parts and checks for consistency.

**Comment by TomAugspurger** [comment]
The schema is pyarrow's, not Dask's. You could likely get it with something like

```python
In [7]: ts = dask.datasets.timeseries()

In [8]: schema = pa.Schema.from_pandas(ts._meta)

In [9]: schema
Out[9]:
id: int64
name: null
x: double
y: double
timestamp: timestamp[ns]
metadata
--------
{b'pandas': b'{"index_columns": ["timestamp"], "column_indexes": [{"name": nul'
            b'l, "field_name": null, "pandas_type": "unicode", "numpy_type": "'
            b'object", "metadata": {"encoding": "UTF-8"}}], "columns": [{"name'
            b'": "id", "field_name": "id", "pandas_type": "int64", "numpy_type'
            b'": "int64", "metadata": null}, {"name": "name", "field_name": "n'
            b'ame", "pandas_type": "empty", "numpy_type": "object", "metadata"'
            b': null}, {"name": "x", "field_name": "x", "pandas_type": "float6'
            b'4", "numpy_type": "float64", "metadata": null}, {"name": "y", "f'
            b'ield_name": "y", "pandas_type": "float64", "numpy_type": "float6'
            b'4", "metadata": null}, {"name": "timestamp", "field_name": "time'
            b'stamp", "pandas_type": "datetime", "numpy_type": "datetime64[ns]'
            b'", "metadata": null}], "creator": {"library": "pyarrow", "versio'
            b'n": "0.15.1"}, "pandas_version": "0.25.1"}'}


```

**Comment by jrbourbeau** [comment]
Closing as it the schema can be manually supplied
