### ISSUE TITLE
Numpy warnings in compute_meta

### ISSUE THREAD

**Issue by estebanag** [dask/dask#5337]
I've noticed that the following (just an example) generates a warning (using dask version `2.3.0`):
```python
import dask.array as da
import numpy as np

data0 = da.zeros((3, 10, 10), chunks=(3, 2, 2))
data1 = da.map_blocks(lambda x: np.mean(x, axis=0), data0, dtype=data0.dtype, drop_axis=0)
```
Output:
```
numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice
```
This seems related to [this pull request](https://github.com/dask/dask/pull/5103).

Thanks!

<details>
dask==2.3.0
numpy==1.17.0
pkg-resources==0.0.0
toolz==0.10.0
</details>

**Comment by jrbourbeau** [comment]
Thanks @estebanag for raising an issue and providing a nice minimal example, I'm able to reproduce the `RuntimeWarning`. The changes made in #5103 are to ignore NumPy's floating-point exceptions (e.g. when dividing by 0). The warning we're seeing here, taking the mean of an empty slice, is not a floating-point exception (see the "Notes" section of the [`numpy.seterr` docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.seterr.html#numpy.seterr) for a list of NumPy's floating-point exceptions).

To ignore this warning, we would need to catch `RuntimeWarning`s more broadly in `compute_meta`. Do you have an interest in submitting a PR (no obligation though)?
