### ISSUE TITLE
till Dask 2.2.0 read_parquet filters parameter doesn't seem to work anymore with pyarrow engine

### ISSUE THREAD

**Issue by DenisRen** [dask/dask#5346]
Hi,
when i upgraded dask from 2.1.0 to 2.2.0 (or 2.3.0), the following code changed its behaviour and stopped filtering parquet files as it did before. This is only appening with pyarrow engine (fastparquet engine is still filtering well).

```
import dask.dataframe as dd
len(dd.read_parquet(path/parquet_sample,engine='pyarrow', filters=[(('DatePart','<=','2018-01-02'))]))
```
On this attached minimal parquet storage sample each partition contains 1 row per date.

With this filter, Dataframe lenght, should be 2.
It's the case for Dask 2.1.0. It's not the case anymore with Dask 2.2.0 or 2.3.0 that stopped filtering parquet files correctly (returned lenght is 10).

Thanks,
Denis

[parquet_sample.zip](https://github.com/dask/dask/files/3556397/parquet_sample.zip)

**Comment by TomAugspurger** [comment]
Thanks for the report. Do you have the code for creating the dataset (so that we can include it in the unit test)?

cc @rjzamora if you have a chance to take a look. Otherwise I'll look later today.

**Comment by rjzamora** [comment]
Can confirm that I get all 10 rows after "filtering" - I'll take a look.
