### ISSUE TITLE
Unexpected behaviour of `blockwise` with `new_axes`

### ISSUE THREAD

**Issue by fsteinmetz** [dask/dask#5347]
I am applying a function `g` using `blockwise` ; the output of this function has a single new dimension:
```python
import numpy as np
from dask.array.blockwise import blockwise

x = np.arange(10, dtype='float32')

def g(x_):
    assert isinstance(x_, np.ndarray)
    return x_[:2]

blockwise(g, 'z',
          x, 'a',
          dtype='float32',
          new_axes={'z': 2},
          ).compute()
```

`dask.__version__` is `2.3.0`.
This code raises an `AssertionError` because `x_` is actually `[x]` in `g`, instead of simply `x`. Using `x_[0]` gives the expected behaviour.

However, when following the example provided in [`blockwise.__doc__`](https://github.com/dask/dask/blob/ca46b0ba2124cbabdb0fd6b0f616a1bb3654c7be/dask/array/blockwise.py#L99), `x_` is a numpy array as expected:

```python
import numpy as np
from dask.array.blockwise import blockwise

x = np.arange(10, dtype='float32')

def f(x_):
    assert isinstance(x_, np.ndarray)
    return x_[:, None] * np.ones((1, 5))

blockwise(f, 'az',
          x, 'a',
          new_axes={'z': 5},
          dtype=x.dtype
          ).compute()
```

Is this a bug, or did I misunderstand the usage of `blockwise` and `new_axes`?

**Comment by sjperkins** [comment]
Your first example implies a contraction over axis 'a'. Hence the wrapped function is posted ask chunks of x in a list. That's why x_[0] works, *if there's only a single chunk in x*

**Comment by fsteinmetz** [comment]
Thanks for the clarification, @sjperkins! That was indeed a misunderstanding on my side.
If I get it right, for each disappearing dimension, all chunks along that dimension are passed in a list, which results in nested lists in case of multiple disappearing dimensions.
I'm closing this issue :)
