### ISSUE TITLE
dask.dataframe.read_parquet does not read divisions from pandas.dataframe.to_parquet files

### ISSUE THREAD

**Issue by ChristophRose** [dask/dask#5355]
I ran into the following problem:
I created many dataframes in Pandas and stored them individually as parquet files. Each parquet file has a sorted index, and the different dataframes do not have overlapping indexes. While the individual dataframes fit in memory, several concatenated together do not. Hence, I wanted to work with Dask.

However, creating a dask dataframe from those parquet files did not lead to any divisions being created (even with infer_index=True). Resetting the index, and setting it again with sorted=True works, but takes some time.

Storing the pandas dataframe as a hdf file and reading it into the dask dataframe works without problems.

MCVE:
```
from pathlib import Path
import pandas as pd
import dask.dataframe as dd
from fastparquet import ParquetFile

# Create a dataframe
pandas_df = pd.DataFrame(np.random.randint(0,30,size=10),
    columns=["Values"],
    index=range(10,20))
pandas_df = pandas_df .rename_axis("index", axis="index")
path = Path("C:/test")

# Store the pandas dataframe as hdf and parquet
pandas_df.to_hdf(path / "hdf_file.h5", key="pandas_df", format="table")
pandas_df.to_parquet(path / "parquet_file.parquet", engine='fastparquet')

# Create dask dataframes directly from the pandas dataframe, from the hdf file, and the parquet file
ddf = dd.from_pandas(pandas_df , npartitions=1)
hdf_ddf = dd.read_hdf(path / "hdf_file.h5", key="pandas_df", sorted_index=True)
parquet_ddf = dd.read_parquet(path / "parquet_file.parquet", infer_index=True)

# Looking at the divisions
print(ddf.divisions)
# Output: (10, 19)
print(ddf2.divisions)
# Output: (10, 19)
print(ddf3.divisions)
# Output: (None, None)

# The needed information is in the parquet file:
print(ParquetFile(str(path / "parquet_file.parquet")).statistics)
# Output: {
#     'min': {'index': [10], 'Values': [3]},
#     'max': {'index': [19], 'Values': [27]},
#     'null_count': {'index': [0], 'Values': [0]},
#     'distinct_count': {'index': [None], 'Values': [None]}}

# Resetting the index and setting it again works.
parquet_ddf = parquet_ddf.reset_index()
parquet_ddf = parquet_ddf.set_index("index", sorted=True)
print(parquet_ddf.divisions)
# Output: (10, 19)
```

**Comment by mrocklin** [comment]
Dask dataframe obtains divisions by looking at the parquet metadata in each row group.  Does the Pandas `to_parquet` method write metadata?

**Comment by ChristophRose** [comment]
Which metadata exactly? As I showed above the ParquetFile object does include the min and max values of the index (and the values).

**Comment by mrocklin** [comment]
Great.  I'm glad to see that this was resolved.  Thanks for reporting your experience @ChristophRose .  Hopefully it helps others who come across this issue in the future.
