### ISSUE TITLE
Parquet reader create 50MB dask tasks

### ISSUE THREAD

**Issue by jdlesage** [dask/dask#5357]
I am using dask 0.2.3 and pyarrow 0.14. My files are on HDFS

When using the dask method `read_parquet` it generates huge dask tasks. If I read several parquet files, it creates dask graph that is > 16GB. It is very slow to transfer and crashes the scheduler. My issue might be related to https://github.com/dask/dask/issues/5321

**How to reproduce**
`filenames = hdfs.ls(...)`
`features = [....]`
`df = dd.read_parquet(filenames[0], columns = features, engine='pyarrow')`

`import cloudpickle`
`fun = df.__dask_graph__().values()[0]`
`print(len(cloudpickle.dumps(fun)), fun)`

It returns 

`38805505 (<function read_parquet_part at 0x7facf7860ae8>, <function ArrowEngine.read_partition at 0x7facab15a0d0>, <fsspec.implementations.hdfs.PyArrowHDFS object at 0x7facaaf87f98>, Empty DataFrame
Columns: [....]
Index: [], ParquetDatasetPiece('/user/[....].parquet', row_group=None, partition_keys=[]), [...], None, {'partitions': None, 'categories': None})`

Currently my workaround is to read parquet files using the pandas reader:
`@dask.delayed`
`def read_parquet(filename):`
`    return pd.read_parquet(filename, columns = features, engine='pyarrow')`

`df = dd.from_delayed([read_parquet(filename) for filename in filenames])`

In this case every 'read_parquet' tasks is about 1KB. Computations become fast and my scheduler consumes less than 1GB.

**Comment by jdlesage** [comment]
Small update: I don't have _metadata. So `gather_statistics` option has no impact

**Comment by stoneyv** [comment]
Are you able to generate a similar parquet object using random data.  This might help replicate the issue

**Comment by mrocklin** [comment]
Indeed, @jdlesage , if you're able to produce a minimal reproducible example that someone else could use to reproduce your problem that would be a huge help in determining what is going wrong here.  It's really hard to help otherwise.

See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for some guidelines.

**Comment by jdlesage** [comment]
Sorry for the delay. Thanks for your answer. I am not able to reproduce it on a simple example. After more investigations, that are the parquet metadata on my files that are big. These metadata are serialized inside the dask graph.

For example here the metadata of the first file.
`<pyarrow._parquet.FileMetaData object at 0x7f564075cbd8>
  created_by: parquet-mr version 1.9.1+20190430131449 (build e64421d51019b3ce7ad0d38a521e432b1c07e874)
  num_columns: 737
  num_rows: 150950
  num_row_groups: 578
  format_version: 1.0
  serialized_size: 43235812`

So definitively, the root cause seems to be on my parquet files.

I will close my ticket and keep my workaround (that does not send these metadata). Feel free to reopen it if you want more information.

**Comment by mrocklin** [comment]
I wonder if maybe we shouldn't be using the pyarrow piece object within the graph, and should instead use some other proxy to it.  Thoughts @martindurant @rjzamora ?

**Comment by martindurant** [comment]
I don't really know what the Piece contains, why it would be so big, but we should be able to figure out which things are needed in the writer code. I did this kind of object trimming for fastparquet.

**Comment by martindurant** [comment]
> num_columns: 737 num_rows: 150950 num_row_groups: 578

Worth pointing out that this is definitely suboptimal use of parquet, only ~260 rows per chunk

**Comment by rjzamora** [comment]
I just took a quick look at this - We should be able to avoid passing around `piece`, and instead pass around information like the path and `partition_keys`.  I'll try implementing a clean fix and submit something later today.

**Comment by martindurant** [comment]
Well, knowing the column names/types and offsets in the files really is necessary, so the data passed might not be as minimal as just paths; unless we want pyarrow to re-parse the file footers within every task.

**Comment by mrocklin** [comment]
> unless we want pyarrow to re-parse the file footers within every task.

That seems cheap?

**Comment by rjzamora** [comment]
> That seems cheap?

This is what I am hoping/assuming.  I suspect that pyarrow is re-reading the metadata anyway - I'll include a bit of benchmarking info in the PR.

**Comment by martindurant** [comment]
(that could, I suppose, be done for fastparquet too)
