### ISSUE TITLE
[Feature Request] Write outout partitioned by for non parquet format?

### ISSUE THREAD

**Issue by manugarri** [dask/dask#5360]
I am migrating an ETL pipeline from spark to dask. For my company, dask seems to be a much better solution (we are mostly a python shop).

However, the final output of the ETL seems to be downright impossible in Dask right now. 

Our data pipeline works with jsonlines compressed files. We read from an S3 input and write to another after transforming the data. So far pretty common use case.

However,

Our output needs to be split in S3 subfolders depending on the value (a date) of a field in the jsonline objects. This is a pretty common practice.

Right now dask supports writing out partitions if you use parquet format (as I believe this is supported by fastparquet/arrow). However it seems to be unavailable for a general solution (the standard partition by in Spark).

Is this achievable right now in Dask? Apologies if this is a solved issue, couldnt find anything related.

**Comment by TomAugspurger** [comment]
Are you working with dask.bag or dask.dataframe? I would think that a `groupby` and mapping a `write` function over each partition might work, but it's hard to say without an example.

**Comment by manugarri** [comment]
so i start with dask.bag ideally it would be managed there, but I can do to_dataframe() and  do it as a dataframe.

As a simple example, lets say we have 3 files as an input from a folder in S3, each one contains jsonline objects in the format:

```
{"date": "2019-09-03", "foo": "bar"...}
{"date": "2019-09-02", "foo": "bar"...}
{"date": "2019-09-02", "foo": "bar"...}
{"date": "2019-09-03", "foo": "bar"...}
{"date": "2019-09-02", "foo": "bar"...}
...
```

Now, I would like to perform some transformations on the input, and save it to another folder in S3, this time **partitioned by the date field on the input data**.

So in this example, the output would consist on some files created in the s3 folder `s3://XXX./date=2019-09-03` and some files created in the folder `s3://XXX./date=2019-09-02`

**Comment by TomAugspurger** [comment]
> so i start with dask.bag ideally it would be managed there, but I can do to_dataframe() and do it as a dataframe.

Performance-wise, it may be better to go to dataframe. It's groupby may be a bit better for shuffling data between partitions.

If I were writing this, I would start with a `.groupby()` and then `.apply` or `.map_partitions`.

If you have success, we'd welcome an update to the docs for this kind of problem. We're lacking in intermediate-level examples of how to use `.map_partitions` and `.apply`.

**Comment by mrocklin** [comment]
Note that partition by outputs may not require a full shuffle a la
groupby.  I think that Manuel is thinking more about how Parquet partitions
data, which is to emit several files per partition.  @martindurant 's
perspective would probably be valuable to have here.

**Comment by manugarri** [comment]
thanks for the pointer!  One issue i see with that approach is that, given that this is a pretty common use case (partition in s3/hdfs by most common shards/dates/, I would have to write from scratch the writing function. Would it make sense/be feasible to add this to the write bytes as a general feature that works with fsspec?

**Comment by martindurant** [comment]
Sounds like the inverse of the operation @jsignell did for reading - that file-path handling code would probably be useful (it is mostly within the Intake repo) referenced in https://github.com/intake/intake/blob/master/intake/source/base.py#L332

I would say fsspec itself doesn't really care what bytes it handles or what paths they go to, the logic would have to be higher, done by Dask.

**Comment by manugarri** [comment]
An approach I was testing (not validated yet) is to use the `name_function`. Would it be possible generate the output file names first in the global namespace and them using the name function to return them depending on the pointer of the partition?

Something like this:

```
items_df = dd.read_json("s3://INPUT/*.json.gz").set_index("date")

# get the dates as indexes from the partitions.

date_index = items_df.map_partitions(
    lambda _df: _df.index.value_counts().sort_index()
                                         ).compute().index

def get_filename(i):
    return date_index[i]

items_df.to_json(f"{OUTPUT_PATH}date=*.json.gz", 
                    name_function=get_filename, 
                    compression="gzip" 
})
```

**Comment by manugarri** [comment]
also, @TomAugspurger , what would be the recommendation of using map_partitions or apply? Wouldnt it make more sense to use map_partitions (since once its separated by the right field i wont need to do anything besides writing the partition?).

**Comment by TomAugspurger** [comment]
Does dask Dataframe's GroupBy have a map_partitions?

**Comment by manugarri** [comment]
I dont think so, no

**Comment by mrocklin** [comment]
To be clear, if @manugarri is trying to emulate what the partition_by keyword does in to_parquet then we should not use groupby or anything that shuffles.  I think that they just want each partition to be split in an embarrassingly parallel fashion.

**Comment by mrocklin** [comment]
So if we have daily data and we partition on a user's name, then we might have files like the following:


```
2000-01-01/alice.json
2000-01-01/bob.json
2000-01-01/charlie.json
2000-01-02/alice.json
2000-01-02/charlie.json
2000-01-03/...
```

**Comment by TomAugspurger** [comment]
Ah, I took the sample output in https://github.com/dask/dask/issues/5360#issuecomment-527530024 to imply that a shuffle *would* be required for this use case.

**Comment by mrocklin** [comment]
Ah, I could be wrong then. I suppose it's up to @manugarri to clarify

**Comment by manugarri** [comment]
@TomAugspurger that is correct, the input data is not already split by day. This means that each of the input files unfortunately has data for multiple dates that I would like to separate at the output.

**Comment by jsignell** [comment]
Just wanted to say that I imagine this is a fairly common scenario both for for 2d and nd data. It might be nice to have a minimal example of the workflow with some smallish/public dataset.

**Comment by TomAugspurger** [comment]
@manugarri here's how I might approach it

setup:

```python
import json
import pandas as pd
import dask.dataframe as dd
import dask.bag as db

data = """\
{"date": "2019-09-03", "foo": "bar"}
{"date": "2019-09-02", "foo": "bar"}
{"date": "2019-09-02", "foo": "bar"}
{"date": "2019-09-03", "foo": "bar"}
{"date": "2019-09-02", "foo": "bar"}"""

for i in range(3):
    with open(f"data-{i}", "w") as f:
        f.write(data)
```

Loading

```python
b = db.read_text("data-*").map(json.loads)
df = b.to_dataframe()
df['date'] = dd.to_datetime(df['date'])
```

Grouping & writing:

```python
def write(x):
    date = str(x['date'].iloc[0].date())
    x.to_csv(f"{date}.csv", mode="w")

df.groupby("date").apply(write, meta={}).compute()
```

**Comment by manugarri** [comment]
@TomAugspurger  thanks for your example! I was checking it and it indeed does the trick. However is not a valid solution in my case since the data I have is pretty big. The groupby operation returns a pandas dataframe per level of the column, this means it writes a single file per output level.

One way I found to balance the output partition sizes is to set the index as the date, which adds significant overhead.

Here is a reproducible example:

imports:
```
import json
import dask.dataframe as dd
import dask.bag as db
import random
from datetime import datetime
from uuid import uuid4
import fsspec
from dask.diagnostics import ProgressBar
```

We generate a decent size input dataset using timestamps instead of dates:

```
DATA_PATH = "./temp/"
N_FILES = 100
N_ROWS_PER_FILE = 100000

DATES = [
    datetime(2019, 9, 1).timestamp(),
    datetime(2019, 9, 2).timestamp(),
    datetime(2019, 9, 3).timestamp(),
]
def generate_row():
    return {
        "timestamp": random.choice(DATES) + 3600 * 12 * random.random(),
        "price": random.random()
    }

def generate_file_data(n_rows):
    return [generate_row() for i in range(n_rows)]

for i in range(N_FILES):
    with open(f"{DATA_PATH}input/data-{i}", "w") as f:
        file_data = generate_file_data(N_ROWS_PER_FILE)
        for line in file_data:
            f.write(json.dumps(line) + "\n")

```

Now we read from the input folder and set the index as the datepart of the timestamp:
I also repartition to make sure I can control the output partition size.

```
b = db.read_text(DATA_PATH +"input/data-*").map(json.loads)
df = b.to_dataframe()
df['date'] = dd.to_datetime(df['timestamp'], unit="s").dt.date
df = df.set_index("date").repartition(partition_size="10MB")
```

Finally use write the partitions:

```
def write_partition(x):
    date = str(x.index.values[0])
    filename = f"{DATA_PATH}output/{date}/-{str(uuid4())}.csv"
    openfile = fsspec.open(filename, "wt")
    with openfile as f:
        x.to_csv(f, mode="w")
    return filename


with ProgressBar():
    filenames = df.map_partitions(write_partition, meta={}).compute()
```

**Comment by TomAugspurger** [comment]
> One way I found to balance the output partition sizes is to set the index as the date, which adds significant overhead.

That's inducing a shuffle. Does it have overhead over the `groupby` approach? I assumed it would be about the same.

> One thing that would be great to add to this code is a way to get the partition number from within the map_partitions.

That seems reasonable. This would emulate what we do with `map_blocks` and `block_info`. Perhaps we could call it `partition_info` and it would be a dict with the keys `partition_number` and the `divisions` (lower / upper bound on the index values).

```python
def write_partition(x, partition_info):
    ...
```

I think that would suffice for your use-case, if you're OK with writing something like `/{date}-{uuid}`, where the CSV files are partitioned by date and input partition.

**Comment by manugarri** [comment]
> That's inducing a shuffle. Does it have overhead over the groupby approach? I assumed it would be about the same.

So the map_partitions itself takes similar time, but the indexing/repartition takes quite some time.

>  if you're OK with writing something like /{date}-{uuid}...

yeah that is what i was thinking of doing, it does bother me that doesnt follow the standard glob paths any longer, since then its a very custom solution. This means that afterwards I dont get to use my ETL framework using the standard * globs anymore, since adding the {date}{uuid} becomes a requirement.

Ideally it would be an options partition_by that would expand the names_function to include the column in the filesystem, regardless of the implementation. 

For example, in the [to_json](https://github.com/dask/dask/blob/master/dask/dataframe/io/json.py#L64)  function we see:

```
outfiles = open_files(
        url_path,
        "wt",
        encoding=encoding,
        errors=errors,
        name_function=kwargs.pop("name_function", None),
        num=df.npartitions,
        compression=compression,
        **(storage_options or {})
    )
    parts = [
        dask.delayed(write_json_partition)(d, outfile, kwargs)
        for outfile, d in zip(outfiles, df.to_delayed())
    ]
    if compute:
        dask.compute(parts)
        return [f.path for f in outfiles]
```

If i understand correctly, it generates the files with open_files then just runs write_json_partition. If the data was partitioned properly , it would make sense that the open_files function would take the partition_by, and generate valid output files including the partitioning key, that way nothing else needs to change.

**Comment by manugarri** [comment]
@TomAugspurger  I've been checking the dask implementation, and I think a nicer solution would be to generate the partition filenames to the native dask `to_json` function.

I can generate nice output filenames (with part names a-la-spark) with the following code:
(it assumes dataframe already indexed by date)
```
url_path = f"{DATA_PATH}output/*.json.gz"
def get_partition_index(x):
    return str(x.index.values[0])

partition_indices = df.map_partitions(get_partition_index).compute()

# too lazy to make this nicer, sorry
partition_filenames = []
part = 0
prev_index = None
for cur_index in partition_indices:
    if cur_index != prev_index:
        part = 0
    else:
        part += 1
    partition_filenames.append(url_path.replace("*", f"{cur_index}/part-{part:05}"))
    prev_index = cur_index
```

This produces a list of filenames, one per partition, that look like this:

>partition_filenames[:10]

```
['./temp/output/2019-08-31/part-00000.json.gz',
 './temp/output/2019-08-31/part-00001.json.gz',
 './temp/output/2019-09-01/part-00000.json.gz',
 './temp/output/2019-09-01/part-00001.json.gz',
 './temp/output/2019-09-01/part-00002.json.gz',
 './temp/output/2019-09-01/part-00003.json.gz',
 './temp/output/2019-09-01/part-00004.json.gz',
 './temp/output/2019-09-01/part-00005.json.gz',
 './temp/output/2019-09-01/part-00006.json.gz',
 './temp/output/2019-09-01/part-00007.json.gz']
```

I tried to pass that list directly to dask `to_json`, but it fails with the following error:

```
[#########################               ] | 62% Completed |  1min 35.1s
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-96-b13d4d86482c> in <module>
      1 with ProgressBar():
----> 2     df.to_json(partition_filenames, compression="gzip", mode="wt")

~/miniconda3/lib/python3.7/site-packages/dask/dataframe/core.py in to_json(self, filename, *args, **kwargs)
   1303         from .io import to_json
   1304 
-> 1305         return to_json(self, filename, *args, **kwargs)
   1306 
   1307     def to_delayed(self, optimize_graph=True):

~/miniconda3/lib/python3.7/site-packages/dask/dataframe/io/json.py in to_json(df, url_path, orient, lines, storage_options, compute, encoding, errors, compression, **kwargs)
     77     ]
     78     if compute:
---> 79         dask.compute(parts)
     80         return [f.path for f in outfiles]
     81     else:

~/miniconda3/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/miniconda3/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/miniconda3/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/miniconda3/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/miniconda3/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/miniconda3/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/miniconda3/lib/python3.7/site-packages/dask/dataframe/io/json.py in write_json_partition(df, openfile, kwargs)
     84 
     85 def write_json_partition(df, openfile, kwargs):
---> 86     with openfile as f:
     87         df.to_json(f, **kwargs)
     88 

~/miniconda3/lib/python3.7/site-packages/dask/bytes/core.py in __enter__(self)
    222         mode = self.mode.replace("t", "").replace("b", "") + "b"
    223 
--> 224         f = SeekableFile(self.fs.open(self.path, mode=mode))
    225 
    226         fobjects = [f]

~/miniconda3/lib/python3.7/site-packages/dask/bytes/local.py in open(self, path, mode, **kwargs)
     60             it. Not used for local.
     61         """
---> 62         return open(self._normalize_path(path), mode=mode)

FileNotFoundError: [Errno 2] No such file or directory: '..../temp/output/2019-08-31/part-00000.json.gz'
```

However, copypasting dask implementation works:

```
# this works

def write_json_partition(df, openfile, kwargs):
    with openfile as f:
        df.to_json(f, **kwargs)

outfiles = open_files(
        partition_filenames,
        "wt",
        compression="gzip",
    )

kwargs = {"orient": "records", "lines":True}
parts = [
        dask.delayed(write_json_partition)(d, outfile, kwargs)
        for outfile, d in zip(outfiles, df.to_delayed())
    ]

with ProgressBar():
    dask.compute(parts)

```

**Comment by martindurant** [comment]
Those dots in '..../temp/output/2019-08-31/part-00000.json.gz' look suspicious, I would try with absolute paths.

**Comment by manugarri** [comment]
@martindurant  the dots are because i dont want to share my local machine absolute path :D

**Comment by manugarri** [comment]
**update**, the issue i was having was because a dask versioning. using dask==2.1.0 was giving the last error I mentioned. I updated to 2.2.0 and the approach I mention (indexing and generating the partition filenames) works like a charm, at the cost of additional overhead for the indexing itself. 

I guess we can close this for now, might make sense to add partitioning as a feature, since I think my approach would work for any serialization function that works similar to `to_json`
