### ISSUE TITLE
Dask trying to save file with too long name

### ISSUE THREAD

**Issue by denisvlah** [dask/dask#5363]
This happens when working with huge dataframe larger than available RAM and dask computational graph is very big. Dask tries to spill data to disc and create too long file names for this.
Traceback from DASK worker:
[DaskErrorToLog.txt](https://github.com/dask/dask/files/3574913/DaskErrorToLog.txt)

Error was obtained on Ubuntu 18.0.4 with file system ext4 (maximum filename length is 255)
DASK version is 2.1.0

**Comment by quasiben** [comment]
@denisvlah not sure how this error is manifesting but I would recommend two things:

1) upgrade to dask 2.3.0 is possible 
2) build a minimal reproducible example we can run: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by denisvlah** [comment]
@quasiben
The error is reproduced on dask 2.3.0.
Cannot provide a tiny code snippet to reproduce this because it would require to port all my code and data.
Created a fix and a pull request for it:
https://github.com/dask/zict/pull/27

**Comment by TomAugspurger** [comment]
Should be fixed by https://github.com/dask/dask/pull/5383.
