### ISSUE TITLE
A public API to access task graph information

### ISSUE THREAD

**Issue by hongzmsft** [dask/dask#5364]
I am working serializing task graph for dask data structures. I understand that the information can be fetched from __dask_graph__().layers. I want to know whether this is a proper API for downstream projects to use. If not, what is the proper way to get task graph information?

**Comment by mrocklin** [comment]
Yes, the `__dask_graph__` interface, and everything in https://docs.dask.org/en/latest/custom-collections.html is stable.  Things change of course, but this has been the state for a long while.

**Comment by hongzmsft** [comment]
Thanks for the clarification.
