### ISSUE TITLE
'Series' object has no attribute 'is_unique'

### ISSUE THREAD

**Issue by j-grover** [dask/dask#5366]
pandas.Series has a property `Series.is_unique` but dask.Series does not currently looking at the API. 

The [implementation](https://github.com/jschendel/pandas/blob/b2f0d82ef4413550807c8f16a5b313382c0598aa/pandas/core/base.py#L1340) for pandas.Series is simply:
`return self.nunique(dropna=False) == len(self)`

So the dask version would be:
`return self.nunique().compute() == len(self)`
(dask's [nunique()](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.Series.nunique) does not support dropna)

I require this functionality for a library that makes use of the is_unique property of a Series.

**Comment by TomAugspurger** [comment]
Thanks for opening the issue.

Do you have a sense for whether `dask.datframe.Series.is_unique` would be lazy (return a Delayed object) or eager? I think that lazy would be my preference.

**Comment by j-grover** [comment]
The following is the code snippet from the existing python package that I require this for:

```python
    for i in non_uniq.copy():
        if df[i].is_unique or i == index:
            unique_attrs.add(i)
            non_uniq.remove(i)
            dependencies.add_unique_lhs(i)
```

I believe in this case the computation would have to be eager?

**Comment by TomAugspurger** [comment]
Yes. Delayed objects can't be used in conditionals

```pytb
In [19]: bool(dask.delayed(True))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-085b85a2eca1> in <module>
----> 1 bool(dask.delayed(True))

~/Envs/pandas-dev/lib/python3.7/site-packages/dask/delayed.py in __bool__(self)
    544
    545     def __bool__(self):
--> 546         raise TypeError("Truth of Delayed objects is not supported")
    547
    548     __nonzero__ = __bool__

TypeError: Truth of Delayed objects is not supported
```

So you would need to `compute` if the `.is_unique` property were lazy.

@jcrist do you have thoughts on what's appropriate for `Index/Series.is_unique`?

**Comment by jcrist** [comment]
Since we can't do this efficiently (it requires a full pass over the data for each column) and we can't match pandas api (I'm against eager behaviors if we can avoid them, especially for properties) perhaps we shouldn't support this at all?

The above loop would be better implemented in dask as a single pass over the data, rather than multiple computations. Something like:

```python
In [45]: df = pd.DataFrame({'a': range(20), 'b': [1, 2, 3, 4] * 5})

In [46]: ddf = dd.from_pandas(df, npartitions=3)

In [47]: length = ddf.shape[0]

In [48]: is_unique = {c: ddf[c].nunique() == length for c in ddf.columns}

In [49]: dask.compute(is_unique)   # Compute everything in a single call to `compute`
Out[49]: ({'a': True, 'b': False},)
```

**Comment by TomAugspurger** [comment]
Thanks. Not implementing seems to be the correct call here. I don't really see `.is_unique` being useful outside of using it as a conditional. And as you say, it's likely there's a more efficient way.

**Comment by j-grover** [comment]
No worries, I see the efficiency issue and why we wouldn't want it to be eager. Okay to close?

**Comment by jcrist** [comment]
Yeah. Thanks for following up.
