### ISSUE TITLE
Task dependencies do not match chunking when using `from_array`

### ISSUE THREAD

**Issue by d-v-b** [dask/dask#5367]
If I create an array chunked along the first axis like so:
```python
shape = (2,2)
chunks = (1,-1)
x = da.random.random(size=shape, chunks=chunks)
x.visualize()
```
![image](https://user-images.githubusercontent.com/3805136/64438270-d3956a80-d095-11e9-83cd-c700a42ad965.png)
The task graph reflects that each chunk is independent. So far so good. 

But if I use the same data and chunking to construct a dask array using `from_array`, the topology of the resulting task graph is different:
``` python
x_ = x.compute()
y = da.from_array(x_, chunks=chunks, name='test')
y.visualize()
```
![image](https://user-images.githubusercontent.com/3805136/64438546-4dc5ef00-d096-11e9-9db2-6b5660419d29.png)

Now both leaves of the task graph share a dependency on the original array _which is independent of the chunking scheme_. 

I feel like the task graph created by `da.random.random` is "right" and the task graph created by `from_array` is "wrong" with respect to my chunking scheme. However, `from_array` seems natural for users, and this can lead to dead workers when using the distributed scheduler, as I describe in another issue (See https://github.com/dask/distributed/issues/3032).

How to fix this? Maybe just make `from_array` call `stack`, `concatenate`, etc under the hood? This guarantees that the outputs of these array creation routines are more uniform. I'd be willing to look into a PR along these lines, but I want to be sure I'm on the right track.

**Comment by TomAugspurger** [comment]
I'm not sure I understand. That graph is showing that the two blocks `y` share a common piece of data (the ndarray `x.compute()`). In order to run `(test, 0, 0)` or `(test, 1, 1)`, you'll need the input.

**Comment by d-v-b** [comment]
@TomAugspurger Good catch, the way I coded that up was confusing. Now I explicitly create a numpy array from `x` and use that as the argument to `from_array`. In this case, I would argue that `(test 0, 0)` should not depend on the entire array, but rather a slice / view of that array.

**Comment by d-v-b** [comment]
I realize I didn't include an important comparison between `from_array` and `stack()`: 
```python
z = da.stack([da.from_array(element) for element in x_])
z.visualize()
``` 
![image](https://user-images.githubusercontent.com/3805136/64448318-6db3dd80-d0ab-11e9-8ac6-89b64b4e1f31.png)

This is the task graph I would expect to see after calling `from_array(x_, chunks=chunks)`: each leaf has an independent data dependency. Instead, `from_array` produces a task graph where each leaf depends on the entire original array.
