### ISSUE TITLE
Columns cut off in mismatched metadata error message

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#5370]
The columns in the computed data do not match the columns in the provided metadata

I have a lot, but not unreasonable amount. of columns. There's a problem with my metadata. However, the message has been truncated so I can't debug.

```
ValueError: ('Long error message', "The columns in the computed data do not match the columns in the provided metadata\n  Expected: ['pioneer_id', 'pioneer_sample_id', 'study_version', 'shield_ping_type', 'app_name', 'app_vendor', 'app_version', 'channel', 'geo_country', 'geo_city', 'geo_subdivision_1', 'geo_subdivision_2', 'server_ts', 'client_ts', 'submission_date_s3', 'event_type', 'is_batch', 'is_trimmed', 'navigation_uuid', 'batch_id', 'tab_active_dwell_time', 'ping_size', 'original_ping_size', 'http_request_count', 'http_response_count', 'http_redirect_count', 'javascript_count', 'trimmed_http_request_count', 'trimmed_http_response_count', 'trimmed_http_redirect_count', 'trimmed_javascript_count', 'payload_http_request_count', 'payload_http_response_count', 'payload_http_redirect_count', 'payload_javascript_count', 'event_data']\n  Actual:   ['pioneer_id', 'pioneer_sample_id', 'study_version', 'shield_ping_type', 'app_name', 'app_vendor', 'app_version', 'channel', 'geo_country', 'geo_city', 'geo_subdivision_1', 'geo_")
```

How do I get more message?

**Comment by mrocklin** [comment]
The relevant code is here:

https://github.com/dask/distributed/blob/98822d4ab13081a49a3643f216dcf26009ff9496/distributed/core.py#L969-L1003

It looks like the length of 1000 characters is hard coded.  Maybe this should be a configuration value?

**Comment by birdsarah** [comment]
> Maybe this should be a configuration value?

+1

**Comment by jrbourbeau** [comment]
@birdsarah does #5530 fix this issue?

**Comment by GenevieveBuckley** [comment]
It looks like this issue has been addressed by https://github.com/dask/dask/pull/5530

If that's not the case, please let us know and we can reopen this issue @birdsarah
