### ISSUE TITLE
Issue in joining empty dataframe with a non empty data frame

### ISSUE THREAD

**Issue by arundh93** [dask/dask#5376]
When we join a DataFrame with an empty dataframe in fails saying 
`You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat`

This is because dask internally applies `_meta_nonemty` which adds one entry to the empty data frame from `_simple_fake_mapping` which generates a row of `foo` entries hence it fails

**Comment by TomAugspurger** [comment]
Do you have a minimal example?

**Comment by arundh93** [comment]
Here is the sample code:

`mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
{'a': 100, 'b': 200, 'c': 300, 'd': 400},
{'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]

df1 = pd.DataFrame(mydict)
ddf1 = dd.from_pandas(df1)

df2 = pd.DataFrame(columns=['a', 'q'])
ddf2 = dd.from_pandas(df2)

ddf1.join(ddf2, on='a', lsuffix='_l', rsuffix='_r')`

The stack trace is as follows:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 2962, in join
    npartitions=npartitions, shuffle=shuffle)
  File "/anaconda3/lib/python3.7/site-packages/dask/dataframe/multi.py", line 375, in merge
    suffixes=suffixes, indicator=indicator)
  File "/anaconda3/lib/python3.7/site-packages/dask/dataframe/multi.py", line 285, in single_partition_join
    meta = left._meta_nonempty.merge(right._meta_nonempty, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6868, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 47, in merge
    validate=validate)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 533, in __init__
    self._maybe_coerce_merge_keys()
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 980, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat
`

**Comment by TomAugspurger** [comment]
Hmm, thanks (btw, your `from_pandas` calls need to specify npartitions).

So you're trying to join an integer-dtype array `df1.a` with an object dtype column (`df2.index`). Pandas typically doesn't allow that.

```python

In [11]: df1 = pd.DataFrame({"A": [1, 2, 3], 'B': [1, 2, 3]})

In [12]: df2 = pd.DataFrame({"A": ['a', 'b', 'c'], 'B': [3, 4, 5]})

In [13]: pd.merge(df1, df2, on="A")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-24d32ed92a0d> in <module>
----> 1 pd.merge(df1, df2, on="A")

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     80         copy=copy,
     81         indicator=indicator,
---> 82         validate=validate,
     83     )
     84     return op.get_result()

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    629         # validate the merge keys dtypes. We may need to coerce
    630         # to avoid incompat dtypes
--> 631         self._maybe_coerce_merge_keys()
    632
    633         # If argument passed to validate,

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
   1137                     inferred_right in string_types and inferred_left not in string_types
   1138                 ):
-> 1139                     raise ValueError(msg)
   1140
   1141             # datetimelikes must match exactly

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat
```

Pandas apparently *does* allow this on empty dtype,

```python
In [14]: pd.merge(df1, df2[:0], on="A")
Out[14]:
Empty DataFrame
Columns: [A, B_x, B_y]
Index: []
```

I'm going to check, but not raising there may be a bug. Dask passes a non-empty version of the data to `concat`, which is why things raise (not sure why we use `_meta_nonempty` instead of `_meta`, but probably working around a bug in pandas.

If you create your DataFrame with proper dtypes for the index, you'll get the expected behavior.

```python
In [25]: df2 = pd.DataFrame(columns=['a', 'q'], index=pd.Index([], dtype="int"))

In [26]: ddf2 = dd.from_pandas(df2, 2)

In [27]: ddf1.join(ddf2, on='a', lsuffix='_l', rsuffix='_r')
    ...:
Out[27]:
Dask DataFrame Structure:
                 a_l      b      c      d     a_r       q
npartitions=1
               int64  int64  int64  int64  object  object
                 ...    ...    ...    ...     ...     ...
Dask Name: merge, 3 tasks
```

**Comment by jrbourbeau** [comment]
@arundh93 did @TomAugspurger comment "If you create your DataFrame with proper dtypes for the index, you'll get the expected behavior." help resolve your issue?

**Comment by jrbourbeau** [comment]
Closing due to lack of response
