### ISSUE TITLE
dask.dataframe.map_partition not as expected

### ISSUE THREAD

**Issue by kwunlyou** [dask/dask#5386]
The following code doesn't output as expected using `dask==2.3.0`
```python
import os

import dask
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame([1, 2, 3, 4, 5], index=[10, 11, 12, 13, 14], columns=['score'])
ddf = dd.from_pandas(df, 1)

def main(d):
    print(d)
    for i, r in d.iterrows():
        with open(os.path.join('/home/ubuntu/test/', str(i)+'.txt'), 'w') as f:
            f.write(str(r['score']))

with dask.config.set(scheduler="synchronous"):
    _ = ddf.map_partitions(lambda df: main(df)).compute()
```

- during the running, there is a strange dataframe generated as follows

```
ubuntu@ip:~$ python test.py
   score
1      1
2      1
    score
10      1
11      2
12      3
13      4
14      5
```

- also, two more files are generated, i.e., `1.txt` and `2.txt`
```
ubuntu@ip:~$ ls /home/ubuntu/test
1.txt  10.txt  11.txt  12.txt  13.txt  14.txt  2.txt
```

if define `df = pd.DataFrame([1, 2, 3, 4, 5], index=[0, 1, 2, 3, 4], columns=['score'])`, everything works fine

**Comment by TomAugspurger** [comment]
Did you see the docs at https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions? When you don't provide a `meta`, dask will try to infer the output by running the computation on a bit of dummy data.

Right now, we don't have a good way of expressing a `map_partitions`-like call that doesn't return a DataFrame. So I'd recommend something like

```python
def main(d):
    print(d)
    for i, r in d.iterrows():
        with open(str(i)+'.txt', 'w') as f:
            f.write(str(r['score']))
    return d  # return d here
```

and pass `meta`

```python
ddf.map_partitions(lambda df: main(df), meta=ddf._meta).compute()
```

**Comment by kwunlyou** [comment]
@TomAugspurger Thanks for the explaination, Tom.
