### ISSUE TITLE
Failing HDFS test

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#5389]
Looks like there's a failing HDFS test (`dask/bytes/tests/test_hdfs.py::test_glob`) on `master` (ref https://travis-ci.org/dask/dask/jobs/583191520). Haven't had a chance to look into it yet, but wanted to open an issue for tracking

cc @martindurant @TomAugspurger

**Comment by martindurant** [comment]
This is OK, actually - directories *should* be included in the glob - so the test needs updating.
