### ISSUE TITLE
Delegate accessor __getattr__ to underlying object __getattr__

### ISSUE THREAD

**Issue by kkraus14** [dask/dask#5394]
In an accessor for dask.dataframe, there's a check to see whether a given attribute exists within the meta object: https://github.com/dask/dask/blob/master/dask/dataframe/accessor.py#L89-L96

In cuDF we delegate a `__getattr__` call to the string accessor to our underlying string library in many situations: https://github.com/rapidsai/cudf/blob/branch-0.10/python/cudf/cudf/core/column/string.py#L59-L80

Dask calculates the set of attributes available using `dir` and raises an `AttributeError` if the attribute isn't in the calculated set which causes issues for us: https://github.com/rapidsai/cudf/issues/2367

Is this something that could be changed or is the answer that cuDF needs to have attributes for every string function that we want to expose?

**Comment by TomAugspurger** [comment]
To make sure I understand, for a string-dtype cuDF Series

```python
>>> df = cudf.DataFrame()
>>> df['date'] = ['20190101', '20190102', '20190103']
```

What's the output of these

```python
hasattr(df['date'], 'str')
'str' in dir(df['date']))
```

**Comment by kkraus14** [comment]
@TomAugspurger both of those return True, the problem is when looking for the `slice` method:
```
hasattr(df['date'].str, 'slice')
# True

'slice' in dir(df['date'].str)
# False
```

**Comment by kkraus14** [comment]
Fixed underlying cudf issue https://github.com/rapidsai/cudf/pull/2796/
