### ISSUE TITLE
User-defined operations

### ISSUE THREAD

**Issue by RuiLoureiro** [dask/dask#5397]
I am unsure if there is currently any straightforward way to implement the following architecture:

I want to be able to define new operations.
These operations can depend on other custom defined operations or built in operations from dask.

I have defined these operations as classes, as I need logic to cache previous computations.

Let's assume operation **_A_** uses dask's `unique()`, operation **_B_** depends on **_A_** and operation **_C_** depends on **_B_**.

When the user asks for operation **_C_**, I would want **_A_**, **_B_** and **_C_** to get computed and cached, in a single dask.compute call (to avoid lower level recomputation).

From what i understood, the only way would be to make every new defined operation generate a high level graph, with its dependencies, but that makes writing new operations a lot harder. 

My first approach was to make every operation delayed, but figured out that nesting delayed calls is an anti-pattern.

As I haven't found any similar examples in the documentation, I wonder if this is currently supported.
Thank you

**Comment by RuiLoureiro** [comment]
Thank you for your quick reply.
I should have given more context.


```
import dask.dataframe as dd
import pandas as pd
class CachedStatistics:
    
    # get parquet
    def __init__(self, parquet)
        self.df = dd.read_parquet(parquet)
        self.cached = {}

    # method to implement cache
    def _call_method(self, name):
        if self.cached[name] is None:
            self.cached[name] = dask.compute(self.getattr(name).__call__())[0]

        return self.cached[name]

    def nrows(self):
        return len(self.df)
    
    def count(self):
        return self.df.count()

    def missing_pct(self):
        return self._call_method("nrows") / self._call_method("count")

    def summary(self):
        df_dict = { 
            'missing_pct': self._call_method("missing_pct") , 
            'mean' : self._call_method("mean")
            'nrows' : self._call_method("nrows")
        }

        return pd.Series(df_dict)
```
This is a simplified (and very inefficient) version of what I'm trying to do. 
(calling dask.compute every time I need to access a method is very expensive).

On the other hand, I would like to make it so that for every method its dependencies are computed before executing it. This can be done manually but, again, is not efficient as I have one compute per method with dependencies. 

I have read https://distributed.dask.org/en/latest/task-launch.html, but, from what I understood, and please correct me if I'm wrong, if I call `client.submit` on different tasks, every task gets treated independently and is, again, inefficient. 

It seems to me that the only way to accomplish efficient custom operations is to make every operation construct a High Level Graph, but wanted to make sure because that would mean writing my operations in a different, and more complex way.

**Comment by mrocklin** [comment]
You can call `dask.compute` with many arguments.

```python
dask.compute(x.sum(), x.mean())
```
