### ISSUE TITLE
Revert Spark doc style changes?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5413]
I mildly prefer the old layout without the boxes.  I think that boxes would make more sense if they included much briefer text, or if they were all connected.  As-is, I personally find the old layout more natural to read.  I also like that the Dask content follows the Spark content.

### Before

*Although I think I would want to remove the blue styling.  It looks like this was left over from the RTD Sphinx theme*

<img width="756" alt="Screen Shot 2019-09-16 at 2 05 47 PM" src="https://user-images.githubusercontent.com/306380/64993578-4cad7280-d88b-11e9-98fd-b2377e18e1ed.png">

### Current

<img width="731" alt="Screen Shot 2019-09-16 at 2 05 58 PM" src="https://user-images.githubusercontent.com/306380/64993593-53d48080-d88b-11e9-81f6-fc1e93ffe468.png">

**Comment by jcrist** [comment]
I agree, I also find the boxes harder to read (more crowded, having to visually correlate sentences between the two boxes).
