### ISSUE TITLE
Add an assume_unique_in_partition option to nunique

### ISSUE THREAD

**Issue by RogerThomas** [dask/dask#5414]
It should be possible to add a flag like `assume_unique_in_partition` to the Series.nunique() function to speed up nunique. This would mean per partition we could just count unique values and sum across partitions.

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @RogerThomas! Out of curiosity, have you come across situations where the current implementation has been too limiting? 

Perhaps @TomAugspurger has thoughts on adding a dask-specific `assume_unique_in_partition` keyword to `Series.nunique()`

**Comment by TomAugspurger** [comment]
To be clear: the proposed speedup is from not having to serialize and pass around a (potentially large) pandas Series of unique values and a subsequent intersection of those values? Instead you would ship the integers and just do a sum?

I'm a bit iffy about this as a parameter. Haven't thought about it too much.

That said, we *could* do this automatically on `Index.nunique` when we have known divisions. In that case we do know that we won't have a value showing up in multiple partitions.

**Comment by mrocklin** [comment]
Can a user do this today somewhat easily with map_partitions and sum?  If
so, then I'm also less excited about adding a custom keyword argument here.

**Comment by jrbourbeau** [comment]
> Can a user do this today somewhat easily with map_partitions and sum?

That's a good point. @RogerThomas would this approach fit your use case?

**Comment by RogerThomas** [comment]
@jrbourbeau sure, can use the map partitions version. Thought it might be a nice feature addition, but understand not wanting to bloat the API, so feel free to close if you wish.

**Comment by jrbourbeau** [comment]
Given the `map_partitions` solution, I think we'll opt to not add a new keyword argument here. But I definitely appreciate you filing an issue. Thanks @RogerThomas!
