### ISSUE TITLE
Support for ADSL Gen2

### ISSUE THREAD

**Issue by lmiroslaw** [dask/dask#5416]
**Feature Request:** in your official documentation you are mentioning Azure DataLake Storage is not supported due to lack of Gen2 implementation.

However [DataLake Storage Gen2](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction) is already there.

What is the current status?

**Comment by jrbourbeau** [comment]
There appears to be ongoing work in https://github.com/dask/dask-adlfs/pull/6

**Comment by martindurant** [comment]
To be sure, we meant *we* didn't have Gen2 support, which is why the storage cannot be supported until we do.

**Comment by jrbourbeau** [comment]
@lmiroslaw does this give a sense of the current status? Is it safe to close this issue?

**Comment by jrbourbeau** [comment]
Closing. @lmiroslaw feel free to follow up in https://github.com/dask/dask-adlfs
