### ISSUE TITLE
Categories lost after groupby + agg

### ISSUE THREAD

**Issue by OliverHofkens** [dask/dask#5419]
### Reproducible example

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

from pandas.testing import assert_frame_equal

pdf = pd.DataFrame({
    "category_1": list("AAABBBCCC"),
    "category_2": list("ABC") * 3,
    "value": [0.1] * 9
})
pdf["category_1"] = pdf["category_1"].astype("category")
pdf["category_2"] = pdf["category_2"].astype("category")
pdf
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>category_1</th>
      <th>category_2</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>A</td>
      <td>A</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>A</td>
      <td>B</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>2</td>
      <td>A</td>
      <td>C</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>3</td>
      <td>B</td>
      <td>A</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>4</td>
      <td>B</td>
      <td>B</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>5</td>
      <td>B</td>
      <td>C</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>6</td>
      <td>C</td>
      <td>A</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>7</td>
      <td>C</td>
      <td>B</td>
      <td>0.1</td>
    </tr>
    <tr>
      <td>8</td>
      <td>C</td>
      <td>C</td>
      <td>0.1</td>
    </tr>
  </tbody>
</table>
</div>

```python
ddf = dd.from_pandas(pdf, npartitions=2)

assert_frame_equal(
    pdf.groupby(["category_1", "category_2"]).agg("mean"),
    ddf.groupby(["category_1", "category_2"]).agg("mean").compute()              
)
```

    ---------------------------------------------------------------------------

    AssertionError                            Traceback (most recent call last)

    <ipython-input-83-6f964c296364> in <module>
          1 assert_frame_equal(
          2     pdf.groupby(["category_1", "category_2"]).agg("mean"),
    ----> 3     ddf.groupby(["category_1", "category_2"]).agg("mean").compute()
          4 )

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in assert_frame_equal(left, right, check_dtype, check_index_type, check_column_type, check_frame_type, check_less_precise, check_names, by_blocks, check_exact, check_datetimelike_compat, check_categorical, check_like, obj)
       1358         check_exact=check_exact,
       1359         check_categorical=check_categorical,
    -> 1360         obj="{obj}.index".format(obj=obj),
       1361     )
       1362 

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in assert_index_equal(left, right, exact, check_names, check_less_precise, check_exact, check_categorical, obj)
        667                 check_less_precise=check_less_precise,
        668                 check_exact=check_exact,
    --> 669                 obj=lobj,
        670             )
        671             # get_level_values may change dtype

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in assert_index_equal(left, right, exact, check_names, check_less_precise, check_exact, check_categorical, obj)
        633 
        634     # class / dtype comparison
    --> 635     _check_types(left, right, obj=obj)
        636 
        637     # level comparison

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in _check_types(l, r, obj)
        609     def _check_types(l, r, obj="Index"):
        610         if exact:
    --> 611             assert_class_equal(l, r, exact=exact, obj=obj)
        612 
        613             # Skip exact dtype checking when `check_categorical` is False

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in assert_class_equal(left, right, exact, obj)
        726             if len(types - {"Int64Index", "RangeIndex"}):
        727                 msg = "{obj} classes are not equivalent".format(obj=obj)
    --> 728                 raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
        729     elif exact:
        730         if type(left) != type(right):

    /usr/local/lib/python3.7/site-packages/pandas/util/testing.py in raise_assert_detail(obj, message, left, right, diff)
        930         msg += "\n[diff]: {diff}".format(diff=diff)
        931 
    --> 932     raise AssertionError(msg)
        933 
        934 

    AssertionError: MultiIndex level [0] are different
    
    MultiIndex level [0] classes are not equivalent
    [left]:  CategoricalIndex(['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'], categories=['A', 'B', 'C'], ordered=False, name='category_1', dtype='category')
    [right]: Index(['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'], dtype='object', name='category_1')

Other similar cases do seem to work:

```python
# Group on 1 col + built-in agg
assert_frame_equal(
    pdf[["category_1", "value"]].groupby("category_1").mean(),
    ddf[["category_1", "value"]].groupby("category_1").mean().compute()              
)
# Works!
```

```python
# Group on 1 col + agg()
assert_frame_equal(
    pdf[["category_1", "value"]].groupby("category_1").agg("mean"),
    ddf[["category_1", "value"]].groupby("category_1").agg("mean").compute()              
)
# Works!
```

```python
# Group on 1 col + agg({dict})
assert_frame_equal(
    pdf.groupby("category_1").agg({"value": "mean"}),
    ddf.groupby("category_1").agg({"value": "mean"}).compute()              
)
# Works!
```

```python
# Group on 2 cols + built-in agg
assert_frame_equal(
    pdf.groupby(["category_1", "category_2"]).mean(),
    ddf.groupby(["category_1", "category_2"]).mean().compute()              
)
# Works!
```

So this only seems to happen if you `groupby` on more than 1 column and use `agg` instead of a built-in aggregation.

**Comment by TomAugspurger** [comment]
Confirmed, thanks. Not sure exactly where things are going wrong though.

**Comment by OliverHofkens** [comment]
I'd be glad to take a look and cook up a PR next week.

**Comment by jrbourbeau** [comment]
That would be welcome, thanks @OliverHofkens

**Comment by OliverHofkens** [comment]
For future reference, I found the issue:
In `_groupby_apply_funcs()` a DataFrame is constructed from the results of the different functions applied: 
https://github.com/dask/dask/blob/6527596f4db4b47943537d66b71cba747ac37b2d/dask/dataframe/groupby.py#L870-L882

When constructing a DataFrame from different Series as is done here, `pandas` unions the indexes of the Series to create the DataFrame index:

https://github.com/pandas-dev/pandas/blob/b10610871a24c619995db400e9419eebf8ac34ed/pandas/core/internals/construction.py#L349-L350

Unioning 2 different Categoricals coerces to object, as mentioned in the pandas documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#merge-dtypes

So the core of the problem is that different functions in `_groupby_apply_funcs()` return differently indexed results, causing coercion when they are put together. In the case of my example in the beginning of the thread, `agg("mean")` applies both `sum()` and `count()`, which seem to be indexed differently:
`sum()` returns the full index while `count()` returns only the index for observed values.

**Comment by OliverHofkens** [comment]
Related: https://github.com/pandas-dev/pandas/issues/17605
