### ISSUE TITLE
da.array(list) returns a list

### ISSUE THREAD

**Issue by d-v-b** [dask/dask#5426]
Calling `da.array()` on a list returns the argument unchanged, i.e. the output is a list, not a dask array. This is unexpected. Either the docstring should be updated to indicate this, or the function should be changed to emit an ndarray as one would expect from the current docstring.

MRE:
```
import dask.array as da
type(da.array([0,1,2,3]))
# prints `list`
```

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @d-v-b. We might want to add `x = asarray(x)` at the beginning of `da.array` (several other functions in `dask/array/routines.py` do this to ensure the that input is converted to a dask array).
