### ISSUE TITLE
warn_dtype_mismatch -method fails sometimes

### ISSUE THREAD

**Issue by JukkaKeisala** [dask/dask#5437]
Not easy to reproduce, but the check in `warn_dtype_mismatch`-method
```py
if not left.dtypes[lo] is right.dtypes[ro]
```
fails sometimes. Maybe one should not use 'is', but instead '=='?

https://github.com/dask/dask/blob/master/dask/dataframe/multi.py#L371-L374

**Comment by mrocklin** [comment]
When does this arise?  No objection from me on changing the is to ==, but
it would be nice to know when this is important.

**Comment by TomAugspurger** [comment]
@JukkaKeisala any response to https://github.com/dask/dask/issues/5437#issuecomment-535923484?

One problem with using `==` is that pandas' extension dtypes can't be safely compared to NumPy dtypes

```python
In [4]: np.dtype('int') == pd.CategoricalDtype()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-ec85c3b44381> in <module>
----> 1 np.dtype('int') == pd.CategoricalDtype()

TypeError: data type not understood
```

**Comment by JukkaKeisala** [comment]
@mrocklin @TomAugspurger 
This happened when tried to merge two dask dataframes. Left and right dtypes were the same in [asciitable](https://github.com/dask/dask/blob/master/dask/dataframe/multi.py#L379) (showed in log/output). Because dtypes were the same I deduced that the error shouldn't have been raised.

Of course it is possible that the printing of asciitable hides the problem...

On my local environment I went to code and changed `is` to `==` and the warning was gone.

The main thing is how to safely compare datatypes, as @TomAugspurger said. 

And the main thing, I've tried to make easy reproducable example of this but I've failed. This goes back to that that sometimes `is` work's as `==`. This usually happens in more complicated examples, not in short exampled as far as I know.

---

I saw somewhere (maybe in NumPy-related stuff) that the comparison was made by using try-except to add more choices. Of course, the datatype comparison is wider topic than this case.

**Comment by TomAugspurger** [comment]
We could try using `pandas.api.types.is_dtype_equal` instead, which should be robust.

@JukkaKeisala do you have an example where this comes up? Ideally we would have a test case for it.

**Comment by JukkaKeisala** [comment]
The following JSON data lies in web (server through REST API in my case):

```
'{"microsecondtimestamp": {"0": 1568981552099000, "1": 1568981799149000, "2": 1568981814126000, "3": 1568981896929000, "4": 1568982049422000, "5": 1568982099443000, "6": 1568982866835000, "7": 1568982875109000, "8": 1568982891157000, "9": 1569220182183000}, "values": {"0": 59.0, "1": 59.0, "2": 59.0, "3": 59.0, "4": 61.2, "5": 61.4, "6": 61.4, "7": 61.4, "8": 69.1, "9": 74.1}}'
```
at endpoint `myendpoint/data1`

and 
```
'{"microsecondtimestamp": {"0": 1569224231024000, "1": 1569225379890000, "2": 1569225399425000, "3": 1569225425104000, "4": 1569323898216000, "5": 1569325297211000, "6": 1569325349491000, "7": 1569325580105000, "8": 1569325587558000, "9": 1569325641823000}, "values": {"0": 54, "1": 54, "2": 55, "3": 56, "4": 56, "5": 99, "6": 99, "7": 99, "8": 99, "9": 99}}'
```
at endpoint `myendpoint/data2`

If I run the following script on TCPServer (using TCPServer.serve_forever + parameters)
```
df1 = dd.read_json('myendpoint/data1', orient='columns')
df2 = dd.read_json('myendpoint/data2', orient='columns')

id1 = id(df1.dtypes['timestamp'])
id2 = id(df1.dtypes['timestamp'])
```
the `id`'s are not the same but the datatypes are (i.e., `==`). This is the reason why I raised this issue.

I cannot reproduce this in iPython or Jupyter Notebook.

**Comment by TomAugspurger** [comment]
Thanks @JukkaKeisala, that and https://github.com/numpy/numpy/issues/6295 was enough to get a reproducer


```python
In [102]: df1 = pd.DataFrame({"a": np.array([1, 2], dtype=np.dtype(np.int64))})

In [103]: df2 = pd.DataFrame({"a": np.array([1, 2], dtype=np.dtype(np.longlong))})

In [104]: dd.multi.warn_dtype_mismatch(df1, df2, 'a', 'a')
/Users/admin/miniconda3/envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/multi.py:387: UserWarning: Merging dataframes with merge column data type mismatches:
+---------------+------------+-------------+
| Merge columns | left dtype | right dtype |
+---------------+------------+-------------+
| ('a', 'a')    | int64      | int64       |
+---------------+------------+-------------+
Cast dtypes explicitly to avoid unexpected results.
  ).format(col_tb)

```

**Comment by TomAugspurger** [comment]
I don't really know what `np.longlong` is, but the repr is `dtype('int64')` for me, and the `np.iinfo()` looks the same. I'll see if we can use `is_dtype_equal` instead there.

**Comment by JukkaKeisala** [comment]
Nice reproducer you found @TomAugspurger, I think `is_dtype_equal` will work here. I cannot check it for a couple of days but will do that as soon as possible.

**Comment by TomAugspurger** [comment]
No need. I have an open PR and the tests all passed.
