### ISSUE TITLE
a bug in automatic chunk? or my misunderstanding??

### ISSUE THREAD

**Issue by tinaok** [dask/dask#5439]
Hi,
we were trying to varying array chunk-size for a benchmarking study. [https://github.com/pangeo-data/benchmarking/issues/30] 
But when choosing automatic chunk, for our case, certain chunk-size we have used does not work.  For example, we set array.chunk-size as 370MB, and set chunks='auto', chunk size created by Dask Array is '(380, 192, 320)' thus it is only 187MB of chunk.
If using chunk-size more than 380MB, this problem does not occur. But less than 370MB (even with around 100MB) this problem occurs.  

I copy and past the outputs I get in a simple example below.  I hope you can point me out if this is a bug or not. 
Thank you for your help !

------------------------------
**import dask.array as da
import dask
dask.config.set({"array.chunk-size": '370MB'})
da.random.RandomState(0).standard_normal((20834, 384, 320), chunks='auto')**  
output: dask.array<standard_normal, shape=(20834, 384, 320), dtype=float64, chunksize=(380, 192, 320)>
**380 * 190 * 320 * 8 = 186777600  => 187MB thus  ##not ok**

**import dask.array as da
import dask
dask.config.set({"array.chunk-size": '380MB'})
da.random.RandomState(0).standard_normal((20834, 384, 320), chunks='auto')**  
output: dask.array<standard_normal, shape=(20834, 384, 320), dtype=float64, chunksize=(386, 384, 320)>
**380 * 384 * 320 * 8 = 379453440  => ok**

**import dask.array as da
import dask
dask.config.set({"array.chunk-size": '100MB'})
da.random.RandomState(0).standard_normal((20834, 384, 320), chunks='auto')**  
output: dask.array<standard_normal, shape=(20834, 384, 320), dtype=float64, chunksize=(232, 192, 160)>
** 232 * 192 * 160 * 8 = 57016320  => 57MB thus not ok**

**Comment by quasiben** [comment]
@tinaok I get the same results as you. I don't think this is a bug but rather how dask tries to keep the chunk shapes relatively the same.   Notice that the dimensions of the differing chunks are off by factors of two `192-> 384` and `320->160`.  In your particular case, the 370 doesn't chunk nicely into equally shaped chunk, but 380 does

**Comment by mrocklin** [comment]
Ben's assessment is correct.  Dask's auto chunking heuristics are
comfortable accepting chunk sizes down to half of what was requested if it
can make things line up nicely.

**Comment by tinaok** [comment]
Thank you @quasiben and @mrocklin 
we made a benchmark study [https://github.com/pangeo-data/benchmarking] comparing 'manual' chunking and automatic chunking by varying chunk size between 64MB-> 128MB -> 256MB -> 512MB for some geophysical operations.  
When I set 64MB, automatic chunking gives me chunksize=(199, 192, 160) thus 49MB
128MB ->chunksize=(251, 192, 160) thus 62MB (slightly less than half)
256MB ->chunksize=(317, 192, 160) thus 78MB (much less than half!)
512MB -> chunksize=(520, 384, 320) thus 511MB (good value ;-)
I see for example setting 256MB and having 78MB may deviate too much.  Is there any way to give some kind of parameter to dask that it use chunk size at least for example 0.8 to 1.2 times the size we asked it to use?

**Comment by mrocklin** [comment]
Not currently, but the code is here in case you'd like to engage further:

https://github.com/dask/dask/blob/f6c2449a000a72f05e41d0208d80696bc257d2ab/dask/array/core.py#L2474-L2597

**Comment by tinaok** [comment]
Thanks @mrocklin 
I look at the code you mentioned, but I could not found the part accepting chunk size down to half, can you plz help me ?
I thought I can may be modify the minimum 'half' part, to somehow larger value, but may be it is not as simple as that?

**Comment by mrocklin** [comment]
Unfortunately I don't have great recall over the full codebase.  I would
have to investigate and understand the code, just as you are now doing.
It's also very possible that I am mis-remembering the half aspect.

**Comment by TomAugspurger** [comment]
@tinaok were you able to look into the auto chunking code at all? It might be worthwhile putting an `import pdb; pdb.set_trace()` in that `auto_chunks` function and stepping through things line-by-line to see how we arrive at the final number.

**Comment by tinaok** [comment]
Hi @TomAugspurger sorry for my late response, I started to look at the code, and understood some part, made some test on change, but then I did not have time to continue.  I'll get back to it next week.

**Comment by tinaok** [comment]
Hi @mrocklin 
here is the implementation of the bug fix that I showed you in SC19 conference;
basic idea is indicated in the comments.
and here is the test code which shows that this make the chunk size better.

----test code ----
import dask.array as da
from distributed.utils import parse_bytes
import dask
import numpy  as np

limit_list=['64MB','128MB','256MB','512MB']

timesteps=20834
lat=320
lon=384
shape=(timesteps,lon,lat)
chunks=("auto","auto","auto")
previous_chunks=None

for limit in limit_list: 
    print('---test with shape=',shape,'and limit=',limit)
    dask.config.set({"array.chunk-size": limit})
    x =da.random.RandomState(0).standard_normal(shape, chunks=chunks  )
    dtype=x.dtype
    print('--chunk computed from dask',x.chunksize,' ratio is:',np.prod(x.chunksize)*dtype.itemsize/parse_bytes(limit))

----

non changed version gives

---test with shape= (20834, 384, 320) and limit= 64MB
--chunk computed from dask (199, 192, 160)  ratio is: 0.76416
---test with shape= (20834, 384, 320) and limit= 128MB
--chunk computed from dask (251, 192, 160)  ratio is: 0.48192
---test with shape= (20834, 384, 320) and limit= 256MB
--chunk computed from dask (317, 192, 160)  ratio is: 0.30432
---test with shape= (20834, 384, 320) and limit= 512MB
--chunk computed from dask (520, 384, 320)  ratio is: 0.9984

with my PR, it gives
-----

---test with shape= (20834, 384, 320) and limit= 64MB
--chunk computed from dask (1894, 64, 64)  ratio is: 0.969728
---test with shape= (20834, 384, 320) and limit= 128MB
--chunk computed from dask (3837, 64, 64)  ratio is: 0.982272
---test with shape= (20834, 384, 320) and limit= 256MB
--chunk computed from dask (4835, 64, 80)  ratio is: 0.7736
---test with shape= (20834, 384, 320) and limit= 512MB
--chunk computed from dask (520, 384, 320)  ratio is: 0.9984


64MB, 128MB, 256MB gives chunk which fits better to defined array.chunk-size.
