### ISSUE TITLE
[Feature] Exposing the `sort` parameter for dataframe groupby aggregations

### ISSUE THREAD

**Issue by ayushdg** [dask/dask#5441]
**Goal**
Avoid sorting intermediaries by default while performing certain groupby aggregations (reduction like aggs: min, max, count etc)

**Proposal**
Would it be possible for dask to support the `sort` parameter for [`dask.dataframe.groupby`](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.groupby) for groupby aggregations so that the value is passed down to the underlying dataframe groupby operation that performs the aggregation.

**Motivation** 
- Performance: A groupby approach that does not need to sort the output is more performant (especially as number of groups increases). Certain reduction aggregations like min, count can be computed without sorting the group keys, and should not require sorting at the dask level as well(unless I missed something).

Since dask does not support the `sort` parameter, groupby aggregations on each partition are restricted to use the default `sort` behavior of the underlying dataframe groupby operation.

Initial discussion that led to this issue: rapidsai/cudf#2717

cc: @kkraus14. @mrocklin (Feel free to tag others or add details that I may have missed)

**Comment by ayushdg** [comment]
The default value for `sort` is `True` for both pandas and cudf at the moment

**Comment by mrocklin** [comment]
That simplifies things considerably :)

I'll give this a quick shot.  One moment.

**Comment by beckernick** [comment]
@ayushdg should this now be closed with the merging of #5801 ?

**Comment by ayushdg** [comment]
@beckernick Thanks for the ping. Closing as #5801 handles this.
