### ISSUE TITLE
make unify_chunks public API?

### ISSUE THREAD

**Issue by dcherian** [dask/dask#5442]
It seems like it would be useful to add `xarray.unify_chunks` that calls `dask.array.core.unify_chunks`. However `unify_chunks` does not appear to be public API (https://docs.dask.org/en/latest/search.html?q=unify_chunks&check_keywords=yes&area=default)

can this be made public?

**Comment by mrocklin** [comment]
Sure.  See https://github.com/dask/dask/pull/5443

**Comment by dcherian** [comment]
Awesome. Thanks, Matt!
