### ISSUE TITLE
Python 3.5 support broken

### ISSUE THREAD

**Issue by ecederstrand** [dask/dask#5447]
The latest dask release, 2.5.0, contains syntax not supported in Python 3.5:

```python
$ python3.5 -c "from dask.dataframe.io.parquet import arrow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib/python3.5/site-packages/dask/dataframe/io/parquet/arrow.py", line 108
    **kwargs,
            ^
SyntaxError: invalid syntax
```
It looks like there is a Python 3.5 CI pipeline, so I'm not sure how this was not caught.

**Comment by quasiben** [comment]
@ecederstrand thanks for the report.  I wasn't able to reproduce the error (though it does look like an error) because I can't create an env with conda:


```
 1 ❯ conda create -n dask35 python=3.5 dask=2.5.0 -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package wheel conflicts for:
dask=2.5.0 -> pandas[version='>=0.21.0'] -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
python=3.5 -> pip -> wheel
Package pip conflicts for:
dask=2.5.0 -> pandas[version='>=0.21.0'] -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
python=3.5 -> pip
Package python conflicts for:
python=3.5
dask=2.5.0 -> pandas[version='>=0.21.0'] -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
Package certifi conflicts for:
dask=2.5.0 -> pandas[version='>=0.21.0'] -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
python=3.5 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
Package setuptools conflicts for:
python=3.5 -> pip -> wheel -> setuptools
dask=2.5.0 -> pandas[version='>=0.21.0'] -> numpy[version='>=1.11.*,>=1.11.3,<2.0a0,>=1.14.6,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> mkl-service[version='>=2,<3.0a0'] -> six -> python[version='3.6.*,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
```

It's also possible that we don't test the parquet functionality in py35.  @TomAugspurger do you know off hand if this is the case ?

**Comment by TomAugspurger** [comment]
The 3.5 env should include pyarrow.

**Comment by mrocklin** [comment]
Perhaps the fact that conda-forge doesn't produce 3.5 packages anymore
makes it so that this issue was hard to detect, and somewhat rare to run
into.

I tried briefly removing the comma in arrow.py and then rerunning black and
I found that black wanted to add the comma back in.  This means that either
my black version is oldish (you need to use master to avoid this issue) (I
think that I'm using a recent enough version though) or that there is
something else in the arrow.py file that makes it 3.6+, and so black is
deciding to use the trailing comma anyway.

**Comment by jcrist** [comment]
IIUC, if black sees a file already uses python 3.6 syntax (e.g. trailing comma after `**kwargs`) then it will force it to use python 3.6 syntax. See https://github.com/psf/black/issues/419.

**Comment by mrocklin** [comment]
So it sounds like you're saying that there might be some *other* bit of
Python 3.6 syntax in this file that we would want to track down.  The
trailing comma would then be a symptom rather than the cause.

**Comment by quasiben** [comment]
looking into this now

**Comment by mrocklin** [comment]
@quasiben see #5490
