### ISSUE TITLE
Toolz dropin API for dask.bag

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#545]
@wrobstory suggested that dask.bag actually follow the `toolz` API directly.  Additionally it might be nice to have functions that could work equally well on dask.bag objects as on normal Python Iterators and Iterables.

@eriknw might find this interesting.

**Comment by eriknw** [comment]
Good idea.  I'd like to tackle this, and the earliest I can do so is during my flight this Sunday.

Do you envision the toolz API wrapping and using the current `dask.Bag`, or do you think `dask.Bag` should be broken apart?

**Comment by mrocklin** [comment]
I think that we probably want to keep the existing bag API as well.  I'm not sure if this answers your question.

**Comment by mrocklin** [comment]
In hindsight I wish I had written dask.bag in a more toolzy way from the start.   I wouldn't be opposed to a full rewrite that put logic in a more pure functional style but kept the current API as a wrapping.  This is probably far more expensive though.

**Comment by StuartAxelOwen** [comment]
When matching the toolz API, you would keep the monad-esque method chaining, right?  That's something I think dask.bag/spark/javascript all got right.  Most programmers have trouble unpacking code of the `map(filter(reduce(something, map(filter(source)))))` style.

**Comment by mrocklin** [comment]
Toolz generally uses bare functions.  We tend to use currying and a pipe function for repeated function composition.

**Comment by mrocklin** [comment]
This doesn't seem like its going to happen.  I suspect that there is already sufficient inertia behind dask.bag so that this is more likely a fun project than an essential project.  Closing.
