### ISSUE TITLE
ExtensionArray in Dask

### ISSUE THREAD

**Issue by achapkowski** [dask/dask#5457]
In pandas, building an ExtensionArray is straight forward.  When writing them in Dask, do you have to implement anything to handle the chunking?  

The blog posts makes it sound simple: https://blog.dask.org/2019/01/22/dask-extension-arrays 

But I wanted to ensure that was the case.

**Comment by jrbourbeau** [comment]
Dask needs the extension array to be registered with `make_array_nonempty` and `make_scalar`. Please see https://docs.dask.org/en/latest/dataframe-extend.html#extension-arrays for more details and an example

**Comment by jrbourbeau** [comment]
@achapkowski does that documentation clarify how to register third-party extension arrays with `dask.dataframe`? Is it safe to close this issue?

**Comment by TomAugspurger** [comment]
I think we're good, let us know if things can be clarified though @achapkowski.

**Comment by achapkowski** [comment]
So if I read this right, I just need to create a throw away method that creates an empty Series essentially?

**Comment by TomAugspurger** [comment]
I don't think it's a Series. I think you register methods for creating a scalar and an array.
