### ISSUE TITLE
dask.array from_delayed and scheduler='processes' not working with hdf5

### ISSUE THREAD

**Issue by rettigl** [dask/dask#5464]
Hi,
I am trying to load multiple hdf5 files delayed into dask arrays using the 'processes' scheduler. I can load data from multimple h5 files in parallel using delayed with both the 'threads' and the 'processes' scheduler, but once I try to convert the "delayed" objects into dask arrays using the from_delayed function of the dask.array, it only works with the 'threads' scheduler, and fails with "TypeError: can't pickle _thread._local objects" using the 'processes' scheduler. A minimal demonstrator is below:
```
import dask as d
from dask import compute, dataframe as dd, array as da
import random
import h5py
h5files=['./file1.h5','./file2.h5', './file3.h5']
for f in h5files:
    h5f=h5py.File(name=f, mode='w')
    arr = random.sample(range(1000000), 1000000)
    h5f.create_dataset("Stream_0", data=arr, dtype='int32')
    h5f.close()

delayeds = [d.delayed(h5py.File(name=f, mode='r').get('Stream_0')) for f in h5files]
d.compute(delayeds, scheduler='threads')
d.compute(delayeds, scheduler='processes')

darrays = [da.from_delayed(d.delayed(h5py.File(name=f, mode='r').get('Stream_0')), dtype='int32', shape=(1, 1000000)) for f in h5files]
d.compute(darrays, scheduler='threads')
d.compute(darrays, scheduler='processes')
```

The last line is producing the said TypeError. I would be glad for any explanation and possible solution for this problem.
Thanks, Laurenz

**Comment by quasiben** [comment]
I am seeing the same thing you are but I'm not sure why.  

The error specifically is:
> TypeError: can't pickle _thread._local objects

I think that when this occurs this can mean that there is a variable scoping issue ?  There have been issues with h5py files in the past.  For example, in https://github.com/dask/distributed/issues/927 the recommendation is to use the threaded scheduler as you are doing now.  

@TomAugspurger  do you have any additional thoughts here ?

**Comment by TomAugspurger** [comment]
I don't think H5py.File objects are serializable.

```python
In [1]: import pickle; import h5py
f
In [2]: f = h5py.File('foo', 'w')

In [3]: pickle.loads(pickle.dumps(f))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b0f4f19aa43c> in <module>
----> 1 pickle.loads(pickle.dumps(f))

~/Envs/dask-dev/lib/python3.7/site-packages/h5py/_hl/base.py in
__getnewargs__(self)
    306         limitations, look at the h5pickle project on PyPI.
    307         """
--> 308         raise TypeError("h5py objects cannot be pickled")
    309
    310     def __getstate__(self):

TypeError: h5py objects cannot be pickled
```

If you're trying to use it with the distributed or multiprocessing
schedulers, you'll need to take care not to pass H5Py.File objects around.
Instead you'll have to pass functions that take serializable inputs like
strings and create the H5Py file from within the function. Note that
there's also some issues w/ thread safety. The Xarray docs may have some
useful information.

**Comment by TomAugspurger** [comment]
Anything else to do here @rettigl? I'm not sure whether we should add a note in the docs about this, or where it should go.

**Comment by rettigl** [comment]
Thanks @TomAugspurger for your reply.
However I am still not quite sure I understand the behavior. I understood the problem with serializing H5py.File objects, that's why I passed the filename to the constructor within the delayed construct, which also worked in the first test case.  
I don't quite get why it does not work the same way in the second case. Why does it need to serialize the H5py.file object, and not just only create it inside the worker process? The actual reading ot the data is happening only with the compute() call, as far as I can tell from memory consumption and drive access.
Any idea on how to bypass this problem?

**Comment by TomAugspurger** [comment]
> I don't quite get why it does not work the same way in the second case. 

Whats the second case?

**Comment by rettigl** [comment]
```
delayeds = [d.delayed(h5py.File(name=f, mode='r').get('Stream_0')) for f in h5files]
d.compute(delayeds, scheduler='threads')
d.compute(delayeds, scheduler='processes')
```
is working with 'processes', but 
```
darrays = [da.from_delayed(d.delayed(h5py.File(name=f, mode='r').get('Stream_0')), dtype='int32', shape=(1, 1000000)) for f in h5files]
d.compute(darrays, scheduler='threads')
d.compute(darrays, scheduler='processes')
```
not. That's the two cases I mean. Both should to my understanding create a H5py.File object only in the worker process, but that's apparently not the case...

**Comment by TomAugspurger** [comment]
Both of those are creating File objects in the client process. They're arguments to `delayed`, which means they exist in the task graph sent from the client to the scheduler.

**Comment by rettigl** [comment]
Thanks, now I got it. It's actually not the H5py.File objects that needs to get serialized, but the return of the .get function, which is a hd5f dataset object, and that cannot be serialized.
The following works:
`darrays = [da.from_delayed(d.delayed(h5py.File(name=f, mode='r').get('Stream_0')[slice(None,None)]), dtype='int32', shape=(1, 1000000)) for f in h5files]`
also with 'processes', as it converts the hdf5 datasets to arrays first.
