### ISSUE TITLE
read_csv from alternative S3 still tries to connect to Amazon

### ISSUE THREAD

**Issue by fgadaleta** [dask/dask#5468]
```
import dask.dataframe as dd

storage_options = {
    'key': input_config['config']['clientId'],
    'secret': input_config['config']['clientSecret'],
    "client_kwargs": {
        "endpoint_url": "https://s3.alternative-region.other-cloud",
    },
    "config_kwargs": {"s3": {"addressing_style": "virtual"}},
}

df = dd.read_csv('s3://bucket/sample.csv', storage_options=storage_options)
```

Returns 

```EndpointConnectionError: Could not connect to the endpoint URL: "https://bucket.alternative-region.other-cloud.amazonaws.com/?list-type=2&prefix=&delimiter=%2F&encoding-type=url"```

Somewhere `amazonaws.com` is appended to the URL

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
The above is equivalent to
```
session = boto3.session.Session(aws_access_key_id, aws_secret_access_key)
conf = boto3.conf.Config(**config_kwargs)
client = session.client('s3', config=conf, **client_kwargs)
```

Can you please check whether this gets the correct URL?

**Comment by martindurant** [comment]
FYI, doing `fsspec.filesystem('s3', **storage_options)`, which is what Dask effectively does, seems to point to the correct endpoint for me (Could not connect to the endpoint URL: "https://s3.alternative-region.other-cloud/").

**Comment by fgadaleta** [comment]
> The above is equivalent to
> 
> ```
> session = boto3.session.Session(aws_access_key_id, aws_secret_access_key)
> conf = boto3.conf.Config(**config_kwargs)
> client = session.client('s3', config=conf, **client_kwargs)
> ```
> 
> Can you please check whether this gets the correct URL?

boto3 has no attribute conf

**Comment by martindurant** [comment]
Sorry, `botocore.config.Config`

**Comment by fgadaleta** [comment]
```
import botocore

storage_options = {
    'key': input_config['config']['clientId'],
    'secret': input_config['config']['clientSecret'],
    "client_kwargs": {
        "endpoint_url": "https://s3.alternative.cloud",
    },
    "config_kwargs": {"s3": {"addressing_style": "virtual"}},
}


conf = botocore.config.Config(**storage_options)
conf = botocore.config.Config(**storage_options['config_kwargs'])
client = session.client('s3', config=conf, **storage_options['client_kwargs'])

client.download_file(Bucket='buckname', Filename='sample.csv', Key='sample.csv')

```

returns `ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request
`

**Comment by martindurant** [comment]
That's not particularly helpful :|
Perhaps `client.list_buckets()` might be a simpler call to try.

**Comment by fgadaleta** [comment]
> That's not particularly helpful :|
> Perhaps `client.list_buckets()` might be a simpler call to try.

that also gives me 
`EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.nl-ams.amazonaws.com/"
`

**Comment by martindurant** [comment]
I does *not* do that for me, so I can only suppose it is getting some additional config from your system, environment or files or instance metadata.
I have never used "virtual" addressing, so that might be worth reading into.

**Comment by TomAugspurger** [comment]
@fgadaleta were you able to debug this any further?

**Comment by fgadaleta** [comment]
Yes it seems to work. Thanks
