### ISSUE TITLE
drop_duplicates(split_out) ValueError

### ISSUE THREAD

**Issue by mgsnuno** [dask/dask#5488]
python: 3.7.3
dask: 2.5.2

```python
import dask.dataframe as dd

pdf = pd.DataFrame({'data': [tuple([1, 2]), tuple([2]), tuple([3])]})
ddf = dd.from_pandas(pdf, npartitions=2)
ddf.drop_duplicates().compute()  # no problem
ddf.drop_duplicates(split_every=2).compute()  # no problem
ddf.drop_duplicates(split_out=2).compute()  # ValueError: setting an array element with a sequence
```

Any idea why?

P.S. - I know using tuples inside columns is not ideal, but it fits a particular use case. Still it works well if I don't `split_out`, hence though relevant to report.

**Comment by TomAugspurger** [comment]
You can reproduce this exception with just pandas `pd.util.hash_pandas_object(pdf)`. I'm not sure whether it's a bug in pandas or a limitation of NumPy, but I don't think there's much Dask can do.

**Comment by mgsnuno** [comment]
Correct. The question is then: why does `compute([split_every])` works and `compute(split_out)` fails? i.e. what in the call to `split_out` makes it fail?

P.S. - I created an issue in pandas: https://github.com/pandas-dev/pandas/issues/28969

**Comment by TomAugspurger** [comment]
No I don't think there's anything for Dask to do right now.

**Comment by mgsnuno** [comment]
Closing since not related to Dask.
