### ISSUE TITLE
pyarrow integration broken as of 0.15.0

### ISSUE THREAD

**Issue by crepererum** [dask/dask#5498]
Dask is currently passing `preserve_index` to pyarrow. This is deprecated as of pyarrow 0.13.0 (has no effect anymore) and is removed with pyarrow 0.15.0.

**Comment by quasiben** [comment]
@rjzamora is this something you could look into ?

**Comment by rjzamora** [comment]
@crepererum - I see that Dask is passing a `preserve_index` argument to `pa.Table.from_pandas`, but I'm not finding it anywhere else - Am I missing something?

If you are refering to the `from_pandas` case, can you link documentation stating that `preserve_index` is deprecated? (I don't see anything in [0.15.0 documentation](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas))

**Comment by crepererum** [comment]
Oh bollocks, I was using an old dask version locally and was probably also looking at the wrong dask code when trying to figure out the root cause. 🤦‍♂  Sorry for that, works on `latest`.

**Comment by mrocklin** [comment]
No worries.  It's reassuring that you're out there testing things and
comfortable raising issues.

**Comment by quasiben** [comment]
Thanks for answering @rjzamora
