### ISSUE TITLE
Data distribution guarantees for CUDA-based multi-node multi-GPU processing

### ISSUE THREAD

**Issue by cjnolet** [dask/dask#5506]
This is a feature request / discussion issue to outline some problems we are having on RAPIDS cuML and, hopefully, converge on a good solution.

**Problem:** Dask Arrays & Dataframes are assumed to be immutable data structures. As GPU memory is more limited than host memory, users can usually still simulate “in-place” changing of the data structures by assigning transformed instances to previously assigned variables in order for the GPU memory of previous data partitions to be garbage collected. 

Example: 
```
ary = <create dask.array instance>
ary = dask.array.rechunk(ary,(ceil(ary.shape[0]/2), 6))
```

Unfortunately, when a user passes one of these data structures into a function, such as a `fit()` function in cuML, we can’t modify variables in the caller’s namespace, so we can’t use this trick. As a result, performing different data manipulation tasks on the structures, such as redistributing the data across the workers, requires at least one copy of the data, and sometimes many more. Notice in the example below, the cuML `fit()` function will make a copy while the original user’s ary instance cannot be garbage collected:

*Client code:*
```
ary = <create dask.array instance>
model.fit(ary)
```
*cuML Code:*
```
def fit(X):
  X = dask.array.rechunk(ary,(ceil(X.shape[0]/2), 6))
  ...
```

We are finding the need to redistribute the data to be the rule, rather than the exception, in machine learning algorithms. This need arises in just about every algorithm on cuML- from needing to support uniform partition sizes for dense linear algebra operations to spatial partitioning and load balancing for sparse graph-like algorithms, such as DBSCAN, Spectral clustering/embedding, TSNE, UMAP, and many of cuGraph’s algorithms.

There are really two problems we face on cuML with the current system:
1. We aren’t able to make modifications to dask.Array / dask.Dataframe partitions in-place.
2. The distribution of partitions across Dask workers might be extremely skewed for each array/dataframe instance.

The problems above have a significant impact on CUDA algorithms, especially when an MPI-like design is used for communication across workers. We're finding that memory size is our biggest issue in scaling, and this approach consistently doubles our memory consumption.

**Proposed solution(s):**

1. A possible solution to the problem 1 above could be for Dask to allow the rechunking of arrays / dataframes in place. The justification here would be that no elements are being changed, just their partition membership. API-wise, this could be as simple as: 

```
ary = dask.array.rechunk(ary,(ceil(ary.shape[0]/2), 6), inplace=True)
```

*Considerations:*
Note that this does assume ownership over the underlying pointers and could run into `__cuda_array_interface__` problems (eg. pytorch -> dask.array.cupy).
This does increase the possibility that two concurrent Dask jobs could possibly modify the partitioning of ary in two different ways. Wondering if this could be solved with some type of lock. 

2. The Dask system could give more control over the uniformity of the distributions for underlying partitions (even if done indirectly)- perhaps an option in the dask.Array/Dataframe to “prefer more uniform distribution of partitions” so ML heavy workflows receive data better partitioned (for the algos) from Dask.

**Comment by cjnolet** [comment]
Tagging @dantegd

**Comment by TomAugspurger** [comment]
> The distribution of partitions across Dask workers might be extremely skewed for each array/dataframe instance.

Can you clarify: do the data become unbalanced across workers as part of a Dask operation, or
is it the result of a user loading in data? If I'm reading from an on-disk file structure
that's unbalanced like

```
/data
   /a.parquet  # 1,000,000 0rows
   /b.parquet  # 100 rows
```

Then I'd say that's a user issue. They should take care to repartition before calling into cuML,
or work to get better-partitioned files written to Disk.

> allow the rechunking of arrays / dataframes in place

I don't understand this. That would potentially involve transferring data, right?

> perhaps an option in the dask.Array/Dataframe to “prefer more uniform distribution of partitions” so ML heavy workflows receive data better partitioned (for the algos) from Dask.

In general, we prefer uniform chunks to non-uniform ones. IIRC, the default
`rechunk` / `repartition` behaviors that take a number of bytes attempt to do
that. But I don't think we should be altering how data is loaded from disk for
partitioned formats like parquet or Zarr. I may be misunderstanding though.

---

Still thinking over the inplace mutation stuff. I suspect there are better ways to do things, but I'm having trouble putting that to words right now.

**Comment by cjnolet** [comment]
> Can you clarify: do the data become unbalanced across workers as part of a Dask operation, or
is it the result of a user loading in data? If I'm reading from an on-disk file structure
that's unbalanced like...

I am very much in agreement that it should be on the users to partition their data to be more uniform if they want better performance. We are working to make our algorithms more flexible so that we can allow users to control the trade-off between repartitioning and using the distribution of their data as-is. Unfortunately, sparse algorithms like DBSCAN require non-trivial repartitioning and that doesn't seem like something we should be requiring users to do beforehand.

> I don't understand this. That would potentially involve transferring data, right?

The problem I'm outlining is that the repartitioning is causing the need to copy the memory. What I'm proposing as one possible solution is that we free memory once it has been successfully transferred to its destination partition, rather than making a copy of it. This would allow us to modify only the partitioning of the data in place.

**Comment by miguelangel** [comment]
Hi,

I think something as the described below is need:

> The Dask system could give more control over the uniformity of the distributions for underlying partitions (even if done indirectly)- perhaps an option in the dask.Array/Dataframe to “prefer more uniform distribution of partitions” so ML heavy workflows receive data better partitioned (for the algos) from Dask.

I am facing some issues with some ML models such as Random Forest which cannot go deeper because one of the GPUs contains more data than the others (the data seems to be unevenly split between the different GPUs). Once 1 GPU runs OOM, the model training fails.

The above also doesn't let the user of a multi-gpu system to use all the GPU memory available.

Imagine a system with 16 GPUs, and the first is using half a gigabyte more than the remaining. That would mean that 15*0.5Gb of memory is not being used because of the issue described above.

**Comment by mrocklin** [comment]
> A possible solution to the problem 1 above could be for Dask to allow the rechunking of arrays / dataframes in place. The justification here would be that no elements are being changed, just their partition membership. API-wise, this could be as simple as:

In principle allowing this sounds great.  I personally have no idea how to implement it safely though. If anyone has suggestions on how this could be done, that would be welcome.

> The Dask system could give more control over the uniformity of the distributions for underlying partitions (even if done indirectly)- perhaps an option in the dask.Array/Dataframe to “prefer more uniform distribution of partitions” so ML heavy workflows receive data better partitioned (for the algos) from Dask.

I think that such an option would always be selected, so lets just make this automatic.  In principle we probably can't design scheduling algorithms which strongly prefer uniform allocation in general, the space of problems that Dask supports is too broad.  However we could have active memory management that moved data around during quiet times.  "quiet" in this case could be tunable.  

Having a process that watched current memory use and took balancing actions opportunistically would solve a variety of issues.  Here is another issue where this came up https://github.com/dask/distributed/issues/3184

This is a non-trivial undertaking, but I think that it would make lots of people happy.  If anyone wants to devote resources here that would be welcome.

**Comment by mrocklin** [comment]
> Imagine a system with 16 GPUs, and the first is using half a gigabyte more than the remaining. That would mean that 15*0.5Gb of memory is not being used because of the issue described above.

Just to be clear, I don't think that Dask will ever be useful in the context where you want to use *all* of your memory.  It's a dynamic system.  It needs some slop space.  If you need to use all of your memory then you should choose some other tool.

**Comment by miguelangel** [comment]
I understand what you say, but I think that by evenly distributing the data through the workers, the issue described above might be mitigated.

**Comment by pklemenkov** [comment]
Could DASK implement partition classes as Spark does? In that case there would be more freedom for users to control their data.

**Comment by TomAugspurger** [comment]
@pklemenkov can you describe what that would look like? You can already put individual pieces of data on specific workers. Perhaps you could build something with that?

**Comment by quasiben** [comment]
I think this issue has gone stale and it's ok to close if folks want to continue the discussion feel free to reopen
