### ISSUE TITLE
infer_storage_options fails with on file paths with two leading slashes.

### ISSUE THREAD

**Issue by samkaufman** [dask/dask#5519]
Calling `dask.bytes.utils.infer_storage_options("//tmp/f”)` returns:

```python
{'protocol': 'file', 'path': '/f', 'host': 'tmp’}
```

but I expected it to return:

```python
{'protocol': 'file', 'path': '//tmp/f'}
```

**Comment by quasiben** [comment]
@samkaufman `infer_storage_options` comes from [fsspec](https://github.com/intake/filesystem_spec/blob/master/fsspec/utils.py#L12-L15) and the bug may need to be fixed there

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
This is a windows network path? I believe it is fixed in fsspec master.

**Comment by TomAugspurger** [comment]
@samkaufman can you try with fsspec master (https://github.com/intake/filesystem_spec/)?

**Comment by samkaufman** [comment]
@martindurant It is not. It’s a good ol’ POSIX path with two leading slashes.

@TomAugspurger Just did. It still exists.

Closing this now in favor of [fsspec issue #164](https://github.com/intake/filesystem_spec/issues/164).
