### ISSUE TITLE
Dask Concatenation of a Series of Dataframes

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#5529]
I've asked a variant of this question already here: https://stackoverflow.com/q/58498507/582917

And I solved it by doing an `groupby`, then `apply`, and finally `reduction`. (I'd like to know whether that could be combined together into a custom aggregation).

Another problem I have is that `map_partitions` behaves entirely different from `groupby` and `apply`. Intuitively I think that both situations is the "map" part of the general map-reduce operation.

In the case of groupby and then apply. When the function returns a series, the result is a dask dataframe where each row is the series of dataframes. Thus the entire dask dataframe columns is equal to the series index.

In the case of `map_partitions`, if the function returns a series, the result is a dask series. I would have expected the same result, a dask dataframe where each row is a series of dataframes.

In this below code, I've done the same thing as the SO question, but this time I remove the `groupby` operation, because I just want to do the same thing but across arbitrary partitions, and not the actual groups that I used in the SO question.

```py
import pandas as pd
import dask.dataframe as dd
import operator
import numpy as np
import math
import itertools


def apportion_pcts(pcts, total):
    """Apportion an integer by percentages
    Uses the largest remainder method
    """
    if (sum(pcts) != 100):
        raise ValueError('Percentages must add up to 100')
    proportions = [total * (pct / 100) for pct in pcts]
    apportions = [math.floor(p) for p in proportions]
    remainder = total - sum(apportions)
    remainders = [(i, p - math.floor(p)) for (i, p) in enumerate(proportions)]
    remainders.sort(key=operator.itemgetter(1), reverse=True)
    for (i, _) in itertools.cycle(remainders):
        if remainder == 0:
            break
        else:
            apportions[i] += 1
            remainder -= 1
    return apportions


images_df = dd.read_csv('./tests/data/classification/images.csv', blocksize=1024)

output_ratio = [80, 20]


def partition_class(group_df, ratio):
    proportions = apportion_pcts(ratio, len(group_df))
    partitions = []
    start = 0
    for proportion in proportions:
        s = slice(start, start + proportion)
        partitions.append(group_df.iloc[s, :])
        start += proportion
    return pd.Series(partitions)


partitioned_schema = dd.utils.make_meta(
    [(i, object) for i in range(len(output_ratio))],
    pd.Index([], name='image_class_id'))

partitioned_ds = images_df.apply(
    partition_class,
    axis=1,
    meta=partitioned_schema,
    ratio=output_ratio)

# each value of the dask series, is a dask series
# each of the dataframes in the dask series should be concatenated
partitioned_ds.loc[0]
partitioned_ds.loc[1]
```

Based on the SO question https://stackoverflow.com/q/58498507/582917, I want to get the same kind of output.

At the end of the day, it should be a dask series of pandas dataframes. How do I achieve this with dask?

**Comment by mrocklin** [comment]
As in that question I asked that you produce a minimal verifiable complete
example.  I've pointed to links on what is requested there.  Do you have
the time to take a few minutes and read over them?

**Comment by CMCDragonkai** [comment]
I did provide the minimal executable example. The code was changed to use an embedded dataset.

**Comment by CMCDragonkai** [comment]
The whole code copied from SO is executable just with python3. `python ./test.py`.

```py
import pandas as pd
import dask.dataframe as dd
import operator
import numpy as np
import math
import itertools

def apportion_pcts(pcts, total):
    """Apportion an integer by percentages
    Uses the largest remainder method
    """
    if (sum(pcts) != 100):
        raise ValueError('Percentages must add up to 100')
    proportions = [total * (pct / 100) for pct in pcts]
    apportions = [math.floor(p) for p in proportions]
    remainder = total - sum(apportions)
    remainders = [(i, p - math.floor(p)) for (i, p) in enumerate(proportions)]
    remainders.sort(key=operator.itemgetter(1), reverse=True)
    for (i, _) in itertools.cycle(remainders):
        if remainder == 0:
            break
        else:
            apportions[i] += 1
            remainder -= 1
    return apportions


# images_df = dd.read_csv('./tests/data/classification/images.csv')
images_df = pd.DataFrame({"image_id": [0,1,2,3,4,5], "image_class_id": [0,1,1,3,3,5]})
images_df = dd.from_pandas(images_df, npartitions=1)

output_ratio = [80, 20]

def partition_class (partition):
    size = len(partition)
    proportions = apportion_pcts(output_ratio, size)
    slices = []
    start = 0
    for proportion in proportions:
        s = slice(start, start + proportion)
        slices.append(partition.iloc[s, :])
        start = start+proportion
    slicess = pd.Series(slices)
    return slicess

partitioned_schema = dd.utils.make_meta(
    [(0, object), (1, object)], pd.Index([], name='image_class_id'))
partitioned_df = images_df.groupby('image_class_id')
partitioned_df = partitioned_df.apply(partition_class, meta=partitioned_schema)
```

**Comment by TomAugspurger** [comment]
Thanks. Do you think that's a minimal example, or can it be narrowed down further?

If it's already minimal, I can try to make time to look at it next week. But it looks quite complex still so I'll need to make time. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may have some hints on how to simplify things. At a glance, I don't see an expected output.

**Comment by CMCDragonkai** [comment]
What's complex about it? The only thing that's non-dask is my `apportion_pcts` function which has nothing to do with the problem. That's just the setup. The problem is just about concatenating a series of dataframes.

I ended up solving it with:

```
ds_schema = dd.utils.make_meta((None, object))

partitioned_ds = images_df.map_partitions(
    partition_class,
    ratio=output_ratio,
    meta=ds_schema)

def zip_partitions(partitions_df, random_seed=None):
    partitions = []
    for i in partitions_df.columns:
        partition = pd.concat(partitions_df[i].tolist())
        partition = partition.sample(frac=1, random_state=random_seed).reset_index(drop=True)
        partitions.append(partition)
    return pd.Series(partitions)

partitioned_ds = partitioned_ds.reduction(
    chunk=lambda s: s,
    aggregate=zip_partitions,
    meta=dd.utils.make_meta((None, object)),
    aggregate_kwargs={
        "random_seed": None
    }
)
```

**Comment by TomAugspurger** [comment]
So you found a workaround @CMCDragonkai? Anything else to do here?

**Comment by jrbourbeau** [comment]
Just checking in here, @CMCDragonkai is there anything else to do for this issue? Otherwise I'm inclined to close it

**Comment by CMCDragonkai** [comment]
I worked around it. So there's no direct solution to the OP?

On 4 November 2019 05:49:40 GMT+11:00, James Bourbeau <notifications@github.com> wrote:
>Just checking in here, @CMCDragonkai is there anything else to do for
>this issue? Otherwise I'm inclined to close it
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/dask/issues/5529#issuecomment-549166791

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jrbourbeau** [comment]
I personally haven't been able to dive into your example yet and am not likely to be able to in the near future 

> I feel like the API can be redesigned so that operations are more obvious. I would think of things like Haskell's standard library.

If you have any concrete suggestions for what you would like to see, please feel free to open up a separate issue regrading proposed API changes / additions
