### ISSUE TITLE
Dask read_csv does not work when file is in local Network 

### ISSUE THREAD

**Issue by lchara03** [dask/dask#5532]
There is a problem when I try to read a csv file from file in local network.

Using pandas read_csv it works fine. i.e. `pd.read_csv(r'\\localnet\folder\file.csv')` but does not work with dask.dataframe.  I also tried `dd.read_csv(r'file:\localnet\folder\file.csv') `

Thank you

**Comment by TomAugspurger** [comment]
cc @martindurant.

@lchara03 what scheduler are you using? Do you create a `Client`, or are you just using the default threaded scheduler?

Can you set

```
import dask

dask.config.set(scheduler='single-threaded')
```

and post the traceback of `dd.read_csv("path/to/file")`?

**Comment by martindurant** [comment]
This should be fixed in fsspec master. Please try it.
If so, we should probably release it.

**Comment by jrbourbeau** [comment]
Just checking in here, @lchara03 did using the current `master` branch of `fsspec` resolve this issue?

**Comment by jrbourbeau** [comment]
Closing for now. @lchara03 please feel free to re-open if this problem persists with the latest release of `fsspec`. Thanks!
