### ISSUE TITLE
Hide nbytes in HTML repr with sparse blocks?

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#5543]
The `nbytes` reported by the HTML array repr is incorrect with we have sparse blocks inside an array.

This issue was discussed in https://github.com/dask/dask/issues/5313. In general, knowing the `.nbytes` correctly isn't possible with sparse blocks. I think we should not include the memory usage when the `_meta` is sparse.

<table>
<tr>
<td>
<table>
  <thead>
    <tr><td> </td><th> Array </th><th> Chunk </th></tr>
  </thead>
  <tbody>
    <tr><th> Bytes </th><td> 800 B </td> <td> 800 B </td></tr>
    <tr><th> Shape </th><td> (10, 10) </td> <td> (10, 10) </td></tr>
    <tr><th> Count </th><td> 2 Tasks </td><td> 1 Chunks </td></tr>
    <tr><th> Type </th><td> float64 </td><td> sparse.COO </td></tr>
  </tbody>
</table>
</td>
<td>
<svg width="170" height="170" style="stroke:rgb(0,0,0);stroke-width:1" >

  
  <line x1="0" y1="0" x2="120" y2="0" style="stroke-width:2" />
  <line x1="0" y1="120" x2="120" y2="120" style="stroke-width:2" />

  
  <line x1="0" y1="0" x2="0" y2="120" style="stroke-width:2" />
  <line x1="120" y1="0" x2="120" y2="120" style="stroke-width:2" />

  
  <polygon points="0.000000,0.000000 120.000000,0.000000 120.000000,120.000000 0.000000,120.000000" style="fill:#ECB172A0;stroke-width:0"/>

  
  <text x="60.000000" y="140.000000" font-size="1.0rem" font-weight="100" text-anchor="middle" >10</text>
  <text x="140.000000" y="60.000000" font-size="1.0rem" font-weight="100" text-anchor="middle" transform="rotate(0,140.000000,60.000000)">10</text>
</svg>
</td>
</tr>
</table>

**Comment by mrocklin** [comment]
This sounds good to me.  What would the check here be, `"sparse" in `typename(x)`?

**Comment by jrbourbeau** [comment]
That seems like a reasonable check. We should also use `dask.utils.typename` in the HTML repr, I don't think we currently are

https://github.com/dask/dask/blob/0871699c0e4b021fca4a3104042d1adf7c5fd5d5/dask/array/core.py#L1269-L1270
