### ISSUE TITLE
Implement nunique (and all supported methods) on Resampler

### ISSUE THREAD

**Issue by birdsarah** [dask/dask#5547]
`df.resample('1d').nunique()` returns `AttributeError: 'Resampler' object has no attribute 'nunique'` 

However, following the code in `/dask/dataframe/tseries/resample.py`  `df.resample('1d')._agg('nunique').compute()` works as expected.

This is a feature request to update Resampler class with all supported methods.

**Comment by jrbourbeau** [comment]
That seems reasonable, thanks for opening up a feature request @birdsarah! Linking to the `Resampler` API docs in pandas for reference https://pandas.pydata.org/pandas-docs/stable/reference/resampling.html

**Comment by quasiben** [comment]
I've been looking into implementing this, and while it is relatively straightforward I'm running into resampling behavior which seems to be incorrect:


```python
In [14]: ddf.resample('1d').mean().compute()                                                                                                                                          
Out[14]: 
                     id         x         y
timestamp                                  
2000-01-01  1000.054352  0.002492  0.000309
2000-01-02   999.782060  0.000381  0.003025
2000-01-03   999.882674 -0.000053  0.000098
2000-01-04          NaN       NaN       NaN

In [15]: df.resample('1d').mean()                                                                                                                                                     
Out[15]: 
                     id         x         y
timestamp                                  
2000-01-01  1000.054352  0.002492  0.000309
2000-01-02   999.782060  0.000381  0.003025
2000-01-03   999.882674 -0.000053  0.000098
```

When resampling, the last row will often be `NaN` -- is this known ?

**Comment by TomAugspurger** [comment]
I wasn't aware of that. It does look buggy.

**Comment by quasiben** [comment]
This error might be an issue with `dask.datasets.timeseries`.  For example, in the following:

> ddf = dask.datasets.timeseries(start='2000-01-01', end='2000-01-04')

The divisions will be:

```python
In [21]: ddf.divisions
Out[21]:
(Timestamp('2000-01-01 00:00:00', freq='D'),
 Timestamp('2000-01-02 00:00:00', freq='D'),
 Timestamp('2000-01-03 00:00:00', freq='D'),
 Timestamp('2000-01-04 00:00:00', freq='D'))
```

but there is no value at `2000-01-04`
