### ISSUE TITLE
Implement cross_val_score

### ISSUE THREAD

**Issue by magehex** [dask/dask#5552]
Hello,

could you please implement cross_val_score

**Comment by quasiben** [comment]
@magehex glad to see your interest in dask.  Could you be a bit more descriptive in what you are asking here ?  Possibly write down some pseudo code ?

**Comment by magehex** [comment]
Thank you for your answer @quasiben . You could have a look at https://github.com/dask/dask-ml/issues/578
That is what I want to do.

**Comment by jrbourbeau** [comment]
@magehex let's continue this conversation over in https://github.com/dask/dask-ml/issues/578
