### ISSUE TITLE
Note on `Add x.str.cat (#3028)` (lines 125-126)

### ISSUE THREAD

**Issue by samuelkampa** [dask/dask#5555]
It's not clear to me why `String.str.cat` isn't supported in Dask when `others == None`. Not having the ability to concat a single series into a string is a significant cost, I think. Unless there's a reason for this condition, I recommend deleting lines 126-126.

**Comment by TomAugspurger** [comment]
Do you have a minimal example of the input for a `.str.cat` with a dask series would be?

What would the return type be?

And the result is a single string, right? Should we assume that string fits in memory?

**Comment by samuelkampa** [comment]
Where `others == None`, `String.str.cat` in Dask should be isomorphic with `String.str.cat` in Pandas. For example:
```
import pandas as pd
import dask.dataframe as dd
df = pd.DataFrame([['x','x'], ['y','y'], ['z','z']], columns=['a','b'])
dff = dd.from_pandas(df, npartitions=2)
dff['a'].str.cat(sep=' ')
```
The result would indeed be a single string. We should assume that the string fits in memory.

**Comment by jrbourbeau** [comment]
@samuelkampa any interest in submitting a PR?

**Comment by samuelkampa** [comment]
Just submitted a PR. Thanks!

**Comment by TomAugspurger** [comment]
@samuelkampa was a PR submitted for this? I don't see one linking to this issue.

**Comment by jrbourbeau** [comment]
xref https://github.com/dask/dask/pull/5559
