### ISSUE TITLE
dask.dataframe.head(n) method results in no rows.

### ISSUE THREAD

**Issue by alphahmed** [dask/dask#5557]

**Comment by alphahmed** [comment]
Passing head(n) method to a dask dataframe which is a product of another dataframe(s), like join( ) results in empty dataframe with zero rows and an error message of not sufficient elements to display.

Iterating through the index elements provides results:
``
df3 = df1.join(df2)

display(df3.head(5))

UserWarning: Insufficient elements for `head`. 5 elements requested, only 0 elements available. Try passing larger `npartitions` to `head`.
warnings.warn(msg.format(n, len(r)))``

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @alphahmed, are you able to produce a minimal example? (see https://blog.dask.org/2018/02/28/minimal-bug-reports for reference)

**Comment by jrbourbeau** [comment]
Is this the type of behavior you're running into?

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: df = pd.DataFrame(columns=['a', 'b'])

In [4]: ddf = dd.from_pandas(df, npartitions=2)

In [5]: ddf.head()
/Users/jbourbeau/github/dask/dask/dask/dataframe/core.py:5744: UserWarning: Insufficient elements for `head`. 5 elements requested, only 0 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(msg.format(n, len(r)))
Out[5]:
Empty DataFrame
Columns: [a, b]
Index: []

In [6]: df.head()
Out[6]:
Empty DataFrame
Columns: [a, b]
Index: []
```

Where you expecting different behavior for an empty DataFrame?

**Comment by alphahmed** [comment]
No, the new dataframe I’m applying the display head(n) method is a result of joining a dataframe of more than 2 million rows and another one with few hundred rows. Their indices are dateTime values.

**Comment by alphahmed** [comment]
> Thanks for opening an issue @alphahmed, are you able to produce a minimal example? (see https://blog.dask.org/2018/02/28/minimal-bug-reports for reference)

I provided a minimal sample above with the exact error message I am getting. It’s a result of joining a df with few millions rows with few dozens of columns, and another df with few thousands of rows with three columns. Their indices are dateTime values, and the error message I am getting is:

UserWarning: Insufficient elements for head. 5 elements requested, only 0 elements available. Try passing larger npartitions to head.
warnings.warn(msg.format(n, len(r)))``

**Comment by mrocklin** [comment]
Right, as the message suggests, head only looks at the first partition for efficiency reasons.  it looks like your first partition did not have any rows in it.  This can happen with certain joins.  The suggestion that it provides is to pass the `npartitions=` keyword to head.  Does this solve your problem?

**Comment by alphahmed** [comment]
> Right, as the message suggests, head only looks at the first partition for efficiency reasons. it looks like your first partition did not have any rows in it. This can happen with certain joins. The suggestion that it provides is to pass the `npartitions=` keyword to head. Does this solve your problem?

Thank you mrocklin, you're right. I passed `npartitons=2` and it's positive!
