### ISSUE TITLE
dd.read_csv : Skip csv files for those pandas fails

### ISSUE THREAD

**Issue by Ahrimanox** [dask/dask#5561]
Hi,
I don't know if this is the best place to ask about that.

I read a bunch of CSV files with dd.read_csv.
Some of them are malformed, non standard or just have bad date format.

This could lead to a dd.read_csv fail just because pandas failed to read one (or more) of them.
Is there a way or an option for dd.read_csv to skip files that couldn't be loaded by pandas ?

At that day, I have to try reading each file individually with many dask delayed objects and skip files for those an Exception has been raised during pandas read_csv.

Is there a simpler way to achieve this, or is it possible to implement it in dask dd.read_csv method ?

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @Ahrimanox! 

> Is there a way or an option for dd.read_csv to skip files that couldn't be loaded by pandas ?

Not that I'm aware of. If you know ahead of time which csv files pandas has issues with, you can pass `dd.read_csv` a list of files which you know aren't malformed, etc.

**Comment by Ahrimanox** [comment]
Thanks for your quick response.

I don't know which files are malformed. 
So i have to read all of them once individually to be sure which one I will append to a list of valid files.
That list, then, i'll pass to `dd.read_csv`.
This leads me to load twice each files.

**Comment by jrbourbeau** [comment]
Are you using the distributed scheduler? If so, you can manually remove `Future`s which have failed (would correspond to `pd.read_csv` calls which have failed). Something like what's outlined in https://docs.dask.org/en/latest/debugging.html#remove-failed-futures-manually

That would allow you to load each file only once

**Comment by TomAugspurger** [comment]
I don't think dask can feasibly add an option to ignore failures. That
would break the data model, since the number
of partitions is tied to the number of files in the directory. We wouldn't
know the actual number of partitions (the
number of loaded files) until runtime.

**Comment by jrbourbeau** [comment]
Yeah, I agree with Tom that adding such an option doesn't seem feasible to do lazily. @Ahrimanox I'd recommend sticking with your current `delayed` approach or perhaps using futures with the distributed scheduler to avoid multiple reads.

**Comment by jrbourbeau** [comment]
Closing as I don't think there's anything to do here on the Dask side
