### ISSUE TITLE
dask without numpy

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#5564]
Follow-up from https://github.com/dask/dask/pull/5511

In theory, according to setup.py, dask[bag, delayed] can run without numpy or pandas being installed.
In practice, at the moment there are no CI tests for the use case, and a quick local try highlighted multiple major breakages.

To reproduce:
1. remove the lines for numpy and pandas from ``continuous_integration/travis/travis-mindeps-bag-delayed.yml`` (at the moment of writing, only available in https://github.com/dask/dask/pull/5511)
2. ``conda env create -n dask-nonumpy -f continuous_integration/travis/travis-mindeps-bag-delayed.yml``
3. ``conda activate dask-nonumpy``
4. ``pytest``

OR
1. ``conda create -n dask-nonumpy python=3.6 pytest pytest-xdist``
2. ``conda activate dask-nonumpy``
3. ``pip install dask[bag, delayed]``
4. ``pytest``

**Comment by mrocklin** [comment]
Is it that tests fail, or does Dask itself not run well?  Are the only changes to be made here in testing files, or are there bugs in actual code as well?

In principle making things work well without numpy/pandas is, I think, important.  Having tests run well would also be nice, but probably isn't a huge deal today.  I don't get the sense that this affects anyone in practice.

If it's cheap from a maintenance/code complexity perspective to clean things up then I'm +1 for fixing things up.  I think that I would be -1 on adding a new CI job (people have complained about CI getting backed up in the past, so this is more of a priority I think).  I would also be against making the test suite significantly more expensive to support this, but I suspect that there are lightweight ways to resolve the issues here.

**Comment by crusaderky** [comment]
@mrocklin sorry for sounding pedantic, but - what exactly is your definition of "run well", when automated tests won't even start? Play around with it by hand and verify that it doesn't crash (at least until the next commit)?

The test failures are *not* localized to ``dask/array/tests`` and ``dask/dataframe/tests``; they are all over the place, so I'm in no position to say if there are bugs in the actual code or not.

**Comment by mrocklin** [comment]
> what exactly is your definition of "run well", when automated tests won't even start?

I'm generally strongly motivated by user experience.  So if users were frequently presenting with `ImportErrors` then that would be a strong motivation to take action quickly.  This doesn't happen today, so I'm not super concerned by the import issues.  I still think that it would be great to fix things, but it's less of a priority for me personally.

**Comment by crusaderky** [comment]
So you basically say it's OK to accidentally make the next dask version completely unusable for minimal bag/delayed users, and that the only thing that will save them is the ability of the code reviewers' to spot it in time??

Look, I am sympathetic with the people getting frustrated by the slowness of CI, as I'm definitely one of them. But offering a massive amount of different legal (and realistic) setups and then not testing them is much worse.

*The* solution, of course, would be to drastically reduce the number of degrees of freedom, that are offered *and thus need to be tested*, to only what actually brings a benefit for the users. This would mean:
- Make PyYAML, cloudpickle, partd, fsspec, and toolz mandatory. They (and their dependencies) are tiny pure-python packages and I cannot think of any case where a user will get a tangible benefit from not installing them.
- Keep (and test) the use case for numpy+pandas not being installed. Us conda and wheel users tend to forget how painful they are when precompiled packages aren't readily available (e.g. android, ARM in general, alternative Python interpreters). Also they take up a huge amount of disk space which embedded and docker users would be happy to save.
- Drop use case for numpy being installed, but not pandas (if you can have one, you won't have problems having the other).
- Keep (and test) the use case for distributed not being installed, because it requires a myriad of sub-dependencies.

This would send the amount of switches in setup.py down from the current 7 to just 3, which could be sensibly covered by CI.

**Comment by crusaderky** [comment]
I am happy to skip testing these edge cases in PRs, as long as you're happy to have master occasionally break after a merge (which I agree sounds like a reasonable trade-off).

**Comment by jrbourbeau** [comment]
> The test failures are not localized to dask/array/tests and dask/dataframe/tests; they are all over the place, so I'm in no position to say if there are bugs in the actual code or not.

FWIW, at least for the `dask[bag, delayed]` case, all test collection / failure issues are related to dependency `ImportError`s. With the following changes, `pytest dask` runs successfully without NumPy or Pandas installed. 

<details>
<summary>Diff:</summary>

```diff
diff --git a/conftest.py b/conftest.py
index be66c1ef..3144ef11 100644
--- a/conftest.py
+++ b/conftest.py
@@ -15,6 +15,22 @@ collect_ignore = [
     "dask/dot.py",
 ]
 
+try:
+    import numpy
+except ImportError:
+    numpy = None
+
+try:
+    import pandas
+except ImportError:
+    pandas = None
+
+collect_ignore_glob = []
+if numpy is None:
+    collect_ignore_glob.append("dask/array/*")
+if pandas is None:
+    collect_ignore_glob.append("dask/dataframe/*")
+
 
 def pytest_addoption(parser):
     parser.addoption("--runslow", action="store_true", help="run slow tests")
diff --git a/dask/array/tests/test_array_core.py b/dask/array/tests/test_array_core.py
index 90c391dd..1cce38df 100644
--- a/dask/array/tests/test_array_core.py
+++ b/dask/array/tests/test_array_core.py
@@ -3,6 +3,7 @@ import copy
 import pytest
 
 np = pytest.importorskip("numpy")
+print("np = {}".format(np))
 
 import os
 import time
diff --git a/dask/bag/tests/test_bag.py b/dask/bag/tests/test_bag.py
index 39ff6d65..b11e8d35 100644
--- a/dask/bag/tests/test_bag.py
+++ b/dask/bag/tests/test_bag.py
@@ -699,6 +699,7 @@ def test_from_long_sequence():
 
 
 def test_from_empty_sequence():
+    pytest.importorskip("dask.dataframe")
     b = db.from_sequence([])
     assert b.npartitions == 1
     df = b.to_dataframe(meta={"a": "int"}).compute()
diff --git a/dask/bytes/tests/test_s3.py b/dask/bytes/tests/test_s3.py
index 871e54de..ab4ada0c 100644
--- a/dask/bytes/tests/test_s3.py
+++ b/dask/bytes/tests/test_s3.py
@@ -4,7 +4,6 @@ from contextlib import contextmanager
 from distutils.version import LooseVersion
 
 import pytest
-import numpy as np
 
 
 s3fs = pytest.importorskip("s3fs")
@@ -121,6 +120,7 @@ def s3_with_yellow_tripdata(s3):
       for mm from 01 - 12.
     """
     pd = pytest.importorskip("pandas")
+    np = pytest.importorskip("numpy")
 
     data = {
         "VendorID": {0: 2, 1: 1, 2: 1, 3: 1, 4: 1},
@@ -389,8 +389,8 @@ def test_parquet(s3, engine):
     lib = pytest.importorskip(engine)
     if engine == "pyarrow" and LooseVersion(lib.__version__) < "0.13.1":
         pytest.skip("pyarrow < 0.13.1 not supported for parquet")
+    np = pytest.importorskip("numpy")
     import pandas as pd
-    import numpy as np
 
     url = "s3://%s/test.parquet" % test_bucket_name
 
@@ -423,7 +423,7 @@ def test_parquet_wstoragepars(s3):
     pytest.importorskip("fastparquet")
 
     import pandas as pd
-    import numpy as np
+    np = pytest.importorskip("numpy")
 
     url = "s3://%s/test.parquet" % test_bucket_name
 
diff --git a/dask/diagnostics/tests/test_progress.py b/dask/diagnostics/tests/test_progress.py
index 82a008ea..3a50c236 100644
--- a/dask/diagnostics/tests/test_progress.py
+++ b/dask/diagnostics/tests/test_progress.py
@@ -21,9 +21,9 @@ def check_bar_completed(capsys, width=40):
 
 
 def test_array_compute(capsys):
-    from dask.array import ones
+    da = pytest.importorskip("dask.array")
 
-    data = ones((100, 100), dtype="f4", chunks=(100, 100))
+    data = da.ones((100, 100), dtype="f4", chunks=(100, 100))
     with ProgressBar():
         out = data.sum().compute()
     assert out == 10000
diff --git a/dask/tests/test_config.py b/dask/tests/test_config.py
index fd37a4ca..d3907b3f 100644
--- a/dask/tests/test_config.py
+++ b/dask/tests/test_config.py
@@ -1,4 +1,3 @@
-import yaml
 import os
 import stat
 import sys
@@ -6,6 +5,7 @@ from collections import OrderedDict
 from contextlib import contextmanager
 
 import pytest
+yaml = pytest.importorskip("yaml")
 
 import dask.config
 from dask.config import (
diff --git a/dask/tests/test_context.py b/dask/tests/test_context.py
index 38f81585..7197271f 100644
--- a/dask/tests/test_context.py
+++ b/dask/tests/test_context.py
@@ -1,9 +1,11 @@
+import pytest
+
 from dask.context import globalmethod
-import dask.array as da
 import dask
 
 
 def test_with_get():
+    da = pytest.importorskip("dask.array")
     var = [0]
 
     def myget(dsk, keys, **kwargs):
diff --git a/dask/tests/test_delayed.py b/dask/tests/test_delayed.py
index 50c4a5ab..939a5562 100644
--- a/dask/tests/test_delayed.py
+++ b/dask/tests/test_delayed.py
@@ -11,7 +11,6 @@ import dask
 from dask import compute
 from dask.delayed import delayed, to_task_dask, Delayed
 from dask.utils_test import inc
-from dask.dataframe.utils import assert_eq
 
 try:
     from operator import matmul
@@ -604,9 +603,11 @@ def test_attribute_of_attribute():
 
 
 def test_check_meta_flag():
+    pytest.importorskip("dask.dataframe")
     from pandas import Series
     from dask.delayed import delayed
     from dask.dataframe import from_delayed
+    from dask.dataframe.utils import assert_eq
 
     a = Series(["a", "b", "a"], dtype="category")
     b = Series(["a", "c", "a"], dtype="category")
diff --git a/dask/tests/test_highgraph.py b/dask/tests/test_highgraph.py
index 33027c4d..e9167731 100644
--- a/dask/tests/test_highgraph.py
+++ b/dask/tests/test_highgraph.py
@@ -2,12 +2,12 @@ import os
 
 import pytest
 
-import dask.array as da
 from dask.utils_test import inc
 from dask.highlevelgraph import HighLevelGraph
 
 
 def test_visualize(tmpdir):
+    da = pytest.importorskip("dask.array")
     pytest.importorskip("graphviz")
     fn = str(tmpdir)
     a = da.ones(10, chunks=(5,))
@@ -29,6 +29,7 @@ def test_basic():
 
 
 def test_keys_values_items_methods():
+    da = pytest.importorskip("dask.array")
     a = da.ones(10, chunks=(5,))
     b = a + 1
     c = a + 2
diff --git a/dask/tests/test_multiprocessing.py b/dask/tests/test_multiprocessing.py
index 16a88641..bd803900 100644
--- a/dask/tests/test_multiprocessing.py
+++ b/dask/tests/test_multiprocessing.py
@@ -2,9 +2,6 @@ import sys
 import multiprocessing
 from operator import add
 import pickle
-import random
-
-import numpy as np
 
 import pytest
 import dask
@@ -15,6 +12,7 @@ from dask.utils_test import inc
 
 def test_pickle_globals():
     """ Unrelated globals should not be included in serialized bytes """
+    np = pytest.importorskip("numpy")
 
     def unrelated_function(a):
         return np.array([a])
@@ -125,8 +123,14 @@ def test_optimize_graph_false():
     assert len(keys) == 2
 
 
-@pytest.mark.parametrize("random", [np.random, random])
+@pytest.mark.parametrize("random", ["numpy", "random"])
 def test_random_seeds(random):
+    if random == "numpy":
+        np = pytest.importorskip("numpy")
+        random = np.random
+    else:
+        import random
+
     def f():
         return tuple(random.randint(0, 10000) for i in range(5))
 
diff --git a/dask/tests/test_system.py b/dask/tests/test_system.py
index 575a0bfd..1e68f8f1 100644
--- a/dask/tests/test_system.py
+++ b/dask/tests/test_system.py
@@ -3,7 +3,6 @@ import io
 import os
 import sys
 
-import psutil
 import pytest
 
 from dask.system import cpu_count
@@ -18,6 +17,7 @@ def test_cpu_count():
 
 @pytest.mark.parametrize("dirname", ["cpuacct,cpu", "cpu,cpuacct", None])
 def test_cpu_count_cgroups(dirname, monkeypatch):
+    psutil = pytest.importorskip("psutil")
     def mycpu_count():
         # Absurdly high, unlikely to match real value
         return 250
diff --git a/dask/tests/test_utils.py b/dask/tests/test_utils.py
index 92c1d26d..7ed09f97 100644
--- a/dask/tests/test_utils.py
+++ b/dask/tests/test_utils.py
@@ -3,7 +3,6 @@ import functools
 import operator
 import pickle
 
-import numpy as np
 import pytest
 
 from dask.utils import (
@@ -152,6 +151,7 @@ def test_dispatch_lazy():
 
 
 def test_random_state_data():
+    np = pytest.importorskip("numpy")
     seed = 37
     state = np.random.RandomState(seed)
     n = 10000
@@ -556,6 +556,7 @@ def test_parse_timedelta():
 
 
 def test_is_arraylike():
+    np = pytest.importorskip("numpy")
     assert is_arraylike(0) is False
     assert is_arraylike(()) is False
     assert is_arraylike(0) is False
```

</details>


Just wanted to say that I also get the sense this isn't a huge problem for users and probably doesn't merit additional CI jobs on PRs

**Comment by jcrist** [comment]
This is why we have the import tests. In general things fail on import if the minimal dependencies aren't installed. Functionality that requires a specific sub-dependency should use local imports. https://github.com/dask/dask/blob/master/continuous_integration/travis/test_imports.sh

Balancing CI costs and test value, the current quick import tests have served us well the last couple of years, I would need to see a real user issue for me to see value in changing this.

**Comment by mrocklin** [comment]
OK.  Closing this.  Thanks all.
