### ISSUE TITLE
Worker hangs due to duplicate task key on the same worker within milli second gap

### ISSUE THREAD

**Issue by pranav-kohli** [dask/dask#5567]
I am running xgboost classifier on a dask cluster with adaptive deployment enabled.
A problem occurs randomly that on one of the worker when a task is submitted, it goes to waiting state, then the same task is resubmitted to the worker again within some millisecond difference and a deadlock occurs.

I cant produce a minimal reproducible sample for this as it happens very randomly

Dask : 0.17.5
Distributed : 1.21.6

Attached is the screenshot for worker on the diagnostics page

<img width="1440" alt="Screenshot 2019-11-07 at 2 37 10 PM" src="https://user-images.githubusercontent.com/9332650/68375611-2a3e2400-016d-11ea-8e7b-71e3165330c7.png">

Worker call stack
<img width="1439" alt="Screenshot 2019-11-07 at 2 45 15 PM" src="https://user-images.githubusercontent.com/9332650/68375724-5fe30d00-016d-11ea-971d-cefb352714d3.png">

**Comment by mrocklin** [comment]
Thank you for the bug report and explanation @pranav-kohli .  

Can you try again with a newer version of Dask and distributed?  The versions that have installed are fairly old.

**Comment by mrocklin** [comment]
Checking in here @pranav-kohli , do you have time to try this with newer versions?

**Comment by pranav-kohli** [comment]
So on debugging a bit further, I found that xgboost library had threading issues, upgrading it seems to solve the problem for now. Sorry for the noise here, Ill close the issue.

**Comment by mrocklin** [comment]
Thanks for the update!
