### ISSUE TITLE
Bag repartition can increase, docstring implies otherwise

### ISSUE THREAD

**Issue by afaulconbridge** [dask/dask#5570]
The original issue https://github.com/dask/dask/issues/1699 solves being able to repartition a bag into more partitions (useful after a flatten() for example).

However, the doc string wasn't updated as part of the PR - it says: "Coalesce bag into fewer partitions."

I would suggest updating it to "Change number of partitions of bag". Happy to do a PR for it.

A similar fix was applied to dataframe for https://github.com/dask/dask/issues/3439

**Comment by mrocklin** [comment]
That would be great.  Thank you Adam
