### ISSUE TITLE
dask.compute() with asynchronous distributed client

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#5580]
dask 2.7.0, distributed 2.7.0

One would expect that, when using an async distributed client, the compute() method of dask collections would return a ``distributed.Future`` or a coroutine. Instead, it crashes:

```python
client = await distributed.Client(asynchronous=True)
delayed(1).compute()
```
Output:
```
site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

site-packages/dask/base.py in compute(*args, **kwargs)
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
    436     results = schedule(dsk, keys, **kwargs)
--> 437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 
    439 

TypeError: zip argument #1 must support iteration
```
Same error for ``dask.compute()``. Only ``client.compute([delayed(1)])[0]`` works.

This issue effectively nullifies the benefit of having a globally-registered client.

**Comment by mrocklin** [comment]
> One would expect that, when using an async distributed client, the compute() method of dask collections would return a distributed.Future or a coroutine. Instead, it crashes:

I definitely agree.  If you can find a nice way of acheiving that while keeping everything simple that would be great.

> This issue effectively nullifies the benefit of having a globally-registered client.

That seems like too extreme of a statement to me.  There are many benefits to having a globally-registered client beyond this case.

**Comment by jrbourbeau** [comment]
This has been brought up before in #5518. Closing this issue as a duplicate
