### ISSUE TITLE
dask_key_name="foo"

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#5582]
dask 2.7.0.

Ok, this is weird.
If one invokes a delayed function with dask_key_name *exactly* equal to "foo", and then it computes it without explicitly setting the scheduler, it returns the wrapped function instead of the function output O_O

```python
>>> from dask import delayed
>>> f = delayed(lambda: 1)
>>> d1 = f(dask_key_name="bar")
>>> d2 = f(dask_key_name="foo")
>>> d1.compute()
1
>>> d2.compute()
<function __main__.f()>
>>> d2.compute(scheduler=d2.__dask_scheduler__)
1
```

**Comment by mrocklin** [comment]
Interesting!  Any interest in tracking this down?

**Comment by crusaderky** [comment]
Interest, plenty. Time, ehrm... 😢

**Comment by crusaderky** [comment]
I'm an idiot.
The issue was that I was connecting to a distributed cluster where, several hours before, I persisted (and never cleaned up) an object with key="foo".
