### ISSUE TITLE
[BUG] IndexError raised by read_parquet when AccessDenied by S3

### ISSUE THREAD

**Issue by tomorrowleadcrunch** [dask/dask#5592]
Start a python interpreter without AWS credentials in the environment.

```
import dask.dataframe as dd

ddf = dd.read_parquet('s3://some-bucket/some-key/*.parquet')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-15-d837a927cc1f> in <module>
      1 import dask.dataframe as dd
      2 
----> 3 ddf = dd.read_parquet('s3://leadcrunch-data-science/firth/embeddings/test-2019-08-01/*.parquet')

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, **kwargs)
    214         filters=filters,
    215         split_row_groups=split_row_groups,
--> 216         **kwargs
    217     )
    218     if meta.index.name is not None:

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, **kwargs)
    181         # correspond to a row group (populated below).
    182         parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
--> 183             fs, paths, gather_statistics, **kwargs
    184         )
    185 

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in _determine_pf_parts(fs, paths, gather_statistics, **kwargs)
    119                 parts = paths.copy()
    120     else:
--> 121         if fs.isdir(paths[0]):
    122             # This is a directory, check for _metadata, then _common_metadata
    123             paths = fs.glob(paths[0] + fs.sep + "*")

IndexError: list index out of range
```

```
import dask
dask.__version__
'2.7.0'
```

I would expect dask to raise a `PermissionError` like pandas does when S3 (botocore) raises a `ClientError`.

I hope this issue is helpful. Please let me know if you need any more details. Happy to contribute a solution if help is needed.

Thanks for maintaining such an awesome project! 😄

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @tomorrowleadcrunch! What version of `fsspec` and `fastparquet` are you using?

**Comment by tomorrowleadcrunch** [comment]
Here are the current versions of `fsspec` and `fastparquet` I have:

```
fastparquet==0.3.2
fsspec==0.5.2
pyarrow==0.15.1
```

Thanks for the quick reply @jrbourbeau!

**Comment by jrbourbeau** [comment]
Sorry, I should have asked for the `s3fs` version too. Both `s3fs` and `fsspec` published new releases today that fixed several issues. Could you try updating to the latest release for those packages (`fsspec==0.6.0` and `s3fs==0.4.0`) and seeing if the problem still persists?

**Comment by tomorrowleadcrunch** [comment]
No worries @jrbourbeau! I wasn't aware of those new releases. I just installed them and tried again with no luck unfortunately. Here's an updated snippet:

```
import s3fs
import fsspec

print(f's3fs=={s3fs.__version__}')
print(f'fsspec=={fsspec.__version__}')
```
```
s3fs==0.4.0
fsspec==0.6.0
```
```
ddf = dd.read_parquet('s3://some-bucket/some-key/*.parquet')
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-4fa892e0b47e> in <module>
----> 1 ddf = dd.read_parquet('s3://some-bucket/some-key/*.parquet')

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, **kwargs)
    214         filters=filters,
    215         split_row_groups=split_row_groups,
--> 216         **kwargs
    217     )
    218     if meta.index.name is not None:

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, **kwargs)
    181         # correspond to a row group (populated below).
    182         parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
--> 183             fs, paths, gather_statistics, **kwargs
    184         )
    185 

/opt/conda/envs/dask-client/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in _determine_pf_parts(fs, paths, gather_statistics, **kwargs)
    119                 parts = paths.copy()
    120     else:
--> 121         if fs.isdir(paths[0]):
    122             # This is a directory, check for _metadata, then _common_metadata
    123             paths = fs.glob(paths[0] + fs.sep + "*")

IndexError: list index out of range
```

Thanks again, for the quick replies.

**Comment by jrbourbeau** [comment]
This is due to `fsspec` catching `IOError`s when `walk`ing a filesystem:

https://github.com/intake/filesystem_spec/blob/9459fffc543e85a4b52c7aeb71499a669cfe920c/fsspec/spec.py#L325-L328

which (I think) is in line with how `os.walk` behaves

https://github.com/python/cpython/blob/4d231bcc77ac8ce7d11bda0804130dcdd678f710/Lib/os.py#L342-L346

I agree this error raised here could be improved. @TomAugspurger @martindurant do you have any thoughts on if this should be handled in `fsspec.AbstractFileSystem` level or if we should try to improve things in `s3fs`?

**Comment by TomAugspurger** [comment]
I'm not sure, but I think that `fsspec.get_fs_token_paths('s3://some-bucket/some-key/*.parquet')` should raise back up with an error (not sure what kind, ideally some kind of permissions error, but may have to be a FileNotFound error).

**Comment by TomAugspurger** [comment]
The following diff to fsspec fixes things

```diff
diff --git a/fsspec/spec.py b/fsspec/spec.py
index 71ca27d..31408f8 100644
--- a/fsspec/spec.py
+++ b/fsspec/spec.py
@@ -325,6 +325,8 @@ class AbstractFileSystem(up, metaclass=_Cached):
 
         try:
             listing = self.ls(path, detail=True, **kwargs)
+        except PermissionError:
+            raise
         except (FileNotFoundError, IOError):
             return [], [], []
 
```

I was a bit surprised that PermissionsError is a subclass of IOError. @martindurant does re-raising for PermissionsError make sense to you?

**Comment by martindurant** [comment]
Yes and no...
I can imagine a user wanting to know if some paths were unaccessible, but I can also imagine the general case where "path/*" means "all the things in path that I *can* see".
Would a warning be appropriate?

**Comment by TomAugspurger** [comment]
Mmm, that's tricky.

I guess on a linux file system, `ls` means just the paths I can see, right? So that's probably the model we should follow in `ls`...

**Comment by martindurant** [comment]
> ls means just the paths I can see

Roughly... you might be able to see the name of a dir but not its contents. I'm not sure how granular you can make permissions within a bucket, but I thought that you only see a prefix if there's a file within that you can see.

**Comment by jsignell** [comment]
I am going to close this since it seems like the behavior while possibly confusing is definitely intentional. If you have a suggestion for an improvement I suggest you bring it up on fsspec.
