### ISSUE TITLE
tensordot and maximum number dimensions

### ISSUE THREAD

**Issue by jcmgray** [dask/dask#5595]
Dask currently cannot handle more than 32 dimensions, which I believe is fairly intrinsically tied to how many dimensions [numpy can handle](https://github.com/numpy/numpy/issues/5744) (and it looks like one could indeed recompile numpy with a higher limit). I guess the first part of this issue is how feasible it would be to lift this. For the kind of things I have in mind the actual array chunks would not have to have ndim>32 if kept in 'squeezed' form, i.e., with chunksize 1 for several dimensions. While the 32 limit makes sense for in-core numpy, it's exactly the kinda realm where dask might be able to extend things!

The second, and more immediately practical issue, is that dask's tensordot cannot handle the case where more than 32 dimensions are just *involved*, even if the input and output tensors are smaller. Reproducer:

```python3
import dask.array as da
n = 11
x = da.random.uniform(size=[2]* (2 * n))
y = da.random.uniform(size=[2]* (2 * n))
da.tensordot(x, y, n)
```
```error
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/conda/lib/python3.7/site-packages/dask/array/utils.py in meta_from_array(x, ndim, dtype)
     90             if ndim > x.ndim:
---> 91                 meta = meta[(Ellipsis,) + tuple(None for _ in range(ndim - meta.ndim))]
     92                 meta = meta[tuple(slice(0, 0, None) for _ in range(meta.ndim))]

IndexError: invalid index to scalar variable.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-835761020f24> in <module>
----> 1 da.tensordot(x, y, n)

~/conda/lib/python3.7/site-packages/dask/array/routines.py in tensordot(lhs, rhs, axes)
    268         right_index,
    269         dtype=dt,
--> 270         axes=(left_axes, right_axes),
    271     )
    272 

~/conda/lib/python3.7/site-packages/dask/array/blockwise.py in blockwise(func, out_ind, name, token, dtype, adjust_chunks, new_axes, align_arrays, concatenate, meta, *args, **kwargs)
    235         return Array(graph, out, chunks, meta=meta)
    236     else:
--> 237         return Array(graph, out, chunks, dtype=dtype)
    238 
    239 

~/conda/lib/python3.7/site-packages/dask/array/core.py in __new__(cls, dask, name, chunks, dtype, meta, shape)
   1030             raise ValueError(CHUNKS_NONE_ERROR_MESSAGE)
   1031 
-> 1032         self._meta = meta_from_array(meta, ndim=self.ndim, dtype=dtype)
   1033 
   1034         for plugin in config.get("array_plugins", ()):

~/conda/lib/python3.7/site-packages/dask/array/utils.py in meta_from_array(x, ndim, dtype)
     96                 meta = meta.reshape((0,) * ndim)
     97     except Exception:
---> 98         meta = np.empty((0,) * ndim, dtype=dtype or x.dtype)
     99 
    100     if np.isscalar(meta):

ValueError: maximum supported dimension for an ndarray is 32, found 33
```
Here we have the 11 indices ``x`` keeps, the 11 that ``y`` keeps, and then the 11 that are 'shared'/contracted, adding up to 33 total.

This reason seems to be because dask currently explicitly creates an intermediate array here: 
https://github.com/dask/dask/blob/94c6b16581828c3fb6c31f1af6d795e7cb02f54c/dask/array/routines.py#L263
before sum reducing the shared/contracted indices. However you can see that If the dimensions are size 2 then a contraction that breaks this is still only equivalent to multiplying two d=2048 matrices so fairly small scale. Is there a way for dask to do the tensordot without the intermediate?

**Comment by mrocklin** [comment]
> Is there a way for dask to do the tensordot without the intermediate?

Perhaps.  It sounds actually like you have a decent grasp on the situation (probably as good as anyone today).  If this is something that you want to pursue then please do.

> Dask currently cannot handle more than 32 dimensions, which I believe is fairly intrinsically tied to how many dimensions numpy can handle (and it looks like one could indeed recompile numpy with a higher limit).

Dask array doesn't intentionally add any additional limits.  It just uses Numpy.  You might consider raising this issue upstream with Numpy to see if this default can be changed.

**Comment by jcmgray** [comment]
> Perhaps. It sounds actually like you have a decent grasp on the situation (probably as good as anyone today). If this is something that you want to pursue then please do.

I'd be interested, just need to wrap my head around how this ``blockwise`` function works I suspect.

**Comment by mrocklin** [comment]
> just need to wrap my head around how this blockwise function works I suspect

Blockwise is a powerful and complex component of dask array.  It's a very useful thing to understand, but also somewhat difficult.  I fully encourage you to jump in, but also don't be discouraged if you don't understand it immediately :)

**Comment by jsignell** [comment]
I'm going to close this since work is not ongoing and there is no plan to work on this feature. @jcmgray please reopen if that changes!
