### ISSUE TITLE
[FEA] Support writing Dask DataFrame as ORC files

### ISSUE THREAD

**Issue by randerzander** [dask/dask#5596]
Reading ORC files into Dask DataFrames with `read_orc` works well, but I need to do some data processing and save the results as new ORC files. Would Dask be willing to support a Dask DataFrame `to_orc` method?

**Comment by mrocklin** [comment]
Certainly a `to_orc` method is well in scope. 

On the CPU side do we know if Arrow has an ORC writer?  cc @jcrist 

Ideally I would like to see us repeat the engine system that we have for Parquet, which seems to be working out well.  Now that the design is formalized hopefully it wouldn't be too difficult to repeat this experiment, although it's probably still a week or more of solid effort to get things running cleanly.  Presumably it would be nice to build out a super-simple to_orc function to start just to get something out there.

**Comment by jcrist** [comment]
> On the CPU side do we know if Arrow has an ORC writer?

It does not at this moment. `liborc` (the c++ library arrow wraps) has a rudimentary writer, but when I wrote the reader I ignored it since it lacked many common features. Things may be better now.

**Comment by mrocklin** [comment]
Do we know if a decent C/C++/Python ORC writer exists today?

**Comment by jcrist** [comment]
A quick google search only turns up the one in https://github.com/apache/orc (same mentioned above). This one does work, it just doesn't support the full ORC spec. Since pyarrow is already using it for the reader, this would make the most sense. If someone wanted to wrap the writer and add it to pyarrow, I'm sure Wes and team would be appreciative. I personally have no bandwidth/plans to do this.

**Comment by mrocklin** [comment]
>  I personally have no bandwidth/plans to do this.

Yeah.  No expectations.  My thought is that @rjzamora would probably be a good person to look into this at some point in the near-to-moderate future.  Rick, when you have a moment (after merge stuff) can I ask you to take a look at the Arrow/ORC code and estimate the time to ...

1.  Provide Python hooks in Arrow
2.  Wrap around those hooks in Dask Dataframe in a naive/simple way (like one file per partition, no metadata)
3.  Provide a more fully featured solution, similar in scope to what we have for parquet

**Comment by rjzamora** [comment]
> Rick, when you have a moment (after merge stuff) can I ask you to take a look at the Arrow/ORC code and estimate the time to ...

> 1. Provide Python hooks in Arrow
> 2. Wrap around those hooks in Dask Dataframe in a naive/simple way (like one file per partition, no metadata)
> 3. Provide a more fully featured solution, similar in scope to what we have for parquet

This sounds good to me.

@randerzander - Given that it will take time to both add wrappers in pyarrow and to implement solution in dask,  would you be interested in a temporary/simple cudf-specific implementation in dask_cudf?

**Comment by randerzander** [comment]
I certainly would, yes.

**Comment by kkraus14** [comment]
cc @jreback for viz here as well given the recent PR for orc reading in Pandas. If an orc writer gets exposed nicely via PyArrow should be straightforward to integrate as well.

**Comment by voycey** [comment]
Just a +1 here - this would be amazing and something that would mean I can start using Rapids immediately as our whole workflow is based on ORC
0.11 is looking like a great release already - a dask solution for this would mean I can hopefully do away with clusters for conversions!

**Comment by TangPere** [comment]
May I know any update for to_orc?

**Comment by quasiben** [comment]
@TangPere as far as I know there is still no orc writer in Pandas/PyArrow.  There is however orc reading/writing in cuDF/dask-cudf.

**Comment by rjzamora** [comment]
> @TangPere as far as I know there is still no orc writer in Pandas/PyArrow. There is however orc reading/writing in cuDF/dask-cudf.

Right - I believe the practical blocker here is the desire for either a pyarrow or pandas (or both) `to_orc` API.  I doubt that I will have much time in the near future to tackle that.  However, if someone else does, I can certainly help move things along on the dask front.

**Comment by mrocklin** [comment]
Is there an Arrow issue about this?  If not, @TangPere that's probably
something constructive that you could help with.

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-3014

From a purely governance oriented point of view it would be valuable to have fully viable ORC support in a community-led project.

**Comment by jorisvandenbossche** [comment]
FYI the latest pyarrow version 4.0.0 now includes basic support for writing ORC files.

**Comment by jrbourbeau** [comment]
I believe this was closed by https://github.com/dask/dask/pull/7756 where `dask.dataframe.to_orc` was added
