### ISSUE TITLE
large objects passed and loaded 

### ISSUE THREAD

**Issue by kwunlyou** [dask/dask#5599]
I have a use case
- a large string object has to be passed to the function `_foo` which is applied for each row of a dataframe
- in the function `_foo`, a trained model is load and predict on the passed text data

The illustration is as follows
```python
import random
import string
import time

from dask.distributed import LocalCluster, Client
import dask.dataframe as dd
import pandas as pd

fake_text = ''.join([random.choice(string.ascii_lowercase) for i in range(2000)])
df = pd.DataFrame(data=(fake_text for i in range(120000)), columns=['text'])

def _foo(text):
    # time.sleep(0.01)
    for i in range (1000000):
        _ = i
    return True

def foo(df):
    return [_foo(x) for x in df]

client = Client(LocalCluster(ip='0.0.0.0'))
ddf = dd.from_pandas(df['text'], npartitions=16)
start = time.time()
res = ddf.map_partitions(foo).compute()
print(time.time()-start)
client.shutdown()
```

my question is for such use case
- is this the proper way to parallelize using dask?
- is there a better way to improve/optimize I/O
- the function `_foo` is also very big because in my real case a big trained model also is loaded in `_foo`, for such a problem, is `map_partition` a right choice?

**Comment by mrocklin** [comment]
Hi @kwunlyou .  There are a variety of ways to use Dask.  The way that you've laid out here could work, but it's not clear that you need dask dataframes here.  In your case you might also look at dask bag or futures. I recommend that you look at the following documentation:

-  https://examples.dask.org/applications/embarrassingly-parallel.html
-  https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-repeatedly-putting-large-inputs-into-delayed-calls

**Comment by kwunlyou** [comment]
@mrocklin thank you for the response. 

Dataframe is used because
- the input data is in parquet files and dataframe APIs has IO functions for parquet
- this is only a part of the whole job. we also need those dataframe convenient APIs to process/analyze data
