### ISSUE TITLE
Memory issue when numpy arrays are passed to dask arrays

### ISSUE THREAD

**Issue by PyDataBlog** [dask/dask#5601]
I have a 68gb ram cluster running which runs into memory issues (which kills the worker) only when Numpy arrays are passed to Dask arrays.

![image](https://user-images.githubusercontent.com/29863388/69137246-a6652f80-0abc-11ea-80ab-ef3f15789f6f.png)

 Dask array reproducible example:

```py
import dask.array as da
import numpy as np
from dask.distributed import Client


client = Client()

x = da.random.uniform(low=0, high=10, size=(112_266_893, 15))
x.std(axis=0).compute()  # works just fine

```

However, I am trying to pass a numpy array (representing my feature matrix with the same size as the simulated dask array. I ran into memory issues when I pass the numpy array to dask array.

Numpy array reproducible example:

```py
test_np = np.random.uniform(low=0, high=10, size=(112_266_893, 15))
test_da = da.from_array(test_np)

test_da.mean(axis=0).compute()  # fails after worker gets killed
```

![image](https://user-images.githubusercontent.com/29863388/69137877-e5e04b80-0abd-11ea-9227-26726fbf1bb3.png)

My question is why does dask array compute work in the former but fail in the latter?

Here's the console output where dask seems to be reporting a potential memory leak from this example:

![image](https://user-images.githubusercontent.com/29863388/69137775-b3365300-0abd-11ea-8537-a1ec299e2c74.png)
 

Am I doing something wrong, or do I just need more ram?

**Comment by mrocklin** [comment]
Maybe your numpy array is to large to safely put on a single worker?  When
you use Dask arrays they are broken up into many small pieces so that you
can solve larger problems than you have ram.  When you use numpy, numpy
allocates a single array which has to fit in ram.

See https://docs.dask.org/en/latest/best-practices.html#load-data-with-dask

**Comment by TomAugspurger** [comment]
@PyDataBlog you gave a thumbs up. Does that mean Matt's comment and the docs explain things adequately?

**Comment by d-v-b** [comment]
This looks like it is the same problem I reported over in distributed: https://github.com/dask/distributed/issues/3032.

If you call `da.from_array(numpy_array)`, regardless of the chunking of the dask array, any computation of any chunk will require the full array (as opposed to only requiring a chunk). For big arrays, this easily blows up a single worker.

So, If you actually want the numpy array to be divided into chunks, you should slice your array into sub-arrays and concatenate / stack them together using something like `da.stack([da.from_array(sub_array) for sub_array in sliced_numpy_array])`

**Comment by PyDataBlog** [comment]
@TomAugspurger I will try the suggestion from @d-v-b and report as well. 

@d-v-b how can I make  `sliced_numpy_array` chunk generator.

**Comment by d-v-b** [comment]
@PyDataBlog something like this:
```python
test_np = np.random.uniform(size=(112_266_893,15))
# window size
ws = 10000
# divide test_np into sub-arrays via simple slicing along the first dimension
sliced = [da.from_array(test_np[slice(ind * ws, (ind * ws) + ws )]) for ind in range(1 + test_np.shape[0]//ws)]
x = da.concatenate(sliced)
```
If you construct `x` like this, then the memory footprint of a single chunk should be `(ws, 15)` times the datatype. Whereas if you construct `x` just using `da.from_array(test_np)`, the memory footprint of a single chunk is the entire array.

**Comment by d-v-b** [comment]
@PyDataBlog did my suggestion work for you?

**Comment by PyDataBlog** [comment]
> @PyDataBlog did my suggestion work for you?

The client is now able to process that same test_np array object that it was failing earlier so that should solve the main task since they have the same shape and size. Feel free to close the issue.

**Comment by jakirkham** [comment]
It's worth noting [`da.from_array(...)`]( https://docs.dask.org/en/latest/array-api.html#dask.array.from_array ) accepts a `chunks` argument as well
