### ISSUE TITLE
Dask.Array to support cupy.sparse arrays

### ISSUE THREAD

**Issue by cjnolet** [dask/dask#5604]
While attempting to demonstrate the use of `cupy.sparse` arrays underneath `Dask.Array`, I found that `cupy.sparse` doesn't yet have `vstack` or `hstack` functions for concatenating sparse arrays. I have filed issue [1] with the cupy project. 

Once this has been implemented, the corresponding concatenate function will need to be registered within Dask. I adapted the following code block from the `scipy.sparse` `concatenate_lookup` function.

```Python
@concatenate_lookup.register_lazy("cupyx")
def register_cupyx():
    import cupyx 
    import cupy

    def _concat_cupy_sparse(L, axis=0):
        if axis == 0:
            return cupy.sparse.vstack(L)
        elif axis == 1:
            return cupy.sparse.hstack(L)
        else:
            msg = (
                "Can only concatenate cupy sparse matrices for axis in "
                "{0, 1}.  Got %s" % axis
            )
            raise ValueError(msg)

    concatenate_lookup.register(cupyx.scipy.sparse.spmatrix, _concat_cupy_sparse)
```

[1] https://github.com/cupy/cupy/issues/2655

**Comment by mrocklin** [comment]
This also came up recently in https://github.com/theislab/scanpy/issues/921

**Comment by mrocklin** [comment]
I noticed that you volunteered to help resolve this on the cupy side.  Thanks @cjnolet .  I'm looking forward to seeing this work.  It's nice seeing all of the Numpy implementations converge a bit.  (cc @stefanv )

**Comment by jakirkham** [comment]
This is being attempted in PR ( https://github.com/dask/dask/pull/5735 ).
