### ISSUE TITLE
[FEA] Dask CuPy Array -> Dask CuDF DataFrame

### ISSUE THREAD

**Issue by quasiben** [dask/dask#5606]
In dask, we can create a dataframe from a dask array like the following:

> dd.from_dask_array(da.random.random(n_rows))

In the above, random numpy data is generated then transformed to a Pandas dataframe.  It would be really cool if I could do something similar with CuPy arrays -> CuDF DataFrames:

```python
import cupy
import dask.array as da
import dask.dataframe as dd

rs = da.random.RandomState(RandomState=cupy.random.RandomState)
dd.from_dask_array(rs.random(n_rows))
```

Maybe in `from_dask_array` we could detect if the obj implemented the `__cuda_array_interface__` and proceed accordingly ?

**Comment by mrocklin** [comment]
I suspect that `x.map_blocks(cudf.Series)` will work ok and that you don't need the special `from_dask_array` function.

**Comment by quasiben** [comment]
I need to do a bit more than that -- though not much:

```python
x = rs.random(10, chunks=(5,))
sr_x = dd.from_dask_array(x.map_blocks(cudf.Series, meta=make_meta(cudf.Series())), columns='x')

y = rs.randint(10, size=(10,), chunks=(5,))
sr_y = dd.from_dask_array(y.map_blocks(cudf.Series, meta=make_meta(cudf.Series(1))), columns='y')

dd.concat([sr_x, sr_y], axis=1)
```

What are your thoughts about usability of the above ?  Could this be simplified ?

**Comment by mrocklin** [comment]
> I suspect that x.map_blocks(cudf.Series) will work ok and that you don't need the special from_dask_array function.

What stops this from working?  If it's easy I'd rather fix this than work around it.

**Comment by quasiben** [comment]
Hmm, looking at this again i think above is incorrect -- the `from_dask_array` is still going to cast the data to a pd.Series.  So I'm not sure how the dask array object can get wrapped into a Dask Dataframe object

```
In [36]: x.map_blocks(cudf.Series, meta=make_meta(cudf.Series()))
Out[36]: dask.array<Series, shape=(100000, 100000), dtype=float64, chunksize=(1000, 1000), chunktype=numpy.ndarray>
```

**Comment by quasiben** [comment]
> What stops this from working? If it's easy I'd rather fix this than work around it.

dtype issues:

```
ValueError: `dtype` inference failed in `map_blocks`.

Please specify the dtype explicitly using the `dtype` kwarg.

Original error is below:
------------------------
BufferSentryError('ndim mismatch')

Traceback:
---------
  File "/datasets/bzaitlen/GitRepos/dask/dask/array/core.py", line 350, in apply_infer_dtype
    o = func(*args, **kwargs)
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/series.py", line 124, in __init__
    data, nan_as_null=nan_as_null, dtype=dtype, name=name
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/column/column.py", line 1226, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/column/column.py", line 1169, in as_column
    data = as_column(Buffer(arbitrary))
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/buffer.py", line 44, in __init__
    _BufferSentry(self.mem).ndim(1)
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/buffer.py", line 213, in ndim
    raise BufferSentryError("ndim mismatch")
```

**Comment by mrocklin** [comment]
OK, for dask dataframe we use this

https://github.com/dask/dask/blob/0805d391718c1efc6f4730b90407fde8e32a2bd8/dask/dataframe/core.py#L5864-L5888

Which allows map_partitions calls that change the underlying meta type to return other kinds of Dask collections.  It looks like we don't currently do this for Dask array.  I can take a look at this starting next week.

@quasiben to unblock you I would recommend making a function that creates a single cudf dataframe and then using that function multiple times with dask.delayed

```python
def make_random_dataframe(n: int) -> cudf.DataFrame:
    return cudf.DataFrame({...: cupy.random.random})
    ...

partitions = [dask.delayed(make_random_dataframe, pure=False)(10000000) for _ in range(npartitions]
df = dd.from_delayed(partitions)
```
