### ISSUE TITLE
Feature Request: TFRecord file format support

### ISSUE THREAD

**Issue by eggie5** [dask/dask#5618]
I've had much success w/ this TFRecord plugin for spark. 

https://github.com/tensorflow/ecosystem/tree/master/spark/spark-tensorflow-connector

You can build your dataset using the DataFrame API and then save to disk in TFRecord format (Example protos) for fast io during TF training. 

I've been migrating my spark workflows to Dask, and thought I would see if this is on anyone's radar?

**Comment by TomAugspurger** [comment]
I'm not aware of anyone doing this yet.

If you were using just pandas, how would you write a DataFrame as a TFRecord?

**Comment by eggie5** [comment]
Each column of the pandas DF would map to a `Feature` in the `Example` proto. The `Example` protos are then written to disk in the tfrecords container format.

**Comment by TomAugspurger** [comment]
Can you provide an example? I suspect this is doable with `dask.delayed`, but I've never used TFRecord before.

**Comment by TomAugspurger** [comment]
@eggie5 can you provide an example using just pandas?

**Comment by eggie5** [comment]
@TomAugspurger 

Not sure how to implement this in pandas, but w/ spark which has a DataFrame API, you can do it like this:

```
def tensorflow_writer(basedir, options):
    """Closure to help build tensorflow writer for rdd.foreach lambda"""
    
    def _writer(group, iterator):
        """writes protos to tfrecords"""
        filename = "%s/%s/ltr_dataset.tfrecord"%(basedir, group)

        with tf.python_io.TFRecordWriter(filename, options=options) as writer:
            for proto in iterator:
                writer.write(proto)

        
    return foreach_writer
```


```
writer = tensorflow_writer(base_dir, options)

protos.mapPartitionsWithIndex(writer).collect()
```

**Comment by TomAugspurger** [comment]
It'd be quite similar with dask.dataframe. I think the main limitation is that we don't currently pass through any group / partition info to the user-defined function (`_writer`) passed to `map_partitions`.


```
import pandas as pd
import tensorflow as tf
import dask.dataframe as dd
import tempfile
import numpy as np

df = pd.DataFrame(np.random.randn(100, 10), columns=list('abcdefghij'))
y = df.a > 0
df.head()


def write(df):
    with tempfile.NamedTemporaryFile() as f:
        writer = tf.python_io.TFRecordWriter(f.name)

        for i in range(len(df)):
            label = y.iloc[i]
            features = list(df.iloc[i])
            feature = {
                "train/label": tf.train.Feature(int64_list=tf.train.Int64List(value=[label])),
                "train/image": tf.train.Feature(float_list=tf.train.FloatList(value=features))
            }
            example = tf.train.Example(features=tf.train.Features(feature=feature))
            writer.write(example.SerializeToString())
            
    return f.name
```

```
>>> write(df)
'/var/folders/hz/f43khqfn7b1b1g8z_z6y3bsw0000gp/T/tmpboi8_8_q'

>>> filenames = ddf.map_partitions(write)
>>> filenames
Dask Series Structure:
npartitions=2
0     object
50       ...
99       ...
dtype: object
Dask Name: write, 4 tasks
```

Closing as this seems to be resolved, but LMK if not.

**Comment by TomAugspurger** [comment]
Oh, and since I didn't explicitly state it, I think that writing to TFRecord is out of scope for dask.dataframe (though others may disagree). But hopefully that snippet helps.

**Comment by mrocklin** [comment]
I think that this is something that we would defer to the Pandas community
to implement first.  Alex, I would encourage you to engage there.  Once
Pandas implements a TFRecord reader/writer it will be easy to add it to
Dask.  If they choose not to implement such a reader/writer then this
functionality should probably go in an external package.

**Comment by eggie5** [comment]
Ah, I understand better know. I guess why I posted the request here first, is that I was confused b/c spark owns the underlying serialization layer whereas Dask simply defers to Pandas.

I'll explore this w/ the Pandas community.

**Comment by tgalery** [comment]
Hi there, I'm insterested in this as well, and it seems that there's this project for pandas https://pypi.org/project/pandas-tfrecords/

**Comment by TomAugspurger** [comment]
Thanks @tgalery. For reference, there's some discussions on making pandas' IO pluggable: https://github.com/pandas-dev/pandas/issues/26804. But there isn't consensus on how to proceed.
