### ISSUE TITLE
documentation of corr method

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#5622]
Documentation of `corr` method (added in #5296) seems to be copied from pandas. It make sense to write dask documentation for this method. Current method description and current examples are pandas specific.
https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.Series.corr

**Comment by TomAugspurger** [comment]
Is this different from https://github.com/dask/dask/issues/1815?

**Comment by jangorecki** [comment]
Yes, this issue asks for a correlation documentation rather than documentation in general. It is useful (for me) to have it, so I can be notified when it (correlation doc) is done.

**Comment by TomAugspurger** [comment]
Mmm, OK. I'm not sure we'll want an issue per method though, but will wait
for feeback from others.

**Comment by mrocklin** [comment]
I agree that raising an issue for every method is probably too much
administrative overhead on maintainers.  I suggest that we close this.  My
apologies to Jan for the inconvenience.

**Comment by TomAugspurger** [comment]
Thanks Jan. I'll try to remember to ping you if there's movement on these
docstrings.

**Comment by jangorecki** [comment]
Could we re-open this issue? Linked issue has been closed but according to latest published documentation this issue is still not yet resolved.

**Comment by jsignell** [comment]
Yes let's reopen this and add some labels to help people find it. Thanks for pinging :)

**Comment by jsignell** [comment]
Just to confirm, @jangorecki there is a disclaimer: 

> This docstring was copied from pandas.core.series.Series.corr.
Some inconsistencies with the Dask version may exist.

and the kwargs are the correct ones for dask. Are you suggesting that the whole docstring should be rewritten?

**Comment by jangorecki** [comment]
@jsignell If documentation is updated for dask, then it should not be rewritten, but the information about inconsistencies should be removed. Users reading this manual entry now might be wondering if they can rely on information found there. If something is not documented one should not expect that to be supported, and even if it is supported at the present moment, it might change without notice or even entry in changelog.
If documentation is not updated for dask, then maybe could be rewritten, but that probably depends what will be easier.

**Comment by jsignell** [comment]
Ok I am going to close this again. It's not feasible for dask to re-write many docstrings, so we have to rely on copying the ones from pandas and numpy and adding a generic disclaimer. If you have a section that you think should be added to the `corr` method, please open a pull request to add that.
