### ISSUE TITLE
Dask Array map_blocks is slower than sequential code when using FastText ML model

### ISSUE THREAD

**Issue by ARDivekar** [dask/dask#5625]
Hi,

I am new to Dask, so this might be my fault for using the wrong function/configuration, but am not quite sure how to set up Dask to parallelize my model prediction.

Essentially, I have a Python list containing text sentences. At the moment I have 25k sentences (a few MB), but in the future, I expect this to grow to 10MM+ sentences.

I have a pretrained [FastText ML model](https://fasttext.cc/) which I want to use to predict on these sentences. The model is about 500 MB.

When running on a single-machine (using LocalCluster) here are my results:

1. Setting up the LocalCluster client:
```py
import dask.array as DaskArray
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(n_workers=5, processes=False)
client = Client(cluster)  # Ref: https://docs.dask.org/en/latest/setup/single-distributed.html
print(client)    # <Client: 'inproc://192.168.1.19/88079/1' processes=5 threads=10, memory=17.18 GB>
```

(As an addendum, is processes=False being ignored?)

2. My data:
```
print(type(input_data))   # list of strings
print(len(input_data))    # 25000
```

3. Prediction using the normal fasttext module, no Dask:

```py
import fasttext
import numpy as np
model = fasttext.load_model(model_path)   # Takes 1.08s
np.array(model.predict(input_data, k=100, threshold=0.0))    # Takes 19.1 sec
```

4. Predictions using Dask Array:

```py
import dask.array as DaskArray
da_input_data = DaskArray.from_array(input_data, chunks=(5_000,))
print(da_input_data)    # dask.array<array, shape=(25000,), dtype=<U506, chunksize=(5000,), chunktype=numpy.ndarray>

def predict_on_sentences(sentences):
    model_path = 'some/path'
    model = fasttext.load_model(model_path)
    labels, scores = model.predict(list(sentences), threshold=0.0, k=10)
    del model
    return np.array([labels, scores])

da_input_data.map_blocks(predict_on_sentences).compute()    # Takes 30.1 sec
```

Seems that predicting on 25k senteces without Dask takes 19.2, whereas with Dask it takes 30.1s. 

The problem persists as I increase the amount of data:

Number of sentences | Without Dask | With Dask Array map_blocks
--- | --- | --- 
25k | 19.1 sec | 30.1 sec
35k | 26.1 sec | 37.9 sec
50k | 38.9 sec | 58.5 sec

I should note that `labels` is a (25_000, 10) ndarray, and so is scores.

Could you please let me know what is happening and how I might avoid it?

**Comment by TomAugspurger** [comment]
`processes=False` is most appropriate for workloads that release the GIL. Do you know if that's the case for your workload? FWIW, if your input data is a list of strings, working with those will hold the GIL. I'm not familiar with fasttext, so I don't know if it converts things to some internal data structure.

As an alternatively, you can use multiple processes, but that will require serializing data between processes.

**Comment by ARDivekar** [comment]
Hi Tom,

Here were my results on 100k sentences, with your suggestion of using `cluster = LocalCluster(n_workers=5, processes=True)`. I tried different chunk sizes as well.

Number of sentences | Without Dask | With Dask Array map_blocks
50k | 41.7 sec | 34.0 sec (chunksize 5,000)
100k | 78.1 sec  | 56.7 sec (chunksize 5,000) , 44.7 (chunksize 10,000), 58.6 (chunksize 20,000)

It seems to me that using processes does beat out the serial solution (optimal is with 10 chunks, using 5 workers and 10 threads), which also beats out the one with threads (i.e. processes > serial > threads).

From my understanding this means the GIL is locked somewhere. Could the Dask Array be the cause? It seems that the list of sentences should be split into blocks of the Dask Array, then mapped to separate workers and processed in parallel when calling `compute()`. Is this not the case?

**Comment by TomAugspurger** [comment]
> If I'm understanding correctly, you're saying that the Dask Array might be holding the GIL?

No, not really. Dask Array is just coordinating things. The bulk of the time is likely spent on the actual execution (in fasttext, or some other library). That's the code that may be using the GIL.

You might want to go through https://docs.dask.org/en/latest/diagnostics-distributed.html and apply those to your problem.

**Comment by TomAugspurger** [comment]
@ARDivekar did https://github.com/dask/dask/issues/5625#issuecomment-558161087 make sense? Anything else to do here?

**Comment by ARDivekar** [comment]
Yes this answered my issue. Also linking to an expanded SO answer [for predicting using multiple models on a LocalCluster](https://stackoverflow.com/a/59015702/4900327) for reference. Thanks and cheers.
