### ISSUE TITLE
Worker memory limit?

### ISSUE THREAD

**Issue by jeffcbecker** [dask/dask#5626]
I'm running on 25 nodes, each with 128G of memory, using dask-mpi. After requesting the nodes from PBS, I do:

```
$ mpirun -np 200 dask-mpi --no-nanny --interface ib0 --nthreads 1 --scheduler-file ./sched.json &
```

So I'm using 8 cores per node. Then in Python I do:

```
jcbecker@r593i2n2 505$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask.distributed import Client
>>> client = Client(memory_limit='8GB',scheduler_file='/home7/jcbecker/dask_mpi/sched.json')
distributed.scheduler - INFO - Receive client connection: Client-10651fd8-0d6d-11ea-9bdc-0cc47a3ff912
distributed.core - INFO - Starting established connection
>>> client
<Client: 'tcp://10.150.53.48:39841' processes=199 threads=199, memory=556.65 GB>
```

Why is memory only 556.65 GB? Since I have 199 workers, and memory_limit='8GB', I thought I would get at least 1TB or more.  Perhaps I'm not understanding the memory_limit argument to Client?

**Comment by mrocklin** [comment]
You need to specify the memory limit when you create your workers, not your
client.  See the `--memory-limit` keyword of dask-mpi

**Comment by jeffcbecker** [comment]
Thanks. That worked.
