### ISSUE TITLE
Silence FutureWarning for empty Series in upcoming pandas version

### ISSUE THREAD

**Issue by SaturnFromTitan** [dask/dask#5630]
In upcoming pandas versions, the default dtype of an empty `Series` will change from `float64` to `object`. [This](https://github.com/pandas-dev/pandas/pull/29405) PR implements a FutureWarning for the next release.

I noticed that [this line](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2058) will raise a FutureWarning that the user can't silence. @jreback suggested opening an issue for that.

**Comment by mrocklin** [comment]
This appears to have been fixed by the attached PR.
