### ISSUE TITLE
How to pass a boto session to dd.read_parquet

### ISSUE THREAD

**Issue by mmccarty** [dask/dask#5632]
[S3fs](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L112) accepts a botocore Session object, however it doesn't seem to be exposed in `dd.read_parquet`.

Passing the session via `storage_options` throws an AttributeError.

```
location = "s3://..."
# get a boto session with my institutional access SDK
boto_session = <institutional access thing>.get_boto_session(location)

df = dd.read_parquet(
    location,
    engine="fastparquet", 
    columns=["id", "feature_x"],
    storage_options={"session": boto_session}
)
df.persist()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.conda/envs/dask-ol/lib/python3.7/site-packages/distributed/protocol/pickle.py in dumps(x)
     37     try:
---> 38         result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
     39         if len(result) < 1000:

AttributeError: Can't pickle local object 'lazy_call.<locals>._handler'
```

I recalled that the parquet IO code was recently re-written. Should the session be handled a different way?

**Comment by mmccarty** [comment]
cc @mdwgrogan

**Comment by TomAugspurger** [comment]
Your usage `storage_options={"session": boto_session}`, looks correct. That would be passed through to s3fs.S3FileSystem on the worker. It just seems that boto3 sessions aren't pickleable

```python
In [32]: session = boto3.session.Session()

In [33]: pickle.dumps(session)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-ec304ee4ccf9> in <module>
----> 1 pickle.dumps(session)

AttributeError: Can't pickle local object 'lazy_call.<locals>._handler'
```

I can raise an issue with boto if you want. In the meantime: why do you need to pass through a `session` in the first place? I wonder if we can avoid it entirely.

**Comment by mmccarty** [comment]
We could just pass the creds like so...
```
df = dd.read_parquet(
    loc,
    engine="fastparquet", 
    columns=["acct_id", "snap_dt"],
    storage_options={
        "key": creds.access_key, 
        "secret": creds.secret_key, 
        "token": creds.token,
    },
)
```
But we would rather not have the need to expose them to the user directly.  The magic institutional access thingy just gives us a boto_session from user-level context baked into the underlying infrastructure.

**Comment by TomAugspurger** [comment]
Gotcha. And using environment variables is not as nice of an option?

I wonder if we can register a custom serializer within distributed to work around this. The object itself is fine with cloudpickle

```python
In [5]: import cloudpickle

In [6]: cloudpickle.dumps(session)
Out[6]: b'\x80\x04\x95\x95f\x00\x00\x00\x00\x00\x00\x8c\rboto3.session\x94\x8c\x07Session\x94\x93\x94)\x81\x94}\x94(\x8c\x08_session\x94\x8c\x10botocore.session\x94h\x01\x93\x94)\x81\x94}\x94(\x8c\x11...
```

However, once we actually do anything with it like

```python
In [11]: s3 = session.client("s3")

In [12]: cloudpickle.dumps(session)
```

We get a long traceback like

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-70612137f216> in <module>
```

ending with

```
/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    522             reduce = getattr(obj, "__reduce_ex__", None)
    523             if reduce is not None:
--> 524                 rv = reduce(self.proto)
    525             else:
    526                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle SSLContext objects
```

Will explore a bit.

**Comment by mmccarty** [comment]
I was wondering about a custom serializer as well. Thanks Tom!

**Comment by mrocklin** [comment]
My guess is that boto maintainers won't want to pass sessions around.  Semantically they're tied to, well, a particular session.

I think that institutionally credentials should probably be handled outside of Dask collections / task graphs, and instead maybe we should think about how to move them around with dask.distributed, dask-gateway, or other institutional infrastructure.

**Comment by TomAugspurger** [comment]
Played around with this a bit, and it's exactly straightforward to write a generic one. I don't know what all state needs to be extracted... Boto doesn't seem interested in supporting this either: https://github.com/boto/botocore/issues/636. 

I see two options:

1. Register your own custom serializer with dask for these session objects. Send through just the bits you need to re-connect on the other side (assuming you can do the special `institutional access thing` on the worker).  One thing to check: will distributed use custom serializers for values in a dictionary? If not that may be a non-starter.
2. Override the lookup for `s3` to point to a custom subclass of `s3fs.S3FileSystem`. Then your subclass' `__init__` could take care of the institutional access thing.

**Comment by mmccarty** [comment]
Excellent, thanks for looking into this @TomAugspurger ! This gives us some options to consider until we have a deployment level solution. 

@mrocklin Would you want to discuss this further in dask-gateway or distributed? I can open an issue there and we can close this one.

**Comment by mrocklin** [comment]
I'll defer that to @jcrist

**Comment by jcrist** [comment]
> The magic institutional access thingy just gives us a boto_session from user-level context baked into the underlying infrastructure.

How is the original boto session being created?

FWIW I agree with Matt that we probably shouldn't mess with serializing boto sessions, and should instead figure out how to make recreating those sessions easier for the end user. The parameters for instantiating them have to come from somewhere.

> maybe we should think about how to move them around with dask.distributed, dask-gateway, or other institutional infrastructure.

Having admin or user defined environment variables is already supported in dask-gateway, but depending on backend they may not use the most secure method of defining them (e.g. in kubernetes we should allow setting environment variables from secrets). If you want to open an issue in the dask-gateway repo we can discuss further there.

**Comment by TomAugspurger** [comment]
It sounds like we'd prefer to handle this outside of dask and distributed. Does that seem reasonable? Anything else to do her @mmccarty?

**Comment by mmccarty** [comment]
Yes, that makes sense. Thanks everyone.
