### ISSUE TITLE
page not found - https://azure-datalake-store.readthedocs.io/

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#5637]
On https://docs.dask.org/en/latest/setup/cloud.html

Clicking on the link at 'adlfs for Microsoft’s ADL` points to:
https://azure-datalake-store.readthedocs.io/
which is not found

Could it be looking for one of these?
https://github.com/dask/adlfs
https://github.com/Azure/azure-data-lake-store-python
https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-data-operations-python

**Comment by jrbourbeau** [comment]
Good catch, thanks for reporting @raybellwaves. I think that should point to https://github.com/dask/adlfs. Any interest in submitting a PR? (no obligation though)

**Comment by raybellwaves** [comment]
Will do shortly

**Comment by jrbourbeau** [comment]
Closed by #5639
