### ISSUE TITLE
build dask docs - can't find packages on main channel

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#5638]
Tried following the commands at:
https://github.com/dask/dask/blob/master/docs/README.rst
got an error saying `dask_sphinx_theme` and `sphinx-click` are not available from the current channel (below).

Need to add conda-forge to the channels for the packages in https://github.com/dask/dask/blob/master/docs/requirements-docs.txt?

https://anaconda.org/conda-forge/dask-sphinx-theme
https://anaconda.org/conda-forge/sphinx-click

```
(base) ray@ray-MS-7B43:~/Documents/PYTHON_dev/dask/docs$ conda create -n daskdocs --file requirements-docs.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - dask_sphinx_theme[version='>=1.1.0']
  - sphinx-click

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jrbourbeau** [comment]
Thank you for raising an issue for this @raybellwaves! I updated the installation instructions over in #5640 which specify to use the `conda-forge` channel (or `pip`). Any comments you may have are appreciated
