### ISSUE TITLE
dask.array.blockwise tries to compute meta even if dtype provided

### ISSUE THREAD

**Issue by smartass101** [dask/dask#5642]
I hit the issue described in https://github.com/pydata/xarray/issues/3574 and I traced it to the fact that `compute_meta` does not play well with `np.vectorize` as mentioned here 

https://github.com/dask/dask/blob/e6ba8f5de1c56afeaed05c39c2384cd473d7c893/dask/array/utils.py#L118

One option would be to supply `meta` directly form `xarray.apply_ufunc`, but perhaps it would make more sense to bypass `compute_meta` if `dtype` is provided which is hinted at here

https://github.com/dask/dask/blob/3960c6518318f2417658c2fc47cd5b5ece726f8b/dask/array/blockwise.py#L237

but is unlikely to be triggered because of the `compute_meta` being run whenever `meta is None` above.

**Comment by mrocklin** [comment]
Hi @smartass101 , I apologize that no one was able to respond to you before.  Thank you for tracking this down.  It sounds like you have a concise solution proposed.  It would probably be easier for people to see and respond to it if you were to submit a PR.

**Comment by jsignell** [comment]
I ran the MRE in the related PR and wasn't able to reproduce the issue. I'm going to close this but please reopen if you run into it again!
