### ISSUE TITLE
read_parquet fails with Decimal data types

### ISSUE THREAD

**Issue by maxfirman** [dask/dask#5647]
### Reproducible example

```python
    from decimal import Decimal
    import pandas as pd
    import dask.dataframe as dd
    import pyarrow as pa
    import random
    import shutil

    NUM_DATA_POINTS_PER_PARTITION = 25
    FILE_NAME = "my_data.parquet"

    schema = pa.schema([pa.field('col1', pa.decimal128(5, 2))])

    random.seed(0)
    data1 = [{"col1": Decimal(f"{random.randint(0, 346)}.00")} for i in range(NUM_DATA_POINTS_PER_PARTITION)]
    data2 = [{"col1": Decimal(f"{random.randint(0, 346)}.00")} for i in range(NUM_DATA_POINTS_PER_PARTITION)]

    ddf = dd.concat([pd.DataFrame(data1), pd.DataFrame(data2)])

    try:
        shutil.rmtree(FILE_NAME)
    except FileNotFoundError:
        pass

    ddf.to_parquet(path=FILE_NAME, engine='pyarrow', schema=schema)

    ddf2 = dd.read_parquet(path=FILE_NAME, engine="pyarrow")  # throws an AssertionError on this line
```

```
Traceback (most recent call last):
  File "C:/Users/firmanm/.PyCharm2019.2/config/scratches/scratch_7.py", line 28, in <module>
    ddf2: dd.DataFrame = dd.read_parquet(path=FILE_NAME, engine="pyarrow")  # throws an AssertionError on this line
  File "C:\Users\firmanm\PycharmProjects\bi_core\venv\lib\site-packages\dask\dataframe\io\parquet\core.py", line 231, in read_parquet
    parts, statistics, filters, index, chunksize
  File "C:\Users\firmanm\PycharmProjects\bi_core\venv\lib\site-packages\dask\dataframe\io\parquet\core.py", line 623, in process_statistics
    out = sorted_columns(statistics)
  File "C:\Users\firmanm\PycharmProjects\bi_core\venv\lib\site-packages\dask\dataframe\io\parquet\core.py", line 544, in sorted_columns
    assert divisions == sorted(divisions)
AssertionError
```

I've done some digging and I believe that the root cause of this issue is that the partition min and max in the metadata statistics for Decimal columns is not being decoded from bytes. This causes the logic in ```sorted_columns``` to fail because sometimes min is greater than max in terms of the raw bytes.

**Comment by mrocklin** [comment]
Thank you for the excellent reproducible example @maxfirman , and my apologies that no one has had the time to respond until now.

>  I believe that the root cause of this issue is that the partition min and max in the metadata statistics for Decimal columns is not being decoded from bytes.

This has happened before for other data types.  Historically we've resolved this by raising an issue upstream in the Apache Arrow JIRA.  Is this something that you're comfortable doing?  If not I can handle it.

**Comment by maxfirman** [comment]
@mrocklin thanks very much for taking the time to respond to my issue. I have now raised the issue on the Apache Arrow JIRA (https://issues.apache.org/jira/browse/ARROW-7350).

**Comment by jsignell** [comment]
I can no longer reproduce so I am going to close this.
