### ISSUE TITLE
assigning values using '.loc

### ISSUE THREAD

**Issue by BabuTango** [dask/dask#5648]
the below code is taken from: https://docs.dask.org/en/latest/dataframe-indexing.html

>>> import dask.dataframe as dd
>>> import pandas as pd
>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [3, 4, 5]},
...                   index=['a', 'b', 'c'])
>>> ddf = dd.from_pandas(df, npartitions=2)
>>> ddf
Dask DataFrame Structure:
                   A      B
npartitions=1
a              int64  int64
c                ...    ...
Dask Name: from_pandas, 1 tasks.

**while i use ddf.loc["a",'A'] = 1,** 
python thows 
TypeError                                 Traceback (most recent call last)
<ipython-input-45-a217c4a9dff5> in <module>
----> 1 ddf.loc["a",'A'] = 1

TypeError: '_LocIndexer' object does not support item assignment

@mrocklin  Can you please help me with this issue

**Comment by jacobtomlinson** [comment]
@BabuTango just to let you know many US based folk are out for Thanksgiving.

**Comment by mrocklin** [comment]
As the error suggests, dask dataframe doesn't support item assignment in this case.

**Comment by mrocklin** [comment]
We're also unlikely to.  Iterating over a parallel dataframe and affecting rows one-by-one is generally not a good idea for performance. Thank you for raising this @BabuTango .  Closing.
