### ISSUE TITLE
Missleading / Incomplete Docs - Scheduling and Pandas

### ISSUE THREAD

**Issue by latusaki** [dask/dask#5649]
When trying to decide scheduler between thread and process model, I read documentation on Dask like https://docs.dask.org/en/latest/scheduling.html#local-threads, which suggests numpy, Pandas operations are OK for thread scheduling. 
I spent a lot of time debugging performance of purely pandas code (under map_partitions) only to find I had 95% thread wait times. After reading pandas release notes, I found that only specific Pandas operations release the GIL. 

Would it be acceptable for me to submit a Dask docs edit on the relevant parts, to make it clear that only specific functions in Pandas will release the GIL ? (with a disclaimer that more are being added)

**Comment by jacobtomlinson** [comment]
Yes please if you feel you can improve the documentation please don't hesitate to raise a PR.

**Comment by mrocklin** [comment]
When profiling a multi-threaded application often all you will see is that
you're waiting on thread.Lock.  This has nothing to do with the GIL.  It's
just that profiling multi-threaded applications is hard.  If you want to
use the cProfile module then please use Dask's single-threaded scheduler.
If you want to profile multi-threaded code then probably the best thing
today is to use Dask's dashboard.

**Comment by latusaki** [comment]
I found out that the pandas code was holding GIL using this library: https://github.com/chrisjbillington/gil_load 

I tested running multiple threads using ThreadPool to fire off functions with Pandas code. It's not related to Dask directly, although the suggestion from Dask documentation that Pandas won't hold the GIL lead me to consider it a fact for quite some time, and use threading scheduler instead of process. I will make a MR tomorrow on this.

**Comment by mrocklin** [comment]
For most operations, Pandas does not hold the GIL.

**Comment by latusaki** [comment]
It could be a coincidence then that most operations we use  (or the ones taking the longest) do hold the GIL, in any case I think it will be beneficial to leave room for doubt and have people test both schedulers rather than assume Thread is the right one. For example one of our main operations is rolling, which is not included among the ones mentioned for GIL release here: https://pandas.pydata.org/pandas-docs/version/0.23.4/whatsnew.html#whatsnew-0171-performance

sort_values, group_by are among some of the functions that are explicitely mentioend to release GIL, but there are many more where its not clear.

**Comment by TomAugspurger** [comment]
@latusaki FYI, most of the methods you mentioned in pandas released the GIL because people explicitly raised issues on the pandas issue tracker about them. There are likely places where the GIL could be released with little effort. I'd encourage you to raises issues where you identify GIL-holding to be a bottleneck.

**Comment by latusaki** [comment]
Thanks, will keep it in mind. Wll have to see if gil_load utility can produce per-line numbers, to help identify the exact lines that cause the bottleneck.
