### ISSUE TITLE
Easier Task Resource Allocation? [Feature]

### ISSUE THREAD

**Issue by aprowe** [dask/dask#5662]
I am very interested in running certain nodes on certain workers (for GPU tasks) but am finding it difficult to integrate the current resources API, as I have to keep track of all the nodes and eventually feed them into `compute(graph, resources={...})`. This means I would have to change the workflow of our code base, and default to working with dask at a lower level than we currently are (i.e. keeping track of node names).

Is there any plans to integrate resources into a higher-level API?
 
With my limited dask knowledge, I was thinking an extra dictionary attribute passed along with HighLevelGraph would do the trick.
For example: 

```python
from dask import delayed
node1 = delayed(my_fn)(dask_key_name='node1', dask_resources={'gpu': 1})
node2 = delayed(my_fn2)(dask_key_name='node2', dask_resources={'cpu': 1})
node3 = node1 + node2

node1.dask.resources
# {'node1': {'gpu', 1}}

node2.dask.resources
# {'node2': {'cpu': 1}}

node3.dask.resources
# {'node2': {'cpu': 1}, 'node1': {'gpu', 1}}

node3.compute(resources=node3.dask.resources)
# Or ideally, node3.compute()
```

Are there any issues to this approach?

**Comment by sjperkins** [comment]
I think this is a variation of Task Annotations: https://github.com/dask/dask/issues/3783

**Comment by mrocklin** [comment]
> Are there any issues to this approach?

In principle the API that you propose seems fine.  I think that the next step would be to propose how this would be implemented.  In principle you're talking about a change to the core graph specification, which is a large undertaking that many people will have strong opionions on, so it's likely to be a challenge.

As @sjperkins writes above, something similar was tried a while ago with Task Annotations and, despite excellent work on an implementation, it didn't go anywhere (at least not yet).

Effort here is welcome, but you should be aware that the probability of success is low without prolonged sustained effort, and considerable buy-in from people with commit rights.

**Comment by mrocklin** [comment]
@aprowe any further updates from you on this?  If not I'm inclined to close in favor of the pre-existing issues.

**Comment by aprowe** [comment]
Its beyond the scope I was hoping for, and the task annotations ticket is further along, so I'll just keep an eye on that issue. Thanks for the response, feel free to close.
