### ISSUE TITLE
[FEA] In-place DataFrame.drops() 

### ISSUE THREAD

**Issue by madsbk** [dask/dask#5664]
### What 
Support of in-place `DataFrame.drops()`

### Motivation
Pandas and cuDF support in-place `DataFrame.drops()`, which is significant faster and less memory intensive than copying the whole DataFrame.

This can double the performance of a distributed merges in some cases: https://github.com/dask/dask/pull/5657

Additionally, a fast `drops()` operation can simplify common workflows: https://github.com/dask/dask/pull/5657#issuecomment-560557840

### Discussion

However as @mrocklin points out, [we cannot support in-place _as is_ because tasks in Dask may run twice or may run out-of-order so we generally cannot modify inputs of a task in-place.](https://github.com/dask/dask/pull/5657#issuecomment-560455949)

As I see it, there is two approaches:
  - Making the drops() operation faster in cuDF, which is hard since the semantic of Pandas requires a full copy but could be done by using some kind of _copy-on-write_ technique. 
  - As suggested by @mrocklin, inject `inplace=True` in drop operations in Dask when it is safe. E.g., it is save when the drop is inside a blockwise operation where it doesn't affect the input of the blockwise operation. @rjzamora is working on this solution.

**Comment by rjzamora** [comment]
@mrocklin - I have a question about the kinds of "drop" tasks that can be safely modified to operate in-place.  

I understand that we would not want to modify data that is the direct input to the `Blockwise` subgraph containing the drop operation. You also mentioned that we would probably not want to modify a task that had multiple direct dependents.  Is it dangerous when the dependents are also within the same subgraph, or just if the drop task has no dependents within the subgraph, but the larger `Blockwise` element has multiple dependents?

For example, I am running a very simple test, and getting graph dependencies that look like this:

![subgraph-example](https://user-images.githubusercontent.com/20461013/70064529-4b990100-15af-11ea-9a32-f99964d4ce04.png)


Would it be safe to perform the drop "in place" for this sepcific example?

For reference, the actual test looks like this:

```python
size = 4
df = pd.DataFrame(
    {
        "a": np.random.permutation(np.arange(size)),
        "b": np.random.permutation(np.arange(size)),
    }
)
ddf = dd.from_pandas(df, npartitions=1)
ddf["a"] = ddf["a"] + ddf["b"]
ddf = ddf.drop(columns=["b"])
ddf["a"] = ddf.a + 1
graph_before = ddf.dask
graph_after = optimize_blockwise(ddf.dask)
graph_after_2 = optimize_drop(graph_after)
```

**Comment by mrocklin** [comment]
I think that it is likely safe if the drop node has many dependents (many tasks use the result of drop).

The dangerous situtation, I think, is when the input to drop has other dependencies.  In that situation it would matter if the drop was called first or second in the computation, which is hard for us to guarantee.
