### ISSUE TITLE
Dask and Pandas syntax difference

### ISSUE THREAD

**Issue by fansichao** [dask/dask#5670]
I am using Dask replace Pandas==0.24.2

I want to know the grammatical differences with Dask and Pandas.

I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this.

Thanks

**Comment by TomAugspurger** [comment]
The docstrings typically mention when we diverge from the pandas behavior:
https://docs.dask.org/en/latest/dataframe-api.html. I don't think there's a
single list collecting all of these, and I'm not sure that compiling that
list is feasible.

**Comment by jcrist** [comment]
Yeah, we're *mostly* compatible, with a few differences in keyword arguments/methods here and there. I suggest you try things out and report issues as you have them. We *could* generate a full api diff, but that's hard to do (see  #3688). Closing.
