### ISSUE TITLE
Basic "delayed" example in docs doesn't work as expected

### ISSUE THREAD

**Issue by zjost** [dask/dask#5674]
I am working through the `delayed` example in [the documentation](https://tutorial.dask.org/01_dask.delayed.html).  It was working as expected, but I was surprised that the parallelized loop code took ~2 seconds instead of 1 second, since all the "inc" calls should be in parallel and there's not a "sleep" call in the "sum" function.

```python
from time import sleep
from dask import delayed

def inc(x):
    sleep(1)
    return x + 1

data = [1, 2, 3, 4, 5, 6, 7, 8]

%%time
# Sequential code

results = []
for x in data:
    y = delayed(inc)(x)
    results.append(y)

total = delayed(sum)(results)
total.compute()

# CPU times: user 4.72 ms, sys: 3.14 ms, total: 7.86 ms
# Wall time: 2.01 s
```
When I run this example in the linked [live session](https://mybinder.org/v2/gh/dask/dask-tutorial/master?urlpath=lab/tree/01_dask.delayed.ipynb), then it behaves as expected 

> CPU times: user 2.11 ms, sys: 4.19 ms, total: 6.3 ms
Wall time: 1 s

I have copied/pasted the exact same code, but it takes twice as long in my local instance.  Further, if I copy the `data` list N times (e.g. `data = data*5`), the Wall time in seconds = 2*N.  

I'm using Python 3.7.5 and using Dask 2.8.1.  The live session notebook is python 3, dask version 1.2.2.  The "visualize" output is exactly as you would expect:  a bunch of parallel boxes pointed to a single call to "sum".

**Comment by jrbourbeau** [comment]
What is the output of 

```python
import dask
print(dask.system.CPU_COUNT)
```
 
on your local machine? It could be that all 8 delayed `inc` calls aren't running in parallel at the same time

**Comment by zjost** [comment]
The output is 4, which makes sense.  Can I change it to use threads or something larger than 4?

**Comment by jrbourbeau** [comment]
You can use the `scheduler` and `num_workers` compute parameters to use threads / specify the number of threads:

```
total.compute(scheduler="threads", num_workers=8)
```

Note there will be some limit on the possible performance based on the resources of your local machine

**Comment by jrbourbeau** [comment]
https://docs.dask.org/en/latest/scheduling.html#configuration

**Comment by zjost** [comment]
Works.  Sorry for the false alarm.

**Comment by jrbourbeau** [comment]
Not a problem, thanks for your quick responses @zjost
