### ISSUE TITLE
Using cloud-volume as a storage backend

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#5687]
[Cloud-volume](https://github.com/seung-lab/cloud-volume) is a great library for interacting with chunked volumetric data on the cloud.  A big advantage is the web visualizer [Neuroglancer](https://github.com/google/neuroglancer) that can display the data "Google maps" style.  The cloud-volume API is very Numpy like, which leads to my desire to see how well it would work with Dask. Here is where I'm at:

There are one or two inconsistencies of CloudVolume objects with the Numpy API (`ndim` missing, `shape` returning an array instead of tuple) which Dask relies on.  I think these can be addressed.

The cloud-volume library manages the storage.  On read, the library downloads the desired data when it an object is sliced, which seems to work reasonably well if the object is wrapped in an Array. On write to storage, it calls `tostring()` on the slice it wants.  To get a small demo working, I can simply slap that method onto a dask object implemented as `compute().tostring()`.  This does not feel quite right in a lazy environment, and that may be the reason `tostring` isn't implemented in Dask.   What's the right approach here for interacting with dask?

I have played around on a single machine, getting things to work with some wrappers as shown in [this gist](https://gist.github.com/chrisroat/2024a495710a871fc7484a5071356815). What considerations should there be when thinking about distributed environment?

**Comment by jcrist** [comment]
Looks like a useful library.

For reading, your implementation looks fine (provided cloudvolume supports threaded/concurrent access). You might want to wrap your implementation in a larger method so users don't have to interact with your `CvReadToDaskWrap` implementation, but otherwise this looks good.

For writing, you usually want each dask worker to write the data directly to storage. As written you're computing a result, sending it to the client, then having cloudvolume handle the writes. For small outputs this may be fine, but for larger data it'd be more efficient to parallelize the writes (if possible). The feasibility of this would depend on cloudvolume's storage format (if it can be written in disparate chunks, or if only a single writer works).

> On write to storage, it calls tostring() on the slice it wants.
> This does not feel quite right in a lazy environment, and that may be the reason tostring isn't implemented in Dask. What's the right approach here for interacting with dask?

Dask is usually used for working with large data - converting a large array to a text representation is usually not what you want (it's inefficient). Does cloudvolume store data in text representation rather than a binary format?

---

If your only goal here is to store large ND arrays in the cloud, you may also be interested in the [zarr library](https://zarr.readthedocs.io/en/stable/). This works very well with dask, providing efficient reading and writing of large arrays to a variety of cloud backends.

**Comment by chrisroat** [comment]
Thanks for your comments.

I am storing large ND arrays, though a requirement is that they are viewable in Neuroglancer, which supports this precomputed format, as well as several others.  Unfortunately, I do not see zarr on that list.

The wrappers weren't intended for use.  I just used them to keep adding methods until I could get the two libraries to work together.  It was a minimal interface, but not the optimal one.  Would you suggest a `to_neuroglancer` method (or a better name) could be added to dask?

As written, I believe the cloudvolume code is efficient for parallelization.  In stand-alone mode, it does do chunking and parallel writes across threads.  The reason for going to dask is that my upstream data is large and is all in dask.

The tostring method is only called by the library during write on each slice.  One option is to have the `to_neuroglancer` method call the library in single-threaded mode, using a wrapper that would make the `tostring` call become a delayed call.  This way, dask can include this in its task graph.  Does that seem reasonable?

**Comment by jcrist** [comment]
> Would you suggest a to_neuroglancer method (or a better name) could be added to dask?

IMO neuroglancer isn't common enough to warrant a method in dask itself. Perhaps such a method could be added to `cloudvolume`?

> As written, I believe the cloudvolume code is efficient for parallelization. In stand-alone mode, it does do chunking and parallel writes across threads. The reason for going to dask is that my upstream data is large and is all in dask.

> ... This way, dask can include this in its task graph.

The issue with the current *write* implementation is that every time cloudvolume tries to write a new slice it
- Lazily extracts the slice as a dask-array
- The dask-array is computed and pulled back to the client node as a numpy array
- Cloudvolume calls `tostring` on the numpy array, then writes the output

This is inefficient for several reasons. It pulls all data back through the client (IO bottleneck), and handles all writes on the client side serially (CPU bottleneck).

Ideally there'd be a way to handle writes from the worker processes/threads in parallel. This would remove the need to pull data back to the client, the workers would write directly to cloudvolume in parallel. This might look something like:

```python
def write_chunk_to_cloudvolume(a, **kwargs):
    """Write a chunk to cloudvolume. This chunk is part of a larger array,
    but it's written to storage piecewise in parallel."""
    # not sure if/how this part would be written

# Write each chunk in parallel
a.map_blocks(
     write_chunk_to_cloudvolume,
    **extra_arguments_to_forward
).compute()
```

What you have right now isn't incorrect, I'm just hoping there's a more efficient way this can be done.

**Comment by chrisroat** [comment]
Thanks for your tips, as they are helping me better understand the dask model.  This could definitely be done via `map_blocks` using `block_info`.  Each block can be written by a single-threaded CloudVolume object.  I think it's probably safest, and lightweight enough, to create the object within the function.

In these cases, what kind of return value would be expected?

**Comment by TomAugspurger** [comment]
You might look at Array.to_zarr for inspiration.

**Comment by TomAugspurger** [comment]
Checking in @chrisroat, how are things going here? Did `to_zarr` provide a useful example?

I share Jim's opinion that

> IMO neuroglancer isn't common enough to warrant a method in dask itself. Perhaps such a method could be added to cloudvolume?

Is there anything else to do here?

**Comment by chrisroat** [comment]
I have started a method based on `to_zarr`, and it seems like it should work.  I'll just plan to add it to cloudvolume.  Thanks.
