### ISSUE TITLE
I HAVE THE SAME PROBLEM

### ISSUE THREAD

**Issue by maxtrus** [dask/dask#5692]
I have the same issue here is my code someone help

print(" ~~~~~~~~~~~~~~~~~~~~~~~ ")
print("|    TIM'S DINER        |")
print("|    Ordering System    |")
print(" ~~~~~~~~~~~~~~~~~~~~~~~ ")
print("")
print("Welcome to our takeway ordering system.")
print("Type X to exit")

code = input("Enter the option code you would like to order from the Menu : ")

file = open("foodMenu.txt","r")

totalCost = 0
while(code!="X"):
    for line in file:
      data = line.split(";")
      itemCode = data[0]
      itemDescription = data[1]
      itemPrice = float(data[2])
      if itemCode == code:
        print(itemCode + " - " + itemDescription + " - £" + str(itemPrice))
        totalcost = totalCost + itemPrice
    code = input("Enter another food code or X to exit") 

print(file.read(5))
print("Total Cost of your order: £" + str(totalCost))
print("Good bye!")
file.close()

# i am trying to get i to open the text file but it says it doesnt exist please help

**Comment by maxtrus** [comment]
Traceback (most recent call last):
  File "H:\report\new-tims-diner\tims-diner-new.py", line 11, in <module>
    file = open("foodMenu.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'foodMenu.txt'
>>> 
   

#this is the error i get

**Comment by TomAugspurger** [comment]
@maxtrus I don't see dask mentioned anywhere in your code. Did you mean to post this somewhere else/

**Comment by jcrist** [comment]
Closing as unrelated.

**Comment by maxtrus** [comment]
yes didnt mean to post this where do i post it as im new and stuck

**Comment by TomAugspurger** [comment]
Stackoverflow is generally a good resource if you have a well-posed question.
