### ISSUE TITLE
Implement dask.dataframe.to_numeric

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#5698]
Which mimics `pandas.to_numeric`.

For scalar inputs, this could return a Delayed object.

For array inputs, this would return a `dask.array.Array` and would be `.map_blocks(pd.to_numeric)`.

For Series, it'd be `.map_partitions(pd.to_numeric)`.

I'm not sure if downcasting can be easily supported, since we'd need to scan the data for min / max values.

**Comment by jsignell** [comment]
Just to say that I am taking a crack at this
