### ISSUE TITLE
[QST] Initiate Communication Task

### ISSUE THREAD

**Issue by madsbk** [dask/dask#5699]
Is it possible to create a task (a node in the `dask` graph) that initiate communication asynchronously and then have a later task _wait_ on the communication to finish?

#### Motivation
I am working on optimizing distributed merge of two dataframes. I would like to implement double buffering so that workers can communicate while computing local dataframe merges.

cc @mrocklin

**Comment by mrocklin** [comment]
Tasks should not explicitly communicate.  Instead they produce results, the scheduler decides subsequent tasks should be run, and then those workers initiate communications to gather the necessary results. Once all dependencies for a result have arrived on a worker then the worker feels free to start that task.

In this way overlapping communication and computation already happen in Dask, assuming that there are tasks and communications to overlap.

For merge computations in partifcular I would expect to see a bit of overlapping towards the beginning, but, due to the all-to-all nature of the computation, I expect that there will be a decent period where there is only communication without extra computation to fill in.

**Comment by mrocklin** [comment]
As demonstration of this if you look at a task stream plot for a non-trivial computation you'll often see that red blocks (transfers) overlap non-red blocks (computation)

https://matthewrocklin.com/raw-host/dask-report.html

**Comment by madsbk** [comment]
Make sense, but it the case of merge this _ad hoc_ scheduling is a problem. 
I think it is possible to hide most of the computation of the local `concat` and `merge` behind communication but it requires a very specific scheduling.

I think I finally found a viable approach :) 
Will continue working on it tomorrow and report back.

**Comment by mrocklin** [comment]
I would be curious to hear more about your plan.  Let me know if there is some way I can help.

**Comment by madsbk** [comment]
My plan was to create a task graph that implements latency hiding by making by interleaving independent task chains.
I can create the graph, but the scheduler re-distribute the initial dataframe partitions between the workers so it doesn't work.
I guess, it is not possible to pin results to a specific worker?

Alternatively, we can do as in cuML where they manually execute operations on the workers without involvement of the scheduler.

**Comment by mrocklin** [comment]
> I guess, it is not possible to pin results to a specific worker?

You can specify that certain tasks run on certain workers, yes, but this kind of manual control rarely works out well in practice.  It's not robust to new or dying workers, load balancing, or a variety of other systems.  

For the UCX + Dask + cuDF work my sense is that accelerating this is possibly not the biggest bottleneck right now.  Personally I'm more curious about how to make full DGX-1 or multi-node work  effectively.  My sense is that we still have order-of-magnitude issues going on there that are, I hope, more straightforward to integrate into a long-term solution.

**Comment by madsbk** [comment]
> You can specify that certain tasks run on certain workers, yes, but this kind of manual control rarely works out well in practice. It's not robust to new or dying workers, load balancing, or a variety of other systems.

Do you have an example of this you can point me to? I would like to benchmark the performance impact even if it isn't a general solution :)

**Comment by mrocklin** [comment]
See
https://distributed.dask.org/en/latest/locality.html#specify-workers-with-compute-persist

**Comment by mrocklin** [comment]
Putting on my Dask maintainers hat, It's going to be very hard to convince folks that specifying workers directly in algorithms like merge is a good idea.  There are several things that make this janky for Dask, so it's unlikely to be accepted.

**Comment by mrocklin** [comment]
Experimentation is always good though, I just don't want you to be surprised by showing better numbers and then having your work turned away.
