### ISSUE TITLE
Enable compression for on-disk shuffle with PartD 

### ISSUE THREAD

**Issue by ChrWesp** [dask/dask#5704]
Dask team - first of all, thanks for the good work and providing such a usefull tool!

I would like to propose a feature request:
Shuffle operations like set_index use PartD for on-disk shuffling. PartD supports transparent compression (lz4), which can greatly improve performance in our usecase.
Howerver, from within dask it is not possibel to trigger a compressed shuffle as any interfacing to the partd library is currently hard coded.

**Example:**
```
import dask
import dask.dataframe as dd
from dask.distributed import Client

# setup local cluster
client = Client(n_workers=4, threads_per_worker=4, processes=False, memory_limit='16GB')

# load, set index, save
df = dd.read_parquet('Data/Parquet', engine='fastparquet')  # <-- is compressed
df2 = df.set_index(use_columns, shuffle='disk')  # <-- generates a lot of uncompressed data on the disk
df2.to_parquet('Data/ParquetSorted', engine='fastparquet', compression="lz4")  # <-- again compressed
```

or see here:
https://stackoverflow.com/questions/58510018/compression-for-dask-on-disk-shuffle

Could this be extended with something like
`df2 = df.set_index(use_columns, shuffle='disk', shuffle_compression="lz4") `
or
`df2 = df.set_index(use_columns, shuffle='disk:lz4') `
?

**Comment by TomAugspurger** [comment]
Thanks for the report. It'd be reasonable to control these by both keywords and dask configuration settings.

My preference would be for a `shuffle_options` keyword to places likes `set_index`, which would allow you to pass keywords through, while not conflicting with pandas' keywords.

**Comment by mrocklin** [comment]
We could also:

   1. Include this as part of the dask.config configuration
   2. Encourage users to make their own Mapping classes using PartD
   manually, and then pass those to the Worker explicitly.  This is doable
   today, but requires users to do a bunch of things manually, and so is
   probably not fun.

**Comment by TomAugspurger** [comment]
@ChrWesp do you have any interest in working on this? I think the configuration lookup would be easiest, and adding a new keyword won't be much additional work on top of that.

**Comment by ChrWesp** [comment]
@TomAugspurger : Yes, I can take a look at it and submit a pull-request. I will need a bit of time as we are wuite quiet busy currently, but I am happy to work on it.
