### ISSUE TITLE
More explicit support for cupy-backed dask.Array

### ISSUE THREAD

**Issue by cjnolet** [dask/dask#5714]
While is possible to have a `dask.Array` backed by cupy arrays currently, there are places where numpy is explicitly used to perform operations on the underlying `ndarray` objects. One such example of this is in the `unique()` function on `dask.Array` [1].

Unfortunately, this causes users to have to reimplement the corresponding distributed functions just so `cupy` can be invoked, rather than `numpy`.

It would be very useful if there was a way to use cupy for these invokation when the underlying arrays are cupy-based. Perhaps if the cupy alternative does not exist, it could fall back to using numpy (and print a warning so the user is aware of the potential performance implication). 

[1] https://github.com/dask/dask/blob/master/dask/array/routines.py#L847

**Comment by mrocklin** [comment]
If a dask array operation fails with cupy or coerces to numpy then it's probably a bug.  If you have specific cases where this is true then I recommend that you raise issues for them.

**Comment by mrocklin** [comment]
In the meantime I'm going to close this issue, just because it has sort of an endless scope.  We'll never get absolutely everything.
