### ISSUE TITLE
Crash when trying to use Julia from Dask multiprocessing

### ISSUE THREAD

**Issue by lungben** [dask/dask#5732]
Hello,

PyJulia crashes when I try to call Julia from inside a Python process using Dask multiprocessing (dask.distributed.Client) throwing the following exceptions:
```
Exception: OSError('exception: access violation reading 0x00000000000019A8')
Exception: AttributeError("function 'was_initialized' not found")
```

Calling Julia from Python's built-in multiprocessing works however fine.

I am using Windows 10 (64 bit), Python 3.7, Dask 2.9 and Julia 1.3.

Test Code:

```
from julia import Julia
import dask.distributed
import concurrent.futures


def jl_calc(id):
    func_text = """
        function myfunc(n:: Int64)
            z:: Int64=1
            for i=1:n
                z += 2i^2
            end
            z
        end
        """
    jl = Julia()
    test_func = jl.eval(func_text)
    res = test_func(id+1)
    return res


def submit_tasks(executor):
    futures = []
    for i in range(10):
        futures.append(executor.submit(jl_calc, i))
    results = [future.result() for future in futures]
    print(results)


if __name__ == '__main__':
    print('calling Julia from Pythons bulit-in Multiprocessing')
    executor_multiprocessing = concurrent.futures.ProcessPoolExecutor()
    try:
        submit_tasks(executor_multiprocessing)
    finally:
        executor_multiprocessing.shutdown()
    print('calling Julia from Pythons bulit-in Multiprocessing successful')

    print('calling Julia from Dask Client')
    executor_dask = dask.distributed.Client()
    try:
        submit_tasks(executor_dask)
    finally:
        executor_dask.shutdown()
    print('calling Julia from Dask Client successful')
```

System setup and stack trace is given in the attachment.
[Dask_Julia_error.txt](https://github.com/dask/dask/files/3984049/Dask_Julia_error.txt)

The same issue has been raised at PyJulia, because I do not know in which component the issue is:

https://github.com/JuliaPy/pyjulia/issues/344

Best Regards
Benjamin

**Comment by mrocklin** [comment]
> Calling Julia from Python's built-in multiprocessing works however fine.

Can I ask you to try when using different multiprocessing contexts, like fork, forkserver, and spawn?

**Comment by tkf** [comment]
PyJulia dev here. Is `jl_calc` guaranteed to be called in the same thread always?  `libjulia` is not thread-safe so otherwise it is natural you have errors.  I'm guessing `multiprocessing` uses some OS threads behind the scene to implement the IPC.  We had a similar problem with vanilla `multiprocessing` before https://github.com/JuliaPy/pyjulia/issues/206 (still unsolved).

**Comment by mrocklin** [comment]
With Dask it will definitely be called from multiple different threads
within the same process, and on different processes.

To check this, you might create your cluster with the threads_per_worker=1
keyword

**Comment by lungben** [comment]
Hi,

thanks for your suggestions.
I checked the multiprocessing-method settings suggested by Matthew with threads_per_worker=1 (for my use case I actually need only one thread per worker, therefore this is fine for me).
I got again a number of errors (access violation, worker restart), but at the same time the actual calculation results were returned and printed.
Logs are attached.

[dask_julia_test2.txt](https://github.com/dask/dask/files/3991785/dask_julia_test2.txt)

Best Regards
Benjamin

**Comment by mrocklin** [comment]
It looks like things aren't shutting down cleanly.  Can I ask you to try
creating the Dask client as a context manager with `with Client(...) as
executor_dask:`

**Comment by tkf** [comment]
If this is happening while shutting down the Python processes, maybe you can workaround this by calling [`atexit.unregister`](https://docs.python.org/3/library/atexit.html#atexit.unregister) on `jl.api.jl_atexit_hook`.

**Comment by lungben** [comment]
Hi,

when using a context manager for Dask Client, I get the error
> Error in atexit._run_exitfuncs:
> OSError: exception: access violation reading 0x00000000000019A0

When adding `atexit.unregister(jl.api.jl_atexit_hook)` inside the function submitted to the Client, the access violation error message vanishes, but I still got "Closing dangling stream" and "restarting worker" warnings.

Best Regards
Benjamin

[dask_julia_test3.txt](https://github.com/dask/dask/files/3992950/dask_julia_test3.txt)

**Comment by quasiben** [comment]
@lungben what happens if you remove dask can execute julia directly from multiprocessing ?

**Comment by jakirkham** [comment]
Would be good if someone could retest

**Comment by jrbourbeau** [comment]
Closing due to lack of response. Though we can reopen if folks would like to continuing engaging
