### ISSUE TITLE
Feature Request: pull delayed scheduler from configuration

### ISSUE THREAD

**Issue by CJ-Wright** [dask/dask#5738]
Would it be possible for dask collections and delayed to initialize a distributed scheduler from some sort of configuration?

My understanding is that currently if a distributed client is instantiated then dask collections and delayed will use that client as the scheduler. However there is no way to put the client loading information into a configuration so that dask collections and delayed instantiate that client themselves if it doesn't exist, forcing you to use whatever client they initialize.

This would be good to have because libraries currently using dask collections and delayed have no way to bind to a particular client unless that client is externally initialized, which may not be possible in some circumstances, for instance running a standalone app.

**Comment by CJ-Wright** [comment]
CC @danielballan

**Comment by mrocklin** [comment]
> Would it be possible for dask collections and delayed to initialize a distributed scheduler from some sort of configuration?

When constructing a dask collection type you can specify a default scheduler to use. 
 See https://docs.dask.org/en/latest/custom-collections.html

Maybe you'll be able to screw around with that to get what you want?

**Comment by CJ-Wright** [comment]
Awesome! Thank you very much! Is there something similar for delayed?

**Comment by CJ-Wright** [comment]
CC @martindurant

**Comment by mrocklin** [comment]
Delayed is a dask collection.  Everything I said holds true for it as well.

**Comment by quasiben** [comment]
I think @mrocklin resolved this issue.  If I'm mistaken please reopen
