### ISSUE TITLE
Use shallow copies when assigning columns

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5739]
Currently when we run code like `df["z"] = df.x + df.y` we call `df = df.assign(z=df.x + df.y)`.  However, the latter snippet calls the underlying assign method, which calls `df.copy()` which can be slow.  Instead, it might be nice to do soemthing like the following:

```python
def set_column(df, name, value):
    df = df.copy(deep=False)
    df[name] = value
    return df
```

And then replace the calls to `M.assign` with this.

This is particularly important for cudf, but probably helps pandas performance a bit as well.

We might want to do this for all assign calls, rather than just setitem?  There are some semantic differences in pandas apparently with regards to copying, but because we don't mutate my guess is that we should do this everywhere.  @TomAugspurger ?

**Comment by mrocklin** [comment]
Also cc @rjzamora @quasiben and @kkraus14

**Comment by TomAugspurger** [comment]
>  There are some semantic differences in pandas apparently with regards to copying, but because we don't mutate my guess is that we should do this everywhere.

That's my initial reaction.

On this topic, https://github.com/pandas-dev/pandas/issues/29309 may be worth reading through.

The operations

```python
    df = df.copy(deep=False)
    df[name] = value
```

May or may not update the original `df` passed to your `set_column`, depending on if you're updating an existing column and the dtypes of the original and new values. I can prioritize fixing that on the pandas side of things if needed.
