### ISSUE TITLE
Feature request: DataFrame.mode()

### ISSUE THREAD

**Issue by maowerner** [dask/dask#5744]
The pandas Series and DataFrame has a member function `mode()` which return a Series / DataFrame with the most frequent value(s). 

The pandas docu can be found [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mode.html) and [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mode.html#pandas.Series.mode)

In Dask the function is currently not supported. The best workaround I could find is

```
ddf.value_counts().compute().idxmax()
```

Would it be possible to expose `mode()` in Dask? If it a reasonable first issue I would also be available to implement it myself.

**Comment by mrocklin** [comment]
Hi Markus, thank you for raising an issue.

Sure, I would say that this is in-scope for the project.  Is this something
that you would like to contribute?

**Comment by maowerner** [comment]
Hello Matthew,

thanks for your estimation. I will try it next weekend

**Comment by ayushpatidar** [comment]
@mrocklin  can i work on this feature.

**Comment by mrocklin** [comment]
You do not need to ask permission.  Any pull request that solves this
problem, adheres to our development guidelines, and is relatively simple
will likely be accepted.  https://docs.dask.org/en/latest/develop.html

If you are able to resolve this issue then that would be great!

**Comment by balast** [comment]
being addressed by https://github.com/dask/dask/pull/5958

**Comment by balast** [comment]
Was addressed by https://github.com/dask/dask/pull/5958

**Comment by jrbourbeau** [comment]
Thanks for implementing `mode` and following up here @balast!
