### ISSUE TITLE
 can't pickle_asyncio.Task objects

### ISSUE THREAD

**Issue by TOURIST-ML** [dask/dask#5745]
I have class

class train():
       def _init(client):
          self.client = client
       def train():
           print("in train function")

if __name__=="__main__":
        c = LocalCluster(processes=False, n_workers=4)
            dask_client = Client(c, asynchronous=True)
           ob = train(dask_client)
           dask_client.submit(ob.train)

ERROR:  **can't pickle _asyncio.Task objects**

**Comment by mrocklin** [comment]
Thank you for raising an issue @TOURIST-ML .  My guess is that you don't need the asynchronous=True keyword, which is only used if you intend to use async/await keywords, see https://distributed.dask.org/en/latest/asynchronous.html .  

Also, I recommend reading through https://blog.dask.org/2018/02/28/minimal-bug-reports

**Comment by TOURIST-ML** [comment]
@mrocklin  I tried with asynchronous=False as well. But still the error persist.

**Comment by mrocklin** [comment]
Then I encourage you to make a minimal reproducible example that triggers the error.  Something that we can copy-paste to run.  Please see the blogpost that I pointed to above.
