### ISSUE TITLE
helm config environment in docs is out of date

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#5749]
I belive the docs for the helm config environment is out of date (https://docs.dask.org/en/latest/setup/kubernetes-helm.html#configure-environment) source for this docs is https://github.com/dask/dask/blob/master/docs/source/setup/kubernetes-helm.rst#configure-environment

It says "By default, the Helm deployment launches three workers using two cores each".

I believe the latest chart has three workers using one core each
https://github.com/dask/helm-chart/blob/master/dask/values.yaml#L53L56

**Comment by mrocklin** [comment]
Thanks Ray!  Are you interested in correcting this with a PR?
