### ISSUE TITLE
If/else Regex in dask dataframe (str.contains) not working

### ISSUE THREAD

**Issue by esokoli** [dask/dask#5753]
I am having an issue passing columns through this regex logic. In pandas, this logic works, but using a dask dataframe, the if statement doesn't catch or change anything.

`df = dd.read_csv('chicago_taxi.csv')
print(df.dtypes)`

Trip_Id                        object
Taxi_Id                        object
Trip_Start_Timestamp           object
Trip_End_Timestamp             object
Trip_Seconds                    int64
Trip_Miles                    float64
Pickup_Census_Tract           float64
Dropoff_Census_Tract          float64
Pickup_Community_Area         float64
Dropoff_Community_Area        float64
Fare                          float64
Tips                          float64
Tolls                           int64
Extras                        float64
Trip_Total                    float64
Payment_Type                   object
Company                        object
Pickup_Centroid_Latitude      float64
Pickup_Centroid_Longitude     float64
Pickup_Centroid_Location       object
Dropoff_Centroid_Latitude     float64
Dropoff_Centroid_Longitude    float64
Dropoff_Centroid_Location      object

Objects should be changed to date/time type or str based on this:
`for column in df.columns:
        if df[column].dtype == 'object':
          if (df[column].str.contains(r'\d{4}-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}', regex = True).all()):
            df[column] = dd.to_datetime(df[column])
          else:
              df[column] = df[column].astype('str')`

However, this changes all objects to datetime64[ns]

Trip_Id                       datetime64[ns]
Taxi_Id                       datetime64[ns]
Trip_Start_Timestamp          datetime64[ns]
Trip_End_Timestamp            datetime64[ns]
Trip_Seconds                           int64
Trip_Miles                           float64
Pickup_Census_Tract                  float64
Dropoff_Census_Tract                 float64
Pickup_Community_Area                float64
Dropoff_Community_Area               float64
Fare                                 float64
Tips                                 float64
Tolls                                  int64
Extras                               float64
Trip_Total                           float64
Payment_Type                  datetime64[ns]
Company                       datetime64[ns]
Pickup_Centroid_Latitude             float64
Pickup_Centroid_Longitude            float64
Pickup_Centroid_Location      datetime64[ns]
Dropoff_Centroid_Latitude            float64
Dropoff_Centroid_Longitude           float64
Dropoff_Centroid_Location     datetime64[ns]

**Comment by mrocklin** [comment]
See #5743 .  You need to explicitly call `.compute()` after the `all` call if you want to use it within an if statement.  Beware though that this will incur the cost of reading through all the data each time though, which may be expensive.

You might consider doing this check for columns at once.

**Comment by esokoli** [comment]
After including `.compute()`, I get the same output as first reading in the data in terms of the data types. Any ideas? Thanks for the response.

**Comment by mrocklin** [comment]
I'm not sure exactly what you're asking.  If you think that you've found a bug then I encourage you to produce a minimal reproducible example.  See https://blog.dask.org/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@esokoli can you provide a minimal example? If so, I'll reopen this and we can figure out where the bug is.
