### ISSUE TITLE
set_index() on list with one item

### ISSUE THREAD

**Issue by WesRoach** [dask/dask#5755]
Dask is raising NotImplementedError when passing a single-item list to set_index()

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({
    'id'  : ['1', '1', '2', '2', '3'],
    'col1': ['a', 'b', 'a', 'b', 'a']
})

ddf = dd.from_pandas(df, 1)

# Works
ddf = ddf.set_index("id")
ddf = ddf.reset_index()

ddf = ddf.set_index(["id"])

NotImplementedError: Dask dataframe does not yet support multi-indexes.
You tried to index with this index: ['id']
Indexes must be single columns only.
```

The user is providing a single column on which to index, but Dask is assuming that the list contains multiple values.

**Comment by mrocklin** [comment]
It would be great to fix this.  Do you think that this is something that
you could do Wes?

**Comment by WesRoach** [comment]
Yeah, I'll take a look sometime this week.
