### ISSUE TITLE
`file_size` fails on files larger than 4 GB with gzip compression

### ISSUE THREAD

**Issue by jcrist** [dask/dask#576]
Uncompressed file size is stored as 4 bytes in gzip files, which means it rolls over every 4 GB. This causes problems for large gzip files using `db.from_filenames(fil, chunkbytes=...)`, as the `file_size` returns an incorrect value. From googling, there doesn't seem to be a way around this.

A good interim solution might be to through a warning if the compressed filesize is larger than 1 GB or so.

**Comment by mrocklin** [comment]
As of #1116 we no longer try to get the size of non-seekable compression files.  Closing
