### ISSUE TITLE
Bug report: Dask submit and gather of 2D array objects is unacceptably slow

### ISSUE THREAD

**Issue by tjorda01** [dask/dask#5768]
Our testing showed Dask is unacceptably slow to scatter/submit and gather a data object containing a 2D array for parallel processing on a single computer using a local distributed Client. Over the past few weeks I believe I've exhausted the options described in [distributed.dask.org](https://distributed.dask.org/en/latest/client.html) documentation without success, but I'm open to suggestions if I've missed something.

This is the simple data class we populate, then process using Dask:
```
    @dataclass
    class DataPkg:
        id:int
        data_array:np.ndarray
```
More specifically a large image is divided into tiles no larger than 4096x4096. Each tile then populates a corresponding `DataPkg` object and is added to a list of such objects. The list of `DataPkg` objects is then scattered and submitted for Dask parallel processing like this:
```
     for pkg in datapkgs:
        big_future = client.scatter(pkg)        
        future = client.submit(parallel_ops, func_list, big_future)
``` 

Here is the `parallel_ops` method that Dask executes on each worker process:
```
    def parallel_ops(func_list:List[DataFunction],
                     datapkg:DataPkg) -> DataPkg:
        """ Calls each function in the list on the previous result, then returns the last result. """
        for func in func_list:
            datapkg = func(datapkg)
        return datapkg
```
        
**Problem**:
Dask takes 3.5 seconds to scatter and submit each `DataPkg` with a 4096x4096 numpy array (on an Intel i7 Windows 10 PC with 48 GB RAM). Dask also takes an additional 2.25 seconds to gather the data back. Since, those measurements were run with `func_list` containing a single "no-op" function, we can assume that virtually all of this time is due to Dask overhead. In fact, in a run where the scatter and submit of 4 DataPkgs of 4096x4096 arrays took 13.821 seconds, `cprofile` showed that 13.779 seconds was due to acquisition of thread locks alone.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.000    0.000   13.781    3.445 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\distributed\client.py:1985(scatter)
        4    0.000    0.000   13.781    3.445 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\distributed\client.py:756(sync)
        4    0.000    0.000   13.781    3.445 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\distributed\utils.py:287(sync)
        4    0.000    0.000   13.780    3.445 C:\apps\Anaconda3\envs\img_proc3\lib\threading.py:534(wait)
        4    0.000    0.000   13.780    3.445 C:\apps\Anaconda3\envs\img_proc3\lib\threading.py:264(wait)
       16   13.779    0.861   13.779    0.861 {method 'acquire' of '_thread.lock' objects}
        4    0.000    0.000    0.039    0.010 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\distributed\client.py:1387(submit)
        7    0.000    0.000    0.037    0.005 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\cloudpickle\cloudpickle.py:1112(dumps)
        7    0.000    0.000    0.037    0.005 C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\cloudpickle\cloudpickle.py:479(dump)
        7    0.000    0.000    0.037    0.005 C:\apps\Anaconda3\envs\img_proc3\lib\pickle.py:426(dump)
   2477/7    0.006    0.000    0.036    0.005 C:\apps\Anaconda3\envs\img_proc3\lib\pickle.py:485(save)
```
In our use case, **thread locks aren't required** since the data elements are independent.
The sum of all other execution time was a very acceptable 0.042 seconds (13.821 - 13.779).

Since the execution time of our typical list of functions operating on a 4096x4096 tile is approximately 0.5 to 2 seconds, the 6.75 seconds (3.5 + 2.25) Dask takes to get data to and from the workers is 3.4 to 13.5 times longer than the actual work being performed. Thus, often making the performance much worse than single thread execution. Overall performance was 1.13 to 4.17 times longer with Dask then without (comparing measured execution time of 0.5 sec tile operation single-threaded vs Dask, and ditto for 2 second operation).

For Dask to be useful in tiled image processing, can Dask provide a means to **turn-off thread-locking**, or greatly minimize it's performance impact?

Here is the Python source code that produces the above results:
[test_dask.py.txt](https://github.com/dask/dask/files/4028421/test_dask.py.txt)

**Comment by quasiben** [comment]
Have you looked at the dask subproject dask-image or the examples of efficient images processing with dask ?

- https://dask-image.readthedocs.io/en/latest/quickstart.html
- https://examples.dask.org/applications/image-processing.html

**Comment by mrocklin** [comment]
@tjorda01 I'm sorry that you've had a hard time.  

Profiling with the cProfile module unfortunately won't help you understand what is taking up time.  The cProfile module only really profiles sequential code.  For more information on profiling Dask I recommend reading through the following:

-  https://docs.dask.org/en/latest/understanding-performance.html
-  and in particular https://docs.dask.org/en/latest/diagnostics-distributed.html#capture-diagnostics

My guess is that either your custom object is expensive to serialize, or that your network is slow.  I don't know though without more information.  You might also want to read through https://blog.dask.org/2018/02/28/minimal-bug-reports on creating minimal bug reports.

Finally, you may not be aware, but your tone comes off as very negative.  This kind of tone is what causes maintainer burnout in open source projects.  While you are asking for help for free I recommend being aware of this.

**Comment by tjorda01** [comment]
@quasiben
Thanks for the links. Yes, I looked at them previously and at your suggestion reread them; here's what I found:
**quickstart.html** mentions `dask_image.imread`, which uses `pims` to read a glob-like string to match one or many filenames into a convenient `ImageSequence`. Our application needs to process geospatial images, so we need to also read the projection and geotransform with the pixel data. Unfortunately, `dask_image.imread` and `pims` doesn't support that. We're using `GDAL` to read images (in NITF, GeoTIFF, and JP2 formats). A combination of `rasterio`, `cv2 `and `glymur` could also be used.

Also, the large images that our application must process are single file images, and not separated into multiple files. So we can't make use of glob-like string to decompose a large image into chunks. That's one of the reasons why we have a pre-processing step that decomposes the read image data into 4096x4096 `numpy` arrays (or smaller if it can't be divided equally). The other reason is some image functions require an overlap between tiles. Does Dask Array support overlapping chunks? I didn't see that in the documentation, nor have I found a Python library to do that so we've incorporated it into our tiling code. 

**image-processing.html** shows a nice example of how to read a large image that already exists in separate files using `dask_image.imread` into a Dask Array. As mentioned before, `dask_image.imread` doesn't support geospatial image data, and our images aren't broken up into multiple files. We currently use `numpy` arrays for our pixel data, but I open to Dask Arrays if they support overlapping chunks.

**Comment by quasiben** [comment]
Dask Array does support overlapping chunks: `map_overlap`.  I recommend reading through https://docs.dask.org/en/latest/array-overlap.html

Are you familiar with the [xarray](http://xarray.pydata.org/en/stable/) project?

**Comment by tjorda01** [comment]
`map_overlap` looks very interesting, thanks for referring me to that. Looks like it does so by incurring '_costs (of) an excess copy and the communication of many small chunks_'. I'll make a JIRA story to evaluate the performance impact of that relative to operating on fixed numpy array tiles with the overlap built-in.

For image processing the xarray project may be useful for labeling arrays larger than 2D, to label the spectral bands, RGB bands, BGR bands, etc.

**Comment by tjorda01** [comment]
@mrocklin
I sincerely apologize if the tone of my bug report came off as negative. In fact, I'm a fan of Dask's clean and simple API, vast scalability, thorough documentation and flexibility of Dask Futures. That's why I chose to incorporate Dask.distributed and Dask Futures into our new high-performance Python image processing system.

I hope you're not put off by my saying "unacceptably slow to scatter/submit and gather", as it echoes the views of my project leaders and I'm having to defend Dask against that headwind. Although potentially a show stopper, I'm hopeful that a simple or relatively simple solution can be found to this issue. Because the alternatives for us are much less scalable or pretty ugly (i.e., potentially lots of custom distributed processing code that we'd much rather reuse from Dask, rather that write and maintain ourselves). Our expertise is image processing, not Python distributed processing.

Regarding cprofile. The cprofile data in my question only profiled the `for` loop containing the `client.scatter` and `client.submit` methods. I assumed that those only pertained to the scheduler and were sequential, not parallel. Is that correct?  If not, are you saying that the `cumtime` of 13.779 seconds that cprofile attributes to `{method 'acquire' of '_thread.lock' objects}` is bogus? I agree that cprofile may completely miss and not count metrics in forked processes, but would be surprised to learn that the data cprofile does report is wrong.

In any case I followed your suggestion and created a dask-report.html that includes all processing (see attached [dask-report.html.txt](https://github.com/dask/dask/files/4033143/dask-report.html.txt) ). Is there anything in that report that suggests how to speed up the scatter and gather?

I too suspected that serialization of the data objects was root cause of the performance bottleneck. However, when I tested that I found the combined serialization and deserialization time of a TilePkg, complete with a 4096x4096 numpy array, geotransform and projection information, was just 192 ms. So that suggests something else is going on. Could it be the network? I'm using a distributed.Client with a local cluster like this:
```
    cluster = LocalCluster()
    client = Client(address=cluster)
```
Please correct me if I'm wrong on any of the following...
So everything must be running on my local computer, therefore should be fast. However, distributed.Client is a web service, by default with this address '127.0.0.1:8786'. So when I call `client.scatter(datapkg)` I'm actually sending that data over TCP... using my ethernet card... which is 100 mbps (12.5 MBps). Therefore, a 4096x4096 numpy array of float64 is ~128MB and take 10.2 seconds (128/12.5) to get to the scheduler. Four of those should take a total of 41 seconds, but Dask is actually taking less time than that (13.8 seconds), so I'm not sure how to account for the difference.

**Comment by mrocklin** [comment]
Yeah, if you look at your performance report and look at either of the tabs "Scheduler Profile (administrative)" or "Worker Profile (administrative)" you'll find that all of the time is spent in functions like `tornado.iostream.read_from_fd` and `tornado.iostream.write_to_fd`.  These are the functions that handle the underlying network traffic.  

Your analysis that sending data from your local machine over a slow ethernet card seem to be consistent with this.

> I agree that cprofile may completely miss and not count metrics in forked processes, but would be surprised to learn that the data cprofile does report is wrong

cprofile only profiles the current thread.  The thread of where you run cprofile is just waiting on a bunch of other threads to finish up some work, and so you don't get any information about the other activity happening, either locally or on separate processes.  

You might try using `cluster = LocalCluster(processes=False)` to avoid network transfer, try things on a better network, or try to avoid scattering data from your local process to the workers.  See https://docs.dask.org/en/latest/best-practices.html#load-data-with-dask

**Comment by tjorda01** [comment]
@mrocklin
Thanks for your analysis and the suggestion to try `processes=False`. That turned out to be important for one of my test scenarios (see below).  Based on the collective advice from you and quasiben, and my subsequent performance testing, I'm fine with you closing this issue as "not a bug'.

FYI, here are the configurations that I tested and the results.
```
A:
cluster = LocalCluster(processes=True)
client = Client(address=cluster, direct_to_workers=True)

B:
cluster = LocalCluster(processes=False)
client = Client(address=cluster, direct_to_workers=True)

C:
from concurrent.futures import ProcessPoolExecutor
executor = ProcessPoolExecutor(n_workers)
```
It's assumed that Configuration A is preferred for distributed processing on a network cluster. However, all of my performance testing was on a single machine (Windows 10, Intel i7, 48 GB RAM, 100 mbps ethernet card) running Python code implementing a NDVI (Normallized Difference Vegetation  Index) algorithm with source imagery being the NIR and red bands of Sentinel-2 imagery (each 10980x10980 pixels).

**Results**
Scenario 1: When the NDVI function is implemented in regular unoptimized Python code (in this case two nested `for` loops), then C: is 15% faster than A: and B: is much worse taking 3.4 times longer than C:.

Scenario 2: When the NDVI function is implemented in optimized python (numpy, cython, numba @jit, numba @cuda.jit, etc.), then B: is by far the fastest - 12 times faster than C: and 40 times faster then A:. In fact, B: was the only one faster than sequential execution. It's worth noting that this test case was an extreme, given that the sequential execution of all image tiles was extremely fast, just 710 ms. Considering the overhead of each of the techniques, I though it unlikely that any could surpass it. Yet B: managed to be 30% faster (505 ms).

My conclusion is, for deployments to a single machine, our image processing framework will likely use a combination of Dask and ProcessPoolExecutor.

**Comment by quasiben** [comment]
Glad to hear it @tjorda01 and thank you for the detailed summary.

**Comment by mrocklin** [comment]
I recommend doing a web search for "ndvi pangeo" to find other examples of
other groups doing this same computation with Dask

**Comment by tjorda01** [comment]
Thanks. Looking into pangeo now... very interesting.
