### ISSUE TITLE
dask.dataframe.read_parquet producing empty columns for those partitioned on

### ISSUE THREAD

**Issue by caseyclements** [dask/dask#5773]
When using pyarrow as the engine in read_parquet, I'm encountering an error working with the columns on which I've partitioned.

If I select the column that I partitioned on, I get an empty series back.

I am using dask version ('2.8.1'), pyarrow ('0.15.1'), nd fastparquet ('0.3.2').
```
$ conda create -c conda-forge -n dask.arrow.issue -y dask fastparquet pyarrow jupyterlab python-snappy
```

To reproduce

```
import dask, pyarrow, fastparquet
(dask.__version__, pyarrow.__version__, fastparquet.__version__) # ('2.9.1', '0.15.1', '0.3.2')

import pandas as pd
import dask.dataframe as dd
import pyarrow.parquet as pq

df = pd.DataFrame([{'str': str(i), 'int':i, 'group': 'ABC'[i%3]} for i in range(6)])

pq_dir = './parquet_partition_issue'
df.to_parquet(pq_dir, partition_cols=['group'], engine='fastparquet')

ddf_arrow = dd.read_parquet(pq_dir, engine='pyarrow')
ddf_fast = dd.read_parquet(pq_dir, engine='fastparquet')

print(len(ddf_arrow['group'].compute()))  # 0
print(len(ddf_fast['group'].compute()))  # 6
print(len(ddf_arrow.compute().group))  # 6
print(len(pq.read_table(pq_dir).to_pandas().group))  # 6
```

**Comment by quasiben** [comment]
Thanks @caseyclements for the clear and reproducible example!   I am also seeing the error with master.  Unfortunately i don't know enough about the metadata handling differences between fastparquet and pyarrow.  @TomAugspurger or @martindurant do you have an idea of what's going on here ?

**Comment by martindurant** [comment]
(also @rjzamora )

**Comment by caseyclements** [comment]
Note that this problem still occurs if parquet is written using pyarrow. I did it this way explicitly because of another (perhaps related) issue: #5774

**Comment by rjzamora** [comment]
Thanks for raising @caseyclements - The problem was probably introduced in `optimize_read_parquet_getitem`.  The graph optimization will effectively use `columns=["group"]` for the `read_parquet` call, however a partition should *not* be specified as a column. 

I will confirm that this is the problem and see if I can find a reasonable fix.
