### ISSUE TITLE
workers die at 50% memory usage when calling persist()

### ISSUE THREAD

**Issue by RalphFS** [dask/dask#5778]
Hi!
My dask workers seem to die (restart) at quite exactly 50% memory usage. I first observed this behavior when creating the cluster via the Moab_Cluster function in the dask_jobqueue package but it also happens when creating a LocalCluster on a single compute node so I will describe it using this local cluster toy example.

1. I'm starting jupyter lab on a compute node with 32 cores and 128GB memory.

2. I run the following code in a jupyter notebook to create a local cluster on the current compute node:

```python
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(n_workers=1,threads_per_worker=32,\
                       processes=True, memory_limit='auto')
client = Client(cluster)
```

3. The dashboard (http://localhost:8787/workers) now shows me the correct values, i.e. 1 worker, 32 cores and 128GB RAM.
Using terminal commands like !free -m and !htop I can also verify that I actually have 128 GB RAM available.

4. Then I run the following python code and watch the Memory use in the dashboard:
```python
import dask.array as da
x = da.random.random((120000,120000),chunks=(12000,12000)) 
x = x.persist()
```

5. Dask then loads the data into memory, which I can observe from the "bytes stored" graph. But as soon as ~64GB are reached, it aborts and starts all over again. 
The output of this notebook cell is:
```python
distributed.nanny - WARNING - Restarting worker
```

If I select another compute node to run jupyter lab on, such as one with 192GB of RAM, the worker restarts at pretty much exactly 96GB Memory Usage (~50%).
I suppose that this behavior has to do with Dask, because the process is not killed by the OS but is instead just restarted by the dask nanny process. Creating the local cluster with nanny=False also didn't help.

**Comment by quasiben** [comment]
Thanks for the bug report @RalphFS .  Dask should be spilling to disk in normal operation.  Can you review your configuration file (typically located at `~/.config/ddask/distributed.yaml`) ?  Perhaps you have memory spilling turned off ?  Another thing to consider is memory limits set by the cluster ?  

As a note, in the dask-jobqueu docs, many of the cluster examples have spilling to disk disabled:
- https://jobqueue.dask.org/en/latest/configurations.html#cheyenne
- https://jobqueue.dask.org/en/latest/configurations.html#nersc-cori

**Comment by RalphFS** [comment]
thank you, I did not think about potential cluster memory limits. The distributed.yaml file looks fine : target:0.6, spill 0.7.  (workers still die when I turn that feature off.)
However, when I create a numpy random array like 
```python
x = np.random.random((120000,120000))
```
my kernel dies at 50% memory usage. So this behavior probably has nothing to do with dask but with the cluster. Spilling out to disk at 40% memory usage would probably be a workaround? Unfortunately, in this case I cannot use the full potential of the cluster. anyway, false alarm :)... sorry.

**Comment by quasiben** [comment]
You might want to ping folks on dask-jobqueue asking if they have come across these problems.  Better yet might be to post on stackoverflow ?

**Comment by TomAugspurger** [comment]
@RalphFS any updates here?

**Comment by RalphFS** [comment]
Hi Tom, @quasiben was right, there seem to be per-node-memory restrictions on the cluster I’m currently working on which are not related to dask. This issue can thus be closed. thanks for your support

**Comment by TomAugspurger** [comment]
Thanks for confirming!
