### ISSUE TITLE
Sending dask dataframe to elasticsearch

### ISSUE THREAD

**Issue by Rahul-Chittora** [dask/dask#5785]
I am trying to send dask dataframe to elasticsearch using [dask-elk](https://github.com/avlahop/dask-elk) python package by using the below mentioned command - 

```
from dask_elk.client import DaskElasticClient
client = DaskElasticClient(host='localhost', port = 9200)
chk = client.save(ddf, index_name , doc_type = 'FeatureCollection', action='index')
```

I have following questions:
1. Data isn't reflecting in elasticsearch. When i call chk.head() some data is shown on ES. How can I know that data is transferred.
2. Also, is there any other python library that I can use
3. Also, when I tried using map_partitions API of dask like 

```

#df_final is dask data frame
def toEs(data):
    client.save(data, index_name , doc_type = 'FeatureCollection', action='index')
    print('done') 

chk = df_final.map_partitions(lambda d: toEs)
```

This runs successfully but don't know the status.
I have checked on Kibana as well but data isn't reflecting.

I have to run the refresh API of elasticsearch, even then data isn't reflecting.

Also, I have tried sending partition using
```
from elasticsearch.helpers import bulk, parallel_bulk

def generate_parallel_obj(list_input):
    for data_dict in list_input:
        obj={
        '_op_type': 'index',
        '_index': index_name,
        '_type': '_doc',
        '_source': data_dict
        }
        yield(obj)

#features is <class 'dask.dataframe.core.Series'>

def toEs(data):
    slist = [row for row in data]
    pb = helpers.parallel_bulk(es, generate_parallel_obj(slist), thread_count=16,queue_size=8,max_chunk_bytes=10*1024*1024)
    deque(pb, maxlen = 0)
    es.indices.refresh(index=index_name)
    print('done')

chk = features.map_partitions(lambda data: toEs).compute(scheduler='processes')

  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
  File "/usr/lib/python3.6/socket.py", line 185, in __getstate__
    raise TypeError("Cannot serialize socket object")
TypeError: Cannot serialize socket object
```

**Comment by quasiben** [comment]
Interesting, i wasn't aware of the `dask-elk` project.  As, this issue seems fairly specific to dask-elk` have you asked them for help with regard to question 1?  

> 2. Also, is there any other python library that I can use

I am not aware of any other dask elk projects, sorry

For the following question, i would again ask the maintainers of the dask-elk project for help as I am unaware of the details

**Comment by TomAugspurger** [comment]
@Rahul-Chittora did you hear back from the dask-elk maintainers? Is there anything else to do here?

**Comment by Rahul-Chittora** [comment]
I haven't heard from them but I was able make it work. I have done the following:
For the first case:
Using dask-elk:
`client.save(data, index_name , doc_type = 'FeatureCollection', action='index').compute(scheduler='processes')`

For the second part, where I tried using parallel_bulk from elasticsearch, I made it work by doing the following changes to the code:

`
def generate_parallel_obj(list_input, index_name):
    for data_dict in list_input:
        obj={
        '_op_type': 'index',
        '_index': index_name,
        '_type': '_doc',
        '_source': data_dict
        }
        yield(obj)

def toEs(data, index_name):
    es = Elasticsearch('localhost:9200', timeout=60)
    pb = helpers.parallel_bulk(es, generate_parallel_obj(data, index_name), thread_count=16,queue_size=8,max_chunk_bytes=10*1024*1024)
    deque(pb, maxlen = 0)
    es.indices.refresh(index=index_name)

#features is a dictionary
features.map_partitions(toEs, index_name, meta = 'dask.dataframe.core.Series').compute(scheduler = 'processes')
`

**Comment by TomAugspurger** [comment]
Is this issue OK to close then?
