### ISSUE TITLE
Complex conjugate with cupy generates errors

### ISSUE THREAD

**Issue by YoujinShin** [dask/dask#5790]
When running this script, the following errors represented.
```javascript
import cupy as cp
import dask.array as da
A = cp.asarray(np.ones((10, 10))*5)
B = cp.asarray(np.ones((10, 10))*6)
A = da.from_array(A, chunks=A.shape)
B = da.from_array(B, chunks=B.shape)
C = A + 1j * B
C.conj().compute()
```

errors

> TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'conjugate'>, '__call__', array([[5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j],
       [5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j, 5.+6.j,
        5.+6.j, 5.+6.j]])): 'ndarray'

If I use Numpy, the errors do not appear. 
How can I use `dask.linalg.svd` with cupy array?
Thanks!

**Comment by TomAugspurger** [comment]
Does the operation work with just cupy (not dask?)

I notice that cupy doesn't implement `cupy.ndarray.conjugate` in https://docs-cupy.chainer.org/en/stable/reference/comparison.html, but does implement `conj`. We call `np.conjugate`. Do you know what the difference is?

**Comment by mrocklin** [comment]
cc @pentschev

**Comment by quasiben** [comment]
conj is an alias for conjugate

> In [4]: np.conj is np.conjugate
Out[4]: True

ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.conj.html

**Comment by pentschev** [comment]
Thanks @TomAugspurger and @quasiben for pointing the semantics already. I think it would make sense to rename that in CuPy, I filed https://github.com/cupy/cupy/issues/2967 to start a discussion.

In the meantime, I would second @TomAugspurger's suggestion on checking whether it's working properly _without_ Dask in the loop.

**Comment by TomAugspurger** [comment]
@YoujinShin any followup here? I think that `np.conjugate(cupy_array)` should be sufficient to reproduce the issue.

**Comment by TomAugspurger** [comment]
Closing this. Let us know if it's only reproducible with Dask @YoujinShin.
