### ISSUE TITLE
map_blocks multi-argument behavior 

### ISSUE THREAD

**Issue by aprowe** [dask/dask#5795]
Hello, 
Our pipeline a has a place where we pass in a 4D array and a 3D array into `dask.array.map_blocks`. Each array has chunks along the left-most axis, as a 'batch size' and the batch sizes are equal. For example
```
arr4d.chunks = ((16,16,16), (100,), (100,), (3,))
arr3d.chunks = ((16,16,16), (4,), (2,))
```

To Clarify, that results in: 
```
arr4d.shape = (48, 100, 100, 3) 
arr4d.chunksize = (16, 100, 100, 3) 

arr3d.shape = (48, 4, 2) 
arr3d.chunksize = (16, 4, 2) 
```

when we called `da.map_blocks(fn, arr4d, arr3d)` (or vice-versa) we expected the function to be called once for each 'batch' (in this example, 3 times). 
However, the resulting behavior was it was called 9 times. The graph reflects this, it has a product type of effect where each combination is called. 

We were eventually able to get the expected behavior by swapping the axis so our arrays look like this: 
```
arr4d.chunks = ((100,) (16,16,16), (100,), (3,))
arr3d.chunks = ((16,16,16), (4,), (2,))
```
Then, we have the correct graph and results. 

I can understand the reason for the behavior, but for our pipeline it causes a major inconvenience, since the left axis for us almost always the batch size. So we may pass 16 images in, and get 16 lower dimension feature sets. That 16 will always sit on the left side. This is causing us to make a hacky solution to add dimensions to the lower dimension array so, our arrays look like this: 
```
arr4d.chunks = ((16,16,16), (100,), (100,), (3,))
arr3d.chunks = ((16,16,16), (4,), (2,), (1,))
```

This works, but for our application is quite hacky, since we have to do this dynamically to not change a bunch of code. Our current solution detects the highest number of dimensions, adds extra dimensions, then wraps the supplied function to removed the extra dimensions before continuing. 

It seems `map_blocks` is aligning it arguments' axes based on a _right-justified_ alignment of their axes. For our application it makes sense to operate on a _left-justified_ alignment, so our arrays will always line up on the lowest-indexed axis. so if we pass in a `NxWxH` array, a `Nx1` array and a `NxWxHxC` array all into a `map_blocks` call, we can do so without extensive reshaping and axis work.

Couple Questions: 
1. Is this all correct? Am I misunderstanding?
2. Is there an easy solution I am missing?
3. Is this noted in the documentation somewhere? If not, let's add it!
 
Thanks!

**Comment by TomAugspurger** [comment]
Do you have a minimal example reproducing this? That'll help make the discussion concrete. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

> Is this noted in the documentation somewhere? If not, let's add it!

From glancing at the docstring, is this section relevant?

https://github.com/dask/dask/blob/370dbd2209f7710c51644262db5bfa49dc072ced/dask/array/core.py#L481-L496

**Comment by aprowe** [comment]
Here is a boiled down example:
```python
import dask.array as da

def fn(a, b):
    return a

# First array, 2x2, two 1x2 chunks
arr1 =  da.random.random((2,2), chunks=(1,2))

# Second array, 2x2x2, two 1x2x2 chunks
arr2 =  da.random.random((2,2,2), chunks=(1,2,2))

graph = da.map_blocks(fn, arr1, arr2)
graph.visualize('dask.png')
```
the resulting graph: 
![dask1](https://user-images.githubusercontent.com/7191456/72638019-1dd20680-3928-11ea-818d-2fbb62fd2825.png)

Now here is our desired behavior, which 
```python
import dask.array as da

def fn(a, b):
    return a

arr1 =  da.random.random((2,2), chunks=(1,2))

# Only change in code on this line
# Second array, 2x2x2, two 2x1x2 chunks
arr2 =  da.random.random((2,2,2), chunks=(2,1,2))

graph = da.map_blocks(fn, arr1, arr2)
graph.visualize('dask.png')
```
![dask2](https://user-images.githubusercontent.com/7191456/72638123-5c67c100-3928-11ea-967e-4428276c45e7.png)

As you can see, the first example produces a pretty complex graph. I understand it is sort of permuting the different chunks. 
It's a tiny difference in actual a code between the two, but it takes an ugly block of logic and wrappers to make this seamless in our codebase. We have always had the convention of having a consistent batch size on the left side of the array. 
A  `map_blocks(..., left_align=True, ...)` option would go a long way for us. 

That docstring definitely seems relevant. I think a more explicit description of this behavior would be great, but not sure how to sum it up exactly.

**Comment by TomAugspurger** [comment]
Thanks, that helps.

> That docstring definitely seems relevant. I think a more explicit description of this behavior would be great, but not sure how to sum it up exactly.

Happy to take improvements here!

I'm not sure, but I *think* that `blockwise` may be what you're looking for. It's what backs `map_blocks`, but will give you more control over how the blocks are stitched together: https://docs.dask.org/en/latest/array-api.html#dask.array.blockwise

**Comment by TomAugspurger** [comment]
@aprowe did you have a chance to look into blockwise? Does it solve your usecase?

**Comment by aprowe** [comment]
@TomAugspurger Haven't had time to dig in and understand exactly how to use blockwise. Right now we are using the work around I described (Add and remove axis to align before / after the operation). I do want to play with Blockwise to see if it can do what we need in a cleaner way.

**Comment by TomAugspurger** [comment]
@aprowe I opened https://github.com/dask/dask/pull/5874 to link from map_blocks to blockwise in the docs. I'm going to close this on the assumption that blockwise does what you want. LMK if I missed anything though.
