### ISSUE TITLE
Unclean multiprocessing.Pool teardown on Python 3.8

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#5806]
```python
import dask.array as da


def test1():
    x = da.from_array([1, 2])
    x.compute()
```
When running the above on Python 3.8, pytest 3.5.2, dask 2.9.2:
```
$ pytest test1.py
[...]
test1.py .                                                                           [100%]

============================================== 1 passed in 0.02s ===============================================
Exception ignored in: <function Pool.__del__ at 0x11c4304c0>
Traceback (most recent call last):
  File "/Users/crusaderky/miniconda3/envs/commrisk/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/Users/crusaderky/miniconda3/envs/commrisk/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```
The problem:
- remains if I explicitly state ``x.compute(scheduler='threading')``
- disappears if I state ``x.compute(scheduler='sync')``
- disappears if I downgrade to Python 3.7
- disappears if I run the test1() function as a plain python script, without pytest

**Comment by TomAugspurger** [comment]
> disappears if I run the test1() function as a plain python script, without pytest

I think pytest alters the default warnings config. When run with `-Werror` we see the same for

```python
import dask.array as da


x = da.from_array([1, 2])
x.compute()
```

output

```
$ python -Werror warn.py
Exception ignored in: <function Pool.__del__ at 0x108292f70>
Traceback (most recent call last):
  File "/Users/taugspurger/miniconda3/envs/dask-38/lib/python3.8/multiprocessing/pool.py", line 265, in __del__
ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=8>
```

**Comment by mrocklin** [comment]
So should we close the default thread pool (or all created thread pools)
with atexit?

**Comment by TomAugspurger** [comment]
Yep, that's what I was thinking.

**Comment by jakirkham** [comment]
It looks like we do call [`pool.close()`]( https://github.com/dask/dask/blob/95ab6ee80a51f85dae61d8761a88f3c42c9b2638/dask/multiprocessing.py#L225-L226 ) though. What am I missing?

**Comment by crusaderky** [comment]
Reproduced with the stdlib:
```python
import atexit
from multiprocessing import Pool


def test1():
    # Don't descope at the end of this function
    global p
    p = Pool(1)
    atexit.register(p.close)
```
Commenting out atexit.register makes it give out the same message.

**Comment by jakirkham** [comment]
Yep, I believe the finding that the pool is not being closed. What's less clear is why.
