### ISSUE TITLE
Is dask.linalg.svd_compressed basically the same as sklearn.utils.extmath.randomized_svd

### ISSUE THREAD

**Issue by georgeblck** [dask/dask#5811]
### Version Info

* `dask=2.9.2`
* `dask_ml=1.1.1`
* `sklearn=0.21.3`
* `python=3.7.4`

### TSVD implementations

The three different SVD/TSVD implementations I am talking about

* [sklearn.decomposition.TruncatedSVD](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html) which is just a wrapper around [sklearn.utils.extmath.randomized_svd](https://github.com/scikit-learn/scikit-learn/blob/b194674c42d54b26137a456c510c5fdba1ba23e0/sklearn/utils/extmath.py#L244)
* [dask.array.linalg.svd_compressed](https://docs.dask.org/en/latest/array-api.html#dask.array.linalg.svd_compressed), source code [here](https://github.com/dask/dask/blob/a27f111b7bd327ad74bc2aff088e30de91ecf7df/dask/array/linalg.py#L686)
* [dask_ml.decomposition.TruncatedSVD](https://ml.dask.org/modules/generated/dask_ml.decomposition.TruncatedSVD.html?highlight=svd#dask-ml-decomposition-truncatedsvd)  , source code [here](https://github.com/dask/dask-ml/blob/ff1b0af3af25080b12dd2f194d041db489505463/dask_ml/decomposition/truncated_svd.py#L8)

### The story

My numpy array is too large in general, and especially for the **sklearn**-TSVD. So I have been using dask and spent some time looking at the differences between the SVD implementations. First, I tried to use the **dask_ml**-TSVD; but it does not work with short-and-fat arrays. This led me to the general **dask**-SVD which *does* general non-skinny arrays but *does not* truncate the SVD.

Through looking at the source code I realized there were a lot similarities between the **sklearn.randomized_svd** and **dask.array.linalg.svd_compressed**. They both also cite the same [paper](https://arxiv.org/abs/0909.4061) for their algorithm. 

### The question

Are the **svd_compressed** and the **randomized_svd** implementation the same?
I am not well versed in python or math, so it is hard for me to judge if they are. If they were the same, I could just manually truncated the output of **dask.array.linalg.svd_compressed** to get the TSVD.

In any case: thanks a lot for the dask-packages, they have been a great help.

**Comment by TomAugspurger** [comment]
I'm not sure what algorithm `sklearn.randomized_svd` uses, but it may well be the same as the one dask / dask-ml uses. That said, the implementation is quite different. The Dask version works with Dask arrays, so will scale out to larger arrays (out of core on a single machine, or distributed on many machines).

**Comment by georgeblck** [comment]
I am very sorry, I should have looked at the dask-ml code more closely.

If passed the `algorithm='randomized'` option, it uses the `da.linalg.svd_compressed`-algorithm in the same way that the `sklearn.TruncatedSVD` uses the `randomized_svd`.

More importantly, only when this algorithm is chosen does the TruncatedSVD work with non-skinny arrays. So I have found what I've been looking for.

**Comment by jrbourbeau** [comment]
>  I have found what I've been looking for

Great, glad to hear it. Thanks for asking @georgeblck
