### ISSUE TITLE
Dask dataframe `read_csv` does not expand user home directory ("~") in path.

### ISSUE THREAD

**Issue by haje01** [dask/dask#5819]
This is really small problem, but better to report.

Dask dataframe `read_csv` does not expand "~" in path. I confirmed it in macOS & Ubuntu.

My Environment:
* Python: 3.7.2
* Dask: 2.9.0

Imagine my current working directory is `~/works`, and I try to read `test.csv` from my home directory:

```python
from dask import dataframe as dd

dd.read_csv('~/test.csv')
```

Result:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-8f41e376b7b0> in <module>()
----> 1 dd.read_csv('~/test.csv')

~/anaconda3/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    576             storage_options=storage_options,
    577             include_path_column=include_path_column,
--> 578             **kwargs
    579         )
    580 

~/anaconda3/lib/python3.6/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    403         compression=compression,
    404         include_path=include_path_column,
--> 405         **(storage_options or {})
    406     )
    407 

~/anaconda3/lib/python3.6/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)
    119                     "To read, set blocksize=None"
    120                 )
--> 121             size = fs.info(path)["size"]
    122             if size is None:
    123                 raise ValueError(

~/anaconda3/lib/python3.6/site-packages/fsspec/implementations/local.py in info(self, path, **kwargs)
     54     def info(self, path, **kwargs):
     55         path = self._strip_protocol(path)
---> 56         out = os.stat(path, follow_symlinks=False)
     57         dest = False
     58         if os.path.islink(path):

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/works/~/test.csv
```

`FileNotFoundError` directs unexpanded home path `/home/ubuntu/works/~/test.csv`

Pandas reads without problem:
```
import pandas as pd

pd.read_csv('~/test.csv')
```

Results:
```
   id  name   score
0   0   kjj     100
1   1   jji      80
2   2   kbj      70
```

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @haje01. Matching pandas here seems reasonable. Dask uses `fsspec` for a large portion of it's file I/O operations. I think updating [`fsspec.utils.stringify_path`](https://github.com/intake/filesystem_spec/blob/7135be86ef9a95edff8f51d15508d08da119cc9d/fsspec/utils.py#L278) to use `os.path.expanduser` would allow for this (that would make it very similar to pandas' `stringify_path` utility function). @martindurant do you think that makes sense for `fsspec`?

**Comment by martindurant** [comment]
Yep, could be done, but note that this only *should* be done for local file paths, so maybe it makes more sense to limit to the LocalFileSystem implementation. Does `expanduser` do the right thing for escaped `"~"` characters that are part of a real file name?

**Comment by jrbourbeau** [comment]
Limiting to `LocalFileSystem` seems like the right thing to do. I opened up https://github.com/intake/filesystem_spec/pull/233 to add the user home directory expansion. `os.path.expanduser` only replaces leading `~` and `~user` in a path. So any escaped `~` characters wouldn't be impacted

**Comment by jrbourbeau** [comment]
@haje01 `fsspec` has been updated to expand user home directories. Updating to the next release once it's out should resolve this issue. In the meantime, if you'd like you can install the development version with 

```
pip install git+https://github.com/intake/filesystem_spec.git
```
