### ISSUE TITLE
map_overlap graph has floating point keys

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#5824]
I am using `map_overlap` and noticed the graph contains floating point keys.  I saw this while troubleshooting performance, and I'm not sure if it's related.  I thought perhaps the floating point might induce some sort lookup or cache miss.  (I *think* I'm seeing a lot more tasks being computed in my scheduler status window than are reported being done.)

It's simple to see in the following with a small array.  And if I make the array dimensionality larger, things get big very fast.  But it's the floating points that worry me more than graph size (I understand overlaps are expensive).

```
# Using dask==2.9.2
import dask.array as da
da.zeros((10,)).map_overlap(lambda x: x, depth=1).visualize()
```

With shape 10:
![download](https://user-images.githubusercontent.com/1053153/73025657-d397cc00-3de4-11ea-990c-77d1e59f3035.png)

With shape 10,10
![download (1)](https://user-images.githubusercontent.com/1053153/73025698-e27e7e80-3de4-11ea-83a3-54a7c1e2b866.png)

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @chrisroat. I think those `getitem` keys are constructed in this block of code:

https://github.com/dask/dask/blob/f4d90c9faa01dc4117c68530f0a9f1b6645ae873/dask/array/overlap.py#L132-L145

Is this something you're interested in looking into? (definitely no obligation though)

**Comment by chrisroat** [comment]
Happy to learn a little more about this.  Can you describe how the key values are used, and that having floating point rounding issues could be concern?

**Comment by jakirkham** [comment]
Yeah the floating point values are intentional. They indicate how much of the neighboring parent chunks are used. One can thinking of this as a percentage of overlap with neighbors.

**Comment by chrisroat** [comment]
Are there ever comparisons done using these keys?

**Comment by jakirkham** [comment]
How do you mean?

**Comment by chrisroat** [comment]
For example, are these keys used for lookups or equality checks?  I'm
curious if floating point comparisons can cause something to go awry.

I noticed a possible memory leak in the scheduler, and my test was using
map_overlap.  I had originally thought maybe these floating point keys
could have been orphaned because of some bad comparison.  However, I see a
memory increase even using straight map_blocks.

**Comment by jakirkham** [comment]
So the thought is repeating decimals might be an issue or floating point values generally?

If the former, it seems pretty simple to change the overlap size such that a non-repeating fraction is produced (like `0.5`). If the latter, it's also possible to ensure boundaries include full neighboring chunks. Though IDK if it forces `float`s to `int`s in the latter case, so there may need to be some tweaking the graph to get the desired outcome. Both of these maintain the data dependency issues in the same way. So it should either reproduce the issue or point to `float`s as the problem.

That said, I suspect this is unlikely. Dask uses `tuple`s with keys precisely because they are immutable. So once Dask has produced a key, it can reuse that key over and over. All the while remaining confident that its contents have not changed and therefore it points to the same value.

That all being said, it seems straightforward to explore and I could always be wrong here. Would certainly be good to fix a memory leak and anything that gets us closer to identifying the cause would help 🙂

**Comment by chrisroat** [comment]
Because I see the memory increase for map_blocks, as well, I also don't think the floating point is the issue.

(My worry on floating point was that if two different parts of the code tried to create the same floating point number, but perhaps did it differently, then a comparison between the two might not show equality.)

We could leave this issue open with the idea of visualizations having repeating numbers truncated for display purposes.

**Comment by jakirkham** [comment]
Thanks for the update. Yeah it agree it sounds unrelated then.

That's the only part of the code that I'm aware of generating such values. Maybe there is something similar on the Dataframe side? Anyways I think risk here is low as one basically only needs these for overlaps, which goes through the same code path.

Sure so what would you like to see on the visualization side then?

**Comment by chrisroat** [comment]
It looks like the [box_label](https://github.com/dask/dask/blob/7138f470f0e55f2ebdb7638ddc4dfe2e78671403/dask/dot.py#L107) function is responsible for the text.  Would it be appropriate for float values to be truncated at 1 sig fig?  Are more sig figs ever used?

**Comment by jakirkham** [comment]
I guess that really depends on the kind of fraction we are looking at 🙂

**Comment by chrisroat** [comment]
It looks to me that it's always 0.1 or 0.9 in these cases.

And in looking a bit into the memory leak I'm seeing, I do see some of the code in overlap getting flagged.  Leaks from tracemalloc below.  The first dask/array/overlap line shown is in a function called `fractional_slice`!  I see the scheduler report a growth in memory of 1 GB, so these leaks aren't even close to the problem I see.  But it's intriguing.

```
import tracemalloc
tracemalloc.start()

import dask.array as da
import distributed

client = distributed.Client(n_workers=4, threads_per_worker=1, memory_limit='10GB')

arr = da.zeros((50, 2, 8192, 8192), chunks=(1, -1, 512, 512))
result = arr.map_overlap(lambda x: x, depth=(0,0,200,200))
store = result.to_zarr('/media/ssd/test/memory_scheduler.zarr', compute=False, overwrite=True)

future = client.compute(store)

client.restart()  # We want everything to go back to normal.

snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')

for stat in top_stats[:20]:
    print(stat)
```

```
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/protocol/core.py:199: size=31.5 MiB, count=220386, average=150 B
/home/croat/dask/dask/array/overlap.py:35: size=25.6 MiB, count=411585, average=65 B
<frozen importlib._bootstrap_external>:525: size=19.9 MiB, count=190477, average=110 B
/home/croat/dask/dask/array/overlap.py:112: size=16.5 MiB, count=183800, average=94 B
/home/croat/dask/dask/array/overlap.py:57: size=16.1 MiB, count=223573, average=76 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:2057: size=15.3 MiB, count=99999, average=161 B
/home/croat/dask/dask/array/overlap.py:48: size=12.4 MiB, count=180207, average=72 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:4723: size=10.9 MiB, count=137218, average=83 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:4744: size=10.6 MiB, count=96661, average=115 B
/home/croat/dask/dask/array/optimization.py:121: size=10.0 MiB, count=1, average=10.0 MiB
/home/croat/dask/dask/array/overlap.py:145: size=9641 KiB, count=102840, average=96 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:4713: size=9221 KiB, count=54710, average=173 B
/home/croat/dask/dask/array/overlap.py:52: size=8693 KiB, count=177658, average=50 B
/home/croat/dask/dask/array/optimization.py:191: size=8231 KiB, count=105361, average=80 B
/home/croat/dask/dask/array/overlap.py:50: size=7290 KiB, count=103675, average=72 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:2055: size=6600 KiB, count=25601, average=264 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:3949: size=5817 KiB, count=25745, average=231 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:655: size=5801 KiB, count=25604, average=232 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:653: size=5800 KiB, count=25603, average=232 B
/home/croat/dask/.venv/lib/python3.7/site-packages/distributed/scheduler.py:4701: size=5800 KiB, count=25601, average=232 B
```

**Comment by chrisroat** [comment]
I'm not finding the floating points being the real problem behind the memory issues I encounter.  

This had been a hypothesis based on a) floating point comparison can be an issue and b) initial suspicions based on memory leak investigations.

**Comment by jakirkham** [comment]
There have also been some improvements to memory usage in recent versions (though there is probably still more work to do there)

**Comment by chrisroat** [comment]
I have noticed the work on worker memory (woot!).  The problem that led me to create this issue was scheduler memory -- I thought some tasks might possibly have been lingering in-memory somehow due to a floating point comparison.
