### ISSUE TITLE
Deprecation warning over invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [dask/dask#5829]
Deprecation warning over invalid escape sequence. Using raw string or escaping would fix the issue. This is a good beginner issue.

```
$ find . -iname '*.py'  | xargs -P 4 -I{} python3.8 -Wall -m py_compile {}

./versioneer.py:485: DeprecationWarning: invalid escape sequence \s
  LONG_VERSION_PY['git'] = '''
```

Thanks for Dask :)

**Comment by TomAugspurger** [comment]
Thanks for the report. These are coming from versioneer. It's been reported at https://github.com/warner/python-versioneer/issues/201.

I think we'll close this, and update our copy when versioneer is updated.
