### ISSUE TITLE
Dask Groupby does not generate correct sum results for grouping variables that are pd.Categorical

### ISSUE THREAD

**Issue by DigitalPig** [dask/dask#5838]
Here is the minimal replicable code:

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np

test = pd.DataFrame(
{
    'col1': ['A', 'B', 'C', 'A'],
    'col2': np.random.randint(0,100, size=4),
    'col3': [12,32,23,22]
})

print("---Initial DataFrame---")
print(test)

test2 = dd.from_pandas(test.copy(), npartitions=2)

test2['col2'] = test2['col2'].map_partitions(pd.cut, [0,50,100])

print("---Dask Results")
print(test2.groupby(['col1', 'col2']).sum().compute())
print("---Dask dtype---")
print(test2['col2'].dtype)


test['col2'] = pd.cut(test['col2'], [0,50,100])
print("---Pandas Results---")
print(test.groupby(['col1', 'col2']).sum())
```

Pandas give the correct results, for column combinations that does not have data, the sum is NaN. Dask gives 0 for those sums, which are incorrect.

<img width="206" alt="Screen Shot 2020-01-28 at 16 34 36" src="https://user-images.githubusercontent.com/97392/73307532-5efdcc80-41ec-11ea-940b-c952b836ff5f.png">

**Comment by TomAugspurger** [comment]
IIUC, the pandas results are incorrect. Pandas defines the sum of an empty array to be 0, but is returning NaN here.

Indeed when grouping by a 1-level grouper, pandas returns 0

```python
In [20]: pd.Series([1, 1, 1]).groupby([pd.Categorical(['a', 'a', 'a'], categories=['a', 'b'])]).sum()
Out[20]:
a    3
b    0
dtype: int64
``` 

but when grouping by multiple levels, you get NaN instead

```python
In [21]: pd.Series([1, 1, 1]).groupby([['a', 'a', 'a'], pd.Categorical(['a', 'a', 'a'], categories=['a', 'b'])]).sum()
Out[21]:
a  a    3.0
   b    NaN
dtype: float64
```

@DigitalPig are you interested in submitting an issue report to pandas?

**Comment by TomAugspurger** [comment]
Closing this in favor of the upstream pandas issue.
