### ISSUE TITLE
Naive implementation for divisions when reading sql

### ISSUE THREAD

**Issue by CJ-Wright** [dask/dask#5843]
Would it be possible to provide a naive approach for reading up sql tables where the index is of type "O"? We know what the max and min values are so we could push them all into one division. While this is less than ideal it seems that picking the divisions requires more knowledge of the table than may be available if reading for the first time.

I guess more advanced heuristics could be produced, for instance if the index is alphabetic, try to use one division per letter. One could then warn that the loading may be suboptimal and that the user should provide divisions for better performance.

**Comment by jakirkham** [comment]
@mariusvniekerk, what do you think about this idea? 🙂

**Comment by TomAugspurger** [comment]
I don't think we should special case object dtype here. If this is important for the user, they should opt into it by providing divisions.

**Comment by mrocklin** [comment]
OK, this has gone stale.  I'm going to close this out.  Thanks @CJ-Wright for raising.
