### ISSUE TITLE
KeyError: 'index' when appending to an existing DataFrame

### ISSUE THREAD

**Issue by gvelchuru** [dask/dask#5846]
Running the following snippet (with a public s3 bucket) gives me a KeyError:
```
import dask.dataframe as df
import pandas as pd
x = df.read_parquet("s3://tmp-th/target_related")
y = x.tail(compute=True)
df.from_pandas(y, npartitions=1).to_parquet("s3://tmp-th/target_related", append=True)
```

**Comment by TomAugspurger** [comment]
Can you provide a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by gvelchuru** [comment]
I found the issue, my parquet file wasn't playing well with a timestamp-based index, I switched to string
