### ISSUE TITLE
pip install dask==2.9.2 installs distributed 2.10.0

### ISSUE THREAD

**Issue by StianOvrevage** [dask/dask#5849]
I have installed dask into a Kubernetes cluster with helm. (This will install 2.9.2 since 2.10.0 is not yet available on Docker image or the Helm chart).

This causes Dask to fail because of incompatible versions:
```
distributed
+--------------------------+---------+
|                          | version |
+--------------------------+---------+
| client                   | 2.10.0  |
| scheduler                | 2.9.2   |
```

I have tried 5 ways of pinning the dask version, such as

```
pip3 install "dask[distributed]"==2.9.2
```

But no matter what I end up with distributed version `2.10.0` in `cat ./env/lib/python3.6/site-packages/distributed/_version.py`

I could probably get around this by using the local scheduler but dask will not talk to my Kubernetes cluster either...

**Comment by TomAugspurger** [comment]
Is pip not uninstalling the dask / distributed installed by conda?

**Comment by StianOvrevage** [comment]
I'm not using conda.

```
$ conda
conda: command not found
```

**Comment by TomAugspurger** [comment]
Mmm I assumed that since you're using kubernetes you were starting from a dask-docker image.

**Comment by StianOvrevage** [comment]
It's running on my local machine.

**Comment by jrbourbeau** [comment]
I think this is coming from our version restriction in `setup.py` only specifying a lower bound on the allowed version of `distributed`. 

https://github.com/dask/dask/blob/ed3895a1b61bfc930aff98cb2aabc685d18c1b66/setup.py#L25

A workaround would be to pin both `dask` and `distributed` 

```
pip install dask==2.9.2 distributed==2.9.2
```

**Comment by StianOvrevage** [comment]
That actually worked, thanks!
