### ISSUE TITLE
FeatureRequest: read_sql_table in ThreadPool

### ISSUE THREAD

**Issue by cgi1** [dask/dask#5858]
Dask is a nice project. Thanks.

I would like to do an enhancement request for speeding up loading time of big tables from postgresql (or any other DB). This is why I noticed that you load the `divisions` sequently in [here](https://github.com/dask/dask/blob/master/dask/dataframe/io/sql.py#L189). 

Which works, but boy, it is slow... No one likes waiting... So I thought that it would be a good idea to do this in parallel in order to enable that invokement of more database processes. 

I think it should work fine with an easy `ThreadPoolExecutor`, something like the code below, but I am new to the Dask code, so I do not know yet how you people handle parallel processing within the code. Happy for advice - lets look for some code:

```
with ThreadPoolExecutor(max_workers=max_threads) as executor:

    futures_to_todo = []
    for div in divisions:
        futures_to_todo.append(executor.submit(fn=sql_select_in_own_function, div=div, index=index, lower=lower, cond=cond))

    wait(futures_to_todo)

```

**Comment by jakirkham** [comment]
Maybe we should be moving the SQL logic into `delayed` as well. Do you see any good ways to do that?

**Comment by mrocklin** [comment]
It looks like that code currently makes a bunch of lazy queries and then
puts those into a dataframe.  If that dask dataframe is computed with a
parallel scheduler then I believe that they will be executed in parallel.

**Comment by jakirkham** [comment]
I think the OP is concerned about [this line]( https://github.com/dask/dask/blob/b3d2c2c50f24a9522c10528d9ee3f529492b3cef/dask/dataframe/io/sql.py#L191 ), which is not lazy, but I could be misunderstanding things here. Additional clarifications would be welcome 🙂

**Comment by mrocklin** [comment]
I believe that that line constructs a lazy sqlalchemy query.  I don't know
for sure though (I don't know sqlalchemy well any more).  I recommend
quickly checking the semantics of sqlalchemy queries.

**Comment by jakirkham** [comment]
Fair enough. @cgi1, have you already looked at [this]( https://docs.dask.org/en/latest/setup/single-machine.html#selecting-threads-processes-or-single-threaded )?

**Comment by TomAugspurger** [comment]
@cgi1 any updates here?

**Comment by mrocklin** [comment]
I think that the premise of this issue is incorrect.  The assumption was that we load divisions sequentially.  We actually don't do this.  Closing.
