### ISSUE TITLE
Ordering changes negatively affecting memory use

### ISSUE THREAD

**Issue by JSKenyon** [dask/dask#5859]
I will attempt to follow this report up with an example. I encountered this behaviour in a relatively complicated example and replicating it in a simpler case is eluding me. I am using dask (2.9.1/2.10.1, see remainder of post), distributed 2.10.0 and Python 3.6.9.

My specific problem involves reading large amounts of data from disk, processing it in independent chunks and then writing the results to disk again. Prior to dask 2.9.2 the memory usage of my code behaved as expected, exhibiting a typical heartbeat pattern as data was read - processed - written.

Post dask 2.9.2, the above is no longer the case and the maximum memory footprint has increased, often substantially. I believe that this is a result of changes to dask.order.order made [here](https://github.com/dask/dask/commit/c63dc149210d45cbf90bb3f9d5a56106339ac24c). 

As an example of what I believe is causing this behaviour, consider the following graph: 
```
   E          # Write operation.
   |   
   C D        # C: Additional computation. D: Write operation. 
   |/
   B          # Computation producing two outputs.
   |
   A          # Read operation.
```
dask.compute is then called on `[D, E]`. In my head (and in the past), this has worked to write two data products to disk per input chunk without growing extensively in memory. However, as of 2.9.2, it seems that the scheduler is no longer giving priority to node `D`. The result is that all those write operations are being kept in memory until every node `E` is completed.  This does not seem like desirable behaviour. 

There is one additional peculiarity - this memory growth is only evident when using the distributed scheduler. I cannot think of any explanation for this as its version was unchanged across my tests.

To boil it down - has anyone else experienced similar changes in behaviour? Is it plausible that changes to ordering could have this effect? Finally, does anyone have any advice for producing an MRE?

**Comment by eriknw** [comment]
Thanks for the report.  `D` is definitely given priority in `order` (both before and after the change).  In fact, the new `order` will never leave a single task like `D` dangling before moving on (the previous version would sometimes do this).  I will need to see a more complete example to see whether `order` is behaving poorly.  It could indeed be something specific with the distributed scheduler and how it interacts with the order of tasks.

Have you tried running with the serial scheduler (`dask.get`)?

**Comment by JSKenyon** [comment]
Thanks for the reply @eriknw. I have tried running with the single-threaded scheduler via compute, which I think is equivalent to `dask.get`. My experiments show that there is memory growth in the serial case too, which I had previously missed. 

I have also confirmed that it was [this commit](https://github.com/dask/dask/commit/c63dc149210d45cbf90bb3f9d5a56106339ac24c) that introduced the change - I installed from source and retested with HEAD at [this commit](https://github.com/dask/dask/commit/5db6dad7947f186a9764cdf409b8f50bf7c38f22), the one directly preceding the ordering changes. There was no memory growth at that point. 

In terms of a specific example, I am still trying. Unfortunately `order` for my code contains around 210 keys per input chunk. It makes it somewhat difficult to identify the precise degree of complexity which triggers my problem.

**Comment by JSKenyon** [comment]
I have managed to get rid of the memory growth by removing some of the fields from the xarray.Datasets which are written to disk. This gives me a little more insight into where the problem is. Hopefully I can get a little close to a reproducible example now.

**Comment by JSKenyon** [comment]
I have been digging further into the problem. Unfortunately I feel like I may be further away from a reproducible example than before. As I mentioned in the original post, I call compute on the two write operations `[D, E]`. I have tested both `D` and `E` independently and neither exhibit the memory growth problem. Calling compute on `[D, E]` exposes the problem, which I think suggests that the dependencies/orderings are being combined sub-optimally.

**Comment by JSKenyon** [comment]
I have saved the results of the call to `order` before and after the changes. The dictionary has 3502 keys. 
Writing an xarray.Dataset to disk produces keys which start with `_finalize_store`. Below are the values associated with all `_finalize_store` operations before and after the ordering change:

```
Before:
[ 212,  256,  420,  506,  592,  678,  764,  850,  936, 1025, 1111,
 1197, 1278, 1364, 1450, 1536, 1622, 1708, 1794, 1880, 1966, 2052,
 2138, 2224, 2310, 2396, 2482, 2492, 2502, 2590, 2678, 2845, 2929,
 2939, 3104, 3190, 3276, 3286, 3417, 3461]
After:
[ 858,  940,  988, 1036, 1084, 1132, 1180, 1228, 1276, 1324, 1372,
 1420, 1468, 1516, 1564, 1612, 1660, 1708, 1756, 1804, 1852, 1900,
 1948, 1996, 2044, 2092, 2140, 2542, 2590, 2638, 2686, 2734, 2782,
 2830, 2878, 2926, 2974, 3022, 3070, 3118]
```

If I am interpreting the above correctly, the new ordering waits a very long time before writing the results of the first chunk to disk. Another thing I found interesting is the non-uniform spacing between `_finalise_store` values (computed as `A[1:] - A[:-1]`):
```
Before:
[ 44, 164,  86,  86,  86,  86,  86,  86,  89,  86,  86,  81,  86,
 86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,
 10,  10,  88,  88, 167,  84,  10, 165,  86,  86,  10, 131,  44]
After:
[ 82,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,
  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,
 402,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48,  48]
```
Prior to the ordering changes, the spacing is less uniform but is consistent with being more evenly spread throughout the ordering dict. With the new ordering spacing is very uniform but there seems to be one fairly extreme outlier.

This behaviour carries over to the other write operation too. 
```
Before:
      [  21,   22,   25,   27,   98,   99,  102,  104,  126,  141,  142,
        145,  147,  168,  272,  273,  276,  278,  334,  349,  350,  353,
        355,  376,  435,  436,  439,  441,  462,  521,  522,  525,  527,
        548,  607,  608,  611,  613,  634,  693,  694,  697,  699,  717,
        779,  780,  783,  785,  803,  865,  866,  869,  871,  892,  939,
        954,  955,  958,  960,  978, 1040, 1041, 1044, 1046, 1064, 1126,
       1127, 1130, 1132, 1150, 1207, 1208, 1211, 1213, 1231, 1293, 1294,
       1297, 1299, 1320, 1379, 1380, 1383, 1385, 1406, 1465, 1466, 1469,
       1471, 1489, 1551, 1552, 1555, 1557, 1575, 1637, 1638, 1641, 1643,
       1664, 1723, 1724, 1727, 1729, 1747, 1809, 1810, 1813, 1815, 1833,
       1895, 1896, 1899, 1901, 1919, 1981, 1982, 1985, 1987, 2008, 2067,
       2068, 2071, 2073, 2091, 2153, 2154, 2157, 2159, 2177, 2239, 2240,
       2243, 2245, 2263, 2325, 2326, 2329, 2331, 2352, 2411, 2412, 2415,
       2417, 2435, 2518, 2519, 2522, 2524, 2546, 2606, 2607, 2610, 2612,
       2668, 2700, 2701, 2704, 2706, 2774, 2775, 2778, 2780, 2801, 2848,
       2858, 2859, 2862, 2864, 2919, 2956, 2957, 2960, 2962, 3018, 3033,
       3034, 3037, 3039, 3060, 3119, 3120, 3123, 3125, 3146, 3205, 3206,
       3209, 3211, 3232, 3308, 3309, 3312, 3314, 3336, 3346, 3347, 3350,
       3352, 3373]
After:
      [  15,   35,   49,   63,   77,   91,  105,  119,  133,  147,  161,
        175,  189,  203,  217,  231,  245,  259,  273,  287,  301,  315,
        329,  343,  357,  371,  385,  402,  419,  436,  453,  470,  487,
        504,  521,  538,  555,  572,  589,  606,  623,  640,  657,  674,
        691,  708,  725,  742,  759,  776,  793,  810,  860,  862,  865,
        892, 2169, 2198, 2227, 2253, 2279, 2305, 2331, 2360, 2388, 2414,
       2440, 2468, 2494, 3120, 3122, 3125, 3127, 3129, 3132, 3134, 3136,
       3139, 3141, 3143, 3146, 3148, 3150, 3153, 3155, 3157, 3160, 3162,
       3164, 3167, 3169, 3171, 3174, 3176, 3178, 3181, 3183, 3185, 3188,
       3190, 3192, 3195, 3197, 3199, 3202, 3204, 3206, 3209, 3211, 3213,
       3216, 3218, 3220, 3223, 3225, 3227, 3230, 3232, 3234, 3237, 3239,
       3241, 3244, 3246, 3248, 3251, 3253, 3255, 3258, 3260, 3262, 3265,
       3267, 3269, 3272, 3274, 3276, 3279, 3281, 3283, 3286, 3288, 3290,
       3293, 3298, 3300, 3303, 3305, 3310, 3312, 3315, 3317, 3322, 3324,
       3327, 3329, 3334, 3336, 3339, 3341, 3346, 3348, 3351, 3353, 3358,
       3360, 3363, 3365, 3370, 3372, 3375, 3377, 3382, 3384, 3387, 3389,
       3394, 3396, 3399, 3401, 3406, 3408, 3411, 3413, 3418, 3420, 3423,
       3425, 3430, 3432, 3435, 3437, 3442, 3444, 3447, 3449, 3454, 3456,
       3459, 3461]
```
Before the ordering changes the writes were evenly spread across the ordering. Now they are highly concentrated. Once again computing `A[1:] - A[:-1]` for these writes:
```
Before:
      [  1,   3,   2,  71,   1,   3,   2,  22,  15,   1,   3,   2,  21,
       104,   1,   3,   2,  56,  15,   1,   3,   2,  21,  59,   1,   3,
         2,  21,  59,   1,   3,   2,  21,  59,   1,   3,   2,  21,  59,
         1,   3,   2,  18,  62,   1,   3,   2,  18,  62,   1,   3,   2,
        21,  47,  15,   1,   3,   2,  18,  62,   1,   3,   2,  18,  62,
         1,   3,   2,  18,  57,   1,   3,   2,  18,  62,   1,   3,   2,
        21,  59,   1,   3,   2,  21,  59,   1,   3,   2,  18,  62,   1,
         3,   2,  18,  62,   1,   3,   2,  21,  59,   1,   3,   2,  18,
        62,   1,   3,   2,  18,  62,   1,   3,   2,  18,  62,   1,   3,
         2,  21,  59,   1,   3,   2,  18,  62,   1,   3,   2,  18,  62,
         1,   3,   2,  18,  62,   1,   3,   2,  21,  59,   1,   3,   2,
        18,  83,   1,   3,   2,  22,  60,   1,   3,   2,  56,  32,   1,
         3,   2,  68,   1,   3,   2,  21,  47,  10,   1,   3,   2,  55,
        37,   1,   3,   2,  56,  15,   1,   3,   2,  21,  59,   1,   3,
         2,  21,  59,   1,   3,   2,  21,  76,   1,   3,   2,  22,  10,
         1,   3,   2,  21]
After:
      [  20,   14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
         14,   14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
         14,   14,   14,   14,   17,   17,   17,   17,   17,   17,   17,
         17,   17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
         17,   17,   17,   17,   17,   17,   17,   50,    2,    3,   27,
       1277,   29,   29,   26,   26,   26,   26,   29,   28,   26,   26,
         28,   26,  626,    2,    3,    2,    2,    3,    2,    2,    3,
          2,    2,    3,    2,    2,    3,    2,    2,    3,    2,    2,
          3,    2,    2,    3,    2,    2,    3,    2,    2,    3,    2,
          2,    3,    2,    2,    3,    2,    2,    3,    2,    2,    3,
          2,    2,    3,    2,    2,    3,    2,    2,    3,    2,    2,
          3,    2,    2,    3,    2,    2,    3,    2,    2,    3,    2,
          2,    3,    2,    2,    3,    2,    2,    3,    2,    2,    3,
          5,    2,    3,    2,    5,    2,    3,    2,    5,    2,    3,
          2,    5,    2,    3,    2,    5,    2,    3,    2,    5,    2,
          3,    2,    5,    2,    3,    2,    5,    2,    3,    2,    5,
          2,    3,    2,    5,    2,    3,    2,    5,    2,    3,    2,
          5,    2,    3,    2,    5,    2,    3,    2,    5,    2,    3,
          2]
```
I find the extreme jumps in the post-change ordering worrying. 

Forgive the walls of numbers, but this seems non-trivial to debug/reproduce. I am relatively certain that it is a bug though.

**Comment by eriknw** [comment]
Thanks for continuing to dig into this.  I am unsure how to interpret these numbers.  In order for me to look at the behavior of `order.order`, it would be sufficient to only have the dependencies of each task.  I don't need the actual tasks or the workflow that created them (although a workflow would be nice).  Could you find a way to post the results of `get_dependencies` on the dask graph that the scheduler gets (i.e., preferably after the optimization passes have occurred).  Thanks!

**Comment by JSKenyon** [comment]
@eriknw Will try get something to you tomorrow. Thanks for the help! 

In terms of the numbers above, they just correspond to the integer values of the write operations as they appear in the output of `order.order`. I was just trying to establish how the changes have affected the ordering.

**Comment by mrocklin** [comment]
You may also be interested in the `x.visualize("myfile.png", color="order")` option, which for modestly sized graphs (below 100-1000?) should create an image of the graph with the ordering overlayed as a colormap.  That can be useful when identifying ordering issues.

**Comment by JSKenyon** [comment]
Thanks @mrocklin - I have done that for a subset of the problem. The graph is very complicated so interpreting the results is a little challenging. It does however look like the ordering change has resulted in a "breadthier" traversal. This is strange because each chunk of input data is processed independently - there shouldn't be any dependencies between data chunks, and the behaviour in the past was consistent with that.

**Comment by JSKenyon** [comment]
@eriknw I have pickled the dictionary ([deps.txt](https://github.com/dask/dask/files/4157823/deps.txt)) produced [here](https://github.com/dask/dask/blob/03aca07be7f69964d290138fd86ce71c8797afe7/dask/order.py#L109). I believe that is what you asked for - please let me know if I am mistaken. The keys containing `_finialize_store` correspond to writing xarray.Datasets to disk. Keys starting with `C147_unflagged.MS-write` correspond to writing columns back to the input dataset. Let me know if I can be of any further assistance.

**Comment by JSKenyon** [comment]
Just as a follow up to @mrocklin's suggestion, here are the ordering plots for a subset of my data.

Pre ordering change:
![pre](https://user-images.githubusercontent.com/6582745/73824915-acd58e80-4803-11ea-9a47-6de45b27be01.png)

Post ordering change:
![post](https://user-images.githubusercontent.com/6582745/73824998-dabad300-4803-11ea-8df4-3d1e840953ec.png)

To me it seems that the post change graph is being traversed in a sub-optimal, breadth-first fashion.

**Comment by eriknw** [comment]
Excellent, thanks @JSKenyon!  I'm taking a look at deps.txt now.

**Comment by eriknw** [comment]
Real, difficult cases like this are very useful, so thanks again for raising the issue @JSKenyon !

I've made a small variation to `order` to go from

![dsk_current-min](https://user-images.githubusercontent.com/2058401/73871701-ed3d0880-4813-11ea-8658-7e42254a60c3.png)

to

![dsk_lifo1-min](https://user-images.githubusercontent.com/2058401/73871928-56248080-4814-11ea-959e-b36f459446e1.png)

which I think is much better (and passes all the `order` tests).

fyi, I made these plots with this command `dask.visualize(dsk, color='order', cmap='autumn', filename='dsk_current.jpeg', node_attr={'penwidth': '10'})`.  Using a different colormap and larger penwidth makes it easier to see behaviors in large graphs.

I'll need more time to investigate the performance impact of this change and to run through other more complicated examples.  I'd like more time to investigate other possible solutions too.  I'll get an experimental branch up later today for you to test out.

**Comment by JSKenyon** [comment]
@eriknw Thank you so much for the help! I look forward to trying out your branch when it appears. :-) And an extra heaping of gratitude for the visualize tips - that will prove super useful.

**Comment by TAdeJong** [comment]
@eriknw I _think_ I run into the same bug in my work, where I have a very large intermediate representation that get's reduced by two different tasks. This gave me a nicely small MWE that might be of use:

```python
import numpy as np
import dask.array as da
import dask
from dask.distributed import Client, LocalCluster

cluster = LocalCluster(n_workers=1, threads_per_worker=2)
client = Client(cluster)

# Normally load actual data here and apply FFTs to do cross correlation
X = da.random.random((150,256,256), chunks=(50,256,256))
Corr = X[:, np.newaxis, ...] * X.conj()[np.newaxis, ...]
flatData = Corr.reshape(Corr.shape[:-2]+(-1,))
argmaxs = da.argmax(flatData, axis=-1)
maxima = da.max(flatData, axis=-1)
dask.visualize((maxima, argmaxs), optimize_graph='True', 
               color='order',
               cmap='viridis', 
               filename='dsk_MWE_argmaxs+maxima.png', 
               node_attr={'penwidth': '10'})
dask.visualize(argmaxs, verbose=True, optimize_graph='True', 
               color='order', 
               cmap='viridis', 
               filename='dsk_MWE_argmaxs.png', 
               node_attr={'penwidth': '10'})

da.compute(argmaxs) #fine 
da.compute(maxima) #fine
da.compute(argmaxs,maxima) #explodes
```
Obviously this is a somewhat awkward quadratic algorithm, but the first explodes memory use (especially if you increase the size somewhat more), while calculating either the argmaxs or maxima alone is perfectly fine, as the chunks of flatData don't remain in memory.

Argmaxs+maxima:
![dsk_MWE_argmaxs+maxima](https://user-images.githubusercontent.com/6816964/78362877-234ffc00-75bb-11ea-9594-764ff72a2506.png)
argmaxs only:
![dsk_MWE_argmaxs](https://user-images.githubusercontent.com/6816964/78362867-1fbc7500-75bb-11ea-9303-dd58380a6297.png)

I did not yet have time to test this MWE with #5872 , but it might be of use for checking and hope #5872 will actually resolve this.

(The full code at https://github.com/TAdeJong/LEEM-analysis/blob/master/2%20-%20Driftcorrection.ipynb used to be able to run with upto 1500 images in 32GB of memory, now it chokes on 500 :cry:  )

**Comment by eriknw** [comment]
@TAdeJong, these are great example, thanks so much!

#5872 does handle this better, and I've already made an improvement to make it do even better :)

**Comment by eriknw** [comment]
This was added as a test.  The new behavior in #5872 is:

![dask_new](https://user-images.githubusercontent.com/2058401/78406157-ac6d3000-75c7-11ea-8596-0a2838a03200.png)
