### ISSUE TITLE
dask dataframe - collect list example

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#5863]
Good discussion here about how to implement [collect list](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=dataframe#pyspark.sql.functions.collect_list) with dask dataframe https://github.com/dask/dask/issues/2706

I would like to create an example in here: https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate (https://github.com/dask/dask/blob/master/docs/source/dataframe-groupby.rst#aggregate)

**Comment by TomAugspurger** [comment]
That sounds great, thanks!
