### ISSUE TITLE
Memory leak on local cluster 

### ISSUE THREAD

**Issue by jchutrue** [dask/dask#5864]
On dask version 2.10.1, I am getting high memory usage on a simple problem:
```python
import dask.array as da
from dask.distributed import LocalCluster
lc = LocalCluster(n_workers=4, threads_per_worker=1, processes=False, memory_limit='8GB')
n_points = 1250*60*60*4
n_scales = 300

scales = da.arange(n_scales)
omega = da.fft.fftfreq(n_points) * 2 * np.pi
x = omega * scales[:, None]
x = x.rechunk((1, 1250*60*5))

x.to_hdf5('testdata.hdf5', '/x')
```

When I run this code, I get a warning "Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?", and this is confirmed by htop. Is there an issue with my code that is causing a problem?

**Comment by TomAugspurger** [comment]
Hard to say, but several things could be causing this. https://github.com/dask/dask/issues/3530 is a common culprit, though HDF5 could be doing things, or perhaps something else entirely.

What's the communication pattern of the rechunking? If you use smaller chunks do you see the same issue?

**Comment by jchutrue** [comment]
No improvements after doing `export MALLOC_MMAP_THRESHOLD_=16384` before running the code. 

The code I posted above is the only thing I'm doing right now, so there's not much going on. If I set the chunksize smaller, say (1, 1250*60), then I still run out of memory. If I set it even smaller to (1, 1250), then the memory again keeps climbing but at a slower rate.

**Comment by mrocklin** [comment]
The numpy/memory management issue would also be my first guess.  I
recommend trying to narrow down the cause by removing HDF5 from the
situation and see if the problem persists or goes away.  I would also
probably try removing Dask and use a concurrent.futures.ThreadPoolExecutor
with similar operations in numpy and see if the problem persists or goes
away (this is how we tracked down the numpy issues in that issue).

**Comment by jchutrue** [comment]
I ran a test by removing HDF5 and specifying a smaller array that would fit in memory, so `x.compute()` instead of `x.to_hdf5`. I only decreased the number of rows in the array; otherwise, the chunks were the same. There was still large memory usage that eventually spilled over into swap before the computation finished, and I got the same potential memory leak warning from dask. In addition, my target array doesn't fit into memory so this isn't a long-term solution.

So far the only solution I've found was to manually create an array with numpy memmap, and then fill the array row-by-row with numpy operations using the threading backend with joblib. In that situation I did not encounter the memory issue. 

My project uses xarray--that's why I hoping to use a dask array for out-of-core computations. I would then create a dataset from that dask array and save the results directly to a netcdf file, rather than using bare numpy memmap's.

Technically I could create a dask array from the numpy memmap, create the xarray Dataset, and write that out to a netcdf file, but that's two writes to disk, each 40+ GB, so I'd like to avoid that situation if possible. This might not be relevant to my original question, but do you happen to have any suggestions or workarounds?

**Comment by mrocklin** [comment]
I suggested removing HDF5 just to remove a bit of technology from your test
and make bug hunting easier, not as a recommendation for what you should be
doing in your actual workflow.   See
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If you want to avoid computing the thing you might instead compute the sum
of the array.

**Comment by jchutrue** [comment]
Hmm the array is going to be transformed later (logs, exponentials, and then fft), so no reductions. I don't see an alternative besides writing to disk because the array is so large.

**Comment by mrocklin** [comment]
Yeah, I'm not trying to tell you how to change your application.  I'm
trying to tell you how to identify the bug that you're running into.

**Comment by jchutrue** [comment]
Right. The problem does seem to indicate the numpy memory segmentation issue. So not much that can be done at this point. Thanks for the help.

**Comment by JSKenyon** [comment]
I have tweaked your example a little - please note that I have not checked that this produces the correct results, only that it doesn't grow indefinitely in memory:

```python
import dask.array as da
from dask.distributed import LocalCluster
import numpy as np

lc = LocalCluster(n_workers=4, threads_per_worker=1, processes=False, memory_limit='8GB')
n_points = 1250*60*60*4
n_scales = 300

scales = da.arange(n_scales, chunks=(1,))
omega = da.fft.fftfreq(n_points, chunks=(1250*60*5,)) * 2 * np.pi

def mul_2d(arr1, arr2):
    return np.atleast_2d(arr1*arr2)

x = da.blockwise(mul_2d, "ij",
                 scales, "i",
                 omega, "j")

y = da.to_zarr(x, 'testdata', overwrite=True)

da.compute(y)
```

With dask 2.10.1 this still raises the warning but the memory usage stabilizes at around 10GB. What is more interesting to me is that this is a decent example of my issue in  #5859 (pinging @eriknw, as this might be a decent test). When I run the above code with 2.9.1 there are no warnings and maximum memory usage is around 500MB.

**Comment by jchutrue** [comment]
@JSKenyon thank you so much for the tweak! My memory usage has also stabilized, even with 2.10.1, and I can now proceed. It's very interesting how dramatically better your approach is on my machine.
