### ISSUE TITLE
Losing index information when using dask.dataframe.to_parquet() with partitioning

### ISSUE THREAD

**Issue by LudwikBielczynski** [dask/dask#5869]
When I was using dask=1.2.2 with pyarrow 0.11.1 I did not observe this behavior. After updating (dask=2.10.1 and pyarrow=0.15.1), I cannot save the index when I use to_parquet method with given partition_on and write_index arguments. Here I have created a minimal example which shows the issue: 

    from datetime import timedelta
    from pathlib import Path
    
    import dask.dataframe as dd
    import pandas as pd
    
    REPORT_DATE_TEST = pd.to_datetime('2019-01-01').date()
    path = Path('/home/ludwik/research/trials/')
    
    observations_nr = 3
    dtas = range(0, observations_nr)
    rds = [REPORT_DATE_TEST - timedelta(days=days) for days in dtas]
    data_to_export = pd.DataFrame({
        'report_date': rds,
        'dta': dtas,
        'stay_date': [REPORT_DATE_TEST] * observations_nr,
        }) \
        .set_index('dta')
    
    data_to_export_dask = dd.from_pandas(data_to_export, npartitions=1)
    
    file_name = 'trial.parquet'
    data_to_export_dask.to_parquet(path / file_name,
                                   engine='pyarrow',
                                   compression='snappy',
                                   partition_on=['report_date'],
                                   write_index=True
                                  )
    
    data_read = dd.read_parquet(path / file_name, engine='pyarrow')
    print(data_read)

Which gives:

    | | stay_date  |dta| report_date|
    |0| 2019-01-01 | 2 | 2018-12-30 |
    |0| 2019-01-01 | 1 | 2018-12-31 |
    |0| 2019-01-01 | 0 | 2019-01-01 |

I did not see that described anywhere in the dask documentation. I have checked if that's not an issue with the dd.read_parquet() by using the pyarrow to read a parquet file inside the partition. The index is not conserved. 

I've looked into the dask.dataframe.core.to_parquet() source code and it seems that there is a reset_index performed while creating the parts of the Delayed objects. I didn't go deeper, but it might be a lead.  

We need in our  data-flow to conserve partitioned database with an index. Of course, I might be doing something wrong but from the documentation it is not apparent.

**Comment by TomAugspurger** [comment]
FWIW, this matches the behavior of pandas, though it looks buggy in each.

```python
In [39]: df = pd.DataFrame({"A": [1, 2, 3], "B": ['a', 'a', 'b']}, index=pd.Index(['a', 'b', 'c'], name='idx'))

In [40]: df
Out[40]:
     A  B
idx
a    1  a
b    2  a
c    3  b

In [41]: df.to_parquet("data.parquet", engine="pyarrow", partition_cols=["B"])

In [42]: pd.read_parquet("data.parquet")
Out[42]:
   A idx  B
0  1   a  a
1  2   b  a
2  3   c  b
```

If we look at the metadata written by pyarrow, their may be an issue

```
In [48]: dset = pq.ParquetDataset("data.parquet")

In [49]: dset.read_pandas()
Out[49]:
pyarrow.Table
A: int64
idx: string
B: dictionary<values=string, indices=int32, ordered=0>
metadata
--------
{b'pandas': b'{"index_columns": [], "column_indexes": [], "columns": [{"name":'
            b' "A", "field_name": "A", "pandas_type": "int64", "numpy_type": "'
            b'int64", "metadata": null}, {"name": "idx", "field_name": "idx", '
            b'"pandas_type": "unicode", "numpy_type": "object", "metadata": nu'
            b'll}], "creator": {"library": "pyarrow", "version": "0.15.1"}, "p'
            b'andas_version": "1.0.1"}'}
```

I would expect to see `idx` in the `index_columns` list. So right now this looks like an upstream bug in pyarrow.

**Comment by TomAugspurger** [comment]
cc @rjzamora, in case this is expected behavior / a known bug.

**Comment by LudwikBielczynski** [comment]
Hi, thanks for the fast answer. I agree that with this pandas version it is reproducible. 

I looked at the source code of pyarrow and it seems that they are loosing the index to conserve the metadata between partitions in line 1419  of pyarrow.parquet.write_to_dataset():

`df = table.to_pandas(ignore_metadata=True)`

**Comment by rjzamora** [comment]
Thanks for raising @LudwikBielczynski 

As you and @TomAugspurger  have sugested, this is likely an upstream issue.  Dask will only *infer* which data to set to the index if it is specified correctly by pyarrow in the pandas metadata.

With that said, you should get the behavior you want by specifying the appropriate column name as the index when reading...

```python
dd.read_parquet(<path>, engine='pyarrow', index='dta').compute()
```
**Output**:
```
      stay_date report_date
dta                        
2    2019-01-01  2018-12-30
1    2019-01-01  2018-12-31
0    2019-01-01  2019-01-01
```

**Comment by LudwikBielczynski** [comment]
Thanks for showing the option to set the index while reading the parquet data. I think we can close this issue on dask side. I will keep trying to push the fix on the pyarrow side.
