### ISSUE TITLE
Submitting task to remote scheduler

### ISSUE THREAD

**Issue by ayushpatidar** [dask/dask#5870]
Hey,

I have deployed a local cluster on remote machine. 
And I have connected to remote cluster from my local machine using  dask Client(). 

But when i am submitting task to dask client it is not executing. 

--------------------------------------------------------------------------------------------
ERROR IS:

distributed.worker - WARNING -  Compute Failed
Function:  mul
args:      (2, 4)
kwargs:    {}
Exception: IndexError('tuple index out of range',)

---------------------------------------------------------------------------------
Local machine : CODE

def mul(a,b):
    return (a+b)

c = Client("remote ip address")
c.submit(mul ,2,4)
-----------------------------------------------------------------------
Can anyone help . Or provide link to suitable to docs for  working on remote scheduler.

**Comment by quasiben** [comment]
can you try your same routine with a localcluster and verify if works ?

```python
from distributed import Client
c = Client()
def mul(...)
r = c.submit(mul, 2, 4)
r.result()
```

**Comment by TomAugspurger** [comment]
You might also verify that your versions match with `client.get_versions(check=True)`.

**Comment by ayushpatidar** [comment]
@quasiben 
I tried in with local cluster it worked.

**Comment by ayushpatidar** [comment]
@TomAugspurger 
Do different versions create problem.

**Comment by TomAugspurger** [comment]
>  Do different versions create problem.

Yep.

It'd be great if you could update your original post to provide a minimal bug report: See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for some tips.

**Comment by TomAugspurger** [comment]
Any updates here @ayushpatidar?

**Comment by TomAugspurger** [comment]
@ayushpatidar let us know if you can provide some updates and we'll reopen.
