### ISSUE TITLE
dask.dataframe import problem

### ISSUE THREAD

**Issue by rizwanishaq** [dask/dask#5875]
I am trying to import dask.dataframe, I am having this error

ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
pip install 'fsspec>=0.3.3'

I am using python3.7 (debian 9), I tried to solve this problem, but no success, any solution? 
when I checked the installed packages, I can see clearly 
fsspec==0.6.2
dask==2.10.1 
any solution for this?

**Comment by TomAugspurger** [comment]
Can you recreate the problem in a new conda or virtual environment?

```python
python3 -m venv dask-env
. dask-env/bin/activate
python3 -m pip install dask[dataframe]
python3 -c "import dask.dataframe"
```

**Comment by rizwanishaq** [comment]
now another problem
ModuleNotFoundError: No module named '_bz2'

**Comment by TomAugspurger** [comment]
That should be bundled with Python: https://docs.python.org/3/library/bz2.html

**Comment by TomAugspurger** [comment]
But it sounds like you're past the dask.dataframe import issue? If so, I'm going to close this and recommend you check out the docs on using / installing python from wherever you got / built it.
