### ISSUE TITLE
Lobby AWS for a serverless Glue option to run dask clusters

### ISSUE THREAD

**Issue by dazza-codes** [dask/dask#5881]
AWS Glue has a pyspark option; could the dask community lobby for a serverless dask cluster?

**Comment by mrocklin** [comment]
My experience is that OSS projects aren't the right groups to do this lobbying.  The feedback that we've gotten from the clouds is that this has to be driven by AWS customers themselves.

**Comment by dazza-codes** [comment]
It might help to identify the intersection of dask and AWS users, to identify the right channels or forums for such requests.  If anyone is interested in this option, add a reaction or subscribe to this issue to see where it goes, assuming the dask project is open to leaving this open for a while.  I'm open to advice on how to redirect attention elsewhere for this, if there is already a SIG for it.

**Comment by mrocklin** [comment]
It has been about a week and there hasn't been any response here.  I'm going to go ahead and close this out.  You might want to try other forums that are more public facing for users, like twitter?
