### ISSUE TITLE
LocalCluster Asynchronous=True potential bug?

### ISSUE THREAD

**Issue by lodivalent** [dask/dask#5885]
I believe I've run into a bug when trying to implement some of the architecture in the Asynchronous Computation: Web Servers + Dask section and attempting to use it with a Local Cluster

The first iteration of the code will start up a tornado webserver and return the result however when I modify the dask client to use a Local Cluster instead, the results hang and never complete. 

	from dask.distributed import Client, LocalCluster
	import tornado.ioloop
	import tornado.httpserver
	import tornado.web
	import json
	import dask.dataframe as dd

	class postHandler(tornado.web.RequestHandler):
		async def post(self):
			data = json.loads(self.request.body.decode('utf-8'))
			rating = data['rating']
			print(rating)
			future = client.submit(runTestFunctionality2, rating)
			r = await future
			print(r)
			self.write(r)

	def runTestFunctionality2(rating):
		return "done "+rating

	def square(x):
	        return x**2
	def neg(x):
	        return -x
	def make_app():
		return tornado.web.Application([
			(r"/", postHandler)
		])

	if __name__=="__main__":
		#################
		client = Client(asynchronous=True)  # WORKs
		#################
		cluster = LocalCluster(n_workers=1, threads_per_worker=1, dashboard_address=0)
		client = Client(cluster, asynchronous=True)  # DOES NOT WORK
		#################
		app = make_app()
		http_server = tornado.httpserver.HTTPServer(app)
		http_server.listen(19000)
		print('Starting server on port 19000')
		tornado.ioloop.IOLoop.instance().start()

I can use the LocalCluster functionality in other script without the asynchronous=True option so i think it's tied to that. Is this a bug or am I just setting something up wrong?

**Comment by mrocklin** [comment]
When starting up Dask clusters or clients in async mode you will want to await them

```python
	cluster = await LocalCluster(n_workers=1, threads_per_worker=1, dashboard_address=0)
	client = await Client(cluster, asynchronous=True)  # DOES NOT WORK
```

**Comment by lodivalent** [comment]
Isn't await is only valid inside an async def though? Is there some method I'm missing to get asyncio to await cluster start up in the main method? I'm running from a script, not a notebook if that makes a difference.
 
By moving the __main__ code to an async function, I was able to get the clusters to start, however then the client variable changes namespaces and is no longer useable by the postHandler function

	async def startup():
		cluster = await LocalCluster(n_workers=1, threads_per_worker=1, dashboard_address=0)
		client = await Client(cluster, asynchronous=True)  # use local processes for now
		print(client.scheduler_info()['services'])
		##test local cluster startup
		gdf = dd.read_table('data.csv')
		A = client.map(square, gdf['num'])
		B = client.map(neg, A)
		total = client.submit(sum, B)
		print(total.result())

		app = make_app()
		http_server = tornado.httpserver.HTTPServer(app)
		http_server.listen(19000)
		print('Starting server on port 19000')

	if __name__=="__main__":
		loop = asyncio.get_event_loop()
		try:
			asyncio.ensure_future(startup())
			loop.run_forever()
		except KeyboardInterrupt:
			pass
		finally:
			print("Closing Loop")
			loop.close()

**Comment by mrocklin** [comment]
Ah, you could try awaiting the cluster and client where you use it.
Awaiting is idempotent, so it will be slow the first time, but free
afterwards.

**Comment by mrocklin** [comment]
Does this resolve your issue @lodivalent ?  I'm going to go ahead and close things here.  Feel free to respond and we'll reopen if necessary.

**Comment by lodivalent** [comment]
Managed to get it working by shifting the LocalCUDACluster instantiation to inside an asynch function. Slightly worried about stability when multiple post requests come in though. 


```
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, LocalCluster
import tornado.ioloop
import tornado.httpserver
import tornado.web
import asyncio
import dask_cudf

class postHandler(tornado.web.RequestHandler):
        async def post(self, *args):
                cluster = await LocalCUDACluster(n_workers=2, threads_per_worker=1, dashboard_address=0)
                with Client(cluster, asynchronous=True) as dask_client:
                        data = json.loads(self.request.body.decode('utf-8'))
                        gdf = dask_cudf.read_parquet('/path', npartitions=2)
                        out = someFunction(gdf, data)
                        self.write(out)

def make_app():
        return tornado.web.Application([
                (r"/", postHandler)
        ])

if __name__=="__main__":
        app = make_app()
        http_server = tornado.httpserver.HTTPServer(app)
        http_server.listen(10000)
        print('Starting server on port 10000')
        tornado.ioloop.IOLoop.instance().start()

```

**Comment by mrocklin** [comment]
Yeah, that seems like it would be pretty slow on every post.  You're not able to create the cluster outside, and then await it in the post call?

Or perhaps you can run an async function that creates everything and run that on the event loop, and then run tornado generally for the web server?

**Comment by mrocklin** [comment]
Or maybe the cluster can be synchronous while you just await the client, which you keep asynchronous?

**Comment by lodivalent** [comment]
> Or maybe the cluster can be synchronous while you just await the client, which you keep asynchronous?

Changing the main function to:
```
if __name__=="__main__":
        cluster = LocalCUDACluster(n_workers=2, threads_per_worker=1, dashboard_address=0)
        app = make_app()
        http_server = tornado.httpserver.HTTPServer(app)
        http_server.listen(10000)
        print('Starting server on port 10000')
        tornado.ioloop.IOLoop.instance().start()

```
and dropping the cluster initialization in the POST functionality works, so i think this is probably a more stable solution. Tested with two concurrent post requests and both succeed. Haven't checked whether the scheduler partitions the tasks across multiple GPUs though.
