### ISSUE TITLE
Unclear error message when meta column order does not match

### ISSUE THREAD

**Issue by bnaul** [dask/dask#5886]
Related to #4887: currently the message when the order is different is:
```
ValueError('The columns in the computed data do not match the columns in the provided metadata\n  Extra:   []\n  Missing: []')
```
Probably want to use a different kind of assert that shows the columns themselves, or at least suggests to the user that order could be responsible?

**Comment by mrocklin** [comment]
My apologies for the late response here @bnaul .  Thank you for spending the time to raise the issue.

> Probably want to use a different kind of assert that shows the columns themselves, or at least suggests to the user that order could be responsible?

Hrm, so currently we *do* provide the column names.  

```python
def check_matching_columns(meta, actual):
    # Need nan_to_num otherwise nan comparison gives False
    if not np.array_equal(np.nan_to_num(meta.columns), np.nan_to_num(actual.columns)):
        extra = actual.columns.difference(meta.columns).tolist()
        missing = meta.columns.difference(actual.columns).tolist()
        raise ValueError(
            "The columns in the computed data do not match"
            " the columns in the provided metadata\n"
            "  Extra:   %s\n"
            "  Missing: %s" % (extra, missing)
        )
```

The logic there seems sensible to me, but clearly there is an issue here.  Is it easy for you to create a failing example here?

**Comment by bnaul** [comment]
The issue is just when the columns are the same but differently-ordered; in that case Extra and Missing are both empty. Printing all the *ordered* column names would be one way to clarify to the user what the nature of the mismatch is, but obviously that could get messy for a large number of columns. I could see either raising a different error when the columns are the same but shuffled that suggests checking the order, or just adding some text to the current exception that hints at order being important, or finally swapping .difference() for something that respects order and therefore would say Expected: [a, b] at indicies i, j, Got: [b, a].
