### ISSUE TITLE
exception derived from BaseException causes KilledWorker exception in gather()

### ISSUE THREAD

**Issue by dkhokhlov** [dask/dask#5894]
exception derived from BaseException causes KilledWorker exception in gather().
When exception derived from Exception - all works as expected - gather generates original exception.

**Comment by mrocklin** [comment]
The KilledWorker exception arises when workers die without us knowing the
cause.  In this case there is no Exception for us to capture.  This
commonly occurs when user code segfaults for example.  Unfortunately there
is nothing for Dask to return to the user in that case.

**Comment by dkhokhlov** [comment]
Make sense. Looks like workers are catching Exception, but not BaseException as was in my case. 
I have workaround. 
It would be good to catch BaseException in workers too.

**Comment by mrocklin** [comment]
Hrm, interesting.  What was the exception that you were running into?

**Comment by dkhokhlov** [comment]
Any exception derived from BaseException. 
Bad case:
```
class SuperBad (BaseException):
     pass
```
Good case - anything derived from Exception:
```
like ZeroDivisionError
```

**Comment by mrocklin** [comment]
Yeah, I'm just curious where it comes up in practice.  In practice the only
non-Exception exception I see regularly is KeyboardInterrupt.  I'm curious
where this came up for you in particular.

**Comment by dkhokhlov** [comment]
In my case the exception was intentionally derived from BaseException to penetrate usual checks, and be visible.

**Comment by mrocklin** [comment]
So I guess your suggestion is that we also catch BaseExceptions in the Worker and report those up to the Client, rather than have the worker fail?

**Comment by mrocklin** [comment]
I wonder if this will have a negative effect if users do a `KeyboardInterrupt` on a worker process.

**Comment by dkhokhlov** [comment]
Right, better not to change any current semantics. So I propose to add field to KilledWorker which will hold original exception that caused worker to die. 
I am looking into distributed code and it is not clear how to get original exception info at place where KilledWorker created and passed to client.

**Comment by mrocklin** [comment]
> So I propose to add field to KilledWorker which will hold original exception that caused worker to die.

In 99% of cases we don't have access to this exception.  The KilledWorker exception is created on the Scheduler after a worker has died unexpectedly.  There is no way for us to get this information, except in the one case that you've mentioned, where someone has constructed a custom Exception that doesn't inherit from Exception.

**Comment by quasiben** [comment]
@dkhokhlov thanks for raising this.  Perhaps if you could provide an example where a worker was killed because of an exception that would be helpful.  As @mrocklin said, KillWorker Exceptions happens when workers die unexpectedly.   Errors like `ZeroDvisionError` in a computation should not kill the work.  I am going to close for now for some house keeping around the issue tracker but @dkhokhlov please feel free to reopen if you would like to keep engaging
