### ISSUE TITLE
Feature Request: Fast alternative to from_array

### ISSUE THREAD

**Issue by astrofrog** [dask/dask#5899]
For an astronomical dataset I am working with, I need to set up a dask array composed of 30,000 equal-shape chunks. To construct this, I am using ``da.block`` which works fine. However, to avoid having dask access any of the data arrays, I need to first convert all the chunks to dask arrays with ``name`` explicitly set to ``False`` (or a random string) and with ``meta`` manually set to prevent any kind of data access before the final dask array is actually used. To do this, I initially looped over all chunks and called ``from_array``, but I realized that this function would be doing and re-doing 30,000 the same checks, which is unnecessary since all the chunks are exactly the same dtype/shape/etc.

I am therefore currently initializing ``Array`` directly with the same arguments that ``from_array`` would have done - here is a simple example:

```python
import uuid
import numpy as np
import dask.array as da


class ArrayWrapper:
    def __init__(self):
        self._array = np.random.random((10, 20, 30))
        self.shape = self._array.shape
        self.dtype = self._array.dtype
        self.ndim = self._array.ndim
    def __getitem__(self, item):
        return self._array[item]


def from_array_fast(array):
    name = str(uuid.uuid4())
    slices = tuple(slice(0, size) for size in array.shape)
    chunk = tuple((size,) for size in array.shape)
    meta = array[()]
    return da.Array({(name,) + (0,) * array.ndim: (da.core.getter, name, slices, False, False),
                      name: array},
                      name, chunk, meta=meta)
```

Comparing the performance of ``from_array_fast`` and ``da.from_array`` gives:

```python
In [4]: %timeit da.from_array(wrapper)                                                                                                           
130 µs ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [5]: %timeit from_array_fast(wrapper)                                                                                                         
22.4 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

The purpose of this issue is two-fold - to check whether using the ``Array`` initializer directly is considered private API and should not be relied upon, and to check whether it would be possible to create a minimal version of ``from_array`` (or have a kwarg) that could do something equivalent to the above for simple cases.

**Comment by mrocklin** [comment]
Calling `da.Array` explicitly is fine.  It's public API and is pretty stable.

> doing and re-doing 30,000 the same checks

Which checks exactly?  Are you mostly referring to all of the isinstance and input cleaning checks?

Assuming that each of your chunks are intended to be single-chunked, then you might also want to investigate [da.from_delayed](https://docs.dask.org/en/latest/array-api.html#dask.array.from_delayed)

If you are highly performance sensitive you could also make your own function that constructed the  raw dictionary / task graph directly.  Writing dictionaries by hand is hard to beat in terms of performance :)

**Comment by mrocklin** [comment]
How did this go @astrofrog ?  Anything else we can do to help here?

**Comment by jsignell** [comment]
I am going to close, this but please feel free to reopen or open a new issue if you have suggestions!
