### ISSUE TITLE
Support for explicit dtype in da.coarson

### ISSUE THREAD

**Issue by manzt** [dask/dask#5902]
## Description
This came up while trying to use coarsen to compute the mean of integer array. I naively thought I could use `functools.partial` like the following:

```python
from functools import partial
import dask.array as da
import numpy as np

x = da.arange( 3 * 50000 * 50000, dtype=np.int32)

int32_mean = partial(np.mean, dtype=np.int32)
reduced = da.coarsen(int32_mean, x, {1: 2, 2: 2}, trim_excess=True)
# TypeError: module, class, method, function, traceback, frame, or code object was expected, got partial
```

Looking into the source, I found this and understand why we can't allow partial.

https://github.com/dask/dask/blob/ed51f88c50587a99372b5fcbc01f569bdf36c6a5/dask/array/routines.py#L1302-L1303

However the current logic defers to the underlying numpy method to decide what dtype to use when computing the mean. This will respect the dtype of `x` if it is a float array, but [**for integer inputs, the default is float64**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html). 

https://github.com/dask/dask/blob/ed51f88c50587a99372b5fcbc01f569bdf36c6a5/dask/array/routines.py#L1314

## Suggestion
I'm not sure what the right approach is here, since I don't think allowing the end user to pass partial is the right call (because we only want to expose `dtype` and not other options).  Perhaps we could add `dtype` with default `None` similar the numpy and use partial internally? I would be happy to make a PR for this!

```python
 if "dask" in inspect.getfile(reduction): 
     reduction = getattr(np, reduction.__name__) 
     if dtype:
        reduction = partial(reduction, dtype=dtype)
```

**Comment by mrocklin** [comment]
Thank you for raising this issue @manzt .  I agree with you that it would be useful to be able to pass a dtype keyword down from `da.coarsen` to the user provided reduction.  

I belive that this is fixed here: https://github.com/dask/dask/pull/5903

**Comment by manzt** [comment]
Great. thanks!

**Comment by manzt** [comment]
FYI @NHPatterson
