### ISSUE TITLE
Creating a dask masked array from multiple numpy masked arrays

### ISSUE THREAD

**Issue by digital-idiot** [dask/dask#5911]
I can read multiple `numpy arrays` from file and combine them into a single `dask array` as follows:
```python
import numpy as np
from itertools import product
from dask import array as da

names = list()
for i in range(100):
    arr = np.random.randint(0, 9, (3, 10, 10))
    fn = 'data/array_{}.npy'.format(i)
    np.save(fn, arr)
    names.append(fn)

indices = list(product(range(10), range(10)))
namex = 'Combined_Array'
dsk = {
    (namex, 0, *index): (np.load, name)
    for name, index in zip(names, indices)
}

dtype=int
shape = (3, 100, 100)
chunks = (3, 10, 10)

d = da.Array(dask=dsk, name=namex, chunks=chunks, dtype=dtype, shape=shape)
```
How can I reproduce the above where I can combine multiple `numpy masked arrays` into a single `dask masked array`. The example code will be as follows: 

```python
import numpy as np
from itertools import product
from dask import array as da

names = list()
for i in range(100):
    arr = np.random.randint(0, 9, (3, 10, 10))
    arr = np.ma.masked_array(arr, arr==0)
    fn = 'data/array_{}.npy'.format(i)
    np.dump(fn, arr)
    names.append(fn)

indices = list(product(range(10), range(10)))
namex = 'Combined_Array'
dsk = {
    (namex, 0, *index): (np.load, name, None, True)
    for name, index in zip(names, indices)
}

dtype=int
shape = (3, 100, 100)
chunks = (3, 10, 10)

# ma.MaskedArray is a hypothetical class which resembles the above example
d = da.ma.MaskedArray(dask=dsk, name=namex, chunks=chunks, dtype=dtype, shape=shape)
```
 `da.ma.MaskedArray` class does not really exist currently. One approach to do this would be separately creating a `dask array` for the data and another `dask array` for the mask and then finally combining them into a `dask masked array`. But is there any way to do it without reading the files twice like:
`da.ma.MaskedArray(dask=dsk, name=namex, chunks=chunks, dtype=dtype, shape=shape)`?

**Comment by jsignell** [comment]
It seems like you could create a masked array from each numpy object as described here: https://docs.dask.org/en/latest/array-api.html#dask.array.ma.masked_array and then concatenate the results.

Just FYI the first code snippet that you provided doesn't run as-is. Please make sure that you include a minimal reproducible example when creating an issue.

**Comment by digital-idiot** [comment]
> ust FYI the first code snippet that you provided doesn't run as-is

It works, just that you need to create a directory called `data` inside the working directory other wise you can remove `data` from the file path and will work.

**Comment by jsignell** [comment]
You can just pass multiple masked numpy arrays into a dask array:

```python
import os
import numpy as np
from itertools import product
from dask import array as da

if not os.path.exists("data"):
    os.mkdir("data")

names = list()
for i in range(100):
    arr = np.random.randint(0, 9, (3, 10, 10))
    arr = np.ma.masked_array(arr, arr==0)
    fn = 'data/array_{}.npy'.format(i)
    arr.dump(fn)
    names.append(fn)

indices = list(product(range(10), range(10)))
namex = 'Combined_Array'
dsk = {
    (namex, 0, *index): (np.load, name, None, True)
    for name, index in zip(names, indices)
}

dtype=int
shape = (3, 100, 100)
chunks = (3, 10, 10)

d = da.Array(dask=dsk, name=namex, chunks=chunks, dtype=dtype, shape=shape)
```
`d.compute()` yields:
```
masked_array(
  data=[[[--, 3, --, ..., 6, --, 6],
         [4, 7, 1, ..., 4, 6, --],
         [--, --, 2, ..., 3, 8, 4],
         ...,
         [4, 3, 7, ..., 4, 7, 4],
         [3, 1, 2, ..., 4, --, 6],
         [6, --, 5, ..., 8, 5, 5]],

        [[7, 6, 1, ..., 6, --, 7],
         [1, 1, 3, ..., 1, --, 5],
         [--, 1, 8, ..., 5, 5, 7],
         ...,
         [--, 3, 3, ..., 1, 4, 8],
         [5, 7, --, ..., 4, 7, 5],
         [4, 4, 5, ..., 1, 7, 8]],

        [[--, 1, 2, ..., 6, 5, --],
         [6, 5, 5, ..., 8, 4, 5],
         [3, --, 8, ..., 5, 4, 7],
         ...,
         [2, 4, 6, ..., 8, 2, 7],
         [8, 5, 4, ..., 4, 1, 2],
         [7, 1, 4, ..., 5, 1, 7]]],
  mask=[[[ True, False,  True, ..., False,  True, False],
         [False, False, False, ..., False, False,  True],
         [ True,  True, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False,  True, False],
         [False,  True, False, ..., False, False, False]],

        [[False, False, False, ..., False,  True, False],
         [False, False, False, ..., False,  True, False],
         [ True, False, False, ..., False, False, False],
         ...,
         [ True, False, False, ..., False, False, False],
         [False, False,  True, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[ True, False, False, ..., False, False,  True],
         [False, False, False, ..., False, False, False],
         [False,  True, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]]],
  fill_value=999999)
```

**Comment by digital-idiot** [comment]
> You can just pass multiple masked numpy arrays into a dask array:
> 
> ```python
> import os
> import numpy as np
> from itertools import product
> from dask import array as da
> 
> if not os.path.exists("data"):
>     os.mkdir("data")
> 
> names = list()
> for i in range(100):
>     arr = np.random.randint(0, 9, (3, 10, 10))
>     arr = np.ma.masked_array(arr, arr==0)
>     fn = 'data/array_{}.npy'.format(i)
>     arr.dump(fn)
>     names.append(fn)
> 
> indices = list(product(range(10), range(10)))
> namex = 'Combined_Array'
> dsk = {
>     (namex, 0, *index): (np.load, name, None, True)
>     for name, index in zip(names, indices)
> }
> 
> dtype=int
> shape = (3, 100, 100)
> chunks = (3, 10, 10)
> 
> d = da.Array(dask=dsk, name=namex, chunks=chunks, dtype=dtype, shape=shape)
> ```
> 
> `d.compute()` yields:
> 
> ```
> masked_array(
>   data=[[[--, 3, --, ..., 6, --, 6],
>          [4, 7, 1, ..., 4, 6, --],
>          [--, --, 2, ..., 3, 8, 4],
>          ...,
>          [4, 3, 7, ..., 4, 7, 4],
>          [3, 1, 2, ..., 4, --, 6],
>          [6, --, 5, ..., 8, 5, 5]],
> 
>         [[7, 6, 1, ..., 6, --, 7],
>          [1, 1, 3, ..., 1, --, 5],
>          [--, 1, 8, ..., 5, 5, 7],
>          ...,
>          [--, 3, 3, ..., 1, 4, 8],
>          [5, 7, --, ..., 4, 7, 5],
>          [4, 4, 5, ..., 1, 7, 8]],
> 
>         [[--, 1, 2, ..., 6, 5, --],
>          [6, 5, 5, ..., 8, 4, 5],
>          [3, --, 8, ..., 5, 4, 7],
>          ...,
>          [2, 4, 6, ..., 8, 2, 7],
>          [8, 5, 4, ..., 4, 1, 2],
>          [7, 1, 4, ..., 5, 1, 7]]],
>   mask=[[[ True, False,  True, ..., False,  True, False],
>          [False, False, False, ..., False, False,  True],
>          [ True,  True, False, ..., False, False, False],
>          ...,
>          [False, False, False, ..., False, False, False],
>          [False, False, False, ..., False,  True, False],
>          [False,  True, False, ..., False, False, False]],
> 
>         [[False, False, False, ..., False,  True, False],
>          [False, False, False, ..., False,  True, False],
>          [ True, False, False, ..., False, False, False],
>          ...,
>          [ True, False, False, ..., False, False, False],
>          [False, False,  True, ..., False, False, False],
>          [False, False, False, ..., False, False, False]],
> 
>         [[ True, False, False, ..., False, False,  True],
>          [False, False, False, ..., False, False, False],
>          [False,  True, False, ..., False, False, False],
>          ...,
>          [False, False, False, ..., False, False, False],
>          [False, False, False, ..., False, False, False],
>          [False, False, False, ..., False, False, False]]],
>   fill_value=999999)
> ```

This solves the issue. Thanks @jsignell
