### ISSUE TITLE
value_counts() not showing the actual counts

### ISSUE THREAD

**Issue by ozlemakpinar** [dask/dask#5919]
Hi,
I've imported a .csv file into a dask dataframe.
When I look into the df.head() of the dataframe, I can see that the column 'o_PlantCode' has values in it.
However, when I run the below code to get the value_counts, I am faced with an unexplainable output.
df['o_PlantCode'].value_counts()

output:
Dask Series Structure:
npartitions=1
    int64
    ...  
Name: o_PlantCode, dtype: int64
Dask Name: value-counts-agg, 3548 tasks

Any ideas why would that be?

Thanks
Ozlem

**Comment by TomAugspurger** [comment]
Most methods in dask.datframe are [lazy](https://docs.dask.org/en/latest/user-interfaces.html#lazy-vs-immediate). `head` is one of the few that is immediate (`compute=True` by default https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.head)
