### ISSUE TITLE
Pipe API

### ISSUE THREAD

**Issue by jamesthegiantpeach** [dask/dask#5936]
Greetings, 
I am interested in creating an API that I can use to scale existing command line tools in bioinformatics. I am thinking of something like the [ADAM pipe API](https://adam.readthedocs.io/en/latest/api/pipes/). Does something like this already exist in the Dask space? If not, then is it possible for Dask to use code that drops shell to a command line tool?

**Comment by mrocklin** [comment]
Hi @jamesthegiantpeach I personally am not familiar with the ADAM pipe API, and I suspect that others here may also be unaware.  Could you say a bit more here about what you're trying to accomplish?  

I take it that you're trying to process text data from files using non-Python command line tools?  I'm curious, how would you process a single small file of data in Python today with your command line tool?  My guess is that if you can help to answer that then we can probably help point you in the right direction to parallelize that work.

**Comment by jamesthegiantpeach** [comment]
@mrocklin Yes I am trying to process some text and binary genomics files with non-python command line tools. I am going to loop back to this when I have some more time to implement some experiments here. I'll re-open then thanks.
