### ISSUE TITLE
[Bug] Dask 2.10.1 cannot connect to server workers but 2.1.0 can

### ISSUE THREAD

**Issue by bing9** [dask/dask#5941]
Hello team,

We are using dask workers and scheduler on EC2. When I connect using dask 2.10.1 the connection has time out error. Then I downgraded to 2.1.0 we could then connect without problem. 

Environment: Windows 10, Python 3.7.6.

`---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-2-3d8123a49e7b> in <module>
      1 import dask
      2 from dask.distributed import Client, progress
----> 3 client = Client("XX.XXX.XX.XX:8786")
      4 client

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    724             ext(self)
    725 
--> 726         self.start(timeout=timeout)
    727         Client._instances.add(self)
    728 

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\client.py in start(self, **kwargs)
    889             self._started = asyncio.ensure_future(self._start(**kwargs))
    890         else:
--> 891             sync(self.loop, self._start, **kwargs)
    892 
    893     def __await__(self):

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     if error[0]:
    344         typ, exc, tb = error[0]
--> 345         raise exc.with_traceback(tb)
    346     else:
    347         return result[0]

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\utils.py in f()
    327             if callback_timeout is not None:
    328                 future = asyncio.wait_for(future, callback_timeout)
--> 329             result[0] = yield future
    330         except Exception as exc:
    331             error[0] = sys.exc_info()

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\tornado\gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\client.py in _start(self, timeout, **kwargs)
    982 
    983         try:
--> 984             await self._ensure_connected(timeout=timeout)
    985         except OSError:
    986             await self._close()

C:\ProgramData\Anaconda3\envs\XX\lib\site-packages\distributed\client.py in _ensure_connected(self, timeout)
   1062             self._connecting_to_scheduler = False
   1063         if timeout is not None:
-> 1064             msg = await asyncio.wait_for(comm.read(), timeout)
   1065         else:
   1066             msg = await comm.read()

C:\ProgramData\Anaconda3\envs\XX\lib\asyncio\tasks.py in wait_for(fut, timeout, loop)
    447             # See https://bugs.python.org/issue32751
    448             await _cancel_and_wait(fut, loop=loop)
--> 449             raise futures.TimeoutError()
    450     finally:
    451         timeout_handle.cancel()

TimeoutError: `

`  added / updated specs:
    - dask=2.1.0

The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2019.11.~ --> pkgs/main::ca-certificates-2020.1.1-0
  openssl            conda-forge::openssl-1.1.1d-hfa6e2cd_0 --> pkgs/main::openssl-1.1.1d-he774522_4

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                       conda-forge --> pkgs/main

The following packages will be DOWNGRADED:

  dask                                          2.10.1-py_0 --> 2.1.0-py_0
  dask-core                                     2.10.1-py_0 --> 2.1.0-py_0
  distributed                                   2.10.0-py_0 --> 2.5.2-py_0`

Regards,

Bing

**Comment by quasiben** [comment]
@bing9 how did you spin on the dask cluster on ec2?   It's possible you may have some versioin mismatches. Can you run:

> client.get_versions()

**Comment by bing9** [comment]
> @bing9 how did you spin up the dask cluster on ec2? It's possible you may have some versioin mismatches. Can you run:
> 
> > client.get_versions()

Hi @quasiben , 

Thanks for your reply. 

Our cluster is running: 2.8.1. Still we do not expect any breaking changes in minor releases.

Regards,

Bing

**Comment by quasiben** [comment]
Dask assumes a fair amount of version matching between client and cluster.  If your cluster is running 2.8.1 your client should be 2.8.1

xref: https://github.com/dask/distributed/issues/595
xref: https://github.com/dask/distributed/issues/1376

**Comment by TomAugspurger** [comment]
We don't currently support mismatched versions between nodes of the cluster.

> Still we do not expect any breaking changes in minor releases.

We don't necessarily follow semver, though larger changes are usually accompanied with bump in the major version number.
