### ISSUE TITLE
Shared upstream create node in dask.array.to_zarr causes huge memory increase

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#5943]
As reported in #5872 (and eventually disentangled from that issue), using to_zarr after #5797 creates a large memory increase.  This [comment](https://github.com/dask/dask/pull/5872#issuecomment-588779752) shows the new `create` node created upstream of the `store` nodes, which is what seems to be the problem.

On a Helm+Kubernetes, I can verify I see a big spike in memory in my jupyter notebook (*not* the scheduler) when execution begins.

With the threads-based scheduler example below provided by @JSKenyon, he saw 17GB memory size, while I saw 40GB.  Reverting back to the old `to_zarr` behavior only takes up 900MB on my machine.

```
import dask.array as da
import numpy as np

n_points = 1250*60*60*4
n_scales = 300

scales = da.arange(n_scales, chunks=(1,))
omega = da.fft.fftfreq(n_points, chunks=(1250*60*5,)) * 2 * np.pi


def mul_2d(arr1, arr2):
    return np.atleast_2d(arr1*arr2)


x = da.blockwise(mul_2d, "ij",
                 scales, "i",
                 omega, "j")

y = da.to_zarr(x, 'testdata', overwrite=True, compute=False)

da.compute(y, scheduler="threads")
```

**Comment by jsignell** [comment]
I think this can probably be safely closed now that we've reverted to the old behavior right @chrisroat?
