### ISSUE TITLE
[FEA] Allow shallow or deep copies of dask dataframes

### ISSUE THREAD

**Issue by beckernick** [dask/dask#5950]
`Dask.dataframe.copy` is currently strictly shallow, which may cause metadata issues when cuDF/pandas objects are scattered across workers and then downstream operations pass `deep=False` as keyword arguments.

It would be useful to parameterize `copy` to accept the deep keyword, and allow either deep or shallow copies:

https://github.com/dask/dask/blob/33ad832dfc80aee72250fe45d3dfc53ebd987f33/dask/dataframe/core.py#L356-L362

**Comment by mrocklin** [comment]
> and then pass deep=False to operations.

Can I ask for more information about what you mean here?  Are you running operations that mutate the dataframe in-place?  If so, that kind of behavior is generally not well supported.

**Comment by quasiben** [comment]
i think this came from a cudf operation which has `deep=False` but the keyword `deep` is currently not supported.  Is that right @beckernick

**Comment by beckernick** [comment]
Yes, that's correct. This came up when trying to use a pre-scattered dask dataframe object, that did not like the cuDF operation that wanted to pass `deep=False` to copy as part of its API.

**Comment by TomAugspurger** [comment]
Accepting `deep` in DataFrame.copy seems OK to me.

I'm not sure what we should do able non-default values. Do we want to accept whatever and just ignore the user-provided value (which makes it easier to write code that works with any dataframe). Or should we raise if the non-default value is provided, as ignoring user-input is generally a bad idea?

**Comment by jsignell** [comment]
Would an acceptable solution here, be to add the `deep` kwarg and only accept `deep=False` and rais otherwise? I think that's what @TomAugspurger is suggesting above.
