### ISSUE TITLE
Per-partition information in dask.dataframe.DataFrame.memory_usage

### ISSUE THREAD

**Issue by xhochy** [dask/dask#5952]
We currently provide a per-column information in a `pandas.Series` when calling `dask.dataframe.DataFrame.memory_usage` Series. It would also be nice to to have that information on a per-partition-per-column basis. This would allow easier analysis in the case of out-of-memory errors.

I could open a PR that returns this information via a parameter but this would then also change the return-type to a `pandas.DataFrame`. Thus I'm unsure of the right API to implement:

1. `dd.DataFrame.memory_usage(per_partition=True) -> pandas.DataFrame`
2. `dd.DataFrame.memory_usage_detailed() -> pandas.DataFrame`.

Any opinions before I start a PR?

**Comment by TomAugspurger** [comment]
My initial preference is for a separate method (`memory_usage_detailed` or `partitionwise_memory_usage` sound fine), but I think a keyword is also reasonable.

**Comment by mrocklin** [comment]
I wonder if it is possible to just use `df.map_partitions(pd.DataFrame.memory_usage)` here.  If this doesn't work, why doesn't it work, and is there some way that we can improve it?

**Comment by jrbourbeau** [comment]
`df.map_partitions(pd.DataFrame.memory_usage)` seems to work for determining per-partition memory usage:

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8]})

In [4]: ddf = dd.from_pandas(df, npartitions=3)

In [5]: ddf.map_partitions(pd.DataFrame.memory_usage)
Out[5]:
Dask Series Structure:
npartitions=2
0    int64
2      ...
3      ...
dtype: int64
Dask Name: memory_usage, 4 tasks

In [6]: ddf.map_partitions(pd.DataFrame.memory_usage).compute()
Out[6]:
Index    128
a         16
b         16
Index    132
a         16
b         16
dtype: int64
```

@xhochy does that contain the information you're after?

**Comment by xhochy** [comment]
I want to have information in there that identifies the partition, so we can also group by partition to get the total partition sizes.

**Comment by jrbourbeau** [comment]
Gotcha, I think an additional `map_partitions(pd.Series.sum)` will result in the total memory for each partition

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8]})
ddf = dd.from_pandas(df, npartitions=2)
mem_usage = ddf.map_partitions(pd.DataFrame.memory_usage)
mem_per_partition = mem_usage.map_partitions(pd.Series.sum)
print("mem_per_partition.compute():")
print(mem_per_partition.compute())
```

outputs

```
mem_per_partition.compute():
0    160
1    164
dtype: int64
```

**Comment by xhochy** [comment]
Yes, that's the expected result. I would really like to have this as a single API call as a I often get problems reports from colleagues where their large dask graph fails with `KilledWorker` due to uneven partition sizes. This would be a good routine for check this.

**Comment by quasiben** [comment]
fwiw, this comes up fairly frequently in debugging for problems I come across

**Comment by jrbourbeau** [comment]
Echoing Tom's previous comment, I think a separate `memory_usage_per_partition` or `memory_usage_partitionwise` method would be a nice addition
