### ISSUE TITLE
Read_parquet ignores chunksize

### ISSUE THREAD

**Issue by jrichterpowell** [dask/dask#5966]
Per the documentation 
`
The target task partition size. If set, consecutive row-groups from the same file will be aggregated into the same output partition until the aggregate size reaches this value.
`
So I expect running 
` dd.read_parquet("file", chunksize='64MB') `
to produce partitions of size 64MB. However, it returns one partition for the entire file. The following code seems to reproduce the issue:
```
import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask

rand = np.random.randint(2**16, size=(2**24, 10))
rdf = pd.DataFrame(rand, columns = [chr(i+97) for i in range(10)])
rdf.to_parquet("test.parquet")

df = dd.read_parquet("test.parquet", chunksize='64MB')
df.npartitions
```
despite the parquet file being around ~300MB this produces only one partition.

Versions:
`dask==2.11.0                                                                                                                                     fastparquet==0.3.3                                                                                                                               pandas==1.0.1                                                                                                                                    pyarrow==0.16.0  
`

**Comment by TomAugspurger** [comment]
The doc says that multiple row-groups will be aggregated. It looks like your file has a single row-group

```python
In [16]: import pyarrow.parquet as pq

In [17]: pq.ParquetFile("test.parquet").num_row_groups
Out[17]: 1
```

**Comment by jrichterpowell** [comment]
@TomAugspurger 
Okay, it seems I misunderstood the documentation. What would be the correct way to mimic the `blocksize=xMB` behaviour from `read_csv` for `read_parquet`? Repartitioning after reading the file seems to load the entire file into memory, which is not feasible if the file is large

**Comment by TomAugspurger** [comment]
I'm not sure if any parquet readers support that. My understanding is that
a row group is the smallest unit.

If you have control over how the parquet file is generated, you might try
writing with multiple row groups.

**Comment by bsesar** [comment]
Hi @TomAugspurger and @jrichterpowell,

I have created a single Parquet file with multiple row groups, but Dask still loads it as single partition. Here is the code that reproduces this problem:

```import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask

rand = np.random.randint(2**16, size=(2**24, 10))
rdf = pd.DataFrame(rand, columns = [chr(i+97) for i in range(10)])
rdf.to_parquet("test.parquet", row_group_size=(len(rdf.index) // 100))

print('Number of row groups in test.parquet = %d' % pq.ParquetFile('test.parquet').num_row_groups)
df = dd.read_parquet("test.parquet", chunksize=1)
print('Number of Dask partitions when chunksize=1: %d' % df.npartitions)

df = dd.read_parquet("test.parquet", chunksize=101)
print('Number of Dask partitions when chunksize=101: %d' % df.npartitions)
```

```Number of row groups in test.parquet = 101
Number of Dask partitions when chunksize=1: 1
Number of Dask partitions when chunksize=101: 1
```

I must be doing something wrong, but I cannot see what. Halp? :-)

**Comment by bsesar** [comment]
In order for read_parquet() to properly partition the data, the user needs to specify
```
gather_statistics=True
```
in read_parquet(), or otherwise Dask is not aware of the number of row groups present in the Parquet file.

**Comment by snehith57624** [comment]
import dask.dataframe as dd

# Data.CSV file is 16MB file
df = dd.read_parquet("Data.CSV",
                     chunksize="5 MiB",
                     gather_statistics=True, split_row_groups=True)
print(df.npartitions)
print(len(df))

Output:
1
129013


I am also facing the same problem, does this problem have any solution?
