### ISSUE TITLE
Dask loses filesystem protocol name in distributed setting

### ISSUE THREAD

**Issue by ayushdg** [dask/dask#5967]
When performing a read operation with Dask Dataframe (tested with parquet/orc)
`dd.read_orc("/path/to/orc")` the filesystem object `fs` seems to lose the `protocol` attribute (only in a distributed setting).

Modifying dask to print `fs.protocol` in the read_orc call and the read_partition task: https://github.com/dask/dask/blob/master/dask/dataframe/io/orc.py#L64

and here: https://github.com/dask/dask/blob/master/dask/dataframe/io/orc.py#L16

I see the following output:
```
Orc_call fs.protocol: file
orc stripe fs.protocol: abstract
orc stripe fs.protocol: abstract
```

Note: This only happens when using the distributed scheduler (eg: LocalCluster)

Any ideas why the protocol name is lost/defaulting to the protocol of the superclass?

Since this is something that also involves `distributed` and `filesystem_spec` I wasn't sure which library to open the issue in. More than happy to move this discussion to another repository if it's more suitable.

**Comment by TomAugspurger** [comment]
Thanks for the report. Do you have a minimal example demonstrating the issue? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports.

**Comment by ayushdg** [comment]
I'm not sure how to get a minimal example since the `filesystem` object is not available/returned as a part of the api. The only minimal way is inspecting the `fs` object at the two locations linked in the original description. I'm open to suggestions that help give a clearer example.

**Comment by TomAugspurger** [comment]
What's the user-facing behavior that results from losing the protocol?

You can also call

```
get_fs_token_paths(
        path, mode="rb", storage_options=storage_options
    )
```

directly, right?

**Comment by ayushdg** [comment]
Thanks for the response. 

> What's the user-facing behavior that results from losing the protocol?

For context: The user does not/ should not notice a difference from losing the protocol. Cudf had a utility function that used the protocol attribute to check if the filesystem was local (it has since been updated to use a different check).

> You can also call
> 
> ```
> get_fs_token_paths(
>         path, mode="rb", storage_options=storage_options
>     )
> ```
> 
> directly, right?

Yes the issue in this case that, the initial `read_orc` (could also be parquet) call has the correct protocol when calling `get_fs_token_paths`. Later when the subtask `_read_orc_stripe` is called with the distributed scheduler, the `fs` object passed in there loses the protocol name. I'm not sure how I can wrap this into an example.

**Comment by martindurant** [comment]
Closing due to lack of a reprducer.
