### ISSUE TITLE
Datatypes are not casted in concatenation of dataframe.

### ISSUE THREAD

**Issue by mlondschien** [dask/dask#5968]
It appears that datatypes of partitions are not casted during `dd.concat`. Consider the following example:

```python
import dask.dataframe as dd
import dask
import pandas as pd

df_1 = pd.DataFrame({"int_col": [1]})
df_2 = pd.DataFrame({"int_col": [0.5]})

ddf_1 = dd.from_pandas(df_1, npartitions=1)
ddf_2 = dd.from_pandas(df_2, npartitions=1)
ddf = dd.concat([ddf_1, ddf_2], axis=0)

dtypes = ddf.map_partitions(lambda x: x.dtypes)

assert dtypes.compute().to_list() == ["int", "float"]  # does not raise
```

There is a test `test_concat_different_dtypes` in https://github.com/dask/dask/blob/master/dask/dataframe/tests/test_multi.py, which tries to cover this issue. However, as
```python
dtypes_list = dask.compute([part.dtypes for part in result.to_delayed()])
```
is a tuple containing a list, the following assert
```python
assert len(set(map(str, dtypes_list))) == 1  # all the same
```
will never raise.

**Comment by TomAugspurger** [comment]
Thanks for the report. This does look like a bug. The dtype handling in https://github.com/dask/dask/blob/2b7945ed783bc1be7bb67ab78b4ca246adfa9804/dask/dataframe/multi.py#L922-L929 looks incorrect.

@mlondschien are you interested in working on this?

**Comment by mlondschien** [comment]
Yes. I might need some help though.

**Comment by jrbourbeau** [comment]
Thanks @mlondschien, we're happy to help. Our contributing guidelines are at https://docs.dask.org/en/latest/develop.html and is a good starting point

**Comment by mlondschien** [comment]
I created a PR #6006.
