### ISSUE TITLE
Converting structured array to dataframe within bag results in heavy performance loss

### ISSUE THREAD

**Issue by jhnnsrs** [dask/dask#5969]
First and foremost: Amazing library and amazing work! Coming from a neuroscience background and trying to develop an image analysis framework, this library has single handedly revolutionized how i think about distributed programming. Thanks so much for this beauty!

Here's a slight hiccup that I encountered with the conversion of structured arrays into daskdataframes. (my implementation relies on xarray and zarr as a storage backend, to save metadata of microscopy files, so numpys structured arrays seemed like the way to go):

Initialization of the data arrays is fine and performant

```python
import numpy as np
import xarray as xr
import dask.array as da
import dask.dataframe as dd
import dask.bag as db


recordsarray = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
channelcoord = xr.DataArray(da.array(recordsarray), dims=["c"])
loaded = xr.DataArray(da.zeros((1024,1024,2,1)),dims=["x","y","c","z"], coords={"channels": channelcoord})

bag = db.from_sequence([loaded, loaded, loaded])
```

However mapping this function yields a massive performance hit

```python
def get_biometa(array):
            df = dd.from_dask_array(array.channels.data)
            df["Array"] = array.name
            return df

newbag = bag.map(get_biometa)
```

```python

%%time
newbag.compute()
Wall time: 1.94 s
````

Versions:
- numpy==1.17.4
- dask==2.9.1
- xarray==0.14.1

Am I failing to see the obvious? Are dask bags even the way to go here? Is the performance actually adequate and I am just too needy? 😄 

Thanks a lot!

**Comment by quasiben** [comment]
@jhnnsrs would it be possible to keep everything in a xarray instead of using a bag ?

**Comment by jhnnsrs** [comment]
@quasiben the bagged arrays do not necessarily share any of their dimensions, e.g vary in shape, so i  opted for the bag instead of stacking them along an axis, if that was the idea?

I just rechecked on a dockerized jupyter notebook instance and interestingly i do not experience the performance hit there. there is no version difference between the two, besides that the dockerized one is running python 3.7.3 (linux container) and the one facing the issue is python 3.7.5 (windows 10)  ? 

Thanks !

**Comment by quasiben** [comment]
Ah, I see -- on my mackbook i measure 78.2 ms.  I am not sure what is causing the slow down.  I would recommend profiling with [snakeviz](https://jiffyclub.github.io/snakeviz/) to see what the bottleneck is on the Windows side.

Another thing to check is the env is the same in docker container.  It's possible xarray is updated there -- I believe 0.15 is out now, for example

**Comment by mrocklin** [comment]
Placing Dask collections inside of other Dask collections is unlikely to have the behavior that you want.  

Instead, I think that you want to just call your function a few times and then call compute on all of the results at once.

```python
L = [loaded, loaded, loaded]
L = [get_biometa(x) for x in L]

dask.compute(*L)
```

**Comment by mrocklin** [comment]
> Ah, I see -- on my mackbook i measure 78.2 ms. I am not sure what is causing the slow down. I would recommend profiling with snakeviz to see what the bottleneck is on the Windows side.

Beware that if you recommend this then you should also point people to use the single-threaded scheduler.  Otherwise they'll come back with a non-informative profile.

**Comment by quasiben** [comment]
Thanks @mrocklin   If you do profile, you should run with the following:

> newbag.compute(scheduler='single-threaded')

**Comment by jhnnsrs** [comment]
While checking the profile I realised that when explicitly calling the compute with the threaded scheduler i do get ms-runtime. The single threaded scheduler works fine in both environments. Just the processes scheduler is affected by the performance hit in the windows environment, not in the dockerized. Probably too much interprocess communication on the windows side?

@mrocklin almost a bit starstruck after seeing all of your informational content !
I mainly use the bag here to facilitate the transition from a django queryset to distributed analysis by method chaining like
```python
ArrayClass.objects.filter(name="test").baggify().map(lambda x: xr.DataArray: dosomethinghere(x)).
```
if that is considered bad practice though, i will opt for a more standard practice?

**Comment by mrocklin** [comment]
> While checking the profile I realised that when explicitly calling the compute with the threaded scheduler i do get ms-runtime

Right, but you're not actually doing the work of the underlying Xarrays though, you have lazy objects (xarrays) within lazy objects (dask bags).  This is likely to cause some chaos and unlikely to be what you want.  Instead of a bag of xarrays I would use a normal Python list of xarrays.  I think that you'll be happier.

**Comment by jhnnsrs** [comment]
Correct, it involves a "double" computational call in the end, which probably does complicate matters and is not as intuitive. The original thought was that filter and folding operations would be parallelized more efficiently (every xarray does contain meta data about the aquisition in form of  structured arrays). And then just selected xarrays would be processed further along the line.
Will check if it actually does help though.

Thank you! Will close the issue!
