### ISSUE TITLE
ENH: Add rolling function for groupby objects

### ISSUE THREAD

**Issue by ankurrajdev** [dask/dask#5974]
I am trying to get the aggregations for rolling windows. It is working fine with pandas but getting an error when using dask.

The code that I am using is as follows:
```import pandas as pd
import numpy as np
from dask import dataframe as dd

df = pd.DataFrame( 
    ...:         { 
    ...:             "date": pd.date_range("2018-01-01", periods=12, freq="D"), 
    ...:             "group": ["first", "second"] * 6, 
    ...:             "clicks": range(12), 
    ...:             "orders": range(10, 22), 
    ...:         } 
    ...:      ).sort_values(by=['group', "date"]).set_index("date") 

```
This is working:
```df.groupby('group').rolling('2D', closed='left').agg([np.sum, np.mean])```                                                                                                                                                                             

But when I replace it with dask datafame:
```
ddf = dd.from_pandas(df, npartitions=16) 
ddf.groupby('group').rolling('2D', closed='left').agg([np.sum, np.mean]).compute()
```
I am getting the following error:
```AttributeError: 'Column not found: rolling'```

Can we implement in dask where we can use the rolling function on a groupby object that uses date as index?
Or is there an existing way of doing it?

**Comment by TomAugspurger** [comment]
I don't believe this is currently implemented. I don't immediately see any fundamental issues blocking it though. @ankurrajdev are you interested in adding support for groupby rolling?

**Comment by ankurrajdev** [comment]
Sure. I can try.

**Comment by nrcjea001** [comment]
Has there been any progress on this?

It is possible to do a groupby rolling, [example here](https://stackoverflow.com/questions/42172130/dask-rolling-function-by-group-syntax), but it only works for fixed windows. When working with datetime windows, its not working. I have raised a question on this [here](https://stackoverflow.com/questions/63289279/pandas-dask-valueerror-index-must-be-monotonic-when-performing-a-rolling-sum)

**Comment by jsignell** [comment]
Just for visibility, I think the solution in https://github.com/dask/dask/issues/6498#issuecomment-671983351 is probably an ok workaround in the meantime until someone implements this.
