### ISSUE TITLE
[BUG] dask data frame column renaming

### ISSUE THREAD

**Issue by rnyak** [dask/dask#5987]
[test.txt](https://github.com/dask/dask/files/4299136/test.txt)
**Describe the bug**

I would like to do column renaming for a dask data frame. The following code does not do column renaming in-place.

**Steps/Code to reproduce bug**
[test.txt](https://github.com/dask/dask/files/4299113/test.txt)

The original dask df  and its columns:

```
import dask
from dask import dataframe as dd

dff = dd.read_csv('test.csv')
dff.head(5).to_pandas()
 VendorID  trip_distance	  RateCodeID	      fare_amount
0	2	          1.59	            1	                 12.0
1	1	          3.30	            1	                 14.5
2	1	          1.80	            1	                  9.5
3	1	          0.50	            1	                  3.5
4	1	          3.00	            1	                 15.0
```

The code for column renaming:
```
# some col-names include pre-pended spaces remove & lowercase column names
tmp = {col:col.strip().lower() for col in list(dff.columns)}
print(tmp)
dff.rename(columns=tmp)

dff.columns
Index(['VendorID', 'trip_distance', 'RateCodeID', 'fare_amount'], dtype='object')
```

**Expected behavior**
```
dff.columns
Index(['vendorid', 'trip_distance', 'ratecodeid', 'fare_amount'], dtype='object')
```
One work around could be the following:

```
# some col-names include pre-pended spaces remove & lowercase column names
tmp = {col:col.strip().lower() for col in list(dff.columns)}
print(tmp)
dff=dff.rename(columns=tmp)
```
But not sure that's the right way to do 

**Additional context**
the test.txt file is attached to reproduce the issue.

**Comment by TomAugspurger** [comment]
Thanks for the report.

Is reading from CSV necessary to reproduce the issue? If not, can you edit your post to just create the dataframe in memory using `from_pandas`? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
Actually, looking at your output, I don't think there's a bug here. DataFrame.rename isn't inplace for pandas or dask.

```python
In [1]: import pandas as pd
d
In [2]: df = pd.DataFrame(columns=['a', 'b', 'c'])

In [3]: df.rename(columns={'a': 'A'})
Out[3]:
Empty DataFrame
Columns: [A, b, c]
Index: []

In [4]: df
Out[4]:
Empty DataFrame
Columns: [a, b, c]
Index: []
```

You need to assign the result.

**Comment by rnyak** [comment]
@TomAugspurger thanks. So, assignment would be enough, or need to do .copy()?

Also, wrt your response here, may be better to provide a pertinent example for `dask.rename` in the docs?

**Comment by TomAugspurger** [comment]
Just the assignment.

We copy the docstring from pandas docs, so any changes would need to be made there.
