### ISSUE TITLE
Sequential calls of client.get result in the same delayed object from the cluster

### ISSUE THREAD

**Issue by ashvin08** [dask/dask#5989]
The client.get API when submitted with a delayed method sequentially gets back the same delayed object from the cluster

```python
import dask
from dask.distributed import Client, LocalCluster

import time

cluster = LocalCluster()
client = Client(cluster)

@dask.delayed
def inc(x):
    x = x + 1
    return x

graph_inc_5 = {
    "inc": (inc, 5)
}

graph_inc_10 = {
    "inc": (inc, 10)
}

f1 = client.get(graph_inc_5, "inc")
f2 = client.get(graph_inc_10, "inc")

client.compute(f1).result() # Result is 6
client.compute(f2).result() # Result is 6. Should be 11
```

However, if I introduce a time delay the results are what I expect

```python
f1 = client.get(graph_inc_5, "inc")
time.sleep(1)
f2 = client.get(graph_inc_10, "inc")

client.compute(f1).result() # Result is 6
client.compute(f2).result() # Result is 11
```

**Comment by mrocklin** [comment]
You are using delayed functions inside of custom task graphs.  This is very strange.  I suspect that you are trying to use too much technology here.  Instead, I recommend that you just use Dask delayed, and not use custom graphs / dictionaries.

**Comment by jennakwon06** [comment]
Hi Matt! 

My colleague's example is a bit contrived here for the sake of brevity. 

What we are doing is using Dask in Production for a flexible data processing workflow.

For this, we have defined a set of Function classes in our codebase. Each Function class takes in a Dask data structure (or a list of), does transformations, and returns a Dask data structure (or a list of). 

It's natural that some of these Functions take in a list of dask.Delayed objects, and output a transformed list of dask.Delayed objects.

At the time of triggering the workflow, we create a custom graph of these functions following this article ( https://docs.dask.org/en/latest/graphs.html ) then persist/compute it on our cluster.

Below is an example of Functions and our workflow trigger code.

Dataset Load Function
```
def my_load_function(dataset_specification):
    # dataset_specification contains data-identifying information.
    dataset_data = []

    for url in get_raw_file_urls(..) 
        dataset_data.append(dask.delayed(url_load_function(url))
    
    return Dataset(data=dataset_data)
```

Dataset Transform Function 
```
def my_transform_function(dataset):
    # dataset.data is a list of dask.Delayed objects    
    transformed_dataset_data = []

    for d in dataset.data:
        dataset_data.append(dask.delayed(apply_my_transform(d))
    
    return Dataset(data=transformed_dataset_data) 
```

Workflow Trigger Code

```
    graph = {
        "load": (my_load_function, dataset_specification_id),
        "transform": (my_transform_function, "load")
    }

result = compute.graph(graph, "transform") # 'get' is the entry point 
client.compute(result.data) # compute the delayed values 
```

Do you see our usage pattern as "too much technology"? If so, will you recommend us on how we can alter our usage pattern?

Thank you!

**Comment by ashvin08** [comment]
Tagging @mrocklin since I cannot reopen this issue.

**Comment by mrocklin** [comment]
I recommend that you just use Python to organize your many dask collections.  I recommend that you do not use custom graphs.

```python
@delayed
def inc(x):
    return x + 1

x = inc(5)
y = inc(10)

dask.compute(x, y)
```
