### ISSUE TITLE
Question on asynchronous operation

### ISSUE THREAD

**Issue by Korijn** [dask/dask#5991]
In the [docs on asynchronous operation](https://distributed.dask.org/en/latest/asynchronous.html), the following example code is displayed:

```python
from dask.distributed import Client

client = Client()  # normal blocking client

async def f():
    future = client.submit(lambda x: x + 1, 10)
    result = await client.gather(future, asynchronous=True)
    return result

client.sync(f)
```

I'm trying to understand why the `client.submit` call doesn't need an `await`, is work scheduling done without IO?

**Comment by mrocklin** [comment]
The IO necessary for submit calls is very small.  As a result it goes onto
a special channel that is sent over in the background, possibly with many
other small messages at once.

**Comment by jrbourbeau** [comment]
@Korijn does that help clarify things?

**Comment by Korijn** [comment]
> @Korijn does that help clarify things?

Yes, it does explain the rationale.

I was just thinking that if someone would want to utilize dask in a high throughput system, such as a celery worker or an agent in any distributed system, network latency would add up; roundtrip times are not a function of message size. Time spent waiting on IO directly affects the amount of throughput the worker/agent can handle.

I currently don't have any problems to solve with this feature but the thought just crossed my mind while reading your documentation. :)

**Comment by gforsyth** [comment]
Great.  I'm going to close this out as "answered" but please ping with additional questions.  

Also, calls to `submit` return a `Future`, I don't think that roundtrip latency applies here.

**Comment by mrocklin** [comment]
Yeah, we bundle submit calls into a separate channel and send them in the
background.  We're not bound by latency when sending lots of messages.
