### ISSUE TITLE
dask is slow compared to normal pandas while applying custom functions

### ISSUE THREAD

**Issue by jibybabu** [dask/dask#5994]
Hi,

I was trying to use dask for applying a custom function in a data frame and noticed that dask is taking way too much time than usual pandas apply.

So I tried to take a baseline to root cause my issue and realized that dask is giving me very bad performance. Below are the following steps to reproduce! Will be great if somebody could help in understanding it. 

import numpy as np
import pandas as pd
import dask
from dask import dataframe as dd
from multiprocessing import cpu_count
n_cores = cpu_count()

print(np.__version__)
print(pd.__version__)
print(dask.__version__)
1.17.4
0.25.3
2.8.1

df = pd.DataFrame()
df['col1'] = np.random.normal(size = 1500000)
df['col2'] = np.random.normal(size = 1500000)

def myfunc(x,y): return y*(x**2+1)
def apply_myfunc_to_DF(df): return df.apply((lambda row: myfunc(*row)), axis=1)

%%time
df['result1'] = df.apply((lambda row: myfunc(*row)), axis=1)
CPU times: user 22.1 s, sys: 85.7 ms, total: 22.2 s
Wall time: 22.3 s

%%time
df['result1'] = dd.from_pandas(data, npartitions=10).map_partitions(apply_myfunc_to_DF).compute(schedule='processes') 
CPU times: user 42.2 s, sys: 474 ms, total: 43.3 s
Wall time: 42.6 s

**Comment by TomAugspurger** [comment]
Have you read through https://docs.dask.org/en/latest/understanding-performance.html?

In this case you're likely running into what's described in https://docs.dask.org/en/latest/scheduling.html#local-processes, you're moving data between processes.

**Comment by TomAugspurger** [comment]
I'll close this for now, but if you think there's a place that can be optimized we'll reopen.
