### ISSUE TITLE
Long sequence of mapped functions result in non-persistable state

### ISSUE THREAD

**Issue by johanols** [dask/dask#5999]
Given the following Dask Bag

```
import dask
import dask.bag as db

def func_a(x):
    return x

def func_b(x):
    return x

def function_with_a_really_long_name(x):
    return x

def another_function_with_a_really_long_name(x):
    return x

def yet_another_function_with_a_really_long_name(x):
    return x

def i_can_keep_on_going_creating_more_functions_with_really_long_names(x):
    return x

def by_now_we_should_have_reached_the_255_character_limit_which_will_raise_file_name_too_long_if_state_is_saved_to_file(x):
    return x

bag = (
    db.from_sequence(range(5))
    .map(func_a)
    .map(func_b)
    .map(function_with_a_really_long_name)
    .map(another_function_with_a_really_long_name)
    .map(yet_another_function_with_a_really_long_name)
    .map(i_can_keep_on_going_creating_more_functions_with_really_long_names)
    .map(by_now_we_should_have_reached_the_255_character_limit_which_will_raise_file_name_too_long_if_state_is_saved_to_file)
)
```

Will in the end generate task names or keys looking something like this `another_function_with_a_really_long_name-func_a-func_b-function_with_a_really_long_name-i_can_keep_on_going_creating_more_functions_with_r-yet_another_function_with_a_really_long_name-by_now_we_should_have_reached_the_255_charachter_l-1c9fd5895927017c1be22d12e1165aa7`.

This particular key is 267 characters long and if a worker in a distributed dask cluster decides to persist its data to disk this will raise an `OSError [Errno 36] File name too long` and put the cluster in an undefined and paused state.

**Comment by lr4d** [comment]
This should serve as a work-around:
```python
from dask.bag.core import ensure_dict, cull, fuse, inline_singleton_lists, lazify
# Set rename_fused_keys to False by default
def optimize(dsk, keys, fuse_keys=None, rename_fused_keys=False, **kwargs):
    """ Optimize a dask from a dask Bag. """
    dsk = ensure_dict(dsk)
    dsk2, dependencies = cull(dsk, keys)
    dsk3, dependencies = fuse(
        dsk2, keys + (fuse_keys or []), dependencies, rename_keys=rename_fused_keys
    )
    dsk4 = inline_singleton_lists(dsk3, keys, dependencies)
    dsk5 = lazify(dsk4)
    return dsk5

dask.config.set(bag_optimize=optimize)  # Override the default function for bag optimization
```

Unfortunately one can not just use `dask.config.set({"fuse_rename_keys":False})` because for dask.bag `rename_keys` defaults to True, see: https://github.com/dask/dask/blob/master/dask/bag/core.py#L158
@mrocklin could the `rename_fused_keys` kwarg  of dask.bag.optimize be removed safely so one can set this using the configuration parameter?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @johanols!

@lr4d I think we want to avoid removing the `rename_fused_keys` keyword as that could break existing user code. Instead I'd recommend changing the default value of `rename_fused_keys` to `None`. That way, `fuse` will pull in any user configured value here:

https://github.com/dask/dask/blob/1f87ae6329c3ae1c6f3f31945f891c33642c64ba/dask/optimization.py#L493-L494

and if not defined then use `True`, which is the current default behavior.

**Comment by fjetter** [comment]
Truncating the concatenated keys is probably more user friendly. I would suspect the ordinary user not to dive this deep into optimisation when encountering something like this.

**Comment by lr4d** [comment]
actually @jrbourbeau , removing the kwarg would be the same as setting it to `None` by default, as the function admits additional `**kwargs`

**Comment by lr4d** [comment]
The difference ofc would be that behavior would change when `renamed_fused_keys=False` is passed to that function, but a warning for that could be added

**Comment by jrbourbeau** [comment]
> Truncating the concatenated keys is probably more user friendly. I would suspect the ordinary user not to dive this deep into optimisation when encountering something like this.

Agreed that most users should be expected to dig this deep into things. We already truncate long function names (xref https://github.com/dask/dask/pull/5383)

> as the function admits additional **kwargs

Ah I missed that, thanks for pointing it out. Although it looks like `kwargs` isn't being passed to any other functions in the bag optimization code. I see you've opened up #6000, we can move the conversation over there

**Comment by johanols** [comment]
This issue is now resolved as of version 2.13.0 by setting fuse_rename_keys to false in the Dask configuration.

**Comment by jrbourbeau** [comment]
Thanks for following up here @johanols

**Comment by eriknw** [comment]
Wouldn't a more general solution be to update the spill-to-disk code to handle long key names to avoid the `OSError`?
