### ISSUE TITLE
How to test functions on dask graph?

### ISSUE THREAD

**Issue by GTimothee** [dask/dask#6003]
Hi,

I am developing a module to optimize dask graphs. 

My problem is that I do not know how to really test that my implementation work in all cases (for all possible dask graphs). I defined some use cases like doing additions on dask arrays, storing it into new files, loading data, rechunking etc. But I cannot know if I covered every possible use cases. 

How should I proceed to ensure that I covered the most possibilities? 

Thank you in advance,

**Comment by jrbourbeau** [comment]
I'm not aware of any mechanism that tests every possible graph configuration. My recommendation would be to start with graphs from the high-level collections, i.e. dask arrays, dask dataframee, and dask bags, which it sounds like you've already done. Then try lower-level custom dictionary graphs. Specifically, [`test_order.py`](https://github.com/dask/dask/blob/master/dask/tests/test_order.py), [`test_optimization.py`](https://github.com/dask/dask/blob/master/dask/tests/test_optimization.py), and our [`order`-related benchmarks](https://github.com/dask/dask-benchmarks/blob/master/dask/benchmarks/order.py) could be a good starting point for those types of graphs.

**Comment by GTimothee** [comment]
Thank you very much for your answer, thanks to you I have a point where to start.
