### ISSUE TITLE
feature request: add a compute argument to to_hdf5 

### ISSUE THREAD

**Issue by GTimothee** [dask/dask#6004]
All is in the title, I would like to use to_hdf5 as I use store: passing it a compute argument to false if I don't want to compute it directly. It is just a matter of two lines of code to implement I think. If you want I can do a pull request for that. 

Regards,

**Comment by jrbourbeau** [comment]
`to_hdf` already has a `compute` keyword:

https://github.com/dask/dask/blob/7b4f90f0a708cbb97ebb498c78f7931d82ec99db/dask/dataframe/io/hdf.py#L45

**Comment by jrbourbeau** [comment]
Ah you probably mean the dask array `to_hdf5` method, not the dask dataframe one. Adding a `compute=` keyword seems like a nice addition (e.g. `to_zarr` has a `compute=` keyword)

> I can do a pull request for that

That would be welcome, thanks!

**Comment by GTimothee** [comment]
Oh cool thank you, yes I meant the one in dask array I should have precised that.
Thank you for your answer, I will do it.

**Comment by GTimothee** [comment]
Hi again, 

So I am reopening this issue just to get some help on how I should implement the modification. 

I understand why it has not been done before: inside the to_hdf5 function, there is a context manager for the hdf5 file. The process is as follows: 

``` Python
with h5py.File(filepath, mode) as f:
    store(**kwargs)
```

The problem is, I implemented the "compute=False" possibility, but now if I do ".compute" on the object returned by my custom function dask scheduler fails because the file I am trying to write into has been closed. 

Therefore, I see two solutions: 
- I could store the opened file inside some config object or something
- I could create a second function to_hdf5_delayed or something like that that would take a hdf5 file object as input such that the user opens the context manager outside dask code and just passes the file to the to_hdf5 method in order to create the task graph.

Do you have any guideline/advice on how I should do ?

**Comment by mrocklin** [comment]
I would either ...

1.  include the h5py file/dataset object in the graph and assume that the user won't close that object
2.  take a filename/dataset name and include those in all of the tasks and open-write-close the file in every task

But there are probably other ways here and it could be that neither of those ways are optimal.  Probably the hard part of resolving this issue is doing some work to figure out the best approach.  The Xarray folks have a lot of experience doing this.  You might consider looking at their solution.

**Comment by GTimothee** [comment]
Ok I will do it thank you very much for your answer !
