### ISSUE TITLE
TypeError: url type not understood: ..Unable to read json file objects keys from aws s3 ; . using dask

### ISSUE THREAD

**Issue by shivatharun** [dask/dask#6005]
Hello,

I'm trying to read aws s3 file object keys,while using dask data frame encountering an error but its working fine when I'm using pandas.

- I am passing explicit date as parameter(lets say "20200311") to run, my regex  will return all the file keys which are 20200311 and will store in data_objects

- data_objects is a variable list of aws s3 json file object keys as below syntax

```
data_objects = [s3.Object(bucket_name=BUCKET_NAME,                        
                       key='bucketname/folder1=20200311/folder2/folder3/folder4/folder5/jsonfile1')]

```

**CODE :**
```

dd.read_json(data_objects.get()['Body'].read(), lines=True, convert_dates=False)


```

**ERROR**
```

Traceback (most recent call last):
  File "py.py", line 53, in <module>
    print([dd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in  data_objects])
  File "py.py", line 53, in <listcomp>
    print([dd.read_json(data_object.get()['Body'].read(), lines=True, convert_dates=False) for data_object in  data_objects])
  File "/usr/local/lib/python3.6/site-packages/dask/dataframe/io/json.py", line 207, in read_json
    **storage_options
  File "/usr/local/lib/python3.6/site-packages/fsspec/core.py", line 205, in open_files
    protocol=protocol,
  File "/usr/local/lib/python3.6/site-packages/fsspec/core.py", line 408, in get_fs_token_paths
    raise TypeError("url type not understood: %s" % urlpath)
TypeError: url type not understood:


```
It's working fine when I'm using  pandas.

**Comment by mrocklin** [comment]
Thank you for raising an issue @shivatharun 

What is the type of the object that you're passing into the `dd.read_json` function?  I believe that that function expects a string.  Maybe you're passing something else?  I'm not very familiar with the `s3.Object` type unfortunately.  My guess is that this is not well understood by Dask either.

**Comment by mrocklin** [comment]
Closing due to lack of response.
