### ISSUE TITLE
Pickle version mismatch

### ISSUE THREAD

**Issue by seanfarley** [dask/dask#6007]
While playing with dask-cloudprovider on my new laptop, it seems that a user will encounter an error when using python3.8 due to its change of the pickle version: `ValueError: unsupported pickle protocol: 5`.

My question is should dask be using `pickle.DEFAULT_PROTOCOL` instead of `pickle.HIGHEST_PROTOCOL`?

https://github.com/dask/dask/blob/master/dask/multiprocessing.py#L26

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @seanfarley. Are you running Python 3.8 on one machine and Python<3.8 on another? It's my understanding that pickle isn't guaranteed to work across different version of Python

**Comment by seanfarley** [comment]
It's guaranteed to work if both support the same version (which in this case is `4`). The main issue here is actually with `dask.distributed` (as I learned after opening this issue): https://github.com/dask/distributed/blob/master/distributed/protocol/pickle.py#L30-L54

Also, something to note, is that I didn't choose the python versions of either machine. Python 3.8 is what homebrew installed and `FargateCluster` chose python 3.7.

**Comment by jrbourbeau** [comment]
> It's guaranteed to work if both support the same version

Ah I see, thanks that's good to know! My understanding was a little off, after looking into it more what I should have said is that `cloudpickle` is only guaranteed to work across the same version of Python. That's outlined in the `cloudpickle` repo README and this comment https://github.com/cloudpipe/cloudpickle/issues/293#issuecomment-502011167 gives some reasoning for why the Python version has to be the same (tl;dr in some cases `cloudpickle` has to send Python bytecode).

In general software environments need to be the same between the `Client` and `Worker` processes (https://distributed.dask.org/en/latest/protocol.html#cross-language-specialization)

> Python 3.8 is what homebrew installed and FargateCluster chose python 3.7

By default `FargateCluster` will use the `daskdev/dask:latest` docker images which are pulling in Python 3.7. I've opened up https://github.com/dask/dask-docker/issues/88 to see about bumping the dask docker images to use Python 3.8.

**Comment by seanfarley** [comment]
Thanks for the explanation!

Maybe to improve the user experience we could warn about python / pickle version mismatch? I noticed there were some warnings about dask specific library mismatch so we could use that as prior art?

It's a shame about pickle, though. In my local environment, I monkey-patched `dask` and `dask.distributed` (didn't touch `cloudpickle`) and that made things work. Would it be possible to upstream that? Or is the risk too much?

**Comment by jrbourbeau** [comment]
> we could warn about python / pickle version mismatch

+1 good idea. The current version checking logic is here https://github.com/dask/distributed/blob/b809777d250152edb52b846e9c1c12a20f500878/distributed/versions.py#L128-L134 and could be modified to also check the Python version

What does the patch look like? In general we need to be able to serialize arbitrary `lambda`s

**Comment by mrocklin** [comment]
It looks like we grab the Python version, but don't include it as a package and so it doesn't go through the same error handling as the Python packages themselves.

**Comment by thoth291** [comment]
@seanfarley 
> It's a shame about pickle, though. In my local environment, I monkey-patched `dask` and `dask.distributed` (didn't touch `cloudpickle`) and that made things work. 

I hit the same issue and was wondering how did you made your patch? Can you please share it?
