### ISSUE TITLE
Errors with datetime (.dt) methods(dt.hour, dt.minute, etc) on a date-time like column

### ISSUE THREAD

**Issue by rnyak** [dask/dask#6014]
Describe the bug

I am working on a dask-cudf data frame. I want to calculate difference between two datetime columns, and get the total_seconds via `dt.total_seconds()`, but I am getting the errors defined below.

Steps/Code to reproduce bug
The steps I am following:
```
import cudf
cdf = cudf.DataFrame()
cdf['tpep_pickup_datetime'] = ['2015-01-15 19:05:39', '2015-01-10 20:33:38', '2015-01-10 20:33:38', '2015-01-10 20:33:39', '2015-01-10 20:33:39']
cdf['tpep_dropoff_datetime'] = ['2015-01-15 19:23:42', '2015-01-10 20:53:28', '2015-01-10 20:43:41', '2015-01-10 20:35:31', '2015-01-10 20:52:58']
cdf['passenger_count'] = [1, 1, 1, 1, 1]
ddf=dask_cudf.from_cudf(cdf, npartitions=2)

ddf.dtypes
tpep_pickup_datetime     object
tpep_dropoff_datetime    object
passenger_count           int64
dtype: object

attributes = {
 'pickup_datetime': 'M8[ns]',
 'dropoff_datetime': 'M8[ns]',
 'passenger_count': 'int32',
}
    
def clean(df_part):      
    # iterate through columns in this df partition
    for col in df_part.columns:
        if df_part[col].dtype == 'object' and col in ['pickup_datetime', 'dropoff_datetime']:
            df_part[col] = df_part[col].astype('M8[ns]')
            continue
        
        if 'int' in str(df_part[col].dtype):
            df_part[col] = df_part[col].astype('int32')
    return df_part

ddf =  ddf.map_partitions(clean, meta=attributes)

ddf.head()

	pickup_datetime	dropoff_datetime	passenger_count
0	2015-01-15 19:05:39	2015-01-15 19:23:42	1
1	2015-01-10 20:33:38	2015-01-10 20:53:28	1
2	2015-01-10 20:33:38	2015-01-10 20:43:41	1

ddf.dtypes
pickup_datetime     datetime64[ns]
dropoff_datetime    datetime64[ns]
passenger_count              int32
```
Error 1. I cannot convert datetimelike to  'M8[ms]' or 'M8[s]'.  When I replace 'M8[ns]') above,it yields`TypeError: cannot convert datetimelike to dtype [datetime64[ms]]`

With dask 2.11.0 I could do as follows:
```
attributes = {
 'pickup_datetime': 'datetime64[s]',
 'dropoff_datetime': 'datetime64[s]',
 'passenger_count': 'int32'
```
But, that does not work with dask 2.12.0

Error 2.  I cannot use `dt.total_seconds()` method:
```
ddf['pickup_datetime'].dt.total_seconds().head()

---> 93             raise AttributeError(key)
     94 
     95 

AttributeError: total_seconds
```

Is there a way that I can calculate the time difference between ` = (ddf['dropoff_datetime'] - ddf['pickup_datetime'])` in seconds? I want to obtain total seconds.

**Comment by mrocklin** [comment]
I'm curious, does everything work if you use just cudf, rather than dask + cudf?

**Comment by quasiben** [comment]
This issue is also being discussed on cudf:
https://github.com/rapidsai/cudf/issues/4473

**Comment by rnyak** [comment]
@quasiben  yes I created the that issue.

**Comment by mrocklin** [comment]
OK, closing this issue in favor of that one.  @rnyak if it's ok with you I'm going to ask you to not double post in the future.  Maintainer time is very limited.
