### ISSUE TITLE
Shape changes when element wise addition

### ISSUE THREAD

**Issue by GillesC** [dask/dask#6016]
I am reading two csv files. One containing the real and one containing the imaginary part.
I want to combine these values real + imag*i.
However, the shape changes after adding the two dataframes. 

```python
df_imag = dd.read_csv(imag_file_path, header=None) # shape (20227200,2)
df_real = dd.read_csv(real_file_path,header=None) # shape (20227200,2)

df_merged = df_real + 1j*df_imag 
df_merged = df_merged.compute() # shape (20267659,2)
```

**Comment by TomAugspurger** [comment]
Do the indices match? Pandas and dask align on binary operations.

A minimal example would make this easier to verify.

**Comment by GillesC** [comment]
Hi
I did not added any indices, so I would expect that when reading two CSV files with the same number of lines, they will have aligned indices?

**Comment by TomAugspurger** [comment]
Do they have the same number of lines and the same partitioning? A minimal example would be very helpful right now: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mrocklin** [comment]
I suspect that the partitioning of the two dataframes differs.  Dask dataframe's read_csv method breaks up a CSV file by bytes, for example cutting the file into 128MB chunks and using each chunk as one partition.  Unfortunately it's unlikely that the same size of bytes in each partition results in the exact same number of lines (unless your CSV files are very regular with the same line lengths and such).  Given that, it would be quite difficult to align two different csv file reads.

My recommendation in your situation would be to switch to some other file format with more metadata, like parquet.

**Comment by mrocklin** [comment]
So, I think that it would certainly be great if Dask Dataframe could identify and resolve issues like this, but I don't really see a path forward with a format like CSV.  Due to this, I'm going to close.  I apologize that we couldn't help you better @GillesC

**Comment by GillesC** [comment]
Hi @mrocklin 
Thank you for your clear explanation. It is of course understandable that you will not invest more time in a format such as CSV.
