### ISSUE TITLE
set_index fails for high valued int64 columns without explicit divisions

### ISSUE THREAD

**Issue by gorlins** [dask/dask#6020]
Under the hood, `set_index('col')` tries to guess the appropriate divisions using `numpy.percentile` which, unfortunately, returns all values as floats.  This can be catastrophic for integer columns where the values are high enough that precision is lost in the float conversion (eg, `int(float(val)) != val`).

In the worst case, I have seen divisions come back such that `divisions[0] > df.col.min()` resulting in ***rows dropping from the indexed result***.

Here is a basic illustration:

```python
from dask import dataframe as dask_df
import pandas as pd
import numpy as np
from pprint import pprint

ddf = dask_df.from_pandas(
    pd.DataFrame({"a": reversed(np.arange(5000))}), chunksize=250
)
offset = int(5e18) - 1
ddf["b"] = ddf.a + offset
pprint(ddf.head())
pprint(ddf.tail())
pprint(ddf.dtypes)

good_idx = ddf.set_index("a")
pprint(good_idx.divisions[:10])
# (0, 249, 499, 749, 999, 1249, 1499, 1749, 1999, 2249)
pprint(len(good_idx)) # 5000


broken_idx = ddf.set_index("b")
pprint([d - offset for d in broken_idx.divisions[:10]])
# [1, 1, 1, 1025, 1025, 1025, 1025, 2049, 2049, 2049]
pprint(len(broken_idx)) # 4999!!!!
```
Here's the head and tail from above:
```
      a                    b
0  4999  5000000000000004998
1  4998  5000000000000004997
2  4997  5000000000000004996
3  4996  5000000000000004995
4  4995  5000000000000004994
      a                    b
4995  4  5000000000000000003
4996  3  5000000000000000002
4997  2  5000000000000000001
4998  1  5000000000000000000
4999  0  4999999999999999999
```

I can think of two workarounds, both of which are pretty ugly.  Both involve processing the column, calculating the divisions, and post processing the results.  Here we go:

```python
def safe_set_int_index(df, col, **kwargs):
    divs = df[[col]].astype({col: str}).set_index(col, **kwargs).divisions
    return df.set_index(col, divisions=[int(d) for d in divs], **kwargs)


def safe_set_int_index2(df, col, **kwargs):
    mn = df[col].min().compute()
    divs = (df[[col]] - mn).set_index(col, **kwargs).divisions
    return df.set_index(col, divisions=[d + mn for d in divs], **kwargs)
```

Both work correctly for the above example, but clearly leave much to be desired.

I do not have an immediate idea for how to fix this in the library, but thought it would still be useful to share.

**Comment by gorlins** [comment]
Actually I suspect the following code is just incorrect in dask.dataframe.partitionquantiles:

```python
def percentiles_summary(df, num_old, num_new, upsample, state):
    ...
    # shouldn't this always be 'nearest' or 'lower'??
    interpolation = "linear"
    if is_categorical_dtype(data):
        data = data.codes
        interpolation = "nearest"
    vals, n = _percentile(data, qs, interpolation=interpolation)
    if interpolation == "linear" and np.issubdtype(data.dtype, np.integer):
        vals = np.round(vals).astype(data.dtype)
    vals_and_weights = percentiles_to_weights(qs, vals, length)
    return vals_and_weights
```

**Comment by TomAugspurger** [comment]
Which part is incorrect, and under what cases?

**Comment by gorlins** [comment]
At least for the purpose of finding divisions, linear interpolation is wrong for an integer index.  This turns it into a float value. I think for integer indices, for the purpose used here, it should be minimum or maybe nearest

**Comment by TomAugspurger** [comment]
That seems sensible. Are you interested in working on it?

**Comment by gorlins** [comment]
i cannot guarantee i have the time in the next 2ish weeks, but may come back shortly or find a teammate if there isn't a core maintainer who has a better idea of how to solve this or is better aware of the impact of any changes.

**Comment by martindurant** [comment]
ping @gorlins , did you ever end up working on this?

**Comment by martindurant** [comment]
If not, I suggest checking that this is still a case and making a new issue or reopening with a clear test case showing the problem (lost rows).
I'll close this for now.
