### ISSUE TITLE
Warning about auto_mkdir

### ISSUE THREAD

**Issue by perezzini** [dask/dask#6028]
Hello,

Simple issue. When reading a dataframe (in my case with, for now, with `read_csv()`), the following warning appears:
```
FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
```

And the most important is that the latter is an error (and not always appears) when computing:
```
{'error': 'Invalid arguments', 'details': 'The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.'}
```

Would be glad if someone discovered a path, or a work-around for this!

Thanks in advance!

**Comment by TomAugspurger** [comment]
What version of dask and fsspec?

**Comment by TomAugspurger** [comment]
You need to specify the argument as a storage option.

```python
In [10]: df = pd.DataFrame({"A": [1, 2]})

In [11]: df.to_csv("data.csv")

In [12]: dd.read_csv("data.csv", storage_options=dict(auto_mkdir=False)).compute()
Out[12]:
   Unnamed: 0  A
0           0  1
1           1  2
```

cc @martindurant, do you recall do we want this warning visible right now, or should dask be passing it automatically?

**Comment by perezzini** [comment]
> What version of dask and fsspec?

fsspec==0.6.3
dask==2.12.0

**Comment by perezzini** [comment]
> You need to specify the argument as a storage option.
> 
> ```python
> In [10]: df = pd.DataFrame({"A": [1, 2]})
> 
> In [11]: df.to_csv("data.csv")
> 
> In [12]: dd.read_csv("data.csv", storage_options=dict(auto_mkdir=False)).compute()
> Out[12]:
>    Unnamed: 0  A
> 0           0  1
> 1           1  2
> ```
> 
> cc @martindurant, do you recall do we want this warning visible right now, or should dask be passing it automatically?

Will try this and comment about this ASAP.
Thanks for the quick response!

**Comment by perezzini** [comment]
Here's a recent issue from SO: https://stackoverflow.com/questions/60764849/strange-warning-using-dask-dataframe-to-read-csv/60765410#60765410

Written by @hellocoldworld, member of my team.

**Comment by martindurant** [comment]
I don't think it's useful to dask users, no. In the next fsspec it can go away already, I think.

**Comment by perezzini** [comment]
> You need to specify the argument as a storage option.
> 
> ```python
> In [10]: df = pd.DataFrame({"A": [1, 2]})
> 
> In [11]: df.to_csv("data.csv")
> 
> In [12]: dd.read_csv("data.csv", storage_options=dict(auto_mkdir=False)).compute()
> Out[12]:
>    Unnamed: 0  A
> 0           0  1
> 1           1  2
> ```
> 
> cc @martindurant, do you recall do we want this warning visible right now, or should dask be passing it automatically?

This approach is apparently working in my project.

But I don't know if it could cause future errors, somewhere using other tools.

I'd like to keep this ticket open.

Thanks!

**Comment by jrbourbeau** [comment]
The latest release of `fsspec` (0.7.1) has removed the `auto_mkdir` warning. I'm going to close this issue for now as I don't think there's anything left to do within dask. @perezzini we can reopen if you run into any issues
