### ISSUE TITLE
Warning while Label Encoding

### ISSUE THREAD

**Issue by justlearn-spec** [dask/dask#6031]
**Problem Description:**

I'm doing a label encoding as below in dask.

categorical_cols = ['DFU', 'Segment', 'Location']

def encode(df):
    le = preprocessing.LabelEncoder()
    for i in categorical_cols:
        df[i] = df[i].astype('category')
        le.fit(df[i])
        df[i] = le.transform(df[i])
    return df

df[categorical_cols] = df[categorical_cols].map_partitions(encode, meta={'Name':'i8','Type':'i8','Gender':'i8'})

When I do df.head(), I'm getting the below warning and the encoding looks to have done as I expected. 

<string>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
<string>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

I understood what does it mean after reading several articles. But, how can I get rid of the warning message?

I don't think I'm doing a Copy and then label encoding.

**Comment by mrocklin** [comment]
I recommend producing a minimal reproducible example with a full traceback.  Please see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@justlearn-spec we'll reopen if you can provide a reproducible example.

And if the issue is with `dask_ml.preprocessing.LabelEncoder`, I'll ask you to open the issue over in https://github.com/dask/dask-ml
