### ISSUE TITLE
[Feature Request] AWS Batch multi node deployment

### ISSUE THREAD

**Issue by manugarri** [dask/dask#6033]
At my company we deal with millions of hourly jsonline encoded records that we store in s3. Since our workloads are batch oriented, we use AWS Batch for cost efficiency. 

However, the AWS Batch resources are capped at 64vcpus for a single machine. AWS batch supports [multi node deployment][(https://docs.aws.amazon.com/batch/latest/userguide/multi-node-parallel-jobs.html), which would be ideal for us since we can process thousands of files in parallel.

However, since this doesnt have yarn, I dont think we could use dask-yarn, is there any way/plan to support this use case?

**Comment by mrocklin** [comment]
There are many ways to deploy Dask on the cloud.  Given that you are on AWS you might find dask-cloudprovider useful.  https://cloudprovider.dask.org/en/latest/

**Comment by manugarri** [comment]
ok @mrocklin i have to say i had no idea dask-cloudprovider existed, that is awesome! THanks so much for sharing it, will close this then since it seems that project seems to suit my need :)

**Comment by mrocklin** [comment]
I'm glad to hear it.  In the future you may want to look through
https://docs.dask.org/en/latest/setup.html
