### ISSUE TITLE
cuDF reductions on the same groups

### ISSUE THREAD

**Issue by quasiben** [dask/dask#6034]
In trying to accommodate multiple [reductions on the same group](https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate):

> df.groupby(columns).aggregate(['sum', 'mean', 'max', 'min', 'std'])

cuDF is running into an [issue](https://github.com/rapidsai/cudf/issues/4388) with the current implementation of `std`.  The problem essentially comes down to not fully supporting the return types of pandas-style apply within cuDF.  The apply within dask groupby-apply framework for std resides here:

https://github.com/dask/dask/blob/2fae9e75a8ac03ea0c689d5d11755d98a370906e/dask/dataframe/groupby.py#L897-L899

Currently, in cuDF, this style reduction leads to a scalar value which then causes problems downstream because we expect series like things.

Because the apply is slow for cuDF and to deal with compatibility issues, we are looking at writing a `SUM_OF_SQUARES` aggregation: https://github.com/rapidsai/cudf/issues/4667 .   If we proceed, how open is dask to moving in a specialized bit of code into `def __compute_sum_of_squares` to better support cuDF?

**Comment by kkraus14** [comment]
For motivation, I'd also like to add that as the number of groups increases Pandas slows down dramatically as well. `apply` is inefficient not only for cuDF, but for Pandas as well, and avoiding `apply` for semi-common groupby aggregations will get speedups across the board.

**Comment by quasiben** [comment]
@TomAugspurger is a cythoninzed sum_of_squares aggregation something that Pandas would accept ?

**Comment by TomAugspurger** [comment]
To make sure I understand, is the proposal for something like `DataFrame.groupby(...).sum_squared_error()` that returns the groupwise SSE? That might be accepted, but historically MSE / SSE have been a bit too far on the statistics side of things for pandas (https://github.com/pandas-dev/pandas/issues/28004).

I'm also a bit unsure about why a `.agg(sum_squared_error)` that's written outside of pandas doesn't quite work.

**Comment by quasiben** [comment]
It doesn't quite work within cuDF beacause the `apply` on a `cudf.seriesGroupBy` fails due to packaging the output apply correctly (which is a little hard given apply robustness). 

In pandas this boils down to:

```python
In [24]: pd.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b'].apply(lambda x: (x ** 2).sum())
Out[24]:
a
1     41
2    136
Name: b, dtype: int64
```

Doing something similar with cudf:
> cudf.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b'].apply(lambda x: (x ** 2).sum())

Fails the output within the apply is a numpy.int:

```python
In [25]: cudf.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b'].apply(lambda x: (x ** 2).sum())
> /datasets/bzaitlen/miniconda3/envs/20200319/lib/python3.7/site-packages/cudf/core/groupby/groupby.py(337)apply()
    336         breakpoint()
--> 337         result = cudf.concat([function(chk) for chk in chunks])
    338         if self._sort:

ipdb> function(chunks[0])
41
ipdb> type(function(chunks[0]))
<class 'numpy.int64'>
```

It's the additional `sum` which is really causing the issue here.  Without it the operation (while incorrect) executes without issue

```python
In [26]: cudf.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b'].apply(lambda x: (x ** 2))
Out[26]:
0     16
1     25
2     36
3    100
Name: b, dtype: int64
```

So obviously things should be fixed in cuDF but while we exploring this issue we also noticed that performance here can be improved.  In a somewhat contrived example of doing just squares we can get a substantial improved by using `np.power` instead of the lambda:


```python
In [43]: srg = pd.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b']
In [44]: %timeit [np.power(srg.get_group(k).values,2) for k in srg.groups.keys()]
171 µs ± 3.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [45]: %timeit pd.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a')['b'].apply(lambda x: (x ** 2))
1.89 ms ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by mrocklin** [comment]
Does using a custom aggregation imply using `groupby-apply`?  I would expect Pandas to have an interface for custom aggregations that don't require pre-sorting data.

**Comment by mrocklin** [comment]
(We certainly do have such a thing in Dask, see dd.Aggregation)

**Comment by quasiben** [comment]
With dd.Aggregation we are back to using lambdas which will be slow.

Perhaps another alternative would be to implement groupby-describe:

```python
In [47]: pd.DataFrame({'a': [1,1,2,2],'b': [4,5,6,10]}).groupby('a').describe()
Out[47]:
      b
  count mean       std  min   25%  50%   75%   max
a
1   2.0  4.5  0.707107  4.0  4.25  4.5  4.75   5.0
2   2.0  8.0  2.828427  6.0  7.00  8.0  9.00  10.0
```

This could be done without lambdas

**Comment by mrocklin** [comment]
I don't understand why you have to use lambdas, or why they would be slow.

`dd.Aggregation` allows you to provide a function that you call on the cudf DataFrame partitions, and then another function to call on the aggregation of those results. You can do whatever you want to in those functions, including link to your own custom code.  You don't have to call `groupby-apply` or use lambdas, or anything like that.

**Comment by TomAugspurger** [comment]
I share Matt's question. In pandas, `groupby.agg(user_defined_function)` doesn't go through `groupby.apply`

**Comment by mrocklin** [comment]
I got on the phone briefly with @quasiben .  I think that his main pain point is coming from here: 

https://github.com/dask/dask/blob/2fae9e75a8ac03ea0c689d5d11755d98a370906e/dask/dataframe/groupby.py#L897-L899

It looks like at one point we took a shortcut and used a groupby-apply in the computation of var/std

https://github.com/dask/dask/blob/2fae9e75a8ac03ea0c689d5d11755d98a370906e/dask/dataframe/groupby.py#L770-L790

My guess is that if we can replace that groupby-apply with a proper groupby aggregation then his problems would go away (mostly)

**Comment by quasiben** [comment]
This is rather hacky and not fully supported in cuDF but does not use an `apply`:

```python
def _compute_sum_of_squares(grouped, column):
    base = grouped[column] if column is not None else grouped
    vals = [np.sum(np.power(base.get_group(k).values,2)) for k in base.groups.keys()]
    idx = list(base.groups.keys())
    name = base._selection_name
    sr = pd.Series(vals, name=name, index=idx)
    idx_name = base.dtype.index.name
    sr.index.name = idx_name
    return sr
```

**Comment by mrocklin** [comment]
The list comprehension over the groups is mostly the same though I think.

**Comment by kkraus14** [comment]
> I share Matt's question. In pandas, `groupby.agg(user_defined_function)` doesn't go through `groupby.apply`

Could you share an example of passing a UDF as opposed to a named aggregation through `.agg(...)`?


The core issue that we're trying to tackle here is avoiding codepaths that iterate over groups like `.apply` as it gives a potentially major slowdown for Pandas and a potentially catastrophic slowdown for cuDF.

**Comment by TomAugspurger** [comment]
> Could you share an example of passing a UDF as opposed to a named aggregation through .agg(...)?

IIUC, this is what you're asking for.

```python
In [5]: df = pd.DataFrame({"A": [1, 2, 3, 4], "B": ['a', 'a', 'b', 'b']})

In [6]: def sse(x):
   ...:     return ((x - x.mean()) ** 2).sum()
   ...:

In [7]: df.groupby("B").agg(sse)
Out[7]:
     A
B
a  0.5
b  0.5
```

But perhaps I misunderstood.

**Comment by mrocklin** [comment]
So my assumption is that groupby-aggregations like sum/mean/count/... don't form groups and then call sum/mean/count/... on those groups.  Instead they walk through the dataset once and update some sort of data structure in a clever way.  We want to do something similar here.

Hopefully we can find some clever way to reuse those existing built-in aggregations to do what we want.  My guess is that we won't be able to use the same groupby object, but will need to square the column first, and then do a groupby-sum ?

**Comment by TomAugspurger** [comment]
> So my assumption is that groupby-aggregations like sum/mean/count/... don't form groups and then call sum/mean/count/... on those groups. Instead they walk through the dataset once and update some sort of data structure in a clever way.

Gotcha, I think I understand now. That is indeed what pandas does for our aggregations like [groupby.sum()](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/groupby.pyx#L451-L498). There isn't a public API for this for user-defined functions.

With some care, we can get the same result in pandas using all "fast" ops 

```python
In [1]: import pandas as pd
   ...: import numpy as np
   ...:
   ...: N = 100_000
   ...:
   ...: df = pd.DataFrame(
   ...:     {"A": np.random.randint(0, 10, N),
   ...:      "B": np.random.randn(N)}
   ...: )
   ...:
   ...: def sse(x):
   ...:     return ((x - x.mean()) ** 2).sum()
   ...:

In [2]: %timeit df.groupby("A").B.agg(sse)
11 ms ± 266 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [3]: %%timeit
   ...: mean = df.groupby("A").B.transform("mean")
   ...: result = ((df.B - mean) ** 2).groupby(df.A).sum()
   ...:
   ...:
5.43 ms ± 98.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

In pandas, `.transform.mean()` does go through the special Cython ops. This does come at the cost of higher memory usage, since the `mean` result needs to be broadcast to the size of the original dataframe. And there are two calls to groupby / all the factorization necessary for that, rather than one.

**Comment by kkraus14** [comment]
@TomAugspurger in your above example you're generating 10 large groups, but say you were to generate 10_000 groups you'd likely see an even larger difference in performance.

**Comment by quasiben** [comment]
@kkraus14 yup:

```python
In [13]: N = 1_000_000                                                                                                                                                                                                                                       

In [14]: df = pd.DataFrame({"A": np.random.randint(0, 10_000, N), "B": np.random.randn(N)})                                                                                                                                                                  

In [15]: %timeit df.groupby("A").B.agg(sse)                                                                                                                                                                                                                  
4.09 s ± 9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [16]: %%timeit 
    ...:    ...: mean = df.groupby("A").B.transform("mean") 
    ...:    ...: result = ((df.B - mean) ** 2).groupby(df.A).sum() 
    ...:  
    ...:                                                                                                                                                                                                                                                     
43.9 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by TomAugspurger** [comment]
OK, so is anyone able to summarize the state of the issue? What remains to be done here / in pandas?

**Comment by kkraus14** [comment]
> OK, so is anyone able to summarize the state of the issue? What remains to be done here / in pandas?

I don't think anything needs to be done in Pandas from my perspective. Even with your `sse` example above, the calculated means would be incorrect unless we partitioned the data before doing local groupbys which would be unnecessarily expensive.

I think we still have more discussion needed from the Dask side to figure out a solution as to how we can avoid expensive iteration based codepaths for doing groupbys like `std` which can't be naively done via a tree reduction.

**Comment by mrocklin** [comment]
> I think we still have more discussion needed from the Dask side to figure out a solution as to how we can avoid expensive iteration based codepaths for doing groupbys like std which can't be naively done via a tree reduction.

It is currently being done with a tree reduction.  The concern now is that our current implementation needlessly uses a groupby-apply within one of the per-partition functions.  We do not use a groupby-apply on the full collection.  This needless use of a local groupby-apply is, I think, what needs to be fixed.

**Comment by mrocklin** [comment]
https://github.com/dask/dask/blob/2fae9e75a8ac03ea0c689d5d11755d98a370906e/dask/dataframe/groupby.py#L897-L899

My guess is that the current approach of using groupby-apply within the per-partition chunk function was chosen because we're getting a groupby object already, rather than having full access to the original dataframe and grouper.  My guess is that we need to unpack the groupby object, do some transformation to the original dataframe, then re-groupby with the provided key, and then do the sum.  That's just a guess though.

**Comment by beckernick** [comment]
@quasiben @rjzamora , I'd be interested in your thoughts on the above

**Comment by rjzamora** [comment]
@beckernick  - @mrocklin's [intuition](https://github.com/dask/dask/issues/6034#issuecomment-604643419) seems correct here.  Replacing the `_compute_sum_of_squares` definition with the following seems to fix the [`std` issue](https://github.com/rapidsai/cudf/issues/4388):

```python
def _compute_sum_of_squares(grouped, column):
    # Note: CuDF cannot use `groupby.apply`.
    # Need to unpack groupby to compute sum of squares
    if hasattr(grouped, "grouper"):
        keys = grouped.grouper
    else:
        keys = grouped.grouping._key_columns
        import pdb; pdb.set_trace()
    df = grouped.obj[column].pow(2) if column else grouped.obj.pow(2)
    return df.groupby(keys).sum()
```

@kkraus14 - Any ideas on a clean way to deal with (or align) the varying approaches needed to upack the groupby object?

**Comment by kkraus14** [comment]
@shwina is much more intimately familiar with cuDF groupby than myself where I'd defer to his expertise here.

I'd also suggest that we try to find a performant generalized solution, where if cuDF needs to go implement something to make it more Pandas-like then that's a perfectly good path.

**Comment by shwina** [comment]
Given a groupby object, it's possible to get both the grouped-by object as well as the grouping "key columns":

```
In [36]: a = cudf.DataFrame({'a': [1, 1, 2], 'b': [1, 2, 3], 'c': ['a', 'b', 'c']})

In [37]: gb = a.groupby(['a', 'b'])

In [38]: gb.obj
Out[38]:
   a  b  c
0  1  1  a
1  1  2  b
2  2  3  c

In [39]: gb.grouping.keys
Out[39]:
MultiIndex(levels=[0    1
1    2
dtype: int64, 0    1
1    2
2    3
dtype: int64],
codes=   a  b
0  0  0
1  0  1
2  1  2)
```

Is this what is required here?

**Comment by shwina** [comment]
Ah apologies -- I see from @rjzamora's comment above that what's really needed is for `cudf` groupby to provide a `.grouper` property just like Pandas.

There's one issue with this though: `.grouper` in Pandas returns an object of type `BaseGrouper`, which is an [implementation detail](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/ops.py#L64).

**Comment by kkraus14** [comment]
> I wonder if there's a public API Pandas exposes to unpack a groupby object into the original object and the key columns?

@TomAugspurger do you have any ideas / insights here?

**Comment by rjzamora** [comment]
@kkraus14 @quasiben - #6186 handles the "std" functionality issue.  Should we close this, or are there other related changes you wanted to plan/discuss here?

**Comment by quasiben** [comment]
I think this resolves the specifics of std.  Thank you for working on this @rjzamora and for the discussion @mrocklin and @TomAugspurger
