### ISSUE TITLE
Dependency: Limit Bokeh to < 2.0?

### ISSUE THREAD

**Issue by zac-hopkinson** [dask/dask#6035]
Would it make sense to limit the Bokeh dependency to `>= 1.0.0,< 2`? They recently released a new major version 2.0.0 which isn't backwards compatible.

https://github.com/dask/dask/blob/2fae9e75a8ac03ea0c689d5d11755d98a370906e/setup.py#L26

The dask-labextension project has made a similar change: https://github.com/dask/dask-labextension/pull/122

An example of where this causes problems:

* Start with a base environment that contains JupyterLab, Dask, dask-labextension and `bokeh=1.4.0`. 
* User creates a new Conda environment with Dask (`conda create -y -n test ipykernel dask=2.12.0`)
* Dask's Conda package installs Bokeh 2.0.0 as a dependency which breaks dask-labextension in the base environment running JupyterLab. (Error is what is shown in the dask-labextension issue above)

**Comment by xhochy** [comment]
The issue with bokeh was fixed in https://github.com/jupyterhub/jupyter-server-proxy/pull/180

Using `dask/distributed` without the proxy in between shows nice plots.

**Comment by jrbourbeau** [comment]
@zac-hopkinson does removing the proxy, or installing the latest release (which has the updates in https://github.com/jupyterhub/jupyter-server-proxy/pull/180) fix things for you?

**Comment by zac-hopkinson** [comment]
Upgrading jupyter-server-proxy to 1.3.0 fixes the issue. Thanks!
