### ISSUE TITLE
shutting down cluster running on baremetal k8s does not delete the service

### ISSUE THREAD

**Issue by giordyb** [dask/dask#6044]
I'm running dask on a baremetal Kubernetes cluster this way:

```
import dask
from dask.distributed import Client
from dask_kubernetes import KubeCluster

dask.config.config["kubernetes"]["scheduler-service-type"] = "LoadBalancer"
dask.config.config["kubernetes"]["namespace"] = "dask"
dask.config.set(scheduler="distributed")
cluster = KubeCluster.from_yaml("worker-spec.yml", deploy_mode="remote")
cluster.scale_up(4)

client = Client(my_cluster_ip)

```

if I run `cluster.close()` then the service get removed, if I run `client.shutdown()` then it does not

**Comment by gforsyth** [comment]
Thanks for reporting @giordyb!  `Client.shutdown` should call the `close` method, so that's an odd discrepancy.  Which version of `distributed` are you running?

**Comment by giordyb** [comment]
Hi @gforsyth ! No problem, I'm glad I'm able to contribute!

Both dask and distributed are 2.13.0

**Comment by gforsyth** [comment]
Ok, great.  I realize I also misread your initial report -- can you see if changing `client = Client(my_cluster_ip)` to `client = Client(cluster)` makes `client.shutdown()` kill your service?

**Comment by giordyb** [comment]
I can confirm that passing the cluster object instead of the "ipaddress:port" string to Client() successfully deleted the service.

**Comment by gforsyth** [comment]
Ok, great!  Are you ok with closing this issue ?

**Comment by giordyb** [comment]
Shouldn't it work anyways without using the cluster object though?
 
Sometimes one might need to close the python session that started the cluster (it may crash, the computer might lose power, etc) and reconnect from another one using the ipaddress:port string instead of passing the cluster object (which I may no longer have access to if I'm working from a new python session). 

I would expect to be able to cleanly shut the cluster down even if the original cluster object is not available.

**Comment by gforsyth** [comment]
The `cluster` object is your only way to scale up and scale down the number of workers (and interact with the cluster).  In your case, if you lose that object you can still interact with the scheduler but you've lost the ability to control it any further (other than shutting it down).

The scheduler is agnostic to where it is running (and there's nothing that inherently prevents you having workers running on a bare instance connect to a scheduler running on k8s) so without a cluster-level object there's a lot of unreliable guesswork that would go into doing the "right thing" if you only have a scheduler address.

You can shut down the scheduler cleanly, but things like k8s services need to be handled by something that is aware of k8s, which in this case is dask-kubernetes.

dask-gateway may provide some of the functionality I think you're looking for (specifically being able to reconnect to running clusters and control them from separate sessions).  There should be a new release cut in the coming weeks (things are still coalescing after a major refactor)

**Comment by giordyb** [comment]
Your explanation makes total sense, I was not aware of Dask-gateway, I'll definitely look into it. Thanks!
