### ISSUE TITLE
Issue when reading remote CSV

### ISSUE THREAD

**Issue by perezzini** [dask/dask#6046]
Hello,

I found that computing series from a remote CSV takes so much time. I can read the file successfully with:
```python
df = dd.read_csv("https://path/dataframe.csv")
```
but when computing, for example:
```python
df.head(1)
```
it REALLY takes a long time.

Could be something about `storage_options` that I am missing? Could be something about the protocol or server where dataframe is storaged?

Thanks for your time.

**Comment by quasiben** [comment]
@perezzini thanks for the report.  Would it be possible to share an a minimal example with public data ?  If you don't have a readily accessible public data set perhaps you can upload an example CSV to Gtihub and use that.

**Comment by perezzini** [comment]
Hi @quasiben .

Apparently it's something concerning server side with a particular CSV. I tried with other public dataframes and computing time for common operations were just OK.

But now, what it's causing me troubles is that with some public CSV files, the following error appears when reading:
```
Backing filesystem couldn't determine file size, cannot do chunked reads. To read, set blocksize=None
```
But using `blocksize=None` in Dask it's like losing what Dask is all about: I cannot longer split datataframes into chunks.

I red somewhere that this problem was "fixed", but it seems not to me. Or maybe I am missing something with respect to `fsspec` lib, etc.

Thanks for quick reply.

Example:
```python
df = dd.read_csv("https://data.lacity.org/resource/hpbr-2ant.csv")
```

**Comment by quasiben** [comment]
@perezzini yes, in http "filesystems" often there is no file size listed in the header so dask has no ability to chunk an unknown sized file.  You can see this info easily with `curl --head`

```
❯ curl --head https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-01.csv
HTTP/1.1 200 OK
x-amz-id-2: M6D3EVbnjVP4vZhNonbzbEBct0yv0Ek3rCC3w9MmaKMtA/XWELc+q6UvFA5B2SdO8xcK+60Kkwg=
x-amz-request-id: 5F530D47FC351F66
Date: Tue, 31 Mar 2020 15:04:33 GMT
Last-Modified: Wed, 14 Aug 2019 17:45:00 GMT
ETag: "1bfeb66e3a477c7ea21766ac97208340-40"
Accept-Ranges: bytes
Content-Type: text/csv
Content-Length: 687088084
Server: AmazonS3
```

Note: `Content-Length: 687088084` As opposed to,

```
❯ curl --head https://data.lacity.org/resource/hpbr-2ant.csv
HTTP/1.1 400 Bad Request
Server: nginx
Date: Tue, 31 Mar 2020 15:04:57 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Error-Code: invalid_request
X-Error-Message: HEAD is not supported
Cache-Control: private, no-cache, must-revalidate
Age: 0
X-Socrata-Region: aws-us-east-1-fedramp-prod
X-Socrata-RequestId: 4a0fd995390410323b84c2206de62f6a
``` 

Where no length is defined.

**Comment by perezzini** [comment]
Thanks @quasiben for your quick and clear response.

Do you know if in the case I start to store (CSV) dataframes in Amazon S3 "filesystem", `Content-Length` is a **MUST**. I mean, does every request (through `http(s)://` or `s3://`) **always** retrieves its own `Content-Length`, so I can use Dask's `read_csv()` *without any worries*?

I'm kind of new using file systems, and my team created a very useful project using Dask but we didn't test reading from remote data (and this is now extremely required).

Again, thanks for your response. Would like to know more about work-arounds about this "issue".

**Comment by quasiben** [comment]
I believe in the case of S3, `Content-Length` should be there and you should be able to use `read_csv` with blocksize. Is that right @martindurant  ?

**Comment by martindurant** [comment]
Yes, S3 provides the length through it's own API, which is what you get with "s3://". I believe the https endpoints for AWS S3 do too via a HEAD call. People use s3 and gcs for blockwise loading of large files all the time.

(The only caveat is that you should not specify the content-encoding for compression, even if the file is indeed, because it makes the byte range you read ambiguous)

**Comment by quasiben** [comment]
Thanks @martindurant for the response.  I think since there is no bug here we are good to close
