### ISSUE TITLE
Delayed objects of unspecified length are not iterable

### ISSUE THREAD

**Issue by hamidkhb** [dask/dask#6060]
I'm having a problem using  `Dask` on my own function in a cluster. I tried it on both functions and the same error is being generated. 

```
def alpha_beta_test(data, a, b1, b2, velocity, distance,t, validation=False, correction=False):
    if validation:
        length = int(data.shape[0]/10)
        #length=10
    else: length = data.shape[0]
    x_s = 0
    v_s = 0
    x_p = np.zeros(length)
    v_p = np.zeros(length)
    index_p = np.zeros((2,length))
    l = []
    for i in range(1, length-1):
        index = np.array(np.unravel_index(np.argmax(data[i,0]), data[i,0].shape))
        v_t = velocity[index[0]]
        x_t = distance[index[1]]
        ######  predict
        x_p[i] = x_s + t*v_p[i-1]
        v_p[i] = v_s
        dx = x_t - x_p[i]
        dv = v_t - v_p[i]
        if correction and len(l)>10:
            std = np.std(l)
            mu = np.mean(l)
            rv = st.norm(loc = mu, scale = std)
            p = rv.cdf(np.abs(dx)+0.7*std)-rv.cdf(np.abs(dx)-0.7*std)
            print(mu, std)
            if p>=0.5:
                x_s = x_p[i] + a * (dx)
                v_s = v_p[i] + b1 * (dv) + b2 * (dx)
            else:
                x_s = x_p[i]
                v_s = v_p[i]
        else:
            x_s = x_p[i] + a * (dx)
            v_s = v_p[i] + b1 * (dv) + b2 * (dx)

        ######  update
        l.append(np.abs(dx))
        index_p[0,i] = np.argmin(np.abs(velocity-v_p[i]))
        index_p[1,i] = np.argmin(np.abs(distance-x_p[i]))

    loss = sum(l)/len(l)
    return x_p, v_p, index_p, loss

def cleaning_data(data, anten=0,  p=0.5, cfar_scale=1.5, delete_frames=False):
    i=0
    deleted = []
    while i<data.shape[0]:
        index_max = np.array(np.unravel_index(np.argmax(data[i, anten,...]), data[i, anten,...].shape))
        if 20 < index_max[0] < 45 and index_max[1]<5 and delete_frames:
            deleted.append(data[i,anten,...])
            data = np.delete(data, i, axis=0)
        else:
            x = data[i, anten, ...]
            x[...,:10] = x.min()
            mask, threshold = rf.os_cfar2D(x, scale= cfar_scale)
            x[x<threshold]=x.min()
            v = (x.max()-x.min())*p+x.min()
            x[x<v]=x.min()
            data[i, anten, ...] = x
            i+=1
    print(i)
    return data, deleted


hostname = socket.gethostname()
print(hostname)
n_workers = 1
n_cores = 4

wks2 = "wn-wks2.fe.hhi.de"
gpu1 = "wn-gpu1.fe.hhi.de"
gpu2 = "wn-gpu-104-01.fe.hhi.de"

if hostname == wks2:
    mem = "16G"      # Allocated memory is critical. For this example it must be at least 16GB 
    q = "wn-35.q"    # Check current queue status on https://hpc-management.fe.hhi.de/wn/phpqstat/
    
    cluster = SGECluster(n_workers=1, cores=n_cores, memory=mem,
                         queue=q, resource_spec=f"h_vmem={mem}", scheduler_options={"host":hostname},
                         job_extra=["-v MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1"])
elif hostname in (gpu1, gpu2):
    
    os.environ["CUDA_VISIBLE_DEVICES"]="3"  # Check current status with nvidia-smi and pick GPU from 0-3
    cluster = LocalCluster(n_workers=n_workers, threads_per_worker=n_cores, host=hostname)
else:
    raise ValueError(f"{hostname} is not a supported host. Please run this example on {wks}, {gpu1} or {gpu2}.")

client = Client(cluster)
client.wait_for_workers(n_workers=n_workers)


clean_data, _ = dask.delayed(ab.cleaning_data)(data)
clean_data.compute()

```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @hamidkhb. Is that entire code snippet needed to reproduce the issue you're running into? Could you provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)?

**Comment by hamidkhb** [comment]
@jrbourbeau so in general I cant use Dask on functions that I cant edit right? and I can use Dask only on very simple functions? right?

**Comment by mrocklin** [comment]
You can use dask on any function, but the people volunteering their time to
help you here probably won't inspect very complex functions for you.  If
you're asking for help we ask that you create a simple example of the bug
that you think you've found.  Otherwise it takes us many hours to figure
out your situation.

**Comment by jrbourbeau** [comment]
I recommend reading through the delayed documentation (https://docs.dask.org/en/latest/delayed.html). In particular, the best practices page is a useful resource (https://docs.dask.org/en/latest/delayed-best-practices.html). Just to second @mrocklin's point, without an example [others can run](https://blog.dask.org/2018/02/28/minimal-bug-reports) it makes it very difficult for maintainers or other community members to help you

**Comment by hamidkhb** [comment]
@jrbourbeau , @mrocklin thanks for your tipps and answers. I used the linkes and they were very useful but my question was in general about the limitations of Dask and if there is anything I have to know about. And the second question was what causes this error in general because I get this almost every where and cand find anaything online about it. But I will try to simplify the code and try again.

**Comment by martindurant** [comment]
I would say that the error is rather clear, especially when comparing with the docstring of `delayed`: when you delay an operation, there is no way to tell how many outputs it will have without running the operation. The only way to iterate, then, is to know beforehand how many outputs you expect, and you can tell Dask this, with the `nout` parameter:

```
@dask.delayed(nout=2)
def makes_two():
    return 1, 2

out1, out2 = makes_two()
out1.compute()
```

**Comment by hamidkhb** [comment]
@martindurant exactly what I needed thanks.

**Comment by TomAugspurger** [comment]
Good to hear.

**Comment by joaomedeiros** [comment]
> I would say that the error is rather clear, especially when comparing with the docstring of `delayed`: when you delay an operation, there is no way to tell how many outputs it will have without running the operation. The only way to iterate, then, is to know beforehand how many outputs you expect, and you can tell Dask this, with the `nout` parameter:
> 
> ```
> @dask.delayed(nout=2)
> def makes_two():
>     return 1, 2
> 
> out1, out2 = makes_two()
> out1.compute()
> ```

I have a question, what happens if after out1.compute(), I call out2.compute()? The makes_two function will be executed again? or how to get out1 and out2 without running makes_two twice?

**Comment by joaomedeiros** [comment]
I tried to answer myself, I'm not sure if I did in the right way:

`@dask.delayed(nout=2)
def makes_two():
    result = [1., 2.]
    return result`

`result = makes_two()
r = resul.compute()
out1 = r[0]
out2 = r[1]`
