### ISSUE TITLE
[Bug] to_csv fails to create directory

### ISSUE THREAD

**Issue by ayushdg** [dask/dask#6062]
Writing a Dask Dataframe `to_csv` fails to create a directory to store the `part` files if the directory doesn't exist.

Reproducer:
```python
from dask import dataframe as dd
import pandas as pd
import numpy as np

df = pd.DataFrame({'a':np.ones(100),'b':np.ones(100)})
ddf = dd.from_pandas(df,npartitions=2)
ddf.to_csv("df_result")
```
<details>
<summary>Error Stacktrace</summary>

<pre>
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-0d4266fadf0f> in <module>
      5 df = pd.DataFrame({'a':np.ones(100),'b':np.ones(100)})
      6 ddf = dd.from_pandas(df,npartitions=2)
----> 7 ddf.to_csv("df_result")

python3.7/site-packages/dask/dataframe/core.py in to_csv(self, filename, **kwargs)
   1347         from .io import to_csv
   1348 
-> 1349         return to_csv(self, filename, **kwargs)
   1350 
   1351     def to_json(self, filename, *args, **kwargs):

python3.7/site-packages/dask/dataframe/io/csv.py in to_csv(df, filename, single_file, encoding, mode, name_function, compression, compute, scheduler, storage_options, header_first_partition_only, **kwargs)
    787         )
    788     if compute:
--> 789         delayed(values).compute(scheduler=scheduler)
    790         return [f.path for f in files]
    791     else:

python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     82         get_id=_thread_get_id,
     83         pack_exception=pack_exception,
---> 84         **kwargs
     85     )
     86 

python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

python3.7/site-packages/dask/dataframe/io/csv.py in _write_csv(df, fil, depend_on, **kwargs)
    590 
    591 def _write_csv(df, fil, *, depend_on=None, **kwargs):
--> 592     with fil as f:
    593         df.to_csv(f, **kwargs)
    594     return None

python3.7/site-packages/fsspec/core.py in __enter__(self)
     97         mode = self.mode.replace("t", "").replace("b", "") + "b"
     98 
---> 99         f = self.fs.open(self.path, mode=mode)
    100 
    101         self.fobjects = [f]

python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    772                 autocommit=ac,
    773                 cache_options=cache_options,
--> 774                 **kwargs
    775             )
    776             if not ac:

python3.7/site-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
    106         if self.auto_mkdir:
    107             self.makedirs(self._parent(path), exist_ok=True)
--> 108         return LocalFileOpener(path, mode, fs=self, **kwargs)
    109 
    110     def touch(self, path, **kwargs):

python3.7/site-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit, fs, **kwargs)
    173         self.autocommit = autocommit
    174         self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 175         self._open()
    176 
    177     def _open(self):

python3.7/site-packages/fsspec/implementations/local.py in _open(self)
    178         if self.f is None or self.f.closed:
    179             if self.autocommit or "w" not in self.mode:
--> 180                 self.f = open(self.path, mode=self.mode)
    181             else:
    182                 # TODO: check if path is writable?

FileNotFoundError: [Errno 2] No such file or directory: '/home/adattagupta/df_result/0.part'
</pre>
</details>

Environment info
```
Dask from master (April 2)
dask                      2.13.0+5.g5d5b43b          pypi_0    pypi
fsspec                    0.7.1                      py_0    conda-forge
```

Did not see the same issue with `parquet` or `json`

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ayushdg. It appears that changes in `fsspec` impacted our behavior here. With `fsspec==0.6.3` the output directory is created, while with `fsspec==0.7.0` the directory is not created and a `FileNotFoundError` error is raised. auto_mkdir

cc @martindurant. Do you think we should pass `auto_mkdir=True` to `fsspec`?

**Comment by martindurant** [comment]
No, becaus that's only relevant to local FS. I would explicitly do `fs.mkdirs( , exist_ok=True)`, which an FS may choose to implement as a no-op.

**Comment by jrbourbeau** [comment]
@ayushdg is this something you're interested in working on? (no obligation though)

**Comment by martindurant** [comment]
(I decided this is something that might be generally useful in fsspec)
