### ISSUE TITLE
Array flag inconsistencies

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#6071]
Currently when a `dask.array` computation returns a NumPy array, the flags for the returned array can vary depending on the scheduler used and other factors like the number of chunks before concatenation to a single NumPy array, if compression was used, etc. Below are a couple of examples which demonstrate how array flags can vary depending on the scheduler used (in particular the `writeable` flag).

<details>
<summary>Example 1:</summary>

In this snippet the `"threads"` and `"processes"` schedulers are successful, but the distributed scheduler throws a `output array is read-only` error

```python
import numpy as np
import dask.array as da
from distributed import Client

y = np.ones(10_000)
dy = da.from_array(y, chunks=-1)

with Client() as client:
    for scheduler in ["threads", "processes", "distributed"]:
        print(f"scheduler = {scheduler}")
        
        dy_result = dy.compute(scheduler=scheduler)

        # Perform operation using original NumPy array
        try:
            y += 1
        except Exception as e:
            print(f"Got error (numpy): {e}")
        
        # Perform same operation using NumPy array returned from Dask
        try:
            dy_result = dy.compute(scheduler=scheduler)
            dy_result += 1
        except Exception as e:
            print(f"Got error (dask): {e}")
        
        print("\n")
```

outputs

```
scheduler = threads


scheduler = processes


scheduler = distributed
Got error (dask): output array is read-only
```

</details>

<details>
<summary>Example 2:</summary>

In this snippet, the `"threads"` scheduler throws a `output array is read-only` error (the expected behavior from NumPy), while the `"processes"` and `"distributed"` scheduler do not

```python

import numpy as np
import dask.array as da
from distributed import Client
    
x = np.random.random(10)
y = np.broadcast_to(x, shape=(6, 10))
dy = da.broadcast_to(x, shape=(6, 10))

with Client() as client:
    for scheduler in ["threads", "processes", "distributed"]:
        print(f"scheduler = {scheduler}")

        dy_result = dy.compute(scheduler=scheduler)

        # Perform operation using original NumPy array
        try:
            y += 1
        except Exception as e:
            print(f"Got error (numpy): {e}")
        
        # Perform same operation using NumPy array returned from Dask
        try:
            dy_result = dy.compute(scheduler=scheduler)
            dy_result += 1
        except Exception as e:
            print(f"Got error (dask): {e}")
        
        print("\n")
```

outputs

```
scheduler = threads
Got error (numpy): output array is read-only
Got error (dask): output array is read-only


scheduler = processes
Got error (numpy): output array is read-only


scheduler = distributed
Got error (numpy): output array is read-only
```

</details>

This inconsistency in the returned array flags can lead to confusing behavior for users and may be something we want to consider standardizing. A few options that come to mind are:

1. We choose a set of array flags we always want Dask to return (e.g. always writeable) and use [`numpy.require`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.require.html) in `dask.array.core.finalize` to ensure those flags are set. This would ensure that we always return an array with the same flags, though perhaps not the same as if using the equivalent NumPy operations.

2. We do nothing. This issue only recently came to my attention and I suspect it's not something that negatively impacts a large number of users (at least I didn't see it pop up in the issue tracker). It may be that we don't want to deal with any associated maintenance burden unless we know there are lots of users who take issue with the current behavior. 

3. We allow a hook into `da.core.finalize`. This would allow users to, for example, use `numpy.require` to set whatever array flags they want. 

4. Something else?

cc'ing @jakirkham @mrocklin @jcrist as they may be interested in this topic

**Comment by jcrist** [comment]
Hmmm. I'm surprised we end up with read only arrays ever from distributed/multiprocessing. My understanding is that these *can* occur when the backing buffer isn't fully owned by that array (but not all views are readonly), but I don't fully understand how that's happening when serialized back from the distributed scheduler since the output is effectively recreated locally.

My gut is that we should ensure outputs from the distributed scheduler are always writeable, since we're recreating them locally we should be able to dictate their flags (at least writeable). I think example 1 is a bug, but example 2 might be expected since the arrays are copied.

Have you dug into where this difference in example 1 is coming from?

**Comment by jakirkham** [comment]
It likely happens because we generate a `bytes` object somewhere and use that to back a NumPy `ndarray`.

```python
In [1]: import numpy as np                                                      

In [2]: b = b"abc"                                                              

In [3]: a = np.asarray(memoryview(b))                                           

In [4]: a.flags                                                                 
Out[4]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

**Comment by jakirkham** [comment]
TBH I'd actually be ok with returning read-only arrays in all cases. In general the user shouldn't be manipulating arrays coming as inputs to their function.

**Comment by jcrist** [comment]
Hmmm, and since byte objects are immutable we can't really avoid making a copy here if we want things to be writeable. If only there was a way to get a memoryview or bytearray instead of bytes.

> In general the user shouldn't be manipulating arrays coming as inputs to their function.

This seems like a fine answer, since copying by default adds extra overhead we may want to avoid.

**Comment by jakirkham** [comment]
I don't know all the places this might happen. Compressors may use `bytes` objects for example. This is one place where I'm aware of this happening ( https://github.com/dask/distributed/pull/3710 ).

**Comment by jrbourbeau** [comment]
Thanks for the feedback @jcrist @jakirkham! 

Re: always returning read-only arrays. I'm slightly hesitant as this could break user code where Dask is used for some larger-than-memory part of a workload that then continues using the returned in-memory NumPy array

```python
# use Dask for some large computation
result = <dask-array>.compute()

# Proceed with rest of workload using the returned NumPy array
result += 1
...
```

> Compressors may use bytes objects for example

Good point, that seems to be what's happening in Example 1 above. Using `y = np.ones(10_000)` in the example we end up using the `lz4` compressor and the array returned is read-only. If I make the the array smaller, i.e. `y = np.ones(10_000)` -> `y = np.ones(1_000)`, the array returned by the distributed scheduler is writable

**Comment by jakirkham** [comment]
Yeah if we want `.compute(...)` to generate a writeable array, that makes more sense to me.

Was more thinking of arrays within a pipeline.

**Comment by GFleishman** [comment]
@jrbourbeau @jcrist @jakirkham 

What is the status of this discussion?

For the past few days I've been tracking down a problem in my workflow that boiled down to inconsistent values for the WRITEABLE flag for blocks in a `da.map_overlap` call on a larger-than-memory array distributed over workers on a dask-jobqueue LSFCluster.

Each block is large, and over-writing the portion of the block I need to modify in place within my mapped function is the most efficient choice for me; but some of the blocks are not writeable. I tried `block.setflags(write=1)` but this throws an exception. I don't know enough about how memory is shared between workers via the scheduler to understand why I can't modify the data or the flag.

**Comment by jakirkham** [comment]
Would use [`np.require`]( https://numpy.org/doc/stable/reference/generated/numpy.require.html ) instead. This can be done like so `np.require(a, requirements="W")`.

The issue with `setflags` is it is trying to change the flags on the existing array. If that is already read-only, then that will fail. Whereas `np.require` will just pay the cost of a `memcpy` to create a new array to meet the requirement if needed.

**Comment by martindurant** [comment]
Marking as "good first issue", since `require` should solve this issue and would not be hard to add.

**Comment by jakirkham** [comment]
Actually I think we already fixed this in Distributed. Not sure what else is needed here
