### ISSUE TITLE
DataFrames with nullable integer or new string dtype don't support the full roundtrip to parquet

### ISSUE THREAD

**Issue by msebbah** [dask/dask#6085]
Hi guys,

Regarding the nullable integer dtype, pandas v1.0.0 offers the writing and reading back in with to_parquet() / read_parquet() starting with pyarrow >= 0.16.
It seems Dask Dataframes do not comply yet
```python
import dask.dataframe as dd

df = dd.from_pandas(pd.DataFrame({'A': [1, None]}, dtype='Int64'), npartitions=1)
df.to_parquet('foo', engine='pyarrow')
dd.read_parquet('foo', engine='pyarrow').compute().dtypes
```
Out: A    float64
dtype: object

However the _meta attribute looks good:
```python
dd.read_parquet('foo', engine='pyarrow')._meta.dtypes
```
Out: A    Int64
dtype: object

Same issue with the new string dtype

I am happy to help, by the way!

**Comment by TomAugspurger** [comment]
Thanks for the report. The fact that the metadata is correct is helpful.

The issue seems to be the `ignore_metadata` at https://github.com/dask/dask/blob/263187bbc263a395dc871e5874ee4fda21abb190/dask/dataframe/io/parquet/arrow.py#L549

```
517  ->	        df = df.to_pandas(categories=categories, use_threads=False, ignore_metadata=True)[
518  	            list(columns_and_parts)
519  	        ]
520
521  	        if index:
522  	            df = df.set_index(index)
523  	        return df
(Pdb) df
pyarrow.Table
A: int64
metadata
--------
{b'pandas': b'{"index_columns": [{"kind": "range", "name": null, "start": 0, "'
            b'stop": 2, "step": 1}], "column_indexes": [{"name": null, "field_'
            b'name": null, "pandas_type": "unicode", "numpy_type": "object", "'
            b'metadata": {"encoding": "UTF-8"}}], "columns": [{"name": "A", "f'
            b'ield_name": "A", "pandas_type": "int64", "numpy_type": "Int64", '
            b'"metadata": null}], "creator": {"library": "pyarrow", "version":'
            b' "0.16.0"}, "pandas_version": "1.0.3"}'}
(Pdb) df.to_pandas(ignore_metadata=True).dtypes
A    float64
dtype: object
(Pdb) df.to_pandas(ignore_metadata=False).dtypes
A    Int64
dtype: object
```

@msebbah I would start by removing that `ignore_metadata` and seeing what breaks. Are you interested in working on that. Or we could ping @rjzamora and ask if he recalls why it's there :)

**Comment by martindurant** [comment]
`ignore_metadata` was probably included specifically for setting the index - in case the user wants a different index from the default one.

**Comment by rjzamora** [comment]
> ignore_metadata was probably included specifically for setting the index - in case the user wants a different index from the default one.

Right - The `ignore_metadata=True` is used to prevent pyarrow from using the metadata to set the index.  The user may want a different column to be used as the index (or just a default RangeIndex).   We do not **need** to do this if there is other metadata information that we really **do not** want to ignore...  I will try to think of a resonable way to clean up the logic

**Comment by martindurant** [comment]
Is setting the index a cheap operation? You could always  
```
df.to_pandas(categories=categories, use_threads=False, ignore_metadata=False).reset_index()[list(columns_and_parts)]
```

**Comment by rjzamora** [comment]
> Is setting the index a cheap operation? You could always

I did confirm that it **does** work to do that.  However, it seems to take a few seconds on a large (30mil rows) `dask.datasets.timeseries` partition.

**Comment by martindurant** [comment]
@TomAugspurger , is there a reason that re/setting the index should take any time. I can only think of the case that it's a range that would get materialised into a data array.

**Comment by rjzamora** [comment]
Sorry @martindurant - explicitly using `inplace=True` after the read + pyarrow->pandas conversion seems to be much faster.

**Comment by rjzamora** [comment]
Trying to set up an environment with pyarrow 16.0 to add a test.  However, the following changes seem to work fine on exisiting tests:

```python
df = piece.read(
    columns=columns,
    partitions=partitions,
    use_pandas_metadata=True,
    use_threads=False,
    **kwargs.get("read", {}),
).to_pandas(
    categories=categories, use_threads=False, ignore_metadata=False
)
df.reset_index(drop=False, inplace=True)
df = df[list(columns_and_parts)]

if index:
    df = df.set_index(index)
return df
```

**Comment by martindurant** [comment]
I wonder if it's worth looking out for a range-index (i.e., one that has no data column, only metadata)

**Comment by rjzamora** [comment]
> I wonder if it's worth looking out for a range-index (i.e., one that has no data column, only metadata)

Good call - There should be no reason to reset the index if `isinstance(df.index, pd.RangeIndex)`
