### ISSUE TITLE
@pytest.mark.slow is "Unknown"

### ISSUE THREAD

**Issue by AndrewYinLi** [dask/dask#6086]
Environment details: `conda 3.7.6, dask==2.14.0, pytest==5.4.1`

Specific import from `dask`: `from dask.bytes.tests.test_s3 import boto3`

Using `pytest` to test my files. I get this warning from `dask/bytes/tests/test_s3.py:113`:

```
/Users/andrewli/opt/anaconda3/envs/condaenvname/lib/python3.7/site-packages/dask/bytes/tests/test_s3.py:113
  /Users/andrewli/opt/anaconda3/envs/condaenvname/lib/python3.7/site-packages/dask/bytes/tests/test_s3.py:113: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @pytest.mark.slow

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by martindurant** [comment]
There are many tests in the suite which are marked as "slow"

> `from dask.bytes.tests.test_s3 import boto3`

Were you doing this import yourself? Many things in the test modules only make sense while running pytest. If I run `pytest dask/bytes/tests/test_s3.py`, I do not see the warning you mention. Perhaps you could give a bit more detail on what it is you were doing?

**Comment by TomAugspurger** [comment]
For reference, we do register this marker in our setup.cfg: https://github.com/dask/dask/blob/263187bbc263a395dc871e5874ee4fda21abb190/setup.cfg#L37

**Comment by AndrewYinLi** [comment]
@martindurant ah I see, I shouldn't be making this import myself haha
