### ISSUE TITLE
Can't find (and can't install) 'tlz' module

### ISSUE THREAD

**Issue by rbdm-qnt** [dask/dask#6088]
I've tried installing dask and dask[dataframe] to work on some parquet files, but everytime I try to even just import it I get this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/core.py", line 18, in <module>
    from tlz import merge, first, unique, partition_all, remove
ModuleNotFoundError: No module named 'tlz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rob/Desktop/bot_alpha_v1/parquet_data_processor_v1.py", line 3, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 56, in <module>
    raise ImportError(msg) from e
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install dask[dataframe] --upgrade  # or python -m pip install

And if I try to manually install the tlz library from the terminal I get:

ERROR: Could not find a version that satisfies the requirement tlz (from versions: none)
ERROR: No matching distribution found for tlz

I'm using Python 3.7 on MacOS 10.12.6. It there any workaround for this? Thanks in advance

**Comment by TomAugspurger** [comment]
tlz is provided by the toolz and cytoolz packages.

How did you install Dask? It should be included when you install with conda or pip.

**Comment by rbdm-qnt** [comment]
I installed it with pip3 install dask, then tried pip3 install "dask[complete]" and also pip3 install dask[dataframe]    also tried pip3 install tlz and got:

ERROR: Could not find a version that satisfies the requirement tlz (from versions: none)
ERROR: No matching distribution found for tlz

**Comment by TomAugspurger** [comment]
You're still seeing the issue after `pip3 install dask[complete]`? `dask[dataframe]` includes toolz: https://github.com/dask/dask/blob/263187bbc263a395dc871e5874ee4fda21abb190/setup.py#L21 so that shouldn't be the case.

Can you post the full terminal output of creating a new virtualenv and installing dask[complete] into it?

**Comment by rbdm-qnt** [comment]
I tried rerunning pip3 install dask[complete] and got this:

Requirement already satisfied: toolz>=0.8.2; extra == "complete" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dask[complete]) (0.10.0)

Since this is version 0.10.0, I tried uninstalling toolz and reinstalling version 0.8.2, which gave me an error, which I fixed and successfully installed. But now it's giving me this: (PS I asked a friend on linux to try and install it and it worked fine for him, so I guess it's a problem on my system)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 13, in <module>
    from .io import (
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/__init__.py", line 13, in <module>
    from .csv import read_csv, to_csv, read_table, read_fwf
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 21, in <module>
    from ...bytes import read_bytes, open_file, open_files
  File "/usr/local/lib/python3.7/site-packages/dask/bytes/__init__.py", line 10, in <module>
    "fsspec is required to use any file-system functionality."
ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
python -m pip install 'fsspec>=0.3.3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rob/Desktop/bot_alpha_v1/parquet_data_processor_v1.py", line 2, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 56, in <module>
    raise ImportError(msg) from e
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install dask[dataframe] --upgrade  # or python -m pip install

**Comment by rbdm-qnt** [comment]
Managed to make it work after uninstalling and reinstalling fsspec a bunch of times, eventually worked when I did so through Pycharm. Thank you!

**Comment by martindurant** [comment]
Probably you should look at the paths where python and pip were, they maybe were different environments.
