### ISSUE TITLE
read_csv manipulates file path whereas pandas does not

### ISSUE THREAD

**Issue by unhott** [dask/dask#6092]
I can't tell if this is an issue or if I just don't understand the docs right. the docs for read_csv seem minimal and defer to pandas read_csv for more details. but pandas.read_csv works perfectly fine in my strange situation. 

I am exploring some data for a project for work but our file system is a little weird. And because of our environment, I have almost 0 capabilities to manipulate anything. The files are stored on my computer but because of the way our systems are setup on our network (windows 10, FYI), my files actually have an address like this: \\SERVER\UserHomeFolder$\me\My Documents\project1\data\filen.csv  -- I can't actually see or access my C drive on this computer. It's the same thing even when I am offline from my work network. 

When I pass this path string to pandas.read_csv, there’s no issue. But when I pass it to dask.dataframe.read_csv I get an os error. 

The system cannot find the path specified: ‘C:/Users/me/$/SERVER/UserHomeFolder$/me/My Documents/python_projects/data analysis/project1/SERVER/UserHomeFolder$/me/My Documents/project1/data/filen.csv’

dask is somehow interpreting the file path string differently, I think appending my current notebook’s path. Is there a way to override this? The dask docs, beyond accepting a list of paths, basically defer to pandas and I don’t understand quite what’s going wrong here. 

I read through some of the other issues, and adding 'file:' seemed promising but that just throws a different os error, but this time with 'file:\\\\SERVER\\'... to the correct path, but with double \'s everywhere, despite me validating that what I was passing it in is like 'file:\\SERVER\'... 

After additional tinkering-- I actually did have the capability to map a drive as Y: and that allowed me to successfully call read_csv, but this is not a good solution for me.

**Comment by TomAugspurger** [comment]
It's a bit hard to say without actual examples. Can you post a full traceback?

**Comment by martindurant** [comment]
I believe this is handled by `fsspec.implementations.local.make_path_posix`. For the current version, and your path, I get output "SERVER/UserHomeFolder$/me/My Documents/project1/data/filen.csv". This does indeed look wrong, it should have "/" as the first character - maybe this is why it's getting interpreted as a relative path.

To workaround, you can pass your path with two leading slashed "//SERVER/Us...", it should work.

**Comment by unhott** [comment]
I'm sorry, I made a typo. That is how my path looks,
\\SERVER\UserHomeFolder$\me\My Documents\project1\data\filen.csv

Which is what works in pandas. I had to type every detail out because I can't export the data from my work laptop, so I can't really get into the full traceback at the moment. 

Do you think it would work if I swap \'s with /?

**Comment by martindurant** [comment]
Yes, it should work if you format the path posix-like (with "/" separators.
I'll raise an issue in fsspec and add your case to the tests.

**Comment by unhott** [comment]
Thanks!

**Comment by jrbourbeau** [comment]
Closing as it looks like this issue was resolved by https://github.com/intake/filesystem_spec/pull/273. We can re-open if that's not the case
