### ISSUE TITLE
add other to_parquet examples

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6096]
It took me longer than I would have liked to work out how to save a `dask.dataframe` in an Azure blob.

https://stackoverflow.com/questions/60765331/moving-data-from-a-database-to-azure-blob-storage/60773724#60773724

Is there any appetite for adding another example to https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/core.py#L337?

The example there currently is about as minimal as you can get (which I understand is the idea).

Or there could be a separate page/section for this. i.e. near https://docs.dask.org/en/latest/dataframe-create.html#locations

**Comment by jcrist** [comment]
Docstring examples should be relatively short and self contained, but we should definitely have a section in our docs about writing to external filesystems. I think https://docs.dask.org/en/latest/dataframe-create.html would be a good place. We should probably add a cross reference to https://docs.dask.org/en/latest/remote-data-services.html from that page as well.

Would you be interested in contributing a short docs section?

**Comment by raybellwaves** [comment]
Happy to do so
