### ISSUE TITLE
Convert yyyymmdd to datetime

### ISSUE THREAD

**Issue by subhamkhemka** [dask/dask#6097]
Hi,

I have a column with the following values as object type
The dataframe has 450 million records and is in parquet format
20191209
20190914 
20190920 
20190712 
20191025

Can you please help me convert this to datetime format ?

**Comment by jcrist** [comment]
Hi @subhamkhemka, Dask is designed to look a lot like Pandas and NumPy. If you know how to convert a pandas column into datetime format, it will work the same with dask. You probably want https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html.

```python
In [16]: import pandas as pd

In [17]: import dask.dataframe as dd

In [18]: s = pd.Series(["20191209", "20190914"])

In [19]: s2 = dd.from_pandas(s, npartitions=1)

In [20]: pd.to_datetime(s, format="%Y%m%d")
Out[20]:
0   2019-12-09
1   2019-09-14
dtype: datetime64[ns]

In [21]: dd.to_datetime(s2, format="%Y%m%d")
Out[21]:
Dask Series Structure:
npartitions=1
0    datetime64[ns]
1               ...
dtype: datetime64[ns]
Dask Name: to_datetime, 2 tasks

In [22]: _.compute()
Out[22]:
0   2019-12-09
1   2019-09-14
dtype: datetime64[ns]
```

In the future, usage questions like this would be more appropriate for https://stackoverflow.com/.
