### ISSUE TITLE
to_parquet creating files not glob-able by read_parquet

### ISSUE THREAD

**Issue by michaelaye** [dask/dask#6099]
I have a bunch of large CSV files that I want to convert to parquet.

For the MVCE, I will create the CSV files on the fly.

I would then like to glob the set using the same syntax as offered for CSV (available according to the read_parquet docstring), but I'm getting an index error:

```python
import dask.dataframe as dd
import pandas as pd
from pathlib import Path

# data prep
for i in range(10):
    istr = str(i).zfill(2)
    fname = Path(f'test_{istr}.csv')
    # create random data
    df = pd.DataFrame(np.random.random((10,10)))
    # create the csv file I want to convert to parquet
    df.to_csv(fname)
    dd.read_csv(fname).to_parquet(fname.with_suffix('.parq'))

# reading single file works:
df = dd.read_parquet("test_00.parq")

# globbing fails:
df = dd.read_parquet('test_*.parq')

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-68db42d944ad> in <module>
----> 1 df = dd.read_parquet('test_*.parq')

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, chunksize, **kwargs)
    231         filters=filters,
    232         split_row_groups=split_row_groups,
--> 233         **kwargs
    234     )
    235     if meta.index.name is not None:

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, **kwargs)
    201         # correspond to a row group (populated below).
    202         parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
--> 203             fs, paths, gather_statistics, **kwargs
    204         )
    205 

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in _determine_pf_parts(fs, paths, gather_statistics, **kwargs)
    142                 pf.cats = paths_to_cats(fns, scheme)
    143                 parts = paths.copy()
--> 144     elif fs.isdir(paths[0]):
    145         # This is a directory, check for _metadata, then _common_metadata
    146         paths = fs.glob(paths[0] + fs.sep + "*")

IndexError: list index out of range
```
Note that reading a single file works.
My expectation is (maybe wrongly), that a file written without any extra parameter set doesn't require any extra info for globbing either.

Versions:
Dask: 2.14.0
Fastparquet: 0.3.3

**Comment by michaelaye** [comment]
Files were created like this:


```bash
ls *.parq
test_00.parq:
_common_metadata  _metadata  part.0.parquet

test_01.parq:
_common_metadata  _metadata  part.0.parquet

test_02.parq:
_common_metadata  _metadata  part.0.parquet

test_03.parq:
_common_metadata  _metadata  part.0.parquet

test_04.parq:
_common_metadata  _metadata  part.0.parquet

test_05.parq:
_common_metadata  _metadata  part.0.parquet

test_06.parq:
_common_metadata  _metadata  part.0.parquet

test_07.parq:
_common_metadata  _metadata  part.0.parquet

test_08.parq:
_common_metadata  _metadata  part.0.parquet

test_09.parq:
_common_metadata  _metadata  part.0.parquet
```

**Comment by michaelaye** [comment]
The error seems to be engine-independent, if I do everything with pyarrow, I get a very similar error:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-39-3b7e659c2cb2> in <module>
----> 1 df = dd.read_parquet('test_*.parq', engine='pyarrow')

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, chunksize, **kwargs)
    231         filters=filters,
    232         split_row_groups=split_row_groups,
--> 233         **kwargs
    234     )
    235     if meta.index.name is not None:

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, split_row_groups, **kwargs)
    219         # correspond to a row group (populated below)
    220         parts, dataset = _determine_dataset_parts(
--> 221             fs, paths, gather_statistics, filters, kwargs.get("dataset", {})
    222         )
    223         # Check if the column-chunk file_path's are set in "_metadata".

/luna4/maye/miniconda3/envs/py37/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py in _determine_dataset_parts(fs, paths, gather_statistics, filters, dataset_kwargs)
    124                 dataset = pq.ParquetDataset(paths[0], filesystem=fs, **dataset_kwargs)
    125                 parts = [base + fs.sep + fn for fn in fns]
--> 126     elif fs.isdir(paths[0]):
    127         # This is a directory, check for _metadata, then _common_metadata
    128         allpaths = fs.glob(paths[0] + fs.sep + "*")

IndexError: list index out of range
```

**Comment by martindurant** [comment]
The glob expects data files, I believe, not a set of directories - so you should use:

`dd.read_parquet('test_*.parq/*. parquet')`

**Comment by michaelaye** [comment]
but read_parquet reads a single filename like that just fine? I'm puzzled why reading the directory sub-parts works for a single file but not when I glob.

**Comment by martindurant** [comment]
There is a difference between reading a directory (which might have a _metadata file that needs special handling) and individual files. We simply have not made the extra code to cover a glob of directories, since you can already do this with the slightly longer URL.

**Comment by michaelaye** [comment]
what i meant above with "single filename" is, e.g., `test_00.parq`, which turns out to be a directory (even so i didn't create it), and is being read fine automatically by pointing read_parquet to that. As it should, because if to_parquet creates a directory without my doing so, read_parquet should really transparently be getting it back, right? I guess the globbing code path is different than simply looping over how to read a filename that turns out to be a directory, otherwise this would be working, right?

**Comment by martindurant** [comment]
Right, exactly. The roundtrip for a single path string work, but the added feature to load from several files and directories works differently.

**Comment by michaelaye** [comment]
if i could patch this together, would it be accepted as a PR?

**Comment by martindurant** [comment]
Certainly (cc @rjzamora )

**Comment by michaelaye** [comment]
actually, your proposed solution of pointing directly to the underlying parquet files ignores the existence of metadata files, correct?

**Comment by martindurant** [comment]
Correct, the following should work
`df = dd.read_parquet('test_*.parq/*.parquet')`

**Comment by michaelaye** [comment]
Sorry, my question was, as that URL is ignoring any potential metadata, I need to come up with a more detailed way to treat globbed directories correctly?

**Comment by martindurant** [comment]
No, the metadata also exists in the data file. The _metadata file contains the metadata(s?) of all of the data files in a directory/data-set, which would allow you to get that in a single read instead of parsing each file.

**Comment by TomAugspurger** [comment]
@martindurant is there a concrete fix that needs to be made here, or is it a matter of passing the right argument to `read_parquet`?

**Comment by martindurant** [comment]
There is an argument to implementing a glob-of-dictionaries, but I have no plans, especially since you can work around with the right arguments.

**Comment by TomAugspurger** [comment]
OK, my default would be to not implement that then if there's a relatively easy way to get the same behavior already.

So this should be closed? Do you agree @michaelaye?

Is there anything in the documentation that needs to be clarified?

**Comment by michaelaye** [comment]
I don’t agree because the writing and reading of parquet files then becomes very ugly asymmetric and you demand from the user to understand the parquet format sufficiently to understand that it’s okay to glob for that anonymous file in all the sub folders while ignoring other files in there. And it’s asymmetric with the fact that when it’s only one “file”, suddenly dask is able to work with the directory transparently.

**Comment by martindurant** [comment]
^ this sounds like a clarity of documentation thing; but I'm not quite certain I understand what is getting lost.

```
path : string or list
    Source directory for data, or path(s) to individual parquet files.
    Prefix with a protocol like ``s3://`` to read from alternative
    filesystems. To read from multiple files you can pass a globstring or a
    list of paths, with the caveat that they must all have the same
    protocol.
```
Says *one* directory or set of *individual files*.  I agree that it might not be obvious to which of these the globstring applies.

**Comment by jrbourbeau** [comment]
Just checking in here, @michaelaye do you have any suggestions on how the current documentation could be updated? Or perhaps something else?

**Comment by michaelaye** [comment]
I don't know, I obviously have a very different imagination of an API that is symmetric and extrapolate-able without having to have detailed knowledge of the file formats, so as a PR isn't welcome I will implement these as private dask-tools. Feel free to close.

**Comment by martindurant** [comment]
> a PR isn't welcome

Sorry if I gave the wrong impression - a PR would be certainly welcome, but I don't think in this case it will be easy to pull off. You will need to directly use fsspec functions like glob and isdir rather than the current open_files.

**Comment by martindurant** [comment]
Closing this as inactive and a workaround available. 
The parquet API has gone through a lot of changes in the mean time. This might even work now! In any case, we would still welcome a PR if not, but I would say that things are working correctly according to the specs of the documentation.
