### ISSUE TITLE
Reusing dask with small datasets

### ISSUE THREAD

**Issue by enriquedacostacambio** [dask/dask#6101]
I have a use case where I use code written to transform large datasets using Dask DataFrames while training an ML model.
Then once this model is trained I'd like to reuse that transformation code without having to rewrite it to work with Pandas. However in this case the "datasets" have just one single row, making the overhead imposed by Dask prohibitive for online inferencing. (See [an example of the overhead](https://stackoverflow.com/questions/61236092/what-explains-the-performance-difference-in-dask-between-dataframe-assignkwar))

It would be nice if Dask offered a feature for this scenario.

eg: optimized paths in the code for dealing with tiny datasets in a way that Dask ends up acting just like an adapter: Dask DataFrame interface and regular Pandas DataFrame implementation.

**Comment by jcrist** [comment]
I think I understand the use case, but now what you'd like the api to look like. My initial gut reaction is that this sounds like something that should be external to Dask (which only reasons about dask collections), but there may be something we should do internally. Can you provide a pseudocode example for how you'd like things to work?

**Comment by mrocklin** [comment]
There may already be an OSS projects that does this.  I've forgotten the
name though.

**Comment by enriquedacostacambio** [comment]
@jcrist 
let's say i have this function:
```
def transform(data: dask.dataframe.DataFrame) -> dask.dataframe.DataFrame:
  data['c'] = data.apply(lambda r: r['a']+r['b'], axis=1, meta=('int32'))
  return data
```
i like to get the Dask perfomance when `data` is large but the Pandas performance when `data` is small.
I cannot call this function with a `pandas.DataFrame` taking advantage of duck-typing because meta is a Dask argument. (this is just an example, and even if it worked i think it's a hacky/risky solution)

Ideally this would be transparent to me, something that is automatically assessed in the  `dask.dataframe.DataFrame` constructor, example in pseudocode:
```
class DataFrame:
  def __init__(self, source_of_data):
    if len(source_of_data) < THRESHOLD:
      self.just_call_pandas = True
    else:
      self.just_call_pandas = True
   
  def apply(self, function, axis, meta):
    if self.just_call_pandas:
      return self.source_of_data.apply(function, axis) # either ignore or just check meta but not pass it
    else:
      // do what dask currently does

  # and the same for every other method
```
(horrible implementation, acknowledged)

or less transparently, it could be a constructor parameter or i guess it could also be achieved externally by subclassing `dask.dataframe.DataFrame`.

does it make sense?

**Comment by jcrist** [comment]
Hi @enriquedacostacambio. I think something like this is out of scope for dask itself. There might be a package for your use case that already handles this, I'm not sure. I know [featuretools](https://github.com/FeatureLabs/featuretools) supports both pandas and dask inputs, but I'm not sure if it satisfies your needs (I've also never used it).

Closing as out-of-scope.

**Comment by enriquedacostacambio** [comment]
fair enough, thanks for the pointer!
