### ISSUE TITLE
nanstd warnings with chunks

### ISSUE THREAD

**Issue by nehz** [dask/dask#6105]
```
T = np.ones((10, )) * np.nan
T[0] = 1
T[1] = 2
V = darr.nanstd(darr.from_array(T, chunks=(2, ))).compute()
```
Gives warning, with chunks, probably due to all nan in that chunk. With full chunks has no warning.

```
/usr/local/lib/python3.6/dist-packages/dask/array/numpy_compat.py:40: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
```

The output calculation seems to be correct.  This might be related to #3906

Also something separate, checking `https://github.com/dask/dask/blob/master/dask/array/numpy_compat.py` the section
`np.divide(1, 0.5, dtype="i8")` seems to always trigger a TypeError, which on brief read, unrelated to the issue it is addressing ?

### Platform
* `dask==2.14.0`
* `Ubuntu Python 3.7`

**Comment by jcrist** [comment]
Thanks for the bug report, I'm able to reproduce. We periodically run into these warning issues. Tracking these down usually involves finding the offending function and figuring out how to either:
- Avoid doing the call that warns in cases that would warn
- Wrapping the call with `np.errstate` to silence the warning

Would you be interested in investigating this issue? The fix shouldn't be done in our `divide` stub in `numpy_compat`, rather it should be somewhere further up the call tree.

> Also something separate, checking https://github.com/dask/dask/blob/master/dask/array/numpy_compat.py the section
np.divide(1, 0.5, dtype="i8") seems to always trigger a TypeError, which on brief read, unrelated to the issue it is addressing ?

Yeah, this is unrelated.

**Comment by nehz** [comment]
I can have a look around, any best practice for debugging? Using np.seterr('raise') doesn't seem to raise the exception (I am guessing it is a multi-thread thing)

**Comment by TomAugspurger** [comment]
@nehz great! https://docs.dask.org/en/latest/debugging.html has some tips. At least in this case using the single-threaded scheduler may be a good place to start: https://docs.dask.org/en/latest/debugging.html#use-the-single-threaded-scheduler
