### ISSUE TITLE
Merge results depend on order of pandas conversion

### ISSUE THREAD

**Issue by HCelion** [dask/dask#6106]
I am afraid this is another problem where I could not find a minimum producing sample. But the dataset is public and I could write up a minimum reproducing example of that.

The issue is that I have a large daskframe and try to merge additional information via an inner join. When I do this naively, I do not get any results (neither with join or merge)

```
# A dataset with str valued index of the format year|month
nyc_data = dd.read_parquet('nyc_data_date_index')

# A csv file that has monthYear as column with the same irder year|month
nyc_temps = pd.read_csv('../../nyc-temp-data.csv')
nyc_temps_indexed = nyc_temps.set_index(nyc_temps.monthYear.astype(str))

# Gives an empty result
nyc_data.merge(nyc_temps_indexed, how='inner', left_index = True, right_index = True).head()
```
If I however take the head of the dask frame and do the merge thereafter, it gives a number of results
```
nyc_data_head = nyc_data.head(15)
nyc_data_head.merge(nyc_temps_indexed, how='inner', left_index = True, right_index = True)
```
is not empty.
I tried reproducing with
```
left_pd = pd.DataFrame({'values': [1,2,3,4,5, 12,13,14,15]}, index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'k', 'l'])
left_dd = dd.from_pandas(left_pd, npartitions = 4)

right_pd =  pd.DataFrame({'values': [1,2,3,4,5, 12,13,14,15]}, index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'k', 'l'])
left_pd.merge(right_pd, how = 'inner', left_index = True, right_index = True)

left_dd.merge(right_pd, how = 'inner', left_index = True, right_index = True).compute()
```
But here results are returned. 

What could be the reason for such behaviour? Are there perhaps other diagnostics I can run to pinpoint the issue? Thanks!

**Comment by HCelion** [comment]
Found the solution to the issue.
I had to pass npartitions = 2 with the head.
The issue can be closed, though I think the behaviour is very misleading. Perhaps adding a message in case no rows are returned? Though, that might be what you expect. Maybe some default setting that when head returns empty, it tries to look at other partitions to return values.

**Comment by jrbourbeau** [comment]
> Perhaps adding a message in case no rows are returned?

There should be a warning message if the first partition returns less than the requested number of items in `head`: 

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: df = pd.DataFrame()

In [4]: ddf = dd.from_pandas(df, npartitions=2)

In [5]: ddf.head()
/Users/jbourbeau/github/Quansight-Labs/dask/dask/dataframe/core.py:5979: UserWarning: Insufficient elements for `head`. 5 elements requested, only 0 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(msg.format(n, len(r)))
Out[5]:
Empty DataFrame
Columns: []
Index: []
```

**Comment by jrbourbeau** [comment]
Closing this issue for now, though we can re-open if you think the current `UserWarning` message can be improved @HCelion
