### ISSUE TITLE
Expected behavior of dask.array.full() for non-scalar fill values?

### ISSUE THREAD

**Issue by Huite** [dask/dask#6107]
What is the expected behavior for `dask.array.full()` for a non-scalar `fill_value`?

The `numpy.full()` signature in the documentation mentions "scalar" for `fill_value`.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html

However, it'll broadcast non-scalar values if it can:
```python
a = np.full((3, 2), [1, 2])
```

Since ``dask.array.full()`` wraps this function, it works similarly:
```python
import dask.array

a1 = dask.array.full((2, 3), [[1, 2, 3], [4, 5, 6]])
a1.compute()
```

The issue is that when the chunk sizes change, it won't work anymore, as it starts broadcasting *per chunk*:
```python
a2 = dask.array.full((2, 3), [[1, 2, 3], [4, 5, 6]], chunks=(1, 3))
a2.compute()  # ValueError: could not broadcast input array from shape (2,3) into shape (1,3)
a3 = dask.array.full((2, 3), [1, 2, 3], chunks=(1, 3))
a3.compute()
```

My feeling is that choosing different chunk sizes shouldn't lead to different behavior here. I think I'd prefer a ValueError for a non-scalar fill_value.

**Comment by jsignell** [comment]
Thanks for raising this issue. I think your proposal of raising an Error when the fill_value is not a scalar is quite reasonable but I wouldn't want to break people unnecessarily. Using `full` with a list works with chunks as long as the `fill_value` can be contained in one chunk. 

![image](https://user-images.githubusercontent.com/4806877/79608070-54075980-80c2-11ea-8896-bd4e4408a71e.png)

I do think it'd be better if we can raise an error before calling `.compute`. I'm just not sure how to go about that. For the record that would happen here: https://github.com/dask/dask/blob/8217ab08d258319b61fe0ef27f437a406fd13c3c/dask/array/wrap.py#L58

**Comment by Huite** [comment]
A few thoughts:
If I take a look at the dask.array API (https://docs.dask.org/en/latest/array-api.html#dask.array), I don't think many of the functions implicitly do this kind of broadcasting? -- So this "chunkwise broadcasting" maybe only affects `full`?

This is probably a naive idea, but:
```python
import dask.array

def full(shape, fill_value, chunks=None):
    return dask.array.broadcast_to(fill_value, shape, chunks=chunks)
```

`broadcast_to` does raise the kind of error we'd be after:

(From your examples):

```python
a1 = full((4, 2, 3), [[1, 2, 3], [4, 5, 6]])
a1.compute()

a2 = full((4, 2, 3), [[1, 2, 3], [4, 5, 6]], chunks=(2, 2, 3))
a2.compute()

a3 = full((4, 2, 3), [[1, 2, 3], [4, 5, 6]], chunks=(2, 2, 1))
```

The last line raises an error immediately, without `.compute`:

```python
ValueError: cannot broadcast chunks ((2,), (3,)) to chunks ((2, 2), (2,), (1, 1, 1)): new chunks must either be along a new dimension or a dimension of size 1
```

(Inoring the `order` and `dtype` arguments of `full` in this example)

**Comment by jcrist** [comment]
I think we should just error if `fill_value`  isn't a scalar. (I didn't even know numpy supported broadcasting of `fill_value`). The broadcasting behavior only works for dask in extremely specific cases, and only works by accident, not by design.

@Huite, would you be interested in making a PR adding a nice error message for this case?

**Comment by Huite** [comment]
I'd be happy to oblige, but I'm not sure what the best way of approaching this is, since `full` is currently justs wraps `np.full`:

https://github.com/dask/dask/blob/8217ab08d258319b61fe0ef27f437a406fd13c3c/dask/array/wrap.py#L140

This requires a specific check on `fill_value`, so I don't think there's an elegant solution within the wrapping functions. This is the easiest way I could special case it:

```python
# full() requires special casing due to argument check on fill_value
_full = w(np.full)  # Generate only once


def full(shape, fill_value, dtype=None, order='C'):
    # np.isscalar has somewhat strange behavior: 
    # https://docs.scipy.org/doc/numpy/reference/generated/numpy.isscalar.html 
    if np.ndim(fill_value) != 0:
        raise ValueError(f"fill_value must be scalar. Received {fill_value} instead.")
    return _full(shape, fill_value, dtype, order)


full.__doc__ = _full.__doc__
full.__name__ = _full.__name__
```

Not sure if that's what you had in mind, more or less?


The most elegant fix seems tackling it upstream in numpy. But I'd argue it's not a real issue in numpy anyway (even though the numpy signature explicitly says "scalar"), and it would likely cause significant breakage.

**Comment by TomAugspurger** [comment]
@Huite that looks good. Could you submit a pull request with it?

**Comment by Huite** [comment]
Yes, will do!
