### ISSUE TITLE
Unable to start dashboard on ARM processor (Raspberry Pi).

### ISSUE THREAD

**Issue by mishab** [dask/dask#6109]
When starting dask-scheduler on an ARM device such as raspberry pi (latest version 4GB ram), the dashboard does not start 

Actual behavior:
On the device with ip 192.168.2.238 execute command dask-scheduler. The following output is observed:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://192.168.2.238:8786
```

Note there is no "dashboard at" output

Expected behavior:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://192.168.2.130:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
```

I have tried running the dask-worker with at least 3 ARM devices and I can reproduce this on all 3 ARM devices.

pip freeze:
bokeh==2.0.1
click==7.1.1
cloudpickle==1.3.0
dask==2.14.0
distributed==2.14.0
fsspec==0.7.2
HeapDict==1.0.1
Jinja2==2.11.2
locket==0.2.0
MarkupSafe==1.1.1
msgpack==1.0.0
numpy==1.18.2
packaging==20.3
pandas==1.0.3
partd==1.1.0
Pillow==7.1.1
psutil==5.7.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3.1
six==1.14.0
sortedcontainers==2.1.0
tblib==1.6.0
toolz==0.10.0
tornado==6.0.4
typing-extensions==3.7.4.2
zict==2.0.0

**Comment by quasiben** [comment]
In your output it says:
> distributed.scheduler - INFO - dashboard at: :8787

So they dashboard should be at ip:8787 or 127.0.0.7:8787.  If those are not working for you perhaps try defining the address with `--dashboard-address`

**Comment by TomAugspurger** [comment]
@mishab can you try debugging this a bit? Does `import distributed.dashboard.scheduler` work for you?

**Comment by mishab** [comment]
@TomAugspurger  - it appear that raspberry pi does not install a library (libatlas-base-dev) required by bokeh. 
I have documented this issue [here](https://mishina.com/2020/04/17/running-dask-dashboard-on-arm/)

**Comment by TomAugspurger** [comment]
Thanks. After installing that things work fine?

**Comment by TomAugspurger** [comment]
Thanks for the update.

**Comment by fastlaner** [comment]
this installs on the r pi 4 libatlas-base-dev gfortran
