### ISSUE TITLE
Dask slow to connect to workers

### ISSUE THREAD

**Issue by jackmmargolis** [dask/dask#6120]
Hello- I've been using Dask for about 6 months now with no problems (it's great!). About 2-3 weeks ago I began facing an issue in my Client setup. I had been using the simple:

```python
from dask.distributed import Client
import multiprocessing as mp
client = Client(mp.cpu_count())
```

and this worked perfectly well, with cpu_count at let's say 48. Doing the equivalent now gives the appearance of what seems to be the code hanging, but looking at the 'top' command line function, I can see the workers being generated slowly 1 by 1, with the 48 finishing in about 20 minutes. 

Thus, my question is- has something changed in this regard within the last month? If not, and you believe it to be a server side issue, what would you recommend having my server admin check? For reference, I'm running a jupyter notebook on an AWS virtual server on my company network. Again, this had been working for many months prior with almost instant speed.

Thanks in advance, and many thanks for dask!

**Comment by TomAugspurger** [comment]
Mmm, my only guess is the automatic version checking that we do now. This will import some libraries, which might take long if loading packages from takes a while.

IIRC there was a discussion about making a configuration option to disable that, but I don't recall if that made it in.

**Comment by TomAugspurger** [comment]
https://github.com/dask/distributed/pull/2627 is the PR adding that if you want to try a commit just before & after then to verify.

The other possible culprit is switching the default multiprocessing method in https://github.com/dask/distributed/pull/3461.

**Comment by mrocklin** [comment]
This might be a good candidate for `git bisect` if you have time to help track this down @jackmmargolis

**Comment by jrbourbeau** [comment]
Just checking in here, @jackmmargolis were you able to investigate any further by narrowing down to a commit where things began to slow down?

**Comment by jackmmargolis** [comment]
Apologies on the slow follow-up. I didn't much further investigation- tbh it started working fine on it's own for no reason in particular after not working for a couple weeks. I had deleted the dask-worker-space folders a few times, but not sure if that made the ultimate difference.

If I run into this problem again I'll be sure to post here again but feel free to close for now....

**Comment by jrbourbeau** [comment]
Okay sounds good, thanks for the additional info @jackmmargolis. Closing for now, but we can re-open if needed
