### ISSUE TITLE
bytes_per_chunk doesn't work in read_sql_table

### ISSUE THREAD

**Issue by kwunlyou** [dask/dask#6121]
```
dask.dataframe.read_sql_table(table, uri, index_col, divisions=None, npartitions=None, limits=None, columns=None, bytes_per_chunk=268435456, head_rows=5, schema=None, meta=None, engine_kwargs=None, **kwargs)
```
> If neither divisions or npartitions is given, the memory footprint of the first few rows will be determined, and partitions of size ~256MB will be used.

based on docs, the same size of partitions will be generated if `divisions` and `npartitions` are missing

However, I got these partitions using the code as below

```
drwxrwxr-x 2 ubuntu ubuntu 4.0K Apr 22 15:13 .              
drwxrwxr-x 3 ubuntu ubuntu 4.0K Apr 22 13:58 ..             
-rw-rw-r-- 1 ubuntu ubuntu 1.9K Apr 22 15:13 _common_metadata
-rw-rw-r-- 1 ubuntu ubuntu  14K Apr 22 15:13 _metadata      
-rw-rw-r-- 1 ubuntu ubuntu 1.3G Apr 22 14:26 part.0.parquet
-rw-rw-r-- 1 ubuntu ubuntu  18M Apr 22 14:18 part.1.parquet
-rw-rw-r-- 1 ubuntu ubuntu  69M Apr 22 14:06 part.10.parquet
-rw-rw-r-- 1 ubuntu ubuntu  71M Apr 22 14:00 part.11.parquet
-rw-rw-r-- 1 ubuntu ubuntu 2.2G Apr 22 15:13 part.12.parquet
-rw-rw-r-- 1 ubuntu ubuntu 339M Apr 22 14:18 part.13.parquet
-rw-rw-r-- 1 ubuntu ubuntu  91M Apr 22 14:06 part.14.parquet
-rw-rw-r-- 1 ubuntu ubuntu 1.9G Apr 22 15:08 part.15.parquet
-rw-rw-r-- 1 ubuntu ubuntu  12M Apr 22 13:59 part.16.parquet
-rw-rw-r-- 1 ubuntu ubuntu 2.2K Apr 22 14:10 part.17.parquet
-rw-rw-r-- 1 ubuntu ubuntu 3.8M Apr 22 14:18 part.18.parquet
-rw-rw-r-- 1 ubuntu ubuntu  22M Apr 22 14:08 part.19.parquet
-rw-rw-r-- 1 ubuntu ubuntu  28M Apr 22 14:04 part.2.parquet
-rw-rw-r-- 1 ubuntu ubuntu  14M Apr 22 14:20 part.20.parquet
-rw-rw-r-- 1 ubuntu ubuntu  71M Apr 22 14:22 part.21.parquet
-rw-rw-r-- 1 ubuntu ubuntu  46M Apr 22 13:59 part.22.parquet
-rw-rw-r-- 1 ubuntu ubuntu 383M Apr 22 14:19 part.23.parquet
-rw-rw-r-- 1 ubuntu ubuntu  34M Apr 22 14:01 part.24.parquet
-rw-rw-r-- 1 ubuntu ubuntu  18M Apr 22 14:01 part.25.parquet
-rw-rw-r-- 1 ubuntu ubuntu  98M Apr 22 14:00 part.26.parquet
-rw-rw-r-- 1 ubuntu ubuntu  78M Apr 22 14:09 part.27.parquet
-rw-rw-r-- 1 ubuntu ubuntu 225M Apr 22 14:11 part.28.parquet
```

```python
client = Client(LocalCluster(ip="0.0.0.0", n_workers=4, threads_per_worker=1))
df = dd.read_sql_table("table_name", 
                       "sqlite:////db.sqlite3",
                       index_col="id")
df.to_parquet("tmp.parquet")
```

**Comment by TomAugspurger** [comment]
Do you have a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

To help debug, can you print out the `count` and `npartitions` at https://github.com/dask/dask/blob/633de3f476cf3fd512211ea583604750f43d662b/dask/dataframe/io/sql.py#L170?

**Comment by kwunlyou** [comment]
> Do you have a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
> 
> To help debug, can you print out the `count` and `npartitions` at
> 
> https://github.com/dask/dask/blob/633de3f476cf3fd512211ea583604750f43d662b/dask/dataframe/io/sql.py#L170
> 
> ?

Thank you for the response. 

- Sorry, let me see if I can generate a reproducible example.

- for my case, `count = 57981` and `npartitions = 36`

**Comment by kwunlyou** [comment]
Also, I had a question on this line 

https://github.com/dask/dask/blob/2.14.0/dask/dataframe/io/sql.py#L180

```python 
  divisions = np.linspace(mini, maxi, npartitions + 1).tolist()
```

for example, if `index` is integer type, and its distribution is not uniform. Computing `divisions` using `np.linspace` can have some trouble?

**Comment by TomAugspurger** [comment]
Yep, that's possibly what's happening here.

If uniform partition sizes is especially important to you, you might want to write your own SQL query to find some uniform divisions and pass those to `read_sql`.

**Comment by kwunlyou** [comment]
> Yep, that's possibly what's happening here.
> 
> If uniform partition sizes is especially important to you, you might want to write your own SQL query to find some uniform divisions and pass those to `read_sql`.

the distribution of my `id` column is very skewed and produces several very big partitions introducing some memory issue. Finally, created a temporary uniform distributed `fake id` in my SQL table and resolved this issue.

**Comment by martindurant** [comment]
losing this issue as inactive. @kwmsmith - the documentation could of course be clearer. If you can think of a better way to phrase the practical use of `bytes_per_chunk` in the docsrting, please submit a PR with that change.
