### ISSUE TITLE
doc: update the azure section?

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6125]
Does the Azure section (https://docs.dask.org/en/latest/remote-data-services.html#azure) need to be updated now that https://github.com/dask/adlfs has added `abfs://`?

cc. @martindurant

**Comment by martindurant** [comment]
Certainly, sounds like a good idea. 

There are in fact [quite[(https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations) a [few](https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations) implementations.

**Comment by jsignell** [comment]
Would you be interested in adding that to the docs @raybellwaves?

**Comment by raybellwaves** [comment]
sure
