### ISSUE TITLE
DataFrame Groupby on Categorical Column + .apply() returns extra rows

### ISSUE THREAD

**Issue by eugeneh101** [dask/dask#6135]
If you do a groupby on a categorical column and then use a builtin `.agg()` (like "sum" or "nunique" or "count"), then everything works correctly where the number of rows is number of categorical levels. However, if you pass in your own function into `.apply()`, then it appears that you get the number of rows = npartition * num_categorical_levels. It appears that you are getting extra rows from other partitions.

I tested on Dask 2.14.0 and Pandas 1.0.3
```
import pandas as pd
import numpy as np

N = 10000
df = pd.DataFrame({"random_int": np.random.randint(0, 2, N), "random_float": np.random.rand(N)})
df["random_int"] = df["random_int"].astype("category")

df.groupby("random_int")["random_float"].apply(pd.Series.median)
```
which prints out correctly 2 rows
```
random_int
0    0.506780
1    0.494878
Name: random_float, dtype: float64
```
<br>  

However if you use Dask DataFrame, you get extra rows:
```
import dask.dataframe as dd

ddf = dd.from_pandas(df, npartitions=4)
ddf.groupby("random_int")["random_float"].apply(pd.Series.median).compute()
```
which prints out 8 rows (4 partitions * 2 categorical levels)
```
random_int
0         NaN
1         NaN
0         NaN
1         NaN
0         NaN
1    0.494878
0    0.506780
1         NaN
Name: random_float, dtype: float64
```

Original question posted on Stackoverflow: https://stackoverflow.com/questions/60711871/dask-apply-with-custom-function/61232826#61232826

**Comment by TomAugspurger** [comment]
The groupby.apply docs have this warning

```
        .. warning::

           Pandas' groupby-apply can be used to to apply arbitrary functions,
           including aggregations that result in one row per group. Dask's
           groupby-apply will apply ``func`` once to each partition-group pair,
           so when ``func`` is a reduction you'll end up with one row per
           partition-group pair. To apply a custom aggregation with Dask,
           use :class:`dask.dataframe.groupby.Aggregation`.

```

Does that explain the behavior you're seeing?

**Comment by eugeneh101** [comment]
Thank you for mentioning the warning. The explanation would make sense under the assumption that the categorical levels are kept across all partitions.
Is there a way to make the categorical levels disappear if there's no data in that partition? With the Principle of Least Surprise, it would be strange (from a user perspective) that the groupby still maintains categorical levels for empty partitions when you expect that there's 1 partition that contains all the data for 1 group. That is the practical result (from a user perspecive) for Dask's built in aggregations like "sum" or "mean", which does not create extraneous rows (of NaN)s.

**Comment by TomAugspurger** [comment]
With a pandas dataframe, you can call `remove_unused_categories` on a Categorical.

**Comment by eugeneh101** [comment]
@TomAugspurger Thanks for the quick reply.
Perhaps, I am doing it wrong, but the extra NaN rows still exist. I run the lines in my first post and also:
`ddf.groupby(ddf["random_int"].cat.remove_unused_categories()).apply(pd.Series.median).compute()`
which prints:
```
           | random_int | random_float
random_int | -- | --
         0 | NaN | NaN
         1 | NaN | NaN
         0 | NaN | NaN
         1 | NaN | NaN
         0 | NaN | NaN
         1 | 1.0 | 0.511774
         0 | 0.0 | 0.516092
         1 | NaN | NaN
```

Am I misinterpreting your advice?

**Comment by TomAugspurger** [comment]
I'm not sure. Dask or pandas might be doing a reindex on the output, if you
want to dig through.

**Comment by jsignell** [comment]
@eugeneh101, I don't think you are removing the unused categories at the right time. It only really makes sense to remove them on each partition (see `map_partition`). But I think what really makes more sense is to do a `dropna` on your output. The warning that Tom mentioned seems to cover your case, so I don't actually think this is a bug.

**Comment by eugeneh101** [comment]
Hello @jsignell ! Thank you for answering this question. Sorry for the delay--the previous 2 weeks have been a bit hectic. The good news is that I have been evangelizing Dask (or rather helping people with Dask questions)  at the company I work!

You are correct that `map_partitions()` and `dropna()` will work. You can drop the NaN before `compute()` or after `compute()`:
```
ddf.groupby("random_int")["random_float"].apply(pd.Series.median).map_partitions(lambda s: s.dropna()).compute()
ddf.groupby("random_int")["random_float"].apply(pd.Series.median).compute().dropna()
```
both which correctly returns
```
  | random_int
1 | 0.494019
0 | 0.490220
Name: random_float, dtype: float64 
```
For the warning that Tom mentioned, the key piece of confusion is whether instances of each categorical level (across all partitions) will be pooled together into 1 "partition-group" pair. For example, if I use a built-in agg like `ddf.groupby("random_int")["random_float"].agg("min").compute()`, then I correctly get the results without the NaNs. However, if I do `ddf.groupby("random_int")["random_float"].apply(min).compute()`, then I get the results with NaNs. Ideally if possible with minimal effort, the results of these 2 calls should generate the same result for consistency.

I understand that perhaps every partition might contain the categorical level during a groupby but have no data. If the categorical levels per partition cannot be updated/removed if that partition doesn't have data corresponding to that categorical level during a groupby (ie if this is just how categorical column works), then I understand and that a fix would be very difficult or intractable. I understand practicality beats purity.

If there is a simple solution to fix this problem, that would be ideal. If not, feel free to close this issue. This issue is a minor thing that doesn't have practical negative implications since users can make this problems go away easily with an extra step (ie `dropna()`).

**Comment by jsignell** [comment]
Thank you for explaining your expectation so clearly! In the case of the predefined, named agg methods, we are able to do smarter things because we understand what is happening. We know how to reduce "min" for instance. For `apply` we don't have any knowledge of the function being applied, so it doesn't make sense to try to do a reduction. 

You can however write a custom aggregator which specifies both a mapping function and a reduction function.

```python
import dask.dataframe as dd
import pandas as pd
import numpy as np

N = 10000
df = pd.DataFrame({"random_int": np.random.randint(0, 2, N), "random_float": np.random.rand(N)})
df["random_int"] = df["random_int"].astype("category")
ddf = dd.from_pandas(df, npartitions=4)
custom_agg = dd.Aggregation('custom_sum', lambda s: s.median(), lambda s0: s0.median())
ddf.groupby("random_int")["random_float"].agg(custom_agg).compute()
```

See https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate for more info.  Note though that you have to be careful with this since the median of the median is not equivalent to the median....
