### ISSUE TITLE
Issue with dashboard when using DASK with `--dashboard-prefix` with Python3.7

### ISSUE THREAD

**Issue by mt-krainski** [dask/dask#6141]
Hey,

I just made a fresh installation of dask 2.15.0 with the latest related packages. When running with `--dashboard-prefix`, the dashboard doesn't render properly - references to `bokeh*.min.js` files are broken. They result in 404s.

I have:
```
python 3.7.5
dask==2.15.0
bokeh==2.0.2
distributed==2.15.0
```

From what I've noticed, when using Python 3.8 everything works as expected. Also, I'm not sure why, but it turns out downgrading `distributed` to 2.14.0 resolves the issue.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @mt-krainski! Do you have any logs or tracebacks you can post to help the debugging process?

**Comment by mt-krainski** [comment]
I'd be happy to post something, I'm just not sure if dask is logging requests to the dashboard anywhere? The scheduler on it's own doesn't log anything suspicious.

Running e.g. with
```
dask-scheduler --dashboard-prefix dask
```
The dashboard then is on `localhost:8787/dask/status` it looks like on the screenshot below 

![image](https://user-images.githubusercontent.com/16303679/80380225-90477080-889f-11ea-99aa-a301a8626572.png)

In the network tab of the developer tools of the browser, one can see that the requests for `bokeh*.min.js` files are failing with a 404.

![image](https://user-images.githubusercontent.com/16303679/80380348-bec54b80-889f-11ea-996e-1c56b800edd5.png)

**Comment by mrocklin** [comment]
My guess is that this is my fault after having reorganzied the Bokeh
application within a vanilla HTTP Server in
https://github.com/dask/distributed/pull/3658

**Comment by jrbourbeau** [comment]
I can reproduce the 404 errors. It seems the prefix is not being filled in for bokeh-related files. The HTML source for the status page is pointing to:

```
localhost:8787/dask/static/js/bokeh.min.js?v=ac90935137e13ae0b2c6583f2e1f3fe8
```

which doesn't exist. However if I remove the `dask/` prefix between `8787/` and `static`, then I'm able to properly navigate to the `.js` file locally. I'll navigate through https://github.com/dask/distributed/pull/3658, but if someone knows where we pass path information to bokeh for where it should put `.js` files that would be very useful

**Comment by mrocklin** [comment]
The BokehTornado application should have a prefix option that we should
have used.  If memory serves I didn't use this, and instead prepended the
prefix to all of the route names for each of the pages like status/tasks.
