### ISSUE TITLE
Array reduction name is not graph-key name

### ISSUE THREAD

**Issue by nre** [dask/dask#6170]
v2.15.0

I expected the graph-key name to be "my_name" instead of "sum".

```python
import dask.array as da
import numpy as np

dtype = np.int
da.reduction(
    da.ones(10, dtype, chunks=2),
    np.sum,
    np.sum,
    dtype=dtype,
    name="my_name").dask.layers.keys()
```
```python
dict_keys([
    'my_name-aggregate-271c2f44ef1b9e606cc14df3fd0c2a49',
    'my_name-partial-3e2ec900080765eb69c9589a1142cee1',
    'sum-a8e3a00efd53c7d17414ec7669d94c3d',
    'ones-6efb89dd626d392f89f98d296d7eecba'
])
```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @nre! I also would have expected that key to be `my_name-sum-...`. From a quick glance at the reduction code, it seems that `name` is not being provided to this `blockwise` call

https://github.com/dask/dask/blob/2d14075004fbca3ad7e5907f5f58ab8b05cdbdc2/dask/array/reductions.py#L155-L157

Is this something you're interested in working on? (no obligation though)
