### ISSUE TITLE
Allow da.stack to operate on unknown chunk sizes

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#6177]
Currently `da.stack` requires that shape of the passed arrays matches. This can fail when one of more of the chunk sizes is unknown:

```python

In [1]: import dask.array as da

In [2]: import numpy as np

In [3]: a = da.ones((10, 15))

In [4]: b = da.ones((10, 15))

In [5]: a._chunks = ((np.nan,), (15,))

In [6]: b._chunks = ((np.nan,), (15,))

In [7]: da.stack([a, b])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-87775e3d62ee> in <module>
----> 1 da.stack([a, b])

~/sandbox/dask/dask/array/core.py in stack(seq, axis)
   4257             "The first {0} had shape {1}, while array "
   4258             "{2} has shape {3}".format(
-> 4259                 idx[0], seq[0].shape, idx[0] + 1, seq[idx[0]].shape
   4260             )
   4261         )

ValueError: Stacked arrays must have the same shape. The first 0 had shape (nan, 15), while array 1 has shape (nan, 15)

```

We could accept an `allow_unknown_chunksizes` similar to `vstack` to treat missing chunk sizes as equal.

**Comment by mrocklin** [comment]
+1 from me.  I suspect that we'll still at least get a runtime error.

**Comment by TomAugspurger** [comment]
Oh... perhaps I'll remove the "good first issue" label then. I didn't look closely at the current implementation.

**Comment by TomAugspurger** [comment]
Oh I misunderstood. I think by "still get a runtime error" you mean we'll get a runtime error if the chunk sizes are in fact different.

**Comment by mrocklin** [comment]
Right, if the chunk sizes are different then they probably won't get an
error message when they construct the dask array, but they will get an
error when they call compute.  This is less awesome, but still nice to know.

**Comment by swapna-pg** [comment]
Would like to work on this.
Should we also change the exception message?
https://github.com/dask/dask/blob/592ab6cea0ea60da87b6e1e8a9a85a10d6af22de/dask/array/core.py#L3793-L3799

**Comment by TomAugspurger** [comment]
We'll want to keep that exception when any of the shapes are *known* to be different.

But we won't raise an exception there when we don't know if the shapes differ because one or more of the arrays has unknown chunk sizes.
