### ISSUE TITLE
Visualize not working, when writing to csv file

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask#6181]
Hello,

I want to visualize this execution graph.

```python
import dask

df = dask.datasets.timeseries(freq="10min", partition_freq="5d")
tasks = list()
for name in ["Dan", "Victor"]:
    tasks.append(
        df[df["name"] == name]
        # .to_csv(name, compute=False)
    )
dask.visualize(tasks)
```

Unfortunately, when uncommenting the "to_csv"-function nothing shows up. The execution works fine. I'm using dask 2.14.0.

It is not just a visualization problem. When serializing the graph to a file, the file is empty. However it visualizes `tasks[0]` just fine.

Greetings
Julian

**Comment by jrbourbeau** [comment]
Thanks for the nice minimal example @JulianWgs, I'm able to reproduce the behavior you're describing. In your example, with the `to_csv` portion uncommented, `tasks` is a nested list of `Delayed` objects

```python
In [1]: import dask
   ...:
   ...: df = dask.datasets.timeseries(freq="10min", partition_freq="5d")
   ...: tasks = list()
   ...: for name in ["Dan", "Victor"]:
   ...:     tasks.append(
   ...:         df[df["name"] == name].to_csv(name, compute=False)
   ...:     )
   ...: dask.visualize(tasks)
Out[1]: <IPython.core.display.Image object>

In [2]: tasks
Out[2]:
[[Delayed('_write_csv-98040538-07c5-48d8-a038-857e16ee1ac2'),
  Delayed('_write_csv-f281a022-a874-404a-81f9-8bbbdf04ad0b'),
  Delayed('_write_csv-45325d3b-b5fe-4761-b076-d04834c59b7e'),
  Delayed('_write_csv-cab7bba7-d633-4432-9240-23054277cdc7'),
  Delayed('_write_csv-d562a946-ba67-4bf3-847e-d099bd1497d1'),
  Delayed('_write_csv-49a8d34b-e32d-4d0c-9fa4-cc1dd396da42')],
 [Delayed('_write_csv-ef8fe226-5086-4f21-87fe-435daf2a2489'),
  Delayed('_write_csv-021dccd6-73f5-42d9-b0ab-6fe1d3363f1b'),
  Delayed('_write_csv-c6625f1c-7c75-4408-b523-0ab06255e3e6'),
  Delayed('_write_csv-2dfb00be-0bd7-4036-817e-f28ffe8f85e6'),
  Delayed('_write_csv-7ff9aa5e-f539-4fad-aa29-c978a8901301'),
  Delayed('_write_csv-458d603b-8a69-4718-8c8b-e5d6d2ea3eed')]]
```

But from the [`dask.visualize`](https://docs.dask.org/en/latest/api.html#dask.visualize), the `visualize` function is expecting dask collection(s) passed in as `*args` arguments. So if you modify the `visualize` call to be `dask.visualize(*tasks)`, then things should work. 

> When serializing the graph to a file, the file is empty.

I suspect this is from using `compute=False` in the `to_csv` call

**Comment by JulianWgs** [comment]
You're welcome. The least I can do ^^ Thanks for the fast answer! You are correct, that this shows the graph.

![grafik](https://user-images.githubusercontent.com/31596773/81086114-61ad4380-8ef8-11ea-8ac3-86d8c3bfcee3.png)

But now there 12 single graphs (for the 2 names and 6 partitions). Comparing this to the graph without the `to_csv`, which has only 6 single graphs and shares the results of the previous computation. This is the same with `optimize_graph` turned on.

![grafik](https://user-images.githubusercontent.com/31596773/81086511-e26c3f80-8ef8-11ea-976a-a98ed41ef4eb.png)

I haven't done any performance tests, but will check if the same compution is done twice.

Greetings
Julian

**Comment by JulianWgs** [comment]
```python
# little flatten function, which is more robust than "*tasks"
def flatten(nested_list, flattened_list=None):
    if flattened_list is None:
        flattened_list = list()
    # recursively call flatten if nested_list is a list
    if isinstance(nested_list, list):
        for item in nested_list:
            flattened_list = flatten(item, flattened_list)
    # append to flattened list, when nested_list is not a list
    else:
        flattened_list.append(nested_list)
    return flattened_list
```

```python
%%timeit
import dask

df = dask.datasets.timeseries(freq="10min", partition_freq="1d")
tasks = list()
for name in ["Dan", "Victor", "Norbert", "Kevin", "Patricia", "Michael", "Charlie", "Ray"]:
    tasks.append(
        df[df["name"] == name]
        #.to_csv(name, compute=False)
    )
dask.compute(flatten(tasks), optimize_graph=True)
```

Without `to_csv`: 646 ms ± 145 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
With `to_csv`: 1.67 s ± 25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

240 files had to be written with a total size of 592 KB on disk (For all runs).
I think, that this proofs, that the same compution is being done multiple times.

**Comment by JulianWgs** [comment]
I could get correct the correct graph in my actual usecase by using `dask.visualize(collections_to_dsk(flatten(tasks)), optimize_graph=True)`, but I can't reproduce it in the minimum working example. Also pandas has a flatten function for arbitrary nested lists: `from pandas.core.common import flatten`

**Comment by quasiben** [comment]
I think the original issue of how to visualize has been resolved.  I am little confused issue of duplicate computation you are bringing up but from my reading of I think you want to be calling `to_csv` only once.  As it stand now you are calling it twice, once for each name.  

Perhaps you want something like:
> df[(df["name"] == 'alpha') | (df["name"] == 'beta')].to_csv(name, compute=False)

Where all the filtering is done prior to calling `to_csv` ?

**Comment by JulianWgs** [comment]
@quasiben Thanks for the reply!

The use case is to save a csv file for every name (or more general filter operation). So the `to_csv` should be appended to every filtering operation in the graph, but it somehow splits it into several graphs. I know that this discussion does not resemble the original issue perfectly, but still the `to_csv` does something to the graph which any other non file related operation does not.

My benchmark might not proof the incorrect graph, but counting the number of tasks shows a difference in the amount of actual and theoretical tasks. 
These are my calculation for the number of tasks
```python
# (make-timeseries per partition) + getitem per npartion and len(names) + (additional getitem per partition)
print("Without to_csv:", df.npartitions + df.npartitions*len(names) + df.npartitions)
# just add a to_csv per partition and name
print("Theoretical to_csv:", df.npartitions + df.npartitions*len(names)*2 + df.npartitions)
# Having three operation per partition and name (make-timeseries, getitem, to_csv)
# make-timeseries should only be called once per partition
print("With to_csv:", df.npartitions*(len(names))*3)
# Use my flatten function
print(len(collections_to_dsk(flatten(tasks))))
```

Do you want me to rename the issue, open a new one or is it OK like it is?

Greetings

**Comment by quasiben** [comment]
I suspect what you are seeing here is how dask is optimizing for both the creation of data and the `to_csv` call.  If you cut off the graph after creation (calling persist()) I believe you get a more reasonable graph:

```python
In [8]: df = df.persist()

In [9]: for name in ["Dan", "Victor"]:
   ...:     tasks.append(
   ...:         df[df["name"] == name].to_csv(name+'.csv', compute=False)
   ...:         )
   ...:

In [10]: dask.visualize(*tasks, optimize_graph=True, filename='to-csv.png', verbose=True)
```

![to-csv](https://user-images.githubusercontent.com/1403768/81439298-2c913300-913c-11ea-82b3-a38b511dc454.png)


As a separate comment, this will create 6 CSVs per filter, not a single csv.  For that you will need to pass in `single_file=True`

**Comment by JulianWgs** [comment]
Thank you for your help. This solves my problem :) Feel free to close this issue. 

However I still think that this is not an obvious way to do it and the behavior is unexpected. For what reason should dask optimize if it is not told to do so? Also it is unexpected to have to switch the `dask.visualize` call in order draw the graph with or without the `to_csv`. I still think this is worth investigating.

**Comment by quasiben** [comment]
Thanks for the feedback @JulianWgs .  If you have concrete thoughts on how to improve dask please come and share and of course if you have other problems please open up other issues
