### ISSUE TITLE
pytest fails on windows without pyarrow

### ISSUE THREAD

**Issue by brl0** [dask/dask#6189]
Running pytest in a bare environment on Windows fails during collection with the following error:
`NameError: name 'pa' is not defined`

The relevant bits of code from `dask/dataframe/io/tests/test_parquet.py`:
```
try:
    import pyarrow as pa

    check_pa_divs = pa.__version__ >= LooseVersion("0.9.0")
except ImportError:
    check_pa_divs = False

...

if sys.platform == "win32" and pa.__version__ == LooseVersion("0.16.0"):
```

The last line was added in #6094, which was a fix to #6093.   

As a side note, `check_pa_divs` is unused.

I will submit a PR with a minor correction.

**Comment by jcrist** [comment]
Fixed by #6190.
