### ISSUE TITLE
Feature request: Bag Repartition "partition_size" keyword argument

### ISSUE THREAD

**Issue by ankur-gos** [dask/dask#6197]
Hi there,

Love this project, use it extensively in my day to day.

This is a feature request for the [```Bag.repartition```](https://docs.dask.org/en/latest/bag-api.html#dask.bag.Bag.repartition) function. The [```Dataframe.repartition```](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.repartition) function has a nice ```partition_size``` keyword which repartitions the dataframe by a specified size. It would be really nice to have the same argument for ```Bag.repartition```. Right now I have to estimate the number of partitions I'll need to get my data down to 100mb per partition prior to calling repartition, so this would be a quality of life improvement for me.

Cheers and thank you for this great project!

**Comment by jsignell** [comment]
Hi @ankur-gos thank you for the suggestion! This seems like a reasonable suggestion and one that could be supported. Would you be interested in working on this?
