### ISSUE TITLE
How to properly upgrade dask

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#6201]
I used to upgrade my dask environment using the following command.
```sh
python -m pip install --upgrade dask
```
Recently I realized, it is not sufficient to properly upgrade dask, because some of its components are not getting upgraded, and will not play well anymore. I needed to use that as well.
```sh
python -m pip install --upgrade dask[distributed]
```
My question is how one should properly upgrade dask ensuring that **all its components** (distributed, pandas, etc.) are in the **proper version** (which possibly may not always be the latest one) so they will play well together?

**Comment by quasiben** [comment]
I would assume that:

> python -m pip install --upgrade "dask[complete]"

should work but I haven't tested it.

**Comment by jsignell** [comment]
I'm going to close this unless you  are still experiencing the issue @jangorecki

**Comment by jangorecki** [comment]
As there are no other solutions provided I understand the method provided by @quasiben is the canonical way to upgrade dask then. Thank you.
