### ISSUE TITLE
factor repr_html into a more standalone utility?

### ISSUE THREAD

**Issue by rabernat** [dask/dask#6212]
I have come to truly love dask's repr_html svg representation of arrays. It has become an invaluable way to communicate with colleagues about complex high-dimensional array computations. Here's an example of the sort of data we regularly work with:
![html_repr](https://aws1.discourse-cdn.com/standard14/uploads/pangeo/original/1X/e6bf349a6d97eb42e2deed8e5971bbf0814561d7.png)
which I used in a recent [Pangeo discourse discussion](https://discourse.pangeo.io/t/best-practices-to-go-from-1000s-of-netcdf-files-to-analyses-on-a-hpc-cluster/588/9).

I frequently find myself wishing I could use this visualization technique  without dask, e.g. with zarr arrays, which have many (but not all) of the same attributes (shape, chunks, dtype; but not tasks).

It would be nice to be able to write code like
```python
array_html_repr(some_array)
# or
class SomeArrayClass:
    def _html_repr_(self):
        return array_html_repr(self)
```
and have it just work with any array that implement certain properties. (Could even do something with numpy arrays.)

I have examined the html_repr code a bit, and it looks like this would not be to hard. It could live either
- inside dask, in a form we can easily import into other projects
- in a small, standalone project, e.g. `dask/array_html_repr`

Does anyone else think this might be a good idea?

**Comment by jcrist** [comment]
I'm -0.5 on pulling this functionality out of dask - synchronizing dependencies and releasing multiple projects makes maintenance slightly trickier. If having it live in dask, but in a more public location would be acceptable, I'd happily accept a PR doing so.

**Comment by rabernat** [comment]
> If having it live in dask, but in a more public location would be acceptable

Would definitely work for my purposes!

**Comment by martindurant** [comment]
It seems that the implementation in `Array._repr_html_` depends on `._meta`, `.nbytes`, `.dtype`, `._dask_graph__`, `.npartition`, `.shape`, `.chunksize`. Obviously, some of these are specific to the dask implementation.

@rabernat , what do you imagine passing to a more generic HTML repr function, and what would it display?

**Comment by martindurant** [comment]
If there is no further discussion here, I would be tempted to close.
