### ISSUE TITLE
float() argument must be a string or a number, not 'Delayed'

### ISSUE THREAD

**Issue by APWx** [dask/dask#6218]
##############################################################
This does NOT work:
##############################################################
```
from dask import delayed

@delayed
def some_fun(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)

def equalize_adapthist_images(images):
    for i in range(len(images)):
        images[i,:,:] = delayed(some_fun)(images[i,:,:])
    return delayed(images)

l = equalize_adapthist_images(images)
```

Error_Message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: float() argument must be a string or a number, not 'Delayed'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-108-791ed8bf6bee> in <module>
----> 1 l = equalize_adapthist_images(images)
      2 #plt.imshow(equalize_adapthist_images(images)[70,:,:])

<ipython-input-107-a73e67b4dd30> in equalize_adapthist_images(images)
      7 def equalize_adapthist_images(images):
      8     for i in range(len(images)):
----> 9         images[i,:,:] = delayed(some_fun)(images[i,:,:])
     10     return delayed(images)

ValueError: setting an array element with a sequence.

##############################################################
This does work:
##############################################################
```
def some_fun(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)

def equalize_adapthist_images(images):
    for i in range(len(images)):
        images[i,:,:] = some_fun(images[i,:,:])
    return images

l = equalize_adapthist_images(images)
```

#############################################################

Hi, I was wandering if someone could provide any guidance in solving
the above issue. 

Some comments: I suspect that it has to do with converting 3D numpy array
here represented by 'images' into dask arrays (yes?). I attempted to do so but failed.
I have noticed that in dask documentation, the creation of dask arrays involves
slicing data into  chunks. Is it needed considering that I would like to parallelize 
the for loop without dividing an array into chunks.

Any help would be greatly appreciated.

**Comment by jcrist** [comment]
It looks like `images` is a numpy array? You can parallelize array code using either `dask.delayed` or `dask.array`. Dask generally works best if you write your functions to not modify their inputs, but to return new values (avoid mutation). Given your exact workload, I'd write this as:

```python
import dask.array as da
import numpy as np


# Some fake data
images = np.random.randint(0, 256, size=(20, 5, 6))


# Ideally your function would support broadcasting, but since if it doesn't you
# can wrap it in `da.as_gufunc`, and have dask handle that for you.
# See https://docs.dask.org/en/latest/array-gufunc.html
@da.as_gufunc(signature="(n,m)->(n,m)", vectorize=True)
def some_fun(zz):
    # Some function that returns an output with the same shape as the input
    return zz + 1

# Convert images to a dask array, chunking along the first axis
# - `auto` lets dask choose a good chunk size, you could replace with a
#   number of you want smaller/bigger chunks
# - `-1` tells dask not to split along that axis
#
# I'll use a fixed chunk here to demonstrate with small data, but for many
# problems `auto` is sufficient

# chunk_size_on_axis = "auto"
chunk_size_on_axis = 4
d_images = da.from_array(images, chunks=(chunk_size_on_axis, -1, -1))

# Apply `some_fun` to your dask array
res = some_fun(d_images)
```

For the general problem of applying some user-defined function that works on small numpy arrays across a larger `dask.array`, the following functions are generally useful:

- [`dask.array.map_blocks`](https://docs.dask.org/en/latest/array-api.html#dask.array.map_blocks)
- [`dask.array.blockwise`](https://docs.dask.org/en/latest/array-api.html#dask.array.core.blockwise)
- [`dask.array.as_gufunc`](https://docs.dask.org/en/latest/array-gufunc.html)

I recommend going through the array section of [tutorial](https://tutorial.dask.org/03_array.html) to get a better feel for `dask.array`.

Does that answer your question?

**Comment by APWx** [comment]
Thank you for the directions.  It looks like I will need some more study time especially when it comes to tutorials you have mentioned.  Yes , images is a numpy array. I think (as there are no errors) that I have been able to adapt your code to the use case i.e. to parallel the for loop.  Am not sure though if I did it correctly as there is no speed up, even for larger arrays .  Am I missing something or it must be a  huuuge array to get any speed improvement relative to regular for loop?  Is there anything I should modify below? 

```
import dask.array as da
import numpy as np
import dask as delayed
import time
from skimage import exposure
# Some fake data
images = np.random.randint(0, 256, size=(10000, 70, 90))
```
```
@da.as_gufunc(signature="(n,m)->(n,m)", vectorize=True, output_dtypes=float)
def some_fun_dask_ON(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)

def some_fun_dask_OFF(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)

chunk_size_on_axis = 'auto'
d_images = da.from_array(images, chunks=(chunk_size_on_axis, -1, -1))
```
The  Wall time comparison is as follows:

```
%%time
# Dask ON
l = np.zeros(images.shape)
for i in range(1000):
    l[i,:,:] = some_fun_dask_ON(d_images[i,:,:])
```
Wall time: 34.8 s

```
%%time
# Dask OFF
l = np.zeros(images.shape)
for i in range(1000):
   l[i,:,:] = some_fun_dask_OFF(images[i,:,:])
```
Wall time: 23.4 s

**Comment by jcrist** [comment]
The following script should run as is:

```python
import time

import numpy as np
import dask.array as da
from dask.distributed import Client
from skimage import exposure

@da.as_gufunc(signature="(n,m)->(n,m)", vectorize=True, output_dtypes=float)
def some_fun_dask(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)


def some_fun(zz):
    return exposure.equalize_adapthist(zz, clip_limit=0.1)


if __name__ == "__main__":
    # Some fake data
    images = np.random.randint(0, 256, size=(2000, 70, 90)).astype("uint16")

    start = time.time()
    l = np.zeros(images.shape)
    for i in range(images.shape[0]):
        l[i,:,:] = some_fun(images[i,:,:])
    stop = time.time()
    print("Without dask took %.1f seconds" % (stop - start))


    with Client(threads_per_worker=1) as client:
        start = time.time()
        d_images = da.from_array(images, chunks=(100, -1, -1))
        # A dask array representing your result
        d_res = some_fun_dask(d_images)
        # Compute the result and bring it back to the client process
        res = d_res.compute()
        stop = time.time()
        print("With dask took %.1f seconds" % (stop - start))
```

Running this I see:

```
$ python temp.py
Without dask took 20.0 seconds
With dask took 8.1 seconds
```

A couple notes:

- The reason yours wasn't working was because you still had a loop in python over the array indices. The point of wrapping your function in `as_gufunc` is that the for-loop isn't necessary - dask handles the broadcasting over that axis (in parallel) for you. This is the `some_fun_dask(d_images)` call. The way you've written it, you're calling into dask's machinery for every slice in the array serially. Since dask does have overhead, and you're giving it nothing to parallelize on, it's bound to ber slower.
- Even with the above fix, I still saw a slowdown when using dask. The reason for this is that `exposure.equalize_adapthist` doesn't release the interpreter lock, so parallelizing with threads (dask-array's default scheduler) will only result in slowdowns. You can see this using the [`ptime`](https://github.com/jcrist/ptime) IPython magic:

```
In [7]: f = np.vectorize(some_fun, signature="(n,m)->(n,m)")

In [8]: %ptime -n4 f(images[:20])
Total serial time:   0.82 s
Total parallel time: 1.37 s
For a 0.60X speedup across 4 threads
```

To fix this, we run the computation in the distributed scheduler (which works fine locally, and can parallelize across processes instead of threads). With that change, I see some speedups. On my machine the best we could expect is 4x than running serially (I have 4 cores), so ~2.5x isn't too bad.

---

I suggest you go through the dask tutorial at tutorial.dask.org. Notebooks 1, 3, 5, & 6 especially should help you gain some insights into how dask works and how it can help you.

**Comment by APWx** [comment]
Thank you for all the guidance and the code! Based on it I have run a few performance tests, the results of which can be accessed here:

[https://docdro.id/6w0ZbT7](url)  

Some observations ... Speedup is clear once the number of rows (chunked axis) increases. But an increase in other two dimensions reduces that speedup.  There is also some cut-off threshold in the number of rows below which the speedup is not observable.

**Comment by jcrist** [comment]
Thanks for the benchmark update, glad you got some positive results. Dask generally gets more efficient as you build longer pipelines - currently you're sending arrays to the workers, running a function on them, then pulling the results back. Longer pipelines amortize the cost of the data transfer, and result in larger speedups. We usually advise users to see if they can find a way to load the data directly on the workers (usually this is done with `delayed` wrapping a loading function, and `from_delayed` to convert to a larger dask array).

Anyway, glad this has been helpful. Closing, feel free to reopen if you run into more issues.
