### ISSUE TITLE
A concurrent.futures.Executor scheduling interface

### ISSUE THREAD

**Issue by tomwhite** [dask/dask#6220]
I've created a [prototype Dask scheduler](https://github.com/tomwhite/dask-executor-scheduler) that uses a Python [concurrent.futures.Executor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor) to run tasks. @mrocklin suggested I open an issue here to discuss if/how it could be incorporated in Dask.

My motivation for building it was to make it possible to get Dask to use serverless cloud functions for executing tasks. I've had success running a small Dask job using [Pywren](https://github.com/pywren/pywren-ibm-cloud) on Google Cloud Run.

I'd be interested to hear what others think about this feature, and if it would be worth exploring further.

**Comment by jcrist** [comment]
Thanks for posting this @tomwhite, this is neat to see. My gut reaction is that this should continue to be a separate project in the near term, but at some point we may want to introduce it to core. Others may feel differently though. The implementation looks pretty clean building off of `dask.local.get_async`, so we hopefully didn't make this too tricky for you to write.

I'd expect this to perform fairly well for workloads where task input/output data sizes were relatively small compared to the amount of work they needed to process (since serializing to/from s3 will be more expensive than running in threads/using distributed's comms). Did you have a use case in mind for this?

**Comment by mrocklin** [comment]
I think that we should consider replacing the apply_async API in dask.local
with a concurrent.futures API.  We chose apply_async because
concurrent.futures wasn't Python 2 compatible.

I see two potential costs here

   1. There might be some performance change (we should measure this)
   2. API churn

But there would be benefits.  Any project that implemented a
concurrent.futures API could schedule Dask graphs on it.  I think that the
goal here isn't to integrate PyWren, but to make it so that a PyWren-Dask
project doesn't need to exist for the two projects to work well together.

**Comment by tomwhite** [comment]
@jcrist, thanks for your comments. The use case I have in mind is processing Zarr, since the data is read to/from cloud storage, rather than being serialized to/from the client, which as you say would be expensive.

@mrocklin That sounds good. I wouldn't know where in the Dask API a concurrent.futures version would slot in, but could it sit alongside the current way of doing things?

**Comment by jakirkham** [comment]
Thanks for working on this and sharing Tom! 😄

This would be handy in a few cases. Agree with Jim and Matt. It might be good to get some more testing of it (perhaps you have recommendations for people wanting to try it out). Upstreaming into `dask.local` makes sense or possibly adding a `dask.async`(?).

One other cost I would add is that debugging workloads in the wild could be more complex. So it may still be useful to have what we have now (just as a fallback for people doing debugging).

Should add others have looked for functionality like this to enable launching tasks from tasks for example (cc @shoyer as I think we discussed this previously in relation to improving `vindex` algorithm IIRC). So this would be useful for that case as well.

**Comment by jakirkham** [comment]
As a side note, we may want to use an [`asyncio.Queue`]( https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue ) as [part of this change]( https://github.com/dask/dask/blob/7b4f90f0a708cbb97ebb498c78f7931d82ec99db/dask/local.py#L108 ) to ensure we have [a non-blocking way]( https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue.put_nowait ) to [add tasks]( https://github.com/dask/dask/blob/7b4f90f0a708cbb97ebb498c78f7931d82ec99db/dask/local.py#L466 ). Though please feel free to correct me if I'm off here.

**Comment by jcrist** [comment]
> As a side note, we may want to use an asyncio.Queue as part of this change to ensure we have a non-blocking way to add tasks. Though please feel free to correct me if I'm off here.

Yeah, this is out of place for this change. The local executor has nothing to do with asyncio, it wouldn't make sense to use that queue here. The standard `queue.Queue` works fine, and since it's unbounded won't block.

**Comment by jakirkham** [comment]
Ah ok. Thanks for the clarification and sorry for the noise.

**Comment by tomwhite** [comment]
@jakirkham thanks for the encouragement and ideas!

Regarding people who want to try it out, I would suggest looking at the [repo](https://github.com/tomwhite/dask-executor-scheduler) for details. I'd be especially interested in people trying it out with Zarr (I haven't done that), since I think there is a good use case for preprocessing data stored in Zarr in the cloud, by transforming/filtering etc to a small subset for more complex processing on a single machine (e.g. graph algorithms which need multiple passes over the data).

Good point too about debugging. I see this interface as an alternative, to allow people to try new scheduling strategies, rather than a full replacement to the current way of doing things.

**Comment by jakirkham** [comment]
Thanks for sharing those details, Tom!

FWIW I found the issue about submitting tasks within tasks in case that is of interest. ( https://github.com/dask/dask/issues/3235 )

Interesting about handling multiple passes over the data. A somewhat common pattern that shows up across domains is this one ( https://github.com/dask/dask/issues/874 ). Would be interesting to see how your approach applies to this problem.

TBH I don't see debugging as a blocker (a concurrent.futures based scheduler is pretty valuable). Just something we should keep in mind.

**Comment by jakirkham** [comment]
Would it make sense to replace our existing implementations of [`dask.mulitprocessing`]( https://github.com/dask/dask/blob/master/dask/multiprocessing.py ) and [`dask.threaded`]( https://github.com/dask/dask/blob/master/dask/threaded.py ) with ones using `ProcessPoolExecutor` and `ThreadPoolExecutor`? Do we want to keep the existing implementations around in some form?

How should the single threaded case change (if at all)?

**Comment by mrocklin** [comment]
Yes, that is exactly what I'm saying.  We would replace the apply_async
system with a concurrent.futures system, probably using .submit and .result
rather than .apply_async and .get.

**Comment by jakirkham** [comment]
Ah ok. Sorry if I'm just misunderstanding.

Do you have thoughts on what we do with the single threaded case (if anything)? Should we have a dummy executor? Should it stay as-is?

**Comment by TomAugspurger** [comment]
FWIW, there was a python-ideas thread about a
concurrent.futures.SerialExecutor:
https://mail.python.org/archives/list/python-ideas@python.org/thread/LMTQ2AI6A7UXEFVHRGHKWD33H24FGM6G/#ICJKHZ4BPIUMOPIT2TDTBIW2EH4CPNCP

I don't think it's going anywhere though, so stay as-is probably makes the
most sense.

**Comment by jakirkham** [comment]
Thanks for the info.

Yeah leaving as-is makes sense. The only reason I wonder about it is if the changes in [`dask.local`]( https://github.com/dask/dask/blob/master/dask/local.py ) might be made simpler by being able to assume a [`concurrent.futures.Executor`]( https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor ) in all cases.

**Comment by mrocklin** [comment]
I suspect that we can make a SerialExecutor that implements submit/result
on our own in around twenty lines of code.  We don't need the full
concurrent futures interface.

**Comment by tomwhite** [comment]
@jakirkham thanks for doing the work in #6322, it looks very promising!

I've been thinking about how this could be used for the application I mentioned above. For PyWren, the ability to batch multiple calls to the same function is critical for efficiency: this is achieved by using the `map()` call on `Executor`, rather than individual calls to `submit()`. However, as it stands, #6322 uses `submit()` rather than `map()` since it is designed  to submit one task at a time (which is the existing way Dask works). There are a couple of ways I can see to get this working with PyWren-like systems:

1. Write an `Executor` wrapper that queues up calls to `submit()` and sends them in a batch to the `map()` method of the underlying `Executor`. This would be very similar to the code in https://github.com/tomwhite/dask-executor-scheduler/blob/master/dask_executor_scheduler/executor.py. This could live in Dask or somewhere else.
2. Incorporate batching into the `get_async` code directly. For a batch size of 1 (the default) it would use `submit()`, otherwise it would use `map()`.

Both of these are probably outside the scope of #6322, but I wanted to mention this in case anyone had any other ideas about how to tackle this problem.

**Comment by photoszzt** [comment]
I'm wondering which approach is faster. There's a recent SoCC paper that does similar thing: https://arxiv.org/pdf/2010.07268.pdf and their code: https://github.com/mason-leap-lab/Wukong/tree/socc2020 It has more changes on the scheduler.

**Comment by jakirkham** [comment]
Sorry for the lack of reply Tom. Agree that switching Dask to use `map` in the future makes sense. We should probably track that in a new issue once we are happy with and have merged PR ( https://github.com/dask/dask/pull/6322 )

**Comment by jakirkham** [comment]
One thing that is a little odd about `map`, is it doesn't return `Future`s, but instead a generator, which produces all of the results in order. However Dask doesn't really need to wait for them to finish in order and doesn't need for all of them to finish before submitting new tasks. Not sure if there is a better way to approach this with `concurrent.futures`, but wanted to raise these limitations for awareness

**Comment by jakirkham** [comment]
Ok PR ( https://github.com/dask/dask/pull/6322 ) now handles batching as well. We couldn't use `map` for the reason above and because of some oddities with `ProcessPoolExecutor.map` on Windows. However we do batch submissions with `Executor.submit`, which seem to have fairly similar performance

**Comment by jakirkham** [comment]
As to batching, raised issue ( https://github.com/dask/dask/issues/7510 ) about potentially refining this feature and documenting it better. Currently it is present, but a bit hidden atm
