### ISSUE TITLE
Unexpected behavior on apply when data are int and float numbers

### ISSUE THREAD

**Issue by argenisleon** [dask/dask#6223]
Hi,
I have this dataframe
```
from dask import dataframe as dd
import numpy as np

a = pd.DataFrame({"A":[5, 1.1]}, dtype=object)
ddf = dd.from_pandas(a, npartitions=1)
print(ddf.compute())

     A
0    5
1  1.1

```
and I am trying to change the number 1.1 to 1.2
```
def func(value):
    if value == 1.1:
        return 1.2
    return value

ddf["A"] = ddf["A"].apply(func, meta=object)
print(ddf.compute())

     A
0  5.0
1  1.2
```

The issue is that '5' has been converted to 'float'. Is this the expected behavior?

**Comment by luis11011** [comment]
To avoid this behaviour you may pass `convert_dtype=False` to `Series.apply`

`ddf["A"] = ddf["A"].apply(func, meta=object, convert_dtype=False)`

**Comment by jcrist** [comment]
To further clarify, yes, this is also how pandas (which dask wraps) works:

```python
In [6]: a = pd.DataFrame({"A":[5, 1.1]}, dtype=object)

In [7]: def func(value):
   ...:     if value == 1.1:
   ...:         return 1.2
   ...:     return value
   ...:

In [8]: a["A"].apply(func)
Out[8]:
0    5.0
1    1.2
Name: A, dtype: float64
```

as @luis11011 said, if you don't want pandas to implicitly convert, you can pass `convert_dtype=False`.

The general answer is - dask tries to maintain pandas compatibility. We're not always successful in that, but if dask does something and pandas also does it, then it's intended behavior.
