### ISSUE TITLE
index-only (no-columns) df.shape issue

### ISSUE THREAD

**Issue by noreentry** [dask/dask#6234]
``` python
assert dd.from_pandas(pd.DataFrame(index=[1,2,3]), npartitions=1).compute().shape[0] == 3  # that's ok
assert dd.from_pandas(pd.DataFrame(index=[1,2,3]), npartitions=1).shape[0].compute() == 3
```
raises **ValueError: cannot convert float NaN to integer**

**Comment by quasiben** [comment]
The number or rows / `shape[0]` is delayed.  Columns, however is a concrete value

```
In [18]: dd.from_pandas(pd.DataFrame(index=[1,2,3]), npartitions=1).shape
Out[18]: (Delayed('int-174d00fa-5844-47ae-a047-60cb2f4a1ec0'), 0)
```

**Comment by TomAugspurger** [comment]
In DataFrame.shape we have https://github.com/dask/dask/blob/8dc4c1a7967bc7bad96c6c282054d53b829a40ea/dask/dataframe/core.py#L3495-L3497

With no columns we do a `0 / 0` which is nan and try to convert that to an int, which raises.

Perhaps it's always best to define the length as a `map_partitions(sum).sum()`. @noreentry are you interested in working on this?

**Comment by quasiben** [comment]
I think PR https://github.com/dask/dask/pull/6237 is meant to address this but I missed the PR on the first pass of reviewing things
