### ISSUE TITLE
Parquet RangeIndex is ignored

### ISSUE THREAD

**Issue by Zaharid** [dask/dask#6235]
The documentation for [read_parquet](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_parquet) states that the index is by default "inferred from the pandas metadata". However it doesn't seem to be working when the index is a range index, even though it works fine with the underlying engine. The following

```python
import pandas as pd
import dask
import dask.dataframe as dd
import pyarrow.parquet as pq

pd.DataFrame([4,5,6], index=range(3,6), columns=['Col']).to_parquet('/tmp/xx.pq')

print(dask.__version__, dask.__git_revision__)

print('pandas', pd.read_parquet('/tmp/xx.pq').index)

print("dask fastparquet", dd.read_parquet('/tmp/xx.pq', engine="fastparquet").index.compute())
print("dask pyarrow", dd.read_parquet('/tmp/xx.pq', engine="pyarrow").index.compute())
print("pyarrow", pq.read_table('/tmp/xx.pq').to_pandas().index)
```

should print the same index for each code path. However it prints

```
2.16.0 d65c44f721013d915c8bff0424775dc47345ec03
pandas RangeIndex(start=3, stop=6, step=1)
dask fastparquet RangeIndex(start=0, stop=3, step=1)
dask pyarrow RangeIndex(start=0, stop=3, step=1)
pyarrow RangeIndex(start=3, stop=6, step=1)
```

Also may I ask if there is a quick workaround?

**Comment by TomAugspurger** [comment]
cc @dask/io. Can this reasonably be supported for multi-file datasets?

**Comment by rjzamora** [comment]
> Can this reasonably be supported for multi-file datasets?

I suppose its possible, but it could get messy when doing things like filtering.  We certainly have access to the required pandas metadata, but would need to determine the length of the first n-1 partitions before reading.

**Comment by martindurant** [comment]
Don't the individual files have different RangeIndexes, so loading each of them should give the right range from the original?

**Comment by rjzamora** [comment]
> Don't the individual files have different RangeIndexes, so loading each of them should give the right range from the original?

That could be true - But then we would need to parse the pandas meteadata for every partition separately (which we are not doing right now).

**Comment by martindurant** [comment]
> then we would need to parse the pandas meteadata for every partition

Ah, if we want the divisions to be correct...

However, the global range index can be inferrer for each partition when we have the row counts for each partition (from a _metadata file), even if we then ignore some of the parts.

**Comment by bryanwweber** [comment]
I get the following output from the original script:

```
2022.02.1 217561b4266c170f452471fed64123940066c4b8
pandas RangeIndex(start=3, stop=6, step=1)
dask fastparquet RangeIndex(start=3, stop=6, step=1)
dask pyarrow RangeIndex(start=3, stop=6, step=1)
pyarrow RangeIndex(start=3, stop=6, step=1)
```

It seems this issue is resolved. If that's not the case, please feel free to reopen! 😄
