### ISSUE TITLE
map_blocks can not return correct shape of input

### ISSUE THREAD

**Issue by df19900725** [dask/dask#6241]
I am using map_blocks to process dask array. However, it can never return the desired shape. Each block is a 2D array. And the function will return 3D. However, I can never get correct result. I know I should give chunks shape if I changed the block.

```
import numpy as np
import dask
import dask.array as da

def get_lagged_value(source_array, index_array):
    res = np.apply_along_axis(lambda c: c[index_array], 1, source_array)
    return res

if __name__ == '__main__':
    source_array = np.random.randint(0, 10, (3, 4))

    index_array_0 = np.asarray([[0, 0, 0], [1, 0, 0], [2, 1, 0], [3, 2, 0]])

    b = np.apply_along_axis(lambda a: a[index_array_0], 1, source_array)
    print(b.shape)

    source_array = da.from_array(source_array, chunks=(2, 4))

    b = source_array.map_blocks(get_lagged_value, index_array=index_array_0, dtype='i8', chunks=[1, 4, 3]).compute()
    print(dask.compute(b.shape))
```

If I remove chunks=[1,4,3], then the code will throw an exception.

If I use np.apply_along_axis diectly to numpy array. The program will return (3, 4, 3) shape and this is  what I want. However, when I add chunks=[1,4,3], it gives ((2, 8, 3),)?

**Comment by jsignell** [comment]
It looks like you are just missing the `new_axis` keyword argument. If instead you do:

```python
b = dask_array.map_blocks(get_lagged_value, index_array=index_array_0, dtype='i8', chunks=(3, 4, 3), new_axis=2).compute()`

```
Then you should be good to go. Let me know if that doesn't solve things for you.

**Comment by df19900725** [comment]
@jsignell Thx, I have realized the meaning of the parameter `new_axis` is the new dimension index that the function will generate. Therefore, I should add `new_axis=[2]` since my function extend the 2D input to 3D and the first two dims remains unchanged. I was so confused by the doc. Thank you very much, the code can run successfully now.

**Comment by jsignell** [comment]
Exactly! If you have a suggestion for how to improve the docs, please open a pull request!

**Comment by df19900725** [comment]
@jsignell Thx, I will try it.
