### ISSUE TITLE
Problem installing dask[complete]

### ISSUE THREAD

**Issue by jackieleng** [dask/dask#6256]
**What happened**:

Installing dask with the 'complete' extra doesn't seem to work and gives a warning.

```

$ pip install -U dask[complete]

Requirement already up-to-date: dask[complete] in ./env/lib/python3.6/site-packages (2.17.1)
WARNING: dask 2.17.1 does not provide the extra 'complete'
Requirement already satisfied, skipping upgrade: pyyaml in ./env/lib/python3.6/site-packages (from dask[complete]) (5.1.2)
```

**What you expected to happen**:

I expect it to install with the 'complete' extras.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.17.1
- Python version: 3.6.9
- Operating System: WSL
- Install method (conda, pip, source): pip

**Comment by DVerzal** [comment]
One of our docker images is failing the build process for the same reason. We had to force it to install dask[complete]==2.17.0 for now.

**Comment by jrbourbeau** [comment]
Thanks for reporting @jackieleng @DVerzal! This was fixed by https://github.com/dask/dask/pull/6257. We'll push a new 2.17.2 release with the fix shortly

**Comment by jrbourbeau** [comment]
`dask==2.17.2` is on PyPI now and should be on conda-forge and docker hub within an hour or two

**Comment by jrbourbeau** [comment]
Closing as you can now `pip install  "dask[complete]"` again. Thanks all for reporting
