### ISSUE TITLE
Incompatibility between 2.8.0 and 2.16.0

### ISSUE THREAD

**Issue by jrdzha** [dask/dask#6269]
Groupby meta seems to have broken between v2.8.0 and v2.16.0. Things work fine on 2.8.0, but on 2.16.0 I get:

> ValueError: The columns in the computed data do not match the columns in the provided metadata
>   Extra:   ['customer_id', 'product_parent']
>   Missing: []

Minimal Complete:
```python
import datetime
import dask.dataframe as dd
import pandas as pd

df = dd.from_pandas(pd.DataFrame({'marketplace': {0: 'US'},
 'customer_id': {0: '35680291'},
 'review_id': {0: 'R34O1VWWYVAU9A'},
 'product_id': {0: 'B000MWFEV6'},
 'product_parent': {0: '406798096'},
 'product_title': {0: 'Baxton Studio Full Leather Storage Bench Ottoman, Espresso Brown'},
 'star_rating': {0: 5},
 'helpful_votes': {0: 1},
 'total_votes': {0: 1},
 'vine': {0: 'N'},
 'verified_purchase': {0: 'Y'},
 'review_headline': {0: 'High quality and roomy'},
 'review_body': {0: "I bought this bench as a storage necessity as I was moving into a smaller room with a smaller dresser. I knew I'd have clothing overflow. This bench solved it and more. It's very roomy. I was able to get all my bulkier sweaters in it, plus still have room for a folded up blanket.<br /><br />The workmanship is high quality (should be for the price), and it's not a piece I'd envision giving away (like you would Ikea stuff) after it gets broken in. I'm very pleased with it."},
 'review_date': {0: datetime.date(2009, 5, 17)},
 'year': {0: 2009}}), npartitions=1)

# This is the line that breaks
df = df.groupby('marketplace').apply(pd.DataFrame.median)
```

- Dask version: 2.8.0 and 2.16.0
- Python version: 3.8
- Operating System: tested macOS and Ubuntu
- Install method (conda, pip, source): conda

**Comment by jrdzha** [comment]
#5423 
Seems like which columns should be retained after groupby was changed? But maybe the metadata is not being updated?

**Comment by TomAugspurger** [comment]
@jrdzha you're saying you bisected this to #5423?

**Comment by jrdzha** [comment]
@TomAugspurger I'm not sure what "bisected" means, but I narrowed it down to this change that broke groupby + median for me. For some reason, the lazy Dask dataframe expects less columns than is produced by the actual groupby + median, causing the metadata do be wrong.

**Comment by TomAugspurger** [comment]
And if you manually provide the correct metadata, does the compute succeed?

**Comment by jrdzha** [comment]
Yes adding meta fixes this:

```python
df = df.groupby('marketplace').apply(pd.DataFrame.median, meta=[('customer_id', 'float'), ('product_parent', 'float'), ('star_rating', 'float'), ('helpful_votes', 'float'), ('total_votes', 'float'), ('year', 'float')])
```

My point is just that the predicted meta from Dask differs from the generated columns - the additional columns was added deliberately but the expected meta wasn't updated.

**Comment by TomAugspurger** [comment]
Can you look into why the meta that Dask get differs? Typically we call the user's function (DataFrame.median in this case) on an empty DataFrame with the same cols & dtypes. Does pandas fail for an empty dataframe or something?

**Comment by jrdzha** [comment]
I'm not sure what you mean by running median on an empty dataframe.. I ran this on an an empty pandas dataframe and got the following output:

```python
marketplace         NaN
customer_id         NaN
review_id           NaN
product_id          NaN
product_parent      NaN
product_title       NaN
star_rating         NaN
helpful_votes       NaN
total_votes         NaN
vine                NaN
verified_purchase   NaN
review_headline     NaN
review_body         NaN
review_date         NaN
year                NaN
dtype: float64
```

**Comment by TomAugspurger** [comment]
@jrdzha I think everything is working as expected here.

Dask applys the function on some dummy data to determine the result metadata (columsn, dtypes). See https://docs.dask.org/en/latest/dataframe-design.html#metadata. This typically works well, but fails when the pandas result depends on the values, rather than the metadata.

DataFrame.median apparently depends on the values. For object-dtype columns, pandas attempts to call `median` on the values, but raises if that operation fails. Your `customer_id`, `product_parent happens to be numeric-like despite being object dtype, so they end up in the output. But this isn't generally true of `object` dtype columns. I opened https://github.com/pandas-dev/pandas/issues/34671 on pandas, since this looks a little fishy.

For now, I'd recommend following the advice of the warning and being explicit about your metadata.
