### ISSUE TITLE
Array.__getitem__ should consider `array.chunk-size` for concrete indexers?

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#6270]
Reported in https://github.com/pydata/xarray/issues/4112, where xarray calling `Array.__getitem__` resulted in an unbalanced Array.

```python
import dask.array

arr = dask.array.from_array([0, 1, 2, 3], chunks=(1,))
print(arr.chunks)  # ((1, 1, 1, 1),)
# align calls reindex which indexes with something like this
indexer = [0, 1, 2, 3, ] + [-1,] * 111
print(arr[indexer].chunks)  # ((1, 1, 1, 112),)
```

That last chunk is large, since all of the `-1`s are in the same input chunk.

To be explicit, the user could chunk the `indexer`:

```
# maybe something like this is a solution
lazy_indexer = dask.array.from_array(indexer, chunks=arr.chunks[0][0], name="idx")
print(arr[lazy_indexer].chunks) # ((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),)
```

If the indexer isn't `chunked`, perhaps dask could examine the input array and indexer and chunk the indexer if we detect that the output chunksize would exceed `dask.config.get('array.chunk-size')`?

**Comment by shoyer** [comment]
> If the indexer isn't `chunked`, perhaps dask could examine the input array and indexer and chunk the indexer if we detect that the output chunksize would exceed `dask.config.get('array.chunk-size')`?

I think this strategy could work well for chunking `arr[indexer]` if any chunks would exceed some maximum chunk sizes.

However, I wouldn't implement this via chunking `indexer`. This removes information about which source chunks different parts of the indexer refer to, which makes indexing require a quadratic number of tasks.
