### ISSUE TITLE
Resample fails on different rules

### ISSUE THREAD

**Issue by abduhbm** [dask/dask#6271]
**What happened**:
`resample` raises `NotImplementedError` error for rules that don't evenly divide a day.  

**What you expected to happen**:
Different frequency rules should be allowed for time series resampling. 

**Minimal Complete Verifiable Example**:

```python
p = 100
index = pd.date_range(start="2012-01-02", periods=p, freq="H")
df = pd.DataFrame({"p": np.random.random(p)}, index=index)
ddf = dd.from_pandas(df, npartitions=5)
result = ddf.resample("2D").count().compute()
--------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/workplaces/dask-env/dask/dask/dataframe/tseries/resample.py in __init__(self, obj, rule, **kwargs)
    132                 "Resampling frequency %s that does"
    133                 " not evenly divide a day is not "
--> 134                 "implemented" % rule
    135             )
    136         self._rule = rule

NotImplementedError: Resampling frequency <2 * Days> that does not evenly divide a day is not implemented
```

**Anything else we need to know?**:
I got a correct resampling for the example above after removing the check on:
https://github.com/dask/dask/blob/79836fe4a52c9cf0e1eb32525792ad6bfed1c62b/dask/dataframe/tseries/resample.py#L130

Also for test:
https://github.com/dask/dask/blob/79836fe4a52c9cf0e1eb32525792ad6bfed1c62b/dask/dataframe/tseries/tests/test_resample.py#L131

```python
expected = s.resample('57T').mean()
expected
```
```
2012-01-02 00:00:00    28
2012-01-02 00:57:00    78
Freq: 57T, dtype: int64
```

```python
ds = dd.from_pandas(s, npartitions=5)
result = ds.resample('57T').mean().compute()
result
```
```
2012-01-02 00:00:00    28
2012-01-02 00:57:00    78
Freq: 57T, dtype: int64
```
I can attempt a PR to remove raising this error, if my assumption here is correct. 

**Environment**:

- Dask version: 2.17.2
- Python version: 3.7.6
- Operating System: MacOS 10.15
- Install method (conda, pip, source): source

**Comment by jsignell** [comment]
Thanks for raising this issue!  I think the original issue that brought it about was this one: https://github.com/dask/dask/issues/726, but that is now no longer an issue because we reindex to the desired timestep anyways. 

The PR would involve removing the error, and then writing a few tests to make sure that things work properly. Ideally, those tests should have gaps in the index. If you'd like to work on it you are more than welcome.
