### ISSUE TITLE
read_parquet with filters and arrow engine returns index in the columns

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#6277]
**What happened**:

When using `dd.read_parquet` with `filters`, the original index ends up in the columns

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask.datasets
import shutil

N = 1_000
P = 4
b = np.arange(P).repeat(N // P)

df = pd.DataFrame({
    "A": np.random.random(size=N),
    "B": pd.Categorical(b)
})
ddf = dd.from_pandas(df, P)

shutil.rmtree("parquet-filters.parquet", ignore_errors=True)
ddf.to_parquet("parquet-filters.parquet", partition_on="B", engine="pyarrow")

dd.read_parquet("parquet-filters.parquet", engine="pyarrow", filters=[[("B", "=", 1)]]).compute()
```

```python
Out[1]:
            A  index  B
0    0.410034    250  1
1    0.313085    251  1
2    0.848964    252  1
3    0.910770    253  1
4    0.922110    254  1
..        ...    ... ..
245  0.028301    495  1
246  0.392158    496  1
247  0.759204    497  1
248  0.122554    498  1
249  0.339143    499  1

[250 rows x 3 columns]
```

**Anything else we need to know?**:

Haven't debugged yet, but for the fastparquet engine the index is in the index, but the outupt is not filtered

```python
   ...: ddf.to_parquet("parquet-filters.parquet", partition_on="B", engine="fastparquet")
   ...:
   ...: dd.read_parquet("parquet-filters.parquet", engine="fastparquet", filters=[[("B", "=", 1)]]).compute()

              A  B
index
0      0.304616  0
1      0.626666  0
2      0.986920  0
3      0.585114  0
4      0.663830  0
...         ... ..
995    0.999620  3
996    0.223592  3
997    0.796024  3
998    0.063832  3
999    0.621195  3

[1000 rows x 2 columns]
```

**Environment**:

- Dask version: master
- Python version: 3.7

**Comment by TomAugspurger** [comment]
cc @dask/io :)

**Comment by TomAugspurger** [comment]
A couple other notes:

1. Why is the column called `index`, when the original index didn't have a name? Is that expected?
2. If I set `df.index.name = 'myindex` before writing, and manually specify `index='myindex'`, things are correct for pyarrow. But `index=None` doesn't auto-detect, which narrows it to `PyArrowEngine.read_metadata`.

**Comment by martindurant** [comment]
The fastparquet version does work, but with this syntax:
```
dd.read_parquet("parquet-filters.parquet", engine="fastparquet", filters=[("B", "==", 1)]).compute()
```
(no double list, but double equals)

**Comment by TomAugspurger** [comment]
Thanks. Do you know if there's a standard for which expressions should be allowed there?

**Comment by martindurant** [comment]
fastparquet did it first, so it must be right :) https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.ParquetFile.to_pandas

**Comment by martindurant** [comment]
> Why is the column called index

This is a default workaround, since the column in parquet cannot have no name. However, the original "None" should have been saved in the global pandas metadata.

**Comment by rjzamora** [comment]
Thanks for raising @TomAugspurger.  Martin is absolutely correct about the reason for the `"index"` name.  I'm not sure why the index is not being detected, but I will investigate a bit

**Comment by rjzamora** [comment]
The problem is likely in the `_write_partitioned` workaround to ARROW-8244. @jsignell  pointed out [here](https://github.com/dask/dask/issues/5873#issuecomment-636107106) that we can likely go back to using pyarrow's `write_to_dataset`.  I will try to fix the issue and work in `write_to_dataset` for newer `pyarrow` versions.

**Comment by TomAugspurger** [comment]
@rjzamora did you see https://issues.apache.org/jira/browse/ARROW-7782?

**Comment by rjzamora** [comment]
> did you see https://issues.apache.org/jira/browse/ARROW-7782? Might be relevant.

Nope - Seems like the same bug we have since the logic is mostly copied :)

**Comment by martindurant** [comment]
@rjzamora : OK to close?

**Comment by rjzamora** [comment]
> @rjzamora : OK to close?

Yes  We should probably close for now.  However, it is worth mentioning that there are a two minor points that have not been addressed yet:

- There is a slightly different filter syntax expected by the different engines, and I think this could be documented a bit better
- We are still not using the pyrrow `write_to_dataset` implementation, and we may be able to simplify the dask code by using the improved version

**Comment by martindurant** [comment]
Let's make those new issues. The former should be simple enough that we can accept either form for either backend, I imagine.
