### ISSUE TITLE
Joins with index-only dataframes return duplicate elements

### ISSUE THREAD

**Issue by velezsarain** [dask/dask#6281]
**What happened**: Joining dask dataframes with index-only dataframes (no columns) returns incorrect results, with rows being duplicated. The amount of duplicate rows depend on the number of partitions of the original datafame.

**What you expected to happen**: The join operation should work on index-only dataframes as it does with non-empty ones.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as ddf
import pandas as pd

first_index = pd.Index([1, 2, 3, 4, 5])
second_index =pd.Index([2, 3, 4])

df = pd.DataFrame(index=first_index)
df['A'] = 1
original = ddf.from_pandas(df, npartitions=1)

not_empty_df = pd.DataFrame(index=second_index)
not_empty_df['B'] = -1

empty_df = pd.DataFrame(index=second_index)

join1 = original.join(not_empty_df, how='left')
join2 = original.join(empty_df, how='left')
```
See that join2 has duplicate rows.

**Anything else we need to know?**: I am doing joins with these dataframes because dask currently does not support dropping rows with the drop operation. I have a list of index values I have to drop from my dataframes, I chose to use joins to achieve this.

**Environment**:

- Dask version: 2.15.0
- Python version: 3.6.9
- Operating System: Ubuntu 18.04.4 LTS
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
I got a pandas error with that example, it seems the issue is with the assignment to `not_empty_df`. Did you perhaps mean to use `first_index`:

```python
not_empty_df = pd.DataFrame({'B': [-1, -1, -1, -1, -1]}, index=first_index)
```

With that change, things work as expected.

**Comment by velezsarain** [comment]
@jsignell I did copy copy over the wrong code before, I modified it once before, I just edited it again to make the issue more legible.

Notice that `not_empty_df `and `empty_df ` have the same index but the joins return different amount of elements, this happens for all join types, not only inner.

**Comment by jsignell** [comment]
Thanks for updating. That example works as I expect it to on dask master:

![image](https://user-images.githubusercontent.com/4806877/83646949-52b2c300-a582-11ea-96a3-892f1bad05da.png)

Are you seeing something different, or is this not what you expected?

**Comment by jsignell** [comment]
Here it is with `"inner"`:

![image](https://user-images.githubusercontent.com/4806877/83647209-a8876b00-a582-11ea-9fda-d7b4d7e5a1d1.png)

**Comment by velezsarain** [comment]
I am seeing different results in version 2.15, I upgraded to 2.17 and the issue is gone. It seems to me this wasn't reported before but was fixed anyway in the latest patches.

Closing since this bug no longer occurs in 2.17.
