### ISSUE TITLE
SeriesGroupBy.nunique not showing up in the docs

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6283]
https://docs.dask.org/en/latest/dataframe-api.html

I can't seem to click on it either.

![image](https://user-images.githubusercontent.com/17162724/83649353-146ad300-a585-11ea-89fa-3cdc53221bfe.png)

**Comment by jsignell** [comment]
Thanks! It looks like there is no docstring for that method. I am opening a PR now.
