### ISSUE TITLE
Add expanding_* functions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#630]
In #487 we added rolling operations.  It would be nice to add their cumulative counterparts.  This is likely to be similar in nature to rolling operations.  

I came across this need while trying to make a simple demo with random data.

**Comment by jcrist** [comment]
With cumulative methods in #636 in, the immediate need for this may be delayed. I have a first pass at this (done before #636 came in, should definitely be reworked to share methods with #636) up on my fork [here](https://github.com/jcrist/dask/tree/expanding). If anyone ever has a need for these this work can be restarted.

**Comment by mrocklin** [comment]
No one but myself seems to be asking for this.  Closing as low-priority.

**Comment by sfragosorodrig** [comment]
is it still possible to add this functionality?
