### ISSUE TITLE
Doc: Add more information on `split_out` argument used in DataFrameGroupBy methods

### ISSUE THREAD

**Issue by asmith26** [dask/dask#6307]
I ran into a memory problem when running `ddf.groupby(...).size()`. Coming across a similar [StackOverflow](https://stackoverflow.com/a/56200246/5179470) problem, using `ddf.groupby(...).size(split_out=NUM_PARTITIONS)` fixed my problem.

Searching the Dask doc for [split_out](https://docs.dask.org/en/latest/search.html?q=split_out&check_keywords=yes&area=default) doesn't yield much information about this argument, nor do the [DataFrameGroupBy methods in the API doc](https://docs.dask.org/en/latest/dataframe-api.html?highlight=split_out#groupby-operations) (I appreciate that most of these particular methods use the pandas doc).

[I'm unfamiliar with the `split_every` argument, but this also appears to be in a similar situation regarding documentation.]

Is it worth adding more information on these arguments? Where might the best place for this information be? My attempt at such documentation for `split_out` would be something like (I'm not actually sure my reasoning behind Dask defaults is correct?):
> By default Dask DataFrame groupby methods return an Dask DataFrame object with only 1 partition. This is to optimize performance, assuming the groupby reduction returns a object that is small enough that is able to fit into memory. If your returned object is larger than this, you can increase the number of output partitions using the `split_out` argument, e.g. `ddf.groupby("some_column").size(split_out=8)`.

**Comment by asmith26** [comment]
Thanks for the feedback @TomAugspurger. 

Can you point me to any examples using `derived_from`? Perhaps this is the cleanest way if it can be used so that the documentation for each groupby method includes the same API description as the `dask.dataframe.core.apply_concat_apply` you point out.

**Comment by TomAugspurger** [comment]
`derived_from` is used throughout `dask.array` and `dask.dataframe`. See `DataFrame.pipe` for example. Just to be clear though, this doesn't currently *insert* parameter descriptions anywhere currently. Updating it to do this might be somewhat difficult. It might be more feasible to have the docstrings include a reference to the prose section describing the parameters.

**Comment by asmith26** [comment]
Thanks for the clarification.

I've created https://github.com/dask/dask/pull/6318 in an attempt to automate the documentation creation for methods containing the `split_out` argument, guided by your ideas whilst not over-complicating things:
![image](https://user-images.githubusercontent.com/6988036/84553137-19f5b500-ad0b-11ea-9c6d-98651dfaf414.png)

Building the doc locally indicates it has generally worked as a expected:

![image](https://user-images.githubusercontent.com/6988036/84553177-3c87ce00-ad0b-11ea-849f-7eb546de7dc6.png)

Some of the generated API documentation have indentation misalignment that I couldn't understand why, hence I created this as a draft pull request (any feedback welcome :) ):

![image](https://user-images.githubusercontent.com/6988036/84553228-73f67a80-ad0b-11ea-80b4-8ba33436856c.png)

**Comment by asmith26** [comment]
Closed by #6318
