### ISSUE TITLE
CSV export with multiprocessing inserts additional lines

### ISSUE THREAD

**Issue by mgsdk** [dask/dask#6313]
**What happened**:
Exporting a dask dataframe to CSV when using the multiprocessing scheduler results in blank lines being inserted in the output between valid lines.

**What you expected to happen**:
No blank lines between valid data lines. Output identical to using the single-threaded and multi-threaded schedulers.

**Minimal Complete Verifiable Example**:

```python
import dask
import tempfile

import dask.dataframe as dd
import numpy as np
import pandas as pd

from filecmp import cmp
from pathlib import Path


def main():
    df = pd.DataFrame(np.random.random(1000000))
    
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)
        path_process = tmp_path / "process.csv"
        path_threads = tmp_path / "threads.csv"
        path_thread = tmp_path / "thread.csv"
        
        dask.config.set(scheduler="processes")
        ddf = dd.from_pandas(df, 1)
        dd.to_csv(ddf, filename=str(path_process), single_file=True)

        dask.config.set(scheduler="threads")
        ddf = dd.from_pandas(df, 1)
        dd.to_csv(ddf, filename=str(path_threads), single_file=True)

        dask.config.set(scheduler="single-threaded")
        ddf = dd.from_pandas(df, 1)
        dd.to_csv(ddf, filename=str(path_thread), single_file=True)
    
        print(f"Process and threads equal output: {cmp(path_process, path_threads)}")
        print(f"Threads and thread equal output: {cmp(path_threads, path_thread)}")
    
    return


if __name__ == '__main__':
    main()
```

**Anything else we need to know?**:
This happens with and without `single_file`, example uses `single_file` for easier demonstration. The added character appears to be an additional `\r` for each line on Windows at least.

**Environment**:

- Dask version: 2.18.1
- Python version: 3.7.3 64 bit, 3.8.2 64 bit
- Operating System: Windows 10
- Install method (conda, pip, source): pip

All installed packages in environment:
```
dask==2.18.1
fsspec==0.7.4
locket==0.2.0
numpy==1.18.5
pandas==1.0.4
partd==1.1.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
six==1.15.0
toolz==0.10.0
```

**Comment by TomAugspurger** [comment]
Thanks for the report. Locally (a Mac with Dask master) I see this output

```
Process and threads equal output: True
Threads and thread equal output: True
```

My initial guess is that the difference is due to us not handling line-endings correctly on windows. Are you interested in debugging?

Could you post the text output for a small dataframe like this?

```python
df = pd.DataFrame({"A": [1, 2, 3, 4]})

dask.config.set(scheduler="processes")
ddf = dd.from_pandas(df, 1)
dd.to_csv(ddf, filename='data.csv', single_file=True)
```

```
,A
0,1
1,2
2,3
3,4
```

**Comment by mgsdk** [comment]
Output from the snippet:
```
,A

0,1

1,2

2,3

3,4


```

Since the output doesn't translate too well in text, here is the hex dump of the file as well:
```
2C 41 0D 0D 0A 30 2C 31 0D 0D 0A 31 2C 32 0D 0D 0A 32 2C 33 0D 0D 0A 33 2C 34 0D 0D 0A
```

For reference, I have just run the code on a RPi 4 (32 bit Linux, Python 3.7.3), and the output there is as expected (no additional lines), and matches what you posted.

If you have any pointers as to where would be a good place to start looking I can attempt to look into it, but I don't have any knowledge of the internal construction/architecture of dask and sub-projects as is.

**Comment by mgsdk** [comment]
For what is is worth, some poking around yields me with the following difference between threads and processes being crucial for the output:

When the interpreter gets to [dataframe/io/csv.py:594](https://github.com/dask/dask/blob/master/dask/dataframe/io/csv.py#L594) the `fil` object (unrelated question, should this be named `file`?) has en empty string as the `newline` attribute when running under threads, but `None` when running under processes.
Manually setting it to an empty string in the debugger when running with the multiprocess scheduler yields the expected result. Alternatively, setting it to `None` in the threads scheduler during debugging yields the incorrect result.

**Comment by TomAugspurger** [comment]
Thanks for inspecting there. I wonder if we can reproduce this with just pandas? What's the output of the following?

```python
import pandas as pd
from dask.bytes import open_file
import concurrent.futures


df = pd.DataFrame({"A": [0, 1]})
options = dict(newline="")

file1 = open_file("data.csv", mode="w", **options)


with file1 as f:
    df.to_csv(f)



def f(x):
    print(x)
    file = open_file("data.csv", mode="a", **options)
    with file as f:
        df.to_csv(f, header=False)


with concurrent.futures.ProcessPoolExecutor() as pool:
    pool.map(f, [0])
```

**Comment by mgsdk** [comment]
The above snippet yields:
```
,A
0,0
1,1

```
Or `2C 41 0D 0A 30 2C 30 0D 0A 31 2C 31 0D 0A` as hex.

As a side note, running the snippet as the sole content of a file yields the following error multiple times:
```
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
in the main module:

    if __name__ == '__main__':
        freeze_support()
        ...

The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.
```

I assume this is unrelated to the issue at hand, you wanted to ensure I didn't fail to report anything.

**Comment by TomAugspurger** [comment]
Hmm thanks. I'm pretty stumped. Any further debugging you can do here would be very welcome.

**Comment by mgsdk** [comment]
With the additions in filesystem_spec, this should be solved with the next release. Thanks for the suggestions, they helped narrow down the issue, and sorry for the noise.

**Comment by TomAugspurger** [comment]
Thanks for following up.
