### ISSUE TITLE
Writing new dtypes (Int64, string) to parquet

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask#6319]
I would like to save the parquet using the new dtypes in pandas. This is not a problem when using pandas to save the parquet files:

```python
import pandas as pd
import numpy as np

test = {
    'a': [0, np.nan],
    'b': ['c', 'dedede']
}

df = pd.DataFrame(test).astype({'a': 'Int8', 'b': 'string'})
df.to_parquet('test.pqt')
df2 = pd.read_parquet('test.pqt')
assert (df2.dtypes == df.dtypes).all()
```

However, the dtypes are not preserved when loading this file with dask:

```python
import pandas as pd
import numpy as np
import dask.dataframe as dd

test = {
    'a': [0, np.nan],
    'b': ['c', 'dedede']
}

df = pd.DataFrame(test).astype({'a': 'Int8', 'b': 'string'})
df.to_parquet('test.pqt')
df2 = dd.read_parquet('test.pqt')
print(df2.dtypes)
assert (df2.dtypes == df.dtypes).all()
```
Side note: the above assertion will give `TypeError: data type not understood`, but that's a separate issue. The print message shows that the datatype is not preserved.

A related issue is https://github.com/dask/dask/issues/6243.

**Environment**:
- pandas version: 1.0.4
- Dask version: 2.18.1
- Python version: 3.7.6 | packaged by conda-forge
- Install method (conda, pip, source): conda

**Comment by SultanOrazbayev** [comment]
Also, the problem seems to be about the interaction with parquet file (even though pandas manages to get the correct dtypes somehow). For example, converting into dask dataframe gives the correct dtypes:
```python
import pandas as pd
import numpy as np
import dask.dataframe as dd

test = {
    'a': [0, np.nan],
    'b': ['c', 'dedede']
}

df = pd.DataFrame(test).astype({'a': 'Int8', 'b': 'string'})
ddf = dd.from_pandas(df, npartitions=2)
print(ddf.dtypes)
```

**Comment by SultanOrazbayev** [comment]
To some extent the problem can be resolved with:
```python
ddf.astype({'a': 'Int8', 'b': 'string'}).compute()
```
However, saving a dataframe with these new dtypes will result in an error:
```python
ddf.astype({'a': 'Int8', 'b': 'string'}).to_parquet('test2.pqt')
# returns: ValueError: Don't know how to convert data type: Int8
```

**Comment by TomAugspurger** [comment]
The original example works with `engine="pyarrow"`. https://github.com/dask/fastparquet/pull/483 is adding supporting for some of pandas' new dtypes in fastparquet, but I don't know what its status is.

**Comment by SultanOrazbayev** [comment]
This is great, setting `engine="pyarrow"` resolves the issue!
