### ISSUE TITLE
array.compute_chunk_sizes() returns chunks with numpy integers

### ISSUE THREAD

**Issue by pziarsolo** [dask/dask#6323]
I am not sure if this is a bug. If you run this code:
```python

import numpy
import dask.array

random_array = dask.array.from_array(numpy.random.randint(1, 10, size=1000000))
random_array = random_array[random_array > 5]   
random_array.compute_chunk_sizes()
type(random_array.chunks[0][0])
```
The generated chunks data type is numpy.int64. I don't know if this is intentional but it breaks dask.array_to_zarr because zarr tries to encode to json  and  it is not able to deal with numpy data types.

There is an issue in zarr with code to reproduce the error:

https://github.com/zarr-developers/zarr-python/issues/569

- Dask version: 2.18.1
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Thanks for the report. Probably not intentional. We can iterate over the `chunk__shape[s]` and get the `.item()` in https://github.com/dask/dask/blob/e7e3b735d4cfee04d44cf7054b122bec1569dd23/dask/array/core.py#L1153 I think.

Any interest in working on this @pziarsolo?

**Comment by pziarsolo** [comment]
> Thanks for the report. Probably not intentional. We can iterate over the `chunk__shape[s]` and get the `.item()` in
> 
> https://github.com/dask/dask/blob/e7e3b735d4cfee04d44cf7054b122bec1569dd23/dask/array/core.py#L1153
> I think.
> 
> Any interest in working on this @pziarsolo?

I have been looking at the code and I don't feel able to do it.:(

**Comment by TomAugspurger** [comment]
Thanks for taking a look. @gforsyth would you be able to?

**Comment by gforsyth** [comment]
I'll take a look, @TomAugspurger -- thanks for the ping.
