### ISSUE TITLE
s3fs - Errors regardless

### ISSUE THREAD

**Issue by DarkBlaez** [dask/dask#6325]
I am unable to get very far reading files from a local Minio server. This is the snippet

df = dd.read_csv('s3://datasets/somedata/example.csv',  storage_options={
        "aws_access_key_id":"admin",
        "aws_secret_access_key":"Safe4root123",
        "endpoint_url":"http://localhost:9000",
        "region_name":"us-east-1"})

df.head()

I keep getting this error. The scheduler and workers to have s3fs installed. does the scheduler need to be rebooted? I assume not since python can pull in modules on the fly.

I have tried many permutations of the "storage_options" including "key" and Dask specific, though I have not seen much documentation other than having to try the boto3 docs.

Please advise. Thanks
DB-

Error stack:
ModuleNotFoundError                       Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/fsspec/registry.py in get_filesystem_class(protocol)
    181         try:
--> 182             register_implementation(protocol, _import_class(bit["class"]))
    183         except ImportError as e:

/opt/conda/lib/python3.7/site-packages/fsspec/registry.py in _import_class(cls, minv)
    196 
--> 197     mod = importlib.import_module(mod)
    198     if minversion:

/opt/conda/lib/python3.7/importlib/__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

/opt/conda/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/conda/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
 in 
      4         "aws_secret_access_key":"Safe4root123",
      5         "endpoint_url":"http://10.10.10.60:9000",
----> 6         "region_name":"us-east-1"})
      7 
      8 df.head()

/opt/conda/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    576             storage_options=storage_options,
    577             include_path_column=include_path_column,
--> 578             **kwargs
    579         )
    580 

/opt/conda/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    403         compression=compression,
    404         include_path=include_path_column,
--> 405         **(storage_options or {})
    406     )
    407 

/opt/conda/lib/python3.7/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)
     91 
     92     """
---> 93     fs, fs_token, paths = get_fs_token_paths(urlpath, mode="rb", storage_options=kwargs)
     94 
     95     if len(paths) == 0:

/opt/conda/lib/python3.7/site-packages/fsspec/core.py in get_fs_token_paths(urlpath, mode, num, name_function, storage_options, protocol)
    516         protocols, path = split_protocol(urlpath)
    517         protocol = protocol or protocols
--> 518         cls = get_filesystem_class(protocol)
    519 
    520         options = cls._get_kwargs_from_urls(urlpath)

/opt/conda/lib/python3.7/site-packages/fsspec/registry.py in get_filesystem_class(protocol)
    182             register_implementation(protocol, _import_class(bit["class"]))
    183         except ImportError as e:
--> 184             raise ImportError(bit["err"]) from e
    185     cls = registry[protocol]
    186     if getattr(cls, "protocol", None) in ("abstract", None):

ImportError: Install s3fs to access S3

**Comment by TomAugspurger** [comment]
@DarkBlaez you should rotate your `aws_secret_access_key` key if that's your real one. That's a secret that shouldn't be shared.

---

The exception is saying that your environment doesn't have s3fs installed. You also need in on the client.

**Comment by DarkBlaez** [comment]
Actually it's not my real key. I am not using AWS for this I am using local Minio instance and change all the data before I posted. Yes the error referenced is the obvious one. I did install s3fs on the client which in this case is a remote Jupiter instance so that resolve this error thrown.

However, what should the "real" storage_options" keys be? I have seen a number of options here, most reference boto3 which I understand Dask sfs3 is wrapped. However, the lack of clear documentation is what has caused a number of online threads to assert this same issue.

Can someone enumerate the storage_options?

Thanks
DB

**Comment by DarkBlaez** [comment]
I think I figured it out:
df = dd.read_csv('s3://datasets/somedata/example.csv,  storage_options={
        "key":"admin",
        "secret":"Safe4root123",
         "client_kwargs":{'endpoint_url': 'http://localhost:9000'}})

However, I would like validation of the full storage_options within Dask since it became clear that even thought Dask is wrapping boto3, there are changes and I wonder what additional changes there was.

DB

**Comment by TomAugspurger** [comment]
> However, I would like validation of the full storage_options within Dask

`read_csv` is agnostic to the particular backend used, so that isn't possible. It's up to that backend to validate the kwargs.

For S3, those are documented at https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem.

**Comment by DarkBlaez** [comment]
Thanks so much
