### ISSUE TITLE
Add version label?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#633]
In the gitter chat @sinhrks suggested that we start tracking versions more robustly.  A cheap solution that he suggested was to label all PRs with a "next release" label, and then rename that label to the version number at the release.  We would then continue by making a new "next release" label for the next release.

Thoughts on this?  I'm quite open to it.  Historically I haven't used processes like this because they add some friction to development.  However, as more people come on to dask it's probably better to act a bit more maturely.  Do others have suggestions on processes that would meaningfully help development?

**Comment by cowlicks** [comment]
reference to the discussion here: https://gitter.im/blaze/dask?at=55d7d0349c8a343a5a1e9ab1

I would not be in favor of adding a third party version tracking framework like versioneer. Just due to the complexity.

**Comment by mrocklin** [comment]
I don't think he's talking about versioning the code.  I think he's talking about versioning the issues and pull requests.  See https://github.com/blaze/dask/issues?q=milestone%3A0.7.1

**Comment by cowlicks** [comment]
I don't have a real reason, other than I would probably forget sometimes.

**Comment by cpcloud** [comment]
FWIW versioneer is pretty much a set it and forget it kind of thing. There's a one time cost to setting it up but after that it requires virtually no maintenance. What you get out of it far outweighs the cost of the one time setup.

**Comment by sinhrks** [comment]
As labeling issues/PRs take not much time, I'm willing to do when we release, until we need more robust management like release note:)

We can discuss versioning separately.

**Comment by jcrist** [comment]
We have used versioneer for a while now, providing a brief changelog on release (https://github.com/dask/dask/blob/master/docs/source/changelog.rst), and tagging issues/PRs after a release seems to work fairly well for now. Closing.
