### ISSUE TITLE
DataFrame.map_partitions_with_index

### ISSUE THREAD

**Issue by ChuckHastings** [dask/dask#6334]
Spark supports an RDD feature:  mapPartitionsWithIndex.  Propose adding this feature to dask.

There are situations where it is useful for a function being applied to all elements of a partition to understand which partition it is running on.  The simplest use would be to compute some sort of global value that is a function of the data on a partition and the partition number.

DataFrame.map_partitions passes the function called the local data frame and then the user supplied arguments.

DataFrame.map_partitions_with_index would pass the function called the local data frame, a number between 0 and numpartitions-1, and then the user supplied arguments.

A simple example

```
import dask.dataframe
import pandas

ddf = dask.dataframe.from_pandas(pandas.DataFrame({'a': ['b', 'c', 'd', 'e']}), npartitions=2)
ddf.map_partitions_with_index(lambda df, i: df.a.apply(lambda r: r + "-" + str(i))).compute()
```

Expected output would be:
```
0    b-0
1    c-0
2    d-1
3    e-1
```

**Comment by TomAugspurger** [comment]
@ChuckHastings IIUC, this would be solved by https://github.com/dask/dask/issues/3707. Can you confirm that?

There's precedence for this in `Array.map_blocks`, where we have a `block_info` keyword.

**Comment by ChuckHastings** [comment]
Yes, the idea described in #3707 would solve this.

**Comment by TomAugspurger** [comment]
Thanks. I'll close this then. Post over there if you're interested in working on it. I started a branch at https://github.com/dask/dask/compare/master...TomAugspurger:map_partitions-info but haven't had time to really work on it.

**Comment by kumarprabhu1988** [comment]
> Thanks. I'll close this then. Post over there if you're interested in working on it. I started a branch at [master...TomAugspurger:map_partitions-info](https://github.com/dask/dask/compare/master...TomAugspurger:map_partitions-info) but haven't had time to really work on it.

Hi @TomAugspurger . I forked off your branch and made a few changes and I think I have a working implementation. Would you prefer if I pushed to your branch or created a separate PR?

**Comment by TomAugspurger** [comment]
A separate PR sounds good, thanks.

**Comment by TomAugspurger** [comment]
FYI, there's also https://github.com/dask/dask/pull/6360, which is maybe stalled.

**Comment by kumarprabhu1988** [comment]
> FYI, there's also #6360, which is maybe stalled.

I saw this draft as well. I think this approach doesn't directly change the graph, but map_blocks implementation does and is similar to your branch.
