### ISSUE TITLE
Scheduler stuck in computation loop

### ISSUE THREAD

**Issue by willsthompson** [dask/dask#6338]
**What happened**: After creating a local cluster from Jupyter Notebook and executing several operations that I do not expect to be computed, the scheduler loads up workers with tasks. Upon completion, the tasks are reloaded and recomputed. This happens repeatedly, until I interrupt the notebook kernel and call `client.shutdown()`. 

Repeating the same operations in the same notebook (with a new cluster at the same scheduler port) does not trigger the same behavior. I see the deferred/estimated results in the notebook, as expected, and the scheduler doesn't start any worker tasks.

**What you expected to happen**: Work is not computed unless explicitly invoked/scheduled.

**Minimal Complete Verifiable Example**:

```python
#%%
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()
client = Client(cluster)
client

#%%
import pandas as pd
import dask.dataframe as dd
df_large = dd.read_parquet('/some_data/') # ~50GB across ~750 parquet files
df_large.index = df_large.index.astype('int32')
df_large
```

**Anything else we need to know?**:

I'm running Notebooks in PyCharm.

**Environment**:

- Dask version: 2.19.0
- Python version: 3.7.7
- Operating System: macOS 10.15.5
- Install method (conda, pip, source): pip
- Jupyter version: 1.0.0
    - jupyter-client: 6.1.3
    - jupyter-console: 6.1.0
    - jupyter-core: 4.6.3

<img width="1498" alt="Screen Shot 2020-06-22 at 12 04 16 PM" src="https://user-images.githubusercontent.com/1315884/85317447-032a2d80-b484-11ea-86fb-489feecaae50.png">

**Comment by gforsyth** [comment]
Hey @willsthompson -- I'm having trouble reproducing this -- can you see if you have the same issue when you first create a sample dataset (otherwise it's hard to make sure we're on the same page).

I've done this:

```
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()
client = Client(cluster)
client

#%%
import pandas as pd
import dask.dataframe as dd

df = dd.demo.make_timeseries()

df.to_parquet("sample")

client.restart()  # cycle the client to drop data and restart workers
```

then done
```
df = dd.read_parquet("sample")
df.index = df.index.astype("int32")

df
```

and no computation occurs until I explicitly call `compute`

Can you try that out on your end and see if the same issue occurs?

**Comment by willsthompson** [comment]
Yes, with a couple differences:
1. I can reproduce this, but seems like only with a fresh kernel. If I shut down the current server, and execute the same two notebook cells above from the MVE (replacing my data path with the location of the parquet files generated by `dd.demo.make_timeseries()`) in sequence, it does the same thing.
2. It looks like I was wrong to assume the loop was infinite. Using the timeseries sample data, it happens a lot more quickly and looks like repeats several times, then stops. I never waited long enough to find out using my data. Nearly all the time spent is on `iloc-read-parquet-len-chunk`.

At this point, I can re-run the code in the second cell and reproduce the behavior. But also if I run *anything* in another cell - even `print('test')` - it reproduces the behavior. I'm pretty new to Dask, so I'm not sure what would be most helpful here, but just guessing...

````
client.call_stack()
{}
````

````
client.get_scheduler_logs()
(('INFO', 'distributed.scheduler - INFO - Clear task state'),
 ('INFO',
  'distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:55641'),
 ('INFO',
  'distributed.scheduler - INFO -   dashboard at:            127.0.0.1:8787'),
 ('INFO',
  "distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:55648', name: 1, memory: 0, processing: 0>"),
 ('INFO',
  'distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55648'),
 ('INFO',
  "distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:55647', name: 3, memory: 0, processing: 0>"),
 ('INFO',
  'distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55647'),
 ('INFO',
  "distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:55653', name: 2, memory: 0, processing: 0>"),
 ('INFO',
  'distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55653'),
 ('INFO',
  "distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:55656', name: 0, memory: 0, processing: 0>"),
 ('INFO',
  'distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55656'),
 ('INFO',
  'distributed.scheduler - INFO - Receive client connection: Client-768affc6-b4cb-11ea-954b-dca9046f1767'))
````

<img width="1231" alt="Screen Shot 2020-06-22 at 3 35 28 PM" src="https://user-images.githubusercontent.com/1315884/85335153-206df480-b4a2-11ea-9342-62331571646f.png">

**Comment by TomAugspurger** [comment]
Does this only occur when you're running the notebook from PyCharm?

**Comment by willsthompson** [comment]
Ugh, yes, appears to be so. This is odd. PyCharm runs the same Jupyter server (it just calls `jupyter notebook --no-browser` from my venv), and then runs its UI against it. If I run everything from PyCharm, including auto-starting the server and executing the first cell from its UI, then switch to the Jupyter server HTML UI and run the second cell, this issue does not appear. Then If I run the second cell from PyCharm, it doesn't occur. It's only when started and both are run from PyCharm. Is there any hope of catching what's going wrong here?

**Comment by TomAugspurger** [comment]
I'm not sure. I'm not familiar with how PyCharm runs notebooks.

**Comment by willsthompson** [comment]
Well, thanks for following me down this rabbit hole, guys. If I find anything out from JetBrains, I'll update the issue.

**Comment by willsthompson** [comment]
Got it. By default, PyCharm will query for information about variables used in Notebooks, forcing evaluation. See https://youtrack.jetbrains.com/issue/PY-40948

**Comment by gforsyth** [comment]
This is very good to know.  Thanks for reporting back @willsthompson !
