### ISSUE TITLE
Regression in index when using `fastparquet`

### ISSUE THREAD

**Issue by gforsyth** [dask/dask#6348]
**What happened**:
on `2.19.0+6.g7138f470f`

```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'t': ['2017-02-03', '2017-03-03', '2017-01-01']})
df['t'] = pd.to_datetime(df.t, utc=True).dt.tz_convert('US/Eastern')
print(df)
print(df.index)
df.to_parquet('test.parquet', engine='fastparquet')
df = dd.read_parquet('test.parquet', engine='fastparquet').compute()
print(df)
print(df.index)
                          t
0 2017-02-02 19:00:00-05:00
1 2017-03-02 19:00:00-05:00
2 2016-12-31 19:00:00-05:00
RangeIndex(start=0, stop=3, step=1)
                                      t
7.342211e-309 2017-02-02 19:00:00-05:00
7.354163e-309 2017-03-02 19:00:00-05:00
7.328124e-309 2016-12-31 19:00:00-05:00
Float64Index([7.342210749717597e-309, 7.35416318582179e-309,
              7.32812395002337e-309],
             dtype='float64')
```

**What you expected to happen**:
on `2.19.0`

```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'t': ['2017-02-03', '2017-03-03', '2017-01-01']})
df['t'] = pd.to_datetime(df.t, utc=True).dt.tz_convert('US/Eastern')
print(df)
print(df.index)
df.to_parquet('test.parquet', engine='fastparquet')
df = dd.read_parquet('test.parquet', engine='fastparquet').compute()
print(df)
print(df.index)
                          t
0 2017-02-02 19:00:00-05:00
1 2017-03-02 19:00:00-05:00
2 2016-12-31 19:00:00-05:00
RangeIndex(start=0, stop=3, step=1)
                          t
0 2017-02-02 19:00:00-05:00
1 2017-03-02 19:00:00-05:00
2 2016-12-31 19:00:00-05:00
RangeIndex(start=0, stop=3, step=1)
```

**Environment**:

- Dask version: 2.19.0+6.g7138f470f
- Python version: 3.8.2 conda-forge
- Operating System: OSX
- Install method (conda, pip, source): source

**Comment by gforsyth** [comment]
@rjzamora looks like this started with #6282 (which is a little odd, since this only impacts `fastparquet` and not `pyarrow`)

**Comment by rjzamora** [comment]
Oops - Sorry about that. I'll try to track down the problem and add test coverage for this.
Looks like we are failing to round-trip a RangIndex on the fastparquet side.

Another repro:
```python
import pandas as pd
import dask.dataframe as dd

df0 = pd.DataFrame(
    {'t': [1, 2, 3]},
    index=pd.RangeIndex(start=1, stop=4),
=)
df.to_parquet('test.parquet', engine='fastparquet')
df1 = dd.read_parquet('test.parquet', engine='fastparquet').compute()

dd.assert_eq(df0.index, df1.index)
```

**Comment by rjzamora** [comment]
Actually, it looks like we never supported round-tripping a `RangeIndex` with fastparquet. The reason [this](https://github.com/dask/dask/issues/6348#issue-646369692) example worked with 2.19.0 was that we didn't even try to preserve the index, and the default`RangeIndex` just happened to be correct.

When you try to round-trip a non-default `RangeIndex`, both versions fail.  @martindurant - Does fastparquet allow us to read  in a `RangeIndex` like so: `pf.read_row_group_file(rg_piece, columns, categories, index=index)` (where `index` specifies a `RangeIndex` column)?  If not, we may need to use the "pandas metadata" to accomplish this.
