### ISSUE TITLE
It's not possible to handle non-picklable objects

### ISSUE THREAD

**Issue by tiagofrepereira2012** [dask/dask#6353]
Hi, 
**What happened**:

I'm building a dask-graph with methods from classes that are not picklable.
To properly handle the serialization, every class implements `__getstate__` and `__setstate__`. 
However, this seems not sufficient and my code keeps crashing no matter where `single-threaded` or via dask-distributed (using `SGECluster` via `dask-jobqueue`).
It seems that `__getstate__` is not a protected method, and since this changes the state of the object, the code has the potential to crash at any time.
The code below shows a simple example of class where the state of the object is changed during the `__getstate__`.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.bag

class ClassThatDoesSomething:

    def __init__(self):
        self.state_variable_not_picklable = 0

    def operationA(self, samples):
        self.state_variable_not_picklable

    def __setstate__(self, d):
        # Handling unpicklable objects
        d["state_variable_not_picklable"] = 0
        self.__dict__ = d

    def __getstate__(self):
        d = self.__dict__        
        d.pop("state_variable_not_picklable") if "state_variable_not_picklable" in d else None
        return d

npartitions = 10
db_a = dask.bag.from_sequence(list(range(110)), npartitions=npartitions)
something = ClassThatDoesSomething()

# Making the graph
db_a = db_a.map_partitions(something.operationA)
all_a = dask.delayed(list)(db_a)
result = db_a.compute(scheduler="single-threaded")
```

**Environment**:

- Dask version: 
```
dask                      2.19.0                     py_0    defaults
dask-core                 2.19.0                     py_0    defaults
distributed               2.19.0                   py37_0    defaults
```

- Python version: 3.7
- Operating System: Debian Stretch
- Install method (conda, pip, source): conda, defaults channel

Thanks for any insight

Cheers

**Comment by mrocklin** [comment]
It looks like you're mutating your object, `something` by deleting the not picklable state variable.  After that the same object in the same process won't have that attribute.  Your minimal example works fine if you don't delete this attribute, but instead return a modified version of the dictionary.

In other words, this works

```python
import dask
import dask.bag

class ClassThatDoesSomething:

    def __init__(self):
        self.state_variable_not_picklable = 0

    def operationA(self, samples):
        self.state_variable_not_picklable

    def __setstate__(self, d):
        # Handling unpicklable objects
        d["state_variable_not_picklable"] = 0
        self.__dict__ = d

    def __getstate__(self):
        d = self.__dict__.copy()  # <---- I added the copy here
        d.pop("state_variable_not_picklable") if "state_variable_not_picklable" in d else None
        return d

npartitions = 10
db_a = dask.bag.from_sequence(list(range(110)), npartitions=npartitions)
something = ClassThatDoesSomething()

# Making the graph
db_a = db_a.map_partitions(something.operationA)
all_a = dask.delayed(list)(db_a)
result = db_a.compute(scheduler="single-threaded")
```

**Comment by tiagofrepereira2012** [comment]
Yes, you are right.
It's not a good idea to touch the state of the object during serialization.

Thanks for the feedback, I'll close this issue
