### ISSUE TITLE
support meta in apply_gufunc

### ISSUE THREAD

**Issue by dcherian** [dask/dask#6358]
**What happened**:

`dask.array.apply_ufunc` does not accept a `meta` kwarg.

**Motivation**

There is a PR (https://github.com/pydata/xarray/pull/4060) updating `xarray.apply_ufunc` to use `dask.array.apply_gufunc`. Currently `apply_ufunc` used `blockwise` which accepted a `meta` kwarg but now we see that `apply_gufunc` does not accept one.

I don't have an example that fails with the current code. But it seems like a good idea to let the user specify `meta` in case the automated inference in the following lines doesn't work
https://github.com/dask/dask/blob/ad5006fc70a256ceb389a3e42b6f303c61c1721d/dask/array/gufunc.py#L420-L440

**Comment by kmuehlbauer** [comment]
IIUC @shoyer's [comment in 4060](https://github.com/pydata/xarray/pull/4060#issuecomment-634774468) `meta` can still be forwarded into `apply_gufunc` via  `**kwargs`. And this is what is done in the current state of https://github.com/pydata/xarray/pull/4060. 

But looking at the above code, this would break if the except-clause will be reached (`meta` inside `**kwargs`).

**Comment by TomAugspurger** [comment]
Agreed, accepting `meta` here makes since. Is anyone interested in working on this?
