### ISSUE TITLE
Scaling dask-ssh

### ISSUE THREAD

**Issue by vinhdiesal** [dask/dask#6361]
I want to get scale more workers in my `dask SSH cluster`, but it keeps erroring out. 

When I execute the following, I only get 4 workers: 
```
from dask.distributed import Client, SSHCluster
cluster = SSHCluster(
        ["localhost", "192.168.1.119", "192.168.1.191"],
        connect_options={"known_hosts": None,"username": "vinhdiesal"},
        worker_options={"nthreads": 40},
        scheduler_options={"port": 0, "dashboard_address": ":8797"},
        worker_module='dask_cuda.dask_cuda_worker')
```
```
dask
+---------------------------+---------+
|                           | version |
+---------------------------+---------+
| client                    | 2.11.0  |
| scheduler                 | 2.11.0  |
| tcp://192.168.1.119:41593 | 2.11.0  |
| tcp://192.168.1.119:43467 | 2.11.0  |
| tcp://192.168.1.191:39413 | 2.17.2  |
| tcp://192.168.1.191:43905 | 2.17.2  |
+---------------------------+---------+
```
According to the dask website, you can use the `cluster.scale(10)` or `cluster.adapt(minimum=0, maximum=100)`
but it always results in only 4 workers. 
How can I get more workers?

**Comment by gforsyth** [comment]
`dask_cuda` will generally (always?) spin up one worker per discrete GPU.  How many GPUs are available in your cluster of 3 machines?

**Comment by quasiben** [comment]
As @gforsyth said, dask_cuda will create one worker per GPU.  Unfortunately, you can't scale with ssh and dask-cuda as you are probably already occupying all of the GPUs.  With SLURM/dask-joqueue/kubernetes scaling is possible because the cluster will most likely have more nodes than are running for your job

**Comment by vinhdiesal** [comment]
Thanks, I do have 4 GPUs and got better performance when I increased the amount of threads. 
Just another quick one before I close, is there a way to create a combination of dask_cuda and dask_works (cpu) so I can increase work force in the SSH cluster? 
In my K8s cluster, I was able to get 20 dask-workers, but had issues with dask-cuda-worker so that's why I'm switching SSH also to take advantage of the latest nvidia drivers and cuda package. If I can combine the scale with the GPUs it will be great.

**Comment by quasiben** [comment]
I don't personally have a lot of experience here.  I think others have used [worker resources](https://distributed.dask.org/en/latest/resources.html#resources-are-applied-separately-to-each-worker-process) to define particular workflows which need to run on a GPU.  I suspect these are highly tuned and not generally used for dataframe operations if that is what you are doing.  If you are having issues with k8s and dask-cuda I would recommend filing an issue and we can help.  Probably best to file on the dask-cuda repo

**Comment by vinhdiesal** [comment]
thank you for all your responses. I'm very happy with dask-cuda and I haven't scratched the surface. Keep up the good work.
