### ISSUE TITLE
Dask dataframe concat with interleave_partitions at True may clear divisions

### ISSUE THREAD

**Issue by msebbah** [dask/dask#6362]
When repartitioning on size after a concat with interleave_partitions at True, something goes south.

It happens for me on chunks of 1GB, anyway the following example reproduces my issue.

```python
df = dd.from_pandas(pd.DataFrame(range(20)), npartitions=4)
dd.concat([df, df], interleave_partitions=True).repartition(partition_size='160B').divisions
```
Returns:
(None, None, None, None, None)
Expected:
Something like (0, 5, 10, 15, 19) or (0, 4, 8, 12, 15, 19)

**Environment**:

- Dask version: 2.19
- Python version: 3.7.6
- Operating System: Ubuntu 18.04
- Install method: pip

**Comment by TomAugspurger** [comment]
Thanks for the report, this is unrealated to concat.

```python
In [4]: df = dd.from_pandas(pd.DataFrame(range(20)), npartitions=4)
   ...: df.repartition(partition_size="80B").divisions
Out[4]: (None, None, None, None, None, None, None, None, None, None, None, None, None)
```

Right now `_split_divisions` clears the divisions explicitly: https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/core.py#L6037. I'm not sure if that can be avoided. I think it would require redoing the partition quantiling to discover divisions. Are you interested in looking into this more @msebbah?

**Comment by msebbah** [comment]
Thanks for the reply

```
In [7]: df = dd.from_pandas(pd.DataFrame(range(20)), npartitions=4)                                 

In [8]: df.repartition(partition_size="1kB").divisions                                              
Out[8]: (0, 19)
```
With fewer partitions, divisions are not cleared, this is why I was confused.

Anyway, I'd be happy to help, let me check If I can spend time for that.

**Comment by jsignell** [comment]
@msebbah I think what you are seeing is the divisions are not cleared if the original `nparititons` is equal to or a multiple of the final `npartitions`. Since the current behavior is expected, I'll close this issue unless you are interested in looking into optionally setting divisions based on the new smaller partitions.
