### ISSUE TITLE
Index(['a', 'b'], dtype='object') instead of Index([], dtype='object') with set_index when empty categories in dataframe

### ISSUE THREAD

**Issue by odovad** [dask/dask#6364]
I ran into categories errors; it seems that a, b categories are created into the Dask Dataframes. 
It's done when using the set_index on a Dask Dataframe with empty categories columns. 
It does not happen when the pandas DataFrame is already indexed.
I was expecting the same Dask Dataframe with the two code samples.
Is there a reason for this ? 

a,b categories with this sample code :
```python
import pandas as pd
import numpy as np
import dask.dataframe as dd

df = pd.DataFrame({'i':[0,1], 'col1':[None, None], 'col2':[None, 'A']})
df=df.astype({'col1':'category',
              'col2':'category'})
df1 = dd.from_pandas(df, npartitions=2).set_index('i')
print('dask', df1['col1'].cat.categories)
print('compute', df1.compute()['col1'].cat.categories)
```
It prints : 
```python
dask Index(['a', 'b'], dtype='object')
compute Index([], dtype='object')
``` 
No a,b categories with this sample code :
```python
import pandas as pd
import numpy as np
import dask.dataframe as dd

df = pd.DataFrame({'i':[0,1], 'col1':[None, None], 'col2':[None, 'A']})
df=df.astype({'col1':'category',
              'col2':'category'})
df2 = dd.from_pandas(df.set_index('i'), npartitions=2)
print('dask', df2['col1'].cat.categories)
print('compute', df2.compute()['col1'].cat.categories)
```
It prints : 
```python
dask Index([], dtype='object')
compute Index([], dtype='object')
``` 

**Environment**:

- Dask version: 2.19
- Python version: 3.8.2
- Operating System: Ubuntu 18.04.3 LTS
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
>  Is there a reason for this ?

Nope, looks like a bug. Can you investigate a bit more in `set_index` to see what goes wrong? Most like we're inappropriately converting `UNKNOWN_CATEGORIES` to "known" categories with the data from `meta_nonempty`


```python
In [29]: dd.from_pandas(df,2 )._meta_nonempty
Out[29]:
   i col1 col2
0  1    a    A
1  1    b    A
```

**Comment by odovad** [comment]
I did not find exactly where it comes from.

The closest I've found : 

There is a really similar meta object with a, b : 
`dask/dataframe/core.py(5175)`
`meta = _emulate(func, *args, udf=True, **kwargs)`

And the object with a, b is returned when these lines are executed : 
`dataframe/shuffle.py`
`map_partitions(M.set_index, df, index, drop=drop, meta=meta)`

`dataframe/core.py(5248)map_partitions()`
new_dd_object(graph, name, meta, divisions)

`dataframe/core.py(6304)new_dd_object()`
get_parallel_type(meta)(dsk, name, meta, divisions)

Does it help ?

**Comment by TomAugspurger** [comment]
Possibly, I'm not sure. Do you intend to keep debugging this?

**Comment by odovad** [comment]
It seems that's the following lines (meta is 'no_default') : 

/opt/conda/lib/python3.8/site-packages/dask/dataframe/core.py(5174)

if meta is no_default:
5172            # Use non-normalized kwargs here, as we want the real values (not
5173            # delayed values)
5174 ->         meta = _emulate(func, *args, udf=True, **kwargs)

_emulate returns 

(Pdb) meta
  col1 col2
i          
1    a    A
2    b    A

Line 5190, make_meta takes the emulate metadata as input:
5190 ->     meta = make_meta(meta) 

It keeps ['a', 'b'] as categories for 'col1'.
