### ISSUE TITLE
persist() to disk (if ram is full)

### ISSUE THREAD

**Issue by manuels** [dask/dask#6366]
If I understand persist() correctly it loads a full dataset into ram. I am wondering what happens if the dataset does not fit into ram. It seems like dask is discarding some partitions and recomputes them later if needed. It would be great if dask would write these partitions to disk instead and reload them later if needed.
Do I understand the current implementation of persist() correctly and would such a "write-to-disk" behavior be possible?

**Comment by quasiben** [comment]
Persist will compute the task graph up to the point where it was called and keep the result on the cluster (as opposed to returning to the client).  It will not necessarily be the case that the result will be in memory (though most likely it will be).  Dask can spill data to disk which can be [configured in a number of ways](https://distributed.dask.org/en/latest/worker.html#memory-management).  Dask is designed to handle large than memory datasets, taking in what can be compute given resources/configuration and discarding data which is no longer need (intermediary results) 

I would recommend taking this conversation to stackoverflow --typically we use the issue tracker for bugs/features.

**Comment by manuels** [comment]
Thanks for clarifying that!
