### ISSUE TITLE
read_csv not returning values

### ISSUE THREAD

**Issue by konradbachusz** [dask/dask#6369]
I created and saved a dataframe in a local directory as a csv file. I can read this file with pandas but dask reads only the headings without values. Is there any parameter than needs to be used to make it work?

![pandas vs dask](https://user-images.githubusercontent.com/37801868/86454728-9599bf00-bd17-11ea-85fa-a5569cc5c007.PNG)

**Comment by TomAugspurger** [comment]
That's intentional: see https://docs.dask.org/en/latest/user-interfaces.html#laziness-and-computing and https://docs.dask.org/en/latest/dataframe.html.

You can view the first rows with `.head()` or `.compute()` to get the entire result.
