### ISSUE TITLE
DataFrame pickling test fails with latest cloudpickle when pickle5 is installed

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/dask#6374]
Created a test environment with `mamba create -n test-dask-cloudpickle python=3.7 dask pandas cloudpickle pytest pip` and installed dask master in it `pip install -e .`. 
With this environment, the `test_dataframe_picklable` passes fine. But when additionally also installing `pickle5`, you then get an error:

```
(test-dask-cloudpickle) $ pytest dask/dataframe/tests/test_dataframe.py::test_dataframe_picklable -v
===============================================================================================
platform linux -- Python 3.7.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/joris/miniconda3/envs/test-dask-cloudpickle/bin/python
cachedir: .pytest_cache
rootdir: /home/joris/scipy/repos/dask, inifile: setup.cfg
collected 1 item                                                                                                                                                                                                  

dask/dataframe/tests/test_dataframe.py::test_dataframe_picklable FAILED                                                                                                                                     [100%]

==================================================================================================== FAILURES =====================================================================================================
____________________________________________________________________________________________ test_dataframe_picklable _____________________________________________________________________________________________

    def test_dataframe_picklable():
        from pickle import loads, dumps
    
        cloudpickle = pytest.importorskip("cloudpickle")
        cp_dumps = cloudpickle.dumps
    
        d = _compat.makeTimeDataFrame()
        df = dd.from_pandas(d, npartitions=3)
        df = df + 2
    
        # dataframe
        df2 = loads(dumps(df))
        assert_eq(df, df2)
>       df2 = loads(cp_dumps(df))
E       ValueError: unsupported pickle protocol: 5

dask/dataframe/tests/test_dataframe.py:1623: ValueError

```

(originally catched by the pyarrow integration tests with dask -> https://issues.apache.org/jira/browse/ARROW-9353)

This started a few days ago with the latest release of cloudpickle, I suppose related to https://github.com/cloudpipe/cloudpickle/pull/370

**Comment by pierreglaser** [comment]
The reason why this test is failing is that `cp_dumps` relies on `pickle5` and thus uses `pickle` protocol 5 when dumping `df`. On the countrary, `loads` is the stdlib `pickle.loads` function, which, on `Python 3.7` does not implement `pickle` protocol 5 yet, hence the error. So `pickle` files generated using `cp_dumps` when `pickle5` is installed should/can only be read using `pickle5.loads`/`cloudpickle.loads`. This change was not avoidable to have `pickle5` support on `Python 3.6/7`.


Although this is a breaking change: 
- `pickle5` is only an optional dependency on `cloudpickle`
- Libraries such as `dask` are working alongside with `cloudpickle` to adapt to this change (dask/distributed#3849)
 
But I'd be glad to hear your concerns.

**Comment by jorisvandenbossche** [comment]
So it's "just" the test that would need to be updated, then? (to use cloudpickle's load when `cp_dumps` was used and when `pickle5` is installed)

(I am not sure what the rationale is to test cloudpickle dump + pickle load combo, and not cloudpickle dump + cloudpickle load. Is that combo a specific case that should be kept where possible?)

**Comment by jorisvandenbossche** [comment]
And thanks for the explanation @pierreglaser !

**Comment by pierreglaser** [comment]
> So it's "just" the test that would need to be updated, then? (to use cloudpickle's load when cp_dumps was used and when pickle5 is installed)

This should indeed fix the test.

> (I am not sure what the rationale is to test cloudpickle dump + pickle load combo, and not cloudpickle dump + cloudpickle load. Is that combo a specific case that should be kept where possible?)

`cloudpickle` explictly advertises that `cloudpickle`-generated files are compatibble with `pickle.load`, which is why this pattern (`pickle.loads(cloudpickle.dumps(obj))`) is often seen in the wild. Formally, this is not the case anymore [1], and this deserves at least a note in the README.

`cloudpickle.loads(cloudpickle.dumps(obj))` should always work, and this probably should promoted to the advertised solution.

[1] Although `cloudpickle` did not deviate from the `pickle` API. It simply uses `pickle5` as a drop-in replacement of `pickle`. This means that when `pickle5` is installed, `pickle5.loads(cloudpickle.dumps(obj))` still works.

**Comment by jakirkham** [comment]
Is the issue still present when using PR ( https://github.com/dask/distributed/pull/3849 )?

**Comment by jorisvandenbossche** [comment]
I don't think the test involves distributed? (see the snippet printed in the pytest output in the top post)

**Comment by quasiben** [comment]
Hmm, I tried with the env you gave and pickle5 but I didn't get any error:

```bash
  master  ❲c❳ test-dask-cloudpickle  ~/GitHub/dask                                                                                                                                                                                              07:38:32   quasiben@lola
❯ conda list pickle
# packages in environment at /home/quasiben/miniconda3/envs/test-dask-cloudpickle:
#
# Name                    Version                   Build  Channel
cloudpickle               1.4.1                      py_0    defaults
pickle5                   0.0.11           py37h8f50634_0    conda-forge
  master  ❲c❳ test-dask-cloudpickle  ~/GitHub/dask                                                                                                                                                                                              07:38:40   quasiben@lola
❯ pytest dask/dataframe/tests/test_dataframe.py::test_dataframe_picklable -v
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.7.7, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/quasiben/miniconda3/envs/test-dask-cloudpickle/bin/python
cachedir: .pytest_cache
rootdir: /home/quasiben/GitHub/dask, inifile: setup.cfg
collected 1 item

dask/dataframe/tests/test_dataframe.py::test_dataframe_picklable PASSED                                                                                                                                                                                                  [100%]

========================================================================================================================== slowest 10 test durations ===========================================================================================================================
0.14s call     dask/dataframe/tests/test_dataframe.py::test_dataframe_picklable

(0.00 durations hidden.  Use -vv to show these durations.)
============================================================================================================================== 1 passed in 0.82s ===============================================================================================================================
  master  ❲c❳ test-dask-cloudpickle  ~/GitHub/dask                                                                                                                                                                                              07:38:44   quasiben@lola
❯
```

**Comment by jorisvandenbossche** [comment]
@quasiben the cloudpickle version in your env is an older release from defaults (1.4.1, instead of 1.5.1), it seems

**Comment by quasiben** [comment]
d'oh.  Sorry @jorisvandenbossche .  With cloudpickle 1.5.0 I can reproduce the error

**Comment by quasiben** [comment]
Should we add statements like:

```python
if sys.version_info < (3, 8):
    try:
        import pickle5 as pickle
    except ImportError:
        import pickle
else:
    import pickle
```

As @jakirkham did in  dask/distributed#3849

**Comment by jakirkham** [comment]
> I don't think the test involves distributed? (see the snippet printed in the pytest output in the top post)

Sorry for misunderstanding (this is what I get for looking at my phone at night 😅).

I think what Pierre said [here]( https://github.com/dask/dask/issues/6374#issuecomment-655414111 ) should provide us a straightforward fix. Will try to take a look at getting something up today.

**Comment by jakirkham** [comment]
Looks like that is the only test that failed. Submitted PR ( https://github.com/dask/dask/pull/6379 ), which works locally. Waiting for CI to report back. Please take a look 🙂
