### ISSUE TITLE
Custom optimization functions are called twice, once without scheduler kwargs.

### ISSUE THREAD

**Issue by ClarkZinzow** [dask/dask#6381]
Custom optimization functions (those given as a scheduler `optimizations=[foo]` kwarg or set in the Dask config) are [being called twice](https://github.com/dask/dask/blob/149abe507a3988073a9acc9d5b8483f44c747f6b/dask/base.py#L223-L224): the first time without scheduler kwargs, the second time with scheduler kwargs.

```python
In [1]: import dask
   ...: import dask.array as da
   ...: import numpy as np

In [2]: def dummy_opt(dsk, keys, **kwargs):
   ...:     print(f"Called with kwargs: {kwargs}")
   ...:     return dsk

In [3]: da.from_array(np.array([1, 2])).compute(optimizations=[dummy_opt], dummy_kwarg="foo")
Called with kwargs: {}
Called with kwargs: {'dummy_kwarg': 'foo'}
Out[3]: array([1, 2])
```

This bug was introduced in [this large performance-oriented PR](https://github.com/dask/dask/pull/6137), and affects the following versions: 2.20.0, 2.19.0, 2.18.1, 2.18.0, 2.17.2, 2.17.1, 2.17.0, and 2.16.0.

**Comment by mrocklin** [comment]
Thank you for tracking this down @ClarkZinzow .  I appreciate it.  In principle the PR that you provided seems sensible to me, but I haven't done all of my homework on it. 

@galipremsagar @quasiben could I ask you all to take a look at the associated PR here?

**Comment by quasiben** [comment]
@mrocklin yeah, i can pick this up
