### ISSUE TITLE
Revisit gather_statistics in read_parquet

### ISSUE THREAD

**Issue by martindurant** [dask/dask#6389]
Loading metadata from parquet files in the client can be costly; parsing the statistics and looking for ordering can also be costly.

- We should limit when we load metadata at all, either from a global file, otherwise from the first data file
- If the pandas metadata says there is an index, or the user specifies an index, we need to parse the statistics for that column only; do not try to guess an index
- While parsing, we can know early that ordering won't work, so bail early

As stated, this implies that any filters will be applied at read time, so we *don't* proactively cut down on partitions, but some partitions might come back empty (but the work is done on the worker).

**Comment by martindurant** [comment]
@rjzamora , does this reflect the gist of what we decided?

**Comment by rjzamora** [comment]
Thanks for summarizing @martindurant !

This pretty much covers the metadata/filtering component of our discussion.  The one grey area is that we don't necessarily need the filtering to be applied at read time.  Rather, we would like to avoid applying filters on the client using python code in dask.  That is, I think we can/should still allow the `pyarrow.datset` API to filter out row-group fragments during dataset discovery.

**Comment by martindurant** [comment]
> That is, I think we can/should still allow the pyarrow.datset API to filter out row-group fragments during dataset discovery.

Yes, totally happy to pass a `filters=` when setting up the graph, but I don't think we want or have a way to transform `df[filter]` into such clauses and rewriting the graph via an optimisation - we'll just end up with some empty partitions instead. We currently only do this where we have an index with known "division" values from the statistics metadata.

Did I understand correctly?

(note the interesting example of https://github.com/holoviz/spatialpandas , which *does* apply limits on columns to rewrite the graph, specialised to lat/lon for datasets where the partitioning strategy is well known [example](https://nbviewer.jupyter.org/github/holoviz/spatialpandas/blob/master/examples/Overview.ipynb#Pack-partitions))

**Comment by jcrist** [comment]
Closing as stale, #8058 better reflects current metadata handling thoughts.
