### ISSUE TITLE
Investigate GIL monitoring

### ISSUE THREAD

**Issue by martindurant** [dask/dask#6391]
Is it possible to measure GIL locking and contention? It would be a very useful diagnostic so that users can decide between threads and processes, and otherwise fine GIL-unfriendly parts of they code.

This is a pie-in-the-sky wish, I don't know how you would do it (one attempt using linux LD_PRELOAD https://github.com/chrisjbillington/gil_load )

**Comment by martindurant** [comment]
We *should* be able to at least measure how much time is spend in waiting for thread locks, right?

**Comment by mrocklin** [comment]
I agree that this information seems useful.  I also don't know how to do it.

> We should be able to at least measure how much time is spend in waiting
for thread locks, right?

Yes, but this isn't the same as the GIL unfortunately.

**Comment by martindurant** [comment]
> this isn't the same as the GIL unfortunately.

Understood, but maybe also worthwhile. 

Unfortunately, although pycharm has nice thread and async visualisations, I've never got them to work for anything real.

**Comment by quasiben** [comment]
@kkraus14 and @shwina measured GIL locking by injecting NVTX annotations into CPython GIL Lock calls --  It was a bit of work to get this done and did require Python source builds

**Comment by shwina** [comment]
cc: @pentschev and @jakirkham as well

In short, the approach followed was:

1. Insert [NVTX](https://github.com/NVIDIA/NVTX) markers directly into the Python source, in the functions [`take_gil` and `drop_gil`](https://github.com/python/cpython/blob/7be4e350aadf93c4be5c97b7291d0db2b6bc1dc4/Python/ceval_gil.h#L143-L271). 

2. Build a conda environment on this version of Python -- the details of this are murky to me and perhaps Peter or John can fill in here.

3. Run your Python code as follows: 

```
nsys profile -t nvtx,osrt python /path/to/program.py
```

4. Open the resulting `.qdrep` file in [Nsight Systems](https://developer.nvidia.com/nsight-systems) to visualize where the GIL is dropped/taken.

**Comment by pentschev** [comment]
If anyone is interested, I have the required changes @shwina mentioned in a branch of mine from a python-feedstock fork in https://github.com/pentschev/python-feedstock/tree/3.7-nvtx-take-gil . IIRC, building wasn't difficult, it was mostly a matter of running https://github.com/pentschev/python-feedstock/blob/3.7-nvtx-take-gil/recipe/build.sh , the problem is the time that process takes, it was taking me several hours due to the tests that the build process runs and I wasn't able to easily disable them so ultimately we paid the cost of build time.

**Comment by mrocklin** [comment]
My guess is that most Dask users won't be comfortable building Python, or
even installing a different Python package into their environment.  If
that's true then I'm not sure that there is much that we can do here.

**Comment by pentschev** [comment]
Yeah, I agree. It may still be a reasonable approach for developers at that stage where they don't know what else to do though. 🙂

**Comment by JulianWgs** [comment]
Another approach would be to measure the influence of processes vs. threads indirectly via the runtime of tasks and task graphs. One of the goals of my project [dask log server](https://github.com/JulianWgs/dask-log-server) is to build to database to answer these kinds of questions. With this database you could build an interpretable model which predicts the runtime based on the logging data. Of course it is impossible to make prediction for an arbitrary graph. Anyway I just wanted to add this to the discussion :)

**Comment by martindurant** [comment]
py-spy has gil tracking: https://github.com/benfred/py-spy#how-does-gil-detection-work

**Comment by maartenbreddels** [comment]
I've been looking into this issue a bit, I've found https://www.youtube.com/watch?v=HtbLNgXmLrw&ab_channel=EuroPythonConference but that solution requires a recompilation of Python with dtrace enabled.


I managed to get a prototype working using the Linux perf tool https://github.com/maartenbreddels/per4m and https://github.com/gaogaotiantian/viztracer (some discussion at https://github.com/gaogaotiantian/viztracer/issues/60). The nice thing is that you can also show hardware performance counters (cache misses, instructions/cycles=mem saturation indicator). A better solutions would use ebpf/bcc but those tools are not as easy to install as perf (standard linux tool).
I have to admit I still cannot tell if it is the GIL or some other mutex, although it is possible (kprobes/uprobes might also help here).

Anyway, just wanted to share there are ways to visualize the GIL in 2020 (https://www.dabeaz.com/GIL/gilvis/index.html is from 2010 and used a custom Python version )

**Comment by JulianWgs** [comment]
Here is a very nice blog post by Maarten Breddels about the topic:

https://www.maartenbreddels.com/perf/jupyter/python/tracing/gil/2021/01/14/Tracing-the-Python-GIL.html

(I only realized after reading the blog post and looking into this issue again, that you already commented on here. Well may be it is interesting for the others 😅)

**Comment by maartenbreddels** [comment]
Thanks @JulianWgs 

> I have to admit I still cannot tell if it is the GIL or some other mutex, although it is possible (kprobes/uprobes might also help here).

This is indeed solved using uprobes.

I've been thinking a bit about how this can be done live, like in the dask dashboard. The current method is not live/interactive visualization, but it can be done using the [perf_event_open](https://man7.org/linux/man-pages/man2/perf_event_open.2.html) syscall. This could be a highly non-trivial undertaking though.

As mentioned in the blog post, getting a report on which (c-extension) function does not release the GIL could already be helpful.

I hope the blog post is an inspiration to develop similar tooling.

**Comment by quasiben** [comment]
Gil monitoring has recently been added to the dashboard:
https://github.com/dask/distributed/pull/7646
