### ISSUE TITLE
InvalidIndexError error mapping dask series

### ISSUE THREAD

**Issue by scottlittle** [dask/dask#6394]
**What happened**:
Tried to map a dask series to a dask series of a separate dataframe.  Stackoverflow issue: [InvalidIndexError error mapping dask series](https://stackoverflow.com/questions/62836974/invalidindexerror-error-mapping-dask-series)

**What you expected to happen**:
Mapping would produce a new column of main dataframe (ddf).

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

np.random.seed(0)
df = pd.DataFrame(np.random.randint(20,120,size=(10_000_000, 4)), columns=['A','B','C','myid'])
df['textcol'] = 'doggy'
ddf = dd.from_pandas( df, npartitions=10 )
ddf.to_parquet('premyfile.parquet', 
               engine='fastparquet',
               compression='snappy', 
               write_index=False,
               compute_kwargs={'scheduler':'threads'}
              )

val = pd.DataFrame( data=np.array([np.arange(20,120),np.random.random(100)]).T, columns=['myid','val'] )
val = dd.from_pandas( val, npartitions=1 )
val['myid']=val['myid'].astype(int)
val = val.set_index('myid')

ddf = dd.read_parquet( 'premyfile.parquet' )
ddf['val'] = ddf['myid'].map( val['val'], meta=pd.Series(float) )

#should error out here
ddf.head() 

#this should also error out
ddf.to_parquet('myfile.parquet', 
               engine='fastparquet',
               compression='snappy', 
               write_index=False,
               compute_kwargs={'scheduler':'threads'}
              )
```

**Anything else we need to know?**:
If you don't save the original ddf to parquet, it does not error.  Also, I'm having more luck with `pyarrow` in my own data, but that process is still running.  In the toy example above, it seems like `pyarrow` has issues as well.

**Environment**:
- Dask version: 0.20.0
- Python version: 3.6
- Operating System: Centos 7
- Install method (conda, pip, source): pip
- Other: numpy 1.18.1, pandas 1.0.5, fastparquet 0.4.0, pyarrow 0.17.1, python-snappy 0.5.4, snappy.x86_64 1.1.0-3.el7

**Comment by scottlittle** [comment]
It seems like setting the above line:
`ddf = dd.read_parquet( 'premyfile.parquet' )`
to
`ddf = dd.read_parquet( 'premyfile.parquet', index=False )`
resolved the issue.

**Comment by martindurant** [comment]
@rjzamora 's refactor is working to prevent automatic selection of indexes in the case that the user didn't specify one, nor is there pandas metadata indicating which column originally was it. This removes guesswork, and potentially saves time decoding parquet statistics. This case is exemplary, since the pandas metadata should show that the original had *no* index.

In the short term, you may want to specify the index as False on load, to prevent trying to guess the index.

**Comment by quasiben** [comment]
Thanks @martindurant.  Given the comments above I think we are good to close.
