### ISSUE TITLE
Better visibility into task arguments

### ISSUE THREAD

**Issue by JohnEmhoff** [dask/dask#6396]
We have a particularly compute heavy task that tends to occupy most of our cluster. It takes just a couple strings as arguments and crunches for some number of hours. It'd be nice if the web UI could show us those arguments so we can quickly see what the cluster is doing and also quickly learn something about tasks that fail. I understand that this doesn't make sense for a lot of use cases (e.g. when passing around huge dataframes) but the ability to inspect simple scalar arguments seems like it would always be a win.

I'm pretty sure I checked the UI thoroughly for something like this but never found it -- please correct me if I'm wrong.

**Comment by mrocklin** [comment]
You're correct that this isn't available today.  For security reasons the
scheduler actually doesn't unpack the Python tasks, so they're little black
boxes that are hard to visualize.

However, you might want to try a project like Prefect, which builds on top
of Dask to provide more information like this, and tends to include other
features that are commonly requested from people in your situation.

**Comment by mrocklin** [comment]
https://www.prefect.io/

**Comment by JohnEmhoff** [comment]
Ah, we had stumbled upon prefect and it looked pretty promising but we didn't want to completely rearchitect our outer loop (adding dask in the middle was a big change already). It sounds like we should consider a more thorough retooling now that we're comfy with dask.
