### ISSUE TITLE
pre-commit hook broken in fresh environment

### ISSUE THREAD

**Issue by JimCircadian** [dask/dask#6401]
II had a commit to the docs fail with the pre commit hook, when I expected it to go correctly. It wasn't validation related, but setup of the hook that caused the problem.

```
[INFO] Stashing unstaged files to /home/jambyr/.cache/pre-commit/patch1594487860.
[INFO] Initializing environment for https://github.com/python/black.
[INFO] Restored changes from /home/jambyr/.cache/pre-commit/patch1594487860.
An unexpected error has occurred: CalledProcessError: command: ('/usr/libexec/git-core/git', 'checkout', 'stable')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'stable' did not match any file(s) known to git.
    
Check the log at /home/jambyr/.cache/pre-commit/pre-commit.log
```

I believe this is due to the redirect in place from python/black to psf/black in github

```
--   repo: https://github.com/python/black
+-   repo: https://github.com/psf/black
```

1. Follow the documentation for installing the pre-commit hooks from master: https://docs.dask.org/en/latest/develop.html#code-formatting with a completely fresh environment (I guess pre-commit caches the libraries hence why it's not already an issue?)
2. Add a change
3. Try to commit :-)

- Dask version: master
- Python version: 3.8
- Operating System: CentOS7
- Install method (conda, pip, source): conda

**Comment by JimCircadian** [comment]
Oh no, sorry I'm wrong, that's not the cause...

**Comment by jcrist** [comment]
Hmmm, I'm not able to reproduce - running `pre-commit install-hooks` on a fresh setup (after cleaning out my pre-commit cache) worked fine with the existing configuration.

Have you tried running:

```
pre-commit clean
pre-commit install-hooks
```

You can also use `black` and `flake8` manually instead of running with `pre-commit`, but having the git integration is nice so you don't forget.

**Comment by JimCircadian** [comment]
No joy with 2.2.0 (as per known environment) nor 2.6.0 (pulled by default). Will dig further into this.

**Comment by JimCircadian** [comment]
@jcrist 

It's the git version, I was using my system git (v1.8), when I upgraded to v2 in the conda env it works fine. This is undoubtedly since I use CentOS7 for my laptop (hence old mainstream git version)

It also turns out that the pinning of the pre-commit hook to python3.7 prevents usage with v3.8, but it works fine when set generically to python3. I wonder does this perhaps suggest it worth changing this in the precommit hook and documenting git in the developer guide? 

Probably a fringe issue given my non-typical OS choice, but doubtless worth sorting somehow to avoid another issue?

**Comment by gforsyth** [comment]
Thanks for reporting @JimCircadian -- as this isn't an issue with our config so much as it's an upstream issue with pre-commit not checking `git` versions, I'm inclined to close this out once you've linked the upstream issue.

**Comment by JimCircadian** [comment]
Closing as advised, apologies for the delay! :-)

**Comment by JimCircadian** [comment]
Interesting feedback @jcrist @gforsyth 

pre-commit assumes that the value of rev is an immutable ref (such as a tag or SHA) and will cache based on that. Using a branch name (or HEAD) for the value of rev is not supported and will only represent the state of that mutable ref at the time of hook installation (and will NOT update automatically).

**Comment by gforsyth** [comment]
That is good to know!  Thanks, @JimCircadian !
