### ISSUE TITLE
Duplicate argument definitions in `to_csv` docstring

### ISSUE THREAD

**Issue by tebesfinwo** [dask/dask#6412]
There are two definitions of `compression` arguments in `data.dataframe.io.csv.to_csv` docstring and one of them does not match with the implementation. 

https://github.com/dask/dask/blob/7aaef9fa8d9d37c7c7e57a1125d7d06ef2a8fefb/dask/dataframe/io/csv.py#L743-L785

**What happened**:
I noticed that compression didn't apply automatically even though the `gz` was an extension of the filename when I was using `data.dataframe.io.csv.to_csv`. Then, I realized there were two `compression` arguments in the [API documentation](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.to_csv). 

**What you expected to happen**:
I expected the argument definitions in the `to_csv` docstring to match up with its implementation. 

**Environment**:
- Dask version: 2.19.0
- Python version: Python 3.7.3
- Operating System: macOS
- Install method (conda, pip, source): poetry

**Comment by tebesfinwo** [comment]
I hope that I follow the right steps to contribute. Here's the [PR](https://github.com/dask/dask/pull/6411) to remove the duplicated `compression` argument from `to_csv`.

**Comment by jsignell** [comment]
Yep, you followed the steps perfectly! Thanks for the PR :)

**Comment by tebesfinwo** [comment]
https://github.com/dask/dask/pull/6411 has been merged to `master`
