### ISSUE TITLE
Using Series map in a loop overwrites previous results

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask#6416]
**What happened**:
I want to get the value of a nested dictionary column in a dataframe. I try to boil down the use case as much as possible in the MWE. In reality it is more complicated. Unfortunately in every iteration of the loop the results of the previous loops get overwritten. This does not happen, when simply assigning a value.

**What you expected to happen**:
Each column having a different/correct value.

**Minimal Complete Verifiable Example**:

```python
import json
import pandas as pd
import dask.dataframe as dd

data = {
        "name": "A", "age": 25,  "nested": {"key1": "value1", "key2": "value2"}
    }

with open("data.json", "w") as file:
    json.dump(data, file)
ddf = dd.read_json("data.json")
keys = ["key1", "key2"]

for key in keys:
    ddf[key] = ddf["nested"].map(lambda dict_: dict_.get(key), meta=pd.Series(name=key, dtype=str))
    ddf[key + "-str"] = key
ddf.compute()
```

**Anything else we need to know?**:
Feel free to ask.

**Environment**:

- Dask version: 2.20.0
- Python version: 3.6.9
- Operating System: Ubuntu 18.04.4
- Install method: pip

**Comment by JulianWgs** [comment]
Okay, I just solved the problem in my usecase with [functools.partial](https://docs.python.org/2/library/functools.html#functools.partial). I will leave this open for further discussions, but feel free to close it.

**Comment by jsignell** [comment]
Glad you figured it out!

**Comment by gforsyth** [comment]
@JulianWgs -- I think you just ran in to https://docs.python-guide.org/writing/gotchas/#late-binding-closures

**Comment by JulianWgs** [comment]
Thank you! It's confusing, because it works in pandas...

**Comment by gforsyth** [comment]
> Thank you! It's confusing, because it works in pandas...

Yep, `pandas` is executing it as you go, but `dask` doesn't execute until you hit `compute`, at which point you'll get the lambda using the last value of `keys`

**Comment by JulianWgs** [comment]
True :D Is it possible to have a check for that, since the error isn't always obvious? I would greatly appreciate it

**Comment by gforsyth** [comment]
I don't think so, it's just a part of Python that comes up when using `dask`.  If you're interested you could add a section to 
 "Best Practices" in the docs

**Comment by gforsyth** [comment]
It happens with all functions and it can happen nearly anywhere.  I don't think there's a global fix / check / warning for this beyond documentation.

**Comment by JulianWgs** [comment]
Okay, thank you :)

**Comment by mrocklin** [comment]
It's more of an issue with lambdas, which do some late binding thing in
Python.  I think that this is more a Python wart than a Dask one :)
