### ISSUE TITLE
Count unique values in a row using dask.array

### ISSUE THREAD

**Issue by eric-czech** [dask/dask#6423]
Is there a way to efficiently calculate the frequency of elements in arrays along an axis using the Array API?

I see a few somewhat related issues like https://github.com/dask/dask/issues/2953 and https://github.com/dask/dask/issues/2851, but this is more specifically what I'd like to do:

```python
x = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [1, 1, 1],
    [2, 2, 2],
])
# A hypothetical `count` function would collapse all 
# dimensions into the requested dimension, counting
# all elements along it
y = count(x, axis=0)
# y.shape = (x.shape[0], x.max())
[
    # The columns are indexed by the values
    # themselves and the counts correspond
    # to the frequency of that value
    [3, 0, 0], # three 0s, no 1s or 2s
    [2, 1, 0], # two 0s, one 1, zero 2s
    [0, 3, 0],
    [0, 0, 3]
]
```

In my case, the max value in `x` is known beforehand and is generally small (<= 4).  I can see a way to do it if dask.array supported `unique` over an axis, but it would still be somewhat complicated.  

Is there a better way to approach this?

Thanks!

**Comment by mrocklin** [comment]
If you are comfortable guaranteeing that the axix along which you are doing the counting can be combined into a single chunk, and if your values are always in `0..k` then you could combine `da.apply_along_axis` with `np.bincount`

```python
In [1]: import dask.array as da                                                                                                                                                                                   

In [2]: import numpy as np                                                                                                                                                                                        

In [3]: x = da.random.randint(0, 4, size=(10, 4), chunks=(5, 2))                                                                                                                                                  

In [4]: da.apply_along_axis(np.bincount, 1, x, minlength=4).compute()                                                                                                                                             
Out[4]: 
array([[1, 0, 1, 2],
       [0, 2, 1, 1],
       [0, 1, 2, 1],
       [1, 0, 2, 1],
       [1, 0, 1, 2],
       [1, 1, 0, 2],
       [0, 1, 2, 1],
       [1, 1, 2, 0],
       [1, 0, 1, 2],
       [2, 2, 0, 0]])
```

If you wanted to relax the aggregated-axis-fits-in-memory constraint then we would have to be a little bit more complex, but it's probably not terrible.

**Comment by eric-czech** [comment]
Oh interesting, thanks @mrocklin!  For the sake of argument, let's say we're not comfortable with the tall-skinny assumption.  Is there a more idiomatic way to do something like this then?

```python
da.random.seed(0)
x = da.random.randint(0, 4, size=(10, 4), chunks=(5, 2))    
# Do the same thing, but within each block
y = da.map_blocks(
    lambda x: np.apply_along_axis(np.bincount, 1, x, minlength=4), 
    x, chunks=(x.chunks[0], 4)
)
# Stack the column blocks on top of each other as a new dimension
z = da.stack([y.blocks[:, i] for i in range(y.numblocks[1])])

# Sum across the column blocks containing counts
result = z.sum(axis=0)

np.testing.assert_allclose(result, da.apply_along_axis(np.bincount, 1, x, minlength=4))
result
array([[0, 1, 1, 2],
       [2, 1, 0, 1],
       [0, 2, 0, 2],
       [1, 1, 1, 1],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 4, 0, 0],
       [0, 1, 1, 2],
       [1, 1, 2, 0],
       [0, 0, 2, 2]])
```

I've been doing this a lot recently -- having use cases where I need to move to and from treating blocks as array dimensions.  Any advice on how to do that without loops and `.blocks` would be awesome.

**Comment by mrocklin** [comment]
Yes, that would work.  I'll bet that it would be near optimal.  You could also call `da.apply_along_axis(..., x.blocks[:, i], ...)` a few times and then add those results together.  It's all the same though.

**Comment by eric-czech** [comment]
Perfect, thanks for the quick response!
