### ISSUE TITLE
dask.base.tokenize raises RecursionError when passed an object that contains cycles

### ISSUE THREAD

**Issue by jbweston** [dask/dask#6425]
**What happened**: `RecursionError` is raised when passing an object containing cycles to `dask.tokenize`

**What you expected to happen**: A valid token to be returned

**Minimal Complete Verifiable Example**:

```python
import dask.base

cycle = dict(a=None)
cycle["a"] = cycle

dask.base.tokenize(cycle)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.20.0
- Python version: 3.8
- Operating System: Ubuntu 18.04 LTS (running under WSL)
- Install method (conda, pip, source): conda (from conda forge)

**Comment by jsignell** [comment]
Well that is certainly an interesting error! Is there a usecase for this? For context the repr of `cycle` is `{'a': {...}}` maybe dask should tokenize that instead?

**Comment by jbweston** [comment]
We're using bits and pieces of Dask (mostly from `dask.base` and `dask.core`) for manipulating task graphs. At some point we want to tokenize the inputs to a task for the purpose of caching. One of the inputs is a complicated object that happens to contain a cycle, and tokenization fails in this case.

I'm not sure what a solution would look like. IIRC `pickle` solves this problem by keeping track of all the objects it has seen during serialization, perhaps a similar approach could be used here?

**Comment by jsignell** [comment]
Or maybe we should just use a `uuid` if tokenize fails.

**Comment by jsignell** [comment]
To see if that would work, you could try using tokenize from dask.delayed and setting `pure=False`.

**Comment by jsignell** [comment]
Hopefully that solves your use case @jbweston. If not please feel free to reopen!

**Comment by jbweston** [comment]
Thanks!
