### ISSUE TITLE
da.histogram unequal array generation

### ISSUE THREAD

**Issue by Sh4zKh4n** [dask/dask#6427]
Hi, I have been using the dask version of histrogram on my array but have run into an interesting problem that I also notice on the dask histogram example. The examples from the dask API shows the same problem, when generating a histogram for example from uint8 image or in the case of the example from the API docs the bin number is one value more than the array of frequency's. The API docs show it as well:

`import dask.array as da

 import numpy as np

x = da.from_array(np.arange(10000), chunks=10)

h, bins = da.histogram(x, bins=10, range=[0, 10000])

 bins

array([    0.,  1000.,  2000.,  3000.,  4000.,  5000.,  6000.,  7000.,
        8000.,  9000., 10000.])

 h.compute()

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])`

As you can see from the above example, there are 11 bins including 0 and 10 values computed from the frequency. It becomes an issue when I try to add these to a dataframe and well then comes the question, has this actually calculated everything correctly or are these bin edges? If they are bin edges, they should be noted as such and a little confused.

**Comment by gforsyth** [comment]
@Sh4zKh4n -- `da.histogram` returns the histogram values and the bin edges, following the behavior of https://numpy.org/doc/stable/reference/generated/numpy.histogram.html.

We could add a `Parameters` and `Returns` section to the `histogram` docstring to make this clearer.

**Comment by Sh4zKh4n** [comment]
@gforsyth -- I think thats the right thing to do, i realised the same. I just ended up making a 1d array of 0-255 and then making an df with both those arrays. It's an easy thing but an annoying slight that could take peoples time up and create a bit of confusion. Thanks for taking a look at it.

**Comment by gforsyth** [comment]
@Sh4zKh4n are you interested in submitting a PR with those documentation updates?

**Comment by Sh4zKh4n** [comment]
@gforsyth , if I knew what that acronym meant and how to do it? ....sure I would. If you could help me out that would be great.

**Comment by gforsyth** [comment]
A PR is a pull request, a proposed change to the code in this repository.  There is some information on how to contribute to the documentation here: https://docs.dask.org/en/latest/develop.html#contributing-to-documentation

**Comment by rpanai** [comment]
@Sh4zKh4n `da.histogram` is in [https://github.com/dask/dask/blob/master/dask/array/routines.py](https://github.com/dask/dask/blob/master/dask/array/routines.py) let me know if you want to make a PR otherwise I can work on it.
@gforsyth just to confirm: here we want to use the same scheme as in `np.histogram` isin't ?

**Comment by gforsyth** [comment]
> @gforsyth just to confirm: here we want to use the same scheme as in `np.histogram` isin't ?

Yes, that's right.

**Comment by Sh4zKh4n** [comment]
@rpanai I can have a go but I would have to work it out from the docs how to do it. Though, if you have time. Could you have a go and give me an overview how to? I can go through the docs at the same time?

**Comment by rpanai** [comment]
@Sh4zKh4n if you can do it go for it. I could eventually work on it in 6 hours. So if you're not done in a couple of hours please let me know.

**Comment by Sh4zKh4n** [comment]
@rpanai I probably won't get time, I'm going be putting my kids sleep...stories and all!

**Comment by rpanai** [comment]
> Though, if you have time. Could you have a go and give me an overview how to? I can go through the docs at the same time?

I'm not very expert but if you like we could try.

**Comment by rpanai** [comment]
@gforsyth @Sh4zKh4n here is my [PR](https://github.com/dask/dask/pull/6439) do you mind to check if it makes sense?

**Comment by ameraner** [comment]
Hi, I think this issue can be closed after https://github.com/dask/dask/pull/6439.

**Comment by gforsyth** [comment]
Thanks for the ping, @ameraner !
