### ISSUE TITLE
Get the underlying array type for a Dask array

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask#6442]
If I have a Dask array which is backed by something other than numpy (cupy for example) I may want to check the type of the underlying array.

I can currently use `_meta` for this, but I feel like I shouldn't be using a private attribute.

```python
>>> import cupy as cp
>>> import dask.array as da

>>> garr = cp.random.random((1000, 1000))
>>> dgarr = da.from_array(garr, chunks=(100, 100))

>>> isinstance(dgarr._meta, cp.ndarray)
True
```

Is there some other means to determine this? And if not how could we expose this?

**Comment by mrocklin** [comment]
Currently this is all that we have.  I don't have strong thoughts on a
public API here.  If it was me I would probably just rely on `_meta`.  It
is private, but also probably pretty reliable?  Maybe?

**Comment by jsignell** [comment]
Should meta be private? I often find myself checking it.

**Comment by jsignell** [comment]
In terms of a new API, I think `dgarr.arraytype` which is implemented as a property that just does `type(dgarr._meta)` would be reasonable. But maybe that gets bad if you then expand it out to dataframe. Would it then be `ddf.dataframetype`? Another option would be `chunktype` and `partitiontype`.

**Comment by jacobtomlinson** [comment]
> If it was me I would probably just rely on `_meta`.

I'm happy to do that, I just find relying on a private attribute a little unpleasant.

> It is private, but also probably pretty reliable?

If we are happy to guarantee it's reliability should it be public? 

> I think dgarr.arraytype which is implemented as a property that just does type(dgarr._meta) would be reasonable

That could work. But perhaps exposing `_meta` as `meta` would also work?

**Comment by jsignell** [comment]
I think it'd be reasonable to expose `_meta` as `meta` perhaps with only a getter?

**Comment by mrocklin** [comment]
If we're going to make this change then we might also consider renaming `meta` to something more intuitive.  Also, I'm going to cc a few folks here that might care about this change.  @TomAugspurger @pentschev

**Comment by TomAugspurger** [comment]
`meta` is fine by me. FWIW, xarray called this `template`:
http://xarray.pydata.org/en/latest/generated/xarray.map_blocks.html#xarray.map_blocks

**Comment by mrocklin** [comment]
`example`, `example_partition`, `example_block`, `sample`, ...

The term meta I think is a bit developer-y.  I'm also totally ok with it, but I wouldn't mind some brief brainstorming.

**Comment by jsignell** [comment]
I like the idea of following xarray and using `template`.

**Comment by jsignell** [comment]
We want to avoid anything that is likely to be a column name right? So `meta` might be kind of annoying.

**Comment by pentschev** [comment]
I don't have any preferences naming-wise. I'm only wondering if maybe keeping it private and adding a getter as @jsignell proposed would make more sense, I'm not sure whether this is an attribute that once public may be tempting for someone to change (never underestimate the power of creativity) and end up with some "interesting" behavior.

**Comment by mrocklin** [comment]
Historically we haven't used private variables and getters and things have
been mostly fine.

**Comment by GenevieveBuckley** [comment]
I would also like an approved way of getting the underlying array type. Like Jacob, I'm currently using `type(arr._meta)` / `isinstance(arr._meta, expected_type)`. 

I don't use dask dataframes though, so I understand if complications there might make things not quite as simple as they might seem at first.

**Comment by mrocklin** [comment]
> I would also like an approved way of getting the underlying array type. Like Jacob, I'm currently using type(arr._meta) / isinstance(arr._meta, expected_type).

I think that right now `_meta` is used throughout enough projects that it is informally approved.  I think that it is reasonable to change away from this convention, but that it would almost certainly need to be done smoothly to support downstream projects.  So I think that for other projects the current state is ok/non-threatening.

The less clear-cut situation I see if if we want users to find this field as well as library developers.  In that case we want a more discoverable and more informative name.  I don't think that `meta` is a good name in this case (too generic and too technical).  Other terms like template make sense, and there is probably something better.

However, the original question on this post was coming from someone asking for a stable API for library integration.  I think that we're ok with `_meta` for that for now.  Does anyone here have a strong need to support users with a discoverable name?  If not, we might close and just keep using `_meta`?

**Comment by jsignell** [comment]
I think before exposing users to a more discoverable `_meta` there is probably some more work to be done to improve `_meta`'s accuracy. So I am in favor of closing this issue and waiting for a user to ask for this. Maybe we could add a section to the developer docs about `_meta` just noting that this is the standard way of accessing the array type?

**Comment by jsignell** [comment]
For reference, the mentions of `_meta` are mainly in the dask dataframe docs under [dataframe-design](https://docs.dask.org/en/latest/dataframe-design.html?highlight=_meta) and [dataframe-extend](https://docs.dask.org/en/latest/dataframe-extend.html?highlight=_meta).

**Comment by jakirkham** [comment]
We could just have a `get_meta` public utility function, which just returns `obj._meta` for whatever `obj` might be.

**Comment by mrocklin** [comment]
> So I am in favor of closing this issue and waiting for a user to ask for this

+1

**Comment by jacobtomlinson** [comment]
> So I am in favor of closing this issue and waiting for a user to ask for this

In this instance I was the user asking for this. I was working on xarray and needed this. However I'm happy to continue using `_meta` in xarray if that is the chosen way to do things.

**Comment by mrocklin** [comment]
I think that it's a safe way to do things.  If we want to choose another
way I'm open to that, but I don't see a large motivation.

**Comment by jsignell** [comment]
Ah sorry @jacobtomlinson I thought you were asking as a developer of xarray not as a user of xarray.

**Comment by jacobtomlinson** [comment]
> I thought you were asking as a developer of xarray

That's true I was. I meant as a user of Dask (I.e xarray consumes the public APIs of Dask).

**Comment by jsignell** [comment]
Right I guess it seems more palatable to have maintainers of downstream libraries accessing private APIs than it would be to have users accessing private APIs.
