### ISSUE TITLE
dask.delayed.Delayed class should appear in objects.inv

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#6465]
If a third-party project that uses dask, intersphinx, and sphinx-autodoc subclasses dask.delayed.Delayed and documents the new class using the ``:show-inheritance:`` flag, sphinx produces an error because it can't find Delayed in  ``https://docs.dask.org/en/latest/objects.inv``.
Starting from Sphinx 3, this issue gets worse as it applies to anything that references dask.delayed.Delayed in a type annotation too.

**Comment by TomAugspurger** [comment]
Makes sense. It can be added at https://github.com/dask/dask/blob/master/docs/source/delayed-api.rst
