### ISSUE TITLE
write_parquet using partition_on breaking on GCS

### ISSUE THREAD

**Issue by hermesribeiro** [dask/dask#6467]
**What happened**:

Saving a partitioned dask dataframe on google cloud storage raises the following error

```shell
/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py in _write_partitioned()
    246         )
    247         prefix = fs.sep.join([root_path, subdir])
--> 248         fs.mkdir(prefix, exists_ok=True)
    249         outfile = guid() + ".parquet"
    250         full_path = fs.sep.join([prefix, outfile])

TypeError: mkdir() got an unexpected keyword argument 'exists_ok'
```

**What you expected to happen**:

The file should be saved on GCS using a folder structure for the partitions.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
dd.from_pandas(pd.DataFrame({'foo': [1, 1, 2, 2]}), npartitions=1).to_parquet('gs://...', partition_on=['foo'])
```

**Anything else we need to know?**:

1. Locally it works fine
2. Maybe there is a typo on https://github.com/dask/dask/blob/05c17758aa9d44158538b7d5059524de18843ae3/dask/dataframe/io/parquet/arrow.py#L75

**Environment**:

- Dask version: 2.21.0
- GCSFS version: 0.6.2
- Python version: 3.7.6
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
@martindurant

**Comment by martindurant** [comment]
`exist_ok` has never been in the signature of `mkdir` (it is in `makedirs`). It may have been silently ignored as part of **kwargs; I could make that change. Also worth checking against master, since a lot of code has changed since 0.6.2 .

**Comment by mrocklin** [comment]
cc @rjzamora then in case we shouldn't be using that API
