### ISSUE TITLE
Dask Array Chunking does not match example in docs

### ISSUE THREAD

**Issue by joshreback** [dask/dask#6468]
To reproduce:

```
import numpy as np
npa = np.array([
   [1, 2, 3, 4, 5, 6],
   [7, 8, 9, 0, 1, 2],
   [3, 4, 5, 6, 7, 8],
   [9, 0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9, 0],
   [1, 2, 3, 4, 5, 6]
])
a = da.from_array(npa, chunks=3)
a.blocks[0]  
# dask.array<blocks, shape=(3, 6), dtype=int64, chunksize=(3, 3), chunktype=numpy.ndarray>
a.blocks[0].compute()
# array([[1, 2, 3, 4, 5, 6],
#       [7, 8, 9, 0, 1, 2],
#       [3, 4, 5, 6, 7, 8]])
a.blocks[2]  
# IndexError: Index is not smaller than dimension 2 >= 2
```

**What happened**:
- Calling `compute` on the block at index 0 of the dask array produced a numpy array of shape **(3,6)**
- Got an `IndexError` when reading the block at index 2.

**What you expected to happen**:
- Calling `compute` on block at index 0 of the dask array produces a numpy array of shape **(3,3)**
- I should be able to read the block at index 2 (and 3).

**Anything else we need to know?**:
I was copying the example from the [documentation](https://docs.dask.org/en/latest/array-chunks.html#chunks-examples).

**Environment**:

- Dask version: 2.21.0
- Python version: 3.7.4
- Operating System: MacOS
- Install method (conda, pip, source): pip

If this is a bug, I am happy to work on it. I originally posted on [SO](https://stackoverflow.com/questions/63094546/understanding-dask-array-chunks) and was referred to file an issue.

**Comment by gforsyth** [comment]
Hey @joshreback -- sorry for the delay in getting to this.
I don't think this is a bug.

Your chunks/blocks are in two dimensions, so you can index them in two dimensions:

```python
In [4]: a.blocks[0, 0].compute()
Out[4]:
array([[1, 2, 3],
       [7, 8, 9],
       [3, 4, 5]])

In [5]: a.blocks[0, 1].compute()
Out[5]:
array([[4, 5, 6],
       [0, 1, 2],
       [6, 7, 8]])

In [6]: a.blocks[0].compute()
Out[6]:
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2],
       [3, 4, 5, 6, 7, 8]])
```

This tracks with `numpy`s slicing, but it operates block-by-block

```
In [8]: npa[0]
Out[8]: array([1, 2, 3, 4, 5, 6])

In [9]: npa[1]
Out[9]: array([7, 8, 9, 0, 1, 2])
```

**Comment by joshreback** [comment]
I see - makes sense! Thanks, @gforsyth
