### ISSUE TITLE
to_sql fails with distributed scheduler

### ISSUE THREAD

**Issue by mgsnuno** [dask/dask#6473]
**What happened**:
`to_sql` fails with distributed scheduler. pickle error.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd
import sqlalchemy
from dask.distributed import Client

client = Client(processes=False, threads_per_worker=2)
engine = sqlalchemy.create_engine(
    <db_connection_string_here>,
    fast_executemany=True,
)
df = dd.from_pandas(pd.DataFrame([1,2, 3,4,5]), npartitions=1)
df.to_sql('test', engine, if_exists='replace')
```

error:
```python
TypeError: cannot pickle '_thread._local' object
```

uncomment `client = Client(processes=False, threads_per_worker=2)` above and the example works, it is tied to the distributed scheduler.

**Environment**:

- Dask version: 2.21.0
- Python version: 3.8.5
- Operating System: linux 64bit (manjaro)
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for the bug report and sorry that it has taken us a while to get to. I am having trouble reproducing the error that you are seeing. This is what I am doing:

```python
from sqlalchemy import create_engine
import pandas as pd
from dask.utils import tmpfile
from dask.dataframe import from_pandas
from dask.distributed import Client

client = Client(processes=False, threads_per_worker=2)

df = pd.DataFrame([ {'i':i, 's':str(i)*2 } for i in range(4) ])
ddf = from_pandas(df, npartitions=2)

with tmpfile() as f:
    db = 'sqlite:///%s' % f
    ddf.to_sql('test', db , if_exists='replace')
    engine = create_engine(db)
    result = engine.execute("SELECT * FROM test").fetchall()

result
```

Can you see if you can get that to fail in the way that you were seeing?

**Comment by mgsnuno** [comment]
Hi @jsignell and sorry for the delay (work + vacations)
Your code works fine, no fail.
`f` is just a file (correct?) but `sqlalchemy.create_engine` is something more no?

Can we mock the db connection in a different way to be more representative?

P.S. - was using prefect with a DaskExecutor and had the same problem of not being able to pickle the sqlalchemy engine with the same `TypeError: cannot pickle '_thread._local' object`

**Comment by jsignell** [comment]
Ah. Yeah, passing `engine` is not supported. The method expects a string. I opened a PR to give an earlier and more descriptive error message for this scenario.
