### ISSUE TITLE
IsADirectoryError: making read_csv accept a string path to a folder without wildcards

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask#6476]
This is a minor issue, but `dask.dataframe.read_csv` can accept a string containing path to a folder with wildcards, e.g. `testfolder/*.csv`. However, passing just `testfolder` will result in `IsADirectoryError`. The same error will not appear for `read_parquet`, so I was wondering if there is any reason to have a different treatment for `csv` files? Below is the mcve:

```python
import dask.dataframe as dd
import numpy as np

# create a df with multiple blocks
df = dd.from_array(np.array([x for x in range(10)]), chunksize=5, columns=['a'])

# define a path (note all the functions below will work if the path is changed to 'test/*')
testpath = 'test/'

df.to_parquet(testpath) # this works
dd.read_parquet(testpath) # this works

# run this if in jupyternotebook (otherwise delete the folder before running the commands below to ensure that the folder contains only csv files)
!rm -vrf {testpath}

df.to_csv(testpath) # this works
dd.read_csv(testpath) # this doesn't work
```

Comparing the relevant code in https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/core.py and https://github.com/dask/dask/blob/master/dask/bytes/core.py, it seems that the behaviour in `read_csv` can be changed to accept just a string path to a folder (without wildcards), so perhaps there is a reason this was not implemented?

However, if this is something that is OK to be implemented, I will be happy to contribute (some handholding would be appreciated).

**Environment**:

- Dask version: 2.21.0
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by SultanOrazbayev** [comment]
Hmm, I think I understand the potential reason not to have it. `read_parquet` can still work on a folder in the presence of other files because of the metadata. To have the same behaviour for csv files (the name need not necessarily have the `.csv` extension), one needs to assume that the folder contains only files in one format (which to me seems reasonable, but maybe this was the precautionary concern for not accepting a path to a folder).

**Comment by gforsyth** [comment]
Hi @SultanOrazbayev -- thanks for raising this.  I think the different handling is more a function of the relative age of each `read_*` method.  (I could be wrong about that).

If you want to take this on, I think it would be a good addition.

**Comment by SultanOrazbayev** [comment]
OK, I know how to spend the next weekend.

**Comment by mrocklin** [comment]
:)

**Comment by SultanOrazbayev** [comment]
So after implementing this and trying it out under various scenarios, I feel that actually the existing approach based on globstrings is simpler, and allowing just directories will introduce unnecessary complexity (how to deal with nested directories, symlinks, etc.), so my guess is that it's best to leave things as they are. Just in case, my implementation is here: https://github.com/SultanOrazbayev/dask/commit/511ea7194c9d71f7d059ba754e9c6a06e2cf1c52

**Comment by jsignell** [comment]
Thanks for trying it out anyways!
