### ISSUE TITLE
DOC: add example of reading parquet file from gs

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6480]
https://docs.dask.org/en/latest/dataframe-create.html#reading-from-various-locations

Is fairly fleshed out which is good.

I think another example could be added at the end. My motivation here is that I often think you can't have too many examples (within reason). In addition, the example below is copy-pastable (although I believe it does require gcsfs to be installed but I think the error message makes this clear).

My proposal would be to change 

```
>>> df = dd.read_csv('s3://bucket-name/my-data-*.csv',
...                  storage_options={'anon': True})
```

to

```
>>> df = dd.read_csv('s3://bucket-name/my-data-*.csv',
...                  storage_options={'anon': True})
>>> df = dd.read_parquet("gs://dask-nyc-taxi/yellowtrip.parquet",
                     storage_options={"token": "anon"})
```

**Comment by jsignell** [comment]
Sorry this sat for a while. I like copy pastable :) Are you planning on opening a PR?

**Comment by raybellwaves** [comment]
Np
