### ISSUE TITLE
Dataframe Performance - updates

### ISSUE THREAD

**Issue by martindurant** [dask/dask#6486]
Ref #6264

dask version 2.22.0+4.g9131e0dd

Some more notes.

- I can confirm that `len(df)` does now become length of the index, and is much faster than loading all columns
- I can *not* confirm that the gather statistics change has any effect, since it doesn't seem to be relevant
- `len(df)` is still slower for the index, which is a RangeIndex, than on an int or even float column; the dtype for the RangeIndex shows up as object, in the meta
- opening a big directory without _metadata still seems to call ParquetReader.open on each small file, apparently to check schema consistency
- assignment to the dataframe object breaks column selection pushdown. This, I now realise, has caused much of the breakage in the blog, solved by restarting (because the original variable has been mutated).
```
df['something'] = df['original']
df['unrelatec col']  # loads everything
```
- no-op selection `df[:]` also breaks column pushdown
- groupby-add does not pass down column selections, everything gets loaded
```
df.groupby(col1).col2.mean()  # not equivalent
df[['col1', 'col2']].groupby(col1).col2.mean()
```
- complex filter operations do not pass down column selection
```
df[df.x > 0 && df.x < 1].y.mean()  # not equivalent
df[['x', 'y']][df.x > 0 && df.x < 1].y.mean()
```
- still get the `Perhaps some other process is leaking memory?` messages, although I didn't get as far as to crash a worker

**Comment by TomAugspurger** [comment]
> I can not confirm that the gather statistics change has any effect, since it doesn't seem to be relevant

As a test, would we expect that re-writing the dataset with Dask, so that there's a metadata / common_metadata file, would have better performance?

**Comment by martindurant** [comment]
Yes, it should definitely avoid touching the all the files from the client - but I don't know why that's happening anyway, I thought we were OK assuming that the schema would be consistent across source files.

**Comment by martindurant** [comment]
(^ cc @rjzamora )

**Comment by rjzamora** [comment]
> Yes, it should definitely avoid touching the all the files from the client - but I don't know why that's happening anyway, I thought we were OK assuming that the schema would be consistent across source files.

We don't *usually* set "validata_schema" in Dask, so we just get default pyarrow behavior.  The only time we avoid schema validation is when we actually **do** have a "_metadata" (since we are not collecting the metadata manually).

Should we make the "validate_schema" option a bit more transparent to the user, and set the default to `False`?

**Comment by martindurant** [comment]
I definitely think so!
We could optionally take the schema from the first file (I assume this is what arrow does if not validating) and use pandas astype or supply the schema to the parquert loader in the load tasks.

**Comment by jorisvandenbossche** [comment]
(note that the new `pyarrow.dataset` doesn't check al files by default any more. The default is to use the schema of the first file)

**Comment by jsignell** [comment]
I think this issue can be closed since it seems like it was intended as a snapshot of the state of affairs. But people can reopen if they disagree with that assessment.
