### ISSUE TITLE
AWS Local and Remote Configuration Conflicts

### ISSUE THREAD

**Issue by brandonwillard** [dask/dask#6488]
**What happened**:

Local AWS configuration parameters&mdash;specified via arguments like `storage_options` to `read_parquet`&mdash;are being distributed to remote workers, which causes errors.

**What you expected to happen**:

It's not clear where the distinction between local and remote parameters to underlying `s3fs` objects is&mdash;or can be&mdash;made.  If there's an option that distinguishes the two or a means of specifying both separately, I wasn't able to find it.

**Minimal Complete Verifiable Example**:

Consider the following local AWS configuration:
```config
# ~/.aws/config
[default]
region = us-east-1

[profile some-profile]
role_arn = arn:aws:iam::<id>:role/some-profile
source_profile = default
mfa_serial = arn:aws:iam::<id>:mfa/<user>
```

Now, assuming that the remote workers do not have similar configurations with a `some-profile` entry, the following code should reproduce the error:

```python
import dask.dataframe as dd

from dask.distributed import Client


client = Client('localhost:8080', set_as_default=True)

s3_storage_options = {
    "profile": "some-profile"
}

s3_file = "s3://some-bucket/some-file.parquet"

df = dd.read_parquet(s3_file, storage_options=s3_storage_options)

df_head = df.head(compute=False)

df_head_ft = client.compute(df_head)
```

The returned future errs and the corresponding exception and log values are as follows:
```python
>>> df_head_ft.exception()
distributed.scheduler.KilledWorker("('read-parquet-head-1-5-read-parquet-55880ef71bda6e5b6fd566c74cea117e', 0)",
                                   <Worker 'tcp://<some-ip>:45135', name: tcp://<some-ip>:45135, memory: 0, processing: 1>)
>>> logs = client.get_worker_logs()
>>> [msg for status, msg in logs['tcp://<some-ip>:34111'] if status == "ERROR"]
['distributed.worker - ERROR - The config profile (some-profile) could not be found...']
```

**Anything else we need to know?**:

Attempting to forego the `"profile"` value in `s3_storage_options` results in a local exception during the `dd.read_parquet` call (when it attempts to read from the S3 source).

Setting the environment variable `AWS_PROFILE` did not seem to affect the underlying `s3fs`/`boto` objects during the `dd.read_parquet` call (i.e. they would fail without `storage_options` set).

It looks like the `storage_options` value is included in the pickled results that are sent to the workers, but it's not clear to me exactly how or why it gets included.

**Environment**:

- Dask version: 2.22.0
- Python version: 3.8
- Operating System: Ubuntu 20.10
- Install method (conda, pip, source): conda
- s3fs: 0.4.2

**Comment by jsignell** [comment]
cc @martindurant who is the most likely to have insight into this.

**Comment by martindurant** [comment]
Indeed, the same storage_options are used for instantiating s3fs on the workers as on the client. This means, if you have different configuration requirements in each situation, you need to make that configuration the default, i.e., what you get from `S3FileSystem()` (with no arguments). 
As far as I know, the following set of environment variables should be taken into consideration: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables . You could set these variables as part of worker startup scripts, client.run, or upload a configuration file.

As a more niche workaround, the fsspec file handling system allows you to stream bytes to the client via one of your workers, using its local configuration, by replacing your URL "s3://bucket/path" -> "dask::s3://bucket/path", assuming the client already exists, and sending your remote options as `storage_options={"s3": {...}}`. This is likely not efficient.

The fsspec project is considering the option to be able to register a "default" instance for each filesystem class, so that you could define this first and then use it without further configuration in following commands. This has not been implemented yet.

**Comment by brandonwillard** [comment]
> Indeed, the same storage_options are used for instantiating s3fs on the workers as on the client. This means, if you have different configuration requirements in each situation, you need to make that configuration the default, i.e., what you get from `S3FileSystem()` (with no arguments).

@martindurant, yes, I was able to get everything working after changing my local config so that `[some-profile]` was the default.  While viable at the moment, I could see it being a blocker under different circumstances.

> As far as I know, the following set of environment variables should be taken into consideration: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables . You could set these variables as part of worker startup scripts, client.run, or upload a configuration file.

I tried setting `AWS_PROFILE` in the local Python session, but that didn't seem to have any effect.  When I get some time, I'll try it again.


> As a more niche workaround, the fsspec file handling system allows you to stream bytes to the client via one of your workers, using its local configuration, by replacing your URL "s3://bucket/path" -> "dask::s3://bucket/path", assuming the client already exists, and sending your remote options as `storage_options={"s3": {...}}`. This is likely not efficient.

Not efficient in terms of computation/data or not efficient as a user-level work-around?  If this is a way to set distinct remote options, then it sounds like the most appealing approach.


> The fsspec project is considering the option to be able to register a "default" instance for each filesystem class, so that you could define this first and then use it without further configuration in following commands. This has not been implemented yet.

Would this allow one alter the instance object (e.g. remove the profile setting) after the `dd.read_parquet` call?

**Comment by martindurant** [comment]
> I tried setting AWS_PROFILE in the local Python session

It might be necessary to do this before importing s3fs in the worker

> Not efficient in terms of computation/data

It involves each read roundtripping a call to the scheduler and worker. In the case that you only need a small amount of (meta)data in the client, it might be negligible, but I imagine the overhead could easily add up. It has not been tested on real workloads.

> Would this allow one alter the instance object

I suppose you would be able to register a new default at any time? There is no design for this yet.

**Comment by brandonwillard** [comment]
In case anyone else ends up being blocked by this, I was able to hack around it by changing the `pickle` behavior for only the one `S3FileSystem` object involved:
```python
storage_options = {"profile": "some-profile"}

example_df = dd.read_parquet(
    "s3://bucket/data.gz.parquet",
    storage_options=storage_options,
)

read_parquet_key = example_df._args[1]
fs = example_df.dask[read_parquet_key, 0][2]

import types
import fsspec

def fs__reduce__(self):
    storage_options = self.storage_options.copy()
    del storage_options["profile"]
    return (
        fsspec.spec.make_instance,
        (type(self), self.storage_args, storage_options),
    )

fs.__reduce__ = types.MethodType(fs__reduce__, fs)

# Confirm that the changes took
fs_pkl = pickle.dumps(fs)
assert b"some-profile" not in fs_pkl
```

**Comment by martindurant** [comment]
An alternative would be to not specify storage_options at all, but use config files or environment variable to do it: https://filesystem-spec.readthedocs.io/en/latest/features.html#configuration

**Comment by brandonwillard** [comment]
I couldn't (and still can't) get the environment variables to actually change/use the AWS profile in this case.  Perhaps it has to do with the MFA?

**Comment by martindurant** [comment]
MFA?
The environment variables I refer to are fsspec-specific: would be `FSSPEC_s3_profile=some-local-profile`. I think this should work? If not, then indeed too much state is being pickled for your use case. One can argue about whether that is right or not.
I am surprised that the AWS-specific environment variables didn't work.

**Comment by brandonwillard** [comment]
Ohh, sorry, I _haven't_ tried the `FSSPEC_*` env variables!  I'll give that a shot.

**Comment by brandonwillard** [comment]
All right, I think that worked (i.e. `import os; os.environ["FSSPEC_s3_profile"] = "some-local-profile"`); much appreciated!  Might as well close this until further notice.

**Comment by martindurant** [comment]
Another workaround would be to create an s3 instance, followed by `s3.storage_options.pop("profile")` (the storage options are not used in the instance after the first connect)
