### ISSUE TITLE
Issues reading large ragged CSV files

### ISSUE THREAD

**Issue by jakepu** [dask/dask#6492]
**What happened**:
When I use a glob string to read a large amount of txt files into a dask dataframe, it has ParserError: Too many columns specified: expected 15 and found 6. This problem is similar to [the issue in pandas](https://github.com/pandas-dev/pandas/issues/2981). 

**What you expected to happen**:
It should return a dataframe without any error. The rows with fewer columns should have NaN in the additional columns because I already pass column names to the function.

**Minimal Complete Verifiable Example**:
Download all files from http://archive.routeviews.org/bgpdata/2020.07/UPDATES/.
Unzip all files and delete the zipped files.
Clone this github repo called [bgpdump](https://github.com/RIPE-NCC/bgpdump) to [compile an executable](https://github.com/RIPE-NCC/bgpdump/wiki)
Convert them into machine-readable txt using bgpdump with bash script (put it in the same directory as the txt files)
`for f in update*;
do
    /path/to/executable/bgpdump -m $f > ~/results/$f.txt
done`
then read them with dask.dataframe
```python
import dask.dataframe as dd
df = dd.read_csv('~/results/*', sep='|', usecols=[0,1,2,3,4,5], names = range(15), header = None)
df.compute()
```

**Anything else we need to know?**:
It seems that the parser cannot handle rows with different column size. If the 2nd column is 'W', the row is shorter (only has 6 columns). If the 2nd column is 'A', the row has 15 columns. But both dask.dataframe and pandas work without the error on one small file if I pass the list of column names. The error occurs when I read a lot of these files. I cannot test it with pandas with all these txt files because the data size is 190GB and it won't fit in my RAM. It might be a bug or there might be something wrong in my txt. If the latter is the case, could you help me locate the problem? I don't know which file and what line the error happens at.
**Environment**:

- Dask version: 2.11.0
- Python version: 3.7.6 64-bit
- Operating System: Windows 10 64-bit & Ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by Twizzledrizzle** [comment]
You can try to loop through all files one by one with pandas to see if any of them has errors.

Else if it is ok to skip rows which throws the exception, try using `error_bad_lines=False`. Not sure how it works together with dask though.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @jakepu. It looks like values for `usecols` and `names` are inconsistent (one is length 6 and one is length 15). Using the following CSV file with Pandas:

```
foo, bar, baz
1, 2, 3
```

I get a similar `ParserError` when the length of `usecols` and `names` don't match (full traceback below). Could you update `usecols` and `names` and try again 

<details>
<summary>Traceback:</summary>

```python
In [4]: pd.read_csv("file_1.csv", usecols=[0, 1, 2], names=range(15))
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-4-6de98b5ea7e5> in <module>
----> 1 pd.read_csv("file_1.csv", usecols=[0, 1, 2], names=range(15))

~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675
--> 676         return _read(filepath_or_buffer, kwds)
    677
    678     parser_f.__name__ = name

~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    452
    453     try:
--> 454         data = parser.read(nrows)
    455     finally:
    456         parser.close()

~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
   1131     def read(self, nrows=None):
   1132         nrows = _validate_integer("nrows", nrows)
-> 1133         ret = self._engine.read(nrows)
   1134
   1135         # May alter columns / col_dict

~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
   2035     def read(self, nrows=None):
   2036         try:
-> 2037             data = self._reader.read(nrows)
   2038         except StopIteration:
   2039             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()

ParserError: Too many columns specified: expected 15 and found 3
```

</details>

**Comment by jakepu** [comment]
> 
> 
> Thanks for raising an issue @jakepu. It looks like values for `usecols` and `names` are inconsistent (one is length 6 and one is length 15). Using the following CSV file with Pandas:
> 
> ```
> foo, bar, baz
> 1, 2, 3
> ```
> 
> I get a similar `ParserError` when the length of `usecols` and `names` don't match (full traceback below). Could you update `usecols` and `names` and try again
> Traceback:
> 
> ```python
> In [4]: pd.read_csv("file_1.csv", usecols=[0, 1, 2], names=range(15))
> ---------------------------------------------------------------------------
> ParserError                               Traceback (most recent call last)
> <ipython-input-4-6de98b5ea7e5> in <module>
> ----> 1 pd.read_csv("file_1.csv", usecols=[0, 1, 2], names=range(15))
> 
> ~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
>     674         )
>     675
> --> 676         return _read(filepath_or_buffer, kwds)
>     677
>     678     parser_f.__name__ = name
> 
> ~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
>     452
>     453     try:
> --> 454         data = parser.read(nrows)
>     455     finally:
>     456         parser.close()
> 
> ~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
>    1131     def read(self, nrows=None):
>    1132         nrows = _validate_integer("nrows", nrows)
> -> 1133         ret = self._engine.read(nrows)
>    1134
>    1135         # May alter columns / col_dict
> 
> ~/miniforge3/envs/dask/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
>    2035     def read(self, nrows=None):
>    2036         try:
> -> 2037             data = self._reader.read(nrows)
>    2038         except StopIteration:
>    2039             if self._first_chunk:
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()
> 
> ParserError: Too many columns specified: expected 15 and found 3
> ```

I tried setting names = range(6) and it still throws the same error.

**Comment by jakepu** [comment]
> 
> 
> You can try to loop through all files one by one with pandas to see if any of them has errors.
> 
> Else if it is ok to skip rows which throws the exception, try using `error_bad_lines=False`. Not sure how it works together with dask though.

I tried what you suggested and pandas can read all of the small txt files without any errors using the following code:
```python
for filename in os.listdir(directory):
    if filename.endswith(".txt"):
        try:
            df = pd.read_csv('./results/'+ filename, sep='|', usecols=[0,1,2,3,4,5],names = range(15), header = None)
        except:
            print(filename)
```
I will try using dask.dataframe to read small files again.

**Comment by jakepu** [comment]
I tried all the combos I can think of over a test.txt with for content:
1|2
1|2|3|4
a|b|c|d|e
f|g|h
I learned that pandas and dask.dataframe have a same behavior with this small file:
1. Without usecols, x can be any number names=range(x)
2. With usecols,  the range of x is [ len(usecols), max(col_size)]

Additionally, I tried using pandas and dask.dataframe to read every file I have in the 190 GB data set and none of them throw an error. The error happens when I try to read in the large data set using glob string as mentioned in my original post. I am convinced that it is a bug in Dask.

**Comment by SultanOrazbayev** [comment]
The fact that `dask.dataframe` can read files individually, but not together suggests that individual files have different numbers of columns. My suggestion would be to print/save the column information for each file that is loaded individually (with pandas or dask.dataframe), that could indicate the problematic file.

**Comment by SultanOrazbayev** [comment]
Not sure if this helps, but it might also be possible to run this (https://github.com/AlexForster/bgpdumpy) on the raw files, implementing some quality controls for the processed data.

**Comment by Twizzledrizzle** [comment]
Also, in my experience, you may have to write a function to clean the csv files individually and save them in a better format, for exempel `to_parquet`. And then use dask on that

Good luck!

**Comment by jakepu** [comment]
After debugging for another day. I think I know where the problem is - the memory is not enough for Dask.
After saving all files to parquets, I tried read_parquet() and ran into decompression error from Snappy telling me my data is invalid. However, when I halved the size of the parquets and run it again, this warning came up a couple times in one run:
`distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting`
`distributed.nanny - WARNING - Restarting worker`
and it has the following error in the end:
```
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-4-d3b39ab4afbf> in <module>
----> 1 df_update.compute()

~/anaconda3/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/anaconda3/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    442         postcomputes.append(x.__dask_postcompute__())
    443 
--> 444     results = schedule(dsk, keys, **kwargs)
    445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    446 

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2680                     should_rejoin = False
   2681             try:
-> 2682                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2683             finally:
   2684                 for f in futures.values():

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1974             else:
   1975                 local_worker = None
-> 1976             return self.sync(
   1977                 self._gather,
   1978                 futures,

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    829             return future
    830         else:
--> 831             return sync(
    832                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    833             )

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1839                             exc = CancelledError(key)
   1840                         else:
-> 1841                             raise exception.with_traceback(traceback)
   1842                         raise exc
   1843                     if errors == "skip":

KilledWorker: ("('read-parquet-cb5c475f1032035e876a58df2f658cea', 777)", <Worker 'tcp://127.0.0.1:41065', name: 2, memory: 0, processing: 1>)
```
I believe the whole problem comes from worker being stopped due to exceeding the memory limit (though I have no idea why, it should be spilled to disk at 70%) and caused some kind inconsistency. Is it because the default setting cannot handle this large size of data? I tried lowering memory_monitor_interval to 50ms in case the monitor missed the working passing the 70% limit but it did not help. @Twizzledrizzle  @SultanOrazbayev @jrbourbeau  Do you mind running my data and debug it? For your information, my desktop has 32 GB ram.

**Comment by SultanOrazbayev** [comment]
How time sensitive is this? I'm not sure that if I run it, the results will be replicable (unless we go full docker on this, which might be over-engineering).

I have the same problem every now and then, and for certain applications you might be better off feeding data to dask in chunks, see "Avoid large partitions" in https://docs.dask.org/en/latest/best-practices.html. So glob your file list and split into chunks of say 10 or 20 and hopefully that will be small enough for memory.

**Comment by Twizzledrizzle** [comment]
What do you want to calculate? If you are running `.compute` without any filters you are loading everything into memory.

Would you rather do something like
`df_update.groupby(x).column.sum.compute`?

**Comment by jakepu** [comment]
> What do you want to calculate? If you are running `.compute` without any filters you are loading everything into memory.
> 
> Would you rather do something like
> `df_update.groupby(x).column.sum().compute()`?

I think you are right. I misunderstood the function. Thank you for pointing it out and I am closing this issue.
