### ISSUE TITLE
map_overlap "meta" keyword argument loses array type info of chunks

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#6493]
**What happened**:
`map_overlap` is inconsistent with `map_blocks` in its handling of the `meta` kwarg. When I use `meta` with `map_blocks` I get what I'd expect (i.e. the output array `_meta` matches, including the reported array type of the dask chunks). 

But when I use `meta` with `map_overlap` then the output array `_meta` attribute doesn't match - the array type of the output dask chunks is reported to be numpy arrays, even when that's not actually the case (see example below).

**What you expected to happen**:
I expected the `_meta` attribute of the output dask array to show that the array chunks are cupy (not numpy)

**Minimal Complete Verifiable Example**:
In a [google colaboratory](https://colab.research.google.com/notebooks/intro.ipynb) notebook you can run:
```python
!pip install git+https://github.com/dask/dask.git

import dask.array as da
import cupy as cp

arr = da.from_array(cp.random.random((10, 10)), chunks=5)

def plus_one(arr):
    return arr + 1

result_1 = arr.map_blocks(plus_one, meta=arr._meta)
result_2 = arr.map_overlap(plus_one, meta=arr._meta, depth=0)

print(type(result_1._meta)) # expect cupy ndarray, this is as expected
# <class 'cupy.core.core.ndarray'>
print(type(result_2._meta)) # expect cupy.ndarray, instead see numpy array reported
# <class 'numpy.ndarray'>
```

**Anything else we need to know?**:

**Environment**:

- Dask version: master branch (2.22.0+8.ge5acf325)
- Python version: 3.6.9
- Operating System: Used a [google colaboratory](https://colab.research.google.com/notebooks/intro.ipynb) notebook (for easier reproducibility)
- Install method (conda, pip, source): pip

**Comment by GenevieveBuckley** [comment]
cc @jakirkham for general awareness

**Comment by jakirkham** [comment]
cc @pentschev

**Comment by pentschev** [comment]
@GenevieveBuckley #6494 should fix this, could you try it out and confirm on your end?

@jakirkham thanks for the ping.

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Comment by GenevieveBuckley** [comment]
Can confirm, https://github.com/dask/dask/pull/6494 fixes the issue.
Thank you @pentschev!
