### ISSUE TITLE
`to_parquet` compression parameter seems to have no effect

### ISSUE THREAD

**Issue by mnicstruwig** [dask/dask#6496]
```python
from dask.distributed import Client
import dask.dataframe as dd
client = Client(n_workers=1)

df = dd.read_parquet('path-to-file.parquet')
df.to_parquet('output.parquet', engine='pyarrow', compression='brotli', parition_on=[col])
```

**What happened**:

Choosing `gzip`, `snappy`, `brotli` or `lz4` compression options had no effect on the size of the created parquet file. In fact, the file created with the `to_parquet` method actually _inflated_ the size by a factor of 3 (from ~7GB to ~20GB). This leads me to suspect that, possibly, no compression is being used somehow? No errors or warnings get raised -- **even if `compression` is set to a nonsensical string**. 

I've tried using both `fastparquet` and `pyarrow` as the engine during writing.

Is there something obvious I'm missing?

**What you expected to happen**:
Expected the various compression settings to have an effect on the size of the output parquet file.

**Anything else we need to know?**:
The various compression settings _do_ appear to have an effect when using `pandas.DataFrame.to_parquet`, as well as when used with the `pyarrow.parquet` library. 

**Environment**:

- Dask version: 2.22.0
- Python version: 3.7.3
- Arrow version: 1.0.0
- Operating System: Manjaro Linux
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for opening this issue! It looks to me like when you use `partition_on` the `compression` option doesn't make it all the way through to the pyarrow command. Specifically, `compression` is missing here:

https://github.com/dask/dask/blob/14c53510a5a58f8eb452c148a97f7813234193d1/dask/dataframe/io/parquet/arrow.py#L78:L78

Here is an example that doesn't throw an error and should:

```python
from dask.datasets import timeseries

ddf = timeseries(freq="1T")
ddf.to_parquet("output.parquet", engine="pyarrow", partition_on=["name"], compression="foo")
```

**Comment by mnicstruwig** [comment]
Thanks for the quick response!

I'm not familiar with the `dask` codebase at all, so excuse my ignorance, but wouldn't you expect the `compression` parameter to be included in the `**kwargs` that get passed in (which doesn't seem to be happening)?

Do the changes on your PR at least throw an error, now that you're explicitly passing the `compression` parameter?

**Comment by jsignell** [comment]
> wouldn't you expect the compression parameter to be included in the **kwargs that get passed in

Yeah that is what my PR does. It makes sure the compression is passed down to the inner function in the kwargs.

> Do the changes on your PR at least throw an error 

Yeah the changes in my PR throw an error. If you want to try out the branch you can let me know if it behaves as expected for you.
