### ISSUE TITLE
map_overlap produces duplicate rows when using groupby.rolling on datetime index

### ISSUE THREAD

**Issue by nrcjea001** [dask/dask#6498]
**What happened**: My goal is to perform a groupby rolling sum on a datetime index. I used the map_overlap function and the resulting series contained duplicate rows for some groups and other groups were missing altogether.

**Minimal Complete Verifiable Example**:

```python
from dask import dataframe as dd
import pandas as pd

# generate pandas df: sample "column1" to be summed by "group1", rolled over "date"
df = pd.DataFrame({"column1": range(600), 'group1': 5*['g'+str(i) for i in range(120)],
                   'date':pd.date_range("20190101", periods=60).repeat(10)})

# set index to date so as to roll by datetime offset.
df = df.set_index('date')

# create dask dataframe, with partitions > 1
ddf = dd.from_pandas(df, npartitions=8)

# rolling groupby using map_overlap
ddf.map_overlap(lambda x: x.groupby('group1').rolling('15D')['column1'].sum(), pd.Timedelta('15D'), 0).compute()

```

**What you expected to happen**: Taking a sample group 'g99' from the above dataframe we observe the following:
```
print(df.loc[df['group1']=='g99'])
            column1 group1
date                      
2019-01-10       99    g99
2019-01-22      219    g99
2019-02-03      339    g99
2019-02-15      459    g99
2019-02-27      579    g99
```
So the rolling sum should produce the following result:
```
group1  date      
g99     2019-01-10      99.0
        2019-01-22     318.0
        2019-02-03     558.0
        2019-02-15     798.0
        2019-02-27    1038.0
```
But instead we got:
```
x=ddf.map_overlap(lambda x: x.groupby('group1').rolling('15D')['column1'].sum(), pd.Timedelta('15D'), 0).compute()
print(x.loc[x.index.get_level_values(0)=='g99'])

group1  date      
g99     2019-01-10      99.0
        2019-01-10      99.0
        2019-01-22     318.0
        2019-01-10      99.0
        2019-01-22     318.0
        2019-01-22     219.0
        2019-02-03     558.0
        2019-02-03     339.0
        2019-02-03     339.0
        2019-02-15     798.0
        2019-02-15     459.0
        2019-02-27    1038.0

# We expected 120 unique groups but only got 100
x.reset_index()['group1'].nunique()
100
```

**Environment**:

- Dask version: 2.22.0
- Python version: 3.8.5.final.0
- Pandas: 1.1.0
- Operating System: Windows 10
- Install method (conda, pip, source): conda (conda-forge)

**Comment by jsignell** [comment]
Thank you for the detailed bug report. I think this workflow was not imagined as a usecase for `map_overlap` but it can probably be made to work. I am wondering if rolling should be added as a method for groupby instead.

**Comment by jsignell** [comment]
I think there is an assumption in `map_overlap` that the index is monotonically increasing. So that probably has to do with the bug you are seeing.

**Comment by nrcjea001** [comment]
Thank you for your response. I think groupby rolling is much needed in dask as I find that it takes a long time to run through large dataframes with pandas only.

**Comment by jsignell** [comment]
Yes that makes sense. Just so you know it might take some time before someone is able to implement that. If you want to try to open a pull request for it you are welcome! 

In the meantime we should probably add a warning that `map_overlap` expects the order of the index to not change. 

You can achieve your desired result by re-sorting the index within the function:

```python
from dask import dataframe as dd
import pandas as pd

# generate pandas df: sample "column1" to be summed by "group1", rolled over "date"
df = pd.DataFrame({"column1": range(600), 'group1': 5*['g'+str(i) for i in range(120)],
                   'date':pd.date_range("20190101", periods=60).repeat(10)})

# set index to date so as to roll by datetime offset.
df = df.set_index('date')

# create dask dataframe, with partitions > 1
ddf = dd.from_pandas(df, npartitions=8)

# rolling groupby using map_overlap
output = ddf.map_overlap(
    lambda x: x.groupby('group1').column1.rolling('15D').sum().sort_index(level=1), 
    pd.Timedelta('15D'), 
    0).compute()

output['g99']
```

**Comment by jsignell** [comment]
Ah turns out there is already a warning in the docs: 

> Note that the index and divisions are assumed to remain unchanged.

From: https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_overlap

I am going to close this, but if you have a suggestion for how to raise a more informative error, or if you want to implement groupby.rolling, please open a pull request!
