### ISSUE TITLE
list(DataFrame) triggers computation

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#6513]
I thought I fixed this in https://github.com/dask/dask/pull/5719/, but apparently not. That ensured that we had the correct result, but the implementation still triggers `len` unnecessarily.

Anyway, `list(DataFrame)` is triggering many `len` + `getitem` tasks.

I'm not immediately sure what's going on. `DataFrame.__iter__` is definitely returning `iter(self._meta)`. I know that Python tries really hard to make things iterable by implementing it as `len` + `getitem`, but I thought that was only if the object didn't implement its own `__iter__`? Will look more later.

(@hugobowne this is one of the things that bit me in the live demo 😄)

**Comment by hugobowne** [comment]
thanks for pinging me, Tom! This is awesome as I think it's the first issue discovered in one of our livestreams :) (hi, @mrocklin)

**Comment by TomAugspurger** [comment]
TIL: https://www.python.org/dev/peps/pep-0424/. The tldr is that even for classes that define `__iter__`, `list(obj)` will still call `len`. The interesting thing is that it's *just* for `list(obj)`. Things like `iter(obj)` just directly call `obj.__iter__`.

```python
In [30]: class Foo:
    ...:     def __init__(self, x):
    ...:         self.x = x
    ...:     def __iter__(self):
    ...:         print("iter")
    ...:         return iter(self.x)
    ...:     def __getitem__(self, i):
    ...:         print("getitem")
    ...:         return self.x[i]
    ...:     def __len__(self):
    ...:         print("len")
    ...:         return len(self.x)
    ...:

In [31]: f = Foo([1, 2, 3])

In [32]: iter(f)
iter
Out[32]: <list_iterator at 0x119637610>

In [33]: list(f)
len
iter
len
Out[33]: [1, 2, 3]
```

Unfortunately, we can't just implement `__length_hint__`. That's implemented (and documented) as calling `len` first and falling back to `__length_hint__` when that fails.

So, we're left with a choice

1. Deprecate `DataFrame.__len__`, implement `__length_hint__`, support `list(df)` returning the columns
2. Document that you should avoid the pattern `list(df)` to get the columns for reasons beyond our control.

I'm leaning towards option 2 right now since I'm hopeful that someday we can support fast `DataFrame.__len__` for storage formats that support it (parquet).

**Comment by TomAugspurger** [comment]
Looking a bit more, I don't see a great place in the docs for this. It could maybe go in a best practice ("Don't call `list(df)` to get the columns), but I think this is too narrow an edge case to warrant an entry in the best practices. Hopefully this issue will help out users confused about why `list(df)` is triggering computation.
