### ISSUE TITLE
Atomicity in Dask's Published Datasets

### ISSUE THREAD

**Issue by chinmaychandak** [dask/dask#6531]
I am trying out Dask's [Published Datasets](https://distributed.dask.org/en/latest/publish.html) functionality and so far everything works really well. Below are the functions I'm using to retrieve a published dataset and to publish/re-publish a new dataset.

```
# Get a published dataset 
def get_published_dataset(key):
    client_x = Client("localhost:8786")
    datasets = client_x.list_datasets()
    res = None
    if key in datasets:
        res = client_x.get_dataset(key)
        client_x.close()
    return res

# Publish a dataset, either by creating a new one or by overriding/updating an existing one
def publish_dataset(res, key):
    client_x = Client("localhost:8786")
    datasets = client_x.list_datasets() 
    if key in datasets:
        client_x.unpublish_dataset(key)
    client_x.publish_dataset(res, name=key)
    client_x.close()
```

I had a couple of questions here:
1. In `get_published_dataset()`, would it make sense for the `client.get_dataset(key)` to return `None` if the specific dataset isn't existent? This would help remove the explicit check.
2. My pipeline requires me to "update" existing datasets using the same key, so that my downstream apps can always know which latest dataset to process. Currently, in `publish_dataset()`, this first requires an `client.unpublish_dataset(key)` and then `client.publish_dataset(res, name=key)` which does not have transactional atomicity, i.e., if unpublish succeeds and publish fails for some reason, the downstream apps lose the dataset altogether. Is there a way to add atomicity to this in Dask, maybe a `republish` function that takes care of this like a hashmap?

**Comment by jsmaupin** [comment]
> In get_published_dataset(), would it make sense for the client.get_dataset(key) to return None if the specific dataset isn't existent? This would help remove the explicit check.

Would we need to check for `None` after the fact?

**Comment by chinmaychandak** [comment]
Yes, basically just return `None` rather than throwing an error here: https://github.com/dask/distributed/blob/25d5a33429479459fa0d7765c96ff0c1c3a8f213/distributed/client.py#L2349, if I'm not wrong.

**Comment by mrocklin** [comment]
Well, folks might genuinely want to store None, or might be surprised by trying to get something that they thought was there, but isn't.  

Instead I think a solution that is still robust, but would perhaps give you the convenience that you need is that we follow the Python `dict.get` semantics and raise with a KeyError if the thing is empty *or* we return a default value if provided

```python

In [1]: d = {"x": 1}                                                                                                                                                                                              

In [2]: print(d.get("x", None))                                                                                                                                                                                   
1

In [3]: print(d.get("y", None))                                                                                                                                                                                   
None
```

**Comment by chinmaychandak** [comment]
Makes sense. What kind of checks would the default variable need? Can it be any arbitrary Python object?

Any opinions on how we can achieve the atomic functionality?

**Comment by mrocklin** [comment]
> Makes sense. What kind of checks would the default variable need? Can it be any arbitrary Python object?

This can all be handled Client side.  You just return back to the user whatever they gave to you if the thing isn't there.  I don't see a need to add any rules here.

> Any opinions on how we can achieve the atomic "override" functionality?

I haven't thought about this problem at all, but my gut reaction is to try a `dask.distributed.Lock`.  There may be a more elegant solution somewhere, but that's a hammer that probably works ok for this problem.

**Comment by chinmaychandak** [comment]
> try a dask.distributed.Lock

Would it make sense for the `publish_dataset` method to try using this lock internally in case it needs to override/update the dataset for that specific key? This way we follow the Python `dict` semantics exactly. Or should this be done Client side?

**Comment by mrocklin** [comment]
Yeah maybe, it depends on if we want to change the policy around
overwriting datasets I guess.  I think that @martindurant owned that code
originally, maybe he can speak as to objectives and constraints here.

**Comment by martindurant** [comment]
I don't think re-publishing the same key was considered at the time - it has been a while.

I don't see why overwrite shouldn't be allowed, perhaps requiring an optional kwarg in the client call - this would be passed to the server, so be atomic automatically (no need for lock). 

The dict-like KeyError or default value sounds fine to me.

**Comment by nils-braun** [comment]
I have implemented the changes suggested by @martindurant in the linked PR.

**Comment by chinmaychandak** [comment]
Thank you so much @nils-braun! Really appreciate you jumping on this
