### ISSUE TITLE
using colspecs when loading fixed width data

### ISSUE THREAD

**Issue by BardiaAfshin** [dask/dask#6532]
I'm loading data with pandas such as

pd.read_fwf(file, colspecs...)

^ the above works, but runs out of memory for large files.

I want to use dask to achieve loading this same file, but take advantage of the pyarrow engine ie

dd.read_fwf(file, colspecs...)

^ this fails. My question is , how do you pass in colspecs to dask read_fwf api?

**Comment by mrocklin** [comment]
It looks like dd.read_fwf forwards keywords to pd.read_fwf, have you tried
colspecs=colspecs ?

**Comment by BardiaAfshin** [comment]
no I haven't, I'll give it a go and update.

**Comment by mrocklin** [comment]
Great!  Let us know how it goes

**Comment by jrbourbeau** [comment]
Just checking in, @BardiaAfshin any luck with passing `colspecs` through?

**Comment by jrbourbeau** [comment]
Closing this issue due to lack of response. @BardiaAfshin feel free to re-open if you'd like to continue
