### ISSUE TITLE
Better repartition behavior with npartitions

### ISSUE THREAD

**Issue by kyprifog** [dask/dask#6533]
If you have source files that are not the same size df.repartition doesn't behave in an intuitive way.  For example.   If I specify

```
df.repartition(npartitions=4)
```

where one source file is much smaller than the other you get partitons sizes like this:

```
2020-08-19 12:39:11        622 0.part
2020-08-19 12:39:12        868 1.part
2020-08-19 12:39:22    6779422 2.part
2020-08-19 12:39:22    6785240 3.part
```

This is because the way that dask choses to create partitions is appears to be as a subset from how the source files are originally partitioned (as the documentation for partition_size says npartitions does not compute the byte size of the partitions).  However, this does not appear to be the case when using "partition_size".  In order to get the behavior I would expect npartitions to create I have to repartition twice so that much smaller partitions are created and then combined:

```
df.repartition(partition_size=even_worker_partition_size).repartition(npartitions=4)

2020-08-19 13:00:36    3145730 0.part
2020-08-19 13:00:36    3477110 1.part
2020-08-19 13:00:36    3471711 2.part
2020-08-19 13:00:36    3471601 3.part
```

But has the obvious penatly of having to repartition twice.

**Comment by jsignell** [comment]
If you intend all partitions to be the same size, then it is best to set that explicitly using `partition_size`. To get your desired outcome it would make sense for you to determine the total memory usage of the dataframe and then set the `partition_size` to that divided by the desired number of partitions.

**Comment by kyprifog** [comment]
That would only be true if the on disk size was the same as in memory which isn't the case.

**Comment by jsignell** [comment]
I would expect something like this to work `ddf.repartition(partition_size=ddf.memory_usage(deep=True).sum().compute() // n)`  but it doesn't give preciesly `n` partitions. You might be interested in a similar issue that came up in dask array: https://github.com/dask/dask/pull/6420. Maybe that approach could be expanded for dask dataframe.

**Comment by jrbourbeau** [comment]
Just checking in here, @kyprifog do you have a suggestion for how the current situation could be improved?

**Comment by kyprifog** [comment]
Well, i dont really know.  Ideally it would be better if there were a way to get even partitions without having to repartition twice.   I tried rebalance but had no luck with that approach.  I'll have to spend more time playing around with it.

**Comment by mrocklin** [comment]
The second repartition is relatively cheap.  I don't see an obvious thing to improve here.  I'm going to close this for now.  If there is more to discuss then please chime in and we'll reopen.
