### ISSUE TITLE
Dataframe.set_index docstring might need an update

### ISSUE THREAD

**Issue by Timost** [dask/dask#6539]
**What happened**:

At the time of writting (dask 2.23.0) The `Dataframe.set_index` signature differs from the parameters described in the docstring, it looks like it was originally the `shuffle.py::set_index` docstring but even then it needs an update:
- `drop` parameter is in the signature but not in the doc string
- `other` parameter in the signature corresponds to the `index` parameter in the docstring
- `df` parameter in docstring is actually `self` in the signature
- `compute` in the docstring but actually falls into the `kwargs` parameters
- `**kwargs` parameters could be explained a bit maybe.

**What you expected to happen**:

I would expect the parameter name in the method signature to correspond to the ones in the docstring.

**Minimal Complete Verifiable Example**:

```python
    # method signature
    def set_index(
        self,
        other,
        drop=True,
        sorted=False,
        npartitions=None,
        divisions=None,
        inplace=False,
        **kwargs,
    ):
        """
       ...
        ----------
        df: Dask DataFrame
        index: string or Dask Series
        npartitions: int, None, or 'auto'
        ...
        shuffle: string, optional
        ...
        sorted: bool, optional
        ...
        divisions: list, optional
        ...
        inplace : bool, optional
        ....
        compute: bool
        ...
        Examples
        --------
        ...
        """
```

**Anything else we need to know?**:
I'm willing to update it but I'm not sure what the convention is for documentation in the dask project.

**Environment**:

- Dask version: 2.23.0

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @Timost! Apologies for the delayed response. Indeed, it seems `set_index`'s docstring has gotten out of sync with its signature

>  I'm willing to update it but I'm not sure what the convention is for documentation in the dask project.

Great, thank you! You can check out the Dask contributing docs at https://docs.dask.org/en/latest/develop.html. Specifically, the "Docstrings" and "Contributing to Documentation" will be particularly relevant for this issue

**Comment by Timost** [comment]
Thanks for the pointers @jrbourbeau !  I'll go through the doc and try to improve the doc string.
