### ISSUE TITLE
Column names _0, _1 ... can cause dropna to fail

### ISSUE THREAD

**Issue by goodwanghan** [dask/dask#6540]
**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as pd
import pandas

pdf = pandas.DataFrame([[0,1],[0,2],[None,3]],columns=["_0","_1"])
df=pd.from_pandas(pdf, npartitions=2)
df.dropna(subset=["_0"]).compute()
df.dropna(subset=["_1"]).compute()
```

**What happened**:

It seems _0 _1... have special meanings inside dask, when using these as column names, it causes failures on dropna

**What you expected to happen**:

These are common names, dask should move to some more unique names that people will not use

**Anything else we need to know?**:

dropna without subset will work, ` _0_`, `_1_` ... will work

**Environment**:

- Dask version: 2.23.0
- Python version: 3.6+
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue and providing a nice minimal example @goodwanghan! This is indeed a bug and I've opened up a proposed fix over in https://github.com/dask/dask/pull/6546
