### ISSUE TITLE
Use funds from Tidelift

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask#6544]
Hi,

currently there are funds of [$637.56/month available at Tidelift for Dask development](https://tidelift.com/lifter/search/pypi/dask):

Tidelift offers managed open source to companies and pays maintainers to maintain their software:

> Customizable catalogs of known-good, proactively maintained JavaScript, Python, Java, PHP, Ruby, and .NET components

> Tidelift is the complete platform for building a scalable income stream around your open source work

- What do you think about Tidelift?
- Do you think Dask would benefit from it?
- Where would the funds go?

Here is the [license agreement](https://docs.tidelift.com/article/57-lifter-agreement).

Greetings,
Julian

**Comment by TomAugspurger** [comment]
Thanks. I was in contact with someone from Tidelift, I just need to finish up the paperwork. It's on my todo list.

**Comment by JulianWgs** [comment]
Great! Sorry for the unnecessary issue, couldn't find any info about it.
