### ISSUE TITLE
"Reschedule" problem when using dask

### ISSUE THREAD

**Issue by HaoGao1996** [dask/dask#6545]
When I use dask to do a specific task, the code repeatly reports these two errors:

> distributed.scheduler - ERROR - Couldn't gather keys {"('coarsen-725943cde54ea5b0ed1c1ff43ede5a6f', 25, 42, 0, 0)": ['tcp://172.16.1.3:35651']

> distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://172.16.1.1:39637'], ('coarsen-725943cde54ea5b0ed1c1ff43ede5a6f', 38, 18, 0, 0)

And finnaly, `KilledWorker: ("('delf-from-value-stack-getitem-f9938140a2c4c62be63e8287fa1f1b23', 6, 0, 0, 0)", <Worker 'tcp://172.16.1.2:44985', name: 72-2, memory: 0, processing: 5>)` shows up, which means the code has been killed.

Here is my code: (where `shift_yx` is the linear transformation function of the image)
```
shifts_filt_bc = client.scatter(shifts_filt)

data_rechunked_1 = data.rechunk(chunks=(1, 1, data.shape[2], data.shape[3]))
data_filt = data_rechunked_1.map_blocks(lambda v: median_filter(v, (1,1,5,5)), dtype='float32')

data_tx = data_filt.map_blocks(shift_yx, shifts_filt_bc, dtype='float32')

data_ds = coarsen(np.mean, data_tx, {2: ds_xy, 3: ds_xy}).compute()
```

Then I check the daskboard and find the confused `"reschedule" problem` (I'm not sure whether it's accurate). U can see the continuous screenshots as follows,

### time 1
![image](https://user-images.githubusercontent.com/24383804/91010050-5cddde00-e614-11ea-96ee-361931413048.png)
### time 2
![image](https://user-images.githubusercontent.com/24383804/91010063-6404ec00-e614-11ea-9e43-302bee53e54e.png)

I find the tasks which have already finished are rescheduled to cores.  

Anyone know how to solve that problem?

**Comment by JulianWgs** [comment]
- I think you can use [performance reports](https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports) to better present the information. 
- Please include a minimal pastable example. [Here](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) is a good blog post on how to write a good bug report. 
- Which version of Dask are you using?

**Comment by HaoGao1996** [comment]
@JulianWgs  Thanks for your suggestions. Unfortunately, I cannot provide a minimal pastable example for you after several attempts. It seems to be the problems of hardware in the server cause sometimes I can get the results directly and at the other time it went wrong. In my own opinion, it may be caused by the communication system in our server to transfer intermediate data from a worker to another one.

After checking the performance reports, I referred to the suggestions in [Best Practices](https://docs.dask.org/en/latest/best-practices.html). I try to write 'data_filt ', 'data_tx', and 'data_ds' in a simple function to process a single image:

```python
def downsampling(im, shifts, block_id):
    from scipy.ndimage.interpolation import shift
    from skimage.measure import block_reduce
    
    t = block_id[0]    
    
    im_filt = median_filter(im, (1, 1, 5, 5)).astype('float32')
    im_shift = shift(im_filt, (0, 0, *shifts[t]), order=1, cval=100)
    
    im_ds = block_reduce(im_shift, block_size=(1, 1, 4, 4), func=np.mean)
    
    return im_ds

data_ds = data.map_blocks(downsampling, shifts, dtypy=‘float32’)
```

After doing that, our code can work well without such errors in most cases. 

**Environment**

- Dask version: 2.21.0
- Python version: 3.7.0
- Operation System: Linux
