### ISSUE TITLE
Rechunking from short-fat to tall-skinny 

### ISSUE THREAD

**Issue by eric-czech** [dask/dask#6552]
I'm trying to understanding why this kind of rechunking isn't possible (on a machine w/ 128G RAM):

```python
x = da.random.random(size=(1_000, 100_000_000), chunks=(10, -1))
x.blocks[0, 0].nbytes // int(1e6) # 8000 MB chunks
x.mean().compute()  # This takes most of the memory but works after a couple minutes

y = x.rechunk((100, 100_000))
y.blocks[0, 0].nbytes // int(1e6) # 80 MB chunks (1% of the original chunk size)
y.mean().compute()  # This instantly runs out of memory
```

More generally, I have an array with very short and wide chunks that I would like to rechunk with something closer to square chunks (or tall-skinny as a more extreme example).  My guess at how this is working is:

1. Start with 10 rows x 100M col chunks
2. Define rechunk to 100 rows (and an arbitrarily small number of columns)
3. Load 10 chunks each with shape 10 rows x 100M cols into memory to create a huge array of shape (100, 100M)
4. Split the big array so the new chunks align to the requested chunks in the cols dimension

My question then is, is there a way to do rechunk short-fat chunks to tall-skinny ones that doesn't require that giant intermediate array?

I'm sure that's a reductive guess at what really happens, but I can't seem to find a way to do this without writing the results out to disk first.  I wanted to confirm that there isn't a more elegant solution.

**Comment by mrocklin** [comment]
y = x.rechunk((100, 100_000))

So you're going to need ten of the 8GB chunks in memory before you can make one of these chunks and release any of the previous generation.  

This should be fine (you have just enough RAM), but if you have a lot of threads doing this at once then they might try to work on many chunks at once, which might blow things up.  So you could try using the single-threaded scheduler with `compute(scheduler="single-threaded")`

The Pangeo folks also ran into this issue and made a package for it.  See https://medium.com/pangeo/rechunker-the-missing-link-for-chunked-array-analytics-5b2359e9dc11

**Comment by eric-czech** [comment]
Well, well thanks @mrocklin!  Rechunker sounds like exactly what I'm looking for.
