### ISSUE TITLE
Does dask array support partial graphs?

### ISSUE THREAD

**Issue by emilmelnikov** [dask/dask#6553]
I would like to use dask arrays as block "containers":

```python
import dask
import numpy
from dask.highlevelgraph import HighLevelGraph


dtype = numpy.dtype("uint8")
dsk = {
    ("spam", 0, 0): (numpy.full, (2, 2), 1, dtype),
    ("spam", 1, 1): (numpy.full, (2, 2), 2, dtype),
}
hlg = HighLevelGraph.from_collections("spam", dsk)
chunks = ((2, 2), (2, 2))
meta = dask.array.core.meta_from_array(None, len(chunks), dtype)

# It is possible to create a dask array from incomplete graph.
a = dask.array.Array(hlg, "spam", chunks, dtype=dtype, meta=meta)

# Mapping over blocks works.
b = a.map_blocks(lambda x: 10 * x)

# Computing the result doesn't work, for obvious reasons.
# b.compute()

# Individual blocks still work.
b.blocks[0, 0].compute()
# array([[10, 10],
#        [10, 10]], dtype=uint8)

# Surprisingly, missing blocks also work.
b.blocks[0, 1]
# dask.array<blocks, shape=(2, 2), dtype=uint8, chunksize=(2, 2), chunktype=numpy.ndarray>

# Trying to compute a missing block raises an exception.
# b.blocks[0, 1].compute()
```

Is this usage pattern supported and/or recommended? If yes, it would be great to see 1-2 paragraphs about it in the docs, and maybe some notes on which operations work and which don't.

Of course it is possible to do this manually, but dask already contains a lot of wonderful machinery for doing similar work.

N.B. My main motivation for doing this is to avoid creating large graphs: I need to handle very large datasets, but can only use small block sizes.

**Comment by TomAugspurger** [comment]
IMO it's a bit hard to say. In the sense that a Dask task graph is just a dictionary of tuples, then yes this should continue to work just fine (just don't ask for the "missing" keys). Beyond that I'm less sure.

> My main motivation for doing this is to avoid creating large graphs: I need to handle very large datasets, but can only use small block sizes.

Are you able to use high-level graphs to represent your operations? Or is storing even one reference to all the chunks prohibitive? Regardless, you might be interested in https://blog.dask.org/2020/07/21/faster-scheduling and related issues (https://github.com/dask/dask/issues/6438).

**Comment by emilmelnikov** [comment]
> Are you able to use high-level graphs to represent your operations? Or is storing even one reference to all the chunks prohibitive?

I'm afraid we cannot afford to generate chunks for the entire array because we need ~128KB chunks, while the array could be arbitrarily large. The reason for such a small chunk size is to be able to quickly compute a small number of these chunks and functions on them. Here is a rough sketch of what do we want to do:

```python
# Create a dask array from a huge dataset.
# This alone generates a very large graph of size N.
a = da.from_zarr("1TB-dataset.zarr", chunks=(512, 512))["dataset"]

# Compute some expensive transformations on the input dataset.
# This generates at least another K*N nodes.
xs = [f(a) for f in expensive_transform_funcs]

# Now we want to compute only 4 chunks from the entire dataset.
# This is the desired result.
# Note that if chunks were much larger than (512, 512),
# we would be wasting a lot of unnecessary compute.
ys1 = dask.compute(x[:1024, :1024] for x in xs])

# After some time, we might want to compute
# a small number of totally different chunks.
ys2 = dask.compute(x[10000:11000, 100:200] for x in xs]) 
```

> Regardless, you might be interested in https://blog.dask.org/2020/07/21/faster-scheduling and related issues (#6438).

Thanks, the high-level graph optimisations look very interesting! Do you think they could be applied for the use case above?

**Comment by mrocklin** [comment]
> Thanks, the high-level graph optimisations look very interesting! Do you
think they could be applied for the use case above?

Yes

**Comment by emilmelnikov** [comment]
Thanks!
