### ISSUE TITLE
Flag for raising an error when `normalize_object` doesn't find `__dask_tokenize__`

### ISSUE THREAD

**Issue by STOpandthink** [dask/dask#6555]
I ran into a bit of a nasty surprised when I realized some of my Delayed objects resulted in a different token when I called `tokenize()`. This is because in my data I had some objects which didn't have `__dask_tokenize__`. I fixed those errors, but I'm afraid they might come up again silently. It would be amazing if I could set a flag that would raise an error any time that I tried to tokenize something which contained anything that couldn't be tokenized deterministically. I'm thinking something in `dask.base.normalize_object` that raises an error instead of returning `uuid.uuid4().hex`.

Thanks!

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @STOpandthink! I can imagine this was tedious to track down. Adding a config option to raise an error or warn when falling back to a random token (which is `False` by default) seems like a nice addition for certain use cases. Is this something you're interested in working on? (no obligation though)

**Comment by hristog** [comment]
Hi @jrbourbeau, could you please elaborate on the "config option" part?
I suppose, based on the wording, you're referring to something other than a flag that's passed to a particular function or set of functions.

**Comment by jrbourbeau** [comment]
Dask has it's own [configuration system](https://docs.dask.org/en/latest/configuration.html) that let's user customize some of Dask's behavior (e.g. logging verbosity). The proposal here is to add a new configuration option that controls if users are informed when [`dask.base.normalize_object`](https://github.com/dask/dask/blob/1767fedd2f0662ba2fd6a9caebf2d3595ca8046c/dask/base.py#L838) isn't able to return a deterministic result and falls back to returning a [random `uuid`](https://github.com/dask/dask/blob/1767fedd2f0662ba2fd6a9caebf2d3595ca8046c/dask/base.py#L842).

**Comment by hristog** [comment]
Thanks, @jrbourbeau! I've created https://github.com/dask/dask/pull/7413 to address this.
I've opted to not going for an overkill and adding analogous handling of other instances of fallbacks to `uuid.uuid4().hex`, elsewhere in `dask/base.py` (e.g., [here](https://github.com/dask/dask/blob/1767fedd2f0662ba2fd6a9caebf2d3595ca8046c/dask/base.py#L822) and [here](https://github.com/dask/dask/blob/1767fedd2f0662ba2fd6a9caebf2d3595ca8046c/dask/base.py#L1006)), because it hasn't been specifically requested.
