### ISSUE TITLE
Add more guidance on working with Parquet files to documentation

### ISSUE THREAD

**Issue by MrPowers** [dask/dask#6556]
Parquet column pruning & parquet predicate pushdown filters can speed up some analyses 100x or more.  These wonderful features are supported by Dask and some prose will help users understand how to leverage these features.

We could add a section to the [Best Practices](https://docs.dask.org/en/latest/best-practices.html) or add a File Formats section to Help and Reference.  Let me know if you'd think this would help and I can submit a pull request with a writeup.

Thanks for building this great project.

**Comment by jrbourbeau** [comment]
Glad to hear you've found these optimizations to be useful @MrPowers! 

Adding some prose to the ["Store Data in Apache Parquet Format" best practice section](https://docs.dask.org/en/latest/dataframe-best-practices.html#store-data-in-apache-parquet-format) seems like a reasonable place. What do you think? Additionally, if you have an example showing off the power of column pruning & predicate pushdown and want to add it to https://github.com/dask/dask-examples, that would also be welcome

For some additional context, these type of optimizations are part of an ongoing effort to expand high-level graphs optimizations for Dask collections (xref https://github.com/dask/dask/issues/5644)

**Comment by MrPowers** [comment]
Added [a blog post here](https://coiled.io/parquet-column-pruning-predicate-pushdown/) on how to use column pruning and Parquet predicate pushdown filtering which can at least give users Googleable results if they're looking for the syntax 🤓
