### ISSUE TITLE
Exclude git commit from docs links

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#6557]
https://twitter.com/naivebayesian/status/1295669510435815424

![image](https://user-images.githubusercontent.com/306380/91237857-8a985500-e6f0-11ea-8cc3-f60c344b2fff.png)

cc @TomAugspurger @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Given that we do not version our documentation (we just have `stable` and `latest`) it probably makes sense to remove this from the page title.

It is interesting that Google is ranking the `latest` docs above the `stable` docs.

We may want to look into this as if you inspect the source of the [`stable` docs](https://docs.dask.org/en/stable/dataframe.html) it seems to be setting `latest` as the canonical URL.

```html
<link rel="canonical" href="https://docs.dask.org/en/latest/dataframe.html" />
```

I would suggest that `stable` should be the default and canonical URL as it will be the documentation for the current release. Where `latest` is the documentation for the tip of the main branch.

Perhaps something to discuss in the community meeting?

**Comment by mrocklin** [comment]
Personally I'm fine with either.  I'd also be fine dropping the
latest/stable distinction.  We've only had a couple of reported cases where
someone got burned by looking at latest and not finding functionality that
was in the latest release.

**Comment by mrocklin** [comment]
We've merged in the change for Dask.   Here is a more sweeping change in dask-sphinx-layout.

https://github.com/dask/dask-sphinx-theme/pull/40

This seems fine to me, but I'm also happy to pull things back a bit if desired.
