### ISSUE TITLE
Wrong path when reading empty csv file

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask#6561]
```python

import dask.dataframe as dd

for k, content in enumerate(["0, 1, 2", "3, 4, 5", "6, 7, 8"]):
    with open(str(k) + ".csv", "w") as file:
        file.write(content)

print(dd.read_csv("*.csv",  include_path_column=True, names=["A", "B", "C"],).compute())
print()

# The second file is empty
for k, content in enumerate(["0, 1, 2", "", "6, 7, 8"]):
    with open(str(k) + ".csv", "w") as file:
        file.write(content)

print(dd.read_csv("*.csv",  include_path_column=True, names=["A", "B", "C"],).compute())

```

returns:

```
   A  B  C    path
0  0  1  2    0.csv
0  3  4  5    1.csv
0  6  7  8    2.csv

   A  B  C    path
0  0  1  2    0.csv
0  6  7  8    1.csv  # <- This is wrong and should be "2.csv"

```

**Environment**:

- Dask version: 2.19.0
- Python version: 3.8.3
- Operating System: Windows 10
- Install method (conda, pip, source): Anaconda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @JulianWgs, I'm able to reproduce on the current development version of Dask and can confirm this is a bug. Is this something you're interested in looking into more? (no obligation though)

**Comment by quasiben** [comment]
I think what is happening here is that blocks will look like the following:

> [[Delayed('read-block-0-217e6e7550017caad19382e07bcec157')], [], [Delayed('read-block-0-3df2b8124f02524ab7b4eb76b9822d31')]]

And eventually the empty list is dropped: https://github.com/dask/dask/blob/51509339c1cc476f5f96ae78e61daf125037ca20/dask/dataframe/io/csv.py#L325

Previously when building up the list of paths: https://github.com/dask/dask/blob/51509339c1cc476f5f96ae78e61daf125037ca20/dask/dataframe/io/csv.py#L482-L487 we don't update the paths for the upcoming flattening step

**Comment by JulianWgs** [comment]
Great, that you could reproduce it. Sorry, I don't have the time right now :/

**Comment by jrbourbeau** [comment]
No worries! @quasiben has done a great job tracking down the root cause of this issue, which will help whenever someone picks this up
