### ISSUE TITLE
dd.read_sql_table could calculate npartitions even if meta is defined

### ISSUE THREAD

**Issue by McToel** [dask/dask#6569]
I think there is no real reason not to calculate npartitions if meta is defined. You could just get the head rows anyways and not infer the data types from there if meta is defined.
And when we are on it, we could generally get the data types from sqlalchemy's python_type function.

**Comment by TomAugspurger** [comment]
cc @martindurant if you have thoughts here.

**Comment by martindurant** [comment]
Sure, it would be reasonable to get the first few rows for the purpose of estimating the bytes/row. In fact, this might be exactly known when the meta is provided, if it contains only primitive types (no objects/strings).

> we could generally get the data types from sqlalchemy's python_type function

Would this be more explicit or exact than using pandas' inference?

**Comment by McToel** [comment]
> Would this be more explicit or exact than using pandas' inference?
If you have a lot of NaNs in your data it can help, as there might only be NaNs in the head rows which may result in a wrong datatype or no NaNs in an integer column which results in the usage of pd.int64 which crashes read_sql_table as soon as there is a NaN Value in that column.
Both problems could be fixed by getting the type the database uses. This could probably be addressed in pandas as well. It just happened that I never had problems with datatypes there as pandas always gets the full table to evaluate the types.

**Comment by martindurant** [comment]
I'd be happy to see this in code.

**Comment by McToel** [comment]
Do you mean how to reproduce this or a fix for it?

**Comment by martindurant** [comment]
I mean a PR with your suggestion - of using bytes/row with meta and type inference without meta - implemented. It would be nice to have tests for the various different argument combinations, of which there would be quite a few.

**Comment by McToel** [comment]
I made a PR with the implementation and new tests #6585
