### ISSUE TITLE
Officially Supported Python Version (documentation)

### ISSUE THREAD

**Issue by jrdzha** [dask/dask#6576]
I'm looking into upgrading our stack to Python 3.9, and am looking at Dask's [documentation](https://docs.dask.org/en/latest/develop.html) to see official support, but it seems like it may be out of date. The last supported Python version is listed as 3.7, but I was able to find a PR for 3.8 support. #5603

> Dask supports Python versions 3.5, 3.6, and 3.7. Name changes are handled by the dask/compatibility.py file.

**Comment by mrocklin** [comment]
Right.   We should definitely add 3.8 to that list.

To my knowledge no one has looked into 3.9 yet, but that would be welcome
if anyone wants to give it a shot.

Probably the way to do this is to open up a PR that adds a 3.9 entry to
CI.  If it passes then we should update docs again and add 3.9 to the
setup.py declarations.
