### ISSUE TITLE
Unable to read String.io buffer though read_csv.

### ISSUE THREAD

**Issue by rishavpathania1995** [dask/dask#6577]
Trying to read StringIO csv buffer not getting following error.

`TypeError: Path should be a string, os.PathLike, list or tuple`

Code:
`self.DATAFRAME = dd.read_csv(self.CSV_STREAM, usecols=self.COLUMN_NUMBER, cache_dates=True,names=self.COLUMN_NAME).set_index("Time")`

**Comment by rishavpathania1995** [comment]
i can read through pandas first and then convert to dask dataframe,but its take time when csv_stream is big .

**Comment by TomAugspurger** [comment]
Thanks, can you include a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rishavpathania1995** [comment]
```
import io
import dask
import dask.dataframe as dd
dask.config.set(scheduler='threads')

csv_stream = io.StringIO()

row = "1,2,3,4,5,6,7,8"

csv_stream.write(row)
csv_stream.seek(0)

'''
#Required solution
df = dd.read_csv(csv_stream)
'''

'''
giving error 
TypeError: Path should be a string, os.PathLike, list or tuple
'''


## Workaround
df = pd.read_csv(csv_stream)
DATAFRAME = dd.from_pandas(df, npartitions=2)
print(DATAFRAME.compute())

```

**Comment by rishavpathania1995** [comment]
when stream is large say 1GB , then pandas takes lot of time to read.
need dask to read StringIO  directly.
Main usage will be when try to read from cloud machines or some uncompressed objects.

**Comment by TomAugspurger** [comment]
> when stream is large say 1GB , then pandas takes lot of time to read.
> need dask to read StringIO directly.

Can you read from a StringIO object in parallel? My guess is no, since I'd assume you can't do concurrent random access. If we can't read it in parallel then dask won't be any faster than pandas.

**Comment by SultanOrazbayev** [comment]
Just to add on a potential use-case for this is for writing small code snippets for tutorials, demos, but not for end-use cases. For example, right now, if I want to write a demo like in the first snippet [here](https://coiled.io/blog/dask-dataframe-to-numeric-object-to-float/), then I will have to import pandas and create dask dataframe via pandas. 

However, it would also be cool to write a snippet that doesn't use `pandas` as an intermediate object, e.g. the first snippet in the link above would look like:

```
from io import StringIO

data = StringIO(
    """nums,letters
1,a
2.8,b
3,c
4,d
hi,e
6,f"""
)

# # currently this will fail
# from dask.dataframe import read_csv
# df = read_csv(data, npartitions=2)

# this will work
from pandas import read_csv as read_csv_pandas

df = read_csv_pandas(data)
```
