### ISSUE TITLE
read_csv with include_path_column fails when csv file size exceeds blocksize

### ISSUE THREAD

**Issue by dwr-psandhu** [dask/dask#6581]
**What happened**:
The snippet below (thanks @TomAugspurger) fails if any csv file is greater than default blocksize
```
In [14]: df = pd.DataFrame({"A": [1] * 1000})

In [15]: ddf = dd.from_pandas(df, 2)

In [16]: ddf.to_csv("data-*.csv")
Out[16]:
['/Users/taugspurger/sandbox/dask/dask-examples/data-0.csv',
 '/Users/taugspurger/sandbox/dask/dask-examples/data-1.csv']

In [17]: ddf2 = dd.read_csv("data-*.csv", blocksize="1KB", include_path_column=True)

In [18]: ddf2.compute()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-616dd9b063d3> in <module>
----> 1 ddf2.compute()

~/sandbox/dask/dask/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169

~/sandbox/dask/dask/dask/base.py in compute(*args, **kwargs)
    444     )
    445
--> 446     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    447     keys, postcomputes = [], []
    448     for x in collections:

~/sandbox/dask/dask/dask/base.py in collections_to_dsk(collections, optimize_graph, **kwargs)
    216             dsk, keys = _extract_graph_and_keys(val)
    217             groups[opt] = (dsk, keys)
--> 218             _opt = opt(dsk, keys, **kwargs)
    219             _opt_list.append(_opt)
    220

~/sandbox/dask/dask/dask/dataframe/optimize.py in optimize(dsk, keys, **kwargs)
     19         dsk = fuse_roots(dsk, keys=flat_keys)
     20
---> 21     dsk = ensure_dict(dsk)
     22
     23     if isinstance(keys, list):

~/sandbox/dask/dask/dask/utils.py in ensure_dict(d)
   1030             dd_id = id(dd)
   1031             if dd_id not in seen:
-> 1032                 result.update(dd)
   1033                 seen.add(dd_id)
   1034         return result

~/sandbox/dask/dask/dask/dataframe/io/csv.py in __getitem__(self, key)
     79
     80         if self.paths is not None:
---> 81             path_info = (self.colname, self.paths[i], self.paths)
     82         else:
     83             path_info = None

IndexError: list index out of range
```

**What you expected to happen**:
It should be able to read the files irrespective of individual file sizes being greater than block size
**Minimal Complete Verifiable Example**:

```python
# try this on csv files exceeding 1M 
dd=dask.dataframe.read_csv('*.csv',include_path_column=True,blocksize='1M') 

dd.compute()
```

**Anything else we need to know?**:
Workaround is to use blocksize greater than any file(s) being read.

**Environment**:

- Dask version: '2.23.0'
- Python version: '3.7.x'
- Operating System: 'Windows'
- Install method (conda, pip, source): 'conda'

**Comment by TomAugspurger** [comment]
Thanks for the report. Here's a full reproducer, including data generation. Could you edit your original post to include it?

```python
In [14]: df = pd.DataFrame({"A": [1] * 1000})

In [15]: ddf = dd.from_pandas(df, 2)

In [16]: ddf.to_csv("data-*.csv")
Out[16]:
['/Users/taugspurger/sandbox/dask/dask-examples/data-0.csv',
 '/Users/taugspurger/sandbox/dask/dask-examples/data-1.csv']

In [17]: ddf2 = dd.read_csv("data-*.csv", blocksize="1KB", include_path_column=True)

In [18]: ddf2.compute()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-616dd9b063d3> in <module>
----> 1 ddf2.compute()

~/sandbox/dask/dask/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169

~/sandbox/dask/dask/dask/base.py in compute(*args, **kwargs)
    444     )
    445
--> 446     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    447     keys, postcomputes = [], []
    448     for x in collections:

~/sandbox/dask/dask/dask/base.py in collections_to_dsk(collections, optimize_graph, **kwargs)
    216             dsk, keys = _extract_graph_and_keys(val)
    217             groups[opt] = (dsk, keys)
--> 218             _opt = opt(dsk, keys, **kwargs)
    219             _opt_list.append(_opt)
    220

~/sandbox/dask/dask/dask/dataframe/optimize.py in optimize(dsk, keys, **kwargs)
     19         dsk = fuse_roots(dsk, keys=flat_keys)
     20
---> 21     dsk = ensure_dict(dsk)
     22
     23     if isinstance(keys, list):

~/sandbox/dask/dask/dask/utils.py in ensure_dict(d)
   1030             dd_id = id(dd)
   1031             if dd_id not in seen:
-> 1032                 result.update(dd)
   1033                 seen.add(dd_id)
   1034         return result

~/sandbox/dask/dask/dask/dataframe/io/csv.py in __getitem__(self, key)
     79
     80         if self.paths is not None:
---> 81             path_info = (self.colname, self.paths[i], self.paths)
     82         else:
     83             path_info = None

IndexError: list index out of range

```

Are you interested in working on this? The logic around `self.paths` will need to be updated to handle the fact that there's not necessarily a 1:1 relationship between partition number and path.

**Comment by dwr-psandhu** [comment]
@TomAugspurger I am new to this project and will need some guidance. I am willing to try to fix it.

**Comment by TomAugspurger** [comment]
Thanks. The logic in
https://github.com/dask/dask/blob/0ca1607aa14cb81520ca9526f871b631fe6706fa/dask/dataframe/io/csv.py#L332-L339
looks wrong. Path is set to something the length of the number of paths,
while it should (perhaps) be the number of blocks. block_file_names looks
to be the right shape.

**Comment by DavidKatz-il** [comment]
Hi @TomAugspurger 
I try to take a look at this issue.

When running this code:
```
        block_file_names = [basename(b[1].path) for b in blocks]
        path = (
            path[0],
            [p for p in path[1] if basename(p) in block_file_names],
        )

        colname, paths = path
```   
`paths` stores the folowing list ['/full/path/to/file/data-0.csv', '/full/path/to/file/data-1.csv'], and its failed with the above exception.

When I tried to follow your suggests I change the code to:
```
        basename_path = {basename(p): p for p in path[1]}
        block_file_names = [basename(b[1].path) for b in blocks]
        path = (
            path[0],
            [basename_path[p] for p in block_file_names],
        )
```
now `paths` stores the folowing list ['/full/path/to/file/data-0.csv', '/full/path/to/file/data-0.csv', '/full/path/to/file/data-0.csv', '/full/path/to/file/data-1.csv',  '/full/path/to/file/data-1.csv', '/full/path/to/file/data-1.csv', '/full/path/to/file/data-1.csv'], 
but it failed [on](https://github.com/dask/dask/blob/0ca1607aa14cb81520ca9526f871b631fe6706fa/dask/dataframe/io/csv.py#L342-L343) with `ValueError: Categorical categories must be unique`.

`block_file_names` stores the folowing list ['data-0.csv',  'data-0.csv', 'data-0.csv', 'data-1.csv', 'data-1.csv', 'data-1.csv', 'data-1.csv'] on both situations.

**Comment by TomAugspurger** [comment]
You'll need the unique paths on the line you gave. You could take a couple
options

1. Call pd.unique on `paths` on that line you linked to.
2. Store `paths` as a dict / Categorical earlier on, and index into it.

Whichever sounds easiest is fine.

**Comment by DavidKatz-il** [comment]
When calling np.unique on `paths` it's still failed on `compute` with the following error:
```python
raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique
```
When I change `paths` in [the following section](https://github.com/dask/dask/blob/0ca1607aa14cb81520ca9526f871b631fe6706fa/dask/dataframe/io/csv.py#L158-L163) the code dosn't fail.
```python
if path:
    colname, path, paths = path
    code = paths.index(path)
    paths = [i if i != code else paths[code] for i in range(len(paths))]
    df = df.assign(
       **{colname: pd.Categorical.from_codes(codes=np.full(len(df), code), categories=paths)}
    )
```

**Comment by DavidKatz-il** [comment]
> When calling np.unique on `paths` it's still failed on `compute` with the following error:
> 
> ```python
> raise ValueError("Categorical categories must be unique")
> ValueError: Categorical categories must be unique
> ```
> 
> When I change `paths` in [the following section](https://github.com/dask/dask/blob/0ca1607aa14cb81520ca9526f871b631fe6706fa/dask/dataframe/io/csv.py#L158-L163) the code dosn't fail.
> 
> ```python
> if path:
>     colname, path, paths = path
>     code = paths.index(path)
>     paths = [i if i != code else paths[code] for i in range(len(paths))]
>     df = df.assign(
>        **{colname: pd.Categorical.from_codes(codes=np.full(len(df), code), categories=paths)}
>     )
> ```

This change doesn't pass this [test](https://github.com/dask/dask/blob/master/dask/dataframe/io/tests/test_csv.py#L1569:L1589), So I make the following changes:
``` python
    if path:
        colname, path, paths = path
        paths = list(set(paths))
        code = paths.index(path)
        df = df.assign(
            **{colname: pd.Categorical.from_codes(codes=np.full(len(df), code), categories=paths)}
        )
```
But the ```assert_eq(result, df, check_index=False)``` is still failing with:
``` python
DataFrame.iloc[:, 3] (column name="path") category.categories values are different (100.0 %)
[left]:  Index(['2.csv', '0.csv'], dtype='object')
[right]: Index(['0.csv', '2.csv'], dtype='object')
```
This is how the data frames look in the test before calling `assert_eq`:
``` python
>>> df
Out[7]: 
   A  B  C   path
0  0  1  2  0.csv
1  6  7  8  2.csv
>>> result
Out[8]: 
   A  B  C   path
0  0  1  2  0.csv
0  6  7  8  2.csv
>>> df.path
Out[9]: 
0    0.csv
1    2.csv
Name: path, dtype: category
Categories (2, object): ['0.csv', '2.csv']
>>> result.path
Out[10]: 
0    0.csv
0    2.csv
Name: path, dtype: category
Categories (2, object): ['2.csv', '0.csv']

```
It seems that we need to ignore the check on the index or ignore the order of the values in the index.

@TomAugspurger how should I proceed?

**Comment by TomAugspurger** [comment]
> When calling np.unique on paths it's still failed on compute with the following error:

Can you try `pd.unique`? `np.unique` sorts, while pandas' doesn't. Hopefully that solves both requirements?

**Comment by DavidKatz-il** [comment]
> Can you try `pd.unique`? `np.unique` sorts, while pandas' doesn't. Hopefully that solves both requirements?      

`pd.unique` didn't solve the problem with `test_reading_empty_csv_files_with_path()`.
The issue comes from here:

> ```python
>     if path:
>         colname, path, paths = path
>         paths = list(set(paths))
>         code = paths.index(path)
>         df = df.assign(
>             **{colname: pd.Categorical.from_codes(codes=np.full(len(df), code), categories=paths)}
>         )
> ```

When I changed `paths = list(set(paths))` to `paths = sorted(set(paths))` the test was succeeded.

**Comment by jsignell** [comment]
This has been resolved in newer versions of dask.
