### ISSUE TITLE
When I use dask custom graph to calculate, how can I get future and calculation status？

### ISSUE THREAD

**Issue by CY113** [dask/dask#6583]
Now I want to encapsulate the dask computation as an interface that will return my task key and future when I publish a task. When I go to get the data, if the status is complete, I will get the data. Now the method I'm using is
        `client.compute( client.get (graph,task_key)`
    However, it seems that it does not return to my future in time. When I deal with complex graphics, it will take a long time to return to the future, as if he has started calculation. So, when I use custom graphics, how can I return to future in  time?

If there is a better way, please let me know. Thank you

**Comment by TomAugspurger** [comment]
Thanks for opening an issue. This is for reporting bugs / feature requests. We recommend stackoverflow for usage questions. 

Make sure to include an MCVE: https://stackoverflow.com/help/minimal-reproducible-example.
