### ISSUE TITLE
Cannot pickle dask array objects

### ISSUE THREAD

**Issue by nbren12** [dask/dask#6589]
**What happened**:

Attempting to pickle a dask array gives:
```
AttributeError: Can't pickle local object 'broadcast_trick.<locals>.inner'
```

Dask arrays are no longer pickleable since v2.23.0.

**What you expected to happen**:

The dask array can be pickled.

**Minimal Complete Verifiable Example**:

```python
import dask.array
import pickle
a = dask.array.ones((10, 10))
pickle.dumps(a)
```

This fails on versions larger than v2.22.

**Anything else we need to know?**:

I am happy to fix this. It seems like a simple fix to move the `inner` function to the module level.

**Environment**:

- Dask version: 2.25.0
- Python version: 3.7.7
- Operating System: Mac OS X
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
> It seems like a simple fix to move the inner function to the module level.

That should make things serializable with `pickle`. Though there may be some restrictions on the signature of the function that `broadcast_trick` returns

Alternatively, does using `cloudpickle` work for your use case?

**Comment by nbren12** [comment]
`cloudpickle` does work, so I could probably use it. However if the simple fix works, it would be nice to fix normal pickle.

**Comment by jrbourbeau** [comment]
Ah, sorry I don't think I was very clear in my previous comment. A fix to make things serializable with `pickle` is very welcome. I meant to propose using `cloudpickle` as a workaround.
