### ISSUE TITLE
Support short-fat array chunking in svd

### ISSUE THREAD

**Issue by eric-czech** [dask/dask#6590]
There appears to be no reason why it wouldn't be possible to use the current support for tall-skinny array chunking in `da.linalg.svd` to also support short-fat array chunking.

Transposing inputs and outputs also appears to be a simpler solution than updating the sfqr implementation (see @mrocklin's comments at https://github.com/dask/dask-ml/issues/731#issuecomment-682590172).

While there are likely some other use cases, this came up in the context of PCA and it looks like some minor changes will also be necessary to support sign determinacy.  Having a `full_matrices` argument (https://github.com/dask/dask/issues/3576) would be a good solution for https://github.com/dask/dask-ml/issues/732 (svd_flip in dask-ml is broken without it).

**Comment by mrocklin** [comment]
I'm all in favor of this.  Is this something that you would be comfortable driving forward @eric-czech ?

**Comment by eric-czech** [comment]
> Is this something that you would be comfortable driving forward @eric-czech ?

👍   I wanted to collect my thoughts here and I'll draft a PR at some point soon to make sure it's on the right track.

**Comment by eric-czech** [comment]
Done in https://github.com/dask/dask/pull/6591, some benchmark info in https://github.com/dask/dask/pull/6613.
