### ISSUE TITLE
Add dask_sql to dataframe-sql docs

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6592]
I would like to think that @nils-braun won't mind dask_sql (https://github.com/nils-braun/dask-sql) being added to the dataframe-sql docs https://docs.dask.org/en/latest/dataframe-sql.html

For example, in the section 'The following packages may be of interest' in https://github.com/dask/dask/blob/master/docs/source/dataframe-sql.rst#does-dask-implement-sql

**Comment by jsignell** [comment]
Sure that seems reasonable to me.

**Comment by mrocklin** [comment]
I'm entirely in favor, but I think that we probably need to wait until it
is slightly more mature.

For example it doesn't yet have a downloadable package on PyPI.

SQL can be tricky, and expectations will be high I think.

**Comment by nils-braun** [comment]
Totally fine with me. I think making the package more mature is a very good first step - before we can add it here.
Thanks for raising the issue anyway!

**Comment by nils-braun** [comment]
Would now be a good time to add dask-sql to the Dask docs? It is definitely not as mature as e.g. blazingSQL (which is also mentioned there), but I see at least some users playing around with it. I am also happy to wait, just wanted to bring up the issue after some time again :-)
