### ISSUE TITLE
Add data/real example in join section of dask.dataframe docs

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6593]
The documentation in the Joins section https://docs.dask.org/en/latest/dataframe-joins.html has code blocks but they aren't interactive and therefore not as useful.

I think the documentation would benefit from an interactive example with use of real data (or data from the [demo](https://github.com/dask/dask/blob/master/dask/dataframe/io/demo.py) API).

I had a quick rummage of the tutorial (https://github.com/dask/dask-tutorial/blob/master/04_dataframe.ipynb) and the examples (https://examples.dask.org/dataframe.html) to find any join examples I could adapt from but didn't find any.

I recently read Learning Spark V2 which had a good section on joins (p187-189 [here](https://pages.databricks.com/rs/094-YMS-629/images/LearningSpark2.0.pdf)). The examples it uses are in Scala and are provided in the repo associated with the book https://github.com/databricks/LearningSparkV2/blob/master/chapter7/scala/src/main/scala/chapter7/SortMergeJoin_7_6.scala and https://github.com/databricks/LearningSparkV2/blob/master/chapter7/scala/src/main/scala/chapter7/SortMergeJoinBucketed_7_6.scala
These could be used as inspiration.

**Comment by jsignell** [comment]
This sounds like a good idea to me. I think the best way to go about it would be to use data from the demo API and create copy/pastable code blocks to include in the docs. Additionally the examples and tutorials examples that you point to could be augmented to include a join. Are you interested in opening a pull request for this?

**Comment by mrocklin** [comment]
+1  generally.  We could always add to the dask.datasets API if there is
some better dataset that we can cheaply reproduce

**Comment by jsignell** [comment]
Sorry for the slow response @kori73, I think using `from_pandas` is fine.
