### ISSUE TITLE
map_overlap fails if last chunk is smaller than depth

### ISSUE THREAD

**Issue by tomwhite** [dask/dask#6597]
**What happened**:

`dask.array.map_overlap` throws a `ValueError` if the last chunk is smaller than the `depth` parameter. (The size of the last chunk is normally outside the user's control.)

**What you expected to happen**:

The function should work in this case. The last chunk should really be ignored for this check since it can be any size less than the array chunksize.

**Minimal Complete Verifiable Example**:

In this example the last chunk is of size 1, and the depth is 2:

```python
>>> import dask.array as da
>>> import numpy as np
>>> x = da.from_array(np.arange(11), chunks=5)
>>> y = x.map_overlap(lambda x: x + len(x), depth=2, boundary=0).compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/workspace/dask/dask/array/core.py", line 2240, in map_overlap
    func, self, depth=depth, boundary=boundary, trim=trim, **kwargs
  File "/Users/tom/workspace/dask/dask/array/overlap.py", line 716, in map_overlap
    args = [overlap(x, depth=d, boundary=b) for x, d, b in zip(args, depth, boundary)]
  File "/Users/tom/workspace/dask/dask/array/overlap.py", line 716, in <listcomp>
    args = [overlap(x, depth=d, boundary=b) for x, d, b in zip(args, depth, boundary)]
  File "/Users/tom/workspace/dask/dask/array/overlap.py", line 489, in overlap
    "more evenly divides the shape of your array." % (d, min(c))
ValueError: The overlapping depth 2 is larger than your
smallest chunk size 1. Rechunk your array
with a larger chunk size or a chunk size that
more evenly divides the shape of your array.
```

`y` should be `9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 15]`

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.25.0
- Python version: 3.7.6
- Operating System: Mac 10.13.6
- Install method (conda, pip, source): source

**Comment by TomAugspurger** [comment]
Thanks for the report. I think I agree with your analysis that the last chunk can be ignored in this case (cc @jakirkham for your thoughts).

**Comment by jsignell** [comment]
It's not quite as simple as ignoring the last chunk in the check. We'd also need to add logic to ensure that the second to last chunk is padded appropriately if the last chunk isn't long enough.

**Comment by tomwhite** [comment]
Agreed - I tried to see what would happen if the check is loosened (by ignoring the last chunk size), and it returns the wrong result.

**Comment by mrocklin** [comment]
In coarsen we recently did a check where we ensured that the chunking structure matched what was necessary for coarsen to perform well (in that case, that all chunks were a multiple of the coarsen size) and if that wasn't the case we called a pre-emptive `rechunk` operation.  I wonder if we might do the same thing here, and if that might solve the problem.  Would would it surprise users to have their data rechunked before a `map_overlap` operation?

See https://github.com/dask/dask/pull/6580 by @dcherian

**Comment by jsignell** [comment]
> would it surprise users to have their data rechunked before a `map_overlap` operation?

Maybe there should be an `allow_rechunk` flag that is `False` by default and the error would recommend setting it to `True` in this particular case with some warning about performance impact?

**Comment by mrocklin** [comment]
I'm not worried about performance impact in this case.  I'm curious if
people using map_overlap expect their chunking structure to not change.  I
think that that's mostly a question for Tom White here, or other folks
familiar with image processing applications.

My *guess* is that it's fine, and we should rechunk if necessary
automatically.

**Comment by tomwhite** [comment]
I'm not sure there's ever a need to rechunk for this case. Another way might be to (internally) pad out the final chunk to the size of the other chunks (I'm thinking chunks are the same except the last one) so that the overlapping logic works even with a small last chunk.

**Comment by mrocklin** [comment]
Well, the rechunking logic might just merge the final two chunks into one
slightly larger than normal chunk, for example

**Comment by tomwhite** [comment]
Actually that sounds like a good solution (as I assume it would be pretty efficient) 😃

**Comment by mrocklin** [comment]
Yeah, the rechunking operations are pretty ok.  In general I think that we
should probably be more aggressive about including auto-rechunking in
operations.

**Comment by jsignell** [comment]
I'm going to start on this since it seems like there is an agreed-on solution.

**Comment by tomwhite** [comment]
Thanks @jsignell!

I have been rechunking the last two chunks into a single chunk, and that works fine (although I haven't tested it on large datasets). Slightly more generally, I wonder if we could combine any chunk of size < depth with the previous chunk? This would solve the problem when we have non-uniform chunk sizes.

**Comment by tomwhite** [comment]
Thanks for fixing this @jsignell!
