### ISSUE TITLE
"take" does not find items in bag

### ISSUE THREAD

**Issue by aluhamaa** [dask/dask#6610]
**What happened**:
I run `take(5)` on the filtered dask.bag object (list of ndjson files), it returns only the first match. 

**What you expected to happen**:
I would expect to get five matches, as the `compute()` command shows that the matches are actually available

**Minimal Complete Verifiable Example**:

```python
import dask.bag as db
import json

if __name__ == "__main__":
    ## does not matter if reading from local or remote source
    ddd = db.read_text('s3://openaq-fetches/realtime/2020-09-08/*.ndjson').map(lambda x: json.loads(x))
    ## there are many items after filtering
    print("Total length of filter cmd {}".format(len(ddd.filter(lambda rec: (rec['location']) == 'FRANKFORT').compute())))
    ## taking the first five, however, fails
    ddd.filter(lambda x: (x['location']) == 'FRANKFORT').take(5)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.25.0
- Python version: 3.7.8
- Operating System: Ubuntu Linux 14.04
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
Do you have an example that doesn't rely on s3? My read_text doesn't return any results (perhaps it's in a specific region?)

**Comment by aluhamaa** [comment]
> Do you have an example that doesn't rely on s3? My read_text doesn't return any results (perhaps it's in a specific region?)

Thanks for looking. Strange because this bucket should not have any region limitations:
`aws s3api get-bucket-location --bucket openaq-fetches
{
    "LocationConstraint": null
}`
but maybe it still requires aws credentials for access?

However, I added the files for download here, https://www.dropbox.com/s/1kaoih7myp7uz86/oaq.tgz?dl=0

**Comment by TomAugspurger** [comment]
Are you able to generate a dataset that reproduces the problem? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

And can you confirm:

1. do you have any warnings filters set? `take` will warn when there are fewer than `n` elements in the partition
2. Can you include the output of your two `print` calls?
3. If you don't compute the `len(...)` first, whats the output of the take?

**Comment by aluhamaa** [comment]
My bad, actually setting `npartitions` argument to `take` will solve the problem and the warning clearly says that. It is a little counterintuitive, I guess by default `take` looks into one file only, but if it is intentional, I'm ok with that. 

Updated code that can generate test data:
```python
import os
import dask.bag as db
import json
import random


def gen_data_files():
    cities = ["Berlin", "Paris", "London"]
    for fileno in range(10):
        with open("testfile_{0:02d}.ndjson".format(fileno), 'w') as fl:
            for jno in range(3):
                sample_json = {"city":random.choice(cities), "value":random.random()}
                fl.write(json.dumps(sample_json) + "\n")


if __name__ == "__main__":
    if not os.path.exists("testfile_00.ndjson"):
        print("generating new sample data")
        gen_data_files()
    ddd = db.read_text('testfile*ndjson').map(lambda x: json.loads(x))
    print(ddd.filter(lambda x: x['city'] == "Berlin").take(2))
    print("Full computation: ", ddd.filter(lambda x: x['city'] == "Berlin").compute())
```
