### ISSUE TITLE
Disabling ORC Support in pyarrow conda packages

### ISSUE THREAD

**Issue by xhochy** [dask/dask#6615]
As `dask` has ORC reading support and uses `pyarrow` for that I wanted to give a heads-up that I will probably disable ORC support for now in the `pyarrow` conda packages. The ORC dependency is a maintenance burden for me and there is no other volunteer taking care of it. Personally, I don't use ORC and thus I don't want to invest time in it. I'm posting this issue here as from my understanding the main user base of ORC reading are dask users.

## What needs to be done?

CMakefiles need to be cleaned up in the ORC C++ project. Currenly they bundle zlib in all installs and also only support static linkage. There is a WIP PR at https://github.com/apache/orc/pull/541 to fix these things but the PR needs to be pushed over the finish line and then also applied to the https://github.com/conda-forge/orc-feedstock repository to show up in the conda packages.

**Comment by TomAugspurger** [comment]
Thanks for the heads up. cc @jcrist if you have any thoughts / people to ping.

**Comment by quasiben** [comment]
cc @calebwin

**Comment by calebwin** [comment]
@quasiben  It seems like most of how we use it in Dask cuDF (and in my work in https://github.com/rapidsai/cudf/pull/6116) is for reading schema, other simple metadata. Reading this metadata without pyarrow should be easy for us if https://github.com/rapidsai/cudf/pull/6142 gets merged since the approach would be similar to how statistics is read in with that PR.

**Comment by jakirkham** [comment]
cc @martindurant @rjzamora (in case either of you have thoughts here 🙂)

**Comment by martindurant** [comment]
My opinion is that it's a shame, but no, I cannot think of where to get the effort from to maintain this.

**Comment by nehaljwani** [comment]
>There is a WIP PR at apache/orc#541 to fix these things but the PR needs to be pushed over the finish line and then also applied to the https://github.com/conda-forge/orc-feedstock repository to show up in the conda packages.

That PR is not WIP, otherwise I would have marked it as such. I'm willing to be a maintainer of the orc feedstock and also willing to patch it up for whatever is required.

**Comment by xhochy** [comment]
> >There is a WIP PR at apache/orc#541 to fix these things but the PR needs to be pushed over the finish line and then also applied to the https://github.com/conda-forge/orc-feedstock repository to show up in the conda packages.
> 
> 
> 
> That PR is not WIP, otherwise I would have marked it as such. I'm willing to be a maintainer of the orc feedstock and also willing to patch it up for whatever is required.

Thanks!

**Comment by xhochy** [comment]
Thanks to @nehaljwani fixes, disabling is from the table and we will keep it enabled. Thanks!
