### ISSUE TITLE
ValueError: Cannot rename index.

### ISSUE THREAD

**Issue by agniszczotka** [dask/dask#6617]
**What happened**: rename function does not work like documented.  it raises error     

raise ValueError("Cannot rename index.")
ValueError: Cannot rename index.

**What you expected to happen**: rename index of data frame

**Minimal Complete Verifiable Example**:

```
    import pandas as pd
    import dask.dataframe as dd 
    df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
    daskd = dd.from_pandas(df, npartitions=1)
    daskd.rename(index={0: "x", 1: "y", 2: "z"})

```

**Anything else we need to know?**: this is your own example from the documentation 

**Environment**:

- Dask version: 2.25.0
- Python version: 3.6 anaconda 2019.10
- Operating System: Mac Catalina 10.15.6
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
If you check https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.rename, you'll see that the docstring is copied from pandas and some incompatibilites may exist.  In particular we don't support the `mapper` or `index` keywords.

We have another issue about making general improvements to documentation.

**Comment by agniszczotka** [comment]
so how to rename the index in dask data frame?

**Comment by TomAugspurger** [comment]
At least for this example, you might be able to do it with
`.map_partitions(lambda x: x.rename(mapping))`. But make sure to clear the
divisions afterwards, since the mapping will have changed them.
