### ISSUE TITLE
svd_compressed breaks on arrays that are wider than they are tall

### ISSUE THREAD

**Issue by eric-czech** [dask/dask#6620]
Does this likely need a similar fix to https://github.com/dask/dask/issues/6590 (transposing inputs)?  I had assumed arrays with more columns than rows should work here:

```python
import numpy as np
import dask.array as da

x = da.random.random((10, 20), chunks=(5, 5))
u, s, v = da.linalg.svd_compressed(x, k=10, n_power_iter=3, compute=True, seed=1)
u.compute()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-106-4bb52dbb22cd> in <module>
      3 
      4 x = da.random.random((10, 20), chunks=(5, 5))
----> 5 u, s, v = da.linalg.svd_compressed(x, k=10, n_power_iter=3, compute=True, seed=1)
      6 u.compute()

/opt/conda/lib/python3.7/site-packages/dask/array/linalg.py in svd_compressed(a, k, n_power_iter, seed, compute)
    733     )
    734     if compute:
--> 735         comp = comp.persist()
    736         wait(comp)
    737     a_compressed = comp.dot(a)

/opt/conda/lib/python3.7/site-packages/dask/base.py in persist(self, **kwargs)
    138         dask.base.persist
    139         """
--> 140         (result,) = persist(self, traverse=False, **kwargs)
    141         return result
    142 

/opt/conda/lib/python3.7/site-packages/dask/base.py in persist(*args, **kwargs)
    642                     return repack(results)
    643 
--> 644     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    645     keys, postpersists = [], []
    646     for a in collections:

/opt/conda/lib/python3.7/site-packages/dask/base.py in collections_to_dsk(collections, optimize_graph, **kwargs)
    216             dsk, keys = _extract_graph_and_keys(val)
    217             groups[opt] = (dsk, keys)
--> 218             _opt = opt(dsk, keys, **kwargs)
    219             _opt_list.append(_opt)
    220 

/opt/conda/lib/python3.7/site-packages/dask/array/optimization.py in optimize(dsk, keys, fuse_keys, fast_functions, inline_functions_fast_functions, rename_fused_keys, **kwargs)
     48         inline_functions_fast_functions = fast_functions
     49 
---> 50     dsk2, dependencies = cull(dsk, keys)
     51     hold = hold_keys(dsk2, dependencies)
     52 

/opt/conda/lib/python3.7/site-packages/dask/optimization.py in cull(dsk, keys)
     49         new_work = []
     50         for k in work:
---> 51             dependencies_k = get_dependencies(dsk, k, as_list=True)  # fuse needs lists
     52             out[k] = dsk[k]
     53             dependencies[k] = dependencies_k

/opt/conda/lib/python3.7/site-packages/dask/core.py in get_dependencies(dsk, key, task, as_list)
    187     """
    188     if key is not None:
--> 189         arg = dsk[key]
    190     elif task is not no_default:
    191         arg = task

KeyError: ('transpose-34c7ebc241d847ae303819250f96ac34', 1, 0)
```

**Comment by eric-czech** [comment]
Hm well I tried to debug it for a while and I think I found something relevant.  First, I haven't found that this bug occurs at all as long as the array is sufficiently big in both dimensions (at least 50 or so rows/cols).  And for this specific example, I found that if I hack the `compression_level` arguments away from their defaults: 

`compression_level(n, q, oversampling=10, min_subspace_size=20)`

to be something like:

`compression_level(n, q, oversampling=1, min_subspace_size=1)`

then that failing example above appears to work fine.  I can also see how that setting is controlling the column chunk size which is then used in the first tsqr call (from `compression_matrix`) to set `meaningful_reduction_possible` if the max row chunk size is >= 2 * the first column chunk size.  This becomes true when those arguments are changed rather than false so presumably that's related (though not directly since it's still going down the "in-core" code path).  

Ultimately, I don't really know what's going on but I'll probably experiment enough to convince myself that this is really just a corner case with tiny arrays.  I don't know where to go from there -- perhaps the function should just throw an error if the provided array isn't big enough?

**Comment by eric-czech** [comment]
Btw, re: 

> looks like an internal issue in tsqr when the number of blocks along the tall dimensions is less the wide dimensions 

I meant to mention that I tried looking at that first and found some contradictions.  I didn't want to discount that in case you were confident about it, but iiuc I think this shows that it's something else:

```python
x = da.random.random((10, 20), chunks=(5, 4))
x.numblocks # (2, 5)
da.linalg.svd_compressed(x, k=10, compute=True)
KeyError: ('transpose-aa4313b1b7e3caac9a219d499095f999', 1, 1)

x = da.random.random((10, 20), chunks=(2, 10))
x.numblocks # (5, 2)
da.linalg.svd_compressed(x, k=10, compute=True)
KeyError: ('transpose-a755e1280d6d483d44594f195a4534f4', 4, 3)
```

**Comment by TomAugspurger** [comment]
Fixed by https://github.com/dask/dask/pull/6622.
