### ISSUE TITLE
Dask breaks the laws of physics

### ISSUE THREAD

**Issue by carlosg-m** [dask/dask#6639]
For lack of time I'm not able to create a reproducible example, however I'll post the issue to generate discussion.

I created a piece of code meant to read a very corrupted shapefile, serialize the shapes as strings with Shapely and save the result as Parquet. It does exactly what I want.

I developed a prototype in Google Colaboratory, however later on the code was migrated to another environment with similar specs (Azure).

Afterwards I noticed that the same code took a lot more time to run in Azure (almost 5 hours) relative to Colab (30 minutes). I verified all libs and configs and everything matched.

So I decided to test the function that reads the shapefile by processing a partition using Python and then Dask and comparing the results. The following results were obtained:
- In the Azure environment, using the python function and reading the first 10K lines of the shapefile takes around 1 minute. Using the same function together with Dask to compute the first partition also takes 1 minute as expected. All 10K outputted rows are equal.
- In colab using the Python function it also takes 1 minute to read the first 10K lines, however if I wrap the function around delayed together with Dask Dataframe to compute the first partition with one worker, it takes 10 seconds. All 10K outputted rows are equal.

**How is this speedup even possible?**
 
- Dask version: 2.25.0
- Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
- Operating System: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Install method (conda, pip, source): pip

Code to read shapefile:
```
def process_shape_corrupt(x):
  try:
    return shape(x)
  except: 
    return None

@dask.delayed
def read_chunck_corrupt(file_name, index, batch_size, length, out_proj):
  
  # Reading range
  lower = index
  upper = min(index+batch_size, length)
  
  # Open and read file with Fiona
  with fiona.open(file_name, 'r') as iterator:
    crs = iterator.crs['init']
    chunks = iterator.filter(lower, upper)
    chunks = map(lambda piece: {**piece['properties'], **{'geometry':piece['geometry']}}, chunks)
    chunks = pd.DataFrame(chunks, index=range(lower,upper))
    chunks['geometry'] = chunks['geometry'].map(process_shape_corrupt)
    chunks = chunks.dropna(subset=['geometry'])
    
    # Geo preprocessing
    chunks = gpd.GeoDataFrame(chunks, crs=crs, index=chunks.index)

    if out_proj is not None:
      chunks['geometry'+'_original'] = chunks['geometry']
      chunks = chunks.to_crs(out_proj)
      chunks['geometry_original'] = chunks['geometry_original'].map(wkt.dumps)

    bounds = ['minx','miny','maxx','maxy']

    chunks[bounds] = chunks['geometry'].bounds[bounds]
    chunks = chunks.dropna(subset=bounds)
    chunks['geometry_type'] = chunks['geometry'].type

    chunks = pd.DataFrame(chunks)
    chunks['geometry'] = chunks['geometry'].map(wkt.dumps)
    return chunks

def read_sf_corrupt(file_name, batch_size, out_proj=None):
    
    # Read metadata
    with fiona.open(file_name) as sf:
      crs = sf.crs
      length = len(sf)
      print('len:', length, '\ncrs:', crs)
    
    meta = read_chunck_corrupt(file_name, 0, 50, length, out_proj).compute()
    result = [read_chunck_corrupt(file_name, index, batch_size, length, out_proj) for index in range(0,length,batch_size)]
    result = dd.from_delayed(result, meta=meta)
    
    return result
```
```
shp = read_sf_corrupt('my_shapefile.shp', batch_size=10000, out_proj='epsg:3763')
%time shp.to_parquet('path/name', engine='pyarrow')
```

**Comment by jsignell** [comment]
My only thought is maybe the worker on collab has multiple threads? Or maybe the size of the first partition isn't the same.

**Comment by carlosg-m** [comment]
Thanks for the reply.

I didn't use prepared geometries in spark. This slows down the operation 10x.

It's not related to Dask.

Colab had more threads by the way ;)
