### ISSUE TITLE
Have Dask Bag use distributed scheduler

### ISSUE THREAD

**Issue by mulka-hop** [dask/dask#6652]
While reading the docs for Dask Bag, (https://docs.dask.org/en/latest/bag.html) I noticed that it says it uses the multiprocessing scheduler and the multiprocessing scheduler docs say that it only supports one machine. I'm wondering if Dask Bag can be extended to use the distributed scheduler.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @mulka-hop! Dask bag uses the multiprocessing scheduler by default but, like all Dask collections, can be used with any other Dask scheduler -- including the distributed scheduler. For example:

```python
In [1]: import dask.bag as db

In [2]: b = db.from_sequence([1, 2, 3, 4, 5, 6], npartitions=2)

In [3]: b.compute()  # uses multi-processing scheduler
Out[3]: [1, 2, 3, 4, 5, 6]

In [4]: b.compute(scheduler="threading")  # uses multi-threaded scheduler
Out[4]: [1, 2, 3, 4, 5, 6]

In [5]: from dask.distributed import Client

In [6]: client = Client()

In [7]: b.compute(scheduler=client)  # uses distributed scheduler
Out[7]: [1, 2, 3, 4, 5, 6]
```

You may be interested in looking through https://docs.dask.org/en/latest/scheduling.html#configuration for how to select which scheduler is used

**Comment by jrbourbeau** [comment]
Closing as I don't think there's anything else to do here. Hopefully the documentation link helps clarify things @mulka-hop

**Comment by mulka-hop** [comment]
Thanks for the link and example code. Works for me. Might be helpful for others to put that link in the section of the bag documentation that talks about the default scheduler.

More recently, I noticed in the documentation for the distributed Client object, it says "When a Client is instantiated it takes over all dask.compute and dask.persist calls by default.". I assume that included the bag compute function too. So, maybe you don't have to specify the scheduler in the bag compute method if you've instantiated a Client object before that.

**Comment by jrbourbeau** [comment]
> Thanks for the link and example code. Works for me

Great, glad to hear it!

> So, maybe you don't have to specify the scheduler in the bag compute method if you've instantiated a Client object before that

Yep, that's correct
