### ISSUE TITLE
Have client.map support a future

### ISSUE THREAD

**Issue by mulka-hop** [dask/dask#6653]
I'm trying to do something similar to the following. I'd like the result of get_files to not leave the cluster but instead have the result be fed into a map call. Unfortunately this is giving me an error:

```
TypeError: object of type 'Future' has no len()
```

```
from dask.distributed import Client

def get_files():
  return ['file1.json', 'file2.json']

def process_file(filename):
  return json.load(open(filename))

client = Client()
files = client.submit(get_files)
processed_files = client.map(process_file, files)
```

**Comment by jrbourbeau** [comment]
Perhaps using Dask bag + persist fits your use case? Something along the lines of:

```python
import random
import dask.bag as db
from dask.distributed import Client

def get_data():
    for _ in range(5):
        yield random.random()

def process(x):
    return x**2

with Client() as client:
    data = db.from_sequence(get_data()).persist()
    result = data.map(process).compute()
    print(f"result = {result}")
```

**Comment by mrocklin** [comment]
https://examples.dask.org/applications/evolving-workflows.html

**Comment by mulka-hop** [comment]
So, the get_files function here, is just a stand-in for listing files from a remote machine, so I need this function to run on the remote machine. It's really more like this:

```
def get_files():
    result_files = glob.glob('/path-on-remote-machine/*/data.json')
    return result_files
```

Then, I'd like to be able to map a process_file function on that list without sending that list back to my laptop. So, client.map doesn't accept a single future which will be a list I'm guessing? I would have to submit tasks from a task? I don't know why but submitting tasks from a task seems weird to me.

**Comment by mrocklin** [comment]
There are a variety of solutions to this problem in the example I point to above, including pulling the result back, waiting on the future and then submitting more tasks after you remotely compute the length, and submitting tasks from tasks.  

You could also consider Prefect, which uses these tricks internally.  

There isn't a clear alternative proposal here, so I'm going to close for now.  Thanks for bringing this up.
