### ISSUE TITLE
DaskDataFrage GroupBy axis=1 does not work

### ISSUE THREAD

**Issue by JannicCutura** [dask/dask#6654]
**What happened**:
I am trying to compute a groupby mean on the columns of a dask dataframe. The [documentation](https://docs.dask.org/en/latest/dataframe-api.html#dataframegroupby) states that `axis` is not supported. I am looking for a workarround or kindly rise awareness to the fact that this is useful. 

**What you expected to happen**:
Get a dask dataframe aggregated by columns as in the pandas example provided below. 

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd,t pandas as pd numpy as np
pdf = pd.DataFrame({'A':[1,2,1],'B':[4,5,6],'C':[7,8,9], 'D':[1,2,3]})
pdf.columns=['A','A','B','B']
pdf.groupby(by=pdf.columns, axis=1).mean() # works
ddf = dd.from_pandas(pdf, npartitions=1) 
ddf.groupby(by=ddf.columns, axis=1).mean() #breaks
ddf.groupby(by=list(ddf.columns), axis=1).mean() #breaks
#TypeError: __init__() got an unexpected keyword argument 'axis'

# for refrence, this works across levels of columns:
pdf = pd.DataFrame({'A':[1,2,1],'B':[4,5,6],'C':[7,8,9], 'D':[1,2,3]})   
pdf.groupby('A').mean()
ddf = dd.from_pandas(pdf, npartitions=1)
ddf.groupby('A').mean().compute()
```

**Environment**:

- Dask version: 2.250
- Python version: 3.8
- Operating System: Windows 7
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for raising an issue. As far as I know there isn't any plan to support the `axis` keyword. If you have time/interest in adding it pull requests are always welcome!

Otherwise, I am wondering if something like this will work for you:

```python
import dask.dataframe as dd
import pandas as pd 
import numpy as np

pdf = pd.DataFrame({'A':[1,2,1],'B':[4,5,6],'C':[7,8,9], 'D':[1,2,3]})
pdf.columns=['A','A','B','B']

ddf = dd.from_pandas(pdf.melt(ignore_index=False), npartitions=1).reset_index()
ddf.groupby(by=["index", "variable"]).mean().compute().unstack()
```

**Comment by jsignell** [comment]
I'm going to close this for now, since there is no plan to change the current behavior.

**Comment by mrocklin** [comment]
Usually axis=1 operations are pretty easy for us to support.  They're
embarrassingly parallel and so  turn into map_partitions calls.  This isn't
high priority, but it probably wouldn't be hard to do either.
