### ISSUE TITLE
Independently chunked computation loads entire zarr arrays into memory

### ISSUE THREAD

**Issue by shoyer** [dask/dask#6668]
**What happened**:

The following example creates four 1 GB zarr arrays on disk, chunked into 100 chunks along only their first axis. The computation graph is entirely independent along the chunked axis, yet dask multi-threaded scheduler loads two of these arrays (2 GB of data) into memory.

**What you expected to happen**:

I expect this computation never to use more than a small amount of memory (e.g., perhaps 10x the chunk size), because each CPU never needs to load more than one chunk at a time.

**Minimal Complete Verifiable Example**:

```python
import dask.array
from dask.diagnostics import ResourceProfiler
from multiprocessing.pool import ThreadPool
import dask.config
import matplotlib.pyplot as plt
import numpy as np

# create data on disk
x = dask.array.zeros((12500, 10000), chunks=('10MB', -1))
dask.array.to_zarr(x, 'saved_x1.zarr', overwrite=True)
dask.array.to_zarr(x, 'saved_y1.zarr', overwrite=True)
dask.array.to_zarr(x, 'saved_x2.zarr', overwrite=True)
dask.array.to_zarr(x, 'saved_y2.zarr', overwrite=True)

# load and profile data
x1 = dask.array.from_zarr('saved_x1.zarr')
y1 = dask.array.from_zarr('saved_x2.zarr')
x2 = dask.array.from_zarr('saved_y1.zarr')
y2 = dask.array.from_zarr('saved_y2.zarr')

def evaluate(x1, y1, x2, y2):
  u = dask.array.stack([x1, y1])
  v = dask.array.stack([x2, y2])
  components = [u, v, u ** 2 + v ** 2]
  return [
      abs(c[0] - c[1]).mean(axis=-1)
      for c in components
  ]

rprof = ResourceProfiler(dt=0.1)

with dask.config.set(pool=ThreadPool(1)):
  with rprof:
    results = evaluate(x1, y1, x2, y2)
    dask.compute(results)
```

Here are the memory profiling results:
![image](https://user-images.githubusercontent.com/1217238/94233020-0fc38500-febc-11ea-9961-bc37c19dab42.png)

Here's what the optimized computational graph looks like, showing just the first two chunks along the first axis:
`dask.visualize(evaluate(x1[:250], y1[:250], x2[:250], y2[:250]), optimize_graph=True)`
![image](https://user-images.githubusercontent.com/1217238/94232151-3b457000-feba-11ea-9900-b2a977cea74c.png)

See this notebook for full details: https://nbviewer.jupyter.org/gist/shoyer/181ae78ec2f22df815e02ab0f5db3603

**Anything else we need to know?**:

It is easy to make this computation work in a streaming fashion, e.g., by removing any one of the listed components. But my understanding was that unless there is overlap in the computational graph (ala https://github.com/dask/dask/issues/874) dask is supposed to always do [depth first](https://docs.dask.org/en/latest/scheduling-policy.html) evaluation of the task graph, which should ensure computation like this is always done in a streaming way. That does not appear to be the case here.

Note: This is a simplified example from a real use-case involving xarray, which does not use `from_zarr` but rather its own system for feeding loaded zarr arrays into dask.

**Environment**:

- Dask version: 2.27 / master
- Python version: Python 3.6 / 3.8
- Operating System: Linux / OS X
- Install method (conda, pip, source): source

**Comment by TomAugspurger** [comment]
Looking at the ordering, things seem OK, right?

```python
n = 125 * 2
dask.visualize(evaluate(x1[:n], y1[:n], x2[:n], y2[:n]), optimize_graph=True,
               color="order", cmap="autumn", node_attr={"penwidth": "4"})
```

![mydask](https://user-images.githubusercontent.com/1312546/94264932-4077de80-fefd-11ea-8e93-164e6af89a5f.png)

All the tasks in the left half are executed before the right half. cc @eriknw if you have some free time to see if anything looks off.

**Comment by eriknw** [comment]
Thanks for the issue and the ping.  It looks like everything *is* connected, right?  I don't know what you expect.  Perhaps the given example is overly-connected from using `zarr`.  Can you try to clarify?

I see two patterns in the task graph.  One pattern is shorter (contains 8, 18, 32, and 40 in Tom's graph), and the other is taller (contains 24 and 46).  Perhaps the shorter ones generally execute before the taller ones, causing intermediate results used by both to remain in memory.  This holding pattern won't continue indefinitely, and it only happens if tasks are well-connected.

Scheduling ordering is generally DFS, but it is not strictly DFS, which would lead to lots of undesirable behavior.

I was able to reproduce the memory profile result.

**Comment by shoyer** [comment]
@TomAugspurger Coloring by execution order is a very nice trick!

Here's an example with the first 4 time chunks, which may be more informative:
```
n = 125 * 4
dask.visualize(evaluate(x1[:n], y1[:n], x2[:n], y2[:n]), optimize_graph=True,
               color="order", cmap="viridis", node_attr={"penwidth": "4"})
```
![image](https://user-images.githubusercontent.com/1217238/94296855-6068cb80-ff18-11ea-846d-f150a7a85043.png)

Here we have four independent execution "towers", but from the coloration we can see that the 2nd and 4th tower overlap in their execution.

We can see a similar issue for `n = 125 * 10` -- instead of executing all three sub-results inside each chunk simultaneously, two of them gets executed long before the last one:
![image](https://user-images.githubusercontent.com/1217238/94297424-56939800-ff19-11ea-9d28-5d216578755c.png)

I imagine the intermediate chunks here get cached in memory, which explains the memory issue.

> It looks like everything _is_ connected, right? I don't know what you expect. Perhaps the given example is overly-connected from using `zarr`. Can you try to clarify?

"overly connected from using zarr" sounds like a likely hypothesis to me, though given how thin of a wrapper `from_zarr` is around `from_array`, I would guess that is the origin (it's also the piece of dask that we reuse inside xarray).

The four blocks at the bottom of the graph correspond to the source zarr arrays. They are indeed the same Python object, but inside Zarr there is an entirely separate file corresponding to each chunk along the first axis. There's no reason why they need to be connected at all -- the computation could (and should) be entirely independent.

It's been a long time (years!) since I looked carefully at task graphs to debug scheduling issues, but from what I recall, graphs like this in the early days of dask used to look entire disconnected.

**Comment by shoyer** [comment]
To test the hypothesis that `from_zarr`/`from_array` was the issue, here's a version that creates random data instead:
```python
x1 = dask.array.random.uniform(size=(12500, 10000), chunks=('10MB', -1))
x2 = dask.array.random.uniform(size=(12500, 10000), chunks=('10MB', -1))
y1 = dask.array.random.uniform(size=(12500, 10000), chunks=('10MB', -1))
y2 = dask.array.random.uniform(size=(12500, 10000), chunks=('10MB', -1))
```

This seems to fix both execution order issue and the memory usage:
![image](https://user-images.githubusercontent.com/1217238/94298475-0e757500-ff1b-11ea-8b8e-22085e4da709.png)
![image](https://user-images.githubusercontent.com/1217238/94298493-159c8300-ff1b-11ea-9ddf-fe17baced3ec.png)

**Comment by shoyer** [comment]
I think tying all computation in these graphs into the single source Zarr arrays object is also the root cause of poor scheduling noted in https://github.com/pangeo-data/rechunker/issues/35#issuecomment-667127467.

**Comment by mrocklin** [comment]
> graphs like this in the early days of dask used to look entire disconnected.

Yeah, people frequently show up wanting to change this configuration back and forth.

Putting the Zarr array in every task ends up creating a non-trivial amount of metadata if you have very many tasks, especially if the zarr array also holds things like a gcsfs filesystem.  If we can reduce the task overhead of bundling a zarr array then we could include it more easily.  Alternatively if `from_zarr` wanted to get more clever about creating a Zarr array on the fly in the task then that would be an easy way to solve this problem.

**Comment by shoyer** [comment]
> Yeah, people frequently show up wanting to change this configuration back and forth.

Does this suggest that perhaps we should have an explicit option in `from_array`?

If I understand correctly, such an option would basically conditionally comment out this line, and instead pass in the array directly into each task:
https://github.com/dask/dask/blob/588a212cbaaa05e5bd69a46b854131247f62b473/dask/array/core.py#L2920

> Alternatively if `from_zarr` wanted to get more clever about creating a Zarr array on the fly in the task then that would be an easy way to solve this problem.

The problem with constructing Zarr arrays on the fly is that creating Zarr arrays can sometimes be in a little expensive: you have to read a file or two from disk to reconstruct the metadata.

That said, in xarray, we have internal caching layer for exactly these sorts of use-cases. As long as you use consolidated metadata, the cost of creating Zarr arrays from a cached Zarr group should be almost zero.

I am inclined to suggest that this means we don't ever want to put source arrays into dask graphs from Xarray, but I guess Xarray's own backend array classes could probably add non-negligible amounts of metadata.

I am loathe to suggest more complexity in dask's scheduler, but perhaps there might be a way to request explicitly "non-cachable" tasks, such that as part of optimization they get inlined into later tasks? I can imagine this also being useful in other contexts in xarray where we do cheap processing on arrays from disk (e.g., broadcasting and other shape manipulation inside `open_mfdataset`). I guess inlining tasks might also end up duplicating considerable metadata in the same way?

**Comment by mrocklin** [comment]
>> Yeah, people frequently show up wanting to change this configuration back and forth.

> Does this suggest that perhaps we should have an explicit option in from_array?

Yes, that seems reasonable to me.

> I am inclined to suggest that this means we don't ever want to put source arrays into dask graphs from Xarray, but I guess Xarray's own backend array classes could probably add non-negligible amounts of metadata.

Maybe.  If all we're storing is a function or a class and some python args then things are pretty cheap.  I suspect that some small amount of effort here can keep things efficient.

> I am loathe to suggest more complexity in dask's scheduler, but perhaps there might be a way to request explicitly "non-cachable" tasks, such that as part of optimization they get inlined into later tasks?

See `inline_functions` here

https://github.com/dask/dask/blob/588a212cbaaa05e5bd69a46b854131247f62b473/dask/array/optimization.py#L23-L37

**Comment by shoyer** [comment]
Optimization is already easily overridable, so that gives me a simple work-around, which I'll use for now in my pipeline until we get a better fix:
```
def custom_optimize(dsk, keys):
    dsk = dask.optimization.inline(dsk, inline_constants=True)
    return dask.array.optimization.optimize(dsk, keys)

with dask.config.set(array_optimize=custom_optimize):
    results = evaluate(x1, y1, x2, y2)
    dask.compute(results)
```

**Comment by shoyer** [comment]
With regards to the inline constants optimization, would there ever be a reason not that if we're using one of the local schedulers? If I understand correctly, Python would actually reuse the same objects for the constants, so the increased size of the graph when serialized wouldn't matter?

If so, perhaps it would make sense to think about applying this optimization automatically when not using the distributed scheduler.

**Comment by mrocklin** [comment]
That might be a workaround, yes.  

I'm going to poke @eriknw again.  Part of his brain seems to be engaged with ordering these days.  I wonder if we can attract him back to this issue with flashy graph plots :)

**Comment by sjperkins** [comment]
> I think tying all computation in these graphs into the single source Zarr arrays object is also the root cause of poor scheduling noted in pangeo-data/rechunker#35 (comment).

We ran into similar  issues in https://github.com/ska-sa/dask-ms/pull/75#issuecomment-563158601. Graphs like the following (with a common ancestor) would OutOfMemory:

![](https://user-images.githubusercontent.com/3530212/70424373-f9a51f00-1a77-11ea-8b45-07fb7b0409c7.png)

We solved it by embedding the our zarr file object equivalent in a proxy object implementing a [Multiton](https://en.wikipedia.org/wiki/Multiton_pattern), as well as developing some internal caching mechanisms for small metadata arrays to produce a graph like this:

![](https://user-images.githubusercontent.com/3530212/70425054-1c840300-1a79-11ea-90ff-ca612e0a3f75.png)

**Comment by sjperkins** [comment]
In general, broadcasts might be problematic, because there's lots cross-communication and it's not immediately clear what the critical path through the graph is (feed large arrays into the broadcast last, consume them first)
