### ISSUE TITLE
Size of dask repr_html for large arrays

### ISSUE THREAD

**Issue by rabernat** [dask/dask#6670]
**What happened**:

I saved a notebook with numerous large dask arrays displayed using `_repr_html_`. The size of the notebook on disk was 50 MB. This is completely dominated by the size of the dask-generated SVG. Notebooks this big are inconvenient to work with and store.

**What you expected to happen**:

I would expect dask to be smarter about generating it's `_repr_html_` so as not to create such large SVG data. In this case, rendering a line for each chunk is pointless, since there are not nearly enough pixels on a screen to actually display this information.

I see three ways to resolve this
- **best**: have `_repr_html_` look at the number of lines it is planning to draw and decide whether it is reasonable. If not, just render a flat polygon.
- **better**: figure out how to rasterize the SVG
- **good**: fall back on the plain-text repr in these cases

**Minimal Complete Verifiable Example**:

```python
import dask.array as dsa
data = dsa.ones((16000, 2400, 3600), chunks=(1, 2400, 3600))
display(data)
len(data._repr_html_().encode('utf-8')) # -> 1379359
```

The repr is 1.4 MB. This is because there are 16000 svg lines drawn along the top and sides of the cube

![image](https://user-images.githubusercontent.com/1197350/94273468-74a9ca00-ff12-11ea-98ca-33e803c818bf.png)

**Environment**:

- Dask version: '2.26.0'
- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
Agreed that we should avoid this. I wonder if it's OK to just not draw any chunk lines in this case, since the table still has the chunking information.

**Comment by rabernat** [comment]
> I wonder if it's OK to just not draw any chunk lines in this case, since the table still has the chunking information.

Yes, that is basically what I call my **best** option.

**Comment by shoyer** [comment]
> > I wonder if it's OK to just not draw any chunk lines in this case, since the table still has the chunking information.
> 
> Yes, that is basically what I call my **best** option.

It is still nice to show the "heavily chunked" axes in a darker color, though. But perhaps in the "too many chunks" case we could just shade in the whole side of the cube than trying to draw lines.

**Comment by mrocklin** [comment]
I think that maxing the number of lines at something like 20 would probably
also give the sense that chunking on that axis is of the value "a lot"

**Comment by jsignell** [comment]
I like the idea of making the heavily chunked sides darker. I am taking a crack at it now.
