### ISSUE TITLE
Some way to explicitly "duplicate" graphs in a dask collection

### ISSUE THREAD

**Issue by shoyer** [dask/dask#6674]
Memory issues with dask seem to occur most often when computation is reused in some way, intentionally or not. Good example would include https://github.com/dask/dask/issues/874 and https://github.com/dask/dask/issues/6668.

This is somewhat inevitable -- it's hard to know ahead of time when something is expensive to compute and shouldn't be re-evaluated vs. when it's cheap and should be discarded. We can add ever more intelligent heuristics, but this is hard to get right in every case.

One work around (the current recommendation) is to explicitly cache results into memory or to disk, with `compute()` or `persist()`.

Another nice option would be have some way to explicitly duplicate every task in a dask collection, so that they are treated as separate tasks when combined with other graphs that contain the same tasks.

Let's go in-depth into the scheduling fail-case example from #874:
```python
import dask.array as da
x = da.ones((8, 200, 200), chunks=(1, 200, 200))  # e.g., a large stack of image data
mad = abs(x - x.mean(axis=0)).mean()
mad.visualize(optimize_graph=True)
```

With explicit caching, we could fix this like `abs(x - x.mean(axis=0).persist()).mean()`. (Side note: to my surprise `abs(x - x.persist().mean(axis=0)).mean()` doesn't work -- `x` and `x.persist()` still seem to resolve to the same dask object.)

With explicit graph duplication, we might write something like `abs(x - x.duplicate_graph().mean(axis=0)).mean()` instead. Arguably, this "duplicate graph" behavior is exactly what one might expect from the `copy()` method, but `copy()` is already defined on collections like arrays as reusing the exact same dask graph, so perhaps we need a new name.

**Comment by jsignell** [comment]
Mildly related to https://github.com/dask/dask/issues/6506

**Comment by mrocklin** [comment]
Hrm, that's an interesting approach.  Is this something that you would find
useful within Xarray or is it something that we would ask users to do?

**Comment by shoyer** [comment]
I don't think this would end up being called directly by xarray, but I imagine plenty of xarray users might use it. You really need to know something about the higher level computational structure for this to make sense.

**Comment by mrocklin** [comment]
I'm generally open to a duplicate graph method.  I was working with another group that had implemented this internally and had seen good results from it.  

They brought up a concern that I hadn't anticipated that I wanted to mention here.  

If you have something like `x.duplicated_graph() - x.mean()` then while the cluster is busy computing the `mean` part of `x.mean` it might also start re-computing `x` again (it has no dependencies).  If the aggregate value that we're computing doesn't occupy the entire cluster then it's apparently common to see memory blow up anyway from re-computing `x`.

Internally they found a need to have both a `clone` function (this is what they call `duplicate_graph`) as well as a `bind` function which adds artificial dependencies so that one collection does not start computing until another is finished.

```python
avg = x.mean()
xx = clone(x)  # make a copy
xx = bind(xx, avg)  # only start computing xx once avg is complete
xx - x.mean()
```

Thoughts @shoyer ?

**Comment by shoyer** [comment]
I hadn't though of `bind()`, but it makes complete sense to want some way to introduce artificial dependencies if you're doing graph surgery. This sounds a little similar to some tricks used [inside rechunker](https://github.com/pangeo-data/rechunker/blob/master/rechunker/executors/dask.py).

**Comment by mrocklin** [comment]
Thoughts on methods vs functions for these?  I don't have strong thoughts here.  I find myself with a slight preference for functions to start, mostly to keep them out of the public eye and contain them a bit, but I haven't thought deeply about this yet.

**Comment by shoyer** [comment]
+1 for functions. I imagine that way they could automatically work on any dask duck collection types? I agree that these are lower level and deserve incubation, so they don't even necessarily have to be in the root `dask` namespace.

**Comment by mrocklin** [comment]
dask.base for now, without elevation to dask, and with a warning in the
docstring?

**Comment by jakirkham** [comment]
@crusaderky added some operations to help manipulate the graph in PR ( https://github.com/dask/dask/pull/7109 ). Maybe that is useful here? 🙂

**Comment by jrbourbeau** [comment]
Thanks for following up here @jakirkham. In fact I suspect the new methods ([documented here](https://docs.dask.org/en/latest/graph_manipulation.html#api)), in particular `clone`, address @shoyer's original use case. @shoyer is it safe to close this issue out?

**Comment by shoyer** [comment]
+1 looks great!

**Comment by jakirkham** [comment]
Thanks for taking a look Stephan! Please let us know how using these goes 🙂
