### ISSUE TITLE
`map_overlap` produces wrong shape with `trim=False`

### ISSUE THREAD

**Issue by zklaus** [dask/dask#6681]
**What happened**:
I am working on a lazy rolling window method for `dask.array`s and use `da.map_overlap`.
Problem is that with `trim=False`, before the result is `compute()`d, the shape is wrong. It includes the boundary.
After compute, the shape is correct.

**What you expected to happen**:
I expect to have the same shape before and after `compute`, even with `trim=False` (provided the function itself trims, of course).

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import numpy as np

x1 = da.random.random(10, chunks=(5, 5))
x2 = x.rechunk(10)

def oversum(x):
    return x[2:-2]

z1 = da.map_overlap(oversum, x1, depth=2, boundary='reflect', trim=False)
z2 = da.map_overlap(oversum, x2, depth=2, boundary='reflect', trim=False)

print(z1.shape, z1.compute().shape)
print(z2.shape, z2.compute().shape)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.25.0-2.28.0
- Python version: 3.8.5
- Operating System: linux (rhel)
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Hmm thanks for raising this. It's an interesting issue. The trim docs do state that if `trim=False` it is assumed that the user-provided func is going to maintain the shape of the original array. So I think your expectation that the shape would be (10,) is correct. 

It is possibly to explicitly provide the `chunks` kwarg which will set the shape of the outcome. 

```python
>>> da.map_overlap(oversum, x2, depth=2, boundary='reflect', trim=False, chunks=(10,)).shape
(10,)
```

but I think you are right that that is what should happen by default.

**Comment by zklaus** [comment]
Thanks for looking into this so quickly, and thanks for the pointer to the `chunks` workaround!
