### ISSUE TITLE
map_overlap should work with smaller-than-depth chunk sizes

### ISSUE THREAD

**Issue by jni** [dask/dask#6688]
Related to #6597, but distinct I think.

If I have an array chunked into individual slices along an axis, but I want to perform an operation across that axis, I would *expect* `map_overlap` to be able to pull as many chunks as it needs along that axis to make the boundary, ie this should work:

```python
from dask import array as da
from scipy import ndimage as ndi

rand = da.random.random((860, 1024, 1024), chunks=(1, 1024, 1024))
filtered = da.map_overlap(
    rand,
    lambda arr: ndi.median_filter(arr, 5),
    depth=(2, 2, 2),
    boundary='reflect',
)
```

This raises:

```pytb
ValueError: The overlapping depth 2 is larger than your
smallest chunk size 1. Rechunk your array
with a larger chunk size or a chunk size that
more evenly divides the shape of your array.
```

But one *should* be able to grab multiple chunks to pad sufficiently?

If auto-rechunking is the preferred solution, then feel free to close this, since I think #6597 covers that adequately.

**Comment by mrocklin** [comment]
I think that auto-rechunking isn't necessarily the best solution, but it's
probably sufficient and easy :)

**Comment by jni** [comment]
Thank you all! :pray: :heart:
