### ISSUE TITLE
map_blocks with dtype induce dummy function call (Doc say it shouldn't)

### ISSUE THREAD

**Issue by oarcher** [dask/dask#6690]
[dask.array.map_blocks](https://docs.dask.org/en/latest/array-api.html#dask.array.map_blocks) says about `dtype`:
> The dtype of the output array. It is recommended to provide this. If not provided, will be inferred by applying the function to a small set of fake data.

So if `dtype` is provided, the function should not be called. 

This minimal example will print a message if the function is called:
```python
import dask.array as da


def block_func(block,block_info=None):
    if block_info is None:
        print("block_func called with block_info=None")
    return block + 0.5

data=da.arange(10,chunks=2)
data.map_blocks(block_func, dtype='f8')
```

This code print "block_func called with block_info=None", and that show that the function is called, despite of the documentation.

I've found that using the undocumented keyword `meta=True`, it's work as expected, and the function is not called:

```python
data.map_blocks(block_func, dtype='f8',meta=True)
```

Is it a documentation problem, or am I missing something else ?

**Environment**:

- Dask version: 2.28.0
- Python version: 3.8.2
- Operating System: linux
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Thanks for the report. The docs will need to be updated, but we might want to also update the behavior.

Previously, we only used `dtype`. Then we added support for using `meta` to specify the concrete container (numpy, cupy, sparse, ...) (https://github.com/dask/dask/pull/5269). Right now the behavior is to not call the function only when both `meta` and `dtype` are specified. We have a few options:

1. Just update the docs. Instruct users to specify both `dtype` and `meta`
2. Update the implementation to restore the old behavior. `dtype="f8"` and no meta would mean a NumPy ndarray with foat64 dtype
3. Update the docs to encourage passing `meta`.

I think my preference is for option 2, but would be curious to hear others' thoughts. cc @pentschev if you have thoughts.

**Comment by pentschev** [comment]
I would go for option 1. Currently, we try to infer `meta` automatically to the best of our abilities, when we go for option 2 we lose that ability. IMO, we should strive to keep this kind of computation automatic when possible, it can be very difficult in a complex pipeline with multiple non-NumPy arrays otherwise.

**Comment by TomAugspurger** [comment]
> we should strive to keep this kind of computation automatic when possible, it can be very difficult in a complex pipeline with multiple non-NumPy arrays otherwise.

My perception is probably skewed, but I'm having trouble balancing the cost of specifying `meta` against how often it'll be used to specify non-NumPy arrays.

How about this modification of option 2: When the user provides just `dtype="f8"` (no `meta`) we scan the input arrays in `args` for arrays. If there's just one type (by far the most common case?) then we set `meta` to that type with the user-specified dtype. This uses the assumption that most functions would return an array of the same type.

If there's multiple types in `args`, we issue the warning asking them to clarify `meta`.

And specifying `meta` up front would disable the scan over `args` entirely.

**Comment by pentschev** [comment]
I agree with these two parts:

> How about this modification of option 2: When the user provides just `dtype="f8"` (no `meta`) we scan the input arrays in `args` for arrays. If there's just one type (by far the most common case?) then we set `meta` to that type with the user-specified dtype. This uses the assumption that most functions would return an array of the same type.
> 
> And specifying `meta` up front would disable the scan over `args` entirely.

But not with:

>  If there's multiple types in `args`, we issue the warning asking them to clarify `meta`.

This last case is indeed what we're trying to solve (emphasis in _trying_) with automatic `meta` deduction. If the user needs to always specify the `meta` type we again ignore this mechanism, and if our intent is to make things easier for complicated cases in the future then we would be going against that goal by doing this.

So my suggestion here would be to address most things as you suggested, except for different `args`. The complete idea would look something like:

"Specifying `meta` up front would use that value as `meta` and no further action is taking to infer its value. When the user provides just `dtype` (no `meta`) we scan the input arrays in `args` for arrays, and if there's just one type then we set `meta` to that type with the user-specified `dtype`. If there's multiple types in `args` but no `meta` is specified, we infer `meta` from arrays in `args`."

Does that look reasonable?

**Comment by TomAugspurger** [comment]
Ah, my apologies, I was confused about the current behavior. I thought that we warned while inferring `meta` (by calling the function). I agree with your proposal.

**Comment by oarcher** [comment]
Yes, it makes sense to me.

I was thinking about some changes in [blockwise.py#L246](https://github.com/dask/dask/blob/8a699223982ce8425f59f048d0163090b4a81193/dask/array/blockwise.py#L246) :

```python
        from dask.array.core import is_scalar_for_elemwise
        if all([a._meta is args[0]._meta for a in args[::2] if not is_scalar_for_elemwise(a) ]):
            meta = args[0]._meta
        else:
            warnings.warn("args have different meta, you should provide meta= explicitly if dtype is provided")
```

I had to import `is_scalar_for_elemwise` to check if `args` is scalar.  Perhaps that to check for `_meta` attr should be enough ?

**Comment by pentschev** [comment]
I don't think using `is` to compare objects is gonna work, as their `_meta` may be similar or even equal, but not the same instance in most cases. I think what we want is something like the following:

```python
    if meta is None:
        from .utils import compute_meta

        if dtype is not None:
            if all([type(a._meta) is type(args[0]._meta) for a in args[::2]]):
                meta = args[0]._meta
            else:
                warnings.warn("args have different meta, you should provide meta= explicitly "
                              "if dtype is provided to prevent meta computation on empty arrays")
                meta = compute_meta(func, dtype, *args[::2], **kwargs)

```

**Comment by oarcher** [comment]
I've got some cases where args have no `_meta`, nor `is_scalar_for_elemwise` ie from code like:

```python
import numpy as np
import xarray as xr

arr=xr.DataArray(np.random.randn(10), dims=("x"), coords={"x": np.arange(10)}).chunk({'x':5})
res=arr.data.map_blocks(lambda d,func,axe:func(axe),lambda axe:axe+0.5,arr.x,dtype='f8')
```
(one of the `args` is a function)

So my proposal is:
```python
    if meta is None:
        if dtype is not None:
            uniq_meta = set([type(a._meta) for a in args[::2] if isinstance(a, Array)])
            if len(uniq_meta) == 1:
                meta = list(uniq_meta)[0]
            else:
                warnings.warn("args have different meta, you should provide meta= explicitly "
                              "if dtype is provided to prevent meta computation on empty arrays")
        if meta is None:
            from .utils import compute_meta

            meta = compute_meta(func, dtype, *args[::2], **kwargs)
```

Or, if having a function in `args` must raise a meta warning:

```python
    if meta is None:
        if dtype is not None:
            from dask.array.core import is_scalar_for_elemwise
            try:
                uniq_meta = set([type(a._meta) for a in args[::2] if not is_scalar_for_elemwise(a)])
            except AttributeError:
                uniq_meta = []
            if len(uniq_meta) == 1:
                meta = list(uniq_meta)[0]
            else:
                warnings.warn("args have different meta, you should provide meta= explicitly "
                              "if dtype is provided to prevent meta computation on empty arrays")
        if meta is None:
            from .utils import compute_meta

            meta = compute_meta(func, dtype, *args[::2], **kwargs)
```

**Comment by pentschev** [comment]
Could you try using https://github.com/dask/dask/blob/8a699223982ce8425f59f048d0163090b4a81193/dask/array/utils.py#L31 ?

The code I posted before would look something like:

```python
    if meta is None:
        from .utils import compute_meta

        if dtype is not None:
            if all([type(meta_from_array(a)) is type(meta_from_array(args[0])) for a in args[::2]]):
                meta = meta_from_array(args[0]._meta)
            else:
                warnings.warn("args have different meta, you should provide meta= explicitly "
                              "if dtype is provided to prevent meta computation on empty arrays")
                meta = compute_meta(func, dtype, *args[::2], **kwargs)
```

**Comment by oarcher** [comment]
I confirm that code before using `meta_from_array` works as expected in the cases I've tested.

**Comment by pentschev** [comment]
> I confirm that code before using `meta_from_array` works as expected in the cases I've tested.

Sorry, I'm having difficulty with interpreting your sentence accurately. Are you saying that:

1. The previous code but now with `meta_from_array` -- which is the code in https://github.com/dask/dask/issues/6690#issuecomment-703910822 -- works as expected; or
1. The code you wrote before my suggestion to use `meta_from_array` -- code in ttps://github.com/dask/dask/issues/6690#issuecomment-703858616d -- is working?

**Comment by oarcher** [comment]
Sorry.
I was talking about your solution (1) at  https://github.com/dask/dask/issues/6690#issuecomment-703910822

My solution (2) at https://github.com/dask/dask/issues/6690#issuecomment-703858616 using `set` and `meta_from_array` just change the `if` condition: 
```python
if len(set([type(meta_from_array(a)) for a in args[::2]])) == 1:
```

But why are you using 
```python
meta = meta_from_array(args[0]._meta)
```
?
may be this can be replaced by:
```python
meta = meta_from_array(args[0])
```
?
or perhaps with:
```python
meta = meta_from_array(args[0]).astype(dtype)
```
?
Because I've seen that the following code:
```python
da.arange(10,chunks=5).map_blocks(lambda x:(x+0.5).astype('f4'),dtype='f4')
```
compute a `meta` like `array([], dtype=int64)`, and I'm confused about the `dtype` that dosen't match the one I gave.

**Comment by pentschev** [comment]
If everything works, I would prefer my solution with `meta_from_array` to remain consistent with the rest of Dask, where we frequently use it to handle `meta` rather than creating custom code. 

I'm sorry, it was a mistake to suggest `meta_from_array(args[0]._meta)`, what I meant to suggest is just `meta_from_array(args[0])`, as you noticed.

Regarding the `dtype`, I didn't suggest it because I think `map_blocks` should adjust `meta`'s `dtype` properly when it runs, but I may be mistaken on this one. Since I'm not totally certain about it, we can definitely ensure it's set now and adjust that later if necessary, I suggest we do it with `meta_from_array(args[0], dtype=dtype)`, because `astype` is done internally https://github.com/dask/dask/blob/34fd6261bfc58f748c2db068dc74482d391ce130/dask/array/utils.py#L103-L104

**Comment by oarcher** [comment]
I think that we need to enforce meta `dtype` (as you proposed with `meta_from_array(args[0], dtype=dtype)`, because without, the resulting dataarray have not the correct `dtype`:

```python
da.arange(10,chunks=5).map_blocks(lambda x: (x+0.5).astype('f4'), dtype='f4')
Out[1]: dask.array<lambda, shape=(10,), dtype=int64, chunksize=(5,), chunktype=numpy.ndarray>
```

With `meta_from_array(args[0], dtype=dtype)`, it's ok, but perhaps that we could add a warning filter in https://github.com/dask/dask/blob/34fd6261bfc58f748c2db068dc74482d391ce130/dask/array/utils.py#L103-L104 

Because there is a useless warning message with complex numbers:

```python
da.arange(10,chunks=5).astype('c16').map_blocks(lambda x: np.abs(x).astype('f4'), dtype='f4')
/home/oarcher/git/dask/dask/array/utils.py:104: ComplexWarning: Casting complex values to real discards the imaginary part
  meta = meta.astype(dtype)
Out[1]: dask.array<lambda, shape=(10,), dtype=float32, chunksize=(5,), chunktype=numpy.ndarray>
```

**Comment by pentschev** [comment]
That's not a useless message, in your lambda `np.abs` is actually casting to `float64`, that's why you don't get the same warning there when you do `astype('f4')`. However, this is the downside of not doing the full path with `compute_meta`, in `compute_meta` we actually execute the `np.abs` on `meta` to ensure it gets also the correct `dtype`. In the particular case above, we would be fine in just filtering out `ComplexWarning`, but I don't know how many more casts could raise some warnings when casting, and I believe we don't want to treat all possible cases in there. @TomAugspurger any suggestions/preferences on how we should address this sort of warning?

**Comment by pentschev** [comment]
We're actually filtering that via NumPy already in https://github.com/dask/dask/blob/8a699223982ce8425f59f048d0163090b4a81193/dask/array/utils.py#L110-L111

I forgot this existed, but simply adding those two lines before `meta = meta_from_array(args[0], dtype=dtype)` seems to resolve the issue. I'm not certain this is the best solution overall (including for `compute_meta`), but we already have a precedent for that, so let's use it to resolve this issue and iterate in the future if we find problems with it later.

**Comment by pentschev** [comment]
I was running Dask's test suite and with just master I see 66 fails, I didn't go through all of them to see if something is wrong or missing in my environment, but that's definitely more than 0 failures which is what I expected. Then I ran the suite with the following changes:

```python
    if meta is None:
        from .utils import compute_meta, meta_from_array

        if dtype is not None:
            if all([type(meta_from_array(a)) is type(meta_from_array(args[0])) for a in args[::2]]):
                with np.errstate(all="ignore"), warnings.catch_warnings():
                    warnings.simplefilter("ignore", category=RuntimeWarning)
                    meta = meta_from_array(args[0], dtype=dtype)
            else:
                warnings.warn("args have different meta, you should provide meta= explicitly "
                              "if dtype is provided to prevent meta computation on empty arrays")
                meta = compute_meta(func, dtype, *args[::2], **kwargs)
```

With the changes above I see 351 failed tests, or a total of 255 new tests failing. Removing the warning, I see 205 tests failing. Those changes are changing some of the existing expected behavior in Dask, I didn't have time to look into that in more detail yet. It's also important to note that only because of the warning we see almost 150 tests failing, this seems like it's going to turn into a major hassle for existing user code, thus I would suggest we document the behavior but don't print warnings.

That still leaves us with another about 150 failing tests to tackle, so I think this is going to take a while.

Finally, just to be sure we weren't doing something wrong, I also ran the code from https://github.com/dask/dask/issues/6690#issuecomment-703858616, and with that I see almost 500 new failing tests. It seems that the solution I suggested in above in this comment is better, but we'll have to fix it further. I'm not sure how soon I'll be able to look into all that.

**Comment by oarcher** [comment]
ouch ! I'm afraid I wont be able to help for those sides effects. But, regarding the reason of opening this issue, perhaps that we can fallback to option 1 in https://github.com/dask/dask/issues/6690#issuecomment-701481444 :
> 1. Just update the docs. Instruct users to specify both dtype and meta

but *both* ? I think just `meta` is ok:

```python
import dask.array as da
import numpy as np

def func(block):
    print("func called")
    return np.abs(block).astype('f4')

data = da.arange(10,chunks=5).astype('c16')

# incorrect, func is called
In[1]: data.map_blocks(func, dtype='f4')

func called
Out[1]: dask.array<func, shape=(10,), dtype=float32, chunksize=(5,), chunktype=numpy.ndarray>

# correct, func is not called, and output dtype is ok
In[2]: data.map_blocks(func, meta=np.array([],dtype='f4'))
Out[2]: dask.array<func, shape=(10,), dtype=float32, chunksize=(5,), chunktype=numpy.ndarray>

# specifying both dtype and meta is confusing (dtype not used)
In[3]: data.map_blocks(func, dtype='f8', meta=np.array([],dtype='f4'))
Out[3]: dask.array<func, shape=(10,), dtype=float32, chunksize=(5,), chunktype=numpy.ndarray>

```

So from my user point of vue, the doc should promote the use of `meta` instead of `dtype` to avoid function call. There is no needs to use `dtype` keyword, as the `dtype` can be specified in `meta` (probably linked to https://github.com/dask/dask/issues/5007 ?)

**Comment by TomAugspurger** [comment]
My only light objection to specifying `meta` is that it's slightly more
annoying to type, especially if you're trying to get the dimensionality of
the array correct.

Dask DataFrame allows a shorthand notation like

    meta=("name", "int64")

as a shorthand for

    meta = pd.Series(np.array([], dtype="int64"), name="name")

We could do something similar for array, something like
`meta=(ndarray_type, ndim, dtype)`.

**Comment by pentschev** [comment]
Yes, I think we should definitely update the docs for now. TBH, I'm not sure how we can improve that further at this point.

> We could do something similar for array, something like `meta=(ndarray_type, ndim, dtype)`.

You can use `meta=meta_from_array(ndarray_type, ndim, dtype)`, does that work for you?

**Comment by oarcher** [comment]
Yes, using `meta=meta_from_array(ndarray_type, ndim, dtype)` seems to work as expected:

```python
import dask.array as da
from dask.array.utils import meta_from_array
import numpy as np


def func(block):
    print("func called")
    return np.abs(block).astype('f4')

data = da.arange(10,chunks=5).astype('c16')


data.map_blocks(func, meta=meta_from_array(np.ndarray,1,dtype='f4'))

Out[1]: dask.array<func, shape=(10,), dtype=float32, chunksize=(5,), chunktype=numpy.ndarray>
```

**Comment by pentschev** [comment]
Just FYI, I opened https://github.com/dask/dask/pull/6763 to document `meta`, let me know if I missed something.

**Comment by jrbourbeau** [comment]
It seems https://github.com/dask/dask/pull/6763 closes this issue. @oarcher  feel free to re-open if that's not the case
