### ISSUE TITLE
docs: args don't seem to show up properly

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6696]
E.g. see https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_parquet

You see things like `pathstring or list`. Believe it should be `path: string or list`

![image](https://user-images.githubusercontent.com/17162724/94862385-e6987c80-0406-11eb-8841-15290dfa1b6a.png)

**Comment by mrocklin** [comment]
Thanks for raising this @raybellwaves .

This came up before I think, and was maybe resolved by tweaking which numpydoc version we used?  cc @gforsyth , who maybe helped us to resolve this last time?

**Comment by gforsyth** [comment]
Got it.  Fixes incoming

**Comment by gforsyth** [comment]
Well, corporate proxy is blocking image uploads, but I have the colons restored via a fix to the `dask-sphinx-theme` and PRs in to pull in that change once the fix PR is merged and a new release is cut.

**Comment by raybellwaves** [comment]
Yep. Thanks

![image](https://user-images.githubusercontent.com/17162724/94965705-f4fb9c80-04c9-11eb-90c2-b4ad6cf875a3.png)

**Comment by mrocklin** [comment]
Woot. Thanks everyone!

**Comment by raybellwaves** [comment]
Am I right that is happening again?

https://docs.dask.org/en/stable/dataframe-api.html#dask.dataframe.read_parquet

![Screen Shot 2021-05-27 at 4 49 53 PM](https://user-images.githubusercontent.com/17162724/119895282-988f3680-bf0b-11eb-97ed-0552bcfe238b.png)

**Comment by gforsyth** [comment]
> Am I right that is happening again?

Yep.  Curses

**Comment by ncclementi** [comment]
Closing this, since it's currently fixed.

![Screen Shot 2021-09-15 at 9 13 26 PM](https://user-images.githubusercontent.com/7526622/133533451-88dcc76c-d09c-46de-9544-29a7f44a25c3.png)
