### ISSUE TITLE
Documentation: how to Manage Python Dependencies

### ISSUE THREAD

**Issue by mulka** [dask/dask#6702]
I feel like this is something that should be covered in the documentation for Dask, but couldn't really find it. Basically, how do people make sure python code in other project files is accessible to the workers?
https://stackoverflow.com/questions/63944610/how-do-people-generally-manage-dependencies-for-their-tasks-in-dask

**Comment by quasiben** [comment]
We have a section in the FAQ which covers a bit of this:
https://distributed.dask.org/en/latest/faq.html#how-do-i-use-external-modules

Perhaps this could be expanded to included other recommendations like bundling things in `conda-pack` ?
