### ISSUE TITLE
Dask docs apostrophe rendering issue

### ISSUE THREAD

**Issue by jsignell** [dask/dask#6704]
I think it's the apostrophes that are having some weird rendering issues on the dask docs: 

![image](https://user-images.githubusercontent.com/4806877/95089161-ce1faf00-06f1-11eb-835f-7e2d304ca7f2.png)

@gforsyth - maybe you know what the deal is?

**Comment by jrbourbeau** [comment]
FWIW I also observe this strange rendering issue on Chrome, but Firefox (shown below) seems okay 

<img width="1552" alt="Screen Shot 2020-10-05 at 9 32 00 AM" src="https://user-images.githubusercontent.com/11656932/95092782-a6c6e300-06ed-11eb-9d7e-1c0a0f830b37.png">

**Comment by jrbourbeau** [comment]
Closing as this was fixed by https://github.com/dask/dask-sphinx-theme/pull/48. We're still observing some strange symbols on Chrome, but are tracking it over in https://github.com/dask/dask-sphinx-theme/issues/47
