### ISSUE TITLE
map_overlap predicts the wrong shape when `trim` is false

### ISSUE THREAD

**Issue by d-v-b** [dask/dask#6717]
```python
data = da.zeros((10,10), chunks=(5,5))

def func(v):
    return v

arr = da.map_overlap(func, data, depth={0: 1, 1: 1}, trim=False, boundary=10)
print(arr.shape)
arr.compute().shape
```
returns 
```
(10, 10)
(14, 14)
```

**Comment by d-v-b** [comment]
after thinking about it a more (specifically, reading the docstring a bit more :) ) it seems like this isn't a bug at all. closing.

**Comment by jsignell** [comment]
@d-v-b I just changed the behavior to match the docstring, so glad you think it's ok :)
