### ISSUE TITLE
Apparent speed regression between Dask 2.12.0 and 2.29.0 & Pandas with `apply`

### ISSUE THREAD

**Issue by ianozsvald** [dask/dask#6726]
I see a significant speed decrease (taking over 2x longer) using a recent version of Dask with Pandas with `apply` compared to using a version from earlier this year for single-machine parallelism. 

I'm using `raw=True` (to cut out more Pandas) but the same behaviour exists without using `raw=True`. I'm using this on my personal laptop (4 core, 4 hyperthread), I'm running the same code using 4 different `conda` environments to show the behaviour.

The same speed slowdowns are confirmed on a colleague's AMD laptop.

Background - this example is derived from my private "Higher Performance Python" training course, I'm giving another iteration this coming week and I see the speed difference compared to the last iteration of the course back in April 2020 (I still have that conda environment).

I provide a code sample below and 4 example run times, each repeated for stable results. The code makes a large random block of data (1M rows * 14 columns), applies a simple `work` function (taking the NumPy mean) and runs this in parallel with 8 partitions.

My training example uses variants of Ordinary Least Squared (costing more time than the mean) with raw NumPy arrays and Pandas Series, the behaviour is the same and significant. The training course also adds a Numba-compiled `work` function which gives even worse results but I think starting with a clear first example might be best.

I haven't tried more library combinations, I figured it best to check if this can be verified and if any obvious library updates might explain this. I've read the https://distributed.dask.org/en/latest/changelog.html and nothing leapt out, I see nothing pertinent in a scan of open & closed Issue (but I haven't studied any in depth).

Each configuration is built using a `conda` Python environment with specified versions of the core libraries installed.

**What happened**:

## April version of the libraries with a current Python 3.8 

```
scratch$ python dask_pandas_speed_check.py 
Python: sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
Dask 2.12.0, Pandas 1.0.1
(1000000, 10)
(1000000,)
Dask took 1.74s
# conda create -n hpp_dask_a python=3.8 dask=2.12.0 pandas=1.0.1 jupyter matplotlib 
```

## same Dask, newer Pandas - slower

```
python dask_pandas_speed_check.py 
Python: sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
Dask 2.12.0, Pandas 1.1.2
(1000000, 10)
(1000000,)
Dask took 2.37s
# conda create -n hpp_dask_b python=3.8 dask=2.12.0 pandas=1.1.2 jupyter matplotlib
```

## new Dask, older Pandas - slower again 

```
python dask_pandas_speed_check.py 
Python: sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
Dask 2.29.0, Pandas 1.0.1
(1000000, 10)
(1000000,)
Dask took 2.91s
# conda create -n hpp_dask_c python=3.8 dask=2.29.0 pandas=1.0.1 jupyter matplotlib

```

## new Dask, new Pandas - slowest by far 

```
python dask_pandas_speed_check.py 
Python: sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
Dask 2.29.0, Pandas 1.1.2
(1000000, 10)
(1000000,)
Dask took 3.62s
```

**Minimal Complete Verifiable Example**:

```python
import sys
import time
import numpy as np
from numpy.testing import assert_array_almost_equal
import dask.dataframe as dd
import pandas as pd
import dask

def work(row):
    # silly worker function
    return row.mean()

if __name__ == "__main__":
    print("Python:", sys.version_info)
    print(f"Dask {dask.__version__}, Pandas {pd.__version__}")

    # make a large block of random dummy data
    arr = np.random.random(size=(1_000_000, 10))
    df = pd.DataFrame(arr)
    print(df.shape)
    
    # Use Pandas raw apply to get canonical answer
    results_with_apply = df.apply(work, axis=1, raw=True)

    # Make Dask do the same job
    N_PARTITIONS = 8 # Ian has 4 cores & 4 hyperthreads
    ddf = dd.from_pandas(df, npartitions=N_PARTITIONS, sort=False)
    SCHEDULER = "processes"

    # Time Dask on raw apply
    t1 = time.time()
    results_with_dask_raw = ddf.apply(work, axis=1, meta=(None, 'float64',), raw=True).compute(scheduler=SCHEDULER)
    t2 = time.time()
    print(results_with_dask_raw.shape)
    assert_array_almost_equal(results_with_apply, results_with_dask_raw)  
    print(f"Dask took {t2-t1:0.2f}s")
```

**Anything else we need to know?**:

**Environment**:

Linux Mint, Dell hardware:

```
$ inxi --full
System:    Host: ian-XPS-15-9550 Kernel: 5.8.1-050801-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia 
Machine:   Type: Laptop System: Dell product: XPS 15 9550 v: N/A serial: <root required> 
           Mobo: Dell model: 0N7TVV v: A00 serial: <root required> UEFI [Legacy]: Dell v: 1.9.0 date: 10/11/2018 
Battery:   ID-1: BAT0 charge: 18.7 Wh condition: 81.1/84.0 Wh (97%) 
CPU:       Topology: Quad Core model: Intel Core i7-6700HQ bits: 64 type: MT MCP L2 cache: 6144 KiB 
           Speed: 1655 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 1655 2: 1674 3: 2369 4: 1863 5: 1656 6: 1266 7: 1356 
           8: 2247 
Graphics:  Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
           Device-2: NVIDIA GM107M [GeForce GTX 960M] driver: N/A 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 3840x2160~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (SKL GT2) v: 4.6 Mesa 20.0.8 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.8.1-050801-generic 
Network:   Device-1: Intel Wireless 8260 driver: iwlwifi 
           IF: wlp2s0 state: up mac: a4:34:d9:6d:0e:f2 
Drives:    Local Storage: total: 953.87 GiB used: 629.25 GiB (66.0%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: PM951 NVMe 1024GB size: 953.87 GiB 
Partition: ID-1: / size: 884.70 GiB used: 628.47 GiB (71.0%) fs: ext4 dev: /dev/dm-1 
           ID-2: /boot size: 703.5 MiB used: 492.0 MiB (69.9%) fs: ext4 dev: /dev/nvme0n1p1 
           ID-3: swap-1 size: 31.50 GiB used: 305.8 MiB (0.9%) fs: swap dev: /dev/dm-2 
Sensors:   System Temperatures: cpu: 46.0 C mobo: 32.0 C sodimm: 40.0 C 
           Fan Speeds (RPM): cpu: 2501 
Info:      Processes: 313 Uptime: 19d 3h 47m Memory: 31.13 GiB used: 8.55 GiB (27.5%) Shell: bash inxi: 3.0.32 
```

**Comment by TomAugspurger** [comment]
Thanks for the (excellent) report.

I wonder if https://github.com/dask/dask/pull/4003 is to partially to blame. We can check that by setting `DASK_MULTIPROCESSING__CONTEXT`. With that I get

DASK_MULTIPROCESSING__CONTEXT | time
----------------------------- | ----
spawn (default)               | 6.2
forkserver                    | 5.74
fork                          | 2.8

The typical solution is to pre-configure a `Pool` to use for all the computations (rather than starting it on demand). If I modify the code to use an existing process `Pool` things at first seem poor still,

```python
from multiprocessing.pool import Pool
pool = Pool(N_PARTITIONS)

with dask.config.set(pool=pool):
    # Time Dask on raw apply
    t1 = time.time()
    results_with_dask_raw = ddf.apply(work, axis=1, meta=(None, 'float64',), raw=True).compute(scheduler=SCHEDULER)
    t2 = time.time()
    assert_array_almost_equal(results_with_apply, results_with_dask_raw)
    print(f"Dask took {t2-t1:0.2f}s")

Dask took 5.38s
```

But if we *reuse* the pool

```python
with dask.config.set(pool=pool):
    # Time Dask on raw apply
    t1 = time.time()
    results_with_dask_raw = ddf.apply(work, axis=1, meta=(None, 'float64',), raw=True).compute(scheduler=SCHEDULER)
    t2 = time.time()
    assert_array_almost_equal(results_with_apply, results_with_dask_raw)
    print(f"Dask took {t2-t1:0.2f}s")

Dask took 2.63s
```

So my best guess right now is that the switch to use `spawn` means that we have two additional sources of overhead

1. The startup time of the pool (which explains the 6.36s -> 5.38s on my machine, with no pre-configured pool to having a pool
2. Expensive imports like NumPy and pandas not cached (the 5.38s -> 2.63s from the first pool run to the second).


It's unfortunate that the change to `spawn` had this slowdown. It was done for usability reasons, but now to explain a "simple" example like this we need to teach users about things all sorts of things like import caching and pool creation overhead. On balance, I think the switch to spawn is still the right choice.

**Comment by ianozsvald** [comment]
@TomAugspurger I'm glad it was clear :-) It was quite a surprise given the size of the performance reduction and I wasn't sure if Pandas or Dask was the cause (it looks like blame can be assigned both ways).
Is there potential for a fix for using Dask DataFrames for parallel `apply`  to make expensive applies run faster, or is this "just the way it is now"?
Presumably if the cost of the applied function was sufficiently high and the dataframe sufficiently large in RAM, the new overheads would become trivial against the cost of the applied function, but that's not the case in my smaller example?

**Comment by TomAugspurger** [comment]
>  Is there potential for a fix for using Dask DataFrames for parallel apply to make expensive applies run faster, or is this "just the way it is now"?

Just to be clear, the actual cost of the parallel apply (probably) didn't change at all. It's all the overhead before it.

If we want a "fair" comparison of the parallelization you could

1. Set up a global pool `pool = multiprocessing.Pool()`
2. Initialize the pool (by running a function that does something like `import pandas` in each process)

and then do the ddf.apply(worker, ...)` inside a `with dask.config.set(pool=pool)`.

You could make an analogy to Numba where there's some one-time overhead (JIT-compiling the function). In the Dask case with multiple processes that's starting up the processes and doing the one-time setup like importing expensive modules.

>  Presumably if the cost of the applied function was sufficiently high and the dataframe sufficiently large in RAM, the new overheads would become trivial against the cost of the applied function, but that's not the case in my smaller example?

Yes, I think that's the case.

**Comment by ianozsvald** [comment]
Much obliged. Closing as I guess there's nothing to do here, cheers.
