### ISSUE TITLE
strange behavior for dask dataframe in client.map (read_csv very slow)

### ISSUE THREAD

**Issue by showkeyjar** [dask/dask#6733]
I create a Local Cluster set  n_workers=2, threads_per_worker=1
then map a function use dask dataframe to read_csv

**What happened**:
I found dask.dataframe.read_csv is very slowly(few minutes per 100 files). so I print the thread id
found dask.dataframe only use 2 threads.

**What you expected to happen**:

I use dask.dataframe.read_csv independent, it's run very fast (few seconds per 100 files)
I read dask document, dask.dataframe.read_csv will auto and efficent to create threads and read data
then I add num_workers=20 parameters to compute() function, but not work.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
logging.basicConfig(format="%(thread)d %(asctime)s %(name)s:%(levelname)s:%(lineno)d:%(message)s",
                    datefmt="%d-%m-%Y %H:%M:%S", level=logging.DEBUG)
logger = logging.getLogger(__name__)

def load_train_data(task_id):
  csv_files = glob.glob(str(task_id) +"/*.csv")
  ddf_samples = dd.read_csv(csv_files, error_bad_lines=False, blocksize=None)
  df_samples = ddf_samples.fillna(0).compute(num_workers=20)
  logger.debug("load csv data:" + str(len(df_samples)))
  return df_samples

cluster = LocalCluster(n_workers=2, threads_per_worker=1, memory_limit="25GB", local_directory="./logs/worker")
client = Client(cluster)
# because I want process different data flow in different tasks, so I create local cluster
process_tasks = client.map(load_train_data, range(20))
df_list = client.gather(process_tasks)
……
```

**Anything else we need to know?**:

**Environment**:

- Dask version:2.30.0
- Python version:3.8.5
- Operating System:CentOS 7.2
- Install method (conda, pip, source):conda

**Comment by jsignell** [comment]
I think you are seeing the expected behavior. If you throttle your cluster to only have 2 workers with 1 thread per worker then you will only have 2 threads working. 

The docs state:

> the multiprocessing and threaded schedulers each take a `num_workers` keyword, which sets the number of processes or threads to use (defaults to number of cores) - https://docs.dask.org/en/latest/scheduler-overview.html

In your example you are using the distributed scheduler, so the `num_workers` isn't valid. To get more workers or more threads per worker, you need to change the settings of your `LocalCluster`

**Comment by showkeyjar** [comment]
so, how could I effecient read_csv in client.map functions ?

**Comment by jsignell** [comment]
Just change the settings in your `LocalCluster` to have more workers or more threads: 

```python
cluster = LocalCluster(n_workers=4, threads_per_worker=3, memory_limit="25GB", local_directory="./logs/worker")
client = Client(cluster)
```

Or use an adaptive cluster by doing `cluster.adapt(minimum=2, maximum=10)`

**Comment by showkeyjar** [comment]
well, I got it. I'll try adapt

**Comment by brl0** [comment]
According to the dask distributed [docs](https://distributed.dask.org/en/latest/client.html#dask):
> When we create a Client object it registers itself as the default Dask scheduler. All .compute() methods will automatically start using the distributed system.

**Comment by TomAugspurger** [comment]
I think everything here has been answered. Thanks.
