### ISSUE TITLE
Fastavro iter_avro

### ISSUE THREAD

**Issue by lqrz** [dask/dask#6744]
Im trying to use the `bag.read_avro()` functionality, but I get the following error:

```
AttributeError: module 'fastavro' has no attribute 'iter_avro'
```

Here is the code to reproduce the case:

```
import dask.bag as db
path_input = './data/*.avro'
df = db.read_avro(path_input).compute()
```

From the fastavro (1.0.0.post1) doc, I get it should be calling `fastavro.reader` instead of `fastavro.iter_avro`:
https://github.com/fastavro/fastavro/blob/3474b6c8a2a38c7d39ca955a5e3d0261d6f3659f/fastavro/read.py

**Environment**:

- Dask version: 2.11.0
- Fastavro version: 1.0.0.post1
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Thanks for the report. IIUC, `fastavro` has changed their API? Do you want to update https://github.com/dask/dask/blob/7f5f7fe49298c2353977b99a081be47dc28bc358/dask/bag/avro.py to be compatible with it (and the old version too, ideally).

**Comment by martindurant** [comment]
Ref: https://github.com/dask/dask/pull/6740

**Comment by TomAugspurger** [comment]
@lqrz you gave a thumbsup to https://github.com/dask/dask/issues/6744#issuecomment-712036919. Does that mean you're looking into updating the code in dask.bag.avro?

**Comment by lqrz** [comment]
@TomAugspurger Hi, Tom! nono, I just intended to support your good interpretation of my original report 😄 ; but im not looking into it!
