### ISSUE TITLE
 `rolling().apply()` doesn't work with npartitions > 1

### ISSUE THREAD

**Issue by SGStino** [dask/dask#6750]
`rolling().apply()` doesn't work with npartitions > 1

**What happened**:
> NotImplementedError: Partition size is less than overlapping window size. Try using ``df.repartition`` to increase the partition size.

**What you expected to happen**:
For the operation to complete normally without error since the window size (100) is smaller than the partition size (1000)

**Minimal Complete Verifiable Example**:

```python
def wma(df):
    return df.sum() # implementation doesn't matter

r = range(10000)
i = pd.to_datetime('now') - pd.to_timedelta(r, unit='T')
df = pd.DataFrame(r, columns=['values'], index = i) 
df = df.reset_index() # try with int index, but original DatetimeIndex has the same error

ddf = dd.from_pandas(df, npartitions=1).repartition(partition_size=1000).rolling(100, min_periods=1).apply(wma, raw=False).compute()
```

**Anything else we need to know?**:

Considering there's #4248 as a feature request, I'm guessing this is a bug?

**Environment**:

- Dask version: 2.30
- Python version: 3.7.3
- Operating System: Jupyter-Dask docker
- Install method (conda, pip, source): Jupyter-Dask docker

**Comment by TomAugspurger** [comment]
A couple things:

1. `repartition` doesn't guarantee exactly `npartitions` or partitions of `partition_size`
2. `partition_size` is the size *in bytes*, not the number of rows.
```
partition_size: int or string, optional
    Max number of bytes of memory for each partition.
```

So you don't have length 100 partitions:

```python
In [15]: ddf.map_partitions(len).compute()
Out[15]:
0      62
1      62
2      62
3      62
4      62
       ..
156    62
157    62
158    62
159    62
160    63
Length: 161, dtype: int64
```

Improvements to the docs here would be welcome.

**Comment by SGStino** [comment]
ok, so, if it doesn't guarantee the size, the hint `ry using df.repartition to increase the partition size.` might not even help? Or is the guarantee more a "less than or equal" uncertainty?

I've implemented it manually now by creating delayed tasks for each partition with the previous partition as secondary input, concat them, trim and filter it out.
But a lot of the actual computation time is lost now in generating those tasks by iterating over the `npartitions`.

**Comment by TomAugspurger** [comment]
I think the hint is correct. You've asked for a rolling window of size `100` but your partitions are too small. Do you agree?

**Comment by SGStino** [comment]
I agree that they are to small, I just can't think of a way to make sure they aren't, aside from specifying npartitions = 1.

I might be wrong, still need to test it again, but I believe i tried npartitions = 2 also, with a total number of rows larger than two times the window size, so in theory, the partitions should have been bigger. 

But I was trying a lot of thins together, so I might have had something else wrong at that moment.

**Comment by jsignell** [comment]
I have been working on #6708 which implements rechunking if needed on `overlap` for arrays. I am wondering if something similar might be helpful here. With the current implementation of repartition, it is hard to ensure that chunks are at least a certain size. As an example I tried repartitioning the dataframe in the example to make each partition have len 100, but what I found was that instead of repartitioning into even parts, some partitions were combined to meet the requirement:

```python
import pandas as pd
import dask.dataframe as dd

def wma(df):
    return df.sum() # implementation doesn't matter

r = range(10000)
i = pd.to_datetime('now') - pd.to_timedelta(r, unit='T')
df = pd.DataFrame(r, columns=['values'], index = i) 
df = df.reset_index() # try with int index, but original DatetimeIndex has the same error

ddf = dd.from_pandas(df, npartitions=1).repartition(partition_size=1000)
ddf = ddf.repartition(npartitions=100)
output = ddf.rolling(100, min_periods=1).apply(wma, raw=False).compute()
```

```python
>>> ddf.map_partitions(len).compute()
0      62
1     124
2      62
3     124
4     124
     ... 
95    125
96    124
97     62
98    124
99    125
Length: 100, dtype: int64
```

**Comment by jsignell** [comment]
Actually, it looks like dd.from_pandas has a `chunksize` argument that will work really well here. 

```python
ddf = dd.from_pandas(df, chunksize=100)
```

For cases where you aren't using `from_pandas` you can always explicitly create the divisions between partitions. The values in this case are the values of the index at the start and end of the partition:

```python
import pandas as pd
import dask.dataframe as dd

def wma(df):
    return df.sum() # implementation doesn't matter

r = range(10000)
i = pd.to_datetime('now') - pd.to_timedelta(r, unit='T')
df = pd.DataFrame(r, columns=['values'], index = i) 
df = df.reset_index() # try with int index, but original DatetimeIndex has the same error

overlap = 100

# this assumes a monotonic integer index like you get when you call `df.reset_index()`
new_divisions = (*range(0, len(df.index) - overlap + 1, overlap), df.index[-1])
ddf = dd.from_pandas(df, npartitions=1).repartition(divisions=new_divisions)
ddf.rolling(overlap, min_periods=1).apply(wma, raw=False).compute()
```

I am going to close this now, since I think the documentation is sufficiently clear.
