### ISSUE TITLE
NotImplementedError: x.str.cat() with `others == None`

### ISSUE THREAD

**Issue by rohanrajpal** [dask/dask#6756]
If I want to simply do
```python
import dask.dataframe as dd
import numpy as np
import pandas as pd
df = pd.read_csv(
    "https://github.com/jbesomi/texthero/raw/master/dataset/bbcsport.csv"
)
ddf = dd.from_pandas(df,npartitions=3)
ddf['text'].str.cat(sep=' ')
```
I will get
```python
NotImplementedError                       Traceback (most recent call last)
<ipython-input-11-8ad82e989cd5> in <module>
      8 # s.str.cat(sep=' ')
      9 # ddf.head(100)
---> 10 ddf['text'].str.cat(sep=' ')

~/anaconda3/envs/namoenv/lib/python3.8/site-packages/dask/dataframe/accessor.py in cat(self, others, sep, na_rep)
    139 
    140         if others is None:
--> 141             raise NotImplementedError("x.str.cat() with `others == None`")
    142 
    143         valid_types = (Series, Index, pd.Series, pd.Index)

NotImplementedError: x.str.cat() with `others == None`
```

I see that this was brought up in #5655 . How do I go about implementing this if `others is None`? I did try googling around but couldn't figure out where to start

**Comment by jsignell** [comment]
I don't understand why you'd want to do this in dask with `others is None`. The result should be a string containing all the values in the 'text' column right? So what is the benefit of doing this in dask vs pandas?

**Comment by TomAugspurger** [comment]
I guess the only potential benefit is the parallelism in the `' '.join()` operation on each partition? But agreed this is a bit strange.

It can be implemented as a `map_partitions` followed by a final str.join

```python
In [30]: s = dd.from_pandas(pd.Series(['a', 'b', 'c', 'd']), 2)

In [31]: dask.delayed(' '.join)(s.map_partitions(lambda x: x.str.cat(sep=' ')).to_delayed()).compute()
Out[31]: 'a b c d'
```

Probably some issues with missing values in that implementation. I dunno what pandas does.

**Comment by rohanrajpal** [comment]
Yep @TomAugspurger, I have a huge dataset and was finding ways to speed things up. Thanks for the snippet!

**Comment by jsignell** [comment]
Oh that makes sense. Didn't mean to sound overly sceptical! Are you interested in adding this to dask or is the workaround good enough?

**Comment by rohanrajpal** [comment]
> Oh that makes sense. Didn't mean to sound overly sceptical! Are you interested in adding this to dask or is the workaround good enough?

The workaround works for me now. But I won't mind adding this functionality, it would be more convenient for me in the future. So feel free to assign me this issue and I'll start working on it.

Also sorry for the late reply, I missed the notification somehow!

**Comment by jsignell** [comment]
Ok sounds good! Feel free to take it on!

**Comment by martindurant** [comment]
I think this issue can be closed, as the immediate problem is solved.

**Comment by rohanrajpal** [comment]
> Ok sounds good! Feel free to take it on!

Great! Will reach out when I make some progress

**Comment by rohanrajpal** [comment]
> I think this issue can be closed, as the immediate problem is solved.

Sure, thanks a lot everyone :smile:
