### ISSUE TITLE
Left Singular Values of Compressed SVD small mistake

### ISSUE THREAD

**Issue by RogerMoens** [dask/dask#6757]
Hi all,

Comparing the dask compressed svd implementation with a GESVD implementation (e.g. as available in SCIPY), I remarked that the left singular values obtained via svd_compressed are not "right" (pun intended). I found that in the linalg.py code 'u' is not transposed, where it should. The mistake is in the svd_compressed function (line 750-751 in linalg.py):

    v, s, u = tsqr(a_compressed.T, compute_svd=True)
    u = comp.T.dot(u)

should be

    v, s, u = tsqr(a_compressed.T, compute_svd=True)
    u = comp.T.dot(u.T)

Why? Well if a = u s v.T, then a.T = v s u.T. However, since u in this case is a square matrix, both comp.T.dot(u) as well as comp.T.dot(u.T) are "valid" in a matrix multiplication sense, that is the reason I think this has been overlooked. If you want to retrieve the correct left singular vectors then u should be first transposed, because tsqr gives you u.T back and not u, so a better description would be v, s, ut = tsqr(a_compressed.T, compute_svd=True).

I will try to have a minimal code example, but don't have the time atm. I have included some graphs where I compare the left and right singular vectors of the GESVD and dask compressed (cosine similarity, low values corresponds to small angle between the two corresponding vectors), before and after adding a transpose. I also included a normalized frobenius and 2-norm comparison (in %) of the "reconstructed matrices" w.r.t. GESVD.

**Singular values before transpose:**
![s](https://user-images.githubusercontent.com/45488927/96731817-f7aa2d00-13b7-11eb-9656-f3bbecb240b9.png)
**Singular values after transpose:**
![s_updated](https://user-images.githubusercontent.com/45488927/96731815-f7aa2d00-13b7-11eb-8091-622a31b5cf69.png)

**Left singular vectors before transpose:**
![u](https://user-images.githubusercontent.com/45488927/96731822-f842c380-13b7-11eb-8c26-2e82caa24a27.png)
**Left singular vectors after transpose (this is where the difference is made):**
![u_updated](https://user-images.githubusercontent.com/45488927/96731819-f842c380-13b7-11eb-975d-cefdc58ef617.png)

**Right singular vectors before transpose:** 
![vt](https://user-images.githubusercontent.com/45488927/96731827-f8db5a00-13b7-11eb-9a73-725cc6df9f1f.png)
**Right singular vectors after transpose (differences w.r.t. before transpose are randomization related):**
![vt_updated](https://user-images.githubusercontent.com/45488927/96731825-f8db5a00-13b7-11eb-9a04-fcc995ce116a.png)

**General comparison before transpose:**
![frob_before](https://user-images.githubusercontent.com/45488927/96731814-f7aa2d00-13b7-11eb-8204-656fded961b7.png)
**General comparison after transpose:**
![frob_after](https://user-images.githubusercontent.com/45488927/96731809-f7119680-13b7-11eb-9a2f-bd2fb436c3db.png)

Those comparisons 

- Dask version: all
- Python version: all

Kind regards,

Roger
P.S. not sure why Mariano Tepper used the Randomized Power Iteration (algorithm 4.3 in Halko et al. paper) instead of the more accurate algorithm 4.4, of that same paper.

Edit: as clarification for the used measures:
<img width="302" alt="Screenshot 2020-10-22 at 08 12 28" src="https://user-images.githubusercontent.com/45488927/96832042-63cf7400-143e-11eb-835e-c698542d7c69.png">

**Comment by RogerMoens** [comment]
Also the more accurate version I was referring to, would be something like this:

`def compression_matrix_updated(data, q, n_power_iter=0, seed=None, compute=False):
    """Randomly sample matrix to find most active subspace
    This compression matrix returned by this algorithm can be used to
    compute both the QR decomposition and the Singular Value
    Decomposition.
    Parameters
    ----------
    data: Array
    q: int
        Size of the desired subspace (the actual size will be bigger,
        because of oversampling, see ``da.linalg.compression_level``)
    n_power_iter: int
        number of power iterations, useful when the singular values of
        the input matrix decay very slowly.
    compute : bool
        Whether or not to compute data at each use.
        Recomputing the input while performing several passes reduces memory
        pressure, but means that we have to compute the input multiple times.
        This is a good choice if the data is larger than memory and cheap to
        recreate.
    References
    ----------
    N. Halko, P. G. Martinsson, and J. A. Tropp.
    Finding structure with randomness: Probabilistic algorithms for
    constructing approximate matrix decompositions.
    SIAM Rev., Survey and Review section, Vol. 53, num. 2,
    pp. 217-288, June 2011
    https://arxiv.org/abs/0909.4061
    """
    m, n = data.shape
    comp_level = compression_level(min(m, n), q)
    if isinstance(seed, RandomState):
        state = seed
    else:
        state = RandomState(seed)
    omega = state.standard_normal(
        size=(n, comp_level), chunks=(data.chunks[1], (comp_level,))
    )
    
    q, _ = qr(data.dot(omega))
    
    # power iteration: referring to algorithm 4.4 of the Halko et al. paper:
    for j in range(n_power_iter):
        q, _ = qr(data.T.dot(q))
        q, _ = qr(data.dot(q))
    
    return q`

and

`def svd_compressed_updated(a, k, n_power_iter=0, seed=None, compute=False, coerce_signs=False):
    """Randomly compressed rank-k thin Singular Value Decomposition.
    This computes the approximate singular value decomposition of a large
    array.  This algorithm is generally faster than the normal algorithm
    but does not provide exact results.  One can balance between
    performance and accuracy with input parameters (see below).
    Parameters
    ----------
    a: Array
        Input array
    k: int
        Rank of the desired thin SVD decomposition.
    n_power_iter: int
        Number of power iterations, useful when the singular values
        decay slowly. Error decreases exponentially as n_power_iter
        increases. In practice, set n_power_iter <= 4.
    compute : bool
        Whether or not to compute data at each use.
        Recomputing the input while performing several passes reduces memory
        pressure, but means that we have to compute the input multiple times.
        This is a good choice if the data is larger than memory and cheap to
        recreate.
    coerce_signs : bool
        Whether or not to apply sign coercion to singular vectors in
        order to maintain deterministic results, by default True.
    Examples
    --------
    >>> u, s, vt = svd_compressed(x, 20)  # doctest: +SKIP
    Returns
    -------
    u:  Array, unitary / orthogonal
    s:  Array, singular values in decreasing order (largest first)
    v:  Array, unitary / orthogonal
    References
    ----------
    N. Halko, P. G. Martinsson, and J. A. Tropp.
    Finding structure with randomness: Probabilistic algorithms for
    constructing approximate matrix decompositions.
    SIAM Rev., Survey and Review section, Vol. 53, num. 2,
    pp. 217-288, June 2011
    https://arxiv.org/abs/0909.4061
    """
    q = compression_matrix_updated(
        a, k, n_power_iter=n_power_iter, seed=seed, compute=compute
    )
    if compute:
        q = q.persist()
        wait(q)
    b = (q.T).dot(a)

    u, s, vt = tsqr(b.T, compute_svd=True)
    u, s, vt = vt.T, s, u.T
    
    u = q.dot(u)
    u = u[:, :k]
    s = s[:k]
    vt = vt[:k, :]
    return u, s, vt`

With higher accuracy:

![s](https://user-images.githubusercontent.com/45488927/96739578-39d76c80-13c0-11eb-9b02-3e619ea2f7ea.png)
![Screenshot 2020-10-21 at 17 09 33](https://user-images.githubusercontent.com/45488927/96739581-3a700300-13c0-11eb-8e04-46da88d848a8.png)
![u](https://user-images.githubusercontent.com/45488927/96739582-3a700300-13c0-11eb-9b94-9abb0f500a20.png)
![vt](https://user-images.githubusercontent.com/45488927/96739583-3b089980-13c0-11eb-8ffd-63436c22dc11.png)

Best regards,


Roger

**Comment by TomAugspurger** [comment]
Thanks for the report. @eric-czech do you have a chance to comment?

**Comment by eric-czech** [comment]
Should it be `comp.T.dot(u)` instead of `comp.T.dot(u.T)` @RogerMoens?  Getting `v s u.T` out of a transposed input makes sense, but I don't know enough about the paper to say if it really should be `comp.T.dot(u)`.  

That's great to know though if it's wrong!  We have gone as far as validating the right singular vectors and singular values against the sklearn randomized svd implementation (for PCA), but we haven't checked the left singular vectors against anything.

**Comment by RogerMoens** [comment]
Dear Eric,

It should be comp.T.dot(u.T) instead of comp.T.dot(u) (line 751). The essence is not that hard to grasp, and maybe to give you some insight into how it is structured a little recap to make sure that we are on the same line. Following the structure as explained in the paper, citing the interesting parts here :

**Stage A:** "_Compute an approximate basis for the range of the input matrix A._" i.e. finding Q
**Stage B:** "_Given a matrix Q, ..., we use Q to help compute a standard factorization of A_"


### Stage A (function compression_matrix in linalg)
Stage A (function compression_matrix in linalg) consists of sampling the columns of your original matrix (there is also a small error in there: [see issue 2849](https://github.com/dask/dask/issues/2849)). After sampling, an additional step is performed, which is the power iteration. 

Why? "_The techniques (without power iteration) described ... work well for matrices whose singular values exhibit some decay, but they may produce a poor basis when the input matrix has a flat singular spectrum or when the input matrix is very large_" 

Ok clear! But why multiplying with my original data matrix? "_The intuition behind these techniques is that the singular vectors associated with small singular values interfere with the calculation, so we reduce their weight relative to the dominant singular vectors by taking powers of the matrix to be analyzed._"

Ok cool! However, the method that is in place now has some downsides: "_Unfortunately, when the power iteration (as given above) is executed in floating point arithmetic, rounding errors will extinguish all information pertaining to singular modes associated with singular values that are small compared with ||A||_". The solution here is to use a QR decompositions, which is called subspace iteration (instead of power iteration). I have given the code in my second post here above.

### Stage B (function svd_compressed in linalg)
To help our standard factorization algorithm, we form a low-rank matrix B as follows: B = Q.T A . Why this one? Well, we now that A = QB (approximatively, assuming that Q.T Q = I). To make the link to the code, B is a_compressed. And actually, we can now compute the SVD on B as it is way smaller than our original matrix A is, such that: B = U S V.T . The final step is to multiply Q and U: A = (QU) S V.T . This is where the mistake is in the code.

Mariano Tepper chose to do the SVD via the tsqr function. I think that this is also not necessary as your a_compressed will be small enough to fit in memory and in-memory linear algebra is as fast as you can get. The largest this matrix will be is (r x n), where r is the approximated matrix rank (what is required as input from the user) and n is the number of rows (as A in R^{m x n}). A nice reference is [this review paper](http://www.netlib.org/utk/people/JackDongarra/PAPERS/siam-svd-2018.pdf), where they actually compare in-memory with distributed (sca)lapack implementations, also in the paper that is used for sfqr [(paper link).](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6691583&casa_token=r1qeLC_2wScAAAAA:AvL-RyP1JNBKIoES0hGatbplYIZIGFpPx8B16XKhqQ-mOsst6WhW0P0MG1lO4dm5T7P1XKIzVw&tag=1) one states: "_Thus, we do not expect numerical linear algebra algorithms for MapReduce to be faster than state-of-the-art in-memory MPI implementations running on clusters with high-performance interconnects_". where the MPI implementations are e.g. scalapack, so normal lapack should clearly outperform the MapReduce. However, I am not sure how faster it would be and of course this is under the assumption that B fits in-memory. 

Nevertheless, because Mariano Tepper used tsqr, the matrix should be certainly tall and skinny, such that he had to transpose the matrix B, as B (or a_compressed) should always be "fat". That means that when you do an svd on a.T: a.T = v s **u.T**, under the assumption that a = u s v.T. That statement is outputted in:

v, s, **u** = tsqr(a_compressed.T, compute_svd=True)

However, this is _not correct_ because we don't obtain u from the svd (via the tsqr) but **u.T**. The final step is then, as explained at the start of this "chapter" on Stage B, to multiply U back with our Q to obtain A = Q B = (QU) S V.T . So that is the last step that is performed:

u = comp.T.dot(u)

in this comp.T is our Q (the extra transpose comes from the fact that in compression_matrix the output is transposed). But of course this is not correct, u should be transposed as u is not u but u.T as the svd function (in this case tsqr) gives one give right singular vectors of the input matrix back as transposed. 


_______________________

Short version:

NOW on line 751 of linalg: u = comp.T.dot(u)
SHOULD BECOME: u = comp.T.dot(u.T)

Hopefully, this makes it a bit clearer? I hope this gives you some insight in how the algorithm works and how it is implemented. Also doing the subspace iteration would be a big gain (see my second post for the accuracy). sklearn has also a LU decomposition implemented (see [extmath](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/extmath.py)) but you can mainly choose in their implementation via the "power_iteration_normalizer" option. I also just saw that they implement the svd via the true svd and not via sfqr implementation. Also you could again consider to do it via a GESVD or GESDD, the latter is faster in most cases, although a bit less accurate than GESVD and uses more memory. In the sklearn implementation they also don't transpose B before svding. 


Hopefully, this makes things clear. I have tried to be as complete as possible.

Best regards,


Roger

**Comment by mrocklin** [comment]
@RogerMoens thank you for your clear and thorough analysis.  Also, I see that you just joined GitHub.  Welcome!

Are you interested in contributing a patch with your proposed changes?

**Comment by mrocklin** [comment]
(no expectation of course, but it seems like you're an expert here, and we could use more of those :) )

**Comment by RogerMoens** [comment]
Thanks @mrocklin! And yes, I can help with a patch, I'll probably have some time over the weekend. How does it work in practice? I have to make a pull request and make the proposed changes to the linalg.py file?

**Comment by mrocklin** [comment]
Yes, that's correct.  Here are some maybe-helpful resources

https://docs.dask.org/en/latest/develop.html
https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#working-with-the-code

We're also happy to help first-timers get started.  If you need help please speak up and we're happy to walk you through it.

**Comment by eric-czech** [comment]
Thanks for that explanation @RogerMoens!  That change sounds great to me and I’m happy to test it out and/or contribute to the PR review (on vacation now for a while yet though). 

I would certainly be curious to see how different iteration algorithms might effect efficiency.  PCA is an important use case for us in genetics so any kind of SVD approximation is valuable.

**Comment by RogerMoens** [comment]
@mrocklin: thanks! I have just tried to commit a first fix to see where it can be improved before I do any other adjustments. Is this the way to go or am I missing some vital information?

- I have set up a Docker ubuntu 20.04 with simple Python 3.8.5 installed (I am looking into changing that to a conda environment). Should I share the environment etc. for the update?
- How do I properly add tests: do I just propose them? @eric-czech Probably also some new ones need to be added for the functionalities I propose to add.
- I just saw that I forgot to parse Black/Flake8 before to commit and pull (although a simple transpose won't be a big problem for PEP8), will try to run that first for the following commits
- Is there any other information that I need to put in the pull?

I am planning to do the following updates/fixes in individual branches:
- [x] Change the transpose of u
- [ ] Fix the promotion to float64 in the column sampling
- [ ] Properly propage the number of oversamples and number of iterations towards randomized_svd
- [ ] Add QR iteration option
- [ ] Add LU iteration option
- [ ] Review the SVD
- [ ] Update the inline docs and general documentation

I will need some help for the latter as the GESVD/GESDD might be more useful than the tsqr if the compressed matrix fits into memory. The question is, how to decide whether it is or not? Or maybe leave it as an option for the user to decide and make tsqr as default.

Cheers,


Roger

**Comment by eric-czech** [comment]
Hey @RogerMoens, thanks again for working on this!  To your points:

> How do I properly add tests: do I just propose them? @eric-czech Probably also some new ones need to be added for the functionalities I propose to add.

If you add some in pull requests, I'll gladly review them and help think about others that might be worth including.  If I recall correctly, I don't think the current `svd_compressed` testing is very comprehensive.

The obvious test possibility that jumped out to me here is to compare `u`, `s`, and `v` from `svd` to `svd_compressed`.  I'm surprised that doesn't already happen in https://github.com/dask/dask/blob/80239dab180ea9b2a444ef03b1998cf9fd589292/dask/array/tests/test_linalg.py#L453.  I have found it to be a little tricky to make direct comparisons between results from `svd_compressed` and other non-chunked, deterministic implementations but not impossible (e.g. https://github.com/pystatgen/sgkit/blob/682d58fbb39f91fcf7e441e3d4a937b91123fcb4/sgkit/tests/test_pca.py#L232 -- this effectively validates `v` but not `u`).   I was not ever able to make a validation work on random data though -- there had to be some correlation structure and the number of components estimated low in order to reach some reasonable floating point error threshold.

> I have just tried to commit a first fix to see where it can be improved before I do any other adjustments. Is this the way to go or am I missing some vital information?

Do you want to get on a video call at some point?  I would be happy to walk through the contributing process if you haven't already figured it out.  

> I will need some help for the SVD as the GESVD/GESDD might be more useful than the tsqr if the compressed matrix fits into memory. The question is, how to decide whether it is or not?

I believe the safest way to do that is to check whether or not the array has only one chunk.  The `dask.linalg.svd` has similar logic that defaults to using `numpy.linalg.svd` if there is only one chunk (i.e. the array fits entirely in memory).

**Comment by RogerMoens** [comment]
Hey @eric-czech, for testing suggestion see: https://github.com/dask/dask/pull/6799#issuecomment-724169462

I am planning to present some v0's on Wednesday for the points that are still open (see my post above).

I am also going to review the QR iterator to see whether a similar compute=True option is possible/needed as is for the power iterator (that was in place), I am not sure why that was added (found something on it in this blog post: [https://blog.dask.org/2020/05/13/large-svds](https://blog.dask.org/2020/05/13/large-svds)).

> The obvious test possibility that jumped out to me here is to compare u, s, and v from scipy to svd_compressed. I'm surprised that doesn't already happen in

You can't do that actually, as they will be not the same (see link to the testing suggestion). Not sure whether a comparison with sklearn is handy for the left and right svs setting it to the same random seed. But, having dependency on other modules is a bit lame.

> Do you want to get on a video call at some point? I would be happy to walk through the contributing process if you haven't already figured it out.

Maybe this is a good idea to do after I have the v0's proposed. Somewhere later this week would be possible for me. (I am at CST +7h, so take that into account :sweat_smile:)

> I believe the safest way to do that (if I'm understanding you correctly) is to check whether or not the array has only one chunk. The dask.linalg.svd has similar logic that defaults to using numpy.linalg.svd if there is only one chunk (i.e. the array fits entirely in memory).

I saw that, so it falls back on the dask linalg svd, which is the GESDD implementation (I guess it uses numpy under the hood) the GESVD implementation is only available from scipy. I think that the difference (in performance) for this case is negligible, that is also why numpy only provides the GESDD and GESDD is the default in the scipy package. However, I think that the GESVD is more accurate, so that a use case could be accuracy, but then again you are performing randomized svd so the accuracy to that level will not be the issue you care about. 

Some thoughts: for the more accurate QR iterator (and maybe in the future LU iterator), it is required to calculate a QR decomposition on top of the matrix multiplication of a simple power iterator. That might be time consuming for very large matrices as QR is quite iterative. 

Some questions that I have in mind: how does the tsqr performs on gpu's? Did you guys ever try to run comparisons on out-of-core randomized svd on GPU vs. CPU? MapReduce is generally also a bit slower than dedicated MPI implementations, did you ever compared to those for linear algebra like the svd or tsqr?

Finally, I am working myself on robust factorization methods for large matrices (largest so far was 750GB). For one of those I need to perform around 30 randomized svds during a convex optimization. I use dask at this moment because the optimization that needs to be performed requires 4x750GB (around 3TB) due to auxiliary matrices (and of course because it is easy in use). Even with 1.5TB RAM on single node available with 52 cores, the actual pain at this moment for me has become the reading and writing to disk (it takes somewhere around 12 days at this moment for the whole optimization). Do you think dask would actually be faster if I e.g. deploy it on a cluster of several nodes, even with less available RAM, but multiple disks to spill? I am interested in whether it makes sense to keep dask for these kind of heavy linear algebra cases, or whether it makes sense to swap to some MPI based implementations?

**Comment by eric-czech** [comment]
> The obvious test possibility that jumped out to me here is to compare u, s, and v from scipy to svd_compressed. I'm surprised that doesn't already happen in

>> You can't do that actually, as they will be not the same (see link to the testing suggestion). Not sure whether a comparison with sklearn is handy for the left and right svs setting it to the same random seed. But, having dependency on other modules is a bit lame.

Ah, I thought scipy had a randomized SVD implementation too.  Understood that direct comparisons to deterministic results won't work.  scikit-learn is a dev dependency already though (see [envorionment-3.8.yaml](https://github.com/dask/dask/blob/master/continuous_integration/environment-3.8.yaml), e.g.) and it would be present in the build, so I still think a comparison to that implementation is possible and much easier to debug than any test based on matrix reconstruction.

> Maybe this is a good idea to do after I have the v0's proposed

Ok let me know if at any point that would be easier!  I'm in EST but I'm awake early.

> Some thoughts: for the more accurate QR iterator (and maybe in the future LU iterator), it is required to calculate a QR decomposition on top of the matrix multiplication of a simple power iterator. That might be time consuming for very large matrices as QR is quite iterative.

Are you talking about the difference between algorithms 4.4 and 4.3 in the paper?  I am certainly curious how much of a problem the round off error associated with 4.3 really is 😬 , and I have to imagine doing a QR decomp in each iteration would slow things down a lot.  

Along those lines, do you know how to tell when the singular value spectra of a matrix would be amenable to using no power iteration at all?  I'm curious if that's ever practical.  Put differently, how do you decide how many power iterations to run?

> Did you guys ever try to run comparisons on out-of-core randomized svd on GPU vs. CPU? MapReduce is generally also a bit slower than dedicated MPI implementations, did you ever compared to those for linear algebra like the svd or tsqr?

No but that's at the core of what we're trying to figure out right now with cloud-native deployments too.  @mrocklin has been helping us with efforts like https://blog.dask.org/2020/05/13/large-svds, though we're going cloud-native either way and haven't put any thought into MPI clusters.

> Even with 1.5TB RAM on single node available with 52 cores, the actual pain at this moment for me has become the reading and writing to disk (it takes somewhere around 12 days at this moment for the whole optimization). Do you think dask would actually be faster if I e.g. deploy it on a cluster of several nodes, even with less available RAM, but multiple disks to spill?

Great question and I'm very curious to hear the answer.  Perhaps @mrocklin would have some thoughts?

**Comment by RogerMoens** [comment]
Adding to that, I couldn't find anything on writing and reading to and from multiple disks at once, for spilling purposes, is this an option?

**Comment by mrocklin** [comment]
Today Dask doesn't think about specific storage hardware.  Instead we rely on the OS for this.  Multi-disk IO is certainly important, but it tends to be handled with high bandwidth network file systems, or with raid.  In both cases Dask/Python is presented with a filesystem abstraction, and we just write to that.

This seems like the right place to put this abstraction, rather than in Dask itself, but I'm sure that there are use cases that this does not cover.

**Comment by RogerMoens** [comment]
@eric-czech 

I have finished all updates and tests except for the LU iterator.

> Ok let me know if at any point that would be easier! I'm in EST but I'm awake early.

Friday somewhere in the morning for you, somewhere in the afternoon for me? What about 9AM EST (so 3PM Amsterdam time)?

> Are you talking about the difference between algorithms 4.4 and 4.3 in the paper? I am certainly curious how much of a problem the round off error associated with 4.3 really is 😬 , and I have to imagine doing a QR decomp in each iteration would slow things down a lot.

Yups, the difference for the type of matrices I use is quite large actually (see the first post). But, it all depends of course on your application. For convex optimizations it also influences the optimization itself, so a bit more accuracy is nice. 

> Along those lines, do you know how to tell when the singular value spectra of a matrix would be amenable to using no power iteration at all? I'm curious if that's ever practical. Put differently, how do you decide how many power iterations to run?

Well, actually I have properly added that as a separate case (the 'none' option in #6813). Sometimes it is even better to go on without power iteration, again it depends on your spectrum. A good question, to which I don't know the answer yet. The Halko et al. paper give some handles, but in the end it states that it is a trade-off between accuracy and computability. From how I see it at this moment is that the error is related to the sampling type and the iterator. So if you have some knowledge on your matrix you could choose a special type of sampling to influence the error. Secondly, the iterator is in place. In remark 4.3 of the paper something is stated about the loss of singular values that are smaller than a certain value that you can calculate, maybe that might be of interest for you? It is a certain machine precision to a power times your largest singular value.

**Comment by eric-czech** [comment]
> Friday somewhere in the morning for you, somewhere in the afternoon for me? What about 9AM EST (so 3PM Amsterdam time)?

Sounds good!  I'll send an invite shortly.

**Comment by RogerMoens** [comment]
Just found this paper from Drew Schmidt at ORNL on SVDs (https://arxiv.org/pdf/2009.00761.pdf). It could be interesting, for comparison and to review some of the effects on large scale.  It is focused on MPI implementations, however.
