### ISSUE TITLE
Unable to specify worker resources with .to_parquet

### ISSUE THREAD

**Issue by syagev** [dask/dask#6758]
**What happened**: Distributed scheduler is ignoring required worker resources when `to_parquet` is part of the compute graph.

**What you expected to happen**: Worker resources should be respected, especially when specifying `optimize_graph=False`

**Minimal Complete Verifiable Example**:

```python
# setup a scheduler with 2 or more workers, one of them having resource "GPU=1"

from dask import dataframe as dd
from dask import core
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(50,3), columns=['a', 'b', 'c'])
ddf = dd.from_pandas(df, npartitions=5)

def _op(df: pd.DataFrame):
    import time
    time.sleep(5)
    return df

r1 = ddf.map_partitions(_op, meta=dd.utils.make_meta([
    ('a', 'f'),
    ('b', 'f'),
    ('c', 'f')]))
r2 = r1.to_parquet(r"D:\Temp\dd.parquet", compute=False)

r2.compute(resources={tuple(core.flatten(r1.__dask_keys__())): {'GPU': 1}}, optimize_graph=False)
```

**Anything else we need to know?**: This doesn't work no matter what `optimize_graph` in `compute` and `write_index` in `to_parquet` are set to. I'm pretty sure this is because `to_parquet` introduces additional steps (`reset_index`, `rename`, etc.).

I'm not sure if this is desired behavior. What is the correct way to specify resource requirements in this setting?

**Environment**:

- Dask version: 2.21.0
- Python version: 3.8.4
- Operating System: Win10
- Install method (conda, pip, source): pip

**Comment by syagev** [comment]
This seems to be a (nasty) workaround that works (at least for my use cases):

```python
def resources_dict_for_collection(graph, ddf: dd.DataFrame, resources: Dict[str, int]) -> Dict:
    """ Returns a resources dict for a collection in a dask graph

    This is better than e.g. {tuple(core.flatten(y.__dask_keys__())): {'GPU': 1}} since it works even if the
    graph was mutated by e.g. to_parquet (see https://github.com/dask/dask/issues/6758)

    Args:
        graph: the results of some dask .compute() call, e.g. to_parquet(..., compute=False)
        ddf: the collection that needs the specified resources
        resources: the resources (e.g. {'GPU': 1})
    Returns:
        dict that can be passed as the `resources` arg to `compute()`
    """
    reverse_q = [graph.dask.dicts]
    ddf_keys = set(key_name for key_name, _ in core.flatten(ddf.__dask_keys__()))
    graph_keys = []

    while reverse_q:
        nodes = reverse_q.pop()
        for key, node in nodes.items():
            if ddf_keys & set(filter(lambda sub_node: isinstance(sub_node, str), node)):
                graph_keys.append(key)
            elif isinstance(node, dict):
                reverse_q.append(node)
            elif hasattr(node, '_dict'):
                reverse_q.append(node._dict)    # pylint: disable=protected-access

    if not graph_keys:
        raise KeyError("Could not find the collection's keys in the graph")
    return {tuple(graph_keys): resources}

# and then from the OP example:
r2.compute(resources=resources_dict_for_collection(r2, r1, {'GPU': 1}), optimize_graph=False)
```

**Comment by jsignell** [comment]
It seems to me that if you want to make sure that all parts of the to_parquet graph run on the worker with the special resources, then you need to do something like: 

```python
r2.compute(resources={tuple(core.flatten(r2.dask.keys())): {'GPUl': 1}}, optimize_graph=False)
```

That works for me locally on latest master.

**Comment by syagev** [comment]
Thanks @jsignell , that indeed works for the original example. But it misses the point in that the above method doesn't allow setting the resources for **intermediate** operations. I guess this is because in your workaround you're setting the keys on the final step (`r2` and not `r1`)?

So, if we add the following code:
```python
def _op2(df: pd.DataFrame):
    import time
    time.sleep(5)
    return df

r2 = r1.map_partitions(_op2, meta=dd.utils.make_meta([
    ('a', 'f'),
    ('b', 'f'),
    ('c', 'f')]))
r3 = r2.to_parquet(r"D:\Temp\dd.parquet", compute=False, write_index=False)
```
And we want `_op1` to run on the GPU, but `_op2` can run anywhere then what should we run according to your suggestion?

See the following results:
```
%%time
r3.compute(resources={tuple(core.flatten(r2.dask.keys())): {'GPU': 1}}, optimize_graph=False)
>>> Wall time: 20.1 s

%%time
r3.compute(resources={tuple(core.flatten(r1.dask.keys())): {'GPU': 1}}, optimize_graph=False)
>>> Wall time: 20.1 s

%%time
r3.compute(resources=resources_dict_for_collection(r3, r1, {'GPU': 1}), optimize_graph=False)
>>> Wall time: 50.2 s
```
So, IMO it's defenite the suggested solution does not constrain any of the relevant tasks to the GPU. In my workaround, I actually expected a wall time of ~30s, since `op2` can run in parallel. A closer examination of the dashboard during execution shows that indeed `op2` tasks do not have the GPU constraint, but the scheduler executes them in serial on the GPU worker, probably because it's optimizing data locality

**Comment by jsignell** [comment]
Ok so it seems like there is some Subgraph doctoring that happens in a place that seems unavoidable: 

https://github.com/dask/dask/blob/9d19952c71daeb96ec6ecef884559827f04183e8/dask/blockwise.py#L213

Digging around you can see that that Subgraph ends up containing your op1 tasks. So this is kind of painful to deal with at the moment. However there is a lot of work going on right now with HighLevelGraphs so I think this behavior is likely to change (and hopefully get better) in the future.

**Comment by rjzamora** [comment]
@jsignell - You are right that `map_partitions` constructs a `Blockwise` layer in the high-level graph, which will transform everything into a `SubgraphCallable`.  However, I think the real problem here is that `to_parquet` [is calling to_delayed](https://github.com/dask/dask/blob/48a4d4a5c5769f6b78881adeb1b3973a950e5f43/dask/dataframe/io/parquet/core.py#L519) without passing in an `optimize_graph`.

Overall, I am not really sure if it is necessary to use Delayed objects at all in `to_parquet` - So, the best solution here may be to revisit/simplify that function.

**Comment by jsignell** [comment]
Ah! Thanks for pointing that out. It seems like we'll be able to use a map_partitions call but maybe it's strange to write files as a side effect of mapping... In the meantime, it is probably worth adding in the `optimize_graph=False` kwarg.

**Comment by mrocklin** [comment]
I think that this will be easier to solve after we handle layer annotations.  It will probably look like this:

```python
with dask.annotate(resources={"GPU": 1}):
    d1 = ...

d2 = d1.to_parquet(...)
```

I recommend waiting for the next major release.
