### ISSUE TITLE
Concatenate partitions based on arbitrary large `chunksize` passed to `dd.read_parquet`

### ISSUE THREAD

**Issue by lr4d** [dask/dask#6765]
When calling `dask.DataFrame.repartition` and providing `partition_size`, this will trigger dask to load the actual data to determine the memory size of each partition, which is an expensive operation. This is needed to figure out the appropriate way of partitioning the dataframe.

However, for data that resides in Parquet, one does not need to read the actual file contents themselves. One could read the Parquet metadata (and use predicate pushdown) to determine the approximate size of partitions. This is something that we have recently implemented in [kartothek](https://github.com/JDASoftwareGroup/kartothek/blob/master/kartothek/io/dask/dataframe.py#L609) (still in a somewhat experimental state). Such a computation is much cheaper than having to load the actual data because we only need to read the metadata of our partitions.

Instead of supporting this directly in `dask.DataFrame.repartition` it probably makes more sense to have this in `dd.read_parquet` (and the appropriate dask.bag method ?). We can already pass a target `chunksize` to `dd.read_parquet` but currently it will only concatenate row groups, so the resulting chunk size may be much smaller than the value that we have passed.

**Comment by quasiben** [comment]
cc @rjzamora and @jorisvandenbossche who have been more involved with parquet refactoring

**Comment by rjzamora** [comment]
Thanks for opening this - I/we have certainly planned to improve the `chunksize` code path and include a better solution for aggregating both row-groups and/or files.  Since CuDF is capable of reading in list of small files efficiently, we are particularly interested in multi-file partitions in Dask-CuDF.

I'd like to focus on it after #6534 gets in.

**Comment by rjzamora** [comment]
Closing this since the requested feature was implemented in read_parquet. (**Note**: There are currently [plans to deprecate this feature](https://github.com/dask/dask/issues/9051), but that *shouldn't* happen until similar functionality is captured in a new way).
