### ISSUE TITLE
Could not serialize object of type tuple error using tldextract library

### ISSUE THREAD

**Issue by kevchn** [dask/dask#6766]
```
import dask.bag as db
from tldextract import extract

def main():
    db.read_text(INPUT_PATH).map(json.loads).map(lambda x: extract(x['uri']).domain)).compute()

if __name__ == '__main__':
    main()
```

Using the extract method from tldextract inside of a Dask processing pipeline yields an error.

`TypeError: ('Could not serialize object of type tuple.', "(<function reify at 0x109b0c430>,`

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: macOS
- Install method (conda, pip, source): Source

**Comment by TomAugspurger** [comment]
Does that tuple contain non-serializable elements? You can try calling `cloudpickle.dumps` on the result locally.

**Comment by kevchn** [comment]
Thanks
