### ISSUE TITLE
Doc suggestion for custom Aggregation to add a new example

### ISSUE THREAD

**Issue by ianozsvald** [dask/dask#6768]
Hi all, I've got a doc suggestion for https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate

The documentation makes it look easy to write a custom Aggregation function but it doesn't note the steps need to access the numbers behind an existing `SeriesGroupBy` object - this cost me a couple of hours of trial and error. 

My suggestion would be to add something like the following to this documentation section, maybe near the end by the "nunique" example:

"To access NumPy functions use an `apply` with a `lambda` function such as `.apply(lambda r: np.sum(r))`. An example sum of squares aggregation would look like `dd.Aggregation(name="sum_of_squares", chunk=lambda s: s.apply(lambda r: np.sum(np.power(r, 2))), agg=lambda s: s.sum())`."

_If the above is overly complex I'd happily be educated about writing a simpler version of the code!_

**Background:**

Given the example in the docs `custom_sum = dd.Aggregation('custom_sum', lambda s: s.sum(), lambda s0: s0.sum())` I'd figured I could call `.power(2)` and other NumPy functions but this doesn't work. Trying e.g. `dd.Aggregation(name="sum_of_squares", chunk=lambda s: np.sum(np.power(s, 2)), agg=lambda s: s.sum())` results in a `pandas/core/base.py` error of `IndexError('Columns(s) cash_min already selected')` which is rather impenetrable!

The errors I encountered were typically in `dask/dataframe` but once I'd realised that under the hood the operation was in part delegated to a Pandas `SeriesGroupBy`, I read the source, tried `chunk=lambda s: s.aggregate(func=lambda x: np.sum(x))` and iterated back out, by trial and error, to using `s.apply(lambda...`. All in this took a couple of hours and a lot of head-scratching.

**Related question - how to debug such issues efficiently?**

From a productivity perspective - how would a core developer have debugged this as a consumer of Dask, without resorting to trial and error and trying to glean insight from a stack trace? 

Trying `chunk=lambda s: print(type(s)), agg=...` now does print `<class pandas.core.gropuby.generice.SeriesGroupBy>` to the screen, I'm sure I tried this yesterday and it would fail (but I was probably knee-deep in a pile of confusion at this point).

Using `chunk=lambda s: breakpoint()` also gets you to a command prompt. I didn't try this yesterday, I'd figured with multiprocessing this wouldn't work and knowing that this gets me into the point of my failures would have made debugging much easier. I'm surprised that with multiprocessing (I'm using Processes not Threads) that this works but I figure it is useful to know. Might adding tips like these somewhere else in the docs (e.g. to the Best Practices page?) be a useful idea?

**Comment by jsignell** [comment]
Thanks for taking the time to write this up! If you know where you'd like to add these to the docs, I encourage you to open a pull request. 

I agree that it can be tricky to reason about what the input is to the `agg` method. Using the debugger and printing the input are both good tips in general when debugging these functions. It seems reasonable to add more information about how to debug and to explicitly say that the input to the chunk function is going to be a SeriesGroupby object.

In terms of how to make things simpler, if your groups are small enough to fit a group in worker memory, it is often easier to use `apply` on the groupby object rather than writing a custom aggregation. For instance, this works as expected:

```python
ddf.groupby("name").apply(lambda s: np.sum(np.power(s, 2))).compute()
```
Note that a custom aggregation class will be faster because it allows the user to perform the aggregation on the grouped data in each partition before combining it.

**Comment by ianozsvald** [comment]
In my case I have a multi-column `groupby` at play with a bunch of steps including an `agg` so keeping the custom `Aggregation` makes sense, thanks for sense-checking my notes. 
Regarding a doc update - maybe I can do that (my volunteer time is mostly focused towards PyDataGlobal's upcoming conference and in part creating my next public talk drove a part of this issue). Feel free to close this if closing is easiest, I may get around to opening a PR in the coming weeks. I don't know the Dask policy on closing off tasks that are unfinished but may be actioned?

**Comment by jsignell** [comment]
I'll leave it open and label it. If there's been no action in a while we'll probably close it.

**Comment by dustinwerran2** [comment]
I'm going to pick this up! Please don't close for now.
