### ISSUE TITLE
Apply a method on the non-null elements

### ISSUE THREAD

**Issue by jonilaserson** [dask/dask#6769]
I have a series where most of the elements are null, and I want to use dask to apply a method only to the non-null values.
In normal pandas, I would write it like this:

```
ix = df[col].notnull()
df.loc[ix, col] = df.loc[ix, col].apply(func)
```
How can I write the equivalent code in dask without applying `func` on the entire series?

**Comment by TomAugspurger** [comment]
I don't think that dask dataframe supports setitem like this.

I'd recommend wrapping your `func` to just return the value when it is null.

**Comment by martindurant** [comment]
Please read up on `map` and `map_partitions`.
e.g., if you want to not change your code at all
```
def myfunc(df):
    ix = df[col].notnull()
    df.loc[ix, col] = df.loc[ix, col].apply(func)
    return df

df2 = df.map_partitions(df)
```


Dask dataframes are not meant to be mutable, except for column assignment.

I am closing this as resolved.
