### ISSUE TITLE
Installation of the package dataframe / delayed manually

### ISSUE THREAD

**Issue by SHLee5864** [dask/dask#6770]
Hello,

I want to use the package "Dask", but there is one problem.
"Dask dataframe requirements are not installed."
Obviously, we can use pip install "dask[dataframe]" or pip install "dask[complete]".
However, in the secured server where I work, there is no internet connection.
So, I transfer the file of package and install manually.
But, I cannot find the package dask[dataframe] for downloading.
How can I install the rest of packages manually without internet connection?

Thank you

**Comment by TomAugspurger** [comment]
You could perhaps use `pip download dask[dataframe]` and copy all the packages over, but this is likely more of a packaging question than a dask question. I'd recommend asking on StackOverflow with the pip tag if that doesn't work.

**Comment by mrocklin** [comment]
You can also see all of the required packages here:
https://github.com/dask/dask/blob/master/setup.py#L10

You can download and install those manually.
