### ISSUE TITLE
DataFrame.join doesn't accept Series as other

### ISSUE THREAD

**Issue by okapies** [dask/dask#6775]
**What happened**:
`dataframe.join(series)` throws `ValueError: other must be DataFrame`.

**What you expected to happen**:
The [document](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.join) states `join` accepts `Series` object as `other`. It seems `is_dataframe_like`, which called by `join`, checks if an object has `merge` attribute, but it doesn't work for `Series`.

https://github.com/dask/dask/blob/45fd9092049a61c1d43067a0132574b3fe715153/dask/utils.py#L1116-L1123

**Minimal Complete Verifiable Example**:
```python
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> df = dd.from_pandas(pd.DataFrame(range(10), columns=['a']), npartitions=1)
>>> df
Dask DataFrame Structure:
                   a
npartitions=1       
0              int64
9                ...
Dask Name: from_pandas, 1 tasks
>>> df['a']
Dask Series Structure:
npartitions=1
0    int64
9      ...
Name: a, dtype: int64
Dask Name: getitem, 2 tasks
>>> df.join(df['a'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/dask/dataframe/core.py", line 4134, in join
    raise ValueError("other must be DataFrame")
ValueError: other must be DataFrame
```

**Anything else we need to know?**:
n/a

**Environment**:
- Dask version: 2.30.0
- Python version: 3.8.1
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for the report! As a workaround, you can use a dataframe rather than a series. 

```python
df.join(df[['a']], lsuffix="_left")
```

That said, it should be relatively straightforward to do that casting from series to dataframe. Something like this:

```python
        if is_series_like(other) and hasattr(other, "name"):
            other = other.to_frame()
```

right before the is_dataframe_like check:

```python

        if not is_dataframe_like(other):
            raise ValueError("other must be DataFrame")
```
https://github.com/dask/dask/blob/9d19952c71daeb96ec6ecef884559827f04183e8/dask/dataframe/core.py#L4144:L4146

**Comment by jsignell** [comment]
Probably best to do index as well.
