### ISSUE TITLE
shutil.move 

### ISSUE THREAD

**Issue by radsou** [dask/dask#6777]
hello guys i have this problem i can't find any solution
the pictures won't move to the folder who already i created

[desk_source.txt](https://github.com/dask/dask/files/5457377/desk_source.txt)
[Direction_files.txt](https://github.com/dask/dask/files/5457379/Direction_files.txt)

        desk_source = open("desk_source.txt", "r")
        direct_files = open("Direction_files.txt", "r")
        link = direct_files.readlines()
        desktop = os.listdir(desk_source.readline())
        pictures_folder = link[0]
        for files in desktop:
            if files.endswith(".jpg"):
                print(files)
                shutil.move(files, pictures_folder)

        desk_source.close()
        direct_files.close()
![error](https://user-images.githubusercontent.com/73634257/97552119-22a60980-19d4-11eb-8968-5cf0065efaf7.png)

**Comment by quasiben** [comment]
HI @radsou, sorry you're having trouble. This is the issue tracker for [Dask](http://dask.org/).  It's not used for general Python troubleshooting.  I'd recommend asking your question on [stackoverflow.com](https://stackoverflow.com/)

**Comment by radsou** [comment]
Well thank you @quasiben , I put my question there
