### ISSUE TITLE
dd.to_parquet with schema='infer' runs my code 4x

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#6784]
**What happened**:

When creating multiple dataframes from a delayed call and writing via parquet with schema inference, my underlying code seems to be called 4 times more than expected. 

This may be two things:
- the to_parquet call seems to make it hard for dask.compute to re-use the common upstream tasks of the dataframes
- the schema=infer seems to cause another level of duplication 

**What you expected to happen**:

My code should be executed once per delayed object.

**Minimal Complete Verifiable Example**:

```python
import logging
import dask
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame(columns=['col'])

def create_2_dataframes():
    logging.warning('run')
    return df, df

df00, df10 = dask.delayed(create_2_dataframes, nout=2)()
df01, df11 = dask.delayed(create_2_dataframes, nout=2)()

#  Use meta avoids additional calls to ascertain dataframe schema.
df0 = dd.from_delayed([df00, df01], meta=df)
df1 = dd.from_delayed([df10, df11], meta=df)

logging.warning('Compute raw dataframes -- executed once per delayed call, as expected')
_ = dask.compute([df0, df1])

logging.warning('Compute to_parquet on each dataframe leads to twice the number of calls')
_ = dask.compute([df0.to_parquet('/tmp/test', compute=False), 
                  df1.to_parquet('/tmp/test', compute=False)])

logging.warning('Inferring schema leads to 4x the number of calls')
_ = dask.compute([df0.to_parquet('/tmp/test', compute=False, schema='infer'), 
                  df1.to_parquet('/tmp/test', compute=False, schema='infer')])
```

Output:
```
WARNING:root:Compute raw dataframes -- executed once per delayed call, as expected
WARNING:root:run
WARNING:root:run
WARNING:root:Compute to_parquet on each dataframe leads to twice the number of calls
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:Inferring schema leads to 4x the number of calls
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
WARNING:root:run
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for writing this up. On dask master I only see the doubling of the number of calls not the 4x with `schema=infer`. I get the doubling with both fastparquet and pyarrow for the record. 

I think the to_parquet issue has the same origin as #6758 which is to say that there is some graph alteration that happens when you call `to_parquet` even if you don't call compute right away. It'd be good to find a way to let the user opt out of that. Ping @martindurant and @rjzamora for visibility.

**Comment by chrisroat** [comment]
With pyarrow (1.0.1 and 2.0.0), I get the 8 calls with `schema=infer`.

The the suggested fix to use optimize_graph=False in https://github.com/dask/dask/issues/6758#issuecomment-720719213 seems to fix the problem for fastparquet.  With pyarrow, it fixes the problem without `schema=infer`, but only partially fixes the problem with `schema=infer`: I see 6 calls!

**Comment by jsignell** [comment]
Yeah it looks like those 4 extra calls represent this section running once per partition per dataframe. 

https://github.com/dask/dask/blob/f937c06a2ee1b92515714365ea945ca7b4d0e945/dask/dataframe/io/parquet/arrow.py#L859-L862

That runs before compute is even called. Fortunately,  that only runs until some non-null value is discovered in the column. So If you change your example to be like:

```python
df = pd.DataFrame(data=np.ones(10), columns=['col'])
```

You'll see your expected result.

**Comment by rjzamora** [comment]
@jsignell is exactly right - We are sampling partitions until we find a non-null schema for every column.  Since your example is using empty DataFrames, we will sample everything without finding what we need.  Therefore, we need to run the df-creation code 4 times durring schema inference (once for each partition being written), and then once for each partitition when the data is actually written by the worker.

**Comment by chrisroat** [comment]
That makes sense.  The danger is that even a computation that results in a null dataframe could be expensive, so the sampling could randomly trigger long calculations.

**Comment by martindurant** [comment]
I thin the expectation is, that you shouldn't use "infer" in such cases. There could be more doc words around this.

**Comment by rjzamora** [comment]
> I thin the expectation is, that you shouldn't use "infer" in such cases. There could be more doc words around this.

Right - This is the reason `schema="infer"` is not the default.  If the user already knows the schema they want, they can pass it directly with this argument.  You can also pass the type for a subset of columns if you pass a `dict`.
