### ISSUE TITLE
dask distributed throws no moduled named xxx error

### ISSUE THREAD

**Issue by df19900725** [dask/dask#6785]
**What happened**:
I am using dask cluster to run programs. My project structure is as follows:

```
project_name/
  folder_a
    a.py
  folder_b
    b.py
```

I import function function_a() within a.py in b.py

**What you expected to happen**:

It should work properly. However, it throws error in worker node like following:

`ModuleNotFoundError: No module named 'folder_a'`

**Minimal Complete Verifiable Example**:

I import function like follows:
```python
from folder_a.a import function_a

@delayed
def test(input_str):
  return function_a(input_str)

client = ...

d_task = [test(str)]
dask.compute(d_task)
```

**Anything else we need to know?**:

The tutorial says that I can use `client.upload_file()`. However, my imported file was in folder_a. It seems that I cannot upload folder using this code.

**Environment**:

- Dask version: 2.11
- Python version: 3.8.3
- Operating System: SuSE SP2
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Yes, your dask worker needs to have access to all the files that you expect to import from. You can probably use a preload script to add folder_a before you start the worker. See https://docs.dask.org/en/latest/setup/custom-startup.html for more information.

**Comment by mrocklin** [comment]
Thank you for raising this issue @df19900725 

> However, my imported file was in folder_a. It seems that I cannot upload folder using this code.

I think that supporting a folder would be a good idea.  If anyone wants to do this, I recommend something like the following:

```python
if os.path.isdir(path):
    import zipfile
    # zip up directory and send those bytes
```

This will also require us to become smarter on the other side when we unpack these bytes.

I think that this is in-scope and would be a useful contribution

**Comment by jsignell** [comment]
I agree! I'll go ahead and close this since there is an open issue in distributed: https://github.com/dask/distributed/issues/925
