### ISSUE TITLE
Some methods of the DataFrame API Documentation are not in the summary table

### ISSUE THREAD

**Issue by steff456** [dask/dask#6788]
**What happened**: In the summary table of the Dataframe API, https://docs.dask.org/en/latest/dataframe-api.html some methods are not present. 

**What you expected to happen**: I will expect to have the following methods in the summary table,
- [ ] DataFrame.abs
- [ ] DataFrame.align
- [ ] DataFrame.all
- [ ] DataFrame.any
- [ ] DataFrame.applymap
- [ ] DataFrame.bfill
- [ ] DataFrame.copy
- [ ] DataFrame.diff
- [ ] DataFrame.divide
- [ ] DataFrame.eq
- [ ] DataFrame.eval
- [ ] DataFrame.ffill
- [ ] DataFrame.first
- [ ] DataFrame.ge
- [ ] DataFrame.gt
- [ ] DataFrame.idxmax
- [ ] DataFrame.idxmin
- [ ] DataFrame.info
- [ ] DataFrame.isin
- [ ] DataFrame.items
- [ ] DataFrame.iteritems
- [ ] DataFrame.last
- [ ] DataFrame.le
- [ ] DataFrame.lt
- [ ] DataFrame.melt
- [ ] DataFrame.mode
- [ ] DataFrame.ne
- [ ] DataFrame.nsmallest
- [ ] DataFrame.pivot_table
- [ ] DataFrame.resample
- [ ] DataFrame.round
- [ ] DataFrame.select_dtypes
- [ ] DataFrame.sem
- [ ] DataFrame.size
- [ ] DataFrame.squeeze
- [ ] DataFrame.to_html
- [ ] DataFrame.to_string
- [ ] DataFrame.to_timestamp

**Minimal Complete Verifiable Example**: For example, `DataFrame.abs` is not present in the summary table,

![image](https://user-images.githubusercontent.com/20992645/97911458-455c5900-1d19-11eb-9de3-a693a69d9281.png)

**Anything else we need to know?**: If I receive instructions of how can I help and add this methods in the documentation I will like to open the PR :)

**Comment by quasiben** [comment]
Thank you @steff456 for the report!  I think you can find those name can be added to the RST file here:
https://github.com/dask/dask/blob/master/docs/source/dataframe-api.rst

A PR would be most welcome!

**Comment by steff456** [comment]
Thanks for the quick response! I'll create the PR shortly 👍
