### ISSUE TITLE
Doc updates

### ISSUE THREAD

**Issue by martindurant** [dask/dask#6795]
Quick scanning, the following should be corrected:

- "Does Dask have a SQL interface": yes it now does (if perhaps not fully featured)
- paid support: add Coiled? others (saturn)?
- main page Supported By: there was discussion on how to add logos here, but I would say Coiled, Saturn, CapitalOne, Prefect should be here. Also, an older page Funding should be the same with more details, or just removed.

**Comment by martindurant** [comment]
#6823

**Comment by mrocklin** [comment]
(Disclaimer, I have a financial bias here)

> paid support: add Coiled? others (saturn)?

My sense is that Quansight is still happy to provide Dask support.

Coiled certainly does this (we have active Dask support contracts today)

I don't think that Saturn currently offers this except for people who work on Saturn Coud (but I could be wrong)

>  main page Supported By

Agreed on Coiled, Saturn, Capital One, Prefect.  Maybe we want to drop HHMI.  I would suggest that we keep Quansight for a year, under the assumption that they may hire someone else to do this in that time.

**Comment by martindurant** [comment]
https://www.quansight.com/dask 
"For more help with Dask for your business, connect with us and we can give you a full systems evaluation to find out if you are getting the most out of your data science software."

cc @jsignell for the saturn view on paid dask support

Discussion on "supported by": https://github.com/dask/community/issues/44 and https://github.com/dask/community/issues/51 (but no action taken) for reference. But I will go ahead and change the list of logos, unless someone disagrees.

**Comment by jsignell** [comment]
Yep I agree that Saturn belongs in "supported by" and not in "paid support". I'll also suggest listing the companies alphabetically.

**Comment by raybellwaves** [comment]
slight follow on here 

https://docs.dask.org/en/latest/support.html#paid-support

What that suppose to be updated?

Correct me if i'm wrong was it decided not to list the companies in the dask docs https://docs.dask.org/en/latest/ i.e. only https://dask.org/

**Comment by martindurant** [comment]
> What that suppose to be updated?

Not according to the discussion - there are several companies that provide services around Dask, but not of the kind of feature-for-cash contracts that Anaconda and Quansight have been involved in in the past.  

> was it decided not to list the companies in the dask docs

There was no concrete decision on this. The main page shows a different list of associated companies/institutes involved with dask development and maintenance, mainly by paying (some of) the salary of one of the team.

**Comment by raybellwaves** [comment]
Thanks. I was after a link for the companies. Opened an issue here: https://github.com/dask/dask.github.io/issues/40
