### ISSUE TITLE
Cannot Write Dask Dataframe to CSV

### ISSUE THREAD

**Issue by rileyhun** [dask/dask#6798]
**What happened**:

I am following a workflow from an example notebook (i.e. https://github.com/dask/dask-examples/blob/master/dataframes/01-data-access.ipynb).

I'm unable to create the artificial dataset.

I get the following error: 

`AttributeError: Can't get attribute 'Day' on <module 'pandas._libs.tslibs.offsets' from '/opt/conda/lib/python3.7/site-packages/pandas/_libs/tslibs/offsets.cpython-37m-x86_64-linux-gnu.so'>`

**What you expected to happen**:

I expected to be able to write the dask dataframe to partitioned csv files. 

**Minimal Complete Verifiable Example**:

```python
import dask
df = dask.datasets.timeseries()

import os
import datetime

if not os.path.exists('data'):
    os.mkdir('data')

def name(i):
    return str(datetime.date(2000, 1, 1) + i * datetime.timedelta(days=1))
    
df.to_csv('data/*.csv', name_function=name)
```

**Environment**:

- Dask version: 2.21.0
- Python version: 3.7.7
- Dask Gateway: 0.7.1
- Using AI Platform Jupyter Notebook as client

**Comment by mrocklin** [comment]
Hrm, this works for me

```python
In [1]: import dask
   ...: df = dask.datasets.timeseries()
   ...: 
   ...: import os
   ...: import datetime
   ...: 
   ...: if not os.path.exists('data'):
   ...:     os.mkdir('data')
   ...: 
   ...: def name(i):
   ...:     return str(datetime.date(2000, 1, 1) + i * datetime.timedelta(days=1))
   ...: 
   ...: df.to_csv('data/*.csv', name_function=name)
   ...: 
Out[1]: 
['/home/mrocklin/data/2000-01-01.csv',
 '/home/mrocklin/data/2000-01-02.csv',
 '/home/mrocklin/data/2000-01-03.csv',
 '/home/mrocklin/data/2000-01-04.csv',
 '/home/mrocklin/data/2000-01-05.csv',
 '/home/mrocklin/data/2000-01-06.csv',
 '/home/mrocklin/data/2000-01-07.csv',
 '/home/mrocklin/data/2000-01-08.csv',
 '/home/mrocklin/data/2000-01-09.csv',
 '/home/mrocklin/data/2000-01-10.csv',
 '/home/mrocklin/data/2000-01-11.csv',
 '/home/mrocklin/data/2000-01-12.csv',
 '/home/mrocklin/data/2000-01-13.csv',
 '/home/mrocklin/data/2000-01-14.csv',
 '/home/mrocklin/data/2000-01-15.csv',
 '/home/mrocklin/data/2000-01-16.csv',
 '/home/mrocklin/data/2000-01-17.csv',
 '/home/mrocklin/data/2000-01-18.csv',
 '/home/mrocklin/data/2000-01-19.csv',
 '/home/mrocklin/data/2000-01-20.csv',
 '/home/mrocklin/data/2000-01-21.csv',
 '/home/mrocklin/data/2000-01-22.csv',
 '/home/mrocklin/data/2000-01-23.csv',
 '/home/mrocklin/data/2000-01-24.csv',
 '/home/mrocklin/data/2000-01-25.csv',
 '/home/mrocklin/data/2000-01-26.csv',
 '/home/mrocklin/data/2000-01-27.csv',
 '/home/mrocklin/data/2000-01-28.csv',
 '/home/mrocklin/data/2000-01-29.csv',
 '/home/mrocklin/data/2000-01-30.csv']
```

**Comment by jsignell** [comment]
I did some mild googling of your error and I suspect that this is a pickle problem. Since you mention dask-gateway and your dask version is 2.21.0 I suspect that you have a different version of dask.distributed or Python on your cluster. If you have access to your cluster it'd be helpful to know what's running there. If not, I recommend upgrading your client-side version of dask and distributed to 2.30.0

**Comment by rileyhun** [comment]
> I did some mild googling of your error and I suspect that this is a pickle problem. Since you mention dask-gateway and your dask version is 2.21.0 I suspect that you have a different version of dask.distributed or Python on your cluster. If you have access to your cluster it'd be helpful to know what's running there. If not, I recommend upgrading your client-side version of dask and distributed to 2.30.0

Hi @jsignell - thanks so much for your suggestion. I upgrade dask + distributed to 2.30.0 on both client and server side and that seemed to do the trick! I shall close this case now.

**Comment by jsignell** [comment]
Yay glad it worked!
