### ISSUE TITLE
blocksize and persist has impact on result

### ISSUE THREAD

**Issue by nils-braun** [dask/dask#6814]
**What happened**:
When running `read_csv` in combination with `persist` and `blocksize`, results change on re-evaluation.
I am using a 10 worker dask-cluster with version 2.29.0 (I skip the cluster setup part of the script).

```python
import dask.dataframe as dd
from distributed import wait

kwargs = dict(
    dtype={
        "payment_type": "UInt8",
        "VendorID": "UInt8",
        "passenger_count": "UInt8",
        "RatecodeID": "UInt8",
    },
    storage_options={"anon": True}
)

# First read it with 16 MiB blocksize
df = dd.read_csv(
    "s3://nyc-tlc/trip data/yellow_tripdata_2019-01*.csv",
    blocksize="16 MiB",
    **kwargs
)
df = df.persist()
wait(df)
print(df.shape[0].compute()) # -> gives 7667792

# Then with default blocksize
df = dd.read_csv(
    "s3://nyc-tlc/trip data/yellow_tripdata_2019-01*.csv",
    **kwargs
)
df = df.persist()
wait(df)
print(df.shape[0].compute()) # -> still 7667792

# Then with 16 MiB again
df = dd.read_csv(
    "s3://nyc-tlc/trip data/yellow_tripdata_2019-01*.csv",
    blocksize="16 MiB",
    **kwargs
)
df = df.persist()
wait(df)
print(df.shape[0].compute()) # -> suddenly gives 12204124
```

**What you expected to happen**:

The same result every time :-)

**Environment**:

- Dask version: 2.29.0
- Python version: 3.8.6
- Operating System: coiled cluster
- Install method (conda, pip, source): coiled cluster

**Comment by jsignell** [comment]
Yikes. I can reproduce on dask/distributed master although I get a different final number. I suspect that there might be some issue with tasks having the same name even if the blocksize is different.
