### ISSUE TITLE
When overwriting partitioned parquet files, Dask may leave old partitions present.

### ISSUE THREAD

**Issue by hayesgb** [dask/dask#6824]
**What happened**:
Let's define a pyarrow Dataset as a collection of parquet files.

When overwriting a pyarrow Dataset created by Dask, where the new Dataset has a fewer number of files than the original dataset, only the new number of partitioned files are overwritten, and the old "dangling" files are left in the directory.

**What you expected to happen**:
A pyarrow Dataset, when written to disk, should contain the same number of files as the number of partitions in Dask.  During an overwrite operation, I would expect any old files to be removed during the write operation.  In the example below, I would expect len(files0) == len(files1) to be True.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
from dask.distributed import Client
import numpy as np
import pandas as pd
from fsspec.implementations.local import LocalFileSystem

fs = LocalFileSystem()

# Create a Dask DataFrame if size (10000, 10) with 5 partitions and write to local
ddf = dd.from_pandas(pd.DataFrame(np.random.randint(low=0, high=100, size=(10000, 10)),
                                 columns=["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]),
                     npartitions=5
                    )
ddf = ddf.reset_index(drop=True)
dd.to_parquet(ddf, "data0.parquet", engine="pyarrow")

# Read that DataFrame back and check its partitions
ddf2 = ddf.repartition(npartitions=3)

# Repartition the dataframe and write to a new location, and then overwrite the existing location
dd.to_parquet(ddf2, "data1.parquet", engine="pyarrow")
dd.to_parquet(ddf2, "data0.parquet", engine="pyarrow")
ddf3 = dd.read_parquet("data1.parquet", engine="pyarrow")

# Assert the # of files written are identical
files0 = fs.ls("data0.parquet")
files1 = fs.ls("data1.parquet")
assert len(files0) == len(files1)
```

**Anything else we need to know?**:

**Environment**:

- Dask version:  2.30.0
- Python version: 3.6.9
- Operating System: Linux
- Install method (conda, pip, source): pip
- Pyarrow version:

**Comment by rjzamora** [comment]
This is very similar to the problem reported in #5873 - That issue was raised when the partitions were being randomly named, but it is the same idea: Dask will not clear the contents of a directory when a dataset is overwritten.

The general sentiment in that issue was that it may be best to make the user responsible for clearing stale data.  However, I am still unsure about this.

**Comment by hayesgb** [comment]
A very common ML engineering use case is to overwrite files on a scheduled basis. The fact that Dask silently allows the write to occur, leaving the dangling parquet files seems problematic.  I included the proposal to explicitly request an overwrite. 

By analog, Spark has the same overwrite keyword, which can permit a remove and write, or with "dynamic" it will only overwrite changed partitions.
 
It looks like appending is only permitted for newly added partitions (in different directories).  Is this correct?

**Comment by melvinev** [comment]
Very much support @hayesgb proposal here, this is a problem for us.

**Comment by jrbourbeau** [comment]
I believe this was closed by https://github.com/dask/dask/pull/6825, though feel free to re-open if that's not the case

**Comment by mengaldo** [comment]
I strongly support @hayesgb. 
I am trying to use the keyword overwrite=True, but I get this error: 
`File "./main_format_gkx.py", line 111, in <module>
    main()
  File "./main_format_gkx.py", line 70, in main
    preprocess.format_data()
  File "/Users/gian/GIT-GM/options_project/operations/../data_handling/formatting/Preprocessing_GKX.py", line 60, in format_data
    self.add_prefix_to_columns(
  File "/Users/gian/GIT-GM/options_project/operations/../data_handling/formatting/Preprocessing_GKX.py", line 167, in add_prefix_to_columns
    self.save_dataset(
  File "/Users/gian/GIT-GM/options_project/data_handling/formatting/Preprocessing.py", line 63, in save_dataset
    Preprocessing.pandas_to_parquet(df=data, save_to=name)
  File "/Users/gian/GIT-GM/options_project/data_handling/formatting/Preprocessing.py", line 74, in pandas_to_parquet
    dd.to_parquet(
  File "/usr/local/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 443, in to_parquet
    meta, i_offset = engine.initialize_write(
  File "/usr/local/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 413, in initialize_write
    fmd = fastparquet.writer.make_metadata(
TypeError: make_metadata() got an unexpected keyword argument 'overwrite'`

**Comment by jsignell** [comment]
@mengaldo are you saying that this issue is not resolved?

**Comment by mengaldo** [comment]
@jsingell my mistake - it has been resolved
