### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by pseudotensor** [dask/dask#6826]
https://towardsdatascience.com/beyond-pandas-spark-dask-vaex-and-other-big-data-technologies-battling-head-to-head-a453a1f8cc13

Curious if these isssues can or have been addressed.  Thanks.

**Comment by quasiben** [comment]
Yes.  I would recommend reading over: https://github.com/dask/dask/issues/6264 and various linked PRs from that issue

**Comment by pseudotensor** [comment]
Thanks!  I've been more deeply relying upon dask and was hopeful.  Will check out the PR, thanks!
