### ISSUE TITLE
dd.read_parquet filter doc does not match filter logic

### ISSUE THREAD

**Issue by postelrich** [dask/dask#6832]
The doc here for `dd.read_parquet` https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/core.py#L199-L212 does not align with the logic that actually takes place in https://github.com/dask/fastparquet/blob/master/fastparquet/api.py#L803. The docs state, if I'm reading correctly, that you can pass in two types of filters. One is a List[List[tuple]] where the tuples in the inner list are joined together with an AND and the items in the outer list are joined together with an OR. The other is a List[tuple] where the tuples in the list are joined together with an AND condition. Looking at the code for `filter_out_cats` in `fastparquet.api` however seems to expect a List[tuple] where the tuples in the list are joined together with an OR since it returns true on the first matching filter. 

Another small error in the doc is it shows '=' as an op when fastparquet only seems to accept '=='. 

**Environment**:

- Dask version: 2.30.0
- Python version: 3.7.0
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by rjzamora** [comment]
Is this a duplicate of #6816 (where the appropriate solution is likely a revised doc string)?

**Comment by postelrich** [comment]
it is indeed
