### ISSUE TITLE
Follow up after moving to GitHub Actions

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#6842]
In https://github.com/dask/dask/pull/6794 we moved our Travis CI build to GitHub Actions 🎉 There are a couple pieces of follow up work we'll want to keep track of:

- [ ] Add coverage back &mdash; potentially moving to codecov (xref https://github.com/dask/dask/pull/6794#issuecomment-726703648)
- [ ] (Maybe?) Separate our main tests workflow into OS-specific workflow files so we can re-run tests on an individual OS, e.g. Windows, without having to re-run on all platforms (xref https://github.com/dask/community/issues/107#issuecomment-720555156)

**Comment by jsignell** [comment]
I just realized that when we stopped running coverage we also stopped running doctest since those were grouped in the same job. That gives this a greater sense of urgency for me, but maybe the doctest should just be run separately anyways.

**Comment by jrbourbeau** [comment]
Hmm looking at the diff for https://github.com/dask/dask/pull/6794, I don't see where we dropped doctests (though I could just be missing something). Are you sure we were running doctests in the first place? I found this PR https://github.com/dask/dask/pull/4427 where we added the `--doctest-modules` flag, but that was just to our developer docs, not CI

**Comment by jrbourbeau** [comment]
Ah, I found it

https://github.com/dask/dask/blob/f8d5f6070ecd8370b6487a23cdde52228723c7fc/continuous_integration/scripts/run_tests.sh#L12-L14

**Comment by jsignell** [comment]
Yeah. I don't know when that came in.

**Comment by jsignell** [comment]
I wrote a job to run doctests in additional ci. I'll open the PR now.

**Comment by jrbourbeau** [comment]
Sounds good, thanks @jsignell

**Comment by ian-r-rose** [comment]
The migration to GitHub actions is complete
