### ISSUE TITLE
Get config item if variable is None

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask#6860]
Throughout many cluster managers it is common to allow configuration of the cluster via kwargs before falling back to the Dask config system.

This results in code like this:

```python
class MyCluster(Cluster)
    def __init__(self, my_kwarg: str = None):
        self.my_kwarg = my_kwarg if my_kwarg is not None else dask.config.get("mycluster.my-kwarg")
```

For long variable names black will turn this into something more like this:

```python
class MyCluster(Cluster)
    def __init__(self, my_very_log_kwarg: str = None):
        self.my_very_log_kwarg = (
            my_very_log_kwarg
            if my_very_log_kwarg is not None
            else dask.config.get("mycluster.my_very_log_kwarg")
        )
```

With many of these repeated, code starts to become [rather unreadable](https://github.com/dask/dask-cloudprovider/blob/master/dask_cloudprovider/aws/ec2.py#L330-L355).

---

I would like to propose adding a new getter method to `dask.config` which encapsulates this functionality. 

The function would take the kwarg variable and also a config key (and possibly still a default as `.get` currently does). If the variable it is passed is not `None` it would pass it straight back, otherwise it would continue with the `dask.config.get` functionality.

```python
class MyCluster(Cluster)
    def __init__(self, my_kwarg: str = None):
        self.my_kwarg = dask.config.get_if_none(my_kwarg, "mycluster.my-kwarg")
```

**Comment by jsignell** [comment]
I like this idea a lot. Another potential name would be `dask.config.maybe_get`

**Comment by mrocklin** [comment]
This seems sensible to me.  I think that it makes sense to think about the
name here.  I wonder if there are examples in the stdlib. I'm reminded of
the converse operation dict.setdefault

**Comment by jacobtomlinson** [comment]
> I think that it makes sense to think about the name here.

Agreed. I must admit I'm struggling to think of a sensible one.

**Comment by jacobtomlinson** [comment]
> Another potential name would be `dask.config.maybe_get`

😄
