### ISSUE TITLE
Ability to customize filename prefix during partitioned to_parquet

### ISSUE THREAD

**Issue by szelenka** [dask/dask#6867]
I have a distributed pipeline which generates portions of a partitioned parquet file, where they all eventually upload all of the parquet files to s3. We can update the _metadata across all the workers in s3, such that it correctly contains all of the pointers to the various partitioned parquet files in the bucket.

The challenge comes when multiple workers try to partition a parquet file in the same partition. They'll essentially encounter a situation where one or more of the workers will overwrite the parquet "part" file on s3.

It'd be really awesome if the library empowered users to rename the prefix used when generating these partitioned parquet files. As it is today, it is hardcoded to "part.%i.parquet".
https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/core.py#L577

This feature request is to allow a kwarg to change the prefix to a user defined string, or some guid for the prefix like pandas does, to eliminate the possibility of overwriting files on disk. Something like:

"%s.%i.parquet" instead of "part.%i.parquet"

**Comment by rjzamora** [comment]
This sounds reasonable to me :)

**Comment by jsignell** [comment]
If you are interested in implementing this you should feel free to open a pull request. You might want to consider whether you could resolve your issue by adding a layer of nesting. It seems like each worker could just write to a subdir.

**Comment by szelenka** [comment]
For this specific case, the source data is too large to fit on the disk of any worker, so the only way to get it to s3 is in different parts or buy more capacity on the workers. 

I realize it's not a typical use case, but the hard code "part.%i.parquet" is preventing us from using dask to write out the parquet files. 

I'll look into drafting a PR in early December.

**Comment by jorisvandenbossche** [comment]
@szelenka would a keyword where you can specify this "template" string be sufficient? So the current behaviour would translate to something like `filename_template="part.%i.parquet"`, and giving the ability to specify another string that can still include `%i`. 

That way, you could specify a different base name in each worker / to_parquet call?

**Comment by rjzamora** [comment]
@szelenka - Can you clarify why setting `append=True` after the initial write doesn't accomplish your goal here?  Does your workflow require you to write to the same dataset from different clients at the same time?

Note that dask used to use a uuid to name each file, but this was resulting in duplicated data in some production-scale cases where workers were occasionally dying mid-write.  It is easy enough to allow the user to optionally use a uuid if they are comfortable with this risk.  However, if the real goal is to "append" to an existing dataset without overwriting files, I  think we want to make sure that the "append=True" code path can accomplish this (and fix any bugs if cannot).

**Comment by szelenka** [comment]
@jorisvandenbossche `filename_template="part.%i.parquet"` would work!

@rjzamora I was using the `append=True` keyword, but it wasn't behaving as I expected.

We have a 100 GB SQL table which we'd like to convert to parquet format on S3, but the workers are running on k8 where they only have 20 GB of ephemeral storage. We can pull out small batches from and distribute that across a pool of workers. 

The first batch will use `append=False` to initialize the `_metadata` and `_common_metadata` files on local disk, then upload that folder to S3 using the AWS CLI tools. Subsequent workers coordinate when someone can download/update/upload the metadata files back to S3.

Each worker pulls it's batch from SQL, downloads the `_metadata` and `_common_metadata` from S3, then coverts the data to a partitioned parquet file on it's local disk (same folder as the metadata files) using `append=True`, and finally uses the AWS CLI tools upload the folder to the same location in S3. This overwrites the metadata files, and should simply add the new files to the folder.

Depending on how the batch decides to partition the data, I've seen it create a `part.%i.parquet` with the same name as something that already exists on S3 but does not on exist the local disk where it's creating the new files. Should `append=True` be preventing this type of file overwrite by using the information from metadata, even though the files referenced in the metadata aren't on the local disk where the new partition is generating files?

**Comment by rjzamora** [comment]
>Should append=True be preventing this type of file overwrite by using the information from metadata, even though the files referenced in the metadata aren't on the local disk where the new partition is generating files?

Hmm - Interesting use case!  I wouldn't be surprised find bugs with `append=True` on hive-partitioned data.  However, I would expect the file-naming offset to be depend on the information in the `_metadata` file (not the acutal data on disk).  For example, to find the part offset for the write, it seems like the arrow engine [takes the length of the ParquetDataset](https://github.com/dask/dask/blob/de2c7b5bb1cedc04977ddc6f2d562c93c1bc99e6/dask/dataframe/io/parquet/arrow.py#L928) and the fastparquet engine [uses find_max_part](https://github.com/dask/dask/blob/de2c7b5bb1cedc04977ddc6f2d562c93c1bc99e6/dask/dataframe/io/parquet/fastparquet.py#L559) - Which engine are you using?

**Comment by bryanwweber** [comment]
I think this is solved by the `name_function` parameter in [`DataFrame.to_parquet()`](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.to_parquet.html#dask.dataframe.DataFrame.to_parquet). Please feel free to reopen if this is not the case! 😄
