### ISSUE TITLE
ddf.drop method fails if columns is an empty list

### ISSUE THREAD

**Issue by Sylvain-chateau** [dask/dask#6870]
Hello,

I have a comment regarding the drop function at https://github.com/dask/dask/blob/master/dask/dataframe/core.py
```    @derived_from(pd.DataFrame)
    def drop(self, labels=None, axis=0, columns=None, errors="raise"):
        axis = self._validate_axis(axis)
        if (axis == 1) or (columns is not None):
            return self.map_partitions(
                drop_by_shallow_copy, columns or labels, errors=errors
            )
        raise NotImplementedError(
            "Drop currently only works for axis=1 or when columns is not None"
        )
```
In case columns is an empty list, we enter the  map_partitions fun and get the error 'metadata inference failed in `drop_by_shallow_copy`. which is not very explicit.
I don't know if it's the desired behaviour, but in case it's not, then a test on columns and an update of the NotImplementedError error msg could be more explicit

**Comment by rjzamora** [comment]
Thanks @Sylvain-chateau - I agree that a metadata-inference failure is not the desired behavior here.  I would expect dask to provide the same behavior as pandas: return a copy of the same DataFrame.

Did you have any interest in providing a PR to handle the `columns == []` case in the code you quoted above?  If not, I should be able to follow up later today or Monday.
