### ISSUE TITLE
groupby-apply differences between categorical and non-categorical

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#6873]
**What happened**:
A groupby-apply operation on a partitioned dataframe processes (empty) duplicated indices if grouped over a categorical.

**What you expected to happen**:
No duplication, which is the behavior with a non-categorical.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

data_cat = {'name': pd.Categorical(['A', 'B', 'B', 'A'], categories=['A', 'B'])}
meta_cat = dd.utils.make_meta((None, str), index=pd.CategoricalIndex(categories=['A', 'B'], name='name'))

data_str = {'name': ['A', 'B', 'B', 'A']}
meta_str = dd.utils.make_meta((None, str), index=pd.Index([''], name='name'))

def agg(frame):
    return 'bar' if len(frame.index) else 'empty'

def groupby_apply(data, meta):
    df = pd.DataFrame(data)
    ddf = dd.from_pandas(df, npartitions=3)
    result = ddf.groupby('name').apply(agg, meta=meta).compute()
    print(result)

print('string')
groupby_apply(data_str, meta_str)
print('\ncategorical')
groupby_apply(data_cat, meta_cat)
```
Output:
```
string
name
A    bar
B    bar
dtype: object

categorical
name
A      bar
B    empty
A    empty
B      bar
dtype: object
```

**Anything else we need to know?**:

Presumably this happens because each groupby-partition is expanding the full categorical, which could be avoided with the observed keyword.  I see #6854 is making some related changes, though in this case I expected the observed=True is what is desired. @jsignell may have some thoughts, being recently familiar with this section of code.

**Environment**:

- Dask version: 2.30.0+65.g3c64a880
- Python version: 3.8.5
- Operating System: Ubunutu 20.04
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
I just pushed a change to #6854 and now it fixes this issue when you specify `observed=True` do you think that is sufficient to close this issue (once that PR merges)?

**Comment by chrisroat** [comment]
I think it will be surprising to get the duplicate keys in any situation.  I would think the best thing is to have `observed=True` always be true during the underlying apply after a groupby.   Each key would just return the result of apply for its value.  

I may not fully understand all the possible cases, but I don't It doesn't seem useful to return the all the other values and produce the duplicate keys that are nearly all empty valued.

**Comment by jsignell** [comment]
Hmm I think I disagree. The docstring for `apply` specifically mentions this case:

> Dask's groupby-apply will apply ``func`` once to each partition-group pair,
   so when ``func`` is a reduction you'll end up with one row per
   partition-group pair.

Consider this case in pandas:
```python
import pandas as pd

data_cat = {'name': pd.Categorical(['A', 'B', 'B', 'A'], categories=['A', 'B', 'C'])}
df = pd.DataFrame(data_cat)

def agg(frame):
    return 'bar' if len(frame.index) else 'empty'

df.groupby("name").apply(agg)
```
output:
```
name
A      bar
B      bar
C    empty
dtype: object
```

When categories are present in the list of known categories a groupby key, value pair is passed to apply even if the category is not present in the dataset. This is precisely what `observed` is for.

**Comment by chrisroat** [comment]
OK, then I'm over-ruled by the documentation.  :)

However, I think it needs to be hashed out a bit more clearly.  Here are two issues that come to my mind: 

1.  If I do a groupby, is a partition always equal to one key?  What if that subset of data does not fit into memory?

2.  I want to understand the possible outcomes and how they are accessible.  Is this correct?

--

`observed=True` in both `apply` and `groupby`
```
A bar
B bar
```

--

`observed=False` in `apply` and `observed=True` in `groupby`
```
A bar
B empty
C empty
A empty
B bar
C empty
```

--

`observed=False` in `groupby` and `observed=True` in `apply`
```
A bar
B bar
C empty
```

--

`observed=False` in both `apply` and `groupby`
```
A bar
B empty
C empty
A empty
B bar
C empty
A empty
B empty
C empty
```

**Comment by jsignell** [comment]
> 1. If I do a groupby, is a partition always equal to one key? What if that subset of data does not fit into memory?

From what I can tell, one key does not necessarily correspond to one partition. It looks like dask handles this internally to ensure that parition size doesn't blow up. When using aggregations the output is often in one partition, but you can use `split_out` or `split_every` to control that.

> 2. I want to understand the possible outcomes and how they are accessible. Is this correct?

There is no `observed` in `apply` so your cases simplify down to the first and the last.

**Comment by chrisroat** [comment]
Gotcha.  I think having `observed` in `apply` comment was more wishful thinking.  I see the logic/consistency in how things are done, even if it seemed a little surprising to me at first.

Thanks for the fix!
