### ISSUE TITLE
Missing index column in dataframe.to_json output

### ISSUE THREAD

**Issue by kinghuang** [dask/dask#6875]
**What happened**:

I have a Dask dataframe with an index, and I am attempting to use `dataframe.to_json` to output a Dask dataframe to JSON (record per line). The resulting output is always missing the index. There seems to be no way to include the index in the output, short of resetting the index.

**What you expected to happen**:

Calling `dataframe.json` with `lines=True` and `orient="records"` should include the index with the output.

**Minimal Complete Verifiable Example**:

```python
from dask import dataframe as dd
import pandas as pd

pandas_df = pd.DataFrame(data={"text": ["a", "b", "c"], "id": [1, 2, 3]})
dask_df = dd.from_pandas(pandas_df, npartitions=1)
dask_df = dask_df.set_index("id")

dask_df.to_json("index-test", lines=True, orient="records")
```

The resulting file only contains `text` for each JSON object line. The `id` is missing.

```
{"text":"a"}
{"text":"b"}
{"text":"c"}
```

**Anything else we need to know?**:

According to the underlying [pandas.DataFrame.to_json](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html) docs, the `index` parameter defaults to `True`. Explicitly setting `index=True` on the Dask `dataframe.to_json` still leaves out the index.

```python
dask_df.to_json("index-test", lines=True, orient="records", index=True)
```

The result is still missing `id`.

```
{"text":"a"}
{"text":"b"}
{"text":"c"}
```

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.6
- Operating System: Linux 840ab195ef9e 5.4.39-linuxkit (python container on Docker for Mac)
- Install method (conda, pip, source): pip

**Comment by rjzamora** [comment]
Perhaps you need to specify `orient="index"`?

```python
from dask import dataframe as dd
import pandas as pd

pandas_df = pd.DataFrame(data={"text": ["a", "b", "c"], "id": [1, 2, 3]})
dask_df = dd.from_pandas(pandas_df, npartitions=1)
dask_df = dask_df.set_index("id")

dask_df.to_json("index-test", orient="index")
dd.read_json("index-test/*", orient="index").compute()
```
```
  text
1    a
2    b
3    c
```

I noticed that the docstring incorrectly references `dd.to_json` - Perhaps we need to improve access to this docstring and make sure it clarifies the proper way to preserve the index?

**Comment by kinghuang** [comment]
I specifically want JSON lines output, so `orient="records", lines=True` is correct. But, I just tried this in Pandas only, and it's also missing the index. This might not be a Dask problem. I'll file an issue over there.

```python
import pandas as pd

pandas_df = pd.DataFrame(data={"text": ["a", "b", "c"], "id": [1, 2, 3]})
pandas_df = pandas_df.set_index("id")
print(pandas_df.to_json(orient="records", lines=True))
```

```
{"text":"a"}
{"text":"b"}
{"text":"c"}
```

**Comment by kinghuang** [comment]
Ah, according to pandas-dev/pandas#25513, not including the index when `orient="records"` is the expected behaviour.

The Pandas docs are rather confusing in this aspect. I took the default `index=True` and the comment about `index=False` being only possible when the orient is `split` or `table` to mean that it'd be included for `records` output.

Resetting the index (or something similar) is the way to go.
