### ISSUE TITLE
Add to dask graph mid-computation 

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#688]
Sometimes we learn about more tasks to compute *during computation*.  At the moment the dask schedulers don't support this and with good reason.  The state that we initialize at the beginning of computation might be tricky to update.

In practice our current solution to this problem is to have several completely separate calls to `get`.  This is simple and effective but loses some potential parallelism as we wait for stragglers.

However, in some cases this might be more doable.  In particular if the tasks that we want to add to the existing graph don't overlap with existing tasks then merging scheduling states might be straightforward.

A prototype implementation of this might add a function `emit_tasks`

```python
from dask.async import incoming_task_queue

def emit_tasks(dsk, keys):
    incoming_task_queue.put((dsk, keys))
```

The hard part would be creating a function that could robustly merge two `states`.

```python
from toolz import merge
def merge_state(old, new):
    return {'cache': merge(old['cache'], new['cache']),
            'running': old['running']
            'ready': old['ready'] + new['ready']
...
```

To be clear, it's not clear that this is a good idea.  Just something that has come up a couple of times and that we should probably keep in the backs of our minds.

**Comment by catethos** [comment]
Consider the the pipeline consists of a few computations, i.e. `f -> g -> h`, and suppose that `f` is very expensive to calculate, and `g` throws some error, I think it would be a waste to throw away the `states` dictionary and restart the whole pipe again. What if we could return the `states` dictionary, tweak it abit and resume the whole pipeline from where it stops?

**Comment by mrocklin** [comment]
If you supply your own cache you can manage this now if you're using the standard scheduler

```python
In [1]: def inc(x):
    return x + 1
   ...: 

In [2]: def throws(x):
    raise Exception()
   ...: 

In [3]: dsk = {'x': 1, 'y': (inc, 'x'), 'z': (throws, 'y')}

In [4]: cache = {}

In [5]: import dask

In [6]: dask.get(dsk, 'z', cache=cache)
Exception: 

In [7]: cache
Out[7]: {'y': 2}

In [8]: dsk.update(cache)

In [9]: dsk
Out[9]: {'x': 1, 'y': 2, 'z': (<function __main__.throws>, 'y')}
```

**Comment by catethos** [comment]
Thanks for the advice. How about the `get

**Comment by mrocklin** [comment]
All of `dask.get`, `dask.threaded.get` and `dask.multiprocessing.get` are mostly the same.  This should work with all of them.

**Comment by mrocklin** [comment]
This can be done with the distributed scheduler, which also operates well on a single machine.  Closing.
