### ISSUE TITLE
Scipy missing from extras_require in setup.py

### ISSUE THREAD

**Issue by jborchma** [dask/dask#6890]
Working on addressing #6880, I chose to use the `array.stats` implementation of skew for the dataframe functionality. However, though the import tests I realized that scipy (which [is needed](https://github.com/dask/dask/blob/master/dask/array/stats.py#L39) for `array.stats`) is not part of any of the `extras_require` installs, hence any usage of `array.stats` fails unless scipy is independently installed. That dependency is also missing from [the docs](https://docs.dask.org/en/latest/install.html#optional-dependencies). 

I am raising this because in my PR draft #6881 I am trying to leverage some code from `array.stats` and hence scipy is needed. Is there a specific reason that dependency has been left out of the current installs? If not, I'd be happy to add this in #6881 as part of my `skew` addition. However, if there is a good reason for excluding the dependency, let me know and we can close this issue.

A potential solution could be to add `scipy` to the `array` install and in #6881 I would then also add it to the dataframe one.

**Comment by jsignell** [comment]
IIRC scipy is not a pure-python library, so it is best installed using conda. That is why it is missing from the extra_requires. It is included in the conda envs: https://github.com/dask/dask/blob/25bdd200fcdf17368008ce475d370dd77af2bb66/continuous_integration/environment-3.8.yaml#L50

If you follow the conda section of the [development install docs](https://docs.dask.org/en/latest/develop.html#development-environment) you'll end up with an env with scipy installed. You'll notice that there are other packages that are used within dask that aren't included (for instance `graphviz`)

**Comment by jsignell** [comment]
If you'd like to add scipy to that docs section you mentioned, I think that'd be a good improvement!

**Comment by jborchma** [comment]
> If you'd like to add scipy to that docs section you mentioned, I think that'd be a good improvement!

Will do! Thanks for the quick response.
