### ISSUE TITLE
Stop supporting pandas 0.23.0

### ISSUE THREAD

**Issue by jsignell** [dask/dask#6891]
When looking over some failing tests I realized that there doesn't seem to be Python 3.7 support in pandas 0.23.0. This is confirmed by the release notes:

> Note Pandas 0.23.2 is first pandas release that’s compatible with Python 3.7 (GH20552)

[source](https://pandas.pydata.org/pandas-docs/version/0.23.3/whatsnew.html#whatsnew-0232)

With that in mind I propose that we stop supporting pandas 0.23 at all, and bump the minimum pandas version to pandas 0.24 (released January 25 2019), pandas 0.25 (released July 18 2019). 

@TomAugspurger, @jrbourbeau, @rjzamora since I think you'll have opinions :)

**Comment by TomAugspurger** [comment]
+1 to dropping 0.23. Don't have a strong opinion on whether 0.24 or 0.25 is a better lower bound. If you grep for `PANDAS_GT_0250 ` and `PANDAS_GT_0240 ` you can get a rough sense for how much compat code we have for each.

**Comment by jrbourbeau** [comment]
Also +1 for dropping 0.23. Not a strong opinion, but I'm fine setting 0.25 as the minimum support version. It's been almost a year and a half since it was released.

**Comment by jsignell** [comment]
Ok I will go for 0.25 as the minimum.

**Comment by jsignell** [comment]
I will also bump numpy up to 1.15 (released July 23 2018)
