### ISSUE TITLE
Indexing an array created from `np.object` returns wrong dtype.

### ISSUE THREAD

**Issue by aulemahal** [dask/dask#6892]
**What happened**:
When indexing a dask Array that was constructed from a numpy array of the `object` dtype, the returned dask array has a `Int64` dtype.

**What you expected to happen**:
I expected the array dtype to stay the same.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import numpy as np

d = da.from_array(np.array(['a', 'b'], dtype=np.object), chunks=(1,))
print(d.dtype)
print(d[(0,)].dtype)
```
Returns:
```
object
int64
```

**Anything else we need to know?**:
This was found while using xarray, which stores strings in object arrays, instead of '<Ux'.

**Environment**:

- Dask version: 2.30.0 (also in 2.17)
- Python version: 3.8.6
- Operating System: Linux
- Install method (conda, pip, source): conda (conda-forge)

**Comment by jsignell** [comment]
Thanks for raising this issue! I can reproduce. I'll open a PR shortly with a fix.
