### ISSUE TITLE
slow first call to parquet

### ISSUE THREAD

**Issue by sdementen** [dask/dask#6897]
**What happened**:

I am using pystore which uses dask. The sample below uses pystore but the issue appaers to be on dask side (as far as I have understood).

The first write action (to_parquet) takes an extra 0.8s vs the following calls.
The first read action (to_pandas) takes an extra 0.45s vs the following calls
The second time I write/read items from pystore, it is immediate (irrespective of the store/collection = parquet file I refer to).

**What you expected to happen**:

To not have this extra time on the first calls.

**Minimal Complete Verifiable Example**:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time

import pandas
import pystore


class Timer:
    def __enter__(self):
        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        self.end = time.perf_counter()
        self.interval = self.end - self.start
        print(f"time taken: {round(self.interval, 3)} seconds")


pystore.set_path("./pystore")

collection = pystore.store("my-store").collection("my-collection")

with Timer():
    # take 0.82 seconds
    collection.write(
        "test",
        pandas.DataFrame(
            index=pandas.date_range(2018, 2019, freq="H"), columns=list("ABCDE"), data=1.0
        ),
        overwrite=True,
    )
with Timer():
    # take 0.02 seconds
    collection.write(
        "test",
        pandas.DataFrame(
            index=pandas.date_range(2018, 2019, freq="H"), columns=list("ABCDE"), data=1.0
        ),
        overwrite=True,
    )

with Timer():
    # take 0.48 seconds
    df = collection.item("test").to_pandas()
with Timer():
    # take 0.02 seconds
    df = collection.item("test").to_pandas()
```

**Anything else we need to know?**:

When profiling the execution of the sample code, I see a long time spent in the `acquire` method of _thread.lock with the following trace.
![image](https://user-images.githubusercontent.com/1304950/100345357-7eb77a00-2fe2-11eb-8497-2189fb88edb5.png)

While debugging, I see that the line of code in dask where the execution is "paused" is https://github.com/dask/dask/blob/master/dask/threaded.py#L76

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8
- Operating System: win10
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I suggest at least linking to a pystore issue too, in case they know what's going on. I would imagine it makes a difference what mix of threads/processes you use (with the distributed client, even locally), and the size of the data and any partitions. These would be useful extra data. Also, you can use the additional dask profiling tools such as the distributed dashboard to figure out what time is being spent on.

**Comment by sdementen** [comment]
here is the minimal version I could come (smallest dataframe, remove effect of lazy imports). 
There is still a slowdown of 0.6s in the `to_parquet` (the `read_parquet` slowdown has disappeared once remove all the lazy import effects).

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time

import dask.dataframe
import pandas


class Timer:
    def __init__(self, description):
        self._description = description

    def __enter__(self):
        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        self.end = time.perf_counter()
        self.interval = self.end - self.start
        print(f"time taken for '{self._description}': {round(self.interval, 3)} seconds")


# import all modules to neutralize time of import
modules = [
    "thrift.Thrift",
    "numba.core",
    "numba.np.linalg",
    "numba.np.npyimpl",
    "numba.cpython.printimpl",
    "numba.misc.cffiimpl",
    "numba.cpython",
    "scipy.linalg",
    "packaging",
    "brotli",
    "fastparquet",
    "cffi",
    "cffi.commontypes",
    "cffi.cparser",
    "numba.core.typing.cffi_utils",
    "pycparser",
    "numba.core.typing.cmathdecl",
    "numba.core.typing.arraydecl",
    "numba.core.typing.enumdecl",
    "numba.core.typing.randomdecl",
    "numba.core.typing.collections",
    "numba.core.typing.listdecl",
    "numba.core.typing.mathdecl",
    "multiprocessing.queues",
    "multiprocessing.synchronize",
    "multiprocessing.dummy",
    "numba.core.typing.dictdecl",
    "numba.misc.gdb_hook",
    "numba.np.arraymath",
    "numba.core.runtime.context",
    "numba.np.arraymath",
    "numba.core.runtime.context",
    "numba.np.polynomial",
    "numba.cpython.heapq",
    "dask.dataframe.io.parquet.utils",
    "dask.dataframe.io.parquet.fastparquet",
    "numba.core.typing.setdecl",
    "numba.core.typing.bufproto",
    "numba.cpython.tupleobj",
    "numba.cpython.randomimpl",
    "numba.misc.literal",
    "numba.cpython.iterators",
    "numba.cpython.enumimpl",
    "numba.core.typing.npdatetime",
    "cffi.lock",
    "cffi.error",
    "cffi.model",
    "cffi",
    "cffi.commontypes",
    "pycparser.plyparser",
    "multiprocessing.queues",
    "multiprocessing.synchronize",
    "multiprocessing.dummy",
    "cffi.lock",
]


with Timer("importing modules"):
    for module in modules:
        __import__(module)

df = pandas.DataFrame(columns=["A"], index=[1])
ddf = dask.dataframe.from_pandas(df, npartitions=1)

with Timer("first write"):
    dask.dataframe.to_parquet(ddf, "dask_parquet")
with Timer("second write"):
    dask.dataframe.to_parquet(ddf, "dask_parquet")
with Timer("first read"):
    dask.dataframe.read_parquet("dask_parquet")
with Timer("second read"):
    dask.dataframe.read_parquet("dask_parquet")

```

**Comment by sdementen** [comment]
Regarding your other suggestions (type of scheduler, etc), I am just running the "default" setup.
For the profiling, the picture is the same as my original post (re `acquire` method of `_thread.lock`)

**Comment by martindurant** [comment]
I would hazard that the time is being spent in numba jit-compiling of the various functions in fastparquet, which happens on first execution. Since the package contains not just function, but also jit-classes, the compiled pieces do not cache well.

**Comment by sdementen** [comment]
Is there some way to confirm this on my side?
Would it be consistent with the time spent in acquire_lock ?

**Comment by martindurant** [comment]
> Is there some way to confirm this on my side?

You could run the code for a very small dataset with scheduler="sync" and see what shows up in a profiler like snakeviz; or you could run with the distributed scheduler and look on the dashboard. You could even profile fastparquet alone, without dask.

> Would it be consistent with the time spent in acquire_lock ?

Maybe? One of your threads will do the compilation, and the others will have to wait, I suppose.

**Comment by sdementen** [comment]
You are right!
It is the first call to `write` from fastparquet that takes a long time.
I close the issue and thank you for your support.
