### ISSUE TITLE
IndexError when supplying multiple paths to dask.dataframe.read_csv() and including a path column

### ISSUE THREAD

**Issue by Sturla22** [dask/dask#6899]
I fixed my installation (dask version 2.30) locally by adding
` and i < len(self.paths)` to this line
https://github.com/dask/dask/blob/fbccc4ef3e1974da2b4a9cb61aa83c1e6d61efba/dask/dataframe/io/csv.py#L82

I bet there is a deeper reason for why `i` is exceeding the length of paths but I could not identify it with a quick look through the neighboring code.

Minimal example to reproduce, assuming multiple csv files in the CWD:
```python
import dask.dataframe as dd
dd.read_csv("*.csv", include_path_column=True).compute() 
```

**Comment by martindurant** [comment]
Would you mind expanding your example code to generate some files too, and then include the traceback, so that we can be sure talk about exactly the same thing, and help with diagnosis?

**Comment by martindurant** [comment]
( @jsignell , for the include_path_column logic)

**Comment by jsignell** [comment]
I am not sure if this is a regression or not, but I can reproduce. Thanks for bringking this up @Sturla22. The issue is that the number of blocks does not neccessarily correspond to the number of files. I'll have a PR shortly.

**Comment by Sturla22** [comment]
Great work, thanks!
