### ISSUE TITLE
Memory issues appending to large arrays (sequential matmul, Cuda)

### ISSUE THREAD

**Issue by kellymarchisio** [dask/dask#6900]
My goal is a large matmul using cupy/CUDA (end-state: 400k x 400k, float16).  I've split the matmul into pieces and can successfully do the multiplication in slices on gpu. The need now is just to append the slices together, but I cannot seem to do this without memory issues.  I've tried the method from #5601 splitting into subarrays and using da.concatenate, but concatenate uses way too much ram as the array AB gets bigger. da = dask.array
```
# in for loop
        AB_js = xp.matmul(A, B[:, prev_i: ])
        AB_js_n = xp.asnumpy(AB_js)
        split = 500
        nsplits = math.floor(AB_js_n.shape[1] / split)
        sliced = [da.from_array(AB_js_n[:, ind*split: ind*split + split],
            chunks=('auto', 'auto')) for ind in range(nsplits)]
        l = [AB]
        l.extend(sliced)
        AB = da.concatenate(l, axis=axis)
```
AB starts out (400k, 5000), will be (400k, 400k). AB_js_n is (400k, 5000). This is in a for loop, so I add 5000 more columns every time. By ~(400k, 40k), the memory usage is already up to 33G, and increasing quickly.

How can I concatenate arrays without causing memory errors?  I just want to append these onto the end of AB - I have no need to load all of AB into RAM but it seems like it's doing that.

Alternatively, what is the best way to do large-scale matrix multiply on GPU using Dask? I cannot simply call AB = da.matmul(A, B) because matmul appears unimplemented for cupy arrays:
`AB = da.matmul(A, B)` results in `TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'matmul'>, '__call__', `

I've searched many many hours for people with similar issues, but have yet to see someone successfully doing large matrix multiply with Dask.

**Comment by mrocklin** [comment]
I recommend using the dot method, like A.dot(B) .  Also, the memory used by
matrix multiplication is highly dependent on chunking structure.  You may
want to try rechunking your arrays to have tall-and-skinny or fat-and-short
chunks to see what works best.

**Comment by kellymarchisio** [comment]
Hi @mrocklin - thanks for the response.  Perhaps I wasn't clear -- my issue isn't actually the matmul, it's that I cannot seem to concatenate arrays without the entirety of them being loaded into RAM. They're too big for RAM. How do I append onto the end of an array stored on disk?  

I've tried A.dot(B), but it seems Dask can't handle this with cupy arrays. It tries to load the entirety into GPU memory, and doesn't chunk. So it is way too big. It seems my only choice is to calculate subproblems and append them -- but dask.array.concatenate is loading the whole thing into RAM. How do people build their large arrays bit-by-bit if the final product too big for RAM?  I can't seem to find anyone having done this -- it always seems like they already have the large amount of data saved in a file, then load it to dask from a file. I need to sequentially build this.

**Comment by jsignell** [comment]
I think people often write to a file in these types of cases. Often a parquet file for tabular data, or a zarr file for nd data. Would that be a viable solution for your use case?

**Comment by jakirkham** [comment]
Any thoughts on Julia's suggestion above @kellymarchisio? 🙂

**Comment by bryanwweber** [comment]
I'm going to close this issue since there's been no response. @kellymarchisio please feel free to reopen if there are other questions here 😄
