### ISSUE TITLE
Calling `.shape` on dask array extracted from dask dataframe results in NaN

### ISSUE THREAD

**Issue by zzhengnan** [dask/dask#6917]
**What happened**:
I have a dask array that's extracted from a dask dataframe using `.values`. Calling `.shape` on said dask array gives back NaN.

**What you expected to happen**:
`.shape` returns the actual shape of the dask array.

**Minimal Complete Verifiable Example**:

```python
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> pandas_df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]})
>>> dask_df = dd.from_pandas(pandas_df, npartitions=1)
>>> extracted_arr = dask_df.loc[:, 'a'].values
>>> type(extracted_arr)
<class 'dask.array.core.Array'>
>>> extracted_arr.shape
(nan,)
>>> pandas_df.loc[:, 'a'].values.shape  # Doing the same with pandas gives the expected result
(4,)
```

**Anything else we need to know?**:
If I create the array directly with `da.from_array` -- as opposed to extracting from a dask dataframe -- the issue seems to go away.
```python
>>> import dask.array as da
>>> numpy_arr = pandas_df.loc[:, 'a'].values
>>> dask_arr = da.from_array(numpy_arr)
>>> dask_arr.shape
(4,)
```

**Environment**:

- Dask version: 2.20.0
- Python version: 3.8.6
- Operating System: macOS Catalina 10.15.7
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
That's expected, since dask dataframe doesn't know the length of each partition.

You can use https://docs.dask.org/en/latest/array-api.html#dask.array.Array.compute_chunk_sizes to compute the size of the unknown chunks (but this may be expensive)

**Comment by zzhengnan** [comment]
Thanks for the explanation @TomAugspurger.

In the example I posted above, both `dask_df` and `dask_arr` consist of a single chunk/partition. Can you help me understand why the dataframe is  not aware of its shape (more specifically, the number of rows), whereas the array is? Is this difference an intentional design choice?

```python
>>> dask_df.shape
(Delayed('int-f9c8703c-3af3-4ee9-b773-bb39bae4ef52'), 2)
>>> dask_arr.shape
(4,)
```

**Comment by TomAugspurger** [comment]
It's just the implementation for now. There's another GitHub issue dedicated for dataframe partition lengths if you search for it.

**Comment by rjzamora** [comment]
>It's just the implementation for now. There's another GitHub issue dedicated for dataframe partition lengths if you search for it.

Linking #5633 here (please do correct me if I'm mistaken)

**Comment by zzhengnan** [comment]
Thanks both for the help and the additional context.
