### ISSUE TITLE
Replace the word "chain" and "chaining" throughout the code base

### ISSUE THREAD

**Issue by brendanpl14** [dask/dask#6922]
Although it is commonly utilized in CS to denote that act of combining multiple objects, functions, or processes into a series, the word “chaining” (or “chain”) is a borderline-racist term that can be associated with slavery and the act of restraining, binding, and imprisoning slaves.  Chains were used to prevent slaves from running away, while allowing enough mobility for them to complete their forced labor.  Symbols such as open handcuffs, shackles, or broken chains are commonly used in art or literature to represent the idea of slaves breaking free from their oppressors.

These words should be removed from the code base and replaced with something else.

**Comment by rjzamora** [comment]
Thanks @brendanpl14 !

I don't actually know how sensitive the word `"chain"` really is, but it shouldn't be too hard to avoid it (although it could be confusing to use a different name for `itertools.chain`).

It is also worth noting that dask still uses the `master` branch name, which other organizations have been moving away from.

**Comment by quasiben** [comment]
I think this discussion should move to https://github.com/dask/community/issues/ where we are also discussing the [branch renaming](https://github.com/dask/community/issues/68) @rjzamora brought up

**Comment by jacobtomlinson** [comment]
I agree that this is a good thing to discuss, but we should continue it over in dask/community#68.
