### ISSUE TITLE
Update opportunistic caching doc

### ISSUE THREAD

**Issue by Timost** [dask/dask#6923]
Hi,
:heart: dask.
I think the doc on opportunistic caching can be updated to remove the experimental feature warning.

I was just watching https://coiled.io/blog/design-principles-of-distributed-systems-dask-and-pyspark/ and I had already stumbled on this page on my own and I thought it might be time to remove the warning as it's quite old. And maybe mention that it's only available on the local scheduler and not using the distributed scheduler.

**Comment by quasiben** [comment]
@Timost any interest in submitting a patch with these changes? If not, no worries

**Comment by Timost** [comment]
Sure I'll do it !
