### ISSUE TITLE
Add default compression="infer" option to read_csv

### ISSUE THREAD

**Issue by rjzamora** [dask/dask#6929]
As discussed in [cudf#6850](https://github.com/rapidsai/cudf/issues/6850), `dask.dataframe`'s `read_csv` API does not match that of pandas when it comes to compression.  The default setting in pandas is `compression="infer"`, while dask uses `compression=None`.

@dask/io - Is there a strong argument against adding a default `"infer"` option to the dask API?

cc @lmeyerov

**Comment by martindurant** [comment]
I can think of no good reason for the difference.
Note that decompression could happen within fsspec *or* pandas, but both should amount to the same thing.
