### ISSUE TITLE
Dask dataframe partition ordering

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#6937]
If I persist a dask dataframe from delayed objects:

```python
ddf = dd.from_delayed(delayed_list, meta)
ddf.to_parquet('/tmp/frame')
```

and then reread it and create another delayed list:

```python
another_delayed_list = dd.read_parquet('/tmp/frame').to_delayed()
```
will `another_delayed_list[i]` always correspond to the same object as `delayed_list[i]`?

This seems to be true in my small tests, but can it be, or is it, a guarantee?

**Comment by TomAugspurger** [comment]
> will another_delayed_list[i] always correspond to the same object as delayed_list[i]?

Do you mean same object in terms of `another_delayed_list[i] is delayed_list[i]`, or just that they're equal? If it's the latter, then yes, they'll be the same. DataFrames are ordered in the rows.

**Comment by chrisroat** [comment]
Yes, just equal is necessary.  Thanks!
