### ISSUE TITLE
dask.dataframe.read_parquet infers pyarrow.decimal128 as datetimelike

### ISSUE THREAD

**Issue by tebesfinwo** [dask/dask#6948]
**What happened**:

`dask.dataframe.read_parquet` infers `pyarrow.decimal128` as datetimelike.

**What you expected to happen**:

I expect `dask.dataframe.read_parquet` to infer `pyarrow.decimal128` as `object`.

**Minimal Complete Verifiable Example**:

```python
from decimal import Decimal
import random
import shutil

import dask.dataframe as dd
import numpy as np
import pandas as pd
import pyarrow as pa


FILE_NAME = "my_data.parquet"

schema = pa.schema([pa.field("col1", pa.decimal128(5, 2))])

random.seed(0)
data = [{"col1": Decimal(f"{random.randint(0, 346)}.00")} for i in range(23)]
ddf = dd.from_pandas(pd.DataFrame(data), npartitions=1)

try:
    shutil.rmtree(FILE_NAME)
except FileNotFoundError:
    pass

ddf.to_parquet(path=FILE_NAME, engine="pyarrow", schema=schema)
ddf2 = dd.read_parquet(path=FILE_NAME, engine="pyarrow")

assert np.dtype("O") == ddf.dtypes.to_dict()["col1"]
assert (
    np.dtype("<M8[ns]") == ddf2.dtypes.to_dict()["col1"]
)  # ddf2.col1 is `datetime64[ns]` instead of `object`.

assert np.dtype("O") == ddf2.dtypes.to_dict()["col1"], "col1 should be an object".    # AssertionError is raised.
```

**Environment**:

- Dask version: 2.30.0
- Pandas version: 1.0.3 and 1.1.5 
- Python version: 3.7.7
- Pyarrow version: 0.16.0, 0.17.1, 1.0.1, and 2.0.0
- Operating System: macOS Catalina and Amazon Linux
- Install method: poetry

**Comment by jsignell** [comment]
I can reproduce on latest master, thanks for the detailed report! I found that when you call compute on the resultant dataframe you end up with dtype `object`:

```python
assert np.dtype("O") == ddf2.compute().dtypes.to_dict()["col1"]
```
So I imagine the issue must be with some assumption in the meta construction.
