### ISSUE TITLE
Optional kwarg for `observered`

### ISSUE THREAD

**Issue by quasiben** [dask/dask#6951]
In https://github.com/dask/dask/pull/6854, dask added the `observed` keyword to categorical groupby operations.  In RAPIDS we just released cuDF 0.17 which does not currently support the `observed` keyword for categorial series groupby operations:

```python
import dask.dataframe as dd
import pandas as pd
import cudf

df = pd.DataFrame({
    'c1': pd.Categorical(['v11', 'v12', 'v11'], ['v11', 'v12', 'v13']),
    'c2': pd.Categorical(['v21', 'v22', 'v23']),
    'c3': [1, 4, 7]})


cdf = cudf.from_pandas(df)
ddf = dd.from_pandas(cdf, npartitions=1)
ddf.c1.groupby(ddf.c1).size().compute()
```

The above fails with:

```
/datasets/bzaitlen/GitRepos/dask/dask/dataframe/groupby.py in __init__(self, df, by, slice, group_keys, dropna, sort, observed)
   1109         self.observed = observed
   1110
-> 1111         self._meta = self.obj._meta.groupby(
   1112             index_meta, group_keys=group_keys, observed=observed, **self.dropna
   1113         )

TypeError: groupby() got an unexpected keyword argument 'observed'
```

RAPIDS is addressing this https://github.com/rapidsai/cudf/pull/6964, however,  when Dask is next released, this will break the stable 0.17 RAPIDS version.  I am asking if we can temporarily pass `observed` as an optional kwarg until 0.18 and then we can switch back.

**Comment by jsignell** [comment]
Sorry about that @quasiben! I will open a PR to follow the dropna pattern. @jrbourbeau this should block release.

**Comment by quasiben** [comment]
@jsignell no no, I think of this is a very big ask from the RAPIDS group.   Also, we are happy to do the work here and track

**Comment by jsignell** [comment]
I mean I merged the observed PR yesterday (aka one day before release) so I don't think it would be bad to revert it slightly if we are breaking rapids.

**Comment by rjzamora** [comment]
>I mean I merged the observed PR yesterday (aka one day before release) so I don't think it would be bad to revert it slightly if we are breaking rapids.

I don't think the PR needs to be reverted, but we do want to avoid passing `observed` unless it is explicitly passed by the user.

**Comment by jsignell** [comment]
Agree. PR coming shortly.
