### ISSUE TITLE
Error adding DateOffsets to datetime64

### ISSUE THREAD

**Issue by gerrymanoim** [dask/dask#6958]
**What happened**:

`UFuncTypeError: ufunc 'add' cannot use operands with types dtype('<M8[ns]') and dtype('O')` when adding `DateOffset` to `datetime64`

**What you expected to happen**:

An offset adjusted column, matching the pandas behavior. 

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

base = pd.Series([1,2,3], dtype="datetime64[ns]")
offsets = pd.Series([pd.offsets.DateOffset(years=o) for o in range(3)])

base+offsets

# results in:
# 0   1970-01-01 00:00:00.000000001
# 1   1971-01-01 00:00:00.000000002
# 2   1972-01-01 00:00:00.000000003
# dtype: datetime64[ns]

dask_base = dd.from_pandas(base, npartitions=1)
dask_offsets = dd.from_pandas(offsets, npartitions=1)

# Triggers error
dask_base + dask_offsets
```

**Anything else we need to know?**:

I'm not entirely sure if this is supposed to be supported, but I didn't see anything in the docs so I figured I'd confirm the expected behavior. The `dtype` of `offsets` is indeed `object`, but I guess pandas handles this internally? 

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
I feel like this is missing some context. Is this the description you intended to put on the dask issue tracker @gerrymanoim?

**Comment by gerrymanoim** [comment]
Err - whoops - sorry! Mistaken copy/paste here. Will find the repo that I originally had here.

**Comment by gerrymanoim** [comment]
@jsignell - Apologies - fixed the issue text now.

**Comment by jsignell** [comment]
Oh that is an interesting bug! It is kind of tough becuase I can't think of a way to pass a meta into the function, which would be the easiest way to workaround the issue. There are a couple other things going on though. One is that the default non_empty `_meta` for objects is a string. And the other is that even if you set the `_meta` on dask_offsets it is ignored. I'll open a PR to mull over some ideas.

**Comment by gerrymanoim** [comment]
I was trying to figure out how to override the meta guessing as well (or some other reasonable workaround), but couldn't figure out if there was a reasonable way to do that. Thanks for confirming.

**Comment by jsignell** [comment]
There is still a lingering question of if `from_pandas` should have a `meta` kwarg. At the moment it tries to deduce it from the data which seems good, but it is being coerced to an empty dd.Series, so the only metadata that it retains is the dtype. In this case the dtype is object, which is super uninformative. It'd be better to just let the `meta` be `.head()` or something, but I am probably missing some subteleties about why it's desirable to use dask collections for metas rather than pandas.
