### ISSUE TITLE
Repartition by a factor of existing number of partitions

### ISSUE THREAD

**Issue by kinghuang** [dask/dask#6962]
The [DataFrame.repartition](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.repartition) method takes an `npartitions` argument as one of the ways to determine how many partitions to target. I often want to scale a dataframe by a factor of its existing number of partitions. It would be useful to have a `factor` argument that does this.

For example, say I read in a Parquet dataset with Hive-style monthly partitions, each with one file/table. When I read in the dataframe for a single year, I get a corresponding Dask dataframe with 12 partitions. If I want to double this to 24 to spread out subsequent tasks in a Dask cluster, I have to calculate the number of partitions and pass that value for the `npartitions` argument.

```python
from dask import dataframe as dd

df = dd.read_parquet("/example/dataset", filters=[[("year", "=", "2018")]])
assert df.npartitions == 12

df.repartition(npartitions=df.npartitions * 2)
assert df.npartitions == 24
```

It would be nice if the `repartition` method directly took a factor. So, something like this could be used.

```python
df.repartition(factor=2)
assert df.npartitions == 24
```

The reason for this is that I'm configuring repartitioning in a Dagster pipeline, and the repartition config options are mapped directly to the [DataFrame.repartition](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.repartition) method. I can't specify `df.npartitions * 2` in the config YAML, and I'd rather not introduce a custom config option like `factor` that doesn't have a corresponding argument in the underlying method.

**Comment by TomAugspurger** [comment]
My initial reaction is that this doesn't warrant a dedicated keyword. Repartition already has four distinct ways of repartitioning. I wouldn't want to add another that's so closely related to `npartitions`.

**Comment by jsignell** [comment]
You might be able to play around with `chunksize` in your `read_parquet` call to get the desired behavior.
