### ISSUE TITLE
Repartitioning on index with dtype object splits the same value of the index into different partitions.

### ISSUE THREAD

**Issue by FilippoBovo** [dask/dask#6972]
**What happened**:

Repartitioning a Dask DataFrame on an index with `object` dtype does not isolate the values to single partitions.

For example, if the index contains values `A`, `B` and `C` and the DataFrame is repartitioned to 3 partitions, the first partition contains only `A`s, the second partition only `B`s and the third partition both `B`s and `C`s.

**What you expected to happen**:

I would expect that `B` are not split in two partitions but are isolated in one partition. 

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd


data = pd.DataFrame(index=pd.Index(["A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "C"]))
data = dd.from_pandas(data, npartitions=2)
# After this the values are isolated into single partitions:
#   the first partition contains the `A`s and the second partitions contains the `B`s and the third `C`.

repartitioned_data = data.repartition(npartitions=3)
# After this the `B`s are split into the 2nd and 3rd partitions:
#   the first partition contains the `A`s, the second partitions contains two `B`s and the third one `B` and one `C`.
```

**Anything else we need to know?**:

The following way of repartitioning isolates the values as I would expect:

```python
data.reset_index().repartition(npartitions=3).set_index('index')
# After this the values are isolated into single partitions:
#   the first partition is empty, the second partitions contains the `A`s and the third the `B`s and `C`.
```

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: MacOS Big Sur (14.0.1)
- Install method (conda, pip, source): Pip

**Comment by rjzamora** [comment]
I'm not certain what the correct functionality "should" be for `repartition`, but I do know that the algorithm is very different from `set_index`...

If you have a numerical index type, specifying an increased number of partitions to `repartition` will result in new (interpolated) divisions.  If you have an "object" index type, interpolation is not spported, and so you will not have known divisions after the `repartition` call (so you will not get the "isolation" you are looking for).

When you call `set_index`, you are not inerpolating, but are effectively giving dask permission to perform a shuffle to get data into the "correct" partitions.  If you specify exact divisions for your last example, you will probably get the partitioning you want:

```python
data.reset_index().set_index('index', divisions=['A', 'B', 'C', 'D'])
```

**Comment by FilippoBovo** [comment]
@rjzamora, thank you for the explanation and prompt reply.

**Comment by jsignell** [comment]
Just as a note, you can do a similar pattern for `repartition`:

```python
repartitioned_data = data.repartition(divisions=["A", "B", "C", "C"])
```

The difference is that like @rjzamora said, there is no interpolation, so only values that are in the index are valid divisions. Hence: `"C", "C"`.

I'm closing this since I think it is resolved, but feel free to reopen if you disagree. And as always if you can think of a way to improve the docs, please open a PR :)

**Comment by FilippoBovo** [comment]
@jsignell, thank you. I will have a look at an improvement for the docs in the second week of January.
