### ISSUE TITLE
`npartitions` argument in `set_index` DataFrame method does not work.

### ISSUE THREAD

**Issue by FilippoBovo** [dask/dask#6974]
**What happened**:

Setting the index of a Dask DataFrame with argument `npartitions` does not set the specified number of partitions.

**What you expected to happen**:

I expect that, if I set for example `npartitions=1` on a DataFrame originally with 2 partitions, the output has 1 partition.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd


data = pd.DataFrame(index=pd.Index(["A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "C"]))
data = dd.from_pandas(data, npartitions=2)
print(data.reset_index().set_index("index", npartitions=1).npartitions)
# Output: 2
# I would have expected the output to be: 1
```

**Anything else we need to know?**:

Using different numbers of argument `npartitions` in `set_index`, like 3 or 5, does not change the number of partitions either.

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: MacOS Big Sur (14.0.1)
- Install method (conda, pip, source): Pip

**Comment by jsignell** [comment]
Indeed! Thanks for raising this. I think I have a fix. I'll open a PR in a minute.

**Comment by FilippoBovo** [comment]
Thank you very much for your quick reply, @jsignell!
