### ISSUE TITLE
dask.bag.from_delayed gives error while calling compute method

### ISSUE THREAD

**Issue by Kshitij68** [dask/dask#6977]
I was trying to convert list(dask.delayed) objects to dask.bag objects using dask.bag.from_delayed functionality

```python
import dask
assert dask.__version__ == '2020.12.0'
import dask.bag as db
from dask import delayed

def func(a):
    return a

a = [delayed(func)(i) for i in range(10)]
a = db.from_delayed(a)
try:
    a.compute()
except TypeError as err:
    assert "object of type 'int' has no len()"
```

- Dask version: 2020.12.0
- Python version: 3.7.4
- Operating System: MacOS
- Install method (conda, pip, source): Pip

**Comment by Kshitij68** [comment]
Full Traceback:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-54807ec12509> in <module>
      9 a = [delayed(func)(i) for i in range(10)]
     10 a = db.from_delayed(a)
---> 11 a.compute()

~/anaconda3/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    277         dask.base.compute
    278         """
--> 279         (result,) = compute(self, traverse=False, **kwargs)
    280         return result
    281 

~/anaconda3/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    565         postcomputes.append(x.__dask_postcompute__())
    566 
--> 567     results = schedule(dsk, keys, **kwargs)
    568     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    569 

~/anaconda3/lib/python3.7/site-packages/dask/multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, **kwargs)
    226             pack_exception=pack_exception,
    227             raise_exception=reraise,
--> 228             **kwargs
    229         )
    230     finally:

~/anaconda3/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

~/anaconda3/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

~/anaconda3/lib/python3.7/site-packages/dask/local.py in execute_task()
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/anaconda3/lib/python3.7/site-packages/dask/core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/anaconda3/lib/python3.7/site-packages/dask/bag/core.py in reify()
   1790     if isinstance(seq, Iterator):
   1791         seq = list(seq)
-> 1792     if len(seq) and isinstance(seq[0], Iterator):
   1793         seq = list(map(list, seq))
   1794     return seq

TypeError: object of type 'int' has no len()
 `

**Comment by jsignell** [comment]
Sorry for the slow response. `db.from_delayed` expected a list of delayed objects where each object represents a partition of the bag, so the delayed object should return lists.

```python
import dask

import dask.bag as db
from dask import delayed

@delayed
def func(a):
    return [a]  # this part is the crucial bit

a = [func(i) for i in range(10)]
a = db.from_delayed(a)
a.compute()
```

I am going to close this issue, since I think the docs are pretty clear: 

> Create bag from many dask Delayed objects.
>
>These objects will become the partitions of the resulting Bag.  They should
evaluate to a ``list`` or some other concrete sequence.

**Comment by kshitij-mathur-by** [comment]
thanks for the response @jsignell !
Yes, this was pretty straightforward.
