### ISSUE TITLE
Unite do and value into delay

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#699]
When parallelizing existing codes I find myself adding a kwargs `do=identity` in many functions

```python
def f(x, y, do=identity):
    return do(g)(x) + do(g)(y)
```

By default this does nothing and the original code continues without change.  

For more complex functions sometimes we pass do within subfunctions

```python
def h(z, do=identity):
    return f(z, z, do=do)
```

This is again harmless in the common case.   However now I need to track which functions parallelize themselves with `do` and onto which I want to call `do` directly. 

```python
result = do(h)(z)  # don't want this
result = h(z, do=do)  # do want this

result = do(f)(z)  # do want this
result = f(z, do=do)  # don't want this
```

 Furthermore, I sometimes want to use `value` but don't want to track sending each down.

To resolve this I propose a new function, `delay` that combines `do` and `value` and works well with the above convention (which I've found a pleasant way to parallelize existing codes.)

```python
import inspect
from functools import partial
def delay(x):
    if callable(x):
        try:
            spec = inspect.getargspec(x)
        except TypeError:
            return do(x)
        if 'delay' in spec.args:
            return partial(x, delay=delay)
        else:
            return do(x)
    else:
        return value(x)
```

This has the following behavior

```python
delay(func) -> do(func)
delay(val) -> value(val)  # unless val is a callable!  warning!
delay(function-with-delay-kwarg) -> partial(function, delay=delay)
```

Unifying do and value in the common case has some value (although also some cost in the case of callable values).  Handling delay-aware functions like `f` above has some value but bakes in a convention.

I'm happy to continue using this in my own user code for a while.  I'm not yet proposing inserting this into dask proper.  I've found this valuable though both in private work and when trying to parallelize sklearn pipelines and gridsearches.

**Comment by jcrist** [comment]
Do you still see this as a good way of doing things? Minus the `delay` keyword, this is fixed by #1111.
