### ISSUE TITLE
Pinned dask[distributed] deployemnts are broken.

### ISSUE THREAD

**Issue by whalebot-helmsman** [dask/dask#6991]
I have pinned version `dask[distributed]==2.10.1` in my requirements file. Since recent release(2020.12.0) it installs `distributed==2020.12.0` which isn't compatible with pinned dask version

**Comment by gforsyth** [comment]
Thanks for reporting @whalebot-helmsman -- the `distributed` extra as defined in `setup.py` only has a lower bound defined in its version constraints.  I'd suggest that you pin `distributed` independently.  Usually you don't want `dask` and `distributed` to stray too much from one another version-wise, so maybe pin to `distributed==2.11.0`?

**Comment by jsignell** [comment]
@gforsyth would it make sense to pin distributed more tightly in dask? I could imaging pinning to `YYYY.MM.*` or something.

**Comment by gforsyth** [comment]
I think we should, and the calver switch should make it a lot easier to manage

**Comment by jsignell** [comment]
@dask/maintenance does anyone not like that idea?

**Comment by martindurant** [comment]
I don't think we formally promise to release together, though, so it's conceivable that a new release of distributed needs the version of dask from the previous month, or a bugfix-only release of dask is needed for the latest distributed, again crossing the month boundary.

**Comment by jsignell** [comment]
hmm yeah and I guess pinning it in the setup.py would make it hard for people to upgrade their distributed independently in a case like that.

**Comment by martindurant** [comment]
It would be hard in the case of `pip install -U dask[distributed]`. I don't know if that is considered common. You would still be able to upgrade the parts separately, though I hear that the new pip resolver is causing problems.

**Comment by jsignell** [comment]
Yeah ok I feel convinced that we should not change the setup.py. @gforsyth I'm going to close this unless you disagree.
