### ISSUE TITLE
Revert reverse compatibility issues in svd_compressed

### ISSUE THREAD

**Issue by eric-czech** [dask/dask#7003]
https://github.com/dask/dask/pull/6813/files introduced a couple changes that are not reverse compatible and cause problems like https://github.com/dask/dask-ml/pull/767.  Specifically:

- The iteration type was changed to 'none' instead of 'power'
- The default number of iterations was changed to 1 instead of 0

There isn't a good reason that enabling iteration should require changing two parameters.

I propose we remove the 'none' type iterator and allow iterations of 0 to be equivalent to no iteration for all iterator types.  

cc: @RogerMoens @tomwhite

**Comment by RogerMoens** [comment]
@eric-czech: to add a note on this, the reason for splitting the "none" and "power" iterator option was to follow the structure of the paper by Halko et al. This explicit notation also requires the user to notice that there is an actual difference, between those options.

**Comment by eric-czech** [comment]
Makes sense @RogerMoens.  I agree that iterator='none' is more clear than iterator='power' and n_iter=0 but I don't think it's important enough to break compatibility.  Allowing iterator='none' **and** n_iter=0 is one potential middle-ground but fewer possible parameterizations is probably better (so I'm weakly in favor of removing the 'none' option).  

It does make me wonder when breaking changes are expected under the new release model though.  Are there any conventions for that @mrocklin?

**Comment by jsignell** [comment]
I can answer this part:

> It does make me wonder when breaking changes are expected under the new release model

Part of the rationale for moving to calver is to make it clear that we can do breaking changes in any release (which was what we were doing in practice anyway). In general, we try to avoid breaking changes and particularly avoid unnecessary breaking changes. In this particular instance, I think it would be best to revert to the old values and add a note in the docstring to make it clear that the value might change in the future.

**Comment by eric-czech** [comment]
Thanks @jsignell!  That's good to know.
