### ISSUE TITLE
Automatically open an issue for upstream CI failures

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#7007]
I noticed Xarray has some [nice infrastructure](https://github.com/pydata/xarray/blob/d3792a6435c6e1e4a94d80bbaad22511114a9b5d/.github/workflows/upstream-dev-ci.yaml#L69) for automatically opening up an issue when there are failures in their upstream CI build. https://github.com/pydata/xarray/issues/4717 is an example issue which was opened and lists which tests failed.

Adding something similar here for Dask would be beneficial as today upstream CI failures can go unnoticed since they're only run on the main development branch and don't trigger a notification when a failure happens. 

cc @andersy005 (who originally added this to Xarray) and @jacobtomlinson (who likes to automate things : ) )

**Comment by jsignell** [comment]
This would be really nice to have. Especially once we get upstream passing :)
