### ISSUE TITLE
npartitions obtained with `from_pandas`... inconsistent?

### ISSUE THREAD

**Issue by yohplala** [dask/dask#7010]
```python
from dask import dataframe as dd
import pandas as pd
a=list('aabbccddeef')
b=list(range(len(a)))
df = pd.DataFrame(dict(a=a, b=b),
                  index = pd.date_range(start='20200101',end='20200106', periods=len(a)))
ddf = dd.from_pandas(df, npartitions=5)
ddf.npartitions
```
Result
```bash
4
```
```python
from dask import dataframe as dd
import pandas as pd
a=list('aabbccddeef')
b=list(range(len(a)))
df = pd.DataFrame(dict(a=a, b=b),
                  index = pd.date_range(start='20200101',end='20200106', periods=len(a)))
ddf = dd.from_pandas(df, npartitions=6)
ddf.npartitions
```
Result
```bash
5
```

The 2nd result tends to show that getting 5 partitions would be doable.
So, when asking for 5 partitions as in the 1st example, why not getting them?

Bests

**Comment by martindurant** [comment]
> npartitions : int, optional
>     The number of partitions of the index to create. Note that depending on
>     the size and index of the dataframe, the output may have fewer
>     partitions than requested.
> 

You get the correct answer in the limit of many rows. The calculation is actually
```
chunksize = int(ceil(nrows / npartitions))
```
(in `dask.dataframe.io`) where you should notice the `ceil` - this guarantees *at most* as many partitions as requested, and if far easier to code than trying to get the exact number, and having irregularly sized partitions.

You could choose to supply `chunksize=` directly, if preferable.
