### ISSUE TITLE
astype convert object to category, get unknown categorical!

### ISSUE THREAD

**Issue by YishuiLi** [dask/dask#7018]
**What happened**:
```python
import dask.dataframe as dd
df = dd.read_csv("E:/iris.csv")
df["iris"] = df["iris"].astype('category')
print(df["iris"])
```
It convert object to unknown categorical!
![image](https://user-images.githubusercontent.com/16732930/103338309-eddc2e80-4ab8-11eb-9cb0-cffb04fd859e.png)

**What you expected to happen**:
use pandas
![image](https://user-images.githubusercontent.com/16732930/103338362-1d8b3680-4ab9-11eb-9701-b9ac419e2f11.png)

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.6.5
- Operating System: windows 10
- Install method (conda, pip, source): pip install dask

**Comment by jsignell** [comment]
This is expected behavior. Dask does not read your whole datafile right away, so it doesn't know what categories are in it unless you explicitly tell it.
