### ISSUE TITLE
atop with multiple output arguments

### ISSUE THREAD

**Issue by shoyer** [dask/dask#702]
Yesterday, we (@mrocklin, @clarkfitzg and myself) discussed writing some sort of user facing API for `atop` for xray that makes use of xray's metadata to automatically generate complex `atop` calls by inspecting the result of applying the function to a single block.

To make this work generically as a function that transforms `xray.Dataset` objects, which can be containers of multiple dask arrays, we need a version of `atop` where the applied function `func` can have multiple output arguments.

**Comment by mrocklin** [comment]
The `atop` function may be restrictive in other ways as well.

For example it currently it trusts that chunks either maintain their shape or else collapse dimensions entirely.  This may be overly restrictive for your case.


The lower-level function `top` may also be appropriate though would also require mucking about with dicts a bit more and handling shape and chunk shapes yourself.

I see a few options for multiple outputs:

1.  We add the `(getitem, key, i)` tasks directly in `atop`
2.  We provide a utility function that spawns these out (provided below)
3.  You work with `top` and handle chunk shapes yourself (this is possibly hard)

```python
def split(x, nout):
    name = ...
    for i in range(nout):
        dsk = {(name,) + k[1:]: (getitem, k, i) for k in core.flatten(x._keys())}
        yield Array(merge(x.dask, dsk), name, x.chunks, x.dtype)
```

**Comment by shoyer** [comment]
I'm OK with chunks along a dimension either preserving their shape or being collapsed entirely.

What I would like, though, is the ability to create new, unchunked, dimensions. I suspect that we could accommodate this by adjusting the `numblocks` argument to `top`, e.g., instead of this:

    >>> top(add, 'z', 'ij', 'x', 'ij', 'y', 'ij', numblocks={'x': (2, 2),
    ...                                                      'y': (2, 2)})  # doctest: +SKIP

we should specify blocks like this:

    >>> top(add, 'z', 'ij', 'x', 'ij', 'y', 'ij', dims={'i': 2, 'j': 2})

New dimensions would be required to have a single block, or alternatively, could be interpreted as indicating a function that yields multiple chunks, e.g.,

    def output_many(x):
        for j in range(10):
            yield x + j

     top(output_many, 'z', 'ij', 'x', 'i', dims={'i': 5, 'j': 10})

I don't actually have an any use cases in mind for yielding multiple chunks along new dimensions, though.

**Comment by shoyer** [comment]
Actually, working with the existing version of `top` directly might be fine. The functions I want to insert into the task graph will each returning a single `xray.Dataset` (or `DataArray`) object. We can then write the book-keeping that turns these results back into dask arrays ourselves.

**Comment by clarkfitzg** [comment]
Still wrapping my head around all this. I'd like to understand:

1. what the existing dask / xray libraries can do together here
2. a specific use case of new functionality we'd like for xray

@shoyer writes:

> What I would like, though, is the ability to create new, unchunked, dimensions.

Does that happen in the code below?

```
import numpy as np
import xray
from dask.dot import dot_graph


def double(darray):
    '''
    Add a new dimension to the dataarray
    '''
    return xray.concat((darray, 2 * darray), dim='new_dim')


# Generate some data
da = xray.DataArray(np.random.randn(100), name='noise')
da[:50].to_dataset().to_netcdf('noise1.nc')
da[50:].to_dataset().to_netcdf('noise2.nc')

# End user writes something like this
ds = xray.open_mfdataset('noise*.nc').pipe(double)

dot_graph(ds.noise.data.dask, 'concat')
```

Which produces:

![image](https://cloud.githubusercontent.com/assets/5356122/9853089/c6cf28c6-5ab6-11e5-802b-500627da9f7a.png)

This creates the expected dataset.

**Comment by shoyer** [comment]
Yes, that's a good example of adding a new dimension. 

A simple use case that is currently impossible is to take the median along one axis of a large array. We currently don't have a median in dask array because streaming quantiles are non-trivial. However, in many practical cases it's actually fine to load al the data necessary for the median in a single chunk:

- Given a large 3D dataset with dimensions (latitude, longitude, time), compute the median across time.

**Comment by clarkfitzg** [comment]
So in this case the large 3d dataset contains several dask arrays. Then we use `da.top` to apply an arbitrary function along a dimension. Is this correct?

**Comment by shoyer** [comment]
Yes, though we might actually be able to use `da.atop` here to keep track of a bit more of the bookkeeping for us.

**Comment by shoyer** [comment]
Quite belatedly, the xarray wrapper is becoming a reality (see https://github.com/pydata/xarray/pull/1517).

Supporting multiple output argument from `atop` (or adding another function that supplies this fuctionality) would still be useful here. As far as I can tell, it's the last missing ingredient required to wrap arbitrary NumPy gufuncs.

**Comment by eriknw** [comment]
@shoyer writes:
> As far as I can tell, it's the last missing ingredient required to wrap arbitrary NumPy gufuncs.

I would like this as well in order to wrap gufuncs with multiple outputs.  Here is a contrived example using `numba` to create a gufunc:
```python
>>> import numba
>>> import dask.array as da
>>> x = da.random.random(size=(200, 300), chunks=100)
>>> y = da.random.random(size=(300, 400), chunks=100)

>>> @numba.guvectorize(['float64[:, :], float64[:, :], float64[:, :, :], float64[:, :, :]'],
...                    ('(i,j),(j,k)->(i,j,k),(i,j,k)'))
... def add_and_sub(x, y, res_add, res_sub):
...     for i in range(res_add.shape[0]):
...         for j in range(res_add.shape[1]):
...             for k in range(res_add.shape[2]):
...                 res_add[i, j, k] = x[i, j] + y[j, k]
...                 res_sub[i, j, k] = x[i, j] - y[j, k]
... 
>>> res_add, res_sub = add_and_sub(x.compute(), y.compute())
>>> # validate calculations
>>> (res_add == x.compute()[:, :, None] + y.compute()[None, :, :]).all()
True
>>> (res_sub == x.compute()[:, :, None] - y.compute()[None, :, :]).all()
True
```
and I would like to be able to specify multiple outputs for `atop` as
```python
>>> da_add, da_sub = da.core.atop(
...     add_and_sub, 'ijk,ijk',  # <-- two output block patterns
...     x, 'ij',
...     y, 'jk',
...     dtype='f8'
... )
```

**Comment by mrocklin** [comment]
Are there ever cases where the output indices would not be identical?

**Comment by eriknw** [comment]
> Are there ever cases where the output indices would not be identical?

Yes.

**Comment by mrocklin** [comment]
How would the function behave in that situation?

**Comment by eriknw** [comment]
Ah, I see how this becomes difficult when the output contains a contraction and not all outputs are the same contraction.  I'll see if I can come up with coherent behavior.

**Comment by shoyer** [comment]
> Are there ever cases where the output indices would not be identical?

My understanding is that `atop` would still map to a single call to `top`, but outputs might be remapped to multiple dask arrays. If there are outputs with different indices, then the "extra" indices would need to correspond to a single chunk, e.g., the dask arrays corresponding to outputs 'abc,bcd' would have one chunk along the dimensions corresponding to `a` and `d`.

**Comment by eriknw** [comment]
@shoyer, I'm not sure I follow.  Then again, I'm not as familiar with `top` as I am with `atop`.

Here's a hacked-together example that uses multiple calls to `atop` (one per output shape).  Criticisms welcome.
```python
>>> import dask.array as da
>>> import toolz
>>> from functools import partial
>>> 
>>> 
>>> def stack_outputs(indices, func, *args, **kwargs):
...     results = func(*args, **kwargs)
...     if len(indices) > 1:
...         return np.stack([results[i] for i in indices])
...     else:
...         return results[indices[0]]
... 
>>> 
>>> def multi_atop(func, out_inds, *args, **kwargs):
...     """Like ``atop``, but accept multiple output patterns such as "ij,ijk"
...     
...     Identical output patterns are calculated at the same time.
...     Different output patterns are calculated separately.
... 
...     """
...     pattern_to_indices = {
...         key: [v[0] for v in vals]
...         for key, vals in toolz.groupby(1, enumerate(out_inds.split(','))).items()
...     }
...     results = {}
...     for pattern, indices in pattern_to_indices.items():
...         new_kwargs = dict(kwargs)
...         new_pattern = pattern
...         if len(indices) > 1:
...             new_kwargs.setdefault('new_axes', {})['z'] = len(indices)
...             new_pattern = 'z' + new_pattern
...         stacked = da.core.atop(
...             partial(stack_outputs, indices, func),
...             new_pattern,
...             *args,
...             **new_kwargs
...         )
...         if len(indices) > 1:
...             for i, index in enumerate(indices):
...                 results[index] = stacked[i]
...         else:
...             results[indices[0]] = stacked
...     return tuple(results[i] for i in range(len(results)))
... 
>>> 
>>> def my_gufunc(x, y):
...     """x[i,j], y[j,k]"""
...     return (
...         x.sum(axis=0) + y.sum(axis=1),  # j
...         x.sum(axis=0) - y.sum(axis=1),  # j
...         x + y.sum(axis=1),  # ij
...         # x - y.sum(axis=1),  # ij
...         x.sum(axis=0)[:, None] + y,  # jk
...         x.sum(axis=0)[:, None] - y,  # jk
...         x[:, :, None] + y[None, :, :],  # ijk
...         x[:, :, None] - y[None, :, :],  # ijk
...     )
... 
>>> x = da.random.random(size=(200, 300), chunks=100)
>>> y = da.random.random(size=(300, 400), chunks=100)
>>> 
>>> multi_output = multi_atop(
...     my_gufunc, 'j,j,ij,jk,jk,ijk,ijk',
...     x, 'ij',
...     y, 'jk',
...     dtype='f8',  # TODO: provide ability to specify dtype for each output
...     concatenate=True,
... )
>>> real_x, real_y, *results1 = da.compute(x, y, *multi_output)
>>> results2 = my_gufunc(real_x, real_y)
>>> for val1, val2 in zip(results1, results2):
...     assert np.allclose(val1, val2)
```
and here's a visualization of `multi_output`:
![image1](https://user-images.githubusercontent.com/2058401/30612893-259ae17e-9d54-11e7-975b-2a51e8035f28.png)

**Comment by eriknw** [comment]
> If there are outputs with different indices, then the "extra" indices would need to correspond to a single chunk, e.g., the dask arrays corresponding to outputs 'abc,bcd' would have one chunk along the dimensions corresponding to a and d.

I see.  So with this approach, only dimensions shared by all outputs would be allowed to have more than one chunk.

Here's a simpler example than may better illustrate the benefit of recomputing for each output shape.  Here, the outputs are shaped `i` and `j`, so there are no shared dimensions on which to chunk using the single-pass approach with `top`.
```python
def simple_gufunc(x):
    return (
        x.sum(axis=1),
        x.sum(axis=0)
    )

multi_output = multi_atop(
    simple_gufunc, 'i,j',
    x, 'ij',
    dtype='f8',
    concatenate=True,
)
real_x, *results1 = da.compute(x, *multi_output)
results2 = simple_gufunc(real_x)
for val1, val2 in zip(results1, results2):
    assert np.allclose(val1, val2)
```
```python
multi_output[0].visualize()
```
![multi_output0](https://user-images.githubusercontent.com/2058401/30617542-7fb90ec8-9d64-11e7-9326-ac4fb9c80d12.png)
```python
multi_output[1].visualize()
```
![multi_output1](https://user-images.githubusercontent.com/2058401/30617549-87553a9e-9d64-11e7-8d5f-b9c5ab2e34d4.png)
```python
dask.visualize(*multi_output)
```
![multi_output01](https://user-images.githubusercontent.com/2058401/30617556-8d10c2be-9d64-11e7-9bf1-520fca4c975f.png)
The function `multi_atop` implemented above more-or-less serves my immediate needs.

**Comment by eriknw** [comment]
I've started implementing this in a branch.  @shoyer, I'd like your thoughts on API, functionality, and whether the following addresses your needs.  Here's an example call:
```python
results = multi_atop(  # alternative name: atop_gufunc
    my_gufunc, 'ij,jk,ijk',
    in1, 'ij',
    in2, 'jk',
    dtypes='i8,f8,f8',
    input_chunks={
        'i': None,  # all in one chunk
        'j': 100,  # reduce chunksize along this chunkable dimension
    },
    # output_chunks={...}  # do we want this?
)
```
As you mentioned above, the gufunc may require that all data in a given dimension be in a single chunk.  I made this explicit with `input_chunks=` keyword argument (where `None` or maybe `-1` means to rechunk the dimension into one chunk).

The behavior that makes the most sense to me is to recompute the gufunc for different output shapes so as to minimize memory usage in a distributed or cachable setting.  I showed an example of this in the previous comment.  After memory usage is minimized, then calculate as many outputs in a single call to the gufunc as possible (hence, so first minimize memory, then minimize CPU).

I would say that ghosting and reduction steps are out of scope (at least for now).  Am I missing anything?  Would this be useful?  Do we want the convenience to rechunk both before and after the calculation?

**Comment by shoyer** [comment]
A version of the current `atop` API with multiple output arguments would be fine, but if we're going to make a new functions (which might be necessary for sanity) we should consider a new API with a specification more similar to how numba/numpy [represent gufunc core dimensions](https://docs.scipy.org/doc/numpy/reference/c-api.generalized-ufuncs.html), e.g.,  `da.gufunc(np.matmul, '(n,m),(m,o)->(n,o)', x, y)` for (naively) parallelized matmul. The API would be pretty similar to `da.elemwise`, except with the extra `signature` argument.

@eriknw writes:

> Here's a simpler example than may better illustrate the benefit of recomputing for each output shape. Here, the outputs are shaped i and j, so there are no shared dimensions on which to chunk using the single-pass approach with top.

I don't think your "recompute for each output shape" model makes sense, in general. It imposes a specific condition on your core functions: that they can be factorized over output dimensions. However, this does not hold in general (or even usually, at least for gufuncs I've encountered). For example, consider this variation of your `simple_gufunc` with the same core dimension signature `(i,j)->(i),(j)`:
```python
def simple_gufunc(x):
    # note that I switched axes to count from the end, per the gufunc spec,
   # which uses core dimensions at the end
    total = x.sum(axis=(-2, -1))
    return (
        x.sum(axis=-1) - total,
        x.sum(axis=-2) - total
    )
```

For cases where inputs/outputs can be factorized over some dimensions, I think you really ought to be writing separate functions to parallelize with dask, rather than calling them a single combined "gufunc".

> As you mentioned above, the gufunc may require that all data in a given dimension be in a single chunk.

I would actually say this is a defining characteristic for gufuncs. If you can represent their data in multiple chunks, then it's a "loop" dimension (which should support broadcasting) rather than a "core" dimension (which sets aside gufuncs from normal ufuncs). So I think we really just need a way to indicate "core" vs "loop" dimensions.

> I would say that ghosting and reduction steps are out of scope (at least for now)

Agreed. These are useful but don't fit the gufunc model.

**Comment by eriknw** [comment]
Thanks for the thoughtful reply @shoyer.  I agree with basically everything you said.

I wouldn't mind having a separate function that uses the numpy/numba syntax for specifying dimensions, especially since my use case involves creating these functions via numba.

I agree that the core issue is how to indicate "core" vs "loop" dimensions.  Your advice is sound.  I believe I *can* (and, hence, probably *should*) break my gufunc into multiple gufuncs, and this should be encouraged.  I need to see how much work this will be on my end.

**Comment by magonser** [comment]
I have the two following questions:

1) Would this new "da.gufunc" do any broadcasting, is it done in the sense of
    - `np.meshgrid(..., indexing='ij', sparse=False)`, or
    - `np.meshgrid(..., indexing='ij', sparse=True)`, or
    - nothing at all and just presenting the called function with the chunks?

2) Why do we need to explicitly indicate the core dimension? If input arrays are such,
that a specific dimension has only one chunk, then it already could serve as indication for a core dimension.
However since `dask.array` usually automatically rechunks if necessary, i.e. that would motivate for an explicit option to specify core-dimensions


From current thoughts and taking your thoughts further, I could imagine the following APIs

`da.gufunc(func, signature, *arrays, dtype, new_axes=None, coredim=None, **kwargs)`

Note: `kwargs` could contain additional arguments similar to `da.atop`

Here is a set of tests, that illustrate what I mean:

```python
import dask.array as da
import numpy as np
from numpy.testing import assert_array_almost_equal


def test_gufunc_scalar_output():
    def foo():
        return 1

    x = da.gufunc(foo, "->()", dtype=int)

    assert x.compute() == 1


def test_gufunc_vector_output():
    def foo():
        return np.array([1, 2, 3], dtype=int)

    x = da.gufunc(foo, "->(i_0)", dtype=int, new_axes={"i_0": 3})

    assert x.chunks == ((3,),)
    assert_array_almost_equal( x.compute(), [1, 2, 3])


def test_gufunc_elementwise():
    def foo(x):
        return 2 * x

    a = da.array(np.arary([1, 2, 3]), chunks=2)
    x = da.gufunc(foo, "(i)->(i)", a, dtype=int)

    assert x.chunks == ((2, 1),)
    assert_array_almost_equal(x.compute(), [2, 4, 6])


def test_gufunc_one_scalar_output():
    def foo():
        return 1,

    x, = da.gufunc(foo, "->(),", dtype=(int,))

    assert x.compute() == 1


def test_gufunc_two_scalar_output():
    def foo():
        return 1, 2

    x, y = da.gufunc(foo, "->(),()", dtype=(int, int))

    assert x.compute() == 1
    assert y.compute() == 2


def test_gufunc_two_mixed_outputs():
    def foo():
        return 1, np.ones(2, 3, dtype=float)

    x, y = da.gufunc(foo, "->(),(i,j)", dtype=(int, float), new_axes={'i': 2, 'j': 3})

    assert x.compute() == 1
    assert y.chunks == ((2,), (3,))
    assert_array_almost_equal(y.compute(), np.ones(2, 3, dtype=float))


def test_gufunc_two_inputs():
    def foo(x, y):
        return x*y

    a = da.ones(2, 3, chunks=(1, 2), dtype=int)
    b = da.ones(3, 4, chunks=(2, 3), dtype=int)

    x = da.gufunc(foo, "(i,j),(j,k)->(i,k)", dtype=int)

    assert x.chunks == ((1, 1), (3, 1))
    assert_array_almost_equal(x.compute(), np.ones(2, 4, dtype=int))


def test_gufunc_reduce_autocoredim():
    def foo(x):
        assert len(x) == 3
        return np.mean(x)

    a = da.array(np.arary([1, 2, 3]), chunks=2)

    x = da.gufunc(foo, "(i)->()", a, dtype=float)

    assert x.shape == tuple()
    assert x.compute() == 3


def test_gufunc_coredim():
    def foo(x):
        assert np.shape(x)[-1] == 3
        return x

    a = da.array(np.arary([1, 2, 3]), chunks=2)

    x = da.gufunc(foo, "(i)->(i)", a, dtype=float, coredim='i')

    assert x.shape == (3,)
    assert_array_almost_equal(x.compute(), [1, 2, 3])


def test_gufunc_many_coredim():
    def foo(x):
        assert np.shape(x)[-2] == 4
        assert np.shape(x)[-1] == 5
        return x

    a = da.ones(3, 4, 5, chunks=2)

    x = da.gufunc(foo, "(i,j,k)->(i,j,k)", a, dtype=float, coredim=('i','k'))

    assert x.shape == a.shape
    assert x.chunks == ((2, 1), (4,), (5,))
    assert_array_almost_equal(x.compute(), a.compute())
```

**Comment by shoyer** [comment]
> Why do we need to explicitly indicate the core dimension? If input arrays are such,
that a specific dimension has only one chunk, then it already could serve as indication for a core dimension.

I think it's better to be fully explicit.

There will be cases where a core dimension is supplied with multiple chunks. The right solution is either to raise an error or automatically rechunk, but certainly not to ignore it.

**Comment by magonser** [comment]
Should core dimensions always come last in the passed arrays axes order? 

What about my first question - does anyone have any thoughts on that?

**Comment by shoyer** [comment]
> Would this new "da.gufunc" do any broadcasting

It's not clear to me what you mean here. Can you give an example?

> Should core dimensions always come last in the passed arrays axes order?

This would probably simplify things. In that case, I think you could get away with a signature like
`da.gufunc(func, signature, *arrays, dtype, new_axes=None)`, though I would probably rename those last two arguments to `output_dtypes` and `output_sizes`.

**Comment by magonser** [comment]
> It's not clear to me what you mean here. Can you give an example?
Let’s say there are two input vectors of different length and their dimensions of different meaning. We want to do outer product (as simple example). The signature is `'(i,),(j,)->(i,j)'`. Are the two vectors broadcast against each other before being passed to the gufunc? 
Maybe there are some similarities in designing this to [xarray.apply_ufunc](http://xarray.pydata.org/en/stable/computation.html#wrapping-custom-computation), but probably you know that much better.

**Comment by shoyer** [comment]
> Let’s say there are two input vectors of different length and their dimensions of different meaning. We want to do outer product (as simple example). The signature is '(i,),(j,)->(i,j)'. Are the two vectors broadcast against each other before being passed to the gufunc? I.e. the first vector becomes of chunkshape (n,1) and the second (1,m) with the chunk sizes being n, respectively m of the two input vectors.

No, NumPy gufuncs don't broadcast core dimensions. They remain at the end.

Loop dimensions do get broadcast. More concretely, for `(i),(j)->(i,j)`:
- input shapes `(3,)` and `(4,)` -> output `(3, 4)`
- input shapes `(2, 3)` and `(4,)` -> broadcasts to `(2, 3)` and `(2, 4)` -> output `(2, 3, 4)`
- input shapes `()` and `(4,)` -> `ValueError` (core dimensions must be present, they don't broadcast)

**Comment by magonser** [comment]
Thanks @shoyer for explaining, somehow I didn't catch it right away. I've been reading further in various documentation and it still isn't clear to me, how a sane interface could look and be named like: 

For example there are two current proposals A) either create a new function `da.gufunc`, or B) make an alteration to `da.atop`. 

**A) Create a new function `da.gufunc`**
The former, i.e. to just call it `da.gufunc` I find slightly confusing for two reasons: 1) because there is already a `da.ufunc.ufunc`, which is a wrapper for numpy ufuncs, and also because it gets passed already arguments. I.e. how about either
`da.gufunc(func, signature, output_dtypes, output_sizes=None)(*args)`, or
`da.apply_gufunc(func, signature, *args, output_dtypes, output_sizes=None)` ?

Further, as `signature` only contains core dims, we need to pass arrays, which will broadcast against each other "naturally", as you have explained already. If this isn't the case during application, the user will have to make his own broadcast before passing the arrays. At this point some new function to make this explicit broadcasting or dimension reordering more user friendly, comes to my mind. I.e. sth. like `da.fancybroadcast(x, 'ij', y, 'jk', core_dims=None)` (where `core_dims` would be excluded from broadcast). Such function would be used to prepare input arrays for a subsequent `da.gufunc/apply_ufunc` call more easily. I understand, that despite the multiple outputs issue, such a use case is exactly covered by `xarray.apply_ufunc` already, but not in `dask`.

A simple example emphasizing on loop/core dims:
        - Elementwise multiplication: `da.apply_gufunc(lambda x, y: x*y, "(),()->()", x, y, output_dtypes=x.dtype)`
        - Dot product: `da.apply_gufunc(lambda x, y: np.sum(x*y, axis=-1), "(i),(i)->()", x, y, output_dtypes=x.dtype)`
        - Outer product: `da.apply_gufunc(lambda x, y: x*y, "(i),(j)->(ij)", *da.fancybroadcast(x, 'i', y, 'j') output_dtypes=x.dtype)`

Benefit of this proposal is, that if `func` should be vectorized, the same `signature` can be used for `np.vectorize`. Drawback is IMHO, that accomplishing something like `xarray.apply_ufunc` still requires additional code (as proposed by sth like `da.fancybroadcast`).

**B) Make an alteration to `da.atop`**
For the proposal of modifying `da.atop` (this issues title) for multiple outputs (and the whole ideas about loop dims and core dims), we should keep in mind, that while `da.atop` signature can be used to change dimension order, the respective transpose of the underlying block arrays have to be done inside `func`. Also no broadcasting of the array in the blocks is done. E.g. one example of `da.atop` is `z = atop(np.transpose, 'ji', x, 'ij', dtype=x.dtype)`. As an dask user this confuses me (or I still miss something). Therefore wouldn't it be better to have a function, which has the signature

`da.somenewname(func, output_inds, *args, output_dtypes, input_core_dims=None, output_core_dims=None)` ?
    - `*args` is same structure as in `da.atop`, i.e. alternating between the input argument and the indices
    - It is to be determined, which argument specifies the amount of outputs; is it `output_inds`, `output_dtypes`, or even an extra `num_outputs` argument?
    - This new function would also perform necessary broadcast and transposition on the input arguments inside the actual blocks before calling `func`
    - If some input argument has a core dim, which is not last, it could be transposed to last position, similar as in `array.apply_ufunc` or an exception could be raised.
    
Benefit of this proposal is IMHO, that calling it is simpler compared to B), because explicit broadcasting or dimension reorderding for input arguments is not separated as in proposal A).

**Comment by jakirkham** [comment]
Is this still relevant?

**Comment by magonser** [comment]
From my side it could be closed, as `apply_gufunc` can be used.
