### ISSUE TITLE
Dask Dataframe fails to run the computation graph with pandas 1.2.0 & fastparquet

### ISSUE THREAD

**Issue by alpha-rafa** [dask/dask#7020]
**What happened**: compute on dask dataframe fails when using pandas 1.2.0. When downgrading to 1.0.1 it works

**What you expected to happen**: pandas 1.2.0 should work exactly as 1.0 release

**Minimal Complete Verifiable Example**:

ddf = dd.from_pandas(my_df, npartitions=20)
ddf.compute()

```python
'DataFrame' object has no attribute '_data'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
---> 30             ddf.compute()
     31 

/opt/conda/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    278         """
--> 279         (result,) = compute(self, traverse=False, **kwargs)
    280         return result

/opt/conda/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    566 
--> 567     results = schedule(dsk, keys, **kwargs)
    568     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

/opt/conda/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2675             try:
-> 2676                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2677             finally:

/opt/conda/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1984                 local_worker = None
-> 1985             return self.sync(
   1986                 self._gather,

/opt/conda/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    830         else:
--> 831             return sync(
    832                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs

/opt/conda/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:

/opt/conda/lib/python3.8/site-packages/distributed/utils.py in f()
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:

/opt/conda/lib/python3.8/site-packages/tornado/gen.py in run(self)
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:

/opt/conda/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1849                         else:
-> 1850                             raise exception.with_traceback(traceback)
   1851                         raise exc

/opt/conda/lib/python3.8/site-packages/dask/optimization.py in __call__()
    962             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 963         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    964 

/opt/conda/lib/python3.8/site-packages/dask/core.py in get()
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result

/opt/conda/lib/python3.8/site-packages/dask/core.py in _execute_task()
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in <genexpr>()
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in _execute_task()
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in <genexpr>()
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in _execute_task()
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in <listcomp>()
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):

/opt/conda/lib/python3.8/site-packages/dask/core.py in _execute_task()
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__()
   2772         float64       40000
-> 2773         complex128    80000
   2774         object        40000

/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__()
   5269 
-> 5270         # Check weights for compliance
   5271         if weights is not None:

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__get__()

/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__()
   5269 
-> 5270         # Check weights for compliance
   5271         if weights is not None:

AttributeError: 'DataFrame' object has no attribute '_data'
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2020.12
- Python version: 3.8.5
- Operating System:
- Install method (conda, pip, source):

**Comment by TomAugspurger** [comment]
@alpha-rafa do you have a fully reproducible example, and can you ensure that pandas 1.2.0 is installed correctly? It *should* still have a `_data` attribute

```python

In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '1.2.0rc0'

In [3]: df = pd.DataFrame({"A": [1, 2]})

In [4]: df._data
Out[4]:
BlockManager
Items: Index(['A'], dtype='object')
Axis 1: RangeIndex(start=0, stop=2, step=1)
IntBlock: slice(0, 1, 1), 1 x 2, dtype: int64
```

**Comment by alpha-rafa** [comment]
thanks for the response here is the code. It seems fastparquet package may be the one causing the issue


```
def test_func(row):
    return "{}".format(row['A'])

client = Client(DASK_SCHEDULER)
df = pd.DataFrame({"A": [1, 2, 3, 4, 5]})
ddf = dd.from_pandas(df, npartitions=8)
ddf['output'] = ddf.apply(test_func, axis=1, meta="object")
df = ddf.compute()
print(df)
client.close()

```


Happens on the jupyter notebook instance that comes with Dask with the following packages installed

env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray fastparquet dask[complete] textdistance[extras] cloudpickle pymongo pendulum scikit-learn tslearn -c conda-forge -y
    - name: EXTRA_PIP_PACKAGES
      value: fastparquet prefect




here are the packages on the instance of jupyter:

=======================
aiohttp                       3.7.3
alembic                       1.4.3
argon2-cffi                   20.1.0
async-generator               1.10
async-timeout                 3.0.1
attrs                         20.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
bleach                        3.2.1
blinker                       1.4
blosc                         1.9.2
bokeh                         2.2.3
brotlipy                      0.7.0
cachetools                    4.2.0
certifi                       2020.12.5
certipy                       0.1.3
cffi                          1.14.3
chardet                       3.0.4
click                         7.1.2
cloudpickle                   1.6.0
conda                         4.8.3
conda-package-handling        1.6.1
croniter                      0.3.36
cryptography                  3.1.1
cytoolz                       0.11.0
dask                          2020.12.0
dask-labextension             3.0.0
decorator                     4.4.2
defusedxml                    0.6.0
distributed                   2020.12.0
docker                        4.4.1
entrypoints                   0.3
fastparquet                   0.5.0
fsspec                        0.8.4
google-api-core               1.24.1
google-auth                   1.24.0
google-cloud-core             1.5.0
google-cloud-storage          1.35.0
google-crc32c                 1.1.0
google-resumable-media        1.2.0
googleapis-common-protos      1.52.0
graphviz                      0.15
HeapDict                      1.0.1
idna                          2.10
importlib-metadata            2.0.0
importlib-resources           4.1.1
ipykernel                     5.3.4
ipython                       7.18.1
ipython-genutils              0.2.0
ipywidgets                    7.5.1
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        1.0.0
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.6.3
jupyter-server-proxy          1.5.0
jupyter-telemetry             0.0.5
jupyterhub                    1.1.0
jupyterlab                    2.2.5
jupyterlab-pygments           0.1.1
jupyterlab-server             1.2.0
llvmlite                      0.35.0
locket                        0.2.0
lz4                           3.1.1
Mako                          1.1.3
MarkupSafe                    1.1.1
marshmallow                   3.10.0
marshmallow-oneofschema       2.1.0
mistune                       0.8.4
msgpack                       1.0.1
multidict                     4.7.5
mypy-extensions               0.4.3
natsort                       7.1.0
nbclient                      0.5.0
nbconvert                     6.0.6
nbformat                      5.0.7
nest-asyncio                  1.4.0
notebook                      6.1.3
numba                         0.52.0
numpy                         1.18.1
oauthlib                      3.0.1
olefile                       0.46
packaging                     20.4
pamela                        1.0.0
pandas                        1.2.0
pandocfilters                 1.4.2
parso                         0.7.1
partd                         1.1.0
pendulum                      2.1.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.0.1
pip                           20.2.3
prefect                       0.14.1
prometheus-client             0.8.0
prompt-toolkit                3.0.7
protobuf                      3.14.0
psutil                        5.7.3
ptyprocess                    0.6.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycosat                       0.6.3
pycparser                     2.20
pycurl                        7.43.0.5
Pygments                      2.7.1
PyJWT                         1.7.1
pymongo                       3.11.0
pyOpenSSL                     19.1.0
pyparsing                     2.4.7
pyrsistent                    0.17.3
PySocks                       1.7.1
python-box                    5.2.0
python-dateutil               2.8.1
python-editor                 1.0.4
python-json-logger            0.1.11
python-slugify                4.0.1
pytz                          2020.4
pytzdata                      2020.1
PyYAML                        5.3.1
pyzmq                         19.0.2
requests                      2.24.0
rsa                           4.6
ruamel-yaml-conda             0.15.80
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
scikit-learn                  0.24.0
scipy                         1.5.3
Send2Trash                    1.5.0
setuptools                    49.6.0.post20200917
simpervisor                   0.3
six                           1.15.0
sortedcontainers              2.3.0
SQLAlchemy                    1.3.19
tabulate                      0.8.7
tblib                         1.6.0
terminado                     0.9.1
testpath                      0.4.4
text-unidecode                1.3
textdistance                  4.2.0
threadpoolctl                 2.1.0
thrift                        0.11.0
toml                          0.10.2
toolz                         0.11.1
tornado                       6.0.4
tqdm                          4.49.0
traitlets                     5.0.4
tslearn                       0.4.1
typing-extensions             3.7.4.3
urllib3                       1.25.10
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.57.0
wheel                         0.35.1
widgetsnbextension            3.5.1
xarray                        0.16.2
yarl                          1.6.3
zict                          2.0.0
zipp                          3.2.0
==================================

**Comment by jsignell** [comment]
I cannot reproduce with pandas 1.2.0 and fastparquet 0.5.0. It does seem odd that you are installing fastparquet both in your conda  install script and your pip install script. So I'd check that your environment is being set up properly.

**Comment by alpha-rafa** [comment]
Closing it
