### ISSUE TITLE
dask groupby does not respect observed argument

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#7024]
**What happened**:

It seems that Dask inherits Pandas memory efficiency regression introduced by default value of `observed` set to `False` in `groupby` function. This is causing queries that previously run successfully, now to crash with out of memory error. Yet Dask does not seem to respect this new argument set to `True` which is used to deal with this memory efficiency regression.
As a result Dask is not able to do a groupby aggregation call on 0.5 GB csv data using 125 GB machine (250 times more than csv data size).

**What you expected to happen**:

Ideally use `observed=True` by default. If not, then at least respect this argument provided explicitly.

**Minimal Complete Verifiable Example**:

```sh
cat > data.csv <<EOL
id1,id2,v1
a,x,4.5
b,y,5.5
EOL
python
```
```py
import pandas as pd
import dask
import dask.dataframe as dd

pd.__version__
#'1.1.5'
dask.__version__
#'2020.12.0'

pf = pd.read_csv("data.csv", dtype={"id1":"category", "id2":"category", "v1":"Float64"})
df = dd.from_pandas(pf, 1, sort=False)

pa = pf.groupby(['id1','id2'], dropna=False, as_index=False, observed=True).agg({'v1':'sum'})
da = df.groupby(['id1','id2'], dropna=False, observed=True).agg({'v1':'sum'}).compute()
da.reset_index(inplace=True)

pa
#  id1 id2   v1
#0   a   x  4.5
#1   b   y  5.5
da
#  id1 id2   v1
#0   a   x  4.5
#1   a   y  0.0
#2   b   x  0.0
#3   b   y  5.5
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.6
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
I think this is fixed by #6992
