### ISSUE TITLE
Confusing behavior when applying differentiate operation to chunked dataset 

### ISSUE THREAD

**Issue by guidocioni** [dask/dask#7025]
**What happened**:
Dask is raising `ValueError: Chunk size must be larger than edge_order + 1. Minimum chunk for axis 0 is 1. Rechunk to proceed.`

**What you expected to happen**:
Dask should apply `differentiate` along the `time` axis given that the chunk size on this axis is > 1

**Minimal Complete Verifiable Example**:
If `dset` is my original dataset with chunks already applied as `{"time": 2, "lat": 100, "lon":100}`

```python
rain_acc = dset['RAIN_GSP'] + dset['RAIN_CON']
```

this produces, as expected

```python
<xarray.DataArray (time: 93, lat: 657, lon: 1097)>
dask.array<rechunk-merge, shape=(93, 657, 1097), dtype=float32, chunksize=(2, 100, 100), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2021-01-04 2021-01-04T01:00:00 ... 2021-01-09
  * lon      (lon) float64 -23.5 -23.44 -23.38 -23.31 ... 44.81 44.88 44.94 45.0
  * lat      (lat) float64 29.5 29.56 29.62 29.69 ... 70.31 70.38 70.44 70.5
    crs      object Projection: latitude_longitude
```

However when I try to do 

```python
rain = rain_acc.differentiate(coord="time", datetime_unit="h")
```
I get the `ValueError` raised. As far as I can see, `differentiate` should already use the chunks that I defined, so `time = 2`, that's why I don't get the error.
The only workaround that I have right now is to do a `.load()` before calling differentiate, which of course is not advisable. 

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.6
- Operating System: Ubuntu 
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
I think what you are experiencing is that since your data doesn't evenly divide into your chunksize you have some chunks that are smaller than you expect. You can confirm this by checking `rain_acc.chunks` 

For instance look at:

```python
import xarray as xr
ds = xr.tutorial.open_dataset("air_temperature", chunks={"time": 973, "lon": 20, "lat": 12})
ds.air.chunks
# ((973, 973, 973, 1), (12, 12, 1), (20, 20, 13))

# error is thrown when you do
ds.air.differentiate(coord="time", datetime_unit="h")
```
So in the meantime you can rechunk and choose chunksize that doesn't give you any chunks of size 1. 

For a fix we could implement some rechunking when this situation is encountered. We recently added something similar for the array overlap case: 

https://github.com/dask/dask/blob/76a4f536237a5e65e03ba471f004226056646b65/dask/array/overlap.py#L421

so that logic could probably be extended.

**Comment by mrocklin** [comment]
Yes, I think that this should be raised in the Xarray project issue
tracker.  I think that automatic rechunking is probably the right thing to
do here.  I recommend that we close this here.

**Comment by guidocioni** [comment]
I suspected the error was related to this but I could not understand why...that makes sense!

I agree some automatic rechunking should take place when calling `.differentiate( )`; the average user would be quite confused if he/she just load the dataset, apply the operation and get the error.

**Comment by jsignell** [comment]
Are you interested in adding the automatic rechunk logic for this case @guidocioni?

**Comment by guidocioni** [comment]
Hey @jsignell, even though I'd like to contribute unfortunately I don't think I have the necessary skill :)

**Comment by douglasdavis** [comment]
Closing here based on the recommendation that automatic rechunking can be implemented on the Xarray side
