### ISSUE TITLE
diagnostic.visualize : pass 'inline' argument to bokeh output_file function

### ISSUE THREAD

**Issue by patquem** [dask/dask#7034]
Hello,

When working in a machine that has no connexion to internet, 'inline' mode option passed to bp.outpufile(filename, mode=...) in diagnostic.visualize would be nice.
(This option allows to directly put the javascript required for results interpretation inside the html file).

Could you please add a such option in the next release ?

Thanks

**Comment by quasiben** [comment]
This seems like a reasonable feature request,  not sure who has time to work on this.  If you do, you are more than welcome (and encouraged) to submit a PR.  You can find the relevant code here:
https://github.com/dask/dask/blob/dcf3c3a1ee5f7bdaa1f45701fca6a7502d3ccb20/dask/diagnostics/profile_visualize.py#L186

**Comment by patquem** [comment]
Hello @quasiben,
I have no experience in GitHub (I work in PyCharm with a private SVN repository), but **this** could be a good opportunity for me to see how it works.
I have start to read the Dask contributers notes and as written in the linked panda doc, indeed:
_To the new user, working with Git is one of the more daunting aspects of contributing_
 :)
I can't promise you anything, but I am really motivated to understand how contributors work in github.
see you,
Patrick

**Comment by jsignell** [comment]
Closed by #7075
