### ISSUE TITLE
Python crashes with xarray.apply_ufunc() in some specific case without any comment

### ISSUE THREAD

**Issue by patquem** [dask/dask#7045]
Hello,

I am faced to a strange behaviour (python crash) when launching the example below.

This example adresses array transformation performed either by Eucliean or PiecewiseAfine transform from scikit-image.

With array of shape > (1000, 1000), here is a sum up of what I have oberved:
Euclidean transform (mode 1):
-> x_transf.compute(scheduler='single-threaded') : OK
->  x_transf.compute() : OK
PiecewiseAfine transform (mode 2):
-> x_transf.compute(scheduler='single-threaded') : OK
-> x_transf.compute() : **NOK - python crashes**

Hope you can reproduce the same behaviour and find explanations about what is wrong.
Thanks.

Patrick

```
import numpy as np
import xarray as xr
from skimage.transform import EuclideanTransform, PiecewiseAffineTransform, warp
import matplotlib.pyplot as plt

x = xr.DataArray(np.random.random((1000, 1000, 10)), dims=["x", "y", "z"])
x = x.chunk(chunks={"z": 1})

def transf(img, mode):
    tx = 1
    ty = 2
    if mode == 1:
        tform = EuclideanTransform(translation=np.array([tx, ty]))
    elif mode == 2:
        xmin, xmax = -img.shape[1], 2 * img.shape[1]
        ymin, ymax = -img.shape[0], 2 * img.shape[0]
        src = [[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax]]
        dst = [[x[0] + tx, x[1] + ty] for x in src]
        tform = PiecewiseAffineTransform()
        tform.estimate(np.asarray(src), np.asarray(dst))
    else:
        raise IOError("incorrect value for 'mode'")
    return warp(img, tform)

def fun(x, mode=None):
    img = x.squeeze()
    img_transf = transf(img, mode)
    return np.reshape(img_transf, (1,) + img_transf.shape)

kwargs = {"mode": 2}
x_transf = xr.apply_ufunc(fun, x,
                          input_core_dims=[['x', 'y']],
                          output_core_dims=[['x', 'y']],
                          dask="parallelized",
                          output_dtypes=[float],
                          kwargs=kwargs)

x_transf.compute()
# x_transf.compute(scheduler='single-threaded')
```

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.7.7
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
Thank you for the excellent reproducible example.  Unfortunately it ran without issue for me.

<details>

```python
In [1]: import numpy as np
   ...: import xarray as xr
   ...: from skimage.transform import EuclideanTransform, PiecewiseAffineTransform, warp
   ...: import matplotlib.pyplot as plt
   ...: 
   ...: x = xr.DataArray(np.random.random((1000, 1000, 10)), dims=["x", "y", "z"])
   ...: x = x.chunk(chunks={"z": 1})
   ...: 
   ...: def transf(img, mode):
   ...:     tx = 1
   ...:     ty = 2
   ...:     if mode == 1:
   ...:         tform = EuclideanTransform(translation=np.array([tx, ty]))
   ...:     elif mode == 2:
   ...:         xmin, xmax = -img.shape[1], 2 * img.shape[1]
   ...:         ymin, ymax = -img.shape[0], 2 * img.shape[0]
   ...:         src = [[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax]]
   ...:         dst = [[x[0] + tx, x[1] + ty] for x in src]
   ...:         tform = PiecewiseAffineTransform()
   ...:         tform.estimate(np.asarray(src), np.asarray(dst))
   ...:     else:
   ...:         raise IOError("incorrect value for 'mode'")
   ...:     return warp(img, tform)
   ...: 
   ...: def fun(x, mode=None):
   ...:     img = x.squeeze()
   ...:     img_transf = transf(img, mode)
   ...:     return np.reshape(img_transf, (1,) + img_transf.shape)
   ...: 
   ...: kwargs = {"mode": 2}
   ...: x_transf = xr.apply_ufunc(fun, x,
   ...:                           input_core_dims=[['x', 'y']],
   ...:                           output_core_dims=[['x', 'y']],
   ...:                           dask="parallelized",
   ...:                           output_dtypes=[float],
   ...:                           kwargs=kwargs)
   ...: 
   ...: x_transf.compute()
Out[1]: 
<xarray.DataArray (z: 10, x: 1000, y: 1000)>
array([[[0.42907156, 0.65652228, 0.09130647, ..., 0.9256608 ,
         0.34838353, 0.        ],
        [0.99015214, 0.19786834, 0.46550213, ..., 0.02218359,
         0.4054686 , 0.        ],
        [0.84568795, 0.17853499, 0.38270076, ..., 0.50083405,
         0.70506655, 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.61161056,
         0.62991212, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.34506056, 0.09773457, 0.88718541, ..., 0.28893585,
         0.88959313, 0.        ],
        [0.42093465, 0.87775369, 0.00972713, ..., 0.63305971,
         0.8897838 , 0.        ],
        [0.19875504, 0.15475013, 0.50424987, ..., 0.91989679,
         0.53857741, 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.30139667,
         0.43245742, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.16291017, 0.51703485, 0.4673711 , ..., 0.78735301,
         0.48894569, 0.        ],
        [0.57931974, 0.22875778, 0.16287981, ..., 0.94836358,
         0.89271111, 0.        ],
        [0.54271036, 0.42041852, 0.07539497, ..., 0.12393385,
         0.7236843 , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.80362994,
         0.90308255, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Dimensions without coordinates: z, x, y
```

</details>

My first guess though is that this particular scikit-image function is not threadsafe.  It might be worth including one of the scikit-image maintainers in this thread.

**Comment by patquem** [comment]
Thank you mrocklin for your feeback.

Indeed, a scikit-image maintainers in this thread will be welcome.

I run with scikit-image v0.17.2.

Personally, when working with last release (v0.18.1), import fails (missing .DLL) :
![image](https://user-images.githubusercontent.com/16154687/104033513-e6f79f00-51cf-11eb-80f1-67d2343e354e.png)
issue reported in : https://github.com/scikit-image/scikit-image/issues/4780 (still opened)

And when trying to install v0.18.0 :
![image](https://user-images.githubusercontent.com/16154687/104033741-3a69ed00-51d0-11eb-9d2a-f6479f2e1aef.png)

not lucky :(
Patrick

**Comment by mrocklin** [comment]
cc @jni in case you know of threading issues on windows with these operations, or might know someone who does.

**Comment by hmaarrfk** [comment]
Can you provide the output of
```
pip list
```
and if applicable
```
conda list
```

**Comment by hmaarrfk** [comment]
is mode2 the only one causing issues? what about mode 1 and mode3 ? I think mode 2 is not very well supported.

**Comment by jni** [comment]
@hmaarrfk I think you're misreading the question. `mode` is not the interpolation order, it is an internal argument to the reproducible example. In this case, mode=1 means defining a EuclideanTransform, while mode=2 involves *estimating* a PiecewiseAffineTransform, see:

```python
def transf(img, mode):
    tx = 1
    ty = 2
    if mode == 1:
        tform = EuclideanTransform(translation=np.array([tx, ty]))
    elif mode == 2:
        xmin, xmax = -img.shape[1], 2 * img.shape[1]
        ymin, ymax = -img.shape[0], 2 * img.shape[0]
        src = [[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax]]
        dst = [[x[0] + tx, x[1] + ty] for x in src]
        tform = PiecewiseAffineTransform()
        tform.estimate(np.asarray(src), np.asarray(dst))
    else:
        raise IOError("incorrect value for 'mode'")
    return warp(img, tform)
```

The source code for `warp` is [here](https://github.com/scikit-image/scikit-image/blob/v0.18.x/skimage/transform/_warps.py#L684-L932).

The key difference in the code path is [here](https://github.com/scikit-image/scikit-image/blob/3fb1cc228769229cfeb810270b9d19ac525ded3e/skimage/transform/_warps.py#L873):

```python
        if matrix is not None:
```

The block will get executed in the case of EuclideanTransform but not PiecewiseAffineTransform.

Now the interesting thing is that, for the piecewise affine, we'll instead go to [this block](https://github.com/scikit-image/scikit-image/blob/3fb1cc228769229cfeb810270b9d19ac525ded3e/skimage/transform/_warps.py#L889-L928), which, as far as I can tell, then only uses pure NumPy operations and then calls `scipy.ndimage.map_coordinates`. So it might not be our warp code that is not threadsafe, but the ndimage code.

So, assuming I haven't made any mistakes following the code, I think that it is `map_coordinates` that is not thread safe. I wonder whether @grlee77 has any further ideas...

**Comment by hmaarrfk** [comment]
right,. i'm curious too see the rest of the pip installed applications so we can recreate an env.

Thanks for the explination and digging.

**Comment by grlee77** [comment]
I also couldn't reproduce the failure for the example provided. 

I don't think `map_coordinates` is too likely to be the problem. Although it is not specifically `map_coordinates`, `dask-image` has used `ndimage.affine_transform` with a multi-threaded scheduler without issues (see PR dask/dask-image#159). It also wraps many other ndimage filtering and morphology operations and I don't think any thread-safety issues have been encountered.

**Comment by patquem** [comment]
Hello everyone,

First of all, thank you all for your previous messages.
I note you do not reproduce the issue from your side.
concerning hmaarrfk  's request, I fear my python env list is a little bit too big to reproduce exactly the same one, nevermind, just pick up in the list below what is necessary for.

Tell me if I can do something to help.

Thanks again,
Patrick


Package                       Version               
----------------------------- -----------           
affine                        2.3.0                 
alabaster                     0.7.12                
apptools                      4.5.0                 
asteval                       0.9.18                
astroid                       2.4.2                 
attrs                         19.3.0                
Babel                         2.8.0                 
backcall                      0.2.0                 
bcrypt                        3.2.0                 
bleach                        3.1.5                 
bokeh                         2.2.3                 
certifi                       2020.6.20             
cffi                          1.14.0                
chardet                       3.0.4                 
clglic                        0                     
click                         7.1.2                 
click-plugins                 1.1.1                 
cligj                         0.7.1                 
cloudpickle                   1.6.0                 
colorama                      0.4.3                 
configobj                     5.0.6                 
contextlib2                   0.6.0.post1           
coverage                      5.2                   
cryptography                  2.9.2                 
cycler                        0.10.0                
Cython                        0.29.21               
dask                          2020.12.0             
dask-image                    0.4.0                 
decorator                     4.4.2                 
defusedxml                    0.6.0                 
descartes                     1.1.0                 
dill                          0.3.2                 
distributed                   2020.12.0             
docopt                        0.6.2                 
docutils                      0.16                  
entrypoints                   0.3                   
envisage                      4.9.2                 
fabio                         0.10.2                
fisx                          1.1.8                 
future                        0.18.2                
GDAL                          3.1.4                 
h5py                          2.10.0
HeapDict                      1.0.1
hyperspy                      1.6.1
hyperspy-gui-ipywidgets       1.2
hyperspy-gui-traitsui         1.2
idna                          2.10
imageio                       2.9.0
imagesize                     1.2.0
importlib-metadata            1.7.0
ipykernel                     5.3.3
ipyparallel                   6.3.0
ipython                       7.16.1
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isort                         4.3.21
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        0.16.0
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.6
jupyter-console               6.1.0
jupyter-core                  4.6.3
kiwisolver                    1.2.0
latexcodec                    2.0.1
lazy-object-proxy             1.4.3
libtiff                       0.4.2
link-traits                   1.0.3
llvmlite                      0.33.0
lmfit                         1.0.1
MarkupSafe                    1.1.1
matplotlib                    3.3.0
mayavi                        4.7.1+vtk82
mccabe                        0.6.1
mistune                       0.8.4
modopt                        1.4.4
mpi4py                        3.0.3
mpmath                        1.1.0
msgpack                       1.0.2
nanoscope                     1.200.1b55
natsort                       7.0.1
nbconvert                     5.6.1
nbformat                      5.0.7
networkx                      2.4
nibabel                       3.1.1
notebook                      6.0.3
numba                         0.50.1
numdifftools                  0.9.39
numexpr                       2.7.1
numpy                         1.19.0+mkl
opencv-python                 4.3.0.36
oset                          0.1.3
packaging                     20.4
pandas                        1.0.5
pandocfilters                 1.4.2
paramiko                      2.7.2
parse                         1.15.0
parso                         0.7.0
patsy                         0.5.1
pep8                          1.7.1
pickleshare                   0.7.5
Pillow                        7.2.0
PIMS                          0.5
Pint                          0.14
pip                           20.3.3
pip-licenses                  3.0.0
pipreqs                       0.4.10
prettytable                   2.0.0
progressbar2                  3.51.4
prometheus-client             0.8.0
prompt-toolkit                3.0.5
psutil                        5.8.0
PTable                        0.9.2
pybtex                        0.22.2
pybtex-docutils               0.2.2
pycodestyle                   2.6.0
pycparser                     2.20
pydot                         1.4.1
pyface                        7.0.1
pyFAI                         0.19.0
Pygments                      2.6.1
pyleti                        4976
pylint                        2.5.3
PyMca5                        5.5.5
PyNaCl                        1.4.0
pynput                        1.6.8
pynufft                       2020.1.0
pyparsing                     2.4.7
pyrsistent                    0.16.0
PySide2                       5.15.0
python-dateutil               2.8.1
python-utils                  2.4.0
pytz                          2020.1
PyVISA                        1.10.1
PyWavelets                    1.1.1
pywin32                       228
pywinpty                      0.5.7
PyYAML                        5.3.1
pyzmq                         19.0.1
qtconsole                     4.7.5
QtPy                          1.9.0
rasterio                      1.1.8
requests                      2.24.0
scikit-fmm                    2019.1.30
scikit-image                  0.17.2
scikit-learn                  0.23.1
scipy                         1.5.1
Send2Trash                    1.5.0
setuptools                    47.2.0
Shapely                       1.7.0
shiboken2                     5.15.0
silx                          0.13.0
sip                           5.3.0
six                           1.15.0
slicerator                    1.0.0
snowballstemmer               2.0.0
snuggs                        1.4.7
sortedcontainers              2.3.0
sparse                        0.10.0
Sphinx                        3.1.2
sphinx-autodoc-annotation     1.0.post1
sphinx-rtd-theme              0.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-autoprogram     0.1.5
sphinxcontrib-bibtex          1.0.0
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-plantuml        0.18
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
statsmodels                   0.11.1
sympy                         1.6.1
tables                        3.6.1
tblib                         1.7.0
terminado                     0.8.3
testpath                      0.4.4
threadpoolctl                 2.1.0
tifffile                      2020.7.17
toml                          0.10.1
tomopy                        1.4.1
toolz                         0.10.0
tornado                       6.0.4
tqdm                          4.48.0
traitlets                     4.3.3
traits                        6.1.0
traitsui                      7.0.1
typed-ast                     1.4.1
typing-extensions             3.7.4.3
uncertainties                 3.1.4
urllib3                       1.25.9
visa                          1.0.0
vtk                           8.1.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.34.2
widgetsnbextension            3.5.1
wrapt                         1.12.1
x86cpu                        0.4
xarray                        0.16.1
xlrd                          1.2.0
xmlrunner                     1.7.7
xrayutilities                 1.6.0
yarg                          0.1.9
zict                          2.0.0
zipp                          3.1.0

**Comment by patquem** [comment]
Hi @hmaarrfk @grlee77 @jni ,
Thank you all for watching my issue. 
Since I am the only one to produce the python crash I propose to close the issue.
FYI, as a new Dask contributor, I have generated a new and shortest python env  that doesn't reproduce the issue. Not sure you have to spend/lose time on it.
See you next
Patrick
