### ISSUE TITLE
sparse test_basic's mean fails on the upstream

### ISSUE THREAD

**Issue by ravwojdyla** [dask/dask#7051]
This error comes up as part of the Upstream CI, see the link below. Afaiu the failure comes from the:

```
pytest.param(lambda x: x.mean(), marks=numpy_120_xfail),
```

case of the 
https://github.com/dask/dask/blob/2d7a3dfdf71d0bf3e9b512b20823131ed325e57b/dask/array/tests/test_sparse.py#L77

And to be clear this case fails on the upstream version but no the latest release of sparse. We might need to track down the change in sparse and potentially fix that up or add xfail marker.

**Environment**:

https://github.com/dask/dask/runs/1674320752 (example, but the previous builds also fail for this case).

**Comment by jsignell** [comment]
Just for reference, I have been trying to fix all the upstream failures in #6896. The `lambda x: x.std()` has been proving very tricky though. Something is going wrong with the `fill_value` for `x.var()`

**Comment by jsignell** [comment]
Ok it won't be fixed by #6896 after all, but I think the conversation in https://github.com/dask/dask/issues/7169 is on the right track. Closing this in favor of that one.
