### ISSUE TITLE
linalg.lstsq incorrect for complex input

### ISSUE THREAD

**Issue by jcmgray** [dask/dask#7053]
**What happened**:

``da.linalg.lstsq`` doesn't produce the correct output for complex inputs, due to e.g. non conjugated transpose in the implementation.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da

A = da.random.random(size=(3, 3)) + 1j * da.random.random(size=(3, 3))
b = da.random.random(size=(3, 1)) + 1j * da.random.random(size=(3, 1))

x, residuals, rank, s = da.linalg.lstsq(A, b)

((A @ x) - b).compute()
# entries far from zero
```

**Anything else we need to know?**:

* If this line

https://github.com/dask/dask/blob/f9649b45abda9332618938d0c2cb2ea5a3db0d56/dask/array/linalg.py#L1396

 is changed to ``x = solve_triangular(r, q.T.conj().dot(b))``, then the returned vector ``x`` is corrected.

* If this line
https://github.com/dask/dask/blob/f9649b45abda9332618938d0c2cb2ea5a3db0d56/dask/array/linalg.py#L1398

is changed to ``residuals = abs(residuals ** 2).sum(...`` then the residuals are fixed, 

* if this line:
https://github.com/dask/dask/blob/f9649b45abda9332618938d0c2cb2ea5a3db0d56/dask/array/linalg.py#L1413

is changed to  ``r.T.conj()`` then the singular values, ``s`` are corrected. One might also want to cast them to the equivalent real type, which would match the ``numpy`` convention.

**Environment**:

- Dask version: 2020.12
- Python version: 3.8
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by gforsyth** [comment]
Thanks for reporting this @jcmgray -- would you be interested in putting in a PR with these changes?

**Comment by jcmgray** [comment]
I can. My only question is I don't understand why the singular values aren't already cast to the real equivalent dtype, since the current implementation seems to run a small ``numpy`` example to get the dtype: 

https://github.com/dask/dask/blob/f9649b45abda9332618938d0c2cb2ea5a3db0d56/dask/array/linalg.py#L1420-L1427 

In other words, how does ``s`` end up complex here when ``ss`` is always real?

**Comment by gforsyth** [comment]
> In other words, how does `s` end up complex here when `ss` is always real?

that's... a very good question.

If I make the changes you suggested and use your example, then when I look at the repr of `s` it indicates that the dtype is `float64` (which seems correct):

```
In [10]: s
Out[10]: dask.array<lstsq-singular, shape=(3,), dtype=float64, chunksize=(3,), chunktype=numpy.ndarray>
```

but yeah, when I `compute` it has some (very tiny) imaginary part

```
In [11]: s.compute()
Out[11]: 
array([2.10699056+5.18868704e-17j, 0.77703314+3.32453067e-17j,
       0.16518369-6.20991144e-17j])
```

**Comment by jcmgray** [comment]
Ah I think the answer might be that ``np.linalg.eigvals`` rather than ``np.linalg.eigvalsh`` is called in the graph on ``r.T.conj() @ r``.

**Comment by jcmgray** [comment]
What are the requirements on the array supplied to ``meta_from_array`` here? Using ``r`` throws a ``numpy.ComplexWarning: Casting complex values to real discards the imaginary part`` that fails the tests with complex inputs.

**Comment by jcmgray** [comment]
PR submitted, I've just used 
```python
    meta = meta_from_array(residuals, 1, dtype=ss.dtype) 
    s = Array(graph, sname, shape=(r.shape[0],), chunks=r.shape[0], meta=meta) 
```
for the moment. ``residuals`` should have the correct type already so possibly ``ss`` is not needed at all? I only hesitate with changing this stuff as not familiar with how the computational graph stuff works.

**Comment by gforsyth** [comment]
> `residuals` should have the correct type already so possibly `ss` is not needed at all? I only hesitate with changing this stuff as not familiar with how the computational graph stuff works.

That should be fine -- `meta` is an array-like with no elements and the correct dtype, so if `residuals` has the correct output type for `s` then it should be good to use that.
