### ISSUE TITLE
Implement reservoir sampling for Bag

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7068]
Most bag operations actually support out-of-memory partitions.  For sampling, this is not currently the case. To support out-of-memory sampling, we should probably implement [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling).

As suggested in https://github.com/dask/dask/pull/7027#discussion_r557476829

**Comment by Turtle24** [comment]
Hi @jsignell this sounds quite interesting. Admittedly I've only had a chance to gloss over it before class but I'd like to take it up. Any pointers beyond the content in #7027 ?

**Comment by jsignell** [comment]
Hi @Turtle24, I don't have any pointers :) but you shouldn't need to know much about dask. Feel free to open a pull request even with some work in progress code and probably someone will be able to take a look.
