### ISSUE TITLE
ERROR collecting dask/dataframe/tests/test_rolling.py

### ISSUE THREAD

**Issue by patquem** [dask/dask#7072]
Hello,

I try to do my first step as a dask contributor :)
After cloning and installing usual packages, when I execute _py.test dask --verbose_ (to be sure all tests correctly run), all tests pass except 1 related to test_rolling.py
Is it a known error ? 
Thanks,
Patrick

![image](https://user-images.githubusercontent.com/16154687/104718624-73074a80-572b-11eb-8e9b-a9c85996b0e6.png)

**Comment by jsignell** [comment]
Thanks yeah that is known. It's related to the pandas version and is fixed by #6996
