### ISSUE TITLE
sparse.SpareArray doesn't exist.

### ISSUE THREAD

**Issue by detrout** [dask/dask#7078]
Hello

I was trying to update the Debian dask & distributed packages and ran into a unit test failure triggered by distributed's tests, though it looked like the ultimate problem is in dask.

There were several errors that all ended in the same "E   AttributeError: module 'sparse' has no attribute 'SparseArray'"

```
___________________ ERROR collecting tests/test_variable.py ____________________
/usr/lib/python3/dist-packages/distributed/tests/test_variable.py:13: in <module>
    from distributed.utils_test import gen_cluster, inc, div
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
/usr/lib/python3/dist-packages/distributed/utils_test.py:67: in <module>
    import dask.array  # register config
/usr/lib/python3/dist-packages/dask/array/__init__.py:2: in <module>
    from .blockwise import blockwise, atop
/usr/lib/python3/dist-packages/dask/array/blockwise.py:259: in <module>
    from .core import new_da_object
/usr/lib/python3/dist-packages/dask/array/core.py:63: in <module>
    from .chunk_types import is_valid_array_chunk, is_valid_chunk_type
/usr/lib/python3/dist-packages/dask/array/chunk_types.py:125: in <module>
    register_chunk_type(sparse.SparseArray)
E   AttributeError: module 'sparse' has no attribute 'SparseArray'
```

I think it might have also impacted xarray as well as this bug looked similar

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960380

This patch in dask that I cribbed from the xarray <a href="https://salsa.debian.org/science-team/python-xarray/-/blob/debian/latest/debian/patches/sparse.patch">fix</a> seems to have resolved the problem

```
diff --git a/dask/array/chunk_types.py b/dask/array/chunk_types.py
index 7b0f5f8..afd9b87 100644
--- a/dask/array/chunk_types.py
+++ b/dask/array/chunk_types.py
@@ -122,7 +122,7 @@ except ImportError:
 try:
     import sparse
 
-    register_chunk_type(sparse.SparseArray)
+    register_chunk_type(sparse.COO)
 except ImportError:
     pass
```

Debian unstable's sparse package is 0.2.0 from your repository https://github.com/mrocklin/sparse which doesn't seem to contain a SparseArray class, either in the Debian package or the HEAD on github.

Thanks

**Comment by gforsyth** [comment]
Hey @detrout -- thanks for raising this!  It sounds like the debian unstable package is pointing at the wrong repo.  `sparse` is actively developed and maintained at https://github.com/pydata/sparse and the latest release is 0.11.2

**Comment by detrout** [comment]
Ooh. I wondered which was the actual release version... Thank you I'll go get the upstream on sparse in Debian switched over.
