### ISSUE TITLE
SettingWithCopyWarning with categorical dtype columns.

### ISSUE THREAD

**Issue by FilippoBovo** [dask/dask#7087]
**What happened**:

Joining a Pandas DataFrame with categorical columns to a Dask DataFrame, raises a `SettingWithCopyWarning` warning.

**What you expected to happen**:

I expect that no warning is raised, as with a Pandas join.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd


df1 = pd.DataFrame(data={"A": ["a", "b", "c"]}, index=["s", "v", "w"])
df2 = pd.DataFrame(data={"B": ["t", "d", "i"]}, index=["v", "w", "r"])

ddf1 = dd.from_pandas(df1, npartitions=1)

# Uncomment one line at a time
df2 = df2.astype({"B": "category"})  # Case1: Raises warning
# df2["B"] = df2["B"].astype("category")  # Case 2: Raises warning
# df2.loc[:, "B"] = df2["B"].astype("category")  # Case 3: Raises warning

print("Pandas join.")
df1.join(df2)

print("Dask join.")
ddf1.join(df2).compute()
```

In all the three cases, the Dask join, unlike the Pandas Join, raises a `SettingWithCopyWarning`:

```
/Users/user/.virtualenvs/my-project/lib/python3.8/site-packages/dask/dataframe/multi.py:272: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rhs[col] = right.astype(dtype)
```

**Anything else we need to know?**:

No.

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8.5
- Operating System: MacOS Big Sur 11.1 (20C69)
- Install method (conda, pip, source): Pip

**Comment by jsignell** [comment]
Thanks for reporting this! I am opening a PR to fix it now.

**Comment by FilippoBovo** [comment]
Thank you, @jsignell.

Is this fix going to be included in the next Dask release?

**Comment by jsignell** [comment]
> Is this fix going to be included in the next Dask release?

It has missed 2021.1.0 but it will probably be in the one after that.

**Comment by FilippoBovo** [comment]
Ok, thanks.
