### ISSUE TITLE
Groupby shift

### ISSUE THREAD

**Issue by beckernick** [dask/dask#7095]
I'd like to be able to use `shift` on groupby Series and DataFrame objects to create per-group lag or lead columns. Today, I can do this in pandas but not Dask.

```python
import pandas as pd
import dask.dataframe as dd
​
pdf = pd.DataFrame({
    "a": [0,1,0,1,1,0],
    "b": range(6),
    "c": ["a","b","c","d","e","f"]
})
ddf = dd.from_pandas(pdf, 2)
​
print(pdf.groupby("a").b.shift(1))
ddf.groupby("a").b.shift(1)
0    NaN
1    NaN
2    0.0
3    1.0
4    3.0
5    2.0
Name: b, dtype: float64
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-f89d506bbdcd> in <module>
     11 
     12 print(pdf.groupby("a").b.shift(1))
---> 13 ddf.groupby("a").b.shift(1)

AttributeError: 'SeriesGroupBy' object has no attribute 'shift'
```

```
conda list | grep "pandas\|dask"
dask                      2021.1.0           pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py37hdc94413_0    conda-forge
```

**Comment by jsignell** [comment]
That seems like a reasonable feature request. Are you interested in working on it? In the meantime I wonder if `map_overlap` could suit your needs.

**Comment by beckernick** [comment]
Thanks for the suggestion! I'll take a look at map_overlap.

I don't have the bandwidth to work on the implementation at the moment, but may in the future.

**Comment by quasiben** [comment]
FYI, cuDF recently refactored an implemented groupby.shfit: https://github.com/rapidsai/cudf/pull/8131

**Comment by chendingyan** [comment]
Hi, I'd like to do the same thing with map_overlap, and I did the following to compute groupby+shift
`ddf.groupby(['a']).map_overlap(lambda x: x.shift(1), 1, 1).compute()`
However, I got:
`AttributeError: 'Column not found: map_overlap'`
I wonder if there is a way for groupby + (other operation like shift)
@beckernick @quasiben

**Comment by jsignell** [comment]
You should take a look at https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate for tips on how to write custom aggregations. Or feel free to open a PR to add `shift` :)

**Comment by kori73** [comment]
I would love to work on this issue. 

This seems  similar to how `transform` or `apply `methods are implemented. My initial approach is to write a `_groupby_slice_shift` function and calling `shift` in it instead of `apply` or `transform`. I think we can then use it inside `map_partitions`.
