### ISSUE TITLE
Groupby.nunique along index

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#710]
We currently calculate groupby.nunique by using `drop_duplicates` on all chunks, then concatenate all results together followed by an `nunique`.  This works ok as long as the intermediate result fits into memory.  In cases where we group along the index, 

```
s.groupby(s.index).nunique()
```

or along an operation that maintains groups along the index

```
s.groupby(s.index.year).nunique()
```

Then we can just do `nuniques` directly on the chunks.  This is more efficient and less prone to fill up memory.  The idea of "operations that maintain groups along the index" is also an interesting one.  For example this would fail for the following:

```
s.groupby(s.index.minute).nunique()
```

**Comment by jsignell** [comment]
Closing since dask uses regular `aca` for `nunique` at this point.
