### ISSUE TITLE
Follow-up compatibility issues with pandas

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/dask#7100]
In https://github.com/dask/dask/pull/6996 we ensured that CI passes with pandas 1.1, 1.2 and master version, but I still skipped some tests or ignored warnings, just to get CI working for now.

The open issues to resolve from that were discovered there:

Changes related to pandas 1.1:

- [x]  There are still some `describe()` related warnings ignored in `dask/dataframe/tests/test_dataframe.py`. The pandas method deprecated behaviour regarding datetimes (seeing them as numeric instead of categorical), and added an option to get the new behaviour (see https://github.com/pandas-dev/pandas/pull/34798). 
  Question here is whether dask follows that behaviour change of pandas. [ #7719 ]

Changes related to pandas 1.2.0:

- [x] #8214
  Some tests are skipped for this in `dask/dataframe/tests/test_arithmetics_reduction.py`
- [x] `Categorical.set_levels(inplace=True)` is deprecated in pandas, and is used here in the groupby code. 
  Warnings are ignored in `dask/dataframe/tests/test_groupby.py` [#7712]
- [x] Pandas 1.2 deprecated using a single string as "partial datetime slice" in `__getitem__` (eg `df["2011-01-02"]`, but partial strings in an actual slice like `df["2011":"2012]` still works fine, and using that string with loc as well, i.e. `df.loc["2011-01-02"]`, where there is no ambiguity about selecting a column or slicing the rows).
  The question is if dask wants to follow this change (I assume yes). Currently some tests are skipped in `dask/dataframe/tests/test_indexing.py`.  [WIP #7749]
- [x] `Index.is_all_dates`is deprecated in pandas, and this is used here in the rolling code. 
  Warning are ignored in `dask/dataframe/tests/test_rolling.py` 
- [ ] #8216
  The question here is whether dask wants to follow that behaviour (I am not familiar with how column reductions are currently implemented). 

Changes related to pandas master (future 1.3.0):

- [x]  Some changes in the rolling code (related to `win_type`) in pandas will need adjustments in dask to make it compatible, see https://github.com/pandas-dev/pandas/pull/38963 
  Some tests are skipped and warning ignored in `dask/dataframe/tests/test_rolling.py` [WIP #8150]

**Comment by jsignell** [comment]
I think the consensus is that dask will follow all pandas behavior changes.

**Comment by mrocklin** [comment]
Hooray for not making design decisions!

**Comment by quasiben** [comment]
I think we can close this issue as Dask's Pandas min versions is now Pandas 1.3
