### ISSUE TITLE
Add support for `add_prefix and `add_suffix`

### ISSUE THREAD

**Issue by mzjp2** [dask/dask#7105]
I tend to use these before doing DataFrame merges so that my column names (of the right merged dataframe) retain some semantic notion of where they came from. Switched to Dask and noticed these don't exist.

Is that a conscious decision to exclude or would you be welcome to its addition?

I tried a brief google search and tried filtering through the issues on this repo, but forgive me if I've missed an existing discussion.

* [`pandas.DataFrame.add_prefix`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.add_prefix.html)
* [`pandas.DataFrame.add_suffix`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.add_suffix.html)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @mzjp2! Not a conscious decision, I suspect it's just nobody has gotten around to implementing these methods.

It seems like they could be implemented with `map_partitions` similar to `abs`

https://github.com/dask/dask/blob/0b33708f4627c3f9c7613c9554d1033db147d4b0/dask/dataframe/core.py#L1663-L1667

or several other methods in the `dask/dataframe/core.py`. 

Are you interested in working on this? No worries if not

**Comment by mzjp2** [comment]
Oh hey @jrbourbeau! We've spoke over at Zarr!

> Are you interested in working on this?

Yes, absolutely! Though I'm _totally_ new to the codebase here, but would love to get stuck in and have a go. Thanks for the pointer to `abs`.

**Comment by jrbourbeau** [comment]
Good to see you here too : )

Sounds good! Our contributing docs are at https://docs.dask.org/en/latest/develop.html. Feel free to open up a WIP PR if you get stuck or have any questions

**Comment by mzjp2** [comment]
Opened a PR @jrbourbeau if you wanna have a look, turned out to be easier than I thought (if I did it correctly at all...!). Thanks again for the pointer :)

**Comment by tsuga** [comment]
Is this PR still active? I wish to have add_prefix.
