### ISSUE TITLE
Clean up the HighlevelGraph.dicts property

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#7108]
``HighLevelGraph.dicts`` is an alias property to ``.layers``, which was put there as temporary backwards compatibility when we migrated from the previous design in #4092.

There's a bunch of stuff in the dask codebase that still invokes .dicts, but it is trivial to fix; not sure if anything else in third party projects uses it though. Should we go through a formal deprecation process, or is it OK to just remove it as over 2 years have passed since the change now?

**Comment by jrbourbeau** [comment]
Thanks for bringing this up @crusaderky. I'm not sure how much existing code out there is using `.dicts`. It's doesn't seem too expensive from a maintenance perspective to update all the code here to use `.layers` and add a deprecation warning to `.dicts` for others to do the same.
