### ISSUE TITLE
Specifying the partition size in DataFrame method `set_index` does not change the number of partitions.

### ISSUE THREAD

**Issue by FilippoBovo** [dask/dask#7110]
**What happened**:

Specifying the partition size in DataFrame method `set_index` does not change the number of partitions.

**What you expected to happen**:

I would expect the number of partitions to change when specifying the partition size.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd


df = pd.DataFrame(data={"a": [1, 2, 3, 2, 1], "b": ["x", "y", "z", "x", "x"], "c": [1, 2, 3, 2, 1]})

ddf = dd.from_pandas(df, npartitions=5)
print("Number of partitions:", ddf.npartitions)
# OUTPUT: Number of partitions: 4

npartitions = ddf.repartition(partition_size=512).npartitions
print(f"The number of partitions changes to: {npartitions}")
# OUTPUT: The number of partitions changes to: 2

npartitions = ddf.set_index("a", npartitions="auto", partition_size=512).npartitions
print(f"The number of partitions remains the same: {npartitions}")
# OUTPUT: The number of partitions remains the same: 4
# Here, I would expect to get 2 partitions, like when using `repartition`.
```

**Anything else we need to know?**:

No.

**Environment**:

- Dask version: 2021.1.1
- Python version: 3.8.5
- Operating System: MacOS Bit Sur 11.1 (20C69)
- Install method (conda, pip, source): Pip

**Comment by jsignell** [comment]
I think it actually is working as expected, but it's important to note that in the `set_index` case, `partition_size` is only allowed to decrease the total number of partitions (https://github.com/dask/dask/blob/5c96d82a1e401f02815b1e4f86f615229401950e/dask/dataframe/shuffle.py#L497:L499). 

In your MRE I think the size of the partitions is increasing dramatically with the `set_index` for instance if you set the partition_size higher, you get the desired effect: 

```python
npartitions = ddf.set_index("a", npartitions="auto", partition_size=5120).npartitions 
print(f"The number of partitions changes to: {npartitions}")                                                                       
# OUTPUT: The number of partitions changes to: 2
```

**Comment by FilippoBovo** [comment]
@jsignell, I suspected that that could be the case by looking at the source code. Do you happen to know what motivated the choice of changing the number of partitions only the new number is smaller than the current one?

Also, just to confirm, I get that, given a partition size, the number of partitions is calculated in different ways in `repartition` and `set_index`, right?

**Comment by jsignell** [comment]
> Do you happen to know what motivated the choice of changing the number of partitions only the new number is smaller than the current one?

I don't know, but I imagine it was to prevent making many small partitions by accident.

> just to confirm, I get that, given a partition size, the number of partitions is calculated in different ways in repartition and set_index, right?

Yeah it seems like it.

**Comment by FilippoBovo** [comment]
Ok. Thank you, @jsignell.

**Comment by FilippoBovo** [comment]
Sorry, just one more question. So, if I would like to set a certain number of partitions, say 5, and set a new index, should I use the following code?

```python
ddf.repartition(npartitions=5).set_index("index")
```

**Comment by jsignell** [comment]
Sorry I missed this. But yes that looks right to me. I am going to close this issue since I think dask is behaving as expected.
