### ISSUE TITLE
read_csv on non-zip files with zip extension

### ISSUE THREAD

**Issue by latusaki** [dask/dask#7111]
**What happened**:
 Reading a CSV file with `.zip` extension fails

**What you expected to happen**:
read_csv should work regardless of extension

**Minimal Complete Verifiable Example**:
fake.zip:
```
colA,colB
1,2
3,4
```

test.py:

```python
import dask.dataframe as dd
dd.read_csv("fake.zip")
```

**Anything else we need to know?**:

Error not present on 2020.12.0 or before

Exception at:

``` 
Traceback (most recent call last):
  File "dask-test.py", line 5, in <module>
    df = dd.read_csv("fake.zip")
  File "pipenv/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 670, in read
    **kwargs,
  File "pipenv/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 501, in read_pandas
    **(storage_options or {}),
  File "pipenv/lib/python3.7/site-packages/dask/bytes/core.py", line 162, in read_bytes
    with OpenFile(fs, paths[0], compression=compression) as f:
  File "pipenv/lib/python3.7/site-packages/fsspec/core.py", line 108, in __enter__
    f = compress(f, mode=mode[0])
  File "pipenv/lib/python3.7/site-packages/fsspec/compression.py", line 65, in unzip
    z = ZipFile(infile)
  File "/usr/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
**Environment**:

- Dask version: error happens at 2021.1.0, not present in 2020.12.0
- Python version: 3.7.5
- Operating System: Linux 
- Install method (conda, pip, source): pipenv

**Comment by latusaki** [comment]
Just noticed this also happens on plain pandas, but pandas version is not changing between `2020.12.0` and ` 2021.1.0`

**Comment by jsignell** [comment]
I suspect this was an issue in 2020.12.0 that has been fixed in 2021.1.0. I would expect this response.

**Comment by latusaki** [comment]
I'm 99% confident I first found this while using the latest version. I'll
confirm in a few hours.

**Comment by jsignell** [comment]
I realized my comment wasn't very clear. I think it is correct for this error to be thrown.

**Comment by latusaki** [comment]
I suspected that might be the case as Pandas will throw it... A bit
disappointing as our code is agnostic of extensions and uses byte headers
to recognise file types.

**Comment by jsignell** [comment]
Oh! In that case, you can do:

```python
import dask.dataframe as dd
dd.read_csv("fake.zip", compression=None)
```
