### ISSUE TITLE
[ENH] Add sort_values to dask dataframe

### ISSUE THREAD

**Issue by stromal** [dask/dask#7120]
I am just trying to order a dask dataframe by a specific column.

**CODE 1** - If I call it it shows as indeed a ddf

```my_ddf```

**OUTPUT 1**
``` Dask DataFrame Structure:   ...
npartitions=1	
headers .....
 ```

**CODE 2**

```my_ddf.sort_values('id', ascending=False)```

**OUTPUT 2**

``` ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-374-35ce4bd06557> in <module>
----> 1 my_ddf.sort_values('id', ascending=False) #.head(20)
      2 # df.sort_values(columns, ascending=True)

~/anaconda3/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in __getattr__(self, key)
   3619             return self[key]
   3620         else:
-> 3621             raise AttributeError("'DataFrame' object has no attribute %r" % key)
   3622 
   3623     def __dir__(self):

AttributeError: 'DataFrame' object has no attribute 'sort_values'
```

**Tried Solutions**
- This is an example from the official dask documentation ``` df.sort_values(columns, ascending=False).head(n)```
- pandas only - https://stackoverflow.com/questions/34499728/dataframe-object-has-no-attribute-sort-values
- pandas only - https://stackoverflow.com/questions/44123874/dataframe-object-has-no-attribute-sort/44123892
- DASK answer - https://stackoverflow.com/a/40378896/10270590
   -  I don't want to set it in to index because I want to have only my current index values. 
   - The following answer is a bit view and I m not sure that it would work when I have more partition or how to not to have just a random big number "1000000000". Or how to make it Increasing from top to bottom in the dask dataframe ```my_ddf.nlargest(1000000000, 'id').compute()```

**Comment by jsignell** [comment]
You are correct. Dask dataframe does not have a `sort_values` method. Dask dataframe mimics the pandas API but is a subset of that API, so not all methods are implemented. As mentioned in some of the links, it can be tricky to sort in a distributed way. Please open a pull request if you are interested in implementing `sort_values`!

**Comment by stromal** [comment]
Currently I am happy with my hotfix I was just checking if there are any other better solution even if the exact function not exists.
