### ISSUE TITLE
Request: Split up the Dataframe API documentation

### ISSUE THREAD

**Issue by gerrymanoim** [dask/dask#7123]
The documentation page at https://docs.dask.org/en/latest/dataframe-api.html is difficult to use at this point. It takes my browser ~10 seconds to load the entire page and become responsive (or to scroll to the linked to content after loading). Finding anything on the page produces hundreds of entries for most search terms. 

I've tried just downloading the pdf instead from (https://docs.dask.org/_/downloads/en/latest/pdf/) but the TOC there only has three sections and is a bit hard to navigate. 

I love all the docs (seriously, thank you) they're just a bit hard to browse at the moment when I can't quite remember what the supported methods are on a dask object.

**Comment by jsignell** [comment]
I have also had this experience. Thanks for bringing it up! Do you have suggestions for how to split it up?

My first idea is to make each of these separate pages:

![image](https://user-images.githubusercontent.com/4806877/106171381-781ebd80-615f-11eb-8b34-1bb01b0f546c.png)

**Comment by gerrymanoim** [comment]
Yep -  I think that makes sense to me! I wasn't able to post a picture before, but the PDF sections are 

![image](https://user-images.githubusercontent.com/194147/106176410-40b30f80-6165-11eb-87ee-5daad8f147b1.png)

for some reason.

**Comment by rajpratyush** [comment]
is this issue open for work @jsignell

**Comment by mrocklin** [comment]
Another option would be to keep the TOC/index page the same, but to split off each function into a separate page.  This is similar to what Pandas does.

I recommend that we do what Pandas does here.

See https://pandas.pydata.org/pandas-docs/stable/reference/index.html

@rajpratyush yes, anyone can work on anything, you do not need to ask for permission.
