### ISSUE TITLE
Repartitiong fails, likely from exhausted iterator relied on by a task

### ISSUE THREAD

**Issue by vlad-oles** [dask/dask#7131]
**What happened:**
Repartitioning of Dask Dataframe fails with StopIteration.

**What you expected to happen:**
Repartitioning is successful.

**Minimal Complete Verifiable Example:**
```
import numpy as np
import pandas as pd
import dask.dataframe as dd

ddf = dd.from_pandas(pd.DataFrame(np.random.rand(1000000, 4)), npartitions=2)
cols = iter(range(len(ddf.columns)))
ddf = ddf.rename(columns=lambda x: next(cols))
ddf.repartition(partition_size='1MB')
```

**Anything else we need to know?:**
The error happens because the .rename() uses an iterator which turns out to be exhausted by the time of .repartition() call.

**Environment:**
* Dask version: 2021.01.1
* Python version: 3.8.6
* OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
* Install method: conda

**Comment by vlad-oles** [comment]
The rationale for renaming columns based on an iterator is to allow element-wise operations between different dataframes:
```
def rename(df):
    cols = iter(range(len(df.columns)))
    return df.rename(columns=lambda x: next(cols))

ddf = dd.from_pandas(pd.DataFrame(np.random.rand(1000000, 4), columns=list('ABCD')), npartitions=1)
rename(ddf[['A', 'B']]) * rename(ddf[['C', 'D']])
```

**Comment by jsignell** [comment]
Thanks for giving the additional context. The reason why you are getting the unexpected failure is because dask runs all functions on `ddf._meta` before creating the task graph. So that uses up the whole iterator before the "real" computation.

Instead of using an iterator you can use a dictionary:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

ddf = dd.from_pandas(pd.DataFrame(np.random.rand(1000000, 4)), npartitions=2)
ddf = ddf.rename(columns={col: i for i, col in enumerate(df.columns)})
ddf.repartition(partition_size='1MB')
```

**Comment by vlad-oles** [comment]
Thank you, this solves the issue for me.
