### ISSUE TITLE
Issue: dask.array.ravel currently requires an 'array' object as argument but should require an 'array_like' object

### ISSUE THREAD

**Issue by D-Stacks** [dask/dask#7132]
I noticed a problem with the `dask.array.ravel` function. It currently requires an `array` as input else it throws an `AttributeError`. This is in contrast to how `numpy.ravel` handles the input, which merely requires the argument to be `array_like`. The problem can be demonstrated with the code below: 

````python

import numpy as np
import dask.array as da

np.ravel([0,0]) #Does not raise any Error
da.ravel([0,0]) #Raises AttributeError
````
The problem can easily be corrected. Currently `dask.array.ravel` simply tries to reshape the the input using `array.reshape((-1))` as follows:

````python
def ravel(array):
    return array.reshape((-1))
````
the correct way, which mirrors `numpy`, performs a conversion calling `asasanyarray()` on the input before reshaping

````python
def ravel(array_like):
    return asasanyarray(array_like).reshape((-1))
````
This may seem trivial at first, and from the code change perspective it is, but a wide range of `numpy` functions use ravel internally and require this behaviour in order to accept array_like arguments. For example: `numpy.append` relies on this behaviour in order to accept `array_like` arguments.

Furthermore, I propose to include this in future testing of the function in order for it to maintain the correct behaviour in future versions. Currently this behaviour is not tested.

**Comment by D-Stacks** [comment]
Sorry for spamming pull requests. I decided to learn the 'how to' through trial and error.

**Comment by jsignell** [comment]
> Sorry for spamming pull requests. I decided to learn the 'how to' through trial and error.

No worries. Glad you were able to figure it out and ended up with a nice clean PR
