### ISSUE TITLE
Repartition on day is incorrect when index is timestamped per day

### ISSUE THREAD

**Issue by rubenvdg** [dask/dask#7139]
When the index is timestamped per day (at midnight), repartition per day gives the wrong result:

```
index = [
    pd.Timestamp(2020, 1, 1),
    pd.Timestamp(2020, 1, 1),
    pd.Timestamp(2020, 1, 2),
    pd.Timestamp(2020, 1, 2)
]

pdf = pd.DataFrame(index=index, data={"foo": "foo"})
ddf = dd.from_pandas(pdf, npartitions=2).repartition(freq="D")

print(ddf.npartitions)
>>> 1

print(ddf.partitions[0].compute())
>>>             foo
>>> 2020-01-01  foo
>>> 2020-01-01  foo
>>> 2020-01-02  foo
>>> 2020-01-02  foo

```

I would expect two partitions (one for January 1 and one for January 2).

If you agree that this is a bug, I could look into it. 

Python: 3.8.6
Dask: 2021.01.1
OS: MacOS (Big Sur)

**Comment by rubenvdg** [comment]
I did some more digging, the problem is as follows:

If:

a) the penultimate division is non-empty, AND
b) there are observations that coincide with the end of the final division

then the last two divisions are wrongfully combined.

So this will go wrong:

```
index = [
    pd.Timestamp("2020-10-31"),
    pd.Timestamp("2020-11-30"),
    pd.Timestamp("2020-12-31"),
]

pdf = pd.DataFrame(index=index, data={"foo": "foo"})
ddf = dd.from_pandas(pdf, npartitions=1).repartition(freq="M")
```

but this will be fine

```
index = [
    pd.Timestamp("2020-10-31"),
    pd.Timestamp("2020-12-31"),
]

pdf = pd.DataFrame(index=index, data={"foo": "foo"})
ddf = dd.from_pandas(pdf, npartitions=1).repartition(freq="M")
```

Pretty tricky to circumvent this, since you'd have to query the index to check if a) holds.

**Comment by jsignell** [comment]
Yeah. Turns out pandas-style resampling is kind of hard for distributed data. If you are able to dig into it more and open a pull request that would be appreciated. I started a PR a while ago #6300 but I didn't really get anywhere.

**Comment by rubenvdg** [comment]
I’ll give it a go.

**Comment by rubenvdg** [comment]
@jsignell I think I have a (simple) fix for this, that I'm implementing. Could you confirm that the divisions in `pytest dask/dataframe/tests/test_dataframe.py::test_repartition_freq_month` are actually wrong atm?

The divisions generated are:

- `Timestamp('2015-01-01 00:00:00', freq='10T')`
- `Timestamp('2015-01-31 00:00:00', freq='M')`
- `Timestamp('2015-02-28 00:00:00', freq='M')`
- `Timestamp(2015-03-31 00:00:00', freq='M')`
- `Timestamp('2015-04-30 00:00:00', freq='M')`
- `Timestamp('2015-05-01 23:50:00', freq='10T'))`

But **should be** imo:

- `pd.Timestamp("2015-1-1 00:00:00")`
- `pd.Timestamp("2015-2-1 00:00:00")`
- `pd.Timestamp("2015-3-1 00:00:00")`
- `pd.Timestamp("2015-4-1 00:00:00")`
- `pd.Timestamp("2015-5-1 00:00:00")`
- `pd.Timestamp("2015-5-1 23:50:00")`

Or am I missing something?

**Comment by jsignell** [comment]
Yeah I think it should either be 

```python
Timestamp("2015-01-01 00:00:00")
Timestamp("2015-02-01 00:00:00")
```

or something that is basically equivalent like:

```python
Timestamp("2015-01-01 00:00:00")
Timestamp("2015-01-31 23:55:00")
...
```

**Comment by jsignell** [comment]
For instance in that test you point to we should be able to add this check and it should work: 

```python
pandas_mean = df.groupby(pd.Grouper(freq="1M")).mean()
assert_eq(expected,  ddf.mean())
```

The index of `pandas_mean` indicates what our partitions should be like.

**Comment by rubenvdg** [comment]
I don't think I understand that. Doesn't `ddf.mean()` just return the column means?

**Comment by jsignell** [comment]
I don't understand it anymore either, sorry about that. Let me try to write this down more carefully. I think this is what I meant:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

ts = pd.date_range("2015-01-01 00:00", " 2015-05-01 23:50", freq="10min")
df = pd.DataFrame(
    np.random.randint(0, 100, size=(len(ts), 4)), columns=list("ABCD"), index=ts
)
ddf = dd.from_pandas(df, npartitions=1).repartition(freq="1M")

pandas_mean = df.groupby(pd.Grouper(freq="1M")).mean()
for index_value in pandas_mean.index:
    assert index_value == ddf.divisions[i + 1]
```

But looking at this now I think you are totally right that last day of the month should be fully included in the division for that month. So your proposal in https://github.com/dask/dask/issues/7139#issuecomment-795419359 seems perfect.

**Comment by rubenvdg** [comment]
Fixed in https://github.com/dask/dask/pull/7357
