### ISSUE TITLE
GroupBy.transform() fails when grouping by Datetime

### ISSUE THREAD

**Issue by vlad-oles** [dask/dask#7140]
**What happened:**
calling .transform() results in ValueError.

**What you expected to happen:**
Successful broadcasting of aggregation result to the original data shape.

**Minimal Complete Verifiable Example:**
```
import pandas as pd
import dask.dataframe as dd

# Create a dataframe indexed by time.
df = pd.DataFrame({'time': pd.date_range('11:00', '18:30', freq='1h'), 'value': [1] * 8})
ddf = dd.from_pandas(df, npartitions=1).set_index('time')
# When aggregating by time, .transform('sum') fails.
ddf.groupby(pd.Grouper(freq='2h')).transform('sum').compute()
```

**Environment:**
* Dask version: 2021.01.1
* Python version: 3.8.6
* OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
* Install method: conda

**Comment by rubenvdg** [comment]
Could well have to do with the fact that `pd.Grouper` is not supported by Dask (https://github.com/dask/dask/issues/5195, https://github.com/dask/dask/issues/6104).

**Comment by jsignell** [comment]
Right, like @rubenvdg mentioned `pd.Grouper` isn't supported. As a workaround, you can use `resample`

For instance:

```python
df.set_index("time").resample("2h").sum()
```

**Comment by vlad-oles** [comment]
Thanks for the suggestion. However, `pd.Grouper` can be used in combination with other columns in a `groupby`. Does `resample` allow such functionality?

For example, if I have my data as 
```
df = pd.DataFrame({'time': pd.date_range('11:00', '18:30', freq='1h'), 'value': [1] * 8, 'group': list('ab')*4})
ddf = dd.from_pandas(df, npartitions=1).set_index('time')
```
and want to aggregate it by the combination of 'group' and 2-hour windows, I can use `pd.Grouper` like
```
ddf.groupby(['group', pd.Grouper(freq='2h')]).sum()
```
(despite the lack of support, it actually works). How would I go about it using `resample`?

**Comment by rubenvdg** [comment]
As long as `pd.Grouper` is not supported I would do something along the lines of:

```
(
    ddf
    .assign(two_hour_bin=lambda ddf: ddf.index.dt.ceil("2H").values)
    .groupby(["group", "two_hour_bin"])
    ["value"]
    .sum()
    .compute()
)
```
