### ISSUE TITLE
Dask.org links should be updated

### ISSUE THREAD

**Issue by Naeemkh** [dask/dask#7147]
[Dask.org](https://dask.org/) `try now` links give the following error:

![image](https://user-images.githubusercontent.com/6773835/106399055-10c17180-63dc-11eb-9064-5fae73a29895.png)

and here is the log:

```
Could not resolve ref for gh:dask/dask-examples/master. Double check your URL. GitHub recently changed default branches from "master" to "main". Did you mean the "main" branch?
```

Changing master to main, resolves the problem.

https://mybinder.org/v2/gh/dask/dask-examples/master?urlpath=lab/tree/dataframe.ipynb --> raise error
https://mybinder.org/v2/gh/dask/dask-examples/main?urlpath=lab/tree/dataframe.ipynb --> OK

**Comment by jsignell** [comment]
Thanks for raising this! We are in the process of moving from master to main and this is not something that we had thought of.

**Comment by jrbourbeau** [comment]
Thanks for reporting @Naeemkh! This should be resolved by https://github.com/dask/dask.github.io/pull/42
