### ISSUE TITLE
Map_partitions does not return partition_info

### ISSUE THREAD

**Issue by bsesar** [dask/dask#7149]
**What happened**: map_partitions() returns None, even for a simple example (see below). I may have misunderstood this [example](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) for ```partition_info```.

**What you expected to happen**: For the simple example given below, ```map_partitions``` should return two lines with a dictionary in each line. 

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.dataframe as dd

def test_func(df, partition_info=None):
  return partition_info

df = dd.from_pandas(pd.DataFrame({'a':np.arange(10), 'b':np.arange(10)}), npartitions=2)

df.map_partitions(test_func)
```
**Anything else we need to know?**:

**Environment**:

- Dask version: 2.30.0
- Python version: 3.7.8
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
partition_info was added in https://github.com/dask/dask/pull/6776 which was first included in dask 2021.01.0, so you'll need to upgrade your dask version to use it.
