### ISSUE TITLE
Any way to speed up da.stack?

### ISSUE THREAD

**Issue by henrypinkard** [dask/dask#7161]
I've got an application where I'm using dask to combine a large number (~10^4) of memory mapped, 2D numpy arrays into a large array with ~5 dimensions. The call `da.stack`, into which I pass a nested list of these memory mapped arrays takes a long time (~2 min) to complete and uses an amount of memory equivalent to the full size of the dataset (20GB) before returning and dropping back down to 1 GB. It seems like daks might be reading every 2D array into memory in the process of combining them.

I'm wondering if this behavior is expected, and if there is any way to speed this up and reduce memory usage?

**Comment by D-Stacks** [comment]
I'm by no way a dask expert but I think you are right. dstack just seems to concatenate tuples.

here is the current implementation:

```python

def dstack(tup, allow_unknown_chunksizes=False):
    tup = tuple(atleast_3d(x) for x in tup)
    return concatenate(tup, axis=2, allow_unknown_chunksizes=allow_unknown_chunksizes)

```

maybe try this little helper function :
```python

import numpy as np
from dask.array.core import map_blocks,

def _dstack_map(x):
    np.dstack(x)
    return x

def dstack(x):
    return map_blocks(_dstack_map, x, dtype=x.dtype)

```

this probably won't be an ideal solution. but i ran the following test:

```python
import numpy as np
import dask.array as da
n = np.random.randint(10, size=(3000, 30, 30))
dar = da.from_array(n, chunks=(300,3,3))

def test_dstack1():
    np.dstack(n)

def test_dstack2():
    da.dstack(dar)

def test_dstack3():
    dstack2(dar).compute()

print('hi')
print(timeit(test_dstack1, number = 10))
print(timeit(test_dstack2, number = 10))
print(timeit(test_dstack3, number = 10))
```

It seems to be about 1/3 faster, but I suspect it might scale to more with larger chunk sizes and bigger arrays.

**Comment by SteffenBauer** [comment]
+1, thats something thats bothering me also.

I opened an according question in the discussions (https://github.com/dask/dask/discussions/7116), there is some example code. Stacking 40000 numpy arrays of shape (100, ) into an array of shape (40000, 100) via da.stack and computing the values takes extremely long, and is growing with O(N^2).

Interestingly, when I rewrote the code to use np.stack via dask.delayed, the result is computed very fast, so it looks like something inefficient is happening in da.stack.

**Comment by d-v-b** [comment]
this has come up several times in the past, and I think the answer was always essentially "use map blocks instead" -- see this discussion https://github.com/dask/dask/issues/5913

**Comment by SteffenBauer** [comment]
Seems to be solved now: https://github.com/dask/dask/issues/7402

**Comment by jakirkham** [comment]
Thanks for the update :)

**Comment by henrypinkard** [comment]
Thanks!
