### ISSUE TITLE
minor documentation error in examples page for LocalCluster

### ISSUE THREAD

**Issue by murphyk** [dask/dask#7185]
On this page
https://examples.dask.org/delayed.html#Start-Dask-Client-for-Dashboard
there is this code snippet
```
from dask.distributed import Client, progress
client = Client(threads_per_worker=4, n_workers=1)
```
This does not run (on my minikube setup). I think it should be
```
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(threads_per_worker=4, n_workers=1)
client = Client(cluster)
```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @murphyk. These two code snippets should be equivalent. If no scheduler address is passed to `Client` then a `LocalCluster` will be created automatically (for reference see the [`Client` docstring](https://github.com/dask/distributed/blob/7d2a22f94332974825e599dd779b4d98f44dbca2/distributed/client.py#L513-L517)).

> This does not run (on my minikube setup)

Could you elaborate a bit more on how things aren't working. Do you get an error or warning?

**Comment by murphyk** [comment]
Hmm, I cannot seem to reproduce the problem. Sorry for the false alarm. Closing the issue.
