### ISSUE TITLE
HighLevelGraph erroneously propagates into local scheduler optimization routines

### ISSUE THREAD

**Issue by jcrist** [dask/dask#7190]
The latest release of dask has broken prefect, but I think the real issue has persisted earlier and is only exposed now due to a new error path.

Here's an example that fails using raw dask alone:

```python
import dask


class NoGetItem:
    def __getitem__(self, key):
        raise Exception("Oh no!")


@dask.delayed
def identity(x):
    return x


x = identity(NoGetItem())


if __name__ == "__main__":
    dask.compute(x, scheduler="processes", optimize_graph=False)
```

Running the above:

```python
﻿﻿﻿Traceback (most recent call last):
  File "ex.py", line 18, in <module>
    dask.compute(x, scheduler="processes", optimize_graph=False)
  File "/Users/jcristharif/Code/dask/dask/base.py", line 563, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/jcristharif/Code/dask/dask/multiprocessing.py", line 202, in get
    dsk2, dependencies = cull(dsk, keys)
  File "/Users/jcristharif/Code/dask/dask/optimization.py", line 51, in cull
    dependencies_k = get_dependencies(dsk, k, as_list=True)  # fuse needs lists
  File "/Users/jcristharif/Code/dask/dask/core.py", line 258, in get_dependencies
    return keys_in_tasks(dsk, [arg], as_list=as_list)
  File "/Users/jcristharif/Code/dask/dask/core.py", line 186, in keys_in_tasks
    if w in keys:
  File "/opt/miniconda3/envs/prefect/lib/python3.8/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/Users/jcristharif/Code/dask/dask/highlevelgraph.py", line 509, in __getitem__
    return self.layers[key[0]][key]
  File "ex.py", line 6, in __getitem__
    raise Exception("Oh no!")
Exception: Oh no!
```

The offending change was https://github.com/dask/dask/pull/7160/files#diff-fcf20b06a1a7fbca83c546765f996db29477b9d43cbccf64f3426ef7cc6eddecR509, but I don't think it's the real bug. The real issue seems to be `HighLevelGraph` objects sneaking into optimization routines in the local schedulers. This might be as simple as a `ensure_dict` call in `dask.multiprocessing.get` before the graph is forwarded to `cull` (https://github.com/dask/dask/blob/2640241fbdf0c5efbcf35d96eb8cc9c3df4de2fd/dask/multiprocessing.py#L202), but I'm not sure where the boundary should be (I haven't kept up with all the high level graph work).

**Comment by jcrist** [comment]
I can confirm that adding a call to `ensure_dict` in `dask.multiprocessing.get` fixes things. Since we want to be passing high-level graphs to the distributed scheduler, I think having the low-level `get` functions handle this transform if needed makes the most sense. I'll push a PR up later today with a fix.

**Comment by jrbourbeau** [comment]
Thanks for surfacing this @jcrist

I was under the impression that optimization, single-machine scheduling, etc. functionality were all compatible with `HighLevelGraph`s. For example, the example you posted works with the synchronous and multi-threaded schedulers (where a `HighLevelGraph` is passed to their low-level `get`) on the current dev version of `dask` and it works on all single-machine schedulers prior to https://github.com/dask/dask/pull/7160. Perhaps the `HighLevelGraph.__getitem__` optimizations introduced in https://github.com/dask/dask/pull/7160 should be modified instead. 

cc @madsbk @rjzamora @crusaderky for visibility

**Comment by jcrist** [comment]
The multiprocessing scheduler calls `cull` (and optionally `fuse`) before forwarding things to `get_async` (which does properly convert the graph to a dict). This is the only difference, and is the reason for the issue here. I think fully converting `HighLevelGraph` objects to `dict`s in `dask.multiprocessing.get` is a sufficient and valid solution. Before things were accidentally working, but I don't think it was intended that `HighLevelGraph` objects made their way into `cull`.

**Comment by jrbourbeau** [comment]
Re-familiarizing myself with how we cull `HighLevelGraph`s, you're totally right that those operations go down a separate code path. Calling `ensure_dict` seems like a reasonable fix
