### ISSUE TITLE
array data without reference kept on workers?

### ISSUE THREAD

**Issue by allefeld** [dask/dask#7212]
I'm trying to wrap my mind around Dask's worker memory management and how to influence it, following [Managing Memory](https://distributed.dask.org/en/latest/memory.html). Here is a small example I used to test:

Creating the client: I have a 16 GB machine, some memory is used by other processes, 12 GB is approximately the amount of free memory.

````python
from dask.distributed import Client
client = Client(processes=False, threads_per_worker=4, n_workers=1, memory_limit='12GB')
````

Creating a large array. This array represents 4.8 GB, less than half of the worker memory. Since it's not computed, after creation used worker memory remains low, at about 160 MB (all numbers according to the dashboard).

````python
import dask.array as da
p = da.random.random((30000, 20000), chunks=(1000, 1000))
````

Computing the mean of the array. Used worker memory remains low throughout, climbing to about 240 MB. Great!

````python
pmc = p.mean().compute()
````

Now I try it the other way around: Compute the array, then calculate the mean locally. Since I request the full array, worker memory use climbs to around 5 GB during `compute`.

````python
pcm = p.compute().mean()
````

Then – it *doubles*. I assume that is because the array is copied from the workers into the local process, which means there are now two copies – but I don't understand why the local copy counts towards the *worker memory* usage?

Correspondingly, I'm getting warnings: "Process memory: 9.31 GB". Which process does this refer to? – I thought the worker process is separate from my local process?

After the mean has been computed, worker memory usage drops again, but only to about 2.8 GB.

I'm guessing that is because `p` still exists, I might do other things with it, and the computed random numbers are kept for that. But then, shouldn't memory use be around 5 GB?

Anyway, I delete the reference to the array to clear the worker memory.

````python
del p
````

That has no effect at all.

In case garbage collection didn't kick in, I run it explicitly.

````python
import gc
gc.collect()
````

Again no effect.

Following the documentation linked to above, I then restart the client.

````python
client.restart()
````

And again, no effect.

So, how do I get rid of the unused 2.8 GB stored on the client, so I can use it again?

I realize requesting gigabytes of computed results from the workers is something that shouldn't normally be done. But on a smaller scale, that is sometimes necessary, and if there is no way to clear worker memory, then this residue accumulates. For an example closer to real use, see [Efficiently avoid large intermediate array in computation? – Dask edition](https://stackoverflow.com/questions/66178337/efficiently-avoid-large-intermediate-array-in-computation-dask-edition).

> Python 3.8.2, Dask 2.30.0, NumPy 1.19.2, Debian 10.8

**Comment by TomAugspurger** [comment]
If I had to guess, this sounds like https://github.com/dask/dask/issues/3530.

It shows up with the threaded scheduler, so it's not necessarily related to the distributed scheduler.

```python
import psutil
import numpy as  np
import dask.array as da
import dask.threaded

proc = psutil.Process()

before = proc.memory_info()


p = da.random.random((30000, 20000), chunks=(1000, 1000))


pcm = p.compute().mean()

after = proc.memory_info()

>>> after.rss / before.rss
41.070425886271714

>>> dask.utils.format_bytes(after.rss)
'2.83 GB'
```

IIRC, that issue isn't resolved.

**Comment by allefeld** [comment]
> It shows up with the threaded scheduler

Pity, that one's pretty old.

> It shows up with the threaded scheduler

Does that mean `threads_per_worker=1, n_workers=4` is a workaround?

**Comment by ncclementi** [comment]
@allefeld  and @TomAugspurger. Checking in here.
I run the code on the original post and now things behave much nicer. After computingthe array, and then calculate the mean locally. Worker memory use climbs to around 5 GB during compute. But after the compute memory goes down to around 300MB

![memory](https://user-images.githubusercontent.com/7526622/129279463-a5ef2582-b7d3-4114-84c4-6db72dd62af9.gif)


When running the code from @TomAugspurger comment I get 
```
>>> after.rss / before.rss
7.352722287504896

>>>dask.utils.format_bytes(after.rss)
'586.61 MiB'
```

My understanding is  that the changes introduced in the Rebalance PR https://github.com/dask/distributed/pull/4774 plus the collocation PR https://github.com/dask/distributed/pull/5018 and https://github.com/dask/distributed/pull/4967 

Affected what is reported here for good. If that's the case, @allefeld would you be comfortable closing the issue?

**Comment by allefeld** [comment]
@ncclementi, my code has changed a lot since February, so this issue is not immediately relevant to me any more. Since you think it may have been resolved, I'm okay to close. Thanks!
