### ISSUE TITLE
Make trivial dependencies mandatory

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#7244]
This is a follow-up from a very old discussion on #5511, which resurfaced again today on #7243.

dask features several trivial optional dependencies: **cloudpickle, fsspec, toolz**, and **partd**. "trivial" here means that
1. they are either pure-python or with a transparent pure-python option,
2. they are tiny,
3. they exclusively have dependencies of their own that match the above two criteria.

As they are optional, when somebody types ``pip install dask`` (as a distracted user will likely do) they are not installed.

There is nothing in our CI, except for the superficial ``continuous_integration/scripts/test_imports.sh``, verifying that dask can actually work without them.

``toolz`` is a hard dependency of ``dask.base``, so I strongly suspect there is nobody out there who doesn't use it: we're talking about an hypotethical user who either manually builds dask graphs or wrote a custom dask collection and who doesn't use any of the many fundamental tools in ``dask.base``. 

# Proposed change
- Make cloudpickle, fsspec, toolz, and partd mandatory dependencies.
- The [bag] and [delayed] targets in setup.py would become empty, for backwards compatibility purposes only.
- Clean up the codebase of all conditional imports of dask.bag, dask.delayed, or one of the above libraries.

CC @ryan-williams ; please pull in any other known "light" dask users that install neither numpy nor pandas.

**Comment by ryan-williams** [comment]
Thanks for starting the discussion!

Just to note: I only ran across this because Dask forks seem to run the mindeps GHAs out of the box (where dask/dask generally don't; [commits containing `test-mindeps` in the msg should trigger them](https://github.com/dask/dask/blob/9426a823bc12034031f3c90e74c7be8f4cb94ca6/.github/workflows/ci-additional.yml#L8), but [I was unable to get that to happen](https://github.com/dask/dask/pull/7242/checks?check_run_id=1928044056)). I'm not generally a "light" Dask user / don't know what that use-case looks like.

**Comment by crusaderky** [comment]
This issue has been encountered on #7247 as well

**Comment by jsignell** [comment]
I am not a minimal dask user and am generally pro this idea of making more dependencies mandatory, but I would like to suggest a few reasons why people might be anti: 

1. Adding dependencies, even trivial dependencies increases the risk of dependency resolution failing or taking a long time.
2. There might be practical use cases where users don't do any IO. In this case, it makes sense that they wouldn't want to include `fsspec`

I am also wondering if the pain around this goes away if we automate testing of the minimal dependencies.

**Comment by crusaderky** [comment]
> I am also wondering if the pain around this goes away if we automate testing of the minimal dependencies.

On the opposite, have a look at the great deal of pain we went through trying to chase this philosophy in #5511.

An example: dask.bag does not, *theoretically*, depend on cloupickle. *Practically* however, its test suite is full of lambdas and local functions which *could* be removed but that would make the code a lot less readable; we should also expect that most dask.bag users will make liberal uses of lambdas for the same reason.

**Comment by jsignell** [comment]
Yeah that makes sense. I don't have a strong opinon.

**Comment by mrocklin** [comment]
Historically the main use case to avoid dependencies was to make other library authors more comfortable depending on Dask.  I think that for us to feel comfortable adding these dependencies we should check with other downstream libraries that depend on Dask today and see how they feel.  Xarray (cc @shoyer), Scikit-Image (cc @stefanv), and Prefect (cc @jcrist) seem like good candidates to query.

How would you all feel if the `dask` PyPI package depended on `fsspec`, `cloudpickle`, `toolz`, and `partd`?

**Comment by stefanv** [comment]
`dask` is an optional dependency of scikit-image, and we always install it along with `cloudpickle`; so from the skimage-specific perspective this is probably fine (I'll mention this to the rest of the team, just in case).

Personally, I think depending on a tiny handful of small, well-maintained, pure-Python dependencies to simplify your code base sounds like a good move.

**Comment by jcrist** [comment]
This also won't matter to prefect, most dasj users are running with the distributed scheduler, and cloudpickle is already a required dependency for other reasons.

**Comment by jsignell** [comment]
Ok seems like there is consensus around adding these dependencies. Thanks for raising this @crusaderky!

**Comment by jsignell** [comment]
I am opening a PR to make this change now.
