### ISSUE TITLE
submit task is not running in background.

### ISSUE THREAD

**Issue by gudipudipradeep** [dask/dask#7245]
I am using **flask application** with **dask_kuberntes**. I am trying to run the **background task by using submit  method**.

def greeting(message):
....from time import sleep
....print(f'countdown started: {message}')
....sleep(60*2)
....print(f'countdown ended: {message}')
....return message
futures_greeting = client.submit(greeting, 10000)

I got the control to the flask application but submit task is not running in the background. I have seen the work log... it is not showing any execution details. but it is working when i add this line `client.gather(futures)` but it is waiting till it complete. but i don't to wait it
Please help me.
@jcrist @mrocklin @jrbourbeau @jsignell  your suggestion will be helpful

**Comment by martindurant** [comment]
Please can you include a full, but minimal example of code which reproduces the problem, which in this case should have a flask app too.

**Comment by gudipudipradeep** [comment]
@martindurant  my flask_api look like below. we are getting cluster object to use.
`this will give the kuberntes cluster object`: dask_cluster.k8scluster


@app.route("/health")
def health():
....    #client creation using cluster object.
....    client = Client(dask_cluster.k8scluster)
....    #scaling the worker 
....    dask_cluster.k8scluster.scale(1) 
........ def greeting(message):
........     from time import sleep
........     print(f'countdown started: {message}')
........     sleep(60*2)
........     print(f'countdown ended: {message}')
........     return message
.... #calling the greeting method
.... futures_greeting = client.submit(greeting, 10000)
.... #futures = client.map(greeting, range(10000))
.... #client.gather(futures)
.... return jsonify("healthy")

This my api endpoint with implementation. when I use gather it is working because it will wait till it complete. but I want it run in background. and I can able to track it by  futures_greeting.key

**Comment by martindurant** [comment]
Again, please can you post a complete code example that we can copy/paste to observe the same problem. You should observe the same with a LocalCluster as with kubernetes.

**Comment by gudipudipradeep** [comment]
@martindurant  this is the peace of code we are using to create the cluster object. it was created it by using int_app in the flask. below peace of code will help you to create as well.

auth = KubeConfig(config_file=r"C:/Users/nameofuser/.kube/config",)
dask.config.set({"kubernetes.scheduler-service-type": "LoadBalancer"})
dask.config.set({"distributed.comm.timeouts.connect": 180})
pod_spec = make_pod_spec(image=<image>, memory_limit='2G', memory_request='2G',cpu_limit=1, cpu_request=1)
cluster = KubeCluster(pod_spec, deploy_mode="remote", auth=auth)
print("Dask cluster detials: {0}".format(cluster))
print("Dask portal: {0}".format(cluster.dashboard_link))

**Comment by gudipudipradeep** [comment]
@martindurant  the below link helped me to solve the issue.
https://stackoverflow.com/questions/62164283/why-do-my-dask-futures-get-stuck-in-pending-and-never-finish

After client submitted the features. can not the scheduler save those feature to process further? if we can please can you guide me this. If scheduler save those feature in sqllitedb kind of thing it will be helpful for me, instead of saving inside the variable. 
If you can guide that functionality I can code from my end as well.
Thanks @martindurant

**Comment by martindurant** [comment]
Do you mean "futures" as opposed to "features"? You could use the [publish](https://distributed.dask.org/en/latest/publish.html) mechanism to have the scheduler keep hold of your compute by name when there is no future pointing to it.

**Comment by gudipudipradeep** [comment]
@martindurant  publish mechanism helped me to hold the features.  
my workers pod are not deleting after feature execution completed and I have  death-timeout 60s..  I waited for 2hours even it is not deleted. Please can you point me the debugging to understand the case.

pod args reference for death-timeout.

`    Host Port:     <none>
    Args:
      dask-worker
      $(DASK_SCHEDULER_ADDRESS)
      --nthreads
      1
      --death-timeout
      60
      --memory-limit
      2G
      --name
      1
    State:          Running
      Started:      Tue, 23 Feb 2021 21:12:57 +0530
    Ready:          True
    Restart Count:`

**Comment by martindurant** [comment]
It seems like it's called this https://docs.dask.org/en/latest/configuration-reference.html#distributed.worker.lifetime.duration

I wasn't certain what you were asking though. Perhaps you just need to delete the published datasets? Also note, that dask-kubernetes allows you to scale the number of workers down at any time https://kubernetes.dask.org/en/latest/api.html#dask_kubernetes.KubeCluster.scale

**Comment by gudipudipradeep** [comment]
@martindurant  I have done saving published datasets, fetching and deleting the datasets. I was facing issue with kuberntes workers running from longer duration.

**Comment by ian-r-rose** [comment]
It seems like the issue was resolved.
