### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#7250]
Dask participated in the 2019 Google Summer of Code, under the NumFOCUS umbrella (see https://github.com/dask/dask/issues/4355). Should we do this again?

As before, we'd need positive answers for these two questions:
> 1. What are good self-contained projects that a novice summer student could accomplish?
> 2. Do we have people who are willing to mentor a summer student?

Personally, I'd be happy to mentor a student (or a pair of students, if they work together). It strikes me that the "dask diagnostics" idea (easier tools to identify inefficiencies) I talked about with @mrocklin & @quasiben could be worked into a reasonably scoped student project.

NumFOCUS have set up an ideas list here, if we decide to be involved: https://github.com/numfocus/gsoc/blob/master/2021/ideas-list.md

**Comment by GenevieveBuckley** [comment]
@jcrist & @martindurant do you want to say anything about how it went last time?

**Comment by jcrist** [comment]
There's honestly not much to say. We only got 2-3 applications, and decided not to select any of them.

**Comment by martindurant** [comment]
I didn't run a Dask student, but my experience with a pangeo-related on, working on xrviz, was pretty positive. I was mentoring, leading the tech side, but didn't do much admin.

**Comment by mrocklin** [comment]
I think that GSoC could be a great thing for the project.  It could also be
a time sink.  If we have people who are enthusiastic about mentorship then
I think that it's a great idea.  We're mostly mentor-constrained here.

Genevieve, if you're interested in this then I'm fully in support.  It does
require a time commitment though.

**Comment by GenevieveBuckley** [comment]
Put some first draft materials up here, Martin & I will keep working on it
* https://github.com/dask/dask/wiki/GSOC-2021-Project-Ideas
* https://github.com/dask/dask/wiki/Google-Summer-of-Code-Student-Instructions
* https://github.com/numfocus/gsoc/pull/362

**Comment by GenevieveBuckley** [comment]
This post about JupyterHub's OutReachy internships has a lot of great detail about how they created successful experiences (in particular 'micro-tasks' and a clear roadmap that gives context). https://discourse.jupyter.org/t/jupyterhubs-experience-with-outreachy-lessons-learned/4803

**Comment by freyam** [comment]
Hola @GenevieveBuckley @martindurant  :wave: 

I am applying to Dask for GSoC this year :rocket:

#7517 is the first PR I have submitted and awaiting review.

I am currently working on adding more methods from Pandas to Dask https://github.com/dask/dask/issues/1259, and as I get more acquainted with Dask, I will continue fixing more advanced issues! :tada:

**Comment by freyam** [comment]
In the meanwhile, I have also submitted a PR to `dask-tutorial`

Awaiting review https://github.com/dask/dask-tutorial/pull/211

It was a trivial Find and Replace job and I have tested it out on https://mybinder.org/ before submitting a PR.

**Comment by GenevieveBuckley** [comment]
That's great @freyam

**Comment by GenevieveBuckley** [comment]
Update: the students for google summer of code have been announced. We are very excited to have @freyam working with us this year on Dask
