### ISSUE TITLE
'DataFrame.iloc' only supports selecting columns.

### ISSUE THREAD

**Issue by arhwang12** [dask/dask#7251]
**What happened**: Error occurred as it can't index the dataframe within the specified row and column

**What you expected to happen**: Should output a single value from the specified row and column

**Minimal Complete Verifiable Example**: train_set.iloc[0,6]

```python
# Put your MCVE code here
train_set.iloc[0,6]
```

**Anything else we need to know?**: N/A

**Environment**: Spyder

- Dask version: 2.9.0
- Python version: 3.7.9
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
IIUC, the bug report / feature request here is that you can't select rows with `.iloc`? If so, that's a know limitation.

https://github.com/dask/dask/pull/6661 is a work in progress to support it.
