### ISSUE TITLE
Dataframe merge fails with KeyError

### ISSUE THREAD

**Issue by S2020BD** [dask/dask#7253]
**What happened**:
Dask optimization fails when trying to merge two dataframes

**What you expected to happen**:
The two dataframes are merged

**Minimal Complete Verifiable Example**:

```
> ddf1 = (
>     dd.read_csv(
>         "http://datasets.imdbws.com/name.basics.tsv.gz",
>          sep="\t", 
>          blocksize=None, 
>          dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
>     )
>     .repartition(partition_size="100MB")
> )
> 
> ddf2 = (
>     dd.read_csv(
>         "http://datasets.imdbws.com/title.principals.tsv.gz",
>          sep="\t", 
>          blocksize=None, 
>          dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
>     )
>     .repartition(partition_size="100MB")
> )
> 
> ddf1.merge(ddf2, on="nconst", how="inner").head()

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-077ceff9c27c> in <module>
     19 )
     20 
---> 21 ddf1.merge(ddf2, on="nconst", how="inner").head()

c:\python\python37\lib\site-packages\dask\dataframe\core.py in head(self, n, npartitions, compute)
   1040             Whether to compute the result, default is True.
   1041         """
-> 1042         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1043 
   1044     def _head(self, n, npartitions, compute, safe):

c:\python\python37\lib\site-packages\dask\dataframe\core.py in _head(self, n, npartitions, compute, safe)
   1073 
   1074         if compute:
-> 1075             result = result.compute()
   1076         return result
   1077 

c:\python\python37\lib\site-packages\dask\base.py in compute(self, **kwargs)
    279         dask.base.compute
    280         """
--> 281         (result,) = compute(self, traverse=False, **kwargs)
    282         return result
    283 

c:\python\python37\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    555     )
    556 
--> 557     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    558     keys, postcomputes = [], []
    559     for x in collections:

c:\python\python37\lib\site-packages\dask\base.py in collections_to_dsk(collections, optimize_graph, optimizations, **kwargs)
    331         for opt, val in groups.items():
    332             dsk, keys = _extract_graph_and_keys(val)
--> 333             dsk = opt(dsk, keys, **kwargs)
    334 
    335             for opt in optimizations:

c:\python\python37\lib\site-packages\dask\dataframe\optimize.py in optimize(dsk, keys, **kwargs)
     36         keys,
     37         dependencies=dependencies,
---> 38         fuse_subgraphs=fuse_subgraphs,
     39     )
     40     dsk, _ = cull(dsk, keys)

c:\python\python37\lib\site-packages\dask\optimization.py in fuse(dsk, keys, dependencies, ave_width, max_width, max_height, max_depth_new_edges, rename_keys, fuse_subgraphs)
    598             child = children_stack[-1]
    599             if child != parent:
--> 600                 children = reducible & deps[child]
    601                 while children:
    602                     # Depth-first search

KeyError: ('assign-cd39294666b9ca8e6b5b06033559949a', 46)

```python
# Put your MCVE code here
ddf1 = (
    dd.read_csv(
        "http://datasets.imdbws.com/name.basics.tsv.gz",
         sep="\t", 
         blocksize=None, 
         dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
    )
    .repartition(partition_size="100MB")
)

ddf2 = (
    dd.read_csv(
        "http://datasets.imdbws.com/title.principals.tsv.gz",
         sep="\t", 
         blocksize=None, 
         dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
    )
    .repartition(partition_size="100MB")
)

ddf1.merge(ddf2, on="nconst", how="inner").head()
```

**Anything else we need to know?**:
(did not know how to re-open previous: <a href="https://github.com/dask/dask/issues/7178">#7178</a>)
I understand version 2021.2.0 includes a fix for this (<a href="https://github.com/dask/dask/pull/7213">#7213</a>: ):
But:
I did
pip install dask[complete] --upgrade
to 2021.2.0:
dask==2021.2.0

but still get the same error. Did I miss anything?

**Environment**:

- Dask version: 2021.2.0
- Python version: 3.7.6
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
`dask==2021.2.0` does not include the changes in https://github.com/dask/dask/pull/7213, which will be included in the next release. You can install Dask directly from GitHub in the meantime (see https://github.com/dask/dask/issues/7178#issuecomment-782712229).

**Comment by S2020BD** [comment]
Please reopen per the comments in #7178 (comment)

**Comment by S2020BD** [comment]
Hello, it seems not solved per our comments. Please re-open and let us know how to address.

**Comment by jrbourbeau** [comment]
This looks to be the same as https://github.com/dask/dask/issues/7262. Is that not the case?

**Comment by S2020BD** [comment]
It is. It was just closed with the issue still present.
