### ISSUE TITLE
Dask array stack hanging

### ISSUE THREAD

**Issue by AlecThomson** [dask/dask#7255]
**What happened**:
Hi there,

I'm trying to create a multi-dimensional dask array from the results of a delayed function using `da.stack`. I'm able to construct and compute the 'sub-array', but I would like to compute the full array (see example below). When I attempt to compute the full array the task hangs, with no output in my dashboard. I could compute the sub-arrays iteratively (looping over a list of sub-arrays), but this seems sub-optimal. 

**What you expected to happen**:
I'd expect the full array to begin computing, with output to the dashboard.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da
from dask import delayed

@delayed
def delayed_function(i,j):
    # do some work
    # makes an 85 x 85 image
    return image

x, y = 85, 85
outer_list = []
for beam in range(36):
    inner_list = []
    for j in range(288):
        delayed_image = delayed_function(i, j)
        da_image = da.from_delayed(delayed_image,
                                 shape=(x, y),
                                 dtype=np.float32
                                 )
        inner_list.append(da_image)
    da_inner = da.stack(inner_list)
    outer_list.append(da_inner)
da_outer = da.stack(outer_list)

print(da_inner)
# dask.array<stack, shape=(288, 85, 85), dtype=float32, chunksize=(1, 85, 85), chunktype=numpy.ndarray>
print(da_outer)
# dask.array<stack, shape=(36, 288, 85, 85), dtype=float32, chunksize=(1, 1, 85, 85), chunktype=numpy.ndarray>

da_inner.compute()
# Runs successfully 
da_outer.compute()
# Hangs...
```

**Anything else we need to know?**:
The delay call is required in this case. It can't easily be replaced by other dask.array functions.

**Environment**:

- Dask version:
    - 2021.02.0
- Python version:
    - 3.7.10
- Operating System:
    - MacOS 10.15.7
- Install method (conda, pip, source):
    - conda

**Comment by AlecThomson** [comment]
Not sure if this is related to #5913

**Comment by jsignell** [comment]
As a workaround, I recommend using map_blocks to construct arrays rather than using from_delayed and stacking. There is a new example in https://docs.dask.org/en/latest/array-creation.html that uses `da.map_blocks` and might be useful to you.

**Comment by ian-r-rose** [comment]
Closing as answered. I think there is still work to be done on improving the experience of stacking and otherwise building up arrays from parts, but that discussion should continue in #5913, where there is more activity.
