### ISSUE TITLE
Dask dataframe merge failure

### ISSUE THREAD

**Issue by S2020BD** [dask/dask#7262]
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-077ceff9c27c> in <module>
     19 )
     20 
---> 21 ddf1.merge(ddf2, on="nconst", how="inner").head()

c:\python\python37\lib\site-packages\dask\dataframe\core.py in head(self, n, npartitions, compute)
   1040             Whether to compute the result, default is True.
   1041         """
-> 1042         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1043 
   1044     def _head(self, n, npartitions, compute, safe):

c:\python\python37\lib\site-packages\dask\dataframe\core.py in _head(self, n, npartitions, compute, safe)
   1073 
   1074         if compute:
-> 1075             result = result.compute()
   1076         return result
   1077 

c:\python\python37\lib\site-packages\dask\base.py in compute(self, **kwargs)
    279         dask.base.compute
    280         """
--> 281         (result,) = compute(self, traverse=False, **kwargs)
    282         return result
    283 

c:\python\python37\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    555     )
    556 
--> 557     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    558     keys, postcomputes = [], []
    559     for x in collections:

c:\python\python37\lib\site-packages\dask\base.py in collections_to_dsk(collections, optimize_graph, optimizations, **kwargs)
    331         for opt, val in groups.items():
    332             dsk, keys = _extract_graph_and_keys(val)
--> 333             dsk = opt(dsk, keys, **kwargs)
    334 
    335             for opt in optimizations:

c:\python\python37\lib\site-packages\dask\dataframe\optimize.py in optimize(dsk, keys, **kwargs)
     36         keys,
     37         dependencies=dependencies,
---> 38         fuse_subgraphs=fuse_subgraphs,
     39     )
     40     dsk, _ = cull(dsk, keys)

c:\python\python37\lib\site-packages\dask\optimization.py in fuse(dsk, keys, dependencies, ave_width, max_width, max_height, max_depth_new_edges, rename_keys, fuse_subgraphs)
    598             child = children_stack[-1]
    599             if child != parent:
--> 600                 children = reducible & deps[child]
    601                 while children:
    602                     # Depth-first search

KeyError: ('assign-dd829a2722acb29e253f7671e46e23b1', 45)
`
**What happened**:
Dask optimization fails when trying to merge two dataframes
**What you expected to happen**:
two big dataframes to merge properly

**Minimal Complete Verifiable Example**:
```python
# Put your MCVE code here
ddf1 = (
    dd.read_csv(
        "http://datasets.imdbws.com/name.basics.tsv.gz",
         sep="\t", 
         blocksize=None, 
         dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
    )
    .repartition(partition_size="100MB")
)

ddf2 = (
    dd.read_csv(
        "http://datasets.imdbws.com/title.principals.tsv.gz",
         sep="\t", 
         blocksize=None, 
         dtype={'isOriginalTitle': 'object', 'isAdult': 'object', 'startYear': 'object'}
    )
    .repartition(partition_size="100MB")
)

ddf1.merge(ddf2, on="nconst", how="inner").head()
```

**Anything else we need to know?**:
Please do not close this issue report until I have checked the solution worked: other tickets were prematurely closed, it takes time to open properly informed ticket:
<https://github.com/dask/dask/issues/7178>#7178</a> and <a href="https://github.com/dask/dask/issues/7253">#7253</a>
**Environment**:

- Dask version: 2021.2.0 with egg package from source including fix 
<a href="https://github.com/dask/dask/pull/7213">#7213</a>: 
02/20/2021  10:21 AM    <DIR>          dask
02/22/2021  10:22 PM    <DIR>          dask-0+unknown-py3.7.egg
02/20/2021  10:21 AM    <DIR>          dask-2021.2.0.dist-info
02/08/2021  12:25 PM    <DIR>          dask_glm
02/08/2021  12:25 PM    <DIR>          dask_glm-0.2.0.dist-info
02/08/2021  12:25 PM    <DIR>          dask_ml
02/08/2021  12:25 PM    <DIR>          dask_ml-1.8.0.dist-info
02/20/2021  03:38 PM    <DIR>          dask_yarn
02/20/2021  03:38 PM    <DIR>          dask_yarn-0.8.1.dist-info
- Python version: Python 3.7.6
- Operating System: Windows 10
- Install method (conda, pip, source): manual python install setup.py from source cloned from #7213

**Comment by S2020BD** [comment]
Can someone please advise on the above?

**Comment by jsignell** [comment]
I added `'birthYear': 'object'` to the `dtype` definitions and it seems to work fine now. I am going to close.
