### ISSUE TITLE
Data locality & fault tolerance in Dask

### ISSUE THREAD

**Issue by georgeg0** [dask/dask#7265]
We are considering the possibilities of using dask. Mainly want to do how the 

- data locality and 
- Fault tolerance 

is taken care in dask. Came across this https://github.com/dask/dask/issues/184 but it’s too old and after the recent changes in HDFS backend, does dask still takes care of data locality? And what’s the scene with the fault tolerance.

**Comment by quasiben** [comment]
Data Locality Docs:
- https://distributed.dask.org/en/latest/locality.html
- https://docs.dask.org/en/latest/scheduling-policy.html#scheduling-in-depth

Fault Tolerance:
- https://distributed.dask.org/en/latest/resilience.html
- https://docs.dask.org/en/latest/institutional-faq.html#is-dask-resilient-what-happens-when-a-machine-goes-down

**Comment by jsignell** [comment]
Closing this since I think your question has been addressed. If you have ideas about how we can better surface docs please open a pull request!
