### ISSUE TITLE
Persist fails on xarray objects but compute succeeds

### ISSUE THREAD

**Issue by djhoese** [dask/dask#7267]
**What happened**:

Tried to run persist on an xarray DataArray but it fails with an exception.

Exception:

<details>

```
----> 1 dask.persist(a)

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/dask/base.py in persist(*args, **kwargs)
    768     results = schedule(dsk, keys, **kwargs)
    769     d = dict(zip(keys, results))
--> 770     results2 = [r({k: d[k] for k in ks}, *s) for r, ks, s in postpersists]
    771     return repack(results2)
    772

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/dask/base.py in <listcomp>(.0)
    768     results = schedule(dsk, keys, **kwargs)
    769     d = dict(zip(keys, results))
--> 770     results2 = [r({k: d[k] for k in ks}, *s) for r, ks, s in postpersists]
    771     return repack(results2)
    772

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/xarray/core/dataarray.py in _dask_finalize(results, func, args, name)
    842     @staticmethod
    843     def _dask_finalize(results, func, args, name):
--> 844         ds = func(results, *args)
    845         variable = ds._variables.pop(_THIS_ARRAY)
    846         coords = ds._variables

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/xarray/core/dataset.py in _dask_postpersist(dsk, info, *args)
    873                 func, args2 = v
    874                 if is_persist:
--> 875                     name = args2[1][0]
    876                     dsk2 = {k: v for k, v in dsk.items() if k[0] == name}
    877                 else:

IndexError: tuple index out of range
```

</details>

**What you expected to happen**:

Get an xarray DataArray back with a persisted dask array underneath.

**Minimal Complete Verifiable Example**:

```python
import xarray as xr
import dask.array as da
import dask
import numpy as np

a = xr.DataArray(da.zeros((5, 5), dtype=np.float64), attrs={'test': 1})
dask.persist(a)  # exception, see above
dask.compute(a)  # succeeds
dask.persist(a.data)  # succeeds

```

**Anything else we need to know?**:

This used to work, but I have no idea when it stopped. I have a tutorial for my library that uses `dask.persist(data_arr1, data_arr2)` and just had a user tell me they got this exception.

Should I file bugs like these with xarray or dask?

CC @shoyer @jhamman @rabernat who may know more on the xarray side. If there is a better person on the xarray side who I should bring into this let me know. Or if you'd rather I just file a bug with each project when I find things like this I can do that too.

**Environment**:

- Dask version: '2021.02.0'
- Xarray version: '0.16.2'
- Python version: 3.7
- Operating System: Ubuntu
- Install method (conda, pip, source):

**Comment by jsignell** [comment]
I can reproduce with xarray 0.16.2, but when I install xarray master the issue goes away, so I presume that it has been fixed on the xarray side. Presumably by https://github.com/pydata/xarray/pull/4884. Please reopen if that doesn't solve this issue.

**Comment by djhoese** [comment]
Yup, xarray master works. Thanks @jsignell!
