### ISSUE TITLE
Groupby on dask bags does not group correctly

### ISSUE THREAD

**Issue by BorjaEst** [dask/dask#7275]
**What happened**:
Groupby on dask bags does not group correctly.

**What you expected to happen**:
When using group by, group correctly by the output key.

**Minimal Complete Verifiable Example**:
```python
from dask.distributed import Client
client = Client(n_workers=4)

import dask.bag as db

b = db.from_sequence(['Alice', 'Bob', 'Ana', 'Dan', 'Borja', 'Frank'])
b.groupby(lambda x: x[0]).compute()  # names grouped first letter
```
Produces:
```sh
[('A', ['Alice']),
 ('B', ['Bob', 'Borja']), # <-- Correct, grouped by first letter
 ('F', ['Frank']),
 ('A', ['Ana']),          # <-- Should be grouped with 'Alice' 
 ('D', ['Dan'])]
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.20.0 
- Python version: 3.8.8
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): conda (see https://github.com/dask/dask-tutorial)

**Comment by jsignell** [comment]
This is a known issue with using bag on with the distributed scheduler. Here is the ticket where the fix is being discussed https://github.com/dask/dask/issues/6723
