### ISSUE TITLE
Memory allocation error - proper way to consume available resources

### ISSUE THREAD

**Issue by piotr-rarus** [dask/dask#7300]
Hey folks

First and foremost, I'm deeply sorry to post this grumble here. Fewer people are answering on *stackoverflow* and I'm a bit hot on meeting the deadline at the university.

I've run into some memory problems while using Dask's `LocalCluster`. I'm working on a machine with 32 CPUs, but I have only 64GB RAM available. I'm instantiating the cluster like that:

```py
cluster = LocalCluster(
    n_workers=os.cpu_count(),
    threads_per_worker=1
)
```

Dask, by default, assigns an equal amount of memory per worker (total RAM divided by the number of workers).
I'm using Dask to compute research batches. Those batches differ in their need for memory. There aren't any problems when I process 32 smaller batches, as they fit into the memory. My problem comes, when I move into the heavier batches, which can't fit into 2GB of assigned available RAM. Then Dask is raising memory allocation errors and the task fails to compute. I've seen that I can increase a worker's timeout, but it's not a very elegant solution. Is there any way to tell Dask to keep the scheduled task in the queue, unless resources are available? What'd be the *correct* way to handle these tasks in the queue while using `LocalCluster`?

**Comment by quasiben** [comment]
You could maybe do something with [resources and annotations](https://distributed.dask.org/en/latest/resources.html?#example).  Instead of coming up with a queueing system you could change the spilling/memory management of the worker to spill earlier if some threshold is hit.  xref: https://distributed.dask.org/en/latest/worker.html#memory-management

**Comment by jsignell** [comment]
Seems like this is resolved, but please feel free to open a pull request if you have suggestions on how to improve the docs!
