### ISSUE TITLE
Interactive alternatives to graphviz for .visualize()

### ISSUE THREAD

**Issue by Madhu94** [dask/dask#7301]
Thoughts on improving the Jupyter display of dask objects with some of the JS libraries like cytoscape? Graphviz works, but there are some things that JS libraries do really well - like tooltips for additional data, zooming in on a section of the graph, etc.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @Madhu94! I'm not familiar with cytoscape, so I can't speak to that project specifically. Though providing a more rich graph visualization experience is certainly in scope. FWIW you might find the discussion over in https://github.com/dask/dask/issues/7141 interesting. 

cc @ian-r-rose @GenevieveBuckley @jsignell who may be interested in thinking about interactively visualizing graphs

**Comment by GenevieveBuckley** [comment]
Thanks, I'm definitely interested in this discussion (although I can't say I know anything about cytoscape)

**Comment by Madhu94** [comment]
Cytoscape was just an example:) I just wanted to start some discussion on JS libraries for .visualize(). IMO, Jupyter's full potential isn't used with graphviz.

**Comment by jsignell** [comment]
Yeah I can imagine having two versions of the visualize output kind of like we have for the dask array `repr`. I think that would be a really nice improvement.

**Comment by ian-r-rose** [comment]
Agreed, thanks for bringing thus up @Madhu94.

I haven't played with cytoscape myself, but it looks cool. Another option that might be a useful small step could be [d3-graphviz](https://observablehq.com/@magjac/introduction-to-d3-graphviz). Since it understands graphviz graphs already, it probably would be pretty easy to adapt the current visualization to use (I also like that it is pretty lightweight, producing just SVG)

**Comment by GenevieveBuckley** [comment]
> I haven't played with cytoscape myself, but it looks cool. Another option that might be a useful small step could be [d3-graphviz](https://observablehq.com/@magjac/introduction-to-d3-graphviz). Since it understands graphviz graphs already, it probably would be pretty easy to adapt the current visualization to use (I also like that it is pretty lightweight, producing just SVG)

Understanding graphviz graphs already sounds like a point in favour of d3-graphviz. But I did see that 
[there's a problem with tooltips](https://github.com/mstefaniuk/graph-viz-d3-js/issues/53) right now, which may or may not be a problem for us, depending on what we want to do.

**Comment by dhirschfeld** [comment]
On the cytoscape side there's [`ipycytoscape`](https://github.com/QuantStack/ipycytoscape) which might make it easier to integrate?

I've also come across [`ipyelk`](https://github.com/jupyrdf/ipyelk) which looks interesting, especially for me, the potential to collapse/drill down into different "jobs" running on the cluster at the same time.

**Comment by Madhu94** [comment]
Thanks @dhirschfeld, those look nice. I think plotly's Dash also has a cytoscape integration. What do you all think of summarizing the features that would be important for us and then we can do a proper evaluation around the open source ecosystem ?  

Summary of what we discussed -
* Tooltips 
* Zoom and drilldown (maybe even having the ability to lazily add nodes helps)

While features are good, but we might also look at how well funded / maintained the project is - something from the pydata ecosystem (where Quansight, Anaconda, Coiled, etc are already there) may be better.  This is just my opinion - but I'd be a bit concerned if Dask had to depend on a library with just 1-2 maintainers.

**Comment by hristog** [comment]
Just to drop another library name, which might be worthy of consideration: https://c3js.org/.
I haven't had the chance to used it yet, but gave heard positive opinions about it.

**Comment by GenevieveBuckley** [comment]
Previous discussion on visualizing large graphs: https://github.com/dask/dask/issues/1991

**Comment by freyam** [comment]
[x-posting from the slack channel]
 
I am currently working on a C project on a social media which recommends friends for a User.

I decided to use Graphviz for the visualization of the friendship network and the results came out to be pretty decent.

### **I also color-coded sub-graphs and also introduced blocks for interdependent nodes.**

![image](https://user-images.githubusercontent.com/62539811/117108930-f14c3300-ad94-11eb-9498-4f7a31a32f83.png)

![image](https://user-images.githubusercontent.com/62539811/117109276-75061f80-ad95-11eb-8be9-587e8e0faffe.png)

It's still just a static image, but it's an overall improvement over the current `Dask.visualize` as it makes more intuitive sense to color code different User groups (here, Dask Task Groups). We can add interactivity by using [`dash-interactive-graphviz`](https://pypi.org/project/dash-interactive-graphviz/) which supports
- Zooming and Panning around the graph (With a reset)
- Selecting nodes
- Animation between different graphs

Even `d3-graphviz` understands `DOT` source. So, that can be used as well.

P.S. I am currently working on bringing interactivity to my Friendship Graph. If it works, I will comment on this thread.

**Comment by martindurant** [comment]
This seems as good a place as any to put my thoughts for @freyam , following our conversation last week. His blog post about meeting the community can be found [here](https://freyam.medium.com/gsoc-journal-01-community-bonding-period-with-dask-bd2838555ac9), and the document listing some pros/cons for some graph display libraries from above is [here](https://docs.google.com/document/d/1HgmxxFyym9TCBfmJI5bB-caOKfq5J5TQbgWTgso5GIs/edit?usp=sharing). 

Immediate work areas for this week:
- to investigate the contents of a dask graph, both low-level and high-level variants, and how these get assigned properties for display with the current code in the `dot` module. What further information is available, based on the task naming conventions and e.g., for high-level graphs the number of sub-tasks and for arrays, the size of the operands. Such information might be added into the nodes as text, colour or edge-style (all probably optional).
- to have some familiarity with the distributed dashboard realtime view of the task graph: what information does the scheduler have about a task while its running, how much of this is derived from the graph itself? Please add Bokeh as one of the possible graph display libraries. Why is Bokeh problematic in the static case? What nice features does it give, which we would love for graphviz-style graphs to also have?
- read up on `client.get_task_stream` as a possible means to record the computation of a graph for post-hoc analysis. Compare with [performance reports](https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports). Could we aim to have performance information, if available, embedded in a static graph view?

As far as the libraries investigation so far, I would like to see a reformatting in terms of pros/cons, only in terns of features that are useful to us. Some examples:
- animations look nice, but what can we use them for? I can think of: comparing two graphs pre/post optimisation; comparing two graphs with/without a given step
- interactive editing of node placement is probably not useful, except on the rare occasion we want to make publication-quality output
- being able to pack/unpack areas of the graph was specifically mentioned as a nice-to-have to be able to make sense of large graphs. Can this be done with static output? Can the packed view give summary information about its contents?

One potential concrete piece of work we discussed: modifying the task graph view in the distributed dashboard to remove the useless axes labels. It is unlikely that the bokeh codebase will feature in the rest of the project, so this would be a perhaps interesting diversion.

Sorry that this is a lot of text! I hope it is not overwhelming.

PS: am I the only one that keeps writing "daskboard"?

**Comment by GenevieveBuckley** [comment]
You're not the only one @martindurant - I write "daskboard" almost every time as well!

**Comment by mrocklin** [comment]
FYI there are ongoing efforts to update visualizations of the performance information coming out of the scheduler.  See for example  https://github.com/dask/distributed/pull/4886   .  

However, what I think would be *really valuable* is not visualizing information coming out of the scheduler, like how we do with Bokeh, but instead visualizing the graph information on the client side.  No one is working on this today and it would be really helpful.

If I were managing this work I would stop investigation into visualization tools, and I would start pumping data about high level graphs into a graphviz visualization.  I think that this can have high impact *today*, and doesn't require much investigation to make serious progress.

**Comment by jakirkham** [comment]
> This seems as good a place as any to put my thoughts for @freyam , following our conversation last week. His blog post about meeting the community can be found [here](https://freyam.medium.com/gsoc-journal-01-community-bonding-period-with-dask-bd2838555ac9), and the document listing some pros/cons for some graph display libraries from above is [here](https://docs.google.com/document/d/1HgmxxFyym9TCBfmJI5bB-caOKfq5J5TQbgWTgso5GIs/edit?usp=sharing).

@martindurant the Google document linked here appears to be deleted. Do we have another copy somewhere?
