### ISSUE TITLE
2D/nD histogram support

### ISSUE THREAD

**Issue by ax3l** [dask/dask#7307]
Hi,

Are there plans to add the equivalents of the numpy
- `histogram2d`
- `histogramdd`

functions to Dask? This would be a great feature for us to process large-scale simulation data on [Summit](https://www.olcf.ornl.gov/summit/) (OLCF) and the upcoming [Perlmutter](https://www.nersc.gov/systems/perlmutter/) (NERSC) cluster.

## Background

We would like to use Dask for data analysis of particle accelerator simulations. A typical analysis of ours filters and bins columns of a DataFrame (particles) into a 2D histogram. This histogram is what we call _phase space_, if we correlates the momentum and position of the particles in a particle beam. We usually have 10^11-10^13 particles in a large simulation and our histograms are usually <=1024^2 bins.

## Refs

- https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html
- https://numpy.org/doc/stable/reference/generated/numpy.histogramdd.html

## Cross-Link

Related to meta-issue #2911 (recently discussed with @jakirkham)

**Comment by jsignell** [comment]
I haven't heard of any plans to add those functions, but if you have time to dedicate to this issue, those functions would be a welcome addition!

**Comment by douglasdavis** [comment]
Taking a stab at https://github.com/dask/dask/pull/7346

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/dask/dask/pull/7387 ), which is included in the recent release, `2021.4.0`

**Comment by ax3l** [comment]
Wuhu, thank you so much @douglasdavis for the PR and @jakirkham for the review and guidance! I'll try it tomorrow on our data! :tada:

**Comment by ax3l** [comment]
This works like a charm!! :+1: 
I tried it in a non-distributed context so far, hope to get to distributed chunks soon (https://github.com/dask/dask/issues/7475#issuecomment-815256247)

![dask](https://user-images.githubusercontent.com/1353258/113953248-3e57dc00-97cc-11eb-9dbf-6890d7c8a755.png)
[DaskOpenPMD.pdf](https://github.com/dask/dask/files/6275308/DaskOpenPMD.pdf) / [DaskOpenPMD.ipynb.zip](https://github.com/dask/dask/files/6275315/DaskOpenPMD.ipynb.zip)

**Comment by jakirkham** [comment]
Awesome thanks for sharing Axel! Nice to see all of these pieces coming together 😀

**Comment by ax3l** [comment]
Oh, that's awesome. Thanks for sharing!

**Comment by ax3l** [comment]
Hi @douglasdavis , thanks for continuously improving the histogram support, I saw your follow up PRs :star_struck: 

I just want to give you another update - finally had some time to code again and finished support for distributed dask clients:
https://github.com/openPMD/openPMD-api/pull/963#issuecomment-873350174 (with video)

**Comment by jakirkham** [comment]
That’s great Axel! 😀

Can we convince you to write up a blogpost on your use case? This would be great to include on the Dask blog 🙂 Though no worries if you are busy

**Comment by ax3l** [comment]
Thanks John! Sounds great!

I am planning to do a few scaling tests over multiple nodes at NERSC and OLCF next and then see if the operations that we typically do benefit from GPU acceleration. I would do at least the first part before reporting some intermediate results :+1:
