### ISSUE TITLE
Will dask optimize IO operation like `np.load` than `slicing`?

### ISSUE THREAD

**Issue by JiaRu2016** [dask/dask#7311]
A question related to performance optimization:
when I only need part of an array (saved on disk, in .npy format), I construct a pipeline like:
```python
a = delayed(np.load)('/path/to/np_array.npy')
b = a[1:10]
b.compute()
```
Will dask still read the whole file (maybe very large) in to memory, or only "touch" the sliced part? Actually I need lots of such `b` arrays (maybe concate them then an feed into deep learning model).  So will the compute of `b` be very slow if the npy file is very large?

**Comment by jsignell** [comment]
I think the answer is it depends on the filetype. Some file formats like parquet support this kind of chunked access. Others do not. I am closing this, but in the future please put usage questions like these in https://github.com/dask/dask/discussions
