### ISSUE TITLE
map_blocks: "MaterializedLayer' object has no attribute 'pack_annotations'"

### ISSUE THREAD

**Issue by jameslamb** [dask/dask#7331]
**What happened**:

Running the provided MCVE below, `compute()`-ing a small Dask array created with `.map_blocks()` resulted in this error

> AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

I remembered from the Dask community meeting that the annotations stuff was fairly new (or at least had recently been changed), so I tried downgrading from `dask` 2021.3.0 to `dask` 2021.2.0 and found that the error went away.

Looking more closely at my configuration, I realized that I had incompatible versions of `dask` and `distributed`.

**`dask` 2021.3.0, `distributed` 2021.2.0**

> AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

**`dask` 2021.3.0`, `distributed` 2021.3.0**

No issue

**`dask` 2021.2.0, `distributed` 2021.2.0**

No issue

**`dask` 2021.2.0, `distributed`, 2021.3.0**

AttributeError: 'HighLevelGraph' object has no attribute '__dask_distributed_pack__'

**What you expected to happen**:

I expected to be able to use `.map_blocks()` with a `lambda` to create one Dask array based on the blocks of another.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da
from distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)

dy = da.random.random((100, ), (50, ))

init_scores = dy.map_blocks(
    lambda x: np.repeat(0.8, x.size),
    dtype=np.float64
)
init_scores.compute()
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version:

<details><summary>conda info</summary>

```text
active environment : None
       user config file : /home/jlamb/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jlamb/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jlamb/miniconda3/pkgs
                          /home/jlamb/.conda/pkgs
       envs directories : /home/jlamb/miniconda3/envs
                          /home/jlamb/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.6 Linux/5.4.0-66-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): `pip`

**Comment by jameslamb** [comment]
In the process of writing up the reproducible example for this, I realized that my issue was actually incompatible versions of `dask` and `distributed`. I guess this is possible unless you're on the fairly-new versions of the `pip` resolver that are strict about versions.

I can see that `dask` does require `distributed>=2021.3.0` as of the most recent release (https://github.com/dask/dask/blob/fb544144611b25a6f23d90637038a93f93153f8f/setup.py#L25), so I don't think there's any regression here or anything that needs to be done.

I figured that out pretty far into writing this up, but decided it would still be valuable to publish the issue and then close it right away, so that others who end up in this situation and search for those error messages will find this post, and that the solution is just to make sure you have the newest `dask` and `distributed`.

**Comment by jrbourbeau** [comment]
Thanks for the write up @jameslamb!

**Comment by jameslamb** [comment]
For anyone arriving here from search, I just want to add something we just discovered over in LightGBM (https://github.com/microsoft/LightGBM/pull/4048#issuecomment-793288582). If you install `dask` and `distributed` from the default conda channels, you may hit this error mentioned above

> AttributeError: 'HighLevelGraph' object has no attribute 'dask_distributed_pack'

Because `dask` is still on 2021.2.0 there.

https://anaconda.org/anaconda/dask

![image](https://user-images.githubusercontent.com/7608904/110410787-13545e00-804f-11eb-8944-959950dd458c.png)

The fix for that is to either prefer conda-forge (`conda install -c conda-forge dask distributed`) or explicitly pin both packages (`conda install dask==2021.2.0 distributed==2021.2.0`).
