### ISSUE TITLE
Bitwise operators mask (where parameter)

### ISSUE THREAD

**Issue by MosGeo** [dask/dask#7332]
It seems that dask does not implement the `where` parameter in the bitwise operations but numpy does. It would be great to implement those to increase compatibility of the current function.

Here is the documentation in number for invert (bitwise_not)
https://numpy.org/doc/stable/reference/generated/numpy.invert.html#numpy.invert

An example in dask below would produce an error. Substituting numpy with dask would work.

```
import dask.array as da
x = da.zeros((10)).astype(np.uint8)
mask = da.ones((10)).astype(bool)
x = da.bitwise_not(x, where=mask)
```

**Comment by jsignell** [comment]
If you are interested in adding support for this please open a pull request. Otherwise, it is likely that the workaround is sufficient for now:

```python
import numpy as np
import dask.array as da
x = da.zeros((10)).astype(np.uint8)
mask = da.ones((10)).astype(bool)
da.bitwise_not(x[mask])
```

**Comment by ncclementi** [comment]
@MosGeo  Would you like to take a crack at this?

**Comment by MosGeo** [comment]
@ncclementi If you think it is a good first issue, I will take a look at it this week :)

**Comment by ncclementi** [comment]
@MosGeo that sounds great, feel free to open a PR with work in progress (add WIP to the name) and we can help you there if you need it.

**Comment by ek234** [comment]
Hey @ncclementi  
Is any work going on for this issue? I want to contribute to DASK. If no one is working on this, may I try to solve this issue?

Thanks

**Comment by MosGeo** [comment]
Hi @ek234 I kinda dropped the ball on this one. I started going through the code but to learn about dask but didn't get to the actual issue. So I dont think anybody working at it atm. You can give it a try.
