### ISSUE TITLE
Not immediately obvious: dask.dataframe indirectly depends on bz2 via pandas

### ISSUE THREAD

**Issue by hristog** [dask/dask#7340]
**What happened**: The `dask.dataframe` cannot be loaded due to an indirect dependency on `bz2`, via `pandas`. `bz2` is apparently an optional choice, when installing Python from source - please, see the references below).

Unfortunately, the resulting error message is not very helpful, because following its advice (and receiving a confirmation from `pip` that `dask[dataframe]` is already installed) doesn't improve the situation:
```
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
```

**What you expected to happen**: Successful loading of the `dask.dataframe` module.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe # also reproducible via simply: import pandas
```

**Anything else we need to know?**: I'm not entirely sure how this could be addressed in the best possible way, because it would be a bit overwhelming, if instead of the generic message referenced above, individual instructions for handling each `dask` dependency were provided to the users.
Please, feel free to close this issue, if you believe addressing it wouldn't provide sufficient value to the users.

**Environment**:

- Dask version: 2021.03.0
- Python version: Python 3.7.4
- Operating System: Xubuntu LTS
- Install method (conda, pip, source): pip

**References**:
- `bz2` as an optional dependency, in the context of `sklearn` and `joblib`: [scikit-learn #7526](https://github.com/scikit-learn/scikit-learn/issues/7526).
- `bz2` as a `pandas` dependency: [https://stackoverflow.com/questions/22346269/bz2-is-module-not-available-when-installing-pandas-with-pip-in-python-virtual](https://stackoverflow.com/questions/22346269/bz2-is-module-not-available-when-installing-pandas-with-pip-in-python-virtual).

**Comment by TomAugspurger** [comment]
bz2 is in the standard library right? It's strange that it wouldn't be available.

Regardless, this should be reported on pandas, not dask. Similar issue for lzma: https://github.com/pandas-dev/pandas/issues/27575

**Comment by hristog** [comment]
Thanks for looking into this!

Just to clarify - the issue was raised in relation to the _error message_ (`dask.distributed`-wise) that gets provided to the user. My point was that it's probably not sufficiently detailed, but also it may be tricky to make it more informative whilst keeping it concise enough.

My understanding is that `bz2` is an optional, compile-flag specific library, which is indeed part of the standard library.

**Comment by TomAugspurger** [comment]
Understood, and thanks for reporting. But my preference would be to fix it in pandas rather than work around it here.

**Comment by hristog** [comment]
Makes sense - thanks again.
