### ISSUE TITLE
.value_counts(normalize=True) Unsupported

### ISSUE THREAD

**Issue by radocisar** [dask/dask#7341]
Dask doesn't seem to support Series.value_counts(normalize=True) which is trivially supported by Pandas.

Example:
```
df = pd.DataFrame({'x': [1, 2, 1, 3, 3, 1, 4]})
a = dd.from_pandas(df, npartitions=3)
b = a["x"].value_counts(normalize=True)
```
Results in:
```
TypeError: value_counts() got an unexpected keyword argument 'normalize'
```

Can all the value_counts()'s parameters be supported by Dask, please?

**Comment by jsignell** [comment]
Dask supports a subset of the pandas space. I agree that it would likely be straightforward to implement. I am looking into it now.

**Comment by rjzamora** [comment]
>Dask supports a subset of the pandas space. I agree that it would likely be straightforward to implement. I am looking into it now.

Thanks @jsignell !  You're right that it wouldn't be difficut to divide the value-counts by the a count before returning.  It may take a bit of effort to optmize the aca algorithm to avoid a second pass over value counts (especially when `split_out`> 1), but I'm not sure how important it is to wory about that optimization.
