### ISSUE TITLE
Define Column Metadata with to_parquet

### ISSUE THREAD

**Issue by achapkowski** [dask/dask#7343]
When writing out to the `parquet` format, I want to define some column metadata.  Using pyarrow, I can write the metadata to the table using the following:

When writing out to parquet using pandas, I can create the Table using the pyarrow library, and once written, I can update the tables' metdata.  
```python
    metadata = table.schema.metadata
    metadata.update({b"geo": _encode_metadata(geo_metadata)})
```

With dask, can I somehow pass this information in above to the `to_parquet` class?

I see metadata files, but I want to define it on the table itself.

**Comment by jrbourbeau** [comment]
cc @rjzamora

**Comment by achapkowski** [comment]
A custom_metadata would be great, where you would do something like:

```python
to_parquet(...., custom_meta={'key' : 'values'})
```
