### ISSUE TITLE
Add example for loading raw binary data with memory mapping to documentation

### ISSUE THREAD

**Issue by uellue** [dask/dask#7355]
In https://docs.dask.org/en/latest/array-creation.html there are a number of examples on how to create dask arrays.

A very efficient method that is not listed yet is memory mapping. Here's an example for that, see also https://github.com/LiberTEM/LiberTEM/pull/984#issuecomment-792948584:

```python
def mmap_load_chunk(filename, shape, dtype, sl):
    data = np.memmap(filename, mode='r', shape=shape, dtype=dtype)
    result = data[sl]
    del data
    return result
    
def mmap_dask_array(filename, shape, dtype):
    chunks = []
    blocksize=5
    for offset in range(0, shape[0], blocksize):
        chunk = da.from_delayed(
            delayed(mmap_load_chunk)(
                filename,
                shape=shape,
                dtype=dtype,
                sl=slice(offset, min(offset+blocksize, shape[0]))
            ),
            shape=(min(offset+blocksize, shape[0]) - offset, ) + shape[1:],
            dtype=dtype
        )
        chunks.append(chunk)
    return da.concatenate(chunks, axis=0)
```

This method has a number of advantages:

* Zero copy, very fast data access from the file system cache
* Low memory consumption
* Lazy loading of the data, completely delegated to the operating system

This method is particularly efficient if only small subsets of the Dask array are accessed at a time since there is no overhead from allocating large chunks. Furthermore, this method is pretty insensitive to the chunking scheme for the same reason.

Technically one could also use `da.from_array()` on a `numpy.memmap()` object. However, that has a number of disadvantages compared to the `from_delayed` method:

* It does not work with `distributed` if the `Client` sees a different filesystem than the workers.
* It may share the memory map between workers or pickle it and send it over the network, which could be system-dependent and just introduces unnecessary potential for errors or undefined behavior. The example above creates the memory map on the system/worker where the data is actually needed, which should be clean in any scenario.

As a side note, the same consideration holds for the HDF5 example in the documentation. It might be cleaner to wrap the file opening in `dask.delayed` to make sure that the `h5py.File` object doesn't have to be pickled or shared. The disadvantage here would be that the HDF5 chunk cache is never shared. Since the chunk cache introduces a hidden state to a `h5py.File` object, sharing it might be a hidden case of this one: https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-global-state In any case, accessing a dataset is idempotent independent of the state of the chunk cache, so it should at least always return the desired result.

If you are interested, I could clean up the mmap case a bit, write it up for https://docs.dask.org/en/latest/array-creation.html and/or add a `da.from_raw()` method. I could also adapt the HDF5 case to only open the file in the worker processes/threads. I'm just asking beforehand since I want to make sure this would be appreciated before investing work into it.

**Comment by jsignell** [comment]
I am definitely interested in adding more examples of efficient array creation. Probably adding an example to the docs is a good first step, and if it seems to be popular, then adding a helper might make sense. That is the path that we are taking with creating an array using `map_blocks`. Ping @martindurant since I suspect you'll be interested in this.

**Comment by martindurant** [comment]
I think it would be optimistic to say that we have a concrete example of how to best do this. There is decent discussion on this at https://github.com/dask/distributed/issues/4497

For the given example, it's not obvious to me that this has an advantage over direct loading of the chunks. The function return value occupies memory just the same, and, by design, dask will not load the same chunk twice in a given computation, so it doesn't really matter is the OS cached it or not.

**Comment by uellue** [comment]
@martindurant Thx for linking to the discussion. As far as I can see, that discussion centers more around sharing data between workers, right? In this case here, the intent is just doing efficient I/O.

To show what this is about, I've appended two notebooks that compare memory mapping with conventional reading. The test simulates a common analysis for 4D STEM data: Working with the values from a specific range of pixels for all scan positions, in this case a single pixel as the most "leveraged" case. This is based on typical use of Dask arrays in this field: https://github.com/pyxem/pyxem-demos/blob/master/10%20STEM%20DPC%20Analysis%20of%20Magnetic%20Sample.ipynb

On a powerful Linux workstation with fast NVMe RAID
[read comparison Linux.ipynb.txt](https://github.com/dask/dask/files/6128341/read.comparison.Linux.ipynb.txt)

On a decent Windows workstation with a SATA SSD
[read_comparison Windows.ipynb.txt](https://github.com/dask/dask/files/6128342/read_comparison.Windows.ipynb.txt)

The test shows that on Linux, memory mapping is clearly superior for this use case, independent if the file is in the file system cache or not. The implementation of memory-mapped I/O in Windows is unfortunately not as good as on Linux: It apparently creates a large number of page faults and context switches if the data has to be loaded from storage. If the data is already in the file system cache, it is as fast as Linux.

A few detailed replies to your comments:

> The function return value occupies memory just the same

In both cases the function returns a reference to memory, but with rather different characteristics: In the normal file reading case, this is memory that is exclusive for the reading process and it always has to be filled with a copy operation. In the memory mapping case, it is a pointer to the file system cache that is shared between all processes on that system. If the file is already in the file system cache, this just creates a reference to memory that is already in use, i.e. no additional memory consumption and in particular no copy operation. If not, the operating system is free to allocate memory for the cache for  the parts of the file that are being accessed, when they are being accessed. Small Dask array chunks can, in principle do the same. However, they are associated with a lot more overhead than just letting the operating system handle it.

>  by design, dask will not load the same chunk twice in a given computation, so it doesn't really matter is the OS cached it or not.

First, the operating system doesn't even have to read the whole chunk in the memory mapping case. It only has to read the parts that are actually accessed on demad. That's why Windows is doing so poorly: Apparently it doesn't recognize the linear access pattern and doesn't read ahead, but actually triggers a costly page fault for every pixel -- they are so far apart in the file that each is in a separate memory page. Linux, however, seems to recognize the access pattern and reads ahead, thus avoiding page faults. The memory mapping case delegates a lot of the decision making to the kernel, while the reading case forces the kernel to allocate and manage additional memory for the file contents that are being read.

Second, looking at the real-world use case (not mine, by the way): It calls `compute()`  behind the scenes every time one of the interactive GUI navigation elements is changed! It should be clear that fast data access from the file system cache greatly improves the user experience in that case.

Reading from fast SSDs in cases where the data doesn't fit into the file system cache is  yet a different scenario, by the way: Direct IO is doing best here since reading from a fast SSD RAID can be almost as fast as accessing memory, and it avoids the overheads associated with constantly thrashing the cache. This could be yet another example. :-)

**Comment by jakirkham** [comment]
Admittedly I haven't read the whole thread (so maybe this already came up), but would actually suggest loading the data a bit differently. Something like this...

```python
import mmap
import numpy as np
import dask.array as da

with open(fn, "r+b") as fh:
    # `mmap` duplicates the file descriptor
    # `0` means map the full file
    mm = mmap.mmap(fh.fileno(), 0)

# coerce to NumPy array of expected type and shape
a = np.asarray(mm).view(type).reshape(shape)

# Don't call `asarray`
a_d = da.from_array(a, chunks=chunks, asarray=False)

# Do other stuff here
...
```

Hopefully saves some boilerplate while still making good use of `mmap`ing.

**Comment by uellue** [comment]
@jakirkham thank you for the example! I've tried it out in comparison to the "original" method. It seems that `np.asarray()` is taking a copy of the data since it has the same performance as the read case:

```python
(...)

def other_mmap(filename, shape, dtype, chunks):
    with open(filename, "rb") as fh:
        # `mmap` duplicates the file descriptor
        # `0` means map the full file
        mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)

    # coerce to NumPy array of expected type and shape
    a = np.asarray(mm).view(dtype).reshape(shape)

    # Don't call `asarray`
    a_d = da.from_array(a, chunks=chunks, asarray=False)
    return a_d

%%time
a = mmap_dask_array(filename, shape, dtype)
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 92 ms

%%time
a = other_mmap(filename, shape, dtype, (5, 128, 128, 128))
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 2.64 s
```

For a _threaded_ single host case, this works better since it eliminates the copy:

```python
def other_mmap_2(filename, shape, dtype, chunks):
    a = np.memmap(filename, mode='r', shape=shape, dtype=dtype)
    # Don't call `asarray`
    a_d = da.from_array(a, chunks=chunks, asarray=False)
    return a_d

%%time
a = other_mmap_2(filename, shape, dtype, (5, 128, 128, 128))
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 111 ms
```

However, with Dask.Distributed both tank since they both apparently send the whole data around the cluster instead of memory mapping it on the worker processes:

```python
c = dd.Client(n_workers=4, threads_per_worker=1, processes=True)

%%time
a = mmap_dask_array(filename, shape, dtype)
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 254 ms

%%time
a = other_mmap(filename, shape, dtype, (5, 128, 128, 128))
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 13.3 s

%%time
a = other_mmap_2(filename, shape, dtype, (5, 128, 128, 128))
# Extract the central pixel from all frames
a[:, :, 64, 64].compute()

Wall time: 10.8 s
```

**Comment by jakirkham** [comment]
It shouldn’t be copying it. NumPy’s `asarray` takes a view if anything following the Python Buffer Protocol, which includes `mmap`

**Comment by uellue** [comment]
@jakirkham Actually, it does take a copy if it is not a subclass of ndarray: https://numpy.org/doc/stable/reference/generated/numpy.asarray.html

What you mean is probably `np.frombuffer()`? https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html

**Comment by jakirkham** [comment]
That said, agree Distributed will transmit data around. It’s use case is different. Changing that is likely more involved

I think `mmap`ing works better with the threaded scheduler. It may work with the multiprocessing scheduler, but that may involve some tricks

**Comment by jakirkham** [comment]
One can feed it through a `memoryview` before giving it to `asarray` and pass `copy=False`, but no it shouldn’t copy. Also don’t think either of those should be needed

**Comment by uellue** [comment]
@jakirkham So how do you explain that your version takes so much longer? Taking a copy in the process of creating the Dask array chunks would be a reasonable assumption, no?

**Comment by jakirkham** [comment]
Relevant NumPy code

https://github.com/numpy/numpy/blob/bb7a31a6a852ecc64d3f7cffb70121fc8bef20eb/numpy/core/src/multiarray/ctors.c#L1285

**Comment by jakirkham** [comment]
All I said was it _shouldn’t_ copy. Not ruling out the potential for a bug somewhere 😉

**Comment by uellue** [comment]
@jakirkham Ok, you are actually correct about the `asarray`. I've tried it out, and it is actually the Dask function that eats up time:

```python
with open(filename, "rb") as fh:
    # `mmap` duplicates the file descriptor
    # `0` means map the full file
    mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)

%%time
a = np.asarray(mm).view(dtype).reshape(shape)

Wall time: 0 ns

%%time
da.from_array(a, chunks=(5, 128, 128, 128), asarray=False)

Wall time: 1.28 s
```

**Comment by uellue** [comment]
This is a bit funny. Apparently the NumPy array is somehow "not right"?

```python
b = np.memmap(filename, shape=shape, dtype=dtype, mode='r')

%%time
da.from_array(b, chunks=(5, 128, 128, 128), asarray=False)
```

**Comment by jakirkham** [comment]
Thanks for the update

So I think we are missing `name=False` in `from_array`. Dask does some hashing with NumPy Arrays by default which we want to avoid here

**Comment by uellue** [comment]
@jakirkham Ok, that helped!

```python
%%time
da.from_array(a, chunks=(5, 128, 128, 128), asarray=False, name=False)

Wall time: 996 µs
```

Updated function:

```python
def other_mmap(filename, shape, dtype, chunks):
    with open(filename, "rb") as fh:
        # `mmap` duplicates the file descriptor
        # `0` means map the full file
        mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)

    # coerce to NumPy array of expected type and shape
    a = np.asarray(mm).view(dtype).reshape(shape)

    # Don't call `asarray`
    # name=False to avoid hashing
    a_d = da.from_array(a, chunks=chunks, asarray=False, name=False)
    return a_d
```

**Comment by jakirkham** [comment]
Yeah `memmap` in NumPy is a bit of an odd duck, which is why I typically go through `mmap` and coerce that into a NumPy Array

**Comment by jakirkham** [comment]
Awesome thanks for the update 😀

**Comment by uellue** [comment]
Interesting about the hashing function, I learned something. :-D Do be honest, I am a bit unsure if having hashing turned on by default is such a good idea since it can be quite punishing on large data.

**Comment by uellue** [comment]
Maybe one should even have both cases as example. One "quick and dirty" with `da.from_array(numpy.memmap(...))` for threaded single host cases, and one longer one with `delayed` etc that works on multiprocessing and distributed systems.

**Comment by jakirkham** [comment]
Yeah we’ve discussed turning hashing off before ( https://github.com/dask/dask/issues/4169 ). Would be good to have your perspective there as well 🙂

Yep 2 examples makes sense. There might be ways to improve the Distributed use case more. Will mull on that a bit
