### ISSUE TITLE
Verify that Read the Docs is building after master -> main

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7361]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by jrbourbeau** [comment]
Thanks for raising this @jsignell (and @jacobtomlinson). I've gone through and pointed RTD to the `main` branch for `dask`, `distributed`, `dask-jobqueue`, `dask-image`, and `dask-stories`. Other projects like `dask-examples`, `dask-ml`, and `dask-tutorial` don't deploy their docs with RTD. We can go through and spot check other repos in the Dask org

**Comment by jakirkham** [comment]
Should we go ahead and close or is there more we'd like to do here?

**Comment by jrbourbeau** [comment]
Should be good here -- @jsignell opened up issues in other repos. Thanks for the reminder @jakirkham
