### ISSUE TITLE
Strange behavior of read_parquet when multiple big partitions are involved

### ISSUE THREAD

**Issue by muscionig** [dask/dask#7363]
Hello,
I am working with a large (very large that even only a small portion [2 partitions] does not fit in an entire single server) dataset which is saved on disk with `30` parquet partitions. Each partition weights `7GB`, but when loaded in memory and decompressed the size of a single partition is about `250-300GB`. 

Now, base on Best Practices and usual workflows I decided to read the parquet folder and launch a repartition, to split the data in smaller chucks, taking only the required columns. During this process I experienced a behavior that, to the best of my knowledge should not happen, as dask should understand how to load partition in memory by itself. 

**What happened**:
In reality, if I read the folder, dask always read multiple partitions at once. To fix this behavior I tried:
1. 1 thread only
2. 1 worker with full memory
3. pyarrow as read engine
4. fastparquet as read engine

Nothing works and `read_parquet` always read multiple files at once. I though then to wait some "restart worker" messages to give the scheduler time to understand how to better schedule the tasks, unfortunately no change (even when the number of trial is a lot higher than the default `3`).

I then moved to something that is usually discouraged, working manually on single partitions, de facto mimicking 
 what actually the scheduler should do, at least with my current understanding. When providing a single partition of the parquet files dask behaves perfectly with the following steps:
1. read_parquet
2. drop_by_shallow
3. repartition
4. reset_index
5. to_parquet

Of course this is not ideal. This workflow will create multiple folders, with multiple parquet files and Dask by itself is not suited to read this structure, which will force us to create the DataFrame `from_delayed`, writing my own code to select the partitions in memory (there is nothing wrong with `from_delayed`, but my understanding is that when I can use dask collections APIs I should use them instead of custom delayed `pandas` read operation).

As this is not the first time that, when I use Dask, I experience some issues with very large partitions that are, in my experience, always loaded in memory concurrently, I have decided to submit an issue instead of a simple question.

**Minimal Complete Verifiable Example**:

Reproducing the behavior is quite hard as a lot of data a required. Below there are the 2 versions of code that I described above.

Single `read_parquet`:
```
import dask.dataframe as dd
from dask.distributed import Client

#tried all possible combinations
client = Client(n_workers=1, processes=True, memory_limit='500GB', interface = 'eth2')

npartitions = 1000

ddf = dd.read_parquet('data/raw_parquet/', gather_statistics = True, engine = 'pyarrow')

ddf = ddf.drop([columns], axis = 1)

ddf = ddf.repartition(npartitions=npartitions)
ddf.to_parquet(save_path, write_index = False)
```
Multiple `read_parquet` manually selecting partitions:
```
import dask.dataframe as dd
from dask.distributed import Client
import glob

client = Client(n_workers=45, processes=True, memory_limit='500GB', interface = 'eth2')

npartitions = 10

partitions = glob.glob('data/raw_parquet/*.parquet')

for partition in partitions:
        ddf = dd.read_parquet(partition, gather_statistics = True, engine = 'pyarrow')
        
        ddf = ddf.drop([columns], axis = 1)

        ddf = ddf.repartition(npartitions=npartitions)
        ddf.to_parquet(save_path+partition_name, write_index = False)
```
With the second method, I can see that Dask actually launches multiple read_parquet on that single partition, reading I guess different part of the partition.

**Anything else we need to know?**:

Tested on a AWS EC2 m5.24xlarge

**Environment**:

Thinking the environment was the problem, I tested on a brand new conda env with only dask installed.

- Dask version: 2021.03.0
- Python version: 3.7
- Operating System: Red Hat 7.2.1-2
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
I suspect that @martindurant will be able to advise. I suspect you might be interested in the ``chunksize`` option.

**Comment by ncclementi** [comment]
@muscionig are you still struggling with this problem? 

@martindurant Do you have any advice?

**Comment by martindurant** [comment]
I had completely forgotten about this issue, sorry.

Firstly, there is nothing that Dask ca do about the basic chunk size ("row-group" of a parquet file) of your data - it will be read into a single dataframe partition, which will typically be much larger than the on-disc representation, and extra memory will typically be used to create it. 

In your case, you *can* handle one partition at a time, but no more, but you'd like to write it out into multiple pieces (as I understand). You method for doing this by hand is probably just fine, and you could manage the file locations after the fact - I don't particularly see a problem with this. You could achieve the same using dask's `delayed` mechanism, if you'd like Dask to handle scheduling.

To use Dask's own mthods, however, you'll want to limit the workers. You could use the single-threaded "sync" scheduler (nothing wrong with this, but writes won't parallelise), but maybe the best would be to run a single worker with a few threads, and assign [worker resources](https://distributed.dask.org/en/latest/resources.html#resources-with-collections) to the `read_parquet` call, but not to the write call. If the worker has one resource, and read requires one, you should ensure that only one partition is read at a time. Ne ones might still get read while a previous one is being written.

**Comment by ian-r-rose** [comment]
Closing this as answered, but if you feel this is not the case, feel free to ping here and we can reopen
