### ISSUE TITLE
Upstream test failures

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#7366]
Just wanted to flag that our upstream tests have a few failures again. Here's a recent build with four test failures https://github.com/dask/dask/runs/2082142688

**Comment by pentschev** [comment]
I did a bit of investigating, and none of the issues are related to #7364 .

Pandas dev branch causes the following test to fail:
```
dask/dataframe/io/tests/test_parquet.py::test_categories_unnamed_index[fastparquet]
```

Two tests fail after installing NumPy dev branch:
```
dask/dataframe/tests/test_dataframe.py::test_combine
dask/dataframe/tests/test_numeric.py::test_to_numeric_on_dask_array
```

And the last test fail with Sparse dev branch:
```
dask/array/tests/test_sparse.py::test_basic[<lambda>13]
```

All of the failing tests above happened on https://github.com/dask/dask/commit/a81a9cdc671776dca0df0b8ebd95a879765084bd, which is the commit immediately before #7364 .

**Comment by jsignell** [comment]
Yeah to be clear, I don't think our upstream tests have been passing in a very long time. I started #7180 again to start working on them.

**Comment by jakirkham** [comment]
Also seeing an HDFS failure [on CI]( https://github.com/dask/dask/runs/2114891256 )

```python
____________________________ test_read_text_unicode ____________________________
24
25
hdfs = <pyarrow.hdfs.HadoopFileSystem object at 0x7fdb0c560268>
26
27
def test_read_text_unicode(hdfs):
28
data = b"abcd\xc3\xa9"
29
fn = "%s/data.txt" % basedir
30
with hdfs.open(fn, "wb") as f:
31
f.write(b"\n".join([data, data]))
32
33
f = db.read_text("hdfs://" + fn, collection=False)
34
35
result = f[0].compute()
36
>       assert len(result) == 2
37
E       TypeError: object of type 'generator' has no len()
38
39
dask/bytes/tests/test_hdfs.py:185: TypeError
```

**Comment by jakirkham** [comment]
Actually the first time that HDFS failure shows up is commit ( https://github.com/dask/dask/commit/5a12b5403250c4e5d712e3a76456d0d6da92fe54 ). Not sure if that is related or coincidental

cc @martindurant (in case you have any thoughts here 🙂)

**Comment by jsignell** [comment]
Ok I have added `xfail` with references to the related issue for all currently failing upstream tests. So I think we should close this ticket and expect upstream tests to pass from here on out.
