### ISSUE TITLE
calculate data row shape and  increase memory!

### ISSUE THREAD

**Issue by sungreong** [dask/dask#7367]
**What happened**:

i just want to know data row shape, and execute code (len(x))
but it use many memory. 
i want to know what happen this situation

**What you expected to happen**:
my expected result 
len(x) -> use less memory(kb)

**Minimal Complete Verifiable Example**:

```python
## example
url = "https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv"
X = dd.read_csv( url, blocksize= 1* 1024 * 1024)
len(X)
```

![image](https://user-images.githubusercontent.com/22166391/110768419-90274800-829a-11eb-8139-84101eeb6372.png)

**Anything else we need to know?**:

**Environment**:

- Dask version:
  - dask                      2021.2.0
  - dask-glm                  0.2.0
  - dask-ml                   1.8.0
- Python version:  3.7
- Operating System: ubuntu
- Install method (conda, pip, source): pip?

thanks :)

**Comment by quasiben** [comment]
@sungreong I'm not sure what you are asking here ? `shape` and `len` both report the same value:

```
In [8]: X.shape[0].compute()
Out[8]: 891

In [9]: len(X)
Out[9]: 891
```

How are you measuring memory usage ?  Note you can do something like the following:

```python
In [10]: X.memory_usage(deep=True).sum().compute()
Out[10]: 322588
```

**Comment by sungreong** [comment]
i make the simple code for memory check

```
from memory_profiler import profile
import dask
import dask.dataframe as dd 
url = "https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv"


@profile
def test(url) :
    data = dd.read_csv(url)
    len(data)
    return data

test(url)
```

see the below output image.
if i use function len. increase memory

![image](https://user-images.githubusercontent.com/22166391/110808600-7d773800-82c7-11eb-9efb-cde98de3ae4f.png)

**Comment by quasiben** [comment]
My guess is that some caching has happened between the calls if they are run serially.   When I execute each function independently I see similar usage:

## len
```
 146 ❯ python test.py
Filename: test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     7     90.0 MiB     90.0 MiB           1   @profile
     8                                         def test(url) :
     9    107.0 MiB     17.0 MiB           1       data = dd.read_csv(url)
    10    108.2 MiB      1.2 MiB           1       len(data)
    11    108.2 MiB      0.0 MiB           1       return data

```

## shape[0].compute
```
 146 ❯ python test.py
Filename: test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    13     90.1 MiB     90.1 MiB           1   @profile
    14                                         def test_shape(url) :
    15    106.9 MiB     16.9 MiB           1       data = dd.read_csv(url)
    16    108.1 MiB      1.2 MiB           1       data.shape[0].compute()
    17    108.1 MiB      0.0 MiB           1       return data
```

**Comment by sungreong** [comment]
so i have a question. 
how to remove cache??

**Comment by quasiben** [comment]
you can use the `del` operator  to delete objects.  Is that what you are looking for ?

**Comment by sungreong** [comment]
> you can use the `del` operator  to delete objects.  Is that what you are looking for ?

Actually i want to know deleting the cache of all operator such as dask.ml.transformer , isna etc

And i know why this object assign many memory than expected memory

**Comment by quasiben** [comment]
How much memory do you expect to be consumed ?  

I'm sorry, I don't understand what you are asking about  when you write "the cache of all operators".

**Comment by sungreong** [comment]
i expect less than 0.1MB, because it just make object only included in row shape

What I want to is that when I use dask, I want to know how to use it without using cache

**Comment by sungreong** [comment]
same issue

https://github.com/dask/dask/issues/3247

**Comment by quasiben** [comment]
I don't think this is related to #3247.  Instead, I believe this is measuring the memory of the entire dataframe + the computation of `len`.  Instead, you can persist the data frame in memory then call `len`.  For example:

```python
@profile
def test_shape(url) :
    data = dd.read_csv(url)
    data = data.persist()
    data.shape[0].compute()
    return data
```

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    14     90.3 MiB     90.3 MiB           1   @profile
    15                                         def test_shape(url) :
    16    107.1 MiB     16.7 MiB           1       data = dd.read_csv(url)
    17    108.2 MiB      1.2 MiB           1       data = data.persist()
    18    108.3 MiB      0.1 MiB           1       data.shape[0].compute()
    19    108.3 MiB      0.0 MiB           1       return data
```

I would recommend reading the [best practices section on persist](https://docs.dask.org/en/latest/dataframe-best-practices.html#persist-intelligently)

**Comment by sungreong** [comment]
What I'm saying is that I don't want the memory increase to happen in any function, not just len.

Here too, when persisting, the memory increases, but as far as I can see, this part seems to increase linearly with the data size.

I'm asking because I want to avoid increasing memory in this way.

![image](https://user-images.githubusercontent.com/22166391/111019978-fd0b2100-8405-11eb-8179-10cffd267e37.png)

**Comment by quasiben** [comment]
It seems like you are asking for a workflow where you read in a bunch of data (read_csv) then do some work (calculate len) then delete everything.  If that's the case, great!   I would recommend reading through https://distributed.dask.org/en/latest/memory.html .  The sections on [clearing data](https://distributed.dask.org/en/latest/memory.html#clearing-data) may be particular useful for what you are trying to achieve.

**Comment by jsignell** [comment]
Closing this since it seems to be resolved.
