### ISSUE TITLE
[MAINT] Clean up import order

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7368]
In working on https://github.com/dask/dask/pull/7345 I have noticed that in some files in dask the imports are not organized in any particular way. This seems petty, but I find that organized imports help me read code more quickly.

My plan is that after #7345 merges, I'll open a PR where I just run `isort` on the whole rep. I don't really see a need to enforce this with more linters in CI, just a one-time cleanup should do the trick. 

@jrbourbeau in case you have objections.

**Comment by jrbourbeau** [comment]
Great timing! @crusaderky and I were talking about `isort` yesterday

I certainly don't have an objection to running `isort` over the codebase. FWIW I'd also be okay trying it out in CI if others have an interest. Since `isort` will apply changes in-place (like `black` does) my hope is that adding it to our `pre-commit` setup won't drastically impact the developer experience

**Comment by jsignell** [comment]
Yeah I think we could add it to pre-commit. I was seeing some things about it interacting poorly with black, but I haven't looked into it much at all. I just ran it on my branch and was pleased with the results.

**Comment by jrbourbeau** [comment]
Nice! I think there are some config settings which make `isort` and `black` play nice with each other. Here's the `isort` settings for [Xarray](https://github.com/pydata/xarray/blob/c195c2636a94b8136050d2c79c8e357740db66ea/setup.cfg#L156-L161) and [pandas](https://github.com/pandas-dev/pandas/blob/bf31347a1e82ac5e17b4d515b07e16aae738e60b/setup.cfg#L163-L175)

**Comment by jsignell** [comment]
Oh nice! Yeah I think this is the perfect thing to bake into pre-commit. Want me to open that PR?

**Comment by jrbourbeau** [comment]
Yeah, that'd be great : )

**Comment by crusaderky** [comment]
You need to add this to setup.cfg or isort and black will bicker with each other:
https://github.com/pydata/xarray/blob/6ff27cae29df7ca52416f5849f6005858c6eb1e7/setup.cfg#L156-L161
