### ISSUE TITLE
pyarrow raises ClientPayloadError when reading lots of files.

### ISSUE THREAD

**Issue by icfly2** [dask/dask#7376]
**What happened**:
Reading from an azure blob store I sometimes get a `ClientPayloadError`.

The setup is several parquet files, written with pandas not dask, in a azure blob storage container. Reading them, especially a small number (1-10) of them works fine. When reading a larger number (100-500), sometimes (too often) this error occurs.

I'm pretty sure it is from aiohttp due to a slower connection or something like that and is not caught in dask / not retried  / awaited properly. I've had a look in the source but am not familiar enough to make any further sensible analysis. Sorry.

I'm not sure if this can be handled in dask or needs a fix in aiohttp.

**What you expected to happen**:
The pd.Dataframe to be computed and returned, as does happen sometimes.

**Minimal Complete Verifiable Example**:

```python
>>> import dask.dataframe as dd
>>> blob_path = "/container/**.parquet"
>>> storage_options = {
        "account_name": storage_client.credential.account_name,
        "account_key": storage_client.credential.account_key,
    }
>>> ddf = dd.read_parquet(blob_path, storage_options=storage_options, engine="pyarrow", gather_statistics=False, **setting_args)
>>> df = ddf.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dask/base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask/base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 317, in reraise
    raise exc
  File "/usr/local/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 385, in read_parquet_part
    for (rg, kw) in part
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 385, in <listcomp>
    for (rg, kw) in part
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 604, in read_partition
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 2005, in _read_table
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 399, in _read_table_from_path
    use_pandas_metadata=True,
  File "/usr/local/lib/python3.7/site-packages/pyarrow/parquet.py", line 384, in read
    use_threads=use_threads)
  File "pyarrow/_parquet.pyx", line 1097, in pyarrow._parquet.ParquetReader.read_all
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: IOError: Response payload is not completed. Detail: Python exception: ClientPayloadError
```

**Anything else we need to know?**:

**Environment**:

```python
dask.__version__
'2021.03.0'
>>> import aiohttp
>>> aiohttp.__version__
'3.7.4.post0'
>>> import pyarrow
>>> pyarrow.__version__
'3.0.0'
>>> import azure.storage.blob
>>> azure.storage.blob.__version__
'12.6.0'
>>> import adlfs
>>> adlfs.__version__
'v0.6.3'
```
- Dask version: 2021.03.0
- Python version: 3.7.3
- Operating System: linux, python 3.7-slim docker image
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
I'm not sure how much luck we'll have debugging this from the dask side, but ping @rjzamora just in case you've seen something like this before.

**Comment by martindurant** [comment]
It sounds like this should be a retriable condition within adlfs. There are similar things in s3fs, when too many connections are active at a time and either the server closes some prematurely or something times out.

**Comment by icfly2** [comment]
So we've done some digging. It looks like the error is caused by a network setting that closes connections that were open for too long a time. So moving to a VM without that fixes that. 

An option to allow retries in `read_parquet` on dropped connections would be nice though, as connections do drop on occasion. 

The problem is that the `compute()`, ideally is called after all sorts of computations have been added to task graph, rather than just the minimal example, so a try except pattern would not be super obvious to me

**Comment by jrbourbeau** [comment]
@icfly2 you might try using Dask's [distributed scheduler](https://distributed.dask.org/en/latest/) (even on a single machine) as it allows you to specify the [number of times tasks should be retried](https://distributed.dask.org/en/latest/api.html#distributed.Client.compute)

**Comment by jsignell** [comment]
I am going to close this issue since I think there are several good paths forward.

**Comment by hayesgb** [comment]
@icfly2 -- Just curious as to how you resolved this.  I'm seeing the same thing with >50 files, and manually setting the retries in a `ddf.compute(retries=5)` does not resolve the issue for me...


Looking at the bytes stored on the dashboard, I see memory pressure one or two workers.  Following the worker logs, I'm seeing the following:
```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 3.05GB --worker memory limit: 4.21 GB
```

The warning gets repeated until the retry starts.

I'm using pyarrow==1.0.1, adlfs==0.7.0, dask==2.12 and distributed==2.30

**Comment by hayesgb** [comment]
Additional information.  Further inspection of the logs shows that, originally, the process memory is logged as: 2.97GB.  With each emitted log, the memory slowly grows until it either retries or the worker gets killed.
