### ISSUE TITLE
dask.config.set not working as described in docs

### ISSUE THREAD

**Issue by kpasko** [dask/dask#7382]
**What happened**:

![image](https://user-images.githubusercontent.com/167271/111027516-9f46ec80-83a5-11eb-8c7f-a568b495b1ec.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/167271/111027503-9229fd80-83a5-11eb-92b2-f3b4ba52172b.png)

**Minimal Complete Verifiable Example**:

```python
dask.config.set({'scheduler.work-stealing': False})
```

**Environment**:
- Dask version:  - dask=2021.3.0=pyhd8ed1ab_0, dask-core=2021.3.0=pyhd8ed1ab_0                                                                                                                                                                                        
- Python version: 3.8.8
- Operating System: OS X 11.2.1
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @kpasko. Unfortunately I'm not able to reproduce using the conda packages you specified (i.e. in a fresh environment created with `conda create -n test python=3.8.8 dask=2021.3.0=pyhd8ed1ab_0 dask-core=2021.3.0=pyhd8ed1ab_0`) or the latest `main` branch. In both cases I get:

```python
>>> import dask
>>> dask.__version__
'2021.03.0'
>>> dask.config.set({'scheduler.work-stealing': False})
<dask.config.set object at 0x7fc9a8c09310>
```

Could you confirm the version of Dask being used in your Jupyter session with `dask.__version__`?

**Comment by kpasko** [comment]
can confirm it was '2021.03.0' within the kernel that was erroring. tried in a fresh kernel however, also returning '2021.03.0' and it seemed to no longer be an issue, so going to assume it was some minor conda-forge version update/mismatch on my end -- closing.
