### ISSUE TITLE
[Discussion] Employ repository dispatch events to trigger CI jobs in dependent repos

### ISSUE THREAD

**Issue by hristog** [dask/dask#7385]
**Question:**
Would it be possible to employ repository dispatch events to trigger CI jobs in dependent repositories within the Dask organization?

**Background:**
For instance, a number of `dask-ml` (and other dependent on `dask` repos) tests started failing as a result of https://github.com/dask/dask/pull/7183. In the most general case, some changes may be needed in either/both repositories to ensure smoother co-development.

Employing repository dispatch events, e.g. upon a commit to the Dask `main` branch, could notify dependent repositories to act upon the event, and execute a CI run, for example, for the purpose of enabling enhanced visibility over the extended impact of the newly-committed changes.

One possible alternative may be to execute CI runs in dependent repos (within the Dask organization), as part of PR creation in the `dask` repository.

**References:**

- docs.github.com: [Repositories -> Create a repository dispatch event](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event).
- stackoverflow.com: [GitHub Action Repository Secrets & how to secure client_payload repo dispatch event Azure Container Registry](https://stackoverflow.com/questions/62762385/github-action-repository-secrets-how-to-secure-client-payload-repo-dispatch-ev).
- github.community: [Triggering by other repository](https://github.community/t/triggering-by-other-repository/16163).

**Comment by jrbourbeau** [comment]
Thanks for bringing this up @hristog! Making sure changes to Dask don't break downstream projects is certainly an important goal.

One useful pattern we've seen is having downstream projects test against the development version of Dask (and other dependencies) in their own CI. Then when an issue arises, which typically happens at a relatively low frequency, they open an upstream issue in the Dask issue tracker informing the rest of the community. While this approach does make things a bit more reactive than proactive, it tends to have a smaller maintenance burden and has done a good job in practice.

Several projects in the Dask org, e.g. distributed, dask-kubernetes, dask-cloudprovider, etc., as well as projects outside the Dask org, e.g. Xarray, sgkit, RAPIDS, etc., all already do this type of upstream testing. In fact, dask-ml itself already has an upstream CI build where we [test against the nightly version of scikit-learn](https://github.com/dask/dask-ml/blob/c964587bedd9abf29cb3065369ccf9f437c8e3eb/ci/posix.yaml#L55-L60). I'll propose we should generalize that dask-ml CI build by adding other important dependencies like dask and distributed. That would have, for example, caught any regression introduced by https://github.com/dask/dask/pull/7183.

**Comment by hristog** [comment]
Hi @jrbourbeau! Thanks for the detailed response! It does make sense, yes.

> I'll propose we should generalize that dask-ml CI build by adding other important dependencies like dask and distributed. 

Yes, please. I'm closing this issue as rejected. I'll leave it up to you to decide whether you'd prefer to re-open it, for the sake of having it as a reminder for the `dask-ml` proposal.
