### ISSUE TITLE
add readthedocs builds in PR

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#7395]
I think this can be configured in readthedocs. I know xarray has it but I don't think there is any code for it on github. You can only see it on open PRs e.g. bottom of https://github.com/pydata/xarray/pull/5031

**Comment by jrbourbeau** [comment]
Thanks for the suggestion @raybellwaves. We already have a documentation build on PRs to ensure that they can be built successfully. However it looks like the readthedocs builds do this as well as provide a preview of the docs for each PR -- which is really useful. Today maintainers have to checkout a PR locally and then build the docs themselves, so automating this in a CI build would definitely add value. 

If there are no objections, I'll plan to play around with adding readthedocs PR builds this afternoon

**Comment by raybellwaves** [comment]
May be somewhere in here. I forget

![Screen Shot 2021-03-15 at 1 24 45 PM](https://user-images.githubusercontent.com/17162724/111194697-d24dd380-8591-11eb-986d-5b3d39fa34f4.png)

**Comment by keewis** [comment]
the option is in "Advanced Settings"

**Comment by jrbourbeau** [comment]
Thanks for the tips @raybellwaves @keewis. I opened up a PR over in https://github.com/dask/dask/pull/7397 which demonstrates that the readthedocs build is working (🎉 ) and removes our existing GitHub actions doc build
