### ISSUE TITLE
Is this check needed?

### ISSUE THREAD

**Issue by parisholley** [dask/dask#7434]
https://github.com/dask/dask/blob/e00f2fa2a8cb4c971dafc1f7b4c45caf53165879/dask/dataframe/io/parquet/arrow.py#L1090-L1094

I have run into this problem with legacy data sitting in an S3 bucket. Is there any reason we couldn't just intersect the two lists?

**Comment by jrbourbeau** [comment]
cc @rjzamora

**Comment by rjzamora** [comment]
This is a good question @parisholley.  I will think about this (and @martindurant  may have good feedback), but it would be helpful to know a bit more about the data:  I assume that you are reading hive-partitioned data.  How was the data written?  Does the data include "pandas metadata"? Does the data include a global "_metadata" file?  Could you share a simple reproducer (even if it is as simple as `read_parquet(<directory-path>)`)?

**Comment by martindurant** [comment]
I assume you have a situation like
```
- data.parquet/field=A/part.parquet
- data.parquet/field=B/part.parquet
```
and that the parts also include a column called "field". In this case, how is dask to know whether "field" refers to the value encoded in the path or the values within the data files? We have chosen to error rather than try to guess the right thing to do. 

Note that you can still load this data using
```
dd.concat([dd.read_csv(path) for path in paths])
```
(here, we choose the in-file version of "field").

**Comment by parisholley** [comment]
no external metadata files

in my case, this data was formed via a datalake vendor using glue, the hive meta is casting the field=A/B as string/int/etc, and it is represented as the same data type in the values.

i could see how there is concern on the data types differing, but that feels like a way less probable edge case.

in my particular use case, regardless of any type conflicts, i don't even care about the fields it is complaining about. eg: when I do `read_parquet(columns=[d,f,g])`, i'm not even asking/filtering on a/b, but the logic is comparing against the raw scanned schema, vs the fields I actually care about.

**Comment by martindurant** [comment]
> i could see how there is concern on the data types differing, but that feels like a way less probable edge case.

I meant the values, but that too

> i'm not even asking/filtering on a/b, but the logic is comparing against the raw scanned schema, vs the fields I actually care about.

I see - I agree that the check should be skipped when the fields that might be problematic are not even needed.

**Comment by ian-r-rose** [comment]
The check in question seems to have been removed in #6534. Closing as resolved. If you feel that's not the case, please let us know and we can re-open!
