### ISSUE TITLE
Should `map_overlap` skip `trim` if `depth` is not equal to zero?

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#7435]
This is possibly a silly question, but do we need to trim the result in `map_overlap` if the keyword argument `depth=0`?

https://github.com/dask/dask/blob/e00f2fa2a8cb4c971dafc1f7b4c45caf53165879/dask/array/overlap.py#L803

I wonder if it should be something like this instead:
```python
if trim and depth != 0:
    # ... continue as usual
```

I had expected these two examples to reduce down to the same thing.

```python
def myfunc(x):
    return x + 1

arr = da.from_array(np.ones((2, 4)).astype(int), chunks=2)
arr
```
![image](https://user-images.githubusercontent.com/30920819/111938574-6550b580-8b1e-11eb-9a26-01aed45a9c15.png)

```python
# Example 1 
res1 = arr.map_blocks(myfunc)
res1.visualize()
```
![image](https://user-images.githubusercontent.com/30920819/111938491-363a4400-8b1e-11eb-8253-3f04f148064b.png)

```python
# Example 2
res2 = arr.map_overlap(myfunc, depth=0)
res2.visualize()
```
![image](https://user-images.githubusercontent.com/30920819/111938502-3e927f00-8b1e-11eb-8a79-11d5e119221c.png)

I know you can explicitly tell it `trim=False`, but I'm pretty sure those tasks aren't actually doing anything anytime `depth=0` (which is the default value).

In practice I don't think this is especially significant, since people generally use `map_overlap` when they want things overlapping (i.e. `depth` not equal to zero). I just came across this while I was trying to wrap my head around how `map_overlap` worked.

**Comment by mrocklin** [comment]
If depth=0 then map_overlap should probably just default to map_blocks?  I
don't see a good use case for map_overlap when depth=0.

**Comment by jsignell** [comment]
depth is set to None by default so if this seems like something that people run into, we could raise an exception if it is explicitly set to 0 and in the exception point out that they should use `map_partitions` instead.

**Comment by jakirkham** [comment]
Yeah if `depth` is computed as a function of something else (maybe in relation to a filter size), it may not be know until `map_overlap` is called. Special casing this to be `map_blocks` or dropping the `trim` step both seem like reasonable solutions/optimizations to apply at that point
