### ISSUE TITLE
dd.from_sql_table() duplicates index with SQLAlchemy==1.4.1

### ISSUE THREAD

**Issue by McToel** [dask/dask#7436]
When using `dd.from_sql_table(index='index_col')` (note that index is a string), the function internally duplicates the index, if it is already in columns. This is due to this code always being executed if index is of type str as columns contains sqlalchemy columns and not strings.
```python
if index_col not in columns:
        columns.append(
            table.columns[index_col] if isinstance(index_col, str) else index_col
        )
```
This was no problem so far because older versions of SQLAlchemy automatically removed this additional column. In version 1.4.1 however, the additional column gets an alias ("index_col__1") instead of being dropped. The extra column results in a meta error, if meta is specified.

To fix this, I think it should be enough to change the snippet from above to the following
```python
if index not in columns:
        columns.append(
            index
        )
```
As `index` is a sqlalchemy column.

I could test this and make a PR.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @McToel! `sqlalchemy=1.4.0` introduced changes which impacted both Dask and pandas (for example, see https://github.com/dask/dask/issues/7406). For the time being I'd recommend using `sqlalchemy<1.4`.

cc @dask/io

**Comment by mgorny** [comment]
(and there are packages that require sqlalchemy 1.4+ already)

**Comment by mgorny** [comment]
sorry, wrong bug.
