### ISSUE TITLE
add repartition parameter(s) for to_parquet

### ISSUE THREAD

**Issue by kpasko** [dask/dask#7446]
df.to_parquet allows for multiple partition_on

`myframe.to_parquet(filename, partition_on=['col1','col2'],...)`

will result in filename/col1=xyz/col2=123/.....

however it would be helpful to be able to specify the size/number of partitions within col2, e.g.

`myframe.to_parquet(filename, partition_on=['col1','col2'],...)`

Output -- filename/col1=xyz,col2=123/part.0.parquet @ ~400MB

vs 

`myframe.to_parquet(filename, partition_on=['col1','col2'],partition_size="100MB",...)`

 Output -- [ filename/col1=xyz,col2=123/part.0.parquet, filename/col1=xyz,col2=123/part.1.parquet, filename/col1=xyz,col2=123/part.2.parquet, filename/col1=xyz,col2=123/part.3.parquet]  @ 4x~100MB

or similar with n_partitions

**Comment by kpasko** [comment]
I was assuming that partition_on would modify the prior partitioning scheme, but from what it sounds like it creates sub partitions from that original 'n-MB' repartitioning? 

Alternatively I suppose this would achieve what I'm after, tho I'm not sure about speed issues
df.shuffle(on=['col1','col2']).repartition(partition_size='100MB').to_parquet(...)

**Comment by jsignell** [comment]
> it creates sub partitions from that original

Yeah that's right. As an example you can mess around with the dask timeseries data:

```python
import dask

ddf = dask.datasets.timeseries()
ddf.to_parquet("timeseries.parquet", parition_on="name")
```
You'll see that you end up with a dir for each name and within each dir, a file for each of the original partitions (in this case one for each day).

**Comment by jsignell** [comment]
I'm going to close this for now since I don't think there are any concrete action items, but please reopen if you plan to work on this!
