### ISSUE TITLE
Promote dd.core.Scalar to dd.Series without forcing computation

### ISSUE THREAD

**Issue by gerrymanoim** [dask/dask#7458]
I have some user defined functions that return a `dd.core.Scalar`. However, I'd like to promote the result to a `dd.Series`, similar to how you can wrap a scalar in a regular `pandas.Series`. At the moment, I don't see any way to do this besides explicitly calling `.compute()` to materialize the scalar, put this into a `pandas.series` and then calling `dd.from_pandas`. 

I don't believe this already exists, but let me know if I've missed something. 

A contrived example that returns a `dd.core.Scalar`:
```
df = dd.from_pandas(pd.Series([10.0]), npartitions=1)
dd.map_partitions(sum, df)
```

**Comment by jsignell** [comment]
I think you are on the way to answering your own question :) You can write a function that takes in the scalar and constructs a `pandas.Series` and then use `map_partitions` to call that function so that you don't have to materialize the scalar in the client.

**Comment by gerrymanoim** [comment]
@jsignell - maybe I'm missing something, but that seems to lead to a type error:

```python
(Pdb++) result
dd.Scalar<series-..., dtype=float64>
(Pdb++) result.compute()
45.45
(Pdb++) dd.map_partitions(lambda x: pd.Series([x]), result, meta=pd.Series([], dtype="float64"))
*** TypeError: Expected meta to specify scalar, got pandas.core.series.Series
Traceback (most recent call last):
  File "/home/g/miniconda3/envs/ibis/lib/python3.8/site-packages/dask/dataframe/core.py", line 5327, in map_partitions
    return Scalar(graph, name, meta)
  File "/home/g/miniconda3/envs/ibis/lib/python3.8/site-packages/dask/dataframe/core.py", line 120, in __init__
    raise TypeError(
(Pdb++) 
```

Specifically it looks like https://github.com/dask/dask/blob/main/dask/dataframe/core.py#L5568 special cases all arguments being `Scalar`s and forces a `Scalar` to be constructed. 

If I do something like 

```python
dd.map_partitions(lambda x, _: pd.Series([x]), result, 0,  meta=pd.Series([], dtype="float64"))
```

`dfs` here https://github.com/dask/dask/blob/main/dask/dataframe/core.py#L5555 is empty causing an `IndexError` here https://github.com/dask/dask/blob/main/dask/dataframe/core.py#L5623. 

Which led me to this solution, which did work:

```python
empty = dd.from_pandas(pd.Series(), npartitions=1)
dd.map_partitions(lambda x, _: pd.Series([x]), result, empty,  meta=pd.Series([], dtype="float64"))
```

Which correctly gives you a `pd.Series` with one element:

```
0    45.45
dtype: float64
```

**Comment by jsignell** [comment]
Nice! I think both the `map_partitions` and the `from_delayed` solution look pretty good.

**Comment by jsignell** [comment]
I'm going to close this since it seems like you have a solution that works. But if you would like to propose a change to the docs or to the codebase please open a pull request!
