### ISSUE TITLE
Array: Slightly More Complex Chunks

### ISSUE THREAD

**Issue by ax3l** [dask/dask#7475]
Hi,

I am reading through the chunking options in
- https://docs.dask.org/en/latest/array-chunks.html
- https://docs.dask.org/en/latest/array-api.html?highlight=from_array#other-functions

I want to read pre-chunked boxes of 2D and 3D arrays from disk with [openPMD-api](https://github.com/openPMD/openPMD-api/pull/935#issuecomment-800844453).

Looking at the options above, I think I need slightly more complex chunking than what I can find documented: our chunks are not regular along an axis, but even option 3 (links above) with explicit chunks seems to assume this. Here is an example how our chunks might look in 2D:
```
shape: (10, 10)
box 1: [0: 3, 0: 3]
box 2: [0: 3, 3:10]
box 3: [3: 6, 0: 6]
box 4: [6:10, 0: 3]
box 5: [6:10, 3: 6]
box 6: [3:10, 6:10]
```
(Please assume the index examples above correspond to way larger chunks. Our chunk sizes are well suited to the file system & data subfile location and node capacity when actually reading them.)

Is there a way to support this in Dask, e.g. by passing a list of slices or explicit chunk extents to `from_array` or the `Array` constructor? This would be fantastic, since it would help us a lot reading enormous data sets from disk on U.S. Exascale machines.

cc @jakirkham maybe? :)

**Comment by ax3l** [comment]
This is a visualization of our distribution in index space, in case this helps (not exactly the same slices as given above, just doodling here):
![dask_chunks](https://user-images.githubusercontent.com/1353258/112695934-23877e00-8e42-11eb-8e8d-451d873188cd.png)

**Comment by jakirkham** [comment]
Maybe one could use [Dask Array's `block`]( https://docs.dask.org/en/latest/array-stack.html#block ) to put together chunks in the desired way?

**Comment by ax3l** [comment]
Thank you for the pointer!

Trying this https://docs.dask.org/en/latest/array-api.html#dask.array.block
```py
import dask.array as da
import numpy as np

b1 = da.from_array(np.zeros((3, 3)))
b2 = da.from_array(np.zeros((3, 7)))
b3 = da.from_array(np.zeros((3, 6)))
b4 = da.from_array(np.zeros((4, 3)))
b5 = da.from_array(np.zeros((4, 3)))
b6 = da.from_array(np.zeros((7, 4)))

data = [[b3], [b4,b5]]
x = da.block(data);
x.shape
# (7, 6)

b6.shape
# (7, 4)

# ... hm, tricky to combine further :)
```

> Blocks in the innermost lists are concatenated along the last dimension (-1), then these are concatenated along the second-last dimension (-2), and so on until the outermost list is reached

Somehow this gets tricky for blocks that span multiple dimensions...

**Comment by jakirkham** [comment]
One thing that I've done before is to create `np.empty(..., dtype=object)` arrays and filled them with the different Dask Arrays that I would like to pass to `da.block` (making sure to call `.tolist()` on the NumPy object array first).

Though this may still have limitations for the use case envisioned here. Perhaps judicious use of Dask Arrays with `0` lengths along some dimensions can help regularize this a bit?

**Comment by mrocklin** [comment]
Dask array does not support fully arbitrary chunking.  I think that it is
unlikely that it will ever do so.  The complexity involved in implementing
this would require a more-or-less full rewrite of most of the algorithms.

More complex chunking is a fully valid use case, just not one that I think
it makes sense for us.

**Comment by jakirkham** [comment]
Well I'm not sure to what extent arbitrary chunking is needed throughout the workflow as opposed to simply a way to compose data from disk into a form that Dask can consume. Currently my operating assumption is the latter and not the former. Agree the former is difficult

**Comment by benjha** [comment]
Hi @ax3l, I am curious about your chunk layout. 

Does this layout come from how the simulation code partitions the spatial domain ? if so, is it ok to assume chunk 1 was written by let's say MPI process 1, chunk 2 by MPI process 2 and so on ? Is it correct to assume that even the chunks are larger than others, do they have  the same amount of elements ?

**Comment by ax3l** [comment]
Thank you for the feedback and details!

Our data is from large-scale simulations that compose multiples of a fundamental block size dynamically into grids and assigning one or more grids to MPI ranks ([AMReX](https://amrex-codes.github.io/amrex/docs_html/ManagingGridHierarchy_Chapter.html) details; note that we talk about the coarsest MR level at the moment). As these grids move around, the domain decomposition over MPI ranks can become [quite colorful](https://warpx.readthedocs.io/en/latest/usage/workflows/plot_distribution_mapping.html).

In I/O, the grids become "chunks" in scalable I/O routines, i.e. [ADIOS2](https://github.com/ornladios/ADIOS2). ADIOS2 uses a subfiling approach in which chunks from one or a group of aggregated ranks go into a physical file. During reads, we have the capability to restore these chunks from meta-data - if we read in chunks back that we know are well mapped to physical layout then we can avoid a lot of meta-data operations from sub-filing (e.g. open/close) as well as unnecessary seeking through overly split 3D array data on disk.

I created a relatively simple approach now that sub-splits chunks over the whole domain by smallest common chunks along an axis. This thus opens and reads some sub-files multiple times for now, but we can get data into the Dask chunking model: https://github.com/openPMD/openPMD-api/pull/952

Now the next trick to pull off is to make our reader objects pickle-able so we can do multi-node worker reads. How did you work-around that in `h5py`/HDF5?

**Comment by jakirkham** [comment]
Thanks for the update Axel! Glad you were able to get something working here 😄

Yeah I think we discussed this a few weeks back, but I think this probably happens in phases. Namely the first step is to get the whole workflow working with Dask. My guess is there are still lots of things we need to iterate on after that, but I think that will be easier to see after being able to run all the way through and seeing data from the Dask dashboard and perhaps collecting [performance reports]( https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports ) for a few cases. Not to mention this is still on CPUs atm and so we haven't transitioned to using GPUs yet. So yeah there's likely more work to do here to get the performance up, but that should be easier to see once we are able to run end-to-end with Dask 🙂

**Comment by ax3l** [comment]
Thanks John, that's also my plan :slightly_smiling_face: 

For getting into the distributed setting: are there more details to the `h5py` tricks that Matthew mentioned in the SO that we could also make use of or should I follow the plan described above? If there is a persistent way to keep workers that are responsible for reading data alive and pass chunks to them without shutting down their I/O-library "file" handles, that would certainly be useful for us. But maybe you used another trick.

**Comment by ian-r-rose** [comment]
This discussion appears to have reached a conclusion. @ax3l if you feel that there are unresolved issues, please let us know and we can reopen.
