### ISSUE TITLE
partition_info contains incorrect information with distributed scheduler

### ISSUE THREAD

**Issue by bnaul** [dask/dask#7488]
Run on dask+distributed main
```
# Correct behavior w/ local scheduler
ddf = dd.from_pandas(pd.DataFrame({"a": range(12)}), npartitions=2)
print(ddf.map_partitions(lambda x, partition_info=None: partition_info).compute(scheduler="threads"))

0    {'number': 0, 'division': 0}
1    {'number': 1, 'division': 6}
dtype: object
```

```
# Incorrect behavior w/ distributed
import distributed; client = distributed.Client()
ddf = dd.from_pandas(pd.DataFrame({"a": range(12)}), npartitions=2)
print(ddf.map_partitions(lambda x, partition_info=None: partition_info).compute())
0    {'number': 0, 'division': 0}
1    {'number': 0, 'division': 0}
dtype: object
```
I also checked and `test_map_partitions_partition_info` from #6776 fails when using the distributed scheduler.

Dug around a little bit but nothing obviously wrong jumped out at me. cc @jsignell @jrbourbeau @kumarprabhu1988 from that PR.

**Comment by jsignell** [comment]
Yeah I can reproduce. My first thought is maybe the whole task graph isn't passed to each worker, and that leads to `number` being wrong.

**Comment by bnaul** [comment]
Thanks @jsignell, that does seem right based on the graph objects I was seeing in a debugger. One more piece of info, I did a `git bisect` and I believe this was introduced in https://github.com/dask/distributed/pull/4489; @madsbk does this issue / @jsignell's diagnosis make sense to you? Any way we can work around it?

**Comment by madsbk** [comment]
I don't know why this worked before  dask/distributed#4489 but https://github.com/dask/dask/pull/7524 should fix it :)
