### ISSUE TITLE
Unable to append dataframe using .to_parquet if column contains a dictionary/structure

### ISSUE THREAD

**Issue by toby-coleman** [dask/dask#7492]
**What happened**: Saving a dataframe using `.to_parquet(path, append=True)` fails when one of the columns contains a dictionary. Raises: `ValueError: Appended columns not the same.`

**What you expected to happen**: Expected to be able to append parquet datasets (this works if using simple column types).

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

dts = pd.date_range('2020-01-01', '2021-01-01')
df = pd.DataFrame(
    {'value': [{'x': x} for x in range(len(dts))]},
    index=dts
)
print(df.head())

ddf = dd.from_pandas(df, npartitions=1)

# This works:
ddf.to_parquet('/tmp/test_parquet', append=True)

# Can successfully read data
print(dd.read_parquet('/tmp/test_parquet').head())

# This fails:
ddf.to_parquet('/tmp/test_parquet', append=True)
# ValueError: Appended columns not the same.
# Previous: ['x', '__null_dask_index__'] | New: ['__null_dask_index__', 'value']
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.03.1
- Python version: 3.7.10
- Operating System: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Install method (conda, pip, source): pip (using Google Colab)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @toby-coleman. Are you using `fastparquet` or `pyarrow`? Also what version of the parquet engine library are you using? 

cc @dask/io

**Comment by toby-coleman** [comment]
I'm using `pyarrow` version `3.0.0`.

**Comment by martindurant** [comment]
You may want to try with v2.x for now

**Comment by toby-coleman** [comment]
Just tried it on `2.0.0` and I get the same thing.

**Comment by rjzamora** [comment]
Thanks for raising this @toby-coleman - I don't think there is any test coverage for dictionary-column types, so I am not surprised that there are issues. I don’t think this is working for me with fastparquet or pyarrow locally, but the pyarrow failure seems like it should be easy to address.

**Comment by jorisvandenbossche** [comment]
> You may want to try with v2.x for now

@martindurant side question: is there a specific reason you recommend v2.x for now? Just to be sure that if there were issues with 3.0, we have addressed them in the upcoming 4.0 release (as this is targetted for next week)

**Comment by martindurant** [comment]
Only because 3 is new, and this is the quickest way to check whether it's the new version which made the difference. I have no particular reason to suspect it.

**Comment by rjzamora** [comment]
>Only because 3 is new, and this is the quickest way to check whether it's the new version which made the difference. I have no particular reason to suspect it.

Yup - I don't think I have seen any *real* pyarrow-3 problems, you guys are great about testing against Dask @jorisvandenbossche !  Even so, it typically makes sense to *consider* the parquet-engine backend when there is a perceived change in behavior.

**Comment by jorisvandenbossche** [comment]
OK, perfect (I was just wondering ;))
