### ISSUE TITLE
Error using read_parquet to read data from gs

### ISSUE THREAD

**Issue by ahah-figure** [dask/dask#7495]
I'm attempting to read parquet files from gs into memory on a gcp VM. Code snippet is below.

```python
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()
client = Client(cluster)

src_path = "gs://..."
load_cols = []  # something like 300 columns out of 2000 total columns

df = dd.read_parquet(
    src_path + "/*.parquet",
    columns=load_cols,
    gather_statistics=False,  # had to disable this because it was super slow
    index=False,
    engine="fastparquet"  # pyarrow didn't help
)
df = df.compute()
```

When I watch the dashboard, it appears that all the parquet files get read, but I get the following error:

```
~/miniconda3/lib/python3.7/site-packages/distributed/protocol/serialize.py in pickle_loads(header, frames)
     73     for i in range(len(buffers)):
     74         mv = memoryview(buffers[i])
---> 75         if writeable[i] == mv.readonly:
     76             if mv.readonly:
     77                 buf = memoryview(bytearray(mv))

IndexError: tuple index out of range
```

Not sure if it helps, but if I parallelize pandas.read_parquet using multiprocessing.imap_unordered on the individual parquet files, everything works fine. In memory, the DataFrame is about 60 GB. I tested this on a VM with 3.7 TB of RAM and 160 cores. Also, the parquet files were generated by pyspark.

Environment is:
- Dask version: 2021.03.1
- Python version: 3.7.10
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ahah-figure. This was reported over in https://github.com/dask/distributed/issues/4645 and we're working to incorporate a fix. If you'd like to engage on that issue, that would be welcome
