### ISSUE TITLE
Using Loky with Dask

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#7511]
[Loky]( https://github.com/joblib/loky ) supplies a [`concurrent.futures.Executor`]( https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor ) that provides an alternative to the Python builtin [`ProcessPoolExecutor`]( https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor ) (so handling the Multiprocessing use case) with a number of improvements. As Dask can now use arbitrary `concurrent.futures.Executor`s with the local scheduler, it might be worth showing an example of how Dask can be used with Loky both for users wanting to use Loky as well as users want to try their own Executor with Dask

**Comment by jakirkham** [comment]
cc @tomMoral @ogrisel @pierreglaser (in case this is of interest)

**Comment by jakirkham** [comment]
Here's a simple example

```python
from loky import get_reusable_executor

import dask
import dask.array as da


a = da.ones((1_000, 1_100), chunks=100)
r = a.sum()

pool = get_reusable_executor()
dask.config.set(pool=pool)

a.compute()
```

**Comment by ncclementi** [comment]
I'll be taking this one.

**Comment by jrbourbeau** [comment]
Great, thanks @ncclementi!
