### ISSUE TITLE
Appending parquet datasets to Google Cloud can make data unreadable

### ISSUE THREAD

**Issue by toby-coleman** [dask/dask#7522]
**What happened**: Write a parquet dataset to GCS storage with `append=True`, read it back, write it again, then the data cannot be read. Error reported is: `ArrowInvalid: Some index in row_group_indices is 1, which is either < 0 or >= num_row_groups(1)`

**What you expected to happen**: Data should be readable.

**Minimal Complete Verifiable Example**:

See also this [Colab notebook](https://colab.research.google.com/drive/1CQDEy_nlWhvJ1oO1W-OmdFGneGJUs7Hp?usp=sharing)

```python
import dask.dataframe as dd
import pandas as pd

# Sample dataframe
dts = pd.date_range('2020-01-01', '2020-01-10')
df = pd.DataFrame(
    {'time': dts, 'value': list(range(len(dts))), 'year': dts.year}
).set_index('time')
ddf = dd.from_pandas(df, npartitions=1)

token = ... # Authenticate to Google Cloud here

path = 'gs://my-bucket/bugtest/abc' # Edit this

# Write to GCS storage
ddf.to_parquet(path, append=True, engine='pyarrow', storage_options={'token': token}, partition_on='year', ignore_divisions=True)

# Read back from GCS storage
print(dd.read_parquet(path, storage_options={'token': token}).compute().head())

# Write to GCS storage again
ddf.to_parquet(path, append=True, engine='pyarrow', storage_options={'token': token}, partition_on='year', ignore_divisions=True)

# Read back from GCS storage (this fails)
print(dd.read_parquet(path, storage_options={'token': token}).compute().head())
```

**Anything else we need to know?**: The problem does not occur if I remove `storage_options` from the calls to `dd.read_parquet`. Presumably Dask is using cached credentials in this situation.

**Environment**:

- Dask version: 2021.04.0
- Python version: 3.7.10
- Operating System: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Install method (conda, pip, source): pip
- Pyarrow version: 3.0.0
- Gcsfs version: 0.7.2

**Comment by jsignell** [comment]
I would try an older version of pyarrow, but other than that @rjzamora will probably know best.

**Comment by raybellwaves** [comment]
I asked something similar on gitter recently: https://gitter.im/dask/dask. There may be a better way to add gitter links but it wasn't too long ago (3/29).

I'm unsure on appending when writing to a bucket instead of local. You could test the caching with something like `fs = gcfs.GCFileSystem(use_listings_cache=False)` cc. @martindurant.

I've tended to use a tmp file if it's a one off thing and not write back to the file i'm reading.

**Comment by toby-coleman** [comment]
It's a private bucket. I tried downloading the data out of Google Cloud and found it was unreadable locally as well.

Having said that, I just retried with the newly release `gcsfs==0.8.0` and the problem looks to be resolved 😀. Reads and writes as expected now.

**Comment by martindurant** [comment]
Er, hurray?!
Then I suppose we can close this, but I can't say I know what happened.

**Comment by toby-coleman** [comment]
I know... I'll admit to being slightly bemused considering how long I spent working out how to reproduce the problem, but take a win where you can, eh?
