### ISSUE TITLE
Configuration docs "dask." prefix not correct

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7532]
**What happened**:

Configuration parameters listed in the [configuration reference](https://docs.dask.org/en/latest/configuration-reference.html) with a `dask.` prefix should not have that prefix.

**Minimal Complete Verifiable Example**:

```python
import os
os.environ['DASK_TEMPORARY_DIRECTORY'] = '/workdir'

import dask
assert dask.config.get("temporary-directory") == '/workdir'  # No `dask.` prefix,
```

With `dask.` prefix, get error:

```
dask.config.get("dask.temporary-directory")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/croat/dask_scheduler_memory2/dask/dask/config.py", line 474, in get
    result = result[k]
KeyError: 'dask'
```

**Anything else we need to know?**:

The [conversion utility](https://docs.dask.org/en/latest/configuration.html#conversion-utility) does the right thing with `dask.` removed.

**Environment**:

- Dask version: 2021.04.0+8.g443aef27
- Python version: 3.9.2
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
The spelling for Dask configs is a little confusing.  I believe it needs to be  `DASK_DASK__VALUE`


```bash
❯ DASK_DASK__TEMPORARY_DIRECTORY="/foobar" python -c 'import dask; print(dask.config.get("dask.temporary-directory"))'
/foobar
```

**Comment by quasiben** [comment]
Hmm, I think I might be wrong actually.  The above will build a new key/value in the config

**Comment by jrbourbeau** [comment]
Thanks for reporting @chrisroat -- I agree with you and @quasiben that the config values listed should be, for example, `optimization.fuse.active` instead of `dask.optimization.fuse.active`.
