### ISSUE TITLE
read_sql_table returns incomplete result if index_col is only column

### ISSUE THREAD

**Issue by c-thiel** [dask/dask#7539]
**What happened**:

When running ``dask.dataframe.read_sql_table(head_rows=0, meta=meta)`` with on a table which has only one column, or when selecting *only* the index_col from a table, then the returned result is incomplete.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
dd.read_sql_table(table='my_table', head_rows=0, meta=meta, uri=uri, index_col='ID')
```
where ``my_table`` has only the `ID` column and more than `head_rows` rows.

**Anything else we need to know?**:
This behaviour is due to this line:
https://github.com/dask/dask/blob/c5633c21e754df6b2c13195f1e2688e347c48963/dask/dataframe/io/sql.py#L227

The problem is that a pandas dataframe with only an index is considered empty if there are no other columns:
```python
import pandas as pd
df = pd.DataFrame([], index=range(10))
df.empty
# True
```
Thus the code takes a wrong branch there and returns the head with ``from_pandas`` - despite there being a whole lot other entries in the index column.

A simple fix might be to use ``len(head)`` instead of ``head.empty``.

**Environment**:

- Dask version: 2021.02.0

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @c-thiel! 

> A simple fix might be to use len(head) instead of head.empty

Naively this seems reasonable to me -- though I'm not sure if there is any downstream logic that might assume there are row/column contents. Would you be interested in submitting a PR with the proposed change?

**Comment by c-thiel** [comment]
@jrbourbeau I am happy to prepare a PR once I find a bit time for it - probably next weekend.

**Comment by jrbourbeau** [comment]
Sounds good, no rush. Thanks @c-thiel : )

**Comment by c-thiel** [comment]
@jrbourbeau PR is ready :)
