### ISSUE TITLE
numpy/dask difference in stacking multi-dim arrays with unknown chunk sizes

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7546]
**What happened**:

When using da.stack and stacking a multi-dim list (of arrays), the allow_unknown_chunksizes parameter is not passed into asarray.  This is needed as asarray calls back to stack if it is passed a sequence, and an error is raised if the unknown chunksize is not the first dimension.

**What you expected to happen**:

da.stack and np.stack to produce the same result when stacking a multi-dim array.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import dask.array as da
import dask.dataframe as dd

a_df = pd.DataFrame({"a": np.arange(12)})
b_df = pd.DataFrame({"b": np.arange(12) * 10})
c_df = pd.DataFrame({"c": np.arange(12) * 100})
d_df = pd.DataFrame({"d": np.arange(12) * 1000})

a_ddf = dd.from_pandas(a_df, sort=False, npartitions=3)
b_ddf = dd.from_pandas(b_df, sort=False, npartitions=3)
c_ddf = dd.from_pandas(c_df, sort=False, npartitions=3)
d_ddf = dd.from_pandas(d_df, sort=False, npartitions=3)

a_x = a_ddf.values
b_x = b_ddf.values
c_x = c_ddf.values
d_x = d_ddf.values

# Works
np.stack([
    [a_df.values, b_df.values],
    [c_df.values, d_df.values],
])

# Does not work
da.stack([
    [a_x, b_x],
    [c_x, d_x]
], allow_unknown_chunksizes=True)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.04.0+16.ge83379d5
- Python version: 3.8.8
- Operating System: MacOS 11.2.3
- Install method (conda, pip, source): conda

**Comment by chrisroat** [comment]
I have a PR that fixes this, but it requires adding `allow_unknown_chunksizes` to `asarray`.  To be thorough, we might also need to add `allow_unknown_chunksizes` to other functions which call `stack`, like `asanyarray`.

**Comment by GenevieveBuckley** [comment]
Could you link to the PR here?

**Comment by chrisroat** [comment]
Added
