### ISSUE TITLE
Merge produces incorrect results with partitioned data

### ISSUE THREAD

**Issue by bluecoconut** [dask/dask#7558]
**What happened**:

Pandas result works, Dask result produces an error and does not work with example above.

Changing  in the example below: `df2_d = dd.from_pandas(df2, npartitions=3).set_index('b')` to 
`df2_d = dd.from_pandas(df2, npartitions=3).set_index('b').repartition(npartitions=5)`
causes dask to run, but produce incorrect results in the output merged dataframe.

**What you expected to happen**:
Dask and pandas agree and produce the same result when joining tables together.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
df1 = pd.DataFrame({'a': ['0', '0', None, None, None, None, '5', '7', '15', '33']})
df2 = pd.DataFrame({'b': ['0', '5', '7', '15'], 'c': ['1', '2', '3', '4']})

pandas_result = df1.merge(df2.set_index('b'), how='left', left_on='a', right_index=True)

df1_d = dd.from_pandas(df1, npartitions=4)
df2_d = dd.from_pandas(df2, npartitions=3).set_index('b')

dask_result = df1_d.merge(df2_d, how='left', left_on='a', right_index=True).compute()
```

**Comment by quasiben** [comment]
When I ran example above I get type error:

> TypeError: '<' not supported between instances of 'str' and 'NoneType'

**Comment by bluecoconut** [comment]
Ah sorry my comment might not have been clear:
```python
import pandas as pd
df1 = pd.DataFrame({'a': ['0', '0', None, None, None, None, '5', '7', '15', '33']})
df2 = pd.DataFrame({'b': ['0', '5', '7', '15'], 'c': ['1', '2', '3', '4']})

pandas_result = df1.merge(df2.set_index('b'), how='left', left_on='a', right_index=True)

df1_d = dd.from_pandas(df1, npartitions=4)
df2_d = dd.from_pandas(df2, npartitions=3).set_index('b')

dask_result = df1_d.merge(df2_d, how='left', left_on='a', right_index=True).compute()
```
produces 
`TypeError: '<' not supported between instances of 'str' and 'NoneType'`


Adding `.repartition(npartitions=5)` to the `df2_d` line, is what produces the incorrect result. 

```python
import pandas as pd
import dask.dataframe as dd

df1 = pd.DataFrame({'a': ['0', '0', None, None, None, None, '5', '7', '15', '33']})
df2 = pd.DataFrame({'b': ['0', '5', '7', '15'], 'c': ['1', '2', '3', '4']})

pandas_result = df1.merge(df2.set_index('b'), how='left', left_on='a', right_index=True)

df1_d = dd.from_pandas(df1, npartitions=4)
df2_d = dd.from_pandas(df2, npartitions=3).set_index('b').repartition(npartitions=5)

dask_result = df1_d.merge(df2_d, how='left', left_on='a', right_index=True).compute()
```

Output:
Pandas:
```
        a	c
0	0	1
1	0	1
2	None	NaN
3	None	NaN
4	None	NaN
5	None	NaN
6	5	2
7	7	3
8	15	4
9	33	NaN
```

Output Dask:
```
	a	c
2	None	None
3	None	None
4	None	None
5	None	None
0	0	NaN
1	0	NaN
7	7	NaN
6	5	NaN
8	15	NaN
9	33	NaN
```

I think that the Error that happens and also the incorrect result are related, and are related to `.division` logic

**Comment by jsignell** [comment]
Yeah I can reproduce and I noticed that even if you explicitly clear the divisions on `df1_d` you still get the incorrect result.

**Comment by rjzamora** [comment]
Thank you for raising this @bluecoconut - This is a good find.  It looks like we are using a hash merge here, and the left-hand join index (a DataFrame column) is getting hashed differently than the right-hand join index (a DataFrame index).  I will definitely look into a solution for this.
