### ISSUE TITLE
PYPI version

### ISSUE THREAD

**Issue by martindurant** [dask/dask#7568]
The dask version which when installed, reports `dask.__version__ == '2021.04.0'` (i.e., current) actually has the version 2021.4.0 on pypi - without the padding zero. The same is true of the filename "dask-2021.4.0-py3-none-any.whl". 

Is this expected?

**Comment by jrbourbeau** [comment]
I think this is expected. See the conversation over in https://github.com/dask/community/issues/100 starting at https://github.com/dask/community/issues/100#issuecomment-704445214.

**Comment by martindurant** [comment]
I had not appreciated from the discussion at the time that the filename and version reported by pypi/pip would not match the __version__ string. Well, it doesn't seem to be causing any pain.

On April 16, 2021 5:20:55 PM EDT, James Bourbeau ***@***.***> wrote:
>I think this is expected. See the conversation over in
>https://github.com/dask/community/issues/100 starting at
>https://github.com/dask/community/issues/100#issuecomment-704445214. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/dask/issues/7568#issuecomment-821570223

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ian-r-rose** [comment]
I've been bit by this before when using @jacobtomlinson's find/replace github action to bump versions. I'm not sure if there is anything to do about it except be aware of the possible pitfall

**Comment by mrocklin** [comment]
It'll be fun to see if anything fun happens in October :)
