### ISSUE TITLE
Export task stream to svg file

### ISSUE THREAD

**Issue by nikusha37** [dask/dask#7570]
Please add save as svg button to the status dashboard of dask distibuted.

Thanks

**Comment by SultanOrazbayev** [comment]
In the meantime you can see workarounds: https://stackoverflow.com/a/67136131/10693596

**Comment by ncclementi** [comment]
@nikusha37 As another alternative you can save the computations as a performance report which will generate an HTML of some useful information. See https://distributed.dask.org/en/latest/diagnosing-performance.html#performance-reports

**Comment by jrbourbeau** [comment]
Thanks @SultanOrazbayev @ncclementi for providing feedback here. As mentioned, there are a couple of ways one can save dashboard plots to static files today. @nikusha37 if there's something you think would be broadly useful to add the Dask's performance reports, please let us know
