### ISSUE TITLE
Applying a function to each chunk in a Dask array and combining the results (output is a different shape to the array)

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#7589]
**What happened**:
I run into this type of pattern a lot.

I want to do $foo to all the chunks (or slightly overlapping chunks) in a Dask array. I can't use `map_overlap` or `map_blocks` easily, because what I get back from the function $foo isn't the same shape as the original array - it's a list, or multiple lists, could be a pandas series or dataframe. 

I need to combine all of these outputs. In the simplest case, I don't care which array chunk they were generated from, I just want to append all the results together.

**What you expected to happen**:
Matt and I both initially expected that we should be able to use `map_blocks` for this kind of situation.

**Minimal Complete Verifiable Example**:
```python
import dask.array as da
import numpy as np
x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    return np.array([1, 2, 3])

result = da.map_blocks(foo, x)
result.compute()
```

But because the result from `foo` isn't the same shape as the input array chunk, we get this error:

<details>
<summary>Details:</summary>

```python-traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-80557264a235> in <module>
      7 
      8 result = da.map_blocks(foo, x)
----> 9 result.compute()

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    282         dask.base.compute
    283         """
--> 284         (result,) = compute(self, traverse=False, **kwargs)
    285         return result
    286 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    565 
    566     results = schedule(dsk, keys, **kwargs)
--> 567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568 
    569 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in <listcomp>(.0)
    565 
    566     results = schedule(dsk, keys, **kwargs)
--> 567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568 
    569 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in finalize(results)
   1073     while isinstance(results2, (tuple, list)):
   1074         if len(results2) > 1:
-> 1075             return concatenate3(results)
   1076         else:
   1077             results2 = results2[0]

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in concatenate3(arrays)
   4757     if not ndim:
   4758         return arrays
-> 4759     chunks = chunks_from_arrays(arrays)
   4760     shape = tuple(map(sum, chunks))
   4761 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in chunks_from_arrays(arrays)
   4528 
   4529     while isinstance(arrays, (list, tuple)):
-> 4530         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4531         arrays = arrays[0]
   4532         dim += 1

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in <listcomp>(.0)
   4528 
   4529     while isinstance(arrays, (list, tuple)):
-> 4530         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4531         arrays = arrays[0]
   4532         dim += 1

IndexError: tuple index out of range

```

</details>

**Anything else we need to know?**:

**Environment**:

- Dask version: '2021.04.0'
- Python version: 3.8
- Operating System: Ubuntu 20.04 LTS
- Install method (conda, pip, source): conda

**Comment by GenevieveBuckley** [comment]
For reference, here are the examples Matt tried involving pandas output from function `foo`. I'm including them here for reference, although I think the fundamental problem is described more simply by the MCVE above.

### With a pandas Series

```python
import dask.array as da
import pandas as pd

x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    return pd.Series([1, 2, 3])

result = da.map_blocks(foo, x)
result.compute()
```

<details>
<summary>Error message details:</summary>

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-33-a4f886589eb2> in <module>
----> 1 result.compute()

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    282         dask.base.compute
    283         """
--> 284         (result,) = compute(self, traverse=False, **kwargs)
    285         return result
    286 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    558     )
    559 
--> 560     dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    561     keys, postcomputes = [], []
    562     for x in collections:

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/base.py in collections_to_dsk(collections, optimize_graph, optimizations, **kwargs)
    334         for opt, val in groups.items():
    335             dsk, keys = _extract_graph_and_keys(val)
--> 336             dsk = opt(dsk, keys, **kwargs)
    337 
    338             for opt in optimizations:

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/dataframe/optimize.py in optimize(dsk, keys, **kwargs)
     39         fuse_subgraphs=fuse_subgraphs,
     40     )
---> 41     dsk, _ = cull(dsk, keys)
     42     return dsk
     43 

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/optimization.py in cull(dsk, keys)
     49         new_work = []
     50         for k in work:
---> 51             dependencies_k = get_dependencies(dsk, k, as_list=True)  # fuse needs lists
     52             out[k] = dsk[k]
     53             dependencies[k] = dependencies_k

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/core.py in get_dependencies(dsk, key, task, as_list)
    250     """
    251     if key is not None:
--> 252         arg = dsk[key]
    253     elif task is not no_default:
    254         arg = task

KeyError: ('foo-78edf44570908b37e2606346af577beb', 1)

```

</details>

### With a pandas dataframe

```python
import dask.array as da
import pandas as pd

x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    return pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

result = da.map_blocks(foo, x)
```

<details>
<summary>Error message details:</summary>

```python-traceback
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-4fc9e129d074> in <module>
----> 1 result = da.map_blocks(foo, x)

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in map_blocks(self, func, *args, **kwargs)
   2313     @wraps(map_blocks)
   2314     def map_blocks(self, func, *args, **kwargs):
-> 2315         return map_blocks(func, self, *args, **kwargs)
   2316 
   2317     def map_overlap(self, func, depth, boundary=None, trim=True, **kwargs):

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in map_blocks(func, name, token, dtype, chunks, drop_axis, new_axis, meta, *args, **kwargs)
    681             pass
    682 
--> 683         dtype = apply_infer_dtype(func, args, original_kwargs, "map_blocks")
    684 
    685     if drop_axis:

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in apply_infer_dtype(func, args, kwargs, funcname, suggest_dtype, nout)
    407     if msg is not None:
    408         raise ValueError(msg)
--> 409     return o.dtype if nout is None else tuple(e.dtype for e in o)
    410 
    411 

~/anaconda3/envs/dask/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 
   5467     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'dtype'
```

</details>

**Comment by GenevieveBuckley** [comment]
I was trying to work around this problem earlier by using blockwise with ragged outputs, but I couldn't quite work out how to make it work for 2D or nD arrays - https://github.com/dask/dask/pull/7551

**Comment by chrisroat** [comment]
You can use a delayed function on each chunk.  I think `map_{blocks,overlap}` are very array-specific, but you could imagine creating another function to handle this.

```python
import dask.array as da
import dask.dataframe as dd
import numpy as np
import pandas as pd
import dask

np.random.seed(42)  # To geterministic results

x = da.ones((20, 10), chunks=(10, 10))

@dask.delayed
def foo(a):
    size = np.random.randint(1,10)  # Make each dataframe a different size
    return pd.DataFrame({'x': np.arange(size), 
                         'y': np.arange(10, 10+size)})

meta = dd.utils.make_meta([('x', np.int64), ('y', np.int64)])
blocks = x.to_delayed().ravel()
results = [dd.from_delayed(foo(b)) for b in blocks]
ddf = dd.concat(results)
ddf.compute()
```

```
   x   y
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
5  5  15
6  6  16
7  7  17
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
```

**Comment by chrisroat** [comment]
And for completeness, here's how to do it with arrays:

```python
import dask.array as da
import numpy as np
import dask

np.random.seed(42)

x = da.ones((20, 10), chunks=(10, 10))

@dask.delayed
def foo(a):
    size = np.random.randint(1,10)
    return np.random.randint(1,10, size=(2, size))

blocks = x.to_delayed().ravel()
results = [da.from_delayed(foo(b), shape=(2, np.nan), dtype=np.int64) for b in blocks]
arr = da.concatenate(results, axis=1, allow_unknown_chunksizes=True)
arr.compute()
```

```
array([[4, 8, 5, 7, 3, 7, 8, 8, 6],
       [5, 4, 8, 8, 3, 6, 5, 2, 5]])
```

**Comment by chrisroat** [comment]
Using the array pattern is what led me to find problems like #7546

**Comment by chrisroat** [comment]
If you want to know the chunk indices, you can do something similar to what is [done in dask-image](https://github.com/dask/dask-image/blob/adcb217de766dd6fef99895ed1a33bf78a97d14b/dask_image/ndmeasure/__init__.py#L299).  Note that they use slicing to get chunks, whereas here I use to_delayed().ravel().  I believe it should be the same.

**Comment by GenevieveBuckley** [comment]
> You can use a delayed function on each chunk.

Yes, this is true.

The reason for raising this issue is:
* Intuitively expecting this is supported seems to be an easy misperception to fall into, and
* This type of pattern is pretty common towards the end of analysis pipelines, so perhaps we should cater for it more.

**Comment by chrisroat** [comment]
Agree that it is useful!  I have used examples of this in my work.  A unified `meta` argument, which could be either an array or dataframe, could be a usable interface.

**Comment by jsignell** [comment]
You can use the `drop_axis` to alter the dimensionality of the output. For example in your case above you can do:

```python
result = da.map_blocks(foo, x, chunks=(3,), drop_axis=0).compute()
# array([1, 2, 3])

# OR
result = da.map_blocks(foo, x, chunks=(3,), drop_axis=1).compute()
# array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3])
```

It's not clear to me from your original problem statement? Are you looking for the output to be 1D?

**Comment by chrisroat** [comment]
I believe the desire is to have each block return a different length output
in one or more dimensions.

**Comment by jsignell** [comment]
Ah ok like this?

```python
In  [1]: import dask.array as da
    ...: import numpy as np
    ...: x = da.ones((100, 10), chunks=(10, 10))
    ...: 
    ...: def foo(a, block_id=None):
    ...:     ii = block_id[0]
    ...:     return np.arange(ii)
    ...: 
    ...: result = da.map_blocks(foo, x, chunks=(tuple(range(0, 10)),), dtype=int, drop_axis=1)
    ...: result.compute()
Out [1]: 
array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7,
       8])


```
Note that the chunks kwarg is only required if you want the `result.chunks` and `result.size` to be accurate. `result.compute()` will work fine without it.

**Comment by jsignell** [comment]
If the intention is to have ragged arrays in each block and not concatenate, then I think this is not a good use of dask.array. It'd probably make more sense as a bag of arrays or something.

**Comment by chrisroat** [comment]
You are correct that it is ragged in every dimension, so an array output is
not going to work.

But it is common to start with an array as input.  (Example: find objects
in a 3d array -- each block has a different number of objects)  Is your
thought to start with an array, turn each chunk into a member of a bag,
then map a function (array->dataframe) on the array bag, and then dd.concat
the dataframe bag?

This is effectively what the code example I give above does, except uses an
array of delayed arrays instead of a bag.  I haven't worked with bags
before, so not sure if what I write makes sense. :)

**Comment by jsignell** [comment]
> Is your thought to start with an array, turn each chunk into a member of a bag,
then map a function (array->dataframe) on the array bag, and then dd.concat
the dataframe bag?

Clearly, I don't have a great understanding of this workflow so feel free to ignore me if this isn't helpful :) but what I was thinking was that you would start with an array and then the output of each chunk would be a bag. I agree that it's very similar to the approach that you gave @chrisroat - I was just trying to avoid the initial `to_delayed` step.

**Comment by chrisroat** [comment]
> Clearly, I don't have a great understanding of this workflow so feel free to ignore me if this isn't helpful :) but what I was thinking was that you would start with an array and then the output of each chunk would be a bag. I agree that it's very similar to the approach that you gave @chrisroat - I was just trying to avoid the initial `to_delayed` step.

That sounds like a similar approach, but I'm not sure how one avoids `to_delayed` or `dask.delayed`.  How can one convert each chunk to a bag without going through something delayed?

**Comment by GenevieveBuckley** [comment]
Thanks @chrisroat and @jsignell, it's really great to see these other examples.

> You are correct that it is ragged in every dimension, so an array output is
not going to work.
I personally have one ragged dimension, which I do want to concatenate the results along. It seems there are more variations on what other people want to do than I'd guessed, which is useful information to know.

**Comment by GenevieveBuckley** [comment]
> You can use the `drop_axis` to alter the dimensionality of the output. For example in your case above you can do:
> 
> ```python
> result = da.map_blocks(foo, x, chunks=(3,), drop_axis=0).compute()
> # array([1, 2, 3])
> 
> # OR
> result = da.map_blocks(foo, x, chunks=(3,), drop_axis=1).compute()
> # array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
> #        2, 3, 1, 2, 3, 1, 2, 3])
> ```
> 
> It's not clear to me from your original problem statement? Are you looking for the output to be 1D?

Hm, sorry. It looks like I've over-simplified the problem and lost some important context.

Let's take this problem setup. I have a dask array, and a function `foo`.  Function `foo` takes in an array chunk (or an array chunk with some overlap), computes something, and returns 1D results with a ragged length. 
```python
import dask.array as da
import numpy as np
np.random.seed(0) # for reproducibility

x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    random_length = np.random.randint(1, 7)
    return np.arange(random_length)
```

If we don't need any overlap, life is fine:
```python
result = da.map_blocks(foo, x, drop_axis=1)
result.compute()  # this works

array([0, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3, 0, 1, 2,
       3, 4, 5, 0, 1, 2, 0, 1, 2, 3, 4, 0])  # a good result
```

But if we need some overlap for function `foo` to work correctly, then we run into problems:

```python
result = da.map_overlap(foo, x, depth=1, drop_axis=1)
result.compute()  # incorrect output, because the result from foo is being trimmed

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 3, 1, 2, 3, 4, 1])  # the first and last element of the results from foo are being trimmed off before the whole thing is concatenated, which we don't want
```

I expected that setting the keyword argument `trim=False` would avoid this problem, but instead we get an error:
```python
result = da.map_overlap(foo, x, depth=1, trim=False, drop_axis=1)
result.compute()  # error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-023aece75635> in <module>
      9     return np.arange(random_length)
     10 
---> 11 result = da.map_overlap(foo, x, depth=1, trim=False, drop_axis=1)
     12 result.compute()

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/overlap.py in map_overlap(func, depth, boundary, trim, align_arrays, *args, **kwargs)
    800     args = [overlap(x, depth=d, boundary=b) for x, d, b in zip(args, depth, boundary)]
    801     assert_int_chunksize(args)
--> 802     x = map_blocks(func, *args, **kwargs)
    803     assert_int_chunksize([x])
    804     if trim:

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in map_blocks(func, name, token, dtype, chunks, drop_axis, new_axis, meta, *args, **kwargs)
    711         adjust_chunks = None
    712 
--> 713     out = blockwise(
    714         func,
    715         out_ind,

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/blockwise.py in blockwise(func, out_ind, name, token, dtype, adjust_chunks, new_axes, align_arrays, concatenate, meta, *args, **kwargs)
    260                 elif isinstance(adjust_chunks[ind], (tuple, list)):
    261                     if len(adjust_chunks[ind]) != len(chunks[i]):
--> 262                         raise ValueError(
    263                             "Dimension {0} has {1} blocks, "
    264                             "adjust_chunks specified with "

ValueError: Dimension 1 has 10 blocks, adjust_chunks specified with 1 blocks
```python-traceback

```

**Comment by GenevieveBuckley** [comment]
And since you can't pass an `adjust_chunks` kwarg directly into map_blocks / map_overlap, that's why I was fiddling around with ragged outputs and blockwise earlier: https://github.com/dask/dask/pull/7551
```python-traceback
ValueError: Dimension 1 has 10 blocks, adjust_chunks specified with 1 blocks
```

I'm not sure that's necessarily the right way to go, using dask delayed, or maybe bag as suggested above might be better options.

**Comment by GenevieveBuckley** [comment]
So, both of these work fine so long as we include the `drop_axis` keyword argument (and for dataframes, we need to pass in the `dtype` kwarg too). Thanks Julia for reminding me how to do it properly!

So to update [the examples from earlier](https://github.com/dask/dask/issues/7589#issuecomment-824527354), this is what they *should* have been instead.

### With a pandas Series

```python
import dask.array as da
import pandas as pd

x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    return pd.Series([1, 2, 3])
 
result = da.map_blocks(foo, x, drop_axis=1)
result.compute()  # works as expected
```

### With a pandas dataframe
 
```python
import dask.array as da
import pandas as pd

x = da.ones((100, 10), chunks=(10, 10))

def foo(a):
    return pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

result = da.map_blocks(foo, x, drop_axis=1, dtype=int)  
result.compute  # works as expected
```

**Comment by jsignell** [comment]
Oh cool! I'm glad you got something that works! Are we good to close this ticket, or do you want to add some examples to the docs or examples?

**Comment by GenevieveBuckley** [comment]
> Oh cool! I'm glad you got something that works! Are we good to close this ticket, or do you want to add some examples to the docs or examples?

I can only make it work for `map_blocks`, but not `map_overlap`. I'd really like to figure out how this can be done more easily.

Right now I have a workaround based on dask delayed and my hacked version of [slices_from_chunks](https://gist.github.com/GenevieveBuckley/decd23c22ee3417f7d78e87f791bc081), but I feel like there could be a much cleaner solution.

For context, I'm [looking at distributed skeleton analysis](https://gist.github.com/GenevieveBuckley/a38112a9dd31cf09a3ab1459768d64eb), something that requires a 1-pixel overlap.

**Comment by GenevieveBuckley** [comment]
Ok, now I'll give up. I've just been digging into it again & it's not going to be as straightforward as I'd hoped to change the way the `map_overlap` results get concatenated back together. 

This has been a very helpful thread, thank you both @chrisroat and @jsignell

**Comment by GenevieveBuckley** [comment]
> You can use a delayed function on each chunk. I think `map_{blocks,overlap}` are very array-specific, but you could imagine creating another function to handle this.
> 
> ```python
> import dask.array as da
> import dask.dataframe as dd
> import numpy as np
> import pandas as pd
> import dask
> 
> np.random.seed(42)  # To geterministic results
> 
> x = da.ones((20, 10), chunks=(10, 10))
> 
> @dask.delayed
> def foo(a):
>     size = np.random.randint(1,10)  # Make each dataframe a different size
>     return pd.DataFrame({'x': np.arange(size), 
>                          'y': np.arange(10, 10+size)})
> 
> meta = dd.utils.make_meta([('x', np.int64), ('y', np.int64)])
> blocks = x.to_delayed().ravel()
> results = [dd.from_delayed(foo(b)) for b in blocks]
> ddf = dd.concat(results)
> ddf.compute()
> ```

When I try this approach on a more real-world dataset, it seems like there is a *lot* of computation of some kind going on well before I get to the compute call.

When I start the dask dashboard with:
```python
from dask.distributed import Client
client = Client()

client
```

and then run the code above, say with an extra call to `time.sleep(5)` inside the function `foo`, I see a lot more activity/waiting happening at this line:
```
results = [dd.from_delayed(foo(b)) for b in blocks]
```

On my real-world dataset, there is LOTS of activity you can see in the dashboard at this line, to the point where things are unusable for a few minutes. It feels as though it's triggering some computation when ideally it should not be. Am I doing this right?

**Comment by GenevieveBuckley** [comment]
> Ok, now I'll give up. I've just been digging into it again & it's not going to be as straightforward as I'd hoped to change the way the `map_overlap` results get concatenated back together.

@jakirkham perhaps it's worth us having a discussion about this particular use case (taking slightly overlapping chunks of a dask array, applying an arbitrary function on them, and then being able to combine different shaped results from each chunk)

**Comment by chrisroat** [comment]
Can you try adding the meta parameter?  I see that my original example didn't include that -- I'll update it.

**Comment by GenevieveBuckley** [comment]
> Can you try adding the meta parameter? I see that my original example didn't include that -- I've updated it.

Ah, much better now! Thanks @chrisroat

**Comment by jni** [comment]
A truly fascinating discussion — thanks all!

I am just writing to echo @GenevieveBuckley's sentiment that it should be easier to do arbitrary computations on (possibly overlapping) chunks *and then combine them in arbitrary ways*. e.g. `da.map_overlap(array, make_graph, depth=1, reduce_func=networkx.compose)`. That is, can we relax the assumption that map_blocks/map_overlap always produce array-likes? Here I am assuming that `make_graph` takes in arrays and produces networkx graphs. By default, `reduce_func` would be cropping + concatenating, along each axis in turn.

Obviously I'm writing from a very naive perspective — I don't know much about the implementation internals — but that is the API I would expect. All of the above workarounds seem rather arcane!

**Comment by GenevieveBuckley** [comment]
John & I are going to have a chat about exactly this after the Dask summit - do you want to join us @jni? (We haven't picked a time yet, so I'm sure we can find one that suits you too)

**Comment by jni** [comment]
I do!

**Comment by jsignell** [comment]
Ooo I am very interested in thinking more about this as well, but I can read the discussion afterwards if timezones don't work out.

**Comment by Yu-AnChen** [comment]
Thanks for the super helpful thread and the blog post! I needed some image mask operation and  `np.unique` for each of my overlapping chunks. Following [the example](https://github.com/dask/dask/issues/7589#issuecomment-827396311) - 

> Let's take this problem setup. I have a dask array, and a function `foo`. Function `foo` takes in an array chunk (or an array chunk with some overlap), computes something, and returns 1D results with a ragged length.
> 
> ```python
> import dask.array as da
> import numpy as np
> np.random.seed(0) # for reproducibility
> 
> x = da.ones((100, 10), chunks=(10, 10))
> 
> def foo(a):
>     random_length = np.random.randint(1, 7)
>     return np.arange(random_length)
> ```
> 
> If we don't need any overlap, life is fine:
> 
> ```python
> result = da.map_blocks(foo, x, drop_axis=1)
> result.compute()  # this works
> 
> array([0, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3, 0, 1, 2,
>        3, 4, 5, 0, 1, 2, 0, 1, 2, 3, 4, 0])  # a good result
> ```
> 
> But if we need some overlap for function `foo` to work correctly, then we run into problems:
> 
> ```python
> result = da.map_overlap(foo, x, depth=1, drop_axis=1)
> result.compute()  # incorrect output, because the result from foo is being trimmed
> 
> array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 3, 1, 2, 3, 4, 1])  # the first and last element of the results from foo are being trimmed off before the whole thing is concatenated, which we don't want
> ```
> 
> I expected that setting the keyword argument `trim=False` would avoid this problem, but instead we get an error:
> 
> ```python
> result = da.map_overlap(foo, x, depth=1, trim=False, drop_axis=1)
> result.compute()  # ValueError
> ```

```python
x = da.ones((100, 10), chunks=(10, 10))
x_overlap = da.overlap.overlap(x, depth=1, boundary='none')

result = x_overlap.map_blocks(foo, drop_axis=1).compute()
# array([0, 1, 0, 1, 2, 3, 4, 0, 1, 0, 1, 2, 0, 1, 2, 0, 0, 1, 0, 1, 0, 1, 0, 1])

np.sum(result == 0)
# 10

x.chunks
# ((10, 10, 10, 10, 10, 10, 10, 10, 10, 10), (10,))

x_overlap.chunks
# ((11, 12, 12, 12, 12, 12, 12, 12, 12, 11), (10,))
```

Would this be a reasonable solution for overlapping chunks? I assume it's not doubling the RAM usage by constructing the overlapping chunks first.

**Comment by GenevieveBuckley** [comment]
> Would this be a reasonable solution for overlapping chunks? I assume it's not doubling the RAM usage by constructing the overlapping chunks first.

Broadly yes, it seems like the easiest way to get around these problems is to
1. Expand the array with `dask.array.overlap.overlap` to get an overlap around each chunk, then
2. Run `map_blocks` on the expanded array

I don't have a specific number to give you about RAM use. I didn't notice anything too out of the ordinary when I ran this. You might like to check this with your own work using the "worker memory" plot of the dask dashboard. Watching the dashboard is very helpful for getting an intuition about these things. 

If you do come close to your memory limit, I'd suggest:
1. Carefully selecting your array chunk size, and...
2. Taking a look at this video from Coiled on managing memory (particularly unmanaged memory) with Dask https://www.youtube.com/watch?v=nwR6iGR0mb0&t=25s

**Comment by Yu-AnChen** [comment]
Thank you @GenevieveBuckley for the summary and the helpful tips! Looking forward to seeing future releases that would allow more flexibility in `map_overlap` outputs 😃

**Comment by jreniel** [comment]
Hi All,
Is there a way to make a meta for returning a geopandas.GeoDataFrame from map_{blocks/overlap} ? 
Most of my operation involve returning a non-array from each block, but I am struggling to make this work for returning arbitrary objects.

**Comment by GenevieveBuckley** [comment]
@jreniel perhaps you'd like to say what solution you ended up with? People with similar problems seem to be finding this thread, so it may help them to know what you did.

We could also try to share the knowledge with a short blogpost. I wrote something [here for arrays](https://blog.dask.org/2021/07/02/ragged-output), having something sort of similar for dataframes could be useful. cc @jacobtomlinson - are you still looking for blogpost ideas?

**Comment by Yu-AnChen** [comment]
@GenevieveBuckley A blog post on meta will be super helpful! The blog you wrote is a great reference for me as well. 

I've come to the following approach for handling arbitrary output (or no output at all, that I just leverage the side effect of the function) from each block that I'm trying to process in parallel - 

```python
import dask
import dask.array as da
import numpy as np
import dask.diagnostics

# target array to be processed block-by-block
# use `da.overlap.overlap` for overlapped blocks
img_da = da.random.randint(
    low=1, high=10, size=(4, 4),
    dtype=int, chunks=2
)

# function that returns a python dictionary
def max_arange(x):
    m = np.max(x)
    return {f"{m}": np.arange(m)}

# list comprehension to iterate over the blocks, lazily
delayed_result = [
    dask.delayed(max_arange)(b) 
    for b in img_da.blocks.ravel()
]

# this is what I'm using for parallel processing, there's likely a better way to
# do this
result = dask.delayed(list)(delayed_result)
result.visualize("mapped.png")
with dask.diagnostics.ProgressBar():
    print(result.compute())
```

Here are the print and exec graph
```python
[########################################] | 100% Completed |  0.1s
[{'6': array([0, 1, 2, 3, 4, 5])}, {'7': array([0, 1, 2, 3, 4, 5, 6])}, {'7': array([0, 1, 2, 3, 4, 5, 6])}, {'6': array([0, 1, 2, 3, 4, 5])}]
```
![mapped](https://user-images.githubusercontent.com/17751400/177269884-dd9b0911-2dc4-48ae-930d-d1c48e73050a.png)

I haven't done any careful benchmarking so you may want to monitor it in your use cases. Hope this approach is general enough for @jsignell 🙂

**Comment by GenevieveBuckley** [comment]
Thank you for the example, and the extra context @jreniel 😄
