### ISSUE TITLE
Better error when creating Dask DataFrames from a source with columns named after special attributes

### ISSUE THREAD

**Issue by jppcr** [dask/dask#7599]
Hello,

I was trying to use Dask to handle a dataset that contained a column named "divisions". This was a large dataset with 90.000 columns or so (one for each word in a set of documents), so I did not know beforehand that a column existed with that particular name.

Whenever I tried to load that data into a Dask DataFrame, either by using `read_csv` or `read_pandas`, an Exception occurred ("TypeError: Column assignment doesn't support type tuple" [(Full trace here)](https://gist.github.com/jppcr/90aea59c4585daa0dd5f854e5cb12de6)). With a little debugging using pdb, I ended up discovering that the problem was occurring because of the name of that particular column. It makes some sense, since "divisions" is the name of a DataFrame attribute. However, just looking at the error would never have led me to discover that.

I suggest that the error message is improved in the cases where the user tries to create a DataFrame with columns containing "reserved words" like attribute names. That would have helped me in this case and I think it would help other people in the future too. My suggestion would be that whenever a word from a forbidden list was used in a column, the error would be "Error: Source contains a column with a reserved name: '\<name of the column here\>'."

To reproduce the current behaviour:

Create a CSV with the following content:

```
a,b,divisions,c
1,2,3,4
```
Both code snippets below result in an Exception:
```
import dask
import dask.dataframe as dd
ddf = dd.read_csv("test_dask_error.csv")
```

```
import pandas as pd
df = pd.read_csv("test_dask_error.csv")
ddf2 = dd.from_pandas(df, npartitions=2)
```

...the Exception being [(full trace in this gist)](https://gist.github.com/jppcr/90aea59c4585daa0dd5f854e5cb12de6)

`TypeError: Column assignment doesn't support type tuple`

My environment:

- Dask version: 2021.4.0
- Python version: 3.7.3
- Operating System: Linux 4.19 (Debian)
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for writing this up so clearly! I think Dask can handle this like how pandas handles a regular column named `index` where you can't access the regular index column using `df.index`, but you can do `df["index"]. I'll open up a PR to test out this approach.

**Comment by jppcr** [comment]
Hi,

I like this solution. It seems even better than just a nicer error, like I proposed. Thank you very much!
