### ISSUE TITLE
ValueError: Metadata inference failed in `map`.

### ISSUE THREAD

**Issue by pjmattingly** [dask/dask#7621]
**What happened**:
ValueError: Metadata inference failed in `map`.
as caused by:
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NAType

**What you expected to happen**:
ddf['paths'].map(get_hash) returning a Dask dataframe of hashes (strings).

**Minimal Complete Verifiable Example**:
```python
#where "files" is an iterable of strings of paths and contains no missing / NaN values
df = pd.DataFrame({'paths': files}, dtype="string")

import dask.dataframe as dd
ddf = dd.from_pandas(df, npartitions=2)

def get_hash(path):
        from simple_file_checksum import get_checksum
        return get_checksum( path, algorithm="SHA256")
ddf['paths'].map(get_hash)
```
**Anything else we need to know?**:
This code will (likely) return an exception: "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NAType". This is because Dask appears to be passing a NaN value to get_hash; Perhaps as part of its probing of return types of the function? Note that this code had worked perfectly well before several unrelated changes to the get_hash function. These changes were reverted to try to troubleshoot this issue (so that the get_hash function matched the above code), but this did not change the resulting issue.

The exception from get_hash then causes the unrelated error: ValueError: Metadata inference failed in `map`.

Adding a "meta" value does not resolve the issue, as the core issue is passing the get_hash value a NaN value unexpectedly. Revising the code to:
```python
def get_hash(path):
        import pandas as pd
        if pd.isna(path):
            return

        from simple_file_checksum import get_checksum
        return get_checksum( path, algorithm="SHA256")
```
resolves the issue. This is unexpected as the values that map() are supposed to be iterating over are strings, and there are no missing values. A more helpful exception would be valuable here. In addition, the documentation for map() should likely be revised to indicate that Dask may pass unexpected NaN values to its function at times.

**Environment**:

- Dask version: Version: 2021.4.1
- Python version: Python 3.8.8
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Can you post a reproducible example? I don't think that `files` or `simple_file_checksum ` are defined.

**Comment by pjmattingly** [comment]
Okay, I'll put something up tomorrow.

**Comment by pjmattingly** [comment]
simple_file_checksum comes from this project: https://github.com/shash873/simple-file-checksum. A simple pip install should load it into your test environment:

`pip3 install simple-file-checksum`

Then for the main code:

'''
The code that generated the list in files:

path = '''C:/Users/pmatt/Documents/Professional Work/Work/dev, keyword check; a tool to help find text in files/test, docs'''
p = Path(path).resolve().glob('*')
files = [str(x) for x in p if x.is_file()]
'''
files = ['C:\\Users\\pmatt\\Documents\\Professional Work\\Work\\dev, keyword check; a tool to help find text in files\\test, docs\\1-s2.0-S0360131516301919-main.pdf', 'C:\\Users\\pmatt\\Documents\\Professional Work\\Work\\dev, keyword check; a tool to help find text in files\\test, docs\\1-s2.0-S0360131517300696-main.pdf', 'C:\\Users\\pmatt\\Documents\\Professional Work\\Work\\dev, keyword check; a tool to help find text in files\\test, docs\\1-s2.0-S0360131517301525-main.pdf']

df = pd.DataFrame({'paths': files}, dtype="string")

import dask.dataframe as dd
ddf = dd.from_pandas(df, npartitions=2)

def get_hash(path):
        from simple_file_checksum import get_checksum
        return get_checksum( path, algorithm="SHA256")
ddf['paths'].map(get_hash)

**Comment by jsignell** [comment]
The error message that you are describing comes from the function being applied to the `meta`. You'll notice that the error message recommends specifying the `meta` in the `map` method to make the expectation of the outcome format explicit:

```python
ddf['paths'].map(get_hash, meta=("paths", str))
```

I am going to close this issue, but please reopen if that does not solve this issue.
