### ISSUE TITLE
Actor w/ async method does not propagate exceptions, and hangs forever

### ISSUE THREAD

**Issue by wwoods** [dask/dask#7626]
**What happened**: When an Actor raises an exception within an `async` method, its result hangs indefinitely.

**What you expected to happen**: The exception to be propagated to the Future resulting from the method being called.

**Minimal Complete Verifiable Example**:

```python
import dask.distributed as d
import time

class Actor:
    async def something(self):
        raise ValueError('beep')


def main():
    c = d.Client()
    a = c.submit(Actor, actor=True).result()

    p = a.something()
    time.sleep(0.1)
    print(f'About to resolve')
    print(p.result())

if __name__ == '__main__':
    main()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.04.1
- Python version: 3.8.1
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @wwoods. @martindurant does https://github.com/dask/distributed/pull/4232 close this?

**Comment by martindurant** [comment]
Yes! 

```
ValueError: beep
```

**Comment by wwoods** [comment]
Cool! Any idea when that change set might make it into a dask release?

**Comment by martindurant** [comment]
@jrbourbeau , do you want to take this opportunity to review and maybe merge?

**Comment by martindurant** [comment]
Ping, any reason not to merge this?
