### ISSUE TITLE
Parquet magic bytes not found in footer

### ISSUE THREAD

**Issue by maurogio** [dask/dask#7631]
**Error message: Parquet magic bytes not found in footer**:

We always recieve the `magic bytes error` if we use `dask.dataframe.read_parquet()` together with `adlfs` on different clients to store and append dask.dataframe.parquet files on the azure blob storage. The error seems to arise from the fact, that by using different clients there is no guarantee, that local caches are up to date.

**Minimal Complete Verifiable Example**:

We use two different clients (client 1 and client 2) for every step of the code added in this example. Every chunk of code needs to be executed completly (on the defined client) before changing client to execute the next chunk of code:

1. We use **client 1** (or jupyter notebook 1) to store a pandas dataframe as dask parquet file to azure blob storage `dask.dataframe.read_parquet()`.

2. Then use **client 2** (or jupyter notebook 2) to read the parquet file from the Azure blob storage `dask.dataframe.read_parquet()`. Probably the \_metadata file is cached at this point.

3. After that we use **client 1** (or jupyter notebook 1) again to append new rows to the parquet file stored on azure with `dask.dataframe.read_parquet(append=True)`.

4. Now, if we try to read the dask.dataframe again (`dask.dataframe.read_parquet()`) with **client 2** we get an error message (`OSError: Could not open parquet input source 'path_to_parquet_files/_metadata': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`). The cached \_metadatafile (step 2) does not contain the newest information now.

```python
#---------------------------------------------------
### Client 1 : Write pandas df as parquet file to Azure Blob Storage --> works fine

import pandas as pd
import pyarrow as pa
from dask import dataframe as dd

account_name = 'xxxxxx'
account_key = 'xxxxxx'
container_name = 'xxxxxx'

storage_options = {
    'account_name': account_name,
    'account_key': account_key
}
parquet_file = 'abfs://' + container_name

# Build pandas DataFrame
df = pd.DataFrame.from_dict(
    {'date': ['02.03.2021','10.04.2021','05.01.2021'],
     'var1': [1,2,3]}
)
# Define Pandas schema
pandas_schema = {
    'date': 'str',
    'var1': 'int64'
}
df = df.astype(pandas_schema)

# Reindex on date
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')
df = df.sort_values(by='date', ascending=True)
df = df.set_index('date')
# Build dask dataframe
pyarrow_schema = {
    'var1': pa.int64()
}
# Repartition on month
ddf = dd.from_pandas(df, npartitions=df.index.nunique())
ddf = ddf.repartition(freq='M')

# Upload data as parquet
ddf.to_parquet(parquet_file,
               engine='pyarrow',
               append=False,
               overwrite=False,
               write_metadata_file=True
               ,schema=pyarrow_schema
               ,storage_options=storage_options
              )


#---------------------------------------------------
### Client 2: Read only --> works fine
import pandas as pd
import pyarrow as pa
import sys
import importlib
import dask.dataframe

account_name = 'xxxxxx'
account_key = 'xxxxxx'
container_name = 'xxxxxx'

storage_options = {
    'account_name': account_name,
    'account_key': account_key
}
parquet_file = 'abfs://' + container_name

# Read dataframe from client 2
ddf = dask.dataframe.read_parquet(parquet_file,
                                  engine='pyarrow-dataset'
                                  ,storage_options=storage_options)


#---------------------------------------------------
### Client 1: Append data to parquet file on azure blob storage --> works fine

# Create new data
df_new = pd.DataFrame.from_dict(
    {'date': ['02.05.2021','10.06.2021','05.07.2021'],
     'var1': [4,5,6]}
)
df_new = df_new.astype(pandas_schema)

# Reindex on date
df_new['date'] = pd.to_datetime(df_new['date'], format='%d.%m.%Y')
df_new = df_new.set_index('date')

# Repartition on month
ddf_new = dd.from_pandas(df_new, npartitions=1)
ddf_new = ddf_new.repartition(freq='M')

# Append to parquet file on azure
ddf_new.to_parquet(
    parquet_file
    ,append=True
    ,ignore_divisions=False
    ,engine='pyarrow'
    ,schema=pyarrow_schema
    ,storage_options=storage_options
)

#---------------------------------------------------
### Client 2: Reading data again works only if we update the fsspec configuration to skip_instance_cache==True --> ERROR

# This leads to Error
ddf = dask.dataframe.read_parquet(parquet_file,
                                  engine='pyarrow-dataset'
                                  ,storage_options=storage_options)

# Workaround
#import fsspec
#fsspec.config.conf.update({ 'abfs': {'skip_instance_cache': True } })
```

**Workaround solves the error:**

We assumed that the \_metadata file on client 1 is cached and therefore isn't changed if we append with client 2. The workaround which worked for us was to deaktivate `fsspec` instance_cache globaly (or reset it manualy for every time we used dask.dataframe.read_parquet():

```python
import fsspec
fsspec.config.conf.update({ 'abfs': {'skip_instance_cache': True } })
```

**Environment**:

I use Anaconda und Jupyter Notebooks

- Python version: 3.8.5

*Package versions:*
- pyarrow==3.0.0
- pandas==1.2.4
- adlfs==v0.7.3
- fsspec==2021.04.0
- azure.storage.blob==12.8.0
- dask==2021.04.0

- Operating System: Windows 10 64-bit
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thank you have opening this issue @maurogio and for the clear description! I think @martindurant or @rjzamora will be able to provide some guidance.

**Comment by martindurant** [comment]
It is generally true, that fsspec-based filesystems will cache file details, because listing them can be rather expensive. If you expect that a file may be changed by some process elsewhere, then you should be sure to disregard the cached file listing, else your application will think the file has a different size to reality.
There are a couple of ways to do this:

- `fs.invalidate_cache`, where `fs` is the fsspec filesystem instance (you would have to create this, e.g., with `fsspec.filesystem("abfs", **storage_options`)
- `skip_instance_cache=True` as an option in the read call, which will ensure a new filesystem instance with zero cache every time, with an overhead cost for reconnecting
- arguments `use_listings_cache`, `listings_expiry_time` and `max_paths` in the read function to control the cache behaviour. I believe this works with abfs, though I haven't tested.

To pass arguments to fsspec, add them into your `storage_options`.

**Comment by maurogio** [comment]
Thank you very much for your inputs. Is it thinkable to integrate one of the the suggested solutions directly into the 'to_parquet()'  function?

**Comment by martindurant** [comment]
Sorry, what would you like to see happen? You can already add arguments to `storage_options` when calling `to_parquet` (although this question was about `read_parquet`).

**Comment by jrbourbeau** [comment]
Just checking in here @maurogio could you clarify what you would like to see happen?

**Comment by maurogio** [comment]
Hi and sorry for the late feedback

Yes, I thought it would be helpful not to have to deal with the problem separately each time. The best solution from my point of view would be to add a parameter in the `read_parquet()` (I actually described this wrong in my last post above) function, for example `reload_cache=True` or `False`. I think that would be "relatively" easy to include, wouldn't it?

Thank you for your attention to this matter

**Comment by martindurant** [comment]
As detailed, you *can* add a parameter to `read_parquet`, i.e., 
- `storage_options={"skip_instance_cache": True}`: new instance every time, could be expensive
- `storage_options={"listings_expiry_time"=10}`: old listings will be refreshed if they are more than 10s old
- `storage_options={"use_listings_cache"=False}`: don't cache listings, but still use single instance
(along with any other "storage options" you might need.

**Comment by maurogio** [comment]
OK thanks, I will close the issue now.
