### ISSUE TITLE
Dataframe repartition doesn't work for certain known_divisions cases

### ISSUE THREAD

**Issue by goodwanghan** [dask/dask#7638]
**What happened**:

```python
import dask.dataframe as dd
import pandas as pd

pdf = pd.DataFrame([[x] for x in range(5)],columns=["a"])
ddf = dd.from_pandas(pdf, npartitions=2, sort=True)
ddf.repartition(5)
```

This throws exception

`ValueError: New division must be unique, except for the last element`

Actually I have done a lot of experiments around this issue, and I can't find an alternative solution

* if setting `npartitions` in `from_pandas` to 5, the `ddf.npartitions` is 4 and `repartition` will still throw exceptions
* if setting `npartitions` in `from_pandas` to 5, then `ddf.npartitions` must be <=4 to avoid exceptions
* if setting `npartitions` in `from_pandas` to 2, then `ddf.npartitions` must be <=2 to avoid exceptions
* if setting `sort=False`, then there is no issue because now `known_divisions` is false

**What you expected to happen**:
`repartition` should not throw exceptions even for impossible cases for example we have 5 rows in total, but want to repartition to 6.

**Minimal Complete Verifiable Example**:[
The following code should not throw exceptions

```python
import dask.dataframe as dd
import pandas as pd

pdf = pd.DataFrame([[x] for x in range(5)],columns=["a"])
for sort in [True, False]:
    for p in [4,5,6]:
        ddf = dd.from_pandas(pdf, npartitions=2, sort=sort)
        ddf.repartition(p)

        ddf = dd.from_pandas(pdf, npartitions=5, sort=sort)
        ddf.repartition(p)

        ddf = dd.from_pandas(pdf, chunksize=1, sort=sort)
        ddf.repartition(p)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.4.1
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Ok so I think there a few things going on here. First, as a workaround, I want to point out that you can pass the exact divisions that you want to `repartition`. So for instance, this will give you 5 partitions each with `len==1`

```python
ddf2 = ddf.repartition(divisions=(0, 1, 2, 3, 4, 4))

for i in range(ddf2.npartitions):
    assert len(ddf2.partitions[i]) == 1
```

I still totally think that the `npartitions` behavior can be cleaned up though. The first thing I tried was getting rid of the uniqueness check. With that gone you don't get a failure even if you set npartitions to 5 or 6 or whatever. You just get empty divisions. So this brought me to the second issue which is that when using `npartitions` the last partition doesn't seem to ever be getting split so even if you allow duplicate divisions they just end up being empty. To make this concrete:

```python
In [1]: import dask.dataframe as dd
   ...: import pandas as pd
   ...: 
   ...: pdf = pd.DataFrame([[x] for x in range(5)],columns=["a"])
   ...: pdf = pd.concat([pdf] * 5)
   ...: ddf = dd.from_pandas(pdf, npartitions=2, sort=True)
   ...: ddf2 = ddf.repartition(10, force=True)

In [2]: for i in range(ddf2.npartitions):
   ...:     print(i, len(ddf2.partitions[i]))
   ...: 
0 0
1 5
2 0
3 5
4 5
5 0
6 0
7 0
8 0
9 10
```

I am not really sure what the behavior should be.

**Comment by goodwanghan** [comment]
Thank you for responding, yes there are many sub topics here. But actually your last case is something I care more about for my goal.

I think using repartition alone does not and should not have assumption how the framework will partition for you. There is no invalid case and the example you show is also valid to me.

But there is a very useful semantic I want to achieve which is even partitioning, and the extreme case is that I want one row in each partition. I think to achieve that it has to compromise on scale and speed, so there should be a separate interface to express this strong semantic.

But the question is given a dask dataframe how can I evenly repartition the dataframe if I really want to. Writing additional code is totally fine but I can’t figure out how to make it possible.

**Comment by jsignell** [comment]
Can you achieve what you want by using `partition_size` on repartition?

```python
import dask.dataframe as dd
import pandas as pd

pdf = pd.DataFrame([[x] for x in range(5)],columns=["a"])
ddf = dd.from_pandas(pdf, npartitions=2)
ddf2 = ddf.repartition(partition_size="76B")

for i in range(ddf2.npartitions):
     print(i, len(ddf2.partitions[i]))
```

**Comment by jrbourbeau** [comment]
Just checking in here, @goodwanghan does `partition_size` help?

**Comment by jrbourbeau** [comment]
Closing due to lack of response. Feel free to re-open as needed
