### ISSUE TITLE
block coarsen

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#764]
@rossant asked the following on [gitter](https://gitter.im/blaze/dask?at=560c435af4b61c106fb2dd70):

> is there a simple way to take a dask array and only keep 1 chunk out of k? for example chunk 0, k, 2k, etc along a given axis

This was my answer

```python
from dask.array.core import Array
from dask.core import flatten
from dask.base import tokenize
from toolz import merge

def block_coarsen(x, factor):
    """ Coarsen blocks by a factor along each axis

    Parameters
    ----------
    x: dask array
    factor: dict
        dict with axes and coarsening factors like {0: 2, 3: 2}
        to coarsen by a factor of two along axes 0 and 3

    Example
    -------

    >>> import dask.array as da
    >>> x = da.ones((100, 100), chunks=(10, 10))
    >>> block_coarsen(x, {0: 2, 1: 3})
    dask.array<block-c..., shape=(50, 40), dtype=float64, chunksize=(10, 10)>
    """
    factor = factor.copy()
    for i in range(x.ndim):
        if i not in factor:
            factor[i] = 1

    def good_key(key):
        return all(key[i + 1] % factor[i] == 0 for i in range(len(key) - 1))

    def new_key(key, name):
        return (name,) + tuple(key[i + 1] // factor[i] for i in range(x.ndim))

    name = 'block-coarsen-' + tokenize(x, factor)
    dsk = {new_key(k, name): k for k in flatten(x._keys()) if good_key(k)}

    chunks = tuple([c[::factor[i]] for i, c in enumerate(x.chunks)])

    return Array(merge(x.dask, dsk), name, chunks, x.dtype)
```

I'm not sure if we want this in public API or not.  I'm unsure what common use cases are for this.

**Comment by rossant** [comment]
Here's my use case for future reference: I have a big dask array `X` of size `(N, M)` with N=1e7 or 1e8. It is stored on disk in multiple chunks (in .npy files), of size (1000, M) for example. I want to compute something like PCA on a subset of all rows. Doing `X[::k, :]` may be inefficient because all files are loaded but few rows are taken from each chunk. It might be more efficient to select all rows from a small number of chunks regularly sampled across the entire dataset.

**Comment by shoyer** [comment]
Note that you don't need to read every npy file into memory if you use the mmap option. So using strides may be more efficient that you might think.

**Comment by rossant** [comment]
Yeah, but I'll still have to open all files wrt a handful. I should just benchmark...

**Comment by shoyer** [comment]
As far as implementation goes, I would probably suggest doing this with the higher level array API rather than dicts. Something like:
```python
from toolz import sliding_window
chunk_indices = np.r_[0, np.cumsum(array.chunks[0])]
array2 = da.stack([array[s:e] for s, e in sliding_window(chunk_indices)])
```

**Comment by mrocklin** [comment]
For large arrays the slicing implementation might actually generate non-trivial overhead.  The small size of the dict implementation seems encouraging to me.  It also has the virtue of being done :)

**Comment by shoyer** [comment]
Yes, done is great ;). In general, though, I think we could do a better job
of leveraging existing higher level code inside dask.array. The only
downside of the later is that it results in graphs with less directly
interpretable task names.

**Comment by mrocklin** [comment]
That's fair.  Dict stuff is also probably not as legible to most potential
developers.

**Comment by mrocklin** [comment]
There doesn't seem to be much interest in this operation.  I'd like to close for now.
