### ISSUE TITLE
ManagedIdentityCredential problems with dask but not adlfs

### ISSUE THREAD

**Issue by rhjmoore** [dask/dask#7642]
Here are the results of my tests. I'm not sure I understand the specifics of the error being reported, but I also have some thoughts on why ManagedIdentityCredential might be inherently problematic with the current structure.

    from azure.identity.aio import ManagedIdentityCredential as ManagedIdentityCredential_aio
    aio_mi_cred = ManagedIdentityCredential_aio(client_id=client_id)
    aio_abfs = AzureBlobFileSystem(**{'account_name': <account_name>, 'credential': aio_mi_cred})
    aio_abfs.ls('data')

This code functions as expected and lists the contents of the container "data". But now we try to use dask to read that data. For context, we have already initiated a connection to a local cluster.

    ddf = dd.read_parquet('abfs://data/input_data.parquet', engine='pyarrow', columns=[<column subset>],
                                                 storage_options={'account_name':<account_name>, 'credential': aio_mi_cred})
    df = ddf.compute()  # This subset of columns fits in memory

This now fails as the work is kicked off with:

    distributed.protocol.pickle - INFO - Failed to serialise (<adlfs.spec.AzureBlobFileSystem at <mem-reference>>, <bound method ArrowDatasetEngine.read_partition of <class 'dask.dataframe.io.parquet.arrow.ArrowLegacyEngine'>>, Empty DataFrame
    ....
    Exception: cannot pickle 'weakref' object

I don't know for sure, but it seem as if this is something to do with the ability to pickle async credentials in general, but then others say that it has worked for them. Does that include reading a file with dask, or just adlfs itself?

Finally, my understanding of the ManagedIdentityCredential protocol, which is admittedly limited, is that it represents an authorisation on the machine itself which is attached and recognised uniquely by an ActiveDirectory server. Apologies if I'm misunderstanding how this works...

This would mean that in general the approach of supplying a ManagedIdentityCredential object created on the client to a dask scheduler for it to pass on to dask workers in a cluster on different machines could be inherently flawed. Will the ManagedIdentityCredential object pass security checks from the AD that it's being used from the machine authorised? Would we not need to pass the ManagedIdentityCredential class and client_id for the workers to create their own objects to use for their own authentications? Or would this requirement pass away if the client, scheduler and workers all are granted permission for that same client_id?

_Originally posted by @rhjmoore in https://github.com/dask/adlfs/issues/226#issuecomment-832401709_

**Comment by jrbourbeau** [comment]
Thanks @rhjmoore. I'm going to close this issue in favor of keeping the conversation over in the `dask/adlfs` repo. The folks there will probably have more insight into how this serialization issue should be resolves
