### ISSUE TITLE
click version 8.0.0 seems removed _verify_python3_env which still called from dask utils.py

### ISSUE THREAD

**Issue by lgonzalezsa** [dask/dask#7658]
Installing from scratch in new conda environment with `conda install dask`; expecting to have dask-ssh working as expected but error thrown.

```
> dask-ssh
Traceback (most recent call last):
  File "/opt/conda/envs/dask_pyarrow/bin/dask-ssh", line 11, in <module>
    sys.exit(go())
  File "/opt/conda/envs/dask_pyarrow/lib/python3.9/site-packages/distributed/cli/dask_ssh.py", line 194, in go
    check_python_3()
  File "/opt/conda/envs/dask_pyarrow/lib/python3.9/site-packages/distributed/cli/utils.py", line 33, in check_python_3
    _unicodefun._verify_python3_env()
AttributeError: module 'click._unicodefun' has no attribute '_verify_python3_env'

```

**What you expected to happen**:
run dask-ssh to launch scheduler and workers.

**Minimal Complete Verifiable Example**:
1. Create new conda env: `conda create --name dask_pyarrow`
2. Install `conda install -c conda-forge dask=2021.4.1`
3. Validate click package is 8.0.0
3. Run `dask-ssh`

**Anything else we need to know?**:
Reverting to click 7.1.2 allow me to use dask-ssh 

**Environment**:

- Dask version: 2021.4.1
- Python version: 3.9.4
- Operating System: openSUSE
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for reporting @lgonzalezsa. The latest `distributed` release (version `2021.05.0`) includes updates to handle `click >= 8`. See https://github.com/dask/distributed/issues/4817 for more details. Additionally, we've patched all older releases of `distributed` on conda-forge to pin `click < 8`. For example, when I run the steps you've outlined above, `click=7.1.2` is installed:

```
$ conda create --name dask_pyarrow
$ conda activate dask_pyarrow
$ conda install -c conda-forge dask=2021.4.1
$ conda list click
# packages in environment at /Users/james/miniforge3/envs/dask_pyarrow:
#
# Name                    Version                   Build  Channel
click                     7.1.2              pyh9f0ad1d_0    conda-forge
```

Can you confirm that you're installing `dask` from `conda-forge`?

Alternatively, if you can update to the latest `dask` / `distributed` releases, then any `click`-related issues should also be resolved

**Comment by lgonzalezsa** [comment]
Perfect! all set now, also running 2021.5.0, no more issues.
Thank you!
`conda-forge `correct!
