### ISSUE TITLE
Add option for dask.dataframe.from_delayed to not combine dag of delayed tasks

### ISSUE THREAD

**Issue by yiliema** [dask/dask#7660]
I recently realized that when initializing a dask dataframe using `dask.dataframe.from_delayed`, the dag of the delayed tasks seems to be combined into one single node. This is not ideal for some situations when certain nodes on the dag are expensive and can be reused. Is it possible to add an option to not do this?

Example:
```
import dask
import dask.dataframe as dd

def data():
    return pd.Series([1,2,3])

def process_data(data):
    return data

data = dask.delayed(data)(dask_key_name='data')
processed_data = dask.delayed(process_data)(data, dask_key_name=f'process_data({data.key})')
ddf = dd.from_delayed(processed_data, meta=(None, int))
cl.compute(ddf)
```

![1](https://user-images.githubusercontent.com/6669228/118371982-bf955200-b574-11eb-846b-d7e126679cee.PNG)
![Capture](https://user-images.githubusercontent.com/6669228/118371984-c15f1580-b574-11eb-89a0-ac6c497c65f3.PNG)

**Comment by yiliema** [comment]
Does anyone know more about this? Is there some option that already exists but I'm not aware to achieve this?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @yiliema. When I run your example, I see separate tasks run for the `data`, `process_data`, and `from_delayed` steps. For example 

```python
import dask
import dask.dataframe as dd
import pandas as pd
from dask.distributed import Client, LocalCluster, wait

def data():
    return pd.Series([1,2,3])

def process_data(data):
    return data

data = dask.delayed(data)(dask_key_name='data')
processed_data = dask.delayed(process_data)(data, dask_key_name=f'process_data({data.key})')
ddf = dd.from_delayed(processed_data, meta=(None, int))

cluster = LocalCluster()
client = Client(cluster)

f = client.compute(ddf)
wait(f)

tasks = cluster.scheduler.tasks
from pprint import pprint
pprint(tasks)
```

outputs 

```
{"('from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)": <TaskState "('from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)" released>,
 'data': <TaskState 'data' released>,
 'finalize-73c37c917ec3a84a058289c3d894369f': <TaskState 'finalize-73c37c917ec3a84a058289c3d894369f' memory>,
 'process_data(data)': <TaskState 'process_data(data)' released>}
```

Where you can see four separate tasks have been computed.

Do you get a different output when you run the code snippet above?

**Comment by yiliema** [comment]
@jrbourbeau that's weird, I do see a different output where I only get 3 tasks, and `data` and `process_data` are combined together.
```
{"('data-process_data(data)-from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)": <Task "('data-process_data(data)-from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)" released>,
 "('from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)": <Task "('from-delayed-83ed1db18d78ee27840321f7996afc0a', 0)" released>,
 'finalize-73c37c917ec3a84a058289c3d894369f': <Task 'finalize-73c37c917ec3a84a058289c3d894369f' memory>}
```
My dask version is `2.30.0`, perhaps it's too old?

**Comment by jrbourbeau** [comment]
Ah, I see. Yeah there have been a lot of changes since `2.30.0`. If you upgrade to the latest release (version `2021.05.1`) then those tasks will automatically not be fused. Otherwise, you can set `dask.config.set({"optimization.fuse.active": False})` at the top of the code snippet, which should result in the same (non-fused) behavior. 

cc'ing @rjzamora for visibility as this is a place where disabling low-level fusion by default for DataFrames has popped up in the wild

**Comment by yiliema** [comment]
Thanks for the insight! I will close the issue.
