### ISSUE TITLE
Get data local to each worker

### ISSUE THREAD

**Issue by fredms** [dask/dask#7672]
Regarding this closed issue: https://github.com/dask/dask/issues/5331. 

I have a similar problem. On each worker, I'd like to get all partitions and run some operations on them.
Is the following suggestions in the thread still valid?

```
def collect_data(partition):
    worker = get_worker()  # get a handle on the worker that runs this task
    with worker._lock:
        if not hasattr(worker, "_inference_data"):
            worker._inference_data= []
    
    worker._inference_data.append(partition)
    return partition

df = df.map_partitions(collect_data)
```

Then I run the following function on each worker:

```
def run_on_worker():
    worker = get_worker()
    print(worker._inference_data)

client.run(run_on_worker)
```
But I got the attribute error:

`AttributeError: 'Worker' object has no attribute '_inference_data'`

**Comment by jsignell** [comment]
Don't you mean `_xgboost_data` rather than `_interface_data` in your second snippet? 

As an alternate approach, you might find it easier to use worker plugins to move data onto workers.

**Comment by trivialfis** [comment]
We adapted the approach from `dask_xgboost` in the new xgboost dask interface implementation.  Feel free to take a look into 

https://github.com/dmlc/xgboost/blob/86e60e3ba8c7e384da7aecd4e77e2518f5ff7f08/python-package/xgboost/dask.py#L345

**Comment by fredms** [comment]
Thanks @jsignell , @trivialfis for the reply. I updated the post.

The example was referring answer in  #[5331](https://github.com/dask/dask/issues/5331).

**Comment by jrbourbeau** [comment]
Closing due to lack of response. We can reopen if there's still and outstanding issue here folks would like to engage on
