### ISSUE TITLE
`dask.visualize` does not work with `filename=None`

### ISSUE THREAD

**Issue by theXYZT** [dask/dask#7685]
According to the documentation for [`dask.visualize`](https://docs.dask.org/en/latest/api.html#dask.visualize),

> **If filename is None, no file will be written**, and we communicate with dot using only pipes.

Unfortunately, it seems this actually throws an error!

```
/python3.8/site-packages/dask/dot.py in <genexpr>(.0)
    274 def graphviz_to_file(g, filename, format):
    275     fmts = [".png", ".pdf", ".dot", ".svg", ".jpeg", ".jpg"]
--> 276     if format is None and any(filename.lower().endswith(fmt) for fmt in fmts):
    277         filename, format = os.path.splitext(filename)
    278         format = format[1:].lower()

AttributeError: 'NoneType' object has no attribute 'lower'
```

Based on the documentation, it sounds like `filename=None` is meant to be supported, but [based on the tests for `dask.visualize`](https://github.com/dask/dask/blob/main/dask/tests/test_base.py#L936-L955), this case was never actually tested for and this error slipped under the radar.

**Comment by GenevieveBuckley** [comment]
Might be something @freyam might like to take a look at? (What do you think, @martindurant)

**Comment by martindurant** [comment]
Sounds like a perfect introduction to the dask graphviz code.
