### ISSUE TITLE
Chunk/memory management for CuPy-backed arrays

### ISSUE THREAD

**Issue by thomasaarholt** [dask/dask#7687]
**What happened**:
I'm trying to understand what the best approach to chunking is for doing dask operations on CuPy-backed arrays, and whether or not the current behaviour is the expected behaviour or a bug. The calculation below is *much* slower on the GPU than on the CPU.

To test this you'll need a GPU and an appropriate installation of CuPy. I am using a GTX 1080TI with 11 GB of memory and CuPy 9.0.0.

The following is a simple example where I try to use the GPU to sum a larger-than-memory array, with a chunk size of 1 GB:
```python
import cupy as cp
import numpy as np
import dask.array as da

huge_array = da.ones(
    (5000, 5000, 200), 
    chunks=(5000, 5000, 5), 
    dtype=float)

huge_array.nbytes / 1e9 # 40 GB in size

np.prod(huge_array.chunksize, dtype=float) * huge_array.dtype.itemsize / 1e9 # chunk size of 1 GB

huge_array = huge_array.map_blocks(cp.asarray) # make it a CuPy-backed array

array_sum = da.sum(huge_array)
array_sum.compute()
```
Upon `compute`, I get the following warning after a little while:
`C:\Users\thomasaar\Miniconda3\envs\gpu2\lib\site-packages\cupy\_creation\from_data.py:66: PerformanceWarning: Using synchronous transfer as pinned memory (1000000000 bytes) could not be allocated. This generally occurs because of insufficient host memory. The original error was: cudaErrorMemoryAllocation: out of memory
  return _core.array(a, dtype, False, order)`

**What you expected to happen**:
I expected that the above example would run without memory errors. The chunks of the `ones` array should be discardable after summing, IMO, meaning that we shouldn't end up in a situation where it can't allocate the 1GB complained about in the warning above.

**Some thoughts**
Does dask create the `ones` chunks on the GPU, or create it on the CPU first and then copy to the GPU? Could it be either of these that is the slow step? Or is CuPy not freeing up memory when it should?

**Environment**:

- Dask version: '2021.04.1'
- Python version: 3.9.4
- Operating System: Windows 10
- Install method (conda, pip, source): conda for all packages.

**Comment by quasiben** [comment]
1. You are correct that dask should be able to handle this.  I suspect that the chunksize is too large and if you lower it (say by a tenth) it should complete
2. This will be slow as you are going to pay a cost for transferring the numpy array from the host to cupy arrays on the device.  It's better, if you can, to allocate on the GPU:
> da.ones_like(cp.array(()), shape=(5000, 5000, 200), chunks=(5000, 5000, 5)

3. This will still be slow because cudaMalloc is a non-zero time operation and it's better to us some kind of memory management -- preferably preallocating memory on the GPU 
  a.  https://docs.cupy.dev/en/v8.5.0/reference/memory.html 
  b. https://docs.rapids.ai/api/rmm/nightly/basics.html#using-rmm-with-cupy

I would recommend `rmm` if you are planning on doing distributed cupy computing

**Comment by quasiben** [comment]
If you are doing larger than memory workloads you might also want to look at how to configure dask-cuda workers:
https://docs.rapids.ai/api/dask-cuda/nightly/spilling.html

**Comment by thomasaarholt** [comment]
Thanks, that was way faster! On the first call, the GPU takes some time (~10s) to "warm up", but after that the calls below are 60 times faster on the GPU with an 8 GB chunk size!


```python
import cupy as cp
import numpy as np
import dask.array as da

shape = (5000, 5000, 2000)
chunks = (5000, 5000, 40)
huge_array_cpu = da.ones(
    shape, 
    chunks=chunks, 
    dtype=float)

print(f"Array size: {huge_array_cpu.nbytes / 1e9} GB")

chunkbytes = np.prod(huge_array_cpu.chunksize, dtype=float) * huge_array_cpu.dtype.itemsize / 1e9
print(f"Chunk size: {chunkbytes} GB")

huge_array_gpu = da.ones_like(cp.array(()), shape=shape, chunks=chunks)

%time array_sum = da.sum(huge_array_cpu).compute()
# 1.34 s
%time array_sum = da.sum(huge_array_gpu).compute()
# 0.022 s - but 14 s on the first call
```

**Comment by quasiben** [comment]
The "warm up" should probably go away if you pre-allocate memory.  Glad things are working though!

**Comment by quasiben** [comment]
@astrofrog unfortunately, we don't really have a good example

It can be controlled with a combination of Dask and CuPy:
https://docs.dask.org/en/latest/configuration-reference.html#rmm
+

```python
client.run(cupy.cuda.set_allocator, rmm.rmm_cupy_allocator)
```

Or with Dask-CUDA directly:

```python
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster(rmm_pool_size="10GB", device_memory_limit=..., )

```

Can I ask you to file an issue on Dask-CUDA issue tracker:
https://github.com/rapidsai/dask-cuda/

There we can find the way to best document how to use RMM with Dask

**Comment by pentschev** [comment]
To add to @quasiben 's answer, we have a [`setup_memory_pool`](https://github.com/rapidsai/dask-cuda/blob/a884233cab309c5b66a9e8ca5a102a634260c6d1/dask_cuda/benchmarks/utils.py#L268-L287) function in Dask-CUDA benchmarks to do exactly that.
