### ISSUE TITLE
Access configuration docs out of date

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#7689]
Trying to follow the examples of `dask.config.get` in the [Access configuration docs](https://docs.dask.org/en/latest/configuration.html#access-configuration) and they are out of date. 
For example `dask.config.get("distributed.logging")` throws a `Key Error`. 

I believe the yaml under the file under "specify configuration"  is also outdated.

**Comment by jrbourbeau** [comment]
You're totally correct, that code block is out of date. We should update it to be consistent with the current default configuration values. If possible, it would be great it we could have those be actual code snippets which were run when the docs are build. That way, the output would always be up to date.

**Comment by ncclementi** [comment]
Interesting, I didn't know that was possible. @jrbourbeau Is there an existing example of code running as the docs are build? If you can drop a link here I can try to get it to work, for this particular case.

**Comment by jrbourbeau** [comment]
Ah sorry, to be clear I don't know if this is possible. I was just proposing that as a better solution (if it's possible) because we wouldn't have to periodically update things as code snippet output becomes outdated. Though just updating the existing docs is definitely an improvement.

**Comment by ncclementi** [comment]
I think for now, we can just update the docs, to reflect the most recent behavior. I can take a crack at this.

**Comment by jrbourbeau** [comment]
That sounds great, thanks @ncclementi
