### ISSUE TITLE
Elevate reduction operations to higher level

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#7690]
Currently both all of dask array/dataframe/bag implement reduction operations.  I'm sitting in the Dask High Energy Physics workshop and I'm seeing people implement their own collections (reasonably so, their data models are different).  They might benefit from high level reduction layers, similar to how we currently provide Blockwise.  

My guess is that this doesn't make sense, but if someone is looking to dive deeply into dask collections then they might look at how to generalize reduction operations that exist in each of the current established collections.

Again, I don't expect this to work (there are complications in each collection that may make it hard to generalize) but I thought I'd raise this anwyay.  Feel free to ignore.

**Comment by jcrist** [comment]
Closing as stale.
