### ISSUE TITLE
skiprows in read_fwf: Link to Issue #2065

### ISSUE THREAD

**Issue by rhjmoore** [dask/dask#7697]
Four years ago in issue #2065 an issue with skiprows was raised. At that time dask.dataframe.read_csv would skip the number of rows specified in skiprows from every partition, not just the first partition. This was acknowledged as a bug and fixed in pull request #2165.
https://github.com/dask/dask/pull/2165

There have been significant changes in that part of the code base and it appears that this bug has reverted.

    import dask.dataframe as dd
    import pandas as pd
    import dask
    
    print(dask.__version__)
    #  '2021.04.1'
    df = pd.read_fwf('data.txt', colspecs=<colspecs>, skiprows=1)
    ddf = dd.read_fwf('data.txt', colspecs=<colspecs>, skiprows=1).compute()
    print(len(df))
    # 1000000
    print(len(ddf))
    # 9999974
    print(ddf.npartitions)
    # 27

**Comment by jrbourbeau** [comment]
Thanks for reporting @rhjmoore. I could be missing something, but I'm not able to reproduce with the latest `dask=2021.5.0` release with the snippet below:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": range(10_000)})
df.to_csv("foo.csv", index=False)

ddf = dd.read_fwf("foo.csv", colspecs="infer", blocksize=600, sample=600, skiprows=1)
print(f"{ddf.npartitions = }")   # Should have more than 1 partition
print(f"{len(df) = }")
print(f"{len(ddf) = }")
```

outputs

```
ddf.npartitions = 82
len(df) = 10000
len(ddf) = 9999
```

Note that there are multiple partitions for `ddf` and the number of rows is one less than the corresponding pandas DataFrame (which is consistent with `skiprows=1`).

**Comment by rhjmoore** [comment]
Apologies, you are right. The bug this time is in skip_footer. I simplified my code too much and did not notice the other possibility.

There is a bug, but the bug is in skipfooter not in skiprows. Try this:

    df = pd.DataFrame({"a": range(10_000)})
    df.to_csv("foo.csv", index=False)

    ddf = dd.read_fwf("foo.csv", colspecs="infer", blocksize=600, sample=600, skiprows=1, skipfooter=1)
    print(f"{ddf.npartitions = }")   # Should have more than 1 partition
    print(f"{len(df) = }")
    print(f"{len(ddf) = }")

**Comment by ncclementi** [comment]
@rhjmoore Thank you for the example, I was able to reproduce the bug. It seems we will need to do a fix similar to the one in the PR #2165 . Would you like to take shot at it?

**Comment by rhjmoore** [comment]
> @rhjmoore Thank you for the example, I was able to reproduce the bug. It seems we will need to do a fix similar to the one in the PR #2165 . Would you like to take shot at it?

@ncclementi I could, yes, but have never contributed to such a project before. I'd just git clone, make a new branch from master, make the changes, then pull request (anyone in particular I should address it to?)?

**Comment by jrbourbeau** [comment]
Yeah, those are most of the main steps. Our complete contributing guide is available at https://docs.dask.org/en/latest/develop.html. Feel free to ping me and @ncclementi on the issue. Thanks!

**Comment by rhjmoore** [comment]
@jrbourbeau It looks like I'll have to change the structure of "parts" in dask.dataframe.io.csv line 372 to include a 4th entry named "is_last" and a new block_mask function to do the opposite of the existing one used for "is_first". Do you see a smarter way of knowing which block is the last one?

**Comment by rhjmoore** [comment]
@ncclementi @jrbourbeau Pinging you both for the PR as suggested.
