### ISSUE TITLE
IndexError: Out of bounds on buffer access (axis 0) while executing compute()

### ISSUE THREAD

**Issue by cyborgnaren** [dask/dask#7705]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-64-6bd294899a6d> in <module>
----> 1 df_dask.set_index('event_id')

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/core.py in set_index(***failed resolving arguments***)
   4093             from .shuffle import set_index
   4094 
-> 4095             return set_index(
   4096                 self,
   4097                 other,

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/shuffle.py in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, partition_size, **kwargs)
    160 
    161     if divisions is None:
--> 162         divisions, mins, maxes = _calculate_divisions(
    163             df, index2, repartition, npartitions, upsample, partition_size
    164         )

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/shuffle.py in _calculate_divisions(df, partition_col, repartition, npartitions, upsample, partition_size)
     33     mins = partition_col.map_partitions(M.min)
     34     maxes = partition_col.map_partitions(M.max)
---> 35     divisions, sizes, mins, maxes = base.compute(divisions, sizes, mins, maxes)
     36     divisions = methods.tolist(divisions)
     37     if type(sizes) is not list:

/Library/anaconda3/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    564         postcomputes.append(x.__dask_postcompute__())
    565 
--> 566     results = schedule(dsk, keys, **kwargs)
    567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568 

/Library/anaconda3/lib/python3.8/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     77             pool = MultiprocessingPoolExecutor(pool)
     78 
---> 79     results = get_async(
     80         pool.submit,
     81         pool._max_workers,

/Library/anaconda3/lib/python3.8/site-packages/dask/local.py in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    512                             _execute_task(task, data)  # Re-execute locally
    513                         else:
--> 514                             raise_exception(exc, tb)
    515                     res, worker_id = loads(res_info)
    516                     state["cache"][key] = res

/Library/anaconda3/lib/python3.8/site-packages/dask/local.py in reraise(exc, tb)
    323     if exc.__traceback__ is not tb:
    324         raise exc.with_traceback(tb)
--> 325     raise exc
    326 
    327 

/Library/anaconda3/lib/python3.8/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    221     try:
    222         task, data = loads(task_info)
--> 223         result = _execute_task(task, data)
    224         id = get_id()
    225         result = dumps((result, id))

/Library/anaconda3/lib/python3.8/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/Library/anaconda3/lib/python3.8/site-packages/dask/optimization.py in __call__(self, *args)
    961         if not len(args) == len(self.inkeys):
    962             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 963         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    964 
    965     def __reduce__(self):

/Library/anaconda3/lib/python3.8/site-packages/dask/core.py in get(dsk, out, cache)
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

/Library/anaconda3/lib/python3.8/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py in read_parquet_part(fs, func, meta, part, columns, index, kwargs)
    379 
    380     if isinstance(part, list):
--> 381         dfs = [
    382             func(fs, rg, columns.copy(), index, **toolz.merge(kwargs, kw))
    383             for (rg, kw) in part

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py in <listcomp>(.0)
    380     if isinstance(part, list):
    381         dfs = [
--> 382             func(fs, rg, columns.copy(), index, **toolz.merge(kwargs, kw))
    383             for (rg, kw) in part
    384         ]

/Library/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_partition(cls, fs, piece, columns, index, categories, **kwargs)
    786             for row_group in row_groups:
    787                 dfs.append(
--> 788                     parquet_file.read_row_group_file(
    789                         row_group,
    790                         columns,

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/api.py in read_row_group_file(self, rg, columns, categories, index, assign, partition_meta)
    236                     rg.num_rows, columns, categories, index)
    237             ret = True
--> 238         core.read_row_group_file(
    239                 fn, rg, columns, categories, self.schema, self.cats,
    240                 open=self.open, selfmade=self.selfmade, index=index,

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/core.py in read_row_group_file(fn, rg, columns, categories, schema_helper, cats, open, selfmade, index, assign, scheme, partition_meta)
    486                         scheme='hive', partition_meta=None):
    487     with open(fn, mode='rb') as f:
--> 488         return read_row_group(f, rg, columns, categories, schema_helper, cats,
    489                               selfmade=selfmade, index=index, assign=assign,
    490                               scheme=scheme, partition_meta=partition_meta)

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, scheme, partition_meta)
    539     if assign is None:
    540         raise RuntimeError('Going with pre-allocation!')
--> 541     read_row_group_arrays(file, rg, columns, categories, schema_helper,
    542                           cats, selfmade, assign=assign)
    543 

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign)
    512             continue
    513 
--> 514         read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    515                  selfmade=selfmade, assign=out[name],
    516                  catdef=out.get(name+'-catdef', None))

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef)
    424         else:
    425             skip_nulls = False
--> 426         defi, rep, val = read_data_page(infile, schema_helper, ph, cmd,
    427                                         skip_nulls, selfmade=selfmade)
    428         if rep is not None and assign.dtype.kind != 'O':  # pragma: no cover

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/core.py in read_data_page(f, helper, header, metadata, skip_nulls, selfmade)
    131 
    132         width = helper.schema_element(metadata.path_in_schema).type_length
--> 133         values = read_plain(io_obj.read(),
    134                             metadata.type,
    135                             int(daph.num_values - num_nulls),

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/encoding.py in read_plain(raw_bytes, type_, count, width, utf, stat)
     39             else:
     40                 return np.array([bytes(raw_bytes)], dtype='O')
---> 41         return unpack_byte_array(raw_bytes, count, utf=utf)

/Library/anaconda3/lib/python3.8/site-packages/fastparquet/speedups.pyx in fastparquet.speedups.unpack_byte_array()

IndexError: Out of bounds on buffer access (axis 0)

**Environment**:

- Dask version: 2021.4.0
- Python version: 3.8
- Operating System: MAC OS Catalina
- Install method (pip):

**Comment by quasiben** [comment]
hanks for raising an issue @cyborgnaren . Are you able to provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports) that we can run which reproduces the issue?

**Comment by jrbourbeau** [comment]
Closing due to lack of response. @cyborgnaren if you're able to provide a minimal example, let us know and we can re-open
