### ISSUE TITLE
Delayed method in a 'delayed_pure' context produces a different Delayed key every time it is evaluated

### ISSUE THREAD

**Issue by kdebrab** [dask/dask#7708]
**What happened**:

Delayed method in a `delayed_pure` context produces a different Delayed key every time it is evaluated.

**What you expected to happen**:

A method producing the same Delayed key every time it is evaluated with the same arguments in a `delayed_pure` context.

It works as expected when the whole class is decorated as delayed, but it doesn't if only a single method is decorated as delayed.

**Minimal Complete Verifiable Example**:

The following example:
```python
import dask

class A(object):
    BASE = 10

    def __init__(self, base):
        self.BASE = base

    @dask.delayed
    def addmethod(self, x, y):
        return self.BASE + x + y

a = A(100)

with dask.config.set(delayed_pure=True):
    assert a.addmethod(3, 4).key == a.addmethod(3, 4).key
```
incorrectly raises an AssertionError,

whereas the following correctly doesn't:

```python
import dask

@dask.delayed
class A(object):
    BASE = 10

    def __init__(self, base):
        self.BASE = base

    def addmethod(self, x, y):
        return self.BASE + x + y

a = A(100)

with dask.config.set(delayed_pure=True):
    assert a.addmethod(3, 4).key == a.addmethod(3, 4).key
```

**Environment**:

- Dask version: 2021.04.1
- Python version: 3.9.4
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
Thanks for raising this @kdebrab .  `delayed` should be wrapped around the function not the class, still, with this correct the context manager does not seem to work correct.  Can I ask you to test if explicitly calling pure=True on the delayed function works as expected ?

**Comment by kdebrab** [comment]
No, it also raises when calling pure=True on the delayed method.

In other words:
```python
assert a.addmethod(3, 4, pure=True).key == a.addmethod(3, 4, pure=True).key
```
raises for the first example (where the method is wrapped), but not for the second one (where the class is wrapped).

**Comment by kdebrab** [comment]
To my understanding, the reason the delayed method does not become pure,  is because of the containing class instance, which is passed as the first argument `self` and which is considered to be a mutable object, even when passing 'pure=True'.  In the case where the whole class is delayed, the containing class is considered immutable when passing 'pure=True', and thus also the method becomes pure.  This is achieved by the decorator through adding a `__dask_tokenize__` method.

I don't know whether that's on purpose.

As I don't want to delay the whole class (as otherwise all its methods become delayed), I'm considering to use the following workaround where I add the `__dask_tokenize__` method to the class through a decorator:

```python
def dask_tokenized(cls):
    class Tokenized(cls):

        def __init__(self, *args, **kwargs):
            self._args = args
            self._kwargs = kwargs
            super().__init__(*args, **kwargs)

        def __dask_tokenize__(self):
            return f"{cls.__name__}-{dask.base.tokenize(cls, self._args, self._kwargs)}"

    return Tokenized
```

Decorating the class with this decorator:
```python
@dask_tokenized
class A:
    BASE = 10

    def __init__(self, base):
        self.BASE = base

    @dask.delayed
    def addmethod(self, x, y):
        return self.BASE + x + y
```
Then:
```python
a = A(100)

assert a.addmethod(3, 4, pure=True).key == a.addmethod(3, 4, pure=True).key
```
doesn't raise an AssertionError anymore.

**Comment by kdebrab** [comment]
An alternative workaround (from https://stackoverflow.com/questions/51110803/are-class-methods-pure-in-dask) is:

```python
class A:
    BASE = 10

    def __init__(self, base):
        self.BASE = base

    def _addmethod(self, x, y):
        return self.BASE + x + y

    def addmethod(self, *args, **kwargs):
        return dask.delayed(self._addmethod, pure=True)(*args, **kwargs)
```
Then:
```python
a = A(100)
b = A(100)
c = A(101)

assert a.addmethod(3, 4).key == a.addmethod(3, 4).key
assert a.addmethod(3, 4).key == b.addmethod(3, 4).key
assert a.addmethod(3, 4).key != c.addmethod(3, 4).key
```
doesn't raise any AssertionError.
