### ISSUE TITLE
Implement `numeric_only` kwarg for dask.dataframe reductions

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7714]
In tracking down some failures on upstream tests #7710 I realized that dask.dataframe should implement `numeric_only` for reductions like `prod`, `sum` and so on. This has some extra urgency now since pandas 1.3.0 will raise a warning if the `numeric_only` kwarg is not explicitly set.

```python
FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
```

Ping @kkraus14 and @quasiben to check if cudf needs to implement this kwarg as well.

**Comment by kkraus14** [comment]
cc @shwina

**Comment by shwina** [comment]
cuDF supports this kwarg for reductions on `DataFrame` objects ([example](https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.max)).

**Comment by jsignell** [comment]
Thanks! 

As a side-note since I've been thinking about optimization, it would be neat to handle `numeric_only` on the dask-side as a cull.
