### ISSUE TITLE
should tornado be listed as dependency? 

### ISSUE THREAD

**Issue by suliuzh** [dask/dask#7717]
Hi
I am wondering if tornado should be listed in setup.py or requirements,txt?
As we can see, tornado is used in dask/base.py  and dask/tests/test_distributed.py as must. But when I use "pip install dask", it seems that tornado will not be installed automatically. So should tornado be listed as dependency? Or maybe it should be introduced as an extra dependnecy for the project?
![image](https://user-images.githubusercontent.com/27858725/119805311-b82a5d00-bf13-11eb-8feb-f01c3163fc30.png)

**Comment by TomAugspurger** [comment]
No, tornado is not a required dependency for Dask.

That line comes after an import of `distributed`, which requires tornado. You shouldn't be in a situation where you have distributed but not tornado.

**Comment by suliuzh** [comment]
Thanks for your reply.

**Comment by suliuzh** [comment]
I am wondering if these dependencies are used but not documented properly.

- tiledb
https://github.com/dask/dask/blob/d06339b1ff6379637d0d100f88fee97d35a65db8/conftest.py#L43
- bcolz
https://github.com/dask/dask/blob/3a552fbd3aef6a6815543a8054f8e2be6b2181b0/dask/dataframe/io/io.py#L260
- numba
https://github.com/dask/dask/blob/3a552fbd3aef6a6815543a8054f8e2be6b2181b0/dask/sizeof.py#L105

- h5py
https://github.com/dask/dask/blob/182a6ebd2de4a95d9d451b6cf1379702d2f10ee7/dask/array/core.py#L5143

- fastavro
https://github.com/dask/dask/blob/80a82008d5b02a08f6ff59d802defcc43247eb1a/dask/bag/avro.py#L143

**Comment by jsignell** [comment]
These are all optional packages. They can be used with dask, but there is plenty of functionality in dask that works without them.

**Comment by yuluc123** [comment]
also for cx_Freeze?

**Comment by suliuzh** [comment]
also for cx_Freeze?

**Comment by TomAugspurger** [comment]
That's only used by versioneer, which is not a runtime dependency.
