### ISSUE TITLE
Frobenius norm promotes float32 matrix to float64 norm

### ISSUE THREAD

**Issue by RogerMoens** [dask/dask#7718]
When applying a Frobenius norm on a float32 matrix, a float64 outcome is generated. A float32 should be expected (similar to numpy). I will try to have a look at this problem next week. Not sure whether the same is true for int-type and complex-type matrices. It might also improve the calculation speed a bit.

Cheers.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
a_64 = np.random.rand(500,500)
a_32 = a_64.astype(np.float32)
print(a_64.dtype, a_32.dtype) # float64 float32
print(np.linalg.norm(a_64, 'fro').dtype, np.linalg.norm(a_32, 'fro').dtype) # float64 float32

import dask.array as da
da_a_64 = da.asarray(a_64)
da_a_32 = da.asarray(a_32)
print(da_a_64.dtype, da_a_32.dtype) # float64 float32
print(da.linalg.norm(da_a_64, 'fro').dtype, da.linalg.norm(da_a_32, 'fro').dtype) # float64 float64
```

**Environment**:

- Dask version: '2021.04.0'
- Numpy version: '1.19.2'
- Python version: 3.8.3
- Operating System: Windows 10

**Comment by douglasdavis** [comment]
`da.linalg.norm` always hits a `np.promote_types` call:

https://github.com/dask/dask/blob/94dae165dfa30f1fdf76eef28e24414ff246d0f4/dask/array/linalg.py#L1461-L1462

Perhaps this should be avoided for float32 inputs?

**Comment by ncclementi** [comment]
@RogerMoens Thanks for reporting this! I just checked and this is still an issue on Dask 2021.07.2 and (Dask main).
Touching base to see if you were able to take a look at this, do you still want to take a crack at it?

**Comment by RogerMoens** [comment]
@ncclementi , I will try to give it a go next week.

**Comment by RogerMoens** [comment]
I don't see any similar thing (i.e. promoting the precision) being performed within the NumPy linalg norm function:
https://github.com/numpy/numpy/blob/5ae53e93b2be9ccf47bf72a85d71ea15d15a2eed/numpy/linalg/linalg.py#L2500

So, an easy fix would be to remove the promotion of types. However, I am trying to figure out why this was required. Would it be possible that it is done to handle complex input matrices? Do you have any idea why the type promotion is performed? @douglasdavis @ncclementi

To add to the speed of float32 vs float64 (@douglasdavis), if the matrix does not fit into memory (mostly the case when you go to float32 I presume), then it could be a tremendous speed up w.r.t. read/write.
