### ISSUE TITLE
-> 165                 dsvd = dask.array.linalg.svd(dataNoMissing)

### ISSUE THREAD

**Issue by mbathanb** [dask/dask#7723]
Hi,

I am trying to use eofunc_pcs function and I am always getting this error:

Please help me.

[EOF_MERRA2_Southern_Africa - Jupyter Notebook.pdf](https://github.com/dask/dask/files/6559190/EOF_MERRA2_Southern_Africa.-.Jupyter.Notebook.pdf)

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @mbathanb. Do you have a minimal reproducer you can post here? (See https://blog.dask.org/2018/02/28/minimal-bug-reports for more information)

**Comment by ncclementi** [comment]
@mbathanb The pdf that you provided is cut in half and can't be read.
I'm going to close this issue for now, but feel free to reopen with a minimal reproducer  (See https://blog.dask.org/2018/02/28/minimal-bug-reports for more information) so we can have more information to help you.
