### ISSUE TITLE
Error with `dd.utils.make_meta`

### ISSUE THREAD

**Issue by trivialfis** [dask/dask#7731]
# Reproduce:
```
>>> meta = {0: 'feat4'}
>>> from dask import dataframe as dd
>>> dd.utils.make_meta(meta)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fis/Workspace/XGBoost/lib/python3.8/site-packages/dask/utils.py", line 511, in __call__
    meth = self.dispatch(type(arg))
  File "/home/fis/Workspace/XGBoost/lib/python3.8/site-packages/dask/utils.py", line 505, in dispatch
    raise TypeError("No dispatch for {0}".format(cls))
TypeError: No dispatch for <class 'dict'>
>>> 
```

The error happens only with`2021.05.01`, works fine with `2021.05.0`.

# Versions
dask/distributed version: '2021.05.1'
install method: pip

**Comment by GenevieveBuckley** [comment]
Most likely related to this https://github.com/dask/dask/pull/7503

**Comment by GenevieveBuckley** [comment]
This also could be a useful test case ([example from here](https://github.com/dask/dask/issues/7589#issuecomment-824539060)):
```python
meta = dd.utils.make_meta([('x', np.int64), ('y', np.int64)])
```

**Comment by mlondschien** [comment]
The issue lies [here](https://github.com/dask/dask/commit/d2020bf30962c9660fba399392a3e8c9df59dca4#diff-d805dac0ba6fd4e90a18a453851ab73e8257c52b88b20b1ae1fd4c0aa46a0fe3R79), where
```python
@make_meta.register(object)
```
was replaced with
```python
@make_meta_obj.register(meta_object_types)
```

**Comment by GenevieveBuckley** [comment]
When I look at the code, it seems as though the expected/intended entry point is `make_meta_utils` 
https://github.com/dask/dask/blob/062ef68aeab7cbf1b15a3c88ede41fb1e28b357a/dask/dataframe/dispatch.py#L86-L108

I wonder whether `make_meta_util` should be renamed to `make_meta` and the other two dispatching functions (`make_meta` and `make_meta_obj`) be turned into private functions. There really seems like there's a mismatch here between what's in the code, and what people actually do (because that's what the dask docs tell them to do)

**Comment by GenevieveBuckley** [comment]
It's unclear to me if we need stronger messaging for other users/projects to use `make_meta_util`, or whether we need to do some shuffling internally in the dask codebase to support `make_meta` as the commonly used entry point for this.

**Comment by adonig** [comment]
I was able to get rid of this error by replacing the make_meta call with just a list of tuples.

**Comment by trivialfis** [comment]
@adonig Thanks for the suggestion, but I think we might be running into different errors.  According to https://github.com/dask/dask/pull/7732 (and my test), list input should also raise and error.

**Comment by trivialfis** [comment]
Thanks for everyone!
