### ISSUE TITLE
Remove enforcement of regular chunking in `to_zarr`

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7736]
AFAICT, [this check for irregular chunking in zarr](https://github.com/dask/dask/blob/4799c9d1dd9d9af7df1358aea11c4f49f15d3809/dask/array/core.py#L3345) is no longer needed.  It seems that zarr will automatically rechunk into regular chunks if given irregular chunks.  I'm not sure at what point zarr introduced this.

*However*, it is not as simple as removing the check.  As written, `return_stored=True` will return an object claiming the original chunking, not the chunking actually output by zarr.

I've run into this issue because `map_overlap`, through `da.overlap.overlap`, will [silently create irregular chunking](https://github.com/dask/dask/blob/4799c9d1dd9d9af7df1358aea11c4f49f15d3809/dask/array/overlap.py#L532). :/

**Comment by mrocklin** [comment]
I suspect that Dask is more able to handle the rechunking than Zarr is.
For example if two Dask processes are writing different parts of the same
chunk from different processes then something needs to make sure that
they're not overwriting each other.  Zarr isn't in a good position to do
this.  I suspect that it is still a good idea for Dask to
automatically rechunk.

**Comment by chrisroat** [comment]
I understand the separation of responsibility between zarr and dask on chunking.  That makes sense -- thanks.  I haven't encountered the use case of separate processes writing out data.

I would disagree with the notion that either should be automatically re-chunking, though I understand how it makes some things easier.
