### ISSUE TITLE
Option to skip auto-rechunking in da.overlap.overlap

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7737]
Would it be acceptable to add an option to da.overlap.overlap and map_overlap to raise an exception instead of [rechunking](https://github.com/dask/dask/blob/4799c9d1dd9d9af7df1358aea11c4f49f15d3809/dask/array/overlap.py#L532) when a small chunk is found?

This bit me pretty hard, and finding this feature has lead me to re-examine a lot of pieces of my code.  The code relies heavily on map_overlap & map_blocks & overlap, using them in ways that assume the chunking will always align (and that it is regular).  For example, if I chunk with map_blocks, the blocks I expect are going to be the centers of blocks I get if I chunk with map_overlaps.

**Comment by jsignell** [comment]
That sounds reasonable to me. There is a kwarg called `allow_rechunk` on gufunc. It seems like you could implement something similar and just have it be True by default.
