### ISSUE TITLE
HTML repr for HighLevelGraphs

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#7754]
There are many people now working on high level graphs.  We could probably improve the representation, both in text and in HTML in a notebook.  Probably the relevant information here is in `.layers` and `.dependencies`.  Of course, we could also improve the HTML repr of each layer if we wanted to get fancy.

cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Yeah I've definitely been thinking about this a bit lately. 

I know that @freyam is looking into an updated version of `vizualise` as part of his GSOC project.

**Comment by mrocklin** [comment]
That seems like a larger effort.  I suspect that there is a small bit of work that we can do in ~1day that would have good short term benefits.

**Comment by GenevieveBuckley** [comment]
I think I'd like to give this a go, if Jacob doesn't mind.

**Comment by jacobtomlinson** [comment]
Please do! Happy to review!

**Comment by GenevieveBuckley** [comment]
So it sounds like there might be a few more places scattered around where HTML representations might be nice to have. Can we collect some of those suggestions here?

(Like Jacob suggests above, some of these might make good short-sh tasks for @freyam)

**Comment by freyam** [comment]
Yes, I would love to work on this! :rocket:

**Comment by GenevieveBuckley** [comment]
@jacobtomlinson are there also some other places (maybe in distributed) that could be earmarked for html representations?

**Comment by jacobtomlinson** [comment]
Yeah there are a bunch of things we could do. Anything which a user might look at as part of debugging would probably benefit folks. 

I'm thinking things like the `Security` object which is used for configuring TLS.

Also `ProcessInterface` from `distributed.deploy.spec` would be useful.
