### ISSUE TITLE
Dataframe column selection can mix up columns

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask#7759]
Currently column selection when reading from CSV (and possibly other IO sources) can mix up column labels, with the wrong name attached to columns. I suspect that this is related to the column projection work that @rjzamora has been doing, but I haven't tracked down the source yet. It also doesn't seem to happen for every CSV.

MWE:

```python
import dask.dataframe as dd
import pandas as pd

URL = "https://github.com/datacamp/python-live-training-template/raw/master/data/airbnb.csv"
dd.read_csv(URL)[["name", "neighbourhood_full"]].head(2)
```
produces 
|    | name                       | neighbourhood_full                                 |
|---:|:---------------------------|:---------------------------------------------------|
|  0 | Brooklyn, Flatlands        | Cozy,budget friendly, cable inc, private entrance! |
|  1 | Manhattan, Upper West Side | Two floor apartment near Central Park              |

```python
import dask.dataframe as dd
import pandas as pd

URL = "https://github.com/datacamp/python-live-training-template/raw/master/data/airbnb.csv"
pd.read_csv(URL)[["name", "neighbourhood_full"]].head(2)
```
produces
|    | name                                               | neighbourhood_full         |
|---:|:---------------------------------------------------|:---------------------------|
|  0 | Cozy,budget friendly, cable inc, private entrance! | Brooklyn, Flatlands        |
|  1 | Two floor apartment near Central Park              | Manhattan, Upper West Side |

- Dask version: current `main`

**Comment by ian-r-rose** [comment]
Unfortunately, seems like it also might be a bit of a heisenbug. I only can reproduce some times, but often enough...

**Comment by rjzamora** [comment]
Interesting - Can you say roughly how often the problem shows up? I have tried the repo 100+ times without any issue yet.

**Comment by ian-r-rose** [comment]
> Interesting - Can you say roughly how often the problem shows up? I have tried the repo 100+ times without any issue yet. 

Looks like you got it, and with a much better reproducer than I did
