### ISSUE TITLE
How to implement reduce with dask as spark does ?

### ISSUE THREAD

**Issue by MordicusEtCubitus** [dask/dask#7766]
Dears,

I have a few trouble in implementing a map reduce algorithm with dask as spark does:

```python
>>> data = list(range(1, 100))
>>> rd = sc.parallelize(data)
>>> rd.reduce(lambda x, y : x * y)
933262154439441526816...and few other digits
```
When trying with dask I've got this issue:
```python
import dask.bag as db
import random
from operator import mul

numbers = list(range(100))

nb = db.from_sequence(numbers)

nb = nb.reduction(mul, mul)
nb.compute()

-> TypeError: mul expected 2 arguments, got 1
```
This produce a nice graph but fails when running as mul is getting a chained sequence of values in each partition rather than implementing a reduce on pair elements.

Thanks for helping,

Gaël,

**Comment by mrocklin** [comment]
Hi Gael,

You should take a look at the docstring for reduction, which says that it's
looking for a function to operate on partitions, not individual elements:
https://docs.dask.org/en/latest/bag-api.html#dask.bag.Bag.reduction

If you want to work with binary operators then you're probably looking for
fold: https://docs.dask.org/en/latest/bag-api.html#dask.bag.Bag.fold

I recommend taking a look through the Bag API docs here:
https://docs.dask.org/en/latest/bag-api.html

**Comment by MordicusEtCubitus** [comment]
Hi, thanks you for taking time to reply to my dummy question.
I had missed the `fold` method. It does what I was looking for.
But after thinking about it, reduction by partition is really nice too and can prevent from creating too much little tasks.
