### ISSUE TITLE
from_delayed can trigger large computation

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7768]
**What happened**:

Creation of a dask dataframe from delayed objects now triggers computation.

**What you expected to happen**:

When a using a `dd.from_delayed` with the `meta` keyword, no computation should be done.

**Minimal Complete Verifiable Example**:

The following code triggers the function with the sleep statement:

```python
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd

def gimme_a_hull():
    import time
    print("I'm so sleepy")
    time.sleep(1000)
    return pd.DataFrame({"segment_id": np.array([1,2,3])})

results = dask.delayed(gimme_a_hull)()
meta = dd.utils.make_meta([("segment_id", np.int64)])
dd.from_delayed(results, meta=meta)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.6.0
- Python version: 3.8.5
- Operating System: Ubuntu 20.04.01
- Install method (conda, pip, source): pip

**Comment by chrisroat** [comment]
I think [this line](https://github.com/dask/dask/blob/d9df00058f3b52b6c6d26ed836fbed9a7e3b4232/dask/dataframe/io/io.py#L591) is the culprit.

I'm not familiar with what `parent_meta` is representing here.  galipremsagar , what is the intention here, and is it possible to avoid triggering a computation?

**Comment by jsignell** [comment]
Thanks for raising the @chrisroa - I think https://github.com/dask/dask/pull/7769 will fix.
