### ISSUE TITLE
TestCase for get functions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#778]
With `distributed` we're starting to acquire more `get` functions.  It would be nice to be able to import a `TestCase` that enforced all known expectations on get functions.  This would require thinking about the spec and making, I think, a fairly simple `unittest` style `TestCase`.

This would also be nice because we could then codify the spec into something more than prose.

**Comment by cowlicks** [comment]
Is [this](https://dask.readthedocs.org/en/latest/scheduler-overview.html#the-get-function) the most formal specification we have?

**Comment by mrocklin** [comment]
https://dask.readthedocs.org/en/latest/spec.html

The objective here is probably to build a clean baseline system that other people can add to easily.

**Comment by jcrist** [comment]
Fixed by #1078.
