### ISSUE TITLE
Upstream test failures

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7783]
I think these are all just `FutureWarning`s coming from pandas. I'll try to take a look this week or next.

From: https://github.com/dask/dask/runs/2795401230

Here's the breakdown AFAICT

6: `FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.`
24: `FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only`
12: `FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only`

**Comment by jsignell** [comment]
@jorisvandenbossche @jbrockmendel the `freq` deprecation in Timestamp is kind of hard for me to wrap my head around. Is this the behavior that you expect? If so I think it's kind of impossible to pickle these.

```python
>>> import pandas as pd
>>> s =  pd.date_range("2000", periods=12, tz="US/Central", freq="D")
>>> s
DatetimeIndex(['2000-01-01 00:00:00-06:00', '2000-01-02 00:00:00-06:00',
               '2000-01-03 00:00:00-06:00', '2000-01-04 00:00:00-06:00',
               '2000-01-05 00:00:00-06:00', '2000-01-06 00:00:00-06:00',
               '2000-01-07 00:00:00-06:00', '2000-01-08 00:00:00-06:00',
               '2000-01-09 00:00:00-06:00', '2000-01-10 00:00:00-06:00',
               '2000-01-11 00:00:00-06:00', '2000-01-12 00:00:00-06:00'],
              dtype='datetime64[ns, US/Central]', freq='D')

>>> s[0]
Timestamp('2000-01-01 00:00:00-0600', tz='US/Central', freq='D')

>>> s[0].freq
FutureWarning: Timestamp.freq is deprecated and will be removed in a future version 
  s[0].freq

>>> pd.Timestamp('2000-01-01 00:00:00-0600', tz='US/Central', freq='D')
FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  pd.Timestamp('2000-01-01 00:00:00-0600', tz='US/Central', freq='D')

**Comment by jbrockmendel** [comment]
> Is this the behavior that you expect? 

Yes.  In a future version Timestamp will have no 'freq' attribute, so we've deprecated passing it as an argument or accessing the property.

> If so I think it's kind of impossible to pickle these.

Honestly haven't given that much thought.  Is there anything in particular we can do on our end to make this easier here?

**Comment by jsignell** [comment]
I think the best thing from our end would be to not include the freq when selecting from a `DatetimeIndex` is that possible?

**Comment by jsignell** [comment]
So it would be 

```python
>>> import pandas as pd
>>> s =  pd.date_range("2000", periods=12, tz="US/Central", freq="D")
>>> s
DatetimeIndex(['2000-01-01 00:00:00-06:00', '2000-01-02 00:00:00-06:00',
               '2000-01-03 00:00:00-06:00', '2000-01-04 00:00:00-06:00',
               '2000-01-05 00:00:00-06:00', '2000-01-06 00:00:00-06:00',
               '2000-01-07 00:00:00-06:00', '2000-01-08 00:00:00-06:00',
               '2000-01-09 00:00:00-06:00', '2000-01-10 00:00:00-06:00',
               '2000-01-11 00:00:00-06:00', '2000-01-12 00:00:00-06:00'],
              dtype='datetime64[ns, US/Central]', freq='D')

>>> s[0]
Timestamp('2000-01-01 00:00:00-0600', tz='US/Central')
```

**Comment by jorisvandenbossche** [comment]
For a failure like this:

```
     def test_make_timeseries():
        df = dd.demo.make_timeseries(
            "2000", "2015", {"A": float, "B": int, "C": str}, freq="2D", partition_freq="6M"
        )
    
>       assert df.divisions[0] == pd.Timestamp("2000-01-31", freq="6M")
```

I think here you can remove the `freq="6M"` in constructing the Timestamp in the `assert` line. The freq of a Timestamp is not considered when evaluating equality of two timestamps.

For pickling:

>  Is there anything in particular we can do on our end to make this easier here?

@jbrockmendel We should maybe ensure that unpickling a Timestamp does not generate a warning?

```
In [10]: idx = pd.date_range("2012", periods=3, freq="D")

In [11]: res = pickle.dumps(idx[0])

In [12]: pickle.loads(res)
/home/joris/miniconda3/envs/dev/bin/ipython:1: FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[12]: Timestamp('2012-01-01 00:00:00', freq='D')
```

It's not the unpickling that should warn about freq, I think, only if the user afterwards accesses the freq as normal.

**Comment by jsignell** [comment]
> I think here you can remove the `freq="6M"` in constructing the Timestamp in the `assert` line. The freq of a Timestamp is not considered when evaluating equality of two timestamps.

Yeah those ones are straightforward :+1:

> It's not the unpickling that should warn about freq, I think, only if the user afterwards accesses the freq as normal.

I agree with this. I think what's going on is that the unpickle instantiates `pd.Timestamp` with `freq` and that is why unpickling raises the warning. 

As a sidenote, I was also surprised that `hasattr(t, "freq")` was raising a warning.

**Comment by jbrockmendel** [comment]
> We should maybe ensure that unpickling a Timestamp does not generate a warning?

Agreed.

> I think the best thing from our end would be to not include the freq when selecting from a DatetimeIndex is that possible?

I'd be happy to see that change, but its an API change so i expect there would be pushback about doing it without the deprecation.

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/pandas-dev/pandas/issues/41949 to keep track of fixing the unpickle on the pandas side


> > I think the best thing from our end would be to not include the freq when selecting from a DatetimeIndex is that possible?
> 
> I'd be happy to see that change, but its an API change so i expect there would be pushback about doing it without the deprecation.

@jsignell what do you actually mean exactly with "include the freq when selecting from a DatetimeIndex"? 

You mean that if you slice a Series/DataFrame that has a DatetimeIndex with Timestamp objects, like `s[Timestamp(..):Timestamp(..)]` ?

**Comment by jsignell** [comment]
I just mean if you select one value from an index. It should not have a `freq`. 

This is what I am proposing:

```python
import pandas as pd

pd.date_range("2012", periods=3, freq="D")[0]
# Timestamp('2012-01-01 00:00:00')
```

**Comment by jsignell** [comment]
Ok I am going to close this since tests are passing on dask. But we are still affected by pandas-dev/pandas#41949 as described here: https://github.com/dask/dask/pull/7795#issue-668361488

**Comment by jrbourbeau** [comment]
Thanks for taking care of this @jsignell!

**Comment by jorisvandenbossche** [comment]
> I just mean if you select one value from an index. It should not have a freq.

I don't think you should care too much about this case where the accessed Timestamp has a freq. In most cases that doesn't matter (it's only for a few specific properties, like `is_year_start`, where it gives different behaviour, and I don't think dask is testing those)

**Comment by jsignell** [comment]
Yeah, I got rid of all the tests where we specifically are checking for `freq`. So the remaining issue is just with the pickle where the `freq` value gets serialized but then when we try to deserialize we get the `freq` deprecation warning.

**Comment by jorisvandenbossche** [comment]
Yes, we will ensure to fix that on the pandas side before the final 1.3 release.

**Comment by rwijtvliet** [comment]
> 
> Yes. In a future version Timestamp will have no 'freq' attribute, so we've deprecated passing it as an argument or accessing the property.
> 

Sorry if this reopens the issue - that's not my intention - but I cannot find the thread where this has been discussed and decided. I'd like to see if there is a way for me to code around this deprecation. Could someone point me to the correct thread? Many thanks.

**Comment by jsignell** [comment]
That would be somewhere in the pandas issue tracker or codebase @rwijtvliet, Dask is just following :)

**Comment by rwijtvliet** [comment]
Ah right, didn't see I was in the wrong project 😅
