### ISSUE TITLE
Using cuda cluster on HPC: Implementation question for a PBSCudaCluster/Job using LocalCUDACluster

### ISSUE THREAD

**Issue by MordicusEtCubitus** [dask/dask#7786]
Dears,

I have posted the same question on Dask Cuda project : https://github.com/rapidsai/dask-cuda/issues/653
In this post I try to understand how to create a CudaLocalCluster on HPC with SLURM/PBS as PBSCluster does for CPU and I provide a simple/naive implementation suggestion.

Would you mind to have a look at it in order to help me work on this implementation ?
But if I'm not wrong in my understanding, I'm a bit blocked by the fact that the `python -m distributed.cli.dask_worker` command used to start PBSJob is hard coded in Job class and can not be easily updated to use in place the `dask_cuda.cli.dask_cuda_worker` 

Could it be a parameter of PBSCluster/PBSJob/Job in order to be more generic/open to new workers alternatives like TPUWorkers...

Also, I have another question not asked in the same cuda post as I think this one is a better place:

I understand that Dask Workers are started using a classical PBS Job script on each node.
But how is started the Scheduler with PBSCluster ?

For what I understand, a local scheduler is created from the submission/login computer.
But on most HPC, the login computer is a front end to HPC cluster and is not strong enought to do computation.  
More, many times, it is not on the same network than the computation nodes.
So, sure I have missed something.
Could you help me to get a better understanding ?

With kind regards,

Gaël,

**Comment by jrbourbeau** [comment]
Thanks @MordicusEtCubitus. Let's close this issue to avoid having multiple conversations. I see things are moving along over in https://github.com/rapidsai/dask-cuda/issues/653 already
