### ISSUE TITLE
Dataframe read_csv globstring exclude does not actually exclude

### ISSUE THREAD

**Issue by shawnvosburg** [dask/dask#7792]
**What happened**:
When importing a globstring with an exclude (e.g. dd.read_csv('[!full]*.csv')), the file "full.csv" is read inside the dataframe.

**What you expected to happen**:
When running dd.read_csv('[!full]*.csv'), I expected to read all CSV files except **full.csv**. I expected that Dask DataFrame follows the same convention as the python standard library glob. 

With the python standard library glob, glob.glob('[!full]*.csv') returns a list of all CSV files in the current directory that is not named full.csv. 

**Minimal Complete Verifiable Example**:
Assuming files:
1.csv:
```
col1,col2,col3
a,a,a
```
2.csv:
```
col1,col2,col3
a,a,a
```
full.csv:
```
col1,col2,col3
c,c,c
d,d,d
```

Current (bad) behavior: 
```python
import dask.dataframe as dd
ddf = dd.read_csv('[!full]*.csv')
ddf.compute()
```
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>col1</th>
      <th>col2</th>
      <th>col3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>c</td>
      <td>c</td>
      <td>c</td>
    </tr>
    <tr>
      <th>1</th>
      <td>d</td>
      <td>d</td>
      <td>d</td>
    </tr>
  </tbody>
</table>
</div>

Workaround:
```python
import dask.dataframe as dd
import glob
ddf = dd.read_csv(glob.glob('[!full]*.csv'))
ddf.compute()
```
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>col1</th>
      <th>col2</th>
      <th>col3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>a</td>
      <td>a</td>
      <td>a</td>
    </tr>
    <tr>
      <th>0</th>
      <td>b</td>
      <td>b</td>
      <td>b</td>
    </tr>
  </tbody>
</table>
</div>

**Anything else we need to know?**:

**Environment**:

- Dask version: '2021.05.0'
- Python version: '3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:34) [MSC v.1916 64 bit (AMD64)]'
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for reporting this! And I'm glad you have found a workaround. @martindurant this looks like an fsspec issue to me.

**Comment by shawnvosburg** [comment]
@jsignell after reading the docs in fsspec, I found out that they do not support negation like the glob standard library, unlike the term "globstring" from the dask docs led me to assume. 

Relevent fsspec section: https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/spec.html#AbstractFileSystem.glob

**Comment by jsignell** [comment]
Nice detective work! If you have any ideas about how to make the dask documentation clearer, please feel free to open a  pull request

**Comment by martindurant** [comment]
You may wish to raise this at fsspec, which is where the glob lives - and feel free to have a try to convert the glob format into regex and fix this!
However, I think this issue should be closed.

**Comment by jsignell** [comment]
I agree with Martin.
