### ISSUE TITLE
Parallel fetch from mongo tables

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#7793]
How should we fetch documents from MongoDB in parallel?

If we copy the process that we use with SQL databases we would want to ...

1. find an ordered and indexed field
2. query for the minimum and maximum values of that field and the number of records
3. query for a sample of values to determine rough record size
4. Use the information above to determine how many partitions we want, and partition the full range of that indexed field into that many sub-ranges
5. Create a dask bag (probably?) of many subqueries 

Mongo is a bit different from SQL databases in that it has less structure.  It [does have indexes](https://docs.mongodb.com/manual/indexes/) though, and in particular it has a [guaranteed `_id` field](https://docs.mongodb.com/manual/core/document/#std-label-document-id-field) which is guaranteed to be indexed.  This is great!  However, it also looks like the default value is a UUID, which is less great.  But fortunately it still appears to be ordered, using a timestamp, which is great again!  https://docs.mongodb.com/manual/reference/method/ObjectId/

This format isn't guaranteed.  `_id` fields can be user defined, but the common case situations might be ok here.

**Comment by crusaderky** [comment]
The default value for \_id is a glorified client-side timestamp. It is typically ordered but offers no guarantee to be - particularly when multiple clients collaborate to populate a collection in parallel. Also, the client can explicitly override the _id with whatever unique hashable it pleases.

Also, being a timestamp, knowing start, stop, and number of documents alone won't tell you how to partition your chunks. You have no idea if the documents were uploaded with constant-ish periodicity, in bursts, or more or less randomly.

The easy way out is to ask the user to make sure the collection features a monotonically ascending integer identifier for the rows of the dask collection. They'll then need to create an index on it together with whatever identifies the dask collection.

At the bare minimum, it only needs to be unique most of the time (without guarantee) and coarsely linearly spaced. In such a case, your dask chunks will be nan-sized. You should ask the user (though a parameter) if it is deterministically unique and contiguous, in which case your chunks can have an int size.

Take a look at my library https://xarray-mongodb.readthedocs.io/, particularly the database reference, which in turn is heavily inspired by GridFS.

A separate problem you'll need to deal with is authentication. pymongo.Client can't be pickled. xarray-mongodb works around it by monkey-patching the class to make it pickle-able; each key of your dask graph will contain the access credentials (which of course can be a security hazard, fixable by using a local certificate file).

**Comment by mrocklin** [comment]
> The easy way out is to ask the user to make sure the collection features a monotonically ascending integer identifier for the rows of the dask collection. They'll then need to create an index on it together with whatever identifies the dask collection.

We're looking for a general purpose solution to read tables that were not written with Dask in mind, so this option is out I'm afraid.

> The default value for _id is a glorified client-side timestamp

Yeah, I agree that that's not ideal for uniform-based partitioning.  Another solution here would be to sample.  It looks like the aggregation pipeline syntax [provides sampling](https://docs.mongodb.com/manual/reference/operator/aggregation/sample/). Do we know if it is cheap to uniformly sample?  If so then I would recommend that we sample, say, 10x more `_id`s than we have partitions.  Then we can partition those and use them.  This feels like an inelegant but usually-pretty-ok solution.

**Comment by mrocklin** [comment]
> A separate problem you'll need to deal with is authentication. pymongo.Client can't be pickled.

Does the `pymongo.Client` have sufficient information about Auth that we can capture that information and send it along in the task?  We'd be happy to recreate a `pymongo.Client` in every task.

**Comment by selshowk** [comment]
A couple of points:
- mongo supports projections on queries to reduce the output size and if you project to only the `_id` field then the query uses just the index (which is stored separately on disk and much more efficient to access).  using this we can, in principle, introspect the id field **relatively** inexpensively.
- combining the above with @mrocklin's subsamping suggestion we should be able to cheaply sample uniformly spaced ids hitting only the index and then use them in range queries for partitions.
- another trick/approach is to use a "LIKE" query to shard the collection over a pre-defined number of partitions without any extra queries (if that's what we want to do).  assuming that the `_id` field is uniformly distributed we can simply partition on alphanumeric prefixes that generate the right number of partitions.  This will **not** work with the default `_id` because the later is based on timestamps so is not uniformly distributed at all.

Something else to think about how is how to "consume" the query in Dask.  @mrocklin mentioned bags but often a collection in mongo has a fixed schema (even if this is not enforced) and I can imagine users wanting to read it into a dataframe instead of bags so I imagine this should be an option.

**Comment by mrocklin** [comment]
>  @mrocklin mentioned bags but often a collection in mongo has a fixed schema (even if this is not enforced) and I can imagine users wanting to read it into a dataframe instead of bags so I imagine this should be an option.

There is a Bag.to_dataframe method that has some basic logic to guess schema (or should if it doesn't).  This feels like the right first step just because it is the most generic.

If that workflow isn't solid though then I agree that a good second step would be to go directly to Pandas.

**Comment by crusaderky** [comment]
> > A separate problem you'll need to deal with is authentication. pymongo.Client can't be pickled.
> 
> Does the `pymongo.Client` have sufficient information about Auth that we can capture that information and send it along in the task? We'd be happy to recreate a `pymongo.Client` in every task.

No. That's exactly what my monkey patch does. Understandably, the Client object won't store anywhere your clear-text password after login. 

> using this we can, in principle, introspect the id field relatively inexpensively.

Copying client-side all of the ids for a use case that is large enough to justify using dask makes me very nervous - unless you have few-ish large documents which is a much less common case of millions small documents. I'll play with it and see if we can figure out some kind of server - side aggregation

**Comment by mrocklin** [comment]
> I'll play with it and see if we can figure out some kind of server - side aggregation

My understanding is that the aggregation pipelines has a `$sample` operation which does this for us server side.

**Comment by selshowk** [comment]
> Copying client-side all of the ids for a use case that is large enough to justify using dask makes me very nervous - unless you have few-ish large documents which is a much less common case than millions small documents. I'll play with it and see if we can figure out some kind of server - side aggregation

I completely agree we should not be aiming to copy all the ids.  Rather we should use `$sample` and @mrocklin suggested and use a projection to ensure that the query only uses the index rather than the collection.

**Comment by crusaderky** [comment]
It turns out that what we want is available out of the box in MongoDB >=3.6 (Nov 2017).

```python
>>> match = ... # User-defined match that defines the dask collection within the MongoDB collection
>>> n_docs = next((coll.aggregate([
...      {"$match": match},
...      {"$count": "count"},
... ])))["count"]
>>> n_chunks = chunk_size // n_docs + bool(chunk_size % n_docs)  # round up
>>> list(coll.aggregate([
...     {"$match": match},
...     {"$bucketAuto": {"groupBy": "$_id", "buckets": n_chunks}},
... ], allowDiskUse=True))
[{'_id': {'min': ObjectId('60c76c852020f270dbf6fb2e'),
   'max': ObjectId('60c76c852020f270dbf702fe')},
  'count': 2000},
 {'_id': {'min': ObjectId('60c76c852020f270dbf702fe'),
   'max': ObjectId('60c76c852020f270dbf70ace')},
  'count': 2000},
 {'_id': {'min': ObjectId('60c76c852020f270dbf70ace'),
   'max': ObjectId('60c76c852020f270dbf7129e')},
  'count': 2000},
 {'_id': {'min': ObjectId('60c76c852020f270dbf7129e'),
   'max': ObjectId('60c76c852020f270dbf71a6e')},
  'count': 2000},
 {'_id': {'min': ObjectId('60c76c852020f270dbf71a6e'),
   'max': ObjectId('60c76c852020f270dbf7223d')},
  'count': 2000}]
```

from which you can simply build the query for each chunk:
```python
>>> coll.aggregate([
...     {"$match": match}, 
...     {"$match": {"_id": {"$gte": id_min, "$lt": id_max}}},
... ])
```
The count from the above query also lets you set the chunk size - no need for NaN-sized chunks.


if you wish to auto-determine chunk size from document size, it's as simple as
```python
>>> coll.find_one(match)
```

Things will get _substantially_ more complicated if the user wants the results sorted by anything other than \_id - do we care about offering it?

**Comment by crusaderky** [comment]
Even better, you can get a size measure without fetching any actual document:

```python
>>> next(coll.aggregate([
...     {"$match": match},
...     {"$limit": 1},
...     {"$project": {"_id": 0, "size": {"$bsonSize": "$$ROOT" }}},
... ]))["size"]
```
The above will require MongoDB 4.4 (July 2020) though, so there should be a fallback for older databases.

**Comment by mrocklin** [comment]
> Things will get substantially more complicated if the user wants the results sorted by anything other than _id - do we care about offering it?

Not to start :) 

> Even better, you can get a size measure without fetching any actual document:

I suspect that bson sizes will be more compact than Python objects in memory.  Pulling back a sample of local results seems nicer to me *if* we have a good way to measure the size of things in Python memory.  If not, then using bson sounds grand.  I don't think that avoiding a fetch is a large motivator though.  My *guess* (which will sometimes be wrong, for sure) is that most documents are small.

**Comment by crusaderky** [comment]
> I suspect that bson sizes will be more compact than Python objects in memory. 

It's a crude approximation which most of the times should be good enough. BSON is not as efficient as msgpack but not as bad as Python objects in memory.

**Comment by ncclementi** [comment]
Closing this issue now, since we have a `dask-mongo` connector now. Leaving a link here for documentation purposes. 
https://github.com/coiled/dask-mongo

**Comment by jrbourbeau** [comment]
🚀 woo!
