### ISSUE TITLE
function in SubgraphCallable does not get the right argument value

### ISSUE THREAD

**Issue by pkuwwt** [dask/dask#7798]
**What happened**:

It seems that the functions in `SubgraphCallable` view the constant argument as constant forever.

When I submit `print(1)` and `print(2)` in `SubgraphCallable`, `print(2)` generates `1`.

**What you expected to happen**:

I expect the functions in subgraph respect the actual arguments, other than assuming it is `CONSTANT`, which is confusing.

**Minimal Complete Verifiable Example**:

```python
from dask.optimization import SubgraphCallable
from distributed import Client
import logging
from time import sleep

def print_(a):
    logging.error(a)


def submit():
    in_keys = []
    out_key = 'z'
    graph1 = SubgraphCallable({'x': 'abc', 'z': (print_, 'x')}, out_key, in_keys)
    graph2 = SubgraphCallable({'x': 'def', 'z': (print_, 'x')}, out_key, in_keys)
    client = Client('127.0.0.1:8786')
    client.gather(client.submit(graph1))
    sleep(1)
    client.gather(client.submit(graph2))


# 1. dask-scheduler
# 2. dask-worker 127.0.0.1:8786
# 3. python main.py
# Expected worker log:
#   ERROR:root:abc
#   ERROR:root:def
# Actual worker log:
#   ERROR:root:abc
#   ERROR:root:abc
if __name__ == '__main__':
    submit()
```

**Environment**:

- Dask version: 1.19.4
- Python version: 3.9.0
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for opening this issue @pkuwwt, I just ran your example on latest dask (2021.06.0) and I got your expected result. I recommend updating your version of dask. I am closing this now, but please reopen if updating dask does not resolve this issue.

**Comment by pkuwwt** [comment]
Well, I tried 2021.06.0 with no luck on MacOS.

**Comment by pkuwwt** [comment]
I can reproduce the problem by docker.

`Dockerfile`

```
FROM python:latest
RUN pip install dask==2021.06.0 distributed==2021.06.0 flask
ADD app.py /app.py
CMD ["python", "/app.py"]
```

`app.py`

```python
from dask.optimization import SubgraphCallable
from distributed import Client
from flask import Flask, jsonify

def test(a):
    return a


def get_results():
    in_keys = []
    out_key = 'z'
    graph1 = SubgraphCallable({'z': (test, 1)}, out_key, in_keys)
    graph2 = SubgraphCallable({'z': (test, 2)}, out_key, in_keys)
    client = Client('dask-scheduler:8786')
    result1 = client.gather(client.submit(graph1))
    result2 = client.gather(client.submit(graph2))
    return [result1, result2]


app = Flask(__name__)

@app.route('/')
def test_graph():
    return jsonify(get_results())

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
```

`docker-compose.yml`

```yml
version: "3.0"

services:
  dask-scheduler:
    image: dask/test_graph
    build:
      context: ./
    command: dask-scheduler
  dask-worker:
    image: dask/test_graph
    command: dask-worker tcp://dask-scheduler:8786
  dask-client:
    image: dask/test_graph
    ports:
      - "5000:5000"
```

After `docker-compose up --build` and browse `127.0.0.1:5000`, I get

```
[1, 1]
```

And the expected result should be
```
[1, 2]
```

**Comment by jsignell** [comment]
Ok thanks for providing more setup information. I had originally run the example using `LocalCluster` like: 

```python
client = Client()
```

But I can reproduce now with the example that you've provided.

**Comment by jsignell** [comment]
@jrbourbeau is there some sort of distributed caching or a layer of optimization that might be causing this?

**Comment by pkuwwt** [comment]
Maybe there is caching mechanism. I can address this problem by using another `name` for `SubgraphCallable`

**Comment by jsignell** [comment]
Oh! I should have noticed that :facepalm: yeah you cannot use the same name for multiple tasks in a task graph.
