### ISSUE TITLE
Reset subset of levels in multi-index from groupby

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#7807]
Multi-indices aren't supported, but are generated by `groupby`, which does allow grouping by multiple columns.  Should one immediately try to go back to a single index?  If so, it seems one is forced to do a computation because `reset_index` does not have a `level` argument, and `set_index` triggers a computation in most cases.  Can the computation be avoided if one wants to keep the partitioning from the `groupby`?

Basically, is there a way to drop just level `b` in the following w/o a computation?

```
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd

def make_df():
    raise RuntimeError

ddf_delayed = dask.delayed(make_df)()
meta = dd.utils.make_meta([('a', np.int64), ('b', np.int64), ('c', np.int64)])
ddf = dd.from_delayed(ddf_delayed, meta=meta)
ddf.groupby(['a', 'b']).sum().reset_index()

ddf = ddf.set_index('a')  # Triggers computation
```

**Comment by jsignell** [comment]
I would say that multiindexes are kind of supported. Is there a workflow that you can share that doesn't work?

**Comment by chrisroat** [comment]
The dask code definitely seems to be hostile to multi-indices:

```
import pandas as pd
import dask.dataframe as dd
dd.from_pandas(pd.DataFrame({'a': [1], 'b': [2], 'c': [3]}).set_index(['a', 'b']), npartitions=1)
```
```
NotImplementedError: Dask does not support MultiIndex Dataframes.
```

You can back your way into multi-indices in certain ways, like by doing a `groupby`.  I've found, however, that when writing multi-index dataframes out and reading them back in (I use pyarrow), the ordering of the multi-index levels can change.  I've mostly abandoned trying to use them, once I've discovered they aren't 100% supported -- but I still have the occasional groupby.

It would be great to be able to drop a subset of levels (without reordering, so not triggering computation), so I'm posting this feature request.  It likely has to wait on the work to fully implement multi-indices (i.e. https://github.com/dask/dask/issues/1493)

**Comment by jsignell** [comment]
Thank you for the additional context. I think it might be possible to handle this by supporting the `as_index` kwarg in pandas.groupby:

```python
import pandas as pd

df = pd.DataFrame({"a": ["cat", "dog", "dog", "dog"], "b": [1, 0, 0, 1], "c": [1, 2, 3, 4]})
df.groupby(["a", "b"], as_index=False).sum()
#      a  b  c
# 0  cat  1  1
# 1  dog  0  5
# 2  dog  1  4
```

Does it seem like this would work for your situation?

**Comment by jsignell** [comment]
Fundamentally, calling `set_index` on an unknown column will always trigger computation. Dask needs to figure out the divisions between each partition in the index. If you don't want to trigger that computation, only do `reset_index`. 

If the issue is that you don't want to include a RangeIndex in your parquet file, then there is probably a kwarg in `to_parquet` to ignore the index.

**Comment by chrisroat** [comment]
The solution to avoid `set_index` is exactly what I so now, but it leaves me without having any of my columns as my index.

In the example above, I do not *want* to call set_index, but I do want `a` as the index.  I just want to drop the `b` column in the example above (at least, as long as true multi-index support is missing).  But I do not see a way to do it without calling `reset_index` followed by `set_index`.    So that is the crux of this issue.

If `reset_index` supported the `level` keyword, that would be one solution.   But without that, I was curious if there was some other magic combination of calls/keywords that could achieve the same effect.

[Technically, pandas does allowed unsorted indices.  Does dask always require a sorted index in the way it handles partitions?]

**Comment by jsignell** [comment]
Even if there was some mechanism to include `level` in `reset_index` dask would still need to do some computation to know which rows are in which partition.

> Does dask always require a sorted index in the way it handles partitions?

Yeah, the way that dask knows which rows are in which partition is it sorts the index (or you can tell it the index is already sorted to avoid this step) and then sets the index values at the boundary between partitions as `divisions`. 

Some workarounds are: try to see if your function really _has to_ have `a` as the index. If you find that it does, you might consider setting `a` as the index within your `chunk` function and then call `reset_index` at the end of the `chunk` function. But you should be careful with that approach since it might lead to wrong answers if your chunk function assumes that it has access to all adjoining rows.

Hopefully this is making some sense.

**Comment by chrisroat** [comment]
It does make sense.  I hadn't really understood how much indexing and partitioning are interlinked.    I am not morally opposed to a single `a` value was spread over a few partitions (say, if `reset_index(level='b')` has a parameter to keep the original partitioning), but I gather that does not fit the model.

**Comment by jsignell** [comment]
I was chatting with @martindurant and he reminded me that you can use `map_partitions` as a layer of your graph. So you can do something like:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": ["cat", "dog", "dog", "dog"], "b": [1, 0, 0, 1], "c": [1, 2, 3, 4]})
ddf = dd.from_pandas(df, 2).groupby(["a", "b"]).sum().reset_index()

ddf.map_partitions(lambda df: df.set_index("a"))
```

So for your original example:

```python
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd

def make_df():
    raise RuntimeError

ddf_delayed = dask.delayed(make_df)()
meta = dd.utils.make_meta([('a', np.int64), ('b', np.int64), ('c', np.int64)])
ddf = dd.from_delayed(ddf_delayed, meta=meta)
ddf = ddf.groupby(['a', 'b']).sum().reset_index()

ddf.map_partitions(lambda df: df.set_index("a"))
```

**Comment by chrisroat** [comment]
Aha!  Neat idea.  That's great that a change of index in map_partitions gets propagated.  

I wanted to see learn how partitioning would handle `a` values that were split across multiple partitions after a group by of `[`a`, `b`]`.  But in the small test below, I didn't get far into the investigation.  The `sum` collapsed the frame to a single partition -- even for a groupby on single column.

I think I am still early-on in understanding dataframes.

```
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd

def make_df():
    raise RuntimeError

ddf_delayed = dask.delayed(make_df)()
meta = dd.utils.make_meta([('a', np.int64), ('b', np.int64), ('c', np.int64)])

ddf0 = dd.from_delayed(ddf_delayed, meta=meta)
ddf1 = dd.from_delayed(ddf_delayed, meta=meta)
ddf2 = dd.from_delayed(ddf_delayed, meta=meta)

ddf = dd.concat([ddf0, ddf1, ddf2])
print(ddf.npartitions)
ddf = ddf.groupby('a').sum()
print(ddf.npartitions)
```

**Comment by jsignell** [comment]
Yeah by default aggregation on a groupby will do that. If you want to have more partitions in your output, you can use the `split_out` kwarg: For instance: `ddf = ddf.groupby('a').sum(split_out=3)`

**Comment by jsignell** [comment]
I think this is good to close since it ended up being more of a usage question. But if you can think of a way to make the docs clearer please open a PR!
