### ISSUE TITLE
TypeError('copy() takes no keyword arguments')

### ISSUE THREAD

**Issue by pseudotensor** [dask/dask#7819]
https://github.com/dmlc/xgboost/issues/7045#issuecomment-864260193

Only on 2021.5 not 2021.4.

I cannot make MRE, but an MRE would look like:
```

def fun():
    import pickle

    from dask_cuda import LocalCUDACluster
    from dask.distributed import Client, wait

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            valid_X, valid_y, names_to_use = pickle.load(open("tmp/h2oai/q.pkl", "rb"))
            valid_X, valid_y = to_dask(valid_X, valid_y)
            valid_X = valid_X[names_to_use]
            print(valid_X.npartitions)
            a = valid_X.compute()


def to_dask(X, y, chunksize=1000):
    import dask.dataframe as dd
    X['target'] = y
    X = dd.from_pandas(X, chunksize=chunksize).persist()
    y = X['target']
    X = X.drop('target', axis=1)
    print(type(X))
    print(type(y))
    return X, y

if __name__ == "__main__":
    fun()
```

That is, the error happens when a frame is sliced by a list (names_to_use).  dask turns this into a drop operation on remaining columns, but the  drop_by_shallow_copy's "df" gets a list not a dataframe and .copy() fails to be relevant/correct.

**Comment by pseudotensor** [comment]
![image](https://user-images.githubusercontent.com/2249614/122614330-4d180600-d03b-11eb-951c-08098818eb94.png)


The odd part is that by the point of the valid_X.compute(), the valid_X.columns doesn't have those target and sample names in it.  Somehow dask thinks they are still there or not yet dropped from a prior drop operation.

**Comment by pseudotensor** [comment]
I can't create MRE it seems because it is not deterministic exactly.  I can do an `valid_X[list(valid_X.columns)].compute()` operation early enough and the later one does not fail, etc.

**Comment by pseudotensor** [comment]
Ok, here is a kind of MRE:

```
from h2oaicore.systemutils import save_obj


def fun():
    import pickle

    from dask_cuda import LocalCUDACluster
    from dask.distributed import Client, wait

    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            valid_X, valid_y, names_to_use = pickle.load(open("q.pkl", "rb"))
            valid_X, valid_y = to_dask(valid_X, valid_y)
            kwargs_dask = dict(eval_set=[(valid_X, valid_y)])

            print("before cause")
            cause_problem = True
            if cause_problem:
                kwargs_dask_pkl = kwargs_dask.copy()
                if 'eval_set' in kwargs_dask:
                    kwargs_dask_pkl['eval_set'] = [
                        (kwargs_dask['eval_set'][0][0].compute(), kwargs_dask['eval_set'][0][1].compute())]
                pickle.dumps(kwargs_dask_pkl)

            print("after cause, see effect")
            valid_X = valid_X[names_to_use]
            valid_X[list(valid_X.columns)].compute()
            print(valid_X.npartitions)
            a = valid_X.compute()


def to_dask(X, y, chunksize=1000):
    import dask.dataframe as dd
    target = "________TARGET_________"
    X[target] = y
    X = dd.from_pandas(X, chunksize=chunksize).persist()
    y = X[target]
    X = X.drop(labels=[target], axis=1)
    print(type(X))
    print(type(y))
    return X, y

if __name__ == "__main__":
    fun()
```

If one sets `cause_problem=True` then the later operations (which should be unaffected by the cause block) fail.  If one sets that to False, then there is no failure.

[q.pkl.zip](https://github.com/dask/dask/files/6679417/q.pkl.zip)

The error is slightly different, not a list but a str, but maybe same issue.

**Comment by pseudotensor** [comment]
And I should be clear, this is just one way this happens.  I can try to avoid this block in our production code and other places still hit such problems.  Once xgboost gets hands on the frame, things get even more confusing as far as error messages.

**Comment by jrbourbeau** [comment]
I can't quite run your example as it's using a local pickle file. It's just a guess, but this looks somewhat like other issues we were seeing around turning low-level task fusion off by default for Dask DataFrames. Could you try setting the `optimization.fuse.active` config value to `True` to see if that helps?

```python
import dask
dask.config.set({"optimization.fuse.active": True})
```

**Comment by pseudotensor** [comment]
@jrbourbeau I shared the file already: https://github.com/dask/dask/files/6679417/q.pkl.zip

**Comment by pseudotensor** [comment]
> I can't quite run your example as it's using a local pickle file. It's just a guess, but this looks somewhat like other issues we were seeing around turning low-level task fusion off by default for Dask DataFrames. Could you try setting the `optimization.fuse.active` config value to `True` to see if that helps?
> 
> ```python
> import dask
> dask.config.set({"optimization.fuse.active": True})
> ```

That does seem to avoid the problem.

**Comment by pseudotensor** [comment]
> > I can't quite run your example as it's using a local pickle file. It's just a guess, but this looks somewhat like other issues we were seeing around turning low-level task fusion off by default for Dask DataFrames. Could you try setting the `optimization.fuse.active` config value to `True` to see if that helps?
> > ```python
> > import dask
> > dask.config.set({"optimization.fuse.active": True})
> > ```
> 
> That does seem to avoid the problem.

How would I set that for dask workers for CLI?  Like?

```
dask_worker_env['DASK_DISTRIBUTED__OPTIMIZATION_FUSE_ACTIVE'] = "True"
```
?

**Comment by jrbourbeau** [comment]
> How would I set that for dask workers for CLI?

`DASK_OPTIMIZATION__FUSE__ACTIVE=true` should work. For reference, I recommend [this utility](https://docs.dask.org/en/latest/configuration.html#conversion-utility) in the docs for converting between different config value formats

> Not sure, but no way to set via env, but seems can be set at client time even if using distributed mode.

Yeah, this particular configuration value only needs to be set in the `Client` process 👍

**Comment by pseudotensor** [comment]
> DASK_OPTIMIZATION__FUSE__ACTIVE=true

Sorry, I see the page for "Conversion Utility" but I don't see what one should actually do.  I only see 3 examples of each kind.

**Comment by pseudotensor** [comment]
> > For reference, I recommend this utility in the docs for converting between different config value formats
> 
> Sorry, I see the page for "Conversion Utility" but I don't see what one should actually do. I only see 3 examples of each kind.
> 
> Ah, duh, it's in the webpage itself.

It doesn't work though.  If I do:

```
DASK_OPTIMIZATION__FUSE__ACTIVE='true' dask-scheduler --scheduler-file foo.json
```
and then run:

```
def fun():
    from dask.distributed import Client, wait
    import dask
    import dask.distributed  # populate config with distributed defaults
    from distributed import LocalCluster
    with Client(scheduler_file="foo.json") as client:
        #dask.config.set({"optimization.fuse.active": True})
        #print(dask.config.config)
        #print(dask.config.get("distributed.admin"))
        #print(dask.config.get("distributed"))
        print(dask.config.get("optimization.fuse.active"))

if __name__ == "__main__":
    fun()
```

it returns the original default of "None".

However, I can set it within the client context.

**Comment by jrbourbeau** [comment]
Sorry, I'll adjust my previous comment https://github.com/dask/dask/issues/7819#issuecomment-864305375. Instead of "this particular configuration value only needs to be set in the Client process" I should have said "this particular configuration value only has an effect when set in the Client process". This is because we only ever use the `optimization.fuse.active` config value on the `Client` process, so `DASK_OPTIMIZATION__FUSE__ACTIVE='true' dask-scheduler --scheduler-file foo.json`, which sets that config value for the scheduler process, won't have any effect. Hopefully that helps clear things up

**Comment by martindurant** [comment]
> this looks somewhat like other issues we were seeing around turning low-level task fusion off by default for Dask DataFrames

Can you please link, @jrbourbeau ? Since the config seems to fix the issue, I'd say it is the same, and we can close this one in favour of a previous mention of the same thing.

**Comment by quasiben** [comment]
This came up a few weeks ago here: https://github.com/dask/dask/issues/7777 .  Mads notes the he [has a potential resolution](https://github.com/dask/dask/issues/7777#issuecomment-858602724) but it may take some time

**Comment by jrbourbeau** [comment]
Thanks for linking @quasiben. Closing in favor of https://github.com/dask/dask/issues/7777
