### ISSUE TITLE
Applying blockwise min/max on array with multiple partitions leads to error

### ISSUE THREAD

**Issue by Mulan-94** [dask/dask#7821]
Hi all,

I was trying to get the maximum and minimum values for an array using `dask.array`'s `blockwise` function. However on calling the `compute` function, I end up with an index error. 

This *only* happens when the array has multiple partitions, it does not occur when there is only a single partition within the array. Below is a minimal, reproducible example + the resulting error:

```
import dask.array as da

z = da.random.randint(1,100, (10000), chunks=5000)
z = da.blockwise(np.min, "i", z, "i", dtype=z.dtype)
z.compute()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/base.py", line 568, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/base.py", line 568, in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/array/core.py", line 1077, in finalize
    return concatenate3(results)
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/array/core.py", line 4807, in concatenate3
    chunks = chunks_from_arrays(arrays)
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/array/core.py", line 4576, in chunks_from_arrays
  File "/home/v_envs/chaosEnv/lib/python3.8/site-packages/dask/array/core.py", line 4578, in <listcomp>
    result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
IndexError: tuple index out of range

```

**Environment**:

- Dask version: 2021.6.1
- Python version: 3.8.5
- Operating System: ubuntu 20.04
- Install method (conda, pip, source): pip

Thank you!

**Comment by GenevieveBuckley** [comment]
Hi @Mulan-94 

Your example should be:
```python
import numpy as np
import dask.array as da

z = da.random.randint(1,100, (10000), chunks=5000)
z = da.blockwise(np.min, "", z, "i", dtype=z.dtype)
z.compute()
```

...which computes the answer `1`.

The reason we have `np.min, "", ...`` (instead of `np.min, "i", ...`) is that we know the output of `np.min` will be a scalar. Roughly speaking:

* scalar --> ""
* 1d array --> "i"
* 2d array --> "ij"

**Comment by GenevieveBuckley** [comment]
This particular bit of the [blockwise examples](https://docs.dask.org/en/latest/array-api.html?highlight=blockwise#dask.array.blockwise) might be useful to you:

> Any index, like `i` missing from the output index is interpreted as a contraction (note that this differs from Einstein convention; repeated indices do not imply contraction.) In the case of a contraction the passed function should expect an iterable of blocks on any array that holds that index. To receive arrays concatenated along contracted dimensions instead pass `concatenate=True`.
> 
> Inner product multiplying a by b, two 1-d vectors
>

```python
def sequence_dot(a_blocks, b_blocks):
    result = 0
    for a, b in zip(a_blocks, b_blocks):
        result += a.dot(b)
    return result

z = blockwise(sequence_dot, '', a, 'i', b, 'i', dtype='f8')
z.compute()
250
```

**Comment by Mulan-94** [comment]
@GenevieveBuckley thank you so much for your reply. Apologies for the example, it was an oversight on my part.
> This particular bit of the blockwise examples might be useful to you

Noted, I think this can be closed then. Thanks again.

**Comment by GenevieveBuckley** [comment]
No need to apologize, it's tricky to get your head around this stuff.

Glad we got you unstuck :+1:
