### ISSUE TITLE
Remove skips from docstests

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7823]
We run doctests on a CI environment with many packages installed: 

https://github.com/dask/dask/blob/a87236041ff223363698f65c5b7c153415a41259/.github/workflows/additional.yml#L80:L104

So we probably don't need to skip as many as we do (grep for `# doctest: +SKIP`).

**Comment by zzhengnan** [comment]
I'm interested in taking this on. 

If some doctests turn out to fail, I'll try to fix them; if that turns out to be non-trivial, I'll flag here and we can discuss next steps.

**Comment by zzhengnan** [comment]
As of commit 26986346, there are a total of 407 instances of `# doctest: +SKIP`, distributed as follows. 

My plan is to open multiple PRs so we can contain the scope of each one. I'll also keep track of my progress by updating the last two columns.

Sub-package | Before | After | PR
--- | --- | --- | ---
`dask`* | 132 |  | 
`dask.dataframe` | 99 |  |
`dask.array` | 94 |  |
`dask.bag` | 56 |  |
`dask.diagnostics` | 20 |  |
`dask.bytes` and `dask.bytes` | 6 |  |
**Total** | **407** |  |

*Modules directly under the top-level namespace (e.g., `dask.graph_manipulation`) _outside_ a sub-package

**Comment by zzhengnan** [comment]
As of commit 26986346, there are a total of 407 instances of `# doctest: +SKIP`, distributed as follows. 

My plan is to open multiple PRs so we can contain the scope of each one. I'll also keep track of my progress by updating the last two columns.

Sub-package | Before | After | PR
--- | --- | --- | ---
`dask`* | 132 |  | 
`dask.dataframe` | 99 |  |
`dask.array` | 94 |  |
`dask.bag` | 56 |  |
`dask.diagnostics` | 20 |  |
`dask.bytes` and `dask.bytes` | 6 |  |
**Total** | **407** |  |

*Modules directly under the top-level namespace (e.g., `dask.graph_manipulation`) _outside_ a sub-package

**Comment by zzhengnan** [comment]
PRs are ready for review. As indicated in the table above, a total of 100 instances of `doctest: +SKIP` have been removed.

**Comment by jsignell** [comment]
Thanks for kicking this work off @zzhengnan!

**Comment by zzhengnan** [comment]
The remaining 3 PRs are now ready for review
- #7872 
- #7865 
- #7864

**Comment by jsignell** [comment]
woohoo!! Thanks @zzhengnan!

**Comment by zzhengnan** [comment]
@jsignell Thanks for all the help getting this across the finish line. I learnt a great deal about the layout of the project.
