### ISSUE TITLE
Date arguments in pure delayed generates different keys

### ISSUE THREAD

**Issue by epizut** [dask/dask#7833]
**What happened**:

It seams that python datetime.date arguments in a pure delayed are generating inconsistant dask keys.

**Minimal Complete Verifiable Example**:

```python
import dask
import datetime

@dask.delayed(pure=True):
def test(obj):
    return obj

dt = datetime.date(2007, 1, 1)
assert test(dt).key == test(dt).key
```

**Environment**:

- Dask version: 2021.6.1
- Python version: 3.7
- Operating System: win10
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks @epizut for raising an issue and providing a nice reproducer. https://github.com/dask/dask/pull/7836 should fix this

**Comment by epizut** [comment]
Thank you for your reactivity !

Knowing that this issue also affects pd.Timestamp and date.datetime, I will be happy to provide a copycat PR but I imagine it could be done in a more generic way?

**Comment by jsignell** [comment]
Copying @jrbourbeau's approach for date.datetime and pd.Timestamp seems like a good idea to me.

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/pull/7836 relies on the string representation of a `datetime.date` to fully specify the `datetime.date` instance. If this is the case for `date.datetime` and `pd.Timestamp` then the same approach will work. If not, then we'll need to take another approach. FWIW it looks like [`datetime.datetime` objects are hashable](https://docs.python.org/3/library/datetime.html#common-properties) which we might be able to utilize here
