### ISSUE TITLE
RFC: nullable types in parquet

### ISSUE THREAD

**Issue by martindurant** [dask/dask#7835]
PR https://github.com/dask/fastparquet/pull/623 implements nullable types in fastparquet: any int or bool column will be a pandas extension type that implement a bool mask for NaNs, rather than possibly casting to float or object. The extension types also have a broader set of dtypes (unsigned, 8 and 16 bit) which are usually upcast by pandas.
Loading the data is not faster because of this, but further computations should be, and creating floats out of ints is a longstanding friction point for pandas.

The PR works for fastparquet and the tests can be made to pass - by having assert_frame_equal ignore the dtype (because the dataframes produced by pd.DataFrame({...}) never gets the nullable types) and by sometimes ignoring the index (because indexes can't use these types).  Applying this to the dask parquet tests, you get
```
E           Attribute "dtype" are different
E           [left]:  int64
E           [right]: Int64
```
(see [here](https://github.com/dask/fastparquet/pull/623/checks?check_run_id=2910367207#step:6:12013])

A couple of notes:
- we only need a nullable type if a column is *optional*. In the write functions, all columns are optional by default, and the same is true for spark and arrow.
- if there are statistics, we can infer that nullable isn't needed if the number of nulls across all column chunks to be loaded is zero. 
- the pandas metadata in the global parquet key-value area should capture what the input type of a column was, if the data originated with pandas (arrow/fastparquet). (actually, there's a bug in arrow that gets the pandas and numpy types the wrong way around)

From Dask's point of view, we have a further complication in that some partitions may have nulls for a given column, others not. I imagine this would give dtype mismatch errors, if fastparquet wanted to use the absence of nulls to pick the simpler type.

Any thoughts?

**Comment by martindurant** [comment]
@rjzamora @jsignell @jrbourbeau maybe?

**Comment by martindurant** [comment]
For additional context: 
- fastparquet currently will return different types for the same column in different partitions, depending on whether there are any nulls (and this doesn't seem to be a problem)
- arrow will return nullable types even if there are no nulls, if the input data type was nullable. II would need to fire up spark to see what it does when the original pandas dtype is not known.

**Comment by jsignell** [comment]
Sorry Martin did you close this for lack of comment? It's not clear to me if dask needs to make a change to be compatible with user expectations.

**Comment by martindurant** [comment]
@jsignell , thanks for checking in. I already made up my mind and made the very minor required changes. I think that the worry of producing new-style parquet files that can't be read by other frameworks is considerably less by now, since the parquet spec has had features like this a long time. To be sure: the fastparquet-written files with ns-resolution times are correctly read by arrow and spark.
