### ISSUE TITLE
Shuffle split layer tasks renamed

### ISSUE THREAD

**Issue by fjetter** [dask/dask#7844]
`shuffle-split` (or `split-shuffle`) tasks are special tasks which benefit greatly from data locality and compute extremely fast. It is usually extremely harmful to compute these tasks on different workers than their dependencies. Since the dask.distributed scheduler may make wrong decisions we hard code the task (prefix) name such that the scheduler can make the proper decision more reliably.
In particular we have two places in the dask.distributed code base where this is hard coded

Default task duration
https://github.com/dask/distributed/blob/94254184bb4d81eca914baf374ce0763488d327e/distributed/distributed.yaml#L29-L31

Blacklist for work stealing
https://github.com/dask/distributed/blob/94254184bb4d81eca914baf374ce0763488d327e/distributed/stealing.py#L456

The recent efforts of converting most dask.dataframe graphs to HLGs has caused a regression since the shuffles layers use slightly different naming conventions

https://github.com/dask/dask/blob/364d799e177ad93020d60b4504fb5ab34ab1588f/dask/layers.py#L740-L741

For reference, reversing `self.name` and the split prefix yields smth like `shuffle-0-cbf47d0a7fe114a2badb9f3e7ad7d820-split` and would break our key split / prefix mechansim entirely so a more sophisticated str manipulation is required to revert to the old behaviour.

There is currently one PR open to address the work stealing problem and add a test to protect from regression https://github.com/dask/distributed/pull/4964

A similar PR is necessary for the default task durations. Alternatively the dask behaviour can be adapted. Either way, the test for the regression should be carried over.

- [x] Fix work stealing https://github.com/dask/distributed/pull/4964
- [x] Fix default task duration https://github.com/dask/distributed/pull/4991

**Comment by mrocklin** [comment]
FYI @rjzamora @madsbk

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/4964 and https://github.com/dask/distributed/pull/4991
