### ISSUE TITLE
Dask compute error: ParserError: Too many columns specified: 

### ISSUE THREAD

**Issue by lime-n** [dask/dask#7862]
I am running the following code that reads a 680GB .csv file into a Dask DataFrame, while selecting a few columns, and converting specific column types to integer:
```
import dask.dataframe as dd
import dask

file_path = "/Volumes/Seagate/Work/Tickets/Third ticket/Extinction/species_all.csv"
cols = ['year', 'species', 'occurrenceStatus', 'individualCount', 'decimalLongitude', 'decimalLatitde']
dataset = dd.read_csv(file_path, names=cols,usecols=cols)

dataset['year']=dd.to_numeric(dataset['year'])
dataset['individualCount']=dd.to_numeric(dataset['individualCount'])
dataset['decimalLongitude']=dd.to_numeric(dataset['decimalLongitude'])
dataset['decimalLatitde']=dd.to_numeric(dataset['decimalLatitde'])

subset_data = dataset[dataset['year']>2000]

```

Now when I run the `.compute` function either on `dd` or `Dask` I get differing number of columns specified when run on the subset data compared to the dataset:
```
dts = dask.compute(subset_data)
```
>ParserError: Too many columns specified: expected 6 and found 4

```
dts = dask.compute(dataset)

```
>ParserError: Too many columns specified: expected 6 and found 3

Although sometimes I Get this error when adding `sep=","`:
```
ValueError: Unable to parse string "3162074496	4fa7b334-ce0d-4e88-aaae-2e0c138d049e	URN:catalog:CLO:EBIRD:OBS892558907	Animalia	Chordata	Aves	Columbiformes	Columbidae	Zenaida	Zenaida macroura		SPECIES	Zenaida macroura (Linnaeus" at position 0
```

However, when I change it to tab-delimited `sep="\t"`, I get this error:
```
ValueError: Unable to parse string "Animalia" at position 0  /Users/X/Conda/anaconda3/lib/python3.8/site-packages/dask/core.py:121: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.   return func(*(_execute_task(a, cache) for a in args))
```
I can remove the user warning with ```dtype='str'```, and only convert `year` to numeric then I get this error:
> ParserError: Error tokenizing data. C error: EOF inside string starting at row 130532

- Dask version: dask 2021.4.0
- Python version: Python 3.9.5
- Operating System: macOS Big Sur version 11.4
- Install method (conda, pip, source): conda
Data is downloaded from gbif.org - the entire dataset (simple_csv.zip)

**Comment by ncclementi** [comment]
Hi @lime-n, it’d be great if you could provide a minimal example as described [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). Please let us know if you’re able to manage this, otherwise it's a bit difficult to see what's happening.  

Looking up a bit about the error 
> ParserError: Error tokenizing data. C error: EOF inside string starting at row 130532

It seems some other people reported that you get this when there is some problem in your data. Maybe this can help a bit. https://stackoverflow.com/questions/60345503/pandas-parsererror-error-tokenizing-data-c-error-eof-inside-string

**Comment by jsignell** [comment]
I'm going to close this, but please reopen @lime-n if you are able to provide more information.
