### ISSUE TITLE
Switch default pyarrow-based read_parquet engine to "pyarrow-dataset" 

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/dask#7871]
When the support for `pyarrow.dataset` was added to `read_parquet` (`ArrowDatasetEngine`, #6174, #6534), we didn't yet turn it on by default (when using pyarrow as engine). 

In the upcoming pyarrow 5.0.0, I am adding more deprecation warnings to the use of several `pyarrow.parquet.ParquetDataset` functionalities (eg the `pieces` and `partitions` attributes). So I think it would be good if dask could start to actually use "pyarrow-dataset" as the default (meaning that `engine="pyarrow"` would map to "pyarrow-dataset" instead of "pyarrow-legacy").  cc @rjzamora 

Are there still known issues with "pyarrow-dataset" compared to "pyarrow-legacy"?

**Comment by rjzamora** [comment]
Thanks for making a formal issue about this @jorisvandenbossche !

>Are there still known issues with "pyarrow-dataset" compared to "pyarrow-legacy"?

I will need to re-run some benchmarks.  There may be some cases where the legacy engine is still a bit faster, but I wouldn't want to delay the move to `ArrowDatasetEngine` unless the difference is significant.  I do happen to  know that Dask-cuDF is still on the legacy engine, but I can submit a PR to change that in the next week or so.
