### ISSUE TITLE
parquet nano-second type

### ISSUE THREAD

**Issue by martindurant** [dask/dask#7877]
This is just for information, @rjzamora @jorisvandenbossche 

Parquet [supports](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#deprecated-time-convertedtype) ms, us and ns-resolution timestamps. The latter is new (well, new*er*), and both pyarrow and fastparquet currently truncate timestamps to us, even though pandas usually stores as ns.

In [this PR](https://github.com/dask/fastparquet/pull/628) I will shortly implement ns resolution, as a "logical type". pyarrow already writes logical type information, so it should be easy enough for it to write ns times too, when the pandas input happens to have ns. @jorisvandenbossche , do you anticipate that arrow should be able to read this OK? https://arrow.apache.org/docs/cpp/parquet.html#logical-types suggests yes.

**Comment by martindurant** [comment]
(after the fastparquet PR goes in, some tests in this repo will need to change, since the truncation to us is accounted for in a few places)

**Comment by martindurant** [comment]
One thought that occurs here, is that data written with the new type (ns) will not be readable by older versions, the numbers will be represented as int.

**Comment by jorisvandenbossche** [comment]
>  do you anticipate that arrow should be able to read this OK? https://arrow.apache.org/docs/cpp/parquet.html#logical-types suggests yes.

Yes, arrow has full support for the logical timestamp types and its different resolutions. So I would say that readinf the data you will write with fastparquet in the PR using pyarrow is a good validation of your fastparquet enhancement (and vice versa, reading what pyarrow writes).

To write nanoseconds with pyarrow, you can specify `version="2.0"`:

```python
In [1]: df = pd.DataFrame({'col': pd.date_range("2012-01-01", periods=3)})

In [2]: import pyarrow.parquet as pq

# default will write nanoseconds
In [5]: df.to_parquet("test_nanoseconds.parquet")

In [6]: pq.read_metadata("test_nanoseconds.parquet").schema
Out[6]: 
<pyarrow._parquet.ParquetSchema object at 0x7f6d7b129680>
required group field_id=-1 schema {
  optional int64 field_id=-1 col (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
}

# set version=2.0 and then will preserve the nanosecond resolution of pandas
In [7]: df.to_parquet("test_nanoseconds.parquet", version="2.0")

In [8]: pq.read_metadata("test_nanoseconds.parquet").schema
Out[8]: 
<pyarrow._parquet.ParquetSchema object at 0x7f6d3715de80>
required group field_id=-1 schema {
  optional int64 field_id=-1 col (Timestamp(isAdjustedToUTC=false, timeUnit=nanoseconds, is_from_converted_type=false, force_set_converted_type=false));
}
```

> One thought that occurs here, is that data written with the new type (ns) will not be readable by older versions, the numbers will be represented as int.

Yes, I think that is the reason that it was (originally) not yet used as the default in pyarrow. We are having some discussion to switch to use `version="2.0"` by default, though, see https://issues.apache.org/jira/browse/ARROW-12203

**Comment by martindurant** [comment]
>  you can specify version="2.0"

I had no idea how to trigger this! :)

**Comment by jorisvandenbossche** [comment]
See https://arrow.apache.org/docs/python/parquet.html#storing-timestamps for some basic docs on the topic.

**Comment by martindurant** [comment]
I suspect we can all move on at this point. Parquet, as a standard bearer of data representation and description could have done better here, I think. A schema element like the one following is pretty ugly I would say
```
<class 'fastparquet.parquet_thrift.parquet.ttypes.SchemaElement'>
converted_type: 10
field_id: None
logicalType: <class 'fastparquet.parquet_thrift.parquet.ttypes.LogicalType'>
  BSON: None
  DATE: None
  DECIMAL: None
  ENUM: None
  INTEGER: None
  JSON: None
  LIST: None
  MAP: None
  STRING: None
  TIME: None
  TIMESTAMP: <class 'fastparquet.parquet_thrift.parquet.ttypes.TimestampType'>
    isAdjustedToUTC: False
    unit: <class 'fastparquet.parquet_thrift.parquet.ttypes.TimeUnit'>
      MICROS: <class 'fastparquet.parquet_thrift.parquet.ttypes.MicroSeconds'>

      MILLIS: None
      NANOS: None


  UNKNOWN: None
  UUID: None

name: s
num_children: None
precision: None
repetition_type: 1
scale: None
type: 2
type_length: None
```

Note that I am *not* interested to implement bloom filters in parquet any time soon!
