### ISSUE TITLE
Visualize profiling results inside notebook without creating new tab

### ISSUE THREAD

**Issue by zzhengnan** [dask/dask#7883]
Is it possible to visualize profiling results _inside_ a notebook? The current behavior is for the results to show up in a new tab.

```python
from dask.diagnostics import Profiler, visualize

with Profiler() as prof:
    # Code to profile
    pass

visualize(prof)
```

dask version: 2.20.0
bokeh version: 2.1.1

Link to relevant function https://github.com/dask/dask/blob/2.20.0/dask/diagnostics/profile_visualize.py#L149

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @zzhengnan. See [Bokeh's guide on using `bokeh` in Jupyter](https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html). Locally, if I'm using JupyterLab and have the `jupyter_bokeh` JupyterLab extension installed, then `visualize(prof)` is rendered directly in the notebook

<img width="1552" alt="Screen Shot 2021-07-08 at 4 51 13 PM" src="https://user-images.githubusercontent.com/11656932/124995352-db652380-e00c-11eb-8cdc-1ba893408537.png">

**Comment by zzhengnan** [comment]
Thanks for the link, James! Confirmed that `bokeh.io.output_notebook` allows me to render the profiling results inline in a classic (i.e., non JupyterLab) notebook.

```python
import dask.array as da
from dask.diagnostics import Profiler, visualize
from bokeh.io import output_notebook

output_notebook()

with Profiler() as prof:
    a = da.random.random(1000, 1000)
    a.sum().compute()

visualize(prof)
```
