### ISSUE TITLE
Implement `Array.__iter__`

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7889]
This came up recently in https://github.com/pandas-dev/pandas/issues/38645 and I took a greedy stab at implementing it in: https://github.com/dask/dask/pull/7888

I abandoned that PR because a bunch of tests failed and I feel like it's at least a little surprising to have `list(array)` return a list of real values. It seems too easy to do by mistake. 

For context, currently on main if you call `list(array)` you get an array of getitem calls with the same length as the 0th dimension of the array. It's possible that is already the best solution. In which case we can probably close this.

**Comment by jakirkham** [comment]
What happens if the array has an unknown shape? As an example would consider how `a1` below behaves

```python
import dask.array as da


a0 = da.arange(10, chunks=2)

a1 = a0[a0 % 2 == 0]
```

**Comment by jsignell** [comment]
On main you get 

```python-traceback
ValueError: Arrays chunk sizes are unknown: (nan,)

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

```

**Comment by GenevieveBuckley** [comment]
> For context, currently on main if you call `list(array)` you get an array of getitem calls with the same length as the 0th dimension of the array. It's possible that is already the best solution. In which case we can probably close this.

Isn't it the best solution? I read through the linked threads, but I don't see why hiding a dask compute call inside this would be preferred. It seems very non-intuitive for every other circumstance.

**Comment by davidhassell** [comment]
Hello, I've been following this with interest, and also agree that the "array of getitem calls with the same length as the 0th" is what I would expect to occur (i.e. _not_ returning computed numpy arrays).

Thanks,
David

**Comment by jsignell** [comment]
I opened a PR to implement a lazy version like that.
