### ISSUE TITLE
map_overlap does not always trim properly when drop_axis is not None

### ISSUE THREAD

**Issue by grlee77** [dask/dask#7893]
**What happened**:

If either the `depth` or `boundary` argument to `map_overlap` is not the same for all axes and `trim=True`, then the code that trims the output does not take `drop_axis` into account, leading to incorrect trimming.

**What you expected to happen**:

When axes are dropped, the corresponding entries should also be dropped from `depth` and `boundary` so that trim works as expected.

**Minimal Complete Verifiable Example**:

```Python
import dask.array as da
x = da.ones((5, 10), dtype=float)

y = da.map_overlap(
    lambda x: x.mean(0), x, depth=(0, 2), drop_axis=(0,), chunks=(0,), dtype=float
).compute()
assert y.shape == (x.shape[1],)
```
The assertion will fail because depth=0 along the dropped axis, but the trimming code does not reduce the depth internally from (0, 2) to just (2,) to take into account the dropped axis. Thus 0 elements get trimmed from either end instead of 2!

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

@jakirkham: this is the issue I mentioned to you this afternoon. I have a solution and will make a PR with it now

**Environment**:

- Dask version: 2012.7.0
- Python version: 3.8.10
- Operating System: linux
- Install method (conda, pip, source):  conda-forge

**Comment by jakirkham** [comment]
cc @GenevieveBuckley

**Comment by jakirkham** [comment]
Fix is being worked on in PR ( https://github.com/dask/dask/pull/7894 )
