### ISSUE TITLE
Length mismatch error from dd.read_csv on data from dd.to_csv via verify_meta=False

### ISSUE THREAD

**Issue by dckc** [dask/dask#7906]
**What happened**:

I used `dd.from_delayed` to compile my data and wrote it with `to_csv` and then got an error from `from_csv`.

I suppose I aimed the gun at my own foot with `verify_meta=False`, but still, this was pretty surprising, especially given that `df.compute()` produces something that prints just fine.

```
$ python bug_lm.py 
   col0  col1  col2  col3  col4  col5
0     1     1     1     1     1   NaN
1     2     2     2     2     2   NaN
2     3     3     3     3     3   NaN
0     1     1     1     1     1   1.0
1     2     2     2     2     2   2.0
2     3     3     3     3     3   3.0
Traceback (most recent call last):
  File "bug_lm.py", line 18, in <module>
    print(dd.read_csv('out-*.csv').compute())
...
ValueError: Length mismatch: Expected axis has 7 elements, new values have 6 elements
```

**What you expected to happen**:

`print(dd.read_csv('out-*.csv').compute())` would print the same way as `print(df.compute())`

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask
import dask.dataframe as dd


def build(n):
    return pd.DataFrame({f'col{i}': [1, 2, 3]
                         for i in range(n)})

df = dd.from_delayed(
    [dask.delayed(build)(n)
     for n in [5, 6]], verify_meta=False)

print(df.compute())

df.to_csv('out-*.csv')

print(dd.read_csv('out-*.csv').compute())
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.06.2
- Python version: 3.8
- Operating System: linux (debian Stretch, supplemented with nix)
- Install method (conda, pip, source): from nix `2z911s62b571d9yvzfhzbxbccgxclbah-python3.8-dask-2021.06.2`

**Comment by dckc** [comment]
I guess I might as well share my work-around:

```py
def patch_cols(dpath,
               oops=',time,type,slogfile,line\n',
               missing=['blockHeight', 'blockTime']):
    for p in dpath.glob('*.csv'):
        if p.name.endswith('-bak.csv'):
            continue
        hd = p.open().readline()
        if hd == oops:
            bak = p.parent / f'{p.stem}-bak.csv'
            df = pd.read_csv(p, index_col=0)
            p.rename(bak)
            for col in missing:
                df[col] = np.nan
            df.to_csv(p)
```

**Comment by jsignell** [comment]
If you look at the contents of `out-0.csv` and `out-1.csv` you'll see that they have different columns. There is an assumption in dask that all files passed to `read_csv` will have exactly the same columns and order. If you think there is a spot in the docs where that could be made more clear, please feel free to open a pull request.

**Comment by dckc** [comment]
Yes, I know they have different columns. The question is: why is `print(df.compute())` happy with that but `read_csv` is not?

**Comment by jsignell** [comment]
Ah sorry I should have made that clear .`df.compute` is happy because it already has the column information for each partition and you have explicitly told dask.delayed that you want it to ignore `meta` so it just does a merge of the partitions. `read_csv` only tries to read the column data from the first file so since the second file has different columns, it just fails.

**Comment by dckc** [comment]
I guess a `verify_meta=False` option for `read_csv` would be handy.

**Comment by jsignell** [comment]
You are right. I think that was the intention of the `enforce` kwarg. But it does not seem to be acting how I'd expect. I am taking a look now.
