### ISSUE TITLE
Enable dictionary format on `dask.dataframe.DataFrame.to_bag` output

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#7920]
The current `dask.dataframe.DataFrame.to_bag` behavior is as follow: 

```python 
import pandas as pd
import dask.dataframe as dd
import dask.bag as db

my_dict = {
    'Name' : ['John', 'Lara', 'James', 'Pablo'],
    'Age' : [23, 21, 22, 21],
    'Fruit' : ['orange', 'apple', 'apricot', 'cherry'],
}

df = pd.DataFrame(my_dict)
ddf = dd.from_pandas(df, npartitions=3)

ddf_bag = ddf.to_bag()
ddf_bag.compute()
```
```
[('John', 23, 'orange'),
 ('Lara', 21, 'apple'),
 ('James', 22, 'apricot'),
 ('Pablo', 21, 'cherry')]
```

This loses the information of the column names, I would like to see something like this as an output
```
[{'name': 'John', 'Age': 23, 'Fruit':'orange'},
 {'name':'Lara', 'Age': 21, 'Fruit':'apple'},
 {'name':'James', 'Age': 22, 'Fruit':'apricot'},
 {'name':'Pablo', 'Age':21, 'Fruit':'cherry'}]
```

**Comment by mrocklin** [comment]
In hindsight dicts probably would have been a better default choice.  The easy thing to do today would be to add a `format=` keyword that defaulted to tuples but also supported a dict option.

For reference, the current implementation of this function lives here:

https://github.com/dask/dask/blob/7772ee32352daf800561ac08fc05f4ba1546e88f/dask/dataframe/io/io.py#L502-L532

My hope is that it is somewhat easy to add a paramter and alternate implementation.  Marking as good first issue.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ncclementi! I agree support for `dict` formatting would make `bag` <--> `DataFrame` conversions smoother. +1 for Matt's `format=` suggestion

**Comment by rajagurunath** [comment]
Hi @jrbourbeau @mrocklin @ncclementi 

Thanks for the detailed discussion, based on the comments above, implemented the initial draft version here: https://github.com/rajagurunath/dask/commit/ce6812f69c3f0384e79b2927addbd0025d6bf520

I am kind of new to the dask community, Can someone have a look into the above commit and help me with further suggestions/Best practices, etc.  Very much happy to take this as my good first issue ❤️ 

Thanks in Advance

**Comment by mrocklin** [comment]
Welcome!  I encouraged you to submit a pull request, even if it is not done
yet.  Pull requests make it easier for maintainers to view and to engage in
conversation.

**Comment by rajagurunath** [comment]
Thanks a lot @mrocklin , Agreed, Raised a PR here: https://github.com/dask/dask/pull/7932

**Comment by jsignell** [comment]
Closing this - thanks @rajagurunath
