### ISSUE TITLE
block_info kwarg from map_blocks - error when mixing array input with dataframe/series output

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#7921]
**What happened**:
You cannot use the `block_info` keyword argument with `map_blocks` if the processing function returns anything other than an array. For example, you can't use the `block_info` kwarg with functions returning Series or DataFrame objects (similar to the [examples in this blogpost](https://blog.dask.org/2021/07/02/ragged-output)). 

This might be more of an edge case that isn't supported, rather than a bug. Still I feel obligated to mention it, now I've come across it.

**What you expected to happen**:
I expected things that worked with `map_blocks` to work the same way, regardless of whether the `block_info` keyword argument was passed in or not.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import pandas as pd

def func(x, block_info=None):
    return pd.DataFrame({'x': [1,2,3], "y": [4,5,6]})

arr = da.random.random((100,100), chunks=(50,50))
result = arr.map_blocks(func, drop_axis=1, dtype=float)
```

<details>
<summary>Error message (click to expand details):</summary>

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-dde43f1e2f6d> in <module>
----> 1 result = arr.map_blocks(func, drop_axis=1, dtype=float)

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in map_blocks(self, func, *args, **kwargs)
   2362     @wraps(map_blocks)
   2363     def map_blocks(self, func, *args, **kwargs):
-> 2364         return map_blocks(func, self, *args, **kwargs)
   2365 
   2366     def map_overlap(self, func, depth, boundary=None, trim=True, **kwargs):

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py in map_blocks(func, name, token, dtype, chunks, drop_axis, new_axis, meta, *args, **kwargs)
    766                     ]
    767                     num_chunks[i] = arg.numblocks
--> 768         out_starts = [cached_cumsum(c, initial_zero=True) for c in out.chunks]
    769 
    770         block_info_name = "block-info-" + out.name

~/anaconda3/envs/dask/lib/python3.8/site-packages/dask/dataframe/core.py in __getattr__(self, key)
   3993             return self[key]
   3994         else:
-> 3995             raise AttributeError("'DataFrame' object has no attribute %r" % key)
   3996 
   3997     def __dir__(self):

AttributeError: 'DataFrame' object has no attribute 'chunks'

```

</details>

If you take `block_info=None` out of the function signature, the code above works fine.

**Anything else we need to know?**:
We run into this error because there is no `.chunks` attribute with this kind of non-array output. Here is the relevant line of code:

https://github.com/dask/dask/blob/7772ee32352daf800561ac08fc05f4ba1546e88f/dask/array/core.py#L773

**Environment**:

- Dask version: 2021.06.2'
- Python version: 3.8
- Operating System: Ubuntu 20.04 LTS
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for writing this up @GenevieveBuckley! I didn't know you could create dataframes from array.map_blocks like this. I'll take a look.

**Comment by jsignell** [comment]
Huh. So `block_id` and `block_info` both use the output as well as the input and they both assume that the output is a `dask.Array`. I am wondering if this should be treated as a supported workflow. If not we should raise a warning as soon know that the output is not a `dask.Array`. If we *do* want to support it then we should generalize the `block_id` and `block_info` logic. 

I am leaning towards explicitly forbidding this workflow.

**Comment by douglasdavis** [comment]
This is right up the alley of something I ran into while working on dask-histogram. In that case, I was looking for a way to have the behavior of `map_blocks` while returning a custom (histogram) object. To me the `map_blocks` API is quite rigidly "array in and array out" (with the `dtype`, `chunks`, and `meta` argument docstrings making that pretty explicit). I reached for `dask.delayed`-- just calling `to_delayed` on the input array and passing the delayed blocks to another delayed function that returns a histogram object.

what I do:

```python
@delayed
def _delayed_fill(data, axes)
    h = Histogram(axes)
    h.fill(data)
    return h

def fill(data, template):
    array_parts = data.to_delayed()
    axes = *template.axes
    fills = [_delayed_fill(a, axes) for a in array_parts]
    # could also be 
    # fills = [_delayed_fill(a, axes) for a  in data.blocks]
    final_result = delayed(sum)(fills)
    return final_result

x = dask_array_factory(...)
h = Histogram(...)
h = fill(x, h)
h.compute()
```

Would it make sense to provide an API that allows `map_blocks` like behavior but instead of returning an array, explicitly return a `Delayed` object? My example above would become:

```python
def fill(data, axes):
    h = Histogram(axes).fill(data)

x = dask_array_factory(...)
h = Histogram(...)
axes = *h.axes
h = x.map_blocks_custom(fill, axes)
h.compute()
```

At the end of the day this would be syntactic sugar, as explicitly taking advantage of delayed works fine.

**Comment by jsignell** [comment]
A similar conversation has been happening on #4148. I have yet to see a really compelling reason why using delayed (like you are saying Doug) or iterating over the blocks. is not sufficient. But I am totally open to being shown such a reason :)

**Comment by GenevieveBuckley** [comment]
Yes, iterating over the blocks and using delayed is what I'm using instead.

I'm happy for https://github.com/dask/dask/issues/7921 (this) and https://github.com/dask/dask/issues/4148 to be closed as out of scope. I mostly just wanted to make sure to make a record of what I found (there are discussions elsewhere about why can't we just use `$foo` instead).

I would be less happy if there was a move to forbid mixed output entirely, particularly after [publicizing that you can](https://blog.dask.org/2021/07/02/ragged-output). (Maybe you hadn't realized I was going to highlight that, which is fine - I also hadn't realized you might want to ban it).

**Comment by GenevieveBuckley** [comment]
> A similar conversation has been happening on #4148. I have yet to see a really compelling reason why using delayed (like you are saying Doug) or iterating over the blocks. is not sufficient. But I am totally open to being shown such a reason :)

@jakirkham might have an opinion here. 
(Tagging him in since he mentioned [memory issues](https://github.com/dask/dask-image/pull/97/#issuecomment-518249772) as a potential problem elsewhere. I don't fully understand that concern though, so it might not be relevant here)

**Comment by jsignell** [comment]
Fair enough. I think for now we can raise an error sooner that is very explicit about `block_id` and `block_info` not being supported for this kind of output.
