### ISSUE TITLE
Series GroupBy head and tail 

### ISSUE THREAD

**Issue by mesejo** [dask/dask#7934]
I'd like to be able to use head and tail on group-by Series. Today, I can do this in pandas but not dask.
```python
import pandas as pd
import dask.dataframe as dd

pdf = pd.DataFrame({
    "a": [0,1,0,1,1,0],
    "b": range(6),
    "c": ["a","b","c","d","e","f"]
})
ddf = dd.from_pandas(pdf, 2)

print(pdf.groupby("a").b.head(1))
ddf.groupby("a").b.head(1)
```
**Output**
```
0    0
1    1
Name: b, dtype: int64

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-6339dbe399f3> in <module>
     10 
     11 print(pdf.groupby("a").b.head(1))
---> 12 ddf.groupby("a").b.head(1)

AttributeError: 'SeriesGroupBy' object has no attribute 'head'
```

The same applies to `tail`. The pandas version is:
```python
dask.__version__
'2021.06.0'
```

**Comment by GenevieveBuckley** [comment]
Looks like the `head` and `tail` methods are defined in the `_Frame` class, but the `SeriesGroupBy` class inherits only from `_GroupBy` and so doesn't know anything about them. 

https://github.com/dask/dask/blob/1fab96cb763e7273079083d0093a55aad096549e/dask/dataframe/core.py#L1057-L1121

**Comment by GenevieveBuckley** [comment]
Ah, I see you have a WIP open. Let us know when you'd like someone to look over it.
