### ISSUE TITLE
`assert_eq` takes both `check_dtypes` & `check_dtype`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#7947]
Currently [`assert_eq`]( https://github.com/dask/dask/blob/a87236041ff223363698f65c5b7c153415a41259/dask/dataframe/utils.py#L559 ) takes both `check_dtypes` & `check_dtype`. The latter is forwarded to [`assert_series_equal`]( https://github.com/pandas-dev/pandas/blob/18d46b172e7eafec2c38780686ed2c71de7686f8/pandas/_testing/asserters.py#L857 ). For example see this code:

https://github.com/dask/dask/blob/8f07a99f1c38f589804300bd3e8c3bf8dee7e657/dask/dataframe/tests/test_arithmetics_reduction.py#L1296-L1299

This is kind of confusing. It would be good to consolidate these into a single parameter if possible to make this a bit easier to understand

cc @pentschev

**Comment by rajagurunath** [comment]
Hi @jakirkham & @jsignell 

Have done some initial changes based on the discussion and raised a PR https://github.com/dask/dask/pull/7952, Please review and let me know if any other things need to be added/changed.

Thanks in advance

**Comment by jsignell** [comment]
closed my #7952
