### ISSUE TITLE
Inspect function annotations to enable unpacking of results with dask.imperative's do?

### ISSUE THREAD

**Issue by shoyer** [dask/dask#795]
Unpacking is a really nice feature for writing readable Python code. Unfortunately, it can't work with dask imperative, because we don't have any way of determining the number of elements to iterate over.

But if we use function annotations for type hints, we could make something like the following work on Python 3:
```
def f(x: int) -> (int, int):
    return (x, x ** 2)

x, y = do(f)(123)
```

Currently this results in `TypeError: Value objects are not iterable`.

**Comment by jcrist** [comment]
This is doable, and may be one of the better ideas I've heard for getting around this problem. Another thought I've had was adding this information to the `do` decorator.

```python
@do(nout=2)
def foo(a, b):
    return a, b

x, y = foo(1, 2)
```

The only issue with this is that it's not quite as succinct to use inline `x, y = do(foo, nout=2)`. It is simple though. Not sure what's best here.
