### ISSUE TITLE
`pyarrow=5.0.0` compatiblity 

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#7961]
We're seeing several test failures in CI due to deprecations in the `pyarrow=5.0.0` release (e.g. see [this CI build](https://github.com/dask/dask/pull/7958/checks?check_run_id=3196777444)). https://github.com/dask/dask/pull/7960 proposes we temporarily pin `pyarrow<5` to unblock CI until we can properly handle the deprecations

cc @rjzamora @jorisvandenbossche

**Comment by rjzamora** [comment]
Well we can't say @jorisvandenbossche didn't warn us :)

I think the failures will be resolved if we switch the default to `ArrowDatasetEngine` for newer pyarrow versions (and stop allowing `ArrowLegacyEngine`).  Note that [cudf#8871](https://github.com/rapidsai/cudf/pull/8871) will finally migrate the backend engine for dask-cudf.

**Comment by jakirkham** [comment]
cc @galipremsagar @quasiben (for awareness)

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/dask/dask/pull/7967 ) has a proposed Dask fix
