### ISSUE TITLE
Adding tooltips to graphviz representation

### ISSUE THREAD

**Issue by freyam** [dask/dask#7970]
While working on https://github.com/dask/dask/issues/7919, I was looking for ways to represent the `layer_type` attribute in the graphviz representation. I stumbled upon the `tooltip` - Tooltip (mouse hover text) attached to the node, edge, cluster, or graph.

This opens up many doors to add more information :rocket: 

## Demo
(image shows the `layer_type` as the tooltip)
![image](https://user-images.githubusercontent.com/62539811/127735097-aa50b328-697e-433f-b376-159c41846556.png)

So, on hover, we can display any kind of information we want per Layer. **We can use this discussion thread to discuss what information would benefit users when they see a Task Graph.**

## Idea

We can show the attributes stored in `collecton_annotations` in the tooltip.
- This could be `shape, dtype, chunksize, type, chunk_type` (`layer_type` too) for Dask Arrays.
- This could be `npartitions, columns, type, dataframe_type, series_dtypes` (`layer_type` too) for Dask DataFrames.
- Anything else.

/cc @GenevieveBuckley @martindurant

**Comment by freyam** [comment]
I have opened a Draft PR where I will be working along with this discussion.
#7973

**Comment by freyam** [comment]
**NOTE**
This would **only** work for SVG outputs.
PNGs and PDFs are not supported.

**Comment by GenevieveBuckley** [comment]
So if we save out an `.svg` file, it retains the hover tooltip information?

If I remember correctly, the high level graph visualizations are saved by default as `.pdf` (and the low level graph visualizations are saved as `.png`, but we're not changing anything about the low level graphviz stuff). Perhaps we should change the high level graph default to `.svg`? It's worthwhile checking to see if most operating systems will be able to display svg files if double-clicked, without having to install other software.

**Comment by freyam** [comment]
> So if we save out an `.svg` file, it retains the hover tooltip information?

Yes, true. The tooltips are stored in the .SVG image. If you open the SVG in a browser later, it would still possess the tooltips.

**Comment by martindurant** [comment]
>  If you open the SVG in a browser later, it would still possess the tooltips.

I would not be certain of this across OSs

**Comment by GenevieveBuckley** [comment]
> > If you open the SVG in a browser later, it would still possess the tooltips.
> 
> I would not be certain of this across OSs

I have a linux machine and a mac we can use for testing if need be. I'm sure we can find someone with a Windows machine if need be, too.

**Comment by GenevieveBuckley** [comment]
My personal preference would be `.svg` if it's easy to open on all operating systems. If it isn't easy, then I'd prefer `.png` to match the default format used to save the low level graph visualizations. It's also worth double checking that default filenames used to save the high & low level graphs are not the same, and adequately describe which is which.
