### ISSUE TITLE
gpuCI follow-up

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#7975]
In https://github.com/dask/dask/pull/7966 and https://github.com/dask/distributed/pull/5147 we added support for gpu-enabled CI builds 🎉 This issue is to track some follow-up work we may to do

For `dask`:

- [x] We may want to include `dask-cudf` as some tests are currently being skipped with `could not import 'dask_cudf': No module named 'dask_cudf'`
- [ ] In the `conda list` step, I see `dask` is installed with `pip` (from the `python setup.py install` step in `build.sh`), but I also see `dask-core` installed from `conda-forge`. It'd be good to confirm that the `dask` package which is actually used in tests corresponds to the PR being built (cc @jakirkham)
- [ ] Again from the `conda list` step, our environment has the latest released version of `distributed` installed. In general, the dev version of `dask` depends on the dev version of `distributed`. I'm not sure what the best way is to ensure we always have the latest dev version of `distributed` installed. Perhaps add a `pip install git+https://github.com/dask/distributed` line to `build.sh`? 

For `distributed`:

- [ ] In the `conda list` step, our environment has the latest released version of `dask` installed. In general, the dev version of `distributed` depends on the dev version of `dask`. I'm not sure what the best way is to ensure we always have the latest dev version of `dask` installed. Perhaps add a `pip install git+https://github.com/dask/dask` line to `build.sh`?

xref https://github.com/rapidsai/dask-build-environment/pull/1 where some of these points are being addressed

cc @charlesbluca @quasiben @raydouglass

**Comment by jrbourbeau** [comment]
We're seeing some gpuCI test failures (e.g. [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/17/CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=21.08/console) for https://github.com/dask/distributed/pull/5151)

**Comment by quasiben** [comment]
@pentschev it looks like the API in RMM has changed ?

> 11:50:01 >                   rmm_usage = c.run_on_scheduler(rmm.get_info)
11:50:01 E                   AttributeError: module 'rmm' has no attribute 'get_info'

Are you aware of this ?

**Comment by quasiben** [comment]
Apparently this was removed some time [ago last summer](https://github.com/rapidsai/rmm/issues/390) and was updated [in this PR](https://github.com/rapidsai/rmm/pull/626/) .  @jrbourbeau please merge that PR when you feel it's ready and we'll fix that test

**Comment by pentschev** [comment]
> Apparently this was removed some time [ago last summer](https://github.com/rapidsai/rmm/issues/390) and was updated [in this PR](https://github.com/rapidsai/rmm/pull/626/) . @jrbourbeau please merge that PR when you feel it's ready and we'll fix that test

Yes, it's been quite a while. I'll work on a fix and submit it soon.

**Comment by jrbourbeau** [comment]
The gpu CI build is already helping : )

**Comment by pentschev** [comment]
I opened a PR with a fix in https://github.com/dask/distributed/pull/5158 .

**Comment by quasiben** [comment]
@jrbourbeau we addressed the `dask-cudf` question [here](https://github.com/rapidsai/dask-build-environment/pull/1/files#r681128007) -- no we do not need it right now

**Comment by charlesbluca** [comment]
Sorry for the poor maintainer experience here @GenevieveBuckley 🙁 I definitely think some additional instructions/context in the bot message would go a long way in empowering maintainers to run gpuCI on more PRs (I've caught a handful where the message pops up and is ignored before merging). IIRC, there were some blockers internally that prevented us from changing this message from its current value (at least on a org/repo-level), but I can double check to see if this is still the case.

In either case, I do think that improving documentation here around gpuCI could ease some of the pains (though it's not the ideal solution); some ideas that pop up are:

- adding a docs page / blurb in CONTRIBUTING.md explaining GPU CI for each repo that implements it
- reworking the existing GPU CI page in Dask's docs to improve visibility/searchability to maintainers
- making it more apparent who has the rights to enable gpuCI (xref https://github.com/dask/community/issues/184)

Would be interested in your thoughts on some of these suggestions, and if you ran into any pain points in finding the docs on the main docs page once you knew they existed.

**Comment by GenevieveBuckley** [comment]
To summarize: Infrequent maintainers forget processes, and we could have a more efficient way to remind people of what to do in the moment.

> I definitely think some additional instructions/context in the bot message would go a long way in empowering maintainers to run gpuCI on more PRs

Agree, I think improving the bot's message would be the most effective change we could make.

> 1. adding a docs page / blurb in CONTRIBUTING.md explaining GPU CI for each repo that implements it
> 2. reworking the existing GPU CI page in Dask's docs to improve visibility/searchability to maintainers
> 3. making it more apparent who has the rights to enable gpuCI (xref https://github.com/dask/community/issues/184)
>
> Would be interested in your thoughts on some of these suggestions, and if you ran into any pain points in finding the docs on the main docs page once you knew they existed.

Thoughts:
1. This might be nice to add for new contributors, but I'm not too worried either way. I'll open an issue. Regardless, if we'd had that, it probably wouldn't have helped me here. If I can forget there is [GPU CI info in the dask contributer guide](https://docs.dask.org/en/stable/develop.html?highlight=gpu%20ci#gpu-ci) will also forget for dask-image. 
2. I have no complaints about the [dask GPU CI docs](https://docs.dask.org/en/stable/develop.html?highlight=gpu%20ci#gpu-ci). It has all the info I need, I just... will forget it exists or where to find it. (At least if I do remember next time, it'll go: see GPU CI bot message --> open https://docs.dask.org --> type "GPU CI" in search bar --> return to original PR with the right message to respond to the bot. Still not great, but slightly fewer steps.)
3. Seems like a good idea. It seems like people agree in the issue that this info should get added to the docs.

**Comment by charlesbluca** [comment]
@GenevieveBuckley update - chatted with RAPIDS ops and turns out we are able to change the bot message 🙂 now the message should read:

```
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all PRs from the same author to run.
```

Unfortunately, this message is set globally across all gpuCI projects, so there wasn't an opportunity here to include a link to Dask's gpuCI documentation, but I think this should hopefully make it a little clearer to maintainers on how to proceed when this message pops up.

In the meantime, I can look into blockers on dask/community#184 to make it clearer who the admins are for each Dask repo.

**Comment by GenevieveBuckley** [comment]
Yes, I'd be happy with that! Thank you for being willing to update it.

**Comment by jakirkham** [comment]
FWIW this has since been done and can be seen in recent comments ( like this one https://github.com/dask/dask/pull/9378#issuecomment-1213298607 )

**Comment by GenevieveBuckley** [comment]
Looks great, thanks all!
