### ISSUE TITLE
Allow errors in async scheduler

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#799]
Ryan (@groutr) had an interesting question about using the dask scheduler to build as many conda packages as possible, even if some of the packages fail.  This would require a mode in the async scheduler that allows for failures, and just continues on to complete the computations that it can.

```python
def inc(x):
    return x + 1
def throws(x):
    raise Exception()

>>> dsk = {'x': (inc, 1), 'y': (inc, 'x'), 'a': (throws, 1), 'b': (inc, 'a')}
>>> y, b = dask.multiprocessing.get(dsk, ['y', 'b'], permit_exceptions=(Exception,))

>>> y
3
>>> b
Exception()  # or maybe something else
```

@jcrist do you have any interest in taking this on?  I can handle it if not.

**Comment by mrocklin** [comment]
Interestingly the scheduler in `distributed` can handle this now (more or less).

**Comment by cowlicks** [comment]
Why not just wrap the possibly failing task with something like:
```python
def ignore_exception(func, args, kwargs, exception):
    try:
        return func(*args, **kwargs)
    except exception:
        pass
```

**Comment by mrocklin** [comment]
We would also want to avoid all downstream tasks

**Comment by jcrist** [comment]
What would the output of a scheduler in this mode be? Some object with the original dask updated with the state of the cache (so completed results are subbed in for the task)? I'm not sure what a good api would be for this. I'm also skeptical of its uses.

**Comment by mrocklin** [comment]
This can be done by the distributed scheduler, which can operate decently well single-machine.  Closing.
