### ISSUE TITLE
Find alternative to NumPy structured arrays

### ISSUE THREAD

**Issue by pentschev** [dask/dask#7997]
Unlike NumPy, some array libraries do not support structured arrays (e.g., CuPy). Dask seems to have very little dependency on structured arrays, with the two cases I could find being [`da.unique`](https://github.com/dask/dask/blob/8d6f2da210900195cca6b531cdf689460763db51/dask/array/routines.py#L1578-L1586) and [`(nan|)arg(min|max)`](https://github.com/dask/dask/blob/8d6f2da210900195cca6b531cdf689460763db51/dask/array/reductions.py#L960-L962).

My first idea to resolve the cases above was to check whether `_meta` supports structured arrays or not, and in the negative case use a `dict` to store as a replacement. The first difficulty is found in `da.unique` that uses `blockwise` to compute chunks, since `blockwise` doesn't seem to be capable of handling multiple output values today. Since results are independent from each other, one alternative would be to implement it as multiple `blockwise` operations, but I imagine that could lead to some performance degradation, although it may not be the case anymore after https://github.com/dask/distributed/pull/4967. My most immediate problem only requires the values from `np.unique`, meaning I could begin by writing an implementation that doesn't use structured arrays, `dict` and at the same time only calls `blockwise` once, and extend it over time as there's more demand for data resulting from `return_index`, `return_inverse` and `return_counts`.

For the `(nan|)arg(min|max)` case I thought using a `dict` would also be a solution, but there are some challenges there too. For instance, [`_tree_reduce`](https://github.com/dask/dask/blob/8d6f2da210900195cca6b531cdf689460763db51/dask/array/reductions.py#L194-L249) uses [`_concatenate2`](https://github.com/dask/dask/blob/8d6f2da210900195cca6b531cdf689460763db51/dask/array/core.py#L287-L337) which obviously can't concatenate a `dict`. I believe one option would be to write a specialized implementation of `_concatenate2` that would be capable of handling `dict`s, but that's less than ideal since it would be a function with probably a single use in the Dask codebase.

There seems to be some demand for this work, particularly for extending `np.unique` support to GPUs in https://github.com/dask/dask/issues/7482 and regarding its memory footprint in https://github.com/dask/dask/issues/6828 . For `np.unique` there's also been some discussion in https://github.com/dask/dask/issues/2851 to implement it as a reduction, which is certainly valuable but would still require structured arrays, so even that wouldn't resolve any of the issues here.

With all the above said I'm wondering what do people feel about the ideas I've come up to allow computing Dask arrays backed by non-NumPy ones (such as CuPy), are those acceptable? If not, are there any other ideas on how we could tackle this problem?

It's also worth noting that there was a request for CuPy to support structured arrays in https://github.com/cupy/cupy/issues/2031, but given the limited amount of Dask code that currently requires it and the complexity of writing GPU code to handle that I'm certain that the effort on the CuPy side would be significantly higher as it would require adding support for that within the entire codebase. Also, having a way to rely on a different approach than structured arrays (even if we keep both for optimal performance in the NumPy case) is certainly beneficial for other array types implementing `__array_function__` that don't implement structured arrays.

**Comment by pentschev** [comment]
@mrocklin since you were interested on the sgkit work that was mentioned during the monthly meeting, this is something I have to resolve for that, in case you have ideas to tackle the problem here.

**Comment by pentschev** [comment]
I should have done this before, but I'm tagging @dask/array in case people have ideas too. To handle the second case (`(nan|)arg(min|max)`), I've produced https://github.com/dask/dask/pull/8014 as a possible solution. This resolved the issue with CuPy, and although IMO it doesn't pollute the code too much, it stillrequires the `_concatenate2` change mentioned in the description.

**Comment by jcrist** [comment]
With #8014 & #8021 in, I believe this can be closed.
