### ISSUE TITLE
Dask client issue

### ISSUE THREAD

**Issue by chivalry123** [dask/dask#7998]
For Dask on a single, I would need a global Memory limit. Since i am running/testing a lot of dask application. I created a separate process 

    from dask.distributed import Client
    client = Client(memory_limit='12GB')  

And try to connect to it in another process using 

    client = Client('127.0.0.1:38719')

However, this line stagnates there.. Did I do anything wrong?

**Comment by jrbourbeau** [comment]
You should make sure you're using the correct scheduler address when creating new clients with `Client(<scheduler-address>)`. You can get the scheduler address from the initial client using `client.scheduler_info()["address"]`. For example:

```python
In [1]: from dask.distributed import Client
   ...: client = Client(memory_limit='12GB')

In [2]: client.scheduler_info()["address"]
Out[2]: 'tcp://127.0.0.1:51022'

In [3]: client2 = Client('tcp://127.0.0.1:51022')

In [4]: client2
Out[4]: <Client: 'tcp://127.0.0.1:51022' processes=4 threads=8, memory=44.70 GiB>
```

**Comment by chivalry123** [comment]
Problem solved! Thanks so much!

**Comment by jrbourbeau** [comment]
🎉
