### ISSUE TITLE
Dask Dashboard not working

### ISSUE THREAD

**Issue by enthusiastics** [dask/dask#8003]
I used AWS EC2 to run everything, in one Jupiter notebook process, I do:
```
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(scheduler_port=5272, dashboard_address=5273,memory_limit='4GB')
# client = Client(cluster)
```

to start a client specifying a port. Then in another process, I join it with,

`client = Client('tcp://127.0.0.1:5272')
`
To check the dash board, I open with safari

`http://ec2-1-123-12-123.compute-1.amazonaws.com:5273/status
`

I could see the dash board, but when i run some big processing tasks, there is no action in the dashboard. still showing little cpu usage. But I saw, huge cpu usage in `htop` , with my `ddf.compute()` running... Did I miss anything?

**Comment by jrbourbeau** [comment]
What happens if you run a very small computation like

```python
f = client.submit(lambda x: x + 1, 1)
print(f.result())
```

Does the computation complete (i.e. do you see `2` printed)? Do you see anything happen in the dashboard status page?

**Comment by enthusiastics** [comment]
It printed 2 successfully without problem... The client actually runs, but the running detail just does not show up in the dashboard

**Comment by enthusiastics** [comment]
ok... when running this task, there is indeed some blue bar appear out there.... not as fancy as others' dash board...

**Comment by enthusiastics** [comment]
Thanks! I actually retry with a more complex case.... a bit fancier dashboard result indeed shows up. I think the problem is solved now! Thanks so much!

**Comment by jsignell** [comment]
My guess is that what you were seeing was graph construction, or transfer. That work is not super apparent in the normal dashboard tabs.
