### ISSUE TITLE
HDFS CI failing 

### ISSUE THREAD

**Issue by jsignell** [dask/dask#8018]
There is a new failure on hdfs ci

```python-traceback
___________________ ERROR at setup of test_read_text_unicode ___________________

request = <SubRequest 'hdfs' for <Function test_read_text_unicode>>

    @pytest.fixture
    def hdfs(request):
>       _maybe_set_hadoop_classpath()
E       NameError: name '_maybe_set_hadoop_classpath' is not defined

dask/bytes/tests/test_hdfs.py:39: NameError
```
https://github.com/dask/dask/runs/3291151260 for instance

@martindurant

**Comment by martindurant** [comment]
Is this definitely happening in a run that is supposed to execute HDFS tests? 

If the import fail, it looks like all the tests should be skipped, but maybe not.

@jorisvandenbossche , did a recent change in pyarrow remove `pyarrow.[_]hdfs._maybe_set_hadoop_classpath` ? Is there an alternative? I recall we had a problem just calling `HadoopFileSystem()` directly without explicit `_connect()`.

**Comment by jorisvandenbossche** [comment]
I think the tests are not properly skipped. There is

https://github.com/dask/dask/blob/cb1527693d0590b67ba4fd51b1833905f1927f7b/dask/bytes/tests/test_hdfs.py#L53

but it's only applied to a single test that uses pyarrow directly. But all other tests also require pyarrow. 

(which doesn't explain why it only started to fail now of course)

**Comment by jorisvandenbossche** [comment]
And the build seems to use pyarrow 0.15, which has https://github.com/apache/arrow/blob/apache-arrow-0.15.1/python/pyarrow/hdfs.py. So it has both `_maybe_set_hadoop_classpath` and `connect` in a `pyarrow.hdfs` module, but that combination doesn't seem to be available in the try/except import sequence at 

https://github.com/dask/dask/blob/cb1527693d0590b67ba4fd51b1833905f1927f7b/dask/bytes/tests/test_hdfs.py#L25-L32

**Comment by martindurant** [comment]
How about the following:
```
try:
    from pyarrow.hdfs import _maybe_set_hadoop_classpath
    phd = pyarrow.hdfs
except ImportError:
    try:
        from pyarrow._hdfs import _maybe_set_hadoop_classpath
        phd = pyarrow._hdfs
    except ImportError:
        pyarrow = False

try:
    _connect = phd._connect
except AttributeError:
    try:
        _connect = phd.connect
    except AttributeError
        pyarrow = False

basedir = "/tmp/test-dask"


# This mark doesn't check the minimum pyarrow version.
require_pyarrow = pytest.mark.skipif(not pyarrow, reason="pyarrow not installed")


@pytest.fixture
@require_pyarrow
def hdfs(request):
    _maybe_set_hadoop_classpath()
    ...
```

**Comment by jorisvandenbossche** [comment]
Do you know for which version the `pyarrow._hdfs` is actually needed?

**Comment by martindurant** [comment]
No idea! :)

**Comment by jcrist** [comment]
The HDFS tests are now failing further on install (the docker container used to test them has python 3.7 installed, while dask is now 3.8+ only). I could possibly spend some time and fix CI here, but I'm feeling a bit inclined to drop this whole CI build and delete a bunch of stuff. We no longer have any HDFS-specific branching in dask itself, so it's more a test that the hdfs filesystem works. Since HDFS is less commonly used than other filesystems, and is imposing some CI burden on us, I'd rather delete this build than spend time fixing things. cc @jrbourbeau for thoughts.

**Comment by jrbourbeau** [comment]
Thanks for bringing this up @jcrist. Yeah, I agree if we no longer have custom logic around HDFS in `dask` and are instead relying on `fsspec`, then dropping the HDFS build seems like a win to me. cc @martindurant for visibility

**Comment by martindurant** [comment]
agreed

**Comment by jcrist** [comment]
https://github.com/dask/dask/pull/9039
