### ISSUE TITLE
HTML repr for dask.config.config

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#8032]
Perhaps it would be nice if we had a HTML representation for the dask config settings. 

The dask `config` object is currently a plain dictionary. Presumably this would require us to make a new configuration class that inherits from dict, and holds a `_repr_html_` method.

You can make nested HTML tables, that might be a good fit for this type of nested dictionary structure.

```python
import dask
import dask.array as da
import dask.dataframe as dd

dask.config.config
```
```
{'temporary-directory': None,
 'dataframe': {'shuffle-compression': None},
 'array': {'svg': {'size': 120},
  'slicing': {'split-large-chunks': None},
  'chunk-size': '128MiB',
  'rechunk-threshold': 4},
 'optimization': {'fuse': {'active': None,
   'ave-width': 1,
   'max-width': None,
   'max-height': inf,
   'max-depth-new-edges': None,
   'subgraphs': None,
   'rename-keys': True}}}
```

Note: you have to import dask array, dataframe, etc. if you want the configuration values specific to those subpackages to appear in the config. Also note, a *lot* of items are added to the config when you start a distributed dask client, so including examples with that is a good idea too.

**Comment by GenevieveBuckley** [comment]
I'd like to see if there's enthusiasm from the dask community, anyone want to weigh in?

This might be a fun thing for @freyam if he unexpectedly ends up with some extra time. Alternatively we could add a "good first issue" label since this problem is nicely self-contained.

**Comment by freyam** [comment]
Yes, glad to help :rocket:

**Comment by mrocklin** [comment]
I kind of like that this is just a dictionary.

**Comment by mrocklin** [comment]
I'm open to changing the repr, but if we do this then I think we should
have a plan for what our objectives are and I'd love to see a mock-up of a
proposed design.

**Comment by jacobtomlinson** [comment]
From a technical viewpoint I also like that it is just a dictionary.

However, from a user perspective, it can be pretty unpleasant to try and view the config once it gets big. Also `dask.config.config` doesn't show all of the default values.

I would really like to see some kind of config inspector where you can see all of the Dask config, whether default values have been overridden and maybe even where (env var, yaml, code, etc). This would really help with debugging some config situations.

It could also be fun to take this further and have an interactive widget where config could be changed as well as viewed, and it could show examples of how to make that change more permanently like how the [docs util does](https://docs.dask.org/en/latest/configuration.html#conversion-utility).

**Comment by jacobtomlinson** [comment]
In #8044 I suggested that if we don't want to mess with the `dask.config.config` dict we could have some kind of inspector function.

```python
from dask.config import inspect

inspect()  # Returns a `DaskConfig` object which wraps `dask.config.config` and has a useful repr
```

**Comment by GenevieveBuckley** [comment]
As discussed in https://github.com/dask/dask/pull/8044 this was really just an idea for fun and/or filling time at the end of GSOC. We don't really need it, this could be closed.

**Comment by jacobtomlinson** [comment]
Personally I would really appreciate a way to find out where each config value has been set for debugging. It's easy to make changes in YAML files and forget about them, or have some system add an environment variable at runtime that you don't know about. 

But that's maybe not what we are talking about here.

**Comment by mrocklin** [comment]
If there is good motivation for a change then I'm in favor.  Mostly I want
to make sure that we are being guided by some practical need, rather than
just filling time.  Writing software is a tax on everyone (review,
maintenance, etc) so we should only do something if we have a solid
motivation.  It sounds like Jacob has some solid motivations.  If folks are
free and excited about working on this then great, let's design a solution
around those needs.

**Comment by jrbourbeau** [comment]
Just want to +1 both @mrocklin and @jacobtomlinson's points. Let's make sure we have some motivation behind development. I personally would have found what Jacob is proposing useful for debugging the Dask config in the past 👍  Also cc @djhoese who may find this conversation interesting

**Comment by djhoese** [comment]
Just want to point out to @GenevieveBuckley and @jacobtomlinson that the `donfig` library exists which is a class-ified version of the dask.config module (still a dict internally). If I remember right @mrocklin wasn't super excited about adding another dependency to `dask` core so it was more of a side project for my other libraries who need/want similar functionality to `dask.config`.

I personally don't think I would need to use this prettier output, but I don't use `donfig` or `dask.config` for more than one or two options anyway. Also, it is this kind of stuff (prettying up HTML repr) that you don't realize you need until it is there. So I like the idea...if someone else implements it.

That said, if this means that dask will have a class-based config object now, please at least borrow from donfig or tell me what needs to be changed in donfig to keep the two in sync.

**Comment by GenevieveBuckley** [comment]
> Personally I would really appreciate a way to find out where each config value has been set for debugging. It's easy to make changes in YAML files and forget about them, or have some system add an environment variable at runtime that you don't know about.
> 
> But that's maybe not what we are talking about here.

This would be very useful, but you're right - that's not quite the same thing being discussed here. Might be worth following up on that idea separately?

I'll close this issue. We'll get the dask blogpost about GSOC done today, then @freyam can take tomorrow off.
