### ISSUE TITLE
DataFrame.shuffle not in documentation

### ISSUE THREAD

**Issue by martinfleis** [dask/dask#8075]
`DataFrame.shuffle` method seems to be a part of the public API, drawing from the code but it is not listed in the API reference in the documentation. Is that on purpose (is it private?)? It made me unsure to which degree I can rely on it downstream.

https://github.com/dask/dask/blob/4229c16cf0cc7ed5f60f313618680bfd04e381ea/dask/dataframe/core.py#L1255

**Comment by mrocklin** [comment]
I don't think that it's going anywhere.  I would be fine with it being in
public API documentation (do you want to add this?).

Also, as a heads-up, I'm working on a newer algorithm here.  The API will
still be the same (I saw that you're doing this for geopandas) but there
may be new algorithms to learn from in the future that may perform slightly
better at large scale.
