### ISSUE TITLE
Viewing large profile plots stresses the browser

### ISSUE THREAD

**Issue by jcrist** [dask/dask#808]
The current profiler stores data in memory, and constructs a bokeh plot from that. This writes all data + markup to a static html document, which can then be viewed with no dependencies. For small graphs this works great, but larger plots can result in extremely large files (I just saw a 160 MB one), which can slow down (or even crash) the browser viewing it.

The data output from a profile run is unlikely to be too large, but the serialized representation stored for bokeh can get large. It might be nice to persist the data from a profile run in some format, and have a simple server for viewing this data later. This has the added benefit of potentially allowing more interesting visualizations than a "static" bokeh plot can provide.

Possible formats:
- sqlite (almost certainly overkill)
- csv
- json
- something else?

Possible pseudocode for use:

``` python
>>> with Profiler() as prof:
...     res = expr.compute()
>>> view(prof)          # View results from a profiler (no need to save)
>>> prof.save('out.prof')
>>> view('out.prof')    # Load and view results from file
```

Being able to create a static html plot (as done currently) should still work, so the api for the server-backed viewer should be separate. This could be done with a separate function/method, or just a keyword to the current `visualize` function.

**Comment by mrocklin** [comment]
I suggest that the full solution to this problem is to invent other diagnostics that can more easily represent aggregate information.  Closing.
