### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'str' if dask.dataframe use map_partitions for twice

### ISSUE THREAD

**Issue by df19900725** [dask/dask#8085]
**What happened**: dask.DataFrame use map_partitions to add a new column. But the first time it will be successfully transformed, but it will throw `TypeError: '<=' not supported between instances of 'int' and 'str'` for the second time

**What you expected to happen**: it should be get correct new column for the second time

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame([[1, 2, 3], [2, 2, 3]])
print(df)

col_name = 0
df = dd.from_pandas(df, npartitions=1)
df["new_0"] = df.map_partitions(
    lambda x: [val for val in x[col_name]]
)
print(df.head())

df["new_1"] = df.map_partitions(
    lambda x: [val for val in x[col_name]]
)
print(df.head())
```

**Anything else we need to know?**:
The first and the second 'print' will get correct result, however, the last one throws error:

```
TypeError: '<=' not supported between instances of 'int' and 'str'
```

**Environment**:

- Dask version: 2021.3.1
- Python version: 3.7
- Operating System: windows 10
- Install method (conda, pip, source): pip

**Comment by df19900725** [comment]
Sure. I will try to fix this.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/9485
