### ISSUE TITLE
Can you add some meaningfull examples?

### ISSUE THREAD

**Issue by Oxi84** [dask/dask#8095]
I was not able to find a meanigfull example of using dask for multiprocessing. Could you add some.

I installed dask and add delayed code in my code and it does not do anything. And it should run a function in paralel but i just do no see any example on how to do it.

Of course i need to run function with parameters and get the result, like in python multiprocessing module.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue. I recommend looking at https://examples.dask.org which has many example usages of Dask. In particular, if you're using the `delayed` interface check out https://examples.dask.org/delayed.html and/or the section in the documentation that covers the `delayed` https://docs.dask.org/en/latest/delayed.html. 

For multiprocessing specifically, see https://docs.dask.org/en/latest/scheduling.html#local-processes which demonstrates how to select Dask's single-machine multiprocessing scheduler.
