### ISSUE TITLE
Dask running out of memory reading in csv files post 2021.04.0 update

### ISSUE THREAD

**Issue by mattcleigh** [dask/dask#8099]
I have been using dask since the beginning of the year to calculate stats, plot histograms and convert file types for some large datasets (~1000 csv files with identical column names totalling ~180GB).

Using version 2021.3.0, dask has worked exactly as expected.

For example the code below uses very little memory, around 1GB for the whole duration of the program.

```
df = dd.read_csv(my_list_of_csv_files, dtype=np.float32, blocksize='64MB')
mean = df.mean(axis=0).compute() 
```

However, since updating to 2021.04.0 (which I need to do in order to use the multi-dimensional histogram functions) running the exact same code causes the memory usage to steadily increase until it hits 16GB, at which point my job is killed. I have tried all the versions after 2021.04.0 (using: conda install dask=XXXX) and none have worked. Reverting back to 2021.03.0 fixes the problem instantly.
 
I should point out that the memory issue is avoided altogether in all versions if I make the slight modification:
```
df = dd.read_csv(my_list_of_csv_files, dtype=np.float32, blocksize='64MB')
arr = df.to_dask_array()
mean = arr.mean(axis=0).compute() 
```

Unfortunately, there are other steps in my program that similarly cause the memory to snowball until failure and I can not get away with converting all steps to arrays. 

Was there some change to read_csv() or to compute() that happened post 2021.03.0? Why would such a simple script keep failing?

Any help is greatly appreciated.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @mattcleigh. It seems like you're running into https://github.com/dask/dask/issues/7583. A fix for this was included in the latest `dask==2021.08.1` release (xref https://github.com/dask/dask/pull/8040). If you're not using `dask==2021.08.1` yet, could you update and retry your workload?

**Comment by ncclementi** [comment]
@mattcleigh checking in here.  Are you still having this issue or has an update to Dask 2021.08.1 solve this problem for you.

**Comment by jrbourbeau** [comment]
Ah, thanks for following up here @ncclementi! Indeed I think https://github.com/dask/dask/pull/8040 resolves this issue. @mattcleigh let us know if that's not the case and we can re-open
