### ISSUE TITLE
reshape constructs extremely large chunks

### ISSUE THREAD

**Issue by dcherian** [dask/dask#8110]
**What happened**:

`reshape` constructs extremely large chunks. 

Related: https://github.com/dask/dask/issues/5544; upstream xarray issue: https://github.com/pydata/xarray/issues/5754

**What you expected to happen**:

`reshape` should not construct extremely large chunks.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import dask.array

# this array has 80MB chunks
arr = dask.array.random.random((300, 180, 4, 18483), chunks=(-1, -1, 1, 183))
# this array has 8GB chunks
arr.reshape(300, 180, -1)
```
<img width="510" alt="image" src="https://user-images.githubusercontent.com/2448579/131718732-b49aa14d-8a00-492a-8229-ae2295f7bade.png">

It seems like dask needs to split large chunks as was done for slicing by a list of ints in #6514

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.07.2
- Python version: 3.8.10
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by GenevieveBuckley** [comment]
@dcherian would you be able to try out [PR 8124](https://github.com/dask/dask/pull/8124) for me? I've given it a basic test, but it'd be very helpful if you could road test this in a more real-world situation, checking the final `compute` result, etc.

**Comment by GenevieveBuckley** [comment]
... I don't think we have an answer to this specific question about real world applications.

**Comment by jsignell** [comment]
Closing this since #8124 is in.
