### ISSUE TITLE
Incorrect divisions when doing an inner join between 2 1-partition dataframes

### ISSUE THREAD

**Issue by davidhao3300** [dask/dask#8113]
**What happened**:

When doing an inner join between 2 Dask DataFrames that both have 1 partition, the joined Dask Dataframe inherits the divisions from the right DF. This appears to be incorrect behavior when `on` is specified.

This problem was discovered when calling repartition() later on yielded an empty dataframe.

**What you expected to happen**:

The divisions field should be inherited from the left dataframe instead.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd
import pandas as pd


df = pd.DataFrame({'a': ['a','b','c']}, index=[0,1,2])
ddf = dd.from_pandas(df, npartitions=1)

right_df = pd.DataFrame({'a': ['a','b','c'], 'b':[1.0, 2.0, 3.0]}).set_index('a')

print("Divisions before join", ddf.divisions)
ddf = ddf.join(right_df, how='inner', on='a')
print("Divisions after join", ddf.divisions)

print("Without repartition", dask.compute(ddf)[0])
print("With no-op repartition", dask.compute(ddf.repartition(divisions=ddf.divisions))[0])
```

The first & second print statements should print the same thing, and so should the third and fourth.

**Anything else we need to know?**:

Some initial investigation notes:
https://github.com/dask/dask/blob/main/dask/dataframe/multi.py#L391 is definitely the problematic area.
The most trivial fix for my particular case would be to swap the left and right if blocks, but that doesn't seem like the full solution.

Perhaps a better solution would be factoring in the `on` parameter(s) in the if statements

**Environment**:

- Dask version: 2021.8.1 (discovered on 2021.4.1)
- Python version: 3.8.8
- Operating System: Ubuntu Bionic
- Install method (conda, pip, source): pip

**Comment by davidhao3300** [comment]
My current workaround is something like this:
```
ddf = left_ddf.join(...)
if left_ddf.npartitions == 1:
	ddf.divisions = left_ddf.divisions
```

**Comment by jsignell** [comment]
Thank you for the excellent bug report! Are you interested in opening a pull request to resolve this issue? It seems like you have a good sense of what is going on.

**Comment by davidhao3300** [comment]
Thanks! As mentioned above, I know enough to fix my particular case, but am not familiar enough with all the other possibile combinations of parameters to know whether or not I'll break other cases

**Comment by jsignell** [comment]
That's totally fair and that is what tests are for if you want to give it a go :)
