### ISSUE TITLE
df.loc[id] often hangs though executed by worker

### ISSUE THREAD

**Issue by a-agmon** [dask/dask#8118]
Apologies - cannot generate a reproducible code, writing here hoping that I stumbled on a known issue. 
Running on a distributed Dask cluster over AWS EKS. 
The following describes the code that generates the issue.

A dataframe is loaded from S3 (CSV file of about 20GB with sessions data of users. each row has user_id, session_type, and start and end timestamps). 

`df = dd.read_csv(query_file)`

the purpose is to run an alg over all the events of each user_id. Using about 100 workers for 1.5M users. 

```
df = df.repartition(npartitions=1024) # not sure if this is proper here
df = df.set_index('user_id')
df = df.persist()
result = df.groupby('user_id').apply(run_alg)
```
All the above runs efficiently as expected
However, when I try to examin one user closely, the following statement just hangs forever, 

`sus = df.loc[random_user_id].compute()`

In the web UI I can see that the loc statement has executed but the compute function does not return. 
Using Jupyter Lab for execution. 
Using Python 3.8 and last Dask version on local and all workers.

Would be glad for any direction

**Comment by jsignell** [comment]
Is it possible that you are running out of memory? Does `df.loc[random_user_id].head()` or `df.loc[random_user_id].tail()` return?

**Comment by a-agmon** [comment]
Thanks for the reply @jsignell  (and apologies for the delay in answering). 
I have made several tests and, indeed, when the call to `df.loc[random_user_id].compute()` hangs then the call to `df.loc[random_user_id].tail()` also hangs and does not return. 
Where am I running out of memory? How can I resolve this? 
(I should also say that using the same dataset and cluster, sometimes I actually do get results and sometimes I don't) .
As you see below, doesnt really look like there is a memory issues on the cluster? right? 
![image](https://user-images.githubusercontent.com/54080741/133340376-08e1f50d-50e1-43af-8d8a-bfcfb5ae5337.png)

How can I adress this?

**Comment by jsignell** [comment]
Looking at this with fresh eyes I'm a little confused why you are both setting the index to `user_id` and doing a groupby on `user_id`. Also I assume this is just a typo in your reproducer, but you have `sus = result.loc[random_user_id].compute()` not `sus = df.loc[random_user_id].compute()` right?

**Comment by a-agmon** [comment]
Thanks for the response, @jsignell 
The run_alg function used here `df.groupby('user_id').apply(run_alg)`, is a function that accepts and calculates user data of one user_id. I call the `set_index('user_id')` beforehand in order to execute all the required shuffles first. 

There is no typo in the code I provided  - I run this `sus = df.loc[random_user_id].compute()` on the original df to test the function by examining the data it was running on

Am I missing something or doing something wrong? 

Thanks

**Comment by jsignell** [comment]
Ok thanks for the additional context! So the groupby is not part of this issue at all, it's a separate task graph. So it's really just an issue with calling `.set_index` and then `.loc`. I am thinking this might have to do with the number of unique user_ids. It should be fast to do a `loc` if the data is persisted.  Has the persist finished? You can use `wait` from distributed to check that.

I am trying to see if I can reproduce with something like:

```python
import uuid
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame(range(100000))
df["user_id"] = df[0].apply(lambda x: str(uuid.uuid4()))

ddf = dd.from_pandas(df, npartitions=1024)
ddf = ddf.set_index("user_id")
ddf = ddf.persist()

random_user_id = df.sample(n=1).user_id.item()
sus = ddf.loc[random_id].compute()
sus

**Comment by a-agmon** [comment]
Thanks, @jsignell, 
I can't get the prob reproducing with the code you suggested, though I have about 1.5 million users, each with about 100 records. 

At any rate, when my code hangs, it looks as if the actual `loc` has been completed, as you can see below: 

![image](https://user-images.githubusercontent.com/54080741/133906018-f075c4b6-b306-4266-82f0-59d3454932e1.png)

Does this mean that it hangs elsewhere? 

This is the full code im running - it hangs when it reaches this line ` sus = df.loc[rand_uid].compute()` while I do see the `loc` task was executed in the web UI

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pandas as pd
import dask.dataframe as dd
import dask.bag as db
import numpy as np
from dask.distributed import Client
import dask
import s3fs

def s3file_exist(file_name):
    s3 = s3fs.S3FileSystem(anon=False)
    return s3.exists(file_name)

def main():
    client = Client("127.0.0.1:8786")

    # S3 bucket data 

    query_file = ***********
    res_exist = dask.delayed(s3file_exist)(query_file)
    exist = res_exist.compute()
    print('Bucket access: ', exist)

    # load it to DF

    df = dd.read_csv(query_file)
    df['start_time'] = dd.to_datetime(df['start_time'])
    df['end_time'] = dd.to_datetime(df['end_time'])
    df['duration_minutes'] = (df['end_time'] - df['start_time']) / np.timedelta64(1, 'm')

    long_durations = df['duration_minutes'] > 5
    df = df[long_durations]

    print('repartitioning...')
    df = df.repartition(npartitions=1024) 
    df = df.set_index('user_id')

    print('persisting...')
    df = df.persist()
    num_users = df.index.nunique().compute()
    print('unique users:', num_users)
    ids = df.index.unique().compute()
    rand_user_id = np.random.choice(ids)
    print('testing random user id')
    sus = df.loc[rand_user_id].compute()
    print(sus)
    
if __name__ == "__main__":
    main()

```

**Comment by a-agmon** [comment]
closing this as the following code  - actually does not raise this issue

```python 
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pandas as pd
import dask.dataframe as dd
import dask.bag as db
import numpy as np
from dask.distributed import Client
import dask
import s3fs

def s3file_exist(file_name):
    s3 = s3fs.S3FileSystem(anon=False)
    return s3.exists(file_name)

def main():
    client = Client("127.0.0.1:8786")

    # S3 bucket data 

    query_file = ***********
    res_exist = dask.delayed(s3file_exist)(query_file)
    exist = res_exist.compute()
    print('Bucket access: ', exist)

    # load it to DF

    df = dd.read_csv(query_file)
    df['start_time'] = dd.to_datetime(df['start_time'])
    df['end_time'] = dd.to_datetime(df['end_time'])
    df['duration_minutes'] = (df['end_time'] - df['start_time']) / np.timedelta64(1, 'm')

    long_durations = df['duration_minutes'] > 5
    df = df[long_durations]

    print('repartitioning...')
   df = df.set_index('user_id')
   df = df.persist()

     #select a random user
    ids = df.index.unique().compute()
    rand_user_id = np.random.choice(ids)
    print('testing random user id:', rand_user_id)
    sus = df.loc[rand_user_id].compute()
    print(sus)
    
if __name__ == "__main__":
    main()
```

**Comment by jsignell** [comment]
I'm glad you were able to get it working :)
