### ISSUE TITLE
Track Index names as metadata in dask.dataframe

### ISSUE THREAD

**Issue by cowlicks** [dask/dask#812]
Currently to get the name of an index of a dask.dataframe, the dask must be computed. This is a small amount of metadata, which should change consistently. So we should be tracking it. This would touch a lot of dataframe creation code. And maybe give some idea about the difficulty of supporting MultiIndexs.

**Comment by mrocklin** [comment]
Seems like a reasonable idea.  You could integrate this into existing tests by adding this check to the `eq`  functions commonly used throughout the dask.dataframe tests.

**Comment by mrocklin** [comment]
From talking with Blake it sounds like this ends up touching a lot of code.  If we're going to consider doing something serious here then it might be good to get ideas from @sinhrks and @shoyer about how to pass through more pandas metadata.

One thought would be to pass through an empty version of the dask.dataframe object.  For example a `dd.DataFrame` might carry an empty `pd.DataFrame` and a `dd.Series` might carry an empty `pd.Series`.  These empty objects would carry metadata though, like `columns/name` and `index.name`.  This might also help to unify some of the internal API.

Any thoughts?

**Comment by shoyer** [comment]
Using an empty pandas object for metadata seems pretty sane to me.

**Comment by sinhrks** [comment]
This seems to be a valid approach which was in my mind for a dtype follow-up (#695).
Sorry I haven't started yet...

**Comment by mrocklin** [comment]
This would also be helpful in map_partitions because we could try the function on the empty dataframe and inspect the output
