### ISSUE TITLE
`.visualize()` returns wrong graph when having multiple arithmetic operations 

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#8140]
My understanding is that  Delayed objects support several standard Python operations, each of which creates another Delayed object representing the result. 
For example, it supports arithmetic operators, e.g. *, -, +

as a matter of fact, the following code shows this: 

```python
from time import sleep
from dask import delayed

@delayed
def inc(x):
    """Increments x by one"""
    sleep(1)
    return x + 1
```
```python
x = inc(1)
y = inc(2)
res = x + y 

res.visualize()
```
Returns this graph:

![Screen Shot 2021-09-13 at 6 57 53 PM](https://user-images.githubusercontent.com/7526622/133169340-c06882ad-bddb-4de4-ab95-af74809ff73c.png)

However, when doing 
```python
x = inc(1)
y = inc(2)
z = inc(3)
res = x + y + z 
res.visualize()
```
I get the following (not expected)

![Screen Shot 2021-09-13 at 6 58 46 PM](https://user-images.githubusercontent.com/7526622/133169403-b4beda0a-4038-41d5-9e8c-f9321d0d9d79.png)

When I would expect this: 

![Screen Shot 2021-09-13 at 7 05 29 PM](https://user-images.githubusercontent.com/7526622/133169427-6924597c-b0ab-4d2b-9dda-cec23ecaf67a.png)

I believe this is only a problem of visualization since the compute times are the same in both cases. To be more explicit
- Code that returns the wrong graph visualization
```python
%%time
x = inc(1)
y = inc(2)
z = inc(3)
res = x + y + z 
res.compute()
```
```
CPU times: user 2.93 ms, sys: 1.6 ms, total: 4.53 ms
Wall time: 1.01 s
```
- Code that returns the correct graph visualization
```python
%%time

x = inc(1)
y = inc(2)
z = inc(3)
res = delayed(sum)((x, y, z))
res.compute()
```
```
CPU times: user 2.64 ms, sys: 3.11 ms, total: 5.74 ms
Wall time: 1.01 s
```

What lets me think the problem is with the visualization but not the computation. 

**Environment**:

- Dask version: '2021.08.1'
- Python version: 3.9.6
- Operating System: macOS Big Sur 11.5.2
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
I think the visualization is correct. If you look at the materialized task graph you'll see that the add ends up as two tasks the second of which takes the output of the first as input. 

```python
In [9]: res.dask.to_dict()
Out[9]: 
{'add-2d1c959ff179ba14e812b3050a047e25': (<function _operator.add(a, b, /)>,
  'add-a2e723cf3abaf05f2723d1906005a301',
  'inc-7de76cf9-9430-4e0b-92fa-b71f1d9be6a0'),
 'add-a2e723cf3abaf05f2723d1906005a301': (<function _operator.add(a, b, /)>,
  'inc-d7ab70c2-7e79-4feb-9830-344ef1ef6801',
  'inc-f8a2ea40-ea5d-4468-8582-5394e0d31d58'),
 'inc-d7ab70c2-7e79-4feb-9830-344ef1ef6801': (<function __main__.inc(x)>, 1),
 'inc-f8a2ea40-ea5d-4468-8582-5394e0d31d58': (<function __main__.inc(x)>, 2),
 'inc-7de76cf9-9430-4e0b-92fa-b71f1d9be6a0': (<function __main__.inc(x)>, 3)}
```

**Comment by ncclementi** [comment]
Yep, after taking a look and studying a bit more about how the built-in `add` function works, this makes sense. It is basically computing first the sum of `x` and `y` and then adding that to `z`.  I'm not seeing a change in the times just because the two `add` in the graph of this example, take a few micro-seconds which is nothing compared to the order of magnitude of the `sleep(1)` of inc.  
```python
x = inc(1)
y = inc(2)
z = inc(3)
res = x + y + z 
res.visualize()
```
Closing this issue, since there is nothing wrong with the graph produced.
