### ISSUE TITLE
to_parquet fails when append=True

### ISSUE THREAD

**Issue by MrPowers** [dask/dask#8145]
**What happened**: Wrote some Parquet files to a directory.  Then tried to write more Parquet files with `append=True` and the code errored out.

**What you expected to happen**: I expected `append=True` to allow the second write to work.

**Minimal Complete Verifiable Example**:

```python
# this part works
df = pd.DataFrame(
    {"nums": [1, 2, 3, 4, 5, 6], "letters": ["a", "b", "c", "d", "e", "f"]}
)
ddf = dd.from_pandas(df, npartitions=2)

ddf.to_parquet("folder-fastparquet", engine="fastparquet")

df = pd.DataFrame(
    {"nums": [7, 8, 9, 10, 11, 12], "letters": ["g", "h", "i", "j", "k", "l"]}
)
ddf = dd.from_pandas(df, npartitions=3)

# this is the line that fails
ddf.to_parquet("folder-fastparquet", engine="fastparquet", append=True)
```

Here's the error message: ValueError: Appended divisions overlapping with previous ones.
Previous: 5 | New: 0

**Anything else we need to know?**: This also fails when PyArrow is used with a slightly different error message: ValueError: Appended divisions overlapping with the previous ones (set ignore_divisions=True to append anyway).
Previous: 5 | New: 0

**Environment**:

- Dask version: 2021.8.1
- Python version: 3.9.7 
- Operating System: macOS Big Sur
- Install method (conda, pip, source): conda

**Comment by MrPowers** [comment]
cc: @dask/io

**Comment by jrbourbeau** [comment]
Thanks for the nice reproducer @MrPowers. I think there are some assumptions we make about the `divisions` for the partitions for the DataFrame we're writing to disk. As you mentioned, setting `ignore_divisions=True` allows your example to work. Do you have a concrete suggestion as to how the current state of things may be improved? 

Also cc @rjzamora for visibility

**Comment by jcrist** [comment]
This isn't really a bug - by default `dd.from_pandas` results in a dask dataframe with known divisions. We currently assume that if a user is appending to a dataset that has known divisions (e.g. a sorted index column), that they want to enforce that sorting and do a check. The error message suggests setting `ignore_divisions=True`, which is the recommended solution here. I'll push up a quick patch to make the fastparquet error suggest this as well, and better clarify this in the docs.

**Comment by MrPowers** [comment]
Thanks @jcrist, sounds like this behavior is intentional and I confirmed the error message gives a nice hint to set `ignore_divisions=True`, so I'm going to close this one.  Thank you!
