### ISSUE TITLE
Improve `DataFrame.query` docstring with local variable example

### ISSUE THREAD

**Issue by umonaca** [dask/dask#8156]
**What happened**:
Prepare Dask distributed:
```
from dask.distributed import Client

client = Client(n_workers=16,
                threads_per_worker=1)
```

This works:
```python
import pandas as pd

data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)
pick = 'c'
df.query('col_2 == @pick')
```
This doesn't work:
```python
dd_temp = dd.from_pandas(df, npartitions=2)
dd_temp.query('col_2 == @pick')
```
Throws UndefinedVariableError("local variable 'pick' is not defined").  

**What you expected to happen**:
Dask version of DataFrame.query should work as in pandas.

**Minimal Complete Verifiable Example**:
See above

**Anything else we need to know?**:
No

**Environment**:

- Dask version: 2021.8.0
- Python version: 3.9.6
- Operating System: Linux (Manjaro)
- Install method (conda, pip, source): conda-forge

**Comment by jsignell** [comment]
Hmm yeah I don't think the `@` syntax is necessarily supported in dask. As a workaround either of these will work:

```python
dd_temp.query(f'col_2 == "{pick}"').compute()
```

```python
dd_temp[dd_temp["col_2"] == pick].compute()
```

**Comment by jsignell** [comment]
Or you can do 

```python
dd_temp.query('col_2 == @pick', local_dict={"pick": pick}).compute()

**Comment by umonaca** [comment]
> Hmm yeah I don't think the `@` syntax is necessarily supported in dask. As a workaround either of these will work:
> 
> ```python
> dd_temp.query(f'col_2 == "{pick}"').compute()
> ```
> 
> ```python
> dd_temp[dd_temp["col_2"] == pick].compute()
> ```

Sometimes there will be complex queries. Besides, f-string does not always work, for example, if you want to use datetime object into the query.

**Comment by jrbourbeau** [comment]
Will @jsignell's other suggestion (xref https://github.com/dask/dask/issues/8156#issuecomment-921153847) work in that case?

```python
dd_temp.query('col_2 == @pick', local_dict={"pick": pick}).compute()
```

**Comment by ncclementi** [comment]
@umonaca Checking in here, Do you think the second suggestion made here https://github.com/dask/dask/issues/8156#issuecomment-921153847 would work in that case?

**Comment by umonaca** [comment]
I'll look into it tomorrow.

**Comment by jrbourbeau** [comment]
Just checking in, @umonaca did this work out?

**Comment by umonaca** [comment]
> Just checking in, @umonaca did this work out?

The solution works. However, I think you should document this parameter in `dask.dataframe.DataFrame.query`.

**Comment by jsignell** [comment]
Ohh! That's true https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.query.html is very thin! I only realized that pattern was supported because I was looking around in the tests. Please feel free to open a pull request with an example of that pattern @umonaca!
