### ISSUE TITLE
Repartition by frequency errors for DatetimeIndex

### ISSUE THREAD

**Issue by jordanparker6** [dask/dask#8159]
I am trying to read in a collection of parquet files that have been indexed by a Datetime column. I have checked the columns and confirmed that the read_parquet method is reading in Datetime values. However, even with the Datetime column set as the index, I get the following error ``` TypeError: Can only repartition on frequency for timeseries```

The code to reproduce this error is below.

```
    files = list(Path("./compressed").glob("*.parquet"))

    df = dd.read_parquet(files[0])
    df["market_id"] = "BIN:" + files[0].stem

    for file in files[1:2]:
        new = dd.read_parquet(file)
        new["market_id"] = "BIN:" + file.stem
        df = dd.concat([df, new], axis=0)

    print(type(df.index.compute()))
    df = df.repartition(freq='MS')
```

Looking at the source code, the TypeError is being thrown here.

```
def repartition_freq(df, freq=None):
    """Repartition a timeseries dataframe by a new frequency"""
    if not isinstance(df.divisions[0], pd.Timestamp):
        raise TypeError("Can only repartition on frequency for timeseries")
```

If I print my df.divisions[0], you can see the value is None despite the type of index being  evaluated as a pd.DatetimeIndex. The df.npartitions output is 2. 

Any reason why the DatetimeIndex is not being recognised?

**Comment by jsignell** [comment]
If you do `df.known_divisions` you'll get `False` which means that dask doesn't know the start and end of the index for each partition. This might happen because your index isn't set on the dask dataframe or isn't sorted. To fix this issue, you can explicitly set the index like: `df = df.set_index("index")`. If that doesn't work, you may need to unset the index first. Something like: `df  = df.reset_index().set_index("index")`

**Comment by jordanparker6** [comment]
> If you do `df.known_divisions` you'll get `False` which means that dask doesn't know the start and end of the index for each partition. This might happen because your index isn't set on the dask dataframe or isn't sorted. To fix this issue, you can explicitly set the index like: `df = df.set_index("index")`. If that doesn't work, you may need to unset the index first. Something like: `df = df.reset_index().set_index("index")`

The lack of sorting looked it was the issue. `df = df.reset_index().set_index("index")` worked a charm. Thanks a lot for your help. 

When saving to disk, I was aiming to have the parts saved by yyyy-mm or in a directory structure yyyy/mm. However, it was just saved as part-*.parquet. Is the ability to control the partitions filenames present?

**Comment by jsignell** [comment]
There is an open pull request for controlling the filename (https://github.com/dask/dask/pull/7682), but you should be able to save in a particular directory structure using the `partition_on` option on `to_parquet` but I think it only allows one level of nesting.

**Comment by jsignell** [comment]
I'm going to close this issue since it seems like the original issue is resolved, but if you run into anything else, please feel free to open a new issue!
