### ISSUE TITLE
Example using dask.array.learn on non-trivial data

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#817]
We built `dask.array.learn` a long while ago https://github.com/blaze/dask/pull/138 . 

It's a fairly trivial pairing of sklearn and dask.array (and honestly something that `sklearn` does just fine with a for loop).  Still, it's something that more established libraries show off, so we might as well have a clear user example on how to combine a large HDF5 file with an sklearn classifier using dask.array, probably something like the following

```python
from sklearn import MyFavoriteEstimator
e = MyFavoriteEstimator()

import h5py
X = h5py.File(...)['/X']
y = h5py.File(...)['/X']

import dask.array as da
X = da.from_array(X, chunks=(...))
y = da.from_array(y, chunks=(...))

da.learn.fit(e, X, y)
e.predict(new_X)
```

The hard thing here is to find a large and meaningful dataset and the right estimator within `sklearn` that supports partial fitting.  Then this work should be publicized in some way, perhaps both in documentation and in some sort of blogpost / notebook.

**Comment by shoyer** [comment]
Dictionary learning with a large stack of images would be an interesting application.

**Comment by mrocklin** [comment]
I agree.  It might be good through to have a straight vanilla problem as well that fits into the above mold.  I think I'm mostly looking for a demonstration of capability of the common case.

**Comment by to266** [comment]
Once I finally add `dask` to `hyperspy`, PCA (or, more likely, [incremental PCA](http://scikit-learn.org/stable/modules/decomposition.html#incremental-pca) ) will no doubt be one of the most widely used features with big datasets.
It's extremely common to perform dimensionality-reduction on electron microscopy datasets, and later on perform ICA or something of that sort.

**Comment by shoyer** [comment]
Incremental PCA does seem like a better example -- dictionary learning can
be very slow. How is it different from the existing chunked linear algebra
routines already in dask, though?

On Tue, Nov 3, 2015 at 2:04 AM, Tomas Ostasevicius <notifications@github.com

**Comment by to266** [comment]
It may not be - I have not had a look. In my mind (never having had to implement it myself) PCA is just an SVD with some pre- and post-processing. On the other hand, you don't have to reinvent the wheel and just plug-and-play with different decompositions (NMF, PCA, incremental PCA)

**Comment by mrocklin** [comment]
My guess is that algorithms like SGD might still be valuable to demonstrate.

**Comment by datnamer** [comment]
How about blaze streaming from a database to sgd? That would be really cool.

**Comment by mrocklin** [comment]
This is ill-formed and stale.  Closing.

Also: http://matthewrocklin.com/blog/work/2016/04/20/dask-distributed-part-5
