### ISSUE TITLE
When updating a parquet dataset on S3 using arrow-engine it fails reading the schema (_get_dataset_offset)

### ISSUE THREAD

**Issue by Paul424** [dask/dask#8175]
When creating a new parquet (hive partitioned) dataset on S3 using pyarrow this runs fine initially; the parts are created, so is the common/metadata.

But then when updating this dataset with additional chunks of data it asserts.

Notice this is a:
- (hive) partitioned dataset
- pyarrow engine selected
- schema explicitly provided (so no infer of schema)

code fragment:

```python
    ddf = dd.from_pandas(pdf, npartitions=1)
    ddf.to_parquet(
        path="s3://<my-bucket>/<my-path>",
        engine="pyarrow",
        compression="snappy",
        write_index=False,
        append=<initially False, then True>,
        overwrite=False,
        ignore_divisions=True,
        partition_on=['a', 'b', 'c'],
        write_metadata_file=True,
        compute=True,
        schema=schema,
    )
```

Callstack to the assert is as follows:

`  File "/opt/miniconda/envs/igx3/lib/python3.8/site-packages/dask/dataframe/core.py", line 4540, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/opt/miniconda/envs/igx3/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 644, in to_parquet
    meta, schema, i_offset = engine.initialize_write(
  File "/opt/miniconda/envs/igx3/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 830, in initialize_write
    arrow_schema = fmd.schema.to_arrow_schema()
AttributeError: 'NoneType' object has no attribute 'schema'
`

Dask inspects if there are other file-fragments (and there are). Then pyarrow is invoked to read the metadata (in _get_dataset_offset).

`fmd = pq.read_metadata(fs.sep.join([path, "_metadata"]))`

However there seems to be no support for S3 on that pyarrow function: https://github.com/dask/dask/blob/main/dask/dataframe/io/parquet/arrow.py#L751

Metadata is read, schema is accessible and the update can proceed.

I can image pyarrow engine doesn't support this specific setup, what other engines should support this setup?

And also are there any drawbacks writing directly to S3, any alternatives?

**Environment**:

- fsspec==2021.8.1
- s3fs==2021.8.1
- dask==2021.9.1
- pyarrow==5.0.0
- Python version: 3.8.5
- Operating System: Ubuntu
- Install method: pip

**Comment by jsignell** [comment]
Ping @martindurant for ideas on this one.

**Comment by martindurant** [comment]
I expect that `engine="fastparquet"` handles this fine. On calling the specific method that does not handle filesystems, I have not yet looked in details, but very probably that pyarrow method can take a file-like object as created by fsspec
```
with fs.open(fs.sep.join([path, "_metadata"])) as f:
    fmd = pq.read_metadata(f)
```

Perhaps your specific code path is not hit in our test suite.

cc @rjzamora

**Comment by rjzamora** [comment]
Thanks for the clear writeup @Paul424 - We should certainly be passing a file-like object to `pq.read_metadata` (rather than a path).  I submitted #8186 with the fix already suggested by Martin.
