### ISSUE TITLE
Read the docs permissions

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask#8189]
@jsignell and I are continuing with our docs work (see #7984 and dask/dask-sphinx-theme#54).

Could we get maintainer rights on Read the Docs so we can check some settings in there? Given that we are both org owners it would be really helpful to have maintainer rights on all RTD sites.

cc @mrocklin @jrbourbeau

**Comment by mrocklin** [comment]
I've added Jacob (I got his login from the dask-cloudprovider rtd site).
Julia, are you jsignell?

**Comment by jrbourbeau** [comment]
Closing as Matt added Jacob and Julia in RTD. Thanks @mrocklin!

**Comment by jacobtomlinson** [comment]
Thanks all!
