### ISSUE TITLE
setting column names has no effect

### ISSUE THREAD

**Issue by DSLituiev** [dask/dask#819]
I am doing a table join and would like to rename columns in the resulting table `acs` afterwards. So I set: 

`acs.columns = ["chr","start", "end", "rep1", "rep2"]`

It allegedly works:
```
In [11]: acs.columns
Out[11]: ['chr', 'start', 'end', 'rep1', 'rep2']
```

But not really:
```
In [12]: acs.head()
Out[12]:
    chr  start    end  counts_x  counts_y
0  chr1  15765  17765         5         1
...
```

**Comment by TomAugspurger** [comment]
Consider using `acs.rename(columns=)` and provide a mapping or function like [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rename.html?highlight=rename#pandas.DataFrame.rename).

Is there a reason `.columns` isn't read-only like `.column_info`?

**Comment by mrocklin** [comment]
@TomAugspurger 's suggestions are spot on.  The `.columns` attribute should be read-only.  The `rename` function should be used here.

**Comment by DSLituiev** [comment]
that is a solution, but it will make things much more complicated: instead of giving a list, I will need to first write a dictionary and then write a function. It is definitely a solution, but a direct set method can save a lots of time in my case of interactive hacking.

**Comment by TomAugspurger** [comment]
@DSLituiev `df = df.rename(columns=dict(zip(df.columns, new_columns)))`, slightly inconvenient but not too bad. dask has a few more things to track than pandas.

**Comment by mrocklin** [comment]
We can also eventually add the direct column assignment as a property change.  This seems reasonable to roll in if we change the metadata from a list of columns to an empty DataFrame.

**Comment by mrocklin** [comment]
It looks like this works now?

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.demo.daily_stock('GOOG', '2008', '2010', freq='1s', 
   ...:                          random_state=1234)

In [3]: 

In [3]: df
Out[3]: 
Dask DataFrame Structure:
                       close     high      low     open
npartitions=505                                        
2008-01-02 09:00:00  float64  float64  float64  float64
2008-01-03 09:00:00      ...      ...      ...      ...
...                      ...      ...      ...      ...
2009-12-31 09:00:00      ...      ...      ...      ...
2009-12-31 16:00:00      ...      ...      ...      ...
Dask Name: from-delayed, 1010 tasks

In [4]: df.columns = list(map(str.upper, df.columns))

In [5]: df
Out[5]: 
Dask DataFrame Structure:
                       CLOSE     HIGH      LOW     OPEN
npartitions=505                                        
2008-01-02 09:00:00  float64  float64  float64  float64
2008-01-03 09:00:00      ...      ...      ...      ...
...                      ...      ...      ...      ...
2009-12-31 09:00:00      ...      ...      ...      ...
2009-12-31 16:00:00      ...      ...      ...      ...
Dask Name: rename, 1515 tasks

In [6]: df.head()
Out[6]: 
                       CLOSE     HIGH      LOW     OPEN
timestamp                                              
2008-01-02 09:00:00  692.889  692.889  692.840  692.871
2008-01-02 09:00:01  692.776  692.868  692.776  692.868
2008-01-02 09:00:02  692.737  692.818  692.737  692.797
2008-01-02 09:00:03  692.632  692.711  692.632  692.711
2008-01-02 09:00:04  692.521  692.637  692.521  692.637
```
