### ISSUE TITLE
Support assignment of scalars based on boolean indexes

### ISSUE THREAD

**Issue by randerzander** [dask/dask#8190]
With Dask DataFrame, I often want to update values for columns only if some condition holds true for the values of one or more columns in those rows.

For example:
```
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> 
>>> df = pd.DataFrame({'id': [0, 1, 2, None]})
>>> ddf = dd.from_pandas(df, npartitions=1)
>>> ddf[ddf['id'] > 1] = -1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/jit/lib/python3.8/site-packages/dask/dataframe/core.py", line 4121, in __setitem__
    raise NotImplementedError(f"Item assignment with {type(key)} not supported")
NotImplementedError: Item assignment with <class 'dask.dataframe.core.Series'> not supported
```

This is supported in Pandas:
```
>>> df[df['id'] > 1] = -1
>>> df
    id
0  0.0
1  1.0
2 -1.0
3  NaN
```

**Comment by mrocklin** [comment]
We've wanted to do this for a while, but mutable semantics have made it
hard (I did this once in a PR, Julia did too I think)

The workaround is to use the where method I think.  Short term maybe we can
improve the error message to point to this method?  Longer term I'd love to
see proper support here if that's doable.

(This is a drive by comment, I apologize if I don't follow up to responses)

**Comment by charlesbluca** [comment]
Is there any reason we can't just rely on the same `where` call used when the `key` is a dataframe or dataframe-like?

```diff
diff --git a/dask/dataframe/core.py b/dask/dataframe/core.py
index 88032cca41..650232cbbd 100644
--- a/dask/dataframe/core.py
+++ b/dask/dataframe/core.py
@@ -4115,7 +4115,11 @@ def __setitem__(self, key, value):
         elif isinstance(key, pd.Index) and not isinstance(value, DataFrame):
             key = list(key)
             df = self.assign(**{k: value for k in key})
-        elif is_dataframe_like(key) or isinstance(key, DataFrame):
+        elif (
+            is_dataframe_like(key)
+            or is_series_like(key)
+            or isinstance(key, (DataFrame, Series))
+        ):
             df = self.where(~key, value)
         elif not isinstance(key, str):
             raise NotImplementedError(f"Item assignment with {type(key)} not supported")
```

This seems to give us consistent behavior with Pandas, but I'm not sure if there's ideally a less expensive way to do this.

**Comment by charlesbluca** [comment]
Looks like that diff was merged in. which should resolve this - happy to open a follow up issue if there's a better way to do this.
