### ISSUE TITLE
s3fs and other extras not listed as extras in setup.py

### ISSUE THREAD

**Issue by leos** [dask/dask#8208]
It's great that there's a list of optional dependencies here - https://docs.dask.org/en/latest/install.html#optional-dependencies - but is there a good reason they aren't added as extras into setup.py?

As it is now, someone installing with `pip` needs to manage the version of dependencies such as `s3fs` or `pyarrow` themselves. If the optional dependencies were configured as extras then `pip install dask[s3fs,pyarrow]` would take care of it and would automatically manage the appropriate versions as new versions of `dask` were installed.

**Comment by jcrist** [comment]
Dask has lots of optional dependencies, adding them all as `extras` to our `setup.py` was deemed unmaintainable, and a list of dependencies in the docs favored instead. Other projects (e.g. pandas https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies) also ran into this issue and came to the same conclusion. See https://github.com/dask/dask/pull/5209 for a full thread hashing this out.
