### ISSUE TITLE
Pandas 1.2.0 compatibility - `std()` for the `datetime64[ns]` dtype

### ISSUE THREAD

**Issue by jsignell** [dask/dask#8214]
This doesn't work yet in dask because here the implementation of `std` generally depends on `var`, which doesn't work for datetimes. 

Some tests are skipped for this in `dask/dataframe/tests/test_arithmetics_reduction.py`

**Comment by jsignell** [comment]
I thought I'd split up #7100 to make it easier to keep track of the different parts.

**Comment by bglossner** [comment]
Does this seem like an okay **first issue**? I'd like to take this on if so! I just don't want to start an issue someone else might be able to do much quicker if I get stuck. Thanks!

**Comment by jsignell** [comment]
It's a pretty good first issue in that you probably don't need a ton of dask-specific knowledge. But it might be a good bit of work. Please feel free to take it on and ping me if you get stuck.

**Comment by bglossner** [comment]
I'll give it a shot then! Thanks for such a quick response.

**Comment by bglossner** [comment]
Sweet, thanks! I left some responses on the commit and will create a WIP PR for the next commit(s) I make.

**Comment by bglossner** [comment]
Left some more interesting problems I am seeing in https://github.com/bglossner/dask/commit/922d7a1e28a7452153d3b72f54aa48f91d871acc when using 250 large numbers.

**Comment by bglossner** [comment]
Sorry for the long break! Created a PR when you have the time. It addresses the `dtype` error I was getting and also has code for doing `axis=1`.

**Comment by jsignell** [comment]
No worries! Thanks for picking it back up!
