### ISSUE TITLE
Nested documentation redirects not working

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8255]
I noticed that our documentation redirect which use nested URLs 

https://github.com/dask/dask/blob/e98d4f2cf8884d142b93c9fb2405d47e4ad02a54/docs/source/conf.py#L362-L374

don't redirect properly. For example, we want https://docs.dask.org/en/latest/setup/cloud.html to redirect to https://docs.dask.org/en/latest/how-to/deploy-dask/cloud.html, however today we're redirected to https://docs.dask.org/en/latest/setup/how-to/deploy-dask/cloud.html instead (note that `setup/` is still in the URL) which doesn't exist.

cc @jacobtomlinson @jsignell for visibility

**Comment by jsignell** [comment]
Rats. Thanks for wrtiting this up James. I will take a look. Worst comes to worst I can just move them all back.
