### ISSUE TITLE
TypeError: len() of unsized object when converting dask array to tensor

### ISSUE THREAD

**Issue by HarryDresden1** [dask/dask#8260]
**What happened**: I use dask for my preprocessing pipeline and in the end, I want to convert it to a PyTorch tensor when I try to do so I get the error "TypeError: len() of unsized object". Although if I tried to do this within a delayed function it works, as in the commented line.

**What you expected to happen**: I expected it to work without using delayed, as if the operations performed using dask array is replaced as NumPy it works.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import torch

x = da.random.random(size=(256, 64, 64, 3))

res = da.stack([x, x], axis=0)

# res = dask.delayed(torch.as_tensor)(res)
res = torch.as_tensor(res)

res.compute()
```

**Environment**:

- Dask version: 2021.9.1 
- PyTorch version: 1.9.1
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by samgans** [comment]
Hi! I can look at the issue and try to understand what's going on.
