### ISSUE TITLE
Improve documentation of `DataFrame.divisions`

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#8264]
Talking to a user recently, they were confused about how to pass `divisions=` in `set_index`. Specifically, they missed that the list had to have N+1 elements in it, and the N+1th element was the upper bound for the last partition.

The API docs currently link to https://docs.dask.org/en/latest/dataframe-design.html#partitions, which does describe this in words, but takes some close reading to get.

A simple example of setting `divisions` using a list of values, both in the `set_index` docs and in the dataframe design section, might be helpful.

**Comment by ncclementi** [comment]
Related to this issue We were chatting about the `divisions` section of the[ docs in set_index](https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.set_index.html#dask-dataframe-dataframe-set-index) where it says

"If sorted=False, you should leave divisions empty and call repartition after set_index." It looks like this comment was introduced a long time ago by @jcrist (see https://github.com/dask/dask/commit/ad752cce5ee01fcc88f341ab707372aee08c050e) and we wonder if this is still the case, or the docs are missing an update. Jim, do you remember why this comment was added at the time and if this still holds?

cc: @gjoseph92

**Comment by jsignell** [comment]
I think I understand what the original meaning was. I opened a PR to clarify.
