### ISSUE TITLE
Flaky test - test_progress.py::test_register

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#8268]
**What happened**:
I'm noticing a flaky test when I run the dask test suite locally (`test_register` in the file `test_progress.py`). Can anybody else reproduce this?

**What you expected to happen**:
I expect that this test should pass every time I run pytest, and not fail intermittently.

**Minimal Complete Verifiable Example**:

I don't know how *reproducible* this is, given it's a flaky test, but this is what I did to fairly reliably reproduce it on my machine.

1. Create a conda dask development environment, following the  [Dask development installation instructions](https://docs.dask.org/en/latest/develop.html)
    ```
    conda env create -n dask-dev -f continuous_integration/environment-latest.yaml
    conda activate dask-dev
    python -m pip install --no-deps -e .
    ```

2. Ran pytest with `py.test dask --verbose --doctest-modules` (again, as suggested by the [Dask development installation instructions](https://docs.dask.org/en/latest/develop.html))

3. Saw the test fail: `FAILED dask/diagnostics/tests/test_progress.py::test_register - assert not {(<bound method CacheProfiler....`

**Anything else we need to know?**:

There were a few weird things:
* I only saw this test fail when I ran the entire test suite with `py.test dask --verbose --doctest-modules`. If I ran pytest on just that one test or file, then `test_register` would pass.
* I only saw this test fail when I used the conda Dask development installation instructions (it did not fail in my environment where I'd used the equivalent pip commands to install the dask development version). I followed [these instructions](https://docs.dask.org/en/latest/develop.html) for creating environments:
    ```
    conda env create -n dask-dev -f continuous_integration/environment-latest.yaml
    conda activate dask-dev
    python -m pip install --no-deps -e .
    ```

Here are the test failure details:
```
FAILED dask/diagnostics/tests/test_progress.py::test_register - assert not {(<bound method CacheProfiler....
```
<details>
<summary>Details - click to expand!:</summary>

```python-traceback
================================================= FAILURES =================================================
______________________________________________ test_register _______________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fcf6c1ff520>

    def test_register(capsys):
        try:
            p = ProgressBar()
            p.register()
    
            assert Callback.active
    
            get_threaded(dsk, "e")
            check_bar_completed(capsys)
    
            p.unregister()
    
>           assert not Callback.active
E           assert not {(<bound method Profiler._start of <dask.diagnostics.profile.Profiler object at 0x7fcf6c0abe20>>, None, <bound method ...None, <bound method ResourceProfiler._finish of <dask.diagnostics.profile.ResourceProfiler object at 0x7fcf6c0abf70>>)}
E            +  where {(<bound method Profiler._start of <dask.diagnostics.profile.Profiler object at 0x7fcf6c0abe20>>, None, <bound method ...None, <bound method ResourceProfiler._finish of <dask.diagnostics.profile.ResourceProfiler object at 0x7fcf6c0abf70>>)} = Callback.active

dask/diagnostics/tests/test_progress.py:81: AssertionError
============================================= warnings summary =============================================
```

</details>

**Environment**:

- Dask version:  2021.9.1+40.g898afc04 (current Dask main branch)
- Python version:  3.8 (I think I also tried python 3.9 at some stage too, but don't totally remember)
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): I followed [these instructions](https://docs.dask.org/en/latest/develop.html) for creating environments:
    ```
    conda env create -n dask-dev -f continuous_integration/environment-latest.yaml
    conda activate dask-dev
    python -m pip install --no-deps -e .
    ```

**Comment by sayantikabanik** [comment]
I tried to build `dask` from the source and followed similar steps.
Faced a similar issue with `flaky plugin`

Issue - [8210](https://github.com/dask/dask/issues/8210)
<details>
<summary> Log </summary>
``` Python
================================================================================================== ERRORS ==================================================================================================
_________________________________________________________________________________ ERROR at setup of test_shuffle_priority __________________________________________________________________________________

self = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x101602a90>, item = <Function test_shuffle_priority>

    def pytest_runtest_setup(self, item):
        """
        Pytest hook to modify the test before it's run.
    
        :param item:
            The test item.
        """
        if not self._has_flaky_attributes(item):
            if hasattr(item, 'iter_markers'):
                for marker in item.iter_markers(name='flaky'):
>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)
E                   TypeError: _make_test_flaky() got an unexpected keyword argument 'reruns'

_____________________________________________________________________________________ ERROR at setup of test_interrupt _____________________________________________________________________________________

self = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x101602a90>, item = <Function test_interrupt>

    def pytest_runtest_setup(self, item):
        """
        Pytest hook to modify the test before it's run.
    
        :param item:
            The test item.
        """
        if not self._has_flaky_attributes(item):
            if hasattr(item, 'iter_markers'):
                for marker in item.iter_markers(name='flaky'):
>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)
E                   TypeError: _make_test_flaky() got an unexpected keyword argument 'reruns'
```
</details>

**Comment by GenevieveBuckley** [comment]
That looks unrelated to this issue @sayantikabanik

**Comment by sayantikabanik** [comment]
I have delinked the issue, to avoid added confusion
