### ISSUE TITLE
Potentially use tblib to handle errors on workers

### ISSUE THREAD

**Issue by jcrist** [dask/dask#831]
Currently we use a custom Exception object to wrap errors on workers, and reraise the exception in the scheduler process/thread. This works, but can have some funky looking errors. [tblib](https://github.com/ionelmc/python-tblib) provides a way to handle this in a mildly clean way.

Pros: tracebacks and errors without extra junk from handling.
Cons: only works on cpython

**Comment by mrocklin** [comment]
cc @freeman-lab

**Comment by mrocklin** [comment]
The distributed scheduler uses `tblib` and it seems to work well.
