### ISSUE TITLE
divisions lost when using index.to_series

### ISSUE THREAD

**Issue by JoranDox** [dask/dask#8319]
**What happened**:
I wanted to use the index column to filter on, but that was a lot harder than using a regular columns, while it should be faster & I'd hope at least as easy to work with.
Using an index doesn't behave like a regular columns (series), and transforming to a series (as workaround) gives a different error.

**What you expected to happen**:
Use an index as a regular column (series), failing that, transforming the index to a series and using that like a regular columns (with the same divisions)

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask

df = pd.DataFrame([{"a": "A", "b": "B"}, {"a": "@", "b": "β"}, {"a": "Aa", "b": "Bb"}, {"a": "aa", "b": "bb"}])

ddf = dask.dataframe.from_pandas(df, npartitions=2)

ddf2 = ddf.set_index("a")

ddf2.divisions
# ('@', 'Aa', 'aa')

ddf2.index.divisions
# ('@', 'Aa', 'aa')

ddf2.index.to_series().divisions
# (None, None, None)

# this works with a regular column
ddf2[ddf2.b.str.endswith("b")].compute()
# selects the rows where column b ends with "b"

# indices don't behave like columns
ddf2[ddf2.index.str.endswith("a")].compute()
# TypeError: '<' not supported between instances of 'bool' and 'str'

# workaround: turn index to series
ddf2[ddf2.index.to_series().str.endswith("a")].compute()
# ValueError: Not all divisions are known, can't align partitions. Please use `set_index` to set the index.

# workaround for the workaround: add the divisions manually
itos = ddf2.index.to_series()
itos.divisions = ddf2.divisions
ddf2[itos.str.endswith("a")].compute()
# selects the rows where index column a ends with "a"

```

**Anything else we need to know?**:
Other ways to do this without workarounds are welcome too, but in general I think it's valid to assume that index.to_series keeps the divisions set on the index.

**Environment**:

- Dask version: '2021.09.1'
- Python version: Python 3.9.7
- Operating System: jupyter docker image with some additions
- Install method (conda, pip, source): probably conda as the pip freeze just says dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1632274741088/work

**Comment by jrbourbeau** [comment]
Thanks for raising an issue. The latest `dask==2021.10.0` release contains this PR https://github.com/dask/dask/pull/8165 which results in `ddf2[ddf2.index.to_series().str.endswith("a")].compute()` no longer raising a `ValueError`. Could you try upgrading to the latest `dask` release to see if that resolves your issue?

**Comment by JoranDox** [comment]
Nice, that works like a charm, thanks!

Should I open a separate bug report / feature request for dask to allow using indices as columns? It seems like something deeply ingrained in dask and as such hard to fix (although e.g. map_partitions would just work I assume?)

**Comment by JoranDox** [comment]
I've started with posting this instead: https://stackoverflow.com/questions/69807167/dask-index-not-behaving-like-a-column-and-not-like-in-pandas
