### ISSUE TITLE
Why is it undesirable for delayed functions to mutate inputs?

### ISSUE THREAD

**Issue by zzhengnan** [dask/dask#8324]
Hi team! Regarding the following piece of best practice from https://docs.dask.org/en/latest/delayed-best-practices.html#don-t-mutate-inputs, why is it not ideal for delayed functions to mutate their inputs?
> Don't mutate inputs
> Your functions should not change the inputs directly.

Is it due to considerations for potential race conditions when the same function has been scheduled to run more than once in a concurrent fashion?

Separately, I'm wondering if there's a more intuitive example we should consider using, as opposed to the current `x += 1` and `x = x + 1`. For integers (and potentially other immutable types as well), I _think_ the two are equivalent.

Thanks!

**Comment by ncclementi** [comment]
Hi @zzhengnan, thanks for opening this issue! It seems like this question is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/t/how-to-use-the-dask-discourse/21). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse.

**Comment by zzhengnan** [comment]
Thanks for the suggestion, @ncclementi.

Done! https://dask.discourse.group/t/why-is-it-undesirable-for-delayed-functions-to-mutate-inputs/57
