### ISSUE TITLE
empty partition in from_delayed

### ISSUE THREAD

**Issue by pinnnnnnz** [dask/dask#8327]
When I use `from_delayed([a list of partition (pandas DF)])`, if there is one partition/df is empty, it will throw an error.
<img width="446" alt="Screen Shot 2021-11-01 at 6 37 29 PM" src="https://user-images.githubusercontent.com/77021940/139772716-ee0d4288-1eb3-42ab-bf7d-861d9a181db4.png">
My current work around is to manually keep those that is not empty but it could be extremely slow when we have a lot of partitions. Could we have a native implementation to get rid of those empty partitions?

**Comment by ncclementi** [comment]
Hi @pinnnnnnz thank you for raising this issue, can you please provide a [Minimal Complete Verifiable Example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) so we can reproduce the error?

**Comment by jrbourbeau** [comment]
Here's a snippet that results in the same error

```python

from dask.delayed import delayed
import numpy as np
import pandas as pd
import dask.dataframe as dd
from dask import delayed

@delayed
def gen_partition(x):
    if x < 5:
        return pd.DataFrame({"a": np.random.random(10)})
    else:
        return pd.DataFrame()


ddf = dd.from_delayed([gen_partition(i) for i in range(10)])
ddf.compute()
```

<details>
<summary>Full traceback:</summary>

```python
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test-from-delayed.py", line 17, in <module>
    ddf.compute()
  File "/Users/james/projects/dask/dask/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/james/projects/dask/dask/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/james/projects/dask/dask/dask/threaded.py", line 79, in get
    results = get_async(
  File "/Users/james/projects/dask/dask/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/Users/james/projects/dask/dask/dask/local.py", line 315, in reraise
    raise exc
  File "/Users/james/projects/dask/dask/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/dataframe/utils.py", line 406, in check_meta
    raise ValueError(
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `pandas.core.frame.DataFrame`
+--------+-------+----------+
| Column | Found | Expected |
+--------+-------+----------+
| 'a'    | -     | float64  |
+--------+-------+----------+
```

</details>

@pinnnnnnz by default Dask will check that a DataFrame's partitions have a consistent schema. If you don't want this behavior, then you can set `verify_meta=False` in your `from_delayed` call

**Comment by ncclementi** [comment]
@pinnnnnnz checking-in here, does the answer above that suggests setting `verify_meta=Flase`solve your problem?

**Comment by pinnnnnnz** [comment]
> @pinnnnnnz checking-in here, does the answer above that suggests setting `verify_meta=Flase`solve your problem?

It does. But I was hesitant to use it because I also want it to be `True` to ensure the meta though.

**Comment by pavithraes** [comment]
@pinnnnnnz Thanks for opening this issue! I think `@jrbourbeau`'s solution sounds good, so I'm boldly closing this as resolved. If the issue persists, or you'd like to propose a new feature, please feel free to re-open it!
