### ISSUE TITLE
AttributeError: module 'dask' has no attribute 'array'

### ISSUE THREAD

**Issue by AhmetCanSolak** [dask/dask#8329]
**What happened**:
I am not able to use any endpoint on `dask.array`. Getting the mentioned attribute error.

**What you expected to happen**:
I was expecting dask to behave as before. I wanted to some simple operations like `dask.array.stack()`.

**Minimal Complete Verifiable Example**:

```python
import dask

print(dask.array.stack)
```

**Anything else we need to know?**:
I need to install from pip. I am using it as a dependency on a package I am developing.

**Environment**:

- Dask version: 2021.10.0 
- Python version: 3.9.7
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip, I tried everything: `dask`, `dask[array]`, `dask[complete]`.

**Comment by douglasdavis** [comment]
To use `dask.array` you'll need to `import dask.array`. Out of curiosity what version of Dask were you able to use `dask.array` by only importing `dask`?

**Comment by AhmetCanSolak** [comment]
Thank you for prompt answer. I cannot recall exact version as I am not pinning dask version but should be something like `2021.3.0` according to pypi release history.
