### ISSUE TITLE
get_async and chunksize

### ISSUE THREAD

**Issue by SebastienDorgan** [dask/dask#8333]
Looking at the code of the _get_ functions offered by dask, I wonder about the use of the chunksize argument for the threaded and multiprocessing cases and their relationship with _local.get_async_.
It would seem to me that it makes more sense to reason in terms of number of partitions (nb_chunks) than in partition size. By doing this _get_async_ would still be able to calculate a consistent/efficient default chunksize using a formula like:
_num_workers = num_workers or config.get("num_workers", None) or CPU_COUNT
chunksize = len(args)//(nb_chunks or num_workers)_
Do you think these make sense?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @SebastienDorgan. How does what your proposing differ from the existing `chunksize = -1` case?

https://github.com/dask/dask/blob/8e5b3f0abd07ec634c29d5e8c665884b35882a24/dask/local.py#L452-L454

Also cc @jakirkham, who recently went through this portion of the codebase, for visibility

**Comment by dorgan-csgroup** [comment]
Indeed I missed this part of the code! Thanks for your quick answer

**Comment by SebastienDorgan** [comment]
Indeed I missed this part of the code! Thanks for your quick answer

**Comment by jakirkham** [comment]
Also this line seems relevant to the question

https://github.com/dask/dask/blob/80a82008d5b02a08f6ff59d802defcc43247eb1a/dask/multiprocessing.py#L180

**Comment by jrbourbeau** [comment]
Closing as I think the original question has been answered. Let us know if that's not the case @SebastienDorgan
