### ISSUE TITLE
`map_partitions` doesn't broadcast single-partition DataFrames

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#8338]
In trying to implement https://github.com/dask/dask/issues/8306 — specifically converting `single_partition_join` to blockwise — I realized that `map_partitions` repartitions single-element inputs to align with multi-partition inputs. I'm not sure if this is intended or desired.

The obvious thing to do for `single_partition_join` is something like:
```python
joined = multi_partition.map_partitions(merge_chunk, single_partition, **kwargs)
```
hoping that `single_partition` would be broadcast to every partition in `multi_partition`. This would match with the behavior of `Array.map_blocks` (single-chunk inputs are broadcast to every chunk).

The code in question is `_maybe_align_partitions`, which first does this `is_broadcastable` check against the inputs: https://github.com/dask/dask/blob/7960b6e04522ca67c2858ed428b910d2b27d0b1c/dask/dataframe/multi.py#L155-L170

But `is_broadcastable` isn't as generic as it sounds—it's specifically a check for single-row Series, to support `df - df.mean()`: https://github.com/dask/dask/blob/7960b6e04522ca67c2858ed428b910d2b27d0b1c/dask/dataframe/core.py#L5330-L5343

This was added 5 years ago in https://github.com/dask/dask/pull/2085 and hasn't changed since.

I'm wondering what the right behavior should be. On one hand, splitting single-partition inputs to align them as we do now means behavior is consistent with multi-partition inputs. OTOH, this is inconsistent with the corollary function from Array (`map_blocks`), and inconsistent with the Blockwise concept in general.

Personally, I think broadcasting single-partition DataFrames is both less surprising, and a more powerful API. It's just particularly annoying that there's no way around this right now. But, I'm not sure how much existing `map_partitions` code is relying on the current behavior.

If we don't want to change behavior, I think we should at least add `align_inputs=True` as a `map_partitions` kwarg (just like `align_arrays` in `map_blocks`) so you can work around this when necessary.

cc @jcrist @ian-r-rose @rjzamora @jrbourbeau

**Comment by jsignell** [comment]
I agree that the default behavior can be surprising. I started down a similar path to what you are outlining here: https://github.com/dask/dask/pull/6628/files

**Comment by gjoseph92** [comment]
I did just realize that, for a really hacky workaround, a single-partition DataFrame passed as a kwarg should be broadcast due to https://github.com/dask/dask/issues/8308.

**Comment by jsignell** [comment]
I'm going to close this since I just merged https://github.com/dask/dask/pull/6628
