### ISSUE TITLE
Promote setup documentation in Docs TOC

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#8348]
I suspect that the deploy page, https://docs.dask.org/en/latest/how-to/deploy-dask-clusters.html#, is of high enough importance that it should maybe get a top-level listing on the sidebar TOC.  Right now it's in the "How to" section at the same level as "How to set up prometheus", which seems less relevant.

**Comment by jsignell** [comment]
Fair enough. @jacobtomlinson and I are going to have some more docs time next week so we will make a plan of how dask and distributed docs should relate then.

**Comment by mrocklin** [comment]
Checking in here.  From my perspective there should maybe be a "Deploy" or "Set up" top level entry that points to https://docs.dask.org/en/stable/how-to/deploy-dask-clusters.html

**Comment by jacobtomlinson** [comment]
Yeah that's in the works.
