### ISSUE TITLE
dask memory issue, isn't it supposed to handle larger than memory computation?

### ISSUE THREAD

**Issue by enthusiastics** [dask/dask#8378]
I have a data folder, 200 parquet files total 600GB Disk. I understand that after fully loaded to memory it would be about 4TB. So I will use dask to perform out of core computation. I assume it would compute and output partitions by partitions to make everything manageable. 

    parquet_files_list = glob.glob(f"{Centralized_location2}{dump_signature2}dd_x_n_y{special_str1}/part*.parquet")
    agg_now = 3600
    parquet_files_list = sorted(parquet_files_list)[:]
    dd_x_n_y_orig = dd.read_parquet(parquet_files_list)
    dd_x_n_y_orig_tmp = dd_x_n_y_orig.copy()
    dd_x_n_y_orig_tmp.index = dd_x_n_y_orig_tmp.index.astype(int)//int(1e9)//agg_now*agg_now*int(1e9)
    dd_x_n_y_orig_tmp.index = ddf_int_to_datetime_1ns(dd_x_n_y_orig_tmp.index)
    gb_tmp = dd_x_n_y_orig_tmp.groupby(["timestamp","symbol"]).first()
    gb_tmp = gb_tmp.reset_index().set_index("timestamp",sorted=True,divisions=(dd_x_n_y_orig_tmp.divisions[0],dd_x_n_y_orig_tmp.divisions[-1]))
    gb_tmp = gb_tmp.repartition(partition_size="100M")
    gb_tmp = gb_tmp.drop("dir0",axis=1)
    str_for_this_agg = f"{dump_signature2}dd_x_n_y{special_str1}_{agg_now:08}"
    dict_agg_to_load_str[agg_now] = str_for_this_agg
    save_parquet_centralized2_datasetfolder(gb_tmp,str_for_this_agg)

The dataframe structure looks like this:

    dd_x_n_y_orig[dd_x_n_y_orig.columns[:5]]
    Dask DataFrame Structure:
    	symbol 	close_end 	volume_sum_1qd 	volume_sum_1h 	volume_sum_15min
    npartitions=783 					
    2018-03-01 00:00:00 	object 	float32 	float32 	float32 	float32
    2018-03-06 23:29:00 	... 	... 	... 	... 	...
    ... 	... 	... 	... 	... 	...
    2021-11-08 08:28:00 	... 	... 	... 	... 	...
    2021-11-08 21:35:00 	... 	... 	... 	... 	...
    Dask Name: getitem, 1566 tasks
My dataset is index by timestamp. my key operations is doing some kind of aggregate on `gb_tmp = dd_x_n_y_orig_tmp.groupby(["timestamp","symbol"]).first()` . However, even with my machine with 752GB memory. It still got memory error... What shall i do in this case? I am now thinking some kind of manual chunk by chunk loading... and saving chunk by chunk... isn't dask supposed to do this in the background?

    KilledWorker: ("('dataframe-groupby-first-combine-b7690c8dbb0634432e127c8153bdcc0e', 3, 0, 0)", <WorkerState 'tcp://172.31.9.233:44651', name: 7, memory: 0, processing: 1>)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @enthusiastics. There are lots of steps in your example, are you able to provide a minimal reproducer (see https://blog.dask.org/2018/02/28/minimal-bug-reports for more details)? Otherwise it may be difficult for others to help debug.

Can you post worker logs? That's often a good place to start looking when a `KilledWorker` exception is encountered. Additionally, you may find this documentation page http://distributed.dask.org/en/stable/killed.html, specifically the portion on `KilledWorker`, useful.

**Comment by ian-r-rose** [comment]
Closing due to lack of response. Since this seems like a usage question, I'd encourage you to reopen your question on the [Dask Discourse](https://dask.discourse.group/) page if you'd like to continue the discussion @enthusiastics.
