### ISSUE TITLE
Missing conda yml file

### ISSUE THREAD

**Issue by marcelned** [dask/dask#8381]
The file `continuous_integration/environment-latest.yaml` can't be found when trying to replicate https://docs.dask.org/en/stable/develop.html.

**Comment by jrbourbeau** [comment]
Thanks for opening this issue @marcelned. That environment file was recently removed in https://github.com/dask/dask/pull/8275. We're now recommending using `continuous_integration/environment-3.9.yaml` (as can be seen in the dev version of the documentation https://docs.dask.org/en/latest/develop.html#install)
