### ISSUE TITLE
QST: task count for getting one partition

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#8382]
**What happened**:

Created a dask.dataframe of multiple partitions. Got a single partition and saw the number of tasks is the same as the number of partitions or larger.

**What you expected to happen**:

When getting a partition from a dask.dataframe wouldn't the task count be 1? In the example below it shows 10. I may be mistaken here e.g. the number of tasks stays the same as the total number of partitions because the metadata/dataframe has to be scanned to find where the partition is located? I know it runs very fast as having a large file in remote storage (say 1,000 partitions i.e. read parquet says 1000 tasks) and getting one partition is fast.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

ddf = dd.demo.make_timeseries(
    start="2000-01-01",
    end="2000-01-10",
    dtypes={"x": float, "y": float, "id": int},
    freq="1min",
    partition_freq="24h",
) # 9 tasks
ddf.to_parquet("tmp.parquet")

ddf = dd.read_parquet("tmp.parquet")
ddf.get_partition(0)
```
![Screen Shot 2021-11-15 at 4 53 21 PM](https://user-images.githubusercontent.com/17162724/141859072-5a08e41b-2bec-4bdc-ae6f-9d381135a207.png)
`

`ddf.get_partition(0).visualize()`

![Screen Shot 2021-11-15 at 4 56 26 PM](https://user-images.githubusercontent.com/17162724/141859464-ec8a5161-6794-4c05-a994-caa429497bb7.png)

**Comment by dcherian** [comment]
You have to cull the graph to get what you want; like passing `optimize_graph=True` to `visualize`

I wrote this function to do what you want (but with xarray things wrapping dask arrays) though I think there are still a few bugs. IT would be nice if dask provided a robust version of this functionality for dask collections
``` python
def visualize_one_block(dataset, **kwargs):
    """
    Visualize one block of a Dataset or DataArray.
    """
    graph = None
    if isinstance(dataset, xr.DataArray):
        dataset = dataset._to_temp_dataset()

    keys = []
    block = get_one_block(dataset.unify_chunks())
    graph = block.__dask_graph__()

    for _, variable in block.variables.items():
        if isinstance(variable.data, dask.array.Array):
            key = (variable.data.name,) + (0,) * variable.ndim
            keys.append(key)

    if graph is None:
        raise ValueError("No dask variables!")
    return dask.visualize(graph.cull(set(keys)), **kwargs)

def get_one_block(dataset):
    if isinstance(dataset, xr.DataArray):
        array = dataset
        dataset = dataset._to_temp_dataset()
        to_array = True
    else:
        to_array = False
    chunk_slices = dict()
    for dim, chunks in dataset.chunks.items():
        start = 0
        chunk = chunks[0]
        stop = start + chunk
        chunk_slices[dim] = slice(start, stop)
    subset = dataset.isel(chunk_slices)
    if to_array:
        subset = array._from_temp_dataset(subset)
    return subset
```

**Comment by scharlottej13** [comment]
Hi @raybellwaves, does this help solve your problem?

**Comment by raybellwaves** [comment]
The simple solutions here seem to be

```
ddf.get_partition(0).visualize(optimize_graph=True)
```

```
ddf.get_partition(0).dask.visualize()
```
(https://github.com/dask/dask/issues/8443#issuecomment-986814308)

I think it's non-trivial to have it show two tasks from the start.

**Comment by ian-r-rose** [comment]
Closing as answered, but if you feel that is not the case, we can reopen to continue the discussion. Thanks all!
