### ISSUE TITLE
Add DataFrame.nunique()

### ISSUE THREAD

**Issue by scharlottej13** [dask/dask#8395]
Opening this as a new issue, as it came up in a recent [SO post](https://stackoverflow.com/questions/69928786/number-of-unique-values-in-dask-dataframe-columns) that @ian-r-rose and I worked on. It seems like it was mistakenly marked as added in issue #3817.

**Comment by fjetter** [comment]
@scharlottej13 can you please add a bit more information to the description? A sentence or two summarising the SO post and/or issue if that it relevant.
I think the SO post also mentions `groupby.nunique`. is this missing as well and part of this issue?

**Comment by scharlottej13** [comment]
This is to write the Dask version of [pandas.DataFrame.nunique](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). The linked SO post is one example of someone asking for this functionality. I don't think `groupby.nunique` is missing, I found the function [here](https://github.com/dask/dask/blob/main/dask/dataframe/groupby.py#L1940), so that's not part of this issue.

@fjetter Let me know if we need any other details!
