### ISSUE TITLE
Weird behavior during assertion

### ISSUE THREAD

**Issue by mesejo** [dask/dask#8408]
**What happened**:
```
s_2 = pd.Series(1, index=[*range(20, 0, -1)])
ds_2 = dd.from_pandas(s_2, npartitions=5)

# works
assert_eq(s_2.index.to_series(), ds_2.index.to_series())

# does not works
assert s_2.index.to_series() == ds_2.index.to_series().compute()
```

**What you expected to happen**:
The second assertion should pass, moreover, when doing:
```
ds_2.index.to_series().compute().tolist()
```
The output is:
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```
The reverse of the expected output.

**Anything else we need to know?**:
Detected this (possible) problem when working on [this](https://github.com/dask/dask/pull/8304)

**Environment**:

- Dask version: '2021.03.0'
- Python version: Python 3.8
- Operating System: Ubuntu 20.04.3 LTS 
- Install method (conda, pip, source): source

**Comment by jsignell** [comment]
This is expected. Dask sorts the index on set, so the data ends up flipped, but each index value points to the same data value. That is one of the reasons why we have helpers like `assert_eq` which makes sure that the indexes are alligned before checking the values.
