### ISSUE TITLE
Update install instructions for dask-dev enviornment

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#8409]
The [Development environment Install section](https://docs.dask.org/en/stable/develop.html#install) of the docs says 
```
conda env create -n dask-dev -f continuous_integration/environment-latest.yaml
conda activate dask-dev
python -m pip install --no-deps -e .
```
But we got rid of `environment-latest.yaml` on https://github.com/dask/dask/commit/5bc14dc7b62f129622c3f11fbe7119c13836de26

We should now point to use `environment-3.9.yaml` unless we recommend something different. 
The file to modify is: https://github.com/dask/dask/blob/main/docs/source/develop.rst

cc: @jsignell @scharlottej13

**Comment by jsignell** [comment]
Is the docs build failing? This should have been updated when the release went in.

**Comment by jsignell** [comment]
I'm taking a look at readthedocs

**Comment by ncclementi** [comment]
I noticed that when I googled for dask docs, it return `stable` instead of `latest`. If I change it to `latest` now I the docs are updated. Should this change be on `stable` or not yet?

**Comment by jsignell** [comment]
It should be on stable. There was an error on the build. I am retrying

**Comment by jsignell** [comment]
Rebuild worked, but we need to rethink our release process to get the stable build to complete properly. It looks like the build got messed up because when it tried to install distributed, that referenced dask 2021.11.2 and that wasn't yet available.

**Comment by jsignell** [comment]
I'm going to close this, but ping @jrbourbeau so that he's aware of the issue with the release process.

**Comment by jrbourbeau** [comment]
Yeah, I've been manually retriggering RTD builds when releasing but forgot to this time. Agreed it would be good to avoid the need for manual steps here

**Comment by jsignell** [comment]
oh yikes, yeah maybe we can come up with something.
