### ISSUE TITLE
Cannot catch and reraise exception with context on .compute()

### ISSUE THREAD

**Issue by jborman-exos** [dask/dask#8429]
**What happened**:

I cannot catch and reraise an exception with context while operating on a dask dataframe. The desired context in this case is the column name that could not be parsed.

In my own use case I am applying a number of parsing functions across the columns in my dataframe. Occasionally a parser will fail and I would like to know which column failed to identify the associated column/function needing attention. Wrapping my parsers with a try-catch to reraise an exception with the desired context does not work.

**What you expected to happen**:

I expect the `dask_parser()` to behave like `pd_parser()` where the `IntCastingNaNError` is caught and re-raised with the additional context indicating the column name. 

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import numpy as np
import pandas as pd

df = pd.DataFrame({'int_col': [None, 1, 2, 3]})
ddf = dd.from_pandas(df, npartitions=1)

def pd_parser(srs):
    try:
        return pd.to_numeric(srs).astype(np.int64)
    except Exception as e:
        raise ValueError(f'Could not parse {srs.name}') from e

def dask_parser(srs):
    try:
        return dd.to_numeric(srs).astype(np.int64)
    except Exception as e:
        raise ValueError(f'Could not parse {srs.name}') from e
```

```python
for col in df.columns:
    try:
        df[col] = pd_parser(df[col])
    except ValueError as e:
        print('Caught pandas parse failure:', e)
```

> Caught pandas parse failure: Could not parse int_col

```python
for col in ddf.columns:
    try:
        ddf[col] = dask_parser(ddf[col])
        ddf.compute()
    except ValueError as e:
        print('Caught dask parse failure:', e)
```

> Caught dask parse failure: Cannot convert non-finite values (NA or inf) to integer

**Anything else we need to know?**:

It makes sense that the column assignment `ddf[col] = dask_parser(ddf[col])` registers a delayed computation that is processed when `.compute()` is called, but the fact that `dask_parser()`'s try-catch wrapper gets skipped seems like an issue.

**Environment**:

- Dask version: 2021.11.2
- Python version: 3.9.4
- Operating System: Windows 10/WSL
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for raising this issue and including a reproducible example. The issue is that `dd.to_numeric(srs).astype(np.int64)` does not raise an error for dask. Not until you call compute. So the try catch that you are putting in the `dask_parser` will never be hit. 

To get the behavior that you are after, you'd have to write a custom function and then map that to each partition of the dataframe. This would look like:

```python

def dask_parser(df):
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col]).astype(np.int64)
        except Exception as e:
            print(f'Could not parse {col}', e)
    return df

ddf.map_partitions(dask_parser).compute()
