### ISSUE TITLE
Avro - s3 byte range for just schema or row count

### ISSUE THREAD

**Issue by tooptoop4** [dask/dask#8438]
boto3 library has s3 get_object that accepts a byte range (to avoid downloading a whole file but just download selected byte range). if my Avro file is 100mb, can this disk library do some byte range seek to only download the s3 object partially (ie the parts that contain header.schema metadata and row count)?

https://docs.dask.org/en/latest/_modules/dask/bag/avro.html seemed to have something about seeking ranges

**Comment by scharlottej13** [comment]
Hi @tooptoop4, thanks for opening this issue! It seems like this question is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse.
