### ISSUE TITLE
dask dataframe read_parquet split_row_groups docs outadated?

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#8446]
The current [documentation](https://docs.dask.org/en/latest/generated/dask.dataframe.read_parquet.html#dask-dataframe-read-parquet) regarding `split_row_groups` in dask dataframe `read_parquet` says " Only the “pyarrow” engine supports this argument." however when running these tests [`dask/dataframe/io/tests/test_parquet.py::test_split_row_groups`](https://github.com/dask/dask/blob/7446308083e2f284229a11e9b3e330aa9e73cf96/dask/dataframe/io/tests/test_parquet.py#L2558-L2596) you’ll see that `fastparquet` , `pyarrow-dataset`, and `pyarrow-legacy` engines will be used (if installed) and the tests pass for all the cases. 

Does this mean that the docs are outdated?

@dask/io

**Comment by ian-r-rose** [comment]
This looks right to me @ncclementi. @martindurant can you comment on fastparquet's support for `split_row_groups`?

**Comment by martindurant** [comment]
split_row_groups is handled by dask and works as expected, I believe - following @rjzamora 's work.

**Comment by ncclementi** [comment]
Then if things work as expected, the last line of these docs should be removed. 
https://github.com/dask/dask/blob/ec6b5267fb381e8f55f3319c1b33078849307a66/dask/dataframe/io/parquet/core.py#L193-L200

I created a PR for this, linked above.
