### ISSUE TITLE
Chunks/dtype not considered with map_blocks result name

### ISSUE THREAD

**Issue by djhoese** [dask/dask#8450]
**What happened**:

As part of a really long multi-day debug session I've finally figured out the root of my problem. I replaced some old code with a single no-dependency map_blocks function and started to run into some issues when the result was included a larger application that involved rechunking. I've discovered that the main issue is that the `chunks` keyword argument isn't considered in the tokenized name so you can produce two different arrays that result in the same name. This isn't a big problem at first glance as you can do `.compute()` and get the final array you expect, but it is a problem when these arrays start getting used in other tasks that may or may not include chunking. In my use case I ran into cases where if I computed two arrays that were dependent on these similar map_blocks results the scheduler would choose one or the other depending on the order that they were passed to `da.compute(`.

**What you expected to happen**:

Either:

1. Documentation in the `map_blocks` docstring about needing inputs to make the name unique including chunks and dtype. Or how to generate a name "manually" that will include this information as well as the args, kwargs, and function name.
2. Include `chunks` (and maybe other meta information) in the `name` generation for the output.

This would be similar to how you can call `da.zeros` multiple times with the same shape but different chunk size and get arrays with different names.

**Minimal Complete Verifiable Example**:

```python

def test_func(fake_in, block_info=None):
    return np.zeros(block_info[None]['chunk-shape'])

fake_input = 1
res1 = da.map_blocks(test_func, fake_input, chunks=((2,), (3, 3, 2, 1, 1), (2, 2, 2, 1, 1, 1, 1)), meta=np.array((), dtype=np.float64), dtype=np.float64)
res2 = da.map_blocks(test_func, fake_input, chunks=((2,), (6, 2, 2), (6, 4)), meta=np.array((), dtype=np.float64), dtype=np.float64)

res1.name
# 'test_func-7ea2153c7f07c8abd6f3181bc0975958'

res2.name
# 'test_func-7ea2153c7f07c8abd6f3181bc0975958'

## Looks like dtype is the same way

res3 = da.map_blocks(test_func, fake_input, chunks=((2,), (3, 3, 2, 1, 1), (2, 2, 2, 1, 1, 1, 1)), meta=np.array((), dtype=np.float32), dtype=np.float32)

res3.name
# 'test_func-7ea2153c7f07c8abd6f3181bc0975958'

```

**Anything else we need to know?**:

This may be related to https://github.com/dask/dask/issues/6649.

**Environment**:

- Dask version: 2021.11.2 (but seen on multiple)
- Python version: 3.9
- Operating System: PopOS
- Install method (conda, pip, source): conda/conda-forge

**Comment by gjoseph92** [comment]
Looks `map_blocks` tokenization logic has remained unchanged since long, long ago when it was first added in https://github.com/dask/dask/pull/848: https://github.com/dask/dask/blob/a87672e949365075e19cd90b81ddb18f63e3178a/dask/array/core.py#L501

Back at that time, py2 was still a think, so `args` and `kwargs` contained all the arguments to `map_blocks` (including `chunks`).

But these days, `args` and `kwargs` are just the arguments to the function!

@djhoese can you try
```diff
diff --git a/dask/array/core.py b/dask/array/core.py
index 150184f7..4eb03e98 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -675,7 +675,7 @@ def map_blocks(
         warnings.warn("The token= keyword to map_blocks has been moved to name=")
         name = token
 
-    name = f"{name or funcname(func)}-{tokenize(func, *args, **kwargs)}"
+    name = f"{name or funcname(func)}-{tokenize(func, dtype, chunks, drop_axis, new_axis, *args, **kwargs)}"
     new_axes = {}
 
     if isinstance(drop_axis, Number):
```

**Comment by djhoese** [comment]
That works for my mini-example above with hacking my installed version of dask. If you need me to try my real world case let me know. Otherwise, this makes sense and seems like a simple fix.

**Comment by djhoese** [comment]
...and I just tested the real world case and that works too!

**Comment by gjoseph92** [comment]
@djhoese care to open a PR? If not I can get to it eventually.

**Comment by djhoese** [comment]
I will try to find time tonight.
