### ISSUE TITLE
DOC: note that compute does not optimize delayed objects 

### ISSUE THREAD

**Issue by twoertwein** [dask/dask#8454]
The doc-strings of the various `compute` functions state that the graph is optimized by default. Optimizations don't seem to be applied for delayed objects https://github.com/dask/dask/pull/6222. It would be great to update the doc-strings and maybe even add a brief example how to optimize delayed objects (that use some "advanced" features such as `bind` - not sure whether `dask.utils.ensure_dict` can handle that).

**Comment by gjoseph92** [comment]
For your reference @twoertwein, the distributed scheduler currently does not schedule un-fused chains of tasks correctly: https://github.com/dask/distributed/issues/5555, https://github.com/dask/distributed/issues/5223). And the `Delayed` class does not currently fuse chains of tasks (unlike other collection types). So there are really two ways to fix the specific problem you're seeing: fix the scheduling behavior, or add the `fuse` optimization to `Delayed`. Of course, one of those is quite a lot easier than the other :)

**Comment by twoertwein** [comment]
Thank you @jrbourbeau and @gjoseph92!

Looking forward to #8448 being hopefully fixed :) Happy to close this issue in favor of #8448 (unless you prefer keeping this doc-only issue open as it might be easier to fix).

**Comment by jrbourbeau** [comment]
Np, let's close this issue in favor of the other one
