### ISSUE TITLE
Update Readme file 

### ISSUE THREAD

**Issue by Kareem-negm** [dask/dask#8463]
Hello Dask team,
I am a newbie in Dask, I am learning Dask these days and want to start contributing with you team 
so I want to start with the small contribution 
the Readme file in this repository need more work wherefore I want to add some features into such as :
- Dask Logo 
- What is Dask
- some Code example 
- Contents, Quickstarts
- Installation
- References 
- Contribution Guide

these topics are important for the project 
please if this is an acceptable contribution let me know to start working on it 

Thanks

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @Kareem-negm. Historically we've opted for a more minimal README in order to avoid replicating information that's already in the Dask docs and can get out of sync over time. See https://github.com/dask/dask/issues/2230 and https://github.com/dask/dask/pull/2231 for previous conversations on this topic.

That said, I'm sure there are ways we can still improve our README, but wanted to point out that there are other factors to consider. @jsignell @jacobtomlinson have been thinking about the Dask docs recently -- I wonder if they have thoughts on how the README might tie into some of the other work going on.

**Comment by Kareem-negm** [comment]
Hello @jrbourbeau , Thanks  a lot for your quick respond 
I understand now why you do not make a README file to avoid replicating information in Docs but I think it will be better if we made a suitable README that can show for the reader what is Dask and not replicate information 
I can work on a suitable README if you allow me to do that shown "what is the Dask is!! "
So that Mr.@jsignell and @jacobtomlinson will tell me about the points that I should take into consideration

**Comment by jacobtomlinson** [comment]
I'm in two minds about this.

- One option would be to add some more descriptive content to the README that should be fairly evergreen. Like the content on dask.org. Then add common headers to the README like `installation`, `contributing`, etc, but just include links to existing content in the docs.
- The other option is to leave things as it is. Keeping things minimal and just having one link out to the main website seems reasonable.

@jsignell what do you think?

**Comment by jsignell** [comment]
I kind of like the idea of putting more content on the README. I tend to agree with @jacobtomlinson that this content changes very infrequently and if we can improve discoverability of information at all that is a good thing. If we end up including `contributing` and `installation` sections we can always put a test to make sure that it stays exactly the same as that content in the docs.

**Comment by Kareem-negm** [comment]
@jrbourbeau ,  @jsignell and @jacobtomlinson, please  review if this is a good style and tell me your feedback

**Comment by scharlottej13** [comment]
@Kareem-negm welcome and thank you for opening up this issue! It looks like it has generated some good ongoing discussion here on the best way to move forward. Might be good to let this conversation play out a bit before spending too much time on writing a whole `readme`.

**Comment by Kareem-negm** [comment]
Hello @scharlottej13 , Ok 
I spent a little time writing a basic style for the README file that I think you will love it 
you can see it here : 
https://github.com/Kareem-negm/dask/tree/readme

This is a preliminary work that I did to get some modifications to the final visualization of the README structure 
I am not moving forward until you and the team guide me

**Comment by Kareem-negm** [comment]
Hello, Happy new year!
there are any updates?

**Comment by jrbourbeau** [comment]
Closing as we already closed the companion PR https://github.com/dask/dask/pull/8488
