### ISSUE TITLE
gpuCI build timeout

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8465]
In https://github.com/dask/dask/pull/8462 and https://github.com/dask/dask/pull/8464 the gpuCI build has failed with [the following logs](https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/896/CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=22.02/console):

```
14:31:36 96261ae979c7: Already exists

14:31:36 b2665af7cbba: Already exists

14:31:36 012b93d16d83: Already exists

14:31:36 1cb5f2c49e59: Already exists

14:31:36 bc62c68465b5: Already exists

14:31:36 65b1154c2a7d: Already exists

14:31:36 5a73e23d9d5b: Pulling fs layer

14:51:36 Build timed out (after 20 minutes). Marking the build as failed.

14:51:36 Build was aborted

14:51:36 Recording test results

14:51:36 [Checks API] No suitable checks publisher found.

14:51:36 Finished: FAILURE
```

cc @charlesbluca any idea what might be going on?

**Comment by charlesbluca** [comment]
I noticed these failures occasionally in dask-sql's gpuCI; my best guess is that some form of connectivity issue with Docker causes the job to hang on the image pull. In my experience, you unfortunately need to wait for the broken job to finish before trying to `rerun tests`, as the failing result of the first job will take precedence over any subsequent results.

I can check in with RAPIDS ops to see if this occurs with other projects running gpuCI and if there's a reasonable resolution for it.

**Comment by quasiben** [comment]
I restarted https://github.com/dask/dask/pull/8464 and things seem to be moving along again.  I suspect this was due to the rather severe AWS outage today

**Comment by jrbourbeau** [comment]
Thanks @quasiben. I'll keep and eye out for the next couple of days and if we don't encounter this timeout again, we can close this issue out 👍

**Comment by jrbourbeau** [comment]
Closing as I've not seen this pop up recently
