### ISSUE TITLE
nanmin & nanmax no longer work for scalar input

### ISSUE THREAD

**Issue by mathause** [dask/dask#8482]
**What happened**:

`dask.array.nanmin(np.int_(3)).compute()` returns `TypeError: len() of unsized object`. This still worked in v2021.11.2. Only `nanmin` and `nanmax` seem affected, `nansum` etc still work.

**What you expected to happen**:

No error.

**Minimal Complete Verifiable Example**:

```python
import dask.array
arr = dask.array.array([0, 1, 2])
dask.array.nanmin(arr[0]).compute()

# or
dask.array.nanmax(np.int_(3)).compute()

```

**Anything else we need to know?**:

xref: pydata/xarray#6016

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.9
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for reporting this. I can reproduce and it seems like this issue probably came in in https://github.com/dask/dask/pull/8375. I'll open a PR shortly to fix.

**Comment by mathause** [comment]
Thanks for the quick fix!
