### ISSUE TITLE
Add optimize_graph flag to Bag `to_dataframe` function

### ISSUE THREAD

**Issue by MaximLippeveld** [dask/dask#8485]
This functionality is necessary to avoid the loss of annotations during graph optimization. Consider the following snippet:
```
with dask.annotate(resources={"GPU": 1}):
    result = bag.map_partitions(func)

df = result.to_dataframe()
```
In some cases `func` will not be executed on a worker with at least 1 GPU resource, because the resource annotation is lost during the graph optimization that occurs in `to_dataframe`.

**Comment by scharlottej13** [comment]
Thanks @MaximLippeveld for opening this issue! Considering this flag already exists in [Dask Array](https://github.com/dask/dask/blob/0d4bdea8d5215270646c7b48413e4125f590166e/dask/array/core.py#L2667-L2687) and Dask DataFrame, it makes sense to also add it here. For context, the loss of annotations when converting a High Level Graph to a Low Level Graph is an [existing issue](https://github.com/dask/dask/issues/7036).
