### ISSUE TITLE
Different output for to_json(compute=False) and  to_json(compute=True) 

### ISSUE THREAD

**Issue by JavierYepez** [dask/dask#8495]
**What happened**:

I'm trying to save a dataframe with more than 1 partition to a json file. For this, I'm using an asynchronous client to compute the save later. The issue is that after waiting  the return is a list full of None objects.

**What you expected to happen**:

I expected to return the same as when using `to_json(df, path, compute=True)`

**Minimal Complete Verifiable Example**:

```python
async def save_to_json(data, path):
    client = Client.current(allow_global=False)
    files = to_json(data, path, compute=False)
    files = client.compute(files)
    return await asyncio.gather(*files)
```

**Anything else we need to know?**:

I think the issue comes from what's been returned in to_json() and that write_json_partition() doesn't return anything.

```python
parts = [
    delayed(write_json_partition)(d, outfile, kwargs)
    for outfile, d in zip(outfiles, df.to_delayed())
]
if compute:
    if compute_kwargs is None:
        compute_kwargs = dict()
    dask_compute(parts, **compute_kwargs)
    return [f.path for f in outfiles]
else:
    return parts #, [f.path for f in outfiles] This does the trick for now for me
```

I think this issue is also present in DataFrame.to_csv()

**Environment**:

- Dask version: 2021.11.2
- Python version: 3.8
- Operating System: macOS Monterey 12.1
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by jsignell** [comment]
Ah that's a good point. In case it's not clear, the operation is working (the data is being written to the file), it's just that the return isn't very informative. 

I have a super-minimal example that I was messing around with:

```python
import dask

ddf = dask.datasets.timeseries(freq="1H")
dask.compute(ddf.to_json("data.json", compute=False))
```

I think the solution is exactly what you are pointing to, but I think it's the return on `write_json_partition` that should be changed. I'll open a PR in a few minutes.
