### ISSUE TITLE
`from_dask_array` materializes the graph unnecessarily

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#8496]
`dask.dataframe.from_dask_array` has many instances of `ensure_dict` and low-level dict-merging, which is both inefficient and will prevent any optimizations from being applied to those layers (without https://github.com/dask/dask/issues/8447).

Convert `from_dask_array` to use and merge HighLevelGraphs properly. xref https://github.com/dask/dask/issues/8306

https://github.com/dask/dask/blob/27a7928fb750d604dfbad0b3f4361aa64a2c97b4/dask/dataframe/io/io.py#L444-L487

**Comment by scharlottej13** [comment]
@gjoseph92 would you be able to provide a little more detail on this in case a new contributor would like to pick it up?

**Comment by gjoseph92** [comment]
I would probably not recommend this for a new contributor. After reading through the current code, I think I would approach this by rewriting it with a different approach: rather than generating graphs, you can fully express this operation using the high-level Array and DataFrame APIs, then `da.map_blocks`/`da.blockwise`/`dd.map_partitions` (not sure which yet) to combine the array with the new index and convert it to a DataFrame.

But this will require a decent understanding of blockwise, which may not be documented well enough yet for someone to be able to pick up.
