### ISSUE TITLE
Nightly build failure

### ISSUE THREAD

**Issue by jsignell** [dask/dask#8504]
@charlesbluca @jakirkham it looks like the nightly build is not succeeding. Do we need to add a token somewhere?

 https://github.com/dask/dask/runs/4585485487?check_suite_focus=true

**Comment by charlesbluca** [comment]
Yes, we need to add a secret with the Anaconda token for the Dask channel:

https://github.com/dask/dask/pull/8469#discussion_r766130681

**Comment by jsignell** [comment]
Ok @jakirkham is that something that you can do?

**Comment by quasiben** [comment]
I added the `DASK_CONDA_TOKEN` -- I thought this was done already.  Things _should_ be working now

**Comment by jakirkham** [comment]
Apologies just got back from holiday

No this was not something I had done yet. Was waiting to see if there were any concerns with this proposal ( https://github.com/dask/dask/pull/8469#discussion_r766130681 )

However it sounds like we are ok with that approach and this has been resolved. Is that correct or are there remaining issues here?

**Comment by charlesbluca** [comment]
Yeah it seems like this is resolved, I see that nightly builds are now uploading:

- https://anaconda.org/dask/dask-core/files

We should be safe to close this

**Comment by jakirkham** [comment]
@jsignell if you see any remaining issues here, please let us know and we can revisit 🙂
