### ISSUE TITLE
[BUG] read_json doesn't respect to meta

### ISSUE THREAD

**Issue by henryliou-kklab** [dask/dask#8515]
**What happened**:
`read_json` doesn't respect to the typeing provided in `meta`

test.txt
```
{"label": "123"}
```
**What you expected to happen**:
`label` should be treated as a `string` field instead of `int`

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"label": ["123"]})
df.to_json("test.jsonl", orient="records", lines=True)

# works as expected
df_pd = pd.read_json("test.jsonl", orient="records", lines=True, dtype={"label": str})
print(df_pd.label)
# 0    123
# Name: label, dtype: object

df_dd = dd.read_json("test.jsonl", orient="records", lines=True, meta={"label": str})
df_dd.compute()

# ValueError: Metadata mismatch found in `from_delayed`.
#
# Partition type: `pandas.core.frame.DataFrame`
# +---------+-------+----------+
# | Column  | Found | Expected |
# +---------+-------+----------+
# | 'label' | int64 | object   |
# +---------+-------+----------+


# workaround
from functools import partial
engine = partial(pd.read_json, dtype={"label": str})
df_dd = dd.read_json("test.jsonl", orient='records', engine=engine)
print(df_dd.compute().label)
# 0    123
# Name: label, dtype: object

```

**Anything else we need to know?**:

**Environment**:

- Dask version: `dask-2021.12.0`
- Python version: `Python 3.8.12`
- Operating System: `MacOS Monterey` on `MacBook Pro 2018 (Intel)`
- Install method (conda, pip, source): `pyenv` + `poetry`

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by jsignell** [comment]
Thanks for writing this up! This is a really common misunderstanding so if you have any suggestions for how to make it clearer please open a pull request. 

So meta tells Dask what it should expect the object to look like. It does not tell Dask to coerce the data to match `meta` it just says, until you have the real data, this is kind of what it looks like. 
For your example you can just set dtype in addition to meta:

```python
df_dd = dd.read_json("test.jsonl", orient="records", lines=True, dtype={"label": str}, meta={"label": str})
```

**Comment by henryliou-kklab** [comment]
Thanks!
Work like a charm :)
