### ISSUE TITLE
ProgressBar `out` parameter issues

### ISSUE THREAD

**Issue by bluegeo** [dask/dask#8524]
The `out` parameter in `diagnostics.ProgressBar` is not documented. It appears it should be a file-like object, which means bytes should be written to it by default. The current implementation raises `TypeError: a bytes-like object is required, not 'str'`.

Example:
```python
from tempfile import TemporaryFile

import dask.array as da
from dask.diagnostics import ProgressBar


with TemporaryFile() as temp_file:
    with ProgressBar(out=temp_file):
        da.random.random((10, 10)).compute()
```

Tested using:

- Dask version: 2021.12.0
- Python version: 3.9.7
- Operating System: Mac OS X 12.1
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
The lack of documentation (and the name `_file`) certainly makes this hard to decipher, but going back to when this change was first introduced(https://github.com/dask/dask/pull/3185), it looks like the intention was just to allow the user to specify `stdout` or `stderr`. So I think that your original issue is not supported. Would you like to open a pull request to improve the documentation?

**Comment by ian-r-rose** [comment]
When I was looking at #8604, I noticed that the example here could be fixed by opening the file in text mode (`TemporaryFile` defaults to `"w+b"`):

```python
from tempfile import TemporaryFile

import dask.array as da
from dask.diagnostics import ProgressBar


with TemporaryFile("w") as temp_file:
    with ProgressBar(out=temp_file):
        da.random.random((10, 10)).compute()
```

So I think that arbitrary files actually *do* work here, they just need to accept string data.

**Comment by Lalitmohansharma1** [comment]
hello ,
i am new to dask , can you assign me this issue

thanks

**Comment by jsignell** [comment]
@Lalitmohansharma1, @ppsbs already has work started on this.
