### ISSUE TITLE
Blockwise optimization bug when collections appear multiple times

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask#8535]
Okay! This is a weird one, and I'm still investigating what is going on, so bear with me. I was working on #7417 and ran into some surprising behavior with blockwise optimization. It appears to happen (at least) when 
1. a collection with the same name is used more than once in a high level graph,
2. when there are at least two blockwise layers that might be combined, and
3. when there are multiple partitions.

A minimal example: the following succeeds

```python
import dask.array as da
import numpy as np

x = np.array([[1,1],[2,2]])
xx = da.from_array(x, chunks=1)  # create a multi-partition dask array

# Two blockwise operations in a row!
xx = xx * 2
z= da.matmul(xx,xx)

# optimize_graph=False turns off other optimizations, but I've manually verified
# that optimize_blockwise it the culprit
z.compute(optimize_graph=False) 

# produces the right answer
# [[12,12], [24,24]]
```

But if I turn on graph optimization (and `optimize_blockwise` does seem to be the important one), I get the wrong answer:

```python
import dask.array as da
import numpy as np

x = np.array([[1,1],[2,2]])
xx = da.from_array(x, chunks=1)  # create a multi-partition dask array

# Two blockwise operations in a row!
xx = xx * 2
z= da.matmul(xx,xx)

z.compute(optimize_graph=True) 

# produces the wrong answer
# [[8,8], [32,32]]
```

It does seem to be related to `xx` appearing twice. If I create a second array with a *different* name, but which is otherwise identical, the snippet succeeds. I'm a bit at a loss as to what might be happening right now, so this is a bit of an in-progress investigation that I'm putting out in case someone with fresher eyes has an idea. @gjoseph92 especially might be interested.

**Environment**:

- Dask version: `main`
- Python version: `3.93
- Operating System: ubuntu
- Install method (conda, pip, source): source

**Comment by rjzamora** [comment]
Hmm - Thanks for raising this. I can certainly reproduce

>It does seem to be related to xx appearing twice. If I create a second array with a different name, but which is otherwise identical, the snippet succeeds.

When you say a different name, do you mean that you modify `xx._name`? I still get the error when a distinct variable name is used (because the collection name is still the same):

```
xx = da.from_array(np.array([[1,1],[2,2]]), chunks=1)
yy = da.from_array(np.array([[1,1],[2,2]]), chunks=1)
assert xx._name == yy._name  # True
```

**Comment by ian-r-rose** [comment]
> When you say a different name, do you mean that you modify `xx._name`? I still get the error when a distinct variable name used (because the collection name is still the same):

Exactly -- I don't need to modify the name manually, I can pass it in as a kwarg, but if I give them different names as opposed to the deterministic tokenization, I get the right answer again:


```python
xx = da.from_array(np.array([[1,1],[2,2]]), name="xx", chunks=1)
yy = da.from_array(np.array([[1,1],[2,2]]), name="yy", chunks=1)
```

**Comment by ian-r-rose** [comment]
Also, thanks for taking a look @rjzamora

**Comment by rjzamora** [comment]
This indeed seems to be a logic bug in optimize_blockwise. It looks like the matmul layer (`Blockwise<(('mul-bd4187c86bf5b3023c3b8ab1f2397129', ('.0', '.1')), ('mul-bd4187c86bf5b3023c3b8ab1f2397129', ('.1', '.2'))) -> matmul-3e94acba0bdfaf326a7220437b4448e8>`) originally targets two distinct `indices`, but these distinct indices become a single result in the fused graph... still need to figure out how to fix it.

**Comment by rjzamora** [comment]
I submitted a possible fix in #8542.  However, I still feel a bit confused by this one, so I welcome feedback (and/or other suggestions) :)

**Comment by ian-r-rose** [comment]
Thanks @rjzamora! I'll take a look today

**Comment by ian-r-rose** [comment]
I would think it's actually pretty important to get a fix for this in `main`, even if it's imperfect. Silently getting the wrong value for matrix multiplication in some cases is a fairly big deal
