### ISSUE TITLE
dask apply loses index type with simple meta

### ISSUE THREAD

**Issue by JoranDox** [dask/dask#8537]
**What happened**:
When trying to *apply* a function to a dataframe, and giving a simple meta, the perceived dtype of the index of the return value is lost. Also the name of the index is lost (harder to show in this minimal example, but pretty similar I assume).
In the bigger picture this gives issues with ddf.merge where it expects the index column "[0]" to exist but instead finds "nameofcolumn".

**What you expected to happen**:
The perceived dtype of the index of the return value is the same as the dtype of the index of return value when computed.

**Minimal Complete Verifiable Example**:

![image](https://user-images.githubusercontent.com/7152733/148384994-daefd5a8-7faf-4a68-a0a5-0960b9a2d0a2.png)

```python
import dask.dataframe as dd
from dask.datasets import timeseries
ddf = timeseries()
ddf.index.dtype                        # shows dtype('<M8[ns]')
editedx = ddf.x.apply(lambda x: x + 1, meta=ddf.x.dtype) # some simple example, giving a simple meta argument
editedx.head()
editedx.index.dtype                  # incorrectly shows dtype('int64'), the default
editedx.index.compute().dtype # correctly shows dtype('<M8[ns]'), as was the dtype of the initial data

```

**Anything else we need to know?**:
It works in this case when we leave the meta out, but in some cases the autodeduction that happens is wrong and we need to provide a specific (if sometimes simple) meta to fix this).

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.9.7
- Operating System: linux (jupyterhub docker on k8s)
- Install method (conda, pip, source): (installed with the base jupyterhub image from above, source I guess? pip freeze shows dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1639176667673/work)

**Comment by JoranDox** [comment]
Kind-of workaround: provide this as meta:
```python
dask.dataframe.utils.make_meta(ddf).x
```
or, if you need to change a column's type:
```python
dask.dataframe.utils.make_meta(ddf).x.astype("int")
```
or if you need to add a new column:
```python
dask.dataframe.utils.make_meta(ddf).rename({"x":"something"},axis=1)["something"].astype(int)
```
making 
```python
editedx = ddf.x.apply(lambda x: x + 1, meta=ddf.x.dtype)
```
into
```python
editedx = ddf.x.apply(lambda x: x + 1, meta=dask.dataframe.utils.make_meta(ddf).rename({"x":"editedx"},axis=1)["editedx"].astype(int))
```
in the worst case.

**Comment by jsignell** [comment]
Yeah I take that whole lecture back. You just need to pass a tuple instead of a plain dtype. That way dask knows to expect a series. If you look at the warning when you don't provide a `meta=` you'll see that is actually what it recommends:

```python
editedx = ddf.x.apply(lambda x: x + 1, meta=("x", ddf.x.dtype))
```

**Comment by jsignell** [comment]
I think that in the case that you originally tried dask should throw an error.

**Comment by JoranDox** [comment]
> You just need to pass a tuple instead of a plain dtype.

Ooh good point, I totally missed that in the warning, thanks, that solves it for us! :+1:
Shall I leave this issue open until the pull request is finished? Or just close it already?

Also a big fan of a comprehensive blog post detailing the finer parts of meta :smile: 

Thanks!

**Comment by jsignell** [comment]
Nice! Let's leave this open and I'll just add a little test for the PR and it should be mergable. 

Feel free to comment on the blog post idea if you have any other questions or confusions! I'm going to get to it at some point :)
