### ISSUE TITLE
Add include_path_column to read_json

### ISSUE THREAD

**Issue by rfilmyer** [dask/dask#8539]
Similar to #6575, I ran into a situation where the `include_path_column` argument from `dd.read_csv` would have been very useful on `dd.read_json`.

**Comment by jsignell** [comment]
Hi @rfilmyer, thanks for opening this feature request. If you are interested in working on this, please feel free to open a Pull Request.

**Comment by jrbourbeau** [comment]
I think @bryanwweber mentioned he is planning on picking this issue up
