### ISSUE TITLE
Mutually inconsistent `x_chunk` and `axis` argument-values during `dask.array.reduction()`

### ISSUE THREAD

**Issue by ParticularMiner** [dask/dask#8541]
Hi all @dask

I continue to thank you guys for the wonderful program that `dask` is!

I'm not sure if the behavior described below is by design or an oversight.  But feel free to let me know what you think.

When "tree-reducing" a `dask` array `x` along multiple axes using 
```python
dask.array.reduction(x, chunk, aggregate, axis=axes, concatenate=concatenate, ...)
```
the values of the `x_chunk` and `axis` arguments passed to the callable `aggregate` when `concatenate=False` (or to the looked-up function `concatenate()` when `concatenate=True`) are in general not mutually consistent.  Here, the value of `x_chunk` is, in general, a nested list of lists of `chunk_type`-arrays.  The number of nesting levels of `x_chunk` reduces as each axis gets fully reduced, but the value of `axis` always remains the same.

This makes it difficult/impossible at each stage of recursion to determine within the callable `aggregate` or `concatenate()` which axes have already been fully reduced and those which are not yet fully reduced, and act accordingly.  And as a result, one could end up inadvertently reducing/concatenating along the wrong axis!  Thus I'm often forced to circumvent this issue by reducing one axis at a time using a for-loop for example:

```python
red_axes = (1, 2)
for axis in red_axes[::-1]:
   red = dask.array.reduction(red, chunk, aggregate, axis=axis, dtype=red.dtype, meta=meta)
```
since, by doing so, I'm always assured of a single nesting-level in each loop and there is no confusion.

There could be two ways to solve this problem permanently:
Either amend the source-code to
1.  at each stage of recursion, pass only those axes that have not yet been fully reduced into `aggregate` (or `concatenate()`) using the argument `axis`, or
2. fix the number of nesting levels of the list of lists `x_chunk` throughout the reduction procedure.  In this case, those axes that have already been fully reduced will have a corresponding nesting-level whose lists are of length 1.

I've already examined the source-code to determine the viability of both options above.  But before I go ahead and submit a PR, your thoughts would be much appreciated.  Thanks.

**Comment by ParticularMiner** [comment]
To illustrate the above issue, see the following example:

```python
import dask.array as da
import numpy as np
from threading import Lock
from more_itertools import collapse
from functools import reduce


print_lock = Lock()


def display(x_chunks, axis):
    x_chunks = [f'   {chunk}' if type(chunk) is list
                else f'   array({chunk})'
                for chunk in x_chunks]
    with print_lock:
        print()
        print(f'{axis=}\n'
              f'x_chunks = [')
        print(*x_chunks, sep=',\n', end='')
        print('\n]')


def chunk_func(x_chunks, axis, keepdims):
    display(x_chunks, axis)
    out = reduce(np.add, collapse(x_chunks, levels=1))
    if keepdims:
        return out
    else:
        return out[0][0]


a, b = 2, 4
x = da.from_array(np.arange(a*b).reshape(a, b), chunks=1)
x_0 = da.reduction(
    x,
    lambda x, axis, keepdims: x,
    chunk_func,
    concatenate=False,
    axis=(0, 1),
    dtype=x.dtype,
    meta=np.array([])
).compute()
```

The following is the output from the first stage of recursion during `reduction()` where we observe `x_chunks` is a list of lists (two-dimensional) as expected:
```python
axis=(0, 1)
x_chunks = [
   [array([[0]]), array([[1]])],
   [array([[4]]), array([[5]])]
]

axis=(0, 1)
x_chunks = [
   [array([[2]]), array([[3]])],
   [array([[6]]), array([[7]])]
]
```
Next is the output from the second stage of recursion where we observe `x_chunks` is just a list (one-dimensional) since one axis is already completely reduced but not the other.  But which one?
```python
axis=(0, 1)
x_chunks = [
   array([[10]]),
   array([[18]])
]
```
Well, obviously axis 0 was reduced first since it had only 2 blocks while axis 1 had 4 blocks.  But how can `chunk_func` determine this if axis is always `(0, 1)`?

**Comment by scharlottej13** [comment]
Thanks for this issue @ParticularMiner! @bryanwweber thanks for taking a look!

**Comment by bryanwweber** [comment]
Hi @ParticularMiner sorry, I haven't had a chance to look at this yet. Hope to this week!

**Comment by ParticularMiner** [comment]
Hi @bryanwweber, @scharlottej13 

Pls [follow this link](https://github.com/ParticularMiner/dask/pull/2#issue-1110345797) to see a fix in my `dask` fork in which I chose to fix the number of dimensions of the list of lists.  (This seemed to be the easiest and most backward-compatible option.)

There, the code above now gives at the 1st stage of recursion:
```python
axis=(0, 1)
x_chunks = [
   [array([[0]]), array([[1]])],
   [array([[4]]), array([[5]])]
]

axis=(0, 1)
x_chunks = [
   [array([[2]]), array([[3]])],
   [array([[6]]), array([[7]])]
]
```
and at the 2nd stage of recursion:
```python
axis=(0, 1)
x_chunks = [
   [array([[10]]), array([[18]])]
]
```

Fortunately, all CI tests there have also passed except for `parquet`-related tests in python 3.7.  I don't yet know if the errors raised by those failed tests are related to this issue or not.  If you find that they are, do let me know.  

And of course, if you feel this fix is worth merging upstream, let me know, and I'll proceed to submit a PR here.

**Comment by ParticularMiner** [comment]
@bryanwweber, @scharlottej13 

Moreover, exchanging the values of `a` and `b`:
```python
a, b = 4, 2
```
yields:
1st stage of recursion:
```python
axis=(0, 1)
x_chunks = [
   [array([[0]]), array([[1]])],
   [array([[2]]), array([[3]])]
]

axis=(0, 1)
x_chunks = [
   [array([[4]]), array([[5]])],
   [array([[6]]), array([[7]])]
]
```
2nd stage of recursion:
```python
axis=(0, 1)
x_chunks = [
   [array([[6]])],
   [array([[22]])]
]
```
which is what one would expect.
