### ISSUE TITLE
Document `dask.DataFrame.from_delayed` compatibility with `Future`s

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8568]
`dask.DataFrame.from_delayed` works when either an iterable of `Delayed` objects or an iterable of `Future`s are passed in as input. However, the docstring for `from_delayed`

https://github.com/dask/dask/blob/358a5e367eedc8f2963651071a72f43e0ac4f887/dask/dataframe/io/io.py#L573-L576

only mentions compatibly with `Delayed` objects. We should update the `from_delayed` docstring to also mentioned `Future`s can be used

**Comment by Kirito1397** [comment]
Hello,
I recently found out about Dask and would really like to make my contribution to this awesome project. I am a beginner and would like to take upon this issue.

**Comment by abergou** [comment]
Question: it appears that [dask.array.from_delayed](https://docs.dask.org/en/stable/generated/dask.array.from_delayed.html) also works with either a `Delayed` object or a `Future` (though unlike the data-frame verison not sequences of these objects). Is this also supported functionality?

**Comment by jsignell** [comment]
Yes @abergou I think delayed and futures are generally meant to be pretty interchangeable.
