### ISSUE TITLE
`@derived_from` decorator not copying docstring

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8584]
Earlier today I noticed that some methods which use our `derived_from` utility to copy docstrings over from some other method (e.g. `dask.dataframe.DataFrame.ffill` copies it's docstring from the corresponding pandas `ffill` method) 

https://github.com/dask/dask/blob/85bc7b5bb888c8a96eee3db07b260ca11d7cc130/dask/dataframe/core.py#L1443-L1445

isn't working 

```python
In [1]: import dask.dataframe as dd

In [2]: dd.DataFrame.ffill?
Signature: dd.DataFrame.ffill(self, axis=None, limit=None)
File:      ~/projects/dask/dask/dask/dataframe/core.py
Type:      function
```

while other methods, e.g. `dd.DataFrame.cummax`, are working as expected (i.e. the docstring is correctly copied over from pandas to Dask).

**Comment by shashiracherla** [comment]
Hi tried to solve it seems like `pandas.DataFrame.ffill.__doc__` is empty unlike cummax but somehow `help(pandas.DataFrame.ffill) `seems to work
