### ISSUE TITLE
Add `engine_kwargs` argument to `dask.dataframe.to_sql`

### ISSUE THREAD

**Issue by scharlottej13** [dask/dask#8596]
This question came up on the [Dask Discourse](https://dask.discourse.group/t/how-to-provide-ssl-details-in-the-ddf-to-sql-function/206). We were able to come up with a solution, but noticed the [`dask.dataframe.read_sql_table`](https://docs.dask.org/en/latest/generated/dask.dataframe.read_sql_table.html) accepts an `engine_kwargs` argument while [`dask.dataframe.to_sql`](https://docs.dask.org/en/latest/generated/dask.dataframe.to_sql.html) does not. Adding an `engine_kwargs` argument would be a nice feature that would make using `to_sql` less confusing.

**Comment by amirkdv** [comment]
@scharlottej13 I looked into this a bit and I think there are some design decisions to be made here.

[`dask.dataframe.to_sql`](https://docs.dask.org/en/latest/generated/dask.dataframe.to_sql.html) delegates db-facing logic to [`pandas.DataFrame.to_sql`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) through a `con` argument. This is expected to be a full sqlalchemy URI for the db connection, and is exposed by `dask.dataframe.to_sql` as an argument called `uri`.

If we were to expose `engine_kwargs` in `dask.dataframe.to_sql`, we'd have to make it behave consistently with the existing `uri` argument. To not break existing code `to_sql(..., uri=..., ...)` should keep working. But now we could make `uri` optional and expose a new `engine_kwargs` argument that creates a connection if `uri` is not provided.

Alternatively, to go back to the [motivating issue](https://github.com/coiled/dask-community/issues/186), I think SSL configuration _can_ be passed as the SQLAlchemy connection string (i.e. the already exposed `uri`). For example for [`Postgres`](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html?highlight=sslmode) the user could add `?sslmode=require` to the connection URI they're already providing to `dask.dataframe.to_sql`. A similar feature exists for [`MySQL`](https://docs.sqlalchemy.org/en/14/dialects/mysql.html#ssl-connections) but with different syntax.

p.s: first time dask contributor, let me know if I'm missing something here!

**Comment by scharlottej13** [comment]
Hi @amirkdv and welcome! Thanks for having a look at this issue. I think you bring up some great points about design consideration. Specifically:

> If we were to expose `engine_kwargs` in `dask.dataframe.to_sql`, we'd have to make it behave consistently with the existing `uri` argument. To not break existing code `to_sql(..., uri=..., ...)` should keep working. But now we could make `uri` optional and expose a new `engine_kwargs` argument that creates a connection if `uri` is not provided.

This is exactly what I was thinking-- to make `dask.dataframe.to_sql` more symmetrical to `dask.dataframe.read_sql_table`, for clarity. 

> Alternatively, to go back to the [motivating issue](https://github.com/coiled/dask-community/issues/186), I think SSL configuration _can_ be passed as the SQLAlchemy connection string (i.e. the already exposed `uri`). 

Yes! That was exactly what we suggested as a solution. This issue is more of a feature request than a bug issue, in that sense.

**Comment by amirkdv** [comment]
Thank you @scharlottej13! I hadn't looked at the actual Discourse page and had missed your similar comments re SSL, sorry about that.

I've opened a PR for this. The test case I used was a much simpler `echo=True` as an engine kwarg, the SSL use case turned out to be a bit more complicated, see PR for details.

**Comment by amirkdv** [comment]
Thanks @scharlottej13! I hadn't look at the original Discourse page and had missed your comments re SSL, sorry about that!

I've opened a PR for this. I used a simpler `echo=True` as the use case. The SSL use case turned out to be a bit more complicated, see PR for details.
