### ISSUE TITLE
ValueError of shape mismatch when assigning vector to a slice of matrix

### ISSUE THREAD

**Issue by KangchengHou** [dask/dask#8598]
**What happened**: ValueError of shape mismatch when assigning a column vector to a slice of matrix.

**What you expected to happen**: the assignment should work without error

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
mat1 = da.zeros((5, 2))
mat2 = da.random.normal(size=(5, 1))
mat1[:, 0::2] = mat2 # works okay
mat1[:, [1]] = mat2 # works okay
mat1[:, 1::2] = mat2 # ValueError
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.01.0
- Python version: 3.8.5
- Operating System: Mac OS X and Linux
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by davidhassell** [comment]
Hi, this is another index parsing bug (sorry!) - I can make a PR for this.
