### ISSUE TITLE
`Series.str` / `Series.dt` methods missing from Docs

### ISSUE THREAD

**Issue by quasiben** [dask/dask#8599]
Dask has many str accessor methods implemented but these are all missing from the documentation. For example, Dask supports `Series.str.capitalize` but it's missing in https://docs.dask.org/en/stable/dataframe-api.html.

xref: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.capitalize.html

**Comment by jrbourbeau** [comment]
Thanks for pointing that out @quasiben. In addition to the `Series.str` methods, Dask also supports `Series.dt` accessors like `Series.dt.hour` https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.hour.html which would also be nice to add to the Dask API docs
