### ISSUE TITLE
Add first and last aggregate functions to `dask.dataframe.pivot_table`

### ISSUE THREAD

**Issue by nordange** [dask/dask#8618]
This question/feature request started on the [Dask Discourse](https://dask.discourse.group/t/using-pivot-table-with-non-numerical-data/267/2).

Currently `dask.dataframe.pivot_table` only supports `mean`, `sum` and `count` as aggregate functions. This makes `pivot_table` inconvenient for working with non-numeric data. `first` and `last` are supported aggregate functions in Pandas' `pivot_table`.

Typical data would look like:
```
   ID Col_ID    value
0   1      A    Alice
1   1      B      Bob
2   1      A  Charlie
```
Desired output in case of `aggfunc='first'`
```
Col_ID      A    B
ID
1       Alice  Bob
```
Desired output in case of `aggfunc='last'`
```
Col_ID        A    B
ID
1       Charlie  Bob
```

Example code
```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"ID": [1, 1, 1], "Col_ID": ["A", "B", "A"], "value": ["Alice", "Bob", "Charlie"]})
df_pivot = df.pivot_table(index="ID", columns="Col_ID", values="value", aggfunc="first")

ddf = dd.from_pandas(df, npartitions=2)
# count is the only aggregate functions that could be useful for non-numeric data
ddf_pivot = ddf.categorize(columns=["Col_ID"]).pivot_table(
    index="ID", columns="Col_ID", values="value", aggfunc="count"
)

```

**Comment by jsignell** [comment]
Thanks for raising this issue @nordange! It seems like adding these aggregations to pivot_table would be relatively straightforward. It would just require changes here: 

https://github.com/dask/dask/blob/e44f78009d56332b0153828adb0eaf0e5d01582f/dask/dataframe/reshape.py#L186

and new `pivot_last` and `pivot_first` functions here:

https://github.com/dask/dask/blob/e44f78009d56332b0153828adb0eaf0e5d01582f/dask/dataframe/methods.py#L417

**Comment by nordange** [comment]
Great! I'll give it a go, @jsignell.
