### ISSUE TITLE
Better error message for unsupported Array reshape operations

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#8634]
`Array.reshape` "only allows for reshapings that collapse or merge dimensions" (xref https://github.com/dask/dask/issues/2561). However, when you try to do one of these unsupported reshapings, the error message `Shapes not compatible` does not make it at all clear that what you're asking for just isn't supported by dask. Instead, it sounds as though your inputs are invalid.

A more descriptive error message, possibly with a link to documentation like https://docs.dask.org/en/latest/array-chunks.html#reshaping, would help users understand what's going on. Also, this should maybe be a NotImplementedError.

```python
import dask.array as da

# NumPy works fine
In [25]: da.random.random((6, 2), chunks=(2, 2)).compute().reshape(3, 4)
Out[25]: 
array([[0.79357568, 0.05108054, 0.08983493, 0.197254  ],
       [0.40013843, 0.43548821, 0.99473879, 0.02848385],
       [0.82485068, 0.21818596, 0.65396113, 0.20300868]])

# Dask does not
In [26]: da.random.random((6, 2), chunks=(2, 2)).reshape(3, 4)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-2733f73e03ee> in <module>
----> 1 da.random.random((6, 2), chunks=(2, 2)).reshape(3, 4)

~/dev/dask/dask/array/core.py in reshape(self, merge_chunks, limit, *shape)
   2080         if len(shape) == 1 and not isinstance(shape[0], Number):
   2081             shape = shape[0]
-> 2082         return reshape(self, shape, merge_chunks=merge_chunks, limit=limit)
   2083 
   2084     def topk(self, k, axis=-1, split_every=None):

~/dev/dask/dask/array/reshape.py in reshape(x, shape, merge_chunks, limit)
    233         x = x.rechunk({i: 1 for i in range(din - dout)})
    234 
--> 235     inchunks, outchunks = reshape_rechunk(x.shape, shape, x.chunks)
    236     # Check output chunks are not too large
    237     max_chunksize_in_bytes = reduce(mul, [max(i) for i in outchunks]) * x.dtype.itemsize

~/dev/dask/dask/array/reshape.py in reshape_rechunk(inshape, outshape, inchunks)
     45                 ileft -= 1
     46             if reduce(mul, inshape[ileft : ii + 1]) != dout:
---> 47                 raise ValueError("Shapes not compatible")
     48 
     49             # Special case to avoid intermediate rechunking:

ValueError: Shapes not compatible
```

**Comment by Dhruv454000** [comment]
can i work on this issue?

**Comment by Dhruv454000** [comment]
@gjoseph92  so the message  should be simply "Not Implemented" right?

**Comment by gjoseph92** [comment]
The exception should be a `NotImplementedError`. Coming up with a good, descriptive error message that helps users is part of the task, though I could write one if you'd like.

Note that this also isn't as simple as changing the text in that one line of code. You need to read and understand the reshape code first to understand if this error is _also_ currently catching cases where you've actually passed in an invalid shape, as opposed to a shape which _could_ be valid, but dask just doesn't support right now. Then you'd also need to figure out how to differentiate between those cases.

**Comment by Dhruv454000** [comment]
ok i will work on it.

**Comment by Dhruv454000** [comment]
@gjoseph92 i have noticed that it works well and if we pass invalid shape it gives error message shape of new array must be unchanged which is correct. so i need to change message now right?

**Comment by pavithraes** [comment]
@Dhruv454000 Thanks for your interest in this! Would you be comfortable opening a PR where we can continue this discussion? It'll be easier for folks to share in-line feedback that way :)

**Comment by TristanBilot** [comment]
Is this issue solved or can I fix it as a first issue? :)

**Comment by kutal10** [comment]
Hi all - i've updated the error message as per #8905

**Comment by kutal10** [comment]
@ian-r-rose I've submitted a PR at #8905 but it only adjusts the message, and doesn't check for validity vs unsupported arrays which I need to implement + also add unit tests for
