### ISSUE TITLE
Dictionary outputs (dtype "object") being interpreted as strings

### ISSUE THREAD

**Issue by tgaddair** [dask/dask#8636]
**What happened**:

Attempted to perform a map-reduce style transformation on a series that outputs a single dictionary following the reduce. However, the dictionary from the map step is being interpreted as a string in the reducer.

**What you expected to happen**:

The dictionary output from the mapper should be passed as a dictionary to the reducer. This behavior is consistent with dask 2022.1.0

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame(columns=['a'], data=[[2], [4], [8]], index=[0, 1, 2])
ddf = dd.from_pandas(df, npartitions=2)

def map_fn(x):
    return {'x': x, 'y': x}

def reduce_fn(series):
    merged = None
    for mapped in series:
        if merged is None:
            merged = mapped.copy()
        else:
            merged['x'] += mapped['x']
            merged['y'] *= mapped['y']
    return merged
    
ddf['a']\
    .map(map_fn, meta=("data", "object"))\
    .reduction(reduce_fn, aggregate=reduce_fn, meta=("data", "object"))\
    .compute()[0]
```

Stack trace:

```
ValueError: Metadata inference failed in `_reduction_chunk`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'str' object has no attribute 'copy'")

Traceback:
---------
  File "/Users/tgaddair/.venv/ludwig/stable/lib/python3.7/site-packages/dask/dataframe/utils.py", line 175, in raise_on_meta_error
    yield
  File "/Users/tgaddair/.venv/ludwig/stable/lib/python3.7/site-packages/dask/dataframe/core.py", line 5975, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/Users/tgaddair/.venv/ludwig/stable/lib/python3.7/site-packages/dask/dataframe/core.py", line 7009, in _reduction_chunk
    o = aca_chunk(x, **kwargs)
  File "<ipython-input-6-e8d610e698cf>", line 9, in reduce_fn
    merged = mapped.copy()
```

**Anything else we need to know?**:

This was working with all prior versions of Dask we've used, so it appears to be a regression specific to 2022.1.1.

**Environment**:

- Dask version: 2022.1.1
- Python version: 3.7, 3.8, 3.9
- Operating System: ubuntu, macos
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thanks for opening this @tgaddair I suspect that it is related to https://github.com/dask/dask/pull/8468 in particular @rjzamora it looks like we might be inadvertently dropping the `meta` before the `map_partitions` call in `apply_concat_apply`.

**Comment by rjzamora** [comment]
Thanks for the ping @jsignell -  #8468 modified ACA to leverage `map_partitions` for both the initial chunkwise "map" phase, as well as the sharding (for aggregations with split_out>1).  This means there are many cases where the output of `map_partitions` will not be a proper DataFrame collection (because the result is not meant to be a "public" collection).

The ACA overhaul was orginally using explicit `Blockwise`-layer construction, but this was changed to `map_partitions` in order to simplify the code (pretty dramatically).  I will need to think a bit about this - We may need to drop the use of `map_partitions` here :/

**Comment by tgaddair** [comment]
Thanks for the fix @rjzamora!
