### ISSUE TITLE
Error "column not in index" when using read_parquet() on hive-partitioned parquet dataset

### ISSUE THREAD

**Issue by th0ger** [dask/dask#8650]
**What happened**:
The `dask.dataframe.read_parquet()` method fails with error `KeyError: "['col1'] not in index"` when trying to read a partitioned parquet dataset (in my example generated by ` pyarrow`).

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import pyarrow as pa
import pyarrow.dataset as ds
import dask.dataframe as dd

df = pd.DataFrame({
    'col1': [1, 2],
    'col2': ['a', 'b']
})

table = pa.Table.from_pandas(df)

ds.write_dataset(data=table,
                 base_dir='foo',
                 basename_template="prefix-{i}.parquet",
                 format="parquet",
                 partitioning=["col1"],
                 existing_data_behavior="delete_matching"
                 )

dd1 = dd.read_parquet(path='foo', engine="pyarrow")
print(dd1)
dd1.compute()
```

```text
Dask DataFrame Structure:
                col1    col2
npartitions=3               
               int64  object
                 ...     ...
                 ...     ...
                 ...     ...
Dask Name: read-parquet, 3 tasks
```
```text
KeyError                                  Traceback (most recent call last)
~/dask-issue.py in <module>
     22 dd1 = dd.read_parquet(path='foo', engine="pyarrow")
     23 print(dd1)
---> 24 dd1.compute()
...
~/.local/share/virtualenvs/.../lib/python3.8/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1314             if raise_missing:
   1315                 not_found = list(set(key) - set(ax))
-> 1316                 raise KeyError(f"{not_found} not in index")
   1317 
   1318             not_found = key[missing_mask]

KeyError: "['col1'] not in index"
```

**Anything else we need to know?**:
Please note that the lazy `print(dd1)` does include `col1`, it's only at `.compute()` we are failing.

I have previously experienced that `pyarrow` (without dask) needs the `partitioning` and `partition_base_dir` args to be set, in order to read the partition columns. Maybe this is the issue somewhere?
I have tested these `kwargs` without luck:

```python
dd1 = dd.read_parquet(path='foo', engine="pyarrow", 
    format="parquet", partitioning="hive", partition_base_dir="foo"
)
```

**Environment**:

- Dask version: 2022.1.1
- Pyarrow version: 6.0.1
- Python version: 3.8
- Operating System: Ubuntu 20.04.3 LTS 
- Install method (conda, pip, source): pipenv

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by bryanwweber** [comment]
Hi @th0ger thanks for reporting this! @pavithraes has volunteered to take a look 😄

**Comment by th0ger** [comment]
@pavithraes a bit closer to a workaround:

```python
dd.read_parquet(path='foo', engine="pyarrow",
                dataset={
                    "partitioning": "hive",
                    "partition_base_dir": "foo"
                  }
                ).compute()
```
```text
...
~/.local/share/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, ignore_metadata_file, metadata_task_size, split_row_groups, chunksize, aggregate_files, **kwargs)
    328         gather_statistics = True
    329 
--> 330     read_metadata_result = engine.read_metadata(
    331         fs,
    332         paths,

~/.local/share/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py in read_metadata(cls, fs, paths, categories, index, gather_statistics, filters, split_row_groups, chunksize, aggregate_files, ignore_metadata_file, metadata_task_size, **kwargs)
    369 
    370         # Stage 1: Collect general dataset information
--> 371         dataset_info = cls._collect_dataset_info(
    372             paths,
    373             fs,

~/.local/share/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py in _collect_dataset_info(cls, paths, fs, categories, index, gather_statistics, filters, split_row_groups, chunksize, aggregate_files, ignore_metadata_file, metadata_task_size, kwargs)
    911                 filesystem=fs,
    912                 format="parquet",
--> 913                 partitioning=partitioning["obj"].discover(
    914                     *partitioning.get("args", []),
    915                     **partitioning.get("kwargs", {}),

TypeError: string indices must be integers
```

The `partitioning="hive"` argument is valid pyarrow syntax that _should_ solve the issue (i belive pyarrow chnaged the behaviour, so you must provide this if the partion keys shall be returned.)

I also tested this syntax:

```python
from pyarrow.dataset import HivePartitioning
partitioning = HivePartitioning(pa.schema([("col1", pa.int16()), ("col2", pa.string())]))
dd.read_parquet(path='foo', engine="pyarrow",
                dataset={
                    "partitioning": partitioning,
                    "partition_base_dir": "foo"
                  }
                ).compute()
```
```text
...
~/.local/share/virtualenvs/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, ignore_metadata_file, metadata_task_size, split_row_groups, chunksize, aggregate_files, **kwargs)
    328         gather_statistics = True
    329 
--> 330     read_metadata_result = engine.read_metadata(
    331         fs,
    332         paths,

~/.local/share/virtualenvs/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py in read_metadata(cls, fs, paths, categories, index, gather_statistics, filters, split_row_groups, chunksize, aggregate_files, ignore_metadata_file, metadata_task_size, **kwargs)
    369 
    370         # Stage 1: Collect general dataset information
--> 371         dataset_info = cls._collect_dataset_info(
    372             paths,
    373             fs,

~/.local/share/virtualenvs/.../lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py in _collect_dataset_info(cls, paths, fs, categories, index, gather_statistics, filters, split_row_groups, chunksize, aggregate_files, ignore_metadata_file, metadata_task_size, kwargs)
    911                 filesystem=fs,
    912                 format="parquet",
--> 913                 partitioning=partitioning["obj"].discover(
    914                     *partitioning.get("args", []),
    915                     **partitioning.get("kwargs", {}),

TypeError: 'pyarrow._dataset.HivePartitioning' object is not subscriptable
```

**Comment by th0ger** [comment]
https://github.com/dask/dask/blob/b6713736533f98afda441e1d0319b7f5b45e53ad/dask/dataframe/io/parquet/arrow.py#L829-L838

**Comment by th0ger** [comment]
@bryanwweber @pavithraes could you kindly provide your comments on this?

**Comment by th0ger** [comment]
Hi @pavithraes and @scharlottej13, thank for looking into this.

First one regression from my end: I forgot to provide `partitioning_flavor="hive"` to `ds.write_dataset()`. This setting ensures that pyarrow names the partition folders as hive-style `/col1=<value>/` instead of just `/<value>/`. It seems to me that pyarrow does not write the `_metadata` and `_common_metadata` files that Dask does (at least by default). So without setting `partitioning_flavor="hive"`, the given name `"col1"` is never persisted, and theres no way that you could read `col1` in automatically.

We don't want to depend on using Dask solely for writing parquet, just to be able to use Dask to read it back. Dask must be able to read partitioned data written with pyarrow (or fastparquet etc.) - especially when we tell Dask to read it via the exact same pyarrow backend.

When it comes to the stability of the new pyarrow Dataset API, my impression is that it's getting quite stable. Also, let me remind you that Dask `engine="pyarrow"` now defaults to the new pyarrow Dataset API, so you already jumped in the water :-)
> engine : ... If 'pyarrow' or 'pyarrow-dataset' is
> specified, the ArrowDatasetEngine (which leverages the pyarrow.dataset
> API) will be used. If 'pyarrow-legacy' is specified, ArrowLegacyEngine
> will be used (which leverages the pyarrow.parquet.ParquetDataset API).
> NOTE: The 'pyarrow-legacy' option (ArrowLegacyEngine) is deprecated
> for pyarrow>=5.

Here is my updated test which shows that shows the interoperability between writing/reading with pyarrow/Dask:

```python
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
import dask.dataframe as dd

df = pd.DataFrame({
    'col1': [1, 2],
    'col2': ['a', 'b']
})

## Write with dask
ddf = dd.from_pandas(df, npartitions=2)
ddf.to_parquet(path='foo-dask', engine='pyarrow', partition_on=["col1"])
# ls foo-dask/ 
# _common_metadata   _metadata  'col1=1'  'col1=2'

## Write with pyarrow
table = pa.Table.from_pandas(df)
ds.write_dataset(data=table,
                 base_dir='foo-pyarrow',
                 basename_template="part.{i}.parquet",
                 format="parquet",
                 partitioning=["col1"],
                 partitioning_flavor="hive",  # Set hive partition style /col1=<val>/
                 existing_data_behavior="delete_matching"
                 )
# ls foo-pyarrow/
# 'col1=1'  'col1=2'

## Read with pyarrow (old API)
print(pq.read_table('foo-dask').to_pandas())
print(pq.read_table('foo-pyarrow').to_pandas())
#                                   col2 col1
# __null_dask_index__          
# 0                                 a    1
# 1                                 b    2
#
#       col2 col1
# 0    a    1
# 1    b    2

## Read with pyarrow (new API)
print(ds.dataset("foo-dask", format="parquet", partitioning="hive").to_table().to_pandas())
print(ds.dataset("foo-pyarrow", format="parquet", partitioning="hive").to_table().to_pandas())
# Same output as above.

## Read with dask
print(dd.read_parquet(path='foo-dask', engine="pyarrow").compute())
try:
    print(dd.read_parquet(path='foo-pyarrow', engine="pyarrow").compute())
except Exception as e:
    print(e)
#     col2 col1
# 0    a    1
# 1    b    2
#
# "['col1'] not in index"
```

I still belive this is caused by the way Dask implementes its calls to pyarrow. But maybe some pyarrow API/behaviour has changed and someone from their team can advice.

I tried the workaround:
```python
dd.read_parquet(path='foo-pyarrow', engine="pyarrow", dataset={"partitioning": "hive"})
```
but this returns `[TypeError: string indices must be integers]()`. It seems this is not allowed due to Dask `kwargs` handling, similar to the discussion in #8677.

**Comment by pavithraes** [comment]
@th0ger Thanks for sharing a nice minimal example, I was able to reproduce this. :)

I'm wondering if this might be a bug in Dask, maybe @jcrist or @rjzamora can help confirm?

Because it seems to work as expected using pandas' `read_parquet`: `pd.read_parquet(path='foo-pyarrow', engine="pyarrow")`. With this information, here's a non-ideal workaround using `Delayed`:

```python
from dask import delayed

delayed_df = delayed(pd.read_parquet)(path='foo-pyarrow', engine="pyarrow")

ddf = dd.from_delayed(delayed_df)

ddf.compute()
```

I also came across [this comment](https://github.com/dask/dask/issues/7512#issuecomment-852381361), which looks similar, but the [suggested work-around](https://github.com/dask/dask/issues/7512#issuecomment-889640208) doesn't seem to help in our example. :/

**Comment by rjzamora** [comment]
Thanks for the reporting this @th0ger - My understading is that dask is able to round-trip the partitioned dataset, but fails when the data was written directly by pyarrow (please do correct me if I am wrong). It is likely that this is a bug in Dask and I will be happy to help investigate.

Some other notes:
- The pyarrow-dataset engine was implemented before the pyarrow.dataset API had write support, so it is no suprise that this case is not tested in CI.
- The `pyarrow.dataset` API is listed as "experimental" by pyarrow, but they have also started deprecating the legacy API (so we can't really rely on pyarrow-legacy for stability here).  Since the two APIs are quite different, we recently decided [to deprecate](https://github.com/dask/dask/pull/8758) the "pyarrow-legacy" engine in Dask.  I am hoping this will allow us to simplify a lot of code and focus our efforts moving forward.
- As you already discovered, you cannot pass `dataset={"partitioning": "hive"}` to `read_parquet` yet. I don't think there is any reason for this ugliness in newer versions of dask/pyarrow, so #8765 will likely resolve that issue soon.

**Comment by th0ger** [comment]
Confirming the fix works on latest main branch.
