### ISSUE TITLE
Column mistmatch prevents append to partitioned parquet dataset with `engine=fastparquet`

### ISSUE THREAD

**Issue by erinov1** [dask/dask#8666]
I'm unable to append to an existing partitioned parquet dataset when using `engine=fastparquet`, although it works fine with `engine=pyarrow`.

MWE:

The second `to_parquet` call fails:
```
import pandas as pd
import dask.dataframe as dd
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [1, 1, 2, 2]})
df = dd.from_pandas(df, npartitions=1)

df.to_parquet(
    "dataset", 
    partition_on="B",
    engine="fastparquet",
    write_index=False,
)
df.to_parquet(
    "dataset", 
    partition_on="B",
    engine="fastparquet", 
    write_index=False,
    append=True # <----- append!
)
```
Tail of traceback:

```
File ~/Library/Caches/pypoetry/virtualenvs/project-GfuZs_x0-py3.8/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py:1089, in FastParquetEngine.initialize_write(cls, df, fs, path, append, partition_on, ignore_divisions, division_info, schema, object_encoding, index_cols, **kwargs)
   1083     raise ValueError(
   1084         "Requested file scheme is hive, but existing file scheme is not."
   1085     )
   1086 elif (set(pf.columns) != set(df.columns) - set(partition_on)) or (
   1087     set(partition_on) != set(pf.cats)
   1088 ):
-> 1089     raise ValueError(
   1090         "Appended columns not the same.\n"
   1091         "Previous: {} | New: {}".format(pf.columns, list(df.columns))
   1092     )
   1093 elif (pd.Series(pf.dtypes).loc[pf.columns] != df[pf.columns].dtypes).any():
   1094     raise ValueError(
   1095         "Appended dtypes differ.\n{}".format(
   1096             set(pf.dtypes.items()) ^ set(df.dtypes.iteritems())
   1097         )
   1098     )

ValueError: Appended columns not the same.
Previous: ['A'] | New: ['A', 'B']
```
There is some issue involving the column `B` used for partitioning. On the other hand, the same code works fine with `engine=pyarrow`.

**Environment**:

- Dask version: 2021.12.0
- Fastparquet version: 0.8.0
- Python version: 3.8
- Operating System: OSX

**Comment by jsignell** [comment]
Thanks for writing this up @erinov1 - ping @martindurant in case you have time to take a look.

**Comment by martindurant** [comment]
@yohplala , do you think a recent change might have done this?

**Comment by yohplala** [comment]
> set(partition_on) != set(pf.cats)

Hi @martindurant ,

1/
I have investigated a bit, and I cannot see any direct link with recently modified code.
The 'faulty' condition uses 2 `ParquetFile` attribute I made no change to: `pf.columns` and `pf.cats`.

2/
To get further, it would be worth to know exactly which condition is raising the trouble, is it:
- `(set(pf.columns) != set(df.columns) - set(partition_on))`
-  or `set(partition_on) != set(pf.cats)`
?
Some `print` statements to display `pf.columns`, `pf.cats` and `partition_on` would be interesting to understand.

3/
Besides, I can see the error message is 'wrong' and should be fixed (the assessed condition is correct however, we have a similar check in `api.py`, but not on ). So, may I raise the hypothesis that it has not been tested so far?
The 'correct' variable to use would be:
```python
# current code
   1090         "Appended columns not the same.\n"
   1091         "Previous: {} | New: {}".format(pf.columns, list(df.columns))

# corrected code (but incomplete)
   1090         "Appended columns not the same.\n"
   1091         "Previous: {} | New: {}".format(pf.columns, list(set(df.columns) - set(partition_on)))
```
But the proposed correction does not rended the other condition `set(partition_on) != set(pf.cats)`.

4/
We have the equivalent checks in fastparquet, and I don't see significant differences, so I would say this case is tests.
```python
# in writer.write
            if tuple(partition_on) != tuple(pf.cats):
                raise ValueError('When appending, partitioning columns must '
                                 'match existing data')
```
```python
# in api.write_row_groups
|...]
        partition_on = list(self.cats)
[...]
            self_cols = sorted(self.columns + partition_on)
            if self_cols != sorted(data.columns):
                diff_cols = set(data.columns) ^ set(self_cols)
                raise ValueError(
                    f'Column names of new data are {sorted(data.columns)}. '
                    f'But column names in existing file are {self_cols}. '
                    f'{diff_cols} are columns being either only in existing '
                     'file or only in new data. This is not possible.')
```

I am sorry @erinov1 , did you try directly with `fastparquet` lib as well? (without `dask` and without `pandas` overlayers)
I can deeper check if directly using fastparquet.
(I am not really dask proficient, sorry for this)
Bests

**Comment by yohplala** [comment]
@erinov1 , @martindurant 

I just tested with `fastparquet`, works ok.
```python
from os import path as os_path
import pandas as pd
import fastparquet as fp

df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [1, 1, 2, 2]})
path = os_path.expanduser('~/Documents/code/data/dask/test_partition')

fp.writer.write(path, df, partition_on='B', file_scheme='hive', write_index=False)
fp.writer.write(path, df, partition_on='B', file_scheme='hive', write_index=False, append=True)
fp.ParquetFile(path).to_pandas()

Out[9]: 
   A  B
0  1  1
1  2  1
2  3  2
3  4  2
4  1  1
5  2  1
6  3  2
7  4  2
```
(and resulting folder structure is as expected)

I would advise as next step would be `print` statements in `fastparquet.py` to know about `pf.columns`, `pf.cats` and `partition_on`.

**Comment by martindurant** [comment]
I finally got around to running the code with dask 2022.01.1 (just before 02.0) and the original code works fine!

**Comment by jsignell** [comment]
Ok! So I am going to go ahead and close this. Thank you everyone for engaging on this :)
