### ISSUE TITLE
`pytest` 7.0.0 compatibility

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8673]
The latest `pytest` release deprecated passing `None` to `pytest.warns` which is causing CI to fail (see [this CI build](https://github.com/dask/dask/runs/5070618868?check_suite_focus=true)). We should avoid passing `None` to `pytest.warns` in our tests.

**Comment by scharlottej13** [comment]
@jrbourbeau, you noted that #8678 only partially addresses this issue, what are the next steps?

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/pull/8678 removed our use of `pytest.warns(None)` (which is now deprecated) in only a single test module `dask/dataframe/tests/test_multi.py`. Next steps would be go to through and remove all the other times we use `pytest.warns(None)` in other test modules.

**Comment by jrbourbeau** [comment]
While https://github.com/dask/dask/pull/8718 did most of the work to close this issue, from [this recent CI build](https://github.com/dask/dask/runs/5788932823?check_suite_focus=true) it appears there are still some tests which are emitting the `pytest.warns(None)` deprecation warning 

```
dask/dataframe/tests/test_ufunc.py: 974 warnings
dask/dataframe/tests/test_multi.py: 8 warnings
  /usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/python.py:192: PytestRemovedIn8Warning: Passing None has been deprecated.
  See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
    result = testfunction(**testargs)
```

@pavithraes when you get a chance, could you look take a look at this issue?
