### ISSUE TITLE
Throw a warning on missing `cachey` dependecy

### ISSUE THREAD

**Issue by hcarvalhoalves** [dask/dask#868]
If not failing outright, it should at least throw a warning here: https://github.com/blaze/dask/blob/master/dask/cache.py#L11

I thought at first `cachey` was a typo of `cache` somewhere in the code until I figured out it's a library.

**Comment by mrocklin** [comment]
This is probably here to allow `py.test --doctest-modules distributed` to work without hanging on the `cache.py` module.  Some options:

1.  Raise an `ImportError` on creating a `Cache` object instead
2.  Figure out how to optionally skip the doctests in `cache.py` if `cachey` isn't around
3.  Raise a warning
