### ISSUE TITLE
Deprecate and remove tseries.resample getnanos

### ISSUE THREAD

**Issue by beckernick** [dask/dask#8688]
I've been exploring and learning about the Resampler class, and noticed that the utility `getnanos` is not currently used in the codebase. From the [blame](https://github.com/dask/dask/commit/7cb2428705fea3555f7269ba4be456783e02e194), it looks like this utility was necessary with an older version of pandas but is no longer necessary. As this is available in the public API, it may not be safe to remove without deprecation. But, perhaps it makes sense to deprecate and then remove this code?

```python
from dask.dataframe.tseries.resample import getnanos
getnanos??
Signature: getnanos(rule)
Docstring: <no docstring>
Source:   
def getnanos(rule):
    try:
        return getattr(rule, "nanos", None)
    except ValueError:
        return None
File:      ~/conda/envs/rapids-22.04/lib/python3.8/site-packages/dask/dataframe/tseries/resample.py
Type:      function
```

**Comment by jrbourbeau** [comment]
Thanks @beckernick -- agreed that `getnanos` is no longer needed. My guess is this was never intended to be part of Dask's public API, but given there's no leading `_` some users may have interpreted it as part of the public API. We should wrap `getnanos` in our `_deprecated` utility decorator 

https://github.com/dask/dask/blob/d36455b38da64b59d831d11e9c9bd44fd5b6cba2/dask/utils.py#L45

and add a test that it has been deprecated. Are you interested in working on this? (no obligation though)

**Comment by beckernick** [comment]
No problem. Unless you think this is particularly time sensitive, I am happy to throw up a PR (likely Friday morning)

**Comment by scharlottej13** [comment]
@beckernick are you still interested in opening a PR for this? No pressure either way, just wanted to check in!

**Comment by beckernick** [comment]
Unfortunately I've had to shift focus and haven't had a chance to do this. I'm still happy to return to this when things clear up, but am also happy for someone else to jump in.

**Comment by jrbourbeau** [comment]
@scharlottej13 would you mind taking a look at this when you get a moment?

**Comment by scharlottej13** [comment]
Just noting we should keep this issue open until we actually remove `getnanos`

**Comment by bryanwweber** [comment]
@scharlottej13 @jsignell I'm not sure how long deprecation cycles are with Dask. When should this function actually be removed?

**Comment by scharlottej13** [comment]
> @scharlottej13 @jsignell I'm not sure how long deprecation cycles are with Dask. When should this function actually be removed?

Thanks @bryanwweber! Looks like in deprecation message I put `after_version="2022.02.0"`, so I think now is a good time :)
