### ISSUE TITLE
Docker example not working on macOS and Windows

### ISSUE THREAD

**Issue by jonashaag** [dask/dask#8704]
https://github.com/dask/dask/blob/main/docs/source/deploying-docker.rst#example

This doesn't work on macOS: https://docs.docker.com/network/host/

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

cc @tschuelia

**Comment by jsignell** [comment]
Thanks for opening this @jonashaag seems like we just need a note saying that this only works on linux unless someone wants to contributed windows or mac examples?

**Comment by GowthamChowdary** [comment]
https://github.com/docker/for-mac/issues/2716  has been on since 2018. I'd like to make a PR with the note.

**Comment by jrbourbeau** [comment]
cc @jacobtomlinson for visibility

**Comment by jacobtomlinson** [comment]
Thanks for the ping here @jrbourbeau. I've opened #8731 to update the example for all platforms.
