### ISSUE TITLE
Add support for ADLS Gen2 with Service Principal (client_id/client_secret)

### ISSUE THREAD

**Issue by th0ger** [dask/dask#8711]
Hi daskers,

The documentation on [Microsoft Azure Storage](https://docs.dask.org/en/stable/how-to/connect-to-remote-data.html#microsoft-azure-storage) reads:
> Microsoft Azure Storage is comprised of Data Lake Storage (Gen1) and Blob Storage (Gen2). These are identified by the protocol identifiers adl and abfs, respectively, provided by the [adlfs](https://github.com/dask/adlfs) back-end.
> Authentication for adl requires tenant_id, client_id and client_secret in the storage_options dictionary.
> Authentication for abfs requires account_name and account_key in storage_options.

We use ADLS Gen2 (= Azure Blob Storage with HNS enabled). Azure has four different [access control models](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control-model), and we follow their [security recommendations](https://docs.microsoft.com/en-us/azure/storage/blobs/security-recommendations#identity-and-access-management) on: 
- "Use Azure Active Directory (Azure AD) to authorize access to blob data" - I.e. use service account `client_id`/`client_secret` via the ACL or RBAC models.
- "The principal of least privilege" - I.e. don't use `account_key`, which is basically root to the entire resource.
- "Disallow Shared Key authorization" - Again, don't `use account_key`.

So the Dask documentation goes directly against best security practices (and even leads less-experiences user in the direction of insecure setups).
Is this an actual limitation in Dask or adlfs? Or should the documentation be improved?

**Comment by th0ger** [comment]
I've posted this as well: https://github.com/fsspec/adlfs/issues/299

**Comment by graingert** [comment]
It looks like adfs supports both client_id/client_secret and account_name/account_key authentication methods: https://github.com/fsspec/adlfs/blob/fbe43c601e7b162b7a2bf93f7f8b699c747b70e6/adlfs/spec.py#L377-L381

so I think this is a documentation bug in dask

**Comment by jsignell** [comment]
Please feel free to open a PR @th0ger to improve the docs!

**Comment by th0ger** [comment]
So far, I can confirm that this auth method works against ADLS Gen2:

```python
df = dd.read_parquet(
    path='abfs://CONTAINER/FOLDER/FILE.parquet',
    engine="pyarrow-dataset",
    storage_options={"tenant_id": TENANT, "account_name": ACCOUNT_NAME, "client_id": CLIENT_ID, "client_secret": CLIENT_SECRET}
    )
```

So yes, ths docs should be improved.
