### ISSUE TITLE
No module named 'dask.distributed'; 'dask' is not a package 

### ISSUE THREAD

**Issue by arcontechnologies** [dask/dask#8719]
Hi,
I'm new to Dask but when I tried to import dask.distributed it said :
**No module named 'dask.distributed'; 'dask' is not a package** 

![image](https://user-images.githubusercontent.com/17960609/153670521-7bc9a4d6-6942-4f54-bba3-dec074307543.png)

Knowing that I'm running conda venv where I can see that dask is installed :

![image](https://user-images.githubusercontent.com/17960609/153670254-b72b592a-0b28-4652-8fb6-7d1a66e4e541.png)

Can someone help to undersatnd what going wrong ?

thanks

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @arcontechnologies. It looks like your local `dask.py` file is interfering with `import`ing from `dask` (the package). One fix would be to change the `dask.py` file to have another name

**Comment by arcontechnologies** [comment]
Oh my mistake ! I renamed it and it's working
thanks
