### ISSUE TITLE
PR Labeler bot not behaving as expected

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#8744]
According to the [labeler.yml](https://github.com/dask/dask/blob/main/.github/labeler.yml) anything that falls under   - `dask/docs/*` or `dask/docs/**/*` should receive the `documentation` label. But it's not working properly, and when the label is added manually it gets removed by the bot. 

For example, see this documentation PR https://github.com/dask/dask/pull/8648. Where the label was added manually twice and then removed by the bot. 

![Screen Shot 2022-02-21 at 2 49 41 PM](https://user-images.githubusercontent.com/7526622/155018094-0d9475b8-15be-48aa-888b-f0cad167d123.png)
![Screen Shot 2022-02-21 at 2 50 34 PM](https://user-images.githubusercontent.com/7526622/155018197-001df00f-3c69-4a59-9256-bcf5ed0cb6a7.png)

cc: @jsignell

**Comment by jsignell** [comment]
What the heck. We have a rogue bot?? Let me see if I can figure it out.
