### ISSUE TITLE
Much slower (100 x) xarray.open_mfdataset  + compute after upgrading to dask > 2022.1.0

### ISSUE THREAD

**Issue by espenairmine** [dask/dask#8753]
We're  opening 3-5 netcdf files, each 200-300mb.

Running on Azure AKS,  python 3.8
xarray==0.21.1
dask==2022.1.1

```
  def _get_forecast_dataframe(self, request: Any, lat: float, lon: float) -> Union[pd.DataFrame, None]:
        """Get a DataFrame with four day forecast"""
        ds = xr.open_mfdataset(self.local_paths)
        times = ds.time.data
        lats = ds.lat.data
        lons = ds.lon.data
        vars = [ds[v] for v in ds.variables if v not in ["lat", "lon", "time", "crs"]]
        forcecast= [v for v in vars if v.long_name.startswith("forecast")]
        tss = {v.name: v.sel(lat=lat, lon=lon, method="nearest").compute() for v in forcecast}
        df = pd.DataFrame(data=tss, index=times)
        return df
```

This call executes in 300-400ms with dask <= 2022.1.0
After upgrading, automatic if package version not pinned, the call takes 20-30 sec 

**What happened**:

After upgrading (automatically), our processes had close to 100x longer call times

**What you expected to happen**:

Upgrading having no negative performance impact

**Minimal Complete Verifiable Example**:

```
import xarray as xr

# weather files from Norwegian Met Service
# if specified not available , download from https://thredds.met.no/thredds/catalog/metpplatest/catalog.xml
# download to /mnt/data, or update path below

url= "https://thredds.met.no/thredds/fileServer/metpplatest/met_forecast_1_0km_nordic_20220225T11Z.nc"

def compute(lat: float, lon: float):
    ds = xr.open_mfdataset("/mnt/data/met*.nc")
    lats = ds.x.data
    lons = ds.y.data
    if lat < lats[0] or lat > lats[-1]:
        print("lat out-of-bounds")
    if lon < lons[0] or lon > lons[-1]:
        print("lon out-of-bounds")
    vars = [ds[v] for v in ds.variables if v  in ["air_pressure_at_sea_level"]]
    tss = {v.name: v.sel(x=lat, y=lon, method="nearest").compute() for v in vars}
    print(tss)

if __name__ == "__main__":
    compute(0, 0)
```

Timing with dask==2202.2:

root@d93a10d88800:/workspace/airmine# time python test-dask.py

real    0m3.689s
user    0m3.045s
sys     0m1.761s

Timing with dask==2202.1
root@d93a10d88800:/workspace/airmine# time python test-dask.py

real    0m0.972s
user    0m0.962s
sys     0m1.165s

This is with opening a single file, we typically open an array

**Anything else we need to know?**:

**Environment**:

VERSION="20.04.2 LTS (Focal Fossa)
Python 3.8.5 [GCC 9.3.0] on linux
xarray==0.21.1
dask==2022.1.1
Installed with pip -r requirements

**Comment by jrbourbeau** [comment]
Thanks for reporting @espenairmine. Are you able to provide a minimal reproducer others can run (see https://blog.dask.org/2018/02/28/minimal-bug-reports for more details)?

**Comment by espenairmine** [comment]
@jrbourbeau  - hopefully reproduceable with updated code above

**Comment by jsignell** [comment]
It would help if you can check the code above. Particularly the path in the `compute` function is not right. 

If I naively run:

```python
import xarray as xr

# weather files from Norwegian Met Service
# if specified not available , download from https://thredds.met.no/thredds/catalog/metpplatest/catalog.xml
# download to /mnt/data, or update path below

url= "https://thredds.met.no/thredds/fileServer/metpplatest/met_forecast_1_0km_nordic_20220225T11Z.nc"

def compute(lat: float, lon: float):
    ds = xr.open_mfdataset("/mnt/data/met*.nc")  # what should this be?
    lats = ds.x.data
    lons = ds.y.data
    if lat < lats[0] or lat > lats[-1]:
        print("lat out-of-bounds")
    if lon < lons[0] or lon > lons[-1]:
        print("lon out-of-bounds")
    vars = [ds[v] for v in ds.variables if v  in ["air_pressure_at_sea_level"]]
    tss = {v.name: v.sel(x=lat, y=lon, method="nearest").compute() for v in vars}
    print(tss)

if __name__ == "__main__":
    compute(0, 0)
```

I get:

```python-traceback
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [1], in <module>
     20     print(tss)
     23 if __name__ == "__main__":
---> 24     compute(0, 0)

Input In [1], in compute(lat, lon)
     10 def compute(lat: float, lon: float):
---> 11     ds = xr.open_mfdataset("/mnt/data/met*.nc")  # what should this be?
     12     lats = ds.x.data
     13     lons = ds.y.data

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/xarray/backends/api.py:873, in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
    870     paths = [os.fspath(p) if isinstance(p, os.PathLike) else p for p in paths]
    872 if not paths:
--> 873     raise OSError("no files to open")
    875 if combine == "nested":
    876     if isinstance(concat_dim, (str, DataArray)) or concat_dim is None:

OSError: no files to open
```

**Comment by espenairmine** [comment]
@jsignell -  sorry, could have included code to download the files, but it was in the comment above:

**Comment by jsignell** [comment]
Ah sorry it's been a while since I was downloading from a thredds server. 

I downloaded a datafile from here: https://thredds.met.no/thredds/catalog/metpplatest/catalog.html?dataset=metpplatest/met_forecast_1_0km_nordic_20220303T13Z.nc 

And ran:

```python
import xarray as xr

def compute(lat: float, lon: float):
    ds = xr.open_mfdataset(
        [
            "data/met_forecast_1_0km_nordic_20220225T11Z.nc",
        ]
    ) 
    lats = ds.x.data
    lons = ds.y.data
    if lat < lats[0] or lat > lats[-1]:
        print("lat out-of-bounds")
    if lon < lons[0] or lon > lons[-1]:
        print("lon out-of-bounds")
    vars = [ds[v] for v in ds.variables if v in ["air_pressure_at_sea_level"]]
    tss = {v.name: v.sel(x=lat, y=lon, method="nearest").compute() for v in vars}
    print(tss)

%time compute(0, 0)

```
with latest dask I got:

```
# CPU times: user 1.64 s, sys: 189 ms, total: 1.83 s
# Wall time: 1.91 s
```

with dask 2021.10.0 I got: 
```
CPU times: user 46.1 ms, sys: 4.32 ms, total: 50.5 ms
Wall time: 47.7 ms
```

when I use `open_dataset` instead I get much more similar times:

latest
```
CPU times: user 36.7 ms, sys: 3 ms, total: 39.7 ms
Wall time: 39.3 ms
```

2021.10.0
```
CPU times: user 41.2 ms, sys: 3.7 ms, total: 44.9 ms
Wall time: 45.1 ms
```

I'm investigating more now.

**Comment by jsignell** [comment]
Ok I took a look at the dask graphs for these arrays and the main difference I am seeing is there is an extra layer in the new graph. I think the layer is coming from here: 

https://github.com/dask/dask/blob/f5b42d4b90d45f9c9bf42fcae99e4a4589246f18/dask/array/core.py#L299-L319

It looks like it was added in https://github.com/dask/dask/pull/7417 @ian-r-rose I'm hoping that you might have some insight.

I simplified down the MRE:

```python
import xarray as xr

ds = xr.open_mfdataset(["data/met_forecast_1_0km_nordic_20220303T13Z.nc"])
var = next(ds[v] for v in ds.variables if v in ["air_pressure_at_sea_level"])
result = var.sel(x=0, y=0, method="nearest")
result.data.dask
```

latest dask:
```
HighLevelGraph with 3 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x7fd48a7dee80>
 0. original-open_dataset-a5d44fce2ee529890053648591a49defair_pressure_at_sea_level-c0e41894600ddf6e227b3db4b107fbe5
 1. open_dataset-a5d44fce2ee529890053648591a49defair_pressure_at_sea_level-c0e41894600ddf6e227b3db4b107fbe5
 2. getitem-6a48430f3a080c3080e74c001bf3ad4d
```

dask 2021.10.0
```
HighLevelGraph with 2 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x7fad69a62fd0>
 0. open_dataset-a465c8db28098227714fcb124311e413air_pressure_at_sea_level-03b0f79a193fef70fa71ac8beb31f839
 1. getitem-6b50c5c17667e0cd242d1d602d06bb72
```

**Comment by jsignell** [comment]
Let me also ping @dcherian from xarray for visibility.

**Comment by ian-r-rose** [comment]
Thanks for the ping @jsignell, sorry to be slow in responding. I'm having a tough time reproducing the behavior here. I tried this on xarray==0.21.1 and dask==2021.10.0/dask==2021.2.1, and did the following steps:

1. Downloaded a ~100MiB netcdf file from the above thredds server ([here](https://thredds.met.no/thredds/catalog/metpplatest/catalog.html?dataset=metpplatest/met_analysis_1_0km_nordic_latest.nc)].
2. Ran the snippets from both [this comment](https://github.com/dask/dask/issues/8753#issuecomment-1058158881) and [this comment](https://github.com/dask/dask/issues/8753#issuecomment-1058133329).
3. Tried the above with both `xr.open_dataset` and `xr.open_mfdataset`.

In no case did I see anything close to 20-30 seconds to compute, everything was in the tens of ms range. Is there perhaps something I've missed in trying to reproduce this?

There *was* a change in how `da.from_array` constructed it's graphs recently (#7417), so it wouldn't be hugely surprising to find some downstream regressions we need to address. The difference in number of HLG layers that @jsignell found is expected, but the final low-level graph should be fairly similar. But without being able to reproduce, it's hard for me to say for sure.

**Comment by jsignell** [comment]
I think the 20-30 seconds was for more than one file. I was seeing ~2 seconds and ~50ms for one file with dask main and dask 2021.10.0 respectively.

**Comment by ian-r-rose** [comment]
With both versions I'm seeing ~50-100 ms. What scheduler are you using? If it's multiprocessing or distributed, there may be some undesirable inter-process communication of the array that's being triggered.

**Comment by ian-r-rose** [comment]
A quick update based on some investigations that @jsignell and I carried out earlier today:

We are indeed able to reproduce a performance regression for this example, and it is related to #7417. That PR changed `from_array` to use `Blockwise`, which in theory allows for higher-level optimizations and cheaper graph communication and construction. But the introduction of `Blockwise` prevented one type of low-level optimization: slicing fusion.

This is because fusing adjacent slices relies on checking whether each task is "get-ish": https://github.com/dask/dask/blob/02f38865939ac4775ba3f34789bfd3c5e915eebe/dask/array/optimization.py#L130-L138 

With the old low-level-graph, the `getter` callable was directly available on the task, and this comparison was easy. But in blockwise, the callables are obfuscated within a `SubgraphCallable`, and the optimizer was no longer able to identify that task as get-ish, and the optimization did not take place.

I'm still cooking up a reproducer that does not rely on xarray, and will post it here when I have it.

There are (at least) two fixes that could be made here:
1. The long term, correct fix is to convert slicing to be a HighLevelGraph Layer (see some early work in #7655), and make sure that it can talk well with `Blockwise`. It may even make sense to convert `da.from_array` from blockwise to whatever slicing layer we come up with. But that design discussion is not particularly close right now.
2. A short term, hacky fix is to make sure that the slicing fusion can recognize a blockwise subgraph callable as a getter. This would be ugly, and involve introspecting `SubgraphCallable`s, making it a very leaky abstraction. But I think it would be fairly easy to do, as long as we put big blinking disclaimers that it should be removed as soon as high-level-slicing is done.

**Comment by ian-r-rose** [comment]
Okay, here is a reproducer with just dask:

```python
import numpy
import dask.array as da

# Use an ndarray subclass to avoid special case for
# numpy arrays. Lazy arrays like xarray datasets
# already satisfy this
class MyArray(numpy.ndarray):
    pass

x = numpy.random.uniform(size=(1000, 1000)).view(MyArray)



xx = da.from_array(x, chunks=100)
yy = xx[23:24, 65:66]  # Slice from one chunk, which can be fused with from_array
dsk = yy.__dask_optimize__(yy.dask, yy.__dask_keys__())
print(dsk)
```

On `dask==2021.10.0` this produces
```python
{('getitem-482c4f7d051bab02a4e5de435b6635d3',
  0,
  0): ('array-getitem-482c4f7d051bab02a4e5de435b6635d3', 0, 0),
 'array-original-0043e9339edbf7b18e0dffa2354ca805': MyArray([[0.75496145, 0.71040058, 0.26402173, ..., 0.89002368,
           0.47585329, 0.96497852],
          [0.5823307 , 0.07175467, 0.14595467, ..., 0.63779591,
           0.67730445, 0.71338149],
          [0.42915523, 0.4993591 , 0.29309595, ..., 0.60710493,
           0.43123075, 0.52111913],
          ...,
          [0.0385207 , 0.20286531, 0.14720955, ..., 0.45732608,
           0.5083299 , 0.76006257],
          [0.72467882, 0.9119804 , 0.60712482, ..., 0.9274443 ,
           0.05040048, 0.96039124],
          [0.12749118, 0.38615043, 0.72269677, ..., 0.29804572,
           0.18775866, 0.3715634 ]]),
 ('array-getitem-482c4f7d051bab02a4e5de435b6635d3',
  0,
  0): (<function dask.array.core.getter(a, b, asarray=True, lock=None)>, 'array-original-0043e9339edbf7b18e0dffa2354ca805', (slice(23, 24, None),
   slice(65, 66, None)), False, False)}
```
whereas on `main` this produces
```python
{('getitem-8565cad6f854187d2bcb8c57560c230a',
  0,
  0): ('array-getitem-8565cad6f854187d2bcb8c57560c230a', 0, 0),
 'original-array-7600483ec382d2244bea4a0da58d8596': MyArray([[0.57031275, 0.07244231, 0.35438451, ..., 0.23643452,
           0.2705955 , 0.23255325],
          [0.53274312, 0.50732558, 0.79660538, ..., 0.1799429 ,
           0.63057926, 0.41924305],
          [0.98659251, 0.06321354, 0.29775424, ..., 0.660547  ,
           0.072433  , 0.73981265],
          ...,
          [0.16659373, 0.51461264, 0.74210757, ..., 0.40877502,
           0.44473356, 0.76993016],
          [0.33193714, 0.37566295, 0.84591651, ..., 0.21424494,
           0.91305219, 0.6167193 ],
          [0.64256872, 0.41688069, 0.3727772 , ..., 0.55530654,
           0.28894569, 0.38069073]]),
 ('array-getitem-8565cad6f854187d2bcb8c57560c230a',
  0,
  0): (<function dask.array.chunk.getitem(obj, index)>, (subgraph_callable-4b804397-1337-48c0-835e-73857e94bb0f,
   'original-array-7600483ec382d2244bea4a0da58d8596',
   (slice(0, 100, None), slice(0, 100, None))), (slice(23, 24, 1),
   slice(65, 66, 1)))}
```

Notice how in the first case the slice operation is fused with the original read from disk (effectively pushing it into the storage layer), but in the second case the slice operation is kept separate.
