### ISSUE TITLE
Expand Meta doc for Arrays

### ISSUE THREAD

**Issue by quasiben** [dask/dask#8759]
In our documentation `meta` is explained for Dataframes:
https://docs.dask.org/en/stable/dataframe-design.html#metadata

It would be nice to include an analogous explanation for arrays as well

**Comment by soma2000-lang** [comment]
@quasiben  can i work on this

**Comment by jsignell** [comment]
@soma2000-lang if you are interested in working on this you can go ahead and open a pull request.

**Comment by soma2000-lang** [comment]
Ok

**Comment by soma2000-lang** [comment]
@jsignell Just once to clarify what I need to do here,should I write about arrays here??

**Comment by pavithraes** [comment]
@soma2000-lang Just checking in, are you comfortable opening a PR for this? Please feel free to ask for more clarifications or help with anything :)

**Comment by soma2000-lang** [comment]
Yes,sorry for the delay

**Comment by sparkyniner** [comment]
Hello if this is still open can I work on this?

**Comment by jsignell** [comment]
@sparkyniner absolutely!! You are welcome to pick up any open issue!

**Comment by sparkyniner** [comment]
Could you please link the html file I need to edit?, I'm having some trouble finding it.

**Comment by jsignell** [comment]
I think Ben was recommending that you add a section to this page: https://github.com/dask/dask/blob/main/docs/source/array-design.rst

**Comment by jayeshmanani** [comment]
Hey @jsignell, @pavithraes, @quasiben I can work on this, I should be doing is add a section of meta in the array-design.rst file, I am doing it and creating the PR.

**Comment by jsignell** [comment]
Yes @jayeshmanani that is exactly right.

**Comment by jayeshmanani** [comment]
Hello, @jsignell I have updated a few details could you suggest what I add more details to it?

**Comment by jsignell** [comment]
I left a comment on the PR. Overall it looks really good! There's just one bit that maybe was copied over from dataframe and doesn't quite apply.
