### ISSUE TITLE
Support for automatic optimizations

### ISSUE THREAD

**Issue by mattgerg12** [dask/dask#8778]
Does dask query optimizer can automatically push down filters and projections based on the transformation queries that follows after the load? (Just similar to spark, duckDB ) Or should we rely on manually specifying this when loading the file(`read_parquet`) using `columns` and `filters` options ? 

Are there any plans to support this in future ? I am curious - as on the contrary to pandas, dask computes lazily and wondering why this feature is not yet baked into the optimizer.

**Comment by jsignell** [comment]
There are definitely plans to push down filters, but they aren't very complete yet, so if you can include columns and filters in the read_parquet call it is always better to be explicit. 

You can watch PRs like https://github.com/dask/dask/pull/8692 and https://github.com/dask/dask/pull/8633 for that work.
