### ISSUE TITLE
[Bug] [Dask-on-Ray] Partd files are not cleaned automatically

### ISSUE THREAD

**Issue by mikwieczorek** [dask/dask#8787]
**What happened**:
Partd files that are used by Dask for shuffling are accumulating in `/tmp` folder on Ray Cluster workers.

**What you expected to happen**:
partd files should be cleaned automatically

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import numpy as np
import pandas as pd
import ray
from ray.util.dask import ray_dask_get


### Helpers
def create_df(num_unique_ids, max_num_samples, min_id, max_id):
    repetition_array = np.random.randint(1, max_num_samples, num_unique_ids)
    ids_array = np.repeat(np.random.randint(min_id, max_id, num_unique_ids), repetition_array).flatten()
    df = pd.DataFrame(
        {
            'id':  ids_array,
            'value': np.random.randint(0, max_num_samples, ids_array.size),
        }
    )
    # print(random_index.shape, repetition_array.shape)
    return df

def myparitionsize(df):
    return len(df)

def custom_func(partition, column_names):
    for col in partition.columns:
        if col in column_names:
            values = partition[col].to_numpy()
            row_sequence = set(['_'.join(str(v).split()) for v in values])
            return row_sequence

def main():
    ### RAY
    # ray.init(address='auto')  ## When run inside a Ray Cluster
    # ray.init(address='ray://127.0.0.1:10001')  ## When run with port-forwarding from k8s
    ray.init(address='ray://172.17.0.20:10001')  ## When run with Ray Cluster Luncher
    # ray.init()  ## Local Ray

    ### DASK
    dask.config.set(scheduler=ray_dask_get)
    # print(dask.config.get("scheduler", None))

    grouping_column = 'id'
    allowed_column_ids = ['id', 'value']

    # Code
    df = create_df(num_unique_ids=20000, max_num_samples=10000, min_id=1, max_id=20000)
    df['id'] = df['id'].astype(np.int64)
    df['value'] = df['value'].astype(object)

    correct_number_of_groups = df['id'].nunique()
    print("Correct number of groups in a generated DataFrame: ", correct_number_of_groups)

    ddf = dd.from_pandas(df, npartitions=4)
    print(f"Paritions before setting index:\n",ddf.map_partitions(myparitionsize).compute())
    ddf = ddf.set_index(grouping_column, sorted=False)                    #  <- wrong results
    # ddf = ddf.set_index(grouping_column, sorted=False, shuffle="tasks") #  <- correct results
    print(f"Paritions after setting index:\n",ddf.map_partitions(myparitionsize).compute())

    d = ddf.groupby(grouping_column).apply(custom_func,
                                        column_names = allowed_column_ids,
                                        meta=object
                                        ).compute(scheduler=ray_dask_get)
    # Number of returned unique groups should be equal to correct_number_of_groups calulcated using Pandas DF
    assert correct_number_of_groups == d.reset_index()['id'].nunique(), f"Correct number of groups: {correct_number_of_groups} NOT EQUAL number of groups returned {d.reset_index()['id'].nunique()}"
    
if __name__ == "__main__":
    main()
```

**Anything else we need to know?**:
Ray Cluster needs to be deployed on Kubernetes with matching Ray versions on cluster and client.

**Environment**:

python_version='3.7.7'
ray_version='1.10.0'
dask_version='2022.02.0'

**Comment by quasiben** [comment]
Have you pinged Ray folks about this ?  My understanding is that the Ray is also handling the object spilling in addition to running tasks through Ray's scheduler

**Comment by mikwieczorek** [comment]
@quasiben Yes, but Ray is spilling objects in a separate directory if needed. `partd` files are Dask related files. Seems like they should be cleaned automatically by Dask after shuffling, but they persist on the workers.

**Comment by mikwieczorek** [comment]
@quasiben Actually yes, I managed to reproduce the problem with local Ray Cluster. Seems like the problem depends on the data size or/and machine-capacity.

You can try modifying `num_cpus` and data size values to obtain `partd` file in the `/tmp` folder.

In the `main` function I used:
```python
...
ray.init(num_cpus=12)
...
df = create_df(num_unique_ids=200000, max_num_samples=100, min_id=1, max_id=2000000)
...
```
What is even more interesting I did not get `partd` files when running with this line
```python
ddf = ddf.set_index(grouping_column, sorted=False, shuffle='tasks')
```
but GOT the `partd` files when running without `shuffle` argument, so with this line

```python
ddf = ddf.set_index(grouping_column, sorted=False) 
```

**Comment by pavithraes** [comment]
@mikwieczorek Thanks for creating this example!

> What is even more interesting I did not get partd files when running with this line

This is expected because [`partd`](https://docs.dask.org/en/stable/dataframe-groupby.html?highlight=partd#shuffle-on-disk) is not used when `shuffle='tasks'` :)

Would you also be able to share an example that uses a [Dask Single Machine Scheduler](https://docs.dask.org/en/stable/scheduling.html)?

**Comment by mikwieczorek** [comment]
@pavithraes Yes, you are right of course about the `partd` and the `shuffle`. However with Ray they do persist even when `shuffle=tasks`

I will have a look

**Comment by mikwieczorek** [comment]
@pavithraes Yes, you are right about the `partd` files nad `shuffle` method. My bad.

I tried Dask `threads` scheduler and it does not leave any `partd` files. 
However, using Dask with Ray and without specifying `shuffle=tasks` does SOMETIMES result in `partd` files left on a disk after processing finished.  

The problem with persisting `partd` files arose when I was using Dask + Ray Cluster and I noticed the files cluttering the `/tmp` folder. If the cluster is multi-node and dask-ray-scheduler is used I assume that all shuffling should be done as `tasks` as it is all in a distributed environment, so the `partd` files should never be created especially on worker nodes? Or am I missing something and dask-ray-scheduler may use `partd` files in some other way?

**Comment by pavithraes** [comment]
@mikwieczorek Thanks for confirming!

>  If the cluster is multi-node and dask-ray-scheduler is used I assume that all shuffling should be done as tasks as it is all in a distributed environment, so the partd files should never be created especially on worker nodes?

That's exactly right, I was wondering the same. With this information, I'd also suggest you check with the Ray community about this.

**Comment by pavithraes** [comment]
@mikwieczorek I'll go ahead and close this because this is related to the Ray Scheduler. We can re-open if needed. :)

**Comment by macedd** [comment]
Having similar results with `shuffle=disk` which writes indexes to `/tmp/partd` files but does not clean them.
I'm looking for code that can actually answers why or how the `temporary-directory` would be cleaned up.
