### ISSUE TITLE
Add ``dask.array.default_rng``

### ISSUE THREAD

**Issue by joanrue** [dask/dask#8790]
Functions used for the generation of random samples (for example [dask.array.random.normal](https://docs.dask.org/en/latest/generated/dask.array.random.normal.html#dask.array.random.normal)) indicate in their docstring:
`New code should use the normal method of a default_rng() instance instead.`. 

This feature is not currently available and would be very useful for compatibility with other array modules (numpy, cupy, ...).

**Comment by jsignell** [comment]
Thanks for opening this @joanrue! If this is something that you are interested in please feel free to open a pull request. For context, that docstring is copied from the upstream library that the function is mimicking (in this case numpy) so we don't really control the contents.
