### ISSUE TITLE
Setting divisions on dask dataframe collapses rows. 

### ISSUE THREAD

**Issue by rajeee** [dask/dask#8802]
**What happened**: Trying to set divisions on a dask dataframe created from delayed objects results in rows being erased from the dataframe.

**What you expected to happen**: The divisions to work as expected

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd
def get_df(bid):
    df = pd.DataFrame({"id": [bid, bid, bid], "value": [bid+0.1, bid+0.2, bid+0.3]})
    df = df.set_index('id')
    return df

ddf = dd.from_delayed([dask.delayed(get_df)(i) for i in range(5)])
ddf.divisions=[0, 9, 15]
ddf.compute()
```
The code outputs this:

![image](https://user-images.githubusercontent.com/12487392/158036601-09fbbe67-d370-44fc-a106-5d490e22f181.png)

Somehow, rest of the rows is lost. The output should have been like this:
![image](https://user-images.githubusercontent.com/12487392/158036643-bc529baf-956c-46c2-85f8-862df8975ec3.png)

**Anything else we need to know?**:
The two partitions of ddf contains the following:
![image](https://user-images.githubusercontent.com/12487392/158036621-7db5df77-12c1-48c1-a89b-7961e96ebe6f.png)
![image](https://user-images.githubusercontent.com/12487392/158036628-7fe31217-5673-4972-886a-962e28c6608d.png)

**Environment**: MAC

- Dask version: 2022.2.1
- Python version: 3.9.7
- Operating System: Mac Catalina
- Install method (conda, pip, source): conda

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by jcrist** [comment]
Assigning directly to divisions `ddf.divisions = ...` has no error checking and isn't really recommended. In your case the issue is that the divisions you're assigning only contain 2 partitions, while your original dataframe has 5 partitions. This results in the trailing 3 partitions being implicitly dropped. As a reminder, divisions is a tuple of npartitions + 1 elements, where the first npartitions elements are the minimum of their partition, and the final value is the maximum value in the last partition.

If you know the divisions of your output dataframe, I recommend passing them in to `dd.from_delayed` directly via the `divisions` kwarg, not mutating the value on the dataframe directly.

**Comment by rajeee** [comment]
@jcrist Thanks for the response.

I think there is more going on. I have not been able to create two partitions with (0, 9, 15) divisions from the list of 5 delayed objects, no matter which approach I use.

Consider the following:

```
import pandas as pd
import dask.dataframe as dd
def get_df(bid):
    df = pd.DataFrame({"id": [bid, bid, bid], "value": [bid+0.1, bid+0.2, bid+0.3]})
    df = df.set_index('id')
    return df

ddf = dd.from_delayed([dask.delayed(get_df)(i) for i in range(5)], divisions=(0,3,6,9,12,15))
# ddf = ddf.repartition(npartitions=2)  # adding this line won't help either
ddf = ddf.repartition(divisions=(0, 9, 15))
ddf.compute()
```
This still results in missing rows.

**Comment by rajeee** [comment]
Awesome! I mixed up how the divisions were supposed to work. Glad that this helped uncover some related issues. 

To conclude, I should have done this:

```python
import pandas as pd
import dask.dataframe as dd
def get_df(bid):
    df = pd.DataFrame({"id": [bid, bid, bid], "value": [bid+0.1, bid+0.2, bid+0.3]})
    df = df.set_index('id')
    return df

ddf = dd.from_delayed([dask.delayed(get_df)(i) for i in range(5)])
ddf.divisions=(0, 1, 2, 3, 4, 4)  # important to have divisions before being able to repartition
ddf = ddf.repartition(divisions=(0, 3, 4))
a = ddf.compute() # gives all 15 rows
b = ddf.get_partition(0).compute() # Gives id 0, 1, 2 (9 rows)
c = ddf.get_partition(1).compute() # Gives id 3, 4 (6 rows)
```
