### ISSUE TITLE
can't install from git repository (error future feature annotations is not defined)

### ISSUE THREAD

**Issue by Abdou24MR** [dask/dask#8839]
when i run this command to install dask 
`

> python -m pip install 

`
it give the error :

**ERROR: You must give at least one requirement to install (see "pip help install")**

so I tried this command: 

`

> C:\Users\....\dask> pip3 install .

`
the new error is from file : setup.py", line 3 

Processing c:\users\e580\dask
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\e580\appdata\local\programs\python\python36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\E580\\dask\\setup.py'"'"'; __file__='"'"'C:\\Users\\E580\\dask\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\E580\AppData\Local\Temp\pip-pip-egg-info-8am3sr_m'
       cwd: C:\Users\E580\dask\
  Complete output (6 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\E580\dask\setup.py", line 3
      from __future__ import annotations
      ^
  **SyntaxError: future feature annotations is not defined**

**Comment by bryanwweber** [comment]
Hello! This is happening because this feature requires at least Python 3.7. Dask supports Python 3.8 and up, see #8572 where Python 3.7 support was dropped.

**Comment by jcrist** [comment]
Closing as resolved.
