### ISSUE TITLE
`TypeError: 'coroutine' object is not iterable` when using compute

### ISSUE THREAD

**Issue by patata3000** [dask/dask#8840]
I'm using dask.distributed in a nameko service. When running something closely related to this following code, I get the TypeError in the title.

```python
from dask.distributed import Client

client = Client("address:port")

def test_func(a):
    return a + 1

def test_dask(self):
        dataf = delayed(test_func)(1)
        result = dataf.compute()  # Error is thrown here
        return result

test_dask()
```

```
  File "/tmp/pex_dzcz0dr1/pex-kguDrQMzO5Dxrx1rpKvG6jiMID8/lib/third_party/dask/base.py", line 288, in compute
     (result,) = compute(self, traverse=False, **kwargs)
  File "/tmp/pex_dzcz0dr1/pex-kguDrQMzO5Dxrx1rpKvG6jiMID8/lib/third_party/dask/base.py", line 572, in compute
     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
TypeError: 'coroutine' object is not iterable
```

**Anything else we need to know?**:
Doing this makes it work:
```python
        result = dataf.compute(scheduler="threads")  # | processes | synchronous # No more errors
```

**Environment**:

- Dask version: 2022.03.0
- Python version: 3.9
- Operating System: archlinux in docker compose
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
It looks like you have an asynchronous scheduler. So you should do something like:

```python
from distributed import Client
import dask

client = Client(asynchronous=True)


def test_func(a):
    return a + 1


dataf = dask.delayed(test_func)(1)
future = client.compute(dataf)
result = await future
```

**Comment by pavithraes** [comment]
@patata3000 Thanks for opening this! Does `@jsignell`'s comment help resolve your issue?

**Comment by pavithraes** [comment]
@patata3000 I'll go ahead and close this, feel free to re-open to continue the discussion if needed. :)

Since this is a usage question, I'd also like to share the [Dask Discourse](https://dask.discourse.group/) forum that you can check out for future questions!
