### ISSUE TITLE
Separate "diagnostics" or "debugging" section in docs sidebar?

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#8841]
Really excited to have https://github.com/dask/dask/pull/8648, but I found it odd that it's sitting in the sidebar between `DataFrame` and `Delayed`:
![image](https://user-images.githubusercontent.com/3309802/159994183-cf34df57-866a-4fed-8ea4-49b85e3be3bc.png)

Should we have either a sub-heading, or an entirely separate heading, for things like this? I'd probably include:
* https://docs.dask.org/en/latest/how-to/debug.html
* https://docs.dask.org/en/latest/dashboard.html
* https://docs.dask.org/en/latest/understanding-performance.html
* https://docs.dask.org/en/latest/diagnostics-local.html (I can no longer figure out how to easily get to this page)
* https://docs.dask.org/en/latest/diagnostics-distributed.html (I can no longer figure out how to easily get to this page)

(I also find it very confusing that all these things about distributed diagnostics/dashboard are in the `dask/dask` docs, not `dask/distibuted`, but that's its own can of worms we don't need to get into right now.)

cc @ncclementi @scharlottej13 @ian-r-rose @jsignell @jacobtomlinson

**Comment by jsignell** [comment]
Yeah I think it should go near "Deploying Clusters" - no strong preference about before or after. Bigger picture the plan is to absorb all of the narrative-style distributed docs into dask.

**Comment by ncclementi** [comment]
I think this issue has 2 parts. 
1. Moving "Dashboard DIagnostics" above Deploying Clusters
2. Design a heading/subheading that includes the links mentioned in the original comment. 

I think we should put some thought and go for 2, but do we create a separate heading call "Diagnostics and Performance" and put in there all the links mentioned above. Should we have debug in how-to and also in this new heading? Any opinions?

**Comment by gjoseph92** [comment]
I like "Diagnostics and Performance" as a heading name. I think debug can move out of how-to and into that new heading.

**Comment by mrocklin** [comment]
We used to have "Understanding Performance" as a header and I referred to
it often.  Nowadays I find that I have to use the searchbox to get to those
pages.  +1 generally on this approach.
