### ISSUE TITLE
`da.from_array` doesn't work as expected for scalar masked numpy array inputs 

### ISSUE THREAD

**Issue by davidhassell** [dask/dask#8866]
Hello,

I've noticed some unexpected behaviour when passing scalar masked numpy arrays to `da.from_array`, e.g. `x = da.from_array(np.ma.array(9, mask=True))`. When `x` is computed, we don't get the same numpy array input back, rather we get the `np.ma.masked` constant. This is problematic for because

1. `np.ma.masked` is a float, which may be a different dtype from the dask array
2. `np.ma.masked`  can not be sliced, unlike a numpy scalar array

#### Reproducer

```python
import numpy as np
import dask as da
a = np.ma.array(9, mask=True)  # 0-d
x = da.from_array(a)

print('\nnumpy input =', repr(a))
print('\ndask =', repr(x))
print('\ndask dtype =', x.dtype)
print('\ndask computed =', repr(x.compute()))
print('\ndask computed dtype =', x.compute().dtype)
```

Gives output:
```
numpy input = masked_array(data=--,
             mask=True,
       fill_value=999999,
            dtype=int64)

dask = dask.array<array, shape=(), dtype=int64, chunksize=(), chunktype=numpy.MaskedArray>

dask dtype = int64

dask computed = masked

dask computed dtype = float64
```
Other size one masked arrays are not affected
```python
import numpy as np
import dask as da
a = np.ma.array([9], mask=[True])  # 1-d
x = da.from_array(a)

print('\nnumpy input =', repr(a))
print('\ndask =', repr(x))
print('\ndask dtype =', x.dtype)
print('\ndask computed =', repr(x.compute()))
print('\ndask computed dtype =', x.compute().dtype)
```

Gives output:
```
numpy input = masked_array(data=[--],
             mask=[ True],
       fill_value=999999,
            dtype=int64)

dask = dask.array<array, shape=(1,), dtype=int64, chunksize=(1,), chunktype=numpy.MaskedArray>

dask dtype = int64

dask computed = masked_array(data=[--],
             mask=[ True],
       fill_value=999999,
            dtype=int64)

dask computed dtype = int64
```

#### Possible solution

This seems to occur because the scalar masked array input is sliced with `()` during it's passage through `da.from_array`:

```python
>>> x = da.from_array(np.ma.array(9, mask=True))
>>> dict(x.dask)
{'original-array-27cd77571adb3b50d0abe2275510329d': masked_array(data=--,
              mask=True,
        fill_value=999999,
             dtype=int64),
 ('array-27cd77571adb3b50d0abe2275510329d',): (subgraph_callable-98ef2ccb-7037-4a4a-9d58-9417f3808eb6,
  'original-array-27cd77571adb3b50d0abe2275510329d',
  ())}
```

In fact, the 1-d masked case is also sliced, but with `slice(0, 1)` so that everything works as expected:

```python
>>> x = da.from_array(np.ma.array([9], mask=[True])) # 1-d
>>> dict(x.dask)
{'original-array-5534b77f07bda580d7a7709dec8ce5af': masked_array(data=[--],
              mask=[ True],
        fill_value=999999,
             dtype=int64),
 ('array-5534b77f07bda580d7a7709dec8ce5af',
  0): (subgraph_callable-1334e14f-ad05-4fdb-9dcb-54a8c20644e4, 'original-array-5534b77f07bda580d7a7709dec8ce5af', (slice(0, 1, None),))}
```
I wonder if the reason behind this is that numpy masked arrays do _not_ have type `np.ndarray`, rather they are `np.ma.core.MaskedArray`:

```python
>>> b = np.ma.arange(9)
>>> type(b) is np.ndarray
False
>>> type(b) is np.ma.core.MaskedArray
True
```
and this means that from_array's `is_ndarray` variable (https://github.com/dask/dask/blob/2022.03.0/dask/array/core.py#L3293) is currently  False for these cases, rather than it being True so that we end up in the `# No slicing needed` clause (https://github.com/dask/dask/blob/2022.03.0/dask/array/core.py#L3306).

A solution could be to replace  `is_ndarray = type(x) is np.ndarray` with 

```python
    is_ndarray = type(x) in (np.ndarray, np.ma.core.MaskedArray)
```

I have tested this and it solves the use case I've described, and doesn't seem to make anything else fail.

If you think that this is all above board, I'm happy to make a PR with new unit tests.

Many thanks,
David

**Comment by pavithraes** [comment]
@davidhassell Thank you for opening this! @jcrist @jsignell what do you think about the proposed solution?
