### ISSUE TITLE
No matching distribution found for dask==2022.3.0 on RHEL 8

### ISSUE THREAD

**Issue by walterdolce** [dask/dask#8872]
**What happened**:
I tried to install `dask==2022.3.0` on RHEL 8, using Python 3.9.6, but got the following error:
```bash
Could not find a version that satisfies the requirement dask==2022.3.0 (from -r /home/ec2-user/requirements.txt (line 20)) (from versions: 0.7.4.linux-x86_64, 0.7.5.linux-x86_64, 0.7.6.linux-x86_64, 0.8.1.macosx-10.5-x86_64, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0rc1, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.20.1, 0.20.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.10.1, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0, 2.17.0, 2.17.1, 2.17.2, 2.18.0, 2.18.1, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2020.12.0, 2021.1.0, 2021.1.1, 2021.2.0, 2021.3.0)

No matching distribution found for dask==2022.3.0 
```

**What you expected to happen**:
Pip to install the package as usual

**Minimal Complete Verifiable Example**:
```bash
# requirements.txt
dask==2022.3.0
```

```bash
pip3 install -r requirements.txt

# ..or ..

pip3 install dask=2022.3.0
```

**Anything else we need to know?**:
The installation has been attempted from the official RHEL8 AWS AMI `ami-0ec23856b3bad62d3`

**Environment**:

- Dask version: 2022.3.0
- Python version: 3.9.6
- Operating System: RHEL 8
- Install method (conda, pip, source): pip3

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by jcrist** [comment]
Are you using a private pypi mirror, or installing from pypi itself? The wheel for `2022.3.0` exists on pypi (https://pypi.org/project/dask/2022.3.0/#files) and seems to be valid for python 3.9.

**Comment by walterdolce** [comment]
It looks like I was using the wrong executable path to pip with Ansible. Using the right one fixed the problem. Thanks!
