### ISSUE TITLE
Add string methods removeprefix and removesuffix

### ISSUE THREAD

**Issue by jorloplaz** [dask/dask#8886]
Since [Pandas 1.4.0 release](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html) (see issue https://github.com/pandas-dev/pandas/issues/36944), two new string methods are available, as a result of Python 3.9 incorporating them as native `str` methods:
* [Series.str.removeprefix](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.removeprefix.html), which applies [str.removeprefix](https://docs.python.org/3.9/library/stdtypes.html?highlight=strip#str.removeprefix) to a whole `Series`.
* [Series.str.removesuffix](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.removesuffix.html), which applies [str.removesuffix](https://docs.python.org/3.9/library/stdtypes.html?highlight=strip#str.removesuffix) to a whole `Series`.
 
So this issue is about adding these methods to Dask (which should be quite straightforward).

As a temporary workaround, they should be marked explicitly as `NotImplemented`, the same way it's done for `.str.get_dummies` (see line below):

https://github.com/dask/dask/blob/43f33a32dd5cdf77363b6ff6348b5f1a8282d28c/dask/dataframe/accessor.py#L119

Please note: **if we want to be compatible with Python < 3.9 or Pandas < 1.4, the implementation shouldn't rely on the standard library's existence of these two methods**. For example, in Python 3.8 they weren't implemented yet.

**Comment by jrbourbeau** [comment]
Thanks @jorloplaz -- I agree this would be a nice addition. Is this something you're interested in working on?

**Comment by jorloplaz** [comment]
I'll see what I can do. This'd be my 1st issue and you tagged it as a good 2nd one, but I think I can manage.
