### ISSUE TITLE
can not get records with dask cluster

### ISSUE THREAD

**Issue by RexHuang** [dask/dask#8923]
**What happened**:
we have 52millon records, we want to filter 65 records and show head(3), but we can't get records.

df2['smg_req'].value_counts().compute()
[########################################] | 100% Completed | 51min 37.7s
1999666998702281009126007712013    65

order1=df2[df2['smg_req']=='1999666998702281009126007712013']
order1.head(3)

/opt/conda/lib/python3.8/site-packages/dask/dataframe/core.py:7274: UserWarning: Insufficient elements for `head`. 3 elements requested, only 0 elements available. Try passing larger `npartitions` to `head`.

**What you expected to happen**:
should show 3 records, but got error. how can I do troubleshooting?

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
df2['smg_req'].value_counts().compute()
order1=df2[df2['smg_req']=='1999666998702281009126007712013']
order1.head(3)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.3.0
- Python version: 3.8
- Operating System: Cento7
- Install method (conda, pip, source): k8s docker hub

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by pavithraes** [comment]
@RexHuang Thanks for opening this issue! I was able to reproduce it. I think you have the first (and possibly many) partitions empty. This can happen if your original dataframe `df2` has significantly more elements, and hence more partitions. The number of partitions are the same after selection, so if `order1` has fewer elements, some partitions end up being empty.

You can use `.repartition()` to update partitions in `order1`, which would resolve this. Example:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({
    'x': list(range(5)) * 2,
    'y': range(10, 20),
    'z': range(20, 30),
})

ddf = dd.from_pandas(df, npartitions=5)

selected = ddf[ddf['x'] == 2]

selected.npartitions # 5

# selected.head(3) # UserWarning: Insufficient elements for head

selected = selected.repartition(npartitions=1) # `npartitions` value depends on the number of elements in `selected`

selected.head(3) # Works!
```

Also, this is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). If this question isn't resolved, would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse. :)

**Comment by RexHuang** [comment]
@pavithraes Thanks for your solution, it solve my problem. I think this is a usability problem, npartitions should be transparent to user, and it returns wrong result, it should be a bug.

**Comment by pavithraes** [comment]
@RexHuang Glad this is resolved!

This warning is shared when the first partition has fewer elements than what you request in `head`, which can happen in a lot of scenarios. The suggestion in the warning: `Try passing larger npartitions to head` is general and I think will work for most cases, and I see it's documented here: https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.head.html#dask.dataframe.DataFrame.head.

If you have thoughts on how we can improve the warning/docs, I'd encourage you to open a PR! 

Here's the file where it's documented: https://github.com/dask/dask/blob/bfc76afdcdc43c575a10ffefda94aaba424fe347/dask/dataframe/core.py#L1196-L1200

And, here's the warning:
https://github.com/dask/dask/blob/bfc76afdcdc43c575a10ffefda94aaba424fe347/dask/dataframe/core.py#L7353-L7354

**Comment by RexHuang** [comment]
@pavithraes OK, I agree. close this issue.
