### ISSUE TITLE
Eager calculation with `dask.array.Array.vindex`

### ISSUE THREAD

**Issue by gcaria** [dask/dask#8928]
```python
%%time

import dask.array as da
import time
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

x = da.from_array(x, chunks=2)

y = da.from_array([0, 1, 2], chunks=2)

out = x.vindex[[0, 1, 2], [0, 1, 2]] # around 1ms up to here
out = x.vindex[y, y] # adds 40ms
```

Although this returns a dask array, it needs to compute the indexers, which removes a good chunk of the advantages of laziness, and represents a hidden `compute()`.

Is this expected behaviour? I believe at least this should be explicit in the documentation.

EDIT: Changed the MRE since the one before was a terribile example. In the code I actually use, the indexers are dask arrays that come from heavy computations, and their computatuions gets triggered when simply defining `out` (i.e. calling `vindex` without `compute()`).

**Comment by jsignell** [comment]
Thanks for writing this up. It seems likely to me that dask arrays are not intentionally supported as indexers. So the simplest solution is to enforce that.

**Comment by gcaria** [comment]
Thanks for your answer @jsignell .

Out of curiosity, what's the reason why the indexer's computation can't be delayed until `compute()` is called on the `vindex` output?

**Comment by jsignell** [comment]
Oh it probably could be delayed, but it isn't currently written in a way that supports that, so the quickest and least surprising solution is to just raise if the user passes a dask array. If you are interested in digging in and making the method support dask objects as indexers, I think the culprit might be:

https://github.com/dask/dask/blob/b0e234f65577a35ae4d78e0569ee3f44235f6089/dask/array/core.py#L5245

or something in:

https://github.com/dask/dask/blob/b0e234f65577a35ae4d78e0569ee3f44235f6089/dask/array/core.py#L5262-L5273

**Comment by jsignell** [comment]
Thanks yeah. We can just leave this issue open to track the suggestion.
