### ISSUE TITLE
WorkerPlugin never called

### ISSUE THREAD

**Issue by jamesstidard** [dask/dask#8932]
**What happened**:
I'm trying to create a WorkerPlugin subclass so I can track available resources as they join or leave the worker pool. The WorkerPlugin subclass is never called for initial workers, or for new workers joining/leaving.

**What you expected to happen**:
Expecting to see the `Plugin.setup` and `Plugin.teardown` functions being called for existing workers, and for new workers.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.array as da

from dask.distributed import Client, WorkerPlugin


class MyPlugin(WorkerPlugin):
    def __init__(self, *args, **kwargs):
        pass  # the constructor is up to you

    def setup(self, worker: dask.distributed.Worker):
        print("hello", worker)

    def teardown(self, worker: dask.distributed.Worker):
        print("goodbye", worker)

    def transition(self, key, start, finish, **kwargs):
        pass

    def release_key(self, key, state, cause, reason, report):
        pass


client = Client("0.0.0.0:8786", asynchronous=False)
plugin = MyPlugin()
client.register_worker_plugin(plugin)

sum_ = da.arange(10, chunks=2).sum()
result = client.compute(sum_).result()
print(result)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: `2022.4.0`
- Python version: `3.8.12`
- Operating System: `macOS 12.3.1`
- Install method (conda, pip, source): `pipenv install dask[complete]`

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by pavithraes** [comment]
@jamesstidard Thanks for opening this issue and including a minimal example! I was able to execute it, and looks like the plugin does work? I'm writing the notes to a file because `print` would display to the workers' std-out:

```python
import dask
import dask.array as da

from dask.distributed import Client, WorkerPlugin

class MyPlugin(WorkerPlugin):
    def __init__(self, *args, **kwargs):
        pass 

    def setup(self, worker):
        with open("logs.txt", "a") as f:
            f.write(f"setting up {worker.id} \n")

    def teardown(self, worker):
        with open("logs.txt", "a") as f:
            f.write(f"tearing down {worker.id} \n")

    def transition(self, key, start, finish, **kwargs):
        pass

    def release_key(self, key, state, cause, reason, report):
        pass

client = Client(asynchronous=False)

plugin = MyPlugin()
client.register_worker_plugin(plugin)

sum_ = da.arange(10, chunks=2).sum()
result = client.compute(sum_).result()
print(result)

client.close() # to trigger teardown
```

**Comment by jamesstidard** [comment]
@pavithraes Ah, I was being silly then, I did't consider I was being called on the worker process. I had also tried to put a breakpoint in there and it never tripped, but also probably because of the separate processes.

Thanks.
