### ISSUE TITLE
set_index error

### ISSUE THREAD

**Issue by RexHuang** [dask/dask#8941]
**What happened**:
dtype_dic= {0: str, 1: str, 2: str, 3: str, 4: str, 5: str, 6: str, 7: str, 8: str, 9: str, 10: str,
            11: str, 12: str, 13: str, 14: str, 15: str, 16: str, 17: str, 18: str, 19: str, 20: str}
%time df2=dd.read_csv('/mnt/output202202/output*.csv', encoding='GBK',dtype=dtype_dic)
df2.columns[0]=['smg_req']
%time df2.set_index('smg_req')

error log:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <timed eval>:1, in <module>

File /opt/conda/lib/python3.8/site-packages/dask/dataframe/core.py:4681, in DataFrame.set_index(***failed resolving arguments***)
   4678 else:
   4679     from dask.dataframe.shuffle import set_index
-> 4681     return set_index(
   4682         self,
   4683         other,
   4684         drop=drop,
   4685         npartitions=npartitions,
   4686         divisions=divisions,
   4687         **kwargs,
   4688     )

File /opt/conda/lib/python3.8/site-packages/dask/dataframe/shuffle.py:216, in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, partition_size, **kwargs)
    213     index2 = index
    215 if divisions is None:
--> 216     divisions, mins, maxes = _calculate_divisions(
    217         df, index2, repartition, npartitions, upsample, partition_size
    218     )
    220     if (
    221         mins == sorted(mins)
    222         and maxes == sorted(maxes)
    223         and all(mx < mn for mx, mn in zip(maxes[:-1], mins[1:]))
    224         and npartitions == df.npartitions
    225     ):
    226         divisions = mins + [maxes[-1]]

File /opt/conda/lib/python3.8/site-packages/dask/dataframe/shuffle.py:41, in _calculate_divisions(df, partition_col, repartition, npartitions, upsample, partition_size)
     39 mins = partition_col.map_partitions(M.min)
     40 maxes = partition_col.map_partitions(M.max)
---> 41 divisions, sizes, mins, maxes = compute(divisions, sizes, mins, maxes)
     42 divisions = methods.tolist(divisions)
     43 if type(sizes) is not list:

File /opt/conda/lib/python3.8/site-packages/dask/base.py:575, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    572     keys.append(x.__dask_keys__())
    573     postcomputes.append(x.__dask_postcompute__())
--> 575 results = schedule(dsk, keys, **kwargs)
    576 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File /opt/conda/lib/python3.8/site-packages/distributed/client.py:3015, in Client.get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   3013         should_rejoin = False
   3014 try:
-> 3015     results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   3016 finally:
   3017     for f in futures.values():

File /opt/conda/lib/python3.8/site-packages/distributed/client.py:2167, in Client.gather(self, futures, errors, direct, asynchronous)
   2165 else:
   2166     local_worker = None
-> 2167 return self.sync(
   2168     self._gather,
   2169     futures,
   2170     errors=errors,
   2171     direct=direct,
   2172     local_worker=local_worker,
   2173     asynchronous=asynchronous,
   2174 )

File /opt/conda/lib/python3.8/site-packages/distributed/utils.py:309, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    307     return future
    308 else:
--> 309     return sync(
    310         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    311     )

File /opt/conda/lib/python3.8/site-packages/distributed/utils.py:376, in sync(loop, func, callback_timeout, *args, **kwargs)
    374 if error:
    375     typ, exc, tb = error
--> 376     raise exc.with_traceback(tb)
    377 else:
    378     return result

File /opt/conda/lib/python3.8/site-packages/distributed/utils.py:349, in sync.<locals>.f()
    347         future = asyncio.wait_for(future, callback_timeout)
    348     future = asyncio.ensure_future(future)
--> 349     result = yield future
    350 except Exception:
    351     error = sys.exc_info()

File /opt/conda/lib/python3.8/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File /opt/conda/lib/python3.8/site-packages/distributed/client.py:2030, in Client._gather(self, futures, errors, direct, local_worker)
   2028         exc = CancelledError(key)
   2029     else:
-> 2030         raise exception.with_traceback(traceback)
   2031     raise exc
   2032 if errors == "skip":

File /opt/conda/lib/python3.8/site-packages/dask/optimization.py:990, in __call__()
    988 if not len(args) == len(self.inkeys):
    989     raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 990 return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))

File /opt/conda/lib/python3.8/site-packages/dask/core.py:149, in get()
    147 for key in toposort(dsk):
    148     task = dsk[key]
--> 149     result = _execute_task(task, cache)
    150     cache[key] = result
    151 result = _execute_task(out, cache)

File /opt/conda/lib/python3.8/site-packages/dask/core.py:119, in _execute_task()
    115     func, args = arg[0], arg[1:]
    116     # Note: Don't assign the subtask results to a variable. numpy detects
    117     # temporaries by their reference count and can execute certain
    118     # operations in-place.
--> 119     return func(*(_execute_task(a, cache) for a in args))
    120 elif not ishashable(arg):
    121     return arg

File /opt/conda/lib/python3.8/site-packages/dask/utils.py:39, in apply()
     37 def apply(func, args, kwargs=None):
     38     if kwargs:
---> 39         return func(*args, **kwargs)
     40     else:
     41         return func(*args)

File /opt/conda/lib/python3.8/site-packages/dask/dataframe/core.py:6330, in apply_and_enforce()
   6328 func = kwargs.pop("_func")
   6329 meta = kwargs.pop("_meta")
-> 6330 df = func(*args, **kwargs)
   6331 if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   6332     if not len(df):

File /opt/conda/lib/python3.8/site-packages/dask/utils.py:1021, in __call__()
   1020 def __call__(self, __obj, *args, **kwargs):
-> 1021     return getattr(__obj, self.method)(*args, **kwargs)

File /opt/conda/lib/python3.8/site-packages/pandas/core/generic.py:11222, in max()
  11202 @doc(  # type: ignore[misc]
  11203     _num_doc,
  11204     desc="Return the maximum of the values over the requested axis.\n\n"
   (...)
  11220     **kwargs,
  11221 ):
> 11222     return NDFrame.max(self, axis, skipna, level, numeric_only, **kwargs)

File /opt/conda/lib/python3.8/site-packages/pandas/core/generic.py:10679, in max()
  10671 def max(
  10672     self,
  10673     axis: Axis | None | lib.NoDefault = lib.no_default,
   (...)
  10677     **kwargs,
  10678 ):
> 10679     return self._stat_function(
  10680         "max",
  10681         nanops.nanmax,
  10682         axis,
  10683         skipna,
  10684         level,
  10685         numeric_only,
  10686         **kwargs,
  10687     )

File /opt/conda/lib/python3.8/site-packages/pandas/core/generic.py:10649, in _stat_function()
  10639     warnings.warn(
  10640         "Using the level keyword in DataFrame and Series aggregations is "
  10641         "deprecated and will be removed in a future version. Use groupby "
   (...)
  10644         stacklevel=find_stack_level(),
  10645     )
  10646     return self._agg_by_level(
  10647         name, axis=axis, level=level, skipna=skipna, numeric_only=numeric_only
  10648     )
> 10649 return self._reduce(
  10650     func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  10651 )

File /opt/conda/lib/python3.8/site-packages/pandas/core/series.py:4471, in _reduce()
   4467     raise NotImplementedError(
   4468         f"Series.{name} does not implement {kwd_name}."
   4469     )
   4470 with np.errstate(all="ignore"):
-> 4471     return op(delegate, skipna=skipna, **kwds)

File /opt/conda/lib/python3.8/site-packages/pandas/core/nanops.py:155, in f()
    153         result = alt(values, axis=axis, skipna=skipna, **kwds)
    154 else:
--> 155     result = alt(values, axis=axis, skipna=skipna, **kwds)
    157 return result

File /opt/conda/lib/python3.8/site-packages/pandas/core/nanops.py:410, in new_func()
    407 if datetimelike and mask is None:
    408     mask = isna(values)
--> 410 result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
    412 if datetimelike:
    413     result = _wrap_results(result, orig_values.dtype, fill_value=iNaT)

File /opt/conda/lib/python3.8/site-packages/pandas/core/nanops.py:1043, in reduction()
   1041         result = np.nan
   1042 else:
-> 1043     result = getattr(values, meth)(axis)
   1045 result = _maybe_null_out(result, axis, mask, values.shape)
   1046 return result

File /opt/conda/lib/python3.8/site-packages/numpy/core/_methods.py:40, in _amax()
     38 def _amax(a, axis=None, out=None, keepdims=False,
     39           initial=_NoValue, where=True):
---> 40     return umr_maximum(a, axis, None, out, keepdims, initial, where)

TypeError: '>=' not supported between instances of 'float' and 'str'
**What you expected to happen**:
it should set_index sucesss.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
dtype_dic= {0: str, 1: str, 2: str, 3: str, 4: str, 5: str, 6: str, 7: str, 8: str, 9: str, 10: str,
            11: str, 12: str, 13: str, 14: str, 15: str, 16: str, 17: str, 18: str, 19: str, 20: str}
%time df2=dd.read_csv('/mnt/output202202/output*.csv', encoding='GBK',dtype=dtype_dic)
df2.columns[0]=['smg_req']
%time df2.set_index('smg_req')

```

**Anything else we need to know?**:

**Environment**:

Dask version: 2022.3.0
Python version: 3.8
Operating System: Cento7
Install method (conda, pip, source): k8s docker hub

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by pavithraes** [comment]
@RexHuang Thanks for the question. I was able to reproduce this when the column I use to `set_index` has `NaN` values. You can do `df2 = df2.dropna()` before `set_index`, which should fix this. :)

Please feel free to close this issue if this resolves your question!
