### ISSUE TITLE
dask with processes scheduler only use 10 CPUs

### ISSUE THREAD

**Issue by dongspy** [dask/dask#8962]
**What happened**:
My HPC has 32 CPUs. Seting dask config with pool=Pool(32), or xx.compute(scheduler='processes', num_workers=32) ，while dask only use 10 CPUs actually
![dask_cpu](https://user-images.githubusercontent.com/32101973/164421417-75a35928-54b7-4cf6-b494-7034c2b41837.png)

**What you expected to happen**:
dask use all my CPUs to compute.

```python
# Put your MCVE code here
dask.config.set(pool=Pool(32), scheduler="processes")
xx = dask.dataframe.from_pandas(
   df, npartitions=100
)
yy = xx.compute()
# OR
yy = xx.compute(scheduler="processes", num_workers=32)
```

**Anything else we need to know?**:

**Environment**:

- Dask version:  2022.01.1
- Python version: Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
- Operating System: CentOS Linux release 7.3.1611 (Core)
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment]
@dongspy Welcome to Dask, and thanks for opening this issue!

The [multiprocessing scheduler (scheduler="processes")](https://docs.dask.org/en/stable/scheduling.html#local-processes) is a single-machine scheduler, and isn't suited for an HPC setup. I'd suggested using the [distributed scheduler](https://docs.dask.org/en/stable/deploying-python.html), or checking out [these deployment options](https://docs.dask.org/en/stable/deploying-hpc.html). Please let us know if you see un-used cores even using the distributed scheduler!

Also, this is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). If this question isn't resolved, would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse. :)

**Comment by bryanwweber** [comment]
@dongspy just to add to the comment from @pavithraes, even if this is a single node in an HPC that has 32 CPU cores, I'd still recommend using the `LocalCluster` from `distributed`.

**Comment by pavithraes** [comment]
I'll go ahead and close this due to lack of activity, but please feel free to re-open it if needed!
