### ISSUE TITLE
parquet "date" type not coverting correctly to datetime64 when reading parquet

### ISSUE THREAD

**Issue by radocisar** [dask/dask#8968]
original parquet data types:
...
|-- new_value_time: timestamp (nullable = true)
|-- old_value: double (nullable = true)
|-- snapshot_date: date (nullable = true)

In:
```
table = dd.read_parquet(
            path=parquets,
            engine="pyarrow-dataset"
        )

table.dtypes
```
Out:
new_value_time            datetime64[ns]
old_value                        float64
snapshot_date                category

parquet `date` type converts to `category` or `object` but not to datetime64 or other date type. This [Stackoverflow](https://stackoverflow.com/questions/59754794/dask-dataframe-converts-undelying-parquet-files-index-from-datetime64-to-object) suggests it's a bug.

Thank you.

**Comment by pavithraes** [comment]
@radocisar Thanks for opening this issue! I'm not able to reproduce this, would you be able to share a minimal example? Also, which Dask version are you running? There's a lot of ongoing work around parquet, so I'd also suggest upgrading versions to see if that helps!

You can use `dask.dataset` to create some temporary data, here's my example for reference:

```python
import dask
import dask.dataframe as dd

ddf = dask.datasets.timeseries()
ddf = ddf.reset_index()
ddf.dtypes

dd.to_parquet(ddf, "temp_parquet_dataset", engine="pyarrow", write_metadata_file=False)

ddf_new = dd.read_parquet("temp_parquet_dataset", engine="pyarrow")
ddf_new.dtypes
```

**Comment by pavithraes** [comment]
I'll close this issue for now due to lack of activity, but please feel free to re-open it if you have a reproducible example that you can share!
