### ISSUE TITLE
Cannot use shared memory with `dask.distributed.Client.map()`

### ISSUE THREAD

**Issue by fAndreuzzi** [dask/dask#8974]
For my use case I'd like to take advantage of shared memory among a group of threads in order to avoid some intermediate writes to intermediate matrices and jump directly to the output matrix. I do not have race conditions since each thread writes to a specific row (or set of rows). 

However it does not seem to be working with `Client.map()`, since the output matrix appears to be untouched at the end of the run. My impression is that each thread receives its own version of the output matrix, thus making any modification local to that thread.

Perhaps I'm doing something wrong? I visited the documentation page about shared memory, but I didn't get any insight from that reading.

```python
from dask.distributed import Client
import numpy as np

def fill(idx, matrix):
    matrix[idx] = idx
    print(idx, matrix[idx])

if __name__ == '__main__':
    client = Client()

    N = 20
    m = np.zeros((N, 10))
    client.gather(client.map(fill, range(N), matrix=m))

    print('-----')
    print('11th row is', m[10])
    print(np.count_nonzero(m))
```
Output:
```
0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
15 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
1 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
16 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
10 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
5 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
2 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
17 [17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]
3 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
4 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
6 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
18 [18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]
11 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
7 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
19 [19. 19. 19. 19. 19. 19. 19. 19. 19. 19.]
8 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
12 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
9 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
13 [13. 13. 13. 13. 13. 13. 13. 13. 13. 13.]
14 [14. 14. 14. 14. 14. 14. 14. 14. 14. 14.]
-----
11th row is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0
```

**Environment**:

- Dask version: 2022.4.1
- Python version: Python 3.9.12
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
By default Dask creates several processes, and recreates the data in each one.  If you want to use a single-shared-memory-process then set the `processes=False` flag

```python
from dask.distributed import Client
import numpy as np

def fill(idx, matrix):
    matrix[idx] = idx
    print(idx, matrix[idx])

if __name__ == '__main__':
    client = Client(processes=False)

    N = 20
    m = np.zeros((N, 10))
    client.gather(client.map(fill, range(N), matrix=m))

    print('-----')
    print('11th row is', m[10])
    print(np.count_nonzero(m))
```

```
0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
2 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
3 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
4 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
5 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
6 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
7 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
8 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
9 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
10 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
11 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
12 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
13 [13. 13. 13. 13. 13. 13. 13. 13. 13. 13.]
15 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
17 [17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]
19 [19. 19. 19. 19. 19. 19. 19. 19. 19. 19.]
16 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
14 [14. 14. 14. 14. 14. 14. 14. 14. 14. 14.]
18 [18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]
-----
11th row is [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
190
```

**Comment by fAndreuzzi** [comment]
My bad, I assumed that `processes` is `False` by default. Thank you very much.

One more thing @mrocklin, do you expect bad performance from such a pattern? I have two versions of my code, one uses shared memory and one doesn't, and the shared memory version performs worse than the other. I expected the opposite.

**Comment by mrocklin** [comment]
I would consider it to be a bit dangerous.  For example, Dask reserves the
right to run functions twice if something strange happens, which might
produce inconsistent results.

In general with parallel computing folks try to avoid functions that rely
on side-effects and global state, and instead try to rewrite things to use
pure functions.

**Comment by mrocklin** [comment]
But, to your particular question around performance, no, I can't easily
explain what you're seeing.

**Comment by fAndreuzzi** [comment]
Thank you for the insights @mrocklin, I'm closing the issue.
