### ISSUE TITLE
dask.array.map_blocks doesn't use meta shape

### ISSUE THREAD

**Issue by oarcher** [dask/dask#8996]
In the below example, the `blocked` function is a simple function that stacks input arrays, so it create a new dimension. 

The `dask.array.map_blocks` documentation says about meta keywords:

>The meta of the output array, when specified  is expected to be an array of the same type and dtype of that returned when calling .compute()

But the meta shape seems to not be used.

```python
import dask.array as da
da1 = da.ones((4,3))
da2 = da.ones((4,3)) + 2
def blocked(np1, np2):
    return np.stack([np1,np2], axis=0)

meta=da.stack([da1,da2], axis=0)
result = da.map_blocks(blocked, da1,da2, meta=meta)
```

input da has shape `(4,3)`, and meta has correct shape of `(2,4,3)`

I was expecting that the result shape is the same as the meta shape, but it's still `(4,3)`

however, if I call `result.compute()`, it has the correct shape `(2,4,3)`

but as the result shape is not the same as the meta shape before `.compute()`, I can't slice result using
```python
dares1 = result[0,:,:]
dares2 = result[1,:,:]
```
(it raise `IndexError: Too many indices for array`)

I've tried to use `new_axis=0`, but the created axis has len 1, not 2 as expected.

dask version '2022.02.1'

**Comment by pavithraes** [comment]
@oarcher Thanks for this question!

I believe `meta` is just a suggestion to Dask and is mainly used until Dask infers the output structure from real data. Dask does not coerce the output to align with `meta`. 

You're exactly right that we need to specify `new_axis=0` here -- but Dask still doesn't really know the actual shape of the output, it just knows there's another axis to consider. Doing `result.compute_chunk_sizes()` fixes that:

```python
import numpy as np
import dask.array as da

da1 = da.ones((4,3))
da2 = da.ones((4,3)) + 2

def blocked(np1, np2):
    return np.stack([np1,np2], axis=0)

result = da.map_blocks(blocked, da1, da2, meta=np.array(()), new_axis=0)

result.shape # (1, 4, 3)

result.compute_chunk_sizes()

result.shape # (2, 4, 3)

dares1 = result[0,:,:]
dares2 = result[1,:,:]
```

Does this help?

**Comment by oarcher** [comment]
Yes using `new_axis=0` and `.compute_chunk_sizes()` helps !

But the documentation of the `meta` keyword is not clear in the documentation.

In this specific case, I've finally used `da.apply_gufunc`, because my original problem was that `map_blocks` is unable to deal with multiple outputs arguments (https://github.com/dask/dask/issues/72)

```python
def gufunc(arg1, arg2):
    return arg1 + 1, arg2 + 2
res1, res2 = da.apply_gufunc(gufunc , '(n),(n)->(n),(n)' , da1, da2)  
res1 # (4,3)
res2 # (4,3)
```

It's ok for me to close the issue.

**Comment by pavithraes** [comment]
@oarcher Thanks for sharing your `apply_gufunc` solution! I agree that `meta` can be documented more clearly in general, and there's [this issue around writing a blog post](https://github.com/dask/dask-blog/issues/129) where we're tracking this. :)
