### ISSUE TITLE
da.unique:  TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Nandeeshkkm7** [dask/dask#9004]
a=len(da.unique(da.array([1,2,2,2,2,3])))
it gives following error
TypeError: 'float' object cannot be interpreted as an integer

**Comment by bryanwweber** [comment]
Hi, welcome to Dask. Please fill in _all_ the information that the Bug Report template asks for, particularly your Dask version. Please also include a [minimal, complete, verifiable example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) code to your post. That really helps us reproduce the issue to work out what to do. Thank you!

Extrapolating from your example, I do not get the same error, but I do get an error:

```
In [1]: import dask.array as da

In [2]: len(da.unique(da.array([1, 1, 1, 2, 2, 2])))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 len(da.unique(da.array([1, 1, 1, 2, 2, 2])))

File ~/mambaforge/envs/parquet/lib/python3.9/site-packages/dask/array/core.py:1503, in Array.__len__(self)
   1498 if np.isnan(self.chunks[0]).any():
   1499     msg = (
   1500         "Cannot call len() on object with unknown chunk size."
   1501         f"{unknown_chunk_message}"
   1502     )
-> 1503     raise ValueError(msg)
   1504 return int(sum(self.chunks[0]))

ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`
```

**Comment by pavithraes** [comment]
I'll go ahead and close this due to lack of activity, but please feel free to re-open it if needed!
