### ISSUE TITLE
Make it easier to manually create DataFrames

### ISSUE THREAD

**Issue by MrPowers** [dask/dask#9009]
We often need to create [Minimal Complete Verifiable Examples](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) with Dask DataFrames for blog posts, questions, etc.

Here's how Dask allows you to make these examples currently:

```python
import pandas as pd

pandas_df = pd.DataFrame(
    {"num1": [1, 2, 3, 4], "num2": [7, 8, 9, 10]},
)
df = dd.from_pandas(pandas_df, npartitions=2)
```

This is confusing for some users.  They are not sure why pandas needs to be imported and can struggle making the pandas => Dask connection.

The following syntax would make the MCVEs shorter and easier to understand:

```python
import dask.dataframe as dd

ddf = dd.DataFrame(
    {"num1": [1, 2, 3, 4], "num2": [7, 8, 9, 10]},
    npartitions=2,
)
```

Let me know if this suggestion sounds good and I can submit a PR.  Or perhaps there is already a way to directly create a Dask DataFrame in a similar manner?

**Comment by pavithraes** [comment]
@jrbourbeau What do you think about this feature?

**Comment by pavithraes** [comment]
Noting as related: https://github.com/dask/dask/issues/6577#issuecomment-1113963312 :)

**Comment by jrbourbeau** [comment]
Thanks @MrPowers, I think this is a reasonable request but wouldn't want to see us point users directly to the `dd.DataFrame` constructor as it's a fairly low-level class constructor and we prefer to route users towards more friendly methods like `dd.read_parquet`, `dd.from_delayed`, etc.

That said, adding a new `dd.from_dict` method similar to pandas' [`pd.from_dict`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html) seems like a nice way to accomplish what you're after while also sticking with an existing DataFrame API. Adding this new method would be my personal preference

**Comment by jrbourbeau** [comment]
Also, there is a [`dask.datasets` module](https://github.com/dask/dask/blob/298112115f63bd8846527bfafae2886999f0f4ec/dask/datasets.py) where we maintain a couple of utility functions for generating demo DataFrames. These might help in some situations, though not all, I'm mostly just mentioning as an FYI.

**Comment by MrPowers** [comment]
@jrbourbeau - `dd.from_dict` sounds like a great approach to me.  I'll prep a PR.  Thanks!
