### ISSUE TITLE
map_overlap with multiple dask dataframes

### ISSUE THREAD

**Issue by faulaire** [dask/dask#9042]
Hi,

I tried to use dask.dataframe.rolling.map_overlap function with multiple dask dataframes. I was expecting the same behavior as map_partitions but unlike map_partitions, only the first dask dataframe is materialized at execution time (https://docs.dask.org/en/latest/generated/dask.dataframe.rolling.map_overlap.html).

I would like to know if we could have the same behavior on map_overlap ?

As an example, I would like to write:

```
ddf1 = dask.dataframe.from_pandas(...)
ddf2 = dask.dataframe.from_pandas(...)

def diff(dd1, dd2):
	return dd1 - dd2
	
dask.dataframe.rolling.map_overlap(diff, ddf1, ddf2, before=5, after=5)
```

What do you think about it ?

Any ideas to address this kind of issues are welcomed :)

Thanks for your help,

Fabien

**Comment by pavithraes** [comment]
@faulaire Welcome to Dask, and thanks for reporting this! It does look like using multiple DataFrames isn't implemented in `map_overlap`, but it might be a reasonable case to support. 

One non-ideal workaround for simple operations could be to [convert the DataFrames to Dask Arrays](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.to_dask_array.html), and use [`da.map_overlap`](https://docs.dask.org/en/stable/generated/dask.array.map_overlap.html) which does allow for multiple Arrays. I'll keep looking into this!

**Comment by faulaire** [comment]
Hi @pavithraes , ok, thanks for your answer.

I already started to implement the support for multiple dataframes on my side. I need some times to tests all cases but I'll raise a pull request before the end of this month.

**Comment by pavithraes** [comment]
> I already started to implement the support for multiple dataframes on my side. I need some times to tests all cases but I'll raise a pull request before the end of this month.

Thank you! Looking forward to it!

**Comment by faulaire** [comment]
I'd like to change the API for map_overlap function. Because it can now accept multiple dataframes, it should have the same signature as map_partitions:

My proposal is;

```python
def map_overlap(
    func,
    before,
    after,
    *args,
    meta=no_default,
    enforce_metadata=True,
    transform_divisions=True,
    align_dataframes=True,
    **kwargs,
):
```

What's your opinion about this change ? 

Moreover, because I don't want to copy/paste code from map_partitions, is it ok if I create some helper functions from map_partitions code in order to share code to handle meta, partition alignement... ?

**Comment by faulaire** [comment]
Hi,

This pull request (draft) : #9065 implement multi dataframe handling.

Can you please have a look ?

I was not able to materialize arguments passed in kwargs, if someone can help me on this point it would be great.

Thanks

**Comment by faulaire** [comment]
@pavithraes, my fault. I reorganized my forked of dask and remove the existing one for a new one with multiple branches (I'm not a git expert, I'm sure it's possible to do it in a smoother way). I'll raise a new PR soon with some changes. The first one was buggy in distributed mode.

**Comment by faulaire** [comment]
All features of map_partitions are now implemented in map_overlap. But a lot of codes are duplicated between the two files.
I could only keep the part of creating new dask dataframe (with previous and nexts parts) and call a map_partitions with the a collection of modified args.
