### ISSUE TITLE
Fuzzing integration by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [dask/dask#9063]
Hi,

Would you be interested in integrating continuous fuzzing of dask by way of OSS-Fuzz? Fuzzing is a form of test-generation technique and has been used to catch many bugs in memory unsafe languages. There is currently efforts to fuzz more memory safe languages, and in this context I was wondering if you would be interested in getting Dask fuzzed?

In this PR I have integrated Dask with OSS-Fuzz: https://github.com/google/oss-fuzz/pull/7688 Specifically, created the necessary logic from an OSS-Fuzz perspective to integrate Dask. The first goal will be to increase the coverage to cover as much of the Dask code as possible. Down the line it is preferable to have the fuzzers upstream but it can be convenient to have on OSS-Fuzz to begin with.

Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid. The fuzzing set up on the OSS-Fuzz side relies on Atheris fuzzer (https://github.com/google/atheris) to perform the fuzzing.

If you would like to integrate, the only thing I need is as list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by pavithraes** [comment]
@DavidKorczynski Thank you for sharing!

@jrbourbeau @jcrist What do you think?

**Comment by jcrist** [comment]
Thanks for opening this @DavidKorczynski, and apologies for the delayed response.

While I think fuzzing is a useful strategy, dask doesn't have a lot of surface area where fuzzing makes sense IMO (and places where it does we often already do have some form of randomized tests). The functions covered in your initial PR already have excellent test coverage in repo, and the fuzz-tests there don't test correctness, only for lack of errors. I (personally) don't see a large benefit from having dask fuzz tests in an upstream repo, which will increase maintenance costs for both our team and the OSS-fuzz project.

**Comment by jcrist** [comment]
Thanks for being understanding (and for doing all this work). I have no problem with you doing work external to the dask project, please let us know if you find any bugs!  Closing.
