### ISSUE TITLE
How do I initialize processes in `dask`'s multi-process scheduler?

### ISSUE THREAD

**Issue by ParticularMiner** [dask/dask#9086]
The following code-snippet works for single and multi-threaded schedulers.  But not for multi-process schedulers.  And probably not for distributed-memory schedulers either.
```python
pims.ImageIOReader.class_priority = 100  # we set this very high in order to force dask-image's imread() to use this reader [via pims.open()]
rgb_frames = dask_image.imread.imread('/path/to/video/file.mpg')  # uses ImageIOReader

rgb_frames.compute(scheduler='single-threaded')  # works
rgb_frames.compute(scheduler='threading')  # works
rgb_frames.compute(scheduler='processes')  # does not work
```

_Originally posted by @ParticularMiner in https://github.com/dask/dask-image/issues/262#issuecomment-1125729240_

**Comment by jakirkham** [comment]
Quoting comment ( https://github.com/dask/dask-image/issues/262#issuecomment-1125796926 ): 

> Yeah the single and thread schedulers share the same process memory. So if the priority is set in that process, that is sufficient. All workers view that same memory.
>
> With the process scheduler, different processes have their own process memory space and it isn't shared. Setting information in one does not necessarily get communicated to another. So one would need to do this during process startup. This is [handled here]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L239-L247 ). The simplest solution is to just [provide your own `ProcessPoolExecutor`]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L180 ), which would have whatever initializer one used to created the `Executor`. Would [follow this for guidance on setting it up]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L183-L195 ).
>
> An alternative solution, would be to add some kind of `dask.config` parameter ([like these]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L179-L181 )), which would allow one to [change the initializer]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L193-L195 ). This could be a totally different function that is run instead. Or perhaps one that gets run as part of [the initializer process]( https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/multiprocessing.py#L239 ) just later on in that function. This is probably a reasonable PR to do if you wanted to go that way.
>
> Distributed would likely have the same issue for the same reason. However there are a lot more options there. For example [preload scripts]( https://docs.dask.org/en/stable/how-to/customize-initialization.html#preload-scripts ) would work. If you are planning on doing process based execution, would suggest just using Distributed. It has a centralized scheduler, the ability to work with `Future`s, a rich diagnostic dashboard, etc. Generally this will be a better experience. Also will be easier to go from there to a cluster, the cloud, etc. as needed.

**Comment by jakirkham** [comment]
PR ( https://github.com/dask/dask/pull/9087 ) is an attempt to allow configuration of the initializer in Dask
