### ISSUE TITLE
Improving bug report template

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask#9099]
This is a suggestion to simplify reporting the dask version in the issue template by providing a suggested code snippet to run (in the **Environment** section of the issue template):

```python
import dask; print("- Dask version:", dask.__version__)
import sys; print("- Python version:", sys.version)
```

**Comment by jrbourbeau** [comment]
Thanks for the suggestion @SultanOrazbayev. I'd go a step further and follow the lead from other projects like `pandas` / `xarray` and add a `dask.show_versions()` method which outputs all the version/system-related information we want included when users open an issue. That would let us replace that section in the template with something like "Include the output of `dask.show_versions()`".

Is this something you're interested in working on? (no obligation though)

**Comment by SultanOrazbayev** [comment]
Thanks, James, yes, I am interested in this!

**Comment by mrocklin** [comment]
I'll propose an alternative which is that we just don't ask people for this
information.  I almost never provide it, and I find it useful only a small
fraction of the time.  Should we reconsider asking folks to provide this?

**Comment by jrbourbeau** [comment]
> I am interested in this!

Great, getting a bit more specific it would be nice to have output like the following:

```python
>>> import dask
>>> dask.show_versions()
Python: 3.9.6
Platform: darwin
Versions:
- dask: X.Y.Z
- distributed: X.Y.Z
- numpy: X.Y.Z
- pandas: X.Y.Z
- cloudpickle: X.Y.Z
- fsspec: X.Y.Z
- bokeh: X.Y.Z
- fastparquet: X.Y.Z
- pyarrow: X.Y.Z
- zarr: X.Y.Z
```

> Should we reconsider asking folks to provide this?

I find myself asking questions like "What version of `dask` are you using? Have you tried the latest release yet?" / "What version of `pandas` / `numpy` / `pyarrow` / ... are you using?" often. I think something like `dask.show_versions()` would allow us to answer several of those questions proactively without users needing to do much. That said, we don't require any of this information when opening an issue, so folks can still feel free to not include it, but it streamlines the process for those that do
