### ISSUE TITLE
Docs Not Updating?

### ISSUE THREAD

**Issue by quasiben** [dask/dask#9101]
In two recent PRs:https://github.com/dask/dask/pull/8911 and https://github.com/dask/dask/pull/9001/ docs were changed but those changes are not present at: https://docs.dask.org/en/stable/ .  For example, changes in https://github.com/dask/dask/pull/8911 should be present in https://docs.dask.org/en/stable/dataframe-api.html (`from_map`)

**Comment by jcrist** [comment]
IIRC, docs are only released on `latest` until a release, when they're promoted to stable. See https://docs.dask.org/en/latest/generated/dask.dataframe.from_map.html#dask.dataframe.from_map for `from_map`.

**Comment by quasiben** [comment]
Ah, forgot we switched to releases.  Sorry for the noise
