### ISSUE TITLE
2022.04.0: `dask` needs some modules which I cannot find

### ISSUE THREAD

**Issue by kloczek** [dask/dask#9107]
Trying to execute pytest based test suite I found that I need few modules which I cannot find or what I'm finding on pypi looks like is not useable
```console
+ PYTHONDONTWRITEBYTECODE=1
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dask-2022.04.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dask-2022.04.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
ImportError while loading conftest '/home/tkloczko/rpmbuild/BUILD/dask-2022.04.0/conftest.py'.
conftest.py:3: in <module>
    import dask
dask/__init__.py:1: in <module>
    from dask import config, datasets
dask/datasets.py:3: in <module>
    from dask.utils import import_required
dask/utils.py:24: in <module>
    import tlz as toolz
E   ModuleNotFoundError: No module named 'tlz'
```
On pypi I found only https://pypi.org/project/tlz/

**Comment by pavithraes** [comment]
@kloczek Welcome! That error refers to the [`toolz` module](https://pypi.org/project/toolz/), so `pip install toolz` should work. Also, on a general note, you can install Dask with: `python -m pip install "dask[complete]"` to install all the necessary dependencies, including `toolz`. :)

**Comment by jrbourbeau** [comment]
Closing as `toolz` is a required dependency for `dask` 

https://github.com/dask/dask/blob/0f5914401441d438321250c29db5a59d62afd5ef/setup.py#L40

**Comment by kloczek** [comment]
Thank you 👍 😃
