### ISSUE TITLE
dask/array/NUMPY_LICENSE.txt not included in PyPI distributions

### ISSUE THREAD

**Issue by musicinmybrain** [dask/dask#9112]
**What happened**:

The GitHub source contains `dask/array/NUMPY_LICENSE.txt`. This makes sense, because some code is copied or forked from numpy, and under the BSD license terms this license and copyright text must be reproduced with distributions in source or binary form.

However, the PyPI sdist and bdist/wheel files do not contain this license file.

**What you expected to happen**:

PyPI distributions contain `dask/array/NUMPY_LICENSE.txt`.

**Minimal Complete Verifiable Example**:

```bash
$ curl -L https://files.pythonhosted.org/packages/d5/61/2ab5b87c89a91e96aa2039722b60570d4cae4961afa47a8f3dacc66bbcd9/dask-2022.5.0.tar.gz | tar -tzv | grep -F NUMPY_LICENSE.txt
# (no output)
$ python3 -m venv _e
$ . _e/bin/activate
(_e) $ pip install dask
Collecting dask
# […]
Successfully installed cloudpickle-2.1.0 dask-2022.5.0 fsspec-2022.5.0 locket-1.0.0 packaging-21.3 partd-1.2.0 pyparsing-3.0.9 pyyaml-6.0 toolz-0.11.2
(_e) $ find _e/lib/python3.10/site-packages/dask* -name NUMPY_LICENSE.txt
# (no output)
```

**Anything else we need to know?**:

It should be sufficient to add `dask/array/NUMPY_LICENSE.txt` to `metadata.license_files` in `setup.cfg`. I will follow up with a PR.

**Environment**:

- Dask version: any (2022.5.0, or current `main`)
- Python version: any (3.10.4)
- Operating System: any (Fedora Linux 36)
- Install method (conda, pip, source): any except GitHub source

**Comment by pavithraes** [comment]
@musicinmybrain Thanks for reporting, and opening a PR!
