### ISSUE TITLE
PyPI sdist lacks conftest.py

### ISSUE THREAD

**Issue by musicinmybrain** [dask/dask#9114]
**What happened**:

The PyPI sdist contains tests (`dask/tests/`), but it lacks `conftest.py`, so a number of tests fail that should not. For example, tests that use the `shuffle_method` fixture, fail with:

```
E       fixture 'shuffle_method' not found
```

**What you expected to happen**:

If PyPI sdists contain tests, then they should contain `conftest.py`.

**Minimal Complete Verifiable Example**:

```bash
$ curl -L -O https://files.pythonhosted.org/packages/d5/61/2ab5b87c89a91e96aa2039722b60570d4cae4961afa47a8f3dacc66bbcd9/dask-2022.5.0.tar.gz
$ tar -xzf dask-2022.5.0.tar.gz
$ python3 -m venv _e
$ . _e/bin/activate
(_e) $ cd dask-2022.5.0/
(_e) $ pip install -e ".[complete,test]"
[…]
Successfully installed MarkupSafe-2.1.1 attrs-21.4.0 bokeh-2.4.3 cfgv-3.3.1 click-8.1.3 cloudpickle-2.1.0 dask-2022.5.0 distlib-0.3.4 distributed-2022.5.0 execnet-1.9.0 filelock-3.7.0 fsspec-2022.5.0 heapdict-1.0.1 identify-2.5.1 iniconfig-1.1.1 jinja2-3.1.2 locket-1.0.0 msgpack-1.0.3 nodeenv-1.6.0 numpy-1.22.4 packaging-21.3 pandas-1.4.2 partd-1.2.0 pillow-9.1.1 platformdirs-2.5.2 pluggy-1.0.0 pre-commit-2.19.0 psutil-5.9.1 py-1.11.0 pyparsing-3.0.9 pytest-7.1.2 pytest-forked-1.4.0 pytest-rerunfailures-10.2 pytest-xdist-2.5.0 python-dateutil-2.8.2 pytz-2022.1 pyyaml-6.0 six-1.16.0 sortedcontainers-2.4.0 tblib-1.7.0 toml-0.10.2 tomli-2.0.1 toolz-0.11.2 tornado-6.1 typing-extensions-4.2.0 urllib3-1.26.9 virtualenv-20.14.1 zict-2.2.0
(_e) $ pytest
[…]
=========== 1 failed, 7092 passed, 875 skipped, 88 xfailed, 2691 warnings, 965 errors in 501.68s (0:08:21) ===========
# Note 965 errors due to missing conftest.py
```

**Anything else we need to know?**:

This is relevant to Linux distribution packaging, which wants to build wheels from source and run the tests, but (at least in Fedora Linux) which would prefer to use PyPI sdists instead of GitHub archives where possible.

It should be sufficient to add `onftest.py` to `MANIFEST.in`. I will follow up with a PR.

**Environment**:

- Dask version: any (2022.5.0, or current `main`)
- Python version: any (3.10.4)
- Operating System: any (Fedora Linux 36)
- Install method (conda, pip, source): PyPI sdist

**Comment by QuLogic** [comment]
This is a duplicate of #8475.

**Comment by musicinmybrain** [comment]
> This is a duplicate of #8475.

Thanks! Since it seems Dask will continue to distribute tests in the PyPI sdist (#8478 was not merged, but instead the tests were moved to the top level in #8662), should I adjust my PR #9115 to reference #8475?

**Comment by musicinmybrain** [comment]
Closing as a duplicate of #8475.
