### ISSUE TITLE
Dask[dataframe] "requirements are not installed" on AWS lambda

### ISSUE THREAD

**Issue by raghaviravi92** [dask/dask#9132]
Trying to use dask.dataframe in AWS lambda. But in-spite of bundling dask.dataframe as part of bundle, I repeatedly see this error :

```
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

conda install dask # either conda install
python -m pip install "dask[dataframe]" --upgrade # or python -m pip install
```

Tried the following:

1. Bundling dask[complete] and uploading it as aws lambda layer
2. Bundling dask[dataframe] and uploading it as aws lambda layer
3. Bundling the code and dependencies and placing in s3 bucket

**python version 3.8**

<img width="315" alt="image" src="https://user-images.githubusercontent.com/32214453/170554637-165f39b3-3ab5-419f-91a8-30674e5796c9.png">

**Comment by quasiben** [comment]
Can you show the full traceback ?  For example, in this intentionally incorrect environment I get the following when trying to import dask.dataframe:

```python
>>> import dask.dataframe as dd
Traceback (most recent call last):
  File "/Users/bzaitlen/Documents/GitHub/dask/dask/dataframe/__init__.py", line 2, in <module>
    import dask.dataframe._pyarrow_compat
  File "/Users/bzaitlen/Documents/GitHub/dask/dask/dataframe/_pyarrow_compat.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bzaitlen/Documents/GitHub/dask/dask/dataframe/__init__.py", line 64, in <module>
    raise ImportError(msg) from e
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
```

**Comment by raghaviravi92** [comment]
@quasiben This is all I see in the cloudwatch logs after triggering my AWS lambda function..

**Comment by quasiben** [comment]
Hmm, another thing you could try is looking print`sys.path`  (hopefully this is picked up by logs) and see if the correct python is being used:

```
>>> import sys
>>> sys.path
['', '/Users/bzaitlen/miniconda3/envs/foo/lib/python38.zip', '/Users/bzaitlen/miniconda3/envs/foo/lib/python3.8', '/Users/bzaitlen/miniconda3/envs/foo/lib/python3.8/lib-dynload', '/Users/bzaitlen/miniconda3/envs/foo/lib/python3.8/site-packages']
>>>
```

Perhaps, the bundle you are using isn't quite correct

**Comment by raghaviravi92** [comment]
{
  "statusCode": 200,
  "body": "[\"/var/task\", \"/opt/python/lib/python3.8/site-packages\", \"/opt/python\", \"/var/runtime\", \"/var/lang/lib/python38.zip\", \"/var/lang/lib/python3.8\", \"/var/lang/lib/python3.8/lib-dynload\", \"/var/lang/lib/python3.8/site-packages\", \"/opt/python/lib/python3.8/site-packages\"]"
}

**Comment by quasiben** [comment]
To me this looks like you are getting multiple versions python installations conflated.  I've never deployed with aws lambda so my experience is limited.  I would suggest reviewing this doc: https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency

And double checking you are deploying everything correctly -- maybe another test to confirm you have NumPy install and a test to confirm you have pandas installed

**Comment by raghaviravi92** [comment]
used docker image to build lambda-layer and it worked.. As rightly pointed out by you, Some issue with the environment I was creating layer. thank you

**Comment by quasiben** [comment]
Great!
