### ISSUE TITLE
normalize_token does not raise warning for function with non-deterministic hash

### ISSUE THREAD

**Issue by LunarLanding** [dask/dask#9135]
```
import dask.config
from dask.base import tokenize
a,b = (
    lambda a: a,
    lambda a: a,
)
with dask.config.set({"tokenize.ensure-deterministic":True}):
    print(tokenize(a)==tokenize(b))
str(a),str(b)
```
Gives:
```
False
('<function <lambda> at 0x14a0d079fee0>',
 '<function <lambda> at 0x14a0ca90cc10>')
```
This is because of the last lines here, where the code gives up by using `str(func)`: 
https://github.com/dask/dask/blob/c60b1f757a3b92361504833cf0417e9c77b82514/dask/base.py#L1043-L1069

**Comment by pavithraes** [comment]
@LunarLanding Welcome to Dask, and thanks for reporting!

**Comment by pavithraes** [comment]
I took a look at this with @ian-r-rose, and this seems to be because cloudpickle isn't always deterministic: https://github.com/cloudpipe/cloudpickle/issues/385

I agree we can raise a warning/runtime error here. I can open a PR. :)

Reproducer:

```
import dask.config
from dask.base import tokenize

a, b = (lambda a: a, lambda a: a)
tokenize(a) == tokenize(b) # True

x, y = (lambda a: a,
lambda a: a) # Just add a new-line
tokenize(x) == tokenize(y) # False
```
