### ISSUE TITLE
wrong calculation of `warnsize` in slicing?

### ISSUE THREAD

**Issue by d70-t** [dask/dask#9146]
**What happened**:
```
PerformanceWarning: Slicing is producing a large chunk.
```

**What you expected to happen**:
No performance warning. Resulting chunks are each below 10MiB.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da
a = da.zeros((100000, 10000000), chunks=(1, 10000000))
a[:,np.arange(1000000)]
```

**Anything else we need to know?**:

The calculation of `warnsize` at [`take`](https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/array/slicing.py#L642) might be wrong. My guess would be, that it should be `max` instead of `sum` like:

```python
np.prod([max(x) for x in other_chunks])
```

That way, the largest resulting chunk would be calculated (instead of chunksize * shape of other dimensions).

**Environment**:

- Dask version: 2022.05.2
- Python version: 3.9.9
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by d70-t** [comment]
cc @TomAugspurger

**Comment by quasiben** [comment]
@jakirkham when you are back from PTO can you take a look at this ?

**Comment by pavithraes** [comment]
@ian-r-rose and I think `@d70-t`'s proposed fix looks right. We tried out the fix locally and all the tests passed, I'll open a PR. :)

**Comment by pavithraes** [comment]
I looked at this with @ian-r-rose, and we think `@d70-t`'s proposed fix looks right. We tried out the fix locally and all the tests passed, I'll open a PR. :)
