### ISSUE TITLE
Documentation reorganization

### ISSUE THREAD

**Issue by koverholt** [dask/dask#915]
This is a dump of my initial thoughts after reading through the docs in the past few days. I'd be happy to work in small PRs to implement those that you find most interesting.
- [x] Reorganize/consolidate collections docs for consistency
- [x] Move developer oriented pages into a different section
- [x] Move API pages to their own section
- [x] Add a section for end-user tutorials in increasing complexity
- [x] Refer to the [example notebooks](https://github.com/dask/dask-examples) and [tutorial](https://github.com/dask/dask-tutorial). Alternatively, have examples directly in docs with links to example notebooks.
- [ ] Split intro figure into a conceptual diagram (As a user, what steps do I take?) and workflow diagram (For a given purpose/workflow/data format, which collection should I use?)
- [ ] Highlight ability to easily swap between schedulers (could be in a tutorial or multiple tutorials).
- [ ] Illustrate/discuss where Dask fits in PyData layers (e.g., Blaze > Dask > Pandas > Numpy > Numba).

**Comment by mrocklin** [comment]
Generally these all sound like good ideas to me.  I don't yet have thoughts that strongly prioritize any of these issues over the others; your judgment here is probably better than my own.  If there was particular language you wanted generated around some topic I would be happy to do so.
