### ISSUE TITLE
Cannot create a lagged variable with dask-cuDF

### ISSUE THREAD

**Issue by shawnbrar** [dask/dask#9162]
I have the following `dask_cudf.core.DataFrame`:-

    import pandas as pd
    import numpy as np
    import dask_cudf
    import cudf

    data = {"x":range(1,21), "nor":np.random.normal(2, 4, 20), "unif":np.random.uniform(size = 20)}
    df = cudf.DataFrame(data)
    ddf = dask_cudf.from_cudf(df, npartitions = 2)
    ddf.compute()

I wanted to create 1st till 5th lagged values for the columns `nor` and `unif`. I create them the following way:-

    colz = ["nor", "unif"]
    ddf[[s + "_" + str(1) for s in colz]] = ddf[colz].shift(1)
    ddf[[s + "_" + str(2) for s in colz]] = ddf[colz].shift(2)

I can create the first and the second lagged values, but not more than that. When I run `shift` with a value more than 2, I get the following error::-

        /usr/local/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
        175     try:
    --> 176         yield
        177     except Exception as e:

    /usr/local/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
       5832     with raise_on_meta_error(funcname(func), udf=udf):
    -> 5833         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
       5834

    /usr/local/lib/python3.7/site-packages/dask/utils.py in __call__(self, _methodcaller__obj, *args, **kwargs)
       1020     def __call__(self, __obj, *args, **kwargs):
    -> 1021         return getattr(__obj, self.method)(*args, **kwargs)
       1022

    /usr/local/lib/python3.7/site-packages/cudf/core/frame.py in shift(self, periods, freq, axis, fill_value)
       1787         assert axis in (None, 0) and freq is None
    -> 1788         return self._shift(periods)
       1789

    /usr/local/lib/python3.7/site-packages/cudf/core/frame.py in _shift(self, offset, fill_value)
       1792         return self.__class__._from_data(
    -> 1793             zip(self._column_names, data_columns), self._index
       1794         )

    /usr/local/lib/python3.7/site-packages/cudf/core/dataframe.py in _from_data(cls, data, index, columns)
        817     ) -> DataFrame:
    --> 818         out = super()._from_data(data, index)
        819         if index is None:

    /usr/local/lib/python3.7/site-packages/cudf/core/frame.py in _from_data(cls, data, index)
        139         obj = cls.__new__(cls)
    --> 140         Frame.__init__(obj, data, index)
        141         return obj

    /usr/local/lib/python3.7/site-packages/cudf/core/frame.py in __init__(self, data, index)
         77             data = {}
    ---> 78         self._data = cudf.core.column_accessor.ColumnAccessor(data)
         79         self._index = index

    /usr/local/lib/python3.7/site-packages/cudf/core/column_accessor.py in __init__(self, data, multiindex, level_names)
        120             if data:
    --> 121                 data = dict(data)
        122                 # Faster than next(iter(data.values()))

    /usr/local/lib/python3.7/site-packages/cudf/core/frame.py in <genexpr>(.0)
       1790     def _shift(self, offset, fill_value=None):
    -> 1791         data_columns = (col.shift(offset, fill_value) for col in self._columns)
       1792         return self.__class__._from_data(

    /usr/local/lib/python3.7/site-packages/cudf/core/column/column.py in shift(self, offset, fill_value)
        390     def shift(self, offset: int, fill_value: ScalarLike) -> ColumnBase:
    --> 391         return libcudf.copying.shift(self, offset, fill_value)
        392

    cudf/_lib/copying.pyx in cudf._lib.copying.shift()

    RuntimeError: parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument

    The above exception was the direct cause of the following exception:

    ValueError                                Traceback (most recent call last)
    <ipython-input-13-27823eac1e8a> in <module>()
          2 ddf[[s + "_" + str(1) for s in colz]] = ddf[colz].shift(1)
          3 ddf[[s + "_" + str(2) for s in colz]] = ddf[colz].shift(2)
    ----> 4 ddf[[s + "_" + str(3) for s in colz]] = ddf[colz].shift(3)

    /usr/local/lib/python3.7/site-packages/dask/dataframe/core.py in shift(self, periods, freq, axis)
       1683             before, after = (periods, 0) if periods > 0 else (0, -periods)
       1684             return self.map_overlap(
    -> 1685                 M.shift, before, after, token="shift", periods=periods
       1686             )
       1687

    /usr/local/lib/python3.7/site-packages/dask/dataframe/core.py in map_overlap(self, func, before, after, *args, **kwargs)
        840         from .rolling import map_overlap
        841
    --> 842         return map_overlap(func, self, before, after, *args, **kwargs)
        843
        844     def memory_usage_per_partition(self, index=True, deep=False):

    /usr/local/lib/python3.7/site-packages/dask/dataframe/rolling.py in map_overlap(func, df, before, after, *args, **kwargs)
        102         meta = kwargs.pop("meta")
        103     else:
    --> 104         meta = _emulate(func, df, *args, **kwargs)
        105     meta = make_meta(meta, index=df._meta.index, parent_meta=df._meta)
        106

    /usr/local/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
       5831     """
       5832     with raise_on_meta_error(funcname(func), udf=udf):
    -> 5833         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
       5834
       5835

    /usr/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
        128                 value = type()
        129             try:
    --> 130                 self.gen.throw(type, value, traceback)
        131             except StopIteration as exc:
        132                 # Suppress StopIteration *unless* it's the same exception that

    /usr/local/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
        195         )
        196         msg = msg.format(f" in `{funcname}`" if funcname else "", repr(e), tb)
    --> 197         raise ValueError(msg) from e
        198
        199

    cudf/_lib/copying.pyx in cudf._lib.copying.shift()

    RuntimeError: parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument

    The above exception was the direct cause of the following exception:

    ValueError                                Traceback (most recent call last)
    /usr/local/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
        195         )
        196         msg = msg.format(f" in `{funcname}`" if funcname else "", repr(e), tb)
    --> 197         raise ValueError(msg) from e
        198
        199

    ValueError: Metadata inference failed in `shift`.

    Original error is below:
    ------------------------
    RuntimeError('parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument')

    Traceback:
    ---------
      File "/usr/local/lib/python3.7/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
        yield
      File "/usr/local/lib/python3.7/site-packages/dask/dataframe/core.py", line 5833, in _emulate
        return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
      File "/usr/local/lib/python3.7/site-packages/dask/utils.py", line 1021, in __call__
        return getattr(__obj, self.method)(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/frame.py", line 1788, in shift
        return self._shift(periods)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/frame.py", line 1793, in _shift
        zip(self._column_names, data_columns), self._index
      File "/usr/local/lib/python3.7/site-packages/cudf/core/dataframe.py", line 818, in _from_data
        out = super()._from_data(data, index)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/frame.py", line 140, in _from_data
        Frame.__init__(obj, data, index)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/frame.py", line 78, in __init__
        self._data = cudf.core.column_accessor.ColumnAccessor(data)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/column_accessor.py", line 121, in __init__
        data = dict(data)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/frame.py", line 1791, in <genexpr>
        data_columns = (col.shift(offset, fill_value) for col in self._columns)
      File "/usr/local/lib/python3.7/site-packages/cudf/core/column/column.py", line 391, in shift
        return libcudf.copying.shift(self, offset, fill_value)
      File "cudf/_lib/copying.pyx", line 633, in cudf._lib.copying.shift

I can't seem to understand why this is happening.

I have installed the nvidia `rapids` library on google colab.

**Comment by pavithraes** [comment]
@shawnbrar Welcome to Dask, and thanks for reporting!

The example seems to work fine with pandas + Dask DataFrame, @jakirkham this might be specific to cudf?

**Comment by jrbourbeau** [comment]
Also cc @dask/gpu

**Comment by galipremsagar** [comment]
Seems to be `dask-cudf` issue, I'm looking into it.

**Comment by galipremsagar** [comment]
@shawnbrar From the stack-trace looks like you are on an older version of `cudf` that had this issue, but this is resolved in latest version of `dask_cudf`:
```python
In [4]: import pandas as pd
   ...: import numpy as np
   ...: import dask_cudf
   ...: import cudf
   ...: 
   ...: 
   ...: data = {"x":range(1,21), "nor":np.random.normal(2, 4, 20), "unif":np.random.uniform(size = 20)}
   ...: df = cudf.DataFrame(data)
   ...: ddf = dask_cudf.from_cudf(df, npartitions = 2)
   ...: colz = ["nor", "unif"]

In [5]: ddf[[s + "_" + str(1) for s in colz]] = ddf[colz].shift(1)

In [6]: ddf[[s + "_" + str(2) for s in colz]] = ddf[colz].shift(2)

In [7]: ddf[[s + "_" + str(3) for s in colz]] = ddf[colz].shift(3)

In [8]: ddf
Out[8]: <dask_cudf.DataFrame | 41 tasks | 2 npartitions>

In [9]: ddf.compute()
Out[9]: 
     x       nor      unif         nor_1       unif_1         nor_2       unif_2         nor_3       unif_3
0    1  2.745560  0.039613          <NA>         <NA>          <NA>         <NA>          <NA>         <NA>
1    2  0.300497  0.892310   2.745560215  0.039613325          <NA>         <NA>          <NA>         <NA>
2    3 -0.452404  0.760497    0.30049661   0.89230955   2.745560215  0.039613325          <NA>         <NA>
3    4  3.182274  0.244889  -0.452404079  0.760496537    0.30049661   0.89230955   2.745560215  0.039613325
4    5  4.723372  0.730248   3.182273703   0.24488867  -0.452404079  0.760496537    0.30049661   0.89230955
5    6 -1.810120  0.966466   4.723372459  0.730248361   3.182273703   0.24488867  -0.452404079  0.760496537
6    7 -1.550030  0.386746  -1.810119663  0.966466115   4.723372459  0.730248361   3.182273703   0.24488867
7    8  3.600397  0.903401  -1.550030463  0.386745959  -1.810119663  0.966466115   4.723372459  0.730248361
8    9 -5.448567  0.569185   3.600397425  0.903400599  -1.550030463  0.386745959  -1.810119663  0.966466115
9   10 -2.844141  0.543476  -5.448567045  0.569185152   3.600397425  0.903400599  -1.550030463  0.386745959
10  11 -5.725374  0.421610  -2.844140634  0.543475825  -5.448567045  0.569185152   3.600397425  0.903400599
11  12 -4.671747  0.252154  -5.725373554  0.421610185  -2.844140634  0.543475825  -5.448567045  0.569185152
12  13 -3.072900  0.713379  -4.671747017   0.25215428  -5.725373554  0.421610185  -2.844140634  0.543475825
13  14 -2.776655  0.251812  -3.072900135  0.713378849  -4.671747017   0.25215428  -5.725373554  0.421610185
14  15  5.647093  0.390376  -2.776654974  0.251811978  -3.072900135  0.713378849  -4.671747017   0.25215428
15  16 -1.406217  0.082309   5.647093058  0.390375584  -2.776654974  0.251811978  -3.072900135  0.713378849
16  17  5.728304  0.261519    -1.4062168  0.082308694   5.647093058  0.390375584  -2.776654974  0.251811978
17  18  1.339052  0.194920   5.728303548  0.261519033    -1.4062168  0.082308694   5.647093058  0.390375584
18  19  6.128900  0.252666   1.339051836   0.19492029   5.728303548  0.261519033    -1.4062168  0.082308694
19  20  1.455445  0.208791   6.128900473  0.252665986   1.339051836   0.19492029   5.728303548  0.261519033

In [10]: cudf.__version__
Out[10]: '22.08.00a+114.g10c4c33286'

In [11]: dask_cudf.__version__
Out[11]: '22.08.00a+114.g10c4c33286'

In [12]: import dask

In [13]: dask.__version__
Out[13]: '2022.05.2+14.gcd6a58b6a'

```

**Comment by jrbourbeau** [comment]
Thanks for looking into this @galipremsagar! @shawnbrar can you upgrade your `dask_cudf` version and confirm whether or not that fixes the issue?

**Comment by shawnbrar** [comment]
Yes I am on `rapids 21.12` which is an older version. I will update it and tell you.

**Comment by jakirkham** [comment]
@shawnbrar have you had a chance to try with a newer version? No worries if not. Just wanted to check-in 🙂

**Comment by shawnbrar** [comment]
Yes, I was able to use the updated version. And it works correctly.

**Comment by jakirkham** [comment]
Thanks for the update! Glad to hear things are working correctly 😄

Have gone ahead and closed as resolved. Though if something else comes up, please feel free to file a new issue and we can follow up there 🙂
