### ISSUE TITLE
Improve docstring for `dask.dataframe.Series.str.split`

### ISSUE THREAD

**Issue by rrpelgrim** [dask/dask#9176]
From [this StackOverflow question](https://stackoverflow.com/questions/71493347/split-column-in-a-dask-dataframe-into-n-number-of-columns) it appears that it would be useful to modify the docstrings for `dask.dataframe.Series.str.split`. 

The [docstrings](https://docs.dask.org/en/latest/generated/dask.dataframe.Series.str.split.html?highlight=dask.dataframe.Series.str.split) currently mention "Some inconsistencies may exist". It could be useful to expand the docstring to include the specific known inconsistency of using `expand=True` with unknown number of splits.

The code below currently returns a NotImplementedError:

```python
import dask.dataframe as dd
import pandas as pd

ddf = dd.from_pandas(
    pd.DataFrame({
        'column_name_1': ['a^b^c', 'e^f^g', 'h^i'], 'column_name_2': ['j', 'k^l', 'm']
    }), npartitions=2
)

# returns NotImplementedError
ddf['column_name_1'].str.split('^', expand=True).compute()
```

**What happened**:
```python-traceback
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Input In [1], in <cell line: 11>()
      4 ddf = dd.from_pandas(
      5     pd.DataFrame({
      6         'column_name_1': ['a^b^c', 'e^f^g', 'h^i'], 'column_name_2': ['j', 'k^l', 'm']
      7     }), npartitions=2
      8 )
     10 # returns NotImplementedError
---> 11 ddf['column_name_1'].str.split('^', expand=True).compute()

File ~/mambaforge/envs/coiled-runtime/lib/python3.9/site-packages/dask/dataframe/accessor.py:125, in StringAccessor.split(self, pat, n, expand)
    123 if expand:
    124     if n == -1:
--> 125         raise NotImplementedError(
    126             "To use the expand parameter you must specify the number of "
    127             "expected splits with the n= parameter. Usually n splits result in n+1 output columns."
    128         )
    129     else:
    130         delimiter = " " if pat is None else pat

NotImplementedError: To use the expand parameter you must specify the number of expected splits with the n= parameter. Usually n splits result in n+1 output columns.
```

**What you expected to happen**:
Be more explicit in the docstring about known inconsistencies.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.01.0
- Python version: 3.9.13
- Operating System: MacOS
- Install method (conda, pip, source): conda

**Comment by scharlottej13** [comment]
Thanks @rrpelgrim for opening up this issue and volunteering to work on it! Here's where [`Series.str.split`](https://github.com/dask/dask/blob/22915dca760f92219915e3afaf9ffa8dc31d1ad9/dask/dataframe/accessor.py#L275-L277) is defined, that's where you can change the docstring
