### ISSUE TITLE
Stop using dask.config.ensure_file in downstream libraries

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#9179]
Ensure file is useful. It's not always what you want though. It creates an optionally-commented-out version of the config file in the user's config directory that corresponds to current default, if no such file exists. This is good because it helps people to quickly see what is available to them.

However, this is also somewhat shortsighted. As we change config we leave lots of these files around. Most people don't actually look at the config when they first start. When they do use config they typically only need a little bit of it, not the whole thing. It's been better to not send these things out all the time, freezing people at whatever config file when they first installed the package (possibly years ago)

Documentation changed in https://github.com/dask/dask/pull/9171

@jacobtomlinson thoughts as someone who maintains a few downstream libraries?

**Comment by jacobtomlinson** [comment]
I would be in favour of dropping these. As you say the biggest shortfall here is that these files get frozen at a point in time. We could potentially do some ruaml magic to keep them up to date, but I think that would get messy quickly!

We also have the nice sphinx extension for including the config spec in docs. Not all downstream libraries have a spec, but we should add them. 

I think the only thing I care about is making sure there are lots of easily understandably copy/paste examples in docs as a replacement for this. YAML indentation can cause headaches, especially when users don't use it every day, so making sure they can easily update their config and understand what is going on would be key.

**Comment by jacobtomlinson** [comment]
I wonder if removing some of the tooling around YAML would also open us up to optionally supporting other formats like TOML that folks may be more familiar with due to it being more used in Python these days. (I will always be a YAML fan due to being a Kubernetes fanatic, but folks seem to like TOML).

**Comment by pavithraes** [comment]
@mrocklin @jacobtomlinson What can be the next steps here? Shall we leave this issue open as a discussion or consider closing as resolved?

**Comment by pavithraes** [comment]
Closing for now, but please feel free to re-open it if needed. :)
