### ISSUE TITLE
Possible race condition in `dask.utils:Dispatch.dispatch`

### ISSUE THREAD

**Issue by zklaus** [dask/dask#9181]
**What happened**:
When using a large number of tasks with `np.ma.core.MaskedArray` blocks, sometimes the scheduler loses the ability to deserialize them. I think I have tracked this down to a possible race condition in [`dask.utils:Dispatch.dispatch`](https://github.com/dask/dask/blob/71aa6ffb3cfdc2a7dcfbc5f5ed91b20f7735c7fd/dask/utils.py#L578), where the lazy registration function is popped off before the registration. If another dispatch happens between those two events, the implementation is not yet in `self._lookup`, but also the lazy registration function is no longer present and thus dask concludes that it can not deserialize the item.

**What you expected to happen**:
That dask/distributed retains the ability to deserialize masked arrays.

**Minimal Complete Verifiable Example**:

I don't have a complete verifiable example due to the tricky nature of reproducing race conditions.

**Environment**:

- Dask version: `main`
- Python version: Python 3.8.13 | packaged by conda-forge
- Operating System: Linux
- Install method (conda, pip, source): Conda environment + dask and distributed source

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by pavithraes** [comment]
@zklaus Thanks for sharing!

I see the dispatch function was updated in #8185. I believe `@jcrist` is on vacation, @jsignell do you have thoughts on this since you reviewed the PR?

**Comment by jrbourbeau** [comment]
@zklaus do you have any traceback / error messages / logs you can post? I'm curious under what circumstances the distributed scheduler is running `Dispatch`-related code in multiple threads

**Comment by quasiben** [comment]
@jakirkham  do you have any thoughts about what could be going on here?

**Comment by jakirkham** [comment]
Not really. The suggestions above seem reasonable

**Comment by jsignell** [comment]
Sorry for being slow to this. I'm wondering if there would be performance implications if we just change the `pop` to a `get`. 

```diff
diff --git a/dask/utils.py b/dask/utils.py
index 2510e904e..6f305a783 100644
--- a/dask/utils.py
+++ b/dask/utils.py
@@ -591,7 +591,7 @@ class Dispatch:
             # Is a lazy registration function present?
             toplevel, _, _ = cls2.__module__.partition(".")
             try:
-                register = self._lazy.pop(toplevel)
+                register = self._lazy[toplevel]
             except KeyError:
                 pass
             else:
```

It seems to me like that would solve the race condition right? It just means that the same dispatch might be assigned to the lookup dict multiple times, but only in rarely based on the description in this issue.

**Comment by zklaus** [comment]
Strange. Thanks for taking care of this, @jsignell!

**Comment by zklaus** [comment]
I added a lock to the lazy dispatch and that seemed to solve the problem for me, though it's always tough to know for sure with this kind of problem. If you think that approach is worth pursuing, I'd be interested to know if adding another dependency (in this case `readerwriterlock`) is acceptable or if we should find a different way to implement the lock.

Then again, perhaps you consider a lock inappropriate or belief that the problem isn't solved by this at all.
