### ISSUE TITLE
AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

### ISSUE THREAD

**Issue by jorgesisco** [dask/dask#9189]
I have a dask cluster active

```
from dask.distributed import Client, progress 

client = Client()
client
```

When I try to encode my data I get the error:

`AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'`

I encoded the data with the cluster closed and then tried to fit the model and I get the same error.

Context: I am training a model using dask distributed on Sagemkaer, so far I have not been able to pull it up on sagemaker instance, when I do it locally it gets trained but I need this to work on sagemaker.

**Comment by pavithraes** [comment]
@jorgesisco Welcome!

> When I try to encode my data I get the error:
> `AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'`

Could you please share a minimal example that we reproduce and the complete error traceback? I'll allow us to help you better. :)

Also, it seems like this is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse!

**Comment by jorgesisco** [comment]
> 

Hello! @pavithraes I am sorry for the late response! The issue is, the error only happens on Sagemaker, if I run my notebook locally I won't have any issue except for the lack of memory when training the model.

When I try to run the block where I encode my data I get the error:

```
enc = LabelEncoder()

gender_enc = enc.fit_transform(x['gender'].astype(str))
category_enc = enc.fit_transform(x['category'].astype(str))
subcategory_enc = enc.fit_transform(x['subcategory'].astype(str))
item_brand_enc = enc.fit_transform(x['item_brand'].astype(str))
item_NWT_enc = enc.fit_transform(x['item_NWT'].astype(str))

x['gender_enc'] = gender_enc
x['category_enc'] = category_enc
x['subcategory_enc'] = subcategory_enc
x['item_brand_enc'] = item_brand_enc
x['item_NWT_enc'] = item_NWT_enc
```


Error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in fit_transform(self, y)
    131         self, y: Union[ArrayLike, SeriesType]
    132     ) -> Union[ArrayLike, SeriesType]:
--> 133         y = self._check_array(y)
    134 
    135         if isinstance(y, da.Array):

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in _check_array(self, y)
    109                     y = y.cat.as_known()
    110             else:
--> 111                 y = y.to_dask_array(lengths=True)
    112         return y
    113 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/dataframe/core.py in to_dask_array(self, lengths, meta)
   1441         """
   1442         if lengths is True:
-> 1443             lengths = tuple(self.map_partitions(len, enforce_metadata=False).compute())
   1444 
   1445         arr = self.values

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    281         dask.base.compute
    282         """
--> 283         (result,) = compute(self, traverse=False, **kwargs)
    284         return result
    285 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    563         postcomputes.append(x.__dask_postcompute__())
    564 
--> 565     results = schedule(dsk, keys, **kwargs)
    566     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    567 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2642             retries=retries,
   2643             user_priority=priority,
-> 2644             actors=actors,
   2645         )
   2646         packed = pack_data(keys, futures)

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in _graph_to_futures(self, dsk, keys, workers, allow_other_workers, priority, user_priority, resources, retries, fifo_timeout, actors)
   2541                 dsk = HighLevelGraph.from_collections(id(dsk), dsk, dependencies=())
   2542 
-> 2543             dsk = highlevelgraph_pack(dsk, self, keyset)
   2544 
   2545             annotations = {}

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in highlevelgraph_pack(hlg, client, client_keys)
    118                     hlg.key_dependencies,
    119                     client,
--> 120                     client_keys,
    121                 ),
    122             }

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in _materialized_layer_pack(layer, all_keys, known_key_dependencies, client, client_keys)
     63     }
     64 
---> 65     annotations = layer.pack_annotations()
     66     all_keys = all_keys.union(dsk)
     67     dsk = {stringify(k): stringify(v, exclusive=all_keys) for k, v in dsk.items()}

AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in fit_transform(self, y)
    131         self, y: Union[ArrayLike, SeriesType]
    132     ) -> Union[ArrayLike, SeriesType]:
--> 133         y = self._check_array(y)
    134 
    135         if isinstance(y, da.Array):

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in _check_array(self, y)
    109                     y = y.cat.as_known()
    110             else:
--> 111                 y = y.to_dask_array(lengths=True)
    112         return y
    113 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/dataframe/core.py in to_dask_array(self, lengths, meta)
   1441         """
   1442         if lengths is True:
-> 1443             lengths = tuple(self.map_partitions(len, enforce_metadata=False).compute())
   1444 
   1445         arr = self.values

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    281         dask.base.compute
    282         """
--> 283         (result,) = compute(self, traverse=False, **kwargs)
    284         return result
    285 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    563         postcomputes.append(x.__dask_postcompute__())
    564 
--> 565     results = schedule(dsk, keys, **kwargs)
    566     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    567 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2642             retries=retries,
   2643             user_priority=priority,
-> 2644             actors=actors,
   2645         )
   2646         packed = pack_data(keys, futures)

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in _graph_to_futures(self, dsk, keys, workers, allow_other_workers, priority, user_priority, resources, retries, fifo_timeout, actors)
   2541                 dsk = HighLevelGraph.from_collections(id(dsk), dsk, dependencies=())
   2542 
-> 2543             dsk = highlevelgraph_pack(dsk, self, keyset)
   2544 
   2545             annotations = {}

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in highlevelgraph_pack(hlg, client, client_keys)
    118                     hlg.key_dependencies,
    119                     client,
--> 120                     client_keys,
    121                 ),
    122             }

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in _materialized_layer_pack(layer, all_keys, known_key_dependencies, client, client_keys)
     63     }
     64 
---> 65     annotations = layer.pack_annotations()
     66     all_keys = all_keys.union(dsk)
     67     dsk = {stringify(k): stringify(v, exclusive=all_keys) for k, v in dsk.items()}

AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in fit_transform(self, y)
    131         self, y: Union[ArrayLike, SeriesType]
    132     ) -> Union[ArrayLike, SeriesType]:
--> 133         y = self._check_array(y)
    134 
    135         if isinstance(y, da.Array):

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask_ml/preprocessing/label.py in _check_array(self, y)
    109                     y = y.cat.as_known()
    110             else:
--> 111                 y = y.to_dask_array(lengths=True)
    112         return y
    113 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/dataframe/core.py in to_dask_array(self, lengths, meta)
   1441         """
   1442         if lengths is True:
-> 1443             lengths = tuple(self.map_partitions(len, enforce_metadata=False).compute())
   1444 
   1445         arr = self.values

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    281         dask.base.compute
    282         """
--> 283         (result,) = compute(self, traverse=False, **kwargs)
    284         return result
    285 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    563         postcomputes.append(x.__dask_postcompute__())
    564 
--> 565     results = schedule(dsk, keys, **kwargs)
    566     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    567 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2642             retries=retries,
   2643             user_priority=priority,
-> 2644             actors=actors,
   2645         )
   2646         packed = pack_data(keys, futures)

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in _graph_to_futures(self, dsk, keys, workers, allow_other_workers, priority, user_priority, resources, retries, fifo_timeout, actors)
   2541                 dsk = HighLevelGraph.from_collections(id(dsk), dsk, dependencies=())
   2542 
-> 2543             dsk = highlevelgraph_pack(dsk, self, keyset)
   2544 
   2545             annotations = {}

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in highlevelgraph_pack(hlg, client, client_keys)
    118                     hlg.key_dependencies,
    119                     client,
--> 120                     client_keys,
    121                 ),
    122             }

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py in _materialized_layer_pack(layer, all_keys, known_key_dependencies, client, client_keys)
     63     }
     64 
---> 65     annotations = layer.pack_annotations()
     66     all_keys = all_keys.union(dsk)
     67     dsk = {stringify(k): stringify(v, exclusive=all_keys) for k, v in dsk.items()}

AttributeError: 'MaterializedLayer' object has no attribute 'pack_annotations'

**Comment by jorgesisco** [comment]
@pavithraes Just to let you know you were right, by creating a new kernel with python 3.8, it's working.

**Comment by pavithraes** [comment]
Gald to hear! I'm closing this as resolved, please feel free to re-open it if needed!
