### ISSUE TITLE
Why does dask + FIPS require python 3.9?

### ISSUE THREAD

**Issue by taqd** [dask/dask#9208]
I am trying to use FIPS with dask using python 3.8, is this possible? Is there a reason why dask + fips is requiring python 3.9?

https://github.com/dask/dask/blob/78452267da9683fe637148fd7a667724c3ff7713/dask/base.py#L912-L920

On my system, I've been able to patch `dask/base.py` to instead test for python 3.8 (instead of 3.9), and everything seems to work fine; is it possible to change this to 3.8? If not, why? Is there a danger with using 3.8 here?

Thanks

**Comment by jsignell** [comment]
I think the decision to set this to python 3.9 was based on the understanding that this flag was added in 3.9 (https://docs.python.org/3.9/library/hashlib.html). I think the danger is that the `usedforsecurity` kwarg might be unsupported on older versions of Python.

**Comment by pavithraes** [comment]
Thanks, `@jsignell`! And, here's the relevant PR: #8762

@taqd If this resolves your question, please feel free to close this issue. :)

**Comment by pavithraes** [comment]
I'll go ahead and close this as resolved, please feel free to re-open it if needed!
