### ISSUE TITLE
Using ddf.from_pandas with chunksize=1 results in one partition having two rows

### ISSUE THREAD

**Issue by orf** [dask/dask#9218]
**What happened**: When creating a ddf using `from_pandas(chunksize=1)` not all partitions have 1 row. The last partition has two rows in it.

**What you expected to happen**: The dataframe should be evenly split into 10 partitions

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as ddf
import pandas as pd
import numpy as np

if __name__ == "__main__":
    df = pd.DataFrame(np.random.randint(0, 10, size=(10, 4)), columns=list('ABCD'))
    dataset: ddf.DataFrame = ddf.from_pandas(df, chunksize=1).persist()
    # get each partition length
    num_rows = dataset.map_partitions(lambda df: len(df)).compute()
    print(list(num_rows))
```

Results in 

```
[1, 1, 1, 1, 1, 1, 1, 1, 2]
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.6.1
- Python version: 3.10
- Operating System: MacOS
- Install method (conda, pip, source): Pip

**Comment by rjzamora** [comment]
Thanks for the simple example - I can also reproduce. I'll take a look at the `from_pandas` code to see whats going on.
