### ISSUE TITLE
`ddf.divisions` lost on `.to_parquet()`

### ISSUE THREAD

**Issue by asmith26** [dask/dask#9222]
**What happened**:
Writing a `dask.DataFrame` to parquet and reading it back seems to lose the divisions information.

**What you expected to happen**:
`ddf.divisions` info to be retrain by the parquet/metadata files.

**Minimal Complete Verifiable Example**:

```python
>>> import dask
>>> import dask.dataframe as dd
>>> ddf = dask.datasets.timeseries(partition_freq="6d")
>>> ddf.divisions
(Timestamp('2000-01-01 00:00:00', freq='6D'), Timestamp('2000-01-07 00:00:00', freq='6D'), Timestamp('2000-01-13 00:00:00', freq='6D'), Timestamp('2000-01-19 00:00:00', freq='6D'), Timestamp('2000-01-25 00:00:00', freq='6D'), Timestamp('2000-01-31 00:00:00', freq='6D'))
>>> ddf.to_parquet("ddf")
>>> dd.read_parquet("ddf").divisions
(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
```

**Anything else we need to know?**:
I've tried this with both pyarrow and fastparquet engines.

**Environment**:

- Dask version:  2022.6.1 
- Python version: 3.8 
- Operating System: Ubuntu
- Install method (conda, pip, source): mamba

**Comment by TomAugspurger** [comment]
Thanks for the simple reproducer.

I think you want the `write_metadata_file=True` argument when writing the file

```
import dask
import dask.dataframe as dd
ddf = dask.datasets.timeseries(partition_freq="6d")

ddf.to_parquet("ddf", write_metadata_file=True)
dd.read_parquet("ddf").divisions
```

This was a [recent change](https://docs.dask.org/en/stable/changelog.html#id20).

**Comment by rjzamora** [comment]
Thanks for filing an issue @asmith26!

Default behavior of `to/read_parquet` has recently changed to improve stability, and two things that used to happen by default are now optional:

1. On the write side, you need to specify `write_metadata_file=True` if you want Dask to write a single global metadata file (as @TomAugspurger suggested).  This is not required to resolve your issue, but can improve read performance at the cost of write performance/stability.
2. On the read side, you must specify that you want to calculate divisions with `calculate_divisions=True`. If you don't set this, Dask will avoid parsing the Parquet metadata/statistics if possible.
