### ISSUE TITLE
ddf.cor and ddf.cov fail for single-row partition

### ISSUE THREAD

**Issue by rjzamora** [dask/dask#9226]
[dask/dataframe/tests/test_dataframe.py::test_cov_corr_meta](https://github.com/dask/dask/blob/bc3137d954d71068de4ef00c7c51470bfc69ef43/dask/dataframe/tests/test_dataframe.py#L3199) uses `from_pandas(..., npartitions=2)`, but (as discussed in #9221) this is actually produces a single-partition DataFrame.

As far as I can tell, `test_cov_corr_meta` fails when there really are 2+ partitions (e.g. `from_pandas(..., chunksize=1)`), because the underlying functions (`cor` and `cov`) fail on single-row partitions.

**Action Items**:

- [ ] Determine if single-row failures are bugs or expected behavior, and fix or document
- [ ] Fix the test to cover single-row partition case

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/9756
