### ISSUE TITLE
Typing overhaul

### ISSUE THREAD

**Issue by multimeric** [dask/dask#9233]
This has been discussed in a piecemeal manner across a number of other issues, but it seems to me that dask could benefit from a type annotation overhaul to more widely apply type annotations. In particular Dask seems to be using Python>=3.8, so most of the type system should be available for systems that can run Dask already.

I'm happy to help with some of this, and actually I already started, but realised I hit a number of blockers that prevent this from being trivially implemented. Therefore I wanted to open this issue to discuss whether there is interest in a typing overhaul, and it yes, how to remove some of these blockers.

The first is the multiple dispatch system. Basically we have an object containing a dictionary that maps types to functions that apply to those types, e.g. if we pass in a tuple to `make_meta` we get back a `pd.Series`. I'm sympathetic to this idea (having experience with R and its multiple dispatch methods), but unfortunately it's totally incompatible with Python's current type annotations, because we are effectively adding new method overloads *at runtime*. Actually the only way I could devise to type this system without entirely rewriting it, is to have each `dispatch` instance have its own `Dispatch` subclass with a ton of `@overload`s. e.g.
```python
make_meta_dispatch = Dispatch("make_meta_dispatch")
```
becomes
```python
class MakeMetaDispatch(Dispatch):
    @overload
    def __call__(self, arg: tuple[str, np.dtype], *args, **kwargs) -> pd.Series:
        ...
    @overload
    def __call__(self, arg: dict[str, np.dtype], *args, **kwargs) -> pd.DataFrame:
        ...
    def __call__(self, arg, *args, **kwargs):
        super().__call__(arg, *args, **kwargs)

make_meta_dispatch = MakeMetaDispatch("make_meta_dispatch")
```
I think this would work, but it's a bit unfortunate because the dispatch system is no longer decentralised like it was before: all the overload types have to be specified at the time of dispatch creation, even if the actual method body does not. I'm not sure this would be acceptable to the designer of this multiple dispatch system in the first place, but maybe it would be an improvement?

Another issue is the docstring system. As far as I can tell, dask is using numpy docstrings, but [I don't believe that system supports type annotations](https://github.com/numpy/numpydoc/issues/196). What this effectively means is that you can to repeat yourself when you define the type signature and in the first line of the docstring. I'm not sure there's any easy solution that doesn't just involve using a different docstring style (like Google, which seems to handle this).

**Comment by pavithraes** [comment]
@multimeric Thanks for opening this! You may find https://github.com/dask/community/issues/255 interesting. :)

**Comment by multimeric** [comment]
Thanks for the link. It didn't come up in my search, I guess because it's in a different repo. Should I close this?

**Comment by ian-r-rose** [comment]
@multimeric Yes, I'd encourage you to weigh in with your thoughts on that issue and close this one, since there is still some active discussion over there around what best practices sould be within Dask. Thanks!

I've tried to annotate dispatching before as well, and have found it to be a tough one :)
