### ISSUE TITLE
"ArrowInvalid: Can't unify schema with duplicate field names" read parquet files from s3 using dask; 

### ISSUE THREAD

**Issue by naarkhoo** [dask/dask#9251]
using a query I dump data from redshift to parquet 

    UNLOAD
    ('
    SELECT
         delivered_at
        , flow_name
        , variant_name
        , user_id
    ') TO
                's3://data/raw/redshift/all_campaigns'
                IAM_ROLE 'arn:aws:iam::XYZ:role/redshift'
                FORMAT AS PARQUET
                maxfilesize 96 mb
                ALLOWOVERWRITE
                MANIFEST;

from the other end using `dask` I try to read a chunk of this data

    df = dd.read_parquet('s3://data/raw/redshift/all_campaigns0079_part_00.parquet')

/Users/fanbuch/Devel/NyRec/EDA.ipynb Cell 7' in <cell line: 1>()
----> 1 df = dd.read_parquet('s3://data/raw/redshift/crm/was_clicked/all_campaigns0079_part_00.parquet')

    File ~/opt/miniconda3/envs/deeprec/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py:460, in read_parquet(path, columns, filters, categories, index, storage_options, engine, calculate_divisions, ignore_metadata_file, metadata_task_size, split_row_groups, chunksize, aggregate_files, parquet_file_extension, **kwargs)
        457 if index and isinstance(index, str):
        458     index = [index]
    --> 460 read_metadata_result = engine.read_metadata(
        461     fs,
        462     paths,
        463     categories=categories,
        464     index=index,
        465     gather_statistics=calculate_divisions,
        466     filters=filters,
        467     split_row_groups=split_row_groups,
        468     chunksize=chunksize,
        469     aggregate_files=aggregate_files,
        470     ignore_metadata_file=ignore_metadata_file,
        471     metadata_task_size=metadata_task_size,
        472     parquet_file_extension=parquet_file_extension,
        473     **kwargs,
        474 )
        476 # In the future, we may want to give the engine the
        477 # option to return a dedicated element for `common_kwargs`.
    ...
    File ~/opt/miniconda3/envs/deeprec/lib/python3.9/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()
    
    File ~/opt/miniconda3/envs/deeprec/lib/python3.9/site-packages/pyarrow/error.pxi:100, in pyarrow.lib.check_status()
    
    ArrowInvalid: Can't unify schema with duplicate field names.

I am sure I don't have identical columns. Please help me improve the question quality if it is not clear.

**Comment by ian-r-rose** [comment]
Hi @naarkhoo, the error seems to be coming from `arrow`. Are you able to read the parquet file with only arrow or only pandas?

That is to say, if you do something like
```python
import pandas
df = pandas.read_parquet('s3://data/raw/redshift/all_campaigns0079_part_00.parquet')
```
do you get the same error? That would help determine whether this is a problem with dask or if it lies elsewhere.

**Comment by naarkhoo** [comment]
Thanks for your reply
it is not the same error but very similar, right ?


[image: image.png]

**Comment by naarkhoo** [comment]
Oh, I believe this is the same error

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?9f3139d5-cc3d-4ff3-a115-8127dd8e7a8b)
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
/Users/fanbuch/Devel/NyRec/EDA.ipynb Cell 9' in <cell line: 2>()
      [1](vscode-notebook-cell:/Users/fanbuch/Devel/NyRec/EDA.ipynb#ch0000031?line=0) import pandas
----> [2](vscode-notebook-cell:/Users/fanbuch/Devel/NyRec/EDA.ipynb#ch0000031?line=1) df = pandas.read_parquet('s3://data/raw/redshift/crm/was_clicked/all_campaigns0079_part_00.parquet')

File ~/opt/miniconda3/envs/deeprec/lib/python3.9/site-packages/pandas/io/parquet.py:493, in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    446 """
    447 Load a parquet object from the file path, returning a DataFrame.
    448 
   (...)
    489 DataFrame
    490 """
    491 impl = get_engine(engine)
--> 493 return impl.read(
    494     path,
    495     columns=columns,
    496     storage_options=storage_options,
    497     use_nullable_dtypes=use_nullable_dtypes,
    498     **kwargs,
    499 )

File ~/opt/miniconda3/envs/deeprec/lib/python3.9/site-packages/pandas/io/parquet.py:240, in PyArrowImpl.read(self, path, columns, use_nullable_dtypes, storage_options, **kwargs)
    233 path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
    234     path,
...
session_minutes: int64
__fragment_index: int32
__batch_index: int32
__last_in_fragment: bool
__filename: string
```

These are the versions
```

dask version        : '2022.6.0'
pyarrow version     : '8.0.0'
fastparquet version : '0.8.1'
```

**Comment by naarkhoo** [comment]
I also have asked the question on [stackoverflow](https://stackoverflow.com/questions/72899255/arrowinvalid-cant-unify-schema-with-duplicate-field-names-read-parquet-files?noredirect=1#comment128762563_72899255)

**Comment by naarkhoo** [comment]
it turned out indeed there were two columns with identical col_names; I wish the library was smarter than that.
