### ISSUE TITLE
404 dask dashboard

### ISSUE THREAD

**Issue by nikhil003** [dask/dask#9254]
When running jupyterlab on a local ubuntu machine, I notice the following in the logs.

**What happened**:

![image](https://user-images.githubusercontent.com/5336184/177917129-fbd9f44a-806b-41b5-8d54-58a7904e71f8.png)

**What you expected to happen**:

I expected the dashboard to work and not encounter the 404.

**Anything else we need to know?**:

When I look try to access https://localhost:8787, I encounter the following

![image](https://user-images.githubusercontent.com/5336184/177917459-e0cadcff-b4b1-44cd-953f-1b771ff7d51d.png)

**Environment**:

- Dask version: 2022.2.1
- Distributed version: 2022.2.1
- Bokeh version: 2.4.2
- Python version: 3.9.10
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): conda (conda-forge channel)

**Comment by pavithraes** [comment]
@nikhil003 Welcome and thanks for reporting!

I believe this is similar to: https://github.com/dask/dask-labextension/issues/164?

If so, I'd suggest moving this question to that issue and closing this one. :) You can also try out some solutions described there like clearing the URL and updating the version of dask-labextension.

**Comment by jrbourbeau** [comment]
Closing in favor of https://github.com/dask/dask-labextension/issues/164
