### ISSUE TITLE
Use consistent variable names for pandas and dask dataframes in groupby docs

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#9263]
In this docs https://github.com/dask/dask/blob/main/docs/source/dataframe-groupby.rst we are using df in some places for pandas dataframes and in other palces for dask dataframes. There is also mention to `ddf` and `df_dask`. 

For example:

df (pandas):

```python
>>> df = pd.DataFrame({
...   'a': ['a', 'b', 'a', 'a', 'b'],
...   'b': [0, 1, 0, 2, 5],
... })
>>> ddf = dd.from_pandas(df, 2)
```

df (dask)
```python
df.set_index(column, shuffle='disk')
df.set_index(column, shuffle='tasks')
```

We should consolidate names and us `df` only for pandas dataframes and `ddf` for dask ones.

**Comment by ivojuroro** [comment]
Hello, I'd like to work on this issue.

**Comment by Alcadeus0** [comment]
Hello, @ivojuroro are you still working on this issue? I'd like to help out as well :)

**Comment by ivojuroro** [comment]
Hi @Alcadeus0 yes, I am! I was having issues when running tests. I'll post here my issues so that we can check. It that's ok for you.

**Comment by ncclementi** [comment]
@ivojuroro this is a fix to the docs, so tests should not be breaking because of your modification. Feel free to open a PR and that will trigger CI, and we can help from there. If you are not super happy with the PR, you can open it as a "work in progress", it doesn't have to be perfect the first time, we can iterate from there.

**Comment by ivojuroro** [comment]
Actually it was with the `make html`  that I was having problems. 
I have created the PR here #9304
