### ISSUE TITLE
repartition documentation doesn't specify whether the size will be reflected on output

### ISSUE THREAD

**Issue by drstewart19** [dask/dask#9276]
Noticed a difference between memory usage and storage size and I think this would be a good thing to note within the documentation that partition sizes won't necessarily be reflected when storing on disk. Moving the issue here from https://github.com/geopandas/dask-geopandas/issues/210#issue-1306025315

**Comment by pavithraes** [comment]
@drstewart19 Welcome, and thanks for opening this issue! I agree the docs can be improved here, would you be interested in submitting a PR?

**Comment by drstewart19** [comment]
@pavithraes thank you for the welcome! I am more than happy to submit a PR.
