### ISSUE TITLE
SLURMCluster modifies a deprecated flag

### ISSUE THREAD

**Issue by ikabadzhov** [dask/dask#9287]
When I want to create a SLURM cluster and specify `process = X ` in the constructor, by looking at the job script, I see that the command that is run has a flag `--nprocs X`.

That currently does not error. However, referring to https://docs.dask.org/en/stable/deploying-ssh.html#cmdoption-dask-ssh-nworkers `--nprocs` is deprecated.

I tried to pass as an `extra = ['--nworkers X']`, but then from another terminal I saw that my job got kicked from the squeue. And the terminal where I started the program, remains in a "wait state". I created a standalone SLURM script passing both `--nprocs` and `--nworkers`, but then I get: `ERROR - Both --nprocs and --nworkers were specified. Use --nworkers only.`

Request: would it be possible to translate the input of `process = ` in the SLURMCluster constructor to `--nworkers`, but not `--nprocs`.

**Comment by douglasdavis** [comment]
Hi @ikabadzhov, I assume you're using`dask_jobqueue` to create your SLURM cluster? If that's the case, it may be better to raise the issue in the https://github.com/dask/dask-jobqueue issue tracker
