### ISSUE TITLE
Dask angle() function + Cupy are reporting errors in different versions

### ISSUE THREAD

**Issue by jcfaracco** [dask/dask#9296]
**What happened**:

To reproduce this issue, I'm running a simple code like the one below.

```python
import cupy as cp
import dask.array as da

in_shape = (20, 20, 20)
in_shape_chunks = (5, 5, 5)

rng = cp.random.default_rng(seed=42)
in_data = rng.random(in_shape)

in_data = da.from_array(in_data, chunks=in_shape_chunks)

angle = da.angle(in_data)

np_angle = angle.compute()
```

After executing the code snippet above, I get the following error:

```python
AttributeError: 'cupy._core.core.ndarray' object has no attribute '__array_wrap__'
```

When I move to Dask **2022.7.0**, I get the error below:

```python
TypeError: Cannot convert numpy.bool_ to cupy._core.core.ndarray
```

According some old bugs it is clear that CuPy does not have `__array_wrap__` implemented. Other Dask issues with other functions were fixed, but apparently, `dask.array.angle()` is still buggy.

**What you expected to happen**:

This code should run without any issue. Especially, because it is a simple one. Obviously, it is an error associated more with CuPy.

**Environment**:

- Dask version: 2021.11.2 and 2022.7.0
- Python version: Python 3.8.12
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): using RAPIDS AI docker image: rapidsai/rapidsai:21.12-cuda11.2-runtime-ubuntu20.04-py3.8

**Comment by pavithraes** [comment]
@jcfaracco Thanks for reporting! I think it might be better to move this to the [cupy issue tracker](https://github.com/cupy/cupy/issues)?

**Comment by jrbourbeau** [comment]
@jcfaracco do you have a pull traceback you could post? Also cc @pentschev

**Comment by quasiben** [comment]
This looks like something odd is happening with numpy/dask dispatching.  It looks like Numpy+Cupy is ok but wrapping a dask.array around cupy then calling angle leads to an implicit change for the metadata/chunktype:


```python
In [1]: import dask.array as da

In [2]: import cupy

In [3]: import numpy as np

In [4]: type(np.angle(cupy.arange(10)))
Out[4]: cupy._core.core.ndarray

In [5]: rs = da.random.RandomState(RandomState=cupy.random.RandomState)

In [6]: np.angle(rs.random(size=(1, 10)))
Out[6]: dask.array<angle, shape=(1, 10), dtype=float64, chunksize=(1, 10), chunktype=numpy.ndarray>
```

**Comment by pentschev** [comment]
The issue here is `cupy.angle()` does not support the `deg` kwarg:

```python
In [1]: import numpy as np, cupy as cp

In [2]: np.angle(np.arange(10))
Out[2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]: np.angle(np.arange(10), deg=True)
Out[3]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]: np.angle(cp.arange(10))
Out[4]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]: np.angle(cp.arange(10), deg=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 np.angle(cp.arange(10), deg=True)

File <__array_function__ internals>:5, in angle(*args, **kwargs)

File cupy/_core/core.pyx:1613, in cupy._core.core.ndarray.__array_function__()

File cupy/_core/_kernel.pyx:1188, in cupy._core._kernel.ufunc.__call__()

TypeError: Wrong arguments {'deg': True}
```

The `deg` kwarg is embedded in the Dask array dispatcher: https://github.com/dask/dask/blob/cfaf931072ae079313761d4d61e25956029abf6c/dask/array/ufunc.py#L282-L287 

@jcfaracco I would encourage you to file a feature request in the [CuPy issue tracker](https://github.com/cupy/cupy/issues), once `cupy.angle()` supports the `deg` kwarg, this issue should be automatically fixed.

**Comment by jcfaracco** [comment]
@pentschev.... done: https://github.com/cupy/cupy/issues/6900

**Comment by jrbourbeau** [comment]
Thanks @jcfaracco! It looks like there's already been a fix merged into `cupy` (xref https://github.com/cupy/cupy/pull/6905). Does `cupy` have nightly builds? I wonder if it's easy for us to test whether or not this issue can be closed

**Comment by pentschev** [comment]
I installed CuPy from source and tested locally:

```python
In [1]: import numpy as np, cupy as cp, dask.array as da

In [2]: cp.__version__  # Actually running +g8e0e07f81
Out[2]: '11.0.0rc1'

In [3]: np.angle(cp.arange(10), deg=True)
Out[3]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]: rs = da.random.RandomState(RandomState=cp.random.RandomState)

In [5]: np.angle(rs.random(size=(1, 10)))
Out[5]: dask.array<angle, shape=(1, 10), dtype=float64, chunksize=(1, 10), chunktype=cupy.ndarray>

In [6]: np.angle(rs.random(size=(1, 10))).compute()
Out[6]: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]: type(np.angle(rs.random(size=(1, 10))).compute())
Out[7]: cupy.ndarray
```

Also submitted https://github.com/dask/dask/pull/9312 to test `cupy.angle`. Tests will only run on CuPy 11.0.0rc2+ (rc2 doesn't exist yet).
