### ISSUE TITLE
Mismatched columns created after get_dummies() [ValueError: Order of columns does not match]

### ISSUE THREAD

**Issue by DRudel** [dask/dask#9297]
This may be related to [6865](https://github.com/dask/dask/issues/6856)
**What happened**: I called `get_dummies()` and then called head() to check results. I got a ValueError: Mismatched columns

**What you expected to happen**: Top 5 rows of new version are printed

**Minimal Complete Verifiable Example**: 

```python
my_dd = dd.read_csv('repro.csv')
my_dd = my_dd.categorize(my_dd.columns)
my_dd = dd.reshape.get_dummies(my_dd)
print(my_dd.head())
```

**Anything else we need to know?**: The order of the E columns is switched between `actual` and `meta`. When using pycharm debugger to inspect columns, prior to calling `head()`, the columns are in the correct order, but somehow the two E columns (E_1.0 and E_0.0) get switched in `actual` at some point without being switched in `meta`.

**Environment**:

- Dask version: 2022_7.0
- Python version: 3.9
- Operating System: Windows (WinPython)
- Install method (conda, pip, source): pip
[repro.csv](https://github.com/dask/dask/files/9155952/repro.csv)

**Comment by pavithraes** [comment]
@DRudel Welcome, and thank you for reporting!

This is the same as #9258 and the fix (#9264) was merged just this week. :)

Closing as resolved!
