### ISSUE TITLE
Mask preserving *_like functions

### ISSUE THREAD

**Issue by rcomer** [dask/dask#9301]
It would be useful to have versions of `ones_like`, `zeros_like` and `empty_like` that preserve masks when applied to masked dask arrays.  Currently (version 2022.7.1) we have

```python
import dask.array as da

array = da.ma.masked_array([2, 3, 4], mask=[0, 0, 1])
print(da.ones_like(array).compute())
```
```
[1 1 1]
```
whereas numpy's version preserves the mask
```python
import numpy as np

print(np.ones_like(array.compute()))
```
```
[1 1 --]
```

I notice there are several functions in `dask.array.ma` that just apply `map_blocks` to the `numpy.ma` version of the function.  So perhaps the simplest thing would be to implement `dask.array.ma.ones_like`, etc. that way.  If it really is that simple, I'd be happy to open a PR.

**Comment by pavithraes** [comment]
@rcomer Thanks for reporting!

> If it really is that simple, I'd be happy to open a PR.

I think this should mostly work.

However, I'd first like to confirm that this isn't related to  `https://github.com/numpy/numpy/issues/15200` -- what do you think about this? 

cc @jsignell for visibility

**Comment by rcomer** [comment]
Thanks @pavithraes.  I'm afraid my understanding of the `__array_ufunc__` and `__array_function__` methods is not very deep.  However, looking at dask's current implementation of these `*_like` functions, they just pass straight to `ones`, etc, which I think can only ever return an unmasked array.
https://github.com/dask/dask/blob/50ab8af982a31b186a8e47597f0ad7e5b59bcab5/dask/array/creation.py#L124-L133

**Comment by jsignell** [comment]
In principle this approach seems fine to me. I think masked arrays are kind of under-supported in Dask in general. So this kind of work is definitely appreciated!

**Comment by rcomer** [comment]
Thanks @jsignell.  I'll put a PR up when I have some time.
