### ISSUE TITLE
Document Dask DataFrame `Index` methods in the API reference

### ISSUE THREAD

**Issue by pavithraes** [dask/dask#9308]
We have some methods that operate on Dask DataFrame Index (sometimes this is slightly different from how they operate on DataFrame/Series, eg: #9290). It'll be nice to document these. 

Maybe we can have a new section `Index` after `Series` here: https://docs.dask.org/en/stable/dataframe-api.html, which will include the methods defined in https://github.com/dask/dask/blob/6bad4c200bea46c76023c52fdf720200881eadda/dask/dataframe/core.py#L4096

cc @ncclementi @jsignell

**Comment by anandhakrishnanaji** [comment]
Hey I am new to open source, can I take up this issue?

**Comment by jrbourbeau** [comment]
Welcome @anandhakrishnanaji! You don't need to ask permission to work on an issue. See https://docs.dask.org/en/stable/develop.html for documentation on setting up a local development environment, how to build the docs, etc.
