### ISSUE TITLE
Verify `test_getitem_avoids_large_chunks_missing`

### ISSUE THREAD

**Issue by pavithraes** [dask/dask#9310]
`test_getitem_avoids_large_chunks_missing` here xfails for `chunks= ((np.nan, np.nan, np.nan, np.nan), (500,), (500,))`:

https://github.com/dask/dask/blob/00c8ec3e613c38af646ebc5c7ea4a60d562f6270/dask/array/tests/test_slicing.py#L919-L939

However, since we've resolved #6586, should we consider removing/updating this test case?

Also, note that #9235 updated the `warnsize` calculation. So we may need to verify if `with dask.config.set({"array.slicing.split-large-chunks": True})` is actually needed currently or if we need to increase the chunk sizes to make it relevant.

@TomAugspurger Do you have thoughts on this?

cc @ncclementi

**Comment by TomAugspurger** [comment]
+1 to removing this test now that similar behavior is covered in https://github.com/dask/dask/pull/9285/files#diff-b5399612ab748a4abf814ff106dd94eec7c8379b0e0f4e51ffcd8599d6353ef1R424.

I'm *guessing* the config is still needed, but I might be wrong.

**Comment by pavithraes** [comment]
@TomAugspurger Thank you!

@ncclementi and I looked into it. We aren't sure what this test is doing. We have a few thoughts, could you please help confirm if our understanding is accurate?

Based on the comment on line 930, it looks like we're testing for: when we have unknown chunks, we shouldn't get the `PerformanceWarning` about large chunks.

In the current state, this test doesn't fail if we remove the config and `arr._chunks = chunks`. This is probably because `arr` never reaches the default `chunk-size` -- so the fix could be that we set a small `chunk-size` with the config.

Next, `dask.config.set({"array.slicing.split-large-chunks": True})` is generally used to silence the `PerformanceWarning`, and from what we can tell, in this test we want it to emit that warning if the chunks are known. So, I think we probably don't need this config?

I've opened a PR with these changes, we can also continue the discussion there. :)
