### ISSUE TITLE
Contiguous order of arrays not preserved by dask.

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#9316]
Contiguous order of arrays not preserved by dask.

This may not be an actual problem, but I thought I should report this anomaly.

**What happened**:
When I do a round trip from numpy -> dask -> numpy, the contiguous order of the original array is not preserved. Dask seems to always produce c contiguous arrays as the output at `.compute()`

**What you expected to happen**:
I expected the order to be preserved.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
 mport numpy as np

numpy_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], order="F")
print(numpy_array.flags)
#  C_CONTIGUOUS : False
#  F_CONTIGUOUS : True
#  OWNDATA : True
#  WRITEABLE : True
#  ALIGNED : True
#  WRITEBACKIFCOPY : False
#  UPDATEIFCOPY : False

dask_array = da.from_array(numpy_array, chunks=(2,2))
dask_array.compute().flags
#  C_CONTIGUOUS : True
#  F_CONTIGUOUS : False
#  OWNDATA : True
#  WRITEABLE : True
#  ALIGNED : True
#  WRITEBACKIFCOPY : False
#  UPDATEIFCOPY : False
```

See how the original numpy array is F_CONTIGUOUS, but becomes C_CONTIGUOUS after being loaded in & out of dask.

It looks like dask always produces C_CONTIGUOUS output, regardless of what the input was.

**Anything else we need to know?**:
This isn't causing any actual problems for me, or anyone else I know. I just discovered it while doing something else.

If no-one considers it very serious (or this is expected behaviour), the fix for this issue could be a documentation update. I did a quick search of the docs and didn't find anything much there already. Although there are a lot of "order" kwargs scattered around the dask code, so it does give the impression you can control it with dask.

**Environment**:

- Dask version: 2021.12.0+412.gf4ea994a
- Python version: 3.9.13
- Operating System: M1 Macbook, running Monteray
- Install method (conda, pip, source): pip editable installation from current main branch

**Comment by pavithraes** [comment]
Interesting, thanks for sharing @GenevieveBuckley!

I'd expect Dask to preserve the order, especially if we set `asarray=True` in `from_array`, because `da.asarray` seems to preserve order:

```python
dask_array = da.from_array(numpy_array, chunks=(2,2), asarray=True)
dask_array.compute().flags
# C_CONTIGUOUS : True
# F_CONTIGUOUS : False
# OWNDATA : True
# WRITEABLE : True
# ALIGNED : True
# WRITEBACKIFCOPY : False
# UPDATEIFCOPY : False

dask_array_2 = da.asarray(numpy_array)
dask_array_2.compute().flags
# C_CONTIGUOUS : False
# F_CONTIGUOUS : True
# OWNDATA : True
# WRITEABLE : True
# ALIGNED : True
# WRITEBACKIFCOPY : False
# UPDATEIFCOPY : False
```

I also agree that we can better document this behaviour regardless. :)

@jsignell I see you[ added support for `order` and `dtype` for `da.asarray` and `da.asanyarray`](https://github.com/dask/dask/pull/8106), what do you think about this issue?

**Comment by jsignell** [comment]
So I did! I will take a look now and see if it's easy to add support in the `from_array` case.

**Comment by jsignell** [comment]
Ok I took a quick look and it doesn't look straightforward. I think we should add a line to the docs and call it a day unless someone expresses a need for this.

**Comment by GenevieveBuckley** [comment]
Agreed, that sounds like a good way to handle things.
