### ISSUE TITLE
Dask array `astype` method does not support `order` keyword argument

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#9318]
**What happened**:
The `astype` method for numpy arrays allows an `order` keyword argument, but the same keyword argument in dask causes an error.

**What you expected to happen**:
I expected the same behaviour as numpy. There are many other places in the dask code repository that include an `order` keyword argument.

**Minimal Complete Verifiable Example**:

```python
import numpy as np

numpy_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], order="C")
print(numpy_array.dtype)
print(numpy_array.flags)
converted_numpy_array = numpy_array.astype(float, order="F")
print(converted_numpy_array.dtype) # array is now float type
print(converted_numpy_array.flags) # array is now F_CONTIGUOUS


import dask.array as da

dask_array = da.from_array(numpy_array)
converted_dask_array = dask_array.astype(float, order="F") # ERROR!
```

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 dask_array.astype(float, order="F")

File ~/Documents/GitHub/dask/dask/array/core.py:2239, in Array.astype(self, dtype, **kwargs)
   2237 extra = set(kwargs) - {"casting", "copy"}
   2238 if extra:
-> 2239     raise TypeError(
   2240         f"astype does not take the following keyword arguments: {list(extra)}"
   2241     )
   2242 casting = kwargs.get("casting", "unsafe")
   2243 dtype = np.dtype(dtype)

TypeError: astype does not take the following keyword arguments: ['order']
```

**Anything else we need to know?**:
Dask doesn't seem like it preserves the contiguous order of arrays (unrelated to this issue). That makes debugging a bit more complicated. See https://github.com/dask/dask/issues/9316

**Environment**:

- Dask version: 2021.12.0+411.gc98fab71
- Python version: 3.9.13
- Operating System: M1 Macbook, running Monteray
- Install method (conda, pip, source): pip editable installation from current main branch

**Comment by GenevieveBuckley** [comment]
Here's someone else having the same problem (this time using `dask.array.to_zarr` which eventually calls `astype`): https://github.com/zarr-developers/zarr-python/issues/962#issuecomment-1195084096

**Comment by pavithraes** [comment]
I believe #9317 resolves this issue, thanks you `@GenevieveBuckley`!
