### ISSUE TITLE
Document how to insert keyword arguments into custom dask task graphs

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask#9321]
I think we should add a section to [the docs page on custom dask task graphs](https://docs.dask.org/en/stable/custom-graphs.html) to include information on how to use keyword arguments.

> FYI, I'm using [this trick Matt Rocklin suggests](https://stackoverflow.com/questions/50861900/including-keyword-arguments-kwargs-in-custom-dask-graphs) to insert a keyword argument into a dask task:
>
> ```python
> from dask.utils import apply
> task = (apply, func, args, kwargs)  # func(*args, **kwargs)
> ```
>
> It's a useful trick, and one that should possibly be documented here too: https://docs.dask.org/en/stable/custom-graphs.html

_Originally posted by @GenevieveBuckley in https://github.com/dask/dask/issues/9320#issuecomment-1196538984_

**Comment by pavithraes** [comment]
Closing as #9322 has now been merged. :)
