### ISSUE TITLE
Remove `werkzeug` pin in CI

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9323]
It looks like out test suite is consistently hanging in PRs (e.g. [see this build](https://github.com/dask/dask/runs/7527674753?check_suite_focus=true)) and `main` (e.g. [see this build](https://github.com/dask/dask/runs/7529722100?check_suite_focus=true)). I've not yet had a chance to dig deeper, but wanted to raise an issue for visibility

cc @jsignell @pavithraes @ncclementi

**Comment by jrbourbeau** [comment]
@pavithraes I know your work day is almost over -- @ncclementi do you have bandwidth to look into this?

**Comment by ncclementi** [comment]
There were multiple cases where CI was hanging and it seems to be happening in `test_distributed.py::test_blockwise_dataframe_io` but I can't reproduce locally with the latest `dask` and `distributed`. I tried also exact versions of distributed pining matching the CI run one, and I can't reproduce it either 

This is also hanging https://github.com/dask/dask/runs/7544919727?check_suite_focus=true

**Comment by jrbourbeau** [comment]
Ended up pinning `werkzeug` over in https://github.com/dask/dask/pull/9325 (there are more details in the PR). Going to keep this issue open as a reminder to removing the package pinning
