### ISSUE TITLE
`delayed` can't handle some `dataclasses` as inputs

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9324]
Someone reported offline that the following snippet fails:

```python
from dask import delayed
from dataclasses import dataclass

@delayed
def noop(x):
    return x


@dataclass
class MyDataClass:
    arg1: int
    def __init__(self, arg):
        self.arg1 = arg

d = noop(MyDataClass(1))
d.compute()
```

with this traceback:

```python
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test.py", line 16, in <module>
    d.compute()
  File "/Users/james/projects/dask/dask/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/james/projects/dask/dask/dask/base.py", line 598, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/james/projects/dask/dask/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/james/projects/dask/dask/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/james/projects/dask/dask/dask/local.py", line 319, in reraise
    raise exc
  File "/Users/james/projects/dask/dask/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/utils.py", line 41, in apply
    return func(*args, **kwargs)
TypeError: MyDataClass.__init__() got an unexpected keyword argument 'arg1'
```

I've not looked deeply into this yet, but after quickly skimming it looks like this section of code 

https://github.com/dask/dask/blob/335882ef60f646c3aeb9234c431a6e1a87224eed/dask/delayed.py#L113-L122

if where this start to go awry

**Comment by ian-r-rose** [comment]
Thanks for the initial investigation and nice reproducer @jrbourbeau!

I think there is likely a limit to our support for dataclasses here. If there is a dataclass with a custom `__init__` signature, then our logic for reconstituting the instance after computing any collections in its fields will, in general, be wrong. That being said, I think the following would be a big improvement:

1. When unpacking dataclasses, test to see if they have a custom `__init__`. If that's the case, give up with a helpful error. I actually don't think there is a 100% solution to this, but we *can* do a reasonable attempt with something like the following:
    ```python
    from dataclasses import replace
    try:
        replace(expr)
    except TypeError:
        raise TypeError("Failed to unpack dataclass, perhaps it has a custom __init__, which is unsupported")
    ````
    I do think there are some pathological cases that this would miss (e.g., a custom `__init__` could permute attribute names and things would silently be wrong). But I think this would catch most real-world problems like the above.
2. If the unpacking process for a dataclass reveals no embedded dask collections, then we actually don't need to ever reconstitute it at all. We can just let it be pickled as an opaque python value and move on. This would allow the above code snippet to succeed.

Thoughts?

**Comment by hendrikmakait** [comment]
One alternative approach would be not to compose a new instance of the dataclass but to replace those fields that (transitively) contain embedded dask collections. Within the body of `unpack_collections` we could then set those fields to None or some other placeholder and the returned functions would set those fields to the actual values once we evaluated them. This way, we'd avoid problems with custom `__init__` functions or existing fields with `init=False`.

I do lack context however whether mutating the objects would be fine or breaking some invariant of `update_collections` or calling code.
