### ISSUE TITLE
Import time penalty from versioneer

### ISSUE THREAD

**Issue by neutrinoceros** [dask/dask#9327]
**What happened**:
`import dask` takes a noticeable runtime penalty because the `dask.__version__`'s computation with versioneer is expensive

**What you expected to happen**:

import time should be as short as possible

**Minimal Complete Verifiable Example**:
Here's how I profiled dask's import time
```shell
python -X importtime -c "import dask" 2> tuna.log && tuna tuna.log
```

current state (notice the white overhead on the right, which accounts for ~30% of the total)
![Screenshot 2022-07-28 at 11 22 46](https://user-images.githubusercontent.com/14075922/181471953-f66dc6db-4256-400a-bb25-76e0ca528211.png)

and with the following trivial patch
```patch
diff --git a/dask/__init__.py b/dask/__init__.py
index 8b7dad5a..bd815066 100644
--- a/dask/__init__.py
+++ b/dask/__init__.py
@@ -1,5 +1,4 @@
 from dask import config, datasets
-from dask._version import get_versions
 from dask.base import (
     annotate,
     compute,
@@ -12,7 +11,3 @@ from dask.core import istask
 from dask.delayed import delayed
 from dask.local import get_sync as get

-versions = get_versions()
-__version__ = versions["version"]
-__git_revision__ = versions["full-revisionid"]
-del get_versions, versions
```
![Screenshot 2022-07-28 at 11 23 24](https://user-images.githubusercontent.com/14075922/181472271-8275060e-6da6-47c9-b700-edee35912c5c.png)

**Anything else we need to know?**:
Of course I don't mean that `dask.__version__` should be dropped. I would suggest instead migrating from `versioneer` to `setuptools_scm`, which puts the computation cost at compilation time rather than at runtime.

**Environment**:

- Dask version: master (50ab8af982a31b186a8e47597f0ad7e5b59bcab5)
- Python version: 3.10.4
- Operating System: macOS
- Install method (conda, pip, source): source

**Comment by TomAugspurger** [comment]
Doesn't versioneer only have a runtime cost during development? I thought that the version number is hardcoded as part of the release build.

**Comment by neutrinoceros** [comment]
Oh I guess you're right. I did not realise. Welp I guess you can close this then.

**Comment by ncclementi** [comment]
Closing as this seems to not be an issue according to the previous two comments.

**Comment by TomAugspurger** [comment]
Just a note: I was going by memory of how versioneer behaves. It's possible I could be wrong :)

**Comment by neutrinoceros** [comment]
Don't worry about it I actually checked. Thanks again !
