### ISSUE TITLE
SciPy 1.9.0 compatibility

### ISSUE THREAD

**Issue by pavithraes** [dask/dask#9335]
SciPy 1.9.0 was released last week, and we have a related test failure.

[`dask/array/tests/test_linalg.py::test_solve_sym_pos`](https://github.com/dask/dask/runs/7617507756?check_suite_focus=true#step:6:22380) fails with:
```
DeprecationWarning: The 'sym_pos' keyword is deprecated and should be replaced by using 'assume_a = "pos"'. 'sym_pos' will be removed in SciPy 1.11.0.
```

**Comment by jrbourbeau** [comment]
Thanks for flagging this @pavithraes! Do you have bandwidth to look into this?

**Comment by pavithraes** [comment]
@jrbourbeau Yes, I'm looking into it. :)

**Comment by jrbourbeau** [comment]
Woo, thank you!
