### ISSUE TITLE
Extracting Small Subset of Large Dataset Taking Hours

### ISSUE THREAD

**Issue by lassiterdc** [dask/dask#9343]
Hello, I am attempting to extract a dataset with dimensions 14x25x7177 and datatype float32 (around 9.58 MiB in size) from a large (655.04 GiB uncompressed) dataset but it's taking hours. I am wondering whether it's user error or if this is the best I can do.

**Data**: [10-days of nationwide radar rainfall data in netcdf form (6.72GB)](https://www.dropbox.com/sh/78c986xgiwf7w6a/AADrPhbLFraxYcwtcJFH2vW_a?dl=0) (link is to a dropbox folder, it might take ~1 hour from the time this is posted for the data to finish uploading)

**Reproducible code:**
```python
import xarray as xr
import dask

dask.config.set({"array.slicing.split_large_chunks": True})

f_in_ncs = "data/*.nc"
chnk_sz = "1000MB"

mrms = xr.open_mfdataset(f_in_ncs,  concat_dim = "time",
            chunks={'time':chnk_sz},
            combine = "nested", engine = 'netcdf4')

idx = {'outlat': [1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815,
        1816, 1817, 1818],
        'outlon': [5362, 5363, 5364, 5365, 5366, 5367, 5368, 5369, 5370, 5371, 5372,
        5373, 5374, 5375, 5376, 5377, 5378, 5379, 5380, 5381, 5382, 5383,
        5384, 5385, 5386]}

mrms_subset= mrms[idx]

mrms_subset= mrms_subset.chunk(chunks={"time":chnk_sz})

df = mrms_subset.rainrate.to_dataframe()
```

**Comment by jsignell** [comment]
You might want to cross-post this on the xarray issue tracker, but at first glance it looks like your data is chunked long the time dimension and you are trying to access a slice in space. This means that you need to read from every chunk. 

A couple things look kind of odd to me about this snippet (I didn't try to run it)
1. Those don't look like lat/lon values. Are they maybe the index instead? If so I am not sure that what you have works.
2. I have never seen a dict being used like `mrms[idx]`. Did you maybe intend to use `mrms.slice` instead?
3. It doesn't seem wise to call `chunk` on the subset. Once your xarray object contains a dask array, you shouldn't have to explicitly set chunks.

**Comment by lassiterdc** [comment]
Thanks for taking a look! The format of the netcdf is not ideal - I had to make it that way to play nice with a piece of software that someone else wrote. `outlat` and `outlon` are integer indices whereas actual geospatial coordinates are recorded in the `latitude` and `longitude` data variables. Slicing an xarray dataset by dimension name and integer indices with that kind of syntax (`mrms[idx]`, with `idx` being a dictionary of dimension names and integer indices) is based on [xarray indexing and slicing documentation here](https://docs.xarray.dev/en/stable/user-guide/indexing.html#quick-overview) and on second review I think I'm doing that part right.

However! I think you found the problem and the solution. Chunking only by the `time` variable meant that basically the entire dataset would have ultimately have to be passed through short term memory. When I also chunk by `outlat` and `outlon`, the run-time drops form hours to about 45 seconds. If you or anyone else have additional suggestions on further reducing runtime, I am all ears but I think we can consider this problem solved!

**Comment by lassiterdc** [comment]
One other bit of odd behavior I'm noticing. The following line of code will assign `time` a maximum chunk size of 719 no matter what chunk size I assign (here it's 1000). I'm guess the maximum chunk size for a dimension is limited by the individual netcdf files that comprise the dataset which have a minimum `time` dimensions size of 719. That probably has more to do with xarray than dask but I figured this thread is the place to mention it. I was hoping I could input multiples of 719 but that does not appear to be the case.
```python
mrms = xr.open_mfdataset(f_in_ncs,  concat_dim = "time",
            chunks={'outlat':20 'outlon':20, , 'time':1000},
            combine = "nested", engine = 'netcdf4')
```
