### ISSUE TITLE
Performance hit with da.delayed processing in dask 2022080 vs 2022070

### ISSUE THREAD

**Issue by jluethi** [dask/dask#9389]
**What happened**:
We're using dask.delayed to process Zarr files, see here for details: https://dask.discourse.group/t/using-da-delayed-for-zarr-processing-memory-overhead-how-to-do-it-better/1007
The actual processing may not be optimal and we're looking to make it more memory efficient (separate discussion in the forum post). While doing that, I tested the new `2022080` release. It is about 25x slower for our approach of using a dask.delayed function to process the Zarr array in dask release `2022080` than in dask `2022070` (or than in `2022011`). The full line is `2022080`, the dotted line is `2022070`
![Indexing202207_vs_202208](https://user-images.githubusercontent.com/18033446/185152944-55b2d9ac-34ef-42a0-b2de-b6ebcac892c0.png)

**What you expected to happen**:
I would expect the performance to be the same/similar.

**Minimal Complete Verifiable Example**:

```python
# Generate some synthetic Zarr file of varying size:
import numpy as np
import dask.array as da
import dask


shapes = [
    (2, 2, 16000, 16000),
    (2, 4, 16000, 16000),
    (2, 8, 16000, 16000),
    (2, 16, 16000, 16000),
]

for shape in shapes:
    shape_id = f"{shape}".replace(",", "").replace(" ", "_")[1:-1]
    x = da.random.randint(0, 2 ** 16 - 1,
                          shape,
                          chunks=(1, 1, 2000, 2000),
                          dtype=np.uint16)
    x.to_zarr(f"data_{shape_id}.zarr")

# Our processing functions
SIZE = 2000
# Function which increases value of each index in 
# a SIZExSIZE image by one (=> pseudo-processing)
def shift_img(img):
    return img.copy() + 1

delayed_shift_img = dask.delayed(shift_img)

def process_zarr(input_zarr):
    out_zarr = f"out_{input_zarr}"
    data_old = da.from_zarr(input_zarr)
    data_new = da.empty(data_old.shape,
                        chunks=data_old.chunks,
                        dtype=data_old.dtype)

    n_c, n_z, n_y, n_x = data_old.shape[:]

    print(f"Input file: {input_zarr}")
    print(f"Output file: {out_zarr}")
    print("Array shape:", data_old.shape)
    print("Array chunks:", data_old.chunks)
    print(f"Image size: ({SIZE},{SIZE})")


    for i_c in range(n_c):
        for i_z in range(n_z):
            for i_y in range(0, n_y - 1, SIZE):
                for i_x in range(0, n_x - 1, SIZE):
                    # Need to do this in 2 steps to avoid a
                    # TypeError: Delayed objects of unspecified length have no len()
                    new_img = delayed_shift_img(data_old[i_c, i_z, i_y:i_y+SIZE, i_x:i_x+SIZE])
                    data_new[i_c, i_z, i_y:i_y+SIZE, i_x:i_x+SIZE] = da.from_delayed(new_img,
                                                                                     shape=(SIZE, SIZE),
                                                                                     dtype=data_old.dtype)


    # Write data_new to disk (triggers execution)
    data_new.to_zarr(out_zarr)

    # Clean up output folder
    shutil.rmtree(out_zarr)

# Code to run the analysis
input_zarrs = ['data_2_2_16000_16000.zarr', 'data_2_4_16000_16000.zarr', 'data_2_8_16000_16000.zarr', 'data_2_16_16000_16000.zarr']
for input_zarr in input_zarrs:
    interval = 0.1
    mem = memory_usage((process_zarr, (input_zarr,)), interval=interval)
    time = np.arange(len(mem)) * interval
    mem_file = "log_memory_" + input_zarr.split(".zarr")[0] + "_.dat"
    print(mem_file)
    np.savetxt(mem_file, np.array((time, mem)).T)

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022070 vs. 2022080
- Python version: 3.9.12
- Operating System: macOS 12.5
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for reporting @jluethi. Looking at the `git log` between the `2022.07.0` and `2022.08.0` releases nothing seems like an obvious culprit. Are you able to run `git bisect` to determine which PR lead to a change in behavior?

Also, just to double check, are you using a local scheduler or a distributed cluster? From the example, it looks like a local cluster, but just wanted to confirm

**Comment by jluethi** [comment]
Thanks @jrbourbeau , will try to narrow it down with `git bisect`. As the only differentiating factor I could find is runtime, it may take a bit. Will report back when I manage to narrow it down.

And yes, just using the local scheduler both for this example as well as in general. 

(We're currently using [parsl](https://parsl-project.org) for orchestration on our cluster to handle some further complexities and use dask within each larger job to parallelise further within each node that we run a job on.)

**Comment by jluethi** [comment]
@jrbourbeau Ok, ran git bisect, thanks a lot for pointing me there, that's a really useful tool!

Using that, I found the issue first at ac74939697c328bd6456aa9fad7d9520328db6e5

Given that this involves some changes to dask graph handling, this could make sense.

Also, again, we may not be using dask optimally here (see discussion about the memory inefficiencies in the forum post linked at the top). But ac74939697c328bd6456aa9fad7d9520328db6e5 makes the code above run significantly slower:
- For the `(2, 4, 16000, 16000)` test, about 27s instead of 7s
- For the `(2, 16, 16000, 16000)` test, about 1800s (~30min) instead of ~80s

Not sure though what other workflows would be affected. At least in that case, performance scaled way worse with larger graphs.

Tagging @rjzamora : would you have an idea why ac74939697c328bd6456aa9fad7d9520328db6e5 would lead to such a performance hit?

**Comment by rjzamora** [comment]
>Tagging @rjzamora : would you have an idea why https://github.com/dask/dask/commit/ac74939697c328bd6456aa9fad7d9520328db6e5 would lead to such a performance hit?

Thanks for the ping, and for writing this up!  I will try to figure out if that "fix" caused other graph-related problems.

**Comment by jrbourbeau** [comment]
> Ok, ran git bisect, thanks a lot for pointing me there, that's a really useful tool!

Totally agree : ) 

> I will try to figure out if that "fix" caused other graph-related problems.

Thanks for taking a look @rjzamora!

**Comment by rjzamora** [comment]
Update: I'm expecting https://github.com/dask/dask/pull/9413 to resolve this issue
