### ISSUE TITLE
Suspected memory leakage when using dask and xarray to write a netcdf from a zarr file

### ISSUE THREAD

**Issue by lassiterdc** [dask/dask#9396]
**What happened**:
I have a zarr file that I'd like to convert to a netcdf which is too large to fit in memory. My computer has 32GB of RAM so writing ~5.5GB chunks shouldn't be a problem. However, within seconds of running this script, my memory usage quickly tops out consuming the available ~20GB and the script fails.
![memory_screenshot](https://user-images.githubusercontent.com/64621312/185004542-7c91bcbc-7e7b-4656-a306-732bc1d2e9c3.jpg)

**What you expected to happen**:
I expected memory usage over time to fluctuate by about the chunk size (5.5GB) until the netcdf writing is complete.

**Minimal Complete Verifiable Example**:
Data: [Dropbox link](https://www.dropbox.com/sh/xmcz93p53n1w3ft/AACjI9EskzwKsA8sp-WmM2BFa?dl=0) to zarr file containing radar rainfall data for 6/28/2014 over the United States that is around 1.8GB in total.
```python
import xarray as xr

fpath_zarr = "out_zarr_20140628.zarr"

ds_from_zarr = xr.open_zarr(store=fpath_zarr, chunks={'outlat':3500, 'outlon':7000, 'time':30})

ds_from_zarr.to_netcdf("ds_zarr_to_nc.nc", encoding= {"rainrate":{"zlib":True}})
```

**Environment**:

- Dask version: 2022.8.0
- Python version: 3.8.13
- Operating System: Windows 11
- Install method (conda, pip, source): conda

**Comment by rjzamora** [comment]
Thanks for sharing your experience here @lassiterdc . Have you opened an xarray issue about this? You may get better and faster feedback there, since your reproducer is not using Dask directly.

That said, it does seem within reason for your memory usage to be >2x the chunk size.  Depending on how xarray has implemented zarr reading and writing, there may be a data copy between reading a writing. Also, are you running with the synchronous scheduler, or might you have multiple threads reading/writing in parallel?

**Comment by lassiterdc** [comment]
Yes I did open an xarray issue and cross posted here since I wasn't sure which community would be most insightful. The fact that you aren't surprised by this behavior definitely leads me to believe this is not a bug which is good news. I wasn't sure whether I was running with the synchronous scheduler and whether I had multiple threads reading and writing in parallel. After looking into that, I came across the [Debugging the schedulers section](https://docs.dask.org/en/stable/scheduler-overview.html#debugging-the-schedulers) of the Scheduler Overview page and included `dask.config.set(scheduler='single-threaded')` in my code. Including that actually seems to have resolved the memory allocation issue and resulted in the behavior I expected (memory allocation fluctuating by about the chunk size). I'm pretty sure this is because netcdfs HAVE to be written serially, so attempts at parallel computing would just slow things down and consume more memory than necessary. I think it's fair to say this problem is solved! I'm not sure if I would have thought to do that without your comment, so thank you!

**Comment by rjzamora** [comment]
Glad that helped - and thanks for engaging here @lassiterdc !

**Comment by ian-r-rose** [comment]
@lassiterdc It sounds like using a single-threaded scheduler may have solved your problem, though note that it will also prevent other parts of your data pipeline from running in parallel.

You might be interested in trying a distributed [`Lock`](https://distributed.dask.org/en/stable/api.html?#distributed.Lock) on just the part of your computation that is not parallel-safe.

**Comment by rjzamora** [comment]
>You might be interested in trying a distributed [Lock](https://distributed.dask.org/en/stable/api.html?#distributed.Lock) on just the part of your computation that is not parallel-safe.

Using distributed (e.g. LocalCluster) without a lock should probably do fine as well.  My understanding is that the problem is with memory usage rather than safety, and so I hope that worker pausing/spilling can handle this "embarassingly parallel" case.
