### ISSUE TITLE
Performance regression in Parquet I/O

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask#9397]
In #9175 we added some logic to bump up the default number of retries when writing parquet to remote filesystems. The reasoning was that remote I/O is usually somewhat flakier than local I/O, and we wanted to provide a better default user experience for that case without having to recommend everyone explicitly tune `retries` themselves.

Unfortunately, this attempt to increase reliability seems to have introduced a regression in performance (at least in some cases). The reason is that setting retries on specific operations goes through the dask annotation system, i.e.:
```python
with dask.annotate(retries=5):
   ... # do some stuff
```
Blockwise optimization fuses adjacent blockwise layers so that they can be reliably run as a single task, reducing intermediate results and task overhead. However, the optimization process bails if the annotations of adjacent layers don't match (the idea being: how do we choose to annotate the combined layer?): https://github.com/dask/dask/blob/097decd5f4914d7cd85b3babd6ecdd20a633bf8d/dask/blockwise.py#L1354-L1360

So by annotating-by-default parquet I/O layers, we accidentally prevented them from being fused with adjacent blockwise layers.

To reproduce, the following workflow does a very simple `to_parquet` call and measures the average memory usage of a local cluster:

```python
import time

import dask
import dask.datasets
import distributed
from distributed.diagnostics import MemorySampler

cluster = distributed.LocalCluster()
client = distributed.Client(cluster)

# Fake something that looks like a remote filesystem
# for the purpose of local demonstration. In reality, this would
# be something like s3://bucket/path/to/key
remote_fn = f"simplecache://timeser"
storage_options = {"target_protocol": "file"}

sampler = MemorySampler()
with sampler.sample("pq"):
    ddf = dask.datasets.timeseries(freq="10ms", partition_freq="12H")
    scalar = ddf.to_parquet(remote_fn, storage_options=storage_options, compute=False)
    scalar.compute()

df = sampler.to_pandas()
print(df.pq.mean() / 1024**3)
```

On `main`, this uses ~4.5 GiB average memory. But if I revert #9175 it uses an average of ~3.5 GiB. See also [here](https://github.com/coiled/coiled-runtime/pull/247#issuecomment-1218511200) for some evidence using larger, cloud-based cluster. We can inspect the high level graph post-optimization to confirm the failure to fuse blockwise layers. On `main`:

![image](https://user-images.githubusercontent.com/5728311/185263627-22d949f0-3900-4179-9b91-96dd67903e6b.png)

And with #9175 reverted:

![image](https://user-images.githubusercontent.com/5728311/185263663-210df8e8-069e-41cd-9a41-485f4ba0f79c.png)

This regression should only be an issue when there are adjacent blockwise layers to our parquet I/O. But I expect that to be quite common in practice. To me, this is a big enough deal that we should consider reverting #9175 and considering whether there is a better way to mark some set of tasks as possibly flakier than others.

Finally, I'll note that the interaction between annotations and graph optimization has been a persistent problem, and has led to a number of surprising behaviors (see at least #7036 and it's linked issues). That interaction may be due for some serious reconsideration.

**Comment by ian-r-rose** [comment]
An alternative to just reverting #9175 could be to actually do the work of merging annotations of adjacent layers based on some simple rules. They could be something like
* **priority**: max of layer priorities
* **workers**: intersection of layer workers
* **resources**: max of layer resources
* **retries**: max of layer retries
* Any custom annotations: bail on fusing layers

The above *could* work, but (a) I'm not sure if it's a great idea to put more resources towards the layer+annotation interactions which have proven so difficult, and (b) it may be worth doing more carefully after reverting #9175

**Comment by fjetter** [comment]
Have we tried using retries on IO level? Naively, I would expect boto/fsspec/whatever to do this for us instead.

**Comment by rjzamora** [comment]
>Have we tried using retries on IO level? Naively, I would expect boto/fsspec/whatever to do this for us instead.

Without understanding the problem fully, I am also hoping this is a possibility :)

>The above could work, but (a) I'm not sure if it's a great idea to put more resources towards the layer+annotation interactions which have proven so difficult, and (b) it may be worth doing more carefully after reverting https://github.com/dask/dask/pull/9175

I seems like it could be possible to implement the rules you described above in a relatively clear and simple way. If so, I'd personally be supportive of that solution (even if the initial PR only addresses the `retries` case for now).

**Comment by ian-r-rose** [comment]
> Have we tried using retries on IO level? Naively, I would expect boto/fsspec/whatever to do this for us instead.

Both boto and s3fs/gcsfs/fsspec have some functionality around retries (this is discussed in the original issue), but even then odd behavior can bubble up to the dask level The work here was basically a belt-and-suspenders approach.

I'm sure there is also work that could be done in s3fs et al (perhaps @martindurant has some insight). The retry logic there currently retries for some error codes, but not for the whole universe of things that might go wrong.

**Comment by ian-r-rose** [comment]
> I seems like it could be possible to implement the rules you described above in a relatively clear and simple way. If so, I'd personally be supportive of that solution (even if the initial PR only addresses the retries case for now).

I also think this could be fairly doable (regardless of whether this particular approach to retries is a good idea). I'm just not sure what our stance towards feature development on HLG/layers is right now...

**Comment by martindurant** [comment]
> I'm sure there is also work that could be done in s3fs et al 

To be sure, there are some things that should *not* be retried, such as not-found and permission violations.

**Comment by rjzamora** [comment]
>I'm just not sure what our stance towards feature development on HLG/layers is right now...

Your hesitation is warranted.  We know we want to change many things in HLG, and we want to avoid further-complicating the current state. However, my understanding is that this only applies to `Blockwise` fusion (there is no other way to fuse HLG Layers), and so the "fix" could be somewhat distinct from the larger HLG design. I'm imagining a simple/moduler `check_fusable_annotations` check in the blockwise-fusion logic that we may or may not throw away in the future.
