### ISSUE TITLE
depth-first order destroyed when disconnect paths of dependency graph

### ISSUE THREAD

**Issue by Joshuaalbert** [dask/dask#9399]
**What happened**:
When you have a dependency with separate paths that do _not_ merge into one node and all keys are traversed, then `toposort` loses depth-first ordering. In fact, the output depends on the ordering in the `dependencies` dict.

**What you expected to happen**:
You would like to maintain depth-first ordering in all cases, as according to the dask scheduling memorandum, doing longest chains first is the smartest way to manage memory.

**Minimal Complete Verifiable Example**:

```python
from dask.core import toposort
print('passes')
dsk = {'a': 1, 'b': (bool, 'a'), 'c': 1, 'd': (bool, 'c')}
deps = {'a': {}, 'b': {'a'}, 'c': {}, 'd': {'c'}}
order = toposort(dsk, deps)
assert order.index('b') == order.index('a') + 1
assert order.index('d') == order.index('c') + 1

print('fails')
dsk = {'a': 1, 'c': 1, 'd': (bool, 'c'), 'b': (bool, 'a')}
deps = {'a': {}, 'c': {}, 'd': {'c'}, 'b': {'a'}}
order = toposort(dsk, deps)
assert order.index('b') == order.index('a') + 1
assert order.index('d') == order.index('c') + 1
```

**Environment**:
 Part of dask core since forever.

EDIT: to clarify the requirements of the dask scheduler are not always satisfied for dependency structures of the sort:
```
a->b
c->d
```
and the resulting topological ordering will depend upon the ordering of the provided `dsk`.

**Comment by Joshuaalbert** [comment]
For a quick fix you can run `toposort` twice where in between you use the first toposort to order the nodes in the dependencies such that depth-first sort is trivially satisfied (case 1 in MVCE).

```python
ordering = _toposort(graph) # get topo order
# reorganise the graph
ordered = set()
new_graph = dict()
def _order(node):
    if node in ordered:
        return
    new_graph[node] = graph[node]
    ordered.add(node)
    for dep in graph[node]:
        _order(dep)

for node in ordering[::-1]: #start at end and work back
    _order(node)

# run again
return _toposort(new_graph)
```

**Comment by fjetter** [comment]
cc @eriknw

**Comment by JSKenyon** [comment]
I am not sure I follow. I have modified the MVCE to the following:

```python
from dask.core import toposort

dsk = {'a': 1, 'b': (bool, 'a'), 'c': 1, 'd': (bool, 'c')}
deps = {'a': {}, 'b': {'a'}, 'c': {}, 'd': {'c'}}
order = toposort(dsk, deps)
assert order.index('b') == order.index('a') + 1
assert order.index('d') == order.index('c') + 1

deps = {'a': {}, 'c': {}, 'd': {'c'}, 'b': {'a'}}
order = toposort(dsk, deps)
assert order.index('b') == order.index('a') + 1
assert order.index('d') == order.index('c') + 1
```

which runs just fine. Would you mind elaborating @Joshuaalbert?

**Comment by eriknw** [comment]
Are the results of `toposort` not topologically sorted?  If not, then I don't think this is an issue.  Other than being topologically sorted, `toposort` makes no other claims about the order.  That said, I expect depth-first search ordering--do you require this?

A reproducible example would be nice to have, because it would be worrying for the current implementation to not have DFS ordering.

**Comment by Joshuaalbert** [comment]
@JSKenyon Yes, I extracted `toposort` to investigate and since `toposort` doesn't depend on on `dsk` actually, only the depdencies, I threw that arg away during debyg. However, your example does fail if you change the order of the `dsk` to match `deps`. In the code `dependencies are just extracted from `dsk` in the order provided by the `dsk` keys, so you need to change the order of `dsk` to see the effect.

```python
from dask.core import toposort
    print('passes')
    dsk = {'a': 1, 'b': (bool, 'a'), 'c': 1, 'd': (bool, 'c')}
    deps = {'a': {}, 'b': {'a'}, 'c': {}, 'd': {'c'}}
    order = toposort(dsk, deps)
    assert order.index('b') == order.index('a') + 1
    assert order.index('d') == order.index('c') + 1

    print('fails')
    dsk = {'a': 1, 'c': 1, 'd': (bool, 'c'), 'b': (bool, 'a')}
    deps = {'a': {}, 'c': {}, 'd': {'c'}, 'b': {'a'}}
    order = toposort(dsk, deps)
    assert order.index('b') == order.index('a') + 1
    assert order.index('d') == order.index('c') + 1
```

@eriknw yes you get topographicaly sorted, but that is not a unique operation. The problem here is that we're not getting depth-first traversal here. 

The dask architecture is based on designs (and research) into how to reduce memory footprints in big computation DAGs. 
This [memo](https://docs.dask.org/en/stable/scheduling-policy.html) lightly explains the key requirements. The notable big requirement is that dask should always prefer to calculate the longest path first. There are a number of other good rules stated in the memo which are worth knowing.

> We want to encourage depth first behavior where, if our computation is composed of something like many trees we want to fully explore one subtree before moving on to the next. This encourages our workers to complete blocks/subtrees of our graph before moving on to new blocks/subtrees.
> 
> And so to encourage this “depth first behavior” we do a depth first search and number all nodes according to their number in the depth first search (DFS) traversal. We use this number to break ties when adding tasks on to the stack. Please note that while we spoke of optimizing the many-distinct-subtree case above this choice is entirely local and applies quite generally beyond this case. Anything that behaves even remotely like the many-distinct-subtree case will benefit accordingly, and this case is quite common in normal workloads.

@mrocklin ^^

**Comment by Joshuaalbert** [comment]
@JSKenyon I updated my MVCE to reflect the `dask.core` version

**Comment by eriknw** [comment]
Thanks for the example.

`dask.order.order` should be used to determine the order that the scheduler runs tasks, not `toposort`.

`toposort` performs a DFS along _dependencies_, not _dependents_.  This means that after visiting `"a"`, it doesn't traverse the dependents of `"a"`, which would be `"b"`.  `"a"` has no dependencies, so the algorithm moves on to the next key, which could be any of them.

Is this behavior causing an issue for you in a wider workflow?

**Comment by eriknw** [comment]
I think we can simplify your workaround thusly:
```python
>>> order = dask.core.toposort(dsk, dependencies=deps)
>>> order
['a', 'c', 'd', 'b']

>>> order = dask.core._toposort(dsk, order[::-1], dependencies=deps)
>>> order
['a', 'b', 'c', 'd']
```
but I don't think it's necessary to always do this.  For example, `toposort` is used in `inline`, which works with _any_ topological sort.  Is there a use case that needs DFS along dependents?

**Comment by Joshuaalbert** [comment]
@eriknw thanks for the replies. Ah, okay. So toposort isn't used for ordering, so this issue is irrelevant w.r.t. maintaining the scheduler principles. I came across this with a valid use case in a project I'm writing that is not based on dask, but also had the same problem in its toposort. In that case, I was desiring the behaviour of `dask.order.order` and had assumed it was a `toposort` with extra constraints. In that use case, there is guarded logic happening where subtrees are not traversed if dependencies are not evaluated and also if a node-specific condition is not met. Furthermore, the traversal actually corresponds to user interaction at each node. If the guard condition is met then we desire the user to go down that branch immediately. However, if there are many distinct trees then we found the user flipping between branches. It was something that made me think "maybe dask team would like to know".

**Comment by eriknw** [comment]
Cool.  From a usability perspective, I think adding an optional argument to `dask.core.toposort` to ensure DFS along _dependents_ is perfectly reasonable.  I've wanted this behavior before when toying around with my own graphs, and I'm pretty sure I used the trick I shared above.

`dask.order.order` _usually_ does DFS, but not always.  `order` is actually [a little complicated](https://github.com/dask/dask/blob/main/dask/order.py).  There are some workloads that would perform terribly if DFS were strictly followed.  Have you tried using `order` for your use case?

**Comment by JSKenyon** [comment]
> @JSKenyon Yes, I extracted `toposort` to investigate and since `toposort` doesn't depend on on `dsk` actually, only the depdencies, I threw that arg away during debug. However, your example does fail if you change the order of the `dsk` to match `deps`. In the code, dependencies are just extracted from `dsk` in the order provided by the `dsk` keys, so you need to change the order of `dsk` to see the effect.

I understand now. Thanks for clarifying!

**Comment by Joshuaalbert** [comment]
Hi @eriknw I ran `dask.order.order` of the above test cases and rearranged the keys by the resulting sort indicies and it meets the dask principles (as expected) and also meets my project needs. I appreciate both your attention on this, despite it being a false alarm.
