### ISSUE TITLE
Filtering on a Python list is 2 orders of magnitude slower than filtering on a numpy array

### ISSUE THREAD

**Issue by RogerThomas** [dask/dask#9411]
**What happened**:
Filtering on a list of integers vs a numpy array on the example below is nearly 200 times slower 
From the example below I get

```
Pandas with list took: 0.573s, len: 3,934,884
Pandas with array took: 0.366s, len: 3,934,884
Dask with list took: 41.739s, len: 3,934,884
Dask with array took: 0.240s, len: 3,934,884
```

**What you expected to happen**:

Filtering on a list vs an array shouldn't be that different in Dask, I would expect it to be a bit slower, but not nearly 200 times slower.

**Minimal Complete Verifiable Example**:

```python
import time
import numpy as np
import pandas as pd
from dask.dataframe import from_pandas
from distributed import LocalCluster, Client


def main():
    n = 10_000_000
    rs = np.random.RandomState(42)
    a_column_unique_values = np.arange(1, n // 10)
    df = pd.DataFrame({"A": rs.choice(a_column_unique_values, n), "B": rs.random(n)})

    filter_values_list = sorted(
        rs.choice(a_column_unique_values, len(a_column_unique_values) // 2).tolist()
    )
    filter_values_array = np.array(filter_values_list, dtype="i8")
    print(f"Len filter: {len(filter_values_list):,}")

    t1 = time.time()
    tmp_df = df[df["A"].isin(filter_values_list)].copy()
    len_after_filter = len(tmp_df)
    print(f"Pandas with list took: {time.time() - t1:,.3f}s, len: {len_after_filter:,}")

    t1 = time.time()
    tmp_df = df[df["A"].isin(filter_values_array)].copy()
    len_after_filter = len(tmp_df)
    print(f"Pandas with array took: {time.time() - t1:,.3f}s, len: {len_after_filter:,}")

    with LocalCluster(n_workers=4, processes=True, threads_per_worker=1) as local_cluster:
        with Client(local_cluster):
            ddf = from_pandas(df, npartitions=8).persist()

            t1 = time.time()
            tmp_ddf = ddf[ddf["A"].isin(filter_values_list)].copy()
            len_after_filter = len(tmp_ddf)
            t2 = time.time()
            print(f"Dask with list took: {t2-t1:,.3f}s, len: {len_after_filter:,}")

            t1 = time.time()
            tmp_ddf = ddf[ddf["A"].isin(filter_values_array)].copy()
            len_after_filter = len(tmp_ddf)
            t2 = time.time()
            print(f"Dask with array took: {t2-t1:,.3f}s, len: {len_after_filter:,}")


if __name__ == "__main__":
    main()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.8.1
- Python version:  3.9.13
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by pavithraes** [comment]
@RogerThomas Thanks for reporting, this is surprising and seems like a bug.

I looked at this with @ian-r-rose, and we think this might be related to how the list is being serialized, specifically by the distributed scheduler.

A few notes:
* we see short overall times and short time _differences_ while using single machine schedulers
* for the list case, the task stream shows some long red bars called "transfer-len-chunks" -- seem to be taking a lot of time
* again or the list case, the profile plot shows many large "serialize" steps, which aren't present in the np.array case

**Comment by RogerThomas** [comment]
thanks for looking into it @pavithraes, is there anything I can help with?

**Comment by hayesgb** [comment]
Hi @RogerThomas .  I've just added a PR that should improve this.  With your reproducer, on my machine, this PR reduces execution time for the list from 2 orders of magnitude greater than Pandas to 1.6x longer than in Pandas.  Most of this time is spent confirming that all of the elements in the list are of same datatype.

Would appreciate any feedback.
