### ISSUE TITLE
Possible regression introduced by PR 9302

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#9428]
Over in https://github.com/coiled/coiled-runtime/issues/272  and https://github.com/coiled/coiled-runtime/issues/271 we reported a potential regression, that after running a git-bisect we were able to identify it was caused by PR https://github.com/dask/dask/pull/9302 even though it's not supposed to affect this workflow, as the option is off by default. 

The test we run consists of this query https://github.com/coiled/coiled-runtime/blob/f858057b8810bce1a397aa391a1f188c83d47cf7/tests/benchmarks/h2o/test_h2o_benchmarks.py#L67-L73

```
dask-version               |     duration [s]
------------------------------------------------------

2022.8.0+18.gc1bc90aa5     |     70.4672958850861  
2022.8.0+19.g097decd5f     |     87.210559129715       (PR https://github.com/dask/dask/pull/9302)
```
This PR shouldn't have affected the behavior as the flag was not turned on. Not quite sure what could be happening here, but this seems like a legitimate regression. A couple of things to know is that `id3` has high cardinality but the total amount of data, in this case, is not that big.

cc: @ian-r-rose @rjzamora Thoughts?

**Comment by ian-r-rose** [comment]
Thanks for the report @ncclementi! This is probably due to the change to the `sort` arg in #9428 . It is now overriding the defaults for some of the aca functions (which previously had `False`, and now have `None`).

**Comment by rjzamora** [comment]
>Thanks for the report @ncclementi! This is probably due to the change to the sort arg in https://github.com/dask/dask/issues/9428 . It is now overriding the defaults for some of the aca functions (which previously had False, and now have None).

I was just about to say the same thing (sort of). The PR now passes the sort argument to `chunk` and `combine` (while it didn't pass anything at all before).  I was undert the impression that passing `None` would be the same as passing nothing in this case, but I'm probably missing something.

**Comment by rjzamora** [comment]
**Side Note**: There is no requirement for the output groups to be sorted in query-3.  The pandas code even uses an explicit `sort=False` for the [published results](https://h2oai.github.io/db-benchmark/).  Therefore, I'd suggest that the benchmark you linked also be changed to `sort=False`.

**Comment by ian-r-rose** [comment]
> I was under the impression that passing None would be the same as passing nothing in this case

I was also under that impression -- but the `None` overrides the default of `False` in some of the chunk/agg functions, which then probably gets defaulted to `True` in [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas-dataframe-groupby).



> **Side Note**: There is no requirement for the output groups to be sorted in query-3. The pandas code even uses an explicit `sort=False` for the [published results](https://h2oai.github.io/db-benchmark/). Therefore, I'd suggest that the benchmark you linked also be changed to `sort=False`.

Good point! Though I'm glad it was unset so as to catch this!

**Comment by ian-r-rose** [comment]
A bit of supporting information: shown are boxplots for duration and average memory. The first is the commit before #9302, the second is #9302, and the third is the same, but with the `sort=self.sort` args removed
![visualization(28)](https://user-images.githubusercontent.com/5728311/186559066-b4f68b56-64bd-4e7b-be73-e65d236b8cfb.png)
:

**Comment by rjzamora** [comment]
Thanks for running those experiments @ian-r-rose - Do you think the best path is to keep defaults, or is this more motivation for something like #9386 (assuming that would help this case)?

**Comment by ian-r-rose** [comment]
From my perspective, going forward with #9386 seems like it would be a fine choice.

Over there you said:

> [it] does not improve performance when the aggregation fits comfortably in memory (and may even introduce a slight regression)

I don't quite understand how it could introduce a regression, seems like it should be doing less work overall. Unless you mean that it performs something like a merge sort on the tree reduction?

**Comment by rjzamora** [comment]
>I don't quite understand how it could introduce a regression

I was confused by my observations, and decided not to devote time to the issue in the short term. My assumption was that the final aggregation node(s) (where `sort=True` is the default) were benefiting from the input aggregations having "pre-sorted" groups. However, I'm far from sure about this, and I don't think the regressions were significant.

**Comment by ian-r-rose** [comment]
Hmm, I'm still seeing `sort=False` have some worse behavior than just not passing it in -- I guess I'll need to dig a bit deeper.
