### ISSUE TITLE
Update dashboard documentation for memory plot 

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#9433]
Once this PR on distributed gets merged https://github.com/dask/distributed/pull/6959 we will have a new color on the worker memory plot. This change should be added to the docs, more specifically here https://github.com/dask/dask/blob/main/docs/source/dashboard.rst

Item actions:
- [ ] Include an image that shows red 
- [ ] Document what red means. (see PR description)

**Comment by crusaderky** [comment]
PR merged

**Comment by yashdev9274** [comment]
is it still open

**Comment by pavithraes** [comment]
@yashdev9274 Yes, this issue is still open. :) Would you be interested in submitting a PR?

**Comment by yashdev9274** [comment]
yeah sure, I'm looking forward to contribute.

**Comment by yashdev9274** [comment]
But cay you tell me  in brief, exactly at what issue I have to look over.

**Comment by ncclementi** [comment]
@yashdev9274 there is an explanation on the initial comment of the issue on what needs to happen. Is there anything, in particular, that is not clear on how to approach?

**Comment by jayeshmanani** [comment]
Is it still open, I would like to contribute to the documentation, and update the documentation @ncclementi

**Comment by jayeshmanani** [comment]
I have updated the documentation, Please have a look at it, and suggest if more improvement needed.
