### ISSUE TITLE
How's the overhead compare with ray?

### ISSUE THREAD

**Issue by jinfagang** [dask/dask#9437]
Ray's overhead can be 400ms even on a very simple program, How does Dask performance? Does it's own overhead too much?

**Comment by pavithraes** [comment]
@jinfagang Based on the docs -- for [single-machine schedulers](https://docs.dask.org/en/latest/shared.html#performance), it's around 200-300us of overhead per task; and for the [distributed scheduler](https://distributed.dask.org/en/stable/index.html#motivation) it can be up to ~1ms of overhead per task. By "per task" we mean the number of tasks we submit to the scheduler. Does this help?

Also, note that we use Discourse for [usage questions](https://dask.discourse.group/). If you have follow-up questions, maybe we can continue the discussion there. :)

**Comment by jinfagang** [comment]
@pavithraes thanks, so that dask is actually faster than ray? I tried using ray running simuteneously tasks, the overhead is 400ms.

For example, I have TaskA and TaskB, one is 6s other is 4s, if they co-runing, overall time should be 6s, but ray got 6.48s. Does Dask able to reducing the overhead to more minimal? If so, by how

**Comment by pavithraes** [comment]
@jinfagang I've not used Ray, so I can't really speak about the speedups. You can consider asking the Ray community: https://discuss.ray.io/.

To address your example, here's the Dask code simulating that:

```python
from time import sleep

import dask
from dask.distributed import Client

client = Client()


def taskA():
    sleep(6)
    return 1


def taskB():
    sleep(4)
    return 2


%%time
a = client.submit(taskA)
b = client.submit(taskB)
result = client.gather(a, b)
```

On my machine (6-core CPU), this took 6.16s to complete.

**Comment by pavithraes** [comment]
Since we have answered your original question, I'll go ahead and close this as resolved.

If you'd like to continue discussing the performance, [Dask's discourse forum](https://dask.discourse.group/) is the best place to do that. :) Please also feel free to re-open this issue if needed!

**Comment by jinfagang** [comment]
@pavithraes thanks, where does the 160ms comes from?

**Comment by pavithraes** [comment]
@jinfagang That would be scheduler overhead + network latency. You might find https://distributed.dask.org/en/stable/journey.html interesting :)
