### ISSUE TITLE
Clarify custom-graph multiprocessing example 

### ISSUE THREAD

**Issue by jinfagang** [dask/dask#9438]
```
import dask
from dask.multiprocessing import get
import numpy as np


def load(filename):
    return np.random.random(32, 4)


def clean(data):
    data[:, 0] = 0.1
    return data


def analyze(sequence_of_data):
    out = sequence_of_data[0]
    for a in sequence_of_data[1:]:
        out += a
    return out


def store(result):
    with open(..., "w") as f:
        f.write(result)


dsk = {
    "load-1": (load, "myfile.a.data"),
    "load-2": (load, "myfile.b.data"),
    "load-3": (load, "myfile.c.data"),
    "clean-1": (clean, "load-1"),
    "clean-2": (clean, "load-2"),
    "clean-3": (clean, "load-3"),
    "analyze": (analyze, ["clean-%d" % i for i in [1, 2, 3]]),
    "store": (store, "analyze"),
}

get(dsk, "store")  # executes in parallel

```

error:

```
lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
```

**Comment by rjzamora** [comment]
Can you try running with your `get` command in a `if __name__ == '__main__':` block? This is usually required for multiprocessing (when you are not executing in a notebook). For example:

```python
if __name__ == '__main__':
    get(dsk, "store")
```

**Comment by jinfagang** [comment]
@rjzamora Hi, it so, it would be better indicates in documentation, otherwise people get confused.

**Comment by rjzamora** [comment]
>it would be better indicates in documentation, otherwise people get confused.

Agree that this should be clarified in the documentation, thanks for raising this. Can you confirm that the `__main__` change fixes your problem locally? If so, we only need a documentation fix here.

**Comment by jinfagang** [comment]
yes

**Comment by ncclementi** [comment]
@jinfagang thank you for reporting this. 

Was this example in the dask documentation? Can you point us to where so we can open a ticket to add to the documentation the suggestion that Rick mentioned? 

Also would you be interested in opening a PR to fix such documentation?

**Comment by rjzamora** [comment]
It looks like this may be the example in question: https://docs.dask.org/en/stable/custom-graphs.html#example

**Comment by ncclementi** [comment]
TODO:
- [ ] Make clear that if not running from a notebook, you need to run the last line as

``` python
if __name__ == '__main__':
    get(dsk, "store") 
```    
in the example in this https://github.com/dask/dask/blob/main/docs/source/custom-graphs.rst

**Comment by noumxn** [comment]
Hi @ncclementi. I opened a PR that fixes this issue. I have a failing import test. I had a looked at the workflow in additional.yml but still haven't been able to figure out why it failed. Could you please check this out for me?

**Comment by noumxn** [comment]
Okay, it just passed all the checks. Could you please review the PR?
