### ISSUE TITLE
Redesigning the array HTML repr for clarity 

### ISSUE THREAD

**Issue by andersy005** [dask/dask#9447]
While the current HTML repr provides very useful information, it can also be _confusing_ for new users. This is due to the fact we currently use a table to represent information (`Type`, `Count`) that is not directly comparable for `Array` and `Chunk` columns

![Screen Shot 2022-08-31 at 11 04 07 AM](https://user-images.githubusercontent.com/13301940/187737746-078a0473-01e8-4724-afd6-cbab038622fd.png)

To improve clarity, it might be useful to get the stuff that’s not directly comparable out of the table. The new HTML repr would 

- keep `Bytes` and `Shape` in a table:

   ![Screen Shot 2022-08-31 at 11 23 21 AM](https://user-images.githubusercontent.com/13301940/187740918-c28ef070-1de7-4cba-9a3f-527349d754a2.png)

   
    This describes the same thing (bytes and shape) across both arrays and chunks.

- and then, outside of the table we could have something along these lines 

  ```
  Dask graph: X chunks in Y tasks
  Data type: float32 numpy.ndarray
  ```

@dask/array, how do folks feel about this?

_The suggestion above came from an offline conversation with @freeman-lab._

**Comment by ncclementi** [comment]
🤔, In that case, we would lose the information about the number of Tasks and Chunks which are very useful when analyzing performance. 

I agree that having count and type in the table can be confusing. I wonder if having a straight line that separates Count and Type if the table would achieve the same, and we  wouldn't loose the information.

**Comment by jacobtomlinson** [comment]
This sounds good to me. As long as all the info stays in the repr I think moving things out of the table makes sense.

**Comment by GenevieveBuckley** [comment]
Sounds good to me too

**Comment by ognis1205** [comment]
Hi, guys.
Could you please assign this issue to me?
I would like to participate in the dask development.

**Comment by phobson** [comment]
@ognis1205 feel free to draft a PR and tag me in it. I'll be happy to review. 

Are you comfortable with the basic workflow of working in Git and Github?

**Comment by ognis1205** [comment]
@phobson Thanks for the reply!
I think I'm comfortable with the workflow but I will review the contribution guideline of the dask project before proceeding.
I found the document online.

**Comment by ognis1205** [comment]
take

**Comment by ognis1205** [comment]
@phobson 
I created the pull request. Could you please review it?
Thanks.
