### ISSUE TITLE
Chunks with size literals (`"20 MiB"`) can result in significantly different chunk sizes than requested

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#9488]
When using chunksizes defined in numbers of bytes, the chunksize chosen is extremely sensitive to minor perturbations in the shape of the overall array. In this example, increasing the array shape by 1 switches the chunk sizes from being the requested size, to being far smaller than the requested size and having 4x more chunks:

```python
>>> import dask.array as da
>>> from dask.utils import format_bytes

>>> a1 = da.random.random((97936, 97936), chunks=("20 MiB", "20 MiB"))
>>> a1.npartitions
3721
>>> format_bytes(a1.blocks[0, 0].nbytes)
'20.00 MiB'

>>> # increase shape by 1 along both dimensions (97936 -> 97937)
>>> a1 = da.random.random((97937, 97937), chunks=("20 MiB", "20 MiB"))
>>> a1.npartitions  # 4x more chunks than previous
14161
>>> format_bytes(a1.blocks[0, 0].nbytes)  # 4x smaller chunks than previous, and nowhere near requested 20MiB size
'5.17 MiB'
```

This was discovered in https://github.com/coiled/coiled-runtime/issues/316#issuecomment-1245623435, where the size of the array is set relative to the total cluster memory. Tiny, natural perturbations in total cluster memory (on the order of 1 MB) were causing the graph to have wildly different numbers of tasks, and runtimes.

For a more minimal reproducer, consider:

```python
>>> from dask.array.core import normalize_chunks

>>> normalize_chunks("10 B", (101,), dtype=bool)
((10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1),)

>>> normalize_chunks("10 B", (102,), dtype=bool)
((6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6),)

>>> normalize_chunks("10 B", (103,), dtype=bool)
((10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3),)
```

In most cases, we get 11 chunks: 10 of exactly the requested size, and the last one holding whatever remainder was needed.

But in the case of a 102-length array, dask tries to get very clever: it recognizes that by picking a different chunksize, all the chunks could be the same size (instead of having one differently-sized chunk for the remainder at the end). So we get 17 chunks instead of 11, and each chunk is 40% smaller than we asked for.

cc @ian-r-rose @jsignell @jrbourbeau

**Comment by ian-r-rose** [comment]
What is the threshold at which it currently makes this choice? Is it relative or absolute?

From my perspective this cleverness is absolutely not worth it, and I'd much rather `normalize_chunks` just give me closer to what I asked for, at the cost of having a few slivers at the end.

**Comment by gjoseph92** [comment]
The problem comes from the fact that using `"20 MiB"` goes down the code-path of `"auto"` chunking. And auto chunking uses this `round_to` function, which:
* tries to pick a factorization of the array size that's within 50% of the set chunk size
* if no such factor exists, just uses the set chunks size

https://github.com/dask/dask/blob/b817dfb62bf3b53dcf0ee58cb94915333a6731f9/dask/array/core.py#L3271-L3274

This means that, depending on what your array length happens to be divisible by (aka the least-significant digits of the array size), you'll go down to very different code paths for picking the chunk size.

* One tries to ensure every single chunk is the same size, even if that size ends up being smaller than necessary.
* The other ensures that as many chunks as possible are as close as possible to the requested size.

If this factorization worked in all cases, I can see why it might be desirable, but since it doesn't, I feel like it might be trying to be too clever. It makes a little more sense in the case of `"auto"` chunksizes, but even I'm not sure what real-world case it solves.

To me, having a single small remainder chunk along each dimension doesn't seem bad enough to be worth making _every_ chunk smaller, and increasing the graph size.

**Comment by gjoseph92** [comment]
Requesting a fixed chunk size, here's a plot of the chunksize, and number of chunks, that dask actually picks for linearly increasing array lengths:

![10MiB](https://user-images.githubusercontent.com/3309802/190027928-932f3932-4302-4f59-9a14-4ab7328cda90.png)

<details><summary>Code to generate</summary>

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

from dask.utils import parse_bytes
from dask.array.core import normalize_chunks

target_chunksize = "10 MiB"

results = np.array(
    [
        (
            size,
            (chunks := normalize_chunks(target_chunksize, (size,), dtype=bool))[0][0],
            len(chunks[0]),
        )
        for size in tqdm(
            np.linspace(
                parse_bytes(target_chunksize),
                parse_bytes(target_chunksize) * 1_000,
                700,  # interval not divisible by chunksize
                dtype=int,
            )
        )
    ]
)

df = pd.DataFrame(results, columns=["Size", "Chunksize", "Numblocks"]).set_index("Size")

df.plot(
    xlabel="Array size",
    title=f"Chunking selected when specifying {target_chunksize} chunks",
    subplots=True,
)
plt.savefig(f"{target_chunksize.replace(' ', '')}.png")
```

</details>

Ideally, the top plot should be a flat line—always 10 MiB—and the bottom should be a straight, linearly-increasing number of chunks, without all the noise.

Indeed, that's what you get if you simply remove the factorization logic:

```diff
diff --git a/dask/array/core.py b/dask/array/core.py
index bbc53f0a8..6c136ca96 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -3268,10 +3268,7 @@ def round_to(c, s):
     smaller than c.
     """
     if c <= s:
-        try:
-            return max(f for f in factors(s) if c / 2 <= f <= c)
-        except ValueError:  # no matching factors within factor of two
-            return max(1, int(c))
+        return max(1, int(c))
     else:
         return c // s * s
```

![10MiB](https://user-images.githubusercontent.com/3309802/190028378-5b0c5281-8aa4-45d4-99e4-1ed5a0abc93f.png)

(Additionally, my visualization script runs in milliseconds in the second case, compared to 11 seconds in the first case. @martindurant's concern in https://github.com/dask/dask/pull/3507#discussion_r189293085 seems valid :)

**Comment by ian-r-rose** [comment]
(I also have my knives out for `normalize_chunks` so this fits in nicely)

**Comment by phobson** [comment]
Wow. Great sleuthing on this one!

**Comment by gjoseph92** [comment]
🔪 for me as well.

I just want to be careful because:
1. I don't understand why this logic is here in the first place from #3507. Was there an actual problem it was trying to solve? Or did it just seem cool at the time?
2. `round_to` is also [used](https://github.com/dask/dask/blob/b817dfb62bf3b53dcf0ee58cb94915333a6731f9/dask/array/core.py#L3229) in the case where `previous_chunks` are known, and we try to preserve their aspect ratio. I haven't thought about whether factorization matters there; my guess is that it doesn't.
3. You could _maybe_ argue that factorization is kind of desirable for some cases of `"auto"` chunks. Or in general, should `"auto"` mean more than a synonym for `config.get("array.chunk-size")`? `"auto"` implies a lot more liberty to pick the chunk size than `"20 MiB"` does—is there a reason we'd want to preserve this behavior for the `"auto"` case only? Again, I think not, because I can't see why it would ever improve performance over using the largest allowable chunks, but I want to ask.

**Comment by ncclementi** [comment]
If we go for the 🔪 option, we might want to ping some Xarray folks, there is a chance that this affects them. 
@TomNicholas, @dcherian Thoughts?

**Comment by TomNicholas** [comment]
Is it going to affect us in a way that is different to how it would affect a naked `dask.array` user?

We don't have many many custom HLGs in xarray, so from a performance perspective I think you will see all the problems that we would see before us (in `apply_gufunc` etc.) Maybe @dcherian can think of other considerations though.

**Comment by dcherian** [comment]
> Is it going to affect us in a way that is different to how it would affect a naked dask.array user?

I don't think so. In addition it's quite common to explicitly set chunk sizes for most array workloads I've seen

**Comment by gjoseph92** [comment]
> Is it going to affect us in a way that is different to how it would affect a naked `dask.array` user?

No.

> We don't have many custom HLGs in xarray

This isn't about HLGs. It's about having arguments like `chunks="200 MiB"`, or `chunks="auto"` (or of course `chunks=(512, 512, "auto", 30, "20MB")` and such).

My guess is it probably won't affect xarray folks as much; as @dcherian says I imagine auto chunking isn't used much in datasets like zarr, which already have explicit chunking.

Maybe occasionally in rechunking though? (I think this change would, overall, be vastly preferable in the case of rechunking—if you ask for `"200 MiB"` chunks, you want to get them!)

**Comment by TomNicholas** [comment]
> This isn't about HLGs. 

My thought was that a user might have a custom HLG whose performance could be affected by suddenly having different chunking structures than the previous default. But that's not us as we don't have many custom algorithms like that.

**Comment by gjoseph92** [comment]
Ahh I see, thanks for the clarification. Yes, I don't think that would be much of a concern.

**Comment by jsignell** [comment]
Just chiming in to say that I totally agree with the assessment of the current state of this code and I have a strong suspicion that even chunking just seemed cool. If we could always get even chunks then that would probably be easier to handle and desirable, but since we can't promise that, all code needs to be able to handle different size chunks (and often empty chunks) anyways. So I don't see this factorization being useful in practice.

**Comment by dcherian** [comment]
OK I now remember where this might make a difference. 

There are places where dask automagically sets chunk size (indexing #6514, reshape #8124). These PRs have really large impact on Xarray users. We index with list-of-ints for "alignment" all the time.

@gjoseph92 Does your change impact these code paths? 

There is certainly an issue with #6514, where it constructs chunks that are a lot smaller than `"chunk-size"`. I am 95% sure there's an issue about it, but can't find that now.

PS Also see #5439 which seems related.

**Comment by gjoseph92** [comment]
Good find on https://github.com/dask/dask/issues/5439, that seems like the same issue. We'll be able to close that one too.

At a brief glance, I don't see https://github.com/dask/dask/pull/6514 being affected. https://github.com/dask/dask/pull/8124 might be slightly, since in that code path [it can use `"atuo"` chunks](https://github.com/dask/dask/blob/ee87819ba0ee6013da212c562aab847ab7471bd3/dask/array/reshape.py#L282). But I think we're in agreement that auto chunking should be better with this change—it will prevent chunks from being too small.
