### ISSUE TITLE
Change organization to dask/dask

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#949]
We're considering moving some dask related projects, like `dask`, `distributed`, `hdfs3`, and `knit` from the blaze org to a new dask org.  

Are there any questions or objections to this move?

Also, pinging @Dask, a current user.  If you are still active on github then how do you feel about this?

**Comment by shoyer** [comment]
If the user "dask" is not active, github will reclaim the username for you. There's a support page that makes it pretty easy to request.

My only concern is that this change makes the need for a dask logo (#761) even more urgent. We need an icon for our profile pages!

**Comment by chdoig** [comment]
Hi @Dask, we are working on an open source project called "dask". The project has grown and we've built several libraries related to that effort (dask, distributed, hdfs3...). We would like "dask" to become its own organization to continue this effort and start a separate Github organization to keep this project growing. We can't see any public activity on your account, but if you are still using it and wouldn't mind changing your username, that would be greatly appreciated. Thank you!

**Comment by mrocklin** [comment]
The previous github user has graciously given us the name and we now have the `dask` org.  If no one has objections then in the next 24 hours I plan to move this repository to the dask organization and transfer membership of dask contributors from the `blaze` organization to the `dask` organization.  

Based on previous contributions, I plan to change permissions for the following users:

* @cowlicks : both blaze and dask
* @danielfrg : just dask
* @eriknw : just dask
* @jcrist : both blaze and dask
* @koverholt : just dask
* @martindurant : just dask
* @mrocklin : both blaze and dask
* @quasiben : just dask
* @shoyer : just dask
* @sinhrks : just dask

Please voice any objections soon.

**Comment by cowlicks** [comment]
lgtm and +1 on the move

**Comment by mrocklin** [comment]
Alrighty.  Moving.

**Comment by mrocklin** [comment]
Done.
