### ISSUE TITLE
[UPSTREAM] test_compatibility `AttributeError: module 'importlib' has no attribute 'metadata'`

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#9497]
We are having an import problem in `compatibility.py` more specifically in this line https://github.com/dask/dask/blob/6c151021c313e5d29d8ecca37d98456e7a3e36c2/dask/compatibility.py#L21

```python
AttributeError: module 'importlib' has no attribute 'metadata'
```
https://github.com/dask/dask/actions/runs/3055182028/jobs/4927954949#step:5:66970

I'm not able to reproduce it locally, I have the same version of `importlib-metadata`  but the test passes with no problems.

cc @jacobtomlinson and @jrbourbeau any ideas on what could be happening here?

**Comment by jrbourbeau** [comment]
Hrm, that's a weird one. Thanks for reporting @ncclementi. I'm also not immediately able to reproduce locally, so will need to dig in a bit more

**Comment by ncclementi** [comment]
Closing as https://github.com/dask/dask/pull/9604 was merged
