### ISSUE TITLE
[UPSTREAM] test_roundtrip_parquet_dask_to_spark `TypeError: Cannot cast DatetimeArray to dtype datetime64`

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#9498]
The issue here comes from pandas, see https://github.com/pandas-dev/pandas/issues/47844

According to the release issue tracker from pandas 1.5. They will address this before the release see https://github.com/pandas-dev/pandas/issues/45223#issuecomment-1247187887

I'd say we should hold on trying to "fix/workaround" this on our end until we have an update. 

cc: @jrbourbeau

**Comment by ian-r-rose** [comment]
Thanks for opening this @ncclementi. I agree, let's just skip this test on pandas 1.5 until upstream is fixed (whether in spark, pyarrow, or pandas)

**Comment by ian-r-rose** [comment]
It looks like the pandas folks plan to raise a deprecation warning here. Since the error is coming from pyspark, we'll probably need to filter out that warning until it is fixed over there.

**Comment by ian-r-rose** [comment]
Taking a look locally, and it seems that with https://github.com/pandas-dev/pandas/pull/48555 merged, this may require no action here.

**Comment by ncclementi** [comment]
I'm not sure if it's fully fixed as this issue was opened since the "fix" was merged: https://github.com/pandas-dev/pandas/issues/48574

It might not affect us, but to keep an eye on it.

**Comment by ncclementi** [comment]
Seeing this comment, https://github.com/dask/dask/pull/9494#issuecomment-1249482904
I'd say we can close this issue.
