### ISSUE TITLE
Selecting columns from a timeseries DataFrame changes the data

### ISSUE THREAD

**Issue by rjzamora** [dask/dask#9514]
**What happened**:

Selecting columns from a `DataFrame` created by `dask.datasets.timeseries` can sometimes change the data in those columns. It seems likely that the problem has something to do with `optimize_dataframe_getitem`, because using `compute(optimize_graph=False)` avoids the unexpected behavior.

**What you expected to happen**:

Selecting columns should **never** change the values in those columns.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd

ddf = dask.datasets.timeseries(
    end='2000-01-02',
    freq='3600s',
    partition_freq='1d',
    seed=1,
)

columns = ["x"]
dd.assert_eq(
    ddf[columns].compute(),
    ddf.compute()[columns],
)
```

This fails! (and moving to an earlier Dask version doesn't seem to resolve the problem)

**Comment by jrbourbeau** [comment]
That's not good! Thanks for surfacing @rjzamora. Have you noticed this other places outside of `timeseries`? I'm wondering if this issue applies to all DataFrames, or if it's related to our random seeding in `timeseries`

**Comment by rjzamora** [comment]
>it's related to our random seeding in timeseries

I'm 99.9% sure it's related to random sampling. I believe the random state evolution for a partition depends on the number and order of columns.

**Comment by jrbourbeau** [comment]
> I'm 99.9% sure it's related to random sampling

That's good to hear : ) Definitely still a bug, but glad it's isolated to `timeseries(...)`
