### ISSUE TITLE
dask array of integers allows assigning np.nan

### ISSUE THREAD

**Issue by ivirshup** [dask/dask#9526]
**Describe the issue**:

Assigning np.nan to a dask array with integer dtypes does not throw an error.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da, numpy as np

dask_array = da.ones((3, 3), dtype=int)
dask_array[:, 1] = np.nan
dask_array.compute()
```

```
array([[                   1, -9223372036854775808,                    1],
       [                   1, -9223372036854775808,                    1],
       [                   1, -9223372036854775808,                    1]])
```

This fails with numpy arrays:

```python
np_array = np.ones((3, 3), dtype=int)
np_array[:, 1] = np.nan
```

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [26], in <cell line: 2>()
      1 np_array = np.ones((3, 3), dtype=int)
----> 2 np_array[:, 1] = np.nan

ValueError: cannot convert float NaN to integer
```

**Anything else we need to know?**:

I was surprised to find that numpy allows assigning other floating point values to an integer array without complaining:

```python
np_array[:, 1] = 5.5
np_array
```

```
array([[1, 5, 1],
       [1, 5, 1],
       [1, 5, 1]])
```

**Environment**:

- Dask version: 2022.9.1
- Python version: Python 3.9.12 (main, Mar 26 2022, 15:52:10) [Clang 13.0.0 (clang-1300.0.29.30)]
- Operating System: macOS-11.6.8-x86_64-i386-64bit
- Install method (conda, pip, source): pip

**Comment by douglasdavis** [comment]
This indeed looks like a deviation from NumPy, and we should try to raise before compute time for this kind of error
