### ISSUE TITLE
Array.copy is not a no-op

### ISSUE THREAD

**Issue by djhoese** [dask/dask#9533]
**Describe the issue**:

The `Array.copy` docs say that `.copy()` is a no-op. However, if you actually do a copy a task is added to the graph and the `.name` of the original and new arrays are not equal.

https://docs.dask.org/en/stable/generated/dask.array.Array.copy.html

See the example below.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
a = da.zeros(5)
b = a.copy()
```

![orig_array](https://user-images.githubusercontent.com/1828519/193348368-93806016-39d4-44e9-b9c7-3a34a69bf376.png)

![copied_array](https://user-images.githubusercontent.com/1828519/193348388-9b6928e5-7d63-4e51-8f66-481b19ec561f.png)

**Anything else we need to know?**:

In the pyresample library we have custom objects that can contain dask arrays. In the `__eq__` of these methods we do a shortcut to avoid having to compute `a == b` by doing `a.name == b.name` if the objects are dask arrays. In a lot of our use cases a and b are relatively large arrays that are loaded from files on disk.

This is coming up as a problem for me with xarray where after new behavior to their deep copy logic, dask arrays are now being copied. See https://github.com/pydata/xarray/issues/7111 and https://github.com/pydata/xarray/pull/7089.

**Environment**:

- Dask version: 2022.9.1
- Python version: 3.10
- Operating System: PopOS
- Install method (conda, pip, source): conda-forge

**Comment by jrbourbeau** [comment]
Thanks @djhoese. It looks like this extra copy was added to provide better `x is y` consistency with NumPy (xref https://github.com/dask/dask/issues/3751, https://github.com/dask/dask/pull/3754). Is the issue here documentation or does it go beyond that? If documentation, we should update the `Array.copy` docstring

**Comment by davidhassell** [comment]
Hi - I'd just like to make a reference to https://dask.discourse.group/t/dask-array-copy-behaviour/1125, in case it's relevant here. Thanks.

**Comment by ian-r-rose** [comment]
I think I agree with @djhoese that `Array.copy` *should* be a no-op. What would be the purpose of mapping `copy` across array blocks in the context of a Dask `Array`? (there may be some, but I can't think of one). Morally speaking, Dask reserves the right to copy arrays, move memory around, and generally own the memory management of underlying blobs of data, and user `copy`ing of data seems counter to that.

I also don't really like the difference in behavior for `npartitions==1`, which doesn't seem very motivated. So I'd probably advocate for just removing that clause all-together. That seems like it would solve both @djhoese and @davidhassell's issues (also, sorry for the slow response @davidhassell!).

I think that a more dask-y way to do something like an `Array` copy would be to use `graph_manipulation.clone`, which creates entirely new keys and forces them to be computed separately. But that's a pretty advanced operation, and I don't think 99% of user code will need it.

**Comment by djhoese** [comment]
I didn't realize the single partition/chunk thing actually changed the results.

```
In [1]: import dask.array as da

In [2]: a = da.zeros((5, 5), chunks=2)

In [3]: b = a.copy()

In [4]: a.name
Out[4]: 'zeros_like-3acb6df8922fefc6974207cb32059cd5'

In [5]: b.name
Out[5]: 'zeros_like-3acb6df8922fefc6974207cb32059cd5'

In [6]: a = da.zeros((5, 5), chunks=-1)

In [7]: b = a.copy()

In [8]: a.name
Out[8]: 'zeros_like-3343f766929330014353da365dce3505'

In [9]: b.name
Out[9]: 'copy-93b3507bb0ab44949803361cb311a878'
```

So multiple chunks I get the same task name. Single chunk I get a new task name. Since dask tasks aren't supposed to modify the numpy array inplace (right?), there isn't a reason to copy the numpy array underneath (to convert a read-only array to a writable one).

**Comment by ian-r-rose** [comment]
I don't think I've heard anybody suggest a reason to keep the odd behavior for `npartitions==1`, so I suggest we remove it, which would make the docstring (closer-to) correct. @djhoese would you be interested in submitting a PR for that?

**Comment by djhoese** [comment]
Done: #9555

**Comment by davidhassell** [comment]
Thanks @djhoese and @ian-r-rose  - looks good to me.
