### ISSUE TITLE
Dask & Pandas giving different results for groupby aggregations 

### ISSUE THREAD

**Issue by etjkai** [dask/dask#9535]
**Describe the issue**:
Performing an aggregation on a groupby gives different results in both pandas and dask. Dask results vary across separate runs, while Pandas results remains constant.

I've done a fresh installation of (only) dask on a separate environment, yet still have the same results. I've installed dask version `'2022.9.2` 

**Minimal Complete Verifiable Example**:

```
import dask
dask.__version__

# Loading Data
df = dask.datasets.timeseries(seed=42)

# Dask Computation
df_zelda = df[df['name']=='Zelda']
dask_f = df_zelda.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()

# Pandas computation
pandas_df = df_zelda.compute()
pandas_f = pandas_df.groupby("name").aggregate({"x": "sum", "y": "max"})

print(dask_f)
print(pandas_f)

```

**Anything else we need to know?**:

Screenshot as shown: 

![alt text](https://i.imgur.com/vGRelRp.png)

**Environment**:

- Dask version: 2022.9.2
- Python version: 3.8.0
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by SultanOrazbayev** [comment]
I tested this on the dask 2022.8.0 version and the code executes correctly (the computed results match), so there is something in the recent upgrades that breaks the calculation.

**Comment by SultanOrazbayev** [comment]
Examining this further, it seems the issue is related to the name of the column "x". Specifically, renaming column "x" to another name resolves the issue in 2022.9.2. This might be related to https://github.com/dask/dask/issues/9313.

**Comment by hayesgb** [comment]
Thanks @etjkai. 

+ @ian-r-rose -- can you take a look?

**Comment by phobson** [comment]
@etjkai if you `.persist() the original df (like below) does it work for you?

```python
import dask
dask.__version__

# Loading Data
df = dask.datasets.timeseries(seed=42).persist() ## <---- change here

# Dask Computation
df_zelda = df[df['name']=='Zelda']
dask_f = df_zelda.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()

# Pandas computation
pandas_df = df_zelda.compute()
pandas_f = pandas_df.groupby("name").aggregate({"x": "sum", "y": "max"})

print(dask_f)
print(pandas_f)
```

**Comment by ian-r-rose** [comment]
Thanks for the report @etjkai! I can reproduce the issue locally as well.

A quick git bisect points to #9442

**Comment by ian-r-rose** [comment]
I suspect this has the same underlying cause as #9514
