### ISSUE TITLE
Adding support for string timedelta in map_overlap before/after parameters

### ISSUE THREAD

**Issue by epizut** [dask/dask#9554]
It would be convenient to allow string timedelta in _map_overlap_ _before_ and _after_ parameters:

`dask.dataframe.rolling.map_overlap(func, dd, before='5min', after=0)`

Also setting a default value to zero could improve readability:

`dask.dataframe.rolling.map_overlap(func, dd, before='5min')`

I can work on a PR, if it makes sense.

**Comment by douglasdavis** [comment]
@epizut a PR would certainly be welcome!

**Comment by epizut** [comment]
Unfortunately, I can't set a default value (=0) of _before_ and _after_ without breaking the API.
We could move _*args_ a bit forward and promote _before_ and _after_ as keyword arguments.
It will also better match what was done in _map_partitions()_.
