### ISSUE TITLE
.set_index looses name

### ISSUE THREAD

**Issue by jreback** [dask/dask#956]
```
ddf = dd.DataFrame(....)
result = ddf.set_index('name')
asseret result.index.name == 'name'
```

**Comment by jcrist** [comment]
We don't track index names as part of the metadata (see https://github.com/blaze/dask/issues/812), but we should. The best fix for this would probably be to keep an empty dataframe/series with the proper columns/index/name as metadata, which has been proposed before. This would actually fix several of the issues you just submitted :).
