### ISSUE TITLE
 Length of passed values is 166, index implies 165.

### ISSUE THREAD

**Issue by Zzlan95** [dask/dask#9562]
xgbst
# XGBoosting feature importance
plot_feature_importance(xgbst, labels=predictors)
plt.show()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-50-c5afda58946b> in <module>
      1 # XGBoosting feature importance
----> 2 plot_feature_importance(xgbst, labels=predictors)
      3 plt.show()

~/Desktop/usyd/QBUS6600/Screen Australia/tutorial9.py in plot_feature_importance(model, labels, max_features)
     42     feature_importance = model.feature_importances_*100
     43     feature_importance = 100*(feature_importance/np.max(feature_importance))
---> 44     table = pd.Series(feature_importance, index = labels).sort_values(ascending=True, inplace=False)
     45     fig, ax = fig, ax = plt.subplots(figsize=(9,6))
     46     if len(table) > max_features:

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    348                 try:
    349                     if len(index) != len(data):
--> 350                         raise ValueError(
    351                             f"Length of passed values is {len(data)}, "
    352                             f"index implies {len(index)}."

ValueError: Length of passed values is 166, index implies 165.

how can i fix this issue?

**Comment by phobson** [comment]
@Zzlan95 from the traceback you posted, this doesn't appear to be a dask issue. The lengths of your `feature_importance` and `labels` sequences are mismatched.
