### ISSUE TITLE
Non-working implicit dask dataframe promotion in map_overlap

### ISSUE THREAD

**Issue by epizut** [dask/dask#9567]
_map_overlap()_ is unable to handle raw pandas DataFrame, unlike _map_partition()_.

```
import dask.dataframe
import pandas as pd

df = pd.util.testing.makeMixedDataFrame()

# Works  fine
dask.dataframe.map_partitions(lambda df: df, df)

# Raises "IndexError: list index out of range"
dask.dataframe.rolling.map_overlap(lambda df: df, df, before=0, after=0)
```
![image](https://user-images.githubusercontent.com/1694892/195291225-3961d434-7c67-43e4-a265-6d3258ec988e.png)

It looks like it should be working as we can see the following code in _map_overlap()_:
```
if align_dataframes:
    args = _maybe_from_pandas(args)
```

I can work on a PR if needed.

**Comment by faulaire** [comment]
Hi,

Just opened a pull request to adress this issue : #9571

**Comment by hayesgb** [comment]
This looks like a nice add to me.  Appreciate the tests to support.
