### ISSUE TITLE
add support for .sort_values

### ISSUE THREAD

**Issue by jreback** [dask/dask#958]
so this allows sub-sorting

e.g.

```
ddf = dd.DataFrame(....)
ddf = ddf.set_index('stock')
ddf = ddf.map_partitions(lambda x: x.sort_values('date'))
```

this is conceptually the same as (in pandas)

```
df = pd.DataFrame(....)
df = df.set_index(['stock,'date']).sort_index()
```

**Comment by mgsnuno** [comment]
@jreback I modified `dask/dataframe/core.py` to include the following:

```python
    @derived_from(pd.DataFrame)
    def sort_values(self, by, split_every=None, split_out=1):
        return aca(
            self,
            chunk=M.sort_values,
            aggregate=M.sort_values,
            meta=self._meta,
            token="dataframe-sort_values",
            split_every=split_every,
            split_out=split_out,
            by=by,
        )
```

following what is done for `nlargest/smallest` and `value_counts`.

Is this a good way to go?

**Comment by mgsnuno** [comment]
@jreback @mrocklin any advice if using the `aca` approach is good to implement `sort_values`? If so I can open a PR with this change.

**Comment by TomAugspurger** [comment]
Will that be sufficient to sort values across partitions?

**Comment by mgsnuno** [comment]
Not sure, that is why I'm asking, but:

```python
chunk=M.sort_values,
aggregate=M.sort_values,
```
should sort everything right?

**Comment by mrocklin** [comment]
aca returns a dataframe with a single partition.

In general distributed sorting algorithms are more complex than aca can
provide.  I think that the right approach here is probably to reuse the
code within set_index.  I wouldn't be surprised if you could get this to
work with some combination of set_index and reset_index

**Comment by TomAugspurger** [comment]
> aca returns a dataframe with a single partition.

Ah, right, thanks.

Agreed that reusing `set_index` is going to achieve much of what we want.

Though, it should be re-emphasized that you should look for alternatives to a full sort_values. With Dask, a `sort_values` will destroy any partition info that you might have had.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/8263
