### ISSUE TITLE
`pytest`-related test failures on `main`

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9597]
We're seeing failures like 

```python
 INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/xdist/plugin.py", line 192, in pytest_configure
INTERNALERROR>     from xdist.dsession import DSession
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/xdist/dsession.py", line 5, in <module>
INTERNALERROR>     from xdist.scheduler import (
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/xdist/scheduler/__init__.py", line 1, in <module>
INTERNALERROR>     from xdist.scheduler.each import EachScheduling  # noqa
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/xdist/scheduler/each.py", line 1, in <module>
INTERNALERROR>     from py.log import Producer
INTERNALERROR> ModuleNotFoundError: No module named 'py.log'; 'py' is not a package
```

on `main`. For an example of this in action see [this CI build](https://github.com/dask/dask/actions/runs/3323657949/jobs/5494288298)

**Comment by jakirkham** [comment]
Copying my comment ( https://github.com/dask/dask/pull/9596#issuecomment-1291045452 ) here:

> Maybe this is related to the recent `pytest` upgrade ( https://github.com/conda-forge/pytest-feedstock/pull/153 )? Perhaps we can raise a reproducer on that feedstock

**Comment by jrbourbeau** [comment]
Here's the upstream issue in `pytest` https://github.com/pytest-dev/pytest/issues/10422 / https://github.com/pytest-dev/pytest/issues/10420. Looks like this is related to `pytest-benchmark` not declaring a dependency (xref https://github.com/ionelmc/pytest-benchmark/pull/227) -- though I don't think we have `pytest-benchmark` installed in our CI environments. Folks upstream in `pytest` are pointing to this `pytest-benchmark` fix https://github.com/ionelmc/pytest-benchmark/pull/227. I'll try pinning `pytest` in CI to see if that works as a temporary fix.

**Comment by jrbourbeau** [comment]
Ah, it looks like various `pytest-*` packages are impacted by an upstream `pytest` change. In our case, I think it's `pytest-xdist` (xref https://github.com/pytest-dev/pytest-xdist/issues/832)

**Comment by jakirkham** [comment]
We can just install `py` on our CI while they work through these issues (which probably will take some time)

**Comment by jrbourbeau** [comment]
Yeah, I was just coming around to that. Do you think it's worth add `py` upstream in the `pytest` conda-forge recipe?

**Comment by jakirkham** [comment]
We could raise that in a feedstock issue and see what the maintainers say

**Comment by jrbourbeau** [comment]
Closing as fixed (xref https://github.com/dask/dask/pull/9596#issuecomment-1291094796)

**Comment by The-Compiler** [comment]
With my pytest maintainer hat on: Please *don't* add `py` as hard dependency to `pytest` itself - the whole point of the change in pytest is to get rid of the dependency where it's not actually needed. That various plugins use `py` without directly declaring it as a dependency is unfortunate, but that should be fixed in those plugins (or in their package, if necessary as a workaround), and not by installing `py` in all pytest installs.
