### ISSUE TITLE
Set `python<3.11` restriction? 

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9605]
Python 3.11 is out (🎉) but Dask doesn't yet have support for Python 3.11 (🙁). Users are starting to report issues (xref https://github.com/dask/distributed/issues/7211) and, in general, I wouldn't expect them to have a good experience on Python 3.11 yet. IIRC historically we haven't set upper limits on Python versions, though maybe we should to make sure Dask users have a working setup until we add support for Python 3.11

cc @jakirkham @fjetter @crusaderky @ian-r-rose for thoughts

**Comment by jakirkham** [comment]
This came up in another context previously and a colleague shared [this blogpost]( https://iscinumpy.dev/post/bound-version-constraints/#tldr ), which suggests not having an upper bound

**Comment by jacobtomlinson** [comment]
A quote from the post @jakirkham shared

> Never cap Python

Perhaps it would make sense to create a Python `3.11` milestone or label and put all issues under that. I think users are quite understanding that supporting new Python versions is always a work in progress. But communicating that we care about supporting it eventually would be a good thing to do.

We could also consider adding the `3.12` beta to CI and actively aim to support it on day 1.

**Comment by crusaderky** [comment]
Getting bug reports about python 3.11 is good. It helps us implement support faster.
I agree that most users should understand that a brand new python version always has bumpy support from packages in the first few weeks.
-1 for capping the python version from me too.

**Comment by fjetter** [comment]
To cite the blogpost

> Only add a cap if a dependency is known to be incompatible or there is a high (>75%) chance of it being incompatible in its next release.

We're very certain that distributed in its current version will not run with python 3.11. There are a couple of asyncio issues to work through first. We invested in this effort already a lot but couldn't complete it, yet (for instance, the entire loop runner effort)

Given this knowledge why wouldn't we pin?

+1 for the milestone

**Comment by jakirkham** [comment]
Think the other practical thing to be aware of is if we add a pin to the current Dask & Distributed release. It won't be present in previous releases. The reason this matters is users could end up installing an earlier version and not encountering this pin.

Also some solvers (Conda definitely does this), will pick older version of Dask & Distributed (if none is specified) to meet Python version requirements.

In `conda-forge` (and `defaults`) repodata can be hot-fixed, which backport a Python version constraint backwards. This is not possible with PyPI.

**Comment by mmccarty** [comment]
I'm not sure pinning gets you anything given that it would only exist in the current version going forward. You could just add a note on the [install](https://docs.dask.org/en/stable/install.html) page letting users know the Python 3.11 is not yet fully baked and reference the milestone.

**Comment by mrocklin** [comment]
Zooming out a bit, is any group currently working on supporting 3.11?  cc'ing also @quasiben in case his folks are interested in supporting here.

**Comment by jrbourbeau** [comment]
Tom has a PR over in `dask/distributed` for adding Python 3.11 (xref https://github.com/dask/distributed/pull/7249). Nobody has started on `dask/dask` support for Python 3.11 -- just opened this issue for tracking that https://github.com/dask/dask/issues/9691

**Comment by jrbourbeau** [comment]
Going to close this as we now have Python 3.11 support (xref https://github.com/dask/dask/pull/9708, https://github.com/dask/distributed/pull/7249)
