### ISSUE TITLE
Fully support partial functions as aggregations

### ISSUE THREAD

**Issue by ChrisJar** [dask/dask#9615]
Currently in `dask.dataframe`, Dask ignores any arguments given to a function in a `partial` when performing an aggregation.

For example:
```python
import pandas as pd
import numpy as np
import dask.dataframe as dd
from functools import partial

df = pd.DataFrame({
    "a": [5, 4, 3, 5, 4, 2, 3, 2],
    "b": [1, 2, 5, 6, 9, 2, 6, 8],
})
ddf = dd.from_pandas(df, npartitions=1)
ddf.groupby("a").agg(partial(np.std, ddof=-2)).compute()
```
returns
```
          b
a          
5  3.535534
4  4.949747
3  0.707107
2  4.242641
```
whereas in pandas:
```python
df.groupby("a").agg(partial(np.std, ddof=-2))
```
returns:
```
          b
a          
2  2.121320
3  0.353553
4  2.474874
5  1.767767
```
The discrepancy is because Dask ignores the`ddof` argument and defualts to `ddof=1`. It'd be great if there were some way for Dask to recognize and take those arguments into account like Pandas does.

**Comment by phobson** [comment]
Thanks for the report, @ChrisJar. I can replicate this on the latest release of dask and distributed.

To be crystal clear, I modified your reproducer slightly to put the discrepancies front-and-center:

```python
import pandas as pd
import numpy as np
import dask.dataframe as dd
from functools import partial

df = pd.DataFrame({
    "a": [5, 4, 3, 5, 4, 2, 3, 2],
    "b": [1, 2, 5, 6, 9, 2, 6, 8],
})
ddf = dd.from_pandas(df, npartitions=1)


pd.concat([
    df.groupby("a").agg(partial(np.std, ddof=1))["b"],
    df.groupby("a").agg(partial(np.std, ddof=-2))["b"],
    ddf.groupby("a").agg(partial(np.std, ddof=1))["b"].compute(),
    ddf.groupby("a").agg(partial(np.std, ddof=-2))["b"].compute(),
], axis=1, keys=[ ("pandas", "ddof=1"), ("pandas", "ddof=-2"), ("dask", "ddof=1"), ("dask", "ddof=-2")])
```

|   a |   ('pandas', 'ddof=1') |   ('pandas', 'ddof=-2') |   ('dask', 'ddof=1') |   ('dask', 'ddof=-2') |
|----:|-----------------------:|------------------------:|---------------------:|----------------------:|
|   2 |               4.24264  |                2.12132  |             4.24264  |              4.24264  |
|   3 |               0.707107 |                0.353553 |             0.707107 |              0.707107 |
|   4 |               4.94975  |                2.47487  |             4.94975  |              4.94975  |
|   5 |               3.53553  |                1.76777  |             3.53553  |              3.53553  |

**Comment by j-bennet** [comment]
May be able to close this via https://github.com/dask/dask/pull/9724.

**Comment by ncclementi** [comment]
Thanks @j-bennet. For some reason, the issue didn't close itself when the PR is merged. Closing now!!
