### ISSUE TITLE
Include Dataframe API in Dataframe dropdown in docs

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#9629]
I wanted to get to the API docs for Dask dataframe.  I clicked on the "DataFrame" section on the left and was surprised not to see "API" as an option.  I then saw the separate "API reference" option below and clicked there and found it.

I think that we should have a link to this page in both places.

@jsignell @jacobtomlinson any objection?  Honestly if diataxis says that this is a bad idea then I think my response is that diataxis is obviously wrong?

**Comment by jacobtomlinson** [comment]
> Honestly if diataxis says that this is a bad idea then I think my response is that diataxis is obviously wrong?

diataxis says the API reference should live in the reference section which I totally agree with. It doesn't say you can't link to it though so I think also having it under the explanation section makes sense.
