### ISSUE TITLE
padding datetime arrays with missing values

### ISSUE THREAD

**Issue by keewis** [dask/dask#9645]
**Describe the issue**:

Trying to pad with `NaT` (the `nan`-equivalent for datetime dtypes) results in a `TypeError`:
```pytb
TypeError: `pad_value` must be composed of integral typed values.
```
This is the case for `np.datetime64("NaT")`, `np.array("NaT", dtype="datetime64")` and `np.array(["NaT"], dtype="datetime64")`

I think the reason for this is that `dask.array.creation.expand_pad_value` checks if the value is an instance of `Number` or `Sequence`, but that evaluates to `False` for dtype instances and 0d arrays.

<details><summary><b>Minimal Complete Verifiable Example</b></summary>

```python
In [1]: import dask.array as da
   ...: import pandas as pd
   ...: import numpy as np

In [2]: a = da.from_array(
   ...:     pd.date_range("2022-04-01", freq="s", periods=15).to_numpy(), chunks=(5,)
   ...: )
   ...: a
Out[2]: dask.array<array, shape=(15,), dtype=datetime64[ns], chunksize=(5,), chunktype=numpy.ndarray>

In [3]: np.pad(a, (1, 1), mode="constant", constant_values=np.datetime64("NaT"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [3], line 1
----> 1 np.pad(a, (1, 1), mode="constant", constant_values=np.datetime64("NaT"))

File <__array_function__ internals>:180, in pad(*args, **kwargs)

File .../dask/array/core.py:1760, in Array.__array_function__(self, func, types, args, kwargs)
   1757 if has_keyword(da_func, "like"):
   1758     kwargs["like"] = self
-> 1760 return da_func(*args, **kwargs)

File .../dask/array/creation.py:1231, in pad(array, pad_width, mode, **kwargs)
   1229 elif mode == "constant":
   1230     kwargs.setdefault("constant_values", 0)
-> 1231     return pad_edge(array, pad_width, mode, **kwargs)
   1232 elif mode == "linear_ramp":
   1233     kwargs.setdefault("end_values", 0)

File .../dask/array/creation.py:966, in pad_edge(array, pad_width, mode, **kwargs)
    959 def pad_edge(array, pad_width, mode, **kwargs):
    960     """
    961     Helper function for padding edges.
    962 
    963     Handles the cases where the only the values on the edge are needed.
    964     """
--> 966     kwargs = {k: expand_pad_value(array, v) for k, v in kwargs.items()}
    968     result = array
    969     for d in range(array.ndim):

File .../dask/array/creation.py:966, in <dictcomp>(.0)
    959 def pad_edge(array, pad_width, mode, **kwargs):
    960     """
    961     Helper function for padding edges.
    962 
    963     Handles the cases where the only the values on the edge are needed.
    964     """
--> 966     kwargs = {k: expand_pad_value(array, v) for k, v in kwargs.items()}
    968     result = array
    969     for d in range(array.ndim):

File .../dask/array/creation.py:912, in expand_pad_value(array, pad_value)
    910     pad_value = array.ndim * (tuple(pad_value[0]),)
    911 else:
--> 912     raise TypeError("`pad_value` must be composed of integral typed values.")
    914 return pad_value

TypeError: `pad_value` must be composed of integral typed values.
```

</details>

**Anything else we need to know?**:

I wonder if 0d arrays could be considered scalars in general? That would also help fixing xarray-contrib/pint-xarray#186

**Environment**:

- Dask version: `2022.10.2+11.g9d624c6df`
- Python version: `3.10.6`
- Operating System: `ubuntu 22.04`
- Install method (conda, pip, source): `pip install -e <path to git checkout>`

**Comment by keewis** [comment]
actually, this might be a duplicate of #4841?

**Comment by keewis** [comment]
changing https://github.com/dask/dask/blob/9d624c6dfd452ad8966ff5011b736614a32793d2/dask/array/creation.py#L881 to
```python
if isinstance(pad_value, Number) or np.isscalar(pad_value) or getattr(pad_value, "ndim", None) == 0:
```
seems to resolve this issue, for both numpy scalars and 0d arrays (though I didn't try other array implementations like `cupy`).

If that sounds good to you, I'd be happy to send in a PR.

**Comment by phobson** [comment]
@keewis hmm -- I don't have this around my head yet. Let us think about this a bit.

**Comment by keewis** [comment]
sure, sounds good to me (and I didn't mean to push). The fix works for me, so I'll just continue using that for now.

**Comment by jrbourbeau** [comment]
Thanks for the issue @keewis 

> I wonder if 0d arrays could be considered scalars in general?

I think the `getattr(pad_value, "ndim", None) == 0` makes sense as `numpy` supports this case

```python
In [5]: np.pad(a, np.array(2), 'mean')
Out[5]: array([3, 3, 1, 2, 3, 4, 5, 3, 3])
```

I'm curious what `np.isscalar(pad_value)` gets us beyond what `isinstance(pad_value, Number)` already provides 

> I'd be happy to send in a PR.

If you've got bandwidth for that a PR would be welcome

**Comment by keewis** [comment]
> I'm curious what np.isscalar(pad_value) gets us beyond what isinstance(pad_value, Number) already provides

I was not sure whether numpy scalars would define `ndim`, so my idea was to check if "`pad_value` is a number, a numpy scalar, or a 0d array". However, since numpy scalars do define `ndim == 0` I agree that it doesn't add anything and can be removed.

> If you've got bandwidth for that a PR would be welcome

Sure, I'll try to take a stab at this on Monday.
