### ISSUE TITLE
Prometheus documentation is outdated

### ISSUE THREAD

**Issue by hendrikmakait** [dask/dask#9648]
As pointed out in dask/distributed#7295, the Prometheus documentation is outdated and does not reflect recent additions to the exposed metrics in `distributed`. The docs should be updated. 

Since all of the Prometheus-related code resides in `distributed`, I would suggest moving the documentation over there to avoid having to synchronize across repositories (which has already proven not to work given the current state of the documentation). Thoughts? cc @fjetter

**Comment by mrocklin** [comment]
To add context, the distributed docs don't really get traffic.  We direct
everyone to docs.dask.org.  If this is more internal technical
documentation then great, but if we want users to be exposed to things then
we probably should keep things over on Dask.

**Comment by hendrikmakait** [comment]
I think it might make sense to split the documentation into two parts, a guide/how-to part living in `dask/dask` for traffic which then links to the technical metric reference in `dask/distributed`. Before doing that, let's finish up #9696 and dask/distributed#7368. cc @crusaderky
