### ISSUE TITLE
'pandas\_libs\missing.pyx", line 382, in pandas._libs.missing.NAType.__bool__'

### ISSUE THREAD

**Issue by frbelotto** [dask/dask#9651]
Hello guys,
I am working on a Pandas dataframe with about 5million rows and and about 145 megabytes (4,776,548 rows and 3 + index). It's not big but applying a pandas function is taking a very long time.

This is the head of my current DF :
![image](https://user-images.githubusercontent.com/24688087/201488391-560c627b-ec77-454a-8196-e24f383a9040.png)

And this are the dtypes:
![image](https://user-images.githubusercontent.com/24688087/201488417-ccce8e26-4848-495b-8cfe-0a4137625176.png)

The function to be applied if to check the values of each column ('produto', 'Afiliados'), ('produto', 'Giftcards') and ('produto', 'Recargas') and set if the cliente has used all products or a combination of them. When applying it o pandas take a long time but it works.

```
def classifica(row):
    if ((row[('produto', 'Afiliados')] >= 1) & (row[('produto', 'Giftcards')] >= 1) &  (row[('produto', 'Recargas')] >= 1)): 
        return '3Produtos'`
```

I´ve been reading about Dask as an alternativa, so I´ve tried to split my DF and run the same function:

```
import dask.dataframe as dd
ddf = dd.from_pandas(base_consumo, npartitions=5)
ddf['tipo'] = ddf.apply(classifica, axis=1)
```

This is the result dataframe:
![image](https://user-images.githubusercontent.com/24688087/201488709-4e5af685-7288-40d2-9b12-e5855605000b.png)

That´s is the problem: 
```
TypeError                                 Traceback (most recent call last)
File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\dataframe\utils.py:195, in raise_on_meta_error(funcname, udf)
    194 try:
--> 195     yield
    196 except Exception as e:

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\dataframe\core.py:6557, in _emulate(func, udf, *args, **kwargs)
   6556 with raise_on_meta_error(funcname(func), udf=udf), check_numeric_only_deprecation():
-> 6557     return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\utils.py:1103, in methodcaller.__call__(self, _methodcaller__obj, *args, **kwargs)
   1102 def __call__(self, __obj, *args, **kwargs):
-> 1103     return getattr(__obj, self.method)(*args, **kwargs)

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:9555, in DataFrame.apply(self, func, axis, raw, result_type, args, **kwargs)
   9546 op = frame_apply(
   9547     self,
   9548     func=func,
   (...)
   9553     kwargs=kwargs,
   9554 )
-> 9555 return op.apply().__finalize__(self, method="apply")

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\apply.py:746, in FrameApply.apply(self)
...
    results[i] = self.f(v)
  File "C:\Users\fabio\AppData\Local\Temp\ipykernel_10788\21312928.py", line 2, in classifica
    if ((row[('produto', 'Afiliados')] >= 1) & (row[('produto', 'Giftcards')] >= 1) &  (row[('produto', 'Recargas')] >= 1)):
  File "pandas\_libs\missing.pyx", line 382, in pandas._libs.missing.NAType.__bool__
```

I´ve tried to search about the "pandas._libs.missing.NAType.__bool__" error but the only thing that I found was an [old pandas doc](https://pandas.pydata.org/pandas-docs/version/1.0.0/user_guide/missing_data.html) , but I couldn't figure out any solution. 

**Environment**:
- Dask version: 2022.10.2
- Python version: 3.10.8 64-bits
- Operating System: Windows 11
- Install method (conda, pip, source): pip

**Comment by ncclementi** [comment]
It's a bit hard to be able to help without a minimal reproducible example. It's not clear what is the code that you run that throws the error. However, this seems more of a pandas issues, but couple of thing that might help. 

1. Which pandas version do you have? 
2. this SO question https://stackoverflow.com/questions/69987112/how-to-map-na-values-of-the-type-pandas-libs-missing-natype

To be able to help, we need a minimal reproducible example see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by frbelotto** [comment]
I am using pandas 1.5.1, the last version.
I´ve been trying to create a sample data or extract a small data of my dataframe to recreate such error over it but I couldn't, but I still have an error over a sample data :

**sample data**
```
`num_variables = 1000
rng = np.random.default_rng()

data = pd.DataFrame({
    'id' :  np.random.randint(1,999999999,num_variables),
    'date' : [np.random.choice(pd.date_range(datetime.datetime(2021,1,1),datetime.datetime(2022,12,31))) for i in range(num_variables)],
    'product' : [np.random.choice(['pre-paid phone', 'giftcards', 'afiliates']) for i in range(num_variables)],
    'brand' : [np.random.choice(['brand_1', 'brand_2', 'brand_4', 'brand_6']) for i in range(num_variables)],
    'gmv' : rng.random(num_variables) * 100,
    'revenue' : rng.random(num_variables) * 100,})

datab = pd.DataFrame({'id' : np.nan,
    'date' : datetime.datetime(2022,1,1),
    'product' : 'afiliates',
    'brand' : 'brand_1',
    'gmv' : 50,
    'revenue' : 10}, index = [0])
data = pd.concat([data,datab])
data = data.astype({'product':'category', 'brand':'category'})

**adjusting/filtering data** 
```
`base = data[['product', 'id']].loc[(data['date'].dt.date >= datetime.date(2022,1,1))].groupby(['id', 'product']).aggregate({'product' : 'count'})
#base = base.convert_dtypes(infer_objects=True, convert_string=True, convert_integer=True, convert_boolean=True, convert_floating=True)
base = base.unstack()`
```


simple test function
`def setup(row):
    if row[('product', 'afiliates')] >= 1 and row[('product', 'giftcards')]:
        return 'afiliates_gift'`

dask apply command (the function does work using pandas apply)
`ddf = dd.from_pandas(data, npartitions=2)
ddf
ddf['type'] = ddf.apply(setup, axis=1)`


dask error
```
`KeyError                                  Traceback (most recent call last)
File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\dataframe\utils.py:195, in raise_on_meta_error(funcname, udf)
    194 try:
--> 195     yield
    196 except Exception as e:

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\dataframe\core.py:6557, in _emulate(func, udf, *args, **kwargs)
   6556 with raise_on_meta_error(funcname(func), udf=udf), check_numeric_only_deprecation():
-> 6557     return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\utils.py:1103, in methodcaller.__call__(self, _methodcaller__obj, *args, **kwargs)
   1102 def __call__(self, __obj, *args, **kwargs):
-> 1103     return getattr(__obj, self.method)(*args, **kwargs)

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:9555, in DataFrame.apply(self, func, axis, raw, result_type, args, **kwargs)
   9546 op = frame_apply(
   9547     self,
   9548     func=func,
   (...)
   9553     kwargs=kwargs,
   9554 )
-> 9555 return op.apply().__finalize__(self, method="apply")

File c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\apply.py:746, in FrameApply.apply(self)
...
  File "c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1022, in _get_with
    return self._get_values_tuple(key)
  File "c:\Users\fabio\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1060, in _get_values_tuple
    raise KeyError("key of type tuple not found and not a MultiIndex")`
```
