### ISSUE TITLE
gpuCI hanging

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9657]
In https://github.com/dask/dask/pull/9655 and https://github.com/dask/distributed/pull/5648 it appears the gpuCI build is stuck even though when I go to the live logs I can see the test suite itself has already finished running / passed. 

![Screen Shot 2022-11-14 at 2 57 12 PM](https://user-images.githubusercontent.com/11656932/201764333-a90a7c98-1be6-4c76-bf89-6bf953f3aae8.png)

cc @quasiben @charlesbluca

**Comment by charlesbluca** [comment]
Yeah I've periodically seen this issue occur on RAPIDS projects with gpuCI, imagine it's an issue with the Jenkins build not receiving the results of the test run to send back to GitHub, and that rerunning tests should resolve.

I should note that RAPIDS is currently migrating many of its gpuCI workflows to GitHub Actions, and once this process is well-defined making this change for the Dask projects should prevent issues like this moving forward

**Comment by jrbourbeau** [comment]
Thanks @charlesbluca! I see you've restarted CI here https://github.com/dask/distributed/pull/5648#issuecomment-1314380953, if that causes things to pass, then we can close this issue out (assuming this is just a transient thing). 

Nice to hear about the GHA migration. Looking forward to seeing what that looks like

**Comment by charlesbluca** [comment]
Looks like that go the check status to publish properly 🙂 

![image](https://user-images.githubusercontent.com/20627856/201766741-20d2593a-be2a-4afb-8401-2e7ac2b00b2a.png)
