### ISSUE TITLE
`read_parquet` with `arrow_to_pandas` can cause incorrect `_meta`

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#9664]
**Describe the issue**:

If users provide a `arrow_to_pandas` argument that affects the dtypes, the Dask DataFrame's `_meta` will be incorrect.

**Minimal Complete Verifiable Example**:

```python
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> df = pd.DataFrame({"A": [pd.Timestamp("2000-01-01")]})
>>> df.to_parquet("/tmp/test.parquet")
>>> ddf = dd.read_parquet("/tmp/test.parquet", arrow_to_pandas={"timestamp_as_object": True})
>>> ddf.A.dtype
dtype('<M8[ns]')
>>> ddf.compute().A.dtype
dtype('O')
```

I don't know exactly how `_meta` is constructed from the parquet / arrow metadata, but if there's call to `.to_pandas()` maybe fixing this is as easy as including the user-provided argument.

**Comment by quasiben** [comment]
II think this is something which came up last year: https://github.com/dask/dask/issues/7219 .   We could do some kind of additional reseting of `meta` in https://github.com/dask/dask/blob/08db480f9387aab3c93c4f256b7c4c726a7314fb/dask/dataframe/io/parquet/core.py#L473-L495

**Comment by rjzamora** [comment]
We can certainly fix this by updating `_create_dd_meta` for the arrow engine to use `_arrow_table_to_pandas`
