### ISSUE TITLE
fft fails for all netcdf files imported with xarray

### ISSUE THREAD

**Issue by nvogtvincent** [dask/dask#9679]
**Describe the issue**:
Dask fft raises a `DataArray.map_blocks() got an unexpected keyword argument 'dtype'` error when operating on any dask array imported via `xr.open_dataset`

**Minimal Complete Verifiable Example**:

Using the sample netcdf file `ECMWF_ERA-40_subset.nc` available [here](https://www.unidata.ucar.edu/software/netcdf/examples/files.html):

```python
import xarray as xr
import dask.array as da

# Load netcdf file
ds = xr.open_dataset('ECMWF_ERA-40_subset.nc', chunks={'longitude': 20, 'latitude': 20})

# Carry out fft
ds_fft = da.fft.fft(ds.tp, axis=0)
```

**Environment**:

- Dask version: 2022.11.0
- Python version: 3.10.6
- Operating System: Ubuntu
- Install method (conda, pip, source): conda via clean install

**Comment by ncclementi** [comment]
I can reproduce this, 
For completion this is the traceback:
```python-traceback
TypeError                                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 ds_fft = da.fft.fft(ds.tp, axis=0)

File ~/mambaforge/envs/issue-9679/lib/python3.9/site-packages/dask/array/fft.py:205, in fft_wrap.<locals>.func(a, n, axis)
    202 if axis is not None:
    203     axes = (axis,)
--> 205 return _func(a, s, axes)

File ~/mambaforge/envs/issue-9679/lib/python3.9/site-packages/dask/array/fft.py:191, in fft_wrap.<locals>.func(a, s, axes)
    188     n = None if s is None else s[0]
    189     args = (n, axis)
--> 191 return a.map_blocks(fft_func, *args, dtype=_dtype, chunks=chunks)

TypeError: map_blocks() got an unexpected keyword argument 'dtype'
```

The only thing I can think might have affected this, are the changes related to this https://github.com/dask/dask/pull/9616/files 

@hendrikmakait can you take a look at this one?
