### ISSUE TITLE
Clarifications for dependencies and unittests

### ISSUE THREAD

**Issue by sciunto** [dask/dask#968]
Hi,

For a packager (like me :) ) it's useful to have full list of dependencies and also what we need to run tests (and how).

There is some discrepancies between https://github.com/blaze/dask#dependencies and http://dask.pydata.org/en/latest/install.html

For the unittests, it seems that we need python-pygraphviz and python-cachey

Thanks!

**Comment by mrocklin** [comment]
Hi @sciunto `cachey` and `graphviz` are purely optional.  The dask collections include interactions with a variety of other non-essential libraries.  We include guarded tests for these libraries if they are present but tests should pass fine if they aren't around.  We don't want to require users to install these.  We prefer to keep the core library lightweight.  Are you running into exceptions when trying to run tests?

I run tests with `py.test dask`.  I agree that we should put this into the documentation.

**Comment by sciunto** [comment]
I answered for the tests in the PR.

There is still the difference I pointed out between the documentation and the readme. ;)
