### ISSUE TITLE
to_csv should just simply be using multiple cores especially if I export it to  multipel CSV

### ISSUE THREAD

**Issue by stromal** [dask/dask#9683]
**Describe the issue**:

to_csv should just simply be using multiple cores especially if I export it to  multipel CSV

```ddf.to_csv('mydata/myfile-*.csv', index=False)``` it exports with the same speed as single file export.

```ddf.to_csv('myfile.csv', index=False)```  it tis super slow as well.

DASK exist to give an easy big data alternative to spark.
I dont ever wat to see code like this
```
import dask.bag as bag
import json
b = bag.from_filenames('input.json.gz').map(json.loads).map(manipulate).concat()
b.map(lambda t: ','.join(map(str, t)).to_textfiles('out.*.csv').compute()
```

I have read about https://docs.dask.org/en/latest/dataframe-parquet.html this does not answers the question that for exporting multiple to CSV files via to_csv  DASK should use all the avilable cores 100% percent like modin.

**Comment by douglasdavis** [comment]
Hi @stromal, the speed that Dask executes a computation is dependent on many things. The first thing that comes to mind is the size of the dataset. If the dataset is not very large then it's unlikely you'll see speed ups from parallelized computation. This topic is more of a discussion (as opposed to an issue with dask itself), perhaps it should be moved to a post on Dask's discourse: https://dask.discourse.group

**Comment by jrbourbeau** [comment]
Closing due to lack of response. Feel free to reopen if you'd like to reengage
