### ISSUE TITLE
Python 3.11 support 

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9691]
Python 3.11 has been released 🎉 Historically it has taken some time for our dependencies to add support for new Python versions and for those changes to show up in releases. Opening this issue for tracking purposes 

cc @charlesbluca in case this is something you might be interested in

**Comment by charlesbluca** [comment]
Right now, the current blockers to solving a 3.11 environment are:

- `tiledb-py` constraint set in https://github.com/dask/dask/pull/9569
    - it suffices to set `tiledb-py!=0.17.5`, but not sure if we've tested CI with newer versions
- `numba` builds for 3.11 (migration being tracked in https://github.com/numba/numba/issues/8304)
- `numcodecs` builds for 3.11 (required by `zarr`, being tracked in https://github.com/zarr-developers/numcodecs/issues/377)
- `libprotobuf` pin set in https://github.com/dask/dask/pull/9465

**Comment by jakirkham** [comment]
These are optional right? Maybe they can be dropped from the Python 3.11 CI environment for now and added back later once they have Python 3.11 support

**Comment by jrbourbeau** [comment]
Thanks for the write up @charlesbluca! 

> These are optional right? Maybe they can be dropped from the Python 3.11 CI environment for now and added back later once they have Python 3.11 support

Yeah, that seems totally fine by me (and what we've done in the past). It looks like @graingert is taking that approach over in https://github.com/dask/dask/pull/9708

**Comment by jakirkham** [comment]
> * `numcodecs` builds for 3.11 (required by `zarr`, being tracked in [Release 0.11 with Python 3.11 support zarr-developers/numcodecs#377](https://github.com/zarr-developers/numcodecs/issues/377))

This should now be addressed.
