### ISSUE TITLE
Fail in cluster for load my lib

### ISSUE THREAD

**Issue by b-y-f** [dask/dask#9692]
**Describe the issue**:

I tried using LocalCluster to process my data, using the code below. I had **no problem** with the empty `Client()` object, but when I put the cluster in the client. I will get some errors.

The task for `do_prediction` is: 
1. use URL to read file in S3 and do feature engineering
2. use a pretrained model which is loaded from a pickle file to predict the data
3. upload prediction result to S3

The feature engineering part in `do_prediction` used some function in my utl.py

```
all_meter_lst = load('all_meter_lst.pkl')
for cks in chunks(all_meter_lst, 999):
    lazy_results = []
    for meter_url in cks:
        lazy_result = dask.delayed(do_prediction)(meter_url)
        lazy_results.append(lazy_result)
    dask.compute(*lazy_results)

# Not work!!!!!
# cluster = LocalCluster(n_workers=8, processes=True)
# client = Client(cluster)
# Work!!!!!
client = Client()
client
```

The error I got:
```
2022-11-25 03:09:13,886 - distributed.worker - ERROR - Could not deserialize task do_prediction-3a99f190-0611-4bc9-bc7f-1764cb6fe83b
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/lake/lib/python3.10/site-packages/distributed/worker.py", line 2219, in execute
    function, args, kwargs = await self._maybe_deserialize_task(ts)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/lake/lib/python3.10/site-packages/distributed/worker.py", line 2192, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*ts.run_spec)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/lake/lib/python3.10/site-packages/distributed/worker.py", line 2863, in _deserialize
    function = loads_function(function)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/lake/lib/python3.10/site-packages/distributed/worker.py", line 2857, in loads_function
    return pickle.loads(bytes_object)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/lake/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'utl'
```

- Dask version: latest
- Python version: 3.10
- Operating System: macos
- Install method (conda, pip, source):

**Comment by b-y-f** [comment]
Another problem is I cannot process list > 1000. So I have to chunk down the size to 999, when the list size > 1000. there is no reaction in dashboard.

**Comment by b-y-f** [comment]
I'm thinking that `utl` is not my module?

**Comment by b-y-f** [comment]
> I'm thinking that `utl` is not my module?

That is my utl..., I just copied all my code into the notebook and it works.

**Comment by phobson** [comment]
@b-y-f I'm trying to figure out what's going on here. I think this would be better discussed in out [Discourse Group](https://dask.discourse.group). But I am curious if you get better results defining your cluster and client *before* asking dask to do a computation. By that I mean:


```python

cluster = LocalCluster(n_workers=8, processes=True)
client = Client(cluster)
all_meter_lst = load('all_meter_lst.pkl')
for cks in chunks(all_meter_lst, 999):
    lazy_results = []
    for meter_url in cks:
        lazy_result = dask.delayed(do_prediction)(meter_url)
        lazy_results.append(lazy_result)
    dask.compute(*lazy_results)
```

You'd probably be better off with a `dask.bag` instead of using `chunks`

**Comment by b-y-f** [comment]
> I'm going to close this for now. @b-y-f, ping me on the Discourse channel when you have something going on there.

This method has a memory issue, when I run it with npartition=20, while having 40k tasks, it will always kill the workers.
