### ISSUE TITLE
pivot_table with aggfunc='min'?

### ISSUE THREAD

**Issue by sorenwacker** [dask/dask#9727]
### Discussed in https://github.com/dask/dask/discussions/9722

<div type='discussions-op-text'>

<sup>Originally posted by **sorenwacker** December  6, 2022</sup>
Hi,
I came across these post on [stackoverflow](https://stackoverflow.com/questions/57536782/how-to-do-pivot-table-in-dask-with-aggfunc-min), where someone asked, if it is possible to do a pivot_table with aggfunc = 'min'. That was in August 2019 and this feature has not yet found its way into the repository. I don't know if such a feature request was ever created, but I wonder why that feature was never implemented. Is there a techincal barrier that makes it particularily difficult to implement the minimum function for a pivot_table aggregation in dask? If someone know the details, I would be interested what these difficulties are. Maybe someone can point me to a resource to read, like a discussion, or documentation, if such things are discussed there in enough detail to understand the issue.</div>

**Comment by phobson** [comment]
xref: https://github.com/dask/dask/pull/9728
