### ISSUE TITLE
Mask preserving where e.g. da.ma.where

### ISSUE THREAD

**Issue by Holmgren825** [dask/dask#9759]
For certain applications, in for instance geo-sciences, a `np.ma.where` equivalent would be very useful, `da.where` does not preserve the mask of masked arrays.  I've looked into this a bit already and I can see two relatively simple ways to implement this. The first option is to follow `np.ma.where` and implement it as a series of `da.where` calls (see [numpy](https://github.com/numpy/numpy/blob/54c52f13713f3d21795926ca4dbb27e16fada171/numpy/ma/core.py#L7303-L7391)) on the data and mask separately and create a new masked array of the results. 

The other option is to follow the implementation of `da.where`,  but applying `np.ma.where` instead of `np.where`. This also requires a mask-aware `nonzero`, which is also fairly simple.

Currently I have a working branch of the of the second alternative. Would be happy to open a PR!

**Comment by jrbourbeau** [comment]
Thanks @Holmgren825
