### ISSUE TITLE
Turn Dependabot off on forks

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#9817]
It looks like Dependabot was added recently. However it is configured to update any repo, which means forks get these autoupdate PRs. Would it be possible to configure this to only update `dask/dask`?

**Comment by jrbourbeau** [comment]
Thanks for surfacing @jakirkham. Disabling on forks sounds reasonable to me. Do you have experience doing this in other projects? 

Out of curiosity, so do you have a link to a fork where a dependabot PR was opened? (the `main` branch for my `dask/dask` fork is very old and doesn't have the dependabot config file)

**Comment by j-bennet** [comment]
Hi @jakirkham ,

This was opened a while ago, and you might have resolved your problem already. But if not, according to [this response](https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1326137957) in `Dependabot`, they released an update on November 7, 2022 and by default, `Dependabot` is now disabled on forks.

If you go to your fork security analysis settings (`https://github.com/<your-username>/dask/settings/security_analysis`), you should be able to see `Dependabot` settings, and enable or disable it there.

I'm going to close the issue, but feel free to reopen if you still need help.

Thank you!
