### ISSUE TITLE
psutil and bokeh are not dependencies, raise ImportErrors when Profiler is used

### ISSUE THREAD

**Issue by ahmadia** [dask/dask#983]
I know there was an effort to pull out some of the dependencies in dask last year, and I just had an extended discussion with @jcrist about what is or isn't an optional dependency.

I'd strongly suggest that if dask is going to get wider adoption, that this be handled more gracefully.  I can think of three reasonable solutions here (feel free to add others if I missed something):

1] pull dask subcomponents out so that they get to remain lightweight, this makes the overall development process harder to coordinate but encourages more ownership as well of the individual pieces and has a slew of other pros/cons
2] bite the bullet and add bokeh/psutil/etc... back in as dependencies to the conda package.  I'm less concerned with folks who install dask from other sources, but the conda package should install everything a user who expects to interact with dask may need.
3] handle all import errors of optional dependencies more gracefully.  Possibly by adding a thin wrapper function around these imports that catches ImportErrors and explains to the user what package failed to import, then points them to a documentation page where optional dependencies are laid out.

**Comment by mrocklin** [comment]
Both 2 and 3 sound like good ideas to me

**Comment by jcrist** [comment]
I'm also fine with either 2 or 3, leaning slightly towards 3. My main concern with 2 is for packages that depend on dask, but might not want all of the dependencies. Dependencies are cheaper to use with conda, but people might still be reluctant to make something like bokeh a dependency of skimage.

**Comment by mrocklin** [comment]
I'm comfortable stacking lots of dependencies within the conda recipe.  We already add a bunch of things there.  Developers I've spoken to about this topic have been comfortable with a lot of dependencies within the conda recipe as long as the pip requirements is sparse.

**Comment by jcrist** [comment]
Here are the (not test-only) things we install on travis that aren't in the conda recipe:

```
scipy - used for da.linalg stuff
pytables - can load from pytables
h5py - can load from h5py
bcolz - can load from bcolz
scikit-learn - da.learn package
dill - for dask.bag
psutil - for profilers
bokeh - for profile plots
graphviz - for graph diagrams, no conda package though :/
```

Of these, `dill`, `psutil`, `scipy`, and `bokeh` are probably the only ones worth making dependencies. `graphviz` would be too, but it's only on pypi right now. Thoughts?

**Comment by mrocklin** [comment]
I'll nix the graphviz dependency.  There is a conda package, but it is broken on OSX.

I'm fine adding all of the others.  Wouldn't mind not including scipy.

**Comment by jcrist** [comment]
Not including scipy also sounds reasonable. I'll also add in nice descriptive errors for the non-installed packages. Would this satisfy your concerns @ahmadia?

**Comment by eriknw** [comment]
Just to clarify, the `graphviz` package in conda contains the command-line tools (`dot`, `circo`, etc).  This is different from the `graphviz` package on pypi, which is one of many Python bindings to graphviz.

It should be very easy to add https://pypi.python.org/pypi/graphviz to conda, which would use the system's graphviz library if not explicitly installed via conda.

**Comment by jcrist** [comment]
Actually, we could just install from the `pypi` channel, it's on there under `graphviz`. If we were to build it in a different channel, I'm not sure what we'd name it. `graphviz` is taken, as is `pygraphviz` (and my favorite `AnotherPyGraphvizAgain`).

**Comment by ahmadia** [comment]
That works, although I think you need both the Python bindings to graphviz as well as graphviz actual, since it isn't installed by default on many systems.

**Comment by mrocklin** [comment]
As a reminder, the conda graphviz package is broken in a decently common case.  I don't think we should depend upon it.  https://github.com/ContinuumIO/anaconda-issues/issues/485

**Comment by mrocklin** [comment]
Oh, we should rewrite the single dill test to use cloudpickle instead and not depend on it.
