### ISSUE TITLE
Can dask.dataframe.from_array take a pandas series?

### ISSUE THREAD

**Issue by fdosani** [dask/dask#9830]
**Describe the issue**:

I noticed this starting with version `2022.12.1`, before this I was not getting this error. I'm not sure if this is an actual bug or maybe this is by design so feel free to close out the issue and ignore me if this is true :)

Before version `2022.12.1` I am able to pass a `pandas.core.series.Series` to `dd.from_array` for the `x` parameter without any issue. Starting with version `2022.12.1` I'm getting a `TypeError`: 

```
TypeError: No dispatch for <class 'pandas.core.series.Series'>
```

Thanks again for the help and great package!

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

a = np.linspace(-4, 4, 10)
a = np.array(a, dtype=np.float32)
b =  pd.Series(a)
dd.from_array(b)
```

**Anything else we need to know?**:

Using Dask 2022.12.0 runs successfully:

```
In [1]: import numpy as np
   ...: import pandas as pd
   ...: import dask.dataframe as dd
   ...:
   ...: a = np.linspace(-4, 4, 10)
   ...: a = np.array(a, dtype=np.float32)
   ...: b =  pd.Series(a)
   ...: dd.from_array(b)
Out[1]:
Dask Series Structure:
npartitions=1
0    float32
9        ...
dtype: float32
Dask Name: from_array, 1 graph layer

In [2]: from dask import __version__

In [3]: __version__
Out[3]: '2022.12.0'
``` 

**Environment**:

- Dask version: 2022.12.1
- Python version: 3.9.13
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for the clear report and example snippet @fdosani! I'm able to reproduce

> I'm not sure if this is an actual bug or maybe this is by design

I think your inclination here is correct that this isn't a bug. The fact that this worked previously was just a happy accident. Instead of `dd.from_array` I'd recommend using `dd.from_pandas` instead. That's the fully supported way of creating a Dask Series/DataFrame from a pandas Series/DataFrame

**Comment by fdosani** [comment]
Thanks @jrbourbeau what I suspected! Thank again for the quick response.
