### ISSUE TITLE
DataFrame.mask fails for single-row partitions

### ISSUE THREAD

**Issue by albarji** [dask/dask#9848]
**Describe the issue**: 

When creating a Dask DataFrame with partitions containing a single row, the `mask` method incorrectly computes shapes and raises a `ValueError: Array conditional must be same shape as self`

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = dd.from_pandas(pd.DataFrame({"column": [1, 2]}), npartitions=2)
df.mask(cond=[[True], [False]], other=5).compute()
```

**Anything else we need to know?**: 

The same MCVE succeeds when:
* Creating a DataFrame with 4 or more rows, or using `npartitions=1`, so that no partition contains just 1 row.
* Using a previous dask version (tested with `2022.6.1`).

**Environment**:

- Dask version: `2022.11.1` and `2023.1.0` (both fail)
- Python version: 3.9.16
- Operating System: Ubuntu WSL 4.4.0-19041-Microsoft
- Install method (conda, pip, source): pip

**Comment by phobson** [comment]
Thanks for the clear report, @albarji. This indeed seems like a bug. We'll take a look.

**Comment by quasiben** [comment]
To unblock you now you could probably use a Series instead of a list?

```python
In [15]: df.mask(cond=pd.Series([True, False]), other=5).compute()
Out[15]:
   column
0       5
1       2
```

**Comment by albarji** [comment]
@phobson thanks for the fast answer!

Also @quasiben thanks for your suggestion. I tried it out and using a Series indeed works for that example, but I also realized that for a general DataFrame one must be careful to align its indices with those in the Series. For example,

```python
df = dd.from_pandas(pd.DataFrame({"column": [1, 2]}, index=[1, 2]), npartitions=2)
df.mask(cond=pd.Series([True, False]), other=5).compute()
```
produces the wrong result

```python
   column
1       1
2       5
```

because the masking seems to be performed after aligning the indices of DataFrame and Series, not just by aligning their rows.

So, the solution seems to be creating the Series with the same indices as the DataFrame being masked

```python
df = dd.from_pandas(pd.DataFrame({"column": [1, 2]}, index=[1, 2]), npartitions=2)
df.mask(cond=pd.Series([True, False], index=df.index), other=5).compute()
```

**Comment by albarji** [comment]
Also, to provide another reproducible example: the same bug arises when masking across several columns.

```python
import dask.dataframe as dd
import pandas as pd

df = dd.from_pandas(pd.DataFrame({"columnA": [1, 2], "columnB": [3, 4]}), npartitions=2)
cond = [[True, True], [False, True]]
df.mask(cond=cond, other=5).compute()
```

a `ValueError: Array conditional must be same shape as self` is raised.

Again, the error disappears when adding more data rows or setting `npartitions=1` , so that no partition has just a single row.

**Comment by albarji** [comment]
In case somebody else is struggling with this: a workaround based on @quasiben 's idea that also works for several columns and arbitrarily indexed dataframes goes as follows:

```python
import dask.dataframe as dd
import pandas as pd

# Inputs
df = dd.from_pandas(pd.DataFrame({"column": [1, 2]}), npartitions=2)
cond = [[True], [False]]   # Also works for cond = [[True, True], [False, True]]

# Cast the masking list to a DataFrame with index and columns as df
cond = pd.DataFrame(data=cond, index=df.index, columns=df.columns)

# Now the masking behaves as expected
df.mask(cond=cond, other=5).compute()
```

**Comment by jorloplaz** [comment]
To clarify the discussion:

>  I tried it out and using a Series indeed works for that example, but I also realized that for a general DataFrame one must be careful to align its indices with those in the Series.

**This doesn't happen in Pandas, so Dask seems to be introducing the index-alignment issue**. 

Using the same MCVE's `Series` and `Dataframe` in pure Pandas we have:

```python
# Index different from range [0, ..., N-1]
df = pd.DataFrame({"column": [1, 2]}, index=[1, 2])                 
df
   column
1       1
2       2
# Calling mask with something that has the same index as df
df.mask(df <= 1, other=5) 
   column
1       5
2       2
# Calling mask with matrix-like (no index associated)
df.mask(cond=[[True], [False]], other=5) 
   column
1       5
2       2
# Try with series that still indexes with [1, 2] instead of [0, 1]
s = df['column']
s
1    1
2    2
Name: column, dtype: int64
# Expected result using same-index series
s.mask(s <= 1, other=5)        
1    5
2    2
Name: column, dtype: int64
# Also with array-like
s.mask([True, False], other=5)
1    5
2    2
Name: column, dtype: int64
```

**Comment by j-bennet** [comment]
Closed via https://github.com/dask/dask/pull/10163.
