### ISSUE TITLE
Read_csv not working as expected

### ISSUE THREAD

**Issue by andyjessen** [dask/dask#9891]
**Describe the issue**:
Installed dask[complete] in virtual environment. Attempt to import csv with read_csv.  Receive "Module Not Found" exception. Believe there is a problem with dependency in fsspec. 

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd
titanic_df = dd.read_csv(
    "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
```

**Anything else we need to know?**:
File ...Python\filesystem_spec\fsspec\implementations\http.py:11
      [9](file:///.../Python/filesystem_spec/fsspec/implementations/http.py?line=8) from urllib.parse import urlparse
---> [11](file:///.../Python/filesystem_spec/fsspec/implementations/http.py?line=10) import aiohttp
     [12](file:///.../Python/filesystem_spec/fsspec/implementations/http.py?line=11) import requests

ModuleNotFoundError: No module named 'aiohttp'
**Environment**:

- Dask version: 2023.1.1
- Python version: 3.8
- Operating System: Windows
- Install method (conda, pip, source): Pip

**Comment by douglasdavis** [comment]
While Dask depends on `fsspec`, there are optional dependencies within `fsspec` that dask doesn't necessarily depend on. To use `http://` URIs with `fsspec` you'll want to install `pip install fsspec[http]`. This will install `requests` and `aiohttp`: https://github.com/fsspec/filesystem_spec/blob/012816bb142de1e507423b81dc3b2c925d4424c3/setup.py#L53

It may be useful to open an issue at the `fsspec` repo to suggest a more descriptive error message

**Comment by andyjessen** [comment]
Thanks. That resolved the issue.
