### ISSUE TITLE
`sqlalchemy` 2.0 compatibility

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9896]
`sqlalchemy` 2.0 was recently released and is causing tests to fail. We should temporarily pin `sqlalchemy<2` in CI as a temporary workaround. 

EDIT: https://github.com/dask/dask/pull/9897 adds the `<2` pin to CI

**Comment by crusaderky** [comment]
https://github.com/coiled/coiled-runtime/pull/675 pins it in coiled-runtime too
