### ISSUE TITLE
Dask DataFrame to_parquet drops null values in the partition_on column

### ISSUE THREAD

**Issue by randerzander** [dask/dask#9911]
Attempting to partition a Parquet dataset on a column containing null values will result in dropping data for the null valued partition column:
```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"id": [0, 1, None]})
ddf = dd.from_pandas(df, npartitions=1)
ddf.to_parquet("test", partition_on="id")

ddf = dd.read_parquet("test")
ddf.compute()
    id
0  0.0
1  1.0
```

**Comment by rjzamora** [comment]
This is related to an existing issue for the read side: https://github.com/dask/dask/issues/9435
