### ISSUE TITLE
Do not force repartition of dataframes that are already aligned in align_partitions

### ISSUE THREAD

**Issue by epizut** [dask/dask#9922]
Hi,

Following [why align_partitions() use force=True?](https://dask.discourse.group/t/why-align-partitions-use-force-true/1528) on discourse:

When passing severals dask dataframes to `map_partitions()`, it looks like the underling align_partitions() force repartitioning every dd even if only a single one needs it.

This generates non-necessary graph nodes that slow down packing/sending/unpacking/schedule stages.

```python
dds = [dask.datasets.timeseries() for i in range(5)]
# Only the latest dd partitionning will differ
dds[-1] = dds[-1].repartition(npartitions=1)

def func(*args):
    return args[0]

dd = dask.dataframe.map_partitions(func, *dds)
dd.dask
```
![image](https://global.discourse-cdn.com/standard17/uploads/dask/original/1X/45559be45bb767f86905e87ee85cffa904a8deab.png)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @epizut. I agree it looks like we're just using the first `DataFrame`s divisions and then repartitioning all the other `DataFrame`s here:

https://github.com/dask/dask/blob/2a2b9d3cb503c052fd65e5693575498df1f9cd23/dask/dataframe/multi.py#L172-L175

I suspect we could update this logic to look for the divisions that are shared among the largest number of `DataFrame`s and then just repartition the ones that don't currently match that partitioning. 

Is this something you're interested in looking into? (no obligation though)

**Comment by epizut** [comment]
I better always align on the first dd. If we simply set `force=False`, it will minimize the impact of this change. Otherwise current users may report unexpected performance issues.

I think a common use case is to use `map_partitions` on a single huge dd with lots of partitions and then add a few smaller contextual dds with none or very few divisions. Using a dynamic divisons selection based on the most used divisions layout will certainly reduce the graph size, but it may confuse users and be more difficult to document.

**Comment by epizut** [comment]
To me, #9924 solves my issue. 
I mentioned `force` in the title, but it was not related to the `force` parameter of `repartition()`.

Did you see any secondary problem that needs to be addressed?

**Comment by jrbourbeau** [comment]
That sounds good to me. Thanks @epizut
