### ISSUE TITLE
Possible Bug in the config Conversion Utility

### ISSUE THREAD

**Issue by jbusecke** [dask/dask#9929]
**Describe the issue**:
I find the [Conversion Tool](https://docs.dask.org/en/latest/configuration.html#conversion-utility) extremely useful. But I just noticed a possible bug with it. 

**Minimal Complete Verifiable Example**:
When I paste this yaml:
```yaml
distributed:
  deploy:
    lost-worker-timeout: 15s
    cluster-repr-interval: 500ms
```

I am getting the following env variables

```
export DASK_DISTRIBUTED__DEPLOY__LOST_WORKER-TIMEOUT="15s"
export DASK_DISTRIBUTED__DEPLOY__CLUSTER_REPR-INTERVAL="500ms"
```

Is the second `-` suposed to be converted to an underscore?

like such?

```
export DASK_DISTRIBUTED__DEPLOY__LOST_WORKER_TIMEOUT="15s"
export DASK_DISTRIBUTED__DEPLOY__CLUSTER_REPR_INTERVAL="500ms"
```

I quickly tried this by setting up a dask-gateway cluster with:

```python
from dask_gateway import Gateway
gateway = Gateway()
options = gateway.cluster_options()

options.environment = dict(
    DASK_DISTRIBUTED__DEPLOY__LOST_WORKER_TIMEOUT="11s", #this would fail with the `-` version
)

# Create a cluster with those options
cluster = gateway.new_cluster(options)
client = cluster.get_client()
cluster.scale(2)

def check_config():
    import dask
    return dask.config.get('distributed.deploy')

client.wait_for_workers(2)
client.run(check_config)
```

And this seems to work. I got

```
{'tls://10.1.158.2:37055': {'lost_worker_timeout': '11s',
  'cluster-repr-interval': '500ms'},
 'tls://10.1.158.4:45179': {'lost_worker_timeout': '11s',
  'cluster-repr-interval': '500ms'}}
```

Just figured I'd mention it in case this is an actual bug.

**Comment by jrbourbeau** [comment]
Thanks for the issue @jbusecke. You're correct, I think we want environment variables to use all underscores. cc @jacobtomlinson
