### ISSUE TITLE
Documentation of dask.array.map_blocks() needs to be fixed?

### ISSUE THREAD

**Issue by flyhamsw** [dask/dask#9938]
**Describe the issue**:

I used map_blocks() with a simple custom function as described in the official document, but it didn't work.

The error message was:
```
TypeError: my_func() takes 0 positional arguments but 1 was given
```

I added one more positional argument to my custom function, and it did work. It seems that dask puts input chunk to my custom function as a positional argument.

My understanding of the official document was when I use my custom function I don't need to care about positional argument, but I think it isn't. I suggest that we need to fix the official document to describe this issue. As a newbie of Dask, it was quite confusing to me.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da

my_darr = da.zeros((5, 5))

# IT RAISES TypeError
def my_func():
    return 0

my_darr = my_darr.map_blocks(my_func, dtype=np.uint8)

my_darr.compute()

# IT WORKS WELL
def my_func(input_array):
    return 0

my_darr = my_darr.map_blocks(my_func, dtype=np.uint8)

my_darr.compute()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.1.1
- Python version: 3.9
- Operating System: macOS
- Install method (conda, pip, source): Conda

**Comment by j-bennet** [comment]
Hi @flyhamsw,

In general, mapping a collection to a function means running this function over every element in the collection. So it would make sense that the function needs to accept a block of dask array. We can make it more explicit in the documentation.

**Comment by flyhamsw** [comment]
@j-bennet Thank you!
