### ISSUE TITLE
New graph on which the scheduler performs poorly

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#994]
In https://github.com/pydata/xarray/issues/729 we found a real-world problem that contained a graph that dask should have been able to compute easily (I think), but didn't.

The resulting graph is here: [dask.pdf](https://github.com/pydata/xarray/files/131262/dask.pdf)

The graph as a cloudpickled file is here: [dask.pkl.txt](https://github.com/dask/dask/files/131295/dask.pkl.txt)

I have a zip file with a dataset and script to reproduce this graph.

Some steps:
1.  Take a hard look at this graph to verify that yes, it indeed should be executing in small space.
2.  Visualize the result of `dask.ordering.order` on such a graph to ensure that we intend to walk through this graph cleanly.  Perhaps do a tiny bit of simulation to improve on the accuracy beyond just the ordering produced by `order`
3.  Perhaps benchmark ghost computations, which can be easily reproduced and look somewhat similar, to ensure that they walk through a graph somewhat cleanly.
4.  ...

**Comment by shoyer** [comment]
@mrocklin could you kindly share your script for working on this?

**Comment by mrocklin** [comment]
This came from the 800 MB zip file found in the referred to xarray issue.  It may still be up if you move quickly.

**Comment by shoyer** [comment]
Oops -- I didn't check on the full contents of that zip. Here's the contents of that script:
```python
# -*- coding: utf-8 -*-

import os
import numpy as np
import time
import xray
import dask



def spatialise(flux,symb,var) :
    Rn= np.intersect1d(symb.NIsoSource.values, flux.NIsoSource.values)

    flux =  flux.sel(NIsoSource = Rn).chunk({'DimI0': 20,'DimJ0': 20, 'NIsoSource':10, "Paliers" : 5})
    symb = symb.sel(NIsoSource = flux.NIsoSource.values).chunk({'time': 50,'NIsoSource':10, "Paliers" : 5})
    
    M = interp(symb[var],flux.Rain)
    res = (flux.Flux_Moyen_Depot_Sec * symb[var].sel(Hpluie = 0) + flux.Flux_Moyen_Depot_Humide *M).sum('Paliers')

    symb.close()
    return res.chunk({'DimI0': 20,'DimJ0': 20, 'NIsoSource':10, "time" : 50})


def interp(array,pluie):
    p0 = (array.sel(Hpluie = 5) -array.sel(Hpluie = 0))/5
    p1 = (array.sel(Hpluie = 10) -array.sel(Hpluie = 5))/5
    p2 = (array.sel(Hpluie = 15) -array.sel(Hpluie = 10))/5
    
    interp = (p0*(pluie.where(pluie<5) - array.Hpluie.sel(Hpluie=5)) +array.sel(Hpluie=5)).fillna(0)\
        +(p1*(pluie.where((pluie>=5) & (pluie<=10)) - array.Hpluie.sel(Hpluie=5)) +array.sel(Hpluie=5)).fillna(0)\
        +(p2*(pluie.where(pluie>10) - array.Hpluie.sel(Hpluie=10)) + array.sel(Hpluie=10)).fillna(0)   
    return interp

# Fonction de lancement de la spatialisation
def run():
    dask.set_options(get=dask.async.get_sync)
    nc = xray.open_dataset(os.path.join('FLUX_AND_RAIN.nc'))
    symb =  xray.open_dataset(os.path.join('SYMB.nc'))
    d = time.time()
    res =spatialise(nc,symb, 'FoodDose')
    d = time.time()
    '''nc.close()
    symb.close()'''
    return res

if __name__ == '__main__':
    res =run()
    print 'Ecriture du fichier resultat'
    res.to_dataset().to_netcdf('RES.nc',format = 'NETCDF4',engine ='netcdf4')
    
```

**Comment by mrocklin** [comment]
Graph ordering logic has changed a bi since this was reported.  Closing.
