### ISSUE TITLE
New engine keyword for read_json in pandas

### ISSUE THREAD

**Issue by phofl** [dask/dask#9943]
Hi,

we (pandas) added a new ``engine`` keyword to pd.read_json (https://pandas.pydata.org/docs/dev/reference/api/pandas.read_json.html) today to switch to https://arrow.apache.org/docs/python/generated/pyarrow.json.read_json.html instead of the pandas implementation. Since the read_json function from Dask has its own keyword, the Dask function needs a different name for the option I guess? Is there a standard naming pattern for such conflicts?

cc @jrbourbeau

**Comment by jrbourbeau** [comment]
> Is there a standard naming pattern for such conflicts?

In general, no. We just make a best effort try. 

It looks like the dask-specific `engine=` kwarg was added in https://github.com/dask/dask/pull/4810 to better support `read_json` on GPUs. @rjzamora do you think we could actually deprecate passing `engine=cudf.read_json` in favor of the recent dataframe backend dispatching work?

**Comment by rjzamora** [comment]
Yes, we can probably tweak the engine to take a string or callable in dask

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/9947
