### ISSUE TITLE
API for filtering dataframes by partition

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#9951]
I just came across a need for a way to filter a Dask DataFrame based on some partition-level characteristics. In this case it was a Dask Geopandas dataframe and I was checking whether the partition's spatial footprint overlaps with some shape (dask-geopandas adds a `spatial_extent` attribute to each Dask GeoDataFrame). In general, this feature would be helpful whenever you have a boolean mask *on the partitions*.

The solution was to use a mixture of `dd.concat` and `dd.get_partition`

Here's a simple example:

```python
>>> import dask.dataframe as dd
>>> df = dask.dataframe.demo.make_timeseries()
>>> mask = df.id.map_partitions(lambda p: len(p.unique()) > 260).compute()
>>> keep = dd.concat([df.get_partition(i) for i, m in enumerate(mask) if m])
>>> keep
Dask DataFrame Structure:
                 name     id        x        y
npartitions=6                                 
               object  int64  float64  float64
                  ...    ...      ...      ...
...               ...    ...      ...      ...
                  ...    ...      ...      ...
                  ...    ...      ...      ...
Dask Name: concat, 8 graph layers
```

(Note that that has 6 partitions, instead of the normal 11).

It's not too difficult of a workaround, but I think a moderate expansion API would be acceptable. It doesn't quite fit `get_partition`, since it's getting multiple partitions. Perhaps a `.filter_partitions` that takes a boolean sequence the same length as the number of partitions? Or a callable that's provided each partition and should return a boolean?

I think this will become especially useful after https://github.com/dask/dask/pull/9473, since users will have more partition-level properties to filter on *without* a compute (cc @rjzamora).

**Comment by mrocklin** [comment]
Don't forget the partitions indexer

**Comment by jrbourbeau** [comment]
@TomAugspurger thoughts on using the existing `df.partitions` indexer? 

```python
In [1]: import dask.dataframe

In [2]: df = dask.dataframe.demo.make_timeseries()

In [3]: mask = df.id.map_partitions(lambda p: len(p.unique()) > 260).compute()

In [4]: df.npartitions
Out[4]: 11

In [5]: mask
Out[5]:
0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10     True
dtype: bool

In [6]: df.partitions[mask]
Out[6]:
Dask DataFrame Structure:
                  name     id        x        y
npartitions=10
2000-01-31      object  int64  float64  float64
2000-02-29         ...    ...      ...      ...
...                ...    ...      ...      ...
2000-11-30         ...    ...      ...      ...
2000-12-31         ...    ...      ...      ...
Dask Name: blocks, 2 graph layers
```

**Comment by TomAugspurger** [comment]
I had forgotten about `.partitions`. I opened https://github.com/dask/dask/pull/9976 to help me next time I forget.
