### ISSUE TITLE
dd.to_hdf tries to write with multiple processes (errno 11, unable to lock file )

### ISSUE THREAD

**Issue by MarcoPasta** [dask/dask#9972]
Hi, 
so i am reading a big h5 File with 600+ keys. Reading and processing work fine and if called with `.compute()` everything runs fine, however when i run `.to_hdf()` my pipeline fails due to multiple processes writing to the file. I've set a lock to either/both read_hdf and to_hdf but the same error kept occuring. 

**Minimal Complete Verifiable Example**:

```python
def load_file(file, f_lock):
    df = dd.read_hdf(file, key="/*", mode="r" , lock=f_lock)
    return df

def process_file(df, config, partition_info=True):
    partition = partition_info['number']
    print("Partition: ", partition)
    pipeline, metadata, detector = ConversionPipeline.pipeline_from_config_dict(config)
    df = pipeline.process(df, detector, metadata)
    print(f"Validation of Partition: {partition}\n{df[:10]}")
    return df


if __name__ == "__main__":
    with LocalCluster(
        n_workers=48, 
        threads_per_worker=2,
        dashboard_address="127.0.0.1:8787"
        ) as cluster, Client(cluster) as client: 
        # lock = Lock()
        # ....
        if file.endswith("h5"):
                # df = load_file(file, lock)
                df = dd.read_hdf(file, key="/*", mode="r" , lock=True)
                print("Filename: ", filename)
                df = df.map_partitions(process_file, file, config, meta=meta_df)
                df.to_hdf(filename, key='/spot_*', lock=True)
                # df.to_hdf(filename, key='/spot_*', lock=lock)
                print("Conversion has ended! :)")
```
The error log looks something like this
```bash
2023-02-16 23:36:27,373 - distributed.worker - WARNING - Compute Failed
Key:       ('to-hdf-563928c0ae4911ed90f5fbcbaa91114d', 539)
Function:  execute_task
args:      ((<function _link at 0x7fbd117a2d30>, None, (<function _pd_to_hdf at 0x7fbd117abb80>, <function NDFrame.to_hdf at 0x7fbd15e9e4c0>, <SerializableLock: 4dcf9e98-bdd9-486b-88f5-73ab0c5ae630>, [        
... contents of the DF ...
kwargs:    {}
Exception: 'HDF5ExtError("Unable to open/create file \'/home/user/Development/testdata/h5/testfile_out.h5\'")'
...
...
File "H5F.c", line 620, in H5Fopen
    unable to open file
  File "H5VLcallback.c", line 3501, in H5VL_file_open
    failed to iterate over available VOL connector plugins
  File "H5PLpath.c", line 578, in H5PL__path_table_iterate
    can't iterate over plugins in plugin path '(null)'
  File "H5PLpath.c", line 620, in H5PL__path_table_iterate_process_path
    can't open directory: /usr/local/hdf5/lib/plugin
  File "H5VLcallback.c", line 3351, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 97, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 1898, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1625, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 1002, in H5FD__sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/user/Development/testdata/h5/testfile_out.h5'
2023-02-16 23:36:34,125 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1944409 exit status was already read will report exitcode 255
2023-02-16 23:36:35,766 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1944417 exit status was already read will report exitcode 255
```

**Anything else we need to know?**:
Running normally:
<img width="1320" alt="Screenshot 2023-02-16 at 23 34 13" src="https://user-images.githubusercontent.com/63001199/219503406-03aa00a8-f01f-453a-b4cc-e61c02116fa6.png">

When failing:
<img width="922" alt="Screenshot 2023-02-16 at 23 36 55" src="https://user-images.githubusercontent.com/63001199/219503456-3b118662-556f-410f-a81c-a5497024622f.png">

Graph might look odd because i forgot to reload

**Environment**:

- Dask version: dask, version 2023.1.1
- Python version: 3.8.14
- Operating System: Ubuntu 20.4.4 LTS
- Install method (conda, pip, source): pip `dask["complete"]`

**Comment by j-bennet** [comment]
Hi @MarcoPasta, sorry it took so long to get a response. Dask is delegating writing hdf to pandas, which is using `HDFStore` from pytables, which is [not tread-safe](https://github.com/pandas-dev/pandas/issues/2397). When you create a `LocalCluster`, it will run workers in separate processes, unless you tell it otherwise. It looks like currently, even though you're applying locks when writing (I don't think locks are needed when reading), locks only work within the same process (worker), and workers may still step on one another.

You can call `df.to_hdf(filename, key='/spot_*', lock=True, scheduler="threads")`, or create a `LocalCluster(processes=False)` to work around the error.

cc @hendrikmakait, you may be able to give a better answer.

**Comment by j-bennet** [comment]
Closing via https://github.com/dask/dask/pull/10309.
