### ISSUE TITLE
Make `dataframe.convert_string` efficient for `dd.read_parquet`

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9978]
With https://github.com/dask/dask/pull/9926 we can now automatically have text data cast to use `pyarrow` strings when the `dataframe.convert_string` config option is set to `True`. We're currently accomplishing this via a simple `map_partitions` call that gets automatically added and casts to `pyarrow` strings. 

This is nice because it works for the full `dask.dataframe` API. However, some methods like `dd.read_parquet` should be able to read from source directly into `pyarrow` strings (when `dataframe.convert_string` is turned on). For the `pyarrow` parquet engine we should be able to make use of the `types_mapper=` keyword for `pa.Table.to_pandas(...)` here

https://github.com/dask/dask/blob/a0f0838c008467f1d696aaab9f15355faf035f4f/dask/dataframe/io/parquet/arrow.py#L1636-L1670

to handle automatically reading data into `string[pyarrow]` in `pandas`. 

For the `fastparquet` engine, we should raise an informative error to users. 

cc @j-bennet @rjzamora for visibility 

xref https://github.com/dask/dask/issues/9946

**Comment by j-bennet** [comment]
Closed via https://github.com/dask/dask/pull/9979.
