### ISSUE TITLE
join works in Pandas but fails in Dask

### ISSUE THREAD

**Issue by twrightsman** [dask/dask#9993]
**Describe the issue**:

I'm trying to join two larger-than-memory dataframes in Dask but get an error regarding mismatched columns. However, the same join operation works in Pandas on a smaller subset.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

data_fake_pd = pd.DataFrame(data = {'group': ['a', 'b', 'a', 'b', 'b'], 'value': [1.5, 0.2, 0.8, 0.01, 0.4]})
passed_pd = data_fake_pd.groupby('group').apply(lambda subdata: ((subdata['value'] < 0.5).sum() / len(subdata)) > 0.5).rename('passed')
joined_pd = data_fake_pd.join(passed_pd, on = 'group')

data_fake_dd = dd.from_pandas(data_fake_pd, npartitions = 2)
passed_dd = data_fake_dd.groupby('group').apply(lambda subdata: ((subdata['value'] < 0.5).sum() / len(subdata)) > 0.5, meta = pd.Series(name = 'value', dtype = bool)).rename('passed')
joined_dd = data_fake_dd.join(passed_dd, on = 'group', how = 'inner')
joined_dd.compute()
```

**Anything else we need to know?**:

Traceback:

```
  File "/home/twrightsman/.conda/envs/dask-env/lib/python3.10/site-packages/dask/dataframe/utils.py", line 429, in check_matching_columns
    raise ValueError(
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   ['group']
  Missing: [0]
```

`joined_dd` gives the expected correct meta, but fails to do the actual computation:

```
>>> joined_pd
  group  value  passed
0     a   1.50   False
1     b   0.20    True
2     a   0.80   False
3     b   0.01    True
4     b   0.40    True
>>> joined_dd
Dask DataFrame Structure:
                group    value passed
npartitions=2                        
               object  float64   bool
                  ...      ...    ...
                  ...      ...    ...
Dask Name: merge_chunk, 16 graph layers
```

Computing both join operands before joining works as expected.

```
>>> data_fake_dd.compute().join(passed_dd.compute(), on = 'group', how = 'inner')
  group  value  passed
0     a   1.50   False
2     a   0.80   False
1     b   0.20    True
3     b   0.01    True
4     b   0.40    True
```

**Environment**:

- Dask version: 2023.2.0
- Python version: 3.10.8
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by j-bennet** [comment]
Thank you for your report @twrightsman. It looks like the error stems from the fact that the shape of the `meta` that you're providing when creating `passed_dd` is not completely correct. This will work:

```python
# use your pandas groupby-apply result as meta
meta = data_fake_pd.groupby('group').apply(lambda subdata: ((subdata['value'] < 0.5).sum() / len(subdata)) > 0.5)
passed_dd = data_fake_dd.groupby('group').apply(lambda subdata: ((subdata['value'] < 0.5).sum() / len(subdata)) > 0.5, meta=meta).rename('passed')
```

This will also work:

```
passed_dd = data_fake_dd.groupby('group').apply(lambda subdata: ((subdata['value'] < 0.5).sum() / len(subdata)) > 0.5, meta=pd.Series([], dtype=bool, index=pd.Index([], name='group'))).rename('passed')
```

If you take a close look at the `meta` above, you'll see that it has an `Index` named `group`. This part is missing in your meta, and that throws things off. This is where the mismatch comes from; the error is unfortunately not very clear.

Pandas, of course, doesn't need `meta` and doesn't have a similar problem.

I hope this helps. Please let us know if you're still having problems.

**Comment by twrightsman** [comment]
Thank you for the follow-up @j-bennet! Yes, that error isn't totally clear since it refers to a missing 'column'. My understanding is that Pandas doesn't typically group the Index with the other data columns conceptually, but maybe Dask does?

If possible, it would be very helpful for Dask to be more explicit that the mismatched index is what is causing the issue.

And thank you for the solutions, they worked flawlessly on my larger datasets :smile:

**Comment by j-bennet** [comment]
Thanks for the update @twrightsman; closing the issue as resolved.
