### ISSUE TITLE
`dask.order` over-prioritizes root tasks in some situations

### ISSUE THREAD

**Issue by gjoseph92** [dask/dask#9995]
In `test_anom_mean`—an example of a basic climatology workload that kicked off [long discussion](https://github.com/dask/distributed/issues/2602) about memory overproduction—it seems that an underlying problem might actually be with how `dask.order` prioritizes the graph.

Compare how the scheduler traverses the graph with  _queuing off and co-assignment off_ (i.e. scheduler behavior when the issue was first reported, prior to https://github.com/dask/distributed/pull/4967 and https://github.com/dask/distributed/pull/6614), versus with _queuing on as normal_:

![diagram](https://user-images.githubusercontent.com/3309802/221068199-83b5d249-374b-4420-84a8-3c9d8b665253.png)

<details><summary>Videos of the graphs executing</summary>

### Queuing on as normal:

https://user-images.githubusercontent.com/3309802/221064109-4d00faf2-ae90-4016-80c4-378229b12387.mp4

### Queuing off and co-assignment off:

https://user-images.githubusercontent.com/3309802/221064132-081ed099-cb05-4017-885a-b2f7948b9afd.mp4

---

</details>

Basically, the graph is prioritized such that the lowest-priority data loading task is still higher priority than nearly all of the data-consuming tasks.

Here's a mini version of the graph, with priorities:

![anom-mean-order-small](https://user-images.githubusercontent.com/3309802/221068914-19d5fb4e-a4bb-4849-aab6-74049b87d211.png)

<details><summary>Code to reproduce</summary>

```python
import dask.array as da
import numpy as np
import xarray as xr
from dask.utils import parse_bytes

data = da.random.random(
    (26, 1310720),
    chunks=(1, parse_bytes("10MiB") // 8),
)

ngroups = data.shape[0] // 4
arr = xr.DataArray(
    data,
    dims=["time", "x"],
    coords={"day": ("time", np.arange(data.shape[0]) % ngroups)},
)

clim = arr.groupby("day").mean(dim="time")
anom = arr.groupby("day") - clim
anom_mean = anom.mean(dim="time")

anom_mean.data.visualize(
    "anom-mean-order.png", color="order", optimize_graph=True, collapse_outputs=True
)
```

</details>

The last data-loading task is priority 106 (lower-left, second circle up). Looking at the data-reducing tasks, I only count 7 / 26 of them as being < 106. So if we follow graph order exactly, ~75% of the initial data will stay in memory.

So before queueing, workers had both root tasks and reduction tasks assigned. They could have run the reduction tasks—all the dependencies were in memory—they just chose not to, because they were lower priority.

<details><summary>To prove this, here are the tasks & priorities assigned to a worker with queuing off:</summary>

https://user-images.githubusercontent.com/3309802/221070444-1e8f7f71-43f8-444e-a21f-7ab3e27a1dfd.mp4

</details>

Queuing effectively added a new graph-prioritization mechanism saying "I don't care what your `dask.order` priority is, if you look like a root task, you always run last". It seems that for `test_anom_mean`, this re-prioritization of the graph might have been the main thing that solved memory usage, less the scheduler<->worker race conditions that queuing also addressed.

This is the same thing @fjetter said in https://github.com/dask/distributed/pull/7526#issuecomment-1431346387:

> this lets me think that a major contributing factor to the success of queuing is in fact that we are breaking priority ordering in a very specific way

The `dask.order` code is quite complicated, so I don't know how we'd address this there. Maybe the `is_rootish` heuristic is good enough and it's not worth trying? It'd be nice to understand the underlying cause though. Maybe @eriknw has ideas?

**Comment by eriknw** [comment]
Great writeup @gjoseph92! Here are some quick reactions:

I'm interested in diving deeper to understand. I think this examples deserves a diagnostic treatment as done here: https://github.com/dask/dask/pull/7992#issuecomment-952436239. It would be great to also view these diagnostics plots with the `is_rootish` / queueing options enabled.

> "[...] if you look like a root task, you always run last"

We may be able to add such a rule to `dask.order`. I think it would be easy for me to add a `is_rootish`-like check, but we would need to guess a reasonable default value for `total_nthreads`. I don't know if adding this behavior would be good to do _in general_, so maybe a config option to control if it's found to sometimes help and sometimes hurt 🤷‍♂️?

I also suspect a different, simpler implementation of `dask.order` could handle many of the cases that suffer from over-subscribing root-ish tasks (but would be terrible for other graphs). Although I prefer to improve the default `dask.order` to handle known workflows, the code _is_ quite complicated and challenging to change safely, so I'm warming up to the idea of allowing `dask.order` to be changeable. Generic task ordering in linear-ish time is _hard_, and using heuristics will always perform poorly for some graphs.

I have also long-wondered what could be improved with a second pass in `dask.order`. I suspect it could improve many of the poorly-behaved graphs, but at the cost of doubling the execution time of `dask.order`. This would be a pretty expensive addition for something that doesn't improve _most_ graphs. OTOH, perhaps a second pass that used e.g. the output of `dask.order`, the number of workers, and threads per worker, could also help with task co-assignment (https://github.com/dask/distributed/issues/7555).

**Comment by RichardScottOZ** [comment]
And if there are a lot of these possibilities in your testing, could enough be fed to a neural network to make some suggestions or think up some possibilities after the requisite work?

**Comment by fjetter** [comment]
Reducing the above example further yields something easier to wield

```python
import dask.array as da
import numpy as np
import xarray as xr
from dask.utils import parse_bytes

data = da.random.random((5, 1), chunks=(1, 1))

arr = xr.DataArray(
    data,
    dims=["time", "x"],
    coords={"day": ("time", np.arange(5) % 2)},
)

clim = arr.groupby("day").mean(dim="time")
anom = arr.groupby("day") - clim
anom_mean = anom.mean(dim="time")

anom_mean.data.visualize(
    "anom-mean-order.png", color="order-age"
)
```
![anom-mean-order](https://github.com/dask/dask/assets/8629629/d486b048-e165-47cd-8ca1-c31c835cf6a0)

In this specific example, the ordering works until we reach `16`. Instead of computing `32` next which would release two tasks it is jumping right away to the next computation branch at the bottom right. This is forbidden by the distributed scheduler root-ish tasks s.t. the distributed scheduler reduces the computation as desired.

From what I can tell, larger examples show the same anti-pattern such that this is a nice minimal graph one can reason about.


The above example as a low level, raw dsk

<details>

```python
{
        ("d", 0, 0): (f, ("a", 0, 0), ("b1", 0, 0)),
        ("d", 1, 0): (f, ("a", 1, 0), ("b1", 1, 0)),
        ("d", 2, 0): (f, ("a", 2, 0), ("b1", 2, 0)),
        ("d", 3, 0): (f, ("a", 3, 0), ("b1", 3, 0)),
        ("d", 4, 0): (f, ("a", 4, 0), ("b1", 4, 0)),
        ("a", 0, 0): (f, f, "random_sample", None, (1, 1), [], {}),
        ("a", 1, 0): (f, f, "random_sample", None, (1, 1), [], {}),
        ("a", 2, 0): (f, f, "random_sample", None, (1, 1), [], {}),
        ("a", 3, 0): (f, f, "random_sample", None, (1, 1), [], {}),
        ("a", 4, 0): (f, f, "random_sample", None, (1, 1), [], {}),
        ("e", 0, 0): (f, ("g1", 0)),
        ("e", 1, 0): (f, ("g3", 0)),
        ("b0", 0, 0): (f, ("a", 0, 0)),
        ("b0", 1, 0): (f, ("a", 2, 0)),
        ("b0", 2, 0): (f, ("a", 4, 0)),
        ("c0", 0, 0): (f, ("b0", 0, 0)),
        ("c0", 1, 0): (f, ("b0", 1, 0)),
        ("c0", 2, 0): (f, ("b0", 2, 0)),
        ("g1", 0): (f, [("c0", 0, 0), ("c0", 1, 0), ("c0", 2, 0)]),
        ("b2", 0, 0): (f, ("a", 1, 0)),
        ("b2", 1, 0): (f, ("a", 3, 0)),
        ("c1", 0, 0): (f, ("b2", 0, 0)),
        ("c1", 1, 0): (f, ("b2", 1, 0)),
        ("g3", 0): (f, [("c1", 0, 0), ("c1", 1, 0)]),
        ("b1", 0, 0): (f, ("e", 0, 0)),
        ("b1", 1, 0): (f, ("e", 1, 0)),
        ("b1", 2, 0): (f, ("e", 0, 0)),
        ("b1", 3, 0): (f, ("e", 1, 0)),
        ("b1", 4, 0): (f, ("e", 0, 0)),
        ("c2", 0, 0): (f, ("d", 0, 0)),
        ("c2", 1, 0): (f, ("d", 1, 0)),
        ("c2", 2, 0): (f, ("d", 2, 0)),
        ("c2", 3, 0): (f, ("d", 3, 0)),
        ("c2", 4, 0): (f, ("d", 4, 0)),
        ("f", 0, 0): (f, [("c2", 0, 0), ("c2", 1, 0), ("c2", 2, 0), ("c2", 3, 0)]),
        ("f", 1, 0): (f, [("c2", 4, 0)]),
        ("g2", 0): (f, [("f", 0, 0), ("f", 1, 0)]),
    }
```
</details>

I'm currently doing a little time travel analysis and it looks like that historic versions didn't have this flaw (I only tested 0.17.2 so far)

**Comment by fjetter** [comment]
After https://github.com/dask/dask/pull/10535, the above example now looks like

![mydask](https://github.com/dask/dask/assets/8629629/69f80fd3-e158-4662-a3b3-1977f76bd082)
